### ISSUE TITLE
Error PHP in 'Associated items' tab of a contract

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#100]
0.90 (I didn't check 0.85)
Probably linked to corrections made for #93 
When adding an item to a contract, I get the following PHP error (itemtype may vary) between the choice of the itemtype (computer, monitor...) and the list of objects of this itemtype.
2015-09-05 10:38:24 [2@debian]
  *** PHP Notice(8): Undefined index: Computer
  Backtrace :
  ajax/dropdownAllItems.php:75    

To reproduce it, take a contract without any associated item, and whose 'max nbr of items' >= 2.
Add an item, let's say a Computer.
Then, (try to) add another itemtype, let's a Monitor -> PHP error.
No error when there is no associated item. No error when the 2nd item is of the same itemtype than the 1st.

**Comment by yllen** [comment]
I have fix this issue with #103

**Comment by blerohellec** [comment]
OK. Thx
