### ISSUE TITLE
Lock blocks post-only user to add followup

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1000]
When locking is enable in the configuration, it works as expected with a tech user, but no lock is set for post-only users.

pinf @tomolimo

**Comment by tomolimo** [comment]
That's by design, post-only users are not locking items, see #54  for more information about design of lock mechanism. Not sure if this was specifically explained.

**Comment by trasher** [comment]
Thank you.

As far as I can see, specific "post-only" case has not been discussed; so, should we add lock on post-only ? Thoughts?

**Comment by tomolimo** [comment]
Then that was forgotten from my side in the #54 issue.
But for me 'post-only' users are not concerned by the lock as they my add followups at any time. In our GLPi we prevent them from editing followups:

![image](https://cloud.githubusercontent.com/assets/7569958/18580745/9ef9a5b0-7bfd-11e6-9af9-64f9f66aa224.png)

As the only risk is when a 'post-only' user is going to edit its own followups, the risk of collision is really reduced, I propose to let this like that and to wait for feedbacks from the GLPi global use.

**Comment by trasher** [comment]
As far as I know, there actually are issues; the user will be denied to add a new followup.

I'll take a deeper look at all of this.

**Comment by tomolimo** [comment]
then if he is really denied from adding a followup: this is a bug, as by design he should be able as 'post-only' to add a followup, even if ticket is locked by a tech.

**Comment by flegastelois** [comment]
Hi @all,

I confirm that @trasher says, the user will be denied to add a new followup : 
https://share.teclib.net/data/public/8ae5d4

**Comment by trasher** [comment]
Thanks @flegastelois :) @tomolimo yes, sounds like a bug; I've edited ticket title, I'll try to fix. Thanks you for the clarifiactions.
