### ISSUE TITLE
Create ticket using /form/helpdesk.php for anonimous users

### ISSUE THREAD

**Issue by yordano91** [glpi-project/glpi#10004]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Create ticket through /form/helpdesk.php having activated the option in System - Support - allow creation of anonymous users gives the following error 

PHP Notice (8): Undefined index: _users_id_requester in /var/www/glpi/inc/ticket.class.php at line 1558
Uncaught Exception TypeError: Argument 1 passed to Ticket::canDelegateeCreateTicket() must be of the type int, null given, called in /var/www/glpi/inc/ticket.class.php on line 1558 in /var/www/glpi/inc/ticket.class.php at line 2428

### Relevant log output

```shell
in glpi/files/_log/php-errors.log

glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Ticket::canDelegateeCreateTicket() must be of the type integer, null given, called in /var/www/glpi/inc/ticket.class.php on line 1558 in /var/www/glpi/inc/ticket.class.php at line 2428
```

### Page URL

glpi/front/tracking.injector.php

### Steps To reproduce

1. Go to glpi/front/helpdesk.php
2. Write title and description
3. Click on "post"
4. redirect to glpi/front/tracking.injector.php
5. does nothing 
-page in blanc
-If you activate glpi in debug mode, the following error will appear:
PHP Notice (8): Undefined index: _users_id_requester in /var/www/glpi/inc/ticket.class.php at line 1558
Uncaught Exception TypeError: Argument 1 passed to Ticket::canDelegateeCreateTicket() must be of the type int, null given, called in /var/www/glpi/inc/ticket.class.php on line 1558 in /var/www/glpi/inc/ticket.class.php at line 2428

### Your GLPI setup information

GLPI 9.5.6 (/glpi => /var/www/glpi)
Installation mode: TARBALL

**Comment by ftoledo** [comment]
I confirm this issue

**Comment by ftoledo** [comment]
Possible solution: 

https://forum.glpi-project.org/viewtopic.php?id=280969
