### ISSUE TITLE
 Modification of the computing of time to own  (takeintoaccount_delay_stat)

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#1001]
Goal : Choose the action for the compute of time to own (takeintoaccount_delay_stat)

At this time, the delay is calculated during any modification in the ticket.

Action, I propose adding for the action for the compute of time to own:
- Ticket Change (Action that is currently used)
- Assigning a group ticket
- Assigning a technician Ticket
- Assignment of a technician / group ticket

Do you have any comments / suggestions?

**Comment by amma35** [comment]
An opinion ?

**Comment by MarcoMoraes** [comment]
I suggest using Assignment of a technician OR group to the ticket.
We are using this value to calculate some goals for IT Metrics.
Thank you
