### ISSUE TITLE
Error to send email notifications

### ISSUE THREAD

**Issue by breno404** [glpi-project/glpi#10015]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Any setting I put doesn't send email and gives an error, sometimes crashing processes

### Relevant log output

```shell
mail-error.log: Erro: Falha na conexão SMTP (). https://github.com/PHPMailer/PHPMailer/wiki/Trou troubleshooting

mail-debug.log: ERRO SMTP: Falha ao conectar ao servidor: Conexão recusada (111)
Falha na conexão SMTP (). https://github.com/PHPMailer/PHPMailer/wiki/Trou troubleshooting
```

**Comment by cconard96** [comment]
Please provide the full stack trace of this error, and please provide your GLPI system information from Setup > General on System tab.

**Comment by breno404** [comment]
I already managed to solve. Apparently it had more to do with the server than the application.
