### ISSUE TITLE
Modification of the SLA interface in the ticket

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#1002]
Goal : 
- Addition of an image to indicate if the SLA  is in progress, paused (status "waiting"), exceeded or finished.

SLA paused and progress : 
![sla1](https://cloud.githubusercontent.com/assets/15138371/18580338/59b177aa-7bfb-11e6-972b-ba44d8457565.jpg)

SLA exceeded : 
![sla2](https://cloud.githubusercontent.com/assets/15138371/18580341/5b5cf6a6-7bfb-11e6-97b1-4a3c89ab2c74.jpg)
- Adding the information of the time consumed time allocated

I send a pull request as soon as possible.

**Comment by Nerato** [comment]
Where is located the file and function that leaves the SLA stopped if the call is pending?
