### ISSUE TITLE
[GLPI 10] Simplified interface - The user can modify category & urgency on a opened ticket

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10045]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

On simplified interface - The user can modify category & urgency on a opened ticket (we cannot do that on 9.5.X)

![image](https://user-images.githubusercontent.com/13178158/145201915-79725a01-e27b-4c8c-aa74-c8c708d07368.png)

### Page URL

http://localhost/glpi/front/ticket.form.php?id=XX

**Comment by tsmr** [comment]
He can update items too
![image](https://user-images.githubusercontent.com/13178158/145202106-85eb69f8-8963-4f18-8531-648f59457356.png)

**Comment by cconard96** [comment]
It seems intentional that requesters can update certain parts of a ticket as long as the ticket isn't solved or closed and there are no followups or tasks.

**Comment by tsmr** [comment]
Ok no problem
