### ISSUE TITLE
[GLPI10] Simplified interface - Can see childs entities

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10043]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

In simplified interface, even with an no recursive profile, you'll see childs entities

![image](https://user-images.githubusercontent.com/13178158/145201376-bde97fad-5071-4997-99e3-021ca3fec897.png)

### Page URL

http://localhost/glpi/front/helpdesk.public.php

**Comment by cconard96** [comment]
I cannot recreate the issue.
I removed the recursive profile from the default post-only user and added the "Self Service" profile without recursion. User could only see the root entity and none of the children.
I tried adding a second profile (Observer) that was assigned recursively and I could see children entities only when the Observer profile was active.

**Comment by tsmr** [comment]
Hello Curtis

I checked on my side. In fact it is when you change profile that this happens.

You connect in self-service: Display OK
You change your profile to super-admin: OK
You change your profile again to Self-Service: KO: The list of entities displays all the entities.

I'm thinking a cache problem, right?

**Comment by tsmr** [comment]
Hello. Sorry but your patch doesn't resolve the issue

**Comment by tsmr** [comment]
Curtis in fact in ajax/entitytreesons.php if i comment : 

```
if (array_key_exists($subckey, $all_entitiestree)) {
    echo json_encode($all_entitiestree[$subckey]);
    exit;
}
```

It's good

**Comment by tsmr** [comment]
So it was a cache problem too i think
