### ISSUE TITLE
[GLPI 10] Php-errors on Show knowbase

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10053]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

```
[2021-12-08 13:14:26] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "knowbaseitemcategories_id" in C:\wamp64\www\glpi\inc\knowbaseitem.class.php at line 1699
  Backtrace :
  ajax\knowbase.php:47                               KnowbaseItem::showList()
```

### Page URL

http://localhost/glpi/front/knowbaseitem.php

**Comment by cconard96** [comment]
In GLPI 10, there shouldn't be a `knowbaseitem.class.php` file in the `inc` directory. Most of the PHP classes were moved to `src`. If the new code files were copied over an older GLPI instance, it is possible the old classes are being loaded.

**Comment by tsmr** [comment]
OK i haven't anymore this error. Sorry
