### ISSUE TITLE
[GLPI 10] Cannot click on results when search sub-entities

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10072]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

When you search a child entity, you cannot click on the result for change entity of GLPI

![image](https://user-images.githubusercontent.com/13178158/145398432-50f23806-01a1-4db3-9131-0ad111b30abc.png)

**Comment by Claonilton** [comment]
Let's go example:
Filterless: (Link created)
![image](https://user-images.githubusercontent.com/16517344/147565650-6c10b8b9-e59c-4ba9-a78d-40e760154cb9.png)

With filter: (The link not created)
![image](https://user-images.githubusercontent.com/16517344/147566083-c3c3183c-84cd-49e8-925a-13575c0973cc.png)

**Comment by tsmr** [comment]
corrected
