### ISSUE TITLE
[GLPI 10] display -1 value if no items linked to ticket

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10073]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

On a opened ticket,  the block display -1 value if no items linked to the ticket

![image](https://user-images.githubusercontent.com/13178158/145401009-88b58789-99ad-4f6b-8982-8372531f1e92.png)

### Page URL

http://localhost/glpi/front/ticket.form.php?id=XX

**Comment by tsmr** [comment]
I have checked this morning - with master.

I created a ticket & the simplified interface display the block with -1 badge

**Comment by cconard96** [comment]
I couldn't recreate this issue but I did notice a bunch of other issues with it.
Can you check to see if #10419 resolves this issue too?

**Comment by tsmr** [comment]
👍 with your PR it's ok for me :)
