### ISSUE TITLE
 Uncaught Exception ValueError: imagecreatetruecolor(): Argument #2 ($height) must be greater than 0

### ISSUE THREAD

**Issue by Riesuu** [glpi-project/glpi#10109]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Hello,
as indicated several times in other tickets, the php error gives me the following errors.
I use GLPI 9.5.6, with a mail collector. For the moment I have not yet had any bug.
I think this error is caused by the images in the signature of people, sometimes it blocks the collector completely, I have to find the mail and delete it.
[php-errors.log](https://github.com/glpi-project/glpi/files/7711290/php-errors.log)

**Comment by cedric-anne** [comment]
Hi,

This seems related to a particular image/document/ticket.

Could you provide more details about the context ?

Regards

**Comment by Riesuu** [comment]
Hello,
I strongly believe that this is a very small image that is problematic. As I had already mentioned in the #8795  and #9431
I have to find the problematic email, delete it, then everything works again.

**Comment by trasher** [comment]
Next time, please provide a cleaned log file, 11Mio is quite huge.

I do not see any flagrant issue reading the code; and do not really have a way to reproduce. As far as I see, height may be calculated, but there is no rounding or similar. Have the image a 0 height?
I have no idea how to replace the `imagecreatetruecolor()` call, or what value to set if it does not accept a 0 (if that can happen).

Is it possible the images you're talking about are kind of corrupted? If that's a collect issue, providing a .eml file we can add in tests suite to reproduce will be mandatory.

**Comment by Riesuu** [comment]
For me, I think the problem comes from the signature, I have this element that weighs almost nothing. Or, can we ignore the images of the collector? What is interesting in the signature is just the text containing the number
![image](https://user-images.githubusercontent.com/17006344/147076260-58ebfb6f-3e18-45cf-9764-a6f21931482e.png)

**Comment by cedric-anne** [comment]
Hi,

Please, provide the email that causes this issue. It is the easier way for us to reproduce your issue.

Regards

**Comment by cconard96** [comment]
@Riesuu can you test the changes made in #10318 to see if that resolves the issue for you?
