### ISSUE TITLE
9.5.6 Can't share dashboard anymore

### ISSUE THREAD

**Issue by Benoit221** [glpi-project/glpi#10128]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Since 9.5.6 update, people that use the shared assistant dashboard can't see it : 
![image](https://user-images.githubusercontent.com/56193156/146214762-a4288e4a-44be-4fa2-965c-9b1f96fe456c.png)
For all authenticated users, it's working : 
![image](https://user-images.githubusercontent.com/56193156/146215500-366ed680-e80c-4a03-8674-19f83e61d6a8.png)

I had already search the bdd for null date, but nothing.

### Your GLPI setup information

<html>
<body>

Operating system: Linux 19c34b1b1a65 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 PHP 7.4.23 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, ctype, curl, 	date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, 	pdo_mysql, pspell, session, sodium, standard, xml, xmlrpc, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.48 (Unix) (Apache/2.4.48 (Unix) Server at serviceinfo.hopital.local Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 Edg/96.0.1054.53 Server Software: mariadb.org binary distribution 	Server Version: 10.6.5-MariaDB-1:10.6.5+maria~focal 	Server SQL Mode:  	Parameters: glpi-user@db/glpi 	Host info: db via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.6.5) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/lib/glpi/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/_cron has been validated. Write access to /var/lib/glpi has been validated. Write access to /var/lib/glpi/_dumps has been validated. Write access to /var/lib/glpi/_graphs has been validated. Write access to /var/lib/glpi/_lock has been validated. Write access to /var/lib/glpi/_pictures has been validated. Write access to /var/lib/glpi/_plugins has been validated. Write access to /var/lib/glpi/_rss has been validated. Write access to /var/lib/glpi/_sessions has been validated. Write access to /var/lib/glpi/_tmp has been validated. Write access to /var/lib/glpi/_uploads has been validated. Write access to /var/www/glpi/marketplace has been validated.
--

GLPI_ROOT: /var/www/glpi GLPI_CONFIG_DIR: /etc/glpi GLPI_VAR_DIR: /var/lib/glpi GLPI_LOG_DIR: /var/log/glpi GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/lib/glpi GLPI_CACHE_DIR: /var/lib/glpi/_cache GLPI_CRON_DIR: /var/lib/glpi/_cron GLPI_DUMP_DIR: /var/lib/glpi/_dumps GLPI_GRAPH_DIR: /var/lib/glpi/_graphs GLPI_LOCAL_I18N_DIR: /var/lib/glpi/_locales GLPI_LOCK_DIR: /var/lib/glpi/_lock GLPI_PICTURE_DIR: /var/lib/glpi/_pictures GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/_plugins GLPI_RSS_DIR: /var/lib/glpi/_rss GLPI_SESSION_DIR: /var/lib/glpi/_sessions GLPI_TMP_DIR: /var/lib/glpi/_tmp GLPI_UPLOAD_DIR: /var/lib/glpi/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/glpi/locales GLPI_VERSION: 9.5.6 GLPI_SCHEMA_VERSION: 9.5.6 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php7)

</body>
</html>

**Comment by Benoit221** [comment]
Is there anyone who encountered the same ?

**Comment by cconard96** [comment]
Please include any relevant entries from GLPI logs `files/_log/php-errors.log` and `files/_log/sql-errors.log`, and in this case, any errors in your browser console too (F12 key and then Console tab).

**Comment by royken** [comment]
same issue here
