### ISSUE TITLE
[10.0.0] Modular ticket dashboard ?

### ISSUE THREAD

**Issue by ZeikoFr** [glpi-project/glpi#10131]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Maybe I'm missing the options in the setting but is it possible to change location of Tabs and ticket info ?

I would like tthe tabs to go above the ticket like this : 

![Screenshot_20211215_212835](https://user-images.githubusercontent.com/54892453/146262042-bd5d45d0-af64-4a22-8cf3-a87193eccc41.jpeg)

And if possible to reverse the location of the ticket info field (on the left instead of right like in a vertical split setup in glpi 9.5.6 ?

Is this possible of is the layout fixed ? (I liked the horizontal split/vertical split options)

**Comment by cconard96** [comment]
It is no longer possible to view tabs/forms in the "classic" or "vertical split" layouts anymore. The only layout option is the new one that determines if the navigation menu is on the left or along the top.

**Comment by ZeikoFr** [comment]
Thanks for the answer, well after a bit of time to adapt I hope that this layout will be nice to use
