### ISSUE TITLE
Non request sources

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1013]
Hello.
Duplicate the original message again.

After upgrading from RC1 9.1 to RC2 9.1 noticed that requests sources are no longer available. There is an issue with request types. Once they became inactive. When you try to activate them – push yes, save and nothing happens. Again inactive. 
Also when I tried to add a field to show active points – everything disappears. Looks like there were deleted or access denied to database.

P.S.
Remembered the problem appeared after you tried to add to the sources of requests, "global view" column display-"active"

**Comment by orthagh** [comment]
I just tested migration from 0.90, the request type are set correctly.
On your instance, please check that your requesttypes have theses values: 
- active: yes
- Request source visible for tickets : yes

You can set theses fields by massive action on the list

**Comment by gloomy-master** [comment]
Hello.
Checked on a test machine that installed RC2, by default. After downloading the database dump from the primary server to the test server, the problem manifested itself.

RC2 with default settings this is not a problem

**Comment by orthagh** [comment]
This kind of displays mean an sql error.

Please check the last timestamp of your files/_log/sql_errors.logs file to retrieve it and copy an extract here for understanding the issue.

Thanks

**Comment by gloomy-master** [comment]
located in/var/log log file mysql.log blank

mysqlquery.log  which is located in/var/log/mysql contains the following entries
[mysqlquery.txt](https://github.com/glpi-project/glpi/files/481842/mysqlquery.txt)

**Comment by orthagh** [comment]
Could you set your glpi in debug mode (you can change the mode in your top right preferences with a super-admin profile) and check if more errors displays.

Check also "Logs in files" parameter in Setup > General, system tab.

**Comment by gloomy-master** [comment]
When you attempt to create a new source of query
![glpi-bug2](https://cloud.githubusercontent.com/assets/21122546/18697587/15eed35c-7fdc-11e6-99d1-119f9ace8cbf.JPG)

**Comment by orthagh** [comment]
Your db schema is not up to date (due to migration between different version of RC)

Here is some queries you could do to fix this issue:

```sql
ALTER TABLE glpi_requesttypes
   ADD COLUMN `is_active` TINYINT(1) NOT NULL DEFAULT '1',
   ADD COLUMN `is_ticketheader` TINYINT(1) NOT NULL DEFAULT '1',
   ADD COLUMN `is_ticketfollowup` TINYINT(1) NOT NULL DEFAULT '1',
   ADD COLUMN `is_followup_default` TINYINT(1) NOT NULL DEFAULT '0',
   ADD COLUMN `is_mailfollowup_default` TINYINT(1) NOT NULL DEFAULT '0';
```

**Comment by gloomy-master** [comment]
Thanks, everything worked.
