### ISSUE TITLE
Planning - task view

### ISSUE THREAD

**Issue by 99net** [glpi-project/glpi#10139]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

Can not see any planned tasks on calendar. Not possible even add one.

**Comment by cconard96** [comment]
Are there any errors in the browser's console (F12 on most browsers)?

**Comment by 99net** [comment]
GLPI cannot see the scheduling no matter if you add a task manually in the calendar or create a scheduling via a ticket.

No errors.

**Comment by cconard96** [comment]
What profile are you trying to use?
I cannot recreate the issue with super-admin, but it look like the default Technician profile doesn't have the permission to create external events at least.

**Comment by 99net** [comment]
SuperAdmin. 
Permissions already checked. 
Same result on other profile like technician, with planning options checked on.

**Comment by stdglpi** [comment]
Same problem on my glpi.

**Comment by cconard96** [comment]
Can you check to see if the fix in #10355 resolves this issue for you too?

**Comment by 99net** [comment]
Better but still not complete. More on https://github.com/glpi-project/glpi/pull/10355
