### ISSUE TITLE
GLPI 10 Beta - Date field doesnt select on click

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10136]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

Hi,

i dont know if it is a bug but while clicking on date picker it doesnt select the date however you have to click outside the date picker to select it.

![image](https://user-images.githubusercontent.com/22425503/146316135-5cdfb819-80d1-4dcd-9375-f207cbc65222.png)

**Comment by cconard96** [comment]
This seems to be intentional with the flatpickr library so that you can change the date and time both without the picker closing immediately after selecting the date.
