### ISSUE TITLE
Followup propagation to ticket not working

### ISSUE THREAD

**Issue by 99net** [glpi-project/glpi#10142]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

On previous version there was an option to propagate followup to ticket. Not present on version 10.

![image](https://user-images.githubusercontent.com/43380069/146344435-dc0b7409-4f10-4d07-ab02-e76f7e78db62.png)

**Comment by cconard96** [comment]
The edit and "Promote to ticket" buttons were moved under a 3 dot menu. When you hover over the followup, this new menu should show up.

**Comment by 99net** [comment]
Can see only edit option.

![image](https://user-images.githubusercontent.com/43380069/146345615-af714574-7660-4c17-b74c-c7ceb4c5b95e.png)

**Comment by cconard96** [comment]
You image shows the ticket's description, not a task or followup.
You should only have the "Edit" option for the description.

**Comment by 99net** [comment]
All done. 

![image](https://user-images.githubusercontent.com/43380069/146348429-b4500c05-1080-4812-8962-54df708dfb01.png)
