### ISSUE TITLE
Ticket Resolve button not present

### ISSUE THREAD

**Issue by 99net** [glpi-project/glpi#10143]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

Resolve button not present, no resolve template available. 

![image](https://user-images.githubusercontent.com/43380069/146345783-f86b985b-20fc-4788-9ba9-60c438fa4a94.png)

**Comment by cconard96** [comment]
What resolve button are you referring to?

Is there something missing from the Solution form?

**Comment by 99net** [comment]
On v 9.5.6 Ive got "Solution" button. Found it already on v10, Close it please.

![image](https://user-images.githubusercontent.com/43380069/146805073-82ffff11-6f3c-4ba4-acc8-d06a66655410.png)

**Comment by 99net** [comment]
Done.
