### ISSUE TITLE
Mini dashboard for tickets

### ISSUE THREAD

**Issue by 99net** [glpi-project/glpi#10141]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Mini dashboard for tickets not visible. Settings done on general settings tab.

![image](https://user-images.githubusercontent.com/43380069/146344007-082ee409-c0d4-4f4b-89d1-c803ca0c5896.png)

![image](https://user-images.githubusercontent.com/43380069/146344050-4a21e580-c92b-4e56-a9b4-b7fcb6d6c35c.png)

**Comment by cconard96** [comment]
I was able to confirm the issue but haven't identified the cause yet.
As far as I can tell, the default mini dashboard isn't displayed in the dropdown list here at least.

**Comment by stdglpi** [comment]
Same problem on my instance.

**Comment by IO-github** [comment]
I have found a "solution"
In file /glpi/js/dashboard.js 
add this 
Dashboard.refreshDashboard();

at the line 112 after this

// init filters from storage
      Dashboard.initFilters();

For me it solve my problem

**Comment by stdglpi** [comment]
> I have found a "solution" In file /glpi/js/dashboard.js add this Dashboard.refreshDashboard();
> 
> at the line 112 after this
> 
> // init filters from storage Dashboard.initFilters();
> 
> For me it solve my problem

Thank you ! 

![image](https://user-images.githubusercontent.com/63521311/149951636-7803512b-d2bf-4e3c-a4a7-4188380ba5cd.png)

**Comment by 99net** [comment]
Thank You.

**Comment by IO-github** [comment]
I don't know.. I don't modify the dashboard directly in the tickets, I go through the dashboard in "Assistance/Dashboard" and I save.
If it can help you

**Comment by stdglpi** [comment]
@IO-github In fact I created a dashboard in the menu "Assistance/Dashboard" I saved it.
The dashboard appears correctly but when I go the to the menu "Tickets" the mini dashboard is BLANK.

In the "general" menu the settings looks good.
![image](https://user-images.githubusercontent.com/63521311/150498579-70f0739d-8095-421e-87a1-59948675d084.png)
