### ISSUE TITLE
[GLPI 10] Database link on menu

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10157]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

I think in the menu, GLPI should point to the DB instances and not to the databases itself, right?

There are more informations into glpi/front/databaseinstance.form.php?id=X than database.form.php?id=X

![image](https://user-images.githubusercontent.com/13178158/146423589-9c679fee-c797-4294-9729-85c87532c0be.png)

**Comment by orthagh** [comment]
I'm note sure.

For explanation 

- database instances almost (see below) matches softwares installed in the computer/vm like mysql server 8.1
- databases matches really the sql database like glpi one

Most of the use case will only use databases only, servers is a redundant information with softwares installed in computer (and found in the corresponding tab)
In the first implementation, we have also a "database server" to differenciate the software to the instance (ex one mysql server software but two instances launched on different ports 3306-3307) but for simplicity we dropped this super object.

This explains why we choose to set database object in first in the menu. This is the most used we though, and also the one inventoried by the new glpi agent.

**Comment by tsmr** [comment]
ok
