### ISSUE TITLE
[GLPI10] Network port list incomplete

### ISSUE THREAD

**Issue by OsamaDengler** [glpi-project/glpi#10159]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

I have a network switch with 300 ports but the list shows only the first 15 and I haven't found any means to scroll further down or paginate the list.

Also, when clicking on the wrench icon besides the number of ports heading ("Select default iitems to show"), nothing happens.

### Page URL

https://server.domain.local/glpi/front/networkequipment.form.php?id=134

### Steps To reproduce

1. GLPI 10.0.0 beta upgraded from latest 9.x version
2. Select network device under "assets"
3. Advance to the "network ports" view

### Your GLPI setup information

Information about system installation and configuration
--
 
GLPI 10.0.0-dev (/glpi => /var/www/html/glpi) Installation mode: TARBALL Current language:en_GB

Operating system: Linux server.domain.local 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, snmp, soap, 	sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="750M" safe_mode="" session.save_handler="files" 	upload_max_filesize="750M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at server.domain.local Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0 Server Software: (Ubuntu) 	Server Version: 8.0.27-0ubuntu0.20.04.1 	Server SQL Mode: NO_ENGINE_SUBSTITUTION 	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version (7.4.3) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. Database engine version (8.0.27) is supported. The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Web access to files directory is protected exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/glpi/marketplace has been validated. Timezones seems loaded in database.

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 10.0.0-dev GLPI_SCHEMA_VERSION: 10.0.0-dev@5d5ed159d30f08ffa4fb9065d7c3f64855d5d4e1 GLPI_MARKETPLACE_PRERELEASES: 1 GLPI_MIN_PHP: 7.4.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.5.3 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) mpdf/mpdf in (/var/www/html/glpi/vendor/mpdf/mpdf/src) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) psr/cache in (/var/www/html/glpi/vendor/psr/cache/src) league/csv in (/var/www/html/glpi/vendor/league/csv/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) symfony/cache in (/var/www/html/glpi/vendor/symfony/cache) html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src) symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler) twig/twig in (/var/www/html/glpi/vendor/twig/twig/src) twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Server: 'server.domain.local', Port: '3268', BaseDN: 'OU=Users,OU=Secret,DC=secret,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$)))', RootDN: 		'DOMAIN\ldap_glpi', Use TLS: none

Not active

Way of sending emails: PHP

</body>
</html>

**Comment by JuanmaSemesur** [comment]
/var/www/glpi/files/_log/php-errors.log

[2021-12-17 08:34:48] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getLink() on bool in /var/www/glpi/src/NetworkPort.php at line 1196
  Backtrace :
  src/NetworkPort.php:1037                           NetworkPort->getUnmanagedLink()
  src/NetworkPort.php:766                            NetworkPort->showPort()
  src/NetworkPort.php:1670                           NetworkPort::showForItem()
  src/CommonGLPI.php:687                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

**Comment by trasher** [comment]
As far as I understand, problem is there is a linked unmanaged equipment missing in data :/ How was this equipment created? Manually? From fusioninventory plugin?

**Comment by WebGregGit** [comment]
I installed version 10 for testing and noticed a similar symptom. 
For me, the ports were inventoried by the mix: fusioninventory and glpi agent. I did not link devices manually. 
Unfortunately, I will not write too much, because I am currently back to version 9.5.6.
I only confirm the symptoms.

**Comment by bbreton09** [comment]
I have same issue.
Migration from 9.5.6 to 10. Equipment created by fusioninventory + SNMP

[2021-12-29 23:46:04] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getLink() on bool in /var/www/html/src/NetworkPort.php at line 1196
  Backtrace :
  src/NetworkPort.php:1037                           NetworkPort->getUnmanagedLink()
  src/NetworkPort.php:766                            NetworkPort->showPort()
  src/NetworkPort.php:1670                           NetworkPort::showForItem()
  src/CommonGLPI.php:687                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

**Comment by bbreton09** [comment]
When i try to show unmanaged port http://glpi/front/networkport.form.php?id=250 i have this error

[2021-12-30 13:58:15] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'PluginFusioninventoryUnmanaged' not found in /var/www/html/src/NetworkPortConnectionLog.php at line 146
  Backtrace :
  src/NetworkPortConnectionLog.php:97                NetworkPortConnectionLog->showForItem()
  src/CommonGLPI.php:687                             NetworkPortConnectionLog::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

As i understand, glpi search to use Class PluginFusioninventoryUnmanaged but she do not existe because i user glpi-inventory.

**Comment by trasher** [comment]
> I found fiew value in database table who make reference to "PluginFusioninventoryUnmanaged"
> 
> glpi_ipaddresses glpi_logs glpi_networkports glpi_rulematchedlogs
> 
> Rename value "PluginFusioninventoryUnmanaged" in "Unmanaged" in glpi_networkports and glpi_networkports correct the port issue.

That is the issue, and renaming is indeed the fix. That's a migration issue from the plugin, not a GLPI one.

**Comment by trasher** [comment]
see https://github.com/glpi-project/glpi-inventory-plugin/issues/27

**Comment by trasher** [comment]
Please try with https://github.com/glpi-project/glpi-inventory-plugin/pull/29

In order to get the fix working, you have to drop all plugin tables, restore original ones and run plugin migration.

**Comment by bbreton09** [comment]
Sorry i can't restore backup from orginal because i do not have one ...

**Comment by trasher** [comment]
Huh... You updated to a beta without any backup? Probably not a good idea.

Anyways, the fix works only on data migration, modifying itemtype in database may be enough; but there are chances the `id` changed aswell.

**Comment by bbreton09** [comment]
> Huh... You updated to a beta without any backup? Probably not a good idea.
> 
> Anyways, the fix works only on data migration, modifying itemtype in database may be enough; but there are chances the `id` changed aswell.

I know it's a bad idea but is not in production environnement just a test in Beta10 and GlpiInventory.

**Comment by WebGregGit** [comment]
For me, the fastest solution was to delete the switch with devices and re-inventory SNMP (after prior import via the discovery job)
