### ISSUE TITLE
[GLPI10] Documentation on network inventory not intuitive

### ISSUE THREAD

**Issue by OsamaDengler** [glpi-project/glpi#10160]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

I've been migrating from latest 9.x to 10.0.0 beta and am about to replace FusionInventory with native GLPI inventory.

The devices have FusionInventory agents running and I've been able to push inventory data to GLPI using mod_rewrite.

However, despite reading the documentation on https://glpi-project.org/glpi-10-native-inventory/ I don't understand how to assign SNMP credentials to a network device and enable network inventory / discovery.

I have agents running and entered the SNMP credentials but am missing the link between credentials and assets.

Is there any additional documentation available?

### Steps To reproduce

1. Read https://glpi-project.org/glpi-10-native-inventory/
2. Do not know how to assign SNMP credentials to assets and/or agents and enable network discovery

**Comment by g-bougard** [comment]
Hi @OsamaDengler 
SNMP Credentials are managed in the core of GLPI from the "Administration" -> "Inventory" panel. You should see a "SNMP Credentials" button at the top.
After you have created your credentials, you should be able to see them in the related dropdown when setting up an IP range.

**Comment by trasher** [comment]
Also, it seems there is an issue preventing the display of network inventory/discovery tasks when adding a job. It's been fixed in master branch already (or should be very soon).
