### ISSUE TITLE
[Improvement][Ticket] Convert task to follow and vice-versa

### ISSUE THREAD

**Issue by sulian** [glpi-project/glpi#1016]
Hello

Can you add an option to convert a task in a follow in the ticket tracking system ? Often another operator made this kind of mistake (write a task instead of follow) and we cannot fix it.

Thanks

**Comment by tomolimo** [comment]
Hello,
Could you post new ideas/requests there: [http://glpi.userecho.com/](http://glpi.userecho.com/)?
Thank you,
Regards,
Tomolimo
