### ISSUE TITLE
GLPI 10 Beta - PHP errors 

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10171]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

Hi..

i upgraded from 9.5.6 to 10 Beta, however im facing the below issues.

1. Debug mode is enabled and i can not disable it. i can not see any user preferences and logout option.
![image](https://user-images.githubusercontent.com/22425503/146674674-220bc951-ffdc-4423-8474-f93650086c5b.png)

2. PHP Warning (2): Undefined array key "users_id" in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 561 on all dashboards.
![image](https://user-images.githubusercontent.com/22425503/146674702-e690d9fa-a444-49af-b1ee-9e47e80cebd2.png)

3. PHP User Warning (512): Unable to decrypt string. It may have been crypted with another key. in /var/www/html/glpi/src/GLPIKey.php at line 426 while importing / synchronizing users from LDAP.
![image](https://user-images.githubusercontent.com/22425503/146674643-53123741-20e2-4ae8-9aed-d49efab64e87.png)

**Comment by roshanroche** [comment]
PHP 8.0.13

Operating system: Linux 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64
PHP 8.0.13 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, mysql,
mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader,
xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="10M"
Software: Apache/2.4.37 (centos) OpenSSL/1.1.1k ()
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Server Software: MariaDB Server
Server Version: 10.4.12-MariaDB
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
Parameters: glpi@127.0.0.1/glpi
Host info: 127.0.0.1 via TCP/IP

PHP version (8.0.13) is supported.PHP version (8.0.13) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.4.12) is supported.Database engine version (10.4.12) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cconard96** [comment]
Can you verify your DB was updated properly with:
`bin/console glpi:database:check_schema_integrity`

**Comment by roshanroche** [comment]
Hi @cconard96 

output of the command for all tables it shows " tables schema differs for table "

![image](https://user-images.githubusercontent.com/22425503/146709292-ec7310bb-5015-45ac-9e3b-d3ffe3a61583.png)

**Comment by cedric-anne** [comment]
Hi @roshanroche 

Please run again the command using following options: `bin/console glpi:database:check_schema_integrity  --ignore-timestamps-migration --ignore-dynamic-row-format-migration --ignore-utf8mb4-migration`. This will permit to detect only missing fields.

Regards

**Comment by cconard96** [comment]
@roshanroche Were you able to re-run the database schema check command?

**Comment by cconard96** [comment]
No feedback for a while. I'll close this for now.
