### ISSUE TITLE
GPLI 10 Beta - SQL Error while migrating utf8mb4

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10175]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

Hi..

while migrating tables to utf8mb4 following SQL errors are thrown 

![image](https://user-images.githubusercontent.com/22425503/146709730-e9314629-d868-4bd1-9c94-2138ea46fe56.png)

![image](https://user-images.githubusercontent.com/22425503/146709761-3854f708-4280-4496-ada1-8601d643d28a.png)

![image](https://user-images.githubusercontent.com/22425503/146709781-ca3407f3-2533-47bc-93d5-0203045cd21e.png)

![image](https://user-images.githubusercontent.com/22425503/146709801-1f981b83-5b54-41b4-bfe3-50ff096056b8.png)

![image](https://user-images.githubusercontent.com/22425503/146709832-1c736409-8108-47e1-b1a9-86cc6fb9df6f.png)

Operating system: Linux 4.18.0-305.12.1.el8_4.x86_64 #1 SMP Wed Aug 11 01:59:55 UTC 2021 x86_64
PHP 8.0.13 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, mysql,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.37 (centos) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.12-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by cconard96** [comment]
It looks like you reached the `wait_timeout` period for MariaDB or some other timeout.
I believe it is only a minute by default, and changing to utf8mb4 can take some time depending on the size of the database.
You can try running the migration again to convert the rest of the tables or at least another batch.

**Comment by roshanroche** [comment]
Hi @cconard96 

i tried again same error

![image](https://user-images.githubusercontent.com/22425503/146747881-209a4497-c53b-4284-a796-140203d4d4ae.png)

**Comment by trasher** [comment]
Check mysql logs to see if there is anything. It seems down/in timeout.
Is your database huge? 
Did you try again with from a verbatim backup of the original database? (remember to drop all existing tables before restoring a backup).

**Comment by cedric-anne** [comment]
Hi,

You may have an issue with your database integrity, or maybe your filesystem has not enough free space to do these operations. Yous should indeed look inside your database logs.
GLPI is just sending a simple `ALTER TABLE` query, which may be long, but should not fail as it is a valid.

As it cannot be handled on GLPI side, I close this issue.

Regards

**Comment by roshanroche** [comment]
Hi @trasher @cconard96 @cedric-anne 

no matter what only the last 50 tables are throwing this error when i run the script. even when i run the script 2nd time only for these 50 tables i get the same issue.

if i run alter command individually for these 50 tables one by one , they seems to migrate. so what could be the issue?

**Comment by roshanroche** [comment]
Hi @trasher @cconard96 @cedric-anne 

the issue seems to be a bug in mariadb version 10.4.12 upgrading it to 10.4.24 solved the issue.

thank you
