### ISSUE TITLE
GLPI 10 Domains

### ISSUE THREAD

**Issue by JuanmaSMS** [glpi-project/glpi#10189]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10

### Bug description

In management / domains there are missing fields such as expiration date, creation date, type, responsible technician ...
Where can I change these fields?

![image](https://user-images.githubusercontent.com/38129485/146896351-5df47a54-d00a-497a-b9c4-afd1609ad5ce.png)

![image](https://user-images.githubusercontent.com/38129485/146896597-d2d95f1d-5ccd-4c05-890d-2487cc012b8b.png)

**Comment by trasher** [comment]
Fixed see #10193
