### ISSUE TITLE
[GLPI 10] No icon for plugins on simplified interface

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10184]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

There is no icon hook for plugins on simplified interface

![image](https://user-images.githubusercontent.com/13178158/146787382-3c7f9674-8551-4a64-a1fe-c013ef28a08e.png)

I can do a PR with a new hook "helpdesk_menu_entry_icon" ? 

```
diff --git a/src/Html.php b/src/Html.php
index 96c7c346c9..f0882d4a68 100644
--- a/src/Html.php
+++ b/src/Html.php
@@ -1885,6 +1886,9 @@ HTML;
                     if (is_string($PLUGIN_HOOKS["helpdesk_menu_entry"][$plugin])) {
                         $link = $PLUGIN_HOOKS["helpdesk_menu_entry"][$plugin];
                     }
+                    if (isset($PLUGIN_HOOKS["helpdesk_menu_entry_icon"][$plugin])) {
+                      $infos['icon'] = $PLUGIN_HOOKS["helpdesk_menu_entry_icon"][$plugin];
+                    }
                     $infos['page'] = $link;
                     $infos['title'] = $infos['name'];
                     $menu['plugins']['content'][$plugin] = $infos;

```

### Page URL

http://localhost/glpi/front/helpdesk.public.php

**Comment by orthagh** [comment]
Yes you can submit the pr.
Don't forget to do also a pr for the empty plugin and in docdev

**Comment by tsmr** [comment]
Thanks for your job curtis
