### ISSUE TITLE
Dropdown User : Load dropdown with many items in search engine

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1018]
Like issue : Load dropdown with many items in search engine #28

In GLPI 0.90.5 there is the same problem for user dropdown.

Example : into ticket lists

![image](https://cloud.githubusercontent.com/assets/13178158/18665005/6cc635d8-7f25-11e6-8579-d5442ef650f1.png)

**Comment by orthagh** [comment]
Could you see if the #907 pr matches your issue ?

**Comment by tsmr** [comment]
Yes i confirm
