### ISSUE TITLE
[GLPI 10] (Feature request) hide task on planning when the ticket is solved

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi#10188]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10 Beta 1

### Bug description

Hi everyone,

i would like to know if it's possible to have the possibility when we plan a task in a ticket to hide them when it's done or if the ticket is solved ? 

I had imagined a checkbox (already check automatically) with the text "hide this task once solved" directly when we add a task in ticket and after have clic on "Plan this task".

Do you think that is possible ? Someone have the same need as me to not overload the agendas ?

Thank in advance.

### Page URL

$SRV/glpi/front/ticket.form.php

### Steps To reproduce

1. Create a ticket
2. Create a task in ticket
3. clic on "Plan this task"
4. Have the possibility to hide or not the task once is done or if the ticket is solved.

**Comment by ASLLR** [comment]
Hi @cconard96, this feature is included in the GLPI 10 RC ? that could be cool :)

Best Regards,

**Comment by cconard96** [comment]
Please open a topic to discuss with community about this enhancement on [suggestion website](https://glpi.userecho.com/).
