### ISSUE TITLE
No oberserved ticket in group view

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1019]
We selected group as watcher. My user is in this group but in group view i don't see observed tickets.

**Comment by orthagh** [comment]
Hello @Armin83.

Could you precise your glpi version please ?

**Comment by Armin83** [comment]
GLPI 0.90.3 or 9.1 RC nightly tarball from last week

**Comment by Armin83** [comment]
> 17 Queries took 0.004s
N° 	Queries	Time	Errors
1	SELECT DISTINCT `glpi_tickets`.`id`
FROM `glpi_tickets`
LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`)
WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_groups_tickets`.`groups_id` IN ('1','5','14') AND `glpi_groups_tickets`.`type` = '2') ) AND (`status` IN ('2','3'))
ORDER BY `glpi_tickets`.`date_mod` DESC	0.001	 
2	SELECT DISTINCT `glpi_tickets`.`id`
FROM `glpi_tickets`
LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`)
WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_groups_tickets`.`groups_id` IN ('1','5','14') AND `glpi_groups_tickets`.`type` = '2') ) AND (`status` IN ('2','3'))
ORDER BY `glpi_tickets`.`date_mod` DESC LIMIT 0,5	0.001	 
3	SELECT `glpi_tickets`.*
FROM `glpi_tickets`
WHERE `glpi_tickets`.`id` = '2085' LIMIT 1	0.000	 
4	SELECT `glpi_groups_tickets`.*
FROM `glpi_groups_tickets`
WHERE `tickets_id` = '2085'	0.000	 
5	SELECT `glpi_tickets_users`.*
FROM `glpi_tickets_users`
WHERE `tickets_id` = '2085'	0.000	 
6	SELECT `glpi_suppliers_tickets`.*
FROM `glpi_suppliers_tickets`
WHERE `tickets_id` = '2085'	0.000	 
7	SELECT *
FROM `glpi_items_tickets`
WHERE `tickets_id` = 2085	0.000	 
8	SELECT `glpi_printers`.*
FROM `glpi_printers`
WHERE `glpi_printers`.`id` = '463' LIMIT 1	0.000	 
9	SELECT *
FROM `glpi_users`
WHERE `id` = '30'	0.000	 
10	SELECT *
FROM `glpi_useremails`
WHERE `users_id` = '30' AND `is_default` = '1'	0.000	 
11	SELECT `glpi_usertitles`.*, '' AS transname, '' AS transcomment
FROM `glpi_usertitles`
WHERE `glpi_usertitles`.`id` = '16'	0.000	 
12	SELECT COUNT(*)
FROM `glpi_ticketfollowups`
WHERE `tickets_id` = '2085' 	0.000	 
13	SELECT COUNT(*)
FROM `glpi_tickettasks`
WHERE `tickets_id` = '2085' 	0.000	 
14	SELECT DISTINCT `glpi_problems`.`id`
FROM `glpi_problems`
LEFT JOIN `glpi_problems_users` ON (`glpi_problems`.`id` = `glpi_problems_users`.`problems_id`)
LEFT JOIN `glpi_groups_problems` ON (`glpi_problems`.`id` = `glpi_groups_problems`.`problems_id`)
WHERE `glpi_problems`.`is_deleted` = 0 AND ( (`glpi_groups_problems`.`groups_id` IN ('1','5','14') AND `glpi_groups_problems`.`type` = '2')) AND (`status` IN ('3','2'))
ORDER BY date_mod DESC	0.000	 
15	SELECT DISTINCT `glpi_problems`.`id`
FROM `glpi_problems`
LEFT JOIN `glpi_problems_users` ON (`glpi_problems`.`id` = `glpi_problems_users`.`problems_id`)
LEFT JOIN `glpi_groups_problems` ON (`glpi_problems`.`id` = `glpi_groups_problems`.`problems_id`)
WHERE `glpi_problems`.`is_deleted` = 0 AND ( (`glpi_groups_problems`.`groups_id` IN ('1','5','14') AND `glpi_groups_problems`.`type` = '2')) AND (`status` IN ('3','2'))
ORDER BY date_mod DESC LIMIT 0,5	0.000	 
16	SELECT DISTINCT `glpi_tickets`.`id`
FROM `glpi_tickets`
LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`)
WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_groups_tickets`.`groups_id` IN ('1','5','14') AND `glpi_groups_tickets`.`type` = '2')) AND `status` = '4'
ORDER BY `glpi_tickets`.`date_mod` DESC	0.001	 
17	SELECT DISTINCT `glpi_tickets`.`id`
FROM `glpi_tickets`
LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`)
WHERE `glpi_tickets`.`is_deleted` = 0 AND ( (`glpi_groups_tickets`.`groups_id` IN ('1','5','14') AND `glpi_groups_tickets`.`type` = '2')) AND `status` = '4'
ORDER BY `glpi_tickets`.`date_mod` DESC LIMIT 0,5

**Comment by Armin83** [comment]
This is from 9.1 tarball.
I see one ticket but this is assigned one. If i search for ticket (watcher group = my groups, state = not solved) i find 4 tickets.

**Comment by orthagh** [comment]
Hello @Armin83 

Could you check the missing tickets are not in assignment part.
The code for observed tickets exclude tickets assigned to your user.
See: https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L4612-L4620

**Comment by Armin83** [comment]
Hello @orthagh 

i or my groups are not assigned or created that tickets.
The group is only watcher.

**Comment by Armin83** [comment]
Resolved
My configuration was wrong.
I see the ticket becouse my user right.
I think group view checks for group watching only group rights and this right was missing

Home -->
     Administration-->
           Profiles -->
            Assistance ------> See Group ticket
