### ISSUE TITLE
rss feed error (9.1 nightly tarball)

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1020]
on configuration page 

PHP Notice: Use of undefined constant CURLOPT_PROXY - assumed 'CURLOPT_PROXY' in /var/www/glpi/inc/rssfeed.class.php at line 860
PHP Notice: Use of undefined constant CURLOPT_PROXYPORT - assumed 'CURLOPT_PROXYPORT' in /var/www/glpi/inc/rssfeed.class.php at line 861
PHP Warning: gzinflate(): data error in /var/www/glpi/vendor/simplepie/simplepie/library/SimplePie/gzdecode.php at line 337

**Comment by Armin83** [comment]
Operating system: Linux testsystem-glpi 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:12:08 UTC 2015 i686
PHP 5.5.9-1ubuntu4.13 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, ldap, libxml, mbstring,
	mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at 10.1.82.225 Port 80)
	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
Server Software: (Ubuntu)
	Server Version: 5.5.44-0ubuntu0.14.04.1
	Server SQL Mode: 
	Parameters: glpidbuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

**Comment by trasher** [comment]
Hello,

I guess the curl php extension is not installed on your system. Could you please install it, restart your webserver and see it that solves your issue?

**Comment by Armin83** [comment]
okay you are right now i get this error "Error retrieving RSS feed" ;) but our mediawiki version is very old. (but on glpi 0.90.3 it works)
curl is now displayed in general -> system but at installation time i don't get a warning that curl is now installed.

**Comment by Armin83** [comment]
oh my fault - i see you refrenced für check for curl extension 👍
