### ISSUE TITLE
Can't create new user

### ISSUE THREAD

**Issue by jniusprime** [glpi-project/glpi#10217]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

When I access the form to create a new user, this error shows (with debug ON)

![image](https://user-images.githubusercontent.com/58817059/147304138-2097b74e-a86a-42cc-a48c-031eb0e2c965.png)
_the rest of the form is empty_

Uncaught Exception TypeError: User::getPictureForUser(): Argument #1 ($ID) must be of type int, string given, called in src/User.php on line 6173 in src/User.php at line 6204

### Relevant log output

```shell
sql-errors.log:
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: User::getPictureForUser(): Argument #1 ($ID) must be of type int, string given, called in src/User.php on line 6173 in src/User.php at line 6204
  Backtrace :
  src/User.php:6173                                  User->getPictureForUser()
  src/User.php:2240                                  User->showSystemUserForm()
  src/CommonGLPI.php:655                             User->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

bin/console glpi:database:check_schema_integrity:
Database schema is OK.
```

### Page URL

front/user.form.php

### Steps To reproduce

1. Open the form to create a new user

### Your GLPI setup information

Information about system installation & configuration

GLPI 10.0.0-dev ( => )
Installation mode: TARBALL
Current language:en_US

Server

 
Operating system: Linux itcazdc-itc-3 5.11.0-1022-azure #23~20.04.1-Ubuntu SMP Fri Nov 19 10:20:52 UTC 2021 x86_64
PHP 8.0.14 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.18.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Server Software: Ubuntu 20.04
	Server Version: 10.3.32-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi2@localhost/glpi2
	Host info: Localhost via UNIX socket
	
PHP version (8.0.14) is supported.PHP version (8.0.14) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.3.32) is supported.Database engine version (10.3.32) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /files/_cache has been validated. Write access to /config has been validated. Write access to /files/_cron has been validated. Write access to /files has been validated. Write access to /files/_dumps has been validated. Write access to /files/_graphs has been validated. Write access to /files/_lock has been validated. Write access to /files/_pictures has been validated. Write access to /files/_plugins has been validated. Write access to /files/_rss has been validated. Write access to /files/_sessions has been validated. Write access to /files/_tmp has been validated. Write access to /files/_uploads has been validated.Write access to /files/_cache has been validated.
Write access to /config has been validated.
Write access to /files/_cron has been validated.
Write access to /files has been validated.
Write access to /files/_dumps has been validated.
Write access to /files/_graphs has been validated.
Write access to /files/_lock has been validated.
Write access to /files/_pictures has been validated.
Write access to /files/_plugins has been validated.
Write access to /files/_rss has been validated.
Write access to /files/_sessions has been validated.
Write access to /files/_tmp has been validated.
Write access to /files/_uploads has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /marketplace has been validated.Write access to /marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

GLPI constants

 
GLPI_ROOT: 
GLPI_CONFIG_DIR: /config
GLPI_VAR_DIR: /files
GLPI_MARKETPLACE_DIR: /marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_DOC_DIR: /files
GLPI_CACHE_DIR: /files/_cache
GLPI_CRON_DIR: /files/_cron
GLPI_DUMP_DIR: /files/_dumps
GLPI_GRAPH_DIR: /files/_graphs
GLPI_LOCAL_I18N_DIR: /files/_locales
GLPI_LOCK_DIR: /files/_lock
GLPI_LOG_DIR: /files/_log
GLPI_PICTURE_DIR: /files/_pictures
GLPI_PLUGIN_DOC_DIR: /files/_plugins
GLPI_RSS_DIR: /files/_rss
GLPI_SESSION_DIR: /files/_sessions
GLPI_TMP_DIR: /files/_tmp
GLPI_UPLOAD_DIR: /files/_uploads
GLPI_INVENTORY_DIR: /files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /locales
GLPI_VERSION: 10.0.0-dev
GLPI_SCHEMA_VERSION: 10.0.0-dev@5d5ed159d30f08ffa4fb9065d7c3f64855d5d4e1
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_YEAR: 2021

Libraries

 
htmlawed/htmlawed version 1.2.6 in (/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/vendor/michelf/php-markdown/Michelf)
true/punycode in (/vendor/true/punycode/src)
iamcal/lib_autolink in (/vendor/iamcal/lib_autolink)
sabre/dav in (/vendor/sabre/dav/lib/DAV)
sabre/http in (/vendor/sabre/http/lib)
sabre/uri in (/vendor/sabre/uri/lib)
sabre/vobject in (/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/vendor/sebastian/diff/src)
elvanto/litemoji in (/vendor/elvanto/litemoji/src)
symfony/console in (/vendor/symfony/console)
scssphp/scssphp in (/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/vendor/ramsey/uuid/src)
psr/log in (/vendor/psr/log/Psr/Log)
psr/simple-cache in (/vendor/psr/simple-cache/src)
psr/cache in (/vendor/psr/cache/src)
league/csv in (/vendor/league/csv/src)
mexitek/phpcolors in (/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/vendor/paragonie/sodium_compat/src)
symfony/cache in (/vendor/symfony/cache)
html2text/html2text in (/vendor/html2text/html2text/src)
symfony/dom-crawler in (/vendor/symfony/dom-crawler)
twig/twig in (/vendor/twig/twig/src)
twig/string-extra in (/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found

SQL replicas

 
Not active

Notifications

 
Way of sending emails: PHP

Mails receivers

 

Plugins list

### Anything else?

It's a new install, new VM, empty DB

**Comment by cconard96** [comment]
Fixed by #10151
