### ISSUE TITLE
LDAP not working for Google Workspace LDAP

### ISSUE THREAD

**Issue by h33raj** [glpi-project/glpi#10218]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.6

### Bug description

I have tried the Google LDAP to connect with GLPI not working, Anyone has tried it before?

**Comment by flegastelois** [comment]
Hi,

GLPI 9.5.6 is not compatible with LDAPS Google Workspace (who needs TLS certificate / key authentication), it's a GLP 10 feature!

https://github.com/glpi-project/glpi/pull/8748

Kind regards,

**Comment by h33raj** [comment]
So just a question, if I upgrade to 10 this will work?

**Comment by flegastelois** [comment]
Do not upgrade to GLPI 10 until stable version is released ;)

But yes, LDAPS with TLS Cert/Key authentification will work, after correctly configure these options.

![image](https://user-images.githubusercontent.com/470612/147348901-9e6a060c-32ad-4828-aef7-2133bde9f723.png)

**Comment by h33raj** [comment]
Thank you so much for the fast. I really appreciate the help.

One more question, sorry to bother you. Since Google LDAP is not working. It is possible to do a bulk user upload to GLPI

**Comment by h33raj** [comment]
I wanted to import all company employees to the platform thanks

**Comment by flegastelois** [comment]
Hi,

The best solution is to use LDAP, you just have to wait a few months ...

If you had [GLPI Network subscription](https://services.glpi-network.com), the team can provide you 9.5 package with Google LDAPS feature.

Kind regards,

**Comment by Megachip** [comment]
Is it working with ldap.google.com? It worked for me till 03rd of august. Than it stopped. Maybe google changed something. I've seen that synology reporting not reachable on both ports 636 and 389, but it worked. Not sure if glpi implements any prechecks?
