### ISSUE TITLE
GLPI 10 Error Sync LDAP

### ISSUE THREAD

**Issue by JuanmaSMS** [glpi-project/glpi#10211]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10

### Bug description

I am trying to sync users through LDAP and it fails (administracion/usuarios/enlace a directorio LDAP).

I have done another test, when on the users page I mark a user and force sync I get this error.

[2021-12-23 11:56:39] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Something went wrong searching in LDAP directory in /var/www/glpi/src/AuthLDAP.php at line 3345
  Backtrace :
  src/AuthLDAP.php:2732                              AuthLDAP::searchUserDn()
  src/AuthLDAP.php:2659                              AuthLDAP::ldapImportUserByServerId()
  src/User.php:3301                                  AuthLDAP::forceOneUserSynchronization()
  src/MassiveAction.php:1168                         User::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1146                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()

The configuration I have is the same as it had in version 9.5 and it worked correctly.

**Comment by orthagh** [comment]
duplicate #10135
