### ISSUE TITLE
Import from file, upload XML, produces Uncaught Exception RuntimeException

### ISSUE THREAD

**Issue by tomway** [glpi-project/glpi#10215]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

While attempting to upload a XML file generated by fusion inventory agent... error occurs (Uncaught Exception RuntimeException) . Tried several XML files, all produced same error. XML file works successfully in previous versions of GLPI using fusioninventory plugin.

### Relevant log output

```shell
Uncaught Exception RuntimeException: Array ( [0] => JSON does not validate. Violations: Additional properties not allowed: services at #->$ref[file~2///var/www/glpi-10.0.0/vendor/glpi-project/inventory_format/inventory.schema.json]->properties:content ) in /var/www/glpi-10.0.0/src/Inventory/Inventory.php at line 209
```

### Steps To reproduce

Go to Import from file under Inventory and try uploading a XML file previously generated by fusion inventory.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.0-dev ( => /var/www/glpi-10.0.0)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux localhost.localdomain 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 15 20:49:28 UTC 2021 x86_64
PHP 7.4.19 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, oci8,
	openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.37 (rocky) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.6.5-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (7.4.19) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.6.5) is supported.
The log file has been created successfully.
Write access to /var/www/glpi-10.0.0/files/_cache has been validated.
Write access to /var/www/glpi-10.0.0/config has been validated.
Write access to /var/www/glpi-10.0.0/files/_cron has been validated.
Write access to /var/www/glpi-10.0.0/files has been validated.
Write access to /var/www/glpi-10.0.0/files/_dumps has been validated.
Write access to /var/www/glpi-10.0.0/files/_graphs has been validated.
Write access to /var/www/glpi-10.0.0/files/_lock has been validated.
Write access to /var/www/glpi-10.0.0/files/_pictures has been validated.
Write access to /var/www/glpi-10.0.0/files/_plugins has been validated.
Write access to /var/www/glpi-10.0.0/files/_rss has been validated.
Write access to /var/www/glpi-10.0.0/files/_sessions has been validated.
Write access to /var/www/glpi-10.0.0/files/_tmp has been validated.
Write access to /var/www/glpi-10.0.0/files/_uploads has been validated.
Web access to files directory is protected
SELinux configuration is OK.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi-10.0.0/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi-10.0.0
GLPI_CONFIG_DIR: /var/www/glpi-10.0.0/config
GLPI_VAR_DIR: /var/www/glpi-10.0.0/files
GLPI_MARKETPLACE_DIR: /var/www/glpi-10.0.0/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_DOC_DIR: /var/www/glpi-10.0.0/files
GLPI_CACHE_DIR: /var/www/glpi-10.0.0/files/_cache
GLPI_CRON_DIR: /var/www/glpi-10.0.0/files/_cron
GLPI_DUMP_DIR: /var/www/glpi-10.0.0/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi-10.0.0/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi-10.0.0/files/_locales
GLPI_LOCK_DIR: /var/www/glpi-10.0.0/files/_lock
GLPI_LOG_DIR: /var/www/glpi-10.0.0/files/_log
GLPI_PICTURE_DIR: /var/www/glpi-10.0.0/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi-10.0.0/files/_plugins
GLPI_RSS_DIR: /var/www/glpi-10.0.0/files/_rss
GLPI_SESSION_DIR: /var/www/glpi-10.0.0/files/_sessions
GLPI_TMP_DIR: /var/www/glpi-10.0.0/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi-10.0.0/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi-10.0.0/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi-10.0.0/locales
GLPI_VERSION: 10.0.0-dev
GLPI_SCHEMA_VERSION: 10.0.0-dev@5d5ed159d30f08ffa4fb9065d7c3f64855d5d4e1
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_YEAR: 2021

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/glpi-10.0.0/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/var/www/glpi-10.0.0/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/glpi-10.0.0/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/glpi-10.0.0/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/glpi-10.0.0/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi-10.0.0/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi-10.0.0/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi-10.0.0/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi-10.0.0/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi-10.0.0/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi-10.0.0/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi-10.0.0/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi-10.0.0/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi-10.0.0/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi-10.0.0/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi-10.0.0/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi-10.0.0/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi-10.0.0/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi-10.0.0/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi-10.0.0/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi-10.0.0/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi-10.0.0/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi-10.0.0/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi-10.0.0/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi-10.0.0/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi-10.0.0/vendor/psr/cache/src)
league/csv in (/var/www/glpi-10.0.0/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi-10.0.0/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi-10.0.0/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi-10.0.0/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi-10.0.0/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi-10.0.0/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi-10.0.0/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi-10.0.0/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi-10.0.0/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/glpi-10.0.0/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi-10.0.0/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi-10.0.0/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi-10.0.0/vendor/symfony/polyfill-php80)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

**Comment by tomway** [comment]
Additional testing using the GLPI Agent also resulted in the error: 
Uncaught Exception RuntimeException: Array ( [0] => JSON does not validate. Violations: Integer expected, "96" received at #->$ref[file~2///var/www/glpi-10.0.0/vendor/glpi-project/inventory_format/inventory.schema.json]->properties:content->properties:versionprovider->properties:etime ) in /var/www/glpi-10.0.0/src/Inventory/Inventory.php at line 209

**Comment by tomway** [comment]
JSON file import also fails with: 
Uncaught Exception RuntimeException: Array ( [0] => JSON does not validate. Violations: String expected, 0 received at #->$ref[file~2///var/www/glpi-10.0.0/vendor/glpi-project/inventory_format/inventory.schema.json]->properties:content->properties:memories->items[0]:0->properties:removable ) in /var/www/glpi-10.0.0/src/Inventory/Inventory.php at line 209

**Comment by NightFlame** [comment]
Loads with error some old XML's from fusioninventory-agent (2.5.2,2.6) or new XML/JSON from glpi-agent.
**1. From glpi-agent:**
```
admin@glpi02:~# glpi-injector --file AT-ENG02.XML --url http://localhost/front/inventory.php -v
Loading AT-ENG02.XML...ERROR: Array
(
    [0] => JSON does not validate. Violations:
Integer expected, "3" received at #->$ref[file~2///var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json]->properties:content->properties:versionprovider->properties:etime

)

These elements were not sent:
AT-ENG02.XML
```
AT-ENG02.XML:
```
...
<VERSIONCLIENT>GLPI-Inventory_v1.0</VERSIONCLIENT>
<VERSIONPROVIDER>
<COMMENTS>Provided by Teclib Edition</COMMENTS>
<COMMENTS>Installer built on Fri Dec 10 18:29:15 2021 UTC</COMMENTS>
<COMMENTS>Built with Strawberry Perl 5.34.0</COMMENTS>
<COMMENTS>Built on github actions windows image for glpi-project/glpi-agent repository</COMMENTS>
<ETIME>38</ETIME>
<NAME>GLPI</NAME>
<PERL_EXE>C:\fi\x64\perl\bin\glpi-agent.exe</PERL_EXE>
<PERL_VERSION>v5.34.0</PERL_VERSION>
<PROGRAM>perl\bin\glpi-inventory</PROGRAM>
<VERSION>1.0</VERSION>
</VERSIONPROVIDER>
...
```
After deleting key `<ETIME>38</ETIME>`, file load successful.
**2. From FusionInventory-agent:**
```
admin@glpi02:~# glpi-injector --file NATALIYA.XML --url http://localhost/front/inventory.php -v
Loading NATALIYA.XML...ERROR: Array
(
    [0] => JSON does not validate. Violations:
Integer expected, "75 W" received at #->$ref[file~2///var/www/html/glpi/vendor/glpi-project/inventory_format/inventory.schema.json]->properties:content->properties:powersupplies->items[0]:0->properties:power_max

)

These elements were not sent:
NATALIYA.XML
```
NATALIYA.XML:
```
...
<POWERSUPPLIES>
<HOTREPLACEABLE>No</HOTREPLACEABLE>
<LOCATION>OEM_Define0</LOCATION>
<MANUFACTURER>OEM_Define2</MANUFACTURER>
<NAME>OEM_Define1</NAME>
<PARTNUM>OEM_Define5</PARTNUM>
<PLUGGED>No</PLUGGED>
<POWER_MAX>75 W</POWER_MAX>
<SERIALNUMBER>OEM_Define3</SERIALNUMBER>
<STATUS>Present, OK</STATUS>
</POWERSUPPLIES>
...
```

**Comment by trasher** [comment]
OK, there are 3 distinct issues here on different "nodes":

1- `services` node, from the original issue.

Such a node does not exists in any specifications, @tomway please provide an example XML.

2- `etime` node.

This is a glpi-agent issue and has been solved

3- `power_max` node

Indeed a bug in the conversion lib, see https://github.com/glpi-project/inventory_format/pull/63

**Comment by tomway** [comment]
@trasher Thank you for pointing out "services", it didn't dawn on me until you mentioned it as the reason for the error. You are correct that the node doesn't exist in any specification. The company I worked for added the extra functionality to the fusion-inventory agent to capture all windows services and the information about them.  It is required to have this information contained within the XML file for our records, the FusionInventory plugin just ignored it and everything else imported. It would make this issue unique to our work. So I guess the best question to ask at this point is: Can custom enhancements/changes/nodes like this be ignored somehow and still allow import of the rest of the valid information?
Here is just one slice of the XML:
     `<SERVICES>
      <ACCEPTSTOP>0</ACCEPTSTOP>
      <CAPTION>Encrypting File System (EFS)</CAPTION>
      <CHECKPOINT>0</CHECKPOINT>
      <CREATIONCLASSNAME>Win32_Service</CREATIONCLASSNAME>
      <DESCRIPTION>Provides the core file encryption technology used to store encrypted files on NTFS file system volumes. If this service is stopped or disabled, applications will be unable to access encrypted files.</DESCRIPTION>
      <DESKTOPINTERACT>0</DESKTOPINTERACT>
      <DISPLAYNAME>Encrypting File System (EFS)</DISPLAYNAME>
      <ERRORCONTROL>Normal</ERRORCONTROL>
      <EXITCODE>1077</EXITCODE>
      <NAME>EFS</NAME>
      <PATHNAME>C:\Windows\System32\lsass.exe</PATHNAME>
      <PROCESSID>0</PROCESSID>
      <SERVICESPECIFICEXITCODE>0</SERVICESPECIFICEXITCODE>
      <SERVICETYPE>Share Process</SERVICETYPE>
      <STARTED>0</STARTED>
      <STARTMODE>Manual</STARTMODE>
      <STARTNAME>LocalSystem</STARTNAME>
      <STATE>Stopped</STATE>
      <STATUS>OK</STATUS>
      <SYSTEMCREATIONCLASSNAME>Win32_ComputerSystem</SYSTEMCREATIONCLASSNAME>
      <SYSTEMNAME>TEST</SYSTEMNAME>
      <TAGID>0</TAGID>
      <WAITHINT>0</WAITHINT>
    </SERVICES>
    <SERVICES>
      <ACCEPTSTOP>1</ACCEPTSTOP>
      <CAPTION>Windows Event Log</CAPTION>
      <CHECKPOINT>0</CHECKPOINT>
      <CREATIONCLASSNAME>Win32_Service</CREATIONCLASSNAME>
      <DESCRIPTION>This service manages events and event logs. It supports logging events, querying events, subscribing to events, archiving event logs, and managing event metadata. It can display events in both XML and plain text format. Stopping this service may compromise security and reliability of the system.</DESCRIPTION>
      <DESKTOPINTERACT>0</DESKTOPINTERACT>
      <DISPLAYNAME>Windows Event Log</DISPLAYNAME>
      <ERRORCONTROL>Normal</ERRORCONTROL>
      <EXITCODE>0</EXITCODE>
      <NAME>eventlog</NAME>
      <PATHNAME>C:\Windows\System32\svchost.exe -k LocalServiceNetworkRestricted</PATHNAME>
      <PROCESSID>1076</PROCESSID>
      <SERVICESPECIFICEXITCODE>0</SERVICESPECIFICEXITCODE>
      <SERVICETYPE>Share Process</SERVICETYPE>
      <STARTED>1</STARTED>
      <STARTMODE>Auto</STARTMODE>
      <STARTNAME>NT AUTHORITY\LocalService</STARTNAME>
      <STATE>Running</STATE>
      <STATUS>OK</STATUS>
      <SYSTEMCREATIONCLASSNAME>Win32_ComputerSystem</SYSTEMCREATIONCLASSNAME>
      <SYSTEMNAME>TEST</SYSTEMNAME>
      <TAGID>0</TAGID>
      <WAITHINT>0</WAITHINT>
    </SERVICES>`

**Comment by trasher** [comment]
Not a bug, this is quite simple in a plugin to extend inventory specifications, this is certainly the best way to go right now.
