### ISSUE TITLE
Check for curl extension

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1022]
Hello,

The curl extension seems to be required only from the RSS class; so we would not add a global check at install time and just suggest to install it).

The RSS class should take care of that, and display a clear error when the extension is missing. Related to #1020 (and other I do not remember).

**Comment by tomolimo** [comment]
Dear @trasher 
I don't agree with this statement!
For me, as soon as something is delivered in standard by GLPi and is requiring some modules, then it has to be checked like for other requirements.
thank you,
regards,
Tomolimo

**Comment by trasher** [comment]
Hello,

The proposal is to handle `ext-curl` dependency as `ext-ldap` or even `ext-imap` already are.

`ldap` and `curl` extension should not be *required* to install GLPi; since it can work very well without. At least, we should just *recommend* to install them to get all features available; but there is no such existing feature on the install process (there already is another ticket opened for this, if I remember correctly).

And anyways, any *recomanded* extension have to be checked where it is used. Extensions that becomes to be used several times in different parts of the code have to be *required*; of course.

**Comment by tomolimo** [comment]
I agree for LDAP, that it is an option as it depends on the chosen authorization schema, but RSS is not an option as it is shown on GLPi home page (even is you don't want to use it). I'll agree that it would be an option if it really was an option but currently, you can de-activate it.

**Comment by trasher** [comment]
Oh... I had in mind that was optional... Will check; thank you :)

**Comment by tomolimo** [comment]
The only settings are in the Profile settings:
![image](https://cloud.githubusercontent.com/assets/7569958/18702293/5405bade-7fe1-11e6-9413-5d233d7819c2.png)
and are about Public RSS, and not private ones.
