### ISSUE TITLE
[GLPI 10] KnowbaseItem - Undefined index: knowbaseitemcategories_id

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#10239]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10 beta

### Bug description

Knowledge base > Browse or Search :

Undefined index: knowbaseitemcategories_id in htdocs/src/KnowbaseItem.php at line 1816

### Relevant log output

```
glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: knowbaseitemcategories_id in htdocs/src/KnowbaseItem.php at line 1816
  Backtrace :
  ajax/knowbase.php:50                               KnowbaseItem::showList()
```

### Page URL

https://demo.with.glpi10.cloud/front/knowbaseitem.php

### Steps To reproduce

1. With or without knowbaseitem (attached or not to a category)
2. Just go to Knowledge base > Browse
3. Or Knowledge base > Search (and make a search)

**Comment by husisusi** [comment]
I cannot reproduce this Issue using php 8.0.14
