### ISSUE TITLE
Button "Save" missing from Cable Management

### ISSUE THREAD

**Issue by 99net** [glpi-project/glpi#10233]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10

### Bug description

No button to save a new record in cable management (Assets > Cables). 
Super admin profile looks just fine.

![image](https://user-images.githubusercontent.com/43380069/147490538-4b5856fd-cd8c-47f5-9e49-6d6c1964a3ba.png)

![image](https://user-images.githubusercontent.com/43380069/147490614-13381a8f-cdba-49b7-a2aa-5e513facf525.png)

**Comment by cconard96** [comment]
Can you test #10234?

**Comment by 99net** [comment]
All fine. Thank You.
