### ISSUE TITLE
Fatal Error : Cannot declare class Glpi\Socket, because the name is already in use in ...\src\Socket.php line 0

### ISSUE THREAD

**Issue by NoxWorld2660** [glpi-project/glpi#10231]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

While navigating in ~80% of the PARC elements, i get this error : 
`Fatal error : Cannot declare class Glpi\Socket, because the name is already in use in C:\xampp\htdocs\glpi10beta\src\Socket.php on line 0
`
And obviously none of the element are displayed.
I think it's a namespace or autoloader issue, but i don't really get where / why.

Might be due to a poorly done upgrade ?

### Page URL

myinstall/glpi10beta/front/computer.php

### Steps To reproduce

1. Upgrade glpi9 stable to glpi10 via web interface
2. After successfull upgrade, login with your account , and go to myinstall/glpi10beta/front/computer.php

### Your GLPI setup information

Upgraded from glpi 9 latest stable to glpi 10.
Using xampp, php8.0

### Anything else?

I may have upgraded the wrong way ? Is there a doc about this ?

**Comment by stdglpi** [comment]
You will found more info here : [#10228 ](https://github.com/glpi-project/glpi/issues/10228#issuecomment-1001033742)

**Comment by flegastelois** [comment]
Fixed by https://github.com/glpi-project/glpi/pull/10169

**Comment by cconard96** [comment]
Please test with latest nightly release. If it is still a problem, please open a new issue.
