### ISSUE TITLE
GLPI 10 BETA Mail_Receivers: Uncaught Exception ArgumentCountError

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#10240]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

I am testing GLPI 10, trying to setup IMAP Receivers. If the Inbox is empty no issue:
![grafik](https://user-images.githubusercontent.com/8606735/147831296-9580a29b-a9d4-499d-997c-364272a38ac1.png)

But when there is an email in the inbox, I just get a white screen. 

    

### Relevant log output

```shell
mb_decode_mimeheader() expects exactly 1 argument, 3 given in /srv/http/glpi/vendor/symfony/polyfill-iconv/bootstrap80.php at line 57
```

### Your GLPI setup information

Operating system: Linux 9455fb1d8bf1 5.15.11-0-lts #1-Alpine SMP Thu, 23 Dec 2021 08:03:24 +0000 x86_64
PHP 8.0.14 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, hash, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix,
	session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Unix) PHP/8.0.14 ()
	Mozilla/5.0 (X11; Linux x86_64; rv:95.0) Gecko/20100101 Firefox/95.0
Server Software: Arch Linux
	Server Version: 10.6.5-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi10
	Host info: Localhost via UNIX socket
	
PHP version (8.0.14) is supported.PHP version (8.0.14) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.6.5) is supported.Database engine version (10.6.5) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /srv/http/glpi/files/_cache has been validated. Write access to /srv/http/glpi/config has been validated. Write access to /srv/http/glpi/files/_cron has been validated. Write access to /srv/http/glpi/files has been validated. Write access to /srv/http/glpi/files/_dumps has been validated. Write access to /srv/http/glpi/files/_graphs has been validated. Write access to /srv/http/glpi/files/_lock has been validated. Write access to /srv/http/glpi/files/_pictures has been validated. Write access to /srv/http/glpi/files/_plugins has been validated. Write access to /srv/http/glpi/files/_rss has been validated. Write access to /srv/http/glpi/files/_sessions has been validated. Write access to /srv/http/glpi/files/_tmp has been validated. Write access to /srv/http/glpi/files/_uploads has been validated.Write access to /srv/http/glpi/files/_cache has been validated.
Write access to /srv/http/glpi/config has been validated.
Write access to /srv/http/glpi/files/_cron has been validated.
Write access to /srv/http/glpi/files has been validated.
Write access to /srv/http/glpi/files/_dumps has been validated.
Write access to /srv/http/glpi/files/_graphs has been validated.
Write access to /srv/http/glpi/files/_lock has been validated.
Write access to /srv/http/glpi/files/_pictures has been validated.
Write access to /srv/http/glpi/files/_plugins has been validated.
Write access to /srv/http/glpi/files/_rss has been validated.
Write access to /srv/http/glpi/files/_sessions has been validated.
Write access to /srv/http/glpi/files/_tmp has been validated.
Write access to /srv/http/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, mbstring. Following extensions are not present: iconv, sodium.Following extensions are installed: ctype, mbstring.
Following extensions are not present: iconv, sodium.
Write access to /srv/http/glpi/marketplace has been validated.Write access to /srv/http/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by husisusi** [comment]
Changing line 57 on glpi/vendor/symfony/polyfill-iconv/bootstrap80.php  fixed this issue:

`function iconv_mime_decode($string, $mode = 0, $encoding = null) { null === $encoding && $encoding = p\Iconv::$internalEncoding; return mb_decode_mimeheader($string); }`

**Comment by cedric-anne** [comment]
Hi,

This bug is located in the `symfony/polyfill-iconv` dependency. I proposed a fix (see https://github.com/symfony/polyfill/pull/384).

Waiting for an approval / merge / release before integrating patch in GLPI.

Regards

**Comment by cedric-anne** [comment]
Fixed by https://github.com/glpi-project/glpi/pull/10334.
