### ISSUE TITLE
[10 beta] [9.5.x] PLANNING - Dragging task that extends beyond calendar view truncates task end date.

### ISSUE THREAD

**Issue by derry43** [glpi-project/glpi#10252]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.4

### Bug description

 In Assistance->Planning - dragging a task (project, reminder, ticket task, external event etc) to beyond the date limits of the particular calendar view will truncate the end date and time to the last day and hour available in the view.

E.g. Create an external event say, which starts at 11:00 AM on Wed 13th Oct 2021 and finishes at 08:00 AM on Friday 15th Oct 2021 (1 day and 21 hours long). Switch to the Day view, in Planning and move (drag) this event to start at 10 AM on Wed 13th Oct 2021 and the event details will be modified such that it now starts at 10:00 AM on Wed 13th Oct 2021 and finishes at 11:00 PM (23:00) on Wed 13th Oct 2021 (now only 13 hours long). i.e. the end date and time is truncated.

### Relevant log output

```shell
No relevant logs
```

### Page URL

front/planning.php

### Steps To reproduce

This can be demonstrated as follows:

Create a task (Task A) which starts at 11:00 AM on Wed 13th Oct 2021 and finishes at 08:00 AM on Friday 15th Oct 2021 (same week).

Assign Task A to yourself (or in Project Task add yourself to Project Task Team).

Open Planning -> Month view.

Drag Task A from 11:00 AM on 13th Oct to 10:00 AM on 13 Oct and dates/times change correctly.

Change to Planning -> Week view.

**Before Task Move**

![49E57983-EE2D-4C8E-B99B-27B75A2138BE](https://user-images.githubusercontent.com/47180698/147877199-89c97627-6d59-4df1-ac10-99862abda97e.png)

Drag Task A from 11:00 AM on 13th Oct to 10:00 AM on 13 Oct and dates/times change correctly. Start and finish times show correctly on calendar task before and after.

**After Task Move**

![9D59EBCE-2BB1-4821-B369-F623D1A15A7D](https://user-images.githubusercontent.com/47180698/147877211-9805c743-98f6-4231-9698-6d35b8a75aad.png)

Change to Planning -> Day view

**Before Task Move (end time is incorrect now)**

![56B796FF-0B79-4AA4-9495-A9B4ACCE9A6D](https://user-images.githubusercontent.com/47180698/147877226-ebe2238b-b33d-48b8-bd14-80e8f676aef1.png)

The part of the task which extends onto the date of 13th Oct is show in the lower part of the calendar view. The part of the task which is on 14th is shown in the all-day section

Drag Task A from 11:00 AM on 13th Oct to 10:00 AM on 13 Oct and dates/times change incorrectly. Appears as though task is truncated to end of visible day.

**After Task Move**

![A7D6BD16-7ECC-40AC-B577-49F1F2CE8089](https://user-images.githubusercontent.com/47180698/147877235-122eacc0-94f7-4694-95a3-6da325910f95.png)

This can also be seen in task detail.

![76DC5364-C327-44C0-ABE9-9B49ED7AB8D4](https://user-images.githubusercontent.com/47180698/147877240-2bb225de-803e-4bbb-9b69-0d41c5822ff4.png)

Same thing happens on Week view if task extends beyond the visible week. Moving the task will truncate to end of visible week. I am guessing that same thing would happen for a task that extended over the month view.

### Your GLPI setup information

GLPI 9.5.4 ( => C:\inetpub\wwwroot\glpi)
Installation mode: TARBALL
Server

Operating system: Windows NT EMPCRUUKWPBU012 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP 7.4.15 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, readline,
	session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Microsoft-IIS/8.5
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36 Edg/94.0.992.38
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.23
	Server SQL Mode: 
	Parameters: glpi@172.16.2.70/glpi
	Host info: 172.16.2.70 via TCP/IP
	
 PHP version is at least 7.2.0 - Perfect!
 Sessions support is available - Perfect!
 Allocated memory > 64 Mio - Perfect!
 mysqli extension is installed
 ctype extension is installed
 fileinfo extension is installed
 json extension is installed
 mbstring extension is installed
 iconv extension is installed
 zlib extension is installed
 curl extension is installed
 gd extension is installed
 simplexml extension is installed
 intl extension is installed
 ldap extension is installed
 apcu extension is not present
 Zend OPcache extension is not present
 xmlrpc extension is installed
 CAS extension is not present
 exif extension is installed
 zip extension is installed
 bz2 extension is installed
 sodium extension is installed
 Database version seems correct (8.0.23) - Perfect!
 Timezones seems loaded in database
 The log file has been created successfully.
 Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated.
 Write access to C:\inetpub\wwwroot\glpi/config has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated.
 Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.
 Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.
 Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
GLPI constants

GLPI_ROOT: C:\inetpub\wwwroot\glpi
GLPI_CONFIG_DIR: C:\inetpub\wwwroot\glpi/config
GLPI_VAR_DIR: C:\inetpub\wwwroot\glpi/files
GLPI_MARKETPLACE_DIR: C:\inetpub\wwwroot\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 1
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: C:\inetpub\wwwroot\glpi/files
GLPI_CACHE_DIR: C:\inetpub\wwwroot\glpi/files/_cache
GLPI_CRON_DIR: C:\inetpub\wwwroot\glpi/files/_cron
GLPI_DUMP_DIR: C:\inetpub\wwwroot\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\inetpub\wwwroot\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\inetpub\wwwroot\glpi/files/_locales
GLPI_LOCK_DIR: C:\inetpub\wwwroot\glpi/files/_lock
GLPI_LOG_DIR: C:\inetpub\wwwroot\glpi/files/_log
GLPI_PICTURE_DIR: C:\inetpub\wwwroot\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\inetpub\wwwroot\glpi/files/_plugins
GLPI_RSS_DIR: C:\inetpub\wwwroot\glpi/files/_rss
GLPI_SESSION_DIR: C:\inetpub\wwwroot\glpi/files/_sessions
GLPI_TMP_DIR: C:\inetpub\wwwroot\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\inetpub\wwwroot\glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\inetpub\wwwroot\glpi/locales
GLPI_VERSION: 9.5.4
GLPI_SCHEMA_VERSION: 9.5.4
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2021
Libraries

htmlawed/htmlawed version 1.2.5 in (C:\inetpub\wwwroot\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.1.6 in (C:\inetpub\wwwroot\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.6 in (C:\inetpub\wwwroot\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.3.5 in (C:\inetpub\wwwroot\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\wwwroot\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\wwwroot\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\wwwroot\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\wwwroot\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\wwwroot\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\wwwroot\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\wwwroot\glpi\vendor\sabre\vobject\lib)
laminas/laminas-cache in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-cache\src)
laminas/laminas-i18n in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-serializer in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-serializer\src)
monolog/monolog in (C:\inetpub\wwwroot\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\wwwroot\glpi\vendor\sebastian\diff\src)
elvanto/litemoji in (C:\inetpub\wwwroot\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\wwwroot\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\wwwroot\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\wwwroot\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\wwwroot\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\wwwroot\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\wwwroot\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\wwwroot\glpi\vendor\psr\simple-cache\src)
mexitek/phpcolors in (C:\inetpub\wwwroot\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\psr7\src)
wapmorgan/unified-archive in (C:\inetpub\wwwroot\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\wwwroot\glpi\vendor\paragonie\sodium_compat\src)
LDAP directories

Server: 'ldap://XXX', Port: '636', BaseDN: 'DC=navsys,DC=ad', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'X@Y',
		Use TLS: none
SQL replicas

Not active
Notifications

Way of sending emails: SMTP (anonymous@XXX)
Mails receivers

Plugins list

	activity             Name: Activities                     Version: 3.0.0      State: Installed / not activated
	actualtime           Name: ActualTime                     Version: 1.5.0      State: Installed / not activated
	fields               Name: Additionnal fields             Version: 1.12.4     State: Enabled
	advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Enabled
	news                 Name: Alerts                         Version: 1.9.0      State: Enabled
	appliances           Name: Appliances                     Version: 3.1.1      State: Not installed
	archisw              Name: Apps structures                Version: 2.2.5      State: Enabled
	impacts              Name: Asset impacts                  Version: 2.0.5      State: Enabled
	behaviors            Name: Behaviours                     Version: 2.5.0      State: Enabled
	archibp              Name: Business Processes             Version: 1.0.1      State: Enabled
	positions            Name: Cartography                    Version: 5.0.0      State: Installed / not activated
	cmdb                 Name: CMDB                           Version: 2.2.1      State: Enabled
	cve                  Name: CVE                            Version: 1.0.0      State: Installed / not activated
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled
	datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled
	databases            Name: Databases                      Version: 2.3.2      State: Enabled
	archimap             Name: Diagrams                       Version: 3.1.2      State: Enabled
	domains              Name: Domains                        Version: 2.2.1      State: Enabled
	father               Name: Father&Sons                    Version: 1.2.0      State: Not installed
	formcreator          Name: Form Creator                   Version: 2.11.2     State: Enabled
	archifun             Name: Functional Areas               Version: 2.2.2      State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled
	resources            Name: Human Resources                Version: 2.7.0      State: Enabled
	geninventorynumber   Name: Inventory number generation    Version: 2.5.0      State: Enabled
	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.7.0      State: Enabled
	itilcategorygroups   Name: ItilCategory Groups            Version: 2.4.1      State: Installed / not activated
	metademands          Name: Meta-Demands                   Version: 2.7.5      State: Installed / not activated
	mreporting           Name: More Reporting                 Version: 1.7.3      State: Enabled
	genericobject        Name: Objects management             Version: 2.11.0     State: Installed / not activated
	order                Name: Orders management              Version: 2.7.2      State: To update
	pdf                  Name: Print to pdf                   Version: 2.0.0      State: Enabled
	projectbridge        Name: Projectbridge                  Version: 2.4        State: Installed / not activated
	releases             Name: Releases                       Version: 1.0.1      State: Not installed
	reports              Name: Reports                        Version: 1.14.1     State: Enabled
	shellcommands        Name: Shell Commands                 Version: 3.0.0      State: Enabled
	tag                  Name: Tag Management                 Version: 2.8.1      State: Installed / not activated
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled
	tasklists            Name: Tasks list                     Version: 1.6.2      State: Enabled
	useditemsexport      Name: Used items export              Version: 2.3.0      State: Installed / not activated
	vip                  Name: VIP                            Version: 1.4RC1     State: Enabled
	webapplications      Name: Web applications               Version: 3.0.0      State: Installed / not activated
	webresources         Name: Web Resources                  Version: 1.3.2      State: Enabled

### Anything else?

Issue also present in 10 Beta as I tested in demo version.

**Comment by derry43** [comment]
In 10 Beta, initially while dragging task you see end date/time update correctly as task is moved, but once mouse is released the end date truncates to end date/time of view.

**Comment by cconard96** [comment]
Duplicates #9677 which has since been re-opened.
