### ISSUE TITLE
error when use "php bin/console glpi:migration:utf8mb4"

### ISSUE THREAD

**Issue by Loopers29** [glpi-project/glpi#10268]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10

### Bug description

Hello team,
Thank you in advance for all you do!

I created a VM to put the beta of GLPI 10 to see what this new version gave.
I connected my remote database on which my data of my GLPI 9.4 are currently.
When I arrive on the home page I have this message: "
11 columns use the deprecated definition, DATETIME. Launch the command "php bin/console glpi:migration:timestamps" to migrate them.
66 tables use the deprecated charset, utf8mb3. Run the command "php bin/console glpi:migration:utf8mb4" to migrate them."

Problem: neither command works and I must admit that I wondered if I should run the command on my remote sql server or on my VM hosting the GLPI 10 files.

Any idea how to solve these two error messages please?

Thanks again 🙏

### Relevant log output

```shell
[2022-01-05 13:37:39] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getTime() on null in /var/www/html/glpi/src/Html.php at line 1652
  Backtrace :
  src/Html.php:1988                                  Html::footer()
  src/Html.php:903                                   Html::nullFooter()
  src/Session.php:1425                               Html::displayErrorAndDie()
  install/install.php:532                            Session::checkCSRF()
  
[2022-01-05 13:37:46] glpiphplog.WARNING: Test logger  
[2022-01-05 13:39:22] glpiphplog.WARNING: Test logger  
[2022-01-05 13:40:00] glpiphplog.WARNING: Test logger  
[2022-01-05 13:40:06] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6626
Compile css/install.scss  {"user":"@myglpiserver"} 
[2022-01-05 13:41:10] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getTime() on null in /var/www/html/glpi/src/Html.php at line 1652
  Backtrace :
  src/Html.php:1988                                  Html::footer()
  src/Html.php:903                                   Html::nullFooter()
  src/Session.php:1425                               Html::displayErrorAndDie()
  install/install.php:532                            Session::checkCSRF()
  
[2022-01-05 13:41:11] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6626
Compile css/palettes/auror.scss  {"user":"@myglpiserver"} 
[2022-01-05 13:41:13] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: glpidate_format in /var/www/html/glpi/src/Toolbox.php at line 2849
  Backtrace :
  src/Html.php:6283                                  Toolbox::getDateFormat()
  src/Html.php:1649                                  Html::getCoreVariablesForJavascript()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index:  in /var/www/html/glpi/src/Toolbox.php at line 2849
  Backtrace :
  src/Html.php:6283                                  Toolbox::getDateFormat()
  src/Html.php:1649                                  Html::getCoreVariablesForJavascript()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type null in /var/www/html/glpi/src/Html.php at line 752
  Backtrace :
  src/Html.php:1727                                  Html::displayDebugInfos()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.WARNING:   *** PHP Warning (2): array_sum() expects parameter 1 to be array, null given in /var/www/html/glpi/src/Html.php at line 752
  Backtrace :
  src/Html.php:752                                   array_sum()
  src/Html.php:1727                                  Html::displayDebugInfos()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type null in /var/www/html/glpi/src/Html.php at line 764
  Backtrace :
  src/Html.php:1727                                  Html::displayDebugInfos()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.WARNING:   *** PHP Warning (2): array_sum() expects parameter 1 to be array, null given in /var/www/html/glpi/src/Html.php at line 764
  Backtrace :
  src/Html.php:764                                   array_sum()
  src/Html.php:1727                                  Html::displayDebugInfos()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.NOTICE:   *** PHP Notice (8): Trying to access array offset on value of type null in /var/www/html/glpi/src/Html.php at line 769
  Backtrace :
  src/Html.php:1727                                  Html::displayDebugInfos()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
  
[2022-01-05 13:41:13] glpiphplog.WARNING:   *** PHP Warning (2): Invalid argument supplied for foreach() in /var/www/html/glpi/src/Html.php at line 769
  Backtrace :
  src/Html.php:1727                                  Html::displayDebugInfos()
  src/Html.php:1988                                  Html::footer()
  inc/config.php:77                                  Html::nullFooter()
  inc/includes.php:51                                include_once()
  front/locale.php:37                                include()
```

### Page URL

myglpiserver/front/central.php

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-dev (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux myglpiserver 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64
PHP 7.4.27 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at myIPglpiserver Port 80
)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.29-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: myglpiuser@myIPsqlserver
	Host info: myIPsqlserver via TCP/IP
	
PHP version (7.4.27) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.3.29) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.0-dev
GLPI_SCHEMA_VERSION: 10.0.0-dev@5d5ed159d30f08ffa4fb9065d7c3f64855d5d4e1
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_YEAR: 2021

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

**Comment by orthagh** [comment]
backtrace:

```
[2022-01-06 11:31:16] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Symfony\Component\Console\Question\ConfirmationQuestion::isMultiline() in /var/www/html/glpi/10.0.git/vendor/symfony/console/Helper/QuestionHelper.php at line 514
  Backtrace :
  ...r/symfony/console/Helper/QuestionHelper.php:130 Symfony\Component\Console\Helper\QuestionHelper->readInput()
  ...or/symfony/console/Helper/QuestionHelper.php:67 Symfony\Component\Console\Helper\QuestionHelper->doAsk()
  src/Console/Migration/MyIsamToInnoDbCommand.php:92 Symfony\Component\Console\Helper\QuestionHelper->ask()
  vendor/symfony/console/Command/Command.php:298     Glpi\Console\Migration\MyIsamToInnoDbCommand->execute()
  vendor/symfony/console/Application.php:1005        Symfony\Component\Console\Command\Command->run()
  src/Console/Application.php:254                    Symfony\Component\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:299         Glpi\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:171         Symfony\Component\Console\Application->doRun()
  bin/console:119                                    Symfony\Component\Console\Application->run()
  ```

**Comment by cedric-anne** [comment]
> Problem: neither command works and I must admit that I wondered if I should run the command on my remote sql server or on my VM hosting the GLPI 10 files.

Hi,

You must run these commands on the GLPI host server, from the GLPI root directory, and using the same user as your webserver (do not run them using root user, to prevent rights issues later).

Regards
