### ISSUE TITLE
Change id format for glpi_tickets

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#10265]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

all versions

### Bug description

In Behaviors plugin user can choose different personal ticket's formats.
One of these is ymd0001
Since 2022, this format can't be used. Many users of GLPI and Behaviors plugin ask me to correct this.
The solution, for me, is to change the data type of field id in glpi_tickets.
Are you agree to change it with data type BIGINT instead of INT? 

If you are OK can you also change id of glpi_changes? (personal number format like tickets can be used)

**Comment by orthagh** [comment]
duplicate 10262
