### ISSUE TITLE
[GLPI 10] When creating an email ticket, the receivers email address (recipient) is Observer

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#10261]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

When creating an e-mail ticket, the "ticket systems e-mail address" is added to the observer.

![grafik](https://user-images.githubusercontent.com/8606735/147989617-d7ed7039-5d52-4395-8a84-afba5fda2d9d.png)

### Steps To reproduce

1. Setup receivers
2. Send an email to this receivers to create a ticket
3. Wait until the email is picked up 
4. Check the "Observer"

### Your GLPI setup information

Last git version (03.01.2022)
Linux, PHP8.0, Apache2, smtp

**Comment by husisusi** [comment]
All of the notification templates on Beta 10 are weird!!

**Comment by Dayflare** [comment]
i can reproduce this on GLPI 9.5.5 and 9.5.6. Doesn't look like a GLPI 10 issue.

**Comment by husisusi** [comment]
What is the technical difference between Observer and Watcher?
As workaround I tried to use "Business rules for tickets", but "Business rules for tickets" has no Observer, only Watcher!

**Comment by cedric-anne** [comment]
@husisusi 

Is the receiver email that is added as observer ?

**Comment by husisusi** [comment]
> @husisusi
> 
> Is the receiver email that is added as observer ?

Yes

**Comment by cedric-anne** [comment]
> > @husisusi
> > Is the receiver email that is added as observer ?
> 
> Yes

In this case, the solution could be to set the mail receiver name value to this address. When the mail receiver name is a valid email address, emails coming from this address are not collected, and this address is excluded from observers.

Can you confrm that it works as expected ?

**Comment by husisusi** [comment]
Mea culpa!! It works.
Thank You @cedric-anne and sorry!

I just saw that there is a note about it next to the name value "i"
![grafik](https://user-images.githubusercontent.com/8606735/159654900-e0162a98-4b11-4bfc-baa4-be4dacd02a92.png)
