### ISSUE TITLE
API "searchOptions" prints the same option values (Complete name and Father) for Location

### ISSUE THREAD

**Issue by anyqov** [glpi-project/glpi#10270]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.3

### Bug description

Hello,

I execute the request:
curl -X GET \
-H 'Content-Type: application/json' \
-H "Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62" \
-H "App-Token: f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7" \
'http://path/to/glpi/apirest.php/listSearchOptions/Location'

In response I get:
{
    "common": {
        "name": "Characteristics"
    },
    "1": {
        "name": "Complete name",
        "table": "glpi_locations",
        "field": "completename",
        "datatype": "itemlink",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "notcontains",
            "equals",
            "notequals",
            "under",
            "notunder"
        ],
        "uid": "Location.completename"
    },
    "2": {
        "name": "ID",
        "table": "glpi_locations",
        "field": "id",
        "datatype": "number",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "notcontains"
        ],
        "uid": "Location.id"
    },
    "14": {
        "name": "Name",
        "table": "glpi_locations",
        "field": "name",
        "datatype": "itemlink",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "notcontains",
            "equals",
            "notequals",
            "under",
            "notunder"
        ],
        "uid": "Location.name"
    },
    "13": {
        "name": "Father",
        "table": "glpi_locations",
        "field": "completename",
        "datatype": "dropdown",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "notcontains",
            "equals",
            "notequals",
            "under",
            "notunder"
        ],
        "uid": "Location.completename"
    },
    ...
}

So uid and field are equal for "1" and "13":
"1": {"field": "completename", "uid": "Location.completename"} 
"13": {"field": "completename", "uid": "Location.completename"}

Option "13" must be:
"13": {"name": "Father", "field": "father", "uid": "Location.father"}

### Page URL

http://path/to/glpi/apirest.php/listSearchOptions/Location

### Steps To reproduce

Execute "listSearchOptions" API request for Location.

### Your GLPI setup information

GLPI 9.5.3
Operating system: Linux glpi-1 4.18.0-240.10.1.el8_3.x86_64 #1 SMP Mon Jan 18 17:05:51 UTC 2021 x86_64
PHP 7.4.15 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter,
	xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="256M" 
Software: Apache/2.4.37 (centos) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4807.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.5.9-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
Please try with latest stable release

**Comment by trasher** [comment]
No feedback, closing.

**Comment by anyqov** [comment]
Hello, 
Sorry for the late reply.

I tried on version 9.5.7, the same error occurs.
