### ISSUE TITLE
GLPI10 - Can't empty dropdowns that allows multiple values

### ISSUE THREAD

**Issue by AdrienClairembault** [glpi-project/glpi#10289]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

While working on #10288, I've noticed that you can't empty a dropdown that allows multiple values.

For example, if you go to your configuration, empty the following field and hit save:
![image](https://user-images.githubusercontent.com/42734840/148574871-80842c2f-c64a-4e3d-b0da-6b875a14d7d4.png)

The changes will not be saved:
![image](https://user-images.githubusercontent.com/42734840/148574950-a5802214-da99-4def-8c44-0f25d27badbb.png)

We use "array" inputs for these kind of fields which are named like this: `planning_working_days[]`.
If you save this input with at least one value then it is sent as a `planning_working_days` array in `$_POST`.
However if you select 0 values then the input is omitted from the form data... there will be no `planning_working_days` key in `$_POST`.

**Comment by husisusi** [comment]
That is not a bug.
You can not set 0 work days, pointless!

**Comment by AdrienClairembault** [comment]
Seems to be a known issue already and the same kind of fix that used in #10288 is also used for each dropdown that should allow an empty value :
![image](https://user-images.githubusercontent.com/42734840/148738747-fc4ac10a-d0b0-473d-8dc3-574b8df306a9.png)
![image](https://user-images.githubusercontent.com/42734840/148738652-2ab8faf7-245d-4af2-b9be-f9643d829e5d.png)

Guess we can't do much more for this.
