### ISSUE TITLE
xmlrpc no longer available in php8.0

### ISSUE THREAD

**Issue by BWMerlin** [glpi-project/glpi#10287]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

GLPI list that php version 7.4 or greater is [supported](https://glpi-install.readthedocs.io/en/latest/prerequisites.html#php) and that xmlrpc is an [optional](https://glpi-install.readthedocs.io/en/latest/prerequisites.html#optional-extensions) pre-requisite.

However when trying to install php8.0 there is no xmlrpc package as this has been [removed](https://php.watch/versions/8.0/xmlrpc).  The GLPI installer will still check for xmlrpc when trying to install.

Is the functionality that is provided by xmlrpc still required or is there an alternative means for this?  Does the documentation need to be updated to more accurately reflect that php8.0 is not or partially supported?

### Steps To reproduce

sudo apt install php8.0-xmlrpc

**Comment by husisusi** [comment]
FYI:
https://php.watch/versions/8.0/xmlrpc

**Comment by cedric-anne** [comment]
Hi,

You can still install this extension using PECL.

However, the XML-RPC API will be deprecated in GLPI 10.0 (see #8386).

Regards
