### ISSUE TITLE
[GLPI10] Inventory using agent

### ISSUE THREAD

**Issue by JTrotta** [glpi-project/glpi#10294]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 Nightly

### Bug description

Error  during agent inventory using:
- GLPI-Agent-1.1-gitce8e7d74-x64.msi
- GLPI 10.0.0 master installed from scratch.

### Relevant log output

```shell
[Sat Jan  8 16:12:07 2022][error] [http client] communication error: 500 Internal Server Error
[Sat Jan  8 16:12:07 2022][error] [http client] unexpected content, starting with: PHP Fatal error:  Incorrect date value: '2021-30-10' for column `glpi10`.`glpi_items_softwareversions`.`date_install` at row 1 in C:\inetpub\wwwroot\GLPI10\src\DBmysql.php on line 1940
```

### Steps To reproduce

1. Intall both Agent and GLPI
2. Force inventory from Agent

### Your GLPI setup information

Operating system: Windows NT XXXXXX 10.0 build 19044 (Windows 10) AMD64
PHP 8.0.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pgsql,
	readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0
Server Software: mariadb.org binary distribution
	Server Version: 10.6.5-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi10
	Host info: localhost via TCP/IP
	
PHP version (8.0.0) is supported.PHP version (8.0.0) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.6.5) is supported.Database engine version (10.6.5) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpub\wwwroot\GLPI10/files/_cache has been validated. Write access to C:\inetpub\wwwroot\GLPI10/config has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_cron has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_dumps has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_graphs has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_lock has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_pictures has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_plugins has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_rss has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_sessions has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_tmp has been validated. Write access to C:\inetpub\wwwroot\GLPI10/files/_uploads has been validated.Write access to C:\inetpub\wwwroot\GLPI10/files/_cache has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/config has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_cron has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_lock has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_rss has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot\GLPI10/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\wwwroot\GLPI10/marketplace has been validated.Write access to C:\inetpub\wwwroot\GLPI10/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

### Anything else?

Importing xml file from plugin to server, works.

**Comment by trasher** [comment]
Please provide GLPI logs output when this error is reached as well as an inventory file (anonymized); or at least the softawre in the list that cause that issue.
Thanks.

**Comment by JTrotta** [comment]
LOG FROM GLPI:
`[2022-01-08 15:12:07] glpiphplog.ERROR:   *** PHP User Error (256): Incorrect date value: '2021-30-10' for column `glpi10`.`glpi_items_softwareversions`.`date_install` at row 1 in C:\inetpub\wwwroot\GLPI10\src\DBmysql.php at line 1940
  Backtrace :
  src\DBmysql.php:1940                               trigger_error()
  src\Inventory\Asset\Software.php:732               DBmysql->executeStatement()
  src\Inventory\Asset\Software.php:335               Glpi\Inventory\Asset\Software->storeAssetLink()
  src\Inventory\Asset\MainAsset.php:751              Glpi\Inventory\Asset\Software->handle()
  src\Inventory\Asset\MainAsset.php:672              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src\RuleImportAsset.php:954                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1496                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1583                        Rule->process()
  src\Inventory\Asset\MainAsset.php:515              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:674                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:324                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:318                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:83                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:292    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:212    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:57                             Glpi\Agent\Communication\AbstractRequest->handleRequest()`

SOFTWARE IN THE LIST THAT CAUSE THE ISSUE:
`        <SOFTWARES>
      <ARCH>x86_64</ARCH>
      <FROM>registry</FROM>
      <GUID>AutoCAD 2021 - English</GUID>
      <INSTALLDATE>10/30/2021</INSTALLDATE>
      <NAME>Autodesk AutoCAD 2021 - English</NAME>
      <PUBLISHER>Autodesk</PUBLISHER>
      <SYSTEM_CATEGORY>application</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>XXXXXXXXXXXXXXXXXXXXX</UNINSTALL_STRING>
      <VERSION>24.0.47.0</VERSION>
    </SOFTWARES>`

**Comment by trasher** [comment]
Is the install date wrong aswell with fusioninventory-agent?

**Comment by JTrotta** [comment]
I have to check.

**Comment by JTrotta** [comment]
Done. Fusioninventory-agent works perfectly.

**Comment by trasher** [comment]
I'm not able to reproduce the initial error on current GLPI (maybe it has been fixed already). The wrong date is stored as `2023-06-10`.
