### ISSUE TITLE
Actors duplicated in tickets if I sublit incomplete form, fix it, and submit again

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#10292]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

If a user submits a new ticket with a mandatory field empty, then fills the mandatory field and submits again, the requester and the assigned users appear twice in the created ticket.

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. use the default ticket template with title mandator in your entity
2. open the ticket creation page
3. filll any description, but leave the title empty
4. submit the ticket; the browser tells the title is required
5. fill the title
6. submit the form
7. open the created ticket : see the actors appears twice

![image](https://user-images.githubusercontent.com/14139801/148637116-9447c7f6-8833-44c8-99d0-54d0a8c05941.png)

**Comment by cconard96** [comment]
I've tried to recreate this issue a few times over the last week or so but haven't been able to.
Is the issue still present for you in the latest GLPI 10 state?

**Comment by btry** [comment]
Hi

It seems thngs changed since my report. I remember that I found the issue by creating a ticket without a title or a content, despite they were both mandatory with Default template. It is no longer possible to submit such form as the browser is now aware if the mandatory property on both fields.

I'm trying to reproduce with an other mandatory field.

**Comment by btry** [comment]
I did a try with mandatory observer, then mandatory category.

In both cases, when the submission is rejected, I go back to an empty ticket; all inputs seems lost. There is maybe a regression compared  to GLPI 9.5, and it is no longer possible to reproduce this issue.

**Comment by cconard96** [comment]
All related PRs have been merged. The issues listed here should all be resolved now.
