### ISSUE TITLE
[Beta 10] Ticket status cannot be changed directly from NEW to Closed or Solved 

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#10299]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10 Beta

### Bug description

Ticket status cannot be changed directly from NEW to Closed or Solved.
No error, the status is reset to New after clicking on Save.

**Comment by cconard96** [comment]
It seems intentional. There is a specific check in the code for updating that ignores the status change when going from New to anything else when the Ticket, Change, or Problem are not assigned. This code has existed for at least 9 years, so it doesn't seem to be a change with GLPI 10.

**Comment by husisusi** [comment]
Hum! but in GLPI version 9.5.6 i can do it.
![grafik](https://user-images.githubusercontent.com/8606735/148853448-b3468a01-f979-4704-98f3-552e0b19c62c.png)

**Comment by orthagh** [comment]
Please check the lifecycle tab of your current profile on both instances.
Maybe the 10 instance forbid this change:

![image](https://user-images.githubusercontent.com/418844/149530922-de745815-f446-43d3-837f-65e414d99c40.png)

**Comment by orthagh** [comment]
On my current instance, i have no problem to close a new ticket

**Comment by cconard96** [comment]
> Indeed, the status update doesn't work with this state, i'll check. @cconard96 do you mind point the historic code you found ? We may drop it, but i want to check some history

https://github.com/glpi-project/glpi/blob/79f9719d7995cc6bd38661cbc03fa0601824b236/src/CommonITILObject.php#L1532-L1553

**Comment by husisusi** [comment]
Thank you @cconard96.
Yes that's it. It works after I changed line 1551 to (only to test):
`             $this->fields['status'] = $this->fields['status']; `

**Comment by cconard96** [comment]
Fixed in #10386
