### ISSUE TITLE
Inconsistency in Contract, 'Items' tab when the item is a template

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#103]
0.85 & 0.90 (also 0.84)
Add a contract to a computer TEMPLATE (or monitor, phone...).
In the Items tab of the contract, the template counts +1 (between ()) but is not displayed in the list.
It also impacts the 'max nb of items'.
![screenshot from 2015-09-06 21 03 36](https://cloud.githubusercontent.com/assets/9383475/9706111/6dede87c-54db-11e5-942e-db254094e75a.png)
I don't know whether a template should be displayed in this list, or not.
But at least, the nbr of items (between ()) and the list of items must be consistent.
And I think that the template should not impact the 'max nbr of items'.

**Comment by blerohellec** [comment]
The nbr of items between () is now correct. The (computer, monitor...) template no longer counts for 1.

But the Items tab of a contract still looks like an item is present but invisible (see previous screencopy). It still impacts the max nbr of items. It lets add an item when the max nbr of items has already been reached.
And something I've just noticed : in the contracts list, add the 'Number of items' to the view -> the template counts for +1.

How is it supposed to work ?

**Comment by yllen** [comment]
Is your contract created in root-entity linked with item in sub-entity? or the contrary?

**Comment by yllen** [comment]
No answer to my question?

**Comment by orthagh** [comment]
I close without answers.
Reopen if you precisions
