### ISSUE TITLE
[10 Beta] "script" folder desappear

### ISSUE THREAD

**Issue by cyrakuse** [glpi-project/glpi#10310]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10 Beta

### Bug description

The folder "script" has desappeared and we can't synchronize LDAP with ldap_mass_sync.php

**Comment by cconard96** [comment]
All scripts were previously deprecated and replace with CLI commands in a previous version. They were removed in this version.

Changelog excerpt:

```
Deprecated scripts/ldap_mass_sync.php has been removed in favor of glpi:ldap:synchronize_users command available using bin/console
Deprecated scripts/compute_dictionary.php has been removed in favor of glpi:rules:replay_dictionnary_rules command available using bin/console
Deprecated scripts/softcat_mass_compute.php has been removed in favor of glpi:rules:process_software_category_rules command available using bin/console
```

**Comment by cyrakuse** [comment]
Ok. Sorry i didn't show this information
