### ISSUE TITLE
GLPI 10.0 Cyrillic display problem 

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#10313]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 Beta

### Bug description

Good afternoon, there is a problem with GLPI 10 and the transmitted data from GLPI-Agent-1.1-gitf5824389-x64.
The problem lies in the encoding of the Cyrillic alphabet, if the inventory is carried out in automatic mode, then I have all the text that contains the Cyrillic alphabet turns into symbols. If I import the local inventory, then all the text is displayed correctly.
Tell me how to fix this problem?

### Your GLPI setup information

GLPI 10.0.0-dev ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:ru_RU

Operating system: Linux glpi.isbank.ru 5.4.17-2136.302.7.2.el8uek.x86_64 #2 SMP Wed Jan 5 19:12:52 PST 2022 x86_64
PHP 7.4.19 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, soap, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="24M" 
Software: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k mod_perl/2.0.11 Perl/v5.26.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.73
Server Software: MariaDB Server
	Server Version: 10.3.28-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/GLPI
	Host info: Localhost via UNIX socket
	
PHP version (7.4.19) is supported.PHP version (7.4.19) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.3.28) is supported.Database engine version (10.3.28) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend
OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

### Anything else?

![1](https://user-images.githubusercontent.com/97535165/149174431-5ab8d435-e314-4772-bb53-7b1eaee39632.png)

**Comment by g-bougard** [comment]
Hi @Badkempachi 
this is a GLPI-Agent issue and this is indeed a duplicated of [Page Code Trouble in inventory](https://github.com/glpi-project/glpi-agent/issues/44).

**Comment by g-bougard** [comment]
Hi @Badkempachi 

can you test with [latest GLPI-Agent nightly build](https://nightly.glpi-project.org/glpi-agent/) as [2559b0b](https://github.com/glpi-project/glpi-agent/commit/2559b0b652098f48a434d55e618fcaf91e7bf19b) should probably fix this problem and report you test result in the [related glpi-agent issue](https://github.com/glpi-project/glpi-agent/issues/44) ?

Thank you
