### ISSUE TITLE
[GLPI 10 RC1]Reminder widget viewed from shared dashboard showing reminders to non targeted users

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10353]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

[glpi 10.0 RC1]

### Bug description

When a targeted user for a reminder shares a dashboard which includes the reminder widget to a user which was not targeted by this reminder, then this non targeted user will still see the reminder  on this dashboard(and not the reminders he was targeted for in the first place)

Shouldn't the proper behavior be : show the relevant reminders for the user even if he is viewing a shared dashboard?

(I'ts just great to be able to communicate with lower users just by staying on the same page by switching dashboards and adding notes to it while keeping the relevant reminders.)

### Steps To reproduce
0° Create a reminder targetting user 1
1° Have user1 to share a dashboard which has the reminder widget on it
2° View the shared dashboard on user 2 profile and see that even if user 2 is not targeted by the reminder, he stills sees its content.

### Your GLPI setup information

GLPI 10 beta rc1
Debian 4.19.208-1 (2021-09-29) x86_64
PHP version (7.4.27)

![Screenshot_20220228_220907](https://user-images.githubusercontent.com/63743077/156059782-8bb71d8c-7111-469c-a24c-f4627e1ffa47.png)
_

**Comment by joomlafun** [comment]
Hi,

From the screenshot provided, you may seen the guest user connected, however he sees the administrator reminders just because the administrator shared a dashboard with him.(the user should see its own reminders only)

**Comment by cedric-anne** [comment]
@joomlafun 

Could you test #13611 ?
