### ISSUE TITLE
GLPI 9.1RC2 is incompatible with PHP 5.4

### ISSUE THREAD

**Issue by fpoirotte** [glpi-project/glpi#1035]
Dear GLPI developers,

GLPI 9.1RC2 is supposed to be compatible with PHP 5.4 (see https://github.com/glpi-project/glpi/blob/9.1-RC2/composer.json).
But in fact, the code in ``inc/api.class.php`` calls ``array_column()`` which was only introduced starting with PHP 5.5 (see http://php.net/manual/en/function.array-column.php).

If support for PHP 5.4 is something you strive for, the following (dirty patch) adds an emulation function that replicates the behaviour of array_column() on < PHP 5.5.
```
--- inc/api.class.php.orig      2016-09-22 14:05:21.065000000 +0200
+++ inc/api.class.php   2016-09-22 14:09:49.400000000 +0200
@@ -31,6 +31,21 @@
  --------------------------------------------------------------------------
  */
 
+// Polyfill for array_column() on < PHP 5.5.
+if (!function_exists('array_column')) {
+    function array_column(array $input, $column_key, $index_key = null) {
+        $res = array();
+        foreach ($input as $values) {
+            if ($index_key !== null) {
+                $res[$values[$index_key]] = $values[$column_key];
+            } else {
+                $res[] = $values[$column_key];
+            }
+        }
+        return $res;
+    }
+}
+
 /** @file
 * @brief
 */
```

Otherwise, please upgrade the dependencies to reflect the incompatibility.

Regards,
François

**Comment by tomolimo** [comment]
Hello,
Can you check if you have the `vendor/ramsey` folder in glpi forlder?
Regards,
Tomolimo

**Comment by orthagh** [comment]
See #857

**Comment by tomolimo** [comment]
I confirm that with this `ramsey` library it's working

**Comment by fpoirotte** [comment]
Indeed, this is a duplicate of #857 which I somehow overlooked. Closing now.
