### ISSUE TITLE
Rights problem to assign a ticket without the update right 

### ISSUE THREAD

**Issue by glpi123** [glpi-project/glpi#10364]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.5 and 9.5.6

### Bug description

Here are the rights assigned to the profile :
- Purge   
- See all tickets
- See assigned
- Assign   
- Beeing in charge
- Change the priority

![image](https://user-images.githubusercontent.com/97961877/150322215-b1c14a3c-afc8-4797-abbb-de4e78b3a774.png)

When this profile want to assign a group to the ticket, he choose the group and clic the botton "Save", this the message is displayed :
"you dont have permission to perform this action"

### Relevant log output

No logs in glpi/files/_logs

### Page URL

front/ticket.form.php

### Steps To reproduce

Tickets->assign ticket to a group->save

### Your GLPI setup information

Operating system: Linux 4.12.14-lp151.28.32-default x86_64
PHP 7.2.5 apache2handler (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, session, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Server Software: SUSE package
	Server Version: 10.2.25-MariaDB
	Server SQL Mode: 
	Parameters: brtquser@localhost/glpidb
	Host info: Localhost via UNIX socket

**Comment by glpi123** [comment]
please any help

**Comment by cedric-anne** [comment]
Hi,

Try with no active plugins, and please, provide logs, GLPI setup information, ...

Regards

**Comment by glpi123** [comment]
hello cedric-anne,
I tried with the version 9.5.6(with no plugins), i have the same problem.
i add the information u ask in my description.
waiting for your response. 
Best regards

**Comment by glpi123** [comment]
Hello,
My hierarchy is requesting migration to the new version and this problem is blocking for users. If you can fix this bug, I will be very grateful.

**Comment by cconard96** [comment]
Fixed via #10874
