### ISSUE TITLE
Consumables items associated to a supplier cannot be viewed in the items tab for supplier.

### ISSUE THREAD

**Issue by mecmav** [glpi-project/glpi#10377]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Consumables items associated to a supplier cannot be viewed in the items tab for supplier.

When a computer are associated with a supplier, can be viewed in the list for Supplier > Items. With consumables no

### Steps To reproduce

associate a consumable to a supplier.
now in Management > Supplier > Items, nothing has been shows.

associate a computer to a supplier.
now in Management > Supplier > Items, the computer is there.

**Comment by cedric-anne** [comment]
Hi,

I do not really know this part of GLPI, but I take a look on the code and I saw that `ConsumableItem`, `CartridgeItem` and `Software` and intentionnally excluded from the results here, and this has been done like that from the beginning ( see https://github.com/glpi-project/glpi/commit/6ba69088c54981f9ce615d6d455db38952e82809#diff-36c805a2ad73c630c6196b1a4a85b36cc20b47e2026f2eb92a6c8fee7d5c433cR68 ). As I do not know why it has been done like that, I cannot help anymore.

Regards

**Comment by mecmav** [comment]
Hi,

I have tryed a analysis in the given link above, but I haven't this these files on my current version of glpi.

Detail: I'm using GLPI 9.5.6.

Should I create these files ?

**Comment by cedric-anne** [comment]
Hi,

I was pointing the fact that it is done like that from the beginning. The exclusion list is now here : https://github.com/glpi-project/glpi/blob/84597f7e02b2ff9e12ba2bd0ee783ad7ca9a09bb/inc/infocom.class.php#L2081

Regards

**Comment by mecmav** [comment]
OK, Now I understood.

When I removed the "ConsumableItem" from line 2082, now in the Supplier > Tab Items, I can see the consumables relationed to this supplier.

Thanks by the directioning.

I believe this thread can be solved or closed.
