### ISSUE TITLE
Undefined index: internal_time_to_resolve when

### ISSUE THREAD

**Issue by nenes82** [glpi-project/glpi#10376]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

When the start date of task in a change is updated the error Undefined index: internal_time_to_resolve occured

### Relevant log output

```shell
PHP Notice:  Undefined index: internal_time_to_resolve in C:\Projects\GLPI\glpi9.5\inc\commonitilobject.class.php on line 1227
```

### Steps To reproduce

Create a change
Create a task
Update start date
save

### Anything else?

The "glpi_changes" table does not contain field internal_time_to_resolve.
Workaround: Add an isset test line 1226 ?

**Comment by cconard96** [comment]
I cannot recreate the issue on GLPI 10 or GLPI 9.5.7. The code that this error was encountered wasn't called in either version when changing the start date of a task in a Change. It only seemed to be run when updating a task if it was within a Ticket.
Can you test again with GLPI 9.5.7?

**Comment by cedric-anne** [comment]
I close this issue due to lack of feedback. Feel free to reopen.
