### ISSUE TITLE
Inventory : String expected at Memory.removable

### ISSUE THREAD

**Issue by BidoumDev** [glpi-project/glpi#10370]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0

### Bug description

Hello,

Inventory from windows returns the following part :
...
     "memories": [
         {
            "capacity": 8192,
            "caption": "Mémoire physique",
            "description": "Mémoire physique",
            "formfactor": "DIMM",
            "numslots": 0,
            "removable": 0,
            "serialnumber": "00000000",
            "speed": "2933",
            "type": "Unknown"
         },
...

But when I tri to import the file, the server respond:
    [0] => JSON does not validate. Violations:
String expected, 0 received at #->$ref[file~2///var/www/glpi/vendor/glpi-project/inventory_format/inventory.schema.json]->properties:content->properties:memories->items[0]:0->properties:removable

If I manually edit the file, and set:
 removable": ""
it works well

For additionnal information:
I tried with two different windows and had the same error 
- Windows 10 native computer
- Windows Server 2012 on vmware ESXI
But no issue from linux on the same vmware ESXI

Thank you

### Steps To reproduce

From any windows version of glpi-agent

**Comment by g-bougard** [comment]
Hi @BidoumDev 
this problem has still been addressed in GLPI-Agent. I guess you're using GLPI-Agent 1.0. Can you try with a [GLPI-Agent nightly build](https://nightly.glpi-project.org/glpi-agent) ?

**Comment by BidoumDev** [comment]
Hi !
It works well out of the box with GLPI-Agent-1.1-git10d038aa-x64.msi
Thank you
