### ISSUE TITLE
[GLPI 10] Images lost after Update

### ISSUE THREAD

**Issue by marcywi** [glpi-project/glpi#10390]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-beta

### Bug description

Good morning,

after updating from 9.5.6 to 10.0 beta, embedded images no longer work in existing (older) tickets. Images added after the update are not a problem.

It seems to be a URL issue somehow, as the old images have the following link:

![grafik](https://user-images.githubusercontent.com/46995340/150487684-7ca83162-3588-4479-adfd-b300cb018c7f.png)

The link of the new images looks ok:

![grafik](https://user-images.githubusercontent.com/46995340/150487819-ac5da133-c9f6-45ed-a5fb-c1e18be69372.png)

Has anyone else encountered this problem and been able to fix it if necessary?

### Relevant log output

```shell
no
```

### Page URL

no

### Steps To reproduce

Any graphic in tickets before the update

**Comment by flegastelois** [comment]
Confirmed on my side too, ```glpi_itilfollowups.content``` example:
```
&lt;p&gt;&lt;a href=&quot;/front/document.send.php?docid=5961&amp;tickets_id=3586&quot; target=&quot;_blank&quot; &gt;&lt;img alt=&quot;32be5e8d-f37490bd-61e157fbe5de69.66687043&quot; width=&quot;383.2767857142857&quot; src=&quot;/front/document.send.php?docid=5961&amp;tickets_id=3586&quot; /&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;Appel &lt;/p&gt;
```

**Comment by marcywi** [comment]
yeah :) here the entry before upgrade to glpi 10-beta:

_&lt;p&gt;&lt;a href=&quot;/front/document.send.php?docid=2605&amp;tickets_id=2020112642&quot; target=&quot;_blank&quot; &gt;&lt;img alt=&quot;4249f5d0-3965ae33-61b720675f5712.34248119&quot; width=&quot;289.43340425531915&quot; src=&quot;/front/document.send.php?docid=2605&amp;tickets_id=2020112642&quot; /&gt;&lt;/a&gt;&lt;/p&gt;_

and here the entry new pictures after upgrade to glpi 10-beta:

_&#60;p&#62;&#60;a href="/front/document.send.php?docid=2749&#38;tickets_id=2020112642" target="_blank" &#62;&#60;img alt="4249f5d0-253608e2-61ea54a6308456.18638955" width="165.75075075075074" src="/front/document.send.php?docid=2749&#38;tickets_id=2020112642" /&#62;&#60;/a&#62;&#60;/p&#62;_
