### ISSUE TITLE
Opening date erased on creation of ticket

### ISSUE THREAD

**Issue by glpi123** [glpi-project/glpi#10392]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

I just migrated GLPI from version 9.2 to version 9.5.5
I noticed that some tickets are saved with the opening date erased on creation, knowing that this field is hidden in the template ticket used on creation with a standard interface.
On the DB, the column "date"  is empty while the column "date_creation" is well informed.
Here is the template used : 
![image](https://user-images.githubusercontent.com/97961877/150512369-28cc33de-64cc-4f6a-a871-d0b110f805dd.png)
The opening date is erased : 
![image](https://user-images.githubusercontent.com/97961877/150513538-674438d6-a160-4856-a450-0f2a192657cc.png)

### Relevant log output

```shell
No logs found
```

### Page URL

front/ticket.form.php

### Steps To reproduce

1. create ticket trough the template 
2. clic save
3. opening date erased  

### Your GLPI setup information

Operating system: Linux 4.12.14-lp151.28.32-default x86_64
PHP 7.2.5 apache2handler (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, ctype, curl, date, dom,
exif, fileinfo, filter, ftp, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
pdo_sqlite, session, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M"
Software: Apache ()
Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36
Server Software: SUSE package
Server Version: 10.2.25-MariaDB
Server SQL Mode:
Parameters: brtquser@localhost/glpidb
Host info: Localhost via UNIX socket

**Comment by cconard96** [comment]
I tested with GLPI 10 using a template that had Opening Date hidden and the created tickets had the `date` and `date_creation` fields both set properly.
This may have been fixed in 9.5.6 or 9.5.7, or was inadvertently fixed during v10 development.

**Comment by cedric-anne** [comment]
@glpi123 

Can you find a reproducible case on [GLPI nightly build](https://nightly.glpi-project.org/glpi/) (either 9.5 or master) ?
We are not able to reproduce the issue, but, also, we already have issues related to empty dates on tickets, so I guess there is an edge case that have to be fixed (or that have been fixed in 9.5.6+).

**Comment by glpi123** [comment]
Hello cedric-anne
I forgot to specify that the problem is not reproducible for me in the test instance. This is an issue that occurred only after migrating my production instance, and this happen only for some tickets using the template describe below.

**Comment by cedric-anne** [comment]
Hi,

The issue should be fixed with an update to 9.5.7 version of GLPI (see #9595).

Could you confirm ?

**Comment by glpi123** [comment]
Hello cedric anne,
Knowing that the problem happen only in the production instance and a migration of GLPI is initiated by my hierarchy, the update to 9.5.7 version is not planned for the moment.
In any case, thank you for your reactivity.
