### ISSUE TITLE
Problem on setup installation in spanish.

### ISSUE THREAD

**Issue by inver32** [glpi-project/glpi#1040]
On first login the page is blank.
Error log apache:

PHP Fatal error:  Uncaught exception 'Zend\I18n\Exception\OutOfBoundsException' with message 'Provided index 1 does not exist in plural array in xxxx/glpi/front/login.php

 Zend\I18n\Translator\Translator->translatePlural('Task category', 'Task categories', 2, 'glpi'), referer: http://www.xxxxxx.com/glpi/front/login.php

**Comment by yllen** [comment]
can you give error in glpi/files/_log/php_error.log?

**Comment by AnaelMobilia** [comment]
Hello @inver32 
I just try a clean install on Spanish (Espana).
I didn't get any error message.

Could you please, try again, and in case of problem, provide us the "glpi/files/_log/php_error.log" files requested by @yllen 

Regards,
Anael

**Comment by trasher** [comment]
Requested informations not provided. Closing.
