### ISSUE TITLE
[GLPI 10] Affected technicians of a ticket

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10413]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

When you edit a ticket, the list of technician displays all users and not only technicians & the users are duplacated (i think its due to theirs emails)

![image](https://user-images.githubusercontent.com/13178158/150677402-030800eb-43d3-4653-abea-b20a74921e95.png)

### Page URL

http://localhost/glpi/front/ticket.form.php?id=XX

**Comment by tsmr** [comment]
Thanks for your correction. However this solves part of the problem. It remains that we can assign tickets to people who do not have the right to process tickets

**Comment by cconard96** [comment]
Second issue should be fixed by #10425

**Comment by tsmr** [comment]
ok for me. Thanks
