### ISSUE TITLE
Reservations won't show in reservations item calendar from Simple Interface

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10421]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 beta

### Bug description

Hi,

Reservations are listed on the users profile, but when checking the calendar of all reservable items from the user account, then there is no reservation visible.

I must add that after booking an item I did not get a reservation confirmation pop up and that I get to be on the reservation form again.

By the way, shouldn't there be a user reservation page listing all reservations made by the logged in user?

![image](https://user-images.githubusercontent.com/63743077/150699450-f84e64c2-908b-4225-b4dd-79303d723acb.png)
![image](https://user-images.githubusercontent.com/63743077/150699656-e6c7b99c-e625-436e-9c68-7da91511a2f3.png)
![image](https://user-images.githubusercontent.com/63743077/150699667-70557216-a46a-4e4b-bb1c-d6b9436bf1a3.png)

### Relevant log output

```shell
No php logs regarding this.
```

### Steps To reproduce

Make a reservation
View all reservations calendar

### Your GLPI setup information

GLPI 10 beta
Debian 4.19.208-1 (2021-09-29) x86_64
PHP version (7.4.27)

### Anything else?

I used impersonate mode but it should not have an impact I guess.

**Comment by cedric-anne** [comment]
Hi,

#11080 should fix this issue.

**Comment by cedric-anne** [comment]
> My GLPI already has all the updates mentioned in the Fix: #11080 but it doesn't show the reservations made by the user.

Please open a new issue and provide all requested informations. #11080 fixed some bugs, so maybe you are facing another one.
