### ISSUE TITLE
Ticket transfert (attached to transfered items)

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#1042]
Code looks bad.

+ see http://forum.glpi-project.org/viewtopic.php?pid=324763#p324763

```
     $query = "SELECT *
                FROM `glpi_tickets`
                LEFT JOIN `glpi_items_tickets`
                   ON `glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`
                WHERE `items_id` = '$ID'
                      AND `itemtype` = '$itemtype'";
```

We have 2 tables

                     $input['id']          = $data['id'];

So which id ? from which table ? Obviously wrong.
 
                     $input['items_id']    = $newID;
                     $input['itemtype']    = $itemtype;

Also wrong, the relation table need to be updated (so bug since 0.85.3...)

**Comment by remicollet** [comment]
For the 1st issue, perhaps a simple
    -       $query = "SELECT *
    +       $query = "SELECT `glpi_tickets`.`id`

**Comment by trasher** [comment]
Isn't it related to #578?

**Comment by remicollet** [comment]
@trasher yes, clearly a duplicate of #578

**Comment by Sismic** [comment]
fix ok
