### ISSUE TITLE
[GLPI 10] The saving of save searches don't save the query

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10430]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

When you create a saved searches, the query field in database is empty

The $input['query'] on prepareInputForAdd is empty

```
[2022-01-24 16:19:22] glpiphplog.INFO: SavedSearch::prepareInputForAdd() in C:\wamp64\www\glpi\src\SavedSearch.php line 327
Array
  (
      [entities_id] => 0
      [is_recursive] => 1
      [itemtype] => Contact
      [type] => 1
      [url] => %2Fglpi%2Ffront%2Fcontact.php
      [name] => test
      [do_count] => 2
      [is_private] => 1
      [users_id] => 6
      [_glpi_csrf_token] => b836dfe069540cf6ed05db7b1c11402b7320a6d336172bd7c410df4905476797
      [_no_history] => 
      [_add] => 1
      [query] => 
  )
   {"user":"6@XXX"} 
```

**Comment by cconard96** [comment]
Confirmed. Issue is with the new "AJAX" search.
The modal to create the saved search gets created when you click the button and it is hard-coded to be the URL that the page was loaded with.

When searching, the URL doesn't change anymore. This is an easy fix, but I still need to find a way to use the current URL instead of the loaded URL for the saved searches.

**Comment by monoamin** [comment]
[#10469](https://github.com/glpi-project/glpi/pull/10469) breaks Saved Searches functionality altogether. The Button does not trigger anything.

**Comment by cconard96** [comment]
Do you have any errors in the browser console when you load the page or click the button?

**Comment by monoamin** [comment]
I manually added the fix into the tarball release of v10, and it seems I made a small error while doing so. I made the neccessary changes, but Saved searches still seem broken.

Upon opening the Save Search window, I get
`tabler.js:6435 Uncaught TypeError: Cannot read properties of undefined (reading 'classList')`

And after clicking Save, I'm redirected to a blank page without errors in the console, and the search is not saved.

**Comment by cconard96** [comment]
I don't know how, but it could be related to the fact I made the patch based on a later version of v10.

I'll check again tonight.

**Comment by cconard96** [comment]
I cannot recreate the issue.

**Comment by monoamin** [comment]
Thanks for looking into it, I will look for the issue elsewhere in our specific installation.

**Comment by mrajema** [comment]
Hello, I have the same issues on 10.0.6. There is a way to fix it please? I have manually modified the three files on my instance but it is not resolved yet. Thank you.
