### ISSUE TITLE
Users count on the dashboard is incorrect if window is resized

### ISSUE THREAD

**Issue by monstermichl** [glpi-project/glpi#10432]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

The dashboard/home "Users" count gets decremented, each time the window is resized while the counter is still counting up.

### Steps To reproduce

1. Import/Create some users (e.g. 300) to make sure that the "Users" counter is running for some time.
2. Resize the window.
3. Resize the window again while the "Users" counter is still running.

### Your GLPI setup information

Operating system: Linux glpi 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64
PHP 7.4.25 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.51 (Debian) (Apache/2.4.51 (Debian) Server at 10.0.0.50 Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.1-MariaDB-1:10.7.1+maria~focal
	Server SQL Mode: 
	Parameters: glpi@MariaDB/glpidb
	Host info: MariaDB via TCP/IP

### Anything else?

Test Setup:
OS: Windows 10 build 19041.1.amd64fre.vb_release.191206-1406.
Browser: Brave 1.34.81

**Comment by cedric-anne** [comment]
Fixed by af247690175191a17767301d1b04e034813a110c.
