### ISSUE TITLE
Problem : Add notifications for "add followup" with "close action" or "resolve action" (Contains the correction)

### ISSUE THREAD

**Issue by titio04** [glpi-project/glpi#1044]
Hi, 

I see a significant regression since multiples versions of GLPI for the notifications.
A lot of people have describe this subject on the forum. But no resolution was posted.

Since the separated windows for the followup (ticket processing window) and the ticket, now it's not possible to send notification to different recipients when you add a followup with different status (Exemple: If you "add a followup" with status resolve or close ...). The notification for the followup was configured to use only two events:
- Add followup
- Update Followup

But on the ticket window, they have a separated events notifications for the status:
- New Ticket
- Update Ticket
- Resolve ticket
- Close Ticket

Reminder: for the ITIL processes, it's important to obtain the same actions  and traceability.

I suggest this simple correction:
- inc\ticketfollowup.class.php line 458

`if ($donotif) {
         $options = array('followup_id' => $this->fields["id"],
                          'is_private'  => $this->fields['is_private']);
         NotificationEvent::raiseEvent("add_followup", $this->input["_job"], $options);
      }`

By 

`if ($donotif) {
         $options = array('followup_id' => $this->fields["id"],
                          'is_private'  => $this->fields['is_private']);
         //NotificationEvent::raiseEvent("add_followup", $this->input["_job"], $options);
         if ($this->input['_status'] == CommonITILObject::CLOSED) {
            NotificationEvent::raiseEvent("add_followup_closed_ticket", $this->input["_job"], $options);    
         } 
         elseif ($this->input['_status'] == CommonITILObject::SOLVED) {
            NotificationEvent::raiseEvent("add_followup_resolved_ticket", $this->input["_job"], $options);
         }
         else {
            NotificationEvent::raiseEvent("add_followup", $this->input["_job"], $options);
        }
      }`
- inc\notificationtargetticket.class.php line 227

`   function getEvents() {

```
  $events = array('new'               => __('New ticket'),
                  'update'            => __('Update of a ticket'),
                  'solved'            => __('Ticket solved'),
                  'rejectsolution'    => __('Solution rejected'),
                  'validation'        => __('Validation request'),
                  'validation_answer' => __('Validation request answer'),
                  'add_followup'      => __("New followup"),
                  'update_followup'   => __('Update of a followup'),
                  'delete_followup'   => __('Deletion of a followup'),
                  'add_task'          => __('New task'),
                  'update_task'       => __('Update of a task'),
                  'delete_task'       => __('Deletion of a task'),
                  'closed'            => __('Closing of the ticket'),
                  'delete'            => __('Deletion of a ticket'),
                  'alertnotclosed'    => __('Not solved tickets'),
                  'recall'            => __('Automatic reminders of SLAs'),
                  'satisfaction'      => __('Satisfaction survey'),
                  'replysatisfaction' => __('Satisfaction survey answer'));
  asort($events);
  return $events;
```

   }`

By

`   function getEvents() {

```
  $events = array('new'               => __('New ticket'),
                  'update'            => __('Update of a ticket'),
                  'solved'            => __('Ticket solved'),
                  'rejectsolution'    => __('Solution rejected'),
                  'validation'        => __('Validation request'),
                  'validation_answer' => __('Validation request answer'),
                  'add_followup'      => __("New followup"),
                  'update_followup'   => __('Update of a followup'),
                  'delete_followup'   => __('Deletion of a followup'),
                  'add_task'          => __('New task'),
                  'update_task'       => __('Update of a task'),
                  'delete_task'       => __('Deletion of a task'),
                  'closed'            => __('Closing of the ticket'),
                  'delete'            => __('Deletion of a ticket'),
                  'alertnotclosed'    => __('Not solved tickets'),
                  'recall'            => __('Automatic reminders of SLAs'),
                  'satisfaction'      => __('Satisfaction survey'),
                  'replysatisfaction' => __('Satisfaction survey answer'),
          'add_followup_closed_ticket'      => __('New Followup - Closing of the ticket'),
          'add_followup_resolved_ticket'      => __('New Followup - Ticket solved'));
  asort($events);
  return $events;
```

   }`
- install\mysql\glpi-9.1-empty.sql line 3948

Add a line

`
INSERT INTO`glpi_notifications`VALUES ('5','Add Followup','0','Ticket','add_followup_closed_ticket','mail','4','','1','1','2010-02-16 16:41:39',NULL);
INSERT INTO`glpi_notifications`VALUES ('5','Add Followup','0','Ticket','add_followup_resolved_ticket','mail','4','','1','1','2010-02-16 16:41:39',NULL);
`

I tested on the GLPI version 0.90.1 , 0.90.5 and 09.91 RC2, and it"s OK

**Comment by arwinfds** [comment]
Hi,
After making the changes in above mentioned files, assistance (tickets) tab is not loading.
Can you upload the files that you modified.
I am using GLPI 90.5 
Arwin

**Comment by trasher** [comment]
#1400 duplicates this one

**Comment by abelmferreira** [comment]
These pieces of codes worked perfectly in 9.3.1!
Is there any reason not to have been implemented for everyone?

**Comment by tguichard25** [comment]
Une maj pour la 9.5?
