### ISSUE TITLE
assign ticket to user

### ISSUE THREAD

**Issue by fabbrofabbro** [glpi-project/glpi#1046]
how can i assign an open ticket to a user?
i see only group and supplier
![profile](https://cloud.githubusercontent.com/assets/22395190/18786698/8f25b2d0-819f-11e6-8e68-8e4de1420449.jpg)
![assistance](https://cloud.githubusercontent.com/assets/22395190/18786699/8f275ab8-819f-11e6-99cd-b618204eefbe.jpg)
![glpi](https://cloud.githubusercontent.com/assets/22395190/18786727/b24e8890-819f-11e6-825b-8f96ada4021e.jpg)

**Comment by yllen** [comment]
You assign a user to a ticket from ticket form
