### ISSUE TITLE
Display with nederlands language

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1048]
http://forum.glpi-project.org/viewtopic.php?id=155397

**Comment by orthagh** [comment]
![screenshot](https://lh5.googleusercontent.com/_jXHPK5kZUuPB5ajx6ubf-bUBnVPHp_qFDhVwFhHE2-E2ta_SDkBu8eBma230FOBXcAm_K0EDJbtiG0=w1855-h990-rw)
