### ISSUE TITLE
[GLPI 10.0 BETA] Assigned a ticket : Assigning a ticket displays all users and only technicians should display

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10498]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10 beta

### Bug description

Hello,

On the glpi 10.0 beta version, when I want to create a ticket and assign this ticket. Glpi 10 displays all users but it must have only Technicians.

With version 9.5.x, the atttbution correctly displays technicians

Version 10.0 : show everyone
![image](https://user-images.githubusercontent.com/68054991/151951413-84abe0a8-9c2b-40e4-b608-2fe5c5fdae15.png)

Version 9.5.x : Show correctly the technians only
![image](https://user-images.githubusercontent.com/68054991/151951632-2e9d7a1f-fff0-486f-9535-51de756ba7d5.png)

I don't know if this bug has been reported

I tested on the same database on version 9.5.7 and 10.0

### Page URL

/front/ticket.form.php

### Steps To reproduce

1 Create th ticket
2 assign ticket

**Comment by steph461** [comment]
I looked at the profiles of glpi 10.0, it corresponds well with version 9.5.x

**Comment by cedric-anne** [comment]
Hi,

It duplicates #10413 and should be fixed by #10425.
