### ISSUE TITLE
Email alert of expired certificates or contracts does not work.

### ISSUE THREAD

**Issue by moisesdfelix** [glpi-project/glpi#10507]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.5

### Bug description

Good evening, for a long time I never used the notifications module for administrative and/or financial information such as expired certificate notifications, contracts or others. Expired certificate alert notifications are not working. 
I would like help knowing where to start checking why expired certificate notifications are not being sent via email. 
There are no errors in the logs, marketing place notifications and ticket opening are working normally.

![PrintScreen-2022_4](https://user-images.githubusercontent.com/50854086/152076018-af4c47d3-c1ce-4d20-a4e2-58c6130d2b7f.png)
![PrintScreen-2022_3](https://user-images.githubusercontent.com/50854086/152076025-5507ecca-5373-472e-888c-dc09c11a34f1.png)
![cert expirado](https://user-images.githubusercontent.com/50854086/152076528-926b49fc-6714-40f7-ac13-ac51918eb185.png)

### Relevant log output

```shell
"0 Action completed, completely processed..."
```

### Steps To reproduce

1. Configure > automatic actions > click on the Certificates item, I execute the action but I don't receive any notification.

### Your GLPI setup information

PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is not presentCAS extension is not present
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.1.48) - Perfect!Database version seems correct (10.1.48) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

**Comment by cconard96** [comment]
Please include log output from `files/_log/php-errors.log`.

**Comment by cedric-anne** [comment]
Hi,

Can you ensure that these alerts are enabled in your entity configuration ?

![image](https://user-images.githubusercontent.com/33253653/155307916-4264978b-ad3c-4ce7-a57b-09a89e062801.png)


Regards

**Comment by 99net** [comment]
Same for licences and certyficates.

**Comment by moisesdfelix** [comment]
> Hi,
> 
> Can you ensure that these alerts are enabled in your entity configuration ?
> 
> ![image](https://user-images.githubusercontent.com/33253653/155307916-4264978b-ad3c-4ce7-a57b-09a89e062801.png)
> 
> Regards

where can i see this option?

**Comment by cedric-anne** [comment]
> > Hi,
> > Can you ensure that these alerts are enabled in your entity configuration ?
> > ![image](https://user-images.githubusercontent.com/33253653/155307916-4264978b-ad3c-4ce7-a57b-09a89e062801.png)
> > Regards
> 
> where can i see this option?

In `Administration` > `Entities`, you can edit each entity configuration. In the entity edit page, you will find this option in the `Notifications` tab.

**Comment by cedric-anne** [comment]
Please include log output from `files/_log/php-errors.log`.

**Comment by cedric-anne** [comment]
Comment initially posted on https://github.com/glpi-project/glpi/issues/10497

> #6799 was finally a bad idea, as it never worked.
>
> There are many solutions to this.
>
> 1) Remove these targets (this is easy to do, but not having these targets may be considered as a missing feature).
>
> 2) Add all concerned technicians to the notification. It would require to change recipient types from `Notification::ITEM_TECH_IN_CHARGE` to a specific value, so we could handle this in `NotificationTargetCertificate::addSpecificTargets()`. Problem is that each certificate may be assigned to a different technician, so each technician may be concerned only by a few items of those mentioned in the notification, and it can be confusing.
>
> 3) Replace grouped notifications by unitary notifications. Migrating notification content may be tricky, so we would keep existing grouped notifications during update, but prevent creation of new ones by "hidding" them in the creation form. People would be able to create new unitary notifications if they want to use the technician/group in charge recipients.
>
> I prefer the 3rd solution, but it may be a bit late to fix this in GLPI 10.0.


We have to fix this.
