### ISSUE TITLE
[GLPI 10] - Bug install without SElinux on the server

### ISSUE THREAD

**Issue by OfficeLink** [glpi-project/glpi#10504]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

In the installation, after clicking on "install", the GLPI is not passing step 0, it does not do the compatibility check.

Problem occurs when SElinux is not activated.
Test scenario:
Server: Almalinux with cPanel.
When using cPanel SElinux is turned off and apparently this new version is conflicting in the check.

![Problem](https://suporteti.cortical.com.br/glpi10.png)

### Relevant log output

```shell
[2022-02-01 16:27:01] glpiphplog.WARNING: Test logger  
[2022-02-01 16:27:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function Glpi\System\Requirement\exec() in /home/cortical/suporteti/src/System/Requirement/SeLinux.php at line 76
  Backtrace :
  src/System/Requirement/AbstractRequirement.php:108 Glpi\System\Requirement\SeLinux->check()
  src/System/Requirement/AbstractRequirement.php:150 Glpi\System\Requirement\AbstractRequirement->doCheck()
  .../twig/twig/src/Extension/CoreExtension.php:1544 Glpi\System\Requirement\AbstractRequirement->isOutOfContext()
  ...a690e74f3f06388b40bf93b88670d7ba8c324b44.php:59 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_1061da1f9510777c1b2683d457cd5ef84543f3573936e2e7188a61903f45c822->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1268 Twig\TemplateWrapper->render()
  ...e626e2c023824fb5c9099ba09622a74392b52042.php:45 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_3526bd10872ecad8f432fbe40d87b6f8b5dffe1c1967f63a421a028e1974ffe7->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  install/install.php:137                            Glpi\Application\View\TemplateRenderer->display()
  install/install.php:559                            step1()
```

### Steps To reproduce

1 - Installed Almalinux.
2 - PHP 8.1.2 and MariaDB 10.5.13
3 - Installed all dependencies required by GLPI.
4 - SELinux disabled.
5 - Upload GLPI files
6 - Through the web interface, starting the installation.

### Anything else?

I commented out line 123 of the "RequirementsManager.php" file
and I managed to proceed with the installation as shown below.

[code] //$requirements[] = new SeLinux();[/code]

![OK](https://suporteti.cortical.com.br/glpi10_ok.png)

**Comment by cconard96** [comment]
Looks like the check is causing an exception because PHP's exec function is disabled. This may be a default or forced for cPanel as a security feature.

**Comment by trasher** [comment]
@OfficeLink please test with changes @cconard96 proposes on #10505

**Comment by OfficeLink** [comment]
@cconard96 Perfect. With this fix everything went well in the installation.
