### ISSUE TITLE
Error importing users from active directory

### ISSUE THREAD

**Issue by J0s388** [glpi-project/glpi#10517]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.7

### Bug description

Good day, I updated GLPI to version 9.5.7 and it throws me an error when importing users from the active directory.

Connection tests with the server were carried out and they are satisfactory.

can you help me, please.

Attached Image of the error and the connection test.

![Screen Shot 2022-02-02 at 9 42 18 AM](https://user-images.githubusercontent.com/98889253/152167014-9a953e30-63da-416d-8f95-cf179ce97bd7.png)
![Screen Shot 2022-02-02 at 9 43 23 AM](https://user-images.githubusercontent.com/98889253/152167037-1407ffb5-f52e-4ef3-867d-3bf94c097104.png)

### Your GLPI setup information

Server
--
Operating system: Linux glpi 5.4.0-96-generic #109-Ubuntu SMP Wed Jan 12 16:49:16 UTC 2022 x86_64 
PHP 8.1.1 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) 
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 170.16.1.37 Port 80) 
        	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:96.0) Gecko/20100101 Firefox/96.0
 Server Software: (Ubuntu) 	
                             Server Version: 8.0.27-0ubuntu0.20.04.1 	
                             Server SQL Mode:  	
                             Parameters: root@localhost/glpi 	
                             Host info: Localhost via UNIX socket 	 
PHP version is at least 7.2.0 - Perfect! 
Sessions support is available - Perfect! 
Allocated memory > 64 Mio - Perfect! 
mysqli extension is installed
 ctype extension is installed
 fileinfo extension is installed 
json extension is installed 
mbstring extension is installed 
iconv extension is installed 
zlib extension is installed 
curl extension is installed 
gd extension is installed 
simplexml extension is installed 
intl extension is installed
 ldap extension is installed 
apcu extension is installed 
Zend OPcache extension is installed
 xmlrpc extension is installed 
exif extension is installed 
zip extension is installed 
bz2 extension is installed 
sodium extension is installed
 Database version seems correct (8.0.27) - Perfect!
 Timezones seems loaded in database The log file has been created successfully.
 Write access to /var/www/html/glpi/files/_cache has been validated. 
Write access to /var/www/html/glpi/config has been validated. 
Write access to /var/www/html/glpi/files/_cron has been validated. 
Write access to /var/www/html/glpi/files has been validated. 
Write access to /var/www/html/glpi/files/_dumps has been validated. 
Write access to /var/www/html/glpi/files/_graphs has been validated. 
Write access to /var/www/html/glpi/files/_lock has been validated. 
Write access to /var/www/html/glpi/files/_pictures has been validated. 
Write access to /var/www/html/glpi/files/_plugins has been validated. 
Write access to /var/www/html/glpi/files/_rss has been validated. 
Write access to /var/www/html/glpi/files/_sessions has been validated. 
Write access to /var/www/html/glpi/files/_tmp has been validated. 
Write access to /var/www/html/glpi/files/_uploads has been validated. 
Write access to /var/www/html/glpi/marketplace has been validated. 
Web access to files directory is protected

GLPI_ROOT: /var/www/html/glpi 
GLPI_CONFIG_DIR: /var/www/html/glpi/config 
GLPI_VAR_DIR: /var/www/html/glpi/files 
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace 
GLPI_USE_CSRF_CHECK: 1 
GLPI_CSRF_EXPIRES: 7200 
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
 GLPI_IDOR_EXPIRES: 7200 
GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org 
GLPI_INSTALL_MODE: TARBALL 
GLPI_NETWORK_MAIL: glpi@teclib.com 
GLPI_NETWORK_SERVICES: https://services.glpi-network.com 
GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 
GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache 
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron 
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps 
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs 
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales 
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock 
GLPI_LOG_DIR: /var/www/html/glpi/files/_log 
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures 
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins 
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss 
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions 
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp 
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads 
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ 
GLPI_I18N_DIR: /var/www/html/glpi/locales 
GLPI_VERSION: 9.5.7 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

Plugins list
--
dashboard            Name: Dashboard                      Version: 0.9.9      State: Enabled 	
fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	
livechat             Name: Livechat                       Version: 1.0.4      State: Enabled 	
Notifications        Name: Notifications                  Version: 9.4+1.0    State: Installed / not activated 	
pdf                  Name: Print to pdf                   Version: 2.0.0      State: Enabled 	
tasklists            Name: Tasks list                     Version: 1.6.2      State: Enabled 	
telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Enabled

**Comment by cconard96** [comment]
Please include any entries from the `files/_log/php-errors.log` and `files/_log/sql-errors.log` files from the time you tried importing the user(s).

**Comment by J0s388** [comment]
Ok, I attach an image with what the php-errors.log log shows
I don't have a log of sql-errors.log
![Screen Shot 2022-02-02 at 4 32 38 PM](https://user-images.githubusercontent.com/98889253/152233200-844135e2-00b8-4b4d-a8c1-9c5b49e8e6bf.png)

**Comment by cconard96** [comment]
Those errors do not seem related. Please try checking your AD server settings in GLPI and re-adding them. It could be possible that the encoding of one or more fields changed so it cannot read it anymore when you import. Most likely it would be and issue with the Connection filter field.

**Comment by cedric-anne** [comment]
I close this as issue seems stale. Feel free to reopen.
