### ISSUE TITLE
Can't create new users - BETA

### ISSUE THREAD

**Issue by Jhamende** [glpi-project/glpi#10510]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

V10 BETA

### Bug description

Can't create new user. 
Only surname field is visible; whil I hit enter I'm getting an error message.
Fresh install. 

### Relevant log output

```shell
[2022-02-02 09:23:37] glpiphplog.WARNING: Test logger
[2022-02-02 09:23:42] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpibeta/src/Html.php line 6626
Compile css/install.scss  {"user":"@vmi572458.contaboserver.net"}
[2022-02-02 09:25:16] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to User::getPictureForUser() must be of the type int, string given, called in /var/www/html/glpibeta/src/User.php on line 6173 in /var/www/html/glpibeta/src/User.php at line 6204
  Backtrace :
  src/User.php:6173                                  User->getPictureForUser()
  src/User.php:2240                                  User->showSystemUserForm()
  src/CommonGLPI.php:655                             User->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

[2022-02-02 09:52:22] glpiphplog.WARNING: Test logger
[2022-02-02 09:54:05] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to User::getPictureForUser() must be of the type int, string given, called in /var/www/html/glpibeta/src/User.php on line 6173 in /var/www/html/glpibeta/src/User.php at line 6204
  Backtrace :
  src/User.php:6173                                  User->getPictureForUser()
  src/User.php:2240                                  User->showSystemUserForm()
  src/CommonGLPI.php:655                             User->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
```

### Steps To reproduce

1. Go to Administration > Users
2. Click "+ Add"
3. Fill only visible field "Surname"
4. hit "Enter

![GLPIAddUser1](https://user-images.githubusercontent.com/14819237/152122974-fc912997-5124-4421-ae11-a829a3f0f19b.PNG)
![GLPIAddUser2](https://user-images.githubusercontent.com/14819237/152122971-efebb1c5-f998-447d-8266-855ce2ed6053.PNG)

### Your GLPI setup information

GLPI 10.0.0-dev ( => /var/www/html/glpibeta)
Installation mode: TARBALL
Current language:en_US

### Anything else?

**Server**
Operating system: Linux vmi572458.contaboserver.net 5.11.0-49-generic #55-Ubuntu SMP Wed Jan 12 17:36:34 UTC 2022 x86_64
PHP 7.4.16 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Apache/2.4.46 (Ubuntu) (Apache/2.4.46 (Ubuntu) Server at glpi.jh-it.be Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Server Software: Ubuntu 21.04
	Server Version: 10.5.13-MariaDB-0ubuntu0.21.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpibetaDBAdmin@localhost/glpibeta
	Host info: Localhost via UNIX socket
	
PHP version (7.4.16) is supported.PHP version (7.4.16) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.5.13) is supported.Database engine version (10.5.13) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpibeta/files/_cache has been validated. Write access to /var/www/html/glpibeta/config has been validated. Write access to /var/www/html/glpibeta/files/_cron has been validated. Write access to /var/www/html/glpibeta/files has been validated. Write access to /var/www/html/glpibeta/files/_dumps has been validated. Write access to /var/www/html/glpibeta/files/_graphs has been validated. Write access to /var/www/html/glpibeta/files/_lock has been validated. Write access to /var/www/html/glpibeta/files/_pictures has been validated. Write access to /var/www/html/glpibeta/files/_plugins has been validated. Write access to /var/www/html/glpibeta/files/_rss has been validated. Write access to /var/www/html/glpibeta/files/_sessions has been validated. Write access to /var/www/html/glpibeta/files/_tmp has been validated. Write access to /var/www/html/glpibeta/files/_uploads has been validated.Write access to /var/www/html/glpibeta/files/_cache has been validated.
Write access to /var/www/html/glpibeta/config has been validated.
Write access to /var/www/html/glpibeta/files/_cron has been validated.
Write access to /var/www/html/glpibeta/files has been validated.
Write access to /var/www/html/glpibeta/files/_dumps has been validated.
Write access to /var/www/html/glpibeta/files/_graphs has been validated.
Write access to /var/www/html/glpibeta/files/_lock has been validated.
Write access to /var/www/html/glpibeta/files/_pictures has been validated.
Write access to /var/www/html/glpibeta/files/_plugins has been validated.
Write access to /var/www/html/glpibeta/files/_rss has been validated.
Write access to /var/www/html/glpibeta/files/_sessions has been validated.
Write access to /var/www/html/glpibeta/files/_tmp has been validated.
Write access to /var/www/html/glpibeta/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpibeta/marketplace has been validated.Write access to /var/www/html/glpibeta/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**GLPI constants**
GLPI_ROOT: /var/www/html/glpibeta
GLPI_CONFIG_DIR: /var/www/html/glpibeta/config
GLPI_VAR_DIR: /var/www/html/glpibeta/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpibeta/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_DOC_DIR: /var/www/html/glpibeta/files
GLPI_CACHE_DIR: /var/www/html/glpibeta/files/_cache
GLPI_CRON_DIR: /var/www/html/glpibeta/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpibeta/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpibeta/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpibeta/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpibeta/files/_lock
GLPI_LOG_DIR: /var/www/html/glpibeta/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpibeta/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpibeta/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpibeta/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpibeta/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpibeta/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpibeta/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpibeta/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpibeta/locales
GLPI_VERSION: 10.0.0-dev
GLPI_SCHEMA_VERSION: 10.0.0-dev@5d5ed159d30f08ffa4fb9065d7c3f64855d5d4e1
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_YEAR: 2021

**Comment by cconard96** [comment]
Hi @Jhamende, this issue has already been fixed since the first beta.
It may be better to test GLPI v10 from the nightly "master" release given the number of fixes and changes made since then.
https://nightly.glpi-project.org/glpi/
