### ISSUE TITLE
[GLPI 10] Error on search "Event" term on search

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10528]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

When we search "Event" Term into GLPI, we have this error : 

![image](https://user-images.githubusercontent.com/13178158/152362958-75b83c1d-566d-4c04-b480-47a146054d97.png)

**Comment by cconard96** [comment]
Should be fixed by #10715
