### ISSUE TITLE
Notification for my changes - email

### ISSUE THREAD

**Issue by trelerele** [glpi-project/glpi#10522]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

When I add a new followup my recipient recieve the email correctly. When I answer it (from the recipient mailbox), a new followup is correctly created in my ticket.

But (and it's strange) the recepient recieve the e-mail for it's own followup when it is added to the ticket ?!

Whenever a profile sends an email to glpi it receives an email with the same content that it has sent.

### Steps To reproduce

1. Sent one email to GLPI.
2. If you are one of the profiles to be notified, you will receive an email with the information you have sent.

**Comment by trelerele** [comment]
I update the information after further testing.

If the user is not created within the GLPI platform, the system works correctly.

If the user is created in the platform with the email information. This is when the bug appears.

**Comment by cconard96** [comment]
This is expected behavior when "Pre-select me as a requester when creating a ticket" is set in a user's preferences.
The default value can be changed in Setup > General on the Default Values tab.

Does the issue still occur with a user that has this option set to No?

**Comment by trelerele** [comment]
I checked the option you mention, and it was already set to NO.
The strange thing is that when the user is not created in the system it works fine. 
But when creating the user with the informed mail is when it fails.

**Comment by trelerele** [comment]
I checked the option you mention, and it was already set to NO.
It still occurs when the option is set to NO.

These are the settings at the time of testing.
![test](https://user-images.githubusercontent.com/18248553/152335773-60b50d34-a73a-498d-ae7b-8df82f931ec5.jpg)

**Comment by trelerele** [comment]
I have checked version 9.5.6 and they have exactly the same problem.
Does anyone know where in the code the notifications are generated? 

I would like to review the code and add a check if needed.

**Comment by cconard96** [comment]
I was wrong, since this is for a followup, it is the "Notifications for my changes" setting in the user's personalization page.
