### ISSUE TITLE
[GLPI 10] Error when import ldap user with manager

### ISSUE THREAD

**Issue by tguichard25** [glpi-project/glpi#10532]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Hello,

When I try to import ldap user with manager i get an error sql 1366.

![image](https://user-images.githubusercontent.com/47602797/152493487-0bdb6287-7599-4303-91ac-bd8617c43d32.png)

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-rc1 ( => /var/www/html/lab_glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux srv-glpi-01 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.mut25.fr Port 88
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.28-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/lab_glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (8.0.28) is supported.
The log file has been created successfully.
Write access to /var/www/html/lab_glpi/files/_cache has been validated.
Write access to /var/www/html/lab_glpi/config has been validated.
Write access to /var/www/html/lab_glpi/files/_cron has been validated.
Write access to /var/www/html/lab_glpi/files has been validated.
Write access to /var/www/html/lab_glpi/files/_dumps has been validated.
Write access to /var/www/html/lab_glpi/files/_graphs has been validated.
Write access to /var/www/html/lab_glpi/files/_lock has been validated.
Write access to /var/www/html/lab_glpi/files/_pictures has been validated.
Write access to /var/www/html/lab_glpi/files/_plugins has been validated.
Write access to /var/www/html/lab_glpi/files/_rss has been validated.
Write access to /var/www/html/lab_glpi/files/_sessions has been validated.
Write access to /var/www/html/lab_glpi/files/_tmp has been validated.
Write access to /var/www/html/lab_glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/lab_glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/lab_glpi
GLPI_CONFIG_DIR: /var/www/html/lab_glpi/config
GLPI_VAR_DIR: /var/www/html/lab_glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/lab_glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/lab_glpi/files
GLPI_CACHE_DIR: /var/www/html/lab_glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/lab_glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/lab_glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/lab_glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/lab_glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/lab_glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/lab_glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/lab_glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/lab_glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/lab_glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/lab_glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/lab_glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/lab_glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/lab_glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/lab_glpi/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/lab_glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/var/www/html/lab_glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/lab_glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/lab_glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/lab_glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/lab_glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/lab_glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/lab_glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/lab_glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/lab_glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/lab_glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/lab_glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/lab_glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/lab_glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/lab_glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/lab_glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/lab_glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/lab_glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/lab_glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/lab_glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/lab_glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/lab_glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/lab_glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/lab_glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/lab_glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/lab_glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/lab_glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/lab_glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/lab_glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/lab_glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/lab_glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/lab_glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/lab_glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/lab_glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/lab_glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/lab_glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/lab_glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/lab_glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/lab_glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/lab_glpi/vendor/symfony/polyfill-php80)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://172.28.10.1', Port: '389', BaseDN: 'DC=MUT25,DC=FR', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=glpi,OU=services,OU=users,OU=DSI,DC=mut25,DC=fr', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc2  State: Installed / not activated

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

Could you paste here the error log ? Your image is a bit small.

Regards

**Comment by tguichard25** [comment]
`[2022-02-04 08:55:45] glpisqllog.ERROR: DBmysql::query() in /var/www/html/lab_glpi/src/DBmysql.php line 360
  *** MySQL query error:
  SQL: INSERT INTO `glpi_users` (`password`, `user_dn`, `date_sync`, `authtype`, `name`, `realname`, `firstname`, `phone`, `mobile`, `comment`, `usertitles_id`, `usercategories_id`, `users_id_supervisor`, `is_deleted_ldap`, `auths>
  Error: Incorrect integer value: '' for column 'users_id_supervisor' at row 1
  Backtrace :
  src/DBmysql.php:1277
  src/CommonDBTM.php:653                             DBmysql->insert()
  src/CommonDBTM.php:1245                            CommonDBTM->addToDB()
  src/AuthLDAP.php:2820                              CommonDBTM->add()
  src/AuthLDAP.php:356                               AuthLDAP::ldapImportUserByServerId()
  src/MassiveAction.php:1175                         AuthLDAP::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1153                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:57                         MassiveAction->process()
  {"user":"2@srv-glpi-01"}
`

**Comment by pcazauran** [comment]
Hi,

Had the same error.
In my situation, it was due to the responsible field, in the user ldap binding setup (Setup > Authentication > LDAP Directory > Users)
In  the user ldap binding setup, it seems to be possible to populate the user responsible field with a ldap parameter.
I firstly tried with the manager ldap parameter. Living blank resolved the issue.
![image](https://user-images.githubusercontent.com/11043179/153213459-ef8856b3-c3de-48cc-855a-8c67da1f1ed0.png)

Regards,

**Comment by cconard96** [comment]
I'm thinking this issue is caused when it tries associating a manager that is not in GLPI yet (or they are but aren't linked to the AD account). I'm in the process of setting up an AD server now to test.
