### ISSUE TITLE
Missed link in Helpdesk -> Panel

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#10538]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10-rc1

### Bug description

After update and maybe in clean installation link in menu "Helpdesk -> Panel" missed. Now is: glpi/front/dashboard_assets.php
Should be: glpi/front/dashboard_helpdesk.php
![Screenshot_229](https://user-images.githubusercontent.com/15270519/152513318-9d3bc757-7256-4d1e-b55c-b7974be51ec3.png)
![Screenshot_230](https://user-images.githubusercontent.com/15270519/152513330-34c3f718-4741-44dc-87a6-288c29a39541.png)

**Comment by SteadEXE** [comment]
I guess this is the correct behavior (probably not user friendly enough), you land on the same page  (the dashboard) and you swap between your dashboard views here:
![image](https://user-images.githubusercontent.com/1759156/152513780-eb2acc84-71df-409f-b9c6-01e32075774f.png)

**Comment by leruetkins** [comment]
> 

It's not helped, system  redirect us to glpi/front/dashboard_assets.php

**Comment by cconard96** [comment]
> > 
> 
> It's not helped, system redirect us to glpi/front/dashboard_assets.php

Did you log out and back in or enable debug mode to force the menu to get recreated?

**Comment by leruetkins** [comment]
> Did you log out and back in or enable debug mode to force the menu to get recreated?

It was answer for [SteadEXE](https://github.com/SteadEXE)
I see, that you solve problem)
