### ISSUE TITLE
Errors occurred inserting default database SQL Error "3780"

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#10530]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-rc1

### Bug description

During update  10-beta to 10-rc1 error uccered:
SQL Error "3780": Referencing column 'agenttypes_id' and referenced column 'id' in foreign key constraint 'agenttypes_id' are incompatible. in query "CREATE TABLE `glpi_agenttypes` ( `id` int unsigned NOT NULL AUTO_INCREMENT, `name` varchar(255) DEFAULT NULL, PRIMARY KEY (`id`), KEY `name` (`name`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC"

Errors occurred inserting default database

After this window says:

PHP Notice (8): Undefined index: version in /var/www/html/glpi/src/Update.php at line 133
PHP Notice (8): Undefined index: version in /var/www/html/glpi/src/Update.php at line 137
PHP Notice (8): Undefined index: language in /var/www/html/glpi/src/Update.php at line 139
PHP Notice (8): Undefined index: version in /var/www/html/glpi/src/Update.php at line 307
Uncaught Exception TypeError: Argument 1 passed to GLPIKey::getExpectedKeyPath() must be of the type string, null given, called in /var/www/html/glpi/src/Update.php on line 307 in /var/www/html/glpi/src/GLPIKey.php at line 94

**Comment by cedric-anne** [comment]
Hi 

Can you provide the full trace located in `files/_logs/php-errors.log` of your GLPI dir?

**Comment by cedric-anne** [comment]
Also, can you explain exactly how you tried to update your GLPI, i.e. which files and database operations you did, and how each step of the upgrade process in UI was done.

**Comment by leruetkins** [comment]
I just deleted all files in dir glpi, then download v.10-rc1, and unpacked  all files to dir glpi, then open browser and chose  update.
Sorry, I can't provide other logs, because it did on VM and I have create resite previous state after this occasion.

After it  restore point I tried to use another way to update: I unpacked files to dir glpi with replacing all files . Further GLPI said that I should update database and system update successful, but some function are broken:
1. Can't open  /glpi/front/knowbaseitem.php - just white page
2. Helpdesk panel opens /glpi/front/dashboard_assets.php  page instead glpi/front/dashboard_helpdesk.php page
3.

**Comment by cedric-anne** [comment]
I tried to reproduced, but without success.

Without any logs, we cannot really investigate.

**Comment by leruetkins** [comment]
Tell me plese, which best way to choose to update glpi 10-beta to 10-rc and further version:
1. Using clean installation with update options?
2. Using file replacement in glpi directory?

**Comment by cedric-anne** [comment]
See https://glpi-install.readthedocs.io/en/latest/update.html

**Comment by cedric-anne** [comment]
You should empty the directory the restore `config` and `files` directory.

**Comment by leruetkins** [comment]
I have installed as yoy said and no errors shown, but 2 problems are actual:

1.    Can't open /glpi/front/knowbaseitem.php - just white page
2.  Helpdesk panel opens /glpi/front/dashboard_assets.php page instead glpi/front/dashboard_helpdesk.php page

**Comment by cedric-anne** [comment]
> 1. Can't open /glpi/front/knowbaseitem.php - just white page

Have you anything added in your GLPI logs when opening this page ?

**Comment by leruetkins** [comment]
I think it's this record:
[2022-02-04 08:54:57] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Knowbase::displayTabContentForItem() must be an instance of CommonGLPI, int given, called in /var/www/html/glpi/front/knowbaseitem.php on line 67 in /var/www/html/glpi/src/Knowbase.php at line 76
  Backtrace :
  front/knowbaseitem.php:67                          Knowbase::displayTabContentForItem()

**Comment by cedric-anne** [comment]
> I think it's this record: php-errors.log [2022-02-04 08:54:57] glpiphplog.CRITICAL: *** Uncaught Exception TypeError: Argument 1 passed to Knowbase::displayTabContentForItem() must be an instance of CommonGLPI, int given, called in /var/www/html/glpi/front/knowbaseitem.php on line 67 in /var/www/html/glpi/src/Knowbase.php at line 76 Backtrace : front/knowbaseitem.php:67 Knowbase::displayTabContentForItem()

OK, so this one is logged in #10533 .

**Comment by leruetkins** [comment]
Thanks!

**Comment by alex-arnautov** [comment]
same! didnt work for me.

open /front/knowbaseitem.php?&reset=reset and get a blank, but with debbug get this:

Uncaught Exception TypeError: Argument 1 passed to Knowbase::displayTabContentForItem() must be an instance of CommonGLPI, int given, called in /var/www/xxxxxxxxxxx/www/front/knowbaseitem.php on line 67 in /var/www/xxxxxxxxxxx/www/src/Knowbase.php at line 76

**Comment by cedric-anne** [comment]
Initial issue seems not reproductible, so I close this issue.

Other issues have to be tracked in #10538 and #10533.
