### ISSUE TITLE
[GLPI 10.0.0-rc1] tickets are not displayed in the root

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#10536]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Hello,

Since I have renamed the folder "root" Racine to "." 
I started to have the following issue => tickets are not displayed in the root

I have a somes tickets and once I open the menu "assistance" and "tickets" and i'm in the root this is what happen

![mstsc_zTg2ULsk1u](https://user-images.githubusercontent.com/63521311/152507569-1e279d36-b6bd-49d0-ae49-de33f4ef5b01.png)

![mstsc_EgbX3QpSVJ](https://user-images.githubusercontent.com/63521311/152507947-be337fee-5ff8-45a9-a9ea-5e66c5402dee.png)

I tried to rename the root entity "." to "Racine" but it change nothing.

### Relevant log output

```shell
[2022-02-04 10:18:20] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Entity::badgeCompletename(): Argument #1 ($entity_string) must be of type string, null given, called in C:\inetpub\wwwroot\glpi\src\Search.php on line 6388 in C:\inetpub\wwwroot\glpi\src\Entity.php at line 3882
  Backtrace :
  src\Search.php:6388                                Entity::badgeCompletename()
  src\Search.php:1645                                Search::giveItem()
  src\Search.php:371                                 Search::constructData()
  src\Search.php:123                                 Search::getDatas()
  src\Search.php:100                                 Search::showList()
  front\ticket.php:46                                Search::show()
```

### Your GLPI setup information

Operating system: Windows NT SRV-GLPI 10.0 build 14393 (Windows Server 2016) i586
PHP 8.0.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, soap, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 Edg/97.0.1072.76
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.27
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP

__________________________

Plugins list
--                
Name: Alertes                        Version: 1.10.0-rc1 State: Enabled 	
Name: Form Creator                   Version: 2.13.0-alpha.2 State: Enabled                
Name: Gestion des tags               Version: 2.9.0-rc1  State: Enabled

**Comment by cconard96** [comment]
How was the root entity renamed?
Was it done in a previous version?

When I tested, I wasn't able to change the name on the Root Entity at all because of a different issue.

**Comment by stdglpi** [comment]
Hello @cconard96 

How was the root entity renamed?  / _It was renamed ==> ._     

_for example :   

Root entity ;          .
                              Entity A
                              Entity B
                                        Entity B1_

Was it done in a previous version? / _It was done in GLPI 10.0.0 beta_

**Comment by cconard96** [comment]
> Hello @cconard96 
> 
> How was the root entity renamed?  / _It was renamed ==> ._     
> 
> _for example :   
> 
>   .
>                               Entity A
>                               Entity B
>                                         Entity B1
> 
> Was it done in a previous version? / _It was done in GLPI 10.0.0 beta_

I meant if it was done in the form, API, directly in database, etc. I was wondering because the form was broken at some point.

**Comment by stdglpi** [comment]
it was done directly in the web page in the entity menu.

![image](https://user-images.githubusercontent.com/63521311/152573495-8f371bd0-81e4-4227-8564-c6c63854f6a3.png)
![image](https://user-images.githubusercontent.com/63521311/152573587-319d8959-31ad-43fd-a2f9-c9934331d42a.png)
![image](https://user-images.githubusercontent.com/63521311/152573622-798abdec-2186-470a-b1b5-9bdbf06f0431.png)

And I came back to the name "Racine".

**Comment by stdglpi** [comment]
![image](https://user-images.githubusercontent.com/63521311/153727201-0298bae0-f7f2-420a-8c09-da3c378307b2.png)

**Comment by stdglpi** [comment]
@cconard96 Hello,

I checked about the table "glpi_entities" and the column "Entities_ID" = NULL
I checked on an another GLPI instance and the value is " -1 "

![image](https://user-images.githubusercontent.com/63521311/154977775-8904643d-ac37-4391-a754-4d5023c219be.png)

**Comment by cconard96** [comment]
This field cannot be negative anymore. A change was made for 9.5.7 to convert unsigned integer columns to signed columns to allow a greater ID range. Following this change, it looks like null is used instead here. On my instance, my root entity has "entities_id" set to null and works as expected.

**Comment by cconard96** [comment]
Can you check your database for tickets with an invalid entity and for tickets with an entity with a missing complete name?

Tickets with an entity that no longer exists:
```SQL
SELECT glpi_tickets.id AS 'TicketID' FROM glpi_tickets WHERE entities_id NOT IN (SELECT id FROM glpi_entities);
```

Tickets with an entity with a missing/null complete name:
```SQL
SELECT glpi_tickets.id AS 'TicketID', glpi_entities.id AS 'EntityID' FROM glpi_tickets LEFT JOIN glpi_entities ON glpi_entities.id = glpi_tickets.entities_id WHERE glpi_entities.completename = NULL;
```

**Comment by cedric-anne** [comment]
@cconard96 on which PHP version did you checked?

**Comment by cconard96** [comment]
PHP 8.0.14

**Comment by stdglpi** [comment]
@cconard96 

first request :
SELECT glpi_tickets.id AS 'TicketID' FROM glpi_tickets WHERE entities_id NOT IN (SELECT id FROM glpi_entities);

![image](https://user-images.githubusercontent.com/63521311/155035059-4f706248-c948-415c-84e2-29e3792b027e.png)

second request : 
SELECT glpi_tickets.id AS 'TicketID', glpi_entities.id AS 'EntityID' FROM glpi_tickets LEFT JOIN glpi_entities ON glpi_entities.id = glpi_tickets.entities_id WHERE glpi_entities.completename = NULL;

![image](https://user-images.githubusercontent.com/63521311/155035082-2f5ea07b-f274-418e-ad5a-8746baeecc62.png)

**Comment by cconard96** [comment]
It looks like somehow an entity was deleted without the tickets being transferred to another entity like the Root Entity.

I don't think it would be a good solution to just manually change the entities_id value for each of them as there may be some issues remaining with linked items or other itemtypes.

Do you recall deleting an entity at some point? Do you know how the circumstances of the issue could be recreated?
I'll try to recreate the issue tomorrow when I have some more time to spend on it.

**Comment by stdglpi** [comment]
@cconard96 @cedric-anne Hello,

From the root, with the debug mod I had also this issue : _Warning on ticket view, Undefined array key "id"_
Issue ==> https://github.com/glpi-project/glpi/issues/10535

I saw this fix : 
Fix ==> https://github.com/glpi-project/glpi/pull/10596

After that, my root is now accessible with all the tickets .. 👍 
I also moved the tickets with no entity.

**Comment by stdglpi** [comment]
Hello @cconard96 

Firstable, I deleted the 8 tickets with no entity (ok for that)
And yes you are true.
I met a problem with entity and child entity on GLPI 10 BETA.
I decided to move tickets and delete the entity which was a problem.

Now, after the clean, I still have this error this error in tickets menu.
![image](https://user-images.githubusercontent.com/63521311/155178066-74a3f131-0dec-4ea8-b565-accf08dc0279.png)

I also found the solution on other issue for the tickets that did not want to appear
I followed this solution : https://github.com/glpi-project/glpi/pull/10596

Now I can see the tickets in the root entity :)

![image](https://user-images.githubusercontent.com/63521311/155178926-3cb6c1c5-73a1-4cf0-a643-906adc0118ac.png)

**Comment by cconard96** [comment]
The remaining error about "Truncated incorrect DOUBLE value" may be fixed by #10770.

**Comment by stdglpi** [comment]
@cconard96 At the beginning I had two errors on the Root entity

However the [#10770](https://github.com/glpi-project/glpi/pull/10770) fixed the tickets view in the root entity.

For the "Truncated incorrect DOUBLE value" I think it's a second error in the database.

PS : I migrate to the GLPI RC2 and I have again some errors on it
![image](https://user-images.githubusercontent.com/63521311/156563895-64ee9d1b-37f5-47df-9db3-911543611fc7.png)

**Comment by cconard96** [comment]
Can you get the full error from the `files/_log/sql-errors.log` file? The errors in that file should have the stack trace which would tell us where the error is being generated in the code.

**Comment by stdglpi** [comment]
hello @cconard96 

[2022-01-16 20:54:38] glpisqllog.WARNING: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 407
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '__NULL__$#$'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '__NULL__$#$'
  Backtrace :
  src\DBmysqlIterator.php:108                        
  src\DBmysql.php:1059                               DBmysqlIterator->execute()
  src\Dropdown.php:454                               DBmysql->request()
  src\Search.php:6368                                Dropdown::getDropdownName()
  src\Search.php:1632                                Search::giveItem()
  src\Search.php:362                                 Search::constructData()
  src\Search.php:114                                 Search::getDatas()
  src\Search.php:97                                  Search::showList()
  front\ticket.php:46                                Search::show()
  {"user":"22@SRV-GLPI","mem_usage":"0.019\", 8.22Mio)"} 
[2022-01-16 20:54:38] glpisqllog.WARNING: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 407
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '__NULL__$#$'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '__NULL__$#$'
  Backtrace :
  src\DBmysqlIterator.php:108                        
  src\DBmysql.php:1059                               DBmysqlIterator->execute()
  src\Dropdown.php:454                               DBmysql->request()
  src\Search.php:6368                                Dropdown::getDropdownName()
  src\Search.php:1632                                Search::giveItem()
  src\Search.php:362                                 Search::constructData()
  src\Search.php:114                                 Search::getDatas()
  src\Search.php:97                                  Search::showList()
  front\ticket.php:46                                Search::show()
  {"user":"22@SRV-GLPI","mem_usage":"0.004\", 8.24Mio)"} 
[2022-01-16 20:54:38] glpisqllog.WARNING: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 407
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '__NULL__$#$'
  Warnings: 
1292: Truncated incorrect DOUBLE value: '__NULL__$#$'
  Backtrace :
  src\DBmysqlIterator.php:108                        
  src\DBmysql.php:1059                               DBmysqlIterator->execute()
  src\Dropdown.php:454                               DBmysql->request()
  src\Search.php:6368                                Dropdown::getDropdownName()
  src\Search.php:1632                                Search::giveItem()
  src\Search.php:362                                 Search::constructData()
  src\Search.php:114                                 Search::getDatas()
  src\Search.php:97                                  Search::showList()
  front\ticket.php:46                                Search::show()
  {"user":"22@SRV-GLPI","mem_usage":"0.004\", 8.26Mio)"} 
[2022-01-16 20:54:38] glpisqllog.WARNING: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 407
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = '__NULL__$#$'

**Comment by cconard96** [comment]
Can you test #10875?

**Comment by stdglpi** [comment]
@cconard96 no SQL error after that but PHP says :  

[2022-03-06 22:07:11] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in C:\inetpub\wwwroot\glpi\src\Dropdown.php at line 444
  Backtrace :
  src\Search.php:6401                                Dropdown::getDropdownName()
  src\Search.php:1611                                Search::giveItem()
  src\Search.php:371                                 Search::constructData()
  src\Search.php:123                                 Search::getDatas()
  src\Search.php:100                                 Search::showList()
  front\ticket.php:56                                Search::show()
  
[2022-03-06 22:07:11] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $post in C:\inetpub\wwwroot\glpi\src\Dropdown.php at line 444
  Backtrace :
  src\Search.php:6401                                Dropdown::getDropdownName()
  src\Search.php:1611                                Search::giveItem()
  src\Search.php:371                                 Search::constructData()
  src\Search.php:123                                 Search::getDatas()
  src\Search.php:100                                 Search::showList()
  front\ticket.php:56                                Search::show()

![image](https://user-images.githubusercontent.com/63521311/156942333-4b2c7a65-6533-4a15-b919-9748b77f8ce9.png)

**Comment by cconard96** [comment]
Some changes were missing. I updated the PR.
