### ISSUE TITLE
[GLPI 10.0.0-rc1] Kanban multiple PHP warnings and uncaught exceptions

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#10545]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Warnings are fired when going into Kanban with tasks in there.

### Relevant log output

```shell
[2022-02-04 11:31:51] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in E:\GLPI\src\Item_Kanban.php at line 64
  Backtrace :
  ajax\kanban.php:210                                Item_Kanban::saveStateForItem()
  
[2022-02-04 11:35:16] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "cards" in E:\GLPI\src\Item_Kanban.php at line 154
  Backtrace :
  ajax\kanban.php:153                                Item_Kanban::moveCard()
  
[2022-02-04 11:35:16] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in E:\GLPI\src\Item_Kanban.php at line 154
  Backtrace :
  ajax\kanban.php:153                                Item_Kanban::moveCard()
  
[2022-02-04 11:35:16] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: array_splice(): Argument #1 ($array) must be of type array, null given in E:\GLPI\src\Item_Kanban.php at line 167
  Backtrace :
  src\Item_Kanban.php:167                            array_splice()
  ajax\kanban.php:153                                Item_Kanban::moveCard()
```

### Page URL

front/project.form.php?id=2

### Steps To reproduce

1. Login
2. Go to Project
3. Create a project
4. Go to Kanban view
5. Add two tasks
6. Try to move the 2nd before the first
7. Voilà

### Your GLPI setup information

Operating system: Windows NT SRVGLPI10 10.0 build 17763 (Windows Server 2016) AMD64
PHP 8.1.1 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="2048M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2048M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.5-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.1) is supported.PHP version (8.1.1) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.6.5) is supported.Database engine version (10.6.5) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to E:\GLPI/files/_cache has been validated. Write access to E:\GLPI/config has been validated. Write access to E:\GLPI/files/_cron has been validated. Write access to E:\GLPI/files has been validated. Write access to E:\GLPI/files/_dumps has been validated. Write access to E:\GLPI/files/_graphs has been validated. Write access to E:\GLPI/files/_lock has been validated. Write access to E:\GLPI/files/_pictures has been validated. Write access to E:\GLPI/files/_plugins has been validated. Write access to E:\GLPI/files/_rss has been validated. Write access to E:\GLPI/files/_sessions has been validated. Write access to E:\GLPI/files/_tmp has been validated. Write access to E:\GLPI/files/_uploads has been validated.Write access to E:\GLPI/files/_cache has been validated.
Write access to E:\GLPI/config has been validated.
Write access to E:\GLPI/files/_cron has been validated.
Write access to E:\GLPI/files has been validated.
Write access to E:\GLPI/files/_dumps has been validated.
Write access to E:\GLPI/files/_graphs has been validated.
Write access to E:\GLPI/files/_lock has been validated.
Write access to E:\GLPI/files/_pictures has been validated.
Write access to E:\GLPI/files/_plugins has been validated.
Write access to E:\GLPI/files/_rss has been validated.
Write access to E:\GLPI/files/_sessions has been validated.
Write access to E:\GLPI/files/_tmp has been validated.
Write access to E:\GLPI/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to E:\GLPI/marketplace has been validated.Write access to E:\GLPI/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cconard96** [comment]
I followed the steps to recreate but didn't see this issue. I make two tasks in the default "No status" column and changed the order of them. I also added another column "New" and moved the cards to it and changed their order. I also tested this with and without the automatic refresh enabled.

Can you check the browser console to see if there are any issues client-side (F12 key and then console tab)?

**Comment by SteadEXE** [comment]
I was able to reproduce it in this scenario :

1. Navigate to "Project"
2. Hit the "Add" button
2. Validate the form with "Add" button
3. Navigate to "Project"
4. Click on the freshly created project
5. Click on "Kanban"
6. On the default column click "+" then "project task", click "add" two time (to create two tasks)
7. Move the second before the first one.

I tried even with refreshing the page, when I swap them, errors occur

I have no javascript/xhr error in my browser dev tool.
I tried with Brave and Edge (chromium).

**Comment by SteadEXE** [comment]
The swap itself works by the way. But there are errors in the log file

**Comment by cconard96** [comment]
> The swap itself works by the way. But there are errors in the log file

Ah, I missed that since they were only warnings. I did recreate the issue then.

**Comment by SteadEXE** [comment]
The following error it occurs time to time, but I can't find how to reproduce it.

`[2022-02-04 11:31:51] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in E:\GLPI\src\Item_Kanban.php at line 64
  Backtrace :
  ajax\kanban.php:210                                Item_Kanban::saveStateForItem()`

**Comment by SteadEXE** [comment]
Thank you Curtis, it seems to work fine with this patch! :)
