### ISSUE TITLE
ability to mention users in ITIL objects doesnt seems to work

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10544]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI RC1

### Bug description

Hi,

i dont know if its a bug or not , i have tried both on beta version as well as RC1 but the user mention doesnt load anything

when i type @ no users are loaded.

i have LDAP configured so do i need any settings?

![image](https://user-images.githubusercontent.com/22425503/152522648-7df49e3b-3094-43d8-9fff-ba5f0157b013.png)

**Comment by cconard96** [comment]
Notifications need to be enabled otherwise the mentions don't show.
Setup > Notifications > Enable Followup

**Comment by roshanroche** [comment]
Thank u @cconard96 i forgot about the notifications... :)
