### ISSUE TITLE
Missing german translations

### ISSUE THREAD

**Issue by eckad158** [glpi-project/glpi#10541]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Some strings are not yet translated:

![Fehlende Übersetzung(en)](https://user-images.githubusercontent.com/23153117/152515471-4d6dcf80-404c-4eb9-b2f5-24f573a640c4.png)
 

### Page URL

https://<helpdesk>/front/ticket.php

### Steps To reproduce

Select german Language in GLPI
click on shown elements
enter "time" as topic
some english strings will show up (see Screenshot)

**Comment by cconard96** [comment]
These translations haven't been contributed yet on the translation platform.

If you wish to contribute translations, you can from Transifex by requesting access to translate for German.
Direct link: https://www.transifex.com/glpi/GLPI/language/de_DE/
To request access, click the 3 dots menu next to "View Members" and select "Join team".
