### ISSUE TITLE
You do not have access to this application because your account has been disabled or removed.

### ISSUE THREAD

**Issue by zeriqueh** [glpi-project/glpi#10542]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.3.3

### Bug description

Hello everyone, I didn't find a specific topic about this even in the official forum. I exported the database from a Production GLPi in version 9.3.3 to a clean version of it after installing and cleaning the database also in version 9.3.3.

When trying to log in after importing the database and all the files from the production base, with any user it gives the following message: "You do not have access to this application because your account has been disabled or removed"

I already tried to create a direct user in the database, but even with this new user the message appears.

I checked the users table and the users I try to log in are active, they are not disabled or excluded I made sure to check all this.

The log shows some errors (lower):

I would like some help with this problem, because nothing I did could solve, thank you.

### Relevant log output

```shell
sql-erros.log
[2022-02-04 08:05:04] glpisqllog.ERROR: DBmysql::query() in /home/suporte/www/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT `entities_id`, `is_recursive` FROM `glpi_profiles_users` WHERE `users_id` = '1285'
  Error: Unknown column 'is_recursive' in 'field list'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/profile_user.class.php:599                     DBmysql->request()
  inc/user.class.php:827                             Profile_User::getUserEntities()
  inc/commondbtm.class.php:1349                      User->prepareInputForUpdate()
  inc/auth.class.php:798                             CommonDBTM->update()
  front/login.php:84                                 Auth->login()
  {"user":"@web228.uni5.net"} 

php-erros.log
[2022-02-04 08:05:04] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/suporte/www/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: glpilanguage
  Backtrace :
  inc/html.class.php:1168                            
  inc/html.class.php:1837                            Html::includeHeader()
  front/login.php:88                                 Html::nullHeader()
  {"user":"@web228.uni5.net","mem_usage":"0.034\", 8.74Mio)"} 
[2022-02-04 08:05:04] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/suporte/www/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: 
  Backtrace :
  inc/html.class.php:1168                            
  inc/html.class.php:1837                            Html::includeHeader()
  front/login.php:88                                 Html::nullHeader()
  {"user":"@web228.uni5.net","mem_usage":"0.000\", 8.74Mio)"} 

event.log
2022-02-04 08:05:04 [@web228.uni5.net]
[login] 3: admin.teste fez login no IP 189.37.xx.1xx

cron.log
2022-02-04 08:05:02 [@web228.uni5.net]
Interno #1: Executar createinquest
```

### Page URL

login

**Comment by cedric-anne** [comment]
Hi,

Version 9.3.x is not anymore maintained. Please upgrade to latest version.

Regards
