### ISSUE TITLE
Hierarchical view for software license type

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#1054]
see http://glpi.userecho.com/topics/380-software-license-type-as-tree-hierarchy/

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
