### ISSUE TITLE
[GLPI 10.0.0-rc1] php bin/console glpi:migration:unsigned_keys 

### ISSUE THREAD

**Issue by mirda123** [glpi-project/glpi#10556]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v10.0.0-rc1

### Bug description

Hello,

I have migrated GLPI v10 to v10.0.0-rc1 too

Found 1642 primary foreign key colums using signed integers

Migration of colum "glpi_domains.entities_id" cannot be done as it contains negative values

i found 10 with -1 value in the table and 15 with 0 value. Can i change the value with 0 everywhere ?

**Comment by cedric-anne** [comment]
Negatives values on this field are not legitimate. I guess the have been produced by some plugin, or has been produced by migration from Domains plugin.

**Comment by cedric-anne** [comment]
For illegitimate negative values in GLPI core, they will be handled by #10763 . For thoose related to plugins, fix has to be produced on plugin side.
