### ISSUE TITLE
There is no page for cameras glpi/front/item_devicecamera.form.php

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#10552]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-rc1

### Bug description

There is no page for cameras glpi/front/item_devicecamera.form.php

![Screenshot_231](https://user-images.githubusercontent.com/15270519/152584159-60c973a8-49f0-4563-9acf-aca8a85bf4cf.png)
![Screenshot_232](https://user-images.githubusercontent.com/15270519/152584174-df92846e-2391-4e96-8ea1-6d51b657b917.png)

### Page URL

glpi/front/item_devicecamera.form.php

**Comment by feroguz** [comment]
The problem still appears in the new version. I have tried to manually replace the code but the same situation is still displayed glpi 10.14
![image](https://github.com/glpi-project/glpi/assets/112366163/79055054-77be-4b8e-a9e4-9030f5b66f59)
![image](https://github.com/glpi-project/glpi/assets/112366163/c86e8e28-68aa-4c10-96e8-ff0c159a4f68)

**Comment by trasher** [comment]
Open new issue with **all required information**.
