### ISSUE TITLE
[GLPI 10.0.0-rc1] Wrong navigation number while passing via Global list

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi#10563]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Having only one computer asset, if I reach it by **Assets**->**Computers** I see a normal `1/1` text on the top right.
If I reach it via **Assets**->**Global**, I see a `1/2` with a "Next" Arrow just close. Clicking on the arrow just get me back to the asset.
In the second case, I expect the same `1/1` normal text.

### Relevant log output

```shell
When I click on **Assets**->**Global** I see this warnings in php-errors.log:

[2022-02-07 11:06:14] glpiphplog.WARNING:   *** PHP Warning (2): class_uses(): object or string expected in /srv/glpi/src/Toolbox.php at line 3320
  Backtrace :
  src/Toolbox.php:3320                               class_uses()
  src/Search.php:1750                                Toolbox::hasTrait()
  src/Search.php:136                                 Search::displayData()
  src/Search.php:100                                 Search::showList()
  front/allassets.php:46                             Search::show()
  
[2022-02-07 11:06:14] glpiphplog.WARNING:   *** PHP Warning (2): in_array() expects parameter 2 to be array, bool given in /srv/glpi/src/Toolbox.php at line 3321
  Backtrace :
  src/Toolbox.php:3321                               in_array()
  src/Search.php:1750                                Toolbox::hasTrait()
  src/Search.php:136                                 Search::displayData()
  src/Search.php:100                                 Search::showList()
  front/allassets.php:46                             Search::show()
```
I don't have any error when clicking on **Assets**->**Computers**, when accessing the asset or when clicking on the "Next" arrow.

### Steps To reproduce

See bug description

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0-rc1 ( => /srv/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi-10-rc1 5.15.12-100.fc34.x86_64 #1 SMP Wed Dec 29 15:21:44 UTC 2021 x86_64
PHP 7.4.25 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="1280M" post_max_size="1068M" safe_mode="" session.save_handler="files"
	upload_max_filesize="1024M" 
Software: Apache/2.4.52 (Debian) (Apache/2.4.52 (Debian) Server at 192.168.1.43 Port 80
)
	Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0
Server Software: Debian 11
	Server Version: 10.5.12-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.25) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.5.12) is supported.
The log file has been created successfully.
Write access to /srv/glpi/files/_cache has been validated.
Write access to /srv/glpi/config has been validated.
Write access to /srv/glpi/files/_cron has been validated.
Write access to /srv/glpi/files has been validated.
Write access to /srv/glpi/files/_dumps has been validated.
Write access to /srv/glpi/files/_graphs has been validated.
Write access to /srv/glpi/files/_lock has been validated.
Write access to /srv/glpi/files/_pictures has been validated.
Write access to /srv/glpi/files/_plugins has been validated.
Write access to /srv/glpi/files/_rss has been validated.
Write access to /srv/glpi/files/_sessions has been validated.
Write access to /srv/glpi/files/_tmp has been validated.
Write access to /srv/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /srv/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /srv/glpi
GLPI_CONFIG_DIR: /srv/glpi/config
GLPI_VAR_DIR: /srv/glpi/files
GLPI_MARKETPLACE_DIR: /srv/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /srv/glpi/files
GLPI_CACHE_DIR: /srv/glpi/files/_cache
GLPI_CRON_DIR: /srv/glpi/files/_cron
GLPI_DUMP_DIR: /srv/glpi/files/_dumps
GLPI_GRAPH_DIR: /srv/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /srv/glpi/files/_locales
GLPI_LOCK_DIR: /srv/glpi/files/_lock
GLPI_LOG_DIR: /srv/glpi/files/_log
GLPI_PICTURE_DIR: /srv/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /srv/glpi/files/_plugins
GLPI_RSS_DIR: /srv/glpi/files/_rss
GLPI_SESSION_DIR: /srv/glpi/files/_sessions
GLPI_TMP_DIR: /srv/glpi/files/_tmp
GLPI_UPLOAD_DIR: /srv/glpi/files/_uploads
GLPI_INVENTORY_DIR: /srv/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /srv/glpi/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/srv/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/srv/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/srv/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/srv/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/srv/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/srv/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/srv/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/srv/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/srv/glpi/vendor/sabre/http/lib)
sabre/uri in (/srv/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/srv/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/srv/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/srv/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/srv/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/srv/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/srv/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/srv/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/srv/glpi/vendor/symfony/console)
scssphp/scssphp in (/srv/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/srv/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/srv/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/srv/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/srv/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/srv/glpi/vendor/ramsey/uuid/src)
psr/log in (/srv/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/srv/glpi/vendor/psr/simple-cache/src)
psr/cache in (/srv/glpi/vendor/psr/cache/src)
league/csv in (/srv/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/srv/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/srv/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/srv/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/srv/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/srv/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/srv/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/srv/glpi/vendor/symfony/cache)
html2text/html2text in (/srv/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/srv/glpi/vendor/symfony/dom-crawler)
twig/twig in (/srv/glpi/vendor/twig/twig/src)
twig/string-extra in (/srv/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/srv/glpi/vendor/symfony/polyfill-php80)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc4  State: Enabled

</pre></details>

### Anything else?

In the 2 cases, the list output is as expected with only one asset:
![image](https://user-images.githubusercontent.com/12514489/152767955-1895322a-c9fb-442c-93ba-0f794c0c9b64.png)

**Comment by g-bougard** [comment]
Just an update, after adding another computer, the maximum index is now 4 in place of 2 so I can see:
![image](https://user-images.githubusercontent.com/12514489/153024273-01a17d41-2074-475c-95af-4c6aac8281ef.png)
Clicking on **Next** arrow switches to the first computer.
Clicking on **Last** arrow switches to the second computer. **Last** arrow only appears on first computer as it should be as the second is the last in that context.

**Comment by cedric-anne** [comment]
I noticed than when you go back to the list and click again on a item, the total counter is incrementing each time.
