### ISSUE TITLE
mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483,

### ISSUE THREAD

**Issue by legolass73** [glpi-project/glpi#10568]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

hello, I have a lot of error in the logs concerning the /var/www/html/inc/toolbox.class.php file. here is the error message:
[Mon Feb 07 14:12:35.900054 2022] [php:warn] [pid 15136] [client 172.20.1.5:39598] PHP Warning: mkdir(): Permission denied in online 1483, referer: https://glpi. localdomain.fr/front/config.form.php

in the page https://glpi.localdomain.fr/front/config.form.php
  it shows me: The directory could not be created in /var/www/html/config. when the folder has  555 permissions,

and shows me a warning message on the home page: For security reasons, please remove webserver (apache, nginx...) write permission on folder: /var/www/html/config when the folder has permissions 775 .

the user and group attributes to the folder is the group and user of apache (www-data)

### Relevant log output

```shell
[Fri Feb 04 10:24:09.920109 2022] [php:warn] [pid 10566] [client 172.20.1.5:58892] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php?forcetab=PluginPdfConfig%241
[Mon Feb 07 13:40:54.845657 2022] [php:warn] [pid 15138] [client 172.20.1.5:55042] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php
[Mon Feb 07 13:41:04.906321 2022] [php:warn] [pid 15136] [client 172.20.1.5:55078] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php
[Mon Feb 07 13:42:18.201636 2022] [php:warn] [pid 50961] [client 172.20.1.5:55274] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php
[Mon Feb 07 14:06:04.555717 2022] [php:warn] [pid 51000] [client 172.20.1.5:37346] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php
[Mon Feb 07 14:11:04.859699 2022] [php:warn] [pid 11284] [client 172.20.1.5:39384] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php
[Mon Feb 07 14:11:40.415021 2022] [php:warn] [pid 51000] [client 172.20.1.5:39448] PHP Warning:  mkdir(): Permission denied in /var/www/html/inc/toolbox.class.php on line 1483, referer: https://glpi.localdomain.fr/front/config.form.php
[Mon Feb 07 14:12:21.231510 2022] [php:warn] [pid 52052] [client 172.20.1.5:39516] PHP Warning:  Unable to load plugin "tasklists" information. in /var/www/html/inc/plugin.class.php on line 452, referer: https://glpi.localdomain.fr/front/plugin.php
```

### Your GLPI setup information

Operating system: Linux glpi_exp 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64
PHP 8.0.10 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="250M" safe_mode="" session.save_handler="files"
	upload_max_filesize="250M" 
Software: Apache/2.4.52 (Debian) (Apache/2.4.52 (Debian) Server at glpi.localdomain.fr Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.175 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.1-MariaDB-1:10.7.1+maria~bullseye
	Server SQL Mode: 
	Parameters: glpi_exp_user@mariadb/glpi_exp
	Host info: mariadb via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.7.1) - Perfect!Database version seems correct (10.7.1) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/files/_cache has been validated.Write access to /var/www/html/files/_cache has been validated.
Write access to /var/www/html/config has been validated.Write access to /var/www/html/config has been validated.
Write access to /var/www/html/files/_cron has been validated.Write access to /var/www/html/files/_cron has been validated.
Write access to /var/www/html/files has been validated.Write access to /var/www/html/files has been validated.
Write access to /var/www/html/files/_dumps has been validated.Write access to /var/www/html/files/_dumps has been validated.
Write access to /var/www/html/files/_graphs has been validated.Write access to /var/www/html/files/_graphs has been validated.
Write access to /var/www/html/files/_lock has been validated.Write access to /var/www/html/files/_lock has been validated.
Write access to /var/www/html/files/_pictures has been validated.Write access to /var/www/html/files/_pictures has been validated.
Write access to /var/www/html/files/_plugins has been validated.Write access to /var/www/html/files/_plugins has been validated.
Write access to /var/www/html/files/_rss has been validated.Write access to /var/www/html/files/_rss has been validated.
Write access to /var/www/html/files/_sessions has been validated.Write access to /var/www/html/files/_sessions has been validated.
Write access to /var/www/html/files/_tmp has been validated.Write access to /var/www/html/files/_tmp has been validated.
Write access to /var/www/html/files/_uploads has been validated.Write access to /var/www/html/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI constants
 
GLPI_ROOT: /var/www/html
GLPI_CONFIG_DIR: /var/www/html/config
GLPI_VAR_DIR: /var/www/html/files
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/html/files
GLPI_CACHE_DIR: /var/www/html/files/_cache
GLPI_CRON_DIR: /var/www/html/files/_cron
GLPI_DUMP_DIR: /var/www/html/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales
GLPI_LOCK_DIR: /var/www/html/files/_lock
GLPI_LOG_DIR: /var/www/html/files/_log
GLPI_PICTURE_DIR: /var/www/html/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins
GLPI_RSS_DIR: /var/www/html/files/_rss
GLPI_SESSION_DIR: /var/www/html/files/_sessions
GLPI_TMP_DIR: /var/www/html/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/files/_uploads
GLPI_I18N_DIR: /var/www/html/locales
GLPI_VERSION: 9.5.7
GLPI_SCHEMA_VERSION: 9.5.8
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022

**Comment by cedric-anne** [comment]
> The directory could not be created in /var/www/html/config

Which action are you trying to do ? Writing operations on configuration directory are really rare.


> For security reasons, please remove webserver (apache, nginx...) write permission on folder: /var/www/html/config

I find no occurence of this message in GLPI source code. This message may be produce by one of your GLPI plugins. Can you try to disable plugins one by one to see which plugin produce this message ?

**Comment by legolass73** [comment]
> I find no occurence of this message in GLPI source code. This message may be produce by one of your GLPI plugins. Can you try to disable plugins one by one to see which plugin produce this message ?
hello, i have no plugin installed on my glpi instance....

> > The directory could not be created in /var/www/html/config
> 
> Which action are you trying to do ? Writing operations on configuration directory are really rare.

But I haven't tried to do anything... it is glpi himself who tells me that...

**Comment by cedric-anne** [comment]
Hi,

It seems that you installed an unofficial distribution of GLPI. Please open your issue on corresponding repository (i.e. https://github.com/DCS-Easyware/gsit ).

Regards
