### ISSUE TITLE
v10.0.0-rc1 unsigned ints migration: devicenetworkcards_id

### ISSUE THREAD

**Issue by jackburton79** [glpi-project/glpi#10566]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v10.0.0-rc1

### Bug description

Hello,

I have migrated GLPI v10.0.0-rc1. Note that this installation was done initially with a very old version of GLPI, and always kept current.

I've started the migration to unsigned ints, and found these errors:

group:/usr/local/share/glpitest # php bin/console glpi:migration:unsigned_keys
Found 1 primary/foreign key columns(s) using signed integers.
Vuoi continuare? [Yes/no]yes
Migration of column "glpi_networkportethernets.items_devicenetworkcards_id" cannot be done as it contains negative values.

I've found lots of -1 in glpi_networkportethernets.items_devicenetworkcards_id.

### Relevant log output

```shell
Found 1 primary/foreign key columns(s) using signed integers.
Vuoi continuare? [Yes/no]yes
Migration of column "glpi_networkportethernets.items_devicenetworkcards_id" cannot be done as it contains negative values.
```

### Steps To reproduce

php bin/console glpi:migration:unsigned_keys

### Your GLPI setup information

<details><summary>Informazioni sul sistema, l'installazione e la configurazione</summary><pre>GLPI 10.0.0-rc1 ( => /usr/local/share/glpitest)
Installation mode: TARBALL
Current language:it_IT

</details><details><summary>Server</summary><pre> 
Operating system: Linux group 5.3.18-lp152.106-default #1 SMP Mon Nov 22 08:38:17 UTC 2021 (52078fe) x86_64
PHP 7.4.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, ctype,
	curl, date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, memcached, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="101M" safe_mode="" session.save_handler="files"
	upload_max_filesize="8M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43
Server Software: MariaDB package
	Server Version: 10.4.17-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES
	Parameters: glpi-test@localhost/glpi-test
	Host info: Localhost via UNIX socket
	
PHP version (7.4.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.4.17) is supported.
The log file has been created successfully.
Write access to /usr/local/share/glpitest/files/_cache has been validated.
Write access to /usr/local/share/glpitest/config has been validated.
Write access to /usr/local/share/glpitest/files/_cron has been validated.
Write access to /usr/local/share/glpitest/files has been validated.
Write access to /usr/local/share/glpitest/files/_dumps has been validated.
Write access to /usr/local/share/glpitest/files/_graphs has been validated.
Write access to /usr/local/share/glpitest/files/_lock has been validated.
Write access to /usr/local/share/glpitest/files/_pictures has been validated.
Write access to /usr/local/share/glpitest/files/_plugins has been validated.
Write access to /usr/local/share/glpitest/files/_rss has been validated.
Write access to /usr/local/share/glpitest/files/_sessions has been validated.
Write access to /usr/local/share/glpitest/files/_tmp has been validated.
Write access to /usr/local/share/glpitest/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/local/share/glpitest/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/local/share/glpitest
GLPI_CONFIG_DIR: /usr/local/share/glpitest/config
GLPI_VAR_DIR: /usr/local/share/glpitest/files
GLPI_MARKETPLACE_DIR: /usr/local/share/glpitest/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /usr/local/share/glpitest/files
GLPI_CACHE_DIR: /usr/local/share/glpitest/files/_cache
GLPI_CRON_DIR: /usr/local/share/glpitest/files/_cron
GLPI_DUMP_DIR: /usr/local/share/glpitest/files/_dumps
GLPI_GRAPH_DIR: /usr/local/share/glpitest/files/_graphs
GLPI_LOCAL_I18N_DIR: /usr/local/share/glpitest/files/_locales
GLPI_LOCK_DIR: /usr/local/share/glpitest/files/_lock
GLPI_LOG_DIR: /usr/local/share/glpitest/files/_log
GLPI_PICTURE_DIR: /usr/local/share/glpitest/files/_pictures
GLPI_PLUGIN_DOC_DIR: /usr/local/share/glpitest/files/_plugins
GLPI_RSS_DIR: /usr/local/share/glpitest/files/_rss
GLPI_SESSION_DIR: /usr/local/share/glpitest/files/_sessions
GLPI_TMP_DIR: /usr/local/share/glpitest/files/_tmp
GLPI_UPLOAD_DIR: /usr/local/share/glpitest/files/_uploads
GLPI_INVENTORY_DIR: /usr/local/share/glpitest/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/local/share/glpitest/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/local/share/glpitest/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/usr/local/share/glpitest/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/local/share/glpitest/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/local/share/glpitest/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/local/share/glpitest/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/local/share/glpitest/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/local/share/glpitest/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/local/share/glpitest/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/local/share/glpitest/vendor/sabre/http/lib)
sabre/uri in (/usr/local/share/glpitest/vendor/sabre/uri/lib)
sabre/vobject in (/usr/local/share/glpitest/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/local/share/glpitest/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/local/share/glpitest/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/local/share/glpitest/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/local/share/glpitest/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/local/share/glpitest/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/local/share/glpitest/vendor/elvanto/litemoji/src)
symfony/console in (/usr/local/share/glpitest/vendor/symfony/console)
scssphp/scssphp in (/usr/local/share/glpitest/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/local/share/glpitest/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/local/share/glpitest/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/local/share/glpitest/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/local/share/glpitest/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/local/share/glpitest/vendor/ramsey/uuid/src)
psr/log in (/usr/local/share/glpitest/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/local/share/glpitest/vendor/psr/simple-cache/src)
psr/cache in (/usr/local/share/glpitest/vendor/psr/cache/src)
league/csv in (/usr/local/share/glpitest/vendor/league/csv/src)
mexitek/phpcolors in (/usr/local/share/glpitest/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/local/share/glpitest/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/local/share/glpitest/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/local/share/glpitest/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/local/share/glpitest/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/local/share/glpitest/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/local/share/glpitest/vendor/symfony/cache)
html2text/html2text in (/usr/local/share/glpitest/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/local/share/glpitest/vendor/symfony/dom-crawler)
twig/twig in (/usr/local/share/glpitest/vendor/twig/twig/src)
twig/string-extra in (/usr/local/share/glpitest/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/local/share/glpitest/vendor/symfony/polyfill-php80)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://ldap', Port: '389', BaseDN: 'OU=AterUsers,DC=IACPUD,DC=LOCAL', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'LDAPSearchUser', Use
		TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp.iacpud.local)

</details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.0-rc2  State: Enabled
	additionalalerts     Name: Altre notifiche                Version: 2.4.0-rc1  State: Enabled
	barcode              Name: Barcode                        Version: 2.5.0      State: Installed / not activated
	printercounters      Name: Contatori della stampante      Version: 2.0.0-rc2  State: Enabled
	dashboard            Name: Dashboard                      Version: 0.9.6      State: Not installed
	datainjection        Name: Data injection                 Version: 2.10.0-rc2 State: Enabled
	databases            Name: Databases                      Version: 2.3.0      State: Installed / not activated
	addressing           Name: Indirizzamento IP              Version: 3.0.0-rc2  State: Installed / not activated
	room                 Name: Locali                         Version: 3.1.3      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.0      State: Installed / not activated
	mreporting           Name: More Reporting                 Version: 1.8.0-rc2  State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.0-rc1  State: Installed / not activated
	reports              Name: Report                         Version: 1.12.0     State: Installed / not activated
	reservation          Name: Reservation                    Version: 2.3.3      State: Installed / not activated
	shellcommands        Name: Shell Commands                 Version: 4.0.0-rc2  State: Installed / not activated
	pdf                  Name: Stampa in PDF                  Version: 1.7.0      State: Installed / not activated
	ticketcleaner        Name: Ticket Cleaner                 Version: 2.1.0      State: Installed / not activated
	treeview             Name: Visualizzazione struttura      Version: 1.10.0-rc1 State: Installed / not activated
	webapplications      Name: Web applications               Version: 4.0.0-rc1  State: Installed / not activated

</pre></details>

**Comment by cedric-anne** [comment]
Negatives values on this field are not legitimate. I guess the have been produced by some plugin. I found `$inst_input['items_devicenetworkcards_id'] = $item_device->getID();` in `ocsinventoryng`, which can produce a `-1` value if it is called on an `$item_device` object that was not initialized correctly.

**Comment by jackburton79** [comment]
Thanks!
Should I file a ticket on the ocsinventoryng plugin project page then ?

**Comment by cedric-anne** [comment]
> Should I file a ticket on the ocsinventoryng plugin project page then ?

Not sure this bug is still present there. I guess it can just be ignore for now.

**Comment by cedric-anne** [comment]
For illegitimate negative values in GLPI core, they will be handled by #10763 . For thoose related to plugins, fix has to be produced on plugin side.
