### ISSUE TITLE
CSV Export - First always line empty

### ISSUE THREAD

**Issue by conchaji** [glpi-project/glpi#10569]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.6

### Bug description

Hi friends!

When exporting current page in CSV or all pages, the first line of the csv before the header is always empty.

This makes really difficult to quickly arrange columns in order in Excel.

Why this happen? and can be fix? I didn't find any other question about this in the forum, hope it is not duplicated.

Thanks a lot

![Captura](https://user-images.githubusercontent.com/80054423/152798895-0ebf15ae-7770-4356-9986-84f11e2e99a8.PNG)

### Steps To reproduce

1. Assets > computers (or any asset)
2. Export current or all pages in csv
3. Open in excel

**Comment by cconard96** [comment]
I tested on 9.5.5 (release archive), 9.5.6 tag, and the latest 9.5 commit (based on 9.5.7) and could not recreate the issue.

Looking at the characters at the start of the Name column heading, it looks like Excel isn't loading it with the correct encoding. CSV files from GLPI use Unicode encoding with a byte order mark.

**Comment by conchaji** [comment]
Hi!

Thanks!

That's certainly odd. I'm using GLPI 9.5.5 Copyright (C) 2015-2021 and It is not only Exel but also happen with Notepad++ or if I open this in the terminal.

![adasd](https://user-images.githubusercontent.com/80054423/154058491-cdc01444-024e-4b4e-b222-b28930988b4e.PNG)
![asd](https://user-images.githubusercontent.com/80054423/154058497-c4b5b2d9-8cda-4388-919c-96f3c3058f2a.PNG)

Any other idea?

**Comment by cedric-anne** [comment]
On my GLPI instance, when exporting a CSV, there is no BOM.

I have no active plugin. You should try to reproduce without any plugins.

```
$ /usr/bin/printf ~/Téléchargements/glpi.csv | file -
/dev/stdin: UTF-8 Unicode text, with no line terminators
```

```
$ cat ~/Téléchargements/glpi.csv 
"Name";"Entity";"Status";"Manufacturer";"Serial number";"Type";"Model";"Operating System - Name";"Location";"Last update";"Components - Processor";
"(1)";"Entité racine";"";"";"";"";"";"";"";"2022-02-04 14:15";"";
"fhfdhg > qsdqs";"Entité racine > qs dfqsdf";"";"";"";"";"";"";"";"2022-02-16 08:23";"";
"qsdfqsdfsdf";"Entité racine > aaa";"";"";"";"";"";"";"";"2022-02-02 15:50";"";
"wxcv";"Entité racine";"";"";"";"";"";"";"";"2022-02-02 15:44";"";
"xcbxcv b";"Entité racine";"";"";"";"";"";"";"";"2021-11-02 10:58";"";
"xcvb";"Entité racine";"";"";"";"";"";"";"";"2022-02-02 15:37";"";
"xcvb";"Entité racine";"";"";"";"";"";"";"";"2022-02-02 15:37";"";
```

**Comment by conchaji** [comment]
Hi cedric-anne!

First of all, please excuse me for the delay!

This is my output:

cat glpi.csv | file -
/dev/stdin: UTF-8 Unicode text**, with CRLF, LF line terminators**

Please can you advice on how to change this to generate csv as yours?: with no line terminators

Thanls a lot!

**Comment by cedric-anne** [comment]
I guess it is normal to have CRLF, LF line terminators if you do your export from a windows server.

Did you tried will all plugins deactivated ?

**Comment by cedric-anne** [comment]
I close his issue due to lack of feedback. Feel free to reopen.
