### ISSUE TITLE
[GLPI 10 RC1] : Impossible to add new entity

### ISSUE THREAD

**Issue by JTrotta** [glpi-project/glpi#10573]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 - rc1

### Bug description

Adding new entity, reply is a blank page

### Relevant log output

```shell
[2022-02-07 19:18:38] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Entity::handleConfigStrategyFields() must be of the type array, bool given, called in /var/www/html/glpi10/src/Entity.php on line 324 in /var/www/html/glpi10/src/Entity.php at line 360
  Backtrace :
  src/Entity.php:324                                 Entity->handleConfigStrategyFields()
  src/CommonDBTM.php:1507                            Entity->prepareInputForUpdate()
  front/dropdown.common.form.php:134                 CommonDBTM->update()
  front/entity.form.php:50                           include()
```

### Page URL

front/entity.form.php

### Steps To reproduce

Try to add a new Entity

### Your GLPI setup information

Operating system: Linux localhost.localdomain 4.18.0-348.12.2.el8_5.x86_64 #1 SMP Wed Jan 19 17:53:40 UTC 2022 x86_64
PHP 7.4.19 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.37 (rocky) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.28-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi10
	Host info: Localhost via UNIX socket

**Comment by flegastelois** [comment]
Duplicate #10572

**Comment by JTrotta** [comment]
Sorry
