### ISSUE TITLE
[GLPI 10.0.0-rc1] Mailgate PHP User Warning exceed 255 characters long (266), it will be truncated

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#10574]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

When a ticket is opened by email with a subject longer than 255 characters. A log keeps getting added to PHP errors.
Ticket never get created, even if the warning say it will get truncated.

### Relevant log output

```shell
[2022-02-08 07:48:02] glpiphplog.WARNING:   *** PHP User Warning (512): [REDACTED (>255 chars)] exceed 255 characters long (266), it will be truncated. in E:\GLPI\src\CommonDBTM.php at line 4109
  Backtrace :
  src\CommonDBTM.php:4109                            trigger_error()
  src\CommonDBTM.php:1214                            CommonDBTM->filterValues()
  src\MailCollector.php:845                          CommonDBTM->add()
  src\MailCollector.php:1821                         MailCollector->collect()
  src\CronTask.php:1016                              MailCollector::cronMailgate()
  front\cron.php:82                                  CronTask::launch()
```

### Page URL

front/cron.php

### Steps To reproduce

1. Open a ticket by email with a subject longer than 255 chars.

### Your GLPI setup information

Operating system: Windows NT SRVGLPI10 10.0 build 17763 (Windows Server 2016) AMD64
PHP 8.1.1 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="2048M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2048M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.5-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.1) is supported.PHP version (8.1.1) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.6.5) is supported.Database engine version (10.6.5) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to E:\GLPI/files/_cache has been validated. Write access to E:\GLPI/config has been validated. Write access to E:\GLPI/files/_cron has been validated. Write access to E:\GLPI/files has been validated. Write access to E:\GLPI/files/_dumps has been validated. Write access to E:\GLPI/files/_graphs has been validated. Write access to E:\GLPI/files/_lock has been validated. Write access to E:\GLPI/files/_pictures has been validated. Write access to E:\GLPI/files/_plugins has been validated. Write access to E:\GLPI/files/_rss has been validated. Write access to E:\GLPI/files/_sessions has been validated. Write access to E:\GLPI/files/_tmp has been validated. Write access to E:\GLPI/files/_uploads has been validated.Write access to E:\GLPI/files/_cache has been validated.
Write access to E:\GLPI/config has been validated.
Write access to E:\GLPI/files/_cron has been validated.
Write access to E:\GLPI/files has been validated.
Write access to E:\GLPI/files/_dumps has been validated.
Write access to E:\GLPI/files/_graphs has been validated.
Write access to E:\GLPI/files/_lock has been validated.
Write access to E:\GLPI/files/_pictures has been validated.
Write access to E:\GLPI/files/_plugins has been validated.
Write access to E:\GLPI/files/_rss has been validated.
Write access to E:\GLPI/files/_sessions has been validated.
Write access to E:\GLPI/files/_tmp has been validated.
Write access to E:\GLPI/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to E:\GLPI/marketplace has been validated.Write access to E:\GLPI/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cconard96** [comment]
I wasn't able to even get the warning but fixed that and the truncation with:
https://github.com/glpi-project/glpi/pull/10579

Can you test to see if this works for you?

**Comment by SteadEXE** [comment]
Yeah it's seems fine. Mail get loaded, ticket get created.
But there is an another log :

`[2022-02-08 12:41:04] glpiphplog.WARNING:   *** PHP User Warning (512): [GLPI #0000040] Nouveau ticket : [REDACTED] exceed 255 characters long (295), it will be truncated. in E:\GLPI\src\CommonDBTM.php at line 4110
  Backtrace :
  src\CommonDBTM.php:4110                            trigger_error()
  src\CommonDBTM.php:1214                            CommonDBTM->filterValues()
  src\NotificationMailing.php:167                    CommonDBTM->add()
  src\Notification.php:608                           NotificationMailing->sendNotification()
  src\NotificationEventAbstract.php:148              Notification::send()
  src\NotificationEvent.php:185                      NotificationEventAbstract::raise()
  src\Ticket.php:2141                                NotificationEvent::raiseEvent()
  src\CommonDBTM.php:1246                            Ticket->post_addItem()
  src\MailCollector.php:840                          CommonDBTM->add()
  src\MailCollector.php:1821                         MailCollector->collect()
  src\CronTask.php:1016                              MailCollector::cronMailgate()
  front\cron.php:82                                  CronTask::launch()`

I guess there is the same issue with notification now.

**Comment by cconard96** [comment]
The warnings are intentional so that there is a record of the truncation. It has to be done because of the limitation of the DB column type.

Does the notification actually send still?

**Comment by SteadEXE** [comment]
Nevermind, the notification is sent 👍 

Thanks
