### ISSUE TITLE
[GLPI 10.0.0-rc1] Search with item seen doesn't return no results

### ISSUE THREAD

**Issue by rmsetra411** [glpi-project/glpi#10575]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0-rc1

### Bug description

When you search with item seen, it doesn't return no results with the item Value show.

![image](https://user-images.githubusercontent.com/99241608/152938759-55237840-502f-4723-a0a8-59b0c18c25b0.png)

### Relevant log output

```shell
[2022-02-08 10:27:48] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined offset: 1 in /opt/glpi/src/Search.php at line 4532
  Backtrace :
  src/Search.php:1234                                Search::addWhere()
  src/Search.php:760                                 Search::constructCriteriaSQL()
  src/Search.php:370                                 Search::constructSQL()
  src/Search.php:123                                 Search::getDatas()
  src/Search.php:100                                 Search::showList()
  front/computer.php:40                              Search::show()
```

### Steps To reproduce

Go to Select default items to show.
Add item "Value"

### Your GLPI setup information

Operating system: Linux GLPI-Server 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="8M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 192.168.1.206 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36
Server Software: Ubuntu 20.04
	Server Version: 10.3.32-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: Admin@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.PHP version (7.4.3) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.3.32) is supported.Database engine version (10.3.32) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /opt/glpi/files/_cache has been validated. Write access to /opt/glpi/config has been validated. Write access to /opt/glpi/files/_cron has been validated. Write access to /opt/glpi/files has been validated. Write access to /opt/glpi/files/_dumps has been validated. Write access to /opt/glpi/files/_graphs has been validated. Write access to /opt/glpi/files/_lock has been validated. Write access to /opt/glpi/files/_pictures has been validated. Write access to /opt/glpi/files/_plugins has been validated. Write access to /opt/glpi/files/_rss has been validated. Write access to /opt/glpi/files/_sessions has been validated. Write access to /opt/glpi/files/_tmp has been validated. Write access to /opt/glpi/files/_uploads has been validated.Write access to /opt/glpi/files/_cache has been validated.
Write access to /opt/glpi/config has been validated.
Write access to /opt/glpi/files/_cron has been validated.
Write access to /opt/glpi/files has been validated.
Write access to /opt/glpi/files/_dumps has been validated.
Write access to /opt/glpi/files/_graphs has been validated.
Write access to /opt/glpi/files/_lock has been validated.
Write access to /opt/glpi/files/_pictures has been validated.
Write access to /opt/glpi/files/_plugins has been validated.
Write access to /opt/glpi/files/_rss has been validated.
Write access to /opt/glpi/files/_sessions has been validated.
Write access to /opt/glpi/files/_tmp has been validated.
Write access to /opt/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /opt/glpi/marketplace has been validated.Write access to /opt/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cconard96** [comment]
Can you test the changes made in #10581?

**Comment by rmsetra411** [comment]
Thanks. It works :)
