### ISSUE TITLE
Turkish Version Wrong Menu Translation 

### ISSUE THREAD

**Issue by xismailaydin** [glpi-project/glpi#10578]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Turkish Language have 2 menu items same Title.

English Version Menu Titles:
Management and Administration

Turkish Version Menu Titles: 

After 10.0.0-rc1 Pre-release
Management = Yönetim
Administration = Yönetim

Before 10.0.0-rc1 Pre-release
Management = İdari
Administration = Yönetim

And if you click Management menu in Turkish as Yönetim, Administration menu is expanding because of same name.
Screenshot added.
![glpi-10-rc1-turkish-bug](https://user-images.githubusercontent.com/99165069/152971344-212d3a07-32b7-446b-938d-ca4192cf400e.png)

### Relevant log output

```shell
There is no error log. Translation error.
```

### Steps To reproduce

1. Login GLPI
2. Select Language Turkish
3. You will see multiple Titles in same name as Yönetim
4. Click one of menu named Yönetim
5. You will see other menu collapsed. This is bug. 
6. Old translation was OK. Management = İdari, Administration = Yönetim

### Your GLPI setup information

<details><summary>Kurulu sistem ve yapılandırması hakkında bilgiler</summary><pre>GLPI 10.0.0-rc1 (/glpi => /home/xismailaydin/public_html/glpi)
Installation mode: TARBALL
Current language:tr_TR

</details><details><summary>Server</summary><pre> 
Operating system: Linux ni-safari.guzelhosting.com 3.10.0-962.3.2.lve1.5.63.el7.x86_64 #1 SMP Fri Oct 8 12:03:35 UTC 2021
	x86_64
PHP 7.4.27 litespeed (Core, PDFlib, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, i360, iconv, igbinary, imap, intl, json, ldap, libxml,
	litespeed, mbstring, memcached, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop,
	soap, sockets, sodium, sqlite3, standard, tidy, timezonedb, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="2048M" post_max_size="128M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: LiteSpeed
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36 OPR/83.0.4254.16 (Edition beta)
Server Software: MySQL Community Server - (GPL)
	Server Version: 5.7.36-cll-lve
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xismaila_glpi@localhost/xismaila_glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.27) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (5.7.36) is supported.
The log file has been created successfully.
Write access to /home/xismailaydin/public_html/glpi/files/_cache has been validated.
Write access to /home/xismailaydin/public_html/glpi/config has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_cron has been validated.
Write access to /home/xismailaydin/public_html/glpi/files has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_dumps has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_graphs has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_lock has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_pictures has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_plugins has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_rss has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_sessions has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_tmp has been validated.
Write access to /home/xismailaydin/public_html/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/xismailaydin/public_html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /home/xismailaydin/public_html/glpi
GLPI_CONFIG_DIR: /home/xismailaydin/public_html/glpi/config
GLPI_VAR_DIR: /home/xismailaydin/public_html/glpi/files
GLPI_MARKETPLACE_DIR: /home/xismailaydin/public_html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /home/xismailaydin/public_html/glpi/files
GLPI_CACHE_DIR: /home/xismailaydin/public_html/glpi/files/_cache
GLPI_CRON_DIR: /home/xismailaydin/public_html/glpi/files/_cron
GLPI_DUMP_DIR: /home/xismailaydin/public_html/glpi/files/_dumps
GLPI_GRAPH_DIR: /home/xismailaydin/public_html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /home/xismailaydin/public_html/glpi/files/_locales
GLPI_LOCK_DIR: /home/xismailaydin/public_html/glpi/files/_lock
GLPI_LOG_DIR: /home/xismailaydin/public_html/glpi/files/_log
GLPI_PICTURE_DIR: /home/xismailaydin/public_html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /home/xismailaydin/public_html/glpi/files/_plugins
GLPI_RSS_DIR: /home/xismailaydin/public_html/glpi/files/_rss
GLPI_SESSION_DIR: /home/xismailaydin/public_html/glpi/files/_sessions
GLPI_TMP_DIR: /home/xismailaydin/public_html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /home/xismailaydin/public_html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /home/xismailaydin/public_html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /home/xismailaydin/public_html/glpi/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/home/xismailaydin/public_html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.3 in (/home/xismailaydin/public_html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/xismailaydin/public_html/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/home/xismailaydin/public_html/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/home/xismailaydin/public_html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/xismailaydin/public_html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/xismailaydin/public_html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/home/xismailaydin/public_html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/xismailaydin/public_html/glpi/vendor/sabre/http/lib)
sabre/uri in (/home/xismailaydin/public_html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/home/xismailaydin/public_html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/xismailaydin/public_html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/xismailaydin/public_html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/xismailaydin/public_html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/xismailaydin/public_html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/xismailaydin/public_html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/xismailaydin/public_html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/home/xismailaydin/public_html/glpi/vendor/symfony/console)
scssphp/scssphp in (/home/xismailaydin/public_html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/xismailaydin/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/xismailaydin/public_html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/xismailaydin/public_html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/xismailaydin/public_html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/xismailaydin/public_html/glpi/vendor/ramsey/uuid/src)
psr/log in (/home/xismailaydin/public_html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/xismailaydin/public_html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/home/xismailaydin/public_html/glpi/vendor/psr/cache/src)
league/csv in (/home/xismailaydin/public_html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/home/xismailaydin/public_html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/xismailaydin/public_html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/xismailaydin/public_html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/xismailaydin/public_html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/xismailaydin/public_html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/xismailaydin/public_html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/xismailaydin/public_html/glpi/vendor/symfony/cache)
html2text/html2text in (/home/xismailaydin/public_html/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/home/xismailaydin/public_html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/home/xismailaydin/public_html/glpi/vendor/twig/twig/src)
twig/string-extra in (/home/xismailaydin/public_html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/home/xismailaydin/public_html/glpi/vendor/symfony/polyfill-php80)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

### Anything else?

No

**Comment by cconard96** [comment]
Translations are done on the Transifex platform.

If you wish to contribute translations, you can from Transifex by requesting access to translate for German.
Direct link: https://www.transifex.com/glpi/GLPI/language/tr_TR/
To request access, click the 3 dots menu next to "View Members" and select "Join team".

**Comment by cconard96** [comment]
I just found out that the Transifex link will show a 404 if you aren't logged in to Transifex already. Just in case you would see that, you would just have to log in and then navigate to that link.

**Comment by xismailaydin** [comment]
I reached Transifex, registered and commited translation suggest and explaination. Thank you for your interest. :))
