### ISSUE TITLE
Adding entity leads to white screen

### ISSUE THREAD

**Issue by DaviidMM** [glpi-project/glpi#10572]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Creating a new entity leads to a white screen where nothing happens.

### Relevant log output

```shell
[2022-02-07 16:55:56] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Entity::handleConfigStrategyFields() must be of the type array, bool given, called in /var/www/glpi/src/Entity.php on line 324 in /var/www/glpi/src/Entity.php at line 360
  Backtrace :
  src/Entity.php:324                                 Entity->handleConfigStrategyFields()
  src/CommonDBTM.php:1507                            Entity->prepareInputForUpdate()
  front/dropdown.common.form.php:134                 CommonDBTM->update()
  front/entity.form.php:50                           include()
```

### Steps To reproduce

1. Go to Administration > Entities
2. Click `+ Add` button
3. Enter desired entity name
4. Click `Save` button

### Your GLPI setup information

- Ubuntu 20.04 LTS
- PHP 7.4.3 (all of the modules required and optional are enabled)
- Apache 2.4.41 (Ubuntu)
- Node version 10.19.0
- Browsers tested: Chrome, Firefox and Safari. All of them in their last releases.

**Comment by DaviidMM** [comment]
I can create a new entity now as a child of the `Root entity` entity.

Now I would like to rename de `Root entity` to a custom name, but I get the white screen again.

Log output:

```bash
[2022-02-07 17:30:10] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Entity::handleConfigStrategyFields() must be of the type array, bool given, called in /var/www/glpi/src/Entity.php on line 324 in /var/www/glpi/src/Entity.php at line 360
  Backtrace :
  src/Entity.php:324                                 Entity->handleConfigStrategyFields()
  src/CommonDBTM.php:1507                            Entity->prepareInputForUpdate()
  front/dropdown.common.form.php:134                 CommonDBTM->update()
  front/entity.form.php:50                           include()
```

**Comment by cconard96** [comment]
This should also be fixed. #10543

**Comment by DaviidMM** [comment]
I made the changes described in that PR but I still get the same white screen and log error

**Comment by arthurrschaefer** [comment]
#10549 Worked fine to add new entities.
#10543 seemed not to work properly. I get the same blank screen as @DaviidMM 

**But just when changing the root entity name**

glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Entity::handleConfigStrategyFields() must be of the type array, bool given, called in /var/www/html/glpi10/src/Entity.php on line 324 in /var/www/html/glpicurrent/src/Entity.php at line 360
  Backtrace :
  src/Entity.php:324                                 Entity->handleConfigStrategyFields()
  src/CommonDBTM.php:1507                            Entity->prepareInputForUpdate()
  front/dropdown.common.form.php:134                 CommonDBTM->update()
  front/entity.form.php:50                           include()

**Comment by cedric-anne** [comment]
I was not able to reproduce this issue on current state of master branch.

#10658 should prevent this kind of errors on edge cases, but it is not related to root entity edition.

**Comment by cconard96** [comment]
@DaviidMM or @arthurrschaefer can you re-test this on the latest nightly "master" release?
https://nightly.glpi-project.org/glpi/

**Comment by cedric-anne** [comment]
I close this issue due to lack of feedback. Feel free to reopen.

**Comment by faizal3315** [comment]
Hello everyone 

how to fix blank to add entities??

**Comment by DaviidMM** [comment]
> @DaviidMM or @arthurrschaefer can you re-test this on the latest nightly "master" release? https://nightly.glpi-project.org/glpi/

Sorry about the lack of feedback. Installing the last update of GLPI solved the problem for me. Thank you!
