### ISSUE TITLE
[GLPI 10.0.0-rc1/rc2] Native inventory expiration configuration is missing

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi#10588]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

The delay between automatic inventory needs to be configurable somewhere, probably in the `http://glpi-server/front/inventory.conf.php` page. It actually defaults to 24h.

### Anything else?

This issue is related to [glpi-inventory-plugin #50](https://github.com/glpi-project/glpi-inventory-plugin/issues/50) as it has a configuration field for that in **General setup** but changing it doesn't change the delay.

**Comment by SteadEXE** [comment]
I guess you can change the title to RC2, it's not there yet 👍

**Comment by trasher** [comment]
Fixed as of #11019
