### ISSUE TITLE
There are no groups in "Planning - add Calendar - Groups"

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#10582]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-rc1

### Bug description

I have a couple groups.
I try add group's calendar in Planning menu. There are no any groups in "Planning - add Calendar - Groups"
![Screenshot_233](https://user-images.githubusercontent.com/15270519/152981673-b3d81a75-9b11-4e82-b3e3-b29f3ef409dc.png)
![Screenshot_234](https://user-images.githubusercontent.com/15270519/152981721-34a3372b-5bfa-4fd3-8c37-ceea8e8bcd1d.png)

### Page URL

/glpi/front/planning.php

**Comment by cedric-anne** [comment]
Hi,

Only groups that are visible in ticket task are shown here. The default selected value for this flag is currently "no" (see #10660).
If you set this flag to "yes" on some groups, you should be able to see them here.

Regards
