### ISSUE TITLE
[GLPI 10.0.0-rc1] Display bug in small | split screen

### ISSUE THREAD

**Issue by atomiksteak77** [glpi-project/glpi#10592]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0RC1

### Bug description

Bonjour,

Lors de l'utilisation en "petit" écran , la barre "home" ne passe pas sous le menu deroulant:

Hello,

When using the "small" screen, the "home" bar does not go under the scrolling menu:

Exemple 1
![image](https://user-images.githubusercontent.com/99338821/153214044-09b44364-7369-4ea5-b0af-22007596135d.png)

Exemple 2
![image](https://user-images.githubusercontent.com/99338821/153214186-957ad039-15bf-4ca8-be27-16c53c3d659d.png)

### Steps To reproduce

1.Ouvrir GLPI en petite fenetre 
2.Aller dans le menu setup / dropdown ( Par exemple)
3.Descendre la page avec le menu deroulant ouvert .

**Comment by trasher** [comment]
Please write in english only.
