### ISSUE TITLE
TTR calculation for SLAs defined in days and Default Calendar

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#10594]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

There is bug in accounting of Pending time when this is met:
1. TTR is defined in days
2. TTR is using calendar without working days for some weekdays and/or holidays (ex. Default calendar)

Function getActiveTimeBetween expects calendar to be 24/7 without holidays see:
https://github.com/glpi-project/glpi/blob/c2a3f2c05e7eee62739dd5fd9e00dca648ef4731/inc/calendar.class.php#L320

But SLA end date calculation computeEndDate counts with holidays (and working hours):
https://github.com/glpi-project/glpi/blob/c2a3f2c05e7eee62739dd5fd9e00dca648ef4731/inc/calendar.class.php#L507

TTR calculation with waiting works like this, first getActiveTimeBetween is called to compute sla_waiting_duration and this is passed to computeEndDate afterwards.
This will lead to issues when ticket is pending over the weekend for example and it will resume after. Too much delay will be accounted.

### Steps To reproduce

1. Create SLA to have TTR 1 day and attach it to default calendar
2. Create ticket attach the created SLA
3. Change status to Pending status
4. Leave it pending over the weekend
5. Resume ticket to working status Processing (Assigned)

Also weekend will be accounted as active time so the new TTR time will be +3 days not just one.

### Your GLPI setup information

Default installation of 9.5.6 without plugins

### Anything else?

I tried to think about fix but it does not seem to be so straightforward, if we would like to account correctly for reminders of working time (coming from working to pending status multiple times).

**Comment by cconard96** [comment]
I closed the PR for my fix because I found it wasn't correct. It wasn't easy to determine the intention of the legacy code and was very complex.
