### ISSUE TITLE
latencies glpi 9.1

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1059]
Hello

I have installed the new release 9.1 and I have latencies in different modules during 10/15 seconds.

Please tell me if you need information, logs....

![image](https://cloud.githubusercontent.com/assets/15144026/18832484/fc529ca8-83eb-11e6-98a3-4e68f81ea67b.png)

![Uploading image.png…]()

**Comment by fgpy** [comment]
Depending on your server config, replacing 'localhost' by '127.0.0.1' in your $dbhost config_db.php sometimes helps.

**Comment by tomolimo** [comment]
Same remark for mysql configuration

**Comment by tomolimo** [comment]
Anyway: what is your configuration?
OS, web server, ...?

**Comment by satyan01** [comment]
It seems to solve my issue
