### ISSUE TITLE
GLPI 10 RC1 - Create new ticket window 

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10598]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 RC1

### Bug description

Hi.

i dont think its a bug but the design when u create a new ticket in a standard interface , the window is aligned to bottom of the page leave a blank white space on top.

![image](https://user-images.githubusercontent.com/22425503/153390863-abbe8a53-19e6-48bf-b1f0-f0345fded9f8.png)

**Comment by tsmr** [comment]
Due to : 

.itil-object .itil-left-side {
  height: 100%;
  ....
}

**Comment by cconard96** [comment]
This seems to be the intended design. As it is, it allows the side panel to show as many options at once as possible. Having the new ticket title and description form aligned to the bottom could be seen as normal as it is effectively the start of a conversation (Chat applications usually have message input at bottom and then it goes to the top when sent/saved).
