### ISSUE TITLE
[GLPI 10.0.0-rc1] software addition history

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#10605]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Hello, I have the following problem.
  Go to Home->Assets->Software now, for example, select 7-Zip 19.00 (x64), and then go to the “Historical” tab and get the message “No historical”, while any events in terms of adding this program from the user, deleting etc. The question is, do I understand correctly what kind of data should be displayed in this tab, or is it supposed to display a different type of information, if so, what kind of information?

### Anything else?

![3](https://user-images.githubusercontent.com/97535165/153427111-c094380d-1c28-44bc-b34c-daeb12700f19.png)

**Comment by cconard96** [comment]
The historical tab for Software only shows changes to the Software form, addition/removal of versions, etc. The history of installations would be done in the Software Versions.

**Comment by Badkempachi** [comment]
> The historical tab for Software only shows changes to the Software form, addition/removal of versions, etc. The history of installations would be done in the Software Versions.

Hey, @cconard96 
My history is not displayed, for example, the same GLPI Agent. During the tests, it was reinstalled several times on different computers, as well as on virtual machines, but the history is empty, what is the reason for this?
![изображение](https://user-images.githubusercontent.com/97535165/156126229-51b4bb14-9cef-4205-bc33-c096f01a7508.png)
![изображение](https://user-images.githubusercontent.com/97535165/156126236-242651aa-cd7e-446c-a04c-f1a9ad1e8f48.png)

**Comment by trasher** [comment]
Did you talk about logs from an inventory, or manually created assets? Anyways, try with 10.0-rc3 to see if you still reproduce.

**Comment by Badkempachi** [comment]
> Did you talk about logs from an inventory, or manually created assets? Anyways, try with 10.0-rc3 to see if you still reproduce.

Hi, @trasher 

The problem was checked on the latest version GLPI night bild master.83848a8.tar.gz 29.03.2022.

That's right, I wrote about the magazines from the inventory.
For example, if we go to Home->Assets->Software and select, for example, the nightly build of the GLPI Agent 1.2 (git9418c6ef) dated 03/29/22 and go to the “Historical” tab, and there 2 events will be waiting for me:

96828 29-03-2022 10:43 inventory Version Add an item: Version (1.2 (12032))
96824 29-03-2022 10:43 inventory Add the item.

And no matter how many installations or deletions are made, new events do not appear here.
For other programs, the situation is similar with events, if we update the version of the program, then in this case a new entity is created. In my understanding, this tab should display events if the selected program is installed, indicating the name of the device on which it was installed. In the best case, the time when the installation was performed is also displayed. The agent provides this information to the glpi server, but it stores this information in other tables. Do I understand correctly what information should be displayed?

If I misunderstood the situation with “Historical” described above, then please go here Home->Assets->Software->eg GLPI Agent 1.2 . Next, we go to the " Versions " tab and select version 1.2. We immediately find ourselves in the “Installations” tab, where devices are displayed where this version of the agent was installed, indicating the date of installation. There is also a tab “Historical” and it is empty in this case.
Sorry for such a sheet, but this question is very important for me, are there plans to change the “Historical” tab to display detailed information? Or maybe it works for others, but not for me?

![6](https://user-images.githubusercontent.com/97535165/160591894-51b1100c-3449-46d9-9032-2338a127a984.png)
![4](https://user-images.githubusercontent.com/97535165/160591904-1af41506-2d7f-4eb1-a955-d5be7046e686.png)
![5](https://user-images.githubusercontent.com/97535165/160591908-94dd4b0c-ee0b-4bea-94e8-f69cbcf8a03b.png)

**Comment by orthagh** [comment]
Hello @Badkempachi could you check the #11155 PR, it should add the missing logs into Software and SoftwareVersion objects.

If you need, you can get a patch by adding `.patch` to the url of the PR

**Comment by Badkempachi** [comment]
> Hello @Badkempachi could you check the #11155 PR, it should add the missing logs into Software and SoftwareVersion objects.
> 
> If you need, you can get a patch by adding `.patch` to the url of the PR

Hey
I may be doing something wrong, but in fact the problem remains. At the current moment, I can see the date the software was installed. But I do not see information when the previous version was installed, this information is simply removed from the history.
I installed the latest version from a nightly build today and after installing a new version of glpi agent, only 2 entries are shown in the history:
148701 04-04-2022 13:15 inventory Version - Add an item: Version (1.2 (24001))
148700 04-04-2022 13:15 inventory - Add the item.
But I want to warn you in advance that I completed the update on the same day you wrote, and I waited a little time to collect the necessary information.
Please tell me what I need to do so that the information is correctly written to the database, and I can get this information, for example, through select.
Do you need logs?

**Comment by Badkempachi** [comment]
![1](https://user-images.githubusercontent.com/97535165/161565470-1be6c451-3256-4683-a301-56a46f1e18c9.png)
![2](https://user-images.githubusercontent.com/97535165/161565477-81c7c1a2-23bf-4aaf-a022-f4cd6b74539d.png)
