### ISSUE TITLE
 [GLPI 10.0.0-rc1] device addition history 

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#10604]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Hello, I have the following problem.
Go to Home->Assets->Computers->Historical and as an example we see the line “Add a component: Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor Thermal Subsystem (19)”. It is not clear what information the numerical value in brackets carries. Is it the number of times the device has been imported, or is it the category number of the device, or is it something else? At the same time, it is not clear why the history shows that one part of the PC components was imported one day, and another the next, despite the fact that the agent collects all the information at once and when adding a new PC, I see all the information at once.
Interested in what is the reason for the incompleteness of the information displayed in the history? I would like to know how this process works.

### Anything else?

![1](https://user-images.githubusercontent.com/97535165/153423082-7899f2f8-d807-4647-8558-531fdac83280.png)
![2](https://user-images.githubusercontent.com/97535165/153423086-b195e4c2-b1aa-406b-9a78-ae57688c0e02.png)

**Comment by cconard96** [comment]
The number in brackets/parenthesis is the ID for the added/updated item.

As to why they are being deleted and recreated presumably every time inventory is run or only parts of the inventory come in each time, I cannot say. Are you using the GLPI Agent and if so, which version?

**Comment by Badkempachi** [comment]
> Число в скобках/круглых скобках — это идентификатор добавленного/обновленного элемента.
> 
> Что касается того, почему они удаляются и создаются заново, предположительно каждый раз, когда проводится инвентаризация, или каждый раз приходят только части инвентаря, я не могу сказать. Используете ли вы агент GLPI, и если да, то какую версию?

Hi, @cconard96 
Used by GLPI-Agent v1.2-git1ea464ca.
I would understand the reason for the change if my devices changed, but this does not happen.
As a result, in two months there are more than 1000 entries in the history that do not carry useful information, I suggest that you consider checking if the device entry is in the database, and if it is found, then do not add information to the history.
As for the identifiers in brackets, it is also not very clear what they carry in themselves due to the fact that these identifiers are duplicated with other devices.
![изображение](https://user-images.githubusercontent.com/97535165/156121211-06b788ab-a87f-47e2-b733-5525da7e4809.png)

**Comment by Badkempachi** [comment]
> The number in brackets/parenthesis is the ID for the added/updated item.
> 
> As to why they are being deleted and recreated presumably every time inventory is run or only parts of the inventory come in each time, I cannot say. Are you using the GLPI Agent and if so, which version?

Hi, @cconard96 
Used by GLPI-Agent v1.2-git1ea464ca.
I would understand the reason for the change if my devices changed, but this does not happen.
As a result, in two months there are more than 1000 entries in the history that do not carry useful information, I suggest that you consider checking if the device entry is in the database, and if it is found, then do not add information to the history.
As for the identifiers in brackets, it is also not very clear what they carry in themselves due to the fact that these identifiers are duplicated with other devices.
![изображение](https://user-images.githubusercontent.com/97535165/156121442-c852e7f6-3811-4d60-83c5-2be2754815d4.png)

**Comment by cconard96** [comment]
I confirm that at least the Computer's component inventory is deleted and recreated every time.

**Comment by cconard96** [comment]
> I confirm that at least the Computer's component inventory is deleted and recreated every time.

Nope, nevermind. Now it is behaving for me...

**Comment by cconard96** [comment]
Seems related to #10880. If so, then it looks like it is just an issue with extra historical entries being added even when the devices aren't actually getting recreated.

**Comment by trasher** [comment]
Please try with 10.0-rc3

**Comment by Badkempachi** [comment]
> Please try with 10.0-rc3

Hi, @trasher 
The problem is partially solved, the situation with duplicate identifiers for the equipment was not detected, and the situation with events for deleting and adding devices has decreased, but not completely. The screenshot provides data from the monoblock, it did not turn off for several days, which excludes the possibility of changing the configuration, but it is still available. First of all, “Network port” after performing an inventory and updating the information received from the agent in the GLPI panel, the deletion of ports is displayed in the history. But the most interesting thing is that information about adding new ports is not displayed in the history. But I still have a device struggle for various peripherals, such as Bluetooth, usb ports and monitors. I have about 30 monoblocks, but only 3 are displayed in the monitors, and after updating the information received from the agent, the reassignment occurs.
![1](https://user-images.githubusercontent.com/97535165/160580511-cc62e7e8-4d00-4f2f-a74f-56d1b009815e.png)
![2](https://user-images.githubusercontent.com/97535165/160580516-439c23e6-c193-40cc-8419-a926543e2b04.png)
![3](https://user-images.githubusercontent.com/97535165/160580521-5f209968-7359-4302-a2de-798dbff4646b.png)

**Comment by stonebuzz** [comment]
Hi @Badkempachi 
For history on add can you try this -> https://github.com/glpi-project/glpi/pull/13574

Best regards
