### ISSUE TITLE
php warning : executing strlen() on an array

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#10602]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

The following commit triggers a php warning when creating a ticket with a validator user

https://github.com/glpi-project/glpi/commit/6ae95fbbe8b2ebc85babf6a11e659d458054a2fd
```
[Thu Feb 10 11:58:40 2022] PHP Warning:  strlen() expects parameter 1 to be string, array given in /home/bugier/public_html/glpi-master/src/CommonDBTM.php on line 4107
[Thu Feb 10 11:58:40 2022] PHP Stack trace:
[Thu Feb 10 11:58:40 2022] PHP   1. {main}() /front/ticket.form.php:0
[Thu Feb 10 11:58:40 2022] PHP   2. Ticket->add($input = *uninitialized*, $options = *uninitialized*, $history = *uninitialized*) /home/bugier/public_html/glpi-master/front/ticket.form.php:72
[Thu Feb 10 11:58:40 2022] PHP   3. Ticket->filterValues($display = *uninitialized*) /home/bugier/public_html/glpi-master/src/CommonDBTM.php:1214

```

When enterinf CommonDBTM::filterValues() $this->input['users_id_validator key'] contains an array (see Ticket::getDefaultValues())  but there is an attempt to truncate it aas if it is a string. 

It seems there is an inconsistency in the fact this value is an array in one hand, and  the fact its type in the search options is itemlink in an other hand. 

### Page URL

front/ticket.form.php

### Steps To reproduce

Create a ticket in GLPI with a user as approbator.

### Your GLPI setup information

GLPI 10 branch master

### Anything else?

Problem introduced by https://github.com/glpi-project/glpi/pull/10579

**Comment by cedric-anne** [comment]
Fixed by cb7751c36d3dc92f29d6df6e778c92d2e7c6f057.
