### ISSUE TITLE
Randomly getting notification response message out of correct flow

### ISSUE THREAD

**Issue by carlosbayerl** [glpi-project/glpi#10613]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.6

### Bug description

Resultados de tradução
we are randomly getting notification response message out of the correct flow. Note that this message is old, ended in 

25612131 | 19-10-2021 22:13 | cron_closeticket | Data de fechamento | Mudança de para 19-10-2021   22:13

**Comment by carlosbayerl** [comment]
> Oi,
> 
> Sua descrição do bug não é muito clara. A que `25612131 | 19-10-2021 22:13 | cron_closeticket | Data de fechamento | Mudança de para 19-10-2021 22:13`se refere?
> 
> Você verificou se todas as suas tarefas cron são executadas corretamente no cronograma esperado? Sua fila de notificação contém apenas elementos recentes ou também desatualizados?
> 
> Cumprimentos

Hello @cedric-anne 
On 02/11/2022, the date I opened this issue, it was the day the notification arrived referring to the dates 25612131 | 2021-10-19 22:13 | cron_closeticket | Closing date | Change from to 2021-10-19 22:13. This problem is recurring. I already checked the cron jobs. As well as the notification queue, which is cleaned weekly. That is, there are no outdated elements. I still haven't been able to resolve it. Can you help me?

Regards...

**Comment by cedric-anne** [comment]
The cron closes tickets that are already solved, based on the configured delay in the ticket entity. If the entity has a configured calendar, then the delay is computed based on working days of this calendar. First, you should check the ticket history to see if delay between solve date and close date seems relevant.

Secondly, you should check queueing date (`create_time`), sending attempt date (`send_time`) and effective sending date (`sent_time`) of the notification. You will find these dates in `glpi_queuednotifications` table. Mail sending may fail, and, in this case, GLPI will retry later. You may find logs about this in `files/_logs/mail-error.log`.

**Comment by carlosbayerl** [comment]
Hello @cedric-anne 
Thank you for your effort. However, I did the checks you gave me, and there was nothing that would cause this notification to be sent late. Is there any other procedure you can give me?
Regards...

**Comment by cedric-anne** [comment]
Maybe there is no bug and you just miss something, by I cannot confirm or disprove this as I do not even know what is the state of the processed data.

I guess I cannot help anymore.
