### ISSUE TITLE
Compute incorrect root_doc

### ISSUE THREAD

**Issue by robsonrosilva** [glpi-project/glpi#10614]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Good night, after much searching found a problem in the root_doc calculation on my server.
When I upload glpi on my server the calculated root_doc is never correct, I identified that it is because of the logic in the inc/config.class.php file.

before finding the directory of glpi($glpidir) the call "chdir(GLPI_ROOT);" it returns the disk in uppercase and when it calculates glpidir the path is wrong.

I solved it locally by changing str_replace to str_ireplace.
![image](https://user-images.githubusercontent.com/26228097/153699816-3dab7b0c-ace1-4fcf-9ac6-a26921b09dab.png)

**Comment by trasher** [comment]
Hi,
Could you please open a pull request with your changes? Thanks :)

**Comment by cedric-anne** [comment]
Not sure that using a case insensitive logic is a good thing, as filesystem may be case sensitive in most context. The best way to fix this would propably to use `realpath()` function on `getcwd()` results in order to normalize paths.

**Comment by robsonrosilva** [comment]
as here windows is complicated for me to evaluate the impacts on systems like linux, so what i did was a palliative to correct my problem in a timely manner, i believe it is something that should be corrected.
I don't understand why after calling the shdir function the variable $currentdir is changed so that the unit is capitalized. I see that could be a problem with her.

**Comment by cedric-anne** [comment]
Hi,

Can you check if #11085 fixes your issue ?
