### ISSUE TITLE
Ticket does not inheritate user's entity

### ISSUE THREAD

**Issue by tksadmin** [glpi-project/glpi#10620]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10.0.0-rc1] 

### Bug description

When a user create a new ticket, the ticket is created with the default entity instead of user's entity

Apparently, on ticket creation, final $_POST variable used as argument to CommonDBTM->add function does not contain the entity id.
Adding 

`$_POST['entities_id'] = $_SESSION['glpiactive_entity'];`

before line 71 in tracking.injector.php seems to fix the issue, but I don't know if this is the correct way.

### Steps To reproduce

Create a new entity [test]
Create a new user test.user and assign [test] entity to it as default entity. 
_test.user has self service authorization._
Log in the helpdesk as test.user and create a new ticket.
Ticket is correctly created but with wrong entity.
User cannot see his newly created ticket.

**Comment by flegastelois** [comment]
Fixed by https://github.com/glpi-project/glpi/pull/10550
