### ISSUE TITLE
Permit to lock palettes for user preferences

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1062]
The user can change the palette which adminstrator has defined. 

It's a good idea to lock this feature for the anothers users

see http://glpi.userecho.com/topics/74-permit-to-lock-palettes-for-user-preferences/#comment-631

**Comment by trasher** [comment]
Done in https://github.com/glpi-project/glpi/pull/4784 but for the whole personalization tab, not only one parameter in.
