### ISSUE TITLE
glpi 9.5.6 Network devices -> Serial number -> display  inf

### ISSUE THREAD

**Issue by jjk334** [glpi-project/glpi#10626]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

![image](https://user-images.githubusercontent.com/77146761/153848160-34d6eb2d-bd44-45fd-b6d0-f84a029ddb48.png)
![image](https://user-images.githubusercontent.com/77146761/153848259-9f06acf6-8e3a-49e2-9ebf-e0d2d8009210.png)

I fill in SN 210235276810E3000046 in the network device
display inf

**Comment by cedric-anne** [comment]
Hi,

Please try with GLPI 9.5.7.

**Comment by jjk334** [comment]
ok thanks
