### ISSUE TITLE
Collector Folder problem

### ISSUE THREAD

**Issue by DeusRulez** [glpi-project/glpi#10648]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

[GLPI 10.0.0-rc1]

### Bug description

Want to collect IMAP folder.
I select folder in collector configuration

### Relevant log output

```shell
Une erreur est survenue en essayer de se connecter au collecteur.
cannot change folder, maybe it does not exist

For the same reason they are not sent to the other folder when accepted or failed
```

### Steps To reproduce

Chaîne de connexion | {xxxx.:993/imap/ssl}INBOX/test

### Your GLPI setup information

Operating system: Linux servicett 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 PHP 7.4.25 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bz2, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="16M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: nginx/1.18.0 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43 Server Software: Debian 11 	Server Version: 10.5.12-MariaDB-0+deb11u1 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: supfai@localhost/supfai 	Host info: Localhost via UNIX socket 	 PHP version (7.4.25) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. Database engine version (10.5.12) is supported. The log file has been created successfully. Write access to /var/www/html/glpitt/supfai/files/_cache has been validated. Write access to /var/www/html/glpitt/supfai/config has been validated. Write access to /var/www/html/glpitt/supfai/files/_cron has been validated. Write access to /var/www/html/glpitt/supfai/files has been validated. Write access to /var/www/html/glpitt/supfai/files/_dumps has been validated. Write access to /var/www/html/glpitt/supfai/files/_graphs has been validated. Write access to /var/www/html/glpitt/supfai/files/_lock has been validated. Write access to /var/www/html/glpitt/supfai/files/_pictures has been validated. Write access to /var/www/html/glpitt/supfai/files/_plugins has been validated. Write access to /var/www/html/glpitt/supfai/files/_rss has been validated. Write access to /var/www/html/glpitt/supfai/files/_sessions has been validated. Write access to /var/www/html/glpitt/supfai/files/_tmp has been validated. Write access to /var/www/html/glpitt/supfai/files/_uploads has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/supfai/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/glpitt/supfai/marketplace has been validated. Access to timezone database (mysql) is not allowed.
--

GLPI_ROOT: /var/www/html/glpitt/supfai GLPI_CONFIG_DIR: /var/www/html/glpitt/supfai/config GLPI_VAR_DIR: /var/www/html/glpitt/supfai/files GLPI_MARKETPLACE_DIR: /var/www/html/glpitt/supfai/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: /var/www/html/glpitt/supfai/files GLPI_CACHE_DIR: /var/www/html/glpitt/supfai/files/_cache GLPI_CRON_DIR: /var/www/html/glpitt/supfai/files/_cron GLPI_DUMP_DIR: /var/www/html/glpitt/supfai/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpitt/supfai/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpitt/supfai/files/_locales GLPI_LOCK_DIR: /var/www/html/glpitt/supfai/files/_lock GLPI_LOG_DIR: /var/www/html/glpitt/supfai/files/_log GLPI_PICTURE_DIR: /var/www/html/glpitt/supfai/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpitt/supfai/files/_plugins GLPI_RSS_DIR: /var/www/html/glpitt/supfai/files/_rss GLPI_SESSION_DIR: /var/www/html/glpitt/supfai/files/_sessions GLPI_TMP_DIR: /var/www/html/glpitt/supfai/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpitt/supfai/files/_uploads GLPI_INVENTORY_DIR: /var/www/html/glpitt/supfai/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpitt/supfai/locales GLPI_VERSION: 10.0.0-rc1 GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3 GLPI_MARKETPLACE_PRERELEASES: 1 GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpitt/supfai/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.5.3 in (/var/www/html/glpitt/supfai/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/var/www/html/glpitt/supfai/vendor/simplepie/simplepie/library) mpdf/mpdf in (/var/www/html/glpitt/supfai/vendor/mpdf/mpdf/src) michelf/php-markdown in (/var/www/html/glpitt/supfai/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpitt/supfai/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpitt/supfai/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpitt/supfai/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpitt/supfai/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpitt/supfai/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpitt/supfai/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/var/www/html/glpitt/supfai/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/var/www/html/glpitt/supfai/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/var/www/html/glpitt/supfai/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpitt/supfai/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/var/www/html/glpitt/supfai/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/var/www/html/glpitt/supfai/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpitt/supfai/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpitt/supfai/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpitt/supfai/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpitt/supfai/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpitt/supfai/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpitt/supfai/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpitt/supfai/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpitt/supfai/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpitt/supfai/vendor/psr/simple-cache/src) psr/cache in (/var/www/html/glpitt/supfai/vendor/psr/cache/src) league/csv in (/var/www/html/glpitt/supfai/vendor/league/csv/src) mexitek/phpcolors in (/var/www/html/glpitt/supfai/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpitt/supfai/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpitt/supfai/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/var/www/html/glpitt/supfai/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/var/www/html/glpitt/supfai/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpitt/supfai/vendor/paragonie/sodium_compat/src) symfony/cache in (/var/www/html/glpitt/supfai/vendor/symfony/cache) html2text/html2text in (/var/www/html/glpitt/supfai/vendor/html2text/html2text/src) symfony/dom-crawler in (/var/www/html/glpitt/supfai/vendor/symfony/dom-crawler) twig/twig in (/var/www/html/glpitt/supfai/vendor/twig/twig/src) twig/string-extra in (/var/www/html/glpitt/supfai/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 in (/var/www/html/glpitt/supfai/vendor/symfony/polyfill-php80)

**Comment by cedric-anne** [comment]
Hi,

Please give more details about steps to reproduce and add corresponding GLPI logs.

Regards

**Comment by cedric-anne** [comment]
I close this issue due to lack of feedback. Feel free to reopen.
