### ISSUE TITLE
Fresh install of 9.1 dies with an error for new databases

### ISSUE THREAD

**Issue by fpoirotte** [glpi-project/glpi#1065]
Dear GLPI developers,

While doing a fresh install of GLPI 9.1, the following error was encountered:
```Fatal error: Call to undefined method Toolbox::createMainConfig() in /usr/share/glpi/install/install.php on line 421```

(Note: I had to remove the call to error_reporting() from install/install.php to actually see the error).

This happened on CentOS 7.2 (PHP 5.4) while selecting the "Install" mode and asking GLPI to create a new database.

Strangely enough, after PHP dies on that error, if I start the installation process again, I see the database has actually been created. Now if I select that database and ask GLPI to overwrite it, the installation finishes successfully and I'm presented with the usual link to access the new installation.

Regards,
François

**Comment by trasher** [comment]
Indeed, there is a mistake here. I guess you should just replace `Toolbox` with `DBConnection` on the faulty line.

**Comment by remicollet** [comment]
Fix by pr #1067
