### ISSUE TITLE
Migration to 9.1 : Database problem

### ISSUE THREAD

**Issue by Ennouchy-Actemium** [glpi-project/glpi#1066]
I encountered an error when trying to update from a 0.90.5 installation to a 9.1.
A SQL error happened when migrating slas to slts.

I had an sla titled 'Maintenance d'urgence'. It seems the ' character was the faulty one.
I updated the name in the _glpi_slas_ table via a sql request to remove the ' character. And I have been able to pursue the migration process to completion without any further error.

**Comment by trasher** [comment]
As far as I can see, the issue has been fixed. I close the ticket, feel free to reopen.
