### ISSUE TITLE
External calendar permission is only set to read, however user can add external calendars in planning.

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10667]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0 beta

### Bug description

External calendar permission is only set to read, however user can add external calendars.

![Screenshot_20220216_000353](https://user-images.githubusercontent.com/63743077/154166904-83166640-aea5-468d-950d-9fc8da4fd264.png)
![Screenshot_20220216_000438](https://user-images.githubusercontent.com/63743077/154166906-e0331c4b-8027-4aa1-be3a-c5417645c192.png)

> 

### Steps To reproduce

1°set planning permission : view my personal planning
2°set external event view to read 
3°click on the button to add an external calendar from the planning view

### Your GLPI setup information

debian 4.19.208-1 (2021-09-29) x86_64
PHP 7.4.27

**Comment by cedric-anne** [comment]
#10667 should fix the issue.

During my checks, I an "Invalid rights" error was displayed instead of the form, so I guess some rights checks were already added since beta version.
