### ISSUE TITLE
PHP User Warning (512): getFromDBByCrit expects to get one result, n found in query

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#10669]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

My guesses:

When mailgate collect an email, and there is no "synchronization field" configured in the LDAP or the field was configured after a user was already created but never updated since, it tries to use that field even if the value is NULL.
If there is more than one user in this case this warning get added to php-errors:

```
[2022-02-16 09:17:02] glpiphplog.WARNING:   *** PHP User Warning (512): getFromDBByCrit expects to get one result, 13 found in query "SELECT `id` FROM `glpi_users` WHERE `sync_field` IS NULL". in E:\GLPI\src\CommonDBTM.php at line 365
  Backtrace :
  src\CommonDBTM.php:365                             trigger_error()
  src\User.php:485                                   CommonDBTM->getFromDBByCrit()
  src\AuthLDAP.php:2789                              User->getFromDBbySyncField()
  src\User.php:4965                                  AuthLDAP::ldapImportUserByServerId()
  src\MailCollector.php:1067                         User::getOrImportByEmail()
  src\MailCollector.php:759                          MailCollector->buildTicket()
  src\MailCollector.php:1821                         MailCollector->collect()
  src\CronTask.php:1016                              MailCollector::cronMailgate()
  front\cron.php:82                                  CronTask::launch()
```

This seems to be a PHP User Warning so I guess the case is handled partially in the code (handle dupplicate in synchronization field).
Maybe we should add a special case to handle "NULL" values.

### Relevant log output

```shell
[2022-02-16 09:17:02] glpiphplog.WARNING:   *** PHP User Warning (512): getFromDBByCrit expects to get one result, 13 found in query "SELECT `id` FROM `glpi_users` WHERE `sync_field` IS NULL". in E:\GLPI\src\CommonDBTM.php at line 365
  Backtrace :
  src\CommonDBTM.php:365                             trigger_error()
  src\User.php:485                                   CommonDBTM->getFromDBByCrit()
  src\AuthLDAP.php:2789                              User->getFromDBbySyncField()
  src\User.php:4965                                  AuthLDAP::ldapImportUserByServerId()
  src\MailCollector.php:1067                         User::getOrImportByEmail()
  src\MailCollector.php:759                          MailCollector->buildTicket()
  src\MailCollector.php:1821                         MailCollector->collect()
  src\CronTask.php:1016                              MailCollector::cronMailgate()
  front\cron.php:82                                  CronTask::launch()
```

### Page URL

src/cron.php

### Steps To reproduce

I don't know exactly how to reproduce it, but I guess you can by having some users without synchronization field set during a mail collect.

### Your GLPI setup information

Operating system: Windows NT SRVGLPI10 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.2 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="2048M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2048M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.87 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.5-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.2) is supported.PHP version (8.1.2) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
Database engine version (10.6.5) is supported.Database engine version (10.6.5) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to E:\GLPI/files/_cache has been validated. Write access to E:\GLPI/config has been validated. Write access to E:\GLPI/files/_cron has been validated. Write access to E:\GLPI/files has been validated. Write access to E:\GLPI/files/_dumps has been validated. Write access to E:\GLPI/files/_graphs has been validated. Write access to E:\GLPI/files/_lock has been validated. Write access to E:\GLPI/files/_pictures has been validated. Write access to E:\GLPI/files/_plugins has been validated. Write access to E:\GLPI/files/_rss has been validated. Write access to E:\GLPI/files/_sessions has been validated. Write access to E:\GLPI/files/_tmp has been validated. Write access to E:\GLPI/files/_uploads has been validated.Write access to E:\GLPI/files/_cache has been validated.
Write access to E:\GLPI/config has been validated.
Write access to E:\GLPI/files/_cron has been validated.
Write access to E:\GLPI/files has been validated.
Write access to E:\GLPI/files/_dumps has been validated.
Write access to E:\GLPI/files/_graphs has been validated.
Write access to E:\GLPI/files/_lock has been validated.
Write access to E:\GLPI/files/_pictures has been validated.
Write access to E:\GLPI/files/_plugins has been validated.
Write access to E:\GLPI/files/_rss has been validated.
Write access to E:\GLPI/files/_sessions has been validated.
Write access to E:\GLPI/files/_tmp has been validated.
Write access to E:\GLPI/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to E:\GLPI/marketplace has been validated.Write access to E:\GLPI/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment]
Hi,

It may be fixed by #10670, but I do not really know the LDAP part of GLPI, so you should check twice.

Regards
