### ISSUE TITLE
[GLPI 10.0-RC1] Mini Dashboard no longer shows up in tickets

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10663]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0-RC1

### Bug description

In my preferences I no longer see the mini dashboard menu. On my production version GLPI 9.5.7, the mini dashboard displays fine

9.5.7 the menu mini tableau de bord ok
![image](https://user-images.githubusercontent.com/68054991/152989669-98c21ae3-be9c-4e05-95e1-0028b03887c6.png)

10.0 RC1 mini tableau de bord doesnt exist
![image](https://user-images.githubusercontent.com/68054991/152989814-d3bef9d4-c2f1-4d62-a3d1-2ae1e5389c26.png)

Dashboard tickets : 
9.5.7
![image](https://user-images.githubusercontent.com/68054991/152990262-b9da14e3-7d46-4661-823f-b9ae7817880e.png)

10.0 RC1 nothing
![image](https://user-images.githubusercontent.com/68054991/152990319-b26ab927-68dd-47e4-b69d-3422315302b2.png)

### Relevant log output

```shell

```

### Page URL

/front/ticket.php

### Steps To reproduce
1. Ticket shows

_No response_

**Comment by cconard96** [comment]
Fixed via #10771
