### ISSUE TITLE
Permission issue : inventory menu still visible for user when disabled in profile

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10666]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 beta

### Bug description

Hi,
Permissions are disabled for inventory but it still shows up; using the standard interface; if I click on inventory it says "permission denied" however the icon could be hidden.

![Screenshot_20220216_000310](https://user-images.githubusercontent.com/63743077/154165588-55fd0b0b-1b73-458
![Screenshot_20220216_001547](https://user-images.githubusercontent.com/63743077/154165950-6ab53497-d4b2-43ed-8a21-9120b22ff5ce.png)
d-bfc6-beb962ae7a96.png)
p

### Steps To reproduce

1° disable all permissions for inventory and rss feeds
2° check that the menus to access it is still visible

### Your GLPI setup information

debian 4.19.208-1 (2021-09-29) x86_64
PHP 7.4.27

**Comment by cconard96** [comment]
I wasn't able to recreate the issue. The visibility of this menu item seems dependent on the Update permission for the `config`.

**Comment by joomlafun** [comment]
Hi,
Thank you for your time Curtis.

To reproduce : please create a new glpi profile which has access to the standard interface and does not have any permission.(all the inventory and administration permissions are empty but it still shows)

**Comment by cconard96** [comment]
![Screenshot from 2022-02-19 08-43-18](https://user-images.githubusercontent.com/17678637/154803321-98664bc5-a6df-42da-b08f-015166bd39dd.png)

A blank profile with standard interface for me shows only personal reminders, personal RSS feeds, and then one of my plugins that is visible to anyone in debug mode.

Please note that I tested on the latest GLPI 10/master branch. There may have been changes between the version you were testing and the latest.

**Comment by joomlafun** [comment]
Ok then the bug is on my side. So let's close this. Thanks for your check !
