### ISSUE TITLE
Problem with netdiscovery and netinventory tasks of Unifi Acces Points

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#10678]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Glpi-agent crashed after net discovery and net invenory of Unifi Acces Points.
[UNIFI_PROBLEMS_XML.ZIP](https://github.com/glpi-project/glpi-agent/files/8051613/UNIFI_PROBLEMS_XML.ZIP)
[XML.ZIP](https://github.com/glpi-project/glpi-agent/files/8051713/XML.ZIP)

Sorry I had to reset the ip and mac addresses because they contain sensitive data.

### To reproduce

Scan ip range withUnifi APs.

### Expected behavior

)

### Operating system

Linux

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

10.0.0-rc1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc4

### Additional context

GLPI-Agent v1.2-git73986331 nightly build

**Comment by leruetkins** [comment]
Ok, I will try reproduce it again.

**Comment by leruetkins** [comment]
This is newest log. I started SNMP inventory from glpi inventory plugin.
[php-errors.log](https://github.com/glpi-project/glpi/files/8081079/php-errors.log)

**Comment by cedric-anne** [comment]
Hi,

Can you try to reproduce on GLPI 10.0.0-rc3 ?

**Comment by g-bougard** [comment]
I just tried some XML from the XML.ZIP file, but after having updated them with some coherent datas regarding IP and MAC address. I imported them without any issue with GLPI 10.0.0-rc3 + GlpiInventory plugin 1.0.0-rc7.

@leruetkins If you're reproducing your issue, can you provide few new XMLs again ? But this without corrupting them (`000.000.000.000` is not a valid ip and `00:00:00:00:00:00` everywhere as MAC address is just wrong, just change few numbers to obfuscate sensible datas). Also, be sure to reproduce again the problem by trying to inject yourself the generated XMLs.

**Comment by leruetkins** [comment]
Hi

Now it works! Thanks a lot! :)

**Comment by JuanMoroteP** [comment]
> I just tried some XML from the XML.ZIP file, but after having updated them with some coherent datas regarding IP and MAC address. I imported them without any issue with GLPI 10.0.0-rc3 + GlpiInventory plugin 1.0.0-rc7.
> 
> @leruetkins If you're reproducing your issue, can you provide few new XMLs again ? But this without corrupting them (`000.000.000.000` is not a valid ip and `00:00:00:00:00:00` everywhere as MAC address is just wrong, just change few numbers to obfuscate sensible datas). Also, be sure to reproduce again the problem by trying to inject yourself the generated XMLs.



> Hi
> 
> Now it works! Thanks a lot! :)

Same for me. I was trying to import xml files from a d-link switch and it didn't work with glpi-agentv1.2 but with glpi-agentv1.0 it worked fine!!
Thanks!!!

**Comment by rbrannath** [comment]
Hi, I have the same issue (v.1.2 and current 1.3-nightly.
I am using glpi-agent on Windows 10. After successfully generating xml-files with glpi-inventory, I am using glpi-injector to upload the files onto my glpi server.

This is the output of the glpi-injector command:
```
ERROR: Unexpected empty server response
C:\Users\myuser\Documents\glpi\netinventory/192.168.0.20.xml
```

Quite interesting is, this problem occurs only for my access points.
The xml of my switch is uploaded smoothly (same manufacturer)

I have done some testing and the <component></component> property is causing most likely the issue here.
If there is only one component, the injection is failing. If there is a second (or more) components, even a dummy, it is getting injected flawlessly.

I suspect this is a server side issue. I am on GLPI v10.0.0 right now using only native inventory (no plugins)

Best regards

**Comment by trasher** [comment]
Please do not comment on closed issues, open a new one.

And as we always ask, provide logs and an inventory file we can use to reproduce.
