### ISSUE TITLE
Problem with profiles

### ISSUE THREAD

**Issue by ashmonger** [glpi-project/glpi#1068]
> Setup:
> GLPI 9.1
> mysql  Ver 14.14 Distrib 5.5.50
> Description:    Ubuntu 14.04.5 LTS

Problem:
I've got some users whose authenticate with LDAP/AD, and each time they log in, a new "glpi_profiles_users" line is created with the default profile, which is set as dynamic and not recursive.

```
mysql> select * from glpi_profiles_users where users_id = 22;
+----+----------+-------------+-------------+--------------+------------+
| id | users_id | profiles_id | entities_id | is_recursive | is_dynamic |
+----+----------+-------------+-------------+--------------+------------+
| 42 |       22 |          10 |           0 |            1 |          0 |
| 57 |       22 |          10 |           0 |            0 |          1 |
+----+----------+-------------+-------------+--------------+------------+
```

Maybe I am doing something wrong with the setup, or there is something fishy.

**Comment by ashmonger** [comment]
It seems to be a problem with the rules.
I have to create a specific rules to assign recursivity to LDAP/AD profile.
The big question is "why?" do I have to make a rules that will apply everytime, after I set a proper profile to each users.

**Comment by trasher** [comment]
This is not a bug; use forums for help on usage
