### ISSUE TITLE
[GLPI 10] Display Items menu without rights

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#10686]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

Profile self-service : 
No rights for inventory
![image](https://user-images.githubusercontent.com/13178158/154437648-bd1cfa40-d0a5-4adc-9a96-4c331b3bee64.png)

In a existant ticket, the menu still appears : 
![image](https://user-images.githubusercontent.com/13178158/154437892-8777a051-cfa2-4011-aed2-d4f2129b9bd1.png)

### Page URL

http://localhost/glpi/front/ticket.form.php?id=X

**Comment by ZalemCitizen** [comment]
Hi,
Same error here, and for "Technician" field too.

**Comment by cconard96** [comment]
> Hi, Same error here, and for "Technician" field too.

Can you open a new issue for the other field/issue?
