### ISSUE TITLE
slowdown issue with offline installation

### ISSUE THREAD

**Issue by Demonheart** [glpi-project/glpi#10697]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

Hello,

I have installed GLPI on my offline server but i have major slowdown issues.
I notice that in my browser the server try to join google.fontapis.com and spend some time on it
![font](https://user-images.githubusercontent.com/1001730/154656949-33038ea8-5a78-49b0-a623-912bbc0d37ab.jpg)
t

### Steps To reproduce

1. On any page of GLPI

### Your GLPI setup information

Offline Install
Local database

**Comment by cedric-anne** [comment]
Hi,

#10698 should fix this issue.

Regards

**Comment by cedric-anne** [comment]
As changes are requiring a rebuild of compiled CSS, a patch is not enough to see results.
Here you can download a build of the PR branch, if you want to test it: https://github.com/cedric-anne/glpi/suites/5361081633/artifacts/167992658

**Comment by Demonheart** [comment]
> As changes are requiring a rebuild of compiled CSS, a patch is not enough to see results. Here you can download a build of the PR branch, if you want to test it: https://github.com/cedric-anne/glpi/suites/5361081633/artifacts/167992658

Thanks it works now !
