### ISSUE TITLE
[GLPI 10.0 RC1] Question about computer image model display : _pictures

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10705]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

### Bug description

On my personal computers, I added the images of the computer models.

On versions 9.5.7 and 10.0, image files are stored in the _pictures folder. I realized when I migrated to the glpi 10.0 test version, I no longer had the images of the computer models

In the folder _picture there is a remove.txt file and saying it is a temporary folder and one can delete it.

Is it possible during a future migration from version 10 to change location ?

images on the folder _pictures
![image](https://user-images.githubusercontent.com/68054991/154710260-20cf9e6e-9173-4820-8a20-1e8cb2220ff0.png)

### Page URL

/front/computer.form.php?id=xxx

**Comment by cedric-anne** [comment]
You misunderstood the file content. Indeed, the `remove.txt` file says `You can safely remove this file.` which is different from saying that the whole directory is a temporary one.

I guess this file has been added to ensure that the directory persist in code repository (i.e. git does not save empty directories).

I close this as it is not an issue.

**Comment by steph461** [comment]
thx for information
