### ISSUE TITLE
watcher field half cut simply template 

### ISSUE THREAD

**Issue by jfumanat** [glpi-project/glpi#10712]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 RC1

### Bug description

Hello

I have created a ticket template, in the simple form I have 6 fields, one of them is observer, this field when added makes the form show only half of the options, if I hide that field the form is show complete.

This did not happen in version 9.5

The other can make the forms editable separately since any change affects both and in my case I need the full form to have fields that the simple one doesn't, but currently what you do in one affects the other.

Thank you for this wonderful tool, I have been using it for two years now and it is spectacular. I hope to be able to contribute as much as possible to make it better and better.

### Page URL

http://localhost/glpi/front/tickettemplate.form.php?id=16

### Steps To reproduce

1. enable whatcher in template
2. when activated the simple form is cut in half 
3. if the field is hidden the form is displayed fine

### Your GLPI setup information

 GLPI 10.0.0-rc1 (/glpi => /usr/share/glpi)
 Installation mode: RPM
 Current language:en_GB

 
Operating system: Linux cobogslnxs01.crepes.ofi 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 PHP 8.1.3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sodium, 	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="0" memory_limit="1000M" post_max_size="32M" safe_mode="" session.save_handler="files" 	upload_max_filesize="5M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/8.1.3 mod_perl/2.0.11 Perl/v5.16.3 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.105 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.2.43-MariaDB 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version (8.1.3) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. Database engine version (10.2.43) is supported. The log file has been created successfully. Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated. For security reasons, SELinux mode should be Enforcing. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /usr/share/glpi/marketplace has been validated. Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

GLPI_ROOT: /usr/share/glpi GLPI_CONFIG_DIR: /etc/glpi GLPI_VAR_DIR: /var/lib/glpi/files GLPI_LOG_DIR: /var/log/glpi GLPI_HTMLAWED: /usr/share/php/htmLawed/htmLawed.php GLPI_FONT_FREESANS: /usr/share/fonts/gnu-free/FreeSans.ttf GLPI_SYSTEM_CRON: 1 GLPI_INSTALL_MODE: RPM GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: /var/lib/glpi/files GLPI_CACHE_DIR: /var/lib/glpi/files/_cache GLPI_CRON_DIR: /var/lib/glpi/files/_cron GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales GLPI_LOCK_DIR: /var/lib/glpi/files/_lock GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins GLPI_RSS_DIR: /var/lib/glpi/files/_rss GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions GLPI_TMP_DIR: /var/lib/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads GLPI_INVENTORY_DIR: /var/lib/glpi/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/share/glpi/locales GLPI_VERSION: 10.0.0-rc1 GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3 GLPI_MARKETPLACE_PRERELEASES: 1 GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.2.0 GLPI_YEAR: 2022

 htmlawed/htmlawed version 1.2.6 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.5.3 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library) mpdf/mpdf in (/usr/share/glpi/vendor/mpdf/mpdf/src) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) psr/cache in (/usr/share/glpi/vendor/psr/cache/src) league/csv in (/usr/share/glpi/vendor/league/csv/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src) symfony/cache in (/usr/share/glpi/vendor/symfony/cache) html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src) symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler) twig/twig in (/usr/share/glpi/vendor/twig/twig/src) twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found phpCas version 1.4.0 in (/usr/share/pear)

Server: '192.168.181.3', Port: '389', BaseDN: 'DC=crepes,DC=ofi', Connection filter: 		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=Servicios Tecnologia 		C&W,OU=Tecnologia,OU=01-BOG,OU=03-SRV,DC=crepes,DC=ofi', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (crepero@crepesywaffles.com@smtp.office365.com)
 
Name: 'crepero@crepesywaffles.com' Active: Yes 	Server: '{outlook.office365.com:995/pop/ssl/novalidate-cert/notls}' Login: 'crepero@crepesywaffles.com' Password: Yes Name: 'wafflero@crepesywaffles.com' Active: Yes 	Server: '{outlook.office365.com:995/pop/ssl/novalidate-cert/notls}' Login: 'wafflero@crepesywaffles.com' Password: Yes
 
fields               Name: Additionnal fields             Version: 1.13.0-rc2 State: Enabled 	tag                  Name: Administración de etiquetas    Version: 2.9.0-rc3  State: Not installed 	camerainput          Name: Camera Input                   Version: 2.0.0-beta1 State: Enabled 	datainjection        Name: Data injection                 Version: 2.10.0-rc2 State: Enabled 	escalade             Name: Escalation                     Version: 2.8.0-rc2  State: Enabled 	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3 State: Not installed 	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc4  State: Installed / not activated 	geninventorynumber   Name: Inventory number generation    Version: 2.6.0-rc2  State: Enabled 	timelineticket       Name: Línea de tiempo de los tickets Version: 10.0+1.0-rc1 State: Enabled 	genericobject        Name: Objects management             Version: 2.12.0-rc2 State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.0-rc1  State: Enabled 	screenshot           Name: Screenshot                     Version: 2.0.0-beta1 State: Not installed 	dashboard            Name: Tablero de informes            Version: 1.0.2      State: Enabled 	typology             Name: Tipologías                     Version: 3.0.0-rc1  State: Not installed 	useditemsexport      Name: Used items export              Version: 2.5.0-rc2  State: Enabled

**Comment by cconard96** [comment]
I cannot recreate the issue, but there have been fixes for this form since the RC1 release. Please try testing it with the latest nightly "master" release.

https://nightly.glpi-project.org/glpi/

If it still doesn't work, can you check if there are any errors logged in `files/_log/php-errors.log`?

**Comment by cedric-anne** [comment]
I close this issue due to lack of feedback. Feel free to reopen.
