### ISSUE TITLE
Actor added by rule systematically removed

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#10718]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10 Nightly

### Bug description

Actor added by rule systematically removed

### Steps To reproduce

1. create rule that added actor when category is updated (for exemple)
2. create ticket
3. change category
4. update ticket
5. see in history
![image](https://user-images.githubusercontent.com/7335054/154931812-4848eb8d-4a89-4916-b12c-2a24a1daa2c8.png)

Actor is added the removed

### Anything else?

[Bug introduced here](https://github.com/glpi-project/glpi/blob/3f478a37e1c157bac5c4503ca5d622bc4474e083/src/CommonITILObject.php#L7760)

**Comment by cconard96** [comment]
Initially fixed by #10852. The related code was refactored in #10950.
