### ISSUE TITLE
Violation of access rights to the FAQ

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#10746]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-rc1

### Bug description

Hello. 
 I created a user with profile USERS and placed him in the Users group. I have opened the possibility for users to read the FAQ.
Next, I created an Instruction with secret logins and passwords in the FAQ and gave access only to a group of System administrators.
So, the user does not have access to this instruction via a direct link, which is correct, but he can see a list of documents to which there is no access, as well as a preview of this instruction, where all logins and passwords will be visible, and this is not correct.
![Screenshot_248](https://user-images.githubusercontent.com/15270519/155123424-59164229-3de4-4acb-80d5-a91c44ff0dbc.png)
![Screenshot_249](https://user-images.githubusercontent.com/15270519/155123420-65f71351-a62b-4b8f-a0a4-181af2a40d53.png)

### Page URL

http://my.server/glpi/front/helpdesk.faq.php

**Comment by cconard96** [comment]
FAQ articles are public to everyone with access to the FAQ. For more specific restrictions, you need to take it out of the FAQ.

**Comment by cconard96** [comment]
My original comment was saying that FAQ articles were public and didn't use the visibility restrictions as that is what I noticed before. I was going to link the user documentation and found that it wasn't clear about that behavior. I retracted my comment until I could confirm the intended behavior.

This may be a bug or at least something that needs clarified in the documentation.

**Comment by cconard96** [comment]
The documentation for this has been improved.
