### ISSUE TITLE
API show  ERROR_APP_TOKEN_PARAMETERS_MISSING GLPI 9.1 RC2

### ISSUE THREAD

**Issue by luanpcweb** [glpi-project/glpi#1074]
Hello,

I have a problem when I try to access the API, even following the supplied manual.

This error is returned:

"ERROR_APP_TOKEN_PARAMETERS_MISSING"
"Missing the app_token parameter, see documentation in your browser http://tm.trulysystems.com/api/#ERROR_APP_TOKEN_PARAMETERS_MISSING"

curl -X GET \
-H 'Content-Type: application / json' \
-H "Authorization: Basic Z2xwaTpnbHBp" \
-H "App-Token: f7g34sp8mgatg5ebc5elnazakw20i9fyev1qopya7" \
'Http: //myhost/glpi/apirest.php/initSession'

glpi version 9.1 RC2

My Serv: 

PHP 5.6.26 cgi-fcgi (Core, OAuth, PDFlib, PDO, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, ereg, exif, fileinfo, filter, ftp, gd, gender, geoip, gettext, gmp, hash, iconv, imagick, imap, json, ldap, libxml,
	mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, pgsql, posix, pspell, readline, redis,
	session, shmop, snmp, soap, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, yaz, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="256M" 
Software: Apache ()
	Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.5.52-cll
	Server SQL Mode: 
	Parameters: trulysys_hds@localhost/trulysys_hds
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
Could you please try again with final 9.1?

**Comment by luanpcweb** [comment]
Tank you. I tried and it worked. :)  Tank you again
