### ISSUE TITLE
Unable to create new Models

### ISSUE THREAD

**Issue by j-mazzie** [glpi-project/glpi#10753]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0-rc1

### Bug description

When trying to create new models for devices, computers, printers, phones, etc an error prompts

### Relevant log output

```shell
Twig Error (Twig\Error\RuntimeError): "The merge filter only works with arrays or "Traversable", got "NULL" as first argument." in template "E:\xampp\htdocs\glpi\templates\dropdown_form.html.twig" at line 235
```

### Page URL

https://localhost/glpi/front/printermodel.form.php

### Steps To reproduce

1. Goto Dropdowns
2. Click dropdown for models
3. Select any model type
4. click Add

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.0-rc1 (/glpi => E:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT TSLGLPI 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2 (Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.1.2 Server at tslglpi Port
	443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.2) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.4.22) is supported.
The log file has been created successfully.
Write access to E:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to E:\xampp\htdocs\glpi/config has been validated.
Write access to E:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to E:\xampp\htdocs\glpi/files has been validated.
Write access to E:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to E:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to E:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to E:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to E:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to E:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to E:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to E:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to E:\xampp\htdocs\glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to E:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: E:\xampp\htdocs\glpi
GLPI_CONFIG_DIR: E:\xampp\htdocs\glpi/config
GLPI_VAR_DIR: E:\xampp\htdocs\glpi/files
GLPI_MARKETPLACE_DIR: E:\xampp\htdocs\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: E:\xampp\htdocs\glpi/files
GLPI_CACHE_DIR: E:\xampp\htdocs\glpi/files/_cache
GLPI_CRON_DIR: E:\xampp\htdocs\glpi/files/_cron
GLPI_DUMP_DIR: E:\xampp\htdocs\glpi/files/_dumps
GLPI_GRAPH_DIR: E:\xampp\htdocs\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: E:\xampp\htdocs\glpi/files/_locales
GLPI_LOCK_DIR: E:\xampp\htdocs\glpi/files/_lock
GLPI_LOG_DIR: E:\xampp\htdocs\glpi/files/_log
GLPI_PICTURE_DIR: E:\xampp\htdocs\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: E:\xampp\htdocs\glpi/files/_plugins
GLPI_RSS_DIR: E:\xampp\htdocs\glpi/files/_rss
GLPI_SESSION_DIR: E:\xampp\htdocs\glpi/files/_sessions
GLPI_TMP_DIR: E:\xampp\htdocs\glpi/files/_tmp
GLPI_UPLOAD_DIR: E:\xampp\htdocs\glpi/files/_uploads
GLPI_INVENTORY_DIR: E:\xampp\htdocs\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: E:\xampp\htdocs\glpi/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (E:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.5.4 in (E:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (E:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
mpdf/mpdf in (E:\xampp\htdocs\glpi\vendor\mpdf\mpdf\src)
michelf/php-markdown in (E:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (E:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (E:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (E:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (E:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (E:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (E:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (E:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (E:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (E:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (E:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (E:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (E:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (E:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (E:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (E:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (E:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (E:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (E:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (E:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (E:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (E:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (E:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (E:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (E:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (E:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (E:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (E:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (E:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (E:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (E:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (E:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/dom-crawler in (E:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (E:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (E:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (tickets@mail.smilelodge.com)

</details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.0-rc2  State: Enabled
	resources            Name: Human Resources                Version: 3.0.0-rc2  State: Not installed
	screenshot           Name: Screenshot                     Version: 2.0.0-beta1 State: Enabled

</pre></details>

**Comment by blackxthink** [comment]
This happens on the cloud version too (the trial).
Any actions to add a model, the popup / pages does not show the form

![image](https://user-images.githubusercontent.com/48074916/155207961-79205847-a6b2-4423-8d5b-f9413a765ebf.png)

**Comment by j-mazzie** [comment]
@blackxthink do you get the same error if you turn on debug mode?

**Comment by blackxthink** [comment]
> @blackxthink do you get the same error if you turn on debug mode?

Pretty much yes

![image](https://user-images.githubusercontent.com/48074916/155217373-baaf8523-d20f-4e2e-bf04-efdad9930171.png)

![image](https://user-images.githubusercontent.com/48074916/155217437-a552cb38-9125-4525-9761-b65f85f23153.png)

**Comment by j-mazzie** [comment]
This fixed the issue. Thanks!
