### ISSUE TITLE
Ticket Validation UX

### ISSUE THREAD

**Issue by AdrienClairembault** [glpi-project/glpi#10760]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

Master

### Bug description

Two issues with ticket validation UX:

![image](https://user-images.githubusercontent.com/42734840/155290266-a77746b6-609c-4632-b27d-ea052f760981.png)

1) The div containing the "Add" div seems to be overflowing on the left and right side.
2) The "Send approval request" button should disappear when this form is open (this button only "open" this form, to send the data you need to press the "Add" button. Having the two buttons displayed at the same time is confusing).

**Comment by cedric-anne** [comment]
Changed by #10913.
