### ISSUE TITLE
'Right' or 'Left' position for ticket items on timeline view

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1076]
Hello,
I would like to start a discussion about the rule which decides the position of the items (task, followups,...) on the timeline view.
### The current rule is:

> // check if curent item user is assignee or requester
> 
> > ```
> >   $user_position = 'left';
> >    if ((isset($ticket_users_keys[$item_i['users_id']])
> >          && ($ticket_users_keys[$item_i['users_id']] == CommonItilActor::ASSIGN))
> >         || ($item['type'] == 'Assign')) {
> >        $user_position = 'right';
> >    }
> > ```
> 
> if writer of the item (task, followup,...) is assigned to ticket (=ticket technician) then the position of the item will be on the right

Note: there is a condition `|| ($item['type'] == 'Assign')` which is strange to me as this value is never assigned to the array.
### Current rule problems
1. we may have technicians that write followups and they are not assigned to the ticket. They may belong to a group assigned to (or not).
2. the 'assigned to' may change during the ticket life, and so the timeline will no longer reflect the real exchanges between the requester and the technicians.
3. a watcher may write a followup. A watcher may be a technician or a requester. So where do we put the item written by a watcher, on the left or on the right? Today on the left.
4. a requester may also be a technician in a ticket, so where do we position the items? On the left or on the right?
### Proposed solutions:

Could we imagine that the position of the item is stored into the item itself in DB? Like this at creation, we may decide to set it on the left or the right depending on several rules:
1. Writer's default profile is 'Simplified interface' or not? But as this setting is not mandatory, we may have troubles!
2. Extended rights on this ticket (=read/write on most of the ticket fields) in one of writer's profiles
3. Based on a new field (='to requester': yes/no default no): when set to 'no' then item will be on the right. 
4. Instead of a new field, we may use the request source, and set a new flag in 'request source' dropdown to determine if it's from Technician or not.
5. Based also on the privacy flag: as only technicians can set followup and task as 'private'.
6. Based on the current (=at item creation) ticket assignments. At item (task, followup,...) creation is the writer also assigned to? then item will be set to the right. 
7. based on ticket business rules to be defined with the rule engine.
8. or any other ideas...
### Favourite solution:

And what about if we do the reverse? Instead of setting the position if the writer is 'assigned to', we may decide the position if the writer is 'requester' or 'observer'? In this case set it to the left. 
Of course we must do this at creation time and save this info into the DB (to prevent timeline changes during ticket life). 

Of course, we may combine several of these rules.

Thank you,
Regards,

Tomolimo

**Comment by orthagh** [comment]
for reference: https://snag.gy/kxU0aq.jpg

**Comment by orthagh** [comment]
As discussed together yesterday, i'm not sure about the fact "user may move between actors during ticket life" is a common one.
I know your instance is big, but did you have this behavior occurs regularly ? 

BTW, i think we could add a position field (numeric with corresponding constant values in class) easily to definitively fix the position of a user's answer.

Also, i am not satisfied with the proposed gui:
- the action should not be placed next to date
- imo, it's a very rare action but the button will be always present
- icons are not very straight forward
To approve this, we need to think about a way to propose this contextual action only when the user need it (unlock button ?, specific profiles ?, drag&drop ?) and avoid unwanted clicks

**Comment by orthagh** [comment]
Oh also, i'll prefer 9.2 in target for this enhancement.

**Comment by tomolimo** [comment]
Hello,

> "user may move between actors during ticket life" 

This case is not the problem we are facing, but rather the assignment and un-assignment of tech during ticket life-cycle:

1. a servicedesk will qualify the ticket when the ticket is still in 'new' status, then where to put the items added during qualification? After qualification, the ticket is assigned to a group, and then someone in the group will look at the ticket (but may be assigned himself to the ticket immediately), and the ticket may be unassgined again (if not routed to the right group). So a technician may be during some times the 'assigned to' and latter be unassigned from the ticket (during ticket life cycle). And another technician will be the 'assigned to'.

1. And sometimes in very rare cases a user may be the requester, and it can be changed during the ticket life cycle.

In both cases, the position of the items in the timeline will change, and will not reflect the effective dialog between requesters and technicians, 
The only way to reflect real dialog is to keep the items in the position they were at item creation. And to achieve this I cannot see something else than a field in DB.

> - the action should not be placed next to date
> - imo, it's a very rare action but the button will be always present
> - icons are not very straight forward To approve this, we need to think about a way to propose this contextual action only when the user need it (unlock button ?, specific profiles ?, drag&drop ?) and avoid unwanted clicks

I agree wit the three remarks, but I didn't find any other possibilities (I'm not good in presentation), And I'll rework that for the 9.2

thank you for the time spent by you on this subject,
regards,
Tomolimo
