### ISSUE TITLE
[GLPI 10.0 RC1] Action Mailgate does not work "mode auto"

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10765]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0 RC1

### Bug description

mailgate does not work on GLPI version 10.0
Apparently, I have other actions that work, but only the mailgate action does not work.

Mode manual, its OK

![image](https://user-images.githubusercontent.com/68054991/155343314-6a77ddac-9675-4ee3-8bbf-83bab991ba09.png)
![mailgate](https://user-images.githubusercontent.com/68054991/155343356-45920e1c-ef0d-4090-8a2a-dd297f1b2a98.jpg)

### Relevant log output

```shell
2022-02-23 15:11:59 [7@srv-glpi]
Interne #1 : Démarrage olaticket
2022-02-23 15:12:20 [7@srv-glpi]
Interne #1 : Démarrage mailgate  <===launch in manual mode and not automatic
2022-02-23 15:22:11 [7@srv-glpi]
Interne #1 : Démarrage graph
2022-02-23 15:22:20 [7@srv-glpi]
Interne #1 : Démarrage mailgate
2022-02-23 15:28:34 [7@srv-glpi]
Interne #1 : Démarrage watcher
2022-02-23 15:31:46 [7@srv-glpi]
Interne #1 : Démarrage mailgate   <===launch in manual mode and not automatic
2022-02-23 15:35:29 [7@srv-glpi]
Interne #1 : Démarrage temp
2022-02-23 15:43:27 [7@srv-glpi]
Interne #1 : Démarrage slaticket
2022-02-23 15:48:49 [7@srv-glpi]
Interne #1 : Démarrage olatick
2022-02-23 15:54:00 [7@srv-glpi]
Interne #1 : Démarrage planningrecall
```

### Page URL

/front/crontask.form.php?id=9

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-rc1 (/glpi10beta => /var/www/html/glpi10beta)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux srv-glpi 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64
PHP 8.0.15 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="5M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.6 (CentOS) PHP/8.0.15 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi10beta
	Host info: Localhost via UNIX socket
	
PHP version (8.0.15) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
Database engine version (10.4.22) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi10beta/files/_cache has been validated.
Write access to /var/www/html/glpi10beta/config has been validated.
Write access to /var/www/html/glpi10beta/files/_cron has been validated.
Write access to /var/www/html/glpi10beta/files has been validated.
Write access to /var/www/html/glpi10beta/files/_dumps has been validated.
Write access to /var/www/html/glpi10beta/files/_graphs has been validated.
Write access to /var/www/html/glpi10beta/files/_lock has been validated.
Write access to /var/www/html/glpi10beta/files/_pictures has been validated.
Write access to /var/www/html/glpi10beta/files/_plugins has been validated.
Write access to /var/www/html/glpi10beta/files/_rss has been validated.
Write access to /var/www/html/glpi10beta/files/_sessions has been validated.
Write access to /var/www/html/glpi10beta/files/_tmp has been validated.
Write access to /var/www/html/glpi10beta/files/_uploads has been validated.
Web access to files directory is protected
For security reasons, SELinux mode should be Enforcing.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi10beta/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi10beta
GLPI_CONFIG_DIR: /var/www/html/glpi10beta/config
GLPI_VAR_DIR: /var/www/html/glpi10beta/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi10beta/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi10beta/files
GLPI_CACHE_DIR: /var/www/html/glpi10beta/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi10beta/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi10beta/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi10beta/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi10beta/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi10beta/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi10beta/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi10beta/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi10beta/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi10beta/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi10beta/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi10beta/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi10beta/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi10beta/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi10beta/locales
GLPI_VERSION: 10.0.0-rc1
GLPI_SCHEMA_VERSION: 10.0.0-rc1@4f12cc11183dfb486b84e28e8dad44a9259736c3
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi10beta/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.5.4 in (/var/www/html/glpi10beta/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi10beta/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi10beta/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi10beta/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi10beta/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi10beta/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi10beta/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi10beta/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi10beta/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi10beta/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi10beta/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi10beta/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi10beta/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi10beta/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi10beta/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi10beta/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi10beta/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi10beta/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi10beta/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi10beta/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi10beta/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi10beta/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi10beta/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi10beta/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi10beta/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi10beta/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi10beta/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi10beta/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi10beta/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi10beta/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi10beta/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi10beta/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi10beta/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi10beta/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi10beta/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi10beta/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi10beta/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi10beta/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
phpCas version 1.4.0 in (/usr/share/pear)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.0-rc2  State: Enabled
	advancedplanning     Name: advancedplanning               Version: 1.1.0-rc1  State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc4  State: Enabled

</pre></details>

**Comment by steph461** [comment]
I try mode execution " GLPI' same issue

**Comment by cedric-anne** [comment]
Was the execution on `2022-02-23 15:22:20 [7@srv-glpi]` also manual ?

**Comment by steph461** [comment]
yes

**Comment by steph461** [comment]
before
![image](https://user-images.githubusercontent.com/68054991/155349927-52b6eafb-9ee3-4c4c-a85a-0f4e630f27e6.png) 

After
Mode auto KO , i launch mode manual
2022-02-23 16:20:49 [7@srv-glpi]
Interne #1 : Démarrage planningrecall
2022-02-23 16:25:18 [7@srv-glpi]
Interne #1 : Démarrage mailgate     <=== lauch manual
![image](https://user-images.githubusercontent.com/68054991/155350608-e0cf4b60-d78b-4774-bcb6-1cae641327e9.png)

**Comment by cedric-anne** [comment]
Can you check `Maximal number of automatic actions (run by CLI)` configuration (in Setup > General > System) ?

Also, it looks like all your actions are in `GLPI` mode, do you have any crontab configured server side ?

**Comment by steph461** [comment]
> Pouvez-vous vérifier `Maximal number of automatic actions (run by CLI)`la configuration (dans Configuration > Général > Système) ?
> 
> De plus, il semble que toutes vos actions soient en `GLPI`mode, avez-vous une crontab configurée côté serveur ?

- 6 mode "CLI" max

I left the same configuration on the version 9.5.7 and 10.0 RC1, it's the same database

Maybe this is a problem with two databases "GLPI" and "GLPI10beta" on the same server ?
http://x.x.x.225/glpi/front (version 9.5.7) Action OK
http://x.x.x.225/glpi10beta/front (version 10.0) Action KO

**Comment by steph461** [comment]
* * * * * php /var/www/html/glpi/front/cron.php &>/dev/null  version 9.5.7 

maybe   * * * * * php /var/www/html/**glpi10beta**/front/cron.php &>/dev/null

**Comment by steph461** [comment]
it was * * * * * php /var/www/html/glpi10/front/cron.php &>/dev/null
it's good I had to add this extra line and I completely forgot to add this line
it was not a bug
