### ISSUE TITLE
10.0.0.1RC1 - Issue when add a Simcards

### ISSUE THREAD

**Issue by jamesg1992** [glpi-project/glpi#10778]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1-RC1

### Bug description

When i add a simcard in the asset i see this error in debug mode
PHP Deprecated function (8192): preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /var/www/html/glpi/src/CommonDBConnexity.php at line 367
Uncaught Exception Error: Class name must be a valid object or a string in /var/www/html/glpi/src/CommonDBConnexity.php at line 372

in other assets all works

Debian 5.10.92-1 (2022-01-18) x86_64 - PHP 8.1.2 - nginx/1.20.2 - 10.5.12-MariaDB-0+deb11u1

_No response_

**Comment by cconard96** [comment]
Can you test the fix in #10787?

**Comment by jamesg1992** [comment]
I have modified the Item_Devices.php, but didn't change anything, i have reboot the machine but anything, there are any fixes?
