### ISSUE TITLE
10.0 RC1 Contract tab visible in ticket when permissions is turned off.

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#10779]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 RC1

### Bug description

Hi,

Thanks a lot for the work, RC1 is already way smoother !

Small issue :
The Contract tab menu visible in ticket view when permissions are turned off.

![Screenshot_20220224_231151](https://user-images.githubusercontent.com/63743077/155616777-1381d820-9511-4b60-8efb-aaa41ecfd074.png)
![Screenshot_20220224_231132](https://user-images.githubusercontent.com/63743077/155616778-70bfc3e4-69ba-42b4-9129-733e579bcb3a.png)
,

### Page URL

single ticket page

### Steps To reproduce

1° remove all contract permissions from a profile
2° view the contract tab visible in the ticket

### Your GLPI setup information

Debian 4.19.208-1 (2021-09-29) x86_64
PHP 7.4.28

**Comment by cconard96** [comment]
Should be fixed by #10788

**Comment by joomlafun** [comment]
Hi, This much appreciated Curtis.
