### ISSUE TITLE
[9.5.5] Sometimes replies to notifications are not integrated into tickets

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#10792]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

Hello,
Sometimes the replies to GLPI notifications are not integrated into GLPI, but they appear in the notimportedemail.php page.
![image](https://user-images.githubusercontent.com/7569958/155735459-da8384f2-f181-4e86-918c-977b66882241.png)

And they are kept in the INBOX folder of the mailbox.
Thank you
Regards,
Tomolimo

### Relevant log output

```shell
There is no log for that in the error logs.
```

### Steps To reproduce

1. Create a ticket like the one I've provided here in eml format:
[headertag test - initial email.eml.txt](https://github.com/glpi-project/glpi/files/8142048/headertag.test.-.initial.email.eml.txt)
1. Then use the reply to notification email here in eml format (change the ticket ID in the eml file before using it:
[headertag test fup email.eml.txt](https://github.com/glpi-project/glpi/files/8142054/headertag.test.fup.email.eml.txt)
1. go to the email receiver, and press "Get email tickets now"
2. You should get an error: 
![image](https://user-images.githubusercontent.com/7569958/155738869-c5fd121f-84fe-4a58-b031-3b7cea569189.png)
1. and the notification reply will stay in the INBOX
1. Expected result would be to get the reply email integrated in the ticket as a followup

### Anything else?

This is also an issue for GLPI 10.0 release.

**Comment by tomolimo** [comment]
Hello,

To give a screen copy of the reply email:
![image](https://user-images.githubusercontent.com/7569958/155739626-fffc82a2-ab65-42f9-a491-60be8efaf824.png)
As you can see, the "headertag" is missing the email: probably it has been deleted by the end-user when replying to the notification...

Thank you
Regards
Tomolimo

**Comment by cedric-anne** [comment]
@tomolimo 

Changing this beahviour is quiet simple:

```diff
diff --git a/src/MailCollector.php b/src/MailCollector.php
index 5d1893e1b1..08c0a76d91 100644
--- a/src/MailCollector.php
+++ b/src/MailCollector.php
@@ -1151,20 +1151,6 @@ class MailCollector extends CommonDBTM
                         '',
                         $tkt['content']
                     );
-                } else if ($has_header_line) {
-                   // Strip all contents between header line and end of message
-                    $tkt['content'] = preg_replace(
-                        '/' . $header_pattern . '.*$/s',
-                        '',
-                        $tkt['content']
-                    );
-                } else if ($has_footer_line) {
-                   // Strip all contents between begin of message and footer line
-                    $tkt['content'] = preg_replace(
-                        '/^.*' . $footer_pattern . '/s',
-                        '',
-                        $tkt['content']
-                    );
                 }
             } else {
                // => to handle link in Ticket->post_addItem()
```

Maybe we should indeed change it, to ensure that followup is still collected when original message has been altered this way.

@orthagh @trasher What do you think of it ?

**Comment by cedric-anne** [comment]
@tomolimo 

#10797 will fix it.
