### ISSUE TITLE
9.5.7 Installation problem

### ISSUE THREAD

**Issue by linuxprocess** [glpi-project/glpi#10793]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

During installation process, for database phase, I met a strange SQL error : Uncaught Exception mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''0', `type` int(11) NOT NULL DEFAULT '0' COMMENT '...' at line 4 in /mnt/sdb1/gui/datas/dev/glpi/glpi/inc/dbmysql.class.php at line 328

### Relevant log output

```shell
[2022-02-25 19:53:37] glpiphplog.WARNING: Test logger  
[2022-02-25 19:54:07] glpiphplog.CRITICAL:   *** Uncaught Exception mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '&#039;0&#039;,
  `type` int(11) NOT NULL DEFAULT &#039;0&#039; COMMENT &#039;...' at line 4 in /mnt/sdb1/gui/datas/dev/glpi/glpi/inc/dbmysql.class.php at line 328
  Backtrace :
  inc/dbmysql.class.php:328                          mysqli->query()
  inc/dbmysql.class.php:857                          DBmysql->query()
  inc/toolbox.class.php:2493                         DBmysql->runFile()
  install/install.php:405                            Toolbox::createSchema()
  install/install.php:677                            step4()
```

### Page URL

http://127.0.0.1/glpi/install/install.php

### Steps To reproduce

Following https://glpi-install.readthedocs.io/en/latest/install/wizard.html ...
After step "Database choice" using an existing database.

### Your GLPI setup information

I'm on commit e9b16bc8e9b61ebb2d35b96b9c71cd25c5af9e48 (HEAD, tag: 9.5.7)
On a up-to-date debian testing distro.

$ mariadb --version
mariadb  Ver 15.1 Distrib 10.6.5-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper

$ md5sum install/mysql/glpi-empty.sql
c3a6fc30d28416d7ccf93f149d8b55d7  install/mysql/glpi-empty.sql

**Comment by cedric-anne** [comment]
Hi,

It seems that your are using PHP 8.1. Unfortunately, GLPI 9.5.x is not compatible with this version of PHP. You have to use PHP 8.0 instead, or to wait for the upcoming GLPI 10.0 version.

Regards

**Comment by linuxprocess** [comment]
Indeed I'm using PHP 8.1.2
Thanks for your answer
Is there any git branch created for this future version, which I could "use" for tests and help to work on ? (I did not find any, but maybe I missed it)
Regards

**Comment by cedric-anne** [comment]
You can use the master branch, or use [GLPI nightly builds](https://nightly.glpi-project.org/glpi/).

**Comment by linuxprocess** [comment]
That works indeed.
Thanks !
