### ISSUE TITLE
Error with 'Ignored values for uniqueness' dropdown when plugin disabled

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#108]
GLPI 0.85
Create a record in 'Ignored values for uniqueness' dropdown for a plugin : Type = 'Sim card', Appliance ....
In the dropdown view, show 'Field' and/or 'Value' (for all other information, there is no error)
Then disable the plugin -> Fatal error: Call to a member function getSearchOptionByField() on a non-object in /var/www/glpi085/inc/fieldblacklist.class.php on line 123
Same when plugin is Uninstalled, and cleaning was not completely done.

Note that more or less the same info is used by (field unicity) checks. And there is no error.

**Comment by yllen** [comment]
I think it's a bug in the plugin not in GLPI
