### ISSUE TITLE
Management datas not duplicated from template

### ISSUE THREAD

**Issue by lorenzo33** [glpi-project/glpi#10804]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

First, I create a template for new computer and I complete general informations and I click on Create button. 

After the creation, I edit the template and add Management Informations (like order date, purchase date, value...) and I save it.

Then, I add a new computer from the previous created template. 
I complete the general tab, I check the Management tab (all datas are correctly showed) and I click on Add button.

Finaly, I check the new computer item created and I see that Management Tab data is empty.

Thanks.

 

### Steps To reproduce

1. Template creation for new computer
2. Add some data to this new template (Management data)
3. Computer creation from this new template
4. Management data is empty instead to be duplicate

### Your GLPI setup information

[code]   GLPI 9.5.6 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux sr-glpi-prod 3.10.0-1160.11.1.el7.x86_64 #1 SMP Mon Nov 30 13:05:31 EST 2020 x86_64 PHP 7.2.34 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.6 (Red Hat Enterprise Linux) PHP/7.2.34 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.27-MariaDB-log 	Server SQL Mode:  	Parameters: glpi@p-bddmaria-01.in.ac-noumea.nc/glpi_prod 	Host info: p-bddmaria-01.in.ac-noumea.nc via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.27) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration. For security reasons, SELinux mode should be Enforcing.

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.6 GLPI_SCHEMA_VERSION: 9.5.6 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/pear)

Server: 'ldap.in.ac-noumea.nc', Port: '389', BaseDN: 'ou=groups,ou=ac-noumea,ou=education,o=gouv,c=nc', Connection filter: none, 		RootDN: 'uid=vr_glpi,ou=People,ou=ac-noumea,ou=education,o=gouv,c=nc', Use TLS: none Server: 'ldap.in.ac-noumea.nc', Port: '389', BaseDN: 'ou=personnels EN,ou=ac-noumea,ou=education,o=gouv,c=nc', Connection 		filter: none, RootDN: 'uid=vr_glpi,ou=People,ou=ac-noumea,ou=education,o=gouv,c=nc', Use TLS: none Server: 'ldap.in.ac-noumea.nc', Port: '389', BaseDN: 'ou=fonctionnelles,ou=ac-noumea,ou=education,o=gouv,c=nc', Connection 		filter: none, RootDN: 'uid=vr_glpi,ou=People,ou=ac-noumea,ou=education,o=gouv,c=nc', Use TLS: none Server: 'ldap.in.ac-noumea.nc', Port: '389', BaseDN: 'ou=autres,ou=ac-noumea,ou=education,o=gouv,c=nc', Connection filter: none, 		RootDN: 'uid=vr_glpi,ou=People,ou=ac-noumea,ou=education,o=gouv,c=nc', Use TLS: none

Not active

Way of sending emails: PHP

Name: 'alertesdsi@ac-noumea.nc' Active: Yes 	Server: '{mail.ac-noumea.nc:993/imap/ssl/notls}INBOX' Login: 'alertesdsi' Password: Yes

news                 Name: Alertes                        Version: 1.8.0      State: Enabled 	servicecatalog       Name: Catalogue de service           Version: 1.7.11     State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.12.6     State: Enabled 	mydashboard          Name: Dashboard                      Version: 1.8.1      State: Enabled 	datainjection        Name: Data Injection                 Version: 2.9.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.12.4     State: Enabled 	tag                  Name: Gestion des tags               Version: 2.8.1      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Enabled 	dashboard            Name: Tableau de bord                Version: 0.9.9      State: Enabled

Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
Host: ocsetab.ac-noumea.ncConnection: OkUse the OCSNG software dictionary: No
[/code]

**Comment by cconard96** [comment]
Duplicate of #9666, #8953, #8544?
Fixed by #10406

**Comment by lorenzo33** [comment]
Thanks a lot. I'm waiting for the pull request in the next release.
