### ISSUE TITLE
no Notification for reply to satisfaction survey

### ISSUE THREAD

**Issue by erramnazi** [glpi-project/glpi#1082]
Dear GLPi user.
 i need know how i configure the satisfaction survey on GLPI
The GLPi team.

**Comment by jorgecamargosdb** [comment]
@erramnazi 

Administration Menu> Entities
Assistance Guide

![image](https://cloud.githubusercontent.com/assets/23311692/24885631/e93bfbd0-1e25-11e7-8888-d81847bde587.png)

**Comment by cedric-anne** [comment]
Hi,

I close this ticket as question has been answered.

Regards
