### ISSUE TITLE
GLPI 10 RC1 - UX issue when financial and administrative info enabled

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10832]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 RC1

### Bug description

Hi,

when i enable financial and administrative info enabled inside any components the UX is somewhat broken at the edges.

![image](https://user-images.githubusercontent.com/22425503/156363358-18bb98d4-e581-4215-a4f4-3448ba750d71.png)

![image](https://user-images.githubusercontent.com/22425503/156363259-1b7e131b-160d-4ee0-983b-65cbe8b377c5.png)

**Comment by cconard96** [comment]
Fixed via #10854.
