### ISSUE TITLE
No sound with browser notifications in Firefox

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#10833]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Browser notifications are OK in Chrome but not in Firefox. I can see in the console : 
`The Notification permission may only be requested from inside a short running user-generated event handler.`

After searching on the web, I found [this StackOverFlow topic](https://stackoverflow.com/questions/61475486/notification-requestpermission-throwing-error-on-mozilla) which concerns that issue.

### Steps To reproduce

1. Activate browser notifications (/front/setup.notification.php)
2. Test the notification (/front/notificationajaxsetting.form.php)

### Your GLPI setup information

GLPI_ROOT: /var/www/apps/glpi
GLPI_CONFIG_DIR: /var/www/apps/glpi/config
GLPI_VAR_DIR: /var/www/apps/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/apps/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/apps/glpi/files
GLPI_CACHE_DIR: /var/www/apps/glpi/files/_cache
GLPI_CRON_DIR: /var/www/apps/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/apps/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/apps/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/apps/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/apps/glpi/files/_lock
GLPI_LOG_DIR: /var/www/apps/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/apps/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/apps/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/apps/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/apps/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/apps/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/apps/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/apps/glpi/locales
GLPI_VERSION: 9.5.7
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022

**Comment by paidge** [comment]
I saw this button near the adress bar and it solves the problem : 
![image](https://user-images.githubusercontent.com/2470104/156374339-d873c217-6359-4fb3-896b-4d89f250cd37.png)

**Comment by paidge** [comment]
But there is no sound when a notification is fired.

**Comment by cconard96** [comment]
Please check your browser console for any warnings or errors when the notification is received (F12 key, console tab).

**Comment by paidge** [comment]
I have already said :
`Browser notifications are OK in Chrome but not in Firefox. I can see in the console :
The Notification permission may only be requested from inside a short running user-generated event handler.` ;)

I will check tomorrow but I think there is no more information in the console.

**Comment by cconard96** [comment]
I wasn't able to recreate the issue on Firefox 97.0. Initially I had no audio at all for notifications until I realized it was disabled by default and had to pick a sound in "Browser Followups Configuration". I also had to manually give permission for audio to play from GLPI in Firefox. I also tested on Google Chrome with the same results.

**Comment by cconard96** [comment]
I should probably add that I'm testing on GLPI 10.

**Comment by paidge** [comment]
I have tried again today. And I don't understand why it is working without changing the configuration of Firefox. Sorry.
