### ISSUE TITLE
[GLPI 10.0.0-rc2] Documents attached to ticket no longer showing up since RC2

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#10839]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

Since update,

When documents are added to a ticket, there are no longer present in the ticket itself:
![image](https://user-images.githubusercontent.com/1759156/156522881-43b9ab30-b09c-4883-8dab-b7512e1c5829.png)

But the documents are linked to the ticket:
![image](https://user-images.githubusercontent.com/1759156/156522995-21fe3c20-72d5-4c46-924e-835d6301f371.png)

I checked, the profil SuperAdmin has every checkbox ticked. I tried to relog since the update, it does not fix the update.
There is not log related to in php-errors.log or error in Debug Mode.

It seems to be a logical issue in the page.

### Page URL

front/ticket.form.php

### Steps To reproduce

1. Create a ticket
2. Add a document to a ticket.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-rc2 ( => E:\GLPI)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT SRVGLPI10 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.2 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="2048M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2048M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.3-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.2) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.3) is supported.
The log file has been created successfully.
Write access to E:\GLPI/files/_cache has been validated.
Write access to E:\GLPI/config has been validated.
Write access to E:\GLPI/files/_cron has been validated.
Write access to E:\GLPI/files has been validated.
Write access to E:\GLPI/files/_dumps has been validated.
Write access to E:\GLPI/files/_graphs has been validated.
Write access to E:\GLPI/files/_lock has been validated.
Write access to E:\GLPI/files/_pictures has been validated.
Write access to E:\GLPI/files/_plugins has been validated.
Write access to E:\GLPI/files/_rss has been validated.
Write access to E:\GLPI/files/_sessions has been validated.
Write access to E:\GLPI/files/_tmp has been validated.
Write access to E:\GLPI/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to E:\GLPI/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: E:\GLPI
GLPI_CONFIG_DIR: E:\GLPI/config
GLPI_VAR_DIR: E:\GLPI/files
GLPI_MARKETPLACE_DIR: E:\GLPI/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: E:\GLPI/files
GLPI_CACHE_DIR: E:\GLPI/files/_cache
GLPI_CRON_DIR: E:\GLPI/files/_cron
GLPI_DUMP_DIR: E:\GLPI/files/_dumps
GLPI_GRAPH_DIR: E:\GLPI/files/_graphs
GLPI_LOCAL_I18N_DIR: E:\GLPI/files/_locales
GLPI_LOCK_DIR: E:\GLPI/files/_lock
GLPI_LOG_DIR: E:\GLPI/files/_log
GLPI_PICTURE_DIR: E:\GLPI/files/_pictures
GLPI_PLUGIN_DOC_DIR: E:\GLPI/files/_plugins
GLPI_RSS_DIR: E:\GLPI/files/_rss
GLPI_SESSION_DIR: E:\GLPI/files/_sessions
GLPI_TMP_DIR: E:\GLPI/files/_tmp
GLPI_UPLOAD_DIR: E:\GLPI/files/_uploads
GLPI_INVENTORY_DIR: E:\GLPI/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: E:\GLPI/locales
GLPI_VERSION: 10.0.0-rc2
GLPI_SCHEMA_VERSION: 10.0.0-rc2@26641609f9b8fcb8038fb220c3fcafa75a95021f
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (E:\GLPI\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (E:\GLPI\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (E:\GLPI\vendor\simplepie\simplepie\library)
mpdf/mpdf in (E:\GLPI\vendor\mpdf\mpdf\src)
michelf/php-markdown in (E:\GLPI\vendor\michelf\php-markdown\Michelf)
true/punycode in (E:\GLPI\vendor\true\punycode\src)
iamcal/lib_autolink in (E:\GLPI\vendor\iamcal\lib_autolink)
sabre/dav in (E:\GLPI\vendor\sabre\dav\lib\DAV)
sabre/http in (E:\GLPI\vendor\sabre\http\lib)
sabre/uri in (E:\GLPI\vendor\sabre\uri\lib)
sabre/vobject in (E:\GLPI\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (E:\GLPI\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (E:\GLPI\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (E:\GLPI\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (E:\GLPI\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (E:\GLPI\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (E:\GLPI\vendor\elvanto\litemoji\src)
symfony/console in (E:\GLPI\vendor\symfony\console)
scssphp/scssphp in (E:\GLPI\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (E:\GLPI\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (E:\GLPI\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (E:\GLPI\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (E:\GLPI\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (E:\GLPI\vendor\ramsey\uuid\src)
psr/log in (E:\GLPI\vendor\psr\log\Psr\Log)
psr/simple-cache in (E:\GLPI\vendor\psr\simple-cache\src)
psr/cache in (E:\GLPI\vendor\psr\cache\src)
league/csv in (E:\GLPI\vendor\league\csv\src)
mexitek/phpcolors in (E:\GLPI\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (E:\GLPI\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (E:\GLPI\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (E:\GLPI\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (E:\GLPI\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (E:\GLPI\vendor\paragonie\sodium_compat\src)
symfony/cache in (E:\GLPI\vendor\symfony\cache)
html2text/html2text in (E:\GLPI\vendor\html2text\html2text\src)
symfony/dom-crawler in (E:\GLPI\vendor\symfony\dom-crawler)
twig/twig in (E:\GLPI\vendor\twig\twig\src)
twig/string-extra in (E:\GLPI\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://srvadsel01', Port: '389', BaseDN: 'DC=spurgin,DC=local', Connection filter: none, RootDN:
		'CN=spurginsvc,OU=Compte Service,OU=Z_GENERIQUE,DC=spurgin,DC=local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@192.168.28.237)

</details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc4  State: Enabled

</pre></details>

**Comment by SteadEXE** [comment]
Images are showing up still:
![image](https://user-images.githubusercontent.com/1759156/156523727-ae4e1da0-7d37-4b80-a5f1-c1c384f8ff60.png)

**Comment by SteadEXE** [comment]
It seems that the message "Created by Foo at Bar" of the document is showing, but the link is missing.

**Comment by SteadEXE** [comment]
I backported the change to my GLPI, now it works for newly created/collected ticket :)
Thanks Curtis for the quick fix!

**Comment by cconard96** [comment]
Re-opening until PR is reviewed and merged. It will automatically close at that time.

**Comment by SteadEXE** [comment]
Hello @cconard96, sorry for bothering you but the issue is still present if a ticket get created with documents already created in another document. Like if the same PDF is sent by multiple users over multiple tickets, the link is not showing up.
