### ISSUE TITLE
[GLPI 10.0.0-rc2] No assets history in user

### ISSUE THREAD

**Issue by jamesg1992** [glpi-project/glpi#10841]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

Hi, i have updated to GLPI v.10.0.0-rc2, and have no history of the assets in the user profile

there is a fix? or a plugin to install?

I noticed this that even in the previous version 

Thanks

Server Software: Debian 11
Server Version: 10.5.12-MariaDB-0+deb11u1
PHP 8.1.2

**Comment by cedric-anne** [comment]
Hi,

This improvement does not exist and is not in our roadmap for now. If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us

You can also propose a pull request to implement this feature.

Regards
