### ISSUE TITLE
text added not persistent when using solutions templates

### ISSUE THREAD

**Issue by ppenin** [glpi-project/glpi#1084]
When using solution templates, when text is added, the content is not preserved after you click Save.
Only the template content remains and text added is lost.
Load a solution template and add text :
![img1](https://cloud.githubusercontent.com/assets/22499638/18916044/5082ef96-8593-11e6-809c-eb4fe4e75119.jpg)
When Save Button is submitted, added text is cleared :
![img2](https://cloud.githubusercontent.com/assets/22499638/18916046/531db15a-8593-11e6-9c7d-29fb20612a58.jpg)

**Comment by orthagh** [comment]
Hello @ppenin 

I could'nt replicate your issue on current master of glpi.
What's your current version ?

**Comment by ppenin** [comment]
Hello,

Glpi version is the last one : 9.1

Regards,

Patrice PENIN
Directeur des systèmes d’information
Direction Générale - Mulhouse
ppenin@groupesaintsauveur.fr<mailto:ppenin@groupesaintsauveur.fr> - 06 74 93 33 92

Groupe Saint Sauveur
Santé Enfance Handicap Senior

Découvrez le GCSMS Partenariat et Développement en cliquant ici.<http://www.groupesaintsauveur.fr/qui-sommes-nous/gcsms>

Pensez à l’environnement. Avez-vous besoin d'imprimer ce courriel ?
Ce message et les pièces jointes sont établis à l'intention exclusive de ses destinataires et sont confidentiels.
Si vous recevez ce message par erreur, merci de le détruire et d'en avertir immédiatement l'expéditeur.


De : Alexandre Delaunay [mailto:notifications@github.com]
Envoyé : mardi 4 octobre 2016 14:17
À : glpi-project/glpi <glpi@noreply.github.com>
Cc : Penin Patrice <ppenin@groupesaintsauveur.fr>; Mention <mention@noreply.github.com>
Objet : Re: [glpi-project/glpi] text added not persistent when using solutions templates (#1084)


Hello @ppenin<https://github.com/ppenin>

I could'nt replicate your issue on current master of glpi.
What's your current version ?

**Comment by orthagh** [comment]
See #1261 for resolution of this issue.
It seems to occurs only on firefox and internet explorer
