### ISSUE TITLE
Fresh install on windows

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1085]
http://forum.glpi-project.org/viewtopic.php?id=155472

Sorry i haven't windows to test

**Comment by tomolimo** [comment]
I got no problem with the archive. 
So try to download it again. 
Try with 7zip.

**Comment by Nosolok** [comment]
Checked on windows 8 with 7-zip and winrar.
These required admin rights to create symlink in glpi/vendor/bin.

**Comment by trasher** [comment]
I'm unsure windows can really use any symlink.... And this is absolutely not used to install nor use glpi anyways.

Maybe should we just drop `vendor/bin` for the next release?

**Comment by tomolimo** [comment]
Yes of course it does :) see https://msdn.microsoft.com/en-us/library/windows/desktop/aa365680(v=vs.85).aspx
But probably not the same content, so not the same behavior at the end, so I agree that we should delete them from the archive.
