### ISSUE TITLE
Search engine for ticket actors

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1086]
http://forum.glpi-project.org/viewtopic.php?id=155498

**Comment by yllen** [comment]
The issue is for all actors dropdown (requester, observer or technician)

**Comment by vinz38500** [comment]
The issue is the same for 9.1 ...

**Comment by orthagh** [comment]
Regression in e04db09
I'm currently investigating

**Comment by vihuarar** [comment]
I already made the changes in 0f50552 with my user (super user) works fine.. but for some users that have "Technical" profile dont work...
