### ISSUE TITLE
Number of user in the dashboard don't take the entity filter into account

### ISSUE THREAD

**Issue by delcroip** [glpi-project/glpi#10870]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Normally when an entity is selected in the entity tree, the dashboard numbers should be updated for the selected entity but the user one shows always the number of all users 

### Steps To reproduce

1. create 2 child entity
2. add a user on each entity (profile with dashboard)
3. connect with on of those users
4. the number of user could be 1 (only the one attached to this entity) or 5 (1 + the 4 on root with access to child) but not 6 as today

**Comment by cedric-anne** [comment]
Fixed by #10871.
