### ISSUE TITLE
I have some error in software 

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#1087]
Hello!

I choose computer, software tab:
http://imgur.com/a/O2Q1j
after click:
http://imgur.com/a/ZTZPw

red line:
PHP Notice: Undefined variable: values in /var/www/glpi/ajax/dropdownInstallVersion.php at line 88

and below:
Fatal error: Uncaught TypeError: Argument 2 passed to Dropdown::showFromArray() must be of the type array, null given, called in /var/www/glpi/ajax/dropdownInstallVersion.php on line 88 and defined in /var/www/glpi/inc/dropdown.class.php:1758 Stack trace: #0 /var/www/glpi/ajax/dropdownInstallVersion.php(88): Dropdown::showFromArray('softwareversion...', NULL, Array) #1 {main} thrown in /var/www/glpi/inc/dropdown.class.php on line 1758
 Install

**Comment by orthagh** [comment]
Hello @Zegordo 

I replicated this error, it triggers when selected software don't have any versions.
You can't install this kind of software in a glpi computers.
Anyway fix incoming for 9.1.1 in #1111
