### ISSUE TITLE
Enable the financial and administrative information by default under assets tab

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#10877]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI All Versions

### Bug description

Hi,

when you Enable the financial and administrative information by default under Setup - General - Assets tab , 

it is enabled only on the new assets ignoring already existing assets. for existing assets you have to enable it manually for each.

**Comment by cconard96** [comment]
The current behavior is intended. Automatically enabling it for all existing items may be problematic on instances that have a lot of items and may not be needed for every previous item if you don't have any data to put in.

You may be able to use the API to script the automatic creation of an empty "financial and administrative information" for other items. The name of the item type for this is "Infocom".
