### ISSUE TITLE
Software category filtering in computer form

### ISSUE THREAD

**Issue by ameurou** [glpi-project/glpi#1088]
Hello,

Since 0.90 (maybe 0.85) software categories are not filtered anymore in computer form. The dropdown show all available categories instead of only related ones to sofware installed on the computer : 

![sofware_categories](https://cloud.githubusercontent.com/assets/11721263/18948716/7e1ac334-8638-11e6-8028-4baa26290982.png)

It is maybe intended, but with a lot of software categories, it could be a pain to find the one you want.

IMO showing only categories related to software installed on the computer is the best, but adding a search box like in software dropdown could be an other option : 

![sofware_categories_search](https://cloud.githubusercontent.com/assets/11721263/18948741/96eb874a-8638-11e6-9611-2fcf212177f4.png)

Regards,
AM

**Comment by trasher** [comment]
I do not know if the change was intended, so I cannot qualify this as a bug or a feature.

Anyways, even if it is a bug or not, I guess we could make the dropdown searchable; sound like a good idea to me.

**Comment by ameurou** [comment]
Do you think that not showing empty categories for a computer can be part of this fix/feature ?

If not, i'll create a sugestion on Userecho.

Thanks

**Comment by cedric-anne** [comment]
Hi,

Display of search engine is configurable using the `Don't show search engine in dropdowns if the number of items is less than` global setting.
For the enhancement on category filter, I guess a suggestion has been made on Userecho.

Regards
