### ISSUE TITLE
Components keep getting added to GLPI, plaguing history 

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#10880]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

I don't know if it's related to native inventory, or on the agent side, but components keep getting added everytime agent run an inventory task.

![image](https://user-images.githubusercontent.com/1759156/156980562-f65f9ccd-4d19-493d-861b-48a698140ca7.png)

![image](https://user-images.githubusercontent.com/1759156/156980594-641bd51e-14e2-41ba-a1c3-cc45c9a1a5f1.png)

![image](https://user-images.githubusercontent.com/1759156/156980608-a23d3b69-1bf9-41c1-b8c4-bdf6a1b6eb4f.png)

I don't see those components getting remove in the history.

### To reproduce

1. Install the agent
2. Let it run a couple of time

### Expected behavior

A same component should only be added once in a computer.

### Operating system

Windows

### GLPI Agent version

1.1

### GLPI version

10.0.0-rc1, development release (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.0-rc4, development release (See additional context below)

**Comment by g-bougard** [comment]
Hi @SteadEXE 

UI issues should be reported as GLPI issue, not GLPI-Agent one ;-)

But thank you for your report.

**Comment by trasher** [comment]
This is indeed a native inventory issue; probably because in facts the link between the item and all devices are recreated (but that should not be logged).
