### ISSUE TITLE
[GLPI 10.0 RC2] Error message on network ports view (network equipment) : Error: Call to a member function getLink()

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10893]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 RC2

### Bug description

On the network ports view, there is an error message on the GLPI 10.0 RC2 version. I have this problem on some switches that are connected to PCs

On my production version 9.5.7, everything is displayed correctly

example : 

9.5.7
![9 5 7](https://user-images.githubusercontent.com/68054991/157052861-dbdf35e9-093e-4a20-b681-1f7e9e21abfd.jpg)

10.0 RC2 : Error Message no link with the computers and no link port networks (51)
![image](https://user-images.githubusercontent.com/68054991/157053079-824d5fd5-3f59-461d-a14a-d79b270c295f.png)

### Relevant log output

```shell
[2022-03-07 13:58:31] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getLink() on bool in /var/www/html/glpi10beta/src/NetworkPort.php at line 1206
  Backtrace :
  src/NetworkPort.php:1047                           NetworkPort->getUnmanagedLink()
  src/NetworkPort.php:776                            NetworkPort->showPort()
  src/NetworkPort.php:1690                           NetworkPort::showForItem()
  src/CommonGLPI.php:687                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-03-07 13:58:57] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getLink() on bool in /var/www/html/glpi10beta/src/NetworkPort.php at line 1206
  Backtrace :
  src/NetworkPort.php:1047                           NetworkPort->getUnmanagedLink()
  src/NetworkPort.php:776                            NetworkPort->showPort()
  src/NetworkPort.php:1690                           NetworkPort::showForItem()
  src/CommonGLPI.php:687                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-03-07 13:59:46] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getLink() on bool in /var/www/html/glpi10beta/src/NetworkPort.php at line 1206
  Backtrace :
  src/NetworkPort.php:1047                           NetworkPort->getUnmanagedLink()
  src/NetworkPort.php:776                            NetworkPort->showPort()
  src/NetworkPort.php:1690                           NetworkPort::showForItem()
  src/CommonGLPI.php:687                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
```

### Page URL

front/networkequipment.form.php?id=xx

### Steps To reproduce

1. network equipment
2. go to network port view

**Comment by trasher** [comment]
I guess you were using fusioninventory plugin and this is a data migration? In that case, do you reproduce if you inventory directly those equipments in 10.0?
Maybe the code may be consilidated to prevent this error; but I suspect an issue in data.

**Comment by steph461** [comment]
It is indeed a data migration with fusion
If I create a switch networks and assign a network port manually, it works and no error
![image](https://user-images.githubusercontent.com/68054991/157065621-75bad6cb-8196-42d2-886d-924451cac23e.png)

**Comment by steph461** [comment]
Hello @trasher

addition of information : 

I removed the switch sw-xx-xx from the list and performed a new network discovery. I added the ports manually without getting the error

For the moment, I do not perform SNMP discovery, there is a bug.
The snmp will allow me to automatically add the switch ports

**Comment by steph461** [comment]
Hello last FIX GLPI 10 its OK
![image](https://user-images.githubusercontent.com/68054991/158795976-e9987253-ff8b-40ec-9493-649281d42028.png)
 maybe #10987

**Comment by trasher** [comment]
> maybe #10987
I don't think so; but the issue is solved, that's the main point :) We've made several fixes last few days.

Thank you for the feedback!
