### ISSUE TITLE
Filter in tickets....

### ISSUE THREAD

**Issue by vihuarar** [glpi-project/glpi#1089]
Hi... 
I have my glpi configured in a subentity...

Most users are part of the subentity "Area TI"... and only about 3 users are part of "root entity"

For some reason... the filters in the search form in the "ticket view" are only showing the users in the "root entity" and the "Area TI" users are not visible...
host/glpi/front/ticket.php
this is the screenshot in the 9.1 version...
![screenshot from 2016-09-29 10 48 41](https://cloud.githubusercontent.com/assets/1976384/18961316/3ce929d8-8632-11e6-91c5-87376f85ab21.png)

and this is the screenshot in the 0.90 version... (working everything fine) 
![screenshot from 2016-09-29 10 50 06](https://cloud.githubusercontent.com/assets/1976384/18961369/7d1ec0c6-8632-11e6-8201-b0a20a0e9e29.png)

Dear GLPi user.

The GLPi team.

**Comment by tomolimo** [comment]
Seems to be like #1086

**Comment by orthagh** [comment]
See #1086 for resolution
