### ISSUE TITLE
Notification config page : Search option "Event" is buggy

### ISSUE THREAD

**Issue by Manu1400** [glpi-project/glpi#109]
In front/notification.php page, the search option/criteria "Event" fail : 

Events contains "ticket" -> don't return lines with the event "New ticket"

Tested with GLPI 0.85.3

**Comment by Manu1400** [comment]
Fail with a "GLPI 0.90" too.

**Comment by yllen** [comment]
I confirm: event dropdown is empty at the creation

**Comment by yllen** [comment]
bug introduce with this commit https://github.com/glpi-project/glpi/commit/2d7fe6eed3e95ead229ed9d0e17e6ad677425275#diff-298092ebe134c5b9ccbc7042328fb02c

In html::jsAdaptDrodown()
if your delete
                   formatSelection: function(object, container) {
                     text = object.text;
                     if (object.element[0].parentElement.nodeName == 'OPTGROUP') {
                        text = object.element[0].parentElement.getAttribute('label') + ' - ' + text;
                     }
                     return text;
                  }
It's( OK

**Comment by orthagh** [comment]
@yllen, I think you are mentioning another issue

@Manu1400 describes a problem with sql query when he search in the content of glpi_notifications.event.
In this case, the query search the word 'ticket' in event field which is in english (and doesn't contains the word ticket), see result of next query : 

````
... `event` LIKE '%ticket%'

name                         | itemtype | event                          | ...
-----------------------------|----------|--------------------------------|-----
Assignation technicien       | Ticket   | plugin_behaviors_ticketnewtech | ...
Assignation groupe           | Ticket   | plugin_behaviors_ticketnewgrp  | ...
Réouverture ticket           | Ticket   | plugin_behaviors_ticketreopen  | ...
attribution à un technicien  | Ticket   | plugin_behaviors_ticketnewtech | ...


````

I don't have any good solution for this issue, ideas are welcome.

For your bug, @yllen, can you open a new issue for tracking and debug.

**Comment by yllen** [comment]
There is no problem.
In the example, new ticket is not an event
You must search on 
Type = Ticket
AND
Event = new
