### ISSUE TITLE
[GLPI 10.0 RC2] Migration DB error "glpi_rules.entities_id"

### ISSUE THREAD

**Issue by Deki60** [glpi-project/glpi#10903]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0 RC2

### Bug description

Migration DB after GLPI Update : 

1 primary or foreign keys columns are using signed integers. Lancez la commande "php bin/console glpi:migration:unsigned_keys" pour les migrer.

### Relevant log output

```shell
/var/www/html/glpi# php bin/console glpi:migration:unsigned_keys
Found 1 primary/foreign key columns(s) using signed integers.
Voulez-vous continuer ? [Yes/no]Yes
Migration of column "glpi_rules.entities_id" cannot be done as it contains negative values.
 1/1 [============================] 100%
Des erreurs se sont produites pendant la migration.
```

**Comment by cconard96** [comment]
Can you check in the DB which rules they are and their sub-types (Would identify if it is from a plugin or core collection)?

```SQL
SELECT name,sub_type,date_creation FROM glpi_rules WHERE entities_id < 0;
```

**Comment by Deki60** [comment]
Thank you for reply

i applied the command here is the result : 

`MariaDB [glpi]> SELECT name,sub_type,date_creation FROM glpi_rules WHERE entities_id < 0;
+------+-----------+---------------------+
| name | sub_type  | date_creation       |
+------+-----------+---------------------+
|      | RuleRight | 2022-01-19 14:38:02 |
+------+-----------+---------------------+
1 row in set (0.000 sec)
`

**Comment by cconard96** [comment]
It is odd that there isn't a name for this "Authorization Assignment Rule", but for all of this type of right, I guess that the Entity doesn't matter as they are global. I did find that the RuleRight form sets the `entities_id` statically to -1. This is indeed a bug.

**Comment by cedric-anne** [comment]
@cconard96 I will fix it.

**Comment by cconard96** [comment]
The odd thing is that saving a new rule of this type now sets it to 0.
