### ISSUE TITLE
Error when creating Project Task in a bulk in Kanban Project

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#10900]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

When I try to create project tasks in bulk, and there is a line break at the end, instead of creating the project tasks in the Kanban, it redirects to the Project creation form.

### Steps To reproduce

1. Create new Proyect and open it
2. Go to Kanban
3. In "No status" click in "..." 
4. Click in "Bulk add"
5. Click in "Project Task"
6. Add Tasks pear line, and also add a line break else, with no text
7. Clic en Add
8. Error, instead of adding the Project Tasks that had been written, one per line, all of these has been ignored, and the URL has been redirect to the Create Project Form.

![image](https://user-images.githubusercontent.com/56606032/157114508-40d6d806-ab8b-4110-bc96-32269da3a667.png)

### Your GLPI setup information

<html>
<body>

[code]   GLPI 9.5.7 ( => /var/www/html/glpi) Installation mode: TARBALL Current language:en_GB
--

Operating system: Linux - 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="360" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at  Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36 Edg/98.0.1108.62 Server Software: Ubuntu 20.04 	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1 	Server SQL Mode:  	Parameters:  	Host info: haproxy via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.34) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.7 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022 GLPI_MOD_DIR: /var/www/html/glpi/plugins/mod

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Not active

accounts             Name: Accounts                       Version: 2.6.0      State: Enabled 	activity             Name: Activities                     Version: 3.0.0      State: Enabled 	actualtime           Name: ActualTime                     Version: 1.5.1      State: Enabled 	fields               Name: Additionnal fields             Version: 1.12.9     State: Installed / not activated 	advancedplanning     Name: advancedplanning               Version: 1.0.0      State: Enabled 	news                 Name: Alerts                         Version: 1.9.1      State: Installed / not activated 	cleanarchivedemails  Name: Archived eMail clean           Version: 2.0.0      State: Installed / not activated 	impacts              Name: Asset impacts                  Version: 2.0.5      State: Enabled 	barcode              Name: Barcode                        Version: 2.6.2      State: Installed / not activated 	behaviors            Name: Behaviours                     Version: 2.5.1      State: Enabled 	positions            Name: Cartography                    Version: 5.0.0      State: Installed / not activated 	cmdb                 Name: CMDB                           Version: 2.2.1      State: Enabled 	consumables          Name: Consumable request             Version: 1.6.0      State: Installed / not activated 	dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled 	datainjection        Name: Data injection                 Version: 2.9.0      State: Installed / not activated 	databases            Name: Databases                      Version: 2.3.2      State: Enabled 	archimap             Name: Diagrams                       Version: 3.1.0      State: Enabled 	manageentities       Name: Entities portal                Version: 3.2.2      State: Installed / not activated 	environment          Name: Environment                    Version: 2.4.2      State: Enabled 	escalade             Name: Escalation                     Version: 2.7.2      State: Installed / not activated 	father               Name: Father&Sons                Version: 1.2.0      State: Installed / not activated 	formcreator          Name: Form Creator                   Version: 2.12.4     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled 	gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Installed / not activated 	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled 	resources            Name: Human Resources                Version: 2.7.0      State: Installed / not activated 	geninventorynumber   Name: Inventory number generation    Version: 2.5.1      State: Enabled 	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled 	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.7.2      State: Enabled 	jsaddons             Name: JS Addons                      Version: 1.0.0      State: Not installed 	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.2      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.7.3      State: Enabled 	satisfaction         Name: More satisfaction              Version: 1.5.2      State: Installed / not activated 	moreticket           Name: More ticket                    Version: 1.6.1      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.8.2      State: Enabled 	genericobject        Name: Objects management             Version: 2.11.0     State: Installed / not activated 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Enabled 	officeonline         Name: Office Online                  Version: 2.0.2      State: Enabled 	onetimesecret        Name: OneTimeSecret                  Version: 1.1.1      State: Enabled 	order                Name: Orders management              Version: 2.7.5      State: Enabled 	pdf                  Name: Print to pdf                   Version: 2.0.0      State: Enabled 	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Enabled 	reports              Name: Reports                        Version: 1.14.1     State: Enabled 	reservation          Name: Reservation                    Version: 2.3.8      State: Enabled 	room                 Name: Rooms                          Version: 3.1.3      State: Enabled 	screenshot           Name: Screenshot                     Version: 1.1.6      State: Installed / not activated 	statecheck           Name: Statecheck Rules               Version: 2.2.3      State: Installed / not activated 	tag                  Name: Tag Management                 Version: 2.8.1      State: Installed / not activated 	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled 	tasklists            Name: Tasks list                     Version: 1.6.2      State: Installed / not activated 	ticketcleaner        Name: Ticket Cleaner                 Version: 3.0.0      State: Installed / not activated 	timelineticket       Name: Timeline of tickets            Version: 9.5+1.1    State: Installed / not activated 	timesheet            Name: Timesheet for GLPI             Version: 1.0.1      State: Not installed 	treeview             Name: Tree view                      Version: 1.9.1      State: Installed / not activated 	useditemsexport      Name: Used items export              Version: 2.4.0      State: Enabled 	webapplications      Name: Web applications               Version: 3.0.2      State: Enabled 	webresources         Name: Web Resources                  Version: 1.3.2      State: Installed / not activated 	yagp                 Name: yagp                           Version: 1.2.0      State: Enabled

Host: haproxyConnection: OkUse the OCSNG software dictionary: No
[/code]

</body>
</html>

**Comment by cconard96** [comment]
Tested on GLPI 10 (would be the next release) and I couldn't recreate the issue. I switched back to 9.5.7 and tried the steps listed and it still created the items I listed. This worked even with multiple empty lines at the bottom of the list.

As I was writing this though, I tested one last time on 9.5.7 and this time it did have the reported issue. The cause seemed to be if the Kanban had a background refresh while the bulk add form was open and not related to the empty line.
