### ISSUE TITLE
missing traslation entries  GLPI10 RC2

### ISSUE THREAD

**Issue by bolivarf** [glpi-project/glpi#10916]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0-rc2

### Bug description

Very good days
What needs to be done to request that the following missing GLPI10 entries be included in the transifex GLPI Project, perhaps as standard input?

#: src/Html.php:5490
msgid "File(s)"

#: src/Html.php:5517
msgid "Drag and drop your file here, or"

#: src/Html.php:6529
msgid "Go to menu"

#: src/Html.php:6530
msgid "Start typing to find a menu"

#: src/Html.php:6532
msgid "Tip: You can call this modal with %s keys combination"

#: templates/components/itilobject/service_levels.html.twig:44
msgid "TTO"

#: templates/components/itilobject/service_levels.html.twig:52
msgid "TTR"

#: templates/components/itilobject/service_levels.html.twig:64
msgid "Internal TTO"

#: templates/components/itilobject/service_levels.html.twig:65
msgid "Internal Time to own"

#: templates/components/itilobject/service_levels.html.twig:72
msgid "Internal TTR"

#: templates/components/itilobject/service_levels.html.twig:73
msgid "Internal Time to resolve"

### Steps To reproduce

1.Login 
2. change language
3. check the language in find menu -> dialog window
4. check the language in in Assistance -> create ticket -> service level

**Comment by bolivarf** [comment]
**also missing**

#: src/Ticket.php:169
#: src/Ticket.php:171
#: src/Ticket.php:5509
#: src/Dashboard/Grid.php:1169
msgid "Tickets waiting for your approval"

**Comment by cedric-anne** [comment]
Should be fixed by #10923.

**Comment by bolivarf** [comment]
I think you stay without updating

#: templates/components/itilobject/service_levels.html.twig:52
msgid "TTR"

#: templates/components/itilobject/service_levels.html.twig:64
msgid "Internal TTO"

#: templates/components/itilobject/service_levels.html.twig:72
msgid "Internal TTR"

**Comment by cedric-anne** [comment]
Indeed, extraction of strings from Twig have to be fixed :/

**Comment by cedric-anne** [comment]
Missing translations have been pushed to Transifex service.
