### ISSUE TITLE
GLPI-Inventory Field missing in computer view

### ISSUE THREAD

**Issue by e-novinfo-it** [glpi-project/glpi#10918]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.0-rc2

### Bug description

Hello, 
In previous version of GLPI 9.5 with Fusion Inventory Plugins.
It was possible to add column and search in computer list view (front/computer.php) directly with the field from the inventory like "Last Inventory". 

For more details see attachment.

Do you have the project to add this feature again ?

Thanks in advance best regards

![2022-03-08_19-16-06](https://user-images.githubusercontent.com/98420294/157300517-663dcfaf-b0d1-4722-81c6-33c31877c2fa.png)

![2022-03-08_19-16-34](https://user-images.githubusercontent.com/98420294/157300500-291d4675-4971-48af-aa44-e5fa9d686ec0.png)

### Page URL

front/computer.php

**Comment by e-novinfo-it** [comment]
Hello,
Wow I'm impressed by your reactivity.
I have check your commit and I see you have added a new field in the table GLPI_COMPUTERS, but the field already exist in the table glpi_plugin_glpiinvnetory_inventorycopmputercomputers field : last_fusioninventory_update.
Best regards

**Comment by trasher** [comment]
As far as I've seen, this table should no longer be used; its data should probably be migrated

**Comment by e-novinfo-it** [comment]
Yes you're right, I think the field in the image seems to be stored in the JSON file (I don't find it in the database) do you think that is possible to fill the the field last_inventory_update when the inventory is made ?

https://user-images.githubusercontent.com/98420294/157300500-291d4675-4971-48af-aa44-e5fa9d686ec0.png

**Comment by trasher** [comment]
> fill the the field last_inventory_update when the inventory is made ?

It should already be OK with #10920; https://github.com/glpi-project/glpi-inventory-plugin/pull/64 will take care of data migration from fi plugin
