### ISSUE TITLE
[10-RC2] user profil for validation requires "create" to be able to validate

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#10929]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-RC2

### Bug description

As a user who only has the right to validate tickets, I can no longer accept or refuse a request.

![image](https://user-images.githubusercontent.com/470612/157432527-366f85d2-0852-400d-8f7e-8939e0714334.png)

To be able to use "Accept / Reject" buttons again, I must also have the right to "Create a validation request".

### Steps To reproduce

1. create a new "validator" profil in standard interface
2. give only the rights (See my tickets, See public follow-ups, Validate a request, Validate an incident)
3. create a user linked to this profile, then create a ticket and send a validation request to this user
4. login with this new validator user, find that it's not possible to validate (screenshot)
5. modify the "validator" profile and add "Create for a request" (or incident) right
6. login again with the validator user, see that it's now possible to validate the request

### Anything else?

In precedent 9.5 version it works with only "Validate" right (no need to have "create a validation request" right)

**Comment by Jean72cgi** [comment]
bonjour,
le statut reste en "attente de validation" malgrès l'acceptation et le passage a 100%.
est-ce qu'une correction est prévue?
