### ISSUE TITLE
[GLPI 10.0 RC2]  glpi:migration:unsigned_keys :  cannot be done as it contains negative values on two data

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10936]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 RC2

### Bug description

Description Migration : php bin/console glpi:migration:unsigned_keys

Migration of column "glpi_plugin_news_alerts_targets.items_id" cannot be done as it contains negative values.
Migration of column "glpi_queuednotifications.items_id" cannot be done as it contains negative values.

I have this probleme on older Version GLPI 10 beta and RC1.

To solve this problem I modify my data with phpmyadmin
![image](https://user-images.githubusercontent.com/68054991/157620365-de4b826a-d55d-4286-8a03-ee20d98c0adb.png)
![image](https://user-images.githubusercontent.com/68054991/157620767-5e74b94b-e798-4276-a84b-f6e69777ed1e.png)

### Steps To reproduce

Migration of Data 9.5.7 === 10.0 RCx

**Comment by cconard96** [comment]
The issue with the News plugin table should be fixed if you update the plugin to the [1.10.0-rc2](https://github.com/pluginsGLPI/news/releases/tag/1.10.0-rc2) version before attempting the migration.
