### ISSUE TITLE
[GLPI 10.0.0-rc2]  ITIL objects UI

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#10931]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

CSS or better say overall design of ITIL objects does not fit well with the new GLPI10 UI.
I've tried several displays with various DPI but somewhere it looks better somewhere worse but overall I think too much space is wasted. As new UI does not leave much space for ITIL objects. IMHO worst is that just 25% is left for the part where most information is displayed. This screenshot shows defaults in Windows10  1920x1080 screen (somewhat better is other OSes and DPIs but not much):
![image](https://user-images.githubusercontent.com/71901245/157445235-31c52a28-596d-4c40-bcd9-804aed30e3f0.png)

Maybe putting controls below the text area would make more space:

![image](https://user-images.githubusercontent.com/71901245/157445915-200a978c-b079-458c-bd74-25df4af410b3.png)

Or any other idea how to deal with it? Yes collapsing the side bars gives more space but I suppose this was not the intention of new UI to have users always repeat it for each ticket and see less than in 9.5.x.

### Steps To reproduce

1. Create new Ticket
2. Add new Task to the ticket, click "Plan the Task"

### Your GLPI setup information

GLPI 10.0.0-rc2
Plugins: 
Formcreator
Fields

**Comment by cedric-anne** [comment]
Hi,

#10943 should enhance this view.
