### ISSUE TITLE
No licence menu after update.

### ISSUE THREAD

**Issue by FabRons** [glpi-project/glpi#1094]
Hi Team,

I updated my GLPI in production today.
We was really interested by Dedicated page for licence managament.

But after clearing my cache I can't see this new menu, update didn't return any error, and my version is 9.1

I need to activate it?

Thank you.

Best Regards,

Fabien.

Config: 
CentOS Linux release 7.2.1511
PHP 5.4.16
Zend Engine v2.4.0
Zend OPcache v7.0.5
mysql  Ver 15.1 Distrib 5.5.47-MariaDB

**Comment by orthagh** [comment]
Hello @FabRons 

We have an issue with licences and dedicated right, see #1072.

Waiting for 9.1.1, you could add manually in the profiles the missing right.
