### ISSUE TITLE
[glpi 9.5.7] tickets followup upload picture 1M failed

### ISSUE THREAD

**Issue by jjk334** [glpi-project/glpi#10948]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.7

### Bug description
tickets followup upload picture 1M there is this problem

![image](https://user-images.githubusercontent.com/77146761/157813230-77b77b65-0a97-475d-8c96-a0c96003906b.png)
![image](https://user-images.githubusercontent.com/77146761/157813261-97b8ff95-cb8c-4c7d-8d6c-bb85d1a08e46.png)

**Comment by jjk334** [comment]
tickets followup upload picture 1M  there is this problem

**Comment by cedric-anne** [comment]
Fixed by #8180.

**Comment by jjk334** [comment]
hello
my glpi version 9.5.7
php upload_max_filesize = 100M

picture upload is success,but followup not display picture 
![image](https://user-images.githubusercontent.com/77146761/157838517-f412389d-8791-451f-bc76-a2c779f366b1.png)

**Comment by cconard96** [comment]
Tested on GLPI 10 by dragging and dropping a 1.3 MB image into a task and saving. Image was uploaded correctly and displaying OK in the task.
Can you check for warnings/errors in `files/_log/php-errors.log`?

Does the upload itself work (does the image show in the Documents section in GLPI)?

**Comment by jjk334** [comment]
can you try glpi 9.5.7

**Comment by jjk334** [comment]
hello, this problem exists in GLPI 10.0.0-rc2。
![image](https://user-images.githubusercontent.com/77146761/158112301-7fbab083-f847-40d2-b435-7b1af61ad6be.png)

**Comment by cedric-anne** [comment]
Hi,

I tried on my side with a 2MB jpg image and was not able to reproduce.

1) Can you attach here a file that cause this issue ?
2) What is your PHP version and your system configuration ?

**Comment by jjk334** [comment]
hello!
PHP 7.4.28
CentOS Linux release 7.9.2009 (Core)  kernel-3.10.0-1160.49.1.el7.x86_64

picture url：
http://220.231.216.65:9999/front/document.send.php?docid=6

test environment：
http://220.231.216.65:9999/
test
Test@33446677

**Comment by cedric-anne** [comment]
Your URLS are not accessible for me. Please attach the image here.

**Comment by jjk334** [comment]
Sorry, the firewall forgot to let it go
you can try

**Comment by jjk334** [comment]
![5da291fdcd8258 30336390image_paste1383375](https://user-images.githubusercontent.com/77146761/158139789-2587c1b7-1e7a-445e-8d29-a631869f66fe.png)

**Comment by cedric-anne** [comment]
I cannot reproduce on my machine, which runs on PHP 8.1.

Many operations related to HTML processing are done using PHP regex engine. Maybe it can be impacted by `pcre.backtrack_limit` PHP configuration, but I am not sure of that.

**Comment by jjk334** [comment]
Ok, I'll try it on PHP 8.1 next.

**Comment by jjk334** [comment]
hello
I update php 8.1.3,but this problem also exists .
test environment：
http://220.231.216.65:9999/
test
Test@33446677

**Comment by cedric-anne** [comment]
I guess the issue is reproducible only on a specific environment.

Do you think it is possible for you to produce a docker image that can be used to reproduce the issue ? With this, I could be able to do some debug.

**Comment by jjk334** [comment]
OK,  I'll try docker image

**Comment by stonebuzz** [comment]
Hi @jjk334 have you try with docker image ?

Best regards

**Comment by stonebuzz** [comment]
Hi @jjk334 
increase ```pcre.backtrack_limit``` from ```php.ini``` solves the problem.

Best regards
