### ISSUE TITLE
Problem with case sensitive in  Fields unicity and Search

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#10955]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

There is a problem with  Fields unicity uppercase and lowercase serial numbers, it is also possible that the names and other parameters are case sensitive.
The rule does not treat them as duplicates.

The same is with search

**Comment by cedric-anne** [comment]
Hi,

I quickly look at the code and, unless I miss something, duplication checks are done using SQL queries. As DB connection charset is forced by ```SET NAMES 'utf8' COLLATE 'utf8_unicode_ci'```, comparisons should be case insensitive.

Could you please provide steps to reproduce ?
Could you also give you MySQL configuration values related to charset/collation ?

I tried to reproduce using following rule, but item creation/update was refused as expected.

![image](https://user-images.githubusercontent.com/33253653/157868720-0253bdc0-8cd6-4d38-adb9-cb001c62b42d.png)
![image](https://user-images.githubusercontent.com/33253653/157868689-382b8c6f-4e9c-4190-abfb-cd1f444f0c42.png)

**Comment by Wolvverine** [comment]
Problem solved. Looks like a problem with the rules. Application until closing.
