### ISSUE TITLE
[GLPI 10.0.0-rc2] [error] [http client] answer without content

### ISSUE THREAD

**Issue by al-lespiauc** [glpi-project/glpi#10959]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

I have a problem during the task inventory process (with the 1.2 GLPI Agent) on most of my computers (GLPI version 10.0.0-rc2) ; here is the error :

[Fri Mar 11 14:45:00 2022][info] running task ESX
[Fri Mar 11 14:45:00 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Fri Mar 11 14:45:00 2022][info] ESX task not supported by server0
[Fri Mar 11 14:45:02 2022][info] running task Deploy
[Fri Mar 11 14:45:02 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Fri Mar 11 14:45:02 2022][info] Deploy task not supported by server0
[Fri Mar 11 14:45:07 2022][info] running task Inventory
[Fri Mar 11 14:45:07 2022][info] New inventory from LI-PORT-BS.LI.intra-2022-03-11-14-44-57 for server0 (tag=LI)
**_[Fri Mar 11 14:45:31 2022][error] [http client] answer without content_**
[Fri Mar 11 14:45:35 2022][info] running task Collect
[Fri Mar 11 14:45:35 2022][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Fri Mar 11 14:45:35 2022][info] Collect task not supported by server0

I get the error message every time : "answer without content".

Some info about the server configuration and the research I did :
- The server was originally in 9.5.5, which I upgraded to 10.0.0-rc1 then to 10.0.0-rc2 (none of the two versions solved my problem), working with the FusionInventory plugin.
- I tried many versions of the GLPI Agent (1.0, 1.1, 1.2, even the latest nightly build)
- The latest FusionInventory plugin is still working (if I send the data to the new URL - https://myserver/glpi/front/inventory.php), but the tag I indicate does not appear in GLPI.
- The agent only works on one computer of the company (mine actually).
- Manual import of the XML generated by the agent does not create the computers in the GLPI fleet either.
- I also tried with the GLPI Inventory plugin (and not the native one) ; same error, i only get rid of the 400 Bad Request Protocol errors.

I checked the php-errors.log and I encounter an error at the same time as that of the agent, which sends me to the Inventory folder, file "Software.php" (line 591)

I still have the backup of my GLPI 9.5.5 with FusionInventory in case I need to get back to this version, or for test purposes if needed.

### Relevant log output

```shell
php-errors.log :

[2022-03-11 14:45:31] glpiphplog.CRITICAL:   *** Uncaught Exception ArgumentCountError: The number of elements in the type definition string must match the number of bind variables in /usr/share/glpi/src/Inventory/Asset/Software.php at line 591
  Backtrace :
  src/Inventory/Asset/Software.php:591               mysqli_stmt->bind_param()
  src/Inventory/Asset/Software.php:333               Glpi\Inventory\Asset\Software->storeSoftware()
  src/Inventory/Asset/MainAsset.php:760              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:681              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:954                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1503                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1588                        Rule->process()
  src/Inventory/Asset/MainAsset.php:515              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:665                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:312                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:83                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:219    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:67                             Glpi\Agent\Communication\AbstractRequest->handleRequest()


Software.php, line 591 :

        $software->handleCategoryRules($stmt_columns);
        $stmt_values = array_values($stmt_columns);
        $stmt->bind_param($stmt_types, ...$stmt_values);
        $DB->executeStatement($stmt);
        $softwares_id = $DB->insertId();
        $this->softwares[$skey] = $softwares_id
```

### Anything else?

_No response
[XML OK.txt](https://github.com/glpi-project/glpi/files/8303982/XML.OK.txt)
[XML Error.txt](https://github.com/glpi-project/glpi/files/8303985/XML.Error.txt)
_

**Comment by cedric-anne** [comment]
Hi,

Could you attach an inventory XML file that can be used to reproduce this issue?

**Comment by trasher** [comment]
It seems there is one (at least) software that is missing an info :/ Your inventory should be OK if you exclude software.

We need at least a list of software nodes that permit to reproduce the issue if you do not want to provide the full inventory.

**Comment by al-lespiauc** [comment]
No problem, I uploaded two XML Inventories (in .txt format because I couldn't upload XML files) - the first one can be uploaded on GLPI manually, the other generates an error, if you want to compare.

**Comment by trasher** [comment]
I do not have any errors with an up to date glpi master. Could you try if you reproduce with latest nightly?

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by jeremydubuc** [comment]
![image](https://user-images.githubusercontent.com/116254071/208939405-481fdeba-75b0-43b3-80f7-08d4b246ec2c.png)
Hello,
same problem no solution anyone have an idea?
