### ISSUE TITLE
[GLPI 10.0.0 RC.2] OCSInventory plugin bug

### ISSUE THREAD

**Issue by Chaniac** [glpi-project/glpi#10962]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0 RC2

### Bug description

Hello,

I configured the OCSInventory server on GLPI with the right identifiers, the right passwords and the right IP addresses except that each time, it answers me that while on GLPI 9.5.6 it works. Is this normal? 

![image](https://user-images.githubusercontent.com/57410982/158056268-ed6c956d-3e54-4e0c-818e-c89fe7324518.png)

### Your GLPI setup information

Operating system: Linux LAPCORP 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Debian) (Apache/2.4.52 (Debian) Server at 192.168.0.38 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 OPR/83.0.4254.70
Server Software: Debian 11
	Server Version: 10.5.12-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpibdd@localhost/glpidb
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
Please ask OCSInventory plugin team
