### ISSUE TITLE
[GLPI 10.0 RC2 + glpinventory] : the ips of printers  dont displayed correctly after the SNMP function

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10960]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 RC2

### Bug description

When I perform a network discovery of the printers, the ips are displayed correctly but with the SNMP function the ips are erased. I don't have any error logs.

It seems to me it worked with an old version glpi 10. 

Example in the image : 

1. decouverte reseau : display IP OK
![image](https://user-images.githubusercontent.com/68054991/157892115-5fc4a8d8-52f4-4630-a2c5-64f6a589b8af.png)
![image](https://user-images.githubusercontent.com/68054991/157891862-e125a9d4-f119-46a6-aad6-1490ee62c471.png)

2. Inventaire reseau SNMP : display KO, No IP
![image](https://user-images.githubusercontent.com/68054991/157892215-6eddce98-1956-4c3e-8685-19c56e55b4c9.png)
![image](https://user-images.githubusercontent.com/68054991/157893393-6fe7b068-c9b7-45a3-970c-03954f053c85.png)

if I run the discovery function a second time, the IPs are displayed

The network hardware, I don't have this problem only with the printers snmp

I don't know if it's server or plugin side

### Relevant log output

```shell
No log
```

### Page URL

/front/printer.php

### Steps To reproduce

1. Execute network discovery OK
2. Execute fonction SNMP Ko

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-rc2 (/glpi10beta => /var/www/html/glpi10beta)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux srv-glpi 3.10.0-1160.53.1.el7.x86_64 #1 SMP Fri Jan 14 13:59:45 UTC 2022 x86_64
PHP 8.0.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="5M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.6 (CentOS) PHP/8.0.16 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi10beta
	Host info: Localhost via UNIX socket
	
PHP version (8.0.16) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi10beta/files/_cache has been validated.
Write access to /var/www/html/glpi10beta/config has been validated.
Write access to /var/www/html/glpi10beta/files/_cron has been validated.
Write access to /var/www/html/glpi10beta/files has been validated.
Write access to /var/www/html/glpi10beta/files/_dumps has been validated.
Write access to /var/www/html/glpi10beta/files/_graphs has been validated.
Write access to /var/www/html/glpi10beta/files/_lock has been validated.
Write access to /var/www/html/glpi10beta/files/_pictures has been validated.
Write access to /var/www/html/glpi10beta/files/_plugins has been validated.
Write access to /var/www/html/glpi10beta/files/_rss has been validated.
Write access to /var/www/html/glpi10beta/files/_sessions has been validated.
Write access to /var/www/html/glpi10beta/files/_tmp has been validated.
Write access to /var/www/html/glpi10beta/files/_uploads has been validated.
Web access to files directory is protected
For security reasons, SELinux mode should be Enforcing.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi10beta/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi10beta
GLPI_CONFIG_DIR: /var/www/html/glpi10beta/config
GLPI_VAR_DIR: /var/www/html/glpi10beta/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi10beta/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi10beta/files
GLPI_CACHE_DIR: /var/www/html/glpi10beta/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi10beta/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi10beta/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi10beta/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi10beta/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi10beta/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi10beta/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi10beta/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi10beta/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi10beta/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi10beta/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi10beta/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi10beta/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi10beta/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi10beta/locales
GLPI_VERSION: 10.0.0-rc2
GLPI_SCHEMA_VERSION: 10.0.0-rc2@f37056b10231ef9a2762d00ee094fbeb60752694
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi10beta/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi10beta/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi10beta/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi10beta/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi10beta/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi10beta/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi10beta/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi10beta/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi10beta/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi10beta/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi10beta/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi10beta/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi10beta/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi10beta/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi10beta/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi10beta/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi10beta/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi10beta/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi10beta/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi10beta/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi10beta/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi10beta/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi10beta/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi10beta/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi10beta/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi10beta/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi10beta/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi10beta/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi10beta/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi10beta/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi10beta/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi10beta/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi10beta/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi10beta/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi10beta/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi10beta/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi10beta/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi10beta/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi10beta/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
phpCas version 1.4.0 in (/usr/share/pear)

</details><details><summary>SQL replicas</summary><pre> 
Not active
</details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.0-rc2  State: Enabled
	advancedplanning     Name: advancedplanning               Version: 1.1.0-rc1  State: Enabled
	datainjection        Name: Data Injection                 Version: 2.10.0-rc2 State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0-rc6  State: Enabled

</pre></details>

### Anything else?

it seems to me, it worked on an old glpi 10 version.

**Comment by steph461** [comment]
@cedric-anne @trasher  for more information :


this phase will be explicit : Test last GLPI and plugin

1. before migration of the 9.5.7 database
![image](https://user-images.githubusercontent.com/68054991/159702295-55bd57fe-945c-4872-951d-61d67777b6ef.png)

2. After migration 9.5.7 RC3 and plugin rc7
![image](https://user-images.githubusercontent.com/68054991/159702460-73c23bfa-e402-43d7-98a5-d39f5e1ae8c0.png)
![image](https://user-images.githubusercontent.com/68054991/159702661-6e6ff08e-011e-4691-ac7d-6ee7d7850335.png)

3. after SNMP inventory wiht add eth0 (green) and eth0 (black) and port management ?
![image](https://user-images.githubusercontent.com/68054991/159704308-4e0e93b7-928c-4250-94dc-2172a61f1e49.png)

4. ETH0 BLACK
![image](https://user-images.githubusercontent.com/68054991/159704421-25ac0c43-34b0-4e72-b298-05c3585c279d.png)
![image](https://user-images.githubusercontent.com/68054991/159704818-c90f4492-d1ff-4ae0-a2ec-e80a2b271737.png)

5.ETH0 GREEN
![image](https://user-images.githubusercontent.com/68054991/159704692-2660d839-91b7-4d1a-9d0a-3a3ec78cc9cd.png)
![image](https://user-images.githubusercontent.com/68054991/159705735-9c2d01aa-0a6c-476e-b478-3fc2d1c4958a.png)

I have the impression, there is a duplicate of eth0 and the address is not set correctly
the ip are erased or double, it depens of methode SNMP
![image](https://user-images.githubusercontent.com/68054991/159706769-2efe5e10-700c-4c5d-b1d3-e5bb0c12dadf.png)
![image](https://user-images.githubusercontent.com/68054991/159706838-1afe4cc3-edf4-4d10-8b13-3338da5199a1.png)

**Comment by steph461** [comment]
Issue https://github.com/glpi-project/glpi-inventory-plugin/issues/53#issuecomment-1092640998
you can merge this issue

**Comment by cedric-anne** [comment]
Hi,

Could you try with [latest nightly build](https://nightly.glpi-project.org/glpi/) ?

**Comment by steph461** [comment]
it's OK for the etho green display but there is still the ip display bug. It's triple this time 


![image](https://user-images.githubusercontent.com/68054991/163981833-d550fecc-ec0a-4ef5-bdbd-0da8f3e8c1ed.png)
https://github.com/glpi-project/glpi-inventory-plugin/issues/53#issuecomment-1092640998

**Comment by steph461** [comment]
![image](https://user-images.githubusercontent.com/68054991/164168714-0fec3fb7-6451-4268-a763-c1e8c0c128fa.png)

**Comment by WebGregGit** [comment]
This is not exactly the same problem, but there are quite a few fixes that have not yet been implemented. Maybe it will help someone. [https://github.com/glpi-project/glpi-inventory-plugin/issues/192](https://github.com/glpi-project/glpi-inventory-plugin/issues/192)
