### ISSUE TITLE
ticket - save current search issue

### ISSUE THREAD

**Issue by spikey80** [glpi-project/glpi#10974]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc2

### Bug description

i can't save any search in tickets page

### Page URL

glpi/front/ticket.php

### Steps To reproduce

1. no particular config
2. go to tickets page
3. clic on "save current search"

![image](https://user-images.githubusercontent.com/101607801/158281880-1c477be2-feb5-4777-b6ee-3da7f3d49b15.png)

### Your GLPI setup information

Operating system: Linux bdp-l-is2130 4.18.0-305.el8.x86_64 #1 SMP Thu Apr 29 08:54:30 EDT 2021 x86_64
PHP 7.4.6 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.37 (Red Hat Enterprise Linux) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.50
Server Software: Source distribution
	Server Version: 8.0.21
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuser@localhost/glpi10rc2
	Host info: Localhost via UNIX socket
	
PHP version (7.4.6) is supported.PHP version (7.4.6) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.21) is supported.Database engine version (8.0.21) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi10rc2/files/_cache has been validated. Write access to /var/www/html/glpi10rc2/config has been validated. Write access to /var/www/html/glpi10rc2/files/_cron has been validated. Write access to /var/www/html/glpi10rc2/files has been validated. Write access to /var/www/html/glpi10rc2/files/_dumps has been validated. Write access to /var/www/html/glpi10rc2/files/_graphs has been validated. Write access to /var/www/html/glpi10rc2/files/_lock has been validated. Write access to /var/www/html/glpi10rc2/files/_pictures has been validated. Write access to /var/www/html/glpi10rc2/files/_plugins has been validated. Write access to /var/www/html/glpi10rc2/files/_rss has been validated. Write access to /var/www/html/glpi10rc2/files/_sessions has been validated. Write access to /var/www/html/glpi10rc2/files/_tmp has been validated. Write access to /var/www/html/glpi10rc2/files/_uploads has been validated.Write access to /var/www/html/glpi10rc2/files/_cache has been validated.
Write access to /var/www/html/glpi10rc2/config has been validated.
Write access to /var/www/html/glpi10rc2/files/_cron has been validated.
Write access to /var/www/html/glpi10rc2/files has been validated.
Write access to /var/www/html/glpi10rc2/files/_dumps has been validated.
Write access to /var/www/html/glpi10rc2/files/_graphs has been validated.
Write access to /var/www/html/glpi10rc2/files/_lock has been validated.
Write access to /var/www/html/glpi10rc2/files/_pictures has been validated.
Write access to /var/www/html/glpi10rc2/files/_plugins has been validated.
Write access to /var/www/html/glpi10rc2/files/_rss has been validated.
Write access to /var/www/html/glpi10rc2/files/_sessions has been validated.
Write access to /var/www/html/glpi10rc2/files/_tmp has been validated.
Write access to /var/www/html/glpi10rc2/files/_uploads has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
exif extension is installed.exif extension is installed.
ldap extension is not present.ldap extension is not present.
openssl extension is installed.openssl extension is installed.
zip extension is not present.zip extension is not present.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /var/www/html/glpi10rc2/marketplace has been validated.Write access to /var/www/html/glpi10rc2/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cedric-anne** [comment]
Hi,

Duplicates #10924 and fixed by #10927.
