### ISSUE TITLE
Sync Active Directory users problem GLPI 9.5.7

### ISSUE THREAD

**Issue by benoit33260** [glpi-project/glpi#10971]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Hi,
Since today, I can no longer synchronise Active Directory users in GLPI. It is also no longer possible to authenticate with it.
I was in version GLPI 9.5.5 and I updated to 9.5.7 thinking that it would fix the problem.
The LDAP configuration has not changed and the connection test works.
Here is what I get when I run the synchronization:

![image](https://user-images.githubusercontent.com/77024616/158262078-20c325e5-7852-4846-971a-a400c98549a6.png)

### Your GLPI setup information

Operating system: Linux serverglpi 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
PHP 7.4.16 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at 192.168.10.4 Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Server Software: mariadb.org binary distribution
	Server Version: 10.5.9-MariaDB-1:10.5.9+maria~buster
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.9) - Perfect!Database version seems correct (10.5.9) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.Write access to /var/www/glpi/files/_uploads has been validated.
Write access to /var/www/glpi/marketplace has been validated.Write access to /var/www/glpi/marketplace has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

**Comment by cedric-anne** [comment]
> Since today, I can no longer synchronise Active Directory users in GLPI. It is also no longer possible to authenticate with it.

Did you changed something on your GLPI server ? If it was working from a long time and then stops working without changing anything on the GLPI server, then it is probably not a bug in GLPI.

In this case, I am not sure we can help.

**Comment by benoit33260** [comment]
These are the only things that have been done:
- templates modifications for email ticket notifications on the GLPI server
- On our Active Directory server, we have implemented a security policy that enforces password policy. Users must change their passwords every 6 months.
The AD account used in GLPI for synchronisation is not impacted by this change, and the connection works.
It is only the synchronisation of users that is not done.

Another element:
On the same server, I do a fresh install of GLPI, and I have the same problem: I add the LDAP parameters and everything works the fist time, the users are synchronized. When I modify a parameter in the LDAP options, for example I put back the password, it doesn't work anymore (the connection test is OK, but the users don't synchronize anymore).

This is very strange!

Test is OK:

![image](https://user-images.githubusercontent.com/77024616/158363337-b32603c2-8d5c-474c-b74e-cef8af98ce0e.png)

But no user sync:

![image](https://user-images.githubusercontent.com/77024616/158363267-4e996cc9-d330-4fef-a820-1a123a56801f.png)

**Comment by bastien33260** [comment]
I have a strong feeling this isn't coming from GLPI itself. I tried installing both latest GLPI 9 and 10 on a VM and I could get neither to synchronize despite trying many accounts : Administrator, GLPI dedicated account with admin privileges, another that I created as a test, my own... I noticed that if you tick the "Delete password" box and save, it erases the password even if you type something in the field next to it.
![image](https://user-images.githubusercontent.com/101653155/158407042-b4f9f829-6489-4d0a-8a88-2c2c50b4eec2.png)


A weird behavior is when you write the right password and testing the sync fails (in the next tab), but if you tick the delete password box, save and try to sync it says the test is successful? Why would the test be successful if there is no password but it would fail is there is one?

Is there a way to see detailed logs of GLPI? We have absolutely no clue where this could be coming from. We checked the apache error logs and we couldn't find a single mention of the issue (despite the LogLevel being set to info). Even by using the integrated script at /var/www/glpi/scripts/ldap_mass_sync.php the only output we get is "Cannot contact LDAP server!". This is extremely hard to debug anything with so little info.... There must be some sort of info that could help us figure out why this doesn't work, even if this isn't coming from GLPI.

Thank you for your answers.

**Comment by benoit33260** [comment]
Finally, the problem was with the new GPO.
The "Domain controller: LDAP server signing requirements" parameter must be set to "None".

![image](https://user-images.githubusercontent.com/77024616/158684384-467e31d1-924e-40d7-8012-00e60f7f29f9.png)


Everything is working now
