### ISSUE TITLE
[GLPI 10.0 RC2] Printer : Bug display printer counter and cartridge after migration

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#10981]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0 RC2

### Bug description

This bug after migration but if new printer the display its OK

Bug display Counter printer
![image](https://user-images.githubusercontent.com/68054991/158415746-4c79b076-f72b-4aa5-bd61-4203588c84e4.png)

Bug display cartridge on the number
![image](https://user-images.githubusercontent.com/68054991/158416011-79e1aa20-a53d-4ee2-852b-5c088748e7d5.png)

new add printer OK
![image](https://user-images.githubusercontent.com/68054991/158416351-ee9ff1f3-e44b-42d5-846c-f7b73daccc0d.png)

### Relevant log output

```shell
no log
```

### Page URL
/front/printer.form.php?id=xx

_No response_

**Comment by steph461** [comment]
I have test this handling

i do request  DELETE FROM glpi_printerlogs 
I do taskjobs of my printers snmp, i dont Bug display printer counter

 I think there is one issue on this table

**Comment by cedric-anne** [comment]
Hi,

Problem appears when there is too many days displayed on the chart.

Many solutions to this:
 - only display the X last entries,
 - display all entries, but find a solution to display only appropriate labels on X axis (appropriate labels may depend on the displayed data range).

**Comment by cedric-anne** [comment]
Fixed by #12529.
