### ISSUE TITLE
impossible to rename the Root entity

### ISSUE THREAD

**Issue by Pieurre** [glpi-project/glpi#10984]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

d007723ac7fe7812431db645bcccfb79b229d94e

### Bug description

I can't rename the root entity, like: 

![image](https://user-images.githubusercontent.com/6872020/158582313-f2796a54-6de2-4ac9-82a0-b5d847a014eb.png)

After saving :

![image](https://user-images.githubusercontent.com/6872020/158582397-eb15dd05-c31c-43ca-a511-811f713e416f.png)

### Relevant log output

```shell
nothing
```

**Comment by orthagh** [comment]
Seems to be related to a cache issue, a reset fixed it
