### ISSUE TITLE
 None or Invalid host in HTTP_REFERER. Reload previous page before doing action again.

### ISSUE THREAD

**Issue by TPei** [glpi-project/glpi#1099]
Hello, 

after step 1 (database access) I get redirected and immediately encounter the following error page:
`None or Invalid host in HTTP_REFERER. Reload previous page before doing action again.`

I am using PHP Version 7.0.8-0ubuntu0.16.04.2 with nginx/1.10.0 and had no errors or warnings on the pages before during the setup. Any ideas?

Thanks!

**Comment by remicollet** [comment]
Check nginx configuration, especially

      fastcgi_param  SERVER_NAME      $host;

**Comment by TPei** [comment]
well, `/etc/nginx/fastcgi_params` has a `fascgi_param SERVER_NAME $server_name;` line. Changing that to `fascgi_param SERVER_NAME $host;` did not change anything.

**Comment by dragan01** [comment]
I am not expirienced too much with all this, but have same issue. Did you find solution TPei ?

**Comment by TPei** [comment]
Nope, sorry @dragan01. I'm a bit ashamed to admit that I uncommented the HTTP referer validation in the installation.php :laughing:

**Comment by AnaelMobilia** [comment]
For memories, the same occurs on Windows, when you try to install from a path with spaces on name (you can't launch the DB installation...).
Tried with http://localhost/glpi - Copie/install/install.php

@TPei could you, please, provide us the path where you have put glpi ?

Regards,
Anael

**Comment by trasher** [comment]
@AnaelMobilia are you sure you got the exact same message? There are 2 similar messages in this part: one fort `host`, the other for `path`. I do not think the URL you tried throws the `host` one ;)

**Comment by AnaelMobilia** [comment]
@trasher you win ! Nice you point at the word !
I have a path issue...

**Comment by trasher** [comment]
Sounds like a server configuration issue, I'm closing

**Comment by jerdin** [comment]
> well, `/etc/nginx/fastcgi_params` 

/etc.nginx/fastcgi_params**.conf**
fascgi_param SERVER_NAME $host;

solved problem for me
