### ISSUE TITLE
Description disappears from ticket when a reply with attached file is received by an e-mail collector

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#110]
Hi,
It is very simple to reproduce:

1. Open a ticket
2. Wait to receive  the e-mail from glpi
3. Reply from your mailer attaching a file in it (I used a csv file)
4. Take a look at the ticket description once the e-mail collector has retrieved this reply

Thanks.

**Comment by orthagh** [comment]
Not sure of the correction for your case.
Could you test this fix .

**Comment by kabassanov** [comment]
I didn't mention that my GLPI version is 0.85.2. And the function you changed is not the same...

**Comment by orthagh** [comment]
ah ! commit for 0.85 incoming

**Comment by orthagh** [comment]
It's difficult for me to test and fix your your bug in 0.85.2.
You should upgrade to last bugfixes version and test if your issue is still present.

**Comment by kabassanov** [comment]
It's a little bit hard for me to maintain a "working" version of GLPI in a professional environment, and to debug the last version (containing more than bug fixes...) . At least, not at the moment... Will try to check and repair the operational one.

**Comment by kabassanov** [comment]
If you are interested, it seems that the issue is related to:

2015-09-09 10:49:02 [@titi.lip6.fr]
  *** PHP Notice(8): Undefined index: content
  Backtrace :
  inc/commonitilobject.class.php:1607
  inc/ticketfollowup.class.php:287                   CommonITILObject->addFiles()
  inc/commondbtm.class.php:790                       TicketFollowup->prepareInputForAdd()
  inc/mailcollector.class.php:549                    CommonDBTM->add()
  inc/mailcollector.class.php:1525                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:781                         call_user_func()
  front/cron.php:84                                  CronTask::launch()

**Comment by kabassanov** [comment]
OK, I found...

There was a modification some months ago (by tsmr) related to the use_rich_text in function prepareInputForAdd... So if, with this modification, I put this variable in GLPI configuration, my issue does not appear anymore... But why don't fill 'content' without rich text?

if ($CFG_GLPI["use_rich_text"]) { 
          $input['content'] = $input["_job"]->setSimpleTextContent($input["content"]); 
       } 

Thanks.
