### ISSUE TITLE
[GLPI 10] Global search does not look for passive devices

### ISSUE THREAD

**Issue by yes1n** [glpi-project/glpi#11008]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0-rc2

### Bug description

Hey! I enter into the global search the information of an object that is in the passive objects section and the search does not give any results.
Thanks!

### Page URL

https://domain.ru/front/search.php?globalsearch=*

### Steps To reproduce

1. Add an object to the passive devices section
2. Use global search to find this object

### Your GLPI setup information

GLPI 10.0.0-rc2
Installation mode: TARBALL
Current language:ru_RU

**Comment by trasher** [comment]
This is not related to version 10; that feature does not exists in previous versions as far as I know

**Comment by yes1n** [comment]
[cedric-anne](https://github.com/cedric-anne), thank you very much

**Comment by leecheromerevilit** [comment]
@cedric-anne can this be also done on consumableitems?
