### ISSUE TITLE
No title on imported groups from LDAP

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#11028]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v9.5.7

### Bug description

When importing groups from LDAP directory, GLPI don't retrieve titles.

![image](https://user-images.githubusercontent.com/2470104/159225185-4c222eaf-a316-4880-b53f-ece81265156a.png)

![image](https://user-images.githubusercontent.com/2470104/159223945-b7c0c994-7263-43b1-9735-6c723107b1e6.png)

### Steps To reproduce

1. Add a LDAP authentication : Setup > Authentication > LDAP Directories
2. Go to : Administration > Groups > LDAP Directory Link
3. Select groups you want to import and then import them (Actions > Import)

### Your GLPI setup information

Operating system: Linux hd-dev 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
PHP 7.4.28 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache/2.4.52 (Debian) (Apache/2.4.52 (Debian) Server at hd-dev.univ-lehavre.fr Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0
Server Software: Debian 10
	Server Version: 10.3.31-MariaDB-0+deb10u1-log
	Server SQL Mode: 
	Parameters: helpdesk_glpi@mysql-proxy-pp.univ-lehavre.fr:33060/helpdesk_glpi
	Host info: mysql-proxy-pp.univ-lehavre.fr via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.3.31) - Perfect!Database version seems correct (10.3.31) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/apps/glpi/files/_cache has been validated.Write access to /var/www/apps/glpi/files/_cache has been validated.
Write access to /var/www/apps/glpi/config has been validated.Write access to /var/www/apps/glpi/config has been validated.
Write access to /var/www/apps/glpi/files/_cron has been validated.Write access to /var/www/apps/glpi/files/_cron has been validated.
Write access to /var/www/apps/glpi/files has been validated.Write access to /var/www/apps/glpi/files has been validated.
Write access to /var/www/apps/glpi/files/_dumps has been validated.Write access to /var/www/apps/glpi/files/_dumps has been validated.
Write access to /var/www/apps/glpi/files/_graphs has been validated.Write access to /var/www/apps/glpi/files/_graphs has been validated.
Write access to /var/www/apps/glpi/files/_lock has been validated.Write access to /var/www/apps/glpi/files/_lock has been validated.
Write access to /var/www/apps/glpi/files/_pictures has been validated.Write access to /var/www/apps/glpi/files/_pictures has been validated.
Write access to /var/www/apps/glpi/files/_plugins has been validated.Write access to /var/www/apps/glpi/files/_plugins has been validated.
Write access to /var/www/apps/glpi/files/_rss has been validated.Write access to /var/www/apps/glpi/files/_rss has been validated.
Write access to /var/www/apps/glpi/files/_sessions has been validated.Write access to /var/www/apps/glpi/files/_sessions has been validated.
Write access to /var/www/apps/glpi/files/_tmp has been validated.Write access to /var/www/apps/glpi/files/_tmp has been validated.
Write access to /var/www/apps/glpi/files/_uploads has been validated.Write access to /var/www/apps/glpi/files/_uploads has been validated.
Write access to /var/www/apps/glpi/marketplace has been validated.Write access to /var/www/apps/glpi/marketplace has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

**Comment by paidge** [comment]
I have no errors concerning this issue in the logs. If I see in my database, there is no name for the imported groups.

`SELECT * FROM glpi_groups WHERE name = ""`

![image](https://user-images.githubusercontent.com/2470104/159887161-aeae7917-ec2e-4930-846a-1cbc1c096c84.png)

**Comment by cconard96** [comment]
The data shown on the list of groups to import doesn't make sense to me. It shows the group names but not the DNs.

Can you provide the information from that LDAP server's Groups tab in GLPI, and also which LDAP server you are using (Active Directory?).

**Comment by paidge** [comment]
This is not an Active Directory. Here is a screenshot concerning the information from that LDAP server's Groups tab in GLPI : 
![image](https://user-images.githubusercontent.com/2470104/160368511-96dc40df-c35a-4579-be0f-64983df3055d.png)

**Comment by cconard96** [comment]
If you don't use Active Directory for LDAP, we may need to know which LDAP implementation you use to try and recreate this issue.

**Comment by paidge** [comment]
We are using OpenLDAP. For information, I'm searching groups in a user attribute (supannentiteaffectation). This attribute is not part of **ou=groups**, this may be the origin of the problem. So this configuration returns the same result/behavior : 
![image](https://user-images.githubusercontent.com/2470104/160374877-62054c57-e2a0-4fab-9901-e79db6f861c5.png)

GLPI lists all groups from this attribute (1st screenshot in 1st message) but, when importing, GLPI is searching these groups in **OU=groups**. As the groups does not exist in **OU=groups**, GLPI does not retrieve the groups name.

**Comment by cconard96** [comment]
I can only find limited information about the "supannentiteaffectation" attribute, but it looks like it only stores a list of names of groups and the documentation also said:
This attribute has local scope . For cross-institutional usage, see supannTypeEntiteAssignment.
Although I don't know what that means. I assume it means it only stores groups in the same OU?

Neither one uses a list of group DNs.

Is there a use case that prevents using the standard "memberof" attribute instead?

**Comment by paidge** [comment]
Here is the use case : In our organization, there is no group concerning the different departments but this attribute (supannentiteaffectation) reflects the departments. That's why I wanted to retrieve the values of this attribute as groups.

With these settings, I can retrieve LDAP groups but we should create new LDAP groups to reflect departments organization.

![image](https://user-images.githubusercontent.com/2470104/160398323-54cd4f3e-8e73-46e4-8803-c1d31ba249c8.png)

**Comment by paidge** [comment]
In this case, a solution consists in creating groups by hand and then populating them with LDAP Directory link settings : 
![image](https://user-images.githubusercontent.com/2470104/160988554-7110d58e-8aad-401a-bfbd-34a9f5ed4bce.png)
