### ISSUE TITLE
[GLPI 10] Bug when sending notification emails

### ISSUE THREAD

**Issue by yacinus** [glpi-project/glpi#11030]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Notice : Undefined Index: usertype in C:\Xampp\htdocs\glpi10rc2\src\NotificationEventMailing.php on line 89

### Page URL

tracking.injector.php

### Steps To reproduce

1. Go to Configuration => Notifications
2. Activate Following and Following by mail
3. on the same page click on email notification configuration
4. Fill the smtp server infos and test the configuration
5. Go to users and fill the mail information of one user
6. Logout and login with the fresh user
7. Create ticket, you can see that there's no email field like in the previous versions and also when you're going to create it you will also notify the error that I discribed.
[event.log](https://github.com/glpi-project/glpi/files/8314174/event.log)
[cron.log](https://github.com/glpi-project/glpi/files/8314178/cron.log)
[mail.log](https://github.com/glpi-project/glpi/files/8314180/mail.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/8314181/php-errors.log)
[remove.txt](https://github.com/glpi-project/glpi/files/8314183/remove.txt)
[sql-errors.log](https://github.com/glpi-project/glpi/files/8314185/sql-errors.log)

**Comment by cedric-anne** [comment]
Fixed by #10909.
