### ISSUE TITLE
[9.1] API :  rights are not applied when get all tickets

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#1103]
USING  API :
for a post only user :  **trying to get a ticket from other people is no allowed :  OK**
```
http://localhost/glpi/apirest.php/ticket/1018?Content-Type=%20application/json&app_token=[GLPI91app-token]&session_token=[PostOnlyUserSessionToken].
```
returns =>["ERROR_RIGHT_MISSING","Vous n'avez pas les droits requis pour réaliser cette action.]

**trying to get all tickets returns all tickets  :  KO**
```
http://localhost/glpi/apirest.php/ticket?Content-Type=%20application/json&app_token=[GLPI91app-token]&session_token=[PostOnlyUserSessionToken].
```

returns list of ticket including # 1018

**Comment by orthagh** [comment]
Oh, good catch, i can't replicate on my first tests, but this issue on the itemtype name.
To filter properly, we need a uppercase on the first letter of Ticket 

Ex:
```
http://localhost/glpi/apirest.php/Ticket?Content-Type=%20application/json&app_token=[GLPI91app-token]&session_token=[PostOnlyUserSessionToken].
```

I'll push a fix soon
