### ISSUE TITLE
[9.5.7] LDAP Not synchronizing existing users, and never re-importing deleted users

### ISSUE THREAD

**Issue by NoxWorld2660** [glpi-project/glpi#11066]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7 

### Bug description

Hi,

I have one LDAP currently activated, and i imported user once manually with a filter on an Organization Unit inside the LDAP. 
This works fine.

However, when i try to synchronize existing users to update their informations, EG email address , it doesn't work.
In the LDAP configuration i have set the following mapping for email : 
![image](https://user-images.githubusercontent.com/57005290/159449155-4fa4bd79-07e4-404f-8366-1a0a059285ba.png)
NB : I have the same problem with other fields, email was just an example.

When i take a user, and make an LDAP request in powershell, i have the field "UserPrincipalName" that is correctly returned.
When i force the sync from GLPI (My user logged in, as super admin, in root entity. I go to  user > XXXX > Force Sync ), GLPI display his popup on the bottom right saying everything has been updated
![image](https://user-images.githubusercontent.com/57005290/159449635-b28e8cd9-40d4-4e52-a15a-4b4c668107e6.png)

Yet the email didn't change.

All the users were initially imported from another LDAP (id 1, now disabled), then changed to new LDAP (id 2, active).
All the users are currently in root entity.
The same things occurs with command lines , both the "ldap_mass_sync.php" script and the "bin/console ldap:sync"

I tried to delete one user, then wanted to reimport it. Now GLPI doesn't find the user in our LDAP, yet when i make the query in powershell, i get every information on that same user, and it was previouly imported from the LDAP.
Is there a way to confirm that GLPI is properly retrieving the informations of that LDAP connection ?
It obviously works when we login and when i make the "Test Connection"

Am i missing something ? Could it be related to a missing PHP Extension or a misconfiguration server side somwhere ? 

### Relevant log output

```shell
[2022-03-22 10:06:37] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: ldap_parse_result(): Argument #2 ($result) must be of type resource, bool given in C:\xampp\htdocs\glpi\inc\authldap.class.php at line 1678
  Backtrace :
  inc\authldap.class.php:1678                        ldap_parse_result()
  inc\authldap.class.php:1837                        AuthLDAP::searchForUsers()
  inc\authldap.class.php:3937                        AuthLDAP::getAllUsers()
  inc\authldap.class.php:1512                        AuthLDAP::getUsers()
  inc\authldap.class.php:3493                        AuthLDAP::showLdapUsers()
  front\ldap.import.php:66                           AuthLDAP::searchUser()
```

### Page URL

http://MyDomainName/front/user.form.php?id=877

### Steps To reproduce

1. Configure an LDAP Connection + mapping fields
2. Import users
3. Try to synchronize any user after change ; Or delete an user and try to reimport it.

### Your GLPI setup information

GLPI 9.5.7 ( => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:fr_FR

Operating system: Windows NT **_XXXXXXXXX_** 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP 8.0.15 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip,
	zlib)
Setup: max_execution_time="180" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.0.15 (Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.0.15 Server at
	_**someDomainName.ext**_ Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi_prod
	Host info: localhost via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is not presentxmlrpc extension is not present
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is not presentsodium extension is not present
Database version seems correct (10.4.22) - Perfect!Database version seems correct (10.4.22) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

**Comment by cedric-anne** [comment]
Hi,

Can you try to set `Use paged results` to no in your LDAP configuration on GLPI side and try again ?

Also, can you check if you have a log entry related to `ldap_search` just before the one you mentionned ?

**Comment by NoxWorld2660** [comment]
@cedric-anne  ; Solved the problem, was mostly coming from configuration (and myself) , and not from GLPI.

- We imported users from LDAP OU = XXXXXXXXX
- We made a new LDAP connexion with OU = YYYYYYYYY
- Some users in the LDAP changed from XXXXXX to YYYYYYY , some stayed in XXXXXXX.
- We edited every GLPI users to user the new connection => YYYYYYYY  ; So obvisouly all the users that stayed in XXXXXX were never updated.

The functionnal problem came from us / me , sorry about that.
I printed the error from "nc\authldap.class.php:1837                        AuthLDAP::searchForUsers()" ; it stated that "user was not found" or something like that. So i went digging and realized how stupid i was. 

However, there are 2-3 small behaviours  and messages in GLPI that could be improved regarding this issue.
- When you have an error such as i had, GLPI states that a part of you users are not up to date ( in my case every user from the LDAP XXXXXX OU ) => Meaning that research probably ignores the filter you made on your LDAP connection.

- When you make the sync from the user interface : Users > Force Synchro ; glpi says it's ok / update was done, even though the users was not found because of the change of LDAP auth or a wrong filter in your LDAP auth in GLPI configuration.

Some of these messages & code probably should be reviewed to make a few extra checks & display a warning or error message in some of these cases.


> Also, can you check if you have a log entry related to ldap_search just before the one you mentionned ?
I didn't recheck, but i had tried several time, and i had several "blocks" of the same logs that i posted above, i looked for anything strange before & after this one block, didn't find anything weird.

Anyway, sync works fine, everything was my fault.
Thank you.

**Comment by cedric-anne** [comment]
Honestly, I do not really know how the LDAP sync works on GLPI, so I cannot really help.

@cconard96 Do you think we could make some improvements to handle this case ?

**Comment by cconard96** [comment]
I'm not sure I completely understand the situation.

There are 2 LDAP servers configured for the same server but different OUs in the connection filter?

**Comment by NoxWorld2660** [comment]
>I'm not sure I completely understand the situation.
There are 2 LDAP servers configured for the same server but different OUs in the connection filter?

Exactly.

**Comment by cconard96** [comment]
> Honestly, I do not really know how the LDAP sync works on GLPI, so I cannot really help.
> 
> @cconard96 Do you think we could make some improvements to handle this case ?

I don't know how much this can be improved with the current authentication system and I don't know how much of this falls under undefined behavior.

When doing a force sync, it doesn't look like it cares if the server is active or not in GLPI. The update success message looks like it would only show if the user was found in the old server. It doesn't use the connection filter for the sync and I'm not sure that it should. Once it is imported, users are connected to the LDAP connection based on the value of their sync field. Since the user is still in the same domain, the sync will still work.

Typically, there should be one LDAP connection in GLPI per domain I think (not sure how it should handle subdomains on the same server and I don't know if that was a consideration when the LDAP auth was first implemented). Having multiple connections for different OUs seems like it would lead to undefined behavior. Handling multiple connections per server would involve modifying the sync and authentication code.

I could also be completely wrong because this part of the code is pretty complex and not really centralized so I don't understand it very well.

**Comment by NoxWorld2660** [comment]
> Typically, there should be one LDAP connection in GLPI per domain I think (not sure how it should handle subdomains on the same server and I don't know if that was a consideration when the LDAP auth was first implemented). Having multiple connections for different OUs seems like it would lead to undefined behavior. Handling multiple connections per server would involve modifying the sync and authentication code.

Is it possible with the current filter to get spécific differents OU ? 

For exemple, given a use case : domain.com , with OU "X100" and "Y100" containing childrens like below

X1000
 - X1010
 -- X1011
 -- X1012
 - X1020
 - X1030

Y100
- Y101
- Y102
- Y103

I would like to import / synchronise users from X1012 and Y100 , would it be possible ?
With classic LDAP filters ? 

Sorry if the question is dumb, my knowledge in LDAP is quite limited and i didn't exactly verify the limitations of GLPI - LDAP

**Comment by cconard96** [comment]
What I've done and seen others do it create one connection with the base DN set to the top-most OU or container that all users are a part of. If there is no common parent OU or container, you could just use the base DN like:
DC=domain,DC=com

For connection filter I just use this to include only user objects:
(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))
This could be modified to include only members of a specific group as well.

You can use authorization assignment rules to assign profiles to users as needed or completely block the import of certain users based on certain criteria including group membership, DN, etc.

If you need to map fields differently, then having multiple connections is the only solution currently I think.

**Comment by NoxWorld2660** [comment]
> What I've done and seen others do it create one connection with the base DN set to the top-most OU or container that all users are a part of. If there is no common parent OU or container, you could just use the base DN like: DC=domain,DC=com
> 
> For connection filter I just use this to include only user objects: (&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))) This could be modified to include only members of a specific group as well.
> 
> You can use authorization assignment rules to assign profiles to users as needed or completely block the import of certain users based on certain criteria including group membership, DN, etc.
> 
> If you need to map fields differently, then having multiple connections is the only solution currently I think.

Very interesting, thank you.

In our case, there are 9 departements having the structure i mentionned, and i'd like to import users of only 2 departments, having no structure DN in common. How do you block the import of users base on criteria ? I could potentially exclude the 7 others departments with that ?
