### ISSUE TITLE
[9.5.7] duplicate place import user ldap

### ISSUE THREAD

**Issue by Riesuu** [glpi-project/glpi#11060]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Hello,
on GLPI 9.5 I import my users via LDAP. The places were created manually in order to make rules of sub-network for fusion inventory, to allow him to redirect the material well.

Entity Master
---A
     ---Location 1
     ---Location 30
---B
     ---Location 1
     ---Location 30
---Z
     ---Location 1
     ---Location 30

When I import a user, he creates a new place with the same name even though the place already exists.
Do you have an idea how to solve this problem?

### Steps To reproduce

Import user with LDAP

**Comment by cedric-anne** [comment]
> Entity Master
> ---A
> ---Location 1
> ---Location 30
> ---B
> ---Location 1
> ---Location 30
> ---Z
> ---Location 1
> ---Location 30

Are A, B and Z entities or locations ?
In case these are entities, then explaination is simple. LDAP sync search for location on root entity, see https://github.com/glpi-project/glpi/blob/0db2ad847165105326b17028254f702200a09661/inc/user.class.php#L1671-L1676

> When I import a user, he creates a new place with the same name even though the place already exists.

Where does the new place is created ?

**Comment by Riesuu** [comment]
A/B/Z are entities.
when the user is imported, I use a rule that is based on the email address to put it in the right entity (the user).
The new place that is created is the same, but in the root entity.

![image](https://user-images.githubusercontent.com/17006344/159264600-1efb567c-222f-41db-89a7-2487000ebcf2.png)

**Comment by cedric-anne** [comment]
Rules are process after mentionned piece of code. So, at this point, entity is not yet assigned.

**Comment by Riesuu** [comment]
Okay. Is there a way to prevent having the same location twice? I use locations with my forms for formcreator and others.

**Comment by cedric-anne** [comment]
The only way would be to put these locations into root entity directly.
