### ISSUE TITLE
GLPI 10.0 RC3+inventory RC7 : Import information, the agent's name (log) is not displayed in the printers and the network

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#11084]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0 RC3

### Bug description

Agent name  dont displayed on printer and network hardware information
Only computers and monitors are displayed well

this problem existed on the old RC

example : 
Computer OK
![image](https://user-images.githubusercontent.com/68054991/159693963-f53580af-a0ab-424a-8c75-739f98c604f9.png)

Printer KO no agent information
![image](https://user-images.githubusercontent.com/68054991/159694086-ccc6a6f7-886f-4096-abe8-1f609de0874a.png)

Networking KO no agent information
![image](https://user-images.githubusercontent.com/68054991/159694193-f3fdb862-b032-4139-8fa5-63e0439a348e.png)

### Relevant log output

```shell
No log
```

### Steps To reproduce

1. Import information printers and networking

**Comment by steph461** [comment]
my agent information
![image](https://user-images.githubusercontent.com/68054991/159695734-bfd566c3-3ec5-460d-b213-33a6fe53a8d2.png)

**Comment by steph461** [comment]
The robot had closed this issue ?

This issue is alway actual

![image](https://user-images.githubusercontent.com/68054991/171815461-411098c1-300d-4321-a66e-616b50610c8e.png)
![image](https://user-images.githubusercontent.com/68054991/171815537-14c18143-0f30-42a7-ad53-0599d0b75953.png)

**Comment by cedric-anne** [comment]
@steph461 

Is this issue still present?

**Comment by stonebuzz** [comment]
seems ok on my side (from nightly build)
![image](https://user-images.githubusercontent.com/7335054/206379925-5535edbd-c026-46fc-8ea5-86a232ad37f5.png)

**Comment by steph461** [comment]
Hello,

its ok  for me
