### ISSUE TITLE
Impossible to use caldav with CAS authentication

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#11091]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v9.5.7

### Bug description

I can use CalDAV without CAS authentication but when this source of authentication is used, CalDAV server sends an XML response to inform that CAS auth failed and the sync is no more efficient.

### Relevant log output

```shell
No error about that in the logs
```

### Steps To reproduce

1. Activate CAS authentication
2. Configure your mail client to sync with your calendar

### Your GLPI setup information

This issue is not linked with my configuration

### Anything else?

[This problem has already been evoked in the forum](https://forum.glpi-project.org/viewtopic.php?pid=490464).

**Comment by cedric-anne** [comment]
Hi,

In the CAS authentication system, when a client application tries to access an application, the CAS system tries to find a valid authentication token (using cookies in our case), and if this token is not found, client is redirected to the CAS server. If client is not already authenticated there, end-user has to complete the authentication process.

I tried to see if we could authenticate against CAS server using a different method and I get lost in documentation. As far as I understand, CAS server may be plugged on many different authentication systems, and for some of them, it is nearly impossibile to simulate the authentication process using simple curl requests.

Maybe it could be possible to implement simulation of some of available CAS authentication processes, and add a configuration `CAS support for backends` to give ability to administrator to chosse the correct process to use (e.g. `Unvailable` (by default), `Simulate form submission`, ...). I do not know if it is a viable solution.

Regards

**Comment by paidge** [comment]
When the CAS authentication is disabled, Thunderbird can use CalDAV. So, I may be wrong, but I think the CAS auth could be bypassed when it is activated.

**Comment by cedric-anne** [comment]
Can you check following patch ?

```diff
diff --git a/inc/caldav/backend/auth.class.php b/inc/caldav/backend/auth.class.php
index 4e731a8719..78e43a3a9b 100644
--- a/inc/caldav/backend/auth.class.php
+++ b/inc/caldav/backend/auth.class.php
@@ -49,6 +49,6 @@ class Auth extends AbstractBasic {
 
    protected function validateUserPass($username, $password) {
       $auth = new \Auth();
-      return $auth->login($username, $password);
+      return $auth->login($username, $password, true);
    }
 }
```

**Comment by paidge** [comment]
Hoho ! It seems to work :)
