### ISSUE TITLE
Post-only observer is unable to read attached documents from a ticket using link from e-mail

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#111]
Hi,

When a post-only user is observer in a ticket and he tries to open a ticket's document following document link in e-mail, there is a permissions error. 

The same user can display the document from the glpi interface.

Thanks.

**Comment by orthagh** [comment]
Can you post your notification template ?

An copy the two links (from email and in interface)

**Comment by kabassanov** [comment]
From glpi interface: https://titi.lip6.fr/glpi/front/document.send.php?docid=4048&tickets_id=2426
In the e-mail: https://titi.lip6.fr/glpi/front/document.send.php?docid=4048
(tickets_id is missing)

I didn't find anything related to attached files in my template... It should be a core add-on, shouldn't it?

**Comment by orthagh** [comment]
What's your glpi version ?

In current master, glpi should add that tickets_id parameter in notification for tickets (also for all itil objects)

**Comment by kabassanov** [comment]
0.85.2

**Comment by orthagh** [comment]
I found, could you change your notification template and replace **##document.url##** by **##document.downloadurl##**

It should work.

**Comment by kabassanov** [comment]
It is strange, but I have not "##document" in my Template... Probably it defaults to something in the GLPI core... It is propably the issue, isn't it?

**Comment by orthagh** [comment]
I'd like to see your final mail (obsufacted if you want).
It will help me find which part of glpi add that link.

**Comment by orthagh** [comment]
With corrections of #124, I suggest you to add in your notification template, the list of attached documents (with the correct url).

Regards
