### ISSUE TITLE
takeintoaccount_delay_stat is not accurate measure, if using Calendars with Active hours

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#11109]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

all

### Bug description

Take Into account date is not computed precisely in Statistics.
Currently GLPI in DB uses just takeintoaccount_delay_stat which is computed as getActiveTimeBetween of creation and current time.
This is enough for determining whether TTO was met or not but it complicates date computation.

For example in Ticket::showStatsDates() it is computed incorrectly as:
`` $date_takeintoaccount     = $date_creation + $this->fields['takeintoaccount_delay_stat'];``
Which does not account active time of calendar.

Also you can't get real time when someone taken ticket into account during inactive time as it will be shown as 1. It is computed following way:
``max(1, $calendar->getActiveTimeBetween($this->fields['date'],$_SESSION["glpi_currenttime"]));``

My proposal would be to extend GLPI by using same thing as for Solution (solvedate), simply add field takeintoaccount_delay_date.
This would also simplify reports when someone would like to report whether ticket SLA was met or not (you could do just simple date comparison)
If this is not a way to go, at least consider fixing the Ticket::showStatsDates() to compute $date_takeintoaccount  using computeDate() using SLA calendar.

### Steps To reproduce

1. Create SLA with calendar 8x5 using TTO in hours
2. Create ticket during Inactive time.
3. Attach SLA to ticket
3. Take into account during Active time.
4. Check the Ticket Statistics

### Your GLPI setup information

Vanilla without plugins

**Comment by cconard96** [comment]
Are you defining your SLA time in days or hours. When specifying it as days, there is a different behavior.
See #10594

**Comment by VladoTTX** [comment]
Sorry I was not precise, I define it in hours. I know about the issue with "days" SLA definition.

**Comment by cconard96** [comment]
I didn't notice you reported the original issue. Sorry.

**Comment by VladoTTX** [comment]
Thinking that it would make more sense to store takeintoaccount_delay_stat without using calendar in Ticket:;computeTakeIntoAccountDelayStat() so use just:
return max(1, strtotime($_SESSION["glpi_currenttime"]) - strtotime($this->fields['date']));
And this way we won't need even proposed takeintoaccount_delay_date.

To me it does not make much sense to know how much time passed from active time but to know real time when ticket was taken into account (for comparison with TTO date). 
And anyway how much active time it was could be still computed after this change (if that is needed in Ticket::showStatsDates) as follows:
$calendar->getActiveTimeBetween($this->fields['date'], $this->fields['date']+$this->fields['takeintoaccount_delay_stat'])

**Comment by VladoTTX** [comment]
Rethinking again, to make it consistent with other *_delay_stat, it would be really better to introduce field takeintoaccountdate to glpi_tickets
This would require GLPI DB to be updated for existing tickets with estimated date from takeintoaccount_delay_stat in DB during GLPI upgrade.
I would propose following. Let me know whether you would accept such PR:

``ALTER TABLE glpi_tickets  ADD COLUMN `takeintoaccountdate` timestamp NULL DEFAULT NULL``

And update src/Tickets.php with few lines:
```
--- src/Ticket.php.20220427     2022-04-27 11:22:08.657795099 +0000
+++ src/Ticket.php      2022-04-27 12:00:46.913503656 +0000
@@ -1547,8 +1547,16 @@ public function pre_updateInDB()
         ) {
             $this->updates[]                            = "takeintoaccount_delay_stat";
             $this->fields['takeintoaccount_delay_stat'] = $this->computeTakeIntoAccountDelayStat();
+            $this->fields['takeintoaccountdate'] =  $_SESSION["glpi_currenttime"];
         }

+       if (in_array("takeintoaccount_delay_stat", $this->updates) &&
+               $this->fields['takeintoaccount_delay_stat'] == 0){
+
+               if(!in_array("takeintoaccountdate", $this->updates)) $this->updates[] = "takeintoaccountdate";
+               $this->fields['takeintoaccountdate']  = NULL;
+       }
+
         parent::pre_updateInDB();
     }

@@ -2579,6 +2587,7 @@ public function updateDateMod($ID, $no_s
                     [
                         'id'                         => $ID,
                         'takeintoaccount_delay_stat' => $this->computeTakeIntoAccountDelayStat(),
+                        'takeintoaccountdate' =>  $_SESSION["glpi_currenttime"],
                         '_disablenotif'              => true
                     ]
                 );
@@ -6554,10 +6563,7 @@ public function showStatsDates()
     {
         $now                      = time();
         $date_creation            = strtotime($this->fields['date']);
-        $date_takeintoaccount     = $date_creation + $this->fields['takeintoaccount_delay_stat'];
-        if ($date_takeintoaccount == $date_creation) {
-            $date_takeintoaccount  = 0;
-        }
+        $date_takeintoaccount     = strtotime($this->fields['takeintoaccountdate']);
         $internal_time_to_own     = strtotime($this->fields['internal_time_to_own']);
         $time_to_own              = strtotime($this->fields['time_to_own']);
         $internal_time_to_resolve = strtotime($this->fields['internal_time_to_resolve']);

```
