### ISSUE TITLE
[GLPI 10.0.0-rc3] Php 8.1 error when upload an image or file in GLPI

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#11120]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0-rc3

### Bug description

Hello,

Trying to upload an image in a ticket and I obtain this error 

![image](https://user-images.githubusercontent.com/63521311/160353618-c5454025-e4e9-4c41-aa44-8257d1b54efd.png)

### Relevant log output

```shell
[2022-03-28 09:55:55] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): basename(): Passing null to parameter #2 ($suffix) of type string is deprecated in C:\inetpub\wwwroot\glpi\vendor\blueimp\jquery-file-upload\server\php\UploadHandler.php at line 1478
  Backtrace :
  ...y-file-upload\server\php\UploadHandler.php:1478 basename()
  ...ry-file-upload\server\php\UploadHandler.php:561 UploadHandler->basename()
  ...ry-file-upload\server\php\UploadHandler.php:581 UploadHandler->trim_file_name()
  ...y-file-upload\server\php\UploadHandler.php:1143 UploadHandler->get_file_name()
  ...y-file-upload\server\php\UploadHandler.php:1422 UploadHandler->handle_file_upload()
  src\GLPIUploadHandler.php:147                      UploadHandler->post()
  ajax\fileupload.php:47                             GLPIUploadHandler::uploadFiles()
```

**Comment by cedric-anne** [comment]
Hi,

Did you tried to copy/paste an image from another application, or did you tried to upload an existing image file ?

**Comment by stdglpi** [comment]
> Hi,
> 
> Did you tried to copy/paste an image from another application, or did you tried to upload an existing image file ?

Both, usually i'm using "share X" to copy paste the screenshot (works perfectly)
I tried to upload same error

**Comment by cedric-anne** [comment]
#11121 should fix this.

**Comment by stdglpi** [comment]
> #11121 should fix this.

@cedric-anne it is better :)
