### ISSUE TITLE
[10.0 RC3]Debug mod:  error SCSS compilation

### ISSUE THREAD

**Issue by okba6z** [glpi-project/glpi#11135]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 RC3

### Bug description

Hello,
Whatever the theme chosen in the preferences in debug mode, I have this error:
https://prnt.sc/AU9YopzFOZkc

Do you have an idea?

Cordially,

**Comment by cconard96** [comment]
Did you copy the new files over top ones from a previous version? The error seems to indicate you have the themes from an older version and the new ones which are named slightly different.

Only some folders should be kept between versions.
https://glpi-install.readthedocs.io/en/latest/update.html

**Comment by cedric-anne** [comment]
See #10365
