### ISSUE TITLE
Edit information about system installation and configuration

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1114]
Hello.
I updated the system with RC2 before the stable release 9.1, but the information that appears on the Setup-> General-> System writes about the previous release.

How can I edit this information, you can do this during working hours.
![glpi](https://cloud.githubusercontent.com/assets/21122546/19077639/de90c9ca-8a66-11e6-9ffe-413e86a7371e.JPG)

**Comment by remicollet** [comment]
If GLPI display git revision, this mean you are using a git snapshot.

From 9.1 branche, should be **GLPI 9.1-21-gdf37d59**
From master branch, should be **GLPI 9.1-36-ged48163**

Should you update your snapshot.
(if you have installed a tarball, just delete the unwanted .git folder)

**Comment by gloomy-master** [comment]
Yes, thanks remicollet, it helped.

And that another folder. tx, you can also delete?

**Comment by remicollet** [comment]
> And that another folder. tx, you can also delete?

Yes
