### ISSUE TITLE
[9.5.6] Rules on tickets with regular expressions no longer work with character  >

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#11143]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.6

### Bug description

Good morning,
all rules that have the > character no longer work.
We have dozens of rules, and I just realized they don’t work anymore.
I tried  > but this is not taken into account.
Is there a patch and where does fat change the code?
Thank you.
Example:
```
(PBS HVAC > Gas|PBS HVAC > External Networks|PBS HVAC > Ventilation|Air Conditioning) 
Here only Air conditioning works because no >
```

**Comment by cedric-anne** [comment]
Hi,

Can you please provide detailed information, as requested in the issue form ?

**Comment by falco2001** [comment]
Actually, it’s about rules on tickets.
With this condition `(PBS HVAC > Gas|PBS HVAC > External Networks|PBS HVAC > Ventilation|Air Conditioning)`only Air Conditioning works.
How to make it take into account the > because it worked before the 9.5.6 and 9.5.5 update.
Thank you

**Comment by cconard96** [comment]
Confirmed bug and it is still present in the latest GLPI 10 nightly version in both test mode and actually running the rule.

In both cases, the `>` is HTML encoded by the time the criteria gets checked so the regex pattern is broken.

**Comment by cedric-anne** [comment]
@falco2001 

#15559 should fix issues with the `<` and `>` chars.
