### ISSUE TITLE
No stdout from bin/console

### ISSUE THREAD

**Issue by Dimitri281** [glpi-project/glpi#11167]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.7

### Bug description

Hello,

I wanted to know if you had already encountered the following problem,
we try to use the glpi cli console to synchronize our users in preprod it works however on our prod the use of the console does not return any feedback.

TIA,

![issue_console](https://user-images.githubusercontent.com/84469067/161241671-5473662f-ffae-496b-8f98-68b075b3e0d7.png)

**Comment by cedric-anne** [comment]
Hi,

Can you try to run `php -d display_error=1 -d error_reporting=E_ALL console -vvv` ?

**Comment by Dimitri281** [comment]
Same result no stdout :/ 
![image](https://user-images.githubusercontent.com/84469067/161252372-e4607479-4dca-4570-a32f-3a93cc54aec3.png)

**Comment by cedric-anne** [comment]
What is the result of `php -v` ?

Can you try to run `php console -vvv --no-plugins` ?

**Comment by Dimitri281** [comment]
`php -v`
![image](https://user-images.githubusercontent.com/84469067/161258118-23219cc9-457b-49e2-b494-164991a80826.png)

`php console -vvv --no-plugins`
![image](https://user-images.githubusercontent.com/84469067/161258348-3d4c9251-3a9b-424b-b2da-a6e264097fcc.png)

**Comment by cedric-anne** [comment]
OK, so you have a plugin that cause the issue.

Maybe there is a plugin that is present on your production server, and probably not present in your preproduction server, that is buggy or that is simply call a `die()` or `exit()` function.

**Comment by Dimitri281** [comment]
with --no-plugins  it's work,
we use :
PHP SAML by Derrick Smith
GLPI Mod by Stevenes Donato
Form Creator by Jérémy Moreau
Export of used itil by TECLIB
Data Injection by Walid Nouh
Field By TECLIB

Same as the Pre-production and all update at the last version :/

**Comment by cedric-anne** [comment]
```
PHP SAML by Derrick Smith
```

After a quick look, I think this plugin might cause the issue. Is it active and configured the same way in your preproduction server ?

Could you try to disable it and run `php console` to see if problem persist ?

**Comment by Dimitri281** [comment]
yes with PHP SAML desactivate the console work fine,
only one diff between  SAML preprod and SAML prod it's the Plugin Enforced option ,
we forced the SAML auth in prod,
really thanks you for u'r troubleshooting help 👍

**Comment by cedric-anne** [comment]
I close issue here.

You should open an issue on plugin repository : https://github.com/derricksmith/phpsaml/issues
