### ISSUE TITLE
[Solved] Change : no way to add task ?

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi#11177]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

V10 RC3

### Bug description

I created a change, But I don't know where to add a task to this change (as done in 9.5.5 for instance)
I see the 'to do list' but not the button to add a task
![image](https://user-images.githubusercontent.com/42341169/161494225-a042374a-0b47-4a09-9ffd-8dc85b961f77.png)

Thanks
Best regards

### Page URL

http://localhost/glpi/front/change.form.php

**Comment by cconard96** [comment]
Hello,
The process for adding tasks is the same for Tickets, Changes and Problems.

What shows up for the Answer button when the ToDo list is hidden?

**Comment by EC2311** [comment]
ok !!!

I just saw it with 'reply/add a task' : not very 'visible' and not really intuitive..

Sorry for disturbing
