### ISSUE TITLE
Massive action for closed tickets

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1118]
http://forum.glpi-project.org/viewtopic.php?id=155158

Delete all actions of update for closed ticket. Must just stay Update status

**Comment by trasher** [comment]
From the tickets list, we can filter for closed tickets, or all tickets... At the moment, there is nothing that we could rely on to know if one of the selected items is closed or not.
We'll probably have to make several changes in order to get that working as expected here.
