### ISSUE TITLE
Self-Service users cannot use Reservation

### ISSUE THREAD

**Issue by jackburton79** [glpi-project/glpi#11193]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

v10.0.0-rc3

### Bug description

As a self-service user I tried to add a reservation.
Clicking on the day inside the calendar I get this error:

![image](https://user-images.githubusercontent.com/3501519/161945312-cee0e9b6-8e66-43e2-ba39-7c92160645a1.png)

After this one, I have to refresh the page, otherwise nothing works anymore.

I checked user/profile permissions, and they look fine:
![image](https://user-images.githubusercontent.com/3501519/161945845-f8a933fe-757b-4dd0-b0c6-3327c784b6f3.png)

There are no logs either in sql-errors.log or php-errors.log

### Steps To reproduce

Using a self-service user

1. Click on reservation

2. Click on "Reserve this item" on any item, then click on any day

**Comment by informaticavera** [comment]
the same thing happens in my installation

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by #11080.

**Comment by jackburton79** [comment]
Is there a tentative date for the next release ?

**Comment by cconard96** [comment]
> Is there a tentative date for the next release ?

April 20th.

**Comment by jackburton79** [comment]
Tested latest nightly and the problem is fixed.
Thank you!
