### ISSUE TITLE
Task todo/done not show last edit

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#11208]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

If you create a new task with status To do, when the task was mask as done no edit info is shown in the task bouble. (that usually appear when someone edit the task)
You can see the modify correctly in the Historical tab instead.

### Steps To reproduce

1. Open a ticket
2. Add a new Task with status: To do
3. write something
4. Save the task
5. tick the checkbox
6. Edit info is not shown in the yellow bouble

**Comment by cconard96** [comment]
Behavior seems to be the same with GLPI 10. Even after a page refresh there is no last update information shown. If you edit the task and only change the state, the information is shown.
