### ISSUE TITLE
Business Rules: associate items to the ticket

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#1121]
**Criteria:**
- Criterion: Description
- Condition: regular expression matches
- Reason: /Item: (c[0-9]{1,5})/

**Actions:**
- Fields: Associated elements
- Action type:     Assign: equipment by name + domain
- Value: #0

**Test:**
![test_ok](https://cloud.githubusercontent.com/assets/15769828/19142394/79f451de-8b9d-11e6-9363-b3330a5f35e5.png)

**Steps:**
1. Use profile Self-service
2. Write in ticket description: "Item: c12345" and save it
3. Watch the error_log file

**error_log:**
[Tue Oct 04 13:24:06.379952 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP Fatal error:  Call to a member function getID() on null in /var/www/html/glpi/inc/fqdnlabel.class.php on line 249, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385667 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP Stack trace:, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385686 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   1. {main}() /var/www/html/glpi/front/tracking.injector.php:0, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385694 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   2. CommonDBTM->add() /var/www/html/glpi/front/tracking.injector.php:79, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385701 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   3. Ticket->prepareInputForAdd() /var/www/html/glpi/inc/commondbtm.class.php:802, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385708 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   4. RuleCollection->processAllRules() /var/www/html/glpi/inc/ticket.class.php:1416, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385714 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   5. Rule->process() /var/www/html/glpi/inc/rulecollection.class.php:1458, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385721 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   6. RuleTicket->executeActions() /var/www/html/glpi/inc/rule.class.php:1404, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1
[Tue Oct 04 13:24:06.385727 2016] [:error] [pid 9535] [client 192.168.0.1:2323] PHP   7. FQDNLabel::getUniqueItemByFQDN() /var/www/html/glpi/inc/ruleticket.class.php:279, referer: http://my_glpi_server/glpi/front/helpdesk.public.php?create_ticket=1

see: http://glpi.userecho.com/topics/163-business-rule-to-associate-items-to-the-ticket/
and: http://glpi.userecho.com/topics/46-get-the-pc-name-in-a-ticket/

Thank you.

**Comment by cedric-anne** [comment]
Hi,

This is working in GLPI 9.4. I close the issue.

Regards
