### ISSUE TITLE
USER ISSUES LIST ERROR

### ISSUE THREAD

**Issue by informaticavera** [glpi-project/glpi#11219]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10.0.0-rc3

### Bug description

glpi/marketplace/formcreator/front/issue.php

Error when users try to list their tickets in the Issues menu
Column 'users_id_recipient' in where clause is ambiguou

![Captura de pantalla de 2022-04-08 07-22-11](https://user-images.githubusercontent.com/32567126/162370128-89fa508f-0f4c-4f93-aee0-b1d4945d122b.png)
s

**Comment by trasher** [comment]
Please report issue on plugin
