### ISSUE TITLE
10.0.0-rc3 PHP Memory Limit not correctly detected in CLI

### ISSUE THREAD

**Issue by monta990** [glpi-project/glpi#11217]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc3

### Bug description

When you run the cli command php bin/console glpi:system:check_requirements
Detects less memory that has assigned

That affect to run the following commands
php bin/console glpi:migration:utf8mb4
php bin/console glpi:migration:unsigned_keys

Necessary for db update

### Steps To reproduce

![image](https://user-images.githubusercontent.com/2209179/162333212-66470add-c4ac-44da-8c2d-d34a19f413f1.png)
But has assingned 128M

### Your GLPI setup information

<html>
<body>

GLPI 10.0.0-rc3 ( => /home/lifeadn/public_html/sistemas) Installation mode: TARBALL Current language:en_US
--

Operating system: Linux ns1009671.ip-92-204-138.us 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 PHP 8.1.4 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, 	pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, 	xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="128M" safe_mode="" session.save_handler="files" 	upload_max_filesize="128M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36 Edg/100.0.1185.29 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.37 	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: lifeadn_sistemas@localhost/lifeadn_sistemas 	Host info: Localhost via UNIX socket 	 PHP version (8.1.4) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (5.7.37) is supported. The log file has been created successfully. Write access to /home/lifeadn/public_html/sistemas/files/_cache has been validated. Write access to /home/lifeadn/public_html/sistemas/config has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_cron has been validated. Write access to /home/lifeadn/public_html/sistemas/files has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_dumps has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_graphs has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_lock has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_pictures has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_plugins has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_rss has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_sessions has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_tmp has been validated. Write access to /home/lifeadn/public_html/sistemas/files/_uploads has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration. For security reasons, SELinux mode should be Enforcing. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium. Write access to /home/lifeadn/public_html/sistemas/marketplace has been validated. Access to timezone database (mysql) is not allowed.

GLPI_ROOT: /home/lifeadn/public_html/sistemas GLPI_CONFIG_DIR: /home/lifeadn/public_html/sistemas/config GLPI_VAR_DIR: /home/lifeadn/public_html/sistemas/files GLPI_MARKETPLACE_DIR: /home/lifeadn/public_html/sistemas/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: /home/lifeadn/public_html/sistemas/files GLPI_CACHE_DIR: /home/lifeadn/public_html/sistemas/files/_cache GLPI_CRON_DIR: /home/lifeadn/public_html/sistemas/files/_cron GLPI_DUMP_DIR: /home/lifeadn/public_html/sistemas/files/_dumps GLPI_GRAPH_DIR: /home/lifeadn/public_html/sistemas/files/_graphs GLPI_LOCAL_I18N_DIR: /home/lifeadn/public_html/sistemas/files/_locales GLPI_LOCK_DIR: /home/lifeadn/public_html/sistemas/files/_lock GLPI_LOG_DIR: /home/lifeadn/public_html/sistemas/files/_log GLPI_PICTURE_DIR: /home/lifeadn/public_html/sistemas/files/_pictures GLPI_PLUGIN_DOC_DIR: /home/lifeadn/public_html/sistemas/files/_plugins GLPI_RSS_DIR: /home/lifeadn/public_html/sistemas/files/_rss GLPI_SESSION_DIR: /home/lifeadn/public_html/sistemas/files/_sessions GLPI_TMP_DIR: /home/lifeadn/public_html/sistemas/files/_tmp GLPI_UPLOAD_DIR: /home/lifeadn/public_html/sistemas/files/_uploads GLPI_INVENTORY_DIR: /home/lifeadn/public_html/sistemas/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /home/lifeadn/public_html/sistemas/locales GLPI_VERSION: 10.0.0-rc3 GLPI_SCHEMA_VERSION: 10.0.0-rc3 GLPI_MARKETPLACE_PRERELEASES: 1 GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.6 in (/home/lifeadn/public_html/sistemas/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.0 in (/home/lifeadn/public_html/sistemas/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/home/lifeadn/public_html/sistemas/vendor/simplepie/simplepie/library) mpdf/mpdf in (/home/lifeadn/public_html/sistemas/vendor/mpdf/mpdf/src) michelf/php-markdown in (/home/lifeadn/public_html/sistemas/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/lifeadn/public_html/sistemas/vendor/true/punycode/src) iamcal/lib_autolink in (/home/lifeadn/public_html/sistemas/vendor/iamcal/lib_autolink) sabre/dav in (/home/lifeadn/public_html/sistemas/vendor/sabre/dav/lib/DAV) sabre/http in (/home/lifeadn/public_html/sistemas/vendor/sabre/http/lib) sabre/uri in (/home/lifeadn/public_html/sistemas/vendor/sabre/uri/lib) sabre/vobject in (/home/lifeadn/public_html/sistemas/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/home/lifeadn/public_html/sistemas/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/home/lifeadn/public_html/sistemas/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/home/lifeadn/public_html/sistemas/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/lifeadn/public_html/sistemas/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/home/lifeadn/public_html/sistemas/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/home/lifeadn/public_html/sistemas/vendor/elvanto/litemoji/src) symfony/console in (/home/lifeadn/public_html/sistemas/vendor/symfony/console) scssphp/scssphp in (/home/lifeadn/public_html/sistemas/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/home/lifeadn/public_html/sistemas/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/home/lifeadn/public_html/sistemas/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/home/lifeadn/public_html/sistemas/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/home/lifeadn/public_html/sistemas/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/home/lifeadn/public_html/sistemas/vendor/ramsey/uuid/src) psr/log in (/home/lifeadn/public_html/sistemas/vendor/psr/log/Psr/Log) psr/simple-cache in (/home/lifeadn/public_html/sistemas/vendor/psr/simple-cache/src) psr/cache in (/home/lifeadn/public_html/sistemas/vendor/psr/cache/src) league/csv in (/home/lifeadn/public_html/sistemas/vendor/league/csv/src) mexitek/phpcolors in (/home/lifeadn/public_html/sistemas/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/home/lifeadn/public_html/sistemas/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/home/lifeadn/public_html/sistemas/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/home/lifeadn/public_html/sistemas/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/home/lifeadn/public_html/sistemas/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/home/lifeadn/public_html/sistemas/vendor/paragonie/sodium_compat/src) symfony/cache in (/home/lifeadn/public_html/sistemas/vendor/symfony/cache) html2text/html2text in (/home/lifeadn/public_html/sistemas/vendor/html2text/html2text/src) symfony/dom-crawler in (/home/lifeadn/public_html/sistemas/vendor/symfony/dom-crawler) twig/twig in (/home/lifeadn/public_html/sistemas/vendor/twig/twig/src) twig/string-extra in (/home/lifeadn/public_html/sistemas/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found

Not active

Way of sending emails: SMTP+SSL
<br class="Apple-interchange-newline">
</body>
</html>

### Anything else?

Version updated from 9.5.7

**Comment by cedric-anne** [comment]
Hi,

Can you run `php -r "var_dump(ini_get('memory_limit'));"` and give us the result ?

**Comment by monta990** [comment]
> Hi,
> 
> Can you run `php -r "var_dump(ini_get('memory_limit'));"` and give us the result ?

Hi.
![image](https://user-images.githubusercontent.com/2209179/162504674-0f42dba5-6311-4bb7-91ab-b07ce335039d.png)

**Comment by cedric-anne** [comment]
Hi,

Your PHP configuration limits memory to 32MB in CLI context. Depending on OS, PHP may have multiple configuration files, one for the CLI context, and one for the Web server context. So you have to change your PHP configuration to fits GLPI requirements.

This is not a GLPI bug, so I close this issue.
