### ISSUE TITLE
Ldap users import failed

### ISSUE THREAD

**Issue by kocmoc1** [glpi-project/glpi#11210]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.7

### Bug description

Coudn't import users from Ldap. Ldap connectivuty test is successed. But during import i got an error "Failed operation
(0 authorizations problems, 1 failures)
a49d15a2-77d7-468d-96dc-327719ca1c54: Error on executing the action".
And coudn't find anythin in logs.

GLPI and DB runs in containers.

**Comment by kocmoc1** [comment]
It's my mistake, some libs wasn't installed in docker

**Comment by nikolaysu** [comment]
Could you describe in more detail what libraries you did not installed?
I have the same problem...

**Comment by kocmoc1** [comment]
https://github.com/kocmoc1/glpi-docker/blob/main/dockerfile
You can take this Dockerfile to create image. Its work for me.

**Comment by nikolaysu** [comment]
thank;s you very much for the answer

I do not have a docker and OS is redhat
I have all these extensions, except was apcu, installing but didn't help....

**Comment by WebGregGit** [comment]
I have problem with import too.

GLPI 10.0.1 But I checked in 9.5.6 and I had the same problem.

Failed operation
(0 authorizations problems, 1 failures)
9c913d69-6c9b-4d81-aba3-09a7b9fdf83a: Error on executing the action

![image](https://user-images.githubusercontent.com/68922721/175290835-657dca49-1ab3-48b0-887d-27ba3ff81288.png)
