### ISSUE TITLE
Problem with Crontab - GLPI

### ISSUE THREAD

**Issue by dimaiam** [glpi-project/glpi#11226]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

I have a problem with crontab:

I have installed GLPI in Ubuntu 20.04 with apache2.

When I try to run this command:

sudo -u www-data /usr/bin/php7.4 /datos/glpi/front/cron.php

I have this output

Uncaught Exception Error: Class 'mysqli' not found in /datos/glpi/inc/dbmysql.class.php at line 186

And I have correclty installed PHP 7.4.12

### Your GLPI setup information

<html>
<body>

Information about system installation and configuration
--
Check if a new version is available
[code]   GLPI 9.5.7 ( => /datos/glpi) Installation mode: TARBALL Current language:en_GB

Operating system: Linux srv-glpi-prv 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 PHP 7.3.24-3+ubuntu18.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apc, apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, 	imagick, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, recode, session, 	shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, 	zlib) Setup: max_execution_time="300" memory_limit="512M" post_max_size="200M" safe_mode="" session.save_handler="files" 	upload_max_filesize="200M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi-prv Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36 Server Software: Ubuntu 20.04 	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.34) - Perfect!  The log file has been created successfully. Write access to /datos/glpi/files/_cache has been validated. Write access to /datos/glpi/config has been validated. Write access to /datos/glpi/files/_cron has been validated. Write access to /datos/glpi/files has been validated. Write access to /datos/glpi/files/_dumps has been validated. Write access to /datos/glpi/files/_graphs has been validated. Write access to /datos/glpi/files/_lock has been validated. Write access to /datos/glpi/files/_pictures has been validated. Write access to /datos/glpi/files/_plugins has been validated. Write access to /datos/glpi/files/_rss has been validated. Write access to /datos/glpi/files/_sessions has been validated. Write access to /datos/glpi/files/_tmp has been validated. Write access to /datos/glpi/files/_uploads has been validated. Write access to /datos/glpi/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /datos/glpi GLPI_CONFIG_DIR: /datos/glpi/config GLPI_VAR_DIR: /datos/glpi/files GLPI_MARKETPLACE_DIR: /datos/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /datos/glpi/files GLPI_CACHE_DIR: /datos/glpi/files/_cache GLPI_CRON_DIR: /datos/glpi/files/_cron GLPI_DUMP_DIR: /datos/glpi/files/_dumps GLPI_GRAPH_DIR: /datos/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /datos/glpi/files/_locales GLPI_LOCK_DIR: /datos/glpi/files/_lock GLPI_LOG_DIR: /datos/glpi/files/_log GLPI_PICTURE_DIR: /datos/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /datos/glpi/files/_plugins GLPI_RSS_DIR: /datos/glpi/files/_rss GLPI_SESSION_DIR: /datos/glpi/files/_sessions GLPI_TMP_DIR: /datos/glpi/files/_tmp GLPI_UPLOAD_DIR: /datos/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /datos/glpi/locales GLPI_VERSION: 9.5.7 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/datos/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/datos/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/datos/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/datos/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/datos/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/datos/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/datos/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/datos/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/datos/glpi/vendor/sabre/http/lib) sabre/uri in (/datos/glpi/vendor/sabre/uri/lib) sabre/vobject in (/datos/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/datos/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/datos/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/datos/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/datos/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/datos/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/datos/glpi/vendor/elvanto/litemoji/src) symfony/console in (/datos/glpi/vendor/symfony/console) scssphp/scssphp in (/datos/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/datos/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/datos/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/datos/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/datos/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/datos/glpi/vendor/ramsey/uuid/src) psr/log in (/datos/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/datos/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/datos/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/datos/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/datos/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/datos/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/datos/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Server: '192.168.200.66', Port: '389', BaseDN: 'ou=USUARIS,dc=pius,dc=local', Connection filter: '(objectClass=user)', RootDN: 		'CN=gesintra,OU=USUARIS,dc=pius,dc=local', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (informatica@mailboxsrv)

Name: 'glpi@piushospital.cat' Active: Yes 	Server: '{localhost}' Login: '' Password: Yes

fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	geninventorynumber   Name: geninventorynumber             Version: 2.5.0      State: Installed / not activated
[/code]

</body>
</html>Information about system installation and configuration
[Check if a new version is available](http://glpi-prv/front/config.form.php?check_version)
[code]
 
GLPI 9.5.7 ( => /datos/glpi)
Installation mode: TARBALL
Current language:en_GB

Server
 
Operating system: Linux srv-glpi-prv 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64
PHP 7.3.24-3+ubuntu18.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apc, apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv,
	imagick, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, recode, session,
	shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi-prv Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36 Edg/100.0.1185.36
Server Software: Ubuntu 20.04
	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.3.34) - Perfect!Database version seems correct (10.3.34) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to /datos/glpi/files/_cache has been validated.Write access to /datos/glpi/files/_cache has been validated.
Write access to /datos/glpi/config has been validated.Write access to /datos/glpi/config has been validated.
Write access to /datos/glpi/files/_cron has been validated.Write access to /datos/glpi/files/_cron has been validated.
Write access to /datos/glpi/files has been validated.Write access to /datos/glpi/files has been validated.
Write access to /datos/glpi/files/_dumps has been validated.Write access to /datos/glpi/files/_dumps has been validated.
Write access to /datos/glpi/files/_graphs has been validated.Write access to /datos/glpi/files/_graphs has been validated.
Write access to /datos/glpi/files/_lock has been validated.Write access to /datos/glpi/files/_lock has been validated.
Write access to /datos/glpi/files/_pictures has been validated.Write access to /datos/glpi/files/_pictures has been validated.
Write access to /datos/glpi/files/_plugins has been validated.Write access to /datos/glpi/files/_plugins has been validated.
Write access to /datos/glpi/files/_rss has been validated.Write access to /datos/glpi/files/_rss has been validated.
Write access to /datos/glpi/files/_sessions has been validated.Write access to /datos/glpi/files/_sessions has been validated.
Write access to /datos/glpi/files/_tmp has been validated.Write access to /datos/glpi/files/_tmp has been validated.
Write access to /datos/glpi/files/_uploads has been validated.Write access to /datos/glpi/files/_uploads has been validated.
Write access to /datos/glpi/marketplace has been validated.Write access to /datos/glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

GLPI constants
 
GLPI_ROOT: /datos/glpi
GLPI_CONFIG_DIR: /datos/glpi/config
GLPI_VAR_DIR: /datos/glpi/files
GLPI_MARKETPLACE_DIR: /datos/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /datos/glpi/files
GLPI_CACHE_DIR: /datos/glpi/files/_cache
GLPI_CRON_DIR: /datos/glpi/files/_cron
GLPI_DUMP_DIR: /datos/glpi/files/_dumps
GLPI_GRAPH_DIR: /datos/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /datos/glpi/files/_locales
GLPI_LOCK_DIR: /datos/glpi/files/_lock
GLPI_LOG_DIR: /datos/glpi/files/_log
GLPI_PICTURE_DIR: /datos/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /datos/glpi/files/_plugins
GLPI_RSS_DIR: /datos/glpi/files/_rss
GLPI_SESSION_DIR: /datos/glpi/files/_sessions
GLPI_TMP_DIR: /datos/glpi/files/_tmp
GLPI_UPLOAD_DIR: /datos/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /datos/glpi/locales
GLPI_VERSION: 9.5.7
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/datos/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/datos/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/datos/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/datos/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/datos/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/datos/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/datos/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/datos/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/datos/glpi/vendor/sabre/http/lib)
sabre/uri in (/datos/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/datos/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/datos/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/datos/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/datos/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/datos/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/datos/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/datos/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/datos/glpi/vendor/symfony/console)
scssphp/scssphp in (/datos/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/datos/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/datos/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/datos/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/datos/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/datos/glpi/vendor/ramsey/uuid/src)
psr/log in (/datos/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/datos/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/datos/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/datos/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/datos/glpi/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/datos/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/datos/glpi/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

LDAP directories
 
Server: '192.168.200.66', Port: '389', BaseDN: 'ou=USUARIS,dc=pius,dc=local', Connection filter: '(objectClass=user)', RootDN:
		'CN=gesintra,OU=USUARIS,dc=pius,dc=local', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+TLS (informatica@mailboxsrv)

Mails receivers
 
Name: 'glpi@piushospital.cat' Active: Yes
	Server: '{localhost}' Login: '' Password: Yes

Plugins list
 
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	geninventorynumber   Name: geninventorynumber             Version: 2.5.0      State: Installed / not activated

[/code]
To copy/paste in your support request

**Comment by cedric-anne** [comment]
> Uncaught Exception Error: Class 'mysqli' not found in /datos/glpi/inc/dbmysql.class.php at line 186

Hi,

It means that mysqli extension is not loaded in CLI context. You have to fix your PHP configuration.
