### ISSUE TITLE
NetInventory: No port or vlan reported in GLPI for Cisco switches

### ISSUE THREAD

**Issue by ntinti** [glpi-project/glpi#11257]
### Documentation

Yes, I read it

### Solution search

Yes, I read it

### Is your help request related to a problem?

Hello

I'm new with glpi. I've installed the newest version glpi 10rc7, glpi-inventory plugin 1.0.0rc7, glpi-agent 1.2.
For two Mikrotik switches network inventory works fine. But for Cisco catalyst C2960X and 3850 only fundamental infos are imported, like serial number, name of the device. But no ports or vlans from the switch. Only the management interface of the Cisco is in the overview. 
If I have a look at the agent log file with debug=2 and I can see a "full match for sysobjectID .1.3.6.1.4.1.9.1.1745 in database" and there are a lot of infos about network interfaces in xml form like this:
```
        <PORT>
          <IFDESCR>GigabitEthernet2/0/23</IFDESCR>
          <IFINERRORS>0</IFINERRORS>
          <IFINOCTETS>4234</IFINOCTETS>
          <IFINTERNALSTATUS>1</IFINTERNALSTATUS>
          <IFLASTCHANGE>50 days, 21:57:24.22</IFLASTCHANGE>
          <IFMTU>1500</IFMTU>
          <IFNAME>Gi2/0/23</IFNAME>
          <IFNUMBER>60</IFNUMBER>
          <IFOUTERRORS>0</IFOUTERRORS>
          <IFOUTOCTETS>213243</IFOUTOCTETS>
          <IFPORTDUPLEX>1</IFPORTDUPLEX>
          <IFSPEED>1000000000</IFSPEED>
          <IFSTATUS>2</IFSTATUS>
          <IFTYPE>6</IFTYPE>
          <MAC>00:76:86:04:e4:17</MAC>
          <TRUNK>0</TRUNK>
          <VLANS>
            <VLAN>
              <NAME>BG</NAME>
              <NUMBER>11</NUMBER>
            </VLAN>
          </VLANS>
        </PORT>
```

But it seems they where not transmitted to the server...
At the end of the run there is an error message about the uuid:
```
[Thu Mar 24 17:36:19 2022][debug2] [http client] E363C17D: received message:
<br />
<b>Warning</b>:  Undefined property: stdClass::$uuid in <b>/usr/local/www/glpi-test/src/Inventory/Asset/MainAsset.php</b> on line <b>186</b><br />
{"expiration":"24","status":"ok"}
[Thu Mar 24 17:36:19 2022][error] [http client] E363C17D: unexpected content, starting with: <br />
<b>Warning</b>:  Undefined property: stdClass::$uuid in <b>/usr/local/www/glpi-test/src/Inventory/Asset/MainAsset.php</b> on line <b>186</b><br />
```
Any idea?

### Expected behavior

Correct import of data for the Cisco

### Actions you've considered

Reading, searching, reading, new installing... A lot in the last two days...

**Comment by trasher** [comment]
I do not reproduce the "unmanaged issue" with latest nightly.
