### ISSUE TITLE
V10 RC3 + night master : Inventory Database

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi#11272]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

V10 RC3

### Bug description

I have GLPI agent 
I have GLPI V10 on same computer (localhost)

So I have at least one database mysql.

On my computer it is not shown any database for this pc : why ? how the database are scanned ?

thanks

### Your GLPI setup information

WAMP

**Comment by cconard96** [comment]
Does the database show in the inventory file? You can download and view it from the computer form under the Inventory Information section. If not, then the issue would seem to be on the agent side.
https://github.com/glpi-project/glpi-agent

If it does show in the inventory file, can you provide the information from at least the `databases_services` and `databases` sections?

**Comment by EC2311** [comment]
Hello

Thanks for you reply.

In the Json file (made with glpi agent 1.1) : how should the report of database be described ? 
I see som 'mysql' topic, but not the description of any database names

thanks
Best regards

**Comment by EC2311** [comment]
Hi @cconard96 

With the agent I am able to generate a xml file with database_services topic, but no yet fully automated, (it's a mysql db I have on my laptop and it seems that on laptop its'not foreseen)
ANyway, the topic database_services appears : it looks fine.
and when importing it in GLPI, it fails with an error : 
![image](https://user-images.githubusercontent.com/42341169/164734924-f657d732-3f75-4f65-88a4-1a80b63ad65e.png)
Here is an extract of database topic : 
   <DATABASES_SERVICES>
      <DATABASES>
        <IS_ACTIVE>1</IS_ACTIVE>
        <NAME>performance_schema</NAME>
        <SIZE>0</SIZE>
      </DATABASES>
      <DATABASES>
        <CREATION_DATE>2021-11-24 11:37:39</CREATION_DATE>
        <IS_ACTIVE>1</IS_ACTIVE>
        <NAME>sys</NAME>
        <SIZE>0</SIZE>
      </DATABASES>
      <IS_ACTIVE>1</IS_ACTIVE>
      <LAST_BOOT_DATE>2022-04-22 07:13:35</LAST_BOOT_DATE>
      <MANUFACTURER>Oracle</MANUFACTURER>
      <NAME>MySQL</NAME>
      <PORT>3306</PORT>
      <SIZE>3122</SIZE>
      <TYPE>mysql</TYPE>
      <VERSION>5.7.31</VERSION>
    </DATABASES_SERVICES>

I removed the databases_services : file well imported
I re-added the databases_services : file not imported

THanks

**Comment by trasher** [comment]
database_services does not exists in XML schema; that won't work. Use JSON format.

**Comment by trasher** [comment]
BTW, database inventories requires a plugin; that work only if there are no credentials on locally installed database (a non sense from the agent to my eyes).

There are no database in your inventory file; so you probably need the plugin. I close, this is not a GLPI bug.

**Comment by EC2311** [comment]
Hi @trasher 
Thanks for your replies

I don't understand why you say there is no database in my inventory file : they are only the lines of my db I put in the file (the delta)

![image](https://user-images.githubusercontent.com/42341169/165036280-89989c18-772f-4587-94b4-2fed56e6dad4.png)

Perhaps I need a plugin, with glpi agent and perhaps glpi inventory : but it's not explained in the extract of what it is the next v10 version
![image](https://user-images.githubusercontent.com/42341169/165036649-18bb320f-b227-40b0-a48b-f3ba4d19729a.png)

So Indeed I tried to scan my Mysql database on my laptop to try to upload the datas  in GLPI. 
Sorry for disturb
Thanks
Best regards

**Comment by trasher** [comment]
> Hi @trasher Thanks for your replies
> 
> I don't understand why you say there is no database in my inventory file : they are only the lines of my db I put in the file (the delta)

I should have write "**If** there is no database in your inventory file".

But as said, that will not work in XML format.
