### ISSUE TITLE
[GLPI 10] Associated items not defined as mandatory

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#11286]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Master

### Bug description

My ticket template have Associated Elements as Mandatory

![image](https://user-images.githubusercontent.com/13178158/163207928-3163c2d6-4574-46e6-b413-bf13af79abb9.png)

When i create a ticket, glpi don't add an red asterix as mandatory

![image](https://user-images.githubusercontent.com/13178158/163208305-970d5a99-ea7e-406c-8a26-249f99124a01.png)

**Comment by cconard96** [comment]
Issue is only visual as the mandatory rule still applies, it just isn't reflected in the UI.

**Comment by joacoetche06** [comment]
I have the same problem but with SLA. It is mandatory but it is not reflected in the UI
![image](https://github.com/glpi-project/glpi/assets/88555611/276b8102-c9d3-468d-b674-b4ed592e2905)
![image](https://github.com/glpi-project/glpi/assets/88555611/3939dd40-bb13-46c7-a6c3-c286afae77aa)

**Comment by trasher** [comment]
This issue is 2 years old. Consider opening a new one with all requested information.
