### ISSUE TITLE
GLPI 10 - RC3 - User Avatar Initials missing for random users

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#11287]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10 RC3 

### Bug description

Hi,

user avatar initials missing for random users as in attached file below.

![image](https://user-images.githubusercontent.com/22425503/163331173-c8e800e4-cfa5-4aaf-a09d-07cd8d343eb5.png)

**Comment by cedric-anne** [comment]
Hi,

What are first letter on their first name and last name ?

**Comment by roshanroche** [comment]
Hi @cedric-anne ,

for the 2nd user its A A
4th user A S

i have 450 users from LDAP and 70% dont show intials.

**Comment by cconard96** [comment]
Do you have any errors logged in `files/_log/php-errors.log` when you display this list? Do any errors show on the page if debug mode is enabled or in the browser console (F12, console tab)?

**Comment by roshanroche** [comment]
hi @cconard96 

there are no errors whatsoever .even when i enable debug mode or developer options.btw i am syncronizing users from active directory via LDAP

**Comment by cconard96** [comment]
Once they are in GLPI, the source should not matter for displaying the initials.

The initials are generated by:
1. If the current entity has anonymized users enabled and you are using the simplified interface, it will use either 'Helpdesk user' or the user's nickname (A field that only shows up in the user form if that option is enabled and selected) depending on the config option for the entity. The first 2 letters of the anonymized name are returned as the initials.
2. If the first character from the first and last name combined don't result in an empty string the first letters from each are used as the initials. If one of these fields is blank, only the first initial from the other name is used.
3. If both the first and last name are not set, the first 2 characters from the login field are used.

Initials are only used if the user's picture path is not set, but the background color is always set. If a picture path points to a missing or broken image it could potentially result in what you see. In that case, you should be able to see the failed request in the browser's debug tools under the Network tab.

**Comment by cconard96** [comment]
Also, if a user has no picture and the current entity has the display of initials disabled (doesn't seem to be the case here), then a placeholder image is used which is `/pics/picture.png` relative to your GLPI root.

**Comment by roshanroche** [comment]
@cconard96 I shall check tomorrow regarding the broken image path. I also suspect now this could be the reason. Will update u.

**Comment by roshanroche** [comment]
Hi @cconard96 @cedric-anne ,

yes indeed the issue was broken path for images. as i did not copy /files/_pictures folder from my backup.
when i clear the image it shows me the user initials.

thank you for your kind help.

**Comment by trasher** [comment]
Does not seems a bug, I close

**Comment by WebGregGit** [comment]
Hi @trasher 

I don't know - should I create a separate issue? I have problem with avatar too.

![obraz](https://user-images.githubusercontent.com/68922721/180204075-367ce9f6-3bd5-4100-b3c0-d724fc6daeaf.png)

Like you see I cleared the avatar and added it again, but e.g. when viewing notes - the photo is not displayed.

**Comment by cedric-anne** [comment]
> I don't know - should I create a separate issue?

Yes, you should, as issue may be different, and in order to provide all requested details..
