### ISSUE TITLE
[GLPI 10] missing fields  in ticket creation form

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#11284]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

In the ticket creation form, section **service level** we have 4 fields. In GLPI 9.5 we had 8 fields. Missing fields are OLA / SLA

![image](https://user-images.githubusercontent.com/14139801/163192116-59e3ca8e-14bb-47e2-a445-342cab383f4d.png)

![image](https://user-images.githubusercontent.com/14139801/163191942-76fdb7e4-6a63-455a-8cb6-1970a0a3e439.png)

### Relevant log output

```shell
none
```

### Page URL

front/ticket.form.php

### Steps To reproduce

1. open ticket creation form

### Your GLPI setup information

Latest revision of GLPI 10.0 in date id 04/11/2022

**Comment by cconard96** [comment]
The SLA/OLA for time to own or time to resolve can be set by clicking the stopwatch icon. After they are set, they show up next to the date field.

**Comment by btry** [comment]
Hi

Indeed, then we can close this issue.
