### ISSUE TITLE
Lot of space between element in search page

### ISSUE THREAD

**Issue by tomamplius** [glpi-project/glpi#11292]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0-rc3

### Bug description

When i search glpi ticket with ticket number
i need to scroll a lot because there is lot of space between elements

css div class is search-container
![2022-04-15_09-36](https://user-images.githubusercontent.com/6951820/163540710-85a2a2b7-c074-48b2-88bb-1b57d3a57c90.png)

### Steps To reproduce

search glpi ticket with ticket number

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0-rc2 ( => /usr/share/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux Z2FRINFPGLP2 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at glpi.intranet.jl.fr Port 80
)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@mysql.server.jl.fr/glpi
	Host info: mysql.server.jl.fr via TCP/IP
	
PHP version (7.4.28) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /usr/share/glpi/files/_cache has been validated.
Write access to /usr/share/glpi/config has been validated.
Write access to /usr/share/glpi/files/_cron has been validated.
Write access to /usr/share/glpi/files has been validated.
Write access to /usr/share/glpi/files/_dumps has been validated.
Write access to /usr/share/glpi/files/_graphs has been validated.
Write access to /usr/share/glpi/files/_lock has been validated.
Write access to /usr/share/glpi/files/_pictures has been validated.
Write access to /usr/share/glpi/files/_plugins has been validated.
Write access to /usr/share/glpi/files/_rss has been validated.
Write access to /usr/share/glpi/files/_sessions has been validated.
Write access to /usr/share/glpi/files/_tmp has been validated.
Write access to /usr/share/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi
GLPI_CONFIG_DIR: /usr/share/glpi/config
GLPI_VAR_DIR: /usr/share/glpi/files
GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /usr/share/glpi/files
GLPI_CACHE_DIR: /usr/share/glpi/files/_cache
GLPI_CRON_DIR: /usr/share/glpi/files/_cron
GLPI_DUMP_DIR: /usr/share/glpi/files/_dumps
GLPI_GRAPH_DIR: /usr/share/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /usr/share/glpi/files/_locales
GLPI_LOCK_DIR: /usr/share/glpi/files/_lock
GLPI_LOG_DIR: /usr/share/glpi/files/_log
GLPI_PICTURE_DIR: /usr/share/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /usr/share/glpi/files/_plugins
GLPI_RSS_DIR: /usr/share/glpi/files/_rss
GLPI_SESSION_DIR: /usr/share/glpi/files/_sessions
GLPI_TMP_DIR: /usr/share/glpi/files/_tmp
GLPI_UPLOAD_DIR: /usr/share/glpi/files/_uploads
GLPI_INVENTORY_DIR: /usr/share/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/locales
GLPI_VERSION: 10.0.0-rc2
GLPI_SCHEMA_VERSION: 10.0.0-rc2@26641609f9b8fcb8038fb220c3fcafa75a95021f
GLPI_MARKETPLACE_PRERELEASES: 1
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/share/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/share/glpi/vendor/symfony/polyfill-php80)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.33.0.24', Port: '389', BaseDN: 'DC=lanvin01fr', Connection filter:
		'(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'glpi@lanvin01fr',
		Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (anonymous@webmail.lanvin.com)

</details><details><summary>Plugins list</summary><pre> 
	activity             Name: Activités quotidiennes         Version: 3.1.0-rc2  State: Error / to clean
	addressing           Name: Adressage IP                   Version: 3.0.0-rc2  State: Error / to clean
	timelineticket       Name: Chronologie des tickets        Version: 10.0+1.0-rc1 State: Error / to clean
	mydashboard          Name: Dashboard                      Version: 2.0.0-rc3  State: Error / to clean
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.3 State: Error / to clean

</pre></details>

### Anything else?

nothing else

**Comment by cedric-anne** [comment]
Hi,

Indeed, there is something to fix here.

Issue appears on global search when using the horizontal page layout.
