### ISSUE TITLE
add group name in search headers

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#113]
Ex : 
* Followup - Descriptions
* Requester - Requester group

**Comment by yllen** [comment]
Le 09/09/2015 14:35, Alexandre Delaunay a écrit :
>
> Closed #113 <https://github.com/glpi-project/glpi/issues/113> via 
> 3cc53df 
> <https://github.com/glpi-project/glpi/commit/3cc53dfca08ece90c392abd29ad9b6198819c628>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/glpi-project/glpi/issues/113#event-404762189>.
>
Bonjour Alexandre,

Je ne comprends pas à quoi sert ce commit.
Le groupe demandeur ainsi que la description d'un suivi étaient déjà 
dans le moteur de recherche d'un ticket.

Je peux tester comment cette modif ?

Nelly

**Comment by orthagh** [comment]
Il apparaissent maintenant en entête des colonnes des listes.
Typiquement, suivi - description et tâche description.

Précédemment, ces préfixes n'apparaissaient que dans les liste du formulaire du moteur de recherche.

Donc pour tester, ajoute la colonne suivi - description dans tes displaypreferences.

**Comment by yllen** [comment]
Le 11/09/2015 11:21, Alexandre Delaunay a écrit :
>
> Il apparaissent maintenant en entête des colonnes des listes.
> Typiquement, suivi - description et tâche description.
>
> Précédemment, ces préfixes n'apparaissaient que dans les liste du 
> formulaire du moteur de recherche.
>
> Donc pour tester, ajoute la colonne suivi - description dans tes 
> displaypreferences.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/glpi-project/glpi/issues/113#issuecomment-139497684>.
>
Je suis en 0.85.5 svn sans tes modifications et je peux déjà 
sélectionner Suici-description ou Taches-description dans ma vue 
personnelle.

**Comment by orthagh** [comment]
Une fois que tu as ajouté ces colonnes en vue personnelle (et que tu as fermée celle ci), dans la liste de ticket : 
* En 0.85, tu as description et description
* Avec le master, tu as Suivi - description et Tâche - description
