### ISSUE TITLE
Cannot set Category in Knowledge Base when creating a new item

### ISSUE THREAD

**Issue by JaniraIT** [glpi-project/glpi#11312]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10 RC3

### Bug description

Cannot set Category in Knowledge Base when creating a new item.

**Comment by cconard96** [comment]
Issue still present in final 10.0.0 release.

**Comment by cconard96** [comment]
Re-added via https://github.com/glpi-project/glpi/pull/11372.
This will be included in the 10.0.1 release.
