### ISSUE TITLE
Fix display (tr) for templates / setup / entity

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1131]
For templates list : 

![image](https://cloud.githubusercontent.com/assets/13178158/19158792/5eb8cfa6-8bea-11e6-85a3-4262a9075092.png)

For template edition : 
![image](https://cloud.githubusercontent.com/assets/13178158/19158926/c3245082-8bea-11e6-98b3-494905de69b4.png)

For Setup : 

![image](https://cloud.githubusercontent.com/assets/13178158/19158940/d6b50c0e-8bea-11e6-93fa-21518b29750d.png)

For entity: 

![image](https://cloud.githubusercontent.com/assets/13178158/19158961/f87d2524-8bea-11e6-83bb-4c55ed091fb5.png)

See PR #1130

**Comment by tsmr** [comment]
See new PR #1305

**Comment by orthagh** [comment]
Merged
