### ISSUE TITLE
Minor design issue with jump to top

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#11325]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 RC3

### Bug description

Usually the 'create a ticket page' looks like this:
![image](https://user-images.githubusercontent.com/96876285/164247557-b4efcf1e-8d2e-4c3a-869b-986bf154948b.png)

However when you have a predefined text that is a bit longer it leads to this problem:
![Untitled](https://user-images.githubusercontent.com/96876285/164248186-54a98e03-f581-4605-9545-afaff9c9ad9f.jpg)

This only happens when you have to scroll.

Example text on a 27" Monitor with 1080p:
````
#
#
#
#
#
# 
#
# - 
# - 
# -
# -
# - 
# - 
# ...
# ...
>>> 
````

### Anything else?

User has horizontal layout active

EDIT:
Also in vertical layout:
![Untitled](https://user-images.githubusercontent.com/96876285/164249996-30b88899-a913-4b77-81f7-d2bfe1b237e4.jpg)

**Comment by cconard96** [comment]
What is the bug experienced here? The button is displaying any time you are not scrolled all the way to the top of the page.
Is it because it is overlapping the submit button?

**Comment by blippercop** [comment]
Yes because its overlapping.
The problem is that when it overlaps the end of the page is reached. So it stays always exactly over the button and you cannot scroll further down.
