### ISSUE TITLE
Upgrade Bug GLPI 10.0

### ISSUE THREAD

**Issue by entdecke** [glpi-project/glpi#11331]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

When I am trying to upgrade from to 9.5.7 to 10.0.0 (Stable) I am getting the following error on the Database upgrade:
SQL Error "1054": Unknown column 'calendars_id' in 'where clause' in query "UPDATE `glpi_slas` SET `use_ticket_calendar` = '1', `calendars_id` = '0' WHERE `calendars_id` = '-1'"
- Fehler in der Datenbank-Abfrage: UPDATE `glpi_slas` SET `use_ticket_calendar` = '1', `calendars_id` = '0' WHERE `calendars_id` = '-1' - Fehler ist Unknown column 'calendars_id' in 'where clause'

<img width="783" alt="Bildschirmfoto 2022-04-21 um 00 21 51" src="https://user-images.githubusercontent.com/81625476/164335394-ccccfc04-a2b2-415f-9a9f-2d78a091cf6e.png">

**Comment by roshanroche** [comment]
Hi ,
 
i am also encountering the same error while upgrading.

![image](https://user-images.githubusercontent.com/22425503/164383585-1aa6e6e4-136f-43c0-8f66-1e7cb4af758f.png)

while trying to upgrade the db via cli

![image](https://user-images.githubusercontent.com/22425503/164383728-91f53342-d860-4efd-ad25-9de8f98efd4e.png)

**Comment by Rheimans** [comment]
Stupid question, how do i do this? I do not work with SQL or PHP maybe adjusting things here and there but adding something like this is out of my wheelhouse. GLPI has always worked quite well even when upgrading databases.

**Comment by diulianovenancio** [comment]
Hi, I solved this problem by running the code `ALTER TABLE `glpi_slas` ADD `calendars_id` int unsigned NOT NULL DEFAULT '0' AFTER `use_ticket_calendar`;` directly in the bank.

**Comment by roshanroche** [comment]
Hi,

Instead use the nightly build this issue has been fixed.

**Comment by xstocler** [comment]
I cannot fix this error.
I can't find the glpi_slas table in my database
