### ISSUE TITLE
The rules do not apply to the "Location" action

### ISSUE THREAD

**Issue by eric95630** [glpi-project/glpi#11338]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10 Final

### Bug description

Hi,
I use the GLPI inventory plugin and the agent on a test PC. I use a rule to specify an entity and a location when importing a new PC from the inventory, based on the Tag.
Everything works fine except the location. The location is not assigned to the new import. While the entity is well assigned. This action "Location" seems to be ignored...
I use the rules integrated in GLPI, not the rules of the plugins.

**Comment by matheusamendola** [comment]
I have the same problem, I performed a fresh installation and even so the rule seems to be ignored. in the Rule import logs tab, the rule does not appear and the location is not defined

**Comment by eric95630** [comment]
Hello, 
I have juste implement and test your updates... But it didn't work... Same problem, the "location" in my rule is ignored. Thanks for your help

**Comment by matheusamendola** [comment]
> Hello, I have juste implement and test your updates... But it didn't work... Same problem, the "location" in my rule is ignored. Thanks for your help

I also tried here but without success, can we pass some information that helps to solve the bug?

**Comment by matheusamendola** [comment]
it looks like the localization is working now with this new push from today, but the status is not, it is blank. even with default status selected in inventory configuration

**Comment by eric95630** [comment]
I manually copy/paste the modifications in my files, and the "location" rule seems to work fine...

**Comment by roshanroche** [comment]
@matheusamendola ,

for status i used native inventory default status. it worked

![image](https://user-images.githubusercontent.com/22425503/167139846-0e604c66-1906-401d-b9dd-6eb4b2cb82eb.png)
