### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1133]
Hello

we have often this message , task creation, ticket creation, ... and we lose that we have writed .

It is very ennoying for users.

Thank you

![image](https://cloud.githubusercontent.com/assets/15144026/19184777/f757ed98-8c7e-11e6-86ba-89128fc2d2ea.png)

**Comment by tomolimo** [comment]
CSRF problem...

**Comment by tomolimo** [comment]
To be sure, you may deactivate it in `config/define.php`
There is a line: `define("GLPI_USE_CSRF_CHECK", "1");`, set it to `define("GLPI_USE_CSRF_CHECK", "0");`
BUT BEWARE THAT THIS DEACTIVATE A SECURITY CHECK!

The problem may comes from a plugin that doesn't manage CSRF in a correct way.
To be sure you may disable all the installed plugins and re-install one per one.

regards,
Tomolimo

**Comment by satyan01** [comment]
Thank you I did it

**Comment by satyan01** [comment]
What is the impact to desactivate security check ?

**Comment by tomolimo** [comment]
https://github.com/glpi-project/glpi/issues/688#issuecomment-222163022
