### ISSUE TITLE
GLPI 10 DB upgrade error

### ISSUE THREAD

**Issue by Rheimans** [glpi-project/glpi#11339]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

When updating the database i get the following error:

SQL Error "1054": Unknown column 'glpi_slas.calendars_id' in 'field list' in query "UPDATE `glpi_slas` INNER JOIN `glpi_slms` ON (`glpi_slas`.`slms_id` = `glpi_slms`.`id`) SET `glpi_slas`.`use_ticket_calendar` = `glpi_slms`.`use_ticket_calendar`, `glpi_slas`.`calendars_id` = `glpi_slms`.`calendars_id` WHERE (1)"

Can i do something to make this go away or is this something to wait for a fix?

**Comment by trasher** [comment]
https://github.com/glpi-project/glpi/issues/11331
