### ISSUE TITLE
glpi_softwares.softwares_id negative values

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#11345]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0

### Bug description

Hello,

After done an migration glpi 9.5.3 to 10.0

I must do this command : php bin/console glpi:migration:unsigned_keys

But i have 1 table that can't be migrated : 

The migration of the "glpi_softwares.softwares_id" column cannot be done because it contains negative values.

And yes indeed i have negative values :

 select count(*) from  glpi_softwares where softwares_id = '-1';
+----------+
| count(*) |
+----------+
|      838 |
+----------+

What i must do for fix this ? 

Thanks.

**Comment by cedric-anne** [comment]
`glpi_softwares.softwares_id` should not contains negative values.

You should either fix the database manually, by replacing `-1` values by `0`, either apply #10763 patch and run the command again.
