### ISSUE TITLE
[GLPI 10.0.0] Installation Error PHP Fatal error

### ISSUE THREAD

**Issue by sonntagausgang** [glpi-project/glpi#11347]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

An error occurs when trying to install the GLPI version-10.0.0 final release.
When trying to open the page, an HTTP ERROR 500 error occurs.

An error occurs when trying to install the GLPI version-10.0.0 final release.
When trying to open the page, an HTTP ERROR 500 error occurs.
The following errors appear in the /var/log/nginx/error.log file:

```
FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ValueError: class_alias(): Argument #1 ($class) must be a user-defined class name, internal class name given in /usr/share/nginx/html/glpi/vendor/laminas/laminas-servicemanager/src/autoload.php:13
Stack trace:
#0 /usr/share/nginx/html/glpi/vendor/laminas/laminas-servicemanager/src/autoload.php(13): class_alias()
#1 /usr/share/nginx/html/glpi/vendor/composer/autoload_real.php(53): require('...')
#2 /usr/share/nginx/html/glpi/vendor/composer/autoload_real.php(36): composerRequirec4bd5bfe2770859dea6d4fc84a735cad()
#3 /usr/share/nginx/html/glpi/vendor/autoload.php(12): ComposerAutoloaderInitc4bd5bfe2770859dea6d4fc84a735cad::getLoader()
#4 /usr/share/nginx/html/glpi/inc/autoload.function.php(413): require_once('...')
#5 /usr/share/nginx/html/glpi/inc/based_config.php(46): include_once('...')
#6 /usr/share/nginx/html/glpi/inc/includes.php(40): include_once('...')
#7 /usr/share/nginx/html/glpi/front/central.php(34): include('...')
#8 {main}
  thrown in /usr/share/n" while reading response header from upstream, client: client_ip, server: FQDN, request: "GET /front/central.php HTTP/1.1", upstream: "fastcgi://unix:/run/php/php8.1-fpm.sock:", host: "FQDN", referrer: "http://FQDN/front/central.php"
```
### Server configuration
1. NGINX - 1.21.6
2.  PHP - 8.1

### Steps To reproduce

1. I extract files from the archive to the web server directory.
3. I am configuring a web server to service this directory.
4. I'm going over the FQDN to glpi-10.0.0 final release in the browser.
5. I get the HTTP ERROR 500 error.

### Anything else?

By editing the file `/usr/share/nginx/html/glpi/vendor/laminas/laminas-servicemanager/src/autoload.php` and by deleting the last three lines 
```
class_alias(ContainerInterface::class, InteropContainerInterface::class);
class_alias(ContainerExceptionInterface::class, InteropContainerException::class);
class_alias(NotFoundExceptionInterface::class, InteropNotFoundException::class);

```
there are no errors and the installation was successful.

**Comment by cconard96** [comment]
This code is not a part of GLPI and it is not likely that something in GLPI triggered the error. Most likely it is related to:
https://github.com/laminas/laminas-servicemanager/issues/124

If you only host GLPI on this server or you have no other PHP app that requires the `psr` PHP extension, please disable or remove it.
