### ISSUE TITLE
Column 'itemtype' in where clause is ambiguous in query

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#11344]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0

### Bug description

Hello,

I've upgraded version 9.5.3 to 10.0 without errors.

But when i open a ticket i have this message in red banner : 

SQL Error "1052": Column 'itemtype' in where clause is ambiguous in query "SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Ticket' AND `items_id` = '8180' AND `is_deleted` = '0'"

I've have already this message in 9.5.3 but it was hided by toggle debug mode.

What i must do for fix this ?

Thanks.

**Comment by cconard96** [comment]
That error should still be hidden behind debug mode. Do have it enabled currently?

Can you get the full error from the `files/_log/sql-errors.log` file? The full error should tell us exactly where the error is occuring.

**Comment by cconard96** [comment]
In GLPI, this error should not be possible. The only 2 tables in this query are `glpi_items_tickets` and `glpi_tickets`. The first table should have the `itemtype` column but the `glpi_tickets` should not. A long time ago it had this column for some reason but it was removed in GLPI 0.90.

Can you check your database schema integrity to see how different it is from what is expected?
Using the GLPI CLI tool:
```sh
bin/console glpi:database:check_schema_integrity
```
https://glpi-user-documentation.readthedocs.io/fr/latest/cli.html#glpi-database-check-schema-integrity

There are options for more checks but I think running without any arguments will give us an idea of how many of these old columns (or tables) remain.

**Comment by kevin-m87** [comment]
`Le schéma diffère pour la table "glpi_profiles".
--- Original
+++ New
@@ @@
 CREATE TABLE `glpi_profiles` (
+  `add_followups` char(1) DEFAULT NULL,
+  `assign_ticket` char(1) DEFAULT NULL,
+  `backup` char(1) DEFAULT NULL,
+  `bookmark_public` char(1) DEFAULT NULL,
+  `budget` char(1) DEFAULT NULL,
+  `calendar` char(1) DEFAULT NULL,
+  `cartridge` char(1) DEFAULT NULL,
   `change_status` text,
   `changetemplates_id` int NOT NULL DEFAULT '0',
+  `check_update` char(1) DEFAULT NULL,
   `comment` text,
+  `computer` char(1) DEFAULT NULL,
+  `config` char(1) DEFAULT NULL,
+  `consumable` char(1) DEFAULT NULL,
+  `contact_enterprise` char(1) DEFAULT NULL,
+  `contract` char(1) DEFAULT NULL,
+  `create_incident_validation` char(1) DEFAULT NULL,
+  `create_request_validation` char(1) DEFAULT NULL,
   `create_ticket_on_login` tinyint NOT NULL DEFAULT '0',
+  `create_ticket` char(1) DEFAULT NULL,
   `date_creation` datetime DEFAULT NULL,
   `date_mod` datetime DEFAULT NULL,
+  `delete_followups` char(1) DEFAULT NULL,
+  `delete_problem` char(1) DEFAULT NULL,
+  `delete_ticket` char(1) DEFAULT NULL,
+  `delete_validations` char(1) DEFAULT NULL,
+  `device` char(1) DEFAULT NULL,
+  `document` char(1) DEFAULT NULL,
+  `dropdown` char(1) DEFAULT NULL,
+  `edit_all_problem` char(1) DEFAULT NULL,
+  `entity_dropdown` char(1) DEFAULT NULL,
+  `entity_helpdesk` char(1) DEFAULT NULL,
+  `entity_rule_ticket` char(1) DEFAULT NULL,
+  `entity` char(1) DEFAULT NULL,
+  `faq` char(1) DEFAULT NULL,
+  `global_add_followups` char(1) DEFAULT NULL,
+  `global_add_tasks` char(1) DEFAULT NULL,
+  `group_add_followups` char(1) DEFAULT NULL,
+  `group` char(1) DEFAULT NULL,
   `helpdesk_hardware` int NOT NULL DEFAULT '0',
   `helpdesk_item_type` text,
   `id` int NOT NULL AUTO_INCREMENT,
+  `import_externalauth_users` char(1) DEFAULT NULL,
+  `infocom` char(1) DEFAULT NULL,
   `interface` varchar(255) DEFAULT 'helpdesk',
+  `internet` char(1) DEFAULT NULL,
   `is_default` tinyint NOT NULL DEFAULT '0',
+  `knowbase_admin` char(1) DEFAULT NULL,
+  `knowbase` char(1) DEFAULT NULL,
+  `link` char(1) DEFAULT NULL,
+  `logs` char(1) DEFAULT NULL,
   `managed_domainrecordtypes` text,
+  `monitor` char(1) DEFAULT NULL,
   `name` varchar(255) DEFAULT NULL,
+  `networking` char(1) DEFAULT NULL,
+  `notes` char(1) DEFAULT NULL,
+  `notification` char(1) DEFAULT NULL,
+  `observe_ticket` char(1) DEFAULT NULL,
+  `own_ticket` char(1) DEFAULT NULL,
+  `password_update` char(1) DEFAULT NULL,
+  `peripheral` char(1) DEFAULT NULL,
+  `phone` char(1) DEFAULT NULL,
+  `printer` char(1) DEFAULT NULL,
   `problem_status` text,
   `problemtemplates_id` int NOT NULL DEFAULT '0',
+  `profile` char(1) DEFAULT NULL,
+  `reminder_public` char(1) DEFAULT NULL,
+  `reports` char(1) DEFAULT NULL,
+  `reservation_central` char(1) DEFAULT NULL,
+  `reservation_helpdesk` char(1) DEFAULT NULL,
+  `rssfeed_public` char(1) DEFAULT NULL,
+  `rule_dictionnary_dropdown` char(1) DEFAULT NULL,
+  `rule_dictionnary_printer` char(1) DEFAULT NULL,
+  `rule_dictionnary_software` char(1) DEFAULT NULL,
+  `rule_import` char(1) DEFAULT NULL,
+  `rule_ldap` char(1) DEFAULT NULL,
+  `rule_mailcollector` char(1) DEFAULT NULL,
+  `rule_softwarecategories` char(1) DEFAULT NULL,
+  `rule_ticket` char(1) DEFAULT NULL,
+  `search_config_global` char(1) DEFAULT NULL,
+  `search_config` char(1) DEFAULT NULL,
+  `show_all_planning` char(1) DEFAULT NULL,
+  `show_all_problem` char(1) DEFAULT NULL,
+  `show_all_ticket` char(1) DEFAULT NULL,
+  `show_assign_ticket` char(1) DEFAULT NULL,
+  `show_full_ticket` char(1) DEFAULT NULL,
+  `show_group_hardware` char(1) DEFAULT NULL,
+  `show_group_planning` char(1) DEFAULT NULL,
+  `show_group_ticket` char(1) DEFAULT NULL,
+  `show_my_problem` char(1) DEFAULT NULL,
+  `show_planning` char(1) DEFAULT NULL,
+  `sla` char(1) DEFAULT NULL,
+  `software` char(1) DEFAULT NULL,
+  `statistic` char(1) DEFAULT NULL,
+  `steal_ticket` char(1) DEFAULT NULL,
   `ticket_status` text,
+  `ticketcost` char(1) DEFAULT NULL,
+  `ticketrecurrent` char(1) DEFAULT NULL,
+  `tickettemplate` char(1) DEFAULT NULL,
   `tickettemplates_id` int NOT NULL DEFAULT '0',
+  `transfer` char(1) DEFAULT NULL,
+  `typedoc` char(1) DEFAULT NULL,
+  `update_followups` char(1) DEFAULT NULL,
+  `update_own_followups` char(1) DEFAULT NULL,
+  `update_priority` char(1) DEFAULT NULL,
+  `update_tasks` char(1) DEFAULT NULL,
+  `update_ticket` char(1) DEFAULT NULL,
+  `user_authtype` char(1) DEFAULT NULL,
+  `user` char(1) DEFAULT NULL,
+  `validate_incident` char(1) DEFAULT NULL,
+  `validate_request` char(1) DEFAULT NULL,
   KEY `changetemplates_id` (`changetemplates_id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
Le schéma diffère pour la table "glpi_slalevels".
--- Original
+++ New
@@ @@
   KEY `is_active` (`is_active`),
   KEY `is_recursive` (`is_recursive`),
   KEY `name` (`name`),
-  KEY `slas_id` (`slas_id`),
   PRIMARY KEY (`id`)
 )
Le schéma diffère pour la table "glpi_slms".
--- Original
+++ New
@@ @@
   `comment` text,
   `date_creation` datetime DEFAULT NULL,
   `date_mod` datetime DEFAULT NULL,
+  `definition_time` varchar(255) DEFAULT NULL,
+  `end_of_working_day` tinyint NOT NULL DEFAULT '0',
   `entities_id` int NOT NULL DEFAULT '0',
   `id` int NOT NULL AUTO_INCREMENT,
   `is_recursive` tinyint NOT NULL DEFAULT '0',
Le schéma diffère pour la table "glpi_tickets".
--- Original
+++ New
@@ @@
   `internal_time_to_own` datetime DEFAULT NULL,
   `internal_time_to_resolve` datetime DEFAULT NULL,
   `is_deleted` tinyint NOT NULL DEFAULT '0',
+  `items_id` int NOT NULL DEFAULT '0',
+  `itemtype` varchar(100) NOT NULL,
   `itilcategories_id` int NOT NULL DEFAULT '0',
+  `linkfield` int DEFAULT NULL,
   `locations_id` int NOT NULL DEFAULT '0',
   `name` varchar(255) DEFAULT NULL,
   `ola_ttr_begin_date` datetime DEFAULT NULL,
@@ @@
   KEY `internal_time_to_own` (`internal_time_to_own`),
   KEY `internal_time_to_resolve` (`internal_time_to_resolve`),
   KEY `is_deleted` (`is_deleted`),
+  KEY `item` (`itemtype`,`items_id`),
   KEY `itilcategories_id` (`itilcategories_id`),
   KEY `locations_id` (`locations_id`),
   KEY `name` (`name`),
@@ @@
   KEY `slas_id_ttr` (`slas_id_ttr`),
   KEY `solvedate` (`solvedate`),
   KEY `status` (`status`),
-  KEY `time_to_own` (`time_to_own`),
   KEY `time_to_resolve` (`time_to_resolve`),
   KEY `type` (`type`),
   KEY `urgency` (`urgency`),
`

**Comment by cconard96** [comment]
The profiles table had those extra columns removed in an even older version of GLPI (0.85) and moved to a new table for profile rights.
I'm not sure the best/safest way to get the DB schema corrected at this point. Maybe someone else has an idea.

**Comment by trasher** [comment]
If I understand well, current issue is due to very old migration that has failed in any way... The only way to go would probably be to fix that by hand.

I'm not 100% sure but since those data are not used from years, I guess extra columns could just be dropped; be sure to keep a backup in case I'm wrong.

**Comment by Ghelpme** [comment]
Hello,
I've the error message in debug mode.

The result of bin/console glpi:database:check_schema_integrity is:

Le schéma diffère pour la table "glpi_profiles".
--- Original
+++ New
@@ @@
 CREATE TABLE `glpi_profiles` (
+  `add_followups` char(1) DEFAULT NULL,
+  `assign_ticket` char(1) DEFAULT NULL,
+  `backup` char(1) DEFAULT NULL,
+  `bookmark_public` char(1) DEFAULT NULL,
+  `budget` char(1) DEFAULT NULL,
+  `calendar` char(1) DEFAULT NULL,
+  `cartridge` char(1) DEFAULT NULL,
   `change_status` text,
   `changetemplates_id` int NOT NULL DEFAULT '0',
+  `check_update` char(1) DEFAULT NULL,
   `comment` text,
+  `computer` char(1) DEFAULT NULL,
+  `config` char(1) DEFAULT NULL,
+  `consumable` char(1) DEFAULT NULL,
+  `contact_enterprise` char(1) DEFAULT NULL,
+  `contract` char(1) DEFAULT NULL,
+  `create_incident_validation` char(1) DEFAULT NULL,
+  `create_request_validation` char(1) DEFAULT NULL,
   `create_ticket_on_login` tinyint NOT NULL DEFAULT '0',
+  `create_ticket` char(1) DEFAULT NULL,
   `date_creation` datetime DEFAULT NULL,
   `date_mod` datetime DEFAULT NULL,
+  `delete_followups` char(1) DEFAULT NULL,
+  `delete_problem` char(1) DEFAULT NULL,
+  `delete_ticket` char(1) DEFAULT NULL,
+  `delete_validations` char(1) DEFAULT NULL,
+  `device` char(1) DEFAULT NULL,
+  `document` char(1) DEFAULT NULL,
+  `dropdown` char(1) DEFAULT NULL,
+  `edit_all_problem` char(1) DEFAULT NULL,
+  `entity_dropdown` char(1) DEFAULT NULL,
+  `entity_helpdesk` char(1) DEFAULT NULL,
+  `entity_rule_ticket` char(1) DEFAULT NULL,
+  `entity` char(1) DEFAULT NULL,
+  `faq` char(1) DEFAULT NULL,
+  `global_add_followups` char(1) DEFAULT NULL,
+  `global_add_tasks` char(1) DEFAULT NULL,
+  `group_add_followups` char(1) DEFAULT NULL,
+  `group` char(1) DEFAULT NULL,
   `helpdesk_hardware` int NOT NULL DEFAULT '0',
   `helpdesk_item_type` text,
   `id` int NOT NULL AUTO_INCREMENT,
+  `import_externalauth_users` char(1) DEFAULT NULL,
+  `infocom` char(1) DEFAULT NULL,
   `interface` varchar(255) DEFAULT 'helpdesk',
+  `internet` char(1) DEFAULT NULL,
   `is_default` tinyint NOT NULL DEFAULT '0',
+  `knowbase_admin` char(1) DEFAULT NULL,
+  `knowbase` char(1) DEFAULT NULL,
+  `link` char(1) DEFAULT NULL,
+  `logs` char(1) DEFAULT NULL,
   `managed_domainrecordtypes` text,
+  `monitor` char(1) DEFAULT NULL,
   `name` varchar(255) DEFAULT NULL,
+  `networking` char(1) DEFAULT NULL,
+  `notes` char(1) DEFAULT NULL,
+  `notification` char(1) DEFAULT NULL,
+  `observe_ticket` char(1) DEFAULT NULL,
+  `own_ticket` char(1) DEFAULT NULL,
+  `password_update` char(1) DEFAULT NULL,
+  `peripheral` char(1) DEFAULT NULL,
+  `phone` char(1) DEFAULT NULL,
+  `printer` char(1) DEFAULT NULL,
   `problem_status` text,
   `problemtemplates_id` int NOT NULL DEFAULT '0',
+  `profile` char(1) DEFAULT NULL,
+  `reminder_public` char(1) DEFAULT NULL,
+  `reports` char(1) DEFAULT NULL,
+  `reservation_central` char(1) DEFAULT NULL,
+  `reservation_helpdesk` char(1) DEFAULT NULL,
+  `rssfeed_public` char(1) DEFAULT NULL,
+  `rule_dictionnary_dropdown` char(1) DEFAULT NULL,
+  `rule_dictionnary_printer` char(1) DEFAULT NULL,
+  `rule_dictionnary_software` char(1) DEFAULT NULL,
+  `rule_import` char(1) DEFAULT NULL,
+  `rule_ldap` char(1) DEFAULT NULL,
+  `rule_mailcollector` char(1) DEFAULT NULL,
+  `rule_softwarecategories` char(1) DEFAULT NULL,
+  `rule_ticket` char(1) DEFAULT NULL,
+  `search_config_global` char(1) DEFAULT NULL,
+  `search_config` char(1) DEFAULT NULL,
+  `show_all_planning` char(1) DEFAULT NULL,
+  `show_all_problem` char(1) DEFAULT NULL,
+  `show_all_ticket` char(1) DEFAULT NULL,
+  `show_assign_ticket` char(1) DEFAULT NULL,
+  `show_full_ticket` char(1) DEFAULT NULL,
+  `show_group_hardware` char(1) DEFAULT NULL,
+  `show_group_planning` char(1) DEFAULT NULL,
+  `show_group_ticket` char(1) DEFAULT NULL,
+  `show_my_problem` char(1) DEFAULT NULL,
+  `show_planning` char(1) DEFAULT NULL,
+  `sla` char(1) DEFAULT NULL,
+  `software` char(1) DEFAULT NULL,
+  `statistic` char(1) DEFAULT NULL,
+  `steal_ticket` char(1) DEFAULT NULL,
   `ticket_status` text,
+  `ticketcost` char(1) DEFAULT NULL,
+  `ticketrecurrent` char(1) DEFAULT NULL,
+  `tickettemplate` char(1) DEFAULT NULL,
   `tickettemplates_id` int NOT NULL DEFAULT '0',
+  `transfer` char(1) DEFAULT NULL,
+  `typedoc` char(1) DEFAULT NULL,
+  `update_followups` char(1) DEFAULT NULL,
+  `update_own_followups` char(1) DEFAULT NULL,
+  `update_priority` char(1) DEFAULT NULL,
+  `update_tasks` char(1) DEFAULT NULL,
+  `update_ticket` char(1) DEFAULT NULL,
+  `user_authtype` char(1) DEFAULT NULL,
+  `user` char(1) DEFAULT NULL,
+  `validate_incident` char(1) DEFAULT NULL,
+  `validate_request` char(1) DEFAULT NULL,
   KEY `changetemplates_id` (`changetemplates_id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
Le schéma diffère pour la table "glpi_tickets".
--- Original
+++ New
@@ @@
   `internal_time_to_own` datetime DEFAULT NULL,
   `internal_time_to_resolve` datetime DEFAULT NULL,
   `is_deleted` tinyint NOT NULL DEFAULT '0',
+  `items_id` int NOT NULL DEFAULT '0',
+  `itemtype` varchar(100) NOT NULL,
   `itilcategories_id` int NOT NULL DEFAULT '0',
   `locations_id` int NOT NULL DEFAULT '0',
   `name` varchar(255) DEFAULT NULL,
@@ @@
   KEY `internal_time_to_own` (`internal_time_to_own`),
   KEY `internal_time_to_resolve` (`internal_time_to_resolve`),
   KEY `is_deleted` (`is_deleted`),
+  KEY `item` (`itemtype`,`items_id`),
   KEY `itilcategories_id` (`itilcategories_id`),
   KEY `locations_id` (`locations_id`),
   KEY `name` (`name`),

**Comment by Ghelpme** [comment]
I've migrated GLPI from 0.90.3 to 10.0.0

**Comment by Ghelpme** [comment]
Should I try "bin/console glpi:database:update - force"?
