### ISSUE TITLE
Stuck at new installation process - Creating database

### ISSUE THREAD

**Issue by radamesi** [glpi-project/glpi#11343]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

### Bug description

GLPI installation process is stuck at the database creation step, so we cannot finish the installation.

### Relevant log output

```shell
N/A; files/php-errors.log and files/sql-errors.log are empty.
```

### Page URL

https://glpi.exactas.unlp.edu.ar/install/install.php

### Steps To reproduce

1. Access to the installation page, select language and click OK.
2. Accept the terms & conditions.
3. Choose 'Install' for new installation.
4. At Step 0, no warnings are shown, all is OK.
5. Insert SQL Server, User (prior, I have created specific user for GLPI) and Password, with connection succesful.
6. Creating a new database or using an existing one shows the same result.
7. GLPI installation is stuck at **Step 3 Initialization of the database**. 

### Your GLPI setup information

Since I'm in a new install I'm unable to do so, but I'm using:

- Proxmox LXC Container with Ubuntu 20.04 LTS (2 cores, 32 GB disk, 2 GB RAM)
- Apache 2.4.41
- MariaDB Server 10.3.34
- PHP 7.4 with all suggested extensions enabled

### Anything else?

- config/config_db.php is properly created, I have to delete it to start again the installation.
- The browser seems to be loading another page, but I do not receive any timeout error message or similar.
- In /etc/php/7.4/apache2/php.ini, memory_limit = 128M and max_execution_time = 3600 (even higher than [GLPI manual](https://glpi-install.readthedocs.io/en/latest/prerequisites.html)).
- I have used the "Create database option" in the install section and the "Use an existing database" with an empty one, with same result.
- When I delete the GLPI database through MariaDB CLI, the deletion process is very slow (5 minutes to empty about 300 rows). I thought it was a MariaDB issue and downloaded world database and then imported it through Adminer. Database was imported in about 19 seconds.

**Comment by cedric-anne** [comment]
> When I delete the GLPI database through MariaDB CLI, the deletion process is very slow (5 minutes to empty about 300 rows).

You should consider upgrading your MariaDB server. Current version is 10.7 (10.3 version has been released in 2018), and many performance improvements have been implemented in recent versions.

**Comment by radamesi** [comment]
I was able to finish the installation through console. First, I received this message:
```
Timezones usage cannot be activated due to following errors:
 - Access to timezone database (mysql) is not allowed.
```
It's quite interesting that this suggestion did not appear under the GUI prerrequisites proccess. After accepting the message, the installation finished in about 1 minute (I will then allow access to the timezone database).

Regarding MariaDB version, I'm using 10.3.**34**, released on February 14, 2022, included with Ubuntu 20.04 LTS repositories. However, I will try to update as soon as possible to new LTS version that uses 10.6.

Thank you so much for your kind assistance and for making this wonderful tool.

**Comment by radamesi** [comment]
I removed GLPI install folder and extracted files again. I then removed the database and followed instructions regarding [Timezones](https://glpi-install.readthedocs.io/en/latest/timezones.html).

After doing that, I ran again the installation from GUI and the database initialized in about one minute.

Maybe the prerrequisites screen should show the same warning that you get when running the install from console?

**Comment by cedric-anne** [comment]
There is 2 way to update GLPI.

1. If the config file is already present on system, this prerequisite is checked and you will have the same warning.

2. If the config file is missing, then this prerequisite cannot be checked at the same step, as DB connection is not available. Check could be indeed done after definition of DB connection settings. As this is an optional prerequisite, it is not a blocker for installation/update.

Anyway, timezones usage could be activated later, see #9841, so, even if UX could be enhanced, this is not a bug.
