### ISSUE TITLE
Create new ticket for another user not easy

### ISSUE THREAD

**Issue by VanAxl** [glpi-project/glpi#11340]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10

### Bug description

On previous GLPI version (9.5.x) when a user called us directly by phone, the technician quite often uses the create ticket interface to declare the incident for that user.
We filled the new ticket with all information, and we set the requester to be the user on the phone.
On the GLPI 10 test platform, we have no easy to change the requester while creating get new ticket, it seems to be set by default to the current technician logged. and we have on the right of the creation form the "Actor", but it seems to not display all sub users of the current entity.
So the technician need to open back the ticket, after it has been created, to change its entity, and then to be able to select the good requester.
Is it a bug  ?

Many thanks.
BR,
Nicolas

### Steps To reproduce

create new ticket, try to change the requester to any users member of a sub entity.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 ( => /usr/share/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux EUVPFIntranet 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
PHP 8.0.17 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, oci8, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at glpi.valve-precision.com Port 443
)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Server Software: Debian 11
	Server Version: 10.5.12-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@euvpfsql.euvpf.valve-precision.fr/glpiTmp
	Host info: euvpfsql.euvpf.valve-precision.fr via TCP/IP
	
PHP version (8.0.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.12) is supported.
The log file has been created successfully.
Write access to /usr/share/glpi/files/_cache has been validated.
Write access to /usr/share/glpi/config has been validated.
Write access to /usr/share/glpi/files/_cron has been validated.
Write access to /usr/share/glpi/files has been validated.
Write access to /usr/share/glpi/files/_dumps has been validated.
Write access to /usr/share/glpi/files/_graphs has been validated.
Write access to /usr/share/glpi/files/_lock has been validated.
Write access to /usr/share/glpi/files/_pictures has been validated.
Write access to /usr/share/glpi/files/_plugins has been validated.
Write access to /usr/share/glpi/files/_rss has been validated.
Write access to /usr/share/glpi/files/_sessions has been validated.
Write access to /usr/share/glpi/files/_tmp has been validated.
Write access to /usr/share/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi
GLPI_CONFIG_DIR: /usr/share/glpi/config
GLPI_VAR_DIR: /usr/share/glpi/files
GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /usr/share/glpi/files
GLPI_CACHE_DIR: /usr/share/glpi/files/_cache
GLPI_CRON_DIR: /usr/share/glpi/files/_cron
GLPI_DUMP_DIR: /usr/share/glpi/files/_dumps
GLPI_GRAPH_DIR: /usr/share/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /usr/share/glpi/files/_locales
GLPI_LOCK_DIR: /usr/share/glpi/files/_lock
GLPI_LOG_DIR: /usr/share/glpi/files/_log
GLPI_PICTURE_DIR: /usr/share/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /usr/share/glpi/files/_plugins
GLPI_RSS_DIR: /usr/share/glpi/files/_rss
GLPI_SESSION_DIR: /usr/share/glpi/files/_sessions
GLPI_TMP_DIR: /usr/share/glpi/files/_tmp
GLPI_UPLOAD_DIR: /usr/share/glpi/files/_uploads
GLPI_INVENTORY_DIR: /usr/share/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/share/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/usr/share/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'euvpf.valve-precision.fr', Port: '389', BaseDN: 'OU=VPF,DC=euvpf,DC=valve-precision,DC=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'vpfadm', Use TLS:
		none
Server: '172.16.192.1', Port: '389', BaseDN: 'OU=CARROS,DC=euste,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'vpfadm', Use TLS:
		none
Server: 'eupvuk.precision.eu', Port: '389', BaseDN: 'OU=PVUK,DC=eupvuk,DC=precision,DC=eu', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=Admin
		VPF,OU=Admin,OU=PVUK,DC=eupvuk,DC=precision,DC=eu', Use TLS: none
Server: '172.16.194.2', Port: '389', BaseDN: 'DC=valvulas,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'vpfadm', Use TLS:
		none
Server: '172.16.33.11', Port: '389', BaseDN: 'dc=eudpv,dc=precision,dc=eu', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=user_ldap,OU=Users,OU=PDSE,DC=eudpv,DC=precision,DC=eu', Use TLS: none
Server: 'pritdom.intra', Port: '389', BaseDN: 'OU=PVI,DC=pritdom,DC=intra', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=VPF
		Administrator,OU=Users,OU=PVI,DC=pritdom,DC=intra', Use TLS: none
Server: 'precision-valve.com', Port: '389', BaseDN: 'DC=precision-valve,DC=com', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: none, Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (anonymous@precisionglobal-com.mail.protection.outlook.com)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additionnal fields             Version: 1.8.2      State: Not installed
	archires             Name: Architectures réseau           Version: 2.6.0      State: Not installed
	datainjection        Name: Data injection                 Version: 2.11.0     State: Enabled
	consumables          Name: Demande de consommables        Version: 1.6.0      State: Not installed
	formcreator          Name: Form Creator                   Version: 2.12.2     State: Installed / not activated
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Installed / not activated
	resources            Name: Human Resources                Version: 3.0.0-rc2  State: Enabled
	mreporting           Name: More Reporting                 Version: 1.7.3      State: Installed / not activated
	oauthimap            Name: Oauth IMAP                     Version: 1.4.0      State: Enabled
	genericobject        Name: Objects management             Version: 2.11.0     State: Not installed
	order                Name: Orders management              Version: 2.8.0      State: Enabled
	reports              Name: Rapports                       Version: 1.14.1     State: Installed / not activated
	manufacturersimports Name: Suppliers imports              Version: 2.3.1      State: Installed / not activated
	dashboard            Name: Tableau de bord                Version: 0.9.8      State: Installed / not activated

</pre></details>

**Comment by cconard96** [comment]
The actor fields seem to take into account the current user's active entities for the results. If your technicians are currently in the Root Entity and are not including sub-entities (The entity in the top right will show "Tree structure" at the end of the name), it will not include users in sub-entities.

**Comment by VanAxl** [comment]
> The actor fields seem to take into account the current user's active entities for the results. If your technicians are currently in the Root Entity and are not including sub-entities (The entity in the top right will show "Tree structure" at the end of the name), it will not include users in sub-entities.

For the test I made, I confirm that the "active entity" was the Root entity, including all sub-entities (Tree Structure is written on top right of the page). So I should get all users available as Actors, right ?
But I can only add / select Users linked to Root Entity.
If I manually change the ticket to another entity (i.e. Root > Entity1 ) I can now select all users from the Entity1, even if the current active entity remains unchanged.

**Comment by bolivarf** [comment]
The same thing happens to me, you have to change the case to the entity of the requesting user and I don't always remember which entity it belongs to, that didn't happen in version 9.x, you could choose any user in the sub-entities in glpi 10.0, you only assign a user from the current entity even if it has the tree structure activated for the sub entities.

**Comment by VanAxl** [comment]
I hope that will be corrected in the next release ... to have back the possibility to set any requester from the sub tree.

**Comment by bolivarf** [comment]
Some technicians tell me that it is very cumbersome to enter user tickets, so I check in previous versions of glpi and apparently the problem arises with the fact of joining groups and authors in the same entry, in previous versions of glpi It only allowed to place a requester when creating the ticket and it was automatically moved to the entity of the requesting user and it seems to me that it is the best behavior because 99% of the cases belong to a single user but what happens when they have more than one user out of two different sub entities to where the case is moved, only one user would have privileges to see the ticket unless the tickets have the option to be visible to the sub entities and remain in the parent entity
