### ISSUE TITLE
Tags in genericobject not saving

### ISSUE THREAD

**Issue by dnyt84** [glpi-project/glpi#11346]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

I create a genericobject called "Disk" and when I try to Tag it I get a drop down with my tags.
I select the once I want and click save but when going back to the item the tag was not saved.

**Comment by trasher** [comment]
Please report on plugin.

**Comment by dnyt84** [comment]
you guys blocked reporting under those plugins ...
