### ISSUE TITLE
Global search doesn't work

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#11355]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0

### Bug description

Hello, i'm using GLPi 10.0 and global search from tickets doesn't work anymore : 

![image](https://user-images.githubusercontent.com/55700796/164621183-ffd38094-8421-4cc0-8b73-daaab5b37d4f.png)

We have 8.1K tickets and we need a way to search tickets and their contents.
This was working fine in 9.5.3.

There is a solution ? 

Thanks.

**Comment by trasher** [comment]
Please provide logs.

**Comment by kevin-m87** [comment]
Oh yes my bad sorry.

Error: Too many tables; MariaDB can only use 61 tables in a join

[sql-errors.log](https://github.com/glpi-project/glpi/files/8537782/sql-errors.log)

**Comment by trasher** [comment]
Well , as the displayed message tell, use "items seen" criterion. This is a database limitation, not a GLPI one.

**Comment by kevin-m87** [comment]
items seen just search in titles tickets. 
We need to search in their contents too.

It was working fine in 9.5.3.

**Comment by Valyrox** [comment]
See also #5023 for more information.

**Comment by kevin-m87** [comment]
It was working fine in 9.5.3 ....

**Comment by cedric-anne** [comment]
> It was working fine in 9.5.3 ....

Yes, problem is that in GLPI 10.0, we added more search options on tickets, and for each of them, it may require additionnal joins in SQL query.

If you want to search for a term on all displayed columns, you should use the "Items seen" search feature.

**Comment by kevin-m87** [comment]
items seen just search in titles tickets.

So now we cant search in their contents ? 

We will not be able too migrate to 10.0 then :(

**Comment by cedric-anne** [comment]
just add the content column in the view

**Comment by kevin-m87** [comment]
oh ok ! Thanks !

**Comment by kevin-m87** [comment]
Hello, so after somes tests.
This requires adding several fields to do a global search on all tickets :

![image](https://user-images.githubusercontent.com/55700796/172403756-324fbd97-d71b-4cfc-a8c6-f2201528c497.png)

And unfortunately you have to enter each time the field with the value to look for.

It was much simpler and faster when the field "all" worked. Even if the search took time.

Is there any way to make this easier?
