### ISSUE TITLE
Error On GLPI Main Dashboard After Logging In

### ISSUE THREAD

**Issue by JosephLive93** [glpi-project/glpi#11351]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

After logging in I am receiving a red exclamation mark on the assistance dashboard (see image below) which cannot be removed from the dashboard. I believe this has to deal with an old version of GLPI (9.5.5) using the behaviors plugin that changed the ticket ID values.

![image](https://user-images.githubusercontent.com/43987440/164609166-498c0d6a-520d-4efa-b750-6dc97ea18888.png)

Any help would be greatly appreciated :)

### Relevant log output

```shell

[2022-04-22 03:24:26] glpiphplog.CRITICAL:   *** Uncaught Exception LogicException: To filter with a CSS selector, install the CssSelector component ("composer require symfony/css-selector"). Or use filterXpath instead. in /var/www/html/glpi/vendor/symfony/dom-crawler/Crawler.php at line 1273
  Backtrace :
  vendor/symfony/dom-crawler/Crawler.php:785         Symfony\Component\DomCrawler\Crawler->createCssSelectorConverter()
  src/Dashboard/Widget.php:1790                      Symfony\Component\DomCrawler\Crawler->filter()
  :                                                  Glpi\Dashboard\Widget::searchShowList()
  src/Dashboard/Grid.php:976                         call_user_func()
  ajax/dashboard.php:137                             Glpi\Dashboard\Grid->getCardHtml()

[2022-04-22 03:59:58] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 2 passed to Glpi\Marketplace\View::getPaginationHtml() must be of the type int, string given, called in /var/www/html/glpi/ajax/marketplace.php on line 114 in /var/www/html/glpi/src/Marketplace/View.php at line 947
  Backtrace :
  ajax/marketplace.php:114                           Glpi\Marketplace\View::getPaginationHtml()

[2022-04-22 04:05:31] glpiphplog.WARNING:   *** PHP User Warning (512): The picture '/var/www/html/glpi/files/_pictures//23/612c54b0b64412.95088147612c54b8e5423.png' referenced by the EnclosureModel with ID 2 does not exist in /var/www/html/glpi/src/CommonDBTM.php at line 5972
  Backtrace :
  src/CommonDBTM.php:5972                            trigger_error()
  .../twig/twig/src/Extension/CoreExtension.php:1607 CommonDBTM->getItemtypeOrModelPicture()
  ...aa86deb7b7e281b488731ae52d49c4bd7e643c20.php:52 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_206011b0ad02a652c0a388ffaff68260a17f52320efc136b1a62ca0bb324775b->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1323 Twig\TemplateWrapper->render()
  ...9e2fda2ae41ddb980a26ff6de5aa04871617713.php:112 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_c860d0206a4e4cb7e8a39ecfdc2e4e7b59a89b46f61f1778fe72927ba7974fca->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  ...3069a68cd53e198c2239d06e7d42da5cf3e87b5e.php:47 Twig\Template->display()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_4ed6ec878c809c4ecafc00c04cb5fbf9143262adb5c78b72911ef54261633009->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  src/Enclosure.php:96                               Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:655                             Enclosure->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

[2022-04-22 04:21:30] glpiphplog.WARNING:   *** PHP User Warning (512): Usage of "utf8" charset/collation detected, should be "utf8mb4" in /var/www/html/glpi/src/DBmysql.php at line 1985
  Backtrace :
  src/DBmysql.php:1985                               trigger_error()
  src/DBmysql.php:359                                DBmysql->checkForDeprecatedTableOptions()
  src/DBmysql.php:426                                DBmysql->query()
  marketplace/webresources/hook.php:46               DBmysql->queryOrDie()
  src/Plugin.php:773                                 plugin_webresources_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:520                 call_user_func()
  src/Marketplace/Controller.php:433                 Glpi\Marketplace\Controller->setPluginState()
  src/Marketplace/Controller.php:177                 Glpi\Marketplace\Controller->installPlugin()
  ajax/marketplace.php:72                            Glpi\Marketplace\Controller->downloadPlugin()

[2022-04-22 05:04:36] glpiphplog.WARNING: Test logger
[2022-04-22 05:17:01] glpiphplog.WARNING:   *** PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_alerts`.`items_id`. in /var/www/html/glpi/src/DBmysql.php at line 2023
  Backtrace :
  src/DBmysql.php:2023                               trigger_error()
  src/DBmysql.php:359                                DBmysql->checkForDeprecatedTableOptions()
  src/DBmysql.php:426                                DBmysql->query()
  ...behaviors-master/script/migrationFor2022.php:61 DBmysql->queryOrDie()

```

### Page URL

N/A

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.0 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux ip-172-31-25-139 5.13.0-1022-aws #24~20.04.1-Ubuntu SMP Thu Apr 7 22:10:15 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 54.227.116.164 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.44
Server Software: Ubuntu 20.04
	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	genericobject        Name: Objects management             Version: 2.12.0     State: Enabled
	webresources         Name: Web Resources                  Version: 2.0.0      State: Enabled

</pre></details>

**Comment by trasher** [comment]
Please  provide relevant php-errors.log file entries (only new lines generated from displaying the page, not the entire file).

**Comment by JosephLive93** [comment]
> Please provide relevant php-errors.log file entries (only new lines generated from displaying the page, not the entire file).

Hi trasher,

I've updated the original comment with the output of the php-errors.log file. I've removed duplicate entries and those are the errors that have appeared in the log.

Thanks!
