### ISSUE TITLE
GLPI 10 // variable timelineitems shown in email

### ISSUE THREAD

**Issue by tristangallet** [glpi-project/glpi#11368]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hello, on a fresh install, emails are showing the variable timelineitems.
Here is the copy paste of the end of the mail:

Pas de catégorie attribuée 
Description : 
Test variable ticket

[2022-04-22 15:30:28]
Rédacteur ##timelineitems.author##
Description ##timelineitems.description##
Date d'ouverture ##timelineitems.date##
Position ##timelineitems.position##
Internal type ##timelineitems.type##
Type ##timelineitems.typename##
Nombre de suivis : 1
Nombre de tâches : 0

### Steps To reproduce

Fresh install, user is using French (Français)
Add a ticket
Make a follow up.

### Your GLPI setup information

GLPI 10.0.0 ( => /var/www/html/support)
Installation mode: TARBALL
Current language:fr_FR
Operating system: Linux sv-ff-glpi 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="500M" safe_mode="" session.save_handler="files"
	upload_max_filesize="500M" 
Software: Apache (Apache Server at support.formation.forem Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.28) is supported.PHP version (7.4.28) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.Database engine version (10.5.15) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/support/files/_cache has been validated. Write access to /var/www/html/support/config has been validated. Write access to /var/www/html/support/files/_cron has been validated. Write access to /var/www/html/support/files has been validated. Write access to /var/www/html/support/files/_dumps has been validated. Write access to /var/www/html/support/files/_graphs has been validated. Write access to /var/www/html/support/files/_lock has been validated. Write access to /var/www/html/support/files/_pictures has been validated. Write access to /var/www/html/support/files/_plugins has been validated. Write access to /var/www/html/support/files/_rss has been validated. Write access to /var/www/html/support/files/_sessions has been validated. Write access to /var/www/html/support/files/_tmp has been validated. Write access to /var/www/html/support/files/_uploads has been validated.Write access to /var/www/html/support/files/_cache has been validated.
Write access to /var/www/html/support/config has been validated.
Write access to /var/www/html/support/files/_cron has been validated.
Write access to /var/www/html/support/files has been validated.
Write access to /var/www/html/support/files/_dumps has been validated.
Write access to /var/www/html/support/files/_graphs has been validated.
Write access to /var/www/html/support/files/_lock has been validated.
Write access to /var/www/html/support/files/_pictures has been validated.
Write access to /var/www/html/support/files/_plugins has been validated.
Write access to /var/www/html/support/files/_rss has been validated.
Write access to /var/www/html/support/files/_sessions has been validated.
Write access to /var/www/html/support/files/_tmp has been validated.
Write access to /var/www/html/support/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/support/marketplace has been validated.Write access to /var/www/html/support/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by aeddyau** [comment]
Can confirm I am seeing the same behaviour in a fresh install of GLPI 10.0.0

**Comment by gabrielhaasee** [comment]
cuento con el mismo error de glpi versión 10.0.0, al recibir una respuesta desde un incidente el mail llega de la siguiente forma:

[2022-04-26 23:05:31]
Escritor ##timelineitems.author##
Descripción ##timelineitems.description##
Fecha de apertura ##timelineitems.date##
Posición ##timelineitems.position##
Internal type ##timelineitems.type##
Type ##timelineitems.typename##
Número de seguimientos : 1
Número de tarefas : 0

**Comment by aeddyau** [comment]
Snapshot of received content attached.  It loops through the timeline items, but doesn't expand the macro's in the HTML version.  In the text version, it displays the content as expected.

<img width="592" alt="Screen Shot 2022-04-28 at 7 33 17 am" src="https://user-images.githubusercontent.com/104499550/165634988-f381d685-a734-4774-9dc8-9205a595f2ad.png">

**Comment by pitgtn** [comment]
Good afternoon. It is necessary to correct the source code in the translation of templates. So that ##timelineitems.description## doesn't break with span tags.
Hope it helps. I'm fine now.

**Comment by cconard96** [comment]
This was broken for new GLPI 10 installations. New installations should be fixed by #11587.
For existing installations, it seems like identifying the correct template to fix during the update process could be difficult especially if there were any changes made to it. I made a note of how to manually fix this for existing installations and included the corrected source to make it easy to copy and paste.

**Comment by aeddyau** [comment]
Thanks.    I can confirm this is resolved with the fixes mentioned above.

**Comment by rudolcas** [comment]
Hello Conrad,

I've updated the code - and YES it works, BUT the email/replies come out to be BOLD, and UNDERLINED.

![image](https://user-images.githubusercontent.com/42798291/170375293-dda3b670-c01a-49eb-aefc-e7fbaa138804.png)

Thank you ~

**Comment by rudolcas** [comment]
This ticket-template code will help many out.


[rudolcas_update_glpi_ticket_template_20220531.txt](https://github.com/glpi-project/glpi/files/8809711/rudolcas_update_glpi_ticket_template_20220531.txt)
