### ISSUE TITLE
[GLPI - 10.0.0] UI - ticket timeline scroller missing

### ISSUE THREAD

**Issue by CAberry** [glpi-project/glpi#11369]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Dear GLPI team and users !

This is a UI / UX report. While reading a ticket, the ticket content overflow is hidden and there is no way to scroll up to see previous messages.
![Screenshot from 2022-04-23 13-36-08](https://user-images.githubusercontent.com/35067345/164893301-98a3712f-9190-4922-9dd3-a830c7a0aff0.png)

Obviously, I have obfuscated the content as this is a production environment.

It seems to be that the element itil-timeline is missing some css. I will create a PR today and hopefully the fix well be accepted by the glpi team.

Have a good day and keep on doing great work !

### Page URL

http://example.com/front/ticket.form.php.id=123456789

### Steps To reproduce

1. Create a new ticket
2. Add enough messages to reach window overflow
3. You see message disappearing on top and there is no way to scroll backup

### Your GLPI setup information

GLPI 10.0.0
Apache2
Php 8.1.2

**Comment by cconard96** [comment]
I cannot recreate the issue. I tested with multiple window sizes and they all had the correct overflow CSS with the exception of very small screens where the height of the timeline grew to accommodate all of the items as expected so no separate scrollbar was needed.

Please indicate which browser you are testing this on.

**Comment by CAberry** [comment]
Hello cconrad96

I'm using Firefox 78.15.0esr (64-bit) on a screen resolution of 1920x1080. I was not expecting this kind of answer. You say you are able to scroll up while you have many messages, more then what your resolution can handle ?

Thank you for your time,

**Comment by cconard96** [comment]
I tested on Firefox 97 (just the version I already had installed) and it worked there too. I'll try to revisit this tomorrow.

**Comment by orthagh** [comment]
i confirm on firefox esr78, scrollbars are not present

**Comment by orthagh** [comment]
@CAberry , After some investigation, this is indeed a bug with Firefox.
It should be fixed since version 81 : https://bugzilla.mozilla.org/show_bug.cgi?id=1042151
I suggest you to upgrade your browser also as a new ESR version is available, your current version is not support by mozilla anymore (since oct 2021) and you are currently vulnerable

Temporarily, you can patch glpi with this workaround:
```diff
diff --git a/templates/components/itilobject/layout.html.twig b/templates/components/itilobject/layout.html.twig
index 4b453e2ed6..d4ae680cd3 100644
--- a/templates/components/itilobject/layout.html.twig
+++ b/templates/components/itilobject/layout.html.twig
@@ -59,7 +59,7 @@
    {% endif %}
 
    <div class="row d-flex flex-column alin-items-stretch itil-object">
-      {% set fl_direction = (item.isNewItem ? 'flex-column' : 'flex-column-reverse') %}
+      {% set fl_direction = (item.isNewItem ? 'flex-column' : 'flex-column') %}
       <div class="itil-left-side col-12 {{ left_side_cls }} order-last order-md-first pt-2 pe-2 pe-md-4 d-flex {{ fl_direction }} border-top border-4">
          {% if item.isNewItem() %}
             {{ include('components/itilobject/timeline/new_form.html.twig') }}
```

This should display the scrollbars, but without the default scroll to bottom.

**Comment by CAberry** [comment]
Thank you for the heads up and for your time Orthagh. Wierd tho, i'm on bullseye and distro says I'm up to date... I will investigate.
