### ISSUE TITLE
ticket's category doesn't reload after changing the type field

### ISSUE THREAD

**Issue by KyoshiroFR** [glpi-project/glpi#11365]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0

### Bug description

Hello,

The problem only appears on a modification of an already existing ticket.
I change the type of ticket and the category does not reload to update its list in incident or request.

Works perfectly when creating a ticket.

I have the stable GLPI v10 without modifications (just notifications) or plugin

Thank you

### Your GLPI setup information

10.0.0 sans modification

**Comment by trasher** [comment]
It is asked to write only in english.

**Comment by KyoshiroFR** [comment]
Done

**Comment by trasher** [comment]
I've edited description to drop not relevant entries.

**Comment by orthagh** [comment]
Hello @KyoshiroFR 

Could you test the fix provided in #11382 
If you need quick help, you can catch me on discord.

Regards.
