### ISSUE TITLE
No username / asking username when creating ticket in simple interface

### ISSUE THREAD

**Issue by werewolf004** [glpi-project/glpi#11377]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

When a user create a new ticket (user use simple interface), ticket is create but when we go to the listing of tickets as tech / admin (with standard interface) the username of the ticket creator do not appear in the column.
If the same user use the standard interface, we check the ticket listing with tech / admin account (always in standard interface) and the username is written in the column

### Steps To reproduce

1. login with a user account who gonna use simple interface
3. create a ticket with this user account
4. log off
5. login with admin account who use standard interface
6. check ticket listing
7. the column with username is empty for the ticket created by the user who use the simple interface

### Your GLPI setup information

GLPI 10.0.0 (/glpi => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

Operating system: Linux glpi 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="5M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 192.168.0.80 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.28-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: adminmysql@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by orthagh** [comment]
see #11328 for a fix
