### ISSUE TITLE
No drop down menu on field 'User' after update to v10

### ISSUE THREAD

**Issue by PHHZV** [glpi-project/glpi#11381]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

### Bug description

After updating to version 10 i cannot select a different user on the computer object.
I have just the same option as in the field technician in change of the hardware.

https://imgur.com/a/i47IH02

Is this a bug?

**Comment by cconard96** [comment]
Please check the GLPI log files for any entries around the time you tried changing the user.
In particular, files/_log/php-errors.log and files/_log/sql-errors.log.

Also, is the issue with the dropdown not showing users or the choice isn't saving?

**Comment by PHHZV** [comment]
It doenst shows the user like it was in the previous version where i can type somehing in. When i click the button right to it leads to a page with all my users so they still exist but i cannot type or select them in any way.

**Comment by orthagh** [comment]
> files/_log/php-errors.log and files/_log/sql-errors.log.

We need these to help you 😉

**Comment by PHHZV** [comment]
Here is the php-error.log & there is no sql-errors.log in my folder

[2022-04-21 14:47:50] glpiphplog.WARNING: Test logger  
[2022-04-21 14:51:16] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6810
Compile css/palettes/auror.scss  {"user":"@phhglpi01"} 
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_keys() expects parameter 1 to be array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_keys()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_keys() expects parameter 1 to be array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_keys()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_keys() expects parameter 1 to be array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_keys()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 479
  Backtrace :
  src/Dashboard/Dashboard.php:479                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_keys() expects parameter 1 to be array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_keys()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 480
  Backtrace :
  src/Dashboard/Dashboard.php:480                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): array_intersect(): Expected parameter 2 to be an array, null given in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    array_intersect()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 14:59:54] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in /var/www/html/glpi/src/Dashboard/Dashboard.php at line 482
  Backtrace :
  src/Dashboard/Dashboard.php:482                    count()
  src/Dashboard/Dashboard.php:153                    Glpi\Dashboard\Dashboard::checkRights()
  src/Dashboard/Dashboard.php:389                    Glpi\Dashboard\Dashboard->canViewCurrent()
  src/Dashboard/Grid.php:106                         Glpi\Dashboard\Dashboard::getAll()
  src/Dashboard/Grid.php:203                         Glpi\Dashboard\Grid::loadAllDashboards()
  src/Central.php:73                                 Glpi\Dashboard\Grid::canViewOneDashboard()
  src/CommonGLPI.php:362                             Central->getTabNameForItem()
  src/Central.php:55                                 CommonGLPI->addStandardTab()
  src/CommonGLPI.php:312                             Central->defineTabs()
  src/Toolbox.php:3392                               CommonGLPI->defineAllTabs()
  ajax/updatecurrenttab.php:42                       Toolbox::getAvailablesTabs()
  
[2022-04-21 15:03:36] glpiphplog.WARNING: Test logger  
[2022-04-21 15:04:22] glpiphplog.WARNING: Test logger  
[2022-04-21 15:05:12] glpiphplog.WARNING: Test logger  
[2022-04-25 12:04:55] glpiphplog.WARNING: Test logger

**Comment by PHHZV** [comment]
Hey guys,

i fixed the issue by myself. If the user doenst have a profil, it wont show up in the drop down menu.
So i created a profil with zero permissions.

Best regards,
Marcel
