### ISSUE TITLE
Simplified interface bug

### ISSUE THREAD

**Issue by WgkLink** [glpi-project/glpi#11399]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

When opening a ticket with any profile that uses the interface, this is what happens:
![image](https://user-images.githubusercontent.com/46378849/165360820-b235eec2-7c5f-4157-a5b2-783ab90775f4.png)

I've used the default ticket template and created others, I've used other users but this is the screen I see when I try to create a ticket with a simplified interface.

When editing a ticket template, you can see that the preview appears correctly:
![image](https://user-images.githubusercontent.com/46378849/165362006-5bf723b8-170e-40a0-a338-1e5a2b583193.png)

This is a homologation environment where it was updated from version 9.5.3 to 10.0.0.

### Steps To reproduce

Open a ticket with any profile that uses a simplified interface.

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.0 (/glpi => /usr/share/nginx/suporte.domain.local/glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux sv-glpi-10 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64
PHP 8.1.2 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.18.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.28-0ubuntu4
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.2) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.28) is supported.
The log file has been created successfully.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_cache has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/config has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_cron has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_dumps has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_graphs has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_lock has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_pictures has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_plugins has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_rss has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_sessions has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_tmp has been validated.
Write access to /usr/share/nginx/suporte.domain.local/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/nginx/suporte.domain.local/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/nginx/suporte.domain.local/glpi
GLPI_CONFIG_DIR: /usr/share/nginx/suporte.domain.local/glpi/config
GLPI_VAR_DIR: /usr/share/nginx/suporte.domain.local/glpi/files
GLPI_MARKETPLACE_DIR: /usr/share/nginx/suporte.domain.local/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /usr/share/nginx/suporte.domain.local/glpi/files
GLPI_CACHE_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_cache
GLPI_CRON_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_cron
GLPI_DUMP_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_dumps
GLPI_GRAPH_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_locales
GLPI_LOCK_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_lock
GLPI_LOG_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_log
GLPI_PICTURE_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_plugins
GLPI_RSS_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_rss
GLPI_SESSION_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_sessions
GLPI_TMP_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_tmp
GLPI_UPLOAD_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_uploads
GLPI_INVENTORY_DIR: /usr/share/nginx/suporte.domain.local/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/nginx/suporte.domain.local/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/share/nginx/suporte.domain.local/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/nginx/suporte.domain.local/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/nginx/suporte.domain.local/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/share/nginx/suporte.domain.local/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/share/nginx/suporte.domain.local/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/nginx/suporte.domain.local/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/nginx/suporte.domain.local/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/nginx/suporte.domain.local/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/nginx/suporte.domain.local/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/nginx/suporte.domain.local/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/nginx/suporte.domain.local/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/nginx/suporte.domain.local/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/nginx/suporte.domain.local/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/nginx/suporte.domain.local/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/nginx/suporte.domain.local/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/nginx/suporte.domain.local/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/nginx/suporte.domain.local/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/nginx/suporte.domain.local/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/nginx/suporte.domain.local/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/nginx/suporte.domain.local/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/nginx/suporte.domain.local/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/nginx/suporte.domain.local/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/nginx/suporte.domain.local/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/nginx/suporte.domain.local/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/nginx/suporte.domain.local/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/nginx/suporte.domain.local/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/nginx/suporte.domain.local/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/nginx/suporte.domain.local/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/nginx/suporte.domain.local/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/nginx/suporte.domain.local/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/nginx/suporte.domain.local/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/nginx/suporte.domain.local/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/nginx/suporte.domain.local/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/nginx/suporte.domain.local/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/nginx/suporte.domain.local/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/nginx/suporte.domain.local/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/share/nginx/suporte.domain.local/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/nginx/suporte.domain.local/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/nginx/suporte.domain.local/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>LDAP directories</summary><pre> 
Server: '172.16.42.10', Port: '389', BaseDN: 'dc=domain,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'glpibind@domain.local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (glpi@domain.net.br@br124.hostgator.com.br)

</details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertas                        Version: 1.10.0     State: Enabled
	behaviors            Name: Comportamentos                 Version: 2.4.0      State: Error / to clean
	addressing           Name: Endereçamento IP               Version: 3.0.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.11.2     State: Installed / not activated
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.9.0      State: Enabled
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.0     State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.0      State: Error / to clean
	mreporting           Name: Mais Relatórios                Version: 1.8.0      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Error / to clean
	dashboard            Name: Painel                         Version: 1.0.1      State: Error / to clean
	reservation          Name: Reservation                    Version: 2.3.5      State: Error / to clean

</pre></details>

**Comment by cconard96** [comment]
Please include requested relevant log output from `files/_log/php-errors.log` and `files/_log/sql-errors.log`.

**Comment by WgkLink** [comment]
Sorry, I had already reported this same bug in issue 10570 https://github.com/glpi-project/glpi/issues/10570,
Anyway I will attach the logs.

[php-erros_100000lines.log](https://github.com/glpi-project/glpi/files/8572288/php-erros_100000lines.log)
[sql-errors.log](https://github.com/glpi-project/glpi/files/8572289/sql-errors.log)

**Comment by WgkLink** [comment]
Php-errors logs are relevant from 4/22 when I upgraded.

**Comment by cconard96** [comment]
![Screenshot from 2022-04-28 20-19-54](https://user-images.githubusercontent.com/17678637/165867619-4c9d00ea-27cf-4fa0-a71f-8a8c1f7e6a4b.png)

I cannot recreate the issue. I'm not able to identify the cause from the log files either.

**Comment by WgkLink** [comment]
Okay, I removed the observer and now it seems to be all right, I'll wait for the new updates.
