### ISSUE TITLE
[RESOLVED] Problem: Recurring tickets do not open automatically

### ISSUE THREAD

**Issue by eitapreula1** [glpi-project/glpi#11395]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

I performed an update from GLPI 9.5.5 to GLPI 10, after this update my recurring tickets are no longer opening on the system
![Screenshot_1](https://user-images.githubusercontent.com/104442711/165319399-94aae5f3-cd00-4c7f-a6a7-6549934a51c1.png)
![Screenshot_2](https://user-images.githubusercontent.com/104442711/165319404-24806278-4ecb-465f-b382-7792778cefae.png)
![Screenshot_3](https://user-images.githubusercontent.com/104442711/165319407-a0727574-83bd-4173-b2e8-daf9d115b896.png)
.

### Page URL

http://192.168.251.167/glpi/front/ticketrecurrent.php

### Steps To reproduce

1 - Create a call template
2 - Create a recurring ticket
3 - Wait.

**Comment by Adri9994** [comment]
Hi, 

did you activate the automatic job "RecurrentItems"? Configuration->Automatic Jobs-> RecurrentItems
![image](https://user-images.githubusercontent.com/104445557/165326757-427faac6-87c0-4d85-b40c-b53645f3ab9f.png)

**Comment by eitapreula1** [comment]
Hi,
This option is activated yes, but it is no longer automatically, as soon as the tickets were opened.
Is there anything I can do?
![Screenshot_6](https://user-images.githubusercontent.com/104442711/165344588-0bb2d1f3-c51d-4312-bcb2-4a8725d10675.png)

**Comment by eitapreula1** [comment]
I managed to fix it by adding a crontab script that updates the actions
* * * * * php /var/www/html/glpi/front/cron.php &>/dev/null
