### ISSUE TITLE
10.0 : GLPI+Agent  lots of files *.xml files are generated in /var/www/html/glpi/files/_inventories.

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#11405]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

### Bug description

When I launch my glpi agent, temp *.xml files are generated in /var/www/html/glpi/files/_inventories.

I had lots of *.xml files (4000 files)

Is this wanted ?

every night I do a cron rm *.xml --force

exemple : 
![image](https://user-images.githubusercontent.com/68054991/165507177-08271ed7-8b77-45b9-885d-e7afc350df2d.png)

### Relevant log output

```shell
no log
```

### Your GLPI setup information

1. start agent with task

**Comment by steph461** [comment]
in the file  example :  same details on all files

<?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <AGENT>
      <AGENTVERSION>1.2</AGENTVERSION>
      <START>1</START>
    </AGENT>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>235948</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-2022-02-16-12-47-12</DEVICEID>
  <QUERY>SNMPQUERY</QUERY>
</REQUEST>

**Comment by trasher** [comment]
Duplicates #10356

**Comment by g-bougard** [comment]
Hi @steph461 
you can give #11518 a try. It should really fix this issue or just enable the cleantmp automatic action.

**Comment by steph461** [comment]
its ok , i see the delete file automatically
