### ISSUE TITLE
"Wathers" in simplified incident is not editable

### ISSUE THREAD

**Issue by DZbox** [glpi-project/glpi#11403]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hi,

When requester creates a ticket using simplified interface he is not able to add wathers, the area is not editable. This applies only simplified interface when I create a ticket
There was a bag fixed at RC1 and 10.0.0 here in https://github.com/glpi-project/glpi/issues/10591, maybe it can be the reason

![image](https://user-images.githubusercontent.com/72818340/165478412-efcd4c35-051e-440a-813d-aa91808ce02f.png)

**Comment by cedric-anne** [comment]
Hi,

Can you check if #11391 solves your issue ?

Regards

**Comment by DZbox** [comment]
> Hi,
> 
> Can you check if #11391 solves your issue ?
> 
> Regards

If I change this then:

![image](https://user-images.githubusercontent.com/72818340/165484557-386fa56c-ca66-44c7-bc9a-8b8b1f9fd276.png)

In this case, it no longer affects whether "int" for "$entity_id" at ConfigExtension.php is there or not.

**Comment by cedric-anne** [comment]
This new issue corresponds to #10570.
