### ISSUE TITLE
Ticket Templates Predefined Fields Don't Populate

### ISSUE THREAD

**Issue by JosephLive93** [glpi-project/glpi#11410]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

As seen below I have a predefined field and it populates in Simplified Interface when creating a ticket, however it does not populate the information in Standard Interface.

![image](https://user-images.githubusercontent.com/43987440/165679553-bc46dd4e-4d1a-40c7-bbd1-80d8d60f673b.png)

![image](https://user-images.githubusercontent.com/43987440/165679598-37ebce19-ae71-4d31-8e94-ad3d81238a61.png)

This same template was used in 9.5.5 and would work on both interfaces before upgrading.

**Comment by barte91** [comment]
I've the same problem
