### ISSUE TITLE
GLPI 10 massiveaction loop

### ISSUE THREAD

**Issue by Lifferman** [glpi-project/glpi#11419]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hi,
I build a docker install with nginx, php8.0 and traeffik.
Everything works fine, except massiveaction.php which loops (gif of bug: https://i.ibb.co/gFS4Mw2/Liaison-annuaire-LDAP-GLPI-Brave-2022-04-25-17-35-07.gif)

### Relevant log output

```shell
No error in nginx
No error in php

access.log:
172.18.0.2 - - [28/Apr/2022:14:54:10 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1318 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:10 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1318 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1322 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1316 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1321 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:11 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1316 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1317 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1322 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1317 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1321 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1318 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:12 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1316 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1317 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1317 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:13 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1323 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1322 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1321 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1318 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1321 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1317 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1322 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:14 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1323 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1320 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1315 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1322 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1319 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1322 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
172.18.0.2 - - [28/Apr/2022:14:54:15 +0000] "GET /front/massiveaction.php?identifier=1418829408 HTTP/1.1" 200 1321 "https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=1418829408" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36"
```

### Page URL

/front/massiveaction.php?identifier=1418829408

### Steps To reproduce

Import 2 users from ldap link

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0 ( => /home/app)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux 7297b258c6c4 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64
PHP 8.0.18 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, cgi-fcgi, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, posix, readline, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="-1" memory_limit="-1" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: nginx/1.21.6
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.23
	Server SQL Mode: 
	Parameters: root@db/glpi
	Host info: db via TCP/IP
	
PHP version (8.0.18) is supported.
Sessions configuration is OK.
Allocated memory is unlimited.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.23) is supported.
The log file has been created successfully.
Write access to /home/app/files/_cache has been validated.
Write access to /home/app/config has been validated.
Write access to /home/app/files/_cron has been validated.
Write access to /home/app/files has been validated.
Write access to /home/app/files/_dumps has been validated.
Write access to /home/app/files/_graphs has been validated.
Write access to /home/app/files/_lock has been validated.
Write access to /home/app/files/_pictures has been validated.
Write access to /home/app/files/_plugins has been validated.
Write access to /home/app/files/_rss has been validated.
Write access to /home/app/files/_sessions has been validated.
Write access to /home/app/files/_tmp has been validated.
Write access to /home/app/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/app/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /home/app
GLPI_CONFIG_DIR: /home/app/config
GLPI_VAR_DIR: /home/app/files
GLPI_MARKETPLACE_DIR: /home/app/marketplace
GLPI_USE_CSRF_CHECK: 0
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /home/app/files
GLPI_CACHE_DIR: /home/app/files/_cache
GLPI_CRON_DIR: /home/app/files/_cron
GLPI_DUMP_DIR: /home/app/files/_dumps
GLPI_GRAPH_DIR: /home/app/files/_graphs
GLPI_LOCAL_I18N_DIR: /home/app/files/_locales
GLPI_LOCK_DIR: /home/app/files/_lock
GLPI_LOG_DIR: /home/app/files/_log
GLPI_PICTURE_DIR: /home/app/files/_pictures
GLPI_PLUGIN_DOC_DIR: /home/app/files/_plugins
GLPI_RSS_DIR: /home/app/files/_rss
GLPI_SESSION_DIR: /home/app/files/_sessions
GLPI_TMP_DIR: /home/app/files/_tmp
GLPI_UPLOAD_DIR: /home/app/files/_uploads
GLPI_INVENTORY_DIR: /home/app/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /home/app/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/home/app/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/app/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/app/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/home/app/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/home/app/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/app/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/app/vendor/iamcal/lib_autolink)
sabre/dav in (/home/app/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/app/vendor/sabre/http/lib)
sabre/uri in (/home/app/vendor/sabre/uri/lib)
sabre/vobject in (/home/app/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/app/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/app/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/app/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/app/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/app/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/app/vendor/elvanto/litemoji/src)
symfony/console in (/home/app/vendor/symfony/console)
scssphp/scssphp in (/home/app/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/app/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/app/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/app/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/app/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/app/vendor/ramsey/uuid/src)
psr/log in (/home/app/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/app/vendor/psr/simple-cache/src)
psr/cache in (/home/app/vendor/psr/cache/src)
league/csv in (/home/app/vendor/league/csv/src)
mexitek/phpcolors in (/home/app/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/app/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/app/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/app/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/app/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/app/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/app/vendor/symfony/cache)
html2text/html2text in (/home/app/vendor/html2text/html2text/src)
symfony/dom-crawler in (/home/app/vendor/symfony/dom-crawler)
twig/twig in (/home/app/vendor/twig/twig/src)
twig/string-extra in (/home/app/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/home/app/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: '172.16.1.20', Port: '389', BaseDN: 'DC=CAD,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=ldap_glpi,OU=Comptes d'annuaire,OU=Système d'information,DC=CAD,DC=local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

**Comment by cconard96** [comment]
Please check the GLPI logs for relevant records.
`files/_log/php-errors.log` and `files/_log/sql-errors.log`

**Comment by Lifferman** [comment]
Hi,
There is no sql-error.log, even in débug mode

Here are the logs from php-errors.log:
`[2022-04-28 15:04:38] glpiphplog.WARNING: Test logger`
`[2022-04-29 11:40:17] glpiphplog.DEBUG: Html::compileScss() in /home/app/src/Html.php line 6810
Compile css/palettes/auror.scss  {"user":"2@7297b258c6c4"}`
`[2022-04-29 11:40:38] glpiphplog.DEBUG: Html::compileScss() in /home/app/src/Html.php line 6810
Compile css/standalone/dashboard.scss  {"user":"2@7297b258c6c4"}`
`[2022-04-29 11:40:39] glpiphplog.DEBUG: Html::compileScss() in /home/app/src/Html.php line 6810
Compile css/standalone/gridstack-grids.scss  {"user":"2@7297b258c6c4"}`
`[2022-04-29 11:40:40] glpiphplog.DEBUG: Html::compileScss() in /home/app/src/Html.php line 6810
Compile css/standalone/chartist.scss  {"user":"2@7297b258c6c4"}`

I can't find any error either in php, nginx or mysql...

**Comment by cconard96** [comment]
This seems like it would be an issue with the setup outside of GLPI but I don't know nginx or traefik.
Do you have a configuration option set in either that changes the referrer policy? The referrer header is used here to know where to redirect after the massive action process is done. If the header isn't set at all, you should get redirected to the home page but in this case it acts like the referrer header is set to the requested URL.

It should be easy to check this by adding:
```php
Toolbox::logDebug($_SERVER['HTTP_REFERER']);
```
to the front/massiveaction.php file above the `$ma = new MassiveAction($_POST, $_GET, 'process');` line and trying to import another user.
The referrer URL will be logged in `files/_log/php-errors.log` and should be the URL of the LDAP import page `/front/ldap.import.php`. If it is, `/front/massiveaction.php`, then it is likely something in your environment is messing with the header in a way that wasn't anticipated.

**Comment by Lifferman** [comment]
You were right, something is messing with headers:
`[2022-05-02 06:46:05] glpiphplog.DEBUG: /home/app/front/massiveaction.php line 42`
`https://glpi.douaisis-agglo.com/front/massiveaction.php?identifier=625334627  {"user":"2@7297b258c6c4"}`

I accessed nginx directly without traefik and it's the same, so the problem is probably in nginx conf...

**Comment by trasher** [comment]
Not a GLPI issue, I close

**Comment by Lifferman** [comment]
Hi,
For those who have the same problem, the problem came from a piece of code that reloads the page if the loading time was too long. As the docker's time was incorrectly set, it looped on massiveaction. It would be interesting to log by default when this happens to be able to monitor it and to fix it easily.

Cordially
