### ISSUE TITLE
CSS does not read

### ISSUE THREAD

**Issue by pedroigor17** [glpi-project/glpi#11422]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Goodnight!

When updating my glpi from version 9.5.7 to version 10.0.0, the system stops reading the CCS, leaving the page unconfigured (only text and fields).

When upgrading on a machine with another (empty) database, error does not occur.

I kindly ask for your help and thank you in advance
!
[Captura de Tela (207)](https://user-images.githubusercontent.com/104610195/165882371-5e0b0396-9b63-4693-9920-300d27a22964.png)
!

**Comment by cedric-anne** [comment]
If you copied GLPI 10.0 files into the GLPI 9.5.x directory, old and new CSS files will conflict.

When updating, you have to extract new GLPI version in an empty directory, and then copy in it `config`, `files`, `marketplace` and `plugins` directories from previous version.
