### ISSUE TITLE
backport cliinstall.php to 0.90.x ?

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1142]
Hi

I need to setup GLPi 0.90.x instances for testing purposes and cliinstall.php since GLPi 9.1 is very useful.

I backported the script and required functions / methods, it seems to work as expected. If GLPi 0.90.x is still maintained for a while,  then this backport may be useful to others.

**Comment by trasher** [comment]
If that works on 0.90.x without any other changes, I guess this could be accepted. :+1:  for me.
