### ISSUE TITLE
Locale changes dont get updated

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#11439]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10.0

### Bug description

Hi,

when .po file edited and compiled to .mo the edited changes does not take effect. even after clearing browsing cache.

is there a method to reset the translation cache like in the previous version?

**Comment by cconard96** [comment]
```
bin/console glpi:cache:clear
```

**Comment by cconard96** [comment]
Translation cache can also still be cleared from the web interface in Setup > General > Performance but you need to have debug mode turned on for your user.
