### ISSUE TITLE
Remove as much SQL as possible

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#1143]
See http://glpi-developer-documentation.readthedocs.io/en/master/devapi/querydb.html

Task tracker for commit attachement.

**Comment by ddurieux** [comment]
Perhaps good idea to use directly DBIterator, because we will do the job 2 times

**Comment by remicollet** [comment]
Yes, this is the goal of this task (with link to the warning...)

**Comment by AnaelMobilia** [comment]
Question : why did the DBmysqlIterator use a fetch_assoc and not a fetch_object ?

Imo: if we need to do a massive rewrite of SQL queries, it's "cleaner" to rewrite code as $row->attrib instead of $row["attrib"].
More POO and readable ?

Maybe we can create a new method nextPOO() in order to maintain compatibility.

**Comment by tomolimo** [comment]
Hello
I agree to have cleaner code, but, please don't forget two things: 
1. Performance, I'm not sure that POO will perform better than array access.
1. Dynamic field redirection (like $row[$field], where variable $field contains the string 'attrib': could this redirection be rewritten in POO?)

Regards,
Tomolimo

**Comment by trasher** [comment]
Hello,

I'm not sure using arrays improves performances. As for the second point, you can use `$row->$field`.

**Comment by tomolimo** [comment]
Thank you trasher,
For performances, we must do some benchmark or use existing ones

**Comment by AnaelMobilia** [comment]
I create a [benchmark](https://gist.github.com/AnaelMobilia/086c3efe66234dd78f036e1c97eb7860) as I can't found any of them actual or interesting for our problem ! ;-)

My benchmark :
  - GLPI database with 468 computers having serials.
  - Get a random 0-9 A-Z char
  - Query DB for computer with serials LIKE %char%
  - Get one by one each row with fetch_array()
  - Replay query and use fetch_object()


Raw results for 25600 queries (~711 play for each char, MySQL bandwith usage : 1.4 Go) : 
  - Global duration for results parse with fetch_array() : 21.79 s
  - Global duration for results parse with fetch_object() : 49.98 s
  - Global overtime : +56.4%,
  - => Average overtime : 0.00109 s


As the purposed change have a very low impact on performances (and regarding we are implementing an SQL query builder...), I sugggest to :
  - Conservate the function next() => no break for actual code using DBIterator
  - Add a separate function nextOOP() 
  - Let's developpers use one or the other as theirs religions want's ;-)

Regards,
Anael

**Comment by AnaelMobilia** [comment]
@trasher It appears that I put a wrong issue reference on the commit, this issue isn't closed.
Could you, please, reopen it ?

Thanks !

**Comment by trasher** [comment]
Work is in progress. Many changes has been done on 9.4/bf branch, and many others in the master after that.
Almost all direct SQL queries has been dropped already, we're finishing the job now.
