### ISSUE TITLE
Can't assign group to task

### ISSUE THREAD

**Issue by nikaro** [glpi-project/glpi#1145]
Hello,

I cannot assign a group to a task. And on the group settings i cannot switch "tasks" to "yes", it always come back to no when save the change to "yes".

![](https://i.imgur.com/oPaDDD5.png)

**Comment by Armin83** [comment]
Bad subject ;) Can't assign task right to group would be better. 
After i update to 9.1 this was default filled with yes in my installation.

Pls activate Debug Mode - i think you would get an error on save action.

**Comment by nikaro** [comment]
Here the trace i get in php-errors.log:
```
2016-10-12 08:54:42 [8@ltpsn]
  *** PHP Notice(8): Undefined index: is_task
  Backtrace :
  inc/group.class.php:279                            
  inc/commonglpi.class.php:467                       Group->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
```

After checking in the database, the field `is_task` is absent from the table `glpi_groups`. May be it's because i installed GLPI in 9.1 RC version (i've updated to 9.1 since then).

So i added the field manually with `ALTER TABLE glpi_groups ADD COLUMN `is_task` tinyint(1) NOT NULL DEFAULT '1'` and now it's working :-)
