### ISSUE TITLE
GLPI 10.0.0 - Tasks added in duplicate tickets

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi#11465]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

Sometimes I have multiple duplicate tickets and I want to remove the observer so that multiple messages on the same subject are not sent when I close the original ticket.

When I remove the observer and save, a task is added to the ticket, which is not correct. I will have to close all tasks on all repeat calls, generating more email traffic.

**Comment by cconard96** [comment]
Please include concise steps to recreate the issue you are experiencing.

**Comment by RobertoMarcelino** [comment]
The customer opened a ticket that received the number 51511. Soon after, he opened another ticket dealing with the same subject, which received the number 51512.

In ticket 51511 we added ticket 51512 as a duplicate.

When clicking save, there is an attempt to add a task to ticket 51511, which is not possible because a category is missing from the task. We use Behaviors. The duplicate ticket is successfully added despite the error message.

![image](https://user-images.githubusercontent.com/57845086/167461424-7b0a87af-3725-4693-8928-3bce0cc3fd62.png)

So that the customer doesn't receive multiple messages on the same subject, we've removed the watcher for duplicate tickets.

When saving, it shows the same error message that a category is missing in the task, when there is no need to add task to the duplicate ticket.

![image](https://user-images.githubusercontent.com/57845086/167461474-84800479-e441-4c7f-b0d1-953b6a87c515.png)

**Comment by cconard96** [comment]
This sounds like an issue with the behaviors plugin and not GLPI itself.

The plugin has config options for requiring a task category.

I suggest reviewing the plugin options and then opening an issue on their GitHub page if you continue experiencing issues with it.
https://github.com/yllen/behaviors
