### ISSUE TITLE
Question about computer item connections/relations

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#1147]
Hello!
In monitors tab on top, and in left tab named connections, we have a tool for connect it with computer
http://prnt.sc/csid3i
And computers in this dropdown list have a "computer name-serial number-inventory number" name.
On screenshot, i selected "Papanina1-5900-AP1".
Question: Where i can change some code to make this dropdown list like "computer name-inventory number" or in example above "Papanina1-AP1"?

**Comment by trasher** [comment]
There is no option for such a change

**Comment by Zegordo** [comment]
i don't need an option, just tell me please where i can modify this code part for my needs
