### ISSUE TITLE
GLPI 10.0.0: GLPI with LDAP and SSO adds "&noAUTO=1" in notification links leading to break SSO

### ISSUE THREAD

**Issue by kodicd** [glpi-project/glpi#11478]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.2

### Bug description

Hi, we’re using GLPI with LDAP and SSO. There has been a change where a link in notifications now behaves differently:

Example:
[https://glpi/index.php?redirect=SoftwareLicense_123&noAUTO=1 ](https://glpi/index.php?redirect=SoftwareLicense_123&noAUTO=1%20)

In our case the “&noAUTO=1” was not really interpreted in the past with previous versions (when an SSO-session did not take place _before_ opening the link one had to refresh and SSO took place again) – _what it does now_ is breaking the SSO-experience (login-site shows up). The whole issue seems not be be new and was already fixed in the past with GLPI 9.1.2:

https://glpi.userecho.com/en/communities/1/topics/339-remove-noauto1-url-parameter-from-email-notifications and https://github.com/glpi-project/glpi/issues/1744

* “Added Auth::LDAP to prevent adding of noAuto=1” (Fixes #1744)

Best,
Carsten

**Comment by kodicd** [comment]
PS: SSO is done with "Fields storage of the login in the HTTP request": "REMOTE_USER".

**Comment by scarpio97** [comment]
Any news about it?

**Comment by kodicd** [comment]
I can only tell this is not an issue with all notifications send out by GLPI...

**Comment by chnateag** [comment]
We currently have this issue since we updated to 10.0.0, we have to login after clicking in email link

**Comment by kodicd** [comment]
Again, this still is an issue (but not all the time) with some (not all) mail notifications: Problem still exists with GLPI 10.0.2.

**Comment by chnateag** [comment]
Up, imo this is important

**Comment by kodicd** [comment]
This still is an issue with some (not all) mail notifications: Problem still exists with GLPI 10.0.3.

**Comment by cedric-anne** [comment]
> This still is an issue with some (not all) mail notifications: Problem still exists with GLPI 10.0.3.

Can you give a list of related notifications, and what was the notification target ?

**Comment by kodicd** [comment]
Hi, thanks for coming back to me, I'm on GLPI 10.0.6 now, I'll wait for such a notification to appear and come back to you (might take some time).

**Comment by trasher** [comment]
No feedback, I close

**Comment by chestnutbak** [comment]
This is still an issue btw. Not sure why it got trashed.

**Comment by kodicd** [comment]
It was closed because I did not respond in time. Issue is still present with 10.0.9, the facts are as follows:

* Some (few) Links in GLPI reminder-mails carry at the end the mentioed string "&noAUTO=1"
* If one is not already authenticated (via SSO) login-screen comes up
* If you've already used GLPI (by calling base URLs, by calling links which do not contain "&noAUTO=1") one is authenticiated, login-screen is thenNOT shown --> that is why it was rather hard to track the issue in daily business

**Comment by cedric-anne** [comment]
Hi,

Not really sure why this `noAUTO` parameter is added to notification links. If the goal is to ensure that the link will NOT be open on a session that was not open by the email recipient, then a better solution would be to add a `uid=sha1($_SESSION['glpiID'])` param to the link, and then, in the redirect process, force the logout only if the `uid` parameter does not match the connected user.

**Comment by wixaw** [comment]
We have just migrated, and I confirm the same issue in the emails. We have links with noAUTO=1, which doesn't redirect authentication to CAS.
