### ISSUE TITLE
Solution predefined template dont work 

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#11489]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

Hi,

the solution templates saved , dont always work when chosen from the drop down. 

![image](https://user-images.githubusercontent.com/22425503/166873799-6cf5d5fb-dff0-40cf-b192-df430d54f2ad.png)

**Comment by roshanroche** [comment]
Hi,

more info.. till Glpi10 RC3 it worked fine for me..

even i noticed one more thing user mentions also doesnt work with Glpi 10.0 even with notifications enabled.

**Comment by cconard96** [comment]
Please check GLPI log files and the browser console for errors.
What issue are you seeing with the mentions feature? Does the popup menu displaying when you start typing `@` and a user name or is some other part not working?

**Comment by roshanroche** [comment]
Hi @cconard96 ,

there are no errors in GLPI log. however im getting the following errors in browser console.

![image](https://user-images.githubusercontent.com/22425503/167063202-70e7c134-5f45-4760-aaad-27957f3a2ed1.png)

while trying to add the solution following error ,

![image](https://user-images.githubusercontent.com/22425503/167063325-00f83fa4-6fab-4ebf-b16f-98f48cf6f734.png)

while using the mention , while i type @ no username is displayed and i get the following error ,

![image](https://user-images.githubusercontent.com/22425503/167063442-1ee49977-4ae5-4134-abfc-001f23fd293d.png)

**Comment by cedric-anne** [comment]
Hi, 

Which version of GLPI are you using ?
Are you using the 10.0.0 version, or a recent nightly build ?

**Comment by roshanroche** [comment]
Hi @cedric-anne ,

i downloaded the nightly build last week. after few bugs which were fixed.

**Comment by cedric-anne** [comment]
OK, so it may be due to #11430 . I have to do some checks.

**Comment by cconard96** [comment]
There is a new issue that was put in for just the user mention issue. Seems to be on a nightly build too.
#11513

**Comment by cedric-anne** [comment]
Should be fixed by #11516.
