### ISSUE TITLE
GLPI 10.0.0 - the options bar displaying problem

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#11492]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Top bar with options (Actions button and to the right of it) and the bottom bar (rows/page, showing x to y of z) are pinned if the page scrolls vertically. If there are more columns and you scroll horizontally - these options are also scrolled.

### Page URL

front/computer.php

### Steps To reproduce

1. Add a lot of columns so that they do not fit on the screen.
2. Scroll horizontally the page to see the last columns that are currently outside the visible area.
3. The options bar will also scroll.

### Anything else?

![Schowek02](https://user-images.githubusercontent.com/68922721/166892836-6458ad77-cf33-4426-96ac-6d4be608bd7d.jpg)

Additionally, the bottom bar is aligned to the width of the columns. By adding more columns you make the data "Showing x to y of z" go further to the right, until it overlaps the navigation buttons:

![Schowek05](https://user-images.githubusercontent.com/68922721/166893492-17d6ab52-eb7b-43ba-b49e-a9e6e56b7757.jpg)

**Comment by cconard96** [comment]
Can you test #11506?
