### ISSUE TITLE
LDAP search filter for group membership within groups is broken

### ISSUE THREAD

**Issue by sl077** [glpi-project/glpi#11497]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Group memberships of LDAP users defined in GroupDN (e.g. by attribute "memberUid") are not respected due to a bug in the search filter. If the form field "Search type" in Setup->Authentication->LDAP directories->Groups contains 'groups', a LDAP search for group membership within group DN should be performed, but fails.

I hope I got everything correct, so here are my findings:

The search filter for this is assembled in src/User.php->ldap_get_user_groups (currently lines 1999-2004) like this:
`$filter = "(& $group_condition ($group_member_field=$user_dn))";`

After that, the filter gets unsanitized in line 2007, to replace `&#38;` (coming from the user supplied part of the filter) to '&' :
`$filter = Sanitizer::unsanitize($filter);`

Sanitizer::unsanitize uses Sanitizer::decodeHtmlSpecialChars for this, which in turn starts with calling Sanitizer::isHtmlEncoded. And here it fails, because the RegExp defined by $special_chars_pattern matches the '&' of the search filter from src/User.php->ldap_get_user_groups and returns false. So decodeHtmlSpecialChars exits without doing anything and leaves us with an invalid search filter.

A quick&dirty fix for this would be, to either replace the '&' of the search filter with it's html encoded counterpart like this:
`$filter = "(&#38; $group_condition ...`
or to put '(& ... )' around the filter AFTER unsanitizing it:
`$filter = '(& ' . Sanitizer::unsanitize($filter) . ')';`

### Relevant log output

```shell
error.log:[Thu May 05 09:23:06.944557 2022] [php7:warn] [pid 27247] [client 2001:XXX::13:50684] PHP Warning:  ldap_search(): Search: Bad search filter in /opt/glpi-10.0.0/src/User.php on line 2006, referer: https://.../glpi/index.php?noAUTO=1
```

### Steps To reproduce

In Tab "Setup->Authentication->LDAP directories->Groups":

1. Set "Search type" to "In groups" or "In users and groups"
2. Set "Filter to search in groups", e.g. "(&(objectClass=posixGroup))"
3. Set "Group attribute containing its users", e.g. "memberUid"

Then:
1. Import LDAP groups to GLPI
2. Login with LDAP user (having group membership defined by memberUid within imported group)
3. Check group memberships within GLPI and find 1: that they are missing and 2: there is a new PHP error message in apache's error.log

### Your GLPI setup information

GLPI 10.0.0 on up-to-date Debian Bullseye amd64, Apache with PHP module
(I skip formatting all data from Setup->General->System, since I think I found the cause elsewhere. But of course I can provide them if required.)

**Comment by sl077** [comment]
Still a problem with 10.0.2.

**Comment by frakbe** [comment]
Hello, same problem here. I can confirm the bug. (glpi 10.0.1)
Removing "&" statement on group filter the sync perform without errors. But obviously sometimes it is necessary to use the "&" statement in filter.
Please, take in charge this issue and correct it on next glpi update.

**Comment by chnateag** [comment]
Hi, Same thing here

**Comment by cedric-anne** [comment]
Hi,

Can you check #12794 ?

Regards

**Comment by sl077** [comment]
Hi,

Thanks, I reverted my temporary patch and tried this (with 10.0.3) and it seems to work. At first I got an error during login, but I guess I should have restarted the server and/or the browser after patching. Successfully tried importing new LDAP users and groups, a login of a LDAP user synced his group memberships and I didn't see any new error messages in my logs.

So I think this solves the bug for me, please let me know, if I should perform additional tests.
