### ISSUE TITLE
GLPI 10.0.0 Requester does not add himself automatically to the ticket

### ISSUE THREAD

**Issue by szymik1029** [glpi-project/glpi#11499]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

The problem occurs when adding a ticket in the simplified interface. When I add a ticket via helpdesk.public.php the Requester field is not filled in the ticket list.

**Comment by cconard96** [comment]
Duplicate of #11334, #11377, #11418.

Fixed by #11328 for 10.0.1
