### ISSUE TITLE
0.85 : Pb with Default bookmark

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#115]
0.85 only
Create a bookmark for computer (but also monitor...), and make it the default one.
Go to Assets > Computers -> the default bookmark applies -> correct
Change the search criteria and Search -> it always comes back to the search criteria of the default bookmark.
It was not the case in 0.84 and it is not the case in 0.90

**Comment by yllen** [comment]
I don't reproduce this issue.
Have you errors in logs?

**Comment by blerohellec** [comment]
Neither do I. You can close. Thx
