### ISSUE TITLE
Closing ticket time issue

### ISSUE THREAD

**Issue by AlroneRhyn** [glpi-project/glpi#1150]
Hi Guys,

Closing a ticket is begining to be a real deal : it can take up to 10seconds with this method :
![statusclosing](https://cloud.githubusercontent.com/assets/8383459/19307049/c96df3c0-9078-11e6-91a0-58e04f1304f3.png) + ![save](https://cloud.githubusercontent.com/assets/8383459/19307082/e5fbd5b6-9078-11e6-96f5-8ba35df5b573.png)

When we are closing them through the Followup/task tab, no issue at all !
![folloupclosing](https://cloud.githubusercontent.com/assets/8383459/19307017/a7af62be-9078-11e6-8527-4a1dd4afecea.png)

We are runing GLPI since 6 years and it began about a year ago. The database contains 78700 closed tickets and 300 constant open tickets.

Is there anything we can do ?

Thanks a lot for your work and time !

setup :  GLPI 9.1
Linux 3.16.0-4-amd64
PHP 5.6.26-0+deb8u1 fpm-fcgi max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" upload_max_filesize="2M"
Opcache enabled and not full
Server Mysql: 5.5.50-0+deb8u1

**Comment by tomolimo** [comment]
Hello,
You may try:

1. install PHP 7.0.x: is really quicker than 5.6
1. memory_limit set to 512M instrad of 128M
1. install Mysql: 5.7:  is really quicker than 5.5
1. another hint could be to switch all tables to innodb and to increase the size of the innodb memory pool.

These are the things I did for us.

regards,
Tomolimo

**Comment by ladenree76000** [comment]
MYSQL 5.7 ? really.

are prerequites up to date ?

Prerequisites

    A web server (Apache, Nginx, IIS, etc.)
    MariaDB (or MySQL < 5.7)
    PHP 5.4 or higher

**Comment by tomolimo** [comment]
Here are the complete info of my new GLPi 9.1 test system:

[code]
 
GLPI 9.1 ( => L:\inetpub\wwwroot\glpi)

Server
 
Operating system: Windows NT ARGLPIT20 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP 7.0.11 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, soap, standard, tidy, tokenizer, wddx, wincache, xml, xmlreader, xmlrpc, xmlwriter, zip,
	zlib)
Setup: max_execution_time="300" memory_limit="1G" post_max_size="8M" safe_mode="" session.save_handler="wincache"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/8.5
	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.15-log
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
OKL:\inetpub\wwwroot\glpi/config : OK
OKL:\inetpub\wwwroot\glpi/files : OK
OKL:\inetpub\wwwroot\glpi/files/_dumps : OK
OKL:\inetpub\wwwroot\glpi/files/_sessions : OK
OKL:\inetpub\wwwroot\glpi/files/_cron : OK
OKL:\inetpub\wwwroot\glpi/files/_graphs : OK
OKL:\inetpub\wwwroot\glpi/files/_lock : OK
OKL:\inetpub\wwwroot\glpi/files/_plugins : OK
OKL:\inetpub\wwwroot\glpi/files/_tmp : OK
OKL:\inetpub\wwwroot\glpi/files/_rss : OK
OKL:\inetpub\wwwroot\glpi/files/_uploads : OK
OKL:\inetpub\wwwroot\glpi/files/_pictures : OK
OKL:\inetpub\wwwroot\glpi/files/_log : OK

Libraries
 
htmLawed version 1.1.21 in (L:\inetpub\wwwroot\glpi\lib\htmlawed)
phpCas version 1.3.4 in (L:\inetpub\wwwroot\glpi\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (L:\inetpub\wwwroot\glpi\vendor\phpmailer\phpmailer)
Zend Framework in (L:\inetpub\wwwroot\glpi\vendor\zendframework\zend-loader\src)
zetacomponents/graph in (L:\inetpub\wwwroot\glpi\vendor\zetacomponents\graph\src)
SimplePie version 1.4.1 in (L:\inetpub\wwwroot\glpi\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (L:\inetpub\wwwroot\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (L:\inetpub\wwwroot\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (L:\inetpub\wwwroot\glpi\vendor\true\punycode\src)
iacaml/autolink in (L:\inetpub\wwwroot\glpi\vendor\iamcal\lib_autolink)
sabre/vobject in (L:\inetpub\wwwroot\glpi\vendor\sabre\vobject\lib)
guzzlehttp/guzzle in (L:\inetpub\wwwroot\glpi\vendor\guzzlehttp\guzzle\src)




Plugins list
 
	accounts             Name: Accounts                       Version: 2.2.0      State: Enabled
	fields               Name: Additionnal fields             Version: 0.90-1.3   State: Enabled
	appliances           Name: Appliances                     Version: 1.8.1      State: To be cleaned
	arsurveys            Name: AR Surveys                     Version: 1.4.1      State: Enabled
	arbehaviours         Name: ARaymond Behaviours            Version: 1.2.0      State: To be cleaned
	behaviors            Name: Behaviours                     Version: 0.83.3     State: To be cleaned
	chgmeridian          Name: CHG-Meridian                   Version: 1.0.0      State: To be cleaned
	datainjection        Name: File injection                 Version: 2.4.2      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Enabled
	mask                 Name: Mask                           Version: 1.2.0      State: To be cleaned
	mreporting           Name: More Reporting                 Version: 0.90+1.2   State: Enabled
	mrules               Name: More Rules                     Version: 1.0.0      State: Enabled
	mydashboard          Name: My Dashboard                   Version: 1.3.0      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.2.3      State: Enabled
	order                Name: Orders management              Version: 0.85+1.3.1 State: Enabled
	pdf                  Name: Print to pdf                   Version: 1.0.2      State: To be cleaned
	processmaker         Name: Process Maker                  Version: 3.0.0      State: Enabled
	rayusermanagementtic Name: RayUserManagementTicket        Version: 0.83.8.2   State: To be cleaned
	relations            Name: Relations                      Version: 1.3.1      State: To be cleaned
	reports              Name: Reports                        Version: 1.6.1      State: To be cleaned
	simcard              Name: Sim cards management           Version: 1.4.2      State: Enabled
	manufacturersimports Name: Suppliers imports              Version: 1.9.0      State: Enabled
	ticketcleaner        Name: Ticket Cleaner                 Version: 2.0.4      State: Enabled
	timezones            Name: Timezones                      Version: 2.0.0      State: Enabled

OCS Inventory NG
Host: 
Connection: Ok
Use the OCSNG software dictionary: No
[/code]

**Comment by remicollet** [comment]
> memory_limit set to 512M instrad of 128M

Sounds terribly high... consumed by each process... you really need a BIG server.
In most case 64-128M should be enough.

And if MySQL 5.7 is supported thanks to some awfull hacks.... I still recommends MariaDB (which is now the default implementation in most linux distributions).

**Comment by tomolimo** [comment]
Beware that MariaDB is locking tables when doing an OPTIMIZE on innodb and mysql > 5.6.xx doesn't!
This led me to switch back to mysql instead of mariadb.
What are you speaking about when 

> And if MySQL 5.7 is supported thanks to some awfull hacks

?

**Comment by remicollet** [comment]
Here is the Hack => https://github.com/glpi-project/glpi/blob/master/inc/dbmysql.class.php#L129

(try to change GLPI_FORCE_EMPTY_SQL_MODE constant value to 0 ;)

**Comment by tomolimo** [comment]
I tried, and it changed nothing to the performances or behavior of my mysql 5.7.15
The SQL mode is now like this:

> Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.15-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP

I beleive that you are speaking about the following troubles in sql mode of the 5.7: http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-changes
But in the 5.7.8 it has been fixed:

> Important
The following discussion applies only for MySQL versions 5.7.4 through 5.7.7. For upgrades from a version older than MySQL 5.7.4, we recommend upgrading to MySQL 5.7.8 or later, which renders this discussion unnecessary.

The problem of the strict mode is between versions 5.7.4 through 5.7.7, from version 5.7.8 the strict mode has been reverted like it was in the past.

**Comment by AlroneRhyn** [comment]
Hi Guys,
I found a while ago what happened. There is action in glpi which send mails directly to the smarthost and other actions that send it in the mailqueue. The direct path way horribly slow due to the call to our smarthost.
I changed my smarthost address to 127.0.0.1 (which handle the queue) and everything was smooth again.

Bye !
