### ISSUE TITLE
Templates can be modified regardless of permission

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#11509]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 and 9.5.6

### Bug description

Go to http://127.0.0.1/helpdesk/front/setup.templates.php?itemtype=Project&add=0 and create a template with no tasks - just a name etc..

Create a new project and select your template (http://127.0.0.1/helpdesk/front/setup.templates.php?itemtype=Project&add=1) and select your template (do not save it!).

Click on project "tasks" and create a new one.

Type in a name and click add.

Go back to the original template http://127.0.0.1/helpdesk/front/setup.templates.php?itemtype=Project&add=0

You will see that the task was added to the original template.

Workaround was to remove the permission to update templates but the permission revoke didn't change anything - the technician is still able to modify the template by adding a task.

### Relevant log output

```shell
None
```

**Comment by cconard96** [comment]
What Project template permission are you referring to? There is no different permission for templates of projects.

**Comment by cconard96** [comment]
A Project is not an ITIL type (at least as far as GLPI is concerned).
Project templates use the Project permissions.

Also, please refrain from posting possible security issues publicly. The project's security policy (Listed in the Security tab of this repository) has an email address that you can send information to if you suspect you found a security vulnerability.
