### ISSUE TITLE
Deprecated strtotime()

### ISSUE THREAD

**Issue by rollandpf** [glpi-project/glpi#11511]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hello,

on my test server with errors displayed I have the following error message when I look the statistics for a ticket  

Deprecated: strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in C:\Wamp\www\glpi\src\Ticket.php on line 6283
![Error](https://user-images.githubusercontent.com/48216797/167102151-42c92863-c29e-4f5c-ab8d-985d331f1797.jpg)

### Page URL

http://localhost/glpi/front/ticket.form.php

### Steps To reproduce

Go to Assistance -> Tickets
Open a ticket
Go to the Statistics Onglet

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 (/glpi => C:\Wamp\www\glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT SIE1180918 10.0 build 16299 (Windows 10) AMD64
PHP 8.1.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	com_dotnet, ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sockets, sodium, sqlite3, standard,
	tokenizer, xdebug, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Win64) PHP/8.1.2 (Apache/2.4.52 (Win64) PHP/8.1.2 Server at localhost Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0 Waterfox/56.6.2022.04
Server Software: mariadb.org binary distribution
	Server Version: 10.2.14-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.2) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.2.14) is supported.
The log file has been created successfully.
Write access to C:\Wamp\www\glpi/files/_cache has been validated.
Write access to C:\Wamp\www\glpi/config has been validated.
Write access to C:\Wamp\www\glpi/files/_cron has been validated.
Write access to C:\Wamp\www\glpi/files has been validated.
Write access to C:\Wamp\www\glpi/files/_dumps has been validated.
Write access to C:\Wamp\www\glpi/files/_graphs has been validated.
Write access to C:\Wamp\www\glpi/files/_lock has been validated.
Write access to C:\Wamp\www\glpi/files/_pictures has been validated.
Write access to C:\Wamp\www\glpi/files/_plugins has been validated.
Write access to C:\Wamp\www\glpi/files/_rss has been validated.
Write access to C:\Wamp\www\glpi/files/_sessions has been validated.
Write access to C:\Wamp\www\glpi/files/_tmp has been validated.
Write access to C:\Wamp\www\glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\Wamp\www\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\Wamp\www\glpi
GLPI_CONFIG_DIR: C:\Wamp\www\glpi/config
GLPI_VAR_DIR: C:\Wamp\www\glpi/files
GLPI_MARKETPLACE_DIR: C:\Wamp\www\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\Wamp\www\glpi/files
GLPI_CACHE_DIR: C:\Wamp\www\glpi/files/_cache
GLPI_CRON_DIR: C:\Wamp\www\glpi/files/_cron
GLPI_DUMP_DIR: C:\Wamp\www\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\Wamp\www\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\Wamp\www\glpi/files/_locales
GLPI_LOCK_DIR: C:\Wamp\www\glpi/files/_lock
GLPI_LOG_DIR: C:\Wamp\www\glpi/files/_log
GLPI_PICTURE_DIR: C:\Wamp\www\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\Wamp\www\glpi/files/_plugins
GLPI_RSS_DIR: C:\Wamp\www\glpi/files/_rss
GLPI_SESSION_DIR: C:\Wamp\www\glpi/files/_sessions
GLPI_TMP_DIR: C:\Wamp\www\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\Wamp\www\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\Wamp\www\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\Wamp\www\glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\Wamp\www\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\Wamp\www\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\Wamp\www\glpi\vendor\simplepie\simplepie\library)
mpdf/mpdf in (C:\Wamp\www\glpi\vendor\mpdf\mpdf\src)
michelf/php-markdown in (C:\Wamp\www\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\Wamp\www\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\Wamp\www\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\Wamp\www\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\Wamp\www\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\Wamp\www\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\Wamp\www\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\Wamp\www\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\Wamp\www\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\Wamp\www\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\Wamp\www\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\Wamp\www\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\Wamp\www\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\Wamp\www\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\Wamp\www\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\Wamp\www\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\Wamp\www\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\Wamp\www\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\Wamp\www\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\Wamp\www\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\Wamp\www\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\Wamp\www\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\Wamp\www\glpi\vendor\psr\cache\src)
league/csv in (C:\Wamp\www\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\Wamp\www\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\Wamp\www\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\Wamp\www\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\Wamp\www\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\Wamp\www\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\Wamp\www\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\Wamp\www\glpi\vendor\symfony\cache)
html2text/html2text in (C:\Wamp\www\glpi\vendor\html2text\html2text\src)
symfony/dom-crawler in (C:\Wamp\www\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\Wamp\www\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\Wamp\www\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>LDAP directories</summary><pre> 
Server: '172.16.10.212', Port: '389', BaseDN: 'DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: ' 172.16.28.201', Port: '389', BaseDN: 'OU=FOYER LOCAL,DC=foyer,DC=pardalets,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,OU=FOYER LOCAL,DC=foyer,DC=pardalets,DC=local', Use TLS: none
Server: '172.16.10.225', Port: '389', BaseDN: 'OU=OLIVERAIE.USER,DC=oliveraie,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,OU=OLIVERAIE.USER,DC=oliveraie,DC=local', Use TLS: none
Server: '172.16.22.201', Port: '389', BaseDN: 'OU=mas.orri.local,DC=mas,DC=orri,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,OU=mas.orri.local,DC=mas,DC=orri,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=SIEGE,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=POLE_AD,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=POLE_ENFANCE,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=POLE_HA,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=POLE_INSERTION,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=POLE_PA,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none
Server: '172.16.10.212', Port: '389', BaseDN: 'OU=POLE_TA,DC=assosauvy,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=GLPI,CN=Users,DC=assosauvy,DC=local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (support.informatique@asso-sauvy.fr@smtp.office365.com)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.12.5     State: Installed / not activated
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Installed / not activated

</pre></details>

**Comment by cconard96** [comment]
This should be a non-blocking issue with PHP 8.1 and the message won't show up at all (unless you have GLPI debug mode on for your user but that's a smaller message) if you don't have the xdebug PHP extension enabled.

Also, having xdebug on a production server isn't really recommended. Just in terms of performance, it can make the PHP application a lot slower than it would be usually.


A fix for the deprecation issue in PHP 8.1 is in progress:
https://github.com/glpi-project/glpi/pull/11504

**Comment by rollandpf** [comment]
Thank you for your quick answser.

It's a test server I use for debugging my own applications.

Xdebug is not present on our production server.
