### ISSUE TITLE
GLPI still asks to change the passwords of generic accounts glpi, post-only, tech

### ISSUE THREAD

**Issue by Lud3rik** [glpi-project/glpi#1151]
Dear GLPI team,

After installing GLPI 9.0.5, I created the account "admin" using super admin profile. I logged off from glpi, then I logged on with admin.
GLPI was asking me to change the passwords of generic accounts glpi, post-only, tech, normal, so I deleted all the generic accounts in order to clear the reminder.
After that, I decided to upgrade to GLPI 9.1.

After the upgrade, I noticed that the reminder for changing the passwords of glpi, post-only, tech, normal is still present. But it's weird as these accounts are not written into the database.
So maybe it could be an enhancement to check if these generic accounts exist in the database before asking the admin to change the passwords.

Thank you for helping

**Comment by remicollet** [comment]
Workaround: disable these accounts (or purge the trash)

**Comment by Lud3rik** [comment]
I have tested to create again the tech account, but GLPI is saying that the account exists, but I don't see it into GUI.

**Comment by remicollet** [comment]
Fixed by PR #1153
