### ISSUE TITLE
Cannot attach document to existing ticket

### ISSUE THREAD

**Issue by ttsoukas** [glpi-project/glpi#11525]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

We have upgraded GLPI from 9.5.7 to 10.0.0. Upgrade went well (except for the signed integer conversion that could not take place for negative values). 
Using the new version, we discovered that we are not able to attach a file to an existing ticket.

### Page URL

https://helpdesk.dss.gr/front/ticket.form.php?id=10972

### Steps To reproduce

We have upgraded GLPI from 9.5.7 to 10.0.0
We are not able to attach a file to an existing ticket.
Using the following method to attach file
![image](https://user-images.githubusercontent.com/20906255/167400737-1654b9ba-d3f1-4680-aae2-a48bd0d454b6.png)
An empty bar appears on top of the ticket as to indicate that something was created, but file cannot be added.
![image](https://user-images.githubusercontent.com/20906255/167400916-e3c74a20-2250-49e2-b334-c3ffabe29584.png)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux asp01 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64
PHP 7.4.29 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, snmp, soap, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Ubuntu) (Apache/2.4.53 (Ubuntu) Server at helpdesk.dss.gr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Server Software: Percona Server (GPL), Release '34', Revision '2e68637'
	Server Version: 5.7.31-34
	Server SQL Mode: STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.29) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.31) is supported.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (helpdesk@dss.gr@mail.dss.gr)

</details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.1      State: Enabled
	activity             Name: Activities                     Version: 3.1.0      State: Enabled
	actualtime           Name: ActualTime                     Version: 1.5.1      State: Not installed
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled
	news                 Name: Alerts                         Version: 1.10.2     State: Enabled
	impacts              Name: Asset impacts                  Version: 2.0.4      State: Not installed
	badges               Name: Badges                         Version: 3.0.0      State: Enabled
	barcode              Name: Barcode                        Version: 2.6.2      State: Not installed
	behaviors            Name: Behaviours                     Version: 2.4.2      State: Not installed
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Enabled
	costs                Name: Costs                          Version: 2.2.3      State: Not installed
	credit               Name: Credit vouchers                Version: 1.11.1     State: Enabled
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled
	datainjection        Name: Data injection                 Version: 2.11.1     State: Enabled
	domains              Name: Domains                        Version: 2.1.0      State: Not installed
	manageentities       Name: Entities portal                Version: 4.0.0      State: Enabled
	escalade             Name: Escalation                     Version: 2.8.0      State: Enabled
	gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Not installed
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	geninventorynumber   Name: Inventory number generation    Version: 2.6.0      State: Enabled
	addressing           Name: IP Adressing                   Version: 3.0.0      State: Enabled
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.0      State: Enabled
	karastock            Name: Karastock                      Version: 1.2.1      State: Not installed
	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.2      State: Not installed
	mailbehaviours       Name: Mail Behaviours                Version: 1.0.0      State: Not installed
	metademands          Name: Meta-Demands                   Version: 3.0.1      State: Enabled
	moreticket           Name: More ticket                    Version: 1.7.0      State: Enabled
	oauthimap            Name: Oauth IMAP                     Version: 1.4.0      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.0      State: Enabled
	order                Name: Orders management              Version: 2.8.0      State: Enabled
	pdf                  Name: Print to pdf                   Version: 2.0.0      State: Not installed
	processmaker         Name: Process Maker                  Version: 4.0.3      State: Not installed
	projectbridge        Name: Projectbridge                  Version: 2.4        State: Not installed
	protocolsmanager     Name: Protocols manager              Version: 1.3.0      State: Enabled
	purchaserequest      Name: Purchase request               Version: 3.0.0      State: Enabled
	manufacturersimports Name: Suppliers imports              Version: 3.0.0      State: Enabled
	tag                  Name: Tag Management                 Version: 2.9.0      State: Enabled
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Not installed
	tasklists            Name: Tasks list                     Version: 2.0.1      State: Enabled
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.0   State: Enabled
	typology             Name: Typologies                     Version: 3.0.0      State: Enabled
	useditemsexport      Name: Used items export              Version: 2.5.0      State: Enabled

</pre></details>

### Anything else?

Please advise.
Thank you for an excellent product and continued support!
Ted Tsoukas

**Comment by trasher** [comment]
This entry should not appears, this has been fixed in 10.0/bugfixes branch. Adding a document can be done using the "actions" button (the one near "save" button).

**Comment by cconard96** [comment]
To add, as of version 10, documents are added to the timeline via tasks and followups rather than separate items or as was mentioned, via the actions dropdown (3 vertical dots to the left of the save button).
