### ISSUE TITLE
[GLPI 10] TinyMCE contextmenu / menubar (feat discussion)

### ISSUE THREAD

**Issue by CorentinS6** [glpi-project/glpi#11529]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

Hello,
Why the tinyMce menubar disapear between glpi 9.5 and glpi 10 ? What are the reasons of this choice ?
Moreover, the contextmenu is now poorer than the old menubar.
Would be nice to configure it with the gui ? (not in src/Html.php).
Best regards.

### Your GLPI setup information

GLPI 10.0.0

**Comment by cconard96** [comment]
Users can switch from the new hovering menu back to the original fixed menu bar with an option in their user preferences.

Regarding the context menu, copy and paste options were recently added and will be in the next bug fix version. Also, you can always access the browser's context menu by holding the ctrl key down when you right click.

**Comment by CorentinS6** [comment]
ty

**Comment by cconard96** [comment]
As a followup for you or anyone else that comes across this, since it is a user preference, you can change the default option for your GLPI instance from Setup > General on the Defaul Values tab.
