### ISSUE TITLE
GLPI 10.0 Last FIX  :  display bug on all tabs, lines do not appear correctly

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#11522]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI LAST FIX 20220507

### Bug description

Bug interface on different research, the line is not displayed correctly

example : 

printer : 
![image](https://user-images.githubusercontent.com/68054991/167365352-78c80620-bef2-4c46-b6e3-ea143af4e112.png)

collecteur no displays :
![image](https://user-images.githubusercontent.com/68054991/167366047-5c163dbc-ab59-4cd4-980c-629f760869b3.png)

ticket : 
![image](https://user-images.githubusercontent.com/68054991/167366607-141e12c2-6a12-4940-aa8f-8f2ac182a4b3.png)
l'id ticket is hidden

computer dysplays : 
![image](https://user-images.githubusercontent.com/68054991/167366154-38cdee39-a08d-45ac-bcb4-7a272138f711.png)

I have the impression there are display problems on glpi fix 07052002

### Relevant log output

```shell
no log
```

**Comment by orthagh** [comment]
duplicate #11520
