### ISSUE TITLE
9.1 : "Undefined variable: func" inc/toolbox.class.php:971

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#1152]
There seems to be a bug here :

> ** PHP Notice(8): Undefined variable: func
  Backtrace :
  inc/toolbox.class.php:971                          
  config/config.php:230                              Toolbox::commonCheckForUseGLPI()
  inc/includes.php:58                                include_once()
  index.php:56                                       include()

**Comment by remicollet** [comment]
@trasher ;)

**Comment by orthagh** [comment]
As i know, it's an error who triggers on migration from 0.90.5 to 9.1.
I think we need cherry-pick for this one

**Comment by remicollet** [comment]
cherry-picked.

**Comment by remicollet** [comment]
(BTW, I was thinking this new check for ext was only in master)
