### ISSUE TITLE
 Title bar is not at the top

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#11520]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Nightly build GLPI10

### Bug description

 Title bar or "address bar"  is not at the top!
CSS issue?

![image](https://user-images.githubusercontent.com/8606735/167271772-c8308bde-331e-4ccf-87a7-58a79f0c5f9c.png)

### Steps To reproduce

Just update to Nightly build

**Comment by husisusi** [comment]
https://github.com/glpi-project/glpi/pull/11506? is the cause of the problem
div class="table-responsive**-md** fix the issue

**Comment by orthagh** [comment]
The solution provided in #11506 is not sufficient.
It only hides the the issue.

I'll work on a fix in the morning
