### ISSUE TITLE
Cannot select or link a Contract from a Ticket, but I can if it viceversa

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#11531]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0 

### Bug description

When I try to select a Contract in the Contract tab from an existing Ticket since the Ticket page, the dropdown is showning empty, but I can link the same Ticket from the Ticket tab since the Contract page

### Relevant log output

```shell
Nothing in error logs.
```

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Create a Contract
2. Create a Ticket and open it
3. Go to the Contract tab
4. Try to select a Contract
5. Empty List
6. Go to the Contract created before
7. Go to the Ticket tab
8. Search the Ticket ID and link it
9. If you go again to the Ticket, in the Contract tab, the contract is already linked

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux 5.13.0-1022 #26~20.04.1-Ubuntu SMP Thu Apr 7 19:42:45 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 20.81.22.108 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36 Edg/101.0.1210.39
Server Software: Ubuntu 20.04
	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: -@localhost/-
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 

</details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.1      State: Installed / not activated
	activity             Name: Activities                     Version: 3.1.0      State: Installed / not activated
	actualtime           Name: ActualTime                     Version: 1.5.1      State: Installed / not activated
	fields               Name: Additionnal fields             Version: 1.15.0     State: Installed / not activated
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated
	news                 Name: Alerts                         Version: 1.10.2     State: Installed / not activated
	cleanarchivedemails  Name: Archived eMail clean           Version: 2.0.0      State: Installed / not activated
	impacts              Name: Asset impacts                  Version: 2.0.5      State: Installed / not activated
	barcode              Name: Barcode                        Version: 2.6.2      State: Installed / not activated
	behaviors            Name: Behaviours                     Version: 2.5.1      State: Installed / not activated
	camerainput          Name: Camera Input                   Version: 1.0.3      State: Installed / not activated
	positions            Name: Cartography                    Version: 6.0.0      State: Installed / not activated
	cmdb                 Name: CMDB                           Version: 3.0.1      State: Installed / not activated
	consumables          Name: Consumable request             Version: 2.0.0      State: Installed / not activated
	costs                Name: Costs                          Version: 2.2.3      State: Installed / not activated
	credit               Name: Credit vouchers                Version: 1.10.0     State: Installed / not activated
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Installed / not activated
	datainjection        Name: Data injection                 Version: 2.10.2     State: Installed / not activated
	databases            Name: Databases                      Version: 2.3.2      State: Installed / not activated
	archimap             Name: Diagrams                       Version: 3.2.7      State: Installed / not activated
	manageentities       Name: Entities portal                Version: 4.0.0      State: Installed / not activated
	environment          Name: Environment                    Version: 2.4.2      State: Installed / not activated
	escalade             Name: Escalation                     Version: 2.8.0      State: Installed / not activated
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.4 State: Installed / not activated
	fpsaml               Name: FP SAML                        Version: 1.1.0      State: Installed / not activated
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Installed / not activated
	gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Installed / not activated
	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Installed / not activated
	resources            Name: Human Resources                Version: 3.0.0-rc2  State: Installed / not activated
	geninventorynumber   Name: Inventory number generation    Version: 2.6.0      State: Installed / not activated
	addressing           Name: IP Adressing                   Version: 3.0.0      State: Installed / not activated
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.0      State: Installed / not activated
	jsaddons             Name: JS Addons                      Version: 1.0.0      State: Not installed
	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.2      State: Installed / not activated
	mreporting           Name: Más informes                   Version: 1.8.0      State: Installed / not activated
	satisfaction         Name: More satisfaction              Version: 1.6.0      State: Installed / not activated
	moreticket           Name: More ticket                    Version: 1.7.0      State: Installed / not activated
	mydashboard          Name: My Dashboard                   Version: 2.0.2      State: Installed / not activated
	genericobject        Name: Objects management             Version: 2.12.0     State: Installed / not activated
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.0      State: Installed / not activated
	officeonline         Name: Office Online                  Version: 2.0.2      State: Installed / not activated
	onetimesecret        Name: OneTimeSecret                  Version: 1.1.1      State: Installed / not activated
	order                Name: Orders management              Version: 2.8.0      State: Installed / not activated
	phpsaml              Name: PHP SAML                       Version: 1.1.2      State: Installed / not activated
	pdf                  Name: Print to pdf                   Version: 2.0.0      State: Installed / not activated
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Installed / not activated
	purchaserequest      Name: Purchase request               Version: 3.0.0      State: Installed / not activated
	releases             Name: Releases                       Version: 2.0.0      State: Installed / not activated
	reports              Name: Reports                        Version: 1.14.1     State: Installed / not activated
	reservation          Name: Reservation                    Version: 2.3.8      State: Installed / not activated
	room                 Name: Rooms                          Version: 3.1.3      State: Installed / not activated
	screenshot           Name: Screenshot                     Version: 2.0.0      State: To update
	statecheck           Name: Statecheck Rules               Version: 2.3.4      State: Installed / not activated
	tag                  Name: Tag Management                 Version: 2.9.0      State: Installed / not activated
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Installed / not activated
	tasklists            Name: Tasks list                     Version: 2.0.1      State: Installed / not activated
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.0   State: Installed / not activated
	timesheet            Name: Timesheet for GLPI             Version: 1.0.1      State: Not installed
	treeview             Name: Tree view                      Version: 1.9.1      State: Installed / not activated
	useditemsexport      Name: Used items export              Version: 2.5.0      State: Installed / not activated
	webapplications      Name: Web applications               Version: 4.0.0      State: To update
	webresources         Name: Web Resources                  Version: 2.0.0      State: Installed / not activated
	yagp                 Name: yagp                           Version: 1.2.0      State: Installed / not activated

</pre></details>

### Anything else?

![image](https://user-images.githubusercontent.com/56606032/167470169-5f38d570-c1fd-4a6e-a5e3-4190d711df51.png)

![image](https://user-images.githubusercontent.com/56606032/167478013-531bf89b-ceff-4234-9929-0e5cb125c8f9.png)

![image](https://user-images.githubusercontent.com/56606032/167479400-db7b4a8a-d365-46b9-97a6-5ad540102f69.png)

![image](https://user-images.githubusercontent.com/56606032/167479460-a612f1fa-1c41-41a6-b198-d9cfd44667f1.png)

**Comment by cconard96** [comment]
Only active contracts are shown in the dropdown from tickets and it looks like the one in your example has an end date that has passed. Can you confirm that a non-expired contract does show in the list properly from a Ticket?

**Comment by jcervantes-sipecom** [comment]
Hi @cconard96, thanks for your response. You were right, I had selected in "Initial Contract Period" 1 month

![image](https://user-images.githubusercontent.com/56606032/167512465-7426fc9f-2979-4692-aec1-3c82b5a63a5e.png)

Change it to 12 months, I can select it from Ticket:

![image](https://user-images.githubusercontent.com/56606032/167512569-cb076edd-6d73-4144-8af7-d8465e388527.png)

![image](https://user-images.githubusercontent.com/56606032/167512542-e35c9d3a-5534-4afc-9e65-46bb01a0c062.png)

Just a quick question, so what's the "Initial Contract Period" means? and What's the difference with "Contract renewal period"?

**Comment by cconard96** [comment]
Looking at the documentation (https://glpi-user-documentation.readthedocs.io/fr/latest/modules/management/contract.html),

Initial Contract Period - How long the contract is initially valid for. This is the initial term for the contract. As an example, you have a service contract that last 1 year. It is possible that some contracts may last a different amount of time initially.
Contract Renewal Period - Duration after which contract renewal is available
Renewal - The type of renewal. A tacit (implied) renewal means that the contact automatically renews. Express renewal represents a contract that both parties must agree on the renewal.

If you have tacit renewal and a renewal period set, the end date should update automatically.

**Comment by jcervantes-sipecom** [comment]
@cconard96 thanks for you explanation very cleared! Yes, I had read the documentation, but I didn't get it, because it just only says: "if this field and start date are given, contract end date will appear, colored in red if contract has expired". What you said is a better explanation of what it field does.

**Comment by jfuentesc** [comment]
The issue exists having a correct a valid contract period...

In contract,php,   function dropdown we have the next code:

            if (
                $p['nochecklimit']
                || ($data["max_links_allowed"] == 0)
                || ($data["max_links_allowed"] > countElementsInTable(
                    'glpi_contracts_items',
                    ['contracts_id' => $data['id']]
                ))
            ) {

But the table where are the assigned contracts to tickets is "glpi_tickets_contracts"

If you define a project with several renews of contract and associate this contract to a project,  this condition (with max_links_allowed = 1) is false 

This glpi_contact_items maybe can be the static variable defined in Tickets_contracts.php
