### ISSUE TITLE
GLPI-10.0.0 : Slowness in Marketplace

### ISSUE THREAD

**Issue by DooBio** [glpi-project/glpi#11548]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0 : Lenteur et erreur dans Marketplace

### Bug description
Hello

When I go to the marketplace I have a lot of slowness before displaying the plugins.

By activating the Debug mode and returning to the marketplace here is the error displayed

![image](https://user-images.githubusercontent.com/32511461/167635908-10db7978-2d82-4524-b154-d851a25a3474.png)

Good luck ;)

### Relevant log output

```shell
[2022-05-10 15:09:46] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:654                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:486                       Glpi\Marketplace\View::getButtons()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:46] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:871                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:539                       Glpi\Marketplace\View::getNetworkInformations()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:46] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:654                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:486                       Glpi\Marketplace\View::getButtons()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:46] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:871                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:539                       Glpi\Marketplace\View::getNetworkInformations()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:46] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:654                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:486                       Glpi\Marketplace\View::getButtons()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:47] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:871                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:539                       Glpi\Marketplace\View::getNetworkInformations()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:47] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:654                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:486                       Glpi\Marketplace\View::getButtons()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:47] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:871                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:539                       Glpi\Marketplace\View::getNetworkInformations()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:47] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:654                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:486                       Glpi\Marketplace\View::getButtons()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
  
[2022-05-10 15:09:47] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch offers information.
Error message:
Response:
{
    "message": "Too Many Attempts."
} in /var/www/glpi/src/GLPINetwork.php at line 342
  Backtrace :
  src/GLPINetwork.php:342                            trigger_error()
  src/Marketplace/Controller.php:364                 GLPINetwork::getOffers()
  src/Marketplace/View.php:871                       Glpi\Marketplace\Controller->getRequiredOffers()
  src/Marketplace/View.php:539                       Glpi\Marketplace\View::getNetworkInformations()
  src/Marketplace/View.php:352                       Glpi\Marketplace\View::getPluginCard()
  src/Marketplace/View.php:249                       Glpi\Marketplace\View::displayList()
  src/Marketplace/View.php:120                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:687                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0 (/glpi => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux SRV-Intranet 5.17.0-1-amd64 #1 SMP PREEMPT Debian 5.17.3-1 (2022-04-18) x86_64
PHP 7.4.29 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="2000M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20000M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at 10.1.125.201 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
Server Software: Debian buildd-unstable
	Server Version: 10.6.7-MariaDB-3
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (7.4.29) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.7) is supported.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.7 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.6.0 in (/var/www/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf not found
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://10.1.100.1', Port: '389', BaseDN: 'DC=*********,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'administrateur@**********.local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (glpi@*************.com@ssl0.ovh.net)

</details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertes                        Version: 1.10.2     State: Installed / not activated
	additionalalerts     Name: Alertes supplémentaires        Version: 2.4.0      State: Enabled
	webapplications      Name: Applications Web               Version: 4.0.0      State: Installed / not activated
	financialreports     Name: Arrêtés du parc                Version: 3.0.0      State: Installed / not activated
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Not installed
	screenshot           Name: Capture d'écran                Version: 2.0.0      State: Not installed
	positions            Name: Cartographie                   Version: 6.0.0      State: Installed / not activated
	fields               Name: Champs supplémentaires         Version: 1.15.0     State: Enabled
	accounts             Name: Comptes                        Version: 3.0.1      State: Installed / not activated
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Installed / not activated
	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.0      State: Installed / not activated
	mydashboard          Name: Dashboard                      Version: 2.0.2      State: Installed / not activated
	datainjection        Name: Data Injection                 Version: 2.11.1     State: Installed / not activated
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Installed / not activated
	errorlog             Name: ErrorLog                       Version: 0.0.1      State: Enabled
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.0      State: Installed / not activated
	formcreator          Name: Form Creator                   Version: 2.13.0-alpha.4 State: Enabled
	geninventorynumber   Name: Génération de numéros d'invent Version: 2.6.0      State: Installed / not activated
	genericobject        Name: Gestion d'objets               Version: 2.12.0     State: Enabled
	order                Name: Gestion des commandes          Version: 2.8.0      State: Enabled
	tag                  Name: Gestion des tags               Version: 2.9.0      State: Installed / not activated
	dev                  Name: GLPI Development Helper        Version: 2.0.0      State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Installed / not activated
	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.0      State: Enabled
	manufacturersimports Name: Imports fabricants             Version: 3.0.0      State: Installed / not activated
	karastock            Name: Karastock                      Version: 1.3.1      State: Installed / not activated
	tasklists            Name: Liste des tâches               Version: 2.0.1      State: Installed / not activated
	metademands          Name: Meta-Demandes                  Version: 3.0.1      State: Installed / not activated
	metabase             Name: metabase                       Version: 1.3.0      State: Enabled
	moreticket           Name: More ticket                    Version: 1.7.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.8.0      State: Installed / not activated
	purgelogs            Name: Purge de l'historique          Version: 1.3.0      State: Enabled
	stab                 Name: Split Timeline Action Buttons  Version: 1.0.0      State: Enabled
	testplugin           Name: testPlugin                     Version: 0.0.1      State: Enabled
	webresources         Name: Web Resources                  Version: 2.0.0      State: Installed / not activated

</pre></details>

**Comment by trasher** [comment]
Please write in english only.

**Comment by DooBio** [comment]
> sorry now its ok

**Comment by cconard96** [comment]
Improved handling of the marketplace when the GLPI Network API cannot be reached will be coming in GLPI 10.1.0.
See: #11427.

It may help with this case too although I don't know how so many API calls are being made that you would get rate limited.
