### ISSUE TITLE
Tasks in a ticket from template are doubled, if you add yourself

### ISSUE THREAD

**Issue by JoHoffmann** [glpi-project/glpi#11546]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Given situation:
You have a ticket template A.
Ticket template A contains pre-defined value "assigned to".
Ticket template A contains 7 different pre-defined tasks.
A ticket is created from this template A on a certain intervall. 
When you now assign this ticket to yourself, you will find double the amount of the 7 predefinded tasks in the ticket. You have 14 tasks in the ticket, each of the initial tasks has been duplicated inside the ticket.

If you need any additional information, don't hesitate to contact me.

KR,
Jo Hoffmann 

### Steps To reproduce

1. Create predefined tasks.
2. Create a ticket template:
     a. with a "Assign to" value
     b. with the tasks from step 1
3. Create a ticket from the template of step 2
4. change the "assign to" value to yourself
5. et voila, tasks are duplicated

Workaround: If the "Assign to" value is not set in the template, the bug will not occur.

### Your GLPI setup information

GLPI 10.0.0 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_US

**Comment by trasher** [comment]
No feedback, closing
