### ISSUE TITLE
RFE: REST API should be able to give plugins additionnal information.

### ISSUE THREAD

**Issue by ashmonger** [glpi-project/glpi#1154]
For exemple:

If I use Fields plugin, I would be able to get thoses new fields by the API.

https://github.com/pluginsGLPI/fields/issues/61

**Comment by ashmonger** [comment]
Some plugins info seems to be accessibles when directly talking to the plugin :
`/glpi/apirest.php/PluginFieldsComputercsserveur<fieldname>`
Will it be possible some day to access it by the computer page and not the plugin page?

**Comment by sebeka** [comment]
Hi,

This solution is not working for me, I get ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM

If I output all defined classes in apirest.class.php (getItem), I get only:

     ...
    [188] => PluginFieldsAutoloader
    [189] => PluginFieldsContainer
    [190] => PluginFieldsProfile
    ...

Thanks,

Sebastian

**Comment by sebeka** [comment]
Related to: https://github.com/glpi-project/glpi/issues/4327

**Comment by sebeka** [comment]
Sorry, I did some confusion here.
ashmonger is right, accessing custom fields is possible.
The plugin "fields" creates new classes out of a template, if you create new containers with new fields.
The new classes are located here: files/_plugins/fields/inc/
and can be called via rest API. Just open the classfile and take the name of the class 

For example, I have a file:
           files/_plugins/fields/inc/computertestblockfornewfield.class.php

The classname is:
            class PluginFieldsComputertestblockfornewfield extends CommonDBTM

The request in the php api client looks like:
           $response = $itemHandler->getAllItems('PluginFieldsComputertestblockfornewfield');


Sebastian
