### ISSUE TITLE
GLPI-10.0.0 - The version of the database is not compatible

### ISSUE THREAD

**Issue by FelipeSilveiraL** [glpi-project/glpi#11551]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0

### Bug description

Upgrading my version 9.5.6 to 10.0.0, asking me to run some script.

i execut the script php bin/console glpi:migration:timestamps, I see the error on the screen"The version of the database is not compatible with the version of the installed files. An update is necessary."

But my database is MariaDB 10.7 and my PHP is 8.1. Can you help me?

### Steps To reproduce

![image](https://user-images.githubusercontent.com/82624468/167657580-b0dbc430-2a96-414a-ac0c-5dd6229b9586.png)

**Comment by cconard96** [comment]
Did you finish the update process from the web UI or CLI?

The first message indicates that the update process wasn't finished.

**Comment by FelipeSilveiraL** [comment]
Thanks for the answer.

My update from process CLI.

Updating my GLPI, the following message appeared: 

![image](https://user-images.githubusercontent.com/82624468/167661784-7eb37b8a-7646-40e4-b403-589f24492d4f.png)

**Comment by cedric-anne** [comment]
> The version of the database is not compatible with the version of the installed files. An update is necessary.

This message indicates that GLPI files version does not match GLPI database version. It is displayed when the GLPI source code has been updated, to indicate that the GLPI update process have to be executed.
As you give a screenshot of update success in UI, it probably mean that your are executing the console on another GLPI instance.

I close this issue, as it does not seems to be a GLPI bug.

**Comment by LinKJeTT** [comment]
i have the same problem, after update GLPI to 10.0.3 and trying to apply this command 

`php bin/console glpi:migration:utf8mb4`

or

`php bin/console glpi:migration:unsigned_keys`

because GLPI show me the next message 

390 tables are using the deprecated utf8mb3 storage charset. Run the "php bin/console glpi:migration:utf8mb4" command to migrate them.
1302 claves primarias o foraneas utilizan enteros con signo Run the "php bin/console glpi:migration:unsigned_keys" command to migrate them.

**Comment by cedric-anne** [comment]
This issue is closed. Please open a new one to explain your bug in details, and to provide all requested information.
