### ISSUE TITLE
I can edit the ticket template but no save button

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#11555]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Nightly build V10

### Bug description

There is no save button when I want to edit the ticket template.

![grafik](https://user-images.githubusercontent.com/8606735/167787598-6bf62475-571b-4bbc-9a62-057f51c59a31.png)

### Steps To reproduce

Create ticket template and save it, try to edit "Standard interface".

**Comment by cconard96** [comment]
Please check the GLPI logs `files/_log/php-errors.log` and `files/_log/sql-errors.log` for entries from around the time you were viewing this page..

**Comment by husisusi** [comment]
> Please check the GLPI logs `files/_log/php-errors.log` and `files/_log/sql-errors.log` for entries from around the time you were viewing this page..

No errors. Nothing in files/_log/php-errors.log and files/_log/sql-errors.log.

**Comment by cconard96** [comment]
The screenshot you provided looks like it is from the preview tab for Standard Interface. The only tabs that are editable are the main tab (set name and comment), Mandatory Fields, Predefined Fields, and Hidden Fields. Can you re-confirm that the save button is visible on those tabs?

**Comment by husisusi** [comment]
Yes, I confirm that! 
Maybe we should rename the "standard interface" tab to "preview", it confuses.
Thank you!

**Comment by cconard96** [comment]
I made a PR to rename the tabs to "Preview (Standard interface)" and "Preview (Simplified Interface)".
#11697
