### ISSUE TITLE
Document / File uploads in Helpdesk tickets not possible after initial ticket creation.

### ISSUE THREAD

**Issue by jm-sbe** [glpi-project/glpi#11559]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Document / File uploads in Helpdesk tickets not possible after initial ticket creation.

### Relevant log output

```shell
Check attached images for a comparison of the GLPI 9.5.5 upload form (working) and the current GLPI 10.0 upload form (faulty) in tickets.
```

### Page URL

https://glpi/front/ticket.form.php?id=XXX

### Steps To reproduce

1. Go to Helpdesk -> Tickets
2. Create a new ticket and save it
3. Open the same ticket after creation and try to upload a new file
4. The form to upload a file doesn't show properly (might be some JavaScript related issue)

GLPI 10.0 upload form (display error?!)
![glpi10 0 0_document-upload_issue](https://user-images.githubusercontent.com/88610847/167794504-0927b8ac-ad84-49e1-b829-449f930e3d2d.png)

GLPI 9.5.5 upload form (working)
![glpi9 5 5_document-upload_working](https://user-images.githubusercontent.com/88610847/167794507-34c68dd7-a998-43b1-a683-bd3bf0742c11.png)

### Your GLPI setup information

OS: Ubuntu Server 22.04 LTS
Webserver: Apache2 with enabled php8.1
Database: MariaDB 10.6

### Anything else?

Affected is our productive GLPI 10.0.0 installation (previously upgraded from version 9.5.5) and also a fresh installation of GLPI 10.0.0 (without any kind of customized settings).

The problem occurs in the simple and advanced view of tickets and every profile (including super-admin permission) is affected.

**Comment by trasher** [comment]
Duplicates #11525
