### ISSUE TITLE
Rejection of Solution for Changes in Timeline

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#11561]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

If this happens:
1. Change is assigned to some person
2. Solution is added to Change request via the Timeline
3. Solution is rejected by requester 

Change status is returned to state ASSIGNED (2) which does not exist for Change requests.
This is later on causing issues with such Change request as it is not visible with this incorrect status in list of changes.

Here should be probably add this condition:
https://github.com/glpi-project/glpi/blob/7d343f43544b8fc7afba1e73d38ee9a493e11007/src/ITILFollowup.php#L323
to here:
https://github.com/glpi-project/glpi/blob/7d343f43544b8fc7afba1e73d38ee9a493e11007/src/ITILFollowup.php#L317

But in my opinion best fix would be to return back to previous "Status" of Change request.
But that would require to store it somewhere in DB.

PS:
Checking the ITILSolution code. It looks like it might have been idea to do the approbations only for Tickets:
https://github.com/glpi-project/glpi/blob/528751026ede1450cc4ce650af955ec31e6d197e/src/ITILSolution.php#L251
But still the Approbation request is displayed also in case it is in status CommonITILValidation::ACCEPTED and hence it is possible to hit this bug

### Steps To reproduce

Steps included in description.

### Your GLPI setup information

10.0.0 without plugins
9.5.7 without plugins

### Anything else?

Bug exists in both 10.x and 9.x versions

**Comment by cconard96** [comment]
When I tested this, the status did not change when adding the solution. When I refused the solution, the status changed to New. It seems that all that would need done is turn off the automatic status change for all except tickets.

**Comment by VladoTTX** [comment]
You need to have Assigned Actor to the Change, just in that case status changes to ASSIGNED.
In case nobody is assigned to Change status changes to NEW.

BTW it looks like maybe here:
https://github.com/glpi-project/glpi/blob/7d343f43544b8fc7afba1e73d38ee9a493e11007/src/ITILFollowup.php#L323
someone meant to have AND not OR condition as it will be always true for helpdesk interface:

**Comment by VladoTTX** [comment]
Still present also in latest version of GLPI and is caused by isAllowedStatus returning true just if MATRIX exists even if ASSIGNED does not exist for given ITIL object type..

https://github.com/glpi-project/glpi/blob/5aba1fc404a86866841a03ff9e5505ce0b672243/src/CommonITILObject.php#L3174-L3182

It should probably double check target status by calling isStatusExists()

Or at least condition should be extended to:
``
$parentitem::isStatusExists($parentitem->fields["status"],CommonITILObject::ASSIGNED) && $parentitem::isAllowedStatus($parentitem->fields["status"], CommonITILObject::ASSIGNED)
``

**Comment by cedric-anne** [comment]
Fixed by #12222.
