### ISSUE TITLE
Grid in the Personal View is displayed in one column only

### ISSUE THREAD

**Issue by pvasener** [glpi-project/glpi#11568]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

When I go to the 'Personal View' tab in the central dashboard. All blocks are displayed at the top of each others in a unique column rather than spanning on 3 columns. It is working good with the same data in GLPI 9.5.7

**Comment by cconard96** [comment]
I can recreate the issue if the "Your tickets to validate" widget is not shown due to not having any items. If I remove the widget completely, then the issue doesn't occur. The issue did not occur when I forced no items to show for another widget. It seems like the issue only occurs for the first expected widget on the page.

**Comment by pvasener** [comment]
I tested with a ticket to validate and, in this case, the display is actually not broken. Thanks for the analysis, @cconard96

**Comment by cosmedd** [comment]
I can confirm that it works but sometimes the tickets are hidden as shown in the image. It is solved by reloading the page.

![Captura de pantalla de 2022-05-27 12-27-42](https://user-images.githubusercontent.com/44313383/170683011-2c1d3d75-4c26-4536-bb98-87b6d456d38e.png)

This happens at least in Firefox 100.0.2

**Comment by pvasener** [comment]
It's better but introduces to new problems:

1. Empty gray lines are displayed at the top of blocks 
![image](https://user-images.githubusercontent.com/1736726/171222666-bd2b7db1-9517-4c48-93e4-54fe32c87f4b.png)

2. The last block 'Your planning' is overflooding the general frame (fixed with a page reload though) 
![image](https://user-images.githubusercontent.com/1736726/171223226-9770d882-1f70-46c1-a3f0-9963c903d60c.png)

**Comment by cconard96** [comment]
For the issues experienced after this fix, can you please open new issues?
@cosmedd 
@pvasener
