### ISSUE TITLE
Migrating from 9.5->10

### ISSUE THREAD

**Issue by we-sell-bags** [glpi-project/glpi#11566]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

After starting 10.0.0
1.
the GUI shows items that must be dealt with.
there are a number of foreign keys that are negative

2. the spelling of "occured" is wrong....  correct... "occurred"

### Relevant log output

```shell
php bin/console glpi:migration:unsigned_keys
Found 1724 primary/foreign key columns(s) using signed integers.
Do you want to continue? [Yes/no]Yes
Migration of column "glpi_plugin_geninventorynumber_configs.entities_id" cannot be done as it contains negative values.
Migration of column "glpi_plugin_uninstall_preferences.locations_id" cannot be done as it contains negative values.
 1724/1724 [============================] 100%
Errors occured during migration.
```

### Steps To reproduce

install 10.0.0
run upgrade script

put system OUT of maintenance mode

warnings on GUI

**Comment by cedric-anne** [comment]
Hi,

Typo will be fixed by #11599 .

For migration of `glpi_plugin_geninventorynumber_configs.entities_id` and `glpi_plugin_uninstall_preferences.locations_id`, you have to first update corresponding plugins, adn run the command again. Plugins update will be adviced with #10763.
