### ISSUE TITLE
Cannot set group's "Visible in a ticket - Task" to Yes

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#1157]
Hello,
In Group tab of group.form.php option "Visible in a ticket" -> "Task" cannot be changed to Yes.
After submitting a form, it backing to No value.

**Comment by hartois** [comment]
I found the reason: my table glpi groups did not contain istask column. 
I solved a problem adding it:
alter table glpi_groups add column `is_task` tinyint(1) NOT NULL DEFAULT '1'

**Comment by Armin83** [comment]
There was other issue but this is already closed. Could it be that you upgraded from 9.1 RC1 to 9.1 stable ?

**Comment by hartois** [comment]
Yes, I upgrage using ```git pull```

**Comment by Armin83** [comment]
#1145

**Comment by orthagh** [comment]
you should be aware that RC version is not for production.
We don't actually manage migration between development versions.

So, your workaround (https://github.com/glpi-project/glpi/issues/1157#issuecomment-253434783) is ok but we will not push in the current code.

I close, feel free to comment this issue if you have question.
