### ISSUE TITLE
Add watcher for simplified interface

### ISSUE THREAD

**Issue by DZbox** [glpi-project/glpi#11578]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hi,

I have a question, it seems this is not a bag
As far as I understand at 10.0.0 it is unable for requester to add a watcher when he creates a ticket and after creating using simplified interface? Or there is a setting for this? It was enable for 9.5 version and I can't find something that can turn this setting on

**Comment by cconard96** [comment]
Please check your ticket template(s). This is not a restriction that was added in GLPI 10 and this field is present for me.

**Comment by DZbox** [comment]
> Please check your ticket template(s). This is not a restriction that was added in GLPI 10 and this field is present for me.

There is no restriction or something hidden regarding this in ticket templates. It is visible but not editable:
![image](https://user-images.githubusercontent.com/72818340/168274583-b58eae1a-dc17-41e8-baf3-4851e0a0d9fa.png)

**Comment by cconard96** [comment]
This field is functional for me. and only looks like that briefly while the page is loading.

Please check the browser console for warnings/errors (F12 > Console tab) and check the GLPI PHP log file `files/_log/php-errors.log` for any warnings/errors from the time you tried loading this page.

Also, try leaving the ticket creation page open for a minute or two in case it is trying to load something in the background (like a script or stylesheet) but it hasn't timed out yet.

**Comment by DZbox** [comment]
> This field is functional for me. and only looks like that briefly while the page is loading.
> 
> Please check the browser console for warnings/errors (F12 > Console tab) and check the GLPI PHP log file `files/_log/php-errors.log` for any warnings/errors from the time you tried loading this page.
> 
> Also, try leaving the ticket creation page open for a minute or two in case it is trying to load something in the background (like a script or stylesheet) but it hasn't timed out yet.

Thank you,
There is an error at browser console:
Uncaught SyntaxError: Unexpected token ',' (at helpdesk.public.php?create_ticket=1:1556:36)


Here is the sourse from console:
ajax: {
            url: '/ajax/actors.php',
            datatype: 'json',
            type: 'POST',
            data: function (params) {
               return {
                  action: 'getActors',
                  actortype: actorytype,
                  users_right: 'all',
   ->>>      entity_restrict: ,
                  searchText: params.term,
                  _idor_token: 'dbc80551bc91334a2cdbc05237466501955a00197ff6123d729554a22c9e563d',
                  itiltemplate_class: 'TicketTemplate',
                  itiltemplates_id: 6,
                  itemtype: 'Ticket',
                  items_id: -1,
                  item: [],
                  returned_itemtypes: ["User","Group","Supplier"],
               };

It seems this can be related with https://github.com/glpi-project/glpi/issues/10570 where I've found the way to resolve another issue by removing "int" for "$entity_id" in ConfigExtension.php (described by the author at the beginning of the topic https://github.com/glpi-project/glpi/issues/10570)

**Comment by cconard96** [comment]
Removing the type for `$entity_id` is only getting rid of a symptom of the real issue unfortunately and will most likely lead to other issues like this one. When a user is logged in, the entity should never be null. I don't think any developer has been able to recreate this issue yet.

**Comment by DZbox** [comment]
> Removing the type for `$entity_id` is only getting rid of a symptom of the real issue unfortunately and will most likely lead to other issues like this one. When a user is logged in, the entity should never be null. I don't think any developer has been able to recreate this issue yet.

I understand, thank you.

If I return "int" then:

base.min.js?v=f4824ecd30d02093bedbcd469a4e83b3c4ea023e:25 
Uncaught ReferenceError: templateResult is not defined
    at HTMLDocument.<anonymous> (helpdesk.public.php?create_ticket=1:383:29)
    at u (base.min.js?v=f4824ecd30d02093bedbcd469a4e83b3c4ea023e:25:27491)
    at c (base.min.js?v=f4824ecd30d02093bedbcd469a4e83b3c4ea023e:25:27819)

**Comment by DZbox** [comment]
I'll follow https://github.com/glpi-project/glpi/issues/10570 thank you!
