### ISSUE TITLE
[GLPI 10 bugfixes] encoding problem on RuleAsset

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#11577]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

On integrated rule - One user assignation on Rule Asset

![image](https://user-images.githubusercontent.com/13178158/168252433-c1e85433-0f5f-434e-b5f2-161f5561b651.png)

When you edit the action : 

![image](https://user-images.githubusercontent.com/13178158/168252371-c566e57c-2811-4530-b842-5ba7700b14cd.png)

### Page URL

http://localhost/glpi/front/ruleasset.form.php?id=474

**Comment by cconard96** [comment]
Error seems to exist in the Sanitizer. It doesn't recognize that the text is HTML encoded so it doesn't unsanitize it before it gets displayed in the form header template.
