### ISSUE TITLE
Ticket creation disabled but button is still clickable

### ISSUE THREAD

**Issue by blackxthink** [glpi-project/glpi#11584]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

I disabled the creation of tickets in the profile self-serve (We do not want the users to create incomplete tickets).

When i am logged in as a self-serve user, i still have the button Add but brings me to an empty page instead of disabling the button or hiding it.

![image](https://user-images.githubusercontent.com/48074916/168342989-cec681b2-310c-41b6-8b9b-cf58e31d0b6e.png)

![image](https://user-images.githubusercontent.com/48074916/168342578-06e49990-9b7d-4069-9712-987685330348.png)

![image](https://user-images.githubusercontent.com/48074916/168342700-077e90a8-849c-499b-83aa-148274839bfc.png)

### Steps To reproduce

Refer to the screenshots.
It is too simple to require steps to reproduce the issue.

**Comment by cconard96** [comment]
Should be fixed by #11586
