### ISSUE TITLE
html email tables formatting in follow ups

### ISSUE THREAD

**Issue by tnrhsv** [glpi-project/glpi#11580]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

There seems to be a problem displaying followups which includes tables with the property "table width" set.
When the table property "table width" is activated and set on any value, like 8cm or 15,5cm the whole follow ups has a problem, displaying the table properly.
![GLPI Outlook Table Property](https://user-images.githubusercontent.com/105439719/168279699-d11e5cc5-6c3b-4976-95f4-5b9ab510ec18.png)
![GLPI Table HTML Column Width](https://user-images.githubusercontent.com/105439719/168279755-19f49d5f-c39d-4644-80ee-9e7439335b5b.png)

The issue happens on Mozilla Firefox 100.0, Google Chrome 101.0.4951.64 & Microsoft Edge 101.0.1210.39.
It only happens, when the e-mail formatting is set to HTML. Using Rich-Text doesn't show any problems.
It only happens when you're on the ticket and read the Follow-Up. 

If you check the preview from the main-Ticket-page it shows the formatting correctly.
If you edit the Follow-Up on the ticket it shows the formatting correctly. If you save/discard the change, it falls back to the formatting problems.
![GLPI Table HTML Edit Formatting](https://user-images.githubusercontent.com/105439719/168280708-304c3b54-cd87-4cd7-aed9-fb1d8ad9a305.png)

On the last picture I've added 2 tables by answering the E-Mail-Ticket. The First table has its table width disabled. The second table had the value set on ~8cm.

![GLPI Table HTML Formatting](https://user-images.githubusercontent.com/105439719/168280948-8cb3ce14-80b8-45dc-a5c7-3623e5d3724a.png)

### Steps To reproduce

1. Send a HTML Formatted E-Mail from Outlook with a table with 2 rows & a few columns.
2. Edit the table properties and activate the table width on some value, like 15cm.
3. Send the e-mail to a glpi receiver.
4. Open the created ticket.
5. Look at the follow up.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 ( => /usr/share/glpi)
Installation mode: RPM
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux yp-glpi.rheine 5.12.15-300.fc34.x86_64 #1 SMP Wed Jul 7 19:46:50 UTC 2021 x86_64
PHP 8.0.8 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sodium, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="2048M" post_max_size="22M" safe_mode="" session.save_handler="files"
	upload_max_filesize="22M" 
Software: Apache/2.4.48 (Fedora) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Server Software: MariaDB Server
	Server Version: 10.5.11-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.0.8) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.11) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi
GLPI_CONFIG_DIR: /etc/glpi
GLPI_VAR_DIR: /var/lib/glpi/files
GLPI_LOG_DIR: /var/log/glpi
GLPI_HTMLAWED: /usr/share/php/htmLawed/htmLawed.php
GLPI_FONT_FREESANS: /usr/share/fonts/gnu-free/FreeSans.ttf
GLPI_SYSTEM_CRON: 1
GLPI_INSTALL_MODE: RPM
GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/lib/glpi/files
GLPI_CACHE_DIR: /var/lib/glpi/files/_cache
GLPI_CRON_DIR: /var/lib/glpi/files/_cron
GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales
GLPI_LOCK_DIR: /var/lib/glpi/files/_lock
GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins
GLPI_RSS_DIR: /var/lib/glpi/files/_rss
GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions
GLPI_TMP_DIR: /var/lib/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/lib/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/usr/share/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/usr/share/glpi/vendor/symfony/polyfill-php81)
phpCas version 1.4.0 in (/usr/share/pear)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (e-mail address removed manually by issue creator)

</details><details><summary>Plugins list</summary><pre> 
	datainjection        Name: Data injection                 Version: 2.11.1     State: Enabled
	formcreator          Name: Form Creator                   Version: 2.13.0-beta.1 State: Installed / not activated
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Installed / not activated
	order                Name: Orders management              Version: 2.8.0      State: Enabled

</pre></details>

**Comment by cconard96** [comment]
What do the table properties show in the text box? Are the widths missing completely now or were they replaced with something else?

**Comment by tnrhsv** [comment]
The Table properties are set differently on the working & problematic ones.
Working one:
![GLPI Table HTML Follow Up Table Properties Working Table](https://user-images.githubusercontent.com/105439719/168544271-2010573e-b8b4-4531-b8ec-ff42f22f1575.PNG)

Problematic one:
![GLPI Table HTML Follow Up Table Properties Faily Table](https://user-images.githubusercontent.com/105439719/168544341-a129c5b4-cbf9-492f-ab72-bf7ef6731343.PNG)

If i manually remove the WIdth: 0px from the faily one, it becomes normal again.

**Comment by cedric-anne** [comment]
Hi,

Which application (Word, OpenOffice, ...) are you using to generate your text ?

Also, could you provide the content of `glpi_tickets` table for the corresponding ticket ? It may help to understand how the rich-text content is converted by TinyMCE, and, maybe, help to find a solution for this.

**Comment by tnrhsv** [comment]
Hi,

the used application is Microsoft Outlook 2016 32-Bit.

I've created a new ticket that has the problem. Since I'm not sure how to encapsulate the text, I've just copied it in here.

`MariaDB [glpi]> SELECT * FROM glpi_tickets WHERE id=5542 LIMIT 1;
+------+-------------+------------------+---------------------+-----------+-----------+---------------------+----------------------+--------+--------------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+----------+-------------------+------+-------------------+-------------+-------------+------------------+-----------------+-------------+--------------------+----------------------+----------------------+-------------+-------------+------------------+--------------------+--------------------------+----------------------+------------------+------------------+------------------+----------------------------+------------+------------+--------------+--------------------+---------------------+
| id   | entities_id | name             | date                | closedate | solvedate | date_mod            | users_id_lastupdater | status | users_id_recipient | requesttypes_id | content                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | urgency | impact | priority | itilcategories_id | type | global_validation | slas_id_ttr | slas_id_tto | slalevels_id_ttr | time_to_resolve | time_to_own | begin_waiting_date | sla_waiting_duration | ola_waiting_duration | olas_id_tto | olas_id_ttr | olalevels_id_ttr | ola_ttr_begin_date | internal_time_to_resolve | internal_time_to_own | waiting_duration | close_delay_stat | solve_delay_stat | takeintoaccount_delay_stat | actiontime | is_deleted | locations_id | validation_percent | date_creation       |
+------+-------------+------------------+---------------------+-----------+-----------+---------------------+----------------------+--------+--------------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+----------+-------------------+------+-------------------+-------------+-------------+------------------+-----------------+-------------+--------------------+----------------------+----------------------+-------------+-------------+------------------+--------------------+--------------------------+----------------------+------------------+------------------+------------------+----------------------------+------------+------------+--------------+--------------------+---------------------+
| 5542 |           0 | Signature-Test 5 | 2022-06-02 14:20:18 | NULL      | NULL      | 2022-06-02 14:24:02 |                    0 |      1 |                 11 |               2 | &#60;html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word" xmlns:m="http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"&#62;&#60;head&#62;&#60;META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=us-ascii"&#62;&#60;meta name=Generator content="Microsoft Word 15 (filtered medium)"&#62;&#60;style&#62;&#60;!--
/* Font Definitions */
@font-face
        {font-family:"Cambria Math";
        panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
        {font-family:Calibri;
        panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
        {font-family:Roboto;
        panose-1:2 0 0 0 0 0 0 0 0 0;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
        {margin:0cm;
        margin-bottom:.0001pt;
        font-size:11.0pt;
        font-family:"Calibri",sans-serif;
        mso-fareast-language:EN-US;}
a:link, span.MsoHyperlink
        {mso-style-priority:99;
        color:#0563C1;
        text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
        {mso-style-priority:99;
        color:#954F72;
        text-decoration:underline;}
span.E-MailFormatvorlage17
        {mso-style-type:personal-compose;
        font-family:Roboto;
        color:windowtext;}
.MsoChpDefault
        {mso-style-type:export-only;
        font-family:"Calibri",sans-serif;
        mso-fareast-language:EN-US;}
@page WordSection1
        {size:612.0pt 792.0pt;
        margin:70.85pt 70.85pt 2.0cm 70.85pt;}
div.WordSection1
        {page:WordSection1;}
--&#62;&#60;/style&#62;&#60;!--[if gte mso 9]&#62;&#60;xml&#62;
&#60;o:shapedefaults v:ext="edit" spidmax="1026" /&#62;
&#60;/xml&#62;&#60;![endif]--&#62;&#60;!--[if gte mso 9]&#62;&#60;xml&#62;
&#60;o:shapelayout v:ext="edit"&#62;
&#60;o:idmap v:ext="edit" data="1" /&#62;
&#60;/o:shapelayout&#62;&#60;/xml&#62;&#60;![endif]--&#62;&#60;/head&#62;&#60;body lang=DE link="#0563C1" vlink="#954F72"&#62;&#60;div class=WordSection1&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto'&#62;&#60;o:p&#62;&#38;nbsp;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto'&#62;&#60;o:p&#62;&#38;nbsp;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;table class=Tabellenraster1 border=0 cellspacing=0 cellpadding=0 width=0 style='width:346.9pt;border-collapse:collapse;border:none'&#62;&#60;tr&#62;&#60;td width=463 colspan=3 style='width:346.9pt;border:solid windowtext 1.0pt;padding:0cm 0cm 0cm 0cm'&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto;mso-fareast-language:DE'&#62;&#60;o:p&#62;&#38;nbsp;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto;mso-fareast-language:DE'&#62;Row 1, Column 1&#60;o:p&#62;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto;mso-fareast-language:DE'&#62;&#60;o:p&#62;&#38;nbsp;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;/td&#62;&#60;/tr&#62;&#60;tr&#62;&#60;td width=132 style='width:98.85pt;border:solid windowtext 1.0pt;border-top:none;padding:0cm 0cm 0cm 0cm'&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto;mso-fareast-language:DE'&#62;Row 2, Column 1&#60;o:p&#62;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;/td&#62;&#60;td width=171 style='width:127.95pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;padding:0cm 0cm 0cm 0cm'&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto;mso-fareast-language:DE'&#62;Row 2, Column 2&#60;o:p&#62;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;/td&#62;&#60;td width=160 style='width:120.1pt;border-top:none;border-left:none;border-bottom:solid windowtext 1.0pt;border-right:solid windowtext 1.0pt;padding:0cm 0cm 0cm 0cm'&#62;&#60;p class=MsoNormal&#62;&#60;span style='font-family:Roboto;mso-fareast-language:DE'&#62;Row 3, Column 3&#60;/span&#62;&#60;span lang=EN-US style='font-family:Roboto;mso-fareast-language:DE'&#62;&#60;o:p&#62;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;/td&#62;&#60;/tr&#62;&#60;/table&#62;&#60;p class=MsoNormal&#62;&#60;span lang=EN-US&#62;&#60;o:p&#62;&#38;nbsp;&#60;/o:p&#62;&#60;/span&#62;&#60;/p&#62;&#60;/div&#62;&#60;/body&#62;&#60;/html&#62; |       3 |      3 |        3 |                 0 |    2 |                 1 |           0 |           0 |                0 | NULL            | NULL        | NULL               |                    0 |                    0 |           0 |           0 |                0 | NULL               | NULL                     | NULL                 |                0 |                0 |                0 |                        224 |          0 |          0 |            0 |                  0 | 2022-06-02 14:24:02 |
+------+-------------+------------------+---------------------+-----------+-----------+---------------------+----------------------+--------+--------------------+-----------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+--------+----------+-------------------+------+-------------------+-------------+-------------+------------------+-----------------+-------------+--------------------+----------------------+----------------------+-------------+-------------+------------------+--------------------+--------------------------+----------------------+------------------+------------------+------------------+----------------------------+------------+------------+--------------+--------------------+---------------------+`

**Comment by cedric-anne** [comment]
Hi,

Could you test #11800 ?

**Comment by tnrhsv** [comment]
Hi,

the test file worked. All the faulty tables are working normally again. According to the table properties, the width has been set correctly in each table.

Thank you for fixing this problem!
