### ISSUE TITLE
class Migration : management of enum type missing

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1158]
Hi

Some plugins use enumerations in their tables. Upgrading the tables from an old version to a newer one must be done with queries for now when their type is ENUM.

We cannot use the class Migration for these columns for now. I think this feature is missing.

**Comment by trasher** [comment]
Since ENUM is a mysql specific type and we're looking to support other database engines; I wonder if this is a good idea.

**Comment by btry** [comment]
This is not the same?

https://www.postgresql.org/docs/9.1/static/datatype-enum.html

**Comment by trasher** [comment]
Maybe yes... I don't remember why I had in mind that was specific. Maybe on older pgsql?

**Comment by cedric-anne** [comment]
Hi,

If you look at the implementation, it is really different between MySQL and PostgreSQL.
In MySQL, different values are stored in your table schema.
In PostgreSQL, the enum have to be declared as a global type, and you will have to handle its name unicity across all your database.

So I guess handling it as a integer or varchar field and handling different values in PHP code is preferable as trying to make something that handles enum types accross different DB engines.

Regards
