### ISSUE TITLE
Missing 2 columns in Parc Computers

### ISSUE THREAD

**Issue by lyonelf** [glpi-project/glpi#11581]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

in Parc Computers view, their is no possibility to add a column for the GLPI Agent version and for the inventory TAG

**Comment by cconard96** [comment]
This doesn't seem like a bug, just a missing feature from when the inventory code was integrated. I don't see any agent search options for inventory devices like Computers and the Agent item type doesn't seem to define any search options to be used by other item types.

**Comment by lyonelf** [comment]
I know it's not an issue but a missing.
It's @g-bougard who say me to post an issue about that

**Comment by trasher** [comment]
Done in #11601
