### ISSUE TITLE
Ticket Timeline Enhancement : Display total of ticket tasks actiontime

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1159]
![image](https://cloud.githubusercontent.com/assets/13178158/19343870/533e6ca0-9138-11e6-9f4a-c9a56dca17a1.png)

Like this.

I send a PR ?

**Comment by tomolimo** [comment]
yes, good idea

**Comment by orthagh** [comment]
i agree also.

Some suggestions: 
- Align right (you have some padding)
- maybe fade the color, currently it attract eye (same color and size as titles) for a secondary information

**Comment by flegastelois** [comment]
Hi Xavier, good idea yes! 
What do you think if also add other quick statistics like "% Done tasks" / "% ToDo tasks", maybe on tooltip ? I don't know the best way for displaying.
Cheers,

**Comment by tsmr** [comment]
Like this ?

![image](https://user-images.githubusercontent.com/13178158/80604867-93269a80-8a32-11ea-8ac0-7858bca6d92c.png)
