### ISSUE TITLE
[GLPI 10 Bugfixes] Automatic inventory state doesn't match like in One user assignation default rule in Asset Rule engine

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#11596]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

There is a default rule (for user affectation from contact informations)

One user assignation
![image](https://user-images.githubusercontent.com/13178158/168618834-f3b31e79-f477-4763-87ea-99655f582c3e.png)

On GLPI inventory agent import (or synchronisation) the computer don't match this rule because of this criterion : 

![image](https://user-images.githubusercontent.com/13178158/168619101-c5f197fb-0716-479d-8140-399b22fa6b78.png)

If i delete these criterion, the rule matches

**Comment by g-bougard** [comment]
As tested myself but with a dedicated rule which sets the technical user when alternate username is matching a given value. With this one, it seems the rule is triggered when "Automatic inventory" criterion is defined on "is" "No":
 - when "Automatic inventory" criterion is defined on "is" "Yes", the technical user is not selected when I import a matching inventory
 - but if it is defined on "is" "No", the technical user is selected when I import a matching inventory

Here is the XML export of the rule I tested:
```
<?xml version="1.0"?>
<rules>
	<rule>
		<entities_id>Entit&#xE9; racine</entities_id>
		<sub_type>RuleAsset</sub_type>
		<ranking>4</ranking>
		<name>Test affectation repsonsable technique</name>
		<description></description>
		<match>AND</match>
		<is_active>1</is_active>
		<comment></comment>
		<is_recursive>0</is_recursive>
		<uuid>f5e0fca4-6f8bf73d-62825e84a255f0.98963250</uuid>
		<condition>3</condition>
		<date_creation>2022-05-16 16:24:04</date_creation>
		<rulecriteria><criteria>_itemtype</criteria><condition>0</condition><pattern>Computer</pattern></rulecriteria>
		<rulecriteria><criteria>contact</criteria><condition>0</condition><pattern>gbougard</pattern></rulecriteria>
		<rulecriteria><criteria>_auto</criteria><condition>1</condition><pattern>0</pattern></rulecriteria>
		<ruleaction><action_type>assign</action_type><field>users_id_tech</field><value>glpi</value></ruleaction>
	</rule>
</rules>
```
This export is for "Item type" is "Computer", "Altername Username" is "gbougard" and "Automatic inventory" is "Yes".

There's maybe another problem with "One user assignation": it seems to work even when the rule is disabled and I import a computer with a user set as a User is always set, not just the "Alternate username". But maybe I'm doing the test the wrong way.

**Comment by trasher** [comment]
No feedback, closing
