### ISSUE TITLE
[GLPI 10] Characters encoding

### ISSUE THREAD

**Issue by warllintan** [glpi-project/glpi#11597]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

In almost all fields filled in GLPI after updating from version 9 to version 10 there was a fallout where the texts are with special characters, has anyone had this problem?
![image](https://user-images.githubusercontent.com/105663574/168641708-123dc2f6-be72-48aa-b843-267866e1e02d.png)
I notice that when accessing GLPI with an ip address on the local network this error disappears

### Page URL

https://ticket.meudominio.com.br/front/computer.form.php?id=81

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.0 ( => C:\inetpub\GlPI)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT DP0000SRV0008 10.0 build 14393 (Windows Server 2016) AMD64
PHP 7.4.1 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sodium, standard, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter,
	zend-test, zip, zlib)
Setup: max_execution_time="600" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.21
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (7.4.1) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.21) is supported.
The log file has been created successfully.
Write access to C:\inetpub\GlPI/files/_cache has been validated.
Write access to C:\inetpub\GlPI/config has been validated.
Write access to C:\inetpub\GlPI/files/_cron has been validated.
Write access to C:\inetpub\GlPI/files has been validated.
Write access to C:\inetpub\GlPI/files/_dumps has been validated.
Write access to C:\inetpub\GlPI/files/_graphs has been validated.
Write access to C:\inetpub\GlPI/files/_lock has been validated.
Write access to C:\inetpub\GlPI/files/_pictures has been validated.
Write access to C:\inetpub\GlPI/files/_plugins has been validated.
Write access to C:\inetpub\GlPI/files/_rss has been validated.
Write access to C:\inetpub\GlPI/files/_sessions has been validated.
Write access to C:\inetpub\GlPI/files/_tmp has been validated.
Write access to C:\inetpub\GlPI/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\GlPI/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\inetpub\GlPI
GLPI_CONFIG_DIR: C:\inetpub\GlPI/config
GLPI_VAR_DIR: C:\inetpub\GlPI/files
GLPI_MARKETPLACE_DIR: C:\inetpub\GlPI/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\inetpub\GlPI/files
GLPI_CACHE_DIR: C:\inetpub\GlPI/files/_cache
GLPI_CRON_DIR: C:\inetpub\GlPI/files/_cron
GLPI_DUMP_DIR: C:\inetpub\GlPI/files/_dumps
GLPI_GRAPH_DIR: C:\inetpub\GlPI/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\inetpub\GlPI/files/_locales
GLPI_LOCK_DIR: C:\inetpub\GlPI/files/_lock
GLPI_LOG_DIR: C:\inetpub\GlPI/files/_log
GLPI_PICTURE_DIR: C:\inetpub\GlPI/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\inetpub\GlPI/files/_plugins
GLPI_RSS_DIR: C:\inetpub\GlPI/files/_rss
GLPI_SESSION_DIR: C:\inetpub\GlPI/files/_sessions
GLPI_TMP_DIR: C:\inetpub\GlPI/files/_tmp
GLPI_UPLOAD_DIR: C:\inetpub\GlPI/files/_uploads
GLPI_INVENTORY_DIR: C:\inetpub\GlPI/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\inetpub\GlPI/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\inetpub\GlPI\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\inetpub\GlPI\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\GlPI\vendor\simplepie\simplepie\library)
mpdf/mpdf in (C:\inetpub\GlPI\vendor\mpdf\mpdf\src)
michelf/php-markdown in (C:\inetpub\GlPI\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\GlPI\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\GlPI\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\GlPI\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\GlPI\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\GlPI\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\GlPI\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\GlPI\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\GlPI\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\GlPI\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\GlPI\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\GlPI\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\GlPI\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\GlPI\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\GlPI\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\GlPI\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\GlPI\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\GlPI\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\GlPI\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\GlPI\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\GlPI\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\GlPI\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\GlPI\vendor\psr\cache\src)
league/csv in (C:\inetpub\GlPI\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\GlPI\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\GlPI\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\GlPI\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\GlPI\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\GlPI\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\GlPI\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\GlPI\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\GlPI\vendor\html2text\html2text\src)
symfony/dom-crawler in (C:\inetpub\GlPI\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\GlPI\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\GlPI\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (C:\inetpub\GlPI\vendor\symfony\polyfill-php80)
symfony/polyfill-php81 in (C:\inetpub\GlPI\vendor\symfony\polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: '192.168.1.7', Port: '389', BaseDN: 'DC=corp,DC=clubedompedroii,DC=com,DC=br', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'DOMPEDROII\administrator', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (warllintan@smtplw.com.br)

</details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Enabled
	news                 Name: Alertas                        Version: 1.9.0      State: To update
	fields               Name: Campos adicionais              Version: 1.13.0-rc3 State: Enabled
	screenshot           Name: Captura de tela                Version: 2.0.0-beta1 State: Enabled
	printercounters      Name: Contadores de impressora       Version: 2.0.0      State: Enabled
	accounts             Name: Contas                         Version: 3.0.0-rc2  State: Enabled
	datainjection        Name: Data injection                 Version: 2.8.0      State: Not installed
	archimap             Name: Diagrams                       Version: 3.0.2      State: Not installed
	addressing           Name: Endereçamento IP               Version: 3.0.0-rc2  State: Enabled
	formcreator          Name: Form Creator                   Version: 2.10.2     State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Not installed
	order                Name: Gerenciamento das ordens de co Version: 2.8.0      State: Enabled
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.8.0      State: Not installed
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.0-rc2 State: Installed / not activated
	pdf                  Name: Imprimir em PDF                Version: 1.7.0      State: Not installed
	mydashboard          Name: Meu Painel                     Version: 1.8.2      State: Not installed
	dashboard            Name: Painel                         Version: 0.9.9      State: Enabled
	resources            Name: Recursos humanos               Version: 3.0.0-rc2  State: Enabled
	reports              Name: Relatórios                     Version: 1.14.1     State: Not installed
	financialreports     Name: Situação dos ativos            Version: 3.0.0-rc2  State: Enabled
	tasklists            Name: Tasks list                     Version: 1.6.2      State: Not installed
	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Installed / not activated
	webservices          Name: Web Services                   Version: 2.1.0      State: Not installed

</pre></details>

**Comment by cconard96** [comment]
Is this issue only present in dropdown fields? Are the other options messed up as well or just the current values?

**Comment by warllintan** [comment]
![image](https://user-images.githubusercontent.com/105663574/168648379-0f3b1a46-6914-4d0f-9f2e-2b34164ea03d.png)
only the current or selected field

**Comment by cedric-anne** [comment]
Hi,

Which browser are you using ?

Regards

**Comment by tsmr** [comment]
For information, i'm using datainjection plugin for inject itil categories with GLPI 10, and i have same encoding problem (i becomes 1)

**Comment by warllintan** [comment]
![image](https://user-images.githubusercontent.com/105663574/168876813-c9d652ed-8642-4966-8d58-e5378e85456d.png)
in firefox browser it appends "â" to the end of the word

**Comment by cedric-anne** [comment]
Hi,

Could you give more details on your client environment (i.e. OS, browser, and browser version) ?

**Comment by trasher** [comment]
No feedback, I close.
