### ISSUE TITLE
Antivirus not showing

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#11603]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.1 

### Bug description

Hello everyone, there is a problem.
On the operating system (Microsoft Windows Server 2019, Microsoft Windows Server 2012 R2, Microsoft Windows Server 2016), the GLPI service page does not display antivirus software. Dr.Web Server, Dr.Web Agent version 13.0, Kaspersky Endpoint Security and Kaspersky Security Center are not displayed on the Windows platform. It displays normally on Windows 7 and Windows 10 workstations.
On Linux, ClamAV antivirus is not displayed.

### Relevant log output

```shell
[2022-05-17 16:13:25] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_computerantiviruses` (`name`, `is_active`, `is_uptodate`, `antivirus_version`, `is_dynamic`, `computers_id`, `date_creation`, `date_mod`) VALUES ('ESET Endpoint Antivirus', '1', '', '', '1', '49', '2022-05-17 16:13:24', '2022-05-17 16:13:24')
  Error: Incorrect integer value: '' for column `GLPI`.`glpi_computerantiviruses`.`is_uptodate` at row 1
  Backtrace :
  src/DBmysql.php:1312                               
  src/CommonDBTM.php:704                             DBmysql->insert()
  src/CommonDBTM.php:1296                            CommonDBTM->addToDB()
  src/Inventory/Asset/Antivirus.php:144              CommonDBTM->add()
  src/Inventory/Asset/MainAsset.php:792              Glpi\Inventory\Asset\Antivirus->handle()
  src/Inventory/Asset/MainAsset.php:713              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:942                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1507                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:536              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:680                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:318                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:366                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:325    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:237    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:85                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
  {"user":"inventory@glpi.stolyarov.info"}
```

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.1 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.stolyarov.info 5.4.17-2136.307.3.1.el8uek.x86_64 #2 SMP Mon May 9 17:29:47 PDT 2022 x86_64
PHP 7.4.29 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysql, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Server Software: MariaDB Server
	Server Version: 10.3.32-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/GLPI
	Host info: Localhost via UNIX socket
	
PHP version (7.4.29) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.32) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
For security reasons, SELinux mode should be Enforcing.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1@3596dc2513665d8511084308966f1d2af201c6b6
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: '192.168.30.190', Port: '3268', BaseDN: 'DC=localhost,DC=info', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=ldapsearch-glpi,OU=Special,DC=localhost,DC=info', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mail2.stolyarov.info)

</details><details><summary>Plugins list</summary><pre> 
	archisw              Name: Apps structures                Version: 2.2.9      State: Enabled
	connections          Name: Connections                    Version: 10.0.0     State: Installed / not activated
	archidata            Name: Data structures                Version: 1.0.9      State: Installed / not activated
	dataflows            Name: Dataflows                      Version: 2.2.11     State: Enabled
	manageentities       Name: Entities portal                Version: 4.0.0      State: Installed / not activated
	financialreports     Name: Financial reports              Version: 3.0.0      State: Installed / not activated
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	addressing           Name: IP Adressing                   Version: 3.0.0      State: Installed / not activated
	mreporting           Name: More Reporting                 Version: 1.8.0      State: Installed / not activated
	printercounters      Name: Printer counters               Version: 2.0.0      State: Installed / not activated
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Not installed
	reports              Name: Reports                        Version: 1.14.1     State: Installed / not activated
	shellcommands        Name: Shell Commands                 Version: 4.0.0      State: Installed / not activated
	manufacturersimports Name: Suppliers imports              Version: 3.0.0      State: Enabled
	tag                  Name: Tag Management                 Version: 2.9.0      State: Enabled
	typology             Name: Typologies                     Version: 3.0.0      State: Installed / not activated
	useditemsexport      Name: Used items export              Version: 2.5.0      State: Enabled

</pre></details>

**Comment by Badkempachi** [comment]
inventory file
[wsus2.stolyarov.info-2022-03-12-21-45-56.txt](https://github.com/glpi-project/glpi/files/8709132/wsus2.stolyarov.info-2022-03-12-21-45-56.txt)

**Comment by Badkempachi** [comment]
P.s the agent itself collects information about installed antiviruses, but the server does not receive information sent to it.

**Comment by trasher** [comment]
Provided file is not valid XML, and does not contains any "antivirus" node. Once again, I'm not able to reproduce.

**Comment by orthagh** [comment]
@Badkempachi 

You must check the files before attach them and open issue.
As @trasher said, your current file doesn't have an `<ANTIVIRUS>` node so the error you mentioned in your issue is not triggered by the current file.
Having Dr.Web in a `<SOFTWARE>` is not sufficient to have an antivirus management by the native inventory.

So 2 hypothesis:
- you're sending to us the wrong file
- you removed yourself the node.

Please check.

**Comment by steph461** [comment]
hello same issue

I join for example file computer.json
[computer_0_156.zip](https://github.com/glpi-project/glpi/files/8714070/computer_0_156.zip)

SQl ERROR : computer_0_156.json for example

```shell
[2022-05-18 09:22:23] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_computerantiviruses` SET `is_uptodate` = '' WHERE `id` = '247'
  Error: Incorrect integer value: '' for column `glpi`.`glpi_computerantiviruses`.`is_uptodate` at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:660                             DBmysql->update()
  src/CommonDBTM.php:1649                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Antivirus.php:124              CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:775              Glpi\Inventory\Asset\Antivirus->handle()
  src/Inventory/Asset/MainAsset.php:696              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:942                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1507                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:522              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:694                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:330                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:366                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:325    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:237    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  src/Inventory/Conf.php:196                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:138                         Glpi\Inventory\Conf->importContentFile()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->importFile()
  {"user":"7@srv-glpi"} 
[2022-05-18 09:25:05] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_computerantiviruses` SET `is_uptodate` = '' WHERE `id` = '247'
  Error: Incorrect integer value: '' for column `glpi`.`glpi_computerantiviruses`.`is_uptodate` at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:660                             DBmysql->update()
  src/CommonDBTM.php:1649                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Antivirus.php:124              CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:775              Glpi\Inventory\Asset\Antivirus->handle()
  src/Inventory/Asset/MainAsset.php:696              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:942                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1507                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:522              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:694                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:330                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:366                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:325    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:237    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  src/Inventory/Conf.php:196                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:138                         Glpi\Inventory\Conf->importContentFile()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->importFile()
  {"user":"7@srv-glpi"}

**Comment by trasher** [comment]
I'm not able to reproduce with provided file :/ Antivirus seems correctly imported without errors (at least on current nighly):
![image](https://user-images.githubusercontent.com/224733/168982611-87e35c11-d99d-4823-a522-a341772ff400.png)

**Comment by steph461** [comment]
computer 156 : 

it is added well in the computer but it generates this sql file. error I don't know why

displays ok but generation sql.error : 
![image](https://user-images.githubusercontent.com/68054991/168983185-39a8ef80-c15d-4130-8a29-13b437e82760.png)

**Comment by trasher** [comment]
I think I found the issue... Reporter says he uses php 7.4; but on my side, I reproduce only with php 8...

**Comment by steph461** [comment]
> I think I found the issue... Reporter says he uses php 7.4; but on my side, I reproduce only with php 8...

I use PHP 8.0.18

**Comment by Badkempachi** [comment]
> @Badkempachi
> 
> You must check the files before attaching them and open issue. As @trasher said, your current file doesn't have an `<ANTIVIRUS>` node so the error you mentioned in your issue is not triggered by the current file. Having Dr.Web in a `<SOFTWARE>` node is not sufficient to have an antivirus management by the native inventory.
> 
> So 2 hypothesis:
> 
>     * you're sending to us the wrong file
> 
>     * you removed yourself the node.
> 
> 
> Please check.

Hey,
This is a screenshot of the Dr.web server software, the control panel and the agent itself are installed on it, and it does not show that the antivirus is installed. The situation is repeated on the Kaspersky server. Might need to be added somewhere. If the antivirus does not get into the <ANTIVIRUS> node, then how to make it get there?
![1](https://user-images.githubusercontent.com/97535165/168991272-e1d62a95-812b-4c75-ae75-4dbda2569fe5.png)

**Comment by trasher** [comment]
You're talking about a different issue that the one reported here. This is an agent/windows issue, not a GLPI one.

**Comment by Badkempachi** [comment]
> You're talking about a different issue that the one reported here. This is an agent/windows issue, not a GLPI one.

understood. Thank you
