### ISSUE TITLE
[10.0.0] Ticket::check() rights for UPDATE not called

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#11618]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Code change for assigning without update  https://github.com/glpi-project/glpi/pull/10874 broke the item_can check.
https://github.com/glpi-project/glpi/blob/0925776bc340eac026dcaa1da711f94e514e5ecf/front/ticket.form.php#L81
Previously it was checked like this:

``$track->check($_POST['id'], UPDATE)``

It basically breaks the the plugins which limit the UPDATE rights on Ticket based on some additional criteria by using item_can.

Is it possible to fix the assignment and have this $track->check($_POST['id'], UPDATE) somewhere still in place?

**Comment by cconard96** [comment]
Do you have an example of a plugin that has this issue?

**Comment by VladoTTX** [comment]
it is not an official plugin on glpi network but my own developed based on available [documentation](https://glpi-developer-documentation.readthedocs.io/en/latest/plugins/hooks.html). Hook is similar to this:
 ``$PLUGIN_HOOKS['item_can']['example']  = ['Ticket' => ['PluginExampleTicket', 'item_can']]; ``

Inside the method, based on few conditions I evaluate whether action is allowed or not:
``if($item->right != READ){  ``

After https://github.com/glpi-project/glpi/pull/10874 GLPI is no longer calling the $item->check() on update, so plugin hook does not fire on during item UPDATE.

**Comment by cconard96** [comment]
The right check is still done via the canUpdate function.
The difference is that it checks UPDATE, ASSIGN, STEAL, OWN, and CHANGEPRIORITY rights and if the user has any, the update is allowed. During the update, checks are made to ensure user with rights like CHANGEPRIORITY can only update certain fields.

It is hard to say for sure, but you may be able to accomplish what you were doing before in your plugin using one or more of the other item lifecycle hooks like `pre_item_update` which can cancel an update (if you return false) or modify the fields being updated.

**Comment by VladoTTX** [comment]
Thanks, I know right is still checked but different way. 
Yes, I have considered other possibilities how to overcome this change in GLPI code and yes it is indeed possible to fix the plugin.

But this change IMHO:
1. Makes GLPI inconsistent - check() and item_can is called for other type of modifications on Ticket object like PURGE, DELETE but for UPDATE not at all.
2. It makes item_can hook quite useless and impractical to use (at least for Tickets)

If code is not updated to include check() call for UPDATE I would recommend to mention this in the documentation so people are aware of these inconsistencies.

It would be nice to have a hook which could be used easily to limit the rights of user based on context of call. Till now item_can was useable for this.

**Comment by VladoTTX** [comment]
I managed to update the plugin.
But don't know how to reliable way to distinguish whether Ticket::update is result of backend action (like approbation form approval and change of status) or frontend like user doing some changes via UI.

Is there a clean way to distinguish that besides checking for input and amount of data submitted?
Previously Ticket::check() was called just on frontend so it was clearly separated.
