### ISSUE TITLE
Software not deleted in GLPI after glpi agent uninstall the software

### ISSUE THREAD

**Issue by ONBET** [glpi-project/glpi#11621]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0

### Bug description

Software not deleted in GLPI after glpi agent uninstall the software. The computer in GLPI still have the old list of software and not up to date

**Comment by trasher** [comment]
Software themselves are not removed; only link with asset is. I've tested with a fedora operating system update; seems that software associated to computer are only the new ones.

**Comment by trasher** [comment]
No feedback, closing
