### ISSUE TITLE
SQL error when the search field contains an apostrophe

### ISSUE THREAD

**Issue by lilian-pouliquen** [glpi-project/glpi#11629]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Whenever I use the search field with "contains" option, the form gives me a SQL error if I wrote an apostrophe in the search field.

The error returned when I am filtering tickets by title with the text "l'installation" is the following :

>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'installation%' ) ) GROUP BY `glpi_tickets`.`id` ORDER BY `ITEM_Ticket_19` DESC' at line 24

This happens on the search forms of these pages:

- Assets
  - Software
  - Printers
  - Consumables
  - Racks
  - Passive devices
  - Unmanaged device
  - Cables
  - Simcards
- Assistance
  - Tickets
  - Problems
  - Changes
  - Recurrent changes
- Management
  -  Licenses
  - Budgets
  - Suppliers
  - Documents
  - Lines
  - Certificates
  - Clusters
  - Appliances
  - Databases
- Tools
  - Saved searches
- Administration
  - Users
  - Groups
  - Entities
- Setup
  - Service levels
  - Receivers
  - External links

The SQL error can also be seen when using an apostophe in the navbar search box.

### Steps To reproduce

1. Go on whatever page quoted in the list above ;
2. Use the filter form to filter by items description for example ;
3. Type a filter that contains an apostrophe ;
4. Confirm search.

Alternative:

1. Use the navbar search box ;
2. Type anything that contains an apostrophe ;
3. Confirm search.

### Your GLPI setup information

Docker container GLPI:

- From redhat/ubi8-minimal:8.5-240
- GLPI 10.0.0
- PHP-FPM 8.1.5

Docker container Httpd:

- From redhat/ubi8-minimal:8.5-240
- Httpd 2.4.37 with Fast-CGI

MySQL server:

- Server RHEL 8.6
- MariaDB 10.3.32

**Comment by trasher** [comment]
This has already been fixed; try nightly

**Comment by lilian-pouliquen** [comment]
Okay thank you, I will wait for the next release before upgrading in production then.
