### ISSUE TITLE
[GLPI 10] Unable to view closed tickets on self-service profile

### ISSUE THREAD

**Issue by Wacxiuz** [glpi-project/glpi#11620]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI v10

### Bug description

Hello,
Users create tickets which we process. Once processed, we close them directly.
Our users use the "SELF SERVICE" profile with default group permissions.
However, the problem is this:
Users cannot see the content of closed tickets, even though they are in the requester box.
The list is well displayed, but when they click on the closed tickets, there is a gray page.

### Relevant log output

```shell
Error apache:

[Thu May 19 09:03:35.191599 2022] [proxy_fcgi:error] [pid 3447265] [client 192.168.100.94:49940] AH01071: Got error 'PHP message: PHP Notice:  Object of class Ticket could not be converted to int in /var/www/glpi/src/CommonDBTM.php on line 2734PHP message: PHP Notice:  Object of class Ticket could not be converted to int in /var/www/glpi/src/CommonDBTM.php on line 2734PHP message: PHP Notice:  Object of class Ticket could not be converted to int in /var/www/glpi/src/CommonDBTM.php on line 2902', referer: https://helpdesk.xxxxx.com/marketplace/formcreator/front/issue.php?as_map=0&browse=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=4&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=6&itemtype=PluginFormcreatorIssue&start=0&_glpi_csrf_token=443e92a65eafe689c4b200aa07c01183cb4e59586200b250a3633075b798b501&sort%5B%5D=6&order%5B%5D=DESC
```

### Page URL

https://helpdesk.xxxxxx.com/marketplace/formcreator/front/issue.form.php?id=5575&tickets_id=5574

### Steps To reproduce

1. Close a ticket
2. Attempt to read the self-service content there

**Comment by cconard96** [comment]
Please include your GLPI system information and any GLPI log entries (not the Apache log) from around the time of the error.

System information can be found in Setup > General > System tab.
GLPI logs can be found in `files/_log`. Primarily we would need to look at `php-errors.log` and `sql-errors.log`.

**Comment by trasher** [comment]
Looks like a formcreator issue, please report on plugin repository
