### ISSUE TITLE
error on ℹ link in a ticket - id's interverted

### ISSUE THREAD

**Issue by Grazouillis** [glpi-project/glpi#11630]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Hello team,

I observed a problem with the ℹ which appears on a ticket
When a superadmin answers, the "i" leads to the superadmin profile instead the user profile, but not the name

![image](https://user-images.githubusercontent.com/8795284/169272648-748797b1-8b56-40d8-8681-381a293b9334.png)

![image](https://user-images.githubusercontent.com/8795284/169272220-f9c3e3d0-5748-4d89-9ba8-27ac70fa63b7.png)
_ 
I tried to search this bug on issues but my english isn't maybe good enough to find it...

Thank you for your help :)

Have a nice day !

### Page URL

https://support.[...].be/front/ticket.form.php?id=xxxx

### Steps To reproduce

Many profiles : simple user, technician, superadmin
discuss in a ticket with a superadmin and a user

### Your GLPI setup information

Informations sur le système, l'installation et la configuration
--
Vérifier si une nouvelle version est disponible
[code]   GLPI 9.5.7 ( => /var/www/glpi-957) Installation mode: TARBALL Current language:fr_FR

Informations sur le système, l'installation et la configuration
[Vérifier si une nouvelle version est disponible](https://support.[...].be/front/config.form.php?check_version)
[code]
 
GLPI 9.5.7 ( => /var/www/glpi-957)
Installation mode: TARBALL
Current language:fr_FR

Server
 
Operating system: Linux srv-sc-support-1 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64
PHP 7.4.27 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="5M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at support.[...].be Port 443)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.162 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.5.8-MariaDB-log
	Server SQL Mode: 
	Parameters: glpiuser@192.168.4.24/glpi
	Host info: 192.168.4.24 via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.8) - Perfect!Database version seems correct (10.5.8) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi-957/files/_cache has been validated.Write access to /var/www/glpi-957/files/_cache has been validated.
Write access to /var/www/glpi-957/config has been validated.Write access to /var/www/glpi-957/config has been validated.
Write access to /var/www/glpi-957/files/_cron has been validated.Write access to /var/www/glpi-957/files/_cron has been validated.
Write access to /var/www/glpi-957/files has been validated.Write access to /var/www/glpi-957/files has been validated.
Write access to /var/www/glpi-957/files/_dumps has been validated.Write access to /var/www/glpi-957/files/_dumps has been validated.
Write access to /var/www/glpi-957/files/_graphs has been validated.Write access to /var/www/glpi-957/files/_graphs has been validated.
Write access to /var/www/glpi-957/files/_lock has been validated.Write access to /var/www/glpi-957/files/_lock has been validated.
Write access to /var/www/glpi-957/files/_pictures has been validated.Write access to /var/www/glpi-957/files/_pictures has been validated.
Write access to /var/www/glpi-957/files/_plugins has been validated.Write access to /var/www/glpi-957/files/_plugins has been validated.
Write access to /var/www/glpi-957/files/_rss has been validated.Write access to /var/www/glpi-957/files/_rss has been validated.
Write access to /var/www/glpi-957/files/_sessions has been validated.Write access to /var/www/glpi-957/files/_sessions has been validated.
Write access to /var/www/glpi-957/files/_tmp has been validated.Write access to /var/www/glpi-957/files/_tmp has been validated.
Write access to /var/www/glpi-957/files/_uploads has been validated.Write access to /var/www/glpi-957/files/_uploads has been validated.
Write access to /var/www/glpi-957/marketplace has been validated.Write access to /var/www/glpi-957/marketplace has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI constants
 
GLPI_ROOT: /var/www/glpi-957
GLPI_CONFIG_DIR: /var/www/glpi-957/config
GLPI_VAR_DIR: /var/www/glpi-957/files
GLPI_MARKETPLACE_DIR: /var/www/glpi-957/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/glpi-957/files
GLPI_CACHE_DIR: /var/www/glpi-957/files/_cache
GLPI_CRON_DIR: /var/www/glpi-957/files/_cron
GLPI_DUMP_DIR: /var/www/glpi-957/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi-957/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi-957/files/_locales
GLPI_LOCK_DIR: /var/www/glpi-957/files/_lock
GLPI_LOG_DIR: /var/www/glpi-957/files/_log
GLPI_PICTURE_DIR: /var/www/glpi-957/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi-957/files/_plugins
GLPI_RSS_DIR: /var/www/glpi-957/files/_rss
GLPI_SESSION_DIR: /var/www/glpi-957/files/_sessions
GLPI_TMP_DIR: /var/www/glpi-957/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi-957/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi-957/locales
GLPI_VERSION: 9.5.7
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022
GLPI_MOD_DIR: /var/www/glpi-957/plugins/mod

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/glpi-957/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/glpi-957/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/glpi-957/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi-957/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi-957/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi-957/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi-957/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi-957/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi-957/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi-957/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi-957/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/glpi-957/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/glpi-957/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/glpi-957/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/glpi-957/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi-957/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi-957/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi-957/plugins/addmembertask/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi-957/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi-957/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi-957/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi-957/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi-957/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi-957/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi-957/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi-957/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/glpi-957/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi-957/plugins/addmembertask/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi-957/plugins/addmembertask/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/glpi-957/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi-957/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

LDAP directories
 
Server: '10.150.250.9', Port: '389', BaseDN: 'DC=[...],DC=be', Connection filter:
		'(&(objectClass=user)(objectCategory=organizationalPerson))', RootDN: 'ldapconsumer@[...].be', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@smtp.[...].be)

Mails receivers
 
Name: 'support.it.he@[...].be' Active: Yes
	Server: '{outlook.office365.com/imap/tls}' Login: 'fcthesupportit@[...].be' Password: Yes

Plugins list
 
	addmembertask        Name: AddMemberTask                  Version: 0.0.1      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.12.0     State: Enabled
	formcreator          Name: Form Creator                   Version: 2.10.4     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+4.0    State: Enabled
	getuseragentinfo     Name: GetUserAgentInfo               Version: 0.0.3      State: Enabled
	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled
	tag                  Name: Tag Management                 Version: 2.8.1      State: Enabled

[/code]

**Comment by trasher** [comment]
Please check with latest release (GLPI 10.0) if issue persists.

**Comment by cedric-anne** [comment]
View has been refactored in GLPI 10.0 and problem does not seems to exist anymore.
