### ISSUE TITLE
Cannot remove lock on disconnecte devices

### ISSUE THREAD

**Issue by rean1mat0r** [glpi-project/glpi#11636]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Hello!
after updating GLPI from 9.5.6 to version with V10, I eventually found a problem: if you disconnect any device from the computer in the "Connections" tab, then when you try to connect the device back, the device does not connect.
After disconnecting the device, it gets into the "Locks" tab.
At the same time, the asset "Computer" in the "History" tab appears the entry "Lock a link with an item: NM-30-19PC".

If you try to remove the lock from the device in the "Locks" tab, nothing changes, the device remains locked, the system does not issue a pop-up message about a successful operation or error. At the same time, the next entry "Computer blocks communication with the element: NM-30-19PC (566)" is added again to the asset "Computer" in the "History" tab.

Also, devices are blocked in a similar way when transferring computers between organizations.

### Steps To reproduce

Option #1:
1. disconnect the monitor/printer from the computer
2. try to connect back
3. result: nothing is connected, and there is a record in the computer history "blocks communication with the element: "name_of_element"

Option #1:
condition:  We have an import rule that, when checking the IP, assigns the desired organization depending on the IP.
1. The computer was moved between organizations
2. At the next inventory, according to the import rule, another organization was assigned to the computer, but the devices connected to it remained in the previous organization.
3. We move the devices connected to the computer.
4.Result: the devices have moved, the connection with the computer has been blocked
5. Attempt to unlock the device via the "Locks" tab: check the boxes on the devices, click "Action", select "Delete forever". Result: we get the message "Operation successful", but the monitor remains in the blocked list, the connection is not restored and another entry "Lock a link with an item:" appears in the history

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 ( => /var/www/itsm.filial-fnkc)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux Server-ITSM 5.13.0-41-generic #46~20.04.1-Ubuntu SMP Wed Apr 20 13:16:21 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gnupg, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0
Server Software: (Ubuntu)
	Server Version: 8.0.29-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/itsm_filial_fnkc_db
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.29) is supported.
The log file has been created successfully.
Write access to /var/www/itsm.filial-fnkc/files/_cache has been validated.
Write access to /var/www/itsm.filial-fnkc/config has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_cron has been validated.
Write access to /var/www/itsm.filial-fnkc/files has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_dumps has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_graphs has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_lock has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_pictures has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_plugins has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_rss has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_sessions has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_tmp has been validated.
Write access to /var/www/itsm.filial-fnkc/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/itsm.filial-fnkc/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/itsm.filial-fnkc
GLPI_CONFIG_DIR: /var/www/itsm.filial-fnkc/config
GLPI_VAR_DIR: /var/www/itsm.filial-fnkc/files
GLPI_MARKETPLACE_DIR: /var/www/itsm.filial-fnkc/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/itsm.filial-fnkc/files
GLPI_CACHE_DIR: /var/www/itsm.filial-fnkc/files/_cache
GLPI_CRON_DIR: /var/www/itsm.filial-fnkc/files/_cron
GLPI_DUMP_DIR: /var/www/itsm.filial-fnkc/files/_dumps
GLPI_GRAPH_DIR: /var/www/itsm.filial-fnkc/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/itsm.filial-fnkc/files/_locales
GLPI_LOCK_DIR: /var/www/itsm.filial-fnkc/files/_lock
GLPI_LOG_DIR: /var/www/itsm.filial-fnkc/files/_log
GLPI_PICTURE_DIR: /var/www/itsm.filial-fnkc/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/itsm.filial-fnkc/files/_plugins
GLPI_RSS_DIR: /var/www/itsm.filial-fnkc/files/_rss
GLPI_SESSION_DIR: /var/www/itsm.filial-fnkc/files/_sessions
GLPI_TMP_DIR: /var/www/itsm.filial-fnkc/files/_tmp
GLPI_UPLOAD_DIR: /var/www/itsm.filial-fnkc/files/_uploads
GLPI_INVENTORY_DIR: /var/www/itsm.filial-fnkc/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/itsm.filial-fnkc/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/itsm.filial-fnkc/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/itsm.filial-fnkc/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/itsm.filial-fnkc/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/itsm.filial-fnkc/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/itsm.filial-fnkc/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/itsm.filial-fnkc/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/itsm.filial-fnkc/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/itsm.filial-fnkc/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/itsm.filial-fnkc/vendor/sabre/http/lib)
sabre/uri in (/var/www/itsm.filial-fnkc/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/itsm.filial-fnkc/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/itsm.filial-fnkc/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/itsm.filial-fnkc/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/itsm.filial-fnkc/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/itsm.filial-fnkc/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/itsm.filial-fnkc/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/itsm.filial-fnkc/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/itsm.filial-fnkc/vendor/symfony/console)
scssphp/scssphp in (/var/www/itsm.filial-fnkc/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/itsm.filial-fnkc/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/itsm.filial-fnkc/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/itsm.filial-fnkc/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/itsm.filial-fnkc/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/itsm.filial-fnkc/vendor/ramsey/uuid/src)
psr/log in (/var/www/itsm.filial-fnkc/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/itsm.filial-fnkc/vendor/psr/simple-cache/src)
psr/cache in (/var/www/itsm.filial-fnkc/vendor/psr/cache/src)
league/csv in (/var/www/itsm.filial-fnkc/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/itsm.filial-fnkc/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/itsm.filial-fnkc/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/itsm.filial-fnkc/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/itsm.filial-fnkc/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/itsm.filial-fnkc/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/itsm.filial-fnkc/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/itsm.filial-fnkc/vendor/symfony/cache)
html2text/html2text in (/var/www/itsm.filial-fnkc/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/itsm.filial-fnkc/vendor/symfony/dom-crawler)
twig/twig in (/var/www/itsm.filial-fnkc/vendor/twig/twig/src)
twig/string-extra in (/var/www/itsm.filial-fnkc/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/itsm.filial-fnkc/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/itsm.filial-fnkc/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (samuylov.sa@kmail.fnkc-fmba.ru)

</details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled
	archisw              Name: Apps structures                Version: 2.2.9      State: Enabled
	archibp              Name: Business Processes             Version: 1.0.4      State: Enabled
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Not installed
	cmdb                 Name: CMDB                           Version: 3.0.1      State: Enabled
	connections          Name: Connections                    Version: 10.0.0     State: Enabled
	dataflows            Name: Dataflows                      Version: 2.2.13     State: Enabled
	archimap             Name: Diagrams                       Version: 3.2.7      State: Enabled
	archifun             Name: Functional Areas               Version: 2.2.5      State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	geninventorynumber   Name: Inventory number generation    Version: 2.6.0      State: Enabled
	addressing           Name: IP Adressing                   Version: 3.0.0      State: Enabled
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.0      State: Not installed
	useditemsexport      Name: Used items export              Version: 2.5.0      State: Enabled
	webresources         Name: Web Resources                  Version: 2.0.0      State: Enabled
	accounts             Name: Аккаунты                       Version: 3.0.1      State: Enabled
	webapplications      Name: Веб-приложений              Version: 4.0.0      State: Enabled
	datainjection        Name: Добавление данных        Version: 2.11.1     State: Enabled
	fields               Name: Дополнительные поля    Version: 1.15.1     State: Enabled
	additionalalerts     Name: Другие уведомления      Version: 2.4.0      State: Enabled
	positions            Name: Картография                   Version: 6.0.0      State: Enabled
	news                 Name: Оповещения                     Version: 1.10.3     State: Enabled
	mreporting           Name: Подробные отчеты          Version: 1.8.0      State: Enabled
	typology             Name: Типологий                      Version: 3.0.0      State: Enabled
	order                Name: Управление заказами    Version: 2.8.0      State: Enabled
	genericobject        Name: Управление объектами  Version: 2.12.0     State: Enabled
	tag                  Name: Управление тегами        Version: 2.9.0      State: Enabled

</pre></details>

**Comment by rean1mat0r** [comment]
During prolonged testing, studying the documentation and the structure of the database, at the moment it was discovered:
if there is an entry with the ID of the computer and device in the glpi_computers_items table, this device will appear in the connected list. However , at the same time: 

1.if the glpi_computers_items table has the value 0 in the is_dynamic field, and the value 1 in the is_deleted field, then the device cannot be connected back to the computer and it does not appear in the list of the "Locks" tab.

2.If the value is set to 0 in the "is_deleted" field, the device disappears from the "Locks" tab and returns to the "Connections" tab.

3. When the device is disconnected via the "Disconnect" button, the glpi_computers_items table is set to "1" in the "is_deleted" field by the system and the device is placed in the blocked list.

However, when trying to remove a device from the list of the "Locks" tab, the system does not set the value 0 in the is_deleted field

**Comment by trasher** [comment]
As far as I know, the lock mechanism works currently as expected; so the issue here is you cannot delete the lock on previously removed connection.

**Comment by rean1mat0r** [comment]
I turned on SQL query logging on my server and found that after trying to remove the device from the blocked list, a query got into the database
`UPDATE `glpi_computers_items` SET `is_deleted` = '1' WHERE `id` = '285436' `

If I understand correctly, then the problem is somewhere in the source code of the business logic. It seems to me that there, instead of is_deleted=0, is_deleted=1 is sent in the request.

If I'm right, I really ask you to tell me where I can find this request and correct it myself, so as not to wait for the release of the official bugfix, since my inventory information is gradually starting to collapse

**Comment by trasher** [comment]
Fixed, see #11647

**Comment by rean1mat0r** [comment]
Thank you very much for your work! 
The unlocking mechanism started working correctly.
