### ISSUE TITLE
Inventory with tag not association recursive

### ISSUE THREAD

**Issue by Claonilton** [glpi-project/glpi#11641]
### Bug reporting acknowledgment

Not applicable

### Professional support

Yes, I know

### Describe the bug

My inventory is working fine, but the TAG defined in glpi-agent1.2 is not assigned recursively.
Computer assigns ok
Printers do not assign.

Is resulting with my printers.
![image](https://user-images.githubusercontent.com/16517344/169409147-4a3f5bb2-27cc-4d8b-a10a-02a10a0440b7.png)

### To reproduce

1 - I created a new entity with TAG=example
2 - I installed the agent on a computer with a printer connected
3 - I waited for the sync
4 - I checked the result.

### Expected behavior

The printer was associated with TAG=example

### Operating system

Linux

### GLPI Agent version

1.2

### GLPI version

10.0.0

**Comment by Claonilton** [comment]
{
   "action": "inventory",
   "content": {
      "bios": {
         "bdate": "2011-02-09",
         "bmanufacturer": "American Megatrends Inc.",
         "bversion": "1.01.CCE",
         "mmodel": "HURONRIVER",
         "smanufacturer": "Standard",
         "smodel": "AHV"
      },
      "hardware": {
         "chassis_type": "Desktop",
         "memory": 16293,
         "name": "ESCRITORIO01",
         "uuid": "03000200-0400-0500-0006-000700080009",
         "vmsystem": "Physical",
         "winlang": "1046",
         "winowner": "usuario",
         "winprodid": "00331-10000-00001-AA020",
         "winprodkey": "W269N-WFGWX-YVC9B-4J6C9-T83GX",
         "workgroup": "WORKGROUP"
      },
      "printers": [
         {
            "driver": "Sweda Printer",
            "name": "Sweda Printer",
            "network": false,
            "port": "USB001",
            "printprocessor": "winprint",
            "resolution": "203x203",
            "serial": "SWEDA_PRINTER_SI-1508888-12340",
            "shared": false,
            "status": "Idle"
         },
         {
            "driver": "HP LaserJet Professional P1102w",
            "name": "PRN01 (HP LaserJet Professional P1102w)",
            "network": false,
            "port": "WSD-f2bcca01-64cd-4b4f-93e7-c0f58ad616d1",
            "printprocessor": "HP1100PrintProc",
            "shared": false,
            "status": "Idle"
         },
         {
            "driver": "Microsoft Print To PDF",
            "name": "Microsoft Print to PDF",
            "network": false,
            "port": "PORTPROMPT:",
            "printprocessor": "winprint",
            "resolution": "600x600",
            "shared": false,
            "status": "Idle"
         },
         {
            "comment": "Network Printer",
            "driver": "HP LaserJet Professional P1102w",
            "name": "HP LaserJet Professional P1102w",
            "network": false,
            "port": "IP_192.168.88.236",
            "printprocessor": "HP1100PrintProc",
            "shared": false,
            "status": "Idle"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.2"
   },
   "deviceid": "ESCRITORIO01-2022-05-20-06-31-39",
   "itemtype": "Computer",
   "tag": "14077528000173"
}

**Comment by g-bougard** [comment]
Thank you @Claonilton 
I imagine you have setup a rule in "Rules for assigning an item to an entity" and it works for the computer item type. Can you describe it ?

**Comment by Claonilton** [comment]
Perfectly. It has only worked for computer.
My rule: 

![image](https://user-images.githubusercontent.com/16517344/169510129-48e25cc1-b52b-498b-8c7a-e95855e2ff5e.png)

![image](https://user-images.githubusercontent.com/16517344/169510200-7b53a8d2-c5cd-4ddd-acda-6ca817f3a08f.png)


I realized that only the first printer was inventoried.

![image](https://user-images.githubusercontent.com/16517344/169509427-e78b1445-8516-4daf-92c9-7826298684c8.png)

![image](https://user-images.githubusercontent.com/16517344/169510432-a6f6e297-c03f-455d-afd2-916ae2a8aeb1.png)
