### ISSUE TITLE
[GLPI 10 Bugfixes] no tooltip for ticket actors

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#11643]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

In previous versions of GLPI we have a tooptip for each actors of tickets (on creation & update form)

![image](https://user-images.githubusercontent.com/13178158/169490804-042567f7-f188-434d-826f-0797b3901f81.png)

In GLPI 10 the tooltip has disappeared

![image](https://user-images.githubusercontent.com/13178158/169490643-bb48656e-3be5-4e1a-a0f3-c194c6ac575d.png)

**Comment by cconard96** [comment]
Confirmed. Although, I can't see anything that would have added these tooltips in 10.0 so it may just be a missing feature.
