### ISSUE TITLE
Request source is wrong for other admins

### ISSUE THREAD

**Issue by LuminousWing** [glpi-project/glpi#11658]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0

### Bug description

After upgrading to GLPI 10, the request source for other admins is set to a secondary value we sometimes use, but the primary should always standard be selected, the weird thing is that I do not have this issue.
The request source is set as standard for incident tickets, and the others are not.
I also checked root entity settings but everything seems fine, is this a bug or where can I fix this?

### Your GLPI setup information

Operating system: Windows NT W2016GLPI 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.1.5 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, readline, session,
	standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.7-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/sfzglpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.5) is supported.PHP version (8.1.5) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.7) is supported.Database engine version (10.6.7) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated. Write access to C:\inetpub\wwwroot\glpi/config has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated. Write access to C:\inetpub\wwwroot\glpi/files has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated.
Write access to C:\inetpub\wwwroot\glpi/config has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated.
Write access to C:\inetpub\wwwroot\glpi/files has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is not present.bz2 extension is not present.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

**Comment by cconard96** [comment]
The default value is set in Setup > General > Default Values while each user can override it in their user preferences.
There is no other place where this can be set.
