### ISSUE TITLE
error category

### ISSUE THREAD

**Issue by Frifeux** [glpi-project/glpi#11656]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0

### Bug description

I migrated my GLPI preproduction a few days ago and according to the ticket creation interface for users, they do not have access to ITIL categories. In simplified interface, no categories, on the other hand I have all my categories in standard interface.

Thanks for your help.

**Comment by cconard96** [comment]
Please test the latest nightly instead. There were many bugs in the 10.0.0 release which have been fixed including a few with the simplified interface ticket form.

https://nightly.glpi-project.org/glpi/
You would want the "10.0" nightly version.
