### ISSUE TITLE
Computer Alternate username no link to Username

### ISSUE THREAD

**Issue by StackAls** [glpi-project/glpi#11677]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

https://forum.glpi-project.org/viewtopic.php?id=283779

GLPI 10.0.0
Plugin GLPI Inventory - 1.0.0 (Marketplace)
GLPI Agent 1.2.0

I link and sync all my Active Directory users to GLPI.
My windows agents send to GLPI "Alternate username" as - user@domain.name and "User" normal linked
But my linux (Debian 10 and Debian 11) send to GLPI "Alternate username" as - domain.name\user - and "User" - not linked and blank.

I change sssd.conf and add "full_name_format = %1$s@%2$s" but this is not work for GLPI Agent.

If I enter to my Linux PC as: user@domain.name - all work. But It's not possible for me for other reasons.

### Steps To reproduce

1. Sync LDAP (AD) to GLPI
2. Install GLPI Agent to Debian Linux 10/11
3. Enter domain user to PC as: domain.name\user
4. Send Inventory data to GLPI
5. See to Computer - 
Alternate username = domain.name\user
User = blank

**Comment by g-bougard** [comment]
Hi @StackAls 
should still be fixed by #11655

**Comment by StackAls** [comment]
Where I run 
MariaDB [glpi]> update glpi_rulecriterias set pattern='/(.*)[,|\\/]/' where id=19;

MariaDB [glpi]> select * from glpi_rulecriterias where id=19;
+----+----------+----------+-----------+--------------+
| id | rules_id | criteria | condition | pattern      |
+----+----------+----------+-----------+--------------+
| 19 |       10 | contact  |         6 | /(.*)[,|\/]/ |
+----+----------+----------+-----------+--------------+
1 row in set (0.000 sec)

One backslash autoremoved.
The same - if I add rule from GLPI - Administration - Rules

**Comment by StackAls** [comment]
And If I run Test this rule from GLPI - Administration - Rules
example:
Alternate username    domain\username
but GLPI autoadd second backslach to field of page 
Alternate username  domain\\username
and test not pass.

For mariadb work this
update glpi_rulecriterias set pattern='/(.*)[,|\\\\/]/' where id=19;
MariaDB [glpi]> select * from glpi_rulecriterias where id=19;
+----+----------+----------+-----------+---------------+
| id | rules_id | criteria | condition | pattern       |
+----+----------+----------+-----------+---------------+
| 19 |       10 | contact  |         6 | /(.*)[,|\\/]/ |
+----+----------+----------+-----------+---------------+
1 row in set (0.000 sec)


But link Alternate username to User - not work
