### ISSUE TITLE
Incorrect display for personnal view in front/central when browser width > 1200px

### ISSUE THREAD

**Issue by philou511** [glpi-project/glpi#11688]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0

### Bug description

The tables of tickets (my tickets, observed tickets, group tickets, etc.) displays in width 100% in general, except when the browser width is over 1200px : then the width is 50% which makes the tables hard to read and a big wide white column on the right (which is not very useful...)

It probably comes from the "@media (min-width: 1200px)" in css_palettes_aerialgreen.min.css which forces the width to be "50%" instead of "100%"

### Page URL

front/central.php

**Comment by cconard96** [comment]
I cannot recreate the issue and none of the individual palettes have media queries. I am not able to find that media query anywhere in the `css` folder. The only place I found that is in the UI library we use (Tabler) but the selector that would force 50% width doesn't match anything on the page for me.

For me, the personal page looks OK from small screens all the way past 2000px and it goes from 1 column to 3 as needed.

**Comment by cconard96** [comment]
I can't recreate the issue with the latest 10.0 commit tested on Chrome 97. The personal view remains properly responsive from very small screens all the way up to ultra-wide (limited to 3 columns by the code).

It may have been fixed by #11696 or there is something else different between your instance and mine.

**Comment by ProBaert** [comment]
We got the same issue, i tested several Browser, they all got the same behavior.
Maybe its related to the update move from 9.7  to 10.

**Comment by cconard96** [comment]
When this issue happens can you press F12 to open the developer tools in your browser, go to the Console tab, type:
```javascript
window.msnry.layout();
```
Then, hit enter to try and force a re-layout of the grid.

Does this fix the issue?

**Comment by ProBaert** [comment]
Hi,

nope, i just get this message (testen in latest chrome & edge):
![image](https://user-images.githubusercontent.com/106799040/172306114-580bde0c-04a2-436c-8af2-21bb2885c6ab.png)

**Comment by cconard96** [comment]
So, the library used to display these items in a responsive grid doesn't seem to be loading at all.
Were there other warnings or errors in the console when you load the page/tab?

**Comment by tsmr** [comment]
![image](https://user-images.githubusercontent.com/13178158/172549852-7d0e4ae7-eeaa-4685-ad3f-03d54d648d4e.png)

linked to the commit : https://github.com/glpi-project/glpi/pull/11696/files

The display is ok if i revert it

**Comment by cconard96** [comment]
Does the PR work OK with this additional patch?

```diff
diff --git a/templates/components/masonry_grid.html.twig b/templates/components/masonry_grid.html.twig
index 57dfee6c05..91bc635252 100644
--- a/templates/components/masonry_grid.html.twig
+++ b/templates/components/masonry_grid.html.twig
@@ -48,17 +48,17 @@
 
 <script type="text/javascript">
 $(function() {
-   var msnry = new Masonry('#grid_{{ rand }}', {
+   window.msnry = new Masonry('#grid_{{ rand }}', {
       "percentPosition": true,
       "horizontalOrder": true,
    });
 
    $('#grid_{{ rand }}').on("layout:refresh", function() {
-      msnry.layout();
+       window.msnry.layout();
    });
 
    $(document).on('masonry_grid:layout', function() {
-       msnry.layout();
+       window.msnry.layout();
    })
 });
 </script>
```

**Comment by tsmr** [comment]
Yes for me it's ok

**Comment by ProBaert** [comment]
Hi, yes, now it works fine !

**Comment by philou511** [comment]
Sorry for my late confirmation, and thanks a lot : it works with the patch on both Firefox and Chrome (which were both concerned by the "bug").
