### ISSUE TITLE
Chamado não relaciona localização de item à regra.

### ISSUE THREAD

**Issue by carlosbayerl** [glpi-project/glpi#11681]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.7

### Bug description

Possuímos regras que tem como um dos Critérios, identificar uma particularidade quanto à localização do item. Atribuindo assim, o OLA específico para atendimento na localidade do item selecionado.
O fato é que a regra não está aplicando as atribuições conforme os Critérios adicionados na criação da mesma. Um detalhe importante, é que ao efetuarmos o Teste Motor de Pesquisa a regra "aponta" todos os ítens necessários ao seu funcionamento de forma correta.
Alugém pode me ajudar quanto à esse problema?

**Comment by cconard96** [comment]
Please write in English (automatic translations are OK).

Having issues reported all in English helps ensure that searching for existing/already reported issues is easier.
Also, the community and development team is international so having a common language helps us too.


Por favor, escreva em inglês (as traduções automáticas estão OK).

Ter problemas relatados em inglês ajuda a garantir que a pesquisa de problemas existentes/já relatados seja mais fácil.
Além disso, a comunidade e a equipe de desenvolvimento são internacionais, portanto, ter uma linguagem comum também nos ajuda.

**Comment by carlosbayerl** [comment]
New issue in #11683
