### ISSUE TITLE
Ticket editor - translation problem

### ISSUE THREAD

**Issue by k0xak** [glpi-project/glpi#11691]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Ticket - followupd editor.

Time info stays english no matter what language is being used for GUI.

![obrazek](https://user-images.githubusercontent.com/67418739/170270596-f935d3f9-7df8-4151-8f53-8516943c2136.png)

**Comment by trasher** [comment]
"no matter what language is being used" => I've just tested in French, everything is translated.

As far as I can see; those stirngs are just not translated in the pl_PL.po file, see for example https://www.transifex.com/glpi/GLPI/translate/#pl_PL/glpipot10/338070183?q=text%3ALists

**Comment by k0xak** [comment]
Screenshoted language is Czech.

So what do you recommend to resolve this issue?
If you tell me where to contribute - I will do it.

**Comment by trasher** [comment]
Unless a string is not marked as translatable in the source code; all translations are handled on transifex. You have to open an account on their platform, and translate missing strings in your language - for 10.0 version.
We retrieve all new translated strings before each release.
