### ISSUE TITLE
Bug in monitor search

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#1169]
Hello!
Search among monitors gives an error in cyrillic language:
http://prntscr.com/cvadog
but with numbers or/and english language it working fine:
http://prntscr.com/cvapm2

upd:
in clobal search, location where a monitros must be, doesnt exists too
http://prntscr.com/cvtsub
with next errors:
1 - http://prntscr.com/cvtuj6
2- http://prntscr.com/cvtuos
3- http://prntscr.com/cvtuzo

**Comment by orthagh** [comment]
Hello @Zegordo .

Sorry for the long delay of this answer.
Could you check that your glpi database and table have an ut8_unicode_ci collation ?

On my side, i can't replicate your issue.

**Comment by orthagh** [comment]
ok, i replicate:
- it's only on mysql server (not mariadb)
- the column which fail is date_mod

**Comment by Zegordo** [comment]
> Could you check that your glpi database and table have an ut8_unicode_ci collation ?

but I'm not sure, that it is what do you ask:
![image](https://cloud.githubusercontent.com/assets/16854682/20180307/0453079c-a76b-11e6-96c7-6eaca41178cb.png)

**Comment by orthagh** [comment]
Hello @Zegordo 

I try to address this issue in the pr #1279.
Could you test the provided [changes](https://github.com/glpi-project/glpi/pull/1279/files) ?
