### ISSUE TITLE
WARNING ON RESERVATION

### ISSUE THREAD

**Issue by waltherhuggo** [glpi-project/glpi#11694]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.0

### Bug description

When booking a device as shown below:
![image](https://user-images.githubusercontent.com/12068330/170336725-91defc38-7117-4677-a74e-837251ba0307.png)

When we go to the date and time selection screen, the following error is often presented:
Warning: Undefined array key "itemtype" in C:\xampp\htdocs\glpi10\src\Reservation.php on line 715

### Page URL

http://192.168.0.112/glpi10/front/reservation.form.php?item%5B1%5D=0&item%5B8%5D=0&item%5B8%5D=8&item%5B2%5D=0&item%5B3%5D=0&item%5B9%5D=0&item%5B4%5D=0&item%5B5%5D=0&item%5B7%5D=0&item%5B6%5D=0&begin=2022-05-25+15%3A00%3A00&end=2022-05-25+16%3A00%3A00&id=

### Steps To reproduce

-OPEN RESERVENTION WINDOW 
- SELECT THE SECOND DEVICE FROM THE LIST
- CLICK ON RESERVE
- ERROR HAS DISPLAYED ON THE TOP THE WINDOW

### Your GLPI setup information

 
Operating system: Windows NT GSDC01 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP 8.1.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.4 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.4 Server at 192.168.0.112
	Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.3.34-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi10
	Host info: localhost via TCP/IP
	
PHP version (8.1.4) is supported.PHP version (8.1.4) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.Database engine version (10.3.34) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi10/files/_cache has been validated. Write access to C:\xampp\htdocs\glpi10/config has been validated. Write access to C:\xampp\htdocs\glpi10/files/_cron has been validated. Write access to C:\xampp\htdocs\glpi10/files has been validated. Write access to C:\xampp\htdocs\glpi10/files/_dumps has been validated. Write access to C:\xampp\htdocs\glpi10/files/_graphs has been validated. Write access to C:\xampp\htdocs\glpi10/files/_lock has been validated. Write access to C:\xampp\htdocs\glpi10/files/_pictures has been validated. Write access to C:\xampp\htdocs\glpi10/files/_plugins has been validated. Write access to C:\xampp\htdocs\glpi10/files/_rss has been validated. Write access to C:\xampp\htdocs\glpi10/files/_sessions has been validated. Write access to C:\xampp\htdocs\glpi10/files/_tmp has been validated. Write access to C:\xampp\htdocs\glpi10/files/_uploads has been validated.Write access to C:\xampp\htdocs\glpi10/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi10/config has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi10/files has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi10/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi10/marketplace has been validated.Write access to C:\xampp\htdocs\glpi10/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

**Comment by steph461** [comment]
```shell
[2022-05-30 11:50:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "itemtype" in /var/www/html/glpi/src/Reservation.php at line 716
  Backtrace :
  front/reservation.form.php:188                     Reservation->showForm()
  
[2022-05-30 11:50:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "itemtype" in /var/www/html/glpi/src/Reservation.php at line 720
  Backtrace :
  front/reservation.form.php:188                     Reservation->showForm()
  
[2022-05-30 11:50:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "itemtype" in /var/www/html/glpi/src/Reservation.php at line 716
  Backtrace :
  front/reservation.form.php:188                     Reservation->showForm()
  
[2022-05-30 11:50:34] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "itemtype" in /var/www/html/glpi/src/Reservation.php at line 720
  Backtrace :
  front/reservation.form.php:188                     Reservation->showForm()
  
[2022-05-30 11:50:34] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getEntityID() on bool in /var/www/html/glpi/src/Reservation.php at line 744
  Backtrace :
  front/reservation.form.php:188                     Reservation->showForm()

when i click here
![image](https://user-images.githubusercontent.com/68054991/170967288-3f7159dc-1acf-413b-8f75-ccd9c1b3e63d.png)
