### ISSUE TITLE
GLPI 10.0.0 - variable timelineitems shown in email #11368

### ISSUE THREAD

**Issue by rudolcas** [glpi-project/glpi#11702]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Ticket shown like this:

![image](https://user-images.githubusercontent.com/42798291/170559222-81c9cb3a-7249-4002-bee3-806c984aa668.png)

**Comment by rudolcas** [comment]
From cconard

##################

Since fixing existing installations will be difficult, the issue can be manually corrected by following these steps:

Go to Setup > Notifications > Notification templates.
Find and open the "Tickets" template

Go to the Translations tab and select the "Default Translation"

In the "HTML body" field, select the "Source code" button in the toolbar. (If you do not see this button, please switch your rich text toolbar layout to classic instead of inline in your user preferences)

Select and replace the full source with:


<div>##IFticket.storestatus=5##</div>
<div>##lang.ticket.url## : <a href="##ticket.urlapprove##">##ticket.urlapprove##</a> <strong> </strong></div>
<div><strong>##lang.ticket.autoclosewarning##</strong></div>
<div><span style="color: #888888;"><strong><span style="text-decoration: underline;">##lang.ticket.solvedate##</span></strong></span> : ##ticket.solvedate##<br><span style="text-decoration: underline; color: #888888;"><strong>##lang.ticket.solution.type##</strong></span> : ##ticket.solution.type##<br><span style="text-decoration: underline; color: #888888;"><strong>##lang.ticket.solution.description##</strong></span> : ##ticket.solution.description## ##ENDIFticket.storestatus##</div>
<div>##ELSEticket.storestatus## ##lang.ticket.url## : <a href="##ticket.url##">##ticket.url##</a> ##ENDELSEticket.storestatus##</div>
<p class="description b"><strong>##lang.ticket.description##</strong></p>
<p><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.title##</span> :##ticket.title## <br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.authors##</span> :##IFticket.authors## ##ticket.authors## ##ENDIFticket.authors## ##ELSEticket.authors##--##ENDELSEticket.authors## <br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.creationdate##</span> :##ticket.creationdate## <br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.closedate##</span> :##ticket.closedate## <br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.requesttype##</span> :##ticket.requesttype##<br><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.item.name##</span> :</p>
<p>##FOREACHitems##</p>
<div class="description b">##IFticket.itemtype## ##ticket.itemtype## - ##ticket.item.name## ##IFticket.item.model## ##lang.ticket.item.model## : ##ticket.item.model## ##ENDIFticket.item.model## ##IFticket.item.serial## ##lang.ticket.item.serial## : ##ticket.item.serial## ##ENDIFticket.item.serial## ##IFticket.item.otherserial## ##lang.ticket.item.otherserial## : ##ticket.item.otherserial## ##ENDIFticket.item.otherserial## ##ENDIFticket.itemtype##</div>
<p> </p>
<p>##ENDFOREACHitems##</p>
<p>##IFticket.assigntousers## <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.assigntousers##</span> : ##ticket.assigntousers## ##ENDIFticket.assigntousers##<br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.ticket.status## </span> : ##ticket.status##<br>##IFticket.assigntogroups## <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.assigntogroups##</span> : ##ticket.assigntogroups## ##ENDIFticket.assigntogroups##<br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.urgency##</span> : ##ticket.urgency##<br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.impact##</span> : ##ticket.impact##<br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.priority##</span> : ##ticket.priority## <br>##IFticket.user.email##<span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.user.email##</span> : ##ticket.user.email ##ENDIFticket.user.email## <br>##IFticket.category##<span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.ticket.category## </span> :##ticket.category## ##ENDIFticket.category## ##ELSEticket.category## ##lang.ticket.nocategoryassigned## ##ENDELSEticket.category## <br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.ticket.content##</span> : ##ticket.content##</p>
<p> </p>
<p><br>##IFticket.storestatus=6##<br><span style="text-decoration: underline;"><strong><span style="color: #888888;">##lang.ticket.solvedate##</span></strong></span> : ##ticket.solvedate##<br><span style="color: #888888;"><strong><span style="text-decoration: underline;">##lang.ticket.solution.type##</span></strong></span> : ##ticket.solution.type##<br><span style="text-decoration: underline; color: #888888;"><strong>##lang.ticket.solution.description##</strong></span> : ##ticket.solution.description##<br>##ENDIFticket.storestatus##</p>
<p> </p>
<p>##FOREACHtimelineitems##</p>
<div class="description b"><br><strong> [##timelineitems.date##]</strong><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.author## </span> <span style="color: #000000; font-weight: bold; text-decoration: underline;">##timelineitems.author##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.description## </span> <span style="color: #000000; font-weight: bold; text-decoration: underline;">##timelineitems.description##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.date## </span> <span style="color: #000000; font-weight: bold; text-decoration: underline;">##timelineitems.date##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.position## </span><span style="color: #000000; font-weight: bold; text-decoration: underline;"> ##timelineitems.position##</span></div>
<div class="description b"><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.type## </span><span style="color: #000000; font-weight: bold; text-decoration: underline;"> ##timelineitems.type##</span></div>
<div class="description b"><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.typename## </span> <span style="color: #000000; font-weight: bold; text-decoration: underline;">##timelineitems.typename##</span></div>
<p>##ENDFOREACHtimelineitems##</p>
<div class="description b">##lang.ticket.numberoffollowups## : ##ticket.numberoffollowups##</div>
<div class="description b">##lang.ticket.numberoftasks## : ##ticket.numberoftasks##</div>


This works but....

**Comment by rudolcas** [comment]
This works but.... the answers* all come out to be "Underlined and Bold."  Please fix the code.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/42798291/170560215-28ffb5bd-54e4-4031-ae99-5f5e6b37742a.png">

**Comment by cedric-anne** [comment]
Hi,

You can edit yout template to remove bold and undeline.

**Comment by cedric-anne** [comment]
Duplicates #11368.
