### ISSUE TITLE
Domains plugin migrated to core error for GLPI 9.5

### ISSUE THREAD

**Issue by silenceroom** [glpi-project/glpi#11704]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5

### Bug description

Hi, 

From the GLPI Documents, it says that by running the migrate command you can convert the Domains into the GLPI Core table. 

However, under GLPI V9.5 the Domains plugin version is v2.2.1, and the migrate script returns an error that requires the plugin version to be v2.1.0. 

Error msg:
"You have to install Domains plugin files in version 2.1.0 to be able to continue."

**Comment by cedric-anne** [comment]
Hi,

Did you tried to run the command using the `--without-plugin` option ?
