### ISSUE TITLE
No user mentioned tag in notifications

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#11707]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

Hi,

i am not able to find tag for  user mentioned in the available notification tags.

**Comment by cedric-anne** [comment]
Hi,

This feature does not exist and is not in our roadmap for now. If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us

You can also propose a pull request to implement this feature, or discuss about it on https://suggest.glpi-project.org/.

Regards

**Comment by serviceticst** [comment]
try this

You have been mentioned in ticket ##ticket.id## - ##ticket.title##.

##FOREACH LAST 1 timelineitems##

Author: ##timelineitems.author##

Description: ##timelineitems.description##

##ENDFOREACHtimelineitems##

Click the button below for more information!

hyperlink
