### ISSUE TITLE
glpi  authentication don't run

### ISSUE THREAD

**Issue by SManuchehr** [glpi-project/glpi#11700]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

glpi  authentication don't run

**Comment by cconard96** [comment]
Please provide more information about the issue and include the requested log output (`files/_log/php-errors.log` and `files/_log/sql-errors.log`)and GLPI setup information (Setup > General > System tab).
