### ISSUE TITLE
avatar color background

### ISSUE THREAD

**Issue by DroidBV8** [glpi-project/glpi#11726]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0

### Bug description

The background color is green and is not transparent

**Comment by DroidBV8** [comment]
![GqMa1OYBBl](https://user-images.githubusercontent.com/71468154/171140337-a98e5557-9986-4a47-b5ec-55d8ad5753a1.png)

**Comment by cconard96** [comment]
It looks like the user picture has transparent corners and you are seeing the default avatar with initials behind it.
Both are loaded at the same time in case there is an issue loading the image.

There may be something that can be done to hide the default avatar once the image loads successfully.

**Comment by DroidBV8** [comment]
Thanks for the feedback. 
I confirm: the user avatar is a PNG file with transparent background.

And yes, the default avatar is loaded with the user avatar.
