### ISSUE TITLE
Templates are not working

### ISSUE THREAD

**Issue by nkzjfuentes** [glpi-project/glpi#11721]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10 (Latest)

### Bug description

GLPI templates are not showing any information.

It's a GLPI 10 (Latest) with a DB imported from GLPI 9.5.7.

![image](https://user-images.githubusercontent.com/101131681/171037491-312a8515-d03a-4d68-9842-36a8e91cc8b1.png)

### Relevant log output

# After debug the php-errors.log file returned the following when we create a new computer/device with any of the templates availables (Blank Template) as example.

glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function mb_ereg() in /var/www/glpi/src/DbUtils.php at line 1709
  Backtrace :
  inc/db.function.php:502                            DbUtils->autoName()
  :                                                  autoName()
  src/Application/View/Extension/PhpExtension.php:86 call_user_func_array()
  ...759d3a252aa3dc7bec0135f86c7a075f966fa64.php:312 Glpi\Application\View\Extension\PhpExtension->call()
  .../twig/twig/src/Extension/CoreExtension.php:1202 __TwigTemplate_c4196af2bd0cff6831335df0d5a1f2c7a51c0d2229eaf38bc9cd26913cfba7bf->macro_autoNameField()
  ...9e2fda2ae41ddb980a26ff6de5aa04871617713.php:169 twig_call_macro()
  vendor/twig/twig/src/Template.php:171              __TwigTemplate_c860d0206a4e4cb7e8a39ecfdc2e4e7b59a89b46f61f1778fe72927ba7974fca->block_form_fields()
  ...49e2fda2ae41ddb980a26ff6de5aa04871617713.php:95 Twig\Template->displayBlock()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_c860d0206a4e4cb7e8a39ecfdc2e4e7b59a89b46f61f1778fe72927ba7974fca->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:177      Twig\TemplateWrapper->display()
  src/CommonDBTM.php:486                             Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:655                             CommonDBTM->showForm()
  ajax/common.tabs.php:107                           CommonGLPI::displayStandardTab()

### Your GLPI setup information

It's a GLPI 10 (Latest) with a DB imported from GLPI 9.5.7. 
OS - CentOS 7.9.2009 (Core)
PHP 7.4.29
Mariadb Ver 15.1 Distrib 10.7.4-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by cconard96** [comment]
Please include the requested information from logs and the GLPI system information.

**Comment by nkzjfuentes** [comment]
> Please include the requested information from logs and the GLPI setup information.

@cconard96 I've included the php logs and also the setup information.
Thank you for your quick reply!
Kind regards.

**Comment by cconard96** [comment]
The setup information from Setup > General > System tab is what I meant. It contains a lot more information like which PHP extensions are enabled, what GLPI plugins you have of any, etc.

Based on the error message though, I guess you don't have the mbstring PHP extension installed or at least just not enabled in the web environment.

**Comment by trasher** [comment]
Indeed, this is a required extension missing issue; not a bug.

**Comment by cedric-anne** [comment]
`mbstring` extension is optional, so I consider it is a bug.

See #11723 for a fix.
