### ISSUE TITLE
GLPI 10 with bigger font sizes than previous versions

### ISSUE THREAD

**Issue by lfardin** [glpi-project/glpi#11730]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

CSS styles are defining bigger font is this new version, so, particularly on smaller screens, it's harder to see larger lists.

font size changed from 11px to 0.875rem (based on root font-size: 16px) - calculate to 14px

Suggestion to reduce root font-size to 14px or at least have an option to the user set its preferred font size.

**Comment by cconard96** [comment]
Having a higher base font size may be required for meeting accessibility guidelines.
For example:
WCAG 2.0 item 1.4.3 (Minimum Contrast) allows a lower contrast between text color and its background if it is large text (18pt normal or 14pt bold).
WCAG 2.0 item 2.5.5 (Target size) defines a minimum size for click/interact targets and the size of some elements are reliant on the text size.

If you would like to adjust this, you can utilize the UI Customization feature (UI Customization tab in Entity forms).
The following custom CSS would change the font size for almost everything:
```css
:root {
   --tblr-body-font-size: 14px;
}
```

There may be some cases where the font size of an element is set to a static value that will require additional custom CSS to fix.

**Comment by sebma** [comment]
> UI Customization

@cconard96 Hi, I cannot find the "Entity forms". Can you be more specific, where on the filesystem can I put this piece of CSS code ?

**Comment by RobertoMarcelino** [comment]
![image](https://user-images.githubusercontent.com/57845086/215282056-3888d134-766f-446d-98f6-65624f4e77c2.png)
