### ISSUE TITLE
GLPI Inventory not working

### ISSUE THREAD

**Issue by SManuchehr** [glpi-project/glpi#11739]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

[Wed Jun  1 11:58:08 2022][info] GLPI Agent exiting (5012)
[Wed Jun  1 11:58:37 2022][info] GLPI Agent service starting
[Wed Jun  1 11:58:37 2022][info] [http server] HTTPD service started on port 62354
[Wed Jun  1 11:58:39 2022][info] GLPI Agent memory usage: WSS=4030464 PFU=104636416
[Wed Jun  1 11:58:39 2022][info] target server0: next run: Wed Jun  1 12:38:11 2022 - http://server.url.com/front/inventory.php
[Wed Jun  1 12:00:24 2022][info] server0 is not ready yet, next server contact planned for Wed Jun  1 12:38:11 2022
[Wed Jun  1 12:00:52 2022][info] running task Deploy: storage maintenance event
[Wed Jun  1 12:00:54 2022][info] GLPI Agent memory usage: WSS=3248128 PFU=115175424

**Comment by SManuchehr** [comment]
Installing [GLPI-Agent-1.3-git2a4bc72e-x64.msi](https://nightly.glpi-project.org/glpi-agent/GLPI-Agent-1.3-git2a4bc72e-x64.msi)

**Comment by trasher** [comment]
I see nothing related to a GLPI issue here. It may be somathing in agent, or glpi or any plugin (since you do not provide requested information).
Feel free to reopen with all requested information, and a clear way to reproduce your issue.
