### ISSUE TITLE
After udpate 9.5.6 -> 10.0 - unable to add document in ticket SQL Error "1054"

### ISSUE THREAD

**Issue by ERFPP** [glpi-project/glpi#11733]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

### Bug description

I update GLPI 9.5.6 -> 10.0
In a ticket, if I want to add a document, i have a white rectangle with cross to close.
I enable the debug mode and i have this error:
SQL Error "1054": Unknown column 'is_notif_enable_default' in 'field list' in query "SELECT `id`, `entities_id`, `is_notif_enable_default` FROM `glpi_entities` WHERE `id` IN ('0')"

### Relevant log output

```shell
in glpi php-errors.log:
[2022-05-31 16:57:53] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: is_notif_enable_default in \glpi\src\Entity.php at line 2051
  Backtrace :
  src\Entity.php:471                                 Entity::showNotificationOptions()
  src\CommonGLPI.php:687                             Entity::displayTabContentForItem()
  ajax\common.tabs.php:107                           CommonGLPI::displayStandardTab()
```

### Page URL

tickets

### Steps To reproduce

windows server iis
glpi 10.0
php 7.4
mysql 8.0.18

### Your GLPI setup information

<html>
<body>

Operating system: Windows NT SRV-GLPI 10.0 build 17763 (Windows Server 2016) AMD64 PHP 7.4.28 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, readline, session, soap, sodium, standard, tokenizer, wincache, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="300" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Microsoft-IIS/10.0 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.53 Server Software: MySQL Community Server - GPL 	Server Version: 8.0.18 	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION 	Parameters: root@127.0.0.1/parc-v10 	Host info: 127.0.0.1 via TCP/IP 	 PHP version (7.4.28) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (8.0.18) is supported. The log file has been created successfully. Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated. Write access to C:\inetpub\wwwroot\glpi/config has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated. Write access to C:\inetpub\wwwroot\glpi/files has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated. Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.
--

GLPI_ROOT: C:\inetpub\wwwroot\glpi GLPI_CONFIG_DIR: C:\inetpub\wwwroot\glpi/config GLPI_VAR_DIR: C:\inetpub\wwwroot\glpi/files GLPI_MARKETPLACE_DIR: C:\inetpub\wwwroot\glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: C:\inetpub\wwwroot\glpi/files GLPI_CACHE_DIR: C:\inetpub\wwwroot\glpi/files/_cache GLPI_CRON_DIR: C:\inetpub\wwwroot\glpi/files/_cron GLPI_DUMP_DIR: C:\inetpub\wwwroot\glpi/files/_dumps GLPI_GRAPH_DIR: C:\inetpub\wwwroot\glpi/files/_graphs GLPI_LOCAL_I18N_DIR: C:\inetpub\wwwroot\glpi/files/_locales GLPI_LOCK_DIR: C:\inetpub\wwwroot\glpi/files/_lock GLPI_LOG_DIR: C:\inetpub\wwwroot\glpi/files/_log GLPI_PICTURE_DIR: C:\inetpub\wwwroot\glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: C:\inetpub\wwwroot\glpi/files/_plugins GLPI_RSS_DIR: C:\inetpub\wwwroot\glpi/files/_rss GLPI_SESSION_DIR: C:\inetpub\wwwroot\glpi/files/_sessions GLPI_TMP_DIR: C:\inetpub\wwwroot\glpi/files/_tmp GLPI_UPLOAD_DIR: C:\inetpub\wwwroot\glpi/files/_uploads GLPI_INVENTORY_DIR: C:\inetpub\wwwroot\glpi/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: C:\inetpub\wwwroot\glpi/locales GLPI_VERSION: 10.0.0 GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff GLPI_MARKETPLACE_PRERELEASES:  GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.2.0 GLPI_YEAR: 2022

</body>
</html>

**Comment by cconard96** [comment]
Please include a screenshot of the "white rectangle with cross to close".
The error posted doesn't seem related as it comes from the code that shows the Notification options in an Entity form, and not related to the Ticket display or Documents.

**Comment by ERFPP** [comment]
OK,
when i click on add a document in a ticket, i can't add document, it's just blank screen on the bottom:

![image](https://user-images.githubusercontent.com/67368034/171348101-2e7cedf0-1a2d-4f13-9594-dcf68589be8b.png)

![image](https://user-images.githubusercontent.com/67368034/171347575-01c22e67-5606-49d2-8199-dc3741b5f68a.png)

**Comment by trasher** [comment]
Try with latest nightly, this has been fixed.

**Comment by trasher** [comment]
And indeed, provided log is not related to declared issue
