### ISSUE TITLE
TAG inventory column always missing in 10.0.1 

### ISSUE THREAD

**Issue by lyonelf** [glpi-project/glpi#11742]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.1

### Bug description

In "parc, computer" there was 2 missing columns "version agent" and "tag inventory" in 10.0 

In 10.0.1 nighlty "version agent" in available but not "tag inventory". In place it's "number inventory" but it's not this one i'd like to add

**Comment by trasher** [comment]
Write in english only, as requested.
