### ISSUE TITLE
Assets with more than one owner or technical user/group.

### ISSUE THREAD

**Issue by alexmicontini** [glpi-project/glpi#11747]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Hi,

in the assets, a single user and a single group can be assigned as owner and as technicians in charge of the hardware. The fact that it only allows a single user or a single group is a limitation. For example, if I assign the owner of a computer to group X, and I want another group Y, whose members can only see its items, to be able to open tickects for that asset, it cannot choose it.

Greetings

### Your GLPI setup information

<html>
<body>

[code]   GLPI 9.5.7 ( => /var/www/html/glpi) Installation mode: TARBALL Current language:es_ES
--

Operating system: Linux CDGPLIpre 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at glpipre.nublo.grancanaria.com Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36 Server Software: Debian 10 	Server Version: 10.3.34-MariaDB-0+deb10u1 	Server SQL Mode:  	Parameters: glpi@172.29.21.193/glpi 	Host info: 172.29.21.193 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.34) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.7 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.6 in (/usr/share/php/CAS/source)

Server: '192.168.21.11', Port: '389', BaseDN: 'ou=usuarios,ou=cabildo,dc=cabildogcpre,dc=local', Connection filter: 		'(&(objectCategory=person)(objectClass=user)(userPrincipalName=*)(mail=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 		RootDN: 'cabildogcpre\userglpi', Use TLS: none

Not active

Way of sending emails: SMTP+SSL (serviciostic@smtps.grancanaria.com)

Name: 'serviciostic@grancanaria.com' Active: Yes 	Server: '{imaps.grancanaria.com:993/imap/ssl/validate-cert/notls}INBOX/SOPORTE' Login: 'serviciostic' Password: Yes Name: 'Correos Aula Virtual' Active: Yes 	Server: '{imaps.grancanaria.com:993/imap/ssl/validate-cert/notls}Aula Virtual' Login: 'serviciostic' Password: Yes

tag                  Name: Administración de etiquetas    Version: 2.8.3      State: Enabled 	news                 Name: Alertas                        Version: 1.9.1      State: Enabled 	impacts              Name: Asset impacts                  Version: 2.0.7      State: Enabled 	databases            Name: Bases de datos                 Version: 2.3.2      State: Enabled 	fields               Name: Campos adicionales             Version: 1.13.0     State: Enabled 	screenshot           Name: Captura de pantalla            Version: 1.1.6      State: Enabled 	cmdb                 Name: CMDB                           Version: 2.2.1      State: Enabled 	datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled 	archimap             Name: Diagrams                       Version: 3.2.7      State: Enabled 	addressing           Name: Direccionamiento IP            Version: 2.9.1      State: Enabled 	domains              Name: Dominios                       Version: 2.2.1      State: Enabled 	escalade             Name: Escalado                       Version: 2.7.2      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+4.1    State: Enabled 	genericobject        Name: Gestión de objetos             Version: 2.11.1     State: Enabled 	pdf                  Name: Impresión a pdf                Version: 2.0.0      State: Enabled 	reports              Name: Informes                       Version: 1.14.1     State: Enabled 	agile                Name: Kanban                         Version: 4.0.0      State: Installed / not activated 	tasklists            Name: Lista de tareas                Version: 1.6.2      State: Enabled 	mreporting           Name: Más Informes                   Version: 1.7.4      State: Enabled 	mydashboard          Name: Mi Dashboard                   Version: 1.8.3      State: Installed / not activated 	cvereporting         Name: Reporte CVE                    Version: 1.0.0      State: Installed / not activated 	dashboard            Name: Tablero de informes            Version: 1.0.2      State: Enabled
[/code]

</body>
</html>

**Comment by cconard96** [comment]
Feature requests can be made on the UserEcho page. We try to keep just bug reports in GitHub issues.
https://glpi.userecho.com/
