### ISSUE TITLE
No pictures of front/back hardware after migrate from 9.5.5 to 10.0.0

### ISSUE THREAD

**Issue by michalmoro** [glpi-project/glpi#11749]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0

### Bug description

After migration from version 9.5.5 I don't see front/back hardware pictures in racks.
Moreover, when I open any equipment model, I also have no pictures. For example, at the front/back picture, I only have X to remove. 
I tried remove additional slash from 5972 line in file/var/www/html/glpi/src/CommonDBTM.php but it not resolved a problem.

### Relevant log output

```shell
The picture '/var/www/html/glpi/files/_pictures//c1/61cf020e219956.068920436                                                                                                                                                                                        1cf0210c88c1.jpg' referenced by the PassiveDCEquipmentModel with ID 6 does not exist in /var/www/html/glpi/src/CommonDBTM.php on line 5972, referer: http://glpi.lan/front/p                                                                                                                                                                                        assivedcequipment.form.php?id=14
```

**Comment by michalmoro** [comment]
Sorry but I can't find this picture in old structure but when I use GLPI 9.5.5 I see this pictures on web site.

**Comment by michalmoro** [comment]
This is strange but I find picture files in path ..../files/_pictrures/c1/61cf020e219956.068920436.
I tried copy files to ..../files/_pictures/... but it still not working...

**Comment by trasher** [comment]
Not a glpi bug, I close
