### ISSUE TITLE
page load too slow on larger cartridges lists

### ISSUE THREAD

**Issue by lfardin** [glpi-project/glpi#11773]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

managing cartridges is too slow for long lists.

For instance, acessing the page /front/cartridgeitem.form.php to add new cartridges to a list with 291 itens, the quantity field at the top takes too long the show its options, so you can add more cartridges.

![image](https://user-images.githubusercontent.com/56692658/171399947-610be80e-d0ea-4ab9-b74f-371b1a2beb7c.png)

The used itens could be displayed at a different tab, ou at least have pagination, the improve performance.

### Steps To reproduce

Go to Assets -> Cartridges
Select a Cartridge model with a large number of itens (new and used)

**Comment by cconard96** [comment]
The main bottleneck here seems to be the creation of a dialog box for the Financial and Management Information for every cartridge rather than the SQL queries or even the loading of the dialog contents which should be done when the dialog actually gets opened.

In fact, In my test of just 100 cartridges, I saw a lot of CPU usage from the browser which makes sense if the dropdown isn't initializing for a long time since it gets converted to a select2 dropdown client-side.

While paginating this list may help as there would be less to make dialogs for, the bigger opportunity for performance gains would be by only creating the dialogs on demand instead of ahead of time.

**Comment by cconard96** [comment]
The pagination was done in #11781.
I'd like to keep this issue open until the other part can be looked at. It may be done as part of the JavaScript modularization work.

**Comment by cedrobert** [comment]
Hello,
I have this error that persists in version 10.0.5 of Glpi, I applied the change "#11781", but the cartridges page is still very slow to load and completely blocks the GLPI. Do you have any news on this problem?

**Comment by cconard96** [comment]
Hello,

What is your list size set for currently (number of items shown on each page of the list)?

**Comment by cedrobert** [comment]
Hello,

The size of the list is currently set to 10 items per page.

**Comment by cedrobert** [comment]
This is the query executed by GLPI:

SELECT DISTINCT `glpi_cartridgeitems`.`id` AS id, 'lolokai1' AS currentuser,                         `glpi_cartridgeitems`.`entities_id`, `glpi_cartridgeitems`.`is_recursive`,  `glpi_cartridgeitems`.`name` AS `ITEM_CartridgeItem_1`,                         `glpi_cartridgeitems`.`id` AS `ITEM_CartridgeItem_1_id`,                         `glpi_cartridgeitems`.`ref` AS `ITEM_CartridgeItem_34`,  `glpi_cartridgeitemtypes`.`name` AS `ITEM_CartridgeItem_4`,  `glpi_manufacturers`.`name` AS `ITEM_CartridgeItem_23`,  `glpi_cartridgeitems`.`alarm_threshold` AS `ITEM_CartridgeItem_8`,   COUNT(DISTINCT `glpi_cartridges_88263a7434fc6144f85e74f158142880`.`id`) AS `ITEM_CartridgeItem_19`,                      `glpi_cartridgeitems`.`alarm_threshold` AS `ITEM_CartridgeItem_9_alarm_threshold`, `glpi_cartridgeitems`.`comment` AS `ITEM_CartridgeItem_16`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`name`, '__NULL__'),                                                '$#$',`glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`id`) ORDER BY `glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`id` SEPARATOR '$$##$$')                               AS `ITEM_CartridgeItem_40`,                     GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_infocoms_136134d03015f26b64ce7600a1aedda5`.`use_date`, '__NULL__'),                                                '$#$',`glpi_infocoms_136134d03015f26b64ce7600a1aedda5`.`id`) ORDER BY `glpi_infocoms_136134d03015f26b64ce7600a1aedda5`.`id` SEPARATOR '$$##$$')                               AS `ITEM_CartridgeItem_38`,                     COUNT(DISTINCT `glpi_cartridges_fbf099cac78863b309d629d9737137ef`.`id`) AS `ITEM_CartridgeItem_17`,                       COUNT(DISTINCT `glpi_cartridges_3a1bfaeb0a6ab317f573339b5c25c067`.`id`) AS `ITEM_CartridgeItem_18` FROM `glpi_cartridgeitems`LEFT JOIN `glpi_cartridgeitemtypes`                                           ON (`glpi_cartridgeitems`.`cartridgeitemtypes_id` = `glpi_cartridgeitemtypes`.`id`                                               )LEFT JOIN `glpi_manufacturers`                                           ON (`glpi_cartridgeitems`.`manufacturers_id` = `glpi_manufacturers`.`id`                                               ) LEFT JOIN `glpi_cartridges`  AS `glpi_cartridges_88263a7434fc6144f85e74f158142880`                                              ON (`glpi_cartridgeitems`.`id` = `glpi_cartridges_88263a7434fc6144f85e74f158142880`.`cartridgeitems_id`                                                   AND `glpi_cartridges_88263a7434fc6144f85e74f158142880`.`date_use` IS NULL AND `glpi_cartridges_88263a7434fc6144f85e74f158142880`.`date_out` IS NULL ) LEFT JOIN `glpi_cartridgeitems_printermodels`                                              ON (`glpi_cartridgeitems`.`id` = `glpi_cartridgeitems_printermodels`.`cartridgeitems_id`                                                  )LEFT JOIN `glpi_printermodels`  AS `glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`                                           ON (`glpi_cartridgeitems_printermodels`.`printermodels_id` = `glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`id`                                               ) LEFT JOIN `glpi_cartridges`                                              ON (`glpi_cartridgeitems`.`id` = `glpi_cartridges`.`cartridgeitems_id`                                                  ) LEFT JOIN `glpi_infocoms`  AS `glpi_infocoms_136134d03015f26b64ce7600a1aedda5`                                           ON (`glpi_cartridges`.`id` = `glpi_infocoms_136134d03015f26b64ce7600a1aedda5`.`items_id`                                               AND `glpi_infocoms_136134d03015f26b64ce7600a1aedda5`.`itemtype` = 'Cartridge'                                               )  LEFT JOIN `glpi_cartridges`  AS `glpi_cartridges_fbf099cac78863b309d629d9737137ef`                                              ON (`glpi_cartridgeitems`.`id` = `glpi_cartridges_fbf099cac78863b309d629d9737137ef`.`cartridgeitems_id`                                                   AND  NOT (`glpi_cartridges_fbf099cac78863b309d629d9737137ef`.`date_use` IS NULL) AND `glpi_cartridges_fbf099cac78863b309d629d9737137ef`.`date_out` IS NULL ) LEFT JOIN `glpi_cartridges`  AS `glpi_cartridges_3a1bfaeb0a6ab317f573339b5c25c067`                                              ON (`glpi_cartridgeitems`.`id` = `glpi_cartridges_3a1bfaeb0a6ab317f573339b5c25c067`.`cartridgeitems_id`                                                   AND  NOT (`glpi_cartridges_3a1bfaeb0a6ab317f573339b5c25c067`.`date_out` IS NULL) ) WHERE  `glpi_cartridgeitems`.`is_deleted` = 0  GROUP BY `glpi_cartridgeitems`.`id` ORDER BY `ITEM_CartridgeItem_1` ASC  LIMIT 0, 10;

This seems to be in error : 
GROUP_CONCAT(
    DISTINCT CONCAT(
        IFNULL(`glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`name`, '__NULL__'),
        '$#$',`glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`id`) 
    ORDER BY `glpi_printermodels_8e0de9a00e9168f37bed9f68c18656a5`.`id` SEPARATOR '$$##$$') 

but I don't understand this part of the SQL.

**Comment by lolokai** [comment]
Up

**Comment by cedric-anne** [comment]
Fixed by #16292.
