### ISSUE TITLE
Network ports issues

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1178]
It looks like we've got a huge issue regarding network ports since 9.1 release.

**Comment by trasher** [comment]
@ddurieux I've assigned this to you, since you already fix some parts of the original issues, and I know you've another bunch of fixes on the road :)

**Comment by Armin83** [comment]
@trasher 
Should i update from 0.90.3 too 9.1 with this problem ?
What is Huge Network issues ? 
Does the problem only matter on import ?

**Comment by trasher** [comment]
@Armin83 honestly... I cannot say. Bug has appear on the fusioninventory plugin unit tests side; and I do not know much, I've not worked on this.

As far as I know, if something is broken on GLPi side right now, it should have been in the 0.90.5 also (and maybe older releases as well).
