### ISSUE TITLE
Can't add a new simcard in child entity

### ISSUE THREAD

**Issue by victoria1984** [glpi-project/glpi#11787]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.3

### Bug description

If being in a child entity I try to add a new sim card, it is generated in the root even though I am placed in the child entity.

### Steps To reproduce

1. in the entities tree, i selct a child entity.
2. go to Assets > Simcard
3. Add a new simcard
4. this sim card link with root entity

**Comment by trasher** [comment]
9.5.3 is quite outdated. Try with at least 9.5.7, or better 10.0.

**Comment by victoria1984** [comment]
Now, i can't update this versión, Please, help me to add a new simcard.
