### ISSUE TITLE
CalDAV authorizations

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#11785]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v9.5.7

### Bug description

When creating a new external event in the planning, Thunderbird can retrieve it wih CalDAV protocol.
But when creating it in Thunderbird, GLPI can't retrieve it (403 error from CalDAV).
However, the sync works in both ways with my personal account and with a local account. It does not work with all other accounts, even if they are SuperAdmin and I don't understand why.

### Relevant log output

```shell
https://zupimages.net/up/22/22/706l.png
```

### Steps To reproduce

1. Create a GLPI user
2. Add a task in its planning
3. Configure Thunderbird to retrieve the calendar with CalDAV protocol
4. Create an event in Thunderbird
5. See that it is not retrieved by GLPI

**Comment by cedric-anne** [comment]
It may be due to the fact that CalDAV endpoint in GLPI is using the default user profile. See #8657 for more details.

**Comment by paidge** [comment]
Maybe the caldav endpoin should check all profiles of the user
