### ISSUE TITLE
GLPI 10.0 native inventory do not inject switch information

### ISSUE THREAD

**Issue by walday** [glpi-project/glpi#11786]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Collect glpi-netinventory from switch not injected to GLPI 10

### Relevant log output

```shell
-----php-error.log---
[2022-06-02 05:14:22] glpiphplog.WARNING:   *** PHP Warning (2): Undefined property: stdClass::$ipaddress in /var/www/html/glpi/src/Inventory/Asset/InventoryNetworkPort.php at line 408
4491   Backtrace :
4492   src/Inventory/Asset/InventoryNetworkPort.php:115   Glpi\Inventory\Asset\NetworkPort->handleUpdates()
4493   src/Inventory/Asset/NetworkPort.php:670            Glpi\Inventory\Asset\NetworkPort->handlePortsTrait()
4494   src/Inventory/Asset/NetworkPort.php:504            Glpi\Inventory\Asset\NetworkPort->handlePorts()
4495   src/Inventory/Asset/MainAsset.php:772              Glpi\Inventory\Asset\NetworkPort->handle()
4496   src/Inventory/Asset/MainAsset.php:693              Glpi\Inventory\Asset\MainAsset->handleAssets()
4497   src/Inventory/Asset/NetworkEquipment.php:218       Glpi\Inventory\Asset\MainAsset->rulepassed()
4498   src/RuleImportAsset.php:939                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
4499   src/Rule.php:1505                                  RuleImportAsset->executeActions()
4500   src/RuleCollection.php:1589                        Rule->process()
4501   src/Inventory/Asset/MainAsset.php:519              RuleCollection->processAllRules()
4502   src/Inventory/Inventory.php:678                    Glpi\Inventory\Asset\MainAsset->handle()
4503   src/Inventory/Inventory.php:316                    Glpi\Inventory\Inventory->handleItem()
4504   src/Inventory/Request.php:364                      Glpi\Inventory\Inventory->doInventory()
4505   src/Inventory/Request.php:288                      Glpi\Inventory\Request->inventory()
4506   src/Inventory/Request.php:257                      Glpi\Inventory\Request->network()
4507   src/Inventory/Request.php:96                       Glpi\Inventory\Request->networkInventory()
4508   src/Agent/Communication/AbstractRequest.php:296    Glpi\Inventory\Request->handleAction()
4509   src/Agent/Communication/AbstractRequest.php:233    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
4510   front/inventory.php:83                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
4511
4512 [2022-06-02 05:14:22] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /var/www/html/glpi/src/Inventory/Asset/InventoryNetworkPort.php at line 409
4513   Backtrace :
4514   src/Inventory/Asset/InventoryNetworkPort.php:409   count()
4515   src/Inventory/Asset/InventoryNetworkPort.php:115   Glpi\Inventory\Asset\NetworkPort->handleUpdates()
4516   src/Inventory/Asset/NetworkPort.php:670            Glpi\Inventory\Asset\NetworkPort->handlePortsTrait()
4517   src/Inventory/Asset/NetworkPort.php:504            Glpi\Inventory\Asset\NetworkPort->handlePorts()
4518   src/Inventory/Asset/MainAsset.php:772              Glpi\Inventory\Asset\NetworkPort->handle()
4519   src/Inventory/Asset/MainAsset.php:693              Glpi\Inventory\Asset\MainAsset->handleAssets()
4520   src/Inventory/Asset/NetworkEquipment.php:218       Glpi\Inventory\Asset\MainAsset->rulepassed()
4521   src/RuleImportAsset.php:939                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
4522   src/Rule.php:1505                                  RuleImportAsset->executeActions()
4523   src/RuleCollection.php:1589                        Rule->process()
4524   src/Inventory/Asset/MainAsset.php:519              RuleCollection->processAllRules()
4525   src/Inventory/Inventory.php:678                    Glpi\Inventory\Asset\MainAsset->handle()
4526   src/Inventory/Inventory.php:316                    Glpi\Inventory\Inventory->handleItem()
4527   src/Inventory/Request.php:364                      Glpi\Inventory\Inventory->doInventory()
4528   src/Inventory/Request.php:288                      Glpi\Inventory\Request->inventory()
4529   src/Inventory/Request.php:257                      Glpi\Inventory\Request->network()
4530   src/Inventory/Request.php:96                       Glpi\Inventory\Request->networkInventory()
4531   src/Agent/Communication/AbstractRequest.php:296    Glpi\Inventory\Request->handleAction()
4532   src/Agent/Communication/AbstractRequest.php:233    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
4533   front/inventory.php:83                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
```

### Steps To reproduce

1)from cli collect data to sw1.ocs:
root@glpi:/home# glpi-netinventory --host 192.168.15.98 --credentials version:2c,community:public > /tmp/sw1.ocs
[sw1.txt](https://github.com/glpi-project/glpi/files/8821963/sw1.txt)

2)from cli inject file to server
root@glpi:/home# glpi-injector -R -f /tmp/sw1.ocs --debug -u http://glpi.server/glpi/front/inventory.php
Loading /tmp/sw1.ocs...[DE72EB24] ERROR: Unexpected empty server response
DEBUG:
These elements were not sent:
/tmp/sw1.ocs
root@glpi:/var/www/html/glpi/files/_inventories#

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022 x86_64
PHP 8.0.17 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, snmp, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.sab-ekb.ru Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Server Software: Ubuntu 20.04
	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.0.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
mpdf/mpdf in (/var/www/html/glpi/vendor/mpdf/mpdf/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	archimap             Name: Diagrams                       Version: 3.2.6      State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	addressing           Name: IP Adressing                   Version: 3.0.0      State: Not installed
	mreporting           Name: More Reporting                 Version: 1.8.0      State: Enabled
	releases             Name: Releases                       Version: 2.0.0      State: Enabled
	tasklists            Name: Список задач                  Version: 2.0.1      State: Enabled
	printercounters      Name: Счетчики принтера        Version: 2.0.0      State: Not installed
	genericobject        Name: Управление объектами  Version: 2.12.0     State: Enabled

</pre></details>

**Comment by trasher** [comment]
duplicates #11362
