### ISSUE TITLE
Interface Error after Update

### ISSUE THREAD

**Issue by hmassot** [glpi-project/glpi#11798]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Hi,
After I upgraded my server with PHP 7.4 (all fine in GLPI), I started the migration to 10.0.1.
At the end of the migration, my interface does not look good ... =/
Do you have any idea ?
Thanks
![image](https://user-images.githubusercontent.com/106779560/171744689-dfddec41-0f7b-4f80-842c-929b395d0ea0.png)

**Comment by cconard96** [comment]
Please clear the browser cache and see if that corrects the issue.

**Comment by hmassot** [comment]
Hi,
Sorry for the delay.
I restarted the migration but I have troubles with it.
I start from the following setup :
- Ubuntu 18.04
- GLPI 9.5.7
- PHP 7.2
- MariaDB 10.14

After apt update && upgrade I have the following setup :
- GLPI 9.5.7
- PHP 8.1
- MariaDB 10.14

Then I unzip GLPI 10.0.1.tgz in my glpi folder and start the GLPI 10 setup.

At the end I have still the same issue...

Do you have any advice that could help me ?

I tried a new installation from the beginning and it works fine =)

Thanks if you have any idea

**Comment by cedric-anne** [comment]
Maybe there is a conflict with old GLPI files. Only some directories must be kept during update, see https://glpi-install.readthedocs.io/en/latest/update.html

**Comment by hmassot** [comment]
Thanks.
I think there is a php error in my installation =/
I'll try to do it when I'll have some time...

**Comment by hmassot** [comment]
Thanks for you link. I'll try with backuping these files

**Comment by trasher** [comment]
This does not seems to be a glpi bug, I close
