### ISSUE TITLE
Unable to create a new project task from the Global Kanban

### ISSUE THREAD

**Issue by pvasener** [glpi-project/glpi#11802]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.1

### Bug description

When I try to create a new Project Task from the Global Kanban, the 'Add' button has no effect.

![image](https://user-images.githubusercontent.com/1736726/171828328-ea3427a3-d4a4-4900-8657-62f54a8b1ff0.png)

In addition, the project dropdown list doesn't properly display (at the top left-hand corner of the site instead of in-place) and I get multiple Javascript errors:

![image](https://user-images.githubusercontent.com/1736726/171828509-f1046c5e-032e-46eb-89e8-c72c675a9c22.png)

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.1 ( => /var/www/html/glpi/test)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux VM-GLPI 5.4.0-113-generic #127-Ubuntu SMP Wed May 18 14:30:56 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at helpdesk-test.aup.edu Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.29-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi_test
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.29) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/test/files/_cache has been validated.
Write access to /var/www/html/glpi/test/config has been validated.
Write access to /var/www/html/glpi/test/files/_cron has been validated.
Write access to /var/www/html/glpi/test/files has been validated.
Write access to /var/www/html/glpi/test/files/_dumps has been validated.
Write access to /var/www/html/glpi/test/files/_graphs has been validated.
Write access to /var/www/html/glpi/test/files/_lock has been validated.
Write access to /var/www/html/glpi/test/files/_pictures has been validated.
Write access to /var/www/html/glpi/test/files/_plugins has been validated.
Write access to /var/www/html/glpi/test/files/_rss has been validated.
Write access to /var/www/html/glpi/test/files/_sessions has been validated.
Write access to /var/www/html/glpi/test/files/_tmp has been validated.
Write access to /var/www/html/glpi/test/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/test/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi/test
GLPI_CONFIG_DIR: /var/www/html/glpi/test/config
GLPI_VAR_DIR: /var/www/html/glpi/test/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/test/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/test/files
GLPI_CACHE_DIR: /var/www/html/glpi/test/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/test/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/test/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/test/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/test/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/test/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/test/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/test/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/test/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/test/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/test/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/test/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/test/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/test/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/test/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/test/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/test/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/test/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/test/marketplace/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/test/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/test/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/test/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/test/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/test/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/test/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/test/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/test/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/test/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/test/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/test/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/test/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/test/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/test/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/test/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/test/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/test/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/test/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/test/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/test/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/test/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/test/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/test/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/test/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/test/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/test/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/test/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/test/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/test/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/test/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/test/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/test/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/test/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/test/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/test/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/test/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/test/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/test/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'aup.local', Port: '389', BaseDN: 'OU=AUPUsers,DC=aup,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'ldap', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (helpdesk@aup.edu@smtp.office365.com)

</details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.2      State: Enabled
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled
	behaviors            Name: Behaviours                     Version: 2.6.0      State: Enabled
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 10.0.0+1.0 State: Enabled
	gantt                Name: gantt                          Version: 1.0.0      State: Enabled
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.0      State: Installed / not activated
	metademands          Name: Meta-Demands                   Version: 3.0.1      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.8.0      State: Enabled
	satisfaction         Name: More satisfaction              Version: 1.6.0      State: Enabled
	mydashboard          Name: My Dashboard                   Version: 2.0.3      State: Enabled
	order                Name: Orders management              Version: 2.9.0      State: Enabled
	additionalalerts     Name: Others alerts                  Version: 2.4.0      State: Enabled
	pdf                  Name: Print to pdf                   Version: 2.1        State: Enabled
	purchaserequest      Name: Purchase request               Version: 3.0.0      State: Enabled
	reports              Name: Reports                        Version: 2.0.0      State: Enabled
	screenshot           Name: Screenshot                     Version: 2.0.0      State: Enabled
	servicecatalog       Name: Service catalog                Version: 2.0.0      State: Installed / not activated
	manufacturersimports Name: Suppliers imports              Version: 3.0.1      State: Enabled
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.0   State: Enabled
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled

</pre></details>

**Comment by cconard96** [comment]
Project tasks must be added to a project (The project selection is blank in your screenshot).
Do you have a non-finished project in your GLPI already? A non-finished project is any that don't have a status that have the "Is finished" option enabled like Closed does.

Also, please provide the requested GLPI setup information and browser version.

**Comment by pvasener** [comment]
It was empty in the screenshot due to the Javascript error mentioned. However, I managed to select a project at initial load of the page but the Add button remains inactive:

![image](https://user-images.githubusercontent.com/1736726/171847400-03b639d6-2f99-4438-a5e9-08f816ba9bfa.png)

**Comment by cconard96** [comment]
If you create a task with a Project that is "finished", the task does get created (at least on my end it does).
In the global kanban, there is a built-in filter that hides the tasks of finished projects to reduce clutter. There should probably be better feedback in that case since the form doesn't automatically close.

**Comment by cconard96** [comment]
I recreated the other issue. A workaround is to close the form and re-open it.
The form remained open to make it quicker to add multiple items but I don't think this issue occurred in 9.5.
It doesn't make sense that it is an error from the qtip library either since it isn't used here.

**Comment by cconard96** [comment]
The reported issues have been fixed. The main issue with the add item form was merged for version 10.0.2. The change in behavior to hide finished projects from the dropdown when adding tasks was done for 10.1.0.
