### ISSUE TITLE
Can't add a follow-up to an existing ticket

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#11819]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

We have only just upgraded to GLPI 10.0.1 from 9.5.7.
We don't seem to be able to create follow-ups in tickets any more. Has something changed in how follow-ups are handled?

If we look at our old tickets, we can see all the historic follow-ups, but no apparent way to create more?

We assume it should appear here:
![image](https://user-images.githubusercontent.com/16598973/172071811-6b994331-532c-4a9b-aafb-ee9b501917a5.png)

### Steps To reproduce

Go into any ticket and attempt to look for a 'followup' button

### Your GLPI setup information

GLPI 10.0.1 ( => /var/www/helpdesk.hayley-group.local)
Installation mode: TARBALL
Current language:en_GB

**Comment by cconard96** [comment]
"Answer" is the new label for adding followups.
The main button is the first action that your user has permission to do from this list:
1. Followup
2. Task
3. Solution
4. Document
5. Validation

If your user didn't have access to add a followup, the button would change to say "Create a task" instead.

**Comment by hgpit** [comment]
Haha! Thank you very much :)
