### ISSUE TITLE
Copying the location from the requester characters other than numbers 

### ISSUE THREAD

**Issue by hubMich** [glpi-project/glpi#11823]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

Copying the location from the requester characters other than numbers not working.

Exaplme:
User1 Location 1111 - copy correct
User2 Location 1111-1123 - not copy

**Comment by cconard96** [comment]
Please provide steps to recreate the issue along with the requested log output (if any exists in files/_log/php-errors.log or files/_log/sql-errors.log) and GLPI setup information.

**Comment by trasher** [comment]
No feedback, closing
