### ISSUE TITLE
Searches with "items seen -> not contains" do not work

### ISSUE THREAD

**Issue by jackburton79** [glpi-project/glpi#11833]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7 / 10.0.1

### Bug description

In any context, when searching with "items seen -> not contains" does not work.
"Items seen -> contains" works correctly.

items seen -> contains -> cosmo:
![image](https://user-images.githubusercontent.com/3501519/172358375-658f5844-3a9b-46c1-a780-0a4971ef6d7c.png)

items seen -> not contains -> cosmo:
![image](https://user-images.githubusercontent.com/3501519/172358494-959a0e71-fae0-4489-9f59-964b51f86357.png)

Happens with both glpi 9.5.7 and 10.0.1.

### Steps To reproduce

1. Go to Assets-> Computers (or any other asset)
2. Search with items seen" -> not contains -> "something"
3. It should show only items which do not contain "something". It shows every item.

### Your GLPI setup information

<html>
<body>

[code]   GLPI 9.5.7 ( => /usr/local/share/glpi) Installation mode: TARBALL Current language:en_GB
--

Operating system: Linux group 5.3.18-150300.59.68-default #1 SMP Wed May 4 11:29:09 UTC 2022 (ea30951) x86_64 PHP 7.4.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, ctype, 	curl, date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, memcached, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="101M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33 Server Software: MariaDB package 	Server Version: 10.5.15-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.5.15) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /usr/local/share/glpi/files/_cache has been validated. Write access to /usr/local/share/glpi/config has been validated. Write access to /usr/local/share/glpi/files/_cron has been validated. Write access to /usr/local/share/glpi/files has been validated. Write access to /usr/local/share/glpi/files/_dumps has been validated. Write access to /usr/local/share/glpi/files/_graphs has been validated. Write access to /usr/local/share/glpi/files/_lock has been validated. Write access to /usr/local/share/glpi/files/_pictures has been validated. Write access to /usr/local/share/glpi/files/_plugins has been validated. Write access to /usr/local/share/glpi/files/_rss has been validated. Write access to /usr/local/share/glpi/files/_sessions has been validated. Write access to /usr/local/share/glpi/files/_tmp has been validated. Write access to /usr/local/share/glpi/files/_uploads has been validated. Write access to /usr/local/share/glpi/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /usr/local/share/glpi GLPI_CONFIG_DIR: /usr/local/share/glpi/config GLPI_VAR_DIR: /usr/local/share/glpi/files GLPI_MARKETPLACE_DIR: /usr/local/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /usr/local/share/glpi/files GLPI_CACHE_DIR: /usr/local/share/glpi/files/_cache GLPI_CRON_DIR: /usr/local/share/glpi/files/_cron GLPI_DUMP_DIR: /usr/local/share/glpi/files/_dumps GLPI_GRAPH_DIR: /usr/local/share/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /usr/local/share/glpi/files/_locales GLPI_LOCK_DIR: /usr/local/share/glpi/files/_lock GLPI_LOG_DIR: /usr/local/share/glpi/files/_log GLPI_PICTURE_DIR: /usr/local/share/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /usr/local/share/glpi/files/_plugins GLPI_RSS_DIR: /usr/local/share/glpi/files/_rss GLPI_SESSION_DIR: /usr/local/share/glpi/files/_sessions GLPI_TMP_DIR: /usr/local/share/glpi/files/_tmp GLPI_UPLOAD_DIR: /usr/local/share/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/local/share/glpi/locales GLPI_VERSION: 9.5.7 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/usr/local/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/usr/local/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/usr/local/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/usr/local/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/local/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/local/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/local/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/local/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/local/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/local/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/local/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/usr/local/share/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/usr/local/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/usr/local/share/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/usr/local/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/local/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/local/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/local/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/local/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/local/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/local/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/local/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/local/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/local/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/local/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/local/share/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/usr/local/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/local/share/glpi/marketplace/oauthimap/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/local/share/glpi/marketplace/oauthimap/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/usr/local/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/local/share/glpi/vendor/paragonie/sodium_compat/src)

Server: 'ldaps://uddc1.iacpud.local', Port: '636', BaseDN: 'OU=AterUsers,DC=IACPUD,DC=LOCAL', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'LDAPSearchUser', Use 		TLS: none Server: 'dc1.ater.pn.it', Port: '389', BaseDN: 'ou=Servizio di Direzione,ou=Company Users,dc=ATER,dc=PN,dc=IT', Connection 		filter: '(objectClass=user)', RootDN: 'LDAPSearchUser', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (assistenza@smtp.iacpud.local)

Name: 'assistenza365' Active: Yes 	Server: '{outlook.office365.com:993/imap/ssl/novalidate-cert/notls}' Login: 'assistenza@ater-udine.it' Password: Yes

accounts             Name: Accounts                       Version: 2.6.0      State: Enabled 	additionalalerts     Name: Altre notifiche                Version: 2.3.0      State: Enabled 	barcode              Name: Barcode                        Version: 2.6.2      State: Enabled 	printercounters      Name: Contatori della stampante      Version: 1.7.0      State: Enabled 	datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled 	databases            Name: Databases                      Version: 2.3.2      State: Enabled 	room                 Name: Locali                         Version: 3.1.3      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.7.4      State: Enabled 	oauthimap            Name: Oauth IMAP                     Version: 1.3.3      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.4      State: Enabled 	reports              Name: Report                         Version: 1.14.1     State: Enabled 	screenshot           Name: Screenshot                     Version: 1.1.6      State: Enabled 	pdf                  Name: Stampa in PDF                  Version: 2.0.0      State: Enabled 	ticketcleaner        Name: Ticket Cleaner                 Version: 3.0.0      State: Enabled 	treeview             Name: Visualizzazione struttura      Version: 1.9.1      State: Enabled 	webapplications      Name: Web applications               Version: 3.0.0      State: Enabled

Host: localhostConnection: OkUse the OCSNG software dictionary: No
[/code]

</body>
</html>

**Comment by cconard96** [comment]
Same as #9604.

Indeed, the way that the "not contains" search works is not very obvious. The query it generates matches everything as long as the term doesn't exist in every shown column.
The search that provides the results that users more often want, is "NOT Items Seen contains cosmo".
