### ISSUE TITLE
GLPI 10.0.1 not display closed ticket

### ISSUE THREAD

**Issue by mulbzh** [glpi-project/glpi#11835]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Hello,

When i want to display in criteria only closed ticket, there is no results.

**Comment by cconard96** [comment]
Please provide more information about the issue including the exact search criteria being used.

Please also check the GLPI logs for relevant entries (files/_log/php-errors.log and files/_log/sql-errors.log) and provide the GLPI setup information (Setup > General > System tab).

**Comment by cconard96** [comment]
@giovanny07 Please open a new issue for this with the attached logs since we don't have enough information to confirm that it is the exact same issue as the original poster.
