### ISSUE TITLE
Booking calendar does not appear complete

### ISSUE THREAD

**Issue by waltherhuggo** [glpi-project/glpi#11838]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0.0

### Bug description

Booking calendar does not appear complete, when we click on the button: "View calendar for all items". In previous versions, all reservations made by all users were shown, after the update it is not being shown nor the reservations made by the user himself.

Super-User (GLPI):
![image](https://user-images.githubusercontent.com/12068330/172426304-e953b6e5-33e5-4014-b850-1e73c871c8e0.png)

Common user (self-service):
![image](https://user-images.githubusercontent.com/12068330/172427689-ce9db981-1c17-4bb5-b587-1449189e80d3.png)

### Page URL

/glpi/front/reservation.php?reservationitems_id=0

### Steps To reproduce

make a reservation for any item,
open the booking calendar for all items,
the reservation you made does not appear

**Comment by cedric-anne** [comment]
Hi,

Can you check if problem persist on GLPI 10.0.1 ? We made some fixes on reservation feature recently.

**Comment by waltherhuggo** [comment]
Could you please send me the download link? I haven't done this update yet.

**Comment by waltherhuggo** [comment]
Even after the update I can't see the existing reservations. With a common user.

![image](https://user-images.githubusercontent.com/12068330/173121049-5989ee6f-c16f-4d09-8cab-3f0d7ace07dd.png)

![image](https://user-images.githubusercontent.com/12068330/173121063-e26aab9c-24ea-4bdc-b1b3-3f6c5ba1fbc0.png)

![image](https://user-images.githubusercontent.com/12068330/173121108-02de50d1-013c-428b-bdbb-c92828476f92.png)
