### ISSUE TITLE
Different SMTP for entities

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#1186]
Is it possible to configure separate SMTP servers for different entities?
Or maybe separate SMTP credentials for each entity with one SMTP server?

**Comment by hartois** [comment]
I cannot find this feature in glpi and I solve the problem with next patch (perhaps someone he is useful):
```
Index: inc/glpimailer.class.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- inc/glpimailer.class.php    (date 1476545828000)
+++ inc/glpimailer.class.php    (revision )
@@ -89,4 +89,20 @@
       }
    }
 
+   public function smtpSend($header, $body)
+   {
+      $customCfgFile = '../config/smtp_custom.php';
+      $customCfg = (file_exists($customCfgFile)) ? require $customCfgFile : false;
+
+      if(
+          is_array($customCfg)
+          && !empty($customCfg[$this->From])
+          && is_array($customCfg[$this->From])
+      ){
+         foreach($customCfg[$this->From] as $param => $value)
+            $this->$param = $value;
+      }
+      return parent::smtpSend($header, $body);
+   }
+
 }
```

**Comment by EmilBelas2015** [comment]
I try this patch but not working for me. If I understand well it will check a header and if 'helpdesk2@maidomain.com' is contained in a header from than user smtp_custom.php right? Is there way how to debug this PHP?

**Comment by hartois** [comment]
if From field from mail message exists in smtp_custom, than use overrided config from smtp_custom
