### ISSUE TITLE
Pas de notifications envoyés par le collecteur GLPI et pas de création automatique des tickets

### ISSUE THREAD

**Issue by nphearly** [glpi-project/glpi#11877]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

Bonjour,
je viens de migrer mon GLPI en version 10.0.0.
J'ai installé le plugin OAUTH pour mon collecteur de mail qui utilise un compte office365.
Le plugin a été bien  installé  mais j'ai les problèmes ci-dessous:
1/ le collecteur fonctionne mais ne recuperent pas tout seul (automatiquement) le mail, je dois aller cliquer manuellement dans le collecteur sur le bouton "Récuperer les courriels maintenant" . j'ai bien vérifier mes actions automatiques Mailgate fonctionne correctement
2/ Lorsque les tickets sont créés, GLPI n'envoie aucune notification

### Relevant log output

```shell
Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot connect to host; error = stream_socket_client(): Unable to connect to ssl://outlook.office365.com:993 (Unknown error) (errno = 0 ) in /usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol/ProtocolTrait.php at line 100
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.0 (/glpi => /usr/share/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux BLCSRV19025.BRALICO.LOCAL 4.9.0-18-amd64 #1 SMP Debian 4.9.303-1 (2022-03-07) x86_64
PHP 8.1.6 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, readline, session, shmop,
	soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at blcsrv19025.bralico.local Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36 Edg/102.0.1245.33
Server Software: mariadb.org binary distribution
	Server Version: 10.3.34-MariaDB-1:10.3.34+maria~stretch
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: admin@10.242.10.25/glpi
	Host info: 10.242.10.25 via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.
The log file has been created successfully.
Write access to /usr/share/glpi/files/_cache has been validated.
Write access to /usr/share/glpi/config has been validated.
Write access to /usr/share/glpi/files/_cron has been validated.
Write access to /usr/share/glpi/files has been validated.
Write access to /usr/share/glpi/files/_dumps has been validated.
Write access to /usr/share/glpi/files/_graphs has been validated.
Write access to /usr/share/glpi/files/_lock has been validated.
Write access to /usr/share/glpi/files/_pictures has been validated.
Write access to /usr/share/glpi/files/_plugins has been validated.
Write access to /usr/share/glpi/files/_rss has been validated.
Write access to /usr/share/glpi/files/_sessions has been validated.
Write access to /usr/share/glpi/files/_tmp has been validated.
Write access to /usr/share/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi
GLPI_CONFIG_DIR: /usr/share/glpi/config
GLPI_VAR_DIR: /usr/share/glpi/files
GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /usr/share/glpi/files
GLPI_CACHE_DIR: /usr/share/glpi/files/_cache
GLPI_CRON_DIR: /usr/share/glpi/files/_cron
GLPI_DUMP_DIR: /usr/share/glpi/files/_dumps
GLPI_GRAPH_DIR: /usr/share/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /usr/share/glpi/files/_locales
GLPI_LOCK_DIR: /usr/share/glpi/files/_lock
GLPI_LOG_DIR: /usr/share/glpi/files/_log
GLPI_PICTURE_DIR: /usr/share/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /usr/share/glpi/files/_plugins
GLPI_RSS_DIR: /usr/share/glpi/files/_rss
GLPI_SESSION_DIR: /usr/share/glpi/files/_sessions
GLPI_TMP_DIR: /usr/share/glpi/files/_tmp
GLPI_UPLOAD_DIR: /usr/share/glpi/files/_uploads
GLPI_INVENTORY_DIR: /usr/share/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/locales
GLPI_VERSION: 10.0.0
GLPI_SCHEMA_VERSION: 10.0.0@9eb698d8fd49f9256d7bd63a6d747587e0effaff
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
</pre></details>

**Comment by SteadEXE** [comment]
Est-ce que les tâches dans Actions Automatiques sont bien activées ? 
Sont-elles en mode d'exécution CLI ou GLPI ?

GLPI recommande d'activer ces tâches en mode CLI.
Ensuite si tu es sous linux il faut un cron qui appel la page front/cron.php à interval régulier, par exemple toutes les minutes.
Sous Windows, il faut faire une tâche dans le planificateur de tâche.

Je pose ces questions car je ne sais pas si cela vient d'un problème de tâche ou de connexion, désolé si je me trompe

Il y a la doc ici si tu as besoin de plus d'infos : 
https://wiki.glpi-project.org/doku.php?id=fr:config:crontab

Sais-tu me dire si les actions automatiques ont tournées ? 
Tu peux le voir dans l'historique de chaque tâche.

Les tâches sont mailgate (récup de mail) et queuednotification (envoit des notifications).

J'espère que cela t'aide.
Pense à ouvrir ton ticket en anglais la prochaine fois tu auras sans doutes plus de réponses ;)

**Comment by trasher** [comment]
In **english** only please.
