### ISSUE TITLE
Closed tickets have no details

### ISSUE THREAD

**Issue by tomSDL** [glpi-project/glpi#11876]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When closing a ticket the details disappear from view. Any follow-ups, solutions, tasks etc. disappear. Reopening the ticket makes them appear again. 

Edge and chrome have the same issues. 

![image](https://user-images.githubusercontent.com/32687810/173078981-4f93840d-e45b-472f-a3a5-19fe9de230c3.png)

### Page URL

https://helpdesk/glpi/front/ticket.form.php?

### Steps To reproduce

Close ticket
Info gone
Open ticket 
Info back

### Your GLPI setup information

Debian 10

**Comment by cconard96** [comment]
Please provide the requested log output.
Specifically, entries from `files/_log/php-errors.log` and `files/_log/sql-errors.log` from around the time you tried viewing a closed ticket.

**Comment by tomSDL** [comment]
php-errors.log

This appears when I open a closed ticket

[2022-06-10 16:12:25] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: array_merge(): Argument #2 must be of type array, null given in /var/www/html/glpi/src/CommonITILObject.php at line 69                                        32
  Backtrace :
  src/CommonITILObject.php:6932                      array_merge()
  src/Ticket.php:4387                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:657                             Ticket->showForm()
  ajax/common.tabs.php:111                           CommonGLPI::displayStandardTab()

I then disabled the newly released updated onetimesecret plugin I installed a few days again and now the dispay is fine again.

**Comment by cconard96** [comment]
Fixed via #11880
