### ISSUE TITLE
GLPI 10.0.1 and display

### ISSUE THREAD

**Issue by mulbzh** [glpi-project/glpi#11885]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

hello,
when i am in a ticket, the email signature imported in GLPI is display like that (below) :
It was not like that before in GLPI 9.5. The email signature is just a table

![image](https://user-images.githubusercontent.com/18529258/173298646-c0f90eba-bd13-46bf-b717-d9b6bd9da1c0.png)

When i edit the task or the follow, the display is different an better
![image](https://user-images.githubusercontent.com/18529258/173298941-7ace9ccb-dc9b-4e06-ad59-179826da0690.png)

**Comment by cedric-anne** [comment]
Hi,

Can you test #11800 ?

**Comment by mulbzh** [comment]
it is that the change to do ? : https://github.com/glpi-project/glpi/commit/069cd4d28204bb76d2c4792dcca721fdd8c791d4

**Comment by cedric-anne** [comment]
> it is that the change to do ? : [069cd4d](https://github.com/glpi-project/glpi/commit/069cd4d28204bb76d2c4792dcca721fdd8c791d4)

Yes
