### ISSUE TITLE
Add info of version in API

### ISSUE THREAD

**Issue by edgardmessias** [glpi-project/glpi#1188]
This ensures to the client that the necessary functions are available in future updates of GLPI

For Example: Calling the `apirest.php/version`, return:

``` json
{
  "glpi": "9.1.0",
  "api": "1.0.0",
  "plugins": {
    "mailanalyzer": "1.2.4"
  }
}
```

**Comment by edgardmessias** [comment]
It would be interesting to implement the status, like in `status.php`

**Comment by trasher** [comment]
@remicollet gives me recently a link about API versionning; that I do not yet have time to read completely...

https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/

Adding an API version is something to be discussed; as for other versions, :+1: for me.

**Comment by ajsb85** [comment]
Hi @edgardmessias 

At the moment some versions are present in the `/Config` endpoint.

Salut.
