### ISSUE TITLE
10.0.0 to 10.0.1 Migration Issues

### ISSUE THREAD

**Issue by qaOYR** [glpi-project/glpi#11881]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When performing the upgrade from 10.0.0 to 10.0.1, the following message appears:

Rename "Computer_SoftwareLicense" itemtype to "Item_SoftwareLicense"
Rename "Computer_SoftwareVersion" itemtype to "Item_SoftwareVersion"

It is not clear at all where one is supposed to do the renaming, directly on the database, perhaps.

I have an inkling that the issue is one of bad semantics in the installer and that GLPI actually wants to convey that those items **have been renamed.**

This [migration script](https://github.com/glpi-project/glpi/blob/aecc75a5d8fc83e79f6e16fa9b1c020b398232a5/install/migrations/update_10.0.0_to_10.0.1/rename_itemtypes.php) seems to suggest as much.

Can anyone please confirm whether this is a non-issue and if it is **please correct the expression from "Rename" to "Renamed"** in the installer to make sure that it is clear that the migration has indeed succeeded.

### Relevant log output

```shell
Rename "Computer_SoftwareLicense" itemtype to "Item_SoftwareLicense"
Rename "Computer_SoftwareVersion" itemtype to "Item_SoftwareVersion"
```

### Steps To reproduce

1. Migrate GLPi 10.0.0 to GLPi 10.0.1
2. The warning/error above is displayed.

### Your GLPI setup information

PHP 7.4.29 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube Loader, json, ldap, libxml, mailparse,
	mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, session, soap, sockets, sodium, sqlite3,
	ssh2, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, uploadprogress, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="3000" memory_limit="256M" post_max_size="150M" safe_mode="" session.save_handler="files"
	upload_max_filesize="150M" 
Software: Apache/2.4.53 (Unix) OpenSSL/1.0.2k-fips ()
	Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0
Server Software: MariaDB Server
	Server Version: 10.2.44-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Host info: Localhost via UNIX socket

**Comment by gvarela89** [comment]
instale GLPI10 y el agente arroja el siguiente error.
[Sat Jun 11 15:58:23 2022][info] sending prolog request to server0
[Sat Jun 11 15:58:23 2022][error] [http client] communication error: 403 Forbidden
[Sat Jun 11 15:58:23 2022][error] No answer from server at https://computersystem.cl/support/front/inventory.php
[Sat Jun 11 15:58:23 2022][info] target server0: next run: Sat Jun 11 16:00:23 2022 - https://computersystem.cl/support/front/inventory.php
[Sat Jun 11 15:58:23 2022][info] GLPI Agent memory usage: WSS=3620864 PFU=114458624

**Comment by qaOYR** [comment]
@gvarela89 - Please _do not hijack this bug_ report to write about a random installation issue that you are experiencing.

If you need help to complete your installation, please write in the community forum. 

**Bug reports are about specific issues.**

**Comment by SteadEXE** [comment]
I had this message too, I guess you are right, I tried to review my ACLs, nothing seems to be missing

**Comment by trasher** [comment]
Thi smessage appears when GLPI is doing the migration, so ythis is correct, and not an error.

**Comment by qaOYR** [comment]
> Thi smessage appears when GLPI is doing the migration, so ythis is correct, and not an error.

My point is that the message is wrong. It should be changed from "Rename" to "Renamed".

Otherwise, I am left with the impression that I must perform some maintenance work after installation. I spent considerable time trying to make sense of something that is easily fixable for this or any other migration script. 

If it has done said migration for you, it should say "Renamed". 

This may seem like a small issue, but I am sure I am not the only one who was left under the impression that the migration was not successful and required manual intervention.

**Comment by cedric-anne** [comment]
#11886 fixes these ambiguous strings.
