### ISSUE TITLE
Broken Graphics after update from 10.0.0 to 10.0.1

### ISSUE THREAD

**Issue by LukeZS** [glpi-project/glpi#11897]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Broken Graphics after update from 10.0.0 to 10.0.1 as shown here:

https://drive.google.com/file/d/1dLdZsObDBqF5QsJekhfzEABqTFlTmPad/view

**Comment by steph461** [comment]
https://github.com/glpi-project/glpi/issues/11888

**Comment by trasher** [comment]
Duplicates #11888; this is fixed in nightly builds
