### ISSUE TITLE
Ticket locking not working after upgrade from 9.5.7 to 10.0.2

### ISSUE THREAD

**Issue by jdeagles** [glpi-project/glpi#11896]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1, not 10.0.2 like I originally stated!

### Bug description

When we interact with tickets, we have noticed that ticket locking is no longer taking place. We have checked global and user settings, and everything appears to be set correctly still.  No records are being generated in the glpi_objectlocks table.

This has the effect that our team have clashed when attempting to resolve tickets.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.1 ( => C:\inetpub\glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT SERVICEDESK01 10.0 build 20348 (Windows Server 2016) AMD64
PHP 8.0.17 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, sockets, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.3-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: usp@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.0.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.3) is supported.
The log file has been created successfully.
Write access to C:\inetpub\glpi/files/_cache has been validated.
Write access to C:\inetpub\glpi/config has been validated.
Write access to C:\inetpub\glpi/files/_cron has been validated.
Write access to C:\inetpub\glpi/files has been validated.
Write access to C:\inetpub\glpi/files/_dumps has been validated.
Write access to C:\inetpub\glpi/files/_graphs has been validated.
Write access to C:\inetpub\glpi/files/_lock has been validated.
Write access to C:\inetpub\glpi/files/_pictures has been validated.
Write access to C:\inetpub\glpi/files/_plugins has been validated.
Write access to C:\inetpub\glpi/files/_rss has been validated.
Write access to C:\inetpub\glpi/files/_sessions has been validated.
Write access to C:\inetpub\glpi/files/_tmp has been validated.
Write access to C:\inetpub\glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\inetpub\glpi
GLPI_CONFIG_DIR: C:\inetpub\glpi/config
GLPI_VAR_DIR: C:\inetpub\glpi/files
GLPI_MARKETPLACE_DIR: C:\inetpub\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\inetpub\glpi/files
GLPI_CACHE_DIR: C:\inetpub\glpi/files/_cache
GLPI_CRON_DIR: C:\inetpub\glpi/files/_cron
GLPI_DUMP_DIR: C:\inetpub\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\inetpub\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\inetpub\glpi/files/_locales
GLPI_LOCK_DIR: C:\inetpub\glpi/files/_lock
GLPI_LOG_DIR: C:\inetpub\glpi/files/_log
GLPI_PICTURE_DIR: C:\inetpub\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\inetpub\glpi/files/_plugins
GLPI_RSS_DIR: C:\inetpub\glpi/files/_rss
GLPI_SESSION_DIR: C:\inetpub\glpi/files/_sessions
GLPI_TMP_DIR: C:\inetpub\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\inetpub\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\inetpub\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\inetpub\glpi/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\inetpub\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\inetpub\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\inetpub\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\glpi\vendor\psr\cache\src)
league/csv in (C:\inetpub\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\glpi\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\inetpub\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\inetpub\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (C:\inetpub\glpi\vendor\symfony\polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'lifs03.curtins.com', Port: '389', BaseDN: 'ou=sites,dc=curtins,dc=com', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'cn=Hardware Access
		Account,cn=Users,dc=curtins,dc=com', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@cumailrelay01.curtins.com)

</details><details><summary>Plugins list</summary><pre> 
	dashboard            Name: Dashboard                      Version: 0.9.6      State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.5+4.0    State: Installed / not activated
	simcard              Name: Sim cards management           Version: 1.4.2      State: Installed / not activated

</pre></details>

**Comment by cedric-anne** [comment]
I confirm the bug.

**Comment by jdeagles** [comment]
Sorry, I put the wrong version number above, it should be 10.0.1

**Comment by Jyru-Ken** [comment]
I confirm the bug too. Present in all 10.x versions.

**Comment by cconard96** [comment]
Hello, can you test the changes made in #12524?

**Comment by Jyru-Ken** [comment]
Hello
I test it but the lock don't work as expected.
When I open a ticket, sometimes the lock will work, sometimes nothing happens.

I can't find why.

**Comment by Jyru-Ken** [comment]
Hello
Did you see my previous message ? The lock don't work the same way it worked in 9.x version.

**Comment by Jyru-Ken** [comment]
Hello

I upgraded from 10.0.2 to 10.0.3 and this bug is still alive. Please could you see [this message](https://forum.glpi-project.org/viewtopic.php?id=282077) if your a french user ? 

I don't know what to do to avoid this problem, and i'm ready to give you all informations you need about it.

Best regards.

Jyru-Ken.

**Comment by cedric-anne** [comment]
![image](https://user-images.githubusercontent.com/33253653/196627608-7a85fcd7-38ba-4d83-9fcb-99279bb1558d.png)

**Comment by Jyru-Ken** [comment]
> ![image](https://user-images.githubusercontent.com/33253653/196627608-7a85fcd7-38ba-4d83-9fcb-99279bb1558d.png)

As I said in the forum, i can't even have this screenshot in my config after upgrade 9.57 to 10.0.x

Have you got an idea what's going on ?

**Comment by Jyru-Ken** [comment]
Hello
I deleted an old plugin no longer in use for us (Additionals Fields) and all gone right now with the lock system. But we've got now the same screenshot with the code (insert....) and the style goes wrong.
Any Idea ?

**Comment by cedric-anne** [comment]
Hi,

Could you test #13047 ?

**Comment by Jyru-Ken** [comment]
> Hi,
> 
> Could you test #13047 ?

It works like a charm. Thanks for your help. Best regards.
