### ISSUE TITLE
[GLPI 10.0.1-RC2] Delete a document from the ticket shows you ticket creation form without deleting anything

### ISSUE THREAD

**Issue by lfpiaggio1** [glpi-project/glpi#11890]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When click on delete image, it redirect to new form ticket and doesn't delete anything.

![image](https://user-images.githubusercontent.com/107441443/173455787-232b724f-ae52-4887-aaf3-9300ddc903ea.png)

### Page URL

/front/ticket.form.php?delete_document&documents_id=1547&tickets_id=1316

### Steps To reproduce

Click delete picture
It redirect to new form ticket

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.1 ( => /var/www/html/vtech)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux aws-glpi 5.11.0-1021-aws #22~20.04.2-Ubuntu SMP Wed Oct 27 21:27:13 UTC 2021 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.27-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi-admin@localhost/glpi_vtech
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.27) is supported.
The log file has been created successfully.
Write access to /var/www/html/vtech/files/_cache has been validated.
Write access to /var/www/html/vtech/config has been validated.
Write access to /var/www/html/vtech/files/_cron has been validated.
Write access to /var/www/html/vtech/files has been validated.
Write access to /var/www/html/vtech/files/_dumps has been validated.
Write access to /var/www/html/vtech/files/_graphs has been validated.
Write access to /var/www/html/vtech/files/_lock has been validated.
Write access to /var/www/html/vtech/files/_pictures has been validated.
Write access to /var/www/html/vtech/files/_plugins has been validated.
Write access to /var/www/html/vtech/files/_rss has been validated.
Write access to /var/www/html/vtech/files/_sessions has been validated.
Write access to /var/www/html/vtech/files/_tmp has been validated.
Write access to /var/www/html/vtech/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/vtech/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/vtech
GLPI_CONFIG_DIR: /var/www/html/vtech/config
GLPI_VAR_DIR: /var/www/html/vtech/files
GLPI_MARKETPLACE_DIR: /var/www/html/vtech/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/vtech/files
GLPI_CACHE_DIR: /var/www/html/vtech/files/_cache
GLPI_CRON_DIR: /var/www/html/vtech/files/_cron
GLPI_DUMP_DIR: /var/www/html/vtech/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/vtech/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/vtech/files/_locales
GLPI_LOCK_DIR: /var/www/html/vtech/files/_lock
GLPI_LOG_DIR: /var/www/html/vtech/files/_log
GLPI_PICTURE_DIR: /var/www/html/vtech/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/vtech/files/_plugins
GLPI_RSS_DIR: /var/www/html/vtech/files/_rss
GLPI_SESSION_DIR: /var/www/html/vtech/files/_sessions
GLPI_TMP_DIR: /var/www/html/vtech/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/vtech/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/vtech/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/vtech/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/vtech/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/vtech/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/vtech/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/vtech/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vtech/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vtech/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/vtech/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/vtech/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/vtech/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/vtech/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/vtech/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/vtech/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/vtech/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/vtech/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/vtech/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/vtech/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/vtech/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/vtech/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/vtech/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/vtech/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/vtech/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/vtech/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/vtech/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/vtech/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/vtech/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/vtech/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/vtech/vendor/psr/cache/src)
league/csv in (/var/www/html/vtech/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/vtech/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/vtech/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/vtech/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/vtech/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/vtech/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/vtech/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/vtech/vendor/symfony/cache)
html2text/html2text in (/var/www/html/vtech/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/vtech/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/vtech/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/vtech/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/vtech/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/vtech/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/vtech/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (suporte@vtechti.com.br@smtp.gmail.com)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Campos adicionais              Version: 1.15.3     State: Enabled
	gantt                Name: gantt                          Version: 1.0.0      State: Enabled
	webresources         Name: Web Resources                  Version: 2.0.2      State: Installed / not activated

</pre></details>

**Comment by cconard96** [comment]
Please provide the requested log output.
Specifically, entries from `files/_log/php-errors.log` and `files/_log/sql-errors.log` from around the time you experienced the issue.
