### ISSUE TITLE
Migration to utf8mb4 is not working with plugin_genericobject

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#11901]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

After Running php bin/console glpi:migration:utf8mb4 i got some errormessages:
```
SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_ASDFtypes` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
```

### Relevant log output

```shell
unsuitable
```

### Page URL

unsuitable

### Steps To reproduce

unsuitable

### Your GLPI setup information

unsuitable

### Anything else?

unsuitable

**Comment by trasher** [comment]
This is related to a plugin, please open an issue on the right repository.

**Comment by vollkommenIrrelevant** [comment]
@trasher 
Where is the bugtracker for this repository?

**Comment by vollkommenIrrelevant** [comment]
great....

Sulution is here: [https://github.com/glpi-project/glpi/issues/11902#issuecomment-1158621077](https://github.com/glpi-project/glpi/issues/11902#issuecomment-1158621077)

> I don't know.
