### ISSUE TITLE
Miration of unsigned_keys is not working

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#11902]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

After Running php bin/console glpi:migration:unsigned_keys i got some errormessages:

`SQL Error "1292": Incorrect date value: '0000-00-00' for column 'date_install' at row 2700 in query "ALTER TABLE `glpi_items_softwareversions` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_items_softwareversions.id" ist mit der Meldung "(1292) Incorrect date value: '0000-00-00' for column 'date_install' at row 2700" fehlgeschlagen.

  649/1612 [===========>----------------]  40%SQL Error "1292": Incorrect date value: '0000-00-00' for column 'date_install' at row 2700 in query "ALTER TABLE `glpi_items_softwareversions` MODIFY COLUMN `items_id` int unsigned NOT NULL DEFAULT '0' "
Die Migration der Spalte "glpi_items_softwareversions.items_id" ist mit der Meldung "(1292) Incorrect date value: '0000-00-00' for column 'date_install' at row 2700" fehlgeschlagen.

  650/1612 [===========>----------------]  40%SQL Error "1292": Incorrect date value: '0000-00-00' for column 'date_install' at row 2700 in query "ALTER TABLE `glpi_items_softwareversions` MODIFY COLUMN `softwareversions_id` int unsigned NOT NULL DEFAULT '0' "
Die Migration der Spalte "glpi_items_softwareversions.softwareversions_id" ist mit der Meldung "(1292) Incorrect date value: '0000-00-00' for column 'date_install' at row 2700" fehlgeschlagen.

  651/1612 [===========>----------------]  40%SQL Error "1292": Incorrect date value: '0000-00-00' for column 'date_install' at row 2700 in query "ALTER TABLE `glpi_items_softwareversions` MODIFY COLUMN `entities_id` int unsigned NOT NULL DEFAULT '0' "
Die Migration der Spalte "glpi_items_softwareversions.entities_id" ist mit der Meldung "(1292) Incorrect date value: '0000-00-00' for column 'date_install' at row 2700" fehlgeschlagen.

 1138/1612 [===================>--------]  70%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_kassenmonitoretypes` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_kassenmonitoretypes.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1140/1612 [===================>--------]  70%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_kassenpcmodels` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_kassenpcmodels.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1188/1612 [====================>-------]  73%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_mytypekassendruckermodells` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_mytypekassendruckermodells.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1193/1612 [====================>-------]  74%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_mytypekassenmonitormodells` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"

Die Migration der Spalte "glpi_plugin_genericobject_mytypekassenmonitormodells.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1195/1612 [====================>-------]  74%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_mytypekassenwaageherstellers` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_mytypekassenwaageherstellers.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1199/1612 [====================>-------]  74%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_mytypekassenwaagemodells` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_mytypekassenwaagemodells.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1200/1612 [====================>-------]  74%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_mytypetischscannerherstellers` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_mytypetischscannerherstellers.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

 1206/1612 [====================>-------]  74%SQL Error "1067": Invalid default value for 'date_creation' in query "ALTER TABLE `glpi_plugin_genericobject_mytypetischscannermodells` MODIFY COLUMN `id` int unsigned NOT NULL  auto_increment"
Die Migration der Spalte "glpi_plugin_genericobject_mytypetischscannermodells.id" ist mit der Meldung "(1067) Invalid default value for 'date_creation'" fehlgeschlagen.

Errors occurred during migration.
You should try to update following plugins to their latest version and run the command again: Objects management.
`

Objects management is the latest version, so - how to solve this?

### Relevant log output

```shell
unsuitable
```

### Page URL

unsuitable

### Steps To reproduce

unsuitable

### Your GLPI setup information

unsuitable

### Anything else?

unsuitable

**Comment by trasher** [comment]
Same here, error seems related to a bad date from the plugin, not related to unsigned and not related to glpi core.

**Comment by cedric-anne** [comment]
Hi,

`glpi_items_softwareversions.date_install` was created in GLPI 9.1 (was `glpi_computers_softwareversions.date_install` at this moment). I guess that, at this time, migration was not handled correctly, and the SQL query was something like ``` ALTER TABLE `glpi_computers_softwareversions` ADD `date_install` date DEFAULT '' ```. As `sql_mode` was set to empty prior to GLPI 10.0, `''` was transformed to `'0000-00-00'`, and SQL server was acepting it. Since GLPI 10.0, only the `ONLY_FULL_GROUP_BY` flag is removed from `sql_mode`, and so `NO_ZERO_IN_DATE` flag is applied by default, and an error is triggered when a table that contains `'0000-00-00'` as default value for a date field is altered.

I am not sure it is possible to produce an automated fix for that, but you should be able to fix it manually by changing default values to `NULL` for these fields.

**Comment by cedric-anne** [comment]
> I am not sure it is possible to produce an automated fix for that, but you should be able to fix it manually by changing default values to `NULL` for these fields.

Maybe you should try to run the

**Comment by vollkommenIrrelevant** [comment]
@cedric-anne 
Thank you for your answer. To clarify: I should set the default value for date_install (and so on) => Null?

@trasher 
Where is the right place for errors in plugins?

**Comment by trasher** [comment]
> @trasher Where is the right place for errors in plugins?

On related plugin repository

**Comment by cedric-anne** [comment]
> @cedric-anne
> Thank you for your answer. To clarify: I should set the default value for date_install (and so on) => Null?

Exactly, you should replace default value from illegal `'0000-00-00'` to `NULL`.

**Comment by vollkommenIrrelevant** [comment]
> > @cedric-anne
> > Thank you for your answer. To clarify: I should set the default value for date_install (and so on) => Null?
> 
> Exactly, you should replace default value from illegal `'0000-00-00'` to `NULL`.

@cedric-anne 
Ok, originale table structure:
`mysql> show fields from glpi_items_softwareversions;
+---------------------+--------------+------+-----+---------+----------------+
| Field               | Type         | Null | Key | Default | Extra          |
+---------------------+--------------+------+-----+---------+----------------+
| id                  | int          | NO   | PRI | NULL    | auto_increment |
| items_id            | int          | YES  |     | NULL    |                |
| itemtype            | varchar(100) | NO   | MUL | NULL    |                |
| softwareversions_id | int          | NO   | MUL | 0       |                |
| is_deleted_item     | tinyint(1)   | NO   | MUL | 0       |                |
| is_template_item    | tinyint(1)   | NO   | MUL | 0       |                |
| entities_id         | int          | NO   | MUL | 0       |                |
| is_deleted          | tinyint(1)   | NO   | MUL | 0       |                |
| is_dynamic          | tinyint(1)   | NO   | MUL | 0       |                |
| date_install        | date         | YES  | MUL | NULL    |                |
+---------------------+--------------+------+-----+---------+----------------+
`

modified structure:
`+---------------------+--------------+------+-----+---------+----------------+
| Field               | Type         | Null | Key | Default | Extra          |
+---------------------+--------------+------+-----+---------+----------------+
| id                  | int          | NO   | PRI | NULL    | auto_increment |
| items_id            | int          | YES  |     | NULL    |                |
| itemtype            | varchar(100) | YES  | MUL | NULL    |                |
| softwareversions_id | int          | YES  | MUL | NULL    |                |
| is_deleted_item     | tinyint(1)   | YES  | MUL | NULL    |                |
| is_template_item    | tinyint(1)   | YES  | MUL | NULL    |                |
| entities_id         | int          | YES  | MUL | NULL    |                |
| is_deleted          | tinyint(1)   | YES  | MUL | NULL    |                |
| is_dynamic          | tinyint(1)   | YES  | MUL | NULL    |                |
| date_install        | date         | YES  | MUL | NULL    |                |
+---------------------+--------------+------+-----+---------+----------------+`

Unfortenately there is the same error message... I guess that the problem is that `0000-00-00` is no valid value and the stored data should be changed... 

- Maybe you can improve the upgradetool glpi:migration:unsigned_keys?
- I can't found a bugtracker at the project page, do you have a more suitable place for the problem?

**Comment by vollkommenIrrelevant** [comment]
> Hum, my bad, I thought the issue was on table structure, but it seems to be on values.
> 
> To fix data, you should probably execute `` UPDATE `glpi_items_softwareversions` SET `date_install` = NULL WHERE `date_install` IS NOT NULL AND `date_install` < '1000-01-01' `` .

thank you for your reply, this did work. In adition I had to change some tables because the datatype datetime could not be converted:
`show fields from glpi_plugin_genericobject_kassenmonitoretypes;
+---------------+--------------+------+-----+---------------------+----------------+
| Field         | Type         | Null | Key | Default             | Extra          |
+---------------+--------------+------+-----+---------------------+----------------+
| id            | int          | NO   | PRI | NULL                | auto_increment |
| name          | varchar(255) | YES  | MUL | NULL                |                |
| comment       | text         | YES  |     | NULL                |                |
| date_mod      | timestamp    | YES  | MUL | NULL                |                |
| date_creation | timestamp    | NO   | MUL | 0000-00-00 00:00:00 |                |
+---------------+--------------+------+-----+---------------------+----------------+
`

`ALTER TABLE glpi_plugin_genericobject_kassenmonitoretypes MODIFY date_creation DATE DEFAULT null;`
`show fields from glpi_plugin_genericobject_kassenmonitoretypes;
+---------------+--------------+------+-----+---------+----------------+
| Field         | Type         | Null | Key | Default | Extra          |
+---------------+--------------+------+-----+---------+----------------+
| id            | int          | NO   | PRI | NULL    | auto_increment |
| name          | varchar(255) | YES  | MUL | NULL    |                |
| comment       | text         | YES  |     | NULL    |                |
| date_mod      | timestamp    | YES  | MUL | NULL    |                |
| date_creation | date         | YES  | MUL | NULL    |                |
+---------------+--------------+------+-----+---------+----------------+
`

It seems that the plugin is still working if date_creation is from type date instead of datetime...

**Comment by vollkommenIrrelevant** [comment]
> > thank you for your reply, this did work. In adition I had to change some tables because the datatype datetime could not be converted:
> 
> No sure it was a good idea. You should revert this part if plugin does not work properly.
Currently everything is fine. I will check and revert this if i run into problems...

> 
> #11925 will fix this kind of values (will be done automatically when upgrading to GLPI 10.0.2, when release will be available).

great, thank you 👍
