### ISSUE TITLE
Bad translation to Spanish (Spain)

### ISSUE THREAD

**Issue by scarpio97** [glpi-project/glpi#11917]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

Good,

We have recently upgraded from version 9.5.7 to version 10.0.1.
After that we have detected that a large percentage of words are not translated correctly and are displayed in English.

Is there a patch to correct the language or a plugin?

Thank you very much and greetings!

**Comment by trasher** [comment]
Translations are done on Transifex:
https://www.transifex.com/glpi/GLPI/dashboard/

All translations are updated before each release.

**Comment by alexmicontini** [comment]
Hello,
I join the request!

![image](https://user-images.githubusercontent.com/86783891/174285777-a1a1ee05-c828-4ed1-9769-023545426b94.png)

**Comment by cedric-anne** [comment]
Fetching up-to-date translations is part of our release process, so if you translate the strings in transifex, they will be translated in GLPI 10.0.2.
