### ISSUE TITLE
Exception creating a ticket

### ISSUE THREAD

**Issue by Kaya84** [glpi-project/glpi#11918]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

By creating a new ticket inside web page (Assistance -> tickets -> add) an error occured.
This is the message:
Uncaught Exception TypeError: in_array(): Argument #2 ($haystack) must be of type array, int given in /var/www/glpi/src/RuleTicketCollection.php at line 144

### Anything else?

RuleTicketCollection.php at  line 144 is 
if (in_array($actor['items_id'], $input[$input_key])) {

If i change to:
if (in_array($actor['items_id'], array($input[$input_key]))) {
Everything seems to work

**Comment by Tony710** [comment]
Same issue after 10.0.1 upgrade

**Comment by jm-sbe** [comment]
Same problem here.

**Comment by cconard96** [comment]
Possibly related to #11796.
A fix is being worked on in #11957

**Comment by cconard96** [comment]
Please update to 10.0.2 when possible or apply the referenced fix manually to see if the issue is resolved.
