### ISSUE TITLE
[GLPI 10.0.1] - Undefined array key "id" in C:\inetpub\wwwroot\glpi\src\CommonDBTM.php

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#11914]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.1

### Bug description

When I try to delete or doing some actions with ticket I have error 500

### Relevant log output

```shell
[2022-06-16 00:43:23] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in C:\inetpub\wwwroot\glpi\src\CommonDBTM.php at line 1918
  Backtrace :
  plugins\formcreator\hook.php:719                   CommonDBTM->delete()
  src\Plugin.php:1464                                plugin_formcreator_hook_update_profile()
  src\CommonDBTM.php:1655                            Plugin::doHook()
  front\profile.form.php:65                          CommonDBTM->update()
```

**Comment by cconard96** [comment]
This seems to be an issue with the Form Creator plugin. Please open an issue on their GitHub.
https://github.com/pluginsGLPI/formcreator/issues/new/choose
