### ISSUE TITLE
Error to assingned tickets to other group

### ISSUE THREAD

**Issue by wc55** [glpi-project/glpi#11913]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When assigning group 1 to group 2, I get the message "You don't have permission to perform this action".

The ticket is assigned to group 2, but the message appears and causes some discomfort.

I don't know if it's necessarily a bug or if it's a default behavior of the system, but anyway I would like to evaluate.

- Information: In the tested profile, the "SEE ALL TICKETS" option in the "Assistance" menu is NOT enabled. When it is enabled, the error does not appear, so it may be a default behavior. The option "ASSIGN" is enabled

### Page URL

front/ticket.form.php?id=

### Steps To reproduce

1 - Access "Assistance" > "Tickets" > Access a ticket)
2 - On the ticket screen, assign the ticket to a group and remove the current group from the ticket.
3 - Assign the ticket to another group and remove it from the current group
![image](https://user-images.githubusercontent.com/106084399/173837846-1ccf0e50-ef3d-4145-bf60-0c41361d60df.png)
![image](https://user-images.githubusercontent.com/106084399/173838089-c9f5d784-837d-46fd-bc73-d5cc1e1ee0f1.png)

4 - Click Save. After saving, the message is displayed:
![image](https://user-images.githubusercontent.com/106084399/173841317-92cb0e91-3f13-46d6-a880-7ea37e1e852b.png)

I remember that the ticket is assigned to the target group, only the message is displayed.

### Your GLPI setup information

GLPI 10.0.1 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

### Anything else?

I'm not sure if it's a mistake, but I'd like to let you know. In addition, we suggest a possibility of error.

If it's a configuration issue, please let me know what to do.

**Comment by wc55** [comment]
Hi

In version 10.0.2 the problem still happens.

Log:

2022-07-28 21:24:32 [@UNOUNIV-0T156DN]
CSRF check failed for User ID:  at /glpi/front/login.php2022-07-28 21:26:53 [10@UNOUNIV-0T156DN]
User ID: 10 tried to access or perform an action on /glpi/front/ticket.form.php?id=1 with insufficient rights. Additional information: No additional information given
	Stack Trace:
		C:\xampp\htdocs\glpi\src\CommonDBTM.php:6240 displayRightError()
		C:\xampp\htdocs\glpi\src\CommonDBTM.php:6328 displayAccessDeniedPage()
		C:\xampp\htdocs\glpi\front\ticket.form.php:259 displayFullPageForItem()

**Comment by cconard96** [comment]
Duplicate of #12337
