### ISSUE TITLE
integration with "zabbix" and "glpi reminders" does not work

### ISSUE THREAD

**Issue by basson63** [glpi-project/glpi#11919]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hello!
the API mechanism does not work in glpi 10, there is no way to connect the browser extension "glpi reminders" and configure a bundle with zabbix.

I set up according to these instructions:
https://www.zabbix.com/ru/integrations/glpi

https://tic.gal/en/how-to-setup-glpi-api/

### Relevant log output

```shell
Sending failed: Error received from GLPi: missing app_token parameter;
```

### Your GLPI setup information

GLPI 10.0.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_EN

**Comment by alexbmw00** [comment]
Hi [basson63](https://github.com/basson63)

I had the same problem today, what happens is that the field/value "Application Token (app_token)" in Home > Setup > General > API Client , needs to be blank, without generating or inserting a key, I tested it here in the Zabbix integration , and it worked (after hours of tshot).

**Comment by lauroitalo** [comment]
> Hi [basson63](https://github.com/basson63)
> 
> I had the same problem today, what happens is that the field/value "Application Token (app_token)" in Home > Setup > General > API Client , needs to be blank, without generating or inserting a key, I tested it here in the Zabbix integration , and it worked (after hours of tshot).

**Comment by lauroitalo** [comment]
> Hi [basson63](https://github.com/basson63)
> 
> I had the same problem today, what happens is that the field/value "Application Token (app_token)" in Home > Setup > General > API Client , needs to be blank, without generating or inserting a key, I tested it here in the Zabbix integration , and it worked (after hours of tshot).

How did you manage to leave "app_token" ( Home --> Setup --> General --> API ) blank? always generates a new token.

**Comment by lauroitalo** [comment]
> > Hi [basson63](https://github.com/basson63)
> > I had the same problem today, what happens is that the field/value "Application Token (app_token)" in Home > Setup > General > API Client , needs to be blank, without generating or inserting a key, I tested it here in the Zabbix integration , and it worked (after hours of tshot).
> 
> How did you manage to leave "app_token" ( Home --> Setup --> General --> API ) blank? always generates a new token.

It's a bug in version 10.0.7. Which does not leave the APP_token blank. Solution update or perform manual correction: https://forum.glpi-project.org/viewtopic.php?id=287035

**Comment by OscarBeiro** [comment]
10.0.9 fixed the issue.
