### ISSUE TITLE
Count Total tickets by User

### ISSUE THREAD

**Issue by hakihosting** [glpi-project/glpi#11920]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

![image](https://user-images.githubusercontent.com/47614045/174110935-f3c5d30e-0764-4d89-8574-4af38ce31a6d.png)

The total count of tickets is not showing , loading

**Comment by cconard96** [comment]
Please provide the requested information.
Specifically, any GLPI log entries from around the time of the issue (`files/_log/php-errors.log` and `files/_log/sql-errors.log`), the GLPI setup information, and in this case any warnings or errors in the browser's console (F12 key > Console tab).
