### ISSUE TITLE
Problem creating domain registrations.

### ISSUE THREAD

**Issue by alexmicontini** [glpi-project/glpi#11927]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Hi, 

when I go to create new domain registrations the page stays blank.

I have cleared the glpi cache and the browser cache. It happens to me in two different environments.

In the logs and in Glpi with debugging mode activated no error is observed.

OS: Debian 10
PHP: 8.1

### Anything else?

![image](https://user-images.githubusercontent.com/86783891/174284975-c369ac6b-3541-48bb-b41f-b9cf9a5fced9.png)

**Comment by trasher** [comment]
Please provide logs as requested; also try without any plugins.

**Comment by alexmicontini** [comment]
Hi,

he disabled all plugins
![image](https://user-images.githubusercontent.com/86783891/174294723-48a8236d-b7f1-46cb-a97e-63ff224e8835.png)

there are no errors in the logs: php-errors.php and sql-errors.php neither in debug mode, neither in Apache nor in Mysql.

An image appears in the window spinning around but immediately disappears.

**Comment by cedric-anne** [comment]
On my side, I am not able to reproduce.

**Comment by alexmicontini** [comment]
Hi,

Where in the code can the error occur?

![image](https://user-images.githubusercontent.com/86783891/174300838-5fa69839-481f-4c4a-90b4-7fb730b3dc4e.png)

**Comment by alexmicontini** [comment]
Hi,

the problem seems to be in the DomainRecord::displayFullPageForItem function.

 _DomainRecord::displayFullPageForItem($_GET["id"], $menus, [
        'domains_id'   => $_GET['domains_id'] ?? null,
        'withtemplate' => $_GET["withtemplate"]
    ]);_

**Comment by alexmicontini** [comment]
Hello @cedric-anne ,

it was not a bug but rather the user's profile did not have permissions to register any type of domain registration. Once done I was able to create new domain registrations.

Now the problem I have is that I cannot associate the domain with elements created with the GenericObject plugin, only those that appear in the select field. Is there any way to do it?

![image](https://user-images.githubusercontent.com/86783891/174573683-488bdda3-d6c1-4496-be2e-a98f7fe25f7f.png)

Thank you

**Comment by alexmicontini** [comment]
Hi @cconard96,

Sorry, i can't to use the computer for a long time.

when i can i will do that.
