### ISSUE TITLE
Notification stock target has wrong numbers

### ISSUE THREAD

**Issue by blackxthink** [glpi-project/glpi#11930]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

I just set up the notification for the consumable / cartridges notification.
I just noticed the consumable notification sends the wrong data.

The puts "1" as my stock target but it is much higher.
It also calculates how many to order with the wrong data.

The email is in french (sorry):

```
Modèle de consommable : Câble HDMI 10'

Référence : 
Restant (left): 0
Objectif de stock (stock target): 1
Commander (order quantity): 1
```

It should be : 
```
Modèle de consommable : Câble HDMI 10'

Référence : 
Restant (left): 0
Objectif de stock (stock target): 15
Commander (order quantity): 15
```
The amount left is the right amount (i have none in inventory), but I feel like this is not working either, because i had an error earlier with cartridges that said i had 0 left... but i think i had more.  The biggest issue is that the notification is actually daily and I cannot test in real time.

![image](https://user-images.githubusercontent.com/48074916/174363185-c307facb-e94b-465c-a6ff-2fc6edf32d17.png)

![image](https://user-images.githubusercontent.com/48074916/174369243-7cf12243-c6d2-46a8-b8fa-1c53dd4ada15.png)

### Steps To reproduce

This is the straight forward notification system for alert thresholds.
Nothing special was done here.

**Comment by cconard96** [comment]
The stock target can default to `Alarm Threshold` + 1 if the target stock value is determined to be 0 or less in the notification logic. This would also mess up the number used for the amount to order.

I did find a bug with retrieving the alarm threshold within the notifications but I do not think it is related to this issue.

**Comment by blackxthink** [comment]
> 

Both default and the one in my item are at 5
Am i missing a setting somewhere ?

I don't know where it gets the "1" as stock threshold when both the default and specific are at 5
![image](https://user-images.githubusercontent.com/48074916/174389816-cd9f123e-a1eb-496a-98af-42272d1f089b.png)

**Comment by blackxthink** [comment]
> The stock target can default to `Alarm Threshold` + 1 if the target stock value is determined to be 0 or less in the notification logic. This would also mess up the number used for the amount to order.
> 
> I did find a bug with retrieving the alarm threshold within the notifications but I do not think it is related to this issue.

I tested the fix you posted earlier, it did not fix the issue:

![image](https://user-images.githubusercontent.com/48074916/174390989-7a03ce31-8242-4fb5-820e-3b9bf4fa7b75.png)

**Comment by cconard96** [comment]
Can you try the fix again with the new changes I added?
I'm dumb and it was using COUNT instead of SELECT when getting the threshold values from the database.

**Comment by blackxthink** [comment]
> Can you try the fix again with the new changes I added? I'm dumb and it was using COUNT instead of SELECT when getting the threshold values from the database.


Hell yeah ! it now works !
As always:  10/10 for your speed and being spot on.

![image](https://user-images.githubusercontent.com/48074916/174394086-423d9003-52ff-4cc1-b375-a23ce18e8f9a.png)
![image](https://user-images.githubusercontent.com/48074916/174394180-0207324a-ad25-4994-90c5-4358d843454d.png)
