### ISSUE TITLE
Wrong creation date in domain listing

### ISSUE THREAD

**Issue by alexmicontini** [glpi-project/glpi#11947]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

In the Domains list view, the date indicated is that of the moment of registration and not the one indicated on the registration form.

### Your GLPI setup information

Domain Example :

Registration date: 06/20/2022

Creation date: 03/18/2022

Date shown in listing: 06/20/2022

It should put 03/18/2022 on the list.

**Comment by cedric-anne** [comment]
Hi,

#11955 should fixes this.

**Comment by alexmicontini** [comment]
Hi,

Thanks a lot. I'll wait for 10.0.2 to apply the change.

Cheers
