### ISSUE TITLE
Bug services GLPI

### ISSUE THREAD

**Issue by RomainL45** [glpi-project/glpi#11940]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

//

### Bug description

Hello
We have a problem on our GLPI.
9 automatic services are in error and do not work anymore:

- PurgeLogs
- mailgate
- planningrecall
- queuednotification
- temp
- Fusioninventory - taskscheduler
- telemetry

So we don't have any more ticket creation from the mailbox (only way used), nor email notification on ticket update.

How can we solve this problem?

Thanks

**Comment by cedric-anne** [comment]
Hi,

> 9 automatic services are in error

What do you mean by "in error" ? Is there any error that outputs in logs ? In this case, please provide these logs.

> ### Version
> //

We do not support this `//` version of GLPI.

> _No response_
> _No response_
> _No response_
> _No response_
> _No response_

Not sure we can help you if you do not provide requested information.

**Comment by cedric-anne** [comment]
![image](https://user-images.githubusercontent.com/33253653/174584403-d378b6f2-abba-485f-9bd1-f139eb3dfa82.png)

**Comment by trasher** [comment]
Requested information has not been provided.

**Comment by RomainL45** [comment]
Hello
Here are the logs that came back
Thank
[php-errors - Copie.log](https://github.com/glpi-project/glpi/files/8957228/php-errors.-.Copie.log)
[sql-errors.log](https://github.com/glpi-project/glpi/files/8957229/sql-errors.log)
s

**Comment by trasher** [comment]
All errors are related to fusioninventory plugin. Try to reproduce issue with all plugins disabled.

**Comment by cedric-anne** [comment]
> GLPI Version 9.4.2

Many fixes have been made in GLPI 9.5 to have a better handling of errors in automatic actions. You should upgrade to GLPI 9.5.7, at least.
