### ISSUE TITLE
Prevent the possibility of change Period of execution

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1195]
Hi all.
GLPI 0.90.1
Tell me is there any possibility to block individual users (users group) modify individual items in Tickets when you work with it.

Prevent the possibility of change:
urgency
impact
SLA

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
