### ISSUE TITLE
GLPI 10.0.1 Global search display right error 

### ISSUE THREAD

**Issue by AymericFR02** [glpi-project/glpi#11961]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Hi,

When I'm trying to do a research in the global search (top right of the page), whatever my user profil (self-service, technician or super-admin) I've a message that said that i haven't the necessary right for this action 

![image](https://user-images.githubusercontent.com/69959679/174797681-6c93f4b8-ffaf-4a7b-b336-144e5d06c699.png)

### Relevant log output

```shell
I don't have any error in my log
```

### Page URL

http://DNS-record-OR-IP-address/front/search.php?globalsearch=108

### Steps To reproduce

just by doing a research whatever the page. 

### Your GLPI setup information

Operating system: Windows NT W2019 10.0 build 17763 (Windows Server 2016) AMD64
PHP 7.4.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	com_dotnet, ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sockets, sqlite3, standard, tokenizer,
	xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.46 (Win64) PHP/7.4.9 (Apache/2.4.46 (Win64) PHP/7.4.9 Server at DNS-RECORD Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.31
	Server SQL Mode: STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER
	Parameters: glpi@localhost:3306/glpi
	Host info: localhost via TCP/IP
	
PHP version (7.4.9) is supported.PHP version (7.4.9) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.31) is supported.Database engine version (5.7.31) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\wamp64\www\glpi/files/_cache has been validated. Write access to C:\wamp64\www\glpi/config has been validated. Write access to C:\wamp64\www\glpi/files/_cron has been validated. Write access to C:\wamp64\www\glpi/files has been validated. Write access to C:\wamp64\www\glpi/files/_dumps has been validated. Write access to C:\wamp64\www\glpi/files/_graphs has been validated. Write access to C:\wamp64\www\glpi/files/_lock has been validated. Write access to C:\wamp64\www\glpi/files/_pictures has been validated. Write access to C:\wamp64\www\glpi/files/_plugins has been validated. Write access to C:\wamp64\www\glpi/files/_rss has been validated. Write access to C:\wamp64\www\glpi/files/_sessions has been validated. Write access to C:\wamp64\www\glpi/files/_tmp has been validated. Write access to C:\wamp64\www\glpi/files/_uploads has been validated.Write access to C:\wamp64\www\glpi/files/_cache has been validated.
Write access to C:\wamp64\www\glpi/config has been validated.
Write access to C:\wamp64\www\glpi/files/_cron has been validated.
Write access to C:\wamp64\www\glpi/files has been validated.
Write access to C:\wamp64\www\glpi/files/_dumps has been validated.
Write access to C:\wamp64\www\glpi/files/_graphs has been validated.
Write access to C:\wamp64\www\glpi/files/_lock has been validated.
Write access to C:\wamp64\www\glpi/files/_pictures has been validated.
Write access to C:\wamp64\www\glpi/files/_plugins has been validated.
Write access to C:\wamp64\www\glpi/files/_rss has been validated.
Write access to C:\wamp64\www\glpi/files/_sessions has been validated.
Write access to C:\wamp64\www\glpi/files/_tmp has been validated.
Write access to C:\wamp64\www\glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\wamp64\www\glpi/marketplace has been validated.Write access to C:\wamp64\www\glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cconard96** [comment]
Please include the full GLPI Setup information.
You can click the "Copy system information" button on the Setup > General > System tab to copy all sections at once.

**Comment by AymericFR02** [comment]
Sorry,

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.1 ( => C:\wamp64\www\glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT W2019 10.0 build 17763 (Windows Server 2016) AMD64
PHP 7.4.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	com_dotnet, ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sockets, sqlite3, standard, tokenizer,
	xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.46 (Win64) PHP/7.4.9 (Apache/2.4.46 (Win64) PHP/7.4.9 Server at DNS-RECORD Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.31
	Server SQL Mode: STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER
	Parameters: glpi@localhost:3306/glpi
	Host info: localhost via TCP/IP
	
PHP version (7.4.9) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.31) is supported.
The log file has been created successfully.
Write access to C:\wamp64\www\glpi/files/_cache has been validated.
Write access to C:\wamp64\www\glpi/config has been validated.
Write access to C:\wamp64\www\glpi/files/_cron has been validated.
Write access to C:\wamp64\www\glpi/files has been validated.
Write access to C:\wamp64\www\glpi/files/_dumps has been validated.
Write access to C:\wamp64\www\glpi/files/_graphs has been validated.
Write access to C:\wamp64\www\glpi/files/_lock has been validated.
Write access to C:\wamp64\www\glpi/files/_pictures has been validated.
Write access to C:\wamp64\www\glpi/files/_plugins has been validated.
Write access to C:\wamp64\www\glpi/files/_rss has been validated.
Write access to C:\wamp64\www\glpi/files/_sessions has been validated.
Write access to C:\wamp64\www\glpi/files/_tmp has been validated.
Write access to C:\wamp64\www\glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\wamp64\www\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\wamp64\www\glpi
GLPI_CONFIG_DIR: C:\wamp64\www\glpi/config
GLPI_VAR_DIR: C:\wamp64\www\glpi/files
GLPI_MARKETPLACE_DIR: C:\wamp64\www\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\wamp64\www\glpi/files
GLPI_CACHE_DIR: C:\wamp64\www\glpi/files/_cache
GLPI_CRON_DIR: C:\wamp64\www\glpi/files/_cron
GLPI_DUMP_DIR: C:\wamp64\www\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\wamp64\www\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\wamp64\www\glpi/files/_locales
GLPI_LOCK_DIR: C:\wamp64\www\glpi/files/_lock
GLPI_LOG_DIR: C:\wamp64\www\glpi/files/_log
GLPI_PICTURE_DIR: C:\wamp64\www\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\wamp64\www\glpi/files/_plugins
GLPI_RSS_DIR: C:\wamp64\www\glpi/files/_rss
GLPI_SESSION_DIR: C:\wamp64\www\glpi/files/_sessions
GLPI_TMP_DIR: C:\wamp64\www\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\wamp64\www\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\wamp64\www\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\wamp64\www\glpi/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\wamp64\www\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\wamp64\www\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\wamp64\www\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\wamp64\www\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\wamp64\www\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\wamp64\www\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\wamp64\www\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\wamp64\www\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\wamp64\www\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\wamp64\www\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\wamp64\www\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\wamp64\www\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\wamp64\www\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\wamp64\www\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\wamp64\www\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\wamp64\www\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\wamp64\www\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\wamp64\www\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\wamp64\www\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\wamp64\www\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\wamp64\www\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\wamp64\www\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\wamp64\www\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\wamp64\www\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\wamp64\www\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\wamp64\www\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\wamp64\www\glpi\vendor\psr\cache\src)
league/csv in (C:\wamp64\www\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\wamp64\www\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\wamp64\www\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\wamp64\www\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\wamp64\www\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\wamp64\www\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\wamp64\www\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\wamp64\www\glpi\vendor\symfony\cache)
html2text/html2text in (C:\wamp64\www\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\wamp64\www\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\wamp64\www\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\wamp64\www\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\wamp64\www\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (C:\wamp64\www\glpi\vendor\symfony\polyfill-php80)
symfony/polyfill-php81 in (C:\wamp64\www\glpi\vendor\symfony\polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'IP-ADDRESS', Port: '389', BaseDN: 'dc=ad,dc=COMPAGNYNAME,dc=fr', Connection filter: '
		(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))) ', RootDN:
		'cn=administrateur,cn=users,dc=ad,dc=COMPAGNYNAME,dc=fr', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (MAIL-SETTING)

</details><details><summary>Plugins list</summary><pre> 
	gantt                Name: gantt                          Version: 1.0.0      State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.1      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.8.0      State: Installed / not activated

</pre></details>

**Comment by AymericFR02** [comment]
Can i have some news please ?

**Comment by AymericFR02** [comment]
Nobody ?

**Comment by AymericFR02** [comment]
So, Finally, i've search in the code, and with the docs I've find that there is a setting in the "configuration" tab," General configuration", in the section Search Engine, there is a parameter "Global Search", you just to set it with 'Yes' value.
