### ISSUE TITLE
network port type set to null on inventorying

### ISSUE THREAD

**Issue by scycrom** [glpi-project/glpi#11972]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.1 

### Bug description

after my update, after an agent do the inventorying, the network port type of the computer is set to null. this happen with both of the agent fusion and glpi-agent and even with the native inventory or the glpi inventory plugin but this problem didn't show up on fusioninventory.

Before the inventorying:
![glpi-before-port](https://user-images.githubusercontent.com/56172841/174969616-8a535570-5ccf-4817-ad76-e731bdacf957.png)
![glpi-before-port-details](https://user-images.githubusercontent.com/56172841/174969622-56dc3370-ed1f-4dc5-9c9d-21677d261042.png)

After the inventorying:
![glpi-after-port](https://user-images.githubusercontent.com/56172841/174969636-be80af6f-67ea-42ff-bb59-48a9ad62e1f7.png)
![glpi-after-port-details](https://user-images.githubusercontent.com/56172841/174969644-d2435609-d41e-407b-bf52-e8ec0f313471.png)

### Relevant log output

```shell
I didn't find any error in the log
```

**Comment by scycrom** [comment]
Can you please precise what file exactly you need.

**Comment by scycrom** [comment]
I send you the configuration but I don't know if its what you need

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.1 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux hgsl03063TST 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64
PHP 7.4.29 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at 10.3.2.150 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.44
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: admglpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.29) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'hgsw03021', Port: '389', BaseDN: 'DC=ch,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'cn=_SVCLDAP,ou=cpt-services,ou=GP_CHD,DC=ch,DC=local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp-chd.ch.local)

</details><details><summary>Plugins list</summary><pre> 
	archires             Name: Architectures réseau           Version: 2.7.0      State: Error / to clean
	fields               Name: Champs supplémentaires         Version: 1.15.1     State: Enabled
	datainjection        Name: Data Injection                 Version: 2.11.1     State: Enabled
	formcreator          Name: Form Creator                   Version: 2.13.0-beta.2 State: Enabled
	fusioninventory      Name: FusionInventory                Version: 10.0.0+1.0 State: Error / to clean
	genericobject        Name: Gestion d'objets               Version: 2.12.0     State: Enabled
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled
	reports              Name: Rapports                       Version: 1.14.1     State: Error / to clean

</pre></details>

**Comment by bruno-alu** [comment]
i have the same problem and when i put manually the ip and save it, the place is empty

**Comment by WebGregGit** [comment]
Hi @bruno-alu and @scycrom 

Do you see correctly inventoried ports after entering the switch?

**Comment by scycrom** [comment]
Hi, from the switch view the link is disconnected and I can't find anymore the computer

**Comment by WebGregGit** [comment]
For me there was a problem with displaying the ports from the switch side (I did not check the computer side) after the update. 
There were problems with the switches being added by Fusion and now the inventory was going through the native GLPI.
I deleted all switches and inventoried them again.

**Comment by scycrom** [comment]
I look a little in the database and for me it's a problem from the computer side after being inventoried, on the top there is two computers after the inventorying and the two on the bottom were not inventoried. the type of the port is set to null and because of that we can't see it from the network port view of GLPI and we can't see it from the switch because it's not the same interface.
![image](https://user-images.githubusercontent.com/56172841/175238129-b17b2650-f42e-4ee2-be8a-6d7daef0f612.png)

**Comment by WebGregGit** [comment]
Strange thing. Today I went into one of the computers and checked the network ports tab. And...

![image](https://user-images.githubusercontent.com/68922721/175381019-fe12539e-1b78-41ff-bdc8-2481deaa81b4.png)

So I checked the switch to which the computer is connected. Yesterday I had ports. But today... only 1 port - Management port. 

I started the SNMP task force - the ports have appeared again. I checked the computer - there is a link again.

Historical information (switch)

<html>
<body>


3879494 | 2022-06-23 21:05 | inventory | Last inventory date | Change 2022-06-23 19:39 to 2022-06-23 21:05
-- | -- | -- | -- | --
3877484 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877483 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877482 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877481 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877480 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877479 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877478 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877477 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877476 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877475 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877474 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877473 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877472 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877471 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877470 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877469 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877468 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877467 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877466 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877465 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877464 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877463 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877462 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877461 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877460 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877459 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877458 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877457 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877456 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877455 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877453 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877452 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877451 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877450 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877449 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877448 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877447 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877446 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877445 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877444 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877443 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877442 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877441 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877440 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877439 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877438 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877437 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877436 | 2022-06-23 19:39 | inventory | Network port | Delete an item: Network port ()
3877435 | 2022-06-23 19:39 | inventory | Last inventory date | Change 2022-06-22 22:15 to 2022-06-23 19:39
3378805 | 2022-06-22 22:15 | inventory | Last inventory date | Change 2022-06-22 20:14 to 2022-06-22 22:15
3376848 | 2022-06-22 20:14 | inventory | Network port | Delete an item: Network port ()
3376847 | 2022-06-22 20:14 | inventory | Network port | Delete an item: Network port ()


</body>
</html>

1. Why I have only delete info? What about add?
2. Why I don't have which port was deleted info?
3. Why were the ports even deleted at all?

**Comment by WebGregGit** [comment]
I ran the discovery job a few minutes later and... the ports are gone again.

**Comment by bruno-alu** [comment]
It s not à problèm with thé switch 
Bécause if i read manuelly thé ip address in thé field and save it
Thé field is empty after since thé v10 

Thé field was good in 9.5.7 version 

Bruno SAZERAT 
Envoyé de mon iPhone

**Comment by scycrom** [comment]
From what I can see there is a problem with the switch and the computer.
@WebGregGit , can you connect the computer to a switch (from the network port tab of the computer) or like me the section with the port type and connection disappeared (look at my previous screenshots)

**Comment by WebGregGit** [comment]
Hi @scycrom 

My mistake - I was describing another problem. It looks like a problem with the plugin. https://github.com/glpi-project/glpi-inventory-plugin/issues/157

I am not sure if I understand your problem correctly. This is my port view from the switch side. I have here the Ethernet port section:
![image](https://user-images.githubusercontent.com/68922721/175510059-7e432493-a7cb-4231-a4d2-09d084a83339.png)

But if I open the port from the computer side, this section is gone:
![image](https://user-images.githubusercontent.com/68922721/175510306-e28fad96-9527-4b0b-8cea-d0ca03353baf.png)

As a result, I cannot determine e.g. the port type.

**Comment by scycrom** [comment]
Hi, @WebGregGit, you understand my problem correctly about the ethernet port but for me this section is gone due to the null in the database after an inventory, this is not a problem with the plugin because I try without and I have the same problem with the native inventory.
