### ISSUE TITLE
Images pasted into the body of an email do not appear in tickets.

### ISSUE THREAD

**Issue by Molina15** [glpi-project/glpi#11979]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When a new ticket is created from an email, if it has images (I don't mean attached files, those don't cause problems), they are not displayed. I have seen that with previous versions #1929 there was also this problem and it ended up being corrected, but with version 10.0.1 it happens again, at least for me.

![image](https://user-images.githubusercontent.com/91999535/175055992-e6c1ea5e-7a1a-4708-96c1-3647daf6147f.png)

### Your GLPI setup information

Operating system: Linux ubuntu-glpi 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 192.168.100.42 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: Ubuntu 20.04
	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.PHP version (7.4.3) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.Database engine version (10.3.34) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated. Write access to /var/www/glpi/config has been validated. Write access to /var/www/glpi/files/_cron has been validated. Write access to /var/www/glpi/files has been validated. Write access to /var/www/glpi/files/_dumps has been validated. Write access to /var/www/glpi/files/_graphs has been validated. Write access to /var/www/glpi/files/_lock has been validated. Write access to /var/www/glpi/files/_pictures has been validated. Write access to /var/www/glpi/files/_plugins has been validated. Write access to /var/www/glpi/files/_rss has been validated. Write access to /var/www/glpi/files/_sessions has been validated. Write access to /var/www/glpi/files/_tmp has been validated. Write access to /var/www/glpi/files/_uploads has been validated.Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment]
Hi,

Could you please export the email that cause the issue into eml format and attach it here ? It would help us to reproduce the issue.

**Comment by Molina15** [comment]
Hello,

It happens with all mail with image. Attached is the one I used for the sample image published here.

[image test.zip](https://github.com/glpi-project/glpi/files/8959175/image.test.zip)

**Comment by dxdemetriou** [comment]
Probably is related with this? https://github.com/glpi-project/glpi/issues/11933

I tried the attached email after applying this https://github.com/glpi-project/glpi/commit/9333ae1ca627ce6e04393582e73f380567b0faf5 and it seems ok

**Comment by trasher** [comment]
@Molina15 please test with patch pointed by @dxdemetriou

**Comment by cedric-anne** [comment]
I cannot reproduce the issue using provided eml file.

![image](https://user-images.githubusercontent.com/33253653/177165602-5e8618fd-24c3-480a-b36a-c6c4a1477035.png)

I tried on both PHP 8.1.x and 7.4.30.

You are using PHP 7.4.3, you should try to update to 7.4.30, maybe this is related to a PHP bug.

**Comment by Molina15** [comment]
Hi, I have updated my version of PHP to 8.1 and restarted the service. 

![image](https://user-images.githubusercontent.com/91999535/177739393-b329a80a-fb68-496d-8000-2c1b25e564b8.png)

Now, the images I paste in the glpi itself if they work (1 problem solved), but the pastes on the body of the mails, still do not appear :(

![image](https://user-images.githubusercontent.com/91999535/177739608-6ada4498-aa79-4d0f-abf6-3a98782b134d.png)

**Comment by dxdemetriou** [comment]
@Molina15 in General, the "URL of the application" is in http and you are using https?

**Comment by Molina15** [comment]
I use http to access.

![image](https://user-images.githubusercontent.com/91999535/177929383-cddb9606-d084-4acd-8cf3-249097dade46.png)

**Comment by cedric-anne** [comment]
> the pastes on the body of the mails, still do not appear :(
> 
> ![image](https://user-images.githubusercontent.com/91999535/177739608-6ada4498-aa79-4d0f-abf6-3a98782b134d.png)

What are these images URL ?

**Comment by Molina15** [comment]
denied:cid:c2a9038c9d90edfc8c738a7d8f2eca79f5789481@zimbra

denied:cid:1bd3700ace4fc89b9bb1918ec2cd6c48837590f3@zimbra

![image](https://user-images.githubusercontent.com/91999535/177930400-540ff049-bca7-48ef-bf08-27bd0ac96174.png)

This is what appears when I try to open the images separately and also when looking at the code of the page.

**Comment by cedric-anne** [comment]
Can you provide, into eml format, the email that cause this issue ?
Also, do you have any active plugin ? In this case, please try to reproduce with no active plugin.

**Comment by Molina15** [comment]
You were right, it was an annoying plugin. This to be concrete. We can now view the images of the mails. Thank you very much for your help :D. Ticket closing.

![image](https://user-images.githubusercontent.com/91999535/177932735-6716133f-a812-4731-966c-5ab08a4bf7b7.png)

**Comment by cedric-anne** [comment]
@Molina15 

> When a new ticket is created from an email,

Is this a copy/paste in the browser, or a ticket created from mail collector ?

Could you check in browser console if you have an error when you paste an image, when this issue happens ?

**Comment by Molina15** [comment]
Hi,

In both chrome and edge, when I do Copy/paste and hit add, I get a box with the error "Problem moving file" (something that had been solved when upgrading to php 8.1, but now it gives an error again). Instead I use the insert image function that embeds the text box, the images load correctly.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/91999535/179479905-717c160c-aaa3-449d-b11a-7a6f010cbafa.png">

<img width="237" alt="image" src="https://user-images.githubusercontent.com/91999535/179480349-29e975b8-8945-4ef9-9d77-08d231905f91.png">

On the other hand, if the ticket is captured through mailcollector, in edge I can see them but not in chrome.

<img width="394" alt="image" src="https://user-images.githubusercontent.com/91999535/179488378-678709bb-1e9f-451d-9607-76783a62b27f.png">
EDGE

<img width="319" alt="image" src="https://user-images.githubusercontent.com/91999535/179488657-50449ff6-1d8e-4107-95cd-21b9b9ea21fb.png">
CHROME

**Comment by Molina15** [comment]
Do you need anything else?

**Comment by cedric-anne** [comment]
> EDIT: The issue of pasting images may be due to a problem with the clipboard. When I do "screen capture" and paste the image, it doesn't load, but instead if I copy an image with right click "copy" and then control "V", then it works.

As I do not have access to a Windows environment, I cannot try to reproduce. Maybe someone else could help.

**Comment by dronces** [comment]
Que tal Molina, has logrado solucionarlo, estoy en las mismas, ya instale en windows y en linux y nada, has logrado algun avance?

**Comment by Molina15** [comment]
Hola Dronces, si conseguí que funcionase. Era un problema de rutas.

En el servidor, en el archivo de host de apache
/etc/apache2/sites-available/000-default.conf (ruta en Ubuntu Sever) tienes
que configurar la el server.name i el document root.

Yo lo tengo asi:
[image: image.png]

*(Lo de rewrite es porque redirijo las peticiones http a https)*
Luego en el GLPI en Configuración-> General, en el campo de URL de la
aplicación tienes que asegurarte que la URL coincide con el nombre que has
puesto en serverName

[image: image.png]
Si tu servidor no tiene https configurado, pon http.

Y luego asegurarte que la URL desde la que acceden los usuarios y tú mismo
siempre es el DNS que has configurado, que debe coincidir con el
serverName. Nosotros creamos un acceso directo a todos los usuarios por GPO
con la URL.

Con todo eso, al fin aparecieron las imágenes.

Espero que te sirva, saludos!

**Comment by trasher** [comment]
Removed non english comments
