### ISSUE TITLE
10.0.1 - no Lock tab for some Assets

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#11985]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

If you open Assets > Monitors > and choose one... there is no Locks tab. The same for network devices, devices, printers... I see it only for the computers.

![image](https://user-images.githubusercontent.com/68922721/175253084-c60602f8-01e5-4254-927c-1607de5e01f0.png)

BTW - there is also no in global locks - the monitor category.

### Anything else?

For this monitor I have "alternate username" locked but I can't unlock it now

![image](https://user-images.githubusercontent.com/68922721/175253669-15b85326-8d44-412f-8bfb-3b1739787081.png)

**Comment by WebGregGit** [comment]
Still valid

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
can you try this -> https://github.com/glpi-project/glpi/pull/12471

Best regards

**Comment by WebGregGit** [comment]
And another bug fixed. Good job and thank you :)

**Comment by dxdemetriou** [comment]
Missing the Unlock tab also. There is only the "Unlock items" which gives an error "Failed operation".
