### ISSUE TITLE
Phone Asset can not show simcard component and can not adjust select default items to show

### ISSUE THREAD

**Issue by hoaitran0429** [glpi-project/glpi#11988]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Phone Asset can not show simcard component and can not adjust select default items to show

**Comment by cconard96** [comment]
Please provide the requested log output and GLPI setup Information.
Specifically, entries from `files/_log/php-errors.log` and `files/_log/sql-errors.log` from around the time you experienced the issue.
The setup information can be found under Setup > General > System tab.
