### ISSUE TITLE
GLPI Network tab of global configuration

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#11995]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2dev of today

### Bug description

![image](https://user-images.githubusercontent.com/12936722/175305819-bcbeaffe-155c-4493-bd6a-89c1ac10808f.png)

Logs
[2022-06-23 12:56:34] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch registration information.
Error message:
Response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
 in /home/yllen/glpi10/src/GLPINetwork.php at line 237
  Backtrace :
  src/GLPINetwork.php:237                            trigger_error()
  src/GLPINetwork.php:100                            GLPINetwork::getRegistrationInformations()
  src/GLPINetwork.php:49                             GLPINetwork::showForConfig(

**Comment by cedric-anne** [comment]
It looks like the registration key is "corrupted", maybe during a decrypt/encrypt operation. So, if there is something to fix, in is probably located in update process.
Could you try to reproduce the migrations context that corrupts the registration key ?
