### ISSUE TITLE
change no id

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1199]
Hello

in GLPI 9.1 The change ID does not appear anymore

![image](https://cloud.githubusercontent.com/assets/15144026/19559707/5e3a5a6c-96d1-11e6-939f-330574905e78.png)

**Comment by Armin83** [comment]
In Problems the same

**Comment by satyan01** [comment]
same in glpi 9.2

**Comment by satyan01** [comment]
same in ticket view 
![image](https://cloud.githubusercontent.com/assets/15144026/22114863/3545b82c-de6b-11e6-890f-04fc663c340d.png)

**Comment by satyan01** [comment]
it was very usefull to have ticket - ID:xxxxx - ticket title

**Comment by satyan01** [comment]
Hello I have added yes to show glpi id, but it shows id everywhere

**Comment by Armin83** [comment]
change have no id in 9.1.3 :(

**Comment by trasher** [comment]
Fixed, see #2338
