### ISSUE TITLE
10.0.1: Profiles - no user listing

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#11992]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

![image](https://user-images.githubusercontent.com/68922721/175290120-5ddac5f7-8cad-4e48-aa6e-880a1de04fdd.png)

### Page URL

front/profile.form.php

**Comment by cconard96** [comment]
It looks like the root entity category/folder is collapsed by default. If you click "Root entity" the users should show as expected.

**Comment by WebGregGit** [comment]
OMG... so sorry. You are absolutely right.
