### ISSUE TITLE
New ticket : cant set type,category and actors until ticket is created

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#12]
with the online demo also 
assistance>tickets>+
 front/ticket.form.php 
with this form i can't set actors, type, category.
I can set title desc and then create ticket. after i can edit this ticket to set these dropdowns

**Comment by orthagh** [comment]
Confirmed on demo, I don't reproduce on local.

**Comment by ladenree76000** [comment]
on demo with  user "admin" confirmed.
on demo with user "normal" can set category before creating.

**Comment by ladenree76000** [comment]
this morning it works fine with online demo ( user = admin)

**Comment by ladenree76000** [comment]
it works when display preference is set on " Tab on left"
it doesn't work when display is set on "vertical split "

**Comment by orthagh** [comment]
OK. I reproduce now. tests and corrections this morning
