### ISSUE TITLE
Update script CleanHistory.php

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#120]
0.85
Update the help of the script tools/cleanhistory.php : type is now up to 27 (see inc/log.class.php for definition)

In 0.90, I can't find the folder /tools. Has it been removed intentionally ?

**Comment by blerohellec** [comment]
0.90 : the /tools folder is not in the glpi-master.zip !!

**Comment by orthagh** [comment]
Yes, for release simplification, tools folder is not in compressed export / archives.
See : https://github.com/glpi-project/glpi/blob/master/.gitattributes
And : https://github.com/glpi-project/glpi/commit/0d700910224bbe5a60ab9955dce85f064a04d85d

You should use raw download of git for access to this folder ([github desktop](https://desktop.github.com/) eases retrieval of sources). 

In near future, we'll complete this .gitatttribute file to add another files (like old sql dumps)
