### ISSUE TITLE
[GLPI 10.0 Bugfixes] Don't see reservations from simplified interface

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#12009]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

```shell
Php error :

[2022-06-24 15:00:10] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $username in C:\wamp64\www\glpi\src\Reservation.php at line 559
  Backtrace :
  ajax\reservations.php:46                           Reservation::getEvents()
```

When drop if condition into Reservation.php at line 541
```
//if ($canedit_admin || $my_item) {
                $user->getFromDB($data['users_id']);
                $username = $user->getFriendlyName();
        //    }
```
The reservations are displayed
```

**Comment by diegorodrigo90** [comment]
@tsm, could you explain what steps you did to get this error?

I tested in the current dev version:

- I added a computer and enable a reservation for it.
- I signed in as a normal user (self-service).
- I made a reservation.

View of the logged-in user:

![image](https://user-images.githubusercontent.com/6834553/189506216-d8af7540-c800-4cbc-b04e-9099586305a1.png)

Admin User View:

![image](https://user-images.githubusercontent.com/6834553/189506236-d6eb2be2-d726-472e-94a3-afa0c2f2b645.png)

Is it possible that the error has already been resolved?
