### ISSUE TITLE
Translation error 

### ISSUE THREAD

**Issue by jm-sbe** [glpi-project/glpi#12007]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Wrong translation in locales/de_DE.po (line 718)

#: src/Html.php:433
#, php-format
msgid "%1$s%2$d hours %3$d minutes %4$d seconds"
msgstr "%1$s%2$d Tage %3$d Minuten %4$d Sekunden"

-----------------------

Need to be changed to:

#: src/Html.php:433
#, php-format
msgid "%1$s%2$d hours %3$d minutes %4$d seconds"
msgstr "%1$s%2$d Stunden %3$d Minuten %4$d Sekunden"

### Steps To reproduce

not relevant

### Your GLPI setup information

not relevant

**Comment by trasher** [comment]
Translations are done on transifex:
https://www.transifex.com/glpi/GLPI/dashboard/
