### ISSUE TITLE
GLPI 0.91 - No watcher with simplified interface

### ISSUE THREAD

**Issue by titio04** [glpi-project/glpi#1200]
Hello,

After a migration between GLPI 0.90.1 to 0.91, the interface field "watcher" has no result with the simplified interface (No user is displayed). 

If i change on the  profil for to use the "standard interface", no problem with the field "watcher".

This bug impact only the" simplified interface"

Best Regards

**Comment by Armin83** [comment]
I don't have this problem. Did you clean browser cache?

**Comment by titio04** [comment]
Yes. 

I have already tested, and it's not a problem with the cache.
Same problem with IE 11 and Firefox 49.0.1

![pb_glpi_watcher_0-91_img2](https://cloud.githubusercontent.com/assets/22375138/19590174/c143a038-9770-11e6-897c-1aa41b6e546d.png)
![pb_glpi_watcher_0-91](https://cloud.githubusercontent.com/assets/22375138/19590173/c13fc724-9770-11e6-9cb7-be84a04c7483.png)

Best Regards

**Comment by titio04** [comment]
Same problem with a fresh installation.

Best Regards

**Comment by Armin83** [comment]
Do you see error in debug modus ?
Can you check mysql for crashed tables ?

In my installation the user can only select members of its groups. If i ad new group with other members i can select new, more other users also in simplified interface.

**Comment by titio04** [comment]
Hi,


In my case i have no group attach on the  "basic users" profil for the moment (With the old version, i see all users with this configuration ).

OK, I understand that now with this version, the watchers use group for the simple interface.
I have created a specific group  for i see all the users on the field "watcher". 

But this is an important problem: it's not possible to create default rules to attach automatically this group on a user profile.

I'll have to add to manually the 270 users on this new group.

Is there a solution to attach by default and automaticaly this group on user profil ?

Best Regards

**Comment by titio04** [comment]
I have found a workaround for the moment.

I used a SQL request for to add the new group on all user profil. 
I created a trigger on the database for the new user (for to replace the automatic attribution rule of group).

The user is now available on the field "Watcher"


Best Regards
