### ISSUE TITLE
Hooks 'pre_show_item' and 'post_show_item' do not work with TicketTask and ITILFollowup

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#12025]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When a plugin wants to use the 'pre_show_item' and 'post_show_item' hooks they are not activated by the TicketTask, ITILFollowup and ITILSolution elements.
This fails on changes, problems and tickets.

### Steps To reproduce

1. Install plugin Example
2. Uncomment to print a test text
3. Entering a ticket with followups or tasks
4. The test text will not be displayed

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.1 ( => /home/glpi10/web/glpi10.tic.gal/public_html)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux testing01.tic.gal 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64
PHP 8.0.14 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="900" memory_limit="256M" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache/2.4.52 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f ()
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.5-MariaDB-1:10.6.5+maria~focal
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi10_glpirw@localhost/glpi10_glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.0.14) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.5) is supported.
The log file has been created successfully.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_cache has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/config has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_cron has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_dumps has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_graphs has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_lock has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_pictures has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_plugins has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_rss has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_sessions has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_tmp has been validated.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/files/_uploads has been validated.
Web access to files directory is protected

exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/glpi10/web/glpi10.tic.gal/public_html/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /home/glpi10/web/glpi10.tic.gal/public_html
GLPI_CONFIG_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/config
GLPI_VAR_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files
GLPI_MARKETPLACE_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files
GLPI_CACHE_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_cache
GLPI_CRON_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_cron
GLPI_DUMP_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_dumps
GLPI_GRAPH_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_graphs
GLPI_LOCAL_I18N_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_locales
GLPI_LOCK_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_lock
GLPI_LOG_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_log
GLPI_PICTURE_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_pictures
GLPI_PLUGIN_DOC_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_plugins
GLPI_RSS_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_rss
GLPI_SESSION_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_sessions
GLPI_TMP_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_tmp
GLPI_UPLOAD_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_uploads
GLPI_INVENTORY_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /home/glpi10/web/glpi10.tic.gal/public_html/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/iamcal/lib_autolink)
sabre/dav in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/sabre/http/lib)
sabre/uri in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/sabre/uri/lib)
sabre/vobject in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/elvanto/litemoji/src)
symfony/console in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/symfony/console)
scssphp/scssphp in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/ramsey/uuid/src)
psr/log in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/psr/simple-cache/src)
psr/cache in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/psr/cache/src)
league/csv in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/league/csv/src)
mexitek/phpcolors in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/symfony/cache)
html2text/html2text in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/html2text/html2text/src)
symfony/css-selector in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/symfony/dom-crawler)
twig/twig in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/twig/twig/src)
twig/string-extra in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/home/glpi10/web/glpi10.tic.gal/public_html/vendor/symfony/polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	example              Name: Plugin Example                 Version: 0.0.1      State: Enabled

</pre></details>

**Comment by cconard96** [comment]
Those hooks are only implemented for the tabs on forms.
What is the expected behavior for these hooks when used with the timeline items?
The "pre_item_form" and "post_item_form" hooks are implemented for the timeline items.

**Comment by xacobofg** [comment]
The hooks for the tabs should be "pre_show_tab" and "post_show_tab".
An example of use for these hooks can be found in the Actualtime plugin.
I use the hook "post_show_item" to show the plugin time in the task without having to open it.
I don't know if there is now another way to add extra information in the tasks or followups.

**Comment by Aeto-J** [comment]
The same problem for me with 'pre_show_item' and 'pre_item_form' / 'post_item_form' are missing in 'simple_form.Html.Twig', so we can't use either of them in a plugin that uses simple_form as main_description ticket editing form for example.

**Comment by cedric-anne** [comment]
@xacobofg @Aeto-J 

Can you validate that #12265 is OK for your needs ?

**Comment by xacobofg** [comment]
Hello @cedric-anne.
Sorry for taking so long to reply.
I tested the change and it works correctly
![actualtime](https://user-images.githubusercontent.com/39123808/181015236-db389425-c90e-4fbd-8315-058b6690d076.png)
