### ISSUE TITLE
Switch doctype to HTML5

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1202]
Hello,

I was trying to fix some minor HTML issues (not closed tags on authentication form, for instance); but there is a little problem: this form is xhtml-strict while main glpi is html 4.0 Transitional.

What about to switch all to html5? We already use some attributes (like required or placeholder) in some places that are html5 only.

**Comment by tomolimo** [comment]
Backward compatibility with old browsers?

**Comment by trasher** [comment]
As far as I know, there is nothing to say regarding compatibility.

The only thing that would not work natively on IE8 and above would be new tags (such as `<section>`, `<article>` and so on) - but solutions exists.

As for attributes like `required` or `palceholder`, they'll be ignored if the browser cannot handle them.

**Comment by tomolimo** [comment]
ok
