### ISSUE TITLE
 Automatic correction inoperative in the follow-ups, tasks, ... of a ticket

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#12021]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When we are in a field of a computer form, we have the possibility of spelling correction by right clicking on the error. The correct word is then proposed.
In the fields of follow-up, tasks, solution of ticket form, the spelling error is well identified, but the correction is not proposed.

**Comment by cconard96** [comment]
The browser's context menu can be accessed with crtl + right click in rich text boxes.
