### ISSUE TITLE
Lost of sellep query GLPI

### ISSUE THREAD

**Issue by mulbzh** [glpi-project/glpi#12034]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Hello,
On my server, ce process mysql use all my cpu.
In mysql, i used the command SHOW PROCESSLIST; i have more than 150 query like that

+--------+-------------+-----------+--------+---------+------+--------------------------+------------------+----------+
| Id     | User        | Host      | db     | Command | Time | State                    | Info             | Progress |
+--------+-------------+-----------+--------+---------+------+--------------------------+------------------+----------+
| 293190 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293207 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293209 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293211 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293212 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293215 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293217 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293219 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293220 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293222 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293223 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |
| 293225 | glpiuser    | localhost | glpidb | Sleep   |    0 |                          | NULL             |    0.000 |

i don't think it could be my CRON, my CROn is :
/usr/bin/php7.4 /var/www/html/glpi/front/cron.php &>/dev/null

### Your GLPI setup information

<html>
<body>

GLPI 10.0.1 ( => /var/www/html/glpi) Installation mode: TARBALL Current language:fr_FR
--

Operating system: Linux svweb 5.4.0-121-generic #137-Ubuntu SMP Wed Jun 15 13:33:07 UTC 2022 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.brestaim.fr Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36 Server Software: Ubuntu 20.04 	Server Version: 10.3.34-MariaDB-0ubuntu0.20.04.1 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: glpiuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 PHP version (7.4.3) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (10.3.34) is supported. The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/glpi/marketplace has been validated. Timezones seems loaded in database.

</body>
</html>

**Comment by cedric-anne** [comment]
Hi,

You should upgrade to GLPI 10.0.2. These queries may be related to recently fixed security issues.
