### ISSUE TITLE
Navtive Inventory: Records are still created for protected fields

### ISSUE THREAD

**Issue by AndiFo** [glpi-project/glpi#12038]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.x

### Bug description

For example: A new location is created, although the Location field is protected in the printers. However, the location is not assigned (under Historical, however, there is an entry as if).

### Page URL

https://SERVER/front/inventory.php

### Your GLPI setup information

GLPI 10.0.2 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:en_GB

**Comment by trasher** [comment]
#12046 should fix your isse

**Comment by AndiFo** [comment]
Sorry, the location is still being created even though the field is globally locked.

**Comment by trasher** [comment]
This was indeed working for Computer but not Printers. I've reworked and added a test on Printer/Location, case, all should be fine now.

**Comment by AndiFo** [comment]
Hello trasher,

For global locked fields it works fine. But if you have a non global locked field it is the same situation as the origin error.

**Comment by trasher** [comment]
Should be all fixed now. I've added the additional test case in our suite.
