### ISSUE TITLE
Uncaught Exception Error: Class "Normalizer" not found in

### ISSUE THREAD

**Issue by Christ125dd** [glpi-project/glpi#12040]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10.0.2

### Bug description

Hello, I have downloaded the latest glpi update. Qaund I make the command "php bin/console glpi:migration:timestamps" I have the following error: 

PHP Warning:  Missing required intl PHP extension in C:\xampp5\htdocs\glpi\src\Session.php on line 682
Uncaught Exception Error: Class "Normalizer" not found in C:\xampp5\htdocs\glpi\vendor\symfony\console\Helper\Helper.php at line 65

intl is well installed.

**Comment by cedric-anne** [comment]
> yet it is well activated

This is an output on Web context, not on CLI context. Please check your php.ini configuration CLI context: `php bin/console glpi:system:check_requirements`.
