### ISSUE TITLE
High CPU mysql because of query

### ISSUE THREAD

**Issue by mulbzh** [glpi-project/glpi#12064]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.2

### Bug description

Hello,

I am on Ubuntu 20.04 (last update) with mariadb and apache2, i update GLPI yesterday but the problem was also with GLPI 10.0.1
mysqld service is always at 100% CPU, i spent my day to find why.

So, what i found i that i have a lot of query, too many and because of that mysql is high CPU. The query come from the server, on localhost on glpi database. 

Show processlist on mysql show that each seconde i have these query, sometimes, more than 5 query by second. i don't know why ?!  it is not because of CRON !

 you can see query behind : 

### Relevant log output

```shell
Id: 162789
    User: glpiuser
    Host: localhost
      db: glpidb
 Command: Query
    Time: 0
   State: Checking permissions
    Info: SELECT `table_name` AS `TABLE_NAME` FROM `information_schema`.`tables` WHERE `table_schema` = 'glpidb' AND `table_type` = 'BASE TABLE' AND `table_name` LIKE 'glpi\_%'
Progress: 0.000
*************************** 152. row ***************************
      Id: 162790
    User: glpiuser
    Host: localhost
      db: glpidb
 Command: Query
    Time: 0
   State: Checking permissions
    Info: SELECT `table_name` AS `TABLE_NAME` FROM `information_schema`.`tables` WHERE `table_schema` = 'glpidb' AND `table_type` = 'BASE TABLE' AND `table_name` LIKE 'glpi\_%'
Progress: 0.000
```

**Comment by mulbzh** [comment]
i have also a lot of query error in logs :

`
[2022-06-30 16:31:36] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
319497    *** MySQL query error:
319498    SQL: SELECT * FROM `glpi_users` WHERE `id` = '412'
319499    Error: MySQL server has gone away
319500    Backtrace :
319501    src/DBmysqlIterator.php:110
319502    src/DBmysql.php:1048                               DBmysqlIterator->execute()
319503    src/DbUtils.php:1617                               DBmysql->request()
319504    inc/db.function.php:456                            DbUtils->getUserName()
319505    src/Search.php:6352                                getUserName()
319506    src/Search.php:1687                                Search::giveItem()
319507    src/Search.php:447                                 Search::constructData()
319508    src/Api/API.php:1646                               Search::getDatas()
319509    src/Api/APIRest.php:191                            Glpi\Api\API->searchItems()
319510    apirest.php:58                                     Glpi\Api\APIRest->call()
319511    {"user":"499@svweb","mem_usage":"0.000\", 4.99Mio)"}
319512  [2022-06-30 16:31:36] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
319513    *** MySQL query error:
319514    SQL: SELECT * FROM `glpi_users` WHERE `id` = '247'
319515    Error: MySQL server has gone away
319516    Backtrace :
319517    src/DBmysqlIterator.php:110
319518    src/DBmysql.php:1048                               DBmysqlIterator->execute()
319519    src/DbUtils.php:1617                               DBmysql->request()
319520    inc/db.function.php:456                            DbUtils->getUserName()
319521    src/Search.php:6352                                getUserName()
319522    src/Search.php:1687                                Search::giveItem()
319523    src/Search.php:447                                 Search::constructData()
319524    src/Api/API.php:1646                               Search::getDatas()
319525    src/Api/APIRest.php:191                            Glpi\Api\API->searchItems()
319526    apirest.php:58                                     Glpi\Api\APIRest->call()
319527    {"user":"499@svweb","mem_usage":"0.000\", 5.01Mio)"}
319528  [2022-06-30 16:31:36] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
319529    *** MySQL query error:
319530    SQL: SELECT * FROM `glpi_users` WHERE `id` = '412'
319531    Error: MySQL server has gone away
319532    Backtrace :
319533    src/DBmysqlIterator.php:110
319534    src/DBmysql.php:1048                               DBmysqlIterator->execute()
319535    src/DbUtils.php:1617                               DBmysql->request()
319536    inc/db.function.php:456                            DbUtils->getUserName()
319537    src/Search.php:6352                                getUserName()
319538    src/Search.php:1687                                Search::giveItem()
319539    src/Search.php:447                                 Search::constructData()
319540    src/Api/API.php:1646                               Search::getDatas()
319541    src/Api/APIRest.php:191                            Glpi\Api\API->searchItems()
319542    apirest.php:58                                     Glpi\Api\APIRest->call()
319543    {"user":"499@svweb","mem_usage":"0.000\", 5.01Mio)"}

`

**Comment by mulbzh** [comment]
so, i found ! you can close. The high CPU is because of script connected to the API

**Comment by trasher** [comment]
Closing as not a glpi issue
