### ISSUE TITLE
View returned after create item in a popup

### ISSUE THREAD

**Issue by raultak** [glpi-project/glpi#12066]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Hello all,
Since version 10.0.0 I have noticed the following behavior and did not find an issue related.

When configuration "Go to created item after creation" is set to "yes".

![image](https://user-images.githubusercontent.com/14891483/176720645-95dc8e94-5e14-4670-84b6-472b061e06d7.png)

Adding a new item using the popup in a dropdown list, the return view show all the frontend interface instead only the new created item form:

![image](https://user-images.githubusercontent.com/14891483/176762812-d380cdd2-da3b-48f3-abc9-f0fd3b901cf3.png)

When configuration "Go to created item after creation" is set to "no".
The popup works as expected returning to a new item form:

![image](https://user-images.githubusercontent.com/14891483/176761806-f1564feb-454b-40e4-bac1-eb2ede88c42e.png)

### Steps To reproduce

1. Setup > General > Default values > Go to created item after creation = yes.
2. On any dropdown list, click the "+" icon to add a new item.
3. Add a new item in the popup form.
4. The return view will show all the frontend interface instead the new created item form.

### Your GLPI setup information

Operating system: Linux 4.15.0-188-generic #199-Ubuntu SMP Wed Jun 15 20:42:56 UTC 2022 x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="5M" 
Software: Apache/2.4.29 (Ubuntu) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.38-0ubuntu0.18.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Host info: Localhost via UNIX socket

**Comment by cconard96** [comment]
Hello,
This should be fixed by #12069

**Comment by raultak** [comment]
> Hello, This should be fixed by #12069

Thank you, @cconard96 !
