### ISSUE TITLE
Update 9.3.3 to 10.0.2

### ISSUE THREAD

**Issue by xstocler** [glpi-project/glpi#12067]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.3.3

### Bug description

I'm using Debian 10
Hestiacp platform with nginx/php8.0-fpm

I have a copy of the 9.3.3 database, it was restored to a new (test) database for the migration

Extract version 10.0.2 files

When accessing the GLPI, the GLPI SETUP page was submitted.

Proceeding with GLPI SETUP , the update option was selected

![image](https://user-images.githubusercontent.com/29358084/176767241-4d1580cb-54cd-4792-8006-487e4bfc8f58.png)

When continuing, it was submitted to connect to the database and finally, the update

It showed the following error:
Could not rename table glpi_changes_projects (ok) to glpi_itils_projects (nok)!

When checking the glpi_itils_projects table, it exists in the database, although it is empty.
Then I redid the update process and deleted the glpi_itils_projects table

It's showing another error
![image](https://user-images.githubusercontent.com/29358084/176769360-28d7ac0c-d2fe-40a5-b585-74cbd50be7bf.png)

Can you help me find a solution?

**Comment by vollkommenIrrelevant** [comment]
Maybe you can try to upgrade first to 9.5.8 and then to 10.0.2?

**Comment by xstocler** [comment]
Performing some manual actions in the bank, it was possible to update.

**Comment by cedric-anne** [comment]
> it was restored to a new (test) database for the migration

I guess problem was here. Restoring a dump over a non empty database will create a mix between old and new tables and migration process cannot handle this.
