### ISSUE TITLE
Empty email replies (followups) when using CLI (cron)

### ISSUE THREAD

**Issue by oneill2john** [glpi-project/glpi#12074]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

My email template consists of the following HTML code:

```
<p>TEST TICKET TEMPLATE</p>
<p>##FOREACHtimelineitems##</p>
<div class="description b"><br><strong> [##timelineitems.date##]</strong><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.author## </span> <span style="color: #000000; font-weight: bold;">##timelineitems.author##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.description## </span> <span style="color: #000000;">##timelineitems.description##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.date## </span> <span style="color: #000000; font-weight: bold;">##timelineitems.date##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.position## </span><span style="color: #000000; font-weight: bold;"> ##timelineitems.position##</span></div>
<div class="description b"><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.type## </span><span style="color: #000000; font-weight: bold;"> ##timelineitems.type##</span></div>
<div class="description b"><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.typename## </span> <span style="color: #000000; font-weight: bold;">##timelineitems.typename##</span></div>
<p>----------------------------------------------------------</p>
<p>##ENDFOREACHtimelineitems##</p>
<div class="description b">##lang.ticket.numberoffollowups## : ##ticket.numberoffollowups##</div>
```

I'm using **CLI Run Mode** for all my Automatic actions. Cron job is properly configured.

**The problem is** - every time a user sends a reply email to tickets, those replies come as empty blank emails.
If I as administrator send back my reply, then user receives empty email as well.
However, I can see all replies in Assistance > Tickets, they are all there.
Only notification emails are empty.

If I don't use CLI cron, and instead of that if I manually run "mailgate" and "queuednotification", in this case all mail email replies come normal with all content in it, as expected.

I have posted this problem on GLPI Support forum where you can see in detail about this problem and what have I tried to solve this so far:
https://forum.glpi-project.org/viewtopic.php?pid=493177#p493177 

### Steps To reproduce

1. Create new "Ticket followups" notification template
2. Add this HTML source code
```
<p>TEST TICKET TEMPLATE</p>
<p>##FOREACHtimelineitems##</p>
<div class="description b"><br><strong> [##timelineitems.date##]</strong><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.author## </span> <span style="color: #000000; font-weight: bold;">##timelineitems.author##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.description## </span> <span style="color: #000000;">##timelineitems.description##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> ##lang.timelineitems.date## </span> <span style="color: #000000; font-weight: bold;">##timelineitems.date##</span><br><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.position## </span><span style="color: #000000; font-weight: bold;"> ##timelineitems.position##</span></div>
<div class="description b"><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.type## </span><span style="color: #000000; font-weight: bold;"> ##timelineitems.type##</span></div>
<div class="description b"><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">##lang.timelineitems.typename## </span> <span style="color: #000000; font-weight: bold;">##timelineitems.typename##</span></div>
<p>----------------------------------------------------------</p>
<p>##ENDFOREACHtimelineitems##</p>
<div class="description b">##lang.ticket.numberoffollowups## : ##ticket.numberoffollowups##</div>

```

3. Configure your "mailgate" and "queuednotification" to use CLI (cron job)
4. Create a new ticket and start sending replies to it using your email client 

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.2 (/glpi => /home/elitetig/public_html/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux vukovar.totohost.hr 3.10.0-962.3.2.lve1.5.68.el7.x86_64 #1 SMP Wed Apr 6 11:12:23 UTC 2022 x86_64
PHP 8.1.7 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, clos_ssa, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, i360, iconv, imap, intl, json, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, sockets, sodium, sqlite3, standard,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="4M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.66 Safari/537.36 Edg/103.0.1264.44
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB-cll-lve
	Server SQL Mode: 
	Parameters: elitetig_glpi@localhost/elitetig_glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.7) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
The log file has been created successfully.
Write access to /home/elitetig/public_html/glpi/files/_cache has been validated.
Write access to /home/elitetig/public_html/glpi/config has been validated.
Write access to /home/elitetig/public_html/glpi/files/_cron has been validated.
Write access to /home/elitetig/public_html/glpi/files has been validated.
Write access to /home/elitetig/public_html/glpi/files/_dumps has been validated.
Write access to /home/elitetig/public_html/glpi/files/_graphs has been validated.
Write access to /home/elitetig/public_html/glpi/files/_lock has been validated.
Write access to /home/elitetig/public_html/glpi/files/_pictures has been validated.
Write access to /home/elitetig/public_html/glpi/files/_plugins has been validated.
Write access to /home/elitetig/public_html/glpi/files/_rss has been validated.
Write access to /home/elitetig/public_html/glpi/files/_sessions has been validated.
Write access to /home/elitetig/public_html/glpi/files/_tmp has been validated.
Write access to /home/elitetig/public_html/glpi/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/elitetig/public_html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /home/elitetig/public_html/glpi
GLPI_CONFIG_DIR: /home/elitetig/public_html/glpi/config
GLPI_VAR_DIR: /home/elitetig/public_html/glpi/files
GLPI_MARKETPLACE_DIR: /home/elitetig/public_html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /home/elitetig/public_html/glpi/files
GLPI_CACHE_DIR: /home/elitetig/public_html/glpi/files/_cache
GLPI_CRON_DIR: /home/elitetig/public_html/glpi/files/_cron
GLPI_DUMP_DIR: /home/elitetig/public_html/glpi/files/_dumps
GLPI_GRAPH_DIR: /home/elitetig/public_html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /home/elitetig/public_html/glpi/files/_locales
GLPI_LOCK_DIR: /home/elitetig/public_html/glpi/files/_lock
GLPI_LOG_DIR: /home/elitetig/public_html/glpi/files/_log
GLPI_PICTURE_DIR: /home/elitetig/public_html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /home/elitetig/public_html/glpi/files/_plugins
GLPI_RSS_DIR: /home/elitetig/public_html/glpi/files/_rss
GLPI_SESSION_DIR: /home/elitetig/public_html/glpi/files/_sessions
GLPI_TMP_DIR: /home/elitetig/public_html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /home/elitetig/public_html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /home/elitetig/public_html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /home/elitetig/public_html/glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/home/elitetig/public_html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/elitetig/public_html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/elitetig/public_html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/home/elitetig/public_html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/elitetig/public_html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/elitetig/public_html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/elitetig/public_html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/home/elitetig/public_html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/elitetig/public_html/glpi/vendor/sabre/http/lib)
sabre/uri in (/home/elitetig/public_html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/home/elitetig/public_html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/elitetig/public_html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/elitetig/public_html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/elitetig/public_html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/elitetig/public_html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/elitetig/public_html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/elitetig/public_html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/home/elitetig/public_html/glpi/vendor/symfony/console)
scssphp/scssphp in (/home/elitetig/public_html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/elitetig/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/elitetig/public_html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/elitetig/public_html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/elitetig/public_html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/elitetig/public_html/glpi/vendor/ramsey/uuid/src)
psr/log in (/home/elitetig/public_html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/elitetig/public_html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/home/elitetig/public_html/glpi/vendor/psr/cache/src)
league/csv in (/home/elitetig/public_html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/home/elitetig/public_html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/elitetig/public_html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/elitetig/public_html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/elitetig/public_html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/elitetig/public_html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/elitetig/public_html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/elitetig/public_html/glpi/vendor/symfony/cache)
html2text/html2text in (/home/elitetig/public_html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/home/elitetig/public_html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/elitetig/public_html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/home/elitetig/public_html/glpi/vendor/twig/twig/src)
twig/string-extra in (/home/elitetig/public_html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	oauthimap            Name: Oauth IMAP                     Version: 1.4.0      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by oneill2john** [comment]
Any progress on this one?

**Comment by cedric-anne** [comment]
I created a ticket and add a followup, and, using this template, I get following notification:
![image](https://user-images.githubusercontent.com/33253653/178284438-d448fa8b-c12b-4f5c-835a-45c825bf5a76.png)

The only thing I can tell is that ticket description is not considered as a timeline item and should be added manually in your notification, but I cannt reproduce the "empty blank email" issue.

**Comment by oneill2john** [comment]
Did you reply to that ticket using email client?

I have this problem even if I'm using default GLPI notification templates, not just my custom templates.

Please take a look at this screenshot: https://i.postimg.cc/qMNWSmns/Untitled-2.jpg
As you can see, for this test I used default GLPI notification template but email notifications is empty. You can in screenshot that this ticket should have 16 follow-ups, but they are not showing up (only initial ticket description).
Follow-ups are visible in GLPI web under Assistance > Tickets, but not in email notifications.

I'm using Microsoft Outlook as email client, just like the rest of my company and users who will use GLPI for sending tickets. But so far I cannot implement GLPI in my environment until this notification problem is solved.

If you need any information about my setup, feel free to ask.

Thank you

**Comment by oneill2john** [comment]
Here's an update:
I have used this fix from https://github.com/glpi-project/glpi/pull/12208/files for my "src/CommonITILObject.php" file and now everything works.
No more blank email notifications.
