### ISSUE TITLE
New group in assignees problems

### ISSUE THREAD

**Issue by digisam1985** [glpi-project/glpi#12085]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.2

### Bug description

when assign to group not send an email notifications to the group after auto assign with rules.

### Steps To reproduce

1. SEND EMAIL TO RECIVER
2. GLPI RECOGNIZE THE RULE AND AUTO ASSIGN TO GROUP
3. EMAIL TO GROUP ASSIGN NOT START

**Comment by dwtz** [comment]
for me it also does not work in version 10.0.2 or the nightly build.

As a mandatory field I set a category in the simple view.

The rule is:
Criterion Condition Reason
Category - Complete name is intern-isms

Technician group Assign intern-isms

The group is added, but there is no notification to the technician group.
However, if I enter the group as a technician in a new ticket, I get the notifications.

**Comment by cconard96** [comment]
What recipients are configured for that notification (May be the "new group in assignees" notification)?
Setup > Notifications > Notifications > New group in assignees > Recipients tab.

**Comment by dwtz** [comment]
we have now changed the logic of creation.
Previously, we automatically assigned the ticket to a group via a category and "assigned to" was not taken into account in the mail notification. We did not use new ticket.

Now we use new ticket and have created a new rule, so it works.

presumably assigned to is now no longer done in two steps, but directly at creation, which led to a different behavior.

it works for us now.
in any case, the behavior has changed from 10.0.1 to 10.0.2.

**Comment by digisam1985** [comment]
> What recipients are configured for that notification (May be the "new group in assignees" notification)? Setup > Notifications > Notifications > New group in assignees > Recipients tab.

I have "group in charge of the ticket" and "technician in charge of the ticket"

With 10.0.3 is the same.

**Comment by fralla2** [comment]
Same problem on my side too (10.0.3)

**Comment by mikellewellynhgs** [comment]
I have the same issue after upgrading to 10.0.3 (from version 9.x), adding groups to assigned/watchers doesn't seem to trigger the new group in assignees or new group in observers notifications

**Comment by superafroboy** [comment]
I see the same behavior after updating from version 9.x to 10.0.3. When we add a group in observers or assigned to, it doesn't seem to trigger the "new group in assignees" or "new group in observers" notifications. I have tried recreating the notifications but it just doesn't seem to trigger the notification when selecting the "new group in assignees" event.

**Comment by fralla2** [comment]
FYI : On our side, we found out that the notification of new tickets for the technician in charge of the group was not set to recursive. This never was an issue prior to v10.0.x but I guess they now do a better job at entity restriction. 

We've putted it to recursive and now the technician in charge of the group automatically assigned to the ticket is notified at the ticket creation as it should...

You might want to check it on your side to make sure it's not the problem too.

**Comment by cedric-anne** [comment]
Hi,

See #11363.

Now, we consider that actors added from UI, by rules or by plugins on ticket creation are part of ticket creation. Information is so present in ticket creation notification (it was not present on GLPI 9.5).

I close this as it is not an issue.

Regards
