### ISSUE TITLE
Operating systems does not exists in dropdown list in the main computer page.

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#1208]
Hello!
using this function
http://prntscr.com/cx4abt
there: http://prntscr.com/cx4axp operating systems do not exist (with search cant find too)

( maybe bug in glpi/inc/computer.class.php  `function getSearchOptions() {`  http://prnt.sc/cx4c5y?)

**Comment by flegastelois** [comment]
Hi,
Can you provide your screenshots with "English" language ?

**Comment by Zegordo** [comment]
this is an english really
but with a littlie bit modified computer.class.php file
in any case, i did screenshots with default computer.class.php file:
1 http://prnt.sc/cx5xs8
2 http://prnt.sc/cx5y30
3 http://prnt.sc/cx5y6u 
4 http://prnt.sc/cx5yb8
same story.

**Comment by flegastelois** [comment]
Okay, duplicate #933
Already fixed by 93e0e99
