### ISSUE TITLE
Suggestion of rules for codesniffer

### ISSUE THREAD

**Issue by edgardmessias** [glpi-project/glpi#1209]
``` xml
  <!-- No white spaces after opening bracket and before closing bracket in IF -->
  <rule ref="PSR2.ControlStructures.ControlStructureSpacing" />

  <!-- White space after IF keyword -->
  <rule ref="Squiz.ControlStructures.ControlSignature" />

  <!-- White space after comma in function call -->
  <rule ref="Generic.Functions.FunctionCallArgumentSpacing" />

```

**Comment by trasher** [comment]
Sounds good to me :+1: 

A few other proposals:
```xml
<!--  Disallows the use of any deprecated functions -->
<rule ref="Generic.PHP.DeprecatedFunctions"/>

<!--  Makes sure that shorthand PHP open tags are not used. -->
<rule ref="Generic.PHP.DisallowShortOpenTag"/>

<!--  Enforces function comments and their format. -->
<rule ref="PEAR.Commenting.FunctionComment"/>

<!--  Checks that no perl-style comments (#) are used. -->
<rule ref="PEAR.Commenting.InlineComment"/>
```

Enabling function comment is probably a quite huge job...

**Comment by edgardmessias** [comment]
```xml
<!-- Not allow long array syntax. -->
<rule ref="Generic.Arrays.DisallowLongArraySyntax"/>
```

**Comment by edgardmessias** [comment]
And full PSR2 specification?

**Comment by edgardmessias** [comment]
For arrays:

```xml
  <!-- No long array syntax (PHP >= 5.4) -->
  <rule ref="Generic.Arrays.DisallowLongArraySyntax" />

  <!-- Array indentation -->
  <rule ref="Squiz.Arrays.ArrayDeclaration" />
```

**Comment by AnaelMobilia** [comment]
Hello,

Many PR for many CS... ;-)

I don't take 3 :
  - @trasher 
```
<!--  Enforces function comments and their format. -->
<rule ref="PEAR.Commenting.FunctionComment"/>
```
Yeah, it's a requierement to have a documentation, but on the preview of the work (and as I'm new on this project ;-)), I can't write so many documentation !

   - @edgardmessias 
```
<!-- No long array syntax (PHP >= 5.4) -->
  <rule ref="Generic.Arrays.DisallowLongArraySyntax" />
```
GLPI coding standards give both short and long array syntax.
@remicollet suggest on ae2cd9c to use array().
So .... I duno !

```
  <!-- Array indentation -->
  <rule ref="Squiz.Arrays.ArrayDeclaration" />
```
is linked to previous ;-)

Regards,
Anael

**Comment by trasher** [comment]
Hello,

> I can't write so many documentation !

Indeed :)
And this is finally probably not a good idea to implement this rule, since we'll have to have every method documented... Even those inherited. For those ones, this is not a requirement since it will be retrieved from parent on generation.
A check for docblock formatting would be interesting anyways; I don't know if that rule exists standalone.

>  @remicollet suggest on ae2cd9c to use array().

Hum... I'm not sure this is a suggestion; it does not seem we have any rules actually for arrays. We can ignore this one too I guess.

@AnaelMobilia thankis for the great job you've done on all this!

**Comment by trasher** [comment]
PR #1117 also implements some CS checks.

**Comment by trasher** [comment]
I've begin to work on a possible solution for the comments:
https://github.com/TECLIB/glpi/tree/cs-comments

Changes will be very huge; as a first step, I maybe can set that rule as Warning and not error... I'll think about that :)

**Comment by trasher** [comment]
@edgardmessias should be a good idea; since I actually copy/paste ruleset from core to plugins... :)

**Comment by edgardmessias** [comment]
An example project:
Https://github.com/phpmyadmin/coding-standard

**Comment by trasher** [comment]
A separate project has been created, see https://github.com/glpi-project/coding-standard
