### ISSUE TITLE
Attribution and change of category in same action

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#121]
Attribution triggers first, so notification on attribution (from behaviors plugins) contains out of date category

**Comment by yllen** [comment]
I don't understand the problem. Can you explain more?
What do you mean by "contains out of date category"?

**Comment by orthagh** [comment]
On existing ticket, 
If you change category and you assign the ticket in same action, the assign will trigger first.

And notification from assignment (from behavior plugin) will show a outdated category.
Maybe another fields concerned.

**Comment by yllen** [comment]
In GLPI you can't assign a ticket and change the category in the same action.
When you change a category, you must click on Update to save the action.
For actors part, when you select the actor you validate the action.

**Comment by yllen** [comment]
The only solution is to change order of update in the core of GLPI.
Behaviors is based on tickets_users and the link tickets_users is done before change of ticket's fields.

**Comment by remicollet** [comment]
I don't think changing save order worth the risk to break everything.

**Comment by orthagh** [comment]
Not a critical request, and my requester changes his workflow after explanation. 
So i agree on complexity.

I close
