### ISSUE TITLE
Uncaught Exception Error: Class 'useremail' not found

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#12119]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Having a recurrent ticket without a requester will trigger endless recreation of the tickets and plenty cron errors.

When you add a requester to the recurrenten ticket template the error stopps.

### Relevant log output

```shell
[2022-07-02 19:35:05] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'useremail' not found in /var/www/helpdesk/src/NotificationEventAbstract.php at line 154
 Backtrace :
 src/NotificationEvent.php:187                      NotificationEventAbstract::raise()
 src/Ticket.php:2123                                NotificationEvent::raiseEvent()
 src/CommonDBTM.php:1305                            Ticket->post_addItem()
 src/CommonITILRecurrent.php:581                    CommonDBTM->add()
 src/CommonITILRecurrentCron.php:92                 CommonITILRecurrent->createItem()
 src/CronTask.php:1018                              CommonITILRecurrentCron::cronRecurrentItems()
 front/cron.php:84                                  CronTask::launch()
```

**Comment by cedric-anne** [comment]
The line indicated in your error stacktrace does not have any mention to a `useremail` class or a `email` array key.

https://github.com/glpi-project/glpi/blob/10873706f388795a1d0d72a028eb4ceba36f7169/src/NotificationEventAbstract.php#L154

Are you using a patched version of GLPI ?
