### ISSUE TITLE
Tasks not displayed on Central List

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12124]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Tasks todo are not displayed on central view (both personal or group)

### Steps To reproduce

1. Create Ticket
2. Create Task assign to yourself
3. Check Personal view

### Your GLPI setup information

Clean GLPI 10.0.2 w/o plugins

**Comment by cconard96** [comment]
Completed in https://github.com/glpi-project/glpi/pull/12125.
