### ISSUE TITLE
Changes to recipients not possible for notification target "Check plugin updates"

### ISSUE THREAD

**Issue by jm-sbe** [glpi-project/glpi#12136]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Applying changes to the recipients list on the notification object "**Check plugin updates**" is not possible, see image below:

![image](https://user-images.githubusercontent.com/88610847/177317536-607ec797-c08c-4e96-8b08-a8a208746b88.png)

In difference to other notification targets the additional group "**Gruppe: IT-Betreuer**" from the screenshot can't be saved. Maybe related to the SQL table value `glpi_notifications.itemtype = "Glpi\Marketplace\Controller"` with some backslashes in it.

### Relevant log output

```shell
[2022-07-05 12:57:33] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function add() on bool in /var/www/html/glpi/src/NotificationTarget.php at line 482
  Backtrace :
  front/notificationtarget.form.php:40               NotificationTarget::updateTargets()

[2022-07-05 12:57:36] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "itemtype" in /var/www/html/glpi/src/NotificationTarget.php at line 452
  Backtrace :
  front/notificationtarget.form.php:40               NotificationTarget::updateTargets()
```

### Steps To reproduce

1. Go to https://glpi/front/notification.php
2. Select "Check plugin updates"
3. Click "Recipients"
4. Try to make a change -> not possible

**Comment by cedric-anne** [comment]
Should be fixed by #12142.
