### ISSUE TITLE
GLPI_10.0.2 : unable to solve a ticket

### ISSUE THREAD

**Issue by DooBio** [glpi-project/glpi#12131]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.2

### Bug description

Since the update to 10.0.2 I can no longer solve certain tickets.

### Relevant log output

```shell
I deleted the log files, rebooted apache, carried out my resolution action again and no php or sql file creation error

in Acces- errors.log  i a find this : 

User ID: 581 tried to access or perform an action on /glpi/front/ticket.form.php?id=2022003005 with insufficient rights. Additional information: No additional information given
	Stack Trace:
		/var/www/glpi/src/CommonDBTM.php:6240 displayRightError()
		/var/www/glpi/src/CommonDBTM.php:6328 displayAccessDeniedPage()
		/var/www/glpi/front/ticket.form.php:259 displayFullPageForItem()

```

### Steps To reproduce

- On this example I made 4 attempts with 2 different users

![image](https://user-images.githubusercontent.com/32511461/177123775-7ebfe510-441a-478b-a7bc-d09ba7756769.png)

- When I try to force it on the right menu Ticket by passing the status Processing (Assigned) to solved after clicking on Save it changes the status to Processing (Assigned). I tried with another status but it's the same.

![image](https://user-images.githubusercontent.com/32511461/177124378-ad8b2ce7-7763-4bf8-b84d-26ac4fc550b6.png)

- Same result with the Actions button

![image](https://user-images.githubusercontent.com/32511461/177124869-17ed0cd6-6ac4-4885-b073-b39a981f2baa.png)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.2 (/glpi => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux SRV-Intranet 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64
PHP 8.1.7 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="2000M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20000M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at 10.1.125.201 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.8-MariaDB-1:10.6.8+maria~buster
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.1.7) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.8) is supported.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://10.1.100.1', Port: '389', BaseDN: 'DC=biopole66,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'administrateur@biopole66.local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (glpi@biopole66.com@ssl0.ovh.net)

</details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertes                        Version: 1.10.4     State: Installed / not activated               
		Install Method: Marketplace
	additionalalerts     Name: Alertes supplémentaires        Version: 2.4.0      State: Installed / not activated               
		Install Method: Marketplace
	webapplications      Name: Applications Web               Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	financialreports     Name: Arrêtés du parc                Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Not installed                           
		Install Method: Marketplace
	screenshot           Name: Capture d'écran                Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace
	positions            Name: Cartographie                   Version: 6.0.1      State: Installed / not activated               
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.16.0     State: Installed / not activated               
		Install Method: Marketplace
	accounts             Name: Comptes                        Version: 3.0.2      State: Installed / not activated               
		Install Method: Marketplace
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.0      State: Installed / not activated               
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Marketplace
	purchaserequest      Name: Demande d'achat                Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	errorlog             Name: ErrorLog                       Version: 0.0.1      State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Installed / not activated              
		 Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.1 State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.0.1      State: Installed / not activated               
		Install Method: Marketplace
	geninventorynumber   Name: Génération de numéros d'invent Version: 2.8.0      State: Installed / not activated              
		 Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.12.1     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.9.0      State: Installed / not activated               
		Install Method: Marketplace
	tag                  Name: Gestion des tags               Version: 2.9.2      State: Installed / not activated               
		Install Method: Marketplace
	dev                  Name: GLPI Development Helper        Version: 2.0.0      State: Installed / not activated               
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.3      State: Enabled                                 
		Install Method: Marketplace
	glpidashboard        Name: glpidashboard                  Version: 1.0.1      State: Not installed                           
		Install Method: Manual
	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.0      State: Installed / not activated               
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	karastock            Name: Karastock                      Version: 1.3.1      State: Installed / not activated               
		Install Method: Manual
	tasklists            Name: Liste des tâches               Version: 2.0.1      State: Installed / not activated               
		Install Method: Marketplace
	metademands          Name: Meta-Demandes                  Version: 3.2.0      State: Installed / not activated               
		Install Method: Marketplace
	metabase             Name: metabase                       Version: 1.3.0      State: Installed / not activated               
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Marketplace
	myobject             Name: myobject                       Version: 0.0.1      State: Not installed                           
		Install Method: Manual
	mod                  Name: Plugin Zizou                   Version: 2.1.0      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.0      State: Installed / not activated               
		Install Method: Marketplace
	purgelogs            Name: Purge de l'historique          Version: 1.3.0      State: Enabled                                 
		Install Method: Manual
	stab                 Name: Split Timeline Action Buttons  Version: 1.0.1      State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.2      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

### Anything else?

Tickets are created with the formCreator 2.13.0-rc.1 , but hey I had no problem before the switch to 10.0.2

I deactivated Formcrator to do a test with the same user at creation and at resolution, I have the same result

**Comment by DooBio** [comment]
Thanks @blippercop 🙏🙏🙏

We don't perform the same action but the purpose and the same on your ticket https://github.com/glpi-project/glpi/issues/12120

I tested your solution to disable the assignment rules and indeed it works very well.

I hope you can find a solution because this operation is very practical to assign automatically according to a form

**Comment by DooBio** [comment]
for ticket assignments 3 importants rules

**Comment by cedric-anne** [comment]
Hi,

Could you check if #12149 resolves your issue ?
