### ISSUE TITLE
No more display in the "applicant" column since the upgrade to 10.0.2

### ISSUE THREAD

**Issue by Gor3pig** [glpi-project/glpi#12147]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

No more display in the "applicant" column since the upgrade to 10.0.2.

![01](https://user-images.githubusercontent.com/42821532/177504420-8c9741b3-af1e-4a99-9a61-695838b0e74c.jpg)

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on current 10.0/bugfixes branch, maybe #12130 and/or #12137 are fixing this issue.
Could you try to reproduce on a test instance based on [GLPI nightly build](https://nightly.glpi-project.org/glpi/)? If you are able to reproduce, could you detail steps to reproduce ?

**Comment by Gor3pig** [comment]
> Hi,
> 
> I cannot reproduce on current 10.0/bugfixes branch, maybe #12130 and/or #12137 are fixing this issue. Could you try to reproduce on a test instance based on [GLPI nightly build](https://nightly.glpi-project.org/glpi/)? If you are able to reproduce, could you detail steps to reproduce ?

This is a production GLPI, I can't afford to switch to Nightly unfortunately. But if it can help you, I had a discussion on the "bug" channel of the Discord, and another French guy has exactly the same problem. Maybe it's related to the language?

**Comment by Gor3pig** [comment]
The old tickets (even those still open) have the column "Applicant" filled in. Only the newly generated tickets have visually no applicants.

Once in the ticket on the other hand, you have the applicant in the header :

![02 jpg](https://user-images.githubusercontent.com/42821532/177716195-5039dd03-b981-480a-9e5c-a08100a2394f.jpg)

**Comment by cedric-anne** [comment]
Could you detail how you reproduce ? Is the ticket created from simplified interface, or from a plugin, ... ? What is the "Me pré-selectionner en tant que demandeur à la création d'un ticket" configuration value or requester ?

Also, have you some active plugins ? Could you try to deactivate them for a short time to see if the bug come from their side ?

**Comment by Gor3pig** [comment]
I have only 4 active plugins:

- Screenshot by Curtis Conard
- Object management by Walid Nouh
- GLPI Inventory
- Shell commands by Xavier Caillaud, Infotel

Tickets are created with the standard interface (not the simplified one) and without dedicated plugins.

To reproduce :

- A "Self Service" user connects to GLPI (Ldap account)
- The standard ticket form (blank) is directly visualized by the user
- The user fills in all the necessary fields: Category, Location, etc.
- The field "requester" is automatically filled with its own account
- The field "assigned to" is automatically filled with the account of the IT technician.
- Validation of the form with the "Add" button.


Note:

- There are 15 hidden fields in the ticket template:

![03 jpg](https://user-images.githubusercontent.com/42821532/177718728-03635e87-be8c-4475-877e-8a0f2fcaba6d.jpg)

**Comment by Gor3pig** [comment]
Interesting test I just did:

- If I create a ticket with my admin account: the Applicant column is filled in

- If I create a ticket with a Self-Service user, the Applicant column is blank

I also tested without any plugins except GLPI Inventory, same problem
