### ISSUE TITLE
How to synchronise GLPI planning with outlook ?

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1214]
Please, do you have a procedure to do that ?

Thank you for your help

GLPI 9.1

**Comment by tomolimo** [comment]
Go to the 'PLanning' view, and 
![image](https://cloud.githubusercontent.com/assets/7569958/19648040/11af4170-9a01-11e6-975f-e30909ee0baa.png)
Export in webcal and open the exported file with Outlook

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/19648138/76597514-9a01-11e6-81f7-8cb0658c6811.png)

**Comment by tomolimo** [comment]
which version of Outlook do you use?

**Comment by satyan01** [comment]
2010

**Comment by tomolimo** [comment]
Did you export ical or webcal?

**Comment by satyan01** [comment]
webcal

**Comment by tomolimo** [comment]
try ical!

**Comment by satyan01** [comment]
it works with ICAL but how to synchronize ?

**Comment by tomolimo** [comment]
is done by outlook

**Comment by satyan01** [comment]
ok I will see

**Comment by satyan01** [comment]
So If I delete in GLPI or Add something it will be synchronised in outlook ?

**Comment by tomolimo** [comment]
See outlook doc to refresh calendar periodically

**Comment by satyan01** [comment]
Thank you so much !

**Comment by tomolimo** [comment]
you're welcome

**Comment by satyan01** [comment]
Hello, Unfortunately the synchronization does not work, If I modify something on each side, other side is not updated

**Comment by halouc** [comment]
I have the same problem !
Tested with:
Zimbra  ( Glpi 0.90.4 = OK, GLPI 9.1 = KO )
Outlook 2010 and 2014 ( Glpi 0.90.4 = OK, GLPI 9.1 = KO )

**Comment by denzoil2** [comment]
Hi. 
@Satyan01: Please note that the synchronisation way is only GLPI => outlook.
@admins: There is a bug with GLPI 0.91: webcal doesn't work anymore. 
If I test with Evolution Mail the error message is that the file format is wrong. It is ok with 0.90.

**Comment by denzoil** [comment]
Sorry I wrote 0.91 but i meant GLPI 9.1 of course.
Doesn't work anymore with Outlook 2010

**Comment by orthagh** [comment]
Duplicate of #1257

**Comment by aze789** [comment]
Hello,
Do you know if it's possible to synchronize automatically outlook with glpi ? ( add an appointment on outlook and can be see on glpi )

**Comment by aze789** [comment]
up

**Comment by orthagh** [comment]
@aze789 cf https://glpi.userecho.com/communities/1/topics/699-import-and-sync-planning-glpi-side
It's an evolution.

**Comment by aze789** [comment]
@orthagh What am I suppose to do with that lmao

**Comment by orthagh** [comment]
Waiting for someone to develop it (or not).
The feature doesn't exists in GLPI.

On your side, you can vote for the feature to improve it's visibility

**Comment by Eisbaeeer** [comment]
Actually don´t know how it is exactly to do, but all enterprise API´s using the EWS to exchange that. Perhaps there is a programmer who can realize that?
In other systems, they using the autodiscover dns feature to get connected. Second is to use a managed service account with full access rights to the mailboxes and to connect to exchange and the API using the mail-address to synchronize the calendar informations.

**Comment by dxdemetriou** [comment]
Tried this:
https://github.com/aluxnimm/outlookcaldavsynchronizer/

and seems to be the only alternative for Outlook.
