### ISSUE TITLE
Dropdown::show() does not create hidden elements for read-only fields

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12156]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Dropdown::show() does not create hidden elements for read-only fields:
https://github.com/glpi-project/glpi/blob/7e0a2407051d8cd24953847eb439ce7846524f65/src/Dropdown.php#L180-L184

But for example Dropdown::showFromArray() does:
https://github.com/glpi-project/glpi/blob/7e0a2407051d8cd24953847eb439ce7846524f65/src/Dropdown.php#L2071-L2080

Is there are reason for this inconsistency? 

It causes some issues in case field is supposed to be read-only and required at the same time as it is not sent to the form..

**Comment by VladoTTX** [comment]
Guys, do you agree this is a bug?
If yes, I can submit a PR for fixing the behavior..

**Comment by trasher** [comment]
This sounds like a bug yes

**Comment by cedric-anne** [comment]
@VladoTTX 

Could you check #13833 ?

**Comment by cedric-anne** [comment]
Fixed by #13833.
