### ISSUE TITLE
Misplaced label for ticket history - yesterday vs 1 day

### ISSUE THREAD

**Issue by lfardin** [glpi-project/glpi#12152]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0,2

### Bug description

The ticket history displays the label "yesterday" when it should use "1 day ago", as you can see ate the image:

![image](https://user-images.githubusercontent.com/56692658/177538392-aa0f16e1-958f-4fb7-aba5-89f6cc6edbf4.png)
****
At the example, today is July 6th, so "yesterday" is not the same as the real date of the event: July 4th

**Comment by lfardin** [comment]
Since this issue was registered using as base the current version (10.0..2), yes, the problem persists at the current version.

**Comment by lfardin** [comment]
The problem still exists.

checking the function timestampToRelativeStr($ts) at the file src/Html.php and also the function relativeDate(str) at js/common.js:

Lokks like this condition here causes the misplaced label, since 1 day diff  when rounded not always means yesterday:

src/Html.php:
 **if ($day_diff == 1) {
                return __('Yesterday');
            }**

js/common.js:
            **: (tmp = Math.round(d)) === 1 ? __('yesterday')**

**Comment by cedric-anne** [comment]
Fixed by #13435.

**Comment by lfardin** [comment]
@cedric-anne , checking issue #13435 , it seems the chance was made at the file src/Html.php.
The same miscalculation is used at this javascript file: js/common.js
There's no need to fix this?
