### ISSUE TITLE
Data Center - Server room - Impact analysis - bug while screening all options

### ISSUE THREAD

**Issue by PCz-Rover-Team** [glpi-project/glpi#12165]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

Every time, when I open "All" option at the left bar to see every section on one screen I see this bug. Impact analysis preview is mixed with other sections and I am unable to see anything.  When I preview only Impact analysis the bug does not happen.
Same bug happens to every of my co-workes.

![Screenshot_39](https://user-images.githubusercontent.com/93161666/177742557-87d8f93f-4f63-40c0-9705-8e22fc7003de.png)

**Comment by cconard96** [comment]
I do not see this issue in GLPI 10.
9.5 is not really supported anymore beyond major security fixes.
