### ISSUE TITLE
takeintoaccount_delay_stat is not accurate measure, if using Calendars with Active hours

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12167]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

I'll not repeat here same description but please check my previous issue #11109 which was recently closed.
Issue is that with calendar with active hours you don't have exact time of take into account (it if is taken into account during in-active time) also statistics is not displayed correctly.
I would like to ask  whether you agree with fix using new field "takeintoaccountdate" in glpi_tickets as described in #11109 and whether you would accept such PR. 

### Steps To reproduce

1. Create SLA with calendar 8x5 using TTO in hours
2. Create ticket during Inactive time.
3. Attach SLA to the ticket
4. Take into account during Active time.
5. Check the Ticket Statistics

### Your GLPI setup information

10.0.2

**Comment by VladoTTX** [comment]
Guys, would you agree on adding new field 'takeintoaccountdate' to the glpi_tickets to fix the issue?
I'll start working on PR if this is acceptable for the project.. 
Not sure whether it could be accepted to 10.0 or 10.1?

**Comment by trasher** [comment]
I would agree for a new field, but I'm maybe not the best one to answer that. @orthagh is not available for a few days, he'll probably answer when he'll be back. maybe @cedric-anne has an idea too.

I'm not sure for the branch to target; since this seems to fix a bug. Globally speaking, we try to avoid shcema changes in minor releases.

**Comment by VladoTTX** [comment]
Thanks, I will submit a PR for 10.0/bugfixes and if needed I'll update for the main tree

**Comment by cedric-anne** [comment]
Fixed by #12613.
