### ISSUE TITLE
Cannot update to 9.5.8

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#12160]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

When trying to update from 9.5.7 to 9.5.8 I couldn't and a blank page is showing, using php bin/console db:update I get:
+-----------------------+----------+--------+
|                       | Current  | Target |
+-----------------------+----------+--------+
| Database host         | myGLPIDatabaseHost  |        |
| Database name         | MyglpiDataBase |        |
| Database user         | myGlpiUserDB |        |
| GLPI version          | 9.5.7    | 9.5.8  |
| GLPI database version | 9.5.7    | 9.5.7  |
+-----------------------+----------+--------+
No migration needed.

### Steps To reproduce

1. Backup config, files, plugins, marketplace folders from my 9.5.7 version
2. Delete glpi folder
3. Download glpi version 9.5.8 and replace with the correct location
4. Restore config, files, plugins, marketpace folders to glpi 9.5.8
5. Trying to navigate on the GLPI Portal Web is impossible, a blank page is showing up. Also I tried to use on web /install/update.php but I couldn't update
6. Trying to use php bin/console db:update but it said "No migration needed"

**Comment by trasher** [comment]
Please provide relevant logs for blank page.

**Comment by jcervantes-sipecom** [comment]
I solved it, I have just to put the folder with version 9.5.8 as it per default first, without restore config, files, plugins, and marketplace folders. 

So The installation part begin, later asking for database information, so it create again the file config_db.php, and finnally warning for glpicrypt.key, just copy this file in config folder, and the database upgrade to 9.5.8

And then when it finished, I restored files, plugins, and marketplace folder.
