### ISSUE TITLE
Category shortcuts do not redirect to the right place

### ISSUE THREAD

**Issue by picinformatique** [glpi-project/glpi#12175]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Since the update of the presentation of the knowledge base, it is impossible to return directly to a category folder. From a page of a knowledge base document, when we click on the shortcuts bearing the name of the category, we are redirected to the main page of the knowledge base.

### Steps To reproduce

1. Go to the knowledge base
2. Go to a knowledge base category
3. Go to a card (page) of the knowledge base of a category
4. On the knowledge page click on the name of the category
5. You return to the main page of the knowledge base section (outside the category)

**Comment by WebGregGit** [comment]
I confirm.
