### ISSUE TITLE
the spell checker no longer works after updating to version 10

### ISSUE THREAD

**Issue by picinformatique** [glpi-project/glpi#12174]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

the spell checker no longer works after updating to version 10.
when we create tickets, we could correct the spelling with the chrome browser on older versions of GLPI. Since the text editor has been modified we can no longer use the spell checker when a word is underlined in red.

I think the new text editor is blocking the chrome browser spell checker, because a right click function has been added.

**Comment by cconard96** [comment]
Ctrl + right click will activate the browser's context menu.
