### ISSUE TITLE
No download link in inventory informations for NetDiscovery & NetInventory of Network switch

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#12179]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

When I perform NetworkDiscovery task, The target device (switch) is found.
SNMP Credentials link to de IP Range are used for SNMP Query.
Device information are send to glpi Server and import rules are processed.
The Device (Netgear Switch) is already register in newtwork device. -> The update rule is verified to update this device
![image](https://user-images.githubusercontent.com/78087722/178026640-52de6153-7671-468d-ba94-de709b7c6f6c.png)
But collected informations are not updated and it is not possible to download the inventory file xml 
![image](https://user-images.githubusercontent.com/78087722/178027191-ef39ae25-b26b-4e8c-8753-954a67098790.png)
Also, in the glpi_networkequipments table, the last_inventory_update, snmpcredentials_id fileds are not updated.
![image](https://user-images.githubusercontent.com/78087722/178027533-b4dc4936-861c-475a-b4d2-dc8e109a3143.png)

I have test with glpi-agent 1.3-1 and 1.4-1 - Glpi version 10.0.2 - Glpi-inventory Version 10.0.3
No errors found in log files.

### To reproduce

Do Network Discorvery task to target Network device.

### Expected behavior

It seems than when network device is found and update, SNMP Credentials needed to NetInventory are registrer. 

### Operating system

Linux

### GLPI Agent version

1.3 & 1.4

### GLPI version

10.0.2

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.3

**Comment by g-bougard** [comment]
Hi @Tony710 

indeed, you're talking about 2 different problems not directly related:
 1. the download link is not shown
 2. the snmpcredentials id is not registered

What is the main problem for you ?

**Comment by steph461** [comment]
For information : 
The inventory Computer its OK  maybe the file are import *.json and not XML

**Comment by steph461** [comment]
I exported a xml file manually in the GLPI, , same issue. Th file xml is not created in the glpi and no ip

No log No php error

**Comment by Molina15** [comment]
Do you have the OCS plugin activated? If so, disable it.

**Comment by steph461** [comment]
> Do you have the OCS plugin activated? If so, disable it.

I use glpiinventory and no OCS plugin

**Comment by stonebuzz** [comment]
Hi @steph461 

For "snmpcredentials id is not registered"
This issue is fixed by :

- https://github.com/glpi-project/glpi/pull/12181
- https://github.com/glpi-project/inventory_format/pull/78

For "download link is not shown"
I do not reproduce
The link is here 
![image](https://user-images.githubusercontent.com/7335054/183590824-14bf9253-37e1-4342-8430-31bf0c0b9dec.png)

Best regards

**Comment by steph461** [comment]
> Hi @steph461
> 
> For "snmpcredentials id is not registered" This issue is fixed by :
> 
> * [feat(inventoriable): add snmp credential and last update for NetworkEquipement and Printer #12181](https://github.com/glpi-project/glpi/pull/12181)
> 
> For "download link is not shown" I do not reproduce The link is here ![image](https://user-images.githubusercontent.com/7335054/183590824-14bf9253-37e1-4342-8430-31bf0c0b9dec.png)
> 
> Best regards

Thx i will test :)

**Comment by steph461** [comment]
I have test with glpi last fix its ok
