### ISSUE TITLE
[GLPI 10] Creating a Problem from Ticket does not copy any data

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12182]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When creating the Problem ticket from Ticket using the tab "Problems" by clicking Link "Create a problem from this ticket".
It redirects to URL https://URL/front/problem.form.php?tickets_id=XXX

Previously in V9.5 GLPI was copying all the parameters from Tickets to new Problem.
Entity, Category, Priority...

With V10 this is not working and it is not loading the parameters from the original Ticket.
While checking code, copy was done in Problem::showForm():

https://github.com/glpi-project/glpi/blob/5da35e463619ba6174d9c1fee940c3f22282e08e/inc/problem.class.php#L1218-L1232

Now in V10 Problems are using common showForm from CommonITILObject::showForm() and there is no such code to copy data to the new Problem.

Should the copy from ticket be added here to CommonITILObject now?
Or do you want to have some generic code here to allow copy of other types as well..

### Your GLPI setup information

10.0.2

**Comment by cedric-anne** [comment]
@VladoTTX 

Corresponding code seems to have been moved here https://github.com/glpi-project/glpi/blob/04c4feccab94774b505d011b1095b1fc2043657a/src/CommonITILObject.php#L458-L478

If it does not work as expected, then there is probably a bug.

**Comment by VladoTTX** [comment]
Yes there is:
https://github.com/glpi-project/glpi/blob/04c4feccab94774b505d011b1095b1fc2043657a/src/CommonITILObject.php#L381
Does not have options which are set just later on right before rendering:
https://github.com/glpi-project/glpi/blob/04c4feccab94774b505d011b1095b1fc2043657a/src/CommonITILObject.php#L413
