### ISSUE TITLE
New Chrome update (103.0.5060.114) uses full CPU and makes for about a minute the "Assistance - Tickets" in unresponsive state, and some emails affecting the GLPI's style

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12184]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

There are no any newer errors on dev on Chrome and neither errors in GLPI's log files and debug. Every OS seems affected (tried on Windows/Linux/Android). Is there any way to troubleshoot this behaviour? For example to load the page with tickets to be 1 ticket per site for checking if it's because of some ticket?

Edit: I have find one reason, we have some reports because of base64 not handled by some mail clients, so the whole long base64 part on the ticket makes the Chrome browser to be unresponsive because of high CPU usage (on Edge and Firefox everything seems ok)

Edit2: Previously I had a ticket that made the GLPI's style with red underlined hyperlinks (for some reason whether the corrypted tcket was in the ticket's list or loaded then the style were affected). I went to the source on the ticket for checking it, when I saved the source without changing anything then everything fixed.

**Comment by dxdemetriou** [comment]
Probably I've mixed two bugs, but it seems to me that's there is a relation

For the unresponsive browser, the only I have until now it's because of a long ticket with base64 code in it

For the second one, this is an email that's affecting the Style
[Re: Knowledge Τree.eml.zip](https://github.com/glpi-project/glpi/files/9084785/Re.Knowledge.ree.eml.zip)

![image](https://user-images.githubusercontent.com/41939421/178285710-caf3f329-b7e8-4165-9ce9-6a29e7d42395.png)

**Comment by cedric-anne** [comment]
Can you attach your `other email with any text 60000 lines` here ?

**Comment by dxdemetriou** [comment]
> Can you attach your `other email with any text 60000 lines` here ?

I'm trying to repruduce the email to similar structure but I'm stuck with 100% CPU in php, and the Tickets page does not load anything. I'm trying to remove them by their numbers and I'll try to attach it.

**Comment by dxdemetriou** [comment]
With this I have stucked everything and I have deleted the tickets drectly from database. 
[email.eml.zip](https://github.com/glpi-project/glpi/files/9092020/email.eml.zip)

Is there a way to protect the front/ticket.php from overloading because of some problematic email? The attached email is somehow bigger because of full 76 letters in each line, which seems that never finishes the loading.

**Comment by cedric-anne** [comment]
With #12207, collecting email takes less than 5 seconds on my machine, and display the ticket page is a bit slow, but is not burning CPU anymore.

Display of ticket list still fails if the `description` column is displayed , and browser freezes a few seconds when the description is displayed on tooltip on title hovering.

The are probably more optimizations to do, but 4.5MB tickets description seems to be a really edge case. For instance, having a 4.5MB base64 source code of an email inside another email body is not something common (usually, forwarded emails source is located into attachements, and would result in having a document attached to GLPI ticket).

**Comment by dxdemetriou** [comment]
> The are probably more optimizations to do, but 4.5MB tickets description seems to be a really edge case. For instance, having a 4.5MB base64 source code of an email inside another email body is not something common (usually, forwarded emails source is located into attachements, and would result in having a document attached to GLPI ticket).

It's from some emails we took from some users that they prefer to use their company's email through their Gmail's account, and lately, Google seems to corrupting some of those emails. Actually we don't know yet from how many users we'll get those corrupted emails, but probably it could be up to the maximum size allowed by Google :confused:
