### ISSUE TITLE
Logs purge

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1218]
Hello,

Actually, we maintain a plugin in order to purge logs (see https://github.com/pluginsGLPI/purgelogs/).

I guess this should be integrated into the core, and we should propose an API for other plugins to add their own logs purge.

Comments?

**Comment by orthagh** [comment]
Looks good to me. We can target next major version for this

**Comment by tomolimo** [comment]
Hello,
Just to be sure: does it keep history or not?
Thank you
Tomolimo

**Comment by orthagh** [comment]
it's the purpose of the plugin / this issue: to no keep the history.

Actually, the plugin provide a configuration to manage what we should keep/remove in glpi_logs.

**Comment by sulian** [comment]
@orthagh, did the plugin can add an entry when the log is cleared ? (to differentiate empty log to log cleared)

**Comment by orthagh** [comment]
yes, it's a good idea

**Comment by trasher** [comment]
@sulian since the plugin is not yet reintegrated, could you please add the RFE on the plugin tracker? Thank you

**Comment by sulian** [comment]
Sure, no problem

**Comment by trasher** [comment]
For reference: http://glpi.userecho.com/topics/62-purge-glpi-logs/

**Comment by trasher** [comment]
Done in current master
