### ISSUE TITLE
Problem with tinymce.js in ticket

### ISSUE THREAD

**Issue by adamcios** [glpi-project/glpi#12189]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Every ticekt load very slow when i want to add new information 
so checked develop tools in browser and i see a lot probles like 
https://myadres.com.pl/css_compiledcss_palettes_teclib.min.css?v=22140bdf034708722b923c6f04634d4691588727&v=22140bdf034708722b923c6f04634d4691588727 net::ERR_ABORTED 404 (Not Found)

i think there is a problem with missing slash or smth couse css_compiled is a direcoty :  css_compiled**/**css_palettes_teclib.min.css?

**Comment by cedric-anne** [comment]
Hi,

Can you test #12256 ?

**Comment by cedric-anne** [comment]
@adamcios 

Can you test #12256 ? I cannot reproduce on my environment, and as you did not provide your GLPI setup information, I cannot be sure of what OS is affected by this issue.

Regards
