### ISSUE TITLE
[GLPI10] Default actors for ITIL Objects behavior

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12188]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Behavior of default Actors has changed since V9.5.
In V10 we get following for  ITIL Objects (except Tickets):
- Requester is empty
- Assignee is current writer

Previous behavior in V9.5 was:
- Requester was current writer
- Assignee was empty

Checking code of V9.5 previously vaules were defined in getDefaultValues() for each ITIL Object.
V9.5 used ``_user_id_*`` from getDefaultValues() of ITIL Objects and just in case it was not defined it revered to getDefaultActors():
https://github.com/glpi-project/glpi/blob/5da35e463619ba6174d9c1fee940c3f22282e08e/inc/commonitilobject.class.php#L4416-L4418

Here definition of getDefaultValues which provided values (example from Problems):
https://github.com/glpi-project/glpi/blob/5da35e463619ba6174d9c1fee940c3f22282e08e/inc/problem.class.php#L1986-L1995

Current behavior of V10 is different. It takes directly from getDefaultActors() as actors are filled in by function CommonITILObject::getActorsForType():
https://github.com/glpi-project/glpi/blob/7d2b179c20568107533d16b8bcf7baf8a66caf4e/src/CommonITILObject.php#L172-L173

So it looks like definition of actors in getDefaultValues is ignored compeltely.

Is it possible to get previous behavior of assigned actors?
Or maybe is it possible to move code from Tickets:getDefaultActors() to CommonITILObject so it is generic for all ITIL Objects and settings glpiset_default_tech and glpiset_default_requester are used for all ITIL Objects not just Tickets?

https://github.com/glpi-project/glpi/blob/7d2b179c20568107533d16b8bcf7baf8a66caf4e/src/Ticket.php#L655-L675

I can submit a PR if we agree on this..

**Comment by fredy1322** [comment]
Tengo el mismo problema, quisiera obtener una solución. Puedes ayudarme?

**Comment by fredy1322** [comment]
I have the same problem, I would like to get a solution. You can help?

**Comment by cedric-anne** [comment]
@VladoTTX 

Can you check #12261 ?

> Or maybe is it possible to move code from Tickets:getDefaultActors() to CommonITILObject so it is generic for all ITIL Objects and settings glpiset_default_tech and glpiset_default_requester are used for all ITIL Objects not just Tickets?

Using `glpiset_default_tech` and `glpiset_default_requester` seems ok for me. @orthagh, do you agree with that ?

Also, as explained in #12261, to have a consistent behaviour, `getDefaultValues()` should probably use `getDefaultActor()`, and `getDefaultActor()` should probably also handle default requester.

Feel free to propose a PR on main branch to enhance this part in GLPI 10.1, or on 10.0/bugfixes branch if you consider there is still an issue to fix.

**Comment by VladoTTX** [comment]
Checked this on 10.0.3 and it works but it fixes part of it but makes user always as Assignee for Change and Problem.
I've opened a PR #12682 for main to make it consistent
