### ISSUE TITLE
Auto assign not ok on update ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1219]
http://forum.glpi-project.org/viewtopic.php?id=155568

**Comment by orthagh** [comment]
As far i remember, we never had an auto assign group for ticket update.
I checked in the code, only Ticket::prepareInputForAdd mention 'auto_assign_mode'.

More about this, i did this exact process in escalation plugin, see following screenshot:
![image](https://cloud.githubusercontent.com/assets/418844/20140254/7fda5064-a68a-11e6-86cc-a5c00781477d.png)

If we want this behavior for ticket update (so in prepareInputForUpdate), it's not a problem, but i think the label attached to this issue should be enhancement and we can postpone a little the fix (let say 9.1.2)
We should also think about scenario when a group already assigned to a ticket.
Maybe we can add an additional option in Entity > Assistance config to manage the activation for update process.

Your opinion

**Comment by yllen** [comment]
In 0.90.x you can automatically affect an assign group based on the category.
For me is a regression, so a bug

**Comment by orthagh** [comment]
I couldn't confirm this bug.
At ticket creation, the auto affection works (just tested). Are you sure you enabled it in entity configuration ?

For ticker update, it never worked, that the point i described in my answer (https://github.com/glpi-project/glpi/issues/1219#issuecomment-259416902)

**Comment by yllen** [comment]
Yes i confirm the bug and it works in 0.90.x
Step to reproduce
I have a category with a group affected - I have a ticket already creating -
In configuration of my entity, i have automatic affectation based on Category
I open the existing ticket and choose my category.
After i update the ticket, i can see the group automatically assigned to the ticket in 0.90.x
In 9.1.x no affectation of the assigned group

**Comment by orthagh** [comment]
I don't understand.
In 0.90 (neither any versions), we don't have auto_assign_mode in ticket update process.

I checked the code again to be sure, i retrieve usage of this config in Ticket::prepareInputForAdd but not for update (nor anyhere).

Could this process are triggerred by a plugin in your case ?

**Comment by yllen** [comment]
Tests done with all plugins desactivated

**Comment by yllen** [comment]
Find the problem:recursive rule
