### ISSUE TITLE
Projects and changes - visible at front page

### ISSUE THREAD

**Issue by FPAdministrator** [glpi-project/glpi#122]
Feature request :).

It would be great if user/technician could see:
- projects for which he/she is reposnsible;
- tasks within projects that are assigned to him/her;
- changes for which he/she is responsible;
- tasks within changes that are assigned to him/her.

Maybe something similar to tickets view? Maybe new tab that would contain info only from projects and changes?

What do you think?

**Comment by orthagh** [comment]
The feature request service will be announced soon but i think i can share the url.
   suggest.glpi-project.org

Could you repost you suggestion on this service, please ?
