### ISSUE TITLE
FOREACHtimelineitems does not include requester's followups when the requester answers by an email to the ticket, so any watcher cannot see requester's followups on their email

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12205]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Ref: https://github.com/glpi-project/glpi/issues/12200

When a requester is replying back by email to the ticket, the timeline shouldn't be to include everything in a timeline? If there are watchers on the ticket, they cannot see any user's followups by their received email.

**Template translation:**
`
##lang.ticket.url##: [##ticket.url##](https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.yml##ticket.url##)

If you wish to add further information, click on the previous links, or reply directly to this e-mail.

##FOREACHtimelineitems##

##timelineitems.author## - ##timelineitems.date##

##timelineitems.description##

##ENDFOREACHtimelineitems##

##lang.ticket.description##:

##ticket.authors## - ##ticket.creationdate##

##ticket.description##
`

### Steps To reproduce

The process I did:
1. Requester sends an email to the GLPI's receiver (ticket created - email contains the description)
2. Supporter answers by a followup (timeline is OK, includes everything)
3. Requester replies back to the ticket by an email (only the description shown on timeline)
4. Supporter answer another followup (timeline is OK, includes everything)
5. Requester replies back to the ticket by an email (every requester's replies are missing from timeline, only description and supporter's followups are in timeline)
6. Supporter solves the ticket (everything in timeline)
7. Requester replies back to the ticket by an email (only description & solution are visible in timeline, and every requester's followups are missing)

**Comment by dxdemetriou** [comment]
Here are the screenshots of the emails:
[GLPI.zip](https://github.com/glpi-project/glpi/files/9101569/GLPI.zip)

**Comment by stonebuzz** [comment]
Hi @dxdemetriou 

can you try this

```patch
diff --git a/src/CommonITILObject.php b/src/CommonITILObject.php
index ee5ba5906e..bf4b44c495 100644
--- a/src/CommonITILObject.php
+++ b/src/CommonITILObject.php
@@ -6626,7 +6626,7 @@ abstract class CommonITILObject extends CommonDBTM
             $followups = $followup_obj->find(['items_id'  => $this->getID()] + $restrict_fup, ['date DESC', 'id DESC']);
             foreach ($followups as $followups_id => $followup) {
                 $followup_obj->getFromDB($followups_id);
-                if ($followup_obj->canViewItem()) {
+                if ($followup_obj->canViewItem() || $params['bypass_rights']) {
                     $followup['can_edit'] = $followup_obj->canUpdateItem();
                     $timeline["ITILFollowup_" . $followups_id] = [
                         'type' => ITILFollowup::class,
@@ -6642,7 +6642,7 @@ abstract class CommonITILObject extends CommonDBTM
             $tasks = $task_obj->find([$foreignKey => $this->getID()] + $restrict_task, 'date DESC');
             foreach ($tasks as $tasks_id => $task) {
                 $task_obj->getFromDB($tasks_id);
-                if ($task_obj->canViewItem()) {
+                if ($task_obj->canViewItem() || $params['bypass_rights']) {
                     $task['can_edit'] = $task_obj->canUpdateItem();
                     $timeline[$task_obj::getType() . "_" . $tasks_id] = [
                         'type' => $taskClass,

```
