### ISSUE TITLE
RAM is not accurate between glpi-agent and GLPI

### ISSUE THREAD

**Issue by hagianghi** [glpi-project/glpi#12202]
### Bug reporting acknowledgment

Yes, I read it

### Describe the bug

RAM is not accurate between glpi-agent and GLPI

### To reproduce

![glpi-agent](https://user-images.githubusercontent.com/20183808/178673277-819a1bf7-3e68-4dd2-8d69-33fdb20a30a3.png)
![glpi-computer](https://user-images.githubusercontent.com/20183808/178673291-ef413d37-d3f9-4aa4-a042-44c79a1e300b.png)

### Expected behavior

my laptop 16GB of RAM but only display 8GB of RAM. im using latest glpi 10 and using glpi-agent 1.2 (glpi-agent 1.4 still same result)

### Operating system

Windows

### GLPI Agent version

1.2

### GLPI version

10.0.1

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.1

**Comment by g-bougard** [comment]
Just to complete the issue and check if we can do something regarding `832500008325` as `manufacturer` string which is clearly wrong, can you report the output of the following command run from the agent installation folder:
```
perl\bin\dmidecode -t 17
```
This is what the agent analyses to report memory module components.

**Comment by g-bougard** [comment]
Hi @hagianghi 

on the agent side, we have code to support reading "Part Number", but the manufacturer here is not recognized. Do you know which manufacturer produced that memory module ? If yes, it would be possible to update the agent to report the right manufacturer. And so, can you open a dedicated issue to support that memory module manufacturer on the glpi-agent project ?

Anyway, there's still a bug in GLPI as it tries to use `832500008325` number as `manufacturers_id` in a SQL request.

**Comment by g-bougard** [comment]
Hi @hagianghi 
I implemented a work-around in glpi-agent and you should have the KingMax module inventoried using the next glpi-agent nightly build.
GLPI still have to be fixed to not convert a manufacturer string made of digits to a number.

**Comment by cedric-anne** [comment]
Hi @hagianghi,

This issue should be fixed now. Do you have a test server that you could use to validate that problem has been solved on latest [GLPI 10.0 nightly build](https://nightly.glpi-project.org/glpi/)?
