### ISSUE TITLE
notificação por e-mail não funciona

### ISSUE THREAD

**Issue by felpbr54** [glpi-project/glpi#12201]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Não sou notificado por e-mail quando faço alterações no ticket, na parte de configuração da erro quando coloco os dados do meu servidor de e-mail, SMTP e não envia teste para e-mail administrador

**Comment by trasher** [comment]
As requested when opening an issue, please **use english only**.
