### ISSUE TITLE
User's replies are missing from timeline that could be a confusing for watcher users if they are relying on emails for notifications

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12200]
> > The difference of not using the "Add a solution" and the "Follow-up & Solved" is preffered it's because of the conversation history:
> > ##FOREACH LAST 1 followups## .. ##ENDFOREACHfollowups##
> 
> In GLPI 10.0, you can use a loop on `timelineitems`, which will include all timeline elements, except the ticket description. See #9456 for more details.

When a user is replying back to the ticket, the timeline shouldn't be to include everything in a timeline?
The process I did:
-Send email to the receiver (ticket created - email contains the description)
-Answer by a followup (timeline is OK)
-User replies back to the ticket (only the description shown on timeline)
-Answer another followup (timeline is OK)
-User replies back (both of their replies are missing from timeline)
-Solved ticket (everything in timeline)
-User replies back (only description & solution are visible in timeline)

Actually I think that those missed informations could be a confuse for watchers if they are be notified by email

_Originally posted by @dxdemetriou in https://github.com/glpi-project/glpi/issues/12055#issuecomment-1181993172_

**Comment by cedric-anne** [comment]
Hi,

> -User replies back to the ticket (only the description shown on timeline)

How did the user replied ? From the UI ? Using simplified interface ? Or maybe by replying to a notification ?

What are you calling the `timeline` here ?

Also, can you provide requested information in [issue form](https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.yml) ?

**Comment by dxdemetriou** [comment]
> Hi,
> 
> > -User replies back to the ticket (only the description shown on timeline)
> 
> How did the user replied ? From the UI ? Using simplified interface ? Or maybe by replying to a notification ?

Firstly by replying to the notification (the requester), and I just have tried by helpdesk. The problem seems only when replying to the notification, and by helpdesk (simplified interface tried) is everything OK

> What are you calling the `timeline` here ?

FOREACHtimelineitems

> Also, can you provide requested information in [issue form](https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.yml) ?
