### ISSUE TITLE
Delete notice back to 9.1

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1221]
Hi all.
There is notification for a new comments. When 2 –level specialist replies via email, his text is added to the proper ticket and he gets back notification about it. Is it possible to cancel such back notifications? Thanks.

**Comment by gloomy-master** [comment]
Any solutions?

**Comment by cedric-anne** [comment]
Hi,

Same as #4643. I close this one as #4643 is more descriptive.

Regards
