### ISSUE TITLE
[APIREST][10.0.2] ProjectTask display restriction

### ISSUE THREAD

**Issue by masakazuwatanabe** [glpi-project/glpi#12211]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

hello.
I'm having a problem because I can't get the list of project tasks with API.

This problem also occurs in Ver9.4.5 - Ver9.5.7.
https://github.com/glpi-project/glpi/issues/6818

Set Project to Seeall in your profile.
- (WebUI): See all projects and project tasks.
- (RestAPI): Project tasks are only visible to users or groups on the task team.

If "See all" in "Projects" of "Profile" is checked,
![profile02](https://user-images.githubusercontent.com/16225492/178910383-1ce5a28b-17dd-446b-b8d4-4fd64c01cdaa.png)

- All projects can be displayed
- All project tasks can be displayed

![project02](https://user-images.githubusercontent.com/16225492/178910481-4d135ec1-f30b-4a91-b95a-89d03cb330b6.png)

![projecttask02](https://user-images.githubusercontent.com/16225492/178910485-1c4a099d-27b4-421a-95b8-502ab90d5336.png)

but,

* Allow API to the same user
* Get the list of "Project Task" by REST-API with the same user
It seems that only the ones associated as "Task Teams" are displayed when I execute.
(Operation equivalent to "MyTasks"?)

It seems that the task team is used as a condition for querying the project task, regardless of the status of the SeeAll permission of the project.

https://github.com/glpi-project/glpi/blob/10873706f388795a1d0d72a028eb4ceba36f7169/src/Search.php#L4251-L4281

There is no way to list all project tasks in REST-API.
If all projects have permissions
Just as the WebUI shows all the tasks,
I also want to get a list of all tasks in REST-API.

### Your GLPI setup information

<details><summary>システムのインストールと設定の情報</summary><pre>GLPI 10.0.2 ( => /usr/local/glpi)
Installation mode: TARBALL
Current language:ja_JP

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi01 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64
PHP 7.4.19 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: nginx/1.14.1
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.8.3-MariaDB-1:10.8.3+maria~jammy
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.19) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.8.3) is supported.
The log file has been created successfully.
Write access to /usr/local/glpi/files/_cache has been validated.
Write access to /usr/local/glpi/config has been validated.
Write access to /usr/local/glpi/files/_cron has been validated.
Write access to /usr/local/glpi/files has been validated.
Write access to /usr/local/glpi/files/_dumps has been validated.
Write access to /usr/local/glpi/files/_graphs has been validated.
Write access to /usr/local/glpi/files/_lock has been validated.
Write access to /usr/local/glpi/files/_pictures has been validated.
Write access to /usr/local/glpi/files/_plugins has been validated.
Write access to /usr/local/glpi/files/_rss has been validated.
Write access to /usr/local/glpi/files/_sessions has been validated.
Write access to /usr/local/glpi/files/_tmp has been validated.
Write access to /usr/local/glpi/files/_uploads has been validated.
Web access to files directory is protected
For security reasons, SELinux mode should be Enforcing.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /usr/local/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/local/glpi
GLPI_CONFIG_DIR: /usr/local/glpi/config
GLPI_VAR_DIR: /usr/local/glpi/files
GLPI_MARKETPLACE_DIR: /usr/local/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /usr/local/glpi/files
GLPI_CACHE_DIR: /usr/local/glpi/files/_cache
GLPI_CRON_DIR: /usr/local/glpi/files/_cron
GLPI_DUMP_DIR: /usr/local/glpi/files/_dumps
GLPI_GRAPH_DIR: /usr/local/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /usr/local/glpi/files/_locales
GLPI_LOCK_DIR: /usr/local/glpi/files/_lock
GLPI_LOG_DIR: /usr/local/glpi/files/_log
GLPI_PICTURE_DIR: /usr/local/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /usr/local/glpi/files/_plugins
GLPI_RSS_DIR: /usr/local/glpi/files/_rss
GLPI_SESSION_DIR: /usr/local/glpi/files/_sessions
GLPI_TMP_DIR: /usr/local/glpi/files/_tmp
GLPI_UPLOAD_DIR: /usr/local/glpi/files/_uploads
GLPI_INVENTORY_DIR: /usr/local/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/local/glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/usr/local/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/local/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/local/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/usr/local/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/local/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/local/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/local/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/local/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/local/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/local/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/local/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/local/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/local/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/local/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/local/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/local/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/local/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/local/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/local/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/local/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/local/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/local/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/local/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/local/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/local/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/local/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/local/glpi/vendor/psr/cache/src)
league/csv in (/usr/local/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/local/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/local/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/local/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/local/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/local/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/local/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/local/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/local/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/local/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/local/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/local/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/local/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/local/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/usr/local/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.130.8.144', Port: '389', BaseDN: 'dc=qualitia,dc=co,dc=jp', Connection filter:
		'(&(objectClass=posixAccount)(objectClass=sambaSamAccount))', RootDN: 'cn=root,dc=qualitia,dc=co,dc=jp', Use TLS: none
Server: '192.168.0.141', Port: '389', BaseDN: 'OU=Users,OU=QUALITIA,DC=domain,DC=nsz,DC=jp', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'DOMAIN\sysadmin', Use
		TLS: '1'

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@localhost)

</details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.0.0      State: Error / to clean                        
		Install Method: Manual
	news                 Name: Alerts                         Version: 1.9.1      State: Error / to clean                        
		Install Method: Manual
	barcode              Name: Barcode                        Version: 2.6.2      State: Error / to clean                        
		Install Method: Manual
	archimap             Name: Diagrams                       Version: 3.2.7      State: Error / to clean                        
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Error / to clean                        
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.0      State: Enabled                                 
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.5.1      State: Error / to clean                        
		Install Method: Manual
	addressing           Name: IP Adressing                   Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.7.4      State: Error / to clean                        
		Install Method: Manual
	genericobject        Name: Objects management             Version: 2.12.1     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Orders management              Version: 2.9.0      State: Installed / not activated               
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.9.2      State: Enabled                                 
		Install Method: Marketplace
	accounts             Name: アカウント                          Version: 3.0.2      State: Enabled                         
		        Install Method: Marketplace
	datainjection        Name: インジェクション                 Version: 2.11.2     State: Installed / not activated       
		        Install Method: Marketplace
	fields               Name: 追加のフィールド                 Version: 1.16.0     State: Enabled                         
		        Install Method: Marketplace

</pre></details>

**Comment by cconard96** [comment]
The issue is when you use the `search` endpoint instead of the `getItems` one. There is a hidden filter in the search engine for these tasks that restrict them to being your tasks. You see the same thing by going to the project task search page `/front/projecttask.php`.'

The URL `/apirest.php/ProjectTask` will show all project tasks.

**Comment by marien-probesys** [comment]
Hi, I can confirm the issue, even when using the URLs `/apirest.php/ProjectTask` or `/apirest.php/Project/<id>/ProjectTask`.

I was able to understand a bit why it's working in the interface, but not in the API.

If the user has access to the project of the tasks, he has the right to read them even if he’s not in the Task Team (see https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/ProjectTask.php#L91-L96). Meaning that the user has the right to read the tasks as soon as it has the rights on the project.

Now, on the API part, the `getItems` method correctly checks the rights, but it also create a `where` condition:

```SQL
(`glpi_projecttaskteams`.`itemtype` = 'User' AND `glpi_projecttaskteams`.`items_id` = '2')
```

Indeed, it first calls `Search::addDefaultWhere`: https://github.com/glpi-project/glpi/blob/b69e15312f81915286a60de8ec68210570406123/src/Api/API.php#L1138

Which returns this condition: https://github.com/glpi-project/glpi/blob/b69e15312f81915286a60de8ec68210570406123/src/Search.php#L4343-L4348

This condition is incomplete as it should probably include an `OR` clause to check if the user has right on the task project. I'm not able to say if it can have unexpected impacts though.
