### ISSUE TITLE
[GLPI10] Possible to set Pending reason if Pending is disabled in Allowed Statuses

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12214]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

It is currently possible to set Pending reason even when Pending status is disabled for given profile in matrix of Allowed statues.

https://github.com/glpi-project/glpi/blob/dc8f7fbe61fead655333ef66dc0e092182f6584b/templates/components/itilobject/timeline/form_followup.html.twig#L212-L215

But I think generally Pending handling should be improved in way that Pending would be treated specially.
And when ticket is returning from Pending it should return to previous status...

**Comment by cconard96** [comment]
Completed via #12215
