### ISSUE TITLE
[GLPI10] Default Problem search criteria for Status in list view

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12217]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Search criteria in list view for Problem is by default pre-defined to "Not Solved" eg. notold.
But values in Dropdown does not contain these special values for Search (withmetaforsearch). This causes issues when someone clicks on either column to sort or next page as it would preselect different condition (eg "Status is New" by default).

Looks like there is old code which does not pass proper parameters to Problem::getDropdownStatus(), basically it does not pass showtype option.

https://github.com/glpi-project/glpi/blob/5aba1fc404a86866841a03ff9e5505ce0b672243/src/Problem.php#L694-L710

But to me both functions in Problem getSpecificValueToDisplay and getSpecificValueToSelect seems to be dead code which should be removed

### Steps To reproduce

1. Click Assistance -> Problem
2. Check Status dropdown values

**Comment by cedric-anne** [comment]
Fixed by #12218.
