### ISSUE TITLE
Cannot relate Contract to multiple items

### ISSUE THREAD

**Issue by hostage007** [glpi-project/glpi#12220]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When linking a contract to items, It's not possible to link to multiple items.
It's the same then trying to link Items back to Contract. 
Since the Items tab is named in plural form, I believe it's a bug?

### Steps To reproduce

1. Contract
2. Items
3. Select a device, ADD
4. Go back to items page, no more ADD button

**Comment by cconard96** [comment]
Contracts can be limited to a certain number of items. By default, the limit is 1 item per contract. You can change this in the contract's form to a higher number or even "Unlimited".
