### ISSUE TITLE
10.0.3 - Knowledge base category -  invalid link

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12240]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Yesterday I installed the nightly build.

The "New item - Knowledge base category" form - here is "i" button for the "As child of" option. When I press it, the list of categories does not appear, but the glpi page loads.

### Steps To reproduce

1. Go to front/knowbaseitem.php
2. Select the add button.
3. Press the plus sign next to "Knowledge base categories" (BTW - the field is too short)
![obraz](https://user-images.githubusercontent.com/68922721/179946340-59995de3-1651-4827-9335-ff032da1e507.png)
4. Click on the "i" button next to the option "As child of".
![obraz](https://user-images.githubusercontent.com/68922721/179945737-4759f663-165a-4142-a07f-ccadfb01dc9a.png)
5. And here is the bug:
![obraz](https://user-images.githubusercontent.com/68922721/179945772-607d0a83-17f5-4230-b422-ec479cb4e236.png)

**Comment by WebGregGit** [comment]
At the moment, I am not able to check if the problem persists. I'll let you know soon.

**Comment by WebGregGit** [comment]
10.0.4 the problem persists.

**Comment by WebGregGit** [comment]
10.0.6-dev - the issue still exists.

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.

This is due to the fact that modal form is inside an `iframe`, so when user clicks on a link inside this modal, link is opened in the `iframe` itself. Link should use `target="_top"`.
