### ISSUE TITLE
Search AND NOT for antivirus still not work

### ISSUE THREAD

**Issue by loyolajavi** [glpi-project/glpi#12258]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7 with FusionInventory 9.5+4.2 

### Bug description

In Computer search when I filter by "not have some antivirus", if a computer have two or more antivirus, eg: Symantec and Kaspersky, that computer appears in the result, even though there is the filter to exclude:
Filter:
![image](https://user-images.githubusercontent.com/17304522/180032796-9c1cf517-76f2-4db2-b36c-076def96a939.png)

That computer have this antiviruses:
![image](https://user-images.githubusercontent.com/17304522/180030958-2996fe66-8f0d-440f-9363-76fb58020238.png)

Besides, the filter "IS NOT" doesn't show any antivirus to choose from:
![image](https://user-images.githubusercontent.com/17304522/180029241-94cf3abe-e901-4651-acdd-e76a906ba3d2.png)

### Steps To reproduce

1. Assets -> Computers
2. Create filter A or B: 
      A. Antiviruses Name not contain Symantec
      B. Antiviruses Name IS NOT Symantec

### Anything else?

I view the issue closed: https://github.com/glpi-project/glpi/issues/4894, but the bug persists in GLPI 9.5.7

**Comment by cconard96** [comment]
Please test with the criteria:
NOT Antiviruses - Name is Symantec

Since you can have more than one antivirus, the negative search criteria does not work as you may expect. Using Is Not or Not Contains would actually match items if ANY of the antiviruses were not Symantec or if ANY of the antiviruses did not contain Symantec.

**Comment by loyolajavi** [comment]
Hi Curtis,

Thanks for your response, I'm afraid the "Antiviruses - Name" "is" and "is not" criterias aren't working properly (at least in my installation).. do not show me any antivirus for selection. 
![image](https://user-images.githubusercontent.com/17304522/180314190-03460cbe-bd48-497d-b652-170e8719ef21.png)
Do you get antiviruses displayed when you select the "is"/"is not" filters? (I have 9.5.7 version)

**Comment by cconard96** [comment]
Is/Is Not probably should not be options. Currently, antiviruses are only stored as sub-items of computers rather than individual items that get linked to one or more computers.
