### ISSUE TITLE
Generate inventory number

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1225]
Hello,

Actually, there is one possibility from GLPi to generate an inventory number; from a template. The geninventorynumber plugin make that possible for all assets; whether it's been created from a template or not.

I propose to mix plugins possibilities into core directly; and maybe to drop the template part that should no longer be useful I guess (or keep it and just extend the system).

Any thoughts?

**Comment by btry** [comment]
Hi

I agree: this is troublesome to have very similar features (but not exactly the same) in the core and the plugin. Could we target GLPI 9.4 ?
