### ISSUE TITLE
Typo in Template translation (front/notificationtemplatetranslation.form.php)

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12259]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

It's
"Template translation - Template translation"
instead of the correct that should be
"Template translation - Notification template's name"

**Comment by cconard96** [comment]
This text should have the translation language as the second part. For the default translation though, it was defaulting to the type name which is "Template translation". #12308 should fix the issue.
