### ISSUE TITLE
[10.0.2] Clean install with MariaDB Galera Cluster (with default options), "Item not found" error in config pages

### ISSUE THREAD

**Issue by dsci-naw** [glpi-project/glpi#12267]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When doing a clean install of GLPI in a MariaDB Galera Cluster (with default options), major config pages of GLPI throw "Item not found" error.
This seems to happen because the id 1 in "glpi_configs" table does not exists in this scenario. Because the first id of that table in this scenario is "2", because of the explaining below.

Happens in all pages that use the config table and have "1" as id `displayFullPageForItem(1, xxxxxx)`. Examples:
- https://github.com/glpi-project/glpi/blob/10.0/bugfixes/front/config.form.php#L92
- https://github.com/glpi-project/glpi/blob/10.0/bugfixes/front/notificationmailingsetting.form.php#L51

Why this happens? MariaDB Galera Cluster, by default, dynamic manages cluster nodes _[auto_increment_increment](https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#auto_increment_increment)_ and _[auto_increment_offset](https://mariadb.com/kb/en/replication-and-binary-log-system-variables/#auto_increment_offset)_ variables to _reduce the likelihood that two nodes will attempt to write the same auto-increment value to a table_. This is done by MariaDB Galera cluster by default setting _[wsrep-auto-increment-control](https://galeracluster.com/library/documentation/mysql-wsrep-options.html#wsrep-auto-increment-control)_.

Not familiar with GLPI code, but possibel fix, before `displayFullPageForItem(1, xxxxxx)`, instead of "1", find the id by name with a `SELECT id FROM glpi_configs WHERE context = 'core' AND name = 'version';` and use that id.

**Comment by cedric-anne** [comment]
Hi,

Could you please test #12270 ?

**Comment by dsci-naw** [comment]
No item not found error, but blank page
![image](https://user-images.githubusercontent.com/89925315/180776213-e878214a-d6c4-4289-831c-9fd99bf1472f.png)

**Comment by cconard96** [comment]
A blank page probably indicates a PHP error. Please check the GLPI logs for any new errors. Specifically the "files/_log/php-errors.log" and "files/_log/sql-errors.log" logs.

**Comment by dsci-naw** [comment]
no error in the logs

**Comment by cedric-anne** [comment]
Fixed by #12295.
