### ISSUE TITLE
JPG / PNG are attached to mails but not gifs

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#12264]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

It is possible to write a followup/solution and paste a JPG/PNG and a GIF (animated).

However when the notification is send the JPG/PNG is attached but the GIF (animated)) is missing which leads to confusion.

### Relevant log output

```shell
None
```

**Comment by cedric-anne** [comment]
Hi,

I just made a test on current nightly build, and GIF pasted in followup content is present in notification body, and is present as attachement if it was added as an attachement to the followup.

If you can reproduce on GLPI nightly build (on a testing server), please give detailed information about the issue.
