### ISSUE TITLE
[GLPI 10.0.0] Migration to GLPI 10

### ISSUE THREAD

**Issue by Tartiflette-glpi** [glpi-project/glpi#12263]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Hi,
I just upgraded GLPI to GLPI 10.0.0 & got 3 warnings.
I tried to migrate the following tables but an error appears in Debian 10:

> PHP Warning:  Missing required intl PHP extension in /var/www/glpi/src/Session.php on line 680
> The version of the database is not compatible with the version of the installed files. An update is necessary.

I don't know how & what update to make it compatible, do you have any idea ?
![Capture d’écran 2022-07-21 103716](https://user-images.githubusercontent.com/109726235/180170189-c74b2b4d-fba0-485e-8f62-155fb3bddf34.png)

### Your GLPI setup information

GLPI 10.0.0
Debian 10.0

**Comment by cedric-anne** [comment]
> The version of the database is not compatible with the version of the installed files. An update is necessary.

It probably means that you executed the console on your old GLPI directory, while the webserver points on new GLPI directory.

**Comment by Tartiflette-glpi** [comment]
> > The version of the database is not compatible with the version of the installed files. An update is necessary.
> 
> It probably means that you executed the console on your old GLPI directory, while the webserver points on new GLPI directory.

The old GLPI directory ? hmm
I put the old GLPI into a directory in /var/www/html/glpi/OLD/
Then I copied the new updated files in /var/www/html/glpi/
I executed the command in the glpi directory

**Comment by cedric-anne** [comment]
What is the output of `bin/console -V` ?

**Comment by Tartiflette-glpi** [comment]
> bin/console -V

```
GLPI CLI 10.0.0
```
I got this

**Comment by cedric-anne** [comment]
> The version of the database is not compatible with the version of the installed files. An update is necessary.

This message means that the database that is configured in `config/config_db.php` is is another version than 10.0.0. So if the update process is not triggered when accessing GLPI on your browser, it means that the GLPI executed in CLI context does not point to the same DB as the GLPI executed in webserver context.
You should verify your configuration.

**Comment by cedric-anne** [comment]
By the way, the latest GLPI version is 10.0.2, why upgrading to 10.0.0 ?

**Comment by Tartiflette-glpi** [comment]
> By the way, the latest GLPI version is 10.0.2, why upgrading to 10.0.0 ?

One of our customers has upgraded when the 10.0.0 been out. And asked us how to fix this, this morning. So we upgraded a GLPI test to 10.0.0 for testings
We exactly have the same problem..

How can I verify / update the version? plz

Thanks for your help

**Comment by cedric-anne** [comment]
> How can I verify / update the version?

Execute `bin/console glpi:database:update` command.
