### ISSUE TITLE
Title and content are not filled when creating a change/problem from ticket

### ISSUE THREAD

**Issue by tsadock** [glpi-project/glpi#12279]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

The form stay empty when creating a change or problem from ticket using the link "Create a change from this ticket" in change tab.

### Page URL

front/problem.form.php?tickets_id=1

### Steps To reproduce

1. Create a ticket and save it
2. Go in Change tab or Problem tab
3. Click the link "Create a change from this ticket"
4. The form is empty

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.2 (/glpivierge => C:\xampp80\htdocs\glpivierge)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT GPMH-UC-07250 10.0 build 19042 (Windows 10) AMD64
PHP 8.0.15 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.0.15 (Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.0.15 Server at localhost
	Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: glpivierge@localhost/glpivierge
	Host info: localhost via TCP/IP
	
PHP version (8.0.15) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.22) is supported.
The log file has been created successfully.
Write access to C:\xampp80\htdocs\glpivierge/files/_cache has been validated.
Write access to C:\xampp80\htdocs\glpivierge/config has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_cron has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_dumps has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_graphs has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_lock has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_pictures has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_plugins has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_rss has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_sessions has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_tmp has been validated.
Write access to C:\xampp80\htdocs\glpivierge/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp80\htdocs\glpivierge/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\xampp80\htdocs\glpivierge
GLPI_CONFIG_DIR: C:\xampp80\htdocs\glpivierge/config
GLPI_VAR_DIR: C:\xampp80\htdocs\glpivierge/files
GLPI_MARKETPLACE_DIR: C:\xampp80\htdocs\glpivierge/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\xampp80\htdocs\glpivierge/files
GLPI_CACHE_DIR: C:\xampp80\htdocs\glpivierge/files/_cache
GLPI_CRON_DIR: C:\xampp80\htdocs\glpivierge/files/_cron
GLPI_DUMP_DIR: C:\xampp80\htdocs\glpivierge/files/_dumps
GLPI_GRAPH_DIR: C:\xampp80\htdocs\glpivierge/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\xampp80\htdocs\glpivierge/files/_locales
GLPI_LOCK_DIR: C:\xampp80\htdocs\glpivierge/files/_lock
GLPI_LOG_DIR: C:\xampp80\htdocs\glpivierge/files/_log
GLPI_PICTURE_DIR: C:\xampp80\htdocs\glpivierge/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\xampp80\htdocs\glpivierge/files/_plugins
GLPI_RSS_DIR: C:\xampp80\htdocs\glpivierge/files/_rss
GLPI_SESSION_DIR: C:\xampp80\htdocs\glpivierge/files/_sessions
GLPI_TMP_DIR: C:\xampp80\htdocs\glpivierge/files/_tmp
GLPI_UPLOAD_DIR: C:\xampp80\htdocs\glpivierge/files/_uploads
GLPI_INVENTORY_DIR: C:\xampp80\htdocs\glpivierge/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\xampp80\htdocs\glpivierge/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\xampp80\htdocs\glpivierge\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp80\htdocs\glpivierge\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp80\htdocs\glpivierge\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\xampp80\htdocs\glpivierge\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp80\htdocs\glpivierge\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp80\htdocs\glpivierge\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp80\htdocs\glpivierge\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp80\htdocs\glpivierge\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp80\htdocs\glpivierge\vendor\sabre\http\lib)
sabre/uri in (C:\xampp80\htdocs\glpivierge\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp80\htdocs\glpivierge\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp80\htdocs\glpivierge\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp80\htdocs\glpivierge\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp80\htdocs\glpivierge\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp80\htdocs\glpivierge\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp80\htdocs\glpivierge\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp80\htdocs\glpivierge\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp80\htdocs\glpivierge\vendor\symfony\console)
scssphp/scssphp in (C:\xampp80\htdocs\glpivierge\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp80\htdocs\glpivierge\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp80\htdocs\glpivierge\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp80\htdocs\glpivierge\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp80\htdocs\glpivierge\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp80\htdocs\glpivierge\vendor\ramsey\uuid\src)
psr/log in (C:\xampp80\htdocs\glpivierge\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp80\htdocs\glpivierge\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp80\htdocs\glpivierge\vendor\psr\cache\src)
league/csv in (C:\xampp80\htdocs\glpivierge\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp80\htdocs\glpivierge\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp80\htdocs\glpivierge\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp80\htdocs\glpivierge\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp80\htdocs\glpivierge\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp80\htdocs\glpivierge\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp80\htdocs\glpivierge\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp80\htdocs\glpivierge\vendor\symfony\cache)
html2text/html2text in (C:\xampp80\htdocs\glpivierge\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp80\htdocs\glpivierge\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp80\htdocs\glpivierge\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp80\htdocs\glpivierge\vendor\twig\twig\src)
twig/string-extra in (C:\xampp80\htdocs\glpivierge\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (C:\xampp80\htdocs\glpivierge\vendor\symfony\polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

### Anything else?

This is working with GLPI 9.5.7

**Comment by cedric-anne** [comment]
Duplicates #12182
