### ISSUE TITLE
[GLPI 10 Bugfixes] Error 400 on list users (with browse mode)

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#12273]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

1. Activate browse mode on users list : 
![image](https://user-images.githubusercontent.com/13178158/180383258-3955df28-0aa1-45c2-924f-365f3d0bf18d.png)

2. go on user form

3.  Click to return to list : 

![image](https://user-images.githubusercontent.com/13178158/180383334-edfd994b-c66b-4c96-967a-90b7ff566755.png)

4. Error 400

GLPI go to http://localhost/glpi/ajax/treebrowse.php

![image](https://user-images.githubusercontent.com/13178158/180383429-deb34db9-6dab-4151-9694-e49e77f1541c.png)

**Comment by cedric-anne** [comment]
Fixed by #12315.
