### ISSUE TITLE
Data loss when updating glpi.

### ISSUE THREAD

**Issue by auguzsto** [glpi-project/glpi#12274]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

After upgrading glpi 10.0.0 to 10.0.2, I lost my FAQ images. All images inserted in the FAQ tutorials do not open.

![image](https://user-images.githubusercontent.com/40308971/180410398-817c1ad6-5486-4c07-b7ba-0f3729f1d3a7.png)
"File not found."

**Comment by cedric-anne** [comment]
Did you correctly restore these files, using correct file permissions ?

**Comment by auguzsto** [comment]
Yea! I followed exactly the tutorial provided in the glpi documentation.

**Comment by cedric-anne** [comment]
Can you give requested details, such as URL, GLPI setup information, ... ?

**Comment by auguzsto** [comment]
I found the problem. For some reason when copying the backup files folder, the copy corrupted. I redid the copy and the data returned to normal.

**Comment by auguzsto** [comment]
I found the problem. For some reason when copying the backup files folder, the copy corrupted. I redid the copy and the data returned to normal.
