### ISSUE TITLE
Can't add image to know base

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#12276]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Hi
I try to add image to know base using drag and drop and image was added:
![изображение](https://user-images.githubusercontent.com/15270519/180416871-b6c304e5-a950-45ec-8f86-92ec92bdf9b6.png)
Then I saved document and after that I have this pic:
![изображение](https://user-images.githubusercontent.com/15270519/180417006-bc364b03-9a68-4d7c-b185-322bb72ccad7.png)
I opened source code and saw this:
![изображение](https://user-images.githubusercontent.com/15270519/180417327-477993a9-7cf7-4424-a874-ee9ceff4f2ce.png)
It's very strange becaus before it system was working fine.
Also I can't understand how to add image to text by using upload button. After choosing and uploading images I can't insert it to document, I have no any option for this. Also if I delete image from editor I can't readd previously added image to editor.
![изображение](https://user-images.githubusercontent.com/15270519/180418512-b3798cd3-4167-4bd2-9722-52e57bafee29.png)
![изображение](https://user-images.githubusercontent.com/15270519/180418776-784595a6-7b7d-4e61-9b76-109d5c39a742.png)

### Page URL

http://my.server/glpi/front/knowbaseitem.form.php

### Your GLPI setup information

Operating system: Linux glpi 5.4.0-120-generic #136-Ubuntu SMP Fri Jun 10 13:40:48 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="80M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi10.intranet.delkom40.by Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.29-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.PHP version (7.4.3) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.29) is supported.Database engine version (8.0.29) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cedric-anne** [comment]
Hi,

Can you test #12281 ?

**Comment by leruetkins** [comment]
> 

Hi

If I understood correctle I should to replace src/Html.php file to fix the problem, bit it didn't help me(

**Comment by cedric-anne** [comment]
> > 
> 
> Hi
> 
> If I understood correctly I should to replace src/Html.php file to fix the problem, bit it didn't help me(

No,

You should apply following patch: https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/12281.patch
You can ignore tests files.

**Comment by leruetkins** [comment]
> > > 
> > 
> > 
> > Hi
> > If I understood correctly I should to replace src/Html.php file to fix the problem, bit it didn't help me(
> 
> No,
> 
> You should apply following patch: https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/12281.patch You can ignore tests files.

I have pached and tested and now is ok!
Thanks!
