### ISSUE TITLE
Duplication in the database credentials in GLPI 9.1

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1228]
Good day developers GLPI.

I've imported users, settings indicated as "Login_field"-"userprincipalname". But since we are faced with the problem of duplication in the database credentials when using authorization of GLPI SSO via kerberos. UPN users differs from the UPN that is substituted when user enters using SSO.
Duplication in the database credentials in GLPI 9.1

Example:
Standard user login-username@domain.local
Login that uses kerberos username@mycompany.net

Therefore, GLPI considers them different accounts.

Solutions that I see:
Change the imported database user Login "GLPI to log in and change the Login_field setting GLPI" with "userprincipalname" to "samaaccountname"

Two questions:
1) As through MySQL remove login users "@xxx. xx"
2) restored the import synchronization
Now if you change "Login_field" to the LDAP connection settings c "userprincipalname" to "samaaccountname" users are not added and no synchronization

**Comment by trasher** [comment]
I do not understand the point... Logins are different, this is not a duplication from the GLPI point of view.

As of 9.2, we've added a synchronization field that is meant to be unique; that may solve your issue (at least, the behevior would not be the same).

Please try with 9.2 when it will be released (in about one moth)
