### ISSUE TITLE
'_no_notif' has disapeared from all source code

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1229]
Hello,

In 0.83.8, I used this flag to prevent sending notifications in some particular cases.

Ex: a requester is creating a ticket, and a plugin is creating a task (assigned to the requester) to keep track of some information during creation, and as this task is done, the requester will receive three notifications (one for ticket creation, one for task assignment, and one for task update).

This option was in the code in the following files:
- commondbchild.class.php
- commondbrelation.class.php
- commonitilactor.class.php
- commonitiltask.class.php
- problem.class.php
- problem_ticket.class.php
- ticket.class.php
- ticketfollowup.class.php

and in some plugins (not exhaustive list):
- behaviors\inc\ticket_user.class.php

Where is it gone, and why?
Is there any possibilities to call `CommonITILTask::add()` or `CommonITILTask::update()` and to pass a parameter to prevent notifications?

Or should we use a `$CFG_GLPI["use_mailing"] = false;` before add or update, and after them a `$CFG_GLPI["use_mailing"] = $oldvalue;` to restore former value?

Thank you,
Regards,
Tomolimo

**Comment by orthagh** [comment]
Like: https://github.com/glpi-project/glpi/blob/master/inc/ticketfollowup.class.php#L431

IMO, The word could have changed

**Comment by trasher** [comment]
Hello

Does not the `_disablenotif` replace that?

**Comment by tomolimo** [comment]
thank you, I'll check that and keep you informed

**Comment by orthagh** [comment]
Any news on this @tomolimo.
Waiting for you answer, i move to 9.1.3

**Comment by tomolimo** [comment]
I'm doing some test about this, and I can see in 9.1.2 the _no_notif flag is used in `CommonDBConnexity::cleanDBonItemDelete()`
line 123
```
     if (!empty($query)) {
         $input = array('_no_history'     => true,
                        '_no_notif'       => true);
```

**Comment by tomolimo** [comment]
But regarding the `_disablenotif`, I'm really not sure that this flag has any effect about sending or not notifications.
I can't find where this flag should prevent the notification to be sent...

**Comment by orthagh** [comment]
Here for example: https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L1301

Many other places (found with fgrep) use this key

**Comment by tomolimo** [comment]
ok, thank you, I didn't see this one, but I could see a lot of places where it should be used and in fact it is not, like [https://github.com/glpi-project/glpi/blob/master/inc/commonitiltask.class.php#L351](https://github.com/glpi-project/glpi/blob/master/inc/commonitiltask.class.php#L351)

**Comment by tomolimo** [comment]
ok, may be not many places, but only some :)

**Comment by tomolimo** [comment]
Ok then, I can see that it is managed correctly in most places,
Then let close this, and if necessary I'll do a PR to fix it when I'll see it missing.
Thank you à lot,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Anyway, this kind of tests seem strange to me: 
`      if (isset($this->input['_disablenotif'])) {`
seems like this can't be equal to false!!!

**Comment by tomolimo** [comment]
I'm going to commit a bunch of modifications ....
