### ISSUE TITLE
Show total tickets count on home screen in global view

### ISSUE THREAD

**Issue by balucha** [glpi-project/glpi#1230]

**Comment by AnaelMobilia** [comment]
Hello @balucha 

On the home page, you got : 
![image](https://cloud.githubusercontent.com/assets/6187125/21619211/fe73b75a-d1ee-11e6-8574-ebc18dec2072.png)

Which stats did you need ?
Just the count of open' tickets ? More specifics rules ?

Regards,
Anael

**Comment by balucha** [comment]
I need count of all tickets in ticket followup windows on global view. 

New	
Processing (assigned)	
Processing (planned)	
Pending	
Solved	
Closed	
Deleted   
**All**           
![glpi1](https://cloud.githubusercontent.com/assets/13922307/21642190/f0d10b6a-d280-11e6-8f57-ce77ff2fe195.png)

**Comment by AnaelMobilia** [comment]
@balucha Thanks for the update !

Could you, please, give me a little more details on your business requierement ?
Why did you need this specific value : what is your usage & how often did you need it ?

Regards,
Anael

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
