### ISSUE TITLE
Security - permissions for and in default reports.

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#12305]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.8 - 10.0.2

### Bug description

After granting read permissions to tools -> report in profile,
a user who does not have permissions to standard assets but only to those defined in the genericobject plugin gains access to reports that are not intended for him.
![image](https://user-images.githubusercontent.com/5873929/181072658-df002058-c1fc-4f21-bf6c-2f64387ad717.png)

### Steps To reproduce

Add permision read only to:
- assets from generic object plugin
-  financial information
-  tools -> report

**Comment by Wolvverine** [comment]
problem persist

**Comment by Wolvverine** [comment]
problem persist

**Comment by cedric-anne** [comment]
Hi,

Can you list reports that user is not supposed to see ? Or what information is shwon and should not be ?

The list in your screenshot is related to Infocom rights.
