### ISSUE TITLE
[PHP error/Blank Page] displayAccessDeniedPage() $menus must be of type array (using null instead)

### ISSUE THREAD

**Issue by dsci-naw** [glpi-project/glpi#12300]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

PHP Fatal error - blank page when we have denied access to entity

Problem here https://github.com/glpi-project/glpi/blob/10.0/bugfixes/front/dropdown.common.form.php#L176
Notice, in this case `$menus` is not an emptu array (`[]`), is `null`
```php
$dropdown::displayFullPageForItem($_GET['id'], null, $options);
```

But here it needs this to be an array. (https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/CommonDBTM.php#L6260) 
```php
public static function displayAccessDeniedPage(array $menus)
```

Possible fix: change ? `null` for `[]`

### Relevant log output

```shell
Uncaught Exception TypeError: CommonDBTM::displayAccessDeniedPage(): Argument #1 ($menus) must be of type array, null given, called in /src/CommonDBTM.php on line 6329 in /src/CommonDBTM.php at line 6228
```

### Page URL

/front/entity.form.php?id=2

### Steps To reproduce

1. Go to an entity which you don't have permissions (ex URI: /front/entity.form.php?id=2)
2. Blank page | php error

**Comment by dsci-naw** [comment]
thanks

**Comment by ftoledo** [comment]
i have same issue after login on glpi 10.0.5, can be realeted to this bug?
i dont have a blank page, but the url change to /index.php?redirect=%2Ffront%2Fupdatepassword.php :

![imagen](https://user-images.githubusercontent.com/95441/210637469-94ab3fda-924b-44d0-85b5-90409b08ef2d.png)

```
[2022-11-17 10:14:28] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to CommonDBTM::displayAccessDeniedPage() must be of the type array, string given, called in /var/www/glpi/src/CommonDBTM.php on line 6385 in /var/www/glpi/src/CommonDBTM.php at line 6297
  Backtrace :
  src/CommonDBTM.php:6385                            CommonDBTM::displayAccessDeniedPage()
  front/user.form.php:241                            CommonDBTM::displayFullPageForItem()
```

**Comment by cedric-anne** [comment]
@ftoledo 

Please open a new issue.
