### ISSUE TITLE
CSS duplicate item

### ISSUE THREAD

**Issue by XSBen** [glpi-project/glpi#12314]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

In css compiled files, some sections are duplicated:

For exemple at line 26658: 

```
.select2-container--default .select2-results__option[aria-disabled=true] {
  color: #999;
}
.select2-container--default .select2-results__option[aria-selected=true] {
  background-color: #ddd;
}
```

In this case, `background-color: #ddd;` is not used by browser (Edge, firefox) for dropdowns:

![image](https://user-images.githubusercontent.com/6490248/181229495-a733c6f9-b9c4-49fb-8d7d-c66c98072664.png)

Should be:

![image](https://user-images.githubusercontent.com/6490248/181229515-d9849323-5418-4250-b359-488e6a9c270d.png)

Or at line 26443:

```
.select2-results__options {
  list-style: none;
  margin: 0;
  padding: 0;
}
.select2-results__option {
  padding: 6px;
  user-select: none;
  -webkit-user-select: none;
}
```

### Page URL

front/ticket.form.php

**Comment by cconard96** [comment]
Duplicate CSS selectors should not be an issue as the browser should combine them. The only thing would be if a property exists for more than one of the duplicates. In that case, the value in the later rule will be used.

I am not seeing this issue on my end.

**Comment by XSBen** [comment]
I made a mistake:

Theses two selectors aren't the same (`aria-disabled` and `aria-selected`:  

```
.select2-container--default .select2-results__option[aria-disabled=true] {
  color: #999;
}
.select2-container--default .select2-results__option[aria-selected=true] {
  background-color: #ddd;
}
```

Sorry for the noise.

For information, I made a few change in our CSS which is more visible from my opinion:

![image](https://user-images.githubusercontent.com/6490248/181474846-04a53dc4-51e0-401b-a916-d2eb962a83ee.png)
