### ISSUE TITLE
Plugin endpoints: Unauthorized (401) and Bad Request (400)

### ISSUE THREAD

**Issue by ajsb85** [glpi-project/glpi#1232]
When we create new endpoints in the plugin, the error for an invalid session token is 400 instead 401.

**GLPi**: Failed to load resource: the server responded with a status of 401 (Unauthorized) 
**PLugin**: Failed to load resource: the server responded with a status of 400 (Bad Request)

**GLPi** endpoints:
`["ERROR_SESSION_TOKEN_INVALID","session_token seems invalid"]`

**Plugin** endpoints:
`["ERROR_RESOURCE_NOT_FOUND_NOR_COMMONDBTM","resource not found or not an instance of CommonDBTM"]`

/cc @btry

**Comment by cedric-anne** [comment]
Hi @ajsb85 ,

Is this problem still occurs in GLPI 9.4.1 ?

Regards

**Comment by btry** [comment]
@cedric-anne 

This issue will very likely still occur with the latest version of GLPI, I may handle this issue as I'm used to work with this part of GLPI.
