### ISSUE TITLE
Business rules for assets don't work outside the root entity and ignore the child entities checkbox

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#12321]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Business rules for assets don't work outside the root entity and ignore the child entities checkbox.

### Steps To reproduce

1. Create a child entity.
2. Switch to this entity.
3. Create a Business rules for assets for add/update.
4. Create an asset and check that the rule does not work.

**Comment by ts2050** [comment]
I'm having the same problem.
When I try to create an asset business rule, it doesn't work.
For example, I created a rule that changes the hardware group based on location, but the rule doesn't work.
