### ISSUE TITLE
GLPI does not want to import groups from LDAP that start with a # in the name.

### ISSUE THREAD

**Issue by wadaki** [glpi-project/glpi#12328]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.x

### Bug description

I set up LDAP and the CRON will import User accounts without any issues. Also some groups are available.

But the most of our group names starts with #
GLPI will not import these groups correct.

### Relevant log output

```shell
During import groups, there is no error.log are written.
```

### Page URL

/front/ldap.group.import.php?next=servers

### Steps To reproduce

1. Open as Administrator the groups from LDAP　http://helpdesk.xxx.com/front/ldap.group.import.php
2. Select groups and click action button to import groups
3. No error, selected group/s are imported, but no name is visible and no DN is included

### Your GLPI setup information

[code]   
GLPI 9.5.7 ( => /var/www/html) Installation mode: TARBALL Current language:de_DE
--

Operating system: Linux tkysv0063 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at helpdesk.xxx.com Port 80) 	Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0 Server Software: Debian 11 	Server Version: 10.5.15-MariaDB-0+deb11u1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.5.15) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/files/_cache has been validated. Write access to /var/www/html/config has been validated. Write access to /var/www/html/files/_cron has been validated. Write access to /var/www/html/files has been validated. Write access to /var/www/html/files/_dumps has been validated. Write access to /var/www/html/files/_graphs has been validated. Write access to /var/www/html/files/_lock has been validated. Write access to /var/www/html/files/_pictures has been validated. Write access to /var/www/html/files/_plugins has been validated. Write access to /var/www/html/files/_rss has been validated. Write access to /var/www/html/files/_sessions has been validated. Write access to /var/www/html/files/_tmp has been validated. Write access to /var/www/html/files/_uploads has been validated. Write access to /var/www/html/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/html GLPI_CONFIG_DIR: /var/www/html/config GLPI_VAR_DIR: /var/www/html/files GLPI_MARKETPLACE_DIR: /var/www/html/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/files GLPI_CACHE_DIR: /var/www/html/files/_cache GLPI_CRON_DIR: /var/www/html/files/_cron GLPI_DUMP_DIR: /var/www/html/files/_dumps GLPI_GRAPH_DIR: /var/www/html/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales GLPI_LOCK_DIR: /var/www/html/files/_lock GLPI_LOG_DIR: /var/www/html/files/_log GLPI_PICTURE_DIR: /var/www/html/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins GLPI_RSS_DIR: /var/www/html/files/_rss GLPI_SESSION_DIR: /var/www/html/files/_sessions GLPI_TMP_DIR: /var/www/html/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/locales GLPI_VERSION: 9.5.7 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/var/www/html/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/vendor/sabre/http/lib) sabre/uri in (/var/www/html/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/vendor/symfony/console) scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src) psr/log in (/var/www/html/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Server: '172.17.202.100', Port: '389', BaseDN: 'dc=xxx,dc=com,dc=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'cn=S0115,ou=User,ou=Users,ou=XXX,dc=xxx,dc=com,dc=local', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (xxx@xxx.com@smtp.office365.com)

Name: 'helpdesk-xxx-it@xxx.com' Active: Yes 	Server: '{outlook.office365.com:993/imap/ssl}INBOX' Login: 'xxx@xxx.com' Password: Yes

news                 Name: Alarme                         Version: 1.9.1      State: Not installed 	order                Name: Bestellverwaltung              Version: 2.7.6      State: Enabled 	datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled 	domains              Name: Domains                        Version: 2.2.1      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.12.5     State: To update 	fusioninventory      Name: FusionInventory                Version: 9.5+4.1    State: Enabled 	addressing           Name: IP Adressierung                Version: 2.9.1      State: Enabled 	ldapcomputers        Name: LDAP computers                 Version: 0.4.1      State: Installed / not activated 	mreporting           Name: More Reporting                 Version: 1.7.4      State: Enabled 	genericobject        Name: Objects management             Version: 2.11.1     State: Enabled 	tag                  Name: Tag Management                 Version: 2.8.3      State: Not installed
[/code]

### Anything else?

Screenshot after import groups.
![20220729_100218_glpi-groups](https://user-images.githubusercontent.com/8577568/181661645-df4a45fe-7c54-4596-92ea-c4fe22bf746e.png)

**Comment by wadaki** [comment]
How can I fix the import of LDAP groups? I think this issue is on GLPI 10 present.

**Comment by wadaki** [comment]
Nobody here?

**Comment by chris-974** [comment]
I have the same problem with GLPI V10.0.2
I don't use any cron but i do it manually.

**Comment by wadaki** [comment]
Please re-open this issue. And let me know, how I can help with log files or similar.

**Comment by wadaki** [comment]
Can we do some tests and fix the bug please

**Comment by cedric-anne** [comment]
Hi,

From what I know, issues relating to LDAP functionality are rarely addressed by community maintainers. Those that I know work in an environment where there is no LDAP and do not have LDAP administration skills, which complicates the work of analyzing/testing/fixing these kinds of problems. If you want a quick answer on this, you should consider asking for [professional support](https://glpi-project.org/subscriptions/).

Regards

**Comment by cconard96** [comment]
Please test with 10.0.7.

Under Active Directory, I added a group named "#hash" and added a user to it.
In GLPI, this group showed up and was able to be imported properly.

I think there were a few patches made regarding LDAP and special characters since this issue was reported and this was likely already fixed by one of them.

**Comment by trasher** [comment]
No feedback from a while, closing.
