### ISSUE TITLE
Ticket email notifications are not sent in response.

### ISSUE THREAD

**Issue by auguzsto** [glpi-project/glpi#12325]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

I'll give an example that I think I can explain better.

I open a ticket, let's say it's the first one. It is classified as New Ticket and will have ID 00001. A notification is sent to me about this open ticket. The technician sends a solution response within this ticket. Instead of the notification being sent to me as an email reply, GLPI creates a new document to send, thus generating two emails instead of just one reply in the New Ticket email, thus making an update of the email that has already been sent to me. A simple demo in the image below.
![image](https://user-images.githubusercontent.com/40308971/181601698-4336cfa3-0c23-475f-863f-d35f1ab5804f.png)
In the image, we can see that 3 email documents were generated from the same ticket. The first, from bottom to top, is an email about the opening of the New Ticket. The second is an alteration of this same ticket, in this case, a resolved ticket response. The third is a rejected solution answer. I would like these ticket changes to be appended to the first email, to the New Ticket open email, as if it were a response, instead of forming 3 email documents. I would like to know if there is a way to do this.

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.2 ( => /var/www/html)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux ncsglpi 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at chamado Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/www/html/files/_cache has been validated.
Write access to /var/www/html/config has been validated.
Write access to /var/www/html/files/_cron has been validated.
Write access to /var/www/html/files has been validated.
Write access to /var/www/html/files/_dumps has been validated.
Write access to /var/www/html/files/_graphs has been validated.
Write access to /var/www/html/files/_lock has been validated.
Write access to /var/www/html/files/_pictures has been validated.
Write access to /var/www/html/files/_plugins has been validated.
Write access to /var/www/html/files/_rss has been validated.
Write access to /var/www/html/files/_sessions has been validated.
Write access to /var/www/html/files/_tmp has been validated.
Write access to /var/www/html/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html
GLPI_CONFIG_DIR: /var/www/html/config
GLPI_VAR_DIR: /var/www/html/files
GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/files
GLPI_CACHE_DIR: /var/www/html/files/_cache
GLPI_CRON_DIR: /var/www/html/files/_cron
GLPI_DUMP_DIR: /var/www/html/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales
GLPI_LOCK_DIR: /var/www/html/files/_lock
GLPI_LOG_DIR: /var/www/html/files/_log
GLPI_PICTURE_DIR: /var/www/html/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins
GLPI_RSS_DIR: /var/www/html/files/_rss
GLPI_SESSION_DIR: /var/www/html/files/_sessions
GLPI_TMP_DIR: /var/www/html/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/vendor/psr/cache/src)
league/csv in (/var/www/html/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/vendor/symfony/cache)
html2text/html2text in (/var/www/html/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/vendor/symfony/polyfill-php81)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'local', Port: '389', BaseDN: 'dc=local,dc=LOCAL', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'glpi@local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (chamado@local.com@email-ssl.com.br)

</details><details><summary>Plugins list</summary><pre> 
	printercounters      Name: Contadores de impressora       Version: 2.0.0      State: Not installed                           
		Install Method: Marketplace
	addressing           Name: Endereçamento IP               Version: 3.0.0      State: Error / to clean                        
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.12.0     State: Error / to clean                        
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.3      State: Enabled                                 
		Install Method: Marketplace
	releases             Name: Liberações                     Version: 2.0.3      State: Not installed                           
		Install Method: Marketplace
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Mais Relatórios                Version: 1.8.0      State: Error / to clean                        
		Install Method: Manual
	satisfaction         Name: Mais satisfação                Version: 1.6.0      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.0      State: Error / to clean                        
		Install Method: Manual
	additionalalerts     Name: Outros alertas                 Version: 2.4.0      State: Error / to clean                        
		Install Method: Manual
	vizir                Name: Vizir                          Version: 1.1.1      State: Not installed                           
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.0      State: Error / to clean                        
		Install Method: Manual

</pre></details>

**Comment by auguzsto** [comment]
:(

**Comment by ConsultechLtda** [comment]
Hello Mateus.

I have the same issue, no solutions yet?

![image](https://user-images.githubusercontent.com/113454647/189940043-68648072-f5ca-494a-920a-e581a99d2874.png)
![ERROR](https://user-images.githubusercontent.com/113454647/189940162-c2170e90-8296-49aa-9136-aa8602e74058.jpg)

**Comment by auguzsto** [comment]
Boa tarde! Não entendi muito bem.. Você está com dificuldades para configurar o envio do e-mail. É isso?

**Comment by ConsultechLtda** [comment]
Ola, Matheus.

 

Eu fiz todas as configurações, mas estou com o mesmo BUG que você mencionou para SNMP, recebi hoje a confirmação que saiu a versão 10.0.0.3, acredito que essa versão tenha ajustado essa falha.

 

Atenciosamente.

Guilherme Dutra Cassiano | Consultor em Tecnologia da Informação

Mobile: +55 (11) 99959-4549 | +55 62 99322-8549

E-mail:  ***@***.***> ***@***.***
Site: https://www.consultech.tec.br   

Linkedin:  <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/> https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/

 <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>  <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/> 

 

 <https://calendly.com/guilherme-cassiano-consultech> Clique aqui e agende a sua reunião

**Comment by trasher** [comment]
@auguzsto @ConsultechLtda please write in **english only** as requested. Thank you.

**Comment by bigparty2** [comment]
@ConsultechLtda @auguzsto  Did last glpi release (10.0.3) fix this?

**Comment by ConsultechLtda** [comment]
Hello William!

 

Good night!!!

 

So, about the GLPi, do you finish the installation version 10.0.3 and the issue about SNMP solved?

 

Kauê Gomes,

 

William is responsible for GLPi

 

Regards.

Guilherme Dutra Cassiano | Consultor em Tecnologia da Informação

Mobile: +55 (11) 99959-4549 | +55 62 99322-8549

E-mail:  ***@***.***> ***@***.***
Site: https://www.consultech.tec.br   

Linkedin:  <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/> https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/

 <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>  <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/> 

 

 <https://calendly.com/guilherme-cassiano-consultech> Clique aqui e agende a sua reunião

**Comment by yurinasc** [comment]
Boa tarde, estou com o mesmo problema. estou na versão 9.5.7, para que de certo preciso fazer a instalação da versão 10.0.3?

**Comment by ConsultechLtda** [comment]
Hello Yuri!

 

Good day for you!

 

Ate you using google account? I had this problem only google account.

 

Regards.

Guilherme Dutra Cassiano | Consultor em Tecnologia da Informação

Mobile: +55 (11) 99959-4549 | +55 62 99322-8549

E-mail:  ***@***.***> ***@***.***
Site: https://www.consultech.tec.br   

Linkedin:  <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/> https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/

 <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>  <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/>   <https://www.linkedin.com/in/guilherme-dutra-cassiano-82823124/> 

 

 <https://calendly.com/guilherme-cassiano-consultech> Clique aqui e agende a sua reunião

**Comment by trasher** [comment]
@yurinasc english only as already requested once here!
