### ISSUE TITLE
php error comes back

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1233]
Hello

1 - I have an error very often, when we create a task and click on add a message "lost" appears and the content of the task is lost.  

2 - a recurrent ticket does not start every morning : 

the cron does not start recurrent ticket in spite of other tasks start normally

2016-11-02 08:21:20 [854@UNGSRVGVA118]
  *** PHP Notice(8): Uninitialized string offset: 0
  Backtrace :
  inc\commonitilobject.class.php:1356                
  inc\ticket.class.php:1746                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:844                       Ticket->post_addItem()
  inc\ticketrecurrent.class.php:481                  CommonDBTM->add()
  inc\ticketrecurrent.class.php:424                  TicketRecurrent::createTicket()
  inc\crontask.class.php:834                         TicketRecurrent::cronTicketRecurrent()
  front\crontask.form.php:50                         CronTask::launch()

**Comment by tomolimo** [comment]
Hello,
Could you give more info about your GLPi configuration?
Thank you,
Regards,
Tomolimo

**Comment by satyan01** [comment]
windows 2012 r2 / glpi 9.1 / php 7.04 / mariadb 10.1

**Comment by stonebuzz** [comment]
Hello @satyan01 , have you resolved your issue ?
Do you have a solution to propose?

Thanks,
