### ISSUE TITLE
Upgrade Bug GLPI 10.0

### ISSUE THREAD

**Issue by hadesmaster81** [glpi-project/glpi#12338]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7 

### Bug description

When updating GLPI version 9.5.7 to 10.0.2, we cannot update because of below error.

![image](https://user-images.githubusercontent.com/110244906/181784299-4c0abb06-bb5a-4bad-ab51-18af3d7a7a88.png)

**Comment by cedric-anne** [comment]
Hi,

Something probably goes wrong by the past in migration to GLPI 9.2.x. You should fix manually your DB by executing following request: ``` ALTER TABLE `glpi_slas` CHANGE `slas_id` `slms_id` INT NOT NULL DEFAULT '0' ```.

**Comment by hadesmaster81** [comment]
Thank you for your help, the migration to 10.0.2 is now effective.

![image](https://user-images.githubusercontent.com/110244906/182135115-2be552a1-3afb-42bb-97fe-20debe31c8fc.png)

On the other hand, the integrity of the database does not seem to be in conformity. As you can see below:

php bin/console glpi:database:check_schema_integrity
Le schéma diffère pour la table "glpi_savedsearches".
--- Original
+++ New
@@ @@
   `type` int NOT NULL DEFAULT 0,
   `users_id` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
-  KEY `do_count` (`do_count`),
   KEY `entities_id` (`entities_id`),
   KEY `is_private` (`is_private`),
   KEY `is_recursive` (`is_recursive`),
   KEY `itemtype` (`itemtype`),
-  KEY `last_execution_date` (`last_execution_date`),
-  KEY `last_execution_time` (`last_execution_time`),
   KEY `name` (`name`),
   KEY `type` (`type`),
   KEY `users_id` (`users_id`)
 )
Le schéma diffère pour la table "glpi_changes".
--- Original
+++ New
@@ @@
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
   KEY `date` (`date`),
+  KEY `due_date` (`time_to_resolve`),
   KEY `entities_id` (`entities_id`),
   KEY `global_validation` (`global_validation`),
   KEY `impact` (`impact`),
@@ @@
   KEY `priority` (`priority`),
   KEY `solvedate` (`solvedate`),
   KEY `status` (`status`),
-  KEY `time_to_resolve` (`time_to_resolve`),
   KEY `urgency` (`urgency`),
   KEY `users_id_lastupdater` (`users_id_lastupdater`),
   KEY `users_id_recipient` (`users_id_recipient`)
 )
Le schéma diffère pour la table "glpi_networkequipments".
--- Original
+++ New
@@ @@
   `locations_id` int NOT NULL DEFAULT 0,
   `manufacturers_id` int NOT NULL DEFAULT 0,
   `name` varchar(255),
+  `networkequipmentfirmwares_id` int NOT NULL DEFAULT 0,
   `networkequipmentmodels_id` int NOT NULL DEFAULT 0,
   `networkequipmenttypes_id` int NOT NULL DEFAULT 0,
   `networks_id` int NOT NULL DEFAULT 0,
@@ @@
   KEY `locations_id` (`locations_id`),
   KEY `manufacturers_id` (`manufacturers_id`),
   KEY `name` (`name`),
+  KEY `networkequipmentfirmwares_id` (`networkequipmentfirmwares_id`),
   KEY `networkequipmentmodels_id` (`networkequipmentmodels_id`),
   KEY `networkequipmenttypes_id` (`networkequipmenttypes_id`),
   KEY `networks_id` (`networks_id`),
Le schéma diffère pour la table "glpi_problems".
--- Original
+++ New
@@ @@
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
   KEY `date` (`date`),
+  KEY `due_date` (`time_to_resolve`),
   KEY `entities_id` (`entities_id`),
   KEY `impact` (`impact`),
   KEY `is_deleted` (`is_deleted`),
@@ @@
   KEY `priority` (`priority`),
   KEY `solvedate` (`solvedate`),
   KEY `status` (`status`),
-  KEY `time_to_resolve` (`time_to_resolve`),
   KEY `urgency` (`urgency`),
   KEY `users_id_lastupdater` (`users_id_lastupdater`),
   KEY `users_id_recipient` (`users_id_recipient`)
 )
Le schéma diffère pour la table "glpi_slalevels".
--- Original
+++ New
@@ @@
   KEY `is_active` (`is_active`),
   KEY `is_recursive` (`is_recursive`),
   KEY `name` (`name`),
-  KEY `slas_id` (`slas_id`)
+  KEY `slts_id` (`slas_id`)
 )
Le schéma diffère pour la table "glpi_slas".
--- Original
+++ New
@@ @@
   KEY `entities_id` (`entities_id`),
   KEY `is_recursive` (`is_recursive`),
   KEY `name` (`name`),
-  KEY `slms_id` (`slms_id`)
+  KEY `slas_id` (`slms_id`)
 )
Le schéma diffère pour la table "glpi_tickets".
--- Original
+++ New
@@ @@
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
   KEY `date` (`date`),
+  KEY `due_date` (`time_to_resolve`),
   KEY `entities_id` (`entities_id`),
   KEY `global_validation` (`global_validation`),
   KEY `impact` (`impact`),
@@ @@
   KEY `solvedate` (`solvedate`),
   KEY `status` (`status`),
   KEY `time_to_own` (`time_to_own`),
-  KEY `time_to_resolve` (`time_to_resolve`),
   KEY `type` (`type`),
   KEY `urgency` (`urgency`),
   KEY `users_id_lastupdater` (`users_id_lastupdater`),
   KEY `users_id_recipient` (`users_id_recipient`)
 )
Table "glpi_dropdown_plugin_certificates_status" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_certificates_status` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `FK_entities` int NOT NULL DEFAULT 0,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)
Table "glpi_dropdown_plugin_backups_scripts_type" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_backups_scripts_type` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)
Table "glpi_dropdown_plugin_backups_history_status" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_backups_history_status` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)
Table "glpi_tickets_export" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_tickets_export` (
+  `id` int NOT NULL AUTO_INCREMENT,
+  `actiontime` int NOT NULL DEFAULT 0,
+  `begin_waiting_date` datetime,
+  `close_delay_stat` int NOT NULL DEFAULT 0,
+  `closedate` varchar(20),
+  `content` text,
+  `cost_fixed` decimal(20,4) NOT NULL DEFAULT 0.0000,
+  `cost_material` decimal(20,4) NOT NULL DEFAULT 0.0000,
+  `cost_time` decimal(20,4) NOT NULL DEFAULT 0.0000,
+  `date_mod` varchar(20),
+  `date` varchar(20),
+  `due_date` datetime,
+  `entities_id` int NOT NULL DEFAULT 0,
+  `global_validation` varchar(255) DEFAULT 'none',
+  `impact` int NOT NULL DEFAULT 1,
+  `items_id` int NOT NULL DEFAULT 0,
+  `itemtype` varchar(100) NOT NULL,
+  `name` varchar(255),
+  `priority` int NOT NULL DEFAULT 1,
+  `requesttypes_id` int NOT NULL DEFAULT 0,
+  `sla_waiting_duration` int NOT NULL DEFAULT 0,
+  `slalevels_id` int NOT NULL DEFAULT 0,
+  `slas_id` int NOT NULL DEFAULT 0,
+  `solution` text,
+  `solve_delay_stat` int NOT NULL DEFAULT 0,
+  `solvedate` varchar(20),
+  `status` varchar(255) DEFAULT 'new',
+  `suppliers_id_assign` int NOT NULL DEFAULT 0,
+  `takeintoaccount_delay_stat` int NOT NULL DEFAULT 0,
+  `ticket_waiting_duration` int NOT NULL DEFAULT 0,
+  `ticketcategories_id` int NOT NULL DEFAULT 0,
+  `ticketsolutiontypes_id` int NOT NULL DEFAULT 0,
+  `type` int NOT NULL DEFAULT 1,
+  `urgency` int NOT NULL DEFAULT 1,
+  `users_id_lastupdater` varchar(255) NOT NULL DEFAULT 0,
+  `users_id_recipient` varchar(255) NOT NULL DEFAULT 0,
+  PRIMARY KEY (`id`),
+  KEY `closedate` (`closedate`),
+  KEY `date_mod` (`date_mod`),
+  KEY `date` (`date`),
+  KEY `due_date` (`due_date`),
+  KEY `entities_id` (`entities_id`),
+  KEY `global_validation` (`global_validation`),
+  KEY `impact` (`impact`),
+  KEY `item` (`itemtype`,`items_id`),
+  KEY `priority` (`priority`),
+  KEY `request_type` (`requesttypes_id`),
+  KEY `slalevels_id` (`slalevels_id`),
+  KEY `slas_id` (`slas_id`),
+  KEY `solvedate` (`solvedate`),
+  KEY `status` (`status`(1)),
+  KEY `suppliers_id_assign` (`suppliers_id_assign`),
+  KEY `ticketcategories_id` (`ticketcategories_id`),
+  KEY `ticketsolutiontypes_id` (`ticketsolutiontypes_id`),
+  KEY `type` (`type`),
+  KEY `urgency` (`urgency`),
+  KEY `users_id_lastupdater` (`users_id_lastupdater`),
+  KEY `users_id_recipient` (`users_id_recipient`)
+)
Table "glpi_dropdown_plugin_certificates_type" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_certificates_type` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `FK_entities` int NOT NULL DEFAULT 0,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)
Table "glpi_dropdown_plugin_backups_works_type" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_backups_works_type` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)
Table "glpi_dropdown_plugin_backups_works_periodicity" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_backups_works_periodicity` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)
Table "glpi_dropdown_plugin_backups_tapes_type" inconnue trouvée dans la base de données.
--- Original
+++ New
@@ @@
+CREATE TABLE `glpi_dropdown_plugin_backups_tapes_type` (
+  `ID` int NOT NULL AUTO_INCREMENT,
+  `comments` text,
+  `name` varchar(255) NOT NULL DEFAULT '',
+  PRIMARY KEY (`ID`),
+  KEY `name` (`name`)
+)

Is there a script to restore database integrity?

If I understand correctly, I can delete all unknown tables?

But when it comes to tables that are different, how do you know if they are renames of old tables or creations? Can you help me on this?

Thanks, have a good day

**Comment by cedric-anne** [comment]
There is no script to restore database integrity. Known issues that are related to known bugs are fixed automatically, but other issues requires often a manual fix.

You have to read this like a diff. A line prefixed by a `-` means that we did not found an expected element, and a line prefixed by a `+` means that we found an unexpected element. As for any database operation, a backup should be done before applying any change, and changes should be made by a database administrator.

1. Unknown tables are not used by GLPI, and, according to their name, should not be used by plugins, but we cannot assert that your GLPI instance does not have any custom patch or any plugin that does not respect naming conventions.
2. Same remark for `glpi_networkequipments.networkequipmentfirmwares_id` field.
3. Other differences are only related to indexes. Indexes are only used to enhance performances of database and does not contains data. You can rename thoose that are not named correclty, and add thoose that are missing.

If you need more help, you can use [forums](https://forum.glpi-project.org/), or consider taking a subscription to get [professionnal support](https://services.glpi-network.com/).

This problem cannot be reproduced now, as it is probably related to migrations to GLPI 9.2.x, and so it cannot be fixed by a code change. So I close this issue as we only track active and fixable bugs here.
