### ISSUE TITLE
IMAP receiver not working with office 365

### ISSUE THREAD

**Issue by enannos** [glpi-project/glpi#12331]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7 and 10.0.2

### Bug description

Deprecation of Basic authentication in Exchange Online

Dear GLPI developers,

Microsoft has deprecated the Basic authentication in Exchange Online. 
Read the related document from [microsoft here](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online#re-enabling-and-opting-out-of-proactive-protection).

Our email **receiver** is not working anymore. 
Microsoft will completely disable the Basic auth for Outlook, EWS, RPS, POP, IMAP, and EAS protocols in Exchange Online in **October 1,2022**. 

We have also tried with port 995, SSL, TLS, all the possible combinations.

When we try to use SSL, GLPI is not responding for 30 seconds(php timeout).

Can you please have a look at this issue? 
Are other users facing the same issue?

If you use Exchange Online to receive emails and it works, do you have a setup example?

Thank you
Best regards
Evangelos

### Relevant log output

```shell
[2022-07-29 10:52:02] glpiphplog.ERROR: MailCollector::collect() in /var/www/html/glpi/inc/mailcollector.class.php line 689
An error occured trying to connect to collector. cannot login, user or password wrong
 #0 /var/www/html/glpi/inc/toolbox.class.php(2348): Laminas\Mail\Storage\Imap->__construct()
#1 /var/www/html/glpi/inc/mailcollector.class.php(1342): Toolbox::getMailServerStorageInstance()
#2 /var/www/html/glpi/inc/mailcollector.class.php(683): MailCollector->connect()
#3 /var/www/html/glpi/inc/mailcollector.class.php(1762): MailCollector->collect()
#4 /var/www/html/glpi/inc/crontask.class.php(943): MailCollector::cronMailgate()
#5 /var/www/html/glpi/front/cron.php(83): CronTask::launch()
```

### Steps To reproduce

Server: outlook.office365.com

IMAP port 143

![grafik](https://user-images.githubusercontent.com/8511600/181723126-a4b86a4f-e2a7-49b7-a594-ce350b059980.png)

**Comment by cedric-anne** [comment]
Hi,

There is a plugin that handles Oauth authentication on IMAP: https://github.com/pluginsGLPI/oauthimap.

**Comment by enannos** [comment]
> 

That did the trick, thank you!

The issue can be closed.

Best regards,
Evangelos
