### ISSUE TITLE
Code does not allow persistent database connections prefix in dbhost ('p:')

### ISSUE THREAD

**Issue by sciaw** [glpi-project/glpi#12330]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

If one tries to use php mysqli persistent database connection string (ex: p:dbserver.domain.tld) in dbhost config variable glpi doesn't work with databse connection error.

For instance using as dbhost:
```php
$dbhost = 'p:dbserver.domain.tld';
$dbhost = 'p:dbserver.domain.tld:3306';
$dbhost = 'p:dbserver';
$dbhost = 'p:dbserver:3306';
```

The only problem is a simple check made in https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/DBmysql.php#L248, because as one can see for persistent connections we also use ":" to separator (as for port)
```php
$hostport = explode(":", $host);
if (count($hostport) < 2) {
```
So, probably, adding a small if should fix the issue, something like this
```php
$hostport = explode(":", $host);
        
// For persistent mysqli connections ex: p:dbserver.domain.tld
if ($hostport[0] === 'p')
{
	array_shift($hostport);
	$hostport[0] = 'p:' . $hostport[0];
}
        
if (count($hostport) < 2) {
```
Tested, with or without the persistent prefix, and worked.

### Anything else?

![image](https://user-images.githubusercontent.com/89925315/181712855-05895e85-a8ca-450c-9ffd-0af40240ccca.png)
See https://www.php.net/manual/en/mysqli.persistconns.php

**Comment by cconard96** [comment]
I'm not sure that just adding the needed change to parse the host correctly when it has this prefix would be a good idea.

Since we have always had the connection closed at the end of a request, I don't know that everything gets cleaned up manually that would need to like transactions and locks especially if an error occurs and the request session dies.
