### ISSUE TITLE
GLPI 10.2 fails to decompress OCS Agent XML inventory

### ISSUE THREAD

**Issue by Mirkk** [glpi-project/glpi#12355]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Dear all,

I tried to send an OCSInventory Agent inventory to the GLPI native inventory (endpoint inventory.php), which should be possible as it is also written in the GLPI News for version 10: "New API REST (front/inventory.php) will be available to receive inventory files in historical format (OCS, fusioninventory)".

It fails with the following error message:
glpiphplog.WARNING:   *** PHP User Warning (512): Start tag expected, '<' not found in  at line 1
  Backtrace : 
  src/Agent/Communication/AbstractRequest.php:235    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()

GLPI 10.02, latest GLPI Inventory plugin installed (should not be relevant for this particular issue)

OCS Agent sends the data in POST with the following Content-Type: **application/x-compressed**
(I tried with Windows version 2.7 but all versions >2.0 seem to have the same content-type in ComHTTP/HTTPConnexion.cpp and the same compression and XML format).

In glpi/src/Agent/Communication/AbstractRequest.php, function handleContentType
many content types are parsed. "application/x-compressed" is missing - I tested adding it to every part of the "switch" statement there, but none of them seems to be able to uncompress it.

Output of  glpi:system:check_requirements:
 [SUGGESTED] zip extension                                              | [OK]    |                                                             |
| Enable installation of zip packages from marketplace.                  |         |                                                             |
| [SUGGESTED] bz2 extension                                              | [OK]    |                                                             |
| Enable installation of bz2 packages from marketplace.                  |         |    
(Note: everything installed except sodium).

Did someone success in sending OCS data to GLPI 10? Does someone have a hint, or is there some bug?

Thank you very much!

### Relevant log output

```shell
glpiphplog.WARNING:   *** PHP User Warning (512): Start tag expected, '<' not found in  at line 1
  Backtrace : 
  src/Agent/Communication/AbstractRequest.php:235    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
```

### Steps To reproduce

Configure an OCS Agent to send the results to GLPI native inventory [...]/glpi/inventory.php, like in the configuration of GLPI Agents (which work correctly for me).

### Your GLPI setup information

Operating system: Linux rhel8 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Mon Oct 18 14:34:11 EDT 2021 x86_64
PHP 7.4.6 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MariaDB Server
	Server Version: 10.3.28-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@mariadb.neteyelocal/glpi
	Host info: mariadb.neteyelocal via TCP/IP
	
PHP version (7.4.6) is supported.PHP version (7.4.6) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.

exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /usr/share/glpi/marketplace has been validated.Write access to /usr/share/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cconard96** [comment]
I started looking into this yesterday.
The `application/x-compressed` content type is not standard and not widely used but the agent seems to use ZLib compression.
The compressed content is not recognized by the PHP `gzuncompress` function so it may be missing the checksum at the end, There is a workaround that I was able to use to decompress the data properly in the PROLOG request the agent sent.

The agent then sent a notify query which was not handled by the GLPI native inventory. I'm not quite sure the best way to handle that query, but just silently accepted the request (return an OK status) and finally got the agent to send the actual inventory but it didn't validate because of a missing "versionclient" property (at least).

That is as far as I was able to get with troubleshooting the compatibility issues with the OCS agent.

**Comment by trasher** [comment]
ocs agent is not supported, you'd better use ocs plugin.

**Comment by Mirkk** [comment]
Wow, thanks Curtis!
@trasher it was mentioned in the GLPI news that the OCS inventory files are supported. The OCS server+glpi plugin have quite some synchronisation issues and using the GLPI native inventory also with the old agents around which are difficult to update in huge, non standardized environments.

As I understood from @cconard96 the issue is the compression and "handshaking" and you were already nearly able to make it run. The real content, the inventory XML, should be already compatible, right?

**Comment by trasher** [comment]
OCS XML format may be supported, all I can say is very old files I had in stock are working. Communicaiton with agent is not supported at all, and differences from FI XML format are not supported...

So yes, XML plain format **may** be compatible, but OCS current format is not officially supported from native inventory. Some things may be missing/not working.

**Comment by Mirkk** [comment]
Thanks for the clear and fast answer. That's not what I expected from the sentence "receive inventory files in OCS format" (and this is why I tried it and opened the bug), but I can fully understand that you referred to the historical OCS format once adopted by Fusion. Ok, nevertheless, it would have been just a feture for "transitional" use, until the GLPI Agent is installed everywhere.
Best regards!
