### ISSUE TITLE
Task modification problem since August 1, 2022: The INTERVAL rule part must be a positive integer (> 0)

### ISSUE THREAD

**Issue by support-gaesi** [glpi-project/glpi#12356]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Hi there,

I am having problems with GLPI when editing tickets.

Information :
GLPI Version: 10.0.2
Plugin:
- Fusion inventory
- Credits
- Dashboard
- FormCreation
- TaskDrop

Last week, I could not schedule a task after the date of August 1, 2022, it is August 1, 2022 and I cannot schedule a ticket task and cannot modify tickets.

Each change displays this message:

`Uncaught Exception InvalidArgumentException: The INTERVAL rule part must be a positive integer (> 0) in /var/www/glpi/vendor/rlanvin/php-rrule/src/RRule.php at line 254`

In the logs I get this message:

```
[2022-08-01 10:20:00] glpiphplog.CRITICAL: *** Uncaught Exception InvalidArgumentException: The INTERVAL rule part must be a positive integer (> 0) in /var/www/glpi/vendor/rlanvin/php- rrule/src/RRule.php at line 254
  Backtrace:
  src/Features/PlanningEvent.php:925 RRule\RRule->__construct()
  src/Features/PlanningEvent.php:606 PlanningExternalEvent::getRsetFromRRuleField()
  src/Planning.php:290 PlanningExternalEvent::populatePlanning()
  src/CommonITILTask.php:322 Planning::checkAlreadyPlanned()
  src/CommonDBTM.php:1572 CommonITILTask->prepareInputForUpdate()
  front/commonitiltask.form.php:94 CommonDBTM->update()
  front/tickettsk.form.php:39 include()
```

Obviously in the **RRule.php** file the variable **$parts['INTERVAL']** returns the value **0**

**I don't understand where the problem comes from, I deactivated my plugins but that doesn't change anything.**

**I updated GLPI v9.5 to GLPI v10.0.2, but that doesn't change anything either.**

**I even did a brand new installation of GLPI, then I connected it to my GLPI database and I still encounter the problem.**

Looking forward to your feedback and your help, thank you in advance!

### Relevant log output

```shell
[2022-08-01 10:20:00] glpiphplog.CRITICAL:   *** Uncaught Exception InvalidArgumentException: The INTERVAL rule part must be a positive integer (> 0) in /var/www/glpi/vendor/rlanvin/php-rrule/src/RRule.php at line 254
  Backtrace :
  src/Features/PlanningEvent.php:925                 RRule\RRule->__construct()
  src/Features/PlanningEvent.php:606                 PlanningExternalEvent::getRsetFromRRuleField()
  src/Planning.php:290                               PlanningExternalEvent::populatePlanning()
  src/CommonITILTask.php:322                         Planning::checkAlreadyPlanned()
  src/CommonDBTM.php:1572                            CommonITILTask->prepareInputForUpdate()
  front/commonitiltask.form.php:94                   CommonDBTM->update()
  front/tickettask.form.php:39                       include()
```

### Page URL

https://glpi.gaesi.fr/front/tickettask.form.php

### Steps To reproduce

1. Go to a ticket
2. Modify a task
3. Scheduled the task for (or after) August 1, 2022
4. Blank page appears (if debug activated, error message linked to INTERVAL)
5. F5
6. Message you are not allowed to do this

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.2 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux ZERO2 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64
PHP 8.0.21 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi.gaesi.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.0.21) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/var/www/glpi/vendor/symfony/polyfill-php81)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (ticket@gaesi.fr@smtp.office365.com)

</details><details><summary>Plugins list</summary><pre> 
	credit               Name: Crédits                        Version: 1.11.2     State: Installed / not activated               
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0-rc.2 State: Installed / not activated               
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: To update                               
		Install Method: Manual
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

It seems that you have inconsistent data in your database.
What is the result of SQL request ``` SELECT `id`, `rrule` FROM `glpi_planningexternalevents` WHERE `rrule` != '' ``` ?

**Comment by support-gaesi** [comment]
Hello, thank you for your help.

I ran the query and got about 20 responses.
  
1 	{"freq":"daily","interval":"1","until":"2020-12-05...
4 	{"freq":"daily","interval":"1","until":"2021-02-13...
5 	{"freq":"daily","interval":"1","until":"2021-05-01...
6 	{"freq":"daily","interval":"1","until":"2021-07-17...
7 	{"freq":"daily","interval":"1","until":"2020-12-05...
9 	{"freq":"daily","interval":"1","until":"2021-02-13...
10 	{"freq":"daily","interval":"1","until":"2021-05-01...
11 	{"freq":"daily","interval":"1","until":"2021-07-17...
16 	{"freq":"daily","interval":"1","until":"2021-01-15...
27 	{"freq":"weekly","interval":"1","until":"","except...
34 	{"freq":"weekly","interval":"1","until":"2022-10-2...
70 	{"freq":"weekly","interval":"1","until":"2022-10-2...
104 	{"freq":"weekly","interval":"1","until":"","except...
114 	{"freq":"daily","interval":"1","until":"2021-11-11...
115 	{"freq":"daily","interval":"1","until":"2022-01-30...
116 	{"freq":"daily","interval":"1","until":"2022-04-17...
117 	{"freq":"daily","interval":"1","until":"2022-07-03...
218 	{"freq":"monthly","interval":"0","until":""}

These are external tasks that we have planned once a week for example or once a month.

**Comment by support-gaesi** [comment]
I see that this line is at 0 at the interval level:
218 {"freq":"monthly","interval":"0","until":""}

Would the problem be this?

**Comment by cedric-anne** [comment]
Task with ID 218 has a 0 interval, issue probably comes from it. `interval` value has to be changed to 1.

**Comment by support-gaesi** [comment]
Thank you very much for your help, I would never have found this on my own.

I allow myself to close this ticket and I will also make an answer on the glpi-project forum, because it could help others in the future.
