### ISSUE TITLE
Problem with AD users in local group and authorization rules

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#12367]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.8

### Bug description

When users from AD/LDAP are added to a local group , the authorization rule does not grant permissions to users based on this group It only grants permissions to local users in the group.

Rule:
group is "INTERNAL_GLPI_GROUP with AD users and local users".

Profile Assign Profile1
Unit Assign Unit1
Recursively Assign Yes

There is a similar problem when using groups with users synchronized with AD.

### Steps To reproduce

1. Make local group with AD and local users
2. Make authorization rule
3. log in

**Comment by Wolvverine** [comment]
The problem is still

**Comment by trasher** [comment]
10.0.3 is outdated, try with up to date version.
