### ISSUE TITLE
List of virtual machines' host incorrect naming

### ISSUE THREAD

**Issue by Poulpi4Ever** [glpi-project/glpi#12365]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

When linking a virtual machine to its host, in the Virtualization tab of the VM, the host is listed in a "List of virtualized environments", which is quite surprising.

### Page URL

/front/computer.form.php

### Steps To reproduce

1. create a VM computer in assets, with an UUID
2. link the VM to a physical computer (host) using the Virtualization tab and the UUID of the VM
3. go to the VM's form, in the tab Virtualization
4. See the first list named "List of virtualized environments", in which you can find the name of the host

### Anything else?

This issue is present in several translations (I checked the French and Canadian French translations, as well as the English one), but giving the structure of their translation files, I guess it is the same for all translations.

I was able to correct this by making simple changes in two documents : 
- **in src/ComputerVirtualMachine.php in the function showForVirtualMachine, line 252 :** changed `'List of virtualized environment'` to `'List of host machines'`
- **in locales/fr_FR.po from line 13044 :** changed 
```
#: src/ComputerComputerVirtualMachine.php:252 src/ComputerVirtualMachine.php:344
msgid "List of virtualized environments"
msgstr "Liste des machines virtuelles"
```
to 
```
#: src/ComputerVirtualMachine.php:344
msgid "List of virtualized environments"
msgstr "Liste des machines virtuelles"

#: src/ComputerComputerVirtualMachine.php:252
msgid "List of host machines"
msgstr "Liste des machines hôtes"
```

This is the example for the French version, but the second modification is essentially the same for all translations.
In order to see the modification appear on my local GLPI, I had to clear GLPI's cache. 

I didn't post this as a pull request, since I cannot translate this in all the languages available in GLPI, and I wouldn't risk making a mistake in the translation by using an online translator.

**Comment by trasher** [comment]
We only add the original stirng in GLPI code, translations are all done on transifex.
