### ISSUE TITLE
Blank page when add element in ticket

### ISSUE THREAD

**Issue by NoahMautain** [glpi-project/glpi#12377]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

When wy want add elemet in ticket, we have an blank page into the part "Ticket".

### Page URL

/front/ticket.form.php

**Comment by trasher** [comment]
Requested information has not been provided. Also, try with latest release.
