### ISSUE TITLE
Self-Service simplified interface : access denied page when logging in

### ISSUE THREAD

**Issue by Poulpi4Ever** [glpi-project/glpi#12378]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0 and 10.0.2

### Bug description

When I log in with a Self-Service profile in GLPI with the simplified interface, I end up on an Access denied page, with the text "You don't have permission to perform this action."
If I refresh the page, I'm still on this Access denied page.

### Relevant log output

```shell
No log of this issue found
```

### Page URL

/front/central.php

### Steps To reproduce

1. Set the interface of the Self-Service profile to "Simplified interface"
2. Create a user with the Self-Service profile
3. Log in with the new user and you'll be on the Access denied page

### Your GLPI setup information

Can't copy and paste this, GLPI is on an isolated computer for tests

**Comment by cconard96** [comment]
Please test on the latest bug fix version (10.0.2) as a lot of issues have been fixed already since the 10.0.0 release.

**Comment by Poulpi4Ever** [comment]
I upgraded to 10.0.2, but the issue is still there
