### ISSUE TITLE
"(copy)" is added after a computer name when created from a template

### ISSUE THREAD

**Issue by GuiGuiSoft** [glpi-project/glpi#12385]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.8

### Bug description

"(copy)" is added after a computer name when it is created from a template.

### Relevant log output

```shell
No relevant log
```

### Page URL

/front/setup.templates.php?itemtype=Computer&add=1

### Steps To reproduce

1. Create a computer template
2. Create a new computer with this template
3. Save

The name of the new computer contains `(copy)`, whereas it is not a copy, just a new one.

### Your GLPI setup information

[code]
 
GLPI 9.5.8 ( => /installation_path/9.5.8)
Installation mode: TARBALL
Current language:fr_FR

Server

 
Operating system: Linux MachineName 4.15.0-189-generic #200-Ubuntu SMP Wed Jun 22 19:53:37 UTC 2022 x86_64
PHP 7.4.30 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="64M" post_max_size="3M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.29
	Server SQL Mode: 
	Parameters: usr@X.X.X.X/db
	Host info: X.X.X.X via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (8.0.29) - Perfect!Database version seems correct (8.0.29) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /installation_path/9.5.8/files/_cache has been validated.Write access to /installation_path/9.5.8/files/_cache has been validated.
Write access to /installation_path/9.5.8/config has been validated.Write access to /installation_path/9.5.8/config has been validated.
Write access to /installation_path/9.5.8/files/_cron has been validated.Write access to /installation_path/9.5.8/files/_cron has been validated.
Write access to /installation_path/9.5.8/files has been validated.Write access to /installation_path/9.5.8/files has been validated.
Write access to /installation_path/9.5.8/files/_dumps has been validated.Write access to /installation_path/9.5.8/files/_dumps has been validated.
Write access to /installation_path/9.5.8/files/_graphs has been validated.Write access to /installation_path/9.5.8/files/_graphs has been validated.
Write access to /installation_path/9.5.8/files/_lock has been validated.Write access to /installation_path/9.5.8/files/_lock has been validated.
Write access to /installation_path/9.5.8/files/_pictures has been validated.Write access to /installation_path/9.5.8/files/_pictures has been validated.
Write access to /installation_path/9.5.8/files/_plugins has been validated.Write access to /installation_path/9.5.8/files/_plugins has been validated.
Write access to /installation_path/9.5.8/files/_rss has been validated.Write access to /installation_path/9.5.8/files/_rss has been validated.
Write access to /installation_path/9.5.8/files/_sessions has been validated.Write access to /installation_path/9.5.8/files/_sessions has been validated.
Write access to /installation_path/9.5.8/files/_tmp has been validated.Write access to /installation_path/9.5.8/files/_tmp has been validated.
Write access to /installation_path/9.5.8/files/_uploads has been validated.Write access to /installation_path/9.5.8/files/_uploads has been validated.
Write access to /installation_path/9.5.8/marketplace has been validated.Write access to /installation_path/9.5.8/marketplace has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI constants

 
GLPI_ROOT: /installation_path/9.5.8
GLPI_CONFIG_DIR: /installation_path/9.5.8/config
GLPI_VAR_DIR: /installation_path/9.5.8/files
GLPI_MARKETPLACE_DIR: /installation_path/9.5.8/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /installation_path/9.5.8/files
GLPI_CACHE_DIR: /installation_path/9.5.8/files/_cache
GLPI_CRON_DIR: /installation_path/9.5.8/files/_cron
GLPI_DUMP_DIR: /installation_path/9.5.8/files/_dumps
GLPI_GRAPH_DIR: /installation_path/9.5.8/files/_graphs
GLPI_LOCAL_I18N_DIR: /installation_path/9.5.8/files/_locales
GLPI_LOCK_DIR: /installation_path/9.5.8/files/_lock
GLPI_LOG_DIR: /installation_path/9.5.8/files/_log
GLPI_PICTURE_DIR: /installation_path/9.5.8/files/_pictures
GLPI_PLUGIN_DOC_DIR: /installation_path/9.5.8/files/_plugins
GLPI_RSS_DIR: /installation_path/9.5.8/files/_rss
GLPI_SESSION_DIR: /installation_path/9.5.8/files/_sessions
GLPI_TMP_DIR: /installation_path/9.5.8/files/_tmp
GLPI_UPLOAD_DIR: /installation_path/9.5.8/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /installation_path/9.5.8/locales
GLPI_VERSION: 9.5.8
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022

Libraries

 
htmlawed/htmlawed version 1.2.5 in (/installation_path/9.5.8/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/installation_path/9.5.8/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/installation_path/9.5.8/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/installation_path/9.5.8/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/installation_path/9.5.8/vendor/michelf/php-markdown/Michelf)
true/punycode in (/installation_path/9.5.8/vendor/true/punycode/src)
iamcal/lib_autolink in (/installation_path/9.5.8/vendor/iamcal/lib_autolink)
sabre/dav in (/installation_path/9.5.8/vendor/sabre/dav/lib/DAV)
sabre/http in (/installation_path/9.5.8/vendor/sabre/http/lib)
sabre/uri in (/installation_path/9.5.8/vendor/sabre/uri/lib)
sabre/vobject in (/installation_path/9.5.8/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/installation_path/9.5.8/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/installation_path/9.5.8/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/installation_path/9.5.8/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/installation_path/9.5.8/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/installation_path/9.5.8/vendor/sebastian/diff/src)
elvanto/litemoji in (/installation_path/9.5.8/vendor/elvanto/litemoji/src)
symfony/console in (/installation_path/9.5.8/vendor/symfony/console)
scssphp/scssphp in (/installation_path/9.5.8/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/installation_path/9.5.8/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/installation_path/9.5.8/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/installation_path/9.5.8/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/installation_path/9.5.8/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/installation_path/9.5.8/vendor/ramsey/uuid/src)
psr/log in (/installation_path/9.5.8/vendor/psr/log/Psr/Log)
psr/simple-cache in (/installation_path/9.5.8/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/installation_path/9.5.8/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/installation_path/9.5.8/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/installation_path/9.5.8/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/installation_path/9.5.8/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/installation_path/9.5.8/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.3 in (/usr/share/php)

LDAP directories

 
Server: 'ldaps://ldap', Port: '636', BaseDN: 'dc=company,dc=com', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'LDAP_USER', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (anonymous@mailserver.com)

Mails receivers

 

Plugins list

 
	automatic            Name: Automatic Action CUSTO         Version: 1.0.0      State: Enabled
	badges               Name: Badges                         Version: 2.6.0      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.13.0     State: Enabled
	behaviors            Name: Comportements                  Version: 2.5.0      State: Enabled
	datainjection        Name: Data Injection                 Version: 2.10.2     State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Enabled
	manufacturersimports Name: Imports fabricants             Version: 2.3.2      State: Enabled
	matomo               Name: Matomo                         Version: 1.0.0      State: Enabled
	moreticket           Name: More ticket                    Version: 1.6.1      State: Enabled
	perception           Name: Perception CUSTO               Version: 1.1.3      State: Enabled
	satisfaction         Name: Plus de satisfaction           Version: 1.5.2      State: Enabled
	restitution          Name: Restitution CUSTO              Version: 1.1.2      State: Enabled
	rfc                  Name: rfc CUSTO                      Version: 1.0.0      State: Enabled
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Enabled

[/code]

**Comment by cconard96** [comment]
Fixed in #10867 for GLPI 10. Some other related issues were fixed in #11708 for GLPI 10.

**Comment by EmperiuM666** [comment]
I'm having this issue since last friday after updating from 9.5.8 to 9.5.9, but I cant find any solution to this versions.

**Comment by trasher** [comment]
New 9.5.x releases are for security fixes only. Consider upgrading to GLPI 10.

**Comment by C-Duv** [comment]
If someone could drop a patch for GLPI 9.5.x it would be greatly appreciated :)
