### ISSUE TITLE
Cartridge ERROR

### ISSUE THREAD

**Issue by Re1Ser** [glpi-project/glpi#12380]
### Version

10.0.2

### Bug description

HI !

I have configured my cartridges with different thresholds. I have also configured the automatic CARTRIDGE action.

However, when thresholds are reached, I get no notification or indication that the threshold has been reached.

thanks !

**Comment by cconard96** [comment]
Please write in English (automatic translations are OK).

Having issues reported all in English helps ensure that searching for existing/already reported issues is easier.
Also, the community and development team is international so having a common language helps us too.

Veuillez écrire en anglais (les traductions automatiques sont acceptables).

Le fait que les problèmes signalés soient tous en anglais permet de faciliter la recherche de problèmes existants ou déjà signalés.
De plus, la communauté et l'équipe de développement étant internationales, le fait d'avoir une langue commune nous aide également.

**Comment by cconard96** [comment]
Under Setup > Notifications > Notifications > Cartridge, are there recipients configured on the Recipients tab?
Are the alarm options for Cartridges set in the Notifications tab of the relevant Entity?

Please also include you GLPI setup information that was requested in the issue template. This can be found in Setup > General > System tab. There is a button there that will let you copy all of the information to paste it here.

**Comment by Re1Ser** [comment]
I have recipients configured and also the alarm options for the Cartridges are set.

What's more, I receive mail when a ticket is created.
