### ISSUE TITLE
GLPi 10.0.2: Superadmin with recursive permissions in all entities cannot mention user unless superadmin switches to entity of that user

### ISSUE THREAD

**Issue by qaOYR** [glpi-project/glpi#12381]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

From root entity, a superadmin who has been assigned recursive permissions to access all subentities cannot mention users who belong to a subentity of the root entity.  **He must switch to that specific subentity first.**

As you type "@", only users of the root entity are shown. My understanding is that this is a bug. 

If you have a lot of entities and need to mention a great deal of users, this mode of operation ends up being quite cumbersome and slow

Right now when you open a new ticket, you are able to select any user from any entity if you have the right permissions. User mentions should function in the same manner.

I look forward to your response.

### Steps To reproduce

Fully up-to-date 10.0.2, glpi mention users by typing "@", all users should be available, but in reality **only those that belong to the root entity are shown.**

**Comment by qaOYR** [comment]
I must update the ticket to clarify a few things.

Upon further testing, I have detected **that it is not a question of whether the user that you want to mention is in the root entity**, but rather you **must first switch to** in an entity that the user belongs to in order to mention him/her, even if  you are superadmin with recursive permissions on the root entity.

To put it more clearly, even if  you are superadmin with recursive permissions, you cannot currently mention a user in a ticket that is assigned to a specific entity and ticket, if you do not switch to that entity first.

I believe that you should be able to to so as superadmin with recursive permissions.

Thanks for looking into this.

**Comment by cconard96** [comment]
I confirm the behavior. It is currently restricted to the user's current entity, but I think that it should actually be restricted to the ticket's entity, unless it is a new ticket, in which case it could be restricted to any of the user's active entities. This would match the behavior of the requester/observer/assigned dropdowns.

**Comment by cedric-anne** [comment]
Hi,

Could you test #12409 ?

**Comment by qaOYR** [comment]
@cedric-anne 

**Thanks for your quick response to this issue.** I have tested the proposed fix and it resolves some of the previous issues, but I think it needs further work. Allow me to elaborate.

When I am opening a new ticket, I still cannot see users of a subentity **unless I select it first from the entities drop-down menu**.

If I understand the modus operandi of GLPi correctly, I believe superadmins with recurssive permissions on all subentities should be able to mention users from all entities below the root one. Is this correct?

Thanks again for all your hard work.

**Comment by qaOYR** [comment]
@cconard96 - You are completely right. This issue can be closed.

In fact, upon further testing, I came to the same conclusion.

**Comment by cedric-anne** [comment]
Will be closed when PR will be merged.
