### ISSUE TITLE
Ticket save button is missing in 10.0.X

### ISSUE THREAD

**Issue by TretornESP** [glpi-project/glpi#12391]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When i try to save a ticket through: Support -> Tickets. The entire right side panel containing the save button is missing. This bug was present in previous 10.0.X versions.

### Steps To reproduce

Navigate to support and tickets, try to create a new one. You won't be able to save it.
![screenshot](https://user-images.githubusercontent.com/13810073/183047654-60240813-6745-4fff-b5fa-b213fde03709.PNG)

### Your GLPI setup information

GLPI 10.0.2 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:es_ES

Operating system: Linux glpi 4.15.0-169-generic #177-Ubuntu SMP Thu Feb 3 10:50:38 UTC 2022 x86_64
PHP 7.4.28 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (Debian) (Apache/2.4.53 (Debian) Server at glpi.coren.com Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.3-MariaDB-1:10.7.3+maria~focal
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_user@mariadb/glpidb
	Host info: mariadb via TCP/IP
	
PHP version (7.4.28) is supported.PHP version (7.4.28) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.3) is supported.Database engine version (10.7.3) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cconard96** [comment]
Please check the GLPI log files (files/_log) for any relevant entries from around the time of the issue.

**Comment by TretornESP** [comment]
This is the only entry that might be related. Hope it helps.

`[2022-08-10 07:12:42] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to CommonTreeDropdown::sanitizeSeparatorInCompletename() must be of the type string, null given, called in /var/www/html/glpi/src/Dropdown.php on line 2955 in /var/www/html/glpi/src/CommonTreeDropdown.php at line 996
  Backtrace :
  src/Dropdown.php:2955                              CommonTreeDropdown::sanitizeSeparatorInCompletename()
  src/Dropdown.php:248                               Dropdown::getDropdownValue()
  src/CommonDBTM.php:4006                            Dropdown::show()
  ...ication/View/Extension/ItemtypeExtension.php:98 CommonDBTM::dropdown()
  ...59d3a252aa3dc7bec0135f86c7a075f966fa64.php:2198 Glpi\Application\View\Extension\ItemtypeExtension->getItemtypeDropdown()
  .../twig/twig/src/Extension/CoreExtension.php:1202 __TwigTemplate_c4196af2bd0cff6831335df0d5a1f2c7a51c0d2229eaf38bc9cd26913cfba7bf->macro_dropdownField()
  ...d54d4a02510a85ebf1b95d52dca8aa290bd4b83.php:333 twig_call_macro()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_6c470747856d93a62bdecc99eb9b570586026045a1c8a53098e676df4cd4130f->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1323 Twig\TemplateWrapper->render()
  ...3176d4f4a5c5d68f761da4c83b2a39ac619a423.php:149 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_e16cc0d180a6e8690c02d42d6e09dd222607f59b8508582007c04a8d557ae004->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:179      Twig\TemplateWrapper->display()
  src/Ticket.php:4385                                Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:657                             Ticket->showForm()
  ajax/common.tabs.php:111                           CommonGLPI::displayStandardTab()

`

**Comment by cedric-anne** [comment]
Hi,

#12391 should fix this issue.
