### ISSUE TITLE
Wrong uid returned in API response

### ISSUE THREAD

**Issue by chnateag** [glpi-project/glpi#12398]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5, 10.0.2

### Bug description

When you do a search request on computer with software name, API response contains the software you're looking for instead of computer name in the real uid "Computer.name" field.

### Relevant log output

```shell
API response GLPI v10.0.2 :


{
    "totalcount": 94,
    "count": 94,
    "sort": [
        "1"
    ],
    "order": [
        "ASC"
    ],
    "data": [
        {
            "Computer.name": "proxmox-ve",
            "Computer.Entity.completename": "Entité racine > FOO",
            "Computer.ComputerType.name": "Serveur",
            "Computer.contact": "",
            "Computer.Manufacturer.name": "HP",
            "Computer.ComputerModel.name": "HP EliteDesk",
            "Computer.id": 1949,
            "Computer.serial": "zzzzzzz",
            "Computer.comment": "",
            "Computer.Location.completename": "valence",
            "Computer.Contract_Item.Contract.name": "Hors Contrat",
            "Computer.IPAddress.name": [
                "127.0.0.1"
            ],
            "Computer.Notepad.content": [
                "ø"
            ],
            "Computer.Item_OperatingSystem.OperatingSystem.name": "Debian"
        },
    "content-range": "0-93/94"
```

### Page URL

http://glpi/apirest.php/search/computer

### Steps To reproduce

Just make a GET request on search/computer endpoint with this query :

`http://glpi_url/apirest.php/search/computer?is_deleted=0&as_map=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=45&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=Debian&criteria%5B1%5D%5Blink%5D=AND&criteria%5B1%5D%5Bitemtype%5D=Software&criteria%5B1%5D%5Bmeta%5D=1&criteria%5B1%5D%5Bfield%5D=1&criteria%5B1%5D%5Bsearchtype%5D=contains&criteria%5B1%5D%5Bvalue%5D=proxmox-ve&search=Rechercher&itemtype=Computer&start=0&uid_cols=true`

here is the json view

```
{
"criteria":
 [
    {
		"field" : 45,
		"searchtype" : "contains",
		"value" : "Debian"
	},{
		"link" : "AND",
		"itemtype" : "Software",
		"meta" : 1,
		"field" : 1,
		"searchtype" : "contains",
		"value" : "proxmox-ve"
	}
],
"uid_cols" : "true"
}
```

### Anything else?

If I don't specify "uid_cols" : "true" i can see that the field number of computer name and software name are the same which is 1

**Comment by chnateag** [comment]
Le bug est reproductible en 10.0.3.

**Comment by trasher** [comment]
I've removed comments that was not written in english.

**Comment by chnateag** [comment]
Issue is still present in the latest release.
