### ISSUE TITLE
Proxy settings ignored  - oauthimap not working

### ISSUE THREAD

**Issue by k0xak** [glpi-project/glpi#12392]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.2

### Bug description

Linux install - Rocky linux 8.6 or 9.0

GLPI 10.2 or 10.3 dev

Internet access is rectricted - you have to use proxy.
There is only one exception - IMAP TCP:993 is open to internet.

Proxy settings is correctly working in operating system:
/etc/profile
/etc/dnf/dnf.conf

In GLPI - we use proxy settings in /setup/General/System/Proxy configuration

We use Office365 email via oauthimap plugin - installed latest1.4.0 version

To get this plugin working you need to pass proxy settings manualy to php-fpm

nano /etc/php-fpm.d/www.conf

env[HTTP_PROXY] = x.x.x.x:3128
env[HTTPS_PROXY] = x.x.x.x:3128

GLPI Market working
GLPI version check working

oauthimap setup went flawlesly - you can manualy get emails, diag run work

Problem occures when you setup mailgate to periodicaly check for emails.
After an hour or so receiver will go into error - please see enclosed log

Token for oauth access is expired and mailgate is unableble to refresh is - curl cannot reach https://login.microsoftonline.com as shown in the log. When you open bash and try to curl this url than it works but when called  via guzzle - CurlFactory its not working. Somehow the system proxy is ommited for this action.

On firewall we see numerous direct https attemps to Microsoft infrastructure.

When you manualy run /Setup/Oauth IMAP applications/name of the app/Diagnose - then it will get new token correctly.
But this will last for next hour or so.

In another installation - different environment - where internet access is unrestricted = not using proxy - mailgate with oauth works without problem.

The question is - how to get oauth working when behind proxy.

### Relevant log output

```shell
[2022-08-05 02:15:31] glpiphplog.CRITICAL: *** Uncaught Exception GuzzleHttp\Exception\ConnectException: cURL error 28: Failed to connect to login.microsoftonline.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://login.microsoftonline.com/fd51798d-962f-4a26-aa45-66afc4240642/v2.0/.well-known/openid-configuration in /var/www/html/glpi/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php at line 210
```

**Comment by trasher** [comment]
Sounds related to a plugin, not GLPI itself, should be reported against faultly plugin
