### ISSUE TITLE
Group Issues

### ISSUE THREAD

**Issue by Re1Ser** [glpi-project/glpi#12394]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Hello!

When I create a certain type of ticket with a group attached to the problem the group appears well.

However, this does not trigger the sending of mail to notify the group. The only way I have found is to remove and reassign the group to this ticket for the mailing to be done.

Thanks in advance

### Your GLPI setup information

GLPI 10.0.2 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cconard96** [comment]
Please write in English (automatic translations are OK).

Having issues reported all in English helps ensure that searching for existing/already reported issues is easier.
Also, the community and development team is international so having a common language helps us too.

Veuillez écrire en anglais (les traductions automatiques sont acceptables).

Le fait que les problèmes signalés soient tous en anglais permet de faciliter la recherche de problèmes existants ou déjà signalés.
De plus, la communauté et l'équipe de développement étant internationales, le fait d'avoir une langue commune nous aide également.

**Comment by cconard96** [comment]
I attempted to translate the request.

I believe this issue may be fixed by #12388.
