### ISSUE TITLE
glpi_infocoms delivery_number not shown

### ISSUE THREAD

**Issue by YohanRodriguezMDM** [glpi-project/glpi#12395]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

delivery_number field shows empty but the value is in the database

### Page URL

front/computer.form.php

### Steps To reproduce

Go to any computer page, delivery_number field shows empty

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.1 ( => /var/www/vhosts/inventaire.montdemarsan.fr)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux xe-marsan-glpi-prod 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Server Software: (Ubuntu)
	Server Version: 8.0.29-0ubuntu0.20.04.3
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_prod_u@localhost/glpi_prod
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.29) is supported.
The log file has been created successfully.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_cache has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/config has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_cron has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_dumps has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_graphs has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_lock has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_pictures has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_plugins has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_rss has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_sessions has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_tmp has been validated.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/vhosts/inventaire.montdemarsan.fr/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/vhosts/inventaire.montdemarsan.fr
GLPI_CONFIG_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/config
GLPI_VAR_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files
GLPI_MARKETPLACE_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files
GLPI_CACHE_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_cache
GLPI_CRON_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_cron
GLPI_DUMP_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_dumps
GLPI_GRAPH_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_locales
GLPI_LOCK_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_lock
GLPI_LOG_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_log
GLPI_PICTURE_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_plugins
GLPI_RSS_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_rss
GLPI_SESSION_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_sessions
GLPI_TMP_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_tmp
GLPI_UPLOAD_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_uploads
GLPI_INVENTORY_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/vhosts/inventaire.montdemarsan.fr/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/sabre/http/lib)
sabre/uri in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/symfony/console)
scssphp/scssphp in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/ramsey/uuid/src)
psr/log in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/psr/simple-cache/src)
psr/cache in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/psr/cache/src)
league/csv in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/symfony/cache)
html2text/html2text in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/symfony/dom-crawler)
twig/twig in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/twig/twig/src)
twig/string-extra in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/vhosts/inventaire.montdemarsan.fr/vendor/symfony/polyfill-php81)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'directory.montdemarsan-agglo.fr', Port: '389', BaseDN: 'dc=agglo,dc=mdm', Connection filter: none, RootDN:
		'cn=viewer,ou=system,dc=agglo,dc=mdm', Use TLS: '1'

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (service.info@montdemarsan-agglo.fr@webmail.montdemarsan.fr)

</details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.0      State: Enabled
	datainjection        Name: Data Injection                 Version: 2.11.2     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 10.0.0+1.0 State: Enabled
	reservation          Name: Reservation                    Version: 2.3.8      State: Enabled

</pre></details>

**Comment by cconard96** [comment]
Should be fixed by #12396

**Comment by YohanRodriguezMDM** [comment]
Perfect, thanks.
