### ISSUE TITLE
"permission denied" message should explain an other profile might allow access

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#1240]
When trying to access a resource my active profile does not allow I get the following message:

> You don't have permission to perform this action.

I think this message should advice use to try an other profile (if any).

Steps to reproduce:

1. Login using an account that has not access to user administration ("post-only" will do).
2. Access to https://glpi.example.com/front/helpdesk.public.php.
3. Set active profile to "post-only".
4. Access to https://glpi.example.com/front/user.php.

Actual result:

> You don't have permission to perform this action.

Expected result:

A message stating access to the request resource is denied but emphasizing on the fact the access is not denied to the user, but is denied to _<active_profile>_ profile. And have advice to try another profile.

Optimal result:

Code could loop over each profile the user and try if any allows access to the requested resource. If one has: switch user to this profile and access the resource. If none has: display the "You don't have permission to perform this action." message.

GLPI version: 0.90.5

**Comment by trasher** [comment]
Hello,

If it should be a little more precise, and tell user another profile he belongs to would solve the problem, I would be ok with that.

But I'm not OK at all with automatic switching.

**Comment by C-Duv** [comment]
Automatic switching hides stuff to the user and provides him with magic (too much, maybe), another idea is not to automatically switch but list the user which of his profiles will give him access: a "compute and suggest but don't act" approach.

That being said, I'm sure adding suggestion to try with other profile to the error message would resolve some user misunderstandings.

**Comment by C-Duv** [comment]
Please 🤖 remove the Stale label .
