### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by NoahMautain** [glpi-project/glpi#12402]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

When you create a dashboard and take the link to share it, the page you access offline via this link appears in white.

### Page URL

/front/central.php?embed&dashboard=xxxxxxx&entities_id=0&is_recursive=1&token=xxxxxxxxx

### Steps To reproduce

Share on dashboard page

### Your GLPI setup information

GLPI on apache server on debian server

**Comment by cedric-anne** [comment]
Hi,

Please test on GLPI 10.0.2.

Also, please provide requested information. With so little information, noone will ever try to investigate on your issue.

**Comment by NoahMautain** [comment]
Same error after update.

/front/central.php?embed&dashboard=xxxxxxx&entities_id=0&is_recursive=1&token=xxxxxxxxx

**Comment by cedric-anne** [comment]
A blank page usually means that a fatal error has been thrown. Is there anything in GLPI logs (`glpi/files/_logs`) when this query is executed ?

**Comment by cedric-anne** [comment]
#12399 may fix this issue.

**Comment by NoahMautain** [comment]
I don't have this files: tests/functionnal/Glpi/Dashboard/Dashboard.php

**Comment by trasher** [comment]
Just ignore it then.
