### ISSUE TITLE
Issue when attributing a group in a ticket

### ISSUE THREAD

**Issue by Re1Ser** [glpi-project/glpi#12404]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.1

### Bug description

Hi, 

when I want to associate a group to a ticket (Observer or attributed to) and i click on the save button.

I have a white web page and the group didn't associate to the ticket

Thanks !

### Your GLPI setup information

GLPI 10.0.1 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

**Comment by cconard96** [comment]
Please try the latest bug fix version of GLPI 10 (10.0.2) as the issue may have already been fixed.
Also, a blank page usually indicates a PHP error, so we would need any information from the GLPI error logs from around that time (files/_log/ directory).

**Comment by Re1Ser** [comment]
I would like to use the GLPI 10.0.2; but I have to put it in production and without the fusionInventory I can't.

So i have to stay on the GLPI 10.0.1.

My issue is : glpiphplog.CRITICAL: *** Uncaught Exception TypeError: Glpi\Toolbox\Sanitizer::isNsClassOrCallableIdentifier(): Argument #1 ($value) must be of type string, array given, called in /var/www/glpi/src/DBmysql.php on line 1257 in /var/www/glpi/src/Toolbox/Sanitizer.php at line 228

**Comment by cedric-anne** [comment]
Duplicates #11796 and fixed by #11957.
