### ISSUE TITLE
Virtualization memory get inventoried correctly only the first time

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi#12416]
In the continuity of glpi-project/glpi-agent#132,

I'm now running glpi-agent 1.4 and it seems LXC containers memory limit get inventoried correctly the first time, but if I change the memory limit in an lxc container's config and then run glpi-agent again, the memory limit in GLPI doesn't get updated. I must delete the container in GLPI and then re-inventory again to get the memory limit update.

_Originally posted by @mightyspiky in https://github.com/glpi-project/glpi-agent/issues/132#issuecomment-1191883824_

**Comment by g-bougard** [comment]
Tested with GLPI 10.0.2.

**Comment by mightyspiky** [comment]
I also don't see anything in php-errors.log and the errors I see in sql-errors.log don't seem related to this issue.
