### ISSUE TITLE
[FIX] Problem in Search filter in tickets for Technicians

### ISSUE THREAD

**Issue by fgendorf** [glpi-project/glpi#1242]
Hi, I recently upgraded to GLPI 9.1 and realize that filters for technicians is not working,  
I saw that have a fix related, but it is not working too, I did the checkout from the last branch.

When I select "Assigned To - Technician" appear users from entities -1 (Root) and the Technician from current Entity don't.

Sometimes navigating on GLPI and returning to Tickets All users from Entity are displayed on Technician combobox, and not just technician...

The combobox inside the Ticket, related to Assigned To, is working well.

I think Search Tickets filters must be reviewed.

Thanks for advance

**Comment by fgendorf** [comment]
I did some changes in file ajax/getDropdownUsers.php

```php
if (isset($_POST['entity_restrict'])) {
   $entity_restrict = json_decode($_POST['entity_restrict']);
   if (json_last_error() != JSON_ERROR_NONE) {
      $entity_restrict = stripslashes($_POST["entity_restrict"]);
   }
}

if ($one_item < 0) {
   $start  = intval(($_POST['page']-1)*$_POST['page_limit']);
   $result = User::getSqlSearchResult(false, $_POST['right'], json_decode($entity_restrict)[0],
                                      $_POST['value'], $used, $_POST['searchText'], $start,
                                      intval($_POST['page_limit']));
```
that way all users from Entity are returned, but not just technicians on filter Assigned To

**Comment by fgendorf** [comment]
OK, I found the bug and fixed by my self...
at the file ./ajax/searchoptionvalue.php change 
```php
case "glpi_users.name" :
                  $options2['right'] = "all";
                  break;
```
TO

```php
case "glpi_users.name" :
                  $options2['right'] = $searchopt["right"];
                  break;
```

**Comment by hartois** [comment]
Oh, thank you!
It has kept me a lot of time!
Maybe you can make PR?

**Comment by orthagh** [comment]
see #1086 for reference (json_decode added)
i found the last problem i think, some slashes added by the includes.php file and need to be removed before json_decode.

I'll push a pr quickly
