### ISSUE TITLE
Error 500 when use the api for add rule cirteria or add rule action

### ISSUE THREAD

**Issue by emerauldwolf** [glpi-project/glpi#12425]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

I use insomnia tool for try the request 

- version insomnia: 2022.5.0
- version httpd: apache 2.4.51 (Rocky Linux 8)
- version php:  php 8.1.9
- vesion zend Engine: v8.1.9

API gen a 500 error code when i use post request for add a rule criteria or a rule action. 
But in glpi web GUI the rules appear and works

### Page URL

https://x/glpi/apirest.php/RuleCriteria/ or https://x/glpi/apirest.php/RuleAction/

### Steps To reproduce

1. Active api with the GUI
2. Allow connexion with id
3. Change the url api to https://x/glpi/apirest.php
4. Add a API client
5.  Use insominia for init connexion and get the token
8. Add rule import entity with the api
  - method: POST
  - link: https://x/glpi/apirest.php/RuleImportEntity
  - json param:  {"input": {"name":"DATA","description":"Ajoute automatiquement les éléments remonté par l'agent glpi dans l'entité DATA","ranking":1,"comment":""}}
  - header: Session-Token , Content-Type: application/json
  - status: 201 Created
10. Add rule Criteria
  - method: POST
  - link: https://x/glpi/apirest.php/RuleCriteria/
  - json param: {"input": { "rules_id": 137, "criteria": "tag", "condition": 0, "pattern": "DATA"}}
  - status: 500 internal server error
11. Add rule RuleAction
  - method: POST
  - link: https://x/glpi/apirest.php/RuleAction/
  - json param: {"input": {"rules_id":137,"action_type": "assign","field": "entities_id","value":0}}
  - status: 500 internal server error

### Your GLPI setup information

# Informations sur le système, l'installation et la configuration

GLPI 10.0.2 (/glpi => /opt/glpi)
Installation mode: TARBALL
Current language:fr_FR

# Server

Operating system: Linux vm-data-glpi-v10.exemple.com 5.14.0-70.17.1.el9_0.x86_64 #1 SMP PREEMPT Wed Jul 13 18:23:04 UTC 2022
	x86_64
PHP 8.1.9 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.51 (Rocky Linux) OpenSSL/3.0.1 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.7.3-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@mysqlpx.exemple.com/glpi_v10
	Host info: mysqlpx.exemple.com via TCP/IP
	
PHP version (8.1.9) is supported.PHP version (8.1.9) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.3) is supported.Database engine version (10.7.3) is supported.
The log file could not be created in /opt/glpi/files/_log.The log file could not be created in /opt/glpi/files/_log.
Write access to /opt/glpi/files/_cache has been validated. Write access to /opt/glpi/config has been validated. Write access to /opt/glpi/files/_cron has been validated. Write access to /opt/glpi/files has been validated. Write access to /opt/glpi/files/_dumps has been validated. Write access to /opt/glpi/files/_graphs has been validated. Write access to /opt/glpi/files/_lock has been validated. Write access to /opt/glpi/files/_pictures has been validated. Write access to /opt/glpi/files/_plugins has been validated. Write access to /opt/glpi/files/_rss has been validated. Write access to /opt/glpi/files/_sessions has been validated. Write access to /opt/glpi/files/_tmp has been validated. Write access to /opt/glpi/files/_uploads has been validated.Write access to /opt/glpi/files/_cache has been validated.
Write access to /opt/glpi/config has been validated.
Write access to /opt/glpi/files/_cron has been validated.
Write access to /opt/glpi/files has been validated.
Write access to /opt/glpi/files/_dumps has been validated.
Write access to /opt/glpi/files/_graphs has been validated.
Write access to /opt/glpi/files/_lock has been validated.
Write access to /opt/glpi/files/_pictures has been validated.
Write access to /opt/glpi/files/_plugins has been validated.
Write access to /opt/glpi/files/_rss has been validated.
Write access to /opt/glpi/files/_sessions has been validated.
Write access to /opt/glpi/files/_tmp has been validated.
Write access to /opt/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /opt/glpi/marketplace has been validated.Write access to /opt/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

# GLPI constants

GLPI_ROOT: /opt/glpi
GLPI_CONFIG_DIR: /opt/glpi/config
GLPI_VAR_DIR: /opt/glpi/files
GLPI_MARKETPLACE_DIR: /opt/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /opt/glpi/files
GLPI_CACHE_DIR: /opt/glpi/files/_cache
GLPI_CRON_DIR: /opt/glpi/files/_cron
GLPI_DUMP_DIR: /opt/glpi/files/_dumps
GLPI_GRAPH_DIR: /opt/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /opt/glpi/files/_locales
GLPI_LOCK_DIR: /opt/glpi/files/_lock
GLPI_LOG_DIR: /opt/glpi/files/_log
GLPI_PICTURE_DIR: /opt/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /opt/glpi/files/_plugins
GLPI_RSS_DIR: /opt/glpi/files/_rss
GLPI_SESSION_DIR: /opt/glpi/files/_sessions
GLPI_TMP_DIR: /opt/glpi/files/_tmp
GLPI_UPLOAD_DIR: /opt/glpi/files/_uploads
GLPI_INVENTORY_DIR: /opt/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /opt/glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

# Libraries

htmlawed/htmlawed version 1.2.6 in (/opt/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/opt/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/opt/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/opt/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/opt/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/opt/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/opt/glpi/vendor/sabre/http/lib)
sabre/uri in (/opt/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/opt/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/opt/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/opt/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/opt/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/opt/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/opt/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/opt/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/opt/glpi/vendor/symfony/console)
scssphp/scssphp in (/opt/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/opt/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/opt/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/opt/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/opt/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/opt/glpi/vendor/ramsey/uuid/src)
psr/log in (/opt/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/opt/glpi/vendor/psr/simple-cache/src)
psr/cache in (/opt/glpi/vendor/psr/cache/src)
league/csv in (/opt/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/opt/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/opt/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/opt/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/opt/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/opt/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/opt/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/opt/glpi/vendor/symfony/cache)
html2text/html2text in (/opt/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/opt/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/opt/glpi/vendor/symfony/dom-crawler)
twig/twig in (/opt/glpi/vendor/twig/twig/src)
twig/string-extra in (/opt/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
phpCas version 1.5.0 in (/usr/share/pear)

# SQL replicas

Not active

# Notifications

Way of sending emails: PHP

# Mails receivers

Empty

# Plugins list

Empty

**Comment by cconard96** [comment]
Please check the GLPI logs (files/_log) to see if anything is logged at the time of the 500 response.

**Comment by emerauldwolf** [comment]
-rw-r--r-- 1 apache apache  336 Aug  9 15:25 access-errors.log
-rw-r--r-- 1 apache apache  102 Aug 10 10:55 api.log
-rw-r--r-- 1 apache apache 3139 Aug 10 11:40 bench_inventory.log
-rw-r--r-- 1 apache apache 4193 Aug 10 17:04 cron.log
-rw-r--r-- 1 apache apache 1742 Aug 10 15:17 event.log
-rw-r--r-- 1 root   root    112 Aug  9 15:20 php-errors.log
-rwxrw-r-- 1 apache apache   80 Jun 28 14:03 remove.txt
-rw-r--r-- 1 root   root   5771 Aug  9 15:20 sql-errors.log


cat acces_errors.log
2022-08-09 13:25:19 [2@vm-data-glpi-v10.exemple.com]
CSRF check failed for User ID: 2 at /front/massiveaction.php2022-08-09 13:25:29 [2@vm-data-glpi-v10.exemple.com]
CSRF check failed for User ID: 2 at /front/massiveaction.php2022-08-09 13:25:47 [2@vm-data-glpi-v10.exemple.com]
CSRF check failed for User ID: 2 at /front/massiveaction.php

cat api.log
2022-08-10 08:55:36 [2@vm-data-glpi-v10.exemple.com]
Enpoint 'RuleCriteria' called by x.x.x.x (glpi)

 cat php-errors.log
[2022-08-09 13:20:37] glpiphplog.WARNING: Test logger
[2022-08-09 13:20:37] glpiphplog.WARNING: Test logger

[sql-errors.log](https://github.com/glpi-project/glpi/files/9301391/sql-errors.log)

**Comment by emerauldwolf** [comment]
I found the solution

It is just a rigth problem on php_errors.log 

Thanks for your help
