### ISSUE TITLE
GLPI doesn't show who made the reservation in profile with simplified interface

### ISSUE THREAD

**Issue by phbotacin** [glpi-project/glpi#12424]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When the GLPI is accessed by a user with a simplified interface (Self-Service), he cannot see who made the reservations, he only displays the message "reserved by "

Follow screenshot attached.

![image](https://user-images.githubusercontent.com/83027238/183911260-8a7290ce-93ac-490a-8ba5-c2acd5b5aa0c.png)

### Anything else?

Would it be possible to make it easier for interface profiles to see who made the reservation?

This function existed in GLPI version < 10

**Comment by cconard96** [comment]
The current logic only shows the user name if you have the standard interface and can read Reservations, or if it is your own reservation. There is no way for other simplified interface users to see who has the other reservations at this time.

The one thing that could be improved is the wording of the tooltip when the user's name is not visible/

**Comment by phbotacin** [comment]
Hello, is there no possibility then to make visible reservations for simplified interface profiles?

This is a pain we are facing with the new GLPI update. Is there a possibility this could be developed or is it out of scope?

**Comment by lbonetti** [comment]
Hi,

Same problem here.
Indeed, in versions < 10, the tooltip message displayed "Reserved by (user name)".

**Comment by cconard96** [comment]
If it showed the information before GLPI 10, it may be a regression (and a bug) from when the reservations were reworked but I am not sure if it was intentional or not.

**Comment by lbonetti** [comment]
I believe it's a bug. Another problem we've noticed is that after a self-service user makes a reservation, the tooltip message of other people's reservations appears as if he made it itself (but cannot click and edit).

**Comment by phbotacin** [comment]
GLPI versions < 10 , all had the tooltip message displayed "Reserved by (username)", even in the simplified interface. Is there a possibility this could be developed or is it out of scope?

**Comment by Kalyeloficial** [comment]
I was able to fix it by following these steps.
https://github.com/glpi-project/glpi/issues/12009

**Comment by phbotacin** [comment]
> I was able to fix it by following these steps. #12009

Hello,

I made the change suggested in the point above. With this change it was possible to view the reservations of the day, those of the previous day or the following days it is not possible to view, but it is already an advance, thanks for the collaboration.

**Comment by Alwaysin** [comment]
We are also affected by this regression. Could we get back the behaviour of < 10 versions ?

**Comment by lbonetti** [comment]
> I was able to fix it by following these steps. #12009

Thank you, but this procedure did not solve the problem completely. The message now shows the name of the user who made the reservation, but it still doesn't show their comments, as it was in versions < 10.

![reserva](https://user-images.githubusercontent.com/8398908/187769426-fe7efc44-5687-42a6-967a-0073408c509f.png)

In the example above, inside the reservation, there is a comment written by the user "teste", but it is not displayed.

**Comment by ogd0ug** [comment]
> > > I was able to fix it by following these steps. #12009
> > 
> > 
> > Thank you, but this procedure did not solve the problem completely. The message now shows the name of the user who made the reservation, but it still doesn't show their comments, as it was in versions < 10.
> > ![reserva](https://user-images.githubusercontent.com/8398908/187769426-fe7efc44-5687-42a6-967a-0073408c509f.png)
> > In the example above, inside the reservation, there is a comment written by the user "teste", but it is not displayed.
> 
> I found a way to display the comments too, like in versions < 10. In the Reservations.php file, on line 559, I changed the original code:
> 
> `? "\n" . sprintf(__("Reserved by %s"), $username)`
> 
> To:
> 
> `? "\n" . sprintf(__("Reserved by %s: %s"), $username, $data['comment'])`
> 
> It worked for me, at least until we have an official solution: ![comments](https://user-images.githubusercontent.com/8398908/187797319-e25b942f-a724-44ae-bb85-4292ad781452.png)


Cara, tentei seguindo esse procedimento e mesmo assim não mostra os nomes, mas mostra os comentários. Queria que só mostrasse os nomes, mesmo fazendo o outro procedimento descrito acima não apareceu

**Comment by trasher** [comment]
@ogd0ug use english only.

**Comment by lbonetti** [comment]
This bug persists in version 10.0.3. I updated the version and it was necessary to do the above mentioned procedures again.

**Comment by Kalyeloficial** [comment]
Yes, for me it was the same, I updated to version 10.0.3 on a test server, the problem still continues, and it is necessary to carry out all the steps described above.

**Comment by lbonetti** [comment]
This bug persists in version 10.0.5.

**Comment by flonou** [comment]
I found a solution for this (and fixed a bug), that can also display comment and reserving user in the calendar. I will try to submit a PR for it but I'm not familiar with these programation languages.
In Reservation.php replace 557-560 with : 
```
                'comment'     => $data['comment'],
                'user'        => ($canedit_admin || $my_item
                              ? "$username"
                              : ""),
```
In reservation.js line 174 add :`
 element.find(".fc-content, .fc-list-item-title").append("&nbsp;"+(extProps.user? extProps.user + " - ":"") + extProps.comment);
`
in reservation.js line replace 191 with : 
`                    content: extProps.comment + (extProps.user?  " - " +extProps.user : ""),`

**Comment by cedric-anne** [comment]
Self-service users are only supposed to be able to read details of a reservation made by someone else, this is not a bug.

**Comment by lbonetti** [comment]
> Self-service users are only supposed to be able to read details of a reservation made by someone else, this is not a bug.

Hi, cedric
In my tests, the self-service users are not able to read reservations made by any other user, not even through the popup.
Will it stay this way? If so, it's a drastic change compared to versions 9. At least if users can know who made the reservations through the popup, it makes internal communication a lot easier.
Thanks.

**Comment by flonou** [comment]
Does the self-service profile has read access on reservations ? I think it's required

**Comment by WgkLink** [comment]
I also believe that it is necessary for the self-service profile to have access to read the reservations. Sometimes users can negotiate reservations with each other.

**Comment by lbonetti** [comment]
> Does the self-service profile has read access on reservations ? I think it's required

In the simplified interface, the "read" permission is omitted. Only the "make a reservation" permission can be enabled and, even with it, users can only see reservations made by themselves.

**Comment by cedric-anne** [comment]
We will try to add the `READ` permission on the self-service profile soon.

**Comment by HectorZanardo** [comment]
The problem still occurs in version 10.9 
Has anyone managed to do anything to really fix this?
All the above solutions did not work for me.

**Comment by Alwaysin** [comment]
@HectorZanardo Indeed. They've added the "read" permission for reservations in Administration -> Profiles -> Self-service -> Tools

![image](https://github.com/glpi-project/glpi/assets/7189936/5756f76a-cb29-450e-a7e2-80c6587822c3)

But even after checking it, it does not seem to work.

**Comment by abreuti** [comment]
I tried using GLPI 10.0.10, and the problem was resolved by adding the "read" permission for reservations.

![image](https://github.com/glpi-project/glpi/assets/104652684/0c308fda-9b0e-4c1b-9df3-b0f5a279ecac)
