### ISSUE TITLE
Reservation start date

### ISSUE THREAD

**Issue by lbonetti** [glpi-project/glpi#12432]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When clicking on a day on the calendar to make a reservation, the "start date" field appears with the previous day.

In the image below, for example, i clicked to make a reservation on the 18th of August. However, the suggested starting date was the day before, August 17th.

![image](https://user-images.githubusercontent.com/8398908/184167429-adbc5ad6-c2f9-40d4-9f42-3ed23b09badc.png)

The bug only happens in the "Month" layout. Does not happen in "Week" or "Day" layouts. The bug happens in any user profile.

**Comment by guieloi** [comment]
I have the same issue. The day when clicked is the previous day.

**Comment by lbonetti** [comment]
This bug persists in version 10.0.3.

**Comment by trasher** [comment]
I've removed non english comment.

**Comment by Rafaeldgs** [comment]
I was able to solve it by adding in the code + HOUR_TIMESTAMP * 3

C:\wamp64\www\glpi\src\Reservation.php Linha 677

} else {
            $resa->getEmpty();
            $resa->fields["begin"] = date("Y-m-d H:i:s", strtotime($options['begin'])+ HOUR_TIMESTAMP * 3); // Adicionado + HOUR_TIMESTAMP * 3

**Comment by waltherhuggo** [comment]
This bug solved in version 10.0.4.
