### ISSUE TITLE
Can't update technician group

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1243]
Hello 

I have a bug on a ticket, impossible to add a group, no error on glpi but php error log i have the message below.

I have tried to change directly in db but I am able to change the technician not the group

2016-11-03 14:36:22 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc\item_ticket.class.php:589                      
  inc\commonglpi.class.php:203                       Item_Ticket->getTabNameForItem()
  inc\ticket.class.php:704                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:158                       Ticket->defineTabs()
  ajax\updatecurrenttab.php:51                       CommonGLPI->defineAllTabs()

**Comment by tomolimo** [comment]
which version?

**Comment by satyan01** [comment]
9.1

**Comment by AnaelMobilia** [comment]
Hello @satyan01 
Could you please, give a little more details on the actions you made ?

I tried to assign a ticket to a groupe, save.
Then I delete the groupe, add another, save.
The change where successfull.

Please provide me the differences on the way to do.

Regards,
Anael

**Comment by satyan01** [comment]
Hello

I was a bug so I don't have more details, it was 2 months ago
