### ISSUE TITLE
Received email shown as html code in ticket

### ISSUE THREAD

**Issue by mskews** [glpi-project/glpi#12443]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

I am still getting HTML code at the top of email alerts and running version 10.0.2

Checked the code in src/MailCollector.php and this is correct.

### Steps To reproduce

Receiving email
Ticket creation
Some tickets are shown as html code

### Your GLPI setup information

AWS Aurora Database
AWS Linux Instance (web server)
Have a DEV environment to test things.

### Anything else?

Issue isn't affecting Ticket emails.

**Comment by mskews** [comment]
From: xxxxxxxx
Sent: 15 August 2022 09:25
To: xxxxxxxx
Subject: [GLPI #0000091] xxxxxxxx

<p></div> <div> URL : <a href="https://zxxxxxxxxxxxxxxxxx/15uBhgQCTKYxCbnBT4SJc?h=bexkTcTaakZpxnIxtLOZpJPvqpa8RicGVzdxo-_3Et0=&u=https://sd.dxctucson.com/index.php?redirect%3Dchange_91">https://xxxxxxxxxxxxxxx/15uBnWbUuwEYcYc6zcqTE?h=B9ImBzwmivBXRZALV8tegprwB6LX6Wd0mAv5xV8WYuc=&u=https://xxxxxxxxxxxx/index.php?redirect%3Dchange_91%3C/a%26gt; </div> <p class="description b"><strong>Change: Description</strong></p> <p><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Title</span> :CM - VMware Cluster HA election setting change <br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Requesters</span> : Johnson Richard <br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Opening date</span> :2022-08-12 11:09 <br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Assigned to technicians</span> : Johnson Richard <br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">Status </span> : New<br /> <br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Urgency</span> : Very low<br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Impact</span> : Very low<br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Priority</span> : Very low <br /><span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;">Category </span> :Change > Normal <br /> <span style="color: #8b8c8f; font-weight: bold; text-decoration: underline;"> Description</span> : 
Increasing the failover/election timer on the Hyperflex cluster (tcprovmwclus01) to 30 seconds
This will resolve an issue highlighted by VMWare Skyline
See GLPI incident 21
[https://xxxxxxxxxxxx/front/ticket.form.php?id=21](https://xxxxxxxxxxxxxxxx/15uBcrCuzhsMnexFuW39z?h=6NBt_axo6x9rgqC_HWOQvWVSkwRwMWDxmdaU3Mt6BWA=&u=https://xxxxxxxxxxxxxx/front/ticket.form.php?id%3D21)
“Performing a Reconfigure for vSphere HA operation on a primary node may cause an unexpected virtual machine failover”
 

 
</p> <p></p> 
Number of followups : 0
<div class="description b">Number of problems : 0</div> <p></p> <div class="description b">Number of tasks : 0</div> <p></p> </div>

-- 

Automatically generated by GLPI

**Comment by cedric-anne** [comment]
Hi,

Is the issue located in notifications received from GLPI, or in tickets created from an email ?

**Comment by cedric-anne** [comment]
By the way, could you complete all sections of the issue form ?

**Comment by mskews** [comment]
It is notifications received from GLPI for Changes and Problems.

**Comment by mskews** [comment]
Any thoughts what might be causing it? It was fine on 9.5.7, but started showing code in emails when I upgraded to 10.0.2.
Oddly its fine when we get emails from Tickets, only Changes and Problem emails.

**Comment by cedric-anne** [comment]
Hi,

Can you test #12622 ?
