### ISSUE TITLE
IMAP -Kerberos authentication

### ISSUE THREAD

**Issue by udi8** [glpi-project/glpi#12442]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.1

### Bug description

option in Mail Receivers - IMAP - **Use Kerberos authentication** was disappeared from this version.
it is exist in GLPI 9.5. 
but in 10 - it dose not.
how can we fix that?

### Your GLPI setup information

<html>
<body>

nformation about system installation & configuration
--
 
GLPI 10.0.1 (/gilboa => D:\Glpi Gilboa) Installation mode: TARBALL Current language:en_US

Operating system: Windows NT PWNWP3306V01 10.0 build 17763 (Windows Server 2016) AMD64 PHP 8.0.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, snmp, soap, sodium, standard, tidy, tokenizer, xml, xmlreader, xmlrpc, 	xmlwriter, zend-test, zip, zlib) Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Microsoft-IIS/10.0 	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36 Server Software: MySQL Community Server - GPL 	Server Version: 8.0.29 	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION 	Parameters: root@localhost/GLPI_Gilboa 	Host info: localhost via TCP/IP 	 PHP version (8.0.0) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (8.0.29) is supported. The log file has been created successfully. Write access to D:\Glpi Gilboa/files/_cache has been validated. Write access to D:\Glpi Gilboa/config has been validated. Write access to D:\Glpi Gilboa/files/_cron has been validated. Write access to D:\Glpi Gilboa/files has been validated. Write access to D:\Glpi Gilboa/files/_dumps has been validated. Write access to D:\Glpi Gilboa/files/_graphs has been validated. Write access to D:\Glpi Gilboa/files/_lock has been validated. Write access to D:\Glpi Gilboa/files/_pictures has been validated. Write access to D:\Glpi Gilboa/files/_plugins has been validated. Write access to D:\Glpi Gilboa/files/_rss has been validated. Write access to D:\Glpi Gilboa/files/_sessions has been validated. Write access to D:\Glpi Gilboa/files/_tmp has been validated. Write access to D:\Glpi Gilboa/files/_uploads has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/gilboa/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to D:\Glpi Gilboa/marketplace has been validated. Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

GLPI_ROOT: D:\Glpi Gilboa GLPI_CONFIG_DIR: D:\Glpi Gilboa/config GLPI_VAR_DIR: D:\Glpi Gilboa/files GLPI_MARKETPLACE_DIR: D:\Glpi Gilboa/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: D:\Glpi Gilboa/files GLPI_CACHE_DIR: D:\Glpi Gilboa/files/_cache GLPI_CRON_DIR: D:\Glpi Gilboa/files/_cron GLPI_DUMP_DIR: D:\Glpi Gilboa/files/_dumps GLPI_GRAPH_DIR: D:\Glpi Gilboa/files/_graphs GLPI_LOCAL_I18N_DIR: D:\Glpi Gilboa/files/_locales GLPI_LOCK_DIR: D:\Glpi Gilboa/files/_lock GLPI_LOG_DIR: D:\Glpi Gilboa/files/_log GLPI_PICTURE_DIR: D:\Glpi Gilboa/files/_pictures GLPI_PLUGIN_DOC_DIR: D:\Glpi Gilboa/files/_plugins GLPI_RSS_DIR: D:\Glpi Gilboa/files/_rss GLPI_SESSION_DIR: D:\Glpi Gilboa/files/_sessions GLPI_TMP_DIR: D:\Glpi Gilboa/files/_tmp GLPI_UPLOAD_DIR: D:\Glpi Gilboa/files/_uploads GLPI_INVENTORY_DIR: D:\Glpi Gilboa/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: D:\Glpi Gilboa/locales GLPI_VERSION: 10.0.1 GLPI_SCHEMA_VERSION: 10.0.1@a130db99c7d9b131c2e2ea59fe0d6260fe93d831 GLPI_MARKETPLACE_PRERELEASES:  GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.6 in (D:\Glpi Gilboa\vendor\htmlawed\htmlawed) phpmailer/phpmailer version 6.6.0 in (D:\Glpi Gilboa\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.8 in (D:\Glpi Gilboa\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.4.4 in (D:\Glpi Gilboa\vendor\tecnickcom\tcpdf) michelf/php-markdown in (D:\Glpi Gilboa\vendor\michelf\php-markdown\Michelf) true/punycode in (D:\Glpi Gilboa\vendor\true\punycode\src) iamcal/lib_autolink in (D:\Glpi Gilboa\vendor\iamcal\lib_autolink) sabre/dav in (D:\Glpi Gilboa\vendor\sabre\dav\lib\DAV) sabre/http in (D:\Glpi Gilboa\vendor\sabre\http\lib) sabre/uri in (D:\Glpi Gilboa\vendor\sabre\uri\lib) sabre/vobject in (D:\Glpi Gilboa\vendor\sabre\vobject\lib) laminas/laminas-i18n in (D:\Glpi Gilboa\vendor\laminas\laminas-i18n\src) laminas/laminas-servicemanager in (D:\Glpi Gilboa\vendor\laminas\laminas-servicemanager\src) monolog/monolog in (D:\Glpi Gilboa\vendor\monolog\monolog\src\Monolog) sebastian/diff in (D:\Glpi Gilboa\vendor\sebastian\diff\src) donatj/phpuseragentparser in (D:\Glpi Gilboa\vendor\donatj\phpuseragentparser\src\UserAgent) elvanto/litemoji in (D:\Glpi Gilboa\vendor\elvanto\litemoji\src) symfony/console in (D:\Glpi Gilboa\vendor\symfony\console) scssphp/scssphp in (D:\Glpi Gilboa\vendor\scssphp\scssphp\src) laminas/laminas-mail in (D:\Glpi Gilboa\vendor\laminas\laminas-mail\src\Protocol) laminas/laminas-mime in (D:\Glpi Gilboa\vendor\laminas\laminas-mime\src) rlanvin/php-rrule in (D:\Glpi Gilboa\vendor\rlanvin\php-rrule\src) blueimp/jquery-file-upload in (D:\Glpi Gilboa\vendor\blueimp\jquery-file-upload\server\php) ramsey/uuid in (D:\Glpi Gilboa\vendor\ramsey\uuid\src) psr/log in (D:\Glpi Gilboa\vendor\psr\log\Psr\Log) psr/simple-cache in (D:\Glpi Gilboa\vendor\psr\simple-cache\src) psr/cache in (D:\Glpi Gilboa\vendor\psr\cache\src) league/csv in (D:\Glpi Gilboa\vendor\league\csv\src) mexitek/phpcolors in (D:\Glpi Gilboa\vendor\mexitek\phpcolors\src\Mexitek\PHPColors) guzzlehttp/guzzle in (D:\Glpi Gilboa\vendor\guzzlehttp\guzzle\src) guzzlehttp/psr7 in (D:\Glpi Gilboa\vendor\guzzlehttp\psr7\src) glpi-project/inventory_format in (D:\Glpi Gilboa\vendor\glpi-project\inventory_format\lib\php) wapmorgan/unified-archive in (D:\Glpi Gilboa\vendor\wapmorgan\unified-archive\src) paragonie/sodium_compat in (D:\Glpi Gilboa\vendor\paragonie\sodium_compat\src) symfony/cache in (D:\Glpi Gilboa\vendor\symfony\cache) html2text/html2text in (D:\Glpi Gilboa\vendor\html2text\html2text\src) symfony/css-selector in (D:\Glpi Gilboa\vendor\symfony\css-selector) symfony/dom-crawler in (D:\Glpi Gilboa\vendor\symfony\dom-crawler) twig/twig in (D:\Glpi Gilboa\vendor\twig\twig\src) twig/string-extra in (D:\Glpi Gilboa\vendor\twig\string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 in (D:\Glpi Gilboa\vendor\symfony\polyfill-php81)

Not active

Way of sending emails: SMTP (anonymous@e2ksmtp01.e2k.ad.ge.com)

 

fields               Name: Additional Fields              Version: 1.13.0-rc6 State: Enabled 	datainjection        Name: Data injection                 Version: 2.11.0-rc3 State: Enabled 	manageentities       Name: Entities portal                Version: 4.0.0-rc1  State: Enabled 	formcreator          Name: Form Creator                   Version: 2.13.0-beta.2 State: Enabled 	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled 	genericobject        Name: Objects management             Version: 2.12.0-rc4 State: Enabled

</body>
</html>

**Comment by cconard96** [comment]
Kerberos IMAP support was dropped in 9.5.0.
https://github.com/glpi-project/glpi/pull/7351

**Comment by udi8** [comment]
thank for the quick reply,
is there any way to get it back?
