### ISSUE TITLE
Tickets created by recievers can override GLPI CSS

### ISSUE THREAD

**Issue by sacreteez** [glpi-project/glpi#12457]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Tickets that are created by EMails from receivers can override GLPI's CSS. This happens when the EMails have a <style></style>.  GLPI is restyled both on the ticket.php and ticket.form.php.

The expected functionality would be:  EMail CSS would only affect individual instances of followups or individual instances of ticket descriptions.

### Page URL

tick.form.php  and ticket.php

### Steps To reproduce

1.Setup Receiver to Create Tickets from EMail.
2.Send and EMail that contains some styles in <style></style>
3.In Ticketing Visit: ticket.php. When that ticket appears in the list is will overwrite GLPI's CSS

**Comment by cconard96** [comment]
Style tags are already removed when using the text editor in the web interface.
As of #12192, they are now also removed from the collected email content.
This fix will be in GLPI 10.0.3.
