### ISSUE TITLE
Bypass of allowed status restrictions on Problem and Change via Massive Actions

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#12469]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

It is possible to bypass existing restrictions of user on Status change on Problem and Change ticket via Massive Action.
Check for isAllowedStatus() is not checked during massive action for Change and Problem tickets.

### Steps To reproduce

1. Create lifecycle for Problem and Change restricting certain statuses
2. Perform massive action on Problem/Change ticket with Update -> Status to status which should be denied by matrix restrictions

### Your GLPI setup information

10.0.2

### Anything else?

I am going to submit PR for this to fix in non-generic way.
Maybe worth considering adding it as common code

**Comment by cedric-anne** [comment]
Fixed by #12519.
