### ISSUE TITLE
User creation rules only applied with Ldap

### ISSUE THREAD

**Issue by DonutsNL** [glpi-project/glpi#12461]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Hi, 

User creation (ldap) rules are only applied when using LDAP and not when a 'user' is created from a plugin (sorry for abusing the incidents a bit).

I am currently working on the PHPSAML plugin. phpSAML has a feature where login of non-existing users (in GLPI) is allowed by creating the corresponding user object on the fly (JIT).  

Currently I am working on adding the rule-engine to allow users to be created based on predefined rules. 

This also got me wondering, that adding specific rules (basically recreating the LDAP ruleset) for each authentication adapter doesn't make allot of sense, is error prone and duplicates already existing code. 

Why not refactor the already implemented LDAP rules to always be applied on user creation? It will fix all issues state above while also allowing current user administration to be simplified pre-provisioning properties based on predefined criteria.

### Page URL

https://github.com/derricksmith/phpsaml/blob/master/inc/phpsaml.class.php#L74

### Steps To reproduce

Create any user, it will apply default settings.

### Your GLPI setup information

GLPI 10.0.2 ( => /var/www/html)
Installation mode: TARBALL
Current language:en_US

**Comment by trasher** [comment]
As far as I understand, this is not actually a bug; but rather a feature request.

If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us

You can also propose a pull request to implement this feature, or discuss about it on https://suggest.glpi-project.org/ to have it considered for a future GLPI version.
