### ISSUE TITLE
GLPI inventory, table `glpi_devicememories`, column `manufacturers_id` - Out of range value error

### ISSUE THREAD

**Issue by gfh1gfh1** [glpi-project/glpi#12465]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

glpi 10.0.2
glpi-inventory-plugin 1.0.3
glpi-agent 1.4

Column `glpi_devicememories`.`manufacturers_id` in database has a type 'int(10) unsigned'. Inventory task trying to insert value '019880898551' that out of range integer type.

### Relevant log output

```shell
[2022-08-23 07:55:58] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi1/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_devicememories` (`frequence`, `devicememorytypes_id`, `manufacturers_id`, `designation`, `date_creation`, `date_mod`) VALUES ('667', '13', '019880898551', 'DDR2 FB-DIMM - FB-DIMM', '2022-08-23 07:55:56', '2022-08-23 07:55:56')
  Error: Out of range value for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1312
  src/CommonDBTM.php:705                             DBmysql->insert()
  src/CommonDBTM.php:1304                            CommonDBTM->addToDB()
  src/CommonDevice.php:512                           CommonDBTM->add()
  src/Inventory/Asset/Device.php:115                 CommonDevice->import()
  src/Inventory/Asset/MainAsset.php:811              Glpi\Inventory\Asset\Device->handle()
  src/Inventory/Asset/MainAsset.php:731              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:957                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:550              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:697                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:331                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:325    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:237    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"inventory@triw","mem_usage":"0.001\", 10.11Mio)"}
```

### Your GLPI setup information

Operating system: Linux triw 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, readline, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi.elsetisochi.ru Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1-log
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi1
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.PHP version (7.4.30) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.Database engine version (10.5.15) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi1/files/_cache has been validated. Write access to /var/www/html/glpi1/config has been validated. Write access to /var/www/html/glpi1/files/_cron has been validated. Write access to /var/www/html/glpi1/files has been validated. Write access to /var/www/html/glpi1/files/_dumps has been validated. Write access to /var/www/html/glpi1/files/_graphs has been validated. Write access to /var/www/html/glpi1/files/_lock has been validated. Write access to /var/www/html/glpi1/files/_pictures has been validated. Write access to /var/www/html/glpi1/files/_plugins has been validated. Write access to /var/www/html/glpi1/files/_rss has been validated. Write access to /var/www/html/glpi1/files/_sessions has been validated. Write access to /var/www/html/glpi1/files/_tmp has been validated. Write access to /var/www/html/glpi1/files/_uploads has been validated.Write access to /var/www/html/glpi1/files/_cache has been validated.
Write access to /var/www/html/glpi1/config has been validated.
Write access to /var/www/html/glpi1/files/_cron has been validated.
Write access to /var/www/html/glpi1/files has been validated.
Write access to /var/www/html/glpi1/files/_dumps has been validated.
Write access to /var/www/html/glpi1/files/_graphs has been validated.
Write access to /var/www/html/glpi1/files/_lock has been validated.
Write access to /var/www/html/glpi1/files/_pictures has been validated.
Write access to /var/www/html/glpi1/files/_plugins has been validated.
Write access to /var/www/html/glpi1/files/_rss has been validated.
Write access to /var/www/html/glpi1/files/_sessions has been validated.
Write access to /var/www/html/glpi1/files/_tmp has been validated.
Write access to /var/www/html/glpi1/files/_uploads has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi1/marketplace has been validated.Write access to /var/www/html/glpi1/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by trasher** [comment]
I guess this should be fixed now. Please with with latest GLPI nightly build.
