### ISSUE TITLE
Unable to delete domains

### ISSUE THREAD

**Issue by blackxthink** [glpi-project/glpi#12468]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.2

### Bug description

There is no option "Delete" for the domains.

Website : front/domain.php

From the form page:
![bug](https://user-images.githubusercontent.com/48074916/186178354-1697ffc2-9283-432f-80fa-25553061e5f9.png)

From the list page:

![bug2](https://user-images.githubusercontent.com/48074916/186178645-9e958591-28a2-4dcb-8ff5-e59a57cbed58.png)

![bug3](https://user-images.githubusercontent.com/48074916/186178659-8f532537-8852-4a89-89b2-28ba39236a0a.png)

### Page URL

front/domain.php

**Comment by cconard96** [comment]
I cannot recreate the issue. Does your profile have the permission to delete Domains?

**Comment by blackxthink** [comment]
> I cannot recreate the issue. Does your profile have the permission to delete Domains?

Oh wow, i am not proud of that one.
Thank you !
