### ISSUE TITLE
Title of column for problem

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1247]
Column for number of ticket appeared with a wrong title
Informations financières et administratives - Nombre de tickets
instead of 
Ticket - Nombre de tickets

**Comment by trasher** [comment]
I was not able to reproduce this issue :/ Could you please precise where the problem appears?

Thank you :)

**Comment by yllen** [comment]
J'ai un problème avec un ordinateur lié.
Dans le moteur de recherche je demande l'affichage de la date de livraison dans les informations financières.
Ensuite dans mes préférences d'affichage je demande l'affiche du nombre de ticket

**Comment by orthagh** [comment]
I reproduce on my side.
To sum up the issue:

- In Assistance > Problems
- You need to have a problem with at min 1 computer associated
- Search with the metacriteria AND Computer - delivery date - contains - 2016
- Add in displaypreferences the "number of tickets" column

**Comment by orthagh** [comment]
Ok found it.
with #1194 and 396d445d another conflict appears between:
- problem criteria (https://github.com/glpi-project/glpi/blob/master/inc/problem.class.php#L491-L498)
```php
$tab[141]['table']         = 'glpi_problems_tickets';
$tab[141]['field']         = 'id';
$tab[141]['name']          = _x('quantity', 'Number of tickets');
...
```
- problem metacriteria from computer infocom (https://github.com/glpi-project/glpi/blob/master/inc/infocom.class.php#L1327-L1332)
```php
$tab[141]['table']               = 'glpi_infocoms';
$tab[141]['field']               = 'delivery_date';
$tab[141]['name']                = __('Delivery date');
...
```
