### ISSUE TITLE
10.0.3-dev: Network port metrics - no graph Input/Output 

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12472]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3-dev

### Bug description

1. Go to the Assets > Network devices
2. Open some switch.
3. Go to the 'Network' ports tab.
4. Choose an active port and enter it.
5. Go to the 'Network port metrics' tab.

![image](https://user-images.githubusercontent.com/68922721/186199518-a361a315-8739-4d35-a1b6-3a489bb84e08.png)

It looks like something should be displayed here, but there is no data.

### Page URL

front/networkport.form.php?id=

### Anything else?

I found this [https://github.com/glpi-project/glpi/pull/10987](https://github.com/glpi-project/glpi/pull/10987) but I have made these changes, so it's not relevant

**Comment by cconard96** [comment]
Do you have any errors in your browser's console (F12 key > Console tab)?

**Comment by WebGregGit** [comment]
Hi @cconard96 

Yes I do

![image](https://user-images.githubusercontent.com/68922721/186345722-279032d5-954a-4af2-a257-cb993fa8f6e3.png)

And after expanded:

<html>
<body>


  | (anonymous) | @ | VM233:5
-- | -- | -- | --
  | mightThrow | @ | jquery.js:3766
  | process | @ | jquery.js:3834
  | setTimeout (async) |   |  
  | jQuery.readyException | @ | jquery.js:4058
  | (anonymous) | @ | jquery.js:4078
  | mightThrow | @ | jquery.js:3766
  | process | @ | jquery.js:3834
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery.js:3872
  | fire | @ | jquery.js:3500
  | fireWith | @ | jquery.js:3630
  | fire | @ | jquery.js:3638
  | fire | @ | jquery.js:3500
  | fireWith | @ | jquery.js:3630
  | process | @ | jquery.js:3854
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery.js:3872
  | fire | @ | jquery.js:3500
  | add | @ | jquery.js:3559
  | (anonymous) | @ | jquery.js:3892
  | eval | @ | VM195:970
  | obj.<computed> | @ | VM195:180
  | then | @ | jquery.js:3877
  | jQuery.fn.ready | @ | jquery.js:4072
  | jQuery.fn.init | @ | jquery.js:3227
  | eval | @ | VM195:225
  | obj.<computed> | @ | VM195:180
  | jQuery | @ | jquery.js:161
  | (anonymous) | @ | VM233:4
  | DOMEval | @ | jquery.js:133
  | domManip | @ | jquery.js:6114
  | append | @ | jquery.js:6250
  | (anonymous) | @ | jquery.js:6344
  | access | @ | jquery.js:4171
  | html | @ | jquery.js:6311
  | (anonymous) | @ | networkport.form.php?id=115353:1852
  | fire | @ | jquery.js:3500
  | fireWith | @ | jquery.js:3630
  | done | @ | jquery.js:9796
  | (anonymous) | @ | jquery.js:10057
  | load (async) |   |  
  | send | @ | jquery.js:10076
  | ajax | @ | jquery.js:9690
  | eval | @ | VM195:378
  | obj.<computed> | @ | VM195:180
  | jQuery.<computed> | @ | jquery.js:9846
  | loadTabContents | @ | networkport.form.php?id=115353:1851
  | (anonymous) | @ | networkport.form.php?id=115353:1875
  | dispatch | @ | jquery.js:5430
  | elemData.handle | @ | jquery.js:5234
  | trigger | @ | jquery.js:8719
  | (anonymous) | @ | jquery.js:8797
  | each | @ | jquery.js:385
  | each | @ | jquery.js:207
  | trigger | @ | jquery.js:8796
  | trigger | @ | tabler.js:5026
  | complete | @ | tabler.js:7841
  | _transitionComplete | @ | tabler.js:7894
  | complete | @ | tabler.js:7855
  | _activate | @ | tabler.js:7860
  | show | @ | tabler.js:7846
  | (anonymous) | @ | tabler.js:7904
  | each | @ | jquery.js:385
  | each | @ | jquery.js:207
  | jQueryInterface | @ | tabler.js:7898
  | (anonymous) | @ | networkport.form.php?id=115353:1879
  | mightThrow | @ | jquery.js:3766
  | process | @ | jquery.js:3834
  | setTimeout (async) |   |  
  | (anonymous) | @ | jquery.js:3872
  | fire | @ | jquery.js:3500
  | fireWith | @ | jquery.js:3630
  | fire | @ | jquery.js:3638
  | fire | @ | jquery.js:3500
  | fireWith | @ | jquery.js:3630
  | ready | @ | jquery.js:4110
  | completed | @ | jquery.js:4120


</body>
</html>

By the way - take a look at the port id :) I have a problem with constantly deleting printer's network ports and adding them again.

<html>
<body>


2022-08-24 07:38 | inventory | Current counter of pages | Change 1171 to 1187
2022-08-24 07:38 | inventory | Last inventory date | Change 2022-08-24 05:48 to 2022-08-24 07:38
2022-08-24 07:38 | inventory | Network port | Delete an item: Network port ()
2022-08-24 05:48 | inventory | Last inventory date | Change 2022-08-23 07:32 to 2022-08-24 05:48
2022-08-24 05:48 | inventory | Network port | Delete an item: Network port ()
2022-08-23 07:32 | inventory | Current counter of pages | Change 1068 to 1171
2022-08-23 07:32 | inventory | Last inventory date | Change 2022-08-23 06:03 to 2022-08-23 07:32
2022-08-23 07:32 | inventory | Network port | Delete an item: Network port ()
2022-08-23 06:03 | inventory | Last inventory date | Change 2022-08-19 08:17 to 2022-08-23 06:03
2022-08-23 06:03 | inventory | Network port | Delete an item: Network port ()
2022-08-19 08:17 | inventory | Current counter of pages | Change 1059 to 1068
2022-08-19 08:17 | inventory | Last inventory date | Change 2022-08-19 07:39 to 2022-08-19 08:17
2022-08-19 08:17 | inventory | Network port | Delete an item: Network port ()
2022-08-19 07:39 | inventory | Last inventory date | Change 2022-08-18 08:57 to 2022-08-19 07:39
2022-08-19 07:39 | inventory | Network port | Delete an item: Network port ()


</body>
</html>

There is a lot of spam in the History tab :)

**Comment by stonebuzz** [comment]
I reproduce, let me find an fix =)

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
can you test this -> #12476 (you need to clear browser cache)

For History tab can you pen new issue? 

Best regards

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

![image](https://user-images.githubusercontent.com/68922721/186392541-15c53d59-c270-40e5-bd89-be8f2439acf9.png)

**Comment by stonebuzz** [comment]
@WebGregGit 
can you past here data from table glpi_networkport_metrics for this network port ?

Best regards

**Comment by WebGregGit** [comment]
I checked front/networkport.form.php site and it's empty. Nothing is loading. I don't know if it should be like that and if it has anything to do with it.

I checked the table and they are actually 0. But shouldn't it also present the data differently then? At the moment, it looks like something is not loading.

I sorted by "ifinbytes" and found something with the data but it didn't change much:

![image](https://user-images.githubusercontent.com/68922721/186401533-f8cf282d-d363-4540-a846-19df889e9f3e.png)


![image](https://user-images.githubusercontent.com/68922721/186401459-ec1aaf0b-d87c-4f58-bb0c-c7f555f31fe7.png)

**Comment by WebGregGit** [comment]
Perhaps there are still some changes that I haven't made yet. I have a nightly build installed, but it's about a month ago.

I don't want to install a new one because not all the fixes you've released have been merged so far, and I don't want to manually change all these files again, because I don't even remember how many it was :-D

**Comment by stonebuzz** [comment]
Can you disconnect / reconnect to GLPI and retry ?

**Comment by WebGregGit** [comment]
OK, I'll try to do a backup in a few hours, install the nightly, deploy the fix and let you know what it looks like.

**Comment by stonebuzz** [comment]
No ,  disconnect / reconnec your GLPI session (log out / log in)

**Comment by stonebuzz** [comment]
with your data and  https://github.com/glpi-project/glpi/pull/12476

![image](https://user-images.githubusercontent.com/7335054/186439452-1716f29d-bf7c-477d-8487-722440dc95be.png)

I do not reproduce, widget is displayed correctly

![image](https://user-images.githubusercontent.com/7335054/186439601-8d9e1ee5-67d7-41bc-a9b6-81d77dc9bfef.png)

Which browser are you using?

**Comment by stonebuzz** [comment]
Chrome
I reproduce
![image](https://user-images.githubusercontent.com/7335054/186441298-1de933eb-8697-4605-b663-e590df5a7e3f.png)

Let me check

**Comment by WebGregGit** [comment]
Yes I get this error in Chrome. The same in Edge. But in Firefox...

![image](https://user-images.githubusercontent.com/68922721/186442584-cef675a1-905a-487b-980b-c1175b813fcf.png)

:)

**Comment by stonebuzz** [comment]
Hi  @WebGregGit 

I have just modified the PR can you retry ?

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

It looks better, but still no chart - all my ports have stopped on 6/23/2022. From that day, despite the forced inventory - no new date appears.

![image](https://user-images.githubusercontent.com/68922721/186605311-339fd029-0337-434e-a1ab-d286bf3aa8e3.png)


PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Comment by stonebuzz** [comment]
That's another problem, can you open a new issue for 

- NetworkPort metric not updated
- Bad display of link icon

**Comment by WebGregGit** [comment]
Sure. Thanks for a good job with the graph as usual, 
I'm closing :)
