### ISSUE TITLE
10.0.3-dev - NetworkPort metric not updated

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12483]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3-dev

### Bug description

All my ports metric have stopped on 6/23/2022. From that day, despite the forced inventory - no new date appears.

![image](https://user-images.githubusercontent.com/68922721/186605311-339fd029-0337-434e-a1ab-d286bf3aa8e3.png)

### Steps To reproduce

1. Go to the Assets > Network devices.
2. Open some switch.
3. Go to the 'Network' ports tab.
4. Choose an active port and enter it.
5. Go to the 'Network port metrics' tab.

### Your GLPI setup information

GLPI 10.0.3-dev ( => /var/www/html/glpi)     (build date: 2022-08-24)
Installation mode: TARBALL
Current language:en_GB

Operating system: Linux chronos 5.4.0-124-generic #140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64

PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="10M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at xxx.xxx.xxx.xxx Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.30-0ubuntu0.20.04.2
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: user@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.PHP version (7.4.3) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.Database engine version (8.0.30) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

	datainjection        Name: Data injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.3      State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.9.2      State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace

**Comment by trasher** [comment]
Could you provide examples inventory files we can use to reproduce? Metrics themselves seems to work as expected, so I suspect another issue with inventory.

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
can you test this -> https://github.com/glpi-project/glpi/pull/12528

The ```NetworkPortMetric``` has a uniqueness constraint on the date of addition/update of the ```NetworkPort```

So if you take an inventory X times today, you will only get one metric for today.

**Comment by trasher** [comment]
You will only get the latest (that's what is currently tested in our UT suite)

**Comment by WebGregGit** [comment]
Hi @stonebuzz and @trasher 

Sorry, I was on vacation :) I tried with https://github.com/glpi-project/glpi/pull/12528 but no change. I still have no data.

![image](https://user-images.githubusercontent.com/68922721/188492121-34ca2f28-dc3d-4035-97be-d11f3283007f.png)

**Comment by stonebuzz** [comment]
I do not reproduce 

![image](https://user-images.githubusercontent.com/7335054/188565656-39203bef-304c-4964-bdb1-dcf4aacc3352.png)

Can you provide two XMLs on two different inventory days ?

Best regards

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

Can it be a fragment of only one port as above?

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

I noticed that the xml file contains new data. But nothing changes in the graph. Either this information is not entered into the database, or the code does not read it from the database correctly.

I'm not sure if I am looking correctly, but when I checked the table glpi_networkportmetrics and and looked for the id of this port above (networkports_id column). I found only one entry. Shouldn't there be more? Several days are several lines with different data for the same networkports_id

**Comment by stonebuzz** [comment]
Have you apply latest version of PR ? 
 
Between this comment  (7 days ago)

> Hi @WebGregGit can you test this -> #12528
> 
> The `NetworkPortMetric` has a uniqueness constraint on the date of addition/update of the `NetworkPort`
> 
> So if you take an inventory X times today, you will only get one metric for today.

And the moment where PR was merged, I changed the way I update the metrics

Can you check that you have the latest version

```patch
diff --git a/src/Inventory/Asset/NetworkPort.php b/src/Inventory/Asset/NetworkPort.php
index 01d7f8c0f93..39f04e8169c 100644
--- a/src/Inventory/Asset/NetworkPort.php
+++ b/src/Inventory/Asset/NetworkPort.php
@@ -38,6 +38,7 @@
 
 use Glpi\Inventory\Conf;
 use Glpi\Inventory\FilesToJSON;
+use NetworkPort as GlobalNetworkPort;
 use NetworkPortType;
 use QueryParam;
 use RuleImportAssetCollection;
@@ -443,6 +444,21 @@ private function handleVlans(\stdClass $port, int $netports_id)
         }
     }
 
+    private function handleMetrics(\stdClass $port, int $netports_id)
+    {
+        $input = (array)$port;
+        //only update networkport metric if needed
+        if (isset($input['ifinbytes'], $input['ifoutbytes'], $input['ifinerrors'], $input['ifouterrors'])) {
+            $netport = new GlobalNetworkPort();
+            $input_db['id'] = $netports_id;
+            $input_db['ifinbytes']   = $input['ifinbytes'];
+            $input_db['ifoutbytes']  = $input['ifoutbytes'];
+            $input_db['ifinerrors']  = $input['ifinerrors'];
+            $input_db['ifouterrors'] = $input['ifouterrors'];
+            $netport->update($input_db);
+        }
+    }
+
     private function prepareAggregations(\stdClass $port, int $netports_id)
     {
         if (!property_exists($port, 'logical_number')) {
@@ -525,6 +541,7 @@ protected function portChanged(\stdClass $port, int $netports_id)
         $this->handleConnections($port, $netports_id);
         $this->handleVlans($port, $netports_id);
         $this->prepareAggregations($port, $netports_id);
+        $this->handleMetrics($port, $netports_id);
     }
 
     /**

```
Best regards

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

It works! :-D 

I misunderstood the previous statement. I thought the point is that in order for the graph to draw, I need inventories from at least two days. Meanwhile, after applying the fix, I need at least two days to see the effect :) 

Thank you again :)
