### ISSUE TITLE
10.0.3-dev -  SQL warnings when sorting by IP

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12488]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3-dev

### Bug description

When I try to sort by "Networking - IP" column in debug mode, I get this:

![image](https://user-images.githubusercontent.com/68922721/186634122-191e2ac3-cc50-4776-aaa4-e82a9171953d.png)

### Page URL

front/computer.php

### Steps To reproduce

1. Go to the Assets > Computers.
2. Add a column "Networing IP"
3. Enable the debug mode.
4. Sort by a column "Networing IP"

### Your GLPI setup information

GLPI 10.0.3-dev ( => /var/www/html/glpi) (build date: 2022-08-24)
Installation mode: TARBALL
Current language:en_GB

Operating system: Linux chronos 5.4.0-124-generic https://github.com/glpi-project/glpi/issues/140-Ubuntu SMP Thu Aug 4 02:23:37 UTC 2022 x86_64

PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )

### Anything else?

The warning in taxt:

> SQL Warnings: 1411: Incorrect string value: '`glpidb`.`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`' for function inet_aton 1411: Incorrect string value: '`glpidb`.`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`' for function inet_aton 1411: Incorrect string value: '`glpidb`.`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`' for function inet_aton 1411: Incorrect string value: '`glpidb`.`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`' for function inet_aton 1411: Incorrect string value: '`glpidb`.`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`' for function inet_aton 1411: Incorrect string value: '`glpidb`.`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`' for function inet_aton in query "SELECT DISTINCT `glpi_computers`.`id` AS id, 'username' AS currentuser, `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`, `glpi_computers`.`name` AS `ITEM_Computer_1`, `glpi_computers`.`id` AS `ITEM_Computer_1_id`, `glpi_computers`.`contact` AS `ITEM_Computer_7`, `glpi_computers`.`otherserial` AS `ITEM_Computer_6`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`, '__NULL__'), '$#$',`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`id`) ORDER BY `glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`id` SEPARATOR '$$##$$') AS `ITEM_Computer_126`, `glpi_agents`.`last_contact` AS `ITEM_Computer_902`, `glpi_locations`.`completename` AS `ITEM_Computer_3` FROM `glpi_computers` LEFT JOIN `glpi_ipaddresses` AS `glpi_ipaddresses_937b8c393ea02752d06397f2628684f5` ON (`glpi_computers`.`id` = `glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`mainitems_id` AND `glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`mainitemtype` = 'Computer' AND `glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`is_deleted` = '0' ) LEFT JOIN `glpi_agents` ON (`glpi_computers`.`id` = `glpi_agents`.`items_id` AND `glpi_agents`.`itemtype` = 'Computer' ) LEFT JOIN `glpi_locations` ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id` ) WHERE `glpi_computers`.`is_deleted` = 0 AND `glpi_computers`.`is_template` = 0 GROUP BY `glpi_computers`.`id` ORDER BY INET_ATON(`glpi_ipaddresses_937b8c393ea02752d06397f2628684f5`.`name`) ASC LIMIT 0, 20"

Previously, I was looking for hints on the forum: [https://forum.glpi-project.org/viewtopic.php?pid=494652](https://forum.glpi-project.org/viewtopic.php?pid=494652)

By the way - please note that the warning message is in the foreground. It covers all other options, e.g. the expansion of the profile options (to turn off debug mode) or the options on the left. I guess it would be better if the layer with the message was displayed a little lower.

**Comment by stonebuzz** [comment]
@WebGregGit 
 I do not reproduce
Which column do you display

**Comment by WebGregGit** [comment]
This only applies to sort by IP. Even if it is the only column displayed (+ default Name). When I sort by another column, e.g. by name, the error disappears. 

The debug mode must be on.

**Comment by stonebuzz** [comment]
I think you have the wrong data in the database
can you check ```name``` column from ```glpi_ipadresses``` table.

Maybe 
```sql
SELECT * FROM glpi_adresses WHERE INET_ATON('name') IS NULL;
```
And past here result

**Comment by WebGregGit** [comment]
Yes, I am looking for a database, but I do not know SQL. 

I changed your query (I don't have table glpi_adresses):

`SELECT * FROM `glpi_ipaddresses` WHERE `version` LIKE '4' AND INET_ATON('name') IS NULL ORDER BY `glpi_ipaddresses`.`name` DESC;`

But it returns all the records to me. And they all have an IP address entered in the name column

**Comment by stonebuzz** [comment]
I made a mistake

can you retry with

````sql
SELECT * FROM glpi_ipaddresses WHERE version LIKE '4' AND INET_ATON(glpi_ipaddresses.name) IS NULL ORDER BYglpi_ipaddresses.name DESC;
```

**Comment by WebGregGit** [comment]
0 results

**Comment by stonebuzz** [comment]
And this

```sql
SELECT INET_ATON(glpi_ipaddresses.name) FROM glpi_ipaddresses WHERE version LIKE 4 order by glpi_ipaddresses.name;
```

**Comment by WebGregGit** [comment]
Returns all.

What you think about "glpi_ipaddresses_937b8c393ea02752d06397f2628684f5"? 
Am I mistaken that he is looking for a table with that name? It is "glpi_ipaddresses" but not with "_937b8c393ea02752d06397f2628684f5".

**Comment by stonebuzz** [comment]
it's an alias used by GLPI, but your SQL query works with my database
Did you try running the query directly in MySQL

```sql
SELECT  DISTINCT glpi_computers.id  AS id
       ,'username'                  AS currentuser
       ,glpi_computers.entities_id
       ,glpi_computers.is_recursive
       ,glpi_computers.name         AS ITEM_Computer_1
       ,glpi_computers.id           AS ITEM_Computer_1_id
       ,glpi_computers.contact      AS ITEM_Computer_7
       ,glpi_computers.otherserial  AS ITEM_Computer_6
       ,GROUP_CONCAT(DISTINCT CONCAT(IFNULL(glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.name,'NULL'),'$#$',glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.id) ORDER BY glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.id SEPARATOR '$$##$$') AS ITEM_Computer_126
       ,glpi_agents.last_contact    AS ITEM_Computer_902
       ,glpi_locations.completename AS ITEM_Computer_3
FROM glpi_computers
LEFT JOIN glpi_ipaddresses AS glpi_ipaddresses_937b8c393ea02752d06397f2628684f5
ON (glpi_computers.id = glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.mainitems_id AND glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.mainitemtype = 'Computer' AND glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.is_deleted = '0' )
LEFT JOIN glpi_agents
ON (glpi_computers.id = glpi_agents.items_id AND glpi_agents.itemtype = 'Computer' )
LEFT JOIN glpi_locations
ON (glpi_computers.locations_id = glpi_locations.id )
WHERE glpi_computers.is_deleted = 0
AND glpi_computers.is_template = 0
GROUP BY  glpi_computers.id
ORDER BY INET_ATON(glpi_ipaddresses_937b8c393ea02752d06397f2628684f5.name) ASC
LIMIT 0, 20
```

**Comment by WebGregGit** [comment]
Same result. One is empty, second returns too many. But I noticed that the second command returns duplicate entries:

|                       3232243537 |
|                       3232243538 |
|                       3232243539 |
|                       3232243540 |
|                       3232248321 |
|                       3232249857 |
|                       3232249857 |
|                       3232249857 |
|                       3232237057 |
|                       1427005602 |
|                       1427005602 |
|                       1427005602 |
|                       1427005602 |
|                       1427005602 |
|                       1427005602 |
|                       1427005602 |
|                       1427005602 |

**Comment by stonebuzz** [comment]
> If you meant running a command:
> "SELECT DISTINCT glpi_computers.id".... etc.

Yes =)

> SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''));

Yes is needed

I don't really know how to reproduce on my side :disappointed: 

Can you : 

- Post here a screenshot of displayed column (in Computer list) maybe usefull for me
- Do a dump of glpi_adresses table and upload here

Best regards

**Comment by tsmr** [comment]
For information i have the same problem into addressing plugin. I need to exclude these for not have mysql warnings : 

(`glpi_ipaddresses`.`name` IS NOT NULL AND `glpi_ipaddresses`.`name` != '0.0.0.0' AND `glpi_ipaddresses`.`name` != '')

**Comment by stonebuzz** [comment]
@WebGregGit 
can you try this -> https://github.com/glpi-project/glpi/pull/12503 

Best regards

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

I didn't check your fix yet. I came back because in the meantime I was doing my tests and I found information somewhere that INET_ATON does not support IPv6. So I deleted all entries containing IPv6 and the warnings are missing :)

I need to restore a backup and see what your fix changes now :)
