### ISSUE TITLE
SLA Rules

### ISSUE THREAD

**Issue by DeltatecAS** [glpi-project/glpi#12489]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

Hello,

I have a little problem. I created lots of SLA assignment rules based on the urgency and category of a ticket.

The problem is that I have the impression that when creating tickets it does not always fit into the rules because it works half the time. Some tickets do have an SLA and some don't. While the conditions are the same.

Have you ever had a similar problem?

Thanks in advance

### Your GLPI setup information

GLPI installed on Ubuntu 8
MySQL installed on windows server 2019

**Comment by cconard96** [comment]
Please write in English (automatic translations are OK).

Having issues reported all in English helps ensure that searching for existing/already reported issues is easier.
Also, the community and development team is international so having a common language helps us too.

Veuillez écrire en anglais (les traductions automatiques sont acceptables).

Le fait que les problèmes signalés soient tous en anglais permet de faciliter la recherche de problèmes existants ou déjà signalés.
De plus, la communauté et l'équipe de développement étant internationales, le fait d'avoir une langue commune nous aide également.

**Comment by DeltatecAS** [comment]
Ok it's done

**Comment by DeltatecAS** [comment]
No idea ?

**Comment by cconard96** [comment]
If these are rules that run on the update of a ticket, it is important to realize that the conditions refer to the changes being made and does not account for the current fields. So, if you only change the category the rule criteria for the urgency will never match because the "change" is non-existent/empty. Both fields must be changed simultaneously.

**Comment by DeltatecAS** [comment]
No idea ?

**Comment by DeltatecAS** [comment]
Obviously when I use the FormCreator plugin to create a ticket (via a form) my SLAs are fine, while when I create a ticket without going through a form I don't have my SLAs

**Comment by DeltatecAS** [comment]
Please help me

**Comment by DeltatecAS** [comment]
I am awaiting a response.
Should I recall my problem?
Anyway, I'm going to do some research but if anyone has an idea it would help me.

**Comment by cedric-anne** [comment]
Hi,

Could you please give all details about your SLA rules, the content of created ticket, the creation context (simplified or standard interface) and the corresponding ticket template ?
I will try to investigate on it.

**Comment by trasher** [comment]
No feedback, I close
