### ISSUE TITLE
Creating a ticket with an objserver status=assigned

### ISSUE THREAD

**Issue by DeltatecAS** [glpi-project/glpi#12490]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10

### Bug description

Hello,

When creating a ticket, if there is an observer who has been encoded, the ticket automatically changes to "Assigned" status. This is quite problematic for technicians who filter on tickets not yet assigned.

Thanks in advance.

Have a good day.

**Comment by DeltatecAS** [comment]
No idea ?

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on [current nightly build](https://nightly.glpi-project.org/glpi/). Could you check if problem still exists ?

**Comment by guieloi** [comment]
> 

This problem still exists on 10.0.2. I already test in my enviroment and GLPI Cloud. When a self-service add an observer when is opening one ticket, doesn't save the observer. And after it, the self-service can't add an observer becaus the field is disabled.

**Comment by trasher** [comment]
@guieloi test with latest nightly build as requested

**Comment by DeltatecAS** [comment]
The problem still exists.

When i create a ticket with observator, the ticket is directly on status assigned. But there are no technician affected
