### ISSUE TITLE
GLPI10: Image loading problem via email

### ISSUE THREAD

**Issue by Gitnor77** [glpi-project/glpi#12494]
I have the same problem.

GLPI 10.0.2 Case 1:
![image](https://user-images.githubusercontent.com/109066311/186832723-fafe093e-4392-4eb5-87f1-375a2b87a2ab.png)

![image](https://user-images.githubusercontent.com/109066311/186832882-69d712f1-3e6b-4d22-9df4-8ce699e71385.png)

GLPI 10.0.2 Case 2:
![image](https://user-images.githubusercontent.com/109066311/186833054-6ddcb56e-cfd5-413a-87fa-10bcc65ac47c.png)

![image](https://user-images.githubusercontent.com/109066311/186833191-69bce5b3-f0cc-4fe3-bafb-2a680363b4a8.png)

GLPI 9.5.7
![image](https://user-images.githubusercontent.com/109066311/186833603-0f65316e-5406-4566-8c3d-62f078e2aca9.png)

![image](https://user-images.githubusercontent.com/109066311/186833523-8b1b5e27-72f4-4ed7-8a73-f8131ea4d7d4.png)

GLPI 10 -> this problem is random, occurs with photos added in the body of the email. 
GLPI 9 -> everything works properly.

_Originally posted by @Gitnor77 in https://github.com/glpi-project/glpi/issues/12438#issuecomment-1228122399_

**Comment by cedric-anne** [comment]
Hi,

Please provide the email export (eml file format) corresponding to the source of this ticket.

**Comment by trasher** [comment]
No feedback, I close
