### ISSUE TITLE
Cannot add group if "assigned to" is mandatory

### ISSUE THREAD

**Issue by blackxthink** [glpi-project/glpi#12493]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.2

### Bug description

In our system, we want to make "assigned to" as mandatory.
Sometimes, we need to assign a ticket to a group of technicians.

When the "assigned to" is mandatory, we get an error as if the technician was empty.
Everything works fine if I turn off the mandatory.

![image](https://user-images.githubusercontent.com/48074916/186757235-dc7ee8bb-62c6-4466-9366-78130cf1f9f9.png)

I tried adding technician and technician group, but none works : 
![image](https://user-images.githubusercontent.com/48074916/186757363-038f9c38-1455-43d3-9439-4d06de58fcb9.png)

### Page URL

front/ticket.form.php

### Steps To reproduce

Create a ticket
add a group to "assigned to" with the field being mandatory (in the ticket template)

Try to create the ticket and you will get a pop up saying that it is empty.

**Comment by cconard96** [comment]
The "Technician" field refers only to assigned users. Having both "Technician" and "Technician Group" as mandatory fields would mean that both need to be present. This does not seem to be a bug. It sounds like this could be a feature request to have an option for "Any assigned" (or similarly named) to make having any user, group or supplier assigned a requirement.

If you want to sponsor this feature, feel free to contact your partner manager, or submit this form: https://portal.glpi-network.com/contact-us

You can also propose a pull request to implement this feature, or discuss about it on https://suggest.glpi-project.org/ to have it considered for a future GLPI version.

**Comment by trasher** [comment]
I agree with @cconard96; this does not seems to be a bug; but rather a feature request.
