### ISSUE TITLE
When installing from scratch a Javascript error occurs

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#125]
![image](https://cloud.githubusercontent.com/assets/7569958/10021601/121a435e-6149-11e5-96b5-0fbe2d54be6f.png)

Seems like $CFG_GLPI['ajax_limit_count'] is not initialized with a default value in html.class.php line 4529

regards,
Tomolimo

**Comment by orthagh** [comment]
no other php or sql errors in log ?

**Comment by tomolimo** [comment]
No, and the problem is that the value of $CFG_GLPI['ajax_limit_count'] is not set by default.
After added `$CFG_GLPI['ajax_limit_count'] = 50 ;` at the end of config/define.php it's ok :)

**Comment by orthagh** [comment]
Can you confirm the error occurs in install.php
