### ISSUE TITLE
Cannot input decimal monitor size 

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#1250]
Hello!
In monitors tab have a string, where we can input size of monitor in inches.
But this string eats only integer numbers, not decimal (trying to type "18.5 or 21,5", for example, string will cancel this and returns the old value)
Many monitors (like this http://www.usa.philips.com/c-p/223V5LSB_27/lcd-monitor-with-smartcontrol-lite - 21.5) have decimal screen size 
How to input 21.5?

**Comment by orthagh** [comment]
Currently glpi_monitors.size field in db type is integer.
I think we could move it to decimal.

**Comment by trasher** [comment]
I guess this change should not be in a minor release.

**Comment by AnaelMobilia** [comment]
@trasher As your wrote, I push it to master branch.
Changes are minor but open to more specific changes : the search bar require "22%" to display my 22.5 screen.
It's linked to the way the SQL query is created (i will open a separate issue for that, it could be an enhancement to automatically add %)
