### ISSUE TITLE
main branch - search by status : incorect dropdown values

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#12521]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.1

### Bug description

When editing a search for ticket / change  with status criteria user may get "undefined" entries

![image](https://user-images.githubusercontent.com/14139801/187502633-f77ecebf-73b9-42a3-99fb-2a04119bdd28.png)

### Page URL

front/change.php

### Steps To reproduce

1. Open tickets list
2. use a simple search by status criteria
3. develop the dropdown to change the seaerched status
4. Type something

See that several undefined values appear.

**Comment by cconard96** [comment]
It looks like this has already been fixed, but the last merge of the bugfixes branch into the main branch was just before this fix was merged 29 days ago.

https://github.com/glpi-project/glpi/pull/12363

Manually applying the patch on top of the main branch resolves the issue.

**Comment by btry** [comment]
Indeed, then I close this issue
