### ISSUE TITLE
[ GLPI 10.0.2] Error in french translation : Project / Contracts

### ISSUE THREAD

**Issue by tristangallet** [glpi-project/glpi#12535]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.2

### Bug description

Hello, 
Langage for the user : Français
If you make a new project, on the left there is "Contracts", should be in french "Contrats". 

It's the same for the langage Français (Canada) and Français (Belgique).

### Steps To reproduce

Change you langage to Français or Français (Canada) or Français (Belgique)
Create a new project
Go to the project, on the left you should see the label "Contracts"

### Your GLPI setup information

GLPI 10.0.2 ( => /var/www/html/support)
Installation mode: TARBALL
Current language:fr_FR

perating system: Linux sv-ff-glpi 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="500M" safe_mode="" session.save_handler="files"
	upload_max_filesize="500M" 
Software: Apache

**Comment by trasher** [comment]
Translations are done using transifex: https://www.transifex.com/glpi/GLPI/dashboard/

**Comment by tristangallet** [comment]
I've checked in transifex, it seems that's it's ok and i haven't seen any modification in the github repository so is it fixed or not ?
