### ISSUE TITLE
automatic action ticket closed does not work

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1255]
![image](https://cloud.githubusercontent.com/assets/15144026/20005489/d0b1bea6-a292-11e6-92a4-66ec74897303.png)

anything happens when execute the task, all my tickets solved stay solved

**Comment by Armin83** [comment]
Did you already configure the days to close in you entity settings ?

**Comment by satyan01** [comment]
yes 20 days, but i would like to force the task to close all tickets solved

**Comment by Armin83** [comment]
I'm not sure if i understand you. You solve a ticket at 02.xx.xxxx it will change to close after 20 days i think the task will do it on 22.xx.xxxx. The task closeticket will do this. If you run closeticket manuall on 23.xx.xxxx it will also close only the tickets in solve state from 02.xx.xxxx or older. if you solve other task on 15.xx.xxx it will be not closed. (for manuell closing use search and multiselect / action...)

**Comment by satyan01** [comment]
I understood better, thank you for your reply
