### ISSUE TITLE
Caracterset

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#12570]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

Wrong caracters on dashbord card

![1](https://user-images.githubusercontent.com/6449156/188128211-d453c6a2-38ed-42c2-9102-b71869d3b7ff.png)

The languade is Portuguese but, in English, the problem is similar:

![2](https://user-images.githubusercontent.com/6449156/188128413-8bbf8867-2984-4ce8-b832-449d839ce145.png)

Thanks

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.1 ( => /var/www/servicedesk/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux srvsd02-pcr 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64
PHP 8.2.0alpha3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at servicedesk Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.70
Server Software: Debian 10
	Server Version: 10.3.34-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.0alpha3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.
The log file has been created successfully.
Write access to /var/www/servicedesk/html/glpi/files/_cache has been validated.
Write access to /var/www/servicedesk/html/glpi/config has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_cron has been validated.
Write access to /var/www/servicedesk/html/glpi/files has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_dumps has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_graphs has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_lock has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_pictures has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_plugins has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_rss has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_sessions has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_tmp has been validated.
Write access to /var/www/servicedesk/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/servicedesk/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/servicedesk/html/glpi
GLPI_CONFIG_DIR: /var/www/servicedesk/html/glpi/config
GLPI_VAR_DIR: /var/www/servicedesk/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/servicedesk/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/servicedesk/html/glpi/files
GLPI_CACHE_DIR: /var/www/servicedesk/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/servicedesk/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/servicedesk/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/servicedesk/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/servicedesk/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/servicedesk/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/servicedesk/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/servicedesk/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/servicedesk/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/servicedesk/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/servicedesk/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/servicedesk/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/servicedesk/html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/servicedesk/html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/servicedesk/html/glpi/locales
GLPI_VERSION: 10.0.1
GLPI_SCHEMA_VERSION: 10.0.1@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (/var/www/servicedesk/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/servicedesk/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/servicedesk/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/servicedesk/html/glpi/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/servicedesk/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/servicedesk/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/servicedesk/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/servicedesk/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/servicedesk/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/servicedesk/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/servicedesk/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/servicedesk/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/servicedesk/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/servicedesk/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/servicedesk/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/servicedesk/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/servicedesk/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/servicedesk/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/servicedesk/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/servicedesk/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/servicedesk/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/servicedesk/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/servicedesk/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/servicedesk/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/servicedesk/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/servicedesk/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/servicedesk/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/servicedesk/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/servicedesk/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/servicedesk/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/servicedesk/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/servicedesk/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/servicedesk/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/servicedesk/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/servicedesk/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/servicedesk/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/servicedesk/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/servicedesk/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/servicedesk/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/servicedesk/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'X.X.X.X', Port: '389', BaseDN: 'OU=XX,OU=XX,DC=XX,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN:
		'CN=glpi,OU=XX,OU=XX,DC=XX,DC=local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@X.X.X.X)

</details><details><summary>Plugins list</summary><pre> 
	fusioninventory      Name: FusionInventory                Version: 10.0.1+1.0 State: Enabled
	pdf                  Name: Imprimir em PDF                Version: 2.1.0      State: Enabled
	oauthimap            Name: Oauth IMAP                     Version: 1.4.0      State: Enabled

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

How to reproduce the issue ? What is the source of this ticket ? API, mail, plugin, simplified interface form, complete interface form, ... ?

Is information is correctly encoded in own ticket page ?

Also, please fill GLPI setup information section in your issue.

**Comment by trasher** [comment]
Also, 10.0.1 is not the latest stable available.

**Comment by rjmontenegro** [comment]
> Hi,
> 
> How to reproduce the issue ? What is the source of this ticket ? API, mail, plugin, simplified interface form, complete interface form, ... ?
> 
> Is information is correctly encoded in own ticket page ?
> 
> Also, please fill GLPI setup information section in your issue.

The soirce of ticket is mail and in own ticket page everiting is ok. The problem is only on dashboard card.
Initially I did not put the system information because it contains information that I do not intend to make publicly available but I will hide this information and publish it.

**Comment by rjmontenegro** [comment]
> Also, 10.0.1 is not the latest stable available.

Yes, the last version still not compatable with my plugins.

**Comment by cedric-anne** [comment]
1. A **critical** security issue has been fixed in GLPI 10.0.2, so it is really risky to not upgrade your GLPI instance.
2. Your are using `PHP 8.2.0alpha3`. Are you using this PHP version on a production server ?

**Comment by rjmontenegro** [comment]
> 2\. Your are using `PHP 8.2.0alpha3`. Are you using this PHP version on a production server ?

Yes, it wasn't supposed to but it was an error during the php update.

**Comment by rjmontenegro** [comment]
> > 2. Your are using `PHP 8.2.0alpha3`. Are you using this PHP version on a production server ?
> 
> Yes, it wasn't supposed to but it was an error during the php update.

Is already in version 8.1.9

**Comment by cedric-anne** [comment]
I am not able to reproduce on current nightly build.

**Comment by rjmontenegro** [comment]
For no reason to justify it, the characters are already displayed correctly!
