### ISSUE TITLE
Problems with display preferences for assets - with generic object

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#12571]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.8 - 10.0.2

### Bug description

No audit of changes to glpi_displaypreferences table in GLPI log audit.
It is not known who changed the global layout for an asset.

Another problem, when a user changes a profile to another owned profile - the field layout changes.

Observed for objects created by generic object plugin.

### Steps To reproduce

1. setting fields as superadmin in one asse
2. switching to another profile - there is a change to the previous layout
3. return to the superadmin profile - some of the fields are changed.

### Your GLPI setup information

 
	fields               Name: Additional Fields              Version: 1.13.0     State: Enabled
	advancedplanning     Name: advancedplanning               Version: 1.0.0      State: Enabled
	barcode              Name: Barcode                        Version: 2.6.2      State: Enabled
	behaviors            Name: Behaviours                     Version: 2.6.0      State: Enabled
	camerainput          Name: Camera Input                   Version: 1.0.3      State: Enabled
	custom               Name: Custom                         Version: 0.90-1.0.1 State: Error / to clean
	datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Enabled
	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.7.4      State: Enabled
	mydashboard          Name: My Dashboard                   Version: 1.8.2      State: Not installed
	notifications        Name: Notifications                  Version: 9.5+1.0    State: Enabled
	genericobject        Name: Objects management             Version: 2.11.1     State: Enabled
	order                Name: Orders management              Version: 2.7.6      State: Enabled
	pdf                  Name: Print to pdf                   Version: 2.0.1      State: Enabled
	printercounters      Name: Printer counters               Version: 1.7.0      State: Enabled
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Enabled
	reports              Name: Reports                        Version: 1.14.1     State: Enabled
	screenshot           Name: Screenshot                     Version: 1.1.7      State: Enabled
	statecheck           Name: Statecheck Rules               Version: 2.3.4      State: Enabled
	manufacturersimports Name: Suppliers imports              Version: 2.3.2      State: Enabled
	tag                  Name: Tag Management                 Version: 2.8.3      State: Enabled
	typology             Name: Typologies                     Version: 2.7.2      State: Enabled

**Comment by Wolvverine** [comment]
It seems that this may also apply to users and profiles where they have revoked permissions to global settings in Setup - Search result display - default display

**Comment by Wolvverine** [comment]
I found the cause.

If it is not in the files/_plugins/genericobject/fields directory
files for each object defined (even if the object only uses fields defined as global/common), then under certain conditions the objects are not displayed.

for each defined object then you need to create a file without field definitions.

```
<?php
global $GO_FIELDS, $LANG;
?>
```

**Comment by trasher** [comment]
Your issue seems to be related only to genericobject plugin. Please open bug report on their bug tracker
