### ISSUE TITLE
Satisfaction - N/A

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#12577]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

after closing the ticket, the user receives a notification about the quality assessment, but the user does not have the opportunity to evaluate, only you can specify a comment.

https://monosnap.com/file/DxpxDif4LtzTJ3PYuVBlG3094SB1ED

### Page URL

https://help.domain.com/marketplace/formcreator/front/issue.form.php?id=8347&tickets_id=2941

### Steps To reproduce

create ticket > execute > set ticket status to close > user will receive a notification by email about the quality assessment > click on the link under the user

### Your GLPI setup information

10.0.2

**Comment by cconard96** [comment]
This seems like it could be an issue with the Form Creator plugin given the URL you provided.
An issue should be raised on their GitHub.
https://github.com/pluginsGLPI/formcreator/issues
