### ISSUE TITLE
API : a search returning an empty dataset has incorrect Content-Range

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1259]
Hi

If I issue a GET /Search/:itemtype and there is no entry in the DB (or criterias excludes all of them) I found content range is wrong. See captures below 

![image](https://cloud.githubusercontent.com/assets/14139801/20055014/9440fb4a-a4df-11e6-8907-475bcf32019a.png)

![image](https://cloud.githubusercontent.com/assets/14139801/20055033/a8ea3b4c-a4df-11e6-90aa-acfacc52fee6.png)

**Comment by btry** [comment]
Content-Range 0-0/0 is meaningless as range from 0 to 0 means there is 1 item, and it enters in conflict witth the fact that totalcount == 0.

Maybe Content-Range should not be returned in such case.

**Comment by newls** [comment]
Thanks @btry for answering me on the other ticket.
I understand thanks to this ticket.
