### ISSUE TITLE
Darker font / display issues

### ISSUE THREAD

**Issue by willgl1** [glpi-project/glpi#12597]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

![glpi issue font](https://user-images.githubusercontent.com/107202756/188629626-c683eed9-47e9-4984-9f71-d4001f5d0fcd.png)

The attached PNG shows the issue. Some of the font is not visible.  Seems to be an issue with the "darker" theme.

I have also noticed within the Administration > Inventory page. That rules for assignment etc are very hard to see in this mode. Along with within tickets not being the easiest on the eyes. 

This is the only mode where the screen is fully dark and it would be good if text was more visible where it needed to be.

### Page URL

http://cdn-v-glpi/uk/front/computer.form.php

### Steps To reproduce

1. Open Computers page
2. select a computer
3. select the components area

**Comment by cconard96** [comment]
> This is the only mode where the screen is fully dark and it would be good if text was more visible where it needed to be.

The Midnight palette is new in 10.0 and has a darker background and more contrast between the font color and background.

**Comment by willgl1** [comment]
Thanks, although there still seems to be an issue with Darker on titles?
