### ISSUE TITLE
Can't reopen a task

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#12606]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0/bf

### Bug description

When a change is cancelled then reopened the status is still "cancelled", but we can add a followup.

### Relevant log output

```shell
No error found in logs
```

### Page URL

front/change.form.php

### Steps To reproduce

1. create a change
2. change its status to "cancelled"
3. click on "reopen button" next to the status
4. See the status is still "cancelled" but we can add a followup

We can also reproduce this behaviour if we set the change to "refused" instead of  "cancelled"

### Anything else?

After reopening the change:

![image](https://user-images.githubusercontent.com/14139801/189059295-6b8b8920-c461-440c-aab1-584cbd58f267.png)

**Comment by yllen** [comment]
When you reopen a change (or a ticket), a followup is displayed to explain why you want to reopen this item.

But, i agree with you, there is a bug because after adding the followup the change stays closed.
