### ISSUE TITLE
Contracts: Allow fine picking of end date

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#12619]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

There is no way to specify a contract _End Date_ to a given day. You set a _Start Date_ and pick a number of months in _Initial contract period_, then the _End Date_ is computed. But we have some contracts that doesn't matches this algorithm.

I think that implementing one of these options would enhance Contracts management:
- adding a dedicated _End Date_ field
  - (which could be prefilled by JS according to _Initial contract period_, so that user experience would not change); or
- allowing to pick a _Initial contract period_ in days instead of only in months.

**Comment by cconard96** [comment]
Feature requests can be made on the UserEcho page. We try to keep just bug reports in GitHub issues.
https://glpi.userecho.com/

**Comment by mathieumd** [comment]
Done: https://glpi.userecho.com/fr/communities/1/topics/2108-contracts-allow-fine-picking-of-end-date
