### ISSUE TITLE
A bug that cuts the administrator off from the settings

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12629]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3-dev

### Bug description

After change the profile interface for Super-Admin - you lose management options.

In my opinion, this is a bug, because the visibility of the administration and setup tab it should depend on permissions, not the chosen interface. 
The user does not see these cards not because of the simple interface, but because of the lack of permissions.

At the moment, I have no way to unscrew what I set due to the lack of permissions. Even when I go to front/profile.php, I get the following message: You don't have permission to perform this action.

### Steps To reproduce

1. Make a backup ;)
2. Go to front/profile.form.php?id=4 (Super Admin)
3. Change the "Profile's interface" to the "Simplified interface".
4. Log out > log back in
5. Start crying if you missed step 1 ;)

**Comment by cconard96** [comment]
If you select the simplified interface, the permissions exclusive to the standard interface no longer apply. It could be a bigger issue if someone purposefully converts a profile to the simplified interface and those users still have permissions that no longer show in that profile.

**Comment by cconard96** [comment]
If you have database access, you can fix the issue by setting the `interface` field to "central" for that profile.
```sql
UPDATE `glpi_profiles` SET `interface` = 'central' WHERE (`id` = '4');
```
