### ISSUE TITLE
[GLPI 10.0.2] - SQL Warnings: 1292: Truncated incorrect DOUBLE value

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#12623]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.2

### Bug description

Hello,

My GLPI instance show warning about one SQL problem.

from memory the only thing i did :

- I have created a child entitie (I have 3 lvl, A, B & C)
- and I moved some entities to **B to C** level.

could you please help me to fix it ?

### Relevant log output

```shell
SQL Warnings: 1292: Truncated incorrect DOUBLE value: '3SKEY' 1292: Truncated incorrect DOUBLE value: '3SKEY' in query "SELECT DISTINCT `glpi_tickets`.`id` AS id, 'USERGLPI' AS currentuser, `glpi_tickets`.`id` AS `ITEM_Ticket_2`, `glpi_tickets`.`name` AS `ITEM_Ticket_1`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`content` AS `ITEM_Ticket_1_content`, `glpi_tickets`.`status` AS `ITEM_Ticket_1_status`, `glpi_entities`.`completename` AS `ITEM_Ticket_80`, `glpi_tickets`.`status` AS `ITEM_Ticket_12`, `glpi_tickets`.`priority` AS `ITEM_Ticket_3`, GROUP_CONCAT(DISTINCT `glpi_users_af1042e23ce6565cfe58c6db91f84692`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_4`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`users_id`, ' ', `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_4_2`, GROUP_CONCAT(DISTINCT `glpi_users_b1b92f6be5e70531688d870931e94a65`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_5`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`users_id`, ' ', `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_5_2`, `glpi_tickets`.`date` AS `ITEM_Ticket_15`, `glpi_tickets`.`date_mod` AS `ITEM_Ticket_19`, `glpi_itilcategories`.`completename` AS `ITEM_Ticket_7`, `glpi_tickets`.`type` AS `ITEM_Ticket_14`, `glpi_tickets`.`internal_time_to_own` AS `ITEM_Ticket_186`, `glpi_tickets`.`status` AS `ITEM_Ticket_186_status`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_tickets`.`tickets_id_1`, '__NULL__'), '$#$',`glpi_tickets_tickets`.`id`) ORDER BY `glpi_tickets_tickets`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_40`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_tickets`.`tickets_id_2`, '__NULL__'), '$#$', `glpi_tickets_tickets`.`id`)ORDER BY `glpi_tickets_tickets`.`id` SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Ticket_40_tickets_id_2`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`items_id`, '__NULL__'), '$#$',`glpi_items_tickets`.`id`) ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_13`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`itemtype`, '__NULL__'), '$#$', `glpi_items_tickets`.`id`)ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Ticket_13_itemtype`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_name_Software`.`name`, '$#$' , `glpi_tickets_name_Software`.`id`) ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$') AS `ITEM_Software_1`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_name_Software`.`id`, '__NULL__'), '$#$', `glpi_tickets_name_Software`.`id`)ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Software_1_id`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_name_Software`.`content`, '__NULL__'), '$#$', `glpi_tickets_name_Software`.`id`)ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Software_1_content`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_name_Software`.`status`, '__NULL__'), '$#$', `glpi_tickets_name_Software`.`id`)ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Software_1_status` FROM `glpi_tickets`LEFT JOIN `glpi_entities` ON (`glpi_tickets`.`entities_id` = `glpi_entities`.`id` ) LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24` ON (`glpi_tickets`.`id` = `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`tickets_id` AND `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`type` = '1' )LEFT JOIN `glpi_users` AS `glpi_users_af1042e23ce6565cfe58c6db91f84692` ON (`glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`users_id` = `glpi_users_af1042e23ce6565cfe58c6db91f84692`.`id` ) LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5` ON (`glpi_tickets`.`id` = `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`tickets_id` AND `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`type` = '2' )LEFT JOIN `glpi_users` AS `glpi_users_b1b92f6be5e70531688d870931e94a65` ON (`glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`users_id` = `glpi_users_b1b92f6be5e70531688d870931e94a65`.`id` )LEFT JOIN `glpi_itilcategories` ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id` ) LEFT JOIN `glpi_tickets_tickets` ON ((`glpi_tickets`.`id` = `glpi_tickets_tickets`.`tickets_id_1` OR `glpi_tickets`.`id` = `glpi_tickets_tickets`.`tickets_id_2`) ) LEFT JOIN `glpi_items_tickets` ON (`glpi_tickets`.`id` = `glpi_items_tickets`.`tickets_id` ) LEFT JOIN `glpi_items_tickets` AS `glpi_items_tickets_Software` ON (`glpi_items_tickets_Software`.`tickets_id` = `glpi_tickets`.`id` AND `glpi_items_tickets_Software`.`itemtype` = 'Software' ) LEFT JOIN `glpi_softwares` ON (`glpi_items_tickets_Software`.`items_id` = `glpi_softwares`.`id` ) LEFT JOIN `glpi_tickets` AS `glpi_tickets_name_Software` ON (`glpi_softwares`.`name` = `glpi_tickets_name_Software`.`id` ) WHERE `glpi_tickets`.`is_deleted` = 0 AND ( `glpi_tickets`.`status` IN ('1','2','3','4') AND ((`glpi_softwares`.`name` NOT LIKE '%Sage -%' OR `glpi_softwares`.`name` IS NULL) ) AND ( ((`glpi_entities`.`completename` NOT LIKE '%IT%' OR `glpi_entities`.`completename` IS NULL) )) ) GROUP BY `glpi_tickets`.`id` ORDER BY `id` "
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.2 ( => C:\inetpub\wwwroot\glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT xxxx 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.1.4 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, soap, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:104.0) Gecko/20100101 Firefox/104.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.28
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.4) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.28) is supported.
The log file has been created successfully.
Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated.
Write access to C:\inetpub\wwwroot\glpi/config has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated.
Write access to C:\inetpub\wwwroot\glpi/files has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\inetpub\wwwroot\glpi
GLPI_CONFIG_DIR: C:\inetpub\wwwroot\glpi/config
GLPI_VAR_DIR: C:\inetpub\wwwroot\glpi/files
GLPI_MARKETPLACE_DIR: C:\inetpub\wwwroot\glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\inetpub\wwwroot\glpi/files
GLPI_CACHE_DIR: C:\inetpub\wwwroot\glpi/files/_cache
GLPI_CRON_DIR: C:\inetpub\wwwroot\glpi/files/_cron
GLPI_DUMP_DIR: C:\inetpub\wwwroot\glpi/files/_dumps
GLPI_GRAPH_DIR: C:\inetpub\wwwroot\glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\inetpub\wwwroot\glpi/files/_locales
GLPI_LOCK_DIR: C:\inetpub\wwwroot\glpi/files/_lock
GLPI_LOG_DIR: C:\inetpub\wwwroot\glpi/files/_log
GLPI_PICTURE_DIR: C:\inetpub\wwwroot\glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\inetpub\wwwroot\glpi/files/_plugins
GLPI_RSS_DIR: C:\inetpub\wwwroot\glpi/files/_rss
GLPI_SESSION_DIR: C:\inetpub\wwwroot\glpi/files/_sessions
GLPI_TMP_DIR: C:\inetpub\wwwroot\glpi/files/_tmp
GLPI_UPLOAD_DIR: C:\inetpub\wwwroot\glpi/files/_uploads
GLPI_INVENTORY_DIR: C:\inetpub\wwwroot\glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\inetpub\wwwroot\glpi/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\inetpub\wwwroot\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\inetpub\wwwroot\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\wwwroot\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\inetpub\wwwroot\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\wwwroot\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\wwwroot\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\wwwroot\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\wwwroot\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\wwwroot\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\wwwroot\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\wwwroot\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\wwwroot\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\wwwroot\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\wwwroot\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\wwwroot\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\wwwroot\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\wwwroot\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\wwwroot\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\wwwroot\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\wwwroot\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\wwwroot\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\wwwroot\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\wwwroot\glpi\vendor\psr\cache\src)
league/csv in (C:\inetpub\wwwroot\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\wwwroot\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\wwwroot\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\wwwroot\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\wwwroot\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\wwwroot\glpi\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\wwwroot\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\inetpub\wwwroot\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\inetpub\wwwroot\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\wwwroot\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\wwwroot\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

 Use
		TLS: none

</details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertes                        Version: 1.10.4     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                 
		Install Method: Manual
	tag                  Name: Gestion des tags               Version: 2.9.2      State: Not installed                           
		Install Method: Manual
	mailbehaviours       Name: Mail Behaviours                Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	stab                 Name: Split Timeline Action Buttons  Version: 1.0.0      State: Not installed                           
		Install Method: Manual

</details><details><summary>Locales overrides</summary><pre></pre></details>

**Comment by cconard96** [comment]
Please include the full error from the `files/_log/sql-errors.log` file including the accompanying stack trace so we can know which code this bad query is from.

**Comment by stdglpi** [comment]
@cconard96 

Hello, 

I copy paste the logs bellow 👍 

`[2022-09-14 12:54:27] glpisqllog.WARNING: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 404
  *** MySQL query warnings:
  SQL: SELECT DISTINCT `glpi_tickets`.`id` AS id, 'USER XXX' AS currentuser,
                        `glpi_tickets`.`id` AS `ITEM_Ticket_2`,   `glpi_tickets`.`name` AS `ITEM_Ticket_1`,
                        `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`,
                        `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`content` AS `ITEM_Ticket_1_content`, `glpi_tickets`.`status` AS `ITEM_Ticket_1_status`, `glpi_entities`.`completename` AS `ITEM_Ticket_80`,  `glpi_tickets`.`status` AS `ITEM_Ticket_12`,  `glpi_tickets`.`priority` AS `ITEM_Ticket_3`,   GROUP_CONCAT(DISTINCT `glpi_users_af1042e23ce6565cfe58c6db91f84692`.`id` SEPARATOR '$$##$$')
                                       AS `ITEM_Ticket_4`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`users_id`, ' ',
                                                        `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`alternative_email`)
                                                        SEPARATOR '$$##$$') AS `ITEM_Ticket_4_2`, 
                            GROUP_CONCAT(DISTINCT `glpi_users_b1b92f6be5e70531688d870931e94a65`.`id` SEPARATOR '$$##$$')
                                       AS `ITEM_Ticket_5`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`users_id`, ' ',
                                                        `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`alternative_email`)
                                                        SEPARATOR '$$##$$') AS `ITEM_Ticket_5_2`, 
                           `glpi_tickets`.`date` AS `ITEM_Ticket_15`,  `glpi_tickets`.`date_mod` AS `ITEM_Ticket_19`,  `glpi_itilcategories`.`completename` AS `ITEM_Ticket_7`,  `glpi_tickets`.`type` AS `ITEM_Ticket_14`,  `glpi_tickets`.`internal_time_to_own` AS `ITEM_Ticket_186`,  `glpi_tickets`.`status` AS `ITEM_Ticket_186_status`,  GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_tickets`.`tickets_id_1`, '__NULL__'),
                                               '$#$',`glpi_tickets_tickets`.`id`) ORDER BY `glpi_tickets_tickets`.`id` SEPARATOR '$$##$$')
                              AS `ITEM_Ticket_40`,
                  
                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_tickets`.`tickets_id_2`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_tickets_tickets`.`id`)ORDER BY `glpi_tickets_tickets`.`id` SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_Ticket_40_tickets_id_2`,  GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`items_id`, '__NULL__'),
                                               '$#$',`glpi_items_tickets`.`id`) ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$')
                              AS `ITEM_Ticket_13`,
                  
                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`itemtype`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_items_tickets`.`id`)ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_Ticket_13_itemtype`,  GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_name_Software`.`name`, '$#$' ,
                                                        `glpi_tickets_name_Software`.`id`) ORDER BY `glpi_tickets_name_Software`.`id`
                                        SEPARATOR '$$##$$') AS `ITEM_Software_1`,
                           
                            IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_name_Software`.`id`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_tickets_name_Software`.`id`)ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_Software_1_id`,  IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_name_Software`.`content`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_tickets_name_Software`.`id`)ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_Software_1_content`,  IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets_name_Software`.`status`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_tickets_name_Software`.`id`)ORDER BY `glpi_tickets_name_Software`.`id` SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_Software_1_status` FROM `glpi_tickets`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_tickets`.`entities_id` = `glpi_entities`.`id`
                                              ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`tickets_id`
                                                  AND `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`type` = '1' )LEFT JOIN `glpi_users`  AS `glpi_users_af1042e23ce6565cfe58c6db91f84692`
                                          ON (`glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`users_id` = `glpi_users_af1042e23ce6565cfe58c6db91f84692`.`id`
                                              ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`tickets_id`
                                                  AND `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`type` = '2' )LEFT JOIN `glpi_users`  AS `glpi_users_b1b92f6be5e70531688d870931e94a65`
                                          ON (`glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`users_id` = `glpi_users_b1b92f6be5e70531688d870931e94a65`.`id`
                                              )LEFT JOIN `glpi_itilcategories` 
                                          ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id`
                                              ) LEFT JOIN `glpi_tickets_tickets` 
                                          ON ((`glpi_tickets`.`id`
                                                = `glpi_tickets_tickets`.`tickets_id_1`
                                               OR `glpi_tickets`.`id`
                                                 = `glpi_tickets_tickets`.`tickets_id_2`)
                                              ) LEFT JOIN `glpi_items_tickets` 
                                             ON (`glpi_tickets`.`id` = `glpi_items_tickets`.`tickets_id`
                                                 ) LEFT JOIN  `glpi_items_tickets` AS `glpi_items_tickets_Software`
                         ON (`glpi_items_tickets_Software`.`tickets_id` = `glpi_tickets`.`id`
                             AND `glpi_items_tickets_Software`.`itemtype` = 'Software'
                             ) LEFT JOIN  `glpi_softwares`
                         ON (`glpi_items_tickets_Software`.`items_id` = `glpi_softwares`.`id`
                             ) LEFT JOIN `glpi_tickets`  AS `glpi_tickets_name_Software`
                                          ON (`glpi_softwares`.`name` = `glpi_tickets_name_Software`.`id`
                                              ) WHERE  `glpi_tickets`.`is_deleted` = 0  AND (   `glpi_tickets`.`status` IN ('1','2','3','4')  AND ((`glpi_tickets_name_Software`.`name` NOT LIKE '%Sage -%'  OR `glpi_tickets_name_Software`.`name` IS NULL) ) ) GROUP BY `glpi_tickets`.`id` ORDER BY `id` 
  Warnings: 
1292: Truncated incorrect DOUBLE value: '3SKEY TOKEN'
1292: Truncated incorrect DOUBLE value: '3SKEY TOKEN'
  Backtrace :
  src\Search.php:1441                                
  src\SavedSearch.php:1270                           Search::constructData()
  src\SavedSearch.php:844                            SavedSearch->execute()
  src\SavedSearch.php:883                            SavedSearch->getMine()
  ajax\savedsearch.php:88                            SavedSearch->displayMine()
  {"user":"22@SRV-XXX","mem_usage":"0.009\", 3.49Mio)"} `

**Comment by stdglpi** [comment]
Hello, 

I close this issue, I did a search on the logs and I deleted the element that cause the issue in the logs...
Now it's working..

thank you
