### ISSUE TITLE
Contracts: Add an Internal Notice field

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#12620]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Current *Notice* field is not enough. Most organizations need two timings:
1. _Notice_, which is the official delay required by the supplier to renew the contract (by example 2 months);
1. _Internal Delay_, which is the time required by the organization to handle and prepare the renewal (hierarchy approval, validation process, etc.) (by example 3 weeks).

Currently, we have to merge both delays into the single *Notice*, but doing so 1) we lost the official delay, and 2) we have to round up delays (being unable to pick days but only months).

That's why I think adding a second *Notice* field (which could be name *Internal Notice*) would help to better manage contracts.

**Comment by cconard96** [comment]
Feature requests can be made on the UserEcho page. We try to keep just bug reports in GitHub issues.
https://glpi.userecho.com/

**Comment by mathieumd** [comment]
Done: https://glpi.userecho.com/fr/communities/1/topics/2107-contracts-add-an-internal-notice-field
