### ISSUE TITLE
PHP Notice (8): Undefined index: ... Ticket.php

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12630]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3-dev

### Bug description

PHP Notice (8): Undefined index: itilcategories_id in /var/www/html/glpi/src/Ticket.php at line 3910
PHP Notice (8): Undefined index: type in /var/www/html/glpi/src/Ticket.php at line 3935
PHP Notice (8): Undefined index: itilcategories_id in /var/www/html/glpi/src/Ticket.php at line 3936
PHP Notice (8): Undefined index: entities_id in /var/www/html/glpi/src/Ticket.php at line 3943
PHP Notice (8): Undefined index: _users_id_requester in /var/www/html/glpi/src/Ticket.php at line 3945

If I log in as a user - I don't see an error.

However, if I log in to the admin, run debug mode and change to user profile, then go to the ticket creation page, I see such warnings. 
When I change the type of notification - then the number of alerts decreases.

![image](https://user-images.githubusercontent.com/68922721/189670586-7f522f03-2a15-4ae1-912d-0fc251b6197a.png)

and type change:

![image](https://user-images.githubusercontent.com/68922721/189670685-f066299b-2cff-473a-958c-81d6b2f7aa88.png)

Even if I go back to the incident type, only these two are displayed.

### Relevant log output

php-errors.log
[2022-09-12 16:31:55] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: itilcategories_id in /var/www/html/glpi/src/Ticket.php at line 3910
  Backtrace :
  front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()

[2022-09-12 16:31:55] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: type in /var/www/html/glpi/src/Ticket.php at line 3935
  Backtrace :
  front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()

[2022-09-12 16:31:55] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: itilcategories_id in /var/www/html/glpi/src/Ticket.php at line 3936
  Backtrace :
  front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()

[2022-09-12 16:31:55] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: entities_id in /var/www/html/glpi/src/Ticket.php at line 3943
  Backtrace :
  front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()

[2022-09-12 16:31:55] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: _users_id_requester in /var/www/html/glpi/src/Ticket.php at line 3945
  Backtrace :
  front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()

### Page URL

front/helpdesk.public.php?create_ticket=1

### Steps To reproduce

1. Log in as an administrator.
2. Enable debug mode.
3. Change the profile to one with a simple interface set up.
4. Open the application form.

**Comment by cconard96** [comment]
Which commit are you testing on?
This issue should be fixed by #12473

**Comment by WebGregGit** [comment]
Yep - it works. 

Sorry. 
I am a bit confused about which version I have, and the system does not show it exactly. It would be nice to add the date on the nightly release, not just the -dev.

![image](https://user-images.githubusercontent.com/68922721/189686639-6c670a57-5f12-4ae7-8eaa-911a99913814.png)

Unless you can see this date somewhere and I missed it

**Comment by cconard96** [comment]
It used to show the git commit info if there was a `.git` folder present, but that wouldn't work for the nightly releases, and it seems broken on newer versions of git if the owner of the folder contents is different than the web server's user and is also not marked as a safe directory in the global git config.
