### ISSUE TITLE
Method Ticket::getTicketActor

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#1263]
I learn method Ticket::getTicketActor() and don't understand it behavior.
Test ticket:
![screen0](https://cloud.githubusercontent.com/assets/11641656/20113148/35c310a4-a600-11e6-8358-b03caa00e981.png)

My code:
```
$ticket_id = 1;
$ticket = new Ticket();
$ticket->getFromDB($ticket_id);
$act = $ticket->getTicketActors();
```
$act return array:
```
(
  [5] => 2 
  [2] => 1 
  [3] => 1 
  [4] => 1
)
```
users ids:
```
glpi => 2
normal => 5
post-only => 3
tech => 4
```
In ticket user "glpi" used as "requester" and "assign" actor.
But getTicketActors() method return it only as "requestor" actor.

I'm doing something wrong?
I understand that the returned array can not contain two identical keys. It might be worth change the return of this method?

**Comment by trasher** [comment]
Just tested with you code on the 9.2/bugfixes branch with "glpi" user set as requester and assigned:
```
array (
  2 => 
  array (
    0 => '1',
    1 => '2',
  )
)
```

So, this is now ok
