### ISSUE TITLE
Error on Rules -> bussines Rules for tickets

### ISSUE THREAD

**Issue by fabiofrances** [glpi-project/glpi#12631]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

I have a rule for assigning tickets to a group as images, but tickets up to version 10.0.1 were as new after the update to version 10.0.2 are being automatically assigned with the Status Processing Assigned

link to print to configuration
https://imgur.com/a/TJSp0p0

### Steps To reproduce

1. Menu Administration -> Rules
2. Bussiness Rules for Tickets

### Your GLPI setup information

GLPI 10.0.2 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_US

**Comment by cconard96** [comment]
It sounds like the expected behavior in 10.0.2. Your rule is assigning a group, so the status is changed automatically from New to Assigned.
