### ISSUE TITLE
Single search for "Characteristics - Title/Description",  "Follow-up/Tasks Description" and "Solution"

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12645]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

In "Assistance - Tickets" when you need to search everything on tickets you have to write the same word for each different field.

It could be more convenient to be an option for using the same search for every field instead of having to write the same thing multiple times.

### Steps To reproduce

1. Go to Assistance
2. Go to Tickets
3. Press on Rule
4. Select Description
5. Write
5. Select Rule
6. Select Title
7. Write
8. ..repeating the same for each referred field (Follow-up/Task Description, Solution) and then "Search"

**Comment by dxdemetriou** [comment]
My mistake, it's just searching the latest followup/reply with "Description". I think that if not possible everyone on each ticket, at least the initial description should be included.

**Comment by dxdemetriou** [comment]
Messed up, I'll cleanup and reopen

**Comment by cconard96** [comment]
Searching on every field even when it isn't showing would be extremely slow and memory intensive.
You could change which columns are shown for yourself, include all the fields you want to search, and use the "Items seen" criteria.

If you are looking for a single search option to search everything in the timeline, you may want to add that suggestion over on the suggestions site to be considered for a future version. We only track bugs on the GitHub.
https://glpi.userecho.com/

**Comment by dxdemetriou** [comment]
Perfect, I didn't knew that it works in this way, thanks.

![Screenshot_20220914_235647](https://user-images.githubusercontent.com/41939421/190261634-c6400477-4f63-4118-9293-82b3ef4588ed.jpg)
