### ISSUE TITLE
The Requester is not assigned on their created ticket when "Standard interface" is used

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12647]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When creating a ticket using the "Standard interface", even shown as Requester, on ticket creation is empty. This happens only o "Standard interface". In Simplified interface is ok.

### Steps To reproduce

1. Go to Assistance
2. Go to Tickets
3. Click on +Add
4. Create your ticket (which Requester is shown)
5. Press the +Add to create the ticket
6. The created ticket dows not include the Requester (it's empty)

**Comment by cedric-anne** [comment]
Hi,

Can you try to reproduce on GLPI 10.0.3 ?

**Comment by dxdemetriou** [comment]
Yes, I'm preparing ot now, thanks.

On 10.0.2 it happend only with some profiles in which it worked before, but with administrator profiles it's ok.

**Comment by dxdemetriou** [comment]
It seems that's fixed with GLPI 10.0.3. Thanks :)
