### ISSUE TITLE
Location rule assigning random number

### ISSUE THREAD

**Issue by willgl1** [glpi-project/glpi#12651]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

we have just noticed this issue so could be linked to new update 10.0.3 applied yesterday.

Locations are assigning numbers instead of actual Location.

I've tried the rules engine and it doesn't seem to have any issues.

Happy to get specific logs where needed.

![image](https://user-images.githubusercontent.com/107202756/190351520-2e6f73b2-ab19-45c3-8333-f59ce7ec0c93.png)

**Comment by CSGiacomini** [comment]
We updated to version 10.0.3 a couple of days ago and we are seeing the same issue.

**Comment by willgl1** [comment]
> We updated to version 10.0.3 a couple of days ago and we are seeing the same issue.

Thanks for confirming it's not something I have done within config haha! For now we have applied address manually so it is now a locked field. If you want a workaround I would suggest that.

**Comment by trasher** [comment]
Please try with latest nightly build, it should have been solved (search on existing issues/pr to get the reference, I do not have time for that).

**Comment by meijin4** [comment]
Experiencing the same issue, affecting random number in 10.0.3

**Comment by shinsen26** [comment]
Just got this issue today
3 new entry with the name = ID from another location

GLPI : 10.0.9
Inventory : 1.2.3
