### ISSUE TITLE
glpi:ldap:synchronize_users not move user in dutsbin

### ISSUE THREAD

**Issue by Dimitri281** [glpi-project/glpi#12669]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello,
i've found a bug present on glpi since 9.5.X when we exec this command line from console :

/usr/bin/php /var/www/html/glpi/bin/console glpi:ldap:synchronize_users -n -u -s 1 --no-plugins

all the user who as been remove from ldap / ad are not move to the dustbin of glpi appliance the sync doesn't work for remove,
i've try whith  -d, --deleted-user-strategy[=DELETED-USER-STRATEGY] argument on option 1, but same result,

![image](https://user-images.githubusercontent.com/84469067/190644946-1dea6ecb-936f-44e9-9ee2-6b75bbca56fa.png)

![image](https://user-images.githubusercontent.com/84469067/190645322-f50fa7a3-f04b-4564-b37d-b613b57426d1.png)

### Steps To reproduce

1. move/disable/remove an ldap / ad user in forest
2. try this comand with/without all the argument in shell `php /var/www/html/glpi/bin/console glpi:ldap:synchronize_users -n -u -s 1 -d 1 --no-plugins`
3. just constat the user is already still in local glpi user base.

### Anything else?

when we try to sync the user manualy from the glpi front it's work fine 👍 but not scriptable,

![image](https://user-images.githubusercontent.com/84469067/190646271-9098acb2-6890-4690-be56-9b9b98afbbac.png)

**Comment by Jean72cgi** [comment]
bonjour, je teste la console pour rendre inactif les utilisateurs supprimés sur ldap mais ça ne marche pas, il désactive presque tous les comptes Glpi ?
hello, i am testing the console to make deleted users inactive on ldap but it doesn't work, it disables almost all Glpi accounts?

bin/console glpi:ldap:synchronize_users --deleted-user-strategy=3 --ldap-server-id=1 -f (samaccountname=*) --no-interaction --quiet
