### ISSUE TITLE
Cached text disappears in ticket description if pressing submit before filling all required fields

### ISSUE THREAD

**Issue by willgl1** [glpi-project/glpi#12665]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

as above from 10.0.3 when submitting a new ticket if you forget to assign a category and press submit then your ticket description is lost.

Not sure if this is part of the new PHP suggestion to protect cookies over http?

### Steps To reproduce

1. write ticket description
2. press submit before filling a mandatory field
3. ticket description will be lost

**Comment by cconard96** [comment]
I confirmed the issue.

**Comment by cconard96** [comment]
Can you re-test with GLPI 10.0.5? I can no longer recreate the issue.

**Comment by willgl1** [comment]
Hi,

I have just upgraded and I still see the issue. 

1. Create a ticket
2. Enter a title
3. Enter a description
4. Leave Category blank
5. Press "Add"
6. Error shows to add a mandatory field "category" but title and description disappear.

Please try the above steps and see.

**Comment by willgl1** [comment]
![Screenshot 2022-11-07 093631](https://user-images.githubusercontent.com/107202756/200276994-9feb9e55-72ff-4162-a093-79cf39322ea1.png)

Above screenshot is error wiping out the title and description I had just typed out. We raise a lot of tickets on behalf of our staff and it's easier for us as admins with all fields to miss the Category field.

**Comment by blackxthink** [comment]
> Can you re-test with GLPI 10.0.5? I can no longer recreate the issue.

Just like willgl1, it's happening to us as well.
Glad to see this was added to 10.0.6, you guys are doing a great job.

**Comment by cedric-anne** [comment]
Fixed by #13292.
