### ISSUE TITLE
GLPI Agent - Multiple request for inventory

### ISSUE THREAD

**Issue by willgl1** [glpi-project/glpi#12666]
### Documentation

Yes, I read it

### Expected behavior

It would be useful to have a mass action to request inventory of agents. This would prove useful when rolling out new software.

### Alternatives you've considered

n/a

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by willgl1** [comment]
Thank you yes I meant a partial. I did mean to use RFE apologies.
