### ISSUE TITLE
API : request with malformed search criteria leads to SQL error

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1266]
Hi

Here is an example of malformed request 

/search/User?criteria[0][field]=134343&criteria[0][searchtype]=contains&criteria[0][value]=dsadasd

Notice the field ID is 134343 which does not exists in the search options of the itemtype User. The request fails with this answer 

HTTP 500 Internal Server Error
[
  "ERROR_SQL",
  "Unexpected SQL Error : Unknown column '' in 'where clause'"
]

The API should catch such attempt and return an HTTP 4xx error instead.

**Comment by btry** [comment]
See PR #1267

**Comment by trasher** [comment]
Fixed in #1267
