### ISSUE TITLE
Technician systematically added as requester at ticket creation

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#12674]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Since the GLPI 10.0.3 update, when creating a ticket from the standard interface, the technician who creates the ticket is systematically added as a requester in the same way as the designated requester.
The option of pre-selection as requester is not activated
![image](https://user-images.githubusercontent.com/78087722/190714554-13f94e73-149d-486a-956c-b1ba416b1f37.png)

### Steps To reproduce

Create a ticket from standard interface on behalf of an requester.
After creation, creator is added to requester.

**Comment by cconard96** [comment]
I cannot recreate the issue.

Please include your GLPI setup information.

**Comment by Tony710** [comment]
Hi @cconard96 
Please find

**Comment by Tony710** [comment]
Some additional tests: this issu only occurs when the behaviors plugin is active...

**Comment by cconard96** [comment]
It sounds like a configuration issue or a big with that plugin then. The plugin's GitHub can be found here:
https://github.com/yllen/behaviors
