### ISSUE TITLE
Read access for some items not working

### ISSUE THREAD

**Issue by EnLef** [glpi-project/glpi#12671]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When a user had only read access to computers (for example), the computer list is empty but when I check update right with read access, it's OK.

### Steps To reproduce

1. Go to Administration -> Profils -> Your profil.
2. Go to Assets panel and check only read right for computers.
3. Try to go in Computers section with a user restricted by this profil.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.3 ( => /var/www/odin)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux CALN-GLPI 5.10.0-15-amd64 #1 SMP Debian 5.10.120-1 (2022-06-09) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at odin.agglo-lisieux.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.33
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: admglpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/www/odin/files/_cache has been validated.
Write access to /var/www/odin/config has been validated.
Write access to /var/www/odin/files/_cron has been validated.
Write access to /var/www/odin/files has been validated.
Write access to /var/www/odin/files/_dumps has been validated.
Write access to /var/www/odin/files/_graphs has been validated.
Write access to /var/www/odin/files/_lock has been validated.
Write access to /var/www/odin/files/_pictures has been validated.
Write access to /var/www/odin/files/_plugins has been validated.
Write access to /var/www/odin/files/_rss has been validated.
Write access to /var/www/odin/files/_sessions has been validated.
Write access to /var/www/odin/files/_tmp has been validated.
Write access to /var/www/odin/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/odin/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/odin
GLPI_CONFIG_DIR: /var/www/odin/config
GLPI_VAR_DIR: /var/www/odin/files
GLPI_MARKETPLACE_DIR: /var/www/odin/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/odin/files
GLPI_CACHE_DIR: /var/www/odin/files/_cache
GLPI_CRON_DIR: /var/www/odin/files/_cron
GLPI_DUMP_DIR: /var/www/odin/files/_dumps
GLPI_GRAPH_DIR: /var/www/odin/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/odin/files/_locales
GLPI_LOCK_DIR: /var/www/odin/files/_lock
GLPI_LOG_DIR: /var/www/odin/files/_log
GLPI_PICTURE_DIR: /var/www/odin/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/odin/files/_plugins
GLPI_RSS_DIR: /var/www/odin/files/_rss
GLPI_SESSION_DIR: /var/www/odin/files/_sessions
GLPI_TMP_DIR: /var/www/odin/files/_tmp
GLPI_UPLOAD_DIR: /var/www/odin/files/_uploads
GLPI_INVENTORY_DIR: /var/www/odin/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/odin/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/odin/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/odin/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/odin/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/odin/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/odin/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/odin/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/odin/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/odin/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/odin/vendor/sabre/http/lib)
sabre/uri in (/var/www/odin/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/odin/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/odin/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/odin/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/odin/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/odin/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/odin/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/odin/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/odin/vendor/symfony/console)
scssphp/scssphp in (/var/www/odin/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/odin/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/odin/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/odin/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/odin/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/odin/vendor/ramsey/uuid/src)
psr/log in (/var/www/odin/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/odin/vendor/psr/simple-cache/src)
psr/cache in (/var/www/odin/vendor/psr/cache/src)
league/csv in (/var/www/odin/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/odin/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/odin/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/odin/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/odin/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/odin/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/odin/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/odin/vendor/symfony/cache)
html2text/html2text in (/var/www/odin/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/odin/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/odin/vendor/symfony/dom-crawler)
twig/twig in (/var/www/odin/vendor/twig/twig/src)
twig/string-extra in (/var/www/odin/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/odin/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/odin/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/odin/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

<details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (anonymous@agglolisieux-fr01c.mail.protection.outlook.com)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.17.3     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportements                  Version: 2.7.1      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.0     State: Enabled                                 
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
Unable to recreate the issue.

Please provide the requested log output. Specifically, the `files/_log/access-errors.log` file may have relevant info.

**Comment by EnLef** [comment]
Hi, This is my log file content :
2022-09-28 20:13:53 [436@CALN-GLPI]
User ID: 436 tried to access or perform an action on /front/profile.form.php?id=5 with insufficient rights. Additional information: User is missing the 1 (READ) right for profile
        Stack Trace:
                /var/www/odin/src/Session.php:984 displayRightError()
                /var/www/odin/front/profile.form.php:38 checkRight()
2022-09-28 20:37:55 [436@CALN-GLPI]
User ID: 436 tried to access or perform an action on /front/profile.form.php?id=5 with insufficient rights. Additional information: User is missing the 1 (READ) right for profile
        Stack Trace:
                /var/www/odin/src/Session.php:984 displayRightError()
                /var/www/odin/front/profile.form.php:38 checkRight()
