### ISSUE TITLE
Blank page on GLPI Login

### ISSUE THREAD

**Issue by BboivinFOCSS** [glpi-project/glpi#12686]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When we try to log in GLPI, no fields appears on login page.
Already logged in user access works perfectly

### Relevant log output

```shell
php-error.log
[2022-09-19 11:51:08] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Toolbox::unclean_html_cross_side_scripting_deep() in /var/www/glpi/index.php at line 111
```

### Page URL

https://support.lafocss.org

### Your GLPI setup information

<html>
<body>

Informations sur le système, l'installation et la configuration
--
 
GLPI 10.0.3 ( => /var/www/glpi) Installation mode: TARBALL Current language:fr_FR

Operating system: Linux HQ-GLPI-01 4.19.0-20-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 PHP 8.1.10 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at support.lafocss.org Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Server Software: Debian 10 	Server Version: 10.3.36-MariaDB-0+deb10u1 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version (8.1.10) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (10.3.36) is supported. The log file has been created successfully. Write access to /var/www/glpi/files/_cache has been validated. Write access to /var/www/glpi/config has been validated. Write access to /var/www/glpi/files/_cron has been validated. Write access to /var/www/glpi/files has been validated. Write access to /var/www/glpi/files/_dumps has been validated. Write access to /var/www/glpi/files/_graphs has been validated. Write access to /var/www/glpi/files/_lock has been validated. Write access to /var/www/glpi/files/_pictures has been validated. Write access to /var/www/glpi/files/_plugins has been validated. Write access to /var/www/glpi/files/_rss has been validated. Write access to /var/www/glpi/files/_sessions has been validated. Write access to /var/www/glpi/files/_tmp has been validated. Write access to /var/www/glpi/files/_uploads has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration. Sessions configuration is secured. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/glpi/marketplace has been validated. Access to timezone database (mysql) is not allowed.

GLPI_ROOT: /var/www/glpi GLPI_CONFIG_DIR: /var/www/glpi/config GLPI_VAR_DIR: /var/www/glpi/files GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: /var/www/glpi/files GLPI_CACHE_DIR: /var/www/glpi/files/_cache GLPI_CRON_DIR: /var/www/glpi/files/_cron GLPI_DUMP_DIR: /var/www/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales GLPI_LOCK_DIR: /var/www/glpi/files/_lock GLPI_LOG_DIR: /var/www/glpi/files/_log GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins GLPI_RSS_DIR: /var/www/glpi/files/_rss GLPI_SESSION_DIR: /var/www/glpi/files/_sessions GLPI_TMP_DIR: /var/www/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/glpi/locales GLPI_VERSION: 10.0.3 GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831 GLPI_MARKETPLACE_PRERELEASES:  GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.3.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src) psr/cache in (/var/www/glpi/vendor/psr/cache/src) league/csv in (/var/www/glpi/vendor/league/csv/src) mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src) symfony/cache in (/var/www/glpi/vendor/symfony/cache) html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src) symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector) symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler) twig/twig in (/var/www/glpi/vendor/twig/twig/src) twig/string-extra in (/var/www/glpi/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 not found symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82) phpCas version 1.3.6 in (/usr/share/php/CAS/source)

news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                  		Install Method: Marketplace 	fields               Name: Champs supplémentaires         Version: 1.17.3     State: Enabled                                  		Install Method: Marketplace 	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                  		Install Method: Marketplace 	escalade             Name: Escalades                      Version: 2.8.0      State: Enabled                                  		Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                  		Install Method: Marketplace 	fusioninventory      Name: FusionInventory                Version: 10.0.1+1.0 State: Enabled                                  		Install Method: Manual 	order                Name: Gestion des commandes          Version: 2.9.0      State: Enabled                                  		Install Method: Marketplace 	manufacturersimports Name: Imports fabricants             Version: 3.0.2      State: Enabled                                  		Install Method: Marketplace 	mreporting           Name: Plus de rapports               Version: 1.8.1      State: Enabled                                  		Install Method: Marketplace

</body>
</html>

**Comment by cedric-anne** [comment]
Hi,

There is no call to `Toolbox::unclean_html_cross_side_scripting_deep()` in mentionned file. Did you patched GLPI, or did you use an alternative "distribution" ?

**Comment by BboivinFOCSS** [comment]
Hi,

Not that i remember. Before upgrade from 9.5 i used a plugin that modify css code on login page.

Should i restore a fresh version of the file ?

**Comment by cedric-anne** [comment]
> Before upgrade from 9.5 i used a plugin that modify css code on login page.

What is this plugin ?

**Comment by BboivinFOCSS** [comment]
GLPI Modifications
https://github.com/stdonato/glpi-modifications

**Comment by BboivinFOCSS** [comment]
Problem solved !

I replaced index.php file by a new one from github repository
