### ISSUE TITLE
Update KB article target with just read permissions

### ISSUE THREAD

**Issue by DonutsNL** [glpi-project/glpi#12691]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.2  - Installation mode: TARBALL

### Bug description

Users with read permissions are able to update the KB targets on an article and have the edit tab available to them (without save button).  Using impersonation, not tested when logging on as actual user. 

### Page URL

/front/knowbaseitem.form.php?id={some_id}

### Steps To reproduce

Create a profile with KB read permissions (nothing else)
Assign the profile to a newly created user;
use the impersonate function to become the created user;
Browse to any KB article targeted to the entity to which the user has permissions;
Add any target and update KB.

### Your GLPI setup information

Tarball install on linux version described above.
Root entity > entity for activity (containing all data);

**Comment by cconard96** [comment]
I cannot recreate the issue. Please test with the latest bugfix version of GLPI 10.0 (10.0.3). If the issue persists, please share the type of profile (simplified or standard) and all options checked under the profiles Tool tab > Knowledgebase.

Please include the requested GLPI setup information as well. This is found in Setup > General > System Tab. There is a button that you can click to copy the full information to the clipboard to paste here in a clean format.

**Comment by DonutsNL** [comment]
Found an issue with a different plugin causing this. We fixed it and it works as intended.
