### ISSUE TITLE
Post-only user can access other users tickers by change ticket's id in the url

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#127]
This problem affects GLPi 0.85.x : http://forum.glpi-project.org/viewtopic.php?pid=280464 

GLPi 0.90 is not affected

**Comment by thibvdb** [comment]
This problem affects every item types with an ID: users, computers, monitors, software, network, devices...

**Comment by thibvdb** [comment]
When can we expect the fix ? Because this is a big security failure. Thank you.

**Comment by orthagh** [comment]
The commits for 0.90 who solved this issue : 
03fdabb2833859ac0af96ca5e68153256e557ca4
b2c0655cdae6f722435249fb1737e60308366cb8
572b9e78ad926d66b9737f7bf43c22a0a242e8b1

**Comment by orthagh** [comment]
fixed in (cherry-picked) :
 e93a1c7
 159f125
 1c0f560
 50b562d
