### ISSUE TITLE
Files of `glpi-project/inventory_format` in release artifacts

### ISSUE THREAD

**Issue by AKorezin** [glpi-project/glpi#12701]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

GLPI uses `glpi-project/inventory_format` as a runtime dependency.

I noticed that some files from `vendor/glpi-project/inventory_format` were not removed when building release artifact.

I'm not sure which of the files are necessary for release, but there are some dupes.
For example
```
# md5sum source_files/*
f2bea08e12c82224370f83550de56902  source_files/oui.txt
957d2650dbb070e0a5d61fd15c8ee584  source_files/pci.ids
f5ebd364fbceca59ef2909c2ac9017ae  source_files/smi-numbers-5.csv
ac556fa79bcc2f8316ef7ee8a9756ffc  source_files/usb.ids
# md5sum data/*
f5ebd364fbceca59ef2909c2ac9017ae  data/iftype.csv
aa14523f67a585882a0b450cda9ff676  data/iftype.json
ff22f1c3b56f05c34a1b38d7a74e410a  data/ouis.json
f2bea08e12c82224370f83550de56902  data/oui.txt
9b4514275868a952da39c406cd348735  data/pciid.json
957d2650dbb070e0a5d61fd15c8ee584  data/pci.ids
07c2866a912f16b83a91e6927e5b6768  data/README.md
f980c6adf3eea4ed343a8b56e2e80dcc  data/usbid.json
ac556fa79bcc2f8316ef7ee8a9756ffc  data/usb.ids
```
Also directories `examples` and `tests`.

Probably they should be removed somewhere here
https://github.com/glpi-project/glpi/blob/dcbda281565de11a97322d0f0ae975e36bdd1e04/tools/build_glpi.sh#L76-L121

### Relevant log output

```shell
Not applicable
```

### Page URL

Not applicable

### Steps To reproduce

1. Get release `10.0.3`.
2. Untar it.
3. Open dir `vendor/glpi-project/inventory_format`.
4. Observe excess files and directories.

### Your GLPI setup information

Not applicable

**Comment by cedric-anne** [comment]
This has been fixed in https://github.com/glpi-project/inventory_format/pull/80 and will be effective in next library release.

**Comment by AKorezin** [comment]
@cedric-anne could you check if other directories are necessary in GLPI release?
```
4.0K	CHANGELOG.md
4.0K	composer.json
4.0K	LICENSE
4.0K	README.md
16K	bin
36K	original.md
68K	lib
84K	inventory.schema.json
460K	tests
3.5M	examples
6.2M	source_files
9.3M	data
```
As I already said `data` directory has the same files as in `source_files` directory.
Are `examples` and `bin` needed in the GLPI release?
Maybe only `*.json` files from `data` directory are required?

**Comment by cedric-anne** [comment]
Indeed, `source_files` and `examples` are usefull in dev environment, but not in the release archive.

**Comment by trasher** [comment]
`bin` may be required to update generated files.
`source_files` is not exactly the same as `data`; it's an non updated version used in tests (because remote may be non reachable (so, only `data` must be kept)
`examples` can be removed
