### ISSUE TITLE
Reword "responsible" to "supervisor"

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#12707]
```suggestion
            Session::addMessageAfterRedirect(sprintf(__('%1$s does not have a supervisor'), $primaryRequester->getFriendlyName()));
```
Sorry if I wasn't clear, but "Supervisor" is the word that made the most sense to me. In the user form currently, it is labelled "Responsible", but that is an adjective and doesn't make any sense as a label in English.

_Originally posted by @cconard96 in https://github.com/glpi-project/glpi/pull/12504#discussion_r957584109_

**Comment by cconard96** [comment]
Done in #12847
