### ISSUE TITLE
Icon Assest does not appear

### ISSUE THREAD

**Issue by fabiofrances** [glpi-project/glpi#12700]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

Assests icon does not appear with the super-admin profile but with the other profiles appears.
PS.:  It's not necessary a bug.

**Comment by cconard96** [comment]
This may be fixed by #12662. It would be included with GLPI 10.0.4.

**Comment by fabiofrances** [comment]
Great. Thanks.
