### ISSUE TITLE
Replace Assigned actors

### ISSUE THREAD

**Issue by michaelNFF** [glpi-project/glpi#12709]
> I've noticed the same behavior yesterday on GLPI 9.5 so It may be an old bug not related to @cedric-anne changes.
> Still would be nice to fix it thought ;)

`assign` only act on actors being added by current ticket update. If actors were already existing before the update process, they are not remove. We agreed, with @orthagh, to not change this behaviour for now.

_Originally posted by @cedric-anne in https://github.com/glpi-project/glpi/issues/11957#issuecomment-1165240861_

In 10.0.3 version, do you plan to change this process and remove old actors if existing them  ?

**Comment by cedric-anne** [comment]
Hi,

We will not do such changes on a bugfix version, as it may have many side effects on existing rules.

Regards

**Comment by michaelNFF** [comment]
Ok could you propose me an workaround to change assigned actor in terms of ticket category?
or juste remove old assigned actor?

Regards.
