### ISSUE TITLE
Can't create a ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#12715]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Github of this day

### Bug description

Super-admin with all rights
Can't create a ticket because of missing right

In CommonDBTM 6386
if (!$item->can($id, READ)) {
=> READ right doesn't exist for a ticket

### Relevant log output

```shell
User ID: 8 tried to access or perform an action on /git10/front/ticket.form.php?id=395 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
	Stack Trace:
		/home/yllen/glpi10/src/CommonDBTM.php:6297 displayRightError()
		/home/yllen/glpi10/src/CommonDBTM.php:6387 displayAccessDeniedPage()
		/home/yllen/glpi10/front/ticket.form.php:259 displayFullPageForItem()
```

**Comment by yllen** [comment]
@orthagh can you close this issue if OK for you (sorry for the PR, done to fast)

**Comment by orthagh** [comment]
I guess it's an error, but you didn't send a pr but a direct commit on 10.0/bugfixes branch.
For the bug, are you sure of the scenario, i can create tickets without any issue currently ?

**Comment by yllen** [comment]
You have this if a mandatory field exist with Behaviors plugin

**Comment by yllen** [comment]
@orthagh laisses tomber je vais changer dans mon plugin.
Mais c'est pénible qu'à chaque version mineure de GLPI il faille revoir le code des plugins

**Comment by orthagh** [comment]
>Mais c'est pénible qu'à chaque version mineure de GLPI il faille revoir le code des plugins

non mais si il y a une quelconque régression, il n'y a aucun problème à la corriger.
L'api core est censée être stable sur les versions mineures.
Par contre, on est pas infaillible et des bugs peuvent être introduits par mégarde.
Tu ne devrais pas avoir à changer quelque chose pour la 10.0.3.

Pour revenir au sujet initial, on n'a pour le moment pas saisi.
Donc si tu veux bien expliquer, on n'aura aucun problème à trouver une solution.
