### ISSUE TITLE
In Planning there is no the Save button

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12716]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

After selecting the period on Planning for creating anb event, there is no the save button for saving even as Super-Admin

![image](https://user-images.githubusercontent.com/41939421/191501322-6e81a8e9-e105-4f38-aff4-74ddec7decb9.png)

### Relevant log output

```shell
php-errors.log
`
[2022-09-21 15:20:17] glpiphplog.WARNING:   *** PHP Warning (2): strlen() expects parameter 1 to be string, array given in /var/www/html/glpi/src/PlanningExternalEvent.php at line 160
  Backtrace :
  src/Planning.php:1493                              PlanningExternalEvent->showForm()
  src/Planning.php:1432                              Planning::showAddEventSubForm()
  ajax/planning.php:95                               Planning::showAddEventForm()
  
[2022-09-21 15:20:17] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to PlanningExternalEvent::showRepetitionForm() must be of the type string, array given, called in /var/www/html/glpi/src/PlanningExternalEvent.php on line 338 in /var/www/html/glpi/src/Features/PlanningEvent.php at line 724
  Backtrace :
  src/PlanningExternalEvent.php:338                  PlanningExternalEvent::showRepetitionForm()
  src/Planning.php:1493                              PlanningExternalEvent->showForm()
  src/Planning.php:1432                              Planning::showAddEventSubForm()
  ajax/planning.php:95                               Planning::showAddEventForm()
````
```


### Page URL

_No response_

### Steps To reproduce

1. Go to Assistance
2. Go to Planning
3. Choose either month/week/day
4. Select or drag for selection
5. The Add button is missing

### Your GLPI setup information

Information about system installation and configuration
````
GLPI 10.0.3 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB
````
Server
````
 
Operating system: Linux glpi-new 4.18.0-372.13.1.el8_6.x86_64 #1 SMP Wed Jun 29 17:21:09 UTC 2022 x86_64
PHP 7.4.30 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt,
	mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, shmop, soap, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="60M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.37 (rocky) OpenSSL/1.1.1k ()
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 29, Revision 11ad961
	Server Version: 5.7.26-29-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiUser@10.42.29.9/glpi-new
	Host info: 10.42.29.9 via TCP/IP
	
PHP version (7.4.30) is supported.PHP version (7.4.30) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.26) is supported.Database engine version (5.7.26) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated. Write access to /etc/glpi/ has been validated. Write access to /var/lib/glpi/_cron has been validated. Write access to /var/lib/glpi has been validated. Write access to /var/lib/glpi/_dumps has been validated. Write access to /var/lib/glpi/_graphs has been validated. Write access to /var/lib/glpi/_lock has been validated. Write access to /var/lib/glpi/_pictures has been validated. Write access to /var/lib/glpi/_plugins has been validated. Write access to /var/lib/glpi/_rss has been validated. Write access to /var/lib/glpi/_sessions has been validated. Write access to /var/lib/glpi/_tmp has been validated. Write access to /var/lib/glpi/_uploads has been validated.Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
SELinux configuration is OK.SELinux configuration is OK.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.
````


### Anything else?

_No response_

**Comment by cedric-anne** [comment]
Hi,

Issue duplicates #12676 and is fixed by #12678, so I close it.
