### ISSUE TITLE
Content lost on ticket creation when a mandatory field is not filled

### ISSUE THREAD

**Issue by Edzilla2000** [glpi-project/glpi#12713]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When creating a new ticket, we have made some filed mandatory.
Previously, when you created a ticket in 9.5.x, if there was a mandatory field not filled in and you tried to create the ticket, there would be a popup telling you about the missing information, and you would have the opportunity to fill it in.

Now, in 10.0.3, in the same circumstances, when clicking the add button, we still get the popup about the filed not being filled in, but we lose all the information already entered.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.3 ( => /srv/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux celeste 5.4.0-126-generic #142-Ubuntu SMP Fri Aug 26 12:12:57 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, soap, sockets,
	sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at sd.limelogic.be Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Server Software: Debian 10
	Server Version: 10.3.36-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiprod@undostres.lpl.grp/glpiprod
	Host info: undostres.lpl.grp via TCP/IP
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.36) is supported.
The log file has been created successfully.
Write access to /srv/glpi/files/_cache has been validated.
Write access to /srv/glpi/config has been validated.
Write access to /srv/glpi/files/_cron has been validated.
Write access to /srv/glpi/files has been validated.
Write access to /srv/glpi/files/_dumps has been validated.
Write access to /srv/glpi/files/_graphs has been validated.
Write access to /srv/glpi/files/_lock has been validated.
Write access to /srv/glpi/files/_pictures has been validated.
Write access to /srv/glpi/files/_plugins has been validated.
Write access to /srv/glpi/files/_rss has been validated.
Write access to /srv/glpi/files/_sessions has been validated.
Write access to /srv/glpi/files/_tmp has been validated.
Write access to /srv/glpi/files/_uploads has been validated.
Web access to files directory is protected
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /srv/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /srv/glpi
GLPI_CONFIG_DIR: /srv/glpi/config
GLPI_VAR_DIR: /srv/glpi/files
GLPI_MARKETPLACE_DIR: /srv/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /srv/glpi/files
GLPI_CACHE_DIR: /srv/glpi/files/_cache
GLPI_CRON_DIR: /srv/glpi/files/_cron
GLPI_DUMP_DIR: /srv/glpi/files/_dumps
GLPI_GRAPH_DIR: /srv/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /srv/glpi/files/_locales
GLPI_LOCK_DIR: /srv/glpi/files/_lock
GLPI_LOG_DIR: /srv/glpi/files/_log
GLPI_PICTURE_DIR: /srv/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /srv/glpi/files/_plugins
GLPI_RSS_DIR: /srv/glpi/files/_rss
GLPI_SESSION_DIR: /srv/glpi/files/_sessions
GLPI_TMP_DIR: /srv/glpi/files/_tmp
GLPI_UPLOAD_DIR: /srv/glpi/files/_uploads
GLPI_INVENTORY_DIR: /srv/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /srv/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/srv/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/srv/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/srv/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/srv/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/srv/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/srv/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/srv/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/srv/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/srv/glpi/vendor/sabre/http/lib)
sabre/uri in (/srv/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/srv/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/srv/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/srv/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/srv/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/srv/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/srv/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/srv/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/srv/glpi/vendor/symfony/console)
scssphp/scssphp in (/srv/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/srv/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/srv/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/srv/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/srv/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/srv/glpi/vendor/ramsey/uuid/src)
psr/log in (/srv/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/srv/glpi/vendor/psr/simple-cache/src)
psr/cache in (/srv/glpi/vendor/psr/cache/src)
league/csv in (/srv/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/srv/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/srv/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/srv/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/srv/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/srv/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/srv/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/srv/glpi/vendor/symfony/cache)
html2text/html2text in (/srv/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/srv/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/srv/glpi/vendor/symfony/dom-crawler)
twig/twig in (/srv/glpi/vendor/twig/twig/src)
twig/string-extra in (/srv/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/srv/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/srv/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/srv/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@10.74.1.15)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace

</details><details><summary>Locales overrides</summary><pre></pre></details>

**Comment by cedric-anne** [comment]
Hi,

Issue duplicates #12665, so I close it.
