### ISSUE TITLE
REST API : multiple UPDATE or DELETE with multi-status may produce bad response

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1271]
Hi

If I UPDATE or DELETE multiple items and some of them fails I get the following responses : 

HTTP 207 Multi-Status
```
[
  "ERROR_GLPI_PARTIAL_UPDATE",
  [
    {
      "2": null
    },
    {
      "3": true
    }
  ]
]
```

HTTP 207 Multi-Status
```
[
  "ERROR_GLPI_PARTIAL_DELETE",
  [
    {
      "2": null
    },
    {
      "3": true
    }
  ]
]
```

In the documentation, UPDATE multiple items shows a fully successful case. However the multiple DELETE example shows a multi-status case.

Currently, the DELETE does not behaves as the documentation says (probably a regression). If UPDATE should return false for failed updates, then it does not behaves as expected.

Tested with the up to date 9.1/bugfixes branch

**Comment by btry** [comment]
The source code currently suggest we might return the reason of failure for each item the same way a single UDATE or DELETE would do.

This seems a good idea, but would break the backward compatibility.

Any thought about that ?

**Comment by btry** [comment]
Example of solution from @orthagh for messages : 
```json
[{"16":true, "message": "blabla"},{"17":false, "message": "blabla"}]
```

**Comment by btry** [comment]
All done in #1273; closing.

**Comment by ddurieux** [comment]
In the stardard API REST, only the multiple item can be managed with POST
