### ISSUE TITLE
Unable to add IP address

### ISSUE THREAD

**Issue by gitdevmod** [glpi-project/glpi#12725]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When I add an IPv4 address to a printer when submitting it does not save IPv4

### Relevant log output

```shell
sql-errors.log

[2022-09-22 09:34:36] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipaddresses` (`itemtype`, `items_id`, `name`, `mainitemtype`, `mainitems_id`, `version`, `binary_0`, `binary_1`, `binary_2`, `binary_3`, `entities_id`) VALUES ('NetworkName', '14895', '192.168.1.1', 'Printer', '636', '4', '0', '0', '65535', '-1062731519', '0')
  Error: Out of range value for column 'binary_3' at row 1
  Backtrace :
  src/DBmysql.php:1312
  src/CommonDBTM.php:716                             DBmysql->insert()
  src/CommonDBTM.php:1321                            CommonDBTM->addToDB()
  src/NetworkName.php:286                            CommonDBTM->add()
  src/NetworkName.php:314                            NetworkName->post_workOnItem()
  src/CommonDBTM.php:1716                            NetworkName->post_updateItem()
  src/NetworkPort.php:437                            CommonDBTM->update()
  src/NetworkPort.php:304                            NetworkPort->updateDependencies()
  src/CommonDBTM.php:1716                            NetworkPort->post_updateItem()
  front/networkport.form.php:123                     CommonDBTM->update()
  {"user":"13@srv-glpi"}
```

### Steps To reproduce

1. Configure printer
2. Add IPv4 address
3. Save

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.3 (/glpi => /usr/share/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux srv-glpi 5.10.0-18-686-pae #1 SMP Debian 5.10.140-1 (2022-09-02) i686
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at srv-glpi Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36 Edg/105.0.1343.42
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi//_cache has been validated.
Write access to /usr/share/glpi/config has been validated.
Write access to /var/lib/glpi//_cron has been validated.
Write access to /var/lib/glpi/ has been validated.
Write access to /var/lib/glpi//_dumps has been validated.
Write access to /var/lib/glpi//_graphs has been validated.
Write access to /var/lib/glpi//_lock has been validated.
Write access to /var/lib/glpi//_pictures has been validated.
Write access to /var/lib/glpi//_plugins has been validated.
Write access to /var/lib/glpi//_rss has been validated.
Write access to /var/lib/glpi//_sessions has been validated.
Write access to /var/lib/glpi//_tmp has been validated.
Write access to /var/lib/glpi//_uploads has been validated.
Web access to files directory is protected
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.

PHP Warning (2): mkdir(): Permission denied in /usr/share/glpi/src/Toolbox.php at line 1168
The directory could not be created in /usr/share/glpi/marketplace.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /usr/share/glpi
GLPI_VAR_DIR: /var/lib/glpi/
GLPI_DOC_DIR: /var/lib/glpi/
GLPI_CRON_DIR: /var/lib/glpi//_cron
GLPI_DUMP_DIR: /var/lib/glpi//_dumps
GLPI_GRAPH_DIR: /var/lib/glpi//_graphs
GLPI_LOCK_DIR: /var/lib/glpi//_lock
GLPI_PICTURE_DIR: /var/lib/glpi//_pictures
GLPI_PLUGIN_DOC_DIR: /var/lib/glpi//_plugins
GLPI_RSS_DIR: /var/lib/glpi//_rss
GLPI_SESSION_DIR: /var/lib/glpi//_sessions
GLPI_TMP_DIR: /var/lib/glpi//_tmp
GLPI_UPLOAD_DIR: /var/lib/glpi//_uploads
GLPI_CACHE_DIR: /var/lib/glpi//_cache
GLPI_LOG_DIR: /var/log/glpi/
GLPI_CONFIG_DIR: /usr/share/glpi/config
GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 

PHP Notice (8): Array to string conversion in /usr/share/glpi/src/Config.php at line 2073
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_LOCAL_I18N_DIR: /var/lib/glpi//_locales
GLPI_INVENTORY_DIR: /var/lib/glpi//_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /usr/share/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/share/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/usr/share/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 

</details><details><summary>Plugins list</summary><pre> 
	shellcommands        Name: Commandes Shell                Version: 4.0.1      State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.1+1.0 State: To update                               
		Install Method: Manual
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
I'm not able to reproduce with provided information

**Comment by trasher** [comment]
Seems like you're using a 32bits operating system; it may be the cause.
I only have 64bits OS on my side, I cannot reproduce, nor fix.

**Comment by gitdevmod** [comment]
Ok, I think I found origin. If name field is not empty I can save IPv4

**Comment by gitdevmod** [comment]
Sorry, with a name it does not solve issue. I still can not save IPv4 address on printer port

**Comment by gitdevmod** [comment]
What does the field binary_3 correspond to?

**Comment by gitdevmod** [comment]
After upgrade I've run php bin/console glpi:migration:unsigned_keys but there is still one ocvsinventory table not updated 
```
php bin/console glpi:migration:unsigned_keys
Trouvé 1 colonne(s) de clé principale ou étrangère utilisant des entiers signés
Voulez-vous continuer ? [Yes/no]Yes
La migration de la colonne "glpi_plugin_ocsinventoryng_networkports.items_devicenetworkcards_id" ne peut pas être faite car elle contient des valeurs négatives.
 1/1 [============================] 100%
Des erreurs se sont produites pendant la migration.
Vous devriez essayer de mettre à jour les plugins suivants dans leur dernière version et relancer la commande à nouveau : OCS Inventory NG.
```

**Comment by gitdevmod** [comment]
Indeed, do you think it's related with my issue ?

**Comment by cedric-anne** [comment]
No, I think your issue is related to the fact that your are using a GLPI server using a 32bit OS.

All active GLPI developpers are using 64bit OS now, so detecting, analyzing and fixing this kind of issues may be tricky.

**Comment by gitdevmod** [comment]
Ok I understand. I'll upgrade to Debian 64bit last release

**Comment by cedric-anne** [comment]
For reference:
- https://www.php.net/manual/en/function.ip2long.php#refsect1-function.ip2long-notes
- https://www.php.net/manual/en/function.long2ip.php#refsect1-function.long2ip-notes

**Comment by gitdevmod** [comment]
Ok, now I understand why somes addresses works :)
It's was working with 9.5.x. I'm building a new 64 bit server.

**Comment by gitdevmod** [comment]
I restored database on a new Debian 64 bit server and I can now change IPv4 address
