### ISSUE TITLE
Automatic Actions - Cleanoldagents doesn't change status (field states_id) and just lock field

### ISSUE THREAD

**Issue by AndiFo** [glpi-project/glpi#12738]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Inventory - Agent cleanup is customized to "Action: Change the status" and "Change the status" is correct selected.

Automatic action "Cleanoldagents" just lock the field status and doesn't change the field to correct value.

If I change the action to "clean agents" then the assignment is deleted as expected.

**Comment by AndiFo** [comment]
I have changed file src\Agent.php line 731 from 
'states_id' => $config['agents_status'] to 
'states_id' => $config['stale_agents_status'] 

and status will be changed. But the field is now also locked! When the agent logs in again, the field is no longer changed to default status.

In my opinion the field should not be locked automatically.

**Comment by slannoy** [comment]
Hi,
as far as I understood the state is now modified as expected with this fix but does the state field remains locked?
I don't understand why the filed should be locked after the state changes.
Thanks
-seb

**Comment by AndiFo** [comment]
That was exactly one of the errors, at first the status was not changed at all (although set differently). Then the status was changed, but the field was locked afterwards. The agent could not change this status again (which I think it should, e.g. from "Active" to "Offline"). 

But there is an exception: When I manually changed the status in the inventory itself, then I didn't want a status change anymore. You then have to unlock the field that the agent is allowed to do that again.

I hope this explanation helps you.

**Comment by slannoy** [comment]
Hi AndiFo,
thanks for the answer. I'll double check with the latest release to confirm the (I would say 'my') expected bahaviour.
Regards,
-Seb

**Comment by BenjaminMarteau** [comment]
Hi,
I have the same problem. Were you able to make a fix?

**Comment by AndiFo** [comment]
Hi @BenjaminMarteau,

Yes, I was able to resolve the problem. First of all you should copy the fix (https://github.com/glpi-project/glpi/pull/12741), this way the agent will not immediately lock unlocked fields again.

But you will probably already have many locked objects. You have to unlock them first (BASE_URL_TO_GLPI/front/lockedfield.php), because status fields that are already locked will not be updated. 

Hope this helps you.

Best Regards
Andi
