### ISSUE TITLE
Error with Inventory - Inventory frequency (in hours)

### ISSUE THREAD

**Issue by AndiFo** [glpi-project/glpi#12739]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

Setting of Inventory frequency (in hours) will be ignored and the default value of 24 hours is always taken.

### Page URL

glpi/front/inventory.conf.php

**Comment by stonebuzz** [comment]
Can you please provide debug output from ```Agent```

ATM, if i change frequency from GLPI Native inventory configuration

![image](https://user-images.githubusercontent.com/7335054/194560034-52dbc81c-58f0-4a80-a271-019a3d5258c7.png)



Agent get new frequancy
Before : 
```shell
[debug2] format: Zlib
[debug2] [http client] FD3D8D8A: received message:
{"expiration":"24","status":"ok"}
```

After : 
```shell
[debug2] format: Zlib
[debug2] [http client] FD3D8D8A: received message:
{"expiration":"4","status":"ok"}
```

**Comment by AndiFo** [comment]
Sorry @stonebuzz, I can't find this information in the log. But currently I'm using FusionInventory Agent and not GLPIAgent.

But if I change "const DEFAULT_FREQUENCY" at src\Agent\Communication\AbstractRequest.php from 24h for example to 8h the agent shows this 8 hours and works with this 8h frequency.

Hope this helps you too.

**Comment by AndiFo** [comment]
Hi @stonebuzz, sorry I did not change the debug level to 2.

I've now tested both agents. GLPI Agent works as expected but FusionInventory Agent does not. FusionInventory Agent works with DEFAULT_FREQUENCY (src\Agent\Communication\AbstractRequest.php).

Log:
<REPLY><PROLOG_FREQ>8</PROLOG_FREQ><RESPONSE>SEND</RESPONSE></REPLY>
