### ISSUE TITLE
Question : decommision date

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1274]
Hello,

Is it possible to add decommission date to software or end of support, in order to create a report.

IT operation master plan :+1: 

hardware end of support
software end of support
planned upgrade

A table would be done with this data in a 5 years planning ordering to have a master view of projects.

hardware renewal, network, software, os,....

Thank you for your answer

**Comment by orthagh** [comment]
Hello @satyan01 

It's already the case since 9.1, see management tab of your software.
You can also add the column in the list and search in this field.
