### ISSUE TITLE
Automatic actions Mailgate does not execute by schedule, just doesnt run

### ISSUE THREAD

**Issue by SILICONICT** [glpi-project/glpi#12742]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.2

### Bug description

Automatic actions Mailgate does not execute by schedule, just doesnt run, need to click teh exceute button from GLPI to get the action to be executed.

**Comment by trasher** [comment]
Also, 10.0.2 is not the latest stable version, consider upgrading.
