### ISSUE TITLE
Group events on Planning can be deleted with read-only permission

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12753]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Somebody with read only permissions on "Planning", can delete a group event, even with the 403 forbidden

### Relevant log output

```shell
==> access-errors.log <==
`
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-22 18:16:18 [15650@glpi-new]
User ID: 15650 tried to access or perform an action on /front/planningexternalevent.form.php?id=17?error=3 with insufficient rights. Additional information: User is missing the 1 (READ) right for planning
        Stack Trace:
                /var/www/html/glpi/src/Session.php:984 displayRightError()
                /var/www/html/glpi/front/planningexternalevent.form.php:38 checkRight()
2022-09-22 18:16:22 [15650@glpi-new]
User ID: 15650 tried to access or perform an action on /front/planningexternalevent.form.php?id=17 with insufficient rights. Additional information: User is missing the 1 (READ) right for planning
        Stack Trace:
                /var/www/html/glpi/src/Session.php:984 displayRightError()
                /var/www/html/glpi/front/planningexternalevent.form.php:38 checkRight()
2022-09-22 21:46:53 [4476@glpi-new]
User ID: 4476 tried to access or perform an action on /front/user.form.php?id=4476 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/user.form.php:241 displayFullPageForItem()
2022-09-23 10:39:11 [8@glpi-new]
User ID: 8 tried to access or perform an action on /front/ticket.form.php?id=27262 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-23 10:40:29 [8@glpi-new]
User ID: 8 tried to access or perform an action on /front/ticket.form.php?id=27237 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-23 10:46:39 [8@glpi-new]
User ID: 8 tried to access or perform an action on /front/ticket.form.php?id=27203 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/ticket.form.php:259 displayFullPageForItem()
2022-09-23 14:17:58 [29221@glpi-new]
User ID: 29221 tried to access or perform an action on /front/user.form.php?id=29221 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6294 displayRightError()
                /var/www/html/glpi/src/CommonDBTM.php:6384 displayAccessDeniedPage()
                /var/www/html/glpi/front/user.form.php:241 displayFullPageForItem()
2022-09-23 17:50:49 [7@glpi-new]
User ID: 7 tried to access a non-existent item /front/reminder.form.php?id=22. Additional information: The item could not be found in the database
        Stack Trace:
                /var/www/html/glpi/src/CommonDBTM.php:6270 displayNotFoundError()
                /var/www/html/glpi/src/CommonDBTM.php:6379 displayItemNotFoundPage()
                /var/www/html/glpi/front/reminder.form.php:143 displayFullPageForItem()
````
From the client side:
````
CalDavSynchronizer.DataAccess.WebDavClientException: Response status code does not indicate success: '403' ('Forbidden'). Message:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:sabredav-version>4.4.0</s:sabredav-version>
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message/>
</d:error>

   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<EnsureSuccessStatusCode>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequest>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.HttpClientBasedClient.WebDavClient.<ExecuteWebDavRequestAndReturnResponseHeaders>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.DataAccess.CalDavDataAccess.<CreateNewEntity>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CalDavSynchronizer.Implementation.CalDavRepository`1.<Create>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GenSync.EntityRepositories.BatchEntityRepositoryAdapter`4.<PerformOperations>d__3.MoveNext()
````
```


### Page URL

_No response_

### Steps To reproduce

1. Go to Administration
2. Go to Pofiles
3. Select some profile
4. Go to Assistance
5. Select only the "Read" on Planning - External events
6. When some event is deleted form a calendar client, there is the 403 forbidden but is deleted

### Your GLPI setup information

Information about system installation and configuration
GLPI 10.0.3 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

### Anything else?

_No response_

**Comment by cedric-anne** [comment]
Hi,

Is it also deleted on GLPI side, or only in your calendar client ?

**Comment by dxdemetriou** [comment]
Both. I'll make some more checks today with different clients.

**Comment by dxdemetriou** [comment]
> Hi,
> 
> Is it also deleted on GLPI side, or only in your calendar client ?

I tried now on Thunderbird with a user with read-only permissions, by subscribing to a Group Planning using the "Copy CalDAV URL to clipboard". Everything deleted on the Thunderbird is also deleted on GLPI but there is no any error message. The only error messages I had, are those on the Outlook with the caldavsynchronizer addon, in which the event is deleted on the GLPI and then it gives the error I posted before without deleting the event on the Outlook because of the error. For some reason, the "read" & "delete" are allowed and the "create" & "update" are not allowed.

**Comment by dxdemetriou** [comment]
I have seen the read-only alternatives the "Export - Ical" and the "Export - Webcal", but if there are multiple group plannings it's more time consuming to subscribe to every group and give it a name, also in some cases it's more preferred to be used the authentication instead of the token.

**Comment by cedric-anne** [comment]
Hi,

There is a limitation of WebDAV specifications, see https://www.rfc-editor.org/rfc/rfc3744#section-3 . Indeed, there is only `read` and `write` levels of privileges in WebDAV/CalDAV.
By default, user should have the `read` privilege on all objects he can see, and the `write` privilege if it has the `UPDATE` right on the object.

Rights are tested against the default profile of the user.

**Comment by dxdemetriou** [comment]
> Hi,
> 
> There is a limitation of WebDAV specifications, see https://www.rfc-editor.org/rfc/rfc3744#section-3 . Indeed, there is only `read` and `write` levels of privileges in WebDAV/CalDAV. By default, user should have the `read` privilege on all objects he can see, and the `write` privilege if it has the `UPDATE` right on the object.
> 
> Rights are tested against the default profile of the user.

Hello,

I've tried to use the links from "Export - Ical/Webcal" (for what I understood, everything using the planning.php with token) both in the Thunderbird and Outlook, but in every case even with the "update, create, purge" selected, it's read-only in every case. If I understood correctly, it's here that will be used the permission manager later?

When the "Copy CalDAV URL to" is used (for what I understood, everything using the caldav.php with credentials), if the "read" is selected then the "create & update" are not working, but the "delete" is allowed. It seems that the "delete" is allowed only on existing content. If I understood correctly, it's here that the sabre/dav is used in which the WebDAV limitations exists? Isn't possible from the GLPI's side to protect the contect, for example if the create is unavailable then to not allow the "delete" to complete?

**Comment by cedric-anne** [comment]
Hi,

Can you check #12803 ?
During deletion action, the `PURGE` right was not checked, so it was indeed possible to delete an item without having this right.

For information, an event created by a given user will always be editable/deletable for this user, regardless its rights. Indeed, `UPDATE` and `PURGE` rights are intended to indicate the possible actions on events created by other users.

**Comment by dxdemetriou** [comment]
> Hi,
> 
> Can you check #12803 ? During deletion action, the `PURGE` right was not checked, so it was indeed possible to delete an item without having this right.
> 
> For information, an event created by a given user will always be editable/deletable for this user, regardless its rights. Indeed, `UPDATE` and `PURGE` rights are intended to indicate the possible actions on events created by other users.

Yes, it seems that's fixed, thanks :)

Tried on Thunderbird which gives this error message:

An error occurred when writing to the calendar CALENDAR-NAME! Please see below for more information.

Error code: MODIFICATION_FAILED

Description: If you're seeing this message after snoozing or dismissing a reminder and this is for a calendar you do not want to add or edit events for, you can mark this calendar as read-only to avoid such experience in future. To do so, get to the calendar properties by right-clicking on this calendar in the list in the calendar or task view.
