### ISSUE TITLE
(notice) Undefined variable in KnowbaseItem_Item.php

### ISSUE THREAD

**Issue by tdozbun-reno** [glpi-project/glpi#12750]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

After adding a solved ticket as an item of a Knowledge Base entry (for reference purposes), viewing the attached items of a ticket produces the following warnings:
Notice: Undefined variable: rand in /var/www/html/src/KnowbaseItem_Item.php on line 208
Notice: Undefined variable: rand in /var/www/html/src/KnowbaseItem_Item.php on line 213
Notice: Undefined variable: rand in /var/www/html/src/KnowbaseItem_Item.php on line 222

I realize this is only a warning and can be suppressed, but I wanted to report it all the same.

![image](https://user-images.githubusercontent.com/94628229/191988469-7cd62fb3-9b5e-4358-a5ed-c850d6c44315.png)

Details:
The ticket was manually marked as solved with the dropdown and doesn't have a proper solution posted, only a followup that appears as a solution visually.

The user viewing the ticket is an administrator with the current entity set to the root and all children selected.

### Relevant log output

```shell
I couldn't find any relevant log output
```

### Page URL

/front/ticket.form.php?id=4388

### Steps To reproduce

1. Create a ticket
2. reply with followup
3. Mark the ticket as solved with the dropdown menu and not an answer.
4. Create a knowledge base entry and add the ticket as an item to it.

### Anything else?

In KnowbaseItem_Item::showForItem :
$rand is set the the return value of either dropdownAllTypes(...) or KnowbaseItem::dropdown(...), but only when $canedit and $ok_state are true. ( `if ($canedit && $ok_state) {` ).    ($ok_state seems to be set when the ticket is not solved and not closed.)

Afterwards $rand is used in the actions form functions (Html::openMassiveActionsForm, showMassiveActions) and Html::getCheckAllAsCheckbox, but only when $canedit is true - a less restrictive condition than the dropdowns.

So, it seems that the actions are displayed even when the ticket is closed or solved - but the dropdowns they rely on are not.

If the current behavior is desirable, then $rand should probably be set to an explicitly empty value when it is not available.

**Comment by cconard96** [comment]
Should be fixed by #12752
