### ISSUE TITLE
Location rule

### ISSUE THREAD

**Issue by Cha-sim** [glpi-project/glpi#12758]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When I want to assign an ip automatically to a location, it creates a new location for me with numbers (ex: 31) depending on the location selected, it changes number.

if I rename this new place (ex: 31 >> test) at the next inventory lift, it will recreate a place for me with a new number.

The only workaround found is to assign the ip to a "regular value" in which I put the name of the place.
if the place is at the root it works, on the other hand if it is a "sub-place" it does not work.

**Comment by trasher** [comment]
Please try with latest 10.0/bugfixes branch nighly build

**Comment by Cha-sim** [comment]
Same problem with the nighly build

**Comment by trasher** [comment]
I confirm the issue

**Comment by jpdenss** [comment]
Unfortunately this problem still exists, even in the GLPI Inventory 1.6 version I recently updated. I installed a database from scratch using Windows and GLPI 10.5. I just installed this plugin and performed the discovery. I found the device but the rule creates a new location and associates it with the device.

Apache/2.4.51 (Win64) 
PHP/8.1.0

**Comment by stonebuzz** [comment]
Can you retry with GLPI nighlty build
https://nightly.glpi-project.org/glpi/
improvements have been added on the inventory part

and glpi-inventory-plugin 1.0.6 ?

Best regards
