### ISSUE TITLE
Add project in https://scrutinizer-ci.com

### ISSUE THREAD

**Issue by edgardmessias** [glpi-project/glpi#1276]
Add project in https://scrutinizer-ci.com

**Comment by edgardmessias** [comment]
@remicollet @trasher @orthagh What do you think about the scrutinizer?

**Comment by ddurieux** [comment]
It's beautiful, but that's all. 
Seems not give information we can need / use.
-1 for me :p

**Comment by trasher** [comment]
Agree with @ddurieux ... Looks like interesting at the first time... But this only give very few interesting informations finally.

👎 for me as well

**Comment by edgardmessias** [comment]
Great, I'll close this.
