### ISSUE TITLE
Unable to massively associate databases with applications

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#12766]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Unable to massively associate databases with applications.
![image](https://user-images.githubusercontent.com/78087722/192316691-93cab38e-d9c0-482a-b5b7-35b678fa60fa.png)
No application are avalable in drop-down list.
But it is possible to associate application.
![image](https://user-images.githubusercontent.com/78087722/192317296-6ddb9ba2-3387-4ef0-ab54-f661d20b9f1e.png)

### Page URL

https://support-info.sites.fr/front/database.php

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by #12769.

**Comment by Tony710** [comment]
OK, I confirm https://github.com/glpi-project/glpi/pull/12769 fix.
Thanks.
