### ISSUE TITLE
printing an individual ticket might require some adjustments

### ISSUE THREAD

**Issue by 4lex11s** [glpi-project/glpi#12764]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Following the masterful update of GLPi, now printing the contents of a ticket only prints incorrectly (printing an individual ticket worked fine in 9.5.9)

It could be that some tweaking is needed for a clean print, maybe adding some dedicated css like:

`<link rel="stylesheet" type="text/css" href="print.css" media="print">`

Thanks in advance

### Steps To reproduce

1. Go to /front/ticket.php
2. Select a ticket
3. Print a ticket (CTRL+P)

### Your GLPI setup information

GLPI on GNU/Linux

**Comment by dmonty2** [comment]
Staff in our school district print the tickets and attach them to assets before shipping to maintenance.  Here is some CSS that makes printed ticket look better on paper.

`
<style media="print">
 #tabspanel, #tabspanel-select {visibility:collapse; min-width:0px; display:none}
 .btn, .m-1, .navbar, .itil-right-side, #itil-footer {display:none}
 body, p, ul, div {font-size:7pt; -webkit-print-color-adjust: exact !important;} 
</style>
`

**Comment by 4lex11s** [comment]
Yes, the problem remains
### Version
10.0.5

**Comment by Krys-cha** [comment]
> Staff in our school district print the tickets and attach them to assets before shipping to maintenance. Here is some CSS that makes printed ticket look better on paper.
> 
> `<style media="print">
> 
> #tabspanel, #tabspanel-select {visibility:collapse; min-width:0px; display:none}
> 
> .btn, .m-1, .navbar, .itil-right-side, #itil-footer {display:none}
> 
> body, p, ul, div {font-size:7pt; -webkit-print-color-adjust: exact !important;}
> 
> </style>`

Hi.
Where exactly do you put this code plz ? I have to print ticket from time to time and the output is horrible by default.
Thank you
