### ISSUE TITLE
RSS Feeds : error  

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#12765]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

![image](https://user-images.githubusercontent.com/78087722/192310042-45684fd0-9e55-4152-89ae-11f25029a1bd.png)

![image](https://user-images.githubusercontent.com/78087722/192310148-1dcc7307-1111-4f77-86ef-f9f059844789.png)

Unable retrive RSS Feeds contente

### Relevant log output

```shell
Php-errors.log
glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "entities_id" in C:\xxx\glpi\front\rssfeed.form.php at line 96  

"entities_id" column doesn't exist in `glpi_rssfeeds`  table.
```
![image](https://user-images.githubusercontent.com/78087722/192310489-4ab02299-c8b0-4d80-854a-85967a63083e.png)

### Page URL

https://glpi-validation.sites.fr/front/rssfeed.form.php

### Steps To reproduce

Just set RSS Feeds

**Comment by Tony710** [comment]
Hi @cedric-anne
 https://github.com/glpi-project/glpi/pull/12771 Fix warning message in php-error.log
but RSS Feeds stay in error

**Comment by cedric-anne** [comment]
I have no problem to retrieve this feed.

Do you have any error il GLPI logs ? Did you manually define `GLPI_SERVERSIDE_URL_ALLOWLIST` value ?

**Comment by Tony710** [comment]
Very strange,
From web browser on GLPI server, I can load RSS feeds : https://glpi.userecho.com/feeds/topics/fr/ -> Not a network restriction. When I setup RSS Feeds, I can show Https Traffic from Glpi to glpi.userecho.com.
I can't find any error on Glpi Logs. GLPI_SERVERSIDE_URL_ALLOWLIST value isn't define in config files (also not found in session variable with Debug mode)
