### ISSUE TITLE
recurrent ticket not created

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1277]
Hello

My recurrent ticket does not created anymore

2016-11-10 06:00:27 [902@UNGSRVGVA118]
  *** PHP Notice(8): Uninitialized string offset: 0
  Backtrace :
  inc\commonitilobject.class.php:1292                
  inc\ticket.class.php:1746                          CommonITILObject->post_addItem()
  inc\commondbtm.class.php:844                       Ticket->post_addItem()
  inc\ticketrecurrent.class.php:481                  CommonDBTM->add()
  inc\ticketrecurrent.class.php:424                  TicketRecurrent::createTicket()
  inc\crontask.class.php:834                         TicketRecurrent::cronTicketRecurrent()
  front\cron.php:66                                  CronTask::launch()

**Comment by trasher** [comment]
I think this is a dup of #1192 ; fee free to reopen if I'm wrong.

**Comment by satyan01** [comment]
Hello I am in 9.1 version so it is not the same bug

**Comment by trasher** [comment]
It will be fixed in 9.1.2, and the 9.1.1 is not yet out... :)

The fix is here:
https://github.com/glpi-project/glpi/pull/1193/files

**Comment by satyan01** [comment]
thx
