### ISSUE TITLE
Error opening /glpi/front/networkport.php

### ISSUE THREAD

**Issue by leruetkins** [glpi-project/glpi#12784]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Error while opening network port at page /glpi/front/networkport.php

### Page URL
glpi/front/networkport.php

### Steps To reproduce

1. I opened any computer
2. Went to [Network ports]
3. Then opened any adapters and tried return to the list
![изображение](https://user-images.githubusercontent.com/15270519/192712784-6079708b-cb6f-4214-8f62-3923cd2ae0ea.png)
![изображение](https://user-images.githubusercontent.com/15270519/192713111-64639bc1-2f54-4a89-899c-09cd2624167c.png)
4. And I got error
![изображение](https://user-images.githubusercontent.com/15270519/192713502-2df74ee7-ba34-4b2d-8fe8-e90a4045a01b.png)

**Comment by trasher** [comment]
This has already been fixed in 10.0/bugfixes branch.
There is no ports list, this button has been hidden.
