### ISSUE TITLE
tikket -> add  a solution

### ISSUE THREAD

**Issue by NazarovRoman** [glpi-project/glpi#12793]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

I have the following problem:
when I click the "solution" button in response to the ticket, then I get an error

sorry for my English

![image](https://user-images.githubusercontent.com/40058572/192770880-3a9b4a8f-6762-4dee-81de-3d867bcbfff8.png)
![image](https://user-images.githubusercontent.com/40058572/192769882-85ae7dcc-7ec2-4121-a356-9d040dc8845f.png)

file logs:
[php-errors.log](https://github.com/glpi-project/glpi/files/9664658/php-errors.log)

[sql-errors.log](https://github.com/glpi-project/glpi/files/9664659/sql-errors.log)
[access-errors.log](https://github.com/glpi-project/glpi/files/9664663/access-errors.log)

### Page URL

help.bpmg.kz

### Steps To reproduce

if you go to any ticket then
when I click the "solution" button in response to the ticket, then I get an error
I have provided more details in the attached pictures.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.3 ( => /opt/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux help.bpmg.kz 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64
PHP 7.4.30 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, memcache, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, recode, session, shmop,
	soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="600" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.22.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 41, Revision da46e5474f9
	Server Version: 5.7.38-41
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.38) is supported.
The log file has been created successfully.
Write access to /opt/glpi/files/_cache has been validated.
Write access to /opt/glpi/config has been validated.
Write access to /opt/glpi/files/_cron has been validated.
Write access to /opt/glpi/files has been validated.
Write access to /opt/glpi/files/_dumps has been validated.
Write access to /opt/glpi/files/_graphs has been validated.
Write access to /opt/glpi/files/_lock has been validated.
Write access to /opt/glpi/files/_pictures has been validated.
Write access to /opt/glpi/files/_plugins has been validated.
Write access to /opt/glpi/files/_rss has been validated.
Write access to /opt/glpi/files/_sessions has been validated.
Write access to /opt/glpi/files/_tmp has been validated.
Write access to /opt/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /opt/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /opt/glpi
GLPI_CONFIG_DIR: /opt/glpi/config
GLPI_VAR_DIR: /opt/glpi/files
GLPI_MARKETPLACE_DIR: /opt/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 

PHP Notice (8): Array to string conversion in /opt/glpi/src/Config.php at line 2073
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /opt/glpi/files
GLPI_CACHE_DIR: /opt/glpi/files/_cache
GLPI_CRON_DIR: /opt/glpi/files/_cron
GLPI_DUMP_DIR: /opt/glpi/files/_dumps
GLPI_GRAPH_DIR: /opt/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /opt/glpi/files/_locales
GLPI_LOCK_DIR: /opt/glpi/files/_lock
GLPI_LOG_DIR: /opt/glpi/files/_log
GLPI_PICTURE_DIR: /opt/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /opt/glpi/files/_plugins
GLPI_RSS_DIR: /opt/glpi/files/_rss
GLPI_SESSION_DIR: /opt/glpi/files/_sessions
GLPI_TMP_DIR: /opt/glpi/files/_tmp
GLPI_UPLOAD_DIR: /opt/glpi/files/_uploads
GLPI_INVENTORY_DIR: /opt/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /opt/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/opt/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/opt/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/opt/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/opt/glpi/marketplace/financialreports/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/opt/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/opt/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/opt/glpi/vendor/sabre/http/lib)
sabre/uri in (/opt/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/opt/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/opt/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/opt/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/opt/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/opt/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/opt/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/opt/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/opt/glpi/vendor/symfony/console)
scssphp/scssphp in (/opt/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/opt/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/opt/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/opt/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/opt/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/opt/glpi/vendor/ramsey/uuid/src)
psr/log in (/opt/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/opt/glpi/vendor/psr/simple-cache/src)
psr/cache in (/opt/glpi/vendor/psr/cache/src)
league/csv in (/opt/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/opt/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/opt/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/opt/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/opt/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/opt/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/opt/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/opt/glpi/vendor/symfony/cache)
html2text/html2text in (/opt/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/opt/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/opt/glpi/vendor/symfony/dom-crawler)
twig/twig in (/opt/glpi/vendor/twig/twig/src)
twig/string-extra in (/opt/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/opt/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/opt/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/opt/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.9 in (/usr/share/pear)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (help@bpmg.kz@smtp.bpmg.kz)

</details><details><summary>Plugins list</summary><pre> 
	activity             Name: Activities                     Version: 3.1.1      State: Enabled                                 
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated               
		Install Method: Marketplace
	archisw              Name: Apps structures                Version: 2.2.9      State: Enabled                                 
		Install Method: Marketplace
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Marketplace
	camerainput          Name: Camera Input                   Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	connections          Name: Connections                    Version: 10.0.0     State: Enabled                                 
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.9      State: Enabled                                 
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.7      State: Enabled                                 
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.2      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Installed / not activated               
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.8.2      State: Installed / not activated               
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.0.4      State: Installed / not activated               
		Install Method: Marketplace
	purchaserequest      Name: Purchase request               Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	releases             Name: Releases                       Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.2      State: Installed / not activated               
		Install Method: Marketplace
	accounts             Name: Аккаунты                       Version: 3.0.2      State: Enabled                           
		      Install Method: Marketplace
	webapplications      Name: Веб-приложений              Version: 4.0.1      State: Enabled                         
		        Install Method: Marketplace
	fields               Name: Дополнительные поля    Version: 1.17.3     State: Installed / not activated       
		        Install Method: Marketplace
	additionalalerts     Name: Другие уведомления      Version: 2.4.0      State: Enabled                         
		        Install Method: Marketplace
	moreticket           Name: Еще заявка                     Version: 1.7.1      State: Enabled                          
		       Install Method: Marketplace
	consumables          Name: Заказ расходных материалов Version: 2.0.0      State: Enabled               
		                  Install Method: Marketplace
	manufacturersimports Name: Импорт поставщиков      Version: 3.0.2      State: Installed / not activated       
		        Install Method: Marketplace
	positions            Name: Картография                   Version: 6.0.1      State: Installed / not activated       
		        Install Method: Marketplace
	news                 Name: Оповещения                     Version: 1.10.5     State: Enabled                         
		        Install Method: Marketplace
	mreporting           Name: Подробные отчеты          Version: 1.8.1      State: Enabled                         
		        Install Method: Marketplace
	screenshot           Name: Сделать и приложить снимок экр Version: 2.0.1      State: Enabled         
		                        Install Method: Marketplace
	financialreports     Name: Состояния оборудования Version: 3.0.0      State: Enabled                      
		           Install Method: Marketplace
	tasklists            Name: Список задач                  Version: 2.0.1      State: Enabled                         
		        Install Method: Marketplace
	timelineticket       Name: Сроки заявок                  Version: 10.0+1.0   State: Enabled                         
		        Install Method: Marketplace
	order                Name: Управление заказами    Version: 2.9.0      State: Enabled                         
		        Install Method: Marketplace
	genericobject        Name: Управление объектами  Version: 2.13.0     State: Enabled                         
		        Install Method: Marketplace
	resources            Name: Человеческие Ресурсы  Version: 3.0.3      State: Enabled                         
		        Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
Errors seems to be related to you "" plugin. Please try with this plugin disabled, and report issues on their tracker.

**Comment by NazarovRoman** [comment]
Thank you! Indeed, I disabled all plugins and the error disappeared
