### ISSUE TITLE
Annotations are not added to the ticket

### ISSUE THREAD

**Issue by Andi-87** [glpi-project/glpi#12790]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.9

### Bug description

We retrieve an e-mail mailbox via IMAP. New tickets are created. If a user replies to a ticket, the reply is not added to the ticket but remains in the mailbox.

When triggering the e-mail fetch manually, I got the following error message: "If you reject the solution, you must specify a reason"

It's basically the same issue as https://github.com/glpi-project/glpi/issues/11398 but for 9.5.9. I don't have the /scr directory.

Can you have a look at this please.

Many Thanks.

### Your GLPI setup information

GLPI 9.5.9 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:de_DE

**Comment by cedric-anne** [comment]
Hi,

Do you have some plugins, especially `behaviours` plugin ? In that case, try to reproduce with all plugins disabled.

Also, GLPI 9.5.x is not supported anymore, so please try to reproduce in GLPI 10.0.3.

**Comment by Andi-87** [comment]
I disabled all plugins but to no avail.

The following plugins are installed.

`dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled
	datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled
	geninventorynumber   Name: Inventarnummern generieren     Version: 2.5.1      State: Installed / not activated
	itilcategorygroups   Name: ItilCategory Groups            Version: 2.4.2      State: Enabled
	pdf                  Name: PDF-Ausgabe                    Version: 2.0.0      State: Enabled
	tag                  Name: Tag Management                 Version: 2.8.3      State: Enabled`


We will plan an update to 10.0.3 soon. I had used GLPI before and it worked without any problems.
