### ISSUE TITLE
Knowledge base profil assignment doesn't list the real profils

### ISSUE THREAD

**Issue by jsdarges** [glpi-project/glpi#12800]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

When you try to add a target to a knwoledge base entry and select "Profil", the list of profils displayed are wrong. It seems to be hard coded because I have 10 profils and I can't see all of them and most of all I think the list is hard coded and based on the default one (when you install GLPI for the first time). At the end I can select all the targets I want. 

### Steps To reproduce

1. Create a knowledge base entry
2. select "profil" as target
3. list the profils (previously add a completly new one that you can easily identify)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.2 ( => C:\inetpub\wwwroot)
Installation mode: GIT
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT SRVMANTISDEV 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.4 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.28
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: cigonline@localhost/glpi_adecco
	Host info: localhost via TCP/IP
	
PHP version (8.1.4) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.28) is supported.
The log file has been created successfully.
Write access to C:\inetpub\wwwroot/files/_cache has been validated.
Write access to C:\inetpub\wwwroot/config has been validated.
Write access to C:\inetpub\wwwroot/files/_cron has been validated.
Write access to C:\inetpub\wwwroot/files has been validated.
Write access to C:\inetpub\wwwroot/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot/files/_lock has been validated.
Write access to C:\inetpub\wwwroot/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot/files/_rss has been validated.
Write access to C:\inetpub\wwwroot/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot/files/_uploads has been validated.
Web access to files directory is protected
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\wwwroot/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\inetpub\wwwroot
GLPI_CONFIG_DIR: C:\inetpub\wwwroot/config
GLPI_VAR_DIR: C:\inetpub\wwwroot/files
GLPI_MARKETPLACE_DIR: C:\inetpub\wwwroot/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: GIT
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\inetpub\wwwroot/files
GLPI_CACHE_DIR: C:\inetpub\wwwroot/files/_cache
GLPI_CRON_DIR: C:\inetpub\wwwroot/files/_cron
GLPI_DUMP_DIR: C:\inetpub\wwwroot/files/_dumps
GLPI_GRAPH_DIR: C:\inetpub\wwwroot/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\inetpub\wwwroot/files/_locales
GLPI_LOCK_DIR: C:\inetpub\wwwroot/files/_lock
GLPI_LOG_DIR: C:\inetpub\wwwroot/files/_log
GLPI_PICTURE_DIR: C:\inetpub\wwwroot/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\inetpub\wwwroot/files/_plugins
GLPI_RSS_DIR: C:\inetpub\wwwroot/files/_rss
GLPI_SESSION_DIR: C:\inetpub\wwwroot/files/_sessions
GLPI_TMP_DIR: C:\inetpub\wwwroot/files/_tmp
GLPI_UPLOAD_DIR: C:\inetpub\wwwroot/files/_uploads
GLPI_INVENTORY_DIR: C:\inetpub\wwwroot/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\inetpub\wwwroot/locales
GLPI_VERSION: 10.0.2
GLPI_SCHEMA_VERSION: 10.0.2@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.2.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.6 in (C:\inetpub\wwwroot\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\inetpub\wwwroot\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\wwwroot\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\inetpub\wwwroot\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\wwwroot\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\wwwroot\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\wwwroot\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\wwwroot\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\wwwroot\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\wwwroot\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\wwwroot\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\wwwroot\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\wwwroot\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\wwwroot\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\wwwroot\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\wwwroot\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\wwwroot\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\wwwroot\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\wwwroot\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\wwwroot\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\wwwroot\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\wwwroot\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\wwwroot\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\wwwroot\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\wwwroot\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\wwwroot\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\wwwroot\vendor\psr\cache\src)
league/csv in (C:\inetpub\wwwroot\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\wwwroot\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\wwwroot\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\wwwroot\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\wwwroot\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\wwwroot\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\wwwroot\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\wwwroot\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\wwwroot\vendor\html2text\html2text\src)
symfony/css-selector in (C:\inetpub\wwwroot\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\inetpub\wwwroot\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\wwwroot\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\wwwroot\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (glpi@dev.cidwe.com@smtp.ionos.fr)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.17.3     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.11.2     State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by cconard96** [comment]
Please test with the latest bug fix version 10.0.3.

**Comment by cconard96** [comment]
After some testing, this seems intentional. The profiles that show up in the list are the ones with the "READ" permission for the Knowledgebase as they would be the only ones that could read the article unless it is put into the FAQ.

**Comment by jsdarges** [comment]
Hello,

After upgrading my version to 10.0.3 : the issue is fixed but I don't think it's due to this upgrade because yes there are 2 notions on the reading mode: knwoledge access and FAQ access. The profils which wasn't list in the dropdown list had no read mode to the FAQ...

Sorry for the misunderstanding
