### ISSUE TITLE
Erro ao anexar arquivo quando obrigatório anexar, GLPI entra em loop solicitando mais anexo após anexado o primeiro

### ISSUE THREAD

**Issue by ppsnetto** [glpi-project/glpi#12819]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Erro ao anexar arquivo na versão 10.0.3, mesmo após anexar, é gerado mensagem para anexar novamente, foi aplicado a configuração de obrigar anexar documento para esse modelo de chamado:

![image](https://user-images.githubusercontent.com/82681973/193269111-6b2d1ecc-9efc-4add-b4f0-59d7f043d2b8.png)
![image](https://user-images.githubusercontent.com/82681973/193269167-e1b54cba-805a-4279-8261-df89c76eca17.png)

### Relevant log output

```shell
[2022-09-30 08:21:06] glpiphplog.WARNING: Test logger  
[2022-09-30 08:27:04] glpiphplog.DEBUG: Html::compileScss() in /var/www/portal.com/public_html/glpi/src/Html.php line 6849
Compile css/palettes/flood.scss  {"user":"@pm-info-pedro"} 
[2022-09-30 09:27:11] glpiphplog.WARNING: Test logger  
[2022-09-30 09:27:11] glpiphplog.WARNING:   *** PHP Warning (2): mkdir(): Permission denied in /var/www/portal.com/public_html/glpi/src/Toolbox.php at line 1168
  Backtrace :
  src/Toolbox.php:1168                               mkdir()
  ...System/Requirement/DirectoryWriteAccess.php:113 Toolbox::testWriteAccessToDirectory()
  src/System/Requirement/AbstractRequirement.php:110 Glpi\System\Requirement\DirectoryWriteAccess->check()
  src/System/Requirement/AbstractRequirement.php:152 Glpi\System\Requirement\AbstractRequirement->doCheck()
  src/Config.php:2051                                Glpi\System\Requirement\AbstractRequirement->isOutOfContext()
  src/Config.php:2218                                Config::showSystemInfoTable()
  src/Config.php:2687                                Config->showSystemInformations()
  src/CommonGLPI.php:689                             Config::displayTabContentForItem()
  src/CommonGLPI.php:653                             CommonGLPI::displayStandardTab()
  ajax/common.tabs.php:113                           CommonGLPI::displayStandardTab()
  
[2022-09-30 09:27:13] glpiphplog.WARNING:   *** PHP User Warning (512): Unable to fetch registration information.
Error message:
Response:
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
 in /var/www/portal.com/public_html/glpi/src/GLPINetwork.php at line 247
  Backtrace :
  src/GLPINetwork.php:247                            trigger_error()
  src/GLPINetwork.php:102                            GLPINetwork::getRegistrationInformations()
  src/GLPINetwork.php:50                             GLPINetwork::showForConfig()
  src/CommonGLPI.php:689                             GLPINetwork::displayTabContentForItem()
  src/CommonGLPI.php:653                             CommonGLPI::displayStandardTab()
  ajax/common.tabs.php:113                           CommonGLPI::displayStandardTab()
 ---------------------------------------------------------------------------------------------


Cron.log:


2022-09-30 08:27:24 [@pm-info-pedro]
Interno #1: Executar olaticket
2022-09-30 08:27:41 [@pm-info-pedro]
Interno #1: Executar reservation
2022-09-30 08:27:50 [@pm-info-pedro]
Interno #1: Executar closeticket
2022-09-30 08:32:21 [@pm-info-pedro]
Interno #1: Executar alertnotclosed
2022-09-30 08:33:29 [@pm-info-pedro]
Interno #1: Executar queuednotification
2022-09-30 08:33:31 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:37 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:43 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:49 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:51 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:53 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:55 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:57 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:33:59 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:01 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:03 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:05 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:07 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:10 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:12 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:14 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:17 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:19 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:21 [@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 08:34:25 [@pm-info-pedro]
Interno #1: Executar mailgate
2022-09-30 08:36:16 [@pm-info-pedro]
Interno #1: Executar slaticket
2022-09-30 09:03:04 [1425@pm-info-pedro]
Interno #1: Executar RecurrentItems
2022-09-30 09:06:45 [@pm-info-pedro]
Interno #1: Executar temp
2022-09-30 09:08:30 [@pm-info-pedro]
Interno #1: Executar olaticket
2022-09-30 09:16:25 [1425@pm-info-pedro]
Interno #1: Executar queuednotification
2022-09-30 09:16:28 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:34 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:40 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:45 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:48 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:50 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:51 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:54 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:56 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:16:57 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:00 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:02 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:04 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:06 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:08 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:10 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:12 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:14 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:16 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:18 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:20 [1425@pm-info-pedro]
Erro ao enviar o e-mail<br/>SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting
2022-09-30 09:17:20 [@pm-info-pedro]
Interno #1: Executar graph
2022-09-30 09:27:03 [10@pm-info-pedro]
Interno #1: Executar slaticket
```

### Page URL

https://glpi.santaluzia.mg.gov.br/

### Steps To reproduce

1 - Assistência>Chamados>Modelos de Chamados
2 - Configurar o modelo de chamado para obrigar anexar arquivo
3 - Criar novo chamado
4 - Anexar arquivo 
5 - Salvar chamado
6 - Erro, mesmo com arquivo anexado, o GLPI entra em loop e continua solicitando anexo.

### Your GLPI setup information

Operating system: Linux pm-info-pedro 5.15.0-48-generic #54~20.04.1-Ubuntu SMP Thu Sep 1 16:17:26 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, soap, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at portal.com Port 80
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.2.22-MariaDB-1:10.2.22+maria~bionic
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@10.1.100.58:3306/glpi_homolog
	Host info: 10.1.100.58 via TCP/IP
	
PHP version (7.4.3) is supported.PHP version (7.4.3) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.2.22) is supported.Database engine version (10.2.22) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/portal.com/public_html/glpi/files/_cache has been validated. Write access to /var/www/portal.com/public_html/glpi/config has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_cron has been validated. Write access to /var/www/portal.com/public_html/glpi/files has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_dumps has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_graphs has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_lock has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_pictures has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_plugins has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_rss has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_sessions has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_tmp has been validated. Write access to /var/www/portal.com/public_html/glpi/files/_uploads has been validated.Write access to /var/www/portal.com/public_html/glpi/files/_cache has been validated.
Write access to /var/www/portal.com/public_html/glpi/config has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_cron has been validated.
Write access to /var/www/portal.com/public_html/glpi/files has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_dumps has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_graphs has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_lock has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_pictures has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_plugins has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_rss has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_sessions has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_tmp has been validated.
Write access to /var/www/portal.com/public_html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
The directory could not be created in /var/www/portal.com/public_html/glpi/marketplace.The directory could not be created in /var/www/portal.com/public_html/glpi/marketplace.
Timezones seems loaded in database.Timezones seems loaded in database.

### Anything else?

Já informado acima os detalhes do problema.
![configuraçao_aplicada](https://user-images.githubusercontent.com/82681973/193270609-c97e275a-d04e-457d-8b60-60a40e2d2a87.jpg)
![evidencia_erro_ao_anexar_arquivo](https://user-images.githubusercontent.com/82681973/193270612-7b065930-2d2f-4ee1-95e5-89165dfbfdc8.jpg)

**Comment by SteadEXE** [comment]
Hello, I would suggest you to translate your request in english.
We only accept english request here, you will also find more answer in english 👍

**Comment by trasher** [comment]
Using only english here is not a only a suggestion; see https://github.com/glpi-project/glpi/blob/10.0/bugfixes/CONTRIBUTING.md

**Comment by tomolimo** [comment]
Hello @trasher,
Same behavior here: [https://glpi.userecho.com/en/communities/1/topics/2114-erro-ao-anexar-documento](https://glpi.userecho.com/en/communities/1/topics/2114-erro-ao-anexar-documento) 😬

**Comment by trasher** [comment]
seems like I've lost userecho credentials; I cannot close by myself :( I'll ask, but almost everyone is offline right now.
