### ISSUE TITLE
Problem with NULL and EMPTY value in filters

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#12817]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

In earlier versions, you could type "NULL" into the search field and fields with or without (with negation) an empty value were searched.

Currently, this does not work properly.

example:
name -> not contain -> NULL
NOT -> name -> not contain -> NULL

NOT -> name -> contain -> NULL
name -> contain -> NULL

The problem is also when the value is empty but not NULL.

It would also be good to add in the filter the possibility to search for "is" or "is not" empty.

name -> is -> NULL/empty
name -> is not -> NULL/empty

It would be best to add the ability to search in "is"/"is not" value "NULL/EMPTY":

WHERE `$field`is NULL OR `$field`=''

**Comment by cedric-anne** [comment]
Hi,

I close this issue as this enhancement has been done in #11863.
