### ISSUE TITLE
Watcher - Observer harmonization

### ISSUE THREAD

**Issue by OscarBeiro** [glpi-project/glpi#12848]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.X

### Bug description

As I was updating some translation issues caused by a recent plural change in Transifex, I noticed a mix of Watcher and Observer (added in GLPI 10) strings for the same concept.

![image](https://user-images.githubusercontent.com/18396050/193446222-3f3e6fe9-6619-4048-a943-629f1a66372a.png)
![image](https://user-images.githubusercontent.com/18396050/193446256-e7cec798-fa2e-4cc1-ae72-c214de5d9a1e.png)

10.1 has already decided to drop watcher apparently.

Inspired by #12707

### Steps To reproduce

Ticket view is using Observer
Rules keep showing Watcher

### Your GLPI setup information

Not relevant

**Comment by trasher** [comment]
Duplicates #12603
