### ISSUE TITLE
composant of computer 

### ISSUE THREAD

**Issue by yassinedamir** [glpi-project/glpi#12852]
### Describe the bug

the information of the administrative and Financial management of the components of the computer (hard desk, network card, ....) they delete with each inventory of the agent glpi

### To reproduce

1-the information of the administrative and Financial management of the components of the computer (hard desk, network card, ....) they delete with each inventory of the agent glpi

### Expected behavior

the information of the administrative and Financial management of the components of the computer (hard desk, network card, ....) they delete with each inventory of the agent glpi

### Operating system

Linux

### GLPI Agent version

1.4, 1.3, 1.2

### GLPI version

10.0.2, 10.0.1, 10.0.0

### GLPIInventory plugin

1.0.4

**Comment by yassinedamir** [comment]
@stonebuzz thank you very much

**Comment by stonebuzz** [comment]
Keep in mind that PR is in progress (draft) , changes maybe occurs

**Comment by yassinedamir** [comment]
![image](https://user-images.githubusercontent.com/37710927/193687088-19e1ff61-a869-426d-8c68-94505e5552e8.png)

**Comment by trasher** [comment]
Solved by #12904

**Comment by yassinedamir** [comment]
@trasher  thank you very much

**Comment by yassinedamir** [comment]
not yet fixed
