### ISSUE TITLE
Public Saved search visible without entity restriction

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi#12857]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

On GLPI v10.0.3, public saved search for tickets are not restricted by entity.

We have the following entities : 
- CSSCV
- --- Ressources Matérielles
- --- Ressources Informatiques

If we create a public saved search inside "Ressources Matérielles" and another one inside "Ressources Informatiques", users inside one or the other entity can see all saved searches listed as public, even if they are located inside the other entity (that they don't have access).

![image](https://user-images.githubusercontent.com/38400135/193583818-19dece71-a78a-4676-b485-6ce72f430660.png)
![image](https://user-images.githubusercontent.com/38400135/193583903-3bec2371-ae65-4acb-967e-9ea9bb9dfe75.png)

**This only affect the vue inside /front/ticket.php when we select the button to show saved searches :** 
![image](https://user-images.githubusercontent.com/38400135/193583627-4d8aa02a-3aae-42e1-8e9a-0c41be6a99ea.png)
![image](https://user-images.githubusercontent.com/38400135/193584151-3030b05e-9ef6-4299-9eed-d0eff9c8e8eb.png)

They are correctly restricted when managing saved searches through /front/savedsearch.php

Also note that the list of saved search on the /front/ticket.php page also list more than one saved search with the default flag (I have 5 with the star) and only 1 is showing the star inside /front/savedsearch.pgp

Thanks

### Relevant log output

```shell
no error
```

### Page URL

/front/ticket.php

### Steps To reproduce

1. Create 2 sub entities
2. Affect one user to one sub entity and a second one to the second entity
3. Create a different public saved search in each sub-entity
4. Log with one user into one of the sub-entity
5. See that both saved search are displayed

### Anything else?

May need a different bug report (please advise) but "saved search" button is not displayed inside objects list of GenericObject plugins. Not sure if it's a bug with glpi or the plugins itself...

![image](https://user-images.githubusercontent.com/38400135/193588270-f8014069-3c16-43ca-8e0a-41eb3c860437.png)

/marketplace/genericobject/front/object.php?itemtype=Myobject

**Comment by trasher** [comment]
Several fixes has been done since 10.0.3 release on that part, please test if you reproduce with latest nightly build.

**Comment by fralla2** [comment]
I will try with all the fixes this afternoon but I already applied those 2 and the problem was still present :

https://github.com/glpi-project/glpi/commit/9727416518a7e80a96476b09823c599397d159ff

https://github.com/glpi-project/glpi/commit/1d21b3f8c1e5b05c77952f5edbc19dacbf3ac292

Thanks
Francois

Sent from my Bell Samsung device over Canada’s largest network.
________________________________

**Comment by fralla2** [comment]
Problem is still present in nightly : https://nightly.glpi-project.org/glpi/main-0158630.tar.gz

**Comment by fralla2** [comment]
Probably need to add an entity restriction in this function : 
https://github.com/glpi-project/glpi/blob/5ec7ba9498d9b9efffe74d126af400e76338d6aa/src/SavedSearch.php#L1318

**Comment by fralla2** [comment]
I think the "Need feedback" should be removed. This issue is still present in v10.0.5

**Comment by qaOYR** [comment]
I can confirm that I have reproduced this issue in two separate instances of glpi. 

I even consider this a security issue as the name of saved searches can be quite revealing. In our case, we do not want one clientsto know the name of other clients.

Let us know if we can of help in further isolating or testing this issue.

Thanks.

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by #13854.

**Comment by fralla2** [comment]
Tested working great. Thanks
