### ISSUE TITLE
Streamlined interface issue

### ISSUE THREAD

**Issue by dognun** [glpi-project/glpi#12860]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

All attempts to configure the simplified interface fail.
In debug mode I get the log:

Uncaught Exception TypeError: CommonITILObject::restoreInputAndDefaults(): Argument #2 ($options) must be of type array, null given, called in /var/www/html/nittech/glpi/src/Ticket.php on line 3909 in / var/www/html/nittech/glpi/src/CommonITILObject.php at line 366

But I can't find anything other than the files available here.

### Relevant log output

```shell
Uncaught Exception TypeError: CommonITILObject::restoreInputAndDefaults(): Argument #2 ($options) must be of type array, null given, called in /var/www/html/nittech/glpi/src/Ticket.php on line 3909 in /var/www/html/nittech/glpi/src/CommonITILObject.php at line 366
```

### Page URL

https://helpdesk.nittech.com.br/front/tickettemplate.form.php?id=3

### Steps To reproduce

1 - Open the assistance tab
2 - Tickets
3 - Template option
4 - Default templates (at this point, it doesn't matter if it's in the default templetate or creating a new one, the error always happens)
5 - Simplified interface

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.3 ( => /var/www/html/nittech/glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi-server-2 5.14.0-70.17.1.el9_0.cloud.x86_64 #1 SMP PREEMPT Fri Jul 29 17:24:52 UTC 2022 x86_64
PHP 8.0.23 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.51 (Rocky Linux) OpenSSL/3.0.1 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84
Server Software: MariaDB Server
	Server Version: 10.5.16-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: nitglpi@localhost/glpinitdb
	Host info: Localhost via UNIX socket
	
PHP version (8.0.23) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.16) is supported.
The log file has been created successfully.
Write access to /var/www/html/nittech/glpi/files/_cache has been validated.
Write access to /var/www/html/nittech/glpi/config has been validated.
Write access to /var/www/html/nittech/glpi/files/_cron has been validated.
Write access to /var/www/html/nittech/glpi/files has been validated.
Write access to /var/www/html/nittech/glpi/files/_dumps has been validated.
Write access to /var/www/html/nittech/glpi/files/_graphs has been validated.
Write access to /var/www/html/nittech/glpi/files/_lock has been validated.
Write access to /var/www/html/nittech/glpi/files/_pictures has been validated.
Write access to /var/www/html/nittech/glpi/files/_plugins has been validated.
Write access to /var/www/html/nittech/glpi/files/_rss has been validated.
Write access to /var/www/html/nittech/glpi/files/_sessions has been validated.
Write access to /var/www/html/nittech/glpi/files/_tmp has been validated.
Write access to /var/www/html/nittech/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/nittech/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/html/nittech/glpi
GLPI_CONFIG_DIR: /var/www/html/nittech/glpi/config
GLPI_VAR_DIR: /var/www/html/nittech/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/nittech/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/html/nittech/glpi/files
GLPI_CACHE_DIR: /var/www/html/nittech/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/nittech/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/nittech/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/nittech/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/nittech/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/nittech/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/nittech/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/nittech/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/nittech/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/nittech/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/nittech/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/nittech/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/nittech/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/html/nittech/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/nittech/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/nittech/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/nittech/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/nittech/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/html/nittech/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/nittech/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/nittech/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/nittech/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/nittech/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/nittech/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/nittech/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/nittech/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/nittech/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/nittech/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/nittech/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/nittech/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/nittech/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/nittech/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/nittech/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/nittech/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/nittech/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/nittech/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/nittech/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/nittech/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/nittech/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/nittech/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/nittech/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/nittech/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/nittech/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/nittech/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/nittech/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/nittech/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/nittech/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/nittech/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/nittech/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/nittech/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/nittech/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/nittech/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/nittech/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/nittech/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/nittech/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/var/www/html/nittech/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/nittech/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (contato@nittech.com.br@smtp.titan.email)

</details><details><summary>Plugins list</summary><pre> 
	datainjection        Name: Data injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Meu Painel                     Version: 2.0.4      State: Not installed                           
		Install Method: Marketplace
	dashboard            Name: Painel                         Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	trademark            Name: Trademark                      Version: 2.0.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
Duplicates #12805
