### ISSUE TITLE
Incorrect integer value: 'Intel Corporation' for column 'manufacturers_id' 

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#12869]
I see the same problem now that GLPI Inventory is activated but on another table : 

[2022-10-03 10:25:03] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_devicecontrols` (`designation`, `manufacturers_id`, `interfacetypes_id`, `date_creation`, `date_mod`) VALUES ('H81 Express LPC Controller', 'Intel Corporation', '217', '2022-10-03 10:24:59', '2022-10-03 10:24:59')
  Error: Incorrect integer value: 'Intel Corporation' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1312                               
  src/CommonDBTM.php:716                             DBmysql->insert()
  src/CommonDBTM.php:1321                            CommonDBTM->addToDB()
  src/CommonDevice.php:512                           CommonDBTM->add()
  src/Inventory/Asset/Device.php:121                 CommonDevice->import()
  src/Inventory/Asset/Controller.php:98              Glpi\Inventory\Asset\Device->handle()
  src/Inventory/Asset/MainAsset.php:847              Glpi\Inventory\Asset\Controller->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@host","mem_usage":"0.001\", 7.48Mio)"}

_Originally posted by @fralla2 in https://github.com/glpi-project/glpi/issues/12811#issuecomment-1265530364_

**Comment by trasher** [comment]
I'm not able to reproduce.
Please wait until tomorrow and try with nightly (previous fix has been merged today).

**Comment by fralla2** [comment]
I might be wring but I would think the problem might come from this line : 

https://github.com/glpi-project/glpi/blob/3976a2518987516668461916ee4ecc80b06cfdf1/src/Inventory/Asset/Controller.php#L65

$pci_manufacturer probably contains the name and not the ID, but get affected to manufacturers_id

**Comment by trasher** [comment]
Then I guess this is related to input data. Could you provide a controller inventory entry I can use to reproduce easily the issue?

**Comment by trasher** [comment]
I've tested using the following (truncated to keep only relevant parts):

```php
    public function testDictionnaryManufacturer()
    {
        //[...]

        $rules_id = $rule->add(['name' => 'Set controller manufacturer',
            'is_active' => 1,
            'entities_id' => 0,
            'sub_type' => 'RuleDictionnaryManufacturer',
            'match' => \Rule::AND_MATCHING,
            'condition' => 0,
            'description' => ''
        ]);
        $this->integer($rules_id)->isGreaterThan(0);

        $this->integer(
            $criteria->add([
                'rules_id' => $rules_id,
                'criteria' => 'name',
                'condition' => \Rule::PATTERN_IS,
                'pattern' => 'My Intel Corporation'
            ])
        )->isGreaterThan(0);

        $this->integer(
            $action->add([
                'rules_id' => $rules_id,
                'action_type' => 'assign',
                'field' => 'name',
                'value' => 'Untel'
            ])
        )->isGreaterThan(0);

        $vendors = new \PCIVendor();
        $this->integer(
            $vendors->add([
                'name'  => addslashes("My Intel Corporation"),
                'vendorid'  => '8086'
            ])
        )->isGreaterThan(0);

        $json = json_decode(file_get_contents(self::INV_FIXTURES . 'computer_1.json'));

        $nb_computers = countElementsInTable(\Computer::getTable());
        $inventory = $this->doInventory($json);

        //[...]

        $controllers = $DB->request([
                'SELECT' => \Manufacturer::getTable() . '.name',
                'FROM' => \DeviceControl::getTable(),
                'LEFT JOIN' => [
                    \Manufacturer::getTable() => [
                        'ON' => [
                            \Manufacturer::getTable() => 'id',
                            \DeviceControl::getTable() => 'manufacturers_id'
                        ]
                    ]
                ],
                'WHERE' => [
                    \DeviceControl::getTable() . '.designation' => 'Wireless 8260'
                ]
            ]
        );
        $this->integer(count($controllers))->isIdenticalTo(1);
        $controller = $controllers->current();
        $this->string($controller['name'])->isIdenticalTo('Untel');
    }
```

It does the following:
- create a PCI vendor with `My Intel Corporation` as name for pciid `8086`,
- create a `RuleDictionnaryManufacturer` replacing `My Intel Corporation` with `Untel`,
- inventory a computer with a controller description `Wireless 8260` and vendorid `8086`,
- check computer is properly inventoried, as well as wireless controller with expected name (`Untel`).

All works well, without any SQL issue on my side.

**Comment by trasher** [comment]
You can see tests are successfull here: https://github.com/trasher/glpi/actions/runs/3188207534/jobs/5200594504 (lint issues are not relevant).

**Comment by mshishko** [comment]
We also have a very similar problem with inventory. Here is an extract from the sql-error.log file

**Comment by trasher** [comment]
I need a way to reproduce, I've not been able to.

**Comment by fralla2** [comment]
I will try to investigate further tomorrow but it looks like it affect almost every field using manufacturers_id with the inventory

If you have a live instance of glpi with inventory, I can try to find one of our computer and redirect the inventory to your setup for testing...

[sql-errors.log](https://github.com/glpi-project/glpi/files/9718723/sql-errors.log)

**Comment by fralla2** [comment]
@trasher : I will try to apply this fix https://github.com/glpi-project/glpi/pull/12670 

It really looks like the same issue. Get back to you in a few hours.
Thanks

**Comment by fralla2** [comment]
@trasher : Way less errors now that I've applied #12670 but I still get some all related to peripherals. I've doublecheck the src/Inventory/Asset/Peripheral.php file and it's identical to the latest version with the fix in it.

Thanks


`[2022-10-06 13:24:41] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'Microdia' WHERE `id` = '22758'
  Error: Incorrect integer value: 'Microdia' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01"} 
[2022-10-06 13:24:41] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'SMART Technologies Inc.' WHERE `id` = '22779'
  Error: Incorrect integer value: 'SMART Technologies Inc.' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01","mem_usage":"0.186\", 6.61Mio)"} 
[2022-10-06 13:26:12] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'Realtek Semiconductor Corp.' WHERE `id` = '22739'
  Error: Incorrect integer value: 'Realtek Semiconductor Corp.' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01"} 
[2022-10-06 13:27:58] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'SMART Technologies Inc.' WHERE `id` = '22906'
  Error: Incorrect integer value: 'SMART Technologies Inc.' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01"} 
[2022-10-06 13:29:23] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'SMART Technologies Inc.' WHERE `id` = '22842'
  Error: Incorrect integer value: 'SMART Technologies Inc.' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01"} 
[2022-10-06 13:31:22] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'TP-Link' WHERE `id` = '22738'
  Error: Incorrect integer value: 'TP-Link' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01"} 
[2022-10-06 13:31:36] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'Realtek Semiconductor Corp.' WHERE `id` = '22739'
  Error: Incorrect integer value: 'Realtek Semiconductor Corp.' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01"} 
[2022-10-06 13:31:36] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi-10.0.3/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_peripherals` SET `manufacturers_id` = 'ARC International' WHERE `id` = '22776'
  Error: Incorrect integer value: 'ARC International' for column 'manufacturers_id' at row 1
  Backtrace :
  src/DBmysql.php:1431                               
  src/CommonDBTM.php:672                             DBmysql->update()
  src/CommonDBTM.php:1675                            CommonDBTM->updateInDB()
  src/Inventory/Asset/Peripheral.php:171             CommonDBTM->update()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Peripheral->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:946                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:305    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:242    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  {"user":"@deimos01","mem_usage":"0.096\", 6.45Mio)"} `

**Comment by trasher** [comment]
I'm still not able to reproduce with latest 10.0/bugfixes nightly. 

Please provide an inventory file and all explanations to reproduce easily from a fresh GLPI installation.
I'm not going to waste more time on that subject.

**Comment by fralla2** [comment]
I did some test with the nightlybuild https://nightly.glpi-project.org/glpi/10.0-54d9a00.tar.gz and it looks like it's fixed on this release...

Something other than #12670  #12816 fixed this issue but I'm not sure what...

I guess we'll wait until 10.0.4 is released and see it the error show-up again.


Thanks
Francois
