### ISSUE TITLE
searchOption 2 has weird available_searchtypes

### ISSUE THREAD

**Issue by ghost** [glpi-project/glpi#1287]
There's something that appeared strange to me today when using `/listSearchOptions`
it looks like the ID searchoption (always number 2) of (per example) Ticket provides only "contains" as available searchtype, which seems weird to me as I think a search by id is more likely to be done with the "equals" searchtype.
Whatever if "contains" is worth being provided or not for id lookup, it isn't the most important part of this ticket.

But wouldn't it be normal that the "equals" searchtype was at least provided ?

This is the ID searchoption I get when doing

`GET /listSearchOptions/Ticket`

![screenshot_2016-11-11_16-01-40](https://cloud.githubusercontent.com/assets/4069983/20219126/255620ec-a828-11e6-9912-b8725d6dd421.png)

This is related to the "add available searchtypes in searchoptions"  merge request : https://github.com/glpi-project/glpi/pull/1014

**Comment by cedric-anne** [comment]
Hi,

Search options were initially used for the search form. As the searchtype `equals` made list of all avalaible values displayed in a dropdown, making it available on ID field of Ticket item may leads to performances issues, as Tickets count can be really important.

Regards
