### ISSUE TITLE
laminas error with imap integration

### ISSUE THREAD

**Issue by renatopancheri** [glpi-project/glpi#12887]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.9

### Bug description

Hi,

i have a couple of emails that laminas library (called by mailgate) cannot read , i get an error on php-error.log when running cron.php.
I am not sure if it is a problem of GLPI or a malformed email,
as far as i understand the problem is that Message-ID header is missing,
it does look like the mail was modified by some spam assassin...
[Attached you can find the email (i've modified sensible data)](https://github.com/glpi-project/glpi/files/9717277/Message.txt)

### Relevant log output

```shell
/XXX/plugins/unicat/inc/request.class.php - IDOR: 828d8b61e13cf04b3add69041f9443a36611b0cf41b41dc1dba8dfb8b485a2ab
[2022-10-05 15:34:30] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name message_id or message_id not found in /XXX/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  inc/mailcollector.class.php:1453                   Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:970                    MailCollector->getHeaders()
  inc/mailcollector.class.php:758                    MailCollector->buildTicket()
  front/mailcollector.form.php:88                    MailCollector->collect()
```

### Steps To reproduce

- setup imap integration
- load on the email box ad email without Message-ID header
- run cron.php with mailgate on

### Your GLPI setup information

[code]
 
GLPI 9.5.9 ( => /XXXX)
Installation mode: TARBALL
Current language:it_IT

Operating system: Linux RPU-HDS-WS-L001 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64
PHP 7.4.32 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="90" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.4.32 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Server Software: MariaDB Server
	Server Version: 10.7.1-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/XXXX
	Host info: Localhost via UNIX socket
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.7.1) - Perfect!Database version seems correct (10.7.1) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /XXX/files/_cache has been validated.Write access to /XXX/files/_cache has been validated.
Write access to /XXX/config has been validated.Write access to /XXX/config has been validated.
Write access to /XXX/files/_cron has been validated.Write access to /XXX/files/_cron has been validated.
Write access to /XXX/files has been validated.Write access to /XXX/files has been validated.
Write access to /XXX/files/_dumps has been validated.Write access to /XXX/files/_dumps has been validated.
Write access to /XXX/files/_graphs has been validated.Write access to /XXX/files/_graphs has been validated.
Write access to /XXX/files/_lock has been validated.Write access to /XXX/files/_lock has been validated.
Write access to /XXX/files/_pictures has been validated.Write access to /XXX/files/_pictures has been validated.
Write access to /XXX/files/_plugins has been validated.Write access to /XXX/files/_plugins has been validated.
Write access to /XXX/files/_rss has been validated.Write access to /XXX/files/_rss has been validated.
Write access to /XXX/files/_sessions has been validated.Write access to /XXX/files/_sessions has been validated.
Write access to /XXX/files/_tmp has been validated.Write access to /XXX/files/_tmp has been validated.
Write access to /XXX/files/_uploads has been validated.Write access to /XXX/files/_uploads has been validated.
Write access to /XXX/marketplace has been validated.Write access to /XXX/marketplace has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.

 
GLPI_ROOT: /XXX
GLPI_CONFIG_DIR: /XXX/config
GLPI_VAR_DIR: /XXX/files
GLPI_MARKETPLACE_DIR: /XXX/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /XXX/files
GLPI_CACHE_DIR: /XXX/files/_cache
GLPI_CRON_DIR: /XXX/files/_cron
GLPI_DUMP_DIR: /XXX/files/_dumps
GLPI_GRAPH_DIR: /XXX/files/_graphs
GLPI_LOCAL_I18N_DIR: /XXX/files/_locales
GLPI_LOCK_DIR: /XXX/files/_lock
GLPI_LOG_DIR: /XXX/files/_log
GLPI_PICTURE_DIR: /XXX/files/_pictures
GLPI_PLUGIN_DOC_DIR: /XXX/files/_plugins
GLPI_RSS_DIR: /XXX/files/_rss
GLPI_SESSION_DIR: /XXX/files/_sessions
GLPI_TMP_DIR: /XXX/files/_tmp
GLPI_UPLOAD_DIR: /XXX/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /XXX/locales
GLPI_VERSION: 9.5.9
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/XXX/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/XXX/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/XXX/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/XXX/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/XXX/vendor/michelf/php-markdown/Michelf)
true/punycode in (/XXX/vendor/true/punycode/src)
iamcal/lib_autolink in (/XXX/vendor/iamcal/lib_autolink)
sabre/dav in (/XXX/vendor/sabre/dav/lib/DAV)
sabre/http in (/XXX/vendor/sabre/http/lib)
sabre/uri in (/XXX/vendor/sabre/uri/lib)
sabre/vobject in (/XXX/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/XXX/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/XXX/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/XXX/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/XXX/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/XXX/vendor/sebastian/diff/src)
elvanto/litemoji in (/XXX/vendor/elvanto/litemoji/src)
symfony/console in (/XXX/vendor/symfony/console)
scssphp/scssphp in (/XXX/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/XXX/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/XXX/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/XXX/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/XXX/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/XXX/vendor/ramsey/uuid/src)
psr/log in (/XXX/vendor/psr/log/Psr/Log)
psr/simple-cache in (/XXX/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/XXX/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/XXX/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/XXX/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/XXX/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/XXX/vendor/paragonie/sodium_compat/src)

<html><body>

Mails receivers
--
Name: 'mail@domain' Active: Yes 	Server: '{dovecot.domain:993/imap/ssl/validate-cert/notls}INBOX' Login: 'mail@domain' 		Password: Yes

</body>
</html>

<html><body>

Plugins list
--
news                 Name: Avvisi                         Version: 1.9.0      State: Enabled 	
fields               Name: Campi aggiuntivi               Version: 1.12.8     State: Enabled
behaviors            Name: Comportamenti                  Version: 2.5.0      State: Enabled 	
dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled 	
datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled 	
formcreator          Name: Form Creator                   Version: 2.12.4     State: Not installed 	
fusioninventory      Name: FusionInventory                Version: 9.5+4.0    State: Enabled 	
pdf                  Name: Stampa in PDF                  Version: 2.0.0      State: Enabled 	
timelineticket       Name: Timeline of tickets            Version: 9.5+1.1    State: Enabled 	
unicat               Name: UniCat                         Version: 1.0.6      State: Enabled
[/code]

</body>
</html>

**Comment by cconard96** [comment]
9.5.X is no longer supported except for security fixes.
This bug should be fixed by #12206 for 10.0.3.

It may be possible to apply the patch to 9.5.X manually. You would only need to apply the changes in the `src/MailCollector.php` file in the patch to `inc/mailcollector.class.php`.
