### ISSUE TITLE
Security die. trying to load an forbidden class name

### ISSUE THREAD

**Issue by IgorMoro** [glpi-project/glpi#1289]
Good day.
Help solve the problem.
When you save a search filter applications bookmark writes error "Security die. Trying to load an forbidden class name".
GLPI version 9.1. In version 0.90.4 was the same

Tell me how to solve this problem.
Thank you in advance
![noname](https://cloud.githubusercontent.com/assets/23448549/20258466/65443642-aa82-11e6-8ce6-073214422c18.png)

**Comment by orthagh** [comment]
Hello @IgorMoro 

Could you check directly in your mysql database, glpi_bookmarks table, if you find some line with itemtype = 0.

here is a query to help find the lines:

```sql
SELECT * FROM glpi_bookmarks WHERE itemtype = '0'
```

**Comment by orthagh** [comment]
836for information, it's a bug normally fixed in 0.90.5 (and so 9.1), see #836

**Comment by IgorMoro** [comment]
Thank you so much.
Now is the time to appear try to implement this fix.
If something goes wrong, I unsubscribe here.

**Comment by IgorMoro** [comment]
I did as you said, it worked.
Once again, thank you very much.
