### ISSUE TITLE
Other auth (http) without SSO plugin throw Warning : Undefined array key "id" in src/User.php

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi#12899]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi, we currently do SSO through http headers (Microsoft app proxy is doing the preauthentification and sends info to glpi)

Problem since v10 is that we get the error bellow in the log file because SSO function tried to find the user' groups from his ID but I think the ID is not defined yet since http headers only sends username

Line in question : https://github.com/glpi-project/glpi/blob/6cba9dadce5b99c6e9f7688f6495074cc6a40453/src/User.php#L2174

I don't know if it's also affecting poeple using your sso plugins or only the ones using http headers only.

### Relevant log output

```shell
[2022-10-06 15:29:07] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi-10.0.3/src/User.php at line 2178
  Backtrace :
  src/Auth.php:548                                   User->getFromSSO()
  src/Auth.php:752                                   Auth->getAlternateAuthSystemsUserLogin()
  front/login.php:88                                 Auth->login()
```

**Comment by cedric-anne** [comment]
I confirm this issue.

**Comment by cedric-anne** [comment]
@fralla2 

Can you validate that #13530 fixes the issue ?

**Comment by fralla2** [comment]
Confirmed, your pull fixed the issue. Thanks
