### ISSUE TITLE
tag_filename on add followup

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#1290]
in CommonITILObject::addFiles():
```
if (isset($this->input['_tag_filename']) && !empty($this->input['_tag_filename'][$key])) {
     $this->input['_tag'][$key] = $this->input['_tag_filename'][$key];
}
```
but $this->input['_tag_filename'] never does not set, 
in TicketFollowup::prepareInputForAdd() only checks and set "_filtename", not "_tag_filename":
```
if (isset($input['_filename'])) {
    $input["_job"]->input['_filename'] = $input['_filename'];
}
```
And if I add <document-tag-from-upload> like this "#a17e7cb9-8f034218-5829793aee7c18.21608269#" it exist in content, but does not exist in $this->input['_tag_filename'] and document does not attached to notification mail.

I think that next code need to be added in TicketFollowup::prepareInputForAdd():
```
if (isset($input['_tag_filename']))
    $input["_job"]->input['_tag_filename'] = $input['_tag_filename'];
```

**Comment by trasher** [comment]
This has been fully reworked since this ticket has been opened; should be ok now
