### ISSUE TITLE
No permission for super-admin (templates)

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12906]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

I'm trying to add a form template.  When I try to add "predefined fields" I get the message "You do not have permission to perform this action".

![image](https://user-images.githubusercontent.com/68922721/194493284-129dea20-2f34-4d98-a6a8-e5b62b51162a.png)

### Page URL

front/tickettemplate.form.php?id=2

### Steps To reproduce

1. Go to the front/tickettemplate.php
2. Open the template.
3. Try to add "Predefined field".

**Comment by cconard96** [comment]
Please test again with GLPI 10.0.5 to see if it is still an issue.
If so, please include the requested log and setup information.
For logs, the "files/_log/access-errors.log" log may contain the most relevant information.
