### ISSUE TITLE
Chrome with errors

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12912]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0-6cba9da (10.0.4-dev)

### Bug description

I see a lot of errors in the Chrome console.

For example, when I open a user-created ticket:

![image](https://user-images.githubusercontent.com/68922721/194517538-40be0e00-7532-4f58-bfed-4ee0f710980b.png)

More of it in the ticket template > in the "standard interface" preview.

![image](https://user-images.githubusercontent.com/68922721/194517951-8e298a8c-d96c-49d3-b0f0-5eace461d85d.png)

**Comment by trasher** [comment]
Please test #13211

**Comment by WebGregGit** [comment]
I confirm, this solved the problem. Thank you.
