### ISSUE TITLE
[GLPI 9.1] Unable to add Real end date on Project task

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#1291]
I have planed some project task on a project, but the task still appears on the calendar, because I'm unable to add the "Real end date".

When I set it, and save the task, Real end date field stay blank. So All task still in calendar view as missed"

**Comment by orthagh** [comment]
Hello @SylvainGuibert 

In the folder glpi/files/_log/, check the present files if you have some errors relative to this issue.

**Comment by SylvainGuibert** [comment]
no error in php_errors.log and sql-error.log about this issue.

**Comment by SylvainGuibert** [comment]
How to debug this issue ?

**Comment by trasher** [comment]
Just tested with current 9.2/bugfxes branch; the "Real end date" field is correctly saved, guess this has been fixed already.
