### ISSUE TITLE
[GLPI 9.1] Project view : Save button dessapear

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#1292]
If you have project name or project task with long name, you lost "save" button at the bottom of the page. Previously saw items name appears on 6 or 6 lines at the right top of the page.

On this exemple, previously name have 69 chars.

No scrolling bar appears on the right. 

You need to switch on full screen to retreive "save button".

![2016-11-14_11h36_56](https://cloud.githubusercontent.com/assets/16323410/20262219/9251c72e-aa61-11e6-80bf-0743ab0f7013.png)

**Comment by orthagh** [comment]
Hello @SylvainGuibert 

Normally, with "splitted interface", you should have scrollbar on each views
I just tested on chrome 54, firefox49 and IE11, in my case, it's works.

Could you indicate the browser and his version your are using.

**Comment by SylvainGuibert** [comment]
I use Chrome v 54.0.2840.99m

I can reproduce the issue with : 
-> Firefox 49.0.2
-> Internet Explorer 11.672.10586.0
-> Edge

**Comment by ladenree76000** [comment]
I confirm with FF45.1.1 (split view)
when i change project title for a long one , the project task area is shifted down.
the bottom of this area is hidden out of the window. ther is a scroll bar for this area but not for the glpi window, if i go back to normal view, the scrollbar appears for glpi window & i can see buttons. in this case if the window is not high enough, area scroll bars work fine

if i make the project title shorter & split view, i can see buttons

**Comment by orthagh** [comment]
Ok i reproduce (i missed the long title part).
The fix will be easy, i think (a white-space: nowrap; on the title)

**Comment by SylvainGuibert** [comment]
Thanks. We wait for next release !

**Comment by edgardmessias** [comment]
@SylvainGuibert, you can test this:

```patch
Index: css/styles.css
===================================================================
--- css/styles.css	(revisão 28600)
+++ css/styles.css	(cópia de trabalho)
@@ -694,7 +694,7 @@
    .layout_vsplit.form table.tab_cadre_pager {
       margin: 0;
       border: 0;
-      width: 150px;
+      width: 100%;
    }
 
    .layout_vsplit.form .ui-tabs-panel table.tab_cadre_pager {
Index: inc/commonglpi.class.php
===================================================================
--- inc/commonglpi.class.php	(revisão 28600)
+++ inc/commonglpi.class.php	(cópia de trabalho)
@@ -846,7 +846,7 @@
                                     __s('Previous')."\" title=\"".__s('Previous')."\"></td>";
          }
 
-         echo "<td width='200px'><a href=\"".$glpilisturl."\">";
+         echo "<td><a href=\"".$glpilisturl."\">";
          if ($glpilisttitle) {
             echo $glpilisttitle;
          } else {
```

Work for me.

**Comment by SylvainGuibert** [comment]
Thx @edgardmessias : Work for me too.
@orthagh : Check the @edgardmessias answer, works for me.

**Comment by trasher** [comment]
@edgardmessias could you open a PR against 9.1/bugfixes branch with your fix please?

Does this solve the issue if the name is very long and/or the screen very small? What about the other views?

Thanks! :)

**Comment by edgardmessias** [comment]
@trasher, I need make test first.
