### ISSUE TITLE
 Adds its own software categories

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12933]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4-dev

### Bug description

Before, I only saw categories of software that I added myself. Currently Glpi is adding its own. Some have specific names, others only sequential numbers.

![image](https://user-images.githubusercontent.com/68922721/194828762-288d7e28-6df7-4ff3-8372-ef79989d7bbb.png)

Numeric categories are empty. Those with the name contain entries:

![image](https://user-images.githubusercontent.com/68922721/194838305-688a05ec-fa59-44aa-b049-ef9b834635c5.png)

### Steps To reproduce

Go to Assets > Software > switch the "toggle browse".

**Comment by WebGregGit** [comment]
I noticed that the categories added are from Ubuntu. But I have a rule - if Publisher is Ubuntu - set it to "free".

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
Can you try this -> https://github.com/glpi-project/glpi/pull/13005

No need to clean up your database, it should work (update of categories depending on your rules) the next time the inventory comes up

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

I am not reproducing at the moment.

With the following rule:

If Editor = Ubuntu 
then category -> cat_perso

Can you try with nightly build ?

https://nightly.glpi-project.org/glpi/

**Comment by WebGregGit** [comment]
Hi @stonebuzz 

I installed nightly > deleted all with the number in the name > Assets > Software > New ones have appeared.

I applied the fix you mentioned above > deleted all with the number in the name > Assets > Software > 3 minutes later (this is how much the software loads for me) > I can't see new entries with numbers.


![image](https://user-images.githubusercontent.com/68922721/196403269-3f7d4805-4b4c-4b62-91e3-ad615d1f753c.png)



I have not checked how it is with other categories, e.g. admin, contrib / utils etc. I suspect this is an attempt to implement automatic categorization in GLPI. I don't know how to judge it yet. On the one hand, it's nice and makes life easier - on the other, I don't know if it's too fragmented.

**Comment by blackpearl-2022** [comment]
I am also having the same issue. I did as you mentioned above.
1. installed nightly build
2. update the file software.php in both the locations
   Even after doing this I still have the issue. The numbers are not generated in the software category but also in the manufacturers.

Also, i am using the glpi agent 1.4, not the nighty build one.

Is there any other thing to do?

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

Can you export your dictionaries and post here generated file ?

![image](https://user-images.githubusercontent.com/7335054/206715399-6c0132de-ab01-48b6-8aac-d60e85ac83ee.png)

Best regards

**Comment by cedric-anne** [comment]
@blackpearl-2022 

Attachement from emails are not added to Github automatically. Please add it manually.

**Comment by blackpearl-2022** [comment]
> @blackpearl-2022
> 
> Attachement from emails are not added to Github automatically. Please add it manually.

The XMl files are not able to upload in here.

**Comment by stonebuzz** [comment]
Yes you need to add it manually directly from github interface

**Comment by trasher** [comment]
> The XMl files are not able to upload in here.

Just change file extension

**Comment by blackpearl-2022** [comment]
Uploading the file after renaming to txt.
[Uploading rules (7) (1).txt…]()

**Comment by stonebuzz** [comment]
```Uploading rules (7) (1).txt…```
is a link to this issue

**Comment by blackpearl-2022** [comment]
Please check this file.
[GLpi-issues.txt](https://github.com/glpi-project/glpi/files/10238037/GLpi-issues.txt)

**Comment by stonebuzz** [comment]
Seems work for me with your rule

My inventory XML software node

```xml
    <SOFTWARES>
      <ARCH>amd64</ARCH>
      <FILESIZE>512000</FILESIZE>
      <FROM>deb</FROM>
      <NAME>indesign</NAME>
      <PUBLISHER>Adobe</PUBLISHER>
      <SYSTEM_CATEGORY>admin</SYSTEM_CATEGORY>
      <VERSION>25.5</VERSION>
    </SOFTWARES>
```

After import : 

![image](https://user-images.githubusercontent.com/7335054/207895463-f35114be-279a-4aca-9ccc-9ff005792fcd.png)

![image](https://user-images.githubusercontent.com/7335054/207895486-a70cf1f8-c3d6-4954-b3d5-c470bab37dab.png)

**Comment by stonebuzz** [comment]
Hi @WebGregGit 
About generating random numbers 
can you try this ->  https://github.com/glpi-project/glpi/pull/13634

Best regards

**Comment by stonebuzz** [comment]
Hi @WebGregGit 

#13634 is closed in favor of -> https://github.com/glpi-project/glpi/pull/13639

Best regards

**Comment by blackpearl-2022** [comment]
Thank you for your support. Now it's not generating . I have edited the file you mentioned and is now working fine.

**Comment by cedric-anne** [comment]
Hi,

I close this issue as, looking at the last comment, it seems to have been fixed.
