### ISSUE TITLE
10.0.4-dev - export to pdf finished with allowed memory exhausted

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#12931]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4-dev

### Bug description

The current page is exported to pdf format. But the option with all sites is return with:

PHP Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/glpi/vendor/tecnickcom/tcpdf/tcpdf.php at line 23317

Overall, I have a lot of problems with the software tab after upgrade from 9.x. I mentioned it here https://github.com/glpi-project/glpi/issues/12779 

### Steps To reproduce

Go to Assets > Software > Export button > All pages in portrait PDF

### Your GLPI setup information

GLPI 10.0.4-dev ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

Operating system: Linux glpi 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64
Server Version: 8.0.30-0ubuntu0.20.04.2
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.34
PHP version (7.4.3) is supported.

**Comment by cedric-anne** [comment]
> PHP Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/glpi/vendor/tecnickcom/tcpdf/tcpdf.php at line 23317

You should try to upgrade your memory limit. The more you have softwares, the more memory will be required to export all your data in PDF. We cannot really optimize this part as it is based on an external library.

**Comment by WebGregGit** [comment]
Hi @cedric-anne 

I'd like to make sure. There were no such problems with version 9.x. Now I have cleared the software table and reloading it. I currently have 1/3 of 9.x and have a problem. 

![image](https://user-images.githubusercontent.com/68922721/194829525-fd375ed5-9738-4522-bc3b-c3dae1c20f22.png)

**Comment by cedric-anne** [comment]
OPcache memory limit is not related to PHP script memory limit.

On my side, I only have a small set of data, so I cannot really investigate on performances issues in PDF export.

**Comment by cedric-anne** [comment]
The second message is related to SQL memory limit, and is probably related to usage of the "tree" view in softwares.

**Comment by WebGregGit** [comment]
@cedric-anne I deleted ~7000 rows (3000 left).

Still problem with pdf

_PHP Error (1): Allowed memory size of 268435456 bytes exhausted (tried to allocate 4194312 bytes) in /var/www/html/glpi/vendor/tecnickcom/tcpdf/tcpdf.php at line 18934_

The sql warning given above no longer shows up. One left:

SQL Warnings: 1260: Row 1887 was cut by GROUP_CONCAT () 1260: Row 1927 was cut by GROUP_CONCAT () 1260: Row 1967 was cut by GROUP_CONCAT () 1260: Row 3386 was cut by GROUP_CONCAT () 1260: Row 3829 was cut by GROUP_CONCAT () 1260: Row 3915 was cut by GROUP_CONCAT () 1260: Row 4054 was cut by GROUP_CONCAT () 1260 (...)

In my opinion, there's an optimization bug somewhere. In version 9.x, Glpi processed this amount without any problems, and now it can't handle it. 
I also don't know how you can have so little software on the list - the agent is reading everything - even what is not installed (e.g. Candy Crush).
