### ISSUE TITLE
*** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input exceeds the allowed length in /var/www/glpi/vendor/laminas/laminas-mail/src/Address.php at line 64 (or 78)

### ISSUE THREAD

**Issue by boisrobe** [glpi-project/glpi#12946]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.9

### Bug description

When collector (imap or pop) collect the mail in our mailbox support we have many error :

[2022-10-11 09:37:29] glpiphplog.CRITICAL: *** Uncaught Exception Laminas\Mail\Header\Exception\InvalidArgumentException: Invalid header value detected in /var/www/glpi/vendor/laminas/laminas-mail/src/Header/GenericHeader.php at line 64
Backtrace :
vendor/laminas/laminas-mail/src/Headers.php:544 Laminas\Mail\Header\GenericHeader::splitHeaderLine()
vendor/laminas/laminas-mail/src/Headers.php:284 Laminas\Mail\Headers->loadHeader()
vendor/laminas/laminas-mail/src/Headers.php:105 Laminas\Mail\Headers->addHeaderLine()
vendor/laminas/laminas-mime/src/Decode.php:150 Laminas\Mail\Headers::fromString()
...r/laminas/laminas-mail/src/Storage/Part.php:111 Laminas\Mime\Decode::splitMessage()
...laminas/laminas-mail/src/Storage/Message.php:53 Laminas\Mail\Storage\Part->__construct()
...r/laminas/laminas-mail/src/Storage/Imap.php:127 Laminas\Mail\Storage\Message->__construct()
...aminas-mail/src/Storage/AbstractStorage.php:268 Laminas\Mail\Storage\Imap->getMessage()
inc/mailcollector.class.php:721 Laminas\Mail\Storage\AbstractStorage->current()
front/mailcollector.form.php:88 MailCollector->collect()

### Steps To reproduce

simply lunch "récupérer les courriers maintenant" and search the /var/www/glpi/files/_log/php-errors.log ti find error
[[MDE GDF] Ethernet salle étage + matériel.zip](https://github.com/glpi-project/glpi/files/9753287/MDE.GDF.Ethernet.salle.etage.%2B.materiel.zip)

### Your GLPI setup information

I try to update glpi in 9.5.9 for the CVE, update php in php 8.0.24.
debian 10
i install php-fpm 8.0 from surry repository

may be i missed something in my upgrade ???

I try to put an eml message which have problem but many of my email are impact. but github tell me we don't support that filte type. so i zip it.

Thank for your support.

### Anything else?

Big Thank you for your help
I will search if i have miss config somathing.

**Comment by boisrobe** [comment]
I search a diif between my email ko and ok, i think it is a problem already view with accent in mail.

**Comment by boisrobe** [comment]
i will upgrade to 10 after i correct this error (must read how to do this major upgrade)
I think it is just an issue with utf8 with the collector.
may be a missconfig when i upgrade to 9.5.9 for security reason

**Comment by boisrobe** [comment]
I don't find the cause :-(

So go for and update to 10. 
Is it the same process as for update 9.5 ? backup bdd, copy folder, install new version, lunch update db, copie file, chown??

**Comment by stonebuzz** [comment]
Please read this -> https://glpi-install.readthedocs.io/en/latest/update.html

**Comment by tomolimo** [comment]
Hello @boisrobe,

It's an issue I've already encountered... and the root cause is that Laminas is restricting email address format to the RFC email format, which is not really respected nowadays.

This issue can be workarounded changing a little bit the default settings of Laminas:
The settings to be changed are in the `vendor/laminas/laminas-validator/src/EmailAddress.php` file
There is a block of code like following:
```
    protected $mxRecord = [];

    /**
     * Internal options array
     */
    protected $options = [
        'useMxCheck'        => false,
        'useDeepMxCheck'    => false,
        'useDomainCheck'    => true,
        'allow'             => Hostname::ALLOW_DNS,
        'strict'            => true,
        'hostnameValidator' => null,
    ];

    /**
     * Instantiates hostname validator for local use
     *
```
It has to be changed to:
```
    protected $mxRecord = [];

    /**
     * Internal options array
     */
    protected $options = [
        'useMxCheck'        => false,
        'useDeepMxCheck'    => false,
        'useDomainCheck'    => false, //true,
        'allow'             => Hostname::ALLOW_DNS,
        'strict'            => false, //true,
        'hostnameValidator' => null,
    ];

    /**
     * Instantiates hostname validator for local use
     *

```

Try this to be sure

Thank you,
Regards,
Tomolimo

**Comment by boisrobe** [comment]
@tomolimo thanks for your proposition.

but after one day without support ticket with accent i try the update of glpi.
And it's work for me.

Now my collector parse the email and my ticket is now created.

Two update in a week :-D 

just disapointed to not find the real problem.

I contact a friend more expert on glpi than me, he have le pb so i'll give him your solution.

**Comment by cedric-anne** [comment]
Hi,

> just disapointed to not find the real problem.

Problem could be either solved by a fix in the Laminas library (version used in 10.0.x is more recent than version used in 9.5.x), either by #12232.

Regards
