### ISSUE TITLE
Agent presents in Agents list in glpi inventory but not linked (Element = 0) 

### ISSUE THREAD

**Issue by herisson80** [glpi-project/glpi#12941]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Hi,
I've got an error with some computers when I launch install (and after). 
Agent is correctly detected by GLPI Inventory but no element is linked to the Agent. Only a "0" is display in the column and if I get into the Agent, "Linked Element" is void.

Windows 10 x64 - Glpi-agent 1.4 - GLPI 10.0.3

Install command :
`msiexec /i c:\install\GLPI-Agent-1.4-x64.msi /q TAG=SER-PDT SERVER=https://MyGLPISRV.fqdn.fr ADD_FIREWALL_EXCEPTION=1 RUNNOW=1`
(I have also try with: `https://MyGLPISRV.fqdn.fr/front/inventory.php` | `https://MyGLPISRV.fqdn.fr` | `https://MyGLPISRV.fqdn.fr/plugins/glpiinventory/` )

My glpi-inventory plugin was download and put manually in plugins folder

In the log files i got
Client :
```
[Mon Oct 10 15:15:14 2022][info] GLPI Agent service starting
[Mon Oct 10 15:15:14 2022][info] [http server] HTTPD service started on port 62354
[Mon Oct 10 15:15:16 2022][info] GLPI Agent memory usage: WSS=3756032 PFU=105369600
[Mon Oct 10 15:15:16 2022][info] target server0: next run: Mon Oct 10 15:15:14 2022 - MyGLPISRV.fqdn.fr/front/inventory.php
[Mon Oct 10 15:15:16 2022][info] target server0: server MyGLPISRV.fqdn.fr/front/inventory.php
[Mon Oct 10 15:15:16 2022][info] sending prolog request to server0
[Mon Oct 10 15:15:16 2022][info] server0 answer shows it supports GLPI Agent protocol
[Mon Oct 10 15:15:17 2022][info] running task Inventory
[Mon Oct 10 15:15:17 2022][info] New inventory from Machine.fqdn.fr-2022-10-10-15-15-14 for server0 (tag=SER-PDT)
[Mon Oct 10 15:15:51 2022][error] [http client] communication error: 500 Internal Server Error, 
```

Serveur :
```
[2022-10-10 15:15:51] glpiphplog.ERROR:   *** PHP User Error (256): Column 'items_id' cannot be null in /var/www/html/glpi/src/DBmysql.php at line 1961
  Backtrace :
  src/DBmysql.php:1961                               trigger_error()
  src/Inventory/Asset/Software.php:836               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:424               Glpi\Inventory\Asset\Software->storeAssetLink()
  src/Inventory/Asset/MainAsset.php:834              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:754              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:965                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1510                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:554              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:701                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:336                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:244    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:86                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
```

Thanks

### To reproduce

No idea .. it happened or not even on same model

### Expected behavior

Agent should add computer in inventory

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

10.0.3

### GLPIInventory plugin or FusionInventory for GLPI plugin version

1.0.4

**Comment by stonebuzz** [comment]
Hi @herisson80 
can you post here inventory file?

Best regards

**Comment by herisson80** [comment]
Hi @stonebuzz 
here is a zip file with 2 HTML inventory files 
[inventaires_OK_et_NOK.zip](https://github.com/glpi-project/glpi/files/9752914/inventaires_OK_et_NOK.zip)

I notice differences in glpi-Agent.dump
[GLPI-Agent.dump.zip](https://github.com/glpi-project/glpi/files/9753020/GLPI-Agent.dump.zip)

Thanks for help

**Comment by trasher** [comment]
Inventory files are XML opr JSON, not HTML.

**Comment by herisson80** [comment]
Sorry I launched glpi-inventory -html on the computer.
so this is the simple glpi-inventory.bat result on Machine1 (OK) and Machine 2 (NOK)
[InvMachine.zip](https://github.com/glpi-project/glpi/files/9757356/InvMachine.zip)

I can't give you export from glpi server because Machine02 has no inventory due to the "bug" (or mistake)
Thanks

**Comment by herisson80** [comment]
it's perhaps obvious for you but in the table glpi_agents of glpi DB, I got NULL in "version" column and 0 in "items_id" for bugging computers

**Comment by stonebuzz** [comment]
Can you delete this agent from database and retry ? 
Best regard

**Comment by herisson80** [comment]
i have already try to delete computer before, but as you ask, i just delete it directly from DB then launch glpi-agent.bat but no luck, same result.
All HP EliteBook x360 1040 G8 Notebook PC seems to be ok (3/3) but Dell models are not import (Latitude 7400, 7420, 7490, 7480)

**Comment by stonebuzz** [comment]
I am not reproducing ATM.
Can you test ```Rules for import and link equipments``` engine here (fill field and test)

![image](https://user-images.githubusercontent.com/7335054/195269733-145000a9-d021-4b63-b38f-554d1ff2fd7a.png)

Can you by resetting rule ```Rules for import and link equipments``` ?

Best regards

**Comment by herisson80** [comment]
Hi,
I tried my rules engine, if i fill "Element Type" = Computer ", "Name" = MaMachine01.obspm.fr-2022-10-10-15-15-14, "serial num." = CF27E2EC-7A6B-4102-9613-2F2EFD2B7BC3, "Entity" = MyRootEntity
The good rule is apply "Computer import (by serial + uuid)"
I've try to reset rules without success

Regards

**Comment by stonebuzz** [comment]
I don't reproduce at the moment,
 I guess it's fixed in the nighlty build, can you test this version
https://nightly.glpi-project.org/glpi/

Best regards

**Comment by herisson80** [comment]
Hi @stonebuzz 
Thanks for tests, I just update my server with 10.0-5fa5d92.tar.gz and it works my computer is now in the inventory.
I am really very happy with the support and the help provided
Regards

**Comment by stonebuzz** [comment]
great =)
