### ISSUE TITLE
can't delete calls

### ISSUE THREAD

**Issue by angelavit** [glpi-project/glpi#12957]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI 10.0.3 

### Bug description

Hello,
i'm trying to clean up the environment but i can't delete all calls, i get this error (from php-errors.log):

[2022-10-11 20:32:13] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to NotificationTargetCommonITILObject::getActorData() must be an instance of CommonDBTM, array given, called in /var/www/html/src/NotificationTargetCommonITILObject.php on line 1192 in /var/www/html/src/NotificationTargetCommonITILObject.php at line 1623
  Backtrace :
  src/NotificationTargetCommonITILObject.php:1192    NotificationTargetCommonITILObject->getActorData()
  src/NotificationTargetTicket.php:161               NotificationTargetCommonITILObject->getDataForObject()
  src/NotificationTargetCommonITILObject.php:1024    NotificationTargetTicket->getDataForObject()
  src/NotificationTarget.php:1338                    NotificationTargetCommonITILObject->addDataForTemplate()
  src/NotificationTemplate.php:278                   NotificationTarget->getForTemplate()
  src/NotificationEventAbstract.php:127              NotificationTemplate->getTemplateByLanguage()
  src/NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src/Ticket.php:695                                 NotificationEvent::raiseEvent()
  src/CommonDBTM.php:2031                            Ticket->pre_deleteItem()
  front/ticket.form.php:141                          CommonDBTM->delete()

**Comment by cedric-anne** [comment]
Hi,

It has been fixed by #12729.
