### ISSUE TITLE
Automatic Actions Not Automatically Running

### ISSUE THREAD

**Issue by dcwalker-500** [glpi-project/glpi#12969]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Automatic Actions Not Automatically Running

I am using the mailgate and queuednotifications for my testing for both are set to scheduled and run every 1 minute using run mode CLI and I have tested this using run mode GLPI and both are not having this auto run I have to manually go in and hit the execute button and the action will run fine with no errors and we will get emails and emails will go out.  I am not sure if this is a miss configuration on my part or if there is an issue with this Version of GLPI I just installed and set this up yesterday and after 4-6 hours of troubleshooting couldn't figure out the issue.

Any ideas or help is appreciated I am definitely not an expert in this just was given a project an am running into some issues.

### Your GLPI setup information

GLPI is setup on a Windows 2019 Server using Xampp for the Apache and SQL I understand a lot of people dislike this setup this is just the way I wanted to do the setup for my environment

**Comment by keguira** [comment]
Question : did you add a scheduled task to execute the /front/cron.php ?

For automatic tasks, you should add a task that execute `php` with the argument `path_to_glpi\front\cron.php`.
Usually, it should be launched every 5 or 10 minutes.
