### ISSUE TITLE
blockquote with object mail in followup (collector)

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#12966]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

For the first time, I'm testing mail collector to add followups in tickets.
When a user responds to a ticket by email, the mail's object is inserted in the followup by using HTML blockquote tag. Is it normal ? Can I disable this behaviour ? 

### Steps To reproduce

1. Configure the mail collector
2. Create a ticket and send notification to users
3. Users add a followup by mail
4. See that the mail's object is inserted in the followup

**Comment by cedric-anne** [comment]
Hi,

I am not sure to understand the behaviour you are facing. Can you attach some screenshots ?

Also, please provide your GLPI setup information.

**Comment by paidge** [comment]
Here is the source code of the followup sent by email : 

![image](https://user-images.githubusercontent.com/2470104/195601149-64fc057d-06b3-428c-9ffd-5bc19eb2fefd.png)

**Comment by cedric-anne** [comment]
Maybe I am wrong, but it looks like the original email is embedded in a `blockquote` by the email client used to send the followup. GLPI only remove content between `=-=-=-=` and `=_=_=_=` lines. Everything located before and after these lines is not removed.

**Comment by paidge** [comment]
You are right. After checking the source code of the email, it seems that Thunderbird adds a <blockquote> tag to embed the original message when we respond to one. Do you think you can treat that case with GLPI ?

**Comment by paidge** [comment]
Firstly, I'll use CSS rules to hide this blockquote

**Comment by cedric-anne** [comment]
I do not know if the blacklist functionnality of GLPI can be used for that, but I am sure that we will not try to do such cleaning process in GLPI as it is destructive and can lead to removal of precious content in some edge case (or in case of a buggy behaviour).
