### ISSUE TITLE
Ticket form validation return to home page if description is not defined

### ISSUE THREAD

**Issue by jsdarges** [glpi-project/glpi#12968]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello,

As a self-service profile (with simplified interface) when you create a new ticket, select a category based on a gabarit and you forget to redefined the description, the user is redirected to the home with the error message 

"You cannot use predefined description verbatim
Mandatory fields are not filled. Please correct: Description "

Why? It's very disturbing: the user should stay on the formular and follow the same process as if you forget to fill a mandatory field

Luckily if the user click (after beeing redirected to the home page), on the "create a ticket" buttong, the formular get back the values he filled before...

Can you consider redirect in any cases the user to the ticket formular if the formular is not weel filled?

### Steps To reproduce

1. create a ITIL category
2. create a ticket template with a default value as description, location mandatory, categoy mandatory and title mandatory
2. assign this ticket template to this category
3. as a selfservice profile create a ticket baed on the category fullfill everything except the description
4. submit the formular => you are redirected to the home page

If you replace the step 3 by a new description and not specify any location and you try to submit the formular, the error message is displayed in the ticket and the user is not redirected to the home page

**Comment by f0rextazy** [comment]
I have the same issue

**Comment by f0rextazy** [comment]
I assume the solution to this problem is the following
In file glpi/front/tracking.injector.php change line 
'if (empty($_POST) || (count($_POST) == 0)) {                                                                                                                                                                                  
    Html::redirect($CFG_GLPI["root_doc"] . "/front/helpdesk.public.php");                                                                                                                                     
} ' 
to
' if (empty($_POST) || (count($_POST) == 0)) {                                                                                                                                                                                  
    Html::redirect($CFG_GLPI["root_doc"] . "/front/helpdesk.public.php?create_ticket=1");                                                                                                                                     
} '

**Comment by jsdarges** [comment]
> 

Yes this solution fix the issue. What is the next step now?

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.
