### ISSUE TITLE
Profil - ASSIGN option (tickets) show all tickets

### ISSUE THREAD

**Issue by jsdarges** [glpi-project/glpi#12967]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello,

In a profil if you check the option "ASSIGN" (Assistance > Tickets): 

![chrome_l6xW2DwaZU](https://user-images.githubusercontent.com/113537051/195387707-ccb5b1af-d243-437d-ba72-6a4bdf0e5c0c.png)

users can assign a ticket (ok for that) but it also allows users seeing all tickets and not only the tickets of their groups even if "SEE ALL TICKETS" is not checked!

### Steps To reproduce

1. In the "technician" profile check the same options as the picture in the descripion except the "ASSIGN" option (let it unchecked) => You can't assign a ticket (that's OK) and you see only the ticket of your groups
2. In the "technician" profile check the same options as the picture in the descripion => you will be able to assign a ticket to any groups (that's ok) and you can now list all the tickets in ./front/ticket.php (that's not OK)

**Comment by jsdarges** [comment]
Up ?

**Comment by jsdarges** [comment]
Up again to keep it open

**Comment by cedric-anne** [comment]
Hi,

Tickets visibility is checked in following code: https://github.com/glpi-project/glpi/blob/ced9d8dbbee1e6241828ab6e7b763a2a51a30623/src/Ticket.php#L250-L312

In your case, technician have `ASSIGN` + `READASSIGN` right, and so has right to see all incoming tickets.

Are you sure your technician can see other tickets ? In this case, could you give more details about his profiles rights ?

**Comment by trasher** [comment]
No feedback, I close
