### ISSUE TITLE
GLPI 10.0.3 - Attaching document in the ticket

### ISSUE THREAD

**Issue by WeronicaSS** [glpi-project/glpi#12974]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello, guys

We verified that when attaching any document in the ticket, the GLPI is changing the of the file to the same name as the title of the ticket

Is it possible to change this?

The bug happens since updating GLPI to new version: 10.0.3.

Thanks!

### Relevant log output

```shell
No response
```

### Page URL

No response

### Steps To reproduce

No response

### Your GLPI setup information

No response

### Anything else?

No response

**Comment by zoriax** [comment]
Hi ! 

Same behavior on version 10.0.5.. Very unsusfull functonnality. Why GLPI renames documents whit ticket title ? 

When you have more than one document, it beacomes very very difficule to find the right document : 

![image](https://user-images.githubusercontent.com/12936546/208855260-7218f127-7623-40e5-b9b8-ef63f737588c.png)

Could you please add a fix for that ?

**Comment by cedric-anne** [comment]
@orthagh 

In GLPI 9.5, document name was also generated using this pattern, but in timeline, the displayed informationw as the initial filename. Should we put back same behaviour on GLPI 10.0 ?

**Comment by orthagh** [comment]
yes, considering the above screenshot, it seems bad to the same name for multiple documents.

**Comment by f0rextazy** [comment]
Hi, in GLPI 10.0.5 i have this
![image](https://user-images.githubusercontent.com/110458362/215985661-ba1bec69-9ac9-4143-a1c5-6832fa6ef97d.png)
Why when create ticket, documents name is changed but when create comments, document name does not change?
For me better when document name not changing. Or in glpi will have settings, change the behavior of the system

**Comment by cedric-anne** [comment]
Fixed by #13987.
