### ISSUE TITLE
9.1.1 official release file wrong folder name

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1297]
9.1.1 official release file have the folder "glpi-9.1.1" in all other version i know there is always only "glpi" inside.

**Comment by Armin83** [comment]
@orthagh 
I can't see who had released 9.1.1 - but i think you can solve this problem ;)

**Comment by tomolimo** [comment]
Hello Armin83,
I made a try, downloading the 9.1.1 draft, and I seems correct to me.
Could you send screen copies ?

**Comment by trasher** [comment]
9.1.1 is not yet released, the official tarball is not yet available to public.

You're talking about "github" release download, and we cannot change anything on that. Plese wait until the official archive; probably tomorrow, I have some tests to do.

**Comment by orthagh** [comment]
@Armin83 
Official release of glpi 9.1.1 is now available.

See https://github.com/glpi-project/glpi/releases/tag/9.1.1
The file: https://github.com/glpi-project/glpi/releases/download/9.1.1/glpi-9.1.1.tgz
