### ISSUE TITLE
9.5.9 - htmlawed not updated

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi#12982]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.9

### Bug description

Using the latest 9.5.9 the 3th party tool htmlawed is still the old version which hase a vulnerability. Please verify this urgently, vulnerability seems not fixed

**Comment by trasher** [comment]
https://glpi-project.org/security-update-10-0-3-and-9-5-9/

**Comment by cedric-anne** [comment]
I will delete your issue. If you think there is a critical vulnerability, please follow the [security policy](https://github.com/glpi-project/glpi/security/policy) instead of posting issue publicly.
