### ISSUE TITLE
Drop not needed empty sql files

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1298]
There is a bunch of "empty" SQL files thare are not relevant, since we're using a versionning system; they're removed in packaging scripts, they're removed in release script, and so on.

I guess we should drop them.

I also wonder if we should not only keep a empty file without any release in its name, it would be easier to maintain.

**Comment by remicollet** [comment]
I'm mostly +1

In this case, perhaps we should go further, and check current schema against   GLPI_VERSION.sha1file("empty.sql"))... to fix migration issue for git users...

Or having 2 cases, for git
* GLPI_VERSION=x.y.z-dev
* GLPI_SCHEMA=sha1file("empty.sql")

and, for release
* GLPI_VERSION=x.y.z
* GLPI_SCHEMA=GLPI_VERSION

**Comment by trasher** [comment]
A big +1 to go further and to prevent migration issues for git users... It is a nightmare :D
