### ISSUE TITLE
PC with Windows 8.1 not being inventoried

### ISSUE THREAD

**Issue by galarov** [glpi-project/glpi#12987]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

The issue was started here: https://github.com/glpi-project/glpi-agent/issues/243

Hello,

I've got the same problem with glpi-agent on Windows 8.1.

GLPI Server: GLPI 10.0.3
GLPI Agent: GLPI-Agent-1.4

Problem is as stated above: After installing the agent on a computer with Windows 8.1 inventorisation is done allright, but there is an error when the computer is trying to send the report to the server. I observe this problem on all Windows 8.1 computers (100+).

The GLPI installation is fresh - no upgrades or other modifications was applied. Just installed the serve, deployed agents and ran into this issue.

### Relevant log output

```shell
Agent side: glpi-agent log:
[Fri Oct 14 14:14:00 2022][info] target server0: server https://inventory.openbit.ru:40443/front/inventory.php
[Fri Oct 14 14:14:00 2022][info] sending prolog request to server0
[Fri Oct 14 14:14:00 2022][info] server0 answer shows it supports GLPI Agent protocol
[Fri Oct 14 14:14:03 2022][info] running task Collect
[Fri Oct 14 14:14:03 2022][error] [http client] authentication required, error status: 400 Bad Request
[Fri Oct 14 14:14:03 2022][info] Collect task not supported by server0
[Fri Oct 14 14:14:03 2022][info] running task ESX
[Fri Oct 14 14:14:03 2022][error] [http client] authentication required, error status: 400 Bad Request
[Fri Oct 14 14:14:03 2022][info] ESX task not supported by server0
[Fri Oct 14 14:14:05 2022][info] running task Deploy
[Fri Oct 14 14:14:05 2022][error] [http client] authentication required, error status: 400 Bad Request
[Fri Oct 14 14:14:05 2022][info] Deploy task not supported by server0
[Fri Oct 14 14:14:05 2022][info] running task Inventory
[Fri Oct 14 14:14:05 2022][info] New inventory from WS26-2022-10-12-12-38-07 for server0 (tag=ARKADIA)
[Fri Oct 14 14:14:43 2022][error] [http client] authentication required, error status: 500 Internal Server Error
[Fri Oct 14 14:14:43 2022][info] target server0: next run: Sat Oct 15 13:33:06 2022 - https://inventory.openbit.ru:40443/front/inventory.php
[Fri Oct 14 14:14:43 2022][info] GLPI Agent memory usage: WSS=3223552 PFU=167604224
[Fri Oct 14 14:14:43 2022][info] running task Deploy: storage maintenance event

Server side: /var/log/httpd/ssl_error_log:
[Fri Oct 14 14:14:48.037754 2022] [php:warn] [pid 1662] [client 176.32.182.186:50007] PHP Warning:  Undefined array key "nok_k7ok7eAQ4y$$$$1360" in /var/www/glpi/src/Inventory/Asset/Software.php on line 714
[Fri Oct 14 14:14:48.038095 2022] [php:error] [pid 1662] [client 176.32.182.186:50007] PHP Fatal error:  Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1961
```

### Steps To reproduce

Install on PC with Windows 8.1 GLPI-Agent-1.4-x64
Force inventory

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.3 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.openbit.ru 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64
PHP 8.1.10 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring,
	memcache, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, session, shmop, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/8.1.10 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
Server Software: MariaDB Server
	Server Version: 10.9.2-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.9.2) is supported.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to files directory is protected
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

### Anything else?

As was suggested here I updated the server up to 10.0.3 version.

Then tried to reproduce issue importing the JSON file directly in the GLPI web UI.
[inventory.zip](https://github.com/glpi-project/glpi/files/9786334/inventory.zip)

Server side log for that:
[Fri Oct 14 15:22:22.680951 2022] [php:warn] [pid 1670] [client 10.100.0.61:52850] PHP Warning:  Undefined array key "nok_Qv2XWRo5Gt$$$$1570" in /var/www/glpi/src/Inventory/Asset/Software.php on line 714, referer: https://glpi.openbit.ru/front/inventory.conf.php?forcetab=Glpi\\Inventory\\Conf$2
[Fri Oct 14 15:22:22.681246 2022] [php:error] [pid 1670] [client 10.100.0.61:52850] PHP Fatal error:  Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1961, referer: https://glpi.openbit.ru/front/inventory.conf.php?forcetab=Glpi\\Inventory\\Conf$2

**Comment by trasher** [comment]
I'm able to reproduce on latest nightly with provided inventory file.

**Comment by trasher** [comment]
Problem is you have an encoding issue in your inventory file. This is an agent issue that has already been fixed as far as I know; you should update agent and try again.

**Comment by galarov** [comment]
Thank you for the investigation.

But GLPI-Agent's version is 1.4. Which is the latest. Should I go back to GLPI-agent repo with this issue?

Could you please give more details, so that they understand right away what the problem is?

**Comment by trasher** [comment]
Just take a look at your inventory file, there are lots of unknonw characters. GLPI cannot handle that file correctly.

As of the agent issue, I really do not know, that's what I've heard, but the file is incorrect, this is an agent issue, and not a GLPI one.
You may try with a agent nightly build, and if you reproduce, open an issue on agent repository.

**Comment by galarov** [comment]
Thank you. I will try.

**Comment by galarov** [comment]
Yes, indeed, I'm able to import json reports from GLPI-agent-1.5 and Computer item appears. Though inventory report still doesn't come when I click "Force Inventory" on the workstation. There is still the same error:
Client-side:
[Mon Oct 24 18:50:16 2022][info] running task Inventory
[Mon Oct 24 18:50:16 2022][info] New inventory from ws17-2022-10-12-12-47-29 for server0 (tag=ARKADIA)
[Mon Oct 24 18:50:37 2022][error] [http client] authentication required, error status: 500 Internal Server Error
[Mon Oct 24 18:50:39 2022][info] running task ESX

Server side:
[Mon Oct 24 18:50:19.871933 2022] [php:warn] [pid 115993] [client 176.32.182.186:59424] PHP Warning:  Undefined array key "nok_ooE6tlcSoj$$$$12668" in /var/www/glpi/src/Inventory/Asset/Software.php on line 714
[Mon Oct 24 18:50:19.872207 2022] [php:error] [pid 115993] [client 176.32.182.186:59424] PHP Fatal error:  Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1961

**Comment by galarov** [comment]
Those exclamation mark characters from your view are just Russian characters presented with wrong encoding. Anyway, GLPI receives them gracefully via json import. Looks like Russian characters is not the issue here.

**Comment by stonebuzz** [comment]
Can you retry with GLPI nightly build and GLPI-Agent 1.5 ?

```ssh
[Mon Oct 24 18:50:19.871933 2022] [php:warn] [pid 115993] [client 176.32.182.186:59424] PHP Warning: Undefined array key "nok_ooE6tlcSoj$$$$12668" in /var/www/glpi/src/Inventory/Asset/Software.php on line 714
[Mon Oct 24 18:50:19.872207 2022] [php:error] [pid 115993] [client 176.32.182.186:59424] PHP Fatal error: Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1961
```
This error seems to be fixed (I don't reproduce on my side)


Best regards

**Comment by stonebuzz** [comment]
Can you post here new inventory file (from GLPI-Agent 1.5)?

Best regards

**Comment by galarov** [comment]
Here is a new inventory file from Windows 8.1 made by GLPI-Agent_v1.5-git2519c10c. This file won't be imported by GLPI Server 10.0.3. Though if you import it using inject tool (xml, json), the process will be a success and the Computer item will appear. It is a progress, because a report from GLPI-Agent_1.4 wouldn't work via inject tool either. 
[ws18_agent_1.5_inventory.zip](https://github.com/glpi-project/glpi/files/9866510/ws18_agent_1.5_inventory.zip)

**Comment by galarov** [comment]
> Can you retry with GLPI nightly build and GLPI-Agent 1.5 ?
> 
> https://nightly.glpi-project.org/glpi/
> 
> ```
> [Mon Oct 24 18:50:19.871933 2022] [php:warn] [pid 115993] [client 176.32.182.186:59424] PHP Warning: Undefined array key "nok_ooE6tlcSoj$$$$12668" in /var/www/glpi/src/Inventory/Asset/Software.php on line 714
> [Mon Oct 24 18:50:19.872207 2022] [php:error] [pid 115993] [client 176.32.182.186:59424] PHP Fatal error: Column 'softwares_id' cannot be null in /var/www/glpi/src/DBmysql.php on line 1961
> ```
> 
> This error seems to be fixed (I don't reproduce on my side)
> 
> Best regards

I will do this experiment on Saturday. It's hard to find time on a work day. I will get back.

**Comment by trasher** [comment]
> Here is a new inventory file from Windows 8.1 made by GLPI-Agent_v1.5-git2519c10c. This file won't be imported by GLPI Server 10.0.3. Though if you import it using inject tool (xml, json), the process will be a success and the Computer item will appear. It is a progress, because a report from GLPI-Agent_1.4 wouldn't work via inject tool either. [ws18_agent_1.5_inventory.zip](https://github.com/glpi-project/glpi/files/9866510/ws18_agent_1.5_inventory.zip)

I confirm this file is successfully imported:
![image](https://user-images.githubusercontent.com/224733/197949114-be17e97b-5cf1-4110-b5cf-3208bec23235.png)
