### ISSUE TITLE
[GLPI 10.0.3] Problem on the IMAP collector with office 365

### ISSUE THREAD

**Issue by Wacxiuz** [glpi-project/glpi#12999]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.3

### Bug description

Hello,
After updating to version 10.0.3, I noticed that my collector with Office 365 no longer worked.
IMAP is still enabled on the exchange.
The password has not changed.
However, I got the following error:

[2022-10-17 09:51:41] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot login, user or password wrong in /var/www/glpi/vendor/laminas/laminas-mail/src/Storage/Imap.php at line 225
  Backtrace :
  src/Toolbox.php:2155                               Laminas\Mail\Storage\Imap->__construct()
  src/MailCollector.php:1375                         Toolbox::getMailServerStorageInstance()
  src/MailCollector.php:698                          MailCollector->connect()
  front/mailcollector.form.php:103                   MailCollector->collect()

![image](https://user-images.githubusercontent.com/83710370/196122174-0bf2f3e3-f21d-446c-a6ca-f3458fc2e531.png)

**Comment by cedric-anne** [comment]
Depending on how you updated you GLPI, it is possible that GLPI creates a new encryption key. In this case, password that are encrypted in GLPI are no longer readable.

There is 2 solutions:
 - you can either try to restore the `config/glpicrypt.key` from your previous installation, if you did not yet reset some password (LDAP, IMAP, SMTP, ...),
 - input the password in your collector config and save the form to force value in DB to be fixed.

**Comment by Wacxiuz** [comment]
> Depending on how you updated you GLPI, it is possible that GLPI creates a new encryption key. In this case, password that are encrypted in GLPI are no longer readable.
> 
> There is 2 solutions:
> 
>     * you can either try to restore the `config/glpicrypt.key` from your previous installation, if you did not yet reset some password (LDAP, IMAP, SMTP, ...),
> 
>     * input the password in your collector config and save the form to force value in DB to be fixed.

Hello,

The glpycrypt file was not changed despite the update. So I left it as is.

I also re-entered the password, but nothing changed.

**Comment by Wacxiuz** [comment]
Hello,
it's okey with Oauth IMAP

**Comment by jmldsilva** [comment]
Hello, did you upgrade the PHP

**Comment by dondadmin** [comment]
Make sure your Office 365 account has IMAP enabled.
