### ISSUE TITLE
Ticket Section in Self-Service is showing duplicated loading animation

### ISSUE THREAD

**Issue by stimpfo** [glpi-project/glpi#12994]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello everyone,

while I was setting up my ticketing system, the display of avaible tickets in the self-service profile is showing multiple loading spinners and the "sections" for those are stretched vertically.

He is an image so you know what I mean: imgur.com/a/8wH0jSG

I didn't change anything in the layout. Anyone here who saw this before and can help? I don't know if it's a PHP or CSS problem.

Thanks in advance.

**Comment by stimpfo** [comment]
Additionally, I found these lines of code that act (in my opinion) a bit weird. 
![Code_Snippit_GLPI](https://user-images.githubusercontent.com/51911806/196106865-38cbc232-d588-44a8-9ee3-96975f2cbfb0.png)

**Comment by cedric-anne** [comment]
Fixed by #13248.
