### ISSUE TITLE
By removing your group from "Assigned to" on tickets when transferring to another group, should not receive ticket notification (email) as they don't have permissions

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#12998]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When transferring a ticket to another group and removing our group from "Assigned to", the removed group is taking an email which is not useful as there is no longer access to the ticket.

### Steps To reproduce

1. From ticket remove your group from Actors - "Assigned to"
2. Add another group to the "Assigned to"
3. Click on save

There is an email notification to the removed group without indicating that the group is removed, but I think that there should not be an email as there is no longer permission to the ticket.

**Comment by LeFouineur** [comment]
It depends how you use GLPI.
For example, if you have two differents teams and you pass the ticket on the second one, it can be interesting for the first one to know that the ticket isn't attributed to them anymore and was passed over.

I think, it could be preferable to use the rule of recipients for email's notifications, and have two objects : old and new assigned (wether it's an user or a group).

**Comment by dxdemetriou** [comment]
It depends. If the transferring is from the support team, then everything it's because they are forwarding to the right group. We had every group as watcher in the past and with email rule, but nobody checked them, also if is there also the regular email then is not usable on mobile devices. For users it's solved by the "Assigned to". For groups I couldn't found any way to separate what is leaved and what comes.

**Comment by dxdemetriou** [comment]
Actually, the question is why there is no a notification icon on groups like on users? If it was a notification icon, then we could just unchecked it, save, and then remove the group. At least with this, it's solved the one part. The other part is about notifications, how it's possible to be defined if your group is included or removed.
