### ISSUE TITLE
Improve cartridges display

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#13000]
It is OK for me on the technical side but I wonder if the UX could be improved.

As a reminder, these "virtuals" searchoptions can't be used as search criteria - they are only used in display preferences.
This mean that someone who want to access this information will need to display 16 huge columns (8 for drum + 8 for toner).
On top of that, most of these columns will be empty but they will still take about 1/5 of your screen per column:

![image](https://user-images.githubusercontent.com/42734840/195848415-fe9e7959-80ec-42be-967c-fd3c590d07a2.png)

I wonder if a single "cartridge information" search option would be more usable.
It could compact all the information in a single column and show only the relevant data (no need to display empty values).
Note that if we choose to do this, it should probably be validated by the internal ref client as it was a paid development.

_Originally posted by @AdrienClairembault in https://github.com/glpi-project/glpi/issues/12986#issuecomment-1278955729_

**Comment by AdrienClairembault** [comment]
Good reminder, I'll put @ccailly on it :)

Maybe we need to validate the UI/UX first ?
I'd suggest two search options (one for all cartridges information and one for all toner information).
We can then display the values using one badge per supported color:

![image](https://github.com/glpi-project/glpi/assets/42734840/5551eca4-7e64-4a83-80f7-38dfe5813390)

Color names could be omitted to gain more space at a small readability cost:

![image](https://github.com/glpi-project/glpi/assets/42734840/cd9ca399-221c-4355-9c38-91ffaced48f1)

Badges could also be replaced by some progress bar which are filled using the given percentages (but be wary that values may also be row text like "OK" - maybe fill the bar completely in this case ?).
It may be a bit harder to implement so my first preference would still be the nameless color badges.

@orthagh @cedric-anne @trasher Any preferences or others suggestions ?

**Comment by cconard96** [comment]
Having only the background color to differentiate them will add accessibility difficulties (color blindness, reduced contrast, etc).

There should be an `aria-label` on them with the color name for those who rely on screen readers but it doesn't really help people with vision deficiencies that don't usually require the use of a screen reader.

Another option is showing the first letter of the color while the full color name is in an `aria-label`/tooltip, but this has other issues like conflicts where two colors share the same first letter or the letter is ambiguous. For example "B" could be blue or black and depending on the color chosen to represent blue, it may look black to some people.

In Chrome, you can add the Rendering tab to the developer tools window and change the "Emulate vision deficiencies" option to get an idea of how someone with various conditions may see these colors/info.

Showing the full name or at least the first N characters seems like the only good way to handle this.
