### ISSUE TITLE
do not list ticket

### ISSUE THREAD

**Issue by paulo-dambros** [glpi-project/glpi#13008]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

GLPI is not displaying open and in progress tickets for a profile of a unit.

---
Sorry for google translate

### Page URL

https://atendimento.unemat.br/front/ticket.php

### Steps To reproduce

When clicking Assistance >> Tickets and applying a filter for open or unresolved tickets, GLPI does not list tickets of this type.

It stays on the screen for hours as if it was looking for tickets, but it doesn't list anything.

For pending and in service status, the filter is executed.

see the gif:
https://user-images.githubusercontent.com/30637210/196252391-317a163b-719a-4759-ad6f-c2acc1365e0d.mp4

### Your GLPI setup information

GLPI 10.0.2 ( => /var/www/atendimento/public)
Installation mode: TARBALL
Current language:pt_BR

**Comment by cconard96** [comment]
Please check the GLPI logs. Specifically `files/_log/php-errors.log` and `files/_log/sql-errors.log`. Also, since the search request is sent in the background now instead of a full page reload, please check the browser console (F12 key > console tab) for warnings/errors as well.

**Comment by paulo-dambros** [comment]
Ok, the browser error:

https://user-images.githubusercontent.com/30637210/196257205-9249e6c0-0f83-4217-9286-a22bc8f15461.mp4

I will collect the log errors

**Comment by paulo-dambros** [comment]
2022-10-17 16:21:56] glpiphplog.CRITICAL:   * Uncaught Exception Error: Undefined constant "PLUGIN_FUSIONINVENTORY_VERSION" in /var/www/atendimento/public/plugins/fusioninventory/front/communication.php at line 72
  Backtrace :
  plugins/fusioninventory/index.php:59               include_once()

022-10-17 16:25:19] glpiphplog.WARNING:   * PHP Warning (2): sha1_file(/var/www/atendimento/public/files/_tmp/5eb3fef7aed0f4.61556415image_paste201879.png): Failed to open stream: No such file or directory in /var/www/atendimento/public/src/Document.php at line 642
  Backtrace :
  src/Document.php:642                               sha1_file()
  src/Document.php:1886                              Document->getFromDBbyContent()
  ...rmcreator/inc/field/textareafield.class.php:208 Document->getDuplicateOf()
  ...place/formcreator/inc/formanswer.class.php:1072 GlpiPlugin\Formcreator\Field\TextareaField->serializeValue()
  src/CommonDBTM.php:1305                            PluginFormcreatorFormAnswer->post_addItem()
  marketplace/formcreator/ajax/formanswer.php:58     CommonDBTM->add()

**Comment by paulo-dambros** [comment]
We deleted the fusion folder and increased the memory in php.ini

**Comment by paulo-dambros** [comment]
Memory in php.ini ok.
1gb.

**Comment by trasher** [comment]
Please also note 10.0.2 has known security issues; consider upgrading.

**Comment by paulo-dambros** [comment]
yea. update on the way.
thanks.

Em ter., 18 de out. de 2022 01:03, Johan Cwiklinski <
***@***.***> escreveu:
