### ISSUE TITLE
Error while listing actors on tickets

### ISSUE THREAD

**Issue by brusilva84** [glpi-project/glpi#13007]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When I try to change the requester  / observer or techinician it just says "Searching" and doesnt list avaiable options
This only happens on recent tickets. I mean tickets created after the 10.0.3 update not on older ones.

### Relevant log output

```shell
*** PHP Warning (2): Undefined array key "action" in /var/www/html/glpi/ajax/actors.php at line 41
```

### Steps To reproduce

Just try to assign a ticket to another requester

### Your GLPI setup information

GLPI 10.0.3 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:pt_PT

### Anything else?

This happened after 10.0.3 upgrade via CLI

**Comment by cconard96** [comment]
I am not able to recreate the issue.
Can you open the developer panel in your browser (F12 key) and then go to the Network tab. Try clicking in one of the actor fields, and you should se a request being made for "actors.php". Can you click that request and see what the "params" or "payload" being sent to GLPI is?
