### ISSUE TITLE
Personal view showing empty horizontal lines after clicking on 'All' tab

### ISSUE THREAD

**Issue by scylla999** [glpi-project/glpi#13009]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

Personal View shows empty horizontal lines after in 'All' tab:

![GLPI-bug01](https://user-images.githubusercontent.com/24919069/196264870-0cc7e877-911f-4775-981b-e7874cf9d1de.png)

Here's what it looks like if I re-select only 'Personal View':

![GLPI-bug02](https://user-images.githubusercontent.com/24919069/196267136-9d96990e-223d-4ee0-a105-a821577c22b2.png)

### Steps To reproduce

1. Migrate GLPI from 9.5.7 to 10.0.3
2. Log on with 'admin' profile user
3. Click on 'Personal View' -> correct display
4. Click on 'All' -> 'Personal View' contains horizontal lines.

### Your GLPI setup information

Operating system: Linux 4.18.0-408.el8.x86_64 #1 SMP Mon Jul 18 17:42:52 UTC 2022 x86_64
PHP 7.4.30 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, pdo_sqlsrv, posix, session, shmop, sockets, sqlite3, sqlsrv, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.37 (centos) OpenSSL/1.1.1k mod_perl/2.0.12 Perl/v5.26.3 ()
	Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0
Server Software: MariaDB Server
	Server Version: 10.5.17-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.PHP version (7.4.30) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.17) is supported.Database engine version (10.5.17) is supported.
The log file has been created successfully.The log file has been created successfully.
Write access to /home2/www/secure_html/glpi/files/_cache has been validated. Write access to /home2/www/secure_html/glpi/config has been validated. Write access to /home2/www/secure_html/glpi/files/_cron has been validated. Write access to /home2/www/secure_html/glpi/files has been validated. Write access to /home2/www/secure_html/glpi/files/_dumps has been validated. Write access to /home2/www/secure_html/glpi/files/_graphs has been validated. Write access to /home2/www/secure_html/glpi/files/_lock has been validated. Write access to /home2/www/secure_html/glpi/files/_pictures has been validated. Write access to /home2/www/secure_html/glpi/files/_plugins has been validated. Write access to /home2/www/secure_html/glpi/files/_rss has been validated. Write access to /home2/www/secure_html/glpi/files/_sessions has been validated. Write access to /home2/www/secure_html/glpi/files/_tmp has been validated. Write access to /home2/www/secure_html/glpi/files/_uploads has been validated.Write access to /home2/www/secure_html/glpi/files/_cache has been validated.
Write access to /home2/www/secure_html/glpi/config has been validated.
Write access to /home2/www/secure_html/glpi/files/_cron has been validated.
Write access to /home2/www/secure_html/glpi/files has been validated.
Write access to /home2/www/secure_html/glpi/files/_dumps has been validated.
Write access to /home2/www/secure_html/glpi/files/_graphs has been validated.
Write access to /home2/www/secure_html/glpi/files/_lock has been validated.
Write access to /home2/www/secure_html/glpi/files/_pictures has been validated.
Write access to /home2/www/secure_html/glpi/files/_plugins has been validated.
Write access to /home2/www/secure_html/glpi/files/_rss has been validated.
Write access to /home2/www/secure_html/glpi/files/_sessions has been validated.
Write access to /home2/www/secure_html/glpi/files/_tmp has been validated.
Write access to /home2/www/secure_html/glpi/files/_uploads has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
Sessions configuration is secured.Sessions configuration is secured.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is not present.zip extension is not present.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring. Following extensions are not present: sodium.Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /home2/www/secure_html/glpi/marketplace has been validated.Write access to /home2/www/secure_html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cconard96** [comment]
This may be fixed by #12953 (work in progress).

**Comment by cedric-anne** [comment]
@AdrienClairembault 

Was this fixed by 12953?

**Comment by scylla999** [comment]
Yes, it seems fixed now.   Thanks!
