### ISSUE TITLE
9.2 : RandomLib high strengh generator required

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1301]
Hi

With GLPi 9.2 I encouteer an exception when a plugin attempts to generate a user token

```
[Wed Nov 16 09:43:57.784329 2016] [:error] [pid 5648] [client ::1:57014] PHP Fatal error:  Uncaught RuntimeException: Could not find mixer in /var/www/html/glpi/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php:237
Stack trace:\n#0 /var/www/html/glpi/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php(78): RandomLib\\Factory->findMixer(Object(SecurityLib\\Strength))
#1 /var/www/html/glpi/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php(94): RandomLib\\Factory->getGenerator(Object(SecurityLib\\Strength))
#2 /var/www/html/glpi/inc/toolbox.class.php(1574): RandomLib\\Factory->getHighStrengthGenerator()
#3 /var/www/html/glpi/inc/user.class.php(4050): Toolbox::getRandomString(40, true)
#4 /var/www/html/glpi/inc/user.class.php(4079): User::getUniquePersonalToken()
#5 /var/www/html/glpi in /var/www/html/glpi/vendor/ircmaxell/random-lib/lib/RandomLib/Factory.php on line 237
```

RandomLib is used with a high strength generator. I solved the error by installing the PHP extension mcrypt. My GLPi was upgraded from 9.1 to 9.2 today, and there was no warning about the lack of high strengh generator. 

Therefore, I think GLPi should  check at least one high strenght generator is available at install / upgrade time.

**Comment by remicollet** [comment]
mcrypt is the worst possible choice.... haven't you the openssl extension ?
which OS ?
Even /dev/random provides Strength::HIGH

See: https://blog.remirepo.net/post/2015/07/07/About-libmcrypt-and-php-mcrypt

**Comment by remicollet** [comment]
perhaps a try / catch switching to not HIGH sources.... for bad env....

**Comment by btry** [comment]
Yes I have the openssl extension ! Then you confirm this exception is strange !

OS : Debian Stretch, PHP 7.0

**Comment by btry** [comment]
Thank you : I removed mcrypt and this works
