### ISSUE TITLE
 "Assigned to" problem in ticket when add a group with onlynumbers name

### ISSUE THREAD

**Issue by tlombardini** [glpi-project/glpi#13034]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi, I am having a problem in GLPI 10.0.3.

I created some user groups. When i add a group as a "asigned to" in a ticket (if the group has only numbers as name) then I have problems in the input area of "asigned to".  After add the "only number group" as assigned, then I cant modify the asigned people or groups. I becomes buggy.

Problematic group name example "365".

Do you need more info?
Thank you

### Steps To reproduce

1. Create user group with a only numers name, example: "365"
2. Create a ticket and add to "Assigned to" that group.
3. Save changes
4. Try to modify assigned groups, techs, etc. I am having an view error in the input and don't take any changes after add a "only numbers name group".

### Your GLPI setup information

GLPI 10.0.3 ( => /var/www/html)
Installation mode: TARBALL
Current language:en_GB

Operating system: Linux sti 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64
PHP 8.1.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Apache/2.4.38 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.23
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION

**Comment by trasher** [comment]
I confirm I can reproduce that issue on current 10.0/bugfixes branch

**Comment by tlombardini** [comment]
mi first reported bug ! 😊

**Comment by cconard96** [comment]
Link to the forum post:
https://forum.glpi-project.org/viewtopic.php?id=285177

**Comment by tlombardini** [comment]
Thank you guys !

**Comment by cconard96** [comment]
Was the browser cache cleared?

**Comment by trasher** [comment]
> Was the browser cache cleared?

Well catched, forcing reload clearing cache makes things work :)
