### ISSUE TITLE
impossible to download 9.1.1

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1303]
https://github.com/glpi-project/glpi/releases/download/9.1.1/glpi-9.1.1.tar.gz

![image](https://cloud.githubusercontent.com/assets/15144026/20347500/c610fb60-ac01-11e6-8b53-dead0d59dfd4.png)

**Comment by fgendorf** [comment]
https://github.com/glpi-project/glpi/releases/download/9.1.1/glpi-9.1.1.tgz

**Comment by trasher** [comment]
Link in description was bad, fixed, thanks.
