### ISSUE TITLE
Rule not work properly, cannot add multiple technician to same ticket

### ISSUE THREAD

**Issue by godsom** [glpi-project/glpi#13035]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.8

### Bug description

as I use  previous version 9.5.3 I can use rules to auto assign a technician to a ticket once it created and can add other technician at same time like 3 persons
then I upgrade to 9.5.8 at same rule it have some thing wrong as rule with  action to assign technician 1 assign and 2 add persons but result is just 1 assign and 1 add technician.
then I try to edit  that rule result go worse it automatic assign only 1 technicial at first line other 2 add technician not come together.  

### Steps To reproduce

1. goto Business Rules for Tickets
2. goto some rule with action have multiple technician
3. edit action or just save.
4. test rule or try to create new ticket with rule criteria.
5. result it not same as 9.5.3 version

**Comment by cedric-anne** [comment]
Hi,

The `assign` action will replace actors that were newly `added` and/or `assigned` from UI and/or rules. If you want to add 3 actors whith the same role, you have to use `add` action instead of `assign`.

**Comment by godsom** [comment]
> Hi,
> 
> The `assign` action will replace actors that were newly `added` and/or `assigned` from UI and/or rules. If you want to add 3 actors whith the same role, you have to use `add` action instead of `assign`.

Hi.I already try with rule for add 3 actor in same rule. but it add only first add actor in a rule.
<img width="761" alt="Screen Shot 2565-10-21 at 14 10 32" src="https://user-images.githubusercontent.com/5634204/197135180-5085adeb-c645-4e61-82e3-9e88dd5690fd.png">

**Comment by Squikou** [comment]
Hi,
Same problem in our GLPI. We did not have the problem in 9.5.7 but since the pass in 9.5.9, .10 and .11, we have this behavior. Very judicious in our activity with regard to customer notifications.
Thanks
