### ISSUE TITLE
Editing a planned task does not take into account the previously saved dates

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#13041]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0/bugfixes

### Bug description

When editing the planned date of a task, the dates of the planning are not taken into account: the date is set to "now" instead of the value from the DB

Here is a task with a planned date (visible on the bottom)
![image](https://user-images.githubusercontent.com/14139801/197137854-01ac32d5-e73b-4510-bad3-d1cb3aaae9e6.png)

Now I try to edit it
![image](https://user-images.githubusercontent.com/14139801/197138004-726d67a8-563d-45b8-9492-e6ad9bf432b9.png)

I click on "Plan this task", let's say to add a reminder I forgot to set.
![image](https://user-images.githubusercontent.com/14139801/197138278-884fab60-1112-4441-9723-aa8f7b300252.png)

Notice that the date saved in the DB is not used to initialize the datetime picker.

### Page URL

front/ticket.form.php?id=150

### Steps To reproduce

1. Create a ticket
2. Add a task and plan it to a date a few days later. Save it
3. Edit again the task, click the "Plan this task" button.
4. The planned date is not reused.

**Comment by cedric-anne** [comment]
Fixed by#13223.
