### ISSUE TITLE
Spell check GLPI 10.0.X

### ISSUE THREAD

**Issue by Rafaeldgs** [glpi-project/glpi#13059]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

In previous versions, there was a spell check option in the accompaniments/solutions, in version 10, there is no longer the option.

![2022-10-25_11-15(2)](https://user-images.githubusercontent.com/88557932/197799296-6dd607aa-db27-4d38-aecd-3ee11893ea09.jpg)
![2022-10-25_11-15(3)](https://user-images.githubusercontent.com/88557932/197799312-3a5103bd-80ba-4ad7-8133-e25bf8a210bc.jpg)

### Steps To reproduce

1. Write a misspelled word in accompaniment/solution
2. Direct button open correction suggestion
3. In version 10, it no longer suggests

### Your GLPI setup information

GLPI - 10.0.3

**Comment by cedric-anne** [comment]
You can use CTRL+click to display browser menu.
In next GLPI version, #12804 will put back previous behaviour by default.

**Comment by Rafaeldgs** [comment]
OK thank you !

**Comment by Rafaeldgs** [comment]
> Você pode usar CTRL+clique para exibir o menu do navegador. Na próxima versão do GLPI, #12804 retornará o comportamento anterior por padrão.

OK thank you !
