### ISSUE TITLE
Error see detail of the modified ticket

### ISSUE THREAD

**Issue by esstampida** [glpi-project/glpi#13062]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.0

### Bug description

When I modify a ticket, I stop seeing the details, this problem has happened to me when I recreated a user that had previously existed, but I unsubscribed it before because it stopped working for us

![image](https://user-images.githubusercontent.com/78594964/197962320-96fc0152-da24-42f4-8a64-2e5bd3807026.png)

### Steps To reproduce

1. create tiquet
2. modify tiquet
3.  i can't see details tiquet

**Comment by esstampida** [comment]
Sorry, this is the first time that there will be an incident, what information is missing?

**Comment by esstampida** [comment]
Sorry, this is the first time that there will be an incident, what information is missing?

**Comment by trasher** [comment]
You have to fill all requested information, or explicitly tell if this is not relevant in your case. Also, last version is 10.0.3, you have to upgrade.

**Comment by cedric-anne** [comment]
> Sorry, this is the first time that there will be an incident, what information is missing?

You have not given the requested information on 3/4 of the form:

![image](https://user-images.githubusercontent.com/33253653/197984220-0d480d9b-26e7-4676-9ffd-292403fae34f.png)
