### ISSUE TITLE
Error on statics visualization

### ISSUE THREAD

**Issue by barte91** [glpi-project/glpi#13069]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.3

### Bug description

Hi All,

I've problem with some visualization, example: I don't see the statitcs bar on home page (see image in attachment)

Anyone can help me, please?
![ErrorGLPI](https://user-images.githubusercontent.com/19166634/197993609-f6cf5279-bb67-4488-8782-069e67b9bc15.png)

 Can be a problem by PHP or in the HTTPD config?

here my config on vhost

`        DocumentRoot "/var/www/"
        Alias /glpi /var/www/glpi
        ErrorLog "/var/log/httpd/glpi-error_log"
        CustomLog "/var/log/httpd/glpi-access_log" combined

        <Directory /var/www/glpi/config>
                AllowOverride None
                Require all denied
        </Directory>

        <Directory /var/www/glpi/files>
                AllowOverride None
                Require all denied
        </Directory>`

### Relevant log output
HTTPD error

`[Tue Oct 18 17:14:07.822397 2022] [proxy_fcgi:error] [pid 886:tid 1087] [client 192.168.100.23:53806] AH01071: Got error 'Primary script unknown', referer: http://netglpi/glpi/front/networkport.form.php?id=7956
[Tue Oct 18 17:14:19.337235 2022] [proxy_fcgi:error] [pid 1098:tid 1142] [client 192.168.100.23:53809] AH01071: Got error 'Primary script unknown', referer: http://netglpi/glpi/front/networkport.form.php?id=7956
[Wed Oct 19 09:25:56.926018 2022] [proxy_fcgi:error] [pid 1098:tid 1142] [client 192.168.100.23:50437] AH01071: Got error 'Primary script unknown', referer: http://netglpi/glpi/front/networkport.form.php?id=7940
[Mon Oct 24 14:03:40.031462 2022] [proxy_fcgi:error] [pid 1098:tid 1149] [client 192.168.100.6:52064] AH01071: Got error 'Primary script unknown', referer: http://netglpi/glpi/front/networkport.form.php?id=8467
[Wed Oct 26 11:44:30.676612 2022] [authz_core:error] [pid 884:tid 1050] [client 192.168.100.71:45970] AH01630: client denied by server configuration: /var/www/glpi/files/_log/php-errors.log`

PHP error

`[2022-10-26 09:25:55] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/var/www/glpi/files/_log/cron.log): Failed to open stream: Permission denied in /var/www/glpi/src/Toolbox.php at line 574
  Backtrace :
  src/Toolbox.php:574                                error_log()
  src/CronTask.php:1064                              Toolbox::logInFile()
  front/cron.php:64                                  CronTask::launch()

[2022-10-26 09:32:09] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/var/www/glpi/files/_log/cron.log): Failed to open stream: Permission denied in /var/www/glpi/src/Toolbox.php at line 574
  Backtrace :
  src/Toolbox.php:574                                error_log()
  src/CronTask.php:1064                              Toolbox::logInFile()
  front/cron.php:64                                  CronTask::launch()

[2022-10-26 09:44:28] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/var/www/glpi/files/_log/cron.log): Failed to open stream: Permission denied in /var/www/glpi/src/Toolbox.php at line 574
  Backtrace :
  src/Toolbox.php:574                                error_log()
  src/CronTask.php:1064                              Toolbox::logInFile()
  front/cron.php:64                                  CronTask::launch()

[2022-10-26 09:44:30] glpiphplog.WARNING: Test logger
[2022-10-26 09:44:30] glpiphplog.WARNING:   *** PHP Warning (2): Array to string conversion in /var/www/glpi/src/Config.php at line 2073
  Backtrace :
  src/Config.php:2218                                Config::showSystemInfoTable()
  src/Config.php:2687                                Config->showSystemInformations()
  src/CommonGLPI.php:689                             Config::displayTabContentForItem()
  ajax/common.tabs.php:113                           CommonGLPI::displayStandardTab()
`

### Steps To reproduce

In home page with SuperAdmin user

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.3 (/glpi => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux NetSrv-glpi.netproject.local 5.14.0-171.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Sat Oct 1 12:56:27 UTC 2022
	x86_64
PHP 8.1.11 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json, ldap, libxml,
	mbstring, memcache, memcached, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, redis, session, sockets, sodium,
	sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.53 (CentOS Stream) OpenSSL/3.0.1 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Server Software: Source distribution
	Server Version: 8.0.30
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
Web access to files directory is protected
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /var/www/glpi/config
GLPI_VAR_DIR: /var/www/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/www/glpi/files
GLPI_CACHE_DIR: /var/www/glpi/files/_cache
GLPI_CRON_DIR: /var/www/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/glpi/files/_lock
GLPI_LOG_DIR: /var/www/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads
GLPI_INVENTORY_DIR: /var/www/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (glpi@net-project.net@smtp.office365.com)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.18.0     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.1      State: Enabled                                 
		Install Method: Marketplace
	notifications        Name: Notifications                  Version: 9.4+1.0    State: Not installed                           
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

Have you some error in the browser console (use F12 key to open it) ?

**Comment by barte91** [comment]
Hi,

I see this in browser console

![ErrorGLPI-console](https://user-images.githubusercontent.com/19166634/198016963-2c4f6144-648d-46ec-a9ae-8d7b6f739435.png)

**Comment by cedric-anne** [comment]
Can you check the network tab of your browser to see if there is any error ?
Also, is there any log added to `files/_log/php-errors.log` when page is displayed ?

**Comment by cedric-anne** [comment]
Can you try to install [current nighly build](https://nightly.glpi-project.org/glpi/) on a test server to see if problem persist ?

**Comment by barte91** [comment]
Hi 

I need to create a VM and try this, but I think tehere is any error on Vhost in HTTPD
I see this:
If I go on my device in Network Device then I modified the netwrok port; then I click on list button, I've this error:

`file not found` (with this url http://netglpi/glpi/front/networkport.php)

**Comment by cconard96** [comment]
> Hi
> 
> I need to create a VM and try this, but I think tehere is any error on Vhost in HTTPD I see this: If I go on my device in Network Device then I modified the netwrok port; then I click on list button, I've this error:
> 
> `file not found` (with this url http://netglpi/glpi/front/networkport.php)

That is a different bug that was already fixed for the upcoming 10.0.4 version:
#12675
There isn't a search page for network ports so the list button should have been hidden.

**Comment by barte91** [comment]
I found an error with association of plugin in my enviroment, I close the ticket, all works fine

Thanks for support
