### ISSUE TITLE
[GLPI 10.0.3] LDAP Filter multiline string

### ISSUE THREAD

**Issue by J-C-P** [glpi-project/glpi#13065]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi,
LDAP Filter used in LDAP Authentication stores multiline string but it doesn't work.
It is possible to store
```
(&	(objectClass=user)
	(objectCategory=person)
	(!(userAccountControl:1.2.840.113556.1.4.803:=2))
	(|
		(memberOf=CN=Group01,OU=roles,OU=groups,DC=company,DC=local)
		(memberOf=CN=Group02,OU=roles,OU=groups,DC=company,DC=local)
		(memberOf=CN=Group03,OU=roles,OU=groups,DC=company,DC=local)
		(memberOf=CN=Group04,OU=roles,OU=groups,DC=company,DC=local)
	)
)
```
but it doesn't work unless it is stored like this
```(&	(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(|(memberOf=CN=Group01,OU=roles,OU=groups,DC=company,DC=local)(memberOf=CN=Group02,OU=roles,OU=groups,DC=company,DC=local)(memberOf=CN=Group03,OU=roles,OU=groups,DC=company,DC=local)(memberOf=CN=Group04,OU=roles,OU=groups,DC=company,DC=local)))```

### Anything else?

The first option is a lot easier to read but doesn't work.
I guess it should be possible to strip the string from unwanted characters before using it internally.

Have a good day,
JC

**Comment by cedric-anne** [comment]
Hi,

Does this kind of string would work if you pass it directly in a LDAP system command ?

**Comment by J-C-P** [comment]
It depends of the tool :-/
Some allows multiline and strip the new line characters, some requires one line only.
LDP (from Microsoft) requires one line only.
