### ISSUE TITLE
Update to 10.0.3 - ocsng_fullsync.sh - SQL Error "1064"

### ISSUE THREAD

**Issue by NilsBay** [glpi-project/glpi#13077]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello,

the following for your information.

I don't know if OCS plugin is a community plugins.

After update GLPI to 10.0.3 (+ OCS plugin) and OCS to 2.11.0,

When I launch the script
/var/www/glpplugins/ocsinventoryng/scripts/ocsng_fullsync.sh

with the command (in crontab or manually)
/var/www/glpplugins/ocsinventoryng/scripts/ocsng_fullsync.sh --thread_nbr=10 --server_id=1 --nolog > /dev/pts/0

I have the following SQL Error
SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY `is_dynamic`' at line 5 in query "SELECT `id`, `name`, `is_dynamic`, `mainitems_id`                                      FROM `glpi_ipaddresses`                                      WHERE `itemtype` = 'NetworkName'                                        AND `items_id` =                                       ORDER BY `is_dynamic`"

With
find /var/www/glpi -type f -exec grep -H 'SELECT `id`, `name`, `is_dynamic`, `mainitems_id`' {} \;

I found the file
/var/www/glpi/plugins/ocsinventoryng/inc/networkport.class.php

In this file I found the query
$query        = "SELECT `id`, `is_dynamic`
                FROM `glpi_networknames`
                WHERE `itemtype` = 'NetworkPort'
                   AND `items_id` = $networkports_id
                ORDER BY `is_dynamic`";

I cannot help much.
Nils.

### Relevant log output

```shell
in
glpi/files/_log/sql-errors.log

Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'ORDER BY `is_dynamic`' at line 5
  Backtrace :
  src/DBmysqlIterator.php:110                        
  src/DBmysql.php:1048                               DBmysqlIterator->execute()
  ...ns/ocsinventoryng/inc/networkport.class.php:209 DBmysql->request()
  ...ns/ocsinventoryng/inc/networkport.class.php:451 PluginOcsinventoryngNetworkPort::updateNetworkPort()
  plugins/ocsinventoryng/inc/device.class.php:546    PluginOcsinventoryngNetworkPort::importNetwork()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1292 PluginOcsinventoryngDevice::updateDevices()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:471 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:448 PluginOcsinventoryngOcsProcess::processComputer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:297 plugin_ocsinventoryng_importFromOcsServer()
  ...s/ocsinventoryng/scripts/ocsng_fullsync.php:166 SecondPass()
  {"user":"@inventaire.local","mem_usage":"1.889\", 31.96Mio)"}
```

### Page URL

shell script

### Your GLPI setup information

I don't post the config here as I don't know it this text is public or not.
(This is my first time to GitHub)

**Comment by trasher** [comment]
Please report issue against OCS plugin.

**Comment by NilsBay** [comment]
Thank you for reading, ok.

**Comment by cedric-anne** [comment]
https://github.com/pluginsGLPI/ocsinventoryng

**Comment by NilsBay** [comment]
Thank you for the link !
