### ISSUE TITLE
Upgrade from 9.5.9 to 10.0.3 - Duplicate entry '0-ComputerModel-3' for key 'unicity' in query

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#13076]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Upgrade from 9.5.9 to 10.0.3

```
SQL Error "1062": Duplicate entry '0-ComputerModel-3' for key 'unicity' in query "UPDATE `glpi_displaypreferences` SET `num` = '3' WHERE `itemtype` = 'ComputerModel' AND `num` = '130'"

- Błąd w trakcie wykonywania zapytania do bazy danych: UPDATE `glpi_displaypreferences` SET `num` = '3' WHERE `itemtype` = 'ComputerModel' AND `num` = '130' - Błąd: Duplicate entry '0-ComputerModel-3' for key 'unicity
```

![image](https://user-images.githubusercontent.com/5873929/198056970-0cf0efab-d904-41bb-a22b-42be5c338a6e.png)

![image](https://user-images.githubusercontent.com/5873929/198059310-5b756775-12b6-493f-a5bc-ac79ee9c9b7d.png)

### Page URL

http://glpi_server.domain/install/update.php

### Steps To reproduce

Upgrade from 9.5.9 to 10.0.3

between version 10.0.0 to 10.0.1

**Comment by cedric-anne** [comment]
Hi,

Could you explain exactly how did you proceed to the update ?
Also, could you provide the corresponding log trace ?

**Comment by WebGregGit** [comment]
Hi. I also have problems with mysql after upgrading from 9.x to 10.x

  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_softwares` WHERE `glpi_softwares`.`id` = '--64-270' LIMIT 1
  Warnings:
1292: Truncated incorrect DOUBLE value: '--64-270'

*** MySQL query warnings:
  SQL: SELECT * FROM `glpi_softwares` WHERE `glpi_softwares`.`id` = '--19' LIMIT 1
  Warnings:
1292: Truncated incorrect DOUBLE value: '--19'

*** MySQL query warnings:
  SQL: SELECT * FROM `glpi_softwares` WHERE `glpi_softwares`.`id` = '---2015-64---1402421519' LIMIT 1
  Warnings:
1292: Truncated incorrect DOUBLE value: '---2015-64---1402421519'

  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_softwares` WHERE `glpi_softwares`.`id` = '-25526952-3243' LIMIT 1
  Warnings:
1292: Truncated incorrect DOUBLE value: '-25526952-3243'

And much more.

```
sudo service apache2 stop
sudo cp glpi/ glpi.bkp -Rf
sudo rm -r -f /var/www/html/glpi
wget https://github.com/.../glpi-10.0.x.tgz
tar -xvzf glpi-10.0.x.tgz -C /var/www/html
copy config, files, marketplace and plugins from glpi.bkp
```

Open the Glpi website > update confirm >

**Comment by WebGregGit** [comment]
My point was that upgrading from 9.x to 10.x caused various problems with mysql. 
I reported it elsewhere but no response: [https://github.com/glpi-project/glpi/issues/12779](https://github.com/glpi-project/glpi/issues/12779)

**Comment by cedric-anne** [comment]
This kind of error appears when you try to restore a dump of a previous version on a database of a more recent version.

Scripts in docker images does not really help to understand the steps you followed to upgrade the GLPI codebase and database.

**Comment by Wolvverine** [comment]
I used the standard way , through the GLPI update web page.

There is nothing extra in the containers, only different versions of GLPI from the GLPI project page.
