### ISSUE TITLE
Satisfaction survey

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1308]
Hello

Is it possible to delete satisfaction survey which not filled from a date.

The reason is a lot of users don't want to fill the survey and want to not view survey on glpi home page.

Thank you for your answer

**Comment by Armin83** [comment]
What did you set at duration of survey ?
Home - Administration - Entities - your entity - helpdesk

**Comment by satyan01** [comment]
I found the solution with mysql query

update glpi_ticketsatisfactions set date_answered='2016-11-15' where date_begin < '2016-02-01' and date_answered is null
