### ISSUE TITLE
Ticketsystem: new line <br> in E-Male results in new Paragraph which is to large

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#13089]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

If I send a new Mail to the ticketsystem which consists of two return the ticketsystem creates a paragraph. So the spacing is very large und hard to read.

### Relevant log output

```shell
-
```

### Page URL

£GLPI/front/ticket.form.php?id=XX

### Steps To reproduce

1. Send Mail to Ticketsystem:
```
Hallo,

ich habe ein Problem mit xyz.

Mit freundlichen Grüssen
```

2. Wait until GLPI created the ticket
3. Open this ticket

![grafik](https://user-images.githubusercontent.com/25504254/198274025-38100e82-b240-4927-8687-6b77dcddf316.png)

![grafik](https://user-images.githubusercontent.com/25504254/198274220-57f28804-1ed3-4d71-b903-cadf1db8322d.png)

![grafik](https://user-images.githubusercontent.com/25504254/198274341-2d223fb2-1755-4318-87fb-628fa2e6b347.png)

### Anything else?

I expect a smaller spacing in the rows of tickets like if you use a `<br>`.. Maybe the `<p>` is to large which results that the Tickets and response-mails are hard to read.
.
.
.
**_initial Mail to Ticketsystem:_**
![grafik](https://user-images.githubusercontent.com/25504254/198274924-29b5e3ba-e0f3-4c4e-b8f8-2f03baca190a.png)
.
.
.
**_Ticket:_**
![grafik](https://user-images.githubusercontent.com/25504254/198275043-5a358c7c-a9b6-465f-9f36-0e76ca7937af.png)
.
.
.
**_reply mail from Ticketsystem:_**
![grafik](https://user-images.githubusercontent.com/25504254/198275162-d0f91cc3-a896-4e22-8247-4ebe867401c3.png)
.
.
.
_**relevant sourcode of rows (Ticket)**_
![grafik](https://user-images.githubusercontent.com/25504254/198274836-9e10a0e4-54c0-445f-bbb2-dd5a1fa009ac.png)

**Comment by cedric-anne** [comment]
Hi,

`WordSection1` and `MsoNormal` classes are generated by your email client. We decided in GLPI to not try to clean styles received in emails as sometimes they might be usefull.

I close this as it is not considered as an issue.

**Comment by vollkommenIrrelevant** [comment]
> Hi,
> 
> `WordSection1` and `MsoNormal` classes are generated by your email client. We decided in GLPI to not try to clean styles received in emails as sometimes they might be usefull.
> 
> I close this as it is not considered as an issue.

Hi cedric,

thank you for your reply. What's the best way to solve this behavior? I can't believe that all other user have no problem with this...
