### ISSUE TITLE
Default statut on Inventory

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi#13091]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When a computer was scan (with glpi agent) for the first time, it changes the statut of the computer by '----' event the statut is locked

with glpi 9.5.*, i can set it to not change the statut

(all my pc are 'in stock' when i use data injection to add them into glpi, with glpi 10, when GLPI agent inventory it, he's show without statut)

### Steps To reproduce

1. add computer with a statut (Data injection)
2. scan a computer with glpi agent (for the first time) and the statut will disapear

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.3 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux vm-glpi-prod 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64
PHP 8.1.2 apache2handler (Core, FFI, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at xxxx.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47
Server Software: Ubuntu 22.04
	Server Version: 10.6.7-MariaDB-2ubuntu1.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.7) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi
GLPI_CONFIG_DIR: /etc/glpi/
GLPI_VAR_DIR: /var/lib/glpi
GLPI_LOG_DIR: /var/log/glpi
GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/lib/glpi
GLPI_CACHE_DIR: /var/lib/glpi/_cache
GLPI_CRON_DIR: /var/lib/glpi/_cron
GLPI_DUMP_DIR: /var/lib/glpi/_dumps
GLPI_GRAPH_DIR: /var/lib/glpi/_graphs
GLPI_LOCAL_I18N_DIR: /var/lib/glpi/_locales
GLPI_LOCK_DIR: /var/lib/glpi/_lock
GLPI_PICTURE_DIR: /var/lib/glpi/_pictures
GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/_plugins
GLPI_RSS_DIR: /var/lib/glpi/_rss
GLPI_SESSION_DIR: /var/lib/glpi/_sessions
GLPI_TMP_DIR: /var/lib/glpi/_tmp
GLPI_UPLOAD_DIR: /var/lib/glpi/_uploads
GLPI_INVENTORY_DIR: /var/lib/glpi/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpi/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@xxxx.fr)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.18.1     State: Enabled                                 
		Install Method: Manual
	news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                 
		Install Method: Manual
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                
		 Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.1     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.14.0     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Imports fabricants             Version: 3.0.2      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Impression pdf                 Version: 2.1.0      State: Enabled                                 
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual
	reservation          Name: Reservation                    Version: 2.4.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by stonebuzz** [comment]
Hi @TheRoby 
maybe you need to add "global lock" on computer status ?
To prevent inventory to override your value
Best regards

**Comment by TheRoby** [comment]
hi @stonebuzz,
thank you for the idea, i have set the global lock. i'll wait to the next new computer and i'll tell you :)

**Comment by stonebuzz** [comment]
=)
it is also possible to define a default status for the inventory
![image](https://user-images.githubusercontent.com/7335054/198329331-c6677ab9-9a74-4da5-abe8-96029d8046cf.png)

**Comment by TheRoby** [comment]
Yes, but no ...
Now it's not possible to (first) import computer with GLPI Agent without update of the statut ... (the default behavior of version 9 with fusion inventory)

**Comment by cedric-anne** [comment]
> Yes, but no ... Now it's not possible to (first) import computer with GLPI Agent without update of the statut ... (the default behavior of version 9 with fusion inventory)

Not sure to understand, can you give more details ?

**Comment by trasher** [comment]
As of myself, I'm sure I do not understand :D

**Comment by TheRoby** [comment]
Hello, sorry :)

When I receive new PCs, I import them into GLPI with data injection, and in my import, I put the status "in stock".
When the PC is installed and during the first synchronization between GLPI Agent and GLPI, it modifies my status by putting what is validated in the configuration indicated by stonebuzz. But suddenly, if it's "-----" then it changes my status to an empty status.

I have this in history : (and the statut field was lock (not globaly))

**18363214	27/10/2022 09:55	inventory	Statut	Changement de <del>En stock (2)</del> Ã  <ins>&nbsp; (0)</ins>**
18363213	27/10/2022 09:55	inventory	ModÃ¨le	Changement de <del>260 G4 Desktop (248)</del> Ã  <ins>HP 260 G4 Desktop Mini PC (215)</ins>
18363212	27/10/2022 09:55	inventory	Usager	Changement de <del></del> Ã  <ins>Administrateur@8CC13913SL</ins>
18363211	27/10/2022 09:55	inventory	Type	Changement de <del>&nbsp; (0)</del> Ã  <ins>Desktop (2)</ins>
18363210	27/10/2022 09:55	inventory	Utilisateur	Changement de <del>&nbsp; (0)</del> Ã  <ins>Administrateur (15606)</ins>
18363209	27/10/2022 09:55	inventory	UUID	Changement de <del></del> Ã  <ins>B447B67F-94A8-B182-11E7-C8FF04404695</ins>
18363208	27/10/2022 09:55	inventory	Date de dernier inventaire	Changement de <del></del> Ã  <ins>27-10-2022 09:55</ins>
18363207	27/10/2022 09:55	inventory	Source de mise Ã  jour	Changement de <del>&nbsp; (0)</del> Ã  <ins>GLPI Native Inventory (1)</ins>

**Comment by stonebuzz** [comment]
Hi @TheRoby 

can you try this -> https://github.com/glpi-project/glpi/pull/13099

Just set "Default status" option to "Do not change"

And do a test with a new item (create manually or with datainecjtion)

**Comment by cedric-anne** [comment]
I close this issue as it seems to be implemented now (see #13099).
