### ISSUE TITLE
Use of more than 15 integers in the Mobile Subscriber Identification Number field on SIM Cards

### ISSUE THREAD

**Issue by eriqueSDB** [glpi-project/glpi#13095]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When using the Mobile Subscriber Identification Number field in SIM Cards regardless of the GLPI version, I tested it in 9.5.6 and 10.0.3 the problem is the same, when trying to use a sequence greater than 15 numeric digits and export this data in .csv this field totally bugs giving random numbers.

### Steps To reproduce

1. Create an item on the sim cards and use the field "Mobile Subscriber Identification Number" with the number: 89550282000038745888
2. Create another item on the sim cards and use the field "Mobile Subscriber Identification Number" with the number: 89550282000038746001
3. Edit sim card page filter to add "Mobile Subscriber Identification Number" field
4. Export the current page or all pages in CSV by GLPI itself.
5. Check if the field in the GLPI matches the report, in this case this is where we see this bug.

**Comment by cedric-anne** [comment]
Hi,

MSIN should contains only 10 digits, see https://en.wikipedia.org/wiki/Mobile_identification_number

> mobile subscription identification number (MSIN) refers to the 10-digit unique number

**Comment by eriqueSDB** [comment]
> Hi,
> 
> MSIN should contains only 10 digits, see https://en.wikipedia.org/wiki/Mobile_identification_number
> 
> > mobile subscription identification number (MSIN) refers to the 10-digit unique number that a wireless carrier uses to identify a mobile phone

Yes I understand, this is an internal need I have to use the field with more than 10 numbers

This same behavior can be noticed using the serial number field in several cases of the glpi menus, including in the same SIM cards menu, if you register any of these numbers that I have described, you will see that they are changed to another standard.

My point here would be to find where in the code exactly this is handled at the time of generating the report in .csv for adaptation in special cases that have this need.

**Comment by trasher** [comment]
I cannot be 100% sure since requested information has not been provided; but I suspect a 32bits systme issue.

Anyways; this field is made to handle 10 charcaters long integer, not 15. If your need differs, then you're trying to store something else; you'd better consider using a plugin like fields to properly handle your own data.

I close since this is not a bug
