### ISSUE TITLE
API : DELETE with force_purge in query string may be ignored

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1309]
Hi

The following request sends the user in the bin, but it should purge it

```DELETE /User/12?force_purge=true```

```
DELETE /User
{ "input": { "id": 15 }, "force_purge": "true" }
```

The following requests purges the user 

```DELETE /User/12?force_purge=1```

```
DELETE /User
{ "input": { "id": 15 }, "force_purge": true }
```

The documentation says force_purge should be true or false.

In  the two first requests, force_purge is (string) "true" In CommonDBTM::deleteFromDB() it is compared to (int) 1 and leads to unexpected behavior.

In the two last requests, the test behaves as expected.

**Comment by orthagh** [comment]
Merged, Thank you
