### ISSUE TITLE
bug in "Managament - Suppliers"

### ISSUE THREAD

**Issue by HelpITru** [glpi-project/glpi#1311]
I have some bug described [here](http://forum.glpi-project.org/viewtopic.php?id=155887)

![161106_glpi_err](https://cloud.githubusercontent.com/assets/16210381/20391583/2001f370-ace5-11e6-8fcb-6f9ef1d657ff.png)

[code]
 
GLPI 9.1 (/glpi => /opt/glpi-0.84.5)

Server

 
Operating system: Linux 2x-glpi.ukritter.local 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64
PHP 5.5.38 apache2handler (Core, PDO, Phar, Reflection, SPL, apache2handler, bz2, calendar, ctype, curl, date, ereg, exif,
	fileinfo, filter, ftp, gd, gettext, hash, iconv, json, libxml, mbstring, mhash, mysql, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.2.15 (CentOS) (Apache/2.2.15 (CentOS) Server at it.helpit.ru Port 80)
	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Server Software: MySQL Community Server (GPL) by Remi
	Server Version: 5.5.53
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
OK/opt/glpi-0.84.5/config : OK
OK/opt/glpi-0.84.5/files : OK
OK/opt/glpi-0.84.5/files/_dumps : OK
OK/opt/glpi-0.84.5/files/_sessions : OK
OK/opt/glpi-0.84.5/files/_cron : OK
OK/opt/glpi-0.84.5/files/_graphs : OK
OK/opt/glpi-0.84.5/files/_lock : OK
OK/opt/glpi-0.84.5/files/_plugins : OK
OK/opt/glpi-0.84.5/files/_tmp : OK
OK/opt/glpi-0.84.5/files/_rss : OK
OK/opt/glpi-0.84.5/files/_uploads : OK
OK/opt/glpi-0.84.5/files/_pictures : OK
OK/opt/glpi-0.84.5/files/_log : OK
OKSELinux mode is Disabled

Libraries

 
htmLawed version 1.1.21 in (/opt/glpi-0.84.5/lib/htmlawed)
phpCas version 1.3.4 in (/opt/glpi-0.84.5/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/opt/glpi-0.84.5/vendor/phpmailer/phpmailer)
Zend Framework in (/opt/glpi-0.84.5/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/opt/glpi-0.84.5/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/opt/glpi-0.84.5/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/opt/glpi-0.84.5/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/glpi-0.84.5/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/glpi-0.84.5/vendor/true/punycode/src)
iacaml/autolink in (/opt/glpi-0.84.5/vendor/iamcal/lib_autolink)
sabre/vobject in (/opt/glpi-0.84.5/vendor/sabre/vobject/lib)
guzzlehttp/guzzle in (/opt/glpi-0.84.5/vendor/guzzlehttp/guzzle/src)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (glpi@test.test)

Mails receivers

 

Plugins list

 
	appliances           Name: Appliances                     Version: 2.2        State: Enabled
	badges               Name: Badges                         Version: 2.2.0      State: Enabled
	certificates         Name: Certificates                   Version: 2.2.0      State: Enabled
	databases            Name: Databases                      Version: 1.9.0      State: Enabled
	domains              Name: Domains                        Version: 1.8.0      State: Enabled
	environment          Name: Environment                    Version: 2.0.0      State: Enabled
	addressing           Name: IP Adressing                   Version: 2.4.0      State: Enabled
	webapplications      Name: Web applications               Version: 2.2.0      State: Enabled
	simcard              Name: Управление SIM-картами  Version: 1.4.2      State: Enabled

[/code]

**Comment by HelpITru** [comment]
I find problem : https://github.com/InfotelGLPI/domains/issues/13 
Please help fix it.

**Comment by trasher** [comment]
This is a plugin related issue; should then be fixed on the plugin side :)

**Comment by HelpITru** [comment]
The same bug with update to 9.1.1 GLPI
