### ISSUE TITLE
No "Add to transfer list" - can't change entities for computers

### ISSUE THREAD

**Issue by gkukovacec** [glpi-project/glpi#13111]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi!
Fresh install of GLPI 10.0.3.
When I select a computer and click Action button, there's no "Add to transfer list" in dropdown.
Logged in as Super admin. Sub-entities under root created.
Please help.
Thanks!

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.3 (/glpi => /home/getimin5/public_html/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux server.getim.hr 4.18.0-348.20.1.lve.1.el8.x86_64 #1 SMP Wed Mar 16 08:45:39 EDT 2022 x86_64
PHP 7.4.32 cgi-fcgi (Core, PDFlib, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mailparse,
	mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, soap, sockets, sodium,
	sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="90" memory_limit="128M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Apache ()
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.30-cll-lve
	Server SQL Mode: STRICT_TRANS_TABLES,ALLOW_INVALID_DATES
	Parameters: getimin5_dbuser@localhost/getimin5_03
	Host info: Localhost via UNIX socket
	
PHP version (7.4.32) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.
The log file has been created successfully.
Write access to /home/getimin5/public_html/glpi/files/_cache has been validated.
Write access to /home/getimin5/public_html/glpi/config has been validated.
Write access to /home/getimin5/public_html/glpi/files/_cron has been validated.
Write access to /home/getimin5/public_html/glpi/files has been validated.
Write access to /home/getimin5/public_html/glpi/files/_dumps has been validated.
Write access to /home/getimin5/public_html/glpi/files/_graphs has been validated.
Write access to /home/getimin5/public_html/glpi/files/_lock has been validated.
Write access to /home/getimin5/public_html/glpi/files/_pictures has been validated.
Write access to /home/getimin5/public_html/glpi/files/_plugins has been validated.
Write access to /home/getimin5/public_html/glpi/files/_rss has been validated.
Write access to /home/getimin5/public_html/glpi/files/_sessions has been validated.
Write access to /home/getimin5/public_html/glpi/files/_tmp has been validated.
Write access to /home/getimin5/public_html/glpi/files/_uploads has been validated.
Web access to files directory is protected
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/getimin5/public_html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /home/getimin5/public_html/glpi
GLPI_CONFIG_DIR: /home/getimin5/public_html/glpi/config
GLPI_VAR_DIR: /home/getimin5/public_html/glpi/files
GLPI_MARKETPLACE_DIR: /home/getimin5/public_html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /home/getimin5/public_html/glpi/files
GLPI_CACHE_DIR: /home/getimin5/public_html/glpi/files/_cache
GLPI_CRON_DIR: /home/getimin5/public_html/glpi/files/_cron
GLPI_DUMP_DIR: /home/getimin5/public_html/glpi/files/_dumps
GLPI_GRAPH_DIR: /home/getimin5/public_html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /home/getimin5/public_html/glpi/files/_locales
GLPI_LOCK_DIR: /home/getimin5/public_html/glpi/files/_lock
GLPI_LOG_DIR: /home/getimin5/public_html/glpi/files/_log
GLPI_PICTURE_DIR: /home/getimin5/public_html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /home/getimin5/public_html/glpi/files/_plugins
GLPI_RSS_DIR: /home/getimin5/public_html/glpi/files/_rss
GLPI_SESSION_DIR: /home/getimin5/public_html/glpi/files/_sessions
GLPI_TMP_DIR: /home/getimin5/public_html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /home/getimin5/public_html/glpi/files/_uploads
GLPI_INVENTORY_DIR: /home/getimin5/public_html/glpi/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /home/getimin5/public_html/glpi/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/home/getimin5/public_html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/getimin5/public_html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/getimin5/public_html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/home/getimin5/public_html/glpi/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/getimin5/public_html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/getimin5/public_html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/getimin5/public_html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/home/getimin5/public_html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/getimin5/public_html/glpi/vendor/sabre/http/lib)
sabre/uri in (/home/getimin5/public_html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/home/getimin5/public_html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/getimin5/public_html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/getimin5/public_html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/getimin5/public_html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/getimin5/public_html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/getimin5/public_html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/getimin5/public_html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/home/getimin5/public_html/glpi/vendor/symfony/console)
scssphp/scssphp in (/home/getimin5/public_html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/getimin5/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/getimin5/public_html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/getimin5/public_html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/getimin5/public_html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/getimin5/public_html/glpi/vendor/ramsey/uuid/src)
psr/log in (/home/getimin5/public_html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/getimin5/public_html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/home/getimin5/public_html/glpi/vendor/psr/cache/src)
league/csv in (/home/getimin5/public_html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/home/getimin5/public_html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/getimin5/public_html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/getimin5/public_html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/getimin5/public_html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/getimin5/public_html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/getimin5/public_html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/getimin5/public_html/glpi/vendor/symfony/cache)
html2text/html2text in (/home/getimin5/public_html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/home/getimin5/public_html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/getimin5/public_html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/home/getimin5/public_html/glpi/vendor/twig/twig/src)
twig/string-extra in (/home/getimin5/public_html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/home/getimin5/public_html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/home/getimin5/public_html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/home/getimin5/public_html/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	pdf                  Name: Print to pdf                   Version: 2.1.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
I'm not able to recreate the issue.
As long as your current profile has permissions to update Computers, has the READ right for "Transfer" (In Administration tab of the profile) and there are multiple entities created, this option should show up. If you just created the entities in this same login session, you may need to log out and back in for GLPI to detect it is now in "multi-entity mode".

**Comment by gkukovacec** [comment]
Thanks!

I’m new to GLPI, sorry for postig this as a bug.

Please close the issue.

Goran

On 30.10.2022., at 11:40, Curtis Conard ***@***.***> wrote:

﻿

I'm not able to recreate the issue.
As long as your current profile has permissions to update Computers, has the READ right for "Transfer" (In Administration tab of the profile) and there are multiple entities created, this option should show up. If you just created the entities in this same login session, you may need to log out and back in for GLPI to detect it is now in "multi-entity mode".
