### ISSUE TITLE
plugin_version_glpi-modifications method must be defined!

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#13115]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.3

### Bug description

After upgrading from 10.0.0.2 to 10.0.0.3 I've got this warnings when opening plugins or marketplace. Can't see any plugin causing the warning

### Relevant log output

```shell
[2022-10-31 13:24:42] glpiphplog.WARNING:   *** PHP User Warning (512): plugin_version_glpi-modifications method must be defined! in .../src/Plugin.php at line 1603
  Backtrace :
  src/Plugin.php:1603                                trigger_error()
  src/Plugin.php:1641                                Plugin::getInfo()
  src/Plugin.php:492                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:472                                 Plugin->checkPluginState()
  front/marketplace.php:43                           Plugin->checkStates()
  
[2022-10-31 13:25:43] glpiphplog.WARNING:   *** PHP User Warning (512): plugin_version_glpi-modifications method must be defined! in .../src/Plugin.php at line 1603
  Backtrace :
  src/Plugin.php:1603                                trigger_error()
  src/Plugin.php:1641                                Plugin::getInfo()
  src/Plugin.php:492                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:472                                 Plugin->checkPluginState()
  front/plugin.php:43                                Plugin->checkStates()
```

### Page URL

front/plugin.php, front/marketplace.php

### Your GLPI setup information

<details><summary>Informationen über das System, die Installation und die Konfiguration</summary><pre>GLPI 10.0.3 ( => ...)
Installation mode: TARBALL
Current language:de_DE

</details><details><summary>Server</summary><pre> 
Operating system: Linux a2e28 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64
PHP 7.4.30 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, igbinary, imagick, imap, intl, ionCube Loader, json,
	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, posix, redis, session, shmop,
	soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="180" memory_limit="512M" post_max_size="128M" safe_mode="" session.save_handler="files"
	upload_max_filesize="128M" 
Software: Apache (Apache Server at ... Port 443
)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.30
	Server SQL Mode: IGNORE_SPACE,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: k191623_glpi@10.35.46.41/k191623_glpi
	Host info: 10.35.46.41 via TCP/IP
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.
The log file has been created successfully.
Write access to .../files/_cache has been validated.
Write access to .../config has been validated.
Write access to .../files/_cron has been validated.
Write access to .../files has been validated.
Write access to .../files/_dumps has been validated.
Write access to .../files/_graphs has been validated.
Write access to .../files/_lock has been validated.
Write access to .../files/_pictures has been validated.
Write access to .../files/_plugins has been validated.
Write access to .../files/_rss has been validated.
Write access to .../files/_sessions has been validated.
Write access to .../files/_tmp has been validated.
Write access to .../files/_uploads has been validated.
Web access to files directory is protected
PHP Warning (2): file_exists(): open_basedir restriction in effect. File(/usr/sbin/getenforce) is not within the allowed path(s): (/var/www/vhosts/hosting176793.a2e28.netcup.net/:/tmp/) in .../src/System/Requirement/SeLinux.php at line 52
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to .../marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: ...
GLPI_CONFIG_DIR: .../config
GLPI_VAR_DIR: .../files
GLPI_MARKETPLACE_DIR: .../marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
PHP Notice (8): Array to string conversion in .../src/Config.php at line 2073
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: .../files
GLPI_CACHE_DIR: .../files/_cache
GLPI_CRON_DIR: .../files/_cron
GLPI_DUMP_DIR: .../files/_dumps
GLPI_GRAPH_DIR: .../files/_graphs
GLPI_LOCAL_I18N_DIR: .../files/_locales
GLPI_LOCK_DIR: .../files/_lock
GLPI_LOG_DIR: .../files/_log
GLPI_PICTURE_DIR: .../files/_pictures
GLPI_PLUGIN_DOC_DIR: .../files/_plugins
GLPI_RSS_DIR: .../files/_rss
GLPI_SESSION_DIR: .../files/_sessions
GLPI_TMP_DIR: .../files/_tmp
GLPI_UPLOAD_DIR: .../files/_uploads
GLPI_INVENTORY_DIR: .../files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: .../locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (.../vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (.../vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (.../vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (.../marketplace/financialreports/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (.../vendor/michelf/php-markdown/Michelf)
true/punycode in (.../vendor/true/punycode/src)
iamcal/lib_autolink in (.../vendor/iamcal/lib_autolink)
sabre/dav in (.../vendor/sabre/dav/lib/DAV)
sabre/http in (.../vendor/sabre/http/lib)
sabre/uri in (.../vendor/sabre/uri/lib)
sabre/vobject in (.../vendor/sabre/vobject/lib)
laminas/laminas-i18n in (.../vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (.../vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (.../vendor/monolog/monolog/src/Monolog)
sebastian/diff in (.../vendor/sebastian/diff/src)
donatj/phpuseragentparser in (.../vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (.../vendor/elvanto/litemoji/src)
symfony/console in (.../vendor/symfony/console)
scssphp/scssphp in (.../vendor/scssphp/scssphp/src)
laminas/laminas-mail in (.../vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (.../vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (.../vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (.../vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (.../vendor/ramsey/uuid/src)
psr/log in (.../vendor/psr/log/Psr/Log)
psr/simple-cache in (.../vendor/psr/simple-cache/src)
psr/cache in (.../vendor/psr/cache/src)
league/csv in (.../vendor/league/csv/src)
mexitek/phpcolors in (.../vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (.../vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (.../vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (.../vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (.../vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (.../vendor/paragonie/sodium_compat/src)
symfony/cache in (.../vendor/symfony/cache)
html2text/html2text in (.../vendor/html2text/html2text/src)
symfony/css-selector in (.../vendor/symfony/css-selector)
symfony/dom-crawler in (.../vendor/symfony/dom-crawler)
twig/twig in (.../vendor/twig/twig/src)
twig/string-extra in (.../vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (.../vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (.../vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (.../vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap.google.com', Port: '636', BaseDN: 'dc=mindo,dc=berlin', Connection filter: none, RootDN: 'uid=Unconsciou', Use
		TLS: '1'
Server: 'ldap.google.com', Port: '389', BaseDN: 'dc=mindo,dc=berlin', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: none, Use TLS: '1'
Server: 'ldap.google.com', Port: '389', BaseDN: 'dc= vapedinnerlady,dc=de', Connection filter: none, RootDN: none, Use TLS: '1'
Server: 'ldap.google.com', Port: '389', BaseDN: 'dc= armytek,dc=de', Connection filter: none, RootDN: none, Use TLS: '1'
Server: 'ldap.google.com', Port: '389', BaseDN: 'dc=coronazentrum-kulturbrauerei,dc=de', Connection filter: none, RootDN:
		'BrightUlys', Use TLS: '1'
Server: 'ldap.google.com', Port: '389', BaseDN: 'dc=vionic,dc=berlin', Connection filter: none, RootDN: none, Use TLS: '1'
Server: 'ldap.google.com', Port: '636', BaseDN: 'dc=*', Connection filter: none, RootDN: none, Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	activity             Name: Activities                     Version: 3.1.2      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Additional fields              Version: 1.18.2     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Bestellverwaltung              Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.3      State: Enabled                                 
		Install Method: Marketplace
	financialreports     Name: Financial reports              Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.0.1      State: Enabled                                 
		Install Method: Marketplace
	jamf                 Name: JAMF Plugin for GLPI           Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	positions            Name: Kartographie                   Version: 6.0.2      State: Enabled                                 
		Install Method: Marketplace
	accounts             Name: Konten                         Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	resources            Name: Mitarbeiter                    Version: 3.0.4      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	satisfaction         Name: More satisfaction              Version: 1.6.1      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.0     State: Enabled                                 
		Install Method: Marketplace
	phpsaml              Name: PHP SAML                       Version: 1.2.0      State: Not installed                           
		Install Method: Manual
	purchaserequest      Name: Purchase request               Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	singlesignon         Name: Single Sign-on                 Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	tasklists            Name: Tasks list                     Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.1   State: Enabled                                 
		Install Method: Marketplace
	trademark            Name: Trademark                      Version: 1.2.4      State: Installed / not activated               
		Install Method: Manual
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.2      State: Installed / not activated               
		Install Method: Marketplace
	webapplications      Name: Webanwendungen                 Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by Megachip** [comment]
> Please report plugins issue on plugins repositories

But how to figure out, which plugin thrown the issue? `src` and `front` are glpi folders, no external stuff

**Comment by btry** [comment]
Hi

You very likely have folder marketplace/glpi-modifications or plugins/glpi-modifications.
