### ISSUE TITLE
open documentation topic direct

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1318]
Hi,

can you reference documentation html to the site i get from.

In other words:
If i go to help with "?" can the system direct open the correct topic i jump from.

I'm on ticket / task section so if i press the "?" i should get to the task section.

best regards
armin

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
