### ISSUE TITLE
Knowledge Base

### ISSUE THREAD

**Issue by mehmettopcu** [glpi-project/glpi#1319]
In the knowledge base there must be different versions of the items for targets.

**Comment by Armin83** [comment]
I'm not a developer or glpi project administrator.
But I think would like do a suggestion or feature request.
This should be done over there http://glpi.userecho.com/

**Comment by trasher** [comment]
@Armin83 is right. If the need is not covered in #912, please open a request on the suggestions website.

Thank you :)
