### ISSUE TITLE
10.0.4 - simplified interface and no permission to answer

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#13199]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

To simplify the lives of users as much as possible, I have set up a simple interface for the user profile. When the user tries to add something to the ticked (the answer), a message appears: You don't have permission to perform this action.

This is due to the inability to grant the appropriate permissions.

Standard interface:
![image](https://user-images.githubusercontent.com/68922721/199945184-d0e1b350-ecfb-4e89-ae98-6574bb97dff2.png)

Simplified interface:
![image](https://user-images.githubusercontent.com/68922721/199945338-de410f26-e560-45c6-9597-38581a13ddb2.png)

Here is not possible to grant such privilages.

### Anything else?

In my opinion, this is a mistake, because simplifying the interface does not have to mean cutting off the user from any interaction while handling the ticket.

**Comment by Tartiflette-glpi** [comment]
Hi, are you using the plugin FormCreator or the glpi's tickets ?

**Comment by WebGregGit** [comment]
Yes. Your point is that this is not a GLPI problem, but a FormCreator?

**Comment by WebGregGit** [comment]
Yes, that solved the problem. Thank you.
But is this normal? Maybe it's because of my lack of understanding of the language. It seems to me not very intuitive. Especially that after changing the interface, these permissions can be granted in a completely different place.

**Comment by WebGregGit** [comment]
And one more strange behavior for me. When I edit the ticket template and run the preview:

Standard interface:
![image](https://user-images.githubusercontent.com/68922721/200065869-c2dae905-fd98-4e48-9c3a-ef5cf88a3a1b.png)

Simplified:
![image](https://user-images.githubusercontent.com/68922721/200066161-1fea6446-945b-4505-b27c-a9cc03dd4bab.png)

But when a user with a simple interface assigned to the profile displays a ticket:

![image](https://user-images.githubusercontent.com/68922721/200066541-49272fa1-c4c6-46bb-952c-db0f25a8cb46.png)

Shouldn't only 1 section be displayed as shown in the preview for simplified?
