### ISSUE TITLE
Dashboard chart title issue

### ISSUE THREAD

**Issue by FelipeBendetto** [glpi-project/glpi#13190]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

The problem was solved. But the title of the graph is on top of the graph.

![Captura](https://user-images.githubusercontent.com/63675440/199762587-81bd09cc-b98f-4b35-890a-c09c4cfa8342.png)

**Comment by cedric-anne** [comment]
Could you please give more details ? It could help us to identify the affected dashboard card, for instance.

**Comment by FelipeBendetto** [comment]
All graphs generated in line have this problem, in any dashboard. No matter how big we put the graph, the title is on top of the data

**Comment by cconard96** [comment]
Can you see if #13236 fixes the issue for you?

**Comment by FelipeBendetto** [comment]
Sorted out. Thank you very much.
