### ISSUE TITLE
[10.0.4]Changing active entity logout the user

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#13192]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

When the user switch to another entity, he is unlogged

**Comment by romarioliveira25** [comment]
Any news about fix this issue?

**Comment by orthagh** [comment]
Fixed in #13191, a new release should be done tomorrow morning (in france)

**Comment by troublestarter** [comment]
same issue here.
We're waiting for fix ;)

**Comment by orthagh** [comment]
releases has been done  : https://github.com/glpi-project/glpi/releases

**Comment by troublestarter** [comment]
oh thanks !

**Comment by troublestarter** [comment]
update done, it has been fixed.

**Comment by troublestarter** [comment]
But strange things with pics
![image](https://user-images.githubusercontent.com/6012203/199927795-3b12d70f-603e-4ac6-b83c-103302d1b45d.png)

**Comment by orthagh** [comment]
If you find bugs not relative to the current one, open a new issue please

**Comment by cedric-anne** [comment]
> But strange things with pics ![image](https://user-images.githubusercontent.com/6012203/199927795-3b12d70f-603e-4ac6-b83c-103302d1b45d.png)

This seems to be a completely different issue. Please open a new thread for this.
