### ISSUE TITLE
Problem of translation

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#132]
http://forum.glpi-project.org/viewtopic.php?id=122160

I don't have right to translate en_GB
La traduction n'est pas correct dans le .po (termes ITIL à utiliser)

**Comment by orthagh** [comment]
You should redirect users (on forum or irc) to transifex and suggest to correct themself.
Anyway, I'm changing the occurences of problems/issues

**Comment by yllen** [comment]
Orthagh : l'utilisateur c'est moi, je n'ai pas le droit de traduire GLPI en anglais
