### ISSUE TITLE
[9.1.1] Planning view Group Members filter

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1320]
In planning view the "group members filter" have an active checkbox if i open the planning site but the the users inside / below are not checked so it is false.

![img_002](https://cloud.githubusercontent.com/assets/19192087/20462560/620d9c5e-af21-11e6-8f38-7be7527faf48.jpg)
![img_003](https://cloud.githubusercontent.com/assets/19192087/20462561/620fed10-af21-11e6-8a67-069a0ad704a1.jpg)

**Comment by Armin83** [comment]
bug is in further present in 9.1.3

**Comment by trasher** [comment]
Just tested on current 9.2/bugfixes branch; I cannot reproduce. The issue should have been fixed
