### ISSUE TITLE
bug : upgrade 9.5.9 to 9.5.11 - /n when modify ticket

### ISSUE THREAD

**Issue by pva69007** [glpi-project/glpi#13205]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

bug : upgrade 9.5.9 to 9.5.11 - /n when modify ticket

When modifying (title or description) on an existing ticket, the "/n" character is displayed for each line break.

We go back to 9.5.9 before create this ticket

### Your GLPI setup information

Operating system: Linux srv-debian-glpi 5.10.0-19-amd64 #1 SMP Debian 5.10.149-1 (2022-10-17) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: 
	Parameters: glpisupport@localhost/glpi_support
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.15) - Perfect!Database version seems correct (10.5.15) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/support/files/_cache has been validated.Write access to /var/www/html/support/files/_cache has been validated.
Write access to /var/www/html/support/config has been validated.Write access to /var/www/html/support/config has been validated.
Write access to /var/www/html/support/files/_cron has been validated.Write access to /var/www/html/support/files/_cron has been validated.
Write access to /var/www/html/support/files has been validated.Write access to /var/www/html/support/files has been validated.
Write access to /var/www/html/support/files/_dumps has been validated.Write access to /var/www/html/support/files/_dumps has been validated.
Write access to /var/www/html/support/files/_graphs has been validated.Write access to /var/www/html/support/files/_graphs has been validated.
Write access to /var/www/html/support/files/_lock has been validated.Write access to /var/www/html/support/files/_lock has been validated.
Write access to /var/www/html/support/files/_pictures has been validated.Write access to /var/www/html/support/files/_pictures has been validated.
Write access to /var/www/html/support/files/_plugins has been validated.Write access to /var/www/html/support/files/_plugins has been validated.
Write access to /var/www/html/support/files/_rss has been validated.Write access to /var/www/html/support/files/_rss has been validated.
Write access to /var/www/html/support/files/_sessions has been validated.Write access to /var/www/html/support/files/_sessions has been validated.
Write access to /var/www/html/support/files/_tmp has been validated.Write access to /var/www/html/support/files/_tmp has been validated.
Write access to /var/www/html/support/files/_uploads has been validated.Write access to /var/www/html/support/files/_uploads has been validated.
Write access to /var/www/html/support/marketplace has been validated.Write access to /var/www/html/support/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

GLPI constants

 
GLPI_ROOT: /var/www/html/support
GLPI_CONFIG_DIR: /var/www/html/support/config
GLPI_VAR_DIR: /var/www/html/support/files
GLPI_MARKETPLACE_DIR: /var/www/html/support/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/html/support/files
GLPI_CACHE_DIR: /var/www/html/support/files/_cache
GLPI_CRON_DIR: /var/www/html/support/files/_cron
GLPI_DUMP_DIR: /var/www/html/support/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/support/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/support/files/_locales
GLPI_LOCK_DIR: /var/www/html/support/files/_lock
GLPI_LOG_DIR: /var/www/html/support/files/_log
GLPI_PICTURE_DIR: /var/www/html/support/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/support/files/_plugins
GLPI_RSS_DIR: /var/www/html/support/files/_rss
GLPI_SESSION_DIR: /var/www/html/support/files/_sessions
GLPI_TMP_DIR: /var/www/html/support/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/support/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/support/locales
GLPI_VERSION: 9.5.9
GLPI_SCHEMA_VERSION: 9.5.7
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2022

Libraries

 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/support/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/support/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/html/support/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/support/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/support/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/support/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/support/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/support/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/support/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/support/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/support/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/support/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/support/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/support/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/support/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/support/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/support/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/support/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/support/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/support/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/support/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/support/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/support/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/support/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/support/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/support/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/support/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/support/marketplace/oauthimap/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/support/marketplace/oauthimap/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/html/support/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/support/vendor/paragonie/sodium_compat/src)

LDAP directories

 
Server: 'W2K19-AD-SG', Port: '389', BaseDN: 'dc=company,dc=dom', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'cn=administrateur,cn=users,dc=company,dc=dom', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP+TLS (support@company.fr@smtp.office365.com)

Mails receivers

 
Name: 'support.company@company.com' Active: No
	Server: '{outlook.office365.com:993/imap/ssl/novalidate-cert/notls}' Login: 'support.company@company.com' Password: Yes
Name: 'support@company.fr' Active: Yes
	Server: '{mail.office365.com:993/imap/ssl/novalidate-cert/notls}' Login: 'support@company.fr' Password: Yes

Plugins list

 
	news                 Name: Alertes                        Version: 1.9.1      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled
	oauthimap            Name: Oauth IMAP                     Version: 1.3.3      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.7.4      State: Enabled

**Comment by RodolpheLP** [comment]
same thing happened to us (go from 9.5.9 to 9.5.11)

**Comment by cedric-anne** [comment]
Can you check https://github.com/pluginsGLPI/formcreator/pull/3065 ?

**Comment by glpibr** [comment]
Expensive,
we at Verdanatech provide a release in our repository with this solution, if you are interested.
The BUG affected all of our customers, so we had to race ourselves to come up with a solution.
If anyone, or even Teclib, is interested in the solution, follow the temporary repository that we are making publicly available.

https://github.com/verdanatech/glpi-9.5.11

**Comment by RodolpheLP** [comment]
Thanks @glpibr.
It works !

**Comment by cedric-anne** [comment]
Duplicates #13202
