### ISSUE TITLE
Issue #1944 reappeared in GLPI 9.5.10/9.5.11

### ISSUE THREAD

**Issue by nsalguero** [glpi-project/glpi#13202]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

Hi,

In GLPI 9.5.10/9.5.11, the issue #1944 reappeared because TinyMCE version 5.10.6 seems to have replaced the event `SaveContent` by `PostProcess`.

To solve the problem, here is my patch:
```
--- glpi/inc/html.class.php.orig        2022-11-04 11:44:35.798454357 +0100
+++ glpi/inc/html.class.php     2022-11-04 11:35:17.132208052 +0100
@@ -3972,6 +3972,9 @@ JS;
                      });
                   }

+                  editor.on('PostProcess', function (contentEvent) {
+                     contentEvent.content = contentEvent.content.replace(/\\r?\\n/g, '');
+                  });
                   editor.on('SaveContent', function (contentEvent) {
                      contentEvent.content = contentEvent.content.replace(/\\r?\\n/g, '');
                   });
```

I cannot check if that problem also occurs with GLPI 10.0.4/10.0.5 or not.

Best regards,

Nicolas Salguero.

### Steps To reproduce

Enter some text containing line feed in a followup, for example and save it.

**Comment by cedric-anne** [comment]
Hi,

On my side, I have additionnal empty lines in followups, but I do not see `rn` strings. Have you some plugins active ? Could you check with no active plugins if the problem persists ?

Regards

**Comment by nsalguero** [comment]
Hi,

After some tests, I now see that `rn` strings only appear with tickets that are generated with FormCreator.  In all other situations, there are additional empty lines.

The patch I provided fixes the two problems.

Best regards,

**Comment by cedric-anne** [comment]
Thanks for your patch, I added it on 9.5 branch: ade4d2e076f5b118aebce9095161dffc73376c7e
