### ISSUE TITLE
[GLPI 9.1] Issue with Bookmarks and default view

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#1321]
When a user want to change is default view, (click on a star) he get a message "Cannot update item: insufficient rights on the parent item(s)".

He need to unstar the actual default view, and select the new one to update this default bookmark.

Same issue with "normal","admin" and "post-only" profile.
All profil are set up with default permisions. (unchangged)

No issue with "super-admin" profile.
No backtrace.

**Comment by orthagh** [comment]
Hello @SylvainGuibert 

I can't replicate this issue on current 9.1/bugfixes, you should try with the last release: https://github.com/glpi-project/glpi/releases/tag/9.1.1

**Comment by SylvainGuibert** [comment]
I can replicate this issue on 9.1.1 release, but you need to change default bookmark twice (with an admin or lower profil)
![2016-11-23_15h48_53](https://cloud.githubusercontent.com/assets/16323410/20566162/67856d86-b194-11e6-9b15-6d69629dd596.png)

**Comment by trasher** [comment]
Seems to be solved already; cannot reproduce with 9.1/bugfixes, will be solved in 9.1.2

**Comment by vinz38500** [comment]
Hello
We are running 9.1.2 in production and we get the same issue.
We need to uncheck the yellow checked star to make it gray (unselect) and select the view we want to make as default.
Should be done when we select another default view

**Comment by mahkorayem** [comment]
Yess me too
I am using 9.1.2 and when I try to add a component to a computer I see the same issue

```
Error
Cannot update items: insufficient rights on the parent item(s)
```

![image](https://cloud.githubusercontent.com/assets/21154403/25798477/9b081b7a-33e1-11e7-96d2-6895470c13a2.png)

**Comment by tomolimo** [comment]
Hello,
This is still existing in 9.1.2 and in 9.2!
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello
The root cause is the checkAttachedItemChangesAllowed() method in commondbconnexity.class.php which returns false when current user can't CREATE or can't DELETE, or can't PURGE the bookmark.
And of course, as the user has not any of these rights, he can't set the default flag to the bookmark.

regards,
Tomolimo
