### ISSUE TITLE
Item and itemtype (other endpoint) are not visible in socket table of an item

### ISSUE THREAD

**Issue by rbrannath** [glpi-project/glpi#13214]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

In the socket table inside an item, there is currently no way to determine the other endpoint of an socket which is connected via a cable. The cable is visible and can be opened, but it would be better to have this information directly in this table.

### Steps To reproduce

1. Two items with a socket
2. Both items and sockets are connected via a cable
3. Go to one of items
4. Open the "sockets" tab
5. Other endpoint is not visibile

**Comment by rbrannath** [comment]
This PR will fix this: #13215

**Comment by cedric-anne** [comment]
Done in #13215
