### ISSUE TITLE
Traitement de masse

### ISSUE THREAD

**Issue by PLP1300** [glpi-project/glpi#13222]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4 et 10.0.5

### Bug description

Même problème sur les deux versions.
Lorsque je choisis en traitement de masse de changer un lieu ou un statut, seul le premier élément de la liste est changé. Les autres éléments non. Par ailleur, un cadena apparait devant le champ modifié (?) indiquant qu'il ne sera pas modifié par les imports... Alors que ces champs ne sont pas importés...

Par contre l'ajout de document en traitement par masse fonctionne correctement.

Cdlt

**Comment by trasher** [comment]
It's requested to write only inn english.
