### ISSUE TITLE
9.5.11 bug - Preview of html codes when pasting formatting

### ISSUE THREAD

**Issue by eriqueSDB** [glpi-project/glpi#13231]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

When copying some text already formatted in 9.5.11 it shows code instead of just formatting in the GLPI standard, as in the example below

![image](https://user-images.githubusercontent.com/102301295/200392295-5bfafbaf-7ba2-494b-9637-de036e875ed2.png)

![image](https://user-images.githubusercontent.com/102301295/200392484-a32260a8-5d40-4afc-85cf-80fd4452b120.png)

**Comment by cedric-anne** [comment]
Hi,

Can you check if #13226 fixes this issue ?

**Comment by trasher** [comment]
9.5 branch is security fixes only. Feel free to reopen ticket if you reproduce with latest 10.0 release.
