### ISSUE TITLE
New Ticket --> Set Requester

### ISSUE THREAD

**Issue by glpinewbi** [glpi-project/glpi#1323]
Hey, i have a Problem/Question about Creating new Ticket.

After upgrade to 9.1 i can't set another requester by opening a new Ticket.

Normal workflow:
1. User has Problem
2. User send an Email to our Hotline (GLPI) and get an answer...

Another workflow:
1. An user ask me and he had an question/Problem
2. I open in "New Ticket" and put normally the E-Mail adress of the user as requester.

But after upgraded as on top wrote i can't set. Always it puts me automatic as requester. I think before upgrading it works fine or am i wrong?

PS: no ldap, no users in glpi integrated, only us from Hotline Team.

**Comment by Armin83** [comment]
**Normal workflow:**
In 9.1.7 there is a bug solution for this problem.

Answer for **another workflow:**
Do you know the user setting `Pre-select me as a requester when creating a ticket` in personal settings

please close if you don't need further assistance.
