### ISSUE TITLE
Image aren't display when sent by mail collector GLPI 10.0.5

### ISSUE THREAD

**Issue by dronces** [glpi-project/glpi#13232]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.5

### Bug description

hello friends, I have the following problem, version 10, when I send an email to glpi and it becomes a ticket with an attached image, I cannot see this image inside the ticket, it comes out as an unavailable image

### Your GLPI setup information

GLPI 10.0.5 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:es_MX

**Comment by cedric-anne** [comment]
Hi,

Can you give an export of an email that cause this issue, in eml format?

**Comment by hebval** [comment]
@cedric-anne : It is any email that contains an image that has been copy-pasted. If the image is enclosed, it will appear as a document, but if the image is directly in the mail, as text, it will not load and display a small icon + "image".

**Comment by hebval** [comment]
> Email structure will depend on client used to sent the email. Can you give an export of an email that cause this issue, in eml format?

@cedric-anne 

(EML file are not available on github so I made it a TXT, you just have to rename it)

[Image not loading.txt](https://github.com/glpi-project/glpi/files/10131483/Image.not.loading.txt)

**Comment by cedric-anne** [comment]
#13505 will fix this.

**Comment by hebval** [comment]
@cedric-anne It's been made woth Outlook v1808 (Desktop version, we're not on O365).

**Comment by hebval** [comment]
@cedric-anne tried to edit src/MailCollector.php with the changes you did, and it's still not working on my side... :/

**Comment by cedric-anne** [comment]
> Are the _tests/emails-tests/37-image-with-octet-stream-type.eml & tests/imap/MailCollector.php_ files required ?
> 
> I don't have these files in my 10.0.5 install...

No, they are not.

**Comment by hebval** [comment]
The problem is from Outlook I think... With another webmail, the images are displaying correctly in the tickets...

**Comment by hebval** [comment]
My emails format is HTML

**Comment by dronces** [comment]
> On my side, it works.
> 
> ![image](https://user-images.githubusercontent.com/33253653/205074981-6c1944d4-ce24-44ef-b699-bcde7d8bd1dc.png)

Greetings my friend, how did you do it?
can you support us?
