### ISSUE TITLE
The ticket template and the actual result differ.

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#13241]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

I hid specific fields in the default ticket template. It looks like this:

![obraz](https://user-images.githubusercontent.com/68922721/200572798-82dd1c24-7dba-4b2c-9fcd-444166706ec5.png)

Using the formcreator, I initialized the ticket by assigning it this template. It looks like this:

![obraz](https://user-images.githubusercontent.com/68922721/200573072-1600729e-bab5-4ad3-bee3-4e2385305c68.png)

### Your GLPI setup information

<html><body>

Information about system installation and configuration
--
 
GLPI 10.0.4 ( => /var/www/html/glpi) Installation mode: TARBALL Current language:en_GB

</body>
</html>

<html><body>

Server
--
Operating system: Linux glpi 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.domain.com Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0 Server Software: (Ubuntu) 	Server Version: 8.0.31-0ubuntu0.20.04.1 	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION 	Parameters: glpiuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 PHP version (7.4.3) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (8.0.31) is supported. No files from previous GLPI version detected. The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server. PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/glpi/marketplace has been validated. Timezones seems loaded in database.

</body>
</html>

<html><body>

Plugins list
--
datainjection        Name: Data injection                 Version: 2.12.0     State: Installed / not activated                		Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.2     State: Enabled                                  		Install Method: Marketplace 	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                  		Install Method: Marketplace 	printercounters      Name: Printer counters               Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	webresources         Name: Web Resources                  Version: 2.0.2      State: Enabled                                  		Install Method: Marketplace 	tag                  Name: Zarządzanie słowami kluczowymi Version: 2.10.0     State: Enabled                                  		Install Method: Marketplace

</body>
</html>

**Comment by cedric-anne** [comment]
Do you reproduce this bug if ticket is created outside fomcreator context?

**Comment by WebGregGit** [comment]
Hi @cedric-anne 

Looks better after installing nightly build. Thank you.
