### ISSUE TITLE
"n" in ticket description when description updated

### ISSUE THREAD

**Issue by nathanks** [glpi-project/glpi#13244]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

When description field updated, GLPI adding "n" character for each existing line break.  Looks similar to an issue submitted back in 2017, issue #2870

![glpi_n_descrip](https://user-images.githubusercontent.com/1743255/200634027-15620273-93fa-44e7-b5e5-2696fe298867.png)

### Page URL

/front/ticket.form.php

### Steps To reproduce

Version 9.5.11
Create new ticket with test description and several line breaks.
Submit new ticket
Edit the description field, add more line breaks and submit.

### Your GLPI setup information

<html>
<body>

[code]   GLPI 9.5.11 ( => /var/www/glpi) Installation mode: TARBALL Current language:en_GB
--

Operating system: Linux glpi 4.15.0-176-generic #185-Ubuntu SMP Tue Mar 29 17:40:04 UTC 2022 x86_64 PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="512M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="16M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at  Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.40-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.40) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi/ has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated. Write access to /var/www/glpi/marketplace has been validated.

GLPI_ROOT: /var/www/glpi GLPI_CONFIG_DIR: /etc/glpi/ GLPI_VAR_DIR: /var/lib/glpi/files GLPI_LOG_DIR: /var/log/glpi GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/lib/glpi/files GLPI_CACHE_DIR: /var/lib/glpi/files/_cache GLPI_CRON_DIR: /var/lib/glpi/files/_cron GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales GLPI_LOCK_DIR: /var/lib/glpi/files/_lock GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins GLPI_RSS_DIR: /var/lib/glpi/files/_rss GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions GLPI_TMP_DIR: /var/lib/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/glpi/locales GLPI_VERSION: 9.5.11 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.10 in (/var/www/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.5 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/glpi/marketplace/oauthimap/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/glpi/marketplace/oauthimap/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.3 in (/usr/share/php)

Server: '', Port: '389', , Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=GLPI 		Auth,OU=service accounts,OU', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@smtp.xxx.com)

Name: '' Active: Yes 	Server: '{outlook.office365.com:993/imap-oauth-1/ssl/novalidate-cert}INBOX' Login: '' Password: Yes

fields               Name: Additionnal fields             Version: 1.13.0     State: Enabled 	datainjection        Name: Data injection                 Version: 2.8.0      State: Installed / not activated 	formcreator          Name: Form Creator                   Version: 2.10.2     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	invoice              Name: Invoice                        Version: 1.1.0      State: Installed / not activated 	oauthimap            Name: Oauth IMAP                     Version: 1.3.3      State: Enabled 	genericobject        Name: Objects management             Version: 2.9.2      State: Installed / not activated
[/code]

</body>
</html>

**Comment by RobertoMarcelino** [comment]
Same problem.

**Comment by stdonato** [comment]
Same problem.

**Comment by trasher** [comment]
Duplicates #13205
