### ISSUE TITLE
no domain support when selecting user in a CLI command

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#13251]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

When instaling a plugin from CLI with command bin/console glpi:plugin:install it is required to specify a user to proceed the installation.

When there are several users with the same identifier the command fails because it is not possible to specify the domain where the user is selected. A SQL error occurs.

![image](https://user-images.githubusercontent.com/14139801/200777850-c89dcc31-1174-4c76-96dc-4717a2330369.png)

### Steps To reproduce

1. configure a GLPI instance with a LDAP directory having a imported glpi user (keep the local glpi account)
3. try to install a plugin with CLI and specifi the argument -u glpi (or type glpi when prompted for a user)

**Comment by trasher** [comment]
A quick workaround would be to limit to local user accounts; but I think we should be able to use a non local user on cli commands

**Comment by btry** [comment]
We could add an extra optional argument or support for an expression similar to an email to specify a directory by its name

--auth-domain foo

--username bar@foo

The instance where I saw the problem has directories with names containing special characters like single quote. We must be careful with such cases.
