### ISSUE TITLE
[9.5.10 / 9.5.11] The TinyMCE menu has disappeared in the notification templates

### ISSUE THREAD

**Issue by luisjosemachado** [glpi-project/glpi#13256]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.10 / 9.5.11

### Bug description

The TinyMCE menu has disappeared in the notification templates and the field only shows the html code.

### Steps To reproduce

1. Go to Home>Notifications>Notification templates;
2. Select any template, "Alert domains", for example;
3. Go to tab "Template transitions";
4. Select "Default transition";
5. The "HTML Body of Email" field does not show the TinyMCE menu.

![image](https://user-images.githubusercontent.com/30940056/200830571-f71db9b4-3cdb-49f0-80ff-b0344d79baab.png)

### Your GLPI setup information

[code]   GLPI 9.5.11 ( => /var/www/chamadonti-h.jfce.jus.br) Installation mode: TARBALL Current language:en_GB
--

Operating system: Linux srvlglpi01-h.jfce.jus.br 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64 PHP 7.2.24 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, 	wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache () 	Mozilla/5.0 (X11; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0 Server Software: MariaDB Server 	Server Version: 10.3.35-MariaDB 	Server SQL Mode:  	Parameters: glpi_hml_adm@srvldbmaria01-h.jfce.jus.br/glpi_hml 	Host info: srvldbmaria01-h.jfce.jus.br via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is not present Database version seems correct (10.3.35) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_cache has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/config has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_cron has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_dumps has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_graphs has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_lock has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_pictures has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_plugins has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_rss has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_sessions has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_tmp has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/files/_uploads has been validated. Write access to /var/www/chamadonti-h.jfce.jus.br/marketplace has been validated. Web access to files directory is protected SELinux configuration is OK.

GLPI_ROOT: /var/www/chamadonti-h.jfce.jus.br GLPI_CONFIG_DIR: /var/www/chamadonti-h.jfce.jus.br/config GLPI_VAR_DIR: /var/www/chamadonti-h.jfce.jus.br/files GLPI_MARKETPLACE_DIR: /var/www/chamadonti-h.jfce.jus.br/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/chamadonti-h.jfce.jus.br/files GLPI_CACHE_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_cache GLPI_CRON_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_cron GLPI_DUMP_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_dumps GLPI_GRAPH_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_locales GLPI_LOCK_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_lock GLPI_LOG_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_log GLPI_PICTURE_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_plugins GLPI_RSS_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_rss GLPI_SESSION_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_sessions GLPI_TMP_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_tmp GLPI_UPLOAD_DIR: /var/www/chamadonti-h.jfce.jus.br/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/chamadonti-h.jfce.jus.br/locales GLPI_VERSION: 9.5.11 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022 GLPI_MOD_DIR: /var/www/chamadonti-h.jfce.jus.br/plugins/mod

htmlawed/htmlawed version 1.2.5 in (/var/www/chamadonti-h.jfce.jus.br/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.5 in (/var/www/chamadonti-h.jfce.jus.br/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/chamadonti-h.jfce.jus.br/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/chamadonti-h.jfce.jus.br/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/chamadonti-h.jfce.jus.br/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/chamadonti-h.jfce.jus.br/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/chamadonti-h.jfce.jus.br/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/chamadonti-h.jfce.jus.br/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/chamadonti-h.jfce.jus.br/vendor/sabre/http/lib) sabre/uri in (/var/www/chamadonti-h.jfce.jus.br/vendor/sabre/uri/lib) sabre/vobject in (/var/www/chamadonti-h.jfce.jus.br/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/chamadonti-h.jfce.jus.br/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/chamadonti-h.jfce.jus.br/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/chamadonti-h.jfce.jus.br/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/chamadonti-h.jfce.jus.br/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/chamadonti-h.jfce.jus.br/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/chamadonti-h.jfce.jus.br/vendor/elvanto/litemoji/src) symfony/console in (/var/www/chamadonti-h.jfce.jus.br/vendor/symfony/console) scssphp/scssphp in (/var/www/chamadonti-h.jfce.jus.br/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/chamadonti-h.jfce.jus.br/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/chamadonti-h.jfce.jus.br/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/chamadonti-h.jfce.jus.br/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/chamadonti-h.jfce.jus.br/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/chamadonti-h.jfce.jus.br/vendor/ramsey/uuid/src) psr/log in (/var/www/chamadonti-h.jfce.jus.br/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/chamadonti-h.jfce.jus.br/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/chamadonti-h.jfce.jus.br/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/chamadonti-h.jfce.jus.br/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/chamadonti-h.jfce.jus.br/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/chamadonti-h.jfce.jus.br/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/chamadonti-h.jfce.jus.br/vendor/paragonie/sodium_compat/src)

Server: 'jfce.jus.br', Port: '389', BaseDN: 'dc=jfce,dc=jus,dc=br', Connection filter: 		'(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'JFCE\autentica.ad', 		Use TLS: none Server: 'srvappv5.jfce.jus.br', Port: '389', BaseDN: 'ou=People,dc=jfce,dc=jus,dc=br', Connection filter: none, RootDN: 		'uid=samba,ou=People,dc=jfce,dc=jus,dc=br', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (chamado.homologa@exchange.jfce.jus.br)

Name: 'chamado.homologa@jfce.jus.br' Active: Yes 	Server: '{exchange.jfce.jus.br/imap/ssl/validate-cert/tls}' Login: 'chamado.homologa' Password: Yes

advancedplanning     Name: advancedplanning               Version: 1.0.0      State: Enabled 	news                 Name: Alertas                        Version: 1.9.1      State: Enabled 	fields               Name: Campos adicionais              Version: 1.13.0     State: Enabled 	behaviors            Name: Comportamentos                 Version: 2.6.0      State: Enabled 	datainjection        Name: Data injection                 Version: 2.10.2     State: Enabled 	escalade             Name: Escalonamento                  Version: 2.7.2      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Enabled 	tag                  Name: Gerenciamento de Etiquetas     Version: 2.8.3      State: Enabled 	genericobject        Name: Gerenciamento de objetos       Version: 2.11.1     State: Enabled 	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled 	tasklists            Name: Lista de tarefas               Version: 1.6.2      State: Enabled 	moreticket           Name: More ticket                    Version: 1.6.1      State: Enabled 	dashboard            Name: Painel                         Version: 1.0.2      State: Enabled 	watermark            Name: Watermark                      Version: 1.0.0      State: Enabled
[/code]

**Comment by FRANCOIS50** [comment]
Hi I have the same behaviour in my system GLPI version 9.5.11
Do you have some Ideas where it come from?
Regards

**Comment by cedric-anne** [comment]
Fixed in GLPI 10.0 by 5c6bed16169da6e48a836ab364160b1ba0a79707.

Patch in 9.5 is probably:
```diff
diff --git a/inc/notificationtemplatetranslation.class.php b/inc/notificationtemplatetranslation.class.php
index 8b853e4b65..5466e38caf 100644
--- a/inc/notificationtemplatetranslation.class.php
+++ b/inc/notificationtemplatetranslation.class.php
@@ -104,8 +104,6 @@ class NotificationTemplateTranslation extends CommonDBChild {
       $template = new NotificationTemplate();
       $template->getFromDB($notificationtemplates_id);
 
-      Html::initEditorSystem('content_html');
-
       $this->showFormHeader($options);
 
       echo "<tr class='tab_bg_1'>";
@@ -152,8 +150,15 @@ class NotificationTemplateTranslation extends CommonDBChild {
       echo "<td>";
       echo __('Email HTML body');
       echo "</td><td colspan='3'>";
-      echo "<textarea cols='100' rows='15' name='content_html'>".$this->fields["content_html"];
-      echo "</textarea>";
+      $content_id = "content$rand";
+      Html::textarea(['name'              => 'content_html',
+                         'value'             => $this->fields['content_html'],
+                         'rand'              => $rand,
+                         'editor_id'         => $content_id,
+                         'enable_fileupload' => false,
+                         'enable_richtext'   => true,
+                         'cols'              => 100,
+                         'rows'              => 15]);
       echo "<input type='hidden' name='notificationtemplates_id' value='".
              $template->getField('id')."'>";
       echo "</td></tr>";
```

**Comment by felag** [comment]
@cedric-anne Hello, is there a patch planned for 9.5 versions ?
(or is it already corrected in 9.5 ?)

**Comment by cedric-anne** [comment]
See c5f003807a1c7baa7551404417c2c3652255bce7

**Comment by felag** [comment]
Excellent, thanks !
