### ISSUE TITLE
GLPI 9.5.11: difficulty to access browser context menu

### ISSUE THREAD

**Issue by nsalguero** [glpi-project/glpi#13254]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

Hi,

Since TinyMCE upgrade from 4.9.11 to 5.10.6, right-click in a text area does not offer access to browser context menu anymore (to access browser spellchecker, for instance).  After looking at the documentation of TinyMCE, I found that it is needed to use Ctrl+right-click to access browser context menu but it is not very easy for a normal user to find that information.

This patch restores the previous behaviour:
```
@@ -3903,7 +3903,9 @@ JS;
                   'table',
 
                   'glpi_upload_doc', // glpi_upload_doc specific plugin to upload files
-               ],
+              ],
+
+               contextmenu: false,
 
                // Appearance
                branding: false,
```

Best regards,

Nicolas Salguero.

**Comment by cconard96** [comment]
This was already fixed/changed for GLPI 10 #12804

GLPI 9.5 no longer receives bug fixes (security fixes only).
