### ISSUE TITLE
glpi 9.5.11 wrong display of HTML ticket texte after ticket saving

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#13266]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

After each Ticket saving, each empty line in the description become the character "n" see screenshot bellow:
![image](https://user-images.githubusercontent.com/12511115/201023035-edd01542-8a12-42ad-b091-59679fbc6c4a.png)

This strange behaviour appeared after the migration from versiln9.59 to 9.5.11 

### Steps To reproduce

1. Open a ticket
2. Save it
3. Character "N" is added to each empty line in the texte of the description.
(This problem appears with different brothers like edge; Firefox and google chrome)

### Your GLPI setup information

<html>
<body>

[code]   GLPI 9.5.11 (/glpi => /usr/share/glpi) Installation mode: TARBALL Current language:fr_FR
--

Operating system: Linux chmsglpi 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 PHP 7.2.34-21+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, 	json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, 	session, shmop, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, 	xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="90" memory_limit="256M" post_max_size="200M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.46 (Ubuntu) (Apache/2.4.46 (Ubuntu) Server at chmsglpi.emea.busch.inet Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.35 Server Software: (Ubuntu) 	Server Version: 8.0.31-0ubuntu0.20.04.1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is not present bz2 extension is not present sodium extension is installed Database version seems correct (8.0.31) - Perfect!  The log file has been created successfully. Write access to /usr/share/glpi/files/_cache has been validated. Write access to /usr/share/glpi/config has been validated. Write access to /usr/share/glpi/files/_cron has been validated. Write access to /usr/share/glpi/files has been validated. Write access to /usr/share/glpi/files/_dumps has been validated. Write access to /usr/share/glpi/files/_graphs has been validated. Write access to /usr/share/glpi/files/_lock has been validated. Write access to /usr/share/glpi/files/_pictures has been validated. Write access to /usr/share/glpi/files/_plugins has been validated. Write access to /usr/share/glpi/files/_rss has been validated. Write access to /usr/share/glpi/files/_sessions has been validated. Write access to /usr/share/glpi/files/_tmp has been validated. Write access to /usr/share/glpi/files/_uploads has been validated. Write access to /usr/share/glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: /usr/share/glpi GLPI_CONFIG_DIR: /usr/share/glpi/config GLPI_VAR_DIR: /usr/share/glpi/files GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /usr/share/glpi/files GLPI_CACHE_DIR: /usr/share/glpi/files/_cache GLPI_CRON_DIR: /usr/share/glpi/files/_cron GLPI_DUMP_DIR: /usr/share/glpi/files/_dumps GLPI_GRAPH_DIR: /usr/share/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /usr/share/glpi/files/_locales GLPI_LOCK_DIR: /usr/share/glpi/files/_lock GLPI_LOG_DIR: /usr/share/glpi/files/_log GLPI_PICTURE_DIR: /usr/share/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /usr/share/glpi/files/_plugins GLPI_RSS_DIR: /usr/share/glpi/files/_rss GLPI_SESSION_DIR: /usr/share/glpi/files/_sessions GLPI_TMP_DIR: /usr/share/glpi/files/_tmp GLPI_UPLOAD_DIR: /usr/share/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/share/glpi/locales GLPI_VERSION: 9.5.11 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.5 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/usr/share/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/usr/share/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)

Server: 'ldaps://10.8.4.63', Port: '636', BaseDN: 'OU=CHM-Users,OU=CHM,DC=emea,DC=busch,DC=inet', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\chm.glpi', Use 		TLS: none Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Composites,OU=Utilisateurs,DC=busch,DC=ch', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'administrateur', Use 		TLS: none Server: '172.22.0.20', Port: '389', BaseDN: 'DC=busch,DC=ch', Connection filter: none, RootDN: 'administrateur', Use TLS: none Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Clean Air,OU=Utilisateurs,DC=busch,DC=ch', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'administrateur', Use 		TLS: none Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Ateliers_Busch,OU=Utilisateurs,DC=busch,DC=ch', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'administrateur', Use 		TLS: none Server: '172.22.0.26', Port: '389', BaseDN: 'OU=Utilisateurs_Windows_7_Enteo_(dossiers_redirigés),DC=busch,DC=ch', Connection 		filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'administrateur', Use TLS: none Server: 'ldaps://10.8.4.63', Port: '636', BaseDN: 'OU=CHA-Users,OU=CHA,DC=emea,DC=busch,DC=inet', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\cha.glpi', Use 		TLS: none Server: '172.22.0.125', Port: '389', BaseDN: 'OU=CHA-Groups,OU=CHA,DC=emea,DC=busch,DC=inet', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\cha.glpi', Use 		TLS: none Server: 'ldaps://10.8.4.63', Port: '636', BaseDN: 'OU=CHC-Users,OU=CHC,DC=emea,DC=busch,DC=inet', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'EMEA\chc.glpi', Use 		TLS: none

Not active

Way of sending emails: SMTP (anonymous@mail.buschvacuum.com)

Name: 'support@busch.ch' Active: No 	Server: '{172.22.4.99:110/pop/notls}inbox' Login: 'support' Password: Yes Name: 'test.user@busch.ch' Active: No 	Server: '{172.22.4.99:110/pop/notls}inbox' Login: 'User test' Password: Yes Name: 'support@busch.ch' Active: No 	Server: '{mail.busch.inet:993/imap/ssl/novalidate-cert/notls}INBOX' Login: 'support@busch.ch' Password: Yes Name: 'support@busch.ch' Active: No 	Server: '{glcs-ex01.busch.inet:993/imap/ssl/novalidate-cert/notls}INBOX' Login: 'support@busch.ch' Password: Yes Name: 'support@busch.ch' Active: No 	Server: '{10.118.14.95:995/pop/ssl/novalidate-cert/tls}INBOX' Login: 'support@busch.ch' Password: Yes Name: 'support@busch.ch' Active: No 	Server: '{10.1.5.19:993/imap/ssl/novalidate-cert/notls}INBOX' Login: 'support@busch.ch' Password: Yes

additionalalerts     Name: Alertes supplémentaires        Version: 2.3.0      State: Enabled 	shellcommands        Name: Commandes Shell                Version: 3.0.0      State: Enabled 	behaviors            Name: Comportements                  Version: 2.5.0      State: Enabled 	uninstall            Name: Cycle de vie des matériels (un Version: 2.7.3      State: Enabled 	datainjection        Name: Data Injection                 Version: 2.10.2     State: Enabled 	formcreator          Name: Form Creator                   Version: 2.12.5     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.7.4      State: Enabled 	reports              Name: Rapports                       Version: 1.14.1     State: Enabled 	reservation          Name: Reservation                    Version: 2.3.8      State: Enabled 	resources            Name: Ressources humaines            Version: 2.7.0      State: Enabled 	ticketcleaner        Name: Ticket Cleaner                 Version: 3.0.0      State: Enabled

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by cedric-anne** [comment]
Duplices #13205, #13244, #13259, ....
