### ISSUE TITLE
Ticket ID does not appear in the support screen column (Linked tickets)

### ISSUE THREAD

**Issue by wc55** [glpi-project/glpi#13265]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

I don't know if it's a bug exactly, but by making filters on the ticket screen, only the ticket's title is displayed, but I believe that if it were possible, the ticket's id would also be displayed.

In this case, I also use the form creator, and that's why the titles end up looking similar, and it's kind of hard to find the titles.

I enabled the option to display the ids, but even so, it does not appear in this part.

If it is not a bug, I suggest that the ticket id be included next to the ticket title, and if possible, without necessarily enabling the display of GLPI ids.

### Page URL

/front/ticket.php

### Steps To reproduce

1 - Access the call screen.
2 - Search using some parameters that display the title of related tickets. Here's an example

![image](https://user-images.githubusercontent.com/106084399/200907437-e6d310d8-4051-4bef-aa39-32c63904f761.png)

>>>
In this case, in my tests, I put "Test x", so in the column "Linked tickets - All Linked Tickets" a number appears on the side, but you can notice that one of them only has "Test"

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.5 (/glpi2 => C:\xampp\htdocs\glpi2)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT UNOUNIV-VFNBAD8 10.0 build 19044 (Windows 10) AMD64
PHP 8.1.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="1024M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at localhost
	Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpidb2
	Host info: localhost via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi2/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi2/config has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi2/files has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi2/files/_uploads has been validated.
The following directories should be placed outside "C:\xampp\htdocs\glpi2":
‣ "C:\xampp\htdocs\glpi2/files" ("GLPI_VAR_DIR")
‣ "C:\xampp\htdocs\glpi2\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\glpi2/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\xampp\\htdocs\\glpi2"
GLPI_CONFIG_DIR: "C:\\xampp\\htdocs\\glpi2/config"
GLPI_VAR_DIR: "C:\\xampp\\htdocs\\glpi2/files"
GLPI_MARKETPLACE_DIR: "C:\\xampp\\htdocs\\glpi2/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "C:\\xampp\\htdocs\\glpi2/files"
GLPI_CACHE_DIR: "C:\\xampp\\htdocs\\glpi2/files/_cache"
GLPI_CRON_DIR: "C:\\xampp\\htdocs\\glpi2/files/_cron"
GLPI_DUMP_DIR: "C:\\xampp\\htdocs\\glpi2/files/_dumps"
GLPI_GRAPH_DIR: "C:\\xampp\\htdocs\\glpi2/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\xampp\\htdocs\\glpi2/files/_locales"
GLPI_LOCK_DIR: "C:\\xampp\\htdocs\\glpi2/files/_lock"
GLPI_LOG_DIR: "C:\\xampp\\htdocs\\glpi2/files/_log"
GLPI_PICTURE_DIR: "C:\\xampp\\htdocs\\glpi2/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\xampp\\htdocs\\glpi2/files/_plugins"
GLPI_RSS_DIR: "C:\\xampp\\htdocs\\glpi2/files/_rss"
GLPI_SESSION_DIR: "C:\\xampp\\htdocs\\glpi2/files/_sessions"
GLPI_TMP_DIR: "C:\\xampp\\htdocs\\glpi2/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\xampp\\htdocs\\glpi2/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\xampp\\htdocs\\glpi2/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "C:\\xampp\\htdocs\\glpi2/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (C:\xampp\htdocs\glpi2\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp\htdocs\glpi2\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\glpi2\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.5.0 in (C:\xampp\htdocs\glpi2\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi2\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi2\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi2\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\glpi2\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\glpi2\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\glpi2\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\glpi2\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\glpi2\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\glpi2\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\glpi2\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi2\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\glpi2\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\glpi2\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi2\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\glpi2\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\glpi2\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\glpi2\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\glpi2\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp\htdocs\glpi2\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp\htdocs\glpi2\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\glpi2\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\glpi2\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\glpi2\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\glpi2\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\glpi2\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\glpi2\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\glpi2\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\glpi2\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\glpi2\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\glpi2\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\glpi2\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\glpi2\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\glpi2\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\glpi2\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\glpi2\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\glpi2\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (C:\xampp\htdocs\glpi2\vendor\symfony\polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

### Anything else?

In this case, in my tests, I put "Test x", so in the column "Linked tickets - All Linked Tickets" a number appears on the side, but you can notice that one of them only has "Test".

**Comment by wc55** [comment]
Hi

In version 10.0.5 the problem still happens.

**Comment by cedric-anne** [comment]
Hi,

I confirm that the ID should be shown next to the ticket name when your preferences are set up to show GLPI ids, so it is a bug.

**Comment by serviceticst** [comment]
"In the simplified interface, it doesn't appear.

![image](https://github.com/glpi-project/glpi/assets/70910492/1c96b6e8-5585-4feb-9f36-3afe4df6d13a)

In the standard interface, it does appear. Is there any adjustment we can make?"

![image](https://github.com/glpi-project/glpi/assets/70910492/7f1b87c9-4caf-4268-9290-218c0ccc4625)
