### ISSUE TITLE
Blacklisted mail content field removes/add/changes html after saving

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#13276]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi,

In Configuration>intitulés>Contenu de courriel interdit

1° add a clean text and save it in the content field, then there is no html.
2° Come back to the "Contenu de courriel interdit" listing and click on the item that you created and see that` <p> and </p>` tags were added.

Alternative version of the bug : 

1°add html content and save it in the content field
2°Come back to the "Contenu de courriel interdit" listing and click on the item that you created and see that your html was either removed or replaced by different tags like `&lt;br&gt;<br />    &lt;/div&gt;</p>`

Result : I cannot remove the thunderbird default answer when you answer to an email :
<div class="moz-cite-prefix">On 10/11/22 22:01, email sender
      wrote:<br>
    </div>

### Your GLPI setup information

Operating system: Linux4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64
PHP 7.4.33 cgi-fcgi

**Comment by joomlafun** [comment]
Problem persists on 10.0.5, not so important for me though, I erase content in mailcollector with 
    
$tkt['content'] = preg_replace('/' . preg_quote('On') .
                          '.*?' .
                          preg_quote('wrote:') . '/', '', $tkt['content']);
                          
                          if($tkt['_users_id_requester'] == 0)

**Comment by cedric-anne** [comment]
I confirm there is a bug here.

Sometimes, but not on every page load, I got a `tinyMCE is not defined` JS error.

However, the content field should probably not use the rich text editor feature. Indeed, due to the fact that is it will be used in strict comparisons, blacklisted content should not be "reformated" by the rich text editor or the corresponding cleaning process. So here we should probably have a raw textarea field.

**Comment by trasher** [comment]
Please try #14337
