### ISSUE TITLE
Add markdown support on KB entries

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1327]
Plain HTML is probably less secure and a bit harder to write for users; a markdown support would be better.

Some things to take care of:
* the WYSIWYG editor must support mardkdown (1)
* we probably need some config somewhere (or per entry?) because HTLM vs MD rendering will not be compatible.

(1) there are numerous specific editors that handle markdown, but we should probably take a look on just tinymce, to be consistent.

See #912 .

**Comment by tomolimo** [comment]
Why not use an editor like for tickets?
It will minimize the development and minimize the learning curve for end-users too.
And moreover, it will be consistant with the rest of GLPi (ticketing)

**Comment by trasher** [comment]
I guess that is  tinymce which is used for tickets; so, yes, we should use it (if it makes the job as expeced, of course!)

**Comment by tomolimo** [comment]
in fact, my idea is to use it the same way than for tickets, so it means no markdown, but rich text (or html), and today (in 9.1) it is already like that using rich text (or internally html), this is perfect, MD is really not so rich than HTML, and is not easier to use when using such tools like tinymce.
What is really missing in KB today is the copy paste (or drag drop) of images

**Comment by SilentBob999** [comment]
I would had like MD. Documenting code with the current tool is kind of a pain for me at the moment...
