### ISSUE TITLE
Bug na versão 10.0.5

### ISSUE THREAD

**Issue by amandagabrielaa** [glpi-project/glpi#13277]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Quando adicionamos um novo acompanhamento em um chamado, o último comentário fica restrito em uma quantidade x de linhas e o restante força para abrir clicando nos três pontos destacados em vermelho abaixo:

![vfsgvds](https://user-images.githubusercontent.com/98328281/201426348-95466156-9305-4086-9d0a-5726259f0771.png)

Assim que é clicado nos três pontos para abrir todo o acompanhamento, os comentários acimas deste somem até que o cash da página seja recarregado. 

![image](https://user-images.githubusercontent.com/98328281/201426522-4942d506-3b95-4444-87e9-c0b4d0cb31cf.png)

### Page URL

https://suporte.sparkag.com.br/

### Steps To reproduce

Quando adicionamos um novo acompanhamento em um chamado, o último comentário fica restrito em uma quantidade x de linhas e o restante força para abrir clicando nos três pontos destacados em vermelho abaixo:

![vfsgvds](https://user-images.githubusercontent.com/98328281/201426348-95466156-9305-4086-9d0a-5726259f0771.png)

Assim que é clicado nos três pontos para abrir todo o acompanhamento, os comentários acimas deste somem até que o cash da página seja recarregado. 

![image](https://user-images.githubusercontent.com/98328281/201426522-4942d506-3b95-4444-87e9-c0b4d0cb31cf.png)

**Comment by trasher** [comment]
It is requested to write in english only.
