### ISSUE TITLE
Error in version 10.0.5

### ISSUE THREAD

**Issue by amandagabrielaa** [glpi-project/glpi#13287]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When a new follow-up on a ticket is made, the last comment is restricted to a number of lines and the remaining force to open by clicking on the three points highlighted in red below:

![image](https://user-images.githubusercontent.com/98328281/201649993-01c7ab61-a497-4005-a79b-8e8f6f2176a0.png)

As soon as the three dots are clicked to open the entire track, the comments above it disappear until the page's cash is reloaded.

![image](https://user-images.githubusercontent.com/98328281/201650180-b03d2836-aa55-43a1-af08-09eaedd62b47.png)

### Relevant log output

```shell
We couldn't find any reference log on the subject.
```

### Steps To reproduce

Add an interaction to a ticket that occupies more than 10 lines -> Only the first 9 lines will appear, the rest will be necessary to click on the three dots that will appear below the comment. -> When carrying out this process, just go up to the top of the call, the images, documents and texts are corrupted.

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/98328281/201655824-62c4ae2f-801e-447f-865a-2b386b708d6e.png)
![image](https://user-images.githubusercontent.com/98328281/201656822-f120e943-0291-4465-9c17-6c5e1b3d4f8a.png)
![image](https://user-images.githubusercontent.com/98328281/201656865-ce7e79c4-a99e-4668-89c8-68f5e0a3989d.png)
![image](https://user-images.githubusercontent.com/98328281/201656950-e79c625f-fbc9-494e-9ca2-e29438b30182.png)
![image](https://user-images.githubusercontent.com/98328281/201657020-400998e6-ba95-48c2-b4d8-9dd1fc934bbc.png)

**Comment by cconard96** [comment]
I cannot recreate the issue. Please check the browser console (F12 key > Console tab) to see if there are any warnings or errors showing.

**Comment by trasher** [comment]
No feedback, I close
