### ISSUE TITLE
The problem of upgrading to version 10.0.5.

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#13286]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4-dev

### Bug description

Hello,
There is a problem upgrading from the current version 10.0.4-dev to version 10.0.5.
![error_update](https://user-images.githubusercontent.com/97535165/201647398-3b08ad87-0459-43b5-85e4-e6324f8da1d7.png)

When I try to update from the night build(10.0-e5ffbbb.tar.gz), I get an error
![glpi_update](https://user-images.githubusercontent.com/97535165/201647299-df257376-cf5b-4712-8635-28a68464028e.png)

### Relevant log output

```shell
migration_to_10.0.4.log:
2022-09-27 17:24:56 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-09-27 17:24:56 [9@glpi.localhost.com]
0 seconds for "Change of the database layout - glpi_tickets" @ 2022-10-06 11:32:14 [@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-10-06 11:32:14 [@glpi.localhost.com ]
0 seconds for "Changing the DB structure - glpi_items_remotemanagements" @ 2022-10-06 11:32:14 [@glpi.localhost.com ]
0 seconds for "Changing the DB structure - glpi_items_devicecameras_imageresolutions" @ 2022-10-06 11:32:14 [@glpi.localhost.com ]
0 seconds for "Changing the DB structure - glpi_items_devicecameras_imageformats" @ 2022-10-06 11:32:14 [@glpi.localhost.com ]
0 seconds for "Settings values added for cas_version (core)." @ 2022-10-10 11:13:59 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-10-10 11:13:59 [9@glpi.localhost.com]
0 seconds for "Change of the database layout - glpi_computers" @ 2022-10-10 11:13:59 [9@glpi.localhost.com]
0 seconds for "Change of the database layout - glpi_dashboards_items" @ 2022-10-10 11:13:59 [9@glpi.localhost.com]
0 seconds for "Change of the database layout - glpi_items_operatingsystems" @ 2022-10-10 11:13:59 [9@glpi.localhost.com]
0 seconds for "Change of the database layout - glpi_agents" @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Changing the database structure - glpi_dashboards_items" @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Changing the database structure - glpi_agents" @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Settings values added for enabled_inventory (inventory)." @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Task completed." @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Changing the database structure - glpi_dashboards_items" @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Task completed." @ 

migration_to_10.0.5.log
2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Task completed." @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Task completed." @ 

migration_to_10.0.6.log:
2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Task completed." @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:53:37 [9@glpi.localhost.com]
0 seconds for "Task completed." @ 

migration_to_10.1.0.log:
2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Work in progress..." @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Changing the database structure - glpi_entities" @ 2022-11-14 12:49:14 [9@glpi.localhost.com]
0 seconds for "Database structure change - glpi_entities" @ 

warning_during_migration_to_10.1.0.log:
2022-11-14 12:49:14 [9@glpi.localhost.com]
New rights has been added for rule_change, you should review ACLs after update @ 

php-errors.log:
[2022-11-14 12:53:37] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Undefined constant CommonITILObject::SURVEY in /var/www/html/glpi/install/migrations/update_10.0.x_to_10.1.0/changesatisfactions.php at line 128
  Backtrace :
  install/migrations/update_10.0.x_to_10.1.0.php:59  require()
  src/Update.php:267                                 update100xto1010()
  install/update.php:143                             Update->doUpdates()
  install/update.php:252                             doUpdateDb()
```

### Your GLPI setup information

<details><summary>System, installation and configuration information</summary><pre>GLPI 10.0.4-dev ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:ru_RU

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.localhost.com 5.4.17-2136.311.6.1.el8uek.x86_64 #2 SMP Thu Sep 22 19:29:28 PDT 2022 x86_64
PHP 8.0.25 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysql, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="24M" safe_mode="" session.save_handler="files"
	upload_max_filesize="24M" 
Software: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/GLPI
	Host info: Localhost via UNIX socket
	
PHP version (8.0.25) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.4-dev"
GLPI_SCHEMA_VERSION: "10.0.4-dev@0a80a403942e42b997303981aed9ce852f029bd0"
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.0.104.2', Port: '3268', BaseDN: 'DC=localhost,DC=ru', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=ldapsearch-glpi,OU=Special,DC=localhost,DC=ru', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mail2.localhost.com)

</details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated               
		Install Method: Marketplace
	archisw              Name: Apps structures                Version: 2.2.9      State: Installed / not activated               
		Install Method: Marketplace
	archibp              Name: Business Processes             Version: 1.0.7      State: Not installed                           
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	connections          Name: Connections                    Version: 10.0.0     State: Installed / not activated               
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.9      State: Installed / not activated               
		Install Method: Marketplace
	dataflows            Name: Dataflows                      Version: 2.2.13     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.9      State: Installed / not activated               
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.2      State: Enabled                                 
		Install Method: Marketplace
	escalade             Name: Escalation                     Version: 2.8.0      State: Installed / not activated               
		Install Method: Marketplace
	financialreports     Name: Financial reports              Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Not installed                           
		Install Method: Marketplace
	reports              Name: Reports                        Version: 1.14.1     State: Installed / not activated               
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	typology             Name: Typologies                     Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Подробные отчеты          Version: 1.8.2      State: Enabled                         
		        Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

The update process is trying to execute the migration to GLPI 10.1.0. Unless you copied the `install` directory from GLPI 10.1 into GLPI 10.0.5 files, this error should not happen. Did you manipulate GLPI source files ?

**Comment by trasher** [comment]
Agree with Cedric; error is from a 10.1.0 update try; this issue is not valid.

**Comment by Badkempachi** [comment]
> Hi,
> 
> The update process is trying to execute the migration to GLPI 10.1.0. Unless you copied the `install` directory from GLPI 10.1 into GLPI 10.0.5 files, this error should not happen. Did you manipulate GLPI source files ?

Hi, I haven't done any manipulations with files, I have version 10.0.4-dev installed, when I try to upgrade to release version 10.0.5, I get this error, if I try to upgrade from a nightly build, the situation is similar. The question arises why this happens, while the upgrade to version 10.1.0-dev is successful.

**Comment by cedric-anne** [comment]
10.0 nightly build archive does not contains `install/migrations/update_10.0.x_to_10.1.0.php` file.
