### ISSUE TITLE
Text editor context menu changed

### ISSUE THREAD

**Issue by Lacro59** [glpi-project/glpi#13288]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

With the update of the TinyMce component, the contextual menu is that of the editor and not of the browser.
![image](https://user-images.githubusercontent.com/124054/201658032-d4a2e217-a80f-44da-a011-df6d60278efb.png)

To solve my issue, I've set the options at false
https://www.tiny.cloud/docs/ui-components/contextmenu/

```            
tinyMCE.init({
   selector: '#{$name}',

   plugins: [
	  'autoresize',
	  'code',
	  'directionality',
	  'fullscreen',
	  'image',
	  'link',
	  'lists',
	  'paste',
	  'searchreplace',
	  'table',

	  'glpi_upload_doc', // glpi_upload_doc specific plugin to upload files
   ],

   contextmenu: false,
```

**Comment by cedric-anne** [comment]
See cb6d3eb053988066ad435dbf738fc8042ceffff2
