### ISSUE TITLE
Asset Global

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1329]
http://forum.glpi-project.org/viewtopic.php?id=156103

I confirm this bug only in 9.1.x

**Comment by orthagh** [comment]
- SoftwareLicences added in 9.1 in global list without contact field.

- we could add in 9.1.3 (milestone moved) the missing field
- in master, we need to add asap a unit test for global searchoptions (test all) to avoid future add in global itemtype with missing fields

**Comment by trasher** [comment]
ping @wawax
