### ISSUE TITLE
GLPI 10.0.5, Operating system version not being updated.

### ISSUE THREAD

**Issue by supertramp4** [glpi-project/glpi#13298]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Please refer to forum question [https://forum.glpi-project.org/viewtopic.php?id=285391](url)

When using the built in GLPI Inventory, 
I have recently upgraded a client computer from Windows 10 to Windows 11
The Computer was originally imported when on Windows 10

The GLPI Agent is correctly reporting that the pc is now on Win 11

----snip from inventory file----
```json
"operatingsystem":
{
   "arch":"64-bit",
   "boot_time":"2022-11-09 11:15:44",
   "dns_domain":"<deleted>",
   "fqdn":"<deleted>",
   "full_name":"Microsoft Windows 11 Pro",
   "install_date":"2022-11-09 08:26:08",
   "kernel_name":"MSWin32",
   "kernel_version":"10.0.22621",
   "name":"Windows",
   "timezone":
   {
      "name":"Europe\/London",
      "offset":"+0000"
   },
   "version":"22H2"
}
```
----------------------------------

GLPI is not updating the following fields :

Computer :Operating System : Name - ( Still showing Microsoft Windows 10 Pro )
Computer :Operating System : install_date  - ( Still showing 2022-02-09 )
Computer :Operating System : kernel - ( Still showing 10.0.19044 )
Computer :Operating System : version  - ( Still showing 21H2 )

The computer is getting regular updates from the GLPI Agent i.e.
2022-11-10 08:07    Computer update (by serial + uuid)       
2022-11-09 17:07    Computer update (by serial + uuid)       
2022-11-09 13:13    Computer update (by serial + uuid)       
2022-11-09 09:19    Computer update (by serial + uuid)       
2022-11-09 09:00    Computer update (by serial + uuid)       
2022-11-08 17:32    Computer update (by serial + uuid)       
2022-11-08 16:13    Computer import (by serial + uuid)   

One final note, a Windows 11 PC that is newly "Imported" by the GLPI agent, correctly reports the OS Name, Install date, Kernal, and Version

### Relevant log output

```shell
There are no entries in the log files for this.
```

**Comment by stonebuzz** [comment]
Hi @supertramp4 

Can you retry with latest GLPI nighlty build

https://nightly.glpi-project.org/glpi/

**Comment by supertramp4** [comment]
Hi, sorry, is it the "Main", or the "10.0" Version i need to try

**Comment by trasher** [comment]
10.0

**Comment by emayoral** [comment]
Very similar issue here.

Several VMware ESXi servers. Their inventory is generated with
glpi-esx
and then injected with
glpi-injector

gpi version 10.0.5
glpi-agent and glpi-agent-task-esx version 1.4

No plugins installed.


Exact same inventory file.

Injected with glpi-injector -> OS does not get updated
Imported from the web interface (Administration -> Inventory -> Import from file) -> OS does get updated

[llei857.arsyslan.es-2022-11-28-07-16-06.ocs.zip](https://github.com/glpi-project/glpi/files/10101030/llei857.arsyslan.es-2022-11-28-07-16-06.ocs.zip)

**Comment by trasher** [comment]
I'm still not abloe to reproduce with current nigthly.

**Comment by trasher** [comment]
Also, I'll be very surprised with any difference using file upload, direct php call to `front/inventory.php` or injector call to `front/inventory.php`. All test I made until now produces the exact same result, and there is nothing is the code that would cause any difference.

**Comment by trasher** [comment]
To make thing clear for everyone:
1- use latest GLPI 10.0 nightly build, on a fresh database install (no db update, no existing computer nor os)
2- avoid updating by hand imported asset (use two distinct inventory files with different OS)
3- make sure you do not have any errors trying to import (of course, an error during import may cause OS not to be updated, even if this is not OS related...).

**Comment by supertramp4** [comment]
Hi Trasher,
The problem is not the initial import - I agree the IMPORT works correctly, The problem is the subsequent GLPI UPDATE.
So If the initial import ( in my case ) was windows 10, i then upgraded my PC to Win 11, then GLPI's UPDATE is not working when the agent pushes the data into GLPI. For some reason if its manually imported through the GUI, then the Update works.
HTH

**Comment by trasher** [comment]
Yes, what I teste dis an OS update, anbnd OS was properly updated.

**Comment by supertramp4** [comment]
Hi Trasher,
I have just changed the client GLPI Agent Server address ( as per ) [https://glpi-agent.readthedocs.io/en/latest/configuration.html](url)
from http://<domain>/
to http://<domain/front/inventory.php, and it's just updated the OS information.
@emayoral, Are you able to check your client config, and see if this works for you ?

**Comment by emayoral** [comment]
You are right, @supertramp4   

Tried with a different ESXi

`glpi-injector --no-ssl-check -u https://glpiservername/ -v -f inventoryfile.ocs`    <-- Does not update OS field
`glpi-injector --no-ssl-check -u https://glpiservername/front/inventory.php  -v -f inventoryfile.ocs`  <- Does update OS field

Same server, same inventory file.

https://glpi-agent.readthedocs.io/en/latest/configuration.html  suggests for URLs should be equivalent, but they are not.


> If you're not using GlpiInventory plugin:
> 
> Your server URL should look like: https://my-glpi-server/, or https://my-glpi-server/front/inventory.php
>

**Comment by trasher** [comment]
I can confirm the used URL is the cause

**Comment by cedric-anne** [comment]
@emayoral @supertramp4 

#13436 should fix this issue. Could you confirm ?
