### ISSUE TITLE
Uncaught Exception ErrorException: preg_match_all(): Unknown modifier ']' in /usr/share/glpi/src/RuleCriteria.php at line 494

### ISSUE THREAD

**Issue by gianlucapiccolo** [glpi-project/glpi#13295]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

The import of ocsinventoryng data (using the GLPI ocsinventoryng integration plugin) fails due to the following error:
`Uncaught Exception ErrorException: preg_match_all(): Unknown modifier ']' in /usr/share/glpi/src/RuleCriteria.php at line 494`.
It fails because there is a rule called `Multiple users: assign to the first` that has been migrated wrongly. More in detail, that rule has an `Alternate username`  criteria regex that contains a `/` that has not been escaped.
The migration script `install/migrations/update_10.0.0_to_10.0.1/fixaction.php` is migrating it wrongly: from `/(.*),/` to `/(.*)[,|/]/`.
The correctly migrated rule should be something like `/(.*)[,|\/]/`.

### Steps To reproduce

1. Get an OCS database with some data
2. Configure OCS InventoryNG GLPI plugin
3. Run `/path/to/glpi/plugins/ocsinventoryng/scripts/ocsng_fullsync.sh --nolog`
4. See the error

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.5 (/glpi => /usr/share/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux gian-ne 5.19.16-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 16 22:50:04 UTC 2022 x86_64
PHP 7.4.19 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@mariadb.neteyelocal/glpi
	Host info: mariadb.neteyelocal via TCP/IP
	
PHP version (7.4.19) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /neteye/shared/glpi/data/_cache has been validated.
Write access to /neteye/shared/glpi/conf has been validated.
Write access to /neteye/shared/glpi/data/_cron has been validated.
Write access to /neteye/shared/glpi/data has been validated.
Write access to /neteye/shared/glpi/data/_dumps has been validated.
Write access to /neteye/shared/glpi/data/_graphs has been validated.
Write access to /neteye/shared/glpi/data/_lock has been validated.
Write access to /neteye/shared/glpi/data/_pictures has been validated.
Write access to /neteye/shared/glpi/data/_plugins has been validated.
Write access to /neteye/shared/glpi/data/_rss has been validated.
Write access to /neteye/shared/glpi/data/_sessions has been validated.
Write access to /neteye/shared/glpi/data/_tmp has been validated.
Write access to /neteye/shared/glpi/data/_uploads has been validated.
GLPI data directories are located in a secured path.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is not present.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/usr/share/glpi"
GLPI_VAR_DIR: "/neteye/shared/glpi/data"
GLPI_CONFIG_DIR: "/neteye/shared/glpi/conf"
GLPI_MARKETPLACE_DIR: "/usr/share/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/neteye/shared/glpi/data"
GLPI_CACHE_DIR: "/neteye/shared/glpi/data/_cache"
GLPI_CRON_DIR: "/neteye/shared/glpi/data/_cron"
GLPI_DUMP_DIR: "/neteye/shared/glpi/data/_dumps"
GLPI_GRAPH_DIR: "/neteye/shared/glpi/data/_graphs"
GLPI_LOCAL_I18N_DIR: "/neteye/shared/glpi/data/_locales"
GLPI_LOCK_DIR: "/neteye/shared/glpi/data/_lock"
GLPI_LOG_DIR: "/neteye/shared/glpi/data/_log"
GLPI_PICTURE_DIR: "/neteye/shared/glpi/data/_pictures"
GLPI_PLUGIN_DOC_DIR: "/neteye/shared/glpi/data/_plugins"
GLPI_RSS_DIR: "/neteye/shared/glpi/data/_rss"
GLPI_SESSION_DIR: "/neteye/shared/glpi/data/_sessions"
GLPI_TMP_DIR: "/neteye/shared/glpi/data/_tmp"
GLPI_UPLOAD_DIR: "/neteye/shared/glpi/data/_uploads"
GLPI_INVENTORY_DIR: "/neteye/shared/glpi/data/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/usr/share/glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/usr/share/icinga-php/vendor/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/icinga-php/vendor/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/icingaweb2/modules/reporting/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/share/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/usr/share/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	icingaweb2sso        Name: Icingaweb2 SSO                 Version: 0.0.1      State: Enabled                                 
		Install Method: Manual
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.3      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

Indeed, migration was incorrect. #13521 fixes this.
