### ISSUE TITLE
Ticket counter "Processing: N°" in requester group does not appear

### ISSUE THREAD

**Issue by loyolajavi** [glpi-project/glpi#13293]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

The ticket counter "Processing: N°" in requester group does not appear
![image](https://user-images.githubusercontent.com/17304522/201698879-9808f6eb-9f99-40a5-b0a0-adf708e3d3d0.png)

The group in this example has 2 unresolved tickets:
![image](https://user-images.githubusercontent.com/17304522/201704944-d5276f30-12df-4b76-ac69-4ed9c2a02c6b.png)

On the other hand, the number of tickets that the group has as assigned to resolve does appear:
![image](https://user-images.githubusercontent.com/17304522/201705775-deef219c-c22c-4410-885a-d6bf019ed5c6.png)

**Comment by trasher** [comment]
9.5 versions are no longer maintained, upgrade to GLPI 10 and feel free to reopen if problem persists.

Also; there are several security releases; your current version is vulnerable; consider at least upgrading to latest 9.5.11.
