### ISSUE TITLE
Undefined index for Business rules for tickets

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#13300]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

Debug mode enabled: Administration > Rules >  Business rules for tickets > Add button:

**PHP Notice (8): Undefined index: entities_id in /var/www/html/glpi/src/CommonDBTM.php at line 3096**

![obraz](https://user-images.githubusercontent.com/68922721/201923744-c0c8b7ed-477b-4426-b3e6-9187e369c26b.png)

### Anything else?

Firefox 102.3.0esr (32 bity)
Server Version: 8.0.31-0ubuntu0.20.04.1
PHP 7.4.3

**Comment by cconard96** [comment]
Bug is with the Tags plugin and not GLPI itself.
We do not track plugin bugs here.

**Comment by cconard96** [comment]
https://github.com/pluginsGLPI/tag/pull/137
