### ISSUE TITLE
migration plugin database 

### ISSUE THREAD

**Issue by FredVRA** [glpi-project/glpi#13302]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

We use plugin database on GLPI 9.5.11.
On our test database GLPI 10.0.5, i used the command : php bin/console glpi:migration:databases_plugin_to_core to migrate datas in the core, but in the inventory, the instances became databases and databases became instances.

![image](https://user-images.githubusercontent.com/27202969/201941406-5ffc5de0-f613-4758-a3b0-74788f9c5bbc.png)

![image](https://user-images.githubusercontent.com/27202969/201941850-18c1066a-7439-423e-a535-9b9a628d2684.png)

**Comment by cedric-anne** [comment]
Hi. This is an intended behaviour. See https://github.com/glpi-project/glpi/issues/10157#issuecomment-1008773745 for database/instance concepts explaination.
