### ISSUE TITLE
Undefined variable for Debug tab

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#13301]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

Debug mode enabled: Setup > Rules > General > Debug tab:

**PHP Notice (8): Undefined variable: footer_string in /var/www/html/glpi/src/NotificationTemplate.php at line 321
PHP Notice (8): Undefined variable: footer_string in /var/www/html/glpi/src/NotificationTemplate.php at line 330**

![obraz](https://user-images.githubusercontent.com/68922721/201924686-67fea320-0722-4836-9f47-255515f94138.png)

### Anything else?

Firefox 102.3.0esr (32 bity)
Server Version: 8.0.31-0ubuntu0.20.04.1
PHP 7.4.3

**Comment by cconard96** [comment]
It looks impossible for that variable to not be defined when those lines are reached. Was this file modified?
What is shown on line 280 of that file?

**Comment by WebGregGit** [comment]
You are absolutely right. Mea culpa. I tested something and forgot to replace the file :(
