### ISSUE TITLE
Public search not displayed for self-service and technician

### ISSUE THREAD

**Issue by jsdarges** [glpi-project/glpi#13317]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello,

If you create a public search bookmark in tickets it's only accessible for super-admin and admin but self-service and technician can't see it.

I thought it was linked to this issue: https://github.com/glpi-project/glpi/issues/8303 but I tried to save twice and it's not better...

### Steps To reproduce

1. Create a public search bookmark in ticket as super-admin :

![image](https://user-images.githubusercontent.com/113537051/202238242-e2a14572-e464-4fe5-ad8b-2ffadbe63ea6.png)

3. login with a self-serice or technician user
4. check the list of seaches => nothing appears :

![image](https://user-images.githubusercontent.com/113537051/202240541-14fe5872-70e3-47ad-8560-ee706fe78db8.png)

**Comment by cedric-anne** [comment]
Hi,

Please try on GLPI 10.0.5.

**Comment by jsdarges** [comment]
That's ok in 10.0.5
