### ISSUE TITLE
Renaming Location to an existing name updates competename but not the name itself 

### ISSUE THREAD

**Issue by Mirkk** [glpi-project/glpi#13313]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.2

### Bug description

Renaming a Location to an already existing name updates the competename but not the name itself. It also shows that the renaming was successful, but with the old name.

With this, name and completename become inconsistent. This is particularly an issue since the name is shown in dropdowns, but once it is selected, the completename is shown.
Issue also found already in GLPI 9.5.

![image](https://user-images.githubusercontent.com/10242044/202210889-cb1eafd3-6152-4e29-9ce9-0aeb9a202c5f.png)

There is an error in sql_errors.log, but also with debug enabled, no error on the GUI.

Proposed fix: also not updating completename / making completename unique on the DB / additionally showing an error on the GUI.

### Relevant log output

```shell
sql_errors.log

*** MySQL query error:
  SQL: UPDATE `glpi_locations` SET `name` = 'Office' WHERE `id` = '3'
  Error: Duplicate entry '0-0-Office' for key 'unicity'

No other log entries found in php and www_error.log.
```

### Page URL

glpi/front/location.php

### Steps To reproduce

1. rename a location to an already existing name (with same parent or no parent)
2. reload and check completename and name

**Comment by trasher** [comment]
I confirm the issue
