### ISSUE TITLE
Notification to group assigned by business rule not sent

### ISSUE THREAD

**Issue by TylerVD** [glpi-project/glpi#13325]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Derived from [#13274](https://github.com/glpi-project/glpi/issues/13274)

Notification from "New Group in assignees" event are not generated by glpi when the group is assign by a business rule.
Group can be notified
![image](https://user-images.githubusercontent.com/82641169/202494304-259a4af4-6808-4f3c-9088-cbb5a043e0ea.png)
Ticket history
![image](https://user-images.githubusercontent.com/82641169/202494438-45b090eb-4b40-4743-8e0d-c8258eda58ef.png)
The notification queue (and its trashbin) does not contains attribution mail.
![image](https://user-images.githubusercontent.com/82641169/202493929-51cf5c63-c724-4d61-9af1-a3c6074a4b7e.png)

### Steps To reproduce

Create a ticket by mail or reccurentcron or interface that matchs a business rule of auto assign group
<img width="696" alt="image" src="https://user-images.githubusercontent.com/82641169/202495139-21adaf09-5a50-41b6-b000-8d2731bfdf69.png">
Be in the assigned group
Be not warned that you have a new ticket to process.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.5 ( => /home/glpi/glpi10)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux TICKET 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64
PHP 8.1.11 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.29-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@172.16.1.24/glpi
	Host info: 172.16.1.24 via TCP/IP
	
PHP version (8.1.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.29) is supported.
The log file has been created successfully.
Write access to /home/glpi/glpi10/files/_cache has been validated.
Write access to /home/glpi/glpi10/config has been validated.
Write access to /home/glpi/glpi10/files/_cron has been validated.
Write access to /home/glpi/glpi10/files has been validated.
Write access to /home/glpi/glpi10/files/_dumps has been validated.
Write access to /home/glpi/glpi10/files/_graphs has been validated.
Write access to /home/glpi/glpi10/files/_lock has been validated.
Write access to /home/glpi/glpi10/files/_pictures has been validated.
Write access to /home/glpi/glpi10/files/_plugins has been validated.
Write access to /home/glpi/glpi10/files/_rss has been validated.
Write access to /home/glpi/glpi10/files/_sessions has been validated.
Write access to /home/glpi/glpi10/files/_tmp has been validated.
Write access to /home/glpi/glpi10/files/_uploads has been validated.
The following directories should be placed outside "/home/glpi/glpi10":
‣ "/home/glpi/glpi10/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/glpi/glpi10/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/glpi/glpi10"
GLPI_CONFIG_DIR: "/home/glpi/glpi10/config"
GLPI_VAR_DIR: "/home/glpi/glpi10/files"
GLPI_MARKETPLACE_DIR: "/home/glpi/glpi10/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/home/glpi/glpi10/files"
GLPI_CACHE_DIR: "/home/glpi/glpi10/files/_cache"
GLPI_CRON_DIR: "/home/glpi/glpi10/files/_cron"
GLPI_DUMP_DIR: "/home/glpi/glpi10/files/_dumps"
GLPI_GRAPH_DIR: "/home/glpi/glpi10/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/glpi/glpi10/files/_locales"
GLPI_LOCK_DIR: "/home/glpi/glpi10/files/_lock"
GLPI_LOG_DIR: "/home/glpi/glpi10/files/_log"
GLPI_PICTURE_DIR: "/home/glpi/glpi10/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/glpi/glpi10/files/_plugins"
GLPI_RSS_DIR: "/home/glpi/glpi10/files/_rss"
GLPI_SESSION_DIR: "/home/glpi/glpi10/files/_sessions"
GLPI_TMP_DIR: "/home/glpi/glpi10/files/_tmp"
GLPI_UPLOAD_DIR: "/home/glpi/glpi10/files/_uploads"
GLPI_INVENTORY_DIR: "/home/glpi/glpi10/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/home/glpi/glpi10/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/home/glpi/glpi10/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/glpi/glpi10/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/glpi/glpi10/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/home/glpi/glpi10/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/glpi/glpi10/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/glpi/glpi10/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/glpi/glpi10/vendor/iamcal/lib_autolink)
sabre/dav in (/home/glpi/glpi10/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/glpi/glpi10/vendor/sabre/http/lib)
sabre/uri in (/home/glpi/glpi10/vendor/sabre/uri/lib)
sabre/vobject in (/home/glpi/glpi10/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/glpi/glpi10/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/glpi/glpi10/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/glpi/glpi10/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/glpi/glpi10/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/glpi/glpi10/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/glpi/glpi10/vendor/elvanto/litemoji/src)
symfony/console in (/home/glpi/glpi10/vendor/symfony/console)
scssphp/scssphp in (/home/glpi/glpi10/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/glpi/glpi10/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/glpi/glpi10/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/glpi/glpi10/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/glpi/glpi10/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/glpi/glpi10/vendor/ramsey/uuid/src)
psr/log in (/home/glpi/glpi10/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/glpi/glpi10/vendor/psr/simple-cache/src)
psr/cache in (/home/glpi/glpi10/vendor/psr/cache/src)
league/csv in (/home/glpi/glpi10/vendor/league/csv/src)
mexitek/phpcolors in (/home/glpi/glpi10/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/glpi/glpi10/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/glpi/glpi10/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/glpi/glpi10/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/glpi/glpi10/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/glpi/glpi10/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/glpi/glpi10/vendor/symfony/cache)
html2text/html2text in (/home/glpi/glpi10/vendor/html2text/html2text/src)
symfony/css-selector in (/home/glpi/glpi10/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/glpi/glpi10/vendor/symfony/dom-crawler)
twig/twig in (/home/glpi/glpi10/vendor/twig/twig/src)
twig/string-extra in (/home/glpi/glpi10/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home/glpi/glpi10/vendor/symfony/polyfill-php82)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (SUPPORT-IT@ratpdev.com@outlook.office365.com)

</details><details><summary>Plugins list</summary><pre> 
	advanceddashboard    Name: advanceddashboard              Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.10.5     State: Enabled                                 
		Install Method: Manual
	approvalbymail       Name: Approval by mail               Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Behaviours                     Version: 2.7.1      State: Enabled                                 
		Install Method: Manual
	branding             Name: Branding                       Version: 1.3.1      State: Not installed                           
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.2     State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Not installed                           
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Manual
	oauthsso             Name: oauthsso                       Version: 1.7.0      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	splitcat             Name: Split categories               Version: 1.5.2      State: Not installed                           
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.1   State: Enabled                                 
		Install Method: Marketplace
	webapplications      Name: Web applications               Version: 4.0.1      State: Enabled                                 
		Install Method: Manual

</details><details><summary>Locales overrides</summary><pre></pre></details>

**Comment by fralla2** [comment]
This seems to be the same issue as https://github.com/glpi-project/glpi/issues/12085

P.S. You might want to double-check the recursitivity of your rules as on my side, this fixed the problem

**Comment by TylerVD** [comment]
Hi,
The recursivity is ok since the technicians of the group receive the notification when the group is manually assigned after the ticket creation. (thanks to this issue's fix [#13274](https://github.com/glpi-project/glpi/issues/13274)
