### ISSUE TITLE
Probable graphic bug version 10.0.5

### ISSUE THREAD

**Issue by geppauso** [glpi-project/glpi#13352]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hello, I would like to point out that, after updating from 10.0.3 to 10.0.5, the PIN and PUK fields in the area dedicated to SIM cards are no longer visible (graphic bug?).
In reality these data are present because if I make a save by deleting the PUK for example, this is reported in the history by reporting the original data.

Is it just my problem or are you experiencing it too?
Do I try resetting 10.0.3 and reinstalling?
Thank you
Giuseppe

### Your GLPI setup information

<details><summary>Informazioni sul sistema, l'installazione e la configurazione</summary><pre>GLPI 10.0.5 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:it_IT

</details><details><summary>Server</summary><pre> 
Operating system: Linux htprodsrvit01vm.ad.lepida.it 3.10.0-1160.76.1.0.1.el7.x86_64 #1 SMP Wed Aug 10 17:32:14 PDT 2022 x86_64
PHP 8.1.11 apache2handler (Core, PDO, PDO_OCI, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	bz2, calendar, crypto, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, oci8, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets,
	sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 () OpenSSL/1.0.2k-fips mod_fcgid/2.3.9 PHP/8.1.11 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.31
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: userglpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.31) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/marketplace/financialreports/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.9 in (/usr/share/pear)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://ad.lepida.it', Port: '636', BaseDN: 'OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT', Connection filter: '(& (|
		(memberOf:1.2.840.113556.1.4.1941:=CN=Admins_DTC,OU=Admins_Datacenter,OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT)
		(memberOf:1.2.840.113556.1.4.1941:=CN=Super_Admins,OU=Admins_Super,OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT) )
		(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))', RootDN: 'CN=Utente
		GLPI,OU=0_Account di servizio,DC=AD,DC=LEPIDA,DC=IT', Use TLS: none
Server: 'ldaps://ad.lepida.it', Port: '636', BaseDN: 'OU=Lepida,DC=AD,DC=LEPIDA,DC=IT', Connection filter: '(&(&(&
		(primaryGroupID=513) (|(mail=*@lepida.it)(mail=*lepida*@gmail.com))
		(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))))', RootDN: 'CN=Utente
		GLPI,OU=0_Account di servizio,DC=AD,DC=LEPIDA,DC=IT', Use TLS: none
Server: 'ldaps://ad.lepida.it', Port: '636', BaseDN: 'OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT', Connection filter: '(&
		(memberOf:1.2.840.113556.1.4.1941:=CN=Admins_Sistemi,OU=Admins_Sistemi,OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT)
		(memberOf:1.2.840.113556.1.4.1941:=CN=Super_Admins,OU=Admins_Super,OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT) )
		(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))', RootDN: 'CN=Utente
		GLPI,OU=0_Account di servizio,DC=AD,DC=LEPIDA,DC=IT', Use TLS: none
Server: 'ldaps://ad.lepida.it', Port: '636', BaseDN: 'OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT', Connection filter: '(&
		(memberOf:1.2.840.113556.1.4.1941:=CN=Admins_ST,OU=Admins_ServizioTecnico,OU=ADM_Lepida,DC=AD,DC=LEPIDA,DC=IT)
		(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))', RootDN: 'CN=Utente
		GLPI,OU=0_Account di servizio,DC=AD,DC=LEPIDA,DC=IT', Use TLS: none
Server: 'ldaps://ad.lepida.it', Port: '636', BaseDN: 'OU=LiberiProfessionisti,OU=Fornitori,OU=Lepida,DC=AD,DC=LEPIDA,DC=IT',
		Connection filter: '(&(&(& (primaryGroupID=513)
		(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))))', RootDN: 'CN=Utente
		GLPI,OU=0_Account di servizio,DC=AD,DC=LEPIDA,DC=IT', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp.cup2000.it)

</details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	additionalalerts     Name: Altre notifiche                Version: 2.4.0      State: Enabled                                 
		Install Method: Marketplace
	activity             Name: Attività                       Version: 3.1.2      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Avvisi                         Version: 1.10.5     State: Enabled                                 
		Install Method: Marketplace
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Marketplace
	camerainput          Name: Camera Input                   Version: 2.0.0      State: To update                               
		Install Method: Marketplace
	fields               Name: Campi aggiuntivi               Version: 1.18.2     State: Enabled                                 
		Install Method: Marketplace
	positions            Name: Cartografia                    Version: 6.0.2      State: Enabled                                 
		Install Method: Marketplace
	consumables          Name: Consumable request             Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Contatori della stampante      Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	databases            Name: Databases                      Version: 2.3.2      State: Not installed                           
		Install Method: Marketplace
	financialreports     Name: Financial reports              Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.2     State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	gdrive               Name: GDrive                         Version: 1.3.0      State: Not installed                           
		Install Method: Marketplace
	genericobject        Name: Gestione degli oggetti         Version: 2.14.1     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestione ordini                Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Gestione Tag                   Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.5      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: Indirizzamento IP              Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.8.3      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.0      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.2      State: Enabled                                 
		Install Method: Marketplace
	manageentities       Name: Portale Entità           Version: 4.0.3      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Print to pdf                   Version: 1.7.0      State: Not installed                           
		Install Method: Manual
	protocolsmanager     Name: Protokoły                      Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	purchaserequest      Name: Purchase request               Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	releases             Name: Releases                       Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	resources            Name: Risorse umane                  Version: 3.0.4      State: Enabled                                 
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	typology             Name: Tipologie                      Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	treeview             Name: Visualizzazione struttura      Version: 1.10.0     State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by cconard96** [comment]
Already fixed for 10.0.6 by #13246.

**Comment by geppauso** [comment]
Ok, thanks a lot for the info. Is the release date of 10.0.6 already in sight?

**Comment by cconard96** [comment]
I don't have a release date for 10.0.6.

The fix can be applied immediately by:
1. Making the changes shown on the Files Changed tab
2. Downloading the patch and applying it with `patch` utility (Linux)

https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/13246.patch
