### ISSUE TITLE
[GLPI 9.1] Users_ID on glpi_tickets_users is set to 0

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#1336]
Hello Team!

Sometimes, we have a issue on Assigned users. 

The displayed name is the mail address of the user and not the username. 
![2016-11-24_09h10_51](https://cloud.githubusercontent.com/assets/16323410/20591016/b0c797f2-b226-11e6-95d7-a5185484218b.png)

When you check in sql database table "glpi_tickets_users", users_id field is set to 0. So ticket is not really assigned to the user.

![2016-11-24_09h16_52](https://cloud.githubusercontent.com/assets/16323410/20591052/dd9a12fa-b226-11e6-9f50-920bcd3c2834.png)

I need to retrieve the user ID and replace users_id field with the correct value to solve this issue.

No Sql Backtrace on this issue, no log ....and (the best thing), I don't know when this issue happen (so I can't tell how to reproduce)...but I knew I have the same issue in 0.90.x

**Comment by SylvainGuibert** [comment]
Nobody have the same issue ?

**Comment by cedric-anne** [comment]
Hi,

This is not a bug. In the ticket form, you can assign a ticket to an anonymous user, just by filling an email address for the followup.

Regards
