### ISSUE TITLE
GLPI 10.0.5 => locked field don't update when uninstall plugin use

### ISSUE THREAD

**Issue by Tony710** [glpi-project/glpi#13369]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When perform life cycle action with uninstall plugin on Computer item, Changes are performed execpt for locked fields .

### Relevant log output

```shell
No error found
```

### Page URL

https://XXXX/front/computer.php

### Steps To reproduce

1- Select Computer
2- Action / uninstall
3- Perform an uninstall action needed changes on locked fields.
4- After action execution, locked fields values aren't changed.

### Your GLPI setup information

GLPI 10.0.5 ( => C:\GLPI-PROD\glpi)
Installation mode: TARBALL
Current language:fr_FR

<html>
<body>

Plugins list
--
fields               Name: Additional fields              Version: 1.18.2     State: Enabled                                  		Install Method: Manual 	addressing           Name: Adressage IP                   Version: 3.0.1      State: Enabled                                  		Install Method: Manual 	camerainput          Name: Camera Input                   Version: 2.0.0      State: Enabled                                  		Install Method: Manual 	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                  		Install Method: Manual 	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.1      State: Enabled                                  		Install Method: Manual 	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                  		Install Method: Manual 	escalade             Name: Escalades                      Version: 2.8.1      State: Enabled                                  		Install Method: Manual 	formcreator          Name: Form Creator                   Version: 2.13.2     State: Enabled                                  		Install Method: Manual 	glpiinventory        Name: GLPI Inventory                 Version: 1.0.5      State: Enabled                                  		Install Method: Manual 	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                  		Install Method: Manual 	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Enabled                                  		Install Method: Manual

</body>
</html>

**Comment by stonebuzz** [comment]
Hi @Tony710 
Which field are you talking ? 

Can you post here your uninstall model config?

Best regards

**Comment by trasher** [comment]
This seems related to a plugin and not GLPI core.

**Comment by vollkommenIrrelevant** [comment]
[maye part of this?](https://github.com/pluginsGLPI/uninstall/pull/73)

**Comment by Tony710** [comment]
Hi @stonebuzz 
Concerned fileds are : Status, User & Group
![image](https://user-images.githubusercontent.com/78087722/203525338-b521a236-38d0-42c8-ba9e-8c9fd51d914a.png)
![image](https://user-images.githubusercontent.com/78087722/203526003-de800dfd-b426-400e-8f89-b236d874b582.png)
Thanks

**Comment by Tony710** [comment]
Yes, locks are defined globally form https://XXXXXXX/front/lockedfield.php
![image](https://user-images.githubusercontent.com/78087722/203717957-1f124daf-cd5c-4013-af55-8e87dbc3d899.png)

**Comment by stonebuzz** [comment]
Thanks for informations.

So, with global locked field, and same ```uninstall``` model, I do not reproduce.

```Group```, ```User``` and ```Status``` are well update during uninstall process.

The only difference is that I am using the develop branch of the ```unisntall``` plugin, can you try again with this branch?

Best regards

**Comment by cedric-anne** [comment]
Hi,

It is related to uninstall plugin. We do not track plugin issues here, please open an issue on [plugin repository](https://github.com/pluginsGLPI/uninstall) .
