### ISSUE TITLE
Inventory error

### ISSUE THREAD

**Issue by tdelaux** [glpi-project/glpi#13367]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Error on inventory : 

GLPI Agent log : 
[Tue Nov 22 08:40:33 2022][error] [http client] communication error: 500 Internal Server Error, 

Serverside error : 
[Tue Nov 22 08:40:27.462228 2022] [php:error] [pid 20169] [client xx.xx.xx.xx:yy] PHP Fatal error:  Out of range value for column 'manufacturers_id' at row 1 in /app/www/glpi/src/DBmysql.php on line 1969

Manufacturers into GLPI Agent logs for exemple: 
 "bmanufacturer": "Dynabook Inc.",
 "manufacturer": "Samsung Electronics Co Ltd",
 "manufacturer": "Realtek Semiconductor Co., Ltd.",
 "manufacturer": "Cypress Semiconductor Corp.",
 "manufacturer": "Chicony Electronics Co., Ltd",
 "manufacturer": "Intel Corporation",
 "manufacturer": "Microsoft",
 "manufacturer": "(Standard system devices)",

### To reproduce

import long manufacturer name

### Expected behavior

I need to import computers datas into GLPI with GLPI agent

### Operating system

Windows

### GLPI Agent version

Nightly build (git version in additional context below)

### GLPI version

Other (See additional context below)

### Additional context

GLPI agent : GLPI-Agent v1.5-gitedc3b504 nightly build
GLPI : 10.0.5

**Comment by stonebuzz** [comment]
Hi @tdelaux 
can you try with GLPI nighlty build ?

https://nightly.glpi-project.org/glpi/

Best regards

**Comment by tdelaux** [comment]
Hi @stonebuzz ,
always the same error with GLPI 1.0.6-dev ;-(

Best regards

**Comment by stonebuzz** [comment]
Can you post complet error stacktrace ?

**Comment by trasher** [comment]
No feedback, I close. Feel free to reopen with requested information.
