### ISSUE TITLE
[10.0.3]$CFG_GLPI['notification_to_myself'] does not apply for anonymous user when code comment says otherwise

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#13373]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi,

Line 166 in src/notificationevent.php, the following line is present for anonymous users to use the global configuration setting of notification for followup items which they are author.
However, anonymous users still receive notifications of the follow up that they have sent.

```
   // Special case for anonymous helpdesk, we have an email
                     // instead of an ID
                     // -> load the global conf and use the email as the emitter
                            $notify_me = $CFG_GLPI['notification_to_myself'];
                            $emitter = $mailcollector_user;
                        }
```

### Your GLPI setup information

Debian  4.19.260-1 (2022-09-29) x86_64 
php 7.4.33

**Comment by trasher** [comment]
Please try with latest official release and nightlybuild, feel free to reopen if issue still occurs.

**Comment by joomlafun** [comment]
Hi, 
@trasher 
Thank you for your help. Can you let me know if it is only one file which got modified ? 

Why : We all love glpi and thanks a lot for your hard work and contributions but
I must say that lots of new bugs appear after an update because of new features being added which is normal.

However the system being almost close to perfect for the quantity of features which it offers, then from my point of view the priority could be bug correction and not developping new features so that we can experience more stable releases.

That's why in this case I would only modify the necessary files, instead of updating the whole installation.

**Comment by trasher** [comment]
> I would only modify the necessary files, instead of updating the whole installation.

That's a bad idea. A patch may require some other changes in order to work as expected, and even worse can cause unexpected issues. 
And finally, issues are opened here we cannot reproduce...

We only provide support for official releases.
