### ISSUE TITLE
Publishing internal IP

### ISSUE THREAD

**Issue by k0xak** [glpi-project/glpi#13372]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Application is publishing internal IPs as response on many places.

Request:
```
POST /ajax/central.php HTTP/1.1
Host: url.com

```
Response:
```
"smtp_host":"10.0.0.2","smtp_port":"25","smtp_username":"","proxy_name":"10.0.0
.20","proxy_port":"3128","proxy_user":""
```

Request:
```
POST /ajax/"leupload.php HTTP/1.1
Host: url.com

```

Response:
```
{"_uploader_"lename":
[{"name":"5e8b52e2d619dc.986521971dc2aee5881747c7146461ddc420a28409ff530359971b2
378c92baed9d0206e.xls","size":33280,"type":"application\/vnd.ms-
excel","url":"http:\/\/10.0..10\/ajax\/"les\/
5e8b52e2d619dc.986521971dc2aee5881747c7146461ddc420a28409ff530359971b2378c92baed
9d0206e.xls","deleteUrl":"http:\/\/10.0.0.10\/ajax\/"leupload.php?
_uploader_"lenam=5e8b52e2d619dc.986521971dc2aee5881747c7146461ddc420a28409ff5303
59971b2378c92baed9d0206e.xls","deleteType":"DELETE","pre"x":"5e8b52e2d619dc.9865
2197","display":"1dc2aee5881747c7146461ddc420a28409ff530359971b2378c92baed9d0206
e.xls 32.5 KiB",""lesize":"32.5 KiB","id":"doc_uploader_"lename1376750681"}]}
```

Its not recommended to exposure sensitive information to both authenticated and not authenticated users.

Exposure of Sensitive Information to an Unauthrorized Actor

Discovered by PS.

**Comment by cedric-anne** [comment]
@k0xak 

Why are you posting security issues publicly ?!
I deleted your issues, even if now many people already received notifications with their contents. Please read https://github.com/glpi-project/glpi/security/policy.
