### ISSUE TITLE
SQL error : Column count doesn't match value count at row 1

### ISSUE THREAD

**Issue by vrocheUP** [glpi-project/glpi#1337]
Hi team,

Another bug found several days ago. When a computer updates via fusion-inventory agent, it's often impossible to get the **glpi_computers_softwareversions** table update because of an SQL error : "Column count doesn't match value count at row 1".

In fact, the field **date_install** is missing in the datas, but the field is required by the INSERT statement : 
   - INSERT INTO `glpi_computers_softwareversions` (`computers_id`,`softwareversions_id`,`is_dynamic`,`entities_id`,`date_install`)

   - VALUES (\'95\',\'81279\',\'1\',\'20\')

See log file attached.

It seems that if I delete the computer from GLPI, everything is correct the next time the same computer contacts the GLPI server, but I can't be totally sure of that.

Have a nice day
[sql-errors.txt](https://github.com/glpi-project/glpi/files/610805/sql-errors.txt)

**Comment by trasher** [comment]
This error seems related to fusioninventory, not to GLPI. Please fill a ticket on the plugin tracker.
