### ISSUE TITLE
Agent installed but can not created computer inventory

### ISSUE THREAD

**Issue by hvubio** [glpi-project/glpi#13397]
### Describe the bug

I installed glpi-agent v1.4 in my computer but glpi can not create my computer in computer inventory. When glpi-agent send data in log file i saw error:  
`[Wed Nov 23 11:51:54 2022][error] [http client] communication error: 500 Internal Server Error`
So i will check in apache error log and saw error:
`[Wed Nov 23 11:51:54.463433 2022] [php:warn] [pid 10380] [client xxx.xxx.xxx.xxx:62145] PHP Warning:  Undefined array key "nok_1mWPVTlvyC$$$$2" in /srv/www/htdocs/glpi/src/Inventory/Asset/Software.php on line 725
[Wed Nov 23 11:51:54.463696 2022] [php:error] [pid 10380] [client xxx.xxx.xxx.xxx:62145] PHP Fatal error:  Column 'softwares_id' cannot be null in /srv/www/htdocs/glpi/src/DBmysql.php on line 1969`

### To reproduce

Uninstall and install again but can not fix.
Import json file but same error 
Edit json file with delete some softwares but not all --> can import json

### Expected behavior

Maybe my computer have alot softwares so it can not write to mariadb database.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin

1.0.4

### Additional context

i had writer problem in forum with link [https://forum.glpi-project.org/viewtopic.php?id=285510](url)

GLPI version 10.0.5

**Comment by trasher** [comment]
@hvubio the final fix is #13390; could you please confirm that also works for you?

**Comment by hvubio** [comment]
@trasher I following link #13387 but in this have #13390 so i use it and  this is work for me. It can fix my issue.

Thank you.
