### ISSUE TITLE
"n" in description field of ticket 

### ISSUE THREAD

**Issue by taupin-a** [glpi-project/glpi#13407]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11 

### Bug description

Dear,

When you save a ticket, a character "n" appears on each lines of the field "description"

![image](https://user-images.githubusercontent.com/22525228/203833263-4126f748-625b-4f0d-aee0-3d85780c9862.png)

This bug  has just appeared when we upgrade to the version 9.5.11

Doest it exist a hotfix to solve this problem ?

Best regards

### Steps To reproduce

1 edit a ticket
2 save the ticket

**Comment by trasher** [comment]
This has already been reported and fixed

**Comment by cedric-anne** [comment]
See https://github.com/glpi-project/glpi/commits/9.5/bugfixes

**Comment by taupin-a** [comment]
Thanks for the response but witch issue resolve this bug ?
