### ISSUE TITLE
Tickets/followups created by mail recievers, CSS don't work 

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#13414]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When tickets/followups are created through the mail receiver, the mail notifications that are sent do not process the template's CSS.

![image](https://user-images.githubusercontent.com/6449156/204001570-63c8378b-a965-4f29-86ac-79c6f7aebe29.png)

This CSS are ignored.

Its seems to be related to: https://github.com/glpi-project/glpi/pull/12192 or https://github.com/glpi-project/glpi/issues/12457

Notification sent after follow up received by email:
![IMG_6131](https://user-images.githubusercontent.com/6449156/204003438-89f22d1b-2b44-4b57-91c1-aa4152bb6c2e.PNG)

Notification sent after followup created in Glpi WEB (without mail receiver involved):
![IMG_6132](https://user-images.githubusercontent.com/6449156/204003469-e670bb88-d991-4976-8f67-e525fd2dba96.PNG)

### Steps To reproduce

1.Setup Receiver to Create Tickets from EMail.
2.Send and EMail that contains for open a new ticket. 
3.the notification sent by email ignores the CSS defined in the template.

### Your GLPI setup information

GLPI 10.0.3 ( => /var/www/servicedesk.municipiopcr.local/html/glpi)
Installation mode: TARBALL
Current language:pt_PT

Operating system: Linux srvsd02-pcr 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64
PHP 8.1.9 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at servicedesk.municipiopcr.local Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56
Server Software: Debian 10
	Server Version: 10.3.34-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.9) is supported.PHP version (8.1.9) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.Database engine version (10.3.34) is supported.
The log file has been created successfully.The log file has been created successfully.

**Comment by trasher** [comment]
Please try with latest release.

**Comment by rjmontenegro** [comment]
Hello @trasher.
I'm going to close the ticket because this situation doesn't always happen, only when there is some element or text that is quite large. In practice the CSS is read correctly.
Thanks
