### ISSUE TITLE
Error when add a followup where the ticket is assigned to a supplier

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#13418]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When I add a followup where the ticket is assigned to a supplier, I have a error.

The supplier:
![image](https://user-images.githubusercontent.com/6449156/204042145-747f4c84-ec99-42dd-b1b4-e716b4bdd60f.png)

The ticket:
![image](https://user-images.githubusercontent.com/6449156/204064935-c9dff9e0-86a5-402e-b523-7cb5cb7f580c.png)

and, after add the followup, open this blank page:
![image](https://user-images.githubusercontent.com/6449156/204065017-4d449756-569b-4878-95e7-c2723569f84e.png)

if i refresh the page i get these errors:
![image](https://user-images.githubusercontent.com/6449156/204065075-33ac37c0-8e02-4fa9-81b9-0f2efe1b69ae.png)

### Relevant log output

```shell
php-error.log:
[2022-11-25 17:31:57] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: NotificationTargetCommonITILObject::getActorData(): Argument #1 ($actor) must be of type CommonDBTM, array given, called in /var/www/servicedesk.municipiopcr.local/html/glpi/src/NotificationTargetCommonITILObject.php on line 1192 in /var/www/servicedesk.municipiopcr.local/html/glpi/src/NotificationTargetCommonITILObject.php at line 1623
  Backtrace :
  src/NotificationTargetCommonITILObject.php:1192    NotificationTargetCommonITILObject->getActorData()
  src/NotificationTargetTicket.php:161               NotificationTargetCommonITILObject->getDataForObject()
  src/NotificationTargetCommonITILObject.php:1024    NotificationTargetTicket->getDataForObject()
  src/NotificationTarget.php:1338                    NotificationTargetCommonITILObject->addDataForTemplate()
  src/NotificationTemplate.php:278                   NotificationTarget->getForTemplate()
  src/NotificationEventAbstract.php:127              NotificationTemplate->getTemplateByLanguage()
  src/NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src/ITILFollowup.php:363                           NotificationEvent::raiseEvent()
  src/CommonDBTM.php:1322                            ITILFollowup->post_addItem()
  front/itilfollowup.form.php:55                     CommonDBTM->add()
```

### Page URL

itilfolowup.form.php

### Steps To reproduce

1, Create a tickek and assign it to supplier
or
2. Add a followup on ticket that is assigned to a supplier 

### Your GLPI setup information

GLPI 10.0.3 ( => /var/www/servicedesk.municipiopcr.local/html/glpi)
Installation mode: TARBALL
Current language:pt_PT

Operating system: Linux srvsd02-pcr 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64
PHP 8.1.9 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M"
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at servicedesk.municipiopcr.local Port 443
)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.56
Server Software: Debian 10
Server Version: 10.3.34-MariaDB-0+deb10u1
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
Parameters: glpi@localhost/glpi
Host info: Localhost via UNIX socket

PHP version (8.1.9) is supported.PHP version (8.1.9) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.Database engine version (10.3.34) is supported.
The log file has been created successfully.The log file has been created successfully.

**Comment by cconard96** [comment]
Please update to the latest bug fix version of 10.0.5 when possible. This bug has already been fixed by #12729.

**Comment by rjmontenegro** [comment]
Hello @cconard96 .
I searched and didn't find it but yes, #12729 fixes it. I didn't update to the last one because fusioninventory only supports 10.0.3.
In this research I found that the GLPI inventory already exists, which does not require plugins and which is good news.
Thanks

**Comment by cedric-anne** [comment]
@rjmontenegro 

You should try to switch to [`glpiinventory` plugin](https://github.com/glpi-project/glpi-inventory-plugin). `glpiinventory` plugin is a fork from `fusioninventory` plugin that has been made by the GLPI core team to keep support of inventory advanced features in combination of usage of basic inventory features that are now directly embeded in GLPI itself.
Migration to it is pretty easy, as you just have to disable `fusioninventory` plugin and install `glpiinventory` plugin that will migrate all your data.
As for any migration, it is preferable to do a backup first. If something goes wrong, just create an issue and so we can fix it.

**Comment by rjmontenegro** [comment]
Yes, I didn't know but when I read it, I was happy because it is excellent news.  I know it's compatible with the fusioninventory agents but I prefer to uninstall the fusioninventory agents and install the glpi ones.  It will take a lot more work but I prefer it.  I just don't know how I can completely uninstall the fusioninventory plugin from the server and database.  Is there documentation for this?  Thanks

Ricardo Montenegro
________________________________

**Comment by cedric-anne** [comment]
> I just don't know how I can completely uninstall the fusioninventory plugin from the server and database. 

1. Disable the `fusioninventory` plugin.
2. Install the `glpiinventory` plugin, it will migrate `fusioninventory` data and remove unnecessary data.
3. Remove the `fusioninventory` directory from your server.
