### ISSUE TITLE
Unable to save search (when too many filters ?)

### ISSUE THREAD

**Issue by jsdarges** [glpi-project/glpi#13425]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When you add multiple search criteria in tickets list it's impossible to save the search as favorite with all profiles

### Steps To reproduce

1. Go to tickets list
2. add multiple search criterias
![image](https://user-images.githubusercontent.com/113537051/204254994-ae038482-6ae1-4a25-b319-fdee35ed240c.png)
3. Try to save
![image](https://user-images.githubusercontent.com/113537051/204255117-a1431f02-eb8f-447a-bd96-bc4993e5d8e9.png)
![image](https://user-images.githubusercontent.com/113537051/204255219-4382c718-9fa0-4dc3-ab9d-46dd16ae4583.png)

**Comment by trasher** [comment]
Please check if #13572 solves the issue
