### ISSUE TITLE
Creating a followup does not always send email to the recepient

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#13427]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Recepient does not receive an email on followups everytime or without solved status

Notification - Add Followup - Recepients: Administrator, Requester, Technician in charge of the ticket, Watcher

### Relevant log output

```shell
==> php-errors.log <==
[2022-11-28 17:09:04] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input is not a valid email address. Use the basic format local-part@hostname in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Address.php at line 74
  Backtrace :
  vendor/laminas/laminas-mail/src/Address.php:50     Laminas\Mail\Address->__construct()
  ...inas-mail/src/Header/AbstractAddressList.php:92 Laminas\Mail\Address::fromString()
  :                                                  Laminas\Mail\Header\AbstractAddressList::Laminas\Mail\Header\{closure}()
  ...inas-mail/src/Header/AbstractAddressList.php:71 array_map()
  vendor/laminas/laminas-mail/src/Headers.php:556    Laminas\Mail\Header\AbstractAddressList::fromString()
  vendor/laminas/laminas-mail/src/Headers.php:282    Laminas\Mail\Headers->loadHeader()
  vendor/laminas/laminas-mail/src/Headers.php:102    Laminas\Mail\Headers->addHeaderLine()
  vendor/laminas/laminas-mime/src/Decode.php:162     Laminas\Mail\Headers::fromString()
  ...r/laminas/laminas-mail/src/Storage/Part.php:106 Laminas\Mime\Decode::splitMessage()
  ...laminas/laminas-mail/src/Storage/Message.php:47 Laminas\Mail\Storage\Part->__construct()
  ...r/laminas/laminas-mail/src/Storage/Imap.php:121 Laminas\Mail\Storage\Message->__construct()
  ...aminas-mail/src/Storage/AbstractStorage.php:270 Laminas\Mail\Storage\Imap->getMessage()
  src/MailCollector.php:731                          Laminas\Mail\Storage\AbstractStorage->current()
  src/MailCollector.php:1852                         MailCollector->collect()
  src/CronTask.php:1018                              MailCollector::cronMailgate()
  front/cron.php:84                                  CronTask::launch()
```

### Steps To reproduce

1. Add followup with pending status (no email sent to recepient)
2. Add a second followup with pending status (thsi time the email is sent to recepient)
3. Using SOLUTION on the ticket (the email always is sent to the recepient)

### Your GLPI setup information

Server

PHP version (7.4.33) is supported.PHP version (7.4.33) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.26) is supported.Database engine version (5.7.26) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated. Write access to /etc/glpi/ has been validated. Write access to /var/lib/glpi/_cron has been validated. Write access to /var/lib/glpi has been validated. Write access to /var/lib/glpi/_dumps has been validated. Write access to /var/lib/glpi/_graphs has been validated. Write access to /var/lib/glpi/_lock has been validated. Write access to /var/lib/glpi/_pictures has been validated. Write access to /var/lib/glpi/_plugins has been validated. Write access to /var/lib/glpi/_rss has been validated. Write access to /var/lib/glpi/_sessions has been validated. Write access to /var/lib/glpi/_tmp has been validated. Write access to /var/lib/glpi/_uploads has been validated.Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
SELinux configuration is OK.SELinux configuration is OK.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by dxdemetriou** [comment]
Even with solved status happens, the same error

==> php-errors.log <==
[2022-11-28 17:24:04] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input is not a valid email address. Use the basic format local-part@hostname in /var/www/html/glpi/vendor/laminas/laminas-mail/src/Address.php at line 74
  Backtrace :
  vendor/laminas/laminas-mail/src/Address.php:50     Laminas\Mail\Address->__construct()
  ...inas-mail/src/Header/AbstractAddressList.php:92 Laminas\Mail\Address::fromString()
  :                                                  Laminas\Mail\Header\AbstractAddressList::Laminas\Mail\Header\{closure}()
  ...inas-mail/src/Header/AbstractAddressList.php:71 array_map()
  vendor/laminas/laminas-mail/src/Headers.php:556    Laminas\Mail\Header\AbstractAddressList::fromString()
  vendor/laminas/laminas-mail/src/Headers.php:282    Laminas\Mail\Headers->loadHeader()
  vendor/laminas/laminas-mail/src/Headers.php:102    Laminas\Mail\Headers->addHeaderLine()
  vendor/laminas/laminas-mime/src/Decode.php:162     Laminas\Mail\Headers::fromString()
  ...r/laminas/laminas-mail/src/Storage/Part.php:106 Laminas\Mime\Decode::splitMessage()
  ...laminas/laminas-mail/src/Storage/Message.php:47 Laminas\Mail\Storage\Part->__construct()
  ...r/laminas/laminas-mail/src/Storage/Imap.php:121 Laminas\Mail\Storage\Message->__construct()
  ...aminas-mail/src/Storage/AbstractStorage.php:270 Laminas\Mail\Storage\Imap->getMessage()
  src/MailCollector.php:731                          Laminas\Mail\Storage\AbstractStorage->current()
  src/MailCollector.php:1852                         MailCollector->collect()
  src/CronTask.php:1018                              MailCollector::cronMailgate()
  front/cron.php:84                                  CronTask::launch()

**Comment by cedric-anne** [comment]
The mentionned error is not related to notifications, but is related to mail collector crontask. Maybe it is related to https://github.com/php/php-src/issues/7980 (fixed in PHP 8.x).

For admin notifications, you should check you notifications settings, to ensure that email address is valid.

**Comment by dxdemetriou** [comment]
> The mentionned error is not related to notifications, but is related to mail collector crontask. Maybe it is related to [php/php-src#7980](https://github.com/php/php-src/issues/7980) (fixed in PHP 8.x).
> 
> For admin notifications, you should check you notifications settings, to ensure that email address is valid.

The email it's the same as it was on GLPI 9.5. I'll try with PHP 8, but with this change, almost everyone using RHEL based Linux will be affected.

This with Recipients which are not taking with email the 1st followup but takes the 2nd one, every user is affected and also the same emails used before. I didn't watched it before, but I suppose that if not happened with the small changes on GLPI 10.0.5, it started from GLPI 10.0.4.

In both cases I'm trying to check the error logs, but there is not seem to be any information why the emails are seems to not be valid.

**Comment by cedric-anne** [comment]
> The email it's the same as it was on GLPI 9.5. 

Maybe we made some modifications on this part in GLPI 10.0. Could you please test #13438 to see if there is any log entry added when notifications are supposed to be generated ?

**Comment by cedric-anne** [comment]
> I'll try with PHP 8, but with this change, almost everyone using RHEL based Linux will be affected.

Indeed. Keep in mind that PHP 7.4 is not anymore maintained since yesterday, so upgrading to PHP 8.x is anyway recommended for security reasons.

**Comment by dxdemetriou** [comment]
> > The email it's the same as it was on GLPI 9.5.
> 
> Maybe we made some modifications on this part in GLPI 10.0. Could you please test #13438 to see if there is any log entry added when notifications are supposed to be generated ?

I tried the changes but I don't get any extra log except of the same in php-errors.log
I checked also into the other log files and into the notofication queue, but nothing for administrator's email is there.

**Comment by dxdemetriou** [comment]
The strage thing, the problem appeared on 2022-11-23 13:34:03 (based on php-errors.log)

The last time I made OS updates was on 4/11 and the plugins updated:
 - screenshot, formcreator (28/11)
 - glpiinventory (16/11)
 - escalade, fields (4/11)
and the rest between June-October

The latest update of GLPI were when released the 10.0.5. The dates does not match for knowing what to check, that's confused me..

**Comment by cedric-anne** [comment]
As I said before:

> The mentionned error is not related to notifications, but is related to mail collector crontask. Maybe it is related to [php/php-src#7980](https://github.com/php/php-src/issues/7980) (fixed in PHP 8.x).

**Comment by dxdemetriou** [comment]
> As I said before:
> 
> > The mentionned error is not related to notifications, but is related to mail collector crontask. Maybe it is related to [php/php-src#7980](https://github.com/php/php-src/issues/7980) (fixed in PHP 8.x).

Sure, but still we have the question "why happens on the 1st time but not on the 2nd time?", as asked here:
https://github.com/glpi-project/glpi/issues/13434
What is the difference between the 1st and the 2nd followup?
I'm planning to update PHP and I'll report during the week, I hope to be solved with this.

**Comment by cedric-anne** [comment]
Did you tested #13280 ?

**Comment by dxdemetriou** [comment]
> Did you tested #13280 ?

Yes, the "1st followup not sent" issue has been fixed with this, thanks. I'll checking pull requests also next times..

For the Administrator's email I'll report after the upgrade. I have applied both fixes https://github.com/glpi-project/glpi/pull/13438 & https://github.com/glpi-project/glpi/pull/13280 , I hope with latest PHP to be solved this too.

**Comment by ArriMa** [comment]
Hi, I've this issue too.

From my test with GLPI 10.0.5 and PHP 8.1.11, sometime followup notification not generate a mail (I see nothing in the notification queue).

- If I add a followup and I enable the pending toggle (on the right of Add button) before click Add button, the notification is not generated.
- Solution is always sent.

I do not tried with the last fixes.

**Comment by dxdemetriou** [comment]
> Hi, I've this issue too.
> 
> From my test with GLPI 10.0.5 and PHP 8.1.11, sometime followup notification not generate a mail (I see nothing in the notification queue).
> 
> * If I add a followup and I enable the pending toggle (on the right of Add button) before click Add button, the notification is not generated.
> * Solution is always sent.
> 
> There are other circumstance that not generate a notification after add a followup
> 
> I do not tried with the last fixes.

If I'm correct, the newer PHP with the first fix is required if you use the Administrator's email in followups (haven't tried yet).

About the followups, every first followup in any status (not only pendings) is not sent, and with the second fix has been solved in my case. Solutions works always even without the fix.
