### ISSUE TITLE
Number of tickets as requester (For Groups) does not appear

### ISSUE THREAD

**Issue by loyolajavi** [glpi-project/glpi#13429]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When add a group as requester the "Number of tickets as requester" does not appear.
Example, in this image the requester group "Amba>Grupo1" does not have the number of unresolved tickets. However, group "Amba>Grupo1" has 6 unresolved tickets. In this example, the number 6 should appear
![image](https://user-images.githubusercontent.com/17304522/204316462-2cfbea81-37fc-4708-9364-a38b440f5f2f.png)

### Page URL

../front/ticket.form.php

### Steps To reproduce

1. Go to create ticket / update ticket
2. Add a group as requester

**Comment by cedric-anne** [comment]
Hi,

Counters only appears for:
 - requester user,
 - assigned user,
 - assigned group,
 - assigned supplier.

I do not know if it is a bug or a missing feature.

@orthagh Should we add counters for all actors ?

**Comment by orthagh** [comment]
It should be easy to do so, so i think yes

**Comment by loyolajavi** [comment]
Thanks to everyone!
