### ISSUE TITLE
Reduce columns width

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#13423]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes] Reduce columns width

### Bug description

Hello, for information, i had this entry to reduce columns width on display

```
.search_page .search-container .search-card .search-results thead:first-child th {
   min-width: auto!important;
}
```

**Comment by cedric-anne** [comment]
Hi 

Feel free to propose a PR.

**Comment by orthagh** [comment]
not sure, i need to test the rendering

**Comment by orthagh** [comment]
i found the proposed patch to be worse on small screens than the current state
And on normal/larger screen, i didn't notice any changes
