### ISSUE TITLE
de_DE.po Translation 9.1 vs 9.2

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1342]
Hi,

tried to use translation mailing list but i'm to stupid ;)

Any known bugs on 9.2 translation source ?
In german translation branch we have to translate many words again like "hours" this is already translated on 9.1. He have 200 (edit: 240) new untranslated words on 9.2 branch.

i see this problem a few weeks ago, but it is my first mailing list.

best regards

**Comment by orthagh** [comment]
Hello @Armin83 

Yes, it's my fault (and transifex service).
When i created the new slug for future 9.2 (some week ago), i tried to import current translations files.
For some language, (and precisely for de_DE), it fails on some strings.
Recently, Transifex import process add a check for empty singular/plural and don't have any clone function.
So on that previous import, we lost some strings.

Here is a way to fix that:
- find all singular strings no translated in current po file (like https://github.com/glpi-project/glpi/blob/master/locales/de_DE.po#L3025) by searching on 'msgstr[0] ""'
- translate them manually on your computer
- send me this file (delaunay[dot].alexandre[at]gmail[dot]com)
- i'll import it.

**Comment by orthagh** [comment]
Or complete the translations in 9.1 slug, and i'll export / import in 9.2

**Comment by Armin83** [comment]
Okay - can we translator get info if you take translation file to new version ? 
I see this problem that this translation is complete missing in 9.2 but it is in 9.1 (other / msgstr[1]) tranlated. 

#: inc/objectlock.class.php:64
msgid "Object Lock"
msgid_plural "Object Locks"
msgstr[0] ""
msgstr[1] ""

I will translate it in 9.1 slug. I see only 13.

**Comment by Armin83** [comment]
I downloaded the "good version" from 9.1 translated two msgstr[0] "" and uploaded too 9.2.
I searched on transifex for the bad in 9.1 but i only found one ??
