### ISSUE TITLE
Cannot upload large files

### ISSUE THREAD

**Issue by PCz-Rover-Team** [glpi-project/glpi#13431]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.5

### Bug description

Hi,
Today I encounter on a really annoying problem.
I cannot change a default amount of max file size, finally I always received an information: "File is too big"
![Screenshot_46](https://user-images.githubusercontent.com/93161666/204361406-e6ac5275-afe7-438a-81ef-cec535fd0176.png)

Backend :
Changing the ''php.ini'' file to the following:

upload_max_filesize = 100M ;
post_max_size = 100M ;

Next I restart following services: 

systemctl restart php-fpm.service
systemctl restart httpd.service (httpd is our apache server)

Then we clean up cache memory to remove unused datas.

And eventually we still are not able to send file which is larger than 2MB.

Thank you in advance for you help.

**Comment by cconard96** [comment]
It needs to be changed in Setup > General > Management tab.
During the initial install, the "Document files maximum size (Mio)" is set to whatever the PHP setting it set for. If you change the PHP option, the setting doesn't change in GLPI automatically. This lets you restrict GLPI uploads more than the PHP setting; useful if you have other PHP apps that need larger uploads than GLPI.

https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/general/management.html
