### ISSUE TITLE
Browser Safari dropdown malfunction

### ISSUE THREAD

**Issue by mauriciolamego** [glpi-project/glpi#13433]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

In safari browser dropdown not work fine when selected. This is occurred in any places.
in the first click:

<img width="594" alt="Captura de Tela 2022-11-28 às 20 46 15" src="https://user-images.githubusercontent.com/40633272/204404554-8ec60ada-926e-4389-b462-170efe4ad7f6.png">

in the second click en same place:

<img width="676" alt="Captura de Tela 2022-11-28 às 20 46 28" src="https://user-images.githubusercontent.com/40633272/204404594-68ac5f93-bfd0-4234-af2d-15d12b83480e.png">

### Relevant log output

```shell
The problem not not have log output.
```

### Page URL

anyone.

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.5 (/Suporte => /home/u412791853/domains/solemtic.com.br/public_html/Suporte)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux br-asc-web720.main-hosting.eu 4.18.0-348.lve.el7h.x86_64 #1 SMP Sun Nov 21 14:20:28 UTC 2021 x86_64
PHP 8.0.23 litespeed (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, libxml, litespeed, mbstring,
	monarxprotect, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, soap, sockets,
	sodium, sqlite3, standard, tidy, timezonedb, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="512M" safe_mode="" session.save_handler="files"
	upload_max_filesize="512M" 
Software: LiteSpeed
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15
Server Software: MariaDB Server
	Server Version: 10.5.13-MariaDB-cll-lve
	Server SQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: u412791853_glpi@localhost/u412791853_glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.0.23) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.13) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_cache has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/config has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_cron has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_dumps has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_graphs has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_lock has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_pictures has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_plugins has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_rss has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_sessions has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_tmp has been validated.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_uploads has been validated.
The following directories should be placed outside "/home/u412791853/domains/solemtic.com.br/public_html/Suporte":
‣ "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files" ("GLPI_VAR_DIR")
‣ "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/u412791853/domains/solemtic.com.br/public_html/Suporte/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte"
GLPI_CONFIG_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/config"
GLPI_VAR_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files"
GLPI_MARKETPLACE_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files"
GLPI_CACHE_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_cache"
GLPI_CRON_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_cron"
GLPI_DUMP_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_dumps"
GLPI_GRAPH_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_locales"
GLPI_LOCK_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_lock"
GLPI_LOG_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_log"
GLPI_PICTURE_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_plugins"
GLPI_RSS_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_rss"
GLPI_SESSION_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_sessions"
GLPI_TMP_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_tmp"
GLPI_UPLOAD_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_uploads"
GLPI_INVENTORY_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/home/u412791853/domains/solemtic.com.br/public_html/Suporte/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/iamcal/lib_autolink)
sabre/dav in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/sabre/http/lib)
sabre/uri in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/sabre/uri/lib)
sabre/vobject in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/elvanto/litemoji/src)
symfony/console in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/symfony/console)
scssphp/scssphp in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/ramsey/uuid/src)
psr/log in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/psr/simple-cache/src)
psr/cache in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/psr/cache/src)
league/csv in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/league/csv/src)
mexitek/phpcolors in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/symfony/cache)
html2text/html2text in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/html2text/html2text/src)
symfony/css-selector in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/symfony/dom-crawler)
twig/twig in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/twig/twig/src)
twig/string-extra in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/home/u412791853/domains/solemtic.com.br/public_html/Suporte/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (chamados@solemtic.com.br@smtp.hostinger.com)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.2     State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	consumables          Name: Pedidos de consumíveis         Version: 2.0.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

No.

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on my browser, and I do not know if someone inside active GLPI developers team has access to a Safari browser to confirm/fix the issue.

**Comment by cconard96** [comment]
Are there any errors in the browser console between the time the page loads and the dropdown is functional?
For Safari, I think you need to enable the Develop menu and then you can show the console with Option + ⌘ + C.
https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac

**Comment by cconard96** [comment]
I was able to set up Cypress with experimental WebKit support and was able to recreate the issue.
It seems related to https://github.com/select2/select2/issues/4678.

**Comment by cedric-anne** [comment]
@mauriciolamego 

Could you please test #14579 ? You have to use the debug mode and clear browser cache to be able to validate the patch.
