### ISSUE TITLE
Network Outlets removed from GLPI 

### ISSUE THREAD

**Issue by ajasa19** [glpi-project/glpi#13447]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Was going to upgrade from a previous version and saw network outlets have been removed completely from the dropdown page and locations side tabs GLPI 10.0.5.
Is this a bug or are network outlets no longer supported by GLPI? 
Network outlets are quite a big reason my team uses GLPI is there a new item to replace them?

**Comment by cconard96** [comment]
They are now managed as "Sockets" in a new cable management feature.
The full list can be found by going to Assets > Cables and then clicking the button along the top of the page with the network port icon. Sockets linked to assets show up in the Sockets tab for those assets and if they are linked to a location, there is a tab for them there as well. You can add a socket from both an asset and location as well.

If you need more help with this, consider opening a post on the forum as we only track bug reports on GitHub.
https://forum.glpi-project.org/
