### ISSUE TITLE
"unauthorized action" when the page is still loading

### ISSUE THREAD

**Issue by msizec** [glpi-project/glpi#13451]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Pretty simple : unauthorized action error is displayed when trying to add a rule to filter tickets or assets, while the page is still loading.
it is easier to reproduce the bug when you set a higher number of tickets per page.

**Comment by msizec** [comment]
This is a real bug, easily reproductible.
I didn't filled logs, url, steps, etc because i didn't think it was useful

**Comment by cconard96** [comment]
It looks like you are able to click the search filter buttons before the `common.js` script is loaded so the AJAX request doesn't send the CSRF token to the server with the request.
