### ISSUE TITLE
Contracts expiration query for notice begins les then 7 and 30 is the same query

### ISSUE THREAD

**Issue by Kuba-Pawlak** [glpi-project/glpi#13453]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Contracts expiration query for notice begins les then 7 and 30 is the same query

Contracts where notice begins in less than 7 days and Contracts where notice begins in less than 30 days shows different counts of results on the Global View but when clik to show details results are the same.
![GLPI_1](https://user-images.githubusercontent.com/68420967/204759015-287cf021-d66d-486d-8c7c-a8640d242fa3.png)

### Page URL

https://helpdesk-test.walstead.pl/front/central.php

### Steps To reproduce

Open GLPI
Go to Global view
check count of dectected results for Contracts where notice begins in less than 7 days and Contracts where notice begins in less than 30 days. I have different count - for 7 days  I have 8, for 30 days I have 3 contracts.
Click Contracts where notice begins in less than 7 days 
and 
Click Contracts where notice begins in less than 30 days
I see the same result only 3 conttracts

**Comment by cconard96** [comment]
I confirmed the issue. Can you test the changes made in #13454?
