### ISSUE TITLE
Saved Search with global / user / category won't work

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi#13457]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hi,

If i select a search, with a global rules / User / Caractéristiques - Catégorie, it's work.
But, if i save them, reinit and reload them, i have "partial loading of the search" error, and the line with the global rules is missing.

if i use / User / Id, it's work.

### Steps To reproduce

1. add a global rules
2. select user / Category not NULL
3. save the search
4. reinit the search
5. select the saved search

### Anything else?

My users came from my AD

**Comment by cedric-anne** [comment]
I confirm the issue.

**Comment by cedric-anne** [comment]
Hi,

Can you check if #14027 fixes the issue?

**Comment by TheRoby** [comment]
Hi,

It's ok !
Thank you !
