### ISSUE TITLE
Bug Browser Notifications

### ISSUE THREAD

**Issue by jamersonsouza-novo** [glpi-project/glpi#13463]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0

### Bug description

hey guys, I have a problem with my glpi on an ubuntu LTS 20.04 server without an SSL certificate, the notifications are not showing up in the browser, I tried the Fix browser notifications solutions; fixes #10612 #10664 but that didn't work either. Sorry for the English, I'm using google translator

**Comment by trasher** [comment]
10.0.0 is very outdated, consider upgrading

**Comment by cedric-anne** [comment]
> server without an SSL certificate

Problem probably comes from this lack of SSL certificate. Indeed `Notification` API is only available on secure contexts. See https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts/features_restricted_to_secure_contexts.
