### ISSUE TITLE
Rule location : the number of id is displayed instead of the place name

### ISSUE THREAD

**Issue by Lophophanes** [glpi-project/glpi#13464]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5 (with GLPI Agent1.4)

### Bug description

Hello,
If I want to assign computers to an entity based on their names, the location name indicates an id (which adds to the list of places). The rule works in testing but not in production.
Thank you in advance for any help you can give me.

**Comment by stonebuzz** [comment]
Can you post here a screenshot to understand your issue (I do not reproduce for the moment)

Best regards

**Comment by trasher** [comment]
No feedback, I close
