### ISSUE TITLE
SNMP Connections

### ISSUE THREAD

**Issue by periodistacg** [glpi-project/glpi#13504]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi, 
SNMP inventory makes a connection between a switch and printer port.
You can see this connection in switch network port tab, but in printer network port tab appear disconnected.

**Comment by trasher** [comment]
Please first try with latest release and nightly build.

If you can reproduce with latest nightly build, feel free to reopen, providing an inventory file and all details sow we can reproduce the issue.

**Comment by periodistacg** [comment]
Network Equipment has a printer connected on Port43 (networkport 229, mac 00:12:a9...)
Networkport 229 shows correctly the connected printer (printer 1, networkport 11, mac 00:26:73...)
Networkport 11 does not shows the connected Network Equipment port

![image](https://user-images.githubusercontent.com/119592157/205291320-8cb39056-92df-418a-804f-48ce9999a119.png)
![image](https://user-images.githubusercontent.com/119592157/205291392-52ed6124-7486-4c54-a6c3-36150209936f.png)
![image](https://user-images.githubusercontent.com/119592157/205291421-cce1eed1-3950-4f2f-a9b1-347819fe4012.png)
