### ISSUE TITLE
Unable to add a solution when ToDo ticked

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#13503]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

If there is a task with ToDo type, when ticked the checkbox to set it as "done", If after that, I add a solution it doesn't recognize that the task is already done.

### Steps To reproduce

1. Enter in a ticket
2. Create a new task with ToDo option
3. Exit and enter to the same ticket
4. Tick the Task as complete (tick the checkbox)
5. Add a Solution

A warning said: You cannot resolve the ticket - You cannot solve/close a ticket with task do to
and the button " + Add" is hidded.

If you refresh the page and add the solution now the button appear.

### Anything else?

When add a solution (after tick a task as completed) the check on the completed task is not done

**Comment by cedric-anne** [comment]
Hi,

I close the issue as it is an issue of the behaviours plugin. Please open an issue on [plugin repository](https://github.com/yllen/behaviors).
