### ISSUE TITLE
API : inconsistency between code and doc

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1350]
Hi

When an API consumer POST multiple items, the source code and the unit tests tells the API will return HTTP 201

However the documentation says HTTP 207. Which one should be fixed ? The source or the documentation ?

**Comment by trasher** [comment]
According to wikipedia (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), 207 status is used for WebDAV; so API is correct and doc is not.

**Comment by trasher** [comment]
Also, doc makes difference between 201 and 207; so I do not know...

**Comment by trasher** [comment]
@btry you should receive 207 if one of the multiple has failed. You'll get 201 if all is OK. What is your case?

**Comment by orthagh** [comment]
according to documentation, you'll have:

- 201 when all ok
- 207, when one item of collection fail
- 400, when all fails

Checking the code, it seems to be ok

**Comment by orthagh** [comment]
the only little error in doc (i found) is in the second curl ex of https://github.com/glpi-project/glpi/blob/master/apirest.md#add-items
