### ISSUE TITLE
A series of unwanted "n" characters being inserted into the ticket description field text

### ISSUE THREAD

**Issue by informatica-tsa** [glpi-project/glpi#13518]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

After upgrading from version 9.5.9 to 9.5.11, whenever we edit some text content in the Description field in the ticket that has "line break", that is, more than one line in the text, a series of "n" characters are inserted in the text.
![Captura de tela 2022-12-04 090110](https://user-images.githubusercontent.com/22958473/205489310-c0894f50-128f-429b-a904-0a8d57acfe33.png)

https://user-images.githubusercontent.com/22958473/205489482-94dbd42b-b941-44c7-a904-17113a1d371a.mp4

### Page URL

/front/ticket.form.php?id=xxxxx

### Steps To reproduce

1-Open an existing ticket
2-Change description text (multiple lines)
3-Save

**Comment by cconard96** [comment]
This was already reported and fixed by commit ade4d2e076f5b118aebce9095161dffc73376c7e
