### ISSUE TITLE
Images add to a ticket are reduced in the notification

### ISSUE THREAD

**Issue by micter59** [glpi-project/glpi#13511]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

When an image is added to a ticket, an email notification is sent to users. The image is attached to the email notification, but in a lower resolution and/or compressed. While the image resolution is kept in the ticket, a user which works remotely without having access to GLPI won't be able to read what's on some screenshots for example.
Would it be possible to choose (globally) if image should be resized ?
This issue seems linked to my problem : https://github.com/glpi-project/glpi/issues/7872

Thanks a lot !

Michaël

### Steps To reproduce

1. Add a screenshot (PNG format) to a ticket
2. Receive the mail notification
3. See the picture, it is resized and not always readable.

**Comment by micter59** [comment]
In fact, we discover that the resize does not happen in every situation.
If the image is added as an attached file (in GLPI, or by replying to an email), it is resized.
If the image is added directly in the textarea in GLPI, or in the content of the reply by email, it is not resized.

**Comment by cedric-anne** [comment]
Hi,

Indeed, images are resized to limit e-mails size. It has been done a long time ago, but since then, transferring large mails is less problematic and the memory allocated on the PHP side has also been increased.
Maybe we could remove this behaviour or increase the size limit, but we have to do some benchmarks. Indeed, `phpmailer` consumes lots of memory to build emails, and it may be a problem when too many images are attached to a ticket. In GLPI 10.1, it will be replaced by `symfony/mailer`, that probably acts differently on this part.

**Comment by cedric-anne** [comment]
By the way, you should upgrade to GLPI 10.0.5.

**Comment by micter59** [comment]
I understand why images size is limited. But what I find strange is the fact that an image which is embedded inside the ticket content will not be resized.
You're right about GLPI 10.0.5 ;-D

**Comment by cedric-anne** [comment]
> I understand why images size is limited. But what I find strange is the fact that an image which is embedded inside the ticket content will not be resized.

Images in rich text should be resized according to the size defined in HTML code. If you resize your images in rich text editor, they should be resized also in notifications (see #12883).

**Comment by berilslv** [comment]
this is still relevant to 10.0.15, images added in followup(ticket) are dramitcaly reduced, so that email receiving user can't see it correctly. 
Is there any workaround?

**Comment by cedric-anne** [comment]
Hi,

In GLPI 11.0, attached images will no longer be resized, unless they were resized in the rich text editor, see #15723.

I close this issue as the enhancement has already been implemented.
