### ISSUE TITLE
Export ignores current sorting

### ISSUE THREAD

**Issue by dm-bo** [glpi-project/glpi#13519]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

In GLPI 10 export always sorts tickets by "Last update".

In GLPI v9 export used sorting applied on current web-page. It was very convinient and useful to get a list in one click. The workaround way is much longer: export CSV, sort it the right way, remove "Last update" column, export PDF.

New interface and new search are nice, especially the multy-sorting feature. However, it would be nice to keep old features too.

### Page URL

http://glpi.example.com/front/ticket.php

### Steps To reproduce

1. Create three tickets (1, 2, 3)
3. Modify the first one (1)
4. Go to the ticket list
5. Sort the list by "Opening date" descending (that gives the order 3, 2, 1)
6. Click the "Export" button on the toolbar
7. Click "All pages in landscape PDF" (or any other)
8. See the downloaded file (it contains tickets sorted by "Last update": 1, 3, 2)

### Your GLPI setup information

Information about system installation and configuration
--
GLPI 10.0.5 ( => /srv/www/glpi.example.com/public_html) 
Installation mode: TARBALL 
Current language:en_GB

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by #13032.
