### ISSUE TITLE
Error linking IT asset to network outlets

### ISSUE THREAD

**Issue by halexsandro** [glpi-project/glpi#1352]
Setup > DropDows > Network outlets (to create network outlets)
Assets > Computers > Any PC > Network ports > Any Network port > Network outlet (to link it)

The system is not linking network outlets to IT assets network interface. No messages, just no linking.

At 0.90.5 this function is normal... 
at 9.1.1 the problem exist.

**Comment by trasher** [comment]
I've just tested with the 9.1/bugfixes branch:
- link outlet to existing port,
- create port with outlet

Both cases are OK. Should be fixed as of GLPI 9.1.2
