### ISSUE TITLE
Inheritance error of operating systems in creating computers

### ISSUE THREAD

**Issue by halexsandro** [glpi-project/glpi#1353]
When a computer model is created and it is assigned an operating system, items created from the model do not inherit the operating system.

In 0.90.5 is normal
In 9.1.1 the problem exists

way to create the template:

Assets > Computers > Add > Blank Template
before, select the template and add a Operation System and select OS created at setup > dropdowns > Operating systems > Operating systems.

During creation, the operating system is displayed. After creation, the system does not appear and must be entered manually. Probable model inheritance error.

**Comment by trasher** [comment]
Seems to be fixed as well on 9.1/bugfixes branch; os, version, arch and so on are correctly set from the template.
