### ISSUE TITLE
Don't see the "Connected to" column in the Network Ports tab

### ISSUE THREAD

**Issue by hubMich** [glpi-project/glpi#13532]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0

### Bug description

Don't see the "Connected to" column in the Network Ports tab
![obraz](https://user-images.githubusercontent.com/38531048/205899281-0059fb1a-e9d3-44a0-97a5-25c877cad172.png)
And can't add this column to view, column is not on the list.

### Page URL

/front/computer.form.php?id=

### Your GLPI setup information

GLPI 10.0.0 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

**Comment by trasher** [comment]
10.0.0 is really outdated, please update to latest stable and see if you reproduce.

**Comment by hubMich** [comment]
This same situation on version 10.0.5

**Comment by cconard96** [comment]
i confirm the issue. Although it seemed to be in the global config by default, if you remove it, it doesn't re-appear in the list of columns to add.

**Comment by cedric-anne** [comment]
Fixed by #13544.
