### ISSUE TITLE
how to setup Receivers for office365

### ISSUE THREAD

**Issue by snakewqq** [glpi-project/glpi#13549]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.11

### Bug description

![image](https://user-images.githubusercontent.com/16697584/206194832-4d18cccf-72f1-493d-991b-04b8e0f1bf76.png)

please help me to config it , thanks.

**Comment by tbaror** [comment]
Hi,
you should first have you hekpdesk mailbox  user 
next in azure portal active directory you should create App registrations and set the Redirect URI , you got from GLPI , just make sure its work on https , youre GLPI (even self signed )
[img=FluxBB bbcode test]https://1drv.ms/u/s!AjfH52oTIe8uhxCntctbNlfl3ZOV?e=e9w8xG[/img] 
[img=FluxBB bbcode test][url=https://1drv.ms/u/s!AjfH52oTIe8uhxRxE7xHUhmKGyhq?e=agJM2J[/img]
[img=FluxBB bbcode test]https://1drv.ms/u/s!AjfH52oTIe8uhxMG7FMuTJWHgZ23?e=H1ahut[/img]
next you shoul install on GLPI plugin named  Oauth IMAP app and create azure provider 
[img=FluxBB bbcode test]https://1drv.ms/u/s!AjfH52oTIe8uhxXmmDNZu6CH09bH?e=xVgO9L[/img]
[img=FluxBB bbcode test]https://1drv.ms/u/s!AjfH52oTIe8uhxbVf4fXwOEv6E2D?e=7qE23t[/img]
after you created that you should go Receivers and configure as follows
[img=FluxBB bbcode test]https://1drv.ms/u/s!AjfH52oTIe8uhxc_fjHByxHKi0Vk?e=gchDDM[/img]
when you have bottom to make the authentication this will redirect you to office365 login you should provide you're helpdesk mail user and credential  
if everything went well you should click on action then click on Get Email Tickets now , this will show you summary of imported mail/tickets 
[img=FluxBB bbcode test]https://1drv.ms/u/s!AjfH52oTIe8uhxjC59vGAqXvIrsd?e=HtpLLM[/img]
tHATS it hupe it helped
BTW , i have issue of that imported mail not apear in tickets , and waiting for assitance
Thanks
