### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by lirmikey** [glpi-project/glpi#1354]
In version 0.90.3 it says for example:
From 1 to 70 **on** 70 instead of From 1 to 70 **of** 70

**Comment by AnaelMobilia** [comment]
@lirmikey 
Hello,

You could fix it on transifex by yourself if you want 
=> https://www.transifex.com/glpi/GLPI/dashboard/
You can use your github account to log-in :-)

**Comment by trasher** [comment]
We'll also have to check if the original string is OK or not

**Comment by trasher** [comment]
String has been updated, transifex should also have been :)
