### ISSUE TITLE
many unnecessary records are generated in the inventory history

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#13559]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6-dev

### Bug description

Good afternoon,
I have a problem, it is related to the fact that many unnecessary records are generated.
It was recommended to update from the night build, but this did not give a result, I also updated from the night build of the agent, but this did not give a result. [The request itself](https://github.com/glpi-project/glpi-agent/issues/285).
In my case, this is information about software removal and windows update patches. The inventory is performed every hour, and every hour, for a reason that I don't understand, I first display that the software has been removed and then installed again. Please tell me what this is related to and how to fix it?
Note this problem is not observed on all computers, but only on some, they have Windows 10 installed.

### Relevant log output

```shell
php-errors.php

[2022-12-07 22:18:01] glpiphplog.WARNING:   *** PHP Warning (2): Undefined property: stdClass::$operatingsystems_id in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php at line 157
  Backtrace :
  src/Inventory/Asset/MainAsset.php:862              Glpi\Inventory\Asset\OperatingSystem->handle()
  src/Inventory/Asset/MainAsset.php:782              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:950                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1522                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1591                        Rule->process()
  src/Inventory/Asset/MainAsset.php:564              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:244    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
```

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.6-dev ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.localhost.com 5.4.17-2136.313.6.el8uek.x86_64 #2 SMP Thu Oct 20 14:30:48 PDT 2022 x86_64
PHP 8.0.26 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysql, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="24M" safe_mode="" session.save_handler="files"
	upload_max_filesize="24M" 
Software: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/GLPI
	Host info: Localhost via UNIX socket
	
PHP version (8.0.26) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.6-dev"
GLPI_SCHEMA_VERSION: "10.0.6-dev@25bc425a251aba11aa530b6d4df1424416b6ecd3"
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.0.104.2', Port: '3268', BaseDN: 'DC=localhost,DC=com', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=ldapsearch-glpi,OU=Special,DC=localhost,DC=com', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mail2.localhost.com)

</details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	archisw              Name: Apps structures                Version: 2.2.9      State: Installed / not activated               
		Install Method: Marketplace
	archibp              Name: Business Processes             Version: 1.0.7      State: Not installed                           
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	connections          Name: Connections                    Version: 10.0.0     State: Installed / not activated               
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.9      State: Installed / not activated               
		Install Method: Marketplace
	dataflows            Name: Dataflows                      Version: 2.2.13     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.9      State: Installed / not activated               
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.2      State: Enabled                                 
		Install Method: Marketplace
	escalade             Name: Escalation                     Version: 2.8.0      State: Installed / not activated               
		Install Method: Marketplace
	financialreports     Name: Financial reports              Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.6      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Not installed                           
		Install Method: Marketplace
	reports              Name: Reports                        Version: 1.14.1     State: Installed / not activated               
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.10.0     State: Enabled                                 
		Install Method: Marketplace
	typology             Name: Typologies                     Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Подробные отчеты          Version: 1.8.2      State: Enabled                         
		        Install Method: Marketplace

</pre></details>

**Comment by Badkempachi** [comment]
![1](https://user-images.githubusercontent.com/97535165/206392725-470b1f9a-5992-4b62-9dd2-c300be1e195b.jpg)

**Comment by Badkempachi** [comment]
![2](https://user-images.githubusercontent.com/97535165/206392768-769cbf12-c111-4077-b15b-02458b1b8c24.jpg)

**Comment by stonebuzz** [comment]
Hi @Badkempachi 
can you post here related inventory file ?

Best regards

**Comment by stonebuzz** [comment]
If possible the one when KB are added and the one when KB are deleted

**Comment by Badkempachi** [comment]
> 
In the form of json is it suitable? Did I download it from the computer tab, or do I need an inventory file that is generated locally on the computer?
[computer_0_50.json.txt](https://github.com/glpi-project/glpi/files/10183624/computer_0_50.json.txt)

**Comment by stonebuzz** [comment]
inventory file that is generated locally on the computer may help

**Comment by stonebuzz** [comment]
On my side, no error from json inventory file (KB software are still present when reimport json file)

**Comment by Badkempachi** [comment]
> On my side, no error from json inventory file (KB software are still present when reimport json file)

In this case, a json file was presented at the time when the software was being added, for a complete test, a second inventory file with the removal of this software will be required. The strangest thing is that this happens with computers on which additional software was not installed for a day or even more, and the computer itself could work for several days. It is very unclear to me what can cause such a problem. 
I will attach the inventory file in which the software will be removed, as it will be on my hands.

**Comment by stonebuzz** [comment]
the second file will allow me to compare the data.

If they are identical the problem will not be on the agent's side

Best regards

**Comment by Badkempachi** [comment]
> Other question : have you got some locks on this computer (`Lock` tab)
> 
> Best regards
There is, but only here. As far as we know, computers can only be blocked here.
![sc](https://user-images.githubusercontent.com/97535165/206407330-dfbbb671-903b-4dd6-8de7-f5bbd9f3cff9.jpg)

**Comment by stonebuzz** [comment]
Please look at ```Lock``` tab et post here a screenshot.

**Comment by Badkempachi** [comment]
> Please look at `Lock` tab et post here a screenshot.

I'm sorry I misunderstood you
![lock](https://user-images.githubusercontent.com/97535165/206411417-af6d6822-c31d-4280-a109-51aa454cbb33.jpg)

**Comment by stonebuzz** [comment]
no problem, it's just to make sure that the locks don't interfere with our problem

**Comment by Badkempachi** [comment]
> the second file will allow me to compare the data.
> 
> If they are identical the problem will not be on the agent's side
> 
> Best regards

I upload the inventory files. In this case, I received the information from a friend's computer.
[computer_0_81_del software.json.txt](https://github.com/glpi-project/glpi/files/10184224/computer_0_81_del.software.json.txt)
[computer_0_81_add software.json.txt](https://github.com/glpi-project/glpi/files/10184225/computer_0_81_add.software.json.txt)

**Comment by stonebuzz** [comment]
Did you modify the files, the json  is not well formed!

**Comment by stonebuzz** [comment]
Files are not identical for the list of software

![image](https://user-images.githubusercontent.com/7335054/206426676-72c82a92-9376-4324-95f6-21271f9b98a2.png)

@g-bougard an idea? Perhaps we should transfer this issue to https://github.com/glpi-project/glpi-agent

**Comment by stonebuzz** [comment]
> Perhaps we should transfer this issue to https://github.com/glpi-project/glpi-agent

Or create new one, records are logical on the side of GLPI

**Comment by Badkempachi** [comment]
> From `computer_0_81_add software.json.txt` we have more informations about operating system
> 
> ![image](https://user-images.githubusercontent.com/7335054/206427375-862123b3-2af9-4d09-8f8b-cbc911cb0eb2.png)

please, delete the screenshot

**Comment by trasher** [comment]
I close since this is not a GLPI issue

**Comment by Badkempachi** [comment]
> Hi @Badkempachi can you still apply #13565 as you'll at least have meaningful history entry for software deletion ?
Hi,
it didn't work for me

**Comment by g-bougard** [comment]
Fyi, the patch won't fix old "delete" entries but only new ones.

**Comment by trasher** [comment]
No. #13565 fix missing information on logged events; that won't fix anything.

On a GLPI point of view, there is no bug here. Both provided inventory files has different contents on softwares, therefore GLPI adds/deletes them; that's expected.

**Comment by Badkempachi** [comment]
> No. #13565 fix missing information on logged events; that won't fix anything.
> 
> On a GLPI point of view, there is no bug here. Both provided inventory files has different contents on softwares, therefore GLPI adds/deletes them; that's expected.

Agree that this is not normal. From what I saw, the problem lies on the Windows 10 operating system, I don’t observe this problem on Linux and windows server.
And what is most interesting is that not all computers on Windows 10 behave this way, but only some of them. But it's still not very clear what the problem is, the computers themselves are in the domain and are controlled by GPO.
From the logs, I see that the problem with the generation of repeated events with the installation\removal of software began, in fact, from the beginning of November 2022.

**Comment by stonebuzz** [comment]
Please open new issue here -> https://github.com/glpi-project/glpi-agent
