### ISSUE TITLE
Email notifications - followups - URGENT

### ISSUE THREAD

**Issue by willgl1** [glpi-project/glpi#13566]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

Email followups has been blanked for some users this is preventing followups.
![issue email 1](https://user-images.githubusercontent.com/107202756/206473522-28e994d9-817a-4a44-9041-ff562934b99f.png)
![issue email 2](https://user-images.githubusercontent.com/107202756/206473528-6eb8dc8f-9117-46bb-8cc9-71d4bad711c3.png)

### Steps To reproduce

1. Go into a ticket
2. Press the bell icon
3. The field is blank
4. Click on the user and email is present
5. Under notification queue a number is present but no emails send
6. Ticket solution emails still send.,
Not all users are affected

**Comment by tuxxic** [comment]
Hello,

I have the same issue.

**Comment by cedrobert** [comment]
Hello,
I also have the same issue.
Did you find a workaround for it?

**Comment by willgl1** [comment]
> Hello, I also have the same issue. Did you find a workaround for it?

Sadly not no, tried to re import users but no luck. Ended up re adding the email on tickets one by one. But still missing some due to the amount of work it is for hundreds of staff. Big issue for us.

**Comment by tuxxic** [comment]
I found useful to add the patch in #13280 and it solved my issue

**Comment by cedrobert** [comment]
Even with #13280, the user's email address does not appear in the 'edit notification settings' menu, and emails are still not being sent.

**Comment by meijin4** [comment]
Same issue and can't fide "rejectedsolution" in the notifications config page.

**Comment by cedric-anne** [comment]
When this field is blank, notification will be sent to the default email address of the user. This field is just meant to be the an alternative email.

Main issue was probably related to #13280 and is probably fixed. I close this issue, feel free to reopen it if issue persist in GLPI 10.0.6 and give some more details about the way to reproduce.

**Comment by nykroy** [comment]
I have same problem when i open a ticket from ticket template with ticket recurrents. The field is blank an the Tecnician didnt receive notification email 
Version
10.0.7

Steps To reproduce

1. Go into a ticket
2. Press the bell icon
3. The field is blank
4. Click on the user and email is present
5. Under notification queue i havent got the email notification.
6. If i unassigned the user and assigned de user manualy the notification wil send and the field on the bell icon from have the email write correctly.

**Comment by nykroy** [comment]
More details after more test. Only didnt receive notificatión user assigned but user observer an user request receive notifications without problems.

**Comment by trasher** [comment]
Please do not comment on closed tickets. Feel free to open a new issue with all requsted information.
