### ISSUE TITLE
[GLPI 10 Bugfixes] Multiples saved searches pinned as default

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#13577]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

When you define as default a saved search & if you return on the list, multiples searches are pinned : 

![image](https://user-images.githubusercontent.com/13178158/206719130-f1027dbf-7c11-4f02-93e7-1f15f91514a0.png)

**Comment by tsmr** [comment]
for information into public function getMine (SavedSearch.php) -> the 2 searches are tagged as  [is_default]

**Comment by trasher** [comment]
I do not reproduce on current 10.0/bugfixes

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.

To reproduce:
 - create a public saved search from user1, and mark it as default,
 - create a private saved search from user2, and mark it as default,
 - -> user2 will see both search as default in the saved search panel.

**Comment by ftoledo** [comment]
i can confirm this bug on 10.0.6

**Comment by trasher** [comment]
Please try #13999
