### ISSUE TITLE
Unable to select Project as SLA Criterion, unable to filter ticket by Project

### ISSUE THREAD

**Issue by dhrzic** [glpi-project/glpi#13573]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello, 
I'm not sure if this is an bug or new feature request, but I'm not able to select Project as an Criterion under Escalation level (SLA) and the same thing with filtering tickets by Project. 

Kind Regards,
Domagoj
![slika](https://user-images.githubusercontent.com/104624347/206707247-16e55170-5e22-48d9-a130-7271af87f4a2.png)

**Comment by cedric-anne** [comment]
Hi,

GLPI 10.0.3 is outdated. Please upgrade to GLPI 10.0.5 and check if problem persist.

**Comment by trasher** [comment]
Feel free to reopen if issue is not solved on latset stable

**Comment by dhrzic** [comment]
Hi, ok I will do the upgrade and test again.

Regards,
Domagoj

**Comment by dhrzic** [comment]
Hello,

I've upgraded and tested with 10.0.5 and same thing, there is no option as posted earlier.

Regards,
Domagoj
