### ISSUE TITLE
When I use GLPI_VAR_DIR and GLPI_CONFIG_DIR the glpi system cron don't work

### ISSUE THREAD

**Issue by akoscomp** [glpi-project/glpi#13570]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.5

### Bug description

When I place config and files directory outside of glpi source folder and set GLPI_VAR_DIR and GLPI_CONFIG_DIR env variables the system cron don't work.
The internal glpi cron still work.
I got this error, when I try to run the command manually:
```
GLPI seems to not be configured properly.
Database configuration file "/var/www/html/glpi/config/config_db.php" is missing.
You have to either restart the install process, either restore this file.
```
After I put back the config and files directory under /var/www/html/glpi/ the cron work as expected.

### Steps To reproduce

1. install a clear glpi
2. set GLPI_VAR_DIR and GLPI_CONFIG_DIR envs
3. move the config and files folder to new path
4. create a new ticket
5. wait for cron to execute the notification process and follow cron.log

Nothing happens

**Comment by cedric-anne** [comment]
Hi,

What are you meaning exactly by `set GLPI_VAR_DIR and GLPI_CONFIG_DIR envs` ?

**Comment by trasher** [comment]
You've defined directories in web environment and not in cli one. Refer to documentation https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations to properly configure your own paths.

**Comment by eandry77** [comment]
I also moved my config dir in /etc, and since I need to add --config-dir=/etc/glpi/config when lauching a php console command.

**Comment by akoscomp** [comment]
I use glpi in docker and cron task that run the glpi cron don't work if I move the config and files folder out from glpi folder.
I don't think that I can pass the config folder locaton to this command:
/usr/bin/php /var/www/html/glpi/front/cron.php
and this command can't realize that the GLPI_CONFIG_DIR variable was set.

**Comment by cedric-anne** [comment]
What are you meaning exactly by `set GLPI_VAR_DIR and GLPI_CONFIG_DIR envs` ?

**Comment by akoscomp** [comment]
> What are you meaning exactly by `set GLPI_VAR_DIR and GLPI_CONFIG_DIR envs` ?
I run:
export GLPI_VAR_DIR=/glpi_files
export GLPI_CONFIG_DIR=/glpi_config

**Comment by cedric-anne** [comment]
Are you sure that this export is available in cron execution context ?

**Comment by cedric-anne** [comment]
First entry found on Google : https://stackoverflow.com/questions/2229825/where-can-i-set-environment-variables-that-crontab-will-use

**Comment by cedric-anne** [comment]
I confirm that you can either defining the variable in command call, either exporting the variable, and it should work.

![image](https://user-images.githubusercontent.com/33253653/206712636-729666c1-7b76-40c7-820e-3aeb8594586d.png)
