### ISSUE TITLE
Mailgate CronTask hangs when there's duplicated item relation

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi#13581]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

This is somehow related to #13579 - after I unlock the MailGate task, it got stuck again but with the following log output.

<img width="785" alt="image" src="https://user-images.githubusercontent.com/2974895/206789365-c392abfe-daf6-41fe-99a9-4f5ad3814e4b.png">

When I attempt to receive the messages manually through the "Destinations" page, I got the following error message:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/2974895/206790059-1fe64b7f-65cb-457b-bdd3-2a352e6e58cd.png">

The following messages are listed into "Messages not imported" at the "Destinations" page:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/2974895/206790528-80d8c4cb-4023-47d3-96f2-acd1f7e99914.png">

Other tasks seems to continue being executed through Task Scheduler (Windows CRON) even with the "mailgate" task being stuck.

### Relevant log output

``php-error.log`` file:

````
[2022-12-09 16:31:27] glpiphplog.WARNING:   *** PHP User Warning (512): Duplicated document item relation in C:\inetpub\glpi\src\Document_Item.php at line 135
  Backtrace :
  src\Document_Item.php:135                          trigger_error()
  src\CommonDBTM.php:1279                            Document_Item->prepareInputForAdd()
  src\CommonDBTM.php:5534                            CommonDBTM->add()
  src\CommonITILObject.php:2578                      CommonDBTM->addFiles()
  src\Ticket.php:2129                                CommonITILObject->post_addItem()
  src\CommonDBTM.php:1325                            Ticket->post_addItem()
  src\MailCollector.php:848                          CommonDBTM->add()
  src\MailCollector.php:1852                         MailCollector->collect()
  src\CronTask.php:1018                              MailCollector::cronMailgate()
  front\crontask.form.php:52                         CronTask::launch()
````

No errors reported in ``sql-errors.log``, ``cron.log`` and ``mail*.log`` files.

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.5 ( => C:\inetpub\glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT UNIFI 10.0 build 17763 (Windows Server 2016) AMD64
PHP 7.4.33 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.40-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: juliano@localhost/dbglpi
	Host info: localhost via TCP/IP
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.40) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\inetpub\glpi/files/_cache has been validated.
Write access to C:\inetpub\glpi/config has been validated.
Write access to C:\inetpub\glpi/files/_cron has been validated.
Write access to C:\inetpub\glpi/files has been validated.
Write access to C:\inetpub\glpi/files/_dumps has been validated.
Write access to C:\inetpub\glpi/files/_graphs has been validated.
Write access to C:\inetpub\glpi/files/_lock has been validated.
Write access to C:\inetpub\glpi/files/_pictures has been validated.
Write access to C:\inetpub\glpi/files/_plugins has been validated.
Write access to C:\inetpub\glpi/files/_rss has been validated.
Write access to C:\inetpub\glpi/files/_sessions has been validated.
Write access to C:\inetpub\glpi/files/_tmp has been validated.
Write access to C:\inetpub\glpi/files/_uploads has been validated.
The following directories should be placed outside "C:\inetpub\glpi":
‣ "C:\inetpub\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\inetpub\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\inetpub\\glpi"
GLPI_CONFIG_DIR: "C:\\inetpub\\glpi/config"
GLPI_VAR_DIR: "C:\\inetpub\\glpi/files"
GLPI_MARKETPLACE_DIR: "C:\\inetpub\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "C:\\inetpub\\glpi/files"
GLPI_CACHE_DIR: "C:\\inetpub\\glpi/files/_cache"
GLPI_CRON_DIR: "C:\\inetpub\\glpi/files/_cron"
GLPI_DUMP_DIR: "C:\\inetpub\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "C:\\inetpub\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\inetpub\\glpi/files/_locales"
GLPI_LOCK_DIR: "C:\\inetpub\\glpi/files/_lock"
GLPI_LOG_DIR: "C:\\inetpub\\glpi/files/_log"
GLPI_PICTURE_DIR: "C:\\inetpub\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\inetpub\\glpi/files/_plugins"
GLPI_RSS_DIR: "C:\\inetpub\\glpi/files/_rss"
GLPI_SESSION_DIR: "C:\\inetpub\\glpi/files/_sessions"
GLPI_TMP_DIR: "C:\\inetpub\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\inetpub\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\inetpub\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "C:\\inetpub\\glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (C:\inetpub\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\inetpub\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.4.4 in (C:\inetpub\glpi\plugins\pdf\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\glpi\vendor\psr\cache\src)
league/csv in (C:\inetpub\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\glpi\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\inetpub\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\inetpub\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (C:\inetpub\glpi\vendor\symfony\polyfill-php80)
symfony/polyfill-php81 in (C:\inetpub\glpi\vendor\symfony\polyfill-php81)
symfony/polyfill-php82 in (C:\inetpub\glpi\vendor\symfony\polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: '192.168.0.1', Port: '389', BaseDN: 'dc=example;dc=com', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'example\administrator', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (glpi@mail.example.com)

</details><details><summary>Plugins list</summary><pre> 
	actualtime           Name: ActualTime                     Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	news                 Name: Alertas                        Version: 1.10.5     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamental                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.1   State: Enabled                                 
		Install Method: Manual
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	resources            Name: Recursos humanos               Version: 3.0.4      State: Enabled                                 
		Install Method: Manual
	reports              Name: Relatórios                     Version: 1.16.0     State: Enabled                                 
		Install Method: Manual
	reservation          Name: Reservation                    Version: 2.4.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

Please let me know if there's anymore information I can provide to troubleshoot and fix this issue.

**Comment by cedric-anne** [comment]
Hi,

Can you provide other entries in error logs that happen at the same time ? The mentionned entry is a warning, it is not a blocking error, so if execution is stopped, it is related to something else.

**Comment by eduardomozart** [comment]
Hello @cedric-anne,
I noticed that the "List of mails not imported" changes every time I pressed the "Obter e-mails agora" (Fetch mails now) and it was successfully excluding the mails from the webmail when importing them 10 mails per time at GLPI. So I had to click at "Fetch mails now" until it fetched all the mails available at our webserver. After importing them all, the error message wasn't being shown anymore (just an "information" one informing that there was 0 mails available for importing) and the Mailgate task started and worked as expected. I believe that when the Mailgate task hangs (like #13579) it didn't seem to properly recovery itself because it should be able to fetch the mails like the manual action does. There seem to be other logic related to the Mailgate task and it would be great if the logic behind the "Fetch mails now" button would be integrated at the Mailgate task, because it's strange that I could fetch the mails manually but not through the Mailgate task.

**Comment by cedric-anne** [comment]
List of mails not imported is emptied before each new mail collecting action (see #8297).

The logic behind the manual fetching is the same as the one launched by the crontask. Maybe there is something wrong in the context execution of your GLPI cron (not same user as webserver, permission issues, missing extensions, ...).

Again, can you provide other entries in error logs that happen at the same time ?

**Comment by eduardomozart** [comment]
Hello @cedric-anne, sadly there was no logs being reported anywhere else.
I did set the expiration time manually at the command line because I had problems into the past related to the Mailgate task getting stuck (#8836). But even when running the Mailgate task manually through the browser it was throwing a "Timeout" error of IIS and when refreshing the page, it was still being reported as "Running" and got stuck.
Another possibility I was thinking - if the Mailgate implements the same logic as the "Actions" tab of "Destinations" page - is that maybe the mails to be fetched was too much (200) because when fetching 10 mails per time (default logic of the "Actions" tab of "Destionations" page) it was working as it should, as there was about ~300 mails by the time the Mailgate task got stuck. Maybe GLPI isn't having time enough to fetch all mails and the PHP timeout is triggered but the task isn't aware that it was suddenly closed? There's any error being thrown when those kind of exception (PHP timeout) happened?

**Comment by cedric-anne** [comment]
Can you check if there is som PHP processes that are running from a really long time ?

Timeout on IIS means that PHP is probably still running in background and IIS stops waiting fo a response.  In this case, I do not know if PHP process will be just killed, or if it will continue its job. If it is killed, then the crontask status will not be updated and will remain in `Running` state. If it is not killed, then the task will be put back to `Waiting` state at some moment.

I do not really know how allof this works on a Windows environment. Could you ensure that there is no PHP timeout active when crontask is executed via `Windows Task Scheduler` ?

**Comment by eduardomozart** [comment]
Hello @cedric-anne,
I can confirm there's no other PHP instance because I created the task with the following command line (I already have problems with the Mailgate task getting stuck before at #8836, that is because I'm enforcing the timeout directly at the command line because PHP CLI doesn't respect the timeout set at the PHP directive by default):

````
%windir%/system32/schtasks.exe /create /tn "GLPI CRON" /sc minute /mo 5 /tr "C:\PHP\v7.4\php.exe -d max_execution_time=600 \"C:\inetpub\glpi\front\cron.php\"" /ru system
````

![image](https://user-images.githubusercontent.com/2974895/207041818-6f62987d-944d-4482-9027-036b0a5c07eb.png)

The task is run and closes as expected, even with the "mailgate" task getting stuck (ie. it doesn't shown as "Running" at ``Windows Task Scheduler``, it simply runs other task as expected and got back to the "PRONTO" [Ready] state, running the tasks as it should).

**Comment by cedric-anne** [comment]
@eduardomozart 

I think you should not set any timeout when executing the GLPI crontask. Indeed, there is no reason for a task to get stucks into an infinite execution. If a task is calling an external service, there will be a timeout defined on this call (for instance, there is a 30 seconds timeout when GLPI authenticates/collects emails from IMAP server). Moreover, if you stop the PHP execution during a task execution, then GLPI will not be able to execute the routine that updates its status of this specific task, and so it will remains in the `running` state.
Since GLPI 9.5.5 (#8878), we improved error handling on crontasks. You should not try to implement some kind of workaround to possible problems encountered on these tasks, it may result in unexpected effects and it makes debugging a bit hard.

I close this issue as the main problem here is that the way you schedule GLPI tasks execution is killing their execution before they are able to finish.
`Duplicate document item relation` is just an annoying warning and has probably no impact on task hanging symptom.
