### ISSUE TITLE
add followup let waiting status

### ISSUE THREAD

**Issue by Sicoval31** [glpi-project/glpi#13583]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

If a ticket is in *waiting* status, add a folowup let the status and not change it.
The option "waiting" is enabled by default.

No logs errors

-----
Si j'ai un ticket "en attente", lorsque je rajoute un suivi, le statu du ticket ne passe pas en "attribué à".
L'option de mise en attente reste activée lors de l'écriture du suivi ; sa désactivation étant manuelle

Pas d'erreurs dans les logs

**Comment by msizec** [comment]
de mémoire ca na jamais été automatique le chgt de statut ...

**Comment by trasher** [comment]
Non english message has been removed.

**Comment by Sicoval31** [comment]
English comment must be optionnal ... and GLPI is a french project !

Mon technicien référent m'assure que si, ce comportement existait en V9. A consulter les forums, d'autres ont relevé ce problème. 
En toute logique, un nouveau suivi signifie une nouvelle action sur l'incident, donc, un changement de statut, qui n’empêche pas pour autant de le remettre "en attente" si le besoin le justifie. Mais si je rajoute un commentaire, c'est que j'ai avancé sur le ticket.
Sauf dans le cas où une demande est faite à l'utilisateur et le nouveau suivi est une relance du suivi précédent

**Comment by Tartiflette-glpi** [comment]
Le changement automatique du statue s'effectue si c'est le demandeur qui envoi un suivi. Le ticket passe alors en "attribué a..." pas de changement si c'est le technicien qui envoi un suivi... En tout cas c'est comme ça que fonctionne le mien.

**Comment by Sicoval31** [comment]
mmmh oui, ça c'est assez logique aussi, possible que mon référent ait zappé ce principe. avec l'age .... le pauvre ;)

**Comment by cedric-anne** [comment]
As @Tartiflette-glpi says, this is an intended behaviour.

The `waiting` status will be removed only if the requester adds a reply.
