### ISSUE TITLE
Unable to assign LDAP users to assets

### ISSUE THREAD

**Issue by polar147** [glpi-project/glpi#13589]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When i try to assign LDAP users to assets they are no showed in combobox

![users](https://user-images.githubusercontent.com/19316838/207148134-0caa8ec4-8e7a-45ba-b8d4-c56ad873fe85.png)
![asset](https://user-images.githubusercontent.com/19316838/207148129-50fa193c-8467-4d1a-8a47-9d93fdda4cd0.png)

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.5 (/glpi => D:\wampstack\apache2\htdocs\glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT DMSV002 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.0.22 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mongodb, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip,
	zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.20
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: root@172.16.0.12/glpi
	Host info: 172.16.0.12 via TCP/IP
	
PHP version (8.0.22) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.20) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_cache has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/config has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_cron has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_dumps has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_graphs has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_lock has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_pictures has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_plugins has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_rss has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_sessions has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_tmp has been validated.
Write access to D:\wampstack\apache2\htdocs\glpi/files/_uploads has been validated.
The following directories should be placed outside "D:\wampstack\apache2\htdocs\glpi":
‣ "D:\wampstack\apache2\htdocs\glpi/files" ("GLPI_VAR_DIR")
‣ "D:\wampstack\apache2\htdocs\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to D:\wampstack\apache2\htdocs\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "D:\\wampstack\\apache2\\htdocs\\glpi"
GLPI_CONFIG_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/config"
GLPI_VAR_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files"
GLPI_MARKETPLACE_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files"
GLPI_CACHE_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_cache"
GLPI_CRON_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_cron"
GLPI_DUMP_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_locales"
GLPI_LOCK_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_lock"
GLPI_LOG_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_log"
GLPI_PICTURE_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_plugins"
GLPI_RSS_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_rss"
GLPI_SESSION_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_sessions"
GLPI_TMP_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "D:\\wampstack\\apache2\\htdocs\\glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (D:\wampstack\apache2\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (D:\wampstack\apache2\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (D:\wampstack\apache2\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.5.0 in (D:\wampstack\apache2\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (D:\wampstack\apache2\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (D:\wampstack\apache2\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (D:\wampstack\apache2\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (D:\wampstack\apache2\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (D:\wampstack\apache2\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (D:\wampstack\apache2\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (D:\wampstack\apache2\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (D:\wampstack\apache2\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (D:\wampstack\apache2\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (D:\wampstack\apache2\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (D:\wampstack\apache2\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (D:\wampstack\apache2\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (D:\wampstack\apache2\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (D:\wampstack\apache2\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (D:\wampstack\apache2\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (D:\wampstack\apache2\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (D:\wampstack\apache2\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (D:\wampstack\apache2\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (D:\wampstack\apache2\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (D:\wampstack\apache2\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (D:\wampstack\apache2\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (D:\wampstack\apache2\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (D:\wampstack\apache2\htdocs\glpi\vendor\psr\cache\src)
league/csv in (D:\wampstack\apache2\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (D:\wampstack\apache2\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (D:\wampstack\apache2\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (D:\wampstack\apache2\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (D:\wampstack\apache2\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (D:\wampstack\apache2\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (D:\wampstack\apache2\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (D:\wampstack\apache2\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (D:\wampstack\apache2\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (D:\wampstack\apache2\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (D:\wampstack\apache2\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (D:\wampstack\apache2\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (D:\wampstack\apache2\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (D:\wampstack\apache2\htdocs\glpi\vendor\symfony\polyfill-php81)
symfony/polyfill-php82 in (D:\wampstack\apache2\htdocs\glpi\vendor\symfony\polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: '172.16.0.12', Port: '389', BaseDN: ' dc=DM,dc=LOCAL', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'mario.brandao@dm.local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	badges               Name: Crachás                        Version: 3.0.0      State: Not installed                           
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.13     State: Not installed                           
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 10.0.3+1.0 State: Enabled                                 
		Install Method: Manual
	treeview             Name: Tree view                      Version: 1.10.0     State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by keguira** [comment]
the user has to be active (which seems the case) and in the same entity. Or at least in same entity tree if you use entity inheritance. Can you confirm this point ?

**Comment by cedric-anne** [comment]
Hi,

Visible users here are users that has the `Ticket: BEEING IN CHARGE` right on item entity.
This has not changed since v0.84 (0d6ce30c3454b35a0f55d15140cc53b478ecbe3c), so I consider this is not a bug.
