### ISSUE TITLE
[9.5.6][10.0.5] class TicketFollowup

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#13599]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.5 et 9.5.6

### Bug description

Good morning,
I have plugins that used the function: 
	```
$followups = new TicketFollowup();
	$followupsModif['tickets_id'] = $idticket;
	$followupsModif['date'] = date("Y-m-d");
	$followupsModif['users_id'] = Session :: getLoginUserID();
	$followupsModif['content'] = "Message automatique : ce ticket est transf&eacute;r&eacute; de ".$nomAncienEntite." &agrave; ".$nomNouvelleEntite." par ".$user->getField('realname');
	$followupsModif['is_private'] = 0;
	$followupsModif['requesttypes_id'] = 0;
        $followupsModif['itemtype'] = 'Entity'; //YD
        $followups->add($followupsModif);
```
but the TicketFollowup class no longer exists nor the add function of course.
Is there an equivalent? I don’t know how long it hasn’t worked.
I’m in 9.5.6 and I’m going to be in 2023 in 10.0.5
Thank you

**Comment by cedric-anne** [comment]
Hi,

You have to use `ITILFollowup` class, with `itemtype=Ticket` and `items_id` instead of `tickets_id`.

**Comment by falco2001** [comment]
Good morning,
with this it’s ok . I didn’t really look at class inheritances 
 ```
$ticketFollowup = new ITILFollowup();//YD 
        $ticketFollowup->add($followUpInput)
```

**Comment by falco2001** [comment]
Good morning,
I just switched to PHP 8 and I have an error in plugins that I didn’t have in php 7.3: 
`Uncaught Exception Error: Undefined constant "Ticket" in /var/www/assistance-dev/plugins/transfertticket/front/transfertTicket.form.php at line 60`

Code : 
```
// Debut YD
       $message = "Message automatique : ce ticket est transf&eacute;r&eacute; de ".$nomAncienEntite." &agrave; ".$nomNouvelleEntite." par ".$user->getField('realname');
       
           $followUpInput = [
           'date'                            => $_SESSION['glpi_currenttime'],
           'users_id'                        => Session::getLoginUserID(),
           'content'                         => $message,
           '_do_not_compute_takeintoaccount' => true
         ];
         // GLPI 9.5.9+
          $followUpInput += [
            'items_id' => $idticket,
            'itemtype' => Ticket,
         ];
          
        $ticketFollowup = new ITILFollowup();//YD 
        $ticketFollowup->add($followUpInput);
         
         // Fin YD
```
do you have an idea? Thank you

**Comment by falco2001** [comment]
it is ok by putting:  
'itemtype' => 'Ticket', à la palce de 'itemtype' => Ticket,   
!!!
