### ISSUE TITLE
I can see the html tags in the knowledge base instead of interpreting 

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#13606]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6-dev

### Bug description

![obraz](https://user-images.githubusercontent.com/68922721/207573297-5bb07c3b-f6ad-48a2-ac6c-bb8f5cd62618.png)

![obraz](https://user-images.githubusercontent.com/68922721/207573367-4d32cbc6-5c24-4150-ae7c-d06fb1507172.png)

### Relevant log output

```shell
No errors in logs.
```

### Steps To reproduce

1. I'm creating a new knowledge base article.
2. I add, for example, a 20KB gif (the insert image icon in editing tools).
3. I click the Add button to save.
4. It seems OK.

5. I replace the file with another gif - 500KB (or I create a new article and add this gif).
6. I can see the added gif.
7. I save the change.
8. I can't see the gif, only the html tag

### Anything else?

I don't know if it has to do with file size. I don't think so, as I recently had a similar situation purely with the numbering setting (< li >).

Here is the test file: 
![test2](https://user-images.githubusercontent.com/68922721/207573080-e4f77872-16c6-4038-810e-4355c882eef3.gif)

From Chrome Console (affected resource: tinymce.js:49681)
![obraz](https://user-images.githubusercontent.com/68922721/207574704-9f248f7a-f6f1-474b-b7c0-7e499fefa627.png)

Forum: [https://forum.glpi-project.org/viewtopic.php?pid=497680#p497680](https://forum.glpi-project.org/viewtopic.php?pid=497680#p497680)

**Comment by Reaking1** [comment]
it's my thought, but I will go check your HTML tags and check your CSS if you can.

**Comment by WebGregGit** [comment]
Hi @Reaking1 
Thank you for the hint. If you mention css you mean "UI customization" - I don't have my own styles defined. I haven't edited the source of the post either - I'm just using the editor window.

If you meant some GLPI source files - I only installing published releases. While I modify the files manually according to released fixes.

**Comment by cedric-anne** [comment]
Hi,

You should try to set an higher value in `pcre.backtrack_limit`.

#13016 was proposed to fix this, but has been reverted in #13446 due to unexpected side-effects. As fixing it requires a huge refactor of rich text management, it cannot be done on 10.0 version.

**Comment by WebGregGit** [comment]
Hi @cedric-anne 

Thank you for your response. I did a test with: 
pcre.backtrack_limit=1000000 (6x0) - the gif is still visible as code
pcre.backtrack_limit=10000000 (7x0) - the gif is displaying correctly

> As fixing it requires a huge refactor of rich text management, it cannot be done on 10.0 version.

So it won't be possible to fix it? You marked it as a bug - leave this issue as open or should I close it?

**Comment by cedric-anne** [comment]
I want to keep it open, as we may fix it in a future major version of GLPI.

**Comment by trasher** [comment]
Sure this is something we can try to fix; but adapting PHP/MySQL or web server is something quite common for apps like GLPI; this is a correct solution to fix your issue.

**Comment by Ressy66** [comment]
I recently noticed many artciles, after an upgrade have html code in the displayed KB FAQ, these are text articles,  when we moved to v9 from an ancient release, I thought it updatred all of them, but seems not all, after other issue today finding many many many articles are not published, I started checking a lot and found a large numbe rof articles like this, and well no docs I can find and google is useless, no idea how to fix it.  these I know displayed corectly on the older versions  (we are taliking 8 or so years ago).  Some were copied from our web pages  going back to early 2000's  glpi  back then, 0.9 IIRC, accepted and displayed that code perfectly, but sometime in teh updates in past coupe years, that did not parse, some  has css or styles but many is plain html with only p's and br's no css.

**Comment by Ressy66** [comment]
Ok so its HTML escpaing, how to clean all that up?
(I am not a developer or html/css/php code junkie)

**Comment by cedric-anne** [comment]
@Ressy66 

Looking at your comment, it seems that your are facing a different issue. Current one is related to an issue during upload of big images. Please open a new issue and give all requested information.

**Comment by cedric-anne** [comment]
#14592 fixes this issue. Fix will be available in GLPI 10.1.
