### ISSUE TITLE
Search filter doesn't find associated items

### ISSUE THREAD

**Issue by haary** [glpi-project/glpi#13600]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When Associated items are added to a Appliances view  the search filter doesn't find anything when searching for an associated item.

### Steps To reproduce

1. Under Management/Appliances add some Applicances
2. Click on the Appliance and add some items (e.g. computers, databases ...)
3. Back in the list view, click on "Select default items to show" and add "Associated items".  Now you can see a column with the items added in step 2.
4. In the search box with the default settings "Items seen" "contains" enter the name of an associated item
5. No results are displayed, a message "No item found" appears.

### Your GLPI setup information

GLPI 10.0.5 (/glpi => /var/www/localhost/htdocs/glpi)
Installation mode: TARBALL
Current language:en_GB

Operating system: Linux glpi 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64
PHP 7.4.33 apache2handler (Core, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, ctype, curl, date,
	dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, session, sodium,
	standard, xml, xmlrpc, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Unix) (Apache/2.4.54 (Unix) Server at  **scrubbed** Port 443
)
	Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MariaDB Server
	Server Version: 10.5.17-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP

**Comment by cconard96** [comment]
Associated items for Appliances is not set to be a searchable field. It can only be displayed.
