### ISSUE TITLE
Discovery printer network port

### ISSUE THREAD

**Issue by periodistacg** [glpi-project/glpi#13609]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6-dev

### Bug description

Printer management port id changes each discovery
[printer.xml.zip](https://github.com/glpi-project/glpi/files/10227852/printer.xml.zip)

**Comment by trasher** [comment]
I confirm the ports is deleted and recreated, not updated; but I have no idea if that's expected/normal

**Comment by stonebuzz** [comment]
already seen / fix here -> https://github.com/glpi-project/glpi/pull/13326/files#diff-556766af2a2604805cb30ffb9fbbe579656168e6e408a93b9f7769ba495e546c (i think)

I will make a separate PR

**Comment by trasher** [comment]
Seems to be fixed on my side with #13610

**Comment by periodistacg** [comment]
It is ok if is not connected to a network equipment.
When you have a printer connected to a network equipment and do a discovery, the printer port change to management.
I am seeing that snmp inventory change the id of the printer port also each inventory even if connected.

**Comment by stonebuzz** [comment]
Hi @periodistacg 
can you test with this new commit -> https://github.com/glpi-project/glpi/pull/13610/commits/d3f20b5c64e01c11863b8db68bb7ebc495cf98b9

**Comment by stonebuzz** [comment]
Can you provide inventory file from ```snmp inventory``` step.

Best regards

**Comment by periodistacg** [comment]
I think it is working fine. I will try the complete process

**Comment by periodistacg** [comment]
The inventory changes the id printer port and still connected the printer
A new discovery does not disconnect the printer and still the id printer port (ok)
I put the inventory printer file
[printerinventory.zip](https://github.com/glpi-project/glpi/files/10235710/printerinventory.zip)

**Comment by stonebuzz** [comment]
Greate =) 

last request, I changed my method can you revert ```d3f20b5``` and try https://github.com/glpi-project/glpi/pull/13610/commits/114257c9055098558970247373d2998f3057df73 ?

Sorry for the inconvenience, this new ```commit``` has less impact on the inventory

**Comment by stonebuzz** [comment]
Thank you for your time

**Comment by periodistacg** [comment]
Exactly the same (with 114257c):
The inventory changes the id printer port and keeps connected the printer
A new discovery does not disconnect the printer and keeps the id printer port (ok)

**Comment by stonebuzz** [comment]
great
thank you for your tests =)
