### ISSUE TITLE
Netpoints connectivity

### ISSUE THREAD

**Issue by Almtesh** [glpi-project/glpi#1362]
When I connect two assets through their network interface, I can only put the netpoint to one of them. The second is neither connected automaticly to the netpoint, nor connectable, nor non-connectable to another netpoint.

**Comment by Almtesh** [comment]
I don't get it, is the problem obsolete or irrelevant?
And why?

**Comment by cedric-anne** [comment]
Hi,

We are closing stale issues (i.e. issues that had no answer from a while).
We will soon introduce a cable management feature that seems to matches your needs. See #9042 .

Regards
