### ISSUE TITLE
Not found language

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1363]
Not found Russian language

![setup glpi - google chrome 2016-11-29 13 01 20](https://cloud.githubusercontent.com/assets/17082164/20710056/ab4d662c-b649-11e6-836d-9d56b5626b86.png)

**Comment by Nosolok** [comment]
Russian language is available but string contain latin "P" and cyrillic "усский"

**Comment by AnaelMobilia** [comment]
Should be fixed as #1483 will be merged.

Thanks for the report !
