### ISSUE TITLE
Bug reset ticket because of required fields

### ISSUE THREAD

**Issue by Maelseznec** [glpi-project/glpi#13658]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hello,

We use an additional field on a specified entity. When the user complete the main field, the additional field reset every time. 
If the user don't see, GLPI shows an error message indicating that additional field need to be complete. 
The ticket is completly reset and the user have to restart all actions on the ticket.
Is it normal?

Thanks for your help.

### Steps To reproduce

1- Create an additional field.
2- Complete the fields at the right of a new ticket.
3- Complete the main field of the ticket.
4- Create the ticket.

At the fourth point, the ticket is reset.

### Your GLPI setup information

GLPI 10.0.5 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cedric-anne** [comment]
Fixed by #13292.
