### ISSUE TITLE
10.0.5 Reminders not showing up for targeted profile 

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#13650]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Reminders do not show up for the target profile permission : 

To reproduce :  
1°create reminder
2°add target profile observer
3°check reminder with a user having the profile observer
4°The reminder do not show(it shows if you target the user though)

### Your GLPI setup information

php 7.4.33

**Comment by trasher** [comment]
10.0.3 is outdated. Please try with latest stable and latest nightly build if you reproduce.

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug. Entity restriction criteria is missing for groups and profiles, so only reminders with no entity restriction on their target are shown.

**Comment by cedric-anne** [comment]
@joomlafun @KeetKhat

Could you test #13650?

**Comment by KeetKhat** [comment]
With this patch it works as intended. I can see a reminer with an entity restriction.
