### ISSUE TITLE
Location ID instead of location name

### ISSUE THREAD

**Issue by DeadPo01** [glpi-project/glpi#13659]
### Bug reporting acknowledgment

Yes, I read it

### Professional support

Yes, I know

### Describe the bug

Created test rule to assign entity and location to computer with GLPI-agent. But inventory proccess is creating location with name from ID number of location from the rule and assigning it (ID as a location name) to computer instead of location name from rule.

### To reproduce

1. Create "Rules for assigning an item to an entity" rule with location assign to  computer
2. Run GLPI-agent with inventory process for this rule
3. Check "Location name" of inventored computer in "Computers" tab in assets.

### Expected behavior

Expected location name from rule.

### Operating system

Windows

### GLPI Agent version

1.4

### GLPI version

Other (See additional context below)

### GLPIInventory plugin or FusionInventory for GLPI plugin version

10.0.1+1.0

### Additional context

GLPI 10.0.5 + Agent 1.4 installed by vbs script.
FusinonInvenory plugin has no that issue.

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi-inventory-plugin/issues/276

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/13667
