### ISSUE TITLE
Netdiscovery without snmp

### ISSUE THREAD

**Issue by periodistacg** [glpi-project/glpi#13660]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6-dev

### Bug description

I am trying to discovery a network equipment witout snmp.
The rule "NetworkEquipment import denied" is not active (I tryed both states)
Importing xml file: result a "blank" page
With task: Found 1 Processed: 0 Created 0
Injecting: ERROR: Unexpected empty server response

[discovery_networkequipment5.zip](https://github.com/glpi-project/glpi/files/10276540/discovery_networkequipment5.zip)

**Comment by trasher** [comment]
"blank page" means PHP error. It's requested to provide related logs when filling an issue.

Seems an issue with recent changed to handle `Unmanaged` items (for what I can see on my local intsance).

**Comment by trasher** [comment]
Or maybe it's linked to #13326; no idea.

**Comment by periodistacg** [comment]
[php-errors.log](https://github.com/glpi-project/glpi/files/10276852/php-errors.log)

**Comment by trasher** [comment]
This is indeed related to #13326. Inventory format lib has been updated, but work has not been finished GLPI side. 10.0.6 is still under development.
