### ISSUE TITLE
Upgrade from 9.4.6 to 10.0.5 not working - The schema differs for the "glpi_notimportedemails" table.

### ISSUE THREAD

**Issue by s0p4LiN** [glpi-project/glpi#13665]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.4.6

### Bug description

Upgrade from 9.4.6 to GLPI 10.0.5 does not work.

OS: Centos 7 updated
PHP 7.4.33
mysql  Ver 15.1 Distrib 10.3.37-MariaDB

Everything is ready to be updated but the check before updated tells me that a table has a collate.
```
php bin/console db:check
Le schéma diffère pour la table "glpi_notimportedemails".
--- Schéma de base de données attendu
+++ Schéma de base de données actuel
@@ @@
   PRIMARY KEY (`id`),
   KEY `mailcollectors_id` (`mailcollectors_id`),
   KEY `users_id` (`users_id`)
-) DEFAULT CHARSET=latin1
+) COLLATE=latin1_swedish_ci DEFAULT CHARSET=latin1
```

I search everywhere on Google, I can not find information on how to remove the collation for the database schema.

How to fix it ? We can not upgrade.
Thank you.

### Steps To reproduce

php bin/console db:check

**Comment by cedric-anne** [comment]
Hi,

You can ignore this specific differences.
