### ISSUE TITLE
error in php-error.log

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1366]
Hello

I have these errors today

2016-11-29 16:37:17 [854@UNGSRVGVA118]
  From getEntitiesRestrictRequest() in C:\inetpub\wwwroot\glpi\inc\db.function.php line 1686
  getEntitiesRestrictRequest called without any `table` specified! 
2016-11-29 16:37:17 [854@UNGSRVGVA118]
  From getEntitiesRestrictRequest() in C:\inetpub\wwwroot\glpi\inc\db.function.php line 1686 (0.055", 2.96Mio)
  getEntitiesRestrictRequest called without any `table` specified! 
2016-11-29 16:37:32 [854@UNGSRVGVA118]
  From getEntitiesRestrictRequest() in C:\inetpub\wwwroot\glpi\inc\db.function.php line 1686
  getEntitiesRestrictRequest called without any `table` specified! 
2016-11-29 16:37:32 [854@UNGSRVGVA118]
  From getEntitiesRestrictRequest() in C:\inetpub\wwwroot\glpi\inc\db.function.php line 1686 (0.054", 2.96Mio)
  getEntitiesRestrictRequest called without any `table` specified! 
2016-11-29 16:41:18 [854@UNGSRVGVA118]

**Comment by trasher** [comment]
This is just a warning and will not break anything. It is most probably raised from a plugin; I did not find any call without a table name in GLPi's core.

**Comment by satyan01** [comment]
ok thx

**Comment by trasher** [comment]
Anyways, it would be a good idea to find which plugin raise this warning and open a ticket to fix that :)
