### ISSUE TITLE
The space is replaced by "n" in the description of the ticket

### ISSUE THREAD

**Issue by TOH2F** [glpi-project/glpi#13675]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 9.5.11

### Bug description

![image](https://user-images.githubusercontent.com/60504041/209566513-35299189-e3fd-4863-8002-56f400a1c9ac.png)

### Steps To reproduce

Create ticket, and change description

**Comment by cconard96** [comment]
This was already reported and fixed by commit https://github.com/glpi-project/glpi/commit/ade4d2e076f5b118aebce9095161dffc73376c7e
