### ISSUE TITLE
ticket templates not present in "Dropdown>Assistance"

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#13674]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hi,

I know that there is a ticket template shortcut on the Assistance view, however it could be listed in "Intitulés>Assistance" as some people new to GLPI may not be able to find it.

Kind regards

### Page URL

https://support.okplace.net/front/dropdown.php

**Comment by cedric-anne** [comment]
Hi,

Except for items that do not have their own page (i.e Followups, Solutions, ...), templates are not manageable from the `Dropdown` page. If we add a link for Ticket templates, then people will start to ask for Computer templates, Project template and so on. If we start to add them, people will no be able to distinguish real dropdown and templates.

IMHO, no template should be located in this `Dropdown` page, but this is another subject.
