### ISSUE TITLE
Some ticket images aren't showing on chrome and edge

### ISSUE THREAD

**Issue by trisosamu** [glpi-project/glpi#13679]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description
![image](https://user-images.githubusercontent.com/78987040/209823454-6edbb7b3-eb54-482a-a6e8-fc201f08af44.png)

Firefox on the left. Chrome on the right. Same ticket

**Comment by cedric-anne** [comment]
Hi,

Could you check if #13402 fixes this issue ?

**Comment by usrqmor** [comment]
Hi @cedric-anne,

I have the same issue.
I tried to find the file html.class.php but i don't find it in my glpi/inc folder.

I look at the 10.0.5 release and I dont see this file too.

**Comment by cedric-anne** [comment]
@usrqmor 

See "Files changed" tab sor changes to apply on 10.0 branch.

**Comment by usrqmor** [comment]
@cedric-anne 
Thank you for the information, I didn't know. I apply the modification.
But, my problem may not be the same as trisosamu.

The bug with images is present without using mailcollector.  It happens in post only or hotliner too. 
I tried to reproduce the bug without success. 
I checked apache log and php log but i didn't find any error.
There is no link with the documents in glpi. It's like the copy paste image wasn't uploaded.

**Comment by trasher** [comment]
No feedback from original requester, closing.

**Comment by cedric-anne** [comment]
@usrqmor

You should open another issue and give all requested information, so we could investigate.

**Comment by usrqmor** [comment]
Hi @cedric-anne, 

Thanks for the reply, I opened another one.

**Comment by trisosamu** [comment]
> Hi,
> 
> Could you check if #13402 fixes this issue ?

sorry, I had some problem and I don't see your reply.

#13402 not work

**Comment by cedric-anne** [comment]
Maybe fixed by #13852.

Anyway, please upgrade to GLPI 10.0.6 and, if you are able to reproduce the issue, please give steps to reproduce.
