### ISSUE TITLE
Milestones should not have end dates

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#13683]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

One can set scheduled duration date and real schedule date on project milestones, but milestones does not have duration.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.3 (/assistance => C:\xampp\htdocs\assistance)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT SRV007D 10.0 build 19044 (Windows 10) AMD64
PHP 7.4.29 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="480" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) mod_authnz_sspi/0.1.1 OpenSSL/1.1.1n PHP/7.4.29 (Apache/2.4.53 (Win64) mod_authnz_sspi/0.1.1
	OpenSSL/1.1.1n PHP/7.4.29 Server at parc Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: xxx
	Host info: localhost via TCP/IP
	
PHP version (7.4.29) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
The log file has been created successfully.
Write access to C:\xampp\htdocs\assistance/files/_cache has been validated.
Write access to C:\xampp\htdocs\assistance/config has been validated.
Write access to C:\xampp\htdocs\assistance/files/_cron has been validated.
Write access to C:\xampp\htdocs\assistance/files has been validated.
Write access to C:\xampp\htdocs\assistance/files/_dumps has been validated.
Write access to C:\xampp\htdocs\assistance/files/_graphs has been validated.
Write access to C:\xampp\htdocs\assistance/files/_lock has been validated.
Write access to C:\xampp\htdocs\assistance/files/_pictures has been validated.
Write access to C:\xampp\htdocs\assistance/files/_plugins has been validated.
Write access to C:\xampp\htdocs\assistance/files/_rss has been validated.
Write access to C:\xampp\htdocs\assistance/files/_sessions has been validated.
Write access to C:\xampp\htdocs\assistance/files/_tmp has been validated.
Write access to C:\xampp\htdocs\assistance/files/_uploads has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/assistance/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\xampp\htdocs\assistance/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: C:\xampp\htdocs\assistance
GLPI_CONFIG_DIR: C:\xampp\htdocs\assistance/config
GLPI_VAR_DIR: C:\xampp\htdocs\assistance/files
GLPI_MARKETPLACE_DIR: C:\xampp\htdocs\assistance/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 

Notice:  Array to string conversion in C:\xampp\htdocs\assistance\src\Config.php on line 2073

GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: C:\xampp\htdocs\assistance/files
GLPI_CACHE_DIR: C:\xampp\htdocs\assistance/files/_cache
GLPI_CRON_DIR: C:\xampp\htdocs\assistance/files/_cron
GLPI_DUMP_DIR: C:\xampp\htdocs\assistance/files/_dumps
GLPI_GRAPH_DIR: C:\xampp\htdocs\assistance/files/_graphs
GLPI_LOCAL_I18N_DIR: C:\xampp\htdocs\assistance/files/_locales
GLPI_LOCK_DIR: C:\xampp\htdocs\assistance/files/_lock
GLPI_LOG_DIR: C:\xampp\htdocs\assistance/files/_log
GLPI_PICTURE_DIR: C:\xampp\htdocs\assistance/files/_pictures
GLPI_PLUGIN_DOC_DIR: C:\xampp\htdocs\assistance/files/_plugins
GLPI_RSS_DIR: C:\xampp\htdocs\assistance/files/_rss
GLPI_SESSION_DIR: C:\xampp\htdocs\assistance/files/_sessions
GLPI_TMP_DIR: C:\xampp\htdocs\assistance/files/_tmp
GLPI_UPLOAD_DIR: C:\xampp\htdocs\assistance/files/_uploads
GLPI_INVENTORY_DIR: C:\xampp\htdocs\assistance/files/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: C:\xampp\htdocs\assistance/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (C:\xampp\htdocs\assistance\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\xampp\htdocs\assistance\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\assistance\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.5.0 in (C:\xampp\htdocs\assistance\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\assistance\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\assistance\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\assistance\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\assistance\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\assistance\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\assistance\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\assistance\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\assistance\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\assistance\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\assistance\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\assistance\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\assistance\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\assistance\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\assistance\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\assistance\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\assistance\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\assistance\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\assistance\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\xampp\htdocs\assistance\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\xampp\htdocs\assistance\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\assistance\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\assistance\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\assistance\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\assistance\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\assistance\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\assistance\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\assistance\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\assistance\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\assistance\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\assistance\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\assistance\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\assistance\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\assistance\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\assistance\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\assistance\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\assistance\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (C:\xampp\htdocs\assistance\vendor\symfony\polyfill-php80)
symfony/polyfill-php81 in (C:\xampp\htdocs\assistance\vendor\symfony\polyfill-php81)
symfony/polyfill-php82 in (C:\xampp\htdocs\assistance\vendor\symfony\polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'xxxx', Port: '389', BaseDN: 'OU=xxxx,DC=xxxxDC=dmn', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'xxxx', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (anonymous@xxxx.mail.protection.outlook.com)

</details><details><summary>Plugins list</summary><pre> 
	fusioninventory      Name: FusionInventory                Version: 10.0.3+1.0 State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.1      State: Enabled                                 
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

![2022-12-29_15h41_43](https://user-images.githubusercontent.com/15892696/209980014-9081f3a5-8650-471f-befa-2984dd2cfc93.png)
![2022-12-29_15h34_47](https://user-images.githubusercontent.com/15892696/209980100-dd87a640-5611-4f5e-97ef-9536effcbba9.png)

**Comment by cconard96** [comment]
Please write in English (automatic translations are OK).

Having issues reported all in English helps ensure that searching for existing/already reported issues is easier.
Also, the community and development team is international so having a common language helps us too.

Veuillez écrire en anglais (les traductions automatiques sont acceptables).

Le fait que les problèmes signalés soient tous en anglais permet de faciliter la recherche de problèmes existants ou déjà signalés.
De plus, la communauté et l'équipe de développement étant internationales, le fait d'avoir une langue commune nous aide également.

**Comment by cconard96** [comment]
Also, please test with 10.0.5 in case this is a bug that has already been fixed.

**Comment by sebfun** [comment]
Hi
I've just tested it on 10.05 and it seems to be the same issue

**Comment by cedric-anne** [comment]
Hi,

This is the expected behaviour. Your task is flagged as milestone ("étape" in french). GLPI considers that this kind of task has no duration.
See https://github.com/glpi-project/glpi/blob/894bade1c0d6028ca6faade54dd4872b218f334a/src/ProjectTask.php#L411-L419

**Comment by sebfun** [comment]
ok so why we 're able to write a scheluled duration date and a real schedule date  ? It's a non sense ...
