### ISSUE TITLE
Tickets have only html code! 

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#13733]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Tickets have only html code! 

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.5 ( => /var/www/assistance-dev3)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux lxc-glpi-dev 5.4.60-1-pve #1 SMP PVE 5.4.60-1 (Mon, 31 Aug 2020 10:36:22 +0200) x86_64
PHP 7.4.30 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="150M" safe_mode="" session.save_handler="files"
	upload_max_filesize="150M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.39
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: assistance@140.77.162.14:3310/glpi-ensl-new
	Host info: 140.77.162.14 via TCP/IP
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_cache has been validated.
Write access to /var/www/config-PROD_NE_PAS_EFFACER has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_cron has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_dumps has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_graphs has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_lock has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_pictures has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_plugins has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_rss has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_sessions has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_tmp has been validated.
Write access to /var/www/files-PROD_NE_PAS_EFFACER/_uploads has been validated.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/assistance-dev3/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/assistance-dev3"
GLPI_CONFIG_DIR: "/var/www/config-PROD_NE_PAS_EFFACER"
GLPI_VAR_DIR: "/var/www/files-PROD_NE_PAS_EFFACER"
GLPI_MARKETPLACE_DIR: "/var/www/assistance-dev3/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/files-PROD_NE_PAS_EFFACER"
GLPI_CACHE_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_cache"
GLPI_CRON_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_cron"
GLPI_DUMP_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_dumps"
GLPI_GRAPH_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_locales"
GLPI_LOCK_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_lock"
GLPI_LOG_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_log"
GLPI_PICTURE_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_plugins"
GLPI_RSS_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_rss"
GLPI_SESSION_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_sessions"
GLPI_TMP_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_tmp"
GLPI_UPLOAD_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_uploads"
GLPI_INVENTORY_DIR: "/var/www/files-PROD_NE_PAS_EFFACER/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/assistance-dev3/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/assistance-dev3/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/assistance-dev3/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/assistance-dev3/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/assistance-dev3/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/assistance-dev3/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/assistance-dev3/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/assistance-dev3/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/assistance-dev3/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/assistance-dev3/vendor/sabre/http/lib)
sabre/uri in (/var/www/assistance-dev3/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/assistance-dev3/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/assistance-dev3/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/assistance-dev3/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/assistance-dev3/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/assistance-dev3/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/assistance-dev3/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/assistance-dev3/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/assistance-dev3/vendor/symfony/console)
scssphp/scssphp in (/var/www/assistance-dev3/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/assistance-dev3/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/assistance-dev3/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/assistance-dev3/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/assistance-dev3/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/assistance-dev3/vendor/ramsey/uuid/src)
psr/log in (/var/www/assistance-dev3/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/assistance-dev3/vendor/psr/simple-cache/src)
psr/cache in (/var/www/assistance-dev3/vendor/psr/cache/src)
league/csv in (/var/www/assistance-dev3/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/assistance-dev3/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/assistance-dev3/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/assistance-dev3/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/assistance-dev3/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/assistance-dev3/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/assistance-dev3/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/assistance-dev3/vendor/symfony/cache)
html2text/html2text in (/var/www/assistance-dev3/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/assistance-dev3/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/assistance-dev3/vendor/symfony/dom-crawler)
twig/twig in (/var/www/assistance-dev3/vendor/twig/twig/src)
twig/string-extra in (/var/www/assistance-dev3/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/assistance-dev3/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/assistance-dev3/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/assistance-dev3/vendor/symfony/polyfill-php82)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap.ens-lyon.fr', Port: '389', BaseDN: 'dc=ens-lyon,dc=fr', Connection filter:
		'(|(objectclass=enslPerson)(objectclass=groupOfNames))', RootDN: none, Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@localhost)

</details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.20.0     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.3     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.14.1     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.6      State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Manual
	controlequalite      Name: Plugin Controle Qualite        Version: 1.0        State: Enabled                                 
		Install Method: Manual
	ens                  Name: Plugin ENS                     Version: 1.1        State: Enabled                                 
		Install Method: Manual
	transfertticket      Name: Plugin Transfert Ticket        Version: 1.0        State: Enabled                                 
		Install Method: Manual
	wol                  Name: Plugin Wake On Lan             Version: 1.0        State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
I am not able to reproduce.

**Comment by trasher** [comment]
Please provide a way to reproduce.

**Comment by falco2001** [comment]
![image](https://user-images.githubusercontent.com/31952346/210561550-1c20b0bb-a09f-4336-acfb-1060bc5e5027.png)

**Comment by trasher** [comment]
Open an issue on plugin repository, we only handle GLPI core issues here.
