### ISSUE TITLE
Search engine: filed is_notify of a group

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1373]
Bug still present in 0.90.5, 9.1.x and master

Data correct in database.
Field is_notify display from list => not OK (even empty)
Search done on this field         => not OK (request this Is Yes or Is No return No item found)

**Comment by trasher** [comment]
Seems like it has been fixed in current 9.1/bugfixes.

**Comment by trasher** [comment]
I added a unit test for this case in PR #1618
