### ISSUE TITLE
The criterion "all" cannot be used with this list of objects, the SQL query fails (too many tables). Please use the "Viewed items" criterion instead.

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi#13748]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI Version 9.5.7

### Bug description

Happy New Year and greetings to all, I have a small problem with GLPI

![image](https://user-images.githubusercontent.com/113598277/210735728-88eab345-1225-4f87-a4ad-53aeb2786d7e.png)

I just wanted to see all the info available from a device
And then it tells me that there is too much info to display but I can't change what I want to see as info, anyone know how I can go back?

I'm missing this icon to indicate what I want to see displayed
![image](https://user-images.githubusercontent.com/113598277/210735795-68c0627d-2c6e-4f07-a893-3713722f8675.png)
And I can't manage it from my account because I have modified the global view and not the personal view
![image](https://user-images.githubusercontent.com/113598277/210735869-3570d6c7-889b-449f-bebc-f824d40e5033.png)
So does anyone know how I can go back?

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/113598277/210735954-defe59d7-0700-4441-9fd1-75db240fbf8b.png)
![image](https://user-images.githubusercontent.com/113598277/210736012-51ab9fe9-9db9-4155-9ea5-9360bb481066.png)
![image](https://user-images.githubusercontent.com/113598277/210736041-8ee58382-e28d-42b2-93e4-5cdfcec7e749.png)
![image](https://user-images.githubusercontent.com/113598277/210736065-245dd406-6cc3-44b8-8536-6a158cbd8ab6.png)

**Comment by cedric-anne** [comment]
Hi,

You can probably unlock the situation by calling the faulty page using `?reset=reset` in URL parameters, e.g. http://domain.tld/front/computer.php?reset=reset

**Comment by HugzWaaa** [comment]
> This issue has been closed as we only track bugs here.
> 
> You can get community support on [forums](https://forum.glpi-project.org/) or you can consider [taking a subscription](https://glpi-project.org/subscriptions/) to get professional support. You can also [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.

offer you an "all" criterion in the user interface and when you select it nothing is displayed and no way to go back except by modifying the DB, but it's not a bug, why not... 

Thanks for your answer cedric-anne :) unfortunately it doesn't work

**Comment by HugzWaaa** [comment]
Thanks for tour reply ☺️

Le jeu. 5 janv. 2023 à 09:37, Cédric Anne ***@***.***> a
écrit :

**Comment by cedric-anne** [comment]
The only solution i see is so to remove some entries in `glpi_displaypreferences` table that corresponds to the itemtype that you are trying to show.

Anyway, we do not anymore support GLPI 9.5, so it will not be fixed, unless problem persist on GLPI 10.0.
