### ISSUE TITLE
Template bugging for pdu with "management"

### ISSUE THREAD

**Issue by blackxthink** [glpi-project/glpi#13746]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

I made a template to create PDUs as a batch.
The issue is with the "management" tab, it does not create the item with the management informations that were added in the template. (it's not activated either).

**The template "management" tab - creating the template:**
![image](https://user-images.githubusercontent.com/48074916/210630644-5130f102-3c5c-4c0c-a8cc-5e9edca94a49.png)

**The management tab when creating an item - visual is broken:**
![image](https://user-images.githubusercontent.com/48074916/210630959-9c794a7b-5807-43ab-9a8b-2e1752739cca.png)

**An item created using the template:**
![image](https://user-images.githubusercontent.com/48074916/210630784-b92b72a3-fb6b-4745-b6de-b277bd7a1310.png)

### Steps To reproduce

- Create a template to add PDUs as a batch
- Create an item using that template and click on management before saving
- Save the item
- Access the item
- Access the management tab of this item
- it should be deactivated.
- Everything seems to work from the template except the management part

### Your GLPI setup information

GLPI 10.0.5 ( => /home/glpi/public_html)
Installation mode: TARBALL
Current language:en_GB

**Comment by cconard96** [comment]
Fixed by #13781
