### ISSUE TITLE
Le critère "tous" ne peut être utilisé avec cette liste d'objets, la requête SQL échoue (trop de tables). Veuillez utiliser le critère "Éléments visualisés" à la place.

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi#13745]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

GLPI Version 9.5.7

### Bug description

Bonne année et salut à tous, j'ai un petit soucis avec GLPI

![image](https://user-images.githubusercontent.com/113598277/210603469-2002c4bc-f485-4b45-a8e0-70faae72fa98.png)

j'ai juste voulu voir toutes les infos disponible d'un device
Et du coup il me dit qu'il y a trop d'infos à afficher mais je ne peut pas remodifier ce que je veux voir comme info, quelqu'un sais comment je peut retourner en arrière ? 

il me manque cette icône pour indiquer ce que je veux voir afficher
![image](https://user-images.githubusercontent.com/113598277/210603648-fe9dbf76-74a3-4c54-ac8a-104e3d9b4722.png)

Et je ne peut pas gérer ça depuis mon compte car j'ai modifier la vue globale et non la vue personnelle
![image](https://user-images.githubusercontent.com/113598277/210603826-e6874678-dcb0-425c-8400-747c39dc8497.png)
Du coup est-ce que quelqu'un sais comment je peut retourner en arrière ? 

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/113598277/210604543-66e27de9-63dd-4429-a974-ccc4b9f66f05.png)

![image](https://user-images.githubusercontent.com/113598277/210605024-0408cb65-b1a0-4225-b932-8905a23a2a82.png)

![image](https://user-images.githubusercontent.com/113598277/210605210-b9927f19-29dc-468f-bab2-8d89c6127a96.png)

![image](https://user-images.githubusercontent.com/113598277/210605338-c00646b7-42db-403e-8b9e-8d091790b078.png)

**Comment by trasher** [comment]
It is requested to write in english only.

**Comment by HugzWaaa** [comment]
It's do :)

Le jeu. 5 janv. 2023 à 07:23, Johan Cwiklinski ***@***.***> a
écrit :

**Comment by Rodolphe231** [comment]
HI, 
I have the same case (in park>computers), is there a solution to unblock this view?
Thanks in advance

**Comment by cedric-anne** [comment]
@Rodolphe231 

If you think there is a bug and if it is reproducible in GLPI 10.0.7, please open a new issue.

**Comment by Rodolphe231** [comment]
Thank you for your quick response. 
We will do an upgrade on our test server and see if the same operation produces the same effect. 
If the problem is reproducible in version 10.0.7, we will open a new issue
Can you please give me a download link for this version knowing that we are currently in 
GLPI 9.5.5 Copyright (C) 2015-2021 Teclib' and contributors
FusionInventory 9.5.0+1.0 - Copyleft © 2010-2019 by FusionInventory Team

**Comment by cedric-anne** [comment]
https://github.com/glpi-project/glpi/releases/download/10.0.7/glpi-10.0.7.tgz
