### ISSUE TITLE
Request Support for PHP 8.2.1

### ISSUE THREAD

**Issue by thefathacker** [glpi-project/glpi#13758]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Unable to Launch GLPI as PHP Version Check does not support sub version of 8.2 only 8.2.0

Worked around by changing index.php to check for 8.2.1 and below

### Relevant log output

```shell
output from /index.php
PHP 7.4.0 - 8.2.0 (exclusive) required
```

### Page URL

/index.php

### Steps To reproduce

Attempt to open [svr]/index.php

### Your GLPI setup information

CentOS 9 VM with Remi PHP 8.2 and Apache

**Comment by cedric-anne** [comment]
Hi,

It was a mistake in version declaration. GLPI is supposed to be compatible with PHP 8.2.
