### ISSUE TITLE
Solution template variables

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#13769]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.5

### Bug description

On template solution, if add a variable **{% for user in ticket.requesters.users %}** get the folling error:

![solution_template_variable_error](https://user-images.githubusercontent.com/6449156/211635928-eeae0cc3-e1d2-400d-bb68-bed834fe8f55.png)

### Steps To reproduce

1. Create solution template
2. Add variable {% for user in ticket.requesters.users %}
3. Save template
4. Error!

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.5 ( => /var/www/XXX/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux srvsd02-pcr 4.19.0-21-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64
PHP 8.1.9 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at XXXX.XXX.LOCAL Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76
Server Software: Debian 10
	Server Version: 10.3.34-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.9) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.34) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
...

**Comment by cedric-anne** [comment]
Hi,

`{% for user in ticket.requesters.users %}` is a tag than can be used to create a loop and is meant to be closed by `{% endfor %}`, for instance `{% for user in ticket.requesters.users %} {{ user.fullname }} {% endfor %}`.
