### ISSUE TITLE
API REST doesn't work well

### ISSUE THREAD

**Issue by HugzWaaa** [glpi-project/glpi#13764]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.7

### Bug description

when I go to the "computer" tab, I see that I have 837 computer
![image](https://user-images.githubusercontent.com/113598277/211289822-75038ca4-dfcb-4e29-a225-9616cc73360e.png)
However when I do a GET with the API, from this same page, the totalcount is equal to 833, I don't understand why
![image](https://user-images.githubusercontent.com/113598277/211290099-16d3aabd-b619-4f42-9847-afc772c1309f.png)

**Comment by trasher** [comment]
9.5 is nolonger maintained, try with latest stable

**Comment by HugzWaaa** [comment]
> 9.5 is nolonger maintained, try with latest stable

Great support !!!
