### ISSUE TITLE
Opening ticket with mandatory description

### ISSUE THREAD

**Issue by jussara-ti** [glpi-project/glpi#13773]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hello,

I found a bug when opening tickets:

When opening a ticket that has the description field as mandatory and predefined, the ticket is opened even if I do not edit this description field

In previous versions, the ticket was not opened until some edit was made in the description field

**Comment by cedric-anne** [comment]
Hi,

I made some tests on both GLPI 9.5.12 and GLPI 10.0.6, and here are the results:
 - if ticket description is both a predefined and a mandatory field, then you have to edit it to be able to create the ticket;
 - if ticket description is a predefined field but is NOT a mandatory field, then you can create the ticket without editing it.

Is your field marked as mandatory ?

**Comment by jussara-ti** [comment]
Thanks for the feedback. Yes, predefined and mandatory.

![Captura de tela 2023-02-07 171733](https://user-images.githubusercontent.com/60328341/217355941-59d8a321-09f7-4517-a325-0927858cb1ca.png)

This ticket opened normally without editing the title and description fields

I'm going to do more tests to see if it can't be a conflict with some plugin

**Comment by cedric-anne** [comment]
Maybe you can try to upgrade to GLPI 10.0.6 to see if problem persists.

**Comment by jussara-ti** [comment]
Hi,

I upgraded to version 10.0.6 but this behavior still persists.

I also did the test by disabling the Behaviors plugin (which I suspected might have some conflict) but the ticket was opened normally, even without any edits to the title and description

**Comment by cedric-anne** [comment]
Can you post here content of the `glpi_tickettemplatepredefinedfields` database table?

**Comment by jussara-ti** [comment]
Sure!

![predefined](https://user-images.githubusercontent.com/60328341/217831877-bb1a4b2f-79d3-4fa2-b142-2208e2f4f5c0.png)

![mandatory](https://user-images.githubusercontent.com/60328341/217831909-342e13c0-fcc1-4b29-8980-b7ed641145dd.png)

**Comment by cedric-anne** [comment]
Could you export it as a SQL file?

**Comment by jussara-ti** [comment]
Of course.
Are these files?
[sql.zip](https://github.com/glpi-project/glpi/files/10698624/sql.zip)

**Comment by cedric-anne** [comment]
Indeed, it may help me to investigate.
