### ISSUE TITLE
Form to add an external event is not displayed

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#13779]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v10.0.3

### Bug description

When the users want to create an external event, there is no submit button to save the event : 

![image](https://user-images.githubusercontent.com/2470104/211861249-3ccc177a-79c7-4d05-87ca-2543f04b820f.png)

Moreover, if I want to add an external event template (gabarit d'évènement externe), there is no form in the ./front/planningexternaleventtemplate.form.php page : the `div#tab-PlanningExternalEventTemplate_main-1383496321` is empty : 
![image](https://user-images.githubusercontent.com/2470104/211861492-c4f6abfa-c426-4164-8cf2-ec146b80ee18.png)

![image](https://user-images.githubusercontent.com/2470104/211861699-798590f3-34cb-420d-81ff-0bc61f2af9bb.png)

I cheked the roles and their abilities. Technicians, Admins and SuperAdmins can add, edit and delete external events.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.3 ( => /var/www/glpi10.0.3)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux hd 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at hd.univ-lehavre.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Server Software: Debian 11
	Server Version: 10.5.18-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: helpdesk_glpi@localhost/helpdesk_glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.18) is supported.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi10.0.3/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: /var/www/glpi10.0.3
GLPI_CONFIG_DIR: /etc/glpi/
GLPI_VAR_DIR: /var/lib/glpi
GLPI_LOG_DIR: /var/log/glpi
GLPI_MARKETPLACE_DIR: /var/www/glpi10.0.3/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_SERVERSIDE_URL_ALLOWLIST: Array
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_CENTRAL_WARNINGS: 1
GLPI_DOC_DIR: /var/lib/glpi
GLPI_CACHE_DIR: /var/lib/glpi/_cache
GLPI_CRON_DIR: /var/lib/glpi/_cron
GLPI_DUMP_DIR: /var/lib/glpi/_dumps
GLPI_GRAPH_DIR: /var/lib/glpi/_graphs
GLPI_LOCAL_I18N_DIR: /var/lib/glpi/_locales
GLPI_LOCK_DIR: /var/lib/glpi/_lock
GLPI_PICTURE_DIR: /var/lib/glpi/_pictures
GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/_plugins
GLPI_RSS_DIR: /var/lib/glpi/_rss
GLPI_SESSION_DIR: /var/lib/glpi/_sessions
GLPI_TMP_DIR: /var/lib/glpi/_tmp
GLPI_UPLOAD_DIR: /var/lib/glpi/_uploads
GLPI_INVENTORY_DIR: /var/lib/glpi/_inventories
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/glpi10.0.3/locales
GLPI_VERSION: 10.0.3
GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_MIN_PHP: 7.4.0
GLPI_MAX_PHP: 8.3.0
GLPI_YEAR: 2022

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi10.0.3/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi10.0.3/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi10.0.3/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi10.0.3/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi10.0.3/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi10.0.3/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi10.0.3/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi10.0.3/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi10.0.3/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi10.0.3/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi10.0.3/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi10.0.3/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi10.0.3/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi10.0.3/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi10.0.3/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi10.0.3/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi10.0.3/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi10.0.3/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi10.0.3/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi10.0.3/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi10.0.3/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi10.0.3/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi10.0.3/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi10.0.3/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi10.0.3/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi10.0.3/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi10.0.3/vendor/psr/cache/src)
league/csv in (/var/www/glpi10.0.3/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi10.0.3/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi10.0.3/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi10.0.3/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi10.0.3/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi10.0.3/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi10.0.3/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi10.0.3/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi10.0.3/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi10.0.3/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi10.0.3/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi10.0.3/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi10.0.3/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi10.0.3/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi10.0.3/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/glpi10.0.3/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap.univ-lehavre.fr', Port: '389', BaseDN: 'dc=univ-lehavre,dc=fr', Connection filter:
		'(|(eduPersonPrimaryAffiliation=affiliate)(eduPersonPrimaryAffiliation=employee)(eduPersonPrimaryAffiliation=faculty))', RootDN:
		'cn=ldapbindusr-glpi-helpdesk,ou=DSA,dc=univ-lehavre,dc=fr', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp.univ-lehavre.fr)

</details><details><summary>Plugins list</summary><pre> 
	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.3     State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
10.0.3 is outdated, please try with latest stable and nightly. Feel free to reopen if you can reproduce on nigthly.
