### ISSUE TITLE
Firmware version did not remove the previous one when updating the equipment's Firmware [BUG] GLPI 9.5.11

### ISSUE THREAD

**Issue by eriqueSDB** [glpi-project/glpi#13780]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

The Firmware Version did not remove the previous one when updating the Firmware of the equipment, it remained at 2 after the update

![image](https://user-images.githubusercontent.com/102301295/211894920-8d322615-6dc4-405c-be54-bc44c82229fd.png)

The device itself is a Mikrotik device on network devices, being inventoried via glpi-agent and using the fusioninventory plugin.

In the inventory report, the firmware only shows the new one, but in glpi it didn't remove the old one, is it really a bug?

**Comment by trasher** [comment]
9.5 will only receive seciruty fixes if any. Please try woth latest stable, and feel free to reopen if you reproduce.

**Comment by cedric-anne** [comment]
Also, on GLPI 9.5.x, your issue is anyway related to `fusioninventory` plugin. Feel free to open an issue on plugin repository.
