### ISSUE TITLE
Computers cant change entity through an update rule in 10.0.5

### ISSUE THREAD

**Issue by Lifthraser** [glpi-project/glpi#13787]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

We have several entities with each their own tags, representing different places.
When a computer change location, we reclone it and deploy a new glpi agent with the right entity tag.
The computer is already in our base, in the wrong entity tag until now but has an inventory number.
When the computer boot, our update rule kicks in and the computer should move from old entity to new entity.
It does not, the name of the computer and the other informations are updated correctly, the tag is the new one but not the entity isnt changed.

**Comment by cedric-anne** [comment]
Hi,

Could you please check if issue persist in GLPI 10.0.6 ?

**Comment by AndiMb** [comment]
This feature would be nice, but I thought there is no automatic process to transfer an item to a new entity? Am I wrong? (see https://glpi-user-documentation.readthedocs.io/fr/master/modules/administration/rules/inventorytools.html in the first avertissement box)

**Comment by trasher** [comment]
No feedback, I close

**Comment by Lifthraser** [comment]
We updated and are using GLPI 10.0.10
glpi agent is version 1.6.1
Problem persist.

**Comment by stonebuzz** [comment]
Hi @Lifthraser 

Can you check that the transfer is authorised (```complete```) in the entity of origin and destination?

![image](https://github.com/glpi-project/glpi/assets/7335054/dc796ad5-fd00-4c28-a6d6-4c99636be589)

**Comment by Lifthraser** [comment]
It seems to work perfectly.
Thanks, in the schools in Gard departement of france, the inventory will be much better now

**Comment by cedric-anne** [comment]
@Lifthraser 

Could you open a new issue with all requested details ?
