### ISSUE TITLE
MailCollector doesn't work on exchange 2016 with IMAP

### ISSUE THREAD

**Issue by MathysLioson** [glpi-project/glpi#13796]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hi,

I try to add an mail collector on GLPI but i have an error when i try to retrieve mail from the collector.
The error :
_An error occurred while connecting to the collector.
cannot login, user or password wrong_

php-errors.log : 
```
[2023-01-13 12:37:20] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot login, user or password wrong in C:\wamp64\www\glpi\vendor\laminas\laminas-mail\src\Storage\Imap.php at line 225
  Backtrace :
  src\Toolbox.php:2196                               Laminas\Mail\Storage\Imap->__construct()
  src\MailCollector.php:1375                         Toolbox::getMailServerStorageInstance()
  src\MailCollector.php:698                          MailCollector->connect()
  front\mailcollector.form.php:103                   MailCollector->collect()
```
  

I'm sure the password is correct, I checked it by logging into Outlook and Thunderbird.

I'm using Echange 2016 server, IMAP is activated on the user and on the server.

- I've test the IMAP on Thunderbird and it worked.
- I have a self-signed certificate on GLPI and an a validate Certificate on exchange.
- My parameter are : 
![image](https://user-images.githubusercontent.com/77407012/212313520-0a0ad087-a705-40ab-aa49-1ae3d39984f6.png)
![image](https://user-images.githubusercontent.com/77407012/212315736-95e36495-b280-42f7-befe-6dc67241c4f7.png)

I see someone with the same issue on this issue : 
https://github.com/glpi-project/glpi/issues/7619#issuecomment-658811420

### Relevant log output

```shell
[2023-01-13 12:37:20] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot login, user or password wrong in C:\wamp64\www\glpi\vendor\laminas\laminas-mail\src\Storage\Imap.php at line 225
  Backtrace :
  src\Toolbox.php:2196                               Laminas\Mail\Storage\Imap->__construct()
  src\MailCollector.php:1375                         Toolbox::getMailServerStorageInstance()
  src\MailCollector.php:698                          MailCollector->connect()
  front\mailcollector.form.php:103                   MailCollector->collect()
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.5 ( => C:\wamp64\www\glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT DDP21-IT 10.0 build 19045 (Windows 10) AMD64
PHP 7.4.26 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, com_dotnet, ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sockets, sodium, sqlite3,
	standard, tokenizer, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/7.4.26 (Apache/2.4.51 (Win64) OpenSSL/1.1.1l PHP/7.4.26 Server at
	support-it.diadom.com Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.36
	Server SQL Mode: STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER
	Parameters: glpiBDD@localhost/glpi_bdd
	Host info: localhost via TCP/IP
	
PHP version (7.4.26) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.36) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_cache has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\etc\glpi has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_cron has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_dumps has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_graphs has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_lock has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_pictures has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_plugins has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_rss has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_sessions has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_tmp has been validated.
Write access to C:\Users\glpiadmin\AppData\Roaming\glpi_conf\var\lib\glpi/_uploads has been validated.
GLPI data directories are located in a secured path.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\wamp64\www\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\wamp64\\www\\glpi"
GLPI_CONFIG_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\etc\\glpi"
GLPI_VAR_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi"
GLPI_DOC_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi"
GLPI_CRON_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_cron"
GLPI_DUMP_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_dumps"
GLPI_GRAPH_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_graphs"
GLPI_LOCK_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_lock"
GLPI_PICTURE_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_plugins"
GLPI_RSS_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_rss"
GLPI_SESSION_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_sessions"
GLPI_TMP_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_tmp"
GLPI_UPLOAD_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_uploads"
GLPI_CACHE_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_cache"
GLPI_LOG_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\log\\glpi"
GLPI_MARKETPLACE_DIR: "C:\\wamp64\\www\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_LOCAL_I18N_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_locales"
GLPI_INVENTORY_DIR: "C:\\Users\\glpiadmin\\AppData\\Roaming\\glpi_conf\\var\\lib\\glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "C:\\wamp64\\www\\glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (C:\wamp64\www\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\wamp64\www\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\wamp64\www\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.5.0 in (C:\wamp64\www\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\wamp64\www\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\wamp64\www\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\wamp64\www\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\wamp64\www\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\wamp64\www\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\wamp64\www\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\wamp64\www\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\wamp64\www\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\wamp64\www\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\wamp64\www\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\wamp64\www\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\wamp64\www\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\wamp64\www\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\wamp64\www\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\wamp64\www\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\wamp64\www\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\wamp64\www\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\wamp64\www\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\wamp64\www\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\wamp64\www\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\wamp64\www\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\wamp64\www\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\wamp64\www\glpi\vendor\psr\cache\src)
league/csv in (C:\wamp64\www\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\wamp64\www\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\wamp64\www\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\wamp64\www\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\wamp64\www\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\wamp64\www\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\wamp64\www\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\wamp64\www\glpi\vendor\symfony\cache)
html2text/html2text in (C:\wamp64\www\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\wamp64\www\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\wamp64\www\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\wamp64\www\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\wamp64\www\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (C:\wamp64\www\glpi\vendor\symfony\polyfill-php80)
symfony/polyfill-php81 in (C:\wamp64\www\glpi\vendor\symfony\polyfill-php81)
symfony/polyfill-php82 in (C:\wamp64\www\glpi\vendor\symfony\polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: '*************', Port: '****', BaseDN: 'DC=*******,DC='*****', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'*******************', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.6      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Not installed                           
		Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

It looks like it is a configuration issue, not a bug.
