### ISSUE TITLE
Error "File is altered (bad checksum)" on documents

### ISSUE THREAD

**Issue by cdecle** [glpi-project/glpi#13792]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Hello, 

We store attachments (Word, Pdf or capture) stored on Documents on your GLPI.
If I try to open an attachment shared by myself, I can download and show the document.
By if I try to open an attachment shared by my colleagues, I have this error message : 
![image](https://user-images.githubusercontent.com/103191216/212270872-5bdce9d8-ed59-4340-a824-617ab2f302d5.png)
The title of this frame is "Access Denied".
Windows and IIS environement.

We have 2 GLPI installed.

A  bug on GLPI or no good rights on Windows Server, can you help us ?

Tks a lot.

### Your GLPI setup information

Operating system: Windows NT W945401IIS02 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.0.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, readline, session, soap, sodium, standard, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Server Software: MariaDB Server
	Server Version: 10.5.9-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxxxxxxx
	Host info: xxxxx via TCP/IP
	
PHP version (8.0.0) is supported.PHP version (8.0.0) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.9) is supported.Database engine version (10.5.9) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated. Write access to C:\inetpub\wwwroot\glpi/config has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated. Write access to C:\inetpub\wwwroot\glpi/files has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated.
Write access to C:\inetpub\wwwroot\glpi/config has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated.
Write access to C:\inetpub\wwwroot\glpi/files has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.
The following directories should be placed outside "C:\inetpub\wwwroot\glpi": ‣ "C:\inetpub\wwwroot\glpi/files" ("GLPI_VAR_DIR") ‣ "C:\inetpub\wwwroot\glpi\config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "C:\inetpub\wwwroot\glpi":
‣ "C:\inetpub\wwwroot\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\inetpub\wwwroot\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is not present.Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment]
Hi,

`File is altered (bad checksum)` is a message that appears when the requested document file contents has changed since the corresponding document has been created in GLPI. It is a way to ensure that GLPI does not serve corrupted files (or files that has been replaced by a malicious software/person).

> We have 2 GLPI installed.

Is this a valuable information here? Are the document files and/or the database shared between both?

Anyway, the person that share the file and the person that tries to read it should not have any impact on this checksum validation. You should verify state of corresponding files on the filesystem.

**Comment by trasher** [comment]
No feedback, I close
