### ISSUE TITLE
no translation for unlock mechanism notification available

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1380]
Hi,
there is no translation on transifex available for:

```
      Hello ##objectlock.lockedby.firstname##,
      Could go to this item and unlock it for me?
      Thank you,
      Regards,
      ##objectlock.requester.firstname##
```

**Comment by trasher** [comment]
I wonder if this has been fixed

**Comment by tomolimo** [comment]
Are there translations available for default notification templates?

**Comment by trasher** [comment]
I do not know how this is designed to be internationalized; but there does not seem to have any  templates notifications messages in the translations files right now.

Is a translation system available from GLPI itself?

**Comment by tomolimo** [comment]
yes, via notification templates, and it seems that in the past we do not deliver template translations, but only English
