### ISSUE TITLE
bad image dimensions in notifications

### ISSUE THREAD

**Issue by doberk** [glpi-project/glpi#13819]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0

### Bug description

When sending notifications with images embedded the html code of the message includes tag "width" but not tag "height". With large images (for example 1920x1080) it shows the image very stretched and imposible to read. I seems that exists a max-height but not a max-width. Images in notifications should have a max-width and max-height and this values should keep the aspect ratio of the image.

**Comment by cedric-anne** [comment]
Hi,

What is the exact version of your GLPI instance?

**Comment by doberk** [comment]
Hi,

10.0.0

**Comment by cedric-anne** [comment]
This should be fixed in GLPI 10.0.5 (see #12883).

Please try to reproduce on GLPI 10.0.5, or on [10.0 nightly build](https://nightly.glpi-project.org/glpi/), and reopen the issue if problem persist.
