### ISSUE TITLE
Recurring Ticket Status Not Getting Correctly Set.

### ISSUE THREAD

**Issue by bturnbough81** [glpi-project/glpi#13838]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When a recurring ticket is created and it uses a template that sets the status to NEW, it is not created with a status of NEW.  It is instead created with a status of "Processing (assigned)".

**Comment by cedric-anne** [comment]
Hi,

#14745 should fix this behaviour.
