### ISSUE TITLE
GLPI 10 : Disable " Request " in incident type 

### ISSUE THREAD

**Issue by cyrilLah** [glpi-project/glpi#13835]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

Glpi 10.5

### Bug description

In Glpi 9 and above, we hidden " Request  " in ticket's form

here : /var/www/html/glpi/inc/ticket.class.php

we can comment this line to hide it

static function getTypes() {

    $options[self::INCIDENT_TYPE] = __('Incident');
     /* BEGIN EXCENT FIXME */
     // $options[self::DEMAND_TYPE]   = __('Request');
     /* END EXCENT FIXME */

    return $options;
 }

Where can I do the same thing in new release ?

Thanks for your answer :)

**Comment by cedric-anne** [comment]
Hi,

You should probably do it. We will not validate your patch, but you can easilly test it on a test server.

**Comment by cyrilLah** [comment]
ok understood but I find in which file can I do this change

**Comment by cedric-anne** [comment]
src/Ticket.php
