### ISSUE TITLE
HTML tag in view

### ISSUE THREAD

**Issue by Coyote00** [glpi-project/glpi#13847]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello have htm in history list of ticket 
![ticket2](https://user-images.githubusercontent.com/123153876/213698778-5f70c9e4-7335-45d1-9921-4e2534b1b468.PNG)

**Comment by cedric-anne** [comment]
Hi,

Please upgrade to GLPI 10.0.5 and try to reproduce. If problem persist, please provide steps to reproduce on a clean GLPI install.

**Comment by trasher** [comment]
Please also make sure issue ca be reproduced with all plugins disabled.

**Comment by Coyote00** [comment]
Ok i proceed, thank you

**Comment by Coyote00** [comment]
if upgrade to 10.0.5 i can't use FusionInventory plugin

**Comment by cedric-anne** [comment]
> if upgrade to 10.0.5 i can't use FusionInventory plugin

You can use `glpiinventory` instead.
`glpiinventory` plugin is a fork from `fusioninventory` plugin that has been made to keep support of inventory advanced features in combination of usage of basic inventory features that are now directly embeded in GLPI itself. It has been made by GLPI core team

**Comment by cedric-anne** [comment]
It can be found here: https://github.com/glpi-project/glpi-inventory-plugin

**Comment by Coyote00** [comment]
Oh Thank you

**Comment by trasher** [comment]
No feedback, I close
