### ISSUE TITLE
Sockets can be assigned to multiple cables

### ISSUE THREAD

**Issue by rbrannath** [glpi-project/glpi#13851]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When adding a cable, a socket can be assigned to multiple cables since a socket which is already in use is still displayed in the dropdown.

If a socket is assigned to multiple cables, it leads to an error in the socket view of an item. This is because the existing query expects one result but gets multiple.
![grafik](https://user-images.githubusercontent.com/14164020/213989124-2aedb7c5-e82e-4318-8663-769ba63d9196.png)

I have already a fix for this issue and will open a PR.

### Page URL

/front/cable.form.php?id=-1

**Comment by stonebuzz** [comment]
```Cable``` form should not allow selection of a ```NetworkPort``` that is already connected to a cable.

One ```NetworkPort``` can only be linked to one ```Cable```

Let me check to fix this.

**Comment by stonebuzz** [comment]
Hi @rbrannath 
can you try this -> https://github.com/glpi-project/glpi/pull/13863

Best regards

**Comment by rbrannath** [comment]
Hi @stonebuzz 
thanks for the quick response. It is working, but you should add the itemtype and item id to the queries. 
Right now, the result gives all used sockets. It would be more performant to only get the used sockets which are relevant for the dropdown.

**Comment by rbrannath** [comment]
Now I am getting a TypeError. The form is broken because of this
`
Uncaught Exception TypeError: Glpi\Socket::getSocketAlreadyLinked(): Argument #2 ($items_id) must be of type int, string given in /var/www/html/glpi/src/Socket.php at line 1138
`

**Comment by rbrannath** [comment]
PR #13863 is merged, I assume this ticket can be closed
