### ISSUE TITLE
[9.5.10 / 9.5.11] The TinyMCE menu has disappeared in the ticket templates

### ISSUE THREAD

**Issue by nykroy** [glpi-project/glpi#13868]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

The TinyMCE menu has also disappeared on description field of ticket template

### Steps To reproduce

Go to Home >Assistance>Tickets>Ticket templates
Create new template or edit one.
Go to tab "Predefined fields";
Select "Description";
The "HTML Body" field does not show the TinyMCE menu.
![image](https://user-images.githubusercontent.com/7745881/214332493-cd0fa476-6b5b-416c-bacf-2465c83e8fd8.png)

### Your GLPI setup information

<html>
<body>

[code]   GLPI 9.5.11 ( => /usr/share/glpi) Installation mode: RPM Current language:en_GB
--

Operating system: Linux VP0488 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 PHP 8.0.24 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, 	sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="60" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="4M"  Software: nginx/1.21.5 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.55 Server Software: MariaDB Server 	Server Version: 10.3.34-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.34) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated. Write access to /usr/share/glpi/marketplace has been validated. For security reasons, SELinux mode should be Enforcing.

GLPI_ROOT: /usr/share/glpi GLPI_CONFIG_DIR: /etc/glpi GLPI_VAR_DIR: /var/lib/glpi/files GLPI_LOG_DIR: /var/log/glpi GLPI_HTMLAWED: /usr/share/php/htmLawed/htmLawed.php GLPI_FONT_FREESANS: /usr/share/fonts/gnu-free/FreeSans.ttf GLPI_SYSTEM_CRON: 1 GLPI_INSTALL_MODE: RPM GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/lib/glpi/files GLPI_CACHE_DIR: /var/lib/glpi/files/_cache GLPI_CRON_DIR: /var/lib/glpi/files/_cron GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales GLPI_LOCK_DIR: /var/lib/glpi/files/_lock GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins GLPI_RSS_DIR: /var/lib/glpi/files/_rss GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions GLPI_TMP_DIR: /var/lib/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/share/glpi/locales GLPI_VERSION: 9.5.11 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.5 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/usr/share/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/usr/share/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/plugins/oauthimap/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/plugins/oauthimap/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.7 in (/usr/share/pear)

[/code]

</body>
</html>

**Comment by nykroy** [comment]
Is related with https://github.com/glpi-project/glpi/issues/13256

**Comment by cedric-anne** [comment]
Hi,

You should upgrade to GLPI 9.5.12. If problem persist, it will not be solved as GLPI 9.5 only receives security updates now.
