### ISSUE TITLE
update to glpi 10.0.6 fails due to npm requirements

### ISSUE THREAD

**Issue by antoniotvr** [glpi-project/glpi#13875]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.5

### Bug description

Hi.

I am trying to update from release 10.0.5 to 10.0.6.

I have downloaded the new tarball from github releases page, migrate configs and files, but this time (it is the first one when I encounter this problem) I obtain an error message in the web page of GLPI insteaf of the upgrade procedure steps.

The error message says that I have to install missing dependencies through composer.

I have install composer and then a new error related to nodejs (npm command missing).

I have installed nodejs but then I obtain an error related to cache files that are proprerty of root user.

Then I stop the migration and I am asking here to be supported if you can.

Are so nodejs, composers, and other libraries now required to do the installation / upgrade of glpi?

Because in the documentation I have not found anywhere these new requirements.

Thank you

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.5 ( => /opt/html)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.10 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: nginx/1.18.0
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.11-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.11) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /opt/html/files/_cache has been validated.
Write access to /opt/html/config has been validated.
Write access to /opt/html/files/_cron has been validated.
Write access to /opt/html/files has been validated.
Write access to /opt/html/files/_dumps has been validated.
Write access to /opt/html/files/_graphs has been validated.
Write access to /opt/html/files/_lock has been validated.
Write access to /opt/html/files/_pictures has been validated.
Write access to /opt/html/files/_plugins has been validated.
Write access to /opt/html/files/_rss has been validated.
Write access to /opt/html/files/_sessions has been validated.
Write access to /opt/html/files/_tmp has been validated.
Write access to /opt/html/files/_uploads has been validated.
The following directories should be placed outside "/opt/html":
‣ "/opt/html/files" ("GLPI_VAR_DIR")
‣ "/opt/html/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /opt/html/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/opt/html"
GLPI_CONFIG_DIR: "/opt/html/config"
GLPI_VAR_DIR: "/opt/html/files"
GLPI_MARKETPLACE_DIR: "/opt/html/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/opt/html/files"
GLPI_CACHE_DIR: "/opt/html/files/_cache"
GLPI_CRON_DIR: "/opt/html/files/_cron"
GLPI_DUMP_DIR: "/opt/html/files/_dumps"
GLPI_GRAPH_DIR: "/opt/html/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/opt/html/files/_locales"
GLPI_LOCK_DIR: "/opt/html/files/_lock"
GLPI_LOG_DIR: "/opt/html/files/_log"
GLPI_PICTURE_DIR: "/opt/html/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/opt/html/files/_plugins"
GLPI_RSS_DIR: "/opt/html/files/_rss"
GLPI_SESSION_DIR: "/opt/html/files/_sessions"
GLPI_TMP_DIR: "/opt/html/files/_tmp"
GLPI_UPLOAD_DIR: "/opt/html/files/_uploads"
GLPI_INVENTORY_DIR: "/opt/html/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/opt/html/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/opt/html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/opt/html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/opt/html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/opt/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/html/vendor/true/punycode/src)
iamcal/lib_autolink in (/opt/html/vendor/iamcal/lib_autolink)
sabre/dav in (/opt/html/vendor/sabre/dav/lib/DAV)
sabre/http in (/opt/html/vendor/sabre/http/lib)
sabre/uri in (/opt/html/vendor/sabre/uri/lib)
sabre/vobject in (/opt/html/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/opt/html/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/opt/html/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/opt/html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/opt/html/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/opt/html/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/opt/html/vendor/elvanto/litemoji/src)
symfony/console in (/opt/html/vendor/symfony/console)
scssphp/scssphp in (/opt/html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/opt/html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/opt/html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/opt/html/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/opt/html/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/opt/html/vendor/ramsey/uuid/src)
psr/log in (/opt/html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/opt/html/vendor/psr/simple-cache/src)
psr/cache in (/opt/html/vendor/psr/cache/src)
league/csv in (/opt/html/vendor/league/csv/src)
mexitek/phpcolors in (/opt/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/opt/html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/opt/html/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/opt/html/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/opt/html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/opt/html/vendor/paragonie/sodium_compat/src)
symfony/cache in (/opt/html/vendor/symfony/cache)
html2text/html2text in (/opt/html/vendor/html2text/html2text/src)
symfony/css-selector in (/opt/html/vendor/symfony/css-selector)
symfony/dom-crawler in (/opt/html/vendor/symfony/dom-crawler)
twig/twig in (/opt/html/vendor/twig/twig/src)
twig/string-extra in (/opt/html/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/opt/html/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'dc01.maddant.local', Port: '389', BaseDN: 'OU=Maddalena_Utenti,DC=maddant,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=ServiceAD,OU=Servizio,OU=Maddalena_Utenti,DC=maddant,DC=local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@relay.maddant.local)

</details><details><summary>Plugins list</summary><pre> 
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Error / to clean                        
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.12.0     State: Error / to clean                        
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

Did you use the [glpi-10.0.6.tgz](https://github.com/glpi-project/glpi/releases/download/10.0.6/glpi-10.0.6.tgz) file or the `Source code (tar.gz)` file ?
The first one is the official build, that should work without having to use composer or npm, but the second one corresponds to the source code that has to be built manually.

**Comment by trasher** [comment]
Please do not use source archives.
