### ISSUE TITLE
Error 404 apiclient.php 

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi#13874]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,
I have an error 404 when i'm in a API Client and i click on list (top left)
https://glpiserveur/front/apiclient.php?sort%5B0%5D=0&order%5B0%5D=ASC&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=

### Page URL

https://glpiserveur/front/apiclient.form.php?id=1

### Steps To reproduce

1. click on the list icone (top left)

### Your GLPI setup information

same on 10.0.5

### Anything else?

Thank you

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.
