### ISSUE TITLE
Incorrect path when changing entity from the top-rigth menu

### ISSUE THREAD

**Issue by yodapotatofly** [glpi-project/glpi#13876]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When I go on the top-right menu and I select an entity, I am redirect to `https://mydomain.com/glpi/front/central.php?active_entity=0` but this is incorrect since my glpi is installed at `https://mydomain.com/` so there should not be `/glpi/` in the url.

This may be linked to the fact that I change the vhost DocumentRoot from `/var/www` to `/var/www/glpi` in order not to have the /glpi in the url. Maybe I missed some change I need to do in GLPI ?

I haven't found any other place where this behavior hapens. Only on that specific menu.

**Comment by cedric-anne** [comment]
Hi,

Is `URL of the application` value in general configuration is correct ?

**Comment by yodapotatofly** [comment]
Yes, I had changed it myself after changing the DocumentRoot.
I also had to manually change the API URL

**Comment by cedric-anne** [comment]
Maybe it is due to a misconfiguration of the Vhost.

Unless there is some wrongly configured proxy/redirect from a Vhost to another, I do not know what could happen here.

**Comment by yodapotatofly** [comment]
There is no such things. Also, if I inspect the elements, I have the following :
```
<span class="fancytree-title">
  <a href="/glpi/front/central.php?active_entity=2">My Sub Entity</a>
</span>
```

From where I stand, the issue seems to be comming from the code itself, not from some kind of redirect or proxy.
I haven't been able to find from where exactly though

**Comment by OlinuxX** [comment]
I have the exact same issue (description is identical, but on my server the change was from /var/www/html to /var/www/html/glpi), and I do not see where I could change this behaviour.
New URL is good on the server as weel.

So at least 2 of us have the same issue.

**Comment by cedric-anne** [comment]
This seems to be a caching issue. Indeed, tree built in `ajax/entitytreesons.php` is cached, but cache is not invalidated when `$CFG_GLPI['root_doc']` change.
I do not know if it is possible to easilly detect `$CFG_GLPI['root_doc']` changes, so the solution may be to add `$CFG_GLPI['root_doc']` value in cache key itself, even if it is some kind of hack.

Anyway, you could try to clean cache, either in UI, in `Setup > General > Performances` (you have to be in debug mode to see the button), either using the `php bin/console cache:clear` CLI command.

**Comment by yodapotatofly** [comment]
Thanks, that worked perfectly
