### ISSUE TITLE
[GLPI 10.0.6] Printer (page) counters graphs are not displayed

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#13882]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello. 
After upgrading from 10.0.5 to 10.0.6, printer (page) counter graphs are not displayed.

![image](https://user-images.githubusercontent.com/16879167/214708647-8c80e5be-3183-4a80-9a94-46ee500676c8.png)

In browser console errors.

### Relevant log output

```shell
VM6239:103 JQMIGRATE: Migrate is installed with logging active, version 3.4.0

base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25 jQuery.Deferred exception: Cannot read properties of undefined (reading 'element') TypeError: Cannot read properties of undefined (reading 'element')
    at HTMLDocument.<anonymous> (<anonymous>:5:70)
    at u (https://site.ru/public/lib/base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25:27491)
    at c (https://site.ru/public/lib/base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25:27819) undefined
E.Deferred.exceptionHook @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
c @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
setTimeout (async)
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
add @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
eval @ VM6239:970
obj.<computed> @ VM6239:180
then @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
E.fn.ready @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
E.fn.init @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
eval @ VM6239:225
obj.<computed> @ VM6239:180
E @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
(anonymous) @ VM6303:4
x @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
Be @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
append @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
K @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
html @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2158
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
C @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
load (async)
send @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
ajax @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
eval @ VM6239:378
obj.<computed> @ VM6239:180
E.each.E.<computed> @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
loadTabContents @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2157
(anonymous) @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2181
dispatch @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
v.handle @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
trigger @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
trigger @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
trigger @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
s @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
_transitionComplete @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
o @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
_activate @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
show @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
jQueryInterface @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
(anonymous) @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2185
u @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
c @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
setTimeout (async)
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fire @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
ready @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
U @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25

base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25 Uncaught TypeError: Cannot read properties of undefined (reading 'element')
    at HTMLDocument.<anonymous> (<anonymous>:5:70)
    at u (base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25:27491)
    at c (base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25:27819)
(anonymous) @ VM6303:5
u @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
c @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
setTimeout (async)
E.readyException @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
u @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
c @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
setTimeout (async)
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fire @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
c @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
setTimeout (async)
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
add @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
eval @ VM6239:970
obj.<computed> @ VM6239:180
then @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
E.fn.ready @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
E.fn.init @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
eval @ VM6239:225
obj.<computed> @ VM6239:180
E @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
(anonymous) @ VM6303:4
x @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
Be @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
append @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
K @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
html @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2158
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
C @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
load (async)
send @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
ajax @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
eval @ VM6239:378
obj.<computed> @ VM6239:180
E.each.E.<computed> @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
loadTabContents @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2157
(anonymous) @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2181
dispatch @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
v.handle @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
trigger @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
trigger @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
trigger @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
s @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
_transitionComplete @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
o @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
_activate @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
show @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
each @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:14
jQueryInterface @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:198
(anonymous) @ printer.form.php?id=125&formoptions=data-track-changes%3Dtrue:2185
u @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
c @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
setTimeout (async)
(anonymous) @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fire @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
l @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
fireWith @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
ready @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
U @ base.min.js?v=ceee5ff31faab27a2e30afc4c0af62d26fe3a283:25
```

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.6 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux 82fbfebbb9a8 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64
PHP 8.1.2-1ubuntu2.9 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="1500" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) OpenSSL/3.0.2 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 YaBrowser/22.11.5.716 Yowser/2.5 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.6.11-MariaDB-1:10.6.11+maria~ubu2004
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@mariadb/glpi
	Host info: mariadb via TCP/IP
	
PHP version (8.1.2-1ubuntu2.9) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.11) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi":
? "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
? "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'site.ru', Port: '389', BaseDN: 'DC=site,DC=ru', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'glpi_ad', Use TLS:
		none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@site.ru)

</details><details><summary>Plugins list</summary><pre> 
	barcode              Name: Barcode                        Version: 2.7.1      State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Manual
	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	telegrambot          Name: TelegramBot                    Version: 3.0        State: Installed / not activated               
		Install Method: Manual
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Installed / not activated               
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	itilcategorygroups   Name: Группы ITIL Категории     Version: 2.5.1      State: Installed / not activated       
		        Install Method: Marketplace
	fields               Name: Дополнительные поля    Version: 1.20.0     State: Enabled                         
		        Install Method: Manual
	news                 Name: Оповещения                     Version: 1.10.5     State: Installed / not activated       
		        Install Method: Marketplace
	escalade             Name: Переназначение             Version: 2.8.1      State: Enabled                         
		        Install Method: Marketplace
	pdf                  Name: Печать в PDF                   Version: 3.0.0      State: Enabled                            
		     Install Method: Manual
	mreporting           Name: Подробные отчеты          Version: 1.8.2      State: Enabled                         
		        Install Method: Manual
	screenshot           Name: Сделать и приложить снимок экр Version: 2.0.2      State: Enabled         
		                        Install Method: Marketplace
	tasklists            Name: Список задач                  Version: 2.0.3      State: Installed / not activated       
		        Install Method: Marketplace
	treeview             Name: Список по местонахождению Version: 1.10.0     State: Installed / not
		activated                Install Method: Marketplace
	tag                  Name: Управление тегами        Version: 2.10.0     State: Enabled                         
		        Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

I confirm there is a bug here.

**Comment by stonebuzz** [comment]
@AdrienClairembault 

The error is caused by this this pull request

https://github.com/glpi-project/glpi/pull/13775

```NetworkPort``` metrics are affected too.

```
Uncaught TypeError: Dashboard.getActiveDashboard() is undefined
    <anonymous> printer.form.php:5
```

**Comment by kofe88** [comment]
@cedric-anne @stonebuzz 

#13920 fixes this

![image](https://user-images.githubusercontent.com/16879167/215695324-ddf90e3f-5c60-4618-a5aa-11abd17ccd12.png)

Thank you very much!

**Comment by steph461** [comment]
I had this bug, I test this fix , its ok
