### ISSUE TITLE
Time to resolved not saved

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#1388]
When we change the "resolution time" field without going through the wizard, and updating the ticket, the value is not saved.

You must first click elsewhere so that the field loses focus and retrieves the value before saving.

Cordially

**Comment by trasher** [comment]
If I remember well, something similar has been reported; and I wonder if that has not yet been fixed on the 9.1/bugfixes branch. @orthagh?

**Comment by orthagh** [comment]
Yes, it's a recurrent issue with date[time] field.
btw, I don't have any clue to solve this.

**Comment by trasher** [comment]
Tis has been fixed :)

**Comment by bi-ayefo** [comment]
Please can I know how and where has this issue been fixed? I'm facing the same problem with glpi 9.1.1.
