### ISSUE TITLE
SQL missing in tag 10.0.6

### ISSUE THREAD

**Issue by maturbet-volta** [glpi-project/glpi#13888]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

The file `install/mysql/glpi-10.0.6-empty.sql` is not present in the [bundle](https://github.com/glpi-project/glpi/archive/refs/tags/10.0.6.tar.gz)

**Comment by trasher** [comment]
It's `nstall/mysql/glpi-empty.sql`
