### ISSUE TITLE
Unable to configure access to lock management in asset properties

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#13896]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Only the Super-Admin profile user has access to change asset lock fields and page /front/lockedfield.php
![image](https://user-images.githubusercontent.com/121490906/214863489-b08ee68e-b879-4b16-9fda-358faa9f2db7.png)

A user with an Admin profile, even when adding all maximum access rights, cannot manage asset locks
![image](https://user-images.githubusercontent.com/121490906/214864063-810a7490-10ec-40c9-b920-0e774076113b.png)

It is also not possible to configure access to change asset locks for a specific user profile. (/profile.form.php)

In addition, it would be convenient to be able to set not only global lock fields, but also globally specify fields that are always unlocked

I will be very grateful to you for solving this problem.

### Page URL

/front/monitor.form.php?id=1 or /front/computer.form.php?id=1 in lock tab in assets 

### Steps To reproduce

Change any field of the asset manually, after which a lock will be automatically set on it. Then try to remove this lock or unlock it by logging in with a user with a profile different from the Super-Admin profile (even if this profile with full access rights is identical to the Super-Admin profile)

**Comment by cedric-anne** [comment]
Hi,

Many issues were fixed between GLPI 10.0.3 and 10.0.6 on locks management. Please upgrade your GLPI and check if issue persists.

**Comment by ak47d** [comment]
Thank you for your prompt response. I'll try to update it soon and let you know if it helped.


> Hi,
> 
> Many issues were fixed between GLPI 10.0.3 and 10.0.6 on locks management. Please upgrade your GLPI and check if issue persists.

Thank you for your prompt response. I'll try to update it soon and let you know if it helped.

**Comment by ak47d** [comment]
There is also an issue with automatic locking by the inventory system user during automatic inventory. Is this issue also known? Has it been fixed in the new version?

**Comment by cedric-anne** [comment]
> by the inventory system user during automatic inventory

If automatic inventory is done by GLPI itself or by the `glpiinventory` plugin, it has probably been fixed.

**Comment by trasher** [comment]
Curren tissue is related to a very outdated GLPI version, I close; Feel free to reopen if issue persists.

**Comment by ak47d** [comment]
Thanks, updating to version 10.0.6 solved the issue. Including setting access rights to locks
