### ISSUE TITLE
In Project or Project Task, when Percent done is ticked and then is unticked, the dropdown doesn't work for choosing a manual percent

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#13899]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.5

### Bug description

In Project or Project Task when Percent done is ticked and then is unticked, the dropdown doesn't work for choosing a manual percent. 

I have to save or refresh the page with the change updated for be able to choose a manual percent in the dropdown.

The dropdown persists blocked when the "Percent done" is ticked, even if the Project or Project Task has been saved or not. 

### Page URL

/front/projecttask.form.php

### Steps To reproduce

1. Go to a Project or Project Task.
2. Ticked the "Percent done" option, the dropdown is blocked as supposed to be happend:
![image](https://user-images.githubusercontent.com/56606032/214934841-df5ec91a-78a0-4d3c-9888-21239540b5ac.png)

3. Unticked the "Percent done" option, the dropdown is still blocked it shouldn't to be happend: 
![image](https://user-images.githubusercontent.com/56606032/214936080-6a805fca-cbdc-48e7-b6a9-c1d9fc76823e.png)

4. The dropdown is unblocked when save the change or when refresh the page:
![image](https://user-images.githubusercontent.com/56606032/214936549-262cc4a6-3f00-4469-82a0-b6d48ff328b3.png)

### Anything else?

In 9.5 version it didn't happend:

- Percent done ticked:
![image](https://user-images.githubusercontent.com/56606032/214936814-a2605d4c-da77-49ce-b625-3300b9583da0.png)

- Percent done unticked: 
![image](https://user-images.githubusercontent.com/56606032/214936838-bbecd1af-ad98-4839-987a-d32cf92ee7f8.png)

**Comment by trasher** [comment]
Try with latest version

**Comment by jcervantes-sipecom** [comment]
Hi @trasher, yes updated to the last version:

![image](https://user-images.githubusercontent.com/56606032/215186738-de1a9768-c304-4462-b749-ab37aa87f66e.png)

Same happend (on-premise):

![image](https://user-images.githubusercontent.com/56606032/215186811-ff79f2b9-e8f8-4f18-89a6-4d354cdec8f0.png)

![image](https://user-images.githubusercontent.com/56606032/215186846-f114ddbd-3d2f-470c-abbf-765bb3bbf2ff.png)

Same happend (on cloud):

![image](https://user-images.githubusercontent.com/56606032/215187217-a05af87c-41ae-4f40-b909-bfc342b2357d.png)

![image](https://user-images.githubusercontent.com/56606032/215187244-8d6bb651-8d0b-45ce-918c-e0bbb2119102.png)

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug (at least on chrome).

**Comment by jcervantes-sipecom** [comment]
Yes, tested in Edged (Chromium based) and Firefox, the same issue.

**Comment by trasher** [comment]
Please try #14341
