### ISSUE TITLE
Project Task created without Planned start and end date just Planned Duration is displayed in the calendar of multiple users in Planning, instead of only the user/member who is assigned in the Project Team of the Project Task.

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#13898]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.5 and GLPI 9.5.9

### Bug description

When I create a Project Task without Planned start and end date just Planned Duration and then assign a user/member to that task in Project Team, I go to Planning and see that Project Task appears on multiple users' calendars instead of just the user assigned to it.

Even if the multiples users are in the same group or not.

### Page URL

/front/planning.php

### Steps To reproduce

1. Create a new Project.
2. Go to Kanban
3. Create a Project Task:
![image](https://user-images.githubusercontent.com/56606032/214875531-06a45f6e-82fb-4e69-9cad-0d397651beef.png)

4. Assign a user o member:
![image](https://user-images.githubusercontent.com/56606032/214876022-ddbaab6c-e440-4801-baae-a81daeee1dda.png)

5. Complete more info, without Planned Start and End Date, just Planned Duration:
![image](https://user-images.githubusercontent.com/56606032/214927040-749c58b9-bc66-4b2c-ad91-0b71aa58454e.png)

6. Go to planning, and add more users, see that the Project Task appears in the calendars of all users, even if they are in the same group or not:
![image](https://user-images.githubusercontent.com/56606032/214927807-ea703a03-1c4d-4b3c-a0ab-60e4ff20fbcd.png)

It shouldn't happen, the task just has to appear to the assigned user/member.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.5 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux VM-APACHE 5.15.0-1029-azure #36~20.04.1-Ubuntu SMP Tue Dec 6 17:00:26 UTC 2022 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="1G" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at IP Public Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1518.61
Server Software: (Ubuntu)
	Server Version: 8.0.32-0buntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_user@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.32) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi/config/ has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/config/"
GLPI_VAR_DIR: "/var/lib/glpi/files"
GLPI_LOG_DIR: "/var/log/glpi/_log"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi/files"
GLPI_CACHE_DIR: "/var/lib/glpi/files/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/files/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'dominio', Port: '389', BaseDN: 'DC=DOM--,DC=COM', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=User 1
		User Generic,CN=Managed Service Accounts,DC=DOM--,DC=COM', Use TLS: none
Server: 'dominio', Port: '389', BaseDN: 'DC=DOM--,DC=COM', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(distinguishedName=CN=%u,CN=Users,DC=DOM--,DC=COM))(!(distinguishedName=CN=%u,CN=Managed
		Service Accounts,DC=DOM--,DC=COM))(!(dn=OU=Z--,DC=DOM--,DC=COM)))', RootDN: 'CN=User 1 User
		Generic,CN=Managed Service Accounts,DC=DOM--,DC=COM', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (user1@smtp.SMTP.com)

</details><details><summary>Plugins list</summary><pre> 
	activity             Name: Activities                     Version: 3.1.2      State: Installed / not activated               
		Install Method: Marketplace
	actualtime           Name: ActualTime                     Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	fields               Name: Additional fields              Version: 1.20.0     State: Installed / not activated               
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated               
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.10.5     State: Installed / not activated               
		Install Method: Marketplace
	archisw              Name: Apps structures                Version: 2.2.15     State: Installed / not activated               
		Install Method: Marketplace
	cleanarchivedemails  Name: Archived eMail clean           Version: 2.0.0      State: Installed / not activated               
		Install Method: Manual
	impacts              Name: Asset impacts                  Version: 2.0.7      State: Installed / not activated               
		Install Method: Manual
	barcode              Name: Barcode                        Version: 2.7.1      State: Installed / not activated               
		Install Method: Marketplace
	behaviors            Name: Behaviours                     Version: 2.7.2      State: Installed / not activated               
		Install Method: Manual
	camerainput          Name: Camera Input                   Version: 2.0.1      State: Installed / not activated               
		Install Method: Marketplace
	positions            Name: Cartography                    Version: 6.0.2      State: Installed / not activated               
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	consumables          Name: Consumable request             Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	costs                Name: Costs                          Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	credit               Name: Credit vouchers                Version: 1.11.3     State: Installed / not activated               
		Install Method: Marketplace
	accounts             Name: Cuentas                        Version: 3.0.2      State: Installed / not activated               
		Install Method: Marketplace
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.12.0     State: Installed / not activated               
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.13     State: Installed / not activated               
		Install Method: Marketplace
	databases            Name: Databases                      Version: 2.3.2      State: Not installed                           
		Install Method: Manual
	dataflows            Name: Dataflows                      Version: 2.2.18     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.18     State: Installed / not activated               
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.3      State: Installed / not activated               
		Install Method: Marketplace
	environment          Name: Environment                    Version: 2.4.2      State: Installed / not activated               
		Install Method: Manual
	escalade             Name: Escalation                     Version: 2.8.1      State: Installed / not activated               
		Install Method: Marketplace
	father               Name: Father&Sons                    Version: 1.2.0      State: Not installed                           
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.3     State: Installed / not activated               
		Install Method: Marketplace
	fpsaml               Name: FP SAML                        Version: 1.1.0      State: Installed / not activated               
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.1      State: Installed / not activated               
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Installed / not activated               
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.6      State: Installed / not activated               
		Install Method: Marketplace
	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Installed / not activated               
		Install Method: Manual
	resources            Name: Human Resources                Version: 3.0.4      State: Installed / not activated               
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.8.3      State: Installed / not activated               
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.1      State: Installed / not activated               
		Install Method: Marketplace
	jsaddons             Name: JS Addons                      Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	mailanalyzer         Name: Mail Analyzer                  Version: 3_1.0.0 beta State: Installed / not activated               
		Install Method: Manual
	metabase             Name: Metabase                       Version: 1.3.2      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Installed / not activated               
		Install Method: Marketplace
	satisfaction         Name: More satisfaction              Version: 1.6.1      State: Installed / not activated               
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Installed / not activated               
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.4      State: Installed / not activated               
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Installed / not activated               
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.1     State: Installed / not activated               
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Installed / not activated               
		Install Method: Marketplace
	officeonline         Name: Office Online                  Version: 2.0.2      State: Installed / not activated               
		Install Method: Manual
	onetimesecret        Name: OneTimeSecret                  Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	order                Name: Orders management              Version: 2.10.0     State: Installed / not activated               
		Install Method: Marketplace
	patchpanel           Name: PatchPanel                     Version: 0.9.4.1    State: Installed / not activated               
		Install Method: Manual
	phpsaml              Name: PHP SAML                       Version: 1.2.0      State: Installed / not activated               
		Install Method: Manual
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Installed / not activated               
		Install Method: Manual
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Installed / not activated               
		Install Method: Manual
	purchaserequest      Name: Purchase request               Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	reports              Name: Reports                        Version: 1.16.0     State: Installed / not activated               
		Install Method: Manual
	reservation          Name: Reservation                    Version: 2.4.2      State: Installed / not activated               
		Install Method: Manual
	room                 Name: Rooms                          Version: 3.1.3      State: Not installed                           
		Install Method: Manual
	screenshot           Name: Screenshot                     Version: 2.0.2      State: To update                               
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	stab                 Name: Split Timeline Action Buttons  Version: 1.1.2      State: Installed / not activated               
		Install Method: Marketplace
	statecheck           Name: Statecheck Rules               Version: 2.3.8      State: Installed / not activated               
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.10.0     State: Installed / not activated               
		Install Method: Marketplace
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	ticketcleaner        Name: Ticket Cleaner                 Version: 3.0.0      State: Not installed                           
		Install Method: Manual
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.1   State: Installed / not activated               
		Install Method: Marketplace
	timesheet            Name: Timesheet for GLPI             Version: 1.0.1      State: Not installed                           
		Install Method: Manual
	treeview             Name: Tree view                      Version: 1.10.0     State: Installed / not activated               
		Install Method: Marketplace
	typology             Name: Typologies                     Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Installed / not activated               
		Install Method: Marketplace
	webapplications      Name: Web applications               Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

I am not able to reproduce. Could youplease all information about the project itself (and the project team), the task team, the groups membership of users, ...?

**Comment by cedric-anne** [comment]
> I am not able to reproduce. 

To be more precise, as long as I do not set any start/end date on the task, I do not see it even on user planning.

**Comment by jcervantes-sipecom** [comment]
Sure, I tried the same in cloud, I'm logged with admin, look:

1. I have 6 users with self-service profile assigned, and the admin with super-admin profile, users 1-3 are in the group GRP123, users 4,5 are in the group GRP45, user 6 and admin are not in any group:

![image](https://user-images.githubusercontent.com/56606032/215595854-0a1dec91-5e73-4677-a6c8-702c70c7f90e.png)

![image](https://user-images.githubusercontent.com/56606032/215595892-50b57d59-98b0-4355-bf84-320b9a8b4bfc.png)


2. I have created a new Project named PRJTest1, with Planned start date: 2023-01-01 12:00:00 and Planned end date: 2023-12-31 12:00:00, manager admin

![image](https://user-images.githubusercontent.com/56606032/215595979-fa48802a-6122-49ea-8ceb-44a428e8947e.png)


3. I've  added a Project Task named Task1 with no Start and End date, just Planned Duration, and added the User1 in Task Team:

![image](https://user-images.githubusercontent.com/56606032/215596048-729d9cd5-e65f-4068-bd6d-b44e7156f85a.png)

![image](https://user-images.githubusercontent.com/56606032/215596083-7a573704-7837-455a-b299-3beb0d642474.png)


4. In Assistance -> Planning, I added the 6 users and the admin as well, and as you can see this Task1 shows in all 7 users:

![image](https://user-images.githubusercontent.com/56606032/215596168-b4aede19-abe9-476f-bdca-d48423edc935.png)


I noted that when the "Not Planned Tasks" is selected, this tasks appears in all users, and when is deselected this tasks disappear:

![image](https://user-images.githubusercontent.com/56606032/215596293-a5e7ba3a-e9e2-4ca4-b0ff-b3dbaafab566.png)

I guess it's ok that this task shows when "Not Planned Tasks" is selected, but it should show only in the user's calendar assigned in "Task Team" not in all users.

**Comment by cedric-anne** [comment]
OK, I confirm the issue. Not planned task should not be visible by everyone.
