### ISSUE TITLE
planning view - sub task of project task is displayed - but done in the past

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1389]
I can see a sub task (of project task) which is done in past. All dates are in past so i should not see it on 02.12.2016 today, but i can see it in my home planning view.
![img_018](https://cloud.githubusercontent.com/assets/19192087/20831321/b43a3368-b884-11e6-9f1f-185146180ed4.jpg)

I think it is displayed becouse of project task date section but i should use the settings from sub task

**Comment by Armin83** [comment]
@orthagh 
Can you approve this bug ?

It is worse than I have assumed. Als task, sub task, tickets, change, etc are all at Done and 100% percent but i get the task in my view. If i delete me from team member (you can see in my screenshot) the task dissappear but this can't be a solution. I should look at a past project who have done this task.... 

![img_003](https://cloud.githubusercontent.com/assets/19192087/24442264/a736b616-145d-11e7-8eff-5959d683b0a0.jpg)

**Comment by pvasener** [comment]
I confirm the bug. It's been there since 9.1.0 and not fixed yet. It looks like the project task status is not checked. All tasks with statuses with 'Finished State' = Yes shouldn't appear in the planning.

**Comment by orthagh** [comment]
Hello here.

Sorry for the long delay for this issue.
Here is the fix, it should come into 9.1.5
