### ISSUE TITLE
[10.0.6] unable to migrate glpi_items_devicebatteries table

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#13895]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

php bin/console glpi:migration:utf8mb4 -vvvv

![image](https://user-images.githubusercontent.com/31952346/214863936-7d68abe3-bb71-4944-8a15-0e4071e8b2f9.png)

nothing in the standard log neither log migration nor php error

The manufacturing_date column contains null or certain dates with the year 2031! is this blocking?

Thanks

**Comment by cedric-anne** [comment]
Hi,

Could you run the ```ALTER TABLE `glpi_items_devicebatteries` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci``` directly on your SQL server?

**Comment by falco2001** [comment]
I have this Error Code: 1292. Incorrect date value: '0000-00-00' for column 'manufacturing_date' at row 1
I’ll put a date other than null? So

**Comment by cedric-anne** [comment]
You should either put null in this case, either put a valid SQL date.

**Comment by cedric-anne** [comment]
> The manufacturing_date column contains null or certain dates with the year 2031! is this blocking?

`NULL` or dates in future are valid for SQL. `0000-00-00` is invalid and should be replaced by `NULL`.

**Comment by falco2001** [comment]
UPDATE glpi_items_devicebatteries
SET glpi_items_devicebatteries = NULL
WHERE manufacturing_date = '0000-00-00'; not ok

Error Code: 1292. Incorrect date value: '0000-00-00' for column 'manufacturing_date' at row 1

SELECT * FROM `glpi_items_devicebatteries` WHERE `manufacturing_date` = '0000-00-00' ;  ok

an idea ?

**Comment by cedric-anne** [comment]
This should not trigger errors:
```sql
UPDATE glpi_items_devicebatteries
SET glpi_items_devicebatteries = NULL
WHERE manufacturing_date < '1000-01-01';
```

**Comment by falco2001** [comment]
thanks
i am also : 
11:04:14	ALTER TABLE `glpi_items_devicebatteries` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci	Error Code: 1292. Incorrect date value: '2031-01-00' for column 'manufacturing_date' at row 129	0.015 sec

**Comment by falco2001** [comment]
same response with 
UPDATE glpi_items_devicebatteries
SET glpi_items_devicebatteries.manufacturing_date = NULL
WHERE manufacturing_date >= '2031-01-00';

**Comment by falco2001** [comment]
i do this :  ok 💯 
UPDATE glpi_items_devicebatteries SET  manufacturing_date = '2021-01-01' WHERE  id in ( 318,538745,773041,788850,841845,887881,931697,952931,962626,1223205);

php bin/console glpi:migration:unsigned_keys
Trouvé 6 colonne(s) de clé principale ou étrangère utilisant des entiers signés
L'exécution de la commande peut être longue et ne devrait pas être interrompue.
Voulez-vous continuer ? [Yes/no]
 6/6 [============================] 100%
 Migration effectuée.

php bin/console glpi:migration:utf8mb4 -vvvv
Aucune migration requise.
Temps écoulé : < 1 sec.
Utilisation de la mémoire : 18.0 MiB.
