### ISSUE TITLE
Knowledge Base search in sub categories

### ISSUE THREAD

**Issue by PandaRoux8** [glpi-project/glpi#13905]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Since update from 10.0.5 to 10.0.6. 
When you search in Knowledge Base, it only searches in the root category.

Expected result : 
Searching article in all categories

This bug is introduced with the following commit [571c902ea7a8dd8ec6ac029502cf90d01cd150dd](https://github.com/glpi-project/glpi/commit/571c902ea7a8dd8ec6ac029502cf90d01cd150dd)

### Relevant log output

```shell
N/A
```

### Page URL

/front/knowbaseitem.php

### Steps To reproduce

- Go to Knowledge base
- Search for an article in a sub category 
> It won't show
- Search for an article in the root category
> It will show

Expected result is search in all categories

### Your GLPI setup information

GLPI 10.0.6 ( => /var/www/html/glpi.lcb-info.ch)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cedric-anne** [comment]
Hi,

Maybe fixed by #13877. Could you check ?

**Comment by cedric-anne** [comment]
Fixed by #13877.
