### ISSUE TITLE
Gantt view

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#1390]
If the label of a task is too long, the label is truncated in GANTT view.

**Comment by orthagh** [comment]
Like this:
![image](https://cloud.githubusercontent.com/assets/418844/21850028/f2a14512-d808-11e6-856d-2cf1a6fefb5d.png)

it seems intended, no ?
Maybe we miss a tooltip but as the view provided by jquery gantt lib, i think we can't achieve this easily.

**Comment by trasher** [comment]
I was taking a look at this. Sounds like we're passing full links to the JS lib, we could add a title on those ones; but I've not yet found where the link is built.

**Comment by orthagh** [comment]
same, in fact, we could fix that:
```diff
diff --git a/inc/commondbtm.class.php b/inc/commondbtm.class.php
index 4b3d81e..0227adf 100644
--- a/inc/commondbtm.class.php
+++ b/inc/commondbtm.class.php
@@ -935,7 +935,8 @@ class CommonDBTM extends CommonGLPI {
 
       $link = $this->getLinkURL();
 
-      return "<a ".$p['linkoption']." href='$link'>".$this->getNameID($options)."</a>";
+      $label = $this->getNameID($options);
+      return "<a ".$p['linkoption']." href='$link' title='$label'>$label</a>";
    }
 
 
```

**Comment by orthagh** [comment]
I reset the 9.1.2 milestone

**Comment by trasher** [comment]
Oh, I do it differently:
```diff
diff --git a/inc/projecttask.class.php b/inc/projecttask.class.php
index 4a25f60..fa2b7af 100644
--- a/inc/projecttask.class.php
+++ b/inc/projecttask.class.php
@@ -1156,7 +1156,7 @@ class ProjectTask extends CommonDBChild {
                         = array('id'    => $task->getID(),
                               'name'    => $task->fields['name'],
                               'desc'    => $task->fields['content'],
-                              'link'    => $task->getlink(),
+                              'link'    => $task->getlink(['linkoption' => " title='{$task->fields['name']}'"]),
                               'type'    => 'task',
                               'percent' => $percent,
                               'from'    => $real_begin,

```

**Comment by trasher** [comment]
There is a potential issue with your proposal; any existing linkoption providing a title would break something

**Comment by trasher** [comment]
But this could be fixed looking at presence of `title=` in the `linkoption`. But I guess that adding a title on every link generated should not be done in a bugfix (we can do for master).
