### ISSUE TITLE
Change Templates - unable to EDIT predefined fields

### ISSUE THREAD

**Issue by bturnbough81** [glpi-project/glpi#13907]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Unable to edit predefined fields in change templates?!  I need to delete and recreate the options in order to make the change?  This should be considered a bug it is so trivial.....

**Comment by trasher** [comment]
Try with latest release

**Comment by trasher** [comment]
Also, provide **all** requested information when you open an issue.

**Comment by bturnbough81** [comment]
I upgraded to 10.0.6 as per your request.  The issue still remains.

**Comment by cedric-anne** [comment]
Hi,

I confirm this action is not possible, as for tickets and problems. It could indeed be enhanced.

**Comment by bturnbough81** [comment]
So if this is a ‘feature request’, as you suggest (even though it is so basic it should have been included in the first place) where is the PROPER place to make said request?



Thank you,

Brad Turnbough
Senior Technology Analyst

[cid:Backlund-Investment-logo_20ce9d6e-04b9-4d73-9d17-cfc69decf4cc.gif]

P: 309.272.2739 F: 309.272.2839

www.betterbanks.com<http://www.betterbanks.com/>
www.statestreetbank.com<http://www.statestreetbank.com>

NOTICE: The information contained in this email and any document attached hereto is intended only for the named recipient(s). If you are not the intended recipient, nor the employee or agent responsible for delivering this message in confidence to the intended recipient(s), you are hereby notified that you have received this transmittal in error, and any review, dissemination, distribution or copying of this transmittal or its attachments is strictly prohibited. If you have received this transmittal and/or attachments in error, please notify me immediately by reply e-mail and then delete this message, including any attachments.
