### ISSUE TITLE
SQL error on upgrading GLPI to 10.0.3

### ISSUE THREAD

**Issue by GabrielCorreaR** [glpi-project/glpi#13900]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.11 to 10.0.3

### Bug description

I went to update my GLPI from 9.5.11 to 10.0.3 and this error is appearing

SQL Error "1288": The target table view_chamados of the UPDATE is not updatable in query "UPDATE `view_chamados` SET `Dt`.` Abertura` = NULL WHERE ( NOT (`Dt`.` Abertura` IS NULL)) AND (`Dt`.` Abertura` < CONVERT_TZ('1970-01-01 00:00:01', '+00:00', (SELECT @@SESSION.time_zone)))"

**Comment by cedric-anne** [comment]
Hi,

1. `view_chamados` is not a GLPI table. Please provide the full error trace or steps to reproduce so we could be able to see if we can exclude it from related script.
2. GLPI 10.0.3 is outdated, please try on GLPI 10.0.6.

**Comment by trasher** [comment]
This seems related to a plugin, and anyways, 10.0.3 is outdated.
