### ISSUE TITLE
Some technician profiles can't see document attached in the solution

### ISSUE THREAD

**Issue by nuria2c** [glpi-project/glpi#13904]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Users who have a profile that does not have "See my ticket" enabled do not see the files that are attached to the ticket solution with that profile.

We have technicians that we don't want to be able to manage their own tickets. For this reason we assign them two profiles, one to manage their own tickets and a second profile to be able to manage those assigned to them as a technician.

In this scenario, since the technician is not a requester of the ticket he can't see the file that has attached himself to the solution.

### Steps To reproduce

1. Create a technician profile without See my ticket" option available
2. Create a ticket with another user and assign it to a group to which the technician has access. The requester is not the technician.
3. Close the ticket with the technician profile attaching a file to the solution
4. The requester will see the file but the technician who attached it will not

**Comment by trasher** [comment]
Try with latest release

**Comment by nuria2c** [comment]
Ok. Thanks but i can't see any isse related in the 10.0.6

**Comment by nuria2c** [comment]
with GLPI 10.0.6 the issue is not solved. The behavor is the same.

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.

A technician that has not any of `Tickets: See my ticket`, `Problem: See (author)` and `Change: See (author)` will not see documents attached to solutions.
Technically, this is due to the fact that `CommonITILObject::getAssociatedDocumentsCriteria()` is based on global rights and not on rights related to a given Ticket/Problem/Change.

**Comment by nuria2c** [comment]
Thanks cedric-anne. We'll wait for the solution.

**Comment by nuria2c** [comment]
Hi,
Do you have a planifiction date to solve the bug?
Thanks

**Comment by cconard96** [comment]
Fixed for GLPI 11.0 in #16318
