### ISSUE TITLE
Change Tempaltes - Opening date is not populated with CURRENT date / time in preview option

### ISSUE THREAD

**Issue by bturnbough81** [glpi-project/glpi#13908]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

When utilizing a change template, you are provided with an option to PREVIEW a change.

When you do so, the fields you have predefined are populated into the change form.  

The Opening date is not predefined in the change and is completely blank even though it is defined in the change template.

**Comment by trasher** [comment]
Try with latest release

**Comment by bturnbough81** [comment]
I upgraded to 10.0.6 as per your request.  The issue still remains.

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.

**Comment by ftoledo** [comment]
i can confirm at 10.0.10

**Comment by trasher** [comment]
Please try #16211
