### ISSUE TITLE
Requestor and assigned to names listed twice in change template 'preview'

### ISSUE THREAD

**Issue by bturnbough81** [glpi-project/glpi#13909]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

I have a change template that uses my name as the requestor and also the assigned to.

When previewing a change, my name is listed as the 'requestor' and also the 'assigned to' twice.

**Comment by trasher** [comment]
Try with latest release

**Comment by bturnbough81** [comment]
The issue still remains n 10.0.6

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug. Thus, same bug exists in Change creation form.

**Comment by cedric-anne** [comment]
Duplicates #13601.
