### ISSUE TITLE
Problem searching for knowledge base articles

### ISSUE THREAD

**Issue by verdanatech-marcio** [glpi-project/glpi#13912]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

When searching for articles that have categories assigned, the search returns empty.

### Page URL

http://127.0.0.1/front/knowbaseitem.php

### Steps To reproduce

1.Open page knowbaseitem.php
2.Search for an article that has a category

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.6 (/glpi-10.0.6 => /var/www/html/glpi-10.0.6)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux  5.15.0-58-generic #64~20.04.1-Ubuntu SMP Fri Jan 6 16:42:31 UTC 2023 x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at localhost Port 80
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: Ubuntu 20.04
	Server Version: 10.3.37-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: admin@127.0.0.1/glpi-10.6
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.37) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi-10.0.6/files/_cache has been validated.
Write access to /var/www/html/glpi-10.0.6/config has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_cron has been validated.
Write access to /var/www/html/glpi-10.0.6/files has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_dumps has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_graphs has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_lock has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_pictures has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_plugins has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_rss has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_sessions has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_tmp has been validated.
Write access to /var/www/html/glpi-10.0.6/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi-10.0.6":
‣ "/var/www/html/glpi-10.0.6/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi-10.0.6/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi-10.0.6/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi-10.0.6"
GLPI_CONFIG_DIR: "/var/www/html/glpi-10.0.6/config"
GLPI_VAR_DIR: "/var/www/html/glpi-10.0.6/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi-10.0.6/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi-10.0.6/files"
GLPI_CACHE_DIR: "/var/www/html/glpi-10.0.6/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi-10.0.6/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi-10.0.6/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi-10.0.6/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi-10.0.6/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi-10.0.6/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi-10.0.6/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi-10.0.6/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi-10.0.6/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi-10.0.6/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi-10.0.6/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi-10.0.6/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi-10.0.6/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi-10.0.6/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi-10.0.6/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi-10.0.6/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi-10.0.6/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi-10.0.6/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi-10.0.6/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi-10.0.6/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi-10.0.6/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi-10.0.6/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi-10.0.6/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi-10.0.6/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi-10.0.6/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi-10.0.6/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi-10.0.6/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi-10.0.6/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi-10.0.6/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi-10.0.6/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi-10.0.6/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi-10.0.6/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi-10.0.6/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi-10.0.6/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi-10.0.6/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi-10.0.6/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi-10.0.6/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi-10.0.6/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi-10.0.6/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi-10.0.6/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi-10.0.6/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi-10.0.6/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi-10.0.6/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi-10.0.6/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi-10.0.6/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi-10.0.6/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi-10.0.6/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi-10.0.6/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi-10.0.6/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi-10.0.6/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi-10.0.6/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi-10.0.6/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi-10.0.6/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi-10.0.6/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi-10.0.6/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi-10.0.6/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi-10.0.6/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi-10.0.6/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 

</details><details><summary>Plugins list</summary><pre> 
	moreactions          Name: More Actions                   Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	skins                Name: Skins                          Version: 3.0.0      State: Not installed                           
		Install Method: Manual

</pre></details>

### Anything else?

![image](https://user-images.githubusercontent.com/80538863/215163776-117815ad-8414-48f5-b8f9-d7ba2e733f3f.png)
![image](https://user-images.githubusercontent.com/80538863/215163860-c95644eb-978f-4400-9b4f-ed8fedc549d5.png)

**Comment by cedric-anne** [comment]
Hi,

Maybe fixed by #13877. Could you check ?

**Comment by baplb** [comment]
Hi,

This fixed the issue for me.

**Comment by cedric-anne** [comment]
@baplb 

Thanks for the feedback.
