### ISSUE TITLE
Migration from 10.0.5 to 10.0.6

### ISSUE THREAD

**Issue by Ridha-DEBBAR** [glpi-project/glpi#13913]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

I upgrade the glpi 10.0.5 to 10.0.6
after that all the documents linked to Ticket, Changes or loaded document are not openening.
I got the following error : File Not Found.
![Access denied - GLPI](https://user-images.githubusercontent.com/98560544/215314233-4faeb112-2e13-4bf1-86ff-342d3d38f700.jpg)

**Comment by cedric-anne** [comment]
Hi,

If all your documents are unavailable, it probably means that you did not restored either your GLPI_VAR_DIR/GLPI_DOC_DIR, either you did not restored your `config/local_define.php` or `inc/downstream.php` specific config file.
