### ISSUE TITLE
command  php bin/console error 

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#13923]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Good morning,
when I run these two commands I have these errors . Thank you
![image](https://user-images.githubusercontent.com/31952346/215510486-d29b6645-4d63-4b00-9b61-276bcbe181de.png)
![image](https://user-images.githubusercontent.com/31952346/215510574-8640b7ac-6f74-4f79-b2c3-90772b6e93d0.png)
and
![image](https://user-images.githubusercontent.com/31952346/215510646-81b9d577-a1a6-42ad-90e0-274aae12f2f5.png)
![image](https://user-images.githubusercontent.com/31952346/215510729-da621223-c53c-49fc-8fa1-92b9acaf47c0.png)

**Comment by trasher** [comment]
Looks like a plugin issue, please report on plugin repository
