### ISSUE TITLE
Incorrect display of knowledge base blocks on the main page of the Self-service profile

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#13927]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Display problem:
![image](https://user-images.githubusercontent.com/121490906/215578052-2357f6ef-fe53-44a4-8425-3a51941755aa.png)

File problem  /glpi/front/helpdesk.public.php

Code needs to be replaced:
```
  if (Session::haveRight('knowbase', KnowbaseItem::READFAQ)) {
        $kb_popular    = KnowbaseItem::showRecentPopular("popular");
        $kb_recent     = KnowbaseItem::showRecentPopular("recent");
        $kb_lastupdate = KnowbaseItem::showRecentPopular("lastupdate");
```
Replace with code:
```
  if (Session::haveRight('knowbase', KnowbaseItem::READFAQ)) {
        $kb_popular    = KnowbaseItem::showRecentPopular("popular", false);
        $kb_recent     = KnowbaseItem::showRecentPopular("recent", false);
        $kb_lastupdate = KnowbaseItem::showRecentPopular("lastupdate", false);
```
After the fix:
![image](https://user-images.githubusercontent.com/121490906/215572909-5bac9144-464c-447a-9c69-6f8b7e3ef463.png)

Please include this fix in future versions of GLPI.

**Comment by cedric-anne** [comment]
Hi,

Could you please propose a pull request to fix this ?

Regards

**Comment by ak47d** [comment]
> Привет,
> 
> Не могли бы вы предложить запрос на включение, чтобы исправить это?
> 
> С уважением

Спасибо. Готово.

**Comment by ak47d** [comment]
> Hi,
> 
> Could you please propose a pull request to fix this ?
> 
> Regards

Thank you. Done
