### ISSUE TITLE
[GLPI 10.0.6] "Save current search" not displayed

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#13921]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello.
After upgrading from 10.0.5 to 10.0.6, the "Save current search" page is not displayed.
![image](https://user-images.githubusercontent.com/5680717/215499815-1b81ef02-d91e-44de-a981-ac29aa556141.png)

### Relevant log output

```shell
POST https://$SERVER$/front/undefined&url=%2Ffront%2Fcomputer.php%3Fis_deleted%3D0%26as_map%3D0%26browse%3D0%26criteria%255B0%255D%255Blink%255D%3DAND%26criteria%255B0%255D%255Bfield%255D%3Dview%26criteria%255B0%255D%255Bsearchtype%255D%3Dcontains%26criteria%255B0%255D%255Bvalue%255D%3D%26itemtype%3DComputer%26start%3D0%26_glpi_csrf_token%3D087429e8ed26b3d008c6936fe77acfb2eb8da90b633bff5afce6c90f63fda8be%26sort%255B%255D%3D1%26order%255B%255D%3DASC 404 (Not Found)
send @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
ajax @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
eval @ VM3332:378
obj.<computed> @ VM3332:180
E.fn.load @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
eval @ VM3332:780
obj.<computed> @ VM3332:180
(anonym) @ GenericView.js:105
dispatch @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
v.handle @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
trigger @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
(anonym) @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
each @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:14
each @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:14
trigger @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
trigger @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:198
show @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:198
(anonym) @ GenericView.js:107
dispatch @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
v.handle @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
```

### Steps To reproduce

1. Try to save a search for any asset

**Comment by trasher** [comment]
Please provide GLPI logs (files/_log/*.log)

**Comment by AndiMb** [comment]
Here are the logs https://datashare.tu-dresden.de/s/5f8iHifwNa7gMXj

**Comment by trasher** [comment]
I cannot open your link, but please provide relevant logs part only when the error apperas, and paste it here.

**Comment by cedric-anne** [comment]
I made many tests on saved searches yesterday and do not had any issue.

> `POST https://$SERVER$/front/undefined&url=%2Ffront%2Fcomputer.php%3Fis_deleted%3D0%26as_map%3D0%26browse%3D0%26criteria%255B0%255D%255Blink%255D%3DAND%26criteria%255B0%255D%255Bfield%255D%3Dview%26criteria%255B0%255D%255Bsearchtype%255D%3Dcontains%26criteria%255B0%255D%255Bvalue%255D%3D%26itemtype%3DComputer%26start%3D0%26_glpi_csrf_token%3D087429e8ed26b3d008c6936fe77acfb2eb8da90b633bff5afce6c90f63fda8be%26sort%255B%255D%3D1%26order%255B%255D%3DASC`

Did you patched your GLPI? Since #13572, parameters are passed into request body, so they are not supposed to be in URL query string.

**Comment by AndiMb** [comment]
Thanks for the replies.

I checked the logs but there is no entry with any error in the logs, when opening the empty search field. Only the cron.log has new entry, which should be normal.

I upgraded GLPI from 10.0.5 to 10.0.6. as described here: https://glpi-install.readthedocs.io/en/latest/update.html So I did not patch GLPI.

**Comment by cedric-anne** [comment]
Can you try to cleanup your browser cache to see if problem persists ?

**Comment by AndiMb** [comment]
I can't reproduce the same error from yesterday, but today the url is without parameter.
`POST https://$SERVER$/front/undefined&url=%2Ffront%2Fcomputer.php 404 (Not Found)
send @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
ajax @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
eval @ VM2226:378
obj.<computed> @ VM2226:180
E.fn.load @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
eval @ VM2226:780
obj.<computed> @ VM2226:180
(anonym) @ GenericView.js:105
dispatch @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
v.handle @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
trigger @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
(anonym) @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
each @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:14
each @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:14
trigger @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
trigger @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:198
show @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:198
(anonym) @ GenericView.js:107
dispatch @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25
v.handle @ base.min.js?v=3bdc0994daf21eb771c8e8ebdc145b13b043e92a:25`

**Comment by cedric-anne** [comment]
Trace of your error is weird, it seems to use a combination of minified files (i.e. `base.min.js`) and of non minified files (i.e. `GenericView.js`). Unless I miss something, it indicates that some JS files are missing.

Could your try to download the official release archive (https://github.com/glpi-project/glpi/releases/download/10.0.6/glpi-10.0.6.tgz), extract it, and overwite your GLPI files with extracted content ?

**Comment by AndiMb** [comment]
The hint to cleanup my browser cache solved the problem. I thought this case was already covered by checking with a second browser, but this obviously had already the same outdated data. 
Thanks for your help!

**Comment by cedric-anne** [comment]
Maybe a proxy stored JS files from a previous version.

I close this issue as your bug seems to be fixed.
