### ISSUE TITLE
Problem accessing the ticket of the same group

### ISSUE THREAD

**Issue by TestOrganigrammeBA** [glpi-project/glpi#13934]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

A user with the "Supervisor" profile belonging to the 'Mag BEB' group, cannot see the tickets of this group.

However, in the rights of the profile, the tick "See group tickets" is well ticked. See below :
![image](https://user-images.githubusercontent.com/91662361/215734137-8cc97326-dafc-410a-a14e-bf143c707de4.png)

### Steps To reproduce

1. Log in to an account with the "self-service" profile
2. Create a ticket
3. Log in to an account with the "Supervisor" profile
4. Browse the list of tickets, realize that the ticket created by the previous user does not appear in the list. While the requesting user belongs to the same group as the "Supervisor" user

### Your GLPI setup information

<html>
<body>

Server
--
Operating system: Linux srvweb 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 PHP 8.0.25 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, snmp, sockets, sodium, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at srvweb Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Server Software: Debian 10 	Server Version: 10.3.36-MariaDB-0+deb10u2 	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: glpiuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 PHP version (8.0.25) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (10.3.36) is supported. No files from previous GLPI version detected. The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server. Sessions configuration is secured. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/glpi/marketplace has been validated. Timezones seems loaded in database.

GLPI_ROOT: "/var/www/html/glpi" GLPI_CONFIG_DIR: "/var/www/html/glpi/config" GLPI_VAR_DIR: "/var/www/html/glpi/files" GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace" GLPI_USE_CSRF_CHECK: "1" GLPI_CSRF_EXPIRES: "7200" GLPI_CSRF_MAX_TOKENS: "100" GLPI_USE_IDOR_CHECK: "1" GLPI_IDOR_EXPIRES: "7200" GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?\|feed):\\/\\/[^@:]+(\\/.*)?$/"] GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org" GLPI_INSTALL_MODE: "TARBALL" GLPI_NETWORK_MAIL: "glpi@teclib.com" GLPI_NETWORK_SERVICES: "https://services.glpi-network.com" GLPI_MARKETPLACE_ALLOW_OVERRIDE: true GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true GLPI_USER_AGENT_EXTRA_COMMENTS: "" GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1" GLPI_AJAX_DASHBOARD: "1" GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: "0" GLPI_CENTRAL_WARNINGS: "1" GLPI_DOC_DIR: "/var/www/html/glpi/files" GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache" GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron" GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps" GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs" GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales" GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock" GLPI_LOG_DIR: "/var/www/html/glpi/files/_log" GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures" GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins" GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss" GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions" GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp" GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads" GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories" GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/" GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/" GLPI_I18N_DIR: "/var/www/html/glpi/locales" GLPI_VERSION: "10.0.6" GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97" GLPI_MARKETPLACE_PRERELEASES: false GLPI_MIN_PHP: "7.4.0" GLPI_MAX_PHP: "8.3.0" GLPI_YEAR: "2023"

htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/marketplace/pdf/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) psr/cache in (/var/www/html/glpi/vendor/psr/cache/src) league/csv in (/var/www/html/glpi/vendor/league/csv/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) symfony/cache in (/var/www/html/glpi/vendor/symfony/cache) html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src) symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector) symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler) twig/twig in (/var/www/html/glpi/vendor/twig/twig/src) twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81) symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)

Server: 'srvad1.ba.loc', Port: '389', BaseDN: 'DC=ba,DC=loc', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(sAMAccountName=*Admin*))(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', 		RootDN: 'adminad@ba.loc', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@relais-smtp.ipline.fr)

Name: 'photocop@boucheries-andre.fr' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert/notls}GLPI' Login: 'photocop@boucheries-andre.fr' Password: Yes

addressing           Name: Adressage IP                   Version: 3.0.1      State: Enabled                                  		Install Method: Marketplace 	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                  		Install Method: Marketplace 	news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                  		Install Method: Marketplace 	financialreports     Name: Arrêtés du parc                Version: 3.0.0      State: Enabled                                  		Install Method: Marketplace 	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                  		Install Method: Marketplace 	camerainput          Name: Camera Input                   Version: 2.0.2      State: Enabled                                  		Install Method: Marketplace 	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                  		Install Method: Marketplace 	positions            Name: Cartographie                   Version: 6.0.2      State: Not installed                            		Install Method: Marketplace 	fields               Name: Champs supplémentaires         Version: 1.20.0     State: Enabled                                  		Install Method: Marketplace 	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	costs                Name: Costs                          Version: 3.0.1      State: Enabled                                  		Install Method: Manual 	mydashboard          Name: Dashboard                      Version: 2.1.4      State: Enabled                                  		Install Method: Marketplace 	datainjection        Name: Data Injection                 Version: 2.12.1     State: Enabled                                  		Install Method: Marketplace 	consumables          Name: Demande de consommables        Version: 2.0.0      State: Enabled                                  		Install Method: Manual 	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                 		 Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.3     State: Installed / not activated                		Install Method: Marketplace 	gantt                Name: gantt                          Version: 1.0.1      State: Enabled                                  		Install Method: Marketplace 	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace 	geninventorynumber   Name: Génération de numéros d'invent Version: 2.8.3      State: Enabled                                 		 Install Method: Marketplace 	genericobject        Name: Gestion d'objets               Version: 2.14.1     State: Enabled                                  		Install Method: Marketplace 	order                Name: Gestion des commandes          Version: 2.10.0     State: Enabled                                  		Install Method: Marketplace 	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                  		Install Method: Marketplace 	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.1      State: Enabled                                  		Install Method: Marketplace 	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                  		Install Method: Marketplace 	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                  		Install Method: Marketplace 	jsaddons             Name: JS Addons                      Version: 2.0.0      State: Enabled                                  		Install Method: Marketplace 	metabase             Name: Metabase                       Version: 1.3.2      State: Enabled                                  		Install Method: Marketplace 	onetimesecret        Name: OneTimeSecret                  Version: 2.0.0      State: Enabled                                  		Install Method: Manual 	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                  		Install Method: Marketplace 	reports              Name: Rapports                       Version: 1.16.0     State: Enabled                                  		Install Method: Manual 	rgpdtools            Name: Utilitaires RGPD               Version: 1.0.0      State: Enabled                                  		Install Method: Manual 	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by cedric-anne** [comment]
Hi,

Users having `See group tickets` right will be able to see tickets that are assigned to one of their group. It does not permit to see tickets assigned to other groups members, even if user is supervisor of the group.

It may be an interesting enhancement, but it is not actually a bug.
