### ISSUE TITLE
Problem with GLPI mail notification attachments

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#13941]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3 / 10.0.6

### Bug description

Hello, dear friends.

By default, GLPI adds attachments to email ticket notifications when you add files to a ticket.
In the GLPI settings, you can only enable or disable the addition of attachments. And set the maximum file size (**not email attachments!**), which applies to the entire GLPI (for all types of documents). Also, by default, GLPI sends in the email notification not the last file that was added with the last comment, but absolutely all the files that are contained in the ticket and all the comments of the ticket.

At the same time, if we take into account that the maximum allowable size of attachments for many mail services is 25-30Mb, serious problems arise. The user adds a file or several files to the ticket (the size of the document allowed in the system), while the size of one file or several files in total exceeds the maximum attachment size. Mail notification could not be sent with error:

`SMTP Error: data not accepted.SMTP server error: DATA END command failed Detail: Error: message file too big; 1672145715-psOTjR2YE4Y1-iyI7pmqK SMTP code: 552 Additional SMTP info: 5.3.4`

Because of this, the task of sending email notifications completely hangs on when you try to send a notification with a large attachment to the mail, after that NO notifications by mail are sent.

**To solve this problem it would be correct to do:**

1) Adding to the mail notification only those file attachments that were added with the last comment. And not all on a ticket
2) The ability to separately configure the maximum size of attachment files for mail notifications (due to the limitation of the mail server)

### Steps To reproduce

Add to the application or comments to the application a file or several files with a total size greater than the mail server attachment size limit

**Comment by cedric-anne** [comment]
Hi,

We could improve this part.


> 1. Adding to the mail notification only those file attachments that were added with the last comment. And not all on a ticket

I think this kind of notification should be added at the notification level. Indeed, you may want sometimes to include the whole content/documents of the ticket (e.g. when the notification is sent to a supplier that does not have access to GLPI), but you may also want to send only the updated/added content when notification is send to an IT technician that is already in charge of the ticket. If configuration is done on notification level, then you can handle this by creating 2 different notifications with distinct config/recipient.

> 2. The ability to separately configure the maximum size of attachment files for mail notifications (due to the limitation of the mail server)

Indeed, such configuration could be added in the notifications settings easilly.

Even if it is not a bug, I would like to keep this issue open as I consider that this is an important improvement to do, at least to drastically reduce size of sent notifications (point 1).

**Comment by cedric-anne** [comment]
> Because of this, the task of sending email notifications completely hangs on when you try to send a notification with a large attachment to the mail, after that NO notifications by mail are sent.

The behaviour should have changed in GLPI 10.0.6 due to #13517. Indeed, if one of the email sending is crashing, it should process other notifications.

**Comment by ak47d** [comment]
Thank you so much for supporting these really useful changes. We hope to include them in the next releases.

**Comment by cedric-anne** [comment]
In GLPI 10.1, it will be possible to only attached documents related to the item that triggers the notification (see #14964), alors, there will be a new `add_document` event that could be used to send a notification containing only the document itself (see #14974).
