### ISSUE TITLE
Inventory not made (HTTP 500) when computer created before inventory without UUID

### ISSUE THREAD

**Issue by felag** [glpi-project/glpi#13940]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When computers are created without UUID and before inventory with agent, default ruleset prevents computer information to be imported.

Changing default rules to have rule "Computer update by serial." at first allows inventory.

### Steps To reproduce

Please note that steps to reproduced are highly linked with customer inventory data.

It appeared that after:
1. creation of a computer with name and serial (without UUID)
2. Installation glpi-agent on computer and launch of inventory

Then:
Inventory is not done and an error occur on PC, agent logs show:
92.168.205.38 - - [22/Nov/2022:11:15:46 +0100] "POST /glpi/plugins/glpiinventory/ HTTP/1.1" 500 - "-" "GLPI-Agent_v1.5-git95f66476"

Expected behavior would be:
When no UUID exists in already existing computer with serial but without UUID:

- 2 first default rules "Computer update by uuid" and "Computer update by serial+uuid" should not match,
- allowing rule "Computer update by serial" to match and computer inventory updates existing and adds missing inventory data

### Your GLPI setup information

* glpi-agent version 1.4 and nightly build were tested
* GLPI Inventory v1.0.5

**Comment by cedric-anne** [comment]
Hi,

Please try to reproduce using GLPI 10.0.6 and glpiinventory 1.1.0. Many fixes were made on inventory feature.

**Comment by trasher** [comment]
Default rules may not apply to every case, admin may have to change them to suit their needs.

For sure defaults does not apply to every possible case, but that's not a bug, just adapt your rules as you already did.
