### ISSUE TITLE
[RFE] better search option id management

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#1396]
To avoid duplicate issue: see #1385 

Changing all id (e.g; to use a string) would be very hard (also need to fix all the bookmark).

Proposal

Instead of 
```
      $tab[28]['table']                = 'glpi_infocoms';
      $tab[28]['field']                = 'bill';
     ..
```

Something like

```
      $tab[]['id']                   = 28;
      $tab[]['table']                = 'glpi_infocoms';
      $tab[]['field']                = 'bill';
     ..
```

To avoid API change, provides 2 methods

```
function getSearchOptionsNew () { /* new fonction */
     ...
}
function getSearchOptions () { /* old fonction */
    foreach(getSearchOptionsNew() as $opt) {
        $ret[$opt['id']] = $foo;
         unset($ret['id']);
    }
    return $ret;
}

```

Main benefit: we can check for duplicate in test suite.

**Comment by trasher** [comment]
The main idea is very interesting, if we could find out those duplicates in our tests suites... It would save a lot of time searching and fixing those ones!

**Comment by trasher** [comment]
Instead of 
```
      $tab[]['id']                   = 28;
      $tab[]['table']                = 'glpi_infocoms';
      $tab[]['field']                = 'bill';
```

Would probably be better to do:
```
$tab = [
   'id'      => 28,
   'table' => 'glpi_infocoms',
   'field'   => 'bill'
];
```

**Comment by btry** [comment]
Hi

How to deal this change in the plugins ?

**Comment by remicollet** [comment]
All functions will still use the getSearchOptions ;)
So a plugin (or any core class) will be able to use old function or switch to new one.

Only the new one will be testable.

**Comment by remicollet** [comment]
> Would probably be better to do:

No ;)

```
$tab[] = [
   'id'      => 28,
   'table' => 'glpi_infocoms',
   'field'   => 'bill'
];
```

**Comment by trasher** [comment]
:D

**Comment by trasher** [comment]
> How to deal this change in the plugins ?

Since `getSearchOptions` will continue to send exactly the same result as before; there should be no issue in the plugins (well, they'll cotinue to duplicate keys, that's all ;))

**Comment by trasher** [comment]
Changes has been done on the master branch; tests have been added, and so on!
