### ISSUE TITLE
License view

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1397]
Hello

Is it possible to add easily a column in license view giving the possibility to have users by department and if it is possible as well to click on it to sort by department.

Thank you for your answer

![capture](https://cloud.githubusercontent.com/assets/15144026/20889353/f2c29528-bb02-11e6-8256-42e34aec080b.PNG)

**Comment by satyan01** [comment]
Hello

up ?

**Comment by AnaelMobilia** [comment]
Hello,
Could you please give more details : do you want to have one more column "User Department" which should be sortable (in order to sort by department) or is it anything else ?

Regards,
Anael

**Comment by satyan01** [comment]
Hello

Yes just one column with the user's group permitting to sort users by group

Thank you

**Comment by AnaelMobilia** [comment]
@satyan01 could you please let this issue open (and instead close #1357) ?

Could you, please, provide me more information on the place where you found this view ? (if you have an url, it would be perfect ;-))
I wasn't able to found it :-/

Thanks !

**Comment by satyan01** [comment]
Hello

the view

http://itsm/glpi/front/softwarelicense.form.php?id=21

**Comment by AnaelMobilia** [comment]
I can't affect licence to users, only computers.

Have you a specific plugin installed on your GLPI ?
If no, could you, please, provide me the (left menu) item name you used ?

**Comment by satyan01** [comment]
Hello

FP Software	1.1.0	GPLv2+	Enabled	Future Processing

**Comment by AnaelMobilia** [comment]
@satyan01 
The ability to link a licence to an user is provided by your plugin fpsoftware.
You have already [open an issue on the plug-in github repository.](https://github.com/FutureProcessing/glpi-fpsoftware/issues/6)

Here, is managed __only__ GLPI core, please go to the plugin repository.

Thanks,
Anael

This issue can be closed for me.

**Comment by trasher** [comment]
Thanks @AnaelMobilia :)

**Comment by satyan01** [comment]
I did it, thx
