### ISSUE TITLE
"Skip remaining rules" does not work if Technician (or Technician group) Assign in Action

### ISSUE THREAD

**Issue by Viktor74Yl** [glpi-project/glpi#13981]
10.0.6
Rule testing is now working correctly, thanks for the fix.

"Skip remaining rules" does not work **if Technician (or Technician group) Assign** in Action
Ticket to TEST-CATEGORY, requester in TEST-LOCATION
```
TEST-RULE-1
Category - Complete name is TEST-CATEGORY
Technician Assign Support1
Skip remaining rules Assign Yes

TEST-RULE-2	
Requester location is TEST-LOCATION
Technician Assign Support2

result of created ticket - 
Assigned to
Support1
Support2

When **testing** the same rules, only Support1 is assigned
```

Thus if for example Urgency Assign - that the "Skip remaining rules" works.
```
TEST-RULE-1
Category - Complete name is TEST-CATEGORY
Urgency Assign Very high
Skip remaining rules Assign Yes
	
TEST-RULE-2
Requester location is TEST-LOCATION
Technician Assign Support2

result of created ticket - 
Urgency Very high
```

_Originally posted by @Viktor74Yl in https://github.com/glpi-project/glpi/issues/13824#issuecomment-1407065690_

**Comment by cedric-anne** [comment]
Hi,

I am not able to reproduce the issue. Also, when using `Assign` in a rule, it replaces the actor added by previous rule.

Test 1 results:
```
RULE-1
Category / is / test
Technician / assign / user1
Skip remaining rules / assign / Yes

RULE-2
Category / is / test
Technician / assign / user2

-> ticket is assigned to user1
```

Test 2 results:
```
RULE-1
Category / is / test
Technician / assign / user1

RULE-2
Category / is / test
Technician / assign / user2

-> ticket is assigned to user2
```

Maybe there is something else that add an additional actor on your ticket. Could you reproduce with no active plugins?

**Comment by Viktor74Yl** [comment]
Hi,
I also can't reproduce the problem by my own rules in 1.0.7
Problem solved
