### ISSUE TITLE
GLPI-Inventory doesnt show component changes in logs

### ISSUE THREAD

**Issue by ilnurxxx** [glpi-project/glpi#13984]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

GLPI inventory with glpi-agent updates my asset (e.g. components), but does not show changes in logs

For the test, I uploaded a json file with the value **memories_capacity**: 2048, then uploaded with value 4096
The component changed from 2048 to 4096, but the change was not displayed in the log

### Page URL

http://glpi-server/glpi/front/computer.form.php

### Steps To reproduce

1. Inventory the asset
2. Go to the components tab in the asset card and see the value (e.g. RAM)
3. Change the hardware characteristics of the asset (e.g. add memory) and Inventory the asset again
4. Look at the components value (e.g. RAM) and check for a change in the logs

### Your GLPI setup information

GLPI 10.0.1 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:ru_RU

**Comment by cedric-anne** [comment]
Hi,

Many fixes were made since 10.0.1 on inventory feature. Please check if problem persist in GLPI 10.0.6.

**Comment by ilnurxxx** [comment]
Hi,
I checked it in version 10.0.6
The problem is also present

**Comment by stonebuzz** [comment]
Hi @ilnurxxx 
can you try this -> https://github.com/glpi-project/glpi/pull/14017

Then go to your computer (component tab)

and click here to see update (from history tab)

![image](https://user-images.githubusercontent.com/7335054/217172570-b9f292b2-8fb8-48d6-b50f-c0ae31e6041d.png)

![image](https://user-images.githubusercontent.com/7335054/217172620-427af6f6-b7f3-4961-bb59-aa70325d49f8.png)

 

Best regards

**Comment by ilnurxxx** [comment]
@stonebuzz 
Thank you very much <3
It really helped me!

Is it possible to apply this fix for the old version 10.0.1?

**Comment by stonebuzz** [comment]
Many changes have been done in inventory.
I advise you update your GLPI to latest version (at least for security fixes) and apply patch.

Best regards

**Comment by cedric-anne** [comment]
> Is it possible to apply this fix for the old version 10.0.1?

Do you have any reason to not upgrade to GLPI 10.0.6? I make no judgment on this point, but as many users seem reluctant to update their GLPI, I would like to know the reasons, to possibly find solutions to the problems encountered.

**Comment by ilnurxxx** [comment]
@cedric-anne 
I have several reasons not to update GLPI, namely:
1) The complexity of the process, did not find the update process instruction
2) Fear of losing data
3) Fear of losing the data filled in in the plugin fields

**Comment by cedric-anne** [comment]
> @cedric-anne I have several reasons not to update GLPI, namely:
> 
> 1. The complexity of the process, did not find the update process instruction

Official documentation is here: https://glpi-install.readthedocs.io/en/latest/update.html

> 2. Fear of losing data

There is no reason to have data lost during GLPI update.

Anyway, you should always to do some tests on a preproduction server when updating your GLPI version, so you can ensure that migration process is not failing.

> 3. Fear of losing the data filled in in the plugin fields

GLPI update does not affect plugins data, so unless you do an update of the plugin, there is no reason to loose this data.

**Comment by ilnurxxx** [comment]
@cedric-anne Thank you for this comprehensive explanation.
@stonebuzz Thank you for your contribution to GLPI.

**Comment by trasher** [comment]
Will be closed automatically when PR will be merged

**Comment by pjordanovic** [comment]
Hello,

**Comment by trasher** [comment]
First, test latest stable and then open a new issue with all requested details.
