### ISSUE TITLE
Network task inventory not working for somes switchs

### ISSUE THREAD

**Issue by cencen99** [glpi-project/glpi#13980]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

The network inventory is not working properly for some switches. There is only one available port: management.
I have errors in the SQL error log: Error:
-Out of range value for column 'netmask_3' at row 1 for glpi_ipnetworks
-Error: Out of range value for column 'binary_0' at row 1 for glpi_ipaddresses

I expect to get all port inventoried.

*IP and Mac address were modified in log

[php-errors.log](https://github.com/glpi-project/glpi/files/10560244/php-errors.log)
[sql-errors.log](https://github.com/glpi-project/glpi/files/10560245/sql-errors.log)

### Relevant log output

```shell
[2023-02-01 21:35:47] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipnetworks` (`name`, `gateway`, `entities_id`, `version`, `address`, `address_0`, `address_1`, `address_2`, `address_3`, `netmask`, `netmask_0`, `netmask_1`, `netmask_2`, `netmask_3`, `gateway_0`, `gateway_1`, `gateway_2`, `gateway_3`, `ipnetworks_id`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('192.168.107.80/255.255.255.248 - 192.168.107.86', '192.168.107.86', '0', '4', '192.168.107.80', '0', '0', '65535', '183069520', '255.255.255.248', '4294967295', '4294967295', '4294967295', '-8', '0', '0', '65535', '183069526', '0', '1', '192.168.107.80/255.255.255.248 - 192.168.107.86', '2023-02-01 21:35:47', '2023-02-01 21:35:47')
  Error: Out of range value for column 'netmask_3' at row 1
  Backtrace :
  src\DBmysql.php:1320                               
  src\CommonDBTM.php:721                             DBmysql->insert()
  src\CommonDBTM.php:1326                            CommonDBTM->addToDB()
  src\Inventory\Asset\InventoryNetworkPort.php:243   CommonDBTM->add()
  src\Inventory\Asset\InventoryNetworkPort.php:120   Glpi\Inventory\Asset\MainAsset->handleIpNetworks()
  src\Inventory\Asset\MainAsset.php:766              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace\glpiinventory\front\communication.php:72 include_once()
  marketplace\glpiinventory\index.php:45             include_once()
  {"user":"inventory@GLPI"} 
[2023-02-01 21:35:47] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipaddresses` (`items_id`, `itemtype`, `name`, `is_dynamic`, `mainitemtype`, `mainitems_id`, `version`, `binary_0`, `binary_1`, `binary_2`, `binary_3`, `entities_id`) VALUES ('85899', 'NetworkName', 'fe80::c82:6714:17d4:741c', '1', 'Computer', '3191', '6', '-25165824', '0', '209872660', '399799324', '0')
  Error: Out of range value for column 'binary_0' at row 1
  Backtrace :
  src\DBmysql.php:1320                               
  src\CommonDBTM.php:721                             DBmysql->insert()
  src\CommonDBTM.php:1326                            CommonDBTM->addToDB()
  src\Inventory\Asset\InventoryNetworkPort.php:328   CommonDBTM->add()
  src\Inventory\Asset\InventoryNetworkPort.php:494   Glpi\Inventory\Asset\MainAsset->addIPAddresses()
  src\Inventory\Asset\InventoryNetworkPort.php:121   Glpi\Inventory\Asset\MainAsset->handleUpdates()
  src\Inventory\Asset\MainAsset.php:766              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace\glpiinventory\front\communication.php:72 include_once()
  marketplace\glpiinventory\index.php:45             include_once()
  {"user":"inventory@GLPI","mem_usage":"0.006\", 6.09Mio)"} 
[2023-02-01 21:36:04] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipnetworks` (`name`, `gateway`, `entities_id`, `version`, `address`, `address_0`, `address_1`, `address_2`, `address_3`, `netmask`, `netmask_0`, `netmask_1`, `netmask_2`, `netmask_3`, `gateway_0`, `gateway_1`, `gateway_2`, `gateway_3`, `ipnetworks_id`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('192.168.4.0/255.255.255.0 - 192.168.4.254', '192.168.4.254', '0', '4', '192.168.4.0', '0', '0', '65535', '176489472', '255.255.255.0', '4294967295', '4294967295', '4294967295', '-256', '0', '0', '65535', '176489726', '0', '1', '192.168.4.0/255.255.255.0 - 192.168.4.254', '2023-02-01 21:36:03', '2023-02-01 21:36:03')
  Error: Out of range value for column 'netmask_3' at row 1
  Backtrace :
  src\DBmysql.php:1320                               
  src\CommonDBTM.php:721                             DBmysql->insert()
  src\CommonDBTM.php:1326                            CommonDBTM->addToDB()
  src\Inventory\Asset\InventoryNetworkPort.php:243   CommonDBTM->add()
  src\Inventory\Asset\InventoryNetworkPort.php:120   Glpi\Inventory\Asset\MainAsset->handleIpNetworks()
  src\Inventory\Asset\MainAsset.php:766              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace\glpiinventory\front\communication.php:72 include_once()
  marketplace\glpiinventory\index.php:45             include_once()
  {"user":"inventory@GLPI"} 
[2023-02-01 21:36:04] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipaddresses` (`items_id`, `itemtype`, `name`, `is_dynamic`, `mainitemtype`, `mainitems_id`, `version`, `binary_0`, `binary_1`, `binary_2`, `binary_3`, `entities_id`) VALUES ('85748', 'NetworkName', 'fefe::fefe0:f0f0:a3a3:d7c', '1', 'Computer', '3225', '6', '-25165824', '0', '1353773278', '-1551889028', '0')
  Error: Out of range value for column 'binary_0' at row 1
  Backtrace :
  src\DBmysql.php:1320                               
  src\CommonDBTM.php:721                             DBmysql->insert()
  src\CommonDBTM.php:1326                            CommonDBTM->addToDB()
  src\Inventory\Asset\InventoryNetworkPort.php:328   CommonDBTM->add()
  src\Inventory\Asset\InventoryNetworkPort.php:494   Glpi\Inventory\Asset\MainAsset->addIPAddresses()
  src\Inventory\Asset\InventoryNetworkPort.php:121   Glpi\Inventory\Asset\MainAsset->handleUpdates()
  src\Inventory\Asset\MainAsset.php:766              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace\glpiinventory\front\communication.php:72 include_once()
  marketplace\glpiinventory\index.php:45             include_once()
  {"user":"inventory@GLPI","mem_usage":"0.004\", 6.29Mio)"} 
[2023-02-01 21:36:22] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipnetworks` (`name`, `gateway`, `entities_id`, `version`, `address`, `address_0`, `address_1`, `address_2`, `address_3`, `netmask`, `netmask_0`, `netmask_1`, `netmask_2`, `netmask_3`, `gateway_0`, `gateway_1`, `gateway_2`, `gateway_3`, `ipnetworks_id`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('192.168.1.0/255.255.254.0 - 192.168.1.251', '192.168.1.251', '0', '4', '192.168.1.0', '0', '0', '65535', '176488448', '255.255.254.0', '4294967295', '4294967295', '4294967295', '-512', '0', '0', '65535', '176488699', '0', '1', '192.168.1.0/255.255.254.0 - 192.168.1.251', '2023-02-01 21:36:22', '2023-02-01 21:36:22')
  Error: Out of range value for column 'netmask_3' at row 1
  Backtrace :
  src\DBmysql.php:1320                               
  src\CommonDBTM.php:721                             DBmysql->insert()
  src\CommonDBTM.php:1326                            CommonDBTM->addToDB()
  src\Inventory\Asset\InventoryNetworkPort.php:243   CommonDBTM->add()
  src\Inventory\Asset\InventoryNetworkPort.php:120   Glpi\Inventory\Asset\MainAsset->handleIpNetworks()
  src\Inventory\Asset\MainAsset.php:766              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace\glpiinventory\front\communication.php:72 include_once()
  marketplace\glpiinventory\index.php:45             include_once()
  {"user":"inventory@GLPI"} 
[2023-02-01 21:36:55] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\glpi\src\DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ipnetworks` (`name`, `gateway`, `entities_id`, `version`, `address`, `address_0`, `address_1`, `address_2`, `address_3`, `netmask`, `netmask_0`, `netmask_1`, `netmask_2`, `netmask_3`, `gateway_0`, `gateway_1`, `gateway_2`, `gateway_3`, `ipnetworks_id`, `level`, `completename`, `date_creation`, `date_mod`) VALUES ('192.168.1.0/255.255.254.0 - 192.168.1.251', '192.168.1.251', '0', '4', '192.168.1.0', '0', '0', '65535', '176488448', '255.255.254.0', '4294967295', '4294967295', '4294967295', '-512', '0', '0', '65535', '176488699', '0', '1', '192.168.1.0/255.255.254.0 - 192.168.1.251', '2023-02-01 21:36:55', '2023-02-01 21:36:55')
  Error: Out of range value for column 'netmask_3' at row 1
  Backtrace :
  src\DBmysql.php:1320                               
  src\CommonDBTM.php:721                             DBmysql->insert()
  src\CommonDBTM.php:1326                            CommonDBTM->addToDB()
  src\Inventory\Asset\InventoryNetworkPort.php:243   CommonDBTM->add()
  src\Inventory\Asset\InventoryNetworkPort.php:120   Glpi\Inventory\Asset\MainAsset->handleIpNetworks()
  src\Inventory\Asset\MainAsset.php:766              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace\glpiinventory\front\communication.php:72 include_once()
  marketplace\glpiinventory\index.php:45             include_once()
  {"user":"inventory@GLPI"}
```

### Page URL

.

### Steps To reproduce

 Launch glpi task netinventory on network

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 ( => C:\inetpub\wwwroot\glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT GLPI 10.0 build 14393 (Windows Server 2016) i586
PHP 7.4.13 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sodium, standard, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip,
	zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.21
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: glpidb_user@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (7.4.13) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.21) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated.
Write access to C:\inetpub\wwwroot\glpi/config has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated.
Write access to C:\inetpub\wwwroot\glpi/files has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated.
The following directories should be placed outside "C:\inetpub\wwwroot\glpi":
‣ "C:\inetpub\wwwroot\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\inetpub\wwwroot\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\inetpub\\wwwroot\\glpi"
GLPI_CONFIG_DIR: "C:\\inetpub\\wwwroot\\glpi/config"
GLPI_VAR_DIR: "C:\\inetpub\\wwwroot\\glpi/files"
GLPI_MARKETPLACE_DIR: "C:\\inetpub\\wwwroot\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "C:\\inetpub\\wwwroot\\glpi/files"
GLPI_CACHE_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_cache"
GLPI_CRON_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_cron"
GLPI_DUMP_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_locales"
GLPI_LOCK_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_lock"
GLPI_LOG_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_log"
GLPI_PICTURE_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_plugins"
GLPI_RSS_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_rss"
GLPI_SESSION_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_sessions"
GLPI_TMP_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\inetpub\\wwwroot\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "C:\\inetpub\\wwwroot\\glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (C:\inetpub\wwwroot\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (C:\inetpub\wwwroot\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\wwwroot\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (C:\inetpub\wwwroot\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\wwwroot\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\wwwroot\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\wwwroot\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\wwwroot\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\wwwroot\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\wwwroot\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\wwwroot\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\wwwroot\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\wwwroot\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\wwwroot\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\wwwroot\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\wwwroot\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\wwwroot\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\wwwroot\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (C:\inetpub\wwwroot\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (C:\inetpub\wwwroot\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\wwwroot\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\wwwroot\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\wwwroot\glpi\vendor\psr\cache\src)
league/csv in (C:\inetpub\wwwroot\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\wwwroot\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\wwwroot\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\wwwroot\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\wwwroot\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\wwwroot\glpi\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\wwwroot\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\inetpub\wwwroot\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\inetpub\wwwroot\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\wwwroot\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\wwwroot\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (C:\inetpub\wwwroot\glpi\vendor\symfony\polyfill-php80)
symfony/polyfill-php81 in (C:\inetpub\wwwroot\glpi\vendor\symfony\polyfill-php81)
symfony/polyfill-php82 in (C:\inetpub\wwwroot\glpi\vendor\symfony\polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://dc.company.com', Port: '636', BaseDN: 'OU=Utilisateurs,OU=service,DC=company,DC=com', Connection
		filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'glpi@aurar-run.com', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@192.168.5.116)

</details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	webapplications      Name: Applications Web               Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	badges               Name: Badges                         Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.20.0     State: Enabled                                 
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Compteurs Imprimantes          Version: 1.7.0      State: Not installed                           
		Install Method: Manual
	credit               Name: Crédits                        Version: 1.11.3     State: Installed / not activated               
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.1.4      State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.10.1     State: Installed / not activated               
		Install Method: Manual
	purchaserequest      Name: Demande d'achat                Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	dataflows            Name: Flux de données                Version: 2.2.18     State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 9.5+4.2    State: Not installed                           
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.11.1     State: Installed / not activated               
		Install Method: Manual
	order                Name: Gestion des commandes          Version: 2.7.6      State: Not installed                           
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	tasklists            Name: Liste des tâches               Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	mailbehaviours       Name: Mail Behaviours                Version: 1.0.3      State: Installed / not activated               
		Install Method: Manual
	metademands          Name: Meta-Demandes                  Version: 3.2.13     State: To update                               
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Marketplace
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	typology             Name: Typologies                     Version: 2.7.2      State: Installed / not activated               
		Install Method: Manual

</pre></details>

### Anything else?

Already tryed with a fresh installation with debian 11, apache2, mariadb: still no inventory from some switches with same error.

**Comment by stonebuzz** [comment]
Hi @cencen99 
Can you provide inventory file, to try to reproduce on my side?

Best regards

**Comment by stonebuzz** [comment]
Are you on 32bit OS?

**Comment by cencen99** [comment]
``

> Hi @cencen99 Can you provide inventory file, to try to reproduce on my side?
> 
> Best regards

[netinv.xml.log](https://github.com/glpi-project/glpi/files/10561013/netinv.xml.log)

**Comment by cencen99** [comment]
> Are you on 32bit OS?

64 bit

**Comment by cencen99** [comment]
i dont understand, i can import the file on fresh glpi installation (debian 11 apache2), but on my production environnement, i have this error: 
Le fichier n'a pas été importé: JSON does not validate. Violations: Integer expected, null received at #->properties:content->properties:network_ports->items[9]:9->properties:ifoutbytes

**Comment by cencen99** [comment]
> Are you on 32bit OS?

Windows 64 bit, IIS 10, php x86

**Comment by stonebuzz** [comment]
I do not reproduce issue with your file,
however if this one has been modified for security reasons, I can't say that everything is OK.

Is it possible to send me (via my professional email address) the XML file in question (unaltered)?

Best regards

**Comment by cencen99** [comment]
Thank you very much for your help. The problem was the use of php x86. I switched to php x64 and everything is working correctly.
