### ISSUE TITLE
License manager

### ISSUE THREAD

**Issue by fgendorf** [glpi-project/glpi#1398]
Hi, when I read that new version 9.1 the license could be managed separated, I imagine that license would be independent, and could be assigned to multiples software, example:

When I buy a software Microsoft Open License, I can use older version with backward compatibility like Visual Studio 2015, 2012, 2010, so the software Visual Studio 2010, Visual Studio 2012, etc can use the same license. With Windows license OEM, from Dell, HP, etc, when I buy I can choose backward compatibility too, so my license is Windows 10 pro, but in use is a Windows 7 Pro.

Is it not a good idea create a relation license:software 1:N ?
That way is possible link one license to multiples software.

**Comment by pnikrat** [comment]
Hello.
So far I am amazed by the project and its scale.

I would welcome the feature @fgendorf describes as well, so I second that.

**Comment by oliveira-esss** [comment]
Hi there,

That feature would be very helpful indeed.

I have another situation where I would like very much to have a 1:N relation between license and software. The example is "Adobe Creative Cloud All Apps" license which grants me access to different software (e. g. Adobe Dreamweaver CC 2017, Adobe Premiere Pro CC 2017, Adobe Photoshop CC 2017, etc).

Can we have that feature implemented anytime soon?

**Comment by fgendorf** [comment]
That is not the same issue, allow same license many times to same computer is not like more than one software per license....
