### ISSUE TITLE
Paste image issue

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#1399]
Hello, 
 when a user paste an image from the clipboard in the "Drag and Drop or paste image" area, he get back an "item not found" error. this happen only when using Internet Explorer 11 or 10 (with Edge it works).

![senza nome](https://cloud.githubusercontent.com/assets/7987648/20895251/f508274c-bb18-11e6-9c61-f47b6ca11e6b.jpg)

it looks like a tinymce issue but I didn't find anything around

**Comment by orthagh** [comment]
Hello @Giudy 

We are working on a revamp of this feature for the next version.
See https://github.com/TECLIB/glpi/pull/14

The interface you mention will disappear soon (for a new ui to drop and paste from clipboard your pictures)

**Comment by trasher** [comment]
Fixed in 785fea3cecfdf582daab845672a1f8b127b4c38c
