### ISSUE TITLE
Bulk delete unmanaged devices

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#13993]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Bulk delete of unmanaged devices in the trash bin is not working, while individual delete works.

### Steps To reproduce

1. go to unmanaged devices
2. delete devices
3. go in trash bin
4. mass-select and bulk delete devices
5. devices stay in trash, but expected to be cleaned up

**Comment by trasher** [comment]
I cannot put unmanaged devices in trashbin; only permanent delete is available via the form or massive actions

**Comment by liedekef** [comment]
Indeed, when I checked now it is indeed not possible. However, it was like this last week, since I do have a "trash bin" option for unmanaged devices and when I look in that trash bin, I see a number of trashed devices. So must be something weird going on, maybe because I first deleted managed network devices and that messed up the bulk-action menu on the "unmanaged devices" then? I'm going to try and reproduce.

**Comment by cedric-anne** [comment]
IMHO, as for refused equipements, we should probably have a dedicated right for unmanaged devices, with READ, UPDATE, DELETE and PURGE options (CREATE should probably not proposed as it does not make sense to manually create unmanaged devices).
