### ISSUE TITLE
Personal View on Home page when Results to display on home page = 0

### ISSUE THREAD

**Issue by calidadcarm** [glpi-project/glpi#13995]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

When an user configure: Results to display on home page = 0 

Personal View on Home page show all tickets in GLPI 9.4.11 

When the number of tickets is very hight the browser is colapsed

![imagen](https://user-images.githubusercontent.com/50906293/216571117-d44e1419-e210-4413-996c-c0d5f2e913ad.png)

but  on GLPI 9.4.6 only show a head with the number of tickets and a link

![imagen](https://user-images.githubusercontent.com/50906293/216568602-d987f97b-0196-4fd8-b149-499b49197b93.png)

Has this functionality been changed on purpose or is it a bug in this version?

### Page URL

glpi/front/central.php

### Steps To reproduce

start glpi
Show Personal View

**Comment by trasher** [comment]
GLPI 9.5 is no longer supported, consider upgrading to latest stable

**Comment by calidadcarm** [comment]
GLPI 10 have the same behavior

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.

The `0` value is not handled as expected, probably since GLPI 9.5.3 (commit c006e7fff3be07796ad9cd26c11864f0e12c7c34).
