### ISSUE TITLE
[9.1RC2][0.90][0.85]Bug with "<" in ticket description

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#140]
When creating a ticket ( helpdesk, collector) with description :
"le temps de réponse passe de < 1ms à < 200ms" it is ok
but when no spaces between < and next caracter then description is truncated :
"le temps de réponse passe de <1ms à <200ms" ->bug

ver 0.85.4 or On line  0.90 DEMO ->bug
in 0.83.8 it seems ok

**Comment by ladenree76000** [comment]
when looking the descriptions, it is truncated, but when mouse over "information" the full text is displayed in the "pop up window".

**Comment by orthagh** [comment]
with rich text enabled ?

**Comment by ladenree76000** [comment]
[0.90-RC1 on WAMP server browser: chrome] rich text diabled, typing in description " temps de réponse passe de <8ms à>400ms" displays "temps de réponse passe de 400ms"  tooltip text is OK

rich text enabled, typing in description " temps de réponse passe de <8ms à plus de >400ms " displays 
temps de réponse passe de <8ms plus="" de="">400ms 
( à disappeard, = and double quote added)
  tooltip text is OK

(same behaviour on line demo ticket 27425)

**Comment by orthagh** [comment]
Can't find where's bug occurs on http://demo.glpi-project.org/front/ticket.form.php?id=27425
Could you attach a screenshot ?

**Comment by ladenree76000** [comment]
today, the ticket description is not truncated anymore on onlineDemo. ! (with FF & IE8 OK)
Sure it was few days earlier.
rich text is disabled on on line demo.

**Comment by ladenree76000** [comment]
this is a screenshot showing tooltip text & description looking different.
ver 0.85.4. browser MS EDGE (but same with IE8, chrome, FF)
this was the same on on line demo but not any more.

![image](https://cloud.githubusercontent.com/assets/13557254/10262482/e481cf32-69c9-11e5-8c66-735ddfbb3aa5.png)

**Comment by ladenree76000** [comment]
0.90 RC2 : 
![image](https://cloud.githubusercontent.com/assets/13557254/10263582/8f7fb718-69f3-11e5-8fbf-0da95f385cf3.png)

**Comment by orthagh** [comment]
I worked 2 hours on this bug 
Can't find a configuration to avoid the first < to be dectected as a html tag.

Currently trying a double encoding but I'm not confident

**Comment by yllen** [comment]
I try to fix in ONLY for 0.85 for the moment.
Can you test it?
Be careful: this correction work only for new text. You must correct description or create a new ticket.
If OK for you, i'll do the same correction for 0.90

**Comment by orthagh** [comment]
@ladenree76000 have you test this correction ?

**Comment by ladenree76000** [comment]
no, since my 0.85 is now upgraded to 0.90 (test & prod).

**Comment by orthagh** [comment]
@ladenree76000, You could even so test the 0.85 patch on your 0.90 test instance : 
https://github.com/glpi-project/glpi/commit/a1f2e1e5f78f414d720a3ec5d940d98eb7906117.patch

```
patch -p1 < /tmp/a1f2e1e5f78f414d720a3ec5d940d98eb7906117.patch 
patching file inc/ticket.class.php
Hunk #1 succeeded at 4226 (offset 129 lines).
Hunk #2 FAILED at 4110.
Hunk #3 succeeded at 6036 with fuzz 1 (offset 70 lines).
1 out of 3 hunks FAILED -- saving rejects to file inc/ticket.class.php.rej
patching file inc/toolbox.class.php
Hunk #1 succeeded at 327 (offset 4 lines).
Hunk #2 succeeded at 351 (offset 4 lines).
```

"Hunk #2 FAILED" is nothing, a change in a space who doesn't affect the current correction

**Comment by orthagh** [comment]
@yllen, in the end, if tested on my instance, no changes.

I think the issue isn't in db storage but more a tinyMCE bug.
If i save directly in db the sentence "temps de réponse passe de <8ms à plus de >400ms", issue apppears.

It's precisly at "<8" who is detected as opening html tag...
I can't figure a fix for this (maybe a preg_replace on <([0-9]1),  <$1 )

**Comment by yllen** [comment]
Orthagh,
Comme je l'ai précisé, il n'y a pas de solution pour les données mal enregistrées. Mais si tu corriges dans ta description en remettant ce qui est correct, l'affichage sera OK.
Testé chez moi OK, testé par Remi OK également

**Comment by orthagh** [comment]
Effectivement, il reste cependant encore une problèmatique : 
![image](https://cloud.githubusercontent.com/assets/418844/10691857/f0ffa6da-798c-11e5-922d-bddc7cbbe950.png)

la description se voit ajouter des <p> </p>
(j'ai copié le même texte dans le titre et la description)

**Comment by yllen** [comment]
ben moi j'ai plus le problème
![richtext](https://cloud.githubusercontent.com/assets/12936722/10698623/46d52e70-79b2-11e5-8ec1-aba49125d1c0.png)

**Comment by ladenree76000** [comment]
I would be pleased to help by testing this patch, but i dont know how to apply on my wamp server ;-(

**Comment by orthagh** [comment]
ok, @yllen, reporte sur le master, on fera un test final dessus et on pourra fermer je pense.

**Comment by ladenree76000** [comment]
installer le master pour tester :  ça je sais faire ;-}

**Comment by orthagh** [comment]
cherry-picked sur le master.

**Comment by orthagh** [comment]
j'ouvre à nouveau.
Je reproduis à nouveau le <p>...</p>, @tsmr aussi il me semble.

Avec le rich text activé, ça se produit lors de la création du ticket

**Comment by yllen** [comment]
tu vois les <p> lors de la création ?

**Comment by orthagh** [comment]
J'ai "revert" les corrections pour l'instant pour ne plus retarder la sortie de la 0.90.1 pour le moment.

J'ai une correction de disponible que j'appliquerais après la release pour faire refaire un cycle de test complet :
```diff
diff --git a/inc/html.class.php b/inc/html.class.php
index aa59328..196c368 100644
--- a/inc/html.class.php
+++ b/inc/html.class.php
@@ -100,7 +100,7 @@ class Html {
    // Problem with this regex : may crash
    //   $value = preg_replace("/ +/u", " ", $value);
       // Revert back htmlawed &amp; -> &
-      $value = str_replace("&amp;", "&", $value);
+      //$value = str_replace("&amp;", "&", $value);
       $value = str_replace(array("\r\n", "\r"), "\n", $value);
       $value = preg_replace("/(\n[ ]*){2,}/", "\n\n", $value, -1);
 
diff --git a/inc/ticket.class.php b/inc/ticket.class.php
index 1ddee89..7ffda8a 100644
--- a/inc/ticket.class.php
+++ b/inc/ticket.class.php
@@ -1373,8 +1373,7 @@ class Ticket extends CommonITILObject {
       if (isset($input["content"])) {
          $input["content"] = preg_replace('/\\\\r\\\\n/',"\n",$input['content']);
          $input["content"] = preg_replace('/\\\\n/',"\n",$input['content']);
-         $input["content"] = Toolbox::clean_cross_side_scripting_deep(Html::clean($input["content"]));
-      }
+         $input["content"] = Html::clean($input["content"]);
 
       $input = $rules->processAllRules(Toolbox::stripslashes_deep($input),
                                        Toolbox::stripslashes_deep($input),
diff --git a/inc/toolbox.class.php b/inc/toolbox.class.php
index d4def61..98ab83d 100644
--- a/inc/toolbox.class.php
+++ b/inc/toolbox.class.php
@@ -324,6 +324,9 @@ class Toolbox {
       $in  = array('<', '>');
       $out = array('&lt;', '&gt;');
 
+      $in  = array('&lt;', '&gt;', '<', '>');
+      $out = array('&amp;lt;', '&amp;gt;', '&lt;', '&gt;');
+
       $value = ((array) $value === $value)
                   ? array_map(array(__CLASS__, 'clean_cross_side_scripting_deep'), $value)
                   : (is_null($value)
@@ -348,6 +351,9 @@ class Toolbox {
       $in  = array('<', '>');
       $out = array('&lt;', '&gt;');
 
+      $in  = array('&lt;', '&gt;', '<', '>');
+      $out = array('&amp;lt;', '&amp;gt;', '&lt;', '&gt;');
+
       $value = ((array) $value === $value)
                   ? array_map(array(__CLASS__, 'unclean_cross_side_scripting_deep'), $value)
                   : (is_null($value)
```

**Comment by ladenree76000** [comment]
issue still exists in 0.90.1

**Comment by orthagh** [comment]
voir le commentaire du dessus : https://github.com/glpi-project/glpi/issues/140#issuecomment-160164295

**Comment by ladenree76000** [comment]
je n'avais pas bien compris Ok.
je vois bien que 3 classes ont été modifiées, je suis prêt à tester mais je ne sais pas comment passer les modifs sur mon serveur.  je vais récupérer les 3 classes modifiées.

**Comment by orthagh** [comment]
Ce sera dans le master et la branche bugfixes rapidement (ce soir ou demain
matin).

Le 30 novembre 2015 17:22, ladenree76000 <notifications@github.com> a écrit
:

**Comment by orthagh** [comment]
Pour préciser le retour en arrière (et l'absence de la correction en 0.90.1), nous avons constaté de nombreuse régressions (pire que le problème initial) suite à la première correction.
J'ai testé pas mal de chose mais cela retardait encore la sortie.

Cette dernière correction (attaché à cette issue) devrait être bonne mais doit être testée plus longtemps pour être sur de ne pas ajouter d'autres régressions.

**Comment by ladenree76000** [comment]
avec les modifications proposées je ne remarque plus d'erreur d'affichage de la description des tickets 
mode rich text activé tickets créés par saisir interface, collecteur, ou copier/coller d'emails reçus hors collecteur.
.
Cependant pour les tickets créés par collecteur (uniquement ceux là), lors de la récupération du ticket la description contient l'intégralité des balises html 
![gui_ticket](https://cloud.githubusercontent.com/assets/13557254/12444959/d9852ba4-bf61-11e5-8c5c-2e8a9dd7e668.png)
![webservices](https://cloud.githubusercontent.com/assets/13557254/12444958/d9818f76-bf61-11e5-886f-97089bca800b.png)

**Comment by yllen** [comment]
This part was corrected https://github.com/glpi-project/glpi/pull/385
Can you make new tests to confirm?

**Comment by ladenree76000** [comment]
until now I used a workaround   
preg_replace('!<[^>]+>!Us', '', html_entity_decode($response['content'])).
 and it works.
it quite difficult to make tests, because only few tickets had this display behaviour., but i'll try.

**Comment by korial29** [comment]
I tried to fix this bug with the htmlawed library.
I made a little change on it to make it work.
It seems fixed from ticket creation / category reload / update and from mailcollector import
I also fixed the changes from richText -> simpleText and simpleText -> richText

**Comment by amrtn** [comment]
I've tested @korial29 PR and found out that the text was still being "overcleaned" in the task timeline tab. My PR #525 tries to fix the issue.

**Comment by orthagh** [comment]
Merge #525 from @amrtn 

We need tests for these commits.

@ladenree76000 can you test 0.90/bugfixes or master branch ?

**Comment by ladenree76000** [comment]
ok  i' ll try this from master branch. and give feed back.

**Comment by orthagh** [comment]
Thank you.
It's the last issue missing before 0.90.2 release (no pressure :D )

**Comment by ladenree76000** [comment]
released planed today ?
until there i can tests some cases but no "full validation"

**Comment by ladenree76000** [comment]
good news : 
tickets that previously looked like " <8ms à 200=""> are now displayed : <8ms à 200ms>
(upgrade from 0.90.1 to 0.90.2 wamp server)

still testing create new tickets rich text enabled/disabled
typing in ticket,  copy/paste from email

and if i have time enough creating from collectors

**Comment by ladenree76000** [comment]
ok with rich text enabled/disabled
ok with copy/paste from emails

**Comment by orthagh** [comment]
Great. my tests are also ok

**Comment by yllen** [comment]
another about about this problem http://forum.glpi-project.org/viewtopic.php?id=152282

**Comment by ladenree76000** [comment]
problem is still present in 9.1 RC2  
typing in  'temps <8ms et >200ms'  gives ' temps 200ms' in description field but in the information popup text is displayed as typed in.

![91rc2](https://cloud.githubusercontent.com/assets/13557254/17261825/287666e4-55d8-11e6-8d43-e52ddcc25d30.png)

**Comment by tomolimo** [comment]
Hello,
Could it be linked to this issue #2247?
Regards,
Tomolimo

**Comment by orthagh** [comment]
You did it

**Comment by troublestarter** [comment]
Exist in 9.2.3 !

**Comment by tuxxic** [comment]
Still exists in 9.4.4 / the workaround of adding the backquote doesn't work in the mail notification, the text is still truncated.

Is there a workaround available to display < and > in the mail notifications ?

**Comment by cedric-anne** [comment]
This has been fixed in master branch.
