### ISSUE TITLE
[9.1.1] No notifications for ticket status change on add task & change status

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1400]
Same problem into 0.90.5 : 

When i want to add task & change status to solved or closed on the same on a ticket : 

![image](https://cloud.githubusercontent.com/assets/13178158/20926318/ff005de8-bbbb-11e6-8e18-c8fde7eae8df.png)

The notifications are not sent by system

**Comment by amma35** [comment]
Notifications are not sent because this parameter is specified during a change of status: $update['_disablenotif'] = true;

In the postAdd() function of the file commonitiltask.class.php

`     //change status only if input change
     if (isset($this->input['_status'])
         && ($this->input['_status'] != $this->input['_job']->fields['status'])) {
         $update['status']        = $this->input['_status'];
         $update['id']            = $this->input['_job']->fields['id'];
         $update['_disablenotif'] = true;
         $this->input['_job']->update($update);
      }`


Is this normal?

**Comment by trasher** [comment]
See:

- https://github.com/glpi-project/glpi/commit/0dc6f3ae68bd3e5648c9144258504529cba4f649
- https://github.com/glpi-project/glpi/issues/366
- https://github.com/glpi-project/glpi/issues/247

**Comment by tsmr** [comment]
Yes but the system send a notification for the resolution of the ticket & not for the update_ticket.

Add an exception for this case ?

**Comment by johannsan** [comment]
Hello

The resolved and closed notification is not send when a followup is created because it's an ticket's update (post_updateItem) and we have $update['_disablenotif'] = true; in inc/ticketfollowup.class.php.

If we want that notifications are sent, we have to create two new notification
- "solved_from_ticket_followup"
- "closed_from_ticket_followup".

A suivre...
