### ISSUE TITLE
Unable to assign call to myself

### ISSUE THREAD

**Issue by Sanderti01** [glpi-project/glpi#14000]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

In my environment I need users to see tickets that are assigned to their particular groups, and not others. So in the profile that was created I unchecked the option "See all calls" and the option "Assign" and with that I get what I said above.

When performing the GLPI upgrade from version 10.0.2 to all the following versions, using the scenario I described above, it fails to assign the call to itself.

As I will show in the steps to reproduce the error.

### Relevant log output

```shell
The only file that had an error was the file below

php-errors.log:

[2023-02-03 14:18:38] glpiphplog.WARNING: Test logger  
[2023-02-03 14:42:59] glpiphplog.WARNING: Test logger  
[2023-02-03 14:42:59] glpiphplog.WARNING: Test logger  
[2023-02-03 14:42:59] glpiphplog.WARNING: Test logger  
[2023-02-03 14:42:59] glpiphplog.WARNING: Test logger  
[2023-02-03 14:43:11] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6820
Compile css/standalone/dashboard.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:43:11] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6820
Compile css/standalone/chartist.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:43:11] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6820
Compile css/palettes/auror.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:43:16] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6820
Compile css/standalone/gridstack-grids.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:48:50] glpiphplog.WARNING: Test logger  
[2023-02-03 14:48:50] glpiphplog.WARNING: Test logger  
[2023-02-03 14:48:50] glpiphplog.WARNING: Test logger  
[2023-02-03 14:48:50] glpiphplog.WARNING: Test logger  
[2023-02-03 14:49:03] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6849
Compile css/standalone/dashboard.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:49:03] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6849
Compile css/standalone/chartist.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:49:03] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6849
Compile css/palettes/auror.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 14:49:07] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6849
Compile css/standalone/gridstack-grids.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 15:19:29] glpiphplog.WARNING: Test logger  
[2023-02-03 15:19:29] glpiphplog.WARNING: Test logger  
[2023-02-03 15:19:54] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6799
Compile css/standalone/dashboard.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 15:19:54] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6799
Compile css/standalone/gridstack-grids.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 15:20:12] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6799
Compile css/palettes/auror.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 15:20:19] glpiphplog.DEBUG: Html::compileScss() in /var/www/html/glpi/src/Html.php line 6799
Compile css/standalone/chartist.scss  {"user":"7@fccorp-glpi"} 
[2023-02-03 15:26:03] glpiphplog.WARNING: Test logger
```

### Page URL

http://10.131.1.139/front/ticket.form.php?id=1

### Steps To reproduce

1 - I created a profile where I disabled the options "Assign" and "see all calls"
![image](https://user-images.githubusercontent.com/95760702/216684320-e4977322-dbbd-4c23-ad17-9e2c316882c4.png)

2 - I created a group called "grupo01" in the root entity and made it visible to the child entities
![image](https://user-images.githubusercontent.com/95760702/216685156-344bc3e7-114a-40b3-a992-da4f2ebfe257.png)

3 - I added the user "user01" to the group "grupo01" and to the profile created "profile01" in the root entity recursively:
![image](https://user-images.githubusercontent.com/95760702/216686100-bc1ec302-aa85-42de-a257-a203246e18ea.png)
![image](https://user-images.githubusercontent.com/95760702/216686287-c358bc68-82d5-4de3-a72d-2afbf33cc8e0.png)

4 - As a rule, the call adds each category of call to its due group, and when I try to assign the call to myself, the "Assign to myself" icon does not appear and an icon appears forbidding inclusion in the drop-down list as in the image below:
![image](https://user-images.githubusercontent.com/95760702/216686912-a7c3454c-11ec-410c-baad-6f6b81a73a0c.png)

### Your GLPI setup information

Information about system installation and configuration
 
GLPI 10.0.6 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

Server

Operating system: Linux fccorp-glpi 4.18.0-372.26.1.el8_6.x86_64 #1 SMP Tue Sep 13 18:09:48 UTC 2022 x86_64
PHP 7.4.32 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="1064M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.37 (rocky) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.9.3-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpiteste
	Host info: Localhost via UNIX socket
	
PHP version (7.4.32) is supported.PHP version (7.4.32) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.9.3) is supported.Database engine version (10.9.3) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

GLPI constants

GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

Libraries

htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.5.0 in (/usr/share/pear)

SQL replicas

Not active

Notifications

Way of sending emails: PHP

Plugins list

### Anything else?

No

**Comment by cconard96** [comment]
This behavior seems correct to me.

Assign - Allow user to add add/change assigned users/groups/suppliers
Steal - Allow user to assign self when the Ticket is already assigned

With rules adding a group to these tickets, users would need the Steal permission to add themselves to the ticket.

**Comment by cconard96** [comment]
This behavior seems correct to me. The Assign permission is the global right to be able to change who is assigned while Steal is just a supplemental right that allows the user to assign themselves if there is already a user/group/supplier assigned.

**Comment by Sanderti01** [comment]
> Esse comportamento me parece correto. A permissão Atribuir é o direito global de poder alterar quem é atribuído, enquanto Roubar é apenas um direito suplementar que permite ao usuário atribuir a si mesmo se já houver um usuário/grupo/fornecedor atribuído.

Sorry, I put the wrong image in step "4" . In the above scenario, what is really expected is that the user cannot attribute to other users, which in fact is what happens. But the big problem is that the user "User01" is also not able to assign himself "Steal", please understand that in the image of step 4 "User01" is not assigned even though he is in the group that gives him the permission to view the called.

Here is an example with a correct imgam, in this case the user "felipe.barros" has the right to assign himself "Roubar" and does not have the right to assign, and has the right to see the calls of his group, and this group calls "TI Suporte & Infraestrutura > Suporte Corporativo" and as we can see in the image it fails to assign itself. In all versions below 10.0.2 they worked normally, after that it didn't work anymore.

Thanks in advance and sorry for the error in the image.

![image](https://user-images.githubusercontent.com/95760702/218474280-036f6a8c-b995-4f64-ac58-d47fd4b45c44.png)

**Comment by Sanderti01** [comment]
Good afternoon, @cconard96  if you need more information, just inform me, which I do with maximum priority, because I need it to be able to migrate my GLPI to version 10.0.X

Thank you very much in advance.

**Comment by cedric-anne** [comment]
Hi,

I confirm there is a bug here.

From technical point of view, there is a `canassigntome` variable that should probably be used to evaluate whether this button should be available. For now, both assignees select field and "Assign to me" button availability are based on the global `ASSIGN` right.

**Comment by ts2050** [comment]
Hello, 

I'm having the same problem described above.

Thanks

**Comment by Sanderti01** [comment]
Good afternoon, @cedric-anne  this problem was solved after closing the bug of other issues? Or will he enter another milestone?
Thanks in advance.

**Comment by cedric-anne** [comment]
Hi,

I removed the milestone as it seems that noone has time to fix it right now.

**Comment by Sanderti01** [comment]
Good morning, @cedric-anne  I've been using GLPI for an average of 4 years, and I'd like to use it in version 10, as it now has the features and looks of a modern system and this issue unfortunately makes it impossible for me to update it. My management was wanting to migrate the tool at the same time that the GLPI10 version was launched, I showed my management and asked them to wait, as the version would meet some of our needs, and unfortunately due to that I will not be able to sustain arguments for us to keep the GLPI in our company, I will have to migrate tools. But thanks anyway, success to all of you.

**Comment by Sanderti01** [comment]
Good afternoon @cedric-anne , I performed the validation and everything is back to normal in my environment. Thank you very much. :)
