### ISSUE TITLE
Inventory not made (HTTP 500) - 

### ISSUE THREAD

**Issue by GLGHus** [glpi-project/glpi#14016]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Using GLPI 10.0.5, GLPI Agent 1.2 &1.4  is working fine

Migrating from GLPI 10.0.5 to 10.0.6  inventory is not more working. The agent is starting inventory, but after the inventory the data upload failed:
agent log
` [error] [http client] communication error: 500 Internal Server Error`
server log
`POST /front/inventory.php - 80 - x.x.x.x GLPI-Agent_v1.2 - 500 0 0 6654`
glpiphplog
```
glpiphplog.ERROR:   *** PHP User Error (256): Duplicate entry 'Computer-360-25264' for key 'glpi_items_softwareversions.unicity' in \src\DBmysql.php at line 1969
  Backtrace :
  src\DBmysql.php:1969                               trigger_error()
  src\Inventory\Asset\Software.php:874               DBmysql->executeStatement()
  src\Inventory\Asset\Software.php:446               Glpi\Inventory\Asset\Software->storeAssetLink()
  src\Inventory\Asset\MainAsset.php:871              Glpi\Inventory\Asset\Software->handle()
  src\Inventory\Asset\MainAsset.php:791              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src\RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src\Rule.php:1522                                  RuleImportAsset->executeActions()
  src\RuleCollection.php:1626                        Rule->process()
  src\Inventory\Asset\MainAsset.php:571              RuleCollection->processAllRules()
  src\Inventory\Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src\Inventory\Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src\Inventory\Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src\Inventory\Request.php:90                       Glpi\Inventory\Request->inventory()
  src\Agent\Communication\AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src\Agent\Communication\AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front\inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
```

For now i fixed the issue in src\Inventory\Asset\Software.php in handle() function $iterator select instruction
10.0.5
Line 293 : 'glpi_softwares.softwarecategories_id'
10.0.6
Line 297 : 'glpi_softwarecategories.name AS softwarecategories_id'
EDIT: error come back again. change all dir src\Inventory by 10.0.5 does the trick. this time i think that maybe a change entity rules is involved

it seems working, i'll let the pro make a pull request if the answer is ok, but the behavior of the new request seems ok but conflit with at least 1 app.
I think the issue appear because of two same software name with different software categories : 

![image](https://user-images.githubusercontent.com/109067798/217000728-281fd33c-7057-4d32-b6e4-24b8a0f36db2.png)

**Comment by trasher** [comment]
This should be fixed as of #14105
