### ISSUE TITLE
Import rules criteria bug

### ISSUE THREAD

**Issue by Goldtool** [glpi-project/glpi#14010]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When creating import rules criteria are not working as expected (tested with "Test Rule engine")

Rule 1 :
Criteria : Serial number is already present -> Yes
Action : Link if possible otherwise import declined

Rule 2 : 
Criteria : Serial number doesn't exist -> Yes
Action : Link if possible

Result of test engine with Serial number **present** in database : 
Rule 1 match

Result of test engine with Serial number **not present** in database :
Rule 1 match

**Comment by cedric-anne** [comment]
Hi,

Could you check if bug is still present on GLPI 10.0.6? Many issues related to inventory have been fixed recently.

**Comment by Goldtool** [comment]
Hi,

I just updated to 10.0.6, and same issue

**Comment by stonebuzz** [comment]
You should also check  (IMHO)
Asset > Serial number **exists** Yes for your first rule

**Comment by Goldtool** [comment]
Hello,

Thank you for the help,
By editing the rules we are finaly able to make it works as we want. (Serial number changed by name, but it doesn't matter)
Issue was action on Rule2 : if "Link if possible otherwise import declined" the rules never applied (so we set link if possible)

If it can help anyone here is what we set :

![image](https://user-images.githubusercontent.com/73882101/217473144-6fd045be-54c0-48ee-9c23-f012fba21dd2.png)
