### ISSUE TITLE
Notification not sent for rule based followups

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#14022]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Having a rule that adds a non private followup is not resulting in an notification by mail.

### Relevant log output

```shell
no errors in log
```

### Steps To reproduce

1. Delay mail send by entity by 3min
2. /front/ruleticket.php
3. create rule "AutoReply: something"
4. Operator AND; Rule execution: ADD; Active: Yes
5. Criteria: Descriptions contains regex (A|B)
6. ACTION: Add followup template
7. Followuptemplate -> Create as non private; Source Webservice; Text "blah blah"
8. Send mail with keyword "A"
9. Ticket will have the non private template but in the /front/queuednotification.php the notification is only send to the groups of the techs - not to the initial requester!

**Comment by cedric-anne** [comment]
Hi,

Notification is explicitely disabled when followup/task are created this way, see https://github.com/glpi-project/glpi/blob/1b10079f98144b1a8c35564f24243bfa5006358a/src/CommonITILObject.php#L7767-L7776

IMHO, notifications should be sent, as they may contains an important information, but maybe there was a good reason to do so. I will investigate to try to find a good reason to not have notifications here.

**Comment by cedric-anne** [comment]
Hi,

Notifications will be sent for tasks/followups created by rules/templates in GLPI 10.1. See #14795.
