### ISSUE TITLE
Decommission date is filled after save

### ISSUE THREAD

**Issue by nelero** [glpi-project/glpi#14023]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When adding financial information, sometimes the decommission date fills automatically with the delivery date.

### Steps To reproduce

1. Activate financial elements in tabs of a peripheral
2. type the date for order, invoice, buying, delivery, last inventory
3. save
4. the decommission date is now filled with the delivery date
5. If not, click again on save button. The decommission date is filled.
6. Empty the decommission date and save. The form is now without a decommission date. Save again, the decommission date is now filled again.

### Your GLPI setup information

GLPI 10.0.6 ( => /home/glpi10)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cconard96** [comment]
Please check your entity configuration (Assets tab in each entity) to ensure the auto-fill settings aren't set accidentally.

**Comment by nelero** [comment]
Exact!
Sorry for this issue as it's not. I've removed the decommission date filled automatically in entity configuration.
Thanks for your quick answer.
Regards,
