### ISSUE TITLE
Incorrect approval counter (closed tickets awaiting approval).

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#14025]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Incorrect display of tickets awaiting approval.

/front/ticket.php

![image](https://user-images.githubusercontent.com/16879167/217455043-59b23558-6687-44cb-bb13-fe9c36ef29d7.png)

/front/central.php

![image](https://user-images.githubusercontent.com/16879167/217455336-b2d59484-65cd-4c02-9753-9cf37ae00bac.png)

Question 1:

Shouldn't the approval be canceled when the Ticket closed?

Question 2:

Should the link lead to the "Approvals" tab?

Link to the Ticket in the "Personal view" on the page

/front/central.php

Throws it to the "Approvals" tab in the Ticket

/front/ticket.form.php?id=3927&forcetab=TicketValidation$1

![image](https://user-images.githubusercontent.com/16879167/217456119-4fdfd264-a6b6-483a-a85f-649639b6f848.png)

On which the Ticket cannot be Approved or Refused. 

![image](https://user-images.githubusercontent.com/16879167/217456365-dc0fc258-b448-44f8-b91c-68e37d7c6bfe.png)

You have to go to the "Ticket" tab and perform actions to Approve or Refuse the Ticket there.

![image](https://user-images.githubusercontent.com/16879167/217457488-61432ff0-c2c0-4aa4-a087-39d52048fa74.png)

Wouldn't it be easier if the link immediately links to the "Ticket" tab? Or if this is wrong, then add the option to "Approve" and "Refuse" to the "Approvals" tab? 

Thanks for attention.

### Steps To reproduce

1. Create a ticket. 
2. Request approval in the ticket. 
3. Solve and close the ticket without approval. 
4. An Ticket for approval will be seen on the counter. 
5. There will be no Tickets for approval in the personal form. 
6. The closed Tickets will remain in the status "waiting for approval". 

### Your GLPI setup information

GLPI 10.0.6

**Comment by cedric-anne** [comment]
Hi,

> Question 1:
> 
> Shouldn't the approval be canceled when the Ticket closed?

If ticket is closed and approval is still open, it means that no answer were given to approval request. In this case, we cannot tell wether this request was accepted or refused, so, to handle this, we should probably create a new `Canceled` status that would be automatically set when ticket is closed. This is an important change, as it intoruces a new value that will probably not be handled correctly by plugins, so it cannot be done on 10.0 branch.

On 10.0 branch, a short term solution could be to filter values to exclude closed tickets.


> Question 2:
> 
> Should the link lead to the "Approvals" tab?

As validation can now be directly made in the ticket timeline, then, indeed, it would be probably better to target the main tab.

**Comment by cedric-anne** [comment]
@kofe88 

Thank you for your work too. Your issues are well explained, so it make the job easier for us.

**Comment by MarcSamD** [comment]
Hi there,

I have the same issue as @kofe88 which stop me from easily "monitoring" tickets that I could have forget to approve and I agree with @cedric-anne short term solution: `filter values to exclude closed tickets.`

1. It should be easy to implement.
2. It keeps the consistency between the result of the counter and the result of GLPI 10 new link 
![Tickets waiting for your approval](https://github.com/glpi-project/glpi/assets/70358310/ae589b40-e24c-4697-abd3-c293a359b46b) that is already filtering the solved and closed tickets (but that it is much less convenient than a counter as it forces us to click on the link to check, even if there is no results)

**Comment by cedric-anne** [comment]
> Subsidiary question: How the button ![Tickets waiting for your approval](https://user-images.githubusercontent.com/70358310/237558066-82a22bc0-fd55-4bd1-bf6c-8b67a110ee8b.png) is displayed ? Currently I can only see it in Super-Admin profile but not when using normal Technician profile (despite that I can use this profile to actually approve).

User must have the `Validation > Validate a request` right and/or the `Validation > Validate an incident` right.
