### ISSUE TITLE
Timezone database access / Alternative

### ISSUE THREAD

**Issue by nelero** [glpi-project/glpi#14033]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,
In non dedicated hosting, we can't add privileges to timezone for mysql (or even activate it).
So with the warning for datetime fields to migrate in timestamps, we can't use the command "php bin/console migration:timestamps"

Could we find an alternative for this situation ?
Thanks

### Steps To reproduce

1- mysql user with no access to time_zone_name table in mysql (root) database.
2- field with datetime element
3- warning occurs
4- in console, migration command blocks with the time_zone_name access.

**Comment by cedric-anne** [comment]
You may have errors that says that timezones are not supported, but it does not mean that the fields are not converted from `datetime` to `timestamp`, but it only means that these `timestamp` fields will only be able to store `UTC` dates.

**Comment by nelero** [comment]
Thanks for your answer !

**Comment by cedric-anne** [comment]
#14421 will help to clarify this.
