### ISSUE TITLE
Filtering on end warranty should also allow to search future dates

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#14035]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Currently it is now possible to select future dates when wanting to see the warranty expiration dates of devices. This PR #14034 helps to see which devices will need attention in the coming X time then.

**Comment by cconard96** [comment]
The linked PR was accepted and merged. It will be included as part of GLPI 10.0.7.
