### ISSUE TITLE
Inventory not working due to dictionary rule (HTTP 500)

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#14038]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

We are using the GLPI Agent 1.4 and GLPI Inventory Plugin. When the GLPI Agents sends an inventory, the process is stopped with "[http client] communication error: 500 Internal Server Error". On the Server side we're getting

[2023-02-08 09:14:07] glpiphplog.ERROR:   *** PHP User Error (256): Incorrect integer value: 'FUJITSU' for column `glpi`.`glpi_softwares`.`manufacturers_id` at row 1 in /var/www/glpi/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()
  src/Inventory/Asset/Software.php:714               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:443               Glpi\Inventory\Asset\Software->storeSoftware()
  src/Inventory/Asset/MainAsset.php:871              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:791              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1522                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1626                        Rule->process()
  src/Inventory/Asset/MainAsset.php:571              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()

The reason seems to be a dictionary rule, which is renaming "FUJITSU CLIENT COMPUTING LIMITED" to "FUJITSU" as Manufacturer. When disabling the rule everything ist working again.

**Comment by stonebuzz** [comment]
Hi @AndiMb 
can you retry with nightly build 
This issue is already fixed by
- https://github.com/glpi-project/glpi/pull/13930
- https://github.com/glpi-project/glpi/pull/13996

Best regards
