### ISSUE TITLE
Knowledge Base after migrating 9.5 to 10.0.6

### ISSUE THREAD

**Issue by carlosbmc** [glpi-project/glpi#14036]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

As you can see in last image  there are a lot of  Knowledge Artigles,  but can not see it in SEE ALL option
![image](https://user-images.githubusercontent.com/31730629/217526947-48b800dc-ff42-4200-a5d7-9f4eb16c2c8b.png)
if Articles is asigned to a Knowledge base categories
![image](https://user-images.githubusercontent.com/31730629/217527520-b61d6d9d-1f36-4cc8-9e86-dba6e59491d9.png)
We have to click on Knowledge base categories in order to search it.
As you can see there are a lot of articles.
![image](https://user-images.githubusercontent.com/31730629/217527987-12d5a804-b505-48a8-bcb4-9c79c25e6ebe.png)

**Comment by cedric-anne** [comment]
Hi,

This has been fixed in #13877.

**Comment by carlosbmc** [comment]
Sorry, i find it ,   than you!
