### ISSUE TITLE
Warranty report

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#14031]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

I have a server with the following financial information:

![image](https://user-images.githubusercontent.com/75667/217504178-23f3a10c-22bb-4f8c-9148-4f523aef10be.png)

The info is imported via the "Suppliers import" plugin.

However, when creating a financial report, I see this as warranty expiration:
![image](https://user-images.githubusercontent.com/75667/217504571-a1cd8657-b9c9-4ca7-abd0-20fdc57658f8.png)

So, several issues here:
- the reporting doesn't take warranty extensions into account
- a report on warranty expiration would be useful, or some configurable action that reports warranty will end in X days for a device

**Comment by liedekef** [comment]
Well, you clearly see in the first screenshot a server with warranty (after extension) end date 2024-09-08.
The financial report however says that the warranty ended on 2020-09-07 (the original first warrenty end date, before any extension). So that is clearly wrong.
Even when searching in the list of items for warranty end date being that date works fine (using a glpi fix, so I can search on warranty end dates in the future). So the database contains the correct info, just the financial report is returning wrong info.

**Comment by cconard96** [comment]
Please test the linked fix:
#14363

**Comment by liedekef** [comment]
This indeed seems to fix the problem, thanks!
