### ISSUE TITLE
Inventory not working : Undefined array key "id" in /var/www/html/glpi/src/Agent.php at line 401

### ISSUE THREAD

**Issue by sebma** [glpi-project/glpi#14039]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,
The inventory is not working : 

```log
PS C:\> tail.exe -f "$env:ProgramFiles/GLPI-Agent/logs/glpi-agent.log"
   "itemtype": "Computer"
}
[Wed Feb  8 16:17:45 2023][error] [http client] communication error: 500 Internal Server Error, 
[Wed Feb  8 16:17:47 2023][debug] new thread 14 to handle task NetDiscovery
```

### Relevant log output

```shell
/var/log/glpi$ tail -f php-errors.log
[2023-02-08 16:18:17] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/src/Agent.php at line 401
  Backtrace :
  src/Inventory/Inventory.php:229                    Agent->handleAgent()
  src/Inventory/Request.php:309                      Glpi\Inventory\Inventory->contact()
  src/Inventory/Request.php:83                       Glpi\Inventory\Request->contact()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()

[2023-02-08 16:18:51] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/splitcat/inc/itilcategory.class.php at line 280
  Backtrace :
  marketplace/splitcat/inc/itilcategory.class.php:70 PluginSplitcatITILCategory::getItilCatSelect()
  marketplace/splitcat/ajax/splitcat.php:52          PluginSplitcatITILCategory::ajax()

The second warning is repeated multiple times.
```

### Steps To reproduce

1. Goto http://localhost:62354/
2. Click on [Force an Inventory](http://localhost:62354/now)
3. Click on Back

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.6 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Linux PAR-GLPI 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.10 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at helpdesk.media-participations.com Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: Ubuntu 20.04
	Server Version: 10.3.37-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: administrateur@172.16.5.162:6033/glpi_v10_0_6
	Host info: 172.16.5.162 via TCP/IP
	
PHP version (8.1.2-1ubuntu2.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.37) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/marketplace/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: '172.16.78.12', Port: '389', BaseDN: 'DC=ORION,DC=lan', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=svc_glpi2,OU=T1-Services,OU=Tier 1,OU=Admin,DC=ORION,DC=LAN', Use TLS: none
Server: 'dupuis.be', Port: '389', BaseDN: 'DC=dupuis,DC=be', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=svc-glpi-ro,OU=Services,OU=Groupes,OU=People,DC=dupuis,DC=be', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	advanceddashboard    Name: advanceddashboard              Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                 
		Install Method: Marketplace
	anonymize            Name: Anonymize                      Version: 2.7.0      State: Enabled                                 
		Install Method: Marketplace
	approvalbymail       Name: Approval by mail               Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace
	branding             Name: Branding                       Version: 1.3.2      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.20.0     State: Enabled                                 
		Install Method: Marketplace
	accounts             Name: Comptes                        Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.1      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.12.1     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.10.1     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	holiday              Name: Holidays                       Version: 1.2.0      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Marketplace
	oauthsso             Name: oauthsso                       Version: 1.9.2      State: Enabled                                 
		Install Method: Marketplace
	collaborativetools   Name: Outils collaboratifs           Version: 1.2.2      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	localeoverride       Name: Renommer les chaînes de GLPI   Version: 1.1.5      State: Enabled                                 
		Install Method: Marketplace
	resources            Name: Ressources humaines            Version: 3.0.4      State: Enabled                                 
		Install Method: Marketplace
	splitcat             Name: Split categories               Version: 1.5.2      State: Enabled                                 
		Install Method: Marketplace
	vip                  Name: VIP                            Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

### Anything else?

server = https://helpdesk.media-participations.com/marketplace/glpiinventory/ in the agent registry.

If I set debug=2 in the agent, I can see the JSON file generated inside the "$env:ProgramFiles/GLPI-Agent/logs/glpi-agent.log".

It seems it is having a problem either sending it to the server or inserting it into the database.

**Comment by stonebuzz** [comment]
Hi @sebma 
can you retry GLPI nighlty build ?

https://nightly.glpi-project.org/glpi/

Your issue should be fixed.

Best regards

**Comment by sebma** [comment]
@stonebuzz Thank you. Before we do that, do you have the PR that fixes this bug ?

**Comment by sebma** [comment]
Hereby attached are the [php-errors.log](https://github.com/glpi-project/glpi/files/10687877/php-errors.log) and the [sql-errors.log](https://github.com/glpi-project/glpi/files/10687878/sql-errors.log).

**Comment by stonebuzz** [comment]
I found this from your log

```sql
  SQL: INSERT INTO `glpi_agents` (`deviceid`, `name`, `last_contact`, `useragent`, `agenttypes_id`, `itemtype`, `version`, `remote_addr`, `items_id`, `threads_networkdiscovery`, `threads_networkinventory`, `timeout_networkdiscovery`, `timeout_networkinventory`) VALUES ('P3786.ORION.lan-2022-12-29-09-49-15', 'P3786.ORION.lan-2022-12-29-09-49-15', '2023-02-08 12:01:02', 'GLPI-Agent_v1.4', NULL, 'Computer', '1.4', '10.10.98.6', '0', '0', '0', '0', '0')
  Error: Column 'agenttypes_id' cannot be null
```

Can you post here result of this SQL query

```sql
select * from glpi_agenttypes;
```

Best regards

**Comment by stonebuzz** [comment]
This warning is related to ```splitcat``` plugin

```
[2023-02-08 16:20:43] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/html/glpi/marketplace/splitcat/inc/itilcategory.class.php at line 280
  Backtrace :
  marketplace/splitcat/inc/itilcategory.class.php:70 PluginSplitcatITILCategory::getItilCatSelect()
  marketplace/splitcat/ajax/splitcat.php:52          PluginSplitcatITILCategory::ajax()
```

**Comment by stonebuzz** [comment]
It seems you have a GLPI Network subscription, please contact us for splitcat warning.

**Comment by sebma** [comment]
@stonebuzz Hi, I'm in trouble with my superior because I forgot to anonymise data before posting this issue.

I just removed some data today, can you also anonymise the data in your answer posted at https://github.com/glpi-project/glpi/issues/14039#issuecomment-1423047310 ?

Thank you for your understanding.

**Comment by stonebuzz** [comment]
done

**Comment by sebma** [comment]
@stonebuzz Thanks a lot.
