### ISSUE TITLE
HTML table formatting issues

### ISSUE THREAD

**Issue by scylla999** [glpi-project/glpi#14048]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

There seems to be a problem with embedded HTML tables in follow-ups.
Column titles are crunched together:
![image](https://user-images.githubusercontent.com/24919069/217884918-9a2dadd8-0a82-4709-9659-a82716f7dc88.png)

Here's what it should look like:
![image](https://user-images.githubusercontent.com/24919069/217885172-a034cc6f-aebf-462e-b6dc-a46afa969e3b.png)

**Comment by scylla999** [comment]
Here's a copy of the HTML before it's broken:

<html>
	<head>
		<title>Gestion cheminement: demande Modification de choix de cours 4523523 (Lalonde, Luc)</title>
	</head>
	<body>
		4523523 : Lalonde, Luc

<table width="99%" border="0" cellpadding="1" cellspacing="0" bgcolor="#EAEAEA"><tr><td>
                            <table width="100%" border="0" cellpadding="5" cellspacing="0" bgcolor="#FFFFFF">
                            <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Date</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;">09/02/2023</font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Identification</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;">Luc Lalonde</font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Matricule</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;">4523523</font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Courriel (Polytechnique)</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;"><a href='mailto:luc.lalonde@polymtl.ca'>luc.lalonde@polymtl.ca</a></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Programme du baccalaurÃ©at</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;">gÃ©nie informatique</font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Type de demande</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;">Modification de choix de cours</font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Raison de la demande de modification</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;"><ul class='bulleted'><li>Je suis en probation</li></ul></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#EAF2FA">
		                                    <td colspan="2">
		                                        <font style="font-family: sans-serif; font-size:12px;"><strong>Cours Ã  modifier :</strong></font>
		                                    </td>
		                               </tr>
		                               <tr bgcolor="#FFFFFF">
		                                    <td width="20">&nbsp;</td>
		                                    <td>
		                                        <font style="font-family: sans-serif; font-size:12px;"><table class='gfield_list' style='border-top: 1px solid #DFDFDF; border-left: 1px solid #DFDFDF; border-spacing: 0; padding: 0; margin: 2px 0 6px; width: 100%'><thead><tr>
<th style='background-image: none; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; padding: 6px 10px; font-family: sans-serif; font-size: 12px; font-weight: bold; background-color: #F1F1F1; color:#333; text-align:left'>Sigle du cours</th>
<th style='background-image: none; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; padding: 6px 10px; font-family: sans-serif; font-size: 12px; font-weight: bold; background-color: #F1F1F1; color:#333; text-align:left'>Groupe ThÃ©orique inscrit</th>
<th style='background-image: none; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; padding: 6px 10px; font-family: sans-serif; font-size: 12px; font-weight: bold; background-color: #F1F1F1; color:#333; text-align:left'>Groupe Pratique inscrit</th>
<th style='background-image: none; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; padding: 6px 10px; font-family: sans-serif; font-size: 12px; font-weight: bold; background-color: #F1F1F1; color:#333; text-align:left'>Groupe ThÃ©orique souhaitÃ©</th>
<th style='background-image: none; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; padding: 6px 10px; font-family: sans-serif; font-size: 12px; font-weight: bold; background-color: #F1F1F1; color:#333; text-align:left'>Groupe Pratique souhaitÃ©</th>
</tr></thead>
<tbody style='background-color: #F9F9F9'><tr><td style='padding: 6px 10px; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; border-top: 1px solid #FFF; font-family: sans-serif; font-size:12px;'>inf1010</td>
<td style='padding: 6px 10px; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; border-top: 1px solid #FFF; font-family: sans-serif; font-size:12px;'>01</td>
<td style='padding: 6px 10px; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; border-top: 1px solid #FFF; font-family: sans-serif; font-size:12px;'>10</td>
<td style='padding: 6px 10px; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; border-top: 1px solid #FFF; font-family: sans-serif; font-size:12px;'>01</td>
<td style='padding: 6px 10px; border-right: 1px solid #DFDFDF; border-bottom: 1px solid #DFDFDF; border-top: 1px solid #FFF; font-family: sans-serif; font-size:12px;'>02</td>
</tr>
<tbody></table>
</font>
		                                    </td>
		                               </tr>
		                               </table>
                        </td>
                   </tr>
               </table>
	</body>
</html>

**Comment by cedric-anne** [comment]
Hi,

Is this followup generated from an email, or is is generated by pasting contents in the followup form?
If source is an email, could you export it into a `.eml` file and attach it to this issue?

**Comment by scylla999** [comment]
It was an email followup... Here's an exported copy.
[GLPI_HTML_Table_Issue.eml.gz](https://github.com/glpi-project/glpi/files/10701258/GLPI_HTML_Table_Issue.eml.gz)

**Comment by scylla999** [comment]
Here's the same message that hasn't gone through our GLPI IMAP email collector.   
[GLPI-Original_HTML_Message.eml.gz](https://github.com/glpi-project/glpi/files/10701628/GLPI-Original_HTML_Message.eml.gz)

**Comment by cedric-anne** [comment]
Problem here is that the `htmLawed` library we use to clean HTML code from malicious content (scripts for instance) is not handling the `<font>` tag properly. We planned to replace this library, but not before, at least, the next major GLPI version.

Anyway, using `<font>` is deprecated since a long time ago now, and source application should be updated to replace this `<font>` tag by something else.

Feel free to report a bug on [`htmLawed` forum](http://www.bioinformatics.org/phplabware/forum/viewforum.php?id=5) if you want this bug to be fixed.

I close the issue as we cannot fix it on GLPI side.

**Comment by scylla999** [comment]
In case anyone else falls on this issue, the tool we use to generate the HTML form:  Gravity Forms (Wordpress plugin)

**Comment by scylla999** [comment]
I posted details and paraphrased your description... I hope that you don't mind:

https://community.gravityforms.com/t/gravity-forms-generates-deprecated-html/14422
