### ISSUE TITLE
mailgate stuck

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#14054]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

mailgate stop process mail to other receiver when one in the middle has a problem

### Steps To reproduce

I verified today I got (I think) a malformed e-mail message in the inbox folder of one mailbox (basically one receiver).

I have configured multiple receivers to process mail from different mailboxes.
If I try to get mail manually (inside the receiver) I got a blank page, but inside the mailgate automatic action, when it process that specific receiver fails and the other receiver will not be processed.

I thing it should be handled some exception to allow processing other receiver even if one of it has some problem.

(I resolved deleting the problematic e-mail and all back working again).

**Comment by cedric-anne** [comment]
Hi,

Most errors are supposed to be catched to prevent this behaviour. Could you please provide the stacktrace related to your balnk page and/or the e-mail that was causing the issue?

**Comment by trasher** [comment]
No feedback, I close
