### ISSUE TITLE
SNMP & Managementlan

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#14057]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

We changed the IP-Adress of the Management Interface of one of our switches from 10.X.X.X to 10.5.135.1. I added 10.5.135.1 - 10.5.135.254 The snmp inventory didn't recognize this. I checked the xml-file which ist provided by glpi = there is no entry for 10.5.135.1.

I made a snmp walk and found the new Adress there. The switch is a HP HP ProCurve 1810G.

### Relevant log output

```shell
SNMP Walk

.1.3.6.1.2.1.4.20.1.1.10.5.135.1 = IpAddress: 10.5.135.1
.1.3.6.1.2.1.4.20.1.2.10.5.135.1 = INTEGER: 25
.1.3.6.1.2.1.4.20.1.3.10.5.135.1 = IpAddress: 255.255.0.0
.1.3.6.1.2.1.4.20.1.4.10.5.135.1 = INTEGER: 1
.1.3.6.1.2.1.4.20.1.5.10.5.135.1 = INTEGER: 65535
```

### Page URL

$GLPI/front/networkequipment.form.php

### Steps To reproduce

1. change the ip of an existing switch
2. run an snmp inventory
3. Check the xml on the page of the switch in glpi

### Your GLPI setup information

<details><summary>Informationen über das System, die Installation und die Konfiguration</summary><pre>GLPI 10.0.5 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:de_DE

</details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.4.0-135-generic #152-Ubuntu SMP Wed Nov 23 20:19:22 UTC 2022 x86_64
PHP 7.4.3-4ubuntu2.17 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="1024M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.XXXX.XX Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: (Ubuntu)
	Server Version: 8.0.32-0ubuntu0.20.04.2
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: X@localhost/X
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3-4ubuntu2.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.32) is supported.
The log file could not be created in /var/www/glpi/files/_log.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/glpi":
‣ "/var/www/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: '10.10.10.2', Port: '389', BaseDN: 'dc=XXX,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberof=cn=XXX,ou=groups,ou=XXX,dc=XXX,dc=local))',
		RootDN: 'XXX@XXX.local', Use TLS: XXX

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (XXX@XXX.XXX.XXX.XXX)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.20.0     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.12.1     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.1      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Installed / not activated               
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.1     State: Enabled                                 
		Install Method: Marketplace
	printlabel           Name: Print Label                    Version: 0.0.1      State: Enabled                                 
		Install Method: Manual
	printlabelprinter    Name: Print Label Printer            Version: 0.0.1      State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Verhalten                      Version: 2.7.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by g-bougard** [comment]
Hi @vollkommenIrrelevant 
firstly, can you tell which agent you're using and in which version ?
If you're using glpi-agent, please provide the output of:
```
glpi-netdiscovery --host 10.5.135.1 --debug --debug
```
If you're not using the default credentials, you should add a `--credentials` option, see [glpi-netdiscovery man page](https://glpi-agent.readthedocs.io/en/latest/man/glpi-netdiscovery.html).

**Comment by vollkommenIrrelevant** [comment]
```
C:\Program Files\GLPI-Agent>glpi-netdiscovery --host 10.5.135.1 --debug --debug
[debug] Logger backend Stderr initialized
[debug] GLPI Agent (1.5-git7e89bf8e)
[debug] initializing job 1
[debug] initializing block 10.5.135.1-10.5.135.1
[debug] Current run expiration timeout: soon
[debug] creating 1 worker threads
[debug] [thread 1] creation
[debug] [thread 1] #1, scanning 10.5.135.1
[debug] [thread 1] #1, full match for sysobjectID .1.3.6.1.4.1.11.2.3.7.11.104 in database
[debug2] [thread 1] #1, C:/Program Files/GLPI-Agent/etc/toolbox.yaml configuration not found
[debug] [thread 1] #1, sysobjectID match: hp-etherswitch mib support enabled
[debug] [thread 1] #1, - scanning 10.5.135.1 with SNMP, credentials 1: success
[debug] [thread 1] #1, - scanning 10.5.135.1 with netbios: no result
[debug] [thread 1] #1, - scanning 10.5.135.1 with echo ping: success
[debug2] [thread 1] #1, executing arp -a 10.5.135.1
[debug] [thread 1] #1, - scanning 10.5.135.1 in arp table: no result
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <CONTENT>
    <DEVICE>
      <AUTHPORT />  <AUTHPROTOCOL />  <AUTHSNMP>1</AUTHSNMP>
      <CONTACT>Vincent Uhres</CONTACT>
      <DESCRIPTION> HP ProCurve 1810G - 24 GE, XYZ</DESCRIPTION>
      <DNSHOSTNAME>10.5.135.1</DNSHOSTNAME>
      <FIRMWARE>CFE-X.X</FIRMWARE>
      <IP>10.5.135.1</IP>
      <IPS>
        <IP>10.5.135.1</IP>
      </IPS>
      <LOCATION>XYZ, IT-</LOCATION>
      <MAC>c0:91:34:XX:XX:XX</MAC>
      <MANUFACTURER>Hewlett-Packard</MANUFACTURER>
      <MODEL>ProCurve 1810G-24 (J9450A)</MODEL>
      <SERIAL>CNXXXXXXX</SERIAL>
      <SNMPHOSTNAME>XYZ - Uplink</SNMPHOSTNAME>
      <TYPE>NETWORKING</TYPE>
      <UPTIME>20 days, 02:23:59.00</UPTIME>
    </DEVICE>
    <MODULEVERSION>5.1</MODULEVERSION>
    <PROCESSNUMBER>1</PROCESSNUMBER>
  </CONTENT>
  <DEVICEID>foo</DEVICEID>
  <QUERY>NETDISCOVERY</QUERY>
</REQUEST>
[debug2] [thread 1] processed 1 scans
[debug] [thread 1] termination
[debug] All netdiscovery threads terminated
```

**Comment by vollkommenIrrelevant** [comment]
![grafik](https://user-images.githubusercontent.com/25504254/218140835-8387ade2-c444-4f5c-9b03-edf0a6bbcb87.png)

![grafik](https://user-images.githubusercontent.com/25504254/218140636-8c9c200d-bfb3-45a4-ac72-ce42ebacb9bc.png)

**Comment by g-bougard** [comment]
This seems okay to me.
Can you now share the output of:
```
glpi-netinventory --host 10.5.135.1 --debug --debug
```

**Comment by vollkommenIrrelevant** [comment]
You've got a mail.

**Comment by vollkommenIrrelevant** [comment]
> > This seems okay to me. Can you now share the output of:
> > ```
> > glpi-netinventory --host 10.5.135.1 --debug --debug
> > ```
> 
> You've got a mail.

Ps. - one Idea:
Maybe the glpi is having a problem with updating the xml-file via snmp. I think it make sense to upgrade to 10.0.6 and check again?

**Comment by g-bougard** [comment]
Tested your XML and seems fine on my GLPI 10.0.6.
Few fixes in GLPI 10.0.6 can still have fix your issue, so yes, upgrade your GLPI and test again.
Just a point, I'm not sure to understand what you think is wrong. So if GLPI 10.0.6 doesn't fixe your problem, can you clarify the problem ?

**Comment by vollkommenIrrelevant** [comment]
@g-bougard 
I Updated and found out that one inventory task did stuck in mode "running" with wireing issues. After 
`Use glpi; DELETE FROM glpi_networkports_networkports;`
The task runs again. Interesting point is that the inventory plugin did show succes on page "Monitoring / Logs" and on Page Status=>Network inventory there was only the for some days running task visible.

**Comment by vollkommenIrrelevant** [comment]
Any Idea how I can get rid of all this old jobs?

![grafik](https://user-images.githubusercontent.com/25504254/219042938-f6f2da17-d856-4d7d-a072-803d271089af.png)

**Comment by trasher** [comment]
forums is a better place to ask for support, this is not related at all with initial issue

**Comment by vollkommenIrrelevant** [comment]
@trasher 
I think you didn't understand this at all. I therefore recommend appropriate restraint.

**Comment by trasher** [comment]
The comment associated to the issue reopening does not seems related to initial issue. If I did not understood, please be more precise, and feel free to reopen.
