### ISSUE TITLE
Inventory Does not update computers

### ISSUE THREAD

**Issue by antoniojunior23** [glpi-project/glpi#14058]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

After updating the version to glpi 10.0.6, the automatic inventory of computers does not work, even with the function enabled, through the domain hosted on hostgator.
Using agent version 1.4 and pointing: meudominio.com.br/front/inventory.php

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.6 ( => /home4/marilia/central.grupomarilia.com.br)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux br1046.hostgator.com.br 4.19.150-76.ELK.el7.x86_64 #1 SMP Wed Oct 7 01:33:43 CDT 2020 x86_64
PHP 8.2.2 litespeed (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, libxml, litespeed, mbstring,
	mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, pspell, random, readline, session,
	soap, sockets, sodium, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="512M" post_max_size="516M" safe_mode="" session.save_handler="files"
	upload_max_filesize="512M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 23, Revision 500fcf5
	Server Version: 5.7.23-23
	Server SQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: marilia_salin@localhost/marilia_glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.2) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.23) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_cache has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/config has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_cron has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_dumps has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_graphs has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_lock has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_pictures has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_plugins has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_rss has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_sessions has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_tmp has been validated.
Write access to /home4/marilia/central.grupomarilia.com.br/files/_uploads has been validated.
The following directories should be placed outside "/home4/marilia/central.grupomarilia.com.br":
‣ "/home4/marilia/central.grupomarilia.com.br/files" ("GLPI_VAR_DIR")
‣ "/home4/marilia/central.grupomarilia.com.br/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home4/marilia/central.grupomarilia.com.br/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home4/marilia/central.grupomarilia.com.br"
GLPI_CONFIG_DIR: "/home4/marilia/central.grupomarilia.com.br/config"
GLPI_VAR_DIR: "/home4/marilia/central.grupomarilia.com.br/files"
GLPI_MARKETPLACE_DIR: "/home4/marilia/central.grupomarilia.com.br/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/home4/marilia/central.grupomarilia.com.br/files"
GLPI_CACHE_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_cache"
GLPI_CRON_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_cron"
GLPI_DUMP_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_dumps"
GLPI_GRAPH_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_locales"
GLPI_LOCK_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_lock"
GLPI_LOG_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_log"
GLPI_PICTURE_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_plugins"
GLPI_RSS_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_rss"
GLPI_SESSION_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_sessions"
GLPI_TMP_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_tmp"
GLPI_UPLOAD_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_uploads"
GLPI_INVENTORY_DIR: "/home4/marilia/central.grupomarilia.com.br/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/home4/marilia/central.grupomarilia.com.br/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/home4/marilia/central.grupomarilia.com.br/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home4/marilia/central.grupomarilia.com.br/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home4/marilia/central.grupomarilia.com.br/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/home4/marilia/central.grupomarilia.com.br/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home4/marilia/central.grupomarilia.com.br/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home4/marilia/central.grupomarilia.com.br/vendor/true/punycode/src)
iamcal/lib_autolink in (/home4/marilia/central.grupomarilia.com.br/vendor/iamcal/lib_autolink)
sabre/dav in (/home4/marilia/central.grupomarilia.com.br/vendor/sabre/dav/lib/DAV)
sabre/http in (/home4/marilia/central.grupomarilia.com.br/vendor/sabre/http/lib)
sabre/uri in (/home4/marilia/central.grupomarilia.com.br/vendor/sabre/uri/lib)
sabre/vobject in (/home4/marilia/central.grupomarilia.com.br/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home4/marilia/central.grupomarilia.com.br/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home4/marilia/central.grupomarilia.com.br/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home4/marilia/central.grupomarilia.com.br/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home4/marilia/central.grupomarilia.com.br/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home4/marilia/central.grupomarilia.com.br/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home4/marilia/central.grupomarilia.com.br/vendor/elvanto/litemoji/src)
symfony/console in (/home4/marilia/central.grupomarilia.com.br/vendor/symfony/console)
scssphp/scssphp in (/home4/marilia/central.grupomarilia.com.br/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home4/marilia/central.grupomarilia.com.br/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home4/marilia/central.grupomarilia.com.br/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home4/marilia/central.grupomarilia.com.br/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home4/marilia/central.grupomarilia.com.br/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home4/marilia/central.grupomarilia.com.br/vendor/ramsey/uuid/src)
psr/log in (/home4/marilia/central.grupomarilia.com.br/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home4/marilia/central.grupomarilia.com.br/vendor/psr/simple-cache/src)
psr/cache in (/home4/marilia/central.grupomarilia.com.br/vendor/psr/cache/src)
league/csv in (/home4/marilia/central.grupomarilia.com.br/vendor/league/csv/src)
mexitek/phpcolors in (/home4/marilia/central.grupomarilia.com.br/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home4/marilia/central.grupomarilia.com.br/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home4/marilia/central.grupomarilia.com.br/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home4/marilia/central.grupomarilia.com.br/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home4/marilia/central.grupomarilia.com.br/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home4/marilia/central.grupomarilia.com.br/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home4/marilia/central.grupomarilia.com.br/vendor/symfony/cache)
html2text/html2text in (/home4/marilia/central.grupomarilia.com.br/vendor/html2text/html2text/src)
symfony/css-selector in (/home4/marilia/central.grupomarilia.com.br/vendor/symfony/css-selector)
symfony/dom-crawler in (/home4/marilia/central.grupomarilia.com.br/vendor/symfony/dom-crawler)
twig/twig in (/home4/marilia/central.grupomarilia.com.br/vendor/twig/twig/src)
twig/string-extra in (/home4/marilia/central.grupomarilia.com.br/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home4/marilia/central.grupomarilia.com.br/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

**glpi agent logs:**
[Fri Feb 10 17:50:51 2023][info] GLPI Agent service starting
[Fri Feb 10 17:50:52 2023][info] [http server] HTTPD service started on port 62354
[Fri Feb 10 17:50:53 2023][info] GLPI Agent memory usage: WSS=4288512 PFU=105697280
[Fri Feb 10 17:50:53 2023][info] target server0: next run: Fri Feb 10 18:49:14 2023 - https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:50:56 2023][info] target server0: server https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:50:56 2023][info] sending prolog request to server0
[Fri Feb 10 17:51:07 2023][error] [http client] communication error: 406 Not Acceptable, 
[Fri Feb 10 17:51:07 2023][error] No answer from server at https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:51:07 2023][info] target server0: next run: Fri Feb 10 17:52:07 2023 - https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:52:07 2023][info] target server0: server https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:52:07 2023][info] sending prolog request to server0
[Fri Feb 10 17:52:07 2023][error] [http client] communication error: 406 Not Acceptable, 
[Fri Feb 10 17:52:07 2023][error] No answer from server at https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:52:07 2023][info] target server0: next run: Fri Feb 10 17:54:07 2023 - https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:52:07 2023][info] GLPI Agent memory usage: WSS=3317760 PFU=120877056
[Fri Feb 10 17:53:09 2023][info] running task Deploy: storage maintenance event
[Fri Feb 10 17:53:11 2023][info] GLPI Agent memory usage: WSS=3407872 PFU=125456384
[Fri Feb 10 17:54:07 2023][info] target server0: server https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:54:07 2023][info] sending prolog request to server0
[Fri Feb 10 17:54:08 2023][error] [http client] communication error: 406 Not Acceptable, 
[Fri Feb 10 17:54:08 2023][error] No answer from server at https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:54:08 2023][info] target server0: next run: Fri Feb 10 17:58:08 2023 - https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:58:08 2023][info] target server0: server https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:58:08 2023][info] sending prolog request to server0
[Fri Feb 10 17:58:08 2023][error] [http client] communication error: 406 Not Acceptable, 
[Fri Feb 10 17:58:08 2023][error] No answer from server at https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:58:08 2023][info] target server0: next run: Fri Feb 10 18:06:08 2023 - https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 17:58:08 2023][info] GLPI Agent memory usage: WSS=3313664 PFU=127082496
[Fri Feb 10 18:03:36 2023][info] target server0: server https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 18:03:36 2023][info] sending prolog request to server0
[Fri Feb 10 18:03:36 2023][error] [http client] communication error: 406 Not Acceptable, 
[Fri Feb 10 18:03:36 2023][error] No answer from server at https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 18:03:36 2023][info] target server0: next run: Fri Feb 10 18:19:36 2023 - https://central.grupomarilia.com.br/front/inventory.php
[Fri Feb 10 18:03:36 2023][info] GLPI Agent memory usage: WSS=3284992 PFU=128524288

**Comment by stonebuzz** [comment]
Hi @antoniojunior23 

```406 Not Acceptable```

certainly a bad configuration of your web server

Best regards

**Comment by adminsolix** [comment]
> ### codigo de conducta
> * [ ] Acepto seguir el código de conducta de este proyecto
> 
> ### ¿Hay un problema existente para esto?
> * [x] He buscado los problemas existentes
> 
> ### Versión
> 10.0.6
> 
> ### Descripcion del error
> Después de actualizar la versión a glpi 10.0.6, el inventario automático de equipos no funciona, incluso con la función habilitada, a través del dominio alojado en hostgator. Utilizando la versión 1.4 del agente y señalando: meudominio.com.br/front/inventory.php
> 
> ### Salida de registro relevante
> _Ninguna respuesta_
> 
> ### URL de la página
> ### Pasos para reproducir
> _Ninguna respuesta_
> 
> ### Su información de configuración de GLPI
> Instrucciones de instalacion y configuracion
> Servidor
> constantes GLPI
> bibliotecas
> réplicas de SQL
> Notificaciones
> Lista de complementos
> ### ¿Algo más?
> **Registros del agente glpi:** [Viernes 10 de febrero 17:50:51 2023][info] Inicio del servicio del agente GLPI [Viernes 10 de febrero 17:50:52 2023][info] [Servidor http] Servicio HTTPD iniciado en el puerto 62354 [Viernes 10 de febrero 17:50:53 2023][información] Uso de memoria del agente GLPI: WSS=4288512 PFU=105697280 [viernes 10 de febrero 17:50:53 2023][información] servidor de destino 0: próxima ejecución: viernes 10 de febrero 18:49:14 2023 - https://central.grupomarilia.com.br/front/inventory.php [Viernes 10 de febrero 17:50:56 2023][info] servidor objetivo0: servidor [https://central.grupomarilia.com.br/front/ inventario.php](https://central.grupomarilia.com.br/front/inventory.php) [Viernes 10 de febrero 17:50:56 2023][info] enviando solicitud de prólogo al servidor0 [Viernes 10 de febrero 17:51:07 2023][error] [cliente http] error de comunicación: 406 No aceptable, [Viernes de febrero 10 17:51:07 2023] [error] No hay respuesta del servidor enhttps://central.grupomarilia.com.br/front/inventory.php [Viernes 10 de febrero 17:51:07 2023][info] servidor objetivo0: próxima ejecución: Viernes 10 de febrero 17:52:07 2023 - [https:/ /central.grupomarilia.com.br/front/inventory.php](https://central.grupomarilia.com.br/front/inventory.php) [Vier 10 Feb 17:52:07 2023][info] servidor destino0: servidor https://central.grupomarilia.com.br/front/inventory.php [ viernes 10 de febrero 17:52:07 2023] [info] enviando solicitud de prólogo al servidor0 [viernes 10 de febrero 17:52:07 2023] [error] [cliente http] error de comunicación: 406 no aceptable, [viernes 10 de febrero 17:52 :07 2023][error] No hay respuesta del servidor en https://central.grupomarilia.com.br/front/inventory.php [Viernes 10 de febrero 17:52:07 2023][info] servidor de destino 0: próxima ejecución: viernes 10 feb 17:54:07 2023 -https://central.grupomarilia.com.br/front/inventory.php [Vier 10 Feb 17:52:07 2023][info] Uso de memoria del Agente GLPI: WSS=3317760 PFU=120877056 [Vier 10 Feb 17:53: 09 2023][información] tarea en ejecución Implementación: evento de mantenimiento de almacenamiento [viernes 10 de febrero 17:53:11 2023][información] Uso de memoria del agente GLPI: WSS=3407872 PFU=125456384 [viernes 10 de febrero 17:54:07 2023][ info] target server0: server https://central.grupomarilia.com.br/front/inventory.php [vie 10 feb 17:54:07 2023][info] enviando solicitud de prólogo al server0 [vie 10 feb 17:54: 08 2023][error] [cliente http] error de comunicación: 406 No aceptable, [vie 10 feb 17:54:08 2023][error] No hay respuesta del servidor en [https://central.grupomarilia.com.br/front/ inventario.php](https://central.grupomarilia.com.br/front/inventory.php) [Viernes 10 de febrero 17:54:08 2023][info] servidor de destino 0: próxima ejecución: Viernes 10 de febrero 17:58:08 2023 - https://central.grupomarilia.com.br/front/inventory.php [Viernes de febrero 10 17:58:08 2023][info] target server0: server https://central.grupomarilia.com.br/front/inventory.php [Vie Feb 10 17:58:08 2023][info] enviando solicitud de prólogo a server0 [Viernes 10 de febrero 17:58:08 2023][error] [cliente http] error de comunicación: 406 No aceptable, [Viernes 10 de febrero 17:58:08 2023][error] No hay respuesta del servidor en [https://central .grupomarilia.com.br/front/inventory.php](https://central.grupomarilia.com.br/front/inventory.php) [Viernes 10 de febrero 17:58:08 2023][info] servidor objetivo0: próxima ejecución: Viernes 10 de febrero 18:06:08 2023 - [https://central.grupomarilia. com.br/front/inventario.php](https://central.grupomarilia.com.br/front/inventory.php) [Viernes 10 de febrero 17:58:08 2023][info] Uso de memoria del agente GLPI: WSS=3313664 PFU=127082496 [Viernes 10 de febrero 18:03:36 2023][info] servidor objetivo0: servidor [https://central.grupomarilia .com.br/front/inventory.php](https://central.grupomarilia.com.br/front/inventory.php) [Viernes 10 de febrero 18:03:36 2023][info] enviando solicitud de prólogo al servidor0 [Viernes 10 de febrero 18:03:36 2023][error] [cliente http] error de comunicación: 406 No aceptable, [vie 10 feb 18:03:36 2023][error] No hay respuesta del servidor en https://central.grupomarilia.com.br/front/inventory.php [vie 10 feb 18:03:36 2023 ][info] target server0: próxima ejecución: Vie 10 Feb 18:19:36 2023 - https://central.grupomarilia.com.br/front/inventory.php [Vier 10 Feb 18:03:36 2023][info ] Uso de memoria del agente GLPI: WSS=3284992 PFU=128524288

Buenas tardes,

Lograste solucionar el Problema. yo tengo el mismo problema y nesecito una solucion, estaría agradecido si me das algunos alcances.
