### ISSUE TITLE
Widgets on the main page /front/central.php do not display the number of active issues and changes

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#14051]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

Widgets on the /front/central.php page cannot be configured to display ONLY active changes and issues, the total number is displayed.
When you click on the widget, only active changes or problems are displayed.

![image](https://user-images.githubusercontent.com/121490906/218088533-e4093d52-cc2c-48f8-896c-fd61158ef52d.png)

![image](https://user-images.githubusercontent.com/121490906/218088847-d594c2bb-3875-4e36-8bd6-16c213252332.png)
![image](https://user-images.githubusercontent.com/121490906/218089020-e0b60c44-4946-408a-a752-d41ca2de6a6a.png)

In the widget settings, there is no option to configure the display of only active changes or problems.
![image](https://user-images.githubusercontent.com/121490906/218089459-6ad6bead-019a-487c-bc48-aa13a4cbd080.png)

I would be very grateful to you if you make it possible to configure these widgets to display only active (unresolved) problems or changes.
Regards and thanks in advance

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.

Problem is that dashboard is counting items without applying any filter, but redirects to a list where default filters are applied (and are depending on defaut search for connected user).

2 solutions are possible:

1. Building dashboard using the default search for connected user. Problem is that dashboard would behave differently from a user to another one, and dashboard editor would not be able to predict the dashboard behaviour. Thus, it would probably require to review how dashboard caching is working to ensure that cache key take care of default search for connected user.

2. Force link to contain empty criteria, to ensure that default filters are not applied.

**Comment by cedric-anne** [comment]
I implemented second solution in #14425 , but I am not sure it is the best one.

**Comment by cedric-anne** [comment]
> A good and most correct solution would be to refine the widgets to be able to select the type of elements to display (for example, show the number of only active problems or changes) and set it so that when switching from the widget to the page and the search form, the type criterion is saved, the same as in the widget.

Feel free to propose a PR to implement it.

**Comment by ak47d** [comment]
> > A good and most correct solution would be to refine the widgets to be able to select the type of elements to display (for example, show the number of only active problems or changes) and set it so that when switching from the widget to the page and the search form, the type criterion is saved, the same as in the widget.
> 
> Feel free to propose a PR to implement it.

Please explain what needs to be done to make it happen.

**Comment by cedric-anne** [comment]
> Please explain what needs to be done to make it happen.

If you think you have skills to develop an enhancement, you can develop it and open a pull request with your changes.

**Comment by ak47d** [comment]
PR = pull request, now I understand )))
