### ISSUE TITLE
Display counters to user preferences don't update after change to "No"

### ISSUE THREAD

**Issue by twmarcelo** [glpi-project/glpi#14053]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

After change the option "Display Counters" on My Settings/Personalization to "No", isn't possible change to "Yes" again.

### Relevant log output

```shell
The default value in table glpi_users column show_count_on_tabs on database is NULL.
Changing the value to "No" in Front-end, is set 0 on the database.
Trying change the value to "Yes" again, the value on de database is not change.
```
![image](https://user-images.githubusercontent.com/123565345/218113495-7684ec72-48fb-45df-b37f-c8aee0655d6f.png)

### Page URL

https://glpi/front/preference.php

### Steps To reproduce

1. Go to Preferences User
2. Change Display Counters to "No" and Save
3. Try change do "Yes" and nothing happen.

### Your GLPI setup information

<details><pre>GLPI 10.0.5 ( => /var/www/html/glpi/htdocs)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux webserver 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64
PHP 7.4.33 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, ionCube Loader, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pdo_sqlsrv, pgsql, posix, session, shmop,
	soap, sockets, sodium, sqlite3, sqlsrv, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="60M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.6.11-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.11) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/htdocs/files/_cache has been validated.
Write access to /var/www/html/glpi/htdocs/config has been validated.
Write access to /var/www/html/glpi/htdocs/files/_cron has been validated.
Write access to /var/www/html/glpi/htdocs/files has been validated.
Write access to /var/www/html/glpi/htdocs/files/_dumps has been validated.
Write access to /var/www/html/glpi/htdocs/files/_graphs has been validated.
Write access to /var/www/html/glpi/htdocs/files/_lock has been validated.
Write access to /var/www/html/glpi/htdocs/files/_pictures has been validated.
Write access to /var/www/html/glpi/htdocs/files/_plugins has been validated.
Write access to /var/www/html/glpi/htdocs/files/_rss has been validated.
Write access to /var/www/html/glpi/htdocs/files/_sessions has been validated.
Write access to /var/www/html/glpi/htdocs/files/_tmp has been validated.
Write access to /var/www/html/glpi/htdocs/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi/htdocs/":
‣ "/var/www/html/glpi/htdocs/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/htdocs/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/htdocs/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi/htdocs/"
GLPI_CONFIG_DIR: "/var/www/html/glpi/htdocs/config"
GLPI_VAR_DIR: "/var/www/html/glpi/htdocs/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/htdocs/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/htdocs/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/htdocs/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/htdocs/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/htdocs/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/htdocs/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/htdocs/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/htdocs/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/htdocs/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/htdocs/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/htdocs/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/htdocs/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/htdocs/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/htdocs/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/htdocs/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/htdocs/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/htdocs/locales"
GLPI_VERSION: "10.0.5"
GLPI_SCHEMA_VERSION: "10.0.5@628dbfbb91eb4caf10c35969d9162b9300b141e0"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2022"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/htdocs/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/htdocs/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/htdocs/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.5.0 in (/var/www/html/glpi/htdocs/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/htdocs/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/htdocs/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/htdocs/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/htdocs/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/htdocs/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/htdocs/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/htdocs/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/htdocs/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/htdocs/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/htdocs/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/htdocs/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/htdocs/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/htdocs/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/htdocs/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/htdocs/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/htdocs/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/htdocs/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/htdocs/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/htdocs/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/htdocs/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/htdocs/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/htdocs/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/htdocs/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/htdocs/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/htdocs/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/htdocs/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/htdocs/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/htdocs/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/htdocs/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/htdocs/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/htdocs/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/htdocs/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/htdocs/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/htdocs/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/htdocs/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/htdocs/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/htdocs/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/htdocs/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/htdocs/vendor/symfony/polyfill-php82)

</details><details><summary>Plugins list</summary><pre> 
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.3     State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Mais Relatórios                Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Enabled                                 
		Install Method: Marketplace
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
Just tested on latest nightly, I cannot reproduce. Please check if you do.

**Comment by twmarcelo** [comment]
Hi, @trasher .

I did a Fresh install and reproduce the same problem.

I recorder a gif to show you.

![glpi4](https://user-images.githubusercontent.com/123565345/218533792-17378093-bfa7-4657-bd09-21e039bc2032.gif)

**Comment by trasher** [comment]
That does not help, I cannot reproduce (tried using super-admin and tech profiles). Without a way to reproduce, I can't help.

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue, but only on PHP 7.4. Global setting has to be set to 'Yes'.

**Comment by trasher** [comment]
Indeed I can confirm the issue with PHP 7.4? I've not yet been able to find what's wrong :/

**Comment by trasher** [comment]
OK, so, I think I found the issue...

```
% php82 -r 'var_dump(0 != "NULL");'
bool(true)
```

while

```
 % php74 -r 'var_dump(0 != "NULL");'
bool(false)
```

Problem is the fix is even worst than the initial issue; that break a lot of things (for all PHP versions of course).
 Since PHP 7.4 is no longer maintained, we officially recommend not to use it, and switch to PHP 8.0, at least.

Therefore, this issue will not be fixed - sorry.
