### ISSUE TITLE
Unable to change password for super-user where password expires. Local server

### ISSUE THREAD

**Issue by mati294** [glpi-project/glpi#14066]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Cannot log in to the super-admin account, nor does any message pop up as in the case of a wrong password.
I noticed that the address of the website changes after the first attempt to log in to the address "http://localhost/glpi/index.php?redirect=%2Ffront%2Fupdatepassword.php".
The address suggests changing the password, but it does nothing.
The password is correct, which I checked and resetting the password in mysql does not fix the problem.

I found a similar issue https://github.com/glpi-project/glpi/issues/11426#issue-1220506074
however his solution doesn't work in my case (page not found)

### Relevant log output

```shell
/var/www/html/glpi/files/_log/access-errors.log

2023-01-04 12:22:34 [3@adxx-VirtualBox]

User ID: 3 tried to access or perform an action on /glpi/front/user.form.php?id=3 with insufficient rights. Additional information: Missing READ right. Cannot view the item.

	Stack Trace:

		/var/www/html/glpi/src/CommonDBTM.php:6309 displayRightError()

		/var/www/html/glpi/src/CommonDBTM.php:6399 displayAccessDeniedPage()

		/var/www/html/glpi/front/user.form.php:241 displayFullPageForItem()
```

### Steps To reproduce

Go to http://localhost/glpi/front/config.form.php ->Security
Set Password expiration period (in days) for 30
Open terminal and login to your mysql server and use glpi_database
Set the date at least 30 days earlier with the command: Update glpi_users set password_last_update='2023-2-2' where name='glpi'; or wait 30 days
Done

### Anything else?

The problem can be solved with the same command ("Update glpi_users set password_last_update='2023-2-2' where name='glpi';") setting the date not later than 30 days from the system date.

**Comment by cedric-anne** [comment]
Hi,

It should be fixed by #14373
