### ISSUE TITLE
SNMP inventory (printers, switches) lock the "ifinbytes" and "ifoutbytes" fields.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#14063]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6 + glpiinventory 1.1.0

### Bug description

During snmp inventory (printers, switches), the "ifinbytes" and "ifoutbytes" fields receive the "lock" status

![image](https://user-images.githubusercontent.com/16879167/218318551-43814aae-049b-4669-b77f-1f550a5ab40c.png)

![image](https://user-images.githubusercontent.com/16879167/218318650-f1b87453-e72d-4f58-b612-0fc7f958db6c.png)

![image](https://user-images.githubusercontent.com/16879167/218318840-05207edc-4cbf-4936-9173-da604bdf3b1d.png)

![image](https://user-images.githubusercontent.com/16879167/218319187-b3c276d7-e76c-4a26-8b12-5c9114f8fd5e.png)

### Page URL

/front/lockedfield.php

### Steps To reproduce

Add a device. 
Perform a network inventory. 
Perform an snmp inventory.

**Comment by trasher** [comment]
I confirm the issue

**Comment by stonebuzz** [comment]
Hi @kofe88 
can you try this

https://github.com/glpi-project/glpi/pull/14064

**Comment by kofe88** [comment]
> Hi @kofe88 can you try this
> 
> #14064

@stonebuzz 

I confirm, this solved the problem, thank you!
