### ISSUE TITLE
Slowness in DEBUG_MODE

### ISSUE THREAD

**Issue by calidadcarm** [glpi-project/glpi#14069]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

Slowness in DEBUG_MODE

translation stacking on page load in DEBUG_MODE.

/front/locale.php?domain=formcreator&version=2.12.5&debug=

![imagen](https://user-images.githubusercontent.com/50906293/218524496-efb17284-97d8-46be-9fb7-577b22bc0664.png)

![imagen](https://user-images.githubusercontent.com/50906293/218528685-ae4d56fd-1606-47ef-b757-f760406bdf0f.png)

### Page URL

home page or any other.

### Your GLPI setup information

Operating system: Linux glpi-pru 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="1200" memory_limit="2G" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="5M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi-pru.es Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/109.0
Server Software: MySQL Enterprise Server - Commercial
	Server Version: 8.0.31-commercial
	Server SQL Mode: 
	Host info: 0.0.0.0 via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (8.0.31) - Perfect!Database version seems correct (8.0.31) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to /opt/glpi/cache has been validated.Write access to /opt/glpi/cache has been validated.
Write access to /etc/glpi/config has been validated.Write access to /etc/glpi/config has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /opt/glpi/session has been validated.Write access to /opt/glpi/session has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.Write access to /var/lib/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.

**Comment by cconard96** [comment]
Translations and other resources like CSS are not cached when debug mode is enabled. Lowered performance is expected.

If you aren't trying to debug an issue, it is best to leave debug mode disabled if performance suffers too much.

**Comment by trasher** [comment]
Also, 9.5 is no longer maintained, please consider upgrading.
