### ISSUE TITLE
Translation "Create a change from this ticket"

### ISSUE THREAD

**Issue by DZbox** [glpi-project/glpi#14060]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,
there is an issue with language translations into some languages in linking tabs to other tickets, changes, problems and projects

### Steps To reproduce

Open a ticket
Switch language to Italian, Dansk or Polski (English, French are looking fine)
Go to ticket tabs "Changes", "Problems". It is also aplicable to Projects, Changes, Problem tabs
"Create a %s from this %s" is not translated. We see "Create a Cambios from this Tiquetes"

![image](https://user-images.githubusercontent.com/72818340/218250905-4e8e82fd-4c76-43d4-9c59-de2b4eeb5725.png)

**Comment by cconard96** [comment]
Translations are done on Transifex:
https://www.transifex.com/glpi/GLPI/dashboard/

The "Create a %s from this %s" term was a relatively recent addition, so it may not be translated for all languages yet. You can request access to languages on Transifex and contribute the translations if you want.

**Comment by DZbox** [comment]
Hi @cconard96, sorry for that.
The translation is complete on Transifex now. I take the .po file, convert it into .mo, placed both of them into /GLPI/locales. It there another step to do? Or it can be applied only with new GLPI release

**Comment by cconard96** [comment]
After updating the "mo" files locally, you will need to clear the server cache. You can do that with the CLI tool "bin/console cache:clear" or by enabling debug mode in the web app, going to Setup > General > Performance tab and clicking the Reset button in the Translation cache section.

**Comment by DZbox** [comment]
> After updating the "mo" files locally, you will need to clear the server cache. You can do that with the CLI tool "bin/console cache:clear" or by enabling debug mode in the web app, going to Setup > General > Performance tab and clicking the Reset button in the Translation cache section.

Thank you so much!
