### ISSUE TITLE
Tickets - Project selection doesn't filter Project Tasks

### ISSUE THREAD

**Issue by tnrhsv** [glpi-project/glpi#14065]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When selecting a Ticket and moving onto the project tab inside, we usually picked out the project in the upper dropdown and then clicked on the bottom dropdown to pick the related project task. Before (10.0.5) it filtered the project tasks in relation to the selected project. 
Right now it just shows all project tasks from all projects.

![grafik](https://user-images.githubusercontent.com/105439719/218410435-c27777d7-3cd5-4b1a-8445-25420258b823.png)
![grafik](https://user-images.githubusercontent.com/105439719/218410482-4356dfaf-2fb5-485a-ac03-0323afe63c48.png)
![grafik](https://user-images.githubusercontent.com/105439719/218410525-c3ce8557-50b5-4e79-a9b0-a9e26d8ddad7.png)

### Steps To reproduce

1. Create 2 Projects, create at least 1 project task in each project with similar names
2. Create a Ticket, open the Project sub-tab & pick out Project No. 1
3. Try to filter for Project Task Name - All Project Tasks are visible

**Comment by trasher** [comment]
Please test if #14067 fix your issue.
