### ISSUE TITLE
After upgrade to 10.0.6 KB search is not more working

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi#14061]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Upgrade from 10.0.5 to 10.0.6
The KB search does not work and any search request returns: "no item found"
![image](https://user-images.githubusercontent.com/6400595/218262762-af497429-71e1-4fb8-abcd-b491665f9c82.png)

### Relevant log output

```shell
no errors found
```

### Steps To reproduce

1. go to KB page
2. search for a existing KB entry

**Comment by cconard96** [comment]
Hi,

This has been fixed in https://github.com/glpi-project/glpi/pull/13877.
