### ISSUE TITLE
Can't unlock fileds becasue checkbox is missing

### ISSUE THREAD

**Issue by HiopsNerevar** [glpi-project/glpi#14078]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

I have some locked fields, and I try unlock them but I can't check filed. 
If check main ckeckbox and push Action opens popup with "No selected items"

![image](https://user-images.githubusercontent.com/11775018/218752764-62b51972-e6a4-4537-99b6-9b6b100aac97.png)

The only thing I don't now it's when bug started. When i update from v9 or change FusionInventory to GLPI Inventory.

### Page URL

http://help/front/computer.form.php

### Steps To reproduce

1. Open some computer
2. Open Unlock tab
3. Try to unlock the field

### Your GLPI setup information

<details><summary>Информация о системе, установке и конфигурации</summary><pre>GLPI 10.0.6 ( => /home/hiops/help)
Installation mode: TARBALL
Current language:ru_RU

</details><details><summary>Server</summary><pre> 
Operating system: Linux kcson-web 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 8.1.14 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at help Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.5.18-MariaDB-1:10.5.18+maria~deb11
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: hiops@localhost/help
	Host info: Localhost via UNIX socket
	
PHP version (8.1.14) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.18) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/hiops/help/files/_cache has been validated.
Write access to /home/hiops/help/config has been validated.
Write access to /home/hiops/help/files/_cron has been validated.
Write access to /home/hiops/help/files has been validated.
Write access to /home/hiops/help/files/_dumps has been validated.
Write access to /home/hiops/help/files/_graphs has been validated.
Write access to /home/hiops/help/files/_lock has been validated.
Write access to /home/hiops/help/files/_pictures has been validated.
Write access to /home/hiops/help/files/_plugins has been validated.
Write access to /home/hiops/help/files/_rss has been validated.
Write access to /home/hiops/help/files/_sessions has been validated.
Write access to /home/hiops/help/files/_tmp has been validated.
Write access to /home/hiops/help/files/_uploads has been validated.
The following directories should be placed outside "/home/hiops/help":
‣ "/home/hiops/help/files" ("GLPI_VAR_DIR")
‣ "/home/hiops/help/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/hiops/help/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/hiops/help"
GLPI_CONFIG_DIR: "/home/hiops/help/config"
GLPI_VAR_DIR: "/home/hiops/help/files"
GLPI_MARKETPLACE_DIR: "/home/hiops/help/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/home/hiops/help/files"
GLPI_CACHE_DIR: "/home/hiops/help/files/_cache"
GLPI_CRON_DIR: "/home/hiops/help/files/_cron"
GLPI_DUMP_DIR: "/home/hiops/help/files/_dumps"
GLPI_GRAPH_DIR: "/home/hiops/help/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/hiops/help/files/_locales"
GLPI_LOCK_DIR: "/home/hiops/help/files/_lock"
GLPI_LOG_DIR: "/home/hiops/help/files/_log"
GLPI_PICTURE_DIR: "/home/hiops/help/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/hiops/help/files/_plugins"
GLPI_RSS_DIR: "/home/hiops/help/files/_rss"
GLPI_SESSION_DIR: "/home/hiops/help/files/_sessions"
GLPI_TMP_DIR: "/home/hiops/help/files/_tmp"
GLPI_UPLOAD_DIR: "/home/hiops/help/files/_uploads"
GLPI_INVENTORY_DIR: "/home/hiops/help/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/home/hiops/help/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/home/hiops/help/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/hiops/help/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/hiops/help/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/home/hiops/help/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/hiops/help/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/hiops/help/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/hiops/help/vendor/iamcal/lib_autolink)
sabre/dav in (/home/hiops/help/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/hiops/help/vendor/sabre/http/lib)
sabre/uri in (/home/hiops/help/vendor/sabre/uri/lib)
sabre/vobject in (/home/hiops/help/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/hiops/help/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/hiops/help/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/hiops/help/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/hiops/help/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/hiops/help/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/hiops/help/vendor/elvanto/litemoji/src)
symfony/console in (/home/hiops/help/vendor/symfony/console)
scssphp/scssphp in (/home/hiops/help/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/hiops/help/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/hiops/help/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/hiops/help/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/hiops/help/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/hiops/help/vendor/ramsey/uuid/src)
psr/log in (/home/hiops/help/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/hiops/help/vendor/psr/simple-cache/src)
psr/cache in (/home/hiops/help/vendor/psr/cache/src)
league/csv in (/home/hiops/help/vendor/league/csv/src)
mexitek/phpcolors in (/home/hiops/help/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/hiops/help/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/hiops/help/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/hiops/help/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/hiops/help/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/hiops/help/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/hiops/help/vendor/symfony/cache)
html2text/html2text in (/home/hiops/help/vendor/html2text/html2text/src)
symfony/css-selector in (/home/hiops/help/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/hiops/help/vendor/symfony/dom-crawler)
twig/twig in (/home/hiops/help/vendor/twig/twig/src)
twig/string-extra in (/home/hiops/help/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home/hiops/help/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://192.168.1.5', Port: '389', BaseDN: 'OU=Active Users,OU=CSON,DC=cson,DC=lan', Connection filter:
		'(objectclass=user)', RootDN: 'CN=GLPIauth,OU=CSON,DC=cson,DC=lan', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mailbox)

</details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Добавление данных        Version: 2.12.0     State: Enabled                         
		        Install Method: Marketplace

</pre></details>

**Comment by stonebuzz** [comment]
Hi @HiopsNerevar  

it's a ```global``` lock.

You need to got here (if you have the rights) : 

![image](https://user-images.githubusercontent.com/7335054/218754691-46033ab8-0ba8-4acf-875e-40c193ec7896.png)


Best regards

**Comment by HiopsNerevar** [comment]
Hi! Hm. I have a rights (I have Super-Admin role). But I don't have this page. I use GLPI Inventory plugin and my page looks like FusionInventory page. If I disabled plugin - menu item disappears completely.

![image](https://user-images.githubusercontent.com/11775018/218758735-20ac28bc-bfea-4c48-ac48-fe224ef91a50.png)

But if I try go to front/lockedfield.php url i have "You don't have permission to perform this action"

**Comment by stonebuzz** [comment]
please check rights here

![image](https://user-images.githubusercontent.com/7335054/218762210-1849cb7a-7ba7-40f7-84d7-b25530faeb1f.png)

**Comment by HiopsNerevar** [comment]
Yes! Huge thanks! Unselect all - Save - Select All helped. Inventory page and unlock fields ceckboxes appeared.
