### ISSUE TITLE
Knowledge base search, not working

### ISSUE THREAD

**Issue by virtazp** [glpi-project/glpi#14071]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When searching in the knowledge base, the results return empty

### Relevant log output

```shell
No error !
```

### Page URL

/front/knowbaseitem.php?contains=xxxxx&_glpi_csrf_token=xxxxxxx

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.6 ( => /var/www/xxxx)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux xxxx 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64
PHP 7.4.33 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="8M" 
Software: nginx/1.18.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.18-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxxxxx
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.18) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/xxxx/files/_cache has been validated.
Write access to /var/www/xxxx/config has been validated.
Write access to /var/www/xxxx/files/_cron has been validated.
Write access to /var/www/xxxx/files has been validated.
Write access to /var/www/xxxx/files/_dumps has been validated.
Write access to /var/www/xxxx/files/_graphs has been validated.
Write access to /var/www/xxxx/files/_lock has been validated.
Write access to /var/www/xxxx/files/_pictures has been validated.
Write access to /var/www/xxxx/files/_plugins has been validated.
Write access to /var/www/xxxx/files/_rss has been validated.
Write access to /var/www/xxxx/files/_sessions has been validated.
Write access to /var/www/xxxx/files/_tmp has been validated.
Write access to /var/www/xxxx/files/_uploads has been validated.
The following directories should be placed outside "/var/www/xxxx":
‣ "/var/www/xxxx/files" ("GLPI_VAR_DIR")
‣ "/var/www/xxxx/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/xxxx/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/xxxx"
GLPI_CONFIG_DIR: "/var/www/xxxx/config"
GLPI_VAR_DIR: "/var/www/xxxx/files"
GLPI_MARKETPLACE_DIR: "/var/www/xxxx/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/xxxx/files"
GLPI_CACHE_DIR: "/var/www/xxxx/files/_cache"
GLPI_CRON_DIR: "/var/www/xxxx/files/_cron"
GLPI_DUMP_DIR: "/var/www/xxxx/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/xxxx/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/xxxx/files/_locales"
GLPI_LOCK_DIR: "/var/www/xxxx/files/_lock"
GLPI_LOG_DIR: "/var/www/xxxx/files/_log"
GLPI_PICTURE_DIR: "/var/www/xxxx/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/xxxx/files/_plugins"
GLPI_RSS_DIR: "/var/www/xxxx/files/_rss"
GLPI_SESSION_DIR: "/var/www/xxxx/files/_sessions"
GLPI_TMP_DIR: "/var/www/xxxx/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/xxxx/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/xxxx/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/xxxx/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/xxxx/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/xxxx/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/xxxx/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/xxxx/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/xxxx/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/xxxx/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/xxxx/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/xxxx/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/xxxx/vendor/sabre/http/lib)
sabre/uri in (/var/www/xxxx/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/xxxx/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/xxxx/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/xxxx/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/xxxx/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/xxxx/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/xxxx/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/xxxx/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/xxxx/vendor/symfony/console)
scssphp/scssphp in (/var/www/xxxx/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/xxxx/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/xxxx/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/xxxx/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/xxxx/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/xxxx/vendor/ramsey/uuid/src)
psr/log in (/var/www/xxxx/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/xxxx/vendor/psr/simple-cache/src)
psr/cache in (/var/www/xxxx/vendor/psr/cache/src)
league/csv in (/var/www/xxxx/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/xxxx/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/xxxx/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/xxxx/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/xxxx/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/xxxx/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/xxxx/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/xxxx/vendor/symfony/cache)
html2text/html2text in (/var/www/xxxx/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/xxxx/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/xxxx/vendor/symfony/dom-crawler)
twig/twig in (/var/www/xxxx/vendor/twig/twig/src)
twig/string-extra in (/var/www/xxxx/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/xxxx/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/xxxx/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/xxxx/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (xxxx)

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.18.1     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportements                  Version: 2.7.1      State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.1+1.0 State: Enabled                                 
		Install Method: Manual
	customnotifications  Name: Mail ticket urgency            Version: 1.0.0      State: Enabled                                 
		Install Method: Manual
	singlesignon         Name: Single Sign-on                 Version: 1.3.3      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
Probably fixed as of #13877. Try with latest nightly, feel free to reopen if you reproduce.
