### ISSUE TITLE
Cannot export Global Assets

### ISSUE THREAD

**Issue by Piputrrrr** [glpi-project/glpi#14079]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello all,

i cannot export any result on Global assets, i am super-admin and it returned me 
"You don't have permission to perform this action."

### Page URL

https://glpi/front/report.dynamic.php?item_type=AllAssets&sort%5B0%5D=1&order%5B0%5D=ASC&start=0criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=vhs&display_type=2

### Steps To reproduce

1. Asets
2. Global
3. Search something
4. export to ...

### Your GLPI setup information

Operating system: Linux CVHP-GLPI 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,

**Comment by Piputrrrr** [comment]
i don't know if it's a bug or not, can you please help me ?

Thank you,

**Comment by cconard96** [comment]
Fixed by #14127 for 10.0.7
