### ISSUE TITLE
Network names are not automatically assigned to computers during inventory (should they?)

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#14087]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Shouldn't the network name of the port (connection) match the network name of the computer from the inventory?
With automatic inventory, it is not filled in.

![image](https://user-images.githubusercontent.com/16879167/218958071-53b41639-95d1-43dc-aa89-9be6dd4184e1.png)

As a result, the directory of network names looks absolutely unreadable, because it is not clear which name is followed by which ip address.

![image](https://user-images.githubusercontent.com/16879167/218958357-47a4a550-7009-4b69-bd8d-0a255f3c82be.png)

[computer_0_109.zip](https://github.com/glpi-project/glpi/files/10740210/computer_0_109.zip)

**Comment by trasher** [comment]
As far as I can see, no, NetworkName has low meaning here. But as far as I remember, this is kind of required so the network (in GLPI meaning) works as expected.
So, they should probably not be created from inventory, we do not have any relevant informaiton to put in them. But reworking the way GLPI handles network would be a nightmare.

This issue does not seems really important anyways, I guess this is not the only part of GLPI the inventory kind of "spam".

**Comment by cedric-anne** [comment]
Fixed by #14090.

**Comment by berilslv** [comment]
Im facing simillar issue, using GLPI 10.0.10, glpi inventory plugin:
Each time netinventory job runs, it creates new network name, and make network device management pretty dirty. It happens only for fortiswitch devices.
Is there any workaround?
![image](https://github.com/glpi-project/glpi/assets/46807385/4df6fdba-82cc-4e81-ac67-eee049cc93c4)
