### ISSUE TITLE
Computers that are automatically configured do not have the ability to change the mac address of the network port.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#14086]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Computers that are automatically configured do not have the ability to change the mac address of the network port.

![image](https://user-images.githubusercontent.com/16879167/218954728-718038ca-9bbb-44ef-a1b2-a461943f83c2.png)

![image](https://user-images.githubusercontent.com/16879167/218954789-87c4a87a-fa96-476f-b9a1-e0bb9f3b6219.png)

If the port is created manually, then the mac address and other parameters can be changed.

![image](https://user-images.githubusercontent.com/16879167/218954933-86799408-6233-4854-8f62-3a17a3f4df0f.png)

![image](https://user-images.githubusercontent.com/16879167/218954987-11a3e5ad-267f-4c5d-a511-c2856044bccb.png)

[computer_0_109.zip](https://github.com/glpi-project/glpi/files/10740190/computer_0_109.zip)

**Comment by trasher** [comment]
As far as I can see, this is not strictly related on inventory; On local test file that creates several network ports for a computer, some have the information, some does not have it. In some cases, it also may be legitimate, but it seems there is a bug anyways.

**Comment by stonebuzz** [comment]
hi @kofe88 

can you try this

https://github.com/glpi-project/glpi/pull/14089

Best regards

**Comment by stonebuzz** [comment]
disregard my previous comment, I misunderstood your problem

You can't update ```MAC``` because your ```NetworkPort``` is not an ```Ethernet``` type

From your ivnentory file ```type``` is missing 
```json
           {
                "description": "Realtek PCIe FE Family Controller",
                "ipaddress": "192.168.9.10",
                "ipdhcp": "192.168.9.3",
                "ipgateway": "192.168.9.3",
                "ipmask": "255.255.252.0",
                "ipsubnet": "192.168.9.0",
                "mac": "E0:CB:4E:D5:55:19",
                "pciid": "10EC:8136:83D3:1043",
                "pnpdeviceid": "PCI\\VEN_10EC&DEV_8136&SUBSYS_83D31043&REV_02\\4&2f20c4e&0&00E2",
                "speed": "100",
                "status": "up",
                "virtualdev": false
            },
```
What is the version of the agent used?

**Comment by trasher** [comment]
So, the bug is we mostly do not have the information for windows OS before windows 8... 
There is nothing we can do, guessing the port type will lead to errors. BTW, this worked exactly the same way in fusion plugin.

Please also note in that case the port does not have any MAC address. The one you talk about in #14085 is in the netowkr card component, not in an associated networkport.

**Comment by kofe88** [comment]
@stonebuzz @trasher 
Hi.

Windows is used newer than Windows 8, namely Windows 10. Here is from another inventory file, there is also no port type. The agent is used version 1.4

```json

        "operatingsystem": {
            "arch": "64-bit",
            "boot_time": "2023-01-25 10:36:03",
            "dns_domain": "work",
            "fqdn": "cad.work",
            "full_name": "\u041c\u0430\u0439\u043a\u0440\u043e\u0441\u043e\u0444\u0442 Windows 10 Pro",
            "install_date": "2022-12-05 12:27:20",
            "kernel_name": "MSWin32",
            "kernel_version": "10.0.19045",
            "name": "Windows",
            "timezone": {
                "name": "Europe\/Moscow",
                "offset": "+0300"
            },
            "version": "22H2"
        },

```

Networks

```json

        "networks": [
            {
                "description": "TAP-Windows Adapter V9",
                "mac": "00:FF:72:0B:00:84",
                "pnpdeviceid": "ROOT\\NET\\0001",
                "speed": "1000",
                "status": "down",
                "virtualdev": true
            },
            {
                "description": "Realtek PCIe GbE Family Controller",
                "ipaddress": "192.168.9.132",
                "ipdhcp": "192.168.9.3",
                "ipgateway": "192.168.9.3",
                "ipmask": "255.255.248.0",
                "ipsubnet": "192.168.9.0",
                "mac": "A8:A1:59:70:15:3B",
                "pciid": "10EC:8168:8168:1849",
                "pnpdeviceid": "PCI\\VEN_10EC&DEV_8168&SUBSYS_81681849&REV_15\\3A147059A1A8000000",
                "speed": "1000",
                "status": "up",
                "virtualdev": false
            },
            {
                "description": "Realtek PCIe GbE Family Controller",
                "ipaddress6": "fe80::ffa6:f9f8:beb4:46b8",
                "ipmask6": "ffff:ffff:ffff:ffff::",
                "ipsubnet6": "fe80::",
                "mac": "A8:A1:59:70:15:3B",
                "pciid": "10EC:8168:8168:1849",
                "pnpdeviceid": "PCI\\VEN_10EC&DEV_8168&SUBSYS_81681849&REV_15\\3A147059A1A8000000",
                "speed": "1000",
                "status": "up",
                "virtualdev": false
            }
        ],

```

Agent 1.4

```json

        "versionclient": "GLPI-Agent_v1.4",
        "versionprovider": {
            "comments": [
                "Provided by Teclib Edition",
                "Installer built on Fri Jul  1 09:35:20 2022 UTC",
                "Built with Strawberry Perl 5.36.0",
                "Built on github actions windows image for glpi-project\/glpi-agent repository"
            ],
            "etime": 32,
            "name": "GLPI",
            "perl_config": [
                "gccversion: 8.3.0",
                "defines: use64bitint usedl useithreads uselargefiles usemallocwrap usemultiplicity usemymalloc=n usenm=false useopcode useperlio useposix useshrplib usethreads usevendorprefix usevfork=false"
            ],
            "perl_exe": "C:\\Program Files\\GLPI-Agent\\perl\\bin\\glpi-agent.exe",
            "perl_inc": "C:\/Program Files\/GLPI-Agent\/perl\/agent:.\/lib:C:\\Program Files\\GLPI-Agent\\perl\\agent:C:\\Program Files\\GLPI-Agent\\perl\\site\\lib:C:\\Program Files\\GLPI-Agent\\perl\\vendor\\lib:C:\\Program Files\\GLPI-Agent\\perl\\lib:C:\/Program Files\/GLPI-Agent\/perl\/site\/lib:C:\/Program Files\/GLPI-Agent\/perl\/vendor\/lib:C:\/Program Files\/GLPI-Agent\/perl\/lib",
            "perl_module": [
                "LWP @ 6.67",
                "LWP::Protocol @ 6.67",
                "IO::Socket @ 1.49",
                "IO::Socket::INET @ 1.49",
                "Net::SSLeay @ 1.92",
                "Net::SSLeay uses OpenSSL 1.1.1i  8 Dec 2020",
                "HTTP::Status @ 6.37",
                "HTTP::Response @ 6.37"
            ],
            "perl_version": "v5.36.0",
            "program": "C:\\Program Files\\GLPI-Agent\\perl\\bin\\glpi-win32-service",
            "version": "1.4"
        },

```

**Comment by trasher** [comment]
> Without a `type` in newtoks, that won't work. Seems a Windows or an agent issue.

I did not see the update... All will be fine then ;)

**Comment by AldarisPale** [comment]
@trasher - I am hitting the same bug.
Although in this case the problem seems to be agent, one question still -  if the mac address is shown on the port list (and is now being shown while opening the "details" for the adapter/port - how can the mac address be manually modified, as there's no field "MAC" when opening the details, yet it's magically there in the port list resulting in magic non-modifiable field.
