### ISSUE TITLE
[inventory] Duplicate entry 'Computer-' for key 'unicity' - and error 500 from the agent

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi#14088]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0-f00a4a1

### Bug description

Hi,
the inventory of some computers does not work anymore (error 500 in the logs)
i don't know if it's glpi or glpi-agent concern ...

### Relevant log output

```shell
php-errors.log :
[2023-02-15 10:15:38] glpiphplog.ERROR:   *** PHP User Error (256): Duplicate entry 'Computer-4324-60150' for key 'unicity' in /var/www/glpi/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()
  src/Inventory/Asset/Software.php:878               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:445               Glpi\Inventory\Asset\Software->storeAssetLink()
  src/Inventory/Asset/MainAsset.php:874              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:794              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1519                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:571              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins/glpiinventory/front/communication.php:72   include_once()
  plugins/glpiinventory/index.php:45                 include_once()

nothing in sql-errors.log

glpi-agent.log :
[glpi-agent.log](https://github.com/glpi-project/glpi/files/10741563/glpi-agent.log)

```

### Steps To reproduce

a lot of computers inventory works ... but some not ...
in inventory information of the computer i have this :
Dernier inventaire
15-02-2023 10:15

but in the list of computers i have this : 
DATE DE DERNIER INVENTAIRE
25-01-2023 09:11

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.7-dev ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux test-glpi 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.10 apache2handler (Core, FFI, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at test.xxx.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.41
Server Software: Ubuntu 22.04
	Server Version: 10.6.11-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.11) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.7-dev"
GLPI_SCHEMA_VERSION: "10.0.7-dev@78ae60f90e13732fb36834521fd38da3735f1d2d"
GLPI_MARKETPLACE_PRERELEASES: true
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpi/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://ad1.xxx.fr', Port: '636', BaseDN: 'DC=xxx,DC=fr', Connection filter:
		'(&(objectCategory=user)(objectClass=user))', RootDN: 'CN=GLPI-LDAP,OU=LDAP,OU=Administration
		DSI,OU=Pseudo,DC=xxx,DC=fr', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mail.xxx.fr)

</details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertes                        Version: 1.10.5     State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.20.0     State: Enabled                                 
		Install Method: Manual
	printercounters      Name: Compteurs Imprimantes          Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.1      State: Not installed                           
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.12.0     State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                
		 Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.14.1     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual
	reservation          Name: Reservation                    Version: 2.4.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

I can't find a common point with the ones that don't work, so I don't know how to find the origin of the problem...

thank you :)

**Comment by stonebuzz** [comment]
Hi @TheRoby 
can you provide related inventory file ?

**Comment by stonebuzz** [comment]
@krenaudUR 
can you provide related inventory file too ?

**Comment by stonebuzz** [comment]
Computer-xxxx-xxxxx

second part (xxxx) is computer ID

**Comment by TheRoby** [comment]
[SERIAL.xxx.fr-2022-03-10-14-38-20.zip](https://github.com/glpi-project/glpi/files/10744304/SERIAL.xxx.fr-2022-03-10-14-38-20.zip)

**Comment by TheRoby** [comment]
do you need more computers ?

**Comment by stonebuzz** [comment]
I do not reproduce ATM

From DB you can run this queries to get related software of this error log

``` Duplicate entry 'Computer-4324-60150'```

SELECT softwares_id FROM glpi_softwareversions WHERE id = 60150

SELECT * FROM glpi_softwares WHERE id =  {softwares_id from previous SQL query}

**Comment by TheRoby** [comment]
id : 11370
name : Microsoft Office Standard 2013

**Comment by stonebuzz** [comment]
Did you see it two times from related computer

![image](https://user-images.githubusercontent.com/7335054/219068763-938ede54-3db3-41a8-a4a1-d0fe49628338.png)

**Comment by TheRoby** [comment]
No, only one in system_component (on Microsoft Office Standard 2013 filter) (with inventory from 25-01-2023)

**Comment by stonebuzz** [comment]
Which one have ID 11370
application or system_component ?

**Comment by TheRoby** [comment]
i have only the system_component, and it's 11370
in global software i have 2 with the same name, id 11370 (system_component) and id 11362 (Applications)

**Comment by stonebuzz** [comment]
Same publisher for each (Microsoft Corporation) ?

Have you some dictionary rules ?

**Comment by TheRoby** [comment]
Only Microsoft, and yes i have dictionary rules

![image](https://user-images.githubusercontent.com/6053818/219074941-9e1922b9-5e09-4a8b-96cb-fa04252e57e5.png)

**Comment by stonebuzz** [comment]
Hi @TheRoby 
it's a "Dictionnary of software" or "Dictionary of manufacturers"?

Best regards

**Comment by TheRoby** [comment]
Hi @stonebuzz 
Dictionary of manufacturers :)

**Comment by stonebuzz** [comment]
I reproduce with your rule =)

@krenaudUR have you some dictionnary rules too?

**Comment by stonebuzz** [comment]
Indeed, without i reproduced too.

**Comment by stonebuzz** [comment]
@TheRoby @krenaudUR 

which agent / version are you using?

**Comment by stonebuzz** [comment]
@TheRoby 

I understand why you have this error

in your inventory file ```Microsoft Office Standard 2013``` exists twice

```xml
    <SOFTWARES>
      <ARCH>i586</ARCH>
      <FROM>registry</FROM>
      <GUID>{90150000-0012-0000-0000-0000000FF1CE}</GUID>
      <INSTALLDATE>11/01/2023</INSTALLDATE>
      <NAME>Microsoft Office Standard 2013</NAME>
      <PUBLISHER>Microsoft Corporation</PUBLISHER>
      <SYSTEM_CATEGORY>system_component</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>MsiExec.exe /X{90150000-0012-0000-0000-0000000FF1CE}</UNINSTALL_STRING>
      <VERSION>15.0.4569.1506</VERSION>
    </SOFTWARES>

    <SOFTWARES>
      <ARCH>i586</ARCH>
      <FROM>registry</FROM>
      <GUID>Office15.STANDARD</GUID>
      <INSTALLDATE>18/08/2020</INSTALLDATE>
      <NAME>Microsoft Office Standard 2013</NAME>
      <NO_REMOVE>0</NO_REMOVE>
      <PUBLISHER>Microsoft Corporation</PUBLISHER>
      <SYSTEM_CATEGORY>application</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>&quot;C:\Program Files (x86)\Common Files\Microsoft Shared\OFFICE15\Office Setup Controller\setup.exe&quot; /uninstall STANDARD /dll OSETUP.DLL</UNINSTALL_STRING>
      <VERSION>15.0.4569.1506</VERSION>
    </SOFTWARES>
```

@g-bougard an idea?

**Comment by TheRoby** [comment]
I have the same error for other computer and other software, you need anything else ?

**Comment by stonebuzz** [comment]
related inventory file to check if it the same behavior (duplicate software)

**Comment by g-bougard** [comment]
The fact is this seems to be 2 different softwares from the system point of view:
 - installation date is different
 - uninstall string is even different
 - even category is different...
 - for the second one, the guid seems weird...
My guess is the software with the same version was installed 2 times on the same computer but in a different way and the second installation didn't cleanup the first one as expected. You may complain to the publisher for that O:)
Anyway same software can be installed for different users, so same software name on a computer should be supported?

**Comment by TheRoby** [comment]
86988 / 21630 : Microsoft Visual C++
[SERIAL.mulhouse.fr-2022-03-10-12-45-35.zip](https://github.com/glpi-project/glpi/files/10754967/SERIAL.mulhouse.fr-2022-03-10-12-45-35.zip)

**Comment by stonebuzz** [comment]
> So It's related to a software problem ? In my case I can delete all software and let all the agent do their inventory again. Can it solve the problem like that ?

No, the first works but after it thrown error

**Comment by trasher** [comment]
We'll tell you when the issue will be solved; we do not know.

**Comment by trasher** [comment]
Issue was due to an UTF-8 invisible character in one of application names.

**Comment by TheRoby** [comment]
Hi @trasher,
Thank you :)
it's ok for Office, but not for Microsoft Visual C++ ...

[2023-02-17 10:45:19] glpiphplog.ERROR:   *** PHP User Error (256): Duplicate entry 'Computer-7233-86988' for key 'unicity' in /var/www/glpi/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()
  src/Inventory/Asset/Software.php:878               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:445               Glpi\Inventory\Asset\Software->storeAssetLink()
  src/Inventory/Asset/MainAsset.php:874              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:794              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1519                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:571              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins/glpiinventory/front/communication.php:72   include_once()
  plugins/glpiinventory/index.php:45                 include_once()

**Comment by stonebuzz** [comment]
Like ```Microsoft Office Standard 2013```

From DB you can run this queries to get related software of this error log

``` Duplicate entry 'Computer-7233-86988'```

SELECT softwares_id FROM glpi_softwareversions WHERE id = 86988

SELECT * FROM glpi_softwares WHERE id =  {softwares_id from previous SQL query}

To identify related software / version from your inventory file

**Comment by TheRoby** [comment]
Yes : 
![image](https://user-images.githubusercontent.com/6053818/219611666-c0600d82-a6c2-4209-89d0-24b906fb2241.png)
Inventory file is up : https://github.com/glpi-project/glpi/issues/14088#issuecomment-1432872020

**Comment by stonebuzz** [comment]
Can you provide version name (id = 86988)

**Comment by TheRoby** [comment]
12.0.21005

**Comment by TheRoby** [comment]
And I have a software dictionary rule : 
![image](https://user-images.githubusercontent.com/6053818/219612760-2ffc6e6c-e39d-4834-bd54-30fa8b62abfe.png)

**Comment by trasher** [comment]
I do not understand what you try to achieve. With this dictionary that won't work correctly. We should fix silently the SQL error, but it will end with only one of all those listed that will be inventoried, either the first or the last one.

**Comment by stonebuzz** [comment]
So, this two nodes becomes duplicate software

```xml
    <SOFTWARES>
      <ARCH>i586</ARCH>
      <COMMENTS>Caution. Removing this product might prevent some applications from running.</COMMENTS>
      <FROM>registry</FROM>
      <GUID>{13A4EE12-23EA-3371-91EE-EFB36DDFFF3E}</GUID>
      <HELPLINK>http://go.microsoft.com/fwlink/?LinkId=133405</HELPLINK>
      <INSTALLDATE>08/01/2021</INSTALLDATE>
      <NAME>Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005</NAME>
      <PUBLISHER>Microsoft Corporation</PUBLISHER>
      <SYSTEM_CATEGORY>system_component</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>MsiExec.exe /X{13A4EE12-23EA-3371-91EE-EFB36DDFFF3E}</UNINSTALL_STRING>
      <VERSION>12.0.21005</VERSION>
    </SOFTWARES>

    <SOFTWARES>
      <ARCH>i586</ARCH>
      <COMMENTS>Caution. Removing this product might prevent some applications from running.</COMMENTS>
      <FROM>registry</FROM>
      <GUID>{F8CFEB22-A2E7-3971-9EDA-4B11EDEFC185}</GUID>
      <HELPLINK>http://go.microsoft.com/fwlink/?LinkId=133405</HELPLINK>
      <INSTALLDATE>08/01/2021</INSTALLDATE>
      <NAME>Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005</NAME>
      <PUBLISHER>Microsoft Corporation</PUBLISHER>
      <SYSTEM_CATEGORY>system_component</SYSTEM_CATEGORY>
      <UNINSTALL_STRING>MsiExec.exe /X{F8CFEB22-A2E7-3971-9EDA-4B11EDEFC185}</UNINSTALL_STRING>
      <VERSION>12.0.21005</VERSION>
    </SOFTWARES>
```

For the first software ```Microsoft Visual C++ 2013 x86 Minimum Runtime - 12.0.21005```  GLPI add and link ```Microsoft Visual c++``` to ```Computer```

For the second soft ```Microsoft Visual C++ 2013 x86 Additional Runtime - 12.0.21005``` GLPI check in database if  ```Microsoft Visual c++```  exist (true) a try to add it again 

You must improve your rule to keep ```Additional Runtime``` and ```Minimum Runtime``` 

GLPI natively see it as two different software.

**Comment by TheRoby** [comment]
> I do not understand what you try to achieve. With this dictionary that won't work correctly. We should fix silently the SQL error, but it will end with only one of all those listed that will be inventoried, either the first or the last one.

Simplify the list of software or I do not necessarily need details ... But maybe it was a bit too extreme ;)
Sorry and thanks !

**Comment by stonebuzz** [comment]
yes

**Comment by trasher** [comment]
> Simplify the list of software or I do not necessarily need details ... But maybe it was a bit too extreme ;) Sorry and thanks !

OK. I'll try to find a fix, but I'm not able to reproduce; it's probably linked to the way all data arrived in your database.

**Comment by trasher** [comment]
> OK. I'll try to find a fix, but I'm not able to reproduce; it's probably linked to the way all data arrived in your database.

I'm not able to reproduce. On my side, dictionary is working as expected, and all duplicated software are correctly merged.

I do not know if you have something wrong in your database, or another rule that makes things goes wrong, or... If you are able to provide a way to reproduce; we can investigate further. For now, I give up.

**Comment by TheRoby** [comment]
I'll see if I can find it, if not it's not serious :)
Thanks
