### ISSUE TITLE
upload documents with api

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#1408]
Actually the api supports 'multipart data' content-type but due to the speficity of the document upload (ajax/upload fiel) in the interface, there is no way to natively upload documents though the api.

Some plugin, for ex [flyvemdm](https://github.com/flyve-mdm/backend) (maybe not yet published) support on their classes the multipart data.

I think we need to add whether: 
- a new endpoint 
- or add a behavior in Document class to get the FILES data.

**Comment by btry** [comment]
Hi

A new endpoint to uploads is probably more generic : it should not be mandatoy to upload a file as a document.

I'm also thinking about a workflow similar to the jquery uploader : uploads go to a temporary placeA later request will re-move the file to its definitive location and do a logic defined by an itemtype implementation (link the file to it for example)

**Comment by orthagh** [comment]
should be fixed by #1676
