### ISSUE TITLE
One network card with two equal mac addresses.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#14085]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

During inventory, computers are added with two identical mac addresses and one network card, and when creating a new port, the drop-down list consists of two network cards with the same mac addresses. There is only one physical card in the PC.

![image](https://user-images.githubusercontent.com/16879167/218950101-efc54e1e-3456-49d2-b04c-befc9789f0a7.png)

![image](https://user-images.githubusercontent.com/16879167/218951595-3a517dd5-b656-4998-b659-9d0a9f588a09.png)

![image](https://user-images.githubusercontent.com/16879167/218951695-072137ac-58de-412a-a2f2-289b8f59805d.png)

![image](https://user-images.githubusercontent.com/16879167/218953656-4dfd61ff-d360-4c6d-9a1e-a1203a9194f6.png)

[computer_0_109.zip](https://github.com/glpi-project/glpi/files/10740078/computer_0_109.zip)

**Comment by trasher** [comment]
I confirm the issue

**Comment by trasher** [comment]
When there are bot network connections on ipv4 and ipv6, there are 2 networks nodes in the XML, with the same MAC, I guess this is the origin of the issue. I tcreates one `DeviceNetworkCard` (which is OK), but two `Item_DeviceNetworkCard` (which is not OK).

**Comment by trasher** [comment]
Please try with #14098
