### ISSUE TITLE
GLPI[10.0.6] Knowledge search

### ISSUE THREAD

**Issue by Coyote00** [glpi-project/glpi#14097]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

The search function no longer works following a 9.4.5 => 10.0.6 update.

Maybe it's a bad setting on my part? even in super admin with all the rights, I tried to change the targets of the documents and it's the same thing.

I think it is certainly a bad setting or use on my part since I am the only one to post this.

### Relevant log output
![knowledge_1](https://user-images.githubusercontent.com/123153876/219314015-0343f169-358c-416c-8af7-0f822282690d.PNG)
![knowlegde_2](https://user-images.githubusercontent.com/123153876/219314050-c1a8f42e-7dad-47fb-9011-40760dac52a6.PNG)

### Page URL

/front/knowbaseitem.php?contains=VERIFICATION&_glpi_csrf_token=

### Steps To reproduce

1. Go to knowledge.
2. Search for a document that exists.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 (/preprod => /home/eydt/www/preprod)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux webm173.cluster027.gra.hosting.ovh.net 5.15.74-ovh-vps-grsec-zfs-classid #1 SMP Wed Oct 26 09:50:47 UTC
	2022 x86_64
PHP 7.4.29 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube Loader, json,
	libxml, mbstring, memcached, mongodb, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, pspell,
	redis, session, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="165" memory_limit="512M" post_max_size="130M" safe_mode="" session.save_handler="files"
	upload_max_filesize="128M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.41-log
	Server SQL Mode: NO_ENGINE_SUBSTITUTION
	Parameters: eydtxrayantho@eydtxrayantho.mysql.db/eydtxrayantho
	Host info: eydtxrayantho.mysql.db via TCP/IP
	
PHP version (7.4.29) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.41) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/eydt/www/preprod/files/_cache has been validated.
Write access to /home/eydt/www/preprod/config has been validated.
Write access to /home/eydt/www/preprod/files/_cron has been validated.
Write access to /home/eydt/www/preprod/files has been validated.
Write access to /home/eydt/www/preprod/files/_dumps has been validated.
Write access to /home/eydt/www/preprod/files/_graphs has been validated.
Write access to /home/eydt/www/preprod/files/_lock has been validated.
Write access to /home/eydt/www/preprod/files/_pictures has been validated.
Write access to /home/eydt/www/preprod/files/_plugins has been validated.
Write access to /home/eydt/www/preprod/files/_rss has been validated.
Write access to /home/eydt/www/preprod/files/_sessions has been validated.
Write access to /home/eydt/www/preprod/files/_tmp has been validated.
Write access to /home/eydt/www/preprod/files/_uploads has been validated.
The following directories should be placed outside "/home/eydt/www/preprod":
‣ "/home/eydt/www/preprod/files" ("GLPI_VAR_DIR")
‣ "/home/eydt/www/preprod/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/eydt/www/preprod/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/eydr/www/preprod"
GLPI_CONFIG_DIR: "/home/eydt/www/preprod/config"
GLPI_VAR_DIR: "/home/eydt/www/preprod/files"
GLPI_MARKETPLACE_DIR: "/home/eydt/www/preprod/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/home/eydt/www/preprod/files"
GLPI_CACHE_DIR: "/home/eydt/www/preprod/files/_cache"
GLPI_CRON_DIR: "/home/eydt/www/preprod/files/_cron"
GLPI_DUMP_DIR: "/home/eydt/www/preprod/files/_dumps"
GLPI_GRAPH_DIR: "/home/eydt/www/preprod/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/eydt/www/preprod/files/_locales"
GLPI_LOCK_DIR: "/home/eydt/www/preprod/files/_lock"
GLPI_LOG_DIR: "/home/eydt/www/preprod/files/_log"
GLPI_PICTURE_DIR: "/home/eydt/www/preprod/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/eydt/www/preprod/files/_plugins"
GLPI_RSS_DIR: "/home/eydt/www/preprod/files/_rss"
GLPI_SESSION_DIR: "/home/eydt/www/preprod/files/_sessions"
GLPI_TMP_DIR: "/home/eydt/www/preprod/files/_tmp"
GLPI_UPLOAD_DIR: "/home/eydt/www/preprod/files/_uploads"
GLPI_INVENTORY_DIR: "/home/eydt/www/preprod/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/home/eydt/www/preprod/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/home/eydt/www/preprod/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/home/eydt/www/preprod/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/eydt/www/preprod/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/home/eydt/www/preprod/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/eydt/www/xreprod/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/eyd/www/preprod/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/eydt/www/preprod/vendor/iamcal/lib_autolink)
sabre/dav in (/home/eydt/www/preprod/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/eydt/www/preprod/vendor/sabre/http/lib)
sabre/uri in (/home/eydt/www/preprod/vendor/sabre/uri/lib)
sabre/vobject in (/home/eydt/www/preprod/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/eydt/www/preprod/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/eydt/www/preprod/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/eydt/www/preprod/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/eydt/www/preprod/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/eydt/www/preprod/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/eydt/www/preprod/vendor/elvanto/litemoji/src)
symfony/console in (/home/eydt/www/preprod/vendor/symfony/console)
scssphp/scssphp in (/home/eydt/www/preprod/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/eydt/www/preprod/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/eydt/www/preprod/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/eydt/www/preprod/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/home/eydt/www/preprod/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/home/eydt/www/preprod/vendor/ramsey/uuid/src)
psr/log in (/home/eydt/www/preprod/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/eydt/www/preprod/vendor/psr/simple-cache/src)
psr/cache in (/home/eydt/www/preprod/vendor/psr/cache/src)
league/csv in (/home/eydt/www/preprod/vendor/league/csv/src)
mexitek/phpcolors in (/home/eydt/www/preprod/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/eydt/www/preprod/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/eydt/www/preprod/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/eydt/www/preprod/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/eydt/www/preprod/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/eydt/www/preprod/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/eydt/www/preprod/vendor/symfony/cache)
html2text/html2text in (/home/eydt/www/preprod/vendor/html2text/html2text/src)
symfony/css-selector in (/home/eydt/www/preprod/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/eydt/www/preprod/vendor/symfony/dom-crawler)
twig/twig in (/home/eydt/www/preprod/vendor/twig/twig/src)
twig/string-extra in (/home/eydt/www/preprod/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/home/eydt/www/preprod/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/home/eydt/www/preprod/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/home/eydt/www/preprod/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (support@medical-informatique-services.com@SSL0.OVH.NET)

</details><details><summary>Plugins list</summary><pre> 
	activity             Name: Activités quotidiennes         Version: 3.1.2      State: Installed / not activated               
		Install Method: Manual
	actualtime           Name: ActualTime                     Version: 2.0.0      State: Not installed                           
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.18.2     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	releases             Name: Mises en production            Version: 2.0.3      State: Installed / not activated               
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.1      State: Installed / not activated               
		Install Method: Manual
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Not installed                           
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
Already fixed, check existing issues.

**Comment by Coyote00** [comment]
https://github.com/glpi-project/glpi/issues/14071 

for fix if someone makes the same mistake as me
