### ISSUE TITLE
Entity unreachable when moving to root entity

### ISSUE THREAD

**Issue by jvergacas** [glpi-project/glpi#14095]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.3 / 10.0.6 

### Bug description

When it is necessary to move a child entity below the root entity, it becomes inaccessible to users who have recursive access from the root entity.

### Steps To reproduce

With a Super-Admin user, at the root entity and recursive;
Create an entity below the root entity;
Create a second entity as a child of the previously created one;
Move the second entity below the root entity;
LOGOFF and LOGON ;
The second entity will become unavailable.

**Comment by nathanael-h** [comment]
I confirm in 10.0.6. Do you have any fix or clue? If I may help, I could make some tests, or provides logs.

**Comment by AlexTR85** [comment]
Same problem on 10.0.6....

**Comment by trasher** [comment]
No feedback, I close
