### ISSUE TITLE
[GLPI 9.1] e-mail capture : attached picture is not atttibuted to the e-mail sender

### ISSUE THREAD

**Issue by mi-cha-el** [glpi-project/glpi#1409]
When automatically capturing an e-mail to create a new ticket, the e-mail content is attributed to the e-mail author but the attached picture (if any) is attributed to another random user.
Seems that this 'random user' is someone connected to GLPI when the e-mail is captured.

[French]
Lorsqu'un e-mail est capturé automatiquement par GLPI, le texte est bien attribué à l'expéditeur lors de l'ouverture de ticket mais l'image éventuelle qui figure en pièce jointe est attribuée à un utilisateur de GLPI au pif, apparemment quelqu'un qui serait connecté sur l'appli au moment de la capture du mail. 
[/French]

[code]
 
GLPI 9.1 ( => /var/www/glpi)

Server
 
Operating system: Linux SRV-GLPI 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64
PHP 5.6.27-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="55M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at XXXX.XXXXXXXX.fr Port 80)
	Mozilla/5.0 (Windows NT 6.1; rv:48.0) Gecko/20100101 Firefox/48.0
Server Software: (Debian)
	Server Version: 5.5.52-0+deb8u1-log
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK

Libraries

 
htmLawed version 1.1.21 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/var/www/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/var/www/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/var/www/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/var/www/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)

LDAP directories

 
Server: '192.168.1.218', Port: '389', BaseDN: 'dc=XXXXX,dc=XXXXXXXXX,dc=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$)))', RootDN:
		'glpi', Use TLS: none
Server: '192.168.1.219', Port: '389', BaseDN: 'dc=XXXXX,dc=XXXXXXXXX,dc=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$)))', RootDN:
		'glpi', Use TLS: none
Server: '192.168.1.220', Port: '389', BaseDN: 'dc=XXXXX,dc=XXXXXXXXX,dc=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$)))', RootDN:
		'glpi', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (XXXXXXXXXXXXXXXXXXXXXXXX)

Mails receivers

 
Name: 'XXXXXXXXXXXX@XXXXXXXXXXXX.fr' Active: Yes
	Server: '{XXXXXXXXXX.XXXXXXXX.fr:143/imap/novalidate-cert/tls}INBOX' Login: 'XXXXXX' Password: Yes

Plugins list

 
	databases            Name: Bases de données               Version: 1.9.0      State: Enabled
	escalade             Name: Escalades                      Version: 2.1.0      State: Not activated
	tasklists            Name: Liste des tâches               Version: 1.1.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Enabled
	purgelogs            Name: Purge de l'historique          Version: 1.2.2      State: Enabled
	reports              Name: Rapports                       Version: 1.9.1      State: Not activated
	dashboard            Name: Tableau de bord                Version: 0.7.7      State: Enabled

[/code]

**Comment by trasher** [comment]
Duplicates #1476 :)
