### ISSUE TITLE
Incorrect software architecture information collected

### ISSUE THREAD

**Issue by xupei30** [glpi-project/glpi#14099]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

The collected software architecture information is incorrect. A software will have two architectures in GLPI and will be counted twice
VMware Horizon Client
i586？and x86_64
![software-horizon](https://user-images.githubusercontent.com/59216351/219318277-378adbbf-ccc5-402e-83e3-113f2e731779.png)

### Your GLPI setup information

GLPI 10.0.6 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

Operating system: Linux localhost.localdomain 3.10.0-1160.76.1.el7.x86_64 #1 SMP Wed Aug 10 16:21:17 UTC 2022 x86_64
PHP 7.4.30 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xdebug, xhprof,
	xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/7.4.30 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.46
Server Software: MariaDB Server
	Server Version: 10.3.36-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by trasher** [comment]
Please provide related inventory file.

**Comment by xupei30** [comment]
[access-errors.log](https://github.com/glpi-project/glpi/files/10754502/access-errors.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/10754503/php-errors.log)
[sql-errors.log](https://github.com/glpi-project/glpi/files/10754506/sql-errors.log)

**Comment by trasher** [comment]
I did not ask for log files

**Comment by cedric-anne** [comment]
@xupei30 

Could you provide inventory file corresponding to your asset?
It can be downloaded from the `Inventory Information` section of the asset main page.
![image](https://user-images.githubusercontent.com/33253653/220856518-d64382eb-112e-490e-8bec-c132644966f8.png)

**Comment by xupei30** [comment]
> @xupei30
> 
> 您能否提供与您的资产相对应的库存文件？可以从资产主页的部分下载它。`Inventory Information` ![image](https://user-images.githubusercontent.com/33253653/220856518-d64382eb-112e-490e-8bec-c132644966f8.png)

[123.csv](https://github.com/glpi-project/glpi/files/10811948/123.csv)

**Comment by cedric-anne** [comment]
This is not the inventory file of your asset.

**Comment by trasher** [comment]
Reading initial issue again, if inventory results gives 2 same software on 2 different architectures, GLPI have to store those both; since there are really 2 different soft installed.
If only one is installed, and the inventory file gives 2, this is an agent issue.

**Comment by oferreens** [comment]
Hi,
I've just seen this issue. I've got this problem. 
This is software list for a computer : 

![abbyy](https://github.com/glpi-project/glpi/assets/138197220/49300d4e-b117-4c05-ba4e-a5579ff286fe)

And this is an example of installations for this software : 

![ok_deploiement](https://github.com/glpi-project/glpi/assets/138197220/d57820a0-df74-4b97-8d95-b67558d8c075)

So the number of installations is not correct because of the architecture. 

GLPI 10.0.7
Deployment with GLPI Inventory.

oferre
