### ISSUE TITLE
Contacts Supplier Notifications

### ISSUE THREAD

**Issue by hakihosting** [glpi-project/glpi#14093]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.1

### Bug description

Hello , 

when i add a supplier in a ticket , the contacts attached to the supplier do not receive the follow up about ticket.

**Comment by trasher** [comment]
Your version is outdated, upgrade to latest and feel free to reopen if you reproduce.
