### ISSUE TITLE
Hide Entities 

### ISSUE THREAD

**Issue by eltonsjbv1** [glpi-project/glpi#14094]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

I cannot hide entities in form tickets.
I need hide specifics entities in ticket form i have 50 entities, i need hide 25 entities for that some peoples not open tickets for this entities.
How do this? Its possible change some block of code in Dropdown.php file?

**Comment by cconard96** [comment]
Sorry, but we only track bug reports on GitHub. You may utilize the [community forum](https://forum.glpi-project.org/index.php) for help using GLPI.
