### ISSUE TITLE
Website: contact button on https://glpi-project.org/roadmap/ not ok

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#14109]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

On the website, https://glpi-project.org/roadmap/, the contact-button is not pointing to an existing url.
The correct url is https://portal.glpi-network.com/marketplace/formcreator/front/formdisplay.php?id=15

**Comment by trasher** [comment]
It's been fixed, thanks for the report
