### ISSUE TITLE
Email notifications send only 1 time

### ISSUE THREAD

**Issue by sazanof** [glpi-project/glpi#1410]
Hello! I use version 0.90.5, and it hasn't been updated, but I have a problem that I have encountered. For some reason, using the notice of contracts, consumables via cron notification email only comes once (recording the result in the database). I would like to have the ability to customize notifications with different intervals and repetitions, and to always, regardless of whether you send you an email or not.

**Comment by sazanof** [comment]
![s61208-07290020](https://cloud.githubusercontent.com/assets/3595562/20997647/84e0ef38-bd18-11e6-8e6c-b303bc32be12.jpg)
![s61208-07295402](https://cloud.githubusercontent.com/assets/3595562/20997648/8966b470-bd18-11e6-9bfc-9d5959ff9179.jpg)

**Comment by trasher** [comment]
Could you please open a thread on th suggestions website (http://glpi.userecho.com)? Thanks.
