### ISSUE TITLE
Create a ticket, assigning a responsible user reloaded page

### ISSUE THREAD

**Issue by adamczestkowski** [glpi-project/glpi#14117]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,

I have a problem with assigning a responsible user to ticket. Sometimes when creating an application and assigning a user to a task, the page reloads and logs me out of glpi. Often redirected to url domain.com/index.php?error=3

The cookie in glpi session duration is set to 2 days.
Has anyone encountered such a problem?

![image](https://user-images.githubusercontent.com/3323372/220017527-9cbbb1ae-6e99-4928-8006-03dcf5fe1c7d.png)

### Your GLPI setup information

Operating system: Linux mail.domain.com 3.10.0-1127.18.2.vz7.163.46 #1 SMP Fri Nov 20 21:47:55 MSK 2020 x86_64
PHP 7.4.30 litespeed (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, ionCube Loader, json, libxml, litespeed, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="1024M" post_max_size="64M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: LiteSpeed
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.22-MariaDB
	Server SQL Mode: 
	Parameters: glpi_gr3144@localhost/glpi_ga1643
	Host info: Localhost via UNIX socket
	
PHP version (7.4.30) is supported.PHP version (7.4.30) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.22) is supported.Database engine version (10.4.22) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /home/glpi/domains/domain.com/public_html/files/_cache has been validated. Write access to /home/glpi/domains/domain.com/public_html/config has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_cron has been validated. Write access to /home/glpi/domains/domain.com/public_html/files has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_dumps has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_graphs has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_lock has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_pictures has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_plugins has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_rss has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_sessions has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_tmp has been validated. Write access to /home/glpi/domains/domain.com/public_html/files/_uploads has been validated.Write access to /home/glpi/domains/domain.com/public_html/files/_cache has been validated.
Write access to /home/glpi/domains/domain.com/public_html/config has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_cron has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_dumps has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_graphs has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_lock has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_pictures has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_plugins has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_rss has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_sessions has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_tmp has been validated.
Write access to /home/glpi/domains/domain.com/public_html/files/_uploads has been validated.
The following directories should be placed outside "/home/glpi/domains/domain.com/public_html": ‣ "/home/glpi/domains/domain.com/public_html/files" ("GLPI_VAR_DIR") ‣ "/home/glpi/domains/domain.com/public_html/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "/home/glpi/domains/domain.com/public_html":
‣ "/home/glpi/domains/domain.com/public_html/files" ("GLPI_VAR_DIR")
‣ "/home/glpi/domains/domain.com/public_html/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
Sessions configuration is secured.Sessions configuration is secured.
exif extension is installed.exif extension is installed.
ldap extension is not present.ldap extension is not present.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/glpi/domains/domain.com/public_html/marketplace has been validated.Write access to /home/glpi/domains/domain.com/public_html/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment]
Hi,

It means that GLPI session is lost. It can be due to lack of sharing of session files between 2 servers in a misconfigured load balanced env, or due to a misconfigured proxy that mix user cookies, or due to a session files agressive cleaning, etc...
Anyway, this is not a GLPI bug.
