### ISSUE TITLE
elements, from the view group tab Are loaded incorrectly

### ISSUE THREAD

**Issue by thallestorchi** [glpi-project/glpi#14114]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

elements, from the view group tab. (technical profile)

Are loaded incorrectly in the google chrome browser.

However, they are loaded normally in the firefox browser.

### Steps To reproduce

a) log in to glpi with the technical profile using google chrome
b) click home
c) click group view
d) the page will load with overlapping elements

### Your GLPI setup information

GLPI 10.0.6 ( => /opt/app-root/src)
Installation mode: TARBALL
Current language:pt_BR

Operating system: Linux glpi-7d5db5467-4tssz 4.18.0-305.72.1.el8_4.x86_64 #1 SMP Thu Nov 17 09:15:11 EST 2022 x86_64
PHP 8.0.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, redis, session, shmop, soap, sockets,
	sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="6M" 
Software: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.49
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@glpi-mysql/glpi
	Host info: glpi-mysql via TCP/IP
	
PHP version (8.0.20) is supported.PHP version (8.0.20) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /glpi/files/_cache has been validated. Write access to /glpi/config has been validated. Write access to /glpi/files/_cron has been validated. Write access to /glpi/files has been validated. Write access to /glpi/files/_dumps has been validated. Write access to /glpi/files/_graphs has been validated. Write access to /glpi/files/_lock has been validated. Write access to /glpi/files/_pictures has been validated. Write access to /glpi/files/_plugins has been validated. Write access to /glpi/files/_rss has been validated. Write access to /glpi/files/_sessions has been validated. Write access to /glpi/files/_tmp has been validated. Write access to /glpi/files/_uploads has been validated.Write access to /glpi/files/_cache has been validated.
Write access to /glpi/config has been validated.
Write access to /glpi/files/_cron has been validated.
Write access to /glpi/files has been validated.
Write access to /glpi/files/_dumps has been validated.
Write access to /glpi/files/_graphs has been validated.
Write access to /glpi/files/_lock has been validated.
Write access to /glpi/files/_pictures has been validated.
Write access to /glpi/files/_plugins has been validated.
Write access to /glpi/files/_rss has been validated.
Write access to /glpi/files/_sessions has been validated.
Write access to /glpi/files/_tmp has been validated.
Write access to /glpi/files/_uploads has been validated.
GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
Sessions configuration is secured.Sessions configuration is secured.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /glpi/marketplace has been validated.Write access to /glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cedric-anne** [comment]
Hi,

Do you use `escalade` plugin? Same kind of issue has been fixed recently (see https://github.com/pluginsGLPI/escalade/releases/tag/2.8.2).

If you do not use this plugin, could you please share some screenshots?

**Comment by trasher** [comment]
No feedback, I close
