### ISSUE TITLE
When creating ticket, any user can be set as watcher even if not in requester group

### ISSUE THREAD

**Issue by yodapotatofly** [glpi-project/glpi#14113]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When a user creates a ticket, he can add ay user of the system as watcher, even users that are not part of his group.

According to the doc [https://glpi-user-documentation.readthedocs.io/fr/latest/modules/assistance/tickets/ticketopening.html](https://glpi-user-documentation.readthedocs.io/fr/latest/modules/assistance/tickets/ticketopening.html), this should not be possible :

> _**Watchers**: Allows to add a watcher and to define notification parameters. Only members of the requester group can be added._

### Page URL

front/helpdesk.public.php?create_ticket=1

### Steps To reproduce

1. Create 2 groups
2. Add two users in each group
3. As one of those users, go to `front/helpdesk.public.php?create_ticket=1`
4. In the field "watcher", you can add a user from the other group while it is not supposed to be possible

**Comment by yodapotatofly** [comment]
Hello @cedric-anne

What would be the follow-up steps to get this issue clarified ?

**Comment by cedric-anne** [comment]
Documentation will be updated, see https://github.com/glpi-project/doc/pull/115 .

**Comment by virtazp** [comment]
Hello, this is exactly the behavior I expect.

Thanks for the solution.
