### ISSUE TITLE
After updating to 9.5.9, information in "Network devices" in "Network ports" about connected devices is no longer displayed

### ISSUE THREAD

**Issue by amtchikin** [glpi-project/glpi#14123]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.9

### Bug description

After updating to 9.5.9, information in "Network devices" in "Network ports" about connected devices is no longer displayed

![image](https://user-images.githubusercontent.com/125869954/220067122-7e912995-c020-4a18-9c52-26f0bea46921.png)

**Comment by trasher** [comment]
9.5 is no longer maintained, please consider upgrading.

**Comment by trasher** [comment]
Also, your issue is related to fusion plugin.

**Comment by amtchikin** [comment]
Version 9.5.12 is currently installed, as well as the latest fusioninventory plugin. However, the result is the same

**Comment by amtchikin** [comment]
What is the probability that the problem will be solved when upgrading to 10.0.6?

**Comment by cedric-anne** [comment]
@amtchikin 

You should open an issue on [fusioninventory plugin repository](https://github.com/fusioninventory/fusioninventory-for-glpi/issues), problem seems related to this plugin.

**Comment by amtchikin** [comment]
Ok
