### ISSUE TITLE
TicketSatisfaction Management with REST API

### ISSUE THREAD

**Issue by ThibaultRL** [glpi-project/glpi#1412]
Hello,
There is an issue when trying to get informations about TicketSatisfaction with the API. 
Even if rights are correct, the following error is returned : 
ERROR_RIGHT_MISSING

I think it's because functions 'canViewItem' and 'canView' are not overwritten in 'TicketSatisfaction' class.
(As a quick and dirty workaround I have overwritten both of them so that they return 'true', and then I can access to the TicketSatisfaction.

The update of these TicketSatisfaction seems to be quite strange too. 
The ID provided in the "input" array of the "PUT" request must be the id of the linked ticket and not the reel ID of the TicketSatisfaction. This is because the getIndexName function of the 'TicketSatisfaction' class return 'ticket_id' and not 'id'. I don't know if it is an intened behaviour, but it's not consistent with the rest of the API.

**Comment by cedric-anne** [comment]
Hi,

Looks like it has been fixed in #5029. See also #5014.

Regards
