### ISSUE TITLE
API : Add / Update subitems

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#1413]
Hello,

I need some help. It seem that it's not possible to add / update subitems in GLPI API (version 9.1.1). I try for exemple to add Infocom on a computer and it seems that not working . For exemple : 
```php
CURLOPT_URL => 'myapi/Computer/100/Infocom',
CURLOPT_RETURNTRANSFER	=> true,
CURLOPT_SSL_VERIFYPEER 	=> false,
CURLOPT_HTTPHEADER	=> array(
   'Content-Type: application/json',
   'App-Token: '.API_TOKEN,
   'Session-Token: '.$this->session,
),
CURLOPT_POSTFIELDS => "{"input" : {"buy_date" : "2016-12-08"}}".
```

The return is :
```php
array(2) {
  [0]=> string(19) "ERROR_RIGHT_MISSING"
}
```

I use "glpi" user in Super-Admin group

Thanks for your help

**Comment by ciadch** [comment]
Same behaviour with NetworkPort. It could be really userfull to have the possiblity to add subitem in one shot ! 

Tanks for your help

**Comment by 20-100** [comment]
Yup, I came across the same problem just today.
I use the API via a python script, however, and what I get as a result of the PUT submission is an empty list.

**Comment by klon9000** [comment]
It's because Infocom have its own ID, you can catch it in response from
apirest.php/Computer/**Computer_ID**/?with_infocoms=true
InfocomID=json['_infocoms']['id']

and now you can PUT request for InfocomID
apirest.php/Infocom/**InfocomID**

the same way using for other type of subitems, Network ports etc.

**Comment by cedric-anne** [comment]
Hi,

I close this issue as a responses has been done.
If you need more help, please use [forum](https://forum.glpi-project.org/).

Regards
