### ISSUE TITLE
knowledage search issue

### ISSUE THREAD

**Issue by asystemdwq** [glpi-project/glpi#14134]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

When I tried to search the articales in my knowledage base, I got no result, which worked in 10.0.3.
![图片](https://user-images.githubusercontent.com/23158457/220335234-2be9120e-b618-4c5c-b0e0-ec94594f4943.png)

**Comment by trasher** [comment]
duplicates #14071
