### ISSUE TITLE
URL params with differen behaviour

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#14138]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

See bug

### Relevant log output

```shell
NONE
```

### Steps To reproduce

1. Create a KB article that is public (FAQ) - Systemconfig FAQ is not visible without authentication
2. copy the link like this scheme: example.com/front/helpdesk.faq.php?id=784
3. open a private browser where you are not logged in and open the url
4. you will be redirected to: example.com/index.php?redirect=%2Ffront%2Fhelpdesk.faq.php%3Fid%3D784?error=3
5. note the: ?error=3 which is from checkValidSessionId() because no session
6. Login as user - not tech
7. See blank page!
8. remove "?error=3" from URL and it works as expected

### Anything else?

Thank you!

**Comment by trasher** [comment]
I confirm the `?error=3` is kept in redirection URL and should not; but in my case, its end with something like `?id=1?error=3` and that does not fail.

**Comment by cedric-anne** [comment]
#14140 should fix this.
