### ISSUE TITLE
9.1.x empty sql miss glpi_taskcategories.is_active

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#1414]
the column is added in https://github.com/glpi-project/glpi/blob/master/install/update_0905_91.php#L837

**Comment by trasher** [comment]
As far as I can see; this field is present in the 9.1.1 release empty script:
https://github.com/glpi-project/glpi/blob/80328baf38e2d6fe6cf269b43ed0edc80c64d89d/install/mysql/glpi-9.1.1-empty.sql#L7045

**Comment by trasher** [comment]
ping?

**Comment by orthagh** [comment]
Can't remember the issue :/

Seems ok, maybe we could close (and remove tag).
