### ISSUE TITLE
STATUS new X SLA

### ISSUE THREAD

**Issue by SilvaFernando** [glpi-project/glpi#14148]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello, I have a strange behavior in version 10.0.6 of glpi, I also simulated in 10.0.3, if I have a ticket with a 2-hour SLA, when changing the status of this ticket to new, when changing the status the SLA already expires, no log is generated. follow evidence:
![image](https://user-images.githubusercontent.com/53239752/220736705-c16cc108-b512-4b93-a8bb-ea0576122917.png)
![image](https://user-images.githubusercontent.com/53239752/220736787-b34a6efb-9c0d-406d-ab1f-478ec5fc8537.png)
Our problem, apparently the status when the status is new, the SLA does not respect the time the ticket was pending.

This problem does not happen if you use the status Processing (assigned)

### Relevant log output

```shell
I don't have error on logs.
```

### Steps To reproduce

1. Open a ticket with SLA
2. Set pending status
3. Wait SLA time
4. Set new status

 

### Your GLPI setup information

<html>
<body>

Information about system installation & configuration
--
 
GLPI 10.0.6 ( => /usr/share/glpi) Installation mode: TARBALL Current language:en_US

Operating system: Linux 60113dba5e2c 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Thu Mar 10 20:59:28 UTC 2022 x86_64 PHP 8.0.27 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, pdo_sqlite, posix, selinux, session, shmop, snmp, soap, sockets, sodium, sqlite3, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.37 (AlmaLinux) () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.50 Server Software: Percona Server (GPL), Release 42, Revision b0a7dc2da2e 	Server Version: 5.7.39-42 	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: glpi@172.17.0.3/glpi 	Host info: 172.17.0.3 via TCP/IP 	 PHP version (8.0.27) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (5.7.39) is supported. No files from previous GLPI version detected. The log file has been created successfully. Write access to /var/lib/glpi/files/_cache has been validated. The directory could not be created in /etc/glpi. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files/data-documents has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated. GLPI data directories are located in a secured path. For security reasons, SELinux mode should be Enforcing. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /usr/share/glpi/marketplace has been validated. Access to timezone database (mysql) is not allowed.

GLPI_ROOT: "/usr/share/glpi" GLPI_CONFIG_DIR: "/etc/glpi" GLPI_MARKETPLACE_ALLOW_OVERRIDE: false GLPI_VAR_DIR: "/var/lib/glpi/files" GLPI_DOC_DIR: "/var/lib/glpi/files/data-documents" GLPI_CRON_DIR: "/var/lib/glpi/files/_cron" GLPI_DUMP_DIR: "/var/lib/glpi/files/_dumps" GLPI_GRAPH_DIR: "/var/lib/glpi/files/_graphs" GLPI_LOCK_DIR: "/var/lib/glpi/files/_lock" GLPI_PICTURE_DIR: "/var/lib/glpi/files/_pictures" GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/files/_plugins" GLPI_RSS_DIR: "/var/lib/glpi/files/_rss" GLPI_SESSION_DIR: "/var/lib/glpi/files/_sessions" GLPI_TMP_DIR: "/var/lib/glpi/files/_tmp" GLPI_UPLOAD_DIR: "/var/lib/glpi/files/_uploads" GLPI_CACHE_DIR: "/var/lib/glpi/files/_cache" GLPI_LOG_DIR: "/var/log/glpi" GLPI_SYSTEM_CRON: true GLPI_MARKETPLACE_DIR: "/usr/share/glpi/marketplace" GLPI_USE_CSRF_CHECK: "1" GLPI_CSRF_EXPIRES: "7200" GLPI_CSRF_MAX_TOKENS: "100" GLPI_USE_IDOR_CHECK: "1" GLPI_IDOR_EXPIRES: "7200" GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?\|feed):\\/\\/[^@:]+(\\/.*)?$/"] GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org" GLPI_INSTALL_MODE: "TARBALL" GLPI_NETWORK_MAIL: "glpi@teclib.com" GLPI_NETWORK_SERVICES: "https://services.glpi-network.com" GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true GLPI_USER_AGENT_EXTRA_COMMENTS: "" GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1" GLPI_AJAX_DASHBOARD: "1" GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: "0" GLPI_CENTRAL_WARNINGS: "1" GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/files/_locales" GLPI_INVENTORY_DIR: "/var/lib/glpi/files/_inventories" GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/" GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/" GLPI_I18N_DIR: "/usr/share/glpi/locales" GLPI_VERSION: "10.0.6" GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97" GLPI_MARKETPLACE_PRERELEASES: false GLPI_MIN_PHP: "7.4.0" GLPI_MAX_PHP: "8.3.0" GLPI_YEAR: "2023"

htmlawed/htmlawed version 1.2.9 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.6.2 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) psr/cache in (/usr/share/glpi/vendor/psr/cache/src) league/csv in (/usr/share/glpi/vendor/league/csv/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src) symfony/cache in (/usr/share/glpi/vendor/symfony/cache) html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src) symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector) symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler) twig/twig in (/usr/share/glpi/vendor/twig/twig/src) twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 in (/usr/share/glpi/vendor/symfony/polyfill-php81) symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82) phpCas version 1.6.0 in (/usr/share/pear)

Not active

Way of sending emails: SMTP+TLS (vinicius.lamelas@servicedeskbrasil.com.br@smtp.office365.com)

 

activity             Name: Activities                     Version: 3.1.2      State: Installed / not activated                		Install Method: Marketplace 	news                 Name: Alertas                        Version: 1.10.5     State: Installed / not activated                		Install Method: Marketplace 	formcreator          Name: Form Creator                   Version: 2.13.0-sdb State: Enabled                                  		Install Method: Manual 	tag                  Name: Gerenciamento de Etiquetas     Version: 2.11.0     State: Installed / not activated                		Install Method: Marketplace 	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.1   State: Installed / not activated                		Install Method: Manual 	sdbsubtask           Name: Plugin SDB SubTask             Version: 1.2.1      State: Installed / not activated                		Install Method: Manual 	sdbacaoporemail      Name: Servicedesk Brasil - Ação por  Version: 2.0.2      State: Enabled                                  		Install Method: Manual 	sdbescalonamentoapro Name: Servicedesk Brasil - Escalonam Version: 1.1.0      State: Installed / not activated                		Install Method: Manual 	vip                  Name: VIP                            Version: 1.8.2      State: Installed / not activated                		Install Method: Marketplace 	workflows            Name: Workflows                      Version: 1.0.0-alpha-10 State: Installed / not activated              		  Install Method: Manual

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by SilvaFernando** [comment]
Hi team.

Can you help me, please?

BR.
Fernando Dias da Silva

**Comment by cedric-anne** [comment]
@SilvaFernando

It see

**Comment by SilvaFernando** [comment]
Ok, thanks we opened ticket on profesional support webstie
