### ISSUE TITLE
0.90.5 : sql error at rule export when target entity is different form root-entity in a software dictionary rule

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#1415]
I'm running GLPI 0.90.5

I get an sql error when exporting rules, and
- I have a Software dictionnary rule
- in the action, the target entity is assigned to an entity different from the root-entity
As a result, in the rules.xml, the value for the action is empty : <value></value> which is embarassing at import time.

 SQL: SELECT `glpi_new_entities`.*, \'\' AS transname, \'\' AS transcomment
FROM `glpi_new_entities`
WHERE `glpi_new_entities`.`id` = \'1\'
Error: Table 'glpi090.glpi_new_entities' doesn't exist
Backtrace :
inc/dropdown.class.php:316
inc/rulecollection.class.php:959 Dropdown::getDropdownName()
front/rule.backup.php:76 RuleCollection::exportRulesToXML()

**Comment by blerohellec** [comment]
Note that when the targeted entity is the root-entity, there is no sql error, but the value in the xml file is still empty (<value></value>) and not equal to 0.

**Comment by trasher** [comment]
I cannot reproduce on current 9.2/bugfixes, I guess the issue has been solved.
