### ISSUE TITLE
GLPI Agent, big latency, bad sql

### ISSUE THREAD

**Issue by chris29B** [glpi-project/glpi#14157]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6 

### Bug description

Hi,

I have a fleet of around 5000 machines that have been inventoried so far with OCS Inventory, for around 1 year, we have been migrating to GLPI Agent, currently in 1.4.
Good morning,

Since version 10.0.6 we have noticed enormous slowness, because there is a problem with the requests passed on the GLPI_agents table, the SQL code request was probably done via an autogenerator

I have reduced the request because otherwise it does not pass in the request, but a random search with ORs at each job query, there is a problem:

`SELECT` idFROMglpi_agents WHERE ((itemtype= 'Monitor' ANDitems_id = '5') OR (itemtype= 'Monitor' ANDitems_id = '7') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '9') OR (itemtype= 'Monitor' ANDitems_id = '25') OR (itemtype= 'Monitor' ANDitems_id = '41') OR (itemtype= 'Monitor' ANDitems_id = '67') OR (itemtype= 'Monitor' ANDitems_id = '80') OR (itemtype= 'Monitor' ANDitems_id = '82') OR (itemtype= 'Monitor' ANDitems_id = '99') OR (itemtype= 'Monitor' ANDitems_id = '115') OR (itemtype= 'Monitor' ANDitems_id = '121') OR (itemtype= 'Monitor' ANDitems_id = '138') OR (itemtype= 'Monitor' ANDitems_id = '166') OR (itemtype= 'Monitor' ANDitems_id = '173') OR (itemtype= 'Monitor' ANDitems_id = '204') OR (itemtype= 'Monitor' ANDitems_id = '277') OR (itemtype= 'Monitor' ANDitems_id = '322') OR (itemtype= 'Monitor' ANDitems_id = '323') OR (itemtype= 'Monitor' ANDitems_id = '359') OR (itemtype= 'Monitor' ANDitems_id = '388') OR (itemtype= 'Monitor' ANDitems_id = '428') OR (itemtype= 'Monitor' ANDitems_id = '434') OR (itemtype= 'Monitor' ANDitems_id = '463') OR (itemtype= 'Monitor' ANDitems_id = '520') OR (itemtype= 'Monitor' ANDitems_id = '546') OR (itemtype= 'Monitor' ANDitems_id = '565') OR (itemtype= 'Monitor' ANDitems_id = '607') OR (itemtype= 'Monitor' ANDitems_id = '674') OR (itemtype= 'Monitor' ANDitems_id = '690') OR (itemtype= 'Monitor' ANDitems_id = '691') OR (itemtype= 'Monitor' ANDitems_id = '723') OR (itemtype= 'Monitor' ANDitems_id = '744') OR (itemtype= 'Monitor' ANDitems_id = '777') OR (itemtype= 'Monitor' ANDitems_id = '846') OR (itemtype= 'Monitor' ANDitems_id = '883') OR (itemtype= 'Monitor' ANDitems_id = '900') OR (itemtype= 'Monitor' ANDitems_id = '924') OR (itemtype= 'Monitor' ANDitems_id = '929') OR (itemtype= 'Monitor' ANDitems_id = '935') OR (itemtype= 'Monitor' ANDitems_id = '1115') OR (itemtype= 'Monitor' ANDitems_id = '1149') OR (itemtype= 'Monitor' ANDitems_id = '1161') OR (itemtype= 'Monitor' ANDitems_id = '1271') OR (itemtype= 'Monitor' ANDitems_id = '1301') OR (itemtype= 'Monitor' ANDitems_id = '1357') OR (itemtype= 'Monitor' ANDitems_id = '1416') OR (itemtype= 'Monitor' ANDitems_id = '1419') OR (itemtype= 'Monitor' ANDitems_id = '1425') OR (itemtype= 'Monitor' ANDitems_id = '1436') OR (itemtype= 'Monitor' ANDitems_id = '1487') OR (itemtype= 'Monitor' ANDitems_id = '1512') OR (itemtype= 'Monitor' ANDitems_id = '1546') OR (itemtype= 'Monitor' ANDitems_id = '1611') OR (itemtype= 'Monitor' ANDitems_id = '1753') OR (itemtype= 'Monitor' ANDitems_id = '1902') OR (itemtype= 'Monitor' ANDitems_id = '1927') OR (itemtype= 'Monitor' ANDitems_id = '1937') OR (itemtype= 'Monitor' ANDitems_id = '1989') OR (itemtype= 'Monitor' ANDitems_id = '2034') OR (itemtype= 'Monitor' ANDitems_id = '2035') OR (itemtype= 'Monitor' ANDitems_id = '2089') OR (itemtype= 'Monitor' ANDitems_id = '2096') OR (itemtype= 'Monitor' ANDitems_id = '2097') OR (itemtype= 'Monitor' ANDitems_id = '2098') OR (itemtype= 'Monitor' ANDitems_id = '2099') OR (itemtype= 'Monitor' ANDitems_id = '2100') OR (itemtype= 'Monitor' ANDitems_id = '2101') OR (itemtype= 'Monitor' ANDitems_id = '2118') OR (itemtype= 'Monitor' ANDitems_id = '2148') OR (itemtype= 'Monitor' ANDitems_id = '2419') OR (itemtype= 'Monitor' ANDitems_id = '2535') OR (itemtype= 'Monitor' ANDitems_id = '2539') OR (itemtype= 'Monitor' ANDitems_id = '2584') OR (itemtype= 'Monitor' ANDitems_id = '2656') OR (itemtype= 'Monitor' ANDitems_id = '2809') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2810') OR (itemtype= 'Monitor' ANDitems_id = '2886') OR (itemtype= 'Monitor' ANDitems_id = '3096') OR (itemtype= 'Monitor' ANDitems_id = '3231') OR (itemtype= 'Monitor' ANDitems_id = '3341') OR (itemtype= 'Monitor' ANDitems_id = '3463') OR (itemtype= 'Monitor' ANDitems_id = '3538') OR (itemtype= 'Monitor' ANDitems_id = '3600') OR (itemtype= 'Monitor' ANDitems_id = '3640') OR (itemtype= 'Monitor' ANDitems_id = '3654') OR (itemtype= 'Monitor' ANDitems_id = '3664') OR (itemtype= 'Monitor' ANDitems_id = '3687') OR (itemtype= 'Monitor' ANDitems_id = '3765') OR (itemtype= 'Monitor' ANDitems_id = '3769') OR (itemtype= 'Monitor' ANDitems_id = '3805') OR (itemtype= 'Monitor' ANDitems_id = '3818') OR (itemtype= 'Monitor' ANDitems_id = '3881') OR (itemtype= 'Monitor' ANDitems_id = '3881') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3889') OR (itemtype= 'Monitor' ANDitems_id = '3894') OR (itemtype= 'Monitor' ANDitems_id = '3894') OR (itemtype= 'Monitor' ANDitems_id = '3899') OR (itemtype= 'Monitor' ANDitems_id = '3909') OR (itemtype= 'Monitor' ANDitems_id = '3910') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3911') OR (itemtype= 'Monitor' ANDitems_id = '3927') OR (itemtype= 'Monitor' ANDitems_id = '3930') OR (itemtype= 'Monitor' ANDitems_id = '3934') OR (itemtype= 'Monitor' ANDitems_id = '3937') OR (itemtype= 'Monitor' ANDitems_id = '3946') OR (itemtype= 'Monitor' ANDitems_id = '3946') OR (itemtype= 'Monitor' ANDitems_id = '3946') OR (itemtype= 'Monitor' ANDitems_id = '3946') OR (itemtype= 'Monitor' ANDitems_id = '3946') OR (itemtype= 'Monitor' ANDitems_id = '3951') OR (itemtype= 'Monitor' ANDitems_id = '3951') OR (itemtype= 'Monitor' ANDitems_id = '3953') OR (itemtype= 'Monitor' ANDitems_id = '3953') OR (itemtype= 'Monitor' ANDitems_id = '3953') OR (itemtype= 'Monitor' ANDitems_id = '3958') OR (itemtype= 'Monitor' ANDitems_id = '3958') OR (itemtype= 'Monitor' ANDitems_id = '3958') OR (itemtype= 'Monitor' ANDitems_id = '3958') OR (itemtype= 'Monitor' ANDitems_id = '3958') OR (itemtype= 'Monitor' ANDitems_id = '3960') OR (itemtype= 'Monitor' ANDitems_id = '3960') OR (itemtype= 'Monitor' ANDitems_id = '3960') OR (itemtype= 'Monitor' ANDitems_id = '3960') OR (itemtype= 'Monitor' ANDitems_id = '3962') OR (itemtype= 'Monitor' ANDitems_id = '3962') OR (itemtype= 'Monitor' ANDitems_id = '3965') OR (itemtype= 'Monitor' ANDitems_id = '3965') OR (itemtype= 'Monitor' ANDitems_id = '3969') OR (itemtype= 'Monitor' ANDitems_id = '3969') OR (itemtype= 'Monitor' ANDitems_id = '3969') OR (itemtype= 'Monitor' ANDitems_id = '3969') OR (itemtype= 'Monitor' ANDitems_id = '3978') OR (itemtype= 'Monitor' ANDitems_id = '3978') OR (itemtype= 'Monitor' ANDitems_id = '3984') OR (itemtype= 'Monitor' ANDitems_id = '3984') OR (itemtype= 'Monitor' ANDitems_id = '3984') OR (itemtype= 'Monitor' ANDitems_id = '3984') OR (itemtype= 'Monitor' ANDitems_id = '3986') OR (itemtype= 'Monitor' ANDitems_id = '3996') OR (itemtype= 'Monitor' ANDitems_id = '3997') OR (itemtype= 'Monitor' ANDitems_id = '3997') OR (itemtype= 'Monitor' ANDitems_id = '4007') OR (itemtype= 'Monitor' ANDitems_id = '4011') OR (itemtype= 'Monitor' ANDitems_id = '4011') OR (itemtype= 'Monitor' ANDitems_id = '4014') OR (itemtype= 'Monitor' ANDitems_id = '4015') OR (itemtype= 'Monitor' ANDitems_id = '4015') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4016') OR (itemtype= 'Monitor' ANDitems_id = '4019') OR (itemtype= 'Monitor' ANDitems_id = '4026') OR (itemtype= 'Monitor' ANDitems_id = '4026') OR (itemtype= 'Monitor' ANDitems_id = '4026') OR (itemtype= 'Monitor' ANDitems_id = '4026') OR (itemtype= 'Monitor' ANDitems_id = '4027') OR (itemtype= 'Monitor' ANDitems_id = '4027') OR (itemtype= 'Monitor' ANDitems_id = '4027') OR (itemtype= 'Monitor' ANDitems_id = '4031') OR (itemtype= 'Monitor' ANDitems_id = '4032') OR (itemtype= 'Monitor' ANDitems_id = '4034') OR (itemtype= 'Monitor' ANDitems_id = '4034') OR (itemtype= 'Monitor' ANDitems_id = '4036') OR (itemtype= 'Monitor' ANDitems_id = '4038') OR (itemtype= 'Monitor' ANDitems_id = '4038') OR (itemtype= 'Monitor' ANDitems_id = '4041') OR (itemtype= 'Monitor' ANDitems_id = '4042') OR (itemtype= 'Monitor' ANDitems_id = '4042') OR (itemtype= 'Monitor' ANDitems_id = '4042') OR (itemtype= 'Monitor' ANDitems_id = '4042') OR (itemtype= 'Monitor' ANDitems_id = '4042') OR (itemtype= 'Monitor' ANDitems_id = '4043') OR (itemtype= 'Monitor' ANDitems_id = '4045') OR (itemtype= 'Monitor' ANDitems_id = '4046') OR (itemtype= 'Monitor' ANDitems_id = '4046') OR (itemtype= 'Monitor' ANDitems_id = '4046') OR (itemtype= 'Monitor' ANDitems_id = '4046') OR (itemtype= 'Monitor' ANDitems_id = '4046') OR (itemtype= 'Monitor' ANDitems_id = '4049') OR (itemtype= 'Monitor' ANDitems_id = '4049') OR (itemtype= 'Monitor' ANDitems_id = '4051') OR (itemtype= 'Monitor' ANDitems_id = '4054') OR (itemtype= 'Monitor' ANDitems_id = '4058') OR (itemtype= 'Monitor' ANDitems_id = '4058') OR (itemtype= 'Monitor' ANDitems_id = '4058') OR (itemtype= 'Monitor' ANDitems_id = '4064') OR (itemtype= 'Monitor' ANDitems_id = '4065') OR (itemtype= 'Monitor' ANDitems_id = '4065') OR (itemtype= 'Monitor' ANDitems_id = '4065') OR (itemtype= 'Monitor' ANDitems_id = '4065') OR (itemtype= 'Monitor' ANDitems_id = '4066') OR (itemtype= 'Monitor' ANDitems_id = '4066') OR (itemtype= 'Monitor' ANDitems_id = '4067') OR (itemtype= 'Monitor' ANDitems_id = '4071') OR (itemtype= 'Monitor' ANDitems_id = '4073') OR (itemtype= 'Monitor' ANDitems_id = '4073') OR (itemtype= 'Monitor' ANDitems_id = '4077') OR (itemtype= 'Monitor' ANDitems_id = '4082') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4087') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4088') OR (itemtype= 'Monitor' ANDitems_id = '4092') OR (itemtype= 'Monitor' ANDitems_id = '4092') OR (itemtype= 'Monitor' ANDitems_id = '4095') OR (itemtype= 'Monitor' ANDitems_id = '4109') OR (itemtype= 'Monitor' ANDitems_id = '4120') OR (itemtype= 'Monitor' ANDitems_id = '4120') OR (itemtype= 'Monitor' ANDitems_id = '4120') OR (itemtype= 'Monitor' ANDitems_id = '4120') OR (itemtype= 'Monitor' ANDitems_id = '4123') OR (itemtype= 'Monitor' ANDitems_id = '4123') OR (itemtype= 'Monitor' ANDitems_id = '4123') OR (itemtype= 'Monitor' ANDitems_id = '4123') OR (itemtype= 'Monitor' ANDitems_id = '4125') OR (itemtype= 'Monitor' ANDitems_id = '4125') OR (itemtype= 'Monitor' ANDitems_id = '4127') OR (itemtype= 'Monitor' ANDitems_id = '4134') OR (itemtype= 'Monitor' ANDitems_id = '4134') OR (itemtype= 'Monitor' ANDitems_id = '4134') OR (itemtype= 'Monitor' ANDitems_id = '4135') OR (itemtype= 'Monitor' ANDitems_id = '4135') OR (itemtype= 'Monitor' ANDitems_id = '4135') OR (itemtype= 'Monitor' ANDitems_id = '4135') OR (itemtype= 'Monitor' ANDitems_id = '4135') OR (itemtype= 'Monitor' ANDitems_id = '4141') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4143') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4158') OR (itemtype= 'Monitor' ANDitems_id = '4166') OR (itemtype= 'Monitor' ANDitems_id = '4168') OR (itemtype= 'Monitor' ANDitems_id = '4169') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4170') OR (itemtype= 'Monitor' ANDitems_id = '4172') OR (itemtype= 'Monitor' ANDitems_id = '4178') OR (itemtype= 'Monitor' ANDitems_id = '4180') OR (itemtype= 'Monitor' ANDitems_id = '4182') OR (itemtype= 'Monitor' ANDitems_id = '4182') OR (itemtype= 'Monitor' ANDitems_id = '4182') OR (itemtype= 'Monitor' ANDitems_id = '4187') OR (itemtype= 'Monitor' ANDitems_id = '4191') OR (itemtype= 'Monitor' ANDitems_id= '4191') ORDER BYlast_contactDESC LIMIT [1]`

### Your GLPI setup information

Operating system: Linux vglpi 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi.ifremer.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release '22', Revision '7e301439b65'
	Server Version: 8.0.30-22
	Server SQL Mode: STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: glpiadmin@mysql8.nodomain.glpi/glpi
	Host info: mysql8.nodomain.glpi via TCP/IP
	
PHP version (7.4.33) is supported.PHP version (7.4.33) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.Database engine version (8.0.30) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated. Write access to /var/www/glpi/config has been validated. Write access to /var/www/glpi/files/_cron has been validated. Write access to /var/www/glpi/files has been validated. Write access to /var/www/glpi/files/_dumps has been validated. Write access to /var/www/glpi/files/_graphs has been validated. Write access to /var/www/glpi/files/_lock has been validated. Write access to /var/www/glpi/files/_pictures has been validated. Write access to /var/www/glpi/files/_plugins has been validated. Write access to /var/www/glpi/files/_rss has been validated. Write access to /var/www/glpi/files/_sessions has been validated. Write access to /var/www/glpi/files/_tmp has been validated. Write access to /var/www/glpi/files/_uploads has been validated.Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/glpi": ‣ "/var/www/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "/var/www/glpi":
‣ "/var/www/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.Sessions configuration is secured.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by stonebuzz** [comment]
Hi @chris29B 

when do you have these SQL request?

When display Computer ?

**Comment by chris29B** [comment]
When I consult a Computer. He search the information for GLPI Agent, in the table glpi_agents. And the request whas very bad

3MB the request

**Comment by cconard96** [comment]
Can you test this patch to see if it is any better?

```diff
diff --git a/src/Features/Inventoriable.php b/src/Features/Inventoriable.php
index fec613fc21..e2bbd7f311 100644
--- a/src/Features/Inventoriable.php
+++ b/src/Features/Inventoriable.php
@@ -274,11 +274,20 @@ JAVASCRIPT;
             );
             if (count($relations_iterator) > 0) {
                 $conditions = ['OR' => []];
+                $itemtype_ids = [];
                 foreach ($relations_iterator as $relation_data) {
-                    $conditions['OR'][] = [
-                        'itemtype' => $relation_data['itemtype'],
-                        'items_id' => $relation_data['items_id'],
-                    ];
+                    if (!isset($itemtype_ids[$relation_data['itemtype']])) {
+                        $itemtype_ids[$relation_data['itemtype']] = [];
+                    }
+                    $itemtype_ids[$relation_data['itemtype']][] = $relation_data['items_id'];
+                }
+                foreach ($itemtype_ids as $itemtype => $ids) {
+                    if (count($ids) > 0) {
+                        $conditions['OR'][] = [
+                            'itemtype' => $itemtype,
+                            'items_id' => $ids
+                        ];
+                    }
                 }
                 $agent = $this->getMostRecentAgent($conditions);
             }
```

Rather than individual conditions for each itemtype/ID pair, it groups the IDs by itemtype. There should only be 1 set of conditions per itemtype now. I don't have any GLPI agents to test this.

**Comment by chris29B** [comment]
Thanks, I test the patch, but I must reastivate GLPI Inventory first and test when many device was inevntory and I return a response.

**Comment by trasher** [comment]
ping @chris29B ?

**Comment by trasher** [comment]
No feedback, I close

**Comment by chris29B** [comment]
Hello, sorry if my response too late

The code was very good. The patch match, I have a parc with 5000 hosts and the time for the inventory I long.

You ca merge this code to project. Thanks a lot

**Comment by trasher** [comment]
OK thanks for feedback. But I'm still kind of surprised of kind of query; I'd like to understand what really happens.

This query tries to load an very large amount of monitors when you're just showing a Computer; that does not looks correct at all.

**Comment by trasher** [comment]
To make things clear: Curtis solution may fix the performance issue, but if this query should not run at all, even with perfomance boost, it's far better.

**Comment by stonebuzz** [comment]
@chris29B 
can you check if this ```Computer``` have a lot of ```Monitor``` linked ?

**Comment by trasher** [comment]
@chris29B does this happen on all computers or just one? Is it linked to many monitors? (check `glpi_computers_items` table with `itemtype = 'Monitor` and `computers_id` the id of computer)

**Comment by chris29B** [comment]
The computer have normally 2 or 4 Monitor. I have 64119 line un glpi_computers_items. When I check with SELECT * FROM glpi.glpi_computers_items WHERE itemtype = "Monitor"; I have 9703 rows returned

**Comment by trasher** [comment]
Well, we were asking to check in the table the numnber of monitor linked to displayed computers, total number is irrelevant.

Anyways; with current nightly, displaying an inventoried computer never query glpi_agents on monitors. EIther your problem has been already solved, either we miss information to reproduce.

**Comment by jjmg84** [comment]
Hi, i had same problem, i had detected that in case a computer havent agent in glpi_agents, but have is_dynamic = 1 on glpi computers table, and you see computer with superadmin profile, then glpi launch this query, i have temporaly resolved it changing is_dynamic to 0 on computers that dont have Agent assigned.

i hope it can be useful for U

**Comment by trasher** [comment]
Thanks for the clarifiactions @jjmg84.

Please test with #14315. It includes Curtis fix proposal; but it should also fix the real initial issue (it was using all knowns relations, while it shoumd have been using current computer ones only).

**Comment by jjmg84** [comment]
> Thanks for the clarifiactions @jjmg84.
> 
> Please test with #14315. It includes Curtis fix proposal; but it should also fix the real initial issue (it was using all knowns relations, while it should have been using current computer ones only).

Thanks, it work like a Charm :) no more SQL queries stuck.

Thanks, :)
