### ISSUE TITLE
Can't search ticket category when type is set to incident

### ISSUE THREAD

**Issue by KMKG-MRAH** [glpi-project/glpi#14152]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Problem: When updating a ticket category, I can't search the category combobox if the Type is set to Incident. It does work when Type is set to Request.

Expected: Searching in the Category field is possible with type set to Incident.

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Create some ticket categories for both Request and Incident
2. Update a ticket. Set Type to Incident, try changing the category. Notice the search box at the top of the list is missing.
3. Set the Type to Request. Notice that now the search box appears.
![glpi-category-request](https://user-images.githubusercontent.com/92576879/220887558-d3960d89-bc20-42ae-bfc4-9e71d290aa48.png)
![glpi-category-incident](https://user-images.githubusercontent.com/92576879/220887561-eb8d9a27-4b41-4d40-bbe2-f2e3ad61d27a.png)

**Comment by cconard96** [comment]
Please verify that the "Page size for dropdown" in Setup > General > General Setup isn't set to a high number. If it is, it is likely that it is set higher than the number of categories configured to be allowed for incidents, but lower than the number allowed for requests.
