### ISSUE TITLE
Request with GLPI Agent, big latency, bad sql

### ISSUE THREAD

**Issue by chris29B** [glpi-project/glpi#14155]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6 

### Bug description

Bonjour,

J'ai un parc d'environs 5000 machines qui été inventorier jusqu'a présent avec OCS Inventory, depuis environs 1 an, nous migrons sur GLPI Agent, actuellement en 1.4.

Depuis la version 10.0.6 nous avons constaté d'énorme lenteur, car il y a un souci avec les requests passé sur la tables GLPI_agents, la resquest SQL à sans doute été fait via un autogénérateur:

`SELECT `id` FROM `glpi_agents` WHERE ((`itemtype` = 'Monitor' AND `items_id` = '5') OR (`itemtype` = 'Monitor' AND `items_id` = '7') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '9') OR (`itemtype` = 'Monitor' AND `items_id` = '25') OR (`itemtype` = 'Monitor' AND `items_id` = '41') OR (`itemtype` = 'Monitor' AND `items_id` = '67') OR (`itemtype` = 'Monitor' AND `items_id` = '80') OR (`itemtype` = 'Monitor' AND `items_id` = '82') OR (`itemtype` = 'Monitor' AND `items_id` = '99') OR (`itemtype` = 'Monitor' AND `items_id` = '115') OR (`itemtype` = 'Monitor' AND `items_id` = '121') OR (`itemtype` = 'Monitor' AND `items_id` = '138') OR (`itemtype` = 'Monitor' AND `items_id` = '166') OR (`itemtype` = 'Monitor' AND `items_id` = '173') OR (`itemtype` = 'Monitor' AND `items_id` = '204') OR (`itemtype` = 'Monitor' AND `items_id` = '277') OR (`itemtype` = 'Monitor' AND `items_id` = '322') OR (`itemtype` = 'Monitor' AND `items_id` = '323') OR (`itemtype` = 'Monitor' AND `items_id` = '359') OR (`itemtype` = 'Monitor' AND `items_id` = '388') OR (`itemtype` = 'Monitor' AND `items_id` = '428') OR (`itemtype` = 'Monitor' AND `items_id` = '434') OR (`itemtype` = 'Monitor' AND `items_id` = '463') OR (`itemtype` = 'Monitor' AND `items_id` = '520') OR (`itemtype` = 'Monitor' AND `items_id` = '546') OR (`itemtype` = 'Monitor' AND `items_id` = '565') OR (`itemtype` = 'Monitor' AND `items_id` = '607') OR (`itemtype` = 'Monitor' AND `items_id` = '674') OR (`itemtype` = 'Monitor' AND `items_id` = '690') OR (`itemtype` = 'Monitor' AND `items_id` = '691') OR (`itemtype` = 'Monitor' AND `items_id` = '723') OR (`itemtype` = 'Monitor' AND `items_id` = '744') OR (`itemtype` = 'Monitor' AND `items_id` = '777') OR (`itemtype` = 'Monitor' AND `items_id` = '846') OR (`itemtype` = 'Monitor' AND `items_id` = '883') OR (`itemtype` = 'Monitor' AND `items_id` = '900') OR (`itemtype` = 'Monitor' AND `items_id` = '924') OR (`itemtype` = 'Monitor' AND `items_id` = '929') OR (`itemtype` = 'Monitor' AND `items_id` = '935') OR (`itemtype` = 'Monitor' AND `items_id` = '1115') OR (`itemtype` = 'Monitor' AND `items_id` = '1149') OR (`itemtype` = 'Monitor' AND `items_id` = '1161') OR (`itemtype` = 'Monitor' AND `items_id` = '1271') OR (`itemtype` = 'Monitor' AND `items_id` = '1301') OR (`itemtype` = 'Monitor' AND `items_id` = '1357') OR (`itemtype` = 'Monitor' AND `items_id` = '1416') OR (`itemtype` = 'Monitor' AND `items_id` = '1419') OR (`itemtype` = 'Monitor' AND `items_id` = '1425') OR (`itemtype` = 'Monitor' AND `items_id` = '1436') OR (`itemtype` = 'Monitor' AND `items_id` = '1487') OR (`itemtype` = 'Monitor' AND `items_id` = '1512') OR (`itemtype` = 'Monitor' AND `items_id` = '1546') OR (`itemtype` = 'Monitor' AND `items_id` = '1611') OR (`itemtype` = 'Monitor' AND `items_id` = '1753') OR (`itemtype` = 'Monitor' AND `items_id` = '1902') OR (`itemtype` = 'Monitor' AND `items_id` = '1927') OR (`itemtype` = 'Monitor' AND `items_id` = '1937') OR (`itemtype` = 'Monitor' AND `items_id` = '1989') OR (`itemtype` = 'Monitor' AND `items_id` = '2034') OR (`itemtype` = 'Monitor' AND `items_id` = '2035') OR (`itemtype` = 'Monitor' AND `items_id` = '2089') OR (`itemtype` = 'Monitor' AND `items_id` = '2096') OR (`itemtype` = 'Monitor' AND `items_id` = '2097') OR (`itemtype` = 'Monitor' AND `items_id` = '2098') OR (`itemtype` = 'Monitor' AND `items_id` = '2099') OR (`itemtype` = 'Monitor' AND `items_id` = '2100') OR (`itemtype` = 'Monitor' AND `items_id` = '2101') OR (`itemtype` = 'Monitor' AND `items_id` = '2118') OR (`itemtype` = 'Monitor' AND `items_id` = '2148') OR (`itemtype` = 'Monitor' AND `items_id` = '2419') OR (`itemtype` = 'Monitor' AND `items_id` = '2535') OR (`itemtype` = 'Monitor' AND `items_id` = '2539') OR (`itemtype` = 'Monitor' AND `items_id` = '2584') OR (`itemtype` = 'Monitor' AND `items_id` = '2656') OR (`itemtype` = 'Monitor' AND `items_id` = '2809') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2810') OR (`itemtype` = 'Monitor' AND `items_id` = '2886') OR (`itemtype` = 'Monitor' AND `items_id` = '3096') OR (`itemtype` = 'Monitor' AND `items_id` = '3231') OR (`itemtype` = 'Monitor' AND `items_id` = '3341') OR (`itemtype` = 'Monitor' AND `items_id` = '3463') OR (`itemtype` = 'Monitor' AND `items_id` = '3538') OR (`itemtype` = 'Monitor' AND `items_id` = '3600') OR (`itemtype` = 'Monitor' AND `items_id` = '3640') OR (`itemtype` = 'Monitor' AND `items_id` = '3654') OR (`itemtype` = 'Monitor' AND `items_id` = '3664') OR (`itemtype` = 'Monitor' AND `items_id` = '3687') OR (`itemtype` = 'Monitor' AND `items_id` = '3765') OR (`itemtype` = 'Monitor' AND `items_id` = '3769') OR (`itemtype` = 'Monitor' AND `items_id` = '3805') OR (`itemtype` = 'Monitor' AND `items_id` = '3818') OR (`itemtype` = 'Monitor' AND `items_id` = '3881') OR (`itemtype` = 'Monitor' AND `items_id` = '3881') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3889') OR (`itemtype` = 'Monitor' AND `items_id` = '3894') OR (`itemtype` = 'Monitor' AND `items_id` = '3894') OR (`itemtype` = 'Monitor' AND `items_id` = '3899') OR (`itemtype` = 'Monitor' AND `items_id` = '3909') OR (`itemtype` = 'Monitor' AND `items_id` = '3910') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3911') OR (`itemtype` = 'Monitor' AND `items_id` = '3927') OR (`itemtype` = 'Monitor' AND `items_id` = '3930') OR (`itemtype` = 'Monitor' AND `items_id` = '3934') OR (`itemtype` = 'Monitor' AND `items_id` = '3937') OR (`itemtype` = 'Monitor' AND `items_id` = '3946') OR (`itemtype` = 'Monitor' AND `items_id` = '3946') OR (`itemtype` = 'Monitor' AND `items_id` = '3946') OR (`itemtype` = 'Monitor' AND `items_id` = '3946') OR (`itemtype` = 'Monitor' AND `items_id` = '3946') OR (`itemtype` = 'Monitor' AND `items_id` = '3951') OR (`itemtype` = 'Monitor' AND `items_id` = '3951') OR (`itemtype` = 'Monitor' AND `items_id` = '3953') OR (`itemtype` = 'Monitor' AND `items_id` = '3953') OR (`itemtype` = 'Monitor' AND `items_id` = '3953') OR (`itemtype` = 'Monitor' AND `items_id` = '3958') OR (`itemtype` = 'Monitor' AND `items_id` = '3958') OR (`itemtype` = 'Monitor' AND `items_id` = '3958') OR (`itemtype` = 'Monitor' AND `items_id` = '3958') OR (`itemtype` = 'Monitor' AND `items_id` = '3958') OR (`itemtype` = 'Monitor' AND `items_id` = '3960') OR (`itemtype` = 'Monitor' AND `items_id` = '3960') OR (`itemtype` = 'Monitor' AND `items_id` = '3960') OR (`itemtype` = 'Monitor' AND `items_id` = '3960') OR (`itemtype` = 'Monitor' AND `items_id` = '3962') OR (`itemtype` = 'Monitor' AND `items_id` = '3962') OR (`itemtype` = 'Monitor' AND `items_id` = '3965') OR (`itemtype` = 'Monitor' AND `items_id` = '3965') OR (`itemtype` = 'Monitor' AND `items_id` = '3969') OR (`itemtype` = 'Monitor' AND `items_id` = '3969') OR (`itemtype` = 'Monitor' AND `items_id` = '3969') OR (`itemtype` = 'Monitor' AND `items_id` = '3969') OR (`itemtype` = 'Monitor' AND `items_id` = '3978') OR (`itemtype` = 'Monitor' AND `items_id` = '3978') OR (`itemtype` = 'Monitor' AND `items_id` = '3984') OR (`itemtype` = 'Monitor' AND `items_id` = '3984') OR (`itemtype` = 'Monitor' AND `items_id` = '3984') OR (`itemtype` = 'Monitor' AND `items_id` = '3984') OR (`itemtype` = 'Monitor' AND `items_id` = '3986') OR (`itemtype` = 'Monitor' AND `items_id` = '3996') OR (`itemtype` = 'Monitor' AND `items_id` = '3997') OR (`itemtype` = 'Monitor' AND `items_id` = '3997') OR (`itemtype` = 'Monitor' AND `items_id` = '4007') OR (`itemtype` = 'Monitor' AND `items_id` = '4011') OR (`itemtype` = 'Monitor' AND `items_id` = '4011') OR (`itemtype` = 'Monitor' AND `items_id` = '4014') OR (`itemtype` = 'Monitor' AND `items_id` = '4015') OR (`itemtype` = 'Monitor' AND `items_id` = '4015') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4016') OR (`itemtype` = 'Monitor' AND `items_id` = '4019') OR (`itemtype` = 'Monitor' AND `items_id` = '4026') OR (`itemtype` = 'Monitor' AND `items_id` = '4026') OR (`itemtype` = 'Monitor' AND `items_id` = '4026') OR (`itemtype` = 'Monitor' AND `items_id` = '4026') OR (`itemtype` = 'Monitor' AND `items_id` = '4027') OR (`itemtype` = 'Monitor' AND `items_id` = '4027') OR (`itemtype` = 'Monitor' AND `items_id` = '4027') OR (`itemtype` = 'Monitor' AND `items_id` = '4031') OR (`itemtype` = 'Monitor' AND `items_id` = '4032') OR (`itemtype` = 'Monitor' AND `items_id` = '4034') OR (`itemtype` = 'Monitor' AND `items_id` = '4034') OR (`itemtype` = 'Monitor' AND `items_id` = '4036') OR (`itemtype` = 'Monitor' AND `items_id` = '4038') OR (`itemtype` = 'Monitor' AND `items_id` = '4038') OR (`itemtype` = 'Monitor' AND `items_id` = '4041') OR (`itemtype` = 'Monitor' AND `items_id` = '4042') OR (`itemtype` = 'Monitor' AND `items_id` = '4042') OR (`itemtype` = 'Monitor' AND `items_id` = '4042') OR (`itemtype` = 'Monitor' AND `items_id` = '4042') OR (`itemtype` = 'Monitor' AND `items_id` = '4042') OR (`itemtype` = 'Monitor' AND `items_id` = '4043') OR (`itemtype` = 'Monitor' AND `items_id` = '4045') OR (`itemtype` = 'Monitor' AND `items_id` = '4046') OR (`itemtype` = 'Monitor' AND `items_id` = '4046') OR (`itemtype` = 'Monitor' AND `items_id` = '4046') OR (`itemtype` = 'Monitor' AND `items_id` = '4046') OR (`itemtype` = 'Monitor' AND `items_id` = '4046') OR (`itemtype` = 'Monitor' AND `items_id` = '4049') OR (`itemtype` = 'Monitor' AND `items_id` = '4049') OR (`itemtype` = 'Monitor' AND `items_id` = '4051') OR (`itemtype` = 'Monitor' AND `items_id` = '4054') OR (`itemtype` = 'Monitor' AND `items_id` = '4058') OR (`itemtype` = 'Monitor' AND `items_id` = '4058') OR (`itemtype` = 'Monitor' AND `items_id` = '4058') OR (`itemtype` = 'Monitor' AND `items_id` = '4064') OR (`itemtype` = 'Monitor' AND `items_id` = '4065') OR (`itemtype` = 'Monitor' AND `items_id` = '4065') OR (`itemtype` = 'Monitor' AND `items_id` = '4065') OR (`itemtype` = 'Monitor' AND `items_id` = '4065') OR (`itemtype` = 'Monitor' AND `items_id` = '4066') OR (`itemtype` = 'Monitor' AND `items_id` = '4066') OR (`itemtype` = 'Monitor' AND `items_id` = '4067') OR (`itemtype` = 'Monitor' AND `items_id` = '4071') OR (`itemtype` = 'Monitor' AND `items_id` = '4073') OR (`itemtype` = 'Monitor' AND `items_id` = '4073') OR (`itemtype` = 'Monitor' AND `items_id` = '4077') OR (`itemtype` = 'Monitor' AND `items_id` = '4082') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4087') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4088') OR (`itemtype` = 'Monitor' AND `items_id` = '4092') OR (`itemtype` = 'Monitor' AND `items_id` = '4092') OR (`itemtype` = 'Monitor' AND `items_id` = '4095') OR (`itemtype` = 'Monitor' AND `items_id` = '4109') OR (`itemtype` = 'Monitor' AND `items_id` = '4120') OR (`itemtype` = 'Monitor' AND `items_id` = '4120') OR (`itemtype` = 'Monitor' AND `items_id` = '4120') OR (`itemtype` = 'Monitor' AND `items_id` = '4120') OR (`itemtype` = 'Monitor' AND `items_id` = '4123') OR (`itemtype` = 'Monitor' AND `items_id` = '4123') OR (`itemtype` = 'Monitor' AND `items_id` = '4123') OR (`itemtype` = 'Monitor' AND `items_id` = '4123') OR (`itemtype` = 'Monitor' AND `items_id` = '4125') OR (`itemtype` = 'Monitor' AND `items_id` = '4125') OR (`itemtype` = 'Monitor' AND `items_id` = '4127') OR (`itemtype` = 'Monitor' AND `items_id` = '4134') OR (`itemtype` = 'Monitor' AND `items_id` = '4134') OR (`itemtype` = 'Monitor' AND `items_id` = '4134') OR (`itemtype` = 'Monitor' AND `items_id` = '4135') OR (`itemtype` = 'Monitor' AND `items_id` = '4135') OR (`itemtype` = 'Monitor' AND `items_id` = '4135') OR (`itemtype` = 'Monitor' AND `items_id` = '4135') OR (`itemtype` = 'Monitor' AND `items_id` = '4135') OR (`itemtype` = 'Monitor' AND `items_id` = '4141') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4143') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4158') OR (`itemtype` = 'Monitor' AND `items_id` = '4166') OR (`itemtype` = 'Monitor' AND `items_id` = '4168') OR (`itemtype` = 'Monitor' AND `items_id` = '4169') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4170') OR (`itemtype` = 'Monitor' AND `items_id` = '4172') OR (`itemtype` = 'Monitor' AND `items_id` = '4178') OR (`itemtype` = 'Monitor' AND `items_id` = '4180') OR (`itemtype` = 'Monitor' AND `items_id` = '4182') OR (`itemtype` = 'Monitor' AND `items_id` = '4182') OR (`itemtype` = 'Monitor' AND `items_id` = '4182') OR (`itemtype` = 'Monitor' AND `items_id` = '4187') OR (`itemtype` = 'Monitor' AND `items_id` = '4191') OR (`itemtype` = 'Monitor' AND `items_id` = '4191') ORDER BY `last_contact` DESC LIMIT 1 `

### Relevant log output

```shell
J'ai alleger la requete car sinon ça ne passe pas dans la request, mais une recherche alétaoire avec des OR à chaque intérogation de poste, il y a un souci
```

**Comment by trasher** [comment]
It's been asked to write only in english.
