### ISSUE TITLE
JSON import problem in specific condition

### ISSUE THREAD

**Issue by ywh-jmorillo** [glpi-project/glpi#14153]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Given a fresh GLPI 10.0.6 install
Given I manually add a computer with minimal info: only set "serial number" = abcd1234 and save.
Given I manually import a json with inventories informations about a computer with serial = abcd1234
Import failed with msg:
`PHP User Error (256): Incorrect integer value: '' for column `glpidb`.`glpi_logs`.`items_id` at row 1 in /var/www/html/glpi/src/DBmysql.php at line 1969`

SQL error: 
`INSERT INTO `glpi_logs` (`items_id`, `itemtype`, `itemtype_link`, `linked_action`, `user_name`, `date_mod`, `id_search_option`, `old_value`, `new_value`) VALUES ('', 'OperatingSystem', 'Computer', '1', 'My user (5)', '2023-02-23 13:33:05', '0', '', 'abcd1234 (1)')

items_id can't be null

-> partial solution is to edit Computer and set an Operating system before importing json

### Your GLPI setup information

Fresh default install of 10.0.6

**Comment by trasher** [comment]
Please provide used inventory file

**Comment by trasher** [comment]
I've not reproduced yet your issue, but just importing your file already cause some errors that sounds strange. 
How this file has been generated? Did you operating system name?

**Comment by trasher** [comment]
OK, your inventory file seems very strange, and you're using an outdated agnt version installed form an untrusted source. Try with official recent agent build, and see if you reproduce.

Feel free to reopen with updated inventory file if you reproduce.

**Comment by ywh-jmorillo** [comment]
This file has been generated using latest [Wapt export-to-glpi plugin](https://store.wapt.fr/store/en/tis-glpi-plugin-export-to-glpi10)
For security reason, the serial has been reset from real one to abcd1234.
If we do not have a computer with serial abcd1234 in GLPI, we could import this json without problem.
The problem only occured if we pre-create a computer inside Glpi, with a serial and without Operating system name, and if we import a json in order to update this pre-created computer

**Comment by stonebuzz** [comment]
IMHO you are trying to use WAPTAgent with GLPI ( which seems to be a (bad) fork of GLPI-agent considering the generated inventory file)

https://www.wapt.fr/en/doc/wapt-console-usage-advanced-glpi.html

Please contact WAPT directly

**Comment by ywh-jmorillo** [comment]
operatingsystem -> name was missing on Wapt json.
a fix will be released soon by Wapt Team.
Thx for your support
