### ISSUE TITLE
Impossible to hide "watchers" field in ticket template

### ISSUE THREAD

**Issue by yodapotatofly** [glpi-project/glpi#14160]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

When I add "watchers" as a hidden field in a ticket template, the field is still visible in the ticket creation interface :

![image](https://user-images.githubusercontent.com/29150345/220976842-04655815-42ad-4a6b-ab45-9e1b3d10b727.png)

![image](https://user-images.githubusercontent.com/29150345/220977012-deea3abc-39f1-45ff-a30e-f8f6c6572363.png)

![image](https://user-images.githubusercontent.com/29150345/220976935-dc6bca45-8f80-48b0-b37c-5a4e1c09801f.png)

**Comment by gljones2001** [comment]
You have to hide both watcher, and watcher group. Just found this today.

**Comment by yodapotatofly** [comment]
@gljones2001 
Thank you, this is correct
