### ISSUE TITLE
 Knowledge base show articles without access when impersonate user

### ISSUE THREAD

**Issue by ftoledo** [glpi-project/glpi#14164]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When I impersonte user.. the FAQ section with self-service profile shows items he shouldn't have access to

Target is Supervisor profile on Root entity:

![imagen](https://user-images.githubusercontent.com/95441/221086396-a6762dd3-2d4f-4ca3-8bd8-07c886b86bca.png)

the KB is still show on user whitout the Supervisor profile and sub entity:

![imagen](https://user-images.githubusercontent.com/95441/221086808-4456d760-d409-461d-95eb-b97d57841e54.png)

on click on the item it's show access deny (not bad for security concerns):

![imagen](https://user-images.githubusercontent.com/95441/221086908-231ba7f3-139d-4359-a352-e71cd82c568c.png)

The expected result is that this item is not displayed because the user do not have the profile/entity as defined in target

**Comment by Phil-ipp1** [comment]
We have the same issue on our side.
We have multiple entities and each entity manages their own knowledge base.  
The knowledge articles Target is linked to one entity only but users from other entities (not sub entities) can see the articles as well.
Luckily this articles cannot be opened by users that are assigned to an entity which is not mentioned within the Target. So it is the same issue as described by ftoledo.

It would be important that users that are not part of the Target definition could not see the article (not even the topic/header).

**Comment by cedric-anne** [comment]
Hi,

Can you try to apply #13890 and see if problem persist?

**Comment by trasher** [comment]
N o feedback , I close

**Comment by Phil-ipp1** [comment]
@cedric-anne Sorry for the late reply.
This fix solved the issue! Thank you so much for the support finding the fix.
FYI: Tested it with formCreator as well and the plugin is fully compatible to the fix

**Comment by ftoledo** [comment]
alo! sorry for delay too!,
I try to apply the patch over 10.0.6:

# patch -p1 </tmp/13890.patch 
patching file src/KnowbaseItem.php
Hunk #2 FAILED at 1534.
1 out of 2 hunks FAILED -- saving rejects to file src/KnowbaseItem.php.rej
patching file src/KnowbaseItemCategory.php

**Comment by ftoledo** [comment]
I can confirm that update to 10.0.7 fix the issue. thanks!
