### ISSUE TITLE
Can't add new user with ldap sync

### ISSUE THREAD

**Issue by Ludo-code** [glpi-project/glpi#14174]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

GLPI doesn't to import more than 1500 users with the ldap ad server... we have more than 1500 users of course and wanted to continue importing them in glpi....

I have see the followed issue : 
https://github.com/glpi-project/glpi/issues/1024

But didn't know if she is still relevant....

**Comment by keguira** [comment]
could you provide more information ?
Does the connexion is valid ? 
Can you list users in users section > LDAP Directory link > import new users  ? If not, even in advanced mode ?

If yes, can you import one user to check if the error is not linked to a configuration of import rules ? 

Do you have any log entry related to this issue ?

**Comment by Ludo-code** [comment]
Hello according to [https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/authentication/ldap.html#advanced-information](https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/authentication/ldap.html#advanced-information)
we think it's a problem about ad server do not display more than 1000 users, my superiror have checked to sync the data and he won't sync more than 999 users and when trying to import only one users, console return an Sizelimit exceeded in the AuthLDAP.php at line 1875.

Are you thinking the same than me? I wan't to be sure it's juste the AD server before make the modification

**Comment by cedric-anne** [comment]
Hi,

Do you have any error in GLPI logs? Are you using the LDAP sync console command or the UI?
