### ISSUE TITLE
Entity lost after moving

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#14179]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6

### Bug description

When a sub-entity is moving or transfer from a parent entity to another entity, the permission for access to that entity is lost, even when we already have parent permission recursively.

When the access is lost, there is no way to access this entity.

### Relevant log output

```shell
n/a
```

### Steps To reproduce

1. Set super-admin permission as recursive in root entity
2. Create a entity and a subentity in it:

![image](https://user-images.githubusercontent.com/56606032/221685703-89629867-5e9f-4348-a53c-2784d6d776b8.png)

**TESTING MOVING DIFFERENTS WAY A SUB-ENTITY**
**_Changing As Child of:_**

3. Change "As Child of" and select the root entity and save:
![image](https://user-images.githubusercontent.com/56606032/221686087-aaf69d66-bc82-447a-904d-848ea0b430ca.png)

4. Log out, and log in again, go to menu Entities, and see the sub-entity is lost:

![image](https://user-images.githubusercontent.com/56606032/221686348-29cd4682-3a14-4304-80d7-6b190cdd4125.png)

**_Using Massive action: Move under._**

5. Create another sub-entity, in my case ETT3 under ET1
6. Select the sub-entity, and use the massive action: move under, and "As Child of:" select the root entity:

![image](https://user-images.githubusercontent.com/56606032/221686908-4c90f88f-387a-45f9-83d8-809663175c41.png)

7. Log out and log in again, go to menu Entities, and see the sub-entity is lost:

![image](https://user-images.githubusercontent.com/56606032/221686348-29cd4682-3a14-4304-80d7-6b190cdd4125.png)

**_Add to transfer list_**

8. Create another sub-entity, in my case ETT4 under ET1
9. Select the sub-entity, and select the action: "Add to transfer list"
10. Select Complete, and select the root entity, clic en "Execute":

![image](https://user-images.githubusercontent.com/56606032/221687786-68411615-261e-4798-a7c2-6c7c3fe2e488.png)

11.  Log out and log in again, go to menu Entities, and see the sub-entity is lost:

![image](https://user-images.githubusercontent.com/56606032/221686348-29cd4682-3a14-4304-80d7-6b190cdd4125.png)

As you can see, whatever way the sub-entity is moving from a sub-entity to the parent level, or prior, this entity dissapear, even when we have recursive privileges on parent.

### Your GLPI setup information

GLPI CLOUD

### Anything else?

The expected beheaviour is that we can get access to the sub-entity moved, as we already has recursive privilege at root entity.

**Comment by jcervantes-sipecom** [comment]
Maybe is something with the session variable glpiactiveentities? as said in: https://github.com/glpi-project/glpi/issues/14180

**Comment by AlexTR85** [comment]
https://github.com/glpi-project/glpi/issues/14095
Same probleme with entities

**Comment by jcervantes-sipecom** [comment]
Hi @cedric-anne I confirm this fix the issue.

**Comment by cedric-anne** [comment]
Thanks for the feedback.
