### ISSUE TITLE
Tickets change status value with slpitted button. Don't receive notification 

### ISSUE THREAD

**Issue by StephaneAtlani** [glpi-project/glpi#1418]
Hello everybody

On ticket, when I use "processing ticket " I create a followup and change status near "add" button and after I submit
I don't receveive notification.

I look code and I view in /inc/ticketfollowup.class.php file
```
// change ticket status (from splitted button)
         $this->input['_job'] = new Ticket();
         if (!$this->input['_job']->getFromDB($this->input["tickets_id"])) {
            return false;
         }
         if (isset($this->input['_status'])
             && ($this->input['_status'] != $this->input['_job']->fields['status'])) {
             $update['status']        = $this->input['_status'];
             $update['id']            = $this->input['_job']->fields['id'];
             $update['_disablenotif'] = true;
             $this->input['_job']->update($update);
          }
```

If I change  $update['_disablenotif'] value  to false. Can I receive notifcation ?

Last question, this is a bug or juste normal fonctionnality

Sorry for my bad english 

Best regards

**Comment by StephaneAtlani** [comment]
I found 
In configuration -> Notifications -> Notifications
You can configure 3 notifications " Add Followup " " Update Followup " " Delete Followup " 
for each notifications you can Add "recipients" and active the notification.

Best regards

**Comment by trasher** [comment]
Hello,

This duplicates #1400
