### ISSUE TITLE
Orphan entity after deleted and create a new one with same ID

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#14180]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6

### Bug description

This is an issue that I guess is related with: https://github.com/glpi-project/glpi/issues/14179

When createad an entity, then moved as indicated in the prior ticket, then deleted, and then create a new one, this new entity is assigned the same ID prior entity last deleted. But this new entity is innaccesible, like it's orphan.

### Relevant log output

```shell
N/A
```

### Steps To reproduce

1. Create a entity, in a sub-entity:

![image](https://user-images.githubusercontent.com/56606032/221701743-40e0b740-6d27-4ef9-b515-ba4d0212ab91.png)

2. Then move this sub-entity to root:

![image](https://user-images.githubusercontent.com/56606032/221702246-b5709705-5d44-46d7-ad8a-4f2f6847fde3.png)

3. Then log out and log int again, the entity dissappear or it's lost, as indicated in the prior ticket:

![image](https://user-images.githubusercontent.com/56606032/221702409-e6317d47-6b66-4b1e-8879-a61826968311.png)

4. To go the lost entity, just change the entity and select the hide one:

![image](https://user-images.githubusercontent.com/56606032/221732795-b0f3089e-415f-40b6-8302-96d2fa760a4d.png)

5. Go to the entity, and delete:

![image](https://user-images.githubusercontent.com/56606032/221734019-3e97f249-4a86-4d64-a396-3d93872a1fb9.png)

6. And error show up, but I think it's ok, but you can check it too:

![image](https://user-images.githubusercontent.com/56606032/221735863-85e6fb17-266d-4fe5-9076-e0c402832111.png)

![image](https://user-images.githubusercontent.com/56606032/221735974-7c9e541b-ad09-4859-8298-d2b749d8cb41.png)

7. Log out and log in
8. Create a new sub-entity, and as you can see the new entity has the same ID as the last one:

![image](https://user-images.githubusercontent.com/56606032/221736465-fa6ba8f2-9f75-4794-aa8d-b72b88c75040.png)

9. Try to change to this new entity, but as you can see nothing happend:

![image](https://user-images.githubusercontent.com/56606032/221736755-a247bf60-0550-4b9b-aa61-d3e545db32ab.png)

The active entity is not the same as the selected one:
![image](https://user-images.githubusercontent.com/56606032/221736882-50a6fa40-fd5b-463a-bac7-a22f369e2641.png)

Even when all the entities is selected, the session variable glpiactiveentities just show an array of 2 elements, but there is a lot of entities:

![image](https://user-images.githubusercontent.com/56606032/221738529-7a19f552-2a99-4631-8cfc-47791067d637.png)

### Your GLPI setup information

GLPI Cloud

**Comment by jcervantes-sipecom** [comment]
Hi @cedric-anne I confirm this fix the issue.

**Comment by cedric-anne** [comment]
Thanks for the feedback.
