### ISSUE TITLE
Knowledge Base editor fullscreen button doesn't do fullscreen and can't scroll to end

### ISSUE THREAD

**Issue by haary** [glpi-project/glpi#14184]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When editing an article in knowledge base  and hit the right-hand fullscreen button, the editor is not fully maximized, but leaves space at the top. It looks like this
![Bildschirmfoto_2023-02-28_15-50-38](https://user-images.githubusercontent.com/4052999/221890081-ce1403e5-9aa0-420d-9813-da02acfc77a8.png)

What's more serious is, that one cannot scroll to the end of the article, which means the end is not visible.  
Using Firefox 102.8.0 on Debian 11

### Your GLPI setup information

GLPI 10.0.6 (/glpi => /var/www/localhost/htdocs/glpi)
Installation mode: TARBALL
Current language:en_US

**Comment by cedric-anne** [comment]
Hi,

#14371 would fix it. As it changes a SCSS source file, change will be visible only on debug mode, or after SCSS recompilation.
