### ISSUE TITLE
Can't add "Camera items" (404)

### ISSUE THREAD

**Issue by aswayze-ops** [glpi-project/glpi#14186]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

Same issue as found in the GLPI forum https://forum.glpi-project.org/viewtopic.php?id=285906. We copied Generic Device form to Camera Device form.
sudo cp /var/www/glpi/front/item_devicegeneric.form.php /var/www/glpi/front/item_devicecamera.form.php just to test it out and get started, but sure you have more options/details available.

![image](https://user-images.githubusercontent.com/65136786/221951022-47f91fff-a091-4899-ba6d-ebc3dcdb2948.png)

![image](https://user-images.githubusercontent.com/65136786/221950886-5e62b37a-f821-4d7c-b3d8-5c2295bb51d7.png)

**Comment by trasher** [comment]
First of all, 10.0.5 is outdated, you should consider upgrading.

I've just tested on current nightly build, I cannot reproduce. Clicking on "Add" button lends to `glpi//front/device.php?itemtype=DeviceCamera` as expected.

**Comment by aswayze-ops** [comment]
Thank you, I'll make sure we confirm we have the latest release and test prior to submitting requests.
