### ISSUE TITLE
Glpi-Agent not updateing/inserting new computer sinc 10.0.6

### ISSUE THREAD

**Issue by Chico0008** [glpi-project/glpi#14223]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When i was on glpi 10.0.5, i had multiple computer having the glpi-agent installed (1.5 nightly)
new computers would contact the server, agent was in glpi, and inserting/updating computer component.

since updating to 10.0.6, not working anymore.
new computer have their agent seen in glpi, but nothing is added in inventory.

I'm using Glpi inventory plugin, and agent contact this plugin.
plugun has been updated to 1.1.0, same issue

### Relevant log output

```shell
glpi agent log (on computer)
[Wed Mar  1 13:38:55 2023][info] New inventory from PC002715.viry.net-2023-02-06-16-41-19 for server0
[Wed Mar  1 13:39:37 2023][error] [http client] communication error: 500 Internal Server Error
[Wed Mar  1 13:39:38 2023][info] target server0: next run: Wed Mar  1 14:30:26 2023 - http://glpi.viry.net/plugins/glpiinventory/

Server side (apache log)
[Wed Mar 01 13:39:37.625754 2023] [php:error] [pid 25293] [client 10.0.3.123:60496] PHP Fatal error:  Incorrect integer value: 'Dell' for column `glpi`.`glpi_softwares`.`manufacturers_id` at row 1 in /var/www/glpi/src/DBmysql.php on line 1969
```

**Comment by stonebuzz** [comment]
Hi @Chico0008 
already fix  =)
Can you try GLPI nightly build ?
https://nightly.glpi-project.org/glpi/

Best regards

**Comment by Chico0008** [comment]
Already tried with the last windows nightly (1.5-gitef14e36c)
same error

tried using native inventory url (/front/inventory.php) same

**Comment by stonebuzz** [comment]
I was talking about the GLPI nightly build not GLPI-agent nightly build
You can find GLPI Nightly Build here -> https://nightly.glpi-project.org/glpi/  ([10.0-1ead1b9.tar.gz](https://nightly.glpi-project.org/glpi/10.0-1ead1b9.tar.gz))

**Comment by Chico0008** [comment]
Oh, ok my bad >_<

just triend with the last Glpi nightly, it's ok now, computer are inserting/updating their inventory now.

thanks

**Comment by stonebuzz** [comment]
:+1:
