### ISSUE TITLE
10.0-nightly no longer has the link to front/unmanaged.php

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#14237]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10-nightly

### Bug description

Just for testing:  front/unmanaged.php is no longer allowed to be accessed in the latest nightly. People won't be able to convert unmanaged to managed then :-) Also, while unmanaged devices are still shown (eg when importing a network device), you can no longer click on it.
Unless this the intention of course.

**Comment by stonebuzz** [comment]
Dedicated right have been added

https://github.com/glpi-project/glpi/pull/14122

Can you check profil right ?

**Comment by liedekef** [comment]
Rights were ok, but needed to logout/login again after upgrade, so all ok now.
