### ISSUE TITLE
Hooks for plugins to add content in any item tab

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1424]
It would be usefull to allow plugins to add contents on any item tab.

See pluginsGLPI/fields#98 for example.

**Comment by tomolimo** [comment]
It's already possible if you use pre_show_item/post_show_item and pre_show_tab/post_show_tab :)

**Comment by trasher** [comment]
Oh, you're probably right; I'll have a look at those ones! Thank you!

**Comment by wawax** [comment]
hi tomolino,

the idea is to add content before showformheader or before showformbutton :)

**Comment by tomolimo** [comment]
ok, I better understand, these pre/post show hooks are used for the show of items or tabs, but not for forms.
