### ISSUE TITLE
Error when adding image/doc to KB

### ISSUE THREAD

**Issue by Piputrrrr** [glpi-project/glpi#14242]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

Error when adding image/doc to KB, when i save i get a "HTTP ERROR 500".

The image is add to the article but i get this error

For a document it didn't work at all, same error but nothing is added.

i tried insert and drag/drop => same 

### Page URL

https://glpi/front/knowbaseitem.form.php

### Your GLPI setup information

Tools => KB 

ADD 

insert or drag/drop image 

insert file (docx for example )

**Comment by Piputrrrr** [comment]
thank you for your time

**Comment by trasher** [comment]
Please provide logs files, as requested.

**Comment by Piputrrrr** [comment]
In access-errors.log : 


CSRF check failed for User ID: 1228 at /front/knowbaseitem.form.php

**Comment by cedric-anne** [comment]
Hi,

A 500 error code should produce a trace in `files/_logs/php-errors.log`. We need this one to be able to investigate. Could you provide it?

**Comment by trasher** [comment]
This error is related to glpiinventory tasks, not KB images.

**Comment by Piputrrrr** [comment]
Hi,

![image](https://user-images.githubusercontent.com/123753588/224719459-54ff82c0-3eb7-4afd-8595-1e2f9c13c91e.png)

I have 5 php-errors files and in two i have found this error :

[2023-02-13 08:15:32] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/usr/share/glpi/files/_log/cron.log): failed to open stream: Permission denied in /usr/share/glpi/src/Toolbox.php at line 599
  Backtrace :
  src/Toolbox.php:599                                error_log()
  src/CronTask.php:1014                              Toolbox::logInFile()
  front/cron.php:64                                  CronTask::launch()


but it didn't repeat after this date :/ 

Hope this help you,

**Comment by Piputrrrr** [comment]
i have retried just now and i still got error 500  on https://glpi/front/knowbaseitem.form.php when i try to insert doc to an existing KB.

I cannot add it even when i'm creating a new KB.


What is surprising is that when I add an image I have the error message but the image is added to the document ^^

**Comment by cedric-anne** [comment]
And is there something added in your GLPI logs when this error occurs?

**Comment by Piputrrrr** [comment]
didn't look like it :/

I just test now with a .txt and it worked perfectly.

i'm confused now, it work with .txt but not with .docx or .pdf

**Comment by cedric-anne** [comment]
What is the last modification date of your log files? Are you sure your are looking in the good directory?

Except maybe on really rare edge cases, a 500 error should be tracked in GLPI logs. If you do not see anything, it is maybe because your are not looking at good files.

**Comment by Piputrrrr** [comment]
Hi,

![image](https://user-images.githubusercontent.com/123753588/224924168-1f94e5bf-6046-4e17-b127-19db56edfaa2.png)

The only error i get in php-errors.log is ( every minute so maybe a cron )

[2023-03-14 08:20:01] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function fetch_array() on bool in /usr/share/glpi/src/DBmysql.php at line 524
  Backtrace :
  ...lpiinventory/inc/networkinventory.class.php:808 DBmysql->fetchArray()
  marketplace/glpiinventory/inc/task.class.php:685   PluginGlpiinventoryNetworkinventory->getDevicesOfIPRange()
  marketplace/glpiinventory/inc/task.class.php:913   PluginGlpiinventoryTask->prepareTaskjobs()
  src/CronTask.php:1018                              PluginGlpiinventoryTask::cronTaskscheduler()
  front/cron.php:84                                  CronTask::launch()

wich is not related to this issue :/ 

I'm sure that the good directory, i even did a search on all my server to find if another php-errors.log but nothing except an older version from when i update glpi.

![image](https://user-images.githubusercontent.com/123753588/224929694-ee9ec76b-b834-4ead-8071-aa11652a63c8.png)

Do you know if it's possible to investigate through debug mod ?

i tried but i just got redirect to the error 500 page :(

Thank you in advance,

**Comment by Piputrrrr** [comment]
PS : i moved all old logs to oldlog file so it will be easier to see

**Comment by cedric-anne** [comment]
Your log files are owned by `root` user and `www-data` user can probably not write anything to them.

I may be wrong, but I think your GLPI cron is executed by `root` user, and this is why it can write in log files. You should update your crontab to execute the GLPI cron as `www-data` user, and change ownership of all your GLPI files to `www-data`.

Your initial issue is probably due to lack of rights on upload directory.

**Comment by Piputrrrr** [comment]
Thank you very much, it was simply rights permissions that where missing :D

i just tried with an .xslx file and now it worked

**Comment by Piputrrrr** [comment]
Thank you @cedric-anne and @trasher for your help :)

have a nice day !
