### ISSUE TITLE
PHP Warning when updating item from API and debugger is not enabled

### ISSUE THREAD

**Issue by ac-mijm** [glpi-project/glpi#14255]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

When updating a Line from the API ([PUT] /apirest.php/Line/) the line is correctly updated but I get a WARNING message in the php-errors.log file.
It only occurs when the account used to make the API request has the debugger not enabled.

### Relevant log output

```shell
[2023-03-07 09:03:05] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in /var/www/glpi/inc/api/api.class.php at line 2355
  Backtrace :
  inc/api/api.class.php:2014                         Glpi\Api\API->getGlpiLastMessage()
  inc/api/apirest.class.php:301                      Glpi\Api\API->updateItems()
  apirest.php:53                                     Glpi\Api\APIRest->call()
```

### Steps To reproduce

1. Access GLPI with an account that has permission to update Lines.
2. Check that the debugger mode is disabled ("bug" icon in the toolbar)
3. Init session in the API, with the same account (using Postman): /apirest.php/initSession/
4. Send the request to update a Line using the token generated in the previous request: /apirest.php/Line/
5. You will get a successful message at Postman and the line will be updated, but a warning message will appear at php-errors.log

**Comment by trasher** [comment]
9.5 is no longer supported, please try if you can reproduce with latest stable.
