### ISSUE TITLE
Formcreator plugin display error after upgrade from glpi 9.0.5 to 10.0.3 

### ISSUE THREAD

**Issue by chumnor1** [glpi-project/glpi#14252]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

glpi verson: 10.0.3   Formcreator plugin version: 2.13.4

### Bug description

Dear All,

I have upgrade GLPI from version 9.0.5 to 10.0.3

everything seem fine except one plugin formcreator which form from old version display are error ( pls check on attach file 1 )

For new form create on new version of glpi are fine ( pls check on attach file 2 )
![attach 1](https://user-images.githubusercontent.com/29721874/223353579-4a1099a7-86b9-4982-a065-bf45745e95d3.jpg)
![attach 2](https://user-images.githubusercontent.com/29721874/223353724-63901e32-ca42-47c2-9a3f-ba4a9901a3c3.jpg)

**Comment by cedric-anne** [comment]
Hi,

First, you should use the lastest GLPI version, that is 10.0.6. Second, you should open an issue on [`formcreator` plugin repository](https://github.com/pluginsGLPI/formcreator), as it seems to be a bug in this plugin.

**Comment by chumnor1** [comment]
Hi @cedric-anne,

Thank for your reply.

For Upgrade to 10.0.6 we are on testing due we're using another plugins, we need to ensure those plugin also working well after upgraded. 

Anyways, I will open an issue on formcreator per your suggested.

Thank you,
Chumnor
