### ISSUE TITLE
default resports OS list for a sub entity contains data of all entities

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#14257]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When generating a "default report" for a subentity under Tools > Reports > Default report the asset list (Computers, Monitors, ...) cointains only the data of the selected entity. The "Operating systems" list contains the data of all entities on the server. The OS list should be limited to the OS information of the subentity. In the image there are no Computers in the entity but 3 OS.
![image](https://user-images.githubusercontent.com/5680717/223377601-54f9eeb9-5748-4fef-b705-37a694a1e506.png)

### Steps To reproduce

1. Add a computer with OS to the root entity
2. Create a subentity of the root entity
3. Switch to a limit view of the subentity (select the subentity in the list of the menu in the upper right corner of glpi)
4. Go to Tools > Reports > Default report
5. There are no Computers in the list since no Computer are in the subentity, but the OS is listed

**Comment by stonebuzz** [comment]
Hi @AndiMb 
can you try this -> https://github.com/glpi-project/glpi/pull/14258

**Comment by AndiMb** [comment]
Hi, yeah, this works. Now the correct OS are listed. Thanks!

**Comment by cedric-anne** [comment]
Fixed by #14258.
