### ISSUE TITLE
[PHP 8.0] [glpi 10.06] Glpi refers to /index.php?error=1

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#14269]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

I went from php 7.4 to 8 and I have this: nothing in the logs. Thank you

GLpi refers to  /index.php?error=1

```
140.77.x.x - [08/Mar/2023:09:58:43 +0100] "GET / HTTP/1.1" 302 440 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
140.77.x.x - - [08/Mar/2023:09:58:43 +0100] "GET /front/login.php HTTP/1.1" 302 441 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
140.77.x.x - - [08/Mar/2023:09:58:43 +0100] "GET /index.php?error=1 HTTP/1.1" 302 439 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
```
The file/_sessions directory is in writing. Thank you

**Comment by cedric-anne** [comment]
Hi,

You should clean your browser cookies and try again. You could also try to to login using a private browsing session, to see if problem persist.

**Comment by falco2001** [comment]
If I already tried to empty the cookies and I also tried of course in private browsing. I also tried to delete the content of files/_sessions but idem

**Comment by cedric-anne** [comment]
It seems that GLPI is not able to retrieve session from a page to another. You should check your PHP/Web server configuration, maybe the `session.cookie_domain` or `session.cookie_path` is not correct.

Anyway, this is not a GLPI bug, so I will close the issue as we only track bugs here.

**Comment by falco2001** [comment]
yes but it worked perfectly with php 7.4! Do you have an idea? thanks

**Comment by cedric-anne** [comment]
> yes but it worked perfectly with php 7.4! Do you have an idea? thanks

I never heard about such an issue. You should ask on forums for help, maybe you will find there someone that already had this issue.
