### ISSUE TITLE
error cleaning orphaned inventory files

### ISSUE THREAD

**Issue by YannickBarone** [glpi-project/glpi#14273]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,

I receive this error when cleanorphans automatic task is running :

```
Les actions automatiques suivantes sont en erreur. Elles nécessitent une intervention.

[cleanorphans] : Nettoyages des fichiers orphelins venant des inventaires
```

And when I run the following php script :

`php front/cron.php --force cleanorphans`
```
.Uncaught Exception Error: Class 'refusedequipment' not found in /var/www/glpi.10.0.6/src/Inventory/Inventory.php at line 905
```

**Comment by cedric-anne** [comment]
Hi,

Can you provide the full error trace that could be found in `files/_logs/php-errors.log`?

**Comment by YannickBarone** [comment]
Hi Cédric,

Please find below the requested logs :

[2023-03-09 08:52:11] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'refusedequipment' not found in /var/www/glpi.10.0.6/src/Inventory/Inventory.php at line 905
  Backtrace :
  src/CronTask.php:1018                              Glpi\Inventory\Inventory::cronCleanorphans()
  front/cron.php:79                                  CronTask::launch()


De : Cédric Anne ***@***.***>
Envoyé : mercredi, 8 mars 2023 18:19
À : glpi-project/glpi ***@***.***>
Cc : BARONE Yannick ***@***.***>; Author ***@***.***>
Objet : Re: [glpi-project/glpi] cleanorphans : Nettoyages des fichiers orphelins venant des inventaires (Issue #14273)


Hi,

Can you provide the full error trace that could be found in files/_logs/php-errors.log?

**Comment by trasher** [comment]
Please provide requested information (at leasdt GLPI setup)

**Comment by YannickBarone** [comment]
<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 ( => /var/www/glpi.10.0.6)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre>
Operating system: Linux slgepgpi01 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Tue Feb 21 19:25:54 UTC 2023 x86_64
PHP 7.4.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
                date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
                openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter,
                xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
                upload_max_filesize="2M"
Software: Apache/2.4.37 (rocky) OpenSSL/1.1.1k ()
                Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Server Software: MariaDB Server
                Server Version: 10.3.35-MariaDB
                Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
                Parameters: ***@***.***/glpidb
                Host info: Localhost via UNIX socket

PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
GLPI data directories are located in a secured path.
SELinux configuration is OK.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi.10.0.6/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre>
GLPI_ROOT: "/var/www/glpi.10.0.6"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/glpi.10.0.6/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/<file:///.*)%3f$/>"]
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: ***@***.******@***.***>
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_LOG_DIR: "/var/lib/glpi/_log"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: "/var/www/glpi.10.0.6/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: ***@***.******@***.***>
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre>
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi.10.0.6/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/glpi.10.0.6/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi.10.0.6/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi.10.0.6/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi.10.0.6/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi.10.0.6/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi.10.0.6/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi.10.0.6/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi.10.0.6/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi.10.0.6/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi.10.0.6/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi.10.0.6/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi.10.0.6/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi.10.0.6/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi.10.0.6/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi.10.0.6/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi.10.0.6/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi.10.0.6/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi.10.0.6/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi.10.0.6/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi.10.0.6/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi.10.0.6/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi.10.0.6/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi.10.0.6/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi.10.0.6/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi.10.0.6/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi.10.0.6/vendor/psr/cache/src)
league/csv in (/var/www/glpi.10.0.6/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi.10.0.6/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi.10.0.6/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi.10.0.6/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi.10.0.6/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi.10.0.6/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi.10.0.6/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi.10.0.6/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi.10.0.6/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi.10.0.6/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi.10.0.6/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi.10.0.6/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi.10.0.6/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi.10.0.6/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi.10.0.6/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/glpi.10.0.6/vendor/symfony/polyfill-php82)
phpCas version 1.4.0 in (/usr/share/pear)

</details><details><summary>LDAP directories</summary><pre>
Server:contoso.ch', Port: '389', BaseDN: 'DC=CONTOSO,DC=CH', Connection filter:
                               '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'DemonGlpi', Use TLS:
                               none

</details><details><summary>SQL replicas</summary><pre>
Not active

</details><details><summary>Notifications</summary><pre>
Way of sending emails: SMTP ()

</details><details><summary>Plugins list</summary><pre>
                addressing           Name: Adressage IP                   Version: 3.0.1      State: Enabled
                               Install Method: Manual
                news                 Name: Alertes                        Version: 1.10.5     State: Enabled
                               Install Method: Manual
                webapplications      Name: Applications Web               Version: 4.0.1      State: Enabled
                               Install Method: Manual
                positions            Name: Cartographie                   Version: 6.0.2      State: Enabled
                               Install Method: Manual
                accounts             Name: Comptes                        Version: 3.0.2      State: Enabled
                               Install Method: Manual
                fpsoftware           Name: FP Software                    Version: 2.0.0      State: Installed / not activated
                               Install Method: Manual
                order                Name: Gestion des commandes          Version: 2.10.0     State: Enabled
                               Install Method: Manual
                moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled
                               Install Method: Manual
                archisw              Name: Structures d'Applications      Version: 2.2.14     State: Enabled
                               Install Method: Manual

</pre></details>


De : Johan Cwiklinski ***@***.***>
Envoyé : jeudi, 9 mars 2023 09:04
À : glpi-project/glpi ***@***.***>
Cc : BARONE Yannick ***@***.***>; Author ***@***.***>
Objet : Re: [glpi-project/glpi] error cleaning orphaned inventory files (Issue #14273)


Please provide requested information (at leasdt GLPI setup)

**Comment by trasher** [comment]
Thanks. I'm able to reproduce.
