### ISSUE TITLE
Manual link - validation error if url contains a &

### ISSUE THREAD

**Issue by AndiFo** [glpi-project/glpi#14286]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Form brings an error if the URL contains a & and cannot be saved.

### Page URL

front/manuallink.form.php

### Steps To reproduce

1. Add manual link
2. Copy a url (example: https://localhost/glpi/front/ticket.php?is_deleted=0&)
3. Save
4. Error invalid url

**Comment by cconard96** [comment]
I confirm the issue. It seems like the `&` is being replaced with an HTML character code which then fails the URL verification.

**Comment by trasher** [comment]
This is already fiex in https://github.com/glpi-project/glpi/pull/14149

**Comment by cedric-anne** [comment]
> This is already fiex in #14149

This was on external links, but there is a remaining bug on manual links.

**Comment by trasher** [comment]
Oh, OK, sorry

**Comment by czare** [comment]
I'm also noticing this error on manual links, when trying to add a link to an external application (the link works just fine in the browser, but I'm not being able to store it in GLPI). Is that the intended behavior of this functionality? Or is it a bug?

<img width="1400" alt="Image" src="https://github.com/user-attachments/assets/acaa6ecb-cef9-4701-a0e4-d78f61b6da2f" />

**Comment by cedric-anne** [comment]
> I'm also noticing another related bug in manual links, when trying to add a link to an external application (the link works just fine in the browser, but I'm not being able to store it in GLPI). Is that the intended behavior of this functionality? Or is it a bug?
> 
> <img alt="Image" width="1400" src="https://private-user-images.githubusercontent.com/12159102/409951207-acaa6ecb-cef9-4701-a0e4-d78f61b6da2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzg3NTUyNzIsIm5iZiI6MTczODc1NDk3MiwicGF0aCI6Ii8xMjE1OTEwMi80MDk5NTEyMDctYWNhYTZlY2ItY2VmOS00NzAxLWEwZTQtZDc4ZjYxYjZkYTJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjA1VDExMjkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMDMyZjQ3YTYxY2UwNzUyMDk0NWE2NzEyZDE2MTRjMTRkNmIwOTdjODc2Yzk1YzM0ODljNzViNjUzNWZiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ae2KBrq_ZrMoIASKs3yLrtL8xvNHvWGw3bJF8SSZebc">
> Link:
> 
> rdm://open?DataSource=29168543-e018-4396-97b0-2bdfe0aea69a&Session=eda2554d-222c-44cd-899b-ff35d1851527

Please open a new issue with all requested information.

**Comment by czare** [comment]
@cedric-anne alright, done under https://github.com/glpi-project/glpi/issues/18925
