### ISSUE TITLE
Planning visualization problems in different domain OUs

### ISSUE THREAD

**Issue by GGodoy21** [glpi-project/glpi#14285]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hello I'm having problems with planning. Currently I have two Active Directory connection setups each with an OU configured. I put the events in the planning and for those in OU 1 they appear normally, but for those in OU 2 everything is transparent

OU1 :
![Design sem nome (1)](https://user-images.githubusercontent.com/114604232/224108112-83951dd2-b985-414a-b51d-3cafdd0b8d9d.png)
OU2:
![Design sem nome](https://user-images.githubusercontent.com/114604232/224108190-ed02a3f0-acc2-4c4e-b5c8-cf0d4556c2b9.png)

### Page URL

http://192.168.0.16/glpi/front/planning.php

**Comment by trasher** [comment]
10.0.3 is outdated, please upgrade and see if you reproduce with latest release

**Comment by trasher** [comment]
No feedback, I close
