### ISSUE TITLE
Problem updating to Nightly build 

### ISSUE THREAD

**Issue by supertramp4** [glpi-project/glpi#14283]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.1.0-dev

### Bug description

I have downloaded the V10.0 Nightly build (10.0-b68e98a.tar.gz), extracted, and trying to upgrade, but the gui complains under setting : 
**Safe configuration of web root directory**
_Web server root directory should be `D:\apache\htdocs\glpi/public` to ensure non-public files cannot be accessed.
Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details._

This however is a SUGGESTED setting, but is blocking me upgrading, and does not allow me to proceed forwards.

How do i fix this. This is purely an internal site, so it doesn't matter, and i already have GLPI_CONFIG_DIR, and GLPI_VAR_DIR configured to be outside the Web Root directory.

**Comment by cedric-anne** [comment]
> This however is a SUGGESTED setting, but is blocking me upgrading, and does not allow me to proceed forwards.

Why is it blocking you?

**Comment by cedric-anne** [comment]
Did you installed GLPI 10.1 then try to install GLPI 10.0 over it?

**Comment by supertramp4** [comment]
I am already on a 10.0 Nightly build ( main-54e3131.tar.gz)  from several months ago, and have been advised to grab the latest nightly build to see if its fixed a different problem. It was suggested to use '10.0', rather than 'Main'
( ticket [https://github.com/glpi-project/glpi-agent/issues/359](url)
Do i need to get the "Main" nightly build ?

**Comment by cedric-anne** [comment]
> You are trying to use GLPI with outdated files compared to the version of the database.

It means that you already installed an higher version, so probably the 10.1.0-dev version.

What is the value in your `glpi_configs` DB table for the `version` config?

**Comment by supertramp4** [comment]
Correct -  version from db reports 
core;version;10.1.0-dev
core;dbversion;10.1.0-dev@50746f183bba9c00749a91407c2d152729d527ea

**Comment by cedric-anne** [comment]
It is not possible to downgrade GLPI database.

**Comment by trasher** [comment]
If you've used main, you're now stucked on main; keep in mind this is a development version.
