### ISSUE TITLE
Error importing and synchronizing users after migrating from version 9.5.7 to 9.5.11

### ISSUE THREAD

**Issue by willdsonalmeida** [glpi-project/glpi#14293]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11

### Bug description

After updating GLPI from version 9.5.7 to 9.5.11 the import and synchronization of users no longer occurs.

I use OpenLDAP in version 2.4.49+dfsg-2ubuntu1.9.

When I try to synchronize using the console, glpi:ldap:synchronize_users returns the number of users less than the original and without a zero mark for updating or importing.

### Relevant log output

```shell
[2023-03-10 17:35:20] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type null in /var/www/html/glpi/inc/authldap.class.php at line 1725
  Backtrace :
  inc/authldap.class.php:1837                        AuthLDAP::searchForUsers()
  inc/authldap.class.php:3937                        AuthLDAP::getAllUsers()
  inc/authldap.class.php:1512                        AuthLDAP::getUsers()
  inc/authldap.class.php:3493                        AuthLDAP::showLdapUsers()
  front/ldap.import.php:66                           AuthLDAP::searchUser()
```

### Your GLPI setup information

 GLPI 9.5.11 ( => /var/www/html/glpi) Installation mode: TARBALL Current language:pt_BR
--

Operating system: Linux SRV-L-VM-STI-GLPI-10-162 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 PHP 8.1.2-1ubuntu2.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, 	bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, 	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Server Software: Ubuntu 22.04 	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpiweb 	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
GLPI 9.5 is no longer maintained

**Comment by TouTUN** [comment]
Hi, i've got exactly teh same issue :(
