### ISSUE TITLE
9.1.1: Problem with $_POST["entity_restrict"] in getDropdownValue.php

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1429]
Dear all,

When using a Dropdown::show() with 'entity' => 0 and 'entity_sons' => true, then the encoded json 'entity_restrict' parameter contains an array with all entity tree, but with strings for the entity values like: 

> `[0,"1525","59","58","1518","1519","1751","1752","181"]`

This will be 'seen' by the getDropdownValue as 

> `[0,\"1525\",\"59\",\"58\",\"1518\",\"1519\",\"1751\",\"1752\",\"181\"]`

due to ` $_POST = array_map(array('Toolbox','addslashes_deep'), $_POST);` line 84 in `includes.php`
and it will not be decoded by the `json_decode` that will returns null.

a json object should not be escaped by addslashes_deep, otherwise we may get undefined results...

thank you
regards,
Tomolimo

**Comment by trasher** [comment]
I do not think we can actually select what to encode and what not to encode... JSON cannot really be identified.

I guess the solution in those cases is actually to stripslashes form the JSON string before doing `json_decode`.
