### ISSUE TITLE
no location field on add user form

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#143]

**Comment by yllen** [comment]
Je ne suis pas d'accord avec la correction.
Tu ne peux pas avoir $entities étant donné que tu n'as pas $ID.
Donc là c'est dropdown:show qui prend l'entité courante quand il ne reçoit pas l'entité.
Donc si tu veux corriger, tu peux à la rigueur le faire au niveau du controle de la multientité, mais il faut remettre tout le début.

**Comment by orthagh** [comment]
dans le cas ou $ID = 0, getUserEntities va renvoyer un tableau vide et donc je force $entities = -1; (le défaut des Dropdown::show)

**Comment by orthagh** [comment]
reverted
