### ISSUE TITLE
Inventories from Agent 1.4 to GLPI 10.0.6 do not work

### ISSUE THREAD

**Issue by dsi-api-rennes** [glpi-project/glpi#14308]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6

### Bug description

Hello
the latest client GLPI Agent 1.4 version 10.3.35 of the MariaDB 
the machines go up well, we can see the agents (last contact well up to date) on the other hand, the inventory lifts are not only done for certain machines.

We have tried to delete the file from the computer and restart the inventory, but we find that the file is not recreated

We stay with a GLPI agent who continues to go up on the other hand but no inventory.

We are in the same situation as this link https://forum.glpi-project.org/viewtopic.php?id=286058+

**Comment by stonebuzz** [comment]
Hi @dsi-api-rennes 

can you retry with GLPI test nighlty build -> https://nightly.glpi-project.org/glpi/

The problem identified here
> https://forum.glpi-project.org/viewtopic.php?id=286058+

is solved
