### ISSUE TITLE
White page when we try to deplace a rule

### ISSUE THREAD

**Issue by EmilieBy** [glpi-project/glpi#14306]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

when we try to deplace a rule with Actions button / Move Befor or After, we have then a white page

http://xxxx/glpi/front/massiveaction.php

the rule is not move.

if we move rule with drag and drop, the position is not kept

### Steps To reproduce

go to the rules
click on one rule
click on Action / move / before

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 (/glpiamenaget => /var/www/html/glpiamenaget)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux app116901l372.cpam-rhone.ramage 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64
PHP 8.1.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring,
	memcache, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, session, shmop, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.34 (Red Hat) PHP/8.1.16 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Server Software: MariaDB Server
	Server Version: 10.5.16-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpiamenaget
	Host info: Localhost via UNIX socket
	
PHP version (8.1.16) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.16) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpiamenaget/files/_cache has been validated.
Write access to /var/www/html/glpiamenaget/config has been validated.
Write access to /var/www/html/glpiamenaget/files/_cron has been validated.
Write access to /var/www/html/glpiamenaget/files has been validated.
Write access to /var/www/html/glpiamenaget/files/_dumps has been validated.
Write access to /var/www/html/glpiamenaget/files/_graphs has been validated.
Write access to /var/www/html/glpiamenaget/files/_lock has been validated.
Write access to /var/www/html/glpiamenaget/files/_pictures has been validated.
Write access to /var/www/html/glpiamenaget/files/_plugins has been validated.
Write access to /var/www/html/glpiamenaget/files/_rss has been validated.
Write access to /var/www/html/glpiamenaget/files/_sessions has been validated.
Write access to /var/www/html/glpiamenaget/files/_tmp has been validated.
Write access to /var/www/html/glpiamenaget/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpiamenaget":
‣ "/var/www/html/glpiamenaget/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpiamenaget/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpiamenaget/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpiamenaget"
GLPI_CONFIG_DIR: "/var/www/html/glpiamenaget/config"
GLPI_VAR_DIR: "/var/www/html/glpiamenaget/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpiamenaget/marketplace"
GLPI_USE_CSRF_CHECK: "0"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpiamenaget/files"
GLPI_CACHE_DIR: "/var/www/html/glpiamenaget/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpiamenaget/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpiamenaget/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpiamenaget/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpiamenaget/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpiamenaget/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpiamenaget/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpiamenaget/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpiamenaget/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpiamenaget/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpiamenaget/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpiamenaget/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpiamenaget/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpiamenaget/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpiamenaget/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpiamenaget/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpiamenaget/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpiamenaget/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpiamenaget/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpiamenaget/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpiamenaget/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpiamenaget/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpiamenaget/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpiamenaget/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpiamenaget/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpiamenaget/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpiamenaget/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpiamenaget/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpiamenaget/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpiamenaget/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpiamenaget/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpiamenaget/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpiamenaget/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpiamenaget/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpiamenaget/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpiamenaget/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpiamenaget/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpiamenaget/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpiamenaget/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpiamenaget/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpiamenaget/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpiamenaget/vendor/psr/cache/src)
league/csv in (/var/www/html/glpiamenaget/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpiamenaget/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpiamenaget/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpiamenaget/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpiamenaget/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpiamenaget/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpiamenaget/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpiamenaget/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpiamenaget/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpiamenaget/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpiamenaget/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpiamenaget/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpiamenaget/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpiamenaget/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'cnamts.local', Port: '389', BaseDN: 'OU=Utilisateurs,OU=116901-CPAM Rhone,OU=Assurance Maladie,DC=cnamts,DC=local',
		Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'C116901-CONSULT_ADN@cnamts.local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
A "white page" means a fatal error. Check your logs and provide relevant entries.

**Comment by EmilieBy** [comment]
with debug I have it
![image](https://user-images.githubusercontent.com/119668416/225326989-d6a119fb-a05f-4a6f-80ae-6e07864df9cd.png)

**Comment by trasher** [comment]
Please provide full entry from logs file.

**Comment by EmilieBy** [comment]
[root@app116901l472 httpd24]# cat error_log
[Sun Mar 19 03:28:01.901715 2023] [http2:warn] [pid 1217] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Mar 19 03:28:01.901738 2023] [http2:warn] [pid 1217] AH02951: mod_ssl does not seem to be enabled
[Sun Mar 19 03:28:01.902363 2023] [lbmethod_heartbeat:notice] [pid 1217] AH02282: No slotmem from mod_heartmonitor
[Sun Mar 19 03:28:01.931804 2023] [mpm_prefork:notice] [pid 1217] AH00163: Apache/2.4.34 (Red Hat) PHP/8.1.16 configured -- resuming normal operations
[Sun Mar 19 03:28:01.931818 2023] [core:notice] [pid 1217] AH00094: Command line: '/opt/rh/httpd24/root/usr/sbin/httpd -D FOREGROUND'

**Comment by EmilieBy** [comment]
[Sun Mar 19 03:28:01.901715 2023] [http2:warn] [pid 1217] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Mar 19 03:28:01.901738 2023] [http2:warn] [pid 1217] AH02951: mod_ssl does not seem to be enabled
[Sun Mar 19 03:28:01.902363 2023] [lbmethod_heartbeat:notice] [pid 1217] AH02282: No slotmem from mod_heartmonitor
[Sun Mar 19 03:28:01.931804 2023] [mpm_prefork:notice] [pid 1217] AH00163: Apache/2.4.34 (Red Hat) PHP/8.1.16 configured -- resuming normal operations
[Sun Mar 19 03:28:01.931818 2023] [core:notice] [pid 1217] AH00094: Command line: '/opt/rh/httpd24/root/usr/sbin/httpd -D FOREGROUND'
[root@app116901l472 httpd24]# ^C
[root@app116901l472 httpd24]# cat error_log-20230319
[Sun Mar 12 03:10:01.836996 2023] [http2:warn] [pid 5324] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Mar 12 03:10:01.837014 2023] [http2:warn] [pid 5324] AH02951: mod_ssl does not seem to be enabled
[Sun Mar 12 03:10:01.837652 2023] [lbmethod_heartbeat:notice] [pid 5324] AH02282: No slotmem from mod_heartmonitor
[Sun Mar 12 03:10:01.872059 2023] [mpm_prefork:notice] [pid 5324] AH00163: Apache/2.4.34 (Red Hat) PHP/8.1.16 configured -- resuming normal operations
[Sun Mar 12 03:10:01.872073 2023] [core:notice] [pid 5324] AH00094: Command line: '/opt/rh/httpd24/root/usr/sbin/httpd -D FOREGROUND'
[Tue Mar 14 10:46:47.157638 2023] [mpm_prefork:notice] [pid 5324] AH00170: caught SIGWINCH, shutting down gracefully
[Tue Mar 14 10:48:40.456634 2023] [suexec:notice] [pid 1217] AH01232: suEXEC mechanism enabled (wrapper: /opt/rh/httpd24/root/usr/sbin/suexec)
[Tue Mar 14 10:48:40.482975 2023] [http2:warn] [pid 1217] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Tue Mar 14 10:48:40.482991 2023] [http2:warn] [pid 1217] AH02951: mod_ssl does not seem to be enabled
[Tue Mar 14 10:48:40.483477 2023] [lbmethod_heartbeat:notice] [pid 1217] AH02282: No slotmem from mod_heartmonitor
[Tue Mar 14 10:48:41.917658 2023] [mpm_prefork:notice] [pid 1217] AH00163: Apache/2.4.34 (Red Hat) PHP/8.1.16 configured -- resuming normal operations
[Tue Mar 14 10:48:41.917695 2023] [core:notice] [pid 1217] AH00094: Command line: '/opt/rh/httpd24/root/usr/sbin/httpd -D FOREGROUND'
[Fri Mar 17 03:24:02.543648 2023] [mpm_prefork:notice] [pid 1217] AH00171: Graceful restart requested, doing restart
[Fri Mar 17 03:24:02.609020 2023] [http2:warn] [pid 1217] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Fri Mar 17 03:24:02.609034 2023] [http2:warn] [pid 1217] AH02951: mod_ssl does not seem to be enabled
[Fri Mar 17 03:24:02.609721 2023] [lbmethod_heartbeat:notice] [pid 1217] AH02282: No slotmem from mod_heartmonitor
[Fri Mar 17 03:24:02.688919 2023] [mpm_prefork:notice] [pid 1217] AH00163: Apache/2.4.34 (Red Hat) PHP/8.1.16 configured -- resuming normal operations
[Fri Mar 17 03:24:02.688932 2023] [core:notice] [pid 1217] AH00094: Command line: '/opt/rh/httpd24/root/usr/sbin/httpd -D FOREGROUND'
[Sun Mar 19 03:28:01.855004 2023] [mpm_prefork:notice] [pid 1217] AH00171: Graceful restart requested, doing restart

**Comment by EmilieBy** [comment]
[Sun Mar 19 03:29:02.984864 2023] [http2:warn] [pid 5644] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Mar 19 03:29:02.984878 2023] [http2:warn] [pid 5644] AH02951: mod_ssl does not seem to be enabled
[Sun Mar 19 03:29:02.994453 2023] [lbmethod_heartbeat:notice] [pid 5644] AH02282: No slotmem from mod_heartmonitor
[Sun Mar 19 03:29:03.164179 2023] [mpm_prefork:notice] [pid 5644] AH00163: Apache/2.4.34 (Red Hat) PHP/8.1.16 configured -- resuming normal operations
[Sun Mar 19 03:29:03.164192 2023] [core:notice] [pid 5644] AH00094: Command line: '/opt/rh/httpd24/root/usr/sbin/httpd -D FOREGROUND'
[Mon Mar 20 08:50:47.057903 2023] [php:warn] [pid 24037] [client 55.137.228.77:61252] PHP Warning:  Undefined array key "id" in /var/www/html/glpiamenaget/src/CommonDBTM.php on line 2011, referer: http://app116901l372/glpiamenaget/front/profile.form.php?id=7
[Mon Mar 20 08:50:51.790418 2023] [php:warn] [pid 24037] [client 55.137.228.77:61252] PHP Warning:  Undefined array key "id" in /var/www/html/glpiamenaget/src/CommonDBTM.php on line 2011, referer: http://app116901l372/glpiamenaget/front/profile.form.php?id=7
[Mon Mar 20 08:51:52.606730 2023] [php:warn] [pid 21456] [client 55.137.228.77:61270] PHP Warning:  Undefined array key "id" in /var/www/html/glpiamenaget/src/CommonDBTM.php on line 2011, referer: http://app116901l372/glpiamenaget/front/profile.form.php?id=7
[Mon Mar 20 10:44:44.609695 2023] [php:warn] [pid 27953] [client 55.137.228.77:51290] PHP Warning:  Undefined array key "rule_class_name" in /var/www/html/glpimvt/src/Rule.php on line 650, referer: http://app116901l372/glpimvt/front/ruleticket.form.php?id=125
[Mon Mar 20 10:44:44.609776 2023] [php:warn] [pid 27953] [client 55.137.228.77:51290] PHP Warning:  Undefined array key "rule_class_name" in /var/www/html/glpimvt/src/Rule.php on line 653, referer: http://app116901l372/glpimvt/front/ruleticket.form.php?id=125

**Comment by cedric-anne** [comment]
Whe need GLPI logs, not apache logs. You can find them in `files/_logs/php-errors.log`.

**Comment by EmilieBy** [comment]
ok excuse me
here php errors.log for today
I reproduce the bug this morning

  
[2023-03-20 09:03:48] glpiphplog.WARNING: Test logger  
[2023-03-20 09:44:44] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "rule_class_name" in /var/www/html/glpimvt/src/Rule.php at line 650
  Backtrace :
  src/MassiveAction.php:908                          Rule::showMassiveActionsSubForm()
  ajax/dropdownMassiveAction.php:53                  MassiveAction->showSubForm()
  
[2023-03-20 09:44:44] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "rule_class_name" in /var/www/html/glpimvt/src/Rule.php at line 653
  Backtrace :
  src/MassiveAction.php:908                          Rule::showMassiveActionsSubForm()
  ajax/dropdownMassiveAction.php:53                  MassiveAction->showSubForm()
  
[2023-03-20 09:44:47] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "Collection" not found in /var/www/html/glpimvt/src/Rule.php at line 690
  Backtrace :
  src/MassiveAction.php:1408                         Rule::processMassiveActionsForOneItemtype()
  src/MassiveAction.php:1386                         MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()

**Comment by cedric-anne** [comment]
Moving rule from the form itself is not really usable as user cannot see list of other rules, so we removed this action from the object form.
