### ISSUE TITLE
php log

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1430]
Hello

I have this error in glpi9.2
2016-12-13 14:29:56 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc\ticket.class.php:229                           
  inc\ticket.class.php:620                           Ticket::canUpdate()
  inc\commonglpi.class.php:203                       Ticket->getTabNameForItem()
  inc\ticket.class.php:703                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:158                       Ticket->defineTabs()
  ajax\updatecurrenttab.php:51                       CommonGLPI->defineAllTabs()

2016-12-13 15:17:05 [903@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_escalade_histories` WHERE tickets_id = : 2016120920 ORDER BY date_mod DESC
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ': 2016120920 ORDER BY date_mod DESC' at line 2
  Backtrace :
  inc\commondbtm.class.php:263                       
  plugins\escalade\inc\history.class.php:51          CommonDBTM->find()
  plugins\escalade\ajax\history.php:10               PluginEscaladeHistory::getHistory()
2016-12-13 15:17:12 [903@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_escalade_histories` WHERE tickets_id = :202016120920 ORDER BY date_mod DESC
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':202016120920 ORDER BY date_mod DESC' at line 2
  Backtrace :
  inc\commondbtm.class.php:263                       
  plugins\escalade\inc\history.class.php:51          CommonDBTM->find()
  plugins\escalade\ajax\history.php:10               PluginEscaladeHistory::getHistory()

**Comment by trasher** [comment]
The SQL error is from a plugin, not from GLPI itself. Please open an issue against the plugin.
