### ISSUE TITLE
LDAP users unable to login after version upgrade

### ISSUE THREAD

**Issue by willdsonalmeida** [glpi-project/glpi#14309]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6 (/glpi => /var/www/html/glpi) Installation mode: TARBALL Current language:pt_BR

### Bug description

I updated from v9.5.11 to 10.0.6, after the update I have a problem with the LDAP users, after entering the login information it goes to glpi/front/login.php and is on an empty screen.
![image](https://user-images.githubusercontent.com/69809203/225445582-836380fd-1d5f-4274-855a-5fb1961f7de2.png)

If I press F5, I get the error "The action you requested is not allowed".

![image](https://user-images.githubusercontent.com/69809203/225441666-45e73ebf-45d6-4b67-b5b3-0d1498e678b1.png)

### Relevant log output

```shell
Logs:

/var/www/html/glpi/files/_log/event.log:
 - Login falhou para <user> no IP <ip>

/var/www/html/glpi/files/_log/php-errors.log:
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: ldap_get_entries(): Argument #2 ($result) must be of type LDAP\Result, bool given in /var/www/html/glpi/src/AuthLDAP.php at line 4235
  Backtrace :
  src/AuthLDAP.php:4235                              ldap_get_entries()
  src/User.php:1760                                  AuthLDAP::get_entries_clean()
  src/AuthLDAP.php:3220                              User->getFromLDAP()
  src/AuthLDAP.php:3304                              AuthLDAP::ldapAuth()
  src/Auth.php:922                                   AuthLDAP::tryLdapAuth()
  front/login.php:89                                 Auth->login()

/var/www/html/glpi/files/_log/access-errors.log:
CSRF check failed for User ID:  at /glpi/front/login.php
```

### Page URL

glpi/front/login.php

### Steps To reproduce

1 - Acesse o IP/glpi
2 - Insira usuário e senha do usuário OpenLDAP
3 - Selecione a base LDAP e Conectar
![image](https://user-images.githubusercontent.com/69809203/225446081-a94bfe67-baec-4d09-9fb7-87617a4b93e6.png)

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.6 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:pt_BR

</details><details><summary>Server</summary><pre> 
Operating system: Linux <hostname> 5.15.0-67-generic #74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpiweb
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details><details><summary>LDAP directories</summary><pre> 
Server: '<ip>', Port: '<port>', BaseDN: '<DN>', Connection filter: none, RootDN:
		'cn=<user_cn>', Use TLS: none
Server: '192.168.XXX.XXX', Port: 'XXX', BaseDN: 'DC=ufmt,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'domais\user_ad',
		Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (suporte.sti@ufmt.br@smtp.gmail.com)

</details><details><summary>Plugins list</summary><pre> 
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

Active Directory  users and local base users log in and are normally directed to /glpi/front/central.php. Only OpenLDAP user have problem.

The problem LDAP users have linked profiles and groups, they accessed normally in version 9.5.11, however I am migrating because I was having problems importing and synchronizing users.

**Comment by TouTUN** [comment]
Hi, I've got the same issue and d'ont find any solution

**Comment by cedric-anne** [comment]
If problem persist, can you apply [this patch](https://github.com/glpi-project/glpi/pull/14356/commits/0ad47491c6a8ae32cbfdb8f17c6d14b430a7cf36), test again, and provide the full stack trace generated in `files/_logs/php-errors.log`?
Without this patch, many ldap errors are not logged, and debugging is pretty hard.

**Comment by cedric-anne** [comment]
Hi,

Could you check to reproduce the issue on GLPI 10.0.7?

**Comment by TouTUN** [comment]
Hi,

I will install the new version and back on you. For the moment i have
disable the software inventory and i don't have any issue.



Le mer. 5 avr. 2023 à 16:41, Cédric Anne ***@***.***> a
écrit :

**Comment by cedric-anne** [comment]
> Hi, I will install the new version and back on you. For the moment i have disable the software inventory and i don't have any issue.

Initial user does not give any feedback, I close the issue as it seems to be fixed for you.

**Comment by TouTUN** [comment]
You can close, i will open a new one if i've got problems with the last
version.

With my solution, i don't have software inventory, which it's not
really good, but i didn't want to back the the 9.5 version, so i was
waiting for the 10.0.7


Le mer. 5 avr. 2023 à 16:49, Cédric Anne ***@***.***> a
écrit :

**Comment by TouTUN** [comment]
HI Cédric,

I'd just update to the version 10.0.7 and it's look good. I have
activate the software inventory and doesn't see any error on duplicate
attributes.

I've got other error on css, but it's doesn't block the utilisation of
glpi, i made a quick search on the forum but don't find any post about it,
il will try later, but if you have an idea to solve it please let me know ;)

Compile css/palettes/auror.scss  ***@***.***"}
[2023-04-07 11:15:59] glpiphplog.DEBUG: Html::compileScss() in
/data/www/glpi/src/Html.php line 6842
Compile css/standalone/gridstack-grids.scss  ***@***.***"}
[2023-04-07 11:16:00] glpiphplog.DEBUG: Html::compileScss() in
/data/www/glpi/src/Html.php line 6842
Compile css/standalone/chartist.scss  ***@***.***"}
[2023-04-07 11:16:00] glpiphplog.DEBUG: Html::compileScss() in
/data/www/glpi/src/Html.php line 6842
Compile marketplace/formcreator/css/styles.scss  ***@***.***"}
[2023-04-07 11:16:01] glpiphplog.DEBUG: Html::compileScss() in
/data/www/glpi/src/Html.php line 6842
Compile css/palettes/auror.scss  ***@***.***"}

Thank you a lot.

Best regards,
Mathieu Tabaka

Le mer. 5 avr. 2023 à 16:49, Cédric Anne ***@***.***> a
écrit :

**Comment by cedric-anne** [comment]
Hi,

These are not errros, but debug messages.

**Comment by TouTUN** [comment]
lol, that's why i don't find post about this error :!

have a nice day

Le ven. 7 avr. 2023 à 11:44, Cédric Anne ***@***.***> a
écrit :
