### ISSUE TITLE
Second rules are not applied 

### ISSUE THREAD

**Issue by Antoine2tt** [glpi-project/glpi#14304]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello ! 

I have two rules for tickets

One to assign a watcher group (Group 1) when a ticket is created FROM EMAIL 
(Rule 1)

Another one is to assign a watcher group (Group 2) when a ticket is created for some entities 
(Rule 2)

The Rule 1 is Working very well, but when i have tickets that match rule 1 and rule 2, at the end, only rule 1 is applied. 

I even use the tool to test rule, i can see that both rules are matching, but only the first one applies (adding group 1, instead of adding both group 1 and group 2) 

Am i missing something with how rules are working ? 

Thanks !

**Comment by EmilieBy** [comment]
if ticket match with many rules, only the last rule is applied
you can test witch rule is applied with rules engine

**Comment by EmilieBy** [comment]
for me no... you must create as many rules as you have cases
