### ISSUE TITLE
Inventory not work (glpi-agent)

### ISSUE THREAD

**Issue by Azgar1998** [glpi-project/glpi#14316]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello,

since the beginning of the week the inventories no longer work.

glpi-agent log:

[Fri Mar 17 10:01:27 2023][error] [http client] communication error: 500 Internal Server Error
[Fri Mar 17 10:01:29 2023][debug] new thread 35 to handle task Collect
[Fri Mar 17 10:01:29 2023][info] running task Collect
[Fri Mar 17 10:01:29 2023][debug2] http://glpi-adress/front/inventory.php?action=getConfig&task[Collect]=2.8&machineid=COMPUTERNAME-2022-10-19-12-14-13
[Fri Mar 17 10:01:29 2023][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Fri Mar 17 10:01:29 2023][info] Collect task not supported by server0
[Fri Mar 17 10:01:31 2023][debug] new thread 36 to handle task RemoteInventory
[Fri Mar 17 10:01:31 2023][info] running task RemoteInventory
[Fri Mar 17 10:01:33 2023][debug] new thread 37 to handle task Deploy
[Fri Mar 17 10:01:33 2023][info] running task Deploy
[Fri Mar 17 10:01:33 2023][debug2] http://glpi-adress/front/inventory.php?action=getConfig&task[Deploy]=2.10&machineid=COMPUTERNAME-2022-10-19-12-14-13
[Fri Mar 17 10:01:33 2023][error] [http client] communication error: 400 Bad Request, Protocol not supported
[Fri Mar 17 10:01:33 2023][info] Deploy task not supported by server0
[Fri Mar 17 10:01:35 2023][info] target server0: next run: Fri Mar 17 13:57:24 2023 - http://glpi-adress/front/inventory.php
[Fri Mar 17 10:01:35 2023][debug] Agent memory usage before freeing memory: WSS=173076480 PFU=190365696
[Fri Mar 17 10:01:35 2023][info] GLPI Agent memory usage: WSS=3252224 PFU=190365696

sql error:

[2023-03-16 18:53:50] glpisqllog.ERROR: DBmysql::query() in glpi-path/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_agents`
  Error: Disk full (/tmp/#sql-temptable-421-bab2-b77a.MAI); waiting for someone to free some space... (errno: 28 "No space left on device")
  Backtrace :
  src/DBmysql.php:889                                
  src/DBmysql.php:1191                               DBmysql->listFields()
  src/CommonDBTM.php:1611                            DBmysql->fieldExists()
  src/Agent.php:463                                  CommonDBTM->update()
  src/Inventory/Inventory.php:229                    Agent->handleAgent()
  src/Inventory/Request.php:309                      Glpi\Inventory\Inventory->contact()
  src/Inventory/Request                               CronTask::launch()

php error:

[2023-03-17 10:06:36] glpiphplog.ERROR:   *** PHP User Error (256): Incorrect integer value: 'Adobe Inc.' for column `glpi`.`glpi_softwares`.`manufacturers_id` at row 1 in glpi-path/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()
  src/Inventory/Asset/Software.php:714               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:443               Glpi\Inventory\Asset\Software->storeSoftware()
  src/Inventory/Asset/MainAsset.php:871              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:791              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1522                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1626                        Rule->process()
  src/Inventory/Asset/MainAsset.php:571              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:706                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()

Thank you for you help

I migrated from version 10.0.3 to 10.0.6 last monday

**Comment by trasher** [comment]
Issue has been reported several times, and is already fixed for next release; try with nightly.

**Comment by Azgar1998** [comment]
While waiting for the next version, I saw that we can replace the glpi-path/src/inventory folder with that of version 10.0.5. You confirm?

**Comment by Azgar1998** [comment]
https://demo.glpi-project.org/viewtopic.php?id=286205

**Comment by cedric-anne** [comment]
> While waiting for the next version, I saw that we can replace the glpi-path/src/inventory folder with that of version 10.0.5. You confirm?

No, replacing some files is never an option, as most of the time it will result in having partial patches that is often more harmfull than the bug itself (it often conduct to fatal error).

**Comment by Azgar1998** [comment]
do you have any other temporary solution that won't be too harmful?

**Comment by cedric-anne** [comment]
If you accept to install a nightly build on your server, you can get it from https://nightly.glpi-project.org/glpi/10.0.tar.gz

**Comment by Azgar1998** [comment]
When are you going to release the final fix?

**Comment by cedric-anne** [comment]
See https://github.com/glpi-project/glpi/milestones

![image](https://user-images.githubusercontent.com/33253653/225888893-1f3cab01-3ce5-47ae-8854-f89967ce4046.png)
