### ISSUE TITLE
Problem, always get "Empty username or password"

### ISSUE THREAD

**Issue by blandygbc** [glpi-project/glpi#14313]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.4

### Bug description

Hi guys.

I have the same problem reported for @jswytka issue [#4145](https://github.com/glpi-project/glpi/issues/4145) however in version 10.0.4.
PHP: 8.1.2
Ubuntu server: 22.04
I'm using Microsoft Edge  111.0.1661.41.

I was using it normally, but when I logged in yesterday, I got redirected to /front/login.php with the message "Empty login or password".

### Steps To reproduce

1. Login with the saved username and password (When you first start the browser) at /index.php.
2. I got redirected to /front/login.php
![login_error](https://user-images.githubusercontent.com/85970505/225657211-34896dd4-5a8e-44c1-9a5e-cd1593a171d1.png)
3. When I click on the button redirects me to /index.php?noAUTO=1
4. From now on I try to log in and got stuck in this loop.

I did a test using chrome and I could log in, then I logged out and accessed /front/login.php directly and clicked on the button again to test. I got redirected to /index.php?noAUTO=1 and chrome stopped working like Edge.

Then I tried to access using Firefox and it is working, but I will not try again to not lose my access totally.

**Comment by blandygbc** [comment]
I've upgraded and the problem persists

GLPI 10.0.6 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:pt_BR

**Comment by blandygbc** [comment]
At the time I'm the only one having this issue.
The web server have access to the folder. My Firefox session still works.
I've already tried to clear the browser cache, but no success.

**Comment by blandygbc** [comment]
I've accidentally touched on close trying to comment on my phone.

**Comment by blandygbc** [comment]
> At the time I'm the only one having this issue. The web server have access to the folder. My Firefox session still works. I've already tried to clear the browser cache, but no success.

**Comment by blandygbc** [comment]
I've looked at the login.php file and saw that it checks if the login and password are set from session or post but if it fails sets log in to be empty. It seems to be failing to get or set that information on redirect and always set the login empty.

![image](https://user-images.githubusercontent.com/85970505/225971634-03ed80f3-a787-4b04-ad33-802aefc68715.png)

**Comment by cedric-anne** [comment]
Have you some plugins installed?

**Comment by blandygbc** [comment]
> Can you reproduce the issue on a private browsing session ?

Worked! I can log in in a private session.

**Comment by blandygbc** [comment]
I tried to reproduce the problem and the login worked normally in a private session.

**Comment by blandygbc** [comment]
Do you think it could be a corrupted session file in session folder?

**Comment by boscorelly** [comment]
Hi,
i have the same issue with 10.0.0.6.
I tried in private browsing (edge incognito), and it doesn't work, keep saying user or password empy.
