### ISSUE TITLE
Can't see sub entities of an entity on search in the Select the desired entity popup

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#14317]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,
When performing an entity search using the ajax search from the entity selection pop-up.
If the search does return the parent entity, but it does not match any of the sub-entities of the parent entity in question, then the sub-entities are hidden.
We cannot therefore see the list of sub-entities in the tree structure of a parent entity during a search.
Thanks

### Steps To reproduce

Let's say that we have those entities
v PARENT ENTITY
   |_ CHILD 1
   |_ CHILD ENTITY

1. Click on Root entity
2. In the pop-up "Select the desired entity" Perform a search on "PARENT"
3. Result : you'll see only "PARENT ENTITY" but no sub entities
4. Perform a search on "ENTITY"
5. Result : you'll see "PARENT ENTITY" and "CHILD ENTITY" but not "CHILD 1"

Expected result : We must see the sub-entity of a parent entity in the tree in any case.
(but sub entity could have the matched search word put in bold if any ?)

### Your GLPI setup information

Operating system: Linux  3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023
	x86_64
PHP 7.4.33 litespeed (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap, libxml, litespeed, mbstring,
	memcached, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, shmop, soap, sockets,
	sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, timezonedb, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: LiteSpeed
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0
Server Software: MariaDB Server
	Server Version: 10.3.38-MariaDB-log
	Server SQL Mode: ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: 
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.PHP version (7.4.33) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.38) is supported.Database engine version (10.3.38) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.

### Anything else?

That was not the case on the V9.5.5

**Comment by cedric-anne** [comment]
Hi,

#14372 will fix this issue.

**Comment by M-Falken** [comment]
@cedric-anne Thanks a lot
