### ISSUE TITLE
PHP error when update SLA : add a calendar with massive action

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#1431]
I'm running GLPI 0.90.5
I get a PHP error when I update the calendar of an SLA with massive action.
I get an error only via massive action. I don't get the error if I modify the calendar within the SLA screen.

  *** PHP Notice(8): Undefined index: definition_time
  Backtrace :
  inc/sla.class.php:501
  inc/commondbtm.class.php:1038                      SLA->prepareInputForUpdate()
  inc/massiveaction.class.php:1186                   CommonDBTM->update()
  inc/massiveaction.class.php:991                    MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:64                         MassiveAction->process()

**Comment by trasher** [comment]
0.90 is EOL from a while; and SLA has changed a lot in latests releases.
