### ISSUE TITLE
no inventories since Update 10.0.3 > 10.0.6

### ISSUE THREAD

**Issue by CGDV-Sophie** [glpi-project/glpi#14329]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Good morning,

I tried to update GLPI 10.0.3 to 10.0.6 and the inventory system no longer works.

I have access to the pages but when I run an inventory on the machines I have : 

```
[Mon Mar 20 11:04:32 2023][error] [http client] communication error: 500 Internal Server Error
[Mon Mar 20 11:04:33 2023][info] running task Deploy
[Mon Mar 20 11:04:33 2023][error] [http client] communication error: 400 Bad Request
[Mon Mar 20 11:04:33 2023][info] Deploy task not supported by server0
[Mon Mar 20 11:04:36 2023][info] running task Collect
[Mon Mar 20 11:04:36 2023][error] [http client] communication error: 400 Bad Request
[Mon Mar 20 11:04:36 2023][info] Collect task not supported by server0
[Mon Mar 20 11:04:38 2023][info] target server0: next run: Tue Mar 21 10:25:42 2023 - http://xxxxx/glpi10/front/inventory.php
[Mon Mar 20 11:04:38 2023][info] GLPI Agent memory usage: WSS=3366912 PFU=159170560
```

P.S. Acces to `http://xxxx/glpi10/marketplace/glpiinventory/front/menu.php` is ok
acces to `http://xxxx/glpi10/front/inventory.php` send error 405
No error in error.log apache

Thank for help.

### Steps To reproduce

save GLPI 10.0.3 DB
save GLPI 10.0.3 rep
clean GLPI 10.0.3 rep
DL GLPI 10.0.6
unzip GLPI 10.0.6 
copy config/glpicrypt.key save to /glpi/
use php bin/console db:update

### Your GLPI setup information

GLPI 10.0.6 (/glpi10 => /var/www/html/glpi10)
Installation mode: TARBALL
Current language:fr_FR

**Comment by CGDV-Sophie** [comment]
error.log ?

```
[Mon Mar 20 11:30:59.486518 2023] [proxy_fcgi:error] [pid 73388] [client 10.228.34.3:6054] AH01071: Got error 'PHP message: PHP Warning:  error_log(/var/www/html/glpi10/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi10/src/Toolbox.php on line 599', referer: http://10.228.35.29/glpi10/front/marketplace.php
[Mon Mar 20 11:47:57.752606 2023] [proxy_fcgi:error] [pid 85862] [client 10.228.34.3:7922] AH01071: Got error 'PHP message: PHP Warning:  error_log(/var/www/html/glpi10/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi10/src/Toolbox.php on line 599', referer: http://10.228.35.29/glpi10/front/config.form.php
[Mon Mar 20 12:17:30.287703 2023] [proxy_fcgi:error] [pid 84852] [client 10.228.35.69:56164] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1377PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Fatal error:  Duplicate entry 'Computer-52-3211' for key 'unicity' in /var/www/html/glpi10/src/DBmysql.php on line 1969'
[Mon Mar 20 12:17:35.990491 2023] [proxy_fcgi:error] [pid 85408] [client 10.228.34.3:11245] AH01071: Got error 'PHP message: PHP Notice:  Undefined index: ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1377PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Warning:  error_log(/var/www/html/glpi10/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi10/src/Toolbox.php on line 599PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Notice:  Undefined index: plugin_ocsinventoryng_ocsservers_id in /var/www/html/glpi10/marketplace/ocsinventoryng/hook.php on line 1379PHP message: PHP Fatal error:  Duplicate entry 'Computer-1-3210' for key 'unicity' in /var/www/html/glpi10/src/DBmysql.php on line 1969'
[Mon Mar 20 12:17:47.636509 2023] [proxy_fcgi:error] [pid 85875] [client 10.228.34.3:11278] AH01071: Got error 'PHP message: PHP Warning:  error_log(/var/www/html/glpi10/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi10/src/Toolbox.php on line 599', referer: http://10.228.35.29/glpi10/front/central.php
```

**Comment by cedric-anne** [comment]
Logs indicates that you have permission issues on your GLPI files. You should fix them (webserver user have to be able to write in your GLPI `files/*` directories), and try again.

**Comment by CGDV-Sophie** [comment]
Thank you for that answer.

I checked and I have the following attributes:

`-rwxrwxr-x  1 www-data www-data     1634 janv. 24 12:34 apirest.php
-rwxrwxr-x  1 www-data www-data     1601 janv. 24 12:34 apixmlrpc.php
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:34 bin
-rwxrwxr-x  1 www-data www-data     1500 janv. 24 12:34 caldav.php
-rwxrwxr-x  1 www-data www-data    41546 janv. 24 12:34 CHANGELOG.md
drwxrwxr-x  2 www-data www-data     4096 mars  20 11:48 config
-rwxrwxr-x  1 www-data www-data     2060 janv. 24 12:34 CONTRIBUTING.md
drwxrwxr-x  7 www-data www-data     4096 janv. 24 12:34 css
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:38 css_compiled
drwxrwxr-x 18 www-data www-data     4096 mars  20 12:28 files
drwxrwxr-x  4 www-data www-data    36864 janv. 24 12:34 front
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:34 inc
-rwxrwxr-x  1 www-data www-data     6255 janv. 24 12:34 index.php
drwxrwxr-x  4 www-data www-data     4096 janv. 24 12:34 install
-rwxrwxr-x  1 www-data www-data      682 janv. 24 12:34 INSTALL.md
drwxrwxr-x  5 www-data www-data     4096 janv. 24 12:34 js
drwxrwxr-x  3 www-data www-data     4096 janv. 24 12:34 lib
-rwxrwxr-x  1 www-data www-data    35148 janv. 24 12:34 LICENSE
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:38 locales
drwxrwxr-x  6 www-data www-data     4096 mars  20 11:48 marketplace
drwxrwxr-x 10 www-data www-data     4096 janv. 24 12:34 pics
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:38 plugins
drwxrwxr-x  3 www-data www-data     4096 janv. 24 12:34 public
-rwxrwxr-x  1 www-data www-data     6029 janv. 24 12:34 README.md
drwxrwxr-x  3 www-data www-data     4096 janv. 24 12:34 resources
-rwxrwxr-x  1 www-data www-data     1067 janv. 24 12:34 SECURITY.md
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:34 sound
drwxrwxr-x 24 www-data www-data    32768 janv. 24 12:34 src
-rwxrwxr-x  1 www-data www-data     2516 janv. 24 12:34 status.php
-rwxrwxr-x  1 www-data www-data      481 janv. 24 12:34 SUPPORT.md
drwxrwxr-x  8 www-data www-data     4096 janv. 24 12:34 templates
drwxrwxr-x 37 www-data www-data     4096 janv. 24 12:38 vendor
drwxrwxr-x  2 www-data www-data     4096 janv. 24 12:34 version
`
and 

`root@SVD9-GLPI:/var/www/html/glpi10/files# ls -la
total 112
drwxrwxr-x 18 www-data www-data  4096 mars  20 12:28 .
drwxrwxr-x 25 www-data www-data  4096 mars  20 10:45 ..
drwxrwxr-x  8 www-data www-data  4096 mars  20 12:28 _cache
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _cron
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _dumps
drwxrwxr-x  2 www-data www-data  4096 mars  20 11:48 _graphs
-rwxrwxr-x  1 www-data www-data   114 mars  20 12:28 .htaccess
drwxrwxr-x  3 www-data www-data  4096 mars  20 12:38 _inventories
drwxrwxr-x  3 www-data www-data  4096 mars  20 12:28 _locales
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _lock
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _log
drwxrwxr-x  3 www-data www-data  4096 mars  20 12:28 PDF
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _pictures
drwxrwxr-x  4 www-data www-data  4096 mars  20 12:28 _plugins
drwxrwxr-x  3 www-data www-data  4096 mars  20 12:28 PNG
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _rss
drwxrwxr-x  2 www-data www-data 36864 mars  20 12:57 _sessions
drwxrwxr-x  2 www-data www-data  4096 mars  20 11:48 _tmp
drwxrwxr-x  2 www-data www-data  4096 mars  20 12:28 _uploads
`
It's not good ?

**Comment by cedric-anne** [comment]
It is hard to read and it depends on your system. If `www-data` is your webserver user, try to execute `chown -r www-data:www-data /var/www/html/glpi10`.

**Comment by cedric-anne** [comment]
These errors are related to inventory endpoint, so they are probably related to your issue.

**Comment by CGDV-Sophie** [comment]
What can I try?

(To test I reinstalled 10.0.6 in /glpi10v2/ with a blank db and I installed GLPI Inventory, and it works, the test machine goes up.

the problem only occurs on the attempt to upgrade from 10.0.3 to 10.0.6)

**Comment by trasher** [comment]
This issue should have already been fixed. Try with 10.0 nightly build
