### ISSUE TITLE
Test Rule to add users on ticket doesn't work

### ISSUE THREAD

**Issue by EmilieBy** [glpi-project/glpi#14327]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,

I create a rule to assign 3 differents groups of users when a new ticket is created.
Only the first group is assigned!

Rule doesn't work when we use Add

![image](https://user-images.githubusercontent.com/119668416/226285840-be545215-65fe-4957-8711-6aadb370d6a9.png)

![image](https://user-images.githubusercontent.com/119668416/226285939-079dd0b3-9546-4cdd-9964-dd6dcdd15153.png)

![image](https://user-images.githubusercontent.com/119668416/226286043-a9dfcaeb-a5b5-4628-9172-731ff8423b25.png)

### Steps To reproduce

create a rule to manage ticket
on actions, add an action which assign a group of technicians
add an other action which add a group of technicans
test the rule

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 (/glpimvt => /var/www/html/glpimvt)
Installation mode: TARBALL
Current language:fr_FR

</details><details><summary>Server</summary><pre> 
Operating system: Linux app116901l372.cpam-rhone.ramage 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64
PHP 8.1.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring,
	memcache, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, session, shmop, sockets, sodium,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.34 (Red Hat) PHP/8.1.16 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0
Server Software: MariaDB Server
	Server Version: 10.5.16-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpimvt
	Host info: Localhost via UNIX socket
	
PHP version (8.1.16) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.16) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpimvt/files/_cache has been validated.
Write access to /var/www/html/glpimvt/config has been validated.
Write access to /var/www/html/glpimvt/files/_cron has been validated.
Write access to /var/www/html/glpimvt/files has been validated.
Write access to /var/www/html/glpimvt/files/_dumps has been validated.
Write access to /var/www/html/glpimvt/files/_graphs has been validated.
Write access to /var/www/html/glpimvt/files/_lock has been validated.
Write access to /var/www/html/glpimvt/files/_pictures has been validated.
Write access to /var/www/html/glpimvt/files/_plugins has been validated.
Write access to /var/www/html/glpimvt/files/_rss has been validated.
Write access to /var/www/html/glpimvt/files/_sessions has been validated.
Write access to /var/www/html/glpimvt/files/_tmp has been validated.
Write access to /var/www/html/glpimvt/files/_uploads has been validated.
The following directories should be placed outside "/var/www/html/glpimvt":
‣ "/var/www/html/glpimvt/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpimvt/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
For security reasons, SELinux mode should be Enforcing.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpimvt/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpimvt"
GLPI_CONFIG_DIR: "/var/www/html/glpimvt/config"
GLPI_VAR_DIR: "/var/www/html/glpimvt/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpimvt/marketplace"
GLPI_USE_CSRF_CHECK: "0"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpimvt/files"
GLPI_CACHE_DIR: "/var/www/html/glpimvt/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpimvt/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpimvt/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpimvt/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpimvt/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpimvt/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpimvt/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpimvt/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpimvt/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpimvt/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpimvt/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpimvt/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpimvt/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpimvt/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpimvt/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpimvt/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/var/www/html/glpimvt/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpimvt/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpimvt/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpimvt/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpimvt/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpimvt/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpimvt/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpimvt/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpimvt/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpimvt/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpimvt/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpimvt/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpimvt/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpimvt/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpimvt/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpimvt/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpimvt/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpimvt/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpimvt/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpimvt/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpimvt/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpimvt/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpimvt/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpimvt/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpimvt/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpimvt/vendor/psr/cache/src)
league/csv in (/var/www/html/glpimvt/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpimvt/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpimvt/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpimvt/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpimvt/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpimvt/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpimvt/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpimvt/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpimvt/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpimvt/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpimvt/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpimvt/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpimvt/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpimvt/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'cnamts.local', Port: '389', BaseDN: 'OU=Utilisateurs,OU=116901-CPAM Rhone,OU=Assurance Maladie,DC=cnamts,DC=local',
		Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'C116901-CONSULT_ADN@cnamts.local', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp.ramage)

</details><details><summary>Plugins list</summary><pre> 
	behaviors            Name: Comportements                  Version: 2.6.0      State: Not installed                           
		Install Method: Manual
	escalade             Name: Escalades                      Version: 2.8.1      State: Installed / not activated               
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

- `assign` action (Assigner) means that already assigned technicians are replaced by the new assigned one.
- `add` action (Ajouter) means that technician is appended to the list of assigned technicians.

Can you try to use `add` action for all of your actions and see if problem remains?

**Comment by EmilieBy** [comment]
Hi,
I understand how it works but add action doesn't work for me.

I create a new rule for test and just use add action
no group is assigned

![image](https://user-images.githubusercontent.com/119668416/226914952-300cfd81-ba2f-4942-9a1a-5caba734a428.png)

![image](https://user-images.githubusercontent.com/119668416/226915103-d6ea8987-c2b7-45f6-9125-5bc51a51ab00.png)

I have made many tests, but it doesn't work

**Comment by EmilieBy** [comment]
If I test this rule with tester, resultats are wrong
But if I use this on tickets, my group is well added 

I think the problem is just on rules tester

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue. Rule is working as expected, but displayed result in test feature does not match actual result.
