### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#1433]
Detected by debian, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=846067

ASL-2.0 is not compatible with GPL v2 used by GLPI
See https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#SoftwareLicenses

Affected 3rd party component:
- vendor/zetacomponents/*
- vendor/jasig/phpcas

Notice
- lib/jqueryplugins/select2 is both ASL-2.0 and GPL-v2.0 (not later), so is OK.

**Comment by remicollet** [comment]
BTW GLPI is "GLPI v2+ (version 2 of the License, or (at your option) any later version", so perhaps GPL v3 is implied here, but GPLv3 doesn't allow GPL v2 code (https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#GPL_Compatibility_Matrix)

**Comment by remicollet** [comment]
IMHO, we should find a replacement for zeta components which seems to be a dead project (in the apache project graveyard)

**Comment by orthagh** [comment]
yes, i think the same.
- In Zeta componements, we are using only graph part. It should be easy to replace it.
- for phpcas, it will be difficult. I don't know any replacements (maybe tillikum/zf2-cas-authentication-adapter).
- same for select2. 3.5 branch begin to be old (no commits since one year) but replacing this lib will be a breaking change.

**Comment by trasher** [comment]
If the project is dead, we'd better find an alternative, yes. As for phpcas, I take a quick look and did not find any alternative yet unfortunately :/

**Comment by wawax** [comment]
And this post was in 2014 : http://forum.glpi-project.org/viewtopic.php?id=36902 ...

**Comment by trasher** [comment]
I've worked on the charts stuff; this is almost done:
https://github.com/glpi-project/glpi/compare/master...trasher:feature/js-charts

It relies on the "on demand js" feature that should be finished/reintegrated first; but that only affects the way scripts are loaded, not the changes themselves

**Comment by trasher** [comment]
Unfortunately... We've not yet been able to find a suitable replacement for PHPCAS library :(
