### ISSUE TITLE
Order by Name or by column in Virtual Machines list

### ISSUE THREAD

**Issue by gitdevmod** [glpi-project/glpi#1434]
Hi,

List of virtual machines is not sorted by name but by import date. Is this possible to sort by name and/or order by column (OS, state, memory, etc.) ?

GLPI version 9.1.1

Thanks in advance

**Comment by gitdevmod** [comment]
I created a PR #1437 to order at least by name

**Comment by orthagh** [comment]
Merged. Thank you for your contribution
