### ISSUE TITLE
[GLPI 9.1.X] Query glpi_logs for solution data

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1435]
https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L6173

GLPI send query to glpi_logs for search technician which have resolve the ticket

```
SELECT `date_mod` AS solution_date, `user_name`, `id`
                                         FROM `glpi_logs`
                                         WHERE `itemtype` = 'Ticket'
                                               AND `items_id` = ".$this->getID()."
                                               AND `id_search_option` = 24
                                         ORDER BY `id` DESC
                                         LIMIT 1
```

Not really efficient ?

Add 	users_id_solve field into glpi_tickets ?

**Comment by pVesian** [comment]
Hi, is there any news on this? Logs get really big over time and they tend to get purged.

**Comment by pVesian** [comment]
Also, as long as this isn't fixed, it would be good not to [hardcode the id_search_option 24 in a query](https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L6071), it could maybe use a constant.

**Comment by trasher** [comment]
Querying logs to get solution details is not a good way to go. But adding a new field won't be enough; existing solutions system need to be reworked (see  #2089)
