### ISSUE TITLE
[Rest API GLPI 10.0.6] ERROR_GLPI_ADD on assigning a group to a ticket

### ISSUE THREAD

**Issue by alexis-thavisouk** [glpi-project/glpi#14357]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello,

I have migrate my glpi v9.5 to v10.0.6.

But i have an issue to assign a group to a ticket (haven't any issue on 9.5)

I use a super admin account and when i use this endpoint :

https://NAME/apirest.php/Group_Ticket?session_token=yourToken

`body:
{
    "input": {
        "tickets_id": 1062,
        "group_id": 18,
        "type": "2"
    }
}`

I got an error with ERROR_GLPI_ADD,

Is someone having the same issue or maybe group assignement has changed?

For informations:
- Assigning a user to ticket works with https://NAME/apirest.php/Ticket_User?session_token=yourToken
- If i assign group to a ticket in the glpi interface there is no problem with the same super admin account 

### Relevant log output

```shell
[
    "ERROR_GLPI_ADD",
    "Vous n'avez pas les droits requis pour réaliser cette action."
]
```

### Steps To reproduce

1 - Get session token of your super admin account
2 - Try to execute with Postman https://localhost/apirest.php/Group_Ticket?session_token=yourToken
with a body like this :
`{
    "input": {
        "tickets_id": 1062,
        "group_id": 18,
        "type": "2"
    }
}`

**Comment by cconard96** [comment]
The field should be "groups_id" not "group_id".
