### ISSUE TITLE
/front/networkport.php Not Found The requested URL was not found on this server.

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#14353]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When creating a socket in: /front/socket.form.php Then selecting a Network ports, and clicking the "i", it open an URL: /front/networkport.php but this page is not in GLPI directory

![image](https://user-images.githubusercontent.com/56606032/226740282-a81870e4-388f-4e41-b5c7-e2b33663bcf7.png)

![image](https://user-images.githubusercontent.com/56606032/226741856-f056b925-dfa8-406a-8238-490aeac172b6.png)

### Page URL

/front/networkport.php

**Comment by trasher** [comment]
Please try if you still reproduce with latest nightly

**Comment by jcervantes-sipecom** [comment]
Hi, I did a git clone from:

![image](https://user-images.githubusercontent.com/56606032/226973758-20d40fd2-e585-40e2-afd1-b5bea8cb30e5.png)

But the issue is still there:

- In cable/socket: /front/socket.form.php
- In network port, I selected Network Device:
- Clic on "i"
- It open the URL: /front/networkport.php
- Error: Not Found The requested URL was not found on this server.

![image](https://user-images.githubusercontent.com/56606032/226973940-5e3dfebd-1eba-43b3-8b06-f111bbf99841.png)

![image](https://user-images.githubusercontent.com/56606032/226974268-dce064ad-f6a3-44c5-8e35-5f9e9c27b3bb.png)

**Comment by stonebuzz** [comment]
Hi @jcervantes-sipecom 

Can you try this -> https://github.com/glpi-project/glpi/pull/14368

Best regards

**Comment by cedric-anne** [comment]
I maked this as `wontfix` as we cannot display NetworkPort list for now. It requires too much work and may probably not worth it.
