### ISSUE TITLE
GLPI does not retrieve xml information from my SNMP inventory task

### ISSUE THREAD

**Issue by Oragonnn** [glpi-project/glpi#14370]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

When I run my SNMP inventory task, all the information goes up but remains blocked in the xml file.
the only exception is my printer where I have everything going back.

Link to a xml file.
https://pastebin.com/C7ERivZ2

### Your GLPI setup information

GLPI 10.0.5 ( => /srv/srv01/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cedric-anne** [comment]
Hi,

Could you try with [GLPI nightly](https://nightly.glpi-project.org/glpi/10.0.tar.gz) build to see if problem persist? Many bugs have been solved since GLPI 10.0.5.

**Comment by g-bougard** [comment]
Hi @Oragonnn
that XML is for a D-Link DXS-1210-12TC switch and the agent doesn't find the serialnumber for that device.
That device should be imported in unmanaged. You can try to enable update & import rules by mac address, but this may involve unexpected side-effects.
If you can create and provide a [snmpwalk output following the documentation](https://glpi-agent.readthedocs.io/en/latest/bug-reporting.html#snmpwalk-output), you should open an [issue on glpi-agent project](https://github.com/glpi-project/glpi-agent/issues) and we will see if we can improve glpi-agent.

**Comment by Oragonnn** [comment]
@g-bougard Thanks for answering, the update and import rule for mac address is already enabled because none of my network equipment is imported if they are not active.
I will try the nightly version of glpi as @cedric-anne says it to see if it solves my problem
