### ISSUE TITLE
Inconsistent ticket creation methods

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1438]
When creating a ticket as an admin, we use `front/ticket.form.php` and call:
```
$track->check(-1, CREATE, $_POST);
$track->add($_POST));
```

When creating a ticket form the self-service profile, we use `front/tracking.injector.php` but there is no `check()` call in that one; that make use of `pre_item_add` hook (at least) inconsistent.

Anyways, I guess we should call `check()` in both cases.

**Comment by orthagh** [comment]
merged
