### ISSUE TITLE
Change Profile

### ISSUE THREAD

**Issue by ts2050** [glpi-project/glpi#14389]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6 ( => /var/www/glpi)

### Bug description

Context:
The attendant has two profiles, service and ticket opening, the first allows access only to the entity of his department, the second profile allows a view of the root, since it is a profile for the requester.

Problem:
The attendant's default profile should be customer service, as this is what they use the most, so we've included it as a default profile. However, when changing to the ticket opening profile, instead of also modifying the root entity of this profile, it changes to the inheritance entity of the service profile.

### Your GLPI setup information

GLPI 10.0.6 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:pt_BR

**Comment by cconard96** [comment]
Is the ticket opening profile assigned recursively on the root entity (so it has access to all entities)? If so, the behavior seems expected.
If you are unsure, you can go to the Users tab of the profile and see if there is a `(R)` next to the user's name under the Root Entity. If so, they have access to all entities with that profile.

**Comment by ts2050** [comment]
Firstly, thank you for your prompt response.

Yes, it's working recursively.

Here's a more organized and error-free version of your text:

When the user accesses the system, the default profile is set as "attendant", which is configured in their entity.
When they change to the "ticket opening" entity, the expected behavior would be to switch to the "ticket opening" profile and also to the "root" entity.
However, when they change the entity, it inherits the entity from the previous profile. The entity should also change to the root entity configured in this "ticket opening" profile.
Note: For example, if I change the default entity to "ticket opening", then every time I log into the system, that is the default entity. When I change to the "support" entity, it should modify to the entity configured in this profile, regardless of the previous profile entity. The problem with this is that the attendant will have to change the entity every time they access the system. In our context, we have a shared service center, meaning that there are several attendants from various business departments. These are the reasons for these observations.

I apologize if it's not very clear, I can try to provide more context if needed.

![Uploading Captura de tela de 2023-03-25 12-29-15.png…]()

**Comment by ts2050** [comment]
After conducting tests, I found a way to work around the issue described above. When registering an attendant, it is recommended to leave the default entity as "root" or higher. This is because if there are two profiles, one for a specific entity and another with a higher entity, changing the entity will allow you to switch to the root of the profile that is defined.

thanks @cconard96
