### ISSUE TITLE
When adding a sim card item if forgets to select a component the data is not saved

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#14399]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When adding a sim card item if forgets to select a component the data is not saved after pressing add and goes to /dev/null.

There is no information that it was not saved - if selecting the simcard component is to be mandatory it should not allow you to leave the form without selecting the component.

### Page URL

http://server/glpi/front/item_devicesimcard.form.php

### Steps To reproduce

1. open add sim card
2. add serial and inventory number
3. click add button

**Comment by Wolvverine** [comment]
And another problem: if I link simmcard item to phone - do not have possibility tu save tab with data about simm card - button "save" not exist, only "remove permanently" button is vissible.

**Comment by stonebuzz** [comment]
Adding a sim card without component is not possible with 10.0.6 (nightly build)

![image](https://user-images.githubusercontent.com/7335054/228144023-804d92ac-e679-435e-85c2-25d6aded31ee.png)

> do not have possibility tu save tab with data about simm card - button "save" not exist, only "remove permanently" button is vissible.

I do not reproduce

![image](https://user-images.githubusercontent.com/7335054/228144600-3b921703-b65c-4f3d-a451-81a26afe4c4a.png)


Can you retry with nightly build -> https://nightly.glpi-project.org/glpi/

**Comment by trasher** [comment]
No feedback, I close

**Comment by Wolvverine** [comment]
On 10.0.6 is ok with sim card type but is other big problem :
https://github.com/glpi-project/glpi/issues/14968
