### ISSUE TITLE
Issue with Follow-Up Notifications Sending Duplicates to User

### ISSUE THREAD

**Issue by ts2050** [glpi-project/glpi#14391]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.6 ( => /var/www/glpi)

### Bug description

When the user replies to a notification email or adds a follow-up to the ticket, that same follow-up is sent back to them. The expected behavior should be that they do not receive the messages they send themselves.

**Comment by cedric-anne** [comment]
Hi,

This behaviour can be controlled by the `Notifications for my changes` preference:
![image](https://user-images.githubusercontent.com/33253653/227860779-17538c12-7147-41bf-8776-56cf7bcc8d0b.png)

What is the selected value for your user?

**Comment by cedric-anne** [comment]
No feedback, I close.

**Comment by gonzaleztroyano** [comment]
Same as #16813.

@ts2050, did you manage to solve the issue?
