### ISSUE TITLE
Plugin installation fails

### ISSUE THREAD

**Issue by TheRich-71** [glpi-project/glpi#14394]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

I did a fresh install of glpi on a Synology NAS, and it seems to be okay so far. Only issue I currently see is with installing Plugins through marketplace, they end silently with a small message "Plugin archive format is not supported by your system: tbz2. ". I am puzzled, since PHP bz2 support is installed, so how could I solve this issue? The log file does not give anything which I can link to the error, see below everything it logged this morning...

### Relevant log output

```shell
[2023-03-27 08:20:43] glpiphplog.WARNING:   *** PHP Warning (2): Cannot modify header information - headers already sent by (output started at /volume1/web/glpi/src/Html.php:2168) in /volume1/web/glpi/src/Marketplace/View.php at line 291
  Backtrace :
  src/Marketplace/View.php:291                       header()
  src/Marketplace/View.php:126                       Glpi\Marketplace\View::discover()
  src/CommonGLPI.php:689                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  
[2023-03-27 08:24:56] glpiphplog.WARNING: Test logger  
[2023-03-27 08:25:02] glpiphplog.WARNING: Test logger  
[2023-03-27 08:26:05] glpiphplog.WARNING: Test logger  
[2023-03-27 08:27:11] glpiphplog.WARNING: Test logger
```

### Steps To reproduce

Pick a plugin from marketplace (I wanted glpi-inventory, but tried others as well) and click on download

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.6 ( => /volume1/web/glpi)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux eln 3.10.108 #42962 SMP Tue Oct 18 15:01:39 CST 2022 x86_64
PHP 8.0.23 fpm-fcgi (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, readline, session,
	sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="240" memory_limit="128M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache/2.4.54 (Unix) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Server Software: Source distribution
	Server Version: 10.3.32-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.0.23) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.32) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /volume1/web/glpi_safe/files/_cache has been validated.
Write access to /volume1/web/glpi_safe/config has been validated.
Write access to /volume1/web/glpi_safe/files/_cron has been validated.
Write access to /volume1/web/glpi_safe/files has been validated.
Write access to /volume1/web/glpi_safe/files/_dumps has been validated.
Write access to /volume1/web/glpi_safe/files/_graphs has been validated.
Write access to /volume1/web/glpi_safe/files/_lock has been validated.
Write access to /volume1/web/glpi_safe/files/_pictures has been validated.
Write access to /volume1/web/glpi_safe/files/_plugins has been validated.
Write access to /volume1/web/glpi_safe/files/_rss has been validated.
Write access to /volume1/web/glpi_safe/files/_sessions has been validated.
Write access to /volume1/web/glpi_safe/files/_tmp has been validated.
Write access to /volume1/web/glpi_safe/files/_uploads has been validated.
The following directories should be placed outside "/volume1/web/glpi":
‣ "/volume1/web/glpi_safe/files" ("GLPI_VAR_DIR")
‣ "/volume1/web/glpi_safe/config" ("GLPI_CONFIG_DIR")
‣ "/volume1/web/glpi_safe/log" ("GLPI_LOG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /volume1/web/glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/volume1/web/glpi"
GLPI_CONFIG_DIR: "/volume1/web/glpi_safe/config"
GLPI_VAR_DIR: "/volume1/web/glpi_safe/files"
GLPI_LOG_DIR: "/volume1/web/glpi_safe/log"
GLPI_MARKETPLACE_DIR: "/volume1/web/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/volume1/web/glpi_safe/files"
GLPI_CACHE_DIR: "/volume1/web/glpi_safe/files/_cache"
GLPI_CRON_DIR: "/volume1/web/glpi_safe/files/_cron"
GLPI_DUMP_DIR: "/volume1/web/glpi_safe/files/_dumps"
GLPI_GRAPH_DIR: "/volume1/web/glpi_safe/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/volume1/web/glpi_safe/files/_locales"
GLPI_LOCK_DIR: "/volume1/web/glpi_safe/files/_lock"
GLPI_PICTURE_DIR: "/volume1/web/glpi_safe/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/volume1/web/glpi_safe/files/_plugins"
GLPI_RSS_DIR: "/volume1/web/glpi_safe/files/_rss"
GLPI_SESSION_DIR: "/volume1/web/glpi_safe/files/_sessions"
GLPI_TMP_DIR: "/volume1/web/glpi_safe/files/_tmp"
GLPI_UPLOAD_DIR: "/volume1/web/glpi_safe/files/_uploads"
GLPI_INVENTORY_DIR: "/volume1/web/glpi_safe/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/volume1/web/glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/volume1/web/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/volume1/web/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/volume1/web/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/volume1/web/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/volume1/web/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/volume1/web/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/volume1/web/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/volume1/web/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/volume1/web/glpi/vendor/sabre/http/lib)
sabre/uri in (/volume1/web/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/volume1/web/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/volume1/web/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/volume1/web/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/volume1/web/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/volume1/web/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/volume1/web/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/volume1/web/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/volume1/web/glpi/vendor/symfony/console)
scssphp/scssphp in (/volume1/web/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/volume1/web/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/volume1/web/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/volume1/web/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/volume1/web/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/volume1/web/glpi/vendor/ramsey/uuid/src)
psr/log in (/volume1/web/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/volume1/web/glpi/vendor/psr/simple-cache/src)
psr/cache in (/volume1/web/glpi/vendor/psr/cache/src)
league/csv in (/volume1/web/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/volume1/web/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/volume1/web/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/volume1/web/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/volume1/web/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/volume1/web/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/volume1/web/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/volume1/web/glpi/vendor/symfony/cache)
html2text/html2text in (/volume1/web/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/volume1/web/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/volume1/web/glpi/vendor/symfony/dom-crawler)
twig/twig in (/volume1/web/glpi/vendor/twig/twig/src)
twig/string-extra in (/volume1/web/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/volume1/web/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/volume1/web/glpi/vendor/symfony/polyfill-php82)

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

You should try to install `Phar` extension. It is probably required to install `tar.bz2` files.
