### ISSUE TITLE
Followup author is receiving email notification of their own followup

### ISSUE THREAD

**Issue by ts2050** [glpi-project/glpi#14392]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.6 ( => /var/www/glpi)

### Bug description

Context:

When an requerent sends an email or includes a notification via the system, the notification also reaches them via email, thus duplicating it. The forum mentions that this was corrected in version 10.0.5, but in tests on version 10.0.6 it still persists.

In the GLPI system, there has been an issue where notifications sent by applicants via email or through the system are being duplicated. This means that the applicant receives the same notification twice, which can be confusing and lead to unnecessary clutter in their inbox. This issue was supposed to have been fixed in version 10.0.5, as per the forum discussions. 

discussion
[https://forum.glpi-project.org/viewtopic.php?id=281641](https://forum.glpi-project.org/viewtopic.php?id=281641)

**Comment by cedric-anne** [comment]
Hi,

I am not sure to understand your issue. Can you, please, provide informations requested in issue form (i.e. steps to reproduce, GLPI system information, ...)?
