### ISSUE TITLE
[9.5.12] Supplier option no longer allows to add an external email

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#14409]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.12

### Bug description

When selecting "Supplier" in the "Assigned to" option, we no longer can write an email, we can only select an existing "internal" created Supplier.

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Open a ticket
2. In the Assigned to option select Supplier
3. It only shows the internal suppliers and not the option to write an email.

Not shows this:
![image](https://user-images.githubusercontent.com/43515938/228498582-9bc97af8-2abb-4d5d-8fdd-2028ee8bb2f0.png)

Should be like this:
![image](https://user-images.githubusercontent.com/43515938/228498265-c04dcdf4-d0a8-4adb-b456-4e1ad80d6b7e.png)

### Your GLPI setup information

Operating system: Linux GLPI 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64
PHP 7.2.34 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mbstring, msgpack,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, session, shmop, sockets, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="1024M" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: nginx/1.20.1
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.54
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.38
	Server SQL Mode: 
	Parameters: user_glpi@172.20.12.45:33306/GLPI_DB
	Host info: 172.20.12.45 via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is not presentsodium extension is not present
Database version seems correct (5.7.38) - Perfect!Database version seems correct (5.7.38) - Perfect!

The log file has been created successfully.The log file has been created successfully.
Write access to /data/glpi/files/_cache has been validated.Write access to /data/glpi/files/_cache has been validated.
Write access to /data/www/glpi.ipleiria.pt/public_html/config has been validated.Write access to /data/www/glpi.ipleiria.pt/public_html/config has been validated.
Write access to /data/glpi/files/_cron has been validated.Write access to /data/glpi/files/_cron has been validated.
Write access to /data/glpi/files has been validated.Write access to /data/glpi/files has been validated.
Write access to /data/glpi/files/_dumps has been validated.Write access to /data/glpi/files/_dumps has been validated.
Write access to /data/glpi/files/_graphs has been validated.Write access to /data/glpi/files/_graphs has been validated.
Write access to /data/glpi/files/_lock has been validated.Write access to /data/glpi/files/_lock has been validated.
Write access to /data/glpi/files/_pictures has been validated.Write access to /data/glpi/files/_pictures has been validated.
Write access to /data/glpi/files/_plugins has been validated.Write access to /data/glpi/files/_plugins has been validated.
Write access to /data/glpi/files/_rss has been validated.Write access to /data/glpi/files/_rss has been validated.
Write access to /data/glpi/files/_sessions has been validated.Write access to /data/glpi/files/_sessions has been validated.
Write access to /data/glpi/files/_tmp has been validated.Write access to /data/glpi/files/_tmp has been validated.
Write access to /data/glpi/files/_uploads has been validated.Write access to /data/glpi/files/_uploads has been validated.
Write access to /data/www/glpi.ipleiria.pt/public_html/marketplace has been validated.Write access to /data/www/glpi.ipleiria.pt/public_html/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.

### Anything else?

We upgraded from 9.5.6 to 9.5.12, so we don't know in which version the problem started...

**Comment by cedric-anne** [comment]
Hi,

GLPI 9.5 is no longer supported. There may have been a regression on this feature in GLPI 9.5.x branch, but it will not be fixed.
If problem is still present on GLPI 10.0, feel free to reopen the issue.

Regards
