### ISSUE TITLE
GLPI not behaving exactly as expected after database import 

### ISSUE THREAD

**Issue by lirmikey** [glpi-project/glpi#14411]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Even if the row numbers are correct in the database after import with a sql file of version 10.0.6 taken with mysqldump, GLPI is not handling all relationships between tables as expected. It is affecting a number of tables like users, entities, networkequipment, tickets. I have tried everything. There are no errors in logfiles.

### Your GLPI setup information

Apache 2.4.56 on Debian 11.6 with kernel 5.10.0-21, 10.5.18-MariaDB-0+deb11u1, PHP 7.4.33

**Comment by lirmikey** [comment]
First we thought data is missing, but a row count shows that the tables are the same. After little research I saw that even if I am a recursive super-admin and should have sufficient rights to view the data, there is nothing to recurse into, because the relationship between glpi_entities and other tables has problems.

**Comment by cedric-anne** [comment]
Hi,

What do you mean by "database import"?
If you try to restore a dump from another version of GLPI, you have to do it on an empty database (i.e. without any GLPI table inside it), and then run the update process.
If you try to restore a dump on an already installed GLPI instance database, you will just have a mix of tables/data from different GLPI versions and it will be impossible to fix it automatically.

Unless you provide a clear way to reproduce it on our side, we cannot help anymore.

**Comment by lirmikey** [comment]
I could send screenshots

**Comment by cedric-anne** [comment]
Did you try to logout and log in again? Did you try to clear GLPI cache?

**Comment by lirmikey** [comment]
Is this documented anywhere?

**Comment by cedric-anne** [comment]
> That seemed to fix it. Could you please explain why?

When you do operations in DB directly, GLPI application cannot be aware of this, so cached values cannot be invalidated automatically.
This is the same for almost any application. Detecting such changes would require to implement detection algorithm that would have negative impact on performances and that may introduce bugs, to handle a really an edge case.

Post DB restore operations are not documentated. Maybe they should, as it can be a legitimate usage, for instance when a server crashed.

I close this issue as it is not related to a bug.
