### ISSUE TITLE
Information about number field for plugins

### ISSUE THREAD

**Issue by jackburton79** [glpi-project/glpi#14410]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.6

### Bug description

Currently I'm using "Dropdown::showNumber" in a plugin, but I'd prefer to use the field used in Displays, this one:

![image](https://user-images.githubusercontent.com/3501519/228505146-2d6c85ef-552c-4b1d-b7ce-6b92f07becd9.png)

Is it possible ? 

If this place is not the correct one for this kind of request, I'm sorry.

**Comment by cconard96** [comment]
The [community forum](https://forum.glpi-project.org/) would be the best place for a question about developing a plugin.
GitHub issues are used for bug reports only.

**Comment by cedric-anne** [comment]
Hi,

This kind of display is using the following Twig macro:
https://github.com/glpi-project/glpi/blob/24b1c3a7522de9f2c39dc2021f180202d5fd514f/templates/components/form/fields_macros.html.twig#L160-L182

If you need more information, please use community forums.
