### ISSUE TITLE
[GLPI 10] No update of Computer_item fields on Computer Inventory

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#14416]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

When I force an inventory of a GLPI agent, the fields of connected objects (monitor, peripheral) do not update

This is a problem with post_updateItem function of Computer.php

On computer inventory, there is only 2 fields in $updates array by default  : 
[0] => last_inventory_update
[1] => date_mod 

https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/Computer.php#L158

So even if $CFG_GLPI['xxxx_autoupdate'] exists, it does nothing.

We must add :

```
if ($CFG_GLPI['is_contact_autoupdate']) {
            $this->updates[] = 'contact';
            $this->updates[] = 'contact_num';
        }

        if ($CFG_GLPI['is_user_autoupdate']) {
            $this->updates[] = 'users_id';
        }

        if ($CFG_GLPI['is_group_autoupdate']) {
            $this->updates[] = 'groups_id';
        }

        if ($CFG_GLPI['state_autoupdate_mode'] < 0) {
            $this->updates[] = 'states_id';
        }

        if ($CFG_GLPI['is_location_autoupdate']) {
            $this->updates[] = 'locations_id';
        }
```

before $update_count = count($this->updates ?? []);

**Comment by trasher** [comment]
This behavior is tested twice as said in our discussion channel; maybe is there a edge case, or a configuration that impacts, but that basically works as expected.

**Comment by trasher** [comment]
No feedback, I close
