### ISSUE TITLE
 OLA recalculating when assigning technician

### ISSUE THREAD

**Issue by vinilamelas** [glpi-project/glpi#14423]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

The Rule is about to apply the OLA through the attribution of the technical group (rules are like adding and updating because it is necessary to add the group in already opened tickets), but when the technical group is already assigned (OLA has already been recalculated) and I join to the ticket the OLA is recalculated again.

Rule:
![image](https://user-images.githubusercontent.com/51828518/228904925-169d8223-cbc4-4f64-befb-b5274b28b07f.png)

Criteria
![image](https://user-images.githubusercontent.com/51828518/228905008-fb7be5b0-7103-4536-88f5-5c9e428888ae.png)

Action
![image](https://user-images.githubusercontent.com/51828518/228905130-90d7c6e3-1831-4b46-a165-e5a4f77597b0.png)

Historical:
![image](https://user-images.githubusercontent.com/51828518/228904657-5780c0fb-d165-44a1-8516-cbf1b17ea7e1.png)

**Comment by cedric-anne** [comment]
Hi,

Does this issue persist on GLPI 10.0.7? Some fixes related to OLA have been made, but I do not remember exactly what was fixed.

**Comment by cedric-anne** [comment]
Fixed by #14497
