### ISSUE TITLE
Can't log-in into super-admin view

### ISSUE THREAD

**Issue by angh0r** [glpi-project/glpi#14438]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

No matter what is set up in my account preferences, I'm always logging in to the self-service view. After logging in, when checking my account setup the default profile and default entity are back to their initial values. 

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.6 ( => /volume1/web/glpi_web)
Installation mode: TARBALL
Current language:en_US

</details><details><summary>Server</summary><pre> 
Operating system: Linux NAS01 4.4.59+ #25556 SMP PREEMPT Sat Aug 28 02:16:43 CST 2021 x86_64
PHP 7.4.30 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap, libxml,
	mailparse, mbstring, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, readline,
	session, shmop, soap, sockets, sodium, sqlite3, ssh2, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="240" memory_limit="128M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: nginx/1.16.1
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Server Software: Source distribution
	Server Version: 10.3.29-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_user@127.0.0.1:3307/new_glpi
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (7.4.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.29) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /volume1/web/glpi_web/files/_cache has been validated.
Write access to /volume1/web/glpi_web/config has been validated.
Write access to /volume1/web/glpi_web/files/_cron has been validated.
Write access to /volume1/web/glpi_web/files has been validated.
Write access to /volume1/web/glpi_web/files/_dumps has been validated.
Write access to /volume1/web/glpi_web/files/_graphs has been validated.
Write access to /volume1/web/glpi_web/files/_lock has been validated.
Write access to /volume1/web/glpi_web/files/_pictures has been validated.
Write access to /volume1/web/glpi_web/files/_plugins has been validated.
Write access to /volume1/web/glpi_web/files/_rss has been validated.
Write access to /volume1/web/glpi_web/files/_sessions has been validated.
Write access to /volume1/web/glpi_web/files/_tmp has been validated.
Write access to /volume1/web/glpi_web/files/_uploads has been validated.
The following directories should be placed outside "/volume1/web/glpi_web":
‣ "/volume1/web/glpi_web/files" ("GLPI_VAR_DIR")
‣ "/volume1/web/glpi_web/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /volume1/web/glpi_web/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/volume1/web/glpi_web"
GLPI_CONFIG_DIR: "/volume1/web/glpi_web/config"
GLPI_VAR_DIR: "/volume1/web/glpi_web/files"
GLPI_MARKETPLACE_DIR: "/volume1/web/glpi_web/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/volume1/web/glpi_web/files"
GLPI_CACHE_DIR: "/volume1/web/glpi_web/files/_cache"
GLPI_CRON_DIR: "/volume1/web/glpi_web/files/_cron"
GLPI_DUMP_DIR: "/volume1/web/glpi_web/files/_dumps"
GLPI_GRAPH_DIR: "/volume1/web/glpi_web/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/volume1/web/glpi_web/files/_locales"
GLPI_LOCK_DIR: "/volume1/web/glpi_web/files/_lock"
GLPI_LOG_DIR: "/volume1/web/glpi_web/files/_log"
GLPI_PICTURE_DIR: "/volume1/web/glpi_web/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/volume1/web/glpi_web/files/_plugins"
GLPI_RSS_DIR: "/volume1/web/glpi_web/files/_rss"
GLPI_SESSION_DIR: "/volume1/web/glpi_web/files/_sessions"
GLPI_TMP_DIR: "/volume1/web/glpi_web/files/_tmp"
GLPI_UPLOAD_DIR: "/volume1/web/glpi_web/files/_uploads"
GLPI_INVENTORY_DIR: "/volume1/web/glpi_web/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/volume1/web/glpi_web/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/volume1/web/glpi_web/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.6.0 in (/volume1/web/glpi_web/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/volume1/web/glpi_web/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/volume1/web/glpi_web/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/volume1/web/glpi_web/vendor/michelf/php-markdown/Michelf)
true/punycode in (/volume1/web/glpi_web/vendor/true/punycode/src)
iamcal/lib_autolink in (/volume1/web/glpi_web/vendor/iamcal/lib_autolink)
sabre/dav in (/volume1/web/glpi_web/vendor/sabre/dav/lib/DAV)
sabre/http in (/volume1/web/glpi_web/vendor/sabre/http/lib)
sabre/uri in (/volume1/web/glpi_web/vendor/sabre/uri/lib)
sabre/vobject in (/volume1/web/glpi_web/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/volume1/web/glpi_web/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/volume1/web/glpi_web/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/volume1/web/glpi_web/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/volume1/web/glpi_web/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/volume1/web/glpi_web/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/volume1/web/glpi_web/vendor/elvanto/litemoji/src)
symfony/console in (/volume1/web/glpi_web/vendor/symfony/console)
scssphp/scssphp in (/volume1/web/glpi_web/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/volume1/web/glpi_web/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/volume1/web/glpi_web/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/volume1/web/glpi_web/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/volume1/web/glpi_web/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/volume1/web/glpi_web/vendor/ramsey/uuid/src)
psr/log in (/volume1/web/glpi_web/vendor/psr/log/Psr/Log)
psr/simple-cache in (/volume1/web/glpi_web/vendor/psr/simple-cache/src)
psr/cache in (/volume1/web/glpi_web/vendor/psr/cache/src)
league/csv in (/volume1/web/glpi_web/vendor/league/csv/src)
mexitek/phpcolors in (/volume1/web/glpi_web/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/volume1/web/glpi_web/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/volume1/web/glpi_web/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/volume1/web/glpi_web/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/volume1/web/glpi_web/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/volume1/web/glpi_web/vendor/paragonie/sodium_compat/src)
symfony/cache in (/volume1/web/glpi_web/vendor/symfony/cache)
html2text/html2text in (/volume1/web/glpi_web/vendor/html2text/html2text/src)
symfony/css-selector in (/volume1/web/glpi_web/vendor/symfony/css-selector)
symfony/dom-crawler in (/volume1/web/glpi_web/vendor/symfony/dom-crawler)
twig/twig in (/volume1/web/glpi_web/vendor/twig/twig/src)
twig/string-extra in (/volume1/web/glpi_web/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/volume1/web/glpi_web/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/volume1/web/glpi_web/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/volume1/web/glpi_web/vendor/symfony/polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://dc01.adal.local', Port: '389', BaseDN: 'OU=ADAL,DC=adal,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'glpiusersearch',
		Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (glpi@adal.eu@adal-bs.home.pl)

</details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Error / to clean                        
		Install Method: Manual
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Error / to clean                        
		Install Method: Manual
	genericobject        Name: Zarządzanie obiektami          Version: 2.14.1     State: Error / to clean                        
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

I am not able to reproduce. Could you try to test if issue can be reproduced on PHP 8.x?

**Comment by trasher** [comment]
No feedback, I close
