### ISSUE TITLE
API AllAssets models error

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#1445]
Hello,

I have an error with AllAsset search options and "model" field : 

![image](https://cloud.githubusercontent.com/assets/12936546/21384357/956e0e7e-c76a-11e6-8fb1-4552253c01f9.png)

It works fine for all others fields but not this one.

Thanks for your help.

**Comment by cedric-anne** [comment]
Hi,

This field is not available for `AllAsset` type.

In 9.4, the  SQL error has been fixed.
```json
["ERROR","Bad field ID in search criteria; view documentation in your browser at http://127.0.0.1:8094/apirest.php/#ERROR"]
```

Regards
