### ISSUE TITLE
Setting custom field as mandatory

### ISSUE THREAD

**Issue by Dragnucs** [glpi-project/glpi#1446]
On **GLPI  0.83.7** we have two custom fields in ticket creation form.

- 1 dropdown
- 1 textbox

The custom fields were added according to [this tutorial](http://thibault.geoffroy.free.fr/tuto/GLPI_Ajouter_un_champ.pdf). No plugins was installed to add the two fields.

**How can I set these fields as mandatory?**

Thank you in advance.

**Comment by trasher** [comment]
This version of GLPI is no supported from a while... And you should really avoid modifying the code directly.

Anyways, if you need to add fields on ticket creation, maybe you'd better take a look to the [Fields plugin](https://github.com/pluginsGLPI/fields) (you'll probably need a more recent glpi version).

**Comment by Dragnucs** [comment]
Thank you. We need to plan an upgrade then.
