### ISSUE TITLE
Cannot import agent XML file even as super-admin.

### ISSUE THREAD

**Issue by fabriceverkor** [glpi-project/glpi#14469]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Cannot import agent XML file even as super-admin.
Message in red is : You don't have permission to perform this action. 

### Relevant log output

```shell
The action n GUI produces output in error log :

[2023-04-01 21:15:26] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: name in /var/www/glpi/src/Agent.php at line 253
  Backtrace :
  src/Search.php:7451                                Agent::getSpecificValueToDisplay()
  src/Search.php:1701                                Search::giveItem()
  src/Search.php:448                                 Search::constructData()
  ...tplace/glpiinventory/inc/dashboard.class.php:58 Search::getDatas()
  :                                                  PluginGlpiinventoryDashboard::nbItems()
  src/Dashboard/Grid.php:958                         call_user_func_array()
  ajax/dashboard.php:128                             Glpi\Dashboard\Grid->getCardHtml()
```

### Steps To reproduce

In GLPI Inventory

### Your GLPI setup information

<html><body>

Information about system installation & configuration
--
 
GLPI 10.0.6 ( => /var/www/glpi) Installation mode: TARBALL Current language:en_US
Operating system: Linux glpi 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 7.4.33 apache2handler
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at glpi.inf.biz.vic.verkor.com Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Server Software: Debian 11
	Server Version: 10.5.18-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost:3306/glpi
	Host info: Localhost via UNIX socket

	accounts             Name: Accounts                       Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Additional Fields              Version: 1.20.0     State: Enabled                                 
		Install Method: Marketplace
	badges               Name: Badges                         Version: 3.0.0      State: Not installed                           
		Install Method: Marketplace
	connections          Name: Connections                    Version: 10.0.0     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.12.1     State: Enabled                                 
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.19     State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.8.3      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.1     State: Enabled                                 
		Install Method: Marketplace
	reservation          Name: Reservation                    Version: 2.4.2      State: Installed / not activated               
		Install Method: Manual
	screenshot           Name: Screenshot                     Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	singlesignon         Name: Single Sign-on                 Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.11.0     State: Enabled                                 
		Install Method: Marketplace

### Anything else?

nothing

**Comment by cconard96** [comment]
Please check the access-errors.log file in files/_log for more detailed information about why access was denied.

**Comment by fabriceverkor** [comment]
Here is the reason :
User ID: 147 tried to access or perform an action on /front/inventory.conf.php?forcetab=Glpi\Inventory\Conf$2 with insufficient rights. Additional information: User is missing the 1024 (unknown right name) right for inventory
        Stack Trace:
                /var/www/glpi/src/Session.php:1039 displayRightError()
                /var/www/glpi/front/inventory.conf.php:40 checkRight()

**Comment by trasher** [comment]
Seems like this is a user right problem, not a bug.

**Comment by fabriceverkor** [comment]
Well, as I mentioned in first post, it happens with a user which has The Super-Admin profile on  Root entity recursively. 
All capabilities have been selected in GLPI inventory configuration part of this profile.

**Comment by cedric-anne** [comment]
Did you click multiple times on submit button ? In such case, a security token is consumed by first sent request, and is then refused by subsequent request, and mentionned message is displayed.

**Comment by fabriceverkor** [comment]
Yes I did. I tried different super-admin account (internal on or LDAP one). Always the same result. Is the ID 1024 in log extract above stored in the DB somewhere ? Would it be the glpi_profilerights table ?

**Comment by cedric-anne** [comment]
Could you try to reproduce on GLPI 10.0.7?

**Comment by trasher** [comment]
No feedback, I close

**Comment by fabriceverkor** [comment]
Sorry. I was really busy. I just upgraded our DEV platform to 10.0.7. Same result.

**Comment by cedric-anne** [comment]
Still not able to reproduce.

Are ou able to access the "Import from file" tab in `/front/inventory.conf.php`? If you are able to access it, there is no reason that you cannot import files.

**Comment by fabriceverkor** [comment]
No, it gives the same result.

**Comment by fabriceverkor** [comment]
It's the super-admin profile. All GLPI inventory rights are selected for this profile. I could not find a specific "Import" right. Would it be the right with ID 1024 in the log extract above ?

**Comment by cedric-anne** [comment]
> All GLPI inventory rights are selected for this profile.

These rights are related to the `GLPI Inventory` plugin.

You have to add rights to your profile in `Administration > Inventory` section.

**Comment by fabriceverkor** [comment]
Ah my bad. I so sorry. I was so sure that all rights were in GLPI Inventory part. Thank you again.
