### ISSUE TITLE
10.0.6 - Planning doesn't reflect reminder as VALARM

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#14479]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Using Caldavsynchronizer with Outlook there are no reminders for the created tasks in GLPI.
Looking into https://domain../caldav.php/calendars/users/myusername/calendar/5d652160-dc00-444a-8308-7f3905f2bd83.ics (which I found seeing in the logs) I've noticed that there is no VALARM set.

https://www.ietf.org/rfc/rfc2445.txt
   Description: A "VALARM" calendar component is a grouping of component
   properties that is a reminder or alarm for an event or a to-do. For
   example, it may be used to define a reminder for a pending event or
   an overdue to-do.

### Steps To reproduce

1. Create a task with planning 
2. Set reminder to 0 minutes or 5 minutes
3. Use a WebDAV client (Calendar)
4. See that there is no notification

**Comment by cedric-anne** [comment]
Hi,

I confirm this feature not exists. There is even a TODO in code for this: https://github.com/glpi-project/glpi/blob/bce21331d50a020cd0928178a68fe4aac2cc50b4/src/CalDAV/Backend/Calendar.php#L57
