### ISSUE TITLE
Tags in mail notifications

### ISSUE THREAD

**Issue by Tartiflette-glpi** [glpi-project/glpi#14477]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,
We have a problem when GLPI send notifications for follow up and tasks, we don't have the content by email but the `##followup.description##` and `##task.description##`  themself, it seems it doesnt work... While this works perfectly with `##ticket.solution.description##`
This exists since our 1st GLPI (v 9.5) and we though it will be resolved by upgrading GLPI but its still here...

Can you please help us ?

Thank you

### Steps To reproduce

With GLPI 10.0.6
Go to notification settings
Add ##followup.description## and ##task.description## in a model
Create a ticket and check the result by email

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.6 (/glpi => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR
</pre></details>

**Comment by cedric-anne** [comment]
Hi,

`##followup.description##` has to be placed between `##FOREACHfollowups##` and `##ENDFOREACHfollowups##`, for instance:
```
##FOREACHfollowups##
[##followup.date##] by ##followup.author##

##followup.description##
##ENDFOREACHfollowups##
```

Same for `##task.description##`, it has to be placed between `##FOREACHtasks##` and `##ENDFOREACHtasks##`.

Could you check your notification template?

**Comment by cedric-anne** [comment]
I close due to lack of feedback. Feel free to reopen.
