### ISSUE TITLE
Webcal doesn't sync tasks (notes ok)

### ISSUE THREAD

**Issue by hobbit32** [glpi-project/glpi#1448]
Good afternoon,

Using GLPI 9.1.1, webcal export now works correctly with Outlook 2016. Notes appear correctly on my Outlook calendar but scheduled tasks do not. 

Do you have any idea?
I attached two screenshots, the first one from GLPI, the second one from Outlook.

Thank you for your help
![outlook notes only](https://cloud.githubusercontent.com/assets/24711492/21417734/f57bf966-c85f-11e6-904e-6013253bb3a5.png)
![glpi task and notes](https://cloud.githubusercontent.com/assets/24711492/21417735/f57cf3ca-c85f-11e6-84a1-4c1213f21a18.png)

**Comment by hobbit32** [comment]
Good morning, 
Does it look like a bug or is it just not possible to sync tasks with outlook?
Thank you

**Comment by orthagh** [comment]
regression introduced by ba0f8160, PR incoming
