### ISSUE TITLE
Profiles section Administration: inventory acls not historized

### ISSUE THREAD

**Issue by keguira** [glpi-project/glpi#14481]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

In profiles management, under 'Administration', the section 'Inventory' is not properly logged in 'History'. 

### Steps To reproduce

1. Go to Administration > Profiles
2. Select a profile (in my case, it was 'Technician')
3. Click on the section Administration 
4. Jump to INVENTORY
5. Change the value of a checkbox

The action will not be logged into 'History'

### Anything else?

I did not identify this point in the changelog. I see that this section has been updated multiple times since the last few months. Maybe a regression due to crossing developments ?

Also, i am thinking of a way to improve the documentation (or at least our internal documentation) : this introduced a domain "regression", our Technicians had access to inventory information on an asset and with this update, they could not anymore

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue.
