### ISSUE TITLE
New 10.0.7 webserver config not applicable when GLPI is installed in subdir

### ISSUE THREAD

**Issue by haary** [glpi-project/glpi#14486]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Beginning with GLPI 10.0.7 it is suggested, that only public directory is exposed, i.e that the webroot / DocumentRoot points to glpi/public.

But there are cases where GLPI is installed in a subdirectory (e.g. /var/www/glpi) and the URL  looks like https://www.example.com/glpi. The webroot directory is set to /var/www or similar  in such cases, with several different websites or applications installed in different subdirectories.

Obviously one can't change the webroot to /var/www/glpi/public, because other installed websites or applications in /var/www (e.g. https://www.example.com/othersite) would no longer be accessible. So the suggested config at https://glpi-install--74.org.readthedocs.build/en/74/prerequisites.html#web-server is not applicable in such cases.

**Comment by cedric-anne** [comment]
Hi,

You can use an Alias.

`Alias "/glpi/" "/path/to/your/glpi/"`

**Comment by viktor-sc** [comment]
> Alias

Where would the Alias go in case of an NGINX Server?

**Comment by cedric-anne** [comment]
I do not know how to configure NGINX, but I search for 2 minutes and found that it would be something like that:

```
server {

    ...

    location /glpi/ {
      alias /var/www/glpi/public;
    }

    ...
}
```

**Comment by wp-perc** [comment]
Hello guys, I think we are facing this very same issue, but we don't seem able to find any useful info on the web.
We need to have GLPI answer on ```/glpi/```, but we don't are able to do it.

Here my current configuration:

```
                ### GLPI
                location /glpi {
                        alias /usr/share/glpi/public;

                        location /glpi/ {
                                try_files $uri /glpi/index.php$is_args$args;
                        }

                        location ~ ^/glpi/.*\.php(.*)$ {
                                # the following line needs to be adapted, as it changes depending on OS distributions and PHP versions
                                fastcgi_index index.php;
                                fastcgi_pass 127.0.0.1:9000;

                                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                                include fastcgi_params;

                                fastcgi_param SCRIPT_FILENAME /usr/share/glpi/public/index.php;
                        }

                }
```

When we try to get ```/glpi/index.php```, we get a HTTP 403. Looking at the debug log, it tries an internal redirect to ```/index.php?```, but I don't understand why.

Just to be sure, I tried this configuration with GLPI as Document Root and it works, do I think setup is fine.

Please, can you help me in understanding what am I doing wrong?

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) for community support.
