### ISSUE TITLE
Technical manager not available anymore as a notification recipient

### ISSUE THREAD

**Issue by rainbob5** [glpi-project/glpi#14482]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

The category "Technical manager" is not displayed anymore in Notifications recipients configuration. It was configured in multiple notifications before and it disappeared.

![image](https://user-images.githubusercontent.com/38276579/230055212-e0001a1b-a13c-4658-90f4-236c45452461.png)

### Steps To reproduce

1. Create a new notification
2. Go to Recipients tab
3. Try to find "Technical Manager", not found

### Your GLPI setup information

Ubuntu 22.04.2 LTS
PHP 8.1.17
Apache 2.4.52
GLPI 10.0.6

**Comment by cedric-anne** [comment]
Hi,

What is the related itemtype ?

**Comment by rainbob5** [comment]
It's a ticket

**Comment by rainbob5** [comment]
And yet the official documentation says there's a "Technical Manager" recipient: https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/notifications/definitions.html

**Comment by cedric-anne** [comment]
> The category "Technical manager" is not displayed anymore

On what version did you see it previously? I do not find anything related to this feature in code.

**Comment by trasher** [comment]
No feedback, I close
