### ISSUE TITLE
Pending reasons are ignoring the calendar

### ISSUE THREAD

**Issue by wc55** [glpi-project/glpi#14492]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When I choose a pending reason, it ignores the calendar.

I did the test with a calendar with only today, and when I chose the pending reason, to include the follow-up "Every day" and to close the ticket "After one follow-up", but the dates that appeared were 7/4/2023 and 8/4/2023, which would be outside the calendar.

I've always used it on a weekly basis, so I hadn't noticed the problem before, so I can't say if the problem predates version 10.0.6.

### Steps To reproduce

1. Access a ticket;
2. Add a follow-up by choosing a pending reason and choosing an interval outside of your calendar;
![image](https://user-images.githubusercontent.com/106084399/230386864-9030f8a7-9e12-42dd-bc9d-a23168bec03f.png)
3. Check the dates:
![image](https://user-images.githubusercontent.com/106084399/230388181-3c3a8552-dbd2-49de-b620-35340230e08d.png)

![image](https://user-images.githubusercontent.com/106084399/230388431-8dfd3b5e-8caf-41ef-b3dc-2963e94084fd.png)

### Anything else?

I used this calendar for testing:

![image](https://user-images.githubusercontent.com/106084399/230388923-e9338dbc-bc47-4979-b2ac-afa2197da271.png)

The calendar was configured in the entity:

![image](https://user-images.githubusercontent.com/106084399/230389216-84f19116-d4e9-4052-9bd4-37124d6438e2.png)

**Comment by cedric-anne** [comment]
Hi,

I confirm that pending reasons are not using calendars. I guess it would not be too complicated to get the calendar defined for ticket to compute a more appropriate date. Maybe we can also use the SLA calendar, but it need to be confirmed.
