### ISSUE TITLE
After 10.0.0.6 to 10.0.0.7 report web server access problem

### ISSUE THREAD

**Issue by grenona** [glpi-project/glpi#14498]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0.7

### Bug description

message at startup:

Web server root directory configuration is not safe as it permits access to non-public files

 ubuntu@ldap:~$ sudo ls -la /var/www
total 12
drwxr-xr-x  3 root root 4096 Nov 25  2021 .
drwxr-xr-x 15 root root 4096 Nov 25  2021 ..
drwxrwxrwx  6 root root 4096 Apr  5 14:21 html

**Comment by cedric-anne** [comment]
See https://glpi-install.readthedocs.io/en/latest/prerequisites.html#web-server

`DocumentRoot` must point to `/public` directory of GLPI.

**Comment by grenona** [comment]
Ok

How do I fix it ?


André Grenon
Architecte T.I.

Cortexgh.com

***@***.***




Le 7 avr. 2023 à 10:18, Cédric Anne ***@***.***> a écrit :

﻿

See https://glpi-install.readthedocs.io/en/latest/prerequisites.html#web-server

DocumentRoot must point to /public directory of GLPI.
