### ISSUE TITLE
you are not allowed and lost information

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1449]
Hello

We have a big issue on GLPI for many month, not always but very often, when we add a task we have the page you are not allowed to perform this action and we lose the text that we have entered.

same result with super admin profile

We are 25 technicians and during a meeting, all users said GLPI is good but this bug is ....!

I don't have anything in logs about that, do you have an idea ?

glpi 9.1 php 7.0.12 mariadb 10 IIS 8.5 WINDOWS 2012 r2

**Comment by tomolimo** [comment]
Hello Yannick 
As a temporary workaround you can disable the csrf check. Remember few months ago I gave you this hint already. 
Regards 
Tomolimo

**Comment by tomolimo** [comment]
#1133

**Comment by satyan01** [comment]
Ok I try, but Orthagh said it was not a good thing to do
