### ISSUE TITLE
Can not add multiple IpNetworks through the API REST

### ISSUE THREAD

**Issue by XavierCvl** [glpi-project/glpi#14490]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello,
I'm trying to use the API to add new IpNetworks. I'm using Postman for my tests. As long as I add only 1 network, no problem. But if I add 2 networks within the same POST action, I can see the 2 networks in GLPI, but the 2nd one does not get its ip address, and the field "ipnetworks_id" of the first network receives the id of the 2nd network. Also the 2nd network gets its completename changed. 
https://a.b.c.d/apirest.php/IPNetwork
My input content :
[
    {"completename": "test10","name": "test10","addressable": 1,"version": 4,"network": "10.0.0.0/24","gateway": "10.0.0.1"},
    {"completename": "test11","name": "test11","addressable": 1,"version": 4,"network": "11.0.0.0/24","gateway": "11.0.0.1"}
]
Result of the POST :
[
    {
        "id": 68,
        "message": "Élément ajouté : test10"
    },
    {
        "id": 69,
        "message": "Élément ajouté : test11"
    }
]
Result in GLPI :
 NOM COMPLET 	ENTITÉ	SOUS-ENTITÉS	RÉSEAU ADRESSABLE	VERSION D'IP	ADRESSE IP	MASQUE DE SOUS-RÉSEAU	PASSERELLE

test11 > test10	Entité racine	Non	Oui	4	10.0.0.0	255.255.255.0	10.0.0.1

test11			Entité racine	Non	Oui	4					11.0.0.1

Result in glpi_ipnetworks table :
id	entities_id	is_recursive	ipnetworks_id	name	completename	level	address	gateway	ancestors_cache	addressable	version	sons_cache
69	0	0	0	test11	test11	1	NULL	11.0.0.1	[]	1	4	NULL
68	0	0	69	test10	test11 > test10	2	10.0.0.0	10.0.0.1	NULL	1	4	NULL

 
If I add more than 2 networks, I get this problem every 2 networks (or every 2 items in the input array).
Any idea what I'm doing wrong ?

Thanks for your help,
Xavier

**Comment by cconard96** [comment]
Can you test the fix in #14491?

**Comment by XavierCvl** [comment]
Sure ! How can I download it ?

**Comment by trasher** [comment]
Use https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/14491.patch

**Comment by XavierCvl** [comment]
I'm not familiar with this... what shall I do with this patch file ?

**Comment by cconard96** [comment]
For simpler patches like this, making the changes manually may be the easiest method.
For larger patches, using the `patch` utility (on Linux at least) would be better.
From the main GLPI directory:
`patch < the_patch.patch`

To revert the changes:
`patch -R the_patch.patch`

**Comment by cedric-anne** [comment]
Fixed by #14491.
