### ISSUE TITLE
glpi 10.0.7 Public folder

### ISSUE THREAD

**Issue by waaalex** [glpi-project/glpi#14496]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

Message on glpi
**La configuration du dossier racine du serveur web n'est pas sécurisée car elle permet l'accès à des fichiers non publics. Référez-vous à la documentation d'installation pour plus de détails.**

**The configuration of the web server root folder is not secure because it allows access to non-public files. Refer to the installation documentation for more details.**

I have followed this : https://glpi-install.readthedocs.io/fr/develop/prerequisites.html?highlight=apache#web-server
but on https://glpi10/glpi/public address, css is not enabled 

Then https://glpi10/glpi/public/front/login.php >> page not found.

### Page URL

https://glpi10/glpi/public/front/login.php

### Steps To reproduce

connect to https://{hostname}/glpi/public/

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.7 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux srv-support.get.com 4.18.0-425.13.1.el8_7.x86_64 #1 SMP Tue Feb 21 04:20:52 EST 2023 x86_64
PHP 8.0.28 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="128M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Apache/2.4.37 (AlmaLinux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.0.28) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /GLPI_FILES/_cache has been validated.
Write access to /GLPI_CONFIG has been validated.
Write access to /GLPI_FILES/_cron has been validated.
Write access to /GLPI_FILES has been validated.
Write access to /GLPI_FILES/_dumps has been validated.
Write access to /GLPI_FILES/_graphs has been validated.
Write access to /GLPI_FILES/_lock has been validated.
Write access to /GLPI_FILES/_pictures has been validated.
Write access to /GLPI_FILES/_plugins has been validated.
Write access to /GLPI_FILES/_rss has been validated.
Write access to /GLPI_FILES/_sessions has been validated.
Write access to /GLPI_FILES/_tmp has been validated.
Write access to /GLPI_FILES/_uploads has been validated.
SELinux configuration is OK.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/GLPI_CONFIG"
GLPI_VAR_DIR: "/GLPI_FILES"
GLPI_LOG_DIR: "/GLPI_LOG"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/GLPI_FILES"
GLPI_CACHE_DIR: "/GLPI_FILES/_cache"
GLPI_CRON_DIR: "/GLPI_FILES/_cron"
GLPI_DUMP_DIR: "/GLPI_FILES/_dumps"
GLPI_GRAPH_DIR: "/GLPI_FILES/_graphs"
GLPI_LOCAL_I18N_DIR: "/GLPI_FILES/_locales"
GLPI_LOCK_DIR: "/GLPI_FILES/_lock"
GLPI_PICTURE_DIR: "/GLPI_FILES/_pictures"
GLPI_PLUGIN_DOC_DIR: "/GLPI_FILES/_plugins"
GLPI_RSS_DIR: "/GLPI_FILES/_rss"
GLPI_SESSION_DIR: "/GLPI_FILES/_sessions"
GLPI_TMP_DIR: "/GLPI_FILES/_tmp"
GLPI_UPLOAD_DIR: "/GLPI_FILES/_uploads"
GLPI_INVENTORY_DIR: "/GLPI_FILES/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://10.0.0.12', Port: '636', BaseDN: 'dc=get, dc=com', Connection filter: none, RootDN: 'cn=admin.glpi, cn=users,
		dc=get, dc=com', Use TLS: none
Server: 'ldaps://10.0.0.11', Port: '636', BaseDN: 'dc=get, dc=com', Connection filter: none, RootDN: 'cn=admin.glpi, cn=users,
		dc=get, dc=com', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@10.0.0.21)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.14.0     State: Enabled                                 
		Install Method: Manual
	accounts             Name: Comptes                        Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.12.0     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.0.0      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Impression pdf                 Version: 2.1.0      State: Enabled                                 
		Install Method: Manual
	mycustomview         Name: MyCustomView                   Version: 1.1.3      State: Enabled                                 
		Install Method: Manual
	reports              Name: Rapports                       Version: 1.15.0     State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

```
[root@srv-support conf.d]# cat glpi.conf
Alias /glpi /var/www/html/glpi

<Directory /var/www/html/glpi>
AllowOverride All
Require all granted

RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?(.*) https://%{SERVER_NAME}/glpi [R,L]
</Directory>
```

```
[root@srv-support conf.d]# cat ssl.conf
Listen 443 https

SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog
SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout  300
SSLRandomSeed startup file:/dev/urandom  256
SSLRandomSeed connect builtin
SSLCryptoDevice builtin

<VirtualHost glpi10:443>
 ServerName glpi10
 DocumentRoot /var/www/html/glpi
 SSLEngine on
 ErrorLog logs/ssl_error_log
 TransferLog logs/ssl_access_log
 LogLevel warn
 SSLProtocol -all +TLSV1.2 +TLSv1.3
 SSLCipherSuite ALL:+HIGH:!ADH:!EXP:!SSLv2:!SSLv3:!MEDIUM:!LOW:!NULL:!aNULL
 SSLHonorCipherOrder on
 SSLCertificateFile /etc/pki/tls/certs/glpi10.crt
 SSLCertificateKeyFile /etc/pki/tls/private/glpi10.key
</VirtualHost>
```

**Comment by cedric-anne** [comment]
Hi,

Your apache configuration is not correct:

```diff
- Alias /glpi /var/www/html/glpi
+ Alias /glpi /var/www/html/glpi/public

- <Directory /var/www/html/glpi>
+ <Directory /var/www/html/glpi/public>
```

Then, GLPI URLs did not changed, you have to access `https://glpi10/glpi/front/login.php`.
