### ISSUE TITLE
Impossible to filter in crypted drive or not

### ISSUE THREAD

**Issue by lyonelf** [glpi-project/glpi#14506]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5

### Bug description

On computers list, i want to filter those who are not crypted but the problem is that inventory list others system partitions like boot and recovery.

![2023-04-11_15h19_20](https://user-images.githubusercontent.com/34097487/231175402-41570d3f-4d37-4cae-b306-4a765b3aae42.png)

So i can't do anything.

**Comment by cedric-anne** [comment]
Hi,

Your issue is not really eloquent, and you did not even provide requested information. Could you please give more details and explain a little bit your issue?

**Comment by lyonelf** [comment]
Hello,

in the computer list, if i had the encryption statut collumn, this one show, not only the C: statut but all partitions.

So it's impossible to filter on it because everytime there are some " not crypted" partitions.

**Comment by cedric-anne** [comment]
Hi,

Indeed, this is a limitation of the search engine.

**Comment by lyonelf** [comment]
So that not the engine the problem but adding a function in GLPI inventory to report only the c: statut.

**Comment by cedric-anne** [comment]
> So that not the engine the problem but adding a function in GLPI inventory to report only the c: statut.

Anyway, this is a new feature that should be discussed/validated/funded/...
