### ISSUE TITLE
Can't change planned end date

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1450]
I can't change planned end date auf this sub task.
No error
No error in Debug mode 
No message

The new changed date is not saved (28-12-2016 / 31-12-2016).
![img_036](https://cloud.githubusercontent.com/assets/19192087/21421824/3497bd90-c835-11e6-9666-f0e6a3a2eee3.jpg)

**Comment by AnaelMobilia** [comment]
Hello @Armin83 ,

I couldn't reproduce this error on the dev version.

Could you, please, give more details on your configuration ?

Regards,
Anael

**Comment by trasher** [comment]
Cannot reproduce on 9.1/bugfixes branch. Do you have any active plugins? Could you please try to reproduce deactivating them?

**Comment by Armin83** [comment]
Okay - i got it :)
If i set milestone = yes it is not possible to change planned end date.
End date is always exact the value from start date.

**Comment by trasher** [comment]
Indeed... And that is what is expected from the source code (it is not a bug). As far as I can see (I'm far from being an expert!); milestones should not have any duration, nor end date. I think original developper has set end date to start date to avoid issues.
