### ISSUE TITLE
Applicant name and ticket data do not appear in ticket tab

### ISSUE THREAD

**Issue by ogd0ug** [glpi-project/glpi#14501]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.1

### Bug description

when I go to a ticket, previously the name of who created the ticket and when it was created appeared, now it is blank
![image](https://user-images.githubusercontent.com/113532896/230916159-4cf6a929-1eed-4047-afec-06439752a7b1.png)

**Comment by ogd0ug** [comment]
![image](https://user-images.githubusercontent.com/113532896/230916091-085bf681-d2b8-41d3-a409-e3505c0e7d70.png)

**Comment by cconard96** [comment]
10.0.1 is an old release and 6 newer bug-fix versions have been released since then. Please try updating to 10.0.7 in case this is one of the many bugs that have already been fixed.

**Comment by trasher** [comment]
As said, this is a very old version. Opne a new issue and provide all requested information if you can reproduce on 10.0.7.
