### ISSUE TITLE
Drop AJAX_INCLUDE from ajax/itemTicket.php

### ISSUE THREAD

**Issue by drTr0jan** [glpi-project/glpi#1451]
The issue is like a #1436.

When the AJAX_INCLUDE var is defined, plugins are not loaded at all.

Trying to add an associated element from 'Objects management' plugin throws an error because plugin is not loaded: the elements are dissapearing from the dropdown list, and _Item_Ticket::showItemToAdd()_ function is working incorrectly.
I'll have to remove the AJAX_INCLUDE variable to get things working.

I've made a try, it does not seems to break anything (and it makes an elements from the plugin to work).

**Comment by trasher** [comment]
Since this file is only called once in the code; I guess this is ok to cange :)
