### ISSUE TITLE
GLPI 10.0.6 automatic actions not working in CLI mode

### ISSUE THREAD

**Issue by RaivoMahnovs** [glpi-project/glpi#14517]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

After upgrade from GLPI 9.5.5 to 10.0.6; php from 7.4 to 8.1; mariadb from 10.4 to 10.11 and nginx to 1.22 i found, that none of automatic actions are working automatically. Crontab is working fine, because other scripts are executing correctly, but /GLPI_root/front/cron.php is not, so all automatic actions in GLPI are showing last and next execution time, but not running it. 
If i run these tasks manually - it works fine. 

my crontab:

* * * * * /usr/bin/php /usr/share/nginx/html/front/cron.php &>/dev/null

### Relevant log output

```shell
Unknown function queuednotification::cronqueuednotification (cron)
2023-04-13 11:14:01 [@my.host.name]
Internal #2: Can't run queuednotification

Internal #1: Nothing to Launch
```

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/120176527/231715504-fc672bcf-be76-4cb3-ab75-74e0e5c77f81.png)

**Comment by cedric-anne** [comment]
Hi,

Have you some more logs to provide? For instance logs from `php-errors.log`.

A common mistake it to execute the cron using another user than the one associated to the webserver (`www-data` per default). Could you ensure that the crontab is associated to this user, and that all GLPI files are owned by this user?

**Comment by RaivoMahnovs** [comment]
Thank you for fast answer!

php-error.log shows the same message about queuednotification:

![Capture](https://user-images.githubusercontent.com/120176527/231722497-7a345642-f299-46b2-a3fc-e594f0d35adf.PNG)


All GLPI files are owned by nginx user and group. 

![Capture](https://user-images.githubusercontent.com/120176527/231722422-f2b01426-fdbb-4f14-a1e8-9931354314d7.JPG)


/etc/crontab file shows:

![image](https://user-images.githubusercontent.com/120176527/231722639-ffc1c888-2f1a-4ecf-a81b-f2fd6b45dd12.png)


so i am guessing it runs with root privileges, but i need to run it as nginx user?

**Comment by cedric-anne** [comment]
> so i am guessing it runs with root privileges, but i need to run it as nginx user?

Indeed, it should.

Also, please execute the following SQL request: `` UPDATE `glpi_crontasks` SET `itemtype` = 'QueuedNotification' WHERE `itemtype` = 'queuednotification'; ``. No idea why, but you have data with wrong case.
