### ISSUE TITLE
 Error Unable to connect to the LDAP directory

### ISSUE THREAD

**Issue by sofi1022** [glpi-project/glpi#14516]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hi,
After the update we cannot login into the AD base.
We only get errors unable to connect to the ldap.
DB is working normally without issues.

**Comment by cedric-anne** [comment]
Hi,

Can you try #14563?

**Comment by sofi1022** [comment]
> Hi,
> 
> Can you try #14563?

Hi for me logging into the glpi admin account helped.I refreshed the connection than ldap worked.
But i never had this issue while updating,
