### ISSUE TITLE
Incorrect format of the user's photo in the pop-up card

### ISSUE THREAD

**Issue by tovich** [glpi-project/glpi#14518]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

When you hover over the letter "i", a contact card pops up next to the user name. It has a name, email and a photo uploaded for example from LDAP. In this card, the photo is cropped, although if you go to the user profile, the photo there is completely normal. The bug does not occur for all users, but only for some part. Moreover, it occurs gradually, i.e. at first the photo is normal, and later it may become cropped.
![bug](https://user-images.githubusercontent.com/23525927/231756454-4bb71230-2426-47e7-93d6-f34f57401613.png)

### Your GLPI setup information

Operating system: Linux glpi 4.12.14-122.88-default #1 SMP Mon Sep 13 15:08:09 UTC 2021 (22a2967) x86_64
PHP 7.4.6 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, readline,
	session, shmop, snmp, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Apache (Apache Server at sd.itgrp.ru Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/111.0
Server Software: SUSE package
	Server Version: 10.2.40-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@10.129.103.200/glpi
	Host info: 10.129.103.200 via TCP/IP
	
PHP version (7.4.6) is supported.PHP version (7.4.6) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.2.40) is supported.Database engine version (10.2.40) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
The directory could not be created in /srv/glpi/files/_cache. Write access to /srv/glpi/config has been validated. The directory could not be created in /srv/glpi/files/_cron. Write access to /srv/glpi/files has been validated. The directory could not be created in /srv/glpi/files/_dumps. The directory could not be created in /srv/glpi/files/_graphs. The directory could not be created in /srv/glpi/files/_lock. The directory could not be created in /srv/glpi/files/_pictures. The directory could not be created in /srv/glpi/files/_plugins. The directory could not be created in /srv/glpi/files/_rss. The directory could not be created in /srv/glpi/files/_sessions. The directory could not be created in /srv/glpi/files/_tmp. The directory could not be created in /srv/glpi/files/_uploads.The directory could not be created in /srv/glpi/files/_cache.
Write access to /srv/glpi/config has been validated.
The directory could not be created in /srv/glpi/files/_cron.
Write access to /srv/glpi/files has been validated.
The directory could not be created in /srv/glpi/files/_dumps.
The directory could not be created in /srv/glpi/files/_graphs.
The directory could not be created in /srv/glpi/files/_lock.
The directory could not be created in /srv/glpi/files/_pictures.
The directory could not be created in /srv/glpi/files/_plugins.
The directory could not be created in /srv/glpi/files/_rss.
The directory could not be created in /srv/glpi/files/_sessions.
The directory could not be created in /srv/glpi/files/_tmp.
The directory could not be created in /srv/glpi/files/_uploads.
The following directories should be placed outside "/srv/glpi": ‣ "/srv/glpi/files" ("GLPI_VAR_DIR") ‣ "/srv/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "/srv/glpi":
‣ "/srv/glpi/files" ("GLPI_VAR_DIR")
‣ "/srv/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.Sessions configuration is secured.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /srv/glpi/marketplace has been validated.Write access to /srv/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by trasher** [comment]
Please try with latest release.

**Comment by tovich** [comment]
In version 10.0.7 it is the same. At least, when upgrading from 10.6, the situation has not changed.

**Comment by cedric-anne** [comment]
It seems to be the same issue as #13880 .
