### ISSUE TITLE
You have an error in your SQL syntax in savedsearch without login

### ISSUE THREAD

**Issue by rootjog** [glpi-project/glpi#14529]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

While trying to access without login access to 

- HOST/front/savedsearch.php?as_map=0&browse=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=hello&search=&itemtype=SavedSearch&start=0&_glpi_csrf_token=208880f8ce8fef9876369aae54a7435db9b960112d417bb281f4ee864e4f4cbe

Host returns 

> ```You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') WHERE `glpi_savedsearches`.`is_private` = '1' AND `glpi_savedsearches`.`users_' at line 14```

We tried accessing data using id or some filters but nothing seems to be returned, we don't know how worrying it is but maybe some tests should be done.

### Page URL

HOST/front/savedsearch.php?as_map=0&browse=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B0%5D%5Bvalue%5D=hello&search=&itemtype=SavedSearch&start=0&_glpi_csrf_token=208880f8ce8fef9876369aae54a7435db9b960112d417bb281f4ee864e4f4cbe

### System
Operating system: Linux glpi 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 8.2.4 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="900" memory_limit="512M" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache ()
	Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.32
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_dev@localhost/glpi_dev
	Host info: Localhost via UNIX socket
	
PHP version (8.2.4) is supported.PHP version (8.2.4) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.32) is supported.Database engine version (8.0.32) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi-dev/files/_cache has been validated. Write access to /var/www/glpi-dev/config has been validated. Write access to /var/www/glpi-dev/files/_cron has been validated. Write access to /var/www/glpi-dev/files has been validated. Write access to /var/www/glpi-dev/files/_dumps has been validated. Write access to /var/www/glpi-dev/files/_graphs has been validated. Write access to /var/www/glpi-dev/files/_lock has been validated. Write access to /var/www/glpi-dev/files/_pictures has been validated. Write access to /var/www/glpi-dev/files/_plugins has been validated. Write access to /var/www/glpi-dev/files/_rss has been validated. Write access to /var/www/glpi-dev/files/_sessions has been validated. Write access to /var/www/glpi-dev/files/_tmp has been validated. Write access to /var/www/glpi-dev/files/_uploads has been validated.Write access to /var/www/glpi-dev/files/_cache has been validated.
Write access to /var/www/glpi-dev/config has been validated.
Write access to /var/www/glpi-dev/files/_cron has been validated.
Write access to /var/www/glpi-dev/files has been validated.
Write access to /var/www/glpi-dev/files/_dumps has been validated.
Write access to /var/www/glpi-dev/files/_graphs has been validated.
Write access to /var/www/glpi-dev/files/_lock has been validated.
Write access to /var/www/glpi-dev/files/_pictures has been validated.
Write access to /var/www/glpi-dev/files/_plugins has been validated.
Write access to /var/www/glpi-dev/files/_rss has been validated.
Write access to /var/www/glpi-dev/files/_sessions has been validated.
Write access to /var/www/glpi-dev/files/_tmp has been validated.
Write access to /var/www/glpi-dev/files/_uploads has been validated.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi-dev/marketplace has been validated.Write access to /var/www/glpi-dev/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

**Comment by cedric-anne** [comment]
Hi,

I confirm there is a SQL issue here (no possible injection, just a missing value).
