### ISSUE TITLE
WebCal and iCAL export are empty since 10.0.7

### ISSUE THREAD

**Issue by pvasener** [glpi-project/glpi#14539]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

Since we upgraded to 10.0.7, our iCAL and WebCAL exports are all empty. Tasks are properly displayed in the planning web page tough.

**Comment by cconard96** [comment]
Please include the requested log and GLPI setup information.

**Comment by cedric-anne** [comment]
Without requested information, we cannot investigate. Feel free to reopen if you can provide them.
