### ISSUE TITLE
Please! An important suggestion to add the status

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1453]
Please add the status of "approval" for ticket that appears automatically at the time of the request for validation, as new and processing (assigned) and Solved, etc.

Please, very need!

**Comment by wawax** [comment]
Hello,

Please submit your suggestions here : http://suggest.glpi-project.org
Thank you !

**Comment by AircraftRu** [comment]
Thank you, I created the ticket http://glpi.userecho.com/topics/464-please-an-important-suggestion-to-add-the-status
