### ISSUE TITLE
Global kanban not adding selected columns

### ISSUE THREAD

**Issue by RaivoMahnovs** [glpi-project/glpi#14546]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

The button "Add Columns" from Global kanban section is not executing nothing. It should show couple of tables below, but it shows nothing and selected filters stay in search field:

![image](https://user-images.githubusercontent.com/120176527/232768374-f77663d3-9441-4934-94bc-626db9cedeb2.png)

In version 10.0.6 worked fine.

### Relevant log output

```shell
No error logs show information about this issue. Debug mode also not showing anything.
```

### Steps To reproduce

1. Go to section Assistance/Tickets

![image](https://user-images.githubusercontent.com/120176527/232769307-b12f6d36-85e9-465d-84f2-1c30eebebd8e.png)

2. Click on Global Kanban button

![image](https://user-images.githubusercontent.com/120176527/232769465-225a9bb9-b63f-46fc-b4c5-342667d28a33.png)

3. Enter some filters in search bar

![image](https://user-images.githubusercontent.com/120176527/232769869-0fe52a21-34c2-428a-ab3b-3e3757f0239f.png)

4. Push the button "Add column" on the right from Kanban search bar

![image](https://user-images.githubusercontent.com/120176527/232770127-a13a4f5f-e8f8-40d2-a9da-ed5c43171f0c.png)

### Your GLPI setup information

![image](https://user-images.githubusercontent.com/120176527/232770215-89794f21-12d9-4205-8fb6-9e770e441be3.png)

**Comment by cconard96** [comment]
I cannot recreate the issue reported. For me, the only things I notice are that filters are not re-applied when a new column is shown and there is an issue where the closed column doesn't show until you refresh the page due to the way it works with never showing any content and only being a target to close tickets dropped in it.

Other columns are able to be shown as expected.
