### ISSUE TITLE
htaccess is not working to resolve web server root directory configuration issue.

### ISSUE THREAD

**Issue by zakirpcs** [glpi-project/glpi#14550]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I have configure htaccess file as below to fix web server root directory issue but still i am facing web server root directory configuration is not safe issue.

##GLPI web content path
 /var/www/html/glpi

## Apache httpd.conf configuration file as follows:

<Directory "/var/www/html/glpi">
    Options Indexes FollowSymLinks
    #AllowOverride None
    AllowOverride All
    # Allow open access:
    Require all granted
</Directory>

## htaccess file configuration
RewriteBase /
RewriteEngine On
RewriteRule ^(.*)$ public/index.php [QSA,L]

Could anyone please me to resolve the issue?

**Comment by trasher** [comment]
Probably solved as of https://github.com/glpi-project/glpi/pull/14503
