### ISSUE TITLE
do not collect mail (Oauth IMAP Azure) GLPI 9.5.7

### ISSUE THREAD

**Issue by pierlaze** [glpi-project/glpi#14555]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 9.5.7

### Bug description

I have the same problem, connection error 1, I have Oauth configured with Azure. Out of nowhere it stopped working, your help please
![image](https://user-images.githubusercontent.com/106604012/232823127-9958bbcc-4e20-47bf-8ac4-c485ad787e99.png)
![image](https://user-images.githubusercontent.com/106604012/232823164-d5c13341-af60-40c0-9e30-18e34b2ba58a.png)

**Comment by StbanMc** [comment]
No found
