### ISSUE TITLE
Rule criteria fails when searching for a string which contains a single quote

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#14557]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

The rules engine fails to search for a string containing a single quote using a rule criteria.

### Page URL

front/ticket.form.php

### Steps To reproduce

1. Create a ITIL category
2. Create a business rule
3. Add a rule criteria : description contains ```doesn't works```
4. add a rule action to assign the ITIL category of step 1 to the ticket
5. enable the rule
6. create a ticket which contains in the description the string ```doesn't works```
7. See the business rule is not applied

### Anything else?

In the class RuleCriteria (https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/RuleCriteria.php#L470)

the variable ```$pattern``` has the single quote escaped, but the variable ```$field```, containing the description of the ticket does not have single quotes escaped.

![image](https://user-images.githubusercontent.com/14139801/232838379-736b31f3-e508-49e7-a897-83623681548f.png)

**Comment by cedric-anne** [comment]
According to method comments, input should not contain slashes.
https://github.com/glpi-project/glpi/blob/cfb661237ccd9d34d1f90c129ebde83652b3e301/src/RuleCollection.php#L1587-L1598

Unless there is a simple and clear solution to this problem, I am not really confident to change the way we handle slashes here. This problem will be fixed by #14302 .

**Comment by btry** [comment]
Hi @cedric-anne

I also saw this comment and it confirms the idea I implemented in #14558. What do you think about it ?

**Comment by cedric-anne** [comment]
I saw it just after adding my comment. We will follow the discussion there.

**Comment by btry** [comment]
Cannot fully solve the encoding differences between pattern in rule criterias and string from ticket to compare. we need to wait GLPI 10.1 which will drop encoding mess.
