### ISSUE TITLE
receiver error 

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1456]
Hello,

 I would like to use a sub folder for receiver but it does not work.

it works when inbox is selected but not with a subfolder

![image](https://cloud.githubusercontent.com/assets/15144026/21427551/7ec3ea54-c855-11e6-859a-4f5d5dda9762.png)

![image](https://cloud.githubusercontent.com/assets/15144026/21427608/cbeab1a0-c855-11e6-8d26-d0766c1d6fc3.png)

error in phplog :

2016-12-22 14:40:26 [854@UNGSRVGVA218]
  *** PHP Notice(8): Unknown: Can't open mailbox {ungsrvgva171:110/pop/novalidate-cert/tls/debug}Inbox\GLPI\: invalid remote specification (errflg=2)
  Backtrace :

**Comment by satyan01** [comment]
test en imap erreur 

2016-12-22 17:04:47 [854@UNGSRVGVA218]
  *** PHP Notice(8): Unknown: Too many login failures (errflg=2)
  Backtrace :
  :

**Comment by satyan01** [comment]
pop works correctly but I need to use IMAP

**Comment by satyan01** [comment]
solved by imap using

**Comment by moalkaabi** [comment]
Hi Satyan , 
I have same as your issue . please share with me your solution as I 'm struggling since I upgraded my Exchange Server .

**Comment by snakewqq** [comment]
I have same as your issue
