### ISSUE TITLE
No "Account" tab for the database plugin integrated to GLPI 10

### ISSUE THREAD

**Issue by naif0s** [glpi-project/glpi#14589]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hello, 

Here is the bug: 

on GLPI 9.5, there was the tab "account" when I clicked on a database with the plugin account then I wanted to migrate on the version 10...

![Capture d’écran 2023-04-25 164339](https://user-images.githubusercontent.com/94651813/234314092-204e783b-5106-402d-8e6e-2efc64a9c5b9.png)

Except that in the version, already the section where was located all the databases are found in "database instances", that I do not understand why? 

And then when I click on any database in version 10 of GLPI no tab account? 

![2](https://user-images.githubusercontent.com/94651813/234315166-ba4e7257-16b9-4968-8484-25fdde745637.png)

### Page URL

/front/databaseinstance.form.php?id=171&

### Your GLPI setup information

GLPI 10.0.7 ( => /var/www/html)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cedric-anne** [comment]
Hi,

The `Account` tab is managed by the `accounts` plugin. Please open an issue on the plugin repository: https://github.com/InfotelGLPI/accounts
