### ISSUE TITLE
Please add a word translation

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1458]
Hello, 
not translated words:

![glpi - computer - google chrome 2016-12-23 10 03 19](https://cloud.githubusercontent.com/assets/17082164/21448775/38af64c4-c8f7-11e6-9d56-2f766395ce8e.png)

**Comment by AircraftRu** [comment]
Knowledge base
![glpi - - google chrome 2017-04-10 11 17 24](https://cloud.githubusercontent.com/assets/17082164/25393445/2673d058-29e4-11e7-9527-6e07eca7250a.png)

**Comment by trasher** [comment]
Thos ones are translated, this is part of tinymce. Don't know why you do not see them translmated, but they're not missing.

**Comment by AircraftRu** [comment]
@trasher Where are translated?

**Comment by trasher** [comment]
In tinymce translations: https://github.com/glpi-project/glpi/blob/9.1/bugfixes/lib/tiny_mce/langs/
Seems that all files are not at the same level.

**Comment by AircraftRu** [comment]
Thank you. But.... how it decode? and it will translate?

**Comment by AircraftRu** [comment]
It seems to be translated and should work, but it does not work.

**Comment by trasher** [comment]
No, this is translated in `ru.js` file; but not in the `ru_RU.js` one (which is the one used). As a workaround, you can try to remove the `ru_RU.js` file.

**Comment by trasher** [comment]
Fixed from #2126
