### ISSUE TITLE
Lack of requester after ticket creation

### ISSUE THREAD

**Issue by mabuchiplm** [glpi-project/glpi#14582]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

User is not attached as requester after ticket creation via self simplified portal. Pre-select me as Requester when Creating Ticket is active. Notification about ticket creation is not generating. When request is creating by Technician everythink is working fine.

![glpi1](https://user-images.githubusercontent.com/131663322/233977177-31f5f660-752f-4168-8ab2-53048713d028.jpg)

**Comment by cedric-anne** [comment]
Hi,

Could you try to upgrade to GLPI 10.0.7 to see if issue persists?

**Comment by mabuchiplm** [comment]
No, I didn't.
But I've found if RoundRobin plugin is active then is removing somehow user from requester field. If I turn it off then users is corectly attached but tiecket is not assigning to a technician
