### ISSUE TITLE
No ticket information is displayed using mail receiver.

### ISSUE THREAD

**Issue by eramos13** [glpi-project/glpi#14585]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I use the mail receiver to generate tickets automatically, but it happens in some cases that the capture that the user sends by mail is not shown in the ticket and blocks all the other information, but it is shown in the ticket preview.

![tk_253](https://user-images.githubusercontent.com/73493165/234055071-9b7f55c1-7ca2-415f-9c61-4ea228faf861.jpg)
![tk_253_1](https://user-images.githubusercontent.com/73493165/234055201-c293cef0-ee8e-45b7-898d-5aefd45f2468.jpg)

### Your GLPI setup information

<details close>
<summary>Server</summary>
Operating system: Linux 584fa0617a50 4.18.0-425.10.1.el8_7.x86_64 #1 SMP Wed Dec 14 16:00:01 EST 2022 x86_64<br>
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,<br>
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap,<br>
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, sockets, sodium, <br>standard,<br>
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)<br>
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"<br>
	upload_max_filesize="2M" <br>
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi.oefa.gob.pe Port 80<br>
)<br>
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36<br>
Server Software: mariadb.org binary distribution<br>
	Server Version: 10.7.8-MariaDB-1:10.7.8+maria~ubu2004<br>
	Server SQL Mode: <br>STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION<br>
	Parameters: glpi@glpi-mariadb/glpibd<br>
	Host info: glpi-mariadb via TCP/IP<br>
<p>

- PHP version (7.4.33) is supported.PHP version (7.4.33) is supported.
- Sessions configuration is OK.Sessions configuration is OK.
- Allocated memory is sufficient.Allocated memory is sufficient.
- mysqli extension is installed.mysqli extension is installed.
- Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
- curl extension is installed.curl extension is installed.
- gd extension is installed.gd extension is installed.
- intl extension is installed.intl extension is installed.
- libxml extension is installed.libxml extension is installed.
- zlib extension is installed.zlib extension is installed.
- The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
- Database engine version (10.7.8) is supported.Database engine version (10.7.8) is supported.
- No files from previous GLPI version detected.No files from previous GLPI version detected.
- The log file has been created successfully.The log file has been created successfully.
- Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
- Write access to /var/www/html/glpi/config has been validated.
- Write access to /var/www/html/glpi/files/_cron has been validated.
- Write access to /var/www/html/glpi/files has been validated.
- Write access to /var/www/html/glpi/files/_dumps has been validated.
- Write access to /var/www/html/glpi/files/_graphs has been validated.
- Write access to /var/www/html/glpi/files/_lock has been validated.
- Write access to /var/www/html/glpi/files/_pictures has been validated.
- Write access to /var/www/html/glpi/files/_plugins has been validated.
- Write access to /var/www/html/glpi/files/_rss has been validated.
- Write access to /var/www/html/glpi/files/_sessions has been validated.
- Write access to /var/www/html/glpi/files/_tmp has been validated.
- Write access to /var/www/html/glpi/files/_uploads has been validated.
- PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
- Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
- The following directories should be placed outside "/var/www/html/glpi": ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".The following directories should be placed outside "/var/www/html/glpi":
- ‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
- ‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
- You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".
- PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
- OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
- exif extension is installed.exif extension is installed.
- ldap extension is installed.ldap extension is installed.
- openssl extension is installed.openssl extension is installed.
- Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
- Zend OPcache extension is installed.Zend OPcache extension is installed.
- Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
- Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
- Timezones seems loaded in database.Timezones seems loaded in database.

	

</details>

<details close>
<summary>GLPI Constans</summary>

- GLPI_ROOT: "/var/www/html/glpi"
- GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
- GLPI_VAR_DIR: "/var/www/html/glpi/files"
- GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
- GLPI_USE_CSRF_CHECK: "1"
- GLPI_CSRF_EXPIRES: "7200"
- GLPI_CSRF_MAX_TOKENS: "100"
- GLPI_USE_IDOR_CHECK: "1"
- GLPI_IDOR_EXPIRES: "7200"
- GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
- GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
- GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
- GLPI_INSTALL_MODE: "TARBALL"
- GLPI_NETWORK_MAIL: "glpi@teclib.com"
- GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
- GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
- GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
- GLPI_USER_AGENT_EXTRA_COMMENTS: ""
- GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
- GLPI_AJAX_DASHBOARD: "1"
- GLPI_CALDAV_IMPORT_STATE: 0
- GLPI_DEMO_MODE: "0"
- GLPI_CENTRAL_WARNINGS: "1"
- GLPI_DOC_DIR: "/var/www/html/glpi/files"
- GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
- GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
- GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
- GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
- GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
- GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
- GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
- GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
- GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
- GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
- GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
- GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
- GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
- GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
- GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
- GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
- GLPI_I18N_DIR: "/var/www/html/glpi/locales"
- GLPI_VERSION: "10.0.7"
- GLPI_SCHEMA_VERSION: "10.0.7"
- GLPI_MARKETPLACE_PRERELEASES: false
- GLPI_MIN_PHP: "7.4.0"
- GLPI_MAX_PHP: "8.3.0"
- GLPI_YEAR: "2023"

</details>

<details close>
<summary>Libraries</summary>

- htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
- phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
- simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
- tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/marketplace/pdf/vendor/tecnickcom/tcpdf)
- michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
- true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
- iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
- sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
- sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
- sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
- sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
- laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
- laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
- monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
- sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
- donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
- elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
- symfony/console in (/var/www/html/glpi/vendor/symfony/console)
- scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
- laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
- laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
- rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
- blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
- ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
- psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
- psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
- psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
- league/csv in (/var/www/html/glpi/vendor/league/csv/src)
- mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
- guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
- guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
- glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
- wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
- paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
- symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
- html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
- symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
- symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
- twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
- twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
- symfony/polyfill-ctype not found
- symfony/polyfill-iconv not found
- symfony/polyfill-mbstring not found
- symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
- symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
- symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
- league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
- league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
- thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
- phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</details>

**Comment by eramos13** [comment]
I add information, apparently the error is at the moment that processes the mail receiver, because I made a test reprocessing an email that before had this problem and this time if I process it normally.

**Comment by cedric-anne** [comment]
Hi,

Do you have some logs added in `files/_log/php-errors.log` when ticket page is displayed?

**Comment by eramos13** [comment]
> Hi,
> 
> Do you have some logs added in `files/_log/php-errors.log` when ticket page is displayed?

I was able to find this in the logs. Also, I want to add information, it does not only happen with tickets created by the mail receiver, it also happens if a ticket is created from the create request menu.

<details close
<summary>php logs</summary>

[2023-04-24 12:34:51] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 2 passed to Glpi\Application\View\Extension\ItemtypeExtension::getItem() must be of the type int, null given, called in /var/www/html/glpi/files/_cache/templates/28/2881732e3f44f9a051dc4ba0f28fbc6fa297abf137c0ffd01f18facb311dbc69.php on line 91 in /var/www/html/glpi/src/Application/View/Extension/ItemtypeExtension.php at line 164
  Backtrace :
  ...f28fbc6fa297abf137c0ffd01f18facb311dbc69.php:91 Glpi\Application\View\Extension\ItemtypeExtension->getItem()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_e522b0bf4930da4934420808a31a80d32943246bfb3eb2d1ce0fe884bc888e29->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1347 Twig\TemplateWrapper->render()
  ...74f3507f13a40a625f7d40b8f05014f86e64625.php:131 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_f39f984177f4bd95bcc9c995a37d1db01c8857c3f2dfebb1f0cc4d0281a240d2->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:179      Twig\TemplateWrapper->display()
  src/Ticket.php:4405                                Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()

</details>

**Comment by cedric-anne** [comment]
Hi,

Sorry for the late reply.

Could you test to reproduce with no active plugins?
If you can still reproduce without any active plugin, could you apply following patch and provide generated error log when you access tickets that cause this issue?

```diff
diff --git a/src/Application/View/Extension/ItemtypeExtension.php b/src/Application/View/Extension/ItemtypeExtension.php
index 6942d7db7d..ec52e4ff30 100644
--- a/src/Application/View/Extension/ItemtypeExtension.php
+++ b/src/Application/View/Extension/ItemtypeExtension.php
@@ -161,8 +161,12 @@ class ItemtypeExtension extends AbstractExtension
      *
      * @return CommonDBTM|null
      */
-    public function getItem($itemtype, int $id): ?CommonDBTM
+    public function getItem($itemtype, $id): ?CommonDBTM
     {
+        if ($id === null) {
+            trigger_error(sprintf('Invalid id `null` for itemtype `%s`.', $itemtype), E_USER_WARNING);
+            return null;
+        }
         if (is_a($itemtype, CommonDBTM::class, true) && ($item = $itemtype::getById($id)) !== false) {
             return $item;
         }
```

**Comment by eramos13** [comment]
> Hi,
> 
> Sorry for the late reply.
> 
> Could you test to reproduce with no active plugins? If you can still reproduce without any active plugin, could you apply following patch and provide generated error log when you access tickets that cause this issue?
> 
> ```diff
> diff --git a/src/Application/View/Extension/ItemtypeExtension.php b/src/Application/View/Extension/ItemtypeExtension.php
> index 6942d7db7d..ec52e4ff30 100644
> --- a/src/Application/View/Extension/ItemtypeExtension.php
> +++ b/src/Application/View/Extension/ItemtypeExtension.php
> @@ -161,8 +161,12 @@ class ItemtypeExtension extends AbstractExtension
>       *
>       * @return CommonDBTM|null
>       */
> -    public function getItem($itemtype, int $id): ?CommonDBTM
> +    public function getItem($itemtype, $id): ?CommonDBTM
>      {
> +        if ($id === null) {
> +            trigger_error(sprintf('Invalid id `null` for itemtype `%s`.', $itemtype), E_USER_WARNING);
> +            return null;
> +        }
>          if (is_a($itemtype, CommonDBTM::class, true) && ($item = $itemtype::getById($id)) !== false) {
>              return $item;
>          }
> ```


Hi. Apply the patch with inactive plugins and the problem ticket is displayed without problems. 

![Screenshot_6](https://github.com/glpi-project/glpi/assets/73493165/4b69d98d-cd1f-43b2-9275-4c6caadf62de)
<details close
<summary>php logs</summary>

[2023-06-16 12:42:52] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid id `null` for itemtype `Document_Item`. in /var/www/html/glpi/src/Application/View/Extension/ItemtypeExtension.php at line 175
  Backtrace :
  ...cation/View/Extension/ItemtypeExtension.php:175 trigger_error()
  ...f28fbc6fa297abf137c0ffd01f18facb311dbc69.php:91 Glpi\Application\View\Extension\ItemtypeExtension->getItem()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_e522b0bf4930da4934420808a31a80d32943246bfb3eb2d1ce0fe884bc888e29->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379              Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:40        Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1347 Twig\TemplateWrapper->render()
  ...74f3507f13a40a625f7d40b8f05014f86e64625.php:131 twig_include()
  vendor/twig/twig/src/Template.php:394              __TwigTemplate_f39f984177f4bd95bcc9c995a37d1db01c8857c3f2dfebb1f0cc4d0281a240d2->doDisplay()
  vendor/twig/twig/src/Template.php:367              Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:47        Twig\Template->display()
  src/Application/View/TemplateRenderer.php:179      Twig\TemplateWrapper->display()
  src/Ticket.php:4405                                Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()

</details>

**Comment by cedric-anne** [comment]
Hi,

Thanks for the feedback. Could you test patch proposed in #14953?
Also, it it possible for you to provide the original e-mail, into `.eml` format, so I could try to reproduce the initial bug (it seems that a document has been incorrectly imported)?

**Comment by eramos13** [comment]
> Hi,
> 
> Thanks for the feedback. Could you test patch proposed in #14953? Also, it it possible for you to provide the original e-mail, into `.eml` format, so I could try to reproduce the initial bug (it seems that a document has been incorrectly imported)?

Hi, the screenshot I sent in my last reply does not correspond to a ticket created by the mail collector, it is a ticket created from the GLPI portal. This failure has happened to me in both cases, even creating tickets using the forms plugin. I have just run the automatic action of cleanorphans to remove orphaned documents.

**Comment by cedric-anne** [comment]
Could you test patch proposed in https://github.com/glpi-project/glpi/pull/14953?

**Comment by trasher** [comment]
No feedback, this should be fixed.
