### ISSUE TITLE
Sub-entities can see each other from one neighboring entity to another

### ISSUE THREAD

**Issue by SI-AURAL** [glpi-project/glpi#14590]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Neighboring entities can see each other.

Example : 
Root Entity
--- Entity L1
--- --- Sub L1'entity
--- Entity L2
--- --- Sub L2'entity

The L2 entity and all its sub-entities can actually be seen by the L1 entity whereas the entities, sub-entities and data of the L2 entity must not be visible to the L1 entity.

From Entity L1, we can see Sub Entity L2 from list but we are not able to edit it, when we want to edit, there is a log output (attached bellow)

### Relevant log output

```shell
User ID: 2 tried to access or perform an action on /front/entity.form.php?id=2 with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /srv/www/prod/glpi/glpi_web/src/CommonDBTM.php:6354 displayRightError()
                /srv/www/prod/glpi/glpi_web/src/CommonDBTM.php:6444 displayAccessDeniedPage()
                /srv/www/prod/glpi/glpi_web/front/dropdown.common.form.php:176 displayFullPageForItem()
                /srv/www/prod/glpi/glpi_web/front/entity.form.php:52 include()
                /srv/www/prod/glpi/glpi_web/public/index.php:73 require()
```

### Page URL

/front/entity.php

### Steps To reproduce

1. Go to Administration > Entities
2. Create some entities and sub entities.
3. Change entity from user menu (top corner right)
4. See other entities who seems not to be visible.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.7 ( => /srv/www/prod/glpi/glpi_web)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux srv-parc.ad.auralyon.fr 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 8.2.5 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, random, readline, session, shmop, snmp, soap,
	sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at glpi.ad.auralyon.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.18-MariaDB-0+deb11u1-log
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_prod@localhost/glpi_prod
	Host info: Localhost via UNIX socket
	
PHP version (8.2.5) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.18) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_cache has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/config/ has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_cron has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_docs has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_dumps has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_graphs has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_lock has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_pictures has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_plugins has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_rss has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_sessions has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_tmp has been validated.
Write access to /srv/www/prod/glpi/glpi_conf_data/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /srv/www/prod/glpi/glpi_web/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/srv/www/prod/glpi/glpi_web"
GLPI_CONFIG_DIR: "/srv/www/prod/glpi/glpi_conf_data/config/"
GLPI_VAR_DIR: "/srv/www/prod/glpi/glpi_conf_data/files"
GLPI_DOC_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_docs"
GLPI_CRON_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_cron"
GLPI_DUMP_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_dumps"
GLPI_GRAPH_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_graphs"
GLPI_LOCK_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_lock"
GLPI_PICTURE_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_plugins"
GLPI_RSS_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_rss"
GLPI_SESSION_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_sessions"
GLPI_TMP_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_tmp"
GLPI_UPLOAD_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_uploads"
GLPI_CACHE_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_cache"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/srv/www/prod/glpi/glpi_web/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_LOCAL_I18N_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_locales"
GLPI_INVENTORY_DIR: "/srv/www/prod/glpi/glpi_conf_data/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/srv/www/prod/glpi/glpi_web/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/srv/www/prod/glpi/glpi_web/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/srv/www/prod/glpi/glpi_web/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/srv/www/prod/glpi/glpi_web/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/srv/www/prod/glpi/glpi_web/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/srv/www/prod/glpi/glpi_web/vendor/michelf/php-markdown/Michelf)
true/punycode in (/srv/www/prod/glpi/glpi_web/vendor/true/punycode/src)
iamcal/lib_autolink in (/srv/www/prod/glpi/glpi_web/vendor/iamcal/lib_autolink)
sabre/dav in (/srv/www/prod/glpi/glpi_web/vendor/sabre/dav/lib/DAV)
sabre/http in (/srv/www/prod/glpi/glpi_web/vendor/sabre/http/lib)
sabre/uri in (/srv/www/prod/glpi/glpi_web/vendor/sabre/uri/lib)
sabre/vobject in (/srv/www/prod/glpi/glpi_web/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/srv/www/prod/glpi/glpi_web/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/srv/www/prod/glpi/glpi_web/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/srv/www/prod/glpi/glpi_web/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/srv/www/prod/glpi/glpi_web/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/srv/www/prod/glpi/glpi_web/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/srv/www/prod/glpi/glpi_web/vendor/elvanto/litemoji/src)
symfony/console in (/srv/www/prod/glpi/glpi_web/vendor/symfony/console)
scssphp/scssphp in (/srv/www/prod/glpi/glpi_web/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/srv/www/prod/glpi/glpi_web/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/srv/www/prod/glpi/glpi_web/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/srv/www/prod/glpi/glpi_web/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/srv/www/prod/glpi/glpi_web/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/srv/www/prod/glpi/glpi_web/vendor/ramsey/uuid/src)
psr/log in (/srv/www/prod/glpi/glpi_web/vendor/psr/log/Psr/Log)
psr/simple-cache in (/srv/www/prod/glpi/glpi_web/vendor/psr/simple-cache/src)
psr/cache in (/srv/www/prod/glpi/glpi_web/vendor/psr/cache/src)
league/csv in (/srv/www/prod/glpi/glpi_web/vendor/league/csv/src)
mexitek/phpcolors in (/srv/www/prod/glpi/glpi_web/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/srv/www/prod/glpi/glpi_web/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/srv/www/prod/glpi/glpi_web/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/srv/www/prod/glpi/glpi_web/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/srv/www/prod/glpi/glpi_web/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/srv/www/prod/glpi/glpi_web/vendor/paragonie/sodium_compat/src)
symfony/cache in (/srv/www/prod/glpi/glpi_web/vendor/symfony/cache)
html2text/html2text in (/srv/www/prod/glpi/glpi_web/vendor/html2text/html2text/src)
symfony/css-selector in (/srv/www/prod/glpi/glpi_web/vendor/symfony/css-selector)
symfony/dom-crawler in (/srv/www/prod/glpi/glpi_web/vendor/symfony/dom-crawler)
twig/twig in (/srv/www/prod/glpi/glpi_web/vendor/twig/twig/src)
twig/string-extra in (/srv/www/prod/glpi/glpi_web/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/srv/www/prod/glpi/glpi_web/vendor/symfony/polyfill-php82)
league/oauth2-client in (/srv/www/prod/glpi/glpi_web/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/srv/www/prod/glpi/glpi_web/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/srv/www/prod/glpi/glpi_web/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://ad.auralyon.fr', Port: '389', BaseDN: 'OU=AURALYON,DC=ad,DC=auralyon,DC=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=SVC_GLPI,OU=Comptes Services,OU=AURALYON,DC=ad,DC=auralyon,DC=fr', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (anonymous@mail.auralyon.fr)

</pre></details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertes                        Version: 1.10.6     State: Enabled                                 
		Install Method: Marketplace
	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.20.5     State: Enabled                                 
		Install Method: Marketplace
	timelineticket       Name: Chronologie des tickets        Version: 10.0+1.1   State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Cycle de vie des matériels (un Version: 2.8.1      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.1.4      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.0     State: Enabled                                 
		Install Method: Marketplace
	purchaserequest      Name: Demande d'achat                Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	consumables          Name: Demande de consommables        Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	archimap             Name: Diagrammes                     Version: 3.2.20     State: Enabled                                 
		Install Method: Marketplace
	dataflows            Name: Flux de données                Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.14.2     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.10.3     State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	tasklists            Name: Liste des tâches               Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	metademands          Name: Meta-Demandes                  Version: 3.2.19     State: Enabled                                 
		Install Method: Marketplace
	releases             Name: Mises en production            Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	satisfaction         Name: Plus de satisfaction           Version: 1.6.1      State: Enabled                                 
		Install Method: Marketplace
	statecheck           Name: Régles de vérification d'état  Version: 2.3.9      State: Enabled                                
		 Install Method: Marketplace
	archisw              Name: Structures d'Applications      Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

### Anything else?

Hope I understand how entities works.
Root Entity got ID = 0 in database. Not sure but Root Entity's ID must not be 1 ?

**Comment by SI-AURAL** [comment]
![1](https://user-images.githubusercontent.com/108948325/234535472-ea915d53-de82-4420-8b6b-8931b2e09196.PNG)
![2](https://user-images.githubusercontent.com/108948325/234535466-8f8edba3-efcb-4349-9f87-365aa2b7ed3c.PNG)
![3](https://user-images.githubusercontent.com/108948325/234535469-4337b57f-50d8-4e55-ba37-bc651544059d.PNG)

To illustrate my point, there is 3 screenshots : 
- Picture 1 : I'm on the root Entity (tree structure view) : here it's normal to view Root entity + all sub entities from root
- Picture 2 : On the Entity L1 (called "Assistance", tree structure view) : here, I should only view "Assistance" named entity (L1) + all sub entities like "Service Informatique" from "Assistance" + read only Root Entity 
- Picture 3 : On the Entity L2 (called "Opérationnel", tree structure view) : here, I should only view "Opérationnel" named entity (L2) + all sub entities like "Service Informatique" from "Opérationnel" + read only Root Entity

The two sub entities from root entity should be compartmentalized. However, this is my understanding of how an entity works, not sure if this is what is originally intended.

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce the issue. When changing the current entity, I ony see this entity and its children.

Do you still have an issue with this? If issue persist, could your try to reproduce, on a fresh installation on test server, using the [latest nightly build](https://nightly.glpi-project.org/glpi/10.0.tar.gz)?

**Comment by SI-AURAL** [comment]
Hi Cedric-Anne

I've already reinstall before submit ticket, same problem.
I've the last version of GLPI.

I can see sub-entities but not manage them(error logged as insufficient rights).
Neighboring entities are not supposed to be visible to each other if the rights do not allow them to be managed.
I should only see sub-entities and not neighboring entities.

**Comment by SI-AURAL** [comment]
[https://forum.glpi-project.org/viewtopic.php?id=286912](https://forum.glpi-project.org/viewtopic.php?id=286912)

I posted the same ticket in French with a bit more explanation

**Comment by cedric-anne** [comment]
I just tried to install a new GLPI instance, created 2 branches in the entity tree, and I am not able to reproduce:

![image](https://github.com/glpi-project/glpi/assets/33253653/187171a6-1c6b-450f-845d-141670d73f8f)

Could you try to clear the cache (in debug mode, using Setup > General > Performances > User data cache > reset button), and deactivate all plugins to see if problem persist?

**Comment by SI-AURAL** [comment]
When you click on >> beside Test A

**Comment by cedric-anne** [comment]
> When you click on >> beside Test A The goal is to have the entity (test A) and its children (Test A1, Test A2 etc...) in 1 single view, not only "Test A".

That is what I have done, see my screenshot.

Could you try to clear the cache (in debug mode, using Setup > General > Performances > User data cache > reset button), and deactivate all plugins to see if problem persist?

**Comment by SI-AURAL** [comment]
> > When you click on >> beside Test A The goal is to have the entity (test A) and its children (Test A1, Test A2 etc...) in 1 single view, not only "Test A".
> 
> That is what I have done, see my screenshot.
> 
> Could you try to clear the cache (in debug mode, using Setup > General > Performances > User data cache > reset button), and deactivate all plugins to see if problem persist?

Thanks, it works! 👍 
Your trick with deleting the cache solved my problem. I was not aware that this option existed.
