### ISSUE TITLE
GLPi 10.0.7 + Web server root directory configuration + GLPi native inventory

### ISSUE THREAD

**Issue by javivu** [glpi-project/glpi#14595]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

OLD CONFIG:
- GLPi 10.0.6 + ubuntu 22.04 + PHP 8.1 + Apache 2
   Install folder /var/www/html/glpi
   Apache config: DocumentRoot /var/www/html
  GLPi URL http://glpi.domain.local/glpi
- GLPI Inventory 1.2.1 
  GLPi Agent 1.4 install env   SERVER=http://glpi.domain.local/glpi/front/inventory.php

NEW CONFIG (changed version and DocumentRoot path):
- GLPi 10.0.7 + ubuntu 22.04 + PHP 8.1 + Apache 2
   Install folder /var/www/html/glpi
   Apache config: DocumentRoot /var/www/html/glpi/public
  GLPi URL http://glpi.domain.local/
- GLPI Inventory 1.2.1 
  GLPi Agent 1.4 install env SERVER=http://glpi.domain.local/glpi/front/inventory.php
  
I'm not sure how to modify the rewrite rules in Apache2 to not re-install o reconfigure SERVER in the GLPi agent
I use the https://glpi-install.readthedocs.io/en/latest/prerequisites.html#apache-configuration to change the Apache config, but the GLPi Agent can not connect to sever.

Thanks

### Relevant log output

```shell
[Tue Apr 25 17:13:43 2023][info] target server0: server http://glpi.domain.local/glpi/front/inventory.php
[Tue Apr 25 17:13:43 2023][info] sending prolog request to server0
[Tue Apr 25 17:13:43 2023][error] [http client] communication error: 403 Forbidden
[Tue Apr 25 17:13:43 2023][error] No answer from server at http://glpi.domain.local/glpi/front/inventory.php
```

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.7 (/glpi => /var/www/html/glpi_10.0.7)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux srv-glpi 5.15.0-70-generic #77-Ubuntu SMP Tue Mar 21 14:02:37 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at glpi.birdlandco.com Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.01/glpi
	Host info: 127.0.01 via TCP/IP
	
PHP version (8.1.2-1ubuntu2.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi_10.0.7/files/_cache has been validated.
Write access to /var/www/html/glpi_10.0.7/config has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_cron has been validated.
Write access to /var/www/html/glpi_10.0.7/files has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_dumps has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_graphs has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_lock has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_pictures has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_plugins has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_rss has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_sessions has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_tmp has been validated.
Write access to /var/www/html/glpi_10.0.7/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/html/glpi_10.0.7":
‣ "/var/www/html/glpi_10.0.7/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi_10.0.7/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/html/glpi_10.0.7/public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi_10.0.7/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi_10.0.7"
GLPI_CONFIG_DIR: "/var/www/html/glpi_10.0.7/config"
GLPI_VAR_DIR: "/var/www/html/glpi_10.0.7/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi_10.0.7/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi_10.0.7/files"
GLPI_CACHE_DIR: "/var/www/html/glpi_10.0.7/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi_10.0.7/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi_10.0.7/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi_10.0.7/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi_10.0.7/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi_10.0.7/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi_10.0.7/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi_10.0.7/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi_10.0.7/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi_10.0.7/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi_10.0.7/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi_10.0.7/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi_10.0.7/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi_10.0.7/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi_10.0.7/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi_10.0.7/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi_10.0.7/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi_10.0.7/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi_10.0.7/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi_10.0.7/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi_10.0.7/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi_10.0.7/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi_10.0.7/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi_10.0.7/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi_10.0.7/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi_10.0.7/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi_10.0.7/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi_10.0.7/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi_10.0.7/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi_10.0.7/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi_10.0.7/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi_10.0.7/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi_10.0.7/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi_10.0.7/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi_10.0.7/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi_10.0.7/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi_10.0.7/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi_10.0.7/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi_10.0.7/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi_10.0.7/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi_10.0.7/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi_10.0.7/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi_10.0.7/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi_10.0.7/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi_10.0.7/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi_10.0.7/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi_10.0.7/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi_10.0.7/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi_10.0.7/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi_10.0.7/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi_10.0.7/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi_10.0.7/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi_10.0.7/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi_10.0.7/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi_10.0.7/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi_10.0.7/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi_10.0.7/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi_10.0.7/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi_10.0.7/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'SRV-ADM-BL', Port: '389', BaseDN: 'OU=Birdland,OU=AD-Users,DC=AMUSE,DC=LOCAL', Connection filter: none, RootDN:
		'glpibind@amuse.local', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (soporte@amuseanimation.com@smtp.gmail.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Additional fields              Version: 1.20.5     State: Enabled                                 
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.13.0     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Not installed                           
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.11.1     State: Enabled                                 
		Install Method: Marketplace
	webresources         Name: Web Resources                  Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details><details><summary>Locales overrides</summary><pre></pre></details>

**Comment by cedric-anne** [comment]
Hi,

Maybe `AliasMatch "^/glpi/front/inventory.php$" "/var/www/html/glpi/front/inventory.php"`.
