### ISSUE TITLE
Missing rights to view attached document

### ISSUE THREAD

**Issue by chnateag** [glpi-project/glpi#14598]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When an user is trying to open a document in a ticket it opens, if he click again on it he has an error which says "you don't have rights..." 

### Relevant log output

```shell
==> /home/web/glpi/files/_log/access-errors.log <==
                /home/web/glpi/front/unmanaged.php:38 checkRight()
2023-04-26 17:44:48 [@TEMPOv-GLPI]
CSRF check failed for User ID:  at /front/login.php2023-04-27 07:32:45 [47@TEMPOv-GLPI]
CSRF check failed for User ID: 47 at /ajax/genericdate.php2023-04-27 07:33:08 [47@TEMPOv-GLPI]
CSRF check failed for User ID: 47 at /ajax/genericdate.php2023-04-27 09:43:53 [134@TEMPOv-GLPI]
User ID: 134 tried to access or perform an action on /front/ticket.form.php?id=6825& with insufficient rights. Additional information: Missing READ right. Cannot view the item.
        Stack Trace:
                /home/web/glpi/src/CommonDBTM.php:6354 displayRightError()
                /home/web/glpi/src/CommonDBTM.php:6444 displayAccessDeniedPage()
                /home/web/glpi/front/ticket.form.php:259 displayFullPageForItem()
```

```
User ID: 573 tried to access or perform an action on /front/unmanaged.php with insufficient rights. Additional information: User is missing the 1 (READ) right for unmanaged
        Stack Trace:
                /home/web/glpi/src/Session.php:1039 displayRightError()
                /home/web/glpi/front/unmanaged.php:38 checkRight(

```

### Steps To reproduce

Nothing much complicated :
- create a ticket in specific entity
- upload a pdf document
- clic on it

### Your GLPI setup information

Operating system: Linux TEMPOv-GLPI 5.10.0-19-amd64 #1 SMP Debian 5.10.149-2 (2022-10-21) x86_64
PHP 8.1.18 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="512M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi.tempo-one.com Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Server Software: Debian 11
	Server Version: 10.5.15-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.18) is supported.PHP version (8.1.18) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.15) is supported.Database engine version (10.5.15) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /home/web/glpi/files/_cache has been validated. Write access to /home/web/glpi/config has been validated. Write access to /home/web/glpi/files/_cron has been validated. Write access to /home/web/glpi/files has been validated. Write access to /home/web/glpi/files/_dumps has been validated. Write access to /home/web/glpi/files/_graphs has been validated. Write access to /home/web/glpi/files/_lock has been validated. Write access to /home/web/glpi/files/_pictures has been validated. Write access to /home/web/glpi/files/_plugins has been validated. Write access to /home/web/glpi/files/_rss has been validated. Write access to /home/web/glpi/files/_sessions has been validated. Write access to /home/web/glpi/files/_tmp has been validated. Write access to /home/web/glpi/files/_uploads has been validated.Write access to /home/web/glpi/files/_cache has been validated.
Write access to /home/web/glpi/config has been validated.
Write access to /home/web/glpi/files/_cron has been validated.
Write access to /home/web/glpi/files has been validated.
Write access to /home/web/glpi/files/_dumps has been validated.
Write access to /home/web/glpi/files/_graphs has been validated.
Write access to /home/web/glpi/files/_lock has been validated.
Write access to /home/web/glpi/files/_pictures has been validated.
Write access to /home/web/glpi/files/_plugins has been validated.
Write access to /home/web/glpi/files/_rss has been validated.
Write access to /home/web/glpi/files/_sessions has been validated.
Write access to /home/web/glpi/files/_tmp has been validated.
Write access to /home/web/glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/home/web/glpi": ‣ "/home/web/glpi/files" ("GLPI_VAR_DIR") ‣ "/home/web/glpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "/home/web/glpi/public".The following directories should be placed outside "/home/web/glpi":
‣ "/home/web/glpi/files" ("GLPI_VAR_DIR")
‣ "/home/web/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/home/web/glpi/public".
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/web/glpi/marketplace has been validated.Write access to /home/web/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

### Anything else?

Look likes its linked to this issue https://github.com/glpi-project/glpi/issues/14590 ?

It's happening to only one user who is super-admin, i am too and am not having this issue

**Comment by cedric-anne** [comment]
Hi,

Provided log does not seems related to any document opening.

Does the problem persist? Maybe it was a session issue.

**Comment by chnateag** [comment]
the issue seems to have disappeared with directory structure change, we moved files/ config/ and log/ as recommended out of glpi's directory
thanks
