### ISSUE TITLE
Need to allow massive actions to open another Window

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#146]
I don't find the solution, for massive action, to open another Window.
Use case: PDF plugin need this.

As the "form" is managed by GLPI, target can't be set for a specific action.

And JQuery is outside my skill ;)
(I have tried various solution from Internet ans JQuery documentation, without success).

**Comment by orthagh** [comment]
Sorry for the delay of answer (3 oct 2015 ...)

here is a patch for achieve opening a new tab on pdf massive action : https://gist.github.com/orthagh/fdc719f44f4c433f1963

Warning, common browsers forbid this behavior and display a warning to accept or refuse the auto-opened tab.

Another solution (used by another plugins) is to display a 'back' link (with onclick='window.history.back') in the massiveaction page and redirect (window.location js) to another page (no popup so) who force an 'Content-Disposition: attachment; filename=...'. 
So the pdf file is downloaded and the page still display the 'back' link and the user can click to return to asset list manually.
With this solution, no warning from the browser but a manual action for user.
