### ISSUE TITLE
glpi 10.0.7 apirest 403

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#14605]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Good morning,
could not connect to 10.0.7 with:  
```
glpi-t [28/Apr/2023:14:03:16 +0200] "GET /apirest.php/initSession HTTP/1.1" 200 6937 "-" "curl/7.87.0"
glpi-[28/Apr/2023:14:04:17 +0200] "GET //apirest.php/initSession HTTP/1.1" 403 6177 "-" "Java/1.8.0_202"
```

no problem en 10.0.6 ! 

Thanks

**Comment by cedric-anne** [comment]
Hi,

In our automated test suite, we have a test that validates it works. Thus, I guess many people would have warn us about this issue if it was broken.

I saw there is a double `/` in your logs (cf `GET //apirest.php/initSession`). Could you try to do your request with only on leading `/`?

**Comment by cedric-anne** [comment]
#14645 will permit to handle duplicates `/` in URLS.
