### ISSUE TITLE
The problem is in the inventory software

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#14602]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hi, everybody,
Faced with the following problem, the inventory history generates the installation and removal of the software “CanoScan LiDE 110 Scanner Driver". During one inventory execution, I receive information in the history of the glpi agent that the installation of the program “CanoScan LiDE 110 Scanner Driver” and its removal were performed.
I updated the versions of the glpi agent, plugins and the server part, but it did not give any results.

### Relevant log output

```shell
[2023-04-27 12:47:13] glpiphplog.WARNING:   *** PHP User Warning (512): user1@localhost/user2@localhost/user3@localhost/user4@localhost/user5@localhost/user6@subdomain2/user7@subdomain2/user8@localhost/user9@subdomain/user10@subdomain2/user11@subdomain/user12@localhost/user13@subdomain/user14@localhost/user15@subdomain/user16@localhost/user17@localhost/user18@subdomain/user19@localhost/user20@localhost/user21@localhost/user22@localhost/user23@localhost/user24@subdomain/user25@localhost exceed 255 characters long (379), it will be truncated. in /var/www/html/glpi/src/CommonDBTM.php at line 4274
  Backtrace :
  src/CommonDBTM.php:4274                            trigger_error()
  src/CommonDBTM.php:1587                            CommonDBTM->filterValues()
  src/Inventory/Asset/MainAsset.php:838              CommonDBTM->update()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:575              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:710                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()

[2023-04-27 13:12:39] glpiphplog.WARNING:   *** PHP User Warning (512): getFromDBByCrit expects to get one result, 518 found in query "SELECT `id` FROM `glpi_domains` WHERE `name` = 'WORKGROUP'". in /var/www/html/glpi/src/CommonDBTM.php at line 397
  Backtrace :
  src/CommonDBTM.php:397                             trigger_error()
  src/Inventory/Asset/MainAsset.php:713              CommonDBTM->getFromDBByCrit()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:575              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:710                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()



[2023-04-27 14:52:23] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/glpi/src/DbUtils.php at line 1580
  Backtrace :
  inc/db.function.php:439                            DbUtils->formatUserName()
  src/Profile_User.php:425                           formatUserName()
  src/Profile_User.php:1098                          Profile_User::showForEntity()
  src/CommonGLPI.php:689                             Profile_User::displayTabContentForItem()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()

[2023-04-27 14:52:28] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): strlen(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/glpi/src/DbUtils.php at line 1580
  Backtrace :
  inc/db.function.php:439                            DbUtils->formatUserName()
  src/Profile_User.php:425                           formatUserName()
  src/Profile_User.php:1098                          Profile_User::showForEntity()
  src/CommonGLPI.php:689                             Profile_User::displayTabContentForItem()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()

[2023-04-27 15:12:14] glpiphplog.WARNING:   *** PHP User Warning (512): getFromDBByCrit expects to get one result, 519 found in query "SELECT `id` FROM `glpi_domains` WHERE `name` = 'WORKGROUP'". in /var/www/html/glpi/src/CommonDBTM.php at line 397
  Backtrace :
  src/CommonDBTM.php:397                             trigger_error()
  src/Inventory/Asset/MainAsset.php:713              CommonDBTM->getFromDBByCrit()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:575              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:710                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
```

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.7 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.localhost.ru 5.4.17-2136.316.7.el8uek.x86_64 #2 SMP Mon Jan 23 18:37:18 PST 2023 x86_64
PHP 8.1.18 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysql, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="24M" safe_mode="" session.save_handler="files"
	upload_max_filesize="24M" 
Software: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/GLPI
	Host info: Localhost via UNIX socket
	
PHP version (8.1.18) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '10.0.100.2', Port: '3268', BaseDN: 'DC=localhost,DC=net', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=ldapsearch-glpi,OU=Special,DC=localhost,DC=net', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mail.localhost.net)

</pre></details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Installed / not activated               
		Install Method: Marketplace
	archisw              Name: Apps structures                Version: 2.2.9      State: Installed / not activated               
		Install Method: Marketplace
	archibp              Name: Business Processes             Version: 1.0.11     State: Not installed                           
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	connections          Name: Connections                    Version: 10.0.0     State: Installed / not activated               
		Install Method: Marketplace
	archidata            Name: Data structures                Version: 1.0.13     State: Installed / not activated               
		Install Method: Marketplace
	dataflows            Name: Dataflows                      Version: 2.2.13     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.17     State: Installed / not activated               
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.3      State: Installed / not activated               
		Install Method: Marketplace
	escalade             Name: Escalation                     Version: 2.8.0      State: Installed / not activated               
		Install Method: Marketplace
	financialreports     Name: Financial reports              Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	protocolsmanager     Name: Protocols manager              Version: 1.4.2      State: Not installed                           
		Install Method: Marketplace
	reports              Name: Reports                        Version: 1.14.1     State: Installed / not activated               
		Install Method: Marketplace
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Installed / not activated               
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	typology             Name: Typologies                     Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name:                                Version: 2.11.1     State: Enabled                         
		        Install Method: Marketplace
</pre></details>

**Comment by Badkempachi** [comment]
![history](https://user-images.githubusercontent.com/97535165/234885352-caf86fa7-1fd8-40a6-9369-7859ab1e3356.png)

**Comment by Badkempachi** [comment]
In the inventory file .the xml generated on the computer and the json file downloaded from the glpi server have only one entry “CanoScan LiDE 110 Scanner Driver”, it has the following form:
			{
				"arch": "x86_64",
				"from": "registry",
				"guid": "{1199FAD5-9546-44f3-81CF-FFDB8040B7BF}_CNQ2414",
				"install_date": "2022-05-31",
				"name": "CanoScan LiDE 110 Scanner Driver",
				"publisher": "Canon Inc.",
				"system_category": "application",
				"uninstall_string": "\"C:\\windows\\system32\\CanonIJ Uninstaller Information\\{1199FAD5-9546-44f3-81CF-FFDB8040B7BF}_CNQ2414\\DELDRV64.exe\" /U:{1199FAD5-9546-44f3-81CF-FFDB8040B7BF}_CNQ2414 /L0x0019"
			}

**Comment by cedric-anne** [comment]
Hi,

Does the issue appear on every inventory, or only once? We recently fixed some issues with invisible/special/space characters, and maybe this software was considered new because one of its field values has its cleaned version changed.

If problem persis, please provide the corresponding inventory file.

**Comment by Badkempachi** [comment]
> Hi,
> 
> Does the issue appear on every inventory, or only once? We recently fixed some issues with invisible/special/space characters, and maybe this software was considered new because one of its field values has its cleaned version changed.
> 
> If problem persis, please provide the corresponding inventory file.

Hi,
This information is duplicated after each inventory, I have 5 computers on which driver data is installed and on each this problem. Can you advise how to solve this problem?
Regarding the fixes, I installed the nightly build from April 27 on the glpi server and the situation did not change, it was also performed using “GLPI-Agent v1.5-git6b8b966f".

Also, on one of the five computers, it was found that the problem hooked more software, I attach a screenshot.

![History](https://user-images.githubusercontent.com/97535165/235888577-cd553b08-65e0-4e6c-9617-09af70cb057a.png)

**Comment by cedric-anne** [comment]
Could you please provide the inventory file?

**Comment by Badkempachi** [comment]
> Could you please provide the inventory file?

of course
[_computer_0_147.json.txt](https://github.com/glpi-project/glpi/files/11382599/_computer_0_147.json.txt)

**Comment by cedric-anne** [comment]
I confirm that during the second import of the inventory file, 2 softwares are deleted and recreated:
![image](https://user-images.githubusercontent.com/33253653/235925608-bc03f38b-40a4-4071-8fed-3e44b83f291a.png)
