### ISSUE TITLE
 Error: Unknown column 'is_helpdesk_visible' in 'where clause

### ISSUE THREAD

**Issue by zergij** [glpi-project/glpi#14607]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.7 

### Bug description

[2023-04-28 15:36:42] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_databases` WHERE `is_deleted` = '0' AND `is_helpdesk_visible` = '1' AND (`glpi_databases`.`entities_id` = '0') ORDER BY `name` LIMIT 100
  Error: Unknown column 'is_helpdesk_visible' in 'where clause'
  Backtrace :
  src/DBmysqlIterator.php:112                        
  src/DBmysql.php:1056                               DBmysqlIterator->execute()
  src/Dropdown.php:3714                              DBmysql->request()
  ajax/getDropdownFindNum.php:47                     Dropdown::getDropdownFindNum()
  {"user":"11@itsm"}

**Comment by cedric-anne** [comment]
Hi,

#14642 should fix this issue, but as you do not even give any context nor any steps to reproduce, I do not know how to confirm this.
