### ISSUE TITLE
An incorrect link to a knowledge base document is generated from the simplified Self-Service interface.

### ISSUE THREAD

**Issue by tovich** [glpi-project/glpi#14600]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

An incorrect link to a knowledge base document is generated from the simplified Self-Service interface.
https://glpi.server.local/front/**helpdesk.faq.php**?id=1 (the document does not open at this link)

In the full Self-Service interface, a correct link is generated from the ticket for the same document:
https://glpi.server.local/front/**knowbaseitem.form.php**?id=1 (this link opens the document)

### Your GLPI setup information

GLPI 10.0.7 ( => /srv/test)
Installation mode: TARBALL
Current language:ru_RU

**Comment by cedric-anne** [comment]
Hi,

The link is correct, but the problem is probably that the item is not visible in the FAQ, so it is not displayed.

#14649 should fix the list (i.e. only items visible in FAQ should appear now in the list).
