### ISSUE TITLE
Global and Personal view not working

### ISSUE THREAD

**Issue by lexcyr** [glpi-project/glpi#14608]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Impossible to apply the global or personal view configuration.
In my example, i have selected 8 collumns to be displayed in the global view, but i am still getting 11 collumns 
![image](https://user-images.githubusercontent.com/10072663/235186250-57d9eb96-1082-4ef2-b65c-f91475d17ce6.png)
![image](https://user-images.githubusercontent.com/10072663/235186297-70388db0-4504-4eef-9f27-afa4963340da.png)

Beside that i have 2 Name in the selection list because the OS Name does not show properly in the selection list. but i guess this should be in a separate issue.

### Steps To reproduce

1. go to asset> Computer
2.  Edit the Global or Personal View

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.6 (/glpi => D:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:en_GB

</details><details><summary>Server</summary><pre> 
Operating system: Windows NT E01SVPGLPI0001 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, soap, sockets, standard, tokenizer, xml, xmlreader, xmlwriter,
	xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6 Server at
	glpi-xxxxxxx.ca Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.6) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to D:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to D:\xampp\htdocs\glpi/config has been validated.
Write access to D:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to D:\xampp\htdocs\glpi/files has been validated.
Write access to D:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to D:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to D:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to D:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to D:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to D:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to D:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to D:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to D:\xampp\htdocs\glpi/files/_uploads has been validated.
The following directories should be placed outside "D:\xampp\htdocs\glpi":
‣ "D:\xampp\htdocs\glpi/files" ("GLPI_VAR_DIR")
‣ "D:\xampp\htdocs\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
Sessions configuration is secured.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
zip extension is installed.
bz2 extension is installed.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to D:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

</details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "D:\\xampp\\htdocs\\glpi"
GLPI_CONFIG_DIR: "D:\\xampp\\htdocs\\glpi/config"
GLPI_VAR_DIR: "D:\\xampp\\htdocs\\glpi/files"
GLPI_MARKETPLACE_DIR: "D:\\xampp\\htdocs\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "D:\\xampp\\htdocs\\glpi/files"
GLPI_CACHE_DIR: "D:\\xampp\\htdocs\\glpi/files/_cache"
GLPI_CRON_DIR: "D:\\xampp\\htdocs\\glpi/files/_cron"
GLPI_DUMP_DIR: "D:\\xampp\\htdocs\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "D:\\xampp\\htdocs\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "D:\\xampp\\htdocs\\glpi/files/_locales"
GLPI_LOCK_DIR: "D:\\xampp\\htdocs\\glpi/files/_lock"
GLPI_LOG_DIR: "D:\\xampp\\htdocs\\glpi/files/_log"
GLPI_PICTURE_DIR: "D:\\xampp\\htdocs\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "D:\\xampp\\htdocs\\glpi/files/_plugins"
GLPI_RSS_DIR: "D:\\xampp\\htdocs\\glpi/files/_rss"
GLPI_SESSION_DIR: "D:\\xampp\\htdocs\\glpi/files/_sessions"
GLPI_TMP_DIR: "D:\\xampp\\htdocs\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "D:\\xampp\\htdocs\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "D:\\xampp\\htdocs\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "D:\\xampp\\htdocs\\glpi/locales"
GLPI_VERSION: "10.0.6"
GLPI_SCHEMA_VERSION: "10.0.6@21cffee0fbb5afbf0d580cabdf6fd7a922598f97"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (D:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.6.0 in (D:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (D:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (D:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (D:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (D:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (D:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (D:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (D:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (D:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (D:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (D:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (D:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (D:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (D:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (D:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (D:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (D:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (D:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (D:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (D:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (D:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
blueimp/jquery-file-upload in (D:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php)
ramsey/uuid in (D:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (D:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (D:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (D:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (D:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (D:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (D:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (D:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (D:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (D:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (D:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (D:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (D:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (D:\xampp\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (D:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (D:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (D:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (D:\xampp\htdocs\glpi\vendor\symfony\polyfill-php82)

</details><details><summary>LDAP directories</summary><pre> 
Server: 'xxxxx', Port: '389', BaseDN: 'DC=xxxx,DC=ca', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'xxxxxxx', Use TLS: none

</details><details><summary>SQL replicas</summary><pre> 
Not active

</details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.20.0     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.12.1     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.12.1     State: Installed / not activated               
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Print to pdf                   Version: 2.1.0      State: Installed / not activated               
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.10.0     State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
Please try with lateste release and see if you reproduce

**Comment by lexcyr** [comment]
After updated to 10.0.7 i still have the same issue.

**Comment by cedric-anne** [comment]
Could you please give more details about the context? Are you using them in your search criteria?

**Comment by lexcyr** [comment]
i basically want just to change the view. add and remove some columns but the changes are not applying.

**Comment by cedric-anne** [comment]
Are you using these columns in your search criteria?

Have you a personal view? In such case, you should select the "Personal view" in the first dropdown before trying to change anything.

Is there something in GLPI logs when you click on the "delete" button?

**Comment by lexcyr** [comment]
ohhh, I am sorry for the inconvenience. I thought i already tried the basic browser troubleshooting. 
I am really sorry. Cleaning the browser resolved the the issue. I should have started with that before even thinking of openning an issue here.

Sorry again. This issue can be closed.
