### ISSUE TITLE
UX : too small dropdowns

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1463]
Hi

I'm using Chromium
Version 55.0.2883.75 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)

With this browser, I got problem to read content of some  dropdowns

Here is the details of a cron job containing an execution range from 00:00 to 24:00
![image](https://cloud.githubusercontent.com/assets/14139801/21455109/dcb56be2-c91d-11e6-8829-19fb263265d6.png)

I need to zoom out to 80% to get a better display
![image](https://cloud.githubusercontent.com/assets/14139801/21455115/f9f2f896-c91d-11e6-82a3-6bc66047281e.png)

I compared with Firefox ESR 45.6.0
The display is OK, 

![image](https://cloud.githubusercontent.com/assets/14139801/21455144/25dc1a78-c91e-11e6-8efb-fd1ffed20288.png)

If I try to zoom in, the bug begins to happen. Here is a screen if zoomed in 110%
![image](https://cloud.githubusercontent.com/assets/14139801/21455139/1ec746d6-c91e-11e6-897b-47a02cb40ba2.png)

Maybe we should give some more width.

**Comment by trasher** [comment]
On my computer, no need to zoom; I got the problem every time... :)
