### ISSUE TITLE
Problem with Domain membership of a Computer

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#14637]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

After the update to GLPI 10.0.7 the Assosiated Domain of a computer is detected. At some state a Domain was added multiple times. So we tried to delete the assosiated domain entry of the computer. Before one domain entry was listed at the Domain list of the Computer and now no Domain is listet. But in the submenu there is a number 3 shown (see screenshot). So it seems, that there are still Domain item entries in the database.
![image](https://user-images.githubusercontent.com/5680717/235604686-3d6d0292-daf1-41a3-ac06-c9f3eba95e62.png)
Now even with a new inventory no associated domain is added.
In the serverlogs, we see errors like this: 
```
[2023-04-28 17:00:15] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: INSERT INTO `glpi_domains_items` (`domains_id`, `itemtype`, `items_id`, `domainrelations_id`, `is_dynamic`) VALUES ('1', 'Computer', '11', '1', '1')
  Error: Duplicate entry '1-Computer-11' for key 'unicity'
  Backtrace :
  src/DBmysql.php:1320
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1317                            CommonDBTM->addToDB()
  src/Inventory/Asset/MainAsset.php:733              CommonDBTM->add()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:575              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:710                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
  {"user":"inventory@vmdebglpi"}
```

### Steps To reproduce

We don't now, how multiple entries of the same domain happened.

**Comment by cedric-anne** [comment]
Hi,

Could you check if issue is resolved by #14494? If problem persists, could you attache here the inventory file corresponding to this computer?

**Comment by AndiMb** [comment]
I added the change of #14494 but the error in the log file is still present.

**Comment by cedric-anne** [comment]
Could you attach here the inventory file corresponding to this computer?

**Comment by AndiMb** [comment]
I think, I found the reason for the error. In our environment the SQL error is thrown only for domain controllers of a certain entity. For these domain controllers the domain relation was switched from "belongs" to "mange" manually, since the domain controllers manage the domain. So in the example error above there is a entry in the database in the table glpi_domains_items for computer with id 11 for domain with id 1 and with the domain relations id set to 2. During the import of the inventory file it tries to add a new domains_item with the domain relations id 1, which results in a sql Duplicate Entry error.
