### ISSUE TITLE
Duplicate entry 'Computer-...' for key 'unicity'

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#14658]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

For two of our linux clients we see a "Duplicate entry" during the GLPI Agent data upload. 

glpiphplog.ERROR:   *** PHP User Error (256): Duplicate entry 'Computer-750-93714' for key 'unicity' in /var/www/glpi/src/DBmysql.php at line 1969
  Backtrace :
  src/DBmysql.php:1969                               trigger_error()
  src/Inventory/Asset/Software.php:885               DBmysql->executeStatement()
  src/Inventory/Asset/Software.php:447               Glpi\Inventory\Asset\Software->storeAssetLink()
  src/Inventory/Asset/MainAsset.php:933              Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:853              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1625                        Rule->process()
  src/Inventory/Asset/MainAsset.php:575              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:710                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:341                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()

Du to the IDs it seems that it belongs to a software package called "texlive-ha-prosper". In the inventory file I found:
			{
				"from": "nix",
				"name": "texlive-HA-prosper",
				"version": "4.21"
			},
and
			{
				"from": "nix",
				"name": "texlive-ha-prosper",
				"version": "4.21"
			},

### Steps To reproduce

1. Upload an Inventory file with the given software names

**Comment by stonebuzz** [comment]
Hi @AndiMb 

can you try this -> https://github.com/glpi-project/glpi/pull/14654

**Comment by stonebuzz** [comment]
not sure if this solves your problem.

The "case" problem in your case is in the name of the software

**Comment by trasher** [comment]
I've tested on my side, #14654 does not solve current issue, but #14659 does ;)
