### ISSUE TITLE
Uncaught Exception Error FilesystemCache.php at line 66

### ISSUE THREAD

**Issue by AngelVillaG** [glpi-project/glpi#14668]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

GLPI SETUP, Step 4

Uncaught Exception Error: Call to undefined function Twig\Cache\filter_var() in /usr/local/www/glpi/vendor/twig/twig/src/Cache/FilesystemCache.php at line 66

### Relevant log output

```shell
Uncaught Exception Error: Call to undefined function Twig\Cache\filter_var() in /usr/local/www/glpi/vendor/twig/twig/src/Cache/FilesystemCache.php at line 66
```

### Steps To reproduce

1. Install FreeBSD 13.2 RELEASE amd64.
2. pkg install apache24 (apache24: 2.4.56).
3. pkg install mysql80-server (mysql80-server: 8.0.32).
5. ee /usr/local/etc/mysql/my.cnf  open_files_limit = 32929 innodb_data_file_path = ibdata1:10M:autoextend
6. pkg install php81 mod_php81 (php81: 8.1.17 mod_php81: 8.1.17).
7. service mysql-server start
8. mysql -u root -p
9. CREATE DATABASE glpi;
10. CREATE USER 'glpi_db_user'@'localhost' IDENTIFIED BY 'glpi_db_user_SECRET';
11. ALTER USER 'glpi_db_user'@'localhost' IDENTIFIED WITH mysql_native_password BY 'glpi_db_user_SECRET';
12. GRANT ALL ON glpi.* TO 'glpi_db_user'@'localhost';
13. GRANT SELECT ON mysql.time_zone_name TO 'glpi_db_user'@'localhost';
14. FLUSH PRIVILEGES;
15. \q
16. mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -p -u root mysql
17. ee /usr/local/etc/php.ini date.timezone = America/Bogota max_execution_time = 600 memory_limit = 64M session.auto_start = off session.cookie_httponly = on
18. service apache24 start
19. pkg install php81-curl php81-fileinfo php81-gd php81-mbstring php81-mysqli php81-session php81-zlib php81-simplexml php81-xml php81-intl
20. pkg install php81-dom php81-ldap php81-pecl-APCu php81-pecl-xmlrpc
21. fetch https://github.com/glpi-project/glpi/releases/download/10.0.7/glpi-10.0.7.tgz
22. tar -zxvf glpi-10.0.7.tgz -C /usr/local/www
23. rm glpi-10.0.7.tgz
24. chown -R www:www /usr/local/www

### Your GLPI setup information

FreeBSD 13.2 RELEASE amd64.

New installation.

### Anything else?

# ee /usr/local/www/glpi/vendor/twig/twig/src/Cache/FilesystemCache.php

My solution is commented this lines with #:

        	if (self::FORCE_BYTECODE_INVALIDATION == ($this->options & self::FORCE_BYTECODE_INVALIDATION)) {
            	// Compile cached file into bytecode cache
  	#if (\function_exists('opcache_invalidate') && filter_var(ini_get('opcache.enable'), \FILTER_VALIDATE_BOOLEAN)) {
  	#	@opcache_invalidate($key, true);
  	#} elseif (\function_exists('apc_compile_file')) {
  	#	apc_compile_file($key);
  	#}
        	}

Now the setup finished OK.

Thank you for your hard work!

**Comment by cedric-anne** [comment]
Hi,

Could you try to install `php81-filter` package to see if it solves the issue?

**Comment by AngelVillaG** [comment]
Hi cedric-anne,

Thank you for your attention.

With the php81-filter installed the Setup finished OK, my complete php modules installed:

# pkg info | grep php | awk '{print $1}'
mod_php81-8.1.17
php81-8.1.17
php81-bz2-8.1.17
php81-ctype-8.1.17
php81-curl-8.1.17
php81-dom-8.1.17
php81-exif-8.1.17
php81-fileinfo-8.1.17
php81-filter-8.1.17
php81-gd-8.1.17
php81-iconv-8.1.17
php81-imap-8.1.17
php81-intl-8.1.17
php81-ldap-8.1.17
php81-mbstring-8.1.17
php81-mysqli-8.1.17
php81-opcache-8.1.17
php81-pecl-APCu-5.1.22
php81-pecl-xmlrpc-1.0.0.r3_2,1
php81-phar-8.1.17
php81-session-8.1.17
php81-simplexml-8.1.17
php81-sodium-8.1.17
php81-xml-8.1.17
php81-zip-8.1.17
php81-zlib-8.1.17

Note:
The issue also occurred on 10.0.6 without the module php81-filter installed.

Thank you sir.
