### ISSUE TITLE
URL for browser notification has //

### ISSUE THREAD

**Issue by PPCM** [glpi-project/glpi#14671]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When a browser notification rises and the associated URL is https://glpi.tld//front/ticket.form.php?id=79
There is a **//**
In Setup > General, the "URL of the application field" is set with "https://glpi.tld" (no / at the end)

For email notifications, there is no problem, the URL is fine : https://glpi.tld/front/ticket.form.php?id=79

### Your GLPI setup information

Docker installation from https://hub.docker.com/r/ppcm/glpi-server

### Anything else?

I made lot of test with different values of "URL of the application field", but each time, the notification is set with **//**

**Comment by cedric-anne** [comment]
Hi,

It has already been reported and fixed. See #14603 .
