### ISSUE TITLE
Technician in charge for licenses

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1467]
It is not logical:

![license](https://cloud.githubusercontent.com/assets/17082164/21496353/dc571ae2-cc2e-11e6-94d8-5880a2843252.png)

**Comment by trasher** [comment]
Y'oure right, same for group ;)

**Comment by AircraftRu** [comment]
Please correct the translation https://www.transifex.com/glpi/GLPI

**Comment by trasher** [comment]
A pR has been opened; it has to be reviewed, accepted and merged first; and then transifex can be updated.

**Comment by AircraftRu** [comment]
Thank you. 
Have not updated the translation.

**Comment by trasher** [comment]
It will be updated next week. 

There were  recently some issues with GLPI translations on transifex; I prefer not doing anything myself since I'm not sure what is wrong or not ;)
