### ISSUE TITLE
Inventory GLPI 10.0.7

### ISSUE THREAD

**Issue by FredVRA** [glpi-project/glpi#14687]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Since the GLPI 10.0.7 update and the new apache configuration, GLPI Agents don't communicate with the Plugin GLPI Inventory.

I found a similar configuration in this post:  https://github.com/glpi-project/glpi/issues/14485 but the solution doesn't work for me:

`AliasMatch "^/(plugins/glpiinventory/(index\.php)?)$" "/var/www/glpi/$1"`

my apache's vhost looks like:

```
<VirtualHost *:443>
        ServerName glpi.mondomaine.fr
        DocumentRoot /var/www/html/glpi/public
        AliasMatch "^/(plugins/glpiinventory/(index\.php)?)$" "/var/www/html/supportinfo/$1"
        SSLEngine on
        SSLCertificateFile /etc/ssl/certs/certifmondomaine.fr.crt
        SSLCertificateKeyFile /etc/ssl/private/certifmondomaine.fr.key

        <Directory /var/www/html/glpi/plugins/glpiinventory>
                Options None
                Require all granted
                Order deny,allow
                Allow from all
        </Directory>

        <Directory /var/www/html/glpi/public>
                AuthType GSSAPI
                AuthName "Kerberos Authentication"
                GssapiBasicAuth On
                GssapiLocalName On
                GssapiCredStore keytab:/etc/apache2/krb5.keytab
                require valid-user
                RewriteEngine On
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^(.*)$ index.php [QSA,L]

        </Directory>
        ServerSignature off
        ErrorLog /var/log/apache2/glpi_error.log
        CustomLog /var/log/apache2/glpi_access.log combined

</VirtualHost>
```

The log's agent:

` [Tue May  2 15:29:37 2023][debug] [http server] GET request / from client 127.0.0.1
[Tue May  2 15:29:37 2023][debug] [http server] response status 200
[Tue May  2 15:29:38 2023][debug] [http server] GET request /now from client 127.0.0.1
[Tue May  2 15:29:38 2023][debug] [http server] rescheduling next contact for all targets right now
[Tue May  2 15:29:38 2023][debug] [http server] response status 200
[Tue May  2 15:29:39 2023][info] target server0: server https://glpi.mondomaine.fr/plugins/glpiinventory
[Tue May  2 15:29:39 2023][debug] [http client] Using Compress::Zlib for compression
[Tue May  2 15:29:39 2023][info] sending prolog request to server0
[Tue May  2 15:29:39 2023][debug2] [http client] sending message:
<?xml version="1.0" encoding="UTF-8" ?>
<REQUEST>
  <DEVICEID>monpc.mondomaine.lan-2023-04-07-15-23-19</DEVICEID>
  <QUERY>PROLOG</QUERY>
  <TOKEN>12345678</TOKEN>
</REQUEST>
[Tue May  2 15:29:39 2023][error] [http client] authentication required, no credentials available
[Tue May  2 15:29:39 2023][error] No answer from server at https://glpi.mondomaine.fr/plugins/glpiinventory
[Tue May  2 15:29:39 2023][info] target server0: next run: Tue May  2 15:37:39 2023 - https://glpi.mondomaine.fr/plugins/glpiinventory
[Tue May  2 15:29:39 2023][debug] Agent memory usage before freeing memory: WSS=29941760 PFU=129138688
[Tue May  2 15:29:39 2023][info] GLPI Agent memory usage: WSS=3207168 PFU=129138688
[Tue May  2 15:29:39 2023][debug] [http server] GET request / from client 127.0.0.1
[Tue May  2 15:29:39 2023][debug] [http server] response status 200`

and the entry in the apache's log:

` "POST /plugins/glpiinventory HTTP/1.1" 401 4039 "-" "GLPI-Agent_v1.4" `

Thanks for your help.

**Comment by cedric-anne** [comment]
Hi,

Path of your alias does not match with path declared in your document root. Your issue is probably due to this.

```diff
        DocumentRoot /var/www/html/glpi/public
-        AliasMatch "^/(plugins/glpiinventory/(index\.php)?)$" "/var/www/html/supportinfo/$1"
+        AliasMatch "^/(plugins/glpiinventory/(index\.php)?)$" "/var/www/html/glpi/$1"
```

Anyway, we only tack bugs here, so I will close the issue.
