### ISSUE TITLE
Missing object names when customizing columns in asset lists, "select default items to show"

### ISSUE THREAD

**Issue by Mirkk** [glpi-project/glpi#14688]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.7

### Bug description

Clicking on the "wrench" icon in any GLPI assets list view, a window with the column names opens, with title "Select default items to show". Here, see the image, the entry "Name" is present several times, because it refers to the name of different sub-objects. In the select box and in the column titles these objects are visible, but not in this list, creating some confusion and making reordering difficult.
![image](https://github.com/glpi-project/glpi/assets/10242044/e84e02a5-2a5c-430b-b197-7cff40667dda)
![image](https://github.com/glpi-project/glpi/assets/10242044/aa8fda32-4fd1-4757-b812-f312f5447a89)

### Relevant log output

```shell
n.a.
```

### Page URL

any assets list

### Steps To reproduce

Clicking on the "wrench" icon in any GLPI assets list view, a window with the column names opens, with title "Select default items to show". Here, see the image, the entry "Name" is present several times.

### Your GLPI setup information

10.0.7 with fields plugin

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue. Search result headers are displaying the itemtype in front of the field in such case (e.g. `Operating system - Name`), so we should probably display it here the same way.
