### ISSUE TITLE
The problem is in the inventory software v2

### ISSUE THREAD

**Issue by Badkempachi** [glpi-project/glpi#14696]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8-dev

### Bug description

Hi, everybody,
I again have a problem with the duplication of software information in the inventory history as it was previously with the case here https://github.com/glpi-project/glpi/issues/14602 . In this case, the problem arose with “Cisco Webex Meetings".

**Comment by Badkempachi** [comment]
![history](https://github.com/glpi-project/glpi/assets/97535165/fc86c2e0-f09c-4ddb-9491-2a0fadc76147)

**Comment by Badkempachi** [comment]
inventory file - 
[computer_0_14.json.txt](https://github.com/glpi-project/glpi/files/11442698/computer_0_14.json.txt)

**Comment by stonebuzz** [comment]
Hi @Badkempachi 

I do not reproduce with your inventory file

Can you test with the GLPI nighlty build?

Best regards

https://nightly.glpi-project.org/glpi/

**Comment by Badkempachi** [comment]
Hi @stonebuzz 
you were right, it was fixed in the nightly build. Thank you
