### ISSUE TITLE
[0.90-RC2] with old browsers : dropdown display :  not "comfortable"

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#147]
Hi,
after selecting a value in a dropdown list, this value is displayed with right alignement. ( and a huge blank space between text and down arrow)

it works but for most of these dropdowns, it is quite hard to read set value.

**Comment by ladenree76000** [comment]
with MS EDGE browser dropdown display is ok
with FF and IE8 :
![image](https://cloud.githubusercontent.com/assets/13557254/10284691/991d94fa-6b85-11e5-9305-a54f0f79ed68.png)

**Comment by ladenree76000** [comment]
FF 17.0 also truncates  dropdown display.

**Comment by orthagh** [comment]
No idea for this issue right now.
My opinion is IE8 is very old and i suggest a browser update.

However, if someone have a pull request, i'll be happy to merge it.
I close
