### ISSUE TITLE
Contract Renewal and Notice - miscalculated

### ISSUE THREAD

**Issue by Christof48** [glpi-project/glpi#14703]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.6

### Bug description

Contract renewal is working unexpected.
If I have "initial Contract period" 60 month and "contract renewal" is additional 12 Month I don`t get 70 moth but 120 month at first renewal. 
Also Notice gives unexpected Results and does not calculate correct.

### Your GLPI setup information

GLPI 10.0.6 ( => /usr/share/glpi)
Installation mode: RPM
Current language:en_GB

### Anything else?

![GLPI Contracts](https://github.com/glpi-project/glpi/assets/75986915/db1cf888-8599-43e2-9519-d50fabef061c)

**Comment by Christof48** [comment]
Operating system: Linux yp-glpi.rheine 5.12.15-300.fc34.x86_64 #1 SMP Wed Jul 7 19:46:50 UTC 2021 x86_64
PHP 8.0.8 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sodium, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="2048M" post_max_size="22M" safe_mode="" session.save_handler="files"
	upload_max_filesize="22M" 
Software: Apache/2.4.48 (Fedora) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0
Server Software: MariaDB Server
	Server Version: 10.5.11-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.0.8) is supported.PHP version (8.0.8) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.11) is supported.Database engine version (10.5.11) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated.Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by Christof48** [comment]
order                Name: Bestellverwaltung              Version: 2.10.3     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.13.0     State: Enabled                                 
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Not installed                           
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.2     State: Enabled                                 
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Enabled                                 
		Install Method: Marketplace

**Comment by M-Falken** [comment]
hi,
any news on this one please ?

**Comment by Christof48** [comment]
Sorry, nothing changed

 

 

Von: Grégory Roussel ***@***.***> 
Gesendet: Montag, 30. Oktober 2023 09:33
An: glpi-project/glpi ***@***.***>
Cc: Christof48 ***@***.***>; Author ***@***.***>
Betreff: Re: [glpi-project/glpi] Contract Renewal and Notice - miscalculated (Issue #14703)

 

hi,
any news on this one please ?

**Comment by FreeMacs** [comment]
Is there any new information? We have the same problem as you can see in my Ticket #15893. 
We would like to use the function in our company but unfortunately this is not possible with the bug.

**Comment by Christof48** [comment]
Yes, that ist the same problem

 

 

 

Mit freundlichen Grüßen

Im Auftrag

 

Christof Overkamp

Systemadministrator Schulen 


 <http://www.rheine.de/> 

Stadt Rheine

Der Bürgermeister

Schulen, Soziales, Migration und Integration

Klosterstr 14

48431 Rheine

Schul-IT

Raum 413a

Tel.: 05971 939 – 366
Mobil: 01707609326

Fax:  05971 939  - 866

 ***@***.***> ***@***.***

 

 

Bitte denken Sie an die Umwelt, bevor Sie diese E-Mail ausdrucken.

 

Hinweis:  
Dies ist eine vertrauliche Nachricht und nur für den Adressaten bestimmt. Es ist nicht erlaubt, diese Nachricht zu kopieren oder Dritten zugänglich zu machen. Sollten Sie irrtümlich diese Nachricht erhalten haben, bitte ich um Ihre Mitteilung per E-Mail oder unter der oben angegebenen Telefonnummer.

 

Von: blippercop ***@***.***> 
Gesendet: Montag, 16. September 2024 14:42
An: glpi-project/glpi ***@***.***>
Cc: Christof48 ***@***.***>; Author ***@***.***>
Betreff: Re: [glpi-project/glpi] Contract Renewal and Notice - miscalculated (Issue #14703)

 

related to #17725 <https://github.com/glpi-project/glpi/pull/17725>  ?

**Comment by trasher** [comment]
This will be fixed in next release then :)
