### ISSUE TITLE
Deleted DatabaseInstances are displayed on "Database instances" tab

### ISSUE THREAD

**Issue by po1vo** [glpi-project/glpi#14739]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Deleted DatabaseInstances are displayed on "Database instances" tab and under "Locked items" on "Locks" tabs as well.

### Page URL

/front/computer.form.php

### Anything else?

A fix would be adding `is_deleted => 0` to the request in DatabaseInstance::showInstances() , unless this is not a bug.

Could you also tell me if and how deleted and/or locked items like these DatabaseInstances are eventually removed from Glpi? I didn't find anything related in automatic actions.

**Comment by cedric-anne** [comment]
Hi,

With #14748, deleted instances rows will have a "red" background. This is what is done usually on other lists (for instance on appliances).

> Could you also tell me if and how deleted and/or locked items like these DatabaseInstances are eventually removed from Glpi? I didn't find anything related in automatic actions.

I do not remember about something that automatically cleans these.
