### ISSUE TITLE
/front/networkport.php 404 not found [9.1.1]

### ISSUE THREAD

**Issue by IiscsiI** [glpi-project/glpi#1473]
Bonjour,

Je voulais gérer les ports réseau de certains de mes équipements (purger, vérifier, etc) mais je suis tombé sur une bonne vieille erreur 404 not found.
Le fichier /front/networkport.php n'existe pas. J'ai retéléchargé l'archive disponible dans les releases mais le fichier n'y est pas (cf capture ci dessous). 
Merci d'avance

description courte en anglais pour ceux qui ne parlent pas français.

When i want to manage my network ports (check, delete objects, ...) i have a 404 not found /front/networkport.php. The file does not exist in the tar.gz file from github.

![capture du 2016-12-28 10-06-52](https://cloud.githubusercontent.com/assets/24807002/21518246/68ee0c48-cce5-11e6-8fe4-c9d255ed4d31.png)

**Comment by IiscsiI** [comment]
Complément d'informations :

extrait des fichiers d'erreurs apache

`script '/var/www/glpi/front/networkport.php' not found or unable to stat, referer: http://glpi.mairie.tarbes/front/networkport.form.php?id=15275`

**Comment by trasher** [comment]
I'm not able to reproduce

**Comment by IiscsiI** [comment]
can't reproduce today the problem .... close the "ticket" and i reopen if needed.
