### ISSUE TITLE
Linking printer cartridge level entries to cartridge models

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#14734]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8-dev

### Bug description

Hello,

In Fusioninventory plugin (in conjunction with Additional alerts) we were able to define warning levels for cartridges currently in use in printers. It seems that this part of the code was not included in the actual GLPI native inventory.
Do you have any plans about its integration? And if so, do you think that related alerts should remain in the Additional alerts plugin or should be integrated to the main printer cartridges managment?

Thanks. 

### Relevant log output

```shell
No trace of this feature.
```

**Comment by orthagh** [comment]
> Do you have any plans about its integration?

No plans atm. You can:

- add an entry to suggest.glpi-project.org (we still consult the site occasionally). We may develop the thing if it becomes popular.
- add the feature yourself. See below.

> should be integrated to the main printer cartridges managment?

I think no, cartridge reports from dynamic inventory is completely different than Asset > cartridges
Still, in Administration > Entity, Notification tab the setup for the alarm my be merged with Cartridges paragraph (with maybe an helper to indicate it targets cartridge reports et not cartridge assets
