### ISSUE TITLE
10.0.7 - Error on my apache webserver when I'm using Alias on vhost

### ISSUE THREAD

**Issue by SilvaFernando** [glpi-project/glpi#14733]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Error on my apache webserver when I'm using Alias on vhost

I'm using Alias like this:
/glpitest /var/www/html/glpi

If I don't apply the correction for new public directory, my alias worked, but if I applied on my VHOST correction for public directory my GLPI has 403 error

<VirtualHost *:80>
    ServerName glpi.localhost

    DocumentRoot /var/www/html/glpi/public

    # If you want to place GLPI in a subfolder of your site (e.g. your virtual host is serving multiple applications),
    # you can use an Alias directive:
    Alias "/glpitest" "/var/www/html/glpi/public"

    <Directory /var/www/html/glpi/public>
        Require all granted

        RewriteEngine On

        # Redirect all requests to GLPI router, unless file exists.
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]
    </Directory>
</VirtualHost>

![image](https://github.com/glpi-project/glpi/assets/53239752/2dbb7651-0256-4c59-86b8-95b11132e07a)

### Relevant log output

```shell
Error HTTP 403
```

### Page URL

localhost/glpitest

### Steps To reproduce

Adjust apache VHOST like documentation: https://glpi-install.readthedocs.io/pt/latest/prerequisites.html

### Your GLPI setup information

Operating system: Linux fdbb8db82001 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Thu Mar 10 20:59:28 UTC 2022 x86_64
PHP 8.0.28 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, selinux, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.37 (AlmaLinux) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Edg/113.0.1774.42
Server Software: Percona Server (GPL), Release 44, Revision 27f408641db
	Server Version: 5.7.41-44
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@db-glpi-10.0.7-Fernando/glpi
	Host info: db-glpi-10.0.7-Fernando via TCP/IP
	
PHP version (8.0.28) is supported.PHP version (8.0.28) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.41) is supported.Database engine version (5.7.41) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file could not be created in /var/log/glpi.The log file could not be created in /var/log/glpi.

**Comment by cedric-anne** [comment]
Your alias is pointing to the same path than the document root, so either it is useless (you can access GLPI directly on vhost root path), either you misconfigured it.

**Comment by SilvaFernando** [comment]
OK thanks, but if we search, we have other issues that have been opened for similar behavior, mainly using an alias for inventory, if possible, this bug needs attention, if I can find a way to solve it I will put it here to help community, especially those who are experiencing this behavior

**Comment by tulhaum** [comment]
> OK thanks, but if we search, we have other issues that have been opened for similar behavior, mainly using an alias for inventory, if possible, this bug needs attention, if I can find a way to solve it I will put it here to help community, especially those who are experiencing this behavior

Did you find any solutions  ? Same problem here, error 403 using Alias.
