### ISSUE TITLE
unable to load new user from LDAP

### ISSUE THREAD

**Issue by JMD974** [glpi-project/glpi#14744]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hi,

since we updated GLPI from 10.0.5 to 10.0.7, we are unable to add new user from LDAP.

In the menu : administration -> users -> LDAP directory link -> import new Users  -> search   I ve got the following error:

The requested URL was not found on this server.
![image](https://github.com/glpi-project/glpi/assets/134267235/7476d27c-9301-46d9-88d2-fac4c1744189)
when clicking search, got this error:
![image](https://github.com/glpi-project/glpi/assets/134267235/f85d71e4-0b66-4a50-8a48-0dea10bce281)

some "public" appeared in the address, don't know why.

This error didn't appeared in GLPI 10.0.5 and 10.0.2, our last 2 previous versions.

Thanks for your help.

JMD974

### Steps To reproduce

In the menu : administration -> users -> LDAP directory link -> import new Users  -> search

### Your GLPI setup information

Debian
apache 2.4.38
GLPI 10.0.7

**Comment by cedric-anne** [comment]
Hi,

#14503 may fix your issue. Could you confirm?

**Comment by JMD974** [comment]
Hi again,

thx cedric-anne, I confirm case #14503 (pb with PHP router) resolved my issue.

Many thanks for your responsiveness.

JMD974
