### ISSUE TITLE
Error updating request rules.

### ISSUE THREAD

**Issue by David-Rodriguez-cabrera** [glpi-project/glpi#14742]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

glpi version: 10.0.6
In the rules for requests, if you put, for example, that the criteria are that the title exists and that the applicant also exists, if it is fulfilled when the request is created, it does so, but if it is fulfilled later, it does not. The update does not work well, however, if we do the same but making the requester and the observer exist and we remove the title criterion, if it is updated correctly, to be that in the fields that are in another part of the request it gives error.

I think it happens with all the rules.

### Steps To reproduce

1. Create a request rule that the title and requester exist.
2. It checks that if you create a request and it meets the requirements, it will execute the rule, but if it meets them when updating, it doesn't.
3. Do the same but with criteria in the same field, such as: Requester and Observer exist, or Title and Description.
With those fields if it works when updating

**Comment by trasher** [comment]
Please try at least with 10.0.7

**Comment by trasher** [comment]
No feedback from a while, closing.
