### ISSUE TITLE
Wrong actor in ticket history

### ISSUE THREAD

**Issue by fbetil** [glpi-project/glpi#1476]
**Problem**
When i add an existing document to an existing ticket, under "Processing ticket > Actions historical" tab, the actor and datetime associated with the document on this ticket is not me but the creator and creation datetime of document.

**Configuration**
`
GLPI 9.1.1 ( => D:\APPLICATIFS\GLPI\WEBTEST)

Server
 
Operating system: Windows NT WENDY 6.1 build 7601 (Windows Server 2008 R2 Enterprise Edition Service Pack 1) i586
PHP 5.6.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	com_dotnet, ctype, curl, date, dom, ereg, fileinfo, filter, ftp, gd, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt,
	mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, session, soap, sqlite3, standard, tokenizer, wddx, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.12 (Win32) mod_authn_ntlm/1.0.0 PHP/5.6.6 ()
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.5.19
	Server SQL Mode: 
	Parameters: root@127.0.0.1:3307/glpi_test
	Host info: 127.0.0.1 via TCP/IP
	
OKD:\APPLICATIFS\GLPI\WEBTEST/config : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_dumps : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_sessions : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_cron : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_graphs : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_lock : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_plugins : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_tmp : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_rss : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_uploads : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_pictures : OK
OKD:\APPLICATIFS\GLPI\WEBTEST/files/_log : OK

Libraries
 
htmLawed version 1.1.21 in (D:\APPLICATIFS\GLPI\WEBTEST\lib\htmlawed)
phpCas version 1.3.4 in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\phpmailer\phpmailer)
Zend Framework in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\zendframework\zend-loader\src)
zetacomponents/graph in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\zetacomponents\graph\src)
SimplePie version 1.4.1 in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\michelf\php-markdown\Michelf)
true/punycode in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\true\punycode\src)
iacaml/autolink in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\iamcal\lib_autolink)
sabre/vobject in (D:\APPLICATIFS\GLPI\WEBTEST\vendor\sabre\vobject\lib)

LDAP directories
 
Server: 'coucou.intra', Port: '389', BaseDN: 'DC=coucou,DC=intra', Connection filter:
		'(&(objectClass=user)(employeeNumber=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'infglpi@coucou.intra',
		Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@smtp)

Mails receivers
 
Name: 'infglpi@coucou.intra' Active: No
	Server: '{pop:110/pop/novalidate-cert/notls}' Login: 'COUCOU\infglpi' Password: No

Plugins list
 
	fusioninventory      Name: FusionInventory                Version: 9.1+1.0    State: Enabled

`

**Comment by AnaelMobilia** [comment]
Hello,

I confirm this issue and add : when we link a document (from the "linked elements" tabs on the document) to a ticket, the history of actions show date & user who uploaded the document.

**Comment by AnaelMobilia** [comment]
For the date, use `glpi_documents_items` => date_mod
For user, we need to add a column to previous table

**Comment by kelior** [comment]
still not fixed in 9.2 on our end

**Comment by trasher** [comment]
@kelior  since this issue is old, and there has been schema changes in order to get it fixed; I doubt you have the same exact issue as the original requester.
So, please open another issue, and provide details.
