### ISSUE TITLE
[10.0.7] Export of tickets impossible

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#14778]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.7

### Bug description

Impossible to export tickets csv this worked in 9.5.9.
I have modified: 
/etc/php/8/apache2/php.ini  : upload_max_filesize = 150M et post_max_size = 150M and  glpi general configuration then management and put 8M
How to do .? Thank you

### Relevant log output

```shell
PHP Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 53248 bytes) in /var/www/assistance/vendor/iamcal/lib_autolink/lib_autolink.php at line 63
```

**Comment by cedric-anne** [comment]
By the way, you still not provide requested information.

**Comment by falco2001** [comment]
47000

**Comment by cedric-anne** [comment]
If you want a quick resolution of this, just try to upgrade your PHP memory limit to an upper value.

**Comment by falco2001** [comment]
I mis1000M in memory limit and it goes!!!!!!!!
Thank you very much for your speed and professionalism.
