### ISSUE TITLE
link is not as environment variable

### ISSUE THREAD

**Issue by filliperitzel** [glpi-project/glpi#14775]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.7

### Bug description

I just tested it on a clean install.

*Create the database
*I created a subdomain (Hostinger Shared host)
* I copied the last version
*Only 2 warning messages appeared.
1 - suggesting I change the root directory to public, but when I point my subdomain to /public it doesn't load anything.
2 – suggesting that I do the procedure of moving sensitive files out of the root, and that I wouldn't have needed if I had pointed the hosting to public.

*Removed the install file
* Changed user passwords

Until then everything works perfectly.

*I added the following text in htaccess:
RewriteBase /
RewriteEngine On
RewriteCond %{REQUEST_URI} !^/public
RewriteRule ^(.*)$ public/index.php [QSA,L]

The problem appears: I enter the glpi user, press the arrow to go to the next user, and I see a “page not found” error, because the url contains “public”
however, this error does not appear when I am changing the ticket page, but if I enter a ticket and press the arrow for the next ticket, the error happens.

First de correct link:
![evi01](https://github.com/glpi-project/glpi/assets/100035499/e8b8b5bd-3245-4855-975a-c90dec8778bf)

now, the wrong link:
![evi02](https://github.com/glpi-project/glpi/assets/100035499/42a3748b-a8cb-4435-adad-f99fb7a0d7fb)

### Your GLPI setup information

<html>
<body>

GLPI 10.0.7 ( => /home/u768482130/domains/riowide.com/public_html/controle) Installation mode: TARBALL Current language:pt_BR
--

Operating system: Linux br-asc-web718.main-hosting.eu 4.18.0-348.lve.el7h.x86_64 #1 SMP Sun Nov 21 14:20:28 UTC 2021 x86_64 PHP 8.1.18 litespeed (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, ctype, curl, date, 	dom, exif, fileinfo, filter, ftp, gd, geoip, gettext, gmp, hash, iconv, igbinary, imagick, imap, intl, json, ldap, libxml, 	litespeed, mbstring, monarxprotect, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, readline, redis, 	session, shmop, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, timezonedb, tokenizer, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="120" memory_limit="1536M" post_max_size="1536M" safe_mode="" session.save_handler="files" 	upload_max_filesize="1536M"  Software: LiteSpeed 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.5.19-MariaDB-cll-lve 	Server SQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: u768482130_controle@localhost/u768482130_controle 	Host info: Localhost via UNIX socket 	 PHP version (8.1.18) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (10.5.19) is supported. No files from previous GLPI version detected. The log file has been created successfully. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_cache has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/config has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_cron has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_dumps has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_graphs has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_lock has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_pictures has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_plugins has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_rss has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_sessions has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_tmp has been validated. Write access to /home/u768482130/domains/riowide.com/public_html/controle/files/_uploads has been validated.  Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details. The following directories should be placed outside "/home/u768482130/domains/riowide.com/public_html/controle": ‣ "/home/u768482130/domains/riowide.com/public_html/controle/files" ("GLPI_VAR_DIR") ‣ "/home/u768482130/domains/riowide.com/public_html/controle/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "/home/u768482130/domains/riowide.com/public_html/controle/public". Sessions configuration is secured. OS and PHP are relying on 64 bits integers. exif extension is installed. ldap extension is installed. openssl extension is installed. Following extensions are installed: bz2, Phar, zip. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /home/u768482130/domains/riowide.com/public_html/controle/marketplace has been validated. Access to timezone database (mysql) is not allowed.

GLPI_ROOT: "/home/u768482130/domains/riowide.com/public_html/controle" GLPI_CONFIG_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/config" GLPI_VAR_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files" GLPI_MARKETPLACE_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/marketplace" GLPI_USE_CSRF_CHECK: "1" GLPI_CSRF_EXPIRES: "7200" GLPI_CSRF_MAX_TOKENS: "100" GLPI_USE_IDOR_CHECK: "1" GLPI_IDOR_EXPIRES: "7200" GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?\|feed):\\/\\/[^@:]+(\\/.*)?$/"] GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org" GLPI_INSTALL_MODE: "TARBALL" GLPI_NETWORK_MAIL: "glpi@teclib.com" GLPI_NETWORK_SERVICES: "https://services.glpi-network.com" GLPI_MARKETPLACE_ALLOW_OVERRIDE: true GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true GLPI_USER_AGENT_EXTRA_COMMENTS: "" GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1" GLPI_AJAX_DASHBOARD: "1" GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: "0" GLPI_CENTRAL_WARNINGS: "1" GLPI_DOC_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files" GLPI_CACHE_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_cache" GLPI_CRON_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_cron" GLPI_DUMP_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_dumps" GLPI_GRAPH_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_graphs" GLPI_LOCAL_I18N_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_locales" GLPI_LOCK_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_lock" GLPI_LOG_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_log" GLPI_PICTURE_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_pictures" GLPI_PLUGIN_DOC_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_plugins" GLPI_RSS_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_rss" GLPI_SESSION_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_sessions" GLPI_TMP_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_tmp" GLPI_UPLOAD_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_uploads" GLPI_INVENTORY_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/files/_inventories" GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/" GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/" GLPI_I18N_DIR: "/home/u768482130/domains/riowide.com/public_html/controle/locales" GLPI_VERSION: "10.0.7" GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6" GLPI_MARKETPLACE_PRERELEASES: false GLPI_MIN_PHP: "7.4.0" GLPI_MAX_PHP: "8.3.0" GLPI_YEAR: "2023"

htmlawed/htmlawed version 1.2.9 in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.8.0 in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.6.2 in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/true/punycode/src) iamcal/lib_autolink in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/iamcal/lib_autolink) sabre/dav in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/sabre/dav/lib/DAV) sabre/http in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/sabre/http/lib) sabre/uri in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/sabre/uri/lib) sabre/vobject in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/elvanto/litemoji/src) symfony/console in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/symfony/console) scssphp/scssphp in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/ramsey/uuid/src) psr/log in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/psr/log/Psr/Log) psr/simple-cache in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/psr/simple-cache/src) psr/cache in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/psr/cache/src) league/csv in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/league/csv/src) mexitek/phpcolors in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/paragonie/sodium_compat/src) symfony/cache in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/symfony/cache) html2text/html2text in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/html2text/html2text/src) symfony/css-selector in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/symfony/css-selector) symfony/dom-crawler in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/symfony/dom-crawler) twig/twig in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/twig/twig/src) twig/string-extra in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 not found symfony/polyfill-php82 in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/symfony/polyfill-php82) league/oauth2-client in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/league/oauth2-client/src/Provider) league/oauth2-google in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/league/oauth2-google/src/Provider) thenetworg/oauth2-azure in (/home/u768482130/domains/riowide.com/public_html/controle/vendor/thenetworg/oauth2-azure/src/Provider)

Not active

Way of sending emails: SMTP+SSL (controle@riowide.com@smtp.hostinger.com)

 

gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                  		Install Method: Marketplace 	gappessentials       Name: Gapp Essentials                Version: 2.1.1      State: Enabled                                  		Install Method: Marketplace 	gdrive               Name: GDrive                         Version: 2.0.0      State: Installed / not activated                		Install Method: Marketplace 	genericobject        Name: Gerenciamento de objetos       Version: 2.14.2     State: Installed / not activated                		Install Method: Marketplace 	resources            Name: Recursos humanos               Version: 3.0.4      State: Installed / not activated                		Install Method: Marketplace

</body>
</html>

**Comment by cedric-anne** [comment]
Hi,

It has been fixed by #14503.
