### ISSUE TITLE
cloning itilcategories

### ISSUE THREAD

**Issue by MLOcc** [glpi-project/glpi#14770]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.7

### Bug description

It's no longer possible to clone items in many dropdowns as it used to in 9.5 in massive actions.
In itilcategories  :
v9.5.7
![image](https://github.com/glpi-project/glpi/assets/71837011/f5ebb3b3-4533-4424-bc1d-9420d1e6448a)
v10.0.7
![image](https://github.com/glpi-project/glpi/assets/71837011/2754225b-160a-49a9-8abb-c9a2b503bcae)

**Comment by cconard96** [comment]
This is a regression, but not a bug. In 9.5, cloning was globally enabled and therefore available for items that should not and could not be cloned properly. For example, the clone option was showing for mandatory fields in ticket templates. In 10.0, we scaled it back to only affect specific items that were validated.

Enabling cloning for an item type could be as simple as adding the `Clonable` trait to the classes, but each one would need validated.

**Comment by cconard96** [comment]
Requested feature added in #16219 for GLPI 11.0.
