### ISSUE TITLE
impossible to add manually ip adress

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1478]
Hello

When I add an ip adress and save nothing is saved

glpi 9.2 same on glpi 9.1.1

**Comment by gitdevmod** [comment]
Hi, it's fixed by this commit https://github.com/glpi-project/glpi/commit/c69d7fa4ff6adde4702edb9d7f874668fc1040fe

**Comment by satyan01** [comment]
Hello

It works manually but not with plugin file injection

**Comment by wawax** [comment]
then please open an issue on the plugin's bugtracker.

thank you.
