### ISSUE TITLE
Notifications of a new task are not sent to the user/group performing the task if the task is assigned to a ticket via the ticket template or ticket rules.

### ISSUE THREAD

**Issue by Hantiel** [glpi-project/glpi#14787]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Notifications of a new task are not sent to the user/group performing the task if the task is assigned to a ticket via the ticket template or ticket rules. On manually adding a task to an open request - the notification is correctly sent. 

### Steps To reproduce

1. Create task 
2. Set task auto assignment via rules / template to ticket

**Comment by cedric-anne** [comment]
Hi,

Same behaviour has already been reported in #14022. I close this issue as it is a duplicate.
