### ISSUE TITLE
Empty "technician" in "assigen to" ticket from mail collector

### ISSUE THREAD

**Issue by Kaya84** [glpi-project/glpi#14780]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.12

### Bug description

When a user answer to a closed ticket (to reopen it or by mistake) an empty technician is added.

![image](https://github.com/glpi-project/glpi/assets/35736369/3d3ae045-4757-4a05-8e36-26fe07ff2c03)
![image](https://github.com/glpi-project/glpi/assets/35736369/9aafa234-5782-449b-96f1-1fd03ebc2763)

You can still work on ticket except for "actions" in the upper right corner (like merge as followup)

If i click on the x to remove I get 
"You don't have permission to perform this action." (even in super admin mode)

I suppose the error is somewhere when collecting the mail.

### Relevant log output

```shell
SELECT * FROM `glpi_tickets_users` WHERE `tickets_id` = '9374' ORDER BY `id` ASC

+-------+------------+----------+------+------------------+-------------------+
| id    | tickets_id | users_id | type | use_notification | alternative_email |
+-------+------------+----------+------+------------------+-------------------+
| 21590 |       9374 |        0 |    2 |                1 |                   |
| 21591 |       9374 |      383 |    1 |                1 |                   |
| 21592 |       9374 |       12 |    2 |                1 |                   |
| 21593 |       9374 |       17 |    2 |                1 |                   |
+-------+------------+----------+------+------------------+-------------------+
```

### Steps To reproduce

Enable mail collector
Create a ticket (via mail or web)
Close it with a solution
Answer to the solution mail with some words
Check the new created ticket

**Comment by trasher** [comment]
9.5 is no longer maitnained. Feel free to reopen if you reproduce with latest GLPI 10 release.
