### ISSUE TITLE
accociated element type in ticket template

### ISSUE THREAD

**Issue by pierre-guillot** [glpi-project/glpi#1479]
Hello,

use GLPI 9.1 whit : 
- Debian 8
- PHP 5.6.24
- apache 2.4.10
- mysql 5.5.50

I have configured default ticket template to chose "computer" as "accociated element type" (see here : https://framapic.org/gallery#cT01FnLXwIvB/pxAaV89Fv8FI.png). But, since Update (from 0.90.1 to 9.1), in simplified view, computer is not selected anymore.

**Comment by trasher** [comment]
I cannot reproduce on current 9.1/bugfixes branch. It probably solved in 9.1.2 or 9.1.3 reelase.
