### ISSUE TITLE
Business rules: Assign works as Add

### ISSUE THREAD

**Issue by DZbox** [glpi-project/glpi#14808]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6 with Behaviors plugin

### Bug description

Hi,

when I add a business rule for tickets and use rule action "Add" or "Assign" they both work as "Add".
As far as I know "Assign" action should replace already assigned persons or groups by the new one

### Steps To reproduce

- Create a rule "If category is changed to CategotyB, assign UserB to the ticket"
- Create a ticket with assigned UserA with category CategotyA
- Change the category to CategotyB
- UserB is added to UserA

**Comment by trasher** [comment]
Also,  you should try if you reproduce on latest stable release.

**Comment by trasher** [comment]
I close for now, feel free to reopen if you reproduce on latest release.
