### ISSUE TITLE
Doesn't count actors correctly when you hide a field

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#14844]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

Doesn't count actors correctly when you hide a field. 

I created a ticket and added 3 observers. After adding the ticket, I have 4 actors (requester and observers). I added another observer and assigned, and still have 4. I can assign the ticket to subsequent support users and it doesn't count either. The reason was that for the default form I covered the field "observer group".

If I create a ticket via FormCreator, I can add an observer group - it is not visible in the ticket after sending the ticket, but it is added (sometimes it appears, e.g. when I delete the following user, it will be displayed). 

### Steps To reproduce

1. Go to front/tickettemplate.form.php?id=1 > Hidden fields > set "watcher group" as hidden field.
2. Create a request by adding a user as an observer.
3. Check the sum of the actors.
4. Edit the ticket by adding another user as a follower and assign the ticket to someone.
5. Save it.
6. Check the sum of the actors again.

### Anything else?

![glpi_actors](https://github.com/glpi-project/glpi/assets/68922721/0f7fdaa2-1b2d-4858-8b7a-32e59865328f)

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue on GLPI 10.0.9. Actors count does not seems correct.
Here is a test ticket on which I randomly added actors, saved, and then reload the page:
![image](https://github.com/glpi-project/glpi/assets/33253653/cca381ad-f8e4-4265-ba0a-53bdcb0dcaa6)

**Comment by cedric-anne** [comment]
Should be fixed by #15391
