### ISSUE TITLE
The search results showing the machines which have already installed with sentinel when searched for the machines which do not have

### ISSUE THREAD

**Issue by blackpearl-2022** [glpi-project/glpi#14848]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

In Computer search when I filter by "does not contain Sentinel antivirus", if a computer has two or more antivirus, eg: defender and  Sentinel, that computer appears in the result, even though there I have set the filter to exclude:

![image](https://github.com/glpi-project/glpi/assets/118801689/1db5d319-0ab1-4962-950b-8061e30de72c)

### Steps To reproduce

Assets---->Computers---->search tab---- 'Antivirus Name---does not contain---SentinelOne
hit search button

### Your GLPI setup information

GLPI 10.0.6 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US
Operating system: Linux 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64
PHP 8.1.18 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at xxxxx Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxxxx@localhost/xxxxx
	Host info: Localhost via UNIX socket

**Comment by cconard96** [comment]
Instead of "Antivirus - Name does not contain sentinel", try changing the first dropdown to NOT and doing "Antivirus - Name contains sentinel"

**Comment by blackpearl-2022** [comment]
I Had tried that option with an entity defined. The filter show the machine
with sentinel also

**Comment by cedric-anne** [comment]
Hi,

This kind of search is not possible for now. It would be possible if `Antivirus` type was available in global rules, but this feature does not exists yet.
If your antivirus is also inventoried in softwares, you can use a global rule on softwares
![image](https://github.com/glpi-project/glpi/assets/33253653/a5d895c7-7d76-4093-8595-6013a5c91e4f)

I do not know if it is normal to have different behaviours between simple rules and global rules. @orthagh is this a normal behaviour?

**Comment by orthagh** [comment]
> different behaviours

Which is ?
