### ISSUE TITLE
import users active directory GLPI 9.1.1

### ISSUE THREAD

**Issue by jmalopez** [glpi-project/glpi#1484]
Hello, I have installed glpi version 9.1.1, I can not find the synchronization / import option of active directory users, you can help me.

Thank you

**Comment by Armin83** [comment]
https://translate.googleusercontent.com/translate_c?depth=1&hl=de&ie=UTF8&prev=_t&rurl=translate.google.de&sl=fr&tl=de&u=http://glpi-project.org/DOC/FR/glpi/config_auth_ldap.html&usg=ALkJrhjq-XqAUGggl7F-4xCjXJrjmQs_Wg

**Comment by jmalopez** [comment]
Hello, I connect perfectly GLPI with the active directory, the problem is that I do not find the option in version 9.1.1 to import users from the active directory, you know how I can import them?

* versión 9.1:
https://bartoc3.wordpress.com/2014/02/11/configurar-glpi-con-active-directory-en-windows-server-2012/comment-page-1/

Thank you

**Comment by Armin83** [comment]
Bulk - super-admin

1. Administration
2. users
3. ldap directory link
4. search without criteria
5. mark all
6. (you import eventually service user too depend on your structure)



Single - Can be done in ticket. If the user / profile have right rights to create a user)

**Comment by ronnydeb** [comment]
I think jlopez have the same issue I have:
link to add user or sync is not appearing

![capture1](https://cloud.githubusercontent.com/assets/25041438/21823908/1556ab4c-d74b-11e6-9dd7-45c2476fdeba.PNG)
![capture2](https://cloud.githubusercontent.com/assets/25041438/21823909/1557e4e4-d74b-11e6-9768-e178348bd852.PNG)

**Comment by jmalopez** [comment]
Yes, Correct, the link does not exist, we have the same problem in version 9.1.1, can someone help us?

**Comment by jmalopez** [comment]
https://cloud.githubusercontent.com/assets/25041438/21823908/1556ab4c-d74b-11e6-9dd7-45c2476fdeba.PNG

**Comment by Armin83** [comment]
`Setup - Authentication - LDAP directories `
The state is active ?
Do you have set as default and use default OR You have choose it in `administration - enities -Advanced information - LDAP directory of an entity`
(Use default is at the same setting location.)

**Comment by ronnydeb** [comment]
solved, thanks for your help.
Option Active was disable, I chose "yes" and apper the option LDAP
Thanks !!!

![capture3](https://cloud.githubusercontent.com/assets/25041438/21852020/8446a874-d7df-11e6-8073-837c18911844.PNG)

**Comment by jmalopez** [comment]
Thankc solved, thanks for your help.

**Comment by Armin83** [comment]
no problem - @jmalopez  please close it
