### ISSUE TITLE
Inventory: Windows Edition is not updated anymore

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi#14850]
# Bug description

### Before:
Using https://my-glpi-server/plugins/fusioninventory/
The OS name is `<OPERATINGSYSTEM><NAME>` and the Edition is Enterprise (info probably extracted from `<OPERATINGSYSTEM><FULL_NAME>`)
![image](https://github.com/glpi-project/glpi/assets/70358310/e009833b-2f66-4086-ba2e-f1f80b84d933)

### Now:
Using https://my-glpi-server/marketplace/glpiinventory/
The OS name is `<OPERATINGSYSTEM><FULL_NAME>` and the Edition is not updated anymore
![image](https://github.com/glpi-project/glpi/assets/70358310/de564677-1937-451d-93bc-5f3d588abb61)
![image](https://github.com/glpi-project/glpi/assets/70358310/bbdff422-122e-43f0-b539-2dfd40b903d7)

# GLPI setup information

Server: GLPI 10.0.7 with Native Inventory
Clients: same behavior with either FusionInventory agent or GLPI-Agent

# Anything else?

Some may argue that the agent is not reporting an `<OPERATINGSYSTEM><EDITION>` value so GLPI server cannot know it and extracting it from another field is dirty.
So I will not advise if this issue should be handle at Agent level or Server level, but as a end-user this is a regression as the result is different than before and less detailed.

May be related to #13298

**Comment by trasher** [comment]
We decided not to keep the way FusionInventory to find OS information. Instead of that, we've implemented rules that can be used for that. 
See the "operating system" rules, several examples (inactive) are provided, and you can of course define your own.

**Comment by MarcSamD** [comment]
Dear @trasher 
Thank you for your reply but there is no field available for the Edition of the OS in glpiinventory/front/collectrule.php :
![image](https://github.com/glpi-project/glpi/assets/70358310/b909a949-29c5-436f-bf37-1a9f5bd44b46)

Also I don't see any examples rules...

**Comment by trasher** [comment]
OS ruels are core, not part of the plugin

**Comment by MarcSamD** [comment]
Omg... a litlle more explanation would have been welcome as this is overcomplicated and a little simplification would not hurt.

_You want to manage how computers are imported from the agent to the server? What about...
Trying to setup a rule in the dedicated plugin rules, like the "computer collect rules", make sense ? => **Wrong**
Ok, let's try to dig in the huge menu "Rules", I guess that "Business rules for assets" should be the right choice => **Wrong again, you lose !**_

_The correct answer for setting up this rule was... **Dictionaries** ! (not even a rule menu...)_

Joke aside, thank you for your time, and hopefully someone will be smart enough to design this a bit more user-friendly (not me :)
