### ISSUE TITLE
PDF with non-ASCII symbols

### ISSUE THREAD

**Issue by DDimly** [glpi-project/glpi#14868]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Any save as PDF (list of task or report, puts "?" on any non ASCII symbols
I think this is resolved issue, but i did't find any resolution about this problem

Where i can check correctly param of my system?

**Comment by DDimly** [comment]
> You should first try if you reproduce using latest stable release; and provide all requested information.

I found topic about this problem in 2008 year
I don't sure problem was resolved in latest build if no resolved early
And i can't updating productive system any time

**Comment by cedric-anne** [comment]
1. Community maintainers cannot remember all of the fixes made since January 24.
2. The way to reproduce your issue is not really clear.
3. You did not provide requested information. We ask them because it may have an impact on bug reproduction.

Community maintainers do their best to fix bugs. They often run out of time to process everything, and tend to deal with the users who help them best.

> I found topic about this problem in 2008 year

Do you have a link to this topic?

> And i can't updating productive system any time

You can try to reproduce on a test server.

**Comment by DDimly** [comment]
About topic 2008 - it was other resource, and i'm lost it in history, but found others

1. In Ukraine in 2010 year: https://www.thin.kiev.ua/unix/39-unix/189-ocs-inventory-ng-glpi.html
Now i didn't find this function and file - topic too old.
Translated:
> By default, when exporting to PDF, question marks are displayed instead of Russian letters, this happens for two reasons: the standard function exports data in ISO-8859-1 encoding, which is supported by the default font. The hint was found on the OPENNET forum. We replace the utf8_decode function call with utf8_decode_cyr in the /var/www/glpi/inc/export.function.php script.
> $ sudo perl -p -i -e 's/utf8_decode/utf8_decode_cyr/g' export.function.php
inc/export.function.php:
> And we add a description of the utf8_decode_cyr function itself to export.function.php.
> function utf8_decode_cyr($value){
>          return iconv("UTF-8","Windows-1251",$value);
> }

2. Russian topic 2011 year - https://forum.glpi-project.org/viewtopic.php?id=22709
Where reolved by way: change in source codepage 1251 to 1251 and change fonts files in folder /lib/ezpdf/fonts

----

I installed test server 10.0.7 and checked - problem has.
Reproducing
1. Put in any data which exported in PDF - cyrrylic symbols. Exapmle in subject of request
2. Export list of request in PDF any format
3. Get "??????" as attached SCR1.png (in your test - in subject only)
Any other PDF export also - reports etc..

Other way test - you can change locale GLPI on Russian and export PDF - you get "?????" in title and column name

I think "????"  it's mistake with codepage
If you see some like chinesse or egipet yerogliph - then you repaired codepage and have next problem with wrong fonts

![scr1](https://github.com/glpi-project/glpi/assets/114323746/d30254a2-5668-43c3-adbd-18999f640b2d)

**Comment by trasher** [comment]
> About topic 2008 - it was other resource, and i'm lost it in history, but found others
> [...]

Seems like its absolutely not the same issue here.

> [...]
> Other way test - you can change locale GLPI on Russian and export PDF - you get "?????" in title and column name

OK, I can reproduce that way, Russian language is not the only one impacted; but issue seems limited to cyrillic characters (spanish and franch are OK for example).

**Comment by trasher** [comment]
Sounds like this is just a font issue; the default one does not contains Cyrillic characters, or at least not all. Change the used font in config, logout and login again, your issue will be solved.

**Comment by trasher** [comment]
I'd advise to use "DejaVuSans", it works well with Russian, and also Arabic (some other are not supported but it seems better than default "Helvetica").

**Comment by DDimly** [comment]
> I'd advise to use "DejaVuSans", it works well with Russian, and also Arabic (some other are not supported but it seems better than default "Helvetica").

Great! Thank you - "DejaVuSans" is working
I tried change to Times New Roman early - not helped.

**Comment by trasher** [comment]
The default font has been changed to DejaVuSans for new instances. FOr existing ones, the only way is to change from preferences, since GLPI updates never changes existing preferences.
