### ISSUE TITLE
Public reminders don't appear for targets

### ISSUE THREAD

**Issue by jorgecamargosdb** [glpi-project/glpi#14873]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3 e 10.0.7

### Bug description

When you include a public reminder and select a target other than by entity, the reminder is not displayed on the home screen of the target users, either by group or profile.

I validated the test in three versions, 10.0.3, 10.0.6 and 10.0.7. Working correctly only on 10.0.06.

Here are the images

GLPI 10.0.3
![image](https://github.com/glpi-project/glpi/assets/23311692/0aaaa157-6106-46bd-99dc-63f757e8ede0)
![image](https://github.com/glpi-project/glpi/assets/23311692/fcfae35e-8317-4bd4-b15e-b49d60dfa6d0)
![image](https://github.com/glpi-project/glpi/assets/23311692/1f8f9287-9ced-4277-8ad5-3b473916e68f)
![image](https://github.com/glpi-project/glpi/assets/23311692/2d55d8da-b826-409f-959d-7f5c1802519e)
![image](https://github.com/glpi-project/glpi/assets/23311692/daa98d04-7c4c-42ee-9fd3-99b57fb64482)

Impersonating the vision of a user who has the profile Manager and Services, does not appear to him p reminder on the home screen

the same occurs in version 10.0.7
![image](https://github.com/glpi-project/glpi/assets/23311692/da92b78d-cf3e-466c-9050-79624db5408a)
![image](https://github.com/glpi-project/glpi/assets/23311692/b5867b24-b406-47b0-b623-4d31fc9f8ab4)
![image](https://github.com/glpi-project/glpi/assets/23311692/5d8707b9-9cde-4a13-8a69-fcdce430dc03)
![image](https://github.com/glpi-project/glpi/assets/23311692/ec6d26d9-42ed-4a4f-beb2-f9387e21484c)

In version 10.0.6 this error does not occur, presenting in a normal way the reminder to the targets
![image](https://github.com/glpi-project/glpi/assets/23311692/b50ea4bb-8926-4d12-91d1-431beb02c6cc)
![image](https://github.com/glpi-project/glpi/assets/23311692/998e9fc1-1b3a-4d80-945e-fe5353e22b7e)
![image](https://github.com/glpi-project/glpi/assets/23311692/1045f41e-d707-4092-80ba-2f1d143dd203)
![image](https://github.com/glpi-project/glpi/assets/23311692/26428589-f135-4160-af4c-94f1e3295497)

### Page URL

https://treinamento.servicedeskbrasil.com.br/

### Steps To reproduce

1. Create a target reminder for a group or profile;
2. Using a user who is a member of the group or assigned to the target profile of the reminder, check the home screen
3. 3. If you target the profile, make sure it has read access to public reminders

### Your GLPI setup information

GLPI 10.0.7 ( => /usr/share/glpi)
Installation mode: TARBALL
Current language:en_US

Operating system: Linux a547537184c0 5.15.74-1-pve #1 SMP PVE 5.15.74-1 (Mon, 14 Nov 2022 20:17:15 +0100) x86_64
PHP 8.0.28 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, selinux, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.37 (AlmaLinux) ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.37
Server Software: Percona Server (GPL), Release 44, Revision 27f408641db
	Server Version: 5.7.41-44
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@glpi-10-treinamento-db/glpi
	Host info: glpi-10-treinamento-db via TCP/IP
	
PHP version (8.0.28) is supported.PHP version (8.0.28) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.41) is supported.Database engine version (5.7.41) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files/data-documents has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated.Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files/data-documents has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.Write access to /usr/share/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.

### Anything else?

If any further evidence is needed, please let us know so we can provide it.

**Comment by cconard96** [comment]
I cannot recreate the issue on the commit tagged for the 10.0.7 release. I created a reminder and added a group as the target. I then impersonated a user in that group and the reminder showed up on their dashboard as a public reminder.

**Comment by cedric-anne** [comment]
It seems related to #13650.

**Comment by jorgecamargosdb** [comment]
@cconard96 I did the same, and according to the images, it was not presented on the home screen, As @cedric-anne commented that this issue is duplicated from 13650, I'll follow up there.

**Comment by trasher** [comment]
Closing as duplicate
