### ISSUE TITLE
Updating GLPI 10.0.6 to 10.0.7 does not work

### ISSUE THREAD

**Issue by SteBoun** [glpi-project/glpi#14870]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello

I followed all the steps to update my GLPI to 10.0.7 but when I get to the installation page, it says "The action you performed is not authorized." 
I've checked my error logs and access.log and nothing to report.
I attach what I have as a page and then inspect the page with my browser (Firefox v.111)

**Comment by SteBoun** [comment]
![Captdure](https://github.com/glpi-project/glpi/assets/50909713/86d094c0-194d-403b-9f64-e4cfec57ea34)
![Capture](https://github.com/glpi-project/glpi/assets/50909713/77d09185-3f23-4c7d-b52e-3ce3537e7d78)

**Comment by cconard96** [comment]
Is the error occurring on the first update screen? If you check the Network tab in Firefox's developer tools (F12), do any of the responses have error messages as the response?

Have you tried clearing your cache/cookies and then restarting the update process in the web interface by manually going back to the update page (not hitting the refresh button), or trying the update in a different supported browser like MS Edge or Chrome?

**Comment by SteBoun** [comment]
Hi, I've already cleared the browser cache and then I've just tried with chrome/edge and I still get the same error.

**Comment by trasher** [comment]
Please answer all questions.

**Comment by SteBoun** [comment]
The error doesn't occur on the first screen but just after accepting the rules and then the f12 in firefox only gives the message I gave you just before in the screenshot.

**Comment by cedric-anne** [comment]
Hi,

It could probably enhanced, but you have to use the "retry" button at the end of the page to launch a new prerequisites check. Indeed, installation/update process does not support page reload from browser.
