### ISSUE TITLE
New ticket page reloads when actors are added

### ISSUE THREAD

**Issue by CartCaved** [glpi-project/glpi#14881]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

In the screen for adding a new ticket, most fields can be changed/edited without a full page reload. However, when adding actors, a full page reload is initiated.

See https://forum.glpi-project.org/viewtopic.php?pid=501538#p501538 for confirmation by @cconard96 of the behaviour and the relevant code. It's unclear what the purpose is, if it was intentionally added in v10.

### Steps To reproduce

1. Create new ticket
2. Add actor
3. Page reloads

**Comment by tomolimo** [comment]
Hello,
This behaviour is also a critical issue for us... due to response time that is added at ticket creation
Thank you,
Regards,
Tomolimo

**Comment by CartCaved** [comment]
Hi - I see the commit that would close this issue would only change the behaviour for non-requesters. 

What is the purpose of keeping a full reload when adding to the requester field?

**Comment by repentandliveholy** [comment]
Hello! Could you please explain for dummies, how can it be fixed?
