### ISSUE TITLE
Update copyright header on all files

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1488]
New year <=> licence headers to update on each file (?)

As it's the update time, is the  
```
* @version $Id$
```
 still used ?
On releases, the tag appears not to be computed 

And last question : would it be added a mention like "and all projects contributors" on the header ? (sens ? legal ?)

Regards

**Comment by trasher** [comment]
I guess headers will be changed, but I'm unsure, I'll let @orthagh answer that.

The`$Id$` stuff is no longer used since the project switched to git. It used to be filled on each commit when using SVN.

I have not idea for the last question, I'll let another one answer too :)

**Comment by orthagh** [comment]
So after revert of #1536, some suggestions: 

- alter the tools/HEADER file to remove @version information and add contributors
- launch tools/modify_headers.pl to apply this header

**Comment by AnaelMobilia** [comment]
Could be great to have docs on tools too : I manually made changes as there was too many differents file header...

On my pull request, I made too :
  - Add header on js files
  - Remove (only if empty) "/** @file -- * @brief -- */"
  - Fix headers on .pl and .sh tools
  - Add headers on .htaccess files

IMHO, actual files have get various tools running on it for headers / comments / ...
Only a manual action can standardize all of these (eg remove empty docblock). And only after that we could use an automated update ;-)
