### ISSUE TITLE
Inventory - Location rule executed before link rule

### ISSUE THREAD

**Issue by Aekinox** [glpi-project/glpi#14902]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.7

### Bug description

location rules are executed before linking rules which change the location of unlinked devices for mobile devices with glpi-agent
It would be better to do the opposite

### Steps To reproduce

Create 2 location rules with TAG and with CIDR for example (for enterprise and home office)
Use a laptop connected to an external monitor
On first inventory, laptop is imported with a link to an external monitor on first location.
Change laptop location maching second location without the external monitor and wait new automatic inventory.
In monitor history, you can see that:
-> location is updated with that of laptop then link is removed
-> monitor's location is wrong

**Comment by trasher** [comment]
Please provide more information on how to reproduce your issue.

**Comment by Aekinox** [comment]
- Create 2 location rules with TAG and with CIDR for example (for enterprise and home office)
- Use a laptop connected to an external monitor
- On first inventory, laptop is imported with a link to an external monitor on first location.
- Change laptop location maching second location without the external monitor and wait new automatic inventory.
- In monitor history, you can see that:
- -> location is updated with that of laptop then link is removed
- -> monitor's location is wrong

**Comment by Aekinox** [comment]
history example
![image](https://github.com/glpi-project/glpi/assets/54978317/4322015c-98a3-4955-9ebf-fd99bca82373)

**Comment by stonebuzz** [comment]
Maybe due to asset configuration

![image](https://github.com/glpi-project/glpi/assets/7335054/924f8bbf-7d01-4f22-9663-87c7826bb78c)

1. Inventory hendle computer
2. The computer changes location and is propagated to the connected elements by this configuration.
3. Inventory handle monitor
4. It realizes that the monitor no longer shows up in the inventory
5. Inventory deletes link with monitor


I don't know if we can do any better:
the inventory process must always take care of the main asset  (ie: computer) before managing the connected elements (ie: monitor)

**Comment by Aekinox** [comment]
Yes that's it
ideally, the location copy process should be executed after managing the connected elements.

**Comment by stonebuzz** [comment]
This configuration propagate location when main asset is update ("When connecting or updating").

it's going to be tricky to do it properly.

That would require bypassing the core's behaviour, just for the inventory.

Not sure we want to go that way

It's going to take a lot of effort for a meagre result

Best regards
