### ISSUE TITLE
Mail sending problems php error

### ISSUE THREAD

**Issue by tpicard17** [glpi-project/glpi#14901]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.5

### Bug description

I have a problem sending mail on glpi. In the php-errors.log of glpi the problem comes from the NotificationEventMailing.php file. Here are the logs in detail :

`[2023-06-13 09:02:27] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "filepath" in /var/www/html/glpi/src/NotificationEventMailing.php at line 295
  Backtrace :
  src/QueuedNotification.php:602                     NotificationEventMailing::send()
  src/CronTask.php:1018                              QueuedNotification::cronQueuedNotification()
  front/crontask.form.php:52                         CronTask::launch()

[2023-06-13 09:02:27] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/src/NotificationEventMailing.php at line 296
  Backtrace :
  src/QueuedNotification.php:602                     NotificationEventMailing::send()
  src/CronTask.php:1018                              QueuedNotification::cronQueuedNotification()
  front/crontask.form.php:52                         CronTask::launch()

[2023-06-13 09:02:27] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/src/NotificationEventMailing.php at line 297
  Backtrace :
  src/QueuedNotification.php:602                     NotificationEventMailing::send()
  src/CronTask.php:1018                              QueuedNotification::cronQueuedNotification()
  front/crontask.form.php:52                         CronTask::launch()

[2023-06-13 09:02:27] glpiphplog.CRITICAL:   *** Uncaught Exception DivisionByZeroError: Division by zero in /var/www/html/glpi/src/NotificationEventMailing.php at line 301
  Backtrace :
  src/QueuedNotification.php:602                     NotificationEventMailing::send()
  src/CronTask.php:1018                              QueuedNotification::cronQueuedNotification()
  front/crontask.form.php:52                         CronTask::launch()

[2023-06-13 09:02:27] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/var/www/html/glpi/files/_log/cron.log): Failed to open stream: Permission denied in /var/www/html/glpi/src/Toolbox.php at line 598
  Backtrace :
  src/Toolbox.php:598                                error_log()
  src/CronTask.php:1030                              Toolbox::logInFile()
  front/crontask.form.php:52                         CronTask::launch()`
`PHP Warning:  Module "intl" is already loaded in Unknown on line 0
PHP Warning:  Undefined array key "filepath" in /var/www/html/glpi/src/NotificationEventMailing.php on line 290
PHP Warning:  Undefined array key "filepath" in /var/www/html/glpi/src/NotificationEventMailing.php on line 295
PHP Notice:  getimagesize(): Read of 8192 bytes failed with errno=21 Is a directory in /var/www/html/glpi/src/NotificationEventMailing.php on line 295
PHP Notice:  getimagesize(): Error reading from /var/www/html/glpi/files/! in /var/www/html/glpi/src/NotificationEventMailing.php on line 295
PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/glpi/src/NotificationEventMailing.php on line 296
PHP Warning:  Trying to access array offset on value of type bool in /var/www/html/glpi/src/NotificationEventMailing.php on line 297
Uncaught Exception DivisionByZeroError: Division by zero in /var/www/html/glpi/src/NotificationEventMailing.php at line 301`

**Comment by cedric-anne** [comment]
Hi,

Some issues related to image handling in notification cron have been fixed in GLPI 10.0.6/10.0.7. Feel free to reopen if issue persist on GLPI 10.0.7.

**Comment by cedric-anne** [comment]
> `glpiphplog.WARNING: *** PHP Warning (2): Undefined array key "filepath" in /var/www/html/glpi/src/NotificationEventMailing.php at line 295`

This error is due to reference to a document that has been deleted in database. #14903 should permit to not block notifications sending in such case.

> `glpiphplog.WARNING: *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/src/NotificationEventMailing.php at line 296`
> `glpiphplog.WARNING: *** PHP Warning (2): Trying to access array offset on value of type bool in /var/www/html/glpi/src/NotificationEventMailing.php at line 297`
> `glpiphplog.CRITICAL: *** Uncaught Exception DivisionByZeroError: Division by zero in /var/www/html/glpi/src/NotificationEventMailing.php at line 301`

This error has been fixed by #14756.

> `glpiphplog.WARNING: *** PHP Warning (2): error_log(/var/www/html/glpi/files/_log/cron.log): Failed to open stream: Permission denied in /var/www/html/glpi/src/Toolbox.php at line 598`

This error is due to wrong file permissions on your server.
