### ISSUE TITLE
Mail Collector

### ISSUE THREAD

**Issue by Ricko987** [glpi-project/glpi#14910]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

So I'm trying to collect emails with the "Collector," but I have an issue: "Cannot change folder, maybe it does not exist."

So I'm on an RHEL distribution, using Postfix as the MTA, Dovecot as the MDA, and I have a local SMTP server.

I can send mail to my account present on my SMTP server, and I can connect to IMAP on my local machine using "openssl s_client -connect <my machine>:993".

After clicking on "collect emails," I can see that GLPI manages to connect to my IMAP server.

I think I misunderstand the way I should use Dovecot.

I'm using Maildir as the mail location: mail_location = maildir:~/Maildir

In my collector options : 

Server : 127.0.0.1
Connection option: imap ssl no-validate-cert norsh
Entry messages folder: new

### Page URL

front/mailcollector.form.php?id=3

### Steps To reproduce

1)Go to collector
2)Go on actions
3)Click collect mails"

### Your GLPI setup information

I can't put my GLPI configs "Security policy".

### Anything else?

Do you know which folder the GLPI mail collector tries to access?

**Comment by cedric-anne** [comment]
Hi,

By default, the mail collector will select the `INBOX` folder.
