### ISSUE TITLE
User should be forced to select a rating for satisfaction survey, no default value.

### ISSUE THREAD

**Issue by pvasener** [glpi-project/glpi#14919]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When a user is reaching the satisfaction survey screen, the rating field is defaulted to 3 stars. Many of our users leave this field to 3 stars instead of providing a real rating. I think it would make more sense to have no default on this field to force the user to provide a relevant rating on his own.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.7 ( => /var/www/html/glpi/prod/www-root)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux VM-GLPI 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at helpdesk.aup.edu Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.43
Server Software: mariadb.org binary distribution
	Server Version: 10.10.5-MariaDB-1:10.10.5+maria~ubu2204
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: aup-glpi@localhost/glpi_prod
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.10.5) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/prod/files/_cache has been validated.
Write access to /var/www/html/glpi/prod/config has been validated.
Write access to /var/www/html/glpi/prod/files/_cron has been validated.
Write access to /var/www/html/glpi/prod/files has been validated.
Write access to /var/www/html/glpi/prod/files/_dumps has been validated.
Write access to /var/www/html/glpi/prod/files/_graphs has been validated.
Write access to /var/www/html/glpi/prod/files/_lock has been validated.
Write access to /var/www/html/glpi/prod/files/_pictures has been validated.
Write access to /var/www/html/glpi/prod/files/_plugins has been validated.
Write access to /var/www/html/glpi/prod/files/_rss has been validated.
Write access to /var/www/html/glpi/prod/files/_sessions has been validated.
Write access to /var/www/html/glpi/prod/files/_tmp has been validated.
Write access to /var/www/html/glpi/prod/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/prod/www-root/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi/prod/www-root"
GLPI_CONFIG_DIR: "/var/www/html/glpi/prod/config"
GLPI_VAR_DIR: "/var/www/html/glpi/prod/files"
GLPI_LOG_DIR: "/var/www/html/glpi/prod/log"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/prod/www-root/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/prod/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/prod/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/prod/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/prod/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/prod/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/prod/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/prod/files/_lock"
GLPI_PICTURE_DIR: "/var/www/html/glpi/prod/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/prod/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/prod/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/prod/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/prod/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/prod/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/prod/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/html/glpi/prod/www-root/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/html/glpi/prod/www-root/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/prod/www-root/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/prod/www-root/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/prod/www-root/marketplace/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/prod/www-root/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/prod/www-root/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/prod/www-root/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/prod/www-root/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/prod/www-root/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/prod/www-root/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/prod/www-root/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/prod/www-root/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/prod/www-root/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/prod/www-root/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/prod/www-root/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/prod/www-root/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/prod/www-root/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/prod/www-root/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/prod/www-root/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/prod/www-root/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/prod/www-root/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/prod/www-root/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/prod/www-root/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/prod/www-root/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/prod/www-root/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/prod/www-root/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/prod/www-root/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/prod/www-root/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/prod/www-root/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/prod/www-root/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/prod/www-root/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/prod/www-root/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/prod/www-root/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/prod/www-root/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/prod/www-root/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/prod/www-root/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/prod/www-root/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/prod/www-root/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/prod/www-root/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/prod/www-root/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/prod/www-root/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/prod/www-root/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/prod/www-root/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/prod/www-root/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'SRV-DC.aup.local', Port: '389', BaseDN: 'OU=AUPUsers,DC=aup,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'ldap', Use TLS:
		none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (helpdesk@aup.edu@smtp.office365.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Additional Fields              Version: 1.20.6     State: Enabled                                 
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Behaviours                     Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	financialreports     Name: Financial reports              Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 10.0.3+1.0 State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.1      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	satisfaction         Name: More satisfaction              Version: 1.6.1      State: Enabled                                 
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.5      State: Installed / not activated               
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.3     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Orders management              Version: 2.10.4     State: Enabled                                 
		Install Method: Marketplace
	additionalalerts     Name: Others alerts                  Version: 2.4.0      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	reports              Name: Reports                        Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	reservation          Name: Reservation                    Version: 2.4.4      State: Installed / not activated               
		Install Method: Manual
	screenshot           Name: Screenshot                     Version: 2.0.2      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Installed / not activated               
		Install Method: Marketplace
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.1   State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by blax50** [comment]
Interested too :)

**Comment by cconard96** [comment]
Feel free to make this suggestion on the suggestions website. We only track bugs here.
https://suggest.glpi-project.org
