### ISSUE TITLE
API search returns wrong entities_id for domain object

### ISSUE THREAD

**Issue by Berthe01** [glpi-project/glpi#14938]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hi there,

It seems that when using the RESTAPI to search a domain, parent entities_id is return in the JSON response instead of the real entities_id for that domain.

### Page URL

{{APIUrl}}/search/domain?

### Steps To reproduce

1. Get domain using APIREST ({{APIUrl}}/domain/{{id}}) :

{
    "id": 1,
    "name": "example.fr",
    "entities_id": 8,
    "is_recursive": 0,
    "domaintypes_id": 0,
    "date_expiration": "2023-06-30 12:00:00",
    "date_domaincreation": "2023-06-07 12:00:00",
    "users_id_tech": 0,
    "groups_id_tech": 0,
    "is_deleted": 0,
    "comment": "",
    "is_template": 0,
    "template_name": null,
    "is_active": 1,
    "date_mod": "2023-06-16 11:31:26",
    "date_creation": "2023-01-05 17:05:53",
...
}

2. List searchoptions :

...
"80": {
        "name": "Entité",
        "table": "glpi_entities",
        "field": "completename",
        "datatype": "dropdown",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "notcontains",
            "equals",
            "notequals",
            "under",
            "notunder"
        ],
        "uid": "Domain.Entity.completename"
    },
    "81": {
        "name": "Identifiant d'entité",
        "table": "glpi_entities",
        "field": "entities_id",
        "datatype": "",
        "nosearch": false,
        "nodisplay": false,
        "available_searchtypes": [
            "contains",
            "notcontains"
        ],
        "uid": "Domain.Entity.entities_id"
    },
...

3. Use search API URL ({{APIUrl}}/search/domain?criteria[0][link]=AND&criteria[0][field]=1&criteria[0][searchtype]=contains&criteria[0][value]=example):

{
    "totalcount": 1,
    "count": 1,
    "sort": [
        "1"
    ],
    "order": [
        "ASC"
    ],
    "data": [
        {
            "1": "example.fr",
            "80": "XXXX > XXXX > XXXX  > Test-Cust02",
            "3": null,
            "2": null,
            "6": "2023-06-30 12:00:00",
            "7": "",
            "8": null,
            "81": 7
        }
    ],
    "content-range": "0-0/1"
}

4. See the wrong value for "81" [Domain.Entity.entities_id] field BUT Value of "80" [Domain.Entity.completename] field is the good one. Note that 7 is the id of parent entity with id 8.

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.7 ( => /var/www/glpi-prod/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux support.****.**** 5.15.0-73-generic #80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, readline, session, shmop, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at support.****.**** Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Server Software: (Ubuntu)
	Server Version: 8.0.33-0ubuntu0.22.04.2
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1/glpi-prod
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.2-1ubuntu2.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.33) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi-prod/files/_cache has been validated.
Write access to /var/www/glpi-prod/config has been validated.
Write access to /var/www/glpi-prod/files/_cron has been validated.
Write access to /var/www/glpi-prod/files has been validated.
Write access to /var/www/glpi-prod/files/_dumps has been validated.
Write access to /var/www/glpi-prod/files/_graphs has been validated.
Write access to /var/www/glpi-prod/files/_lock has been validated.
Write access to /var/www/glpi-prod/files/_pictures has been validated.
Write access to /var/www/glpi-prod/files/_plugins has been validated.
Write access to /var/www/glpi-prod/files/_rss has been validated.
Write access to /var/www/glpi-prod/files/_sessions has been validated.
Write access to /var/www/glpi-prod/files/_tmp has been validated.
Write access to /var/www/glpi-prod/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi-prod/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi-prod/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi-prod/config"
GLPI_VAR_DIR: "/var/www/glpi-prod/files"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/glpi-prod/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi-prod/files"
GLPI_CACHE_DIR: "/var/www/glpi-prod/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi-prod/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi-prod/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi-prod/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi-prod/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi-prod/files/_lock"
GLPI_PICTURE_DIR: "/var/www/glpi-prod/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi-prod/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi-prod/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi-prod/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi-prod/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi-prod/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi-prod/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/glpi-prod/glpi/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi-prod/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi-prod/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi-prod/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi-prod/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi-prod/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi-prod/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi-prod/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi-prod/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi-prod/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi-prod/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi-prod/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi-prod/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi-prod/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi-prod/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi-prod/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi-prod/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi-prod/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi-prod/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi-prod/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi-prod/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi-prod/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi-prod/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi-prod/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi-prod/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi-prod/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi-prod/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi-prod/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi-prod/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi-prod/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi-prod/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi-prod/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi-prod/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi-prod/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi-prod/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi-prod/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi-prod/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi-prod/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi-prod/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi-prod/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi-prod/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://10.12.0.80', Port: '636', BaseDN: 'DC=customers,DC=****', Connection filter: none, RootDN:
		'CUSTOMERS\Administrateur', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	connections          Name: Connexions                     Version: 10.0.0     State: Not installed                           
		Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.14.3     State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by cconard96** [comment]
I confirmed the issue. Can you test the fix in #14939?

**Comment by Berthe01** [comment]
Hi,

Your fix solves the issue !

Thanks a lot,


I tried to make tests with other objects type (contracts, computer) but these don't use entity id as a search option.
From my point of view, that should be an available searchoption for all item types as they are always related to an Entity, and entities_id is sometimes (often for me) more convenient / efficient to use vs Entity.completename.

Should I post an enhancement issue about this ?

**Comment by cconard96** [comment]
I don't know how much use there is to have a search option for the entity ID for use in the web interface, and GLPI 10.1 will have a new API alongside the existing one which already shows the ID, name and complete name.
For the current API, complete names are supposed to be unique, so i guess it is possible to do a search on entities with that complete name to get the ID.
