### ISSUE TITLE
Uncaught Exception Error: Call to undefined function mysqli_report() in /var/www/html/src/DBmysql.php at line 226

### ISSUE THREAD

**Issue by wolfsden3** [glpi-project/glpi#14930]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

System suddenly stopped, and for no reason because nobody made any updates or changes, checking email.  I have to log into the glpi account and manually click the button on the web interface in receivers to check email.  It's been working for a year and suddenly breaks.  I went to the cron and ran the php cron manually without the null so I could see the errors / output and this is what I get.

root@helpdesk:/var/www/html/src# php /var/www/html/front/cron.php
Uncaught Exception Error: Call to undefined function mysqli_report() in /var/www/html/src/DBmysql.php at line 226

I tried to patch the DBmysql.php with the bug fix version on the git for 10.0 and it didn't work.  I still get this same error!

Line 226 says:  "$this->setConnectionCharset();" <-- larger code snippet below...

`        if ($this->dbh->connect_error) {
 260             $this->connected = false;
 261             $this->error     = 1;
 262         } else if (!defined('MYSQLI_OPT_INT_AND_FLOAT_NATIVE')) {
 263             $this->connected = false;
 264             $this->error     = 2;
 265         } else {
 266             $this->setConnectionCharset();
 267
 268            // force mysqlnd to return int and float types correctly (not as strings)
 269             $this->dbh->options(MYSQLI_OPT_INT_AND_FLOAT_NATIVE, true);
 270
 271             $this->dbh->query("SET SESSION sql_mode = (SELECT REPLACE(@@sql_mode, 'ONLY_FULL_GROUP_BY', ''))");
 272
 273             $this->connected = true;
 274
 275             $this->setTimezone($this->guessTimezone());
 276         }
 277     }
`

The bug fix php file for that off the git actually breaks my web interface entirely so I had to restore the original file.

### Relevant log output

```shell
php /var/www/html/front/cron.php
Uncaught Exception Error: Call to undefined function mysqli_report() in /var/www/html/src/DBmysql.php at line 226
```

### Steps To reproduce

Run the cron from the crontab that's been working forever and a day to do the email checking from the mail receiver.

### Your GLPI setup information

GLPI 10.0.3 ( => /var/www/html)
Installation mode: TARBALL
Current language:en_US
NGINX
MariaDB
PHP
PHP-FPM

**Comment by trasher** [comment]
GLPI makes call to that function at each database connexion, so if web UI is workinjg, that's not a bug.

You run cron as root, which is often a bad idea for files permissions; your issue is probably due to environment setup (not runnin gthe same PHP version, or using a different configuration for web and cli).
