### ISSUE TITLE
Synchro LDAP

### ISSUE THREAD

**Issue by BNMorty38** [glpi-project/glpi#14933]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

Bonjour, 

Je viens d'installer GLPI sur un serveur Windows 2019 avec Xampp. L'installation s'est bien déroulé et GLPI fonctionne. 
J'ai fait une synchro avec mon annuaire LDAP. Test ok.
Mais lorsque je veux importer des users depuis mon annuaire LDAP, j'ai une erreur: 
**Warning: ldap_search(): Search: Bad search filter in D:\xampp\htdocs\glpi\src\AuthLDAP.php on line 1922**
**Aucun utilisateur à importer**

J'ai vérifié dans le fichier AuthLDAP.php, je n'ai aucune ligne ldap_search()

Une idée? 

Aussi, j'ai le message sur ma page d'accueil " La configuration du dossier racine du serveur web n'est pas sécurisée car elle permet l'accès à des fichiers non publics. Référez-vous à la documentation d'installation pour plus de détails."

Comment corriger? 

Je vous remercie!

### Your GLPI setup information

GLPI 10.0.7
Xampp
phpmyadmin

**Comment by tech62** [comment]
Problème au niveau de tes réglages d'authentification , pour ldapsearch() c'est la fonction appelée pour procéder à la recherche dans l'AD.

Pour ton soucis du message "La configuration du dossier racine du serveur web n'est pas sécurisée car elle permet l'accès à des fichiers non publics. Référez-vous à la documentation d'installation pour plus de détails."

Vérifie ta configuration apache de Xampp et check cette page : https://glpi-install.readthedocs.io/en/latest/prerequisites.html

Exemple de fichier de conf (de mémoire)
 ```
<VirtualHost *:80>
    ServerName glpi.localhost

    DocumentRoot "C:/xampp/htdocs/glpi/public"

    # If you want to place GLPI in a subfolder of your site (e.g. your virtual host is serving multiple applications),
    # you can use an Alias directive:
    # Alias "/glpi" "C:/xampp/htdocs/glpi/public"

    <Directory "C:/xampp/htdocs/glpi/public">
        Require all granted

        RewriteEngine On

        # Redirect all requests to GLPI router, unless file exists.
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]
    </Directory>
</VirtualHost>
```

**Comment by BNMorty38** [comment]
> Problème au niveau de tes réglages d'authentification, pour ldapsearch() c'est la fonction appelée pour procéder à la recherche dans l'AD.
> 
> Pour ton soucis du message "La configuration du dossier racine du serveur web n'est pas sécurisée car elle permet l'accès aux fichiers non publics. Référez-vous à la documentation d'installation pour plus de détails."
> 
> Vérifiez votre configuration apache de Xampp et vérifiez cette page : https://glpi-install.readthedocs.io/en/latest/prerequisites.html N'oubliez pas de réactiver le service après avoir modifié votre conf !
> 
> Exemple de fichier de conf (de mémoire)
> 
> ```
> <VirtualHost *:80>
>    ServerName glpi.localhost
> 
>    DocumentRoot "C:/xampp/htdocs/glpi/public"
> 
>    # If you want to place GLPI in a subfolder of your site (e.g. your virtual host is serving multiple applications),
>    # you can use an Alias directive:
>    # Alias "/glpi" "C:/xampp/htdocs/glpi/public"
> 
>    <Directory "C:/xampp/htdocs/glpi/public">
>        Require all granted
> 
>        RewriteEngine On
> 
>        # Redirect all requests to GLPI router, unless file exists.
>        RewriteCond %{REQUEST_FILENAME} !-f
>        RewriteRule ^(.*)$ index.php [QSA,L]
>    </Directory>
> </VirtualHost>
> ```

Bonjour, merci pour votre retour. J'ai bien mis cela dans le fichier de conf apache, avec le bon path (mon xampp est sur le D et non le C). J'ai bien redémarrer le service Apache, mais j'ai toujours le message...

Merci

**Comment by trasher** [comment]
It is requested to write in english only. Thank you.
