### ISSUE TITLE
Native inventory overwrites entity for printers updated through glpi-agent netinventory

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#14948]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8-dev

### Bug description

Printers updated through native inventory / glpi inventory / glpi-agent change their existing entity (with creation of related cartridges in the new entity if they don't exist).

There is a field "Default Entity" on the Administration/Inventory page and it could not be empty. I didn't check in details yet, but I suppose that retreived printer informations trigger somehow this entity assignment.

**Comment by trasher** [comment]
I've tested following:
1- create entity "default for inv" and set it as default for inventory,
2- create "another" entity,
2- inventory a printer - entity is set to default one
3- transfer printer to entity "another",
4- inventory again => entity is still on "another".

**Comment by kabassanov** [comment]
Sorry, I forgot to describe what I did. I've just migrated from 9.5 to 10.0.8 and replaced Fusioninventory by GLPIinventory and also the local agent that manages netinventory. I have the default Root Entity (that I dont fill) and then a "sub-root" entity that is my organisation root entity. In it I have several sub-sub-entities. My printers are dispatched in this sub-root and its children.
On the Administration / Inventory page the Default Entity field is "sub-root". Printers from sub-sub-entities are moved to the sub-entity during inventory...

**Comment by trasher** [comment]
We need a reproducible use case

**Comment by kabassanov** [comment]
> @kabassanov
> 
> I assume that your SNMP discovery/inventory tasks were created in the destination entities?

Of course (they were already present in the old glpi with fusioninventory in it). There is also a checked box saying "Restrict scope to task entity".

**Comment by kabassanov** [comment]
> On FusionInventory the task entity used to determine the asset entity
> 
> Now yo need to use "Rules for assigning an item to an entity" to dispatch assets to the right entity.
> 
> Rules are played after default entity option

So I need to find some common criteria in order to dispatch them to the right entity? 

BTW, it is strange for me to see the printer type of a printer asset modified to "Printer"... And also the printer state getting removed even if my default status in Administration/Inventory is left blank.

**Comment by kabassanov** [comment]
@cedric-anne ,
Let me check. Will be back in some days.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by kabassanov** [comment]
I have still the same behaviour concerning the Entity, but while reading @stonebuzz comment, I understand that it will not change.
In the Default status configuration field now I can see a value "Do not change" that seems to do what is expected.
The printer type is no more overwritten either.
