### ISSUE TITLE
Licensing does not notify

### ISSUE THREAD

**Issue by CamiloPerezOrtiz** [glpi-project/glpi#14969]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello, I hope you can help me, I am working with glpi version 10.0.6.
I have a detail with the notifications of the licenses that are not notifying, either by email or by web, I comment on the steps that I have followed and reviewed in other publications.
The cron has been configured from the terminal (The application is in an Ubuntu Server operating system).
Notifications have already been configured in the entity
![image](https://github.com/glpi-project/glpi/assets/41083269/7e44b5e4-d6cb-4176-8afc-0fecf382749b)

In the notifications it is already configured for both email and web, in the receivers the Super – Admin profile is configured (the same has already been tried with other profiles and groups)
![image](https://github.com/glpi-project/glpi/assets/41083269/b7b8a79a-0081-444b-882f-ec5aa1a2240d)
![image](https://github.com/glpi-project/glpi/assets/41083269/65e6fa90-2716-4f14-9fef-3855d9700d0f)

In the automatic actions, it is still configured, for each day and the mode from CLI.
![image](https://github.com/glpi-project/glpi/assets/41083269/4bd188ac-9916-4bce-a3e3-6633474616f8)

Even when I run it from the button, it does not register any action in the "Pending Notifications" section
![image](https://github.com/glpi-project/glpi/assets/41083269/9438722b-08bf-4164-97ea-a41676148ac0)

Checking the files/_log/cron.log does not show any errors when I execute the task, the only logo that sends an error is the following /files/_log/php-errors.log

cron.log
![image](https://github.com/glpi-project/glpi/assets/41083269/fcbae63c-b22f-4745-8e5e-31042e81b73a)

php-errors.log
![image](https://github.com/glpi-project/glpi/assets/41083269/c4bab5f6-bd7b-415a-878a-2e885889db1d)

The license date is configured like this
![image](https://github.com/glpi-project/glpi/assets/41083269/c0173a9b-e65e-45c1-9c2d-833c6eb57c3b)

I don't know if I have to configure something else.
Thanks for the help

**Comment by 4lex11s** [comment]
there is actually no link to the parameter that is realized at the level of the entity...

> GLPI allows you to configure a notification on the expiry of the hardware warranty. This is configurable by entity in notification management to define the models and recipients used and in [the administration of entities](https://glpi-user-documentation.readthedocs.io/fr/latest/modules/administration/entities.html) to enable or disable this feature, define the default values and anticipate the sending of the notification if .

[src](https://glpi-user-documentation.readthedocs.io/fr/latest/modules/management/licenses.html)

**Comment by cconard96** [comment]
I cannot recreate the issue. Is it possible that an alert has been raised for this license expiration? I'm not sure if there is any way to see this in the UI, but with SQL (replace LICENSE_ID with your license ID):
```sql
SELECT * FROM glpi_alerts WHERE itemtype="SoftwareLicense" AND items_id=LICENSE_ID;
```

If an alert exists already, it will not try to send the notification. If the alert was raised before the notifications were configured properly, it may explain why you cannot get the notification now.

**Comment by CamiloPerezOrtiz** [comment]
Hello @cconard96 , thanks for the answer.
Make the queries that you comment but it does not show any stored notification, the effective date is July 15, 2023.

![image](https://github.com/glpi-project/glpi/assets/41083269/3335ce03-dae0-4f5e-9a46-5fb788c8e83c)

![image](https://github.com/glpi-project/glpi/assets/41083269/bc0db5dc-8168-4d1d-ab98-8e45e5407acc)

The configuration is the same as described at the beginning of this article.

**Comment by CamiloPerezOrtiz** [comment]
Hello @Benj74CB 
Thanks for the information, I checked it and now it is already notifying, thanks. I hadn't checked that on the Wiki, thanks for the advice.
