### ISSUE TITLE
Problem template does not respect status field as predefined

### ISSUE THREAD

**Issue by alexpfarias** [glpi-project/glpi#14962]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.0.3 / 10.0.0.5

### Bug description

Opening a Problem call does not respect the pre-defined Status field (Pending) in the Problem template.
<img width="1681" alt="Problem Status Bug 2" src="https://github.com/glpi-project/glpi/assets/71707434/b4ccba22-7d0d-4ad0-9483-310d7541ae6a">
<img width="787" alt="Problem Status Bug 1" src="https://github.com/glpi-project/glpi/assets/71707434/c819fc79-a1b3-494c-a1a1-6faf3dd26dd7">

### Relevant log output

```shell
<img width="1681" alt="Problem Status Bug 2" src="https://github.com/glpi-project/glpi/assets/71707434/b4ccba22-7d0d-4ad0-9483-310d7541ae6a">
<img width="787" alt="Problem Status Bug 1" src="https://github.com/glpi-project/glpi/assets/71707434/c819fc79-a1b3-494c-a1a1-6faf3dd26dd7">
```

### Page URL

/front/problemtemplate.form.php?

### Steps To reproduce

1 - Create Problem template
2- Add predefined field as Status (Pending)
3 - Save and use template as default
4- Problem call always applies Status as Awaiting service

### Your GLPI setup information

<html>
<body>

Operating system: Linux crm02 4.15.0-210-generic #221-Ubuntu SMP Tue Apr 18 08:32:52 UTC 2023 x86_64 PHP 8.1.18 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, 	pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, 	xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at helpdesk.asv.com.br Port 443 ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.51 Server Software: (Ubuntu) 	Server Version: 5.7.42-0ubuntu0.18.04.1 	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION 	Parameters: root@localhost/helpdesk 	Host info: Localhost via UNIX socket 	 PHP version (8.1.18) is supported. Sessions configuration is OK. Allocated memory is sufficient. mysqli extension is installed. Following extensions are installed: dom, fileinfo, json, simplexml. curl extension is installed. gd extension is installed. intl extension is installed. libxml extension is installed. zlib extension is installed. The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present. Database engine version (5.7.42) is supported. The log file has been created successfully. Write access to /var/www/html/helpdesk/files/_cache has been validated. Write access to /var/www/html/helpdesk/config has been validated. Write access to /var/www/html/helpdesk/files/_cron has been validated. Write access to /var/www/html/helpdesk/files has been validated. Write access to /var/www/html/helpdesk/files/_dumps has been validated. Write access to /var/www/html/helpdesk/files/_graphs has been validated. Write access to /var/www/html/helpdesk/files/_lock has been validated. Write access to /var/www/html/helpdesk/files/_pictures has been validated. Write access to /var/www/html/helpdesk/files/_plugins has been validated. Write access to /var/www/html/helpdesk/files/_rss has been validated. Write access to /var/www/html/helpdesk/files/_sessions has been validated. Write access to /var/www/html/helpdesk/files/_tmp has been validated. Write access to /var/www/html/helpdesk/files/_uploads has been validated. Web access to files directory is protected PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values. exif extension is installed. ldap extension is installed. openssl extension is installed. zip extension is installed. bz2 extension is installed. Zend OPcache extension is installed. Following extensions are installed: ctype, iconv, mbstring, sodium. Write access to /var/www/html/helpdesk/marketplace has been validated. Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.
--

GLPI_ROOT: /var/www/html/helpdesk GLPI_CONFIG_DIR: /var/www/html/helpdesk/config GLPI_VAR_DIR: /var/www/html/helpdesk/files GLPI_MARKETPLACE_DIR: /var/www/html/helpdesk/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: 1 GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_CENTRAL_WARNINGS: 1 GLPI_DOC_DIR: /var/www/html/helpdesk/files GLPI_CACHE_DIR: /var/www/html/helpdesk/files/_cache GLPI_CRON_DIR: /var/www/html/helpdesk/files/_cron GLPI_DUMP_DIR: /var/www/html/helpdesk/files/_dumps GLPI_GRAPH_DIR: /var/www/html/helpdesk/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/helpdesk/files/_locales GLPI_LOCK_DIR: /var/www/html/helpdesk/files/_lock GLPI_LOG_DIR: /var/www/html/helpdesk/files/_log GLPI_PICTURE_DIR: /var/www/html/helpdesk/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/helpdesk/files/_plugins GLPI_RSS_DIR: /var/www/html/helpdesk/files/_rss GLPI_SESSION_DIR: /var/www/html/helpdesk/files/_sessions GLPI_TMP_DIR: /var/www/html/helpdesk/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/helpdesk/files/_uploads GLPI_INVENTORY_DIR: /var/www/html/helpdesk/files/_inventories GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/helpdesk/locales GLPI_VERSION: 10.0.3 GLPI_SCHEMA_VERSION: 10.0.3@a130db99c7d9b131c2e2ea59fe0d6260fe93d831 GLPI_MARKETPLACE_PRERELEASES:  GLPI_MIN_PHP: 7.4.0 GLPI_MAX_PHP: 8.3.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.9 in (/var/www/html/helpdesk/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.0 in (/var/www/html/helpdesk/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.8 in (/var/www/html/helpdesk/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.4.4 in (/var/www/html/helpdesk/plugins/pdf/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/helpdesk/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/helpdesk/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/helpdesk/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/helpdesk/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/helpdesk/vendor/sabre/http/lib) sabre/uri in (/var/www/html/helpdesk/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/helpdesk/vendor/sabre/vobject/lib) laminas/laminas-i18n in (/var/www/html/helpdesk/vendor/laminas/laminas-i18n/src) laminas/laminas-servicemanager in (/var/www/html/helpdesk/vendor/laminas/laminas-servicemanager/src) monolog/monolog in (/var/www/html/helpdesk/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/helpdesk/vendor/sebastian/diff/src) donatj/phpuseragentparser in (/var/www/html/helpdesk/vendor/donatj/phpuseragentparser/src/UserAgent) elvanto/litemoji in (/var/www/html/helpdesk/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/helpdesk/vendor/symfony/console) scssphp/scssphp in (/var/www/html/helpdesk/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/helpdesk/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/helpdesk/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/helpdesk/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/helpdesk/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/helpdesk/vendor/ramsey/uuid/src) psr/log in (/var/www/html/helpdesk/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/helpdesk/vendor/psr/simple-cache/src) psr/cache in (/var/www/html/helpdesk/vendor/psr/cache/src) league/csv in (/var/www/html/helpdesk/vendor/league/csv/src) mexitek/phpcolors in (/var/www/html/helpdesk/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/helpdesk/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/helpdesk/vendor/guzzlehttp/psr7/src) glpi-project/inventory_format in (/var/www/html/helpdesk/vendor/glpi-project/inventory_format/lib/php) wapmorgan/unified-archive in (/var/www/html/helpdesk/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/helpdesk/vendor/paragonie/sodium_compat/src) symfony/cache in (/var/www/html/helpdesk/vendor/symfony/cache) html2text/html2text in (/var/www/html/helpdesk/vendor/html2text/html2text/src) symfony/css-selector in (/var/www/html/helpdesk/vendor/symfony/css-selector) symfony/dom-crawler in (/var/www/html/helpdesk/vendor/symfony/dom-crawler) twig/twig in (/var/www/html/helpdesk/vendor/twig/twig/src) twig/string-extra in (/var/www/html/helpdesk/vendor/twig/string-extra) symfony/polyfill-ctype not found symfony/polyfill-iconv not found symfony/polyfill-mbstring not found symfony/polyfill-php80 not found symfony/polyfill-php81 not found symfony/polyfill-php82 in (/var/www/html/helpdesk/vendor/symfony/polyfill-php82)

</body>
</html>

**Comment by trasher** [comment]
Try with latest release, feel free to reopen if issue persists.
