### ISSUE TITLE
Wrong evaluation of session.cookie_httponly variable

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi#14961]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

`php bin/console system:check_requirements` found that `session.cookie_httponly` is not enabled despite it is.

### Relevant log output

```shell
| [SUGGESTED] Security configuration for sessions      | [INFO]     | PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values. |
| Ensure security is enforced on session cookies.      |            |                                                                                                                      |
```

### Your GLPI setup information

php info confirms that session.cookie_httponly is enabled:
![image](https://github.com/glpi-project/glpi/assets/70358310/30e399ff-a010-4d4d-b928-c9654b0716e8)

And same on browser side:
![image](https://github.com/glpi-project/glpi/assets/70358310/f53c4a0a-a6cd-4401-9e82-001855eb20da)

### Anything else?

Maybe the check_requirements script is only looking for on/off value but not for 0/1 ?

**Comment by cedric-anne** [comment]
Hi,

Are you sure that this configuration value is the same in CLI mode? You can check it by running `php -i | grep session.cookie` command.

**Comment by MarcSamD** [comment]
Thank you @cedric-anne 
Indeed my server was using 2 different php.ini conf file for Apache2 and CLI.
