### ISSUE TITLE
phone and sim card - delete permanently the RELATION with selected object - deleted permanently simm card from GLPI

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#14968]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

having a sim card assigned to the phone , in the components tab I select the card and give "delete permanently the RELATION with selected object" - this completely removes the sim card from GLPI.

### Page URL

/front/phone.form.php?id=28#modal_massaction_content094d6c....

### Steps To reproduce

having a sim card assigned to the phone , in the components tab I select the card and give "delete permanently the RELATION with selected object" - this completely removes the sim card from GLPI.

**Comment by cconard96** [comment]
Does it just delete the sim card or the entire sim card model/definition?
Sim cards and other components are a unique case where most of their data in stored in the relation itself.
For sim cards, the main "item" has just a name, comment, manufacturer, type voltage and "allow voip" flag.
The relation has the PIN/PUK, MSSN, serial number, etc.
For all intents and purposes, components are the models and the relations are the actual individual items.

Removing a component from an item is handled with the Dissociate action.
Perhaps it is best to just remove the option allowing you to delete the relation in this case so people don't accidentally delete their data.

**Comment by trasher** [comment]
So that's expected, not a bug. What you talk about is the `front/item_devicesimcard.form.php`, which is the relation between the Phone (`front/phone.form.php`) and the component (`front/device.form.php?itemtype=DeviceSimcard`).

Maybe that's not clear, but as far as I know, all component works the same way.
