### ISSUE TITLE
Tasks time doesn't appear

### ISSUE THREAD

**Issue by Tartiflette-glpi** [glpi-project/glpi#14976]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hi,

Since the patch for the document root "/var/www/glpi/public" we can't see anymore time of every tasks in tickets.
The global time is still visible in the tickets main page but not the time tasks by tasks

When we go back with the old conf, the problem is still here

Can you help us please

### Your GLPI setup information

GLPI 10.0.7
Debian 10

**Comment by cedric-anne** [comment]
Hi,

Could you please give requested information? For instance, screenshots, steps to reproduce, logs content, system information, ... could help to understand what is your issue.
Right now, I am not able to understand what is you issue.

**Comment by Tartiflette-glpi** [comment]
Hi,

The problem:
Creation of the task: https://i.ibb.co/XYW6y3S/Capture-d-cran-2023-06-22-095812.png
Result: https://i.ibb.co/0XsLN2b/Capture-d-cran-2023-06-22-095836.png
Tickets page: https://i.ibb.co/kQHh9QB/Capture-d-cran-2023-06-22-095904.png


I followed this: https://readthedocs.org/projects/glpi-install-fr/downloads/pdf/latest/

my glpi.conf:
```
<VirtualHost *:64200>
        ServerName glpi.localhost
        DocumentRoot /var/www/glpi/public
        Alias "/glpi" "/var/www/glpi/public"
        <Directory /var/www/glpi/public>
                Require all granted
                RewriteEngine On
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^(.*)$ index.php [QSA,L]
        </Directory>
</VirtualHost>
```

"config" content:
/var/www/glpi/config/ -> /etc/glpi/

"files" content:
/var/www/glpi/files/ -> /var/lib/glpi/

logs:
/var/log/glpi/

Creation of inc/downstream.php :
```
<?php
define('GLPI_CONFIG_DIR', '/etc/glpi/');
if (file_exists(GLPI_CONFIG_DIR . '/local_define.php')) {
require_once GLPI_CONFIG_DIR . '/local_define.php';
}
```
Creation of /etc/glpi/local_define.php : 
```
<?php
define('GLPI_VAR_DIR', '/var/lib/glpi');
define('GLPI_LOG_DIR', '/var/log/glpi');
```
```
a2enmod rewrite
systemctl reload apache2
```

php version is: 8.0.29

Where can I find the logs you need ?
in /var/log/glpi/ there are :
https://i.ibb.co/sbmsq3p/Capture-d-cran-2023-06-22-095722.png

thanks

**Comment by trasher** [comment]
> When we go back with the old conf, the problem is still here

Then I doubt web server configuration is the issue.

**Comment by cedric-anne** [comment]
I am not able to reproduce on current GLPI nightly build.
![image](https://github.com/glpi-project/glpi/assets/33253653/dd3b453e-7fa8-48a3-ae8a-f301294159fb)

Please try to reproduce with no active plugins. Also, what is your PHP version, have you some active plugins, have you some custom CSS, ... ?

**Comment by Tartiflette-glpi** [comment]
Okay the troublemaker has been found :
![image](https://github.com/glpi-project/glpi/assets/109726235/16ec64ce-8ff0-4b67-b7d5-6da0dbd21ce4)

It's a plugin update that make this. 

I was thinking about the new conf because I made it at the same time as this lil shitty update

Thank you both, now I'll be less of an idiot

**Comment by cedric-anne** [comment]
Please open an issue on plugin's repository: https://github.com/InfotelGLPI/moreticket
