### ISSUE TITLE
Kerberos & picture import

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#150]
When use external authentication like kerberos, the user picture are not imported.

Test : Change authentication to LDAP, synchronize user => the picture is here
Change to external authentication & synchronize => the picture is dropped

GLPI 0.85.5

**Comment by orthagh** [comment]
First part of test seems ok for me.
Second is strange.
Could you precise a little more ?

I sent a first fix for this, can you test again

**Comment by orthagh** [comment]
any tests for be45cd3 commit ?

**Comment by tsmr** [comment]
Same problem
