### ISSUE TITLE
"Time to resolve + progress" is not in search dropdown ticket list

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#15004]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Is not posible select "Time to resolve + progress" in dropdown search menu
![image](https://github.com/glpi-project/glpi/assets/56876938/42124dda-0867-46cc-969f-7619ed394128)

![image](https://github.com/glpi-project/glpi/assets/56876938/5cfd389b-d1e1-42fc-a565-a412dcb9e6b0)

It is a very useful feature for creating custom views with saved searches, and since it is not included in the search filter, it has to be added as a fixed field, which is not practical.

### Page URL

/front/ticket.php

### Steps To reproduce

ad custom search filter on tickets area "Time to resolve + progress" is not listed.

**Comment by cconard96** [comment]
This isn't a bug. Currently, the "+ Progress" options cannot be searched from a technical point of view. In the search engine they are treated exactly like the non "+ Progress" options and then the extra data is added when it is ready to be displayed. Given that the progress calculation uses the calendars, I don't think this is something that can be changed to be directly in a SQL query.

If the desire is just to be able to have non-searchable columns show depending on the current saved search view, it would have to be developed. We only track bugs here though. You can add feature suggestions on the suggestion website.
https://suggest.glpi-project.org
