### ISSUE TITLE
Big mess on reminder creation

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#15001]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8-dev

### Bug description

Hi,

A strange entry in my logs leaded me to something really weird during reminder creations.

When a sub-entity user creates a new reminder and attach a file to it at the same time, the file is attached to the root entity which is a problem if the user does not belong to it. Or... is-it possible that the file is simply not attached to an entity at all?

Another thing I observed is that super-admin does not have access to the created reminder (I'm not sure if it is by conception or not)...

And "last" thing, when the same user tries to reupload the file (as he can't see it in the reminder, even if there is a trace in the history), there is an sql error due to unicity key violation. Probably because the file already exists in the root entity.  And the user sees the new file in the reminder with a name changed to {SOMEHASH}filename...

### Relevant log output

```shell
[2023-06-22 16:34:08] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 379
  *** MySQL query error:
  SQL: INSERT INTO `glpi_documents_items` (`documents_id`, `itemtype`, `items_id`, `date`, `users_id`, `entities_id`, `is_re
cursive`, `date_creation`, `date_mod`) VALUES ('21247', 'Reminder', '52', '2023-06-22 16:34:07', '8429', '0', '0', '2023-06-
22 16:34:07', '2023-06-22 16:34:07')
  Error: Duplicate entry '21247-Reminder-52-0' for key 'unicity'
  Backtrace :
  src/DBmysql.php:1341
  src/CommonDBTM.php:722                             DBmysql->insert()
  src/CommonDBTM.php:1317                            CommonDBTM->addToDB()
  src/CommonDBTM.php:5569                            CommonDBTM->add()
  src/Features/PlanningEvent.php:226                 CommonDBTM->addFiles()
  src/CommonDBTM.php:1583                            Reminder->prepareInputForUpdate()
  front/reminder.form.php:81                         CommonDBTM->update()
  public/index.php:82                                require()
```

### Steps To reproduce

1. Connect as a not admin user in a sub-entity
2. Go to reminders
3. Add a file in the form
4. Put some title and text to the reminder
5. Submit
6. Check result

**Comment by 0xNath** [comment]
Hello,
On my end I encounter the same behaviour as you, the documents imported when creating a reminder are assigned to the root entity. It's also doing this for the knowledge base items at least. 

I think that reminders have been designed to only be visible to it's creator by default. There is the possibility to make them visible after creation by setting their targets. It make sense to me for this to be the default behaviour, that's what I would expect as an user creating a note.

I think the documents should be assigned by default to the desired entity of the person creating it. 
If my memory is correct, I remember importing documents for knowledge base items from sub-entities in previous 10.0.x version so maybe it's a recently introduced bug. I will try to solve this it if it's not too complicated for me.

**Comment by 0xNath** [comment]
Hello,
I have found the origin of the issue when importing files from the form of the reminders and of the knowledge base items.

When an user want to add an item for anything, he will get a form in is browser with an hidden input field **entities_id**. 
For the items form that includes importing a documents, like reminders and documents, this input field is used to choose in which entities they will be assigned to.
If an type of item lack the column **entities_id** in the database, the form will be generated with an **entities_id** set to 0.

In CommonDBTM.php :
``` PHP
public function getEmpty()
    {
        global $DB;

        //make an empty database object
        $table = $this->getTable();

        if (
            !empty($table) &&
            ($fields = $DB->listFields($table))
        ) {
            foreach (array_keys($fields) as $key) {
                $this->fields[$key] = "";
            }
        } else {
            return false;
        }

        if (
            array_key_exists('entities_id', $this->fields)
            && isset($_SESSION["glpiactive_entity"])
        ) {
            $this->fields['entities_id'] = $_SESSION["glpiactive_entity"];
        }
```
In the DB for 10.0.8-dev, tables _glpi_reminders_ and _glpi_knowledgebaseitems_ both lack the column **entities_id**.
I don't know if it is specific to this version, nor why it doesn't exist.

To continue.
