### ISSUE TITLE
Resolve ticket witch user asigned by API from Zabbix

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#15005]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hello, 

A ticket created through the GLPI API from ZABBIX with an assigned user is not resolved upon receiving the resolution order. However, if I create the ticket without assigning a user, it does get resolved. The user has solution permissions from all states.
![image](https://github.com/glpi-project/glpi/assets/56876938/50152e6f-45c2-4287-a094-04d995ee40b9)

thnakyou

### Steps To reproduce

Create a ticket through API from ZABBIX
assing on the script user
send resolution order
Not working.

If you do not assing user, no problem.

**Comment by cconard96** [comment]
Please include the API call being made to solve the ticket, any relevant log entries around the time of the issue, and your GLPI setup information. The GLPI logs are in "files/_log" and the setup information is in Setup > General on the System tab.

**Comment by AlexTR85** [comment]
With zabbix user (user with the token id) dont work, but, if i use another usar with same profile, its okey.

I close the ticket.
