### ISSUE TITLE
Inventory : Location created in the wrong entity instead of being assigned

### ISSUE THREAD

**Issue by JulienRemi** [glpi-project/glpi#15029]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I have rules to put a computer in an entity and location depending on his inventory Tag. But when I change this Tag and do a new inventory, the new location is created in the current entity and the computer is linked to it. And just after that he is link to the right location. So I end up with an empty location.  
The computer is correctly transferred to the right entity.   
Here you can see in yellow that his devices are also moved under the wrong location (id: 1724) and then when he is link to the right one in blue (id: 1707):
![Capture](https://github.com/glpi-project/glpi/assets/71510592/ef1f0202-2a3c-46f4-8141-6bc178f34d97)  
  
I thought it could come from the devices so I change the transfer rule but it still create a new location (I deleted it before trying that):  
![Capture2](https://github.com/glpi-project/glpi/assets/71510592/c8d4ee06-ab6c-4283-bf2b-9333d6013c81)    
  
I've got the location test1 under the entity test1 and same for test2. The computer was supposed to go from entity and location test1 to test2. But a location test2 was created under test1:
![Capture3](https://github.com/glpi-project/glpi/assets/71510592/3ff7d9bd-1994-49a6-9371-9f01a6740b96)

### Steps To reproduce

1. Create 2 entities and in each of them a location.
2. Create rules to assign an entity and a location to a computer based on a Tag.
3. Select a transfer rule in the assets panel of the root entity (other entities inherit from root).
4. Put the glpi-agent on a computer with one of the Tag.
5. Do an inventory.
6. Change the Tag of the agent.
7. Do an inventory.

### Your GLPI setup information

Operating system: Windows NT WIN-I9EE2IIBF66 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.7 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, random,
	readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.33
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost:3306/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.2.7) is supported.PHP version (8.2.7) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.33) is supported.Database engine version (8.0.33) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpriv\glpi\files/_cache has been validated. Write access to C:\inetpriv\glpi\config has been validated. Write access to C:\inetpriv\glpi\files/_cron has been validated. Write access to C:\inetpriv\glpi\files has been validated. Write access to C:\inetpriv\glpi\files/_dumps has been validated. Write access to C:\inetpriv\glpi\files/_graphs has been validated. Write access to C:\inetpriv\glpi\files/_lock has been validated. Write access to C:\inetpriv\glpi\files/_pictures has been validated. Write access to C:\inetpriv\glpi\files/_plugins has been validated. Write access to C:\inetpriv\glpi\files/_rss has been validated. Write access to C:\inetpriv\glpi\files/_sessions has been validated. Write access to C:\inetpriv\glpi\files/_tmp has been validated. Write access to C:\inetpriv\glpi\files/_uploads has been validated.Write access to C:\inetpriv\glpi\files/_cache has been validated.
Write access to C:\inetpriv\glpi\config has been validated.
Write access to C:\inetpriv\glpi\files/_cron has been validated.
Write access to C:\inetpriv\glpi\files has been validated.
Write access to C:\inetpriv\glpi\files/_dumps has been validated.
Write access to C:\inetpriv\glpi\files/_graphs has been validated.
Write access to C:\inetpriv\glpi\files/_lock has been validated.
Write access to C:\inetpriv\glpi\files/_pictures has been validated.
Write access to C:\inetpriv\glpi\files/_plugins has been validated.
Write access to C:\inetpriv\glpi\files/_rss has been validated.
Write access to C:\inetpriv\glpi\files/_sessions has been validated.
Write access to C:\inetpriv\glpi\files/_tmp has been validated.
Write access to C:\inetpriv\glpi\files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\glpi/marketplace has been validated.Write access to C:\inetpub\glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by trasher** [comment]
Can you try if you reproduce with latest 10.0/bugfixes nightly build? Several fixes already has been done on that branch regarding inventory.

**Comment by JulienRemi** [comment]
Hi, I was trying to install from the source but got this error :  
> @php -r "file_put_contents('.composer.hash', sha1_file('composer.lock'));"
> @php -f vendor/bin/build_hw_jsons
> patch -f -p1 -d vendor/laminas/laminas-mail/ < tools/patches/laminas-mail-invalid-header-ignore.patch || true
'patch' is not recognized as an internal or external command,
operable program or batch file.
'true' is not recognized as an internal or external command,
operable program or batch file.
Script patch -f -p1 -d vendor/laminas/laminas-mail/ < tools/patches/laminas-mail-invalid-header-ignore.patch || true handling the post-update-cmd event returned with error code 1

Got the same with composer and installed it but I can't find a way to get patch and true on Windows.

**Comment by trasher** [comment]
Don't install from sources. See https://nightly.glpi-project.org/glpi/.
