### ISSUE TITLE
2 dashboard widgets not working

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#15022]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0 nightly build from 23/6

### Bug description

Using the nightly build, when clicking on the widget "computers by type" or "network devices by locations" I'm redirected to another php page but the result is a blank page.
The resulting URLs ("front/networkequipment.php&criteria[0][field]=31&criteria[0][searchtype]=equals&criteria[0][value]=0&criteria[criteria][0][value]=0&reset=reset" or "front/computer.php&criteria[0][field]=23&criteria[0][searchtype]=equals&criteria[0][value]=0&criteria[criteria][0][value]=6&reset=reset" ) seem to work if I remove all the url arguments to it ...

### Relevant log output

Nothing is logged (neither glpi log or php log), but in the browser log output I see the return code 403 (Forbidden), even when logged in as super admin. Removing all arguments results in the expected list.

### Anything else?

The released version 10.0.7 works as expected, it is only the nightly build.

**Comment by cedric-anne** [comment]
It seems that there is a missing `?` in front of URL arguments.

**Comment by cedric-anne** [comment]
I am not able to reproduce. The following line should ensure that URL params are prefixed by a `?`: https://github.com/glpi-project/glpi/blob/a6c3769b0b2939c9a891b79ba9d2b7246041ced5/src/Dashboard/Provider.php#L143

Is there any difference in PHP version between your servers?

**Comment by liedekef** [comment]
Indeed, the "?" is the problem (didn't even see that one ...). I'll try debugging, because the code is simple enough so it should work (irrelevant of php versions ...).

**Comment by liedekef** [comment]
Manual php updates on a production server are not possible here :-)
But when doing command line testing, the php code functions as expected.

**Comment by liedekef** [comment]
That part of the code works correctly (according to error_log when I log $search_url and $url). But clicking on the link returns a link without the "?", it is like if the javascript code changes that to "&" somewhere.

**Comment by liedekef** [comment]
Just upgraded to latest nightly and the same issue persists.

**Comment by liedekef** [comment]
Btw: the problem is not with widgets of type "bignumber", but with the "donut" widgets and others (like I said the type of widget).
Now the fix seems to be in Provider.php, line 863 (in function nbItemByFk ) which should change from

`'url'    => $url . '&' . Toolbox::append_params([`

to

`'url'    => $url . (str_contains($url, '?') ? '&' : '?') . Toolbox::append_params([`

I'll leave this up to you guys to evaluate ...

**Comment by cedric-anne** [comment]
My bad, I was not checking the right place.

#15027 should fix the issue.

**Comment by liedekef** [comment]
The fix works (and indeed I saw there was an issue with the resulting params), but the result is now (when for example clicking on the computer type "Qemu" in the donut widget "Computers by type"

![image](https://github.com/glpi-project/glpi/assets/75667/79fbbb96-6e82-4b43-8b86-f010f1880542)

So there is an line searching for type empty combined with an AND for type "qemu", resulting in an empty result. Removing the "empty" line works:
![image](https://github.com/glpi-project/glpi/assets/75667/32e58e05-9400-40d8-b409-3538097fc387)

**Comment by liedekef** [comment]
This changeset is not completely solving the issue (see my latest remark)

**Comment by liedekef** [comment]
Ok, based on the current code, it seems in Provider.php, function nbItemByFk, the lines at 848-853:

```
        $search_criteria = self::getSearchFiltersCriteria($fk_table, $params['apply_filters'])['criteria'] ?? [];
        $search_criteria[] = [
            'field'      => $params['searchoption_id'],
            'searchtype' => 'equals',
            'value'      => 0
        ];
```

should just be:

`        $search_criteria = self::getSearchFiltersCriteria($fk_table, $params['apply_filters'])['criteria'] ?? [];`

This avoids the "empty" search param to always be added further down (in $result_criteria)

**Comment by liedekef** [comment]
Apparently the fix was already in one of the mentioned changesets, so I'm closing this.
