### ISSUE TITLE
Number of Installations in Software does not match Installations in Software details

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#15025]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When we filter software in the software list with "Number of installations" is zero, we get a list of software a in the image for the example 7-zip.
![Softwareliste](https://github.com/glpi-project/glpi/assets/5680717/d1cb2e3f-5737-4bfa-a5f7-6ba252eec405)
When we select the software an look into the details there are installations for the software.
![SoftwareDetail](https://github.com/glpi-project/glpi/assets/5680717/5a7bf809-56cf-42c9-8097-bcbe7c33a922)
So it seems the number of installations in the software list does not match the number of installations of the software.

### Steps To reproduce

Right now we don't know how to reproduce this behaviour.

**Comment by cconard96** [comment]
What entity are you looking at this data from and are you in "tree structure" mode to be able to view child entities?

**Comment by cconard96** [comment]
From the search results, it seems to be taking the entity of the software while the count in the tab takes into account the entity of the linked assets.

**Comment by AndiMb** [comment]
I'm looking at the data from a child entity, so I'm in tree structure mode. But as far as I understand, there is a Software entry for each entity separately. So all computer listed in the installations list are from this entity.

**Comment by AndiMb** [comment]
The issue still persists in 10.0.9.
