### ISSUE TITLE
Issue when clonning collector Rule

### ISSUE THREAD

**Issue by tomamplius** [glpi-project/glpi#15023]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When cloning rule name "Affectation de l'entité FLL" the new rule name is "Affectation de l\'entité FLL (copie)"

![image](https://github.com/glpi-project/glpi/assets/6951820/50388801-9985-4957-bb9d-3238ddce5dd7)

Other fields like description are the same issue
![image](https://github.com/glpi-project/glpi/assets/6951820/b9207a57-7c71-4c57-8264-457becc8c03f)

the backslash need to be remove

### Steps To reproduce

Clone collector rule with ' on the subject

**Comment by trasher** [comment]
I confirm the issue
