### ISSUE TITLE
Installations statistics

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1502]
Hi,

Have we somewhere statistics on currents installations as :
  - GLPI version
  - list of plugins (and version)
  - PHP version
  - OS
  - Web server name & version
  - ...

This in order to known the current state of usage of the software (and where work should be done ) ?

Regards,
Anael

**Comment by wawax** [comment]
Hi,

The only we've got for now is here : http://glpi-project.org/?page=refer&lang=fr
We're thinking at a way to be able to declare itself from within glpi.

Regards,

**Comment by AnaelMobilia** [comment]
9.2 version add it :)
http://glpi-project.org/telemetry/telemetry

Great job !
