### ISSUE TITLE
GPI 10.0.7 - LDAP error when new user is imported

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#15028]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Hello all,

I'm facing an import problem that I encountered in 10.0.6.
We have a local active directory synchronised with MSO365 (Azure AD connect) 
We set up Intune recently but I don't see what this has to do with the bug.

When I create my user in the active directory like the others and import it manually into GLPI I get a 500 error. 

I have to connect to the SQL database to delete the imported user and then I can access the user menu again.

Despite my searches in the GLPI logs I can't find a log specific to the problem.

![image](https://github.com/glpi-project/glpi/assets/63521311/58e9f9ee-096e-4335-bec0-b17f6d65ee55)

### Your GLPI setup information

Operating system: Windows NT SRV-GLPI 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.1.4 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	readline, session, soap, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="192M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.58
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.28
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	
PHP version (8.1.4) is supported.PHP version (8.1.4) is supported.

**Comment by cedric-anne** [comment]
> I get a 500 error.

When a 500 error occurs, the trace of this error should be added to `files/_log/php-errors.log`. Could you check again if something is added here when you try to import your user ?

**Comment by stdglpi** [comment]
Hello @cedric-anne 



I tried to import 2 users this morning, and it seems ok. the third one I have the error 500.

at 11:00 am
![image](https://github.com/glpi-project/glpi/assets/63521311/937b79b5-3340-425d-a07f-6d6e96f6f419)

In fact when the error comes, the file "php-errors.log" does not increment... so I can't see the update.
![image](https://github.com/glpi-project/glpi/assets/63521311/999cb143-d74d-4b1c-9962-34774fc4a1e8)

**Comment by stdglpi** [comment]
@cedric-anne 

I have propagated the rights to the folder "wwwroot" of the IIS and the subfolder "GLPI"

I imported  an user again, but the log file doesn't change


I checked also te file : "FastCGI_errors.log"

And I saw this log seems to refer to my problem (AuthLDAP.php)

24-May-2023 21:25:23 Europe/Paris] PHP Deprecated:  addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in C:\inetpub\wwwroot\glpi\src\AuthLDAP.php on line 2839
[24-May-2023 21:25:23 Europe/Paris] PHP Warning:  Invalid value "" found for actor in "_users_id_observer". in C:\inetpub\wwwroot\glpi\src\CommonITILObject.php on line 8104
[25-May-2023 21:05:22 Europe/Paris] PHP Deprecated:  addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in C:\inetpub\wwwroot\glpi\src\AuthLDAP.php on line 2839
[07-Jun-2023 10:55:23 Europe/Paris] PHP Warning:  Duplicated document item relation in C:\inetpub\wwwroot\glpi\src\Document_Item.php on line 135

**Comment by cedric-anne** [comment]
Without the trace of the 500 error, we cannot investigate.

**Comment by stdglpi** [comment]
understood, I try to upgrade my PHP and I will come back.

**Comment by trasher** [comment]
Seems like an issue outside GLPI scope. I close for now, feel free to reopen if you find any informaiton on a GLPI issue.

**Comment by stdglpi** [comment]
Hello @cedric-anne and @trasher 

I saw that the last release GLPI 10.0.8 came out but i tried to focus on PHP first. 

I was in PHP 8.1 with GLPI 10.0.7
I upgraded my PHP to 8.2.7 and now everything is working fine !

regards,
