### ISSUE TITLE
Error HTTP 403 with public directory on vhost

### ISSUE THREAD

**Issue by Tuxman2** [glpi-project/glpi#15033]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

With the 10.0.7 version we've got the "Web server root directory configuration is not safe" warning. So, we have to define public folder to avoid this message. But when we do it, we can't access with http(s)://nameserver/glpi but with http(s)://nameserver
If we try to connect with http(s)://nameserver/glpi , we've got the following error : "Error HTTP 403".

The problem is still know, see it: https://github.com/glpi-project/glpi/issues/14733

So, I would like to be able to connect through http(s)://nameserver/glpi like before previous versions in GLPI 10.0.7.

I think this a bug as many users have this problem too. That's why I posted this message.

**Comment by cedric-anne** [comment]
Hi,

You can use something like
```
<VirtualHost *:80>
    ServerName nameserver

    DocumentRoot /var/www/html

    Alias "/glpi" "/var/www/glpi/public"

    <Directory /var/www/glpi/public>
        Require all granted

        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteRule ^(.*)$ index.php [QSA,L]
    </Directory>
</VirtualHost>
```

**Comment by Tuxman2** [comment]
Hello,

thank you very much for your help. It works now. ;-)
