### ISSUE TITLE
Licence - Add a new computer

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1504]
On the dev version :
  - create a new licence
  - Go to the computer tab for this licence and add it to a computer
  - Use the dropdown to assign the licence to another computer

The previously assigned computer is still available on the dropdown.

For me two possibility :
  - Don't display anymore a device which is already assigned for a licence
  - Add an option on the licence to define if it can be used multiple times for the same items. And only on this case allow the dropdown to provide multiple assignation

Regards

**Comment by cedric-anne** [comment]
Hi,

Unless I do miss something, it seems to be a feature now. See #3794.

Regards
