### ISSUE TITLE
HP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#15040]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I don't know where this error is trigger and how, but I'm getting a lot of that:

glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

### Relevant log output

```shell
[2023-06-28 10:20:57] glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

[2023-06-28 10:20:57] glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

[2023-06-28 10:21:23] glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

[2023-06-28 10:22:05] glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

[2023-06-28 10:22:28] glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()

[2023-06-28 10:25:02] glpiphplog.WARNING: Test logger
[2023-06-28 10:29:03] glpiphplog.WARNING:   *** PHP User Warning (512): "timeline_answer_actions" hook callback result should be an array, "NULL" returned. in /glpi/src/CommonITILObject.php at line 6633
  Backtrace :
  src/CommonITILObject.php:6633                      trigger_error()
  src/Ticket.php:4406                                CommonITILObject->getTimelineItemtypes()
  src/CommonGLPI.php:676                             Ticket->showForm()
  ajax/common.tabs.php:116                           CommonGLPI::displayStandardTab()
  public/index.php:73                                require()
```

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.7 ( => /glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux 5.15.0-1040 #Linux SMP Thu Jun 1 19:38:24 UTC 2023 x86_64
PHP 8.1.2-1 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="25" memory_limit="512M" post_max_size="4M" safe_mode="" session.save_handler="files"
	upload_max_filesize="1M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Server Software: Linux
	Server Version: DB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@vm/glpi
	Host info: ..... via UNIX socket
	
PHP version (8.1.2-1) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /glpi/files/_cache has been validated.
Write access to /glpi has been validated.
Write access to /glpi/files/_cron has been validated.
Write access to /glpi/files has been validated.
Write access to /glpi/files/_dumps has been validated.
Write access to /glpi/files/_graphs has been validated.
Write access to /glpi/files/_lock has been validated.
Write access to /glpi/files/_pictures has been validated.
Write access to /glpi/files/_plugins has been validated.
Write access to /glpi/files/_rss has been validated.
Write access to /glpi/files/_sessions has been validated.
Write access to /glpi/files/_tmp has been validated.
Write access to /glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/glpi"
GLPI_CONFIG_DIR: "/glpi"
GLPI_VAR_DIR: "/glpi/files"
GLPI_LOG_DIR: "/glpi/log"
GLPI_MARKETPLACE_DIR: "/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/glpi/files"
GLPI_CACHE_DIR: "/glpi/files/_cache"
GLPI_CRON_DIR: "/glpi/files/_cron"
GLPI_DUMP_DIR: "/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/glpi/files/_locales"
GLPI_LOCK_DIR: "/glpi/files/_lock"
GLPI_PICTURE_DIR: "/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/glpi/files/_plugins"
GLPI_RSS_DIR: "/glpi/files/_rss"
GLPI_SESSION_DIR: "/glpi/files/_sessions"
GLPI_TMP_DIR: "/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/glpi/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/glpi/vendor/sabre/http/lib)
sabre/uri in (/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/glpi/vendor/symfony/console)
scssphp/scssphp in (/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/glpi/vendor/ramsey/uuid/src)
psr/log in (/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/glpi/vendor/psr/simple-cache/src)
psr/cache in (/glpi/vendor/psr/cache/src)
league/csv in (/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/glpi/vendor/symfony/cache)
html2text/html2text in (/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/glpi/vendor/symfony/dom-crawler)
twig/twig in (/glpi/vendor/twig/twig/src)
twig/string-extra in (/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'dominio', Port: '389', BaseDN: 'DOMINIO', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=usuario,DC=DOMINIO', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (account@smtp.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace
	activity             Name: Activities                     Version: 3.1.2      State: Installed / not activated               
		Install Method: Marketplace
	actualtime           Name: ActualTime                     Version: 2.1.0      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Additional fields              Version: 1.20.6     State: Installed / not activated               
		Install Method: Marketplace
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Not installed                           
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.12.1     State: Installed / not activated               
		Install Method: Marketplace
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Behaviours                     Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	positions            Name: Cartography                    Version: 6.0.2      State: Enabled                                 
		Install Method: Marketplace
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.13.2     State: Installed / not activated               
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.2.21     State: Enabled                                 
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.3      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.0.4      State: Not installed                           
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.2      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Marketplace
	resources            Name: Human Resources                Version: 3.0.4      State: Installed / not activated               
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.8.3      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.8.1      State: Installed / not activated               
		Install Method: Marketplace
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	metabase             Name: Metabase                       Version: 1.3.3      State: Installed / not activated               
		Install Method: Marketplace
	mfa                  Name: MFA                            Version: 1.0.2      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Installed / not activated               
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.1      State: Installed / not activated               
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.5      State: Installed / not activated               
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Enabled                                 
		Install Method: Marketplace
	officeonline         Name: Office Online                  Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	onetimesecret        Name: OneTimeSecret                  Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	order                Name: Orders management              Version: 2.10.4     State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Not installed                           
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.11.2     State: Installed / not activated               
		Install Method: Marketplace
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Not installed                           
		Install Method: Marketplace
	yagp                 Name: yagp                           Version: 2.1.1      State: Not installed                           
		Install Method: Marketplace

</pre></details>

**Comment by jcervantes-sipecom** [comment]
Sure, the info was updated.

**Comment by trasher** [comment]
Please try without all plugins disabled

**Comment by cedric-anne** [comment]
I quickly checked in plugins code, and I guess `onetimesecret` is the source of this issue. Please open an issue on plugin's repository (https://github.com/ticgal/one-timesecret).
