### ISSUE TITLE
pluginsGLPI maintained or not

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#15044]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Part of GLPI is the power of plugins. However I feel like many of the advertised plugins go unmaintained. When installing plugins via GLPI web interface, one should be able to assume these are maintained. However bugfixes on several plugins go unanswered and tickets unread/not reacted on.
Is GLPI having any influence on this? For example "ocsi inventory ng" and "suppliers imports" could use some love :-)

**Comment by trasher** [comment]
Plugins are the responsibility of their respective owners, and it is not possible to know which are still maintained or not.

The only thing to do is to contact plugin owners, or you can take care of some plugins yourself.
