### ISSUE TITLE
10.0.7 : HTTP 500 error with new PHP router exposing only selected directories for ajax call

### ISSUE THREAD

**Issue by ericferon** [glpi-project/glpi#15051]
From PR #13197 : 
"For the moment, this router will only do filtering to only serve URLs that seem legitimate, and return an error code for the others.
For plugins, the authorized URLs are:
  - all files located in the `/public` folder,
  - all `.php` files located in the `/ajax`, `/front` and `/report` folders, as well as those located at the root of the plugin (except `setup.php` and `hook.php`) ,
  - all `index.php` files located in any folder,
  - all `*.css.php` and `*.js.php` files located in any folder,
  - all HTML files (`*.htm`, `*.html`), `*.css`, `*.js`, `*.json`, images (`*.gif`, `*.jpg` , `*.jpeg`, `*.png`, `*.svg`), audios (`*.mp3`, `*.ogg`, `*.wav`), empty (`*.mp4`, ` *.ogm`, `*.ogg`, `*.webm`), fonts (`*.eot`, `*.ttf`, `*.woff`, `*.woff2`) and `favicon.ico` , located in any folder.
However, the following files will be disallowed:
  - all hidden files (starting with a `.`),
  - all the files located in the `/node_modules` or `/vendor` folders,
  - the `composer.json`, `package.json` and `package-lock.json` files located at the root.
"
_Originally posted by @cedric-anne in https://github.com/glpi-project/glpi/issues/13197#issuecomment-1453637687_
In my plugin "archimap", I'm using ajax calls to .../archimap/drawio-integration/ajax/getconfig.php. Before v10.0.7, this was working fine. I moved the "getconfig.php" file to .../archimap/ajax and to .../archimap : in both cases, the same call now returns an HTTP error 500 (internal server error).
Is it a bug or am I wrong ?
K.r,
Eric Feron

**Comment by cedric-anne** [comment]
Hi,

Following path should work:
- `/plugins/archimap/ajax/getconfig.php`
- `/plugins/archimap/ajax/drawio-integration/getconfig.php`
- `/plugins/archimap/public/getconfig.php`
- `/plugins/archimap/public/drawio-integration/ajax/getconfig.php`

`/plugins/archimap/drawio-integration/ajax/getconfig.php` will result in a 403 error. If you have a 500 error, it is probably due to something in your `getconfig.php` that has to be updated due to file moving.

**Comment by cedric-anne** [comment]
As it seems to be fixed in v3.3.0 of the plugin, see https://github.com/ericferon/glpi-archimap/releases/tag/v3.3.0, I close this issue.
