### ISSUE TITLE
Inventory : Unmanaged rules don't look in computers but update them on import

### ISSUE THREAD

**Issue by JulienRemi** [glpi-project/glpi#15116]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When discovering with glpiinventory computers already inventoried, the Unmanaged rules for importing and linking computers doesn't search mac or names in Computers and only in Unmanaged. BUT when importing them they update existing computers.
Since discovery finds only one of the computer interfaces, it deletes all the others.

Testing rules (basic rules) :
![Screenshot 2023-07-05 091404](https://github.com/glpi-project/glpi/assets/71510592/10597624-aa03-43fd-a061-6b3d78990371)
![Screenshot 2023-07-05 090236](https://github.com/glpi-project/glpi/assets/71510592/aceba256-8ee0-4713-9c6d-20fbc6de41d5)  
It doesn't find the existing computer  
  
But if you do a network discovery it will update the computer with the import rule.
![Screenshot 2023-07-05 091558](https://github.com/glpi-project/glpi/assets/71510592/6e823fb3-503d-4594-9fcf-3de63ea34e9e)

### Relevant log output

```shell
INVENTORY XML FILE :

<REQUEST>
<CONTENT>
<DEVICE>
<DNSHOSTNAME>10.200.0.188</DNSHOSTNAME>
<ENTITY>7</ENTITY>
<IP>10.200.0.188</IP>
<MAC>90:8d:6e:62:f3:c9</MAC>
<NETBIOSNAME>DESKTOP-6Q5B6KV</NETBIOSNAME>
<WORKGROUP>WORKGROUP</WORKGROUP>
</DEVICE>
<MODULEVERSION>5.1</MODULEVERSION>
<PROCESSNUMBER>2</PROCESSNUMBER>
</CONTENT>
<DEVICEID>WIN-I9EE2IIBF66-2023-06-21-18-01-00</DEVICEID>
<QUERY>NETDISCOVERY</QUERY>
</REQUEST>
```

### Steps To reproduce

1. Have 2 computers already inventoried in the same network 
2. Make a network discovery on a computer (Create IPRange + Task)
3. 

### Your GLPI setup information

Operating system: Windows NT WIN-I9EE2IIBF66 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.7 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, random,
readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M"
Software: Microsoft-IIS/10.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38
Server Software: MySQL Community Server - GPL
Server Version: 8.0.33
Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
Parameters: root@localhost:3306/glpi
Host info: localhost via TCP/IP

PHP version (8.2.7) is supported.PHP version (8.2.7) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.33) is supported.Database engine version (8.0.33) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpriv\glpi\files/_cache has been validated. Write access to C:\inetpriv\glpi\config has been validated. Write access to C:\inetpriv\glpi\files/_cron has been validated. Write access to C:\inetpriv\glpi\files has been validated. Write access to C:\inetpriv\glpi\files/_dumps has been validated. Write access to C:\inetpriv\glpi\files/_graphs has been validated. Write access to C:\inetpriv\glpi\files/_lock has been validated. Write access to C:\inetpriv\glpi\files/_pictures has been validated. Write access to C:\inetpriv\glpi\files/_plugins has been validated. Write access to C:\inetpriv\glpi\files/_rss has been validated. Write access to C:\inetpriv\glpi\files/_sessions has been validated. Write access to C:\inetpriv\glpi\files/_tmp has been validated. Write access to C:\inetpriv\glpi\files/_uploads has been validated.Write access to C:\inetpriv\glpi\files/_cache has been validated.
Write access to C:\inetpriv\glpi\config has been validated.
Write access to C:\inetpriv\glpi\files/_cron has been validated.
Write access to C:\inetpriv\glpi\files has been validated.
Write access to C:\inetpriv\glpi\files/_dumps has been validated.
Write access to C:\inetpriv\glpi\files/_graphs has been validated.
Write access to C:\inetpriv\glpi\files/_lock has been validated.
Write access to C:\inetpriv\glpi\files/_pictures has been validated.
Write access to C:\inetpriv\glpi\files/_plugins has been validated.
Write access to C:\inetpriv\glpi\files/_rss has been validated.
Write access to C:\inetpriv\glpi\files/_sessions has been validated.
Write access to C:\inetpriv\glpi\files/_tmp has been validated.
Write access to C:\inetpriv\glpi\files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\glpi/marketplace has been validated.Write access to C:\inetpub\glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

### Anything else?

Also tested on nightly-build 10.0.8-BugFixes

Also, it update the right computer using import by names but without having the name in the inventory.
For instance, I have a linux inventoried named influxdb01.  
Here is his XML inventory file which only have is IP as dnshostname : 
![image](https://github.com/glpi-project/glpi/assets/71510592/834a01e4-38e0-4d2a-b30e-115827905e83)

But it will be update by the Unmanaged import rule (by names) and change his name : 
![Screenshot 2023-07-05 100135](https://github.com/glpi-project/glpi/assets/71510592/55488ed2-e464-4f94-b4d7-ec4851d365bd)
![Screenshot 2023-07-05 093643](https://github.com/glpi-project/glpi/assets/71510592/decbd2c9-57ac-46c2-b3f0-95a1359ea8b7)

**Comment by stonebuzz** [comment]
Hi @JulienRemi 

firstly, when the inventory  handle ```unmanaged device```, it first looks to see if a device (```computer``` / ```printer``` etc ...) has the same MAC and the same entity (because an ```unmanaged device``` can converted to an ```asset``` (see action))

if it finds an asset, it updates it (and indeed the rules are no good -> because it's the rule that match the unamanged device et not related asset found)

if no asset is found, it is added as ```unmanaged```

Can you check if related ```computer``` have same ```MAC``` and ```entity``` ?

**Comment by stonebuzz** [comment]
in general, SNMP discovery / inventory is only dedicated / designed for ```Printer``` and ```NetworkEquipment```

Trying to manage computers from SNMP discovery / inventory is a bad idea as the information returned by SNMP is not the same (hence the name change)

It's better to adapt your IP ranges/import rules to exclude PCs from SNMP discovery/inventory.

Best regards

**Comment by JulienRemi** [comment]
> in general, SNMP discovery / inventory is only dedicated / designed for `Printer` and `NetworkEquipment`
> 
> Trying to manage computers from SNMP discovery / inventory is a bad idea as the information returned by SNMP is not the same (hence the name change)
> 
> It's better to adapt your IP ranges/import rules to exclude PCs from SNMP discovery/inventory.
> 
> Best regards

I wanted to make a network discovery on the whole range to find every device on the network. I can have switches and PLC but also computers without inventory agent. I just want to ignore already inventoried computer and was thinking that I can filter them with a rule. I have a lot of different network and have automatized the IPRange creation. Is there no other way than create range without the IP of already inventoried computer ?
