### ISSUE TITLE
Massive computer remove from trash

### ISSUE THREAD

**Issue by buggzbeny** [glpi-project/glpi#15114]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

when i delete from inventory to trash no problem, it do it quickly

When i want to empty trash, i have blank page and do not go to end of action

i try to put 360s time on php.ini, try also to raise amount on memory in this file but no luck.

### Steps To reproduce

Remove computer from trash with or without removing components

### Your GLPI setup information

GLPI 10.0.7
Debian 11
Mariadb 10
PHP 8.1

**Comment by cconard96** [comment]
Please provide the requested information.

**Comment by buggzbeny** [comment]
> Please provide the requested information.

J'écris en anglais mais je suis Francais ;)
