### ISSUE TITLE
Problem attached document on ticket

### ISSUE THREAD

**Issue by buggzbeny** [glpi-project/glpi#15113]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

When i create a ticket with attached document i can see it in followup

But when i try to add new document in follow task or just document upload, i have pop up that document is moved correctly but it do not appear in ticket.

If i edit first message created with the ticket and add a document i can see the new document on timeline of ticket.

### Your GLPI setup information

GLPI 10.0.7 fresh upgrade from 9.5
Debian 11
Php 8.1

**Comment by trasher** [comment]
Please try with latest 10.0/bugfixes nightly build, this may have been fixed already.

**Comment by buggzbeny** [comment]
i replace all glpi files with the nighty builds one ?

**Comment by trasher** [comment]
OK... Wait for 10.0.8.

**Comment by buggzbeny** [comment]
> OK... Wait for 10.0.8.

when it will be released ?

**Comment by cedric-anne** [comment]
> > OK... Wait for 10.0.8.
> 
> when it will be released ?

Today.

**Comment by buggzbeny** [comment]
same problem after 10.0.8 update

**Comment by manfon10** [comment]
same problem after 10.0.8 update x2 :(

**Comment by cedric-anne** [comment]
Hi,

Do you have any active plugin?
When your try to attach a document, is there any error trace in GLPI logs?

**Comment by manfon10** [comment]
Hello, my problem is that when I update to 10.0.8 the images that were previously attached in the monitoring does not let them be seen, it throws a 403 Forbiden

**Comment by trasher** [comment]
Double check files ACLs on your system. It also seems you're talking about different issue than original one.

**Comment by cedric-anne** [comment]
@buggzbeny 

Can you give a screenshot of user profile rights ?

**Comment by buggzbeny** [comment]
Yes i can send to you, witch one do you want ? Here is one profile right :

![2023-07-12 15_11_36-Profil - Admin Responsable - GLPI et 1 page supplémentaire - Personnel – Microso](https://github.com/glpi-project/glpi/assets/45596518/6389e283-0fb1-4bbe-8d15-cab0884a9b74)

![2023-07-12 15_10_50-Profil - Admin Responsable - GLPI et 1 page supplémentaire - Personnel – Microso](https://github.com/glpi-project/glpi/assets/45596518/e83ea5b8-d5a9-4e22-b331-424c60f589e1)



 The problem occur even with super user account.

**Comment by manfon10** [comment]
> Verifique los archivos ACL en su sistema. También parece que estás hablando de un tema diferente al original.

The permissions are OK, since GLPI can write to my path where the documents and images are saved, it seems I will have to open a new number, is that correct?

**Comment by cedric-anne** [comment]
> it seems I will have to open a new number, is that correct?

Indeed, please open a new issue, as it seems to be a different one.

**Comment by cedric-anne** [comment]
Do you have some plugins? Is there something in GLPI logs?

**Comment by manfon10** [comment]
If I have several plugins, like GLPI Inventory, Oauth IMAP, Form Creator, the php logs say this:

[2023-07-13 13:18:31] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "field" in /var/www/html/glpi/src/Search.php at line 1225
  Backtrace :
  src/Search.php:839                                 Search::constructCriteriaSQL()
  src/Search.php:447                                 Search::constructSQL()
  src/Api/API.php:1662                               Search::getDatas()
  src/Api/APIRest.php:191                            Glpi\Api\API->searchItems()
  apirest.php:57                                     Glpi\Api\APIRest->call()
  public/index.php:82                                require()

![image](https://github.com/glpi-project/glpi/assets/46856278/3b445c90-0dab-4e43-bbc8-cb6873da6927)

**Comment by cedric-anne** [comment]
Could you please open the URL that is shown in red in your screenshot, and tell us what message is displayed when it is opened?

**Comment by cedric-anne** [comment]
> Another thing is that after the migration, the new cases where pasted images are attached in the description text do show them with different query params than the ones that don't load.
> 
> ![image](https://user-images.githubusercontent.com/46856278/253986827-ab7aa5d6-6950-4278-8134-3fe63c1e1e6a.png)

What are the full URL fo these images? Are they both located under a `/glpi` directory, or only the one that fails to load?

**Comment by manfon10** [comment]
Hello, if everything is in /var/lib/glpi the old one, the new one is created in the same folders as the old one depending on its format.

**Comment by cedric-anne** [comment]
> What are the full URL fo these images?

**Comment by manfon10** [comment]
![image](https://github.com/glpi-project/glpi/assets/46856278/0be4ada2-549d-4d80-bdfe-04cee63b8197)

This one with problem.

**Comment by cedric-anne** [comment]
Can you, please, give the full URL of the image that is correctly isplayed and the one that cannot be loaded? You can find these using your browser console.
Maybe the root path is different, for instance
```diff
- https://domain/glpi/front/document.send.php?...
+ https://domain/front/document.send.php?...
```

**Comment by manfon10** [comment]
Hello, I already found the problem, the image has this URL -> https://cau.eastus.cloudapp.azure.com/glpi/front/document.send.php?docid=2323&tickets_id=2140 , after the domain look for /glpi and said directory is no longer configured, do you know how I could change that?

**Comment by cedric-anne** [comment]
Hi,

#15349 will probably fix this issue.
