### ISSUE TITLE
No connector for printer device 

### ISSUE THREAD

**Issue by COFIEM-Informatique** [glpi-project/glpi#15119]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

this is not possible to add connector for a printer device.

**Comment by stonebuzz** [comment]
Are you talking about ```sockets``` ?

![image](https://github.com/glpi-project/glpi/assets/7335054/a3ee8621-acd4-4460-8d2d-771108747c09)

**Comment by trasher** [comment]
No feedback, closing.
