### ISSUE TITLE
Massive delete from trash

### ISSUE THREAD

**Issue by buggzbeny** [glpi-project/glpi#15117]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

when i delete from inventory to trash no problem, it do it quickly

When i want to empty trash, i have blank page and do not go to end of action

i try to put 360s time on php.ini, try also to raise amount on memory in this file but no luck.

### Steps To reproduce

Remove computer from trash with or without removing components

### Your GLPI setup information

GLPI 10.0.7
Debian 11
Mariadb 10
PHP 8.1

**Comment by trasher** [comment]
You still not provide requested information. See https://github.com/glpi-project/glpi/issues/15114#issuecomment-1621079145

**Comment by buggzbeny** [comment]
> You still not provide requested information. See [#15114 (comment)](https://github.com/glpi-project/glpi/issues/15114#issuecomment-1621079145)

don't understand what i need to add ?

**Comment by trasher** [comment]
logs, full setup, etc. All that is requested in template.
