### ISSUE TITLE
PL - Translation error

### ISSUE THREAD

**Issue by diegulec** [glpi-project/glpi#15120]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

When is Tab with  Actors  assigned to ticket in Polish  translate we have  "Ucestnicy"   it should be "Uczestnicy"
![Firefox_Screenshot_2023-07-05T09-49-08 918Z](https://github.com/glpi-project/glpi/assets/78162275/c9d7fadb-7b15-4c20-8803-4adacfa937a2)

### Page URL

front/ticket.form.php?

**Comment by trasher** [comment]
Please use transifex to directly fix translations https://www.transifex.com/glpi/GLPI/dashboard/
