### ISSUE TITLE
10.0.8 regression : Private followups/tasks are not visible to users with the "See Private Ones" permissions

### ISSUE THREAD

**Issue by Zoddo** [glpi-project/glpi#15128]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

I just upgraded our test instance to 10.0.8 ([to debug another issue](https://github.com/glpi-project/glpi/issues/14711)) and I noticed that all private followups and tasks are now hidden to any user (even super-admins).

After looking at the changes made in 10.0.8, it looks like it's a regression introduced by this PR:
* #14988

Reverting this PR fix the issue.

### Steps To reproduce

1. Use a profil that can see private followups/tasks (like super-admins)
2. Post a private followup and a private task
3. Notice that you can't see them
4. Revert PR #14988 : They are now visible

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.8 (/glpitest => /var/www/glpitest)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux [REDECATED] 4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.39-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: db-glpitest@localhost/glpitest
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpitest/files/_cache has been validated.
Write access to /var/www/glpitest/config has been validated.
Write access to /var/www/glpitest/files/_cron has been validated.
Write access to /var/www/glpitest/files has been validated.
Write access to /var/www/glpitest/files/_dumps has been validated.
Write access to /var/www/glpitest/files/_graphs has been validated.
Write access to /var/www/glpitest/files/_lock has been validated.
Write access to /var/www/glpitest/files/_pictures has been validated.
Write access to /var/www/glpitest/files/_plugins has been validated.
Write access to /var/www/glpitest/files/_rss has been validated.
Write access to /var/www/glpitest/files/_sessions has been validated.
Write access to /var/www/glpitest/files/_tmp has been validated.
Write access to /var/www/glpitest/files/_uploads has been validated.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpitest/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpitest"
GLPI_CONFIG_DIR: "/var/www/glpitest/config"
GLPI_VAR_DIR: "/var/www/glpitest/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpitest/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpitest/files"
GLPI_CACHE_DIR: "/var/www/glpitest/files/_cache"
GLPI_CRON_DIR: "/var/www/glpitest/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpitest/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpitest/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpitest/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpitest/files/_lock"
GLPI_LOG_DIR: "/var/www/glpitest/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpitest/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpitest/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpitest/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpitest/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpitest/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpitest/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpitest/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpitest/locales"
GLPI_VERSION: "10.0.8"
GLPI_SCHEMA_VERSION: "10.0.8@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpitest/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpitest/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpitest/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpitest/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpitest/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpitest/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpitest/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpitest/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpitest/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpitest/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpitest/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpitest/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpitest/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpitest/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpitest/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpitest/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpitest/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpitest/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpitest/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpitest/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpitest/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpitest/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpitest/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpitest/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpitest/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpitest/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpitest/vendor/psr/cache/src)
league/csv in (/var/www/glpitest/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpitest/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpitest/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpitest/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpitest/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpitest/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpitest/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpitest/vendor/symfony/cache)
html2text/html2text in (/var/www/glpitest/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpitest/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpitest/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpitest/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpitest/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpitest/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpitest/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/glpitest/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpitest/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpitest/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpitest/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
[REDECATED]

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@[REDECATED])

</pre></details><details><summary>Plugins list</summary><pre> 
	[REDECATED, but every plugins were disabled]

</pre></details>

**Comment by alexmicontini** [comment]
Idem!

**Comment by trasher** [comment]
I confirm the issue, and I confirm reverting ecb65bb5c06c230ec0f982511d60c9109f7119d2 does solve the issue.
I do not have correct fix right now.

**Comment by trasher** [comment]
Please try #15138

**Comment by trasher** [comment]
Thanks for the feedback
