### ISSUE TITLE
Profile - Language dropdown - no auto-complete

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1512]
Hello,

There isn(t auto-completion available on the language selection on the profil
![image](https://cloud.githubusercontent.com/assets/6187125/21618258/56568b0a-d1ea-11e6-8280-bbf05465caf0.png)

Should be cool ;-)

Regards,
Anael

**Comment by trasher** [comment]
It is due to configuration. Until recently (see cfe60832bad4c03872829472e8c692fe23001561) only list with 50 or more elements displays a search field.

Change the value for "Don't show search engine in dropdowns if the number of items is less than" in Setup > General and you should be done :)

**Comment by AnaelMobilia** [comment]
Thanks for the information !
So the behavior is now the same for the install screen and the profile, which is great !

Regards
