### ISSUE TITLE
Can not Login after Update to 10.0.8

### ISSUE THREAD

**Issue by ukkt** [glpi-project/glpi#15132]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.8

### Bug description

Hello,

I can not login after the update. I get the error "The requested operation is not allowed".
Please help me.

### Page URL

login.php

### Steps To reproduce

Try to login

### Your GLPI setup information

Operating system: Windows NT glpi-server 6.2 build 9200 (Windows Server 2012 Datacenter Edition) i586
PHP 8.2.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, random, readline, session, sodium, standard, tokenizer, xml, xmlreader,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Win32) OpenSSL/1.1.1m PHP/8.2.4 (Apache/2.4.52 (Win32) OpenSSL/1.1.1m PHP/8.2.4 Server at glpi-server Port
	80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Server Software: MySQL Enterprise Server - Commercial
	Server Version: 8.0.11-commercial
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@glpi-server/glpi
	Host info: glpi-server via TCP/IP
	
PHP version (8.2.4) is supported.PHP version (8.2.4) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.11) is supported.Database engine version (8.0.11) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated. Write access to C:\xampp\htdocs\glpi/config has been validated. Write access to C:\xampp\htdocs\glpi/files/_cron has been validated. Write access to C:\xampp\htdocs\glpi/files has been validated. Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated. Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated. Write access to C:\xampp\htdocs\glpi/files/_lock has been validated. Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated. Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated. Write access to C:\xampp\htdocs\glpi/files/_rss has been validated. Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated. Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated. Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/config has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "C:\xampp\htdocs\glpi": ‣ "C:\xampp\htdocs\glpi/files" ("GLPI_VAR_DIR") ‣ "C:\xampp\htdocs\glpi\config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "C:\xampp\htdocs\glpi\public".The following directories should be placed outside "C:\xampp\htdocs\glpi":
‣ "C:\xampp\htdocs\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\xampp\htdocs\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "C:\xampp\htdocs\glpi\public".
Sessions configuration is secured.Sessions configuration is secured.
OS or PHP is not relying on 64 bits integers, operations on IP addresses may produce unexpected results.OS or PHP is not relying on 64 bits integers, operations on IP addresses may produce unexpected results.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

**Comment by ukkt** [comment]
CSRF check failed for User ID:  at /glpi/front/login.php2023-07-06 04:45:37 [@KABEL254]

**Comment by cedric-anne** [comment]
Hi,

Please provide requested information.

**Comment by ukkt** [comment]
I cannot login to get the server information.

**Comment by cedric-anne** [comment]
Can you try to use a private browsing session or another browser? Maybe it is due to something wrong with cookies.

**Comment by ukkt** [comment]
Same issue.

**Comment by ukkt** [comment]
![Sessions](https://github.com/glpi-project/glpi/assets/49140655/ea6de653-ea10-4062-8e68-ec8866c4e8a7)
New session files are created and can not find any changs in the access files.

**Comment by ukkt** [comment]
[NEW_sess_uler4l8od0vhlii1u2l14bpglh.txt](https://github.com/glpi-project/glpi/files/11966251/NEW_sess_uler4l8od0vhlii1u2l14bpglh.txt)
[OLD_sess_gpmo4nfurlokijpn5jnn4oh9pv.txt](https://github.com/glpi-project/glpi/files/11966255/OLD_sess_gpmo4nfurlokijpn5jnn4oh9pv.txt)

The session files looks very different

**Comment by ukkt** [comment]
If I use my backup with the new database version (change version number to 10.0.7 in table glpi_config) it work again. I think it is a problem in the new code of 10.0.8.

**Comment by Dbuchmann001** [comment]
Same issue at mine. After update 
Logging in than GLPI says Requested action is not allowed.
Tried to fix it:
- File Permissions, Moving Plugin folder has no success
- Someone has an idea

**Comment by cedric-anne** [comment]
Hi,

What kind of authntication method are you using? Is this a local account from GLPI DB, or a LDAP authentication, or something else?

Is there anything in GLPI logs?


> Same issue at mine. After update

What was the previous version you was using. Did you update only GLPI, or did you also update system packages?

**Comment by ukkt** [comment]
Hello,

we use the GLPI DB for login. Our previous version was 10.0.7. I only updated GLPI.

**Comment by cedric-anne** [comment]
@Dbuchmann001 

Are you also using XAMPP ?

**Comment by Dbuchmann001** [comment]
@cedric-anne 
Yes we do

**Comment by ukkt** [comment]
We also use XAMPP

**Comment by orthagh** [comment]
Could you try to drop all sessions files ? (in `htdocs/glpi/files/_sessions/`)
Also if it doesn't fix, please provide, like asked, last logs entries (not the full logs please) present in `htdocs/glpi/files/_log/`

**Comment by ukkt** [comment]
It don't helps. 
[access-errors.log](https://github.com/glpi-project/glpi/files/11980325/access-errors.log)

**Comment by orthagh** [comment]
you just have this file ? no php-errors.log nor mysql-errors.log ?

**Comment by ukkt** [comment]
[php-errors.log](https://github.com/glpi-project/glpi/files/11980355/php-errors.log)
But there is nothing in.

**Comment by orthagh** [comment]
You can also check XAMPP control panel, the **APACHE** and **PHP** related logs (errors ones)

**Comment by ukkt** [comment]
[xammp_acces.log.txt](https://github.com/glpi-project/glpi/files/11980447/xammp_acces.log.txt)
This is the XAMPP access log.

**Comment by orthagh** [comment]
**access** logs doesn't help, from glpi or apache. We need to find **errors** 
![image](https://github.com/glpi-project/glpi/assets/418844/3e915cc8-623b-4d89-9499-4361c975fcb6)

P

**Comment by ukkt** [comment]
In the error.log I have only this:
_'VirtualProtect() failed [87] Falscher Parameter'_

And I have no php_error_log

**Comment by ukkt** [comment]
No, it doesn't work.

**Comment by cedric-anne** [comment]
Could you try to remove all your plugins from the `/marketplace` and `/plugins` directories and see if problem persist?

Could you try to install a GLPI 10.0.8 without using your existing data (i.e. install into a new database) and without any plugin to see if you can reproduce?

**Comment by ukkt** [comment]
Hello, 
sorry, I was on holidays. 
I have tested this also and had no luck.

**Comment by HectorZanardo** [comment]
go into php.ini and disable zend_extension=opcache by putting a ; in front and test to see if it logs in.
I really don't know why these things happen in GLPI.

**Comment by ukkt** [comment]
Hello, thank you for your help it works. But what is the problem with this extension?

**Comment by cedric-anne** [comment]
What is your opcache configuration ?

**Comment by HectorZanardo** [comment]
> Hello, thank you for your help it works. But what is the problem with this extension?

I really don't know, I also had to disable it, I can no longer access the system if I enable it.

**Comment by HectorZanardo** [comment]
> What is your opcache configuration ?


 i was using this one.




opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=8000
opcache.use_cwd=1
opcache.revalidate_freq=60
opcache.fast_shutdown=1

**Comment by cconard96** [comment]
Are you hosting more than one site under XAMPP on Windows?

**Comment by HectorZanardo** [comment]
> Are you hosting more than one site under XAMPP on Windows?

I only have it in Xamp
I think it's some setting in opcache .

**Comment by cconard96** [comment]
The reason I asked was because there could be a cache conflict. On Windows (and only Windows), all processes running the same Server API (SAPI), in this case apache2handler, under the same user account share the same OPCache instance.

You can add "opcache.cache_id=${OPCACHE_ID}" to your PHP configuration and then set a unique value to that environment variable in your Apache virtual host config(s) to have them use separate caches.

This setting only exists for Windows.

**Comment by HectorZanardo** [comment]
> The reason I asked was because there could be a cache conflict. On Windows (and only Windows), all processes running the same Server API (SAPI), in this case apache2handler, under the same user account share the same OPCache instance.
> 
> You can add "opcache.cache_id=${OPCACHE_ID}" to your PHP configuration and then set a unique value to that environment variable in your Apache virtual host config(s) (using SetEnv) to have them use separate caches.
> 
> This setting only exists for Windows.

Thanks for replying @cconard96 

I tried adding this line opcache.cache_id=${OPCACHE_ID} in php.ini and then enabling opcache but unfortunately the problems remains

**Comment by HectorZanardo** [comment]
> The reason I asked was because there could be a cache conflict. On Windows (and only Windows), all processes running the same Server API (SAPI), in this case apache2handler, under the same user account share the same OPCache instance.
> 
> You can add "opcache.cache_id=${OPCACHE_ID}" to your PHP configuration and then set a unique value to that environment variable in your Apache virtual host config(s) (using SetEnv) to have them use separate caches.
> 
> This setting only exists for Windows.

Its work now, !! Thanks @cconard96

**Comment by cconard96** [comment]
Hooray 🎉

**Comment by aspiranteabodybuilder** [comment]
Contribuindo : no meu caso eu atualizei um cliente da 9.5.x para 10.0.7
O problema é que esqueci de atualizar o virtualhost para o /public
Após fazer isso, voltou a logar normal

**Comment by cedric-anne** [comment]
Hi,

We cannot do much on GLPI side for this. Invalidating opcache on update is not an option, as it may impact other applications than GLPI.
We consider that it is either a bug in opcache, either a configuration issue.

**Comment by flyfish520** [comment]
> 
before 10.0.7 have not this issue.
