### ISSUE TITLE
glpi_queuednotifications database schema_integrity differs after 10.0.7 to 10.0.8 update

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi#15133]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Relevant log output

```shell
# php bin/console database:check_schema_integrity
Table schema differs for table "glpi_queuednotifications".
--- Expected database schema
+++ Current database schema
@@ @@
   `create_time` datetime,
   `documents` text,
   `entities_id` int NOT NULL DEFAULT 0,
-  `event` varchar(255),
   `headers` text,
   `is_deleted` tinyint NOT NULL DEFAULT 0,
   `items_id` int NOT NULL DEFAULT 0,
```

**Comment by trasher** [comment]
This field has been added on 10.0.7; your migration to previous version seems to failed somehow.
Just create missing field (you'll find definition in install/mysql/glpi-empty.sql).

**Comment by cedric-anne** [comment]
To add the missing field, you can execute:
```sql
alter table `glpi_queuednotifications` add column `event` varchar(255) DEFAULT NULL;
```

**Comment by MarcSamD** [comment]
Thank you both for your quick reply.
I confirm that @cedric-anne  SQL command can manually fix this issue.

> ```sql
> alter table `glpi_queuednotifications` add column `event` varchar(255) DEFAULT NULL;
> ```
