### ISSUE TITLE
Dashboard not displaying for Technicians profile after update 10.0.7 to 10.0.8

### ISSUE THREAD

**Issue by MarcSamD** [glpi-project/glpi#15137]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

After update from 10.0.7 to 10.0.8, the dashboards are not displayed anymore for technicians profile (they are still correctly working under super-admin profile though). 
Technicians can only see a grey line with black dots moving:

![image](https://github.com/glpi-project/glpi/assets/70358310/ebc6829c-4a19-4b37-a328-a34759102f20)

### Relevant log output

```shell
No errors recorded
```

### Page URL

/front/dashboard_assets.php

### Anything else?

I tried without success to apply the fix from https://github.com/glpi-project/glpi/issues/15131 (which is also a Dashboard issue - but different error)

**Comment by cconard96** [comment]
Do you have any warnings or errors in the browser console (F12 key > Console tab) when you load a dashboard page?

**Comment by MarcSamD** [comment]
Yes: `Uncaught SyntaxError: Unexpected token ',' (at dashboard_assets.php:2070:26)`

**Comment by cconard96** [comment]
Can you test #15139?

**Comment by cedric-anne** [comment]
Fixed by e95ba97379add2f844c7f6cb0473ec5af7d95c46.

**Comment by lrodriguezc** [comment]
Hello everyone, in our case we cloned super admin profile and modified permissions.
