### ISSUE TITLE
Windows Actions blank page --> error :/glpi/ajax/massiveaction.php 404 not found

### ISSUE THREAD

**Issue by lble44** [glpi-project/glpi#15143]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.8

### Bug description

Hi,
Since update in 10.0.7, when I want to select a consumable and click on Actions :
![image](https://github.com/glpi-project/glpi/assets/69039920/9716410f-fc96-408f-84c3-f5a684e7a3ce)
I get a blank page.
In debug mode, I did'nt get any error, and nothing in the log.
I just had the firefox debugger which specifies :
![image](https://github.com/glpi-project/glpi/assets/69039920/b73fb4cb-324f-45ed-8e37-03e17350735d)

### Relevant log output

```shell
No error in log file.
```

### Steps To reproduce

1. GLPI 10.0.8 - PHP8.0
2. Go to consumables, then select a consumable used and click on Actions
3. A blank page appear

### Your GLPI setup information

GLPI 10.0.8 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by trasher** [comment]
I do not reproduce. Make sure the file exists, and aslo make sure your webserver setup does not break some URLs.

**Comment by trasher** [comment]
No feedback, closing.

**Comment by lble44** [comment]
Yes you were right, my webserver which is like a proxy seems to break some URL, as a direct access to the GLPI works.
Thank's
