### ISSUE TITLE
Problem with access to inventory tab with locked fields tab

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#15156]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Despite assigning permissions in the profile for:
**"INVENTORY ->Inventory -> locked fields"**
users do not have access to the tab.
![image](https://github.com/glpi-project/glpi/assets/5873929/94938b33-cd73-4de3-83cf-e481807b92ee)

Result:
.../front/lockedfield.php
![image](https://github.com/glpi-project/glpi/assets/5873929/a02b2ecc-3fab-454e-9180-cd7d8dc0d7c3)

### Page URL

http:/servername.domain/front/lockedfield.php

### Steps To reproduce

1. Add permision for profile
2. log ass user with this profile
3. Go to Locked Fields tab

**Comment by stonebuzz** [comment]
Hi @Wolvverine 

please update your GLPI to latest version =)

this has already been corrected

**Comment by Wolvverine** [comment]
Thanks @stonebuzz , that would be the best option , unfortunately , before an update is possible there must be all plugins compatible with 10.0.8 version of GLPI. And due to the large changes in GLPI between minor versions of GLPI , accualizations are not immediately possible.

Can you point to the commit in which this was corrected?

**Comment by cedric-anne** [comment]
> And due to the large changes in GLPI between minor versions of GLPI

When there are some changes in bugfixes versions that have a negative impact on plugins, we expect plugin developpers to report it to us. As far as I know, no plugin developper complains recently about anything that blocks its plugin (except in #15051), and if it was the case, we would probably give some help.

**Comment by trasher** [comment]
Several fixes has been done, in both 10.0.7 and 10.0.8. We cannot certify a commit among all others would fix the issue as excepted.
Upgrading to latest version is the only reliable way to go; you'll have to see plugins problems with respective maintainers.
