### ISSUE TITLE
10.0.8 : IF The name "port" in the file XML is very long and The IP is not filled in with SNMP inventory

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#15152]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

When I want to reassemble an HP brand printer with SNMP inventory. The ip is not remounted because of this error
The name in the file XML is very long and The IP is not filled in
![image](https://github.com/glpi-project/glpi/assets/68054991/23597bf7-82fc-4249-a376-258952ac2f61)
![image](https://github.com/glpi-project/glpi/assets/68054991/4be11edf-3b43-4553-b17b-e73d0ea85f0d)

i must edit the file XML , change name "HP ETHERNET MULTI-ENVIRONMENT,ROM none,JETDIRECT,JD153,EEPROM JSI25050010" to "ETHO" for example. L'inventory SNMP its OK

### Relevant log output

```shell
no log
```

### Steps To reproduce

1 administration
2 inventory
3 import

**Comment by steph461** [comment]
i have this issue all "HP PRINTERS"

**Comment by trasher** [comment]
Import is denied with default rules using provided XML file.

**Comment by steph461** [comment]
[192.168.1.1.zip](https://github.com/glpi-project/glpi/files/11979635/192.168.1.1.zip)

I have test its ok :)
