### ISSUE TITLE
Error migration:timestamps 10.0.8

### ISSUE THREAD

**Issue by guruznet** [glpi-project/glpi#15161]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

Error when running the command below:

<img width="1399" alt="Captura de Tela 2023-07-07 às 11 28 10" src="https://github.com/glpi-project/glpi/assets/24541944/7abdfb62-a494-4743-b299-b76d58dbbcbb">

glpi:/var/www/html/glpi.10\# php bin/console migration:timestamps
Uncaught Exception Error: Call to undefined function session_status() in /var/www/html/glpi.10/src/Session.php at line 228

<img width="1358" alt="Captura de Tela 2023-07-07 às 11 09 09" src="https://github.com/glpi-project/glpi/assets/24541944/88dcc623-5975-46d4-80ca-a5e7274cca98">

### Steps To reproduce

1. docker exec -ti glpi /bin/bash
2. cd /var/www/html/glpi.10
3. php bin/console migration:timestamps

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.8 ( => /var/www/html/glpi.10)
Installation mode: TARBALL
Current language:pt_BR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.15.49-linuxkit-pr #1 SMP Thu May 25 07:17:40 UTC 2023 x86_64
PHP 8.2.8 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml,
	mbstring, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, random, redis, session, snmp, soap, sockets,
	sodium, standard, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Server Software: mariadb.org binary distribution
	Server Version: 11.0.2-MariaDB-1:11.0.2+maria~ubu2204-log
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@mariadb/glpi10
	Host info: mariadb via TCP/IP
	
PHP version (8.2.8) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (11.0.2) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi.10/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi.10"
GLPI_CONFIG_DIR: "/etc/glpi"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi.10/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi.10/locales"
GLPI_VERSION: "10.0.8"
GLPI_SCHEMA_VERSION: "10.0.8"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi.10/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi.10/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi.10/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi.10/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi.10/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi.10/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi.10/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi.10/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi.10/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi.10/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi.10/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi.10/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi.10/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi.10/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi.10/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi.10/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi.10/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi.10/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi.10/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi.10/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi.10/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi.10/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi.10/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi.10/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi.10/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi.10/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi.10/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi.10/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi.10/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi.10/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi.10/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi.10/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi.10/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi.10/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi.10/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi.10/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi.10/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi.10/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi.10/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi.10/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi.10/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi.10/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi.10/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi.10/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	activity             Name: Activities                     Version: 3.1.2      State: Enabled                                 
		Install Method: Manual
	actualtime           Name: ActualTime                     Version: 2.1.0      State: Enabled                                 
		Install Method: Manual
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	news                 Name: Alertas                        Version: 1.12.1     State: Enabled                                 
		Install Method: Manual
	archisw              Name: Apps structures                Version: 3.0.8      State: Enabled                                 
		Install Method: Manual
	archibp              Name: Business Processes             Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	fields               Name: Campos adicionais              Version: 1.20.6     State: Enabled                                 
		Install Method: Manual
	screenshot           Name: Captura de tela                Version: 2.0.2      State: Enabled                                 
		Install Method: Manual
	positions            Name: Cartografia                    Version: 6.0.2      State: Enabled                                 
		Install Method: Manual
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Enabled                                 
		Install Method: Manual
	shellcommands        Name: Comandos de Shell              Version: 4.0.1      State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	connections          Name: Connections                    Version: 10.0.0     State: Enabled                                 
		Install Method: Manual
	accounts             Name: Contas                         Version: 3.0.3      State: Enabled                                 
		Install Method: Manual
	costs                Name: Costs                          Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	badges               Name: Crachás                        Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	dataflows            Name: Dataflows                      Version: 3.0.5      State: Enabled                                 
		Install Method: Manual
	addressing           Name: Endereçamento IP               Version: 3.0.1      State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalonamento                  Version: 2.9.0      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Manual
	archifun             Name: Functional Areas               Version: 2.2.9      State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Manual
	order                Name: Gerenciamento das ordens de co Version: 2.10.4     State: Enabled                                 
		Install Method: Manual
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.11.2     State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.3     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.2      State: Enabled                                 
		Install Method: Manual
	itilcategorygroups   Name: Grupos ItilCategory            Version: 2.5.1      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Importação de dados            Version: 2.13.2     State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.9.0      State: Enabled                                 
		Install Method: Manual
	releases             Name: Liberações                     Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	timelineticket       Name: Linha do tempo dos chamados    Version: 10.0+1.1   State: Enabled                                 
		Install Method: Manual
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	moreticket           Name: Mais Chamados                  Version: 1.7.3      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Mais Relatórios                Version: 1.8.2      State: Enabled                                 
		Install Method: Manual
	satisfaction         Name: Mais satisfação                Version: 1.6.1      State: Enabled                                 
		Install Method: Manual
	metademands          Name: Meta-Demands                   Version: 3.3.0      State: Enabled                                 
		Install Method: Manual
	mydashboard          Name: Meu Painel                     Version: 2.1.5      State: Installed / not activated               
		Install Method: Manual
	mfa                  Name: MFA                            Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Enabled                                 
		Install Method: Manual
	additionalalerts     Name: Outros alertas                 Version: 2.4.0      State: Enabled                                 
		Install Method: Manual
	manageentities       Name: Portal de entidades            Version: 4.0.3      State: Enabled                                 
		Install Method: Manual
	resources            Name: Recursos humanos               Version: 3.0.4      State: Enabled                                 
		Install Method: Manual
	reports              Name: Relatórios                     Version: 1.16.0     State: Enabled                                 
		Install Method: Manual
	roundrobin           Name: Round Robin                    Version: 1.0.0      State: Enabled                                 
		Install Method: Manual
	stab                 Name: Split Timeline Action Buttons  Version: 1.1.2      State: Enabled                                 
		Install Method: Manual
	statecheck           Name: Statecheck Rules               Version: 2.3.9      State: Enabled                                 
		Install Method: Manual
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	ticketmail           Name: Ticket Mail                    Version: 3.6.2      State: Enabled                                 
		Install Method: Manual
	typology             Name: Tipologias                     Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Manual
	vip                  Name: VIP                            Version: 1.8.2      State: Enabled                                 
		Install Method: Manual
	webhook              Name: Webhooks                       Version: 1.0.14     State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

GLPi and MariaDB are using different images.
Reason: MariaDB has other databases for other applications.

## BEGIN: mariadb (docker-compose.yaml)

version: "3"

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    hostname: mariadb
    restart: "no"
    command:
      [
        '--log-bin=mysqld-bin',
        \# Logging
        '--slow-query_log_file=/var/lib/mysql/mariadb-slow.log',
        '--slow_query_log=1',
        '--long_query_time=1',
        '--innodb_buffer_pool_size=1024M',
        '--innodb_read_io_threads=4',
        '--innodb_flush_log_at_trx_commit=2',
        '--innodb_flush_method=O_DIRECT',
        '--transaction-isolation=READ-COMMITTED',
        '--binlog-format=ROW'
      ]
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: XXXX
      MYSQL_ROOT_PASSWORD: XXXX
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 128M
    volumes:
      - data_mariadb:/var/lib/mysql

volumes:
  data_mariadb:
    external: true

networks:
  default:
    name: hammers
    external: true

## BEGIN: glpi (Dockerfile)

FROM alpine:3.18.2

ENV HTTPD_HOME=/etc/apache2 \
    HTTPD_CONF=/etc/apache2/httpd.conf \
    HTTPD_HTML=/var/www/html \
    HTTPD_CGI=/var/www/cgi-bin \
    HTTPD_FCGI=/var/www/fcgi-bin \
    GLPI_ETC=/etc/glpi \
    GLPI_HOME=/var/www/html/glpi.10 \
    GLPI_LIB=/var/lib/glpi \
    GLPI_LOG=/var/log/glpi \
    GLPI_SSL=/etc/ssl \
    PHP_INI=/etc/php82/php.ini \
    GLPI_POSTFIX=/etc/postfix/main.cf

RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
    apache2-proxy \
    apache2-ssl \
    apache2-utils \
    bash \
    build-base \
    bzip2 \
    cronie \
    cronie-openrc \
    ca-certificates \
    composer \
    composer-bash-completion \
    curl \
    fcgi \
    gzip \
    logrotate \
    openrc \
    openssl \
    postfix \
    rsyslog \
    rsyslog-http \
    tzdata \
    unzip \
    zip \
    php82 \
    php82-apache2 \
    php82-bcmath \
    php82-bz2 \
    php82-calendar \
    php82-cgi \
    php82-cli \
    php82-common \
    php82-ctype \
    php82-curl \
    php82-dba \
    php82-dbg \
    php82-dom \
    php82-embed \
    php82-exif \
    php82-fileinfo \
    php82-fpm \
    php82-ftp \
    php82-gd \
    php82-gettext \
    php82-iconv \
    php82-imap \
    php82-intl \
    php82-json \
    php82-ldap \
    php82-mbstring \
    php82-mysqli \
    php82-opcache \
    php82-openssl \
    php82-pdo \
    php82-pdo_mysql \
    php82-pdo_sqlite \
    php82-pecl-redis \
    php82-phar \
    php82-posix \
    php82-session \
    php82-simplexml \
    php82-snmp \
    php82-soap \
    php82-sodium \
    php82-tokenizer \
    php82-xml \
    php82-xmlreader \
    php82-xmlwriter \
    php82-xsl \
    php82-zip \
    php82-zlib

RUN cd /tmp && \
    cd /etc/apache2 && \
    ln -sf /usr/lib/apache2 modules && \
    mkdir -p ${HTTPD_HOME}/logs && \
    mkdir -p ${GLPI_LOG}/_cache && \
    mkdir -p ${GLPI_LOG}/_cron && \
    mkdir -p ${GLPI_LOG}/_dumps && \
    mkdir -p ${GLPI_LOG}/_graphs && \
    mkdir -p ${GLPI_LOG}/_lock && \
    mkdir -p ${GLPI_LOG}/_log && \
    mkdir -p ${GLPI_LOG}/_pictures && \
    mkdir -p ${GLPI_LOG}/_plugins && \
    mkdir -p ${GLPI_LOG}/_rss && \
    mkdir -p ${GLPI_LOG}/_sessions && \
    mkdir -p ${GLPI_LOG}/_tmp && \
    mkdir -p ${GLPI_LOG}/_uploads && \
    mkdir -p ${GLPI_LIB}/_cache && \
    mkdir -p ${GLPI_LIB}/_cron && \
    mkdir -p ${GLPI_LIB}/_dumps && \
    mkdir -p ${GLPI_LIB}/_graphs && \
    mkdir -p ${GLPI_LIB}/_locales && \
    mkdir -p ${GLPI_LIB}/_lock && \
    mkdir -p ${GLPI_LIB}/_log && \
    mkdir -p ${GLPI_LIB}/_pictures && \
    mkdir -p ${GLPI_LIB}/_plugins && \
    mkdir -p ${GLPI_LIB}/_rss && \
    mkdir -p ${GLPI_LIB}/_sessions && \
    mkdir -p ${GLPI_LIB}/_tmp && \
    mkdir -p ${GLPI_LIB}/_uploads && \
    mkdir -p ${HTTPD_HTML} && \
    mkdir -p ${HTTPD_CGI} && \
    mkdir -p ${HTTPD_FCGI} && \
    mkdir -p ${GLPI_ETC} && \
    chown -R apache: ${GLPI_LIB} && \
    chown -R apache: ${GLPI_LOG} && \
    chown -R apache: ${GLPI_ETC} && \
    echo "America/Sao_Paulo" > /etc/timezone && \
    cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime && \
    rm -rf /var/cache/apk/*

COPY .docker/glpi10.tar.bz2 /tmp
COPY .docker/glpi.crt ${GLPI_SSL}/apache2
COPY .docker/glpi.csr ${GLPI_SSL}/apache2
COPY .docker/glpi.key ${GLPI_SSL}/private
COPY .docker/config_db.php ${GLPI_ETC}
COPY .docker/glpicrypt.key ${GLPI_ETC}
COPY .docker/httpd.conf ${HTTPD_HOME}
COPY .docker/status.conf ${HTTPD_HOME}/conf.d
COPY .docker/glpi.vhost.conf ${HTTPD_HOME}/conf.d
COPY .docker/.bashrc /root
COPY .docker/.bash_profile /root
COPY .docker/.my.cnf /root
COPY .docker/glpi-start.sh /opt

RUN cd ${HTTPD_HTML} && \
    tar xjvf /tmp/glpi10.tar.bz2 && \
    rm -f /tmp/glpi10.tar.bz2 && \
    chown -R apache: ${GLPI_HOME} && \
    chmod 000 ${GLPI_HOME}/install && \
    chmod +x /opt/glpi-start.sh

COPY .docker/favicon.ico ${GLPI_HOME}/pics
COPY .docker/.htaccess.install ${GLPI_HOME}/install/
COPY .docker/local_define.php ${GLPI_HOME}/config

\# Enable modules
RUN sed -i 's/\;\(session.cookie_secure =\)/\1 on/g' ${PHP_INI} && \
    sed -i 's/\(session.cookie_httponly =\)/\1 on/g' ${PHP_INI} && \
    sed -i 's/^\(ServerTokens\) OS/\1 Prod/g' ${HTTPD_CONF} && \
    sed -i '221 a ServerName localhost:80' ${HTTPD_CONF} && \
    sed -i 's/\(ServerSignature\) On/\1 Off/g' ${HTTPD_CONF} && \
    sed -i 's/\(Require host\) .example.com/\1 .localdomain/g' ${HTTPD_HOME}/conf.d/info.conf && \
    sed -i '138 a inet_interfaces = all' ${GLPI_POSTFIX} && \
    sed -i '186 a mydestination = \$myhostname, localhost.\$mydomain, localhost' ${GLPI_POSTFIX} && \
    sed -i '412 a alias_maps = hash:/etc/aliases' ${GLPI_POSTFIX} && \
    sed -i '422 a alias_database = hash:/etc/aliases' ${GLPI_POSTFIX} && \
    sed -i 's,#\(LoadModule access_compat_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule alias_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule allowmethods_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule auth_basic_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule auth_digest_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authn_anon_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authn_core_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authn_dbd_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authn_dbm_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authn_file_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authn_socache_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_core_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_dbd_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_dbm_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_groupfile_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_host_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_owner_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule authz_user_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule autoindex_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule cache_disk_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule cache_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule cache_socache_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule data_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule dbd_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule deflate_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule dir_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule dumpio_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule echo_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule env_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule expires_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule ext_filter_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule filter_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule headers_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule include_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule info_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule log_config_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule logio_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule macro_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule mime_magic_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule mime_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule remoteip_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule reqtimeout_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule request_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule rewrite_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule setenvif_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule slotmem_plain_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule socache_dbm_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule socache_memcache_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule status_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule substitute_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule suexec_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule unique_id_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule unixd_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule userdir_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule version_module\),\1,g' ${HTTPD_CONF} && \
    sed -i 's,#\(LoadModule vhost_alias_module\),\1,g' ${HTTPD_CONF}

ENTRYPOINT [ "/opt/glpi-start.sh" ]

EXPOSE 80 443

## BEGIN: glpi (docker-compose.yaml)
version: "3"

services:
  glpi:
    image: glpi
    container_name: glpi
    hostname: glpi
    restart: "no"
    ports:
      - 8990:80
      - 8993:443
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.50'
          memory: 16M
    volumes:
      - data_glpi_etc:/etc/apache2/logs
      - data_glpi_log:/var/log/glpi
      - data_glpi_lib:/var/lib/glpi
      - data_glpi_apache2:/var/log/apache2
      - data_glpi_postfix:/var/spool/postfix

volumes:
  data_glpi_etc:
    external: true
  data_glpi_log:
    external: true
  data_glpi_lib:
    external: true
  data_glpi_apache2:
    external: true
  data_glpi_postfix:
    external: true

networks:
  default:
    name: hammers
    external: true

**Comment by cedric-anne** [comment]
Hi,

The session extension is probably not loaded in CLI context. Please verify your PHP configuration.

**Comment by trasher** [comment]
No feedback, closing.
