### ISSUE TITLE
Seguimientos Privados no se pueden visualizar

### ISSUE THREAD

**Issue by danielrodrigsand** [glpi-project/glpi#15169]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.8

### Bug description

Luego de actualizar a 10.0.8 los seguimientos que se añaden como privados no se visualizan en el caso, unicamente se pueden ver las tareas.

### Anything else?

![Seguimiento](https://github.com/glpi-project/glpi/assets/73403325/08033ec3-ec82-43a9-a0b6-cb276eb1e1e3)

**Comment by cedric-anne** [comment]
1. It is requested to write in English.
2. Duplicates #15128.
