### ISSUE TITLE
numerous locked domain items for a computer

### ISSUE THREAD

**Issue by static302** [glpi-project/glpi#15168]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

For every computer I have a lot of locked dup domain fields, they are just search domains and/or ips, not even real domain names, but the main problem is that those items stay for long time.
![Screenshot from 2023-07-08 14-13-24](https://github.com/glpi-project/glpi/assets/42393000/ca181d7d-ad31-40ca-91a5-66564f0a9ff7)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.8 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux 5.15.0-76-generic #83-Ubuntu SMP Thu Jun 15 19:16:32 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.13 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at glpi.xbet.lan Port 443
)
	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuser@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.13) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.8"
GLPI_SCHEMA_VERSION: "10.0.8@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.20.6     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.2      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.1      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
Locks are added when a field is "manually" modified (ie. not from inventory process). After a lock is set, it won't be removed unless you do it explicitly.
Do you have any plugins that may change domains relations? Or an external script (from API, for example)?

It may be an issue from inventory itself, of course; but we need a way to reproduce in the case.

**Comment by static302** [comment]
Thank you for your response.

No, I do not have any plugins specifically designed to work with domains. While I heavily rely on plugins from my list, none of them involve domain functionality. Well, GLPI inventory does, but I do not use this functions.

And yes, I work with glpi via API in scripts, but not for managing domains. In reality, I do not utilize domains at all. However, the reason this bug concerns me is because the locked domain fields have a significant number of entries (1 billion and counting), which impacts various operations involving this table links, such as host removal.

Thank you for your attention to this matter.

**Comment by trasher** [comment]
We need a way to reproduce on our side, from a blank database. I've launched several times an inventory on 10.0.9 on a computer that belongs to a domain, it never creates any lock, so basically, all is OK on my side.

So, there is something in your setup and/or data that cause this issue. Try to reproduce without any plugins, maybe also check your rules. I have no other idea.

**Comment by static302** [comment]
I'll install bare default glpi server and will point some new and existing hosts to it.
What i see on current glpi installs - domain fields created for search option on linux hosts, is it expected behavior?
Because according to https://glpi-user-documentation.readthedocs.io/fr/latest/modules/management/domains.html?highlight=domain#domains they should not in my understanding.

**Comment by static302** [comment]
Made test environment consist of server and 5 clients (server also has client installed, so 6 in total).
Server is all defaults, pure bare install.
All machines are identical when it comes to OS, configurations, resolv.conf (`search test.domain.lan`) and so on.
Agents with identical configs.
After first agent force launch `glpi-agent -f` (executed via ansible simultaneously) i've got 6 domain records:
```
MariaDB [glpi]> SELECT * FROM `glpi_domains` WHERE `name` IN (SELECT `name` FROM `glpi_domains` GROUP BY `name` HAVING COUNT(*) > 1);
+----+-----------------+-------------+--------------+----------------+-----------------+---------------------+---------------+----------------+------------+---------+-------------+---------------+-----------+---------------------+---------------------+
| id | name            | entities_id | is_recursive | domaintypes_id | date_expiration | date_domaincreation | users_id_tech | groups_id_tech | is_deleted | comment | is_template | template_name | is_active | date_mod            | date_creation       |
+----+-----------------+-------------+--------------+----------------+-----------------+---------------------+---------------+----------------+------------+---------+-------------+---------------+-----------+---------------------+---------------------+
|  1 | test.domain.lan |           0 |            0 |              0 | NULL            | NULL                |             0 |              0 |          0 | NULL    |           0 | NULL          |         0 | 2023-07-14 17:19:39 | 2023-07-14 17:19:39 |
|  2 | test.domain.lan |           0 |            0 |              0 | NULL            | NULL                |             0 |              0 |          0 | NULL    |           0 | NULL          |         0 | 2023-07-14 17:19:39 | 2023-07-14 17:19:39 |
|  3 | test.domain.lan |           0 |            0 |              0 | NULL            | NULL                |             0 |              0 |          0 | NULL    |           0 | NULL          |         0 | 2023-07-14 17:19:39 | 2023-07-14 17:19:39 |
|  4 | test.domain.lan |           0 |            0 |              0 | NULL            | NULL                |             0 |              0 |          0 | NULL    |           0 | NULL          |         0 | 2023-07-14 17:19:39 | 2023-07-14 17:19:39 |
|  5 | test.domain.lan |           0 |            0 |              0 | NULL            | NULL                |             0 |              0 |          0 | NULL    |           0 | NULL          |         0 | 2023-07-14 17:19:39 | 2023-07-14 17:19:39 |
|  6 | test.domain.lan |           0 |            0 |              0 | NULL            | NULL                |             0 |              0 |          0 | NULL    |           0 | NULL          |         0 | 2023-07-14 17:19:39 | 2023-07-14 17:19:39 |
+----+-----------------+-------------+--------------+----------------+-----------------+---------------------+---------------+----------------+------------+---------+-------------+---------------+-----------+---------------------+---------------------+
6 rows in set (0.001 sec)
```
So every machine got their own but same domain linked with them.

After second launch domain relinked and locked items appeared:
```
MariaDB [glpi]> SELECT * FROM `glpi_domains_items` WHERE `itemtype` = 'Computer' AND `items_id` IN (SELECT `items_id` FROM `glpi_domains_items` GROUP BY `items_id` HAVING COUNT(*) > 1);
+----+------------+----------+----------+--------------------+------------+------------+
| id | domains_id | items_id | itemtype | domainrelations_id | is_dynamic | is_deleted |
+----+------------+----------+----------+--------------------+------------+------------+
|  2 |          2 |        2 | Computer |                  1 |          1 |          1 |
|  3 |          3 |        3 | Computer |                  1 |          1 |          1 |
|  4 |          4 |        4 | Computer |                  1 |          1 |          1 |
|  5 |          5 |        5 | Computer |                  1 |          1 |          1 |
|  6 |          6 |        6 | Computer |                  1 |          1 |          1 |
|  7 |          1 |        2 | Computer |                  1 |          1 |          0 |
|  8 |          1 |        3 | Computer |                  1 |          1 |          0 |
|  9 |          1 |        4 | Computer |                  1 |          1 |          0 |
| 10 |          1 |        5 | Computer |                  1 |          1 |          0 |
| 11 |          1 |        6 | Computer |                  1 |          1 |          0 |
+----+------------+----------+----------+--------------------+------------+------------+
10 rows in set (0.001 sec)
```

Next, changed on one of clients string `search test.domain.lan` to `search test.domain.lan another-test.domain.lan` in /etc/resolv.conf. After report - nothing changed, second search domain ignored entirely.
Then i swapped domains in search (`search another-test.domain.lan test.domain.lan`) and got domain record `another-test.domain.lan` in `glpi_domains` table and one more lock for this test machine, because from glpi point of view there could be only one value for search option in resolv.conf.

In ideal world it shouldn't happen, clients connecting with some timedrift and all should run as expected, but we're in the real world :)
And I didn't even tried to add multiple entities to mix, since entries in domain table have `is_recursive=0` but clients with those domains can exist in different entities.

My thoughts on the subject:
1. For folks who don't care about domain information, is it suitable to ask adding flag to enable or disable domain functionality in inventory entirely? It could be enabled by default, so for default install everything will work as before.
2. Maybe lock domain table while inserting new record to prevent dups?
3. Possibility of more than one value for search option should be taken into account.
4. Is it possible to change `is_recursive=0` to `is_recursive=1` for new domain records? Or  it also could be configurable and 0 by default but with ability to change it to 1 in UI.

Thanks for your hard work and awesome piece of software. Cheers.

**Comment by OscarBeiro** [comment]
Hi,

I know it is a new feature but adding Domains to the Fields Unicity supported types might be a way to avoid these duplication situations.

Just my two cents

**Comment by static302** [comment]
Yeah, it could be the way to solve one part of the problem if it will be implemented, thanks.

**Comment by trasher** [comment]
I spent again a lot of time yesterday,  and I'm still not able to reproduce on current 10.0/bugfixes branch.
