### ISSUE TITLE
Error al renderizar la tarjeta

### ISSUE THREAD

**Issue by manfon10** [glpi-project/glpi#15171]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

Realice una migración exitosa de GLPI a la ultima versión, pero al iniciar sesión algunos paneles de la central muestran el error _> Error al renderizar la tarjeta.

![image](https://github.com/glpi-project/glpi/assets/46856278/7f9e9111-fa16-4342-8c16-062793eb603a)

**Comment by cedric-anne** [comment]
1. It is requested to write in English.
2. Duplicates #15137.

**Comment by manfon10** [comment]
Hello, I applied what they commented in issue #15137 but the same Rendering error continues, any recommendations?

![image](https://github.com/glpi-project/glpi/assets/46856278/398b8ef4-bc2f-47b8-b800-06d1995e9b86)

**Comment by manfon10** [comment]
Hi,

https://github.com/glpi-project/glpi/pull/15134 fixes this issue.
