### ISSUE TITLE
[GLPI 9.1.1] Mailcollector : All mails goes to Refused Folder 

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1518]
With this commit, All mails which not match rules goes to Refused Folder 

https://github.com/glpi-project/glpi/commit/879a6575baee2353c9967ce5d9134a6450b19173

But the "List of not imported emails" menu is here for check not matched emails.

In my case i don't want to move automaticly the non-matched emails to this folder.

Need add a config parameter into collector, i think !

**Comment by trasher** [comment]
Configuration parameters won't be added on bugfixes releases

**Comment by Armin83** [comment]
sry for post here but i don't know how to configure the accept or refused folder correct.

You can see my request
http://forum.glpi-project.org/viewtopic.php?id=156328

it don't work:
```
2017-05-03 08:44:03 [@myhost]
  *** PHP User Notice(1024): Falsche Konfiguration für den Ordner accepted des Empfängers it-support@mydomain.de
Variables:<wddxPacket version='1.0'><header><comment>Variables</comment></header><data><struct><var name='mid'><number>2</number></var><var name='folder'><string>accepted</string></var><var name='name'><string>accepted</string></var></struct></data></wddxPacket>
  Backtrace :
  :
  inc/mailcollector.class.php:1558                   trigger_error()
  inc/mailcollector.class.php:580                    MailCollector->deleteMails()
  inc/mailcollector.class.php:1614                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:88                                  CronTask::launch()
2017-05-03 08:44:04 [@myhost]
  *** PHP Notice(8): Unknown: [TRYCREATE] The destination mailbox could not be found. (errflg=2)
  Backtrace :
  :
2017-05-03 08:44:04 [@myhost]
  *** PHP Notice(8): Unknown: [TRYCREATE] The destination mailbox could not be found. (errflg=2)
  Backtrace :
  :


```

![img_001](https://cloud.githubusercontent.com/assets/19192087/25650715/2ac65a8a-2fdf-11e7-9994-f902c982b65d.jpg)

**Comment by Armin83** [comment]
okay sorry again. I solved it. But i don't find something in english forum, old / new documentation or help files.

INBOX/accepted
INBOX/refused

It is a german mailbox but i use the english word for Posteingang (INBOX). My custom folder have english name. now it works for me.
