### ISSUE TITLE
Can't See Private follow up after upgrade to 10.0.8 version

### ISSUE THREAD

**Issue by espacitto** [glpi-project/glpi#15186]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

Hello,

Technician, admin and super-admin can't see Private follow-ups after upgrade even if the ticket was created by them.

Regards.

**Comment by cconard96** [comment]
Duplicate of #15128
