### ISSUE TITLE
Agent presents in Agents list in glpi inventory but not linked (Element = 0) 

### ISSUE THREAD

**Issue by jbesnard** [glpi-project/glpi#15206]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

Hi,
I've got an error with some computers when I launch install (and after).
Agent is correctly detected by GLPI Inventory but no element is linked to the Agent. Only a "0" is display in the column and if I get into the Agent, "Linked Element" is void.

I tried my test server with Nightly Builds 10.0-e18dea0 
I've try to reset rules without success

### Relevant log output

```shell
client:
[Wed Jul 12 16:47:03 2023][info] target server0: server http://srv-asap10-test.mydom.fr/
[Wed Jul 12 16:47:03 2023][info] sending contact request to server0
[Wed Jul 12 16:47:03 2023][info] running task Inventory
[Wed Jul 12 16:47:03 2023][info] New inventory from NBK00413.mydom.fr-2023-07-12-15-11-26 for server0
[Wed Jul 12 16:47:42 2023][error] [http client] communication error: 500 Internal Server Error
[Wed Jul 12 16:47:43 2023][info] target server0: next run: Thu Jul 13 16:47:23 2023 - http://srv-asap10-test.mydom.fr/
[Wed Jul 12 16:47:43 2023][info] GLPI Agent memory usage: WSS=3416064 PFU=160505856

Server:
[Wed Jul 12 16:27:04.648465 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/Device.php on line 173
[Wed Jul 12 16:27:04.649580 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/Device.php on line 109
[Wed Jul 12 16:27:04.649637 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/Device.php on line 173
[Wed Jul 12 16:27:04.650405 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 131
[Wed Jul 12 16:27:04.650653 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 136
[Wed Jul 12 16:27:04.650781 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "entities_id" in /var/www/html/glpi/src/Item_OperatingSystem.php on line 645
[Wed Jul 12 16:27:04.650826 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "is_recursive" in /var/www/html/glpi/src/Item_OperatingSystem.php on line 646
[Wed Jul 12 16:27:04.651564 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 158
[Wed Jul 12 16:27:04.651602 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 159
[Wed Jul 12 16:27:04.651636 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 167
[Wed Jul 12 16:27:04.651663 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/OperatingSystem.php on line 168
[Wed Jul 12 16:27:04.652173 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/Printer.php on line 284
[Wed Jul 12 16:27:04.663808 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/Software.php on line 331
[Wed Jul 12 16:27:04.665758 2023] [php:warn] [pid 371624] [client 172.16.3.143:53069] PHP Warning:  Undefined array key "id" in /var/www/html/glpi/src/Inventory/Asset/Software.php on line 921
```

### Steps To reproduce

No idea .. it happened or not even on same model

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.8 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux srv-asap 5.4.0-153-generic #170-Ubuntu SMP Fri Jun 16 13:43:31 UTC 2023 x86_64
PHP 8.1.21 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlsrv, posix, readline, session, shmop, snmp, soap, sockets, sodium, sqlsrv, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at mydom.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.170
Server Software: Ubuntu 20.04
	Server Version: 10.3.38-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.1.21) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.38) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.8"
GLPI_SCHEMA_VERSION: "10.0.8@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/html/glpi/marketplace/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP

</pre></details><details><summary>Plugins list</summary><pre> 
	barcode              Name: Barcode                        Version: 2.1.0      State: Installed / not activated               
		Install Method: Manual
	positions            Name: Cartographie                   Version: 6.0.2      State: Enabled                                 
		Install Method: Marketplace
	servicecatalog       Name: Catalogue de service           Version: 2.0.7      State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.20.6     State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	uninstall            Name: Cycle de vie des matériels (un Version: 2.9.0      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.1.5      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.2     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Replaced                                
		Install Method: Manual
	genericobject        Name: Gestion d'objets               Version: 2.14.3     State: Enabled                                 
		Install Method: Marketplace
	glpi2mdt             Name: GLPI 2 MDT                     Version: 0.3.0      State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.3      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	sccm                 Name: Interface - SCCM               Version: 2.4.3      State: Installed / not activated               
		Install Method: Marketplace
	metademands          Name: Meta-Demandes                  Version: 3.3.0      State: Enabled                                 
		Install Method: Marketplace
	browsernotification  Name: Notification de Navigateur     Version: 1.1.9      State: Installed / not activated               
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	reports              Name: Rapports                       Version: 1.14.1     State: Installed / not activated               
		Install Method: Manual
	reservation          Name: Reservation                    Version: 2.4.4      State: Enabled                                 
		Install Method: Manual
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	transmissions        Name: Transmissions                  Version: 0.0.1      State: Installed / not activated               
		Install Method: Manual
	videoprojecteurs     Name: Videoprojecteurs               Version: 0.0.1      State: Installed / not activated               
		Install Method: Manual

</pre></details>

### Anything else?

Operating system
Windows

GLPI Agent version
1.5

**Comment by stonebuzz** [comment]
Hi @jbesnard 

Can you provide related inventory file ? 

Best regards

**Comment by jbesnard** [comment]
Hi @stonebuzz 

here is a xml file 
[inv1.zip](https://github.com/glpi-project/glpi/files/12033180/inv1.zip)

Thanks for help

**Comment by trasher** [comment]
Provided file can be imported without any issues on my instance. Is the computer imported into GLPI? I suspect one of your rules refuse the inventory, try with default rules.

**Comment by stonebuzz** [comment]
@jbesnard have you some dictionary rules ?

**Comment by jbesnard** [comment]
Hi, I don't try to import from XML files, when I try, I have this error message : 

Enregistrement impossible pour Numéro de série = BH8LMF2
Un autre élément existe
[[DP-ICI](http://srv-asap10-test.mydom.fr/front/computer.form.php?id=1943) - ID : 1943 - Numéro de série : BH8LMF2 - Entité : MYDOM]

I don't have dictionary rules, all import rules are default.
