### ISSUE TITLE
10.0.9 : Slown Marketplace ( Random)

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#15219]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Hello,

I randomly get this error when I click on Marketplace.  It works randomly.
Bug random of marketplace ?

### Relevant log output

```shell
[2023-07-13 15:12:17] glpiphplog.WARNING:   *** PHP User Warning (512): Ã‰chec de connexion. Si vous utilisez un proxy, merci de le configurer. (Resolving timed out after 5516 milliseconds) in /var/www/html/glpi/src/Toolbox.php at line 1526
  Backtrace :
  src/Toolbox.php:1526                               trigger_error()
  src/GLPINetwork.php:320                            Toolbox::callCurl()
  src/Marketplace/View.php:148                       GLPINetwork::isServicesAvailable()
  src/Marketplace/View.php:218                       Glpi\Marketplace\View::checkRegistrationStatus()
  src/Marketplace/View.php:123                       Glpi\Marketplace\View::installed()
  src/CommonGLPI.php:691                             Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:117                           CommonGLPI::displayStandardTab()
```

### Steps To reproduce

1. Go to plugin Marketplace

**Comment by cedric-anne** [comment]
> ```
> Resolving timed out
> ```

Hi,

This kind of error is mainly due to DNS resolution issues. If there was a problem on GLPI marketplace servers, it has probably been already fixed. If problem persist, it may be related to a misconfiguration somewhere in your network infrastructure.
