### ISSUE TITLE
Update GLPI 9.5.13 to 10.0.0

### ISSUE THREAD

**Issue by hadesmaster81** [glpi-project/glpi#15221]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.13

### Bug description

During the update, we have the following error:

SQL Error "1054": Unknown column 'glpi_slas.slms_id' in 'on clause' in query "UPDATE `glpi_slas` INNER JOIN `glpi_slms` ON (`glpi_slas`.`slms_id` = `glpi_slms`.`id`) SET `glpi_slas`.`use_ticket_calendar` = `glpi_slms`.`use_ticket_calendar`, `glpi_slas`.`calendars_id` = `glpi_slms`.`calendars_id` WHERE (1)"

How can this error be resolved?

![image](https://github.com/glpi-project/glpi/assets/110244906/cdd7db2f-d9e2-4dad-869a-17473b803229)

### Relevant log output

```shell
cat debug-glpi/files/_log/sql-errors.log
[2023-07-13 18:22:22] glpisqllog.ERROR: DBmysql::query() in /var/www/debug-glpi/src/DBmysql.php line 370
  *** MySQL query error:
  SQL: UPDATE `glpi_slas` INNER JOIN `glpi_slms` ON (`glpi_slas`.`slms_id` = `glpi_slms`.`id`) SET `glpi_slas`.`use_ticket_calendar` = `glpi_slms`.`use_ticket_calendar`, `glpi_slas`.`calendars_id` = `glpi_slms`.`calendars_id` WHERE (1)
  Error: Unknown column 'glpi_slas.slms_id' in 'on clause'
  Backtrace :
  src/DBmysql.php:428
  src/Migration.php:832                              DBmysql->queryOrDie()
  install/migrations/update_9.5.x_to_10.0.0.php:93   Migration->executeMigration()
  src/Update.php:260                                 update95xto1000()
  install/update.php:139                             Update->doUpdates()
  install/update.php:248                             doUpdateDb()
  {"user":"@WikiDSI"}
```

### Page URL

http://debug-glpi.xxx.xx/install/update.php

**Comment by cedric-anne** [comment]
Hi,

Maybe something goes wrong in the past during the migration from GLPI 9.1.x to 9.2.0.

If your `glpi_slas` table has a `slas_id` field, rename this field to `slms_id` and it should fix the migration.

**Comment by hadesmaster81** [comment]
Good morning,

Thank you for your help, after the modification the update to version 10.0.9 works well. And, the integrity check allowed me to fix 5 or 6 indexes on primary keys with incorrect names.

In the process, I have another question regarding the implementation of CAS authentication. We implemented this one and it works, but after a while the page switching doesn't work anymore and we have the following errors:

[Tue Jul 18 08:54:30.277233 2023] [auth_cas:error] [pid 110222] [client XXX.XXX.XXX.XXX:58945] MOD_AUTH_CAS: INVALID_SERVICE, referer: https://XXXX.XXX.XXX/

To work around the problem, for example on a page "https://XXX.XXX.XXX.XXX/front/ticket.form.php?id=25611", we reload the following page "https://XXX.XXX. XXX.XXX/" then returning to the ticket it works again.

I was thinking for a token expiration issue, but even with a mod_auth_cas with the following configuration:

<IfModule mod_auth_cas.c>
# CASValidateServer On
# CASCertificatePath /etc/apache2/ssl/cas.pem
       CASCookiePath /var/cache/apache2/mod_auth_cas/
       CASLoginURL https://XXX.XXX.XXX/cas/login
       CASValidateURL https://XXX.XXX.XXX/cas/serviceValidate
       CASProxyValidateURL https://XXX.XXX.XXX/cas/proxyValidate
       CASTimeout 36000
       CASIdleTimeout 36000
       CASIdleTimeout 36000
       CASPreserveTicket On
       CASDebug On
</IfModule>

Do you have any ideas?

**Comment by cedric-anne** [comment]
Hi,

I never used CAS so I cannot help on this part. You should try to get help on community forums.

I close this issue as the initial problem has bene solved.
