### ISSUE TITLE
Virt host not cleaning up old linked vm's if no vm is running

### ISSUE THREAD

**Issue by liedekef** [glpi-project/glpi#15220]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI bugfix version of 30/6

### Bug description

If a virtualization host has vm's, these are correctly detected and shown in the "virtualization" tab of the asset.
However, if for some reason (all vm's down, migrated, ...) no vm's are running anymore on that host, the linked vm's stay as-is in the virtualization tab. It seems the case of 0 running vm's is not correctly taken into account here.

**Comment by stonebuzz** [comment]
hi @liedekef 

can you try this

https://github.com/glpi-project/inventory_format/pull/116

You need to adapt this file (under your GLPI)

```vendor/glpi-project/inventory_format/lib/php/Converter.php```

**Comment by liedekef** [comment]
I tried this change, but it doesn't seem to be effective.

**Comment by liedekef** [comment]
As super admin I can see the opcache stats like in your screenshot, but there's no "reset" button present on the pages ...
But I did: "php bin/console cache:clear" and "php bin/console system:clear_cache".
What is the correct way to provide the related inventory file?

**Comment by stonebuzz** [comment]
You need te enable débug mode.

Both are correct

**Comment by liedekef** [comment]
I cleared the opcache via a custom php script (that calls opcache_reset via the browser) and verified in glpi that the stats were ok.
I checked the json file for that asset (after running inventory again) and it doesn't contain any virtualmachines entry.

**Comment by liedekef** [comment]
btw: I can provide the generated json file (but in private due to sensitive content) => please provide me with a means to send it (email, upload private, ...)

**Comment by liedekef** [comment]
Some more info: when generating the xml on the client asset, copying it over and running vendor/glpi-project/inventory_format/bin/convert on it, the resulting json is ok. However: is it not so (or possible) that the newer glpi agent code (which I was forced to use to resolve other bugs, per the developer) is by default sending json and so this converter step is never executed?

**Comment by trasher** [comment]
Indeed GLPI Agent natively uses JSON, so convert code is not used.

**Comment by liedekef** [comment]
So, that means this issue is not resolved with the proposed changeset ...

**Comment by trasher** [comment]
Try #15380

**Comment by liedekef** [comment]
That seems better!

**Comment by cedric-anne** [comment]
Fixed by #15380.
