### ISSUE TITLE
Problem integrating GLPI API with Zabbix Server - ERROR_APP_TOKEN_PARAMETERS_MISSING

### ISSUE THREAD

**Issue by jwsanchez** [glpi-project/glpi#15222]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.9

### Bug description

ERROR In Zabbix: Sending failed: Error received from GLPi: missing parameter app_token; more info http://serverglpi/apirest.php/#ERROR_APP_TOKEN_PARAMETERS_MISSING

The configuration used: https://www.zabbix.com/la/integrations/glpi

**Comment by cconard96** [comment]
If the Zabbix integration is incapable of using an App Token from GLPI, do you have an API Client configured that has no app token associated that can validate the access for Zabbix?

**Comment by jwsanchez** [comment]
> If the Zabbix integration is incapable of using an App Token from GLPI, do you have an API Client configured that has no app token associated that can validate the access for Zabbix?

If the Zabbix integration is incapable of using an App Token from GLPI, do you have an API Client configured that has no app token associated that can validate the access for Zabbix?

**Comment by rallisf1** [comment]
Just make the app_token field in the GLPI API Client empty.
