### ISSUE TITLE
Assets -> Devices list slow

### ISSUE THREAD

**Issue by tilkov** [glpi-project/glpi#15241]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Listing Devices in Assets is slow, about 35 seconds to display them. All other categories are fast, except Global of course, since it includes Devices. Limit is set to 100.

Number of devices: 1924

### Relevant log output

```shell
Here's the query:

SELECT DISTINCT `glpi_peripherals`.`id` AS id, 'todor' AS currentuser, `glpi_peripherals`.`entities_id`, `glpi_peripherals`.`is_recursive`, `glpi_peripherals`.`name` AS `ITEM_Peripheral_1`, `glpi_peripherals`.`id` AS `ITEM_Peripheral_1_id`, `glpi_entities`.`completename` AS `ITEM_Peripheral_80`, `glpi_states`.`completename` AS `ITEM_Peripheral_31`, `glpi_manufacturers`.`name` AS `ITEM_Peripheral_23`, `glpi_peripheraltypes`.`name` AS `ITEM_Peripheral_4`, `glpi_peripheralmodels`.`name` AS `ITEM_Peripheral_40`, `glpi_peripherals`.`date_mod` AS `ITEM_Peripheral_19`, `glpi_peripherals`.`contact` AS `ITEM_Peripheral_7`, `glpi_users`.`name` AS `ITEM_Peripheral_70`, `glpi_users`.`realname` AS `ITEM_Peripheral_70_realname`, `glpi_users`.`id` AS `ITEM_Peripheral_70_id`, `glpi_users`.`firstname` AS `ITEM_Peripheral_70_firstname`, `glpi_peripherals`.`otherserial` AS `ITEM_Peripheral_6`, `glpi_peripherals`.`serial` AS `ITEM_Peripheral_5`, `glpi_locations`.`completename` AS `ITEM_Peripheral_3`, `glpi_peripherals`.`comment` AS `ITEM_Peripheral_16`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_infocoms`.`order_number`, '__NULL__'), '$#$',`glpi_infocoms`.`id`) ORDER BY `glpi_infocoms`.`id` SEPARATOR '$$##$$') AS `ITEM_Peripheral_26` FROM `glpi_peripherals`LEFT JOIN `glpi_entities` ON (`glpi_peripherals`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_states` ON (`glpi_peripherals`.`states_id` = `glpi_states`.`id` )LEFT JOIN `glpi_manufacturers` ON (`glpi_peripherals`.`manufacturers_id` = `glpi_manufacturers`.`id` )LEFT JOIN `glpi_peripheraltypes` ON (`glpi_peripherals`.`peripheraltypes_id` = `glpi_peripheraltypes`.`id` )LEFT JOIN `glpi_peripheralmodels` ON (`glpi_peripherals`.`peripheralmodels_id` = `glpi_peripheralmodels`.`id` )LEFT JOIN `glpi_users` ON (`glpi_peripherals`.`users_id` = `glpi_users`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_peripherals`.`locations_id` = `glpi_locations`.`id` ) LEFT JOIN `glpi_infocoms` ON (`glpi_peripherals`.`id` = `glpi_infocoms`.`items_id` AND `glpi_infocoms`.`itemtype` = 'Peripheral' ) WHERE `glpi_peripherals`.`is_deleted` = 0 AND `glpi_peripherals`.`is_template` = 0 AND ( `glpi_peripherals`.`entities_id` IN ('12', '18') OR (`glpi_peripherals`.`is_recursive`='1' AND `glpi_peripherals`.`entities_id` IN (0, 1)) ) GROUP BY `glpi_peripherals`.`id` ORDER BY `ITEM_Peripheral_1` ASC LIMIT 0, 100;
```

### Steps To reproduce

1. Go to Assets -> Devices
2. Observe delay of 35 seconds until the list appears.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.9 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux board 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64
PHP 7.4.3-4ubuntu2.19 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bcmath, bz2,
	calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, geoip, gettext, hash, iconv, imap, intl, json,
	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, readline, session,
	shmop, snmp, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zip, zlib)
Setup: max_execution_time="30" memory_limit="1024M" post_max_size="4098M" safe_mode="" session.save_handler="files"
	upload_max_filesize="4098M" 
Software: nginx/1.18.0
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.33-0ubuntu0.20.04.2
	Server SQL Mode: NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.3-4ubuntu2.19) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.33) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpi/marketplace/financialreports/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://dc.ad.videnov.bg', Port: '636', BaseDN: 'OU=VidenovUsers,DC=ad,DC=videnov,DC=bg', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'helpdesk', Use
		TLS: none
Server: 'mail.videnov.bg', Port: '389', BaseDN: 'ou=People,dc=videnov,dc=bg', Connection filter: none, RootDN:
		'cn=mail,dc=videnov,dc=bg', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (anonymous@mail.videnov.bg)

</pre></details><details><summary>Plugins list</summary><pre> 
	barcode              Name: Barcode                        Version: 2.6.0      State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Behaviours                     Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	positions            Name: Cartography                    Version: 6.0.2      State: Installed / not activated               
		Install Method: Marketplace
	dashboard            Name: Dashboard                      Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.2     State: Enabled                                 
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.3.0      State: Enabled                                 
		Install Method: Marketplace
	manageentities       Name: Entities portal                Version: 4.0.3      State: Installed / not activated               
		Install Method: Marketplace
	escalade             Name: Escalation                     Version: 2.9.1      State: Installed / not activated               
		Install Method: Marketplace
	financialreports     Name: Financial reports              Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 10.0.6+1.1 State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.2      State: Enabled                                 
		Install Method: Marketplace
	geninventorynumber   Name: Inventory number generation    Version: 2.8.3      State: Installed / not activated               
		Install Method: Marketplace
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.9.0      State: Installed / not activated               
		Install Method: Marketplace
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Installed / not activated               
		Install Method: Marketplace
	mydashboard          Name: My Dashboard                   Version: 2.1.5      State: Installed / not activated               
		Install Method: Marketplace
	genericobject        Name: Objects management             Version: 2.14.3     State: Enabled                                 
		Install Method: Marketplace
	order                Name: Orders management              Version: 2.10.4     State: Enabled                                 
		Install Method: Marketplace
	printercounters      Name: Printer counters               Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	releases             Name: Releases                       Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace
	reports              Name: Reports                        Version: 1.14.1     State: Installed / not activated               
		Install Method: Manual
	screenshot           Name: Screenshot                     Version: 2.0.2      State: Installed / not activated               
		Install Method: Marketplace
	stab                 Name: Split Timeline Action Buttons  Version: 1.1.2      State: Installed / not activated               
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.11.5     State: Installed / not activated               
		Install Method: Marketplace
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Installed / not activated               
		Install Method: Marketplace
	timelineticket       Name: Timeline of tickets            Version: 10.0+1.1   State: Installed / not activated               
		Install Method: Marketplace
	treeview             Name: Tree view                      Version: 1.10.1     State: Installed / not activated               
		Install Method: Marketplace
	typology             Name: Typologies                     Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Installed / not activated               
		Install Method: Marketplace
	room                 Name: Зали                           Version: 3.1.3      State: Enabled                               
		  Install Method: Manual

</pre></details>

### Anything else?

EXPLAIN ANALYZE of the query

| -> Limit: 100 row(s)  (actual time=21044..21044 rows=100 loops=1)
    -> Sort row IDs: glpi_peripherals.`name`, limit input to 100 row(s) per chunk  (actual time=21044..21044 rows=100 loops=1)
        -> Table scan on <temporary>  (cost=2.93e+6..2.94e+6 rows=864703) (actual time=21038..21038 rows=1924 loops=1)
            -> Temporary table  (cost=2.93e+6..2.93e+6 rows=864703) (actual time=21038..21038 rows=1924 loops=1)
                -> Group aggregate: group_concat(distinct concat(ifnull(glpi_infocoms.order_number,'__NULL__'),'$#$',glpi_infocoms.id) order by glpi_infocoms.id ASC separator '$$##$$')  (cost=2.85e+6 rows=864703) (actual time=0.921..21027 rows=1924 loops=1)
                    -> Nested loop left join  (cost=2.76e+6 rows=864703) (actual time=0.866..21016 rows=1924 loops=1)
                        -> Nested loop left join  (cost=2.26e+6 rows=864703) (actual time=0.841..20998 rows=1924 loops=1)
                            -> Nested loop left join  (cost=1.95e+6 rows=864703) (actual time=0.83..20993 rows=1924 loops=1)
                                -> Nested loop left join  (cost=1.65e+6 rows=864703) (actual time=0.813..20985 rows=1924 loops=1)
                                    -> Nested loop left join  (cost=1.35e+6 rows=864703) (actual time=0.804..20982 rows=1924 loops=1)
                                        -> Nested loop left join  (cost=1.04e+6 rows=864703) (actual time=0.797..20979 rows=1924 loops=1)
                                            -> Nested loop left join  (cost=742257 rows=864703) (actual time=0.779..20976 rows=1924 loops=1)
                                                -> Nested loop left join  (cost=439611 rows=864703) (actual time=0.755..20973 rows=1924 loops=1)
                                                    -> Filter: ((glpi_peripherals.is_deleted = 0) and ((glpi_peripherals.entities_id in ('12','18')) or ((glpi_peripherals.is_recursive = 1) and (glpi_peripherals.entities_id in (0,1)))))  (cost=136966 rows=864703) (actual time=0.736..20972 rows=1924 loops=1)
                                                        -> Index lookup on glpi_peripherals using is_template (is_template=0)  (cost=136966 rows=3.46e+6) (actual time=0.0269..20018 rows=6.97e+6 loops=1)
                                                    -> Single-row index lookup on glpi_entities using PRIMARY (id=glpi_peripherals.entities_id)  (cost=0.25 rows=1) (actual time=457e-6..479e-6 rows=1 loops=1924)
                                                -> Single-row index lookup on glpi_states using PRIMARY (id=glpi_peripherals.states_id)  (cost=0.25 rows=1) (actual time=0.00128..0.00131 rows=1 loops=1924)
                                            -> Single-row index lookup on glpi_manufacturers using PRIMARY (id=glpi_peripherals.manufacturers_id)  (cost=0.25 rows=1) (actual time=0.00133..0.00134 rows=0.39 loops=1924)
                                        -> Single-row index lookup on glpi_peripheraltypes using PRIMARY (id=glpi_peripherals.peripheraltypes_id)  (cost=0.25 rows=1) (actual time=0.00109..0.00111 rows=1 loops=1924)
                                    -> Single-row index lookup on glpi_peripheralmodels using PRIMARY (id=glpi_peripherals.peripheralmodels_id)  (cost=0.25 rows=1) (actual time=0.00126..0.00128 rows=0.992 loops=1924)
                                -> Single-row index lookup on glpi_users using PRIMARY (id=glpi_peripherals.users_id)  (cost=0.25 rows=1) (actual time=0.00418..0.0042 rows=0.78 loops=1924)
                            -> Single-row index lookup on glpi_locations using PRIMARY (id=glpi_peripherals.locations_id)  (cost=0.25 rows=1) (actual time=0.00253..0.00254 rows=0.631 loops=1924)
                        -> Single-row index lookup on glpi_infocoms using unicity (itemtype='Peripheral', items_id=glpi_peripherals.id)  (cost=0.483 rows=1) (actual time=0.00874..0.00877 rows=1 loops=1924)

![glpi-mysql-an](https://github.com/glpi-project/glpi/assets/546928/a4957f69-00d8-4284-af9a-9be6320dee24)

Edit: added Mysql Workbench Execution Plan analyzer

**Comment by cedric-anne** [comment]
Hi,

I am not sure how to read the EXPLAIN analyze, but as far as I understand, the performance issue here is due to display of "infocom order number" field. Can you try to remove this field from the displayed page to confirm this?
