### ISSUE TITLE
Bug with "Enable high contrast" 

### ISSUE THREAD

**Issue by PierreTeclib** [glpi-project/glpi#1524]
Hi,
When "Enable high contrast" is activated we have a display bug. See attahment.

Thks.

GLPI version:  https://github.com/glpi-project/glpi/commit/03ef69fec33d81c4214c61f7c65347698c0f4277

![image001](https://cloud.githubusercontent.com/assets/6872020/21683002/c26a65fa-d357-11e6-9ede-e2f1eab91330.png)

**Comment by trasher** [comment]
Does the bug happens on 9.1?

**Comment by PierreTeclib** [comment]
I don't know.

**Comment by trasher** [comment]
The problem is that rule `.tab_actors, .actor-head, .actor-content { margin: 0; }` from the high contrast stylesheet overrides the `.tab_cadre_fixe, .tab_cadre_fixehov { margin: 0px auto 5px auto; }` one.

I confirm the issue already exists in 9.1.

**Comment by PierreTeclib** [comment]
OK. Sorry I've migrated directly from 0.84 to 9.1.1 so I haven't tested in 9.1 :)
