### ISSUE TITLE
Dropdown of actors infinitely loading

### ISSUE THREAD

**Issue by verdanatech-marcio** [glpi-project/glpi#15256]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

![image](https://github.com/glpi-project/glpi/assets/80538863/e91bfb35-a684-42be-b136-dc9baf674245)
The actors dropdown has infinite loading and the request returns that there are no more users available.

### Page URL

http://127.0.0.1/front/ticket.form.php

### Steps To reproduce

1- Open page of new ticket
2- Navigate between the actors of the call

### Your GLPI setup information

PHP  8.2.7
GLPI - 10.0.9

**Comment by cconard96** [comment]
Can you test the fix in #15257?

**Comment by cedric-anne** [comment]
Fixed by #15257.
