### ISSUE TITLE
GLPI 10.0.6 to 10.0.9 - Small improvment on login page

### ISSUE THREAD

**Issue by Exitneox** [glpi-project/glpi#15258]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6, 10.0.8 or 10.0.9

### Steps To reproduce

On login screen, when you activate the right columns (in my case an SSO provider), and/or "Text in the login box" and/or Anonymous FAQ they as stacked in the right columns and it is not really "nice to see"

![20230720_glpi_original_login_page_2columns](https://github.com/glpi-project/glpi/assets/56884956/cb9d10db-f5a1-49d4-bad5-57b1231ab241)

My small improvment is by reordering the html code inside the login.html.twig file (maybe there is a better place to do the customization) to put "Text in the Login Box" on top of the two columns, and FAQ link at bottom, make it smoother to read
![20230720_glpi_new_login_page_2columns](https://github.com/glpi-project/glpi/assets/56884956/f117727a-422e-43cb-af61-446f5df5e6c7)

### Your GLPI setup information

GLPI 10.0.6 in production
GLPI 10.0.8 in preprod
GLPI 10.0.9 in dev

### Anything else?
My diff file

[templates_pages_login.html.twig.diff.txt](https://github.com/glpi-project/glpi/files/12104771/templates_pages_login.html.twig.diff.txt)

**Comment by cedric-anne** [comment]
@Exitneox 

Could you open a pull request with your changes?

**Comment by cedric-anne** [comment]
ping @Exitneox

**Comment by Exitneox** [comment]
Sorry did not see the previous message.
 I would be pleased to do the pull request if my change is relevant.

Regards

Envoyé à partir de Outlook pour Android<https://aka.ms/AAb9ysg>

________________________________
De : Cédric Anne ***@***.***>
Envoyé : mercredi, août 2, 2023 3:39:55 PM
À : glpi-project/glpi ***@***.***>
Cc : Neox ***@***.***>; Mention ***@***.***>
Objet : Re: [glpi-project/glpi] GLPI 10.0.6 to 10.0.9 - Small improvment on login page (Issue #15258)


ping @Exitneox<https://github.com/Exitneox>

**Comment by Exitneox** [comment]
I gave a try to create a pull request, but it says `Pull request creation failed. Validation failed: must be a collaborator `
if the diff file is enough feel free to take it to do the pull request for yourself, i don't ask credit for such small change ;)
