### ISSUE TITLE
GLPI ticket status is not showing in dashboard

### ISSUE THREAD

**Issue by zakirpcs** [glpi-project/glpi#15267]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

After update glpi version from 9.3.1 to 10.0.9 i am getting below error in dashboard.

"Map rendering error! ticket_status" 

For better understanding screenshot has been attached.
![Screenshot 2023-07-21 220847](https://github.com/glpi-project/glpi/assets/39796037/90ad40c4-e5d4-49e3-a941-98564f8ef31e)

In this regarding, could anyone please help me to resolve the issue?

**Comment by cconard96** [comment]
Please copy and paste any relevant log output. Find them in `*-error.log` files under `glpi/files/_log/`.

**Comment by zakirpcs** [comment]
Did not get anything related to ticket_status in below location

[root@supportinfo _log]# pwd
/var/www/html/glpi/files/_log
[root@supportinfo _log]# grep -lnr "ticket_status"

In which log should i check from below files:
[root@supportinfo _log]# ls -lrt *error*
-rw-r--r-- 1 apache apache      6427 Jun 28 15:17 access-errors.log
-rw-r--r-- 1 apache apache  15948225 Jul 20 07:50 sql-errors.log
-rw-r--r-- 1 apache apache  13368875 Jul 20 08:52 mail-error.log
-rw-r--r-- 1 apache apache 785556678 Jul 21 12:48 php-errors.log

**Comment by cedric-anne** [comment]
Hi,

Please check if some logs are added to `php-errors.log` when the dashboard is generated. Related log will likely not contains `ticket_status`, so a `tail` command is probably more appropriate than a `grep` command here.

**Comment by zakirpcs** [comment]
I am getting below error in php-errors.log while loading dashboard.

[2023-07-24 10:05:51] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Glpi\Dashboard\Provider::formatMonthyearDates(): Argument #1 ($monthyear) must be of type string, null given, called in /var/www/html/glpi/src/Dashboard/Provider.php on line 1311 in /var/www/html/glpi/src/Dashboard/Provider.php at line 1635
  Backtrace :
  src/Dashboard/Provider.php:1311                    Glpi\Dashboard\Provider::formatMonthyearDates()
  :                                                  Glpi\Dashboard\Provider::getTicketsStatus()
  src/Dashboard/Grid.php:934                         call_user_func_array()
  ajax/dashboard.php:192                             Glpi\Dashboard\Grid->getCardHtml()

**Comment by zakirpcs** [comment]
Issue has been identified. I found 2 record where "set date" field value was empty. That is why ticket status graph was not generated.

**Comment by pschivo** [comment]
> Issue has been identified. I found 2 record where "set date" field value was empty. That is why ticket status graph was not generated.

Hi there, sorry for asking these after a long time but this is happening to me and i can't find any "set date" field inside the php file or database. Would you mind telling me your detailed fix?

Thanks in advance
