### ISSUE TITLE
Regex matching impossible against a text with some specific characters

### ISSUE THREAD

**Issue by keguira** [glpi-project/glpi#15266]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I'm trying to create a rule with a regex to retrieve informations about a software (name and version from the original name) but it's impossible to create a match because some characters are, i think, escaped in a way making it impossible.

Up until now, i identified these 3 characters : < > /

 

### Steps To reproduce

1. create a dictionnary rule for manufacturer or software
2. add a criteria "regular expression matches" with `/^foo-bar..$/`
3. test the criteria against this string : `foo-bar##` -> it will match
4. test the criteria against this string : `foo-bar@@` -> it will match
5. test the criteria against this string : `foo-bar//` -> it will match
6. test the criteria against this string : `foo-bar\\` -> it will **not** match.
7. test the criteria against this string : `foo-bar\\\\` -> it will match because of the escaping and in preview, this will be displayed as `foo-bar\\`.
8. test the criteria against this string : `foo-bar<<` -> it will **not** match
9. test the criteria against this string : `foo-bar>>` -> it will **not** match

I my opinion, use cases 6, 8 and 9 should match. use case 7 should not match

**Comment by keguira** [comment]
More information and another example : `Skype™ 7.4` ( no comment on this version, i have some quite old assets 😄 )

None of these regex works to match this name :
* `/(Skype™) [\d\.]+/`
* `/(Skype[™]) [\d\.]+/`
* `/(Skype\u2122) [\d\.]+/`
* `/(Skype.) [\d\.]+/`

**Comment by cedric-anne** [comment]
Hi,

For the `<`, `>`, `&` and `\\` chars, it may be due to problems with GLPI sanitization logic, but I do not have time to validate it now. Maybe it is fixed on main branch, thanks to #14302 (cannot be used in production yet as it requires all HTML generated code to be reviewed). 

For the `™` char, it is a unicode char, so you probably have to use the `u` modifier (`/(Skype™) [\d\.]+/u`).

**Comment by keguira** [comment]
> For the `™` char, it is a unicode char, so you probably have to use the `u` modifier (`/(Skype™) [\d\.]+/u`).

I confirm, both of these syntax are working :
* `/(Skype™) [\d\.]+/u`
* `/(Skype\x{2122}) [\d\.]+/u`

I didn't think to add the modifier as I saw the `i` modifier forced in the source code. Sorry. 
So this use case is not linked to this issue. I'll try to test the 10.1 too

**Comment by cedric-anne** [comment]
@keguira 

#15559 should fix issues with the `<`, `>`, `&` and `\` chars.

**Comment by keguira** [comment]
I was finally able to test the fix with 10.0.10 : it's working well.

**Comment by Lyx09** [comment]
Hello,

Testing with 10.0.12, `/^.$/` does not seem to match `\` nor `\\` but it does match `\i` (or any other character after the '\')
Also `/^.$/` does not seem to match `&`

Can anyone confirm they have a similar behavior ?

**Comment by Lyx09** [comment]
My bad I may have read too quickly. Thanks for the fix

Regards,
