### ISSUE TITLE
Contracts - Missing update field in actions

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi#15260]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

I want to update the "reconduction" field of contracts using actions. but i haven't the field :)

![image](https://github.com/glpi-project/glpi/assets/6053818/f517dea9-c42a-433f-8675-7172869db513)

### Steps To reproduce

1. Go to contracts
2. select one, then click Actions
3. select update
4. Reconduction isn't in the field list :)

### Anything else?

Impossible to import the field with data injection plugin, I don't know if it's related

**Comment by cedric-anne** [comment]
Hi,

#15347 will permit to unlock massive update of this field.

**Comment by TheRoby** [comment]
Sorry for the delay, holidays... ;)
It works, thank you :)
