### ISSUE TITLE
Spelling mistake "mention"

### ISSUE THREAD

**Issue by derpedda** [glpi-project/glpi#15278]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.5 / 10.0.9

### Bug description

Hey all,

when configuring the notifications i stumbled across a typo that takes its way through the templates and through the code naming as well. 
I looked at the notifications for the "mentioned" event and after a short lookaround in the code i saw that it is spelled everywhere as "mentionned" and that this happens to bee around for a pretty long time already. The correct english form should be "mentioned" with only one n, maybe that is fixable in oe of the future versions, as only changing the translation is not sufficient I would say.

### Steps To reproduce

1. Mention someone in a ticket or followup
2. Receive a mail with the typo in it

### Anything else?

Keep up the good work, happy with GLPI for plenty of years now.

**Comment by cedric-anne** [comment]
Fixed by #15281
