### ISSUE TITLE
Software dictionary : unnecessary duplication

### ISSUE THREAD

**Issue by keguira** [glpi-project/glpi#15289]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

I'm trying to use the dictionnary rules to group each same software with it's versions.

If it's working well when "recalculate", when a computer is inventoried, it creates a new entry of the software with my rules instead of linking it to the existing one.

For example, let's take a software named `foo`.

* Names are with this pattern `<software name> <version as x.y.z>` such as `foo 1.2` or `foo 1.3.1`.
* Version is also correctly filled automatically without any rules.

-> Result is I have as many software as versions in GLPI

I've created a rule with a regular expression matching `/^(foo) ([\d\.]+)$/`
The corresponding action is to apply the value of the regular expression `#0`.

After replaying the rules for the editor, i have one `foo` with all versions correctly filled (sourced from the agent).

After some time, a new `foo` is generated with some versions and computers move from one `foo` to another. I've tried to update my regex for `/^(foo)(?: ([\d\.]+))?$/` to also match `foo` just in case but it's not working properly.

 

### Steps To reproduce

I noticed this with multiple softwares but common ones like xnview, filezilla client and some are impacted too.

### Your GLPI setup information

<details><summary>Plugins list</summary><pre> 
	advanceddashboard    Name: advanceddashboard              Version: 1.5.1      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertes                        Version: 1.12.1     State: Enabled                                 
		Install Method: Marketplace
	branding             Name: Branding                       Version: 1.4.0      State: Enabled                                 
		Install Method: Marketplace
	timelineticket       Name: Chronologie des tickets        Version: 10.0+1.1   State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	escalade             Name: Escalades                      Version: 2.9.0      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	ldaptools            Name: Outils LDAP                    Version: 0.0.3      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace
	localeoverride       Name: Renommer les chaînes de GLPI   Version: 1.1.7      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

### Anything else?

I use some plugins : they are listed in _setup informations_.

I'm trying to do more tests to see if it's a pattern issue, a name issue (order ?) or something else... I'll post more info if i find one

Also, i've found an old staled issue with simingly the same behavior : #10836

**Comment by trasher** [comment]
Please try with latest stable release.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by keguira** [comment]
Sorry, it took some time for us to update. 
We are currently on 10.0.9 with agent 1.5. 
I do not see this behavior anymore.
