### ISSUE TITLE
Notification settings page not working

### ISSUE THREAD

**Issue by blackxthink** [glpi-project/glpi#15295]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.9

### Bug description

The page "Configuration -> Notifications" gives this error in debug mode:

`Uncaught Exception Error: Class 'NotificationSettingConfig' not found in /home/glpi/public_html/front/setup.notification.php at line 51`

### Page URL

xxx/front/setup.notification.php

### Steps To reproduce

Configuration -> Notifications

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce. Is the `src/NotificationSettingConfig.php` file present in your GLPI installation? Did you patched your GLPI instance?

**Comment by blackxthink** [comment]
> Hi,
> 
> I cannot reproduce. Is the `src/NotificationSettingConfig.php` file present in your GLPI installation? Did you patched your GLPI instance?

Oh yeah, now it works.
When I updated, some files transfered but were in reality empty.

I fixed it by reuploading the file.

Thank you !
