### ISSUE TITLE
[0.90] javascript search in textfields disappear

### ISSUE THREAD

**Issue by xsgoodbox** [glpi-project/glpi#153]
Hello,

It seems to be a bug, the search feature in textfields disappears when editing entries, that works when hitting a key before ~1s.

I'm using firefox 38.3

**Comment by yllen** [comment]
can you give an example?

**Comment by xsgoodbox** [comment]
Sure, in all forms with researchable dropdowns, the search field disappears immediately, for example the location field in the computer form:

https://glpi/glpi09/front/computer.form.php

**Comment by yllen** [comment]
In Setup > Global, what is the value for "Don't show search engine in dropdowns if the number of items is less than"?
And how many items have you in location dropdown?

**Comment by xsgoodbox** [comment]
It was 50, then I put 4, now it's working!

Thanks you.
