### ISSUE TITLE
Ticket Creation - Submit an unknown email requester automacally select an entity which is not the desired behaviour

### ISSUE THREAD

**Issue by Dual-Boot** [glpi-project/glpi#15305]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

  Hello GLPI Team,

 I have met a curious behaviour with ticket creation in the web frontend.
 I can reproduce it on my server each time by following the steps : 
* create new ticket
* fill in the form
* set up the requester with an unknown email
If the email requester is known by GLPI, entity field remains the same I filled it earlier. But with an unknown email address GLPI change the entity. And whatever is the unknown address, GLPI always changes the entity and I can not change it until I remove the unknown email address.

 The entity that GLPI choose is always the same entity and it is not a default entity, it is sub-sub-entity.
I have checked everything I could with or without debug mode : 
* disabled all the plugin
* check business rules
* check default Ticket Template
* check the log (Apache and GLPI, and no error)
* I add a user (email address) to the entity which automacally spawn in the form without any success to check the user assignment

 Maybe I missed something ? Where can I search to find a solution ?
 Thank you for helping.

### Steps To reproduce

* create new ticket
* fill in the form
* set up the requester with an unknown email
If the email requester is known by GLPI, entity field remains the same I filled it earlier. But with an unknown email address GLPI change the entity. And whatever is the unknown address, GLPI always changes the entity and I can not change it until I remove the unknown email address.

### Your GLPI setup information

GLPI 10.0.9 ( => /var/www/scl-glpi01)
Installation mode: TARBALL
Current language:fr_FR

Operating system: Linux scl-glpi01 5.4.0-155-generic #172-Ubuntu SMP Fri Jul 7 16:10:02 UTC 2023 x86_64
PHP 7.4.3-4ubuntu2.19 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
        bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
        mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
        sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
        upload_max_filesize="10M"
Software: Apache ()
        Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Server Software: Ubuntu 20.04
        Server Version: 10.3.38-MariaDB-0ubuntu0.20.04.1
        Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
        Parameters: adminsc@localhost/glpi_database
        Host info: Localhost via UNIX socket

PHP version (7.4.3-4ubuntu2.19) is supported.PHP version (7.4.3-4ubuntu2.19) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.38) is supported.Database engine version (10.3.38) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/scl-glpi01/files/_cache has been validated. Write access to /var/www/scl-glpi01/config has been validated. Write access to /var/www/scl-glpi01/files/_cron has been validated. Write access to /var/www/scl-glpi01/files has been validated. Write access to /var/www/scl-glpi01/files/_dumps has been validated. Write access to /var/www/scl-glpi01/files/_graphs has been validated. Write access to /var/www/scl-glpi01/files/_lock has been validated. Write access to /var/www/scl-glpi01/files/_pictures has been validated. Write access to /var/www/scl-glpi01/files/_plugins has been validated. Write access to /var/www/scl-glpi01/files/_rss has been validated. Write access to /var/www/scl-glpi01/files/_sessions has been validated. Write access to /var/www/scl-glpi01/files/_tmp has been validated. Write access to /var/www/scl-glpi01/files/_uploads has been validated.Write access to /var/www/scl-glpi01/files/_cache has been validated.
Write access to /var/www/scl-glpi01/config has been validated.
Write access to /var/www/scl-glpi01/files/_cron has been validated.
Write access to /var/www/scl-glpi01/files has been validated.
Write access to /var/www/scl-glpi01/files/_dumps has been validated.
Write access to /var/www/scl-glpi01/files/_graphs has been validated.
Write access to /var/www/scl-glpi01/files/_lock has been validated.
Write access to /var/www/scl-glpi01/files/_pictures has been validated.
Write access to /var/www/scl-glpi01/files/_plugins has been validated.
Write access to /var/www/scl-glpi01/files/_rss has been validated.
Write access to /var/www/scl-glpi01/files/_sessions has been validated.
Write access to /var/www/scl-glpi01/files/_tmp has been validated.
Write access to /var/www/scl-glpi01/files/_uploads has been validated.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/scl-glpi01/marketplace has been validated.Write access to /var/www/scl-glpi01/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                  		Install Method: Marketplace 	datainjection        Name: Data Injection                 Version: 2.13.2     State: Enabled                                  		Install Method: Marketplace 	escalade             Name: Escalades                      Version: 2.9.2      State: Enabled                                  		Install Method: Marketplace 	glpiinventory        Name: GLPI Inventory                 Version: 1.2.3      State: Enabled                                  		Install Method: Marketplace 	itilcategorygroups   Name: Helpdesk catégories groupes    Version: 2.5.1      State: Enabled                                  		Install Method: Marketplace 	moreticket           Name: More ticket                    Version: 1.7.3      State: Enabled                                  		Install Method: Marketplace 	oauthimap            Name: Oauth IMAP                     Version: 1.4.1      State: Enabled                                  		Install Method: Marketplace 	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                  		Install Method: Marketplace 	vip                  Name: VIP                            Version: 1.8.2      State: Enabled                                  		Install Method: Marketplace 	webhook              Name: Webhooks                       Version: 1.0.14     State: Installed / not activated                		Install Method: Marketplace

### Anything else?

ras

**Comment by cconard96** [comment]
I cannot recreate the issue. The entity remains the same as the one I choose (or the default root entity) even when I add an anonymous requestor to the ticket.

**Comment by Dual-Boot** [comment]
Hello,
Thank you to try to reproduce it.
Is there a way to know which trigger is used when the requester is added ?

  Regards,

**Comment by cedric-anne** [comment]
Hi,

Could you test #15626 ?

**Comment by berilslv** [comment]
Hi guys,
I'm facing same issue. When support is adding custom email at requester field example@example.org (default: filled with ticket creator) , after selecting entity is changed to other.
Tried: change template,create new ticket template.
This problem occurs only to users which are not super-users. 
Super-user doenst have this issue.

**Comment by trasher** [comment]
You should first try with latest stable release, and open a new issue with all required information if there is a real bug. Current issue has been closed for months.
