### ISSUE TITLE
Mailgate action won't trigger with CLI and errors on Unable to connect to 365...

### ISSUE THREAD

**Issue by jfelixoptimiumnc** [glpi-project/glpi#15306]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Hi,

Mailgate action won't trigger with CLI and errors on Unable to connect to 365...
Worked before upgrade from 10.0.6

$ php www/parcs/front/cron.php
Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot connect to host; error = stream_socket_client(): Unable to connect to ssl://outlook.office365.com:993 (Connection refused) (errno = 0 ) in ***GLPIPATH***/vendor/laminas/laminas-mail/src/Protocol/ProtocolTrait.php at line 100

Thx for your help.

**Comment by cedric-anne** [comment]
Hi,

Do you have anything in GLPI logs that is added when your cron task is executed? Can you try to input the password again in your collector form and test again? Maybe the GLPI encryption key was regenerated during update as it was not copied from previous installation. In such case, imap password cannot be decrypted and is corrupted.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by jfelixoptimiumnc** [comment]
Hi,

Sorry for late response, was on vacations.

I've investigated a little more and CLI doesn't work anymore for any actions after upgrade to 10.0.9, I have to stay on GLPI mode.

Logs don't help.

Hope you can help.

Best,

Jerome
