### ISSUE TITLE
Minify ressources

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1537]
We provide some ressources which aren't minified (css, some js).

We could use a minify tool in order to reduce delivered files size (quicker load for user).
The drawback is we need to generate the minified file each time we change it on dev (is it frequent ?)

Regards

**Comment by tomolimo** [comment]
Could it be possible to provide both versions? 
And to output the non-minify version when in debug?

**Comment by trasher** [comment]
+1 for the proposition; this is already what we do for some plugins (see http://glpi-plugins.readthedocs.io/en/latest/empty/index.html#minifying-css-ans-js); and I have that in mind for a while for the core :)

Some points:
1. this must be a release process; no minified files should be stored in the repository;
2. a command would be provided for git users to minify if they want to;
3. if minified files does not exists or if we're in debug mode; we must load not minified versions.

That mainly concerns core's JS and CSS files; as libs often provide an already minified version (and those ones does not change generally).
