### ISSUE TITLE
Failed to perform bulk update for additional fields

### ISSUE THREAD

**Issue by joaoangelozem** [glpi-project/glpi#15370]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

After the update from version 10.0.2 to 10.0.8 and now to 10.0.9 the mass update functionality for additional fields is not functional.
![1](https://github.com/glpi-project/glpi/assets/73944931/e48f6330-9a96-40a4-a28e-5c09e45de5e6)

### Relevant log output

```shell
There is no error record in the log
```

### Steps To reproduce

1) Mark 1 or more calls on the Assistance -> Calls screen
2) Click on "Actions"
3) Choose "Update" option from dropdown menu
4) Choose any field that has been created by the "Additional Fields" plugin

### Your GLPI setup information

GLPI 10.0.9 ( => /var/www/sekurglpi)
Installation mode: TARBALL
Current language:pt_BR

Operating system: Linux linux02 4.19.0-24-cloud-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64
PHP 8.1.18 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="256M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache (Apache Server at helpdesk.sekurtecnologia.com.br Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.8-MariaDB-1:10.7.8+maria~deb10
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi_sekur
	Host info: Localhost via UNIX socket
	
PHP version (8.1.18) is supported.PHP version (8.1.18) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.8) is supported.Database engine version (10.7.8) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/sekurglpi/files/_cache has been validated. Write access to /var/www/sekurglpi/config has been validated. Write access to /var/www/sekurglpi/files/_cron has been validated. Write access to /var/www/sekurglpi/files has been validated. Write access to /var/www/sekurglpi/files/_dumps has been validated. Write access to /var/www/sekurglpi/files/_graphs has been validated. Write access to /var/www/sekurglpi/files/_lock has been validated. Write access to /var/www/sekurglpi/files/_pictures has been validated. Write access to /var/www/sekurglpi/files/_plugins has been validated. Write access to /var/www/sekurglpi/files/_rss has been validated. Write access to /var/www/sekurglpi/files/_sessions has been validated. Write access to /var/www/sekurglpi/files/_tmp has been validated. Write access to /var/www/sekurglpi/files/_uploads has been validated.Write access to /var/www/sekurglpi/files/_cache has been validated.
Write access to /var/www/sekurglpi/config has been validated.
Write access to /var/www/sekurglpi/files/_cron has been validated.
Write access to /var/www/sekurglpi/files has been validated.
Write access to /var/www/sekurglpi/files/_dumps has been validated.
Write access to /var/www/sekurglpi/files/_graphs has been validated.
Write access to /var/www/sekurglpi/files/_lock has been validated.
Write access to /var/www/sekurglpi/files/_pictures has been validated.
Write access to /var/www/sekurglpi/files/_plugins has been validated.
Write access to /var/www/sekurglpi/files/_rss has been validated.
Write access to /var/www/sekurglpi/files/_sessions has been validated.
Write access to /var/www/sekurglpi/files/_tmp has been validated.
Write access to /var/www/sekurglpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/sekurglpi": ‣ "/var/www/sekurglpi/files" ("GLPI_VAR_DIR") ‣ "/var/www/sekurglpi/config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if your web server root directory is "/var/www/sekurglpi/public".The following directories should be placed outside "/var/www/sekurglpi":
‣ "/var/www/sekurglpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/sekurglpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/sekurglpi/public".
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/sekurglpi/marketplace has been validated.Write access to /var/www/sekurglpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cconard96** [comment]
I cannot recreate the issue.

**Comment by trasher** [comment]
This seems rather a plugin issue than a core one anyways. Please report plugin side, with all information to reproduce.
