### ISSUE TITLE
Solve_delay_stat not running with API resolution

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#15378]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.9

### Bug description

If you generate an incident ticket from Zabbix, when Zabbix sends the solution, the "Solve_delay_Stat" field is not updated in the database, and the solution date is also not updated in GLPI.
![image](https://github.com/glpi-project/glpi/assets/56876938/18a64d9e-9fab-4b9b-b8db-2452b3aa2485)
![image](https://github.com/glpi-project/glpi/assets/56876938/ae6a25d9-0cc3-488f-b5c8-01a7de23b56e)

**Comment by trasher** [comment]
This seems an issue from a plugin, please open bug on plugin repository.
