### ISSUE TITLE
Problem displaying profiles in authorization

### ISSUE THREAD

**Issue by virtazp** [glpi-project/glpi#15387]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

Good morning,

I have 2 profiles with the simplified interface (P1, P2) and 3 profiles with the standard interface. (P3, P4, Super-admin)

The P4 profile must be able to assign authorization to a user (P3).

Setting the P4 profile: Administration -> Profiles:
- Read: yes
- Update: no
- Create: no
- bleed: no

Impersonate user P4 ->

Administration -> Users -> User who already has a basic profile for the entity

Authorizations -> Add an authorization to a user -> profile list:
- P1, P2, P4
P3 is not present.

If I change the P4 profile setting:
- Read: yes
- Update: no
- Create: yes
- bleed: no

Authorizations -> Add an authorization to a user -> profile list:
- P1, P2, P3, P4, super admin

Why does P3 and super-admin appear when I check "Create"?

### Relevant log output

```shell
none
```

### Page URL

https://glpi/front/user.form.php?id=34

### Steps To reproduce

See Bug description

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.7 ( => /var/www/xxxxxx)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux SMD11-DSI-DMZ 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 8.2.5 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: nginx/1.18.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.18-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxxxxx
	Host info: Localhost via UNIX socket
	
PHP version (8.2.5) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.18) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/xxxxxx/files/_cache has been validated.
Write access to /var/www/xxxxxx/config has been validated.
Write access to /var/www/xxxxxx/files/_cron has been validated.
Write access to /var/www/xxxxxx/files has been validated.
Write access to /var/www/xxxxxx/files/_dumps has been validated.
Write access to /var/www/xxxxxx/files/_graphs has been validated.
Write access to /var/www/xxxxxx/files/_lock has been validated.
Write access to /var/www/xxxxxx/files/_pictures has been validated.
Write access to /var/www/xxxxxx/files/_plugins has been validated.
Write access to /var/www/xxxxxx/files/_rss has been validated.
Write access to /var/www/xxxxxx/files/_sessions has been validated.
Write access to /var/www/xxxxxx/files/_tmp has been validated.
Write access to /var/www/xxxxxx/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/xxxxxx/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/xxxxxx"
GLPI_CONFIG_DIR: "/var/www/xxxxxx/config"
GLPI_VAR_DIR: "/var/www/xxxxxx/files"
GLPI_MARKETPLACE_DIR: "/var/www/xxxxxx/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/xxxxxx/files"
GLPI_CACHE_DIR: "/var/www/xxxxxx/files/_cache"
GLPI_CRON_DIR: "/var/www/xxxxxx/files/_cron"
GLPI_DUMP_DIR: "/var/www/xxxxxx/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/xxxxxx/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/xxxxxx/files/_locales"
GLPI_LOCK_DIR: "/var/www/xxxxxx/files/_lock"
GLPI_LOG_DIR: "/var/www/xxxxxx/files/_log"
GLPI_PICTURE_DIR: "/var/www/xxxxxx/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/xxxxxx/files/_plugins"
GLPI_RSS_DIR: "/var/www/xxxxxx/files/_rss"
GLPI_SESSION_DIR: "/var/www/xxxxxx/files/_sessions"
GLPI_TMP_DIR: "/var/www/xxxxxx/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/xxxxxx/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/xxxxxx/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/xxxxxx/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/xxxxxx/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/xxxxxx/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/xxxxxx/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/xxxxxx/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/xxxxxx/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/xxxxxx/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/xxxxxx/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/xxxxxx/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/xxxxxx/vendor/sabre/http/lib)
sabre/uri in (/var/www/xxxxxx/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/xxxxxx/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/xxxxxx/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/xxxxxx/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/xxxxxx/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/xxxxxx/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/xxxxxx/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/xxxxxx/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/xxxxxx/vendor/symfony/console)
scssphp/scssphp in (/var/www/xxxxxx/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/xxxxxx/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/xxxxxx/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/xxxxxx/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/xxxxxx/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/xxxxxx/vendor/ramsey/uuid/src)
psr/log in (/var/www/xxxxxx/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/xxxxxx/vendor/psr/simple-cache/src)
psr/cache in (/var/www/xxxxxx/vendor/psr/cache/src)
league/csv in (/var/www/xxxxxx/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/xxxxxx/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/xxxxxx/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/xxxxxx/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/xxxxxx/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/xxxxxx/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/xxxxxx/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/xxxxxx/vendor/symfony/cache)
html2text/html2text in (/var/www/xxxxxx/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/xxxxxx/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/xxxxxx/vendor/symfony/dom-crawler)
twig/twig in (/var/www/xxxxxx/vendor/twig/twig/src)
twig/string-extra in (/var/www/xxxxxx/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/xxxxxx/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/xxxxxx/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/xxxxxx/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/xxxxxx/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (xxxxxx)

</pre></details><details><summary>Plugins list</summary><pre> 
	singlesignon         Name: Authentification unique        Version: 1.3.3      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
Profiles are visible if you have the right to create them, or if your profile has the same or more access than the profile(s) you are trying to view.
