### ISSUE TITLE
PostgreSQL support for GLPI

### ISSUE THREAD

**Issue by Operativ** [glpi-project/glpi#15381]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

### Bug description

Not a bug report.

It would be great to see GLPI move on to a more modern and robust database solution such as PostgreSQL, there have been some previous reports on implementing that as well.

### Your GLPI setup information

Example setup use case:

1. Servers on cloud provider (AWS, Azure...)
2. Using only PostgreSQL on the same provider
3. Containing GLPI within Docker or Kubernetes on the cloud provider, hosted independently or on a virtual server

### Anything else?

This would open up GLPI to a broader audience, and futureproof it as PostgreSQL becomes more and more relevant, some solutions even dropping MySQL and MariaDB support in favour of PostgreSQL. It is no wonder that less and less people maintain these database types and some infrastructure maintainers omit from hosting a separate DB for tools without PostgreSQL support.

**Comment by cedric-anne** [comment]
Hi,

We already tried to integrate PostgreSQL support, but it is a huge job and that requires many pieces of GLPI code to be rewritten. It will probably be added in a future version, but we cannot give any roadmap for it yet.

**Comment by trasher** [comment]
See https://glpi.userecho.com/communities/1/topics/119-postgresql-compatibility
