### ISSUE TITLE
Bug in Plugin Fields!

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15396]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Good day,

I have a problem with the Fields plugin. I have created a Custom Field for Enclosures and there a field with the option "Insertion in the form (before save button)". When I wanted to delete the field again, I only got a white screen. After refreshing the field was still there. In debug mode I got the following message:

Uncaught Exception Error: Class "PluginFieldsBusinesscriticalfieldDropdown" not found in /var/www/***********/glpi/marketplace/fields/inc/dropdown.class.php at line 208

I can't delete the field or custom block, then I always get the same message. I also can't uninstall the plugin, then I also get this error message.

I can create new fields in the block, but they are not displayed in the asset. It is also not possible to create a new custom block for enclosures because I get this message: You cannot add several blocks with type 'Insertion in the form' on same object.

What can I do, please help.

**Comment by trasher** [comment]
Please report issue on plugin
