### ISSUE TITLE
App_token automatically regenerate after saving with Regenerate box not checked

### ISSUE THREAD

**Issue by quentinlegay** [glpi-project/glpi#15395]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

On Setup tab --> General --> API
The app_token of an API client is automatically regenerated each time it is saved, even though the Regenerate box is not checked.

### Steps To reproduce

1. Go to Setup tab --> General --> API
2. Edit an API client without modification
3. Save parameters 
Application token (app_token) will change automatically after you click Save.

**Comment by trasher** [comment]
Please try with latest stable release.

**Comment by cedric-anne** [comment]
I just made a test and I am not able to reproduce on current nightly build.

**Comment by quentinlegay** [comment]
I will update and try with latest release but I found this PR : https://github.com/glpi-project/glpi/pull/14713
So normally merged to v10.0.8, my bad!

**Comment by quentinlegay** [comment]
I confirm that the bug has been fixed in the latest version (10.0.9).
