### ISSUE TITLE
Partial inventory add inventory elements of a given category where it should replace all elements of the category

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi#15390]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.9

### Bug description

Partial inventory generated by `glpi-inventory` script with `--partial` option permits to update one or more given inventory category, for example software or antivirus.
But actually it seems to add or update elements without deleting no more available elements.
This is particularly visible in the antivirus context where you can finally think you have 2 or more antivirus installed and eventually active after you uninstalled an antivirus and installed a new one.

### Steps To reproduce

Here is a summary to reproduce the issue in the antivirus case:
1. Import `antivirus-1.json` file from [partial-inventories.zip](https://github.com/glpi-project/glpi/files/12310733/partial-inventories.zip) archive
   Note: "partial" property must be reset to "true" before the test
2. Check antivirus category, and you should see:
![antivirus-1](https://github.com/glpi-project/glpi/assets/12514489/6eecdcc2-c709-45ac-af89-3151114cd3d7)
3. Import `antivirus-2.json` file from the archive
4. Check antivirus category, and you should see:
![antivirus-2](https://github.com/glpi-project/glpi/assets/12514489/bdb3b46a-8e99-4eee-b881-46a3361a7aaf)
But the `Microsoft Defender` one should have been removed.
5. Import `antivirus-3.json` file from the archive
6. Check antivirus category, and you should see:
![antivirus-3](https://github.com/glpi-project/glpi/assets/12514489/c111fa4f-f9d3-4ae0-bcf8-c0a42aa2deec)
The `Microsoft Defender` antivirus should not be in the list.
7. If you import back `antivirus-2.json`, you now have 3 antivirus with `Yes` as `active` status.
8. Now change to `false` or remove in all `antivirus-X.json` files the `partial` property and try again to import inventories, you should see the antivirus list with the expected result each time

**Comment by trasher** [comment]
I'm not able to reproduce. Upload of antivurs-1 creates one Ms Defender antivirus linked to computer, import of antivirus-2 file creates an Antivirus 2 linked to computer but no longer Ms Defender.
I've quickly setted up tests that validates it works: https://github.com/glpi-project/glpi/compare/10.0/bugfixes...trasher:glpi:fix/15390

**Comment by g-bougard** [comment]
Oups, big sorry, I made a mistake in the attached json... I attached the ones I finally modified for my own tests and so they don't have the "partial" property set to "true". So you have to set/add this property before doing again the test.

**Comment by g-bougard** [comment]
Here are the original files: [original-partial-json.zip](https://github.com/glpi-project/glpi/files/12319013/original-partial-json.zip)

**Comment by trasher** [comment]
Described behaviour has been explicitly set; and not only for antiviruses; changing only for antivirus seems a nonsense, and changing the whole behaviour seems too much for a bugfixes.

Also, I'm not sure this is a bug. No remove on partial inventories is hardcoded in several parts, this was therefore intended. I do not remember why exactly, and  "partial" thing has never really been specified...

**Comment by g-bougard** [comment]
From the agent point of view, when creating a partial inventory, it provides the full stuffs for the given categories. So IMHO, in glpi, when a category is present in a partial inventory, it must act like it was a full inventory for this inventory part. So yes, this must not be for AV specifically, but for all inventory discovered categories.

About the specification question, we discussed a lot about this feature when we decided to implement databases services inventory support. But yes, we should have detailed it somewhere.

**Comment by trasher** [comment]
"it provides the full stuffs for the given categories" => this is not what have been implemented. Also, this is not possible in some cases, some parts may rely on other (software rely on operating system for example - it may have others).

Removing data from a partial inventory is a bad idea. And your use case is a test case only; we should not tell user to do that;.

**Comment by g-bougard** [comment]
I guess we need first to fully specify how "partial" inventory should be handled:
- [ ] Write partial inventory support specs
