### ISSUE TITLE
Uncaught Exception Error: Call to undefined method Printer::isRackPart() in /glpi/src/Dropdown.php at line 362

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#15408]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

When trying to add a socket to a printer, I got this error: 

> Uncaught Exception Error: Call to undefined method Printer::isRackPart() in /glpi/src/Dropdown.php at line 362

This error was reported in the blog the last year but with no answer: https://forum.glpi-project.org/viewtopic.php?id=283813

![image](https://github.com/glpi-project/glpi/assets/56606032/0edb7552-9e1c-4b3e-8258-74e8a96e3790)

### Relevant log output

```shell
[2023-08-14 16:29:24] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined method Printer::isRackPart() in /glpi/src/Dropdown.php at line 362
  Backtrace :
  src/CommonDBTM.php:4108                            Dropdown::show()
  ajax/cable.php:54                                  CommonDBTM::dropdown()
  public/index.php:82                                require()
```

### Page URL

/front/socket.form.php

**Comment by jcervantes-sipecom** [comment]
Hi @trasher, I tried your suggest but now I got another error:

![image](https://github.com/glpi-project/glpi/assets/56606032/408d2b6b-73a3-47f0-a58c-7a0dac2bee58)

> [2023-08-28 09:20:42] glpiphplog.WARNING:   *** PHP Warning (2): Undefined variable $itemtype in /var/www/glpi/ajax/cable.php at line 53
>   Backtrace :
>   public/index.php:82                                require()

**Comment by jcervantes-sipecom** [comment]
I also tried what @cconard96 suggest in: https://github.com/glpi-project/glpi/pull/15409

And it allow to list the Printers:

![image](https://github.com/glpi-project/glpi/assets/56606032/7cc9bbfa-aff7-4f87-9c71-5495d40dc82c)

**Comment by trasher** [comment]
> Hi @trasher, I tried your suggest but now I got another error:
> [...]

Should be fixed as of latest commit proposed by Curtis on the PR.
