### ISSUE TITLE
API : authentication of a LDAP user fails after login with personal_token 

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1541]
Hi

To reproduce : import a user from a directory (AD or LDAP)
use this user to login, and create a personal_token
use  the API to login with this personal_token; login will succeed
now, try to login again to GLPi; login will fail

in the database, authtype changed from Auth::LDAP to Auth::API after a login attempt from the API

This bug does **not** happen if the user logs in with the API and his credentials

**Comment by btry** [comment]
I think the problem is the constant self::API which defines a new authentication type (the column authtype in the table glpi_user)

An authentication type seems to define where a user account come from (GLPi's DB, LDAP, CAS, X509...) 

However the auth type Auth::API is **how** a user logs in.

**Comment by trasher** [comment]
I do not totally agree. To me, the auth type seems to define how we'll try to authenticate the user. If type is API, we're using a token, etc.
I guess the problem is the system have never been prepared for concurrent auth.

**Comment by remicollet** [comment]
For now, API authent is considered as "extauth", when is should not.

**Comment by remicollet** [comment]
For now, API authent is considered as "extauth", when is should not., which is confusing with "atlernate" auth

Possible fix:

   static function isAlternateAuth($authtype) {
      return in_array($authtype, array(self::X509, self::CAS, self::EXTERNAL, self::API));
   }

And then

            if (isAlternateAuth($authtype)) {
               $this->extauth                  = 0;
            } else {
               $this->extauth                  = 1;
               $this->user->fields['authtype'] = $authtype;
            }

**Comment by remicollet** [comment]
Je pense aussi que le blankPassword (qui fait du SQL direct) devrait être supprimer et remplacer par le champ virtuel "_extauth", déjà géré dans prepareInputForAdd, manquant dans prepareInputForUpdate)

**Comment by btry** [comment]
I updated the PR with your suggestion : it works for me, better implemented.

I removed the call to User::blankPassword() too.

After a check : User::blankPassword() is no longer called anywhere in GLPi. We might remove it, if we are sure no plugin use it. 

If OK, lets remove the method in this PR then merge.

**Comment by trasher** [comment]
Fxed in PR #1548
