### ISSUE TITLE
Saved Searches don't work

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15418]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.9

### Bug description

Hello, the saved searches are not working properly. When I save a search in a custom object, I cannot run this saved search. I just get the message: "This page was not found". 

![image](https://github.com/glpi-project/glpi/assets/115316656/ca0bdb2d-6652-4103-a0f5-d4a92169f5d9)

In a normal category, however, the search will work.

### Steps To reproduce

1. create a custom object 
2. create a saved search within the custom object
3. select the saved search in the custom object 
4. after that you should see this message

![image](https://github.com/glpi-project/glpi/assets/115316656/ca0bdb2d-6652-4103-a0f5-d4a92169f5d9)

**Comment by cconard96** [comment]
Please include the GLPI setup information requested by the issue template.
Setup > General > System tab. Click "Copy system information" to copy all sections of information, which can then be pasted here.

**Comment by cconard96** [comment]
This issue should be fixed by #15273. The fix will be a part of GLPI 10.0.10.
