### ISSUE TITLE
SLA calendar issue. SLA Working with 24/7 calendar only.

### ISSUE THREAD

**Issue by jojyjmj1** [glpi-project/glpi#15429]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Suspect the SLA calendar working at a different timzone after upgrading to 10.0.9. Tickets are auto-escalated during the creation itself. 

### Steps To reproduce

![image](https://github.com/glpi-project/glpi/assets/142773742/46fc0fef-c25b-4d90-8b32-56f592927c5c)
![image](https://github.com/glpi-project/glpi/assets/142773742/c7f4c0bf-595c-4d31-b17b-0e8c6cdb3b56)

### Your GLPI setup information

GLPI 10.0.9 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

**Comment by antonplotn** [comment]
I have the same issue. Strange bug when using custom calendar:
- escalations in SLA do not work correctly when escalation time is negative regarding to the time to resolve.
- when escalation time equals TTR or more than TTR, escalations work correctly.

**Comment by jojyjmj1** [comment]
Same issue. So I configured it with TTR+ and managed it with OLA.

**Comment by cedric-anne** [comment]
@jojyjmj1 , @antonplotn 

This issue may be fixed by #15357. Could you validate this?
