### ISSUE TITLE
Notifications triggered by email followups don't mention tickets documents added after the initial ticket creation 

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#15428]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10-dev last synchronized on July the 13th

### Bug description

When somebody replies by email to a ticket notification, the notification triggered upon reception by the collector takes into account only documents attached during ticket creation (ie excludes documents from followups and so...) In the user interface ticket page all the documents are visible.

It seems that it comes from the following call:

NotificationTargetCommonITILObject.php:                    $item->getAssociatedDocumentsCriteria()

where the bypass_rights parameter is not set. As the ITILFollowup::canView is not defined either (probably because there is no active Session?), sql query is limited to documents with ticket item type.

Do you think that setting bypass_right value like this would be OK?
```$item->getAssociatedDocumentsCriteria(Session::isCron()),```

Thanks. 

### Steps To reproduce

1. Open a ticket with an attached document
2. Reply by email to the received notification adding an additional file
3. Check new notification number of documents et documents list.

**Comment by cedric-anne** [comment]
Fixed by #15454.
