### ISSUE TITLE
Separate coding standard rules so plugins can also use them

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#1542]
Actually, I copy the ruleset file from the core to each plugin; and I have to redo the operation each time it's changed on core.

@edgardmessias has proposed on #1209 to use a separate project to store rules, and require them using composer.

**Comment by trasher** [comment]
Here is a test; the glpi repo:
https://github.com/glpi-project/glpi/compare/master...trasher:feature/composer-standards

And the standards repo (just a copy or the ruleset file verbatim):
https://github.com/glpi-project/coding-standard/

**Comment by trasher** [comment]
(Note: for tests purposes, I've requested "dev-master" on a vcs repo -- of course, we'll make releases, and that will be changed!)

**Comment by trasher** [comment]
I've created releases and added the project to packagist:
https://packagist.org/packages/glpi-project/coding-standard

**Comment by AnaelMobilia** [comment]
Good idea !
It should be a good idea to suggest to plugins dev to respect ruleset too ?

Regards

**Comment by trasher** [comment]
@AnaelMobilia if the #1543 is merged, I'll update the empty plugin and the docs to reflect that. I've already begin to work on this for the fields plugin (https://github.com/pluginsGLPI/fields/pull/135) :)

**Comment by AnaelMobilia** [comment]
@trasher so, need docs update ;-)

**Comment by trasher** [comment]
It's been added already; but its currently in the "hooks" branch (http://glpi-developer-documentation.readthedocs.io/en/hooks/plugins/requirements.html#coding-standards) ;)

And a PR is open on the empty plugin (https://github.com/pluginsGLPI/empty/pull/17)

**Comment by trasher** [comment]
Done; see 7d510d3c5771e152e1de0ff517957eab3d665b87
