### ISSUE TITLE
The problem with restricting access to budgets

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#15430]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

At the moment it is possible to provide a general possibility to work with budgets through profile settings. With this, any employee of this profile sees the budget for all organizations. For example, there is a profile "External Support", it is used for different third-party organizations, different organizations fill their costs for work with applications. In this case, employees of different external organizations see each other’s budgets, which is neither technically nor legally correct.

**Comment by cconard96** [comment]
Budgets can be located in specific entities and profiles can be assigned for specific entities to restrict user access by entity.
