### ISSUE TITLE
Dashboard not updated on entity change

### ISSUE THREAD

**Issue by AndiMb** [glpi-project/glpi#15431]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

When flipping between enties in the "CTRL+ALT+E" menu, the dashboard is not updated and still uses the data from the entity before. Even reloading the page makes no difference. When reloading the page 10-15 seconds after the entity change, the data of the actual entity is used. It seems, GLPI is using cached values.

### Steps To reproduce

1. Open the dashboard page for one entity selected in the "CTRL+ALT+E" menu
2. Change the entity in the "CTRL+ALT+E" menu

**Comment by cedric-anne** [comment]
Hi,

I confirm the issue. The `c_cache_key` parameter, expected to prevent caching issues, is not impacted by active entities. It means that if the entity change occurs inside the cache validity timeframe (40s), some cards may contains invalid data.

**Comment by cedric-anne** [comment]
Fixed by #15537 in GLPI 10.0.10.
