### ISSUE TITLE
New Tickets Created with an ID of "0"

### ISSUE THREAD

**Issue by qaOYR** [glpi-project/glpi#15458]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

New Tickets are created with an "ID" value of 0.

If ticket "0" is deleted, **all subsequent new tickets are deleted**.  If it is "closed", all new tickets are closed. If it left as "New", all subsequent new tickets are then created successfully and with a status of "New".

In summary, my contention is that there is a serious bug in GLPi 10.0.9 that creates some tickets with an ID value of "0" as I have seen this happen in three separate installs. This ticket with an id of 0 determines what happens to subsequent tickets.

I assume that this isn´t a generalized problem and may be caused by interaction between code that was not there before 10.0.9  and a specific DB version of MariaDB, but it is quite clear to me that this bug was introduced by GLPi 10.0.9 as it never happened before the update.

It has taken us many hours to decipher what was going on.

### Steps To reproduce

1. Create new ticket
2. See ticket created with an ID=0 and therefore cannot be acted upon.
3. If you delete this ticket in the DB, all subsequent tickets will be deleted.
4. If you close ticket 0 by changing its status in DB to 6, all subsequent tickets will be closed.

### Your GLPI setup information

**Operating system:** Linux 
Server Software: MariaDB Server
	Server Version: 10.2.44-MariaDB
	Server SQL Mode: NO_AUTO_VALUE_ON_ZERO

**Comment by cconard96** [comment]
Try disabling the NO_AUTO_VALUE_ON_ZERO SQL mode flag. This mode shouldn't be enabled in a default installation of MySQL or MariaDB. Is the database server shared with another application that requires this SQL mode?

**Comment by qaOYR** [comment]
> Try disabling the NO_AUTO_VALUE_ON_ZERO SQL mode flag. This mode shouldn't be enabled in a default installation of MySQL or MariaDB. Is the database server shared with another application that requires this SQL mode?

Thank you so much for your prompt reply. I actually thought about this, but did not recall changing the configuration of MySQL.

**This was exactly the issue.** We are going to review when this changed was introduced in the configuration of our MySQL Server and make sure that this issue is clearly reflected in our internal docs to avoid seeing it again in the future.

**I really appreciate** your prompt response as we have been scratching our heads for a while with this issue.

Many thanks and keep up the excellent work.

**Comment by trasher** [comment]
I do not really agree. Full group option was a default we cannot deal with; this one was explicitly set by user. 

I'm pretty sure there are plenty of DB configuration options that can cause issues with GLPI (and many other software) - we can't deal with that.
