### ISSUE TITLE
An error in the statistics graph

### ISSUE THREAD

**Issue by Pasha8392** [glpi-project/glpi#15461]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7-git-develop-5b653c6

### Bug description

The number of requests is incorrectly displayed in the statistics.
Namely, the 'Late' and 'Closed' request statuses are mixed up.
I noticed this when I was forming statistics on requests and looking at graphs.

### Page URL

https://my_host/front/stat.graph.php?id=8&date1=2022-08-28&date2=2023-08-28&itemtype=Ticket&type=user

### Steps To reproduce

In the file src/Stat/Data/Graph/StatDataTicketAverageTime.php, I found this error on lines 61 and 64.

### Your GLPI setup information

Information about system installation & configuration:
GLPI 10.0.7-git-develop-5b653c6 ( => /opt/glpi)
Installation mode: GIT
Current language:en_US
Server:
Operating system: Linux glpi-staging 5.15.0-79-generic #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.13 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at glpi.startupsoft.org Port 443
)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: root@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.2-1ubuntu2.13) is supported.PHP version (8.1.2-1ubuntu2.13) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi_file/files/_cache has been validated. Write access to /var/www/html/glpi_file/config has been validated. Write access to /var/www/html/glpi_file/files/_cron has been validated. Write access to /var/www/html/glpi_file/files has been validated. Write access to /var/www/html/glpi_file/files/_dumps has been validated. Write access to /var/www/html/glpi_file/files/_graphs has been validated. Write access to /var/www/html/glpi_file/files/_lock has been validated. Write access to /var/www/html/glpi_file/files/_pictures has been validated. Write access to /var/www/html/glpi_file/files/_plugins has been validated. Write access to /var/www/html/glpi_file/files/_rss has been validated. Write access to /var/www/html/glpi_file/files/_sessions has been validated. Write access to /var/www/html/glpi_file/files/_tmp has been validated. Write access to /var/www/html/glpi_file/files/_uploads has been validated.Write access to /var/www/html/glpi_file/files/_cache has been validated.
Write access to /var/www/html/glpi_file/config has been validated.
Write access to /var/www/html/glpi_file/files/_cron has been validated.
Write access to /var/www/html/glpi_file/files has been validated.
Write access to /var/www/html/glpi_file/files/_dumps has been validated.
Write access to /var/www/html/glpi_file/files/_graphs has been validated.
Write access to /var/www/html/glpi_file/files/_lock has been validated.
Write access to /var/www/html/glpi_file/files/_pictures has been validated.
Write access to /var/www/html/glpi_file/files/_plugins has been validated.
Write access to /var/www/html/glpi_file/files/_rss has been validated.
Write access to /var/www/html/glpi_file/files/_sessions has been validated.
Write access to /var/www/html/glpi_file/files/_tmp has been validated.
Write access to /var/www/html/glpi_file/files/_uploads has been validated.

GLPI data directories are located in a secured path.GLPI data directories are located in a secured path.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /opt/glpi/marketplace has been validated.Write access to /opt/glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by trasher** [comment]
10.0.7 is outdated. Try with latest release, feel free to reopen if issue is still present.

**Comment by Pasha8392** [comment]
I tried it on version 10.0.7-git-main-7349104 too, but this error was there too.
It only disappeared after I fixed the error in the code

**Comment by trasher** [comment]
I do not understand... 10.0.7 is a stable release published months ago, and has nothing to deal with main. Also, commit number does not really mean anything. 

Anyway, if problem exists on current 10.0/bugfixes branch, and you have a fix, please open a pull request.

**Comment by Pasha8392** [comment]
I failed to create a pull request. Maybe you can do it?

**Comment by Pasha8392** [comment]
Thank you very much!
