### ISSUE TITLE
[10.0.7] ldap synchronization problem on an entity 

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#15464]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

 php bin/console ldap:synchronize_users --only-create-new

imports the new ones but nothing in the entity in question!

 php bin/console ldap:synchronize_users 

doesn’t matter says anything ok  !

How to feed an entity via an ldap fltre but how?
php bin/console ldap:synchronize_users  -f ???
It is in the supannaffectation of a user of type DN: uid=abenoit,or=people,dc=ns-lyon,dc=fr with supannaffectation = DPT BIOLOGIE.*/ ?

PS: I think the users exist in GLPI but in other entities you have to have them in that biology

I think this is a recurring problem when creating a new entity with rules about ldap users.
Can you help me?
In fact it is  "how to feed an entity with users that come from an ldap server when they are already present in other entities?"
I was thinking of making a sql query to add users? But I might break everything right?
Where is the link between users and entities in base? Thank you
Thanks to you

Ru
Thanks to you

Note:
In user menu there is ldap import then expert:
I choose Biology as an entity:
and I put:
Base dn: dc=es-lyon,dc=fr
ldap filter: (& (uid=*) (|(objectclass=enslPerson)(objectclass=groupOfNames))

But I would like to put supannEntiteAffectation = "DPT Biology" (which is in the uid of people)  m

**Comment by falco2001** [comment]
Hello,
is it possible to know the changes to be made in 10.0.7 because a migration is an important job with php mysql and all the personal plugins we have?
In advance Thank you

**Comment by cedric-anne** [comment]
> a migration is an important job with php mysql and all the personal plugins we have

Hi,

You should be able to migrate from 10.0.7 to 10.0.9 without having to update your PHP, MySQL or GLPI plugins.
