### ISSUE TITLE
[0.90] Bug with TinyMCE on ticket tab change

### ISSUE THREAD

**Issue by korial29** [glpi-project/glpi#155]
On rich text mode there is a bug with TinyMCE to display ticket content : 
1. Show the main ticket form : TinyMCE is OK
2. Change tabulation and go back to main form : First TinyMCE error "Uncaught ReferenceError: uploadFile1010068914 is not defined"
3. Change tabulation a second time and go back to main form : Second TinyMCE error "Uncaught TypeError: Cannot read property 'offsetHeight' of null" and the ticket description disappears.

**Comment by orthagh** [comment]
version of glpi ?
0.90 ?

**Comment by korial29** [comment]
Oui la version 0.90 trunk

**Comment by korial29** [comment]
Cela vient du système d'upload de fichier, je regarde

**Comment by orthagh** [comment]
ok
The release of 0.90 planned for this evening. The bug seems minor.
If this not fixed before end of day, after release, we'll do an update of lib on master and re-check this bug.

**Comment by yllen** [comment]
See also https://github.com/glpi-project/glpi/issues/161

**Comment by orthagh** [comment]
uploadFile zone is in cause and i can't find why the function of paste init cannot be called on tab switch.
But i dislike this feature in current version.

I started a branch to test upgrade of tinymce and drop paste zone (see #167) .
TinyMCE support picture pasting (also droping) in the content of textearea.
Moreover, pasting now work with IE11, so we could also drop java applet (erk !) 

Your opinions ?

**Comment by korial29** [comment]
I will test the new tinyMCE, if it supports image paste with the major browsers i agree that it's better to remove the current paste system.

We could remove the applet but the paste system will not be available for the earlier versions of IE ?

**Comment by orthagh** [comment]
thank you for your answer, waiting for your tests

**Comment by orthagh** [comment]
Addition to topic : http://forum.glpi-project.org/viewtopic.php?id=129975
Java applet is really really ugly and a nightmare to integrate properly

**Comment by orthagh** [comment]
```
We could remove the applet but the paste system will not be available for the earlier versions of IE ?
```
No ! and I'm in favor to remove this part.
Old version concerns Internet explorer <= 9. G. Analytics says 3% of our audience.

On customer integration prestation, we can provide a plugin (we had a old version for 0.84).
