### ISSUE TITLE
Subentities Ticket Management

### ISSUE THREAD

**Issue by anfgar** [glpi-project/glpi#1550]
Hi everybody!

We are an IT service provider and we have different costumers who recieve technical support. We are considering GLPI as the ticket system. 

We have created our company as our Root Entity. We create tickets, ANS, locations, places, etc, but when we wan to create a costumer company everything goes well until we create a ticket. We need that the subentity tickets could be watch from the Root Entity without the need of change the entity. 

Is that possible?

**Comment by tomolimo** [comment]
Hello 
Of course it's possible, GLPi is really doing it. 
Just select the tree structure in the entity selector. 

Moreover this web site is dedicated to issues (bugs), and not to functionnal questions, you should use the GLPi forum for that. http://forum.glpi-project.org
Regards 
Tomolimo
