### ISSUE TITLE
After upgrade to 0.91 version, the license tab is missing in software form

### ISSUE THREAD

**Issue by moralillos** [glpi-project/glpi#1551]
I was 0.90.5 but I update to 0.91 version I lost the license Items.
For example

This image was when I had the 0.90.5 version
 
![licencias](https://cloud.githubusercontent.com/assets/24966507/21734562/98cafa3e-d429-11e6-9712-c2486d430bc7.png)

This one is after to update 0.91 version
![glpi](https://cloud.githubusercontent.com/assets/24966507/21734575/b651504e-d429-11e6-9593-5a739ee3f3d2.png)

Any idea to how solve the problem

Thanks

**Comment by trasher** [comment]
Guess this is a right issue; since there are changes on 9.1 on tis part. Please review rights on your profiles; that should solve your problem.
