### ISSUE TITLE
"Lost" Status after contract cost update

### ISSUE THREAD

**Issue by eglyn** [glpi-project/glpi#15523]
### Version

10.0.9

### Bug description

Hi all :)

We have an issue when we add a cost to a contract, when we click on the add button, we have this: 
![image](https://github.com/glpi-project/glpi/assets/24936778/79e819bd-f940-41a1-bf75-7bd40d9733c4)

But the cost is recorded, if we go back to the contract, everything is find.

Do you know why this screen appear ? 

Thx !

**Comment by cconard96** [comment]
I cannot recreate the issue.

Please include the information requested in the issue template.
