### ISSUE TITLE
Add tasks in ticket templates

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#1554]
Add the possibility to create tasks in ticket templates.

See https://github.com/glpi-project/glpi/issues/1554

**Comment by AnaelMobilia** [comment]
@wawax #1554 is this ticket itself (wrong link) ;-)

**Comment by trasher** [comment]
I don't know why the link has been changed; I get the following on the original GH notification:
http://glpi.userecho.com/topics/249-add-task-template-to-ticket-template/

**Comment by orthagh** [comment]
see #1815
