### ISSUE TITLE
auto_prepend_file 

### ISSUE THREAD

**Issue by benchti** [glpi-project/glpi#15544]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.9

### Bug description

On our stack (debian/apache/php8.2) we have a php prepend file. The test on the document root fail since the first file is not a glpi file 

### Steps To reproduce

1: setup an auto_prepend_file in your webserver (the file should not be in glpi directory) 
2: install a new glpi 
3: you should see the warning during the install (in french) "La configuration du dossier racine du serveur web n'est pas sécurisée car elle permet l'accès à des fichiers non publics. Référez-vous à la documentation d'installation pour plus de détails." 

### Anything else?

here is the patch on our install 

src/System/Requirement/SafeDocumentRoot.php

```
62,66c62
<         $included_files = get_included_files();
<         while (!empty($included_files) && strpos(reset($included_files), GLPI_ROOT) !== 0) {
<                array_shift($included_files);
<         }
<         $initial_script = $included_files[0] ?? '';
---
>         $initial_script = get_included_files()[0] ?? '';
```

**Comment by cedric-anne** [comment]
Hi @benchti 

Could you test #15545 ?

**Comment by Cerdic** [comment]
Hi @cedric-anne 
this doesn't fix in our case as the `auto_prepend_file` is including 2 other files, and thus the `GLPI_ROOT . 'public/index.php'`  is only the 4th in the list.

That said there is a 'in between' solution which is to go through the `while()` only if there is an `auto_prepend_file`, that will keep the most usual case simplier

**Comment by cedric-anne** [comment]
> Hi @cedric-anne this doesn't fix in our case as the `auto_prepend_file` is including 2 other files, and thus the `GLPI_ROOT . 'public/index.php'` is only the 4th in the list.

Indeed, usage of prepended file is often resulting in including multiple files.

> 
> That said there is a 'in between' solution which is to go through the `while()` only if there is an `auto_prepend_file`, that will keep the most usual case simplier

I added a commit to implement this case.

**Comment by benchti** [comment]
We are using https://github.com/glpi-project/glpi/pull/15545/commits/122e1054714db9d885d261fe99a9d6aea80231e4 and it's ok on our side . 
Thanks

**Comment by cedric-anne** [comment]
Could you tell us for what purpose you are using this directive?
