### ISSUE TITLE
GLPI 9.1 - problem to see group's tickets

### ISSUE THREAD

**Issue by dan723** [glpi-project/glpi#1555]
Hi,
I've got this issue on GLPI 9.1: 
I creaty an entity, child of the root entity
Under this entity i create a group
I create 4 techcnicians under this entity and i add this technician to the group
In the profile they'got the privilege to see the group's tickets.
The problem is that each technician is able to see only the tickets assigned to him and not all the tickets assigned to the group.

Thanks

**Comment by tomolimo** [comment]
Hello 
Did you try with version 9.1.1?
Thank you 
Regards 
Tomolimo

**Comment by dan723** [comment]
Hi,
No, I didn't. 
I would like to know if it's an issue of the version 9.1 before updating.
Thanks

**Comment by tomolimo** [comment]
Could be a better idea to have a test of the new release before updating.

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on GLPI 9.4.2.

Regards
