### ISSUE TITLE
The auto-bump task doesn't follow the calender set in the entity

### ISSUE THREAD

**Issue by Zoddo** [glpi-project/glpi#15569]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

When using pending reasons with auto-bumps configured, bumps are sent outside of working days.

I'd expected that these bumps aren't sent on non-working days (like if you configure auto-close for resolved tickets, non-working days are excluded when calculating the date on which the ticket will be closed).

### Steps To reproduce

1. Create a follow up template
2. Create a pending reason with auto-bump enabled (every 1 days) with that follow up template
3. Create a calendar defining working days/hours (for the example, you can set working hours only for yesterday), and set it in the entity settings (assistance tab)
4. Put a ticket in pending state, and use the pending reason created above
5. Around 24 hours later, the ticket gets auto-bumped despite that day not being a working day

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.9 (/glpi => /var/www/glpi/glpi-1009)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux [REDACTED] 4.19.0-24-amd64 #1 SMP Debian 4.19.282-1 (2023-04-29) x86_64
PHP 8.2.8 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.39-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: [REDACTED]
	Host info: Localhost via UNIX socket
	
PHP version (8.2.8) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi/glpi-1009/files/_cache has been validated.
Write access to /var/www/glpi/glpi-1009/config has been validated.
Write access to /var/www/glpi/glpi-1009/files/_cron has been validated.
Write access to /var/www/glpi/glpi-1009/files has been validated.
Write access to /var/www/glpi/glpi-1009/files/_dumps has been validated.
Write access to /var/www/glpi/glpi-1009/files/_graphs has been validated.
Write access to /var/www/glpi/glpi-1009/files/_lock has been validated.
Write access to /var/www/glpi/glpi-1009/files/_pictures has been validated.
Write access to /var/www/glpi/glpi-1009/files/_plugins has been validated.
Write access to /var/www/glpi/glpi-1009/files/_rss has been validated.
Write access to /var/www/glpi/glpi-1009/files/_sessions has been validated.
Write access to /var/www/glpi/glpi-1009/files/_tmp has been validated.
Write access to /var/www/glpi/glpi-1009/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/glpi-1009/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi/glpi-1009"
GLPI_CONFIG_DIR: "/var/www/glpi/glpi-1009/config"
GLPI_VAR_DIR: "/var/www/glpi/glpi-1009/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/glpi-1009/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi/glpi-1009/files"
GLPI_CACHE_DIR: "/var/www/glpi/glpi-1009/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/glpi-1009/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi/glpi-1009/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi/glpi-1009/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/glpi-1009/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/glpi-1009/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/glpi-1009/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/glpi-1009/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/glpi-1009/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/glpi-1009/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/glpi-1009/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/glpi-1009/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/glpi-1009/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/glpi-1009/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/glpi-1009/locales"
GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/glpi-1009/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/glpi-1009/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/glpi-1009/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/var/www/glpi/glpi-1009/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/glpi-1009/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/glpi-1009/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/glpi-1009/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/glpi-1009/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/glpi-1009/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/glpi-1009/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/glpi-1009/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/glpi-1009/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/glpi-1009/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/glpi-1009/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/glpi-1009/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/glpi-1009/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/glpi-1009/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/glpi-1009/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/glpi-1009/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/glpi-1009/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/glpi-1009/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/glpi-1009/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi/glpi-1009/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi/glpi-1009/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/glpi-1009/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/glpi-1009/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/glpi-1009/vendor/psr/cache/src)
league/csv in (/var/www/glpi/glpi-1009/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/glpi-1009/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/glpi-1009/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/glpi-1009/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/glpi-1009/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/glpi-1009/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/glpi-1009/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/glpi-1009/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/glpi-1009/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/glpi-1009/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/glpi-1009/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/glpi-1009/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/glpi-1009/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/glpi-1009/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/glpi-1009/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/glpi-1009/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/glpi-1009/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
[REDACTED]
</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP ([REDACTED])

</pre></details><details><summary>Plugins list</summary><pre> 
	actualtime           Name: ActualTime                     Version: 2.1.0      State: Enabled                                 
		Install Method: Manual
	news                 Name: Alertes                        Version: 1.12.1     State: Enabled                                 
		Install Method: Manual
	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.20.7     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.13.2     State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalades                      Version: 2.9.2      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Manual
	gappessentials       Name: Gapp Essentials                Version: 2.1.2      State: Enabled                                 
		Install Method: Marketplace
	order                Name: Gestion des commandes          Version: 2.10.4     State: Enabled                                 
		Install Method: Manual
	tag                  Name: Gestion des tags               Version: 2.11.5     State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Impression pdf                 Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	tasklists            Name: Liste des tâches               Version: 2.0.3      State: Enabled                                 
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.3      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Enabled                                 
		Install Method: Manual
	reservation          Name: Reservation                    Version: 2.4.4      State: Enabled                                 
		Install Method: Manual
	stab                 Name: Split Timeline Action Buttons  Version: 1.1.2      State: Enabled                                 
		Install Method: Manual
	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Enabled                                 
		Install Method: Manual
	ticketcleaner        Name: Ticket Cleaner                 Version: 4.0.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

This enhancement has been done in #14698 and will be available in the next GLPI major version.
