### ISSUE TITLE
HCL Notes (Lotus Domino) Embedded images into body of emails don't appears in tickets

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#15578]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

We are using last version of Lotus Notes.
Embedded images into body of emails don't appears in tickets.

Test EMail attached.
[Test Mail.zip](https://github.com/glpi-project/glpi/files/12611234/Test.Mail.zip)

**Comment by cedric-anne** [comment]
Hi,

It works on my side (current nightly build of 10.0.x).
![image](https://github.com/glpi-project/glpi/assets/33253653/e94f3fee-d7b9-418d-ab5f-ab631859ec73)

Could you please provide requested information (logs, if any, GLPI system information, list of your plugins)?
Could you also provide a screenshot of the result you get when displaying the created ticket?

**Comment by husisusi** [comment]
Hi,

Thank you @cedric-anne.

I'll do a few more tests today, I suspected that the error only occurs with pop3 or simply when I use the Domino server as a receiver, but I'm not sure yet.

I will provide you with more information after further testing.

**Comment by husisusi** [comment]
Hi @cedric-anne 

If I push this “test Mail.eml” file into my GLPI helpdesk mailbox, it works. That's why it worked for you.

Apparently I have to email you directly from Domino Server to reproduce the issue on your side.
Is it possible to send me a private message with your testing email address so I can email you directly to your testing environment?

Screenshot:
![grafik](https://github.com/glpi-project/glpi/assets/8606735/39f75a42-a4e7-47a6-8658-744f2191efd5)


Server Information:
`GLPI 10.0.9 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US`

> Operating system: Linux as-glpi 5.15.0-83-generic-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64
PHP 8.1.23 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="360" memory_limit="512M" post_max_size="128M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
PHP version (8.1.23) is supported.PHP version (8.1.23) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

> PHP version (8.1.23) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

Plugins:
	`accounts             Name: Accounts                       Version: 3.0.3      State: Enabled                                 
		Install Method: Manual
	fields               Name: Additional fields              Version: 1.20.7     State: Enabled                                 
		Install Method: Manual
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.2     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.7     State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.3      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	shellcommands        Name: Shell Commands                 Version: 4.0.1      State: Enabled                                 
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.11.5     State: Enabled                                 
		Install Method: Manual
`

**Comment by cedric-anne** [comment]
> Is it possible to send me a private message with your testing email address so I can email you directly to your testing environment?

Please send it to [glpi-debug-gre684hvtez874@teclib.com](mailto:glpi-debug-gre684hvtez874@teclib.com). This is a temporary alias to my email.

**Comment by husisusi** [comment]
@cedric-anne, Thank you!
I just sent test mail from Lotus Note to this email.

**Comment by cedric-anne** [comment]
I confirm the issue.

![image](https://github.com/glpi-project/glpi/assets/33253653/e68a0185-0bc0-4b4c-b202-84520c52102d)

**Comment by cedric-anne** [comment]
This case is fixed by #15702 and added in our test suite.

![image](https://github.com/glpi-project/glpi/assets/33253653/2328ffc3-c036-4145-95db-5540be36b336)

**Comment by husisusi** [comment]
Could you please reopen this issue?
The Fix works for HCL Lotus Notes but not for IBM Lotus Notes.
I can send example email to the temporary alias.

**Comment by cedric-anne** [comment]
> Could you please reopen this issue? The Fix works for HCL Lotus Notes but not for IBM Lotus Notes. I can send example email to the temporary alias.

[glpi-debug-h8te74hte84hjt4@teclib.com](mailto:glpi-debug-h8te74hte84hjt4@teclib.com)

**Comment by husisusi** [comment]
I sent an email today at 10:50 am.

**Comment by cedric-anne** [comment]
It works on mi side on current nightly build:

![image](https://github.com/glpi-project/glpi/assets/33253653/34624ad5-89a6-4a7c-bc5a-b2c83fcf439c)
