### ISSUE TITLE
sha1sum dependencies

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1558]
e7ba43b7a54eae3bb2d0389ee4ef85346beef61f introduce a dependency to sha1sum which isn't installable on windows.

In order to prevent OS dependencies couldn't we call an OS independent tools (PHP script, ... ) ?

Regards,
Anael

**Comment by trasher** [comment]
Yes, I guess we can use PHP to generate the checksum from the composer script.
