### ISSUE TITLE
GLPI entity on ticket is wrong if "select all" are marked

### ISSUE THREAD

**Issue by Peterfilho** [glpi-project/glpi#15596]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Working with GLPI 10.0.9 i found a issue that not happens in version 9.x (not tested on above 10.0.9)

Afeter login with my user who has 3 entities (IT, Maintence, sales) and self service profile (to be able to open tickets) In menu i can change my entity and depends on my entity i can open ticket with some cathegory. For example, if my entity is IT, i can open ticket asking to configure wifi, and anothers cathegories does not show, but i can select all on menu for when i need to create ticket show all categories to user, and depends on selected category the entity on ticket is selected,right?

#### This is the menu
![entity](https://github.com/glpi-project/glpi/assets/13772779/fea97bbb-e7e3-4617-9fa7-0f6d49a8c6b2)

If i select a single entity i can open ticket and entity was right atributed!

but if i use this button:
![entity2](https://github.com/glpi-project/glpi/assets/13772779/69b0ec6e-762e-4d79-9365-1869e671c1f9)

Even i set ticket with IT cathegory, the entity in ticket was default user entity (sales for example) thats results in ticket who not displays on IT's tickets.

### Steps To reproduce

1. Add user's two or more entities;
2. Create cathegory of ticket for each entities (example IT, Sales);
3. Login and click in menu (as image shows) on select all option;
4. if your default cathegory is sales, try to open ticket with IT cathegory;
5. The ticket will be opened with default 'Sales' cathergory and no be in IT tickets;

### Anything else?

This only happens if select all entities was marked. If i go to a single entity and select, the ticket is generated normaly.

**Comment by Peterfilho** [comment]
uo

**Comment by mssantosjr** [comment]
The soluction is choose a default entitie on user.
