### ISSUE TITLE
Computer description not displayed in inventory

### ISSUE THREAD

**Issue by buggzbeny** [glpi-project/glpi#15597]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello,

We used Fusion Inventory on Glpi 9.x.x and there was computer description which was displayed in "plugin computer system commentary" from registry key :

my $description = getRegistryValue(path => 'HKEY_LOCAL_MACHINE/SYSTEM/CurrentControlSet/Services/lanmanserver/Parameters/srvcomment');

Now we use GLPI 10.x and Glpi Agent 1.5 and this information is not available on the server even if this is part of inventory in hardware.pm

C:\Users\administrateur>"C:\Program Files\GLPI-Agent\glpi-inventory.bat" --partial hardware
[info] New partial inventory from PC-TEAM-LBU.louis-barthou.lyc-2023-09-18-16-30-27 for local0
{
"action": "inventory",
"content": {
"bios": {
"bdate": "2014-04-01",
"bmanufacturer": "SeaBIOS",
"bversion": "rel-1.16.1-0-g3208b098f51a-prebuilt.qemu.org",
"smanufacturer": "QEMU",
"smodel": "Standard PC (i440FX + PIIX, 1996)"
},
"hardware": {
"chassis_type": "Other",
"description": "salle-test",
"memory": 6143,
"name": "xxxxxx",
"uuid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
"vmsystem": "QEMU",
"winlang": "1036",
"winowner": "xxxxxxxxxxxxxx",
"winprodid": "00331-20020-00000-AA044",
"workgroup": "workgroup.local"
},
"versionclient": "GLPI-Inventory_v1.5"
},
"deviceid": "xxxxxxxxxxxxxxxxxxxxx-2023-09-18-16-30-27",
"itemtype": "Computer",
"partial": true
}
[info] Inventory dumped on standard output

Is it possible to show this information on GLPI server ?

regards

### Your GLPI setup information

GLPI 10.0.6 (/glpi => /opt/glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by trasher** [comment]
First of all, you'd better use last stable release.

Second, what is the missing information you're talking about, in the JSON file?

**Comment by stonebuzz** [comment]
@trasher he talk about ```description``` files from ```hardware``` node (see related issue from glpi-agent repo).

Maybe we Can put this fields into computer ```comment``` field

Or into New object ?

**Comment by stonebuzz** [comment]
Here https://github.com/glpi-project/glpi-agent/issues/486#issue-1901128857

Look at json comment from ```hardware``` node

**Comment by trasher** [comment]
Seems like `comment` field of main asset is not used; so yes it should be used to store that. Since this data looks like related to windows OS only, I'm not in favor of adding anything new in database.
