### ISSUE TITLE
Error in assembling json response. rest api uri :listSearchOptions/type

### ISSUE THREAD

**Issue by kirkinmur1561** [glpi-project/glpi#15593]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

last

### Bug description

Non-standardized response for rest api.
If I make a request to http://..../apirest.php/listSearchOptions/Ticket, I get a response in the form of characteristics and fields. example:
```json
"common": {"name": "Characteristics"},
   "1": {"name": "Header","table": "glpi_tickets","field": "name","datatype": "itemlink","nosearch": false,"nodisplay": false," available_searchtypes": ["contains","notcontains"],"uid": "Ticket.name"},
   "21": {
     "name": "Description",
     "table": "glpi_tickets",
     "field": "content",
     "datatype": "text",
     "nosearch": false,
     "nodisplay": false,
     "available_searchtypes": [
       "contains",
       "notcontains"
     ],
     "uid": "Ticket.content"
   },...
```
common is a field, and 1 is a characteristic.
Problem.
When requesting http://..../apirest.php/listSearchOptions/User
The last 2 fields are written as characteristics.
Example.
```json
"link": "External Links",
   "145": {
     "name": "External Links",
     "table": "glpi_links",
     "field": "_virtual",
     "datatype": "specific",
     "nosearch": true,
     "nodisplay": false,
     "available_searchtypes": [
       "contains",
       "notcontains"
     ],
     "uid": "User.Link_Itemtype.Link._virtual"
   },
   "manuallink": "Links to documentation",
   "146": {
     "name": "Links to documentation",
     "table": "glpi_manuallinks",
     "field": "_virtual",
     "datatype": "specific",
     "nosearch": true,
     "nodisplay": false,
     "available_searchtypes": [
       "contains",
       "notcontains"
     ],
     "uid": "User.ManualLink._virtual"
   }
```
manuallink and link should be written as "manuallink":{"name": "Documentation Links"} "link":{"name": "External Links"}
I haven't checked the other requests.

### Page URL

/listSearchOptions/Ticket /listSearchOptions/User

**Comment by cedric-anne** [comment]
Fixed by #15701.
