### ISSUE TITLE
Page in ticket creation always reloads for some fields

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15595]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

When creating a ticket, the page reloads when filling in some fields. What is the reason for this and is this normal behavior? The following fields are affected: Entity, Type, Category, Requester.

**Comment by trasher** [comment]
Yes, that is expected, to properly reload all related data mainly. Changing category or entity is a very huge change.
