### ISSUE TITLE
Last PDF Library : Trouble with PDF Export (All pages)

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#156]
When you want to export a important list of object, the web server go to timeout

GLPI 0.84 with 4440 tickets & pdf library ezpdf : 1 minute (no timeout)

GLPI 0.90 with 4440 tickets & pdf library tcpdf : timeout & error to memory
 Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 70 bytes) in glpi90/lib/tcpdf/tcpdf.php on line 16440

**Comment by tsmr** [comment]
Problématique déjà présente en 0.85
Augmentation du memory_limit à 1024 Mo
Augmentation du max_execution_time à 3000
toujours pas d'affichage après 20mn à tourner dans le vide

**Comment by remicollet** [comment]
Which font is configure ?
But probably we hit some limit...

**Comment by tsmr** [comment]
I try the 3 in config

**Comment by AnaelMobilia** [comment]
Hello,

I made some test with stub tickets :
  - With more than 1000 tickets, I hit a memory limit (128M)
  - With 1000 tickets, I hit the 300 s time limit...
  - With 500 tickets, it need like 45-60 seconds to generate the PDF file

This time is really high in regard of the time (~5 sec) requiered to display the same list on the browser.

Need to track execution time to known if it's linked to tcpdf itself or the way we call it.
[glpi-5.pdf](https://github.com/glpi-project/glpi/files/1595002/glpi-5.pdf)

Note : the tcpdf library isn't maintened from 2016...
Need to upgrade to [tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf) (not released for the moment)

Regards,
Anael

**Comment by AnaelMobilia** [comment]
I tried to move to the [dompdf library](https://github.com/dompdf/dompdf) v0.8.2 (more active than tcpdf / tc-lib-pdf).
Results aren't high as required... a few more performance, but no miracles.

Still crash on high tables.

Advantages of dompdf : css can be used to format the page (no need of "hack" in php)

Regards

**Comment by trasher** [comment]
Until the PDF lib is updated to be more performant; the only way to go is to update server memory and timeout limits.
Some improvements may be done on the GLPI part, of course, but ths would be a very huge job, for a very small performance enhancement.
