### ISSUE TITLE
Accounts plugin PHP error 

### ISSUE THREAD

**Issue by npo412** [glpi-project/glpi#15603]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Hello,

After the upgrade to version 10.0.9, we encountered issues with the Accounts plugin:

PHP Warning:  Invalid relations declared for "glpi_plugin_accounts_accountstates" table. Target table "glpi_plugin_accounts_mailingstates" does not correspond to a known itemtype. in /var/local/xxxxxxxxxx/glpi/src/DbUtils.php on line 2111

The accounts plugin works well and we can access the accounts and passwords without any issue but this alert on PHP appears every day since the update.

### Relevant log output

```shell
[2023-09-18 10:21:42] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared for "glpi_plugin_accounts_accountstates" table. Target table "glpi_plugin_accounts_mailingstates" does not>
  Backtrace :
  src/DbUtils.php:2111                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
  src/CommonDBConnexity.php:127                      CommonDBTM->delete()
  src/CommonDBTM.php:992                             CommonDBConnexity->cleanDBonItemDelete()
  src/IPAddress.php:205                              CommonDBTM->deleteChildrenAndRelationsFromDb()
  src/CommonDBTM.php:783                             IPAddress->cleanDBonPurge()
  src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
  src/Inventory/Asset/InventoryNetworkPort.php:497   CommonDBTM->delete()
  src/Inventory/Asset/InventoryNetworkPort.php:121   Glpi\Inventory\Asset\MainAsset->handleUpdates()
  src/Inventory/Asset/MainAsset.php:823              Glpi\Inventory\Asset\MainAsset->handlePorts()
  src/RuleImportAsset.php:969                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1525                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1640                        Rule->process()
  src/Inventory/Asset/MainAsset.php:573              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:709                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:340                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:360                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:92                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  plugins/glpiinventory/front/communication.php:72   include_once()
  plugins/glpiinventory/index.php:45                 include_once()
  public/index.php:82                                require()
```

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.9 ( => /var/local/xxxxx/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at glpi.xxxxx.net Port 443
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.19-MariaDB-0+deb11u2
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.19) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/local/xxxxx/glpi/files/_cache has been validated.
Write access to /var/local/xxxxx/glpi/config has been validated.
Write access to /var/local/xxxxx/glpi/files/_cron has been validated.
Write access to /var/local/xxxxx/glpi/files has been validated.
Write access to /var/local/xxxxx/glpi/files/_dumps has been validated.
Write access to /var/local/xxxxx/glpi/files/_graphs has been validated.
Write access to /var/local/xxxxx/glpi/files/_lock has been validated.
Write access to /var/local/xxxxx/glpi/files/_pictures has been validated.
Write access to /var/local/xxxxx/glpi/files/_plugins has been validated.
Write access to /var/local/xxxxx/glpi/files/_rss has been validated.
Write access to /var/local/xxxxx/glpi/files/_sessions has been validated.
Write access to /var/local/xxxxx/glpi/files/_tmp has been validated.
Write access to /var/local/xxxxx/glpi/files/_uploads has been validated.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/local/xxxxx/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/local/xxxxx/glpi"
GLPI_CONFIG_DIR: "/var/local/xxxxx/glpi/config"
GLPI_VAR_DIR: "/var/local/xxxxx/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/local/xxxxx/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/local/xxxxx/glpi/files"
GLPI_CACHE_DIR: "/var/local/xxxxx/glpi/files/_cache"
GLPI_CRON_DIR: "/var/local/xxxxx/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/local/xxxxx/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/local/xxxxx/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/local/xxxxx/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/local/xxxxx/glpi/files/_lock"
GLPI_LOG_DIR: "/var/local/xxxxx/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/local/xxxxx/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/local/xxxxx/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/local/xxxxx/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/local/xxxxx/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/local/xxxxx/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/local/xxxxx/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/local/xxxxx/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/local/xxxxx/glpi/locales"
GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/local/xxxxx/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/local/xxxxx/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/local/xxxxx/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/local/xxxxx/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/local/xxxxx/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/local/xxxxx/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/local/xxxxx/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/local/xxxxx/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/local/xxxxx/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/local/xxxxx/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/local/xxxxx/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/local/xxxxx/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/local/xxxxx/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/local/xxxxx/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/local/xxxxx/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/local/xxxxx/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/local/xxxxx/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/local/xxxxx/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/local/xxxxx/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/local/xxxxx/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/local/xxxxx/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/local/xxxxx/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/local/xxxxx/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/local/xxxxx/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/local/xxxxx/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/local/xxxxx/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/local/xxxxx/glpi/vendor/psr/cache/src)
league/csv in (/var/local/xxxxx/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/local/xxxxx/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/local/xxxxx/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/local/xxxxx/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/local/xxxxx/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/local/xxxxx/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/local/xxxxx/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/local/xxxxx/glpi/vendor/symfony/cache)
html2text/html2text in (/var/local/xxxxx/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/local/xxxxx/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/local/xxxxx/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/local/xxxxx/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/local/xxxxx/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/local/xxxxx/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/local/xxxxx/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/local/xxxxx/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/local/xxxxx/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/local/xxxxx/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/local/xxxxx/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://fr-val-dc02.xxxxx.net', Port: '389', BaseDN: 'DC=xxxxx,DC=net', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 's_glpi', Use TLS:
		none
Server: 'auth2.xxxxx.net', Port: '389', BaseDN: 'dc=xxxxx,dc=lz', Connection filter: '(&(|(sambaAcctFlags=[U      
		  
		])(sambaAcctFlags=[U]))(!(uid=adminscan))(!(uid=faxuser))(!(uid=git))(!(uid=mroom))(!(uid=mtest))(!(uid=root))(!(uid=qc))(!(uid=qcatl2016))(!(uid=scan))(!(uid=supertest))(!(uid=dspoutnik))(!(uid=s_winsync)))',
		RootDN: none, Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@localhost)

</pre></details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.3      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
This is an issue on accounts plugin, please report issue against plugin

**Comment by npo412** [comment]
Thanks for the answer, sorry to post on the wrong channel.
