### ISSUE TITLE
##unicity.message## Error on reference URL to Computer

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#15607]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

I have setup Field Unicity for Computer based of its Name:

![image](https://github.com/glpi-project/glpi/assets/56606032/63997c2c-d38e-487c-b2a9-7ef92d52567f)

I already got a notification, but the tag `##unicity.message##` shows wrong the URL to reference to a Computer: 

![image](https://github.com/glpi-project/glpi/assets/56606032/040e9457-5070-41f0-bd3f-3dba256d7d19)

As you can see, when move the mouse over the computer's name, it only shows the path but not the complete URL.

I check the notification temple as well, but it can't be the issue as I cannot modified the tag `##unicity.message##` so I guess it's a code issue. 

I also tried the tag `##glpi.url##` but it only references to the principal URL and not with the asset path

**Comment by cconard96** [comment]
Is the application URL set in Setup > General > General setup tab?

**Comment by jcervantes-sipecom** [comment]
hi @cconard96 yes:

![image](https://github.com/glpi-project/glpi/assets/56606032/080bb90e-d670-487a-acda-2218c8b22cda)

**Comment by cedric-anne** [comment]
I take a look at the code and it seems that the link is built by a method that is used for both the UI and the notifications. Method uses `$CFG_GLPI['root_doc']` as a prefix, and that is correct for the UI, but not for the notifications where `$CFG_GLPI['url_base']` should be used.

**Comment by cedric-anne** [comment]
A solution could be to add a piece of code, at the end of the `NotificationTemplate::process()` method, that converts relative links to absolute link. This kind of code already exists in GLPI: https://github.com/glpi-project/glpi/blob/329b50bd6a9f1b5c96c035bd294d23484f7a4cc2/src/RichText/RichText.php#L122-L127
