### ISSUE TITLE
Line spacing in tinymce Editor

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15630]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.9

### Bug description

We have a problem with the description fields e.g. in the ticket creation which seems to be caused by the tinymce editor. The line spacing is way too big and we would like to adjust it via the UI customization in the entity. Unfortunately we can't adjust the tinymce via this but we could help ourselves with the class: rich_text_container.

.rich_text_container p {
  margin-bottom: 0;
}

![image](https://github.com/glpi-project/glpi/assets/115316656/f86af8ab-1c0c-4cf7-9b57-e3e83bf20d30)
![image](https://github.com/glpi-project/glpi/assets/115316656/9b75a759-143e-4aeb-b79b-c6ce7ae00914)

When creating the ticket in the tinymce editor or in the description of the ticket, nothing changes but after saving the line spacing is correct.

![image](https://github.com/glpi-project/glpi/assets/115316656/02b36f65-2b08-4336-9036-73a3df698738)
![image](https://github.com/glpi-project/glpi/assets/115316656/52d60846-1de1-4e50-8015-1bbc18ab5fde)

Is there a better way to set this or configure this in tinymce?

**Comment by cedric-anne** [comment]
Hi,

It is not currently possible to customize editor styles.
