### ISSUE TITLE
How to unlock globally a locked field by FusionInventory

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi#15634]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Hello

How to unlock globally a field locked previsously with FusionInventory ?
There is a button to add a lock : ok
but to unlock a field (Serial for instance) in order that glpi-inventory may set this value for all computers ?

thanks

**Comment by stonebuzz** [comment]
Hi @EC2311 
You need to do it here

![image](https://github.com/glpi-project/glpi/assets/7335054/e9a17f87-8691-4828-b05c-a423c0ede739)

Search for global lock, and use massive action

Best regards
