### ISSUE TITLE
[GLPI 10.0.10] Loss of solution template formatting

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi#15636]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.10

### Bug description

I have ready-made solutions for answering tickets in Home / Setup / Dropdowns / Solution templates.

In versions prior to 10.0.10, what was configured was what appeared when we added the solution to the ticket.

![image](https://github.com/glpi-project/glpi/assets/57845086/f304fa6a-15dc-49af-b693-40331ee78dc4)

Now, the formatting is being disregarded.

Excerpt from the solution's source code:

![image](https://github.com/glpi-project/glpi/assets/57845086/115fde5f-dd51-465d-98b0-d3673f98b2d0)

As it appears when we insert the solution template in the ticket:

![image](https://github.com/glpi-project/glpi/assets/57845086/30cacec1-8f1a-4139-aaa0-02a72a677885)

Excerpt from the solution source code inserted into the ticket:

![image](https://github.com/glpi-project/glpi/assets/57845086/084d4ae9-f610-4335-80b4-51c9fdc87ab4)

**Comment by cedric-anne** [comment]
Maybe it is related to #15531.

**Comment by RobertoMarcelino** [comment]
This is not an image but pure HTML text.

I changed the default font and added an HTML table, and when we add it to the ticket, the formatting is lost.

**Comment by M-Falken** [comment]
That's because some html tag are not authorised in the tinymce configuration.
For example we must have :
valid_elements: "@[class],p[style],h3,h4,h5,h6,a[href|target],strong/b,"
              + "div[align],br,table,tbody,thead,tr,td,ul,ol,li,img[src]"
valid_children : "+body[style]"

I wish that we have more settings in the general configuration to tweak the editor as we need.
Because I must redo my hacks for every glpi update.

**Comment by RobertoMarcelino** [comment]
Where did you add those hacks?

**Comment by jussara-ti** [comment]
Hi, same issue here. 
In version 10.0.10 colors and the text alignment in tables are lost when i add a solution through solution templates

**Comment by RobertoMarcelino** [comment]
@M-Falken  Where did you add those hacks?

**Comment by RobertoMarcelino** [comment]
> Same issue for me That's because some html tag are not authorised in the tinymce configuration. For example we must have : valid_elements: "@[class],p[style],h3,h4,h5,h6,a[href|target],strong/b," + "div[align],br,table,tbody,thead,tr,td,ul,ol,li,img[src]" valid_children : "+body[style]"
> 
> All in the tniymce js file, and in src/Html.php But what I don't understand is that it seems all allowed by default for Tinymce and only iframe are blocked, but when I save a template all is lost.
> 
> I wish that we have more settings in the general configuration to tweak the editor as we need. Because I must redo my hacks for every glpi update.

Where did you add those hacks?

In which files do you add these changes?

**Comment by RobertoMarcelino** [comment]
Hello @M-Falken.

Could you help us by telling us which files and on which lines you made the changes in tinymce?

We'd really appreciate your contribution.

**Comment by trasher** [comment]
If I correctly understand, the initial issue was HTML tags/attriutes, like `table` are removed when adding a solution (directly, not from a template).
#15839 may address this, you can test (not yet validated, accepted solution may be different).

Note for those who edit GLPI files: all will be overriden on next GLPI update.

**Comment by trasher** [comment]
Please try #15840

**Comment by M-Falken** [comment]
> Hello @M-Falken.
> 
> Could you help us by telling us which files and on which lines you made the changes in tinymce?
> 
> We'd really appreciate your contribution.

oops sorry, I didn't receive the notification
I found this in various posts on the web because I already had the problem under GLPI 9.5.
Today it's a little different with GLPI v10, but you can check these files.

- public/lib/tinymce.js (about line 27000)
- [src/Html.php](https://github.com/glpi-project/glpi/blob/8668618aa0b9e47fd3b672ad4179f4037b5a2fa6/src/Html.php#L3884C10-L3884C10)
