### ISSUE TITLE
Error in email followup

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#15642]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

I'm receiving emails in GLPI, but the email text is not displayed, only HTML code:

For example:

![image](https://github.com/glpi-project/glpi/assets/56876938/e7fc16b9-f25f-46b2-a805-03141fb663da)

In DDBB followup content:

![image](https://github.com/glpi-project/glpi/assets/56876938/90772fe7-7945-4d1c-a098-05b32bbc57da)

</span></p>
</div>
</div>
</div>

GLPI version 10.0.9

thank you

### Relevant log output

```shell

I do not find logs at error followup error time.

mailgate.log:
El mensaje (cannot read - connection closed?) no es vÃ¡lido. Revisa en "/GLPI10/glpi/files/_log/php-errors.log" para mÃ¡s detalles.

php-error.log:
[2023-09-26 15:10:06] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Protocol\Exception\RuntimeException: cannot read - connection closed? in /GLPI10/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php at line 110
  Backtrace :
  .../laminas/laminas-mail/src/Protocol/Imap.php:137 Laminas\Mail\Protocol\Imap->nextLine()
  .../laminas/laminas-mail/src/Protocol/Imap.php:256 Laminas\Mail\Protocol\Imap->nextTaggedLine()
  .../laminas/laminas-mail/src/Protocol/Imap.php:546 Laminas\Mail\Protocol\Imap->readLine()
  ...r/laminas/laminas-mail/src/Storage/Imap.php:113 Laminas\Mail\Protocol\Imap->fetch()
  ...aminas-mail/src/Storage/AbstractStorage.php:270 Laminas\Mail\Storage\Imap->getMessage()
  src/MailCollector.php:755                          Laminas\Mail\Storage\AbstractStorage->current()
  src/MailCollector.php:1888                         MailCollector->collect()
  src/CronTask.php:1018                              MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  
[2023-09-26 15:10:06] glpiphplog.WARNING:   *** PHP Warning (2): fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:0A00010F:SSL routines::bad length in /GLPI10/glpi/vendor/laminas/laminas-mail/src/Protocol/Imap.php at line 327
  Backtrace :
  .../laminas/laminas-mail/src/Protocol/Imap.php:327 fwrite()
  .../laminas/laminas-mail/src/Protocol/Imap.php:343 Laminas\Mail\Protocol\Imap->sendRequest()
  .../laminas/laminas-mail/src/Protocol/Imap.php:414 Laminas\Mail\Protocol\Imap->requestAndResponse()
  ...r/laminas/laminas-mail/src/Storage/Imap.php:239 Laminas\Mail\Protocol\Imap->logout()
  ...aminas-mail/src/Storage/AbstractStorage.php:135 Laminas\Mail\Storage\Imap->close()
  src/CronTask.php:1018                              Laminas\Mail\Storage\AbstractStorage->__destruct()
  front/cron.php:83                                  CronTask::launch()
```

### Page URL

no applicable

### Steps To reproduce

receiving mails only, is random.

### Your GLPI setup information

<details><summary>Información sobre la instalación y configuración del sistema</summary><pre>GLPI 10.0.9 ( => /GLPI10/glpi)
Installation mode: TARBALL
Current language:es_ES

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux SR 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64
PHP 8.1.2-1ubuntu2.13 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Server Software: MySQL Enterprise Server - Commercial
	Server Version: 8.0.32-commercial
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: 123@SR:6446/glpi
	Host info: SR via TCP/IP
	
PHP version (8.1.2-1ubuntu2.13) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.32) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /GLPI10/glpi/files/_cache has been validated.
Write access to /GLPI10/glpi/config has been validated.
Write access to /GLPI10/glpi/files/_cron has been validated.
Write access to /GLPI10/glpi/files has been validated.
Write access to /GLPI10/glpi/files/_dumps has been validated.
Write access to /GLPI10/glpi/files/_graphs has been validated.
Write access to /GLPI10/glpi/files/_lock has been validated.
Write access to /GLPI10/glpi/files/_pictures has been validated.
Write access to /GLPI10/glpi/files/_plugins has been validated.
Write access to /GLPI10/glpi/files/_rss has been validated.
Write access to /GLPI10/glpi/files/_sessions has been validated.
Write access to /GLPI10/glpi/files/_tmp has been validated.
Write access to /GLPI10/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /GLPI10/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/GLPI10/glpi"
GLPI_CONFIG_DIR: "/GLPI10/glpi/config"
GLPI_VAR_DIR: "/GLPI10/glpi/files"
GLPI_MARKETPLACE_DIR: "/GLPI10/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/GLPI10/glpi/files"
GLPI_CACHE_DIR: "/GLPI10/glpi/files/_cache"
GLPI_CRON_DIR: "/GLPI10/glpi/files/_cron"
GLPI_DUMP_DIR: "/GLPI10/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/GLPI10/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/GLPI10/glpi/files/_locales"
GLPI_LOCK_DIR: "/GLPI10/glpi/files/_lock"
GLPI_LOG_DIR: "/GLPI10/glpi/files/_log"
GLPI_PICTURE_DIR: "/GLPI10/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/GLPI10/glpi/files/_plugins"
GLPI_RSS_DIR: "/GLPI10/glpi/files/_rss"
GLPI_SESSION_DIR: "/GLPI10/glpi/files/_sessions"
GLPI_TMP_DIR: "/GLPI10/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/GLPI10/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/GLPI10/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/GLPI10/glpi/locales"
GLPI_VERSION: "10.0.9"
GLPI_SCHEMA_VERSION: "10.0.9@77fc44668eaae89b61d95fe606d20d93d66110cd"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/GLPI10/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/GLPI10/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/GLPI10/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/GLPI10/glpi/marketplace/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/GLPI10/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/GLPI10/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/GLPI10/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/GLPI10/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/GLPI10/glpi/vendor/sabre/http/lib)
sabre/uri in (/GLPI10/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/GLPI10/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/GLPI10/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/GLPI10/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/GLPI10/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/GLPI10/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/GLPI10/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/GLPI10/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/GLPI10/glpi/vendor/symfony/console)
scssphp/scssphp in (/GLPI10/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/GLPI10/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/GLPI10/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/GLPI10/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/GLPI10/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/GLPI10/glpi/vendor/ramsey/uuid/src)
psr/log in (/GLPI10/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/GLPI10/glpi/vendor/psr/simple-cache/src)
psr/cache in (/GLPI10/glpi/vendor/psr/cache/src)
league/csv in (/GLPI10/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/GLPI10/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/GLPI10/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/GLPI10/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/GLPI10/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/GLPI10/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/GLPI10/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/GLPI10/glpi/vendor/symfony/cache)
html2text/html2text in (/GLPI10/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/GLPI10/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/GLPI10/glpi/vendor/symfony/dom-crawler)
twig/twig in (/GLPI10/glpi/vendor/twig/twig/src)
twig/string-extra in (/GLPI10/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/GLPI10/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/GLPI10/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/GLPI10/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/GLPI10/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Plugins list</summary><pre> 
	mailanalyzer         Name: Mail Analyzer                  Version: 3.0.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

Please attach corresponding email source into eml format, so we can try to reproduce.

**Comment by trasher** [comment]
Ne feedback from a while, closing
