### ISSUE TITLE
Existing problem with black font in dark theme as in ticket #15606

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15645]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.10

### Bug description

I have now installed version 10.0.10 and still the black font in the dark theme which should have been fixed with version 10.0.10.

After the update to 10.0.10 the occurring black font after pasting from the browser suggestions was fixed but in some situations like in this picture it still is.

![268968001-b3f396f5-2d62-45b5-ba67-2af7c4508448](https://github.com/glpi-project/glpi/assets/115316656/0e3d2c34-ed8c-4d5a-a8b7-3482b45f1172)

Here is an example in the project creation. Here it occurs in the Description and Comments fields by hand input.

![image](https://github.com/glpi-project/glpi/assets/115316656/0f2fba98-6636-4901-a83d-2efbacd2b9f2)

**Comment by cconard96** [comment]
The two cases should be fixed by #15707.
