### ISSUE TITLE
phpDocumentor code style

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#1564]
As discuss with @trasher on a PR, we should made our guidelines for the phpdoc

https://phpdoc.org/docs/latest/getting-started/your-first-set-of-documentation.html#example

Maybe we should create a § on readthedocs in order to define the order we want (@param, @since, @return, @throws, @global, @author, @deprecated, @global, @see, ...)

**Comment by trasher** [comment]
I've made a proposal https://github.com/glpi-project/docdev/issues/13 :)

**Comment by trasher** [comment]
Done on the developer doc :)
