### ISSUE TITLE
GLPI can not get Monitor from GLPI Agent when GLPI Agent get seri monitor is 00000000

### ISSUE THREAD

**Issue by biz1990** [glpi-project/glpi#15653]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

GLPI can not get Monitor from GLPI Agent when <SERIAL>00000000</SERIAL> for import to inventory. How to fix it please help me.

### Relevant log output

```shell
<MONITORS>
      <BASE64>AP///////wAebd5bAAAAAAEaAQOAMBt46jE1pVVOoSYMUFSlSwBxT4GAlQCzAKnAgQCBwJBAAjqAGHE4LUBYLEUA4A4RAAAeAAAA/QA4Sx5VEgAKICAgICAgAAAA/ABMRyBGVUxMIEhECiAgAAAA/wAKICAgICAgICAgICAgAdwCAxKxR5AEAwESHxNlAwwAEAACOoAYcTgtQFgsRQDgDhEAAB4qRICgcDgnQDAgNQDgDhEAAB4BHQByUdAeIG4oVQDgDhEAAB6MCtCKIOAtEBA+lgDgDhEAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYw==</BASE64>
      <CAPTION>LG FULL HD</CAPTION>
      <DESCRIPTION>1/2016</DESCRIPTION>
      <MANUFACTURER>Goldstar Company Ltd</MANUFACTURER>
      <PORT>HDMI</PORT>
      <SERIAL>00000000</SERIAL>
    </MONITORS>
```

### Your GLPI setup information

GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10@05de68add675fb55abaeec10f3a2552085594a16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

**Comment by g-bougard** [comment]
Hi @biz1990 

first of all, this is not a GLPI issue by itself: `00000000` is not a valid serialnumber and so is blacklisted in GLPI.

It could be a glpi-agent one, but if you have searched a little you would have discovered you're facing a monitor problem: many manufacturers made their monitors with a bug that prevents their serialnumber to be retrieved when they are connected via hdmi. You may fix this issue to connect via vga or dvi if your monitor has such port.

Anyway, you should complain to your monitor manufacturer and ask them for a solution: why their monitor is reporting such wrong serialnumber ? And please share the answer if they have one as this can be useful.

Regarding the inventory task itself for this kind of monitor, the best choice for you is probably to just make manual inventory.
