### ISSUE TITLE
Broken ranking management when Adding a new Rule using API

### ISSUE THREAD

**Issue by Berthe01** [glpi-project/glpi#15658]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When I try to add a rule of %SubType% using API with no ranking value, next rank is not computed correctly.

It seems to be related to the SubType (or even getType method)  management in Rule.php :

- prepareInputForAdd($input)
- getNextRanking()

Into getNextRanking, any type of Rule will return 1 (0+1).

I think at least into that two above function getType method should be replaced by some kind ok getSubType method, or input['sub_type'] if defined.

----

Another thing to handle would be to Add a rule at an existing rank should rewrite ranking of following rules eventually using the RuleCollection::moveRule function ?

### Steps To reproduce

1. Try to add a rule via API and do not specify ranking, for example :
    {
    "input": {
           "entities_id": 0,
           "sub_type": "RuleMailCollector",
           "name": "ADD02",
           "description": "",
           "match": "OR",
           "is_active": 0
    }
} 
2. See that rank is alway defined to 1.

### Your GLPI setup information

GLPI 10.0.10 ( => /var/www/glpi-prod/glpi)
Installation mode: TARBALL
Current language:fr_FR

PHP 8.1.2-1ubuntu2.14 
Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at *** Port 443)
MySQL  8.0.34-0ubuntu0.22.04.1

**Comment by cedric-anne** [comment]
I confirm the issue.

**Comment by cconard96** [comment]
Which URL are you using to create the rule? It seems to me like `/RuleMailCollector` is the most correct URL to use. When creating the rule from `/Rule` the getNextRanking is called on a `Rule` object instead of the sub type which then returns the wrong rank since nothing in the DB exists for a rule of type `Rule`.

#15692 should fix the addition of rules using the generic `/Rule` endpoint in the legacy API.

**Comment by Berthe01** [comment]
Hi Curtis,

Yes I used {{APIUrl}}/Rule to add the MailCollector Rule.

I did not try to to {{APIUrl}}/RuleMailCollector because a GET on that URL do not return any data.

**Comment by cedric-anne** [comment]
Fixed by #15692
