### ISSUE TITLE
Task date in the list

### ISSUE THREAD

**Issue by evertondemoura** [glpi-project/glpi#15657]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9 

### Bug description

When creating a task from a ticket, the list shows the date of creation or editing and does **not include the date of the task**.
To view the task date, I need to edit the task and if the ticket is already finished, I need to reopen the ticket and change the task to view the task date.

In GLPI 9 this function existed, but in GLPI 10 I can't configure it.
Does it still exist or do I now need a plugin?
If so, what would it be?

exemple GLPI 10
![image](https://github.com/glpi-project/glpi/assets/15331384/47cec8dc-0086-4836-9df9-28f9b6b31fee)

![image](https://github.com/glpi-project/glpi/assets/15331384/34aca14d-061b-455c-94cd-ad527a4ba268)

exemple GLPI 9 
![image](https://github.com/glpi-project/glpi/assets/15331384/171aba03-327b-4cb5-8f38-c20ccb9442ca)

**Comment by stonebuzz** [comment]
Hi @evertondemoura 

can you try this 

https://github.com/glpi-project/glpi/issues/15657

Best regards

**Comment by evertondemoura** [comment]
Correct, in glpi 9 it was in this shared format.
However, in 10 I couldn't implement it.
If there is a plugin for this, can you share?

**Comment by stonebuzz** [comment]
Sorry for wrong link 

There is #15659
