### ISSUE TITLE
Unknown table "glpi_networkportmigrations"

### ISSUE THREAD

**Issue by wforumw** [glpi-project/glpi#15686]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hi,

When I run 
`php bin/console database:check_schema_integrity`
 I get

> Unknown table "glpi_networkportmigrations" has been found in database.
> --- Expected database schema
> +++ Current database schema
> @@ @@
> +CREATE TABLE `glpi_networkportmigrations` (
> +  `id` int NOT NULL AUTO_INCREMENT,
> +  `comment` text,
> +  `entities_id` int NOT NULL DEFAULT 0,
> +  `gateway` varchar(255),
> +  `invalid_address` tinyint NOT NULL DEFAULT 0,
> +  `invalid_gateway` tinyint NOT NULL DEFAULT 0,
> +  `invalid_network` tinyint NOT NULL DEFAULT 0,
> +  `ip` varchar(255),
> +  `is_recursive` tinyint NOT NULL DEFAULT 0,
> +  `items_id` int NOT NULL DEFAULT 0,
> +  `itemtype` varchar(100) NOT NULL,
> +  `logical_number` int NOT NULL DEFAULT 0,
> +  `mac` varchar(255),
> +  `name` varchar(255),
> +  `netmask` varchar(255),
> +  `netpoints_id` int NOT NULL DEFAULT 0,
> +  `networkinterfaces_id` int NOT NULL DEFAULT 0,
> +  `subnet` varchar(255),
> +  `unknown_interface_type` tinyint NOT NULL DEFAULT 0,
> +  PRIMARY KEY (`id`),
> +  KEY `entities_id` (`entities_id`),
> +  KEY `is_recursive` (`is_recursive`),
> +  KEY `item` (`itemtype`,`items_id`),
> +  KEY `netpoints_id` (`netpoints_id`),
> +  KEY `networkinterfaces_id` (`networkinterfaces_id`),
> +  KEY `on_device` (`items_id`,`itemtype`)
> +)

Can I remove this table?
Thanks in advance
Kind Regards,

**Comment by trasher** [comment]
This table should have been dropped in GLPI 0.84. I **guess** you can remove it.
