### ISSUE TITLE
Profiles are invisible for Admin when rights on "Gabarits de suivis" are given

### ISSUE THREAD

**Issue by paidge** [glpi-project/glpi#15685]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

v10.0.7

### Bug description

I duplicated default profiles so that I can modify them without breaking the default ones.
I am the SuperAdmin and I just gave Admin profile to somebody so that he can give Technician profile to any interns.
Oddly, he can't see the technician profile in the list when he wants to give that profile : 
![image](https://github.com/glpi-project/glpi/assets/2470104/4f5d7309-d1aa-45cc-9fb9-2c071b219391)

After investigating with a test profile, I noticed that profiles are invisible when rights are activated on "tracking templates"

![image](https://github.com/glpi-project/glpi/assets/2470104/205b45c2-59dd-4b6d-a264-ae14beadd07e)

### Steps To reproduce

1. Create the Admin profile with these rights and give that profile to a user (John Doe): 
![image](https://github.com/glpi-project/glpi/assets/2470104/9b4d06c6-6a0b-4380-b28a-67534b3089a7)

2. Create two profiles. One with rights activated on "tracking templates" and one without.
3. Connect with John Doe accountwith the Admin profile
4. Try to give a profile to a lambda user and notice that the profile with rights on "tracking templates" is invisible

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.7 ( => /var/www/glpi10.0.7)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux hd 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64
PHP 8.1.23 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at hd.domain.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0
Server Software: Debian 11
	Server Version: 10.5.21-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: helpdesk_glpi@localhost/helpdesk_glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.23) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.
gd extension is installed.
intl extension is installed.
libxml extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.21) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Web server root directory configuration seems safe.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi10.0.7/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi10.0.7"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/glpi10.0.7/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/glpi-plugins/"
GLPI_I18N_DIR: "/var/www/glpi10.0.7/locales"
GLPI_VERSION: "10.0.7"
GLPI_SCHEMA_VERSION: "10.0.7@5d45269702917a32805e25b678f6779a98b145f6"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.3.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi10.0.7/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi10.0.7/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi10.0.7/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi10.0.7/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi10.0.7/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi10.0.7/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi10.0.7/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi10.0.7/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi10.0.7/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi10.0.7/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi10.0.7/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi10.0.7/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi10.0.7/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi10.0.7/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi10.0.7/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi10.0.7/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi10.0.7/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi10.0.7/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi10.0.7/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi10.0.7/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi10.0.7/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi10.0.7/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/glpi10.0.7/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/glpi10.0.7/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi10.0.7/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi10.0.7/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi10.0.7/vendor/psr/cache/src)
league/csv in (/var/www/glpi10.0.7/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi10.0.7/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi10.0.7/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi10.0.7/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi10.0.7/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi10.0.7/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi10.0.7/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi10.0.7/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi10.0.7/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi10.0.7/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi10.0.7/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi10.0.7/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi10.0.7/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi10.0.7/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi10.0.7/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi10.0.7/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi10.0.7/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap.domain.fr', Port: '389', BaseDN: 'dc=domain,dc=fr', Connection filter:
		'(|(eduPersonPrimaryAffiliation=affiliate)(eduPersonPrimaryAffiliation=employee)(eduPersonPrimaryAffiliation=faculty))', RootDN:
		'cn=ldapbindusr-glpi-helpdesk,ou=DSA,dc=domain,dc=fr', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp.domain.fr)

</pre></details><details><summary>Plugins list</summary><pre> 
	screenshot           Name: Capture d'écran                Version: 2.0.2      State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
Please first try on latest release if you reproduce.
