### ISSUE TITLE
Tickets with a large number of associated assets are not displayed correctly

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#15690]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

On the main page /front/central.php a list of tickets is displayed for support users. If there are a large number of devices associated with the ticket, the application field becomes too large.
![image](https://github.com/glpi-project/glpi/assets/121490906/68e4da3d-c2c0-4eb0-868c-dcf48741dfd6)

It would be correct to hide some of the related elements if there are too many of them. Following the example of how this is done for comment or note text fields.
![image](https://github.com/glpi-project/glpi/assets/121490906/d0691b21-68da-4e6a-a22b-9b7483db91c7)

### Page URL

 /front/central.php a list of tickets is displayed for support users. If there are a large number of devices associated with the ticket, the application field

**Comment by trasher** [comment]
Try with latest stable if you reproduce.

**Comment by ak47d** [comment]
Tested on 10.0.10. Same problem
