### ISSUE TITLE
timeline display with anonymous ticket

### ISSUE THREAD

**Issue by yatar** [glpi-project/glpi#157]
When a ticket is created with an anonymous email in the timeline the name (email address) does not appear
![ticket1](https://cloud.githubusercontent.com/assets/15038264/10376670/65ab47a8-6dff-11e5-8e1c-644c0713db7a.png)
![ticket2](https://cloud.githubusercontent.com/assets/15038264/10376669/65a4e714-6dff-11e5-963c-096dfc796916.png)

**Comment by Siruv** [comment]
Hi,
I have the same problem, a ticket created with an anonymous email doesn't appear in the new timeline.
It is very disturbing to follow the request.

Are you going to fix the bug for milestone 0.90.1 ?


Best regards.

**Comment by orthagh** [comment]
I fixed the display to show "requester" instead false user information.
I can't deduce the email associated to a ticket or a followup, in case of anonymous collect.
Requesters can be multiple or changed after creation, so the information in users_id_requester isn't ok.

I think we need a _users_id_recipient_notif for theses anonymous ticket or followups

**Comment by Siruv** [comment]
Ok thanks for your fix !
I 'd like : instead of reading 'demandeur' (requester), read : 'email of requester'. Is it possible ?

**Comment by orthagh** [comment]
No, i dislike, requester can be different according to source
