### ISSUE TITLE
In refusing to approve a solution for a change, it does not change the status, it only adds a follow-up; the status is not altered.

### ISSUE THREAD

**Issue by verdanatech-marcio** [glpi-project/glpi#15700]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

In refusing to approve a solution for a change, it does not change the status, it only adds a follow-up; the status is not altered.

### Page URL

http://localhost/glpi/front/change.form.php

### Steps To reproduce

1. Solve an open change.
2. Refuse solution

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.10 ( => /var/www/html/glpi-10.0.10)
Installation mode: GIT
Current language:pt_BR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux PEVTCMTNB3015 6.1.0-11-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64
PHP 8.2.10 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop, soap, sockets,
	sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.57 (Debian) (Apache/2.4.57 (Debian) Server at glpi.local Port 80
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Server Software: Debian 12
	Server Version: 10.11.3-MariaDB-1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: admin@127.0.0.1/glpi-10.9
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.2.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.3) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi-10.0.10/files/_cache has been validated.
Write access to /var/www/html/glpi-10.0.10/config has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_cron has been validated.
Write access to /var/www/html/glpi-10.0.10/files has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_dumps has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_graphs has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_lock has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_pictures has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_plugins has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_rss has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_sessions has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_tmp has been validated.
Write access to /var/www/html/glpi-10.0.10/files/_uploads has been validated.

Web server root directory configuration seems safe.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi-10.0.10/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi-10.0.10"
GLPI_CONFIG_DIR: "/var/www/html/glpi-10.0.10/config"
GLPI_VAR_DIR: "/var/www/html/glpi-10.0.10/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi-10.0.10/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "GIT"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi-10.0.10/files"
GLPI_CACHE_DIR: "/var/www/html/glpi-10.0.10/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi-10.0.10/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi-10.0.10/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi-10.0.10/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi-10.0.10/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi-10.0.10/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi-10.0.10/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi-10.0.10/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi-10.0.10/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi-10.0.10/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi-10.0.10/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi-10.0.10/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi-10.0.10/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi-10.0.10/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi-10.0.10/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10@05de68add675fb55abaeec10f3a2552085594a16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi-10.0.10/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi-10.0.10/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi-10.0.10/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi-10.0.10/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi-10.0.10/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi-10.0.10/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi-10.0.10/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi-10.0.10/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi-10.0.10/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi-10.0.10/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi-10.0.10/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi-10.0.10/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi-10.0.10/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi-10.0.10/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi-10.0.10/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi-10.0.10/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi-10.0.10/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi-10.0.10/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi-10.0.10/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi-10.0.10/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi-10.0.10/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi-10.0.10/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi-10.0.10/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi-10.0.10/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi-10.0.10/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi-10.0.10/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi-10.0.10/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi-10.0.10/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi-10.0.10/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi-10.0.10/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi-10.0.10/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi-10.0.10/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi-10.0.10/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi-10.0.10/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi-10.0.10/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi-10.0.10/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi-10.0.10/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi-10.0.10/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi-10.0.10/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi-10.0.10/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi-10.0.10/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi-10.0.10/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi-10.0.10/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.6.0 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

**Comment by verdanatech-marcio** [comment]
Any corrections?

**Comment by Pieurre** [comment]
Hello @verdanatech-marcio,
As a TECLIB Official partner, you hav ton open your requests and decalre bugs via the offical way: https://support.teclib.com

Thank you very much
Pierre

**Comment by Pieurre** [comment]
z

**Comment by cedric-anne** [comment]
I keep this issue open since it is not fixed yet.
