### ISSUE TITLE
GLPI NETWORK

### ISSUE THREAD

**Issue by arnaud8854** [glpi-project/glpi#15731]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Bonjour,

Je viens d'installer la dernière version de Glpi 10.0.10 sur un Windows serveur 2022. Il m'est impossible d'accéder à l'onglet GLPI Network afin de pouvoir enregistrer la clé. le site est bien en https, quand je navigue dans les autres onglets je n'ai aucun problème.
J'ai essayé la solution curl.cainfo sans résultat
Auriez-vous une solution ?

### Page URL

https://support.chris-admin.fr/front/config.form.php

### Your GLPI setup information

GLPI 10.0.10 ( => C:\glpi)
Installation mode: TARBALL
Current language:fr_FR

perating system: Windows NT SRV-WEB 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.9 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, random, readline, session, soap, standard, tidy, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47
Server Software: MySQL Community Server - GPL
	Server Version: 8.1.0
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: admin.glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.2.9) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.1.0) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\glpi/files/_cache has been validated.
Write access to C:\glpi/config has been validated.
Write access to C:\glpi/files/_cron has been validated.
Write access to C:\glpi/files has been validated.
Write access to C:\glpi/files/_dumps has been validated.
Write access to C:\glpi/files/_graphs has been validated.
Write access to C:\glpi/files/_lock has been validated.
Write access to C:\glpi/files/_pictures has been validated.
Write access to C:\glpi/files/_plugins has been validated.
Write access to C:\glpi/files/_rss has been validated.
Write access to C:\glpi/files/_sessions has been validated.
Write access to C:\glpi/files/_tmp has been validated.
Write access to C:\glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "C:\glpi":
‣ "C:\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "C:\glpi\public".
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to C:\glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

### Anything else?

vous pouvez me contacter a cette adresse :

contact@chris-admin.fr

**Comment by arnaud8854** [comment]
je viens de faire quelques modifs, voici la sortie

Operating system: Windows NT SRV-WEB 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.9 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, random, readline, session, soap, sodium, standard, tidy, tokenizer, xml, xmlreader,
	xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47
Server Software: MySQL Community Server - GPL
	Server Version: 8.1.0
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: admin.glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.2.9) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.1.0) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\glpi/files/_cache has been validated.
Write access to C:\glpi/config has been validated.
Write access to C:\glpi/files/_cron has been validated.
Write access to C:\glpi/files has been validated.
Write access to C:\glpi/files/_dumps has been validated.
Write access to C:\glpi/files/_graphs has been validated.
Write access to C:\glpi/files/_lock has been validated.
Write access to C:\glpi/files/_pictures has been validated.
Write access to C:\glpi/files/_plugins has been validated.
Write access to C:\glpi/files/_rss has been validated.
Write access to C:\glpi/files/_sessions has been validated.
Write access to C:\glpi/files/_tmp has been validated.
Write access to C:\glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "C:\glpi":
‣ "C:\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "C:\glpi\public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

**Comment by trasher** [comment]
It is requested to write in english only.

**Comment by trasher** [comment]
Also, it seems this is rather a support question than a bug
