### ISSUE TITLE
GLPI 10.0.10 assistance ticket right menu is empty

### ISSUE THREAD

**Issue by psk4ykn** [glpi-project/glpi#15744]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

After updating GLPI from 10.0.7 to 10.0.10, i saw that the right menu in assistance ticket is empty. 
<img width="1079" alt="glpi-assistance-ticket" src="https://github.com/glpi-project/glpi/assets/147483960/fe2cf963-407e-4044-ad54-c5313e151d0a">

div of the right menu : 

![image](https://github.com/glpi-project/glpi/assets/147483960/0e3110b7-ae60-47c0-86c6-4582b8f3fc5c)

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.10 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.numerian.lan 5.15.0-75-generic #​82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64
PHP 8.1.2-1ubuntu2.14 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at support.numerian.fr Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.2-1ubuntu2.14) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/glpi/files"
GLPI_CACHE_DIR: "/var/www/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10@05de68add675fb55abaeec10f3a2552085594a16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.9 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@smtp-master-v.inforoutes.fr)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.21.4     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.13.2     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.7     State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.3      State: Enabled                                 
		Install Method: Manual
	satisfaction         Name: Plus de satisfaction           Version: 1.6.2      State: Enabled                                 
		Install Method: Manual
	reports              Name: Rapports                       Version: 1.16.0     State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

Please check GLPI logs (`_files/logs/php-errors.log`). There is probably an error that prevent the form to be rendered completely.

**Comment by psk4ykn** [comment]
Hi, 

I got this :

[2023-06-19 14:42:53] glpiphplog.WARNING: Test logger
[2023-06-19 14:43:15] glpiphplog.WARNING:   *** PHP User Warning (512): Missing required intl PHP extension in /var/www/glpi/src/Session.php at line 694
  Backtrace :
  src/Session.php:694                                trigger_error()
  inc/config.php:69                                  Session::loadLanguage()
  inc/includes.php:53                                include_once()
  front/locale.php:41                                include()

[2023-06-19 14:43:24] glpiphplog.WARNING: Test logger
[2023-06-19 14:43:28] glpiphplog.WARNING: Test logger
[2023-06-19 14:43:34] glpiphplog.WARNING: Test logger
[2023-06-19 14:44:01] glpiphplog.WARNING: Test logger
[2023-06-19 14:44:07] glpiphplog.WARNING: Test logger
[2023-06-19 14:44:46] glpiphplog.WARNING: Test logger
[2023-06-19 14:46:15] glpiphplog.WARNING: Test logger
[2023-06-19 14:47:28] glpiphplog.WARNING: Test logger
[2023-06-19 14:47:52] glpiphplog.WARNING: Test logger
[2023-06-19 14:48:15] glpiphplog.WARNING: Test logger
[2023-06-19 14:48:32] glpiphplog.WARNING: Test logger
[2023-06-19 14:51:23] glpiphplog.WARNING: Test logger
[2023-06-19 14:53:28] glpiphplog.WARNING: Test logger
[2023-06-19 14:59:50] glpiphplog.WARNING: Test logger
[2023-06-19 15:00:07] glpiphplog.WARNING: Test logger
[2023-06-19 15:03:32] glpiphplog.WARNING: Test logger
[2023-06-19 15:04:23] glpiphplog.WARNING: Test logger

**Comment by psk4ykn** [comment]
Hi,

i find this in php-errors.log :

[2023-10-09 16:15:39] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:44] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:44] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:49] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:49] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:54] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:54] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:59] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:15:59] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:04] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:04] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:09] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:09] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:14] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:14] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:19] glpiphplog.WARNING:   *** PHP Warning (2): include_once(/var/www/glpi/plugins/mreporting/vendor/autoload.php): Failed to open stream: No such file or directory in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

[2023-10-09 16:16:19] glpiphplog.WARNING:   *** PHP Warning (2): include_once(): Failed opening '/var/www/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/php') in /var/www/glpi/plugins/mreporting/setup.php at line 60
  Backtrace :
  plugins/mreporting/setup.php:60                    include_once()
  src/Plugin.php:1852                                include_once()
  src/Plugin.php:1854                                Plugin->{closure}()
  src/Plugin.php:1774                                Plugin->loadPluginSetupFile()
  src/Plugin.php:746                                 Plugin->getInformationsFromDirectory()
  src/Plugin.php:517                                 Plugin->getNewInfoAndDirBasedOnOldName()
  src/Plugin.php:497                                 Plugin->checkPluginState()
  src/Plugin.php:229                                 Plugin->checkStates()
  inc/includes.php:86                                Plugin->init()
  ajax/notifications_ajax.php:36                     include()
  public/index.php:73                                require()

**Comment by cedric-anne** [comment]
This log is not related to the current issue.

Please try to display the page and see if errors are added to the log at the same time.

**Comment by psk4ykn** [comment]
There are no errors being added to the php-errors logs.

**Comment by gabriel-maggalhaes** [comment]
Do you use the "Additional Fields" plugin? I had this error in an additional tab that I created, disabled and it worked.

**Comment by psk4ykn** [comment]
Thanks you !

Yes I use it. I have disabled the additional field and now I have the right menu.

**Comment by psk4ykn** [comment]
Thanks you !

Yes I use it. I have disabled the additional field and now I have the right menu.
