### ISSUE TITLE
Unaligned items and blank spaces in answer, task, solution and validation interfaces

### ISSUE THREAD

**Issue by jussara-ti** [glpi-project/glpi#15750]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hello everyone,

In version 10.0.10 I noticed some unaligned items and blank spaces in the tasks, validations, responses and solution interfaces. Here some screenshots:

![Tarefa GLPI](https://github.com/glpi-project/glpi/assets/60328341/f05f9984-f022-4b1a-a940-be0507da2b55)

![Validação](https://github.com/glpi-project/glpi/assets/60328341/10570f3c-8d1d-4c97-8bd7-2acded54acbb)

With that, some fields are shrink, which is a bit inconvenient.

Thanks in advance.

### Your GLPI setup information

Operating system: Linux GLPI-T 5.10.0-25-amd64 #​1 SMP Debian 5.10.191-1 (2023-08-16) x86_64
PHP 8.2.10 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json,
	ldap, libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop,
	soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at XXX Port 443
)

**Comment by Rom1-B** [comment]
https://github.com/glpi-project/glpi/pull/15639 should correct it

**Comment by jussara-ti** [comment]
Ok, I'll test it
