### ISSUE TITLE
"You don't have permission to perform this action" On locations and Entities moved

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#15752]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10 and Cloud

### Bug description

We cannot access to locations that had been transfer from a Child to a Parent Entity, after this Entity has been moved as a Child Entity.

### Relevant log output

```shell
Cannot Access to Log Files from Cloud.
```

### Steps To reproduce

1. Create 2 entities in the same level:

![image](https://github.com/glpi-project/glpi/assets/56606032/a4879fd7-fee6-4e2d-a79c-1e43bc643b42)

2. Create Locations in the First Entity (change to that entity and create them):

![image](https://github.com/glpi-project/glpi/assets/56606032/95b9c26a-6337-4297-9e34-28b74945ded1)

3. Move the First Entity as a child to the Second Entity:

![image](https://github.com/glpi-project/glpi/assets/56606032/64a49d76-7f32-452a-8779-1150870f3990)

4. Update Locations created in the First Entity to be Recursive:

![image](https://github.com/glpi-project/glpi/assets/56606032/ef9fa498-e327-4d8e-8f1b-af4ecfbabac6)

5. Add the Locations to Transfer List, and move them to the Parent Entity of the First Entity, I mean to the Second Entity:

![image](https://github.com/glpi-project/glpi/assets/56606032/52ca3558-d640-4f23-94cf-aa63bb8ac16c)

6. Change to the First Entity (the child Entity), and go to Locations:

![image](https://github.com/glpi-project/glpi/assets/56606032/236fa890-2249-4beb-b5cb-7d5bf71a6fbf)

As you can see, I can see the locations, because they are UP in the Parent entity and set Recursively.

7. Open a Location, and see the bug:

![image](https://github.com/glpi-project/glpi/assets/56606032/a5dcfa37-c70e-40f7-b920-0e18bdb48f79)

8. 
9. 

### Anything else?

This impact to Tickets, because Location Field disappear:

![image](https://github.com/glpi-project/glpi/assets/56606032/5bc6ee1e-87fe-463e-afbb-b28df1f937e9)

But If I tried to the Parent Entity this field show up:

![image](https://github.com/glpi-project/glpi/assets/56606032/62ff72ce-c215-4e24-9d6c-1e920617daa0)

**Comment by jcervantes-sipecom** [comment]
the issue is still afecting GLPI.

**Comment by cconard96** [comment]
I confirm the issue. It seems that when you move entities, the ancestor/son cache in $GLPI_CACHE isn't cleared/refreshed. So, when you moved EntityFirst under EntitySecond, it still had only the root entity as a parent/ancestor of EntityFirst. A workaround is to forcibly clear the GLPI cache using the `bin/console cache:clear` command or by going to Setup > General > Performance with debug mode enabled and clicking the "Reset" button under the "User data cache" section.
