### ISSUE TITLE
task in problems are not displayed as ticket

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1576]
Hello

task in problems are not displayed as ticket

![image](https://cloud.githubusercontent.com/assets/15144026/21808046/c8cbc090-d741-11e6-8d75-86a12c2cb12b.png)

![image](https://cloud.githubusercontent.com/assets/15144026/21808054/d91e0aca-d741-11e6-9d7a-a85c81d17029.png)

is it a bug or is it not as ticket

**Comment by boscorelly** [comment]
Tasks of tickets problems are listed in problems, as they are linked.

**Comment by satyan01** [comment]
I talk about the visual, Why is it not like ticket task visual ?

**Comment by boscorelly** [comment]
Oh ok !

I agree with you !

**Comment by satyan01** [comment]
Do you know why ? it is normal ? Do I need to modify something to have the same visual as ticket task ?

**Comment by boscorelly** [comment]
It's "normal" because it is not designed to be like this actualy. 

I have the same as you.

**Comment by satyan01** [comment]
ok thx, waiting for enhancement
