### ISSUE TITLE
[GLPI 10.0.10] Cannot set empty mini dashboard for tickets

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#15776]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.10

### Bug description

Before GLPI 10.0.10 we can set no mini dashboard into preferences : 

![image](https://github.com/glpi-project/glpi/assets/13178158/a1c6090a-7fda-4371-afd1-7a6165ce5cc4)

In GLPI 10.0.10 with this setup, the mini dashboard is still loaded

**Comment by cedric-anne** [comment]
Is this fixed by #15757 ?

**Comment by tsmr** [comment]
Yes ok for me, thanks :)
