### ISSUE TITLE
[GLPI 10.0.10] Cannot add new column into Kanban (Tickets / Problems / changes)

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#15775]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.10

### Bug description

We cannot add new column into Kanban

![image](https://github.com/glpi-project/glpi/assets/13178158/c138047d-d98d-4bc1-9be4-858043fd8424)

![image](https://github.com/glpi-project/glpi/assets/13178158/ace865e6-09db-4055-9fe7-352a6d6a38ee)

**Comment by trasher** [comment]
Please test if #15798 solves your issue

**Comment by tomolimo** [comment]
Hello @trasher 
Yes it does fix the issue :)
Thank you,
Regards,
Tomolimo
