### ISSUE TITLE
Review Ticket::SURVEY right

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#1578]
Implementation seems broken

According to original ticket #340 this new right should only apply to ticket author (right still always granted to requester).

So in central.class.php this part of code have no sense: 

```
         if ($showsurvey) {
            Ticket::showCentralList(0, "survey", false);
         }
```

in showCentralList, "survey" list must be fixed (request criteria)
Ticket::getTabNameForItem
TicketSatisfaction::canUpdateItem
etc...

**Comment by tomolimo** [comment]
linked to #1371
