### ISSUE TITLE
Rules don't work in native GLPI inventory

### ISSUE THREAD

**Issue by sina-4** [glpi-project/glpi#15780]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI-10.0.10

### Bug description

I have been using the Fusion Inventory plugin and had created a rule that changes a computer's entity based on its IP address. However, after upgrading to GLPI 10.0.10 and switching to native GLPI inventory, the rule is no longer functioning correctly. It only seems to work if the computer doesn't already exist in the inventory.
I opened an issue in GLPI-Agent, they told me to post it here. 

### Steps To reproduce

1.Install GLPI-10.0.10
2.Install GLPI-Agent
3.Create a valid rule
4.Create a new computer and assign it to an entity
5.Froce an inventory

### Your GLPI setup information

Expected behavior

The computer’s entity should change according to the rule (Computer's IP adress has changed so that the entity)

### Anything else?

Operating system : Linux
GLPI Agent version : Agent-1.6-gitf83b22f4-x64

**Comment by stonebuzz** [comment]
Hi @sina-4 

Have you authorized the transfer in the destination entity's configuration?

![image](https://github.com/glpi-project/glpi/assets/7335054/fcbe26a1-ed29-4c5d-babc-c0a7b8d7bde7)

**Comment by sina-4** [comment]
No, I haven't! When I authorized the transfer, it is actually working now. Thank you very much for helping me.
