### ISSUE TITLE
Drop-down list dont work (GLPI 10.0.10)

### ISSUE THREAD

**Issue by rafaelscoimbra1** [glpi-project/glpi#15787]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When you access the dropdown page.php you get this error, and the page is blank.

After upgrading from version 10.0.7 to version 10.0.10, any solutions?

![image](https://github.com/glpi-project/glpi/assets/12819634/d9adbe28-058e-4cb8-9907-0600ffae46b9)

**Comment by trasher** [comment]
Pleas eprovide requested information, and try without plugins.

**Comment by rafaelscoimbra1** [comment]
I removed all the files from the glpi directory, and reinstalled version 10.0.10, copying only the necessary folders, without the plugin folders. It solved my problem. Thank you!
