### ISSUE TITLE
Entities problem: Sub-entities not showing

### ISSUE THREAD

**Issue by hsky1672** [glpi-project/glpi#15790]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0.9

### Bug description

I created 2 sub-entities and I only transferred categories to them, but 2 sub-entities have all data like root entities, it seems like they linked root entities. Try to remove them but they're not showing on entities lists

![image](https://github.com/glpi-project/glpi/assets/110877312/9765395c-6281-4481-8814-dbadcd2a8df9)

![image](https://github.com/glpi-project/glpi/assets/110877312/9ac1aaf3-83a1-438c-bd3f-c1f1fa2ba8d6)

any suggestions?

**Comment by cedric-anne** [comment]
Hi,

When new entities are created, you may have to login/logout to see them. This is a known limitation.

**Comment by hsky1672** [comment]
> Hi,
> 
> When new entities are created, you may have to logout/login to see them. This is a known limitation.

Hi,
yes, I did, but not working

**Comment by cedric-anne** [comment]
Please try to upgrade to GLPI 10.0.10.

**Comment by cedric-anne** [comment]
No feedback, I close.
