### ISSUE TITLE
Timeline display on smartphone

### ISSUE THREAD

**Issue by yatar** [glpi-project/glpi#158]
I have a display problem with timeline display on smartphone, i don't see all information

![screenshot_2015-10-09-09-28-27](https://cloud.githubusercontent.com/assets/15038264/10388302/fd08c846-6e68-11e5-80ed-a1db75a65747.png)
![screenshot_2015-10-09-09-29-05](https://cloud.githubusercontent.com/assets/15038264/10388301/fcdf7cc0-6e68-11e5-818c-b515e8ce757c.png)

**Comment by orthagh** [comment]
It should be better (not perfect)
