### ISSUE TITLE
The translation in the ticket categories does not work

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15801]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.10

### Bug description

I have created a category under Setup > Dropdowns > ITIL categories with a description of the category in the comment field. There was also an English translation added under Translations but it doesn't work. if I set GLPI to English the text in the comments stays on the German version.

Here are a few example images

![image](https://github.com/glpi-project/glpi/assets/115316656/026141fb-5d04-4e21-b0d8-77c921539acd)

English translation created

![image](https://github.com/glpi-project/glpi/assets/115316656/3acc3fc6-fa87-42ef-b70b-7e2b1084c661)

Glpi changed to English

![image](https://github.com/glpi-project/glpi/assets/115316656/cdcce283-16b5-422e-a4ff-0f61e3eaf542)

Comments are still in German

As described in ticket #15180, the subcategories also disappear in the dropdown lists where a translation has been inserted.

![image](https://github.com/glpi-project/glpi/assets/115316656/1a80a89a-1c88-4cab-92f6-73b3349f883c)
![image](https://github.com/glpi-project/glpi/assets/115316656/0bc130e4-1193-4378-8c24-1d9f0241e16e)

To do this, simply set GLPI to the language in which the translation was created.

**Comment by cconard96** [comment]
I cannot recreate the issue. Do you have the translation of dropdowns enabled in Setup > General on the General setup tab?

**Comment by cconard96** [comment]
I confirm. It seems that if I add a name translation the complete name is generated properly along with it. If I then add a translation for the comments, the complete name translation in the DB is suddenly empty.
