### ISSUE TITLE
queuednotification error

### ISSUE THREAD

**Issue by wessrafamessi** [glpi-project/glpi#15802]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.6

### Bug description

Hello,

I have encountered an issue regarding the email notifications for tickets. The automatic action "queuednotification" is not functioning as expected, which means that I have to execute it manually to clear the notification queue.

I would appreciate your assistance in resolving this issue, if possible.

Best regards

**Comment by trasher** [comment]
10.0.6 is outdated, upgrade to latest stable release and see if you reproduce. If you do reproduce, feel free to open an issue with **all requested information**.
