### ISSUE TITLE
Software Category Rules not triggering on GLPI Agent inventory import

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#15806]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Software Rules do not appear to be working for us.

We have tried GLPI Agent 1.5 and 1.6 (nightly) on two different Windows machines as our test clients.

In GLPI, we have created a Software Rule ("_Rules for assigning a category to software_") which simply does the following:

IF
Software exists = Yes
THEN
Category Assign to testcategory

'testcategory' exists as a software category.

We then run a clean GLPI inventory on the client. All the software gets pulled into GLPI, however it gets put into other software categories which never existed on our GLPI, such as 'application', 'system', etc.

If we select all the imported software and run the mass change to "Recalculate Rules", the rules work okay.

This appears to just be scratching the surface of issues with the Software Rules, as upon further testing, no amount of rule experimentation appears to do anything, leading us to believe that the Software Rules never trigger upon any inventory/asset import.

Are we misunderstanding how Software Rules are supposed to be used? It seems to us like they are just broken and a bug exists.

Very grateful for any feedback.

Kind regards,

EJ

### Relevant log output

Nothing relevant appears to log in the Apache or PHP logs.

### Page URL

https://glpi.my-domain.local/front/rule.php

### Steps To reproduce

1. Create Software Rule:
IF
Software exists = Yes
THEN
Category Assign to testcategory
2. Import new inventory
3. Observe that rule has not applied

### Your GLPI setup information

Operating system: Linux g000077 4.18.0-372.16.1.el8_6.0.1.x86_64 #​1 SMP Thu Jul 14 21:39:58 UTC 2022 x86_64
PHP 7.4.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sodium, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="-1" memory_limit="2G" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="25M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.6.12-MariaDB-log
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi-rw@it-db-server-2.hayley-group.local/glpi_it
	Host info: it-db-server-2.hayley-group.local via TCP/IP
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/helpdesk.my-domain.local/files/_cache has been validated.
Write access to /var/www/helpdesk.my-domain.local/config has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_cron has been validated.
Write access to /var/www/helpdesk.my-domain.local/files has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_dumps has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_graphs has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_lock has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_pictures has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_plugins has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_rss has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_sessions has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_tmp has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/helpdesk.my-domain.local/marketplace has been validated.
Timezones seems loaded in database.

**Comment by hgpit** [comment]
@keguira To be honest, we had similar suspicions. But it doesn't make sense.
For instance, there is a criteria in the rules for 'Category from inventory tool' which implies that it should/can be used during import.
![image](https://github.com/glpi-project/glpi/assets/16598973/213bb580-e3f4-4f18-871e-35cf098ffa85)

And also, I don't see why you would need Software Category Rules once the data is already imported, because you have access to mass changes at that stage.

It would be great if we could get an official response on this, to clear it up.

**Comment by hgpit** [comment]
Also, as my colleague has just reminded me, we're pretty sure during all our testing that the Software Category Rules **_do_** apply during inventory import for **_only_** against Operating Systems. So, yeah, it just sounds like a confused feature, LOL.

**Comment by hgpit** [comment]
According to GLPI's own documenation: https://glpi-user-documentation.readthedocs.io/fr/latest/modules/administration/rules/rulesmanagement.html

"Classification by category makes it easier to display and find software. **This can be done automatically for any new software, or retroactively.** The available criteria are the publisher, the name and the comment of the software. The only possible action is to assign software to a category. It is possible to replay the rules from the software list, using massive action Recalculate category."

We read "automatically" as via inventory.

**Comment by cconard96** [comment]
The GLPI documentation in this part is from before the addition of the native inventory feature/GLPI Agent in GLPI. In this case "automatically" just means whenever a software is created, the category assignment rules should run for it.

**Comment by hgpit** [comment]
It still seems "broken" that the category rules work on Operating Systems which import via Inventory, but they don't work on actual applications. There seems to be no consistency or it's a half-implemented feature.
