### ISSUE TITLE
Software dictionary rules don't complete all actions

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#15818]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Software Dictionary rules doen't perform all defined actions during import.

### Relevant log output
Nothing posted in Apache or PHP logs that I can see

### Steps To reproduce

1. Create Software Dictionary rule:
![image](https://github.com/glpi-project/glpi/assets/16598973/9686def8-9cd1-4ae8-94ad-92b4fee03863)
3. Run inventory/import from suitable GLPI Agent client
4. Check GLPI software asset database to see that the Software name gets changed, but the the category reassignment and publisher change is ignored:
![image](https://github.com/glpi-project/glpi/assets/16598973/3c1539ae-9a4a-4cb8-a2bc-ad667df2573d)

### Your GLPI setup information

Operating system: Linux g000077 4.18.0-372.16.1.el8_6.0.1.x86_64 #​1 SMP Thu Jul 14 21:39:58 UTC 2022 x86_64
PHP 7.4.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sodium, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="-1" memory_limit="2G" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="25M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.6.12-MariaDB-log
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi-rw@it-db-server-2.my-domain.local/glpi_it
	Host info: it-db-server-2.my-domain.local via TCP/IP
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/helpdesk.my-domain.local/files/_cache has been validated.
Write access to /var/www/helpdesk.my-domain.local/config has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_cron has been validated.
Write access to /var/www/helpdesk.my-domain.local/files has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_dumps has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_graphs has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_lock has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_pictures has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_plugins has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_rss has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_sessions has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_tmp has been validated.
Write access to /var/www/helpdesk.my-domain.local/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/helpdesk.my-domain.local/marketplace has been validated.
Timezones seems loaded in database.

**Comment by stonebuzz** [comment]
Hi @hgpit 

can you post here related inventory file et rules dictionnaries (you can export them from GLPI)?

Best regards

**Comment by hgpit** [comment]
By the way, I don't believe the issue is with the specific rule and it appears to exhibit the same behaviour on any other rules we test.
For instance:
![image](https://github.com/glpi-project/glpi/assets/16598973/64f985b6-3a1f-46c8-9c22-7b1d71aef0d2)
ACTION 'A' takes place, but ACTION 'B' is ignored/skipped/missed.

**Comment by stonebuzz** [comment]
I think I've found it,
your inventory file already contains an "Acronis Cyber Protect" software.

```json
{
            "arch": "x86_64",
            "from": "registry",
            "guid": "9EBDE6F5-EAE6-4326-A3A1-DEAA29F32D1D_BackupAndRecovery",
            "install_date": "2023-10-16",
            "name": "Acronis Cyber Protect",
            "publisher": "Acronis",
            "system_category": "application",
            "uninstall_string": "C:\Program Files\Common Files\Acronis\BackupAndRecovery\AcronisUninstaller.exe",
            "version": "15.0.36514"
         },
```
and you try to transform this one

```json
{
            "arch": "x86_64",
            "from": "registry",
            "guid": "{C3C08FBE-639E-4453-963C-0959CF18D60C}",
            "install_date": "2023-10-16",
            "name": "Cyber Protect",
            "publisher": "Acronis",
            "system_category": "system_component",
            "uninstall_string": "MsiExec.exe /X{C3C08FBE-639E-4453-963C-0959CF18D60C}",
            "url_info_about": "https://www.acronis.com",
            "version": "15.0.36514"
         },
```json

Like the first one, 

which prevents GLPI from doing its reconciliation job properly

It does change the name, but when it comes to processing the category and publisher, it's the first one that's processed. 

can you adapt your rule (with other values for categorie / name / publisher) to see if GLPI correctly handles "Cyber Protect"?

You'll need to remove the two "Acronis Cyber Protect" softwares to start again from a "clean" base.

Best regards

**Comment by stonebuzz** [comment]
Just delete both acronis software , and adapt rule to see if glpi handle correctly cyber protect soft when glpi dictionnary update it with another name

**Comment by hgpit** [comment]
So, there are two software version entries in our live GLPI which appear to have been introduced automatically via inventory:
![1](https://github.com/glpi-project/glpi/assets/16598973/30188803-4012-42f5-af72-f7ca1ac91795)
I Deleted A and B, leaving me with:
![2](https://github.com/glpi-project/glpi/assets/16598973/03980fd1-371c-49f7-94ec-0a49f0f78c4a)
I then re-ran the inventory:
![image](https://github.com/glpi-project/glpi/assets/16598973/9fe48757-3ad0-4d94-b1b8-132668b33aa7)
So, yes, it appears that the first qualifying software item in the inventory gets renamed (name and publisher) and [possibly] assigned to the correct category. Then on the second qualifying entry there is no match, as the rule is looking for just 'Cyber Protect'. So that is starting to make sense. I am going to create another rule (or regexp the existing rule) to hopefully catch both. and see what happens.

**Comment by hgpit** [comment]
I will post an update on our finding ASAP, unfortunately I got tied up with other commitments. Hoping to get back to this very soon.
