### ISSUE TITLE
Bug in the translation of ITIL categories

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15810]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.10

### Bug description

I have created ticket categories that have subcategories. In the categories, I wrote short descriptions in German. After I subsequently created translations into English, the subcategories were no longer displayed in the drop-down selection lists. In German, the display worked as usual, but in English, I could no longer see the categories with the translated descriptions.

![image](https://github.com/glpi-project/glpi/assets/115316656/2a38e911-37f5-4a2f-8a47-dcea2ceac75d)
![image](https://github.com/glpi-project/glpi/assets/115316656/dd2dd98d-037b-41ac-aa2c-de89e3ac37a5)

### Steps To reproduce

1. set the language to e.g. German 
2. go to a ticket category and create a translation in English 
3. set the language of GLPI to English and go to ticket creation 
4. when selecting the category, the categories with translation should be hidden.

But works only with subcategories like mine with Hardware > Phone. The Phone should then be hidden.

**Comment by trasher** [comment]
duplicates #15801
