### ISSUE TITLE
[10.0.10] location import from LDAP / AD annuary

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#15812]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.10

### Bug description

in 10.0.6 when you imported your locations from ldap (with a value containing location 1 > location2), the hierarchy was recreated in GLPI

in 10.0.10 GLPI no longer creates the hierarchy and creates a duplicate (With  location 1 > location2 into field name)

**Comment by tsmr** [comment]
Introduced by 

https://github.com/glpi-project/glpi/commit/94b42081a9ef34d0524e9173de1c878545c08ff3#diff-4dcbc11d713678e97f70f2321527d825e6e8fc5f6c4f541ee485a050da120f8dL1906

**Comment by cedric-anne** [comment]
@tsmr 

Please try #15815.
