### ISSUE TITLE
some &#60; ... &#62; in fields

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi#15822]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Some "&#60; ... &#62;" in fields 

I compared tasktemplates (i have the same thing in other tables) ; 
I compare these 2 tables between 9.5 and 10.0.10 : 
- in 9.5 : &lt;p&gt;Changement - Envoi information&lt;/p&gt;
![image](https://github.com/glpi-project/glpi/assets/42341169/4683284c-4535-409f-88a0-1da5f694e38d)

- in 10.0.10 : &#60;p&#62;Changement - Envoi information&#60;/p&#62;
![image](https://github.com/glpi-project/glpi/assets/42341169/fea7e682-283f-450c-b7ef-217aed1e7366)

Is this normal ? Did I forget something when migrating ?

or is it a 'wrong' page code to update ?
Thanks

**Comment by trasher** [comment]
Is there an issue GLPI side?

**Comment by EC2311** [comment]
No issue, no log
I remarked that when testing the changes I created using formcreator, and some fields (impactcontent , rolloutplan backoutplancontent and checklistcontent) are fields wxith that
![image](https://github.com/glpi-project/glpi/assets/42341169/51bfa99f-0772-4559-bd6f-535727ba7177)
and before it was blank
![image](https://github.com/glpi-project/glpi/assets/42341169/5dbd69cd-1faf-42d9-89d5-35c7120def92)

**Comment by EC2311** [comment]
> Encoding of special chars has changed a little in GLPI 10.0. This should not affect end users.

you mean : the fields have been converted from utf8_unicode_ci to utf8mb4_unicode_ci ?

**Comment by cedric-anne** [comment]
> No issue, no log I remarked that when testing the changes I created using formcreator, and some fields (impactcontent , rolloutplan backoutplancontent and checklistcontent) are filled with that ![image](https://user-images.githubusercontent.com/42341169/276242916-51bfa99f-0772-4559-bd6f-535727ba7177.png) and before it was blank ![image](https://user-images.githubusercontent.com/42341169/276243068-5dbd69cd-1faf-42d9-89d5-35c7120def92.png)

OK, so your real issue is probably this. We can now try to reproduce.


> > Encoding of special chars has changed a little in GLPI 10.0. This should not affect end users.
> 
> you mean : the fields have been converted from utf8_unicode_ci to utf8mb4_unicode_ci ?

See #8763 for a technical explaination.

**Comment by cedric-anne** [comment]
Can you please give all requested information, related to your issue (howw to reproduce, GLPI system information, ...)?

**Comment by trasher** [comment]
Well, if issue is from a plugin usage, it may be in plugin only. 

Such issues - that are not issues but questions - but there is maybe an issue somewhere - no one knows - are a waste of time. 

Please provide a way to reproduce you r issue, without using a plugin.

**Comment by EC2311** [comment]
without plugin : 
- just after migration : ie tasktemplates (perhaps other tables ?) are not filled with the same content
 in 9.5 
![image](https://github.com/glpi-project/glpi/assets/42341169/6e33c0b8-2d2b-4dc9-b24a-64d0136288c2)
in 10.0.10
![image](https://github.com/glpi-project/glpi/assets/42341169/fa29f8a3-f92f-4928-90f4-58587b1b3789)

If I create a change (without plugin)
in v9.5 : column impact
![image](https://github.com/glpi-project/glpi/assets/42341169/ab305c3e-cf39-4f6c-9d4f-cded8eb39600)
in v10.0.10 : column impactcontent
![image](https://github.com/glpi-project/glpi/assets/42341169/55ce2bf0-6353-4ed9-8e1c-80905ee8c278)

if at sight, it seems ok, it's not the case, and some script may be impacted (if searching some value in columns)

**Comment by cedric-anne** [comment]
Is there an issue on end-user side? I guess your users are not reading the database directly...

**Comment by EC2311** [comment]
ok for closure.
Indeed, at user's sight, no problem, but it's more for scripts ;)

thanks

**Comment by trasher** [comment]
No script should use database directly, GLPI API is done for that kind of uses. There are lots of chances you break something trying to use DB directly.
