### ISSUE TITLE
Global search don't display printers if search in the fields Serial number and Inventory number

### ISSUE THREAD

**Issue by novalenik** [glpi-project/glpi#1582]
GLPI 9.1.1
Devices search, printers don't search.

**Comment by trasher** [comment]
None of devices or printer is searching in serial or inventory number. Search is done on name and completename fields only; for both of them.

**Comment by novalenik** [comment]
It's SQL request for Devices in GLPI debug mode.
![2017-01-19_09-15_glpi](https://cloud.githubusercontent.com/assets/24838637/22093606/e44f51fe-de28-11e6-9a62-119910c1094b.jpg)
Then SQL request for Printers in GLPI debug mode
![2017-01-19_09-21_glpi](https://cloud.githubusercontent.com/assets/24838637/22093625/15d4f166-de29-11e6-8e0e-2198773b83ee.jpg)
Devices have serial and otherserial fields in sql request.
