### ISSUE TITLE
The watcher is automatically added to the request in support and cannot be canceled.

### ISSUE THREAD

**Issue by tojeroman** [glpi-project/glpi#15820]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

The Watcher is automatically added to the support request and cannot be canceled. If I download requests using IMAP, a watcher is always added to the requests with the email address of the email sender in the global settings, and it is not possible to cancel this addition of the email address to the watcher.

**Comment by cedric-anne** [comment]
Hi,

Each recipient of the collected email is added to the watchers. You can prevent a recipient to be added to observers by adding its email to the email blacklist (from `/front/blacklist.php` page).

**Comment by tojeroman** [comment]
> Hi,
> 
> Each recipient of the collected email is added to the watchers. You can prevent a recipient to be added to observers by adding its email to the email blacklist (from `/front/blacklist.php` page).

Thank you, it solved the problem, I don't know if it's the right way to set it up, but now my emails go to the GLPI administrator's email again :(
