### ISSUE TITLE
Block description field once ticket is created.

### ISSUE THREAD

**Issue by calidadcarm** [glpi-project/glpi#15832]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.11 - 10.0.x

### Bug description

New functionality

Regarding the functionality in GLPI, once a request is created, the description field of a ticket is blocked once said ticket is created.

1 - Is this functionality already available for future versions of GLPI 10?

2 - Or if not, will it be implemented for future versions?

We'll await for further news.

All the best.

### Anything else?

New functionality implemented for GLPI or future versions.

**Comment by cedric-anne** [comment]
Hi,

This feature is not in our roadmap yet.
