### ISSUE TITLE
[GLPI 9.1.1] 404 error page on dropdowns

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#1583]
Process : 

Go on glpi/front/dropdown.php
Select Locations on dropdown
You are redirected to /front/location.php : OK
In the same dropdown, select Empty value

![image](https://cloud.githubusercontent.com/assets/13178158/21842943/4be1fdb2-d7e9-11e6-8302-b1136d528f10.png)

 
Error : 
You are redirected to :  The requested URL /glpi/front/0 was not found on this server.

**Comment by trasher** [comment]
I remember a very similar issue has been posted recently

**Comment by trasher** [comment]
OK, I had #1473 in mind, but it is not reproducible, so there is nothing interesting to grab.
