### ISSUE TITLE
 Warning (512): Invalid relations declared for "glpi_ticketcategories" table. Table does not correspond to a known itemtype.

### ISSUE THREAD

**Issue by NeueMedienBecker** [glpi-project/glpi#15848]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.10

### Bug description

 Warning (512): Invalid re
[2023-10-23 10:22:44] glpiphplog.WARNING:   *** PHP User Warning (512): Invalid relations declared for "glpi_ticketcategories" table. Table does not correspond to a known itemtype. in /home/users/glpi/www/src/DbUtils.php at line 2064
  Backtrace :
  src/DbUtils.php:2064                               trigger_error()
  inc/db.function.php:585                            DbUtils->getDbRelations()
  src/CommonDBTM.php:866                             getDbRelations()
  src/CommonDBTM.php:788                             CommonDBTM->cleanRelationData()
  src/CommonDBTM.php:2068                            CommonDBTM->deleteFromDB()
  src/CommonDBTM.php:4631                            CommonDBTM->delete()
  ...ace/glpiinventory/install/update.native.php:700 CommonDBTM->deleteByCriteria()
  marketplace/glpiinventory/hook.php:405             pluginGlpiinventoryUpdateNative()
  src/Plugin.php:915                                 plugin_glpiinventory_install()
  :                                                  Plugin->install()
  src/Marketplace/Controller.php:545                 call_user_func()
  src/Marketplace/Controller.php:435                 Glpi\Marketplace\Controller->setPluginState()
  ajax/marketplace.php:82                            Glpi\Marketplace\Controller->installPlugin()
  public/index.php:82                                require()
lations declared for "glpi_ticketcategories" table. Table does not correspond to a known itemtype.

**Comment by cedric-anne** [comment]
Hi,

The `glpi_ticketcategories` table does not exists anymore. The only reference to it I found is inside the `resources` plugin.
Issue has already be reported on the plugin, as you already know (see https://github.com/InfotelGLPI/resources/issues/123).

We cannot do anything about it in GLPI.
