### ISSUE TITLE
Mailgate reply to change assigned to ticket

### ISSUE THREAD

**Issue by troloff** [glpi-project/glpi#15859]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

For changes, there seems to be no followup possible via mailgate.

I configured notifications for changes and E-Mails are sent out.

However, if I include the ##change.title## tag in the template subject, the subject contains something like
[GLPI `#0000006`] <change title>

`#0000006` is obviously the change id, however, if someone answers this mail, the reply isn't assigned to the change.
- if there is no ticket `#0000006`, a new ticket is created
- if there is a ticket `#0000006`, the reply to the change is (probably) assigned to the (wrong) ticket.

It would be great to have a way to assign replies to changes via mailgate, e.g. via a separate tag like [GLPI-Change `#0000006`]

### Steps To reproduce

1. configure mail notification for changes, e.g. notification on new change
2. include ##change.title## in mail subject
3. answer mail
4. new ticket is created, answer is not linked to change (probably gets linked to wrong ticket, if ticket with same id like change exists)

**Comment by ftoledo** [comment]
i confirm this

**Comment by ftoledo** [comment]
related to #14581 ?

**Comment by ftoledo** [comment]
any update? mailgate wont support reply change..but i have a glpi with mailcolletor patched that process reply for changes.. i still have some issues but almost work

**Comment by troloff** [comment]
Fernando, that sounds promising.

From my point of view, it looks like changes and problems were added as additional "flavours" of tickets. We have same fields, e-Mail-notifications etc. But it was somehow forgotten to implement the mailgate functionality.

I mean, if glpi is capable of *sending* change/problem notifications via e-Mail, it should be able to handle replies to those mails.

Thanks a lot for your work,
Torsten

________________________________________
Von: Fernando Toledo ***@***.***>
Gesendet: Dienstag, 12. Dezember 2023 21:59
An: glpi-project/glpi
Cc: Roloff, Torsten; Author
Betreff: [ext] Re: [glpi-project/glpi] Mailgate reply to change assigned to ticket (Issue #15859)

any update? mailgate wont support reply change..but i have a glpi with mailcolletor patched that process reply for changes.. i still have some issues but almost work

**Comment by ftoledo** [comment]
@troloff see this PR from ticgal https://github.com/glpi-project/glpi/pull/15789
