### ISSUE TITLE
Search in API cannot use field "name" for "equals" searchtype

### ISSUE THREAD

**Issue by support-ATE** [glpi-project/glpi#1586]
Hello,

After a few tries and some help in the IRC channel, it appears that : 

/search/Computer?criteria[0][field]=1&criteria[0][searchtype]=contains&criteria[0][value]=servername

will return matches (so servername01, servername02), but 

/search/Computer?criteria[0][field]=1&criteria[0][searchtype]=equals&criteria[0][value]=servername01

will not return results.

The only way to get a server with its exact name is : 

/search/Computer?criteria[0][field]=1&criteria[0][searchtype]=contains&criteria[0][value]=^servername$

Additionally, the fact that we can use ^ and $ (but no other regex symbols as it seems) is not documented in the API doc.

**Comment by trasher** [comment]
Hello,

The use of `^` and/or `$` is not part of the API documentation since it's not only related to the API. This is explained in GLPI user documentation.

**Comment by trasher** [comment]
The comportement you point out is correct; but we should drop a line in the docs for that.

**Comment by orthagh** [comment]
CF https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/search.class.php#L3188-L3192
