### ISSUE TITLE
Having some problems with contracts!

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#15893]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

I would like to record my contracts in GLPI, but am having some problems doing so:

Contract term:

The service contract is concluded for a term of 3 years. The term of the service contract is extended for another year at a time, unless it has been terminated by the contract partner with a notice period of 3 months before the end of the respective service contract year.

My interpretation of the contract term:

The contract should therefore be created as follows:

Start Date: 2020-08-01
Initial contract period: 36 months (for the first 3 years, I would have specified the 36 months here)
Notice: 3 months (I would like to be notified 3 months before the end)
Contract renewal period: 12 months (after the 3 years, the contract will be renewed annually)
Renewal: Tacit

Problems:

In the initial contract period I now have an end date of 2026-08-01, although I would actually expect to have an end date after the first 3 years, which in this case is 2023-08-01, and then with the contract renewal period the contract is renewed by one year each time.

The notice field is also not working correctly. I entered 3 months there and now have a date of 2023-05-01, although if I had an end date of 2026-08-01, I would not expect to have a date of 2026-05-01 until again.

Question:

Am I not understanding the function of the fields correctly or is something being calculated incorrectly here?

**Comment by cedric-anne** [comment]
Hi,

It duplicates #14703, I guess.
