### ISSUE TITLE
Rich text field in Change Templates

### ISSUE THREAD

**Issue by jairockman** [glpi-project/glpi#15928]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10 and Cloud

### Bug description

When I create a Change, Analysis Impacts, Control List, Backup Plans, Deployment Plan, Checklist, allow me to use the "Rich text field" so I can use it to format the text.

But when I create a Change template, these fields don't allow me to use "Rich text field" just plain text.

### Page URL

/front/changetemplate.form.php

**Comment by cconard96** [comment]
Fixed by #15726. It will be in GLPI 10.0.11.
