### ISSUE TITLE
[GLPI 9.1.1] TicketValidation::CREATEDEMAND is declared nowhere!!!

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1592]
Hello,

If you try to search for ticket on Ticket Approval - Requester field on ticket.php you get an error message:

> Uncaught Error: Undefined class constant 'CREATEDEMAND' in C:\inetpub\wwwroot\glpi091\inc\user.class.php:3032
> 
> Stack trace:
> 
> #0 C:\inetpub\wwwroot\glpi091\ajax\getDropdownUsers.php(94): User::getSqlSearchResult(false, Array, Array, 0, Array, '', 0, 200)
> 
> #1 {main}

I searched in the complete GLPI tree, and I cannot find this constant.

Regards,
Tomolimo

**Comment by trasher** [comment]
Sounds like it has been added here:
https://github.com/glpi-project/glpi/commit/55595ab314d96288af1eb1d8d60ac784cf4579a2#diff-a9c4448deb6265f035355e2a9ca92bc0R2881

But I can't find any declaration of that constant, guess the line should be removed.
