### ISSUE TITLE
Erro with  "php bin/console db:check_schema_integrity" command

### ISSUE THREAD

**Issue by okba6z** [glpi-project/glpi#15933]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.7

### Bug description

php bin/console db:check_schema_integrity
Checking the integrity of the database is not supported for the version "10.0.7@5d45269702917a32805XXXXXXXXXXX9a98b145f6"

### Steps To reproduce

SSh command: php bin/console db:check_schema_integrity

### Your GLPI setup information

Operating system: Linux cre-vsupport1 5.10.0-21-amd64 https://github.com/glpi-project/glpi/issues/1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 8.1.25 fpm-fcgi (Core, FFI, PDO, PDO_Firebird, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2,
calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json,
ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_dblib, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix,
readline, session, shmop, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader,
xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M"
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at xxxxxxxxxxxxxxxx Port 80
)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Server Software: Debian 11
Server Version: 10.5.21-MariaDB-0+deb11u1
Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
Parameters: axxxxxxx/xxxx
Host info: Localhost via UNIX socket

PHP version (8.1.25) is supported.PHP version (8.1.25) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.21) is supported.Database engine version (10.5.21) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/files/_cache has been validated. Write access to /var/www/html/config has been validated. Write access to /var/www/html/files/_cron has been validated. Write access to /var/www/html/files has been validated. Write access to /var/www/html/files/_dumps has been validated. Write access to /var/www/html/files/_graphs has been validated. Write access to /var/www/html/files/_lock has been validated. Write access to /var/www/html/files/_pictures has been validated. Write access to /var/www/html/files/_plugins has been validated. Write access to /var/www/html/files/_rss has been validated. Write access to /var/www/html/files/_sessions has been validated. Write access to /var/www/html/files/_tmp has been validated. Write access to /var/www/html/files/_uploads has been validated.Write access to /var/www/html/files/_cache has been validated.
Write access to /var/www/html/config has been validated.
Write access to /var/www/html/files/_cron has been validated.
Write access to /var/www/html/files has been validated.
Write access to /var/www/html/files/_dumps has been validated.
Write access to /var/www/html/files/_graphs has been validated.
Write access to /var/www/html/files/_lock has been validated.
Write access to /var/www/html/files/_pictures has been validated.
Write access to /var/www/html/files/_plugins has been validated.
Write access to /var/www/html/files/_rss has been validated.
Write access to /var/www/html/files/_sessions has been validated.
Write access to /var/www/html/files/_tmp has been validated.
Write access to /var/www/html/files/_uploads has been validated.

### Anything else?

I wanted to upgrade to 10.0.10

**Comment by trasher** [comment]
It's already been reported, please search on existing tickets.

**Comment by okba6z** [comment]
I am sorry. It was probably my mistake I removed the entire install directory instead of only intall.php.

I put back the install directory and removed only install.php after that It seems to be all right.

But now when I try the "php bin/console db:check_schema_integrity" command:
`root@cre-vsupport1:/var/www/html# php bin/console db:check_schema_integrity
The schema differs for the table"glpi_slms".
--- Expected database schema
+++ Current database schema
@@ @@
 CREATE TABLE `glpi_slms` (
   `id` int NOT NULL AUTO_INCREMENT,
-  `calendars_id` int NOT NULL DEFAULT 0,
+  `calendars_id` int,
   `comment` text,
   `date_creation` datetime,
   `date_mod` datetime,`

how to resolve this

thanks for help

**Comment by okba6z** [comment]
Hi
Always need help
thanks
