### ISSUE TITLE
LDAPS Issue with Linux and Apache (related to issue #15941)

### ISSUE THREAD

**Issue by ciosz** [glpi-project/glpi#15949]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0

**Comment by s0p4L1n3** [comment]
My previous [ISSUE](https://forum.glpi-project.org/viewtopic.php?id=289689)

You can use LDAPS and Use Bind = Yes, but you have to specify `ldaps://` in the server field
It gave me a big reminder to RTFM

# LDAPS NOT WORKING

<img width="1066" alt="not_working_ldaps" src="https://github.com/glpi-project/glpi/assets/126569468/5c8f3204-5762-40db-87ae-454de68d83cf">


# LDAPS WORKING


<img width="1068" alt="working_ldaps" src="https://github.com/glpi-project/glpi/assets/126569468/5b108d4e-89de-42ef-9e4a-0a49046b19de">
