### ISSUE TITLE
Problems - page title

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#1594]
GLPI 9.1.1

The page title is GLPI - Problems - $problemID$

It should be the problem title no ?

**Comment by boscorelly** [comment]
To be more precise, it appears as "GLPI - Problems - 4" for exemple.
Maybe it is not a bug and it is wanted as it :)

**Comment by trasher** [comment]
It is the same for tickets, and I guess for changes as well. I do not know if it was designed as it... @orthagh?

**Comment by trasher** [comment]
OK, this is not an issue. This is the default title displayed if nothing has been specified; but I guess this can be improved a bit.

**Comment by orthagh** [comment]
> I do not know if it was designed as it... 

It was.
in fact, it's pretty easy to append id to title (retrieved in the GET parameter) but not for the title (we need to instanciate the object).

**Comment by boscorelly** [comment]
thanks :)
so, it must be done in tickets too if modified here :)
it is not important and can be updated in 9.2
