### ISSUE TITLE
LDAPS issue

### ISSUE THREAD

**Issue by aaaaaaaaaaaaaaaffff** [glpi-project/glpi#15941]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

No LDAPS is working on IIS/Windows server 2022/PHP 8.2.12.
The LDAP connection is working well with LDAP, but not with LDAPS

### Steps To reproduce

With IIS 10 on windows server 2022, PHP 8.2.12, the LDAPS is not working at all

### Your GLPI setup information

GLPI 10.0.10 ( => C:\inetpub\glpi)
Installation mode: TARBALL
Current language:en_GB

Operating system: Windows NT SRVGLPI01 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.12 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	random, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.35
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.2.12) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\inetpub\glpi/files/_cache has been validated.
Write access to C:\inetpub\glpi/config has been validated.
Write access to C:\inetpub\glpi/files/_cron has been validated.
Write access to C:\inetpub\glpi/files has been validated.
Write access to C:\inetpub\glpi/files/_dumps has been validated.
Write access to C:\inetpub\glpi/files/_graphs has been validated.
Write access to C:\inetpub\glpi/files/_lock has been validated.
Write access to C:\inetpub\glpi/files/_pictures has been validated.
Write access to C:\inetpub\glpi/files/_plugins has been validated.
Write access to C:\inetpub\glpi/files/_rss has been validated.
Write access to C:\inetpub\glpi/files/_sessions has been validated.
Write access to C:\inetpub\glpi/files/_tmp has been validated.
Write access to C:\inetpub\glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

**Comment by udi8** [comment]
Hi,
i'm facing the same issue, any update on this?

**Comment by ciosz** [comment]
Hi,

Facing the same issue here. 

GLPI test seems to work when using : "Use Bind = no" 

But it does'nt work when we set it on yes.

**Comment by aaaaaaaaaaaaaaaffff** [comment]
Hello,
I found how to do. You need to add the root certificate in .pem (export it with Firefox), rename it as "cert.pem" and add it in  C:\Program Files\Common Files\SSL. Restart the IIS and the ldap connection with bind enabled will be okay

**Comment by cedric-anne** [comment]
I close this issue as it seems to be a system issue, not a GLPI one.

**Comment by s0p4L1n3** [comment]
My previous [ISSUE](https://forum.glpi-project.org/viewtopic.php?id=289689)

You can use LDAPS and Use Bind = Yes, but you have to specify `ldaps://` in the server field
It gave me a big reminder to RTFM

# LDAPS NOT WORKING

<img width="1066" alt="not_working_ldaps" src="https://github.com/glpi-project/glpi/assets/126569468/5c8f3204-5762-40db-87ae-454de68d83cf">


# LDAPS WORKING


<img width="1068" alt="working_ldaps" src="https://github.com/glpi-project/glpi/assets/126569468/5b108d4e-89de-42ef-9e4a-0a49046b19de">
