### ISSUE TITLE
Update rule in Bussiness Rules for Ticket is not working

### ISSUE THREAD

**Issue by blackpearl-2022** [glpi-project/glpi#15955]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hi,
I am currently utilizing the most recent version of GLPI, version 10.0.10, on an Ubuntu server  Ubuntu 22.04.2 LTS with PHP 8.2.12 (cli) (built: Oct 26 2023 17:33:49). In line with our needs, I endeavored to establish an update rule for tickets. My goal was to automatically allocate the technical group to a service request ticket generated by a user after receiving approval from their manager.

The request for the approval rule was operational, intended to activate upon ticket creation. But the update rule which was to be triggered upon the manager approve the request.

I am sharing the screenshots of the process and the ticket creation flow .

The update rule is as below :-  

![7](https://github.com/glpi-project/glpi/assets/118801689/c45b14d1-29d6-4243-a90c-b2329aa74a34)

![6](https://github.com/glpi-project/glpi/assets/118801689/8b9e6a01-f468-45ec-9139-2fc1e49bb071)

![5](https://github.com/glpi-project/glpi/assets/118801689/2da226b6-cdaf-4d8c-9890-9ad748ca7cd5)

The ticket created and the approved screen shots are as below :- 

1. Creating the request ticket 

![2](https://github.com/glpi-project/glpi/assets/118801689/4040ff2f-6016-4e2d-8a9c-8f62ab250ba4)

2. After creating ticket the validation request is sent to his manager 
![1](https://github.com/glpi-project/glpi/assets/118801689/d6635123-3616-4f1d-aa99-d0e69bb72020)

3. The automated request sent by ES to his manager is approved 

![4](https://github.com/glpi-project/glpi/assets/118801689/acec85e5-f27b-4db2-98ed-64da80cc0321)

![3](https://github.com/glpi-project/glpi/assets/118801689/ca254e1f-5d9f-4c06-9892-e16c1eb3246d)

Following the approval as per the rule, the task was supposed to be assigned to the Network_team group, and the ticket status was expected to change to "processing (assigned)." However, this process was not functioning as expected.

Based on the documents, I comprehend that the business rule update is designed to trigger when a field in the ticket is modified. In the described situation, the approval field is altered to 'granted.' However, this specific change is not being detected by the rule. The rule is activated successfully when the test is conducted.

I suspect this might be a type of bug. 

    

### Your GLPI setup information

GLPI 10.0.10 ( => /xxxxx/xxxxx/glpi)
Installation mode: TARBALL
Current language:en_US

Operating system: Linux xxxxxx-sv05 5.15.0-87-generic #​97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023 x86_64
PHP 8.1.18 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at xxxxx.com
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Server Software: Ubuntu 22.04
	Server Version: 10.6.12-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxxxxxxx
	Host info: Localhost via UNIX socket
	
PHP version (8.1.18) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.12) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /etc/glpi/ has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database

**Comment by stonebuzz** [comment]
Hi @blackpearl-2022 

I can reproduce but :

It's important to understand that the data sent to the rules engine on update is only the data updated AND used by the rules.

In your case, the approval of a request only leads to a modification of the global validation status on the ticket.

So the ticket rule engine only receives 

```
      [id] => 3 //Ticket id
      [global_validation] => 3 //global validation compute afer validation approval
      [_from_itilvalidation] => 1 //where the call comes from 
      [actor] ......
```

Ticket status is not present because is not updated 

It's a behavior that's been around (and used) for a long, long time on GLPI.

This is a very sensitive area that needs a lot of work to ensure it doesn't interfere with the community's current use of it.

As proof, I tried a PR to change behavior 

https://github.com/glpi-project/glpi/pull/15965

Unit tests are already in error  and will certainly require a great deal of adaptation to GLPI (and will therefore probably be integrated into 10.1).

I advise you to adapt your rules accordingly

**Comment by blackpearl-2022** [comment]
Hi,
Can you suggest any other ways that we can customize the rules or implement workaround techniques to assign a group instead of altering the ticket status when the manager grants approval? 
Our primary goal was to automatically assign the group/user to the ticket.

**Comment by stonebuzz** [comment]
Remove this line

![image](https://github.com/glpi-project/glpi/assets/7335054/99f6ac76-f9f4-412b-8067-7ef393032036)

and it should be ok

**Comment by blackpearl-2022** [comment]
Thank you for reply. 

I changed the rule as you have mentioned. It working 
After removing the Category it is working. The group is assigned automatically .
![image](https://github.com/glpi-project/glpi/assets/118801689/615fe6e6-923c-43db-8df8-96e66136d8de)

In our case this group is only need to be assigned for laptop request by the end user.

So any other condition that can be given along the validation criteria?

**Comment by stonebuzz** [comment]
possibly the actors, as they are managed in a different way
