### ISSUE TITLE
Behaviors Solution types

### ISSUE THREAD

**Issue by edualmomds** [glpi-project/glpi#15969]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When using the Behaviors Plugin, we have configured the system for the Type of solution is mandatory before ticket is solved/closed. Even after everything is configured, when solving the ticket the NULL(----) value is possible to select and the technicians can close without the proper option configured.

The idea of the behavior is to allow the ticket to be closed with only the created options are selected, not the NULL value.

### Your GLPI setup information

![image](https://github.com/glpi-project/glpi/assets/113107789/25d4835c-24ed-4585-a0a2-0f6b179a9049)

**Comment by trasher** [comment]
We do not handle plugin issues/questions here; thank you.
