### ISSUE TITLE
Reservation expired

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#15976]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.7

### Bug description

In the expired reservation notification, the variables are not populated:

![image](https://github.com/glpi-project/glpi/assets/6449156/9dfc9777-a9ce-4c1d-bbcc-ce04d9725aec)

### Steps To reproduce

1. create reservation
2. wait until expire
3. on notification of expired show the bug

### Your GLPI setup information

My version is 10.0.7 but before update to 10.0.1o try on "glpi-network.cloud" and the issue is also present there.

**Comment by jcervantes-sipecom** [comment]
hi @rjmontenegro a quick question, your template is beetween these tags: ##FOREACHreservations##  ##ENDFOREACHreservations##?

I have this template and work for me:


```
##lang.reservation.entity## : ##reservation.entity##


##FOREACHreservations##
##lang.reservation.itemtype## : ##reservation.itemtype##

 ##lang.reservation.item## : ##reservation.item##

 ##reservation.url##

 ##ENDFOREACHreservations##
```

**Comment by rjmontenegro** [comment]
Yes, you're right! The default notification is wrong and that misled me.
