### ISSUE TITLE
Upgradation error

### ISSUE THREAD

**Issue by nidhin077** [glpi-project/glpi#15983]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

0.84

### Bug description

Hi,

I'm attempting to update my glpi to the most recent version, but I'm encountering some issues with database tables. Could you recommend a reliable method for upgrading from 0.84 to 10.0?

**Comment by cedric-anne** [comment]
Hi,

1. Restore your GLPI 0.84 database dump into an empty database (empty = no tables at all). Let's say you name it `glpi10`.
2. Use the CLI console to configure GLPI 10.0 to connect to this database: `bin/console db:configure --db-host=XXX --db-name=glpi10 --db-user=YYY --db-password=ZZZ`.
3. Execute the `bin/console db:check` command to validate that your GLPI 0.84 database has the expected structure. If some differences exists, you will have to fix them manually.
4. If the database has the expected structure, run the `bin/console db:update` command. If you have any error, open an issue with the corresponding error trace.

**Comment by nidhin077** [comment]
@cedric-anne 

I executed the script bin/console db:check and followed your instructions, please see the output of this command.

![image](https://github.com/glpi-project/glpi/assets/107123789/820c8fae-ef23-42e5-8db6-c627a63ce7d6)

After that, I tried the upgrade procedure and encountered an issue. 

![image](https://github.com/glpi-project/glpi/assets/107123789/1b49a613-6959-4325-aed0-57c19fd8510d)



I'm not sure what went wrong here, so could you kindly assist me in fixing it?

**Comment by cedric-anne** [comment]
@nidhin077 

Before executing the upgrade, you have to fix the differences shown by the `bin/console db:check` command. For instance, according to you result, the `glpi_authldaps` is missing from your database and you have to create it manually. The SQL query used to create it corresponds to the output of the `bin/console db:check` command.

**Comment by nidhin077** [comment]
@cedric-anne I tried to create the missing SQL table, but finally got an error.


```
Table schema differs for table "glpi_authldaps".
--- Expected database schema
+++ Current database schema
@@ @@
   KEY `date_mod` (`date_mod`),
   KEY `is_active` (`is_active`),
   KEY `is_default` (`is_default`)
-)
+) COLLATE=utf8mb4_general_ci
```
I attempted to resolve the issue by altering the previously specified structure, but the error persisted. Would you kindly help me to solve the same?

**Comment by nidhin077** [comment]
@cedric-anne we are stuck at this point, please assist me on this.

**Comment by cedric-anne** [comment]
This minor difference is not supposed to be an issue. If this is the only remaining diffrence, you should be able to execute the upgrade process using the `php bin/console db:update` command.

**Comment by nidhin077** [comment]
@cedric-anne We have done the upgrade, but in the end, we got an issue with the table structure. So we assume the issue is with the above structure issue.

**Comment by cedric-anne** [comment]
You can run the `php bin/console migration:utf8mb4` to ensure that your whole GLPI data base is converted to `utf8mb4` charset. I guess this will fix this issue.
