### ISSUE TITLE
In the case that more than one operating system is linked to a computer, a link with is_dynamic=1 cannot be removed.

### ISSUE THREAD

**Issue by Mirkk** [glpi-project/glpi#15991]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.10

### Bug description

There is the case that more than one operating system is linked to a computer (this cannot be done on the web interface, but e.g. when importing an OS with the datainjection plugin!).

Now, try to delete one of them, with Action->Delete permanently the relation.

- if the OS link to delete has is_dynamic=0, it works.
- if it has is_dynamic=1, it cannot be removed! 
    --- History entry: Lock a link with an item: ...  
    --- Database entry for glpi_items_operatingsystems: is_dynamic=1, is_deleted=1  but it is still shown!

Workaround: if is_dynamic is changed to 0 in the database, it works.

### Relevant log output

```shell
History entry: Lock a link with an item: ...
```

### Page URL

/computer.form.php

### Steps To reproduce

see above

### Your GLPI setup information

tried with 3 different installations.

**Comment by stonebuzz** [comment]
Since support is provided via our internal tool, I will close this issue.

The datainjection plugin will be fixed to no longer allow multiple OS to be added (like GLPI).
