### ISSUE TITLE
ticket template

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#160]
http://forum.glpi-project.org/viewtopic.php?id=120773

This bug appear if requester type is defined in user settings

**Comment by virginiacorrea** [comment]
Hi all!

I have a problem

I have a template on which to interface two camps hidden helpdesk.

User (helpdesk) enters and perfect sees the two camps ...

It happens that they want to see the two camps created after the ticket (for technical management) but there are still hidden.

I have selected the default template for the entity and sub-distributors and even also for the super-admin profile, however still leaves me hidden fields and I need to see to update them (Standard Interface).

It is very important to me this functionality. I know I'm not ignoring.

If anyone can help me. I appreciate it.

Thank you.

**Comment by virginiacorrea** [comment]
I'm using Version: 090.1
