### ISSUE TITLE
Inventory module does not insert or update a Virtual Machine comment into the database

### ISSUE THREAD

**Issue by jbonor** [glpi-project/glpi#16002]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

I am trying to inject inventories with virtual machines with a comment and it does not work.
`<VIRTUALMACHINES>
  <COMMENT>STRING</COMMENT>
</VIRTUALMACHINES>
`

It seems the "comment" property it is not handled in the foreach loop on 
src/Inventory/Asset/VirtualMachine.php line 245

**Comment by stonebuzz** [comment]
Hi @jbonor 

can you provide related inventory file ?
