### ISSUE TITLE
Problem when uploading files (takes too long)

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#16001]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hello all,

I migrated our GLPI v9.6 (Linux, Debian) to GLPI v10.0.10 on Windows 2022 server with IIS & PHP & MYSQL.
It was quite long but I did it and everything is working.

the team brought to my attention a rather annoying problem: when the technician uploaded a file, there was a "File missing" error. 

after some research, I had to specify a path to a "temporary" folder in the php.ini file.

In this case, I gave him this path: **C:\inetpub\wwwroot\glpi\files\_tmp** (because I had spotted a temporary folder => _tmp)

something I never had to do in older versions of GLPI.

the second problem, which I can't explain. I can now "load files" but it takes a long time ...
Ex: a 200kb file => 4 minutes

**also, for a loaded file it creates a lot of .tmp files and a lot of requests.**

I'll show you a GIF so you can see the problem (click on the image to see the GIF and the problem in live)

[![image](https://github.com/glpi-project/glpi/assets/63521311/dc5c8008-49c2-48df-ad07-00f6f26161cb)](https://i.imgur.com/1rrcLu4.gif)

I have no errors in the PHP LOG & SQL LOG, seems to be clean here...

in parallel, I have another instance of GLPI in 10.0.6 on Windows server and I don't have this problem.

**Comment by cedric-anne** [comment]
Maybe it is due to an unexpected value in PHP configuration that produce in an unexpected result in https://github.com/glpi-project/glpi/blob/0fed4fa7716ce3c8bbb1fc20810e08be4aeb3c78/src/Toolbox.php#L1803

What are the values of your PHP variables post_max_size and upload_max_filesize ?

**Comment by stdglpi** [comment]
> Maybe it is due to an unexpected value in PHP configuration that produce in an unexpected result in
> 
> https://github.com/glpi-project/glpi/blob/0fed4fa7716ce3c8bbb1fc20810e08be4aeb3c78/src/Toolbox.php#L1803
> 
> What are the values of your PHP variables post_max_size and upload_max_filesize ?

Hello @cedric-anne  

thank you for your return ! 

post_max_size = 8M
upload_max_filesize = 15

**Comment by cedric-anne** [comment]
> upload_max_filesize = 15

I think it means that the max size of uploaded files is 15 bytes. In this case, the upload is split into really small chunks (less than 15 bytes each), and it takes many requests to upload the whole file.

A `M` is missing here, you probably meant to set
```diff
- upload_max_filesize = 15
+ upload_max_filesize = 15M
```

**Comment by stdglpi** [comment]
> > upload_max_filesize = 15
> 
> I think it means that the max size of uploaded files is 15 bytes. In this case, the upload is split into really small chunks (less than 15 bytes each), and it takes many requests to upload the whole file.
> 
> A `M` is missing here, you probably meant to set
> 
> ```diff
> - upload_max_filesize = 15
> + upload_max_filesize = 15M
> ```

Hello @cedric-anne 

I tested and you spotted the problem

Thank you ! you can close this request.

Have a good weeknd
