### ISSUE TITLE
Satisfaction Survey expires even after being answered

### ISSUE THREAD

**Issue by vinilamelas** [glpi-project/glpi#16009]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

The Applicant responds to the satisfaction survey and after time passes for the survey to expire, even with the satisfaction survey completed, the GLPI shows that it has expired and it is not possible to view the response applied.

### Relevant log output

```shell
No error log
```

### Page URL

/front/ticket.form.php?id=479172

### Steps To reproduce

1 - Approves the solution to the call
2 - Applicant responds to the satisfaction survey
3 - After the days applied to the entity for the satisfaction survey to expire, go to this call in the satisfaction tab and try to view the survey response

Prints de exemplo : 

![image](https://github.com/glpi-project/glpi/assets/51828518/cd1e9379-3210-410d-81be-1b78dee18c99)

![image](https://github.com/glpi-project/glpi/assets/51828518/56e8e2d2-b50a-49df-87fe-ceb1bff15d71)

### Your GLPI setup information

Operating system: Linux cso-glpiapp1p 5.4.17-2136.301.1.4.el8uek.x86_64 #​2 SMP Fri Dec 3 20:28:14 PST 2021 x86_64
PHP 8.0.30 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, snmp, soap, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.37 (Oracle Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 38, Revision 3692a61
	Server Version: 5.7.35-38
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: 
	Host info: 
	
PHP version (8.0.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /etc/glpi has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

**Comment by cedric-anne** [comment]
Hi,

It is not really a bug, but a bad design of the feature. Indeed, if an answer was made, I think the user can expect to be able to see what was answered, even when the survey expired.

**Comment by Lainow** [comment]
This problem is solved in the PR: [16034](https://github.com/glpi-project/glpi/pull/16034)
