### ISSUE TITLE
The database schema is not consistent with the current GLPI version.

### ISSUE THREAD

**Issue by npo412** [glpi-project/glpi#16012]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

During the update from GLPI-10.0.9 to glpi-10.0.10, a php error appears: 
`The database schema is not consistent with the installed GLPI version (10.0.9). Run the "php bin/console database:check_schema_integrity" command to view found differences.`

Here is the result of the database check:
```
root@glpi:/var/local/xxxxxxxxxxxx/glpi# php bin/console database:check_schema_integrity
Table schema differs for table "glpi_domains".
--- Expected database schema
+++ Current database schema
@@ @@
 CREATE TABLE `glpi_domains` (
   `id` int NOT NULL AUTO_INCREMENT,
   `comment` text,
-  `date_creation` datetime,
   `date_domaincreation` datetime,
   `date_expiration` datetime,
   `date_mod` datetime,
@@ @@
   `template_name` varchar(255),
   `users_id_tech` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
-  KEY `date_creation` (`date_creation`),
-  KEY `date_domaincreation` (`date_domaincreation`),
   KEY `date_expiration` (`date_expiration`),
   KEY `date_mod` (`date_mod`),
   KEY `domaintypes_id` (`domaintypes_id`),
Table schema differs for table "glpi_entities".
--- Expected database schema
+++ Current database schema
@@ @@
   KEY `level` (`level`),
   KEY `name` (`name`),
   KEY `problemtemplates_id` (`problemtemplates_id`),
-  KEY `tickettemplates_id` (`tickettemplates_id`),
-  KEY `transfers_id` (`transfers_id`)
+  KEY `tickettemplates_id` (`tickettemplates_id`)
 )
Table schema differs for table "glpi_networkportethernets".
--- Expected database schema
+++ Current database schema
@@ @@
   `date_creation` datetime,
   `date_mod` datetime,
   `items_devicenetworkcards_id` int NOT NULL DEFAULT 0,
+  `netpoints_id` int NOT NULL DEFAULT 0,
   `networkports_id` int NOT NULL DEFAULT 0,
   `speed` int NOT NULL DEFAULT 10,
   `type` varchar(10) DEFAULT '',
@@ @@
   KEY `card` (`items_devicenetworkcards_id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
+  KEY `netpoint` (`netpoints_id`),
   KEY `speed` (`speed`),
   KEY `type` (`type`)
 )
Table schema differs for table "glpi_networkportfiberchannels".
--- Expected database schema
+++ Current database schema
@@ @@
   `date_creation` datetime,
   `date_mod` datetime,
   `items_devicenetworkcards_id` int NOT NULL DEFAULT 0,
+  `netpoints_id` int NOT NULL DEFAULT 0,
   `networkportfiberchanneltypes_id` int NOT NULL DEFAULT 0,
   `networkports_id` int NOT NULL DEFAULT 0,
   `speed` int NOT NULL DEFAULT 10,
@@ @@
   KEY `card` (`items_devicenetworkcards_id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
+  KEY `netpoint` (`netpoints_id`),
   KEY `speed` (`speed`),
   KEY `type` (`networkportfiberchanneltypes_id`),
   KEY `wwn` (`wwn`)
 )
Table schema differs for table "glpi_states".
--- Expected database schema
+++ Current database schema
@@ @@
   `entities_id` int NOT NULL DEFAULT 0,
   `is_recursive` tinyint NOT NULL DEFAULT 0,
   `is_visible_appliance` tinyint NOT NULL DEFAULT 1,
-  `is_visible_cable` tinyint NOT NULL DEFAULT 1,
   `is_visible_certificate` tinyint NOT NULL DEFAULT 1,
   `is_visible_cluster` tinyint NOT NULL DEFAULT 1,
   `is_visible_computer` tinyint NOT NULL DEFAULT 1,
@@ @@
   KEY `entities_id` (`entities_id`),
   KEY `is_recursive` (`is_recursive`),
   KEY `is_visible_appliance` (`is_visible_appliance`),
-  KEY `is_visible_cable` (`is_visible_cable`),
   KEY `is_visible_certificate` (`is_visible_certificate`),
   KEY `is_visible_cluster` (`is_visible_cluster`),
   KEY `is_visible_computer` (`is_visible_computer`),
```

Everything seems to be good but when I run `php bin/console db:update`, I have an error message:

`root@glpi:/var/local/xxxxxxxxxxxx/glpi# php bin/console db:update
Some optional system requirements are missing. Run the "php bin/console system:check_requirements" command for more details.
+-----------------------+-----------+---------+
|                       | Current   | Target  |
+-----------------------+-----------+---------+
| Database host         | localhost |         |
| Database name         | glpi      |         |
| Database user         | glpi      |         |
| GLPI version          | 10.0.9    | 10.0.10 |
| GLPI database version | 10.0.9    | 10.0.10 |
+-----------------------+-----------+---------+
Checking database schema integrity...
The database schema is not consistent with the installed GLPI version (10.0.9). Run the "php bin/console database:check_schema_integrity" command to view found differences.
Do you want to continue? [Yes/no]yes
======================================== Update to 10.0.10 =========================================
====================================== Initializing rules... =======================================
Migration done.
We need your help to improve GLPI and the plugins ecosystem!
Since GLPI 9.2, we’ve introduced a new statistics feature called “Telemetry”, that anonymously with your permission, sends data to our telemetry website.
Once sent, usage statistics are aggregated and made available to a broad range of GLPI developers.
Let us know your usage to improve future versions of GLPI and its plugins!
Do you want to send "usage statistics"? [Yes/no]no
The database schema is not consistent with the current GLPI version.
It is recommended to run the "php bin/console database:check_schema_integrity" command to see the differences.
`

**Comment by cedric-anne** [comment]
Hi,

It shows that your database has some missing fields/indexes and has also unknown fields/indexes. If you want to fix this, you will have to do it manually using database queries.
