### ISSUE TITLE
The data defined in the task model is not being replicated in the form when selected.

### ISSUE THREAD

**Issue by acmaximino** [glpi-project/glpi#16014]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

The data defined in the task model is not being replicated in the form when selected. For example, if you set the status to "Information" in the task template, when you select this template the status field remains at "to do"

### Page URL

all pages that use tasks, tickets, problems, changes...

### Steps To reproduce

1 - Create new template in https://servicedeskhml.hsl.org.br/front/tasktemplate.php with status = information
2 - open a new ticket and add a task by selecting the created template. You will see that the status field remained in "to do" instead of assuming the value of the created model

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.10 ( => C:\inetpub\wwwroot\10010\glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Windows NT HSLITSMP01 10.0 build 20348 (Windows Server 2022) AMD64
PHP 8.2.10 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, random, readline, session, soap, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Server Software: MySQL Community Server - GPL
	Server Version: 8.1.0
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/itsm_hsl_db_10010
	Host info: localhost via TCP/IP
	
PHP version (8.2.10) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.1.0) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_cache has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/config has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_cron has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_dumps has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_graphs has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_lock has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_pictures has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_plugins has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_rss has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_sessions has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_tmp has been validated.
Write access to C:\inetpub\wwwroot\10010\glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\wwwroot\10010\glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\inetpub\\wwwroot\\10010\\glpi"
GLPI_CONFIG_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/config"
GLPI_VAR_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files"
GLPI_MARKETPLACE_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files"
GLPI_CACHE_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_cache"
GLPI_CRON_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_cron"
GLPI_DUMP_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_locales"
GLPI_LOCK_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_lock"
GLPI_LOG_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_log"
GLPI_PICTURE_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_plugins"
GLPI_RSS_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_rss"
GLPI_SESSION_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_sessions"
GLPI_TMP_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "C:\\inetpub\\wwwroot\\10010\\glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (C:\inetpub\wwwroot\10010\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.8.0 in (C:\inetpub\wwwroot\10010\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\inetpub\wwwroot\10010\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (C:\inetpub\wwwroot\10010\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\inetpub\wwwroot\10010\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\inetpub\wwwroot\10010\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\inetpub\wwwroot\10010\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\inetpub\wwwroot\10010\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\inetpub\wwwroot\10010\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\inetpub\wwwroot\10010\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\inetpub\wwwroot\10010\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\inetpub\wwwroot\10010\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\inetpub\wwwroot\10010\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\inetpub\wwwroot\10010\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\inetpub\wwwroot\10010\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\inetpub\wwwroot\10010\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\inetpub\wwwroot\10010\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\inetpub\wwwroot\10010\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\inetpub\wwwroot\10010\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\inetpub\wwwroot\10010\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\inetpub\wwwroot\10010\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\inetpub\wwwroot\10010\glpi\vendor\rlanvin\php-rrule\src)
ramsey/uuid in (C:\inetpub\wwwroot\10010\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\inetpub\wwwroot\10010\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\inetpub\wwwroot\10010\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\inetpub\wwwroot\10010\glpi\vendor\psr\cache\src)
league/csv in (C:\inetpub\wwwroot\10010\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\inetpub\wwwroot\10010\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\inetpub\wwwroot\10010\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\inetpub\wwwroot\10010\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\inetpub\wwwroot\10010\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\inetpub\wwwroot\10010\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\inetpub\wwwroot\10010\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\inetpub\wwwroot\10010\glpi\vendor\symfony\cache)
html2text/html2text in (C:\inetpub\wwwroot\10010\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\inetpub\wwwroot\10010\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\inetpub\wwwroot\10010\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\inetpub\wwwroot\10010\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\inetpub\wwwroot\10010\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (C:\inetpub\wwwroot\10010\glpi\vendor\symfony\polyfill-php82)
league/oauth2-client in (C:\inetpub\wwwroot\10010\glpi\vendor\league\oauth2-client\src\Provider)
league/oauth2-google in (C:\inetpub\wwwroot\10010\glpi\vendor\league\oauth2-google\src\Provider)
thenetworg/oauth2-azure in (C:\inetpub\wwwroot\10010\glpi\vendor\thenetworg\oauth2-azure\src\Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'hsl.pvt', Port: '389', BaseDN: 'DC=hsl,DC=pvt', Connection filter:
		'(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))', RootDN: 'svc.servnow@hsl.pvt', Use
		TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (glpi@hsl.org.br@hslexmbx01.hsl.pvt)

</pre></details><details><summary>Plugins list</summary><pre> 
	actualtime           Name: ActualTime                     Version: 2.2.0      State: Enabled                                 
		Install Method: Manual
	fields               Name: Additional fields              Version: 1.21.6     State: Enabled                                 
		Install Method: Manual
	archires             Name: Arquiteturas de Rede           Version: 2.7.0      State: Not installed                           
		Install Method: Manual
	cmdb                 Name: CMDB                           Version: 3.0.3      State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	correcttimeworked    Name: Corrige tempo trabalhado gerad Version: 1.0.0      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.3     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.7     State: Installed / not activated               
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.6+1.1 State: To update                               
		Install Method: Manual
	gappessentials       Name: Gapp Essentials                Version: 2.1.2      State: Enabled                                 
		Install Method: Marketplace
	dashboard            Name: Painel                         Version: 1.0.2      State: Installed / not activated               
		Install Method: Manual
	stopslabygroup       Name: Stop SLA By Group              Version: 1.0.0      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
Please try nightly build

**Comment by cedric-anne** [comment]
Duplicates #15760, fixed by #15786.
