### ISSUE TITLE
Expiring tokens for a login page can be confusing and annoying in some cases

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#16010]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.1.0 - main

### Bug description

When a login check is made and fails, it may redirect the user to the login page. Often this happens with an "Invalid use of session ID" error showing on the login page. The login form has a CSRF token protecting it which remains valid for 2 hours by default. If the redirect happened because of an explicit action taken by the user, this really isn't an issue as they would log back in before it expires.

The issue comes when this redirect is not triggered by a user action. For example, the automatic refresh of the ticket list. In that case, GLPI will automatically show the login page. If the user returns after 2 hours or more and tries to log in, they are presented with yet another error and have to log in a second time.

Rather than redirect directly to the login screen, a separate screen could be shown with just the relevant error (maybe re-worded as "Your session has expired. Please log in again") with a button to go to the login screen. In this case, no token is generated until the user explicitly chooses to try to log in again and should make an expiring CSRF token on the login screen much less likely.

**Comment by cedric-anne** [comment]
Fixed by #16289 .
