### ISSUE TITLE
To be able to assign users to groups using LIKE % instead of complete name

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1604]
Hello
I propose to give more possibilities when searching LDAP for user members of groups.
Let's have an example:
![image](https://cloud.githubusercontent.com/assets/7569958/21894721/867c01b4-d8e0-11e6-839d-bd9e73583606.png)
Current test is to match exact string in the attribute value. This has the drawback if 'department' is not written the exact same way in LDAP, then it will not match

I propose to use LIKE instead of IN in the mySQL query, This will permit to have a more flexible use of assignment:
![image](https://cloud.githubusercontent.com/assets/7569958/21894808/cc0ee6ba-d8e0-11e6-8d1d-0372615f5e55.png)
Using LIKE operator will permit such criterion. In this case any user department matching the '163387 %' will be added to the group.

**Comment by orthagh** [comment]
ping @wawax for this issue and the corresponding PR #1606 

Moved to 9.1.3 to have time for tests (9.1.2 freezed today for wanted date of release next monday)
