### ISSUE TITLE
No "Delete" button for simplified interface

### ISSUE THREAD

**Issue by Ratherius** [glpi-project/glpi#16048]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Hello! I did not find the option to reopen the issue https://github.com/glpi-project/glpi/issues/2565, so I have created a new one.

My users with simplified interface have no possibility to delete attached files, while users with standard interface have the button.
Thank you in advance for your help!

**Comment by trasher** [comment]
Try with latest release
