### ISSUE TITLE
Future dates are allowed to be placed in the opening date 

### ISSUE THREAD

**Issue by loyolajavi** [glpi-project/glpi#16058]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

In tickets,  problem and changes, future dates are allowed to be placed in the opening date.

**Comment by cconard96** [comment]
This isn't a bug, and some technicians may actually want to create tickets with a future opening date as it affects SLA/stats.
If you want to suggest a change to this behavior/a configurable option to limit the selection to past dates/times, you can submit the suggestion on the suggestions site.
https://glpi.userecho.com/
