### ISSUE TITLE
Adding new system from template gives error

### ISSUE THREAD

**Issue by mhryni** [glpi-project/glpi#16052]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.5.4

### Bug description

Hello,

It is my first topic here.

I'm trying to update GLPI engine from 9.2.4 to 9.5.4

after installation wich was succesful, I logged in and tryed to check the functions.

Addind New System by using template, even empty one gives this error"

Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi954\inc\dbmysql.class.php on line 1084

Fatal error: Missing table name in C:\xampp\htdocs\glpi954\inc\dbmysqliterator.class.php on line 277

When i use back button in the web browser im going back to the page before and small pop=up window appears that it was created. Later i can find it.

I do not understand the error and where is hould search for a problem, because those lines marked as problematic gives no information what the problem really is.

### Your GLPI setup information

I can see anly this....

Operating system: Windows NT SERVER-LEXWARE 10.0 build 19045 (Windows 10) i586
PHP 7.2.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, sodium, standard, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="80M" 
Software: Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 (Apache/2.4.33 (Win32) OpenSSL/1.1.0h PHP/7.2.6 Server at 192.168.0.9
	Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.1.32-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP

**Comment by trasher** [comment]
GLPI 9.5 is no longer supported; consider upgrading to GLPI 10.

**Comment by mhryni** [comment]
I have my reasons to not upgrade to GLPI 10.

If you dont know how to help at least you could try to point the place where i could get help.

**Comment by cedric-anne** [comment]
> If you dont know how to help at least you could try to point the place where i could get help.

You can try to get help on [community forum](https://forum.glpi-project.org/).
