### ISSUE TITLE
standard hook plugin_x_deactivate and post_plugin_disable not called on plugin deactivate

### ISSUE THREAD

**Issue by flex-pgum** [glpi-project/glpi#16075]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Both "plugin_x_deactivate" (standard hook in hook.php) and "post_plugin_disable" are not called when disabling any custom plugin.

### Steps To reproduce

1. Add a small custom module (maybe the [https://github.com/pluginsGLPI/example](https://github.com/pluginsGLPI/example) plugin)
2. Add function `plugin_example_deactivate` to hook.php with an error_log or something similar to see if function is called (in case you installed and configured xdebug, simply set a breakpoint)
3. Configure the `post_plugin_disable` hook in setup.php, create the function in hook.php and set a breakpoint (or log)
5. Install and activate the plugin
6. Deactivate the plugin

### Anything else?

I did some debugging and found the reason for both issues:

- *plugin_x_deactivate*: in file **Plugin.php** (./src/Plugin.php) under function `unactivate` the respective hook.php is not included like in for example `activate`
- *post_plugin_disable*: in file **Plugin.php** (./src/Plugin.php) under function `doHook` there is a `isPluginActive` condition which prevents the `post_plugin_disable` hook to execute. This is a logical error because the plugin is and can not be active anymore when the *post*_plugin_disable hook is called.

I would be glad if anyone with some more glpi-knowledge could look into this and confirm my thoughts.

**Comment by cedric-anne** [comment]
The following patch should fix the call to `plugin_x_deactivate` hook.

```diff
diff --git a/src/Plugin.php b/src/Plugin.php
index 79fd2a15d0..465343e0b4 100644
--- a/src/Plugin.php
+++ b/src/Plugin.php
@@ -1116,6 +1116,9 @@ class Plugin extends CommonDBTM
     {
 
         if ($this->getFromDB($ID)) {
+            // Load plugin hooks
+            self::load($this->fields['directory'], true);
+
             $deactivate_function = 'plugin_' . $this->fields['directory'] . '_deactivate';
             if (function_exists($deactivate_function)) {
                 $deactivate_function();
```

For the `post_plugin_disable` hook, it will not be call for the plugin that has just been disabled, and it is normal. The purpose of this hook is to indicate to other plugins that your plugin has been deactivated.
