### ISSUE TITLE
fields plugin not work in GLPI 10.0.10

### ISSUE THREAD

**Issue by polskigaz** [glpi-project/glpi#16088]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.10

### Bug description

Plugin ver. 1.21.6 not work after updated GLPI to ver. 10.0 10.
Enabling plugin causes the basic ticket fields disappear.
Plugin enabled:
![image](https://github.com/glpi-project/glpi/assets/152395731/45f7c8a2-7147-48bf-927d-b4c37f102a6e)

plugin disabled:
![image](https://github.com/glpi-project/glpi/assets/152395731/0dddba87-6618-456f-9219-771b5652c8d9)

is this a plugin problem or a GLPI problem?

### Anything else?

issue ticket created on fileds github repository - still no reply.

https://github.com/pluginsGLPI/fields/issues/724

**Comment by trasher** [comment]
Please do not open plugin related issues here.
