### ISSUE TITLE
Notification mail php

### ISSUE THREAD

**Issue by AMUNIER9** [glpi-project/glpi#16090]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.3 

### Bug description

Hi everyone,

Since few month, I'm trying to improve the notification's users with a php code that I founded on a website. 
But when I tried to add it, the "traduction" doesn't work.
The mail look like the code that I've add. 

Is anyone could help me... 
Thanks! 

(sorry for my english skills, I've not practice since many years)

**Comment by trasher** [comment]
10.0.3 is very outdated, try with latest stable.

**Comment by trasher** [comment]
> Do you think that it could be solved with the update of glpi ?

That is something to try anyway. Also, many securitu fixes has been applied since .3.

> The only problem that I have with an update is that I use fusioninventory. This one is not compatible with a more recent version than 10.0.6

You can ask plugin maintainer to update. Or you can replace it with native inventory, and if needed glpiinventory plugin.

**Comment by AMUNIER9** [comment]
Hello,
I found how to bypass the version's problem of fusioninventory.
I tried to upgrade glpi this morning but I don't know why, I had a 403 error just after...
Maybe a access right mistake. 
I'll try later, I only have a prod server, I don't want to break it a second time now

**Comment by AMUNIER9** [comment]
Hello, 
Glpi is up to date but when I tried again with the html code (not php, shame on me) it's the same. :(

**Comment by AMUNIER9** [comment]
So... I've found the problem... It's me... I didn't add the html code in source code... 
Sorry!
