### ISSUE TITLE
ticket description with rich text

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#161]
http://forum.glpi-project.org/viewtopic.php?id=127383

**Comment by yllen** [comment]
Bon pour moi c'est un problème jquery parce que si je regarde le code source généré
<textarea style="visibility: hidden;" id="content1666085608" name="content" cols="100" rows="10">
tout est correct suivant le textarea généré dans GLPI (name, cols, rows, id) 
sauf le visibility: hidden qui n'a pas été positionné.
Le problème apparait uniquement en cas de rechargement d'un page déjà appelée, page utilisant le rich_text

**Comment by yllen** [comment]
Autre question : pourquoi y a-t-il 3 versions de jquery  dans GLPI ?

**Comment by orthagh** [comment]
fixed in eb058ec
