### ISSUE TITLE
[GLPI 9.1.1] In 'your planning' on central home page, the days are not updated when tasks are updated

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1610]
Hello,
With latest sources from 9.1/bugfixes (from today https://github.com/glpi-project/glpi/tree/5783a997c0c6e51c41fbe2fbf0a6400911b9f10c : includes the latest version of fullcalendar) , it's 'your planning' panel is not updated when a task due-date is updated.
ex:
![image](https://cloud.githubusercontent.com/assets/7569958/21934132/8c3890ea-d9a8-11e6-9953-b09413b532dd.png)

let's edit task 'test 5', and changed initial due-date that was set to 13-01-2017, set it to 16-01-2017, and save.
![image](https://cloud.githubusercontent.com/assets/7569958/21934210/e01b98d8-d9a8-11e6-91ea-69279c8512c0.png)

'your planning' is not updated to reflect the new date:

![image](https://cloud.githubusercontent.com/assets/7569958/21934241/0040d038-d9a9-11e6-9058-2adf40e6631b.png)

In the past (:)) yesterday, 'your planning' was updated to reflect due-date changes.

thank you,
regards,
Tomolimo

**Comment by orthagh** [comment]
hum, with popup edition, no refresh is made to planning, a manual one make the planning ok.
I'll check to add a force refresh after ajax event.
