### ISSUE TITLE
[GLPI 9.1.1] logout will re-login automatically when using SSO with LDAP

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1611]
Hello,

In the past there was a parameter on the logout url that was noAuto=1, where is gone this parameter?

![image](https://cloud.githubusercontent.com/assets/7569958/21934619/600af4ca-d9aa-11e6-946f-08bb57bbb781.png)

Now with today sources (from 9.1/bugfixes), this option seems to have disappear, and of course there is no way to logout, as the logout will re-login automatically and immediately...

info: authtype is 3: LDAP directory

Thank you to re-enable this option on the logout url.

**Comment by willouuu** [comment]
I have same issue, no logout with cas

**Comment by orthagh** [comment]
still present in 9.1/bugfixes and master but your account need to be an external type.

See: https://github.com/glpi-project/glpi/blob/master/inc/html.class.php#L1430-L1432

Maybe a diff on your instance ?

I close, feel free to reopen.

**Comment by orthagh** [comment]
see (on master) : 
![image](https://cloud.githubusercontent.com/assets/418844/22115808/b9ec98ea-de6e-11e6-8e0b-fbd774cfb6cc.png)

**Comment by tomolimo** [comment]
Was not like that with 9.1.1

**Comment by orthagh** [comment]
yes, also in 9.1: 
![image](https://cloud.githubusercontent.com/assets/418844/22115886/f09f2da8-de6e-11e6-998d-6b805d6407a7.png)

https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/html.class.php#L1511-L1513

**Comment by orthagh** [comment]
also in 9.1.1: https://github.com/glpi-project/glpi/blob/9.1.1/inc/html.class.php#L1511-L1513

could you check the code on your side ?

**Comment by tomolimo** [comment]
Yes, same code, but the $_SESSION['glpiextauth'] is equal to 0, my user is authenticated via LDAP with SSO

**Comment by tomolimo** [comment]
I made a test setting auth to GLPI internal, and then back to LDAP, and still the same values

**Comment by tomolimo** [comment]
Even if I force my user to be ext+LDAP (auth=4) the noAuto=1 doesn't appear

**Comment by btry** [comment]
Hi Tomolino, 

Can you check after reverting #1548 #1553 (and maybe #1627)  ?

**Comment by orthagh** [comment]
ok, #1548 is indeed the cause.
I'l provide you a fix in the morning, @tomolimo
