### ISSUE TITLE
[GLPi 9.1.1] When setting ticket category via massive action, wrong categories appear in list

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1613]
Hello,

If you try to set ticket category via massive action, categories that can't be assigned to ticket will appear even if theses categories are not for tickets:
exp:

![image](https://cloud.githubusercontent.com/assets/7569958/21973486/4c36efc6-dbc1-11e6-87e2-bbc9a2c40fdb.png)

And:

![image](https://cloud.githubusercontent.com/assets/7569958/21973519/9eeb9d66-dbc1-11e6-9f5c-01c9b27fc5df.png)

regards,
Tomolimo

**Comment by tomolimo** [comment]
Same issue for Problems and for Changes

**Comment by yllen** [comment]
I disagree: check must only done for massiveactions.
For ticket you can increment  getValueToSelect() of ticket.class

`case 'itilcategories_id' :`
     `$field_id_or_search_options['condition'] = ' is_incident = 1 OR is_request = 1';`
     `break;`

To do the same for problem and change
