### ISSUE TITLE
Notifications are not sent for tasks automatically assigned by rules or template

### ISSUE THREAD

**Issue by Hantiel** [glpi-project/glpi#16139]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hi. 

After the recent GLPI update to version 10.0.10 from version 10.0.6, task notifications that are automatically assigned based on rules for requests or request templates no longer work. Only a notification of a newly created ticket is sent.
When adding a task manually, notifications are sent. 

I have a GLPI Network Subscription - but the options to report a problem there do not currently work.  :(
![image](https://github.com/glpi-project/glpi/assets/113474035/82abaed8-f803-410e-8969-4a376c6802a9)

### Steps To reproduce

1. create a task template assigned to you.
2. create a business rule for tickets or a ticket template that assigns the created task template to a ticket.
3. create a ticket that complies with the above conditions.
4. check if the task has been assigned to the ticket - if so, check if you have received notification of a new task assigned to you

### Your GLPI setup information

GLPI 10.0.10 
Installation mode: TARBALL
Current language:pl_PL

PHP 8.1.14 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.54 (Debian)

**Comment by Hantiel** [comment]
Tested on 10.0.11 - still same problem.

**Comment by trasher** [comment]
If you own a subscription, please report your issue on support. Services downtime certainly has been fixed since 2 weeks.
