### ISSUE TITLE
Documents gets renamed with added random characters

### ISSUE THREAD

**Issue by plburguet** [glpi-project/glpi#16140]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When documents on OFFICE formats (pptx, xlsx...) are submitted directly inside an answers, it gets renamed like : 60b732e5f64b50.71666440REAL TITLE.xlsx
But if we add it just as a document, and not in the answers, it behave normally.
Sometimes they can get fully renamed with a similar file that already exists and was uploaded in an older ticket (the file is exactly the same, the technician only change the name of it before uploading)
![image](https://github.com/glpi-project/glpi/assets/52488995/6c139c5c-72d5-48aa-a458-48c9b2c0fb2d)

### Relevant log output

```shell
no errors logged
```

### Steps To reproduce

1. go to a user ticket
2. answers the user with some text
3. add a document
4. submit

### Your GLPI setup information

GLPI 10.0.10 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR
PHP 8.2.13

### Anything else?

It looks like that problem exist since the upgrade from 9.5 to 10, I am able to find back some files that got the same behavior near the date of the upgrade, but not before.

**Comment by AdrienClairembault** [comment]
I think this was fixed by https://github.com/glpi-project/glpi/pull/15782.
Could you try again in 10.0.11 ?

**Comment by plburguet** [comment]
hello, it seem like it is yes.
I can't reproduce that error now
I will be attentive on the next tickets in case it happens again, this issue can be closed.
Thanks a lot
