### ISSUE TITLE
The reminder for a planned task is too late

### ISSUE THREAD

**Issue by LayzIsNotAvailable** [glpi-project/glpi#16152]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hello, 
When I schedule a task on GLPI, I receive a reminder too late in relation to the start date of the task.
You can see it on these screenshots: 

![Screen1-GLPI](https://github.com/glpi-project/glpi/assets/152962975/40c58697-b4f1-48b8-b345-5f51aad1aa40)
![Screen2-Mail](https://github.com/glpi-project/glpi/assets/152962975/b298b1a4-940c-41a9-bcc5-990c5f4d695f)

Thank you in advance for your help.
Regards.

**Comment by cconard96** [comment]
This seems like a configuration/expectation issue, not a bug.
First, reminders for planned tasks/events generated by the `planningrecall` automatic action which is set to run by default every 5 minutes. It can be reduced to every minute. Then once the notification is generated, it goes to the queue. The notifications from the queue are sent by the `queuednotification` automatic action which is set to run every minute by default.
By setting a reminder for 0 minutes, it is very unlikely you would actually get the notification within a minute of the scheduled start time. Finally, the run mode set for both tasks can greatly impact how quickly they are able to start after they become due.

If you need help configuring the automatic actions, feel free to make a post on the GLPI Forums.
https://forum.glpi-project.org/
You can also find documentation regarding this part of GLPI here in the user documentation:
https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/crontasks.html
