### ISSUE TITLE
Web server root directory configuration is not safe

### ISSUE THREAD

**Issue by bfg01** [glpi-project/glpi#16158]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

On a GLPI 10.0.10 new installation from scratch on Centos 9, in the environmental checks
https://glpi-install.readthedocs.io/en/latest/install/wizard.html#environment-checks
I keep getting: "Web server root directory configuration is not safe
contents should be placed at /var/www/glpi/public/glpi/public"

This is setting DocumentRoot /var/www/glpi/public
If setting for example /var/www/html, the error expects /var/www/html/glpi/glpi/public
And so on.
There's no way to satisfy the environment checks.

### Steps To reproduce

Follow the installation instructions from start documented at
https://glpi-install.readthedocs.io/en/latest/
Use this httpd configuration (no htaccess)
https://glpi-install.readthedocs.io/en/latest/prerequisites.html#apache-configuration
Proceed with installation steps
Reach the environmental checks step.

### Your GLPI setup information

No previous setup at all; this is a clean installation attempt.

**Comment by bfg01** [comment]
My bad, it was not a bug, but an issue in httpd configuration on my side.
I'm sorry. Closed.

**Comment by maravento** [comment]
> My bad, it was not a bug, but an issue in httpd configuration on my side. I'm sorry. Closed.

This is a problem that many people have, and you have closed it without giving any explanation. Very bad move on your part.
