### ISSUE TITLE
No picture in the mail send when an incident is closed

### ISSUE THREAD

**Issue by HelpdeskEscal** [glpi-project/glpi#16164]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

Hello everyone,

As you can see on the picture (in attachment) when we add a picture in the closure note, the mail that is sent to the final user is not complete.
Has someone the same issue ?

![2023-12-04 13_39_54-RE_  GLPI #0001736  Votre  Demande a été résolu - ACCES _ Droits répertoire comp](https://github.com/glpi-project/glpi/assets/152872115/0d584cd7-a5a9-40a9-a486-95f7b87e5ccb)

Thanks in advance

**Comment by cconard96** [comment]
This doesn't seem like a GLPI issue. The error in the placeholder for the image states the image isn't being shown by default, but it could be if you right-click it. It seems like an Outlook-specific behavior/issue. If the image shows properly after right-clicking it, it is certainly an Outlook behavior/issue. If it still doesn't show, feel free to reopen this issue with the new information/errors. Make sure you include the information that was requested on the initial bug report too like GLPI error log entries (if they exist in files/_log) and the GLPI setup information (Setup > General > System tab). It would also be helpful to know the custom notification template content being used.
