### ISSUE TITLE
Response empty when add Ticket API Rest 

### ISSUE THREAD

**Issue by Morgan4nt** [glpi-project/glpi#16177]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Hi,

Got a strange issue here, when i add a ticket with the API there's no response. The request seems to work because the ticket is well added. But the response seems to be empty.

Here's the CURL resquest : 
```
curl -X POST \
-H 'Content-Type: application/json' \
-H 'Session-Token: xxxx' \
-H 'App-Token: xxxx' \
-d '{"input": {"name": "Test CURL", "content": "Mon test via CURL", "status": "1"}}' \
'http://xxxx/apirest.php/Ticket'
```

And here's is the Python code i use : 
```Python
try:
    gman.client.add(TICKET_TYPE, {
            'name': "Test",
            'content': "Test 1234",
            'status': 1
        }
    )
except glpi_api.GLPIError as e:
    print(e) 
```

The Python code did raise an error, but nothing interresting, just : 
```
unknown error: [200/OK] 
```

This is just for Ticket items, for example, i can create a new user and i got the correct response 200 with the new user ID.

Thx for your time !

Morgan

**Comment by trasher** [comment]
10.0.6 is outdated, try with latest stable if you reproduce.

**Comment by Morgan4nt** [comment]
Ho yes, ok, I'll ask to my sysadmin.
Coming back for return !
