### ISSUE TITLE
[Native Inventory] NetworkEquipment / Printer import without network_device property

### ISSUE THREAD

**Issue by pftpz** [glpi-project/glpi#16171]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When using the native inventory to import devices of the NetworkEquipment and Printer types, the inventory expects the main information of the asset to be provided in the "content" > "network_device" part of the JSON schema. 
This expectation is not documented anywhere, and there is no warning from the import when deviating from it. The intuitive expectation from the user perspective would be that the information gets imported in the same way as e.g. for computers.
When importing a file for a NetworkEquipment or Printer that provides information using the "content" > "hardware", "bios" and "networks" properties, as is done e.g. for Computers and Phones, the behaviour is as follows:

For NetworkEquipment, most of the content will be ignored, resulting in an almost empty item that will likely be rejected by the import rules.
The reason is that the $extra_data array in src > Inventory > Asset > NetworkEquipment.php does not request the 'hardware', 'bios', 'users' and '\Glpi\Inventory\Asset\NetworkCard' parts which are listed in the $extra_data of MainAsset.php.
When adding these items to the array, the full information is imported.

For Printers, the effect is nearly the same, as they extend the NetworkEquipment class in the native inventory. However, the import will additionally crash, as the prepare() function assumes that any input that does not have the network_device property is a printer connected to another item, so that the content is actually only a sub-array of the total JSON. Then, it attempts to assign the autoupdatesystems_id property on all parts of the raw data.
However, if the main itemtype is printer and no network_device property is provided, this assumption is not true, and it is attempted to assign autoupdatesystems_id on properties that are only strings and cannot have subproperties, e.g. the mandatory deviceid property.

I propose the following options to improve the behaviour:

1. Add the additional extra_data content to NetworkEquipment and fix the possible crash in the Printer import. Possibly only consider the new extra_data parts if no network_device property is provided
2. Alternatively, when importing a NetworkEquipment or Printer without the necessary network_device property, warn the user that this is not the intended way for these device types, and also make sure that there is no crash

### Steps To reproduce

1. Use a working JSON example for computers that has no "network_device" property
2. Change the "itemtype" property to "NetworkEquipment" or "Printer"
3. Attempt to import the JSON using the native import

**Comment by g-bougard** [comment]
> This expectation is not documented anywhere, and there is no warning from the import when deviating from it.

You have indeed a description here:
https://github.com/glpi-project/inventory_format/blob/2145886bd87dba9e97ddc76abaa6e194a2edca81/inventory.schema.json#L2788

**Comment by trasher** [comment]
Indeed, this may be not precise, but it always worked that way; we had to make this distinction building the schema to be compatible with old agents and legacy plugin.
So, JSON you provide are "build", but not from the GLPI agent? If so, well.. That's not currently a bug, making everything logic in inventory data is not on roadmap right now; and it's a quite huge job.

Now you know the `network_device` is mandatory, and Fusion/GLPI agents are producing it as expected as far a I know.
