### ISSUE TITLE
[Native Import] Item matching in import rules ignores result of entity rules

### ISSUE THREAD

**Issue by pftpz** [glpi-project/glpi#16170]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When running an import using the native inventory, the result of the previously executed entity assignment rules is discarded while looking for possible assets to link with in the asset import rules.
This means that even if the entity rules determine that the asset should go into entity A, it will nevertheless be linked with an asset in entity B afterwards.
In RuleImportAsset.php->findWithGlobalCriteria, it is started to build a where clause $where_entity to filter on the currently assigned entity of the asset. However, this is never used later on except for passing it to the plugin hooks.
So, if a plugin is not used with the use_rules hook to add the entity criterion, this will get ignored.

IMO, the expected behaviour is that the result of the entity assignment rules should determine the final entity of the asset, even if a matching asset can be found in different entities. This is relevant e.g. if multiple entities belong to different organizations that may have assets with similar names and other field values which could be caught by the linking rules.

### Steps To reproduce

1. Obtain a valid JSON example for the native import
2. Create two variants of the example, one with the property "tag":"0" and one with "tag":"1"
3. Create two entities in GLPI, and create entity assignment rules that will assign items with the inventory tag 0 to the first entity, and tag 1 to the second entity
4. Import the first JSON file (with tag 0) - it will correctly be moved to the first entity
5. Delete and Purge the imported asset
6. Import the second JSON file (with tag 1) - it will correctly be moved to the second entity
7. Import the first JSON file again. Instead of creating a new asset in the first entity, the item will be imported and linked with the existing item in the second entity, even though the entity rule determines the item should be in the first entity

**Comment by keguira** [comment]
Like you explain it, I think it works as indented. In the "Rules for import and link equipments", there are the rules to import computers and it defines how a computer is identified in the system based on its name, serial number and other criterias.

If it's the same computer, it should not created multiple times in the system. Only one computer exists but if you change its tag, it means you changed the context, not the computer. 
The entity is a context of use such as you are "moving" the computer from an entity to another.
Wanting to create multiple times the same computer in the system may create other strange behaviors.
