### ISSUE TITLE
DB error while upgrading to 10.0.11

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#16188]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.3

### Bug description

Hi

i get the following error while upgrading to 10.0.11

![image](https://github.com/glpi-project/glpi/assets/22425503/935341a4-23a0-446d-8679-e0c020d07daa)

**Comment by cedric-anne** [comment]
Hi,

The `glpi_states.is_visible_cable` column was supposed to be created during migration from 9.5.x to 10.0.0. Did you had a warning, before running the migration, that indicates that database schema was not consistent with the expected one ?

**Comment by roshanroche** [comment]
Hi @cedric-anne 

when i run php bin/console database:check_schema_integrity i get the following 

![image](https://github.com/glpi-project/glpi/assets/22425503/040285d3-407e-4340-88af-841fc10ed5fa)

is there a way i can fix this issue please?

**Comment by cedric-anne** [comment]
You should:
1. Restore the database backup, if any.
2. Run the database integrity check and fix issues.
3. Run the migration.

**Comment by roshanroche** [comment]
Hi @cedric-anne 

how can I fix the database integrity issue? is there any way?

**Comment by cedric-anne** [comment]
> how can I fix the database integrity issue? is there any way?

It can only be fixed manually. The system is not able to know why the database schema is not consistente and, therefore, it is not possible to fix it automaticallly without risking some data loss.

**Comment by trasher** [comment]
see also #11938 ...
