### ISSUE TITLE
Active Directory LDAP: issue while importing users

### ISSUE THREAD

**Issue by wshsenanayaka** [glpi-project/glpi#16184]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 9.5.6

### Bug description

Can not import the users from Active Directory LDAP

### Relevant log output

```shell
Failed Operation
(0 authorizations problems, 1 failures)
170db628-0a6c-47f1-9d3b-cafacfe7592c: Error on executing the action
```

**Comment by trasher** [comment]
GLPI 9.5 is no longer supported, please consider upgrading.

**Comment by VasiliyMooduckovich** [comment]
that is just very f well, what if i don't like the new ui design and i got this very same error after upgrading to the last 9.5 version tag i can tell that something wrong with ldap integration starting to happen the moment we upgraded to 9 version not all of users in AD can be added to glpi db but after the final upgrade it's complete broke down
there u go
https://forum.glpi-project.org/viewtopic.php?id=287699
https://github.com/glpi-project/glpi/issues/892
https://github.com/glpi-project/glpi/issues/8188
