### ISSUE TITLE
Support / tickets / Kanban Global error add column

### ISSUE THREAD

**Issue by bajosega** [glpi-project/glpi#16187]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

When we go to support / tickets and look for the global kanban, when trying to add a column of kanban filters by states, the filters are not displayed, and therefore, they cannot be added. In Debug, the error is not visible, in the JS Console, it seems that the issue is that the data either doesn't arrive or arrives empty, and that's why the filters are not showing.

The error occurs in both a version with data (updated from a previous version) and in a clean installation of version 10.0.10 locally. However, I noticed that the error does not occur in the glpi-network.cloud test network.

![image](https://github.com/glpi-project/glpi/assets/8278087/7fc03db9-5cda-4112-bb30-a8736b9b0377)

**Comment by steph461** [comment]
On version 10.0.10 it didn't work and version 10.0.11 its ok for me
i think I think it must be this image
![image](https://github.com/glpi-project/glpi/assets/68054991/0a76e53c-9c4d-4466-98c8-b9778c75e04f)

**Comment by cedric-anne** [comment]
Fixed in GLPI 10.0.11.

**Comment by bajosega** [comment]
In version 10.0.10 it does not work and I would like to be able to solve it without having to update but if there is no other option I will have to update and see what new errors GLPI has. I hope a solution comes out for version 10.0.10 without having to update.

**Comment by trasher** [comment]
You have to update to fixed version, there is no other way.
