### ISSUE TITLE
“Port connection history” issue

### ISSUE THREAD

**Issue by LucasBERTHIER** [glpi-project/glpi#16189]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

The port connection history on a device's network port is empty even after several SNMP reports (every hour)
![image](https://github.com/glpi-project/glpi/assets/135853226/83117236-a285-4b51-a78b-372a50c3da88)

**Comment by trasher** [comment]
I wonder if it's possible to provide event less information...

Try with latest stable if you reproduce.

**Comment by LucasBERTHIER** [comment]
I didn't understand your answer.
Do you want additional information?

We use the stable version of GLPI 10.0.10 as well as GLPI Agent V1.6.1 which reports every hour.

**Comment by trasher** [comment]
Latest stable release is 10.0.11. If you reproduce, we need more information.

**Comment by steph461** [comment]
I've never used this history but it might be interesting.
I think, It must be these steps

1) Create task snmp ( inventories switch)
![image](https://github.com/glpi-project/glpi/assets/68054991/84b2e310-b63b-433d-ab9f-54a72fe6e976)

2) ![image](https://github.com/glpi-project/glpi/assets/68054991/3b0682f1-5b40-4d5a-90e7-6e6c0e94c12a)
![image](https://github.com/glpi-project/glpi/assets/68054991/9ec94540-26eb-4ad7-b8e9-c12e6c4334eb) update OK

3) ![image](https://github.com/glpi-project/glpi/assets/68054991/6248a166-3fed-47ed-9a82-4809d9127865)

4) ![image](https://github.com/glpi-project/glpi/assets/68054991/01d6c6b8-ee49-4210-9219-138ec2148e46)

Maybe It's used for this history :
port 10 = pc.computer A 17/11/2023, 
port 10 = pc.computer A 20/11/2023
port 10 = pc.computer A 30/11/2023
port 10 = "pc.computer B" or "Printer HP" 18/12/2023 if i switch a new computer or printer maybe ?

**Comment by LucasBERTHIER** [comment]
I updated GLPI to version 10.0.11.
However, the port history is always empty, even after changing the hardware connected to this network socket.

**Comment by Mirkk** [comment]
Hello @trasher ,
We looked in many different Network Devices which have SNMP discovery running since many months (with GLPIInventory Plugin), and all "port connection history" are empty also here. Different Agents till 1.12, GLPI V. 10.0.17.
When something should appear here?

We expected that you can see the connection history if connections were changed and also if connections are down/(no packets sent) for some time and thus the SNMP does no more get the connected MAC address (happens many times).

Moreover, also "Ethernet Port - Historical" is always empty everywhere.

**Comment by trasher** [comment]
@Mirkk this issue is closed since a year. If it's a bug, please open another issue with all information, and example inventory files required to reproduce.
