### ISSUE TITLE
Satisfaction survey for post only

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1619]
http://forum.glpi-project.org/viewtopic.php?id=156302

Specific right was requested for technician and doesn't exist in simplified interface.

adding this new value in both interfaces

**Comment by tomolimo** [comment]
linked to #1371?

**Comment by trasher** [comment]
This is a duplicate of #1371 that has been fixed in the bugfixes branch alreay. Will be fixed in 9.1.2 :)
