### ISSUE TITLE
Password with special characters '\\' do not sign-in on GLPI 

### ISSUE THREAD

**Issue by Brunuz77** [glpi-project/glpi#16195]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.5

### Bug description

In the actual version that im using GLPI, users passwords starting with '\\' (double left slash bar) cannot sign in.
Using Active Directory.

**Comment by trasher** [comment]
Try with latest stable, it may has been resolved.

**Comment by trasher** [comment]
Feel free to reopen if you reproduce with 10.0.11
