### ISSUE TITLE
API HS since the switch to 10.0.10

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#16192]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

2023-12-14 10:00:53] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "name" in /var/www/assistance/src/Api/API.php at line 1725
  Backtrace :
  src/Api/APIRest.php:214                            Glpi\Api\API->searchItems()
  apirest.php:57                                     Glpi\Api\APIRest->call()
  public/index.php:82                                require()

thanks

**Comment by cedric-anne** [comment]
Hi,

Please check if issue persists with GLPI 10.0.11.

Also, you did not provide enough information. We cannot investigate.

**Comment by falco2001** [comment]
Thank you but I can not make a migration of this kind it takes me a lot of time several days to test the plug-in css ... personalized. Do you have a solution?

**Comment by cedric-anne** [comment]
As I said, you did not provide enough information. We cannot investigate, so we cannot even know what is the issue.

**Comment by trasher** [comment]
Testing if case is reproducible on latest stable release is mandatory; there is no need to waste time to investigate if issue is already resolved.
You can test setting up a testing environment on your side.
