### ISSUE TITLE
Error: An error has occurred, but the trace of this error could not recorded because of a problem accessing the log file.

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#16196]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.11

### Bug description

Hello,

i updated the glpi from 10.0.3 to 10.0.11 now while accessing the page im getting the following error

Error: An error has occurred, but the trace of this error could not recorded because of a problem accessing the log file.

where can i find the error? i checked the permissions on the log file it all seems fine.

**Comment by trasher** [comment]
errors are logged in logs files; it is mandatory GLPI can access them. You have to fix your setup.
