### ISSUE TITLE
plug in install error after 10.0.11 upgrade

### ISSUE THREAD

**Issue by grenona** [glpi-project/glpi#16207]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

After i install 10.0.11 i when to plug in i try to install plug inn, i get this error
Plugin archive format is not supported by your system: tbz2.
i try many solution post on the web : install PHAR done, same result

some info: 
/etc/php/8.1/cli/conf.d/20-phar.ini,
Registered PHP Streams => https, ftps, compress.zlib, php, file, glob, data, http, ftp, phar, zip
Phar-based phar archives => enabled
Tar-based phar archives => enabled
ZIP-based phar archives => enabled
phar.cache_list => no value => no value
phar.readonly => On => On
phar.require_hash => On => On

how can i fix this issue

### Anything else?

php log

[Fri Dec 15 14:57:01.506145 2023] [php:warn] [pid 1404514] [client 172.16.25.178:52152] PHP Warning:  Unable to load plugin "barcode" information. in /var/www/html/glpi/src/Plugin.php on line 626, referer: http://172.16.25.171/glpi/front/central.php
[Fri Dec 15 14:57:01.507037 2023] [php:warn] [pid 1404514] [client 172.16.25.178:52152] PHP Warning:  Unable to load plugin "escalade" information. in /var/www/html/glpi/src/Plugin.php on line 626, referer: http://172.16.25.171/glpi/front/central.php
[Fri Dec 15 14:57:01.507612 2023] [php:warn] [pid 1404514] [client 172.16.25.178:52152] PHP Warning:  Unable to load plugin "datainjection" information. in /var/www/html/glpi/src/Plugin.php on line 626, referer: http://172.16.25.171/glpi/front/central.php
[Fri Dec 15 14:57:01.508157 2023] [php:warn] [pid 1404514] [client 172.16.25.178:52152] PHP Warning:  Unable to load plugin "genericobject" information. in /var/www/html/glpi/src/Plugin.php on line 626, referer: http://172.16.25.171/glpi/front/central.php
[Fri Dec 15 14:57:01.508900 2023] [php:warn] [pid 1404514] [client 172.16.25.178:52152] PHP Warning:  Unable to load plugin "itilcategorygroups" information. in /var/www/html/glpi/src/Plugin.php on line 626, referer: http://172.16.25.171/glpi/front/central.php
[Fri Dec 15 14:57:01.509854 2023] [php:warn] [pid 1404514] [client 172.16.25.178:52152] PHP Warning:  Unable to load plugin "mreporting" information. in /var/www/html/glpi/src/Plugin.php on line 626, referer: http://172.16.25.171/glpi/front/central.php

**Comment by trasher** [comment]
Install bz2 extension.
