### ISSUE TITLE
Can't open documents/attachments

### ISSUE THREAD

**Issue by polskigaz** [glpi-project/glpi#16227]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

In GLPI 10.0.10 can't open older document/attachments.
No documents from previous versions of GLPI are available. Only those added in version 10.0.10 can be opened.
They are not available directly from the management-->documents and tickets.

### Page URL

https://sample.sample/front/document.send.php?docid=5732

### Steps To reproduce

Try to open file form tickets or documents (any type):
![image](https://github.com/glpi-project/glpi/assets/152395731/da5ca590-e9de-4074-b54b-75163900fc45)

Then file not found,
![image](https://github.com/glpi-project/glpi/assets/152395731/a5c31e42-7611-4eb7-9499-0c9cde422363)

### Your GLPI setup information

GLPI 10.0.10 ( => /usr/share/glpi)
Installation mode: TARBALL
Current language:pl_PL

Operating system: Linux pg-glpi.polskigaz.pl 6.2.12-200.fc37.x86_64 #​1 SMP PREEMPT_DYNAMIC Thu Apr 20 23:38:29 UTC 2023 x86_64
PHP 8.1.24 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, event, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, intl, json, ldap, libxml, lzf,
	mbstring, mysqli, mysqlnd, openssl, pcov, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="10M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.57 (Fedora Linux) OpenSSL/3.0.8 mod_perl/2.0.12 Perl/v5.36.1 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Server Software: MariaDB Server
	Server Version: 10.5.22-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiu@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.24) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.22) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /usr/share/glpi/files/_cache has been validated.
Write access to /usr/share/glpi/config has been validated.
Write access to /usr/share/glpi/files/_cron has been validated.
Write access to /usr/share/glpi/files has been validated.
Write access to /usr/share/glpi/files/_dumps has been validated.
Write access to /usr/share/glpi/files/_graphs has been validated.
Write access to /usr/share/glpi/files/_lock has been validated.
Write access to /usr/share/glpi/files/_pictures has been validated.
Write access to /usr/share/glpi/files/_plugins has been validated.
Write access to /usr/share/glpi/files/_rss has been validated.
Write access to /usr/share/glpi/files/_sessions has been validated.
Write access to /usr/share/glpi/files/_tmp has been validated.
Write access to /usr/share/glpi/files/_uploads has been validated.
SELinux configuration is OK.

Web server root directory configuration seems safe.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

**Comment by trasher** [comment]
Most of the time, files directory has been missed during upgrade. Also, 10.0.10 is not the latest stable.

**Comment by polskigaz** [comment]
Is there any solution for this?
Do you need to add or replace any files in version 10.0.10?
this is a huge problem for us.

**Comment by trasher** [comment]
"Most of the time, files directory has been missed during upgrade." => this means you did not copy the `files` directory from your old instance.
