### ISSUE TITLE
Personal view no load

### ISSUE THREAD

**Issue by guillermohaad** [glpi-project/glpi#1622]
I have of version 0.90.3 and When I open start does not load personal view, Attached evidence: 
![image](https://cloud.githubusercontent.com/assets/12921805/21992068/046b7064-dbe3-11e6-8509-b689a51c0934.png)

**Comment by trasher** [comment]
Please check the log files (glpi/giles/_logs). Also, there are chances your issue has been solved since.

**Comment by guillermohaad** [comment]
Hi, @trasher 
The strange thing is that it came working well and from one day to the next stopped working?
_log does not report anything abnormal.

Also If I consult the tickets assigned to a particular technician, the connection falls after a while.

![image](https://cloud.githubusercontent.com/assets/12921805/22021656/704170b4-dc8c-11e6-869c-43a172c2f46a.png)

**Comment by guillermohaad** [comment]
Hi @trasher, 
Detect that the problem is the table glpi_tickets; because I
Install another instance of GLPI with this table empty and works perfect.

what is this about? how can I solve that?

thank you

**Comment by trasher** [comment]
I do not have any idea what is wrong, sorry.

You should test with 0.90.5 in the first time, and maybe with 9.1.1 to see if the problem still happens.

**Comment by guillermohaad** [comment]
Hi @trasher , Already test with 9.1.1 but same, the problem is the table glpi_tickets ??

**Comment by trasher** [comment]
Have you tried to repair/optimize this table? I do not see why it would cause you issues; but it seems that table or maybe something it contains specifically is wrong.... Without any errors an now way to reproduce, it is hard to guess :/

**Comment by guillermohaad** [comment]
@trasher , And repair and optimize and stay the same
Very strange this problem because I have been working with Glpi for more than 3 years.
The table weighs only 60 MB
