### ISSUE TITLE
HTML/CSS content error mail notification

### ISSUE THREAD

**Issue by Loopers29** [glpi-project/glpi#16247]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hi guys,
Thanks for your beautiful work !!

For many years I've been using custom code for my e-mail notifications.
Since I switched to GLPI 10, my notification templates no longer work. After extensive testing, [including testing the generic code in the GLPI documentation](https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/notifications/template_example.html#code-in-email-html-body-field:~:text=Code%20dans%20le%20champ%20%C2%AB%20Corps%20HTML%20de%20l%27e%2Dmail%20%C2%BB), I get the code in my mail body instead of my design.
I also use the Oauth IMAP plugin to connect to our support mailbox via Azure.

Here's the code I'm trying to implement : 
HTML + CSS compiled : 
```
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap" rel="stylesheet">
<style>
body {
font-family: 'Roboto', Arial, sans-serif;
font-weight: 300;
background-color: #f4f4f4;
margin: 0;
padding: 0;
}


.container {
max-width: 600px;
margin: 20px auto;
background-color: #fff;
padding: 20px;
border-radius: 5px;
box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}


.header {
background-color: #048D45;
padding: 3px;
color: #fff;
text-align: center;
border-radius: 5px 5px 0 0;
}


.header h1 {
font-weight: 700;
}


.logo {
max-width: 150px;
margin-bottom: 1px;
}


.content {
padding: 20px;
font-size: 16px;
line-height: 1.5;
}


.footer {
margin-top: 20px;
padding: 20px;
background-color: #ecf0f1;
text-align: center;
font-size: 14px;
border-radius: 0 0 5px 5px;
}


.ticket-info {
margin-top: 10px;
}


.ticket-info span {
font-weight: 700;
}


.footer-message {
display: inline-block;
}
</style>
</head>
<body>
<div class="container">
<div class="header">
<img src="URL LOGO ENTREPRISE" alt="Logo Enterprise" class="logo">
<h1>Support XXX Entreprise</h1>
</div>
<div class="content">
<p>Cher(e) ##ticket.authors##,</p>
<p>Merci d'avoir contacté notre service d'assistance informatique. Nous avons reçu votre demande/incident et nous mettons tout en œuvre pour vous apporter une solution dans les meilleurs délais.</p>
<p>Voici les informations concernant votre ticket :</p>
<div class="ticket-info">
<p>Numéro du Ticket :<span> ##ticket.id##</span></p>
<p>Sujet :<span> ##ticket.title##</span></p>
<p>Date de Création :<span> ##ticket.creationdate##</span></p>
</div>
<p>Notre équipe technique examinera votre demande et vous contactera dès que possible. Nous vous remercions pour votre patience.</p>
<p>Si vous avez des informations supplémentaires à fournir ou si vous souhaitez mettre à jour votre demande, veuillez répondre directement à ce message.</p>
</div>
<div class="footer">
<span class="footer-message">Nous vous souhaitons une agréable journée de la part de toute l'équipe XXX Entreprise</span>
</div>
</div>
</body>
</html>

```
HTML + CSS compiled test 2 : 
```
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap" rel="stylesheet">
</head>
<body style="font-family: 'Roboto', Arial, sans-serif; font-weight: 300; background-color: #f4f4f4; margin: 0; padding: 0;">
<div style="max-width: 600px; margin: 20px auto; background-color: #fff; padding: 20px; border-radius: 5px; box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);">
<div style="background-color: #048D45; padding: 3px; color: #fff; text-align: center; border-radius: 5px 5px 0 0;">
<img src="URL LOGO ENTREPRISE" alt="Logo Entreprise" style="max-width: 150px; margin-bottom: 1px;">
<h1 style="font-weight: 700;">Support XXX Entreprise</h1>
</div>
<div style="padding: 20px; font-size: 16px; line-height: 1.5;">
<p>Cher(e) ##ticket.authors##,</p>
<p>Merci d'avoir contacté notre service d'assistance informatique. Nous avons reçu votre demande/incident et nous mettons tout en œuvre pour vous apporter une solution dans les meilleurs délais.</p>
<p>Voici les informations concernant votre ticket :</p>
<div style="margin-top: 10px;">
<p>Numéro du Ticket :<span style="font-weight: 700;"> ##ticket.id##</span></p>
<p>Sujet :<span style="font-weight: 700;"> ##ticket.title##</span></p>
<p>Date de Création :<span style="font-weight: 700;"> ##ticket.creationdate##</span></p>
</div>
<p>Notre équipe technique examinera votre demande et vous contactera dès que possible. Nous vous remercions pour votre patience.</p>
<p>Si vous avez des informations supplémentaires à fournir ou si vous souhaitez mettre à jour votre demande, veuillez répondre directement à ce message.</p>
</div>
<div style="margin-top: 20px; padding: 20px; background-color: #ecf0f1; text-align: center; font-size: 14px; border-radius: 0 0 5px 5px;">
<span style="display: inline-block;">Nous vous souhaitons une agréable journée de la part de toute l'équipe XXX Entreprise</span>
</div>
</div>
</body>
</html>
```

I also tested separating HTML and CSS and putting them directly in the appropriate fields : 
HTML : 
```
<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="header">
        <img src="URL LOGO ENTREPRISE" alt="Logo XXX Entreprise" class="logo">
        <h1>Support XXX Entreprise</h1>
    </div>
    <div class="content">
        <p>Cher(e) ##ticket.authors##,</p>
        <p>Merci d'avoir contacté notre service d'assistance informatique. Nous avons reçu votre demande/incident et nous mettons tout en œuvre pour vous apporter une solution dans les meilleurs délais.</p>
        <p>Voici les informations concernant votre ticket :</p>
        <div class="ticket-info">
            <p>Numéro du Ticket :<span> ##ticket.id##</span></p>
            <p>Sujet :<span> ##ticket.title##</span></p>
            <p>Date de Création :<span> ##ticket.creationdate##</span></p>
        </div>
        <p>Notre équipe technique examinera votre demande et vous contactera dès que possible. Nous vous remercions pour votre patience.</p>
        <p>Si vous avez des informations supplémentaires à fournir ou si vous souhaitez mettre à jour votre demande, veuillez répondre directement à ce message.</p>
    </div>
    <div class="footer">
        <span class="footer-message">Nous vous souhaitons une agréable journée de la part de toute l'équipe XXXX Entreprise</span>
    </div>
</div>
</body>
</html>
```

CSS : 
```
body {
    font-family: 'Roboto', Arial, sans-serif;
    font-weight: 300;
    background-color: #f4f4f4;
    margin: 0;
    padding: 0;
}

.container {
    max-width: 600px;
    margin: 20px auto;
    background-color: #fff;
    padding: 20px;
    border-radius: 5px;
    box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
}

.header {
    background-color: #048D45;
    padding: 3px;
    color: #fff;
    text-align: center;
    border-radius: 5px 5px 0 0;
}

.header h1 {
    font-weight: 700;
}

.logo {
    max-width: 150px;
    margin-bottom: 1px;
}

.content {
    padding: 20px;
    font-size: 16px;
    line-height: 1.5;
}

.footer {
    margin-top: 20px;
    padding: 20px;
    background-color: #ecf0f1;
    text-align: center;
    font-size: 14px;
    border-radius: 0 0 5px 5px;
}

.ticket-info {
    margin-top: 10px;
}

.ticket-info span {
    font-weight: 700;
}

.footer-message {
    display: inline-block;
}

```

I've tried removing the links to the Google fonts, but that doesn't work either.
Is this a bug?

### Relevant log output

```shell
no error
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.10 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux vps-8452fc2b 5.10.0-26-cloud-amd64 #​1 SMP Debian 5.10.197-1 (2023-09-29) x86_64
PHP 8.2.11 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at support.xxx.fr Port 443
)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.21-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiuserdb@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.11) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.21) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10@05de68add675fb55abaeec10f3a2552085594a16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+OAUTH (support@xxx.fr@outlook.office365.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.7     State: Not installed                           
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	phpsaml              Name: PHP SAML                       Version: 1.2.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
I cannot recreate the issue, at least to the point where the notification HTML is added to the message for the PHPMailer library to send. The message body appears to be the entire, valid HTML from your first example.I don't have a mailbox configured to receive notifications. Can you provide the source for the email (the eml file) notification you receive? You can redact any email addresses or other sensitive information in the saved email.

**Comment by Loopers29** [comment]
Hi cconard96,

Thanks for your answer.
I've added the EML file to this answer.
[[GLPI #0000041] Réponse automatique - Ticket d'Assistance 0000041.eml.zip](https://github.com/glpi-project/glpi/files/13858002/GLPI.0000041.Reponse.automatique.-.Ticket.d.Assistance.0000041.eml.zip)

Here's a screenshot of what I get in the mail :  
<img width="937" alt="Screenshot 2024-01-08 at 09 59 26" src="https://github.com/glpi-project/glpi/assets/55393114/7b3cdfab-1699-4cef-ac84-8942f37a4ffc">

In this case, we're not using PHPMailer but the OAuth IMAP plugin, as specified in my initial message.

Thanks again for your help.

**Comment by Loopers29** [comment]
Hi @cconard96 
Did you have time to look at this subject please ? 
We're really stuck. My boss wants us to go into production.
Thanks a lot for your help!

**Comment by verdanatech-marcio** [comment]
Hi @Loopers29. The php mailer, the library responsible for sending GLPi emails, does not support this type of CSS declaration. Styles must be applied to elements using inline css

**Comment by Loopers29** [comment]
I did it! It's just that, stupidly, I was entering my code directly into the "HTML body of the e-mail" field instead of pressing the red-circled button in my screen to do it in the tab dedicated to that ... 
![Screenshot 2024-01-29 at 17 43 31](https://github.com/glpi-project/glpi/assets/55393114/4708512e-eae7-4974-ba6c-e705a51a605b)
