### ISSUE TITLE
duplication of software information in the inventory history

### ISSUE THREAD

**Issue by lucasolerr** [glpi-project/glpi#16255]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hi, everybody,
I again have a problem with the duplication of software information in the inventory history as it was previously with the case here https://github.com/glpi-project/glpi/issues/14602 and https://github.com/glpi-project/glpi/issues/14696. In this case, the problem is with all the softwares of my machines.
![image](https://github.com/glpi-project/glpi/assets/92515171/01f2b4a7-ea11-4a15-b128-0b4eca1045ae)

### Your GLPI setup information

GLPI 10.0.10 ( =>)
Installation mode: TARBALL
Current language:fr_FR

**Comment by keguira** [comment]
After seeing your issue, I encoutered some duplicated too.
I can provide more examples if needed.

At first, i thought it was due to non-breaking spaces but your examples does not seems to have one.

**Comment by trasher** [comment]
We need more informaiton, and reproducible case from a blank installation.

**Comment by trasher** [comment]
Also, try on latest stable release.
