### ISSUE TITLE
Used item history unavailable from User view

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#16258]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When an item is being assigned to a person, it shows up under "Used items" list in person view, but there's no entry about used items under person's historical view. On the other hand, if an asset's history is being viewed, history tab shows the history of users to whom the asset was/is assigned to.

### Page URL

/front/user.form.php

### Steps To reproduce

1. Open a computer
2. Assign a user to computer
3. Observe from user's view that computer is shown under "used items"
4. Observe that there's no entry of asset being assigned to user under "Historical" tab in user view
5. Observe from computer view, that it is visible from "Historical" tab to whom the computer was assigned to

### Your GLPI setup information

GLPI 10.0.11
GLPI GenericObject Plugin 2.14.8
GLPI Fields plugin 1.21.6
GLPI Inventory Plugin 1.3.4

### Anything else?

This would enable to track what has been ever assigned to user during the user's whole GLPI lifecycle, also this would enable a lot easier tracking of assets - for example assets were assigned to someone else by mistake or by somekind of automation mistake. Currently one has to know the asset name/number first.

**Comment by AldarisPale** [comment]
Bumping, as bot closed this for being stale. Problem is still there though.

**Comment by vmorozovunl** [comment]
Bumping this issue too. Either there should be a history in "Used items" or rename the category to "Items currently in use".

**Comment by AldarisPale** [comment]
Posting here to prevent auto-closure of ticket, as problem still persists.

**Comment by cconard96** [comment]
Not a bug IMO. Just a missing feature.

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
