### ISSUE TITLE
Software License Overview: remove "name - " in Serial number and Comments field & show whole comment

### ISSUE THREAD

**Issue by michaelschufi** [glpi-project/glpi#1628]
Hi

I would like to alter the license overview, so the name doesn't get printed in the Serial and Comments fields. 

Additionally, I would like GLPI to show the whole comment instead of limiting the text shown in the overview to a certain number of lines/characters.

Where can I customize this? If it's not possible in the GUI, where can I do it in the code?

GLPI Version 9.1.1

**Comment by trasher** [comment]
I don't think this is possible from the UI.

In the code, it's probably somewhere in the SoftwareLicense class.
