### ISSUE TITLE
No more access to history in ticket or on computers 

### ISSUE THREAD

**Issue by plburguet** [glpi-project/glpi#16285]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

Since the last update, a technician told me that they are no longer able to see the history within a ticket.
after further investigation, it appears that there is also no more access to the history on the computers.
![image](https://github.com/glpi-project/glpi/assets/52488995/7d650c8a-bb7c-4f65-809f-d0f159518a3c)

### Steps To reproduce

Go to a ticket
Check if history is available

### Your GLPI setup information

GLPI 10.0.11
PHP 8.2.14

### Anything else?

I found a way around to give back the access to that menu, by allowing technician profile to read all the log in the administration tab

![image](https://github.com/glpi-project/glpi/assets/52488995/56bb1a42-e4b5-4364-aa63-a883220dc6f3)
But by enabling this, they also get that menu, which is unnecessary for them and provides too much info
![image](https://github.com/glpi-project/glpi/assets/52488995/4273e3cf-e32b-4ad1-8fa7-1a325e05c443)

**Comment by StbanMc** [comment]
When navigating through the items, I am unable to view the history for tickets or computers."

**Comment by cedric-anne** [comment]
The limitation was introduced by #15877. A better rights management will be introduced in GLPI 10.0.12, see #16286 .

**Comment by SkoEdi** [comment]
Same issue in 10.0.18
