### ISSUE TITLE
Undefined array key "is_recursive" in src/CommonDBTM.php

### ISSUE THREAD

**Issue by tizianosartori** [glpi-project/glpi#16294]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.11

### Bug description

When I run crontask id 4 "software" the result is "Execution error"

### Relevant log output

```shell
[php:warn] [pid 2638860] [client xxxxx] PHP Warning:  Undefined array key "is_recursive" in /var/www/glpi_www/src/CommonDBTM.php on line 3202, referer: xxxxx/front/crontask.form.php?id=4
```

### Page URL

/front/crontask.form.php?id=4

### Steps To reproduce

1. Start task execution
2. Read logs

### Your GLPI setup information

<details><summary>Informazioni sul sistema, l'installazione e la configurazione</summary><pre>GLPI 10.0.11 ( => /myfolder/glpi_www)
Installation mode: TARBALL
Current language:it_IT

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 6.1.0-13-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64
PHP 8.2.12 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlsrv, posix, random, readline, session, shmop, sockets, sodium, sqlsrv, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" disable_functions="" 
Software: Apache/2.4.57 (Debian) (Apache/2.4.57 (Debian) Server at glpi.amambiente.it Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.30
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@10.0.49.5/glpi
	Host info: 10.0.49.5 via TCP/IP
	
PHP version (8.2.12) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /myfolder/glpi_files/_cache has been validated.
Write access to /myfolder/glpi_files/_cron has been validated.
Write access to /myfolder/glpi_files has been validated.
Write access to /myfolder/glpi_files/_dumps has been validated.
Write access to /myfolder/glpi_files/_graphs has been validated.
Write access to /myfolder/glpi_files/_lock has been validated.
Write access to /myfolder/glpi_files/_pictures has been validated.
Write access to /myfolder/glpi_files/_plugins has been validated.
Write access to /myfolder/glpi_files/_rss has been validated.
Write access to /myfolder/glpi_files/_sessions has been validated.
Write access to /myfolder/glpi_files/_tmp has been validated.
Write access to /myfolder/glpi_files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /myfolder/glpi_www/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/myfolder/glpi_www"
GLPI_CONFIG_DIR: "/myfolder/glpi_config"
GLPI_VAR_DIR: "/myfolder/glpi_files"
GLPI_MARKETPLACE_DIR: "/myfolder/glpi_www/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/myfolder/glpi_files"
GLPI_CACHE_DIR: "/myfolder/glpi_files/_cache"
GLPI_CRON_DIR: "/myfolder/glpi_files/_cron"
GLPI_DUMP_DIR: "/myfolder/glpi_files/_dumps"
GLPI_GRAPH_DIR: "/myfolder/glpi_files/_graphs"
GLPI_LOCAL_I18N_DIR: "/myfolder/glpi_files/_locales"
GLPI_LOCK_DIR: "/myfolder/glpi_files/_lock"
GLPI_LOG_DIR: "/myfolder/glpi_files/_log"
GLPI_PICTURE_DIR: "/myfolder/glpi_files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/myfolder/glpi_files/_plugins"
GLPI_RSS_DIR: "/myfolder/glpi_files/_rss"
GLPI_SESSION_DIR: "/myfolder/glpi_files/_sessions"
GLPI_TMP_DIR: "/myfolder/glpi_files/_tmp"
GLPI_UPLOAD_DIR: "/myfolder/glpi_files/_uploads"
GLPI_INVENTORY_DIR: "/myfolder/glpi_files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/myfolder/glpi_www/locales"
GLPI_VERSION: "10.0.11"
GLPI_SCHEMA_VERSION: "10.0.11@6795e1eea6621428b5ef42350d555715bda8a96f"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/myfolder/glpi_www/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/myfolder/glpi_www/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/myfolder/glpi_www/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/myfolder/glpi_www/marketplace/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/myfolder/glpi_www/vendor/michelf/php-markdown/Michelf)
true/punycode in (/myfolder/glpi_www/vendor/true/punycode/src)
iamcal/lib_autolink in (/myfolder/glpi_www/vendor/iamcal/lib_autolink)
sabre/dav in (/myfolder/glpi_www/vendor/sabre/dav/lib/DAV)
sabre/http in (/myfolder/glpi_www/vendor/sabre/http/lib)
sabre/uri in (/myfolder/glpi_www/vendor/sabre/uri/lib)
sabre/vobject in (/myfolder/glpi_www/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/myfolder/glpi_www/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/myfolder/glpi_www/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/myfolder/glpi_www/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/myfolder/glpi_www/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/myfolder/glpi_www/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/myfolder/glpi_www/vendor/elvanto/litemoji/src)
symfony/console in (/myfolder/glpi_www/vendor/symfony/console)
scssphp/scssphp in (/myfolder/glpi_www/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/myfolder/glpi_www/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/myfolder/glpi_www/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/myfolder/glpi_www/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/myfolder/glpi_www/vendor/ramsey/uuid/src)
psr/log in (/myfolder/glpi_www/vendor/psr/log/Psr/Log)
psr/simple-cache in (/myfolder/glpi_www/vendor/psr/simple-cache/src)
psr/cache in (/myfolder/glpi_www/vendor/psr/cache/src)
league/csv in (/myfolder/glpi_www/vendor/league/csv/src)
mexitek/phpcolors in (/myfolder/glpi_www/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/myfolder/glpi_www/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/myfolder/glpi_www/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/myfolder/glpi_www/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/myfolder/glpi_www/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/myfolder/glpi_www/vendor/paragonie/sodium_compat/src)
symfony/cache in (/myfolder/glpi_www/vendor/symfony/cache)
html2text/html2text in (/myfolder/glpi_www/vendor/html2text/html2text/src)
symfony/css-selector in (/myfolder/glpi_www/vendor/symfony/css-selector)
symfony/dom-crawler in (/myfolder/glpi_www/vendor/symfony/dom-crawler)
twig/twig in (/myfolder/glpi_www/vendor/twig/twig/src)
twig/string-extra in (/myfolder/glpi_www/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/myfolder/glpi_www/vendor/symfony/polyfill-php82)
league/oauth2-client in (/myfolder/glpi_www/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/myfolder/glpi_www/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/myfolder/glpi_www/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap://10.0.49.1', Port: '636', BaseDN: 'DC=stet,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=Nagios,CN=Users,DC=stet,DC=local', Use TLS: none
Server: 'ldap://10.0.69.1', Port: '389', BaseDN: 'DC=amnu,DC=dominio', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=Nagios,CN=Users,DC=amnu,DC=dominio', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@10.0.49.4)

</pre></details><details><summary>Plugins list</summary><pre> 
	datainjection        Name: Data Injection                 Version: 2.13.4     State: Installed / not activated               
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.1.2      State: Installed / not activated               
		Install Method: Marketplace
	addressing           Name: Indirizzamento IP              Version: 3.0.1      State: Installed / not activated               
		Install Method: Marketplace
	jsaddons             Name: JS Addons                      Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: More Reporting                 Version: 1.8.5      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Enabled                                 
		Install Method: Marketplace
	pdf                  Name: Stampa in PDF                  Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	treeview             Name: Visualizzazione struttura      Version: 1.10.2     State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

**Comment by AdrienClairembault** [comment]
Should be fixed by #16303
