### ISSUE TITLE
Tickets Followup ID goes on ticket 2147483647 - behavior plugin

### ISSUE THREAD

**Issue by Castelsarrasin** [glpi-project/glpi#16310]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

9.3.4

### Bug description

When i update 9.3.4 to 9.4.2, then all the followup (more than 1000) gone in the ticket ID 2147483647
I know this problem, it's an INT database. I had to move on BIGINT database type the ticket ID.
I saw on the scripts update_940_941.php and update_941_942.php there are some change ID.
I suspect that ins this migration it's going to a temporary database column with INT, so all tickets ID > to 2147483647 who has some followup, are moving to the max and then when it come to the new column, it change the ID.

### Relevant log output

```shell
I have no capture or logs, i just can tell you that the ticket ID who is 2147483647 normally have 1 followup.
After i migrate there are 1009 followup and all other tickets don't have anymore followup (except the files or before 2147483647).
```

### Steps To reproduce

Install glpi 9.3.4, install behavior plugin, select the ymd0001 format.
Create a ticket and add some followup with and without files uploaded.

Upgrade glpi 9.3.4 to 9.4.2 and then you'll see the followup will disapear.
To me i can see them because i have a ticket ID 2147483647.

### Your GLPI setup information

plugin behavior + fields + LDAP lync

### Anything else?

I would love you help me i can't upgrade my glpi to the last security patches.

**Comment by cconard96** [comment]
We don't track issues for plugins here. Also, GLPI 9.3 and 9.4 are both not supported anymore. You may still seek assistance on the community forum though.
https://forum.glpi-project.org/index.php
