### ISSUE TITLE
Graphical issue Printer counter

### ISSUE THREAD

**Issue by TheRoby** [glpi-project/glpi#16321]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

Hi
I have more counter (color ...) than total for 3 days, but the graphic is not right
![graphique](https://github.com/glpi-project/glpi/assets/6053818/6a47258d-046b-44cd-a4d9-81a76d8cc089)
![database](https://github.com/glpi-project/glpi/assets/6053818/f7b3ddf0-6651-45e1-904d-944fef7024ea)
(since https://github.com/glpi-project/glpi-agent/issues/574)

### Page URL

https://glpi/front/printer.form.php?id=xxx

### Your GLPI setup information

Last nightly build of glpi-agent, but the database seems to be on the right time, so ... :)

**Comment by TheRoby** [comment]
https://github.com/glpi-project/glpi/compare/10.0/bugfixes...TheRoby:glpi:patch-1

**Comment by cedric-anne** [comment]
Fixed in #16386.
