### ISSUE TITLE
Validation request approval redirects to blank page

### ISSUE THREAD

**Issue by namtarkur** [glpi-project/glpi#16327]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

After granting a validation approval to related request by clicking approve button, GLPI redirects to a blank page. Besides that, approval is granted but this redirection is inconvenient.

### Relevant log output

```shell
[2024-01-08 13:41:45] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: CommonITILValidation::computeValidation(): Argument #3 ($validation_percent) must be of type int, null given, called in \glpi\src\CommonITILValidation.php on line 1516 in \glpi\src\CommonITILValidation.php at line 1533
  Backtrace :
  src\CommonITILValidation.php:1516                  CommonITILValidation::computeValidation()
  src\CommonITILValidation.php:451                   CommonITILValidation::computeValidationStatus()
  src\CommonDBTM.php:1721                            CommonITILValidation->post_updateItem()
  front\commonitilvalidation.form.php:112            CommonDBTM->update()
  front\ticketvalidation.form.php:40                 include()
  
[2024-01-08 13:45:59] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "validation_percent" in \glpi\src\CommonITILValidation.php at line 1497
  Backtrace :
  src\CommonITILValidation.php:451                   CommonITILValidation::computeValidationStatus()
  src\CommonDBTM.php:1721                            CommonITILValidation->post_updateItem()
  front\commonitilvalidation.form.php:113            CommonDBTM->update()
  front\ticketvalidation.form.php:40                 include()
  
[2024-01-08 13:45:59] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: CommonITILValidation::computeValidation(): Argument #3 ($validation_percent) must be of type int, null given, called in \glpi\src\CommonITILValidation.php on line 1516 in \glpi\src\CommonITILValidation.php at line 1533
  Backtrace :
  src\CommonITILValidation.php:1516                  CommonITILValidation::computeValidation()
  src\CommonITILValidation.php:451                   CommonITILValidation::computeValidationStatus()
  src\CommonDBTM.php:1721                            CommonITILValidation->post_updateItem()
  front\commonitilvalidation.form.php:113            CommonDBTM->update()
  front\ticketvalidation.form.php:40                 include()
```

### Page URL

https://localhost/glpi/front/ticketvalidation.form.php

### Steps To reproduce

1. Create new ticket.
2. Go to new created ticked and click on right side of Answer button, placed on bottom of the page,  to choose option: Ask for validation. 
3. Validation Request  form will appear 
4. In  Validation Request  set as Approver the same person as Requester, add comment and click Add button.
5.  Validation Request Ansewer form will appear.
6. In Validation Request Ansewer please add comment and click on Approve or Refuse button.
7. Blank page appears.

### Your GLPI setup information

Information about system installation and configuration

GLPI 10.0.10 (/glpi => \glpi)
Installation mode: TARBALL
Current language:en_GB

Server

 
Operating system: Windows NT 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.2.1 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, random, readline, session, soap, sodium, standard, tidy, tokenizer, xml, xmlreader, xmlwriter,
	zend_test, zip, zlib)
Setup: max_execution_time="600" memory_limit="4096M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0
Server Software: mariadb.org binary distribution
	Server Version: 10.6.8-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.2.1) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.8) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to \glpi/files/_cache has been validated.
Write access to \glpi/config has been validated.
Write access to \glpi/files/_cron has been validated.
Write access to \glpi/files has been validated.
Write access to \glpi/files/_dumps has been validated.
Write access to \glpi/files/_graphs has been validated.
Write access to \glpi/files/_lock has been validated.
Write access to \glpi/files/_pictures has been validated.
Write access to \glpi/files/_plugins has been validated.
Write access to \glpi/files/_rss has been validated.
Write access to \glpi/files/_sessions has been validated.
Write access to \glpi/files/_tmp has been validated.
Write access to \glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "\glpi":
‣ "\glpi/files" ("GLPI_VAR_DIR")
‣ "\glpi\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "\glpi\public".
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to \glpi/marketplace has been validated.
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.

GLPI constants

 
GLPI_ROOT: "\\glpi"
GLPI_CONFIG_DIR: "\\glpi/config"
GLPI_VAR_DIR: "\\glpi/files"
GLPI_MARKETPLACE_DIR: "\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "\\glpi/files"
GLPI_CACHE_DIR: "\\glpi/files/_cache"
GLPI_CRON_DIR: "\\glpi/files/_cron"
GLPI_DUMP_DIR: "\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "\\glpi/files/_locales"
GLPI_LOCK_DIR: "\\glpi/files/_lock"
GLPI_LOG_DIR: "\\glpi/files/_log"
GLPI_PICTURE_DIR: "\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "\\glpi/files/_plugins"
GLPI_RSS_DIR: "\\glpi/files/_rss"
GLPI_SESSION_DIR: "\\glpi/files/_sessions"
GLPI_TMP_DIR: "\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "\\glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10@05de68add675fb55abaeec10f3a2552085594a16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

### Anything else?

The same problem has been described in ticket: https://github.com/glpi-project/glpi/issues/9999. Mentioned ticket was closed so I have been asked to created a new one. 

![Zrzut ekranu z 2024-01-08 12-46-35](https://github.com/glpi-project/glpi/assets/24360197/d22dc5f8-1d8e-4530-b575-2df52fde9c66)
![Zrzut ekranu z 2024-01-08 12-47-54](https://github.com/glpi-project/glpi/assets/24360197/d7a13434-acce-4730-80da-63c1693e4e86)
![Zrzut ekranu z 2024-01-08 12-48-13](https://github.com/glpi-project/glpi/assets/24360197/49168656-47c0-41fd-aa44-5b7fec84da2e)

**Comment by cedric-anne** [comment]
This error does not make sense to me. The `validation_percent` field is not supposed to be nullable in database, so the value passed here is not supposed to be something else than an integer.

Could you execute the `bin/console database:check` command and give the result?

**Comment by namtarkur** [comment]
Adding results as attachment:
[glpi.log](https://github.com/glpi-project/glpi/files/13922222/glpi.log)

**Comment by cconard96** [comment]
Your DB schema is not correct. The global validation column for tickets and changes hasn't been "varchar(255) DEFAULT 'none'" since before GLPI 0.85. You will need to make the adjustment to the correct column schemas manually. It should be "int NOT NULL DEFAULT 1".

You also have a bunch of missing columns which could cause issues later. For example, you are missing the "documents" column for queued notifications so I guess you will never get related documents/attachments in your notifications.

**Comment by namtarkur** [comment]
So something went wrong during upgrades... It is strange because we have upgraded glpi from version to version. 
Are incorrect column schemas the only cause of this issue? In example apart of schemas adjustment do I need to add values to missing columns?

**Comment by trasher** [comment]
There is no way to know how a broken database will act... You have to fix your database schema, and then check if your issue is solved
