### ISSUE TITLE
Item type dropdown when assigning item to a rack position

### ISSUE THREAD

**Issue by yild** [glpi-project/glpi#16324]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

'New item - item" window while assigning item to rack position:

Item types dropdown list display only first six positions, while adding multiple passive devives or pdu user need to scroll dropdown every time.

![obraz](https://github.com/glpi-project/glpi/assets/19593025/867eaba4-f240-49b6-941b-6bb888106674)

This list is small and should list all item types without need to search (scroll) for them.

Tested on Mozilla Firefox, Chrome and Edge.

### Relevant log output

```shell
No log
```

**Comment by cconard96** [comment]
This is not a bug.
Also, you can change the number of options needed to be in a dropdown before the search box appears in General > Setup > General if you want to filter the options without scrolling.
