### ISSUE TITLE
error 500 during add project task

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1634]
Hello

When I add a project task I have a 500 error

**Comment by AnaelMobilia** [comment]
Hello,

Error 500 is an error from your web server configuration.
You should found more logs on your web server log files (you are running IIS 8.5 of memory)

Regards

**Comment by tomolimo** [comment]
Hello
Try to setup the failed request tracing, and wait for the next error. 
Thank you 
Regards 
Tomolimo
