### ISSUE TITLE
Items Locks in-browser notification URL

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#16348]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When you enable the items locks functionality and set the browser notification for ask a user to take the control of that object, when you click on the notification toast it open a URL that is referring to the locks instead of the object locked (computer, ticket or so on).

### Page URL

https://####/glpi/front/objectlock.form.php?id=1852

### Steps To reproduce

1. enable browser notification for lock items
2. Open an object that is locked from another user
3. Ask to unlock
4. (from the users that own the lock) click on the notification toast in the browser
5. It open a blank tab referring to the url ...glpi/front/objectlock.form.php?id=1852

**Comment by cconard96** [comment]
I'm not able to recreate the issue. The URL is correctly set to "/?redirect=Ticket_1728" for me. Please check the template set for this notification.

**Comment by ArriMa** [comment]
Hi, I've checked the template but no reference to the URL. Here my template:
![immagine](https://github.com/glpi-project/glpi/assets/16684500/feca8504-b9ee-4355-af76-90ba1b004e59)
