### ISSUE TITLE
Items locks alert

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#16349]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When the feature items locks is enabled and open an object locked from another user, there is a possibility to tick an option "Alert me when unlocked".
In the notifications there isn't an event that trigger that kind of notification (I would like to create a browser notification).
The only event related to the locks is "Unlock Item Request".

How this option works? In which way I can be alerted when the object is now available to use?

**Comment by cconard96** [comment]
The alert is merely client-side. If you leave the tab open, it will occasionally check if it is still locked. When it becomes unlocked, it will display an alert on the page. If you need further help with this feature, please use the community forum.
