### ISSUE TITLE
[GLPI 9.1] Acces denied when create ticket

### ISSUE THREAD

**Issue by JonasRoux** [glpi-project/glpi#1637]
Hi
Since 9.1, we can't create ticket from user account view. The creating page start but when we try to change the ticket type or the category, we got an Acces denied :  "The action you have requested is not allowed."
This work fine from Assistance/New ticket

**Comment by tyronewyatt** [comment]
Just upgraded to GLPI 9.1.1 and I'm also experiencing this issue.
Unfortunately this is the method I normally use to create tickets as it gives me a chance to look at the requester past tickets to check for ongoing issues.
I also tested without plugins enabled and it still occurred .

**Comment by tyronewyatt** [comment]
Looks like is duplicate with https://github.com/glpi-project/glpi/issues/1078

**Comment by trasher** [comment]
This indeed duplicates #1078; that has been fixed as of GLPI 9.1.2.
