### ISSUE TITLE
GLPI does not escape emojis in tickets

### ISSUE THREAD

**Issue by Index-s** [glpi-project/glpi#16382]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

As far as someone paste an emoji into tickets, does are not been escaped and an mysql error is been thrown through the unsupported unicode. This should be escaped properly to be saved to database. Nor creation or update can be made when an emoji is been inserted.

### Steps To reproduce

1. New Ticket
2. Emoji copy & paste
3. Try to create the ticket

**Comment by cconard96** [comment]
The requested log and server information was not provided. Also, did you perform the optional migration to convert tables to utf8mmb4 character set (if you updated from a version before GLPI 10)?
