### ISSUE TITLE
[BUG][10.0.11] Observer not saved in ticket when added using Simplified interface

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#16392]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When a user creates a ticket with front/helpdesk.public.php?create_ticket=1, after filling all fields:
Type, Request, Category, Urgency, Medium, Watchers, Location, Title, Description
then saves with "Submit message", the watcher is not saved to the database and not shown in the new ticket.

The same procedure applied to 10.0.10 doesn't show this behavior, so I believe this bug was introduced with version 10.0.11

### Relevant log output

```shell
No relevant log output
```

### Page URL

front/helpdesk.public.php?create_ticket=1

### Steps To reproduce

1. Log in as a user with profile in simplified interface
2. Click in the menu "+ Create a ticket"
3. Fill in all fields, including the "Watchers" field
4. Click on the "Submit message" button
5. The notification pop-up appears at the bottom right with the new ticket number
6. Click on the ticket number
7. Notice that the watcher is missing

### Your GLPI setup information

Information about system installation and configuration
GLPI 10.0.11 ( => /opt/glpi/10.0.11)
Installation mode: TARBALL
Current language:en_GB

Server
 
Operating system: Linux GLPISERVER 4.18.0-477.27.1.el8_8.x86_64 #​1 SMP Thu Aug 31 10:29:22 EDT 2023 x86_64
PHP 7.4.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mbstring,
	memcached, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="150" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k mod_perl/2.0.12 Perl/v5.26.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.39-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.PHP version (7.4.33) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.39) is supported.Database engine version (10.3.39) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /opt/glpi/10.0.11/files/_cache has been validated. Write access to /opt/glpi/10.0.11/files/_cron has been validated. Write access to /opt/glpi/10.0.11/attachements has been validated. Write access to /opt/glpi/10.0.11/files/_dumps has been validated. Write access to /opt/glpi/10.0.11/files/_graphs has been validated. Write access to /opt/glpi/10.0.11/files/_lock has been validated. Write access to /opt/glpi/10.0.11/_pictures has been validated. Write access to /opt/glpi/10.0.11/files/_plugins has been validated. Write access to /opt/glpi/10.0.11/files/_rss has been validated. Write access to /opt/glpi/10.0.11/files/_sessions has been validated. Write access to /opt/glpi/10.0.11/files/_tmp has been validated. Write access to /opt/glpi/10.0.11/files/_uploads has been validated.Write access to /opt/glpi/10.0.11/files/_cache has been validated.
Write access to /opt/glpi/10.0.11/files/_cron has been validated.
Write access to /opt/glpi/10.0.11/attachements has been validated.
Write access to /opt/glpi/10.0.11/files/_dumps has been validated.
Write access to /opt/glpi/10.0.11/files/_graphs has been validated.
Write access to /opt/glpi/10.0.11/files/_lock has been validated.
Write access to /opt/glpi/10.0.11/_pictures has been validated.
Write access to /opt/glpi/10.0.11/files/_plugins has been validated.
Write access to /opt/glpi/10.0.11/files/_rss has been validated.
Write access to /opt/glpi/10.0.11/files/_sessions has been validated.
Write access to /opt/glpi/10.0.11/files/_tmp has been validated.
Write access to /opt/glpi/10.0.11/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /opt/glpi/10.0.11/marketplace has been validated.Write access to /opt/glpi/10.0.11/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

GLPI constants
 
GLPI_ROOT: "/opt/glpi/10.0.11"
GLPI_DOC_DIR: "/opt/glpi/10.0.11/attachements"
GLPI_PICTURE_DIR: "/opt/glpi/10.0.11/_pictures"
GLPI_CENTRAL_WARNINGS: "0"
GLPI_CONFIG_DIR: "/opt/glpi/10.0.11/config"
GLPI_VAR_DIR: "/opt/glpi/10.0.11/files"
GLPI_MARKETPLACE_DIR: "/opt/glpi/10.0.11/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_CACHE_DIR: "/opt/glpi/10.0.11/files/_cache"
GLPI_CRON_DIR: "/opt/glpi/10.0.11/files/_cron"
GLPI_DUMP_DIR: "/opt/glpi/10.0.11/files/_dumps"
GLPI_GRAPH_DIR: "/opt/glpi/10.0.11/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/opt/glpi/10.0.11/files/_locales"
GLPI_LOCK_DIR: "/opt/glpi/10.0.11/files/_lock"
GLPI_LOG_DIR: "/opt/glpi/10.0.11/files/_log"
GLPI_PLUGIN_DOC_DIR: "/opt/glpi/10.0.11/files/_plugins"
GLPI_RSS_DIR: "/opt/glpi/10.0.11/files/_rss"
GLPI_SESSION_DIR: "/opt/glpi/10.0.11/files/_sessions"
GLPI_TMP_DIR: "/opt/glpi/10.0.11/files/_tmp"
GLPI_UPLOAD_DIR: "/opt/glpi/10.0.11/files/_uploads"
GLPI_INVENTORY_DIR: "/opt/glpi/10.0.11/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/opt/glpi/10.0.11/locales"
GLPI_VERSION: "10.0.11"
GLPI_SCHEMA_VERSION: "10.0.11@6795e1eea6621428b5ef42350d555715bda8a96f"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

Libraries
 
htmlawed/htmlawed version 1.2.14 in (/opt/glpi/10.0.11/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/opt/glpi/10.0.11/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/opt/glpi/10.0.11/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/opt/glpi/10.0.11/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/glpi/10.0.11/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/glpi/10.0.11/vendor/true/punycode/src)
iamcal/lib_autolink in (/opt/glpi/10.0.11/vendor/iamcal/lib_autolink)
sabre/dav in (/opt/glpi/10.0.11/vendor/sabre/dav/lib/DAV)
sabre/http in (/opt/glpi/10.0.11/vendor/sabre/http/lib)
sabre/uri in (/opt/glpi/10.0.11/vendor/sabre/uri/lib)
sabre/vobject in (/opt/glpi/10.0.11/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/opt/glpi/10.0.11/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/opt/glpi/10.0.11/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/opt/glpi/10.0.11/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/opt/glpi/10.0.11/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/opt/glpi/10.0.11/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/opt/glpi/10.0.11/vendor/elvanto/litemoji/src)
symfony/console in (/opt/glpi/10.0.11/vendor/symfony/console)
scssphp/scssphp in (/opt/glpi/10.0.11/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/opt/glpi/10.0.11/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/opt/glpi/10.0.11/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/opt/glpi/10.0.11/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/opt/glpi/10.0.11/vendor/ramsey/uuid/src)
psr/log in (/opt/glpi/10.0.11/vendor/psr/log/Psr/Log)
psr/simple-cache in (/opt/glpi/10.0.11/vendor/psr/simple-cache/src)
psr/cache in (/opt/glpi/10.0.11/vendor/psr/cache/src)
league/csv in (/opt/glpi/10.0.11/vendor/league/csv/src)
mexitek/phpcolors in (/opt/glpi/10.0.11/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/opt/glpi/10.0.11/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/opt/glpi/10.0.11/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/opt/glpi/10.0.11/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/opt/glpi/10.0.11/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/opt/glpi/10.0.11/vendor/paragonie/sodium_compat/src)
symfony/cache in (/opt/glpi/10.0.11/vendor/symfony/cache)
html2text/html2text in (/opt/glpi/10.0.11/vendor/html2text/html2text/src)
symfony/css-selector in (/opt/glpi/10.0.11/vendor/symfony/css-selector)
symfony/dom-crawler in (/opt/glpi/10.0.11/vendor/symfony/dom-crawler)
twig/twig in (/opt/glpi/10.0.11/vendor/twig/twig/src)
twig/string-extra in (/opt/glpi/10.0.11/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/opt/glpi/10.0.11/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/opt/glpi/10.0.11/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/opt/glpi/10.0.11/vendor/symfony/polyfill-php82)
league/oauth2-client in (/opt/glpi/10.0.11/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/opt/glpi/10.0.11/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/opt/glpi/10.0.11/vendor/thenetworg/oauth2-azure/src/Provider)

LDAP directories
(not relevant)

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+TLS (anonymous@mailrelay.example.net)

Mails receivers
 
(not relevant)

Plugins list
 
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	resources            Name: Mitarbeiter                    Version: 3.0.4      State: Enabled                                 
		Install Method: Marketplace

**Comment by cedric-anne** [comment]
Hi @rickyweb,

Could you check if #16237 fixes this issue?

**Comment by rickyweb** [comment]
Hello @cedric-anne , thanks, that fixes the bug on my side.

**Comment by trasher** [comment]
It will be fixed in 10.0.12 then, thanks for the feedback
