### ISSUE TITLE
Error display log 

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#1639]
GLPI version 9.1 and 9.2

When building history in the getHistoryData method of the log.class.php file, there is no case for HISTORY_UPDATE_RELATION.

In the history view because of this case, the choice of the number of items to display no longer corresponds.

**Comment by tsmr** [comment]
2 solutions : 

1. Add Case into getHistoryData function

2. Or Modify initial query : 
```
$query = "SELECT *
<Tsmr>                 FROM `glpi_logs`
<Tsmr>                 WHERE `items_id` = '$items_id'
<Tsmr>                       AND `itemtype` = '$itemtype' AND `linked_action` != '".self::HISTORY_UPDATE_RELATION."'";
```

**Comment by trasher** [comment]
Since `HISTORY_UPDATE_RELATION` seems to be the only one missing in the cases, I guess it can be added.

**Comment by amma35** [comment]
I suggest this: 

```
case self::HISTORY_UPDATE_RELATION :
$tmp['field'] = NOT_AVAILABLE;
if ($linktype_field = explode('#', $data["itemtype_link"])) {
 $linktype      = $linktype_field[0];
 $tmp['field']  = $linktype::getTypeName();
}
$tmp['change'] = sprintf(__('%1$s: %2$s'), __('Update a link with an item'),
					   sprintf(__('%1$s (%2$s)'), $data["old_value"],
							   $data["new_value"]));
break;
```

**Comment by trasher** [comment]
Sounds good to me. @amma35 could you please open a PR?
