### ISSUE TITLE
After upgrading GLPI to 10.0.11, the Automatic Actions named "queuednotification" and "mailgate" no longer work automatically but manually they do.

### ISSUE THREAD

**Issue by REMY31470** [glpi-project/glpi#16393]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.11

### Bug description

After upgrading GLPI to 10.0.11, the Automatic Actions named "queuednotification" and "mailgate" no longer work automatically but manually they do.

If you enter the task, clear the date of the last run (1), change the status to Disabled (2) then Save (3) and then return to the task and change the status back to Scheduled (3) then Save again (4) ==> The task runs once and plans to run again at a future date (here every minute) but 1 minute later still nothing and the Next run date is not changed.

![image](https://github.com/glpi-project/glpi/assets/77795328/00e11428-ab47-4b1d-8c28-9df8d970b696)

Are there any logs to look at in order to understand the exact error or can someone help me run some commands to make these 2 tasks run again automatically?

Thanks in advance for your help. 

### Your GLPI setup information

Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-91-generic x86_64)
Apache/2.4.52 (Ubuntu)

**Comment by cconard96** [comment]
Please review the GLPI documentation for automatic actions.
https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/crontasks.html

Currently, you have at least the queuednotification action set for GLPI mode which relies on user traffic on your GLPI site to trigger running actions. If you want actions to run consistently, you need to set them for CLI mode and configure a cron job to trigger them. If you need more help, feel free to make a post on the community forum.

If you have a related error in your GLPI logs (files/_log folder), you may add the information here and re-open the bug report.
