### ISSUE TITLE
In the Dashboard, customise OK on Firefox and HS on Chrome and Edge.

### ISSUE THREAD

**Issue by REMY31470** [glpi-project/glpi#16394]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.11

### Bug description

The Dashboard can be customised to show only tickets filtered on certain characteristics.

It is possible to see the fit on Firefox but impossible on Chrome and Edge.

![image](https://github.com/glpi-project/glpi/assets/77795328/f66eefe0-90a6-444a-a918-ba16173b8093)

Have you ever had this problem? 

Thank you in advance for your feedback,
Rémy

### Your GLPI setup information

Ubuntu 22.04.2 LTS (GNU/Linux 5.15.0-91-generic x86_64)
Apache/2.4.52 (Ubuntu)

**Comment by cconard96** [comment]
Please check for and provide any relevant messages from your GLPI logs as requested by the bug report template. Specifically, you'll probably find info in files/_log/php-errors.log or files/_log/sql-errors.log.

You should also check the browser's console (F12 key > Console tab) for warnings/errors when the dashboard is loading.
