### ISSUE TITLE
[0.90] Changing default entity in preferences forms asks password confirmation

### ISSUE THREAD

**Issue by xsgoodbox** [glpi-project/glpi#164]
Hello gents, 

I think that can be an enhancement:
when changing the default entity in front/preference.php it asks for the password confirmation.
Is it possible to avoid this behavior ?

Thanks in advance.

**Comment by orthagh** [comment]
Again ( :) ), i do not have this behavior in my side.

It could be chrome/chromium who autofill the password field and not its confirmation.
So on page submit, error triggers.

Check if your password field in this page is filled and yellow backgrounded

**Comment by remicollet** [comment]
Missing the autocomplete='off' attribute ?

**Comment by orthagh** [comment]
Ggood point

**Comment by orthagh** [comment]
But chrome/chromium ignores this feature (autocomplete=off), see https://code.google.com/p/chromium/issues/detail?id=468153#c29

**Comment by xsgoodbox** [comment]
All right for the autocomplete setting in chromium! 
Actually firefox fills one of the two password fields and chromium zero of them.

- "Mozilla Iceweasel 38.3.0"
- "Chromium 37.0.2062.120 Built on Debian 7.6, running on Debian 7.9"

**Comment by orthagh** [comment]
a test for the full form, but i think we can't do a better fix.
Support by browsers are currently not very good.

See : http://caniuse.com/#feat=input-autocomplete-onoff

**Comment by xsgoodbox** [comment]
Huhu, on chrome it's OK !
However on firefox, it fill the password even if the attributes contains autocomplete=off.
