### ISSUE TITLE
"Peer certificate dit not match expected CN" when using Azure Managed Database

### ISSUE THREAD

**Issue by breys-s** [glpi-project/glpi#16410]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

I enabled SSL on my Azure MySQL database but when I download the database certificate (which is not customizable) and put it on my server, I get an error that says: "Peer certificate CN=cr5.northeurope1-a.control.database.windows.net' did not match expected CN=XX.XX.XX.XX' in /var/www/html/glpi/src/DBmysql.php".

For information, GLPI runs on Ubuntu 22.04 and the database is managed by Azure Cloud, so I don't control the certificate used by the database.

I've tried pointing to the base's domain name instead of its IP but I get the same problem.

The base uses a private endpoint for information

As a workaround, I put MYSQLI_CLIENT_SSL_DONT_VERIFY_SERVER_CERT in real_connect function and it worked but I think this is not a good solution

### Relevant log output

```shell
"Peer certificate CN=`cr5.northeurope1-a.control.database.windows.net' did not match expected CN=`XX.XX.XX.XX' in /var/www/html/glpi/src/DBmysql.php"
```

**Comment by cconard96** [comment]
Please provide details regarding how you configured the SSL connection.
Did you change your database connection config as stated in the GLPI installation documentation?
https://glpi-install.readthedocs.io/en/latest/install/advanced-configuration.html#ssl-connection-to-database

**Comment by breys-s** [comment]
Hi,
Here is my dbconfig file : 

class DB extends DBmysql {
   public $dbhost = 'xx.xx.xx.xx';
   public $dbuser = 'glpi@xx';
   public $dbpassword = 'xxxx';
   public $dbdefault = 'glpi';
   public $use_timezones = true;
   public $use_utf8mb4 = true;
   public $allow_myisam = false;
   public $allow_datetime = false;
   public $allow_signed_keys = false;
   public $dbssl = true;
   public $dbsslca = '/var/www/html/glpi/config/DigiCertGlobalRootG2.crt.pem';
}
