### ISSUE TITLE
Bug Ticket creation with mail collector

### ISSUE THREAD

**Issue by Fivcolas** [glpi-project/glpi#16418]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.11

### Bug description

We have a problem creating and tracking tickets via emails since the upgrade to version 10.0.11 of GLPI.
Some tickets made by email are not created or visible in the GLPI DB and we receive two emails concerning this ticket, one with the wrong ID but the correct body of text. No problem when the ticket is made via the web interface however.
Here is an exemple of  a ticket created by mail : 
![image](https://github.com/glpi-project/glpi/assets/157382531/2e83e967-f7a3-44cd-895f-da640e131d86)
![image](https://github.com/glpi-project/glpi/assets/157382531/9f07177f-d992-461f-976b-d98572ac99f4)

There appears to be a mismatch on the ticket IDs

### Relevant log output

```shell
[2024-01-24 10:34:31] glpiphplog.WARNING:   *** PHP User Warning (512): No-Reply address is not defined in configuration. in C:\httpd\support\src\Config.php at line 3854
  Backtrace :
  src\Config.php:3854                                trigger_error()
  src\NotificationTarget.php:1213                    Config::getEmailSender()
  src\NotificationTemplate.php:623                   NotificationTarget->getSender()
  src\NotificationEventAbstract.php:135              NotificationTemplate->getDataToSend()
  src\NotificationEvent.php:188                      NotificationEventAbstract::raise()
  src\Ticket.php:1754                                NotificationEvent::raiseEvent()
  src\CommonDBTM.php:1747                            Ticket->post_updateItem()
  src\ITILSolution.php:329                           CommonDBTM->update()
  src\CommonDBTM.php:1343                            ITILSolution->post_addItem()
  front\itilsolution.form.php:63                     CommonDBTM->add()
```

### Steps To reproduce

- Upgrade GLPI 10.0.6 to 10.0.11
- Create a ticket by mail with collector

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.11 ( => C:\httpd\support)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Windows NT SUPPORT 10.0 build 14393 (Windows Server 2016) AMD64
PHP 8.1.24 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="1200" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" disable_functions="" 
Software: Apache/2.4.41 (Win64) mod_authnz_sspi/0.1.1 OpenSSL/1.1.1e PHP/8.1.24 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.30
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: GLPIAdmin@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.24) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.30) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\httpd\support/files/_cache has been validated.
Write access to C:\httpd\support/files/_cron has been validated.
Write access to C:\httpd\support/files has been validated.
Write access to C:\httpd\support/files/_dumps has been validated.
Write access to C:\httpd\support/files/_graphs has been validated.
Write access to C:\httpd\support/files/_lock has been validated.
Write access to C:\httpd\support/files/_pictures has been validated.
Write access to C:\httpd\support/files/_plugins has been validated.
Write access to C:\httpd\support/files/_rss has been validated.
Write access to C:\httpd\support/files/_sessions has been validated.
Write access to C:\httpd\support/files/_tmp has been validated.
Write access to C:\httpd\support/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "C:\httpd\support":
‣ "C:\httpd\support/files" ("GLPI_VAR_DIR")
‣ "C:\httpd\support/files/_cache" ("GLPI_CACHE_DIR")
‣ "C:\httpd\support/files/_cron" ("GLPI_CRON_DIR")
‣ "C:\httpd\support/files" ("GLPI_DOC_DIR")
‣ "C:\httpd\support/files/_dumps" ("GLPI_DUMP_DIR")
‣ "C:\httpd\support/files/_graphs" ("GLPI_GRAPH_DIR")
‣ "C:\httpd\support/files/_lock" ("GLPI_LOCK_DIR")
‣ "C:\httpd\support/files/_log" ("GLPI_LOG_DIR")
‣ "C:\httpd\support/files/_pictures" ("GLPI_PICTURE_DIR")
‣ "C:\httpd\support/files/_plugins" ("GLPI_PLUGIN_DOC_DIR")
‣ "C:\httpd\support/files/_rss" ("GLPI_RSS_DIR")
‣ "C:\httpd\support/files/_sessions" ("GLPI_SESSION_DIR")
‣ "C:\httpd\support/files/_tmp" ("GLPI_TMP_DIR")
‣ "C:\httpd\support/files/_uploads" ("GLPI_UPLOAD_DIR")
You can ignore this suggestion if your web server root directory is "C:\httpd\support\public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\httpd\support/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\httpd\\support"
GLPI_CONFIG_DIR: "C:\\httpd\\support/config"
GLPI_VAR_DIR: "C:\\httpd\\support/files"
GLPI_MARKETPLACE_DIR: "C:\\httpd\\support/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "C:\\httpd\\support/files"
GLPI_CACHE_DIR: "C:\\httpd\\support/files/_cache"
GLPI_CRON_DIR: "C:\\httpd\\support/files/_cron"
GLPI_DUMP_DIR: "C:\\httpd\\support/files/_dumps"
GLPI_GRAPH_DIR: "C:\\httpd\\support/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\httpd\\support/files/_locales"
GLPI_LOCK_DIR: "C:\\httpd\\support/files/_lock"
GLPI_LOG_DIR: "C:\\httpd\\support/files/_log"
GLPI_PICTURE_DIR: "C:\\httpd\\support/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\httpd\\support/files/_plugins"
GLPI_RSS_DIR: "C:\\httpd\\support/files/_rss"
GLPI_SESSION_DIR: "C:\\httpd\\support/files/_sessions"
GLPI_TMP_DIR: "C:\\httpd\\support/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\httpd\\support/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\httpd\\support/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "C:\\httpd\\support/locales"
GLPI_VERSION: "10.0.11"
GLPI_SCHEMA_VERSION: "10.0.11@6795e1eea6621428b5ef42350d555715bda8a96f"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (C:\httpd\support\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.8.0 in (C:\httpd\support\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\httpd\support\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (C:\httpd\support\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\httpd\support\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\httpd\support\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\httpd\support\vendor\iamcal\lib_autolink)
sabre/dav in (C:\httpd\support\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\httpd\support\vendor\sabre\http\lib)
sabre/uri in (C:\httpd\support\vendor\sabre\uri\lib)
sabre/vobject in (C:\httpd\support\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\httpd\support\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\httpd\support\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\httpd\support\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\httpd\support\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\httpd\support\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\httpd\support\vendor\elvanto\litemoji\src)
symfony/console in (C:\httpd\support\vendor\symfony\console)
scssphp/scssphp in (C:\httpd\support\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\httpd\support\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\httpd\support\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\httpd\support\vendor\rlanvin\php-rrule\src)
ramsey/uuid in (C:\httpd\support\vendor\ramsey\uuid\src)
psr/log in (C:\httpd\support\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\httpd\support\vendor\psr\simple-cache\src)
psr/cache in (C:\httpd\support\vendor\psr\cache\src)
league/csv in (C:\httpd\support\vendor\league\csv\src)
mexitek/phpcolors in (C:\httpd\support\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\httpd\support\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\httpd\support\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\httpd\support\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\httpd\support\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\httpd\support\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\httpd\support\vendor\symfony\cache)
html2text/html2text in (C:\httpd\support\vendor\html2text\html2text\src)
symfony/css-selector in (C:\httpd\support\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\httpd\support\vendor\symfony\dom-crawler)
twig/twig in (C:\httpd\support\vendor\twig\twig\src)
twig/string-extra in (C:\httpd\support\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (C:\httpd\support\vendor\symfony\polyfill-php82)
league/oauth2-client in (C:\httpd\support\vendor\league\oauth2-client\src\Provider)
league/oauth2-google in (C:\httpd\support\vendor\league\oauth2-google\src\Provider)
thenetworg/oauth2-azure in (C:\httpd\support\vendor\thenetworg\oauth2-azure\src\Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'XXXX.XXXX', Port: '389', BaseDN: 'OU=Utilisateurs,DC=XXXX,DC=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'XXXX@XXXX', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (XXXX@XXXX@smtp.office365.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	servicecatalog       Name: Catalogue de service           Version: 2.0.9      State: Enabled                                 
		Install Method: Manual
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                
		 Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.4      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	satisfaction         Name: Plus de satisfaction           Version: 1.6.2      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by ftoledo** [comment]
first, you must add the no-reply address to solve these warning at you mail notification settings page, like "no-reply@you_domain.com.ar"
