### ISSUE TITLE
Candados GLPI 10

### ISSUE THREAD

**Issue by Luisahvargas** [glpi-project/glpi#16424]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.9 

### Bug description

Buenas tardes,
Tengo una duda y es que el inventario del GLPI me está bloqueando los campos con un candado para que el inventario no me realice cambios, pero requiero que el campo de Nombre de usuario alternativo, el inventario lo esté cambiando constantemente, cada vez que alguien inicie sesión en ese equipo, pero no permite, ya que posee el candado y no he podido encontrar la opción donde quitarlo, ya que me fije en campos bloqueados, pero me salen solo los equipos que tengo, ¿es posible desbloquear esa casilla para todos los equipos? 
![Screenshot_1](https://github.com/glpi-project/glpi/assets/99419147/7ac61680-9672-4b3e-b338-f67288139801)

### Steps To reproduce

Abra la página front/lockedfield.form.php

### Your GLPI setup information

Abra la página con la computadora, por ejemplo: front/computer.form.php?id=1
Aquí está el campo "Número de inventario".
Si desea bloquearlo, debe seleccionar en la página front/lockedfield.form.php No permite

**Comment by trasher** [comment]
It is requested to write only in english, and to use latest stable release.
