### ISSUE TITLE
The follow-up template does not generate the follow-up notification in the email

### ISSUE THREAD

**Issue by lucaslevi-consultor-glpi** [glpi-project/glpi#16427]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

I've noticed some strange behavior in the notification templates. I created a notification template to be used when the technician makes the first interaction on the call.

What's happening: if the user uses the template manually by clicking on the reply tab of the ticket, the email notification is generated normally in the notification queue (new follow-up trigger) but if I try to use the same follow-up template via rule, it adds the follow-up to the ticket but doesn't generate the email notification.

The idea would be for the requester to receive an automatic follow-up notification in the email about who is going to start the service.

I've created a very simple rule so that it associates the template with the call when the technician exists (i.e. when the technician is assigned). I tested it on 2 different GLPIs in version 0.11 but to no avail

The environment has a new follow-up trigger for the requester and it works normally. 

This bug is very strange, it's as if the GLPI doesn't understand that the follow-up is a follow-up when it is added to the ticket via a rule. Which ends up not generating the email to the user (even with the template and trigger and cron activated).

### Steps To reproduce

Create a follow-up template, make a business rule to associate the template with the call in some kind of update and see if it will generate the email notification

Of course, this trigger needs to be enabled in Configure > Notifications > Notifications.

**Comment by cedric-anne** [comment]
Hi,

It will be changed in GLPI 10.1, see #14795.
