### ISSUE TITLE
ERROR: 400 Bad Request, JSON does not validate. Violations: "NVME" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)

### ISSUE THREAD

**Issue by AlekseyBerez** [glpi-project/glpi#16421]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

This problem is the same as https://github.com/glpi-project/glpi-agent/issues/207
GLPI Agent (1.6.1, 1.7.1, now is 1.8 nightly build) don't create agent in GLPI Inventory (1.3.4)
Fragment from the JSON:
      "storages": [
         {
            "description": "PCI Slot 8 : Bus 3 : Device 0 : Function 0 : Adapter 1",
            "disksize": 512110,
            "firmware": "L183",
            "interface": "NVME",
            "model": "SSSTC CL1-8D512-HP",
            "name": "PhysicalDisk0",
            "serial": "38F6_0156_3050_DEA7.",
            "type": "SSD"
         }

The output of 'glpi-inventory --partial storage --debug --debug':
{
   "action": "inventory",
   "content": {
      "bios": {
         "bdate": "2023-10-06",
         "bmanufacturer": "HP",
         "bversion": "T70 Ver. 01.15.00",
         "mmanufacturer": "HP",
         "mmodel": "87E0",
         "msn": "PKWJF028JEJ2AI",
         "skunumber": "150C5EA#ACB",
         "smanufacturer": "HP",
         "smodel": "HP ProBook 440 G8 Notebook PC",
         "ssn": "5CD103JGCR"
      },
      "hardware": {
         "chassis_type": "Notebook",
         "memory": 16064,
         "name": "VT-LT-0026",
         "uuid": "AC033014-0141-4214-AE47-62923261AF23",
         "vmsystem": "Physical",
         "winlang": "1049",
         "winowner": "vtsa",
         "winprodid": "00330-53398-16354-AAOEM",
         "winprodkey": "J63P4-N3KDT-M3CV9-C3GTG-C9XTP",
         "workgroup": "**********"
      },
      "storages": [
         {
            "description": "PCI Slot 8 : Bus 3 : Device 0 : Function 0 : Adapter 1",
            "disksize": 512110,
            "firmware": "L183",
            "interface": "NVME",
            "model": "SSSTC CL1-8D512-HP",
            "name": "PhysicalDisk0",
            "serial": "38F6_0156_3050_DEA7.",
            "type": "SSD"
         }
      ],
      "versionclient": "GLPI-Inventory_v1.8-git82e3ca7d"
   },
   "deviceid": "VT-LT-0026.************-2024-01-24-17-24-23",
   "itemtype": "Computer",
   "partial": true
}

### Relevant log output

```shell
C:\Program Files\GLPI-Agent>glpi-injector.bat -u https://*******/plugins/glpiinventory/ --file "VT-LT-0026-2024-01-24-16ERROR: 400 Bad Request, JSON does not validate. Violations:                                                                            "NVME" does not match to ^(SCSI|HDC|IDE|USB|1394|SATA|SAS|ATAPI)$ at #->properties:content->properties:storages->items[0]:0->properties:interface                                                                                                                             These elements were not sent:                                                                                                          VT-LT-0026-2024-01-24-16-01-22.json
```

**Comment by trasher** [comment]
You probably made a mistake upgrading, you have (at least) the inventory_format library that is really outdated, this has been fixed 2 years ago.

Check your vendor directory is up-to-date.
