### ISSUE TITLE
Item (asset) not assigned to change when creating the change from the assets changes tab

### ISSUE THREAD

**Issue by fajo-de** [glpi-project/glpi#16438]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When creating a change from an items (assets) Changes tab the change will not become linked to that item/asset if the category of the change is changed. When leaving the category alone the link is established. 

### Page URL

/front/change.form.php

### Steps To reproduce

1. open an asset (computer or networking for example)
2. navigate to the "Changes" tab
3. click "New change for this item"
4. select a "Category" from the dropdown (causes a page reload)
5. fill all mandatory fields (if any)
6. click "+Add" to create the change
7. The change will be created but the item is not linked

When not changing the Category the item is linked successfully.

**Comment by cedric-anne** [comment]
Hi,

This is the same issue as #15358.
