### ISSUE TITLE
Blank screen when creating a new change

### ISSUE THREAD

**Issue by tmayans** [glpi-project/glpi#16466]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

A blank screen is shown when creating a new "Change".

### Relevant log output

```shell
With mode debug enabled, the error is 
"Uncaught Exception TypeError: Unsupported operand types: string + string in /var/www/html/glpi/src/CommonITILObject.php at line 2935"
```

### Page URL

https://<servepath>/front/change.form.php

### Steps To reproduce

1. Go to Support -> Changes
2. Open new change from "+ add" button
3. The screen not show the form

**Comment by trasher** [comment]
Try if you reproduce with latest stable. If so, please provide full error stack trace. You may try to disable plugins also.

**Comment by ppenin** [comment]
Hello,
same problem when creating an new ticket in GLPI 10.0.12.
Here the error displayed in debug mode
Uncaught Exception TypeError: Unsupported operand types: int + string in /var/www/html/glpi/src/LevelAgreement.php at line 855
no difference between 10.0.11 and 10.12 version for LevelAgreement.php
It tries to add int and string in line 855 ($endtime   = $starttime + $delay + $additional_delay;=
No issue when creating a new change

**Comment by cedric-anne** [comment]
@tmayans @ppenin  What is your PHP version?

**Comment by tmayans** [comment]
@cedric-anne my php version is PHP 8.1.2

**Comment by cedric-anne** [comment]
Can you provide the full error trace?

**Comment by ppenin** [comment]
php is 8.1.2
a ticket can be created if service levels are filled up with a date > today
![image](https://github.com/glpi-project/glpi/assets/22499638/c1222b96-bb94-4768-82ed-8bf324cda730)

**Comment by ppenin** [comment]
here the differences between 10.0.11 and 10.0.12 in Ticket.php
![image](https://github.com/glpi-project/glpi/assets/22499638/7c69b6a7-89d4-42a6-b133-f2b9feada7f8)

**Comment by cedric-anne** [comment]
Could you test #16496 ?

**Comment by ppenin** [comment]
It worked for me. Many Thanks

**Comment by tmayans** [comment]
It worked for me too. Thanks

*---Toni Mayans.*

**Comment by Gor3pig** [comment]
The fix didn't work for us. The error is gone, but the ticket is not created.

**Comment by cedric-anne** [comment]
@Gor3pig 

The patch proposal has been updated, could you check again #16496?
