### ISSUE TITLE
The ITIL category is being replicated in the destination entity when transferring tickets between entities.

### ISSUE THREAD

**Issue by thallestorchi** [glpi-project/glpi#16464]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.9

### Bug description

When escalating a ticket with the ITIL category set to another entity, GLPI creates the current ITIL category of the ticket in the other entity to which the ticket is transferred. This behavior is undesirable, and it would be preferable to have the option to set the category as null when transferring the ticket between entities.

### Steps To reproduce

1. CreateOpen the GLPI system and navigate to the tickets section.
2. Select a ticket that has the ITIL category configured.
3. Proceed a escalation process for the ticket to another entity.
Note that, during the escalation, GLPI creates the ITIL category in the destination entity, replicating the current category of the ticket. a ticket 

### Your GLPI setup information

Operating system: Linux glpi-5bb67545dc-wfkwv 4.18.0-305.82.1.el8_4.x86_64 #1 SMP Thu Feb 23 09:21:04 EST 2023 x86_64
PHP 8.0.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, redis, session, shmop, soap, sockets,
	sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="1024M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="6M" 
Software: Apache/2.4.37 (Red Hat Enterprise Linux) OpenSSL/1.1.1k ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.35-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@glpi-mysql/glpi
	Host info: glpi-mysql via TCP/IP
	
PHP version (8.0.20) is supported.PHP version (8.0.20) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.35) is supported.Database engine version (10.3.35) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to /glpi/files/_cache has been validated. Write access to /glpi/config has been validated. Write access to /glpi/files/_cron has been validated. Write access to /glpi/files has been validated. Write access to /glpi/files/_dumps has been validated. Write access to /glpi/files/_graphs has been validated. Write access to /glpi/files/_lock has been validated. Write access to /glpi/files/_pictures has been validated. Write access to /glpi/files/_plugins has been validated. Write access to /glpi/files/_rss has been validated. Write access to /glpi/files/_sessions has been validated. Write access to /glpi/files/_tmp has been validated. Write access to /glpi/files/_uploads has been validated.Write access to /glpi/files/_cache has been validated.
Write access to /glpi/config has been validated.
Write access to /glpi/files/_cron has been validated.
Write access to /glpi/files has been validated.
Write access to /glpi/files/_dumps has been validated.
Write access to /glpi/files/_graphs has been validated.
Write access to /glpi/files/_lock has been validated.
Write access to /glpi/files/_pictures has been validated.
Write access to /glpi/files/_plugins has been validated.
Write access to /glpi/files/_rss has been validated.
Write access to /glpi/files/_sessions has been validated.
Write access to /glpi/files/_tmp has been validated.
Write access to /glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.Web server root directory configuration seems safe.
Sessions configuration is secured.Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.OS and PHP are relying on 64 bits integers.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /glpi/marketplace has been validated.Write access to /glpi/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by trasher** [comment]
Please test with latest stable.
