### ISSUE TITLE
Guest FAQ Visibility 

### ISSUE THREAD

**Issue by coopernicholas** [glpi-project/glpi#16474]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.11 

### Bug description

I made it so the FAQ can be viewed by guests. Guests can see the topics but when you go into the topics the page is blank. When I login with a self-service user the FAQ information shows up.

**Comment by KeetKhat** [comment]
The target needs to be set as recursive

**Comment by coopernicholas** [comment]
Thank you!
