### ISSUE TITLE
Error in OLA or SLA rule when adding a ticket

### ISSUE THREAD

**Issue by verdanatech-marcio** [glpi-project/glpi#16498]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

When creating a ticket that runs any SLA or OLA rule. The sla_waiting_duration and ola_waiting_duration fields are passed empty and an error occurs when adding the database. Not allowing the ticket to be opened

### Relevant log output

```shell
*** MySQL query error:
  SQL: INSERT INTO `glpi_tickets` (`name`, `content`, `entities_id`, `date`, `type`, `itilcategories_id`, `status`, `requesttypes_id`, `urgency`, `impact`, `priority`, `locations_id`, `actiontime`, `slas_id_tto`, `slas_id_ttr`, `olas_id_tto`, `olas_id_ttr`, `users_id_lastupdater`, `users_id_recipient`, `global_validation`, `slalevels_id_ttr`, `sla_waiting_duration`, `time_to_resolve`, `date_creation`, `date_mod`) VALUES ('Teste A', '&#60;p&#62;Teste A&#60;/p&#62;', '0', '2024-02-01 16:06:34', '1', '0', '1', '1', '3', '3', '3', '0', '0', '0', '1', '0', '0', '2', '2', '1', '0', '', '2024-02-02 08:06:34', '2024-02-01 16:06:34', '2024-02-01 16:06:34')
  Error: Incorrect integer value: '' for column `verdanadesk_local`.`glpi_tickets`.`sla_waiting_duration` at row 1
```

### Page URL

http://localhost/glpi/front/ticket.form.php

### Steps To reproduce

1. Access ticket.form.php
2. Fill in all ticket details
3. Have a rule that adds an SLA to the ticket

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.12 ( => /var/www/html/glpi-10.0.12)
Installation mode: TARBALL
Current language:pt_BR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux PEVTCMTNB3015 6.1.0-13-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64
PHP 8.2.17 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M"
	disable_functions="pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,"
	
Software: Apache/2.4.57 (Debian) (Apache/2.4.57 (Debian) Server at glpi.local Port 80
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Server Software: Debian 12
	Server Version: 10.11.4-MariaDB-1~deb12u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: admin@127.0.0.1/verdanadesk_local
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.2.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.4) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi-10.0.12/files/_cache has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_cron has been validated.
Write access to /var/www/html/glpi-10.0.12/files has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_dumps has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_graphs has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_lock has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_pictures has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_plugins has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_rss has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_sessions has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_tmp has been validated.
Write access to /var/www/html/glpi-10.0.12/files/_uploads has been validated.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi-10.0.12/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi-10.0.12"
GLPI_CONFIG_DIR: "/var/www/html/glpi-10.0.12/config"
GLPI_VAR_DIR: "/var/www/html/glpi-10.0.12/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi-10.0.12/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/html/glpi-10.0.12/files"
GLPI_CACHE_DIR: "/var/www/html/glpi-10.0.12/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi-10.0.12/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi-10.0.12/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi-10.0.12/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi-10.0.12/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi-10.0.12/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi-10.0.12/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi-10.0.12/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi-10.0.12/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi-10.0.12/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi-10.0.12/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi-10.0.12/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi-10.0.12/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi-10.0.12/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi-10.0.12/locales"
GLPI_VERSION: "10.0.12"
GLPI_SCHEMA_VERSION: "10.0.12@b902ef5f5da967c1a9d0826ee8a7dce07d57cf3d"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 

PHP User deprecated function (16384): phpCAS autoloader is deprecated. Install phpCAS using composer instead. in /usr/share/php/CAS/source/CAS/Autoload.php at line 86
PHP User deprecated function (16384): Including CAS.php is deprecated. Install phpCAS using composer instead. in /usr/share/php/CAS/CAS.php at line 32
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi-10.0.12/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi-10.0.12/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi-10.0.12/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi-10.0.12/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi-10.0.12/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi-10.0.12/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi-10.0.12/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi-10.0.12/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi-10.0.12/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi-10.0.12/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi-10.0.12/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi-10.0.12/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi-10.0.12/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi-10.0.12/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi-10.0.12/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi-10.0.12/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi-10.0.12/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi-10.0.12/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi-10.0.12/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi-10.0.12/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi-10.0.12/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi-10.0.12/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi-10.0.12/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi-10.0.12/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi-10.0.12/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi-10.0.12/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi-10.0.12/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi-10.0.12/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi-10.0.12/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi-10.0.12/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi-10.0.12/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi-10.0.12/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi-10.0.12/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi-10.0.12/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi-10.0.12/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi-10.0.12/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi-10.0.12/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi-10.0.12/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi-10.0.12/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi-10.0.12/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi-10.0.12/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi-10.0.12/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi-10.0.12/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi-10.0.12/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi-10.0.12/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.6.0 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (testeglpivdk@gmail.com@smtp.gmail.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Manual
	skins                Name: Skins                          Version: 3.4.0      State: Enabled                                 
		Install Method: Manual
	chat                 Name: Verdana Chat                   Version: 12.2.1     State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cosmedd** [comment]
We have the same problem with GLPI 10.0.12

**Comment by GrupoIntegracao-LuisNobre** [comment]
We has meeting the same issue after upgrade to 10.0.12

When a associete try to create a new ticket and click in create, that page renew but don't create any ticket

**Comment by raultak** [comment]
Same problem here and the MySQL log shows the same error described.
The value for field `glpi_tickets`.`sla_waiting_duration` is empty ''.
Problem stared after upgrade from 10.0.11 to 10.0.12.

**Comment by cedric-anne** [comment]
Hi @verdanatech-marcio @cosmedd @GrupoIntegracao-LuisNobre @raultak ,

Could you check the fix proposed in #16496?

**Comment by ftoledo** [comment]
I can confirm this bug and the #16496 fix that works.

**Comment by troublestarter** [comment]
And how to apply the fix ?
