### ISSUE TITLE
SLA not reflected as mandatory in the UI

### ISSUE THREAD

**Issue by joacoetche06** [glpi-project/glpi#16495]
When i create a ticket, glpi don't add SLA with an red asterix as mandatory. It is mandatory in the template but it is not reflected in the UI
![image](https://github.com/glpi-project/glpi/assets/88555611/276b8102-c9d3-468d-b674-b4ed592e2905)
![image](https://github.com/glpi-project/glpi/assets/88555611/3939dd40-bb13-46c7-a6c3-c286afae77aa)

_Originally posted by @joacoetche06 in https://github.com/glpi-project/glpi/issues/11286#issuecomment-1919282132_

**Comment by ftoledo** [comment]
I can confirm this UI bug
