### ISSUE TITLE
[0.90] Fonts loading in chromium 

### ISSUE THREAD

**Issue by xsgoodbox** [glpi-project/glpi#165]
Hello, it's me again, sorry for these frequent reports, purely cosmetic…

With Chromium "Version 37.0.2062.120 Built on Debian 7.6, running on Debian 7.9 (281580) (64-bit)"
Interface fonts are not loaded, but they does in 0.8x. So chromium seems to switch on defaults fonts.

Unfortunately, I didn't have the time to look at the code actually.

PS: as a feedback, the I found the new interface really relaxing and enjoyable to use. Thanks a lot. Wish you a nice day!

**Comment by orthagh** [comment]
Hi.
Thanks for your reports.
Can you provide some screenshots ?

I switched some fonts to match firefox and chrome rendering.
In my side : chrome 45, ubuntu 15.04, no issue with fonts

**Comment by xsgoodbox** [comment]
Yes, 
![chromium-fonts-with-glpi](https://cloud.githubusercontent.com/assets/1431656/10451184/ef02f788-719e-11e5-80db-24c0919d29ba.png)

There is a vanilla, without modules chromium on my work computer.

**Comment by orthagh** [comment]
what's version of your browsers (left and right) ?

**Comment by xsgoodbox** [comment]
Sorry,
so I'm using same old versions there:

    "Mozilla Iceweasel 38.3.0"
    "Chromium 37.0.2062.120 Built on Debian 7.6, running on Debian 7.9"

**Comment by orthagh** [comment]
can't find which font used in your chrome.
Could you inspect body tag in chrome developper tools (F12) to check used font-family property

**Comment by xsgoodbox** [comment]
Yes,
`font-family: 'Bitstream Vera Sans', Verdana, Tahoma, 'Sans serif';
font-size: 12px;`

**Comment by orthagh** [comment]
oh check this issue relative to chrome 37  : https://code.google.com/p/chromium/issues/detail?id=395528
It's already fixed in newer versions.

If you can't upgrade your chromium version, it seems this workaround could work : http://superuser.com/a/814025

**Comment by xsgoodbox** [comment]
All right !
Many thanks.
Closed.
