### ISSUE TITLE
Ticket hangs when loading

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#16529]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

A technician added photos with a description to a ticket. After that, the entire ticket could no longer be loaded. When opening the ticket, only an endless loading screen appeared.

<img width="668" alt="image" src="https://github.com/glpi-project/glpi/assets/115316656/b612fb6a-039d-4a79-8c20-6e5b97af36ce">

The ticket could only be exited again after a very long wait. Closing the browser did not help either. After we restarted the server, we were then able to access the content of the ticket with a waiting time of 10 minutes. The comment field where the photos and the technician's comments should be was empty and could only be deleted after a very long wait. After deleting it, everything worked normally again.

### Steps To reproduce

Unfortunately, I cannot reproduce the problem

**Comment by efriastech** [comment]
Hello, this issue might be related to the one I mentioned, so it would be worth following the development of this entry as well: https://github.com/glpi-project/glpi/issues/16444

Thank you.

**Comment by FreeMacs** [comment]
I can reproduce the problem.

When I drag and drop an image into this field, there are several behaviors in GLPI.

![image](https://github.com/glpi-project/glpi/assets/115316656/5631f1dc-cdc8-4c0b-b289-d1498756184f)


Images up to approx. 500KB are displayed without any problems.

For images between 600KB and 4MB I only get an empty field.
![image](https://github.com/glpi-project/glpi/assets/115316656/7b0c82c4-e547-4925-ae75-000bf99e28a0)


and with images that are over 4-5MB in size, the ticket can no longer be opened and it just loads endlessly.
![image](https://github.com/glpi-project/glpi/assets/115316656/632e649f-956e-4b19-8920-fdef6dac943d)


If I drag files and photos into the drag and drop field, it works without any problems.
![image](https://github.com/glpi-project/glpi/assets/115316656/6fc9fb2b-30e1-43c6-8058-7f51a764811b)


The image is always displayed when I drag it in and it also says Upload Succesful, but after saving it, the specified problems occur.
![image](https://github.com/glpi-project/glpi/assets/115316656/e05ab3c1-6de8-4904-a34f-e27b07adcd5f)

Is this an error in the text field? Is it not even intended for this? And if not, shouldn't this function be disabled immediately and only be possible via the drag and drop field?

**Comment by FreeMacs** [comment]
I have now found out with an API query that if you load the photos directly into the comment field, they are probably stored base64 encoded directly in the database and this probably leads to the error.

![image](https://github.com/glpi-project/glpi/assets/115316656/ae6d390f-8782-44d0-9024-3b704455f501)
![image](https://github.com/glpi-project/glpi/assets/115316656/aa5402fa-3deb-44ef-94d6-090567fb1ef8)


After this follow-up has been deleted via the API, I can open the ticket again.
