### ISSUE TITLE
cannot create tickets manually after migration to 10.0.12 (Error: Incorrect integer value: '' for column `glpidb`.`glpi_tickets`.`sla_waiting_duration` at row 1)

### ISSUE THREAD

**Issue by GR-ASAP** [glpi-project/glpi#16537]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

When I click on "add" to create tickets , the page reloads but tickets are not created. The webpage reloads keeping fields data but ticket are not created.

Migration done 2 days ago from GLPI 10.0.11 to 10.0.12 .

### Relevant log output

```shell
[2024-02-09 10:20:16] glpisqllog.ERROR: DBmysql::doQuery() in /var/www/html/src/DBmysql.php line 403
  *** MySQL query error:
  SQL: INSERT INTO `glpi_tickets` (`name`, `content`, `entities_id`, `date`, `type`, `itilcategories_id`, `status`, `requesttypes_id`, `priority`, `slas_id_tto`, `slas_id_ttr`, `olas_id_tto`, `olas_id_ttr`, `urgency`, `impact`, `users_id_lastupdater`, `users_id_recipient`, `global_validation`, `slalevels_id_ttr`, `sla_waiting_duration`, `time_to_resolve`, `time_to_own`, `date_creation`, `date_mod`) VALUES ('test', '&#60;p&#62;test&#60;/p&#62;', '3', '2024-02-09 10:23:14', '2', '90', '1', '3', '3', '7', '8', '0', '0', '3', '3', '7', '7', '1', '0', '', '2024-02-14 10:23:14', '2024-02-12 10:23:14', '2024-02-09 11:20:16', '2024-02-09 11:20:16')
  Error: Incorrect integer value: '' for column `glpidb`.`glpi_tickets`.`sla_waiting_duration` at row 1
  Backtrace :
  src/DBmysql.php:1380                               DBmysql->doQuery()
  src/CommonDBTM.php:729                             DBmysql->insert()
  src/CommonDBTM.php:1342                            CommonDBTM->addToDB()
  front/ticket.form.php:80                           CommonDBTM->add()
  public/index.php:82                                require()
```

### Page URL

https://exemple.com/front/ticket.form.php

### Steps To reproduce

1 - Open new ticket form (Assitance -> Tickets -> Add)
2 - Fill all requeried fields
3 - Click on add to cteate the ticket
4 - The page reloads but nothing happen. 

### Your GLPI setup information

PHP-FPM 8.3.2
Apache 2.4.58

### Anything else?

Thank you for all the work done for GLPI !

**Comment by trasher** [comment]
>     * [x]  I have searched the existing issues

duplicates #16498

**Comment by GR-ASAP** [comment]
My bad... Thank you trasher for you prompt reply !
