### ISSUE TITLE
Running task Deploy - [error] [http client] Can't decode JSON content, starting with: 

### ISSUE THREAD

**Issue by mauriciolamego** [glpi-project/glpi#16542]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

I am trying to use the software deployment module but it is showing the following error in the target asset log.
the package has the target and group configured, and the deploy module enabled on the asset agents and on the server.
As a result, the installation does not start.
![Captura de tela 2024-02-10 095704](https://github.com/glpi-project/glpi/assets/40633272/00cf3269-9584-41e1-a953-6fccb20c4576)
![Captura de tela 2024-02-10 100131](https://github.com/glpi-project/glpi/assets/40633272/b5ebe68c-a8f0-4fae-be2d-58840859a5c9)

### Relevant log output

```shell
[Sat Feb 10 09:40:24 2024][info] running task Deploy
[Sat Feb 10 09:40:24 2024][error] [http client] Can't decode JSON content, starting with: 
         
<!DOCTYPE html>
<html lang="pt"       >
<head>
   <title>Autentica....o - GLPI</title>
   <meta charset="utf-8" />
...
[Sat Feb 10 09:40:24 2024][info] Deploy task not supported by server0
```

### Steps To reproduce

1. enable the client-side deploy module
2. enable the server-side deploy module
3. create computer group
4. create software package
5. Select Deployment Target
6. Go to Target and select the available software package
7. Force client side to start service
8. see the expected results by following the log.

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.11 ( => /var/www/html/glpi_ti)
Installation mode: TARBALL
Current language:pt_BR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux DPESRVPRWEB04 5.10.0-21-amd64 #​1 SMP Debian 5.10.162-1 (2023-01-21) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath,
	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M"
	disable_functions="pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,"
	
Software: Apache/2.4.54 (Debian) (Apache/2.4.54 (Debian) Server at glpi.DOMAIN Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Server Software: Debian 10
	Server Version: 10.3.31-MariaDB-0+deb10u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi_ti
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.31) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /etc/glpi_ti/var/_cache has been validated.
Write access to /etc/glpi_ti/var/_cron has been validated.
Write access to /etc/glpi_ti/var has been validated.
Write access to /etc/glpi_ti/var/_dumps has been validated.
Write access to /etc/glpi_ti/var/_graphs has been validated.
Write access to /etc/glpi_ti/var/_lock has been validated.
Write access to /etc/glpi_ti/var/_pictures has been validated.
Write access to /etc/glpi_ti/var/_plugins has been validated.
Write access to /etc/glpi_ti/var/_rss has been validated.
Write access to /etc/glpi_ti/var/_sessions has been validated.
Write access to /etc/glpi_ti/var/_tmp has been validated.
Write access to /etc/glpi_ti/var/_uploads has been validated.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi_ti/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi_ti"
GLPI_CONFIG_DIR: "/etc/glpi_ti/"
GLPI_VAR_DIR: "/etc/glpi_ti/var"
GLPI_LOG_DIR: "/etc/glpi_ti/log"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi_ti/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/etc/glpi_ti/var"
GLPI_CACHE_DIR: "/etc/glpi_ti/var/_cache"
GLPI_CRON_DIR: "/etc/glpi_ti/var/_cron"
GLPI_DUMP_DIR: "/etc/glpi_ti/var/_dumps"
GLPI_GRAPH_DIR: "/etc/glpi_ti/var/_graphs"
GLPI_LOCAL_I18N_DIR: "/etc/glpi_ti/var/_locales"
GLPI_LOCK_DIR: "/etc/glpi_ti/var/_lock"
GLPI_PICTURE_DIR: "/etc/glpi_ti/var/_pictures"
GLPI_PLUGIN_DOC_DIR: "/etc/glpi_ti/var/_plugins"
GLPI_RSS_DIR: "/etc/glpi_ti/var/_rss"
GLPI_SESSION_DIR: "/etc/glpi_ti/var/_sessions"
GLPI_TMP_DIR: "/etc/glpi_ti/var/_tmp"
GLPI_UPLOAD_DIR: "/etc/glpi_ti/var/_uploads"
GLPI_INVENTORY_DIR: "/etc/glpi_ti/var/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi_ti/locales"
GLPI_VERSION: "10.0.11"
GLPI_SCHEMA_VERSION: "10.0.11"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi_ti/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi_ti/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi_ti/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi_ti/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi_ti/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi_ti/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi_ti/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi_ti/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi_ti/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi_ti/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi_ti/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi_ti/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi_ti/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi_ti/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi_ti/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi_ti/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi_ti/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi_ti/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi_ti/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi_ti/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi_ti/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi_ti/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi_ti/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi_ti/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi_ti/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi_ti/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi_ti/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi_ti/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi_ti/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi_ti/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi_ti/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi_ti/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi_ti/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi_ti/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi_ti/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi_ti/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi_ti/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi_ti/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi_ti/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi_ti/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi_ti/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi_ti/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi_ti/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi_ti/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi_ti/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '10.243.119.11', Port: '389', BaseDN: 'DC=XXX,DC=XX,DC=XXf,DC=br,DC=local', Connection filter:
		'(&(objectClass=user)(|(department=*))(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'glpi@DOMAIN, Use TLS: none
Server: '10.166.1.12', Port: '389', BaseDN: 'dc=DOMAIN,dc=XX,dc=XXdc=br', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'glpi@DOMAIN', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (nao-responder@DOMAIN@10.243.119.2)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Campos adicionais              Version: 1.21.6     State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	archimap             Name: Diagrams                       Version: 3.3.4      State: Enabled                                 
		Install Method: Marketplace
	escalade             Name: Escalonamento                  Version: 2.9.2      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Marketplace
	gappessentials       Name: Gapp Essentials                Version: 2.2.0      State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.11.7     State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.8     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.4      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Importação de dados            Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Meu Painel                     Version: 2.1.5      State: Enabled                                 
		Install Method: Marketplace
	consumables          Name: Pedidos de consumíveis         Version: 2.0.1      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
This issue is related to a plugin, please open report on related plugin issue tracker.
