### ISSUE TITLE
interface language is not saved

### ISSUE THREAD

**Issue by this-is-boris** [glpi-project/glpi#16566]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

The interface language is not saved in the account that is synchronized via the LDAP.
For example, the country of Poland is indicated in the account, and no matter how I save the interface settings so that it is English. Still, Poland remains.
User from Ldap Active directory. Country Poland.
p.s.sorry for my english

### Steps To reproduce

1. Change language for user from 'Polish' to "Eng"
2. Log out
3. Log in language and again lang for user "Polish".

**Comment by cconard96** [comment]
Do you have your LDAP directory set to sync the language in Setup > Authentication > LDAP directories > Your LDAP > Users tab? If so, it will override any manually set language.

**Comment by this-is-boris** [comment]
omg. I did't know about this tab.  Thank you!!
