### ISSUE TITLE
Groups assigned to a public task are not shown in the simplified interface

### ISSUE THREAD

**Issue by tomaskanevicius** [glpi-project/glpi#16560]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.6

### Bug description

Groups are not visible in tasks for users who use the simplified interface. If a task is public and has an assigned executor, that's fine, it is visible in both interfaces. But if a group is assigned, it is only visible in the standard interface.
How it should look like in simplified interface:
![image](https://github.com/glpi-project/glpi/assets/62842018/8cd72ee9-90f5-46c6-bbc4-325207abffc7)
How it looks like in simplified interface:
![image](https://github.com/glpi-project/glpi/assets/62842018/0231c0ff-a3d1-484c-9be0-4757a533ddec)

Both tasks are public.

### Page URL

/front/ticket.form.php?id=xxxx

### Steps To reproduce

1. Allow users of the simplified interface to see public tasks.
2. Create a public task and assign a group of executors to it.
3. Navigate to the simplified interface and find the ticket where the task was created.
4. You cannot see who is doing the task.

### Your GLPI setup information

Operating system: Windows NT server_name 10.0 build 17763 (Windows Server 2016) AMD64
PHP 7.4.27 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, readline, session, soap, sodium, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zend-test, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Server Software: MySQL Community Server - GPL
	Server Version: 8.0.28
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi-db
	Host info: localhost via TCP/IP
	
PHP version (7.4.27) is supported.PHP version (7.4.27) is supported.
Sessions configuration is OK.Sessions configuration is OK.
Allocated memory is sufficient.Allocated memory is sufficient.
mysqli extension is installed.mysqli extension is installed.
Following extensions are installed: dom, fileinfo, json, simplexml.Following extensions are installed: dom, fileinfo, json, simplexml.
curl extension is installed.curl extension is installed.
gd extension is installed.gd extension is installed.
intl extension is installed.intl extension is installed.
libxml extension is installed.libxml extension is installed.
zlib extension is installed.zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.28) is supported.Database engine version (8.0.28) is supported.
No files from previous GLPI version detected.No files from previous GLPI version detected.
The log file has been created successfully.The log file has been created successfully.
Write access to C:\inetpub\www\glpi10/files/_cache has been validated. Write access to C:\inetpub\www\glpi10/config has been validated. Write access to C:\inetpub\www\glpi10/files/_cron has been validated. Write access to C:\inetpub\www\glpi10/files has been validated. Write access to C:\inetpub\www\glpi10/files/_dumps has been validated. Write access to C:\inetpub\www\glpi10/files/_graphs has been validated. Write access to C:\inetpub\www\glpi10/files/_lock has been validated. Write access to C:\inetpub\www\glpi10/files/_pictures has been validated. Write access to C:\inetpub\www\glpi10/files/_plugins has been validated. Write access to C:\inetpub\www\glpi10/files/_rss has been validated. Write access to C:\inetpub\www\glpi10/files/_sessions has been validated. Write access to C:\inetpub\www\glpi10/files/_tmp has been validated. Write access to C:\inetpub\www\glpi10/files/_uploads has been validated.Write access to C:\inetpub\www\glpi10/files/_cache has been validated.
Write access to C:\inetpub\www\glpi10/config has been validated.
Write access to C:\inetpub\www\glpi10/files/_cron has been validated.
Write access to C:\inetpub\www\glpi10/files has been validated.
Write access to C:\inetpub\www\glpi10/files/_dumps has been validated.
Write access to C:\inetpub\www\glpi10/files/_graphs has been validated.
Write access to C:\inetpub\www\glpi10/files/_lock has been validated.
Write access to C:\inetpub\www\glpi10/files/_pictures has been validated.
Write access to C:\inetpub\www\glpi10/files/_plugins has been validated.
Write access to C:\inetpub\www\glpi10/files/_rss has been validated.
Write access to C:\inetpub\www\glpi10/files/_sessions has been validated.
Write access to C:\inetpub\www\glpi10/files/_tmp has been validated.
Write access to C:\inetpub\www\glpi10/files/_uploads has been validated.
The following directories should be placed outside "C:\inetpub\www\glpi10": ‣ "C:\inetpub\www\glpi10/files" ("GLPI_VAR_DIR") ‣ "C:\inetpub\www\glpi10\config" ("GLPI_CONFIG_DIR") You can ignore this suggestion if you are certain that these directories are not accessible through your web server.The following directories should be placed outside "C:\inetpub\www\glpi10":
‣ "C:\inetpub\www\glpi10/files" ("GLPI_VAR_DIR")
‣ "C:\inetpub\www\glpi10\config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if you are certain that these directories are not accessible through your web server.
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol. PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
exif extension is installed.exif extension is installed.
ldap extension is installed.ldap extension is installed.
openssl extension is installed.openssl extension is installed.
zip extension is installed.zip extension is installed.
bz2 extension is installed.bz2 extension is installed.
Zend OPcache extension is installed.Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\inetpub\www\glpi10/marketplace has been validated.Write access to C:\inetpub\www\glpi10/marketplace has been validated.
Timezones seems loaded in database.Timezones seems loaded in database.

**Comment by cedric-anne** [comment]
Hi,

GLPI 10.0.6 is outdated, please try if you can reproduce on latest GLPI version.

**Comment by tomaskanevicius** [comment]
In my organisation, every new version of a product has to go through a security check, which takes quite a long time, so the product is updated quite rarely. What other options are there? I have tried to look for information about fixing this bug in the announcements of newer versions, but nobody has written about this bug, so it is very possible that it is recurring in later versions.

**Comment by trasher** [comment]
Try if you reproduce on a test environment with latest release.

**Comment by tomaskanevicius** [comment]
Hi, I have updated to the latest version of GLPI and I can confirm that I have the same problem.
