### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in D:\wamp\www\glpi\src\Features\Inventoriable.php on line 53

### ISSUE THREAD

**Issue by EC2311** [glpi-project/glpi#16573]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Every 5 minutes, in php-errors.log : 
PHP Parse error:  syntax error, unexpected '?', expecting function (T_FUNCTION) or const (T_CONST) in D:\wamp\www\glpi\src\Features\Inventoriable.php on line 53

### Your GLPI setup information

GLPI 10.0.10
php 8.0.26 or php 8.1.26
mysql 8.0.22
apache 2.4.54.2

**Comment by trasher** [comment]
There is no syntax error in that file. You probably edited this file, and made a mistake.

Also, 10.0.10 is outdated, consider upgrading.

**Comment by EC2311** [comment]
Hello 
No update done on the script itself.
and on another environnement (dev) it's ok. (same version php, apache  and mysql)
here we are on pre-prod.

it look likes this script is called every 5 minutes like a cron task.

**Comment by cconard96** [comment]
If the issue is noticed when called from cron, then your system's default version of PHP is too old. The version used by Apache is set separately.
```php --version```
Use whatever method applies to your OS to change the default PHP version.

**Comment by EC2311** [comment]
php version is 8.0.26 or 8.1.26 : whatever these version, i have this error :(

**Comment by EC2311** [comment]
A thing I don't understand : 
in the 'system' notes in glpi : I do see the good version of php used (8.1.26) : ok
but I installed mysql 8.0.22
![image](https://github.com/glpi-project/glpi/assets/42341169/496aae74-4b2f-4fb5-b9f4-8a0bef695a98)

and in glpi I see : database engine 5.7.19.
I stopped wamp and restarted it : still 5.7.19

**Comment by trasher** [comment]
Original issue cannot be reproduced on our side: there is no syntax error in that file (try a `php -l path/to/that/file`). No bug here.

Since your database version is not the one you expect, I guess the PHP running crontab one is not the one you expect neither. You also seem a kind of surprised call comes from a cron... But if there is a cron; that's been setted up on your system, not from GLPI.

Please use forums to get support.
