### ISSUE TITLE
No global Kanban in 'Assistance'

### ISSUE THREAD

**Issue by ShonkaiDJ** [glpi-project/glpi#16594]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.8

### Bug description

I cannot see a global kanban for the tickets. I do find screenshots online that show me it exists. I looked all over to find some configuration but it just does not seem to work.

### Steps To reproduce

1. Go to projects
2. Open global kanban, it shows
3. Go to assistance
4. Open global kanban, nothing showing

### Your GLPI setup information

Nginx with phpfpm

### Anything else?

Not sure of the bug, Itil wise it doesn't seem to be a problem but  i really can't find anything on it for a few weeks now. Workable situation so no hurry at all.

**Comment by trasher** [comment]
Update to latest stable release, and feel frre to reopen if issue persists. 10.0.8 is very outdated.
