### ISSUE TITLE
Bug in statistic by ticket (0.85 & 0.90)

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#166]
http://forum.glpi-project.org/viewtopic.php?id=127286

**Comment by orthagh** [comment]
link dead :S

**Comment by yllen** [comment]
ben si le sujet a été supprimé... heureusement que j'ai bonne mémoire...
Dans les statistiques par ticket, il n'est pas possible de supprimer une option d'affichage (L'action que vous avez réalisée n'est pas autorisée.)
J'ai confirmé le bug et je le corrigerais vendredi.
