### ISSUE TITLE
Mentions unavailable when creating a ticket via web interface

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#16604]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

When creating a ticket via web, mentioning functionality does **not** exist/trigger.

### Relevant log output

```shell
N/A
```

### Page URL

/front/helpdesk.public.php

### Steps To reproduce

1. Make sure your are using profile "self-service"
2. Click on "Create a ticket"
3. Try to mention someone in the Description field
4. Observe that there's no mentioning functionality

### Your GLPI setup information

N/A

### Anything else?

Might be related to https://github.com/glpi-project/glpi/issues/15230

Idea/proposal - probably only people who are in the same entity as ticket creator should mentionable when creating a ticket.

Thing to note is that users are already expecting mentioning to be available everywhere, as they like it very much when there's discussion happening in ticket. Having mentions unavailable when creating a ticket is surprising, as it's immediately available after ticket creation.

**Comment by Kuba-Pawlak** [comment]
Sorry my bad. I searched in opened issues

**Comment by cedric-anne** [comment]
Hi,

This feature is indeed not enabled on the simplified interface.

As it exposes the name of all the users that have an habilitation on thee current entity, I am not sure that enabling it is not a good idea.

**Comment by AldarisPale** [comment]
Just to add some background why I think it's important:

1. If it's not available on the screen most people see the most, users will probably assume it's not available at all anywhere in GLPI
2. In order to reduce the risk, it should be accessible only when a person has logged in - the same way it would be available after they have created the ticket and discussion in ongoing.
