### ISSUE TITLE
Duplicate recurring tickets

### ISSUE THREAD

**Issue by pippo571** [glpi-project/glpi#16602]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

Hello,

I have a problem with (some of) my recurring tickets after upgrading to version 10.0.12.

When a recurring ticket is created, it is then duplicated every 5 minutes until I set it to "Active : No". 

This does not happen with all my recurring tickets.
All the recurring tickets (impacted or not) were present before the upgrade.

All duplicated tickets are created with the same opening date, and their last update time is 1 hour before, incrementing by the duplication time, then updates the opening date after last update = opening date. Example that I reproduced today :

- First ticket created at 15:00 - Opening date 15:00 - Last update 14:00
- Duplicate 1 created at 15:05 - Opening date 15:00 - Last update 14:05
- Duplicate 2 created at 15:10 - Opening date 15:00 - Last update 14:10
- etc ...
- Duplicate X created at 16:00 - Opening date 15:00 - Last update 15:00
- Duplicate X+1 created at 16:05 - Opening date 16:00 - Last update 16:05
- Duplicate X+1 created at 16: - Opening date 16:00 - Last update 16:10
- etc...

I also tried to create a new recurring ticket using a new ticket template with only description and title as predefined fields, same problem.

RecurrentItems automatic action is set to run in CLI mode every 5 minutes, no error in the task logs in GLPI, get "1	Action completed, fully processed" for all tickets.

Tried to move the recurring ticket to another entity, did not help.
Tried to clone ticket and delete the original, same result.
Tried to delete and 

All recurring tickets use the same calendar.
All are visible for sub entities.
None have an end date.
Some impacted and non-impacted tickets are in the same entity.

### Relevant log output

Cannot find any relevant logs for that. 

```shell

- access-error.logs Only has CSRF check failed lines for a few past months : 


2024-02-20 19:01:21 [7@elrond]
CSRF check failed for User ID: 7 at /front/itilfollowup.form.php
```

- sql-errors.log last log is from January : 

```
[2024-01-05 19:47:43] glpisqllog.ERROR: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 403
  *** MySQL query error:
  SQL: UPDATE `glpi_planningrecalls` SET `when` = DATE_SUB('NULL', INTERVAL `before_time` SECOND) WHERE `itemtype` = 'TicketTask' AND `items_id` = '9749'
  Error: Incorrect datetime value: 'NULL'
  Backtrace :
  src/DBmysql.php:1503                               DBmysql->doQuery()
  src/PlanningRecall.php:242                         DBmysql->update()
  src/CommonITILTask.php:401                         PlanningRecall::managePlanningUpdates()
  src/CommonDBTM.php:1747                            CommonITILTask->post_updateItem()
  src/CommonITILTask.php:1945                        CommonDBTM->update()
  front/commonitiltask.form.php:111                  CommonITILTask->unplan()
  front/tickettask.form.php:39                       include()
  public/index.php:82                                require()
  {"user":"7@elrond"} 
```

- php-error.log contains only testlogger lines : 

```
[2024-02-21 15:44:45] glpiphplog.WARNING: Test logger  
[2024-02-21 15:45:45] glpiphplog.WARNING: Test logger
```

### Steps To reproduce

1. Set the automatic action "RecurrentItems" to run in CLI mode every 5 minutes.

2. Set cron for GLPI in your server crontab (that must be set in the crontab of the user running your webserver): `*/5 * * * * /usr/bin/php /var/www/glpi/front/cron.php &>/dev/null `

3. Create a new ticket template.

4. Add predefined fields : 
    - Title 
    - Description

5. Create a recurring ticket that is active and uses the template you created at step 1 and 2.

6. No end date, no preliminary creation, use the default calendar.

7. Set periodicity to 1 hour.

8. Set a start date.

9. Wait for the ticket to be created.

10. Every 5 minutes after that, a duplicate should be created. 

11. Set the recurring ticket to "Active: No" or delete it to stop the duplicates from being generated.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.12 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux elrond 5.10.0-27-amd64 #​1 SMP Debian 5.10.205-2 (2023-12-31) x86_64
PHP 8.3.2-1+0~20240120.16+debian11~1.gbpb43448 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath,
	bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: nginx/1.18.0
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:123.0) Gecko/20100101 Firefox/123.0
Server Software: Debian 11
	Server Version: 10.5.21-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.3.2-1+0~20240120.16+debian11~1.gbpb43448) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.21) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/_cache has been validated.
Write access to /var/lib/glpi/_cron has been validated.
Write access to /var/lib/glpi has been validated.
Write access to /var/lib/glpi/_dumps has been validated.
Write access to /var/lib/glpi/_graphs has been validated.
Write access to /var/lib/glpi/_lock has been validated.
Write access to /var/lib/glpi/_pictures has been validated.
Write access to /var/lib/glpi/_plugins has been validated.
Write access to /var/lib/glpi/_rss has been validated.
Write access to /var/lib/glpi/_sessions has been validated.
Write access to /var/lib/glpi/_tmp has been validated.
Write access to /var/lib/glpi/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_CONFIG_DIR: "/etc/glpi"
GLPI_VAR_DIR: "/var/lib/glpi"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/lib/glpi"
GLPI_CACHE_DIR: "/var/lib/glpi/_cache"
GLPI_CRON_DIR: "/var/lib/glpi/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/_locales"
GLPI_LOCK_DIR: "/var/lib/glpi/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.12"
GLPI_SCHEMA_VERSION: "10.0.12@b902ef5f5da967c1a9d0826ee8a7dce07d57cf3d"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@localhost)

</pre></details><details><summary>Plugins list</summary><pre> 

</pre></details>

**Comment by pippo571** [comment]
Hello,

This indeed seems to solve the problem.

I had a difference of 1 hour between PHP and MariaDB time, both were using their default value (system timezone for MariaDB and UTC for PHP), setting PHP to my system timezone solved the issue, the tickets are now created correcty and not duplicated anymore. 

Thanks :)

**Comment by cedric-anne** [comment]
Thanks for the feedback, I close this issue as it duplicates #9913.

**Comment by clesiosantos** [comment]
I'm using version 10.0.15 and I'm having a similar problem.

GLPI configured for America/Sao_Paulo
Mariadb configured for America/Sao_Paulo
PHP configured for America/Sao_Paulo

When cloning a ticket, the cloned ticket keeps the opening date of the old ticket
