### ISSUE TITLE
Erros: timestamps, utf8mb4, unsigned_keys ao atualizar o glpi para a versão 10.0.12

### ISSUE THREAD

**Issue by Scjonatha** [glpi-project/glpi#16603]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

![Capturar2](https://github.com/glpi-project/glpi/assets/97475763/87ab6f7b-ea48-4915-9ca4-0951b68a0a43)

realizei uma atualização da versão 9.5.7 para a versão 10.0.12 (utilizo o windows server), após essa atualização esse erro começou a aparecer e então executei o comando:
```
C:\xampp\htdocs\glpi> php bin/console migration:timestamps
``` 
e o seguinte erro foi retornado: 
```
'php' não é reconhecido como um comando interno ou externo. programa operável ou arquivo em lote
```
Já pesquisei como resolver porém não compreendi muito bem as resoluções que encontrei.
Acredito que esteja faltando algum arquivo na pasta do meu glpi como o informado nesse problema: https://github.com/glpi-project/glpi/issues/8225. Caso seja a falta de algum arquivo, como consigo baixar esse arquivo para o meu diretório do glpi e qual a forma correta de executar esses comandos .php via cmd sem retornar os erros citados?
![folder bin](https://github.com/glpi-project/glpi/assets/97475763/f596c558-26df-419e-84e4-eaa5b2f203f0)
![folder inc](https://github.com/glpi-project/glpi/assets/97475763/22ed3931-8a7a-4329-ad8a-8c614cc09232)
obs: o glpi está instalado no xampp versão 8.2.12

### Your GLPI setup information

glpi 10.0.12 instalado no xampp versão 8.2.12

**Comment by cconard96** [comment]
Please write in English (automatic translations are OK).

Having issues reported all in English helps ensure that searching for existing/already reported issues is easier.
Also, the community and development team is international so having a common language helps us too.

Por favor, escreva em inglês (as traduções automáticas não têm problemas).

Ter os problemas relatados todos em inglês ajuda a garantir que a pesquisa de problemas existentes/já relatados seja mais fácil.
Além disso, a comunidade e a equipa de desenvolvimento são internacionais, pelo que ter uma língua comum também nos ajuda.
