### ISSUE TITLE
Poor behavior of business rules for tickets

### ISSUE THREAD

**Issue by IT-CELAD** [glpi-project/glpi#16619]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

Business rules for Tickets with condition Status is Solved AND any other conditions is not evaluating properly if state of ticket is changed as result of "Processing Ticket" flow.

Instead rule matches and Action is executed when:

- State of ticket is changed directly adjusting "State" dropdown rule matches.
- Also if there is only one condition in rule: "state is Solved"

Looks like a bug which is related to action of Processing Ticket -> "Solution" workflow.

### Steps To reproduce

1. Create Business rule for tickets with example following conditions (at least 2 one of which is not state):
  - Logical operator: add
  - Use rule for: Add/Update
  - Condition:
    - Status "is" Solved
    - Category "is" XXX
  - Action:
    - Followup template add "YYY"
    - Status assign "Processing (assigned)"

2. Create ticket with Category XXX

Go to Processing ticket ->Solution. Fill in "Solution Type" and Description. Click "+Add".
**Result:**
Ticket state is changed to Solved but rule is not matched/Action not executed

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.12 ( => /var/www/glpi.yyy.com/public_html)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi.xxx.yyy.com 4.18.0-425.10.1.el8_7.x86_64 #​1 SMP Thu Jan 12 10:05:00 EST 2023 x86_64
PHP 8.2.15 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, random, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" disable_functions="" 
Software: Apache/2.4.37 (AlmaLinux) OpenSSL/1.1.1k PHP/8.2.15 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
Server Software: MariaDB Server
	Server Version: 10.3.39-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.15) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/glpi.yyy.com/public_html/files/_cache has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_cron has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_dumps has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_graphs has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_lock has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_pictures has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_plugins has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_rss has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_sessions has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_tmp has been validated.
Write access to /var/www/glpi.yyy.com/public_html/files/_uploads has been validated.
SELinux configuration is OK.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/glpi.yyy.com/public_html":
‣ "/var/www/glpi.yyy.com/public_html/files" ("GLPI_VAR_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/glpi.yyy.com/public_html/public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi.yyy.com/public_html/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi.yyy.com/public_html"
GLPI_CONFIG_DIR: "/var/www/glpi.yyy.com/public_html/config"
GLPI_VAR_DIR: "/var/www/glpi.yyy.com/public_html/files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi.yyy.com/public_html/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/glpi.yyy.com/public_html/files"
GLPI_CACHE_DIR: "/var/www/glpi.yyy.com/public_html/files/_cache"
GLPI_CRON_DIR: "/var/www/glpi.yyy.com/public_html/files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi.yyy.com/public_html/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi.yyy.com/public_html/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi.yyy.com/public_html/files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi.yyy.com/public_html/files/_lock"
GLPI_LOG_DIR: "/var/www/glpi.yyy.com/public_html/files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi.yyy.com/public_html/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi.yyy.com/public_html/files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi.yyy.com/public_html/files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi.yyy.com/public_html/files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi.yyy.com/public_html/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi.yyy.com/public_html/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi.yyy.com/public_html/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi.yyy.com/public_html/locales"
GLPI_VERSION: "10.0.12"
GLPI_SCHEMA_VERSION: "10.0.12@b902ef5f5da967c1a9d0826ee8a7dce07d57cf3d"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi.yyy.com/public_html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi.yyy.com/public_html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi.yyy.com/public_html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi.yyy.com/public_html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi.yyy.com/public_html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi.yyy.com/public_html/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi.yyy.com/public_html/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi.yyy.com/public_html/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi.yyy.com/public_html/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi.yyy.com/public_html/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi.yyy.com/public_html/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi.yyy.com/public_html/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi.yyy.com/public_html/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi.yyy.com/public_html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi.yyy.com/public_html/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi.yyy.com/public_html/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi.yyy.com/public_html/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi.yyy.com/public_html/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi.yyy.com/public_html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi.yyy.com/public_html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi.yyy.com/public_html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi.yyy.com/public_html/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi.yyy.com/public_html/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi.yyy.com/public_html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi.yyy.com/public_html/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi.yyy.com/public_html/vendor/psr/cache/src)
league/csv in (/var/www/glpi.yyy.com/public_html/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi.yyy.com/public_html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi.yyy.com/public_html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi.yyy.com/public_html/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi.yyy.com/public_html/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi.yyy.com/public_html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi.yyy.com/public_html/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi.yyy.com/public_html/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi.yyy.com/public_html/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi.yyy.com/public_html/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi.yyy.com/public_html/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi.yyy.com/public_html/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi.yyy.com/public_html/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi.yyy.com/public_html/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi.yyy.com/public_html/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi.yyy.com/public_html/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi.yyy.com/public_html/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'xxx.yyy.com', Port: '389', BaseDN: 'OU=Utilisateurs,DC=***,DC=***,DC=***', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=Administrateur,OU=Sans Stratégies,DC=xxx,DC=yyy,DC=com',
		Use TLS: none
Server: 'A.B.C.2', Port: '389', BaseDN: 'DC=zzz,DC=com', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=Ldap BROWSER,CN=Users,DC=zzz,DC=com', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (user@yyy.com@smtp.office365.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertes                        Version: 1.12.1     State: Enabled                                 
		Install Method: Marketplace
	treeview             Name: Arborescence                   Version: 1.10.2     State: Enabled                                 
		Install Method: Marketplace
	barcode              Name: Barcode                        Version: 2.7.1      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.21.6     State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	mydashboard          Name: Dashboard                      Version: 2.1.5      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	escalade             Name: Escalades                      Version: 2.9.2      State: Enabled                                 
		Install Method: Marketplace
	useditemsexport      Name: Export des éléments utilisés   Version: 2.5.1      State: Enabled                                
		 Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gestion d'objets               Version: 2.14.8     State: Enabled                                 
		Install Method: Marketplace
	tag                  Name: Gestion des tags               Version: 2.11.7     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.4      State: Enabled                                 
		Install Method: Marketplace
	manufacturersimports Name: Imports fabricants             Version: 3.0.5      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.6      State: Enabled                                 
		Install Method: Marketplace
	protocolsmanager     Name: Protocols manager              Version: 1.4.2.1    State: Enabled                                 
		Install Method: Manual
	webresources         Name: Web Resources                  Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by cconard96** [comment]
This is a known behavior and not a bug. In most cases (I think there are a few exceptions), rules only match and modify the state of an action. For example during updates, the criteria only matches on the changes you attempt to make. There is no way to access the current state (before the update) of the ticket. Unless the status AND category are changed at the same time, the rule will not match. In your example, the ticket's category was already set before you added the solution and therefore changed the status to solved.

**Comment by IT-CELAD** [comment]
Alright, but it works when I manually change the status. Is there a way to have this behavior in a regular workflow?
