### ISSUE TITLE
Missing notifications for events

### ISSUE THREAD

**Issue by blippercop** [glpi-project/glpi#16616]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

When creating an external event it is not possible to invite a team (group) so I added all colleagues as guests.

However, when I set the notification I receive an email notification but none of the "guests" are receiving one.

As the events are "write-protected copies" (stated in the decription for the guests) they should receive the notification too.

But they are not receiving the notification - only I am receiving the notification.

**Comment by cconard96** [comment]
Did you test on the latest 10.0.X version?
What recipients are configured for the notification?

Please include the information that was requested in the bug report template including steps to reproduce and your GLPI setup information.
