### ISSUE TITLE
10.0.12 : Error: Incorrect integer value: '' for column `glpi`.`glpi_tickets`.`sla_waiting_duration` at row 1

### ISSUE THREAD

**Issue by RaivoMahnovs** [glpi-project/glpi#16611]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

Hello,

When i want to generate a new ticket manually from assistance/+ Create Ticket, i have no informationabout ticket being created and i have one error message in the sql-errors.log

![sql-errors](https://github.com/glpi-project/glpi/assets/120176527/43a280a9-79bc-47dd-9628-582aacb1d12e)

### Page URL

/glpi/front/ticket.form.php

### Steps To reproduce

1. Go to Assistance tab
2. Click on "+ Create Ticket" button
3. Edit title, description, entity and assigned technician
4. Click "+ Add" button

### Your GLPI setup information

![image](https://github.com/glpi-project/glpi/assets/120176527/4d28617c-7895-4143-b809-3448cee752b1)

**Comment by trasher** [comment]
Already reported and fixed, please search existing issues.
