### ISSUE TITLE
impossible to add attachment in ticket

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1662]
Hello

I updated glpi to master version for test and when I want to add an attachment this error appears

![image](https://cloud.githubusercontent.com/assets/15144026/22109474/33695b02-de58-11e6-859f-16c74c8be50d.png)

same in computers

![image](https://cloud.githubusercontent.com/assets/15144026/22109542/83de7306-de58-11e6-867e-ebc3430040b7.png)

**Comment by orthagh** [comment]
see incoming #1633

**Comment by satyan01** [comment]
after modification

error

![image](https://cloud.githubusercontent.com/assets/15144026/22110046/99408dfe-de5a-11e6-995c-10d63c09498e.png)

**Comment by satyan01** [comment]
I tried with pdf / xlsx / doc, same behavior

**Comment by orthagh** [comment]
could you describe which way you the attachment ? select, drop ?

**Comment by satyan01** [comment]
both gives same behavior

**Comment by satyan01** [comment]
It works with png file but not other extension

**Comment by satyan01** [comment]
xlsx pdf doc... are authorized

**Comment by orthagh** [comment]
See: https://github.com/glpi-project/glpi/pull/1665/files
It should fix your issue

**Comment by satyan01** [comment]
I have already done it but it does not fix the issue

**Comment by satyan01** [comment]
jpg works as well, so it seems just image format works

**Comment by orthagh** [comment]
tested on my side, @tsmr also, pdf/xlsx/txt work.
Are you sure you pulled the last master version (we merged the last fix)

**Comment by satyan01** [comment]
yes from 12h30

**Comment by satyan01** [comment]
and added your modification after manually

**Comment by orthagh** [comment]
Do you still have the same error ("filetype...") ?
Do you see lines in glpi/files/_log/php_errors.log after adding last modification ?

**Comment by satyan01** [comment]
it works with this commit 82a0bbb

**Comment by satyan01** [comment]
thx a lot for your help
