### ISSUE TITLE
Inventory file missing / getFromDBByCrit expects to get one result, 4 found

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#16636]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

1. I am debugging why I cannot download inventory files for computers.
2. I noticed that when I enabled debug mode, warning shows up: ```PHP User Warning (512): getFromDBByCrit expects to get one result, 4 found in query "SELECT `id` FROM `glpi_autoupdatesystems` WHERE `name` = 'GLPI Native Inventory'". in /var/www/html/src/CommonDBTM.php at line 393```

### Relevant log output

```shell
glpiphplog.WARNING:  *** PHP User Warning (512): getFromDBByCrit expects to get one result, 4 found in query "SELECT `id` FROM `glpi_autoupdatesystems` WHERE `name` = 'GLPI Native Inventory'". in /var/www/html/src/CommonDBTM.php at line 393
  Backtrace :
  src/CommonDBTM.php:393               trigger_error()
  src/Features/Inventoriable.php:79         CommonDBTM->getFromDBByCrit()
  .../twig/twig/src/Extension/CoreExtension.php:1635 Computer->getInventoryFileName()
  ...ates/54/5451dd728b6d735e7bf4bf59394a62e2.php:55 twig_get_attribute()
  vendor/twig/twig/src/Template.php:394       __TwigTemplate_8a735c63e6573d9b7dac89935ced263a->doDisplay()
  vendor/twig/twig/src/Template.php:367       Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/Template.php:379       Twig\Template->display()
  vendor/twig/twig/src/TemplateWrapper.php:38    Twig\Template->render()
  .../twig/twig/src/Extension/CoreExtension.php:1347 Twig\TemplateWrapper->render()
  ...tes/bb/bb9a33248aefcf5fe6ab393447b28839.php:146 twig_include()
  vendor/twig/twig/src/Template.php:394       __TwigTemplate_02cbc319cab622925b02080ec3a01f21->doDisplay()
  vendor/twig/twig/src/Template.php:367       Twig\Template->displayWithErrorHandling()
  vendor/twig/twig/src/TemplateWrapper.php:45    Twig\Template->display()
  src/Application/View/TemplateRenderer.php:184   Twig\TemplateWrapper->display()
  src/CommonDBTM.php:492               Glpi\Application\View\TemplateRenderer->display()
  src/CommonGLPI.php:680               CommonDBTM->showForm()
  ajax/common.tabs.php:120              CommonGLPI::displayStandardTab()
  public/index.php:82                require()
```

### Page URL

front/computer.form.php

### Steps To reproduce

1. Enable glpi native inventory plugin
2. Allow computers to send inventory
3. Notice that you cannot download inventory file
4. Enable debug mode
5. Notice warning message

### Your GLPI setup information

GLPI 10.0.12, TARBALL
Plugins:
fields 1.21.6
glpiinventory 1.3.4
genericobject 2.14.8

### Anything else?

- We migrated from 9.x last week which had fusioninventory plugin.
- This bug might be related to https://github.com/glpi-project/glpi-inventory-plugin/issues/380
- When checking front/autoupdatesystem.php I notice that there are four (4) instances of "GLPI Native Inventory" listed there. Each of those instance has 1 entry in the "Historical" tab: "Add the item". The time is exactly the same for all 4 instances.
- Perhaps I could just delete all the instances except for 1? I'm worried about potential information loss though.
- Agents running on the computers are fusioninventory latest agents, cannot upgrade them yet.

**Comment by stonebuzz** [comment]
Just delete all instances, GLPI Well handle this case and will recreate a single instance

**Comment by stonebuzz** [comment]
Please use glpi-agent, fusion-inventory agent is no longer maintained

**Comment by stonebuzz** [comment]
In the first versions of GLPI 10.x, we kept a compatibility with fusion, but forced to note that we move away (or him) from the native inventory, we manage here only the problems of the native inventory or GLPI Agent.

**Comment by trasher** [comment]
> Just delete all instances, GLPI Well handle this case and will recreate a single instance

This should indeed solve the issue; the root cause (which cannot be defined) may be an update glitch from the original plugin.

I close, feel free to reopen if issues persists in the future.
