### ISSUE TITLE
glpiphplog.WARNING: Failed to save key "{key}" of type int

### ISSUE THREAD

**Issue by AldarisPale** [glpi-project/glpi#16637]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

php-errors.log contains error message related to caching, bin/console cache:clear does not make it go away

### Relevant log output

```shell
glpiphplog.WARNING: Failed to save key "{key}" of type int: rename(/var/www/html/files/_cache/core/467d1f57917a,/var/www/html/files/_cache/core/V/I/4mVnQYV7w8xMPKgbq7QA): No such file or directory {"key":"f30f21a0fbd74265283f2095d8a477600fddf8a8","exception":"[object] (ErrorException(code: 0): rename(/var/www/html/files/_cache/core/467d1f57917a,/var/www/html/files/_cache/core/V/I/4mVnQYV7w8xMPKgbq7QA): No such file or directory at /var/www/html/vendor/symfony/cache/Traits/FilesystemCommonTrait.php:117)","cache-adapter":"Symfony\\Component\\Cache\\Adapter\\FilesystemAdapter"}
```

### Page URL

N/A

### Steps To reproduce

1. Migrate from 9.x
2. bin/console cache:configure --use-default
3. bin/console cache:clear
4. check php-errors.log

### Your GLPI setup information

GLPI 10.0.12, TARBALL
Plugins:
fields 1.21.6
glpiinventory 1.3.4
genericobject 2.14.8

**Comment by trasher** [comment]
Please double check web user does have proper access on cache directory.
