### ISSUE TITLE
Add and remove switch port all the time

### ISSUE THREAD

**Issue by francisco-vilaca** [glpi-project/glpi#16632]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.12

### Bug description

GLPI is adding and removing switch ports every scan

![image](https://github.com/glpi-project/glpi/assets/144910601/7c970e87-c0be-4393-bc82-0e80209a1b4e)

### Steps To reproduce

.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.12 ( => /var/www/glpi-prod/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.15.0-94-generic #​104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64
PHP 8.2.7 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json,
	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop, soap,
	sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at glpi.bel.ind.br Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Server Software: Ubuntu 22.04
	Server Version: 10.6.16-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_admin@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version (8.2.7) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.16) is supported.
No files from previous GLPI version detected.
The log file could not be created in /var/www/glpi-prod/glpi/../files/_log.
Write access to /var/www/glpi-prod/glpi/../files/_cache has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_cron has been validated.
Write access to /var/www/glpi-prod/glpi/../files has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_dumps has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_graphs has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_lock has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_pictures has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_plugins has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_rss has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_sessions has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_tmp has been validated.
Write access to /var/www/glpi-prod/glpi/../files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi-prod/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi-prod/glpi"
GLPI_CONFIG_DIR: "/var/www/glpi-prod/glpi/config"
GLPI_VAR_DIR: "/var/www/glpi-prod/glpi/../files"
GLPI_MARKETPLACE_DIR: "/var/www/glpi-prod/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/glpi-prod/glpi/../files"
GLPI_CACHE_DIR: "/var/www/glpi-prod/glpi/../files/_cache"
GLPI_CRON_DIR: "/var/www/glpi-prod/glpi/../files/_cron"
GLPI_DUMP_DIR: "/var/www/glpi-prod/glpi/../files/_dumps"
GLPI_GRAPH_DIR: "/var/www/glpi-prod/glpi/../files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/glpi-prod/glpi/../files/_locales"
GLPI_LOCK_DIR: "/var/www/glpi-prod/glpi/../files/_lock"
GLPI_LOG_DIR: "/var/www/glpi-prod/glpi/../files/_log"
GLPI_PICTURE_DIR: "/var/www/glpi-prod/glpi/../files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/glpi-prod/glpi/../files/_plugins"
GLPI_RSS_DIR: "/var/www/glpi-prod/glpi/../files/_rss"
GLPI_SESSION_DIR: "/var/www/glpi-prod/glpi/../files/_sessions"
GLPI_TMP_DIR: "/var/www/glpi-prod/glpi/../files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/glpi-prod/glpi/../files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/glpi-prod/glpi/../files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi-prod/glpi/locales"
GLPI_VERSION: "10.0.12"
GLPI_SCHEMA_VERSION: "10.0.12"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi-prod/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi-prod/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi-prod/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi-prod/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi-prod/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi-prod/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi-prod/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi-prod/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi-prod/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi-prod/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi-prod/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi-prod/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi-prod/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi-prod/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi-prod/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi-prod/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi-prod/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi-prod/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi-prod/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi-prod/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi-prod/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi-prod/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi-prod/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi-prod/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi-prod/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi-prod/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi-prod/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi-prod/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi-prod/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi-prod/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi-prod/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi-prod/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi-prod/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi-prod/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi-prod/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi-prod/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi-prod/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi-prod/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi-prod/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi-prod/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '172.16.100.8', Port: '389', BaseDN: 'dc=belfix,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'belfix\francisco.vilaca', Use TLS: none
Server: '172.16.100.10', Port: '636', BaseDN: 'dc=belfix,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'belfix\francisco.vilaca', Use TLS: '1'

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (alertas@bel.ind.br@sender.skymail.net.br)

</pre></details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertas                        Version: 1.12.1     State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Campos adicionais              Version: 1.21.8     State: Enabled                                 
		Install Method: Marketplace
	databaseinventory    Name: Database Inventory             Version: 1.0.0      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: Endereçamento IP               Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.0.4      State: Enabled                                 
		Install Method: Marketplace
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.8     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Marketplace
	mod                  Name: GLPI Modifications             Version: 10.0.1     State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Importação de dados            Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Mais Relatórios                Version: 1.8.6      State: Enabled                                 
		Install Method: Marketplace
	singlesignon         Name: Single Sign-on                 Version: 1.3.4      State: Enabled                                 
		Install Method: Manual
	tasklists            Name: Tasks list                     Version: 2.0.3      State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
I do not reproduce that issue using inventory file in my possession. Try to reproduce on a blank install, and in that case provide us an inventory file to reproduce.

**Comment by francisco-vilaca** [comment]
I don't think you have the files of this 2 switch, I will attach here. 
What do you mean by blanc install? A new GLPI installation ?

[networkequipment_0_98.txt](https://github.com/glpi-project/glpi/files/14420837/networkequipment_0_98.txt)

[networkequipment_0_99.txt](https://github.com/glpi-project/glpi/files/14420836/networkequipment_0_99.txt)

**Comment by trasher** [comment]
> I don't think you have the files of this 2 switch, I will attach here. What do you mean by blanc install? A new GLPI installation ?

Yes. That issue can cam from already existing data in base. Testing with a brand new GLPI permits to ba sure of that.

**Comment by trasher** [comment]
> [networkequipment_0_98.txt](https://github.com/glpi-project/glpi/files/14420837/networkequipment_0_98.txt)
> 
> [networkequipment_0_99.txt](https://github.com/glpi-project/glpi/files/14420836/networkequipment_0_99.txt)

I cannot reproduce with thos files. On my default install, only the `last_inventory_date` is present in history.

**Comment by francisco-vilaca** [comment]
I think that the problem is because you are just importing the device and the problem happens when you run a snmp scan when the device already exists

**Comment by trasher** [comment]
Fom a strict GLPI point of view, that does not matters, if file on "day 1" and on "day 2" are the same.

**Comment by francisco-vilaca** [comment]
.

**Comment by francisco-vilaca** [comment]
I'm closing this case without solution. I'm facing too many problems with GLPI inventory, I'm gonna tray to find a new inventory solution
