### ISSUE TITLE
Knowledge base UPDATE rights

### ISSUE THREAD

**Issue by tomaskanevicius** [glpi-project/glpi#16647]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

This problem is repeated in previous versions
Ticket resolvers can only attach a document from the knowledge base with UPDATE permissions.

Since they have UPDATE permissions, they can edit the records in the knowledge base.

The objective is to make it possible for a ticket solver to attach a document from the knowledge base to a ticket without having UPDATE rights in the knowledge base module.

It would be good if, with the rights as shown in the picture, he could read the knowledge base, but also have the right to link a record from the knowledge base inside the ticket

![image](https://github.com/glpi-project/glpi/assets/62842018/3468e2f6-26a0-47b4-a536-2521ca7bc23f)
![image](https://github.com/glpi-project/glpi/assets/62842018/d2adfde6-9e88-4df6-ad42-9ba3a1bb7657)

**Comment by tomaskanevicius** [comment]
Can anyone confirm that this behaviour is not normal and needs to be corrected? I can elaborate on the situation if necessary, in case there are any questions

**Comment by arthurrschaefer** [comment]
I tested here on 10.0.14.

When you have 'UPDATE' rights set, you may add the article to a ticket, due to the associated elements tab.
Even if the user has the update rights, without the 'KNOWLEDGE BASE ADMINISTRATION' permission, the user is not able to edit the article.
Can you test it that way?
