### ISSUE TITLE
Ticket posting session inactive after a certain period of time

### ISSUE THREAD

**Issue by aha999** [glpi-project/glpi#16653]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

When i am trying to post/publish a ticket in GLPI (Assistance->Create ticket) and have some content written, then i start doing other tasks and come back to the ticket after 10 minutes (for example), finish writing the ticket and try to post it, i get an error that the action is not allowed and i have to re-do the entire ticket, which could have taken me a while to complete and there is no way in my knowledge to restore the last edit, so i wouldn't have to rewrite the entire ticket. 
Current personal "solution" is that the content is copied before posting the ticket in case this would happen.

I am currently using version 9.5.6. Is this Issue/Bug fixed in GLPI 10.x.x. or in any way migitated?

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Start writing a ticket (menu Assistance->Create ticket)
2. Wait 10 minutes (for example) so GLPI makes this session inactive
3. try to post a ticket
4. ticket was not posted, text saying "The action you have requested is not allowed"
5. Start writing the ticket again, making sure, you copy the text before posting in case this happens again.

**Comment by cedric-anne** [comment]
Hi,

It will be fixed in GLPI 11 by #16626.

**Comment by aha999** [comment]
@cedric-anne I don't get a warning named _Your session has expired_, as it is seen in the #16626, but _The action you have requested is not allowed_. Is the fix related to "both" issues or warning texts?

**Comment by cedric-anne** [comment]
> @cedric-anne I don't get a warning named _Your session has expired_, as it is seen in the #16626, but _The action you have requested is not allowed_. Is the fix related to "both" issues or warning texts?

Yes. The message was a bit different in GLPI 10.0.

By the way, you should upgrade to GLPI 10.0, at least to get latest security fixes.
