### ISSUE TITLE
vertical split bug

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1667]
Hello

Some users are using vertical split, when they maximize task area size in full screen, it is behind ticket form, so they don't see what they write.

![bug](https://cloud.githubusercontent.com/assets/15144026/22116564/261592ea-de71-11e6-84be-6e02e6556d59.png)

**Comment by tomolimo** [comment]
Hello,
Seems like it is still existing even in GLPI 9.2, 9.3, and 9.4
Thank you
Regards,
Tomolimo

**Comment by nenes82** [comment]
Hello,
here is a video that shows the problem

![bug_display](https://user-images.githubusercontent.com/48098839/53640450-83dc6f00-3c2c-11e9-9ec7-58390dde3c40.gif)


regards
