### ISSUE TITLE
Statistic graph not working

### ISSUE THREAD

**Issue by blublu31** [glpi-project/glpi#16679]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.12

### Bug description

Hello, 

I went to Home/Assistance/Statistics => By ticket => Characteristics - Category
When i choose any report all the stats are at 0 and in debug mode i get quite a lot of errors.

![Capture d'écran 2024-03-01 152027](https://github.com/glpi-project/glpi/assets/59641773/c1098084-1abb-42da-b90a-2a1b120242d4)

### Relevant log output

```shell
php-errors.log
\/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/
[2024-03-01 15:21:38] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in /var/www/glpi/front/stat.graph.php at line 350
  Backtrace :
  public/index.php:82                                require()


sql-errors.log
\/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/ \/
[2024-03-01 15:21:38] glpisqllog.WARNING: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 443
  *** MySQL query warnings:
  SQL: SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(`glpi_tickets`.`solvedate`),'%Y-%m') AS `date_unix`, COUNT(DISTINCT(`glpi_tickets`.`id`)) AS `total_visites` FROM `glpi_tickets` WHERE `glpi_tickets`.`is_deleted` = '0' AND `glpi_tickets`.`itil>
  Warnings:
1292: Truncated incorrect DECIMAL value: ''
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/Stat.php:1556                                  DBmysql->request()
  src/Stat/StatData.php:80                           Stat::constructEntryValues()
  ...tat/Data/Graph/StatDataTicketAverageTime.php:50 Glpi\Stat\StatData->getDataByType()
  front/stat.graph.php:416                           Glpi\Stat\Data\Graph\StatDataTicketAverageTime->__construct()
  public/index.php:82                                require()
  {"user":"5000@FR-PARGLPI01","mem_usage":"0.001\", 3.90Mio)"}
```

### Page URL

https://helpdesk.ad.satys.com/front/stat.graph.php?date1=2023-03-01&date2=2024-03-01&itemtype=Ticket&type=itilcategories_id&champ=0

### Steps To reproduce

With GLPI 10.0.12 
Go to Home/Assistance/Statistics => By ticket => Characteristics - Category
Click on any category graph icon
See the graph being at 0

### Your GLPI setup information

GLPI 10.0.12 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

**Comment by cconard96** [comment]
Please include the complete error. The second error message provided is cut off (see the > at the end of the line).
Please also test with the latest GLPI version.

**Comment by blublu31** [comment]
Hello, i did not notice the > at the end of the line.
We will update GLPI, try with the latest version and i will come back when it's done.

Thanks.

**Comment by blublu31** [comment]
Hello, we updated GLPI in 10.0.14 and i tried again.
I do have the same problem, here are more Screens and the complete SQL error message.

### SQL-errors.log
```shell
[2024-03-20 08:44:45] glpisqllog.WARNING: DBmysql::doQuery() in /var/www/glpi/src/DBmysql.php line 443
  *** MySQL query warnings:
  SQL: SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(`glpi_tickets`.`solvedate`),'%Y-%m') AS `date_unix`, COUNT(DISTINCT(`glpi_tickets`.`id`)) AS `total_visites` FROM `glpi_tickets` WHERE `glpi_tickets`.`is_deleted` = '0' AND `glpi_tickets`.`itilcategories_id` = '' AND `glpi_tickets`.`status` IN ('6', '5') AND ( NOT (`glpi_tickets`.`solvedate` IS NULL AND `glpi_tickets`.`time_to_resolve` IS NULL)) AND ((`glpi_tickets`.`solvedate` >= '2023-03-20') AND (`glpi_tickets`.`solvedate` <= ADDDATE('2024-03-20', INTERVAL 1 DAY))) AND glpi_tickets.solvedate > glpi_tickets.time_to_resolve GROUP BY `date_unix` ORDER BY `glpi_tickets`.`solvedate`
  Warnings:
1292: Truncated incorrect DECIMAL value: ''
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/Stat.php:1556                                  DBmysql->request()
  src/Stat/StatData.php:80                           Stat::constructEntryValues()
  ...tat/Data/Graph/StatDataTicketAverageTime.php:50 Glpi\Stat\StatData->getDataByType()
  front/stat.graph.php:416                           Glpi\Stat\Data\Graph\StatDataTicketAverageTime->__construct()
  public/index.php:82                                require()
  {"user":"5000@FR-PARGLPI01","mem_usage":"0.001\", 2.95Mio)"}
```

###Debug mode error messages
![Err1](https://github.com/glpi-project/glpi/assets/59641773/4c8fb529-8067-4d6b-9cfb-20a6e193e54d)
![Err2](https://github.com/glpi-project/glpi/assets/59641773/97d10dbb-cd41-4781-9754-76dcccbfc9a2)
![Err3](https://github.com/glpi-project/glpi/assets/59641773/4ba8c977-4de0-4d8d-bf12-3723dd3c048b)

**Comment by trasher** [comment]
Please test https://github.com/glpi-project/glpi/pull/16815

**Comment by blublu31** [comment]
Hello,

I tested it and it works, Thank You.

![image](https://github.com/glpi-project/glpi/assets/59641773/fa3f644e-cebb-4060-a727-ad630424d767)

**Comment by trasher** [comment]
:+1: thanks for the feedback!
