### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Lifthraser** [glpi-project/glpi#16697]
Hello

The exact same problem came back when we updated to 10.0.12

Tried to update glpi inventory from 1.6.1 to 1.7 but it didnt change anything.

_Originally posted by @Lifthraser in https://github.com/glpi-project/glpi/issues/13787#issuecomment-1976614303_

**Comment by cedric-anne** [comment]
Please create a new issue, using this form: https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&projects=&template=bug_report.yml

The most details we have about your issue and your GLPI installation, the easier it is for us to investigate.
