### ISSUE TITLE
problem with the automatic collector

### ISSUE THREAD

**Issue by Olfa17** [glpi-project/glpi#16694]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

Hello,

Since GLPI has been upgraded to version 10.0.10, I am experiencing a problem with the automatic collector. It doesn't retrieve emails and gets errors, whereas if I manually click on "retrieve emails now", it works and the user follow-ups are fed into the tickets.
What's more, e-mail notifications work correctly.
The "mailgate" action is configured in CLI with a cron that runs every minute.

**My collector configuration:**
Name 	
helpdesk@zolux.com
Connection errors 45
Active	
Yes
Server	
outlook.office365.com
Connection options	
Oauth Office 365

SSL

NO-TLS

-----

-----

-----

DEBUG
Incoming message folder (optional, often INBOX)	
INBOX
Port (optional)	
Connection string {outlook.office365.com/imap-oauth-1/ssl/notls/debug}INBOX
Identifier	

helpdesk@zolux.com
Accepted e-mail archive folder (optional)	
Archive folder for rejected e-mails (optional)	
Maximum size of files imported by the collector	
10 MiB
Use e-mail date instead of collection date	
Yes
Use "Reply To" as requester (if available)	
No
Add CC users as observers	
No
Collect only unread emails	
Yes
Comments	

I've tried changing the "no-TLS" to "TLS" but it doesn't work because I get a "cannot enable TLS" error message. However, I don't think that's where it's coming from, because in manual mode it works.

I've looked at a lot of forums, and there are a lot of people in this situation, but no solutions have been found.

Do you have any idea where the problem might be coming from?

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.10 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux sv-glpi 5.10.0-26-amd64 #​1 SMP Debian 5.10.197-1 (2023-09-29) x86_64
PHP 7.4.33 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.56 (Debian) (Apache/2.4.56 (Debian) Server at glpi-zolux Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.21-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.21) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
PHP 7.4 official support has ended. An upgrade to a more recent PHP version is recommended.
Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/var/www/html/glpi":
‣ "/var/www/html/glpi/files" ("GLPI_VAR_DIR")
‣ "/var/www/html/glpi/config" ("GLPI_CONFIG_DIR")
You can ignore this suggestion if your web server root directory is "/var/www/html/glpi/public".
PHP directive "session.cookie_secure" should be set to "on" when GLPI can be accessed on HTTPS protocol.
PHP directive "session.cookie_httponly" should be set to "on" to prevent client-side script to access cookie values.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: Phar, zip.
Following extensions are not present: bz2.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/var/www/html/glpi/config"
GLPI_VAR_DIR: "/var/www/html/glpi/files"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/var/www/html/glpi/files"
GLPI_CACHE_DIR: "/var/www/html/glpi/files/_cache"
GLPI_CRON_DIR: "/var/www/html/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/www/html/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/html/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/html/glpi/files/_locales"
GLPI_LOCK_DIR: "/var/www/html/glpi/files/_lock"
GLPI_LOG_DIR: "/var/www/html/glpi/files/_log"
GLPI_PICTURE_DIR: "/var/www/html/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/html/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/www/html/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/www/html/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/www/html/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/html/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/html/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10@05de68add675fb55abaeec10f3a2552085594a16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/var/www/html/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/var/www/html/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'dc01.grp.zolux.local', Port: '389', BaseDN: 'OU=Utilisateurs,DC=grp,DC=zolux,DC=local', Connection filter: none,
		RootDN: 'CN=GLPI_Search,OU=Utilisateurs,DC=grp,DC=zolux,DC=local', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@zolux-com.mail.protection.outlook.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.21.6     State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by Olfa17** [comment]
[sql-errors.log](https://github.com/glpi-project/glpi/files/14481679/sql-errors.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/14481691/php-errors.log)

**Comment by Olfa17** [comment]
Cron task:

*/1 * * * * php /var/www/html/glpi/front/cron.php > /var/log/cron.php.log

cron log:
Uncaught Exception Laminas\Mail\Storage\Exception\RuntimeException: cannot change folder, maybe it does not exist in /var/www/html/glpi/vendor/laminas/laminas-mail/src/>
Uncaught Exception Error: Call to a member function xpath() on null in /var/www/html/glpi/src/RichText/UserMention.php at line 207

**Comment by cedric-anne** [comment]
@Olfa17 

Could you try to enable the mbstring PHP extension on PHP CLI context ? Maybe the error is related to this.

**Comment by Olfa17** [comment]
I've uncommented the "extension=mbstring" line
and restarted the Apache service

I'm waiting to see the result, whether it works or not.

**Comment by Olfa17** [comment]
I've enabled mbstring in /etc/php/8.2/Apache2/php.ini and /etc/php/8.2/cli/php.ini

**Comment by cedric-anne** [comment]
Do you still have the `PHP Warning (2): iconv(): Wrong encoding, conversion from "UTF-8" to "UTF7-IMAP//IGNORE" is not allowed` error? If you still have this error, could you put here the full error trace?

**Comment by cedric-anne** [comment]
By the way, on CLI context, restarting Apache has no effect. Please ensure that `mbstring` extension is correctly loaded by executing `php -m`.

**Comment by Olfa17** [comment]
sv-glpi _log $ php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring' (tried: /usr/lib/php/20220829/mbstring (/usr/lib/php/20220829/mbstring: cannot open shared object file: No such file or directory), /usr/lib/php/20220829/mbstring.so (/usr/lib/php/20220829/mbstring.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
[PHP Modules]
apcu
calendar
Core
ctype
date
dom
exif
FFI
fileinfo
filter
ftp
gettext
hash
iconv
imagick
intl
json
libxml
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
random
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zlib

[Zend Modules]
Zend OPcache

**Comment by cedric-anne** [comment]
It seems that the mbstring extension is not loading. You should fix this issue first (see https://askubuntu.com/a/776366).

**Comment by Olfa17** [comment]
i try but the extension is already installed:

apt-get install php8.2-mbstring
Reading package lists... Done
Build dependency tree... Done
Read status information... Done
The following packages have been installed automatically and are no longer required:
  linux-image-5.10.0-20-amd64 php-apcu-bc php7.4-apcu php7.4-apcu-bc php8.2-apcu php8.2-imagick php8.2-memcache php8.2-phpdbg
Please use "apt autoremove" to remove them.
The following NEW packages will be installed:
  php8.2-mbstring
0 updated, 1 newly installed, 0 to be removed and 51 not updated.
It is necessary to take 441 kB from the archives.
After this operation, 1,223 kB of additional disk space will be used.
Err :1 https://packages.sury.org/php bullseye/main amd64 php8.2-mbstring amd64 8.2.15-1+0~20240120.39+debian11~1.gbp56f296
  404 Not Found [IP : 143.244.56.51 443]
E: Unable to retrieve https://packages.sury.org/php/pool/main/p/php8.2/php8.2-mbstring_8.2.15-1%2b0%7e20240120.39%2bdebian11%7e1.gbp56f296_amd64.deb 404 Not Found [IP : 143.244.56.51 443]
E: Unable to retrieve some archives, maybe you need to run apt-get update or try with --fix-missing?

**Comment by Olfa17** [comment]
phpenmod mbstring
WARNING: Module mbstring ini file doesn't exist under /etc/php/8.3/mods-available
WARNING: Module mbstring ini file doesn't exist under /etc/php/8.3/mods-available
WARNING: Module mbstring ini file doesn't exist under /etc/php/8.2/mods-available
WARNING: Module mbstring ini file doesn't exist under /etc/php/8.2/mods-available
WARNING: Module mbstring ini file doesn't exist under /etc/php/8.2/mods-available

**Comment by cedric-anne** [comment]
The installation log displays an error, it means that the `mbstring` extension was not installed for your PHP 8.2.

Also, in the initial description of your issue, you mentioned `PHP 7.4.33 apache2handler`. Please ensure that you installed the `mbstring` for the correct PHP version (check with `php -v`).

**Comment by cedric-anne** [comment]
Please run `apt-get update && apt-get install php8.2-mbstring`.

**Comment by Olfa17** [comment]
Same error

sv-glpi / $ apt-get update && apt-get install php8.2-mbstring
Reached :1 http://security.debian.org/debian-security bullseye-security InRelease
Reached :2 http://deb.debian.org/debian bullseye InRelease
Reached :3 http://deb.debian.org/debian bullseye-updates InRelease
Received :4 https://packages.sury.org/php bullseye InRelease [7,551 B]
Err :4 https://packages.sury.org/php bullseye InRelease
  The following signatures are invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
7,551 o received in 1s (7,270 o/s)
Reading packet lists... Fact
W: An error occurred while checking the signature. The repository is not updated and previous index files will be used. GPG error: https://packages.sury.org/php bullseye InRelease: The following signatures are invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
W: Unable to recover https://packages.sury.org/php/dists/bullseye/InRelease The following signatures are invalid: EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
W: Download of some index files failed, they were ignored, or old ones were used instead.
Reading package lists... Done
Build dependency tree... Done
Read status information... Done
The following packages have been installed automatically and are no longer required:
  linux-image-

**Comment by cedric-anne** [comment]
https://www.faqforge.com/linux/solved-the-following-signatures-were-invalid-expkeysig-b188e2b695bd4743-deb-sury-org-automatic-signing-key/

**Comment by Olfa17** [comment]
apt-key adv --fetch-keys https://packages.sury.org/php/apt.gpg
E: gnupg, gnupg2 and gnupg1 do not seem to be installed, but one of them is required for this operation


sv-glpi / $ apt-get install -y gnupg2 gnupg gnupg1
Reading package lists... Done
Build dependency tree... Done
Read status information... Done
The following packages have been installed automatically and are no longer required:
  linux-image-5.10.0-20-amd64 php-apcu-bc php7.4-apcu php7.4-apcu-bc php8.2-apcu php8.2-imagick php8.2-memcache php8.2-phpdbg
Please use "apt autoremove" to remove them.
The following additional packages will be installed:
  dirmngr gnupg-l10n gnupg-utils gnupg1-l10n gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libnpth0 pinentry-curses
Suggested packages :
  dbus-user-session pinentry-gnome3 tor parcimonie xloadimage libpcsclite1 xloadimage | imagemagick | eog scdaemon pinentry-doc
The following NEW packages will be installed:
  dirmngr gnupg gnupg-l10n gnupg-utils gnupg1 gnupg1-l10n gnupg2 gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libassuan0 libksba8 libnpth0 pinentry-curses
0 updated, 17 newly installed, 0 to be removed and 51 not updated.
It is necessary to take 9,254 kB from the archives.
After this operation, 21.1 MB of additional disk space will be used.
Received :1 http://deb.debian.org/debian bullseye/main amd64 libassuan0 amd64 2.5.3-7.1 [50.5 kB]
Receiving :2 http://deb.debian.org/debian bullseye/main amd64 gpgconf amd64 2.2.27-2+deb11u2 [548 kB]
Received :3 http://deb.debian.org/debian bullseye/main amd64 lib


apt-key adv --fetch-keys https://packages.sury.org/php/apt.gpg
Attention : apt-key est obsolète. Gérer les fichiers de trousseau dans trusted.gpg.d à la place (voir apt-key(8)).
Exécution : /tmp/apt-key-gpghome.QjddAjXg87/gpg.1.sh --fetch-keys https://packages.sury.org/php/apt.gpg
gpg : requête de la clef sur " https://packages.sury.org/php/apt.gpg "
gpg : clef B188E2B695BD4743 : clef publique " DEB.SURY.ORG Automatic Signing Key <deb@sury.org> " importée
gpg :       Quantité totale traitée : 1
gpg : importées : 1



apt-get update
Atteint :1 http://deb.debian.org/debian bullseye InRelease
Atteint :2 http://security.debian.org/debian-security bullseye-security InRelease
Atteint :3 http://deb.debian.org/debian bullseye-updates InRelease
Réception de :4 https://packages.sury.org/php bullseye InRelease [7 551 B]
Err :4 https://packages.sury.org/php bullseye InRelease
  Les signatures suivantes ne sont pas valables : EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
Lecture des listes de paquets... Fait
W: Une erreur s'est produite lors du contrôle de la signature. Le dépôt n'est pas mis à jour et les fichiers d'index précédents seront utilisés. Erreur de GPG : https://packages.sury.org/php bullseye InRelease : Les signatures suivantes ne sont pas valables : EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
W: Impossible de récupérer https://packages.sury.org/php/dists/bullseye/InRelease  Les signatures suivantes ne sont pas valables : EXPKEYSIG B188E2B695BD4743 DEB.SURY.ORG Automatic Signing Key <deb@sury.org>
W: Le téléchargement de quelques fichiers d'index a échoué, ils ont été ignorés, ou les anciens ont été utilisés à la place.

**Comment by trasher** [comment]
You have system issues that are out of the scope of GLPI community support. Please make sure mbstrig ext is properly installed, and then try if that solves your GLPI issue.

**Comment by Olfa17** [comment]
I solved the repository problem with the apt-get update command.

Here is the result of the command:
apt-get install php8.2-mbstring
Reading package lists... Done
Build dependency tree... Done
Read status information... Done
The following packages have been installed automatically and are no longer required:
  linux-image-5.10.0-20-amd64 php-apcu-bc php7.4-apcu php7.4-apcu-bc php8.2-apcu php8.2-imagick php8.2-memcache php8.2-phpdbg
Please use "apt autoremove" to remove them.
The following additional packages will be installed:
  libapache2-mod-php8.2 php8.2-cli php8.2-common php8.2-intl php8.2-mysql php8.2-opcache php8.2-phpdbg php8.2-readline php8.2-xml
The following NEW packages will be installed:
  php8.2-mbstring
The following packages will be updated:
  libapache2-mod-php8.2 php8.2-cli php8.2-common php8.2-intl php8.2-mysql php8.2-opcache php8.2-phpdbg php8.2-readline php8.2-xml
9 updated, 1 newly installed, 0 to be removed and 50 not updated.
It is necessary to take 6,930 kB from the archives.
After this operation, an additional 1,223 kB of disk space will be used.
Would you like to continue? [Y/n] Y
Received :1 https://packages.sury.org/php bullseye/main amd64 php8.2-xml amd64 8.2.16-1+0~20240216.40+debian11~1.gbp6cbea3 [111 kB]
Received :2 https://packages.sury.org/php bullseye/main amd64 php8.2-readline amd64 8.2.16-1+0~20240216.40+debian11~1.gbp6cbea3 [12,6 kB]
Receiving :3 https

**Comment by Olfa17** [comment]
@cedric-anne 
I've checked the collector and there's no longer any error message.
So I tried adding a follow-up to a ticket by sending an e-mail to our helpdesk e-mail address. The follow-up was added 1min after sending.

Thanks for your feedback. The problem was on mbstring

**Comment by cedric-anne** [comment]
The extension will be marked as mandatory in GLPI 11.0 to prevent this kind of issues, see #16696.
