### ISSUE TITLE
Notifications from automatic notifications are blacklisted

### ISSUE THREAD

**Issue by fgendorf** [glpi-project/glpi#16711]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

Hi, sometimes we want automatic notifications turn into ticket, especially expiration licenses and contracts notifications, but we noted that latest version  of GLPI implemented this:

```
if ($this->isMessageSentByGlpi($message)) {
           // Message was sent by current instance of GLPI.
           // Message is blacklisted to avoid infinite loop (where GLPI creates a ticket from its own notification).
            $tkt['_blacklisted'] = true;
            return $tkt;
        }
        
```

Now the notifications from GLPI cannot be turned to ticket automatically...

### Steps To reproduce

1 configure an automatic notification like "[Contract End Periodicity]" to send e-mail e-mail to Receivers MailCollector
2 wait notification execute
3 Click on "Get Email Tickets Now" and see 
![image](https://github.com/glpi-project/glpi/assets/15034336/82d6bc5c-7879-4920-9710-c0795683628a)

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.12 ( => /home/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi2 4.18.0-425.19.2.el8_7.x86_64 #​1 SMP Tue Apr 4 05:30:47 EDT 2023 x86_64
PHP 8.1.27 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, yaml, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" disable_functions="" 
Software: Apache/2.4.37 (AlmaLinux) OpenSSL/1.1.1k mod_perl/2.0.12 Perl/v5.26.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.36
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@10.0.0.26/glpi
	Host info: 10.0.0.26 via TCP/IP
	
PHP version (8.1.27) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.36) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/g_files/_cache has been validated.
Write access to /home/g_files/_cron has been validated.
Write access to /home/g_files has been validated.
Write access to /home/g_files/_dumps has been validated.
Write access to /home/g_files/_graphs has been validated.
Write access to /home/g_files/_lock has been validated.
Write access to /home/g_files/_pictures has been validated.
Write access to /home/g_files/_plugins has been validated.
Write access to /home/g_files/_rss has been validated.
Write access to /home/g_files/_sessions has been validated.
Write access to /home/g_files/_tmp has been validated.
Write access to /home/g_files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/glpi"
GLPI_CONFIG_DIR: "/home/g_files/config"
GLPI_VAR_DIR: "/home/g_files"
GLPI_MARKETPLACE_DIR: "/home/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/home/g_files"
GLPI_CACHE_DIR: "/home/g_files/_cache"
GLPI_CRON_DIR: "/home/g_files/_cron"
GLPI_DUMP_DIR: "/home/g_files/_dumps"
GLPI_GRAPH_DIR: "/home/g_files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/g_files/_locales"
GLPI_LOCK_DIR: "/home/g_files/_lock"
GLPI_LOG_DIR: "/home/g_files/_log"
GLPI_PICTURE_DIR: "/home/g_files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/g_files/_plugins"
GLPI_RSS_DIR: "/home/g_files/_rss"
GLPI_SESSION_DIR: "/home/g_files/_sessions"
GLPI_TMP_DIR: "/home/g_files/_tmp"
GLPI_UPLOAD_DIR: "/home/g_files/_uploads"
GLPI_INVENTORY_DIR: "/home/g_files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/home/glpi/locales"
GLPI_VERSION: "10.0.12"
GLPI_SCHEMA_VERSION: "10.0.12@b902ef5f5da967c1a9d0826ee8a7dce07d57cf3d"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/home/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/home/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/home/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/home/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/glpi/vendor/sabre/http/lib)
sabre/uri in (/home/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/home/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/home/glpi/vendor/symfony/console)
scssphp/scssphp in (/home/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/home/glpi/vendor/ramsey/uuid/src)
psr/log in (/home/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/glpi/vendor/psr/simple-cache/src)
psr/cache in (/home/glpi/vendor/psr/cache/src)
league/csv in (/home/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/home/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/glpi/vendor/symfony/cache)
html2text/html2text in (/home/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/home/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/glpi/vendor/symfony/dom-crawler)
twig/twig in (/home/glpi/vendor/twig/twig/src)
twig/string-extra in (/home/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/home/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/home/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/home/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldap.fln.esss.com.br', Port: '389', BaseDN: 'ou=ESSS,dc=esss,dc=com,dc=br', Connection filter:
		'(&(departmentnumber=*)(objectclass=CourierMailAccount)(!(status=*nativo)))', RootDN: none, Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@10.0.0.35)

</pre></details><details><summary>Plugins list</summary><pre> 
	accounts             Name: Accounts                       Version: 3.0.4      State: Not installed                           
		Install Method: Marketplace
	actualtime           Name: ActualTime                     Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Additional Fields              Version: 1.21.8     State: Enabled                                 
		Install Method: Marketplace
	behaviors            Name: Behaviours                     Version: 2.7.2      State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data injection                 Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Marketplace
	fpsoftware           Name: FP Software                    Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Marketplace
	addressing           Name: IP Adressing                   Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	mailanalyzer         Name: Mail Analyzer                  Version: 3.1.1      State: Enabled                                 
		Install Method: Manual
	mailbehaviours       Name: Mail Behaviours                Version: 2.0.0      State: Enabled                                 
		Install Method: Manual
	mfa                  Name: MFA                            Version: 1.0.2      State: Enabled                                 
		Install Method: Marketplace
	moreticket           Name: More ticket                    Version: 1.7.3      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Enabled                                 
		Install Method: Marketplace
	reports              Name: Reports                        Version: 1.16.0     State: Enabled                                 
		Install Method: Manual
	manufacturersimports Name: Suppliers imports              Version: 3.0.5      State: Not installed                           
		Install Method: Marketplace
	tag                  Name: Tag Management                 Version: 2.11.7     State: Enabled                                 
		Install Method: Marketplace
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Enabled                                 
		Install Method: Marketplace
	ticketcleaner        Name: Ticket Cleaner                 Version: 4.0.2      State: Not installed                           
		Install Method: Manual
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Enabled                                 
		Install Method: Marketplace
	webapplications      Name: Web applications               Version: 4.0.1      State: Enabled                                 
		Install Method: Marketplace
	webhook              Name: Webhooks                       Version: 1.0.18     State: Enabled                                 
		Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Hi @fgendorf, 

This feature will be restored if #17197 is validated.
