### ISSUE TITLE
Uncaught Exception TypeError: Unsupported operand types: int + string in /var/www/html/glpi/src/LevelAgreement.php at line 855

### ISSUE THREAD

**Issue by berils** [glpi-project/glpi#16722]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

Whenever user is trying to create ticket with selected SLA plan/time , error is producted. (Only in debug mode you can see error code)
Error showed in debug mode:
Uncaught Exception TypeError: Unsupported operand types: int + string in /var/www/html/glpi/src/LevelAgreement.php at line 855

### Relevant log output

```shell
glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Unsupported operand types: int + string in /var/www/html/glpi/src/LevelAgreement.php at line 855
                                                                                                                   │  Backtrace :
                                                                                                                   │  src/Ticket.php:449                                 LevelAgreement->computeDate()
                                                                                                                   │  src/Ticket.php:1428                                Ticket->getDatasToAddSLA()
                                                                                                                   │  src/Ticket.php:2027                                Ticket->slaAffect()
                                                                                                                   │  src/CommonDBTM.php:1297                            Ticket->prepareInputForAdd()
                                                                                                                   │  front/ticket.form.php:80                           CommonDBTM->add()
                                                                                                                   │  public/index.php:82                                require()
```

### Steps To reproduce

Ticket template: Time to resolve- required
Create ticket with SLA/OLA plan selected.

### Your GLPI setup information

yesturday upgraded from 10.0.10 to 10.0.12

### Anything else?

This is pretty important bug, as support can't create tickets as expected.
Workaround- Turn off mandatory field TTR. 
When TTR is empty, ticket is created as expected.

**Comment by cedric-anne** [comment]
Fixed by #16496.
