### ISSUE TITLE
Deleting computer equipment permanently

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi#16744]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

I'm not sure if it's a bug or if it really should be like this, but when we are deleting an item from the GLPI recycle bin, for example a computer, 2 ways of deletion are always presented:
- Permanently delete but keep devices
- Permanently delete and remove devices

The issue is that I have always noticed that when permanent deletion is chosen asking to remove the devices together, some items are not excluded, leaving several inventory requirements that will no longer exist behind, such as: Software, monitor and devices

I believe that this behavior is incorrect and that everything related to that equipment should be removed.

I know that there is an automatic action task that cleans software and software versions that are no longer linked to any computer, this partially resolves the garbage left by a deleted computer, for example.

But today there is no automatic task that deletes unlinked orphan devices that were in automatic inventory, I believe that perhaps this is the way to go, to leave them in the GLPI as optional, or to clean them when deleting the equipment.

**Comment by cconard96** [comment]
By "devices" it refers to components, not connected assets like monitors/printers or software (except software installations which are child items on the computer itself).

**Comment by trasher** [comment]
As Curtis said, that's not the same. I'm pretty sure GLPI cannot assert a linked equipment can be deleted along with its parent; it has no way to know if it's relevant or not. Only link between them can be "safely" removed.

I guess the better solution would be to rely on a cleaning crontask action; you can propose that on suggestion website, since this is a feature request rather than a bug.

Thank you.
