### ISSUE TITLE
Error on notifications - 1292: Truncated incorrect DOUBLE value: 'N/A'

### ISSUE THREAD

**Issue by SilvaFernando** [glpi-project/glpi#16743]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

Error on notifications.

Hi team.

When my GLPI sends a notifications on sql-errors.logI have this output:
![image](https://github.com/glpi-project/glpi/assets/53239752/2b86705e-b6ad-4e29-9a52-01203cd7719a)

### Relevant log output

```shell
[2024-03-11 10:53:56] glpisqllog.WARNING: DBmysql::query() in /usr/share/glpi/src/DBmysql.php line 419
  *** MySQL query warnings:
  SQL: SELECT * FROM `glpi_notificationtemplatetranslations` WHERE `notificationtemplates_id` = 'N/A' AND `language` IN ('pt_BR', '') ORDER BY `language` DESC LIMIT 1
  Warnings:
1292: Truncated incorrect DOUBLE value: 'N/A'
  Backtrace :
  src/DBmysqlIterator.php:112
  src/DBmysql.php:1078                               DBmysqlIterator->execute()
  src/NotificationTemplate.php:572                   DBmysql->request()
  src/NotificationTemplate.php:284                   NotificationTemplate->getByLanguage()
  src/NotificationEventAbstract.php:122              NotificationTemplate->getTemplateByLanguage()
  src/NotificationEvent.php:187                      NotificationEventAbstract::raise()
  src/CommonITILActor.php:459                        NotificationEvent::raiseEvent()
  src/Ticket_User.php:59                             CommonITILActor->post_addItem()
  src/CommonDBTM.php:1324                            Ticket_User->post_addItem()
  src/CommonITILObject.php:1813                      CommonDBTM->add()
  src/Ticket.php:1338                                CommonITILObject->prepareInputForUpdate()
  src/CommonDBTM.php:1589                            Ticket->prepareInputForUpdate()
  front/ticket.form.php:204                          CommonDBTM->update()
  public/index.php:82                                require()
  {"user":"156026@ip-172-33-2-135.ec2.internal"}
^C
```

### Page URL

127.0.0.1

**Comment by cconard96** [comment]
Please check if you have any notifications that are linked to invalid/deleted notification templates. If you have access to the DB, this query should be sufficient to find the IDs of the notifications linked to non-existant templates:

```sql
SELECT `notifications_id` FROM `glpi_notifications_notificationtemplates` LEFT OUTER JOIN `glpi_notificationtemplates` ON `glpi_notificationtemplates`.`id` = `glpi_notifications_notificationtemplates`.`notificationtemplates_id` WHERE `glpi_notificationtemplates`.`id` IS NULL;
```

**Comment by berils** [comment]
> Please check if you have any notifications that are linked to invalid/deleted notification templates. If you have access to the DB, this query should be sufficient to find the IDs of the notifications linked to non-existant templates:
> 
> ```sql
> SELECT `notifications_id` FROM `glpi_notifications_notificationtemplates` LEFT OUTER JOIN `glpi_notificationtemplates` ON `glpi_notificationtemplates`.`id` = `glpi_notifications_notificationtemplates`.`notificationtemplates_id` WHERE `glpi_notificationtemplates`.`id` IS NULL;
> ```

Hmm, getting same error, but after provided query, zero results.
MySQL returned an empty result set (i.e. zero rows). (Query took 0.0013 seconds.)

**Comment by berils** [comment]
Im getting similar issue with notification, but idk if its releated to this exact issue.

`glpisqllog.WARNING: DBmysql::doQuery() in /var/www/html/glpi/src/DBmysql.php line 443
  *** MySQL query warnings:
  SQL: SELECT `glpi_notificationtemplates`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_notificationtemplates` WHERE `glpi_notificationtemplates`.`id` = 'N/A'
  Warnings:
1292: Truncated incorrect DOUBLE value: 'N/A'
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/Dropdown.php:544                               DBmysql->request()
  src/NotificationTarget.php:1641                    Dropdown::getDropdownName()
  src/NotificationTarget.php:1657                    NotificationTarget::showForGroup()
  src/CommonGLPI.php:694                             NotificationTarget::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()
  public/index.php:82                                require()
  {"user":"104@servicedesk-p1","mem_usage":"0.002\", 3.82Mio)"}
`

**Comment by SilvaFernando** [comment]
I've found seven registries on database with this select, but this notifications is disabled.
