### ISSUE TITLE
[GLPI 10 Bugfixes] Display Delete permanently without purge rights

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#16740]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

[GLPI 10 Bugfixes]

### Bug description

Profile : No right to purge tickets

But in the ticket form, the button is displayed : 

![image](https://github.com/glpi-project/glpi/assets/13178158/16ea7494-fe6f-426f-b2a3-6b27e4a421a0)

**Comment by trasher** [comment]
I've just checked with up-to-date 10.0/bugfixes branch, I do not reproduce (purge button is not displayed).

Either this has been fixed since, or we miss information to reproduce.
