### ISSUE TITLE
Content-Range header is not provided anymore on latest revisions of GLPI

### ISSUE THREAD

**Issue by newls** [glpi-project/glpi#1675]
Using one of the machines I work on, I realised that my local glpi repository was not positionned at HEAD.
Doing a git pull, I realised that the webapp I'm writing using Angular.JS don't run anymore with the latest "`master`" glpi.

My local  `master` branch was pointing at 47e80d2f97273552d86d45a99625e5eef5f353ef before I do the `git pull`, now `master` is at `HEAD` and glpi is no more providing Content-Range on some specific requests.

Here is one of the HTTP request that is not providing Content-Range anymore

```http
GET /apirest.php/Ticket/183274/TicketTask?range=0-0 HTTP/1.1
Host: localhost:8000
```
We cannot see `Content-Range` in the response headers here :

```http
HTTP/1.1 200 OK
Host: localhost:8000
Connection: close
X-Powered-By: PHP/5.6.11-1ubuntu3.4
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: content-type, content-range, accept-range
Pragma: no-cache
Accept-Range: TicketTask 1000
Content-Type: application/json; charset=UTF-8
Cache-Control: no-store, no-cache, must-revalidate
Expires: Mon, 26 Jul 1997 05:00:00 GMT
```

Now, let's checkout `47e80d2f97273552d86d45a99625e5eef5f353ef`.
Now, the response contains `Content-Range` after "replaying" the same request.

```http
HTTP/1.1 200 OK
Host: localhost:8000
Connection: close
X-Powered-By: PHP/5.6.11-1ubuntu3.4
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: content-type, content-range, accept-range
Pragma: no-cache
Content-Range: 0--1/0
Accept-Range: TicketTask 1000
Content-Type: application/json; charset=UTF-8
Cache-Control: no-store, no-cache, must-revalidate
Expires: Mon, 26 Jul 1997 05:00:00 GMT
```

I don't know why the availability of this header regressed since October, but I hope someone will be able to give me some input !

Have a nice day.

**Note 1:** [Here is the list of changes from this commit](https://github.com/glpi-project/glpi/compare/47e80d2f97273552d86d45a99625e5eef5f353ef...master)  
**Note 2:** range=0-0 is a convention discussed with @orthagh to get the number of items in `/Ticket/183274/TicketTask` -per example-, it works by reading the `Content-Range` and `Accept-Range` headers)

**Comment by orthagh** [comment]
Hello @newls 

Here is the corresponding issues:
* #1570 
* #1259 

I must go now, but we could discuss later directly (monday ?)

**Comment by btry** [comment]
Hi

When you submit a search to t he API and there are results you can choose a few of the results from **0** to **(totalcount -1)**

However if the search does not have any result, then the Content-Range was **0-0/0** or **0--1/0**  depending on the way to compute it.

If totalcount == 0 and Content-Range says **0-0/0** their is a problem : 0-0 means there is **1 item**, and this is opposed to totalcount being **0** and also the last zero in the header.

if totalcount == 0 and Content-Range says **0--1/0** (which is actually *0 dash (minus 1) slash 0* this is even worse : the maximum is less than the minimum, there are 2 items and the last 0 in the header says there is no item.

From these observations I found better to **not** send Content-Range when a search does not returns any result. I submitted a PR for that and it has been accepted. I thought this is an acceptable way to address these inconsistencies.

**Comment by newls** [comment]
@orthagh APropos de Monday: Sure !

**Comment by newls** [comment]
@btry :

0-1-0-1-0-1 = -3 :)

**Comment by newls** [comment]
So, I thought there was going to be some more activity on this thread/subject/issue/ticket.

i'm scared that the `range selection functionnality` of this `API search` is couter intuitive this way isn't it ?
Or it is just a personal feeling IDK

**Comment by newls** [comment]
I close this Issue due to inactivity.

**Comment by btry** [comment]
Currently, the API does not sends a Content-Range header if the result is empty. 

If there is at least 1 result, then the Content-Range is sent and contains consistent data.

**Comment by newls** [comment]
Thanks for this answer, I followed what happened here : https://github.com/glpi-project/glpi/issues/1259
