### ISSUE TITLE
automation scheduler issues (CLI) after restoring system snapshot

### ISSUE THREAD

**Issue by plpamos** [glpi-project/glpi#16754]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.12

### Bug description

This is not an error in the strict sense, but maybe it is worth taking care of it somehow.
For example, after recreating a snapshot - some of the automation "hangs" because their next launch time (in the CLI model) is lower than the current system time.
It rarely happens... restoring a snapshot taken e.g. 30 minutes earlier... but it still happens... especially if something went wrong with the update.
It requires a review of the entire "scheduler" and manual intervention.
Consider whether it is worth handling it.

### Steps To reproduce

make system snapshot (VmWare etc.)
restore after an hour
jobs (run by  CLI) which should run int the menatime "hangs" and needs "manual" restart because their "next time run" is less then actual system time

**Comment by plpamos** [comment]
UPDATE:  it seems that even a temporary interruption in the operation of the application - e.g. during updating... longer than the time gap of the scheduled scheduler requires manual intervention..
This especially applies to the tasks of receiving and sending mail/notifications

**Comment by cedric-anne** [comment]
What is the state of the tasks that you considered as hung ? The `Next run` is just an indication of the timestamp on which the task will be considered as "to be executed". Even if it is be far in the past, the task would still be executed if its state is `Scheduled`.

**Comment by plpamos** [comment]
maybe it was in coincidence with GLPI upgrade. 
Can't reproduce now.. I will observe it next time doing upgrade.
Sorry for bothering.

**Comment by plpamos** [comment]
Can't reproduce any more.
will wait for nex upgrade. Porbably there is a coincidence with scheduler and database upgrade
