### ISSUE TITLE
search field on login screen not working

### ISSUE THREAD

**Issue by vinilamelas** [glpi-project/glpi#16758]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.12

### Bug description

ldap source search field does not work, it just keeps loading

![image](https://github.com/glpi-project/glpi/assets/51828518/26b5282c-269d-4999-a35f-a5cf1f6acc52)

### Steps To reproduce

1 Go to the login screen
2 Click the Login Source selection list
3 Enter any word, you will just be looking for

**Comment by trasher** [comment]
Anything in logs?

**Comment by vinilamelas** [comment]
Hello,

I did the research test and followed the logs within GLPI Linux and it didn't show any errors.

**Comment by trasher** [comment]
What about javascript errors in borwser dev tools?

**Comment by cedric-anne** [comment]
I confirm the issue.

![image](https://github.com/glpi-project/glpi/assets/33253653/a0f74c08-481b-486f-817d-a4f20e135b35)

**Comment by vinilamelas** [comment]
Hello.

The error shown follows, it is the same as the Cedric-anne

![image](https://github.com/glpi-project/glpi/assets/51828518/cca94a71-c960-49c0-aab6-e6933134538a)
