### ISSUE TITLE
List "attribué à " empty since 10.0.13 version

### ISSUE THREAD

**Issue by oph85** [glpi-project/glpi#16769]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.13

### Bug description

List "attribué à " empty since 10.0.13 version (it worked on 10.0.12)
![Capture d'écran 2024-03-14 084038](https://github.com/glpi-project/glpi/assets/19650392/689cf6d1-b52a-479a-946e-9c5935556542)

### Steps To reproduce

Go to ticket page (menu help / tickets)
On the right of the page clic on "attribué à" field.
The field is empty (see screenshot above)

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.13 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Windows NT SRVGLPI10 10.0 build 17763 (Windows Server 2019) AMD64
PHP 8.1.5 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, sodium, standard, tokenizer, xml, xmlreader, xmlwriter, zip,
	zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" disable_functions="" 
Software: Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.5 (Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.5 Server at srvglpi10
	Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
Server Software: mariadb.org binary distribution
	Server Version: 10.4.24-MariaDB
	Server SQL Mode: NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
PHP version (8.1.5) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.4.24) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to C:\xampp\htdocs\glpi/files/_cache has been validated.
Write access to C:\xampp\htdocs\glpi/files/_cron has been validated.
Write access to C:\xampp\htdocs\glpi/files has been validated.
Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated.
Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated.
Write access to C:\xampp\htdocs\glpi/files/_lock has been validated.
Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated.
Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated.
Write access to C:\xampp\htdocs\glpi/files/_rss has been validated.
Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated.
Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated.
Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "C:\xampp\htdocs\glpi":
‣ "C:\xampp\htdocs\glpi/files" ("GLPI_VAR_DIR")
‣ "C:\xampp\htdocs\glpi/files/_cache" ("GLPI_CACHE_DIR")
‣ "C:\xampp\htdocs\glpi/files/_cron" ("GLPI_CRON_DIR")
‣ "C:\xampp\htdocs\glpi/files" ("GLPI_DOC_DIR")
‣ "C:\xampp\htdocs\glpi/files/_dumps" ("GLPI_DUMP_DIR")
‣ "C:\xampp\htdocs\glpi/files/_graphs" ("GLPI_GRAPH_DIR")
‣ "C:\xampp\htdocs\glpi/files/_lock" ("GLPI_LOCK_DIR")
‣ "C:\xampp\htdocs\glpi/files/_log" ("GLPI_LOG_DIR")
‣ "C:\xampp\htdocs\glpi/files/_pictures" ("GLPI_PICTURE_DIR")
‣ "C:\xampp\htdocs\glpi/files/_plugins" ("GLPI_PLUGIN_DOC_DIR")
‣ "C:\xampp\htdocs\glpi/files/_rss" ("GLPI_RSS_DIR")
‣ "C:\xampp\htdocs\glpi/files/_sessions" ("GLPI_SESSION_DIR")
‣ "C:\xampp\htdocs\glpi/files/_tmp" ("GLPI_TMP_DIR")
‣ "C:\xampp\htdocs\glpi/files/_uploads" ("GLPI_UPLOAD_DIR")
You can ignore this suggestion if your web server root directory is "C:\xampp\htdocs\glpi\public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to C:\xampp\htdocs\glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "C:\\xampp\\htdocs\\glpi"
GLPI_CONFIG_DIR: "C:\\xampp\\htdocs\\glpi/config"
GLPI_VAR_DIR: "C:\\xampp\\htdocs\\glpi/files"
GLPI_MARKETPLACE_DIR: "C:\\xampp\\htdocs\\glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "C:\\xampp\\htdocs\\glpi/files"
GLPI_CACHE_DIR: "C:\\xampp\\htdocs\\glpi/files/_cache"
GLPI_CRON_DIR: "C:\\xampp\\htdocs\\glpi/files/_cron"
GLPI_DUMP_DIR: "C:\\xampp\\htdocs\\glpi/files/_dumps"
GLPI_GRAPH_DIR: "C:\\xampp\\htdocs\\glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "C:\\xampp\\htdocs\\glpi/files/_locales"
GLPI_LOCK_DIR: "C:\\xampp\\htdocs\\glpi/files/_lock"
GLPI_LOG_DIR: "C:\\xampp\\htdocs\\glpi/files/_log"
GLPI_PICTURE_DIR: "C:\\xampp\\htdocs\\glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "C:\\xampp\\htdocs\\glpi/files/_plugins"
GLPI_RSS_DIR: "C:\\xampp\\htdocs\\glpi/files/_rss"
GLPI_SESSION_DIR: "C:\\xampp\\htdocs\\glpi/files/_sessions"
GLPI_TMP_DIR: "C:\\xampp\\htdocs\\glpi/files/_tmp"
GLPI_UPLOAD_DIR: "C:\\xampp\\htdocs\\glpi/files/_uploads"
GLPI_INVENTORY_DIR: "C:\\xampp\\htdocs\\glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "C:\\xampp\\htdocs\\glpi/locales"
GLPI_VERSION: "10.0.13"
GLPI_SCHEMA_VERSION: "10.0.13@8f13530f7cf0fb07add30ae20013f0374956795b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed)
phpmailer/phpmailer version 6.8.0 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.8 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.6.2 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/dav in (C:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV)
sabre/http in (C:\xampp\htdocs\glpi\vendor\sabre\http\lib)
sabre/uri in (C:\xampp\htdocs\glpi\vendor\sabre\uri\lib)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
laminas/laminas-i18n in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src)
laminas/laminas-servicemanager in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-servicemanager\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
donatj/phpuseragentparser in (C:\xampp\htdocs\glpi\vendor\donatj\phpuseragentparser\src\UserAgent)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
scssphp/scssphp in (C:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src)
laminas/laminas-mail in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol)
laminas/laminas-mime in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src)
rlanvin/php-rrule in (C:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src)
ramsey/uuid in (C:\xampp\htdocs\glpi\vendor\ramsey\uuid\src)
psr/log in (C:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log)
psr/simple-cache in (C:\xampp\htdocs\glpi\vendor\psr\simple-cache\src)
psr/cache in (C:\xampp\htdocs\glpi\vendor\psr\cache\src)
league/csv in (C:\xampp\htdocs\glpi\vendor\league\csv\src)
mexitek/phpcolors in (C:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors)
guzzlehttp/guzzle in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src)
guzzlehttp/psr7 in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src)
glpi-project/inventory_format in (C:\xampp\htdocs\glpi\vendor\glpi-project\inventory_format\lib\php)
wapmorgan/unified-archive in (C:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src)
paragonie/sodium_compat in (C:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)
symfony/cache in (C:\xampp\htdocs\glpi\vendor\symfony\cache)
html2text/html2text in (C:\xampp\htdocs\glpi\vendor\html2text\html2text\src)
symfony/css-selector in (C:\xampp\htdocs\glpi\vendor\symfony\css-selector)
symfony/dom-crawler in (C:\xampp\htdocs\glpi\vendor\symfony\dom-crawler)
twig/twig in (C:\xampp\htdocs\glpi\vendor\twig\twig\src)
twig/string-extra in (C:\xampp\htdocs\glpi\vendor\twig\string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (C:\xampp\htdocs\glpi\vendor\symfony\polyfill-php82)
league/oauth2-client in (C:\xampp\htdocs\glpi\vendor\league\oauth2-client\src\Provider)
league/oauth2-google in (C:\xampp\htdocs\glpi\vendor\league\oauth2-google\src\Provider)
thenetworg/oauth2-azure in (C:\xampp\htdocs\glpi\vendor\thenetworg\oauth2-azure\src\Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '172.17.1.1', Port: '389', BaseDN: 'DC=ophlm-vendee,DC=fr', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'adjoin', Use TLS:
		none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@mail.vendeehabitat.fr)

</pre></details><details><summary>Plugins list</summary><pre> 
	gantt                Name: gantt                          Version: 1.0.4      State: Installed / not activated               
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Installed / not activated               
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

**Comment by cedric-anne** [comment]
Fixed by #16770.

**Comment by cedric-anne** [comment]
Duplicates #16768
