### ISSUE TITLE
Impossible to assign a ticket to somebody since 10.0.13

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#16768]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.13

### Bug description

Since upgrade, it's impossible to assign ticket to somebody, there is no result in dropdown.
It still possible to assign ticket to itself since it does not use dropdown

### Relevant log output

```shell
(See attached screenshot)

[2024-03-14 08:44:09] glpiphplog.WARNING:   *** PHP Warning (2): Trying to access array offset on null in E:\GLPI\src\Dropdown.php at line 4235
  Backtrace :
  ajax\actors.php:46                                 Dropdown::getDropdownActors()
  public\index.php:82                                require()
  
[2024-03-14 08:44:09] glpiphplog.WARNING:   *** PHP Warning (2): foreach() argument must be of type array|object, null given in E:\GLPI\src\Dropdown.php at line 4235
  Backtrace :
  ajax\actors.php:46                                 Dropdown::getDropdownActors()
  public\index.php:82                                require()
```

### Page URL

front/ticket.form.php?id=XXXX

### Your GLPI setup information

#REDACTED#

### Anything else?

![image](https://github.com/glpi-project/glpi/assets/1759156/38078601-4c68-4fe9-90e6-539ebf09b275)

**Comment by cedric-anne** [comment]
Fixed by #16770.
