### ISSUE TITLE
Users can't create ticket, need to fill technician field not displayed

### ISSUE THREAD

**Issue by JonioDiPonio** [glpi-project/glpi#16773]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.13

### Bug description

So i just did the upgrade to 10.0.13 yesterday and i have some users reporting that they can't create tickets anymore because they need to fill "Technician" field which is not displayed, since they don't need to fill it.
![image](https://github.com/glpi-project/glpi/assets/71132109/0e469719-628e-496f-a680-b346b110371d)

It was working before the update (was in 10.0.11).

### Relevant log output

None

### Steps To reproduce

1. Update to 10.0.13
2. Go as an user profile
3. Try to create a ticket

**Comment by cedric-anne** [comment]
Hi,

Do you have anything in GLPI logs ?

**Comment by cedric-anne** [comment]
Also, what was yourprevious GLPI version ?

**Comment by cedric-anne** [comment]
Could you test #16770 ?

**Comment by JonioDiPonio** [comment]
I modified the file but still can't create a ticket.
Do i need to restart something special ? Tried apache but nope.

And i just noticed buy the issue you gave me, i have this in the logs which correspond to the file i touched (before i changed it)
![image](https://github.com/glpi-project/glpi/assets/71132109/ba3e83c7-6f3d-4d98-a646-bb135134de67)

**Comment by cedric-anne** [comment]
Could you validate that #16774 fixes your issue ?

**Comment by JonioDiPonio** [comment]
Yup it works, I modified the 2 files in the src directory and the ticket is created.
I didn't create the 3rd one since i don't have the directory "tests" but i guess i don't need to create it ?
Anyway, thanks you.

**Comment by trasher** [comment]
> but i guess i don't need to create it ? Anyway, thanks you.

Indeed ;)

Thanks for the feedback.

**Comment by trasher** [comment]
It' fixed in GLPI 10.0.14
