### ISSUE TITLE
disappearance of the Ticket Panel due to change of entity

### ISSUE THREAD

**Issue by bern2b** [glpi-project/glpi#16775]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.13

### Bug description

We installed version 10.0.13 yesterday on the two different glpi instances we administer.

we notice a bug on this version with the panel present on the right on the details of a ticket during the following manipulation:
- the user connects and arrives at their default entity (example: entity A)
- if he opens a ticket, he has the panel on the right with the elements on the ticket, the requester, the technician, etc.
- it then changes entity to connect to entity B
- if he opens an existing ticket on this entity B, the panel is not visible (empty space instead)
- even if it then returns to its default entity, the panel is no longer visible.

If the agent disconnects and reconnects to GLPI, the panel returns.

This bug is problematic because it is no longer possible to act on tickets from entities other than the default one. I specify that the behavior is observed on the two different instances of glpi.
the action buttons to add a follow-up, a solution... in the queue you tickets also disappear.

Could you tell us if the problem has been identified? is a patch available?

*********************************************************************

Nous avons installé la version 10.0.13 hier sur les deux instances différentes de glpi que nous administrons.

nous constatons un bug sur cette version avec le panel présent à droit sur le détail d'un ticket lors de la manipulation suivante :
- l'utilisateur se connecte et arrive sur son entité par défaut (exemple : l'entité A)
- s'il ouvre un ticket, il dispose bien du panel à droite avec les éléments sur le ticket, le demandeur, le technicien...
- il change ensuite d'entité pour se connecter à l'entité B
- s'il ouvre un ticket existant sur cette entité B, le panel n'est pas visible (espace vide à la place)
- même s'il revient ensuite sur son entité par défaut, le panel n'est plus visible.

Si l'agent ce déconnecte et se reconnecter à GLPI, le panel revient.

ce bug est problématique car il n'est donc plus possible d'agir sur les tickets des autres entités que celle par défaut. je précise que le comportement est constaté sur les deux instances différentes de glpi.
les boutons d'actions pour ajouter un suivi, une solution...dans le file tu tickets disparaissent également.

Pourriez vous nous indiquer si le problème a été identifié ? un patch est-il disponible ?

### Page URL

/front/ticket.form.php

### Steps To reproduce

- the user connects and arrives at their default entity (example: entity A)
- if he opens a ticket, he has the panel on the right with the elements on the ticket, the requester, the technician, etc.
- it then changes entity to connect to entity B
- if he opens an existing ticket on this entity B, the panel is not visible (empty space instead)
- even if it then returns to its default entity, the panel is no longer visible.

### Your GLPI setup information

GLPI 10.0.13 ( => /data/http/glpi)
Installation mode: TARBALL
Current language:fr_FR

**Comment by cedric-anne** [comment]
Fixed by #16777.

**Comment by verdanatech-jadiael** [comment]
The problem may be related to the get Matching Active Entities method of the Session Class, I noticed that when treating the data, the behavior seems normalized!
