### ISSUE TITLE
Problem when solving a ticket

### ISSUE THREAD

**Issue by eduscott** [glpi-project/glpi#16789]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When I'm not the ticket initiator, I can't approve a solution. I have to reject the solution and then do a comment to close the ticket.

### Steps To reproduce

1. Close a ticket that you aren't the initiator.
2. Reject the solution.
3. Close the ticket

**Comment by cconard96** [comment]
If you are not the requestor, you shouldn't have the ability to approve a solution. The only way you should be able to reject the solution is by changing the status of the ticket. Closing a ticket with a solution pending should not auto-approve it.
