### ISSUE TITLE
Loop between collector and Mail notification

### ISSUE THREAD

**Issue by glasserre** [glpi-project/glpi#16785]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

Hello.

In the case we use a third party no-reply email as account in GLPI to open ticket, the fact that the notification is enable by default create a loop between mail server and GLPI that create amount of follow up.

For example : 
We create an account in GLPI with MSSecurity-noreply@microsoft.com email in order to create a ticket from MS Defender notifications.
When the ticket is created, the notification is enable by default : 

![image](https://github.com/glpi-project/glpi/assets/2472365/fc24ee07-bbd6-4f49-8382-4a80aee429d4)

When tecnician add followups or update ticket, a notification is sent to MSSecurity-noreply@microsoft.com, the mail server can't deliver the message and reply to the collector with no deliver response. Then GLPI add the follow up with no delivering message from mail server, and GLPI resend a notification to MSSecurity-noreply@microsoft.com because a new folloup was added, etc ...

![image](https://github.com/glpi-project/glpi/assets/2472365/c5039ee5-e97f-40e7-afad-d819b02e721e)

Suggest : 
Be able to control this default notification settings in GLPI user profil and allow to set "disable" for this type of user account.

Regards.

**Comment by cconard96** [comment]
Which headers are sent in the response from the "no reply" mailbox? You will need to view the source of this email (export as eml and view with a text editor).

There already exists rules in GLPI to handle ignoring automatic replies, but some are disabled by default.
See Administration > Rules > Rules for assigning a ticket created through a mails receiver (it applies to any email collected).

**Comment by glasserre** [comment]
Hello Curtis.
Will try to catch an email and you're right, i found the rules and they are disabled.
I test that as soon as possible and keep you up to date.
