### ISSUE TITLE
Error when reserving equipment with simplified interface

### ISSUE THREAD

**Issue by halexsandrosales** [glpi-project/glpi#16790]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Using the system's simplified interface, when we try to reserve an asset, the system does not complete the process.
No error message is displayed either.

Note: This error only occurs with the simplified interface. In the default interface, the system works normally.

### Page URL

../front/reservation.php?reservationitems_id=1

### Steps To reproduce

1 - enable an asset for the reserve.
2 - change your profile to self-service and try to reserve the item

**Comment by verdanatech-jadiael** [comment]
This problem is occurring because there is an identical check in the handleAddForm method of the Reservation.php class, but the types are different

It is necessary to cast the variable in the second condition to solve the problem!

(int)$input['user_id'];

**Comment by trasher** [comment]
Fixed by https://github.com/glpi-project/glpi/pull/16792
