### ISSUE TITLE
Inventory files have no cleanup policy

### ISSUE THREAD

**Issue by erique-souza** [glpi-project/glpi#16804]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

I noticed that the .json inventory files do not have a cleaning policy, these files I am using the downstream.php file indicating the GLPI_VAR_DIR in /var/lib/glpi/files

Inside this folder, a folder called _inventories is created and inside it there are several loose xml_code files and also several folders with .json files

In the xml_code files, there are many files that are dated 6 months ago, which is when the inventory began, and what catches my attention besides the date, is the content of some of them:
- These are simply records of connection errors in files that have not also been cleaned

![image](https://github.com/glpi-project/glpi/assets/102301295/4941ac25-992f-4446-876a-1c0d8341343b)
![image](https://github.com/glpi-project/glpi/assets/102301295/9081a2f9-2279-4c39-b65f-9aab2602c6c0)

I have a park of approximately 12 thousand computer devices, 6 thousand printers and 8 thousand network devices, and with this amount and anyone who has a similar or even larger park, will have some problems involving these files due to file management and the lack According to their cleaning policy, shouldn't these files be part of the automatic "cleantemp" task?

If we just look at the size of this folder with inventory files, it is currently around 7.4GB and without a cleaning policy, this will soon become a problem.
![image](https://github.com/glpi-project/glpi/assets/102301295/3dbfc6f8-6d99-483f-9021-1b22b3b18f7b)

**Comment by trasher** [comment]
There is an existing cron job for that.
