### ISSUE TITLE
Self-service booking impossible since the update from GLPI 10.0.10 to 10.0.14.

### ISSUE THREAD

**Issue by HUB79** [glpi-project/glpi#16800]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Good morning,
Since updating GLPI 10.0.10 to 10.0.14, I can no longer make reservations with the self-service profile. When I choose the reservation date and save, nothing happens and my reservation is not added.

I thank you in advance for your feedback.

**Comment by keguira** [comment]
I guess this is the same issue as #16790 
Fixed in 10.0.15

**Comment by HUB79** [comment]
Good morning,
Thank you for your comeback. With editing the srv/Reservation.php file the issue was resolved.
