### ISSUE TITLE
How to validate functional behaviors when values are set via massive actions?

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1681]
Hello,

This issue is linked to #1680, and linked to #1613, the goal is to enlarge the discussion and to solve those issues with a global approach.

Currently, there is no functional validation of values when they are set via massive actions (like possibility to assign "change category" to "ticket", or assign "incident ticket category" to a "request ticket")!

This breaks the data coherence.

My proposal: is to add this data coherence check on browser side when possible (for example: to not show ticket categories when doing massive actions on changes), and on PHP side every time (this will also benefit to the REST API).

Thank you,
Regards,

Tomolimo

**Comment by trasher** [comment]
Also related to #1118

**Comment by trasher** [comment]
I guess the PHP side validation should be done on each case; it does not sounds a good idea to rely only on browser data to do any validation.

**Comment by tomolimo** [comment]
I'm not speaking about browser data, but my meaning is for example the case of the ticket categories : do not show the change categories when editing tickets fields.

**Comment by trasher** [comment]
You said
> check on browser side when possible (for example: to not show ticket categories when doing massive actions on changes), and on PHP side when not possible

That should be changed to « check on browser side when possible (for example: to not show ticket categories when doing massive actions on changes), and on PHP side everytime » :)

**Comment by tomolimo** [comment]
I agree that my explanations were not so clear!
I'll fix that
