### ISSUE TITLE
Reservations made by a user with a simplified interface are not recorded

### ISSUE THREAD

**Issue by lbonetti** [glpi-project/glpi#16825]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

After migrating to version 10.0.14, even with the "Make a reservation" permission assigned in the profile, reservations made by a user with a simplified interface are not recorded.
No errors are displayed. The user can open the item's reservation calendar, select an empty period, fill the fields and click "Add", however nothing happens. The reservation is not entered into the calendar, which remains empty.

Making the reservation:
![making reservation](https://github.com/glpi-project/glpi/assets/8398908/b6f9b2cf-db7e-4554-95e3-3e14b24cc57f)

After clicking "add":
![after click](https://github.com/glpi-project/glpi/assets/8398908/8101b670-0af7-4ebe-b46c-ec88bd64b654)

### Relevant log output

```shell
No relevant logs are generated.
```

### Steps To reproduce

With a simplified user interface:
Go to the "Reservations" menu;
Open an item's reservation calendar;
Find an empty period and try to make a reservation.

### Anything else?

I upgraded directly from version 10.0.12 to version 10.0.14.

**Comment by cedric-anne** [comment]
Fixed by #16784.
