### ISSUE TITLE
There is no page for cameras glpi/front/item_devicecamera.form.php

### ISSUE THREAD

**Issue by feroguz** [glpi-project/glpi#16824]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

In the "Cameras" section it is not possible to generate or add a new camera. It indicates that the page does not exist. This has been reported before.

![image](https://github.com/glpi-project/glpi/assets/112366163/f058543a-f8cc-4b07-b156-f5183498d4d3)

![image](https://github.com/glpi-project/glpi/assets/112366163/a66bfdb7-e364-48bc-b610-8bbef6ab323d)

### Page URL

/front/item_devicecamera.form.php

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.14 ( => /home2/acpmex75/glpi.acpmex.com)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux gator4325.hostgator.com 4.19.286-203.ELK.el7.x86_64 #​1 SMP Wed Jun 14 04:33:55 CDT 2023 x86_64
PHP 8.2.17 litespeed (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, libxml, litespeed,
	mbstring, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, pspell, random, readline,
	session, soap, sockets, sodium, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="512M" post_max_size="516M" safe_mode="" session.save_handler="files"
	upload_max_filesize="512M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Server Software: Percona Server (GPL), Release 23, Revision 500fcf5
	Server Version: 5.7.23-23
	Server SQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: acpmex75_glpi310@localhost/acpmex75_glpi310
	Host info: Localhost via UNIX socket
	
PHP version (8.2.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.23) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_cache has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_cron has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_dumps has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_graphs has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_lock has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_pictures has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_plugins has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_rss has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_sessions has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_tmp has been validated.
Write access to /home2/acpmex75/glpi.acpmex.com/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/home2/acpmex75/glpi.acpmex.com":
‣ "/home2/acpmex75/glpi.acpmex.com/files" ("GLPI_VAR_DIR")
You can ignore this suggestion if your web server root directory is "/home2/acpmex75/glpi.acpmex.com/public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is not present.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /home2/acpmex75/glpi.acpmex.com/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home2/acpmex75/glpi.acpmex.com"
GLPI_CONFIG_DIR: "/home2/acpmex75/glpi.acpmex.com/config"
GLPI_VAR_DIR: "/home2/acpmex75/glpi.acpmex.com/files"
GLPI_MARKETPLACE_DIR: "/home2/acpmex75/glpi.acpmex.com/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/home2/acpmex75/glpi.acpmex.com/files"
GLPI_CACHE_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_cache"
GLPI_CRON_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_cron"
GLPI_DUMP_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_dumps"
GLPI_GRAPH_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_locales"
GLPI_LOCK_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_lock"
GLPI_LOG_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_log"
GLPI_PICTURE_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_plugins"
GLPI_RSS_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_rss"
GLPI_SESSION_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_sessions"
GLPI_TMP_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_tmp"
GLPI_UPLOAD_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_uploads"
GLPI_INVENTORY_DIR: "/home2/acpmex75/glpi.acpmex.com/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/home2/acpmex75/glpi.acpmex.com/locales"
GLPI_VERSION: "10.0.14"
GLPI_SCHEMA_VERSION: "10.0.14@8f13530f7cf0fb07add30ae20013f0374956795b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/home2/acpmex75/glpi.acpmex.com/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/home2/acpmex75/glpi.acpmex.com/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home2/acpmex75/glpi.acpmex.com/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/home2/acpmex75/glpi.acpmex.com/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home2/acpmex75/glpi.acpmex.com/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home2/acpmex75/glpi.acpmex.com/vendor/true/punycode/src)
iamcal/lib_autolink in (/home2/acpmex75/glpi.acpmex.com/vendor/iamcal/lib_autolink)
sabre/dav in (/home2/acpmex75/glpi.acpmex.com/vendor/sabre/dav/lib/DAV)
sabre/http in (/home2/acpmex75/glpi.acpmex.com/vendor/sabre/http/lib)
sabre/uri in (/home2/acpmex75/glpi.acpmex.com/vendor/sabre/uri/lib)
sabre/vobject in (/home2/acpmex75/glpi.acpmex.com/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home2/acpmex75/glpi.acpmex.com/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home2/acpmex75/glpi.acpmex.com/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home2/acpmex75/glpi.acpmex.com/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home2/acpmex75/glpi.acpmex.com/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home2/acpmex75/glpi.acpmex.com/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home2/acpmex75/glpi.acpmex.com/vendor/elvanto/litemoji/src)
symfony/console in (/home2/acpmex75/glpi.acpmex.com/vendor/symfony/console)
scssphp/scssphp in (/home2/acpmex75/glpi.acpmex.com/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home2/acpmex75/glpi.acpmex.com/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home2/acpmex75/glpi.acpmex.com/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home2/acpmex75/glpi.acpmex.com/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/home2/acpmex75/glpi.acpmex.com/vendor/ramsey/uuid/src)
psr/log in (/home2/acpmex75/glpi.acpmex.com/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home2/acpmex75/glpi.acpmex.com/vendor/psr/simple-cache/src)
psr/cache in (/home2/acpmex75/glpi.acpmex.com/vendor/psr/cache/src)
league/csv in (/home2/acpmex75/glpi.acpmex.com/vendor/league/csv/src)
mexitek/phpcolors in (/home2/acpmex75/glpi.acpmex.com/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home2/acpmex75/glpi.acpmex.com/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home2/acpmex75/glpi.acpmex.com/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home2/acpmex75/glpi.acpmex.com/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home2/acpmex75/glpi.acpmex.com/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home2/acpmex75/glpi.acpmex.com/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home2/acpmex75/glpi.acpmex.com/vendor/symfony/cache)
html2text/html2text in (/home2/acpmex75/glpi.acpmex.com/vendor/html2text/html2text/src)
symfony/css-selector in (/home2/acpmex75/glpi.acpmex.com/vendor/symfony/css-selector)
symfony/dom-crawler in (/home2/acpmex75/glpi.acpmex.com/vendor/symfony/dom-crawler)
twig/twig in (/home2/acpmex75/glpi.acpmex.com/vendor/twig/twig/src)
twig/string-extra in (/home2/acpmex75/glpi.acpmex.com/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home2/acpmex75/glpi.acpmex.com/vendor/symfony/polyfill-php82)
league/oauth2-client in (/home2/acpmex75/glpi.acpmex.com/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/home2/acpmex75/glpi.acpmex.com/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/home2/acpmex75/glpi.acpmex.com/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (ticket@acpmex.com@gator4325.hostgator.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional Fields              Version: 1.20.5     State: Installed / not activated               
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.0     State: Installed / not activated               
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.8     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.4      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: More Reporting                 Version: 1.8.2      State: Installed / not activated               
		Install Method: Manual
	moreticket           Name: More ticket                    Version: 1.7.1      State: Not installed                           
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Objects management             Version: 2.14.2     State: Installed / not activated               
		Install Method: Manual
	order                Name: Orders management              Version: 2.10.4     State: Installed / not activated               
		Install Method: Manual
	pdf                  Name: Print to pdf                   Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	tag                  Name: Tag Management                 Version: 2.11.6     State: Installed / not activated               
		Install Method: Manual
	ticketmail           Name: Ticket Mail                    Version: 3.6.2      State: Installed / not activated               
		Install Method: Manual
	useditemsexport      Name: Used items export              Version: 2.5.1      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Comment by trasher** [comment]
This has already been reported, and fixed

**Comment by cedric-anne** [comment]
See #16818
