### ISSUE TITLE
Undefined array key "action" in /var/www/glpi/src/Inventory/Asset/MainAsset.php at line 592

### ISSUE THREAD

**Issue by JonioDiPonio** [glpi-project/glpi#16828]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

So i have a new computer, i installed glpi agent with a GPO (like every other PC) but this one won't get created in GLPI, the agent is there but is linked with nothing since the computer can't be imported. Tried to install manually but still no.
In the agent log there is no specific error.

I don't know if it's the rules or not, i had no problem for the last computer in v10.0.11 of GLPI and now it's now working (i was in version 10.0.13 a hour ago and same problem the upgrade to v14 didn't helped).

The rules were never changed from before.

### Relevant log output

```shell
php-error.log : 
`
[2024-03-26 13:18:24] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "action" in /var/www/glpi/src/Inventory/Asset/MainAsset.php at line 592
  Backtrace :
  src/Inventory/Inventory.php:724                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:355                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:364                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:359    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:271    Glpi\Agent\Communication\AbstractRequest->handleJSONRequest()
  front/inventory.php:95                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()
  public/index.php:82                                require()
`
```

### Steps To reproduce

1. Get a new computer
2. install the agent
3. Try to make an inventory

### Anything else?

GLPI Agent : 1.7.2 (tried with 1.7.1 and some 1.8 night build but nope)

**Comment by trasher** [comment]
Seems like an issues with your rules. Try (on a preprod eventuelly) to reset rules.

**Comment by JonioDiPonio** [comment]
I will try now but last time i did that for another problem (that i still have but will do another issue) it worked but EVERY computer started to duplicate so i went back as before.

**Comment by trasher** [comment]
Anyway, we need a simple way to reproduce from a blank install to get that fixed; since we do not have your data.

**Comment by JonioDiPonio** [comment]
The computer is created with a blank install of GLPI, is there a way to see which rule is the problem ?

**Comment by trasher** [comment]
You can try to import your rules in blank install, and if you reproduce, try to disable some; until you get the faultly one. On my local instance, I generally use brekpoints with a debugger to find those kind of issues.

**Comment by JonioDiPonio** [comment]
I imported the rules (only 13 of 25 where imported for Computer) and it works.
I'm thinking maybe it's the rules from v9.5.xx with fusioninventroy who got imported when i upgraded to v10 and it duplicated every rules and doing some weird stuff (I might be wrong just a hypothesis).

I'm gonna compare what got imported and what is left on the prod one

**Comment by JonioDiPonio** [comment]
Yeah ok it was the rules, I'm pretty sure that one day I got confused by many same rules when trying to fix a bug with "item_id cannot be null" (not fixed yet but will check now) and totally messed them up.
Now that they look like default the import of a new computer is good.
