### ISSUE TITLE
Error on glpi_consumable screen

### ISSUE THREAD

**Issue by SilvaFernando** [glpi-project/glpi#16839]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Timeout on glpi_consumable items when I use these fields on personal view(NUMBER OF USED CONSUMABLES and NUMBER OF USED CONSUMABLES:
![image](https://github.com/glpi-project/glpi/assets/53239752/b2d0108a-3bb3-4a08-be8f-fd10e53d827c)

### Relevant log output

```shell
Don't have any logs
```

### Page URL

https://glpi-14.sdbrasil.ninja/front/consumableitem.php

### Steps To reproduce

Use NUMBER OF USED CONSUMABLES and NUMBER OF USED CONSUMABLES, this error just occurs if you have many consumables.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.14 ( => /usr/share/glpi)
Installation mode: RPM
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux 952d72f724be 4.18.0-477.21.1.el8_8.x86_64 #​1 SMP Tue Aug 8 21:30:09 UTC 2023 x86_64
PHP 8.2.13 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, random, selinux, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36 Edg/123.0.0.0
Server Software: Percona Server (GPL), Release 27, Revision 2f8eeab2
	Server Version: 8.0.35-27
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@glpi_db_new/glpi
	Host info: glpi_db_new via TCP/IP
	
PHP version (8.2.13) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.35) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi/files/_cache has been validated.
Write access to /var/lib/glpi/files/_cron has been validated.
Write access to /var/lib/glpi/files/data-documents has been validated.
Write access to /var/lib/glpi/files/_dumps has been validated.
Write access to /var/lib/glpi/files/_graphs has been validated.
Write access to /var/lib/glpi/files/_lock has been validated.
Write access to /var/lib/glpi/files/_pictures has been validated.
Write access to /var/lib/glpi/files/_plugins has been validated.
Write access to /var/lib/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /var/lib/glpi/files/_tmp has been validated.
Write access to /var/lib/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
The directory could not be created in /usr/share/glpi/marketplace.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/usr/share/glpi"
GLPI_CONFIG_DIR: "/etc/glpi"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: false
GLPI_VAR_DIR: "/var/lib/glpi/files"
GLPI_DOC_DIR: "/var/lib/glpi/files/data-documents"
GLPI_CRON_DIR: "/var/lib/glpi/files/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi/files/_graphs"
GLPI_LOCK_DIR: "/var/lib/glpi/files/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi/files/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/files/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi/files/_uploads"
GLPI_CACHE_DIR: "/var/lib/glpi/files/_cache"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_SYSTEM_CRON: true
GLPI_INSTALL_MODE: "RPM"
GLPI_MARKETPLACE_DIR: "/usr/share/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi/files/_locales"
GLPI_INVENTORY_DIR: "/var/lib/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/usr/share/glpi/locales"
GLPI_VERSION: "10.0.14"
GLPI_SCHEMA_VERSION: "10.0.14"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.4.4 in (/usr/share/glpi/plugins/pdf/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/usr/share/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/usr/share/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/usr/share/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.6.1 in (/usr/share/pear)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: none, Port: '389', BaseDN: none, Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: none, Use TLS:
		none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (si@servicedeskbrasil.com.br@smtp.office365.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	news                 Name: Alertas                        Version: 1.12.1     State: Enabled                                 
		Install Method: Manual
	fields               Name: Campos adicionais              Version: 1.20.6     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data injection                 Version: 2.13.2     State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalonamento                  Version: 2.9.1      State: Enabled                                 
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.8.1   State: Enabled                                 
		Install Method: Manual
	genericobject        Name: Gerenciamento de objetos       Version: 2.14.3     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.2.1      State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Enabled                                 
		Install Method: Manual
	metabase             Name: Metabase                       Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	phpsaml              Name: PHP SAML                       Version: 1.3.0      State: Enabled                                 
		Install Method: Manual
	sdbsubtask           Name: Plugin SDB SubTask             Version: 1.2.1      State: Enabled                                 
		Install Method: Manual
	sdbacaoporemail      Name: Servicedesk Brasil - Ação por  Version: 2.0.9      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
How many consumables do you have in your DB?
```sql
SELECT COUNT(*) FROM glpi_consumables;
```
What is your current list limit (Number of search results displayed on a single page)?

**Comment by SilvaFernando** [comment]
Hi @cconard96.
Follow count: 
![image](https://github.com/glpi-project/glpi/assets/53239752/92355709-d798-4b72-882a-188e5eed0f25)

**Comment by SilvaFernando** [comment]
Hi @cconard96.
Do you have some feedback?
Thanks

**Comment by cconard96** [comment]
How many consumables are you trying to display in GLPI at once (how many search results are you showing per page)?
You indicate that the issue appears when there are a lot of consumables. In order to test this, I would need to know the total number of consumables (which you provided) and how many are trying to be shown at once so that I can try to recreate the circumstances and see if the performance can be improved any substantial amount.

**Comment by SilvaFernando** [comment]
Hi @cconard96.
I've trying show just 10 lines, which I think is not very much, If I show just one I have the same issue.

**Comment by SilvaFernando** [comment]
Hi @cconard96, do you have some feedback?

**Comment by SilvaFernando** [comment]
Hi @cconard96, can you help-me?

**Comment by IsaacMariaMedina** [comment]
Has anyone else experienced this? When I try to search in Consumables, I get this error:

Twig Error (Twig\Error\RuntimeError): "An exception has been thrown during the rendering of a template ("CommonDBTM::isMassiveActionAllowed(): Argument #1 ($items_id) must be of type int, null given")." in template "/var/www/html/glpi/templates/components/search/table.html.twig" at line 121

**Comment by IsaacMariaMedina** [comment]
> Has anyone else encountered this error when trying to search in Consumables?
> 
> Twig Error (Twig\Error\RuntimeError): "An exception has been thrown during the rendering of a template ("CommonDBTM::isMassiveActionAllowed(): Argument #1 ($items_id) must be of type int, null given")." in template "/var/www/html/glpi/templates/components/search/table.html.twig" at line 121
> 
> Additionally, when I load the Consumable Request plugin, it returns this error:
> 
> PHP User Warning (512): Duplicate keys found in search options for item type ConsumableItem: 1, 2 in /var/www/html/glpi/src/Search.php at line 8335

The solution is to copy the old Search.php to the new path. This will help those who are facing this issue
