### ISSUE TITLE
PHP Deprecated function (8192): mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/Inventory/Asset/Software.php at line 525

### ISSUE THREAD

**Issue by JonioDiPonio** [glpi-project/glpi#16840]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

So, I have an error on some computers when doing an inventory, some of them doesn't get linked with their agent so the inventory doesn't update in GLPI.

In the agent log i have this error : 
![image](https://github.com/glpi-project/glpi/assets/71132109/4a94ff93-a8c0-4ed6-b377-0d67b3d11eca)
Column 'items_id' cannot be null

I see the agent getting created in Inventory > Agent but not linked with the computer.
When i'm on the computer page i download the inventory file and it download the right inventory file.

but when i try to import it manually (json or xml (from the agent)) i got this error showing with debug mode on : 
![image](https://github.com/glpi-project/glpi/assets/71132109/a8104729-1bbe-4473-a84f-f516b0dd539e)

And i noticed that i have this error on computer where there is locks on them like this : 
![image](https://github.com/glpi-project/glpi/assets/71132109/889f06c6-3b1b-4d9b-9dff-3fbecc572ef1)

I can't delete these locks with no name and i can't find in the database where are they to delete them.

### Relevant log output

```shell
`[2024-03-27 14:39:22] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/Inventory/Asset/Software.php at line 525
  Backtrace :
  src/Inventory/Asset/Software.php:525               mb_strtolower()
  src/Inventory/Asset/Software.php:362               Glpi\Inventory\Asset\Software->getFullCompareKey()
  src/Inventory/Asset/MainAsset.php:1001             Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:916              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:981                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1531                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1660                        Rule->process()
  src/Inventory/Asset/MainAsset.php:582              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:724                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:355                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:364                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:242                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:187                         Glpi\Inventory\Conf->importContentFile()
  src/Inventory/Conf.php:291                         Glpi\Inventory\Conf->importFiles()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->displayImportFiles()
  public/index.php:82                                require()

[2024-03-27 14:39:22] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/glpi/src/Inventory/Asset/Software.php at line 525
  Backtrace :
  src/Inventory/Asset/Software.php:525               mb_strtolower()
  src/Inventory/Asset/Software.php:363               Glpi\Inventory\Asset\Software->getFullCompareKey()
  src/Inventory/Asset/MainAsset.php:1001             Glpi\Inventory\Asset\Software->handle()
  src/Inventory/Asset/MainAsset.php:916              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/RuleImportAsset.php:981                        Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/Rule.php:1531                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1660                        Rule->process()
  src/Inventory/Asset/MainAsset.php:582              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:724                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:355                    Glpi\Inventory\Inventory->handleItem()
  src/Inventory/Request.php:364                      Glpi\Inventory\Inventory->doInventory()
  src/Inventory/Request.php:90                       Glpi\Inventory\Request->inventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  src/Inventory/Conf.php:242                         Glpi\Agent\Communication\AbstractRequest->handleRequest()
  src/Inventory/Conf.php:187                         Glpi\Inventory\Conf->importContentFile()
  src/Inventory/Conf.php:291                         Glpi\Inventory\Conf->importFiles()
  front/inventory.conf.php:47                        Glpi\Inventory\Conf->displayImportFiles()
  public/index.php:82                                require()`
```

### Steps To reproduce

1. Have a computer in GLPI
2. Have lock on software with no name
3. Try to do an inventory

### Anything else?

GLPI agent 1.7.2

I tried on a fresh install it works, and with my imported rules aswell.

**Comment by trasher** [comment]
You probably have software rules or similar that is causing the issue.

We need a way to reproduce from a fresh install.

**Comment by JonioDiPonio** [comment]
Got a solution to bypass this problem : 
-Delete permanently the computer -> inventory ok 👍 
A bit bad if you want to keep some history on the computer and link with tickets but it works.

I will still look around on a fresh install and prod if i can reproduce this bug.

**Comment by JonioDiPonio** [comment]
Ok so i wasn't successful to reproduce the bug on a fresh install but i got a clean solution for this.
I deleted all the software from the database linked with the computer, in the table "glpi_items_softwareversions" i deleted all the software where the "items_id" column correspond to the id of my computer and the "ghosts" software were no more and the inventory is ok.
For example my computer Id was "554" so i deleted all the software where items_id = 554.

**Comment by trasher** [comment]
Sounds like the issue was from your existing data then... I close since we cannot fix and you found a way to fix on your side.
