### ISSUE TITLE
generic object plugin error

### ISSUE THREAD

**Issue by avelor** [glpi-project/glpi#16842]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

We're using plugin Generic Object for custom objects at glpi.
Today our users faces pretty strange problem:
Than  I try to sort objects by filed with users (no matter is it User field or Technical in charge) there is an error "Expression #1 of ORDER BY contains aggregate function and applies to the result of a non-aggregated query".

![image](https://github.com/glpi-project/glpi/assets/38662163/8410a263-373b-42a0-b7a1-e1559325ea7f)

It seems like sql error and bug for me..

If I sort by another fileds with dropdowns (like Status)- there is no error..

**Comment by trasher** [comment]
Please do not report plugins issues here; but on each plugin directly.

**Comment by avelor** [comment]
How I can do that? I can’t create issue at plugin repo - https://github.com/pluginsGLPI/genericobject/issues 
Only Report a security vulnerability…

**Comment by trasher** [comment]
No idea. Issues on glpi-project/glpi are only for GLPI core issues, nothing else.
