### ISSUE TITLE
Access denied for LDAP auth

### ISSUE THREAD

**Issue by Franco-Sparrow** [glpi-project/glpi#16857]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11
10.0.14

### Bug description

I have configured the LDAP auth following the [official documentation](https://glpi-user-documentation.readthedocs.io/fr/latest/modules/configuration/authentication/ldap.html) for Active Directory. I am using Windows AD 2022 (AD 2016 server level).

![imagen](https://github.com/glpi-project/glpi/assets/56793015/6a0e7961-7add-4303-b6a0-ea620f1ed98c)
PS: I have tried also with `RootDN: CN=ccecasa,CN=Users,DC=ecasa,DC=avianet,DC=cu`.

If the LDAP configuration were wrong, I guess that I couldnt be able to synchronize with my AD, which is not the case, as the GLPI is capable to import all users from **Redes** AD group:

```bash
sudo -u www-data /usr/bin/php bin/console glpi:ldap:synchronize_users
```

The output is as follow:

```bash
+-----------------+-----------+
| Servidores LDAP | DC101 (2) |
| Filtro LDAP     |           |
| Fecha de inicio |           |
| Fecha fin       |           |
+-----------------+-----------+
¿Quiere continuar? [Yes/no]yes
Procesando servidor LDAP "2"...
Importando nuevos usuarios desde el servidor "2"...
No se encontraron usuarios.
Sincronizar usuarios con el servidor "2"...
 6/6 [============================] 100%
+---------------+------------+--------------+-------------------+-------------------------+
| Servidor LDAP | Importados | Sincronizado | Eliminado de LDAP | Restablecido desde LDAP |
+---------------+------------+--------------+-------------------+-------------------------+
| 2             | 0          | 6            | 0                 | 0                       |
+---------------+------------+--------------+-------------------+-------------------------+
```

![imagen](https://github.com/glpi-project/glpi/assets/56793015/f6d7676b-772b-40f0-a573-3c0419776b68)

![imagen](https://github.com/glpi-project/glpi/assets/56793015/3bf26d74-1079-48b2-bcd9-176439597e1c)

![imagen](https://github.com/glpi-project/glpi/assets/56793015/19c9c2c5-b140-4eb2-a1a8-59d78f1f29a0)

![imagen](https://github.com/glpi-project/glpi/assets/56793015/58d31a6e-8436-4b6e-bd84-fa0616e4109b)

**Comment by cconard96** [comment]
Is the user active and does it have at least one profile assignment?

**Comment by Franco-Sparrow** [comment]
> Is the user active and does it have at least one profile assignment?

Hi Sir, thanks for your quick response. I havent seen this on the official documentation. In fact, I got this command to synchronize user outside the LDAP topic in the dcumentation. In response to your question: Yes, they are all active users once imported and synchronized with the GLPI server:

![imagen](https://github.com/glpi-project/glpi/assets/56793015/d62dc0d6-1b28-44fc-98be-6a35af8f1eaf)

**Comment by Franco-Sparrow** [comment]
I guess I will have to keep with local database access, as this is not working.

**Comment by trasher** [comment]
Try with latest stable release; and without plugins (no idea if you use some because you did not fill requested information).

While it is possible there is a bug, it also could be a configuration issue that is out of the scope of community support, since this is often the case with configuration similar to yours.

**Comment by Franco-Sparrow** [comment]
@trasher thanks for your reply. Could you please indicate me where is the configuration issue? I shared the link to the official documentation, I followed the instructions, I even added the screenshots. Did you see anything wrong from my side? I have only installed Glpi Inventory plugin, no extra plugin for auth, LDAP is integrated with the solution. I will follow your recommendation, and will install the latest stable version...but does that means that this is broken on v10.0.11? 

Thanks in advance

**Comment by trasher** [comment]
Since I have absolutely no knowledge on Azure, no I can't tell what the problem is. As said, that is out of the scope of community support.

Latest release contains numerous fixes (including security ones); I have no idea if that can affect your problem, but anyway this is the first thing to check.

**Comment by Franco-Sparrow** [comment]
@cconard96 @trasher 

Good day gentlemans. As recommended by you previous this comment, I have upgraded to GLPI latest stable version `10.0.14`. The LDAP auth issue remains even after the upgrade.

![image](https://github.com/glpi-project/glpi/assets/56793015/4d319fc8-cf86-4b32-b0b5-92aaed342f89)

![image](https://github.com/glpi-project/glpi/assets/56793015/4008724f-e3a6-4d5f-ae06-aad92f0cb80f)

![image](https://github.com/glpi-project/glpi/assets/56793015/0d449f0a-f4aa-48a5-a4b3-0721606f314f)

May I have a follow up on this? 

Thanks in advance

**Comment by Franco-Sparrow** [comment]
Is working now. I had a missing `)` in the LDAP user filter.
