### ISSUE TITLE
Changes "Last edit by" sorting SQL query problem

### ISSUE THREAD

**Issue by blublu31** [glpi-project/glpi#16855]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Hello,

There is a bug when you order by  "Last edit by" on the Changes list.
If you order by anything (ID, Last update, Status, etc...) it works like a charm, but if you order by "Last edit by" it only print out one line.

I have checked the SQL request with the debug mode and i think i found the problem.

### Relevant log output

```shell
SQL request :

SELECT DISTINCT `glpi_changes`.`id` AS id, 'cbluzat' AS currentuser,
                        `glpi_changes`.`entities_id`, `glpi_changes`.`is_recursive`, `glpi_changes`.`id` AS `ITEM_Change_2`,   `glpi_changes`.`name` AS `ITEM_Change_1`,
                        `glpi_changes`.`id` AS `ITEM_Change_1_id`,
                        `glpi_changes`.`id` AS `ITEM_Change_1_id`, `glpi_changes`.`status` AS `ITEM_Change_1_status`, `glpi_entities`.`completename` AS `ITEM_Change_80`,  `glpi_changes`.`priority` AS `ITEM_Change_3`,  `glpi_changes`.`status` AS `ITEM_Change_12`,  `glpi_changes`.`date_mod` AS `ITEM_Change_19`,   `glpi_users_users_id_lastupdater`.`name` AS `ITEM_Change_64`,
                        `glpi_users_users_id_lastupdater`.`realname` AS `ITEM_Change_64_realname`,
                        `glpi_users_users_id_lastupdater`.`id`  AS `ITEM_Change_64_id`,
                        `glpi_users_users_id_lastupdater`.`firstname` AS `ITEM_Change_64_firstname`,
                        `glpi_itilcategories`.`completename` AS `ITEM_Change_7`, IFNULL(`glpi_itilcategories_trans_completename`.`value`,'__NULL__')  AS `ITEM_Change_7_trans_completename`,  `glpi_projects_58d1ddfe4485681a04da313df0a12066`.`name` AS `ITEM_Change_450` 
FROM `glpi_changes`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_changes`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_users`  AS `glpi_users_users_id_lastupdater`
                                          ON (`glpi_changes`.`users_id_lastupdater` = `glpi_users_users_id_lastupdater`.`id`
                                              )LEFT JOIN `glpi_itilcategories` 
                                          ON (`glpi_changes`.`itilcategories_id` = `glpi_itilcategories`.`id`
                                              )LEFT JOIN `glpi_dropdowntranslations` AS `glpi_itilcategories_trans_completename`
                  ON (`glpi_itilcategories_trans_completename`.`itemtype` = 'ITILCategory'
                        AND `glpi_itilcategories_trans_completename`.`items_id` = `glpi_itilcategories`.`id`
                        AND `glpi_itilcategories_trans_completename`.`language` = 'en_GB'
                        AND `glpi_itilcategories_trans_completename`.`field` = 'completename') LEFT JOIN `glpi_itils_projects` 
                                          ON (`glpi_changes`.`id` = `glpi_itils_projects`.`items_id`
                                              AND `glpi_itils_projects`.`itemtype` = 'Change'
                                              ) LEFT JOIN `glpi_projects`  AS `glpi_projects_58d1ddfe4485681a04da313df0a12066`
                                          ON (`glpi_itils_projects`.`projects_id` = `glpi_projects_58d1ddfe4485681a04da313df0a12066`.`id`
                                              ) 
WHERE  `glpi_changes`.`is_deleted` = 0  AND (   `glpi_changes`.`status` IN ('1','9','10','7','4','11','12') ) ORDER BY GROUP_CONCAT(DISTINCT CONCAT(
                                IFNULL(`glpi_users_users_id_lastupdater`.`firstname`, ''),
                                IFNULL(`glpi_users_users_id_lastupdater`.`realname`, ''),
                                IFNULL(`glpi_users_users_id_lastupdater`.`name`, '')
                            ) ORDER BY CONCAT(
                                IFNULL(`glpi_users_users_id_lastupdater`.`firstname`, ''),
                                IFNULL(`glpi_users_users_id_lastupdater`.`realname`, ''),
                                IFNULL(`glpi_users_users_id_lastupdater`.`name`, '')) ASC
                            ) ASC
```

### Page URL

https://helpdesk.ad.satys.com/front/change.php?is_deleted=0&as_map=0&browse=0&criteria%5B0%5D%5Blink%5D=AND&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=notold&itemtype=Change&start=0&_glpi_csrf_token=38bc0bc9b71b8db6947779dd722d9365f71037a79f2a637ea212e487f2b62222&sort%5B%5D=64&order%5B%5D=ASC

### Steps To reproduce

Go to the changes tab
Order by "Last edit by"
Only 1 line appears.

### Your GLPI setup information

GLPI 10.0.12 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

### Anything else?

I tried deleting the _"ORDER BY GROUP_CONCAT(DISTINCT CONCAT(
                                IFNULL(`glpi_users_users_id_lastupdater`.`firstname`, ''),
                                IFNULL(`glpi_users_users_id_lastupdater`.`realname`, ''),
                                IFNULL(`glpi_users_users_id_lastupdater`.`name`, '')
                            )"_ from the SQL request, and it seems like it works, i don't know if it is the solution but looking at the other ORDER BY, they don't have a double one.
                            
[Changes Last edit by SQL REQUEST.txt](https://github.com/glpi-project/glpi/files/14805466/Changes.Last.edit.by.SQL.REQUEST.txt)

I tried it on GLPI database here is a part of the result
![Server SQL Answer](https://github.com/glpi-project/glpi/assets/59641773/d5b2f90e-5e03-4730-a966-3066201a1d64)

**Comment by trasher** [comment]
I confirm this is reproducible on current 10.0/bugfixes branch, and indeed the `ORDER BY` clause seems strange.

**Comment by trasher** [comment]
Issue also appears when trying to sort on "Writer", and on all `ITILObjects` (`Changes`, 'Tickets` and `Problems`).
It seems it only appears when there is no other "user" field in display. For example, when adding "Requester" to display list, issue does not happens.

**Comment by blublu31** [comment]
Thank you for looking at this.
I will add another "user" filed in display until 10.0.15 is out.
Appreciate it ! 👍🏻
