### ISSUE TITLE
Dropdown list "Linked Tickets"

### ISSUE THREAD

**Issue by CDG47** [glpi-project/glpi#16877]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.14

### Bug description

since the update from 10.0.12 to 10.0.13 and 10.0.14, we have a slow request for the dropdown list of
linked tickets
![image](https://github.com/glpi-project/glpi/assets/11661365/28a21ac8-140a-4a13-946b-28afa77fc394)

### Relevant log output

```shell
no error shown in logs
```

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.14 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux support 5.10.0-22-amd64 #​1 SMP Debian 5.10.178-3 (2023-04-22) x86_64
PHP 8.1.26 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="96M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Server Software: Debian 12
	Server Version: 10.11.4-MariaDB-1~deb12u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: 
	Host info: xxxx via TCP/IP
	
PHP version (8.1.26) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.4) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/xxx/glpi/files/_cache has been validated.
Write access to /home/xxx/glpi/files/_cron has been validated.
Write access to /home/xxx/glpi/files has been validated.
Write access to /home/xxx/glpi/files/_dumps has been validated.
Write access to /home/xxx/glpi/files/_graphs has been validated.
Write access to /home/xxx/glpi/files/_lock has been validated.
Write access to /home/xxx/glpi/files/_pictures has been validated.
Write access to /home/xxx/glpi/files/_plugins has been validated.
Write access to /home/xxx/glpi/files/_rss has been validated.
Write access to /home/xxx/glpi/files/_sessions has been validated.
Write access to /home/xxx/glpi/files/_tmp has been validated.
Write access to /home/xxx/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi"
GLPI_VAR_DIR: "/home/xxx/glpi/files"
GLPI_DOC_DIR: "/home/xxx/glpi/files"
GLPI_CRON_DIR: "/home/xxx/glpi/files/_cron"
GLPI_DUMP_DIR: "/home/xxx/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/home/xxx/glpi/files/_graphs"
GLPI_LOCK_DIR: "/home/xxx/glpi/files/_lock"
GLPI_PICTURE_DIR: "/home/xxx/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/xxx/gpi/files/_plugins"
GLPI_RSS_DIR: "/home/xxx/glpi/files/_rss"
GLPI_SESSION_DIR: "/home/xxx/glpi/files/_sessions"
GLPI_TMP_DIR: "/home/xxx/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/home/xxx/glpi/files/_uploads"
GLPI_CACHE_DIR: "/home/xxx/glpi/files/_cache"
GLPI_CONFIG_DIR: "/var/www/glpi/config"
GLPI_MARKETPLACE_DIR: "/var/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_LOCAL_I18N_DIR: "/home/xxx/glpi/files/_locales"
GLPI_LOG_DIR: "/home/xxx/glpi/files/_log"
GLPI_INVENTORY_DIR: "/home/xxx/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi/locales"
GLPI_VERSION: "10.0.14"
GLPI_SCHEMA_VERSION: "10.0.14@8f13530f7cf0fb07add30ae20013f0374956795b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi/vendor/psr/cache/src)
league/csv in (/var/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
</pre></details><details><summary>Plugins list</summary><pre> 
	actualtime           Name: ActualTime                     Version: 3.0.0      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertes                        Version: 1.12.1     State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Champs supplémentaires         Version: 1.21.8     State: Enabled                                 
		Install Method: Marketplace
	credit               Name: Crédits                        Version: 1.13.2     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.5     State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.9     State: Enabled                                 
		Install Method: Marketplace
	fusioninventory      Name: FusionInventory                Version: 10.0.6+1.1 State: Error / to clean                        
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Marketplace
	mreporting           Name: Plus de rapports               Version: 1.8.6      State: Installed / not activated               
		Install Method: Marketplace

</pre></details>

**Comment by trasher** [comment]
Please writ in english only, as requested.

**Comment by CDG47** [comment]
Sorry, since the update from 10.0.12 to 10.0.13 and 10.0.14, we have a slow request for the dropdown list of 
linked tickets

**Comment by trasher** [comment]
Did you try without any plugin?

Without an easy way to reproduce, and no further information (like number of related tickets, ...); it's not really possible to investigate on this kind of issue.

**Comment by CDG47** [comment]
About 55 300 tickets in the database.
Without any plugin it's the same issue.
The duration varies but many times it's around 10-15s

**Comment by nuria2c** [comment]
We have the same problem and with some technician profiles returns en error 500 (when the techician profile doesn't have the capability "View all tickets").

Version of GLPI: 10.0.14
Duration: more than 15s
Number of tickets in database: 133.000 aprox
Search by id ticket

**Comment by trasher** [comment]
A 500 error certainly have a trace in logs. Reported issue is not about an error, but a slow response.

**Comment by nuria2c** [comment]
Is a very low response. Most than 120 seconds. 

When you try to link tickets you start write in the dropdown and at this moment, the system starts to generate the query. I think this is the reason for the slowness-

Example: if you want to link to the ticket with id 127672, when you start write "1" in the drop down the query starts, then you writes "2" and the query re-start. The system doesn't to execute the query till you finish to write. Its dificult to explain in english for me-... (sorry)

The query, for the example, is like:


SELECT DISTINCT `glpi_tickets`.* FROM `glpi_tickets` LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`tickets_id`
                                                  AND `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.`type` = '1' ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_019878060c6d5f06cbe3c4d7c31dec24`
                                             ON (`glpi_tickets`.`id` = `glpi_groups_tickets_019878060c6d5f06cbe3c4d7c31dec24`.`tickets_id`
                                                  AND `glpi_groups_tickets_019878060c6d5f06cbe3c4d7c31dec24`.`type` = '1' ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`.`tickets_id`
                                                  AND `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`.`type` = '3' ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_9c6b5b644d74a9e8013c7c2ea051dffd`
                                             ON (`glpi_tickets`.`id` = `glpi_groups_tickets_9c6b5b644d74a9e8013c7c2ea051dffd`.`tickets_id`
                                                  AND `glpi_groups_tickets_9c6b5b644d74a9e8013c7c2ea051dffd`.`type` = '3' ) LEFT JOIN `glpi_tickets_users`  AS `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`
                                             ON (`glpi_tickets`.`id` = `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`tickets_id`
                                                  AND `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`type` = '2' ) LEFT JOIN `glpi_groups_tickets`  AS `glpi_groups_tickets_c6f7f58b9365babf7388e555e526efd5`
                                             ON (`glpi_tickets`.`id` = `glpi_groups_tickets_c6f7f58b9365babf7388e555e526efd5`.`tickets_id`
                                                  AND `glpi_groups_tickets_c6f7f58b9365babf7388e555e526efd5`.`type` = '2' ) LEFT JOIN `glpi_ticketvalidations`
                                             ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id`
                                                 ) WHERE `glpi_tickets`.`is_deleted` = '0' AND  NOT (`glpi_tickets`.`id` IN ('132223')) AND (((`glpi_tickets`.`name` LIKE '%error a statistic%') OR (`glpi_tickets`.`name` LIKE '%error a statistic%') OR (`glpi_tickets`.`id` LIKE '%error a statistic%') OR (`glpi_tickets`.`id` LIKE '%error a statistic%'))) AND ( `glpi_tickets_users_019878060c6d5f06cbe3c4d7c31dec24`.users_id = 'xxxxx'
                                    OR `glpi_tickets_users_9c6b5b644d74a9e8013c7c2ea051dffd`.users_id = 'xxxxx'
                                    OR `glpi_tickets`.`users_id_recipient` = 'xxxxx' OR `glpi_groups_tickets_019878060c6d5f06cbe3c4d7c31dec24`.`groups_id`
                                             IN (59,87) OR `glpi_groups_tickets_9c6b5b644d74a9e8013c7c2ea051dffd`.`groups_id`
                                             IN (59,87) OR `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.users_id = '33664'  OR `glpi_tickets_users_c6f7f58b9365babf7388e555e526efd5`.`users_id` = 'xxxxx' OR `glpi_groups_tickets_c6f7f58b9365babf7388e555e526efd5`.`groups_id`
                                             IN (59,87) OR `glpi_tickets`.`status`='1' OR `glpi_ticketvalidations`.`users_id_validate`
                                          = '33664')  ORDER BY `glpi_tickets`.`name` LIMIT 100


I don't know if this informations can help to reduce the time of the quey.

**Comment by CDG47** [comment]
We did a test, when we want link a ticket with previously selected an entity in the tree, it's fast but if we want link tickets which depend on different entities, it's extremely slow. With the version 10.0.12, the users have not reported any problems.

**Comment by nuria2c** [comment]
We have only 1 entity. In our case the ticket could depend of more than one group. May be this is the reason.

**Comment by Blank-Vcf** [comment]
same here after update to 10.0.15, while searching for ticket to link searches are made letter by letter while tipping in form and query are never kill
![image](https://github.com/glpi-project/glpi/assets/16317786/16484ea5-5892-4be2-a056-9b8de1964486)
by the way the basic query itself run in ~7-8s
 	
SELECT DISTINCT `glpi_tickets`.* 
FROM `glpi_tickets` 
WHERE `glpi_tickets`.`is_deleted` = '0' AND  NOT (`glpi_tickets`.`id` IN ('336682')) AND (((`glpi_tickets`.`name` LIKE '%sinistre%') OR (`glpi_tickets`.`name` LIKE '%sinistre%') OR (`glpi_tickets`.`id` LIKE '%sinistre%') OR (`glpi_tickets`.`id` LIKE '%sinistre%'))) 
ORDER BY `glpi_tickets`.`entities_id`, `glpi_tickets`.`name` LIMIT 100

on table with ~278000 lines.

same on prod and dev, install on prod dedicated has own mariadb server

**Comment by cedric-anne** [comment]
Could you check the result of the `bin/console db:check` command and see if there is missing indexes on the `glpi_tickets` table ?

**Comment by cedric-anne** [comment]
I just checked and indexes cannot be used here, due to the usage of the `%` operator in the begining of the searched value.

From https://mariadb.com/kb/en/like/
> MariaDB can use indexes for LIKE on string columns in the case where the LIKE **_doesn't start with %_** or _.

**Comment by Blank-Vcf** [comment]
/var/www/glpi# bin/console db:check
Le schéma diffère pour la table "glpi_items_disks".
--- Schéma de base de données attendu
+++ Schéma de base de données actuel
@@ @@
   `encryption_type` varchar(255),
   `entities_id` int NOT NULL DEFAULT 0,
   `filesystems_id` int NOT NULL DEFAULT 0,
-  `freesize` bigint NOT NULL DEFAULT 0,
+  `freesize` int NOT NULL DEFAULT 0,
   `is_deleted` tinyint NOT NULL DEFAULT 0,
   `is_dynamic` tinyint NOT NULL DEFAULT 0,
   `items_id` int NOT NULL DEFAULT 0,
@@ @@
   `itemtype` varchar(255),
   `mountpoint` varchar(255),
   `name` varchar(255),
-  `totalsize` bigint NOT NULL DEFAULT 0,
+  `totalsize` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),

should not affect ticket problem

**Comment by trasher** [comment]
@Blank-Vcf that issue is already solved, and is entirely out of context here.
