### ISSUE TITLE
[9.1.2] Can't update SLT on tickets in child entities

### ISSUE THREAD

**Issue by CoolGoat** [glpi-project/glpi#1688]
Hi,

Followup from this issue : https://github.com/glpi-project/glpi/issues/1313
I can assign a SLT on ticket creation, which was not possible in 9.1.1, but not update SLT on tickets in child entities.
The "clock" button is only available in root entity, although the SLT is applied on child entities.
This has been tested on a fresh install as well.

![missing slt](https://cloud.githubusercontent.com/assets/25319013/22241932/bd523588-e221-11e6-8279-113ec7f95798.png)
![root slt](https://cloud.githubusercontent.com/assets/25319013/22241935/bf5e7d32-e221-11e6-99d4-13d9cfae0581.png)
![slt on child entities](https://cloud.githubusercontent.com/assets/25319013/22241938/c12d1a38-e221-11e6-99df-612fbc8277f2.png)

Thank you

**Comment by peraun** [comment]
In the #1313 I didn't see your post before posting. I've the same problem, and if you need you could use the information and images I posted there to report the problem. My comment: https://github.com/glpi-project/glpi/issues/1313#issuecomment-274787165
