### ISSUE TITLE
PHP Version warning banner

### ISSUE THREAD

**Issue by Alemmi** [glpi-project/glpi#16886]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Hi!
In the latest version, a banner warns the user to update his PHP version (because of the EOL).

For our customer, we set up an RHEL 8 machine, and in this environment, PHP 7.4 is the LTS version (based on [this](https://access.redhat.com/support/policy/updates/rhel-app-streams-life-cycle#rhel8_application_streams))

Then we want to ask if adding a setting to hide this banner is possible because we have not planned a PHP update in a short period of time.

Thanks for understanding

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.14 (/glpi => /usr/share/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux REDACTED 4.18.0-513.18.1.el8_9.x86_64 #​1 SMP Thu Feb 1 03:51:05 EST 2024 x86_64
PHP 7.4.33 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.39-MariaDB
	Server SQL Mode: REDACTED
	Parameters: REDACTED
	Host info: REDACTED via TCP/IP
	
PHP version (7.4.33) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.3.39) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to REDACTED/glpi/data/_cache has been validated.
Write access to REDACTED/glpi/data/_cron has been validated.
Write access to REDACTED/glpi/data has been validated.
Write access to REDACTED/glpi/data/_dumps has been validated.
Write access to REDACTED/glpi/data/_graphs has been validated.
Write access to REDACTED/glpi/data/_lock has been validated.
Write access to REDACTED/glpi/data/_pictures has been validated.
Write access to REDACTED/glpi/data/_plugins has been validated.
Write access to REDACTED/glpi/data/_rss has been validated.
Write access to REDACTED/glpi/data/_sessions has been validated.
Write access to REDACTED/glpi/data/_tmp has been validated.
Write access to REDACTED/glpi/data/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.
PHP 7.4 is no longer maintained by its community.
Even if GLPI still supports this PHP version, an upgrade to a more recent PHP version is recommended.
Indeed, this PHP version may contain unpatched security vulnerabilities.
Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/usr/share/glpi"
GLPI_CONFIG_DIR: "REDACTED/glpi/conf"
GLPI_VAR_DIR: "REDACTED/glpi/data"
GLPI_MARKETPLACE_DIR: "REDACTED/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "REDACTED/glpi/data"
GLPI_CACHE_DIR: "REDACTED/glpi/data/_cache"
GLPI_CRON_DIR: "REDACTED/glpi/data/_cron"
GLPI_DUMP_DIR: "REDACTED/glpi/data/_dumps"
GLPI_GRAPH_DIR: "REDACTED/glpi/data/_graphs"
GLPI_LOCAL_I18N_DIR: "REDACTED/glpi/data/_locales"
GLPI_LOCK_DIR: "REDACTED/glpi/data/_lock"
GLPI_LOG_DIR: "REDACTED/glpi/data/_log"
GLPI_PICTURE_DIR: "REDACTED/glpi/data/_pictures"
GLPI_PLUGIN_DOC_DIR: "REDACTED/glpi/data/_plugins"
GLPI_RSS_DIR: "REDACTED/glpi/data/_rss"
GLPI_SESSION_DIR: "REDACTED/glpi/data/_sessions"
GLPI_TMP_DIR: "REDACTED/glpi/data/_tmp"
GLPI_UPLOAD_DIR: "REDACTED/glpi/data/_uploads"
GLPI_INVENTORY_DIR: "REDACTED/glpi/data/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/usr/share/glpi/locales"
GLPI_VERSION: "10.0.14"
GLPI_SCHEMA_VERSION: "10.0.14@8f13530f7cf0fb07add30ae20013f0374956795b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version REDACTED in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version REDACTED in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version REDACTED in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version REDACTED in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 in (/usr/share/glpi/vendor/symfony/polyfill-php80)
symfony/polyfill-php81 in (/usr/share/glpi/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/usr/share/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/usr/share/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/usr/share/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	

</pre></details>

**Comment by trasher** [comment]
It is not possible to hide those messages, but they're displayed only on admin home page.
Since you plan an update soon, they'll disappear soon as well :)

**Comment by trasher** [comment]
Note you can hide all central message setting `GLPI_CENTRAL_WARNINGS` constant to `0` in you local config, "at your own risk".
