### ISSUE TITLE
Soucis dans les profils

### ISSUE THREAD

**Issue by ropie** [glpi-project/glpi#169]
Hello,
Dans un profil, j’enlève tous les droits sur la partie changement. A la sauvegarde ceux-ci reviennent.
Si j’enlève manuellement tous les droits (sans passer par la cas Sélectionner tous), a la sauvegarde, les droits sur les notes  et celui "Valider" se recochent tout seul.
Dans tous les cas, dans le profil concerné, on a toujours accès à la partie changement.

GLPI 0.85.5
Merci.

**Comment by orthagh** [comment]
Bonjour.
il est préférable d'utiliser cet espace en anglais.
Si vous préférez utiliser le français pour vos retour de bugs, le [forum](http://forum.glpi-project.org/) permet cela.

Cela dit, votre version de glpi serait un plus pour vous aider.

**Comment by yllen** [comment]
J'ai solutionné ce problème avec https://github.com/glpi-project/glpi/issues/180
