### ISSUE TITLE
When a user reply to its own email, it creates a new ticket instead of adding a followup

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#16903]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.14

### Bug description

Hello,

It's a common issue here, a lot of time users reply to their own emails (the collector email is in cc field) to add more infos or because the notification hasn't arrived yet.
Instead of adding a followup it opens a new ticket even if the original ticket is still opened.

The GLPI id is present in the subject field.

It generates a lot of fake tickets and sometime errors because informations end up in different tickets instead of being followups.

### Relevant log output

```shell
There is none.
```

### Steps To reproduce

1. Send an email to the collector address.
2. Wait ticket for being created.
3. Reply to the mail sent to the collector address.

**Comment by sebma** [comment]
@trasher #16813 is related but are you certain this is a duplicate ?

Also related : #8457

Does anyone know how to prevent GLPI from recreating a ticket when a reply-all is done with the collector email in CC ?
