### ISSUE TITLE
Strange behavior for $options in pre/post_item_form hooks in helpdesk form

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1691]
Hello,
We can see this in Ticket::showFormHelpdesk():

```
if (count($delegating) || $CFG_GLPI['use_check_pref']) {
         echo "<div class='center'><table class='tab_cadre_fixe'>";

         Plugin::doHook("pre_item_form", ['item' => $this, 'options' => &$opt]);
      }
```

First question: why is the hook inside the test of delegating or check_pref? Should it be outside of the test?

second question:

`      Plugin::doHook("post_item_form", ['item' => $this, 'options' => &$options]);`

why the $opt (from the 'pre_item_form') is not passed to the 'post_item_form', but another array which has nothing to do with the first one?

regards,
Tomolimo

**Comment by trasher** [comment]
First answer: I don't know, I'll have to check that.

Second answer: sounds like a copy/paste issue or something similar :)

**Comment by trasher** [comment]
It has also been reported that one of the post hook in tickets is called after the submit button.

**Comment by trasher** [comment]
See PR. I've move pre and post hooks; and I've removed both `$opt` and `$options` since they are not display options we're waiting for as far as I can see.
