### ISSUE TITLE
Can't find computers having 2 softwares

### ISSUE THREAD

**Issue by FrenchHope** [glpi-project/glpi#16919]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.14

### Bug description

I can't find computers having 2 software like Firefox AND Chrome with global rules on software name.
There is no result.
It seems to work for a query like Firefox OR Chrome.

### Steps To reproduce

Go to computers,
create 2 global rules criteria search on software : name
One with software 1
The other with software 2
using AND operator

**Comment by keguira** [comment]
Did some tests.

**UC1** : 
- 'Software' 'Characteristics - Name' 'contains' 'firefox'
- AND 'Software' 'Characteristics - Name' 'contains' 'chrome'

Returns : nothing

**UC2** : 
- 'Software' 'Characteristics - Name' 'contains' 'firefox'
- OR 'Software' 'Characteristics - Name' 'contains' 'chrome'

Returns : computers with one or the other or both

**UC3** : 
- 'Software' 'Characteristics - Name' 'contains' 'firefox'
- OR 'Software' 'Characteristics - Name' 'contains' 'ESR'

Returns : computers with any variation of firefox ESR
The search query aggregate the search query for _a same entry_. Also confirmed by another test where I use an other attribute of the software (editor or version)

**UC4** : trying to use the grouping system to force to look for multiple software entries on same computer

- Group  
  - 'Software' 'Characteristics - Name' 'contains' 'firefox'
- AND Group 
  - 'Software' 'Characteristics - Name' 'contains' 'chrome'

Returns : nothing.

**Comment by FrenchHope** [comment]
Thanks. I tried grouping system too.
