### ISSUE TITLE
Calculating profiles during login process removes all dynamic profiles of the user

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#16936]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.15-dev

### Bug description

Hello,

Some days ago I applied last commits from the bugfixes branch and I obseved that users with only dynamic profiles calculated from their groups stop connecting to GLPI. After some investigations, it appeared that the reason was that peoples dynamic profiles were deleted during the login process. Some debugging allowed me to see that the applyRightRules User's function were called twice, the first time during authentication, and the second time while getAuthToken. When I checked https://github.com/glpi-project/glpi/pull/16881, I found that a property called "must_process_ruleright" was introduced. I suppose that it was done in order to control if right rules should really be applied. But it seems that nothing switch it back to false. So on the first call, profile rights are updated in the DB, and on the second call they are removed. If the property is disabled at the end of the first processing, the second call would not do anything, so user would keep his profile rights...

```diff
--- User.php.orig       2024-04-16 10:28:48.495096498 +0200
+++ User.php    2024-04-16 10:29:47.579855251 +0200
@@ -1363,6 +1363,7 @@ class User extends CommonDBTM
                     $right->delete($db_profile);
                 }
             }
+           $this->must_process_ruleright = false;
         }
         return $return;
     }
```

### Relevant log output

```shell
Backtrace :
  src/User.php:1198                                  User->applyRightRules()
  src/CommonDBTM.php:1747                            User->post_updateItem()
  src/Auth.php:1031                                  CommonDBTM->update()
  front/login.php:94                                 Auth->login()
  public/index.php:82                                require()

Backtrace :
  src/User.php:1198                                  User->applyRightRules()
  src/CommonDBTM.php:1747                            User->post_updateItem()
  src/User.php:5951                                  CommonDBTM->update()
  src/Auth.php:1094                                  User->getAuthToken()
  front/login.php:94                                 Auth->login()
  public/index.php:82                                require()
```

**Comment by trasher** [comment]
Indeed, thank for the investigation, and the proposed solution that seems perfectly correct. I've proposed it in #16937
