### ISSUE TITLE
Error parsing date.timezone (php.ini)

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi#16939]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

When setting the date.timezone PHP directive like this:

```
[Date]
date.timezone = America/Sao_Paulo ; // https://www.php.net/manual/pt_BR/timezones.php
```

And setting up GLPI on a new database, the following error is thrown:

### Relevant log output

```shell
[2024-04-16 12:42:14] glpiphplog.WARNING:   *** PHP Warning (2): date(): Invalid date.timezone value 'America/Sao_Paulo ; // https://www.php.net/manual/pt_BR/timezones.php', we selected the timezone 'UTC' for now. in /home/robertinho/public_html/glpi/src/Session.php at line 236
  Backtrace :
  src/Session.php:236                                date()
  install/install.php:519                            Session::start()
  public/index.php:82                                require()
```

### Page URL

https://glpi.example.com/install/install.php

### Steps To reproduce

1. Start a new GLPI installation with a new (clean) DB.

### Anything else?

Doesn't matter if string is quoted or not (e.g. 'America/Sao_Paulo'), the same error is being thrown. If double quoted (e.g. "America/Sao_Paulo"), a "500 Internal Server Error" is thrown.

**Comment by trasher** [comment]
This issue is system side, not related to GLPI.
