### ISSUE TITLE
Undefined array key "order_ref" in /var/www/html/glpi/marketplace/consumables/inc/field.class.php

### ISSUE THREAD

**Issue by mfrakka** [glpi-project/glpi#16944]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

 After upgrading from 10.0.12 we notice that modifying an item in our consumable inventory the field "name" on table "glpi.glpi_consumableitems" is overwritten by the value of field "Order reference".
 Apache logs report messages about 'Undefined array key "order_ref"'

### Relevant log output

```shell
`[php:warn] [pid 106627] [client 172.29.58.80:34682] PHP Warning:  Undefined array key "order_ref" in /var/www/html/glpi/marketplace/consumables/inc/field.class.php on line 110, referer: http://www.mydomain.it/front/consumableitem.form.php?id=7`
```

### Page URL

/front/consumableitem.form.php

### Steps To reproduce

1. Home -> Assets -> Consumables
2. Search for any item in your inventory. With debug enabled we got the error "PHP User Warning (512): Duplicate keys found in search options for item type ConsumableItem: 1, 2 in /var/www/html/glpi/src/Search.php at line 8346" but this seems to be harmless.
3. Select the item to edit its properties.
4. Save the tab, even if no modifications was made.

![pre](https://github.com/glpi-project/glpi/assets/52761303/ebbbf06d-957e-4240-a39d-838e038d24fb)
![while](https://github.com/glpi-project/glpi/assets/52761303/48a0b7b3-3aeb-4980-aea9-8665bf048012)
![after](https://github.com/glpi-project/glpi/assets/52761303/71205d29-349f-4c10-9cfc-13ce6da65b61)

**Comment by cconard96** [comment]
This seems like a bug with the consumables plugin. We only track GLPI bugs here.

**Comment by cconard96** [comment]
https://github.com/InfotelGLPI/consumables/issues

**Comment by trasher** [comment]
`in /var/www/html/glpi/marketplace/consumables/inc/field.class.php on line 110`

Issue is coming from plugin code. Probably from PHP version.
