### ISSUE TITLE
Doesn't assign a technician to a ticket when a ticket is submitted via email

### ISSUE THREAD

**Issue by krzysztofmaciejewskiit** [glpi-project/glpi#16955]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

I have a problem because I am configuring GLPI as a new ticketing system for the company I work for, but the tickets are not being assigned to users using the round-robin method.

When the ticket is created from GLPI and when I manually select the category then everything works correct, the ticket goes to my group and the technician is randomly assigned.
When I do it by email from my mail only the main unit is assigned thanks to the rule I posted below.

I don't know how to do this, but maybe you know how to assign categories to tickets submitted by email?

![image](https://github.com/glpi-project/glpi/assets/128192435/752b46f0-556c-4d1b-ab44-f8242d3ab8d6)

![image](https://github.com/glpi-project/glpi/assets/128192435/9e6b87ea-c527-4682-b288-338701bd3fb2)

![image](https://github.com/glpi-project/glpi/assets/128192435/847aa73b-ad3f-42bf-b241-9daba9bb5ed8)

I think the problem may be in the screen shot below (Automatic user assignment), just don't know how I can configure it.
![image](https://github.com/glpi-project/glpi/assets/128192435/ae81224a-63c2-41b0-8a58-e3180a945eab)

I noticed that when this option is selected, when you create the request yourself and manually select the cateogry, then it all works correctly with assignment to users by round robin method.
![image](https://github.com/glpi-project/glpi/assets/128192435/2832bee9-b2b4-48fc-936d-0bcc9eccd41b)

![image](https://github.com/glpi-project/glpi/assets/128192435/a2005c0f-217d-4b3f-8d96-f097685b3abb)

**Comment by cedric-anne** [comment]
Hi,

The problem seems to be located in the RoundRobin plugin. Please open the issue on the plugin repository: https://github.com/initiativa/roundrobin.
