### ISSUE TITLE
"URL of the application"

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#16963]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

In version 10.0.10 I have the "URL of the application" field blank since I access from 2 different URLs. I'm testing with version 10.0.14 and I see that with the "URL of the application" field empty, the pages do not load, they remain blank, but the menus do appear. Have there been any changes? 
![image](https://github.com/glpi-project/glpi/assets/56876938/c3376c8d-4814-4488-badb-3c3bf1968450)

and with the URL of the application: 
![image](https://github.com/glpi-project/glpi/assets/56876938/31b78848-979f-44ba-bc91-bf968b185978)

Thanks.

### Steps To reproduce

To reproduce the issue, you just need to leave the "URL of the application" field blank on the General tab.

### Your GLPI setup information

10.0.14

**Comment by trasher** [comment]
As far as I remember, configuration URL is required for a while; leaving it blank should not have been allowed.

**Comment by AlexTR85** [comment]
To maintain my current functionality, do I just need to leave this as it was before?
https://github.com/glpi-project/glpi/pull/16965/commits/70f1cf728a799eaa2597d1c6a5f7947b3c7d7869

**Comment by trasher** [comment]
This will cause other issues.

As said, URL should not be leaved blank; GLPI does not expect that, and it will no longer be allowed in next major release.

**Comment by trasher** [comment]
(also, fix proposed in related PR is  probably better)

**Comment by AlexTR85** [comment]
@trasher I don't understand what you mean? Will it still be possible to maintain access from more than 1 URL/domain?

**Comment by trasher** [comment]
On GLPI 10, yes. On GLPI 11, no.

**Comment by AlexTR85** [comment]
I have 2 URLs/domains, is there an option to create a plugin or something?

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
