### ISSUE TITLE
Permission conflict between "APPROVE SOLUTION/REPLY SURVEY (MY TICKET)" option and "LIFE CYCLE OF TICKETS" restricion

### ISSUE THREAD

**Issue by fixwhat** [glpi-project/glpi#16973]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

If a tecnician has a restriction on "LIFE CYCLE OF TICKETS" that blocks him from closing a ticket like:

![image](https://github.com/glpi-project/glpi/assets/22347308/01ec6df3-cadb-4df5-8016-fffed4cc5b78)

GLPI ignores the option described in Profile > Assistance > APPROVE SOLUTION/REPLY SURVEY (MY TICKET):

![image](https://github.com/glpi-project/glpi/assets/22347308/ad40e980-7906-4fdb-b806-40fcc760a221)

What would be expected:
- Tecnician cannot close a ticket from another user, but could close a ticket that he opened himself

What actually happens:
- GLPI doesn't aloud the tecnician to approve a ticket that he himself opened 

### Steps To reproduce

1. Configure the tecnician profile in "LIFE CYCLE OF TICKETS" to not move a ticket do closed, only solved (see first image above)
2. Configure the tecnician profile in Profile > Assistance > APPROVE SOLUTION/REPLY SURVEY (MY TICKET) to yes  (see second image above)
3.  Tecnician '1' opens a ticket and assigns to another tecnician '2'
4. Tecnician '2' offers a sollution to the problem 
5. Tecnician '1' cannot approve or interact with the ticket: 

![image](https://github.com/glpi-project/glpi/assets/22347308/3e4f1865-0895-49bb-87c6-2db9f5c95b22)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.10 ( => /mnt/files/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux SRV-047 6.5.0-26-generic #​26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64
PHP 8.2.17 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at xxx.xxxx.xx.xxx.xxPort 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.36-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: sa@xxxxxx
        Host info: xxx
	
PHP version (8.2.17) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.36) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /mnt/files/glpi/../files/_cache has been validated.
Write access to /mnt/files/glpi/../config has been validated.
Write access to /mnt/files/glpi/../files/_cron has been validated.
Write access to /mnt/files/glpi/../files has been validated.
Write access to /mnt/files/glpi/../files/_dumps has been validated.
Write access to /mnt/files/glpi/../files/_graphs has been validated.
Write access to /mnt/files/glpi/../files/_lock has been validated.
Write access to /mnt/files/glpi/../files/_pictures has been validated.
Write access to /mnt/files/glpi/../files/_plugins has been validated.
Write access to /mnt/files/glpi/../files/_rss has been validated.
Write access to /mnt/files/glpi/../files/_sessions has been validated.
Write access to /mnt/files/glpi/../files/_tmp has been validated.
Write access to /mnt/files/glpi/../files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /mnt/files/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/mnt/files/glpi"
GLPI_CONFIG_DIR: "/mnt/files/glpi/../config"
GLPI_VAR_DIR: "/mnt/files/glpi/../files"
GLPI_MARKETPLACE_DIR: "/mnt/files/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_DOC_DIR: "/mnt/files/glpi/../files"
GLPI_CACHE_DIR: "/mnt/files/glpi/../files/_cache"
GLPI_CRON_DIR: "/mnt/files/glpi/../files/_cron"
GLPI_DUMP_DIR: "/mnt/files/glpi/../files/_dumps"
GLPI_GRAPH_DIR: "/mnt/files/glpi/../files/_graphs"
GLPI_LOCAL_I18N_DIR: "/mnt/files/glpi/../files/_locales"
GLPI_LOCK_DIR: "/mnt/files/glpi/../files/_lock"
GLPI_LOG_DIR: "/mnt/files/glpi/../files/_log"
GLPI_PICTURE_DIR: "/mnt/files/glpi/../files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/mnt/files/glpi/../files/_plugins"
GLPI_RSS_DIR: "/mnt/files/glpi/../files/_rss"
GLPI_SESSION_DIR: "/mnt/files/glpi/../files/_sessions"
GLPI_TMP_DIR: "/mnt/files/glpi/../files/_tmp"
GLPI_UPLOAD_DIR: "/mnt/files/glpi/../files/_uploads"
GLPI_INVENTORY_DIR: "/mnt/files/glpi/../files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/mnt/files/glpi/locales"
GLPI_VERSION: "10.0.10"
GLPI_SCHEMA_VERSION: "10.0.10"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2023"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/mnt/files/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/mnt/files/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/mnt/files/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/mnt/files/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/mnt/files/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/mnt/files/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/mnt/files/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/mnt/files/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/mnt/files/glpi/vendor/sabre/http/lib)
sabre/uri in (/mnt/files/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/mnt/files/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/mnt/files/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/mnt/files/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/mnt/files/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/mnt/files/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/mnt/files/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/mnt/files/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/mnt/files/glpi/vendor/symfony/console)
scssphp/scssphp in (/mnt/files/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/mnt/files/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/mnt/files/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/mnt/files/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/mnt/files/glpi/vendor/ramsey/uuid/src)
psr/log in (/mnt/files/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/mnt/files/glpi/vendor/psr/simple-cache/src)
psr/cache in (/mnt/files/glpi/vendor/psr/cache/src)
league/csv in (/mnt/files/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/mnt/files/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/mnt/files/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/mnt/files/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/mnt/files/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/mnt/files/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/mnt/files/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/mnt/files/glpi/vendor/symfony/cache)
html2text/html2text in (/mnt/files/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/mnt/files/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/mnt/files/glpi/vendor/symfony/dom-crawler)
twig/twig in (/mnt/files/glpi/vendor/twig/twig/src)
twig/string-extra in (/mnt/files/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/mnt/files/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/mnt/files/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/mnt/files/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/mnt/files/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>LDAP directories</summary><pre> 

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (anonymous@xxxxs)

</pre></details><details><summary>Plugins list</summary><pre> 
	advancedplanning     Name: advancedplanning               Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alertas                        Version: 1.12.2     State: Enabled                                 
		Install Method: Marketplace
	fields               Name: Campos adicionais              Version: 1.20.7     State: Installed / not activated               
		Install Method: Marketplace
	behaviors            Name: Comportamentos                 Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	escalade             Name: Escalonamento                  Version: 2.9.2      State: Installed / not activated               
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.6     State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.0.4.1    State: Enabled                                 
		Install Method: Manual
	gappessentials       Name: Gapp Essentials                Version: 2.3.0      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.4      State: Enabled                                 
		Install Method: Marketplace
	itilcategorygroups   Name: Grupos ItilCategory            Version: 2.5.1      State: Installed / not activated               
		Install Method: Marketplace
	datainjection        Name: Importação de dados            Version: 2.13.2     State: Installed / not activated               
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Installed / not activated               
		Install Method: Marketplace
	mreporting           Name: Mais Relatórios                Version: 1.8.6      State: Installed / not activated               
		Install Method: Marketplace
	satisfaction         Name: Mais satisfação                Version: 1.6.2      State: Enabled                                 
		Install Method: Marketplace
	metademands          Name: Meta-Demands                   Version: 3.3.2      State: Installed / not activated               
		Install Method: Marketplace
	dashboard            Name: Painel                         Version: 1.0.3      State: Enabled                                 
		Install Method: Manual
	taskdrop             Name: TaskDrop                       Version: 2.0.0      State: Installed / not activated               
		Install Method: Marketplace
	vip                  Name: VIP                            Version: 1.8.2      State: Enabled                                 
		Install Method: Marketplace

</pre></details><details><summary>Locales overrides</summary><pre></pre></details>

**Comment by trasher** [comment]
Please try with latest stable release.

**Comment by fixwhat** [comment]
> Please try with latest stable release.

Just did. Same behaviour:
![image](https://github.com/glpi-project/glpi/assets/22347308/89e5b148-7d36-449e-a8fa-7fe8d88a11b4)

**Comment by fixwhat** [comment]
I still consider this a bug, since it refers to confliting permissions, and don't think this should be considered stale.
