### ISSUE TITLE
Planning not loading - Minor bug

### ISSUE THREAD

**Issue by PandaRoux8** [glpi-project/glpi#16979]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

The planning is not loading properly

![2024-04-23 10_06_07-Planning - GLPI](https://github.com/glpi-project/glpi/assets/13942083/d3e84637-7974-491d-b3b2-45b4c92848b7)

## Workaround

- Click on the refresh

## Idea

As the screenshot above shows, it seems like resourceTimeline is not loaded properly.
When the page is fully loaded and you click refresh it works fine.

### Relevant log output

```shell
Chrome JS Console :

Plugin file not loaded for resourceTimeline
refinePluginDefs @ VM776:4566
Calendar.addPluginInputs @ VM776:6615
Calendar @ VM776:6605
display @ planning.min.js?v=9b0a1839675c4ebc3932fbf2eba2602ca72afb8c:33
(anonymous) @ unknown
u @ base.min.js?v=9b0a1839675c4ebc3932fbf2eba2602ca72afb8c:186
c @ base.min.js?v=9b0a1839675c4ebc3932fbf2eba2602ca72afb8c:186
```

### Page URL

https://glpi.lcb-info.ch:8445/front/planning.php

### Steps To reproduce

1. Go to `Assistance` - `Planning`
2. The planning doesn't load

### Anything else?

Tested on : Chrome Version 123.0.6312.124 (Build officiel) (64 bits) and Edge

**Comment by cconard96** [comment]
Fixed by #16788. Will be included with GLPI 10.0.15.
