### ISSUE TITLE
Booking tool. Calendar time error

### ISSUE THREAD

**Issue by Marat-209** [glpi-project/glpi#16978]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Booking tool. Calendar time error. The red line is always 3 hours behind
![de20ba3a-23b8-496e-8e1e-5cb17a5b1c01](https://github.com/glpi-project/glpi/assets/130477764/a86f7720-0428-4fb0-a9aa-1182cb76021c)

### Relevant log output

```shell
Good afternoon colleagues. Which day I can’t solve the problem with displaying the red line on the booking calendar. The red line should show the current time but it is always 3 hours lower. The time zone settings are configured the same everywhere (in GLPI.php.web hosting). Tried other time zones, reboot.
```

### Your GLPI setup information

Operating system: Linux isp.++++ 5.4.0-172-generic #​190-Ubuntu SMP Fri Feb 2 23:24:22 UTC 2024 x86_64
PHP 8.1.19 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, session, shmop, soap, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc,
	xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="2048M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M"
	disable_functions="pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,"
	
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at support+++++++ Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.36-0ubuntu0.20.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpidb
	Host info: Localhost via UNIX socket

**Comment by cedric-anne** [comment]
Hi,

This issue has been fixed recently (see #16931) and the fix will be part of GLPI 10.0.15 that should be released tomorrow.

Duplicates #15929.
