### ISSUE TITLE
Aruba AP iftype 188 (NetworPortWifi) isn't being imported

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi#16981]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

When NetInventory Aruba AP devices, no Radio is being shown on "Network ports" tab, as they seems to be reported as ``iftype`` 188 which isn't importable by default as seem in ``glpi_networkporttypes`` table. It would also be needy to update ``/src/NetworkPortType.php`` to consider ``188`` iftype as an importable NetworkPortWifi and create a migration DB script to change it's value as importable during GLPI 10.0.14 -> 10.0.15.

The expectation is that GLPI UI could import and show Aruba AP Radio interfaces on "Network ports" device tab without having to set the iftype ``188`` as importable, as it should already be importable by default, as it is the ``iftype`` which Aruba devices reports its Radios (SSIDs) by default and there's already a MibSupport file on GLPI Agent side (``Aruba.pm``) to extend GLPI Agent support for Aruba devices, but it doesn't make any sense if it's gathered information isn't reported on GLPI UI at all.

### Page URL

https://glpi.rnetworks.com.br/front/inventory.conf.php

### Steps To reproduce

1. Do a NetInventory of an Aruba IAP Cluster member device.
2. WiFi Radio interfaces are reported as "``radioX_ssid_idX``" but they aren't shown/imported by GLPI logic.

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.14 ( => /home/robertinho/public_html/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux cloud.ifantasy.srv.br 3.10.0-962.3.2.lve1.5.26.2.el7.x86_64 #​1 SMP Tue Jul 23 08:31:06 EDT 2019 x86_64
PHP 8.1.27 litespeed (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, bcmath, ctype, curl, date, dom, exif, fileinfo,
	filter, ftp, gd, gettext, hash, i360, iconv, imagick, imap, intl, ionCube Loader, json, ldap, libxml, litespeed, mbstring,
	memcached, mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, readline, session, soap,
	sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="300M" safe_mode="" session.save_handler="files"
	upload_max_filesize="300M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Server Software: MySQL Community Server - (GPL)
	Server Version: 5.7.30-cll-lve
	Server SQL Mode: 
	Parameters: robertinho_glpi@localhost/robertinho_glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.1.27) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.30) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/robertinho/glpi/files/_cache has been validated.
Write access to /home/robertinho/glpi/files/_cron has been validated.
Write access to /home/robertinho/glpi/files has been validated.
Write access to /home/robertinho/glpi/files/_dumps has been validated.
Write access to /home/robertinho/glpi/files/_graphs has been validated.
Write access to /home/robertinho/glpi/files/_lock has been validated.
Write access to /home/robertinho/glpi/files/_pictures has been validated.
Write access to /home/robertinho/glpi/files/_plugins has been validated.
Write access to /home/robertinho/glpi/files/_rss has been validated.
Write access to /home/robertinho/glpi/files/_sessions has been validated.
Write access to /home/robertinho/glpi/files/_tmp has been validated.
Write access to /home/robertinho/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: Phar, zip.
Following extensions are not present: bz2.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /home/robertinho/public_html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/robertinho/public_html/glpi"
GLPI_CONFIG_DIR: "/home/robertinho/glpi"
GLPI_VAR_DIR: "/home/robertinho/glpi/files"
GLPI_LOG_DIR: "/home/robertinho/glpi/files/_log"
GLPI_MARKETPLACE_DIR: "/home/robertinho/public_html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/home/robertinho/glpi/files"
GLPI_CACHE_DIR: "/home/robertinho/glpi/files/_cache"
GLPI_CRON_DIR: "/home/robertinho/glpi/files/_cron"
GLPI_DUMP_DIR: "/home/robertinho/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/home/robertinho/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/robertinho/glpi/files/_locales"
GLPI_LOCK_DIR: "/home/robertinho/glpi/files/_lock"
GLPI_PICTURE_DIR: "/home/robertinho/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/robertinho/glpi/files/_plugins"
GLPI_RSS_DIR: "/home/robertinho/glpi/files/_rss"
GLPI_SESSION_DIR: "/home/robertinho/glpi/files/_sessions"
GLPI_TMP_DIR: "/home/robertinho/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/home/robertinho/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/home/robertinho/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/home/robertinho/public_html/glpi/locales"
GLPI_VERSION: "10.0.14"
GLPI_SCHEMA_VERSION: "10.0.14@8f13530f7cf0fb07add30ae20013f0374956795b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/home/robertinho/public_html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/home/robertinho/public_html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/robertinho/public_html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/home/robertinho/public_html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/robertinho/public_html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/robertinho/public_html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/robertinho/public_html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/home/robertinho/public_html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/robertinho/public_html/glpi/vendor/sabre/http/lib)
sabre/uri in (/home/robertinho/public_html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/home/robertinho/public_html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/robertinho/public_html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/robertinho/public_html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/robertinho/public_html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/robertinho/public_html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/home/robertinho/public_html/glpi/vendor/symfony/console)
scssphp/scssphp in (/home/robertinho/public_html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/robertinho/public_html/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/home/robertinho/public_html/glpi/vendor/ramsey/uuid/src)
psr/log in (/home/robertinho/public_html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/robertinho/public_html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/home/robertinho/public_html/glpi/vendor/psr/cache/src)
league/csv in (/home/robertinho/public_html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/home/robertinho/public_html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/robertinho/public_html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/robertinho/public_html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/robertinho/public_html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/robertinho/public_html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/robertinho/public_html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/robertinho/public_html/glpi/vendor/symfony/cache)
html2text/html2text in (/home/robertinho/public_html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/home/robertinho/public_html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/robertinho/public_html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/home/robertinho/public_html/glpi/vendor/twig/twig/src)
twig/string-extra in (/home/robertinho/public_html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home/robertinho/public_html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/home/robertinho/public_html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/home/robertinho/public_html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/home/robertinho/public_html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Manual
	swcpuram             Name: Show CPU-Memory Network Device Version: 1.0.0      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

XML GLPI Agent inventory for Aruba AP:
[networkequipment_0_8.xml.txt](https://github.com/glpi-project/glpi/files/15076588/networkequipment_0_8.xml.txt)

snmpwalk file for Aruba AP:
[arubaiap.walk.txt](https://github.com/glpi-project/glpi/files/15083474/arubaiap.walk.txt)

**Comment by trasher** [comment]
I'm not sure I understand what you want. Aslo, a snmpwalk is useless for GLPI. Please provide an XML inventory file.

Also, types that are not "importable" an be configured your side.

**Comment by eduardomozart** [comment]
> I'm not sure I understand what you want. Aslo, a snmpwalk is useless for GLPI. Please provide an XML inventory file.
> 
> Also, types that are not "importable" an be configured your side.

Hello @trasher, I updated the issue description and provided the GLPI XML inventory file, which I would like to have provided when I opened this issue, but I was troubleshooting another issue on GLPI Agent side and there snmpwalk output is used so I think I got the things confused.

**Comment by trasher** [comment]
OK, thanks for the XML.

So you can just configure corresponding iftype on your instance, I do not see a bug.

**Comment by eduardomozart** [comment]
> OK, thanks for the XML.
> 
> So you can just configure corresponding iftype on your instance, I do not see a bug.

It isn't exactly a bug, it's only that GLPI should provide support for them as it's an iftype that is used for Radio types interfaces (Wifi) as reported by GLPI Agent itself. GLPI Agent reports them on XML but they isn't shown on GLPI UI, so the inventory do not seems full filed as it could be by default.

**Comment by trasher** [comment]
As I've said, I have no idea if changing defaults on this type is correct or not. I have no idea neither why it's disabled nor attached to any instance right now.

Anyway, if we change that, it will target GLPI 11.

**Comment by stonebuzz** [comment]
If I'm not mistaken, the port types can be added manually if required (glpi only offers a default list, which can be adapted to each context).

https://my_glpi/front/networkporttype.php

![image](https://github.com/glpi-project/glpi/assets/7335054/65cf02f9-d095-4a04-861c-1cc6af90b839)

**Comment by stonebuzz** [comment]
or update the existing one

![image](https://github.com/glpi-project/glpi/assets/7335054/a0c00f2a-045f-4ff8-abce-ade278118eaa)

**Comment by eduardomozart** [comment]
Hello @stonebuzz, yes, but it seems that Aruba AP returns iftype ``188`` which isn't imported by default even GLPI Agent reported them on the device XML Inventory file. I believe that by default such Radio interfaces should be imported by GLPI and shown in "Network port" tab of the Network device.

**Comment by g-bougard** [comment]
Indeed @stonebuzz is right, this port is available in "Network port types" dropdown and from there you can set it to be imported.

In our private snmpwalk database, I only see that port type used by Aruba devices.

I don't know if we have to translate it to wifi by default. But it can make sens for port connection as it says by definition MAC layer is used.

**Comment by eduardomozart** [comment]
Hello @g-bougard 
I believe that based on NetworkPortTypes default association (https://github.com/glpi-project/glpi/blob/10.0/bugfixes/src/NetworkPortType.php#L109), the WiFi one seems to be more suitable, as it would allows the user to provide more information that the sysadmin could provide related to those radios, like "Wifi protocol version" and "Wifi mode", and also associate a "Wifi network".

**Comment by trasher** [comment]
See #16995:
=> it targets GLPI 11
=> the change is only for new installations

Having a PR opened does not means it will be accepted and merged :)
