### ISSUE TITLE
[10.0.15 - "glpi_items_disks"] The database schema does not match that of the current GLPI version

### ISSUE THREAD

**Issue by Gor3pig** [glpi-project/glpi#16991]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

When updating to version 10.0.15 from version 10.0.14, this message appears:

_**The database schema does not conform to that of the current GLPI version. We recommend you run the command “php bin/console database:check_schema_integrity” to see the differences.**_

The database integrity test gives the following result:

```
`Le schéma diffère pour la table "glpi_items_disks".
--- Schéma de base de données attendu
+++ Schéma de base de données actuel
@@ @@
   `encryption_type` varchar(255),
   `entities_id` int NOT NULL DEFAULT 0,
   `filesystems_id` int NOT NULL DEFAULT 0,
-  `freesize` bigint NOT NULL DEFAULT 0,
+  `freesize` int NOT NULL DEFAULT 0,
   `is_deleted` tinyint NOT NULL DEFAULT 0,
   `is_dynamic` tinyint NOT NULL DEFAULT 0,
   `items_id` int NOT NULL DEFAULT 0,
@@ @@
   `itemtype` varchar(255),
   `mountpoint` varchar(255),
   `name` varchar(255),
-  `totalsize` bigint NOT NULL DEFAULT 0,
+  `totalsize` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),`
```

### Steps To reproduce

Just update to 10.0.15

**Comment by trasher** [comment]
Indeed, migration script has been copied in the wrong directory (10.0.4 to 10.0.5); and as our migrations tests are done on a version < 10.0.4, we do not detect the issue... 

You can either ignore, or manually change this column to bigint.

**Comment by GuidoWilden** [comment]
+1

**Comment by TechLoic** [comment]
Same issue here on two instances. What's the solution?

**Comment by cedric-anne** [comment]
> Same issue here on two instances. What's the solution? It's not risky to ignore it?

You can ignore it or manually fix the columns type in tghe database (`int` -> `bigint`).

**Comment by TechLoic** [comment]
> > Same issue here on two instances. What's the solution? It's not risky to ignore it?
> 
> You can ignore it or manually fix the columns type in tghe database (`int` -> `bigint`).

Ok, thank you. I've changed it via phpmyadmin, all is fine now.

**Comment by campolargo** [comment]
Is there an estimate of this being released?

**Comment by AnothUser** [comment]
any official fix ?

**Comment by Loweack** [comment]
When you look at the commit shown in the issue, it seems that they will fix it on the next release.

![image](https://github.com/glpi-project/glpi/assets/64659299/93ee488b-b5ab-4916-9eb9-11a588dfb26e)

**Comment by trasher** [comment]
This will be fixed on next release. As already said, you can either change the column type on your database, or just ignore the message.
