### ISSUE TITLE
Attribuer un technicien à une tâche de projet

### ISSUE THREAD

**Issue by robertdelamancha** [glpi-project/glpi#170]
Bonjour, 

It is  possible to add a tech on the task.

I add in the projecttask.class.php the code bellow

      echo "</td></tr>";
      echo "<td>Technicien</td><TD>";
      //User::dropdown(array('value' => $this->fields["tech_id"]));
      User::dropdown(array('name'   => 'tech_id',
                           'value'  => $this->fields["tech_id"],
                           'right'  => 'own_ticket',
                           'entity' => $this->fields["entities_id"]));

      echo "</td></tr>";

**Comment by tsmr** [comment]
You have already a tab for define the team for the task
