### ISSUE TITLE
Database Schema not consistent after Update to 10.0.15

### ISSUE THREAD

**Issue by EGSCOLEMAN** [glpi-project/glpi#17000]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

After upgrading from version 10.0.14 to 10.0.15 I received an error that my database  schema is not consistent with the current GLPI version.

Table schema differs for table "glpi_items_disks".
--- Expected database schema
+++ Current database schema
@@ @@
   `encryption_type` varchar(255),
   `entities_id` int NOT NULL DEFAULT 0,
   `filesystems_id` int NOT NULL DEFAULT 0,
-  `freesize` bigint NOT NULL DEFAULT 0,
+  `freesize` int NOT NULL DEFAULT 0,
   `is_deleted` tinyint NOT NULL DEFAULT 0,
   `is_dynamic` tinyint NOT NULL DEFAULT 0,
   `items_id` int NOT NULL DEFAULT 0,
@@ @@
   `itemtype` varchar(255),
   `mountpoint` varchar(255),
   `name` varchar(255),
-  `totalsize` bigint NOT NULL DEFAULT 0,
+  `totalsize` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),

### Your GLPI setup information

GLPI 10.0.15 ( => /var/www/glpi)
Installation mode: TARBALL
Current language:en_GB

**Comment by cedric-anne** [comment]
Duplicates #16991
