### ISSUE TITLE
GLPI server time zone shows in Setup > Authentication instead of Setup > General

### ISSUE THREAD

**Issue by litbea** [glpi-project/glpi#17004]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

GLPI server time zone should be located in Setup > General, instead of /front/auth.settings.php in my opinion.

### Page URL

/front/auth.settings.php

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.14 ( => /servicio/aplicacion/_materiales/glpi-10014)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux soporte.uva.es 5.15.0-205.149.5.1.el9uek.x86_64 #​2 SMP Fri Apr 5 11:29:36 PDT 2024 x86_64
PHP 8.0.30 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, sockets, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.57 (Oracle Linux Server) OpenSSL/3.0.7 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0
Server Software: MariaDB Server
	Server Version: 10.11.7-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_user@127.0.0.1/glpi_db
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.0.30) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.7) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /servicio/aplicacion/static-glpi-files/_cache has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_cron has been validated.
Write access to /servicio/aplicacion/static-glpi-files has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_dumps has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_graphs has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_lock has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_pictures has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_plugins has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_rss has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_sessions has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_tmp has been validated.
Write access to /servicio/aplicacion/static-glpi-files/_uploads has been validated.
PHP 8.0 is no longer maintained by its community.
Even if GLPI still supports this PHP version, an upgrade to a more recent PHP version is recommended.
Indeed, this PHP version may contain unpatched security vulnerabilities.
Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
GLPI data directories are located in a secured path.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /servicio/aplicacion/_materiales/glpi-10014/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/servicio/aplicacion/_materiales/glpi-10014"
GLPI_CONFIG_DIR: "/servicio/aplicacion/static-glpi-config/"
GLPI_VAR_DIR: "/servicio/aplicacion/static-glpi-files"
GLPI_LOG_DIR: "/servicio/aplicacion/static-glpi-logs"
GLPI_MARKETPLACE_DIR: "/servicio/aplicacion/_materiales/glpi-10014/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/servicio/aplicacion/static-glpi-files"
GLPI_CACHE_DIR: "/servicio/aplicacion/static-glpi-files/_cache"
GLPI_CRON_DIR: "/servicio/aplicacion/static-glpi-files/_cron"
GLPI_DUMP_DIR: "/servicio/aplicacion/static-glpi-files/_dumps"
GLPI_GRAPH_DIR: "/servicio/aplicacion/static-glpi-files/_graphs"
GLPI_LOCAL_I18N_DIR: "/servicio/aplicacion/static-glpi-files/_locales"
GLPI_LOCK_DIR: "/servicio/aplicacion/static-glpi-files/_lock"
GLPI_PICTURE_DIR: "/servicio/aplicacion/static-glpi-files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/servicio/aplicacion/static-glpi-files/_plugins"
GLPI_RSS_DIR: "/servicio/aplicacion/static-glpi-files/_rss"
GLPI_SESSION_DIR: "/servicio/aplicacion/static-glpi-files/_sessions"
GLPI_TMP_DIR: "/servicio/aplicacion/static-glpi-files/_tmp"
GLPI_UPLOAD_DIR: "/servicio/aplicacion/static-glpi-files/_uploads"
GLPI_INVENTORY_DIR: "/servicio/aplicacion/static-glpi-files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/servicio/aplicacion/_materiales/glpi-10014/locales"
GLPI_VERSION: "10.0.14"
GLPI_SCHEMA_VERSION: "10.0.14@8f13530f7cf0fb07add30ae20013f0374956795b"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.6.2 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/servicio/aplicacion/_materiales/glpi-10014/vendor/michelf/php-markdown/Michelf)
true/punycode in (/servicio/aplicacion/_materiales/glpi-10014/vendor/true/punycode/src)
iamcal/lib_autolink in (/servicio/aplicacion/_materiales/glpi-10014/vendor/iamcal/lib_autolink)
sabre/dav in (/servicio/aplicacion/_materiales/glpi-10014/vendor/sabre/dav/lib/DAV)
sabre/http in (/servicio/aplicacion/_materiales/glpi-10014/vendor/sabre/http/lib)
sabre/uri in (/servicio/aplicacion/_materiales/glpi-10014/vendor/sabre/uri/lib)
sabre/vobject in (/servicio/aplicacion/_materiales/glpi-10014/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/servicio/aplicacion/_materiales/glpi-10014/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/servicio/aplicacion/_materiales/glpi-10014/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/servicio/aplicacion/_materiales/glpi-10014/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/servicio/aplicacion/_materiales/glpi-10014/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/servicio/aplicacion/_materiales/glpi-10014/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/servicio/aplicacion/_materiales/glpi-10014/vendor/elvanto/litemoji/src)
symfony/console in (/servicio/aplicacion/_materiales/glpi-10014/vendor/symfony/console)
scssphp/scssphp in (/servicio/aplicacion/_materiales/glpi-10014/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/servicio/aplicacion/_materiales/glpi-10014/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/servicio/aplicacion/_materiales/glpi-10014/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/servicio/aplicacion/_materiales/glpi-10014/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/servicio/aplicacion/_materiales/glpi-10014/vendor/ramsey/uuid/src)
psr/log in (/servicio/aplicacion/_materiales/glpi-10014/vendor/psr/log/Psr/Log)
psr/simple-cache in (/servicio/aplicacion/_materiales/glpi-10014/vendor/psr/simple-cache/src)
psr/cache in (/servicio/aplicacion/_materiales/glpi-10014/vendor/psr/cache/src)
league/csv in (/servicio/aplicacion/_materiales/glpi-10014/vendor/league/csv/src)
mexitek/phpcolors in (/servicio/aplicacion/_materiales/glpi-10014/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/servicio/aplicacion/_materiales/glpi-10014/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/servicio/aplicacion/_materiales/glpi-10014/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/servicio/aplicacion/_materiales/glpi-10014/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/servicio/aplicacion/_materiales/glpi-10014/vendor/paragonie/sodium_compat/src)
symfony/cache in (/servicio/aplicacion/_materiales/glpi-10014/vendor/symfony/cache)
html2text/html2text in (/servicio/aplicacion/_materiales/glpi-10014/vendor/html2text/html2text/src)
symfony/css-selector in (/servicio/aplicacion/_materiales/glpi-10014/vendor/symfony/css-selector)
symfony/dom-crawler in (/servicio/aplicacion/_materiales/glpi-10014/vendor/symfony/dom-crawler)
twig/twig in (/servicio/aplicacion/_materiales/glpi-10014/vendor/twig/twig/src)
twig/string-extra in (/servicio/aplicacion/_materiales/glpi-10014/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/symfony/polyfill-php81)
symfony/polyfill-php82 in (/servicio/aplicacion/_materiales/glpi-10014/vendor/symfony/polyfill-php82)
league/oauth2-client in (/servicio/aplicacion/_materiales/glpi-10014/plugins/oauthimap/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/servicio/aplicacion/_materiales/glpi-10014/plugins/oauthimap/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/servicio/aplicacion/_materiales/glpi-10014/plugins/oauthimap/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.6.1 in (/usr/share/pear)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '192.168.21.24', Port: '389', BaseDN: 'ou=personal,dc=uva,dc=es', Connection filter: none, RootDN:
		'uid=incidencias_uva,ou=aplicaciones,ou=gestion,dc=uva,dc=es', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP (c00001454m@cartero-aux.uva.es)

</pre></details><details><summary>Plugins list</summary><pre> 
	formcreator          Name: Form Creator                   Version: 2.13.5     State: Enabled                                 
		Install Method: Manual
	oauthimap            Name: Oauth IMAP                     Version: 1.4.2      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by keguira** [comment]
I don't understand this issue or maybe it's a misunderstanding of what is defined, where and "what for" (and maybe a label thing)

The server timezone (or offset by default) defined in `Setup > General > Default values` corresponds to the time zone applied on the application by default for all users unless you ovewrite it at user-level.
This configuration handles the [timezone function](https://glpi-install.readthedocs.io/en/latest/timezones.html) (Europe/Lisbon for example) when timezones are activated.

In authentication, the offset (and not timezone compliant) corresponds to an offset to apply in the use case of ldap sync . It's the `time_offset` value stored in `glpi_config` table and it's seems to be a legacy thing. This is not used anywhere else.

There is no other place in GLPI to declare your server configurated timezones / offsets (OS, mysql/mariadb and php levels) as they can use a specific value or the OS one. As for version 10.x and 11.x, all points in time (datetime) are still stored as `TIMESTAMP` (so relative to UTC with a range from `1970` to `2038`)

**Comment by litbea** [comment]
I'm sorry, but there is no "server timezone" in my Setup > General > Default Values panel. I'm currently using version 10.0.14. That may explain my confusion, I now understand the auth offset is a different parameter.
<img width="680" alt="2024-05-03 GLPI timezone missing" src="https://github.com/glpi-project/glpi/assets/3986967/f75fe2ed-1ac2-41f4-997e-0ce791f5606b">

**Comment by keguira** [comment]
The problem is myself and my misspell : it's not a _server_ timezone, just "timezone" in personnalisation. This ils the one i'm talking about in the first paragraph. Corrected.

**Comment by trasher** [comment]
Those are indeed two distinct settings. The one in auth file is specific to authentication and is present in very old GLPI versions.
