### ISSUE TITLE
Error during installation version 10.0.15

### ISSUE THREAD

**Issue by rendonvelez** [glpi-project/glpi#17024]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

Uncaught Exception Error: Class "DB" not found in /var/www/glpi/src/Toolbox.php at line 2382.

### Relevant log output

```shell
[2024-04-27 23:46:01] glpiphplog.WARNING: Test logger
[2024-04-27 23:46:18] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class "DB" not found in /var/www/glpBacktrace :>
  install/install.php:321                            Toolbox::createSchema()
  install/install.php:620                            step4()
  public/index.php:82                                require()
```

### Steps To reproduce

Install wizard until step 3

**Comment by zacksanz** [comment]
It seems that the GLPI initialization script for the lastest versions is broken (or at least not working for some setups). I got the same error when installing in Rocky Linux 9.4 with PHP 8.1 to 8.3 with MySQL Server 8.0.3 or MariaDB Server 10.5.22. My solution was first to install GLPI 10.0.7 and then upgrading to version 10.0.15.
