### ISSUE TITLE
Forum registration seems broken

### ISSUE THREAD

**Issue by cautiouscoyote** [glpi-project/glpi#17025]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

An attempt to register at the GLPI forum (https://forum.glpi-project.org/register.php) fails with the **registration email not being delivered**, neither in the inbox, nor in the junk/spam folder.

Also, the suggestion to, in such case when the email is not received, send a message to the forum admin at glpi-at-teclib.com results in ... just silence.
I tried contacting the forum admin from the email address with which I tried to register an account, and also from a secondary email account, under the assumption that - heck, who knows - the first might have been junked at the forum admin's mail box.
A couple of weeks have passed, still no response whatsoever.

Trying to re-register with the same intended username and/or email address results in the message that an account is already registered with either of them.

Can anyone with the proper privileges please have a look at that forum admin mailbox and registration mechanism?

### Relevant log output

```shell
N/A
```

### Page URL

https://forum.glpi-project.org/register.php

### Anything else?

I understand that this is not a GLPI issue as such, but since the proper point of contact fails, I see no other option than this public board of issues.

**Comment by cautiouscoyote** [comment]
Anyone...?
It is still **awfully quiet** on this matter.
Wouldn't any other new forum users possibly have troubles registering?

There are some issue discussions I'd like to participate in, help improving things with input from my side.
But without registration there is no way to begin.

**Comment by trasher** [comment]
Just tested with a temporary email, and I get the registration email correctly. Try with a different email address.

Also, github bug tracker is for GLPI issues; and this is not a GLPI issue.
