### ISSUE TITLE
Impossible to use `@` in password

### ISSUE THREAD

**Issue by felag** [glpi-project/glpi#17038]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

When using an account from internal database,
When this account uses a password containing character `@`,
Then connexion to GLPi is refused.

Workaround: remove `@` from password of account, let login occur.

### Steps To reproduce

1. With an account of internal database containing `@` in its password,
2. Fill login and password of login screen
3. Clic on button "connect"

**Comment by felag** [comment]
I forgot to mention that this bug is seen also on version 10.0.12 of GLPi.

**Comment by cconard96** [comment]
How was the user created/password set? Through the new user form, API, password reset form, etc?

**Comment by felag** [comment]
Sorry to have borrewed your time. :sweat: 

I do not know how user was created and I could not reproduce it on a "vanilla instance" (just installed GLPi from scratch).

I believe it was linked to this specific installation (later on, I learned that GLPi has been reinstalled).
I suspect glpicrypt.key to have been changed between account creation and usage.

I will now close this issue and thanks for having looked into it.
