### ISSUE TITLE
About the server URL to use as server parameter, it will depends on you server and plugins installation

### ISSUE THREAD

**Issue by AlexTR85** [glpi-project/glpi#17063]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.10

### Bug description

In the documentation:
"https://glpi-agent.readthedocs.io/en/latest/configuration.html"
It states the following:

---------------------------------------------------------------------------------

If you're using [GLPI 10+](https://glpi10.com/), there are few cases regarding [GlpiInventory plugin](https://plugins.glpi-project.org/#/plugin/glpiinventory) usage:

If you're not using GlpiInventory plugin:

Your server URL should look like: https://my-glpi-server/, or https://my-glpi-server/front/inventory.php

Using https://my-glpi-server/ may cause issues fixed in GLPI 10.0.6. If you use an older version, it may be better to use the full URL for now.

If you have installed GlpiInventory plugin via Marketplace:

Your server URL should look like: https://my-glpi-server/marketplace/glpiinventory/

If you have installed GlpiInventory plugin manually under /plugins GLPI folder:

Your server URL should look like: https://my-glpi-server/plugins/glpiinventory/

---------------------------------------------------------------------------------

However, "https://my-glpi-server/" continues to function even when using the inventory plugin, so it's pointless to set up a separate agent proxy and close it off from the internet if you want to avoid exposing the GLPI inventory to the internet when only conducting local inventory. (At the firewall level, you can prevent access to "https://my-glpi-server/marketplace/glpiinventory/" from the internet while maintaining local access, but you can't do that with "https://my-glpi-server/".)

The URL "https://my-glpi-server/front/inventory.php" returns an error, but you can still send inventory to "https://my-glpi-server/" without any issues.

With the plugin activated, "https://my-glpi-server/" should not receive inventories; they should only be sent to "https://my-glpi-server/marketplace/glpiinventory/" or "https://my-glpi-server/plugins/glpiinventory/".

### Page URL

https://my-glpi-server/

### Steps To reproduce

With the plugin installed, configuring an agent with the URL: "https://my-glpi-server/" and sending an inventory, GLPI collects it

**Comment by trasher** [comment]
Inventory is handled from GLPI, not from the plugin; which just adds a kind of alias; that does not seems a bug.
