### ISSUE TITLE
cant login after upgrade 10.0.8 and newer disable zend_extension=opcache its not solution

### ISSUE THREAD

**Issue by adamcios** [glpi-project/glpi#17079]
go into php.ini and disable zend_extension=opcache by putting a ; in front and test to see if it logs in.
I really don't know why these things happen in GLPI.

_Originally posted by @HectorZanardo in https://github.com/glpi-project/glpi/issues/15132#issuecomment-1655506112_
            
after upgrade on 2 glpi systems with xamp if idont disable zend extension opcache i cant login.  get error "CSRF check failed for User ID:  at /glpi/front/login.php" 
Problem still exist in the newest version. i try upgrade to 10.0.8 and now i have 10.0.15 and problem exist . 
problem start after upgrade to 10.0.8 and newer. in version 10.0.7 and 10.0.6 it  doesnt exist ...
any suggestion? 
disable opcache its not a solution

**Comment by cedric-anne** [comment]
@adamcios 

Are you using XAMPP ? Until now, the problem your are facing was only reproduced on XAMPP. This software is not designed to be used in production, see https://www.apachefriends.org/hosting.html.

> XAMPP provides an ideal local development environment, but is not meant for production deployments.

Anyways, if you are using XAMPP, did you try this solution proposed in another comment ?

> The reason I asked was because there could be a cache conflict. On Windows (and only Windows), all processes running the same Server API (SAPI), in this case apache2handler, under the same user account share the same OPCache instance.
> 
> You can add "opcache.cache_id=${OPCACHE_ID}" to your PHP configuration and then set a unique value to that environment variable in your Apache virtual host config(s) (using SetEnv) to have them use separate caches.
> 
> This setting only exists for Windows.

**Comment by adamcios** [comment]
no it doesnt work for me "opcache.cache_id=${OPCACHE_ID}" and setenv.
So what alternative is for xamp which can i use in production?  any suggestions?

**Comment by cedric-anne** [comment]
Maybe this issue can be related to usage of `session.cookie_secure = on` if your are using GLPI on the HTTP port. Indeed, this configuration will not send cookies to the browser if you are not using the HTTPS protocol, resulting in the kind of issue you are facing.

> So what alternative is for xamp which can i use in production?

There are many possible solutions, you can ask on [community forums](https://forum.glpi-project.org/).
