### ISSUE TITLE
Computers search with under criteria

### ISSUE THREAD

**Issue by gitdevmod** [glpi-project/glpi#1707]
Hi,

When using the following search in computers
![glpi-sous1](https://cloud.githubusercontent.com/assets/2040775/22324215/46d6e768-e3a8-11e6-9e80-206b3b972c64.PNG)

then I execute the request it search in the first children
![glpi-sous2](https://cloud.githubusercontent.com/assets/2040775/22324235/6413a1b8-e3a8-11e6-9a01-c61f6e9acc59.PNG)

GLPI VERSION: 9.1.1

Let me know if you need more information,
TIA

**Comment by trasher** [comment]
OK, so, what's your problem? You do not talk about any issue here.

**Comment by gitdevmod** [comment]
I want only Status "Actif" but if I execute it search "Actif > En stock"

**Comment by gitdevmod** [comment]
This is an extract of status configured
![glpi-sous3](https://cloud.githubusercontent.com/assets/2040775/22324890/e1fd62f0-e3ab-11e6-9c8e-2a31b4e041f2.PNG)

**Comment by trasher** [comment]
Thnaks for the details. I cannot reproduce with GLPI 9.1.2; it may have been fixed. Could you please try with this release?

**Comment by gitdevmod** [comment]
I do not have the issue if I select under "Historique"
In doubt, I will upgrade to GLPI 9.1.2

**Comment by gitdevmod** [comment]
I just upgraded to GLPI 9.1.2 ==> same issue

The criteria changes when I press "Rechercher", if I modify the URL directly whith the correct ID it works.

computer.php?is_deleted=0&criteria[0][field]=31&criteria[0][searchtype]=under&criteria[0][value]=**22**&search=Rechercher&itemtype=Computer&start=0&_glpi_csrf_token=

in the table glpi_states, the id of "Actif" is 22 and "Actif > Stock" is 20

**Comment by trasher** [comment]
Ok, I'm still not able to reproduce, I really don't know why :/

**Comment by trasher** [comment]
It may be possible you are facing this issue because you have one day changed your tree; or if you changed something manually in the database (are you in one of those cases?)

On a **test database**, run the following query:
```
UPDATE `glpi_states` SET sons_cache = null, ancestors_cache = null;
```
And see if that solves your problem.

**Comment by gitdevmod** [comment]
Maybe I changed the tree in glpi one day but never directly in mysql.
I tested but still same issue.

As workaround I recreated a new state and moved childrens to it: no more bug.

No sure if it could be related to #1148 
Thanks
