### ISSUE TITLE
php compatible

### ISSUE THREAD

**Issue by loyolajavi** [glpi-project/glpi#17093]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

Hello  everyone, 
Is php 8.3.X compatible with Glpi?
In the readme the max version is 8.2
But in the 10.0.10 release announced compatibility with php 8.3.

**Comment by cconard96** [comment]
PHP 8.3 is indeed supported as of GLPI 10.0.10.

**Comment by loyolajavi** [comment]
Thank you Curtis

**Comment by bborrel** [comment]
I know ticket was closed, but to complement @cconard96's comment, GLPI core may support PHP 8.3, but not its dependencies.

On an install of GLPI 10.0.11, if you ask composer what's prohibiting PHP 8.3, it will list a couple of dependencies which in their own `composer.json` are declaring that they do not support PHP 8.3.

To get this info from Composer:

```
composer why-not php 8.3
Package "php" could not be found with constraint "8.3", results below will most likely be incomplete.
friendsoftwig/twigcs           v6.1.0 requires php (~7.4.0 || ~8.0.0 || ~8.1.0 || ~8.2.0) 
laminas/laminas-i18n           2.15.0 requires php (^7.4 || ~8.0.0 || ~8.1.0)             
laminas/laminas-loader         2.8.0  requires php (^7.3 || ~8.0.0 || ~8.1.0)             
laminas/laminas-mail           2.16.0 requires php (^7.3 || ~8.0.0 || ~8.1.0)             
laminas/laminas-mime           2.9.1  requires php (^7.3 || ~8.0.0 || ~8.1.0)             
laminas/laminas-servicemanager 3.10.0 requires php (~7.4.0 || ~8.0.0 || ~8.1.0)           
laminas/laminas-stdlib         3.7.1  requires php (^7.3 || ~8.0.0 || ~8.1.0)             
laminas/laminas-validator      2.16.0 requires php (^7.3 || ~8.0.0 || ~8.1.0)
```

Note that you can skip `friendsoftwig/twigcs`, which is a _require-dev_, but there is still the whole laminas projects to consider.
