### ISSUE TITLE
Has anyone else encountered this error when trying to search in Consumables?

### ISSUE THREAD

**Issue by IsaacMariaMedina** [glpi-project/glpi#17092]
Has anyone else encountered this error when trying to search in Consumables?

Twig Error (Twig\Error\RuntimeError): "An exception has been thrown during the rendering of a template ("CommonDBTM::isMassiveActionAllowed(): Argument #1 ($items_id) must be of type int, null given")." in template "/var/www/html/glpi/templates/components/search/table.html.twig" at line 121

Additionally, when I load the Consumable Request plugin, it returns this error:

PHP User Warning (512): Duplicate keys found in search options for item type ConsumableItem: 1, 2 in /var/www/html/glpi/src/Search.php at line 8335

_Originally posted by @IsaacMariaMedina in https://github.com/glpi-project/glpi/issues/16839#issuecomment-2088665867_

**Comment by IsaacMariaMedina** [comment]
The solution is to copy the old Search.php to the new path. This will help those who are facing this issue

**Comment by cedric-anne** [comment]
> The solution is to copy the old Search.php to the new path. This will help those who are facing this issue

Replacing a file in the source code is never a good solution. It may trigger even more bugs.
