### ISSUE TITLE
[0.90] Blank page when deleting entries in dust bin

### ISSUE THREAD

**Issue by xsgoodbox** [glpi-project/glpi#171]
There's a blank page doing a 
→ Show deleted items
→ Action(s), "Delete permanently *"

it falls on that blank page (https://glpi/glpi09/front/massiveaction.php); the entries aren't removed.

**Comment by orthagh** [comment]
Could you provide last errors in glpi/_files/[sql|php]-errors.log

**Comment by xsgoodbox** [comment]
The problem don't update theses logs, however, got that in debug mode
` Fatal error: Class 'PluginFieldsComputer4jscomputerfields' not found in /var/www/html/glpi09/plugins/fields/inc/container.class.php on line 270` 
I'm gonna report to the fields gh page, Closing!

Have a good night.
