### ISSUE TITLE
The List button is not displayed

### ISSUE THREAD

**Issue by NoNameAvailableUsers** [glpi-project/glpi#17119]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

![Screenshot_20240514_194229_Teams](https://github.com/glpi-project/glpi/assets/168309320/9bbf6fcb-edf5-4583-9f8c-658ef85e59be)
![Screenshot_20240514_194233_Teams](https://github.com/glpi-project/glpi/assets/168309320/d49ffc28-a23a-43ae-bd7c-862a654596c9)
![Screenshot_20240514_194235_Teams](https://github.com/glpi-project/glpi/assets/168309320/e825c11c-2d89-446e-aa68-7041880bf432)

The List button does not appear on the global page.  On other pages Assets/.... works fine

**Comment by cedric-anne** [comment]
Hi,

This is not a bug, but a missing feature. The `Lists` button is not available in GLPI 10.0 in the assets global page. This feature will be present in GLPI 11.0.
