### ISSUE TITLE
glpi_items_disks database schema_integrity differs after 10.0.10 to 10.0.15 update

### ISSUE THREAD

**Issue by ak47d** [glpi-project/glpi#17111]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

Please tell me how to fix it.
After upgrading from 10.0.10 to 10.0.15 warning: The database schema does not match the current version of GLPI. It is recommended to run the "php bin/console database:check_schema_integrity" command to see the differences.

After launch
php bin/console database:check_schema_integrity

```
The table schema is different in the "glpi_items_disks" table.
--- Expected database schema
+++ Current database schema
@@ @@
   `encryption_type` varchar(255),
   `entities_id` int NOT NULL DEFAULT 0,
   `filesystems_id` int NOT NULL DEFAULT 0,
-  `freesize` bigint NOT NULL DEFAULT 0,
+  `freesize` int NOT NULL DEFAULT 0,
   `is_deleted` tinyint NOT NULL DEFAULT 0,
   `is_dynamic` tinyint NOT NULL DEFAULT 0,
   `items_id` int NOT NULL DEFAULT 0,
@@ @@
   `itemtype` varchar(255),
   `mountpoint` varchar(255),
   `name` varchar(255),
-  `totalsize` bigint NOT NULL DEFAULT 0,
+  `totalsize` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),

```

**Comment by trasher** [comment]
This has already been reported and fixed

**Comment by ak47d** [comment]
How can I fix this? Provide a link to the fix or problem if it has already been resolved before

**Comment by trasher** [comment]
Just search in closed issues

**Comment by ak47d** [comment]
https://github.com/glpi-project/glpi/issues/16991
