### ISSUE TITLE
approval is confusing

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1712]
hello

A lot of users have some problem to use the approval.

Would it be possible to improve it ?

![image](https://cloud.githubusercontent.com/assets/15144026/22335483/3ee1a4da-e3df-11e6-8053-c621f9e127cb.png)

add a line to show, firstly click on the line to approve the request

**Comment by nbriche** [comment]
Seconded. Approvers usually only change the global approval status, then after a while we notice that they still haven't approved, then we go see them and we tell them how to actually approve.

Rince, repeat.

**Comment by Giudy** [comment]
see #442

**Comment by trasher** [comment]
Duplicates #442
