### ISSUE TITLE
[TRADUCTION] Error on French traduction in computer model

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi#17121]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.13

### Bug description

Hi everyone, 

one the page to add or modify the model of computer we have the field "Is half rack". When GLPI is in french the actual value is "Demie largeur" cela doit plutôt être "demi-largeur". 

Thank you in advance, 

### Relevant log output

```shell
.
```

### Page URL

https://GLPI/front/computermodel.form.php

### Steps To reproduce

.

### Your GLPI setup information

.

### Anything else?

.

**Comment by trasher** [comment]
Translations are handled on transifex:
https://app.transifex.com/glpi/GLPI/dashboard/
