### ISSUE TITLE
Typo in DE translation

### ISSUE THREAD

**Issue by userjab** [glpi-project/glpi#17140]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

Typo in the German translation.
/locales/de_DE.po
"Importiere Invetarisierungs-Dateien" should be "Importiere Inve**n**tarisierungs-Dateien"

### Page URL

https://github.com/glpi-project/glpi/blob/10.0/bugfixes/locales/de_DE.po#L11762

**Comment by trasher** [comment]
Translations are handled on transifex, please fix directly there:
https://app.transifex.com/glpi/GLPI/dashboard/
