### ISSUE TITLE
Right to update ticket for technicien only with the right 'Beeing in charge'

### ISSUE THREAD

**Issue by glpi123** [glpi-project/glpi#17149]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

glpi 10.0.15

### Bug description

Here are the rights assigned to the profile :
See assigned
Assign
Beeing in charge
![image](https://github.com/glpi-project/glpi/assets/97961877/307abedb-6653-4aa4-a2c8-e4fbc4a5dea9)
This profile has the right to update ticket.

### Relevant log output

```shell
No logs in glpi/files/_logs
```

### Page URL

front/ticket.form.php

### Steps To reproduce

Tickets-> update ticket assigned (all fields)->save

### Your GLPI setup information

GLPI 10.0.15
Operating system: Linux 5.14.21-150500.55.19-default x86_64
PHP 8.0.30 apache2handler (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, ctype, curl, date, dom, exif, fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" upload_max_filesize="2M" disable_functions=""
Software: Apache ()
Server Software: MariaDB package Server Version: 10.6.14-MariaDB

**Comment by glpi123** [comment]
i will be grateful for any help

**Comment by cedric-anne** [comment]
Hi,

This is not a bug. As long as you can assign or being in charge of tickets, GLPI considers that you have enough rights to update tickets.
