### ISSUE TITLE
GLPI <= 9.1.2: Solution id is always 0

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#1715]
Hi,

On GLPI <= 9.1.2 [solution ids are always set as 0](https://github.com/glpi-project/glpi/blob/master/inc/ticket.class.php#L6092). This is linked to #1435, as in the future solution ids might actually exist.

**Comment by tomolimo** [comment]
Hello,
Just one question: where/when/for what do you need to have an id for a solution?
Does a solution list (or table) will be what you are looking for?
This will help me designing the new code for solutions.
Thank you
Regards,
Tomolimo

**Comment by pVesian** [comment]
@tomolimo Hi, sorry I didn't see your reply. I don't remember the specifics, just that solutions don't have ids in DB and data is queried from the log table which should never ever happen. Relates to #1435 and #2089.

**Comment by trasher** [comment]
Tickets solution has been reworked for 9.3; this problem will be solved
