### ISSUE TITLE
contract statistic link error

### ISSUE THREAD

**Issue by ciberfred** [glpi-project/glpi#17169]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.15

### Bug description

Unknown column 'glpi_contracts._virtual_expiration' in 'where clause'

### Relevant log output

```shell
[2024-05-22 17:06:16] glpisqllog.ERROR: DBmysql::doQuery() in /var/www/html/glpi-10.0.15/src/DBmysql.php line 403
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_contracts`.`id` AS id, 'glpi' AS currentuser,
                        `glpi_contracts`.`entities_id`, `glpi_contracts`.`is_recursive`,  `glpi_contracts`.`name` AS `ITEM_Contract_1`,
                        `glpi_contracts`.`id` AS `ITEM_Contract_1_id`,
                        `glpi_contracttypes`.`name` AS `ITEM_Contract_4`,  `glpi_contracts`.`num` AS `ITEM_Contract_3`,  `glpi_contracts`.`begin_date` AS `ITEM_Contract_5`,  `glpi_contracts`.`duration` AS `ITEM_Contract_6`,  `glpi_contracts`.`notice` AS `ITEM_Contract_7`,  (SUM(`glpi_contractcosts`.`cost`) / COUNT(`glpi_contractcosts`.`id`)) * COUNT(DISTINCT `glpi_contractcosts`.`id`) AS `ITEM_Contract_11`,  `glpi_contracts`.`renewal` AS `ITEM_Contract_23`,  `glpi_contracts`.`begin_date` AS `ITEM_Contract_12_begin_date`, `glpi_contracts`.`duration` AS `ITEM_Contract_12_duration`, `glpi_contracts`.`renewal` AS `ITEM_Contract_12_renewal` FROM `glpi_contracts`LEFT JOIN `glpi_contracttypes`
                                          ON (`glpi_contracts`.`contracttypes_id` = `glpi_contracttypes`.`id`
                                              ) LEFT JOIN `glpi_contractcosts`
                                             ON (`glpi_contracts`.`id` = `glpi_contractcosts`.`contracts_id`
                                                 ) WHERE  `glpi_contracts`.`is_deleted` = 0  AND `glpi_contracts`.`is_template` = 0  AND (    (`glpi_contracts`.`_virtual_expiration`  LIKE '%>6%' )  AND (`glpi_contracts`.`_virtual_expiration`  LIKE '%<30%' ) ) GROUP BY `glpi_contracts`.`id`
  Error: Unknown column 'glpi_contracts._virtual_expiration' in 'where clause'
  Backtrace :
  src/Search.php:1460                                DBmysql->doQuery()
  src/Search.php:449                                 Search::constructData()
  src/Search.php:200                                 Search::getDatas()
  src/Search.php:177                                 Search::showList()
  front/contract.php:42                              Search::show()
```

### Page URL

http://10.1.230.66/glpi/front/contract.php?reset=reset&sort=12&order=DESC&start=0&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bvalue%5D=%3E6&criteria%5B0%5D%5Bsearchtype%5D=contains&criteria%5B1%5D%5Bfield%5D=12&criteria%5B1%5D%5Blink%5D=AND&criteria%5B1%5D%5Bvalue%5D=%3C30&criteria%5B1%5D%5Bsearchtype%5D=contains

### Steps To reproduce

create a contract that expire in less than 1 month, go to start page see the contract expirity number click on it => get an error.

### Your GLPI setup information

10.0.15 version

### Anything else?

contract stats are ok but link to listing is in error and not reporting the correct contract. got SQL error.

**Comment by trasher** [comment]
I cannot reproduce from searc, and I do not really understand "go to start page see the contract expirity number click on it".

Maybe try without any plugin enabled.

**Comment by ciberfred** [comment]
same error like this one : https://forum.glpi-project.org/viewtopic.php?id=289959

**Comment by cedric-anne** [comment]
I was able to reproduce.

1. Create a contract that will expire in less than 30 days.
2. Go to the `Home` page, in the `Global View` tab.
3. Click on the `Contracts expiring in less than 30 days` link located in the `Contract` card.

![image](https://github.com/glpi-project/glpi/assets/33253653/2a33d2b6-d3ec-480c-b3ae-653dc6b504c2)

**Comment by Rom1-B** [comment]
https://github.com/glpi-project/glpi/pull/17173 should fix this.

**Comment by ciberfred** [comment]
you should modify the 'tab' 20 as DAY instead of MOUNTH as the filtering unit (line 592)

**Comment by cedric-anne** [comment]
@ciberfred 

Could you test #17189 ?

**Comment by ciberfred** [comment]
seems works :).
just question : what about contract renewal that never expire ? is there any alert statistic about this ?
