### ISSUE TITLE
It's not possible to attach files with the .rar extension

### ISSUE THREAD

**Issue by lleonardx** [glpi-project/glpi#17165]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

When i try to attach any file with .rar extension, appears the message "file type not allowed".

I follow the steps to add a new doc type: Settings > dropdown list > document types. But is not possible attach .rar
zip extension is possible, i tried to

![image](https://github.com/glpi-project/glpi/assets/89672096/5b655600-4bf9-4acf-a37a-4a25c8bc4732)

### Steps To reproduce

1. Create a new ticket
2.  Write a ticket steps 
3.  Try attach any file with .rar extension

**Comment by fgendorf** [comment]
You can go to /front/documenttype.php if you are super-admin and add new mime-type support, like this
![image](https://github.com/glpi-project/glpi/assets/15034336/941ccc6d-9845-4514-9c07-c81522a88e74)

**Comment by lleonardx** [comment]
Hi @fgendorf, i follow you comment using a super-admin account and it worked. Now it's possible attach a file with rar extension

thanks for helping me
