### ISSUE TITLE
project's task duration computed in days

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#1716]
tested on current master and 9.1/bugfixes.

![image](https://cloud.githubusercontent.com/assets/418844/22338222/235f16b8-e3e7-11e6-92a0-161ec6f493c0.png)

It should be better if we could use the entity calendar (in assistance tab)

This issue happens:
- in project form 
- in project's task form

**Comment by trasher** [comment]
As far as I understand, it should be computed taking in count hours/day (so, it should display 5 days)

**Comment by LordBat** [comment]
hi, any update about this? thanks

**Comment by Armin83** [comment]
In ticket tasks too.
http://forum.glpi-project.org/viewtopic.php?id=41268

**Comment by GambitK** [comment]
Is there any solution or workaround for this? I'm having the same issue that planned tasks are in a 24h cycle, a solution could me let the user decide the calendar when creating a task.

**Comment by Nomino-pl** [comment]
I raise the topic
Probably everyone who uses projects and has to settle hours sees this as a problem.
It's nice if one day you could count days based on a work calendar defined by yourself ;)

**Comment by wavancini** [comment]
If the system shows on hours is  enough.
How can I show on all views the total of ours (of tasks or sum of tasks when assigned) do not calculated in days.
