### ISSUE TITLE
The depth of the device cannot be changed

### ISSUE THREAD

**Issue by hubMich** [glpi-project/glpi#17170]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.15

### Bug description

The depth of the device cannot be changed

### Page URL

/front/networkequipmentmodel.form.php

### Steps To reproduce

1.Change depth field
2. Save
3. Get communicate: "Unable to update model because it is used by an asset in the "[Rack Name](https://glpiaddress/front/rack.form.php?id=196)" rack and the new required units do not fit into the rack"

### Anything else?

After removing the devices from the rack, the depth can be changed.
This problem does not occur in every rack.

**Comment by trasher** [comment]
That seems the expected behaviour; I do not see the bug here.

**Comment by hubMich** [comment]
Why do I have to remove the device from the rack when changing the depth from 1 to 1/3 in the model?

**Comment by trasher** [comment]
Well, you did not give all useful information in your first message. Please provide a reproducible use case from a fresh install.
