### ISSUE TITLE
loading favorites takes a long time

### ISSUE THREAD

**Issue by laurixia** [glpi-project/glpi#17176]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.14

### Bug description

When I need to use a search of my favorites and I click on the "favorites" button, it takes a long time to load the list of my saved searches.

<img width="296" alt="image" src="https://github.com/glpi-project/glpi/assets/26741776/0fbc8009-9ae0-4a50-bb8f-4282afb4e0b7">

### Your GLPI setup information

[GLPI 10.0.15]

**Comment by cconard96** [comment]
Please provide the information requested by the issue template.
