### ISSUE TITLE
Image issue when sending notifications

### ISSUE THREAD

**Issue by PaulinDeuxTrois** [glpi-project/glpi#17177]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

When i send a image in mail to collector, it creates a ticket with the image in origin size but the notification mail has a compressed image which is blurry. I checked all permissions and size limits in php.ini/GLPI options and yet it still get compressed.
![php_error](https://github.com/glpi-project/glpi/assets/95508677/b5d8a0ee-d021-4eb1-8c2e-d281bd46125d)

### Steps To reproduce

Send mail to colector with img attachment
Check ticket created if it has an image with  good resolution 

### Your GLPI setup information

[GLPI 10.0.11 ( = varwwwglpi).txt](https://github.com/glpi-project/glpi/files/15418257/GLPI.10.0.11.varwwwglpi.txt)

**Comment by trasher** [comment]
First, you're using an old GLPI release; and second, you have permission issues you have to fix.
