### ISSUE TITLE
Problem with Entities that have multiple users with the same email address

### ISSUE THREAD

**Issue by theuwguy** [glpi-project/glpi#17181]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.11

### Bug description

We are currently having an issue where tickets are link to a user in a separate entity.  

**Recievers Flow:**
[Receiver 1] -> [Mail Receiver Rule 1] -> [Entity 1]

[Receiver 2] -> [Mail Receiver Rule 2] -> [Entity 2]

**Auth Assignments Flow:**
[LDAP 1] -> [Auth Rule 1] -> [Entity 1]

[LDAP 2] -> [Auth Rule 2] -> [Entity 2]

Note:
- Users can exist in both LDAP auth sources with the SAME email address.

**Problem:**
[Entity 2 User (user@test.com)] -> [Receiver 2 (help1@test.com)] -> [Entity 2] -> Linked to [Entity 1 User (user@test.com)]

So everything works up until the Entity assignment but when the ticket is linked to an account it chooses on from another entity (with the same email)

**Finding/Suggestions:**

I didn't see any logic that looks at the Entity(s) and its user account prior to linking the ticket.  It would appear that it queries the database and uses the first email address that matches (usually the on with the lowest record number) and links that to the ticket.

Hope this makes sense

**Comment by trasher** [comment]
Please try with latest stable release.
