### ISSUE TITLE
Problems enhancement

### ISSUE THREAD

**Issue by glasserre** [glpi-project/glpi#17182]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

Future release

### Enhancement description

- Add followups on problems
- Problems visibility + followups on end user start page / glpi menu in order to keep them inform.

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by glasserre** [comment]
This site don't work ... i tried before to post my idea.

![image](https://github.com/glpi-project/glpi/assets/2472365/0673ab44-0792-49a9-8411-f4d48abb3c70)

**Comment by trasher** [comment]
https://glpi.userecho.com/

**Comment by trasher** [comment]
> This site don't work ... i tried before to post my idea.

It's now fixed
