### ISSUE TITLE
Prevent an user from having no authorizations profile

### ISSUE THREAD

**Issue by emitlinks** [glpi-project/glpi#17188]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

There is an issue with GLPI that has been going on for a while with users authorizations and the ability to be able to view/edit that user profile when the last authorization has been removed from the user.
When this happens, you are not allowed to view the user's page on GLPI and cannot edit the user anymore. The only way to fix that is to add an entry in the database in the glpi_profiles_users table to add one authorization manually.

There are two ways I can see to address this issue, either block the removal of the last authorization profile from the user or create a permission to be able to access the user page when something like that happens.

### Steps To reproduce

1. Create / Import an user in GLPI
2. Go on the user page and remove every authorization
3. You get access denied when applying the modification and cannot access the page anymore

**Comment by cconard96** [comment]
Are you trying to view the user when connected to the root entity in tree/recursive mode? A user without profiles has no entity assignment so you need to be able to see all entities to view them.

**Comment by emitlinks** [comment]
Yes, I have the role Super-Admin, and I am connected to the root entity in recursive mode, but I can't see the users that have no entity assignment.

The entity I'm on :
![image](https://github.com/user-attachments/assets/86c28324-3fd7-42e9-a962-19bb20b6ca4c)

What I get when I search the user : 
![image](https://github.com/user-attachments/assets/43f42878-e637-45a8-bef8-db579f241cdc)

The user is in database but doesn't have a profile linked to it : 
![image](https://github.com/user-attachments/assets/38048c2f-f964-42ac-a5d5-b76da91753c6)

Added the profile with sql query : 
![image](https://github.com/user-attachments/assets/0422a0c8-710e-4e35-81fa-2e94dd87f0b8)

User is visible after adding the profile : 
![image](https://github.com/user-attachments/assets/fc06cfb7-c194-4e4c-821c-57c7b0b5778d)

**Comment by emitlinks** [comment]
I made a temp fix on my own with a script that look in the database every 5
mins for an user without authorization profile which then add one as self
service for the root entity.

Still this issue need to be addressed.

**Comment by trasher** [comment]
I've not been able to reproduce on a fresh local instance; from the default admin account, all users are still present in the list.
To fix the issue, we need a way to reproduce it from a fresh install.

**Comment by emitlinks** [comment]
I just tested on a fresh instance with a fresh database and I don't get the issue. There must be something wrong in the database from the migration from an old version of GLPI.
I will close this issue since it's not a bug native to GLPI, but something messed up in the database (probably related to the root entity, need to investigate).
