### ISSUE TITLE
can't load saved searches in Global inventory

### ISSUE THREAD

**Issue by mdsi33** [glpi-project/glpi#17190]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

I have an issue in the global inventory.
I can search, I see the star to saved my search.
I can find it in front/savedsearch.php
But in global inventory, there is no icon to load it (no "Lists")

### Steps To reproduce

1. Go to 'Inventory -> Global'
2. Do a search
3. Click on the star to save it (give a name)
4. there is no "Lists" button to load it

### Your GLPI setup information

GLPI 10.0.15
Current language:fr_FR
PHP 8.2.19 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dba, dom,
	exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, posix, random, session, shmop, soap, sodium, sqlite3, standard, tidy, tokenizer, xml, xmlreader,
	xmlwriter, xsl, zip, zlib)

**Comment by cedric-anne** [comment]
Duplicates #17119.
