### ISSUE TITLE
Bad Url

### ISSUE THREAD

**Issue by PedroRocha79** [glpi-project/glpi#17192]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

11 dev

### Bug description

![image](https://github.com/glpi-project/glpi/assets/102227374/58e1f824-0e4d-402e-9837-6c54fe31c329)

The url LDAP directory link is missing the front, expect is /glpi/front/ldap.group.php

**Comment by cedric-anne** [comment]
Fixed by #17193.
