### ISSUE TITLE
text lost during ticket creation / ticket task creation / ticket solution

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1719]
Hello,

We have for a long time an issue very ennoying.

after ticket creation or ticket task creation or ticket solution when we add or save we have the message :+1: 

"you are not allowed to perform this action"

and we lost that we have done.

I checked log and nothing relevant about these error appears.

The solution from tomolino was to disable csrf, but this option is not available anymore 

Do you have a solution please ?

Thank you for your help

**Comment by trasher** [comment]
Disabling CSRF is still available; but the file has moved from `config` directory to `inc` directory.

**Comment by satyan01** [comment]
thx
