### ISSUE TITLE
Error when adding user from entity page

### ISSUE THREAD

**Issue by ctresvaux** [glpi-project/glpi#17207]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

When i am on the tab "users" of an entity configuration page and when i click to add new user form here, i have the following error

Uncaught Exception Error: Call to a member function getNameID() on bool in /var/www/support/html/src/Profile_User.php at line 1266

### Your GLPI setup information

<details><summary>Informations sur le système, l'installation et la configuration</summary><pre>GLPI 10.0.15 ( => /var/www/support/html)
Installation mode: TARBALL
Current language:fr_FR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux p6-php82.probesys.net 6.1.0-20-amd64 #​1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11) x86_64
PHP 8.2.18 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imagick, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="40M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
Server Software: Debian 12
	Server Version: 10.11.6-MariaDB-0+deb12u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: p6-man-db1-support-user@10.6.111.243/p6-man-db1-support
	Host info: 10.6.111.243 via TCP/IP
	
PHP version (8.2.18) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.11.6) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/support/html/files/_cache has been validated.
Write access to /var/www/support/html/files/_cron has been validated.
Write access to /var/www/support/html/files has been validated.
Write access to /var/www/support/html/files/_dumps has been validated.
Write access to /var/www/support/html/files/_graphs has been validated.
Write access to /var/www/support/html/files/_lock has been validated.
Write access to /var/www/support/html/files/_pictures has been validated.
Write access to /var/www/support/html/files/_plugins has been validated.
Write access to /var/www/support/html/files/_rss has been validated.
Write access to /var/www/support/html/files/_sessions has been validated.
Write access to /var/www/support/html/files/_tmp has been validated.
Write access to /var/www/support/html/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/support/html/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/support/html"
GLPI_CONFIG_DIR: "/var/www/support/html/config"
GLPI_VAR_DIR: "/var/www/support/html/files"
GLPI_MARKETPLACE_DIR: "/var/www/support/html/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/support/html/files"
GLPI_CACHE_DIR: "/var/www/support/html/files/_cache"
GLPI_CRON_DIR: "/var/www/support/html/files/_cron"
GLPI_DUMP_DIR: "/var/www/support/html/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/support/html/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/support/html/files/_locales"
GLPI_LOCK_DIR: "/var/www/support/html/files/_lock"
GLPI_LOG_DIR: "/var/www/support/html/files/_log"
GLPI_PICTURE_DIR: "/var/www/support/html/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/support/html/files/_plugins"
GLPI_RSS_DIR: "/var/www/support/html/files/_rss"
GLPI_SESSION_DIR: "/var/www/support/html/files/_sessions"
GLPI_TMP_DIR: "/var/www/support/html/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/support/html/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/support/html/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/support/html/locales"
GLPI_VERSION: "10.0.15"
GLPI_SCHEMA_VERSION: "10.0.15@2eed74704cb07e0bac48b933cbd5c1c356f09629"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/support/html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/support/html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/support/html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/support/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/support/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/support/html/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/support/html/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/support/html/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/support/html/vendor/sabre/http/lib)
sabre/uri in (/var/www/support/html/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/support/html/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/support/html/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/support/html/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/support/html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/support/html/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/support/html/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/support/html/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/support/html/vendor/symfony/console)
scssphp/scssphp in (/var/www/support/html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/support/html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/support/html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/support/html/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/support/html/vendor/ramsey/uuid/src)
psr/log in (/var/www/support/html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/support/html/vendor/psr/simple-cache/src)
psr/cache in (/var/www/support/html/vendor/psr/cache/src)
league/csv in (/var/www/support/html/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/support/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/support/html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/support/html/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/support/html/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/support/html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/support/html/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/support/html/vendor/symfony/cache)
html2text/html2text in (/var/www/support/html/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/support/html/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/support/html/vendor/symfony/dom-crawler)
twig/twig in (/var/www/support/html/vendor/twig/twig/src)
twig/string-extra in (/var/www/support/html/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/support/html/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/support/html/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/support/html/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/support/html/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: 'ldaps://p6-idm4.idm.probesys.net', Port: '636', BaseDN: 'cn=users,cn=accounts,dc=idm,dc=probesys,dc=net', Connection
		filter: none, RootDN: 'uid=binddn-glpi,cn=sysaccounts,cn=etc,dc=idm,dc=probesys,dc=net', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (support@probesys.com@smtp.probesys.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Champs supplémentaires         Version: 1.21.8     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportements                  Version: 2.7.2      State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.13.4     State: Error / to clean                        
		Install Method: Manual
	father               Name: Père/Fils                      Version: 1.4.3      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.2      State: Enabled                                 
		Install Method: Manual
	projectbridge        Name: Projectbridge                  Version: 2.7.8      State: Enabled                                 
		Install Method: Manual
	rgpdtools            Name: Utilitaires RGPD               Version: 1.1.0      State: Not installed                           
		Install Method: Manual

</pre></details>

**Comment by ctresvaux** [comment]
It's not really a bug.
yhis message apperas if you clik on "add" wihtout selecting a user before

**Comment by cedric-anne** [comment]
Fixed by #17211.
