### ISSUE TITLE
Rules for assigning an item to an entity - Criteria - Unavailable

### ISSUE THREAD

**Issue by BorisNovg** [glpi-project/glpi#17237]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

OCS Inventory plugin version : 2.0.4 (and last master too)

Home - Administration - Rules - Rules for assigning an item to an entity:
![ocs1](https://github.com/pluginsGLPI/ocsinventoryng/assets/39726474/4ad76b50-e138-484d-adbd-ec83809b77f6)
![ocs2](https://github.com/pluginsGLPI/ocsinventoryng/assets/39726474/97a52263-9fad-4a9c-a7d1-5b87a477f5a7)

In glpi 9.5.6:
![ocs3](https://github.com/pluginsGLPI/ocsinventoryng/assets/39726474/55fdcbcc-3331-4699-960b-ac7bfc888133)

### Relevant log output

```shell
php-errors.log (on click to  "Unavailable"):

[2024-06-03 16:43:40] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "field" in /usr/share/glpi/src/RuleImportEntity.php at line 157
  Backtrace :
  src/Rule.php:2644                                  RuleImportEntity->displayAdditionalRuleCondition()
  ajax/rulecriteriavalue.php:53                      Rule->displayCriteriaSelectPattern()
  public/index.php:82                                require()
  
[2024-06-03 16:43:40] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "field" in /usr/share/glpi/src/RuleImportEntity.php at line 169
  Backtrace :
  src/Rule.php:2644                                  RuleImportEntity->displayAdditionalRuleCondition()
  ajax/rulecriteriavalue.php:53                      Rule->displayCriteriaSelectPattern()
  public/index.php:82                                require()
```

### Anything else?

Table glpi_rulecriterias in field criteria:
MACHINE_NAME
IPADDRESS

**Comment by trasher** [comment]
As far as I know; OCS plugin provide its own rules. This issue is probably related to the plugin, please report issue on their side.
