### ISSUE TITLE
Migration file missing in 10.0.15 tgz

### ISSUE THREAD

**Issue by KrisLowet** [glpi-project/glpi#17242]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

File `install/migrations/update_10.0.14_to_10.0.15/items_disks.php` is missing in the glpi-10.0.15.tgz release file.

`[root@glpi001]-[/var/www/glpi/prod]
# sudo -u www-data /usr/bin/php8.2 bin/console db:update
+-----------------------+-----------+---------+
|                       | Current   | Target  |
+-----------------------+-----------+---------+
| Database host         | localhost |         |
| Database name         | glpi_prod |         |
| Database user         | glpi      |         |
| GLPI version          | 10.0.14   | 10.0.15 |
| GLPI database version | 10.0.14   | 10.0.15 |
+-----------------------+-----------+---------+
Checking database schema integrity...
Database schema is OK.
Do you want to continue? [Yes/no]
======================================== Update to 10.0.15 =========================================
====================================== Initializing rules... =======================================
Migration done.
The database schema is not consistent with the current GLPI version.
It is recommended to run the "php bin/console database:check_schema_integrity" command to see the differences.
[root@glpi001]-[/var/www/glpi/prod]
# sudo -u www-data /usr/bin/php8.2 bin/console db:check_schema_integrity
Table schema differs for table "glpi_items_disks".
--- Expected database schema
+++ Current database schema
@@ @@
   `encryption_type` varchar(255),
   `entities_id` int NOT NULL DEFAULT 0,
   `filesystems_id` int NOT NULL DEFAULT 0,
-  `freesize` bigint NOT NULL DEFAULT 0,
+  `freesize` int NOT NULL DEFAULT 0,
   `is_deleted` tinyint NOT NULL DEFAULT 0,
   `is_dynamic` tinyint NOT NULL DEFAULT 0,
   `items_id` int NOT NULL DEFAULT 0,
@@ @@
   `itemtype` varchar(255),
   `mountpoint` varchar(255),
   `name` varchar(255),
-  `totalsize` bigint NOT NULL DEFAULT 0,
+  `totalsize` int NOT NULL DEFAULT 0,
   PRIMARY KEY (`id`),
   KEY `date_creation` (`date_creation`),
   KEY `date_mod` (`date_mod`),
`

### Relevant log output

```shell
The database schema is not consistent with the current GLPI version.
It is recommended to run the "php bin/console database:check_schema_integrity" command to see the differences.
```

### Steps To reproduce

Do a migration from 10.0.14 to 10.0.15:
`sudo -u www-data /usr/bin/php8.2 bin/console db:update`

Check with:
`sudo -u www-data /usr/bin/php8.2 bin/console db:check_schema_integrity`

**Comment by trasher** [comment]
Duplicates #16991
