### ISSUE TITLE
The user is missing from the LDAP directory but remains active in GLPI.

### ISSUE THREAD

**Issue by vinilamelas** [glpi-project/glpi#17247]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

When we deactivate a user from LDAP in AD, GLPI shows as missing in the LDAP directory and keeps the user as active = yes in GLPI.

### Steps To reproduce

Go to AD and deactivate the user. Then, go to GLPI and force synchronization. Verify that the BASE DN shows the user as missing in the LDAP directory while remaining ACTIVE in GLPI.

**Comment by cconard96** [comment]
GLPI doesn't do anything to handle inactive LDAP users differently. GLPI only handles when a user/group is deleted from LDAP and when a user/group is restored (if you have a soft-delete feature like AD Recycle Bin enabled on your server).

**Comment by vinilamelas** [comment]
Hello,

Understood, I will analyze the AD.

Thanks for the quick response
