### ISSUE TITLE
error in debug mode

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1725]
glpi 9.2

in tickets 
PHP Notice: Undefined index: users_id in C:\inetpub\wwwroot\glpi\inc\ticket.class.php at line 6053

in computers

PHP Warning: Declaration of PluginFusioninventoryCollect::getSearchOptionsToAdd() should be compatible with CommonDBTM::getSearchOptionsToAdd($itemtype = NULL) in C:\inetpub\wwwroot\glpi\plugins\fusioninventory\inc\collect.class.php at line 0

2017-01-27 18:13:48 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc\rssfeed.class.php:101                          
  inc\commonglpi.class.php:263                       RSSFeed::canView()
  inc\html.class.php:1367                            CommonGLPI::getMenuContent()
  plugins\genericobject\front\object.form.php:102    Html::header()

**Comment by trasher** [comment]
```
PHP Warning: Declaration of PluginFusioninventoryCollect::getSearchOptionsToAdd() should be compatible with CommonDBTM::getSearchOptionsToAdd($itemtype = NULL) in C:\inetpub\wwwroot\glpi\plugins\fusioninventory\inc\collect.class.php at line 0
```
Is only relative to fusioninventory plugin. Won't fix.

```
2017-01-27 18:13:48 [@UNGSRVGVA118]
*** PHP Notice(8): Undefined index: glpiactiveprofile
Backtrace :
inc\rssfeed.class.php:101
inc\commonglpi.class.php:263 RSSFeed::canView()
inc\html.class.php:1367 CommonGLPI::getMenuContent()
plugins\genericobject\front\object.form.php:102 Html::header()
```

Seems related to genericobject plugin. Don't know if issue is on plugin side or core side.

**Comment by satyan01** [comment]
adn

**Comment by satyan01** [comment]
Hello I understood for others but for this one

in tickets
PHP Notice: Undefined index: users_id in C:\inetpub\wwwroot\glpi\inc\ticket.class.php at line 6053

**Comment by trasher** [comment]
This one is from the core, yes. 
I don't understand why you closed the ticket.

**Comment by satyan01** [comment]
because you told me when it is a different issue I have to create another issue . Thing that i have done, but you have closed it as well

**Comment by satyan01** [comment]
@trasher trasher referenced this issue 6 minutes ago
 Closed
during adding attachment in ticket in debug mode #1726

**Comment by trasher** [comment]
> because you told me when it is a different issue I have to create another issue 

I've never said that. Just said that one of the three notices you get was from a plugin.

**Comment by satyan01** [comment]
in older issue you told me that. but anyway
