### ISSUE TITLE
Simplified Interface - Ticket Fields can be changed but show error after pressing save

### ISSUE THREAD

**Issue by SimonTheIman** [glpi-project/glpi#17273]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

In the Ticket view of the Simplified Interface, the field `Category` and `Urgency` can be edited but show a permission error after pressing save, when the profile does not have the "Create" Permission.

Solution would be to make the fields "disabled", as the profile does not have the permission to save them anyway.

![image](https://github.com/glpi-project/glpi/assets/13744449/74939705-2225-486d-96cb-1a08f3fa04b0)
![image](https://github.com/glpi-project/glpi/assets/13744449/510ab3f2-38aa-4f6a-b1fc-8a5851f9d2da)
![image](https://github.com/glpi-project/glpi/assets/13744449/a67c0c0b-6096-4f0d-9610-c06d145094a4)

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Remove the permission `Create` from a profile with simplified interface.
2. Create a Ticket and view as user with that profile.
3. Change either of the fields `Category` or `Urgency` and press save.
4. Permission error is displayed.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.15 ( => /var/www/glpi_test)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux 5.15.0-107-generic #​117-Ubuntu SMP Fri Apr 26 12:26:49 UTC 2024 x86_64
PHP 8.2.19 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.59 (Ubuntu) (Apache/2.4.59 (Ubuntu) Server at ******* Port 443
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Server Software: Ubuntu 22.04
	Server Version: 10.6.16-MariaDB-0ubuntu0.22.04.1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi_test@localhost/glpi_test
	Host info: Localhost via UNIX socket
	
PHP version (8.2.19) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.6.16) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi_test/_cache has been validated.
Write access to /var/lib/glpi_test/_cron has been validated.
Write access to /var/lib/glpi_test has been validated.
Write access to /var/lib/glpi_test/_dumps has been validated.
Write access to /var/lib/glpi_test/_graphs has been validated.
Write access to /var/lib/glpi_test/_lock has been validated.
Write access to /var/lib/glpi_test/_pictures has been validated.
Write access to /var/lib/glpi_test/_plugins has been validated.
Write access to /var/lib/glpi_test/_rss has been validated.
Write access to /var/lib/glpi_test/_sessions has been validated.
Write access to /var/lib/glpi_test/_tmp has been validated.
Write access to /var/lib/glpi_test/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/glpi_test/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/glpi_test"
GLPI_CONFIG_DIR: "/etc/glpi_test/"
GLPI_VAR_DIR: "/var/lib/glpi_test"
GLPI_DOC_DIR: "/var/lib/glpi_test"
GLPI_CRON_DIR: "/var/lib/glpi_test/_cron"
GLPI_DUMP_DIR: "/var/lib/glpi_test/_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi_test/_graphs"
GLPI_LOCK_DIR: "/var/lib/glpi_test/_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi_test/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi_test/_plugins"
GLPI_RSS_DIR: "/var/lib/glpi_test/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi_test/_sessions"
GLPI_TMP_DIR: "/var/lib/glpi_test/_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi_test/_uploads"
GLPI_CACHE_DIR: "/var/lib/glpi_test/_cache"
GLPI_LOG_DIR: "/var/log/glpi_test"
GLPI_MARKETPLACE_DIR: "/var/www/glpi_test/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi_test/_locales"
GLPI_INVENTORY_DIR: "/var/lib/glpi_test/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/glpi_test/locales"
GLPI_VERSION: "10.0.15"
GLPI_SCHEMA_VERSION: "10.0.15@2eed74704cb07e0bac48b933cbd5c1c356f09629"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/glpi_test/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/glpi_test/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/glpi_test/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/glpi_test/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi_test/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi_test/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi_test/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/glpi_test/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/glpi_test/vendor/sabre/http/lib)
sabre/uri in (/var/www/glpi_test/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/glpi_test/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/glpi_test/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/glpi_test/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/glpi_test/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi_test/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/glpi_test/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/glpi_test/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi_test/vendor/symfony/console)
scssphp/scssphp in (/var/www/glpi_test/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/glpi_test/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/glpi_test/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/glpi_test/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/glpi_test/vendor/ramsey/uuid/src)
psr/log in (/var/www/glpi_test/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/glpi_test/vendor/psr/simple-cache/src)
psr/cache in (/var/www/glpi_test/vendor/psr/cache/src)
league/csv in (/var/www/glpi_test/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/glpi_test/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/glpi_test/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/glpi_test/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/glpi_test/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/glpi_test/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/glpi_test/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/glpi_test/vendor/symfony/cache)
html2text/html2text in (/var/www/glpi_test/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/glpi_test/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/glpi_test/vendor/symfony/dom-crawler)
twig/twig in (/var/www/glpi_test/vendor/twig/twig/src)
twig/string-extra in (/var/www/glpi_test/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/glpi_test/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/glpi_test/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/glpi_test/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/glpi_test/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Additional fields              Version: 1.21.8     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Behaviours                     Version: 1.4        State: Not installed                           
		Install Method: Manual
	formcreator          Name: Form Creator                   Version: 2.13.9     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Manual
	glpisaml             Name: Glpisaml                       Version: 1.1.5      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
Not a bug. Under specific conditions, the ticket requester is allowed to change certain parts of the ticket.
Conditions where a user can update a ticket:
- They are a requester
- Ticket isn't solved or closed
- There are no tasks or followups added yet
