### ISSUE TITLE
Action button dissappeared - over 1k consumables

### ISSUE THREAD

**Issue by Hevelious** [glpi-project/glpi#1728]
We have over 1000 usb mouses in our consumables, since reaching that 1k mark the action button disappeared because of "too large selection" even when you have for example 50 position display setting. I think this bug is connected to the paging feature implemented not so long time ago.

**Comment by trasher** [comment]
It seems indeed that the total count of elements in the database is used to (de)activate massive actions; I do not know if this is a real bug, or if there is a reason for that.

**Comment by trasher** [comment]
@orthagh what do you think of that?

**Comment by orthagh** [comment]
already agreed with you on another channel
