### ISSUE TITLE
Cisco stack reporting issue

### ISSUE THREAD

**Issue by bacus99** [glpi-project/glpi#17281]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

For some time, my Cisco switches are not reporting stacks properly.  It change around version 10.0.11, but I'm not sure
Now I have in most of the case 1 switch with all the ports in it.  Plus on random frequency, glpi-netinventory snmp update flush all my ports (And sometime change the name of the switch 0 (ex: Site-SW-01 to Site-SW-01 - 2)

### Relevant log output

```shell
188480424	2024-06-10 10:40	inventory	Last inventory date	Change 2024-06-10 08:02 to 2024-06-10 10:40
188455147	2024-06-10 08:02	inventory	Network port	Add an item: Network port (site-SW-01 - Gi3/1/4 (1743265))
188455145	2024-06-10 08:02	inventory	Network port	Add an item: Network port (site-SW-01 - Gi3/1/3 (1743264))
188455143	2024-06-10 08:02	inventory	Network port	Add an item: Network port (site-SW-01 - Gi3/1/2 (1743263))
188454884	2024-06-10 08:02	inventory	Firmware	Delete a component: C9200L-48P-4G-F (83683)
188454881	2024-06-10 08:02	inventory	Firmware	Add a component: C9200L-48P-4G-F (83684)
188454880	2024-06-10 08:02	inventory	Last inventory date	Change 2024-06-10 07:25 to 2024-06-10 08:02
188439063	2024-06-10 07:25	inventory	Last inventory date	Change 2024-06-10 07:19 to 2024-06-10 07:25
188436222	2024-06-10 07:19	inventory	Network port	Delete an item: Network port (site-SW-01 - Po1 (1740521))
188436221	2024-06-10 07:19	inventory	Network port	Delete an item: Network port (site-SW-01 - Vl599 (1740512))
188436219	2024-06-10 07:19	inventory	Network port	Delete an item: Network port (site-SW-01 - VLAN-599 (1740511))
188436218	2024-06-10 07:19	inventory	Network port	Delete an item: Network port (site-SW-01 - VLAN-440 (1740510))
188436217	2024-06-10 07:19	inventory	Network port	Delete an item: Network port (site-SW-01 - VLAN-421 (1740509))
```

### Steps To reproduce

Simply create an SNMP scan with glpi-netinventory, then scan

### Your GLPI setup information

GLPI is filling my logs (up to 30 GB) with this

2024-06-06 15:04:07] glpiphplog.WARNING:   *** PHP User Warning (512): Wired non unique! in /usr/share/glpi/src/NetworkPort_NetworkPort.php at line 273
  Backtrace :
  src/NetworkPort_NetworkPort.php:273                trigger_error()
  src/CommonDBTM.php:1297                            NetworkPort_NetworkPort->prepareInputForAdd()
  src/NetworkPort_NetworkPort.php:172                CommonDBTM->add()
  src/Inventory/Asset/NetworkPort.php:892            NetworkPort_NetworkPort->connectToHub()
  src/Inventory/Asset/NetworkPort.php:369            Glpi\Inventory\Asset\NetworkPort->handleHub()
  src/Inventory/Asset/NetworkPort.php:611            Glpi\Inventory\Asset\NetworkPort->handleMacConnection()
  src/Inventory/Asset/NetworkPort.php:633            Glpi\Inventory\Asset\NetworkPort->handleConnections()
  src/Inventory/Asset/NetworkPort.php:623            Glpi\Inventory\Asset\NetworkPort->portChanged()
  src/Inventory/Asset/InventoryNetworkPort.php:519   Glpi\Inventory\Asset\NetworkPort->portUpdated()
  src/Inventory/Asset/InventoryNetworkPort.php:121   Glpi\Inventory\Asset\NetworkPort->handleUpdates()
  src/Inventory/Asset/NetworkPort.php:835            Glpi\Inventory\Asset\NetworkPort->handlePortsTrait()
  src/Inventory/Asset/NetworkPort.php:618            Glpi\Inventory\Asset\NetworkPort->handlePorts()
  src/Inventory/Asset/MainAsset.php:1001             Glpi\Inventory\Asset\NetworkPort->handle()
  src/Inventory/Asset/MainAsset.php:916              Glpi\Inventory\Asset\MainAsset->handleAssets()
  src/Inventory/Asset/NetworkEquipment.php:231       Glpi\Inventory\Asset\MainAsset->rulepassed()
  src/RuleImportAsset.php:981                        Glpi\Inventory\Asset\NetworkEquipment->rulepassed()
  src/Rule.php:1531                                  RuleImportAsset->executeActions()
  src/RuleCollection.php:1660                        Rule->process()
  src/Inventory/Asset/MainAsset.php:582              RuleCollection->processAllRules()
  src/Inventory/Inventory.php:724                    Glpi\Inventory\Asset\MainAsset->handle()
  src/Inventory/Inventory.php:355                    Glpi\Inventory\Inventory->handleItem()
  ...inc/communicationnetworkinventory.class.php:170 Glpi\Inventory\Inventory->doInventory()
  marketplace/glpiinventory/hook.php:1088            PluginGlpiinventoryCommunicationNetworkInventory->import()
  src/Plugin.php:1730                                plugin_glpiinventory_network_inventory()
  src/Inventory/Request.php:280                      Plugin::doHookFunction()
  src/Inventory/Request.php:252                      Glpi\Inventory\Request->network()
  src/Inventory/Request.php:98                       Glpi\Inventory\Request->networkInventory()
  src/Agent/Communication/AbstractRequest.php:332    Glpi\Inventory\Request->handleAction()
  src/Agent/Communication/AbstractRequest.php:269    Glpi\Agent\Communication\AbstractRequest->handleXMLRequest()
  front/inventory.php:95                             Glpi\Agent\Communication\AbstractRequest->handleRequest()
  ...tplace/glpiinventory/front/communication.php:72 include_once()
  marketplace/glpiinventory/index.php:45             include_once()

### Anything else?

It worked perfectly some time ago, but I did not check back network devices often.

I tried:

- Delete all network assets
- flush networkport table
- reset rules
The only common point in my situation is my firewall is wire connected on the 3 nodes of my switch (port 1/1 on switch a-b-c for exemple)

Using either SNMPv3 or SNMP v2c, same behavior

**Comment by trasher** [comment]
Plese provide XML/JSON inventory file we can use to reproduce.

**Comment by steph461** [comment]
@hello bacus99

i have bug similary Stack 2 or 3 or 4 or 5

Try this command : 

1) glpi-netdiscovery.bat --host YourIP --credentials version:3,username:username,authprotocol:SHA,authpassword:XXXXXX,privprotocol:AES128,privpassword:XXXXXXX -i -s c:\folder

2) delete the stack and purge, its very important

3) Import only in the c:\folder\netinventory\yourip.xml

4) import
![image](https://github.com/glpi-project/glpi/assets/68054991/b7aee6fd-1581-46df-a611-eed85d0a7320)

5) Normally it's ok

6) perform an update, you lose the information
I lose the information on all my stacks

I have this bug for 10.0.3

example : 

before
![image](https://github.com/glpi-project/glpi/assets/68054991/569cf40e-68b9-42f3-80b1-4449a16190d4)


if i udpate  ( after): 
![image](https://github.com/glpi-project/glpi/assets/68054991/121f8179-0bee-4c26-bf42-591a18236de4)

**Comment by bacus99** [comment]
xml is coming, exactly my behavior

**Comment by bacus99** [comment]
Did your test full, with --debug

[debug] #1, switching SNMP context to vlan 401
[debug] #1, Netinventory worker terminated
[debug] #1, #1, worker termination
[debug] #1, Netdiscovery worker terminated


You have this message?

**Comment by bacus99** [comment]
[networkequipment_4_4977 1.txt](https://github.com/user-attachments/files/15794284/networkequipment_4_4977.1.txt)
Here's the SML

**Comment by trasher** [comment]
I cannot see your original issue with provided XML. With this one, there is only one network equipment imported; with one port in it.

>  Plus on random frequency, glpi-netinventory snmp update flush all my ports (And sometime change the name of the switch 0 (ex: Site-SW-01 to Site-SW-01 - 2)

This looks like a rule issue.

@steph461 please provide inventory file to reproduce.

**Comment by bacus99** [comment]
So you are right, it's not the common point.  I reset the rules, still add/remove the ports and don't see 2 switches.  Just found in my file that we DON'T see the second serial number switch like I can see in Orion
![image](https://github.com/glpi-project/glpi/assets/11425241/d170ef47-e3dd-46da-b971-bc94eff3abaa)

I'll do more tests, but it makes sense it will not create the second switch... Now why

**Comment by bacus99** [comment]
@steph461 not 100% sure if related, but I have 2 sites OK

My faulty switches: Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 16.9.4
My good switches: Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 17.6.5

What is the version of your switches?

**Comment by steph461** [comment]
> @steph461 not 100% sure if related, but I have 2 sites OK
> 
> My faulty switches: Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 16.9.4 My good switches: Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 17.6.5
> 
> What is the version of your switches?

Aruba 2930F VSF VC, revision WC.16.10.0009,

**Comment by steph461** [comment]
When you have test, you took the files in the folder in the picture
![image](https://github.com/glpi-project/glpi/assets/68054991/03baee97-7408-4da2-a39e-b7862a2c930b)

**Comment by trasher** [comment]
> My faulty switches: Cisco IOS Software [Fuji], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 16.9.4 My good switches: Cisco IOS Software [Bengaluru], Catalyst L3 Switch Software (CAT9K_LITE_IOSXE), Version 17.6.5

That looks like an issue on switch support on agent side. Please open a discussion on agent repository.

**Comment by bacus99** [comment]
OK based on my tests, agent 1.9 installed on Linux

glpi-netdiscovery --first 172.16.10.1 --last 172.16.10.254 --credentials version:2c,community:community1 --credentials version:2c,community:community2 --credentials version:2c,community:public --credentials 'version:3,username:snmp-glpi,authprotocol:SHA,authpassword:aaaa,privprotocol:AES,privpassword:ssss' --debug --control --backend-collect-timeout 30 --timeout 5 --retries 1 --threads 10000 -i -s /tmp

glpi-injector --no-ssl-check -v --recursive --directory /tmp/netinventory -u https://glpi.mycompany/glpi/marketplace/glpiinventory/

Import all switches with stacks

From GLPI inventory interface, stack are single switch and delete ports after few passes
