### ISSUE TITLE
The transfer operation creates new location entries linked to the target entity

### ISSUE THREAD

**Issue by tabad** [glpi-project/glpi#1729]
# The environment

  * Server Side
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2
           * Clean/Empty Database
           * No Plugins Installed or Enabled

This is the [information about system installation and configuration](https://github.com/glpi-project/glpi/files/738530/Information-about-system-installation-and-configuration.txt).

# The issue

The transfer operation of an object, for example a computer, creates on the target entity the same location tree structure which the object is linked on the source entity.

The transfer operation should not take into account the location field of the object because is very improbably than the target entity has the same location structure than the source entity. In fact, transfer rules (*Home > Administration > Rules > Transfer*) do not allow configure any option for locations.

    Note: The issue was detected in GLPI v0.84.8.

I think should be two possible solutions to this issue

* Do not take into account locations in transfer operations or
* Give the possibility of configure the location behaviour into transfer rule definitions
 
# The test

In this scene

* *Administration > Entities*

 |         Complete Name          |
 |--------------------------------|
 | #                              |
 | # > Teclib                     |
 | # > Teclib > France            |
 | # > Teclib > France > Paris    |
 | # > Teclib > Spain             |
 | # > Teclib > Spain > Barcelona |

* *Setup > Dropdowns > Locations*

 |         Complete Name        |             Entity             |
 |------------------------------|--------------------------------|
 | Avenida Diagonal             | # > Teclib > Spain > Barcelona |
 | Avenida Diagonal > Warehouse | # > Teclib > Spain > Barcelona |
 | Rue de Cambrai               | # > Teclib > France > Paris    |
 | Rue de Cambrai > Datacenter  | # > Teclib > France > Paris    |

* *Assets > Computers*

 |   Name  |             Entity          | Manufacturer |        Model       |          Location           |
 | ------- | --------------------------- | ------------ | ------------------ | --------------------------- |
 | srv0001 | # > Teclib > France > Paris |  Supermicro  | SuperServer 2028TP | Rue de Cambrai > Datacenter |

the computer *srv0001* is transfered from entity *# > Teclib > France > Paris* to entity *# > Teclib > Spain > Barcelona* using the *complete* transfer rule. It seems to be well because the computer have been actually tranfered but this has happend.

* *Assets > Computers*

 |   Name  |              Entity            | Manufacturer |        Model       |             Location            |
 | ------- | ------------------------------ | ------------ | ------------------ | ------------------------------- |
 | srv0001 | # > Teclib > Spain > Barcelona |  Supermicro  | SuperServer 2028TP | **Rue de Cambrai > Datacenter** |

* *Setup > Dropdowns > Locations*

 |           Complete Name         |                Entity              |
 |---------------------------------|------------------------------------|
 | Avenida Diagonal                | # > Teclib > Spain > Barcelona     |
 | Avenida Diagonal > Warehouse    | # > Teclib > Spain > Barcelona     |
 | Rue de Cambrai                  | # > Teclib > France > Paris        |
 | **Rue de Cambrai**              | **# > Teclib > Spain > Barcelona** |
 | Rue de Cambrai > Datacenter     | # > Teclib > France > Paris        |
 | **Rue de Cambrai > Datacenter** | **# > Teclib > Spain > Barcelona** |

Not only has not changed the location of the computer, but it also created two new locations linked to *# > Teclib > Spain > Barcelona* entity.

**Comment by tabad** [comment]
Hello again,

It's passed some time since the last change of this issue and there aren't any news about it. The last news was that this issue was planned for 9.2 release but it's unscheduled yet.

Please, please... and please ;) , take it into account for the next v9.2.3 or, perhaps, for the next v9.2.4 but not more over.

Thanks in advance,

**Comment by trasher** [comment]
This seems to be a quite huge change, and it may be complex to achieve. For now, it stays uplanned

**Comment by spamy** [comment]
Hello to everyone,

This problem does not allow to move any asset to another location because it would generate a huge problem in our structure and nowadays locations can not been used.

I kept hope since I saw this message of modification ->  "@trasher trasher modified the milestones: Candidate for next major version, 9.2 on Sep 12, 2017 "
But I have recently updated my GLPI to 9.2.3 and I can confirm that this issue continues. 

Regards.

**Comment by tabad** [comment]
Long, long time ago I wrote this issue hoping some compassionate human being make it happen. Since then, GLPI has grown from its *9.1* to its brand-new *9.4* years old but, surprisingly, it continues without to implement my desire and need. :astonished:

Nowadays, although some years older, I continue with the hope than some day,  some compassionate human being, makes it happen. :innocent: Please, take into account Christmas is close and it's time for presents and love. :christmas_tree: :revolving_hearts:

To end, what do you understood for `Candidate for next major version`?

Best regards,

P.D. Note that it's written from affection. Please, do not misinterpret. :wink:
