### ISSUE TITLE
Tickets with tasks that havent been closed...can still be closed.

### ISSUE THREAD

**Issue by bturnbough81** [glpi-project/glpi#17306]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.15

### Bug description

A ticket that contains tasks that haven't been closed (checked) can still be closed.

This should not be possible.

### Steps To reproduce

Open a ticket.
Add a task.
Close the ticket.

### Anything else?

It should not be possible for a user to close a ticket unless ALL tasks are closed.

**Comment by cconard96** [comment]
Not a bug. Please use the suggestions website to propose adding this limitation or use the "behaviors" plugin to enable this behavior.

https://suggest.glpi-project.org
