### ISSUE TITLE
Simplified Interface -  when displaying logs in timeline, the user that did the action is not shown

### ISSUE THREAD

**Issue by prigaux** [glpi-project/glpi#17334]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.14

### Bug description

When you choose to see "History" events, it does not show the user that did the action.

Here is a simple suggested change: https://github.com/glpi-project/glpi/commit/0314f04de9a780b20c2081e913d9082106cdf158 (tested in production)

NB: the change only handle "user" events. Actions from non-users are still shown. The log "user_name" field could also be displayed somewhere...

**Comment by prigaux** [comment]
Current behavior:
![image](https://github.com/glpi-project/glpi/assets/1790460/8b5cda67-3be1-452c-99a8-1baa690dfd53)

Suggested behavior:
![image](https://github.com/glpi-project/glpi/assets/1790460/9db22440-70bc-4b1c-ba2e-91ed98d08079)

**Comment by trasher** [comment]
Could you please open a pull request with proposed change? Thank you.

**Comment by prigaux** [comment]
Sure : https://github.com/glpi-project/glpi/pull/17337

**Comment by cconard96** [comment]
Fixed by merged PR #17337.
