### ISSUE TITLE
Super-admin ERROR_RIGHT_MISSING

### ISSUE THREAD

**Issue by Gizmodo** [glpi-project/glpi#17359]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.13

### Bug description

My user has Super-Admin profile:
![image](https://github.com/glpi-project/glpi/assets/1078610/346d55a5-ab8e-4086-866f-f632bbb2e691)
When I perform REST API request {{baseurl}}/apirest.php/Ticket/233554 response is:
403
[
	"ERROR_RIGHT_MISSING",
	"You don't have permission to perform this action."
]
Same error on Web
![image](https://github.com/glpi-project/glpi/assets/1078610/e2a17f49-6855-443e-b245-f3f19c2d0347)

But if I switch profile to simple user with less rights, then I can view ticket 
![image](https://github.com/glpi-project/glpi/assets/1078610/48396af9-8d3d-499e-bbd6-689b188da04b)
and perform REST API request with success response:
![image](https://github.com/glpi-project/glpi/assets/1078610/0091d836-e4fd-4315-a527-1f54a81863e4)

### Your GLPI setup information

[code]   GLPI 9.5.13 ( => /var/www/html) Installation mode: TARBALL Current language:en_GB
--

Operating system: Linux glpi 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 PHP 7.2.24-0ubuntu0.18.04.17 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, 	ldap, libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, recode, session, shmop, 	sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="4M"  Software: Apache/2.4.57 (Ubuntu) (Apache/2.4.57 (Ubuntu) Server at glpi.44it.ru Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.4.31-MariaDB-1:10.4.31+maria~ubu1804-log 	Server SQL Mode:  	Parameters: root@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.4.31) - Perfect!  The log file has been created successfully. Write access to /var/www/html/files/_cache has been validated. Write access to /var/www/html/config has been validated. Write access to /var/www/html/files/_cron has been validated. Write access to /var/www/html/files has been validated. Write access to /var/www/html/files/_dumps has been validated. Write access to /var/www/html/files/_graphs has been validated. Write access to /var/www/html/files/_lock has been validated. Write access to /var/www/html/files/_pictures has been validated. Write access to /var/www/html/files/_plugins has been validated. Write access to /var/www/html/files/_rss has been validated. Write access to /var/www/html/files/_sessions has been validated. Write access to /var/www/html/files/_tmp has been validated. Write access to /var/www/html/files/_uploads has been validated. Write access to /var/www/html/marketplace has been validated. Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

GLPI_ROOT: /var/www/html GLPI_CONFIG_DIR: /var/www/html/config GLPI_VAR_DIR: /var/www/html/files GLPI_MARKETPLACE_DIR: /var/www/html/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  PHP Notice (8): Array to string conversion in /var/www/html/inc/config.class.php at line 1969GLPI_SERVERSIDE_URL_ALLOWLIST: Array GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/files GLPI_CACHE_DIR: /var/www/html/files/_cache GLPI_CRON_DIR: /var/www/html/files/_cron GLPI_DUMP_DIR: /var/www/html/files/_dumps GLPI_GRAPH_DIR: /var/www/html/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales GLPI_LOCK_DIR: /var/www/html/files/_lock GLPI_LOG_DIR: /var/www/html/files/_log GLPI_PICTURE_DIR: /var/www/html/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins GLPI_RSS_DIR: /var/www/html/files/_rss GLPI_SESSION_DIR: /var/www/html/files/_sessions GLPI_TMP_DIR: /var/www/html/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/locales GLPI_VERSION: 9.5.13 GLPI_SCHEMA_VERSION: 9.5.7 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2022

htmlawed/htmlawed version 1.2.5 in (/var/www/html/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.6.5 in (/var/www/html/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/vendor/sabre/http/lib) sabre/uri in (/var/www/html/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/vendor/symfony/console) scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src) psr/log in (/var/www/html/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src) phpCas version 1.3.3 in (/usr/share/php)

archimap             Name: Diagrams                       Version: 3.0.3      State: Installed / not activated 	gappessentials       Name: Gapp Essentials                Version: 1.2.0      State: Not installed 	screenshot           Name: Screenshot                     Version: 1.1.2      State: Not installed 	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Installed / not activated 	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Installed / not activated 	xivo                 Name: xivo                           Version: 1.0.0      State: Not installed 	fields               Name: Дополнительные поля    Version: 1.12.0     State: Installed / not activated 	dashboard            Name: Панель отчетов              Version: 0.9.6      State: Enabled 	tasklists            Name: Список задач                  Version: 1.6.2      State: Installed / not activated 	timelineticket       Name: Сроки заявок                  Version: 9.4+1.0    State: Not installed 	news                 Name: Уведомления                   Version: 1.8.1      State: Enabled
[/code]

**Comment by cconard96** [comment]
GLPI 9.5 versions aren't supported officially anymore and we only track bugs for supported versions on GitHub. If you upgrade to the latest 10.0 version and still have this issue, then you can try re-opening this issue report. Otherwise, you can make a post on the community forum to get help with this version.
