### ISSUE TITLE
Incorrect integer value: '' for column `glpi`.`glpi_documents`.`is_recursive` at row 1

### ISSUE THREAD

**Issue by Cornitus** [glpi-project/glpi#17379]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

When I want to upload a document I get this error message in /var/www/glpi/files/_log/sql-errors.log:

Error: Incorrect integer value: '' for column `glpi`.`glpi_documents`.`is_recursive` at row 1

The part "is_recursive" does not contain a value. Neither 1 nor 0.

Backtrace :
src/DBmysql.php:1380 DBmysql->doQuery()
src/CommonDBTM.php:729 DBmysql->insert()
src/CommonDBTM.php:1342 CommonDBTM->addToDB()
front/document.form.php:58 CommonDBTM->add()
public/index.php:82 require()

### Relevant log output

```shell
*** MySQL query error:
  SQL: INSERT INTO `glpi_documents` (`documentcategories_id`, `entities_id`, `is_recursive`, `users_id`, `name`, `mime`, `filename`, `filepath`, `sha1sum`, `tag`, `date_creation`, `date_mod`) VALUES ('6', '0', '', '7', 'Dokument: TEST', 'text/xml', 'TEST.xml', 'XML/19/0eda921758e09f3ca50b4fde34ebaed20e8d9c.XML', '190eda921758e09f3ca50b4fde34ebaed20e8d9c', '00eeedfc-b2d8e96f-667d639d5bf511.02695448', '2024-06-27 15:05:36', '2024-06-27 15:05:36')
  Error: Incorrect integer value: '' for column `glpi`.`glpi_documents`.`is_recursive` at row 1
  Backtrace :
  src/DBmysql.php:1380                               DBmysql->doQuery()
  src/CommonDBTM.php:729                             DBmysql->insert()
  src/CommonDBTM.php:1342                            CommonDBTM->addToDB()
  front/document.form.php:58                         CommonDBTM->add()
  public/index.php:82                                require()
  {"user":"7@glpi"}
```

### Page URL

https://glpi.domain.test/front/softwarelicense.form.php?id=17

**Comment by Cornitus** [comment]
After updating to version 10.0.16 the same problem still exists. It is currently not possible to use the program.

**Comment by Cornitus** [comment]
The problem still exists. If I run mariadb with sql_mode=NO_ENGINE_SUBSTITUTION then it works. But that can't be the solution and it hasn't been necessary for the last 3 years. Why is the field for 'is_recursive" empty? If it were filled with 0 or 1, the problem wouldn't exist.

**Comment by cedric-anne** [comment]
I am not able to reproduce. Could you please provide a detailled way to reproduce it ? Also, please fill requested information, like the list of your plugins.
