### ISSUE TITLE
When updating related components in devices, such as external storage disks, the old ones are deleted and not kept in the inventory

### ISSUE THREAD

**Issue by Moh417** [glpi-project/glpi#17371]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.14

### Bug description

When updating related components in devices, such as external storage disks, the old ones are deleted and not kept in the inventory, and this thing must be kept private, like the disks for the backup process. Is there a solution to this problem so that when the components are updated, they are not deleted?
![Screenshot 2024-06-27 085913](https://github.com/glpi-project/glpi/assets/138872978/0e26add5-9a55-4180-a804-04258acef4d8)

**Comment by trasher** [comment]
First check with laetst GLPI release if you reproduce. If you do, we need example inventories files to reproduce the issue.
