### ISSUE TITLE
the requester email does not matter

### ISSUE THREAD

**Issue by montoia** [glpi-project/glpi#17384]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

I have the following situation in GLPI.
I import tickets by email using mailgate, for users who have registered with GLPI, when imported, they come as applicant normally. But when I have an email that I don't have registered, for example fulano@gmail.com, the ticket is imported but the applicant is discarded. In previous versions the email was displayed and now it is anonymous and we don't know who created it.

### Steps To reproduce

1) I created a ticket via email, it should not be in the user base
2) Let it import via the mailgate method
3) See the ticket created, it will be without applicant data

### Anything else?

Creating a ticket from an unregistered email.
Is it normal behavior to hide? I ask because how will I know who requested it.
![email-ticket](https://github.com/glpi-project/glpi/assets/16062199/c859c9b5-a621-42fb-acdf-0cb20c306287)

**Comment by montoia** [comment]
Any corrections planned?

**Comment by montoia** [comment]
Any corrections planned?

**Comment by martinaluna** [comment]
Hi, I have the same problem 
![imagen](https://github.com/user-attachments/assets/b3ed1609-60d6-4ea5-84b6-ca6fce482173)

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce the issue. Could you do a test on the [GLPI 10.0 nightly build](https://nightly.glpi-project.org/glpi/) and witout any active plugin ?

**Comment by cedric-anne** [comment]
The name displayed in the ticket description header can only corresponds to a real user. So in case a ticket is created by someone that is not registered as a GLPI user, nothing is displayed.

I did not remember how it was displayed in GLPI 9.x.

**Comment by martinaluna** [comment]
Cedric

I have tested this problem in glpi version 10.0.16 with all plugins disabled and it works correctly. It is likely that one of the plugins installed in the other glpi is interfering with the workflow of the tool

@montoia what plugins do you have activated?

**Comment by montoia** [comment]
> martinaluna

fields > https://github.com/pluginsGLPI/fields
behaviors > https://github.com/yllen/behaviors
Form Creator > https://pluginsglpi.github.io/formcreator/
pdf > https://github.com/yllen/pdf
satisfaction > https://github.com/pluginsGLPI/satisfaction
oauthimap > https://github.com/pluginsGLPI/oauthimap/
tasklists > https://github.com/InfotelGLPI/tasklists
webapplications > https://github.com/InfotelGLPI/webapplications

I'm on version 10.0.15.
I will validate if it is a plugin that is affecting

**Comment by montoia** [comment]
The problem was the plugin's behavior. The option "Use the applicant's group" was set to "First". When changing to no it returned to normal import.

I thank everyone for the support.
![image](https://github.com/user-attachments/assets/40860d65-7aa1-4d22-9232-ef6640e6e9b6)
