### ISSUE TITLE
Portuguese (Portugal) translation not working

### ISSUE THREAD

**Issue by moodyblue** [glpi-project/glpi#17386]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

If I select Portuguese (Portugal) as the language, Portuguese (Brazil) is used instead.

**Comment by moodyblue** [comment]
Closing temporarily for further analysis

**Comment by cconard96** [comment]
If there are issues with the actual translations, rather than an issue with the wrong language being selected, you can fix the translations on Transifex. You would need to create an account and request access to the language to be able to make changes.
https://explore.transifex.com/glpi/GLPI/

**Comment by moodyblue** [comment]
Thanks. It was my mistake. And yes, I've started reviewing translations in transifex.
