### ISSUE TITLE
E-mail alert although the stock target is 0

### ISSUE THREAD

**Issue by FreeMacs** [glpi-project/glpi#17388]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

I have changed the stock target for a cartridge model from 1 to 0 and Alert to never because I no longer need email alerts from this model. However, I have still been receiving emails from this cartridge for weeks. The email also says that the stock target is set to 1 although it is set to 0 in GLPI itself. 
<img width="374" alt="image" src="https://github.com/glpi-project/glpi/assets/115316656/13b46f1d-abed-4cbc-a645-0b801e89ad80">
Everything is set to 0 and never in the cartridge asset
<img width="807" alt="Screenshot 2024-07-01 082733" src="https://github.com/glpi-project/glpi/assets/115316656/dee9e6b1-2fe7-4971-8f16-8825d11c420f">
There is also no default value set in the entity
<img width="313" alt="image" src="https://github.com/glpi-project/glpi/assets/115316656/a0d0c169-33a1-4f18-922a-d077539a28c6">
The email alert still shows a stock target of 1

**Comment by cconard96** [comment]
The stock target being 1 instead of 0 is intended, although maybe not as intuitive as I originally thought. See my description of the feature in the related PR (#9687).

For why the alert keeps triggering, I haven't been able to recreate the issue or find a potential cause.
