### ISSUE TITLE
The field of serial number of license need to change

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1738]
The field of serial number of license need to change on product key of license. Otherwise this is not logical.

![glpi - computers - pruduct key - mozilla firefox 2017-01-31 10 49 37](https://cloud.githubusercontent.com/assets/17082164/22457563/31a4676c-e7a9-11e6-84d4-8df8041b8e7c.png)
![glpi - licenses -product key - mozilla firefox 2017-01-31 10 51 25](https://cloud.githubusercontent.com/assets/17082164/22457565/33be844c-e7a9-11e6-8d94-4bf6d83791d7.png)

Example license stickers:
![example product key](https://cloud.githubusercontent.com/assets/17082164/22457567/34e0efc2-e7a9-11e6-9da6-667170cbd813.png)

**Comment by AircraftRu** [comment]
Hello, 
will you answer me by the issue?

**Comment by AircraftRu** [comment]
Hi, you have the ability to change this field according to the logic?

**Comment by orthagh** [comment]
Hello @AircraftRu .

I don't understand your issue.
Is it the label that bother you ?

**Comment by AircraftRu** [comment]
It's not right. Correctly not the Serial number, but the license key.
Thank you.

**Comment by remicollet** [comment]
The field is "Serial Number"
If you put something else inside, this is not a GLPI bug
If you use OCS of Fusion, probably to be reported to these projects.

**Comment by AircraftRu** [comment]
And where to write down the "Product Key" ?

**Comment by AircraftRu** [comment]
Hello. I propose to add the field "Product Key" that is right.
