### ISSUE TITLE
[9.1.2] at ticket creation the hardware type list is not linked with the current entity (tree structure)

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1739]
Hello,

Let's consider the following:

- entity structure:
Root > Global > Company A > Department A

- and computer list:
Computer A in entity Department A, and user is me
Monitor A in entity Department A, and user is me

Then

1. Create new ticket, and select entity to be 'Department A', in this case the 'Hardware type' list will contains Computer A and Monitor A: OK

1. Change entity to 'Global', in this case the 'Hardware type' list is also empty: OK

1. Change entity to 'Global (tree structure)', in this case the 'Hardware type' list is empty: NOK

![image](https://cloud.githubusercontent.com/assets/7569958/22459492/1322f3c4-e7a1-11e6-9371-45eccc41d3c0.png)

For me in case 3, the list should contains the same items than with case 1,

thank you,
regards,
Tomolimo

**Comment by orthagh** [comment]
> For me in case 3, the list should contains the same items than with case 1.

No. I could misunderstand your need, but items associated with tickets must be in the same entity.
In your screenshot example, the ticket will be created in "Global" entity, so we need to have only items from this entity. 

Without talking about your instance, GLPI permits to have the next scenario
- Self-service user with a tree of entities
- Technicians with a single entity (the upper one for example)
In this case, the technicians wont be able to see linked items.

If you need to associate item from "Departement A", your ticket should be in this entity.

In 9.2 we added is_recursive in computer (mainly for templates), so we could consider adding upper items (with is_recursive = 1).

Generally, in GLPI, we don't go down in entities from objects without recursivity

**Comment by tomolimo** [comment]
> In 9.2 we added is_recursive in computer (mainly for templates), so we could consider adding upper items (with is_recursive = 1).

In fact: as far as I can see (and test), this is already the case in the 9.1.2: it's possible to link the ticket (created in Global entity) with a computer in Root entity (the generated SQL query will do this), as soon as the is_recursive=1.
![image](https://cloud.githubusercontent.com/assets/7569958/22498318/dee15fe4-e857-11e6-96de-691f4eff3c1d.png)


> Generally, in GLPI, we don't go down in entities from objects without recursivity

In the case 3, GLPI doesn't respect the tree structure (=recursivity) from the current entity `Global (tree structure)`. 

Should I cancel my PR?

**Comment by orthagh** [comment]
> In fact: as far as I can see (and test), this is already the case in the 9.1.2: it's possible to link the ticket (created in Global entity) with a computer in Root entity (the generated SQL query will do this), as soon as the is_recursive=1.

Indeed, it was for 9.1 version, i though it was more recent.

> In the case 3, GLPI doesn't respect the tree structure (=recursivity) from the current entity Global (tree structure).

i'm not sure about this affirmation.
I consider that the item list should inherit the ticket entity and not the global (i mean the global selector) one. 
My opinion, current entity of the ticket is inherited from the global selector, but as the ticket didn't have any recursivity property (and i don't think we want to add it), i think we shouldn't display in this list the items from parent entities to avoid potential 'no access' issues.

> Should I cancel my PR?

for me, yes.
