### ISSUE TITLE
Can't use a random parameter to force reload of javascript in plugins 

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1742]
Hello,

In the past, it was possible to force reload of javascript files by browser using a trick: to add a random parameter to the script name like:
$PLUGIN_HOOKS['add_javascript']['myplugin']="js/myscript.js?rnd=$rand";
This is no longer possible due to the tests used for including files, in html.class.php line 1255
`if (file_exists(GLPI_ROOT."/plugins/$plugin/$file")) {`

This trick is mandatory to force Chrome to reload javascript files, otherwise it will use file in memory cache.

I'm going to provide a fix for it.

thank you
regards,
Tomolimo

**Comment by trasher** [comment]
Plugin version is added as a parameter from core; is that not enough?

**Comment by tomolimo** [comment]
where is it?

**Comment by tomolimo** [comment]
anyway it will not be enough, as Chrome doesn't reload javascript at all, even when you set the usual HTTP header to force reload. The only fix to this is to use a random parameter passed to javascript in the script tag.

**Comment by trasher** [comment]
In script() and css() methods (https://github.com/glpi-project/glpi/blob/master/inc/html.class.php#L4969).

And it should be enough since the script files are not going to change when a plugin is released. You're talking about a developer issue. So my guess is to ask GLPI to add that random param when using debug mode.

**Comment by tomolimo** [comment]
Your are in the master, don't you?

> And it should be enough since the script files are not going to change when a plugin is released.

I've got some javascript files that are dynamically computed by PHP files, and the content is not always the same, it depends on the context, so I need this random value passed to the generating file.

**Comment by trasher** [comment]
> Your are in the master, don't you? 

Yes. And proposed changes would kind of "break" it btw.

> I've got some javascript files that are dynamically computed by PHP files

Yes, several plugins are already doing this as far as I know.
Changes in core are 2 or 3 years old; I'm surprised nobody complains about this kind of issues since that's been changed.

**Comment by tomolimo** [comment]
The problem is only with Chrome
