### ISSUE TITLE
Post Migration the network ports not appear again

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#17438]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.15

### Bug description

The issue #11713 was closed, but it happens again.

### Relevant log output

[2024-07-04 10:56:36] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getType() on bool in /var/www/html/glpi/src/NetworkPort.php at line 1171
  Backtrace :
  src/NetworkPort.php:891                            NetworkPort->showPort()
  src/NetworkPort.php:1880                           NetworkPort::showForItem()
  src/CommonGLPI.php:694                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()

**Comment by trasher** [comment]
Just linking a 2 years old issue... Please provide all requested information, and a clear way to reproduce on a fresh GLPI 10.0.16 install.

**Comment by jsamaniegog** [comment]
Log:

[2024-07-04 10:56:36] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getType() on bool in /var/www/html/glpi/src/NetworkPort.php at line 1171
  Backtrace :
  src/NetworkPort.php:891                            NetworkPort->showPort()
  src/NetworkPort.php:1880                           NetworkPort::showForItem()
  src/CommonGLPI.php:694                             NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()


Solution:
[https://github.com/glpi-project/glpi/issues/11713#issuecomment-1141895399](https://github.com/glpi-project/glpi/issues/11713#issuecomment-1141895399)

**Comment by stonebuzz** [comment]
The associated device which cannot be loaded by GLPI (and which returns this error) is loaded from the ```glpi_networkports_networkports``` table.

This table must contain the ID of an asset that no longer exists in your GLPI.

You can empty this table (it will be rebuilt as the inventory comes up)

```DELETE FROM glpi_networkports_networkports```

Errors should no longer be made

**Comment by jsamaniegog** [comment]
Hi @stonebuzz,

thank you for your response.

I don't want to delete all because some links are manual. I have deleted the ones that do not exist, but it still shows the same error...

```sql
delete from glpi_networkports_networkports where networkports_id_1 not in (select id from glpi_networkports);
delete from glpi_networkports_networkports where networkports_id_2 not in (select id from glpi_networkports);
```

**Comment by stonebuzz** [comment]
maybe you have a line with `networkports_id_1` and `networkports_id_2` that do not exist in `glpi_networkports`

**Comment by jsamaniegog** [comment]
I have removed the links to assets of type PluginFusioninventoryUnmanaged and it seems to work now.

Final solution:
```sql
delete gnn.* 
from glpi_networkports_networkports gnn 
left join glpi_networkports gn on gnn.networkports_id_1 = gn.id
where gn.id is null or itemtype = 'PluginFusioninventoryUnmanaged';

delete gnn.* 
from glpi_networkports_networkports gnn 
left join glpi_networkports gn on gnn.networkports_id_2 = gn.id
where gn.id is null or itemtype = 'PluginFusioninventoryUnmanaged';
```

I must to migrate everything to GLPI inventory and remove Fusion Inventory as soon as possible

Thank you very much for your help.
