### ISSUE TITLE
A ticket cannot be answered by only one of the two technicians

### ISSUE THREAD

**Issue by Gor3pig** [glpi-project/glpi#17437]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Without having made any particular changes, I have a disparity in the way two technician users operate. This bug started with version **10.0.15**.

**How it works:**

**There are two technical users:**
- Jean
- Jacques

**There are two Entities:**
- Entity A (the global entity)
- Entity B (dedicated sub-entity for the two technicians : Jean and Jacques)

Jean and Jacques have **scrupulously** the same rights, the same settings, on the same entity. They also share the same ticket template, etc. Zero differences (I checked more than a dozen times)

**Bug description :**

When Jean receives a ticket, he can view them, he can close or archive them **and he can reply to the ticket**.

On the other hand, when Jacques receives a ticket, he can view them, he can close or archive them, but he can **NOT reply to them**. No "reply" button appears, nor even any elements in the right-hand sidebar (where there is the opening date, type of incident, etc.).

I should point out that for Jean and Jacques, tickets sent to him are sent via the "Form" plugin. It also benefits from identical settings at this level.

Before updates 10.0.15 (and 10.0.16) it could, which makes me think more of a bug than a setting problem.

**Comment by cconard96** [comment]
Please provide the requested GLPI log and setup information.
If the panel on the right is completely blank, there was probably a PHP error which would be in your GLPI logs.

**Comment by Gor3pig** [comment]
You're right, I've activated debug mode, and here's the error message that appears:

> Twig Error (Twig\Error\RuntimeError): "An exception has been thrown during the rendering of a template ("Empty IN are not allowed")." in template "/var/www/glpi/templates/components/itilobject/fields_panel.html.twig" at line 216

This is curious because it doesn't happen for the second user.

Thanks for your help Curtis,

**Comment by cedric-anne** [comment]
@Gor3pig 

Could you try to empty the `files/_cache/templates` directory and see if the problem persists ?

**Comment by Gor3pig** [comment]
> @Gor3pig
> 
> Could you try to empty the `files/_cache/templates` directory and see if the problem persists ?

The _cache folder is completely empty :
![01](https://github.com/user-attachments/assets/15092daf-e1a1-46af-a0e3-b98d606b07a3)

**Comment by cedric-anne** [comment]
Cache is probably stored in another location. Could you try to empty the directory defined in the `CLPI_CACHE_DIR` constant?

**Comment by Gor3pig** [comment]
> Cache is probably stored in another location. Could you try to empty the directory defined in the `CLPI_CACHE_DIR` constant?

Ok, indeed the path was in another place, I was able to empty _cache/templates.

Unfortunately, the problem is the same

**Comment by cedric-anne** [comment]
Could you try to execute the `bin/console glpi:cache:clear` command? It seems to have solved a similar issue (see #17239).

The weird thing is that you say that both users have the same rights. Are these rights declared in the same order? Are the same entities shown in the entity selector for both of them?

**Comment by Gor3pig** [comment]
> Could you try to execute the `bin/console glpi:cache:clear` command? It seems to have solved a similar issue (see #17239).
> 
> The weird thing is that you say that both users have the same rights. Are these rights declared in the same order? Are the same entities shown in the entity selector for both of them?

I had already cleaned the cache, no changes

Same rights, same access to entities yes

Thank you for your help :-)

**Comment by Gor3pig** [comment]
For your information, this is exactly the same problem as reported on the forum by another user:

[https://forum.glpi-project.org/viewtopic.php?id=289596](url)

**Comment by stonebuzz** [comment]
Hi @LucianaCabrera 

Hi @LucianaCabrera

To address this, you can try resetting the entity caches by running the following SQL query:

UPDATE glpi_entities SET ancestors_cache = null, sons_cache = null;

This query clears potential cache issues that might be affecting entity-related data display.

Best regards
