### ISSUE TITLE
[9.1.2] in notifications the ##ticket.url## will contain noAUTO=1

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1744]
Hello,

This is really a problem when using SSO mechanism...

Here is the template:

![image](https://cloud.githubusercontent.com/assets/7569958/22504586/669a9896-e877-11e6-8cd7-b5d70d13fdb6.png)

and here is the notification:

![image](https://cloud.githubusercontent.com/assets/7569958/22504642/a3521e9e-e877-11e6-987c-46a6a01f4f72.png)

The URL must not contains the noAUTO=1 parameter!

Thank you,
regards,
Tomolimo

**Comment by wawax** [comment]
Reference suggestion : http://glpi.userecho.com/topics/339-remove-noauto1-url-parameter-from-email-notifications/

**Comment by orthagh** [comment]
#1760 merged

**Comment by tomolimo** [comment]
Did you cherry-pick this to master branch?

**Comment by orthagh** [comment]
Yes, check here: https://github.com/glpi-project/glpi/commits/master

**Comment by nerocide** [comment]
Hello,

i had the same problem with in a SSO environnement, just to confirm to you, the patch is working fine.

Thank you
