### ISSUE TITLE
GLPI LDAP Sync Issue: The LDAP l Attribute is Not Synchronized with Subentities

### ISSUE THREAD

**Issue by CLcdiazp** [glpi-project/glpi#17448]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

"It would be beneficial to update GLPI to ensure that Active Directory attributes, such as the 'City' field (l), synchronize correctly according to configured rules. Currently, even when the main entity rule specifies that all LDAP synchronization should go to the subentity, the City field synchronizes to the main entity, causing duplication issues with locations. Enhancing the synchronization rule interpretation could resolve this issue and optimize location management within GLPI. Additionally, when one needs to provide location statistics for the user who generated a request or incident, the field appears blank because the users are in different subentities. This issue was previously posted at https://github.com/glpi-project/glpi/issues/9287 but no solution or improvement was provided."
![atributos](https://github.com/glpi-project/glpi/assets/129112079/0fc154e7-9400-440b-ba49-1bd35d808ec8)

**Comment by trasher** [comment]
Duplicates #9287

**Comment by CLcdiazp** [comment]
Since it will be duplicated, they are different versions
