### ISSUE TITLE
create an incident from a change

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1745]
Hello

the case :+1: 
a change has been done to migrate exchange 2010 to 2013
many incident after this migration have been opened
these incidents come from the change "exchange migration"

Would it be possible to add in change form : 
create an incident due to change or attached incident due to change ?

Thank you for your answer

**Comment by tyronewyatt** [comment]
+1 from me.

Could this be expanded to include create an incident from a problem too?

http://glpi.userecho.com/topics/38-create-a-ticket-from-a-problem/

**Comment by yllen** [comment]
From a change or a problem, you can add a ticket.
It's not logic to do in other sense.
You create a ticket -> this ticket can create a problem -> this problem need a change

**Comment by satyan01** [comment]
Hello

As I writed above, migration for exchange, we create a change, during this change an incident happens.

It is logic and ITIL compliant
