### ISSUE TITLE
Visibility of NEW ticket assigned to another group.

### ISSUE THREAD

**Issue by Ticsis-Fr** [glpi-project/glpi#17466]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Hello everyone,

I have a problem for a long time ago (9.3)
We have 3 differents groups of technician in the same entity.

I made rule for auto assigment of ticket for one of this group, and a second rule to change the ticket in the NEW status after this assigment.
The problem is here, the techician of the others groups can see this ticket if this status is NEW, but it's not assigned to them.

How can i make this work please (without delete the assigment option for the technician profil) ?

Thx

![2024-07-08 11_09_40-Window](https://github.com/glpi-project/glpi/assets/175004154/8ea34f2c-de02-4ff5-a251-10fbee164237)

### Steps To reproduce

1. create a ticket
2. the ticket is attribuate to a specific group (groupe A)
3. The other group can't see this (group B & C)
4. Change the status of this ticket (manually or with rules) to NEW
5. The ticket is visible by everyone (the issue)

### Your GLPI setup information

Glpi 10.0.16
Debian 12 up to date
php 8.2
MariaDB for the database

**Comment by cconard96** [comment]
Not a bug. If a user has permission in 10.0 or earlier to assign a ticket, they can view it when it is in a New status. In GLPI 11 there is a separate permission for seeing new tickets. Having an assigned ticket with a New status is a bit of an undefined behavior.
