### ISSUE TITLE
Satisfaction survey view on Home page

### ISSUE THREAD

**Issue by DZbox** [glpi-project/glpi#17494]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.14

### Bug description

Hi,

A technician creates a ticket for a customer, let's assume he received information by phone. 
So Requester is the customer, Author is the technician.

The ticket is closed, GLPI automatically creates an external satisfaction survey (I didn't try this with internal survey). Now both Requester and Author see the survey reminder in the Personal View at the GLPI Home page (Main dashboard).

It seems only Requester should see the survey, not Author

### Page URL

/front/central.php

**Comment by cconard96** [comment]
This seems intentional. GitHub issues should be reserved for bug reports. You can make the suggestion to change this behavior here:
https://glpi.userecho.com/
