### ISSUE TITLE
[9.1.2] Not correct work rulemailcollector rules

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#1749]
Good day, developers.
When you try to create a "Rules for assigning a ticket created through a receiver mails" function is not available and is not active.
![rulemailcollector2](https://cloud.githubusercontent.com/assets/21122546/22544487/c1b1c896-e956-11e6-83fe-7ab8d7eb80cd.jpg)

If the user glpi, switch the interface language to English and then again on Russian, the function becomes active and allows you to create a rule.
![rulemailcollector3](https://cloud.githubusercontent.com/assets/21122546/22544488/c48b79d6-e956-11e6-87ea-4c34b59fb26f.jpg)

**Comment by gloomy-master** [comment]
Hello developers.
How are things with this little problem its fixed?

**Comment by cedric-anne** [comment]
Hi,

Cannot reproduce on 9.4.1. It may have been fixed.

Regards
