### ISSUE TITLE
"Search" button on "Rules for import and link equipments" do nothing

### ISSUE THREAD

**Issue by eduardomozart** [glpi-project/glpi#17500]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

There's a "Search" button on "Rules for import and link equipments" but it does nothing. It would be great if this page could allow searching instead of tab navigation, so we could filter by category if we want and have a more congruent experience relative to other pages that uses the "Search" form.

### Relevant log output

```shell
None.
```

### Page URL

https://glpi.example.com/front/ruleimportasset.php

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.16 ( => /home/robertinho/public_html/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux cloud.ifantasy.srv.br 3.10.0-962.3.2.lve1.5.26.2.el7.x86_64 #​1 SMP Tue Jul 23 08:31:06 EDT 2019 x86_64
PHP 8.2.18 litespeed (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, ctype, curl, date, dom, exif,
	fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap, libxml, litespeed, mbstring, memcached,
	mysqli, mysqlnd, odbc, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, random, readline, session, soap,
	sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache ()
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Server Software: MySQL Community Server - (GPL)
	Server Version: 5.7.30-cll-lve
	Server SQL Mode: 
	Parameters: robertinho_glpi@localhost/robertinho_glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.18) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (5.7.30) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /home/robertinho/glpi/files/_cache has been validated.
Write access to /home/robertinho/glpi/files/_cron has been validated.
Write access to /home/robertinho/glpi/files has been validated.
Write access to /home/robertinho/glpi/files/_dumps has been validated.
Write access to /home/robertinho/glpi/files/_graphs has been validated.
Write access to /home/robertinho/glpi/files/_lock has been validated.
Write access to /home/robertinho/glpi/files/_pictures has been validated.
Write access to /home/robertinho/glpi/files/_plugins has been validated.
Write access to /home/robertinho/glpi/files/_rss has been validated.
Write access to /home/robertinho/glpi/files/_sessions has been validated.
Write access to /home/robertinho/glpi/files/_tmp has been validated.
Write access to /home/robertinho/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar.
Following extensions are not present: zip.
Zend OPcache extension is not present.
Following extensions are installed: ctype, iconv, mbstring.
Following extensions are not present: sodium.
Write access to /home/robertinho/public_html/glpi/marketplace has been validated.
Access to timezone database (mysql) is not allowed.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/home/robertinho/public_html/glpi"
GLPI_CONFIG_DIR: "/home/robertinho/glpi"
GLPI_VAR_DIR: "/home/robertinho/glpi/files"
GLPI_LOG_DIR: "/home/robertinho/glpi/files/_log"
GLPI_MARKETPLACE_DIR: "/home/robertinho/public_html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/home/robertinho/glpi/files"
GLPI_CACHE_DIR: "/home/robertinho/glpi/files/_cache"
GLPI_CRON_DIR: "/home/robertinho/glpi/files/_cron"
GLPI_DUMP_DIR: "/home/robertinho/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/home/robertinho/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/home/robertinho/glpi/files/_locales"
GLPI_LOCK_DIR: "/home/robertinho/glpi/files/_lock"
GLPI_PICTURE_DIR: "/home/robertinho/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/home/robertinho/glpi/files/_plugins"
GLPI_RSS_DIR: "/home/robertinho/glpi/files/_rss"
GLPI_SESSION_DIR: "/home/robertinho/glpi/files/_sessions"
GLPI_TMP_DIR: "/home/robertinho/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/home/robertinho/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/home/robertinho/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/home/robertinho/public_html/glpi/locales"
GLPI_VERSION: "10.0.16"
GLPI_SCHEMA_VERSION: "10.0.16@b13256c443dd4fdb27b4a0d3b8fea8caba4dfaa9"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/home/robertinho/public_html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/home/robertinho/public_html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/home/robertinho/public_html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/home/robertinho/public_html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/home/robertinho/public_html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/home/robertinho/public_html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/home/robertinho/public_html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/home/robertinho/public_html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/home/robertinho/public_html/glpi/vendor/sabre/http/lib)
sabre/uri in (/home/robertinho/public_html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/home/robertinho/public_html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/home/robertinho/public_html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/home/robertinho/public_html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/home/robertinho/public_html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/home/robertinho/public_html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/home/robertinho/public_html/glpi/vendor/symfony/console)
scssphp/scssphp in (/home/robertinho/public_html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/home/robertinho/public_html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/home/robertinho/public_html/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/home/robertinho/public_html/glpi/vendor/ramsey/uuid/src)
psr/log in (/home/robertinho/public_html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/home/robertinho/public_html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/home/robertinho/public_html/glpi/vendor/psr/cache/src)
league/csv in (/home/robertinho/public_html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/home/robertinho/public_html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/home/robertinho/public_html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/home/robertinho/public_html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/home/robertinho/public_html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/home/robertinho/public_html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/home/robertinho/public_html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/home/robertinho/public_html/glpi/vendor/symfony/cache)
html2text/html2text in (/home/robertinho/public_html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/home/robertinho/public_html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/home/robertinho/public_html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/home/robertinho/public_html/glpi/vendor/twig/twig/src)
twig/string-extra in (/home/robertinho/public_html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/home/robertinho/public_html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/home/robertinho/public_html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/home/robertinho/public_html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/home/robertinho/public_html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: PHP

</pre></details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Endereçamento IP               Version: 3.0.2      State: Enabled                                 
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Manual
	singlesignon         Name: Logon Único                    Version: 1.3.5      State: Installed / not activated               
		Install Method: Manual

</pre></details>

**Comment by stonebuzz** [comment]
Hi @eduardomozart 

There is simply no search filter here or for the rules in general.

Related PR remove useless 'search' entry
