### ISSUE TITLE
Import location hierarchy from LDAP Active Directory user

### ISSUE THREAD

**Issue by corzakiewicz** [glpi-project/glpi#17514]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Hi,

Our current GLPI is version 10.0.16
We have only one instance : Production.

LDAP Active Directory synchronization is set up on our GLPI server.
This allow to import users and to automatically create location mapping the AD User field "City". The automatic creation of locations using hierarchy methode (using the symbol > to specify the child and parent) was working great on GLPI v9.
We migrated to GLPI v10 on December 2023.
Then I discovered new locations in GLPI have automatically been created the day after we migrated to GLPI v10.

We first had opened an issue : https://github.com/glpi-project/glpi/issues/17106 

Now we did the last update to 10.0.16 few days ago, we see the issue still occurs.

Do you know how we can solve it ?

Thank you very much for your help.

**Comment by cedric-anne** [comment]
Hi,

Could you explain how we can reproduce the issue? I was not able to reproduce this, but maybe I was not following the exact same scenario. Are these locations created when the synchronization is made by the `ldap:synchronize_users` command, or when the synchronization is manually done by the admin, or when the user logs-in to GLPI?

**Comment by corzakiewicz** [comment]
Hi,

I have just read again your post in my previous issue ticket.
You wrote :
"
**I am not able to reproduce.
- I tested with Mycompanyname Agences>Caen and it created me a Mycompanyname Agences>Caen location.
- I tested with Mycompanyname Agences > Caen and it created me a Caen location as a child of a Mycompanyname Agences location.**
"

Actually, you reproduced the issue :
When you set "Mycompanyname Agences>Caen", it creates "Mycompanyname Agences>Caen" location while in the previous versions of GLPI, this way of "writing the location" in the Active Directory User property allowed GLPI to create Caen as a child of Mycompanyname agence.
So, I wonder if at a moment the behaviour of GLPI changed regarding that way of "coding" the locations in the location field of an Active Directory user.
When we set up GLPI for the first time, in v9 version, this was working great without inserting space character in the location between the separator ">".

What do you think about this ?
