### ISSUE TITLE
Software dictionary not applied after inventory with GLPI agent

### ISSUE THREAD

**Issue by Berlinst** [glpi-project/glpi#17516]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

Hello! I initially created an issue at https://github.com/glpi-project/glpi-agent/issues/714, but it was not the correct place according to the comment by @g-bougard.

I installed the GLPI agent on a computer to perform an inventory of the device in GLPI. After forcing the inventory, the computer was correctly inventoried in GLPI. Following this, I created some rules in the software dictionary to adjust the software categories on the computers, aiming for better filtering.

![image](https://github.com/user-attachments/assets/8b657fc7-7b1f-448b-bb7b-321ea45e7c7b)
-> Software Dictionary

After creating these rules, I forced the inventory again. However, there was no change in the software categories according to the created dictionary. I tested by permanently deleting and removing devices of the computer, then forcing the inventory again, but the software categories remained blank, along with other tabs for the computer in question.

![image](https://github.com/user-attachments/assets/80ae4308-3061-4e08-845c-94fd5cd93519)
-> Before permanently deleting and removing devices of the computer, then forcing the inventory again.

![image](https://github.com/user-attachments/assets/bbacc888-f542-4fc5-af77-2bf91e479330)
-> After permanently deleting and removing devices of the computer, then forcing the inventory again.

I also tested by reinstalling the GLPI agent, but it didn't resolve the issue. Upon uninstalling and reinstalling the GLPI agent, the software information was retrieved again, but the categories were still not adjusted according to the dictionary.

![image](https://github.com/user-attachments/assets/b1667797-4db4-4a92-9c1a-25e953067d14)
-> According to the above dictionary, the software category should be 'Antivírus'.

![image](https://github.com/user-attachments/assets/14fae510-517e-4962-97f2-00a83cd3b31c)
-> According to the above dictionary, the software category should be 'Compactador'.

![image](https://github.com/user-attachments/assets/23de89a4-8a58-4ea7-9761-b4bf61833a17)
-> According to the above dictionary, the software category should be 'GLPI'.

**Comment by serviceticst** [comment]
Hello, any updates on this issue? We're experiencing the same problem.

**Comment by Berlinst** [comment]
Hello, I wanted to follow up on this issue as I haven’t received any response yet. Could someone please provide an update or guidance on this matter? Any help would be greatly appreciated.

Thanks.

**Comment by Berlinst** [comment]
It was found that due to the USB connection of the printer to the computer, the agent was automatically importing the printer. This behavior is expected and normal. However, we no longer wanted this to occur, so we disabled the "Rules for import and link equipment" related to printers, as well as the global rules that were importing and updating by MAC address and by serial number.

After performing a new inventory, the printer is not removed. **It only gets removed if the agent is uninstalled and reinstalled.** This is the same issue occurring with the software, as mentioned above.

**Comment by g-bougard** [comment]
Hi @Berlinst 

latest glpi-agent version is used to send partial inventory most of the time and this can be confusing in your tests. To avoid confusion, please disable the feature on the computer you're using for tests by setting `full-inventory-postpone` to 0 in agent configuration (you have to change it in registry and restart the agent). With this option disabled, you won't have to fully reinstall the agent to see your rules applied.

This glpi-agent full-inventory-postpone feature can be confusing when testing rules as only changed parts are sent most of the time: if you're testing software rules and no software has been installed, uninstalled or updated, glpi won't have to apply any rule.
