### ISSUE TITLE
Can't create anonymous ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1752]
http://forum.glpi-project.org/viewtopic.php?id=156736

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/1438

**Comment by trasher** [comment]
As far as I remember, the inconsistence from #1438 was because of the inderect call of `getEmpty()`.

Two solutions, replace by:
```
$track->getEmpty();
```

Or by:
```
if (!$CFG_GLPI["use_anonymous_helpdesk"])) {
   $track->check(-1, CREATE, $_POST);
}
```
