### ISSUE TITLE
Icons dropdown (for choosing a tabler icon) is very slow

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#17522]

**Comment by cconard96** [comment]
How slow is it for you? It takes about a second for me.
It isn't really surprising given Select2 is rendering 4739 options with span elements being created using `createElement` and inserted into the DOM every time it is opened. Showing just the icon names still has a noticeable delay for me, but is improved.

**Comment by orthagh** [comment]
> It isn't really surprising

No indeed

I opened the issue up more so that discussions could happen.
Select2 is not a good choice for this control, I let it pass initially because it eased the selection (instead of a text input).
But we should find a new way for an icon selector.

Inspiration could come from messenger applications where they display an emojis selector.

**Comment by orthagh** [comment]
lib ideas:
https://github.com/migliori/universal-icon-picker -> I don't like their UI but they have a demo with table
https://github.com/noeGnh/vue3-icon-picker -> vue3
https://github.com/AppoloDev/vanilla-icon-picker -> no tabler direct implementation but support iconify JSON, it should be possible (it relies by default on SVG, so not so easy)
https://fonticonpicker.github.io/ -> does not rely on any icon library by default and just transforms a classic select

In several options (applodev, fonticonpicker), we need to have the list of icons and pass it to the js function. We may find a list provided by `@tabler/icons` package to construct the select (may we already do this ?)

**Comment by orthagh** [comment]
I tried a bit the last one:
![image](https://github.com/user-attachments/assets/4fdf7149-3978-46fc-a289-c9e8cf60ed0e)
It works but as it rely on jquery, I'm not pleased (still an enhancement on actual implementation)

I'm very interested to see the vue one in action as it includes tabler directly but I lack the experience to import the thing

**Comment by orthagh** [comment]
A note that's said, the jquery lib seems to be the only one to have a category feature (like `{ 'category label': ['ti ti...', ...]}`)

**Comment by orthagh** [comment]
I will write a bunch of stuff today to see if we can just make a pagination to local data with the existing method using select2
In fact it could be the best option (same component as usual) rather than choosing an additional library for that
An alternative could be using an ajax source for icons also.
