### ISSUE TITLE
FAQ not visible for anonymous

### ISSUE THREAD

**Issue by DerGast01** [glpi-project/glpi#17569]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

I have the problem that FAQ entries do not open even though they are marked as "public".
See the picture:
FAQ for anonym is activated.
![grafik](https://github.com/user-attachments/assets/954c3f25-6586-4b8a-9f89-bbc767eaeb61)

FAQ-Button ist visible
![grafik](https://github.com/user-attachments/assets/f5b7b7db-be59-4583-83b8-80674c25d98a)
Title of a "Test FAQ" is also visible.
![grafik](https://github.com/user-attachments/assets/d849293f-6743-40fd-b465-047645525c70)

But wenn i click on a link, the site is empty.
![grafik](https://github.com/user-attachments/assets/87465278-21e0-4ac0-b53a-748c4a96dc0a)

Tested on two fresh installed Servers.

Any ideas? Thanks a lot :)
Kind regards
Daniel

**Comment by cconard96** [comment]
Please provide the information requested in the bug report template including relevant log output (files/_log folder).
