### ISSUE TITLE
Unable to save Entity Address

### ISSUE THREAD

**Issue by tyronewyatt** [glpi-project/glpi#1756]
Since update to GLPI 9.1.2 I can't save any changes to Entity Address.
When the save button is pressed the error "The action you have requested is not allowed." appears.
![glpi-entity](https://cloud.githubusercontent.com/assets/13756677/22578643/4f0df350-ea1e-11e6-8d45-7393e6e098e8.PNG)
![glpi-entity-error](https://cloud.githubusercontent.com/assets/13756677/22578642/4f0d6336-ea1e-11e6-9e37-c4fbc646951d.PNG)
Tested okay in 9.1.1.
Confirmed all plugins disabled.

**Comment by ukef** [comment]
I can confirm this issue, I have the same problem. In version 9.1.1 all is working fine.
