### ISSUE TITLE
Undefined constant "Glpi\RichText\GLPI_TEXT_MAXSIZE (I lost all personal tickets and I no longer have computers)

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#17586]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

"Glpi\RichText\GLPI_TEXT_MAXSIZE" in /var/www/assistance-dev/src/RichText/RichText.php at line 294

### Relevant log output
Migration from version 10.0.10 to php 8.0
I lost all personal tickets and I no longer have computers

**Comment by cedric-anne** [comment]
Hi,

Did you patched the `inc/based_config.php` file?

**Comment by cedric-anne** [comment]
By the way, please fill requested information. It may help to understand your issue.

**Comment by cedric-anne** [comment]
If you want to override some constants, you have to do it, for instance, in a `local_define.php` file of you GLPI configuration directory. See https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations for more information.

**Comment by falco2001** [comment]
Thank you very much.
