### ISSUE TITLE
Error export PDF

### ISSUE THREAD

**Issue by SilvaFernando** [glpi-project/glpi#17584]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

HI team, when i try export a ticket page as PDF:
![image](https://github.com/user-attachments/assets/1e75c0a8-80e7-4a4c-8bb5-96a71bb2dcb7)

And i Have this error:
![image](https://github.com/user-attachments/assets/2bf07b3c-328b-4d86-ac5b-b767f446af46)

### Page URL

/front/ticket.php

### Steps To reproduce

Export a PDF on a ticket page

### Your GLPI setup information

<details><summary>Instruções de instalação e configuração</summary><pre>GLPI 10.0.16 ( => /usr/share/glpi)
Installation mode: TARBALL
Current language:pt_BR

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux SESSRVPRAPP98 5.15.0-113-generic #​123-Ubuntu SMP Mon Jun 10 08:16:17 UTC 2024 x86_64
PHP 8.2.21 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, snmp, soap, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" disable_functions="" 
Software: Apache/2.4.52 (Ubuntu) (Apache/2.4.52 (Ubuntu) Server at 10.243.38.55 Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Server Software: Percona Server (GPL), Release '28', Revision '47601f19'$
	Server Version: 8.0.36-28
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version (8.2.21) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (8.0.36) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /dados/glpi/files/_cache has been validated.
Write access to /dados/glpi/files/_cron has been validated.
Write access to /dados/glpi/files/documents has been validated.
Write access to /dados/glpi/files/_dumps has been validated.
Write access to /dados/glpi/files/_graphs has been validated.
Write access to /dados/glpi/files/_lock has been validated.
Write access to /dados/glpi/files/_pictures has been validated.
Write access to /dados/glpi/files/_plugins has been validated.
Write access to /dados/glpi/files/_rss has been validated.
Write access to /var/lib/glpi/files/_sessions has been validated.
Write access to /dados/glpi/files/_tmp has been validated.
Write access to /dados/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /usr/share/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/usr/share/glpi"
GLPI_CONFIG_DIR: "/etc/glpi"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: false
GLPI_VAR_DIR: "/dados/glpi/files"
GLPI_DOC_DIR: "/dados/glpi/files/documents"
GLPI_CRON_DIR: "/dados/glpi/files/_cron"
GLPI_DUMP_DIR: "/dados/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/dados/glpi/files/_graphs"
GLPI_LOCK_DIR: "/dados/glpi/files/_lock"
GLPI_PICTURE_DIR: "/dados/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/dados/glpi/files/_plugins"
GLPI_RSS_DIR: "/dados/glpi/files/_rss"
GLPI_SESSION_DIR: "/var/lib/glpi/files/_sessions"
GLPI_TMP_DIR: "/dados/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/dados/glpi/files/_uploads"
GLPI_CACHE_DIR: "/dados/glpi/files/_cache"
GLPI_LOG_DIR: "/var/log/glpi"
GLPI_SYSTEM_CRON: true
GLPI_MARKETPLACE_DIR: "/usr/share/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_LOCAL_I18N_DIR: "/dados/glpi/files/_locales"
GLPI_INVENTORY_DIR: "/dados/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/usr/share/glpi/locales"
GLPI_VERSION: "10.0.16"
GLPI_SCHEMA_VERSION: "10.0.16"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/usr/share/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/usr/share/glpi/vendor/sabre/http/lib)
sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/usr/share/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/usr/share/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/usr/share/glpi/vendor/symfony/console)
scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src)
psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src)
psr/cache in (/usr/share/glpi/vendor/psr/cache/src)
league/csv in (/usr/share/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/usr/share/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/usr/share/glpi/vendor/symfony/cache)
html2text/html2text in (/usr/share/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/usr/share/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/usr/share/glpi/vendor/symfony/dom-crawler)
twig/twig in (/usr/share/glpi/vendor/twig/twig/src)
twig/string-extra in (/usr/share/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/usr/share/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/usr/share/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/usr/share/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/usr/share/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS ()

</pre></details><details><summary>Plugins list</summary><pre> 
	fields               Name: Campos adicionais              Version: 1.21.9     State: Enabled                                 
		Install Method: Manual
	behaviors            Name: Comportamentos                 Version: 2.7.3      State: Enabled                                 
		Install Method: Manual
	fusioninventory      Name: FusionInventory                Version: 10.0.6+1.1 State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Importação de dados            Version: 2.13.5     State: Enabled                                 
		Install Method: Manual
	pdf                  Name: Imprimir em PDF                Version: 3.0.0      State: Not installed                           
		Install Method: Manual
	moreticket           Name: Mais Chamados                  Version: 1.7.4      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Mais Relatórios                Version: 1.8.6      State: Enabled                                 
		Install Method: Manual
	satisfaction         Name: Mais satisfação                Version: 1.6.2      State: Enabled                                 
		Install Method: Manual
	trademark            Name: Trademark                      Version: 1.4.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cconard96** [comment]
I cannot recreate the issue. Please provide the full error message from your GLPI logs and the exact search criteria being used.

**Comment by SilvaFernando** [comment]
Folow the filter:
![image](https://github.com/user-attachments/assets/4e520dda-26d8-4541-a570-977feb27e895)

And URL: /front/report.dynamic.php?item_type=Plugin&sort%5B0%5D=1&order%5B0%5D=ASC&start=0&criteria%5B0%5D%5Bfield%5D=view&criteria%5B0%5D%5Blink%5D=contains&criteria%5B0%5D%5Bvalue%5D=&display_type=2

In SQL-ERRORS:
[2024-07-23 16:35:18] glpisqllog.WARNING: DBmysql::doQuery() in /usr/share/glpi/src/DBmysql.php line 443
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = 'notold'
  Warnings:
1292: Truncated incorrect DOUBLE value: 'notold'
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/Dropdown.php:552                               DBmysql->request()
  src/Search.php:2116                                Dropdown::getDropdownName()
  src/Search.php:2028                                Search::computeTitle()
  src/Search.php:208                                 Search::outputData()
  front/report.dynamic.php:136                       Search::showList()
  public/index.php:82                                require()
  {"user":"8401@SESSRVPRAPP98"}
[2024-07-23 16:41:04] glpisqllog.WARNING: DBmysql::doQuery() in /usr/share/glpi/src/DBmysql.php line 443
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = 'notold'
  Warnings:
1292: Truncated incorrect DOUBLE value: 'notold'
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/Dropdown.php:552                               DBmysql->request()
  src/Search.php:2116                                Dropdown::getDropdownName()
  src/Search.php:2028                                Search::computeTitle()
  src/Search.php:208                                 Search::outputData()
  front/report.dynamic.php:136                       Search::showList()
  public/index.php:82                                require()
  {"user":"7408@SESSRVPRAPP98"}
[2024-07-23 16:41:20] glpisqllog.WARNING: DBmysql::doQuery() in /usr/share/glpi/src/DBmysql.php line 443
  *** MySQL query warnings:
  SQL: SELECT `glpi_tickets`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_tickets` WHERE `glpi_tickets`.`id` = 'notold'
  Warnings:
1292: Truncated incorrect DOUBLE value: 'notold'
  Backtrace :
  src/DBmysqlIterator.php:112                        DBmysql->doQuery()
  src/DBmysql.php:1109                               DBmysqlIterator->execute()
  src/Dropdown.php:552                               DBmysql->request()
  src/Search.php:2116                                Dropdown::getDropdownName()
  src/Search.php:2028                                Search::computeTitle()
  src/Search.php:208                                 Search::outputData()
  front/report.dynamic.php:136                       Search::showList()
  public/index.php:82                                require()
  {"user":"7408@SESSRVPRAPP98"}
                                                   
PHP-errors:
[2024-07-23 20:35:01] glpiphplog.WARNING:   *** PHP Warning (2): session_save_path(): Session save path cannot be changed after headers have already been sent in /usr/share/glpi/src/Session.php at line 217
  Backtrace :
  src/Session.php:217                                session_save_path()
  src/Console/Application.php:389                    Session::setPath()
  src/Console/Application.php:116                    Glpi\Console\Application->initSession()
  bin/console:121                                    Glpi\Console\Application->__construct()

[2024-07-23 20:35:01] glpiphplog.WARNING:   *** PHP Warning (2): ini_set(): Session ini settings cannot be changed after headers have already been sent in /usr/share/glpi/src/Session.php at line 230
  Backtrace :
  src/Session.php:230                                ini_set()
  src/Console/Application.php:390                    Session::start()
  src/Console/Application.php:116                    Glpi\Console\Application->initSession()
  bin/console:121                                    Glpi\Console\Application->__construct()

[2024-07-23 20:35:01] glpiphplog.WARNING:   *** PHP Warning (2): session_name(): Session name cannot be changed after headers have already been sent in /usr/share/glpi/src/Session.php at line 231
  Backtrace :
  src/Session.php:231                                session_name()
  src/Console/Application.php:390                    Session::start()
  src/Console/Application.php:116                    Glpi\Console\Application->initSession()
  bin/console:121                                    Glpi\Console\Application->__construct()

[2024-07-23 20:35:01] glpiphplog.WARNING: Test logger

**Comment by cconard96** [comment]
Please test again without plugins enabled.

Also, the URL for the export you provided doesn't match your search.
Decoded: item_type=Plugin&sort[0]=1&order[0]=ASC&start=0&criteria[0][field]=view&criteria[0][link]=contains&criteria[0][value]=&display_type=2

This seems like an export of Plugin results with the default Items Seen criteria.

**Comment by trasher** [comment]
No feedback, closing
