### ISSUE TITLE
Favorite in Saved searches not working

### ISSUE THREAD

**Issue by paulo-dambros** [glpi-project/glpi#17597]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

GLIP is unable to keep a favorite search as the default in the Saved Searches feature

### Page URL

/front/ticket.php

### Steps To reproduce

1. Save a global search with some filter in /front/ticket.php.
3. Go to a non-root user and try to apply this saved search as a favorite.
5. Log in with that user and verify that the saved search has not been applied and marked as a favorite.

In our installation, this problem occurs with some users only; for others, it works. Even a screenshot is difficult to explain for understanding.

**Comment by cconard96** [comment]
Please provide the information that was requested in the bug report template. Specifically, the GLPI setup information and any GLPI log entries that may be present around the time of the issue.
