### ISSUE TITLE
not possible to create an ldap directory entry on safari

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#176]
The Add button is not clickable on safari in 9.0. (search button works)

**Comment by orthagh** [comment]
Hello.

Could you provide version of glpi and a screenshot of your issue ?
I tested with different version of OSX & safari, without found problems.

**Comment by Megachip** [comment]
glpi 0.90 final. 

I could... except it worked today. Only difference since yesterday: I've created an ldap entry (manually enter the path to form).

Deleting and recreating works too... curios. I think this can be closed.
