### ISSUE TITLE
Wrong alternate username with glpi agent

### ISSUE THREAD

**Issue by AntoninRoyerPID** [glpi-project/glpi#17601]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

The alternate username format is incorrect because I don't have the full email address. For example, “`toto@mail.com`” is truncated to just “toto”. This issue started with version 1.9 on Windows 11 and persisted in version 1.10 on Windows 10 and 11.
The problem seems to come from this function `protected function prepareForUsers($val)` at line 244 in `src/Inventory/Asset/MainAsset.php`. I'm trying to do some logging but I didn't find anything.

When importing using a full JSON file, the process works correctly, but it fails when using the agent. It appears this problem is related to the issue discussed in [this ticket](https://github.com/glpi-project/glpi-agent/issues/687), which was supposedly patched.

### Steps To reproduce

1.Install and configure agent
2.Force inventory
3. Look at results in GLPI

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.16 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux glpi 5.15.0-105-generic #​115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64
PHP 8.3.4 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, random, readline, redis, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: Apache/2.4.57 (Debian) (Apache/2.4.57 (Debian) Server at glpi.plugindigital.com Port 80
)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.7.8-MariaDB-1:10.7.8+maria~ubu2004
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi.pid@mariadb:3306/web_glpi_plugin_digital
	Host info: mariadb via TCP/IP
	
PHP version (8.3.4) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.7.8) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/lib/glpi//_cache has been validated.
Write access to /var/lib/glpi//_cron has been validated.
Write access to /var/lib/glpi/ has been validated.
Write access to /var/lib/glpi//_dumps has been validated.
Write access to /var/lib/glpi//_graphs has been validated.
Write access to /var/lib/glpi//_lock has been validated.
Write access to /var/lib/glpi//_pictures has been validated.
Write access to /var/lib/glpi//_plugins has been validated.
Write access to /var/lib/glpi//_rss has been validated.
Write access to /var/lib/glpi//_sessions has been validated.
Write access to /var/lib/glpi//_tmp has been validated.
Write access to /var/lib/glpi//_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/html/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/html/glpi"
GLPI_CONFIG_DIR: "/etc/glpi/"
GLPI_VAR_DIR: "/var/lib/glpi/"
GLPI_LOG_DIR: "/var/log/glpi/"
GLPI_MARKETPLACE_DIR: "/var/www/html/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/lib/glpi/"
GLPI_CACHE_DIR: "/var/lib/glpi//_cache"
GLPI_CRON_DIR: "/var/lib/glpi//_cron"
GLPI_DUMP_DIR: "/var/lib/glpi//_dumps"
GLPI_GRAPH_DIR: "/var/lib/glpi//_graphs"
GLPI_LOCAL_I18N_DIR: "/var/lib/glpi//_locales"
GLPI_LOCK_DIR: "/var/lib/glpi//_lock"
GLPI_PICTURE_DIR: "/var/lib/glpi//_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/lib/glpi//_plugins"
GLPI_RSS_DIR: "/var/lib/glpi//_rss"
GLPI_SESSION_DIR: "/var/lib/glpi//_sessions"
GLPI_TMP_DIR: "/var/lib/glpi//_tmp"
GLPI_UPLOAD_DIR: "/var/lib/glpi//_uploads"
GLPI_INVENTORY_DIR: "/var/lib/glpi//_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/html/glpi/locales"
GLPI_VERSION: "10.0.16"
GLPI_SCHEMA_VERSION: "10.0.16@b13256c443dd4fdb27b4a0d3b8fea8caba4dfaa9"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/html/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/html/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
psr/cache in (/var/www/html/glpi/vendor/psr/cache/src)
league/csv in (/var/www/html/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/html/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/html/glpi/vendor/symfony/cache)
html2text/html2text in (/var/www/html/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/html/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/html/glpi/vendor/symfony/dom-crawler)
twig/twig in (/var/www/html/glpi/vendor/twig/twig/src)
twig/string-extra in (/var/www/html/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/html/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/html/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/html/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/html/glpi/vendor/thenetworg/oauth2-azure/src/Provider)
phpCas version 1.6.0 in (/usr/share/php/CAS/source)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+OAUTH (*****)

</pre></details><details><summary>Plugins list</summary><pre> 
	addressing           Name: Adressage IP                   Version: 3.0.2      State: Enabled                                 
		Install Method: Marketplace
	news                 Name: Alerts                         Version: 1.12.2     State: Enabled                                 
		Install Method: Marketplace
	datainjection        Name: Data Injection                 Version: 2.13.4     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.9     State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	ocsinventoryng       Name: OCS Inventory NG               Version: 2.0.4      State: Installed / not activated               
		Install Method: Marketplace
	onetimesecret        Name: OneTimeSecret                  Version: 2.1.3      State: Enabled                                 
		Install Method: Marketplace
	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Enabled                                 
		Install Method: Manual
	trademark            Name: Trademark                      Version: 1.4.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

### Anything else?

I solve it by editing the function with a default domain but this is not the rigth solution for long term scalability.
Here is my code : 
```php
protected function prepareForUsers($val)
{
    /** @var \DBmysql $DB */
    global $DB;

    $defaultDomain = 'domain.com'; // Default domain if none is found

    if (property_exists($val, 'users_id')) {
        if ($val->users_id == '') {
            unset($val->users_id);
        } else {
            // Find the domain from the agent's data
            $domain = $defaultDomain;
            if (isset($this->extra_data['users'])) {
                foreach ($this->extra_data['users'] as $a_users) {
                    if (property_exists($a_users, 'domain') && !empty($a_users->domain)) {
                        $domain = $a_users->domain;
                        break;
                    }
                }
            }

            // Assemble the email for the contact
            $val->contact = $val->users_id . '@' . $domain;

            $iterator = $DB->request([
                'SELECT' => 'id',
                'FROM'   => 'glpi_users',
                'WHERE'  => [
                    'name'   => Sanitizer::sanitize($val->users_id)
                ],
                'LIMIT'  => 1
            ]);

            if (count($iterator)) {
                $result = $iterator->current();
                $val->users_id = $result['id'];
            } else {
                $val->users_id = 0;
            }
        }
    }

    // * USERS
    $cnt = 0;
    if (isset($this->extra_data['users'])) {
        if (count($this->extra_data['users']) > 0) {
            $user_temp = '';
            if (property_exists($val, 'contact')) {
                $user_temp = $val->contact;
            }
            $val->contact = '';
        }
        foreach ($this->extra_data['users'] as $a_users) {
            $user = '';
            if (property_exists($a_users, 'login')) {
                $user = $a_users->login;
                if (
                    property_exists($a_users, 'domain')
                    && !empty($a_users->domain)
                ) {
                    $user .= "@" . $a_users->domain;
                } else {
                    $user .= "@" . $domain; // Add the found domain
                }
            }
            if ($cnt == 0) {
                if (property_exists($a_users, 'login')) {
                    // Search with the found domain
                    $where_add = [];
                    if (
                        property_exists($a_users, 'domain')
                        && !empty($a_users->domain)
                    ) {
                        $ldaps = $DB->request(
                            'glpi_authldaps',
                            ['WHERE'  => ['inventory_domain' => Sanitizer::sanitize($a_users->domain)]]
                        );
                        $ldaps_ids = [];
                        foreach ($ldaps as $data_LDAP) {
                            $ldaps_ids[] = $data_LDAP['id'];
                        }
                        if (count($ldaps_ids)) {
                            $where_add['authtype'] = Auth::LDAP;
                            $where_add['auths_id'] = $ldaps_ids;
                        }
                    }
                    $iterator = $DB->request([
                        'SELECT' => ['id'],
                        'FROM'   => 'glpi_users',
                        'WHERE'  => [
                            'name'   => Sanitizer::sanitize($a_users->login . "@" . $domain)
                        ] + $where_add,
                        'LIMIT'  => 1
                    ]);
                    if ($row = $iterator->current()) {
                        $val->users_id = $row['id'];
                    }
                }
            }

            if ($user != '') {
                if (property_exists($val, 'contact')) {
                    if ($val->contact == '') {
                         $val->contact = $user;
                    } else {
                        $val->contact .= "/" . $user;
                    }
                } else {
                    $val->contact = $user;
                }
            }
            $cnt++;
        }
        if (empty($val->contact)) {
            $val->contact = $user_temp ?? '';
        }
    }
}

```

**Comment by myrandor** [comment]
I just did a change like that... My Windows domain is a single word (like DOMAIN), and the userprincipalname fetched from LDAP is adding ".com". I'm also using the LDAP email field to login users...

So when Inventory run, it doesn't found user@DOMAIN since my email2 is configured with user@domain.com...
