### ISSUE TITLE
White page after connection

### ISSUE THREAD

**Issue by DataSharing** [glpi-project/glpi#17608]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

Hi, 
I'm using CAS authentication for login, I don't know if it has anything to do with the error, a blank page appears when trying to login. It appears there is an error in the code related to querying the database and retrieving the results. Specifically, the DB::fetch_assoc() method is called, which does not exist. This problem occurs in the profile.class.php file on line 107.

Environment:
- Authentication Method: CAS
- File: plugins/gestion/inc/profile.class.php
- Line: 107

`
Uncaught Exception Error: Call to undefined method DB::fetch_assoc() in /var/www/glpi/plugins/gestion/inc/profile.class.php at line 107
`
Proposed Solution:

Replace the incorrect method call with a valid method for fetching the result set from the database query. The specific method to use depends on the database library being used (e.g., PDO, mysqli).

Example Correction:

`
public function getFromDBByProfile($profiles_id)
{
    global $DB;

    $query = "SELECT *
              FROM `" . $this->getTable() . "`
              WHERE `profiles_id` = '" . (int) $profiles_id . "' ";

    if ($result = $DB->query($query)) {
        if ($result->num_rows > 0) {
            //BEFORE : $this->fields = $DB->fetch_assoc($result);
            $this->fields = $result->fetch_assoc();
            if (is_array($this->fields) && count($this->fields)) {
                return true;
            }
        }
    }

    return false;
}
`

### Page URL

/front/login.php

**Comment by trasher** [comment]
Problem is in the "gestion" plugin. Please report to plugin owner.
