### ISSUE TITLE
Wrong label in software form ?

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1763]
Hi 

Have a look into this screenshot (GLPI 9.1.2)

![image](https://cloud.githubusercontent.com/assets/14139801/22641980/284b442e-ec59-11e6-97e3-2f246fc47e52.png)

Technician and group in chage of the hardware seems wrong to me. Should not be in charge of the **software** instead ?

**Comment by trasher** [comment]
Another issue have been opened for a similar problem (#1467). Taking a look at the whole code, there are other similar issues remaining :(

**Comment by trasher** [comment]
Nevermind, other occurences are OK
