### ISSUE TITLE
Wrong column used when searching a computer IP address

### ISSUE THREAD

**Issue by 0xNath** [glpi-project/glpi#17642]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Hello,
when looking for a specific computer based on his IP address, using the selector "is", the SQL request made use the "ID" column of the table "glpi_ipaddresses" instead of the column "name".

When using the selector "contains", the request is made with the correct column.

See the WHERE part of the request made incorrectly on the left and the correct one on the right : 
![image](https://github.com/user-attachments/assets/7cf43659-d5e4-4d2d-9017-cee76d1e296e)

The structure of the table is bellow : 
![image](https://github.com/user-attachments/assets/84b92b63-09c2-4646-87fc-a9f7a3e17f47)

When using the selector "IS", it should also look against the "name" column, not like that : 
![image](https://github.com/user-attachments/assets/ec944bbf-23af-4508-b56a-cd1eaea6a500)

I'm looking into this issue and will propose a pull request.

Best regards

### Steps To reproduce

1. Search for a computer using the selector "is" with an actual IP address.

**Comment by trasher** [comment]
I confirm the issue
