### ISSUE TITLE
When creating a ticket, the “business rules” do not work correctly. Not all specialists are added to the ticket.

### ISSUE THREAD

**Issue by MiDgEm** [glpi-project/glpi#17663]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.13

### Bug description

Just recently updated to GLPI 9.4.4. until 9.5.13.
When working with it, specialists who were assigned to tickets received complaints that the “business rules” configured back in 9.4.4 did not work.

In our GLPI we do not use third-party plugins (many with an “error” status). Standard features only.
Note: We previously used OCSInventory, but abandoned it after unsuccessful use.

### Steps To reproduce

1. Create a simple business rule;

2. Set the criterion by which specialists and observers will be appointed: ![Screenshot 2024-08-09 092632](https://github.com/user-attachments/assets/1625a76e-1ad7-44c8-a2ab-654babcf399b)

3. Inside the rule, on the Action tab, add a group of specialists, specialists and wathers:
![Screenshot 2024-08-09 092231](https://github.com/user-attachments/assets/e225ffac-a277-43a9-a905-2a33f732c20d)

4. Create a ticket from the "post-only" profile:
![Screenshot 2024-08-09 094425](https://github.com/user-attachments/assets/c2304530-ac67-4dfc-a5a4-858b06e4b679)

Result: Out of 3 specialists, only 1 was added. And out of 2 observers, only 1 was added.
![Screenshot 2024-08-09 094647](https://github.com/user-attachments/assets/f4998e74-10ad-4830-8960-00a8b8d8c7a3)

### Anything else?

Please help me with this problem. I don’t really understand where and what needs to be changed to fix this problem.

**Comment by trasher** [comment]
GLPI 9.5 is EOL since July 2023. Consider upgrading to latest stable release (10.0.16).

**Comment by MiDgEm** [comment]
Unfortunately, we settled on this version. Because the new version 10.x.x does not suit us.

At least indicate in which files glpi creates/executes rules for adding specialists
