### ISSUE TITLE
Results to display per page problem

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#1767]
[code]
 
GLPI 9.1.2 (/glpi => /var/www/html/glpi)

Server

 
Operating system: Linux habsrv11.habilita.local 2.6.32-573.12.1.el6.x86_64 #1 SMP Tue Dec 15 21:19:08 UTC 2015 x86_64
PHP 5.4.45 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, apache2handler, bz2, calendar, ctype, curl,
	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mhash, mysql,
	mysqli, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="21M" 
Software: Apache/2.2.15 (CentOS) (Apache/2.2.15 (CentOS) Server at systrack.habilita.local Port 80)
	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0
Server Software: MySQL Community Server (GPL) by Remi
	Server Version: 5.5.47
	Server SQL Mode: 
	Parameters: usr_glpi_prod@localhost/glpi91
	Host info: Localhost via UNIX socket
	
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
OKSELinux mode is Disabled

Libraries

 
htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/var/www/html/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/var/www/html/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/var/www/html/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/vendor/ircmaxell/password-compat/lib)
ramsey/array_column in (/var/www/html/glpi/vendor/ramsey/array_column/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)

LDAP directories
***

SQL replicas

 
Not active

Notifications

 
***

Mails receivers
***

Plugins list

 
	accounts             Name: Accounts                       Version: 2.2.0      State: Enabled
	fields               Name: Additionnal fields             Version: 1.4.5      State: Enabled
	certificates         Name: Certificates                   Version: 2.2.0      State: Enabled
	datainjection        Name: File injection                 Version: 2.4.2      State: Enabled
	addressing           Name: IP Adressing                   Version: 2.5.0      State: Enabled
	genericobject        Name: Objects management             Version: 2.4.0      State: Enabled
	manufacturersimports Name: Suppliers imports              Version: 1.9.0      State: Enabled

[/code] 

Hi!,
under personalization(in user setting), at the "Results to display per page" if I try to search 1000 the search return "-1" because the max value is 200.
The problem is that if I select "-1" and press save, the value is saved in DB (immediatly afer pressing save the combo show 5 but is not real). The problem is that every list (computer, printer, ticket etc...) return 0 row.

After blanking the value manually from the DB all returns work.

**Comment by trasher** [comment]
Indeed; this happen when search is not enabled but when we quickly hit a key just after the dropdown opens; or when search has been activated on a very few item amounts.

Some other issues have been opened that my refer to the same problem.
