### ISSUE TITLE
Suggestion for Enhancing User Association Rules with LDAP Company Attribute

### ISSUE THREAD

**Issue by allanlopesprado** [glpi-project/glpi#17689]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Hello,

I recently encountered a situation where a necessary functionality was unavailable.

In the Active Directory (AD) for all users, under the Organization section, in the (Company) field, we insert the name of the company, for example: Branch 1, Branch 2, Branch 3, etc.

I would like to use this information in a straightforward manner to create user association rules for specific companies. Since I could not find a practical solution, I ended up modifying the glpi_rulerightparameters table with the following code:

```
INSERT INTO `glpi_rulerightparameters` (`id`, `name`, `value`, `comment`, `date_mod`, `date_creation`) VALUES
(15, '(LDAP) Company', 'company', '', NULL, NULL);
```
I suggest adding the (LDAP) Company option to the criteria for user permission association rules.

Thanks for considering this!

Best,

**Comment by cconard96** [comment]
GitHub issues should be reserved for bug reports only.
Suggestions can be made here: https://glpi.userecho.com/
Community Support can be found on the forum: https://forum.glpi-project.org/

By the way, you can add these parameters yourself by clicking the "+" button next to the criteria dropdown in the Authorization Assignment Rules.

**Comment by trasher** [comment]
As an alternative, you can consider opening a pull request with change done, and tests cases added.
