### ISSUE TITLE
Business Rules: Assing a group to validation a ticket dont work

### ISSUE THREAD

**Issue by camillagds** [glpi-project/glpi#177]
When I created a Business rule if the action is "Send an approval request user/group" or "Approval request to technician group manager" and test (or create a ticket) the rule don't work. In the 0.85.3 version It worked perfectly.

![glpi_error 001](https://cloud.githubusercontent.com/assets/6138714/10504434/cfd85c20-72d6-11e5-8e64-40f34cae870b.png)
![glpi_error 002](https://cloud.githubusercontent.com/assets/6138714/10504469/07a3b974-72d7-11e5-822a-836c6deeaa0f.png)
![glpi_error 003](https://cloud.githubusercontent.com/assets/6138714/10504436/d011802c-72d6-11e5-9e79-3610eedbcca1.png)

**Comment by yllen** [comment]
It's not a bug: your rule is not active

**Comment by camillagds** [comment]
Its a bug. This rule is inactive because I disabled before the printscreen, sorry.
In the Brazilian Community another user simulated the rule in the version 0.85.4 and 0.90 and had the same issue.

Can you re-open this bug?

**Comment by orthagh** [comment]
see #188
