### ISSUE TITLE
Replies to a thread email in Outlook opens a new ticket if not replying to GLPI email itself

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#17705]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

It happens a lot that people opens a ticket with their manager in the CC's, sometime the manager replies to the email and we end up having the original ticket with severals "RE: xxxx" ticket.

### Steps To reproduce

1. Send an email from user A to helpdesk email with user B in CC.
2. Reply to user A's email with user B.
3. It creates two tickets.

**Comment by DZbox** [comment]
Hi,
try https://plugins.glpi-project.org/#/plugin/mailanalyzer

**Comment by SteadEXE** [comment]
I'll try, thanks you.
It think it should also be handled natively as threads are pretty common in companies, or atleast give more ability to handle it with collector rules
