### ISSUE TITLE
Partial Import on inventory

### ISSUE THREAD

**Issue by Ludo-code** [glpi-project/glpi#17716]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.12

### Bug description

When running an inventory with the glpi-agent 1.9 or 1.10 to glpi 10.0.12 sometimes serial number or processor info are not imported in glpi... But if i check by exporting in html all missing info are in the export... So the computer deduplicate after each inventory...

### Relevant log output

```shell
No access to it
```

### Steps To reproduce

Run inventory with the agent on glpi 10.0.12 and see if serial or processor info are retrived in glpi

### Your GLPI setup information

No access

**Comment by trasher** [comment]
First, try on up-to date version; and second, please provide more information on how to reproduce exactly.

**Comment by Ludo-code** [comment]
I will reproduce this day :) thx i will add more information
