### ISSUE TITLE
Devices connections not removed with partial inventory

### ISSUE THREAD

**Issue by Aekinox** [glpi-project/glpi#17721]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Devices that are no longer present on the PC are no longer disconnected from pc's inventory with glpi-agent 1.10.0.
We must set [full-inventory-postpone](https://glpi-agent.readthedocs.io/en/latest/configuration.html#full-inventory-postpone) to "0" to workaround
glpi-agent [closed issue ](https://github.com/glpi-project/glpi-agent/issues/741)

### Steps To reproduce

1-connect an external screen
2-force inventory from http://localhost:62354/
3-disconnect external screen
4-force inventory from http://localhost:62354/
5-external screen stay in computer's connexions

### Your GLPI setup information

GLPI 10.0.16
PHP version (8.1.29)

Plugins
	addressing           Name: Adressage IP                   Version: 3.0.2      State: Enabled                                 
		Install Method: Manual
	news                 Name: Alertes                        Version: 1.12.3     State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.21.11    State: Enabled                                 
		Install Method: Manual
	datainjection        Name: Data Injection                 Version: 2.13.5     State: Installed / not activated               
		Install Method: Manual
	consumables          Name: Demande de petit matériel      Version: 2.0.1      State: Installed / not activated               
		Install Method: Manual
	gantt                Name: gantt                          Version: 1.1.0      State: Enabled                                 
		Install Method: Manual
	order                Name: Gestion des commandes          Version: 2.10.6     State: Enabled                                 
		Install Method: Manual
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Manual
	mreporting           Name: Plus de rapports               Version: 1.8.6      State: Enabled                                 
		Install Method: Manual
	reports              Name: Rapports                       Version: 1.16.0     State: Enabled                                 
		Install Method: Manual

**Comment by trasher** [comment]
Please provide a partial inventory file sent with disconnected monitors.

**Comment by g-bougard** [comment]
Hi @Aekinox 

since glpi-agent 1.8 & [e2971a3](https://github.com/glpi-project/glpi-agent/commit/e2971a38f4670d076c62bf6cd1e743d585b11e73), when glpi-agent detects a monitor change with no more monitor connected, it will send a full inventory. So full-inventory-postpone should no more be a problem for your case since 1.8.

So finally, are you sure you're not reporting a problem for a computer where agent has not been updated ?
