### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by doganzorlu** [glpi-project/glpi#17738]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.11

### Bug description

in the file /glpi/marketplace/geststock/inc/ticket.class.php at line 68 must be change from:

 if ($req->count())) {

to:

 if ($req->count()) {

**Comment by trasher** [comment]
This concerns a plugin, please report issue to plugin developers.
