### ISSUE TITLE
Access denied for Super-Admin

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1774]
GLPI 9.1.2. When you save an error is that there is no access. It has full rights by default.

![glpi - entity - 7 - 2017-02-07 09 15](https://cloud.githubusercontent.com/assets/17082164/22680016/f4e95ed6-ed16-11e6-975e-f373471b608f.png)

![glpi - access denied - 2017-02-07 09 15](https://cloud.githubusercontent.com/assets/17082164/22680020/f72ccd7c-ed16-11e6-86cc-03f30db456f2.png)

**Comment by tyronewyatt** [comment]
Sounds like a duplicate issue of what I logged last week https://github.com/glpi-project/glpi/issues/1756

**Comment by trasher** [comment]
Indeed, this is a duplicate.
