### ISSUE TITLE
Planning in central

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1776]
http://forum.glpi-project.org/viewtopic.php?id=156765

**Comment by tsmr** [comment]
Modify inc/commonitiltask.class.php 

Add l989
```
$addrestrict = "AND NOT `" . $parentitem->getTable() . "`.`status` IN ('" . implode("', '",
                                                                                                      array_merge($parentitem->getSolvedStatusArray(),
                                                                                                                  $parentitem->getClosedStatusArray())
         ) . "')";
```

**Comment by nqb** [comment]
+1. When you have a lot of tasks, web browser freeze during fewer seconds at login.

@yllen : could you merge @tsmr's code ?

**Comment by nqb** [comment]
tsmr's patch tested on 9.2.2 (nightly build) by modify this line :  https://github.com/glpi-project/glpi/blob/39d4ad46a5e5f4ea326ea7b8bcaeccf59deb6b1f/inc/commonitiltask.class.php#L986

With this patch, GLPI didn't display scheduled tasks on closed objects (tickets, changes, problems). It's an enhancement.

However, you always see past tasks and I wonder if it necessary. 

For example : a ticket created in october 2013, always opened with a scheduled task in october 2013 will display an entry in planning (central). In 2018, you don't want to see this task. We can improve `$addrestrict` filter.

**Comment by nqb** [comment]
@orthagh : 9.2.3 ?

**Comment by nqb** [comment]
Hello,

It works for me but as explained in https://github.com/glpi-project/glpi/issues/1776#issuecomment-369250409, it would be nice to hide past tasks (see my example).

@amma35, @tsmr, @trasher, what is your opinion ?

Don't know if it is important but I get a warning when applying patch : 
```
$ git apply 3914.patch
3914.patch:18: trailing whitespace.
      $addrestrict .= "AND NOT `" . $parentitem->getTable() . "`.`status` IN
warning: 1 ligne a ajouté des erreurs d'espace.
```

**Comment by trasher** [comment]
Discussed on IRC with other devs; it appears that past tasks should have been closed; if they are not, this is expected they appear.
