### ISSUE TITLE
mailcollector is filling logs since 10.0.10

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#17770]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

I just discovered that since we passed version 10.0.10 in 2023, mailgate is filling logs with useless change :
![image](https://github.com/user-attachments/assets/d7cad52c-01e6-405e-8c35-e985c46b31e7)

It generated more than 8200 pages of history in one year.
There is no way to flush those logs without flushing real logs somewhere else.

It started right after upgrading to 10.0.10 and continued since.
It takes several seconds to navigate in logs pages and CPU usage of DB also skyrocket while loading the page.

**Comment by SteadEXE** [comment]
Apparently this has been introduced by https://github.com/glpi-project/glpi/pull/15565

**Comment by trasher** [comment]
Please try https://github.com/glpi-project/glpi/pull/17772

**Comment by SteadEXE** [comment]
It fixes the issue thanks, if anybody wants to clear the logs by hand:
```sql
DELETE FROM glpi_logs WHERE itemtype = 'MailCollector' AND id_search_option IN (22, 23)
```
