### ISSUE TITLE
Plugins upgrade - need to know the previous version

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1777]
Hi

Plugin version in glpi_plugin always match the version of the plugin found in setup.php. 

When a super admin upgrades a plugin, the plugin never know from which version it must upgrade. However this is needed when the plugin becomes complex. Upgrading by searching for fields or tables makes the upgrade code messy over time.

It would be useful that GLPI maintains in is glpi_plugins table the schema version of the plugin.

**Comment by remicollet** [comment]
This won't help.

You can remove a plugin, "clean" its installation state in glpi_plugins (but keep its data) and later reinstall it.

So, IMHO, the plugin install/upgrade have to check what is the current schema of existing table.
