### ISSUE TITLE
Knowledgebase revison comparison overflows 

### ISSUE THREAD

**Issue by tograss** [glpi-project/glpi#17773]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

When comparing two revisions the resulting change can overflow the modal-body resulting in the following view:
![scope](https://github.com/user-attachments/assets/871aaf94-0a96-434e-b62e-032297d6c611)

### Steps To reproduce

1. Go to knwoledgebase
2. create a new article and save
3. enter a long text line
4. compare the revisions

**Comment by tograss** [comment]
The bug is back in 11.0.5

**Comment by trasher** [comment]
Open a new ticket with all requested info.
