### ISSUE TITLE
Add ticket status in item ticket was promote

### ISSUE THREAD

**Issue by f0rextazy** [glpi-project/glpi#17778]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.14 

### Bug description

Hello
Please add ticket status in item ticket was promote
![image](https://github.com/user-attachments/assets/9239c3cd-5f9a-4a03-ae5c-a04eee2af3a9)

For example, like here, the green circle
![image](https://github.com/user-attachments/assets/d9d35f4b-7114-498e-b789-0236c80a6c8a)

**Comment by cconard96** [comment]
Suggestions should be made on the [UserEcho site](https://glpi.userecho.com/).
Issues are for bug reports only (or maybe also discussions if you offer to make a code contribution and wish to discuss it first).
