### ISSUE TITLE
Trouble with sort on infocoms fields

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#178]
forced aggregation on this fields add ##$$id in value returned.
In case of infocoms table, we can have no line for an asset, so field return is NULL.

Visually , on sorting on this fields, example : compute .delivery_date, we have empty values on both side.

**Comment by yllen** [comment]
I don't understand the problem.
I have no problem to sort item of infocom even they are empty.
You have this issue when you're doing which action?

**Comment by orthagh** [comment]
The problem isn't the possibility to sort but the result of this sorting.
With theses needless groupby (infocoms is a 1:1 relation) : 
* Asset without infocoms : return NULL
* Asset with infocoms and empty date : return $$##$$id 
* Asset with infocoms and filled date : return date$$##$$id 

On sort (buy_date for ex), we have a raw datas list : 

NULL, 
NULL, 
...
date$$##$$id, 
date$$##$$id , 
...
$$##$$id; 
$$##$$id; 

and a  displayed list
"", 
"", 
...
"date", 
"date", 
...
"", 
""

removing the groupby option clear the $$##$$id on this case "Asset with infocoms and empty date" and the list is sorted correctly.

**Comment by yllen** [comment]
What do you want to change the result if you can correctly sort it in GLPI?
I will introduce others problems in GLPI

**Comment by remicollet** [comment]
>  With theses needless groupby (infocoms is a 1:1 relation) : 

No. This is a 0:n relation for Sofware, Cartdrige, ...

This to create 1 software with 2 licences, each licence with infocom and fill "Delivery"

0.90 => both delivery are displayed
master => only one

**Comment by orthagh** [comment]
It's not sorted correctly!  We have empty values on each side and filled values on middle

**Comment by yllen** [comment]
All the line if filled if items are not empty.
I test the example of Remi and confirm that if you have many licences with infocom only the last is display, so bug.

**Comment by orthagh** [comment]
Ok for that  : "This is a 0:n relation for Sofware, Cartdrige,"
I must find a better solution to the initial problem.

For better comprehension, see this screenshot (with forcegroupby) : 
![image](https://cloud.githubusercontent.com/assets/418844/10695469/24583472-79a4-11e5-9f68-2a92c7fb5f02.png)

And raw datas :
```SQL
SELECT 'adelaunay' AS currentuser,
       `glpi_monitors`.`name` AS `ITEM_0`,
       
       GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_infocoms`.`buy_date`, '__NULL__'), '$#$',`glpi_infocoms`.`id`) SEPARATOR '$$##$$') AS `ITEM_9`,
       `glpi_monitors`.`id` AS id
FROM `glpi_monitors`
LEFT JOIN `glpi_entities` ON (`glpi_monitors`.`entities_id` = `glpi_entities`.`id`)
LEFT JOIN `glpi_states` ON (`glpi_monitors`.`states_id` = `glpi_states`.`id`)
LEFT JOIN `glpi_manufacturers` ON (`glpi_monitors`.`manufacturers_id` = `glpi_manufacturers`.`id`)
LEFT JOIN `glpi_locations` ON (`glpi_monitors`.`locations_id` = `glpi_locations`.`id`)
LEFT JOIN `glpi_monitortypes` ON (`glpi_monitors`.`monitortypes_id` = `glpi_monitortypes`.`id`)
LEFT JOIN `glpi_monitormodels` ON (`glpi_monitors`.`monitormodels_id` = `glpi_monitormodels`.`id`)
LEFT JOIN `glpi_infocoms` ON (`glpi_monitors`.`id` = `glpi_infocoms`.`items_id`
                              AND `glpi_infocoms`.`itemtype` = 'Monitor')
WHERE `glpi_monitors`.`is_deleted` = '0'
  AND `glpi_monitors`.`is_template` = '0'
GROUP BY `glpi_monitors`.`id`
ORDER BY ITEM_9 DESC LIMIT 0, 50
```

currentuser | ITEM_0                         | ITEM_9            | id
------------|--------------------------------|-------------------|---
adelaunay   | 0/2011                         | __NULL__$#$8235   | 10
adelaunay   | W2252                          | __NULL__$#$8234   | 9
adelaunay   | ASUS MS236                     | __NULL__$#$8233   | 8
adelaunay   | ASUS MS236                     | __NULL__$#$7938   | 6
adelaunay   | W2242                          | __NULL__$#$11581  | 11
adelaunay   | W2252                          | 2015-10-23$#$7939 | 7
adelaunay   | Default Monitor                | NULL              | 3
adelaunay   | Moniteur non Plug-and-Play g   | NULL              | 4
adelaunay   | 0/2011                         | NULL              | 5

**Comment by yllen** [comment]
I think a understand.
When you open your asset, the last sort was display.
If you click on the title of your column, the sort will be OK

**Comment by orthagh** [comment]
No, in other way of sorting : 
![image](https://cloud.githubusercontent.com/assets/418844/10698230/45d1dff2-79b0-11e5-8d6a-46b2825a6f15.png)

check the SQL query : 

```
GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_infocoms`.`buy_date`, '__NULL__'), '$#$',`glpi_infocoms`.`id`) SEPARATOR '$$##$$') AS `ITEM_9`,
...
ORDER BY ITEM_9 DESC 
```

**Comment by orthagh** [comment]
if you didn't, you must revert this commit to view the problem

**Comment by yllen** [comment]
Orthagh,
I made a correction that solved my problem about licences and should solve your problem too.
If OK for you, you can close this ticket.

**Comment by orthagh** [comment]
Ok, it works on all assets except thoses who's defined in $specific_itemtype.
It's better.

I just test on softwares and the problem still here.
I think we must change the search engine to return __NULL__$#$ in case of absent infocoms on items.
It should correct definitively this issue and specific case will be uneeded, we could keep group_by

**Comment by orthagh** [comment]
@yllen can you test 25202ec commit.
If it's ok for, we can revert your a1bb17b commit

**Comment by remicollet** [comment]
@orthagh IIUC your commit, it fix sort order with "forcegroupby".
Reverting a1bb17b will "remove" needed "forcegroupby".

Or you have to revert both  a1bb17b 1AND 21202a0 (so keep unconditional "forcegroupby")

**Comment by orthagh** [comment]
Yes you're right

**Comment by yllen** [comment]
Ok also for me with many lines in the result

**Comment by yllen** [comment]
IFNULL added in search engine to solve this issue opens another one: https://github.com/glpi-project/glpi/issues/232

**Comment by orthagh** [comment]
i'm not sure theses issues are related.
I'll check this afternoun

**Comment by tomolimo** [comment]
personaly I think  they are not, as the SQL Error on ITILCategories  was already existing in our special 0.83.8 release (you remember the backport of the dropdown translations you did several years ago)
