### ISSUE TITLE
CSV export with line breaks in description create multiple lines

### ISSUE THREAD

**Issue by Phil-ipp1** [glpi-project/glpi#17803]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

The CSV export creates multiple output lines for assets that have multiple lines in the description. Due to this one asset would result in multiple lines instead of a single line.

### Steps To reproduce

1. Create an Asset->Coomputer with multiple lines in description:
![image](https://github.com/user-attachments/assets/1276f5f9-683d-4ea0-992c-d2a1ed59febe)
2. Add Description to the view 
![image](https://github.com/user-attachments/assets/b4b58fa2-5e43-4a35-9308-f6566fde6407)
3. Export as CSV
![image](https://github.com/user-attachments/assets/1ebb1900-3a1b-414a-a0b9-dadb34605267)

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.15 ( => /www/glpi)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux tessrv74 5.14.0-70.13.1.el9_0.x86_64 #​1 SMP PREEMPT Tue May 17 15:53:11 EDT 2022 x86_64
PHP 8.1.9 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date, dom,
	exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring, msgpack, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_sqlite, posix, redis, session, shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="20000M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20000M" disable_functions="" 
Software: nginx/1.20.1
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.5.22-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@127.0.0.1:6033/glpi_prod
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.1.9) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.22) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /www/glpi/files/_cache has been validated.
Write access to /www/glpi/files/_cron has been validated.
Write access to /www/glpi/files has been validated.
Write access to /www/glpi/files/_dumps has been validated.
Write access to /www/glpi/files/_graphs has been validated.
Write access to /www/glpi/files/_lock has been validated.
Write access to /www/glpi/files/_pictures has been validated.
Write access to /www/glpi/files/_plugins has been validated.
Write access to /www/glpi/files/_rss has been validated.
Write access to /www/glpi/files/_sessions has been validated.
Write access to /www/glpi/files/_tmp has been validated.
Write access to /www/glpi/files/_uploads has been validated.
For security reasons, SELinux mode should be Enforcing.

Web server root directory configuration is not safe as it permits access to non-public files. See installation documentation for more details.
The following directories should be placed outside "/www/glpi":
‣ "/www/glpi/files" ("GLPI_VAR_DIR")
You can ignore this suggestion if your web server root directory is "/www/glpi/public".
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/www/glpi"
GLPI_CONFIG_DIR: "/www/glpi/config"
GLPI_VAR_DIR: "/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "0"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/www/glpi/files"
GLPI_CACHE_DIR: "/www/glpi/files/_cache"
GLPI_CRON_DIR: "/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/www/glpi/files/_lock"
GLPI_LOG_DIR: "/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/www/glpi/locales"
GLPI_VERSION: "10.0.15"
GLPI_SCHEMA_VERSION: "10.0.15@2eed74704cb07e0bac48b933cbd5c1c356f09629"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/www/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/www/glpi/vendor/psr/cache/src)
league/csv in (/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/www/glpi/vendor/symfony/cache)
html2text/html2text in (/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (psdsmtp@smtpsend.psiade.com)

</pre></details><details><summary>Plugins list</summary><pre> 
	datainjection        Name: Data injection                 Version: 2.13.5     State: Enabled                                 
		Install Method: Marketplace
	formcreator          Name: Form Creator                   Version: 2.13.9     State: Enabled                                 
		Install Method: Marketplace
	gantt                Name: gantt                          Version: 1.1.0      State: Enabled                                 
		Install Method: Marketplace
	glpiinventory        Name: GLPI Inventory                 Version: 1.3.5      State: Enabled                                 
		Install Method: Marketplace
	oauthimap            Name: Oauth IMAP                     Version: 1.4.3      State: Enabled                                 
		Install Method: Marketplace
	phpsaml              Name: PHP SAML                       Version: 1.2.1      State: Enabled                                 
		Install Method: Manual

</pre></details>

**Comment by cedric-anne** [comment]
Hi,

The CSV syntax seems OK, but it looks that you did not configured properly the import settings.

On LibreOffice, it works as expected.

![image](https://github.com/user-attachments/assets/1513f59d-2f77-4664-9d83-b724443ccddc)
![image](https://github.com/user-attachments/assets/b1b34917-0b5a-42b8-b72b-2e29c31c9244)
