### ISSUE TITLE
Modification page de connexion

### ISSUE THREAD

**Issue by DACRUZPGV** [glpi-project/glpi#17829]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Contribution description

Nous sommes actuellement en v10.0.15 avec le plugin GLPISAML v1.1.6, nous souhaitons personnaliser la page de connexion. 

Nous y sommes parvenues partiellement en modifiant : 

- via glpi configuration > configuration générale > champs Texte sur la page de connexion
- également en modifiant un fichier html qui se trouve dans /var/www/html/glpi/marketplace/glpisaml/templates 

Nous obtenons le résultat suivant : 

![image](https://github.com/user-attachments/assets/2ed3737d-843a-481d-9dbe-75f511dd5102)

Nous souhaiterions modifier le libellé "Connexion à votre compte", quelqu'un sait il où se trouve le fichier de config ?

Merci par avance pour votre aide :-)

**Comment by tech62** [comment]
I don't know how to do that, try to modify the login template here :
https://github.com/glpi-project/glpi/blob/742255e9aae6968c9e97ee9927de2dedb93308d3/templates/pages/login.html.twig#L49
