### ISSUE TITLE
Setup UI Issues

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#17823]
## Too much weight on labels

11.0:
![image](https://github.com/user-attachments/assets/4ad9788a-3fd2-47cb-b281-827aad36c328)

10.0:
![image](https://github.com/user-attachments/assets/05699eb9-b456-46a9-a0d4-9972378b60f2)

Note, that we use the default style as used in Assets (and it's fine here, but we may test also with bold).
For setup, I think we should have normal weight for labels

## Previews for some dropdowns missing

- page layout
- palettes

11.0:
![Image](https://github.com/user-attachments/assets/cc0bb39b-3331-4f8b-9cf5-bc76f2e3704a)

10.0:
![Image](https://github.com/user-attachments/assets/81955db7-529e-4af5-91d0-bf999887ea5c)

## Main header style

*(Not only in setup, but it's "ok" in computer for example)*

The ribbon seems attached to nothing.

![image](https://github.com/user-attachments/assets/b316fb55-6ae1-49ee-ac7d-1671193912f6)

We lack a background and a border probably

## Headers incoherence between tabs

There is at least 4 designs in all tabs of setup, a rationalization is required

**Comment by orthagh** [comment]
Some part of this was not done.
Anyway, I'll create separate issues.

**Comment by trasher** [comment]
DIdi not pay enough attention, sorry. But separate issues will be more clear.
