### ISSUE TITLE
glpisqllog.WARNING: DBmysql::doQuery() in /var/www/html/glpi/src/DBmysql.php line 443

### ISSUE THREAD

**Issue by Chillieloir** [glpi-project/glpi#17850]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

 SQL: SELECT DISTINCT `glpi_networkequipments`.`id` AS id, 'lisandro.eloir' AS currentuser,
                        `glpi_networkequipments`.`entities_id`, `glpi_networkequipments`.`is_recursive`,  `glpi_networkequipments`.`name` AS `ITEM_NetworkEquipment_1`,
                        `glpi_networkequipments`.`id` AS `ITEM_NetworkEquipment_1_id`,
                        `glpi_entities`.`completename` AS `ITEM_NetworkEquipment_80`,  `glpi_networkequipmenttypes`.`name` AS `ITEM_NetworkEquipment_4`,  `glpi_locatio$
                                               '$#$',`glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328`.`id`) ORDER BY `glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c$
                              AS `ITEM_NetworkEquipment_126`,

                  `glpi_networkequipments`.`serial` AS `ITEM_NetworkEquipment_5`,  `glpi_groups`.`completename` AS `ITEM_NetworkEquipment_71`,  `glpi_states`.`complete$
                                               '$#$',`glpi_networkports`.`id`) ORDER BY `glpi_networkports`.`id` SEPARATOR '$$##$$')
                              AS `ITEM_NetworkEquipment_21`,

                  `glpi_networkequipments`.`date_mod` AS `ITEM_NetworkEquipment_19` FROM `glpi_networkequipments`LEFT JOIN `glpi_entities`
                                          ON (`glpi_networkequipments`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_networkequipmenttypes`
                                          ON (`glpi_networkequipments`.`networkequipmenttypes_id` = `glpi_networkequipmenttypes`.`id`
                                              )LEFT JOIN `glpi_locations`
                                          ON (`glpi_networkequipments`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_manufacturers`
                                          ON (`glpi_networkequipments`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_networkequipmentmodels`
                                          ON (`glpi_networkequipments`.`networkequipmentmodels_id` = `glpi_networkequipmentmodels`.`id`
                                              ) LEFT JOIN `glpi_ipaddresses`  AS `glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328`
                                          ON (`glpi_networkequipments`.`id` = `glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328`.`mainitems_id`
                                              AND `glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328`.`mainitemtype` = 'NetworkEquipment'
                                               AND `glpi_ipaddresses_3714572b4d6732a91ac0d68a00a3c328`.`is_deleted` = '0' AND  NOT (`glpi_ipaddresses_3714572b4d6732a91$
                                          ON (`glpi_networkequipments`.`groups_id` = `glpi_groups`.`id`
                                              )LEFT JOIN `glpi_states`
                                          ON (`glpi_networkequipments`.`states_id` = `glpi_states`.`id`
                                              ) LEFT JOIN `glpi_networkports`
                                          ON (`glpi_networkequipments`.`id` = `glpi_networkports`.`items_id`
                                              AND `glpi_networkports`.`itemtype` = 'NetworkEquipment'
                                              )  WHERE  `glpi_networkequipments`.`is_deleted` = 0  AND `glpi_networkequipments`.`is_template` = 0  AND  ( `glpi_network$

### Relevant log output

```shell
When trying to access the path http://192.168.1.5/front/networkequipment.php nothing appears and when viewing the logs in /var/www/html/glpi/files/_log/sql-errors.log this error log appears
```

### Page URL

http://192.168.1.5/front/networkequipment.php

**Comment by trasher** [comment]
Please provide all required information; write only in english, and give details about how to reproduce. Also, log message seems truncated.
