### ISSUE TITLE
Unable to login to GLPI

### ISSUE THREAD

**Issue by jackli1982** [glpi-project/glpi#17856]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

I installed GLPI for the first time and used a K8s Pod. The Pod runs everything normally, but now I'm encountering an issue. I can reach the login page where I enter the username and password, but I cannot access the system. I tried using the username and password 'glpi', but neither works for logging in. I attempted to create an account from the database, but it wouldn't let me. I have reinstalled multiple times, but the same problem persists. I am using images version 10.0.16 and need your help to determine where the issue lies and how to troubleshoot it.
![GLPI2](https://github.com/user-attachments/assets/08440455-ec3e-4e4e-998e-5167a5d3ec0e)
![GLPI1](https://github.com/user-attachments/assets/b8ee7e7c-799d-4ee1-91da-1b419d8056cf)

### Relevant log output

```shell
[2024-09-16 09:08:29] glpiphplog.WARNING: Test logger
[2024-09-16 09:08:30] glpiphplog.WARNING: Test logger
[2024-09-16 09:08:30] glpiphplog.WARNING: Test logger
[2024-09-16 09:08:31] glpiphplog.WARNING: Test logger
[2024-09-16 09:08:31] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "version" in /var/www/html/src/Console/Database/CheckSchemaIntegrityCommand.php at line 169
  Backtrace :
  vendor/symfony/console/Command/Command.php:298     Glpi\Console\Database\CheckSchemaIntegrityCommand->execute()
  vendor/symfony/console/Application.php:1040        Symfony\Component\Console\Command\Command->run()
  src/Console/Application.php:286                    Symfony\Component\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:301         Glpi\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:171         Symfony\Component\Console\Application->doRun()
  bin/console:122                                    Symfony\Component\Console\Application->run()

[2024-09-16 09:08:31] glpiphplog.WARNING: Test logger
[2024-09-16 09:08:50] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "version" in /var/www/html/src/Console/Database/CheckSchemaIntegrityCommand.php at line 169
  Backtrace :
  vendor/symfony/console/Command/Command.php:298     Glpi\Console\Database\CheckSchemaIntegrityCommand->execute()
  vendor/symfony/console/Application.php:1040        Symfony\Component\Console\Command\Command->run()
  src/Console/Application.php:286                    Symfony\Component\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:301         Glpi\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:171         Symfony\Component\Console\Application->doRun()
  bin/console:122                                    Symfony\Component\Console\Application->run()

[2024-09-16 09:08:50] glpiphplog.WARNING: Test logger
[2024-09-16 09:09:05] glpiphplog.WARNING: Test logger
[2024-09-16 09:09:06] glpiphplog.WARNING: Test logger
[2024-09-16 09:09:32] glpiphplog.WARNING: Test logger
```

**Comment by cedric-anne** [comment]
Hi,

The problem could be due to the fact that your session cookie is not received/sent by your browser. For instance, if the `session.cookie_secure` directive is set to `on`, the the session cookie will not be available on the `http://` protocol. Please check your server configuration.

**Comment by jackli1982** [comment]
Thank you very much for your reply. Which configurations should I check? I am completely unfamiliar with GLPI, as this is my first time using it.

> This issue has been closed as we only track bugs here.
> 
> You can get community support on [forums](https://forum.glpi-project.org/) or you can consider [taking a subscription](https://glpi-project.org/subscriptions/) to get professional support. You can also [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.

**Comment by trasher** [comment]
Please ask your question on [forums](http://forum.glpi-project.org).
