### ISSUE TITLE
Update tasks when ticket status is closed

### ISSUE THREAD

**Issue by jgobet** [glpi-project/glpi#1786]
Hello,

In GLPI 0.90.x it is not possible to modify the tasks of a ticket when it is closed.
But in the new version 9.1.2 it is possible to modify these tasks in the planning or directly from the edition of the ticket.
Can you re-establish this control?

Thanks.

**Comment by jgobet** [comment]
Hello,

We can always resize and drag the tasks directly in the planning.
Can you fix this bug ?

Thanks.

**Comment by jgobet** [comment]
Same in GLPI 9.1.4...

**Comment by yllen** [comment]
in 9.1.4 if the ticket is closed you don't have save button in the task form in ticket or in planning.

**Comment by jgobet** [comment]
It works for save button but you can resize or drag the task in the planning.
So the begin date (or en date) and the duration can be updated when the ticket is closed...

**Comment by jgobet** [comment]
It's always possible to resize and drag tasks in the planning when the ticket is closed.
Can you fix it in the next version of GLPI please ?
Thanks.
