### ISSUE TITLE
No info in asset Phones, but rows in glpi.glpi_phones exists

### ISSUE THREAD

**Issue by nm4D** [glpi-project/glpi#17871]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.6

### Bug description

I add new phone into asset `Phones`, but  when i go into `https://<ip-address>/front/phone.php` no phones shows.
In mysql table `glpi.glpi_phones` info collected:
```
| id | entities_id | name          | date_mod            | contact | contact_num | users_id_tech | groups_id_tech | comment | serial               | otherserial | locations_id | phonetypes_id | phonemodels_id | brand | phonepowersupplies_id | number_line | have_headset | have_hp | manufacturers_id | is_global | is_deleted | is_template | template_name | users_id | groups_id | states_id | ticket_tco | is_dynamic | autoupdatesystems_id | uuid | date_creation       | is_recursive | last_inventory_update |
| 10 |           0 |               | 2024-09-17 09:17:49 |         |             |             0 |              0 |         |                      |             |            0 |             0 |              0 |       |                     0 | 0           |            0 |       0 |                0 |         0 |          0 |        NULL | NULL          |        0 |         0 |         0 |     0.0000 |          0 |                    0 |      | 2024-09-17 08:49:59 |            0 | NULL           
 ```

i can go to https://<ip-address>/front/phone.form.php?id=10

### Relevant log output

```shell
no error logs
```

### Steps To reproduce

1. Add new item into asset `Phones` 
2. Goto asset `Phones`
3. GLPI shows `No item found` in this page

### Your GLPI setup information

GLPI 10.0.6 ( => /var/www/html/glpi)
Installation mode: TARBALL
Current language:en_US

**Comment by cconard96** [comment]
GitHub issues as for reporting bugs only. Since this may be a bug that was already fixed in a previous version, we ask that you test using the latest GLPI release. You may choose to set up a separate GLPI installation of the latest version using a copy of your database to test this issue.
