### ISSUE TITLE
Failed to download export Assets and Users

### ISSUE THREAD

**Issue by FelipeBasilio1991** [glpi-project/glpi#17902]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

11

### Bug description

Hello. I have a problem when I want to export computers or users, the button where they download them is simply not working.
<img width="830" alt="Capture" src="https://github.com/user-attachments/assets/30cbc97a-ceb9-4c97-84d5-74d2e50892ab">

**Comment by trasher** [comment]
Please try https://github.com/glpi-project/glpi/pull/17907
