### ISSUE TITLE
Access to the ticket tasks without these permissions

### ISSUE THREAD

**Issue by f0rextazy** [glpi-project/glpi#17914]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

GLPI 10.0.14

### Bug description

![image](https://github.com/user-attachments/assets/b86cfe64-8ae7-45b5-aa03-7bc1354dfeda)
There is no access to the tasks.

If I am in "Assigned to", then I have access to create tasks
![image](https://github.com/user-attachments/assets/6ac49898-7c25-43c6-ab2d-729152b293af)

If I am no in "Assigned to", then I dont have access to create tasks
![image](https://github.com/user-attachments/assets/f7c5d66d-1e2c-4f12-bab1-45decc330c99)

How to completely restrict access to ticket tasks?

**Comment by cconard96** [comment]
We only track bugs here.
Task permissions will be changed in GLPI 11. See #17298.
