### ISSUE TITLE
Add default location for helpdesk ticket creation

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1793]
Hello,

When creating ticket via helpdesk (simplified interface), the location field must be set by default to the locations_id of the requester.

regards,
Tomolimo

**Comment by remicollet** [comment]
There is already 2 "rules" for this (Location from user or from item)

**Comment by tomolimo** [comment]
Where? in the simplified interface?

**Comment by remicollet** [comment]
In the "ticket rules"
Applied when the ticket is created (if the user haven't chose another location)

Works for all way to create ticket (normal interface, simplified, mail collecteur, API...)

**Comment by tomolimo** [comment]
Then it's not in the default value in the form, that's the purpose of the PR.
The rules are not applied at showForm() (=ticket creation display) but when submitting the creation form.
The idea of this PR is to have a default value when displaying the ticket creation form. By default the value of the locations_id is `0`, but to simplified the life of the end-users, I've set it by default to its location. He may of course change it if necessary (set it to none '-----', or else), and any business rules may changed it also.

**Comment by yllen** [comment]
I not agree with this change.
This field was added only to define that the requester was temporally not in his habitual location.

A technician can know the location of a requester with the icon near the name

**Comment by tomolimo** [comment]
Hello Yllen,
This default value is only a default value!
I totally agree with that the idea of this field is to permit the requester to tell that current incident/request occurs somewhere else than his/her own location, but most of the time (80%/20%), the ticket will be for his/her own location, so why not set it to this as a default location for ticket?
An empty field is always disturbing :), and will lead requesters to input their locations even if not changed.
Or another solution, if you really want to left it empty, then change the description of the field to "Location (left empty will default to xxxxxx)" where xxxxxx is the requester location, or something like that .
Regards,
Tomolimo

**Comment by Giudy** [comment]
I do agree with Tomolino: leaving the field blank can be tricky for a user. taking it from the user location clarify and speed up the process of creating a ticket.

http://forum.glpi-project.org/viewtopic.php?id=33726

**Comment by yllen** [comment]
Like Remi said, if you want this default value you can define it in a business rule.
I totally disagree this change

**Comment by trasher** [comment]
Change refused as it.
