### ISSUE TITLE
GLPI 9.2 - debug mode icon in header unexpecdly off

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1796]
Hi

If I login as glpi, enable debug mode, the icon becomes red.

Adter logout / login cycle it reverts to white (then disabled). However at the bottom of the page, the debug button is here, and working.

If I try to disable the debug mode, it is actually disabled and the button bottom is no longer available. 

It appears thre is a sync issue with the actual state of the debug mode and the switch after login with debug mode enabled.

**Comment by trasher** [comment]
I've unset the milestone since the feature is already in here; but this is a 9.2 issue ;)
