### ISSUE TITLE
suggest.glpi-project.org certificate expired on 23. 6. 2024.

### ISSUE THREAD

**Issue by aha999** [glpi-project/glpi#17963]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10

### Bug description

It is not possible to connect to the website https://suggest.glpi-project.org/ because the certificate is expired.

The browser output (Firefox):

Did Not Connect: Potential Security Issue

Firefox detected an issue and did not continue to suggest.glpi-project.org. The website is either misconfigured or your computer clock is set to the wrong time.

It’s likely the website’s certificate is expired, which prevents Firefox from connecting securely.

What can you do about it?

suggest.glpi-project.org has a security policy called HTTP Strict Transport Security (HSTS), which means that Firefox can only connect to it securely. You can’t add an exception to visit this site.

The issue is most likely with the website, and there is nothing you can do to resolve it. You can notify the website’s administrator about the problem.

[Learn more…](https://support.mozilla.org/1/firefox/130.0.1/WINNT/sl/time-errors)

Websites prove their identity via certificates, which are valid for a set time period. The certificate for suggest.glpi-project.org **expired on 23. 6. 2024.**
 
Error code: [SEC_ERROR_EXPIRED_CERTIFICATE](about:certerror?e=nssBadCert&u=https%3A//suggest.glpi-project.org/&s=badStsCert&c=UTF-8&d=%20#certificateErrorDebugInformation)
 
[View Certificate](javascript:void(0))
![slika](https://github.com/user-attachments/assets/856cf3d2-770e-497f-8517-aeaea25d0ed3)

### Page URL

https://suggest.glpi-project.org/

### Steps To reproduce

1. Open https://suggest.glpi-project.org/
2. See certificate error
3. unable to connect to the website to suggest features

**Comment by trasher** [comment]
Thank you for reporting. Problem has been solved or should be quickly.
