### ISSUE TITLE
error with missing table

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1797]
Hello

I have this error all the time in sql logs,

2017-02-09 15:58:21 [854@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_knowbaseitems_items` WHERE `itemtype` = \'Ticket\' AND `items_id` = 2017020321
  Error: Table 'glpidb91.glpi_knowbaseitems_items' doesn't exist
  Backtrace :
  inc\dbmysql.class.php:919                          
  inc\dbmysql.class.php:543                          DBmysqlIterator->__construct()
  inc\db.function.php:317                            DBmysql->request()
  inc\knowbaseitem_item.class.php:77                 countElementsInTable()
  inc\commonglpi.class.php:207                       KnowbaseItem_Item->getTabNameForItem()
  inc\ticket.class.php:703                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:162                       Ticket->defineTabs()
  inc\commonglpi.class.php:723                       CommonGLPI->defineAllTabs()
  inc\commonglpi.class.php:1174                      CommonGLPI->showTabsContent()
  front\ticket.form.php:193                          CommonGLPI->display()

COuld you provide me the command in mysql to add missing table please

glpi 9.2

**Comment by trasher** [comment]
Hello,

Check `install/mysql/glpi-9.2-empty.sql` file.

**Comment by satyan01** [comment]
I don't understand What I have to do ?

**Comment by satyan01** [comment]
I found, thx
