### ISSUE TITLE
Right panel display error and no button respond or other entity

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#17999]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Right panel display error and no button respond or other entity

### Relevant log output

```shell
Twig Error (Twig\Error\RuntimeError): "An exception has been thrown during the rendering of a template ("Empty IN are not allowed")." in template "/var/www/assistance/templates/components/itilobject/fields_panel.html.twig" at line 209
```

**Comment by cedric-anne** [comment]
Hi,

Please try to remove the `files/_cache/template` directory and see if problem persist.

**Comment by falco2001** [comment]
Hello, Thank you yes it’s the same!!! Thank you

**Comment by trasher** [comment]
Please also try without any plugin.

**Comment by falco2001** [comment]
php bin/console plugin:deactivate
reload apache --> idem Thank you

**Comment by falco2001** [comment]
Is it the same problem? github.com/glpi-project/glpi/issues/17437 thank you
