### ISSUE TITLE
When submit in any option it stay in blank screen

### ISSUE THREAD

**Issue by DevDorrejo** [glpi-project/glpi#18004]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Each time I click submit, need to reload the website because after submit it stay in a blank screen.

### Relevant log output

```shell
[2024-10-03 14:51:33] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "HTTP_REFERER" in /srv/www/glpi/front/central.php at line 67
Backtrace :
public/index.php:82                                require()

[2024-10-03 14:51:33] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/www/glpi/src/Html.php at line 529
Backtrace :
src/Html.php:529                                   addslashes()
front/central.php:67                               Html::redirect()
public/index.php:82                                require()

[2024-10-03 14:51:43] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "HTTP_REFERER" in /srv/www/glpi/front/central.php at line 67
Backtrace :
public/index.php:82                                require()

[2024-10-03 14:51:43] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): addslashes(): Passing null to parameter #1 ($string) of type string is deprecated in /srv/www/glpi/src/Html.php at line 529
Backtrace :
src/Html.php:529                                   addslashes()
front/central.php:67                               Html::redirect()
public/index.php:82                                require()

[2024-10-03 14:52:36] glpiphplog.DEBUG: Html::compileScss() in /srv/www/glpi/src/Html.php line 6935
Compile css/palettes/darker.scss  {"user":"7@tickets"} 
[2024-10-03 14:54:33] glpiphplog.DEBUG: Html::compileScss() in /srv/www/glpi/src/Html.php line 6935
Compile css/standalone/gridstack-grids.scss  {"user":"7@tickets"} 
[2024-10-03 14:54:35] glpiphplog.DEBUG: Html::compileScss() in /srv/www/glpi/src/Html.php line 6935
Compile css/standalone/dashboard.scss  {"user":"7@tickets"} 
[2024-10-03 14:54:35] glpiphplog.DEBUG: Html::compileScss() in /srv/www/glpi/src/Html.php line 6935
Compile css/standalone/chartist.scss  {"user":"7@tickets"} 

[2024-10-03 14:52:58] glpisqllog.ERROR: DBmysql::doQuery() in /srv/www/glpi/src/DBmysql.php line 403
*** MySQL query error:
SQL: SELECT DISTINCT `glpi_tickets`.*, `glpi_itilcategories`.`completename` AS `catname` FROM `glpi_tickets` LEFT JOIN `glpi_groups_tickets` ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`) LEFT JOIN `glpi_tickets_users` ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`) LEFT JOIN `glpi_suppliers_tickets` ON (`glpi_tickets`.`id` = `glpi_suppliers_tickets`.`tickets_id`) LEFT JOIN `glpi_itilcategories` ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id`) LEFT JOIN `glpi_items_tickets` ON (`glpi_tickets`.`id` = `glpi_items_tickets`.`tickets_id`) LEFT JOIN `glpi_tickettasks` ON (`glpi_tickets`.`id` = `glpi_tickettasks`.`tickets_id`) LEFT JOIN `glpi_ticketvalidations` ON (`glpi_tickets`.`id` = `glpi_ticketvalidations`.`tickets_id`) WHERE `status` = '1' AND `is_deleted` = '0' ORDER BY `glpi_tickets`.`date_mod` DESC LIMIT 50
Error: Column 'status' in where clause is ambiguous
Backtrace :
src/DBmysqlIterator.php:112                        DBmysql->doQuery()
src/DBmysql.php:1109                               DBmysqlIterator->execute()
src/Ticket.php:5340                                DBmysql->request()
src/Central.php:161                                Ticket::showCentralNewList()
src/Central.php:106                                Central::showGlobalView()
src/CommonGLPI.php:694                             Central::displayTabContentForItem()
ajax/common.tabs.php:120                           CommonGLPI::displayStandardTab()
public/index.php:82                                require()
{"user":"7@tickets"}
```

### Steps To reproduce

1. Fresh install of GLPI.
2. Setup everything.
3. Normal User but each time I submit an option, blank screen, need to reload.

### Your GLPI setup information

<details><summary>Information about system installation & configuration</summary><pre>GLPI 10.0.16 ( => /srv/www/glpi)
Installation mode: TARBALL
Current language:en_US

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux tickets 6.4.0-150600.23.22-default #​1 SMP PREEMPT_DYNAMIC Fri Sep 13 10:42:50 UTC 2024 (5c05eeb) x86_64
PHP 8.2.20 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, gd, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite,
	random, session, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="900" memory_limit="512M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" disable_functions="" 
Software: Apache (Apache Server at tickets.ind.local Port 80
)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 11.5.2-MariaDB-ubu2404
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: tickets@127.0.0.1/mdb_tickets
	Host info: 127.0.0.1 via TCP/IP
	
PHP version (8.2.20) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (11.5.2) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /srv/www/glpi/files/_cache has been validated.
Write access to /srv/www/glpi/files/_cron has been validated.
Write access to /srv/www/glpi/files has been validated.
Write access to /srv/www/glpi/files/_dumps has been validated.
Write access to /srv/www/glpi/files/_graphs has been validated.
Write access to /srv/www/glpi/files/_lock has been validated.
Write access to /srv/www/glpi/files/_pictures has been validated.
Write access to /srv/www/glpi/files/_plugins has been validated.
Write access to /srv/www/glpi/files/_rss has been validated.
Write access to /srv/www/glpi/files/_sessions has been validated.
Write access to /srv/www/glpi/files/_tmp has been validated.
Write access to /srv/www/glpi/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /srv/www/glpi/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/srv/www/glpi"
GLPI_CONFIG_DIR: "/srv/www/glpi/config"
GLPI_VAR_DIR: "/srv/www/glpi/files"
GLPI_MARKETPLACE_DIR: "/srv/www/glpi/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/srv/www/glpi/files"
GLPI_CACHE_DIR: "/srv/www/glpi/files/_cache"
GLPI_CRON_DIR: "/srv/www/glpi/files/_cron"
GLPI_DUMP_DIR: "/srv/www/glpi/files/_dumps"
GLPI_GRAPH_DIR: "/srv/www/glpi/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/srv/www/glpi/files/_locales"
GLPI_LOCK_DIR: "/srv/www/glpi/files/_lock"
GLPI_LOG_DIR: "/srv/www/glpi/files/_log"
GLPI_PICTURE_DIR: "/srv/www/glpi/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/srv/www/glpi/files/_plugins"
GLPI_RSS_DIR: "/srv/www/glpi/files/_rss"
GLPI_SESSION_DIR: "/srv/www/glpi/files/_sessions"
GLPI_TMP_DIR: "/srv/www/glpi/files/_tmp"
GLPI_UPLOAD_DIR: "/srv/www/glpi/files/_uploads"
GLPI_INVENTORY_DIR: "/srv/www/glpi/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/srv/www/glpi/locales"
GLPI_VERSION: "10.0.16"
GLPI_SCHEMA_VERSION: "10.0.16@b13256c443dd4fdb27b4a0d3b8fea8caba4dfaa9"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/srv/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/srv/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/srv/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/srv/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/srv/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/srv/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/srv/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/srv/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/srv/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/srv/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/srv/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/srv/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/srv/www/glpi/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/srv/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/srv/www/glpi/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/srv/www/glpi/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/srv/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/srv/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/srv/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/srv/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/srv/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/srv/www/glpi/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/srv/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/srv/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/srv/www/glpi/vendor/psr/simple-cache/src)
psr/cache in (/srv/www/glpi/vendor/psr/cache/src)
league/csv in (/srv/www/glpi/vendor/league/csv/src)
mexitek/phpcolors in (/srv/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/srv/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/srv/www/glpi/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/srv/www/glpi/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/srv/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/srv/www/glpi/vendor/paragonie/sodium_compat/src)
symfony/cache in (/srv/www/glpi/vendor/symfony/cache)
html2text/html2text in (/srv/www/glpi/vendor/html2text/html2text/src)
symfony/css-selector in (/srv/www/glpi/vendor/symfony/css-selector)
symfony/dom-crawler in (/srv/www/glpi/vendor/symfony/dom-crawler)
twig/twig in (/srv/www/glpi/vendor/twig/twig/src)
twig/string-extra in (/srv/www/glpi/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/srv/www/glpi/vendor/symfony/polyfill-php82)
league/oauth2-client in (/srv/www/glpi/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/srv/www/glpi/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/srv/www/glpi/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>LDAP directories</summary><pre> 
Server: '10.0.0.21', Port: '389', BaseDN: 'OU=Tecnologia de la Informacion,OU=example,DC=exa,DC=mple', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=Walddys E.
		Dorrejo Cespedes,OU=Tecnologia de la Informacion,OU=example,DC=exa,DC=mple', Use TLS: none

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+SSL (notificaciones@example.com@example.com)

</pre></details><details><summary>Plugins list</summary><pre> 

</pre></details>

**Comment by cedric-anne** [comment]
> Each time I click submit, need to reload the website because after submit it stay in a blank screen.

I do not understand what you are trying to do. Could you explain a bit more the context of your issue?

**Comment by DevDorrejo** [comment]
Video:
https://1drv.ms/v/s!AoQL6wLQkON3iqsicj8y-7KUl-9Jbg?e=UjcrFd

**Comment by DevDorrejo** [comment]
> Do you have some custom server-side configuration used to enhance performances ? These 302 response codes are not corresponding to the normal GLPI behaviour.

I have a clean setup with Apache2 + php-fpm, I only change what the doc glpi recommended

**Comment by cconard96** [comment]
I only recreate the blank page issue on 10.0.16 when the Referer header is missing. Do you have an extension that is blocking this header? Maybe a privacy related extension?

If this header is missing on the current `main` branch it just redirects to the GLPI homepage when it cannot redirect back to the previous form/page so I guess there was a recent workaround for this.

**Comment by DevDorrejo** [comment]
Ok, found what was causing the issue, this header:
`Header always set Referrer-Policy "no-referrer"`

if added this will cause issue with glpi

**Comment by trasher** [comment]
Seems like issue is resolved
