### ISSUE TITLE
Cannot add file to Licenses - error "Filetype not allowed"

### ISSUE THREAD

**Issue by as-umed** [glpi-project/glpi#18002]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.15

### Bug description

I cannot add PDF as a picture to License entity. Always getting error "Filetype not allowed". In Home -> Setup -> Dropdowns -> Document types every type is allowed. In Documents you can upload any file, but not in Licenses.

### Page URL

https://glpi/front/softwarelicense.form.php?id=1

**Comment by cedric-anne** [comment]
Hi,

This is not a bug. The only types accepted for the pictures fields are the following image types: `.gif`, `.png`, `.jpg`, `.jpeg`.
