### ISSUE TITLE
Get date formats from dedicated methods

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#1803]
Hi,

On two separate files the date formats are declared. I'm working on a plugin which uses these, but in case of an update in the list I'll have to update mine too.
It would be great to have a method like `Config::getAvailableDateformats()`.

https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/planning.class.php#L538
https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/config.class.php#L978

Edit: The use of constants to define the keys would be great too. `$CFG_GLPI['date_format'] == 0` can be hard to read/understand.

Thanks!

**Comment by trasher** [comment]
Since formats are different, we cannot factorize.

**Comment by pVesian** [comment]
@trasher The formats are different in output but the same in syntax (if you ignore the "-" between them and the translation, they are the same).
```
$date_formats = array(0 => 'YYYY MMM DD',
                            1 => 'DD MMM YYYY',
                            2 => 'MMM DD YYYY');
```
```
$date_formats = array(0 => __('YYYY-MM-DD'),
                            1 => __('DD-MM-YYYY'),
                            2 => __('MM-DD-YYYY'));
```

By the way, the first one has MMM and the second MM, shouldn't it be the same in both places?

**Comment by trasher** [comment]
One is for a PHP display, the other for a javascript one. And the "-" is also a difference between the format. So, no, as I said: format are different.

**Comment by pVesian** [comment]
@trasher Ok, it doesn't have to be factorized, could this be in dedicated functions then? That way it could be used by plugins.

**Comment by trasher** [comment]
I guess we could create methods to retrieve available formats, yes :)
