### ISSUE TITLE
Zabbix cannot send notification to GLPI---An error appears

### ISSUE THREAD

**Issue by Hasanmonitoring** [glpi-project/glpi#18032]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.0.14

### Bug description

Sending failed: Error received from GLPi: missing parameter app_token; view documentation in your browser at https://itsm.xb.uz/apirest.php/#ERROR_APP_TOKEN_PARAMETERS_MISSING

### Page URL

https://itsm.xb.uz/

**Comment by Hasanmonitoring** [comment]
I don't know what to do with it, help me

**Comment by cconard96** [comment]
There is nothing here that indicates a bug with GLPI. There isn't much information provided at all really. You say a different software is having trouble sending things to the GLPI API which sounds like a configuration issue with that software or a bug in that software.

We only track GLPI bugs here. If you want other help, you need to post on the forum and see if someone in the community is able to help or pay for professional help.

**Comment by cedric-anne** [comment]
Also, it duplicates other issues you can find here: https://github.com/glpi-project/glpi/issues?q=is%3Aissue+zabbix+is%3Aclosed
