### ISSUE TITLE
Partial inventory duplicates VPN networkport

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#18062]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0.16

### Bug description

When a partial inventory updates an existing port (related to a VPN that have an IP change for example), the existing port is not removed nor updated, it ends with an extra port on asset.
There is certainly several other cases.

**Comment by cedric-anne** [comment]
Fixed by #18074
