### ISSUE TITLE
Don't change "Destination Entity" field in the "target ticket"

### ISSUE THREAD

**Issue by igortarasiuk** [glpi-project/glpi#1807]
Hello!

In the form plugins/formcreator/front/targetticket.form.php?id=1
1) Administratiron > Forms 
2) Open the form
3) Change tab int form "Destination" and edit it.

I can't change "Target ticket" >  field "Destination Entity"  on any one. 
When I try to change it and save form - I get error in the log file:  files/_log/php-errors.log

Error is:

2017-02-10 13:48:26 [314@up-www-lo]
  *** PHP Notice(8): Undefined index: destination_entity
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:207 
  inc/commonglpi.class.php:473                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
2017-02-10 13:48:26 [314@up-www-lo]
  *** PHP Notice(8): Undefined index: destination_entity_value
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:252 
  inc/commonglpi.class.php:473                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
2017-02-10 13:48:26 [314@up-www-lo]
  *** PHP Notice(8): Undefined index: destination_entity_value
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:271 
  inc/commonglpi.class.php:473                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()
2017-02-10 13:48:26 [314@up-www-lo]
  *** PHP Notice(8): Undefined index: destination_entity_value
  Backtrace :
  plugins/formcreator/inc/targetticket.class.php:290 
  inc/commonglpi.class.php:473                       PluginFormcreatorTargetTicket->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()

Thanks a lot!

**Comment by trasher** [comment]
Please report bug against the plugin on https://github.com/pluginsGLPI/formcreator/
