### ISSUE TITLE
Satisfaction survey is not displayed in simplified interface

### ISSUE THREAD

**Issue by lklsr** [glpi-project/glpi#1811]
Sirs, good afternoon.

Does anyone know how to solve the problem of displaying satisfaction survey in the simplified interface? In the standard interface it is displayed normally but in the simplified the pending evaluation tickets are displayed but clicking does not show the evaluation field.

![image](https://cloud.githubusercontent.com/assets/18348158/22889528/9a90b2b6-f1f0-11e6-9c40-81039e8d90d5.png)

![image](https://cloud.githubusercontent.com/assets/18348158/22889553/ae404650-f1f0-11e6-8c94-01307ca943e5.png)

**Comment by tomolimo** [comment]
Hello 
Which version do you have? 
Regards 
Tomolimo

**Comment by jorgecamargosdb** [comment]
good afternoon,
@tomolimo 


I'm having the same problem in version 9.1.1.

Instruções de instalação e configuração
[code]
 
GLPI 9.1.1 (/glpi_911 => E:\Xamp\htdocs\glpi_911)

Server
 
Operating system: Windows NT SDB_PROJETOS 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP 5.6.23 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype,
	curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash,
	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, session, standard, tokenizer, wddx, xml,
	xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="12M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2000M" 
Software: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23 (Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23 Server at localhost
	Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.1.13-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi_911
	Host info: localhost via TCP/IP
	
OKE:\Xamp\htdocs\glpi_911/config : OK
OKE:\Xamp\htdocs\glpi_911/files : OK
OKE:\Xamp\htdocs\glpi_911/files/_dumps : OK
OKE:\Xamp\htdocs\glpi_911/files/_sessions : OK
OKE:\Xamp\htdocs\glpi_911/files/_cron : OK
OKE:\Xamp\htdocs\glpi_911/files/_graphs : OK
OKE:\Xamp\htdocs\glpi_911/files/_lock : OK
OKE:\Xamp\htdocs\glpi_911/files/_plugins : OK
OKE:\Xamp\htdocs\glpi_911/files/_tmp : OK
OKE:\Xamp\htdocs\glpi_911/files/_rss : OK
OKE:\Xamp\htdocs\glpi_911/files/_uploads : OK
OKE:\Xamp\htdocs\glpi_911/files/_pictures : OK
OKE:\Xamp\htdocs\glpi_911/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.1.21 in (E:\Xamp\htdocs\glpi_911\lib\htmlawed)
phpCas version 1.3.4 in (E:\Xamp\htdocs\glpi_911\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (E:\Xamp\htdocs\glpi_911\vendor\phpmailer\phpmailer)
Zend Framework in (E:\Xamp\htdocs\glpi_911\vendor\zendframework\zend-loader\src)
zetacomponents/graph in (E:\Xamp\htdocs\glpi_911\vendor\zetacomponents\graph\src)
SimplePie version 1.4.1 in (E:\Xamp\htdocs\glpi_911\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (E:\Xamp\htdocs\glpi_911\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (E:\Xamp\htdocs\glpi_911\vendor\michelf\php-markdown\Michelf)
true/punycode in (E:\Xamp\htdocs\glpi_911\vendor\true\punycode\src)
iacaml/autolink in (E:\Xamp\htdocs\glpi_911\vendor\iamcal\lib_autolink)
sabre/vobject in (E:\Xamp\htdocs\glpi_911\vendor\sabre\vobject\lib)

LDAP directories
 
Server: '10.0.0.11', Port: '389', BaseDN: 'dc=agilitynetworks,dc=com,dc=br', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'pservices@agilitynetworks.com.br', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+SSL (correio.level3br.com@pservices@agilitynetworks.com.br)

Mails receivers
 

Plugins list
 
	accounts             Name: Accounts                       Version: 2.2.0      State: New
	fields               Name: Additionnal fields             Version: 1.3.1      State: To be cleaned
	news                 Name: Alerts                         Version: 9.1        State: To be cleaned
	webapplications      Name: Aplicações web                 Version: 2.1.1      State: To be cleaned
	appliances           Name: Appliances                     Version: 2.1.       State: To be cleaned
	databases            Name: Bancos de dados                Version: 1.8.1      State: To be cleaned
	behaviors            Name: Behaviours                     Version: 1.2        State: Enabled
	certificates         Name: Certificados                   Version: 2.1.1      State: To be cleaned
	chat                 Name: Chat                           Version: 1.0.2      State: To be cleaned
	contrato             Name: Contrato                       Version: 0.1        State: To be cleaned
	environment          Name: Environment                    Version: 2.0.0      State: Not installed
	datainjection        Name: File injection                 Version: 2.4.2      State: To be cleaned
	formcreator          Name: Forms                          Version: 0.90-1.3.4 State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.2.4      State: Not installed
	morenotifications    Name: More notifications             Version: 9.1        State: To be cleaned
	mreporting           Name: More Reporting                 Version: 1.3.0      State: To be cleaned
	moreticket           Name: More ticket                    Version: 1.2.3      State: To be cleaned
	mydashboard          Name: My Dashboard                   Version: 1.3.2      State: To be cleaned
	os                   Name: Os                             Version: 0.0.3      State: To be cleaned
	additionalalerts     Name: Others alerts                  Version: 1.9.0      State: To be cleaned
	dashboard            Name: Painel                         Version: 0.7.8      State: To be cleaned
	pdf                  Name: Print to pdf                   Version: 1.0.2      State: To be cleaned
	purgelogs            Name: Purge history                  Version: 0.85+1.1   State: To be cleaned
	racks                Name: Rack enclosures management     Version: 1.7.0      State: New
	reports              Name: Relatórios                     Version: 1.9.1      State: To be cleaned
	renamer              Name: Renamer                        Version: 0.90-1.0   State: Not installed
	seasonality          Name: Seasonalities                  Version: 1.1.0      State: To be cleaned
	financialreports     Name: Situação do ativo              Version: 2.2.1      State: To be cleaned
	solvecloseticketacti Name: solvecloseticketaction         Version: 0.85+1.0   State: To be cleaned
	tasklists            Name: Tasks list                     Version: 1.0.0      State: To be cleaned
	timelineticket       Name: Timeline of ticket             Version: 0.90.3     State: To be cleaned

[/code]

**Comment by tomolimo** [comment]
Fixed in 9.1.2 in #1371
