### ISSUE TITLE
Broken newlines when creating a project from a template

### ISSUE THREAD

**Issue by tograss** [glpi-project/glpi#18123]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

When creating a project from a template newlines in the description field getting escaped. So after a save instead of a newline \r\n is displayed. This only happens when creating a project from a template. 
Reason is the call to the clone function in Clonable.php and there the call to `Toolbox::addslashes_deep($value);` in line 228.
Clone is called from CommonDBTM.php line 1266.

**Comment by cconard96** [comment]
This shouldn't be an issue in GLPI 11 since sanitization logic was completely redone.
The `Toolbox::addslashes_deep($value);` in 10.0.X was added to prevent issues on the DB side (#16690)

**Comment by cedric-anne** [comment]
Fixed by #18125.
