### ISSUE TITLE
It does not allow inserting address in entities

### ISSUE THREAD

**Issue by jorgecamargosdb** [glpi-project/glpi#1812]
Good afternoon.

Version 9.1.2 is not allowing the inclusion of address for the entities, presenting the message "The action you have requested is not allowed.". Attached image.
---------------------------
Information
Server
 
Operating system: Windows NT SDB_PROJETOS 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP 5.6.23 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype,
	curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash,
	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, session, standard, tokenizer, wddx, xml,
	xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="12M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2000M" 
Software: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23 (Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23 Server at localhost
	Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.1.13-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi_912
	Host info: localhost via TCP/IP
	
OKE:\Xamp\htdocs\glpi_912/config : OK
OKE:\Xamp\htdocs\glpi_912/files : OK
OKE:\Xamp\htdocs\glpi_912/files/_dumps : OK
OKE:\Xamp\htdocs\glpi_912/files/_sessions : OK
OKE:\Xamp\htdocs\glpi_912/files/_cron : OK
OKE:\Xamp\htdocs\glpi_912/files/_graphs : OK
OKE:\Xamp\htdocs\glpi_912/files/_lock : OK
OKE:\Xamp\htdocs\glpi_912/files/_plugins : OK
OKE:\Xamp\htdocs\glpi_912/files/_tmp : OK
OKE:\Xamp\htdocs\glpi_912/files/_rss : OK
OKE:\Xamp\htdocs\glpi_912/files/_uploads : OK
OKE:\Xamp\htdocs\glpi_912/files/_pictures : OK
OKE:\Xamp\htdocs\glpi_912/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.1.21 in (E:\Xamp\htdocs\glpi_912\lib\htmlawed)
phpCas version 1.3.4 in (E:\Xamp\htdocs\glpi_912\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (E:\Xamp\htdocs\glpi_912\vendor\phpmailer\phpmailer)
Zend Framework in (E:\Xamp\htdocs\glpi_912\vendor\zendframework\zend-loader\src)
zetacomponents/graph in (E:\Xamp\htdocs\glpi_912\vendor\zetacomponents\graph\src)
SimplePie version 1.4.1 in (E:\Xamp\htdocs\glpi_912\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (E:\Xamp\htdocs\glpi_912\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (E:\Xamp\htdocs\glpi_912\vendor\michelf\php-markdown\Michelf)
true/punycode in (E:\Xamp\htdocs\glpi_912\vendor\true\punycode\src)
iacaml/autolink in (E:\Xamp\htdocs\glpi_912\vendor\iamcal\lib_autolink)
sabre/vobject in (E:\Xamp\htdocs\glpi_912\vendor\sabre\vobject\lib)

SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 
Name: 'servicedeskbrasil.teste@gmail.com' Active: Yes
	Server: '{pop.gmail.com/pop/ssl/debug}' Login: 'servicedeskbrasil.teste@gmail.com' Password: Yes

Plugins list
 

[/code]
To copy/paste in your support request

![image](https://cloud.githubusercontent.com/assets/23311692/22890840/a962571e-f1f4-11e6-8e53-ccd0c57446c7.png)

**Comment by yllen** [comment]
I can't reproduce.
Wich field do you want to change?

**Comment by jorgecamargosdb** [comment]
@yllen 

The entity address
![image](https://cloud.githubusercontent.com/assets/23311692/23082484/bddff738-f540-11e6-88fb-7d178cbd7ba8.png)

**Comment by yllen** [comment]
I can change all fields in this tab without problem

**Comment by trasher** [comment]
This issue has already been reported (and fixed); see #1756
