### ISSUE TITLE
Characters error when receiving tickets from 0Auth with Microsoft Office365

### ISSUE THREAD

**Issue by truong-luong** [glpi-project/glpi#18127]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

Dear Everyone,

We have applied GLPI to our ticket system, It is great for this solution,
We have faced the following error:
- we use Microsoft 365 email to receive tickets from the client,
- When the client sends a request via email, the system cannot read the font, and it leads to font errors like the picture,
- Other languages are fine, except Korean.

Example sent from Korean:
![wrong](https://github.com/user-attachments/assets/b2fd5034-ca08-4999-a669-8b33100dfa8c)

¾È³çÇÏ¼¼¿ä

ÀÌ½ºÆ®½ÃÅ¥¸®Æ¼ÀÔ´Ï´Ù.

À¯¼±»ó ¿äÃ»ÇÏ½Å ASM ¹æÈ­º® Á¤º¸ Àü´Þ µå¸³´Ï´Ù.

Ã·ºÎµÈ ¹®¼­ Âü°í ºÎÅ¹ µå¸³´Ï´Ù.

±âÅ¸ ¹®ÀÇ»çÇ× ÀÖÀ¸½Ã¸é È¸½Å ¹Ù¶ø´Ï´Ù.

°¨»çÇÕ´Ï´Ù.

Has anyone encountered this situation, and has any ideas to handle it.

Any comments are highly appreciated.

Thank you very much.

### Steps To reproduce

1. Connect receiver office365 mailbox with 0Auth to GLPI
2. Setup automatic mailgate to retrieve the new emails as tickets
3. Send email with Korean characters to this mailbox
4. The new ticket is created, but wrong character.

**Comment by cedric-anne** [comment]
Hi,

Could you attach here the corresponding email source in `.eml` format? It would help us to reproduce and investigate on the issue.

**Comment by truong-luong** [comment]
Dear @cedric-anne

This is my file for example,
![image](https://github.com/user-attachments/assets/f7004dd6-2398-46a7-aebe-ff903b7b641e)

Sorry, git doesn't allow .eml files, so I compressed it into a zip file.
Thanks for checking.

[다리는 계절입니다. 따뜻한 날씨와 함께 바다에서 수영하거나 산으로 여행을 떠날 수 있습니다. 또한 친구들과 바비큐 파티를 뜻한 날씨와 .zip](https://github.com/user-attachments/files/17486539/default.zip)

**Comment by trasher** [comment]
It looks like a kind of known problem with `ks_c_5601-1987` and `ks_c_5601-1989` used by Microsoft products. Current GLPI version throw a warning on encoding conversion.
I've tried to add your email to our test suite so I can test fixes; but until now I got no results.

**Comment by trasher** [comment]
I have a fix proposal, see #18142

Only mail content can be fixed. Subject is another issue; I did not yet found any solution to get it fixed.

**Comment by truong-luong** [comment]
> I have a fix proposal, see #18142
> 
> Only mail content can be fixed. Subject is another issue; I did not yet found any solution to get it fixed.

Dear Support Team,

It's works well except for the Title but that's fine.

Warm thanks.
