### ISSUE TITLE
Add edit option to personal view in My Settings > Personal view

### ISSUE THREAD

**Issue by KMalone42** [glpi-project/glpi#18133]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

If a user creates a personal view that throws an error for whatever reason, in this case I added a plugin field to the view, they will be unable to edit the view without deleting it entirely since this button only appears in the section of a page not rendered when error is thrown. 
Error
![PersonalViewBug1](https://github.com/user-attachments/assets/8b94a0e9-9e5d-43bb-b08d-a4a16c61da45)
Expected Edit button on this page, only option available is to delete view.
![PersonalViewBug2](https://github.com/user-attachments/assets/375286a2-676b-4a7d-8626-d61c518ff9bd)

### Page URL

https://helpdesk.com/front/preference.php

### Steps To reproduce

1. Create personal view that throws an error (in this case using a plugin field) 
2. realize your only option is to delete the view

**Comment by cconard96** [comment]
This shouldn't be an issue with GLPI 11. Several changes were made to make searches more resilient.
For changing/deleting personal views, you can already. Click top-right user menu > My settings > Personal view tab.
