### ISSUE TITLE
Line breaks in ticket description

### ISSUE THREAD

**Issue by wagneral** [glpi-project/glpi#1814]
Dear GLPI team,

after upgrading to the latest Version (9.2.1) we realized that editing the ticket description of an existing ticket (a ticket that was created in an earlier glpi version) leads to non existent line breaks: the line breaks are replaced by 'rn'. 

After saving the ticket, instead of showing
This is a
Test

the description shows
This is arnTest

When I look into the database, it's a similar behaviour: the 'rn's are also inserted in the 'content' field of an old ticket, whereas a new ticket entry shows real linebreaks.
id=1 -> old ticket (9.1)
id=2 -> new ticket (9.2.1)

mysql> select id, content from glpi_tickets;
+----+-----------------------------------+
| id | content                           |
+----+-----------------------------------+
|  1 | TestrnErneuter TestrnDritter Test |
|  2 | Test
Test zwei
Test drei          |
+----+-----------------------------------+
2 rows in set (0.00 sec)

Seems not to be a real big deal, but perhaps you can check that.

Thanks in advance

**Comment by wagneral** [comment]
Just realized - If I insert a <br /> manually (instead of pushing the return key) line breaks are stored and shown correctly.

**Comment by wagneral** [comment]
Any news relating this issue? Can anyone confirm or disprove this behaviour?

**Comment by wagneral** [comment]
Ok, finally I found a useful workaround. I tried activating rich text for helpdesk actions - et voilà: line breaks breaking well ;)

Simply configure in glpi webinterface:
Setup >> General >> All >> Assistance
_Use rich text for helpdesk_ YES

**Comment by sebma** [comment]
> Ok, finally I found a useful workaround. I tried activating rich text for helpdesk actions - et voilà: line breaks breaking well ;)
> 
> Simply configure in glpi webinterface: Setup >> General >> All >> Assistance _Use rich text for helpdesk_ YES

Hi, Cannot find "use rich text" option in GLPI v11.

**Comment by wagneral** [comment]
> > Ok, finally I found a useful workaround. I tried activating rich text for helpdesk actions - et voilà: line breaks breaking well ;)
> > Simply configure in glpi webinterface: Setup >> General >> All >> Assistance _Use rich text for helpdesk_ YES
> 
> Hi, Cannot find "use rich text" option in GLPI v11.

Hey, I am sorry but as you can see this request has been created many years ago. We do not use GLPI any longer, so unfortunately I can't help navigating through version 11. Maybe you can check the official documentation or contact the support.
