### ISSUE TITLE
Problem with ticket templates and type

### ISSUE THREAD

**Issue by virtazp** [glpi-project/glpi#18148]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

10.0.16

### Bug description

On GLPI, I have entities. On one of my entities, I have a pre-filled input template. When I change the type (From incident to request) when creating a ticket, the site crashes ((failure)net::ERR_HTTP2_PROTOCOL_ERROR)

### Relevant log output

```shell
No significant error in logs when error occurs
```

### Steps To reproduce

1. Create an entity
2. Create a ticket template for the description field
3. Create a ticket (Simplified or standard interface) and change the type (From Incident to Request)
4. Error

### Your GLPI setup information

<details><summary>Information about system installation and configuration</summary><pre>GLPI 10.0.16 ( => /var/www/xxxxxxxxxx)
Installation mode: TARBALL
Current language:en_GB

</pre></details><details><summary>Server</summary><pre> 
Operating system: Linux SMD11-DSI-DMZ 5.10.0-27-amd64 #​1 SMP Debian 5.10.205-2 (2023-12-31) x86_64
PHP 8.2.21 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bz2, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, random, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" disable_functions="" 
Software: nginx/1.18.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Server Software: Debian 11
	Server Version: 10.5.23-MariaDB-0+deb11u1
	Server SQL Mode: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxxxxxx@localhost/xxxxxxx
	Host info: Localhost via UNIX socket
	
PHP version (8.2.21) is supported.
Sessions configuration is OK.
Allocated memory is sufficient.
mysqli extension is installed.
Following extensions are installed: dom, fileinfo, filter, libxml, json, simplexml, xmlreader, xmlwriter.
curl extension is installed.
gd extension is installed.
intl extension is installed.
zlib extension is installed.
The constant SODIUM_CRYPTO_AEAD_XCHACHA20POLY1305_IETF_NPUBBYTES is present.
Database engine version (10.5.23) is supported.
No files from previous GLPI version detected.
The log file has been created successfully.
Write access to /var/www/xxxxxxxxxx/files/_cache has been validated.
Write access to /var/www/xxxxxxxxxx/files/_cron has been validated.
Write access to /var/www/xxxxxxxxxx/files has been validated.
Write access to /var/www/xxxxxxxxxx/files/_dumps has been validated.
Write access to /var/www/xxxxxxxxxx/files/_graphs has been validated.
Write access to /var/www/xxxxxxxxxx/files/_lock has been validated.
Write access to /var/www/xxxxxxxxxx/files/_pictures has been validated.
Write access to /var/www/xxxxxxxxxx/files/_plugins has been validated.
Write access to /var/www/xxxxxxxxxx/files/_rss has been validated.
Write access to /var/www/xxxxxxxxxx/files/_sessions has been validated.
Write access to /var/www/xxxxxxxxxx/files/_tmp has been validated.
Write access to /var/www/xxxxxxxxxx/files/_uploads has been validated.

Web server root directory configuration seems safe.
Sessions configuration is secured.
OS and PHP are relying on 64 bits integers.
exif extension is installed.
ldap extension is installed.
openssl extension is installed.
Following extensions are installed: bz2, Phar, zip.
Zend OPcache extension is installed.
Following extensions are installed: ctype, iconv, mbstring, sodium.
Write access to /var/www/xxxxxxxxxx/marketplace has been validated.
Timezones seems loaded in database.

</pre></details><details><summary>GLPI constants</summary><pre> 
GLPI_ROOT: "/var/www/xxxxxxxxxx"
GLPI_CONFIG_DIR: "/var/www/xxxxxxxxxx/config"
GLPI_VAR_DIR: "/var/www/xxxxxxxxxx/files"
GLPI_MARKETPLACE_DIR: "/var/www/xxxxxxxxxx/marketplace"
GLPI_USE_CSRF_CHECK: "1"
GLPI_CSRF_EXPIRES: "7200"
GLPI_CSRF_MAX_TOKENS: "100"
GLPI_USE_IDOR_CHECK: "1"
GLPI_IDOR_EXPIRES: "7200"
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: false
GLPI_SERVERSIDE_URL_ALLOWLIST: ["/^(https?|feed):\\/\\/[^@:]+(\\/.*)?$/"]
GLPI_TELEMETRY_URI: "https://telemetry.glpi-project.org"
GLPI_INSTALL_MODE: "TARBALL"
GLPI_NETWORK_MAIL: "glpi@teclib.com"
GLPI_NETWORK_SERVICES: "https://services.glpi-network.com"
GLPI_MARKETPLACE_ALLOW_OVERRIDE: true
GLPI_MARKETPLACE_MANUAL_DOWNLOADS: true
GLPI_USER_AGENT_EXTRA_COMMENTS: ""
GLPI_DISABLE_ONLY_FULL_GROUP_BY_SQL_MODE: "1"
GLPI_AJAX_DASHBOARD: "1"
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: "0"
GLPI_CENTRAL_WARNINGS: "1"
GLPI_TEXT_MAXSIZE: "4000"
GLPI_DOC_DIR: "/var/www/xxxxxxxxxx/files"
GLPI_CACHE_DIR: "/var/www/xxxxxxxxxx/files/_cache"
GLPI_CRON_DIR: "/var/www/xxxxxxxxxx/files/_cron"
GLPI_DUMP_DIR: "/var/www/xxxxxxxxxx/files/_dumps"
GLPI_GRAPH_DIR: "/var/www/xxxxxxxxxx/files/_graphs"
GLPI_LOCAL_I18N_DIR: "/var/www/xxxxxxxxxx/files/_locales"
GLPI_LOCK_DIR: "/var/www/xxxxxxxxxx/files/_lock"
GLPI_LOG_DIR: "/var/www/xxxxxxxxxx/files/_log"
GLPI_PICTURE_DIR: "/var/www/xxxxxxxxxx/files/_pictures"
GLPI_PLUGIN_DOC_DIR: "/var/www/xxxxxxxxxx/files/_plugins"
GLPI_RSS_DIR: "/var/www/xxxxxxxxxx/files/_rss"
GLPI_SESSION_DIR: "/var/www/xxxxxxxxxx/files/_sessions"
GLPI_TMP_DIR: "/var/www/xxxxxxxxxx/files/_tmp"
GLPI_UPLOAD_DIR: "/var/www/xxxxxxxxxx/files/_uploads"
GLPI_INVENTORY_DIR: "/var/www/xxxxxxxxxx/files/_inventories"
GLPI_NETWORK_REGISTRATION_API_URL: "https://services.glpi-network.com/api/registration/"
GLPI_MARKETPLACE_PLUGINS_API_URI: "https://services.glpi-network.com/api/marketplace/"
GLPI_I18N_DIR: "/var/www/xxxxxxxxxx/locales"
GLPI_VERSION: "10.0.16"
GLPI_SCHEMA_VERSION: "10.0.16@b13256c443dd4fdb27b4a0d3b8fea8caba4dfaa9"
GLPI_MARKETPLACE_PRERELEASES: false
GLPI_MIN_PHP: "7.4.0"
GLPI_MAX_PHP: "8.4.0"
GLPI_YEAR: "2024"

</pre></details><details><summary>Libraries</summary><pre> 
htmlawed/htmlawed version 1.2.14 in (/var/www/xxxxxxxxxx/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.8.0 in (/var/www/xxxxxxxxxx/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.8 in (/var/www/xxxxxxxxxx/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.7.5 in (/var/www/xxxxxxxxxx/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/xxxxxxxxxx/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/xxxxxxxxxx/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/xxxxxxxxxx/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/xxxxxxxxxx/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/xxxxxxxxxx/vendor/sabre/http/lib)
sabre/uri in (/var/www/xxxxxxxxxx/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/xxxxxxxxxx/vendor/sabre/vobject/lib)
laminas/laminas-i18n in (/var/www/xxxxxxxxxx/vendor/laminas/laminas-i18n/src)
laminas/laminas-servicemanager in (/var/www/xxxxxxxxxx/vendor/laminas/laminas-servicemanager/src)
monolog/monolog in (/var/www/xxxxxxxxxx/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/xxxxxxxxxx/vendor/sebastian/diff/src)
donatj/phpuseragentparser in (/var/www/xxxxxxxxxx/vendor/donatj/phpuseragentparser/src/UserAgent)
elvanto/litemoji in (/var/www/xxxxxxxxxx/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/xxxxxxxxxx/vendor/symfony/console)
scssphp/scssphp in (/var/www/xxxxxxxxxx/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/xxxxxxxxxx/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/xxxxxxxxxx/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/xxxxxxxxxx/vendor/rlanvin/php-rrule/src)
ramsey/uuid in (/var/www/xxxxxxxxxx/vendor/ramsey/uuid/src)
psr/log in (/var/www/xxxxxxxxxx/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/xxxxxxxxxx/vendor/psr/simple-cache/src)
psr/cache in (/var/www/xxxxxxxxxx/vendor/psr/cache/src)
league/csv in (/var/www/xxxxxxxxxx/vendor/league/csv/src)
mexitek/phpcolors in (/var/www/xxxxxxxxxx/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/xxxxxxxxxx/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/xxxxxxxxxx/vendor/guzzlehttp/psr7/src)
glpi-project/inventory_format in (/var/www/xxxxxxxxxx/vendor/glpi-project/inventory_format/lib/php)
wapmorgan/unified-archive in (/var/www/xxxxxxxxxx/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/xxxxxxxxxx/vendor/paragonie/sodium_compat/src)
symfony/cache in (/var/www/xxxxxxxxxx/vendor/symfony/cache)
html2text/html2text in (/var/www/xxxxxxxxxx/vendor/html2text/html2text/src)
symfony/css-selector in (/var/www/xxxxxxxxxx/vendor/symfony/css-selector)
symfony/dom-crawler in (/var/www/xxxxxxxxxx/vendor/symfony/dom-crawler)
twig/twig in (/var/www/xxxxxxxxxx/vendor/twig/twig/src)
twig/string-extra in (/var/www/xxxxxxxxxx/vendor/twig/string-extra)
symfony/polyfill-ctype not found
symfony/polyfill-iconv not found
symfony/polyfill-mbstring not found
symfony/polyfill-php80 not found
symfony/polyfill-php81 not found
symfony/polyfill-php82 in (/var/www/xxxxxxxxxx/vendor/symfony/polyfill-php82)
league/oauth2-client in (/var/www/xxxxxxxxxx/vendor/league/oauth2-client/src/Provider)
league/oauth2-google in (/var/www/xxxxxxxxxx/vendor/league/oauth2-google/src/Provider)
thenetworg/oauth2-azure in (/var/www/xxxxxxxxxx/vendor/thenetworg/oauth2-azure/src/Provider)

</pre></details><details><summary>SQL replicas</summary><pre> 
Not active

</pre></details><details><summary>Notifications</summary><pre> 
Way of sending emails: SMTP+TLS (xxxxxxxxxx@mail.xxxxxxxxxx)

</pre></details><details><summary>Plugins list</summary><pre> 
	singlesignon         Name: Authentification unique        Version: 1.3.3      State: Enabled                                 
		Install Method: Manual
	fields               Name: Champs supplémentaires         Version: 1.21.15    State: Enabled                                 
		Install Method: Marketplace

</pre></details>

### Anything else?

No errors in server logs

**Comment by cconard96** [comment]
Try clearing cache and/or using a different browser.

**Comment by virtazp** [comment]
I forgot to mention that I tested on all browsers and I have the same problem!
However, I solved it by adding 2 directives to my nginx server site configuration file:
http2_max_field_size 16k;
http2_max_header_size 32k;

I added this in my server block. The requests are greedy lol
