### ISSUE TITLE
Crash on adding a computer device

### ISSUE THREAD

**Issue by pruje** [glpi-project/glpi#1816]
Hi
There is a crash when adding a device to a computer:
1. Click on an existing computer
2. Go on the Device tab (Composants in French)
3. Cick on the "Add" button
4. Getting a blank page with: "Security die. trying to load an forbidden class name"

I'm using Glpi 9.1.2 (fresh install) with user glpi (super-admin).
Thanks

**Comment by trasher** [comment]
I can only reproduce when no device type has been selected; you have to select component type before clicking add button.

**Comment by pruje** [comment]
@trasher Yes after a while I understood it, but it would be better if this crash was fixed, with a warning message for the user.

**Comment by trasher** [comment]
Yes, I agree; a warning message should be displayed, or the add button should be disabled when no type has been selected :)
