### ISSUE TITLE
No button to add a new license

### ISSUE THREAD

**Issue by pruje** [glpi-project/glpi#1817]
Hi
I cannot add a new license because the button to save is missing.
Step to reproduce:
1. Create a software
2. Go on licenses page and click on the + to add a new one
3. There is no button to submit the form!

Edit: using Glpi 9.1.2 (fresh install) with the glpi super-admin user.

Thanks

**Comment by wawax** [comment]
Hello,

Please provide the version of GLPI you're using.
Do you have the right to create a license in your profile ?

**Comment by pruje** [comment]
Sorry I forgot it.
I'm using Glpi 9.1.2 (fresh install) using the glpi super-admin user.

**Comment by trasher** [comment]
I cannot reproduce on current 9.1/bugfixes. Please try with this one to see if that solve your issue.

Feel free to reopen if issue is still valid.

**Comment by michelmzs** [comment]
@trasher Same behavior here and on [Demo-GLPI](https://demo.glpi-project.org/). Licenses of a License cannot be added, no add button.
