### ISSUE TITLE
404 errors on debug endpoint should not spam the error log

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#18181]
404 responses are returned from `ajax/debug.php` any time the debug toolbar tries requesting debug data for a request that didn't have any. This is **normal** in most cases and the debug toolbar even lets users try to re-request the data. Previously, the 404 response would be returned on its own, but recently things changed so that full exceptions are being thrown instead.

**Comment by trasher** [comment]
Duplicate of https://github.com/glpi-project/glpi/issues/18165?

**Comment by cconard96** [comment]
Oops. Yes. I didn't pay enough attention to my GitHub notifications today,
