### ISSUE TITLE
wrong definition of table glpi_notimportedemails after installation

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1819]
All tables in GLPI have a collation set in the schema definition.

However since 2010, glpi_notimportedemails use CHASET=Latin1

https://github.com/glpi-project/glpi/blob/master/install/mysql/glpi-9.2-empty.sql#L5203

see this old commit https://github.com/glpi-project/glpi/commit/b4dc2d49ef75cd13db1a325e2d26e6528f3d2a4e#diff-96fa2724176a28afb94d7972df7ec50dR2368

**Comment by cedric-anne** [comment]
This has been fixed on master branch.
