### ISSUE TITLE
GLPI 11 - Not Selected DB

### ISSUE THREAD

**Issue by ojauumdev** [glpi-project/glpi#18204]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

11

### Bug description

Ao tentar instalar o GLPI 11 não me permite prosseguir na hora que seleciono o banco de dados.

version: '3.9'
services:
  glpi_app:
    image: sdbrasil/glpi:11.0-alpha
    container_name: glpi_app
    volumes:
      - glpi_config:/etc/glpi
      - glpi_documents:/var/lib/glpi/files/data-documents
      - glpi_plugins:/usr/share/glpi/plugins
      - glpi_marketplace:/usr/share/glpi/marketplace
      - glpi_files_plugins:/var/lib/glpi/files/_plugins
      - glpi_backup:/backup
    networks:
      - glpi
    ports:
      - "8080:80"

  glpidb:
    image: mariadb:10.5  # Alterado para MariaDB versão 10.5
    container_name: glpi_db
    networks:
      - glpi
    volumes:
      - glpi_db_log:/var/log/mysql
      - glpi_db_lib:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ADM@MySQL_GLP1
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=GLP1_MySQL@10
      - TZ=America/Sao_Paulo

networks:
  glpi:
    driver: bridge

volumes:
  glpi_config:
  glpi_documents:
  glpi_plugins:
  glpi_marketplace:
  glpi_files_plugins:
  glpi_backup:
  glpi_db_log:
  glpi_db_lib:

Informa: Impossível gravar o arquivo de configurações do banco de dados

**Comment by trasher** [comment]
Please write in englsih.

**Comment by cedric-anne** [comment]
It has been fixed by #18255.
