### ISSUE TITLE
Missing variable

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#18220]
`$occurence_date` does not exists

https://github.com/glpi-project/glpi/blob/main/src/CommonITILRecurrent.php#L471

**Comment by trasher** [comment]
I've trid to fix, but fail, see #18219

**Comment by AdrienClairembault** [comment]
It does exist because the first iteration of the loop will not enter this condition since `tmp_search_time` will be null.

(I do agree that this code is badly structured though, it could be simplified)

**Comment by trasher** [comment]
OK, I totally misunderstood the code.

**Comment by AdrienClairembault** [comment]
It can be simplified like this, but this part will always be hard to read without reworking the whole function :/

![Image](https://github.com/user-attachments/assets/4f5d0787-70f1-455c-9c40-8790c8585248)
