### ISSUE TITLE
Korean Character Error in Email Subject When Using Microsoft 365 Mailbox Receiver in GLPI

### ISSUE THREAD

**Issue by Duaka1** [glpi-project/glpi#18236]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.16

### Bug description

Dear Everyone,

My issue is exactly the same as #18127.

By following @Trasher's instructions, I resolved the Korean character issue in the email content.

However, I am currently encountering the Korean Character Error in the Subject.

**Details:**

- Set up the Microsoft 365 Mailbox Receiver in GLPI with OAuth.
- When the client sends an email request via Outlook, the GLPI system receives those emails with an error in the subject.
- If the client sends an email request with a short Korean subject (about 1-19 Korean characters), it works fine. If the subject is longer, an error occurs.
- Other languages are fine, except Korean.

**Example:**

Client sends an email request with:
- Subject "요청하신 자료를 보내드립니다" -> **Fine**
- Subject "요청하신 자료를 보내드립니다 요청하신 자료를 보내드립니다" -> **Error** (like image bellow)
![Image](https://github.com/user-attachments/assets/5b5a831a-f84e-464f-acef-8df42eafa639)

**Additional Information:**

- If the client sends an email request via Gmail, there are no issues.

Could you please let me know if there is a solution for this?

I am very grateful for any feedback you may provide.

### Steps To reproduce

1. Set up the Microsoft 365 Mailbox Receiver in GLPI with OAuth.
2. Set up the automatic mailgate to retrieve new emails as tickets.
3. Send an email with Korean characters via Outlook to this mailbox.
4. A new ticket is created, but the subject line displays incorrect characters

**Comment by cedric-anne** [comment]
@Duaka1 

What is your PHP version ?

**Comment by trasher** [comment]
As said in #18127, I did not find any solution. Header decoding relies on PHP native method `iconv_mime_decode`, that:
1- does not support `ks_c_5601-1987` encoding,
2- does not permit to tell what original encoding actually is.

Therefore I see no way to get that fixed.

**Comment by Duaka1** [comment]
> [@Duaka1](https://github.com/Duaka1)
> 
> What is your PHP version ?

Hi @cedric-anne, my PHP version is 8.3.6.

**Comment by Duaka1** [comment]
> As said in [#18127](https://github.com/glpi-project/glpi/issues/18127), I did not find any solution. Header decoding relies on PHP native method `iconv_mime_decode`, that: 1- does not support `ks_c_5601-1987` encoding, 2- does not permit to tell what original encoding actually is.
> 
> Therefore I see no way to get that fixed.

Sorry to hear that. Even so, thank you very much for your response.
I hope this issue will be resolved in the future.

**Comment by trasher** [comment]
If someone can provide me a possible way to fix, I'll be happy to do. Or maybe Outlook and co will one day change their charset to something more "standard"... :D

**Comment by cedric-anne** [comment]
@Duaka1 

We use the `laminas/mail` for now to handle emails reading. The subject decoding is made by the following method: https://github.com/laminas/laminas-mail/blob/75e02574979a58b123cf9cb19a0fbad7d5eebf21/src/Header/HeaderWrap.php#L130-L151

If the `imap` PHP extension  is not present on your system, you can try to install and activate it, it may fix your issue. But it would probably only be a temporary fix, as this extension is not really maintained and may not be available in future PHP versions, see https://php.watch/versions/8.4/imap-unbundled

**Comment by Duaka1** [comment]
> If someone can provide me a possible way to fix, I'll be happy to do. Or maybe Outlook and co will one day change their charset to something more "standard"... :D

Thank you for your dedication.
One more thing I forgot to mention: in the Outlook classic app, if I change encoding for outgoing messages from Western European (default) to Unicode (UTF-8), it works fine when sending an email with Korean characters to my GLPI mailbox. However, it's not ideal to ask each client to make this adjustment.


![Image](https://github.com/user-attachments/assets/e78c54e7-e1ce-4e39-8a98-6148eb1396e9)
![Image](https://github.com/user-attachments/assets/112b8838-8d43-43b9-96e2-85bbfd876e6b)

Does this information help?

**Comment by Duaka1** [comment]
> [@Duaka1](https://github.com/Duaka1)
> 
> We use the `laminas/mail` for now to handle emails reading. The subject decoding is made by the following method: https://github.com/laminas/laminas-mail/blob/75e02574979a58b123cf9cb19a0fbad7d5eebf21/src/Header/HeaderWrap.php#L130-L151
> 
> If the `imap` PHP extension is not present on your system, you can try to install and activate it, it may fix your issue. But it would probably only be a temporary fix, as this extension is not really maintained and may not be available in future PHP versions, see https://php.watch/versions/8.4/imap-unbundled

Many thanks for your suggestion. I don’t have expertise in PHP, but I’ll look into it.
Hope for your support in the future.
