### ISSUE TITLE
Ticket category no longer saved when at a lower level entity (normal interface)

### ISSUE THREAD

**Issue by tkuijs** [glpi-project/glpi#18240]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.0.17

### Bug description

We got most of our ITIL categories at the top level entity with recursive enabled, when creating a ticket to a lower level entity I can select the category options but after selecting the form auto submits and the category is empty again. It does work for the simplified interface.

### Relevant log output

Cannot find anything in the logs

### Page URL

/front/ticket.form.php

### Steps To reproduce

1. Set all ITIL categories at the top level with recursive on
2. Go to lower level and do not use the simplified interface
3. Create a new ticket and select a top level itil category
4. Form submits and category is empty

**Comment by tkuijs** [comment]
Thanks for the quick response! 🙏🏻

**Comment by alexmicontini** [comment]
Hi,

Does this error only affect the new version 10.0.17 or did it also affect 10.0.16? Is it safe to upgrade to 10.0.17?

best regards

**Comment by tdozbun-reno** [comment]
I'm on 10.0.17 and encountering this problem today.

**Comment by LucianaCabrera** [comment]
I also confirm that this error occurs

**Comment by Rom1-B** [comment]
Hello,

Here's the patch that addresses this issue: https://github.com/glpi-project/glpi/pull/18244

**Comment by wjqwh** [comment]
Yes, it is a bug, I met same issue.
