### ISSUE TITLE
Impossible to write the database setup file during Initialization of the database

### ISSUE THREAD

**Issue by joacoetche06** [glpi-project/glpi#18249]
When I am installing glpi 11 version I have this issue:
![Image](https://github.com/user-attachments/assets/5b2ca157-ccc3-460c-948f-117ba9958583)

I have this permission on Config folder:
drwxrwxrwx  2 www-data www-data  4096 nov  6 14:21 config

**Comment by ftoledo** [comment]
i have same issue.

**Comment by trasher** [comment]
Duplicates #https://github.com/glpi-project/glpi/issues/18153
