### ISSUE TITLE
GLPI PDF export does't show the number of items in the footer

### ISSUE THREAD

**Issue by tabad** [glpi-project/glpi#1826]
# The environment

  * Server Side
    * Red Hat Enterprise Linux Server release 7.3 (Maipo)
        * GLPI v9.1.2

# The issue

This is the footer of a GLPI PDF export report generated with GLPI 0.84.8

> GLPI PDF export - 2017-02-16 - 20 items - 1/1

This is the footer of a GLPI PDF export report generated with GLPI 9.1.2

> GLPI PDF export - 2017-02-16 - 1/3

This happens with *Current page in landscape PDF*, *Current page in portrait PDF*, *All pages in landscape PDF* and *All pages in portrait PDF*.

**Comment by trasher** [comment]
This seems to have been dropped or lost since version 0.85.
