### ISSUE TITLE
API KO since 10.0.17

### ISSUE THREAD

**Issue by SteadEXE** [glpi-project/glpi#18261]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

One of our partner can no longer fetch data from our GLPI instance since we upgraded to GLPI 10.0.17.
It raises an HTTP 500 error.

### Relevant log output

[2024-11-07 14:56:02] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "id" in E:\GLPI\src\User.php at line 736
  Backtrace :
  src\Api\API.php:1771                               User::unsetUndisclosedFields()
  src\Api\APIRest.php:214                            Glpi\Api\API->searchItems()
  apirest.php:57                                     Glpi\Api\APIRest->call()
  public\index.php:82                                require()

### Steps To reproduce

Try to fetch tickets from API.
If response contains tickets it raises an HTTP 500.
If no tickets are fetched, it returns an empty array.

_No response_

**Comment by cedric-anne** [comment]
Fixed by #18266.
