### ISSUE TITLE
i18n button translation "Resolve"

### ISSUE THREAD

**Issue by troloff** [glpi-project/glpi#18285]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

Just a wrong translation:

In ticket list / mass action / resolve selected tickets, German translation for button "Resolve"
 is wrong ("Some mandatory system requirements are missing"). Should be "Lösen" (or something suitable it was before)

OK: English
![Image](https://github.com/user-attachments/assets/3394fe53-d45b-45b5-aa95-ef32bb0d80a2)

Not OK: German
![Image](https://github.com/user-attachments/assets/88dcdbe3-cf8c-47d4-815a-9f25e11e0386)

### Relevant log output

```shell

```

**Comment by trasher** [comment]
Translations are doen on Transifex https://app.transifex.com/glpi/GLPI/dashboard/ it has to be fixed there.

**Comment by troloff** [comment]
Ok, I tried that ;-)
