### ISSUE TITLE
PHP Deprecated function (8192): strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/html/glpi/src/Calendar.php at line 244

### ISSUE THREAD

**Issue by danielmbicalho** [glpi-project/glpi#18283]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

Some itil categories are presenting errors on create or solve the tickets. 

### Relevant log output

```shell
[2024-11-11 10:32:35] glpiphplog.NOTICE:   *** PHP Deprecated function (8192): strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/html/glpi/src/Calendar.php at line 244
  Backtrace :
  src/Calendar.php:244                               strtotime()
  src/Calendar.php:544                               Calendar->isHoliday()
  src/LevelAgreement.php:843                         Calendar->computeEndDate()
  src/CommonITILObject.php:2375                      LevelAgreement->computeDate()
  src/Ticket.php:1615                                CommonITILObject->pre_updateInDB()
  src/CommonDBTM.php:1700                            Ticket->pre_updateInDB()
  front/ticket.form.php:90                           CommonDBTM->update()
  public/index.php:82                                require()
```

### Page URL

/front/ticket.form.php?id=52285

### Steps To reproduce

1. Open the ticket
2. Change the situation to Solved
3. Click the save button
4. the glpi process and crash
5. on debug mod, shows the message: 
```
PHP Deprecated function (8192): strtotime(): Passing null to parameter #1 ($datetime) of type string is deprecated in /var/www/html/glpi/src/Calendar.php at line 244
```

**Comment by trasher** [comment]
This means there is a "calendar holiday" entry in your database that does not have an end date; I wonder if that should really happens (even if it seems to be currently permitted).
As a workaround, adding an end date should do the trick.

**Comment by trasher** [comment]
BTW, I've just tested, and that does not seems a legit case: when creating a holiday, if you do not give an end date, it's set to start date automatically.

**Comment by danielmbicalho** [comment]
Ok.I Understood the problem. Thanks for orientation
