### ISSUE TITLE
Permanently delete buttons are not displayed

### ISSUE THREAD

**Issue by verdanatech-marcio** [glpi-project/glpi#18281]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

After updating GLPi, the validation by type of the variable was changed and it comes with an empty string instead of an int and it does not work. The button does not appear in any tab.
![Image](https://github.com/user-attachments/assets/8f5315d0-ed94-4425-ab2c-b09d3ac61587)
After this change, the button appeared again.

### Relevant log output

```shell

```

**Comment by batcox85** [comment]
Thank's for sharing solution.

**Comment by trasher** [comment]
Be careful with that change, it can leads to security issues.

**Comment by trasher** [comment]
Also, please provide all requested information, and try without any plugin.

**Comment by cedric-anne** [comment]
Duplicates #18280.
