### ISSUE TITLE
Unable to select ticket category in 10.0.17, the field is reset when select a value

### ISSUE THREAD

**Issue by Gabilach** [glpi-project/glpi#18291]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

Hello,

After upgrade to 10.0.17 i find that when we create a ticket, select an entity and select a categorie, the field value is reset.

The problem not happend if we select root entity, i have reproduce the bug on a fresh install of GLPI.

 ![Image](https://github.com/user-attachments/assets/fb4c2979-801b-459c-b4b8-d330445faee7)

Regards

### Relevant log output

```shell
No log or error in log files
```

### Steps To reproduce

1. Create a Ticket
2. Select and entity
3. Select a category
4. Field value category is reset

### Your GLPI setup information

GLPI 10.0.17

**Comment by cedric-anne** [comment]
Duplicates #18240.
