### ISSUE TITLE
mail notification with image in mime (to avoid the "fishing" message in outlook)

### ISSUE THREAD

**Issue by etiquet** [glpi-project/glpi#1829]
Dear Community, we are facing a issue with email notification regarding inclusion of images within the html notification. 

(Image are included with an absolute path)
Currently the mail client (outlook) detect the image as a fishing attempt.

Considering two options : 
1/ is there any none recommendation to workaround this issue ?

2/ would the community consider the following enhancement request : add images as mime part within the mail body ?

Typically the algorithm could be : 
- scan the html body
- detect the tag image within the html 
=> built an array (only considering relative imagepath, absolute means don't touch )
and when creating the mail body add the image.

I found the following example on internet if someone as some time ressource to do-it : 
$mime = new Mail_mime($crlf);
$mime->addHTMLimage('mail_templates/img/bg.png', 'image/png');

In the html part of mail body:
<img src="mail_templates/img/bg.png"/>

A convention might be needed, where to put the image folder accessible to the scripts.

Free to echange this request.
with many thanks
Eric

**Comment by tomolimo** [comment]
Please http://glpi.userecho.com/ to post any new request/idea

**Comment by etiquet** [comment]
done.
