### ISSUE TITLE
Custom asset definitions add noticeable request performance hit

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#18304]
I've noticed that as I add more custom asset definitions for testing (or from running E2E tests locally), almost every request to a PHP script has gotten nearly 10x slower than what it is in 10.0/bugfixes. Currently, I have 70 asset definitions with a few custom fields in each. It isn't clear yet if the issue is the number of definitions, number of custom fields, specific capacities, or a combination of everything.

**Comment by cconard96** [comment]
Identified the `IsInventoriableCapacity` as the source of the performance hit. I only had a single asset definition with it enabled and it alone was adding 550ms to the response times.

**Comment by AdrienClairembault** [comment]
I confirm on my side too.

Without `IsInventoriableCapacity`:
![Image](https://github.com/user-attachments/assets/f0f5ddfc-dd31-4d9b-966e-facabe0217ef)

With one `IsInventoriableCapacity`:
![Image](https://github.com/user-attachments/assets/884a11f4-9da0-4a99-8b87-2ef1799b342a)
