### ISSUE TITLE
ITIL category not registered

### ISSUE THREAD

**Issue by Gaelolito** [glpi-project/glpi#18317]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

Since version update from 10.0.16 to 10.0.17 :
The choice of a category is removed when a ticket is registered on a sub-entity.
Registering a ticket on the root entity retains the choice of category.
Registering a ticket via the email collector, a form or a webservice retains the category, even if the ticket is registered on a sub-entity.
ITIL categories are set up on the root entity and the ‘sub-entity’ box is checked.
The default ticket template made the category mandatory: this has been temporarily removed to avoid blocking.
The Urgency and Impact drop-down lists retain the choice when saving on a sub-entity.
--------------------
Depuis MAJ de version 10.0.16 à 10.0.17 :
Le choix d'une catégorie est supprimé lors de l'enregistrement d'un ticket sur une sous-entité.
L'enregistrement d'un ticket sur l'entité racine conserve le choix de la catégorie.
L'enregistrement d'un ticket via le collecteur de email, un formulaire ou un webservice conserve la catégorie, même si le ticket est enregistré sur une sous-entité.
Les catégories ITIL sont paramétrées sur l'entité racine et la case "sous-entité" est bien cochée.
Le gabarit de ticket par défaut rendait la catégorie obligatoire : cela a été supprimé temporairement pour éviter le blocage.
Les listes déroulantes Urgence et Impact conservent bien le choix lors de l'enregistrement sur une sous-entité.

### Relevant log output

```shell

```

**Comment by trasher** [comment]
Seems this has already been reported; and has been fixed.
