### ISSUE TITLE
Monitors not showing in global search

### ISSUE THREAD

**Issue by meulie** [glpi-project/glpi#18322]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

When I use the global search and search for a location, the search results do not mention any Monitors assigned to this location.

I have three items (a computer, a peripheral, and a monitor) that all have location 135 assigned to them. However, when I do a global search for 135, only the computer and the peripheral show up.

It specifically states under 'Other searches with no item found' that it also checked Monitor.

### Relevant log output

```shell

```

### Steps To reproduce

* Assign a monitor to a location
* Do a global search for this location

**Comment by meulie** [comment]
I've gotten a bit closer. It applies to any part of the location-name.

However, when I go to Assets -> Monitors and add Location to the view, it becomes searchable as well.

So one can only find monitors in search if the Location-field is visible in the overview on Assets -> Monitors.
(perhaps this applies to other fields in other categories as well?)

Perhaps this is by design, but IMHO one should still be able to search on fields like Location, also if they're not displayed.

**Comment by trasher** [comment]
This is the way global search works, it uses per default displayed fields.
