### ISSUE TITLE
Wrong assignment of business rule for services

### ISSUE THREAD

**Issue by LucianaCabrera** [glpi-project/glpi#18351]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.15 - 10.0.17

### Bug description

It happens that we create an example rule where the criterion is that the title contains hello and with the action that is added to a specific project.
This works but is not displayed in the left tab panel of the created ticket. You have to go to the project that is in the rule and view this ticket assignment in the elements tab of that projects

In the history the action of the rule working is displayed:
![Image](https://github.com/user-attachments/assets/fe8f79df-f7d6-4367-b9bd-2ff63a65f5d1)
![Image](https://github.com/user-attachments/assets/879abad2-af47-46c6-b8d4-ced7dcdde70e)

Here we see that the ticket was perfectly assigned to the project, being located in the project, not in the ticket:
![Image](https://github.com/user-attachments/assets/aafe8d05-8821-459f-832a-8152604c3cf1)

### Relevant log output

```shell

```

### Steps To reproduce

1. Create a business rule for services with the action that it is assigned to a specific project
ej:
![Image](https://github.com/user-attachments/assets/1e1ca7d2-ce04-4b9e-8764-a9a926ab6343)
2. create a ticket that meets the criteria of that rule
3. Review the history to see that the project assignment action was carried out
4. Go to the project where the ticket should have been assigned.
5. go to items tab

**Comment by joacoetche06** [comment]
I have this issue too

**Comment by ftoledo** [comment]
It seems that the ticket is assigned as an inventory asset and not as an ITIL item

**Comment by cconard96** [comment]
Fixed by #18557. Will be fixed in 10.0.18.
