### ISSUE TITLE
AD LDAP Sync: username is case sensitive

### ISSUE THREAD

**Issue by gitpwc** [glpi-project/glpi#1837]
Configured GLPI (from version 0.8xx) to sync from my LDAP AD.
I use _userprincipalname_ attribute to publish GLPI's username

When moving user between OU, GLPI search the current username in directory and then update user's DN.
If the username casing has been changed, GLPI is unable to find the user.
Example:
userPrincipalName: John@domain.tld
samAccountName: DOMAIN\John
DN: CN=John, OU=test1, DC=domain, DC=tld

Then I move John in another OU but also change his userPrincipalName so the first letter is lowercase:
userPrincipalName: john@domain.tld
samAccountName: DOMAIN\John
DN: CN=John, OU=test2, DC=domain, DC=tld

In such example, GLPI won't find the user anymore.

**Comment by trasher** [comment]
As far as I can see; case sensitive or not is defined on the server side; I do not see anything related to that while searching.
Anyways, this is the same issue when the user login has been changed. We've added a "synchronisation field" (based on a field that should not change) to handle such cases, this will be available in 9.2 (see #2073 )

**Comment by gitpwc** [comment]
Thanks for reply.
Probably I was not clear.
Active Directory IS not case sensitive for username so John@domain.tld is the same as JOHN@DOMain.tld.

For GLPI the two fields are different while for an AD administrator casing has no influence.
BTW, if you use another field this will be automatically solved.
Could you please tell me which LDAP/AD field you will use? I looked at the #2073 but didn't understand how this field will work.
Thanks

**Comment by trasher** [comment]
OK, I see... We could lower case user entry, but since some server configurations may be case sensitive, it could be wrong on some cases :(

As for the synchronization field; you can use what you want. For AD, 9.2 will support objectguid field which seems to be a very good choice for such a feature :)
