### ISSUE TITLE
Unmanaged assets doesn't have Add button

### ISSUE THREAD

**Issue by boedyirh** [glpi-project/glpi#18398]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

GLPI 10.0.17

### Bug description

I found that in [GLPI 10.0.17] the Unmanaged assets doesnt have Add Button and Template Button. It only has Search and Lists button.
![Image](https://github.com/user-attachments/assets/25c22c8d-a5b8-4318-9205-fd3c0799f582)

### Relevant log output

```shell

```

### Page URL

http://localhost/glpi/front/unmanaged.php

**Comment by trasher** [comment]
Unamanged assets are only created from inventory process; that's intended.
