### ISSUE TITLE
[9.1.2] "from x to x of z" not translated in french 

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#1841]
in assets list or ticket list, at the top of the list   "from 1 to 30 of 35" is not translated in french

**Comment by ladenree76000** [comment]
![image sans titre](https://cloud.githubusercontent.com/assets/13557254/23220914/beeba03c-f923-11e6-82ea-bfe54983d85e.png)

**Comment by remicollet** [comment]
Feel free to fix it on Transifex ;)

See https://www.transifex.com/glpi/GLPI/

**Comment by ladenree76000** [comment]
done : i joined glpi team.
anyway "from" is allready translated. so i guess, this is not the cause.
i keep investigating.

**Comment by trasher** [comment]
Translations are updated at release time; if this is now translated; it will be available in the next release ;)

**Comment by ladenree76000** [comment]
in locales :  
#. TRANS: %1$d, %2$d, %3$d are page numbers
#: inc/html.class.php:3979 inc/html.class.php:4167
#, php-format
msgid "From %1$d to %2$d **on** %3$d"
msgstr "De %1$d à %2$d sur %3$d"

in html.class.php line 4008 
echo sprintf(__('From %1$d to %2$d **of** %3$d'), $current_start, $current_end, $numrows);


i think there's something wrong : of / on  (mistype) i don't think add new translation for From %1$d to %2$d **of** %3$d  is the best solution

**Comment by sebfun** [comment]
also missing in licence menu -> licence tab -> 
**Technician in charge of the license**	
 	Éditeur	
 
**Group in charge of the license**

**Comment by flegastelois** [comment]
Already fixed by https://github.com/glpi-project/glpi/issues/1354
