### ISSUE TITLE
ticket.form.php ITIL categories not applying after changing it

### ISSUE THREAD

**Issue by RaivoMahnovs** [glpi-project/glpi#18447]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

When trying to change category creating new ticket from ticket.form.php (Assistance/+ Create ticket), it is not saving, when entity differs, although entities are configured with sub-entities. 

![Image](https://github.com/user-attachments/assets/eb4522c1-18c0-4055-a9c3-53980527a09c)

![Image](https://github.com/user-attachments/assets/8207db4c-2d26-4869-bbef-52932503994c)

### Relevant log output

```shell
Nothing about this in log files.
```

### Page URL

../ticket.front.php

### Steps To reproduce

1. Assistance
2. Create ticket
3. Change Entity
4. Change to category which is in different sub-entity
5. See if the changes save, or disappear

### Your GLPI setup information

![Image](https://github.com/user-attachments/assets/9f9eac0f-a07e-4068-8f84-2e8878ad883d)

### Anything else?

In previous versions it worked fine with this configuration.

**Comment by cconard96** [comment]
Duplicates #18240

Please search open and closed issues before reporting bugs.
