### ISSUE TITLE
Rubrique documents

### ISSUE THREAD

**Issue by demonisto** [glpi-project/glpi#1845]
Bonjour,

Vous trouverez ci-joint une demande d'évolution si cela est réalisable avec 2 propositions.
La première serait la mieux mais je pense qu'elle va demander un gros travail.

[Affecter  une visibilité aux rubriques de documents.docx](https://github.com/glpi-project/glpi/files/787255/Affecter.une.visibilite.aux.rubriques.de.documents.docx)

Les imprimes écrans sont issues de GLPI 0.90.5.

Si besoin de plus d'explication ou détail je reste à disposition pour y répondre.

PS : J'ai du mal avec l'anglais donc je l'ai fait en français

**Comment by yllen** [comment]
Et un document sans rubrique ?
Parce que lorsque vous ajoutez un document à un ticket vous n'avez pas de choix de rubrique
ou lorsqu'un document arrive par mail vous n'avez pas de choix de rubrique non plus.
Et pour la FAQ qui ne nécessite pas ne connection pour la visibilité ?

Que ce soit la première ou la seconde solution, ce n'est pas aussi simple que vous le pensez car il faut revoir les droits de tous les objets de GLPI possédant un lien avec un document.
