### ISSUE TITLE
Error when editing Entities address GLPI 9.1.2

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#1846]
When I try to modify entities' addresses GLPI returns me with an error of no permission to do that task.
The great problem is that I have full access to all the modules of GLPI as super-admin.

GLPI version 9.1.2

Administration > Entities > Select an entity > Try to modify something on the Address tab.

![2017-02-20 12_44_48-glpi - access denied](https://cloud.githubusercontent.com/assets/13874922/23131865/6baf3ae2-f76a-11e6-80dd-5c9b38fac32a.png)

**Comment by carvanders** [comment]
Hello! Same problem here!

**Comment by trasher** [comment]
This issue has already been reported (and fixed); see #1756

**Comment by arthurrschaefer** [comment]
Sorry for the duplicate. And thanks for the answer.
