### ISSUE TITLE
GLPI Inventory - Error 403

### ISSUE THREAD

**Issue by Dennishid** [glpi-project/glpi#18475]
I updated my GLPI system from 9.x to 10.x sometime back and just recently realized that my GLPI Inventory system was not working anymore.  When I goto the inventory page (http://host/glpi/front/inventory.php) I get a Access to host is denied (HTTP Error 403.  Before the upgrade to version 10.x everything was working perfectly fine, but now it has quit.  I know based on my research it seems like it is a permissions issue, but I can't for the life of me figure out where the permissions issue is?

Thank-You to everyone in advance for you help in advance for your help,

**Comment by cedric-anne** [comment]
Go to `/front/inventory.conf.php` and verify that `Enable inventory` option is checked.
