### ISSUE TITLE
Components listed in RuleImportAsset view

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#18485]
Reported by @g-bougard on internal chat

![Image](https://github.com/user-attachments/assets/26af2c8f-bb9a-4310-994e-e9ea922c2f05)

This is not present in 10.0/bf.

So 2 possibilities:
- it's a bug
- it's a feature asked by a customer, and I forgot.

I'm more inclined toward the first, as I don't see any case where the direct inventory of Peripherals makes sense (In a computer import, yes)

**Comment by cconard96** [comment]
This rule collection has tabs for everything registered to `state_types`. When States genericity was added, device types were added to this array, `location_types` and `contract_types`.

**Comment by cedric-anne** [comment]
I remember having already noticed that it was weird to use the `state_types` here. I guess it is time to use a dedicated config.

**Comment by trasher** [comment]
Yes, the use of `state_types` is coming from the original plugin
