### ISSUE TITLE
REST API, Auth problem with CAS and user_token

### ISSUE THREAD

**Issue by moobyfr** [glpi-project/glpi#1849]
Using GLPI 9.1.2 with authentication set up for LDAP with CAS, I'm unable to do a `initSession` because the call contains a redirection to the CAS server.
I've tried with a LDAP user using CAS as auth and with a local user.

The problem is related to `api.class.php:169` where `noAuto` is set to `false`.
Keeping the value to `true` is a workaround

**Comment by xoryves** [comment]
The workaround does not work for 9.2.1.

I have to switch https://github.com/glpi-project/glpi/blob/9.2.1/inc/auth.class.php#L1101-L1108 with https://github.com/glpi-project/glpi/blob/9.2.1/inc/auth.class.php#L1110-L1113.

In master REST API calls with enabled CAS and user_token are still broken.

**Comment by moobyfr** [comment]
It's fixed with commit 428ca922ba2702b0b185a46b3fad0c133466dbac (9.4.1.1)
