### ISSUE TITLE
add cost on projects

### ISSUE THREAD

**Issue by gituncar** [glpi-project/glpi#185]
When add/edit cost on project, Jump to project task tab. It better if stay on cost or current tab when make update.
glpi 0.90
![image 3](https://cloud.githubusercontent.com/assets/7705197/10552598/8bba2fec-741a-11e5-8193-5b7d413ea8eb.png)
![image 4](https://cloud.githubusercontent.com/assets/7705197/10552599/8bbe72f0-741a-11e5-8610-2d2bee1bb84b.png)

**Comment by yllen** [comment]
I don't have this issue.
After creation of modification i stay on the cost tab.
What is the value of "Go to created item after creation" in your settings?

**Comment by orthagh** [comment]
Non answers since 13 days, i close
