### ISSUE TITLE
Update Zend-Cache to 2.7.2 and allow use APC and APCu

### ISSUE THREAD

**Issue by edgardmessias** [glpi-project/glpi#1850]
Update Zend-Cache to 2.7.2 and allow use APC and APCu.

Not need more "apcu-bc".

Update https://github.com/glpi-project/glpi/blob/master/inc/session.class.php#L579 to check APC and APCu.

Add APCu compatibility:
* https://github.com/glpi-project/glpi/blob/08716615d960ef214e120823e6218af4029168a4/front/config.form.php#L60
* https://github.com/glpi-project/glpi/blob/7126e64713b163b77ae233c7bbb1e44b244d35d3/inc/config.class.php#L1522

**Comment by remicollet** [comment]
Looking at zend-cache 2.7.2 code, still apc_* functions used
So apcu-bc still required.

**Comment by edgardmessias** [comment]
You can use:
```php
//for APC
$cache = Zend\Cache\StorageFactory::factory(array('adapter' => 'apc'));

//for APCu
$cache = Zend\Cache\StorageFactory::factory(array('adapter' => 'apcu'));
```

**Comment by remicollet** [comment]
Indeed, refresh issue in my IDE

**Comment by edgardmessias** [comment]
My suggestion:

```php
$adapter = function_exists('apcu_fetch') ? 'apcu' : 'apc';
$cache = Zend\Cache\StorageFactory::factory(array('adapter' => $adapter));
```

**Comment by remicollet** [comment]
done in PR #1855

**Comment by remicollet** [comment]
> My suggestion:

No value to keep 'apc', as no stable version exists for anything >= 5.4, so definitively better to use APCu

**Comment by edgardmessias** [comment]
And support for other types of caches?
Like Memcached, Redis, WinCache, XCache, ....

We can use interfaces to manager: https://zendframework.github.io/zend-cache/storage/adapter/#adapters

**Comment by remicollet** [comment]
I don't see any value to support network shared cache for translation. Local is always faster.

No idea about WinCache, don't even know what is this ;)
XCache is dead.
