### ISSUE TITLE
No Changing status when modify a task

### ISSUE THREAD

**Issue by sylvainclerc** [glpi-project/glpi#1852]
version : 9.1.2

Description : 
- Create a ticket
- Add a task with a description
- Modify the task with a change of the status of the ticket 

![screenshot2062](https://cloud.githubusercontent.com/assets/25950425/23204577/6b579f2a-f8e7-11e6-9f50-a2e0b0eeb293.jpg)
=> the status of the ticket hasn't changed because of the fields of the task hasn't been modified.

**Comment by tetageek** [comment]
Hi, i'have same bug, please correct this bug;
Thanks a lot.

**Comment by tetageek** [comment]
If we put a space or character in description field than save it's ok..

http://forum.glpi-project.org/viewtopic.php?id=157173
