### ISSUE TITLE
Change status menu not complete when adding task

### ISSUE THREAD

**Issue by sylvainclerc** [glpi-project/glpi#1853]
version : 9.1.2

Description : 
- in preferences : layout in vsplit mode
- when adding a task on a new ticket, the dropdown menu status isn't fully display 

![screenshot2063](https://cloud.githubusercontent.com/assets/25950425/23205057/dbb70958-f8e8-11e6-83b5-64d2117cac18.jpg)

**Comment by trasher** [comment]
Which browser are you using? I cannot reproduce on firefox nor chromium.

**Comment by trasher** [comment]
Please also specify wich colour palette is used; as it may be related (you do not seems to use the default one).

**Comment by sylvainclerc** [comment]
Hello,

This bug can be reproduced with Firefox 52 and Internet Explorer 11.

You must have a ticket without any associated item (followup, tasks, documents, etc ...) : in this case, the element "<div class="timeline_box">" has a small height and can't show the element "<ul class="x-button-drop-menu">" entirely.

You must be in vertical split mode (no problem with classic view or tabs on left).

I've reproduced this bug with differents colours templates (classic, teclib, dark).

I've tested this behavior on http://demo.glpi-project.org and it also appears.

**Comment by trasher** [comment]
I cannot reproduce :/ On the demo website with firefox; I got:
![tasks](https://cloud.githubusercontent.com/assets/224733/24601768/7c781036-185a-11e7-8788-2510899cd614.png)

**Comment by sylvainclerc** [comment]
![screenshot2171](https://cloud.githubusercontent.com/assets/25950425/24601987/4d650ae6-185b-11e7-8e50-d23da3af040a.jpg)
![screenshot2172](https://cloud.githubusercontent.com/assets/25950425/24601995/51f09238-185b-11e7-895f-f7bc45eeb2b2.jpg)
![screenshot2170](https://cloud.githubusercontent.com/assets/25950425/24602059/7d1c5ef6-185b-11e7-9c58-89adaf2dd7d6.jpg)

I'm on ticket 32208 in vertical split mode.
With a large resolution, no problem, I've the timeline on the right and
I reduce the size of my firefox window to have the timeline under the ticket's informations and the problem appears.

**Comment by trasher** [comment]
Oh! OK, I got it... DId not think to try with a smaller resolution :)

**Comment by trasher** [comment]
Could you please test the change proposed in https://github.com/trasher/glpi/commit/9f7e190517bf8162275f306dcf38ad86e228680b?

I'm not sure it will not break anything else :/
