### ISSUE TITLE
CLI notifications are no longer working at all

### ISSUE THREAD

**Issue by Gor3pig** [glpi-project/glpi#18556]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

Hello,

Without making any changes apart from updating to version 10.0.17, the notifications suddenly stopped working.

I checked the crontab configuration on my Debian (both as root and as the www-data user), and I also tried manually executing the cron.php file directly from Linux.

The PHP script works; however, no notifications are received. Ever.

However, if I go through the automatic actions configuration and click "Execute" in "queuednotification," the notifications work, and everyone receives the emails.

The crontab logs indicate that crontab is working properly and is correctly calling the cron.php script in the correct GLPI path.

On the other hand, I noticed that I get this error message when I run the crontab command manually :

`/usr/bin/php /var/www/glpi/front/cron.php`

**_Uncaught Exception Error: Call to undefined function mysqli_report() in /var/www/glpi/src/DBmysql.php at line 226_**

Anyone else in this situation?

![Image](https://github.com/user-attachments/assets/a561fcd0-b730-4a92-a9c6-89961b7e3a36)

### Relevant log output

```shell

```

**Comment by cedric-anne** [comment]
> Uncaught Exception Error: Call to undefined function mysqli_report() in /var/www/glpi/src/DBmysql.php at line 226

In the CLI context, the `mysqli` extension is not loaded. You have to fix your PHP configuration.
