### ISSUE TITLE
phpunit `WebhookTest` causes several "risky tests"

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#18563]
The `WebhookTest` causes several "risky tests":
```
1) tests\units\WebhookTest::testGetWebhookBody
Test code or tested code closed output buffers other than its own
```

I'm not sure what the problem is exactly (and I do not really want to spend time on that). If that can cause issues with phpunit, I'll revert this one.

_Originally posted by @trasher in https://github.com/glpi-project/glpi/issues/18561#issuecomment-2548169903_

**Comment by cconard96** [comment]
Fixed by #18569
