### ISSUE TITLE
ticket Absolute solving Time

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1857]
Please is it possible to add in ticket column view :+1: 

actually we do it in excel, but I think it should be usefull for kpi to add it in GLPI

Column A is business holidays
("18:00"-"08:00") is support hours calculate automatically working days monday to friday

=(NETWORKDAYS(C2;D2;A$2:A$10)-1)*("18:00"-"08:00")+IF(NETWORKDAYS(D2;D2;A$2:A$10);MEDIAN(MOD(D2;1);"18:00";"08:00");"18:00")-MEDIAN(NETWORKDAYS(C2;C2;A$2:A$10)*MOD(C2;1);"18:00";"08:00")

![image](https://cloud.githubusercontent.com/assets/15144026/23253457/e4c3e09e-f9b4-11e6-86f4-96816bf06fe0.png)

Absolute solving Time

formula :
solving date time - Opening date time - waiting time (pending)

taking into account business holidays and support hours.

Thanks for your help

**Comment by flegastelois** [comment]
Hi, it's already possible with "Time ranges" / "Close times" features in a GLPI "Calendar".
I don't understand what you need more.

**Comment by satyan01** [comment]
I think that you have not understand my need.

We would like to have a column in ticket view with time passed on the ticket from opening time to solved time only with support hours.

example a ticket is opened at 17h55 and solved day after at 8h05

absolute time is 10 minutes.

**Comment by flegastelois** [comment]
Hi, I have understood your need, which is already covered by GLPI.

You must use "Calendar" feature (attached to Entity of Ticket) before the ticket was Solved or Closed.

Then you have the following columns available in the ticket list : 

![image](https://cloud.githubusercontent.com/assets/470612/23353775/74caecca-fcce-11e6-9ef4-8bc51f3b2db5.png)


**Example** : 
* My calendar attached to the entity corresponding for my ticket : 
  * Configuration : Monday-Friday (08:00 to 18:00 each day)
  * 10 hours per FULL business-work-day ==> 36000 seconds

* My ticket : 
  * Opening date : Monday 16-01-2017 16:59
  * Resolution date : Friday 10-02-2017 10:56

* Statistics displayed by GLPI : 
  * Waiting time : 5 days 20 hours 54 minutes ==> 507240 seconds
  * Resolution time : 1 days 19 hours 3 minutes ==> 154980 seconds

![image](https://cloud.githubusercontent.com/assets/470612/23353494/154b7b8a-fccd-11e6-91a2-ad6f8cdd9ac6.png)

* Explanation : 
  * Monday 16-01-2017 16:59 **TO** Monday 16-01-2017 18:00 => 3660 seconds
  * Tuesday 17-01-2017 **TO** Thursday 09-02-2017 => 18 FULL business-work-days => 648000 seconds
  * Friday 10-02-2017 08:00 **TO** Friday 10-02-2017 10:56 => 10560 seconds
  * Total seconds for resolution (regardless of the waiting time) : 662220 seconds
  * Total seconds for resolution (without the waiting time) : 154980 seconds
    * **Converted time in the display by GLPI** : 154980 seconds => 2583 minutes => 43 hours 3 minutes => 1 days 19 hours 3 minutes

Can you explain to me what I did not understand in your need ?

Regards,

**Comment by flegastelois** [comment]
Thank you ?
