### ISSUE TITLE
opcache fail xampp

### ISSUE THREAD

**Issue by maravento** [glpi-project/glpi#18582]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

10.0.17

### Bug description

GLPI requires as a prerequisite to activate the [Zend OPcache extension: enhance PHP engine performances](https://glpi-install.readthedocs.io/en/latest/prerequisites.html#configuration:~:text=using%20SSL/TLS%3B-,Zend%20OPcache,-%3A%20enhance%20PHP%20engine).

For Xampp
`zend_extension=opcache`

For UniServerZero
`zend_extension=\${US_ROOTF}/core/php83/extensions/php_opcache.dll`
`zend_extension=php_opcache.dll`

However, activating it in Xampp implies that the database initialization is blocked at step No. 3

![Image](https://github.com/user-attachments/assets/bc4ecd19-b81a-4bff-a7dd-74d7f1edc5da)

Affected versions:
xampp-windows-x64-8.2.12-0-VS16-installer.exe
xampp-windows-x64-8.1.25-0-VS16-installer.exe
UniserverZero 15_0_2_ZeroXV.exe

Proposal:
Remove this prerequisite

**Comment by trasher** [comment]
`opcache` extension is recommended, not mandatory; GLPI works fine without it.
