### ISSUE TITLE
Printer inventory with computers

### ISSUE THREAD

**Issue by Serpher1** [glpi-project/glpi#18594]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Contribution description

Will GLPI Agent scan for printers that are connected to a computer (and attach them to said computer) in the future like OCS plugin did?

**Comment by cconard96** [comment]
GitHub issues here are for bug reports in the core GLPI project only. You can ask about the GLPI Agent on its own GitHub or on the GLPI Forum.

https://github.com/glpi-project/glpi-agent/discussions/
https://forum.glpi-project.org/

**Comment by trasher** [comment]
I have no idea what OCS do on their side, but GLPI Agent already report connected printers when a computer is inventoried.
