### ISSUE TITLE
Notification template how to find original

### ISSUE THREAD

**Issue by geekson** [glpi-project/glpi#1859]
Hello,

I've erased the notification template.
Would it block the email notification process? 
Where can I find samples of notification template please?

Regards,
David

**Comment by sebfun** [comment]
Hi
It depends of what you've replaced ?

Tell us more about that. GLPI version, etc...

You should restore the DB (partial restore of course). Tables named glpi_notificationstemplates or something like this.
Always backup DB before doing DB's modifications !

**Comment by geekson** [comment]
@Sebfun,

Hi thanks for your answer. Ok I suck a little bit, I forgot to backup the DB. Anyway,

After restoring from an old backup I noticed the HTML body of an Alert Reservation doesn't work right:

<p>##lang.reservation.entity## : ##reservation.entity## <br /> <br />
##FOREACHreservations## <br />##lang.reservation.itemtype## : ##reservation.itemtype##<br />
##lang.reservation.item## : ##reservation.item##<br /> <br />
<a href="##reservation.url##"> ##reservation.url##</a><br />
##ENDFOREACHreservations##</p>

Anyway, I use another notifcation template.

Regards,
david

**Comment by sebfun** [comment]
For Alert reservation on GLPI 9.1.2 default notification, here it is : 

 ##lang.reservation.entity## : ##reservation.entity##

##FOREACHreservations##
##lang.reservation.itemtype## : ##reservation.itemtype##
##lang.reservation.item## : ##reservation.item##

##reservation.url##
##ENDFOREACHreservations##

Looks like to be the same as you and I haven't any problm with email notication.
What about your SMTP server's error or info or debug ?

**Comment by geekson** [comment]
@sebfun 
Well, now it works with the alert reservation notif template... I'm a bit lost... 
I used to receive something like:
------------------------------
Entity:##reservation.entity##
##reservation.expirationdate##


--
-------------------------------
It might have been the code not written properly. 
Thanks a lot mate :+1: 
I still have a question if I may, how come the automatic action "watcher" do not launch "queuedmail" within the scheduled time: 

Last run	2017-02-28 11:07 
Next run	As soon as possible.
(2017-02-28 11:08)

but it's 11:15 am

**Comment by sebfun** [comment]
you're welcome

I've no idea for that but you should open a new topic for that
