### ISSUE TITLE
Make icon up & down more visible in view

### ISSUE THREAD

**Issue by gitdevmod** [glpi-project/glpi#1866]
Hi,

Since 9.1.x (I guess), it's not possible to order elements in view.
![glpi-view](https://cloud.githubusercontent.com/assets/2040775/23303766/4894f9a0-fa96-11e6-9cde-54dbe6cae708.PNG)
As a workaround, it's possible to remove elements and add elements in new order.

**Comment by trasher** [comment]
It is possible, and your screenshot confirm that; but icons are maybe not enough visible.

**Comment by remicollet** [comment]
+1 icones are nearly invisible

**Comment by gitdevmod** [comment]
Indeed ! I just changed title
