### ISSUE TITLE
non conform method names

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1872]
Hi

I noticed Crontask::Register() and Crontask::Unregister() don't follow coding standard. The first letter of their name is up case but should not.

As function names are not case sensitive, we may fix this without breaking anything.

http://www.php.net/manual/en/functions.user-defined.php

**Comment by trasher** [comment]
There are many methods that does not suits coding standards... Some of them are just case issues like this one; but other would be more complex to fix (for example methods with an `_` and so on)

**Comment by trasher** [comment]
I propose for those one to:
- create a new method with the right name,
- make old method call new one and add a Warngin into the logs
- deprecate old methods.
