### ISSUE TITLE
Business Rules: item location criterion  dont work

### ISSUE THREAD

**Issue by camillagds** [glpi-project/glpi#188]
When I created a Business rule if the action is "Send an approval request user/group" or "Approval request to technician group manager" and test (or create a ticket) the rule don't work. 
I use that actions in more 4 rules, and after the upgrade the rules dont work.
In the Brazilian Community another user simulated the rule in the version 0.85.4, 0.85.5 and 0.90 and had the same issue.

In the 0.85.3 version It worked perfectly.

http://forum.glpi-project.org/viewtopic.php?pid=287036#p287036

**Comment by orthagh** [comment]
Hello.

I can't replicate this issue on master (i didn't test on previous releases).
I tested whit this rule : 
![image](https://cloud.githubusercontent.com/assets/418844/10756165/97632142-7ca2-11e5-89ac-fbbe17f7a688.png)

And a resulting ticket : 
![image](https://cloud.githubusercontent.com/assets/418844/10756183/b0529ca0-7ca2-11e5-876f-cbccfcfe8074.png)
*Fabien Alin is the supervisor of "Experts GED" group*

**Comment by orthagh** [comment]
I test again with a criterion on item location, and i replicate the issue.
So the issue is not on action but on this precise type of criterion.

I'll push soon a fix

**Comment by camillagds** [comment]
Thank you
