### ISSUE TITLE
Requester source defaults not adhered to when adding followup to ticket

### ISSUE THREAD

**Issue by tyronewyatt** [glpi-project/glpi#1881]
When I requester replies to the GLPI notifications the followup is added to the ticket with the source of followup not being set to email. This used to be the case 0.85 and older. 
![image](https://cloud.githubusercontent.com/assets/13756677/23387037/2e0c9fb4-fdae-11e6-931e-01a2e22e9300.png)
If I create a follow up the followup source is not set to helpdesk.
![image](https://cloud.githubusercontent.com/assets/13756677/23387067/5f221228-fdae-11e6-8fa6-a5f5e030ded8.png)
To my understanding followup type should be set from request source.
![image](https://cloud.githubusercontent.com/assets/13756677/23387116/a3cfeaf8-fdae-11e6-8a53-131787121be8.png)

**Comment by tomolimo** [comment]
Hello,
Could you also check these values:
![image](https://cloud.githubusercontent.com/assets/7569958/23395939/76a42778-fd91-11e6-8912-1f95cd639afa.png)
?

**Comment by tyronewyatt** [comment]
Thanks. So It seems new 9.1 installs have the correct settings for ticket follow-up default.
But older GLPI installs upgrade to 9.1 don't have defaults for tickets follow-ups as per screen shots below.
Might be worth closing the issue is defaults correct in new installs.
![screenshot_20170228-221016](https://cloud.githubusercontent.com/assets/13756677/23403398/13b4b560-fe04-11e6-91a0-6e7528f0f3c5.png)
![screenshot_20170228-220913](https://cloud.githubusercontent.com/assets/13756677/23403405/18f2d05c-fe04-11e6-9559-7f9f95cee20c.png)
