### ISSUE TITLE
[GLPI 9.1.2] Traduction manquante

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#1882]
Bonjour
Dans la liste des tickets en français, il manque la traduction du nombre de tickets affichés à droite

Ex : From 1 to 25 of 25

Cela ne me gêne pas c'est juste pour info
Merci et bon courage

**Comment by trasher** [comment]
Duplicates #1841

**Comment by sebfun** [comment]
autant pour moi je n'avais pas vu qu'il y avait déjà une demande

**Comment by tomolimo** [comment]
In English, please :)

**Comment by ladenree76000** [comment]
#1841  should not be closed, since the incident is not due  to lack of translation in locales but mistyping in html.class.php line 4008

**Comment by trasher** [comment]
String has been changed in sources (see #1354).
But locales has maybe not been extracted again since.

**Comment by trasher** [comment]
It has been. I confirm the new string is on transifex and has been translated. So ; this is already fixed. Will be ok in the next release.

**Comment by sebfun** [comment]
I joined Transifex and started to translate
