### ISSUE TITLE
9.1.1: Software version dropdown can't be understood

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#1886]
Hi,

When trying to select all software with a specific version, if there are multiple entries of said version, user doesn't know which to select. Here for example there are two versions of 5.1.6.2 and of 2.3.18. 

![glpi_software_version_select](https://cloud.githubusercontent.com/assets/3509962/23456904/afe72636-fe75-11e6-8e83-58e8aa0b1de8.png)

Nothing distinguishes them.
To select the correct one, the user has two options:
* select one, inspect the DOM element, find the hidden input and check the ID is the correct one
* or select one, test it (it reloads the page), if it's not right, test the next

Related to https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2085.

Thanks

**Comment by trasher** [comment]
As far as I understand, the problem is we're working with soft and version, not version only.  I wonder if we could change to get only the version; we'll have to search on the version name rather than its ID then.

@orthagh thoughts?

**Comment by orthagh** [comment]
PR incoming
