### ISSUE TITLE
A user is not disable when the user is disable in AD

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#1889]
Hello,
a user is not disable when the user is disable in Active Directory after syncronization.

GLPI 9.1.2

**Comment by yllen** [comment]
What are your parameters for disable user in AD?
Kepp user? put it in the dustbin?

**Comment by AircraftRu** [comment]
Hello, @yllen 
`Action when a user is deleted from the LDAP directory - Disable`

**Comment by AircraftRu** [comment]
This ticket don't actualy. User is disable if he is disable in AD.
