### ISSUE TITLE
Contract supplier: don't hardcode query in form method

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#1895]
Hi,

Currently the [SQL query to get suppliers linked to a contract](https://github.com/glpi-project/glpi/blob/9.1.2/inc/contract_supplier.class.php#L157) is hardcoded in a form method (Contract_Supplier::showForSupplier()).
This poses a problem to build plugins around, since the same code has to be copied.
I think using a method in the Contract class would be appropriate.

Thanks.

**Comment by flegastelois** [comment]
Hi Pierre,

Thanks a lot for your proposal.
Can you open a pull request with the code ?
We'd review it and test it, that's for me the best solution right now.

Regards,

**Comment by yllen** [comment]
List of suppliers in a contract or list of contracts for a supplier must be in Contract_Supplier class.
It's the framework of GLPI.

**Comment by pVesian** [comment]
@yllen I'm not saying it shouldn't be in Contract_Supplier, I'm saying it should be in a separate function so it can be reused.
