### ISSUE TITLE
responsive mode

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#190]
Improve view on smartphone

**Comment by korial29** [comment]
Hi ! i still have a problem with the ticket add form : 
![image](https://cloud.githubusercontent.com/assets/12070735/10943045/00ea7702-8313-11e5-873f-df702d000505.png)

**Comment by orthagh** [comment]
In meeting right now, i'll check tomorrow

**Comment by korial29** [comment]
Please take a look on my last commit : 1739cbdc7eff460f817e2f6566496ee853280601

**Comment by orthagh** [comment]
counteroffer for this issue :)
