### ISSUE TITLE
Unable to load files

### ISSUE THREAD

**Issue by geekson** [glpi-project/glpi#1907]
Hello,

I'm trying to upload a file from glpi 9.1 but I get this error 

![filetype_error](https://cloud.githubusercontent.com/assets/15198277/23605411/e8de5b72-025c-11e7-906b-a76eff778e2f.PNG)

I have nothing in the logs. I cannot upload any type of documents... What is the cause of this?

Can you help?

By the way we cannot put colon in this message box...

**Comment by wawax** [comment]
Hello,

The type of file is not allowed to be uploaded. You have go to setup > dropdowns => document type and add the extension.

**Comment by geekson** [comment]
Hello,

thanks for answering. Actually I haven't change the config since last time I uploaded documents. The list of document types is fair. For instance the PDF upload is authorised and yet I'm unable to upload it.

![document type](https://cloud.githubusercontent.com/assets/15198277/23606019/40371a88-025f-11e7-8a16-88ab18575021.PNG)

**Comment by tomolimo** [comment]
Hello,
Which GLPI versions, and which OS, web server, etc...?
Thank you
Tomolimo

**Comment by geekson** [comment]
Hi,

Thanks for your time! Actually, versions is 9.1 OS is windows server 2012.

I use Apache 2.4.9
mysql 5.6.17
php 5.5.12

Cheers,

**Comment by tomolimo** [comment]
And SSO NTLM?

**Comment by geekson** [comment]
I do not manage SSO, yet I know we use it within our domain. I do not know about NTLM.
The authentication is link to our LDAP directory that's all.

**Comment by tomolimo** [comment]
Do you use the SSPI module of Apache?

**Comment by tomolimo** [comment]
which browser?

**Comment by geekson** [comment]
I use chrome Version 56.0.2924.87
I don't see any SSPI
![image](https://cloud.githubusercontent.com/assets/15198277/23606572/9e6ad3cc-0261-11e7-8169-c62dfd1edc44.png)

**Comment by geekson** [comment]
NB Even by using Firefox and another glpi account I get the problem.

**Comment by tomolimo** [comment]
Did you check the Apache logs?

**Comment by geekson** [comment]
Nothing inspiring:
[Mon Mar 06 09:49:24.294708 2017] [mpm_winnt:notice] [pid 5152:tid 516] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Mon Mar 06 09:49:26.325396 2017] [mpm_winnt:notice] [pid 5284:tid 432] AH00364: Child: All worker threads have exited.
[Mon Mar 06 09:49:26.372258 2017] [mpm_winnt:notice] [pid 5152:tid 516] AH00430: Parent: Child process 5284 exited successfully.
[Mon Mar 06 09:49:29.465255 2017] [mpm_winnt:notice] [pid 8988:tid 516] AH00455: Apache/2.4.9 (Win32) PHP/5.5.12 configured -- resuming normal operations
[Mon Mar 06 09:49:29.465255 2017] [mpm_winnt:notice] [pid 8988:tid 516] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:13:13
[Mon Mar 06 09:49:29.465255 2017] [core:notice] [pid 8988:tid 516] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Mon Mar 06 09:49:29.465255 2017] [mpm_winnt:notice] [pid 8988:tid 516] AH00418: Parent: Created child process 10208
[Mon Mar 06 09:49:30.136972 2017] [mpm_winnt:notice] [pid 10208:tid 436] AH00354: Child: Starting 64 worker threads.
[Mon Mar 06 10:02:00.589385 2017] [access_compat:error] [pid 10208:tid 984] [client ::1:61004] AH01797: client denied by server configuration: C:/wamp/www/glpi/files/_log/php-errors.log
[Mon Mar 06 10:26:14.036875 2017] [access_compat:error] [pid 10208:tid 980] [client ::1:61636] AH01797: client denied by server configuration: C:/wamp/www/glpi/files/_log/php-errors.log
libpng warning: Interlace handling should be turned on when using png_read_image

**Comment by geekson** [comment]
Any idea?

**Comment by geekson** [comment]
Looks like the documents sent from a specific company are not authorised to be uploaded.

**Comment by miitniick** [comment]
Did you resolve this problem? I have the same
