### ISSUE TITLE
Recalculation of resolution time in SLT

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#1911]
GOAL : 
Add new option for calculating the resolution time in SLT:
- Calculate according to the ticket opening date (Current operation)
- Calculate according to the date of assignment of the SLT

This choice will be made at the level of the SLT.
![sla](https://cloud.githubusercontent.com/assets/15138371/23615071/8b0e69aa-0285-11e7-973b-11e46bd53aeb.png)

Are you agree with this feature?

**Comment by flegastelois** [comment]
Hi Amandine,

I don't understand the need to recalculate the maximum resolution time as soon as a ticket is take into account, I think it's not the standard for "Resolution Time KPI". So I personally disagree with this feature as it is.

However, could you more explain the context ? (perhaps by providing us a complete workflow as an example)

Regards,
François

**Comment by tsmr** [comment]
For example : 
At this time in GLPI : 
Ticket created at 09h00

You affect SLT (on TTR) for a Group G1 (with 2 hours for resolve it)
And if G1 change affectation of ticket to G2 at 10h30 (which have 1 hour for resolve it - if we use rules engine), the G2 group have no time to resolve.

Because in GLPI, the resolution time is calculated all the time from creation date.

Another context : If an enterprise wants to use SLT like OLA (Affect each SLA / Calendar for each technicians groups)

**Comment by molinux** [comment]
Hi !

I suggested in the issue #1912 an option to calculate the total time of a ticket withou the pending time.
Many GLPI users are in need of this functionality

**Comment by flegastelois** [comment]
Hi Xavier, thanks for the details.

Developing and using OLAs seems to me the cleanly right solution, that is exactly what we are discussing internally in trying to understand your needs.

By definition the OLA is not the SLA, so we can't include it directly in the SLT.

What you said, and I agree with you : 
* SLA : is for describe engagement between IT provider and customer ;
* OLA : is for describe engagement between IT team to each other.

This may be the time to fully specify service level management (SLM) that can be used to describe SLR, SLA, OLA, and UC.

* SLR (service level requirement) : not already coverred by GLPI ;
* SLA : already coverred by GLPI with SLT (Time to own and time to resolved) ;
* OLA (operational level agreement) : not already coverred by GLPI ;
* UC (underpinning contracts) : we can say that this may be the contracts, but it would require a direct link with the service levels.

All these notions could come in a new menu (drop in replacement of actual "SLA") or in an extension of the categories that must be reviewed in service catalog (multi-targets).

Have you ever written such specifications ? 
Can you help us write them down ?

François.

**Comment by tsmr** [comment]
Hello Francois

Several points to note on our side.

I totally agree with you on the principle and the fact of evolving the whole module.

However
- This is a very urgent customer request and we will unfortunately not have the time necessary to evolve all this module at his time.
- This option solves an existing problem in the heart. Indeed, with the rule engine we already arrive at this incoherent result and it is necessary from my point of view to make a correction.
- The choice is left to the users (with this option) to restart or not the calculation when assigning this SLT, so the initial behavior is not affected.

**Comment by molinux** [comment]
What about counting the SLT total time without pending time ?!?

Many users need this option

**Comment by zinhleShabangu** [comment]
Good Day
was there a resolution to this problem. i also am trying to re-set the SLA based on corrected values(criticality,impact,priority) entered by the technician.
