### ISSUE TITLE
Ticket total time (SLA) without Pending Time

### ISSUE THREAD

**Issue by molinux** [glpi-project/glpi#1912]
Hi Guys !

Me and another guys have a problem with GLPI x SLA total time
When I change a ticket from processing to pending status and after a time return to processing, the pending time is counted in the final SLA result.

For some contracts this is a big problem and I think GLPI should have an option to choose whether the pending time should be accounted or not in the total SLA time

Here, I created an SQL query example that counting the total SLA with and without pending time and I hope it can help and that this function will be soon integrated into GLPI

SELECT id,CONVERT(name USING utf8) AS "Title",date AS "Opening Date",solvedate AS "Solution Date", 
SEC_TO_TIME(waiting_duration) AS "Pending Time",
CONCAT(FLOOR(HOUR(SEC_TO_TIME(TIME_TO_SEC(TIMEDIFF (solvedate,date))))/24), ' days ',  
MOD(HOUR(SEC_TO_TIME(TIME_TO_SEC(TIMEDIFF (solvedate,date)))),24), ':',  
MINUTE(SEC_TO_TIME(TIME_TO_SEC(TIMEDIFF (solvedate,date)))), ':',  
SECOND(SEC_TO_TIME(TIME_TO_SEC(TIMEDIFF (solvedate,date))))) AS "Total Time + Pending",
CONCAT(FLOOR(HOUR(SEC_TO_TIME((TIME_TO_SEC(TIMEDIFF(solvedate,date)))-waiting_duration))/24), ' days ', MOD(HOUR(SEC_TO_TIME((TIME_TO_SEC(TIMEDIFF(solvedate,date)))-waiting_duration)),24), ':',
MINUTE(SEC_TO_TIME((TIME_TO_SEC(TIMEDIFF(solvedate,date)))-waiting_duration)), ':',
SECOND(SEC_TO_TIME((TIME_TO_SEC(TIMEDIFF(solvedate,date)))-waiting_duration))
) 
AS "Real Total Time" 
FROM glpi_tickets

**Comment by rpereira156** [comment]
Did you get any feedback from the community? I've read the #1911 issue, but is inconclusive if this functionality was added to the backlog to be developed or not.
As i've said [here](https://forum.glpi-project.org/viewtopic.php?id=171442), I'm having a similar problem.

**Comment by trasher** [comment]
Issue #1911 has been fixed in https://github.com/glpi-project/glpi/pull/2185
