### ISSUE TITLE
I dont' see tickets on a computer but I see tickets in tickets view

### ISSUE THREAD

**Issue by johannsan** [glpi-project/glpi#1916]
Hello, 
with a profile like  "technician", I see tickets when I'm in glpi_tickets_users or when the ticket is new, but I don't see all tickets : 
![image](https://cloud.githubusercontent.com/assets/6028912/23706250/b30ac1fe-040d-11e7-80b3-02d7dc540475.png)

On ticket's list, I see tickets 48, 49, 50 : 
The 49 and 50 creator is user "normal"
The 48 creator is "glpi".
I am connexcted with the user "glpi"
![image](https://cloud.githubusercontent.com/assets/6028912/23706381/39652c3a-040e-11e7-8aec-da19b077292f.png)

but, in the computer, I don't see the tickets 49 and 50: 
![image](https://cloud.githubusercontent.com/assets/6028912/23706658/627bef90-040f-11e7-971c-52fc822b7d78.png)

I think, there is a bug (in 0.90.5 or 9.1.*) in ticket.class.php / showListForItem() on line 5301 :  
![image](https://cloud.githubusercontent.com/assets/6028912/23706723/ab4b8dca-040f-11e7-822a-324cab02c34d.png)

 $restrict .= " AND (`glpi_tickets`.`users_id_recipient` = '".Session::getLoginUserID()."'    --> OK
OR (`glpi_tickets_users`.`tickets_id` = '".$item->getID()."'                        --> tickets_id is not computer's id
       AND `glpi_tickets_users`.`users_id`= '".Session::getLoginUserID()."'))";

So I think the correction is perhaps : 
![image](https://cloud.githubusercontent.com/assets/6028912/23707018/f65844e2-0410-11e7-83f7-6e34ea9729ca.png)

The result is :  
![image](https://cloud.githubusercontent.com/assets/6028912/23707035/09750358-0411-11e7-9022-338382576e97.png)

**Comment by johannsan** [comment]
No evolution or correction?

**Comment by johannsan** [comment]
Is it the same problem : 
https://github.com/glpi-project/glpi/commit/7a6c3728cf250241a08f956b4038619acde27ef4
?

**Comment by trasher** [comment]
I do not think it's related to that other ticket; you can test that on your side since it's been fixed already.

I guess you're right, there is something wrong with 
```
`glpi_tickets_users`.`tickets_id` = '".$item->getID()."'
```

**Comment by johannsan** [comment]
yes, "My" bug is still present.
I think my proposition est still to do  : 

Replace
`glpi_tickets_users`.`tickets_id` = '".$item->getID()."'
by 
`glpi_tickets_users`.`tickets_id` = `glpi_tickets`.`id`


And add : 
if (Session::haveRight(self::$rightname, self::ASSIGN))
{
	$restrict .= "OR (`glpi_tickets`.`status`=".self::INCOMING.")";
}
