### ISSUE TITLE
[GLPI 9.1.2] Processing Ticket View - Ticket Recall display a wrong requester name

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#1918]
In Processing ticket view when you use "Vertical Split" Layout, and your ticket have more than one requester, the requester name displayed on ticket recall is the username whose name is the last in alphabetical order.

This issue does not occured on splitted view Layout and classic Layout.

**How to reproduce ?**

1 - Configure your profile to use Vertical Split Layout (Preferences)
2 - On a ticket add a requester which have his first last name letter after first last name letter of the first requester in alphabetical order (exemple : If you have Mr SMITH John, add Mr WHITE Spirit ..)
3 - Go on Processing ticket view and check requester which is displayed on ticket Recall. (You can see Mr White Spirit in place of Mr SMITH John)

thx

**Comment by vinz38500** [comment]
In addition, the wording is wrong ... Should be ticket Sum Up and not ticket recall ;) (I guess)

**Comment by trasher** [comment]
This does not seems to be related to the view used.
Tickets can have multiple requesters; but recall on ticket processing display only one... Maybe should we display the first attached one; but that sounds a bit incorrect.

And I guess you're right @vinz38500 ; "recall" is probably wrong :)

**Comment by nqb** [comment]
Maybe linked to #2442

**Comment by nqb** [comment]
Maybe linked to #2442
