### ISSUE TITLE
The assign table disappears when a closed ticket is created

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#192]
Example :
Profile with Life cycles blocked for Closed status to others

Logon with this profile
Launch ticket creation
Modify status to closed
Change Requester
The assign table disappears

**Comment by orthagh** [comment]
added by @yllen in commit 367989e2

issue in this part  : 
```
if (!$ID) {
...
   && $this->isAllowedStatus($this->fields['status'], CommonITILObject::ASSIGNED)

```

In case of new ticket, status defined by user is the final status and can't be changed by the user/group assignation.

I think isAllowedStatus test is unnecessary and should be removed

**Comment by yllen** [comment]
I done what Tsmr said and i don't reproduce

**Comment by orthagh** [comment]
@yllen 

you need this configuration : 
![image](https://cloud.githubusercontent.com/assets/418844/10966764/1a57098c-83b6-11e5-856c-16f64d31bd3e.png)

* logout/login
* Open new ticket form (you don't need to submit to see issue)
* Set status to closed
* Change any fields (request/category/type/...) who refresh your browser page
* See results : 
![image](https://cloud.githubusercontent.com/assets/418844/10966847/9d72e836-83b6-11e5-9492-eb245dd25d44.png)

I think we don't need this line : https://github.com/glpi-project/glpi/blob/2533d7b2b77fa4377d9f3d83b16d2a3cdd288140/inc/commonitilobject.class.php#L3885

This check is for avoiding status change to "assigned" but on ticket creation, a "status" set buy user can't be overwrited by adding a assign user.
Higher in code, we have a check on ticket creation/update ("if (!$ID) {") so i think we can remove this part : 
$this->isAllowedStatus($this->fields['status'], CommonITILObject::ASSIGNED)

**Comment by yllen** [comment]
Je suis désolée mais je n'arrive vraiment pas à reproduire
![yllen](https://cloud.githubusercontent.com/assets/12936722/10995017/2e6b2290-847a-11e5-984f-e64751aa83e8.jpg)

J'ai bien le cycle de vie bloqué comme demandé

**Comment by yllen** [comment]
Ok i understand. It's when you change an actor, form is reload
