### ISSUE TITLE
rest API - php notice

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#1924]
backtrace 

2017-03-09 11:13:52 [132@vm000169]
  *** PHP Notice(8): Undefined index: searchtype
  Backtrace :
  inc/search.class.php:116                           Search::constructSQL()
  inc/api.class.php:1379                             Search::getDatas()
  inc/apirest.class.php:174                          API->searchItems()
  apirest.php:46                                     APIRest->call()

**Comment by trasher** [comment]
Could you provide more details please?

**Comment by btry** [comment]
Not sure : I found this while searching for something else; and I don't have more data about it. I need to find how to reproduce it; the backtrace is a first clue for that.
