### ISSUE TITLE
Adding a task to a project raised a php error on debug mode

### ISSUE THREAD

**Issue by arnaudmeurou** [glpi-project/glpi#193]
Hi,

With glpi 90, when you click on add a task on a project the form is loaded but this error is raised : 

```PHP Notice: Undefined index: projecttasks_id in /usr/share/glpi90/inc/projecttask.class.php at line 361```

Full stack error :
```
2015-10-22 09:00:10 [7@luna]
  *** PHP Notice(8): Undefined index: projecttasks_id
  Backtrace :
  inc/projecttask.class.php:361                      
  inc/commonglpi.class.php:611                       ProjectTask->showForm()
  inc/commonglpi.class.php:1124                      CommonGLPI->showPrimaryForm()
  front/projecttask.form.php:86                      CommonGLPI->display()
```

This not seems to prevent to use the form...

**Comment by orthagh** [comment]
Can't replicate this error.

Could you check the url when error trigger and copy/paste here ?

**Comment by arnaudmeurou** [comment]
https://server/glpi90/front/projecttask.form.php?projects_id=2 is called when i press "add a task"

I forgot to say that i update from 0.84.7 to 0.90, maybe something wrong during migration. I'm going to test with clean install to confirm this...

**Comment by arnaudmeurou** [comment]
I found the problem, this error is raised only when i use the vertical split view. Clean install and migrated install are concerned. using standard view doesn't raised the error.
