### ISSUE TITLE
requester or requester group missing after ticket creation

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1936]
Hello

on many tickets I don't see the requester group and / or I have no requester

in debug mode i found this issue

PHP Notice: Undefined index: users_id in C:\inetpub\wwwroot\glpi\inc\ticket.class.php at line 6058

database user_id_recipient is correctly filled

**Comment by btry** [comment]
Hi

Please have a look in files/_log/php-errors.log : you will find the error message with the related backtrace. Can you copy it here ?

**Comment by satyan01** [comment]
2017-03-10 14:49:40 [1186@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: users_id
  Backtrace :
  inc\ticket.class.php:6058                          
  inc\ticket.class.php:605                           Ticket->getTimelineItems()
  inc\commonglpi.class.php:206                       Ticket->getTabNameForItem()
  inc\ticket.class.php:703                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:161                       Ticket->defineTabs()
  inc\commonglpi.class.php:722                       CommonGLPI->defineAllTabs()
  inc\commonglpi.class.php:1173                      CommonGLPI->showTabsContent()
  front\ticket.form.php:194                          CommonGLPI->display()

**Comment by trasher** [comment]
The field is missing in the database. This is a GIT running update issue.
