### ISSUE TITLE
TinyMCE adds CR LF to its return content that will be transformed to "rn" in solution

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#1944]
Hello,

When adding simple text like 

> Test 
of 
multilines

 in a ticket solution,

Then will get 

> Test
rn
of
rn
multilines

And when doing some spying on the HTTP traffic, one can see that tinyMCE is sending:
`<p>Test</p>\r\n<p>of</p>\r\n<p>multilines</p>`

And GLPI will transform this into 
`<p>Test</p>rn<p>of</p>rn<p>multilines</p>` 
due to `Toolbox::stripslashes_deep()` that uses stripslashes() which will delete any `\`, and left only the "rn" string.

Use of stripcslashes() will solve this issue,

thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
In order to prevent code breaks, I preferred to prevent tinyMCE to output \r\n from editor at submit time

**Comment by tomolimo** [comment]
@trasher: the issues (#1944 and #2031) are not the same this as this one is via web user interface, and the other one is via mailgate.

**Comment by trasher** [comment]
Oh... You're right; thanks.

**Comment by 20-100** [comment]
I've encountered the same problem.

If that might be of any use : If I hit "Shift + Enter" instead of "Enter" to add a newline, it doesn't create a new paragraph but a newline nonetheless, and there is no "rn" added.
Not sure about the consequences of this behaviour on mail/html rendering, but I'm going to use this as a workaround until a proper fix is released.

**Comment by orthagh** [comment]
Since b40d8c52d2695a9761c95999a75bdaa0266e67ef

**Comment by Vitamol** [comment]
Same bug in 9.2 version.

**Comment by vitalybelskih** [comment]
Confirm. in GLPI 9.2 same bug. I try to insert lines from solution #1954 to line 3474 of file html.class.php, but it's doesn't help.

**Comment by lcpj** [comment]
@vitalybelskih line 1134 in /inc/commondbtm.class.php is a empty line before 

` if (!$this->getFromDB($input[static::getIndexName()])) {`


What exactly did you comment to make it work?

**Comment by joaoheytor** [comment]
Same in 9.2.
![image](https://user-images.githubusercontent.com/13548034/32272749-a0970ae8-bee6-11e7-9f0c-2dc4008c8807.png)
And:
![image](https://user-images.githubusercontent.com/13548034/32272785-d155cef8-bee6-11e7-9154-9110b115c7f3.png)

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/pull/3095
