### ISSUE TITLE
[9.1.2] wrong sla escalation - supplier assigned

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1945]
I have the following. SLT escalation for time to solve.
The ticket have a supplier assigned so i should no get a email. 

```
SLT
Child entities
No  
Name  Comments  
SLA Silber 
Last update 25-06-2015 14:38 
Type 
… Time to resolve 

Maximum time 
… 12 

… Hours 

Created on 18-11-2016 16:33
Last updated on 25-06-2015 14:38

```

`
Add an escalation level
Name  Execution 
… - 12 hours 
 Active 
… Yes 
 Actions 
Name
Execution
Active
  Noch-nicht-gelöst - 4 hours 0 minutes Yes 
Criteria
Criterion
Condition
Reason
Technician exists Yes 
Status is not Pending 
Status is not Processing (planned) 
Assigned to a supplier is N/A 
Criterion
Condition
Reason
Actions
Fields
Action type
Value
Automatic reminders of SLT Send Yes 
Fields
Action type
Value
 
`

![img_025](https://cloud.githubusercontent.com/assets/19192087/23864328/742feeba-0812-11e7-9f0d-db10b70a728f.jpg)
![img_024](https://cloud.githubusercontent.com/assets/19192087/23864329/7475108a-0812-11e7-8e15-4446e6088e98.jpg)

If i search for this combination i got no tickets in my system, but i got a escalation. I should not get a escalation if a supplier is assigned.

![img_021](https://cloud.githubusercontent.com/assets/19192087/23864501/03091300-0813-11e7-89a0-7bdf2c2249ec.jpg)

**Comment by Armin83** [comment]
@orthagh 
Is this a known bug or does this filter don't work correct ?

**Comment by bobogner** [comment]
Very similar problem here. I have SLA / SLT defined to follow several of my ITIL categories.

Configuration:
- SLT to escalate to my subordinate if service is 10 minutes late.
- SLT to escalate to me if service is 20 minutes late.
- slaticket job (automatic actions) runs every 15 minutes. 

Problem:
SLA constantly sends mails as if ticket has been Updated and the ticket is not updated! SLA has been started and it works but it sends mail as if the ticket has been changed. SLA has not made any changes to the ticket yet the mail of an update has been sent. This is very frustrating and my GLPi has become a spamming service. Sending SLA remnider has the sam effect. Please help!
