### ISSUE TITLE
Global asset not displayed

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#1953]
Error: Unknown column 'glpi_softwarelicenses.contact' in 'field list'
  Backtrace :
  inc/search.class.php:921                           
  inc/search.class.php:97                            Search::constructDatas()
  inc/search.class.php:80                            Search::showList()
  front/allassets.php:46                             Search::show()

**Comment by trasher** [comment]
Is not that one already fixed in the 9.1/bugfixes branch?

**Comment by trasher** [comment]
Sounds like fixed in 9.1/bugfixes; cannot reproduce

**Comment by orthagh** [comment]
duplicate #1329
