### ISSUE TITLE
Technician can edit the task created at ticket level even after closure of the task.

### ISSUE THREAD

**Issue by nageshpnr** [glpi-project/glpi#1958]
Dear GLPI team,

Technician can edit the task created at ticket level even after closure of the task.

Steps to reproduce:
1. Portal user created a Ticket type as Request. 
2. Lead will assign the ticket to the Technician.
3. Technician creates the task and enter the hours.
4. Technician will enter the solution and ticket will go to the solved status.
5. Portal user approves the solution and ticket will be closed automatically.
6. Even after closing the ticket Technician can edit the task. How to restrict the editing the task even after ticket closing.

**Information at General setup**
[code]
 
GLPI 9.1.2 (/glpi => C:\xampp\htdocs\glpi)

Operating system: Windows NT GLPIDEV 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
PHP 5.6.28 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash,
	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, standard, tokenizer, wddx, xml, xmlreader,
	xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28 (Apache/2.4.23 (Win32) OpenSSL/1.0.2h PHP/5.6.28 Server at
	213.42.143.107 Port 90)
	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Server Software: mariadb.org binary distribution
	Server Version: 10.1.19-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpidb
	Host info: localhost via TCP/IP

**Comment by CCoruble** [comment]
Hi,

Did not test on my glpi but I think you can change this in the profile permission in "Assistance" "Followups/task"
Try to uncheck this permission :
![2017-04-14 14_45_19-glpi - profiles - 6](https://cloud.githubusercontent.com/assets/24699373/25043559/2022cbb2-2121-11e7-8eb5-f8e27291046b.png)

I did check all the permissions of this profile and it seems to be the only permission that could allow editing task / followups of closed ticket. But as I said I'm not sure !
