### ISSUE TITLE
planning calendar dropdown group technicians

### ISSUE THREAD

**Issue by klodnitsky** [glpi-project/glpi#1960]
Hello,

Is it possible to fix css style in planning, when I try to add a group, and show all names, then I can't see all technicians.

![screenshot_3](https://cloud.githubusercontent.com/assets/7794575/24095975/3f48c02c-0d68-11e7-83ec-f54a332cb972.png)

**Comment by trasher** [comment]
I must admit this display is kind of horrible... But during my tests, on firefox and chromium; I always get the full list displayed; main window height adapt to adjust.
What browser are you using?

**Comment by klodnitsky** [comment]
Hhmm.. I tried in other browsers and it seems the same issue.
Google Chrome 57.0.2987.133 (incognito, without addons) - problem;
Internet Explorer 11.103.14393.0 - problem;
Firefox 51.0.1 (32bit) - problem;

**Comment by trasher** [comment]
Not sure I understand the issue then... But anyways; that display should be changed ;)

**Comment by trasher** [comment]
Hi,

Could you please test the fix proposed in https://github.com/glpi-project/glpi/pull/1992?

**Comment by klodnitsky** [comment]
Hi,

Now It seems OK, but new issue with Planning box in main menu.

This one is ok:
![plan2](https://cloud.githubusercontent.com/assets/7794575/24538850/3c4a3d8a-15f4-11e7-944c-6e7c494a7cc0.png)

New issue after fix:
![plan1](https://cloud.githubusercontent.com/assets/7794575/24538839/36c25d70-15f4-11e7-9eaa-196157a0d755.png)

**Comment by trasher** [comment]
Oh... I missed that. I've fixed the fix! https://github.com/glpi-project/glpi/pull/1992/commits/103dcbd21141f921d587a1ace183f8a32747ab4d :)

**Comment by klodnitsky** [comment]
Fixed fix works now :) bug solved! :)

**Comment by trasher** [comment]
Great, thant you for testing :)
