### ISSUE TITLE
LDAP mass sync breaks

### ISSUE THREAD

**Issue by pablogaralv** [glpi-project/glpi#1961]
Hi there!
the LDAP mass sync script: https://github.com/glpi-project/glpi/blob/master/scripts/ldap_mass_sync.php
breaks when syncing LDAP directories with 500 or more entries (at least under the same "ou").
php-errors.log contains the following:

`
2017-03-20 15:08:17 [@xxxxxxxxxxxx]
  *** PHP Warning(2): ldap_search(): Partial search results returned: Sizelimit exceeded
  Backtrace :
  :                                                  
  inc/authldap.class.php:1364                        ldap_search()
  inc/authldap.class.php:1491                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:156                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:119                     import()
`

`
2017-03-20 15:08:17 [@xxxxxxxxxxxx]
  *** PHP Warning(2): ldap_control_paged_result_response(): Result is: Size limit exceeded (4)
  Backtrace :
  :                                                  
  inc/authldap.class.php:1417                        ldap_control_paged_result_response()
  inc/authldap.class.php:1491                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:156                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:119                     import()
`

Thanks!

**Comment by trasher** [comment]
I wonder if you should not just change the page size parameter in your ldap direcotry configuration.

**Comment by pablogaralv** [comment]
Well, the thing is: now it is not complaining, nor filling up the log files to the point it runs out of disk space...I increased the "Page size" to 1000 and that seemed to do the trick. It was only synchronizing 500 entries now, but that was an LDAP/SLAPD configuration problem that I solved by adding `olcSizeLimit: 1000` to the `cn=config.ldif` file.
Thanks for your help.
