### ISSUE TITLE
In processing tasks are displayed with last update value

### ISSUE THREAD

**Issue by Djiock** [glpi-project/glpi#1966]
Hello !
In the current (9.1.2) version of GLPI now when editing a task to edit the time it was done, mostly because we write it afterwards (sometimes the next day or so) it's the time we edited the task that is displayed in "processing ticket"...
But the tasks are set in the right order, and we can see in base that "date" is respected, but "date_mod" is displayed.
Is that intentional ?

Thanks ! And thanks again for this amazing piece of software ;)

My setup :

Operating system: Linux xxxxxx 4.4.0-66-generic -Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64
PHP 7.0.15-0ubuntu0.16.04.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at tools.xxxxxx.com Port 443)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0
Server Software: Ubuntu 16.04
	Server Version: 10.0.29-MariaDB-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by Djiock** [comment]
Hi there !

I just upgraded to 9.1.3 and "date_mod" is still displayed instead of the date of the task we want to set...

Will it stay that way now in GLPI ?

Thanks

**Comment by Djiock** [comment]
Hello !

We upgraded to 9.1.6, still the same. And I tested with latest 9.2, I can see the same behavior.

Since my thread has been labeled "question", can we assume that it will remain that way ?

Thanks in advance

**Comment by trasher** [comment]
Since I do not know if that is intended or not... I've set the question label for someone else to take a look.

**Comment by Djiock** [comment]
I don't know if the behaviour is still the same but I don't have use for it anymore, I'm closing. Sorry for leaving it open for this long.
