### ISSUE TITLE
Software deleted by OCS sync

### ISSUE THREAD

**Issue by Ruiseart** [glpi-project/glpi#197]
There is functionality in GLPI, which fills the comment field in Software by the "Software deleted by OCSNG sync" when a version of an application is deleted. This is a problem for me because I use this field for description of the application. Can I turn this feature off somewhere in the configuration?

**Comment by orthagh** [comment]
Theses line are added by ocsinventory plugin.
I suggest to repost your issue on [forum](http://forum.glpi-project.org/viewforum.php?id=21) or on https://github.com/pluginsGLPI/ocsinventoryng/issues
