### ISSUE TITLE
API: updateItems

### ISSUE THREAD

**Issue by derricksmith** [glpi-project/glpi#1971]
What is the correct input structure for the updateItems endpoint?  I am trying to update multiple items using the following input arrays, neither work:

$post = http_build_query(
	array(
		'input' => array(
			(object) ['id' => 6785, 'name' => 'test1'],
			(object) ['id' => 6784, 'name' => 'test2']
		)
	)
);

$post = http_build_query(
	array(
		'input' => array(
			array('id' => 6785, 'name' => 'test1'),
			array('id' => 6784, 'name' => 'test2')
		)
	)
);

The endpoint method appears to fail at line 1638 when the if (isset($object->id)) check is performed.  The input $object that is produced by the above input is an array and fails.

**Comment by btry** [comment]
Hi

It looks like you're trying to send the names of your objects in the query string. 

You must send the data in the HTTP body of your request.
Have a look into the documentation (apirest.md) and notice in the example the data is not in the query string.

```
$ curl -X PUT \
-H 'Content-Type: application/json' \
-H "Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62" \
-H "App-Token: f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7" \
-d '{"input": [{"id": 16,  "otherserial": "abcde"}, {"id": 17,  "otherserial": "fghij"}]}' \
'http://path/to/glpi/apirest.php/Computer/'
```

**Comment by derricksmith** [comment]
Thanks that clears things up!  Is working now.
