### ISSUE TITLE
[9.1.2] cartridge performance

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#1974]
If i open cartridge the result needs a long time. If i have the following filter result is immediately displayed.

Without filter
8.397 seconds - 2.7 MB

Fast with filter
![img_017](https://cloud.githubusercontent.com/assets/19192087/24353335/61827b9e-12ed-11e7-97bb-48e71a63878c.jpg)

0.075 seconds - 2.7 MB

**Comment by trasher** [comment]
How many entries do you have without filtering?

The default search order set to name may cause issues on large datasets.

**Comment by Armin83** [comment]
Overall we have 71 and slow without filter.
With filter we have 63 and fast.
if i filter with "**and** alert threshold containts -1" i got 8 with slow performance

**Comment by trasher** [comment]
OK, so I guess there are one or more item in the 8 results that is causing the issue.

Could you identify one of those 8 results as cause of this issue? It will be difficult to reproduce otherwise.

**Comment by Armin83** [comment]
I deleted one. We used it to count the sites from printers.

**Comment by Armin83** [comment]
No problems on test system with innodb and mariadb :) 👍

**Comment by trasher** [comment]
Goot to know! Thanks for the feeback ;)
