### ISSUE TITLE
(085+090) Fonction deleted always used

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#198]
showImagePaste always used but deleted in https://github.com/glpi-project/glpi/commit/0b1167a79581794327e20159ad790ec215a33420

**Comment by orthagh** [comment]
@korial29 
You should check this issue

**Comment by korial29** [comment]
The call of this function (document.from line 106) should be deleted. It was used in the old image paste system displayed in a popup, which is no longer used

**Comment by orthagh** [comment]
*thank to ignore ac121f5 commit for this issue, i pushed a bad commit message (now corrected)*
