### ISSUE TITLE
bug in log

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#1983]
[27-Mar-2017 16:31:49 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to a member function query() on null in C:\inetpub\wwwroot\glpi\inc\profile_user.class.php:320
Stack trace:
#0 C:\inetpub\wwwroot\glpi\inc\profile_user.class.php(994): Profile_User::showForEntity(Object(Entity))
#1 C:\inetpub\wwwroot\glpi\inc\commonglpi.class.php(482): Profile_User::displayTabContentForItem(Object(Entity), '1', '')
#2 C:\inetpub\wwwroot\glpi\ajax\common.tabs.php(96): CommonGLPI::displayStandardTab(Object(Entity), 'Profile_User$1', '', Array)
#3 {main}
  thrown in C:\inetpub\wwwroot\glpi\inc\profile_user.class.php on line 320
[27-Mar-2017 17:00:27 Europe/Berlin] PHP Fatal error:  Uncaught Zend\I18n\Exception\ParseException: Unknown or invalid parser rule:  nplurals=INTEGER; plural=EXPRESSION; in C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Plural\Rule.php:194
Stack trace:
#0 C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Loader\Gettext.php(149): Zend\I18n\Translator\Plural\Rule::fromString(' nplurals=INTEG...')
#1 C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Translator.php(700): Zend\I18n\Translator\Loader\Gettext->load('en_GB', 'C:\\inetpub\\wwwr...')
#2 C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Translator.php(572): Zend\I18n\Translator\Translator->loadMessagesFromFiles('mydashboard', 'en_GB')
#3 C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Translator.php(440): Zend\I18n\Translator\Translator->loadMessages('mydashboard', 'en_GB')
#4 C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Translator.php(354): Zend\I18n\Translator\Translator->getTr in C:\inetpub\wwwroot\glpi\vendor\zendframework\zend-i18n\src\Translator\Plural\Rule.php on line 194

**Comment by yllen** [comment]
For first error, corrected with https://github.com/glpi-project/glpi/pull/2009/
For error of Zend, reload your apche to clean apcu cache
