### ISSUE TITLE
GLPI 9.1.1: User profiles removed after synchronization with AD

### ISSUE THREAD

**Issue by AlekseyBykov** [glpi-project/glpi#1984]
After synchronization with AD not all the users visible in the list. For example, in AD I have 500 users, after synchronization only 111 users is available for me in GLPI(other profiles are not created).

I restored backup and all users appeared in GLPI again, but after synchronization remained only 111.

The table glpi_profiles_users before synchronization contains 526 profiles, but after synchronization only 123 profiles.

I performed synchronization through UI and by using scripts/ldap_mass_sync.php:

```
[bykovan@docflow scripts]$ sudo php -q -f ldap_mass_sync.php action=0;
Processing LDAP Server: MS Active Directory, ID: 1
.............................................................................
Imported: 0
Synchronized: 0
Deleted from LDAP: 0


[bykovan@docflow scripts]$ sudo php -q -f ldap_mass_sync.php action=1;
Processing LDAP Server: MS Active Directory, ID: 1
.............................................................................
Imported: 0
Synchronized: 2
Deleted from LDAP: 22


[bykovan@docflow scripts]$ sudo php -q -f ldap_mass_sync.php action=2;
Processing LDAP Server: MS Active Directory, ID: 1
.............................................................................
Imported: 0
Synchronized: 501
Deleted from LDAP: 65


[bykovan@docflow scripts]$
```

What could be the reason?..

My environment:

Server:

> Operating system: Linux docflow.metall1c.local 3.10.0-514.6.1.el7.x86_64 1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 PHP 5.4.16 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="1024M" post_max_size="128M" safe_mode="" session.save_handler="files" upload_max_filesize="100M" Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_auth_gssapi/1.4.0 mod_auth_kerb/5.4 PHP/5.4.16 () Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Server Software: MariaDB Server Server Version: 5.5.52-MariaDB Server SQL Mode: Parameters: glpi@localhost/glpi Host info: Localhost via UNIX socket OK/home/glpi/config : OK OK/home/glpi/files : OK OK/home/glpi/files/_dumps : OK OK/home/glpi/files/_sessions : OK OK/home/glpi/files/_cron : OK OK/home/glpi/files/_graphs : OK OK/home/glpi/files/_lock : OK OK/home/glpi/files/_plugins : OK OK/home/glpi/files/_tmp : OK OK/home/glpi/files/_rss : OK OK/home/glpi/files/_uploads : OK OK/home/glpi/files/_pictures : OK OK/home/glpi/files/_log : OK OKSELinux mode is Disabled

Libraries:

`htmLawed version 1.1.21 in (/home/glpi/lib/htmlawed) phpCas version 1.3.4 in (/home/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.16 in (/home/glpi/vendor/phpmailer/phpmailer) Zend Framework in (/home/glpi/vendor/zendframework/zend-loader/src) zetacomponents/graph in (/home/glpi/vendor/zetacomponents/graph/src) SimplePie version 1.4.1 in (/home/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.12 in (/home/glpi/vendor/tecnickcom/tcpdf) ircmaxell/password-compat in (/home/glpi/vendor/ircmaxell/password-compat/lib) ramsey/array_column in (/home/glpi/vendor/ramsey/array_column/src) michelf/php-markdown in (/home/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/glpi/vendor/true/punycode/src) iacaml/autolink in (/home/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/home/glpi/vendor/sabre/vobject/lib)`

LDAP directories:

`Server: 'XXX.XXX.XXX.XXX', Port: '389', BaseDN: 'CN=Users,DC=Metall1C,DC=local', Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$)))', RootDN: 'glpi@metall1c.local', Use TLS: none`

SQL replicas:

`Not active`

Notifications:

`Way of sending emails: SMTP (anonymous@XXX)`

Mails receivers:

`Name: 'helpdesk@Metall1C.local' Active: No Server: '{XXX:110/pop}INBOX' Login: 'helpdesk@Metall1C.local' Password: No`

Plugins list:

`fusioninventory Name: FusionInventory Version: 9.1+1.0 State: To be cleaned reports Name: Reports Version: 1.9.1 State: Not installed`

I would be very grateful for the information. Thanks to all.

**Comment by AlekseyBykov** [comment]
I found some conformity in the table glpi_profiles_users:

![conformity](https://cloud.githubusercontent.com/assets/19653312/24490747/1514b980-1535-11e7-9393-65ba5d9d7b8f.jpg)

Maybe the solution is to update glpi_profiles_users and for all id with the same profiles_id to leave only one record with profiles_id==1 and is_dynamic==0?..

**Comment by aldrickode** [comment]
Hi,
Have you resolved your problem?
I have the same kind of thing.
How did you do?
Regards
