### ISSUE TITLE
Global approval status - readonly

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#199]
Hi,

If a user does not have the right to add a validation, "global_validation" field should be read only.

Regards,

**Comment by yllen** [comment]
You don't have rights CREATE for ticketvalidation

**Comment by yllen** [comment]
flegastelois 
you want to block global validation in the form of the ticket of in the Approvals tab?

**Comment by flegastelois** [comment]
Hi yllen,

I speak of the field "Global approval status" available in the validation tab.

Even if I do not have the right to send a new approval request, I can change the dropdown (global approval status), but I don't have the "Save" button.

![selection_072](https://cloud.githubusercontent.com/assets/470612/10727592/4ece414a-7bdb-11e5-91c6-e173da8df564.png)

This field should be "read only", like the field "Approval" in main ticket when user has no UPDATE privilege.

![selection_073](https://cloud.githubusercontent.com/assets/470612/10727658/d1ee2a4a-7bdb-11e5-94e1-8a3654be2c5b.png)

Regards,

**Comment by yllen** [comment]
For me, this can be modify if you have right to validate a request not to create one.
It's the validator that indicates the status.

**Comment by yllen** [comment]
OK i think i understand.
There is no problem. In all dropdown in GLPI you don't have text only if you don't have rights, you just delete the button.
But there is a problem in ticket form: you could not be able to change value of global status with update right on the ticket. You must have right to create request (to be consistent)
