### ISSUE TITLE
Create ticket from user

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#1991]
Hello,

It seems that is not possible to create a ticket directly from a user (active directory). If I use the button "New ticket for this item...", the ticket form page opens and I can edit it but when I change something I have (same with admin) : 

![image](https://cloud.githubusercontent.com/assets/12936546/24537740/d95ef3e6-15e4-11e7-9080-0b73ecf9b020.png)

Any help would be really appreciate

Cheers !

**Comment by trasher** [comment]
Hi,

Several tickets already have been opened regading this issue. It's been fixed in the 91/bugfixes branch; please search in existing closed tickets to get the fix.

**Comment by ciadch** [comment]
Thanks for your return
