### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2008]
Hello

Please could you tell me where is the field in database corresponding to ticket technician assigned ?

![image](https://cloud.githubusercontent.com/assets/15144026/24645344/06351c5c-1918-11e7-96fc-7c88b67206ba.png)

I have deleted a profile and all his closed tickets are without technician.

Thank you

**Comment by btry** [comment]
Hi

There is a table glpi_tickets_users. It is the relation between a tickets and actors. Actors are requesters, observers, technicians, and suppliers. An actor may also be an anonymous user, known only by his email address.

Be  careful if you write something in this table.
