### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2010]
Hello

Please could you tell me what is the issue in this log ?

2017-04-04 12:03:52 [1186@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: users_id
  Backtrace :
  inc\ticket.class.php:6058                          
  inc\ticket.class.php:605                           Ticket->getTimelineItems()
  inc\commonglpi.class.php:206                       Ticket->getTabNameForItem()
  inc\ticket.class.php:703                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:161                       Ticket->defineTabs()
  ajax\updatecurrenttab.php:50                       CommonGLPI->defineAllTabs()

**Comment by satyan01** [comment]
same for this one 

2017-04-04 11:23:20 [1186@UNGSRVGVA118]
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_ticketsatisfactions` (`tickets_id`,`date_begin`,`type`) VALUES (\'2017021324\',\'2017-04-04 11:23:19\',\'1\')
  Error: Duplicate entry '2017021324' for key 'tickets_id'
  Backtrace :
  inc\commondbtm.class.php:440                       
  inc\commondbtm.class.php:864                       CommonDBTM->addToDB()
  inc\ticket.class.php:1358                          CommonDBTM->add()
  inc\commondbtm.class.php:1197                      Ticket->post_updateItem()
  front\ticket.form.php:61                           CommonDBTM->update()

**Comment by trasher** [comment]
Please open one ticket per issue; and give a minimum details about how to reproduce, version used, and so on (see https://github.com/glpi-project/glpi/blob/9.1/bugfixes/ISSUE_TEMPLATE.md displayed on new ticket creation).
