### ISSUE TITLE
Traitement du ticket -solution

### ISSUE THREAD

**Issue by chtitcanard** [glpi-project/glpi#2012]
Bonjour,

Je souhaite utiliser glapi pour l'ouverture des tickets. 
Mon équipe fais à la fois du sport Helpdesk, niveau 1 et 2.
Je souhaite pouvoir gérer la resolution en premier niveau c'est à dire des la saisie et que la solution soit indiqué dans le mail.
On peut modifier le statut à résolu depuis l'onglet traitement du ticket mais ne pouvons indiquer la solution sur cette page et donc la solution n'est pas notifiée par mail. 
A-t-on un moyen : 
-d'ajouter le champ solution description directement dans traitement des tickets
-d'inclure une solution dans un autre champ et que ce dernier soit inclus dans les notifications par mail?
Encore Bravo pour cet outil qui est vraiment très intéressant 
Merci

**Comment by sebfun** [comment]
Bonjour
Faut faire vos demandes en anglais ici pas en français
Pour la première question c'est oui grâce au plugin More ticket
Pour la 2e je ne sais pas

**Comment by trasher** [comment]
Hi,

As said, please use english only here.

For usage questions, you'd better ask on forums: http://forum.glpi-project.org/

Thanks
