### ISSUE TITLE
 keep previous description on refused solution #2014 

### ISSUE THREAD

**Issue by berger-anthony** [glpi-project/glpi#2015]
hi,
when a solution is refused, and a new one is written,
the previous solution is remove from the ticket management.
the previous one should be kept with the right date even if the text appear in the new solution.
now, we loose some information in the process reply

**Comment by ladenree76000** [comment]
vote for this suggetion http://glpi.userecho.com/topics/99-ticket-solution-history/
 or something equivalent : create a solution.class and link to ticket allow a ticket to have several solutions, only one is the "last" solution, other are kept for history with its attributes( author, date, category, description, approved/rejected(?))

it is probably much more complicated as it looks, but could be a great improvement
