### ISSUE TITLE
New status.php

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2021]
Hello,

I have modified the status.php page, if it is useful for other users I attached the code

![image](https://cloud.githubusercontent.com/assets/15144026/24793268/ab556906-1b81-11e7-8de8-235c69cb1c8c.png)

I am not a developper so maybe you could optimize the code

**Comment by satyan01** [comment]
<?php
/*
 * @version $Id$
 -------------------------------------------------------------------------
 GLPI - Gestionnaire Libre de Parc Informatique
 Copyright (C) 2015-2016 Teclib'.

 http://glpi-project.org

 based on GLPI - Gestionnaire Libre de Parc Informatique
 Copyright (C) 2003-2014 by the INDEPNET Development Team.

 -------------------------------------------------------------------------

 LICENSE

 This file is part of GLPI.

 GLPI is free software; you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation; either version 2 of the License, or
 (at your option) any later version.

 GLPI is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with GLPI. If not, see <http://www.gnu.org/licenses/>.
 --------------------------------------------------------------------------
 */

/** @file
* @brief
*/

define('DO_NOT_CHECK_HTTP_REFERER', 1);
include ('./inc/includes.php');

// Force in normal mode
$_SESSION['glpi_use_mode'] = Session::NORMAL_MODE;

// Need to be used using :
// check_http -H servername -u /glpi/status.php -s GLPI_OK


// Plain text content
header('Content-type: text/html');

$ok_master = true;
$ok_slave  = true;
$ok        = true;
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <title>GLPI Monitoring</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2 font style="trebuchet"><img src="pics/logos/logo-GLPI-500-blue.png" alt="" width="100" height="50%"/> Monitoring</h2>
    <p></p>        
  <p></p>    
  <table class="table">
    <thead>
      <tr>
        <th style="font-size:18px">Service</th>
        <th style="font-size:18px">State</th>
      </tr>
    </thead>
    <tbody>
	<tr>
        <td>GLPI_Database</td>
        <td><?php
		if (DBConnection::establishDBConnection(false, true, false)) {
   echo "<img src='pics/new.png' />";
} else {
   echo "<img src='pics/redbutton.png' />";
   $ok_master = false;
}
?> </td>
        
      </tr>
      <tr>
        <td>GLPI_Tables</td>
        <td><?php
		if (!empty($crashedTables)) {
   echo "<img src='pics/redbutton.png' />";
} else {
   echo "<img src='pics/new.png' />";
   
}
?> </td>
        
      </tr>
      <tr>
        <td>GLPI Session Dir</td>
        <td>
		<?php 
		if (is_dir(GLPI_SESSION_DIR) && is_writable(GLPI_SESSION_DIR)) {
   echo "<img src='pics/new.png' />";
} else {
   echo "<img src='pics/redbutton.png' />";
   $ok = false;}?>
   </td>
     
      </tr>
      <tr>
        <td>Check LDAP servers</td>
        <td>
		<?php
		$ldap_methods = getAllDatasFromTable('glpi_authldaps', '`is_active`=1');

   if (count($ldap_methods)) {
      
      foreach ($ldap_methods as $method) {
         echo " ".$method['name'];
         if (AuthLDAP::tryToConnectToServer($method, $method["rootdn"],
                                            Toolbox::decrypt($method["rootdn_passwd"],
                                            GLPIKEY))) {
            echo "<img src='pics/new.png' />";
         } else {
            echo "<img src='pics/redbutton.png' />";
            $ok = false;
         }    
      }

   } else {
      echo "No LDAP server\n";
   }?>
   </td>
   <tr>
   <td>Check IMAP servers</td>
        <td>
		<?php
		$imap_methods = getAllDatasFromTable('glpi_authmails', '`is_active`=1');

   if (count($imap_methods)) {
      
      foreach ($imap_methods as $method) {
         echo " ".$method['name'];
         $param = Toolbox::parseMailServerConnectString($method['connect_string'], true);
         if ($param['ssl'] === true) {
            $host = 'ssl://'.$host;
         } else {
            if ($param['tls'] === true) {
               $host = 'tls://'.$host;
            }
         }
         if ($fp = @fsockopen($host, $param['port'],
                            $errno, $errstr, 1)) {
            echo "<img src='pics/new.png' />";
         } else {
            echo "<img src='pics/redbutton.png' />";
            $ok = false;
         }
         fclose($fp);
      }

   } else {
      echo "No IMAP server";
   }?>
   </td>
     </tr>
	 
	 <tr>
   <td>Check CAS_SERVER</td>
        <td>
		<?php
		if (!empty($CFG_GLPI["cas_host"])) {
      echo "CAS_SERVER";

      $url = $CFG_GLPI["cas_host"];
      if (!empty($CFG_GLPI["cas_port"])) {
         $url .= ':'.intval($CFG_GLPI["cas_port"]);
      }
      $url .= '/'.$CFG_GLPI["cas_uri"];
      $data = Toolbox::getURLContent($url);
      if (!empty($data)) {
         echo "_OK";
      } else {
         echo "_PROBLEM";
         $ok = false;
      }
     
   } else {
      echo "No CAS server<br />";
   }?>
   </td>
     </tr>
	 
	 <tr>
   <td>Check mailcollectors</td>
        <td>
		<?php
		$mailcollectors = getAllDatasFromTable('glpi_mailcollectors', '`is_active`=1');
   if (count($mailcollectors)) {
      $mailcol = new MailCollector();
      foreach ($mailcollectors as $mc) {
         echo " ".$mc['name'];
         if ($mailcol->getFromDB($mc['id'])) {
            $mailcol->connect();
            if ($mailcol->marubox) {
               echo "<img src='pics/new.png' />";
            } else {
               echo "<img src='pics/redbutton.png' />";
               $ok = false;
            }
            echo "<br />";
            $mailcol->close_mailbox();
         }
      }

   } else {
      echo "No mail collector\n";
   }
   ?>
   </td>
     </tr>
	 
	 <tr>
   <td>Check Crontasks</td>
        <td>
		<?php
		$crontasks = getAllDatasFromTable('glpi_crontasks',
                                     "`state`=".CronTask::STATE_RUNNING."
                                      AND ((unix_timestamp(`lastrun`) + 2 * `frequency` < unix_timestamp(now()))
                                           OR (unix_timestamp(`lastrun`) + 2*".HOUR_TIMESTAMP." < unix_timestamp(now())))");
   if (count($crontasks)) {
         foreach ($crontasks as $ct) {
         echo " ".$ct['name']."<img src='pics/redbutton.png' />";
         $ok = false;
      }
   } else {
      echo "<img src='pics/new.png' />";
   }

   // hook for plugin
   $param = array('ok' => $ok);
   Plugin::doHook("status", $param);
   if (isset($param['ok'])) {
      $ok = $param['ok'];
   }
   ?>
   </td>
     </tr>
	
<tr>
   <td>Check Slave DB</td>
        <td>
		<?php
		if (DBConnection::isDBSlaveActive()) {
   $DBslave = DBConnection::getDBSlaveConf();
   if (is_array($DBslave->dbhost)) {
      $hosts = $DBslave->dbhost;
   } else {
      $hosts = array($DBslave->dbhost);
   }

   foreach ($hosts as $num => $name) {
      $diff = DBConnection::getReplicateDelay($num);
      if (abs($diff) > 1000000000) {
         echo "GLPI_DBSLAVE_${num}_OFFLINE";
         $ok_slave = false;
      } else if (abs($diff)> HOUR_TIMESTAMP) {
         echo "GLPI_DBSLAVE_${num}_PROBLEM";
         $ok_slave = false;
      } else {
         echo "GLPI_DBSLAVE_${num}_OK";
      }
   }
} else {
   echo "No slave DB";
}
   ?>
   </td>
     </tr>

	
	  <tr>
   <td>Check GLPI</td>
        <td>
		<?php
		if ($ok) {
   echo "GLPI <img src='pics/new.png' />";
} else {
   echo "GLPI<img src='pics/redbutton.png' />";
}
   ?>
   </td>
     </tr>
      </tr>
    </tbody>
  </table>
</div>

</body>
</html>

**Comment by remicollet** [comment]
This page is designed to be called by monitoring tool, so HTML doesn't male sense.

**Comment by satyan01** [comment]
just to help.
