### ISSUE TITLE
Entity, catalog

### ISSUE THREAD

**Issue by orlapez** [glpi-project/glpi#2023]
Greetings community.
Is it possible that in the request for incidents and requirements, the end user, can choose the entity, subentity, and categories and subcategories of the catalog? That Catalan is dependent on entities and sub-entities?
How can I achieve this functionality?
Thank you very much for your ideas.

**Comment by trasher** [comment]
Hi,

You'd better use forums to ask such questions; see http://forum.glpi-project.org/
