### ISSUE TITLE
Mailcollector rule does not assign entity as expected

### ISSUE THREAD

**Issue by wanderleihuttel** [glpi-project/glpi#2024]
I'm using the defaults rules of maillcollector (Auto-Reply X-Auto-Response-Suppress and Auto-Reply Auto-Submitted) and Root I disabled.
```---------------------------------------
I create a new one:
Name = User Profile
Active = yes
---------------------------------------
Criteria
Requester exists - yes
---------------------------------------
Action
Entity based on user's profile - assign - yes
---------------------------------------
```
The email user is correct (exist), the user has an entity default (Root entity), but the ticket is not opened.

In Receivers -> List of not imported emails I get the message
"Unable to affect the email to an entity."

Best Regards
Wanderlei

**Comment by arthurrschaefer** [comment]
After a lot of tests I realized something.
To have the tickets forwarded to the correct entity you have to do this.
All my clients has the Self-Service profile, so I did that

- Create a new rule with the operator "e", 
Criteria 
"User featuring the profile"         "is"             "self-service"

Actions
"Entity based on user's profile"	"Assign"	"Yes"


Testing all of these I realized that when you force the rules to look for the user's profile, GLPI assume the Entity that the user is assigned.
If you use rules that analyze "subject", "from", or "to" headers. Or even when the ticket is sent to a mail collector, the rule don't put the ticket inside the user's entity.
I really don't know if it's a bug or it's made to be like this.

But to have the tickets being forwarded to the correct entity of my users and also allow annonymous ticket creation, I had to create two rules after Auto-Reply X-Auto-Response-Suppress and Auto-Reply Auto-Submitted and before the Root. I called it Each entity with the following content:
![2017-04-18 11_53_09-glpi - rules](https://cloud.githubusercontent.com/assets/13874922/25137435/24741396-242e-11e7-8602-16d1e5f849ff.png)
![2017-04-18 11_53_34-glpi - rules - 72](https://cloud.githubusercontent.com/assets/13874922/25137436/247a02e2-242e-11e7-907a-3cfd1cae0050.png)
![2017-04-18 11_53_55-glpi - rules - 3](https://cloud.githubusercontent.com/assets/13874922/25137437/24831738-242e-11e7-9d54-c74344f5af62.png)


Now, when the e-mail is from a known user, the ticket is opened and assigned to the correct entity, when the e-mail is unknown, it's opened in root entity.

**Comment by jaisonbenvenutti** [comment]
I have the same problem that you reported in this topic and I got around it as Arthur said, but I will need the other rule to work.
Could you tell me if it really is a bug?

**Comment by cconard96** [comment]
I recently made a fix for another issue with mail headers in rules. Can you try the changes made in #10338 to see if it resolves this issue too?
