### ISSUE TITLE
 GLPI Does Not Display Save Button on Simplified Interface

### ISSUE THREAD

**Issue by lklsr** [glpi-project/glpi#2028]
Good morning, after performing a check with the system in production I noticed that when accessing an open call in GLPI the save button is not displayed when sending a new file on the ticket home page. Is it possible to insert the same in the source code? It is worth remembering that in the standard the button is normally displayed as per the attachment.

![image](https://cloud.githubusercontent.com/assets/18348158/24908316/ebcf7d5c-1e95-11e7-9e1e-81afe6b7c66a.png)

**Comment by lklsr** [comment]
![image](https://cloud.githubusercontent.com/assets/18348158/24908339/0bd2ccee-1e96-11e7-87b1-8194199f4e68.png)

Default interface

**Comment by trasher** [comment]
It sounds like something that already have been fixed. As you did not specify the GLPI version you use, try with the latest stable release, ans if opssible make a test with the 9.1/bugfixes branch.

**Comment by lklsr** [comment]
Hello, the version used is 9.1, I tried to update to 9.2 on a VM and the problem continues, however this only happens with the simplified interface, the defaul displays normally.

**Comment by trasher** [comment]
I guess you want to say you're using 9.1.1 and you tried to update to 9.1.2 (9.2 does not exists yet).
Please try to update to 9.1/bugfixes (future 9.1.3) and see if problem persists.

Thank you.

**Comment by lklsr** [comment]
Sorry hahahaha the version used is 9.1.1 but I did the update for 9.1.2 and even then the problem continues.

**Comment by trasher** [comment]
And with the 9.1/bugfixes branch?

**Comment by trasher** [comment]
ping?

**Comment by lklsr** [comment]
Sorry, I just forgot to answer here. Is it necessary to install the composer for this version to upload?

**Comment by trasher** [comment]
Yes, you will need composer to install 3rd party libs

**Comment by lklsr** [comment]
![image](https://cloud.githubusercontent.com/assets/18348158/25390850/149c7ca6-29ab-11e7-8fe8-694b25054c03.png)

Is there any preference to install? I am trying to install via Xampp and even after installing the program the following error message is displayed

**Comment by trasher** [comment]
You have to install composer (see http://getcomposer.org) and run the command it gives you in the glpi directory.
Anyways, 9.1.3 will be out at the end of the week, you will be able to test it. We're freezing code today anyways, if your issue is not yet solved, it will not be in 9.1.3

**Comment by lklsr** [comment]
Thank you very much
