### ISSUE TITLE
[9.1.2] backslashes replaced in ticket description

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#2031]
Hi
When users gives an local url (or any url containing backslash) in a ticket description (send by mail to the mail support) (i.e. : C:\Windows\system32), Glpi replaces the backslashes with no character so for the i.e. above it gaves : C:Windowssystem32

**Comment by trasher** [comment]
This is the same issue as #1944

**Comment by trasher** [comment]
Did a mistake, this is not the same, looks like specific to the mailgate.

**Comment by wanderleihuttel** [comment]
Hello 
I've tested this and it looks is working fine!
#### Email 
![email](https://cloud.githubusercontent.com/assets/16232272/25016618/352a96b8-2057-11e7-8481-f2c040ef3358.png)

-----------------------------------------------------
#### Ticket
![ticket](https://cloud.githubusercontent.com/assets/16232272/25016625/3b08b754-2057-11e7-8212-610c6e8f2996.png)


Best regards
Wanderlei

**Comment by trasher** [comment]
Thank you for testing @wanderleihuttel :) Could you please precise wich GLPI version you used? 

@sebfun please prcise GLPI version as well.

**Comment by wanderleihuttel** [comment]
Hello @trasher  ! Sorry, I forgot to inform.
I'm using the version 9.1.2. 

Best regards
Wanderlei

**Comment by sebfun** [comment]
Hello @trasher it's 9.1.2 as i said in the subject of this topic :)

**Comment by tomolimo** [comment]
Hello,
I've got the same issue, and here are the steps to reproduce:

1. start ticket creation:
![image](https://user-images.githubusercontent.com/7569958/28834461-97415b70-76e2-11e7-9adf-70345c8dd71c.png)
2. add text in the title and description like below:
![image](https://user-images.githubusercontent.com/7569958/28834575-e22d3456-76e2-11e7-948c-c4a44909d8fd.png)
3. change the ticket type, and then after the 'postback':
![image](https://user-images.githubusercontent.com/7569958/28834635-19341b2c-76e3-11e7-838d-d4d3e5997cde.png)

And then backslashes have disappeared.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I made another test without any plugins, and the issue is still there

**Comment by tomolimo** [comment]
I found culprit code:
It's in ticket.class.php in the showForm() method:
```
if (isset($values['content'])) {
         // Clean new lines to be fix encoding
         $order            = array('\\r', '\\n', "\\");
         $replace          = array("", "", "");

         $values['content'] = str_replace($order,$replace,$values['content']);
      }
      if (isset($values['name'])) {
         $values['name'] = str_replace("\\", "", $values['name']);
      }
```
here: on 9.1/bugfixes branch: https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/ticket.class.php#L3754

**Comment by tomolimo** [comment]
Same issue with GLPI 9.1.6, I made a test with 9.1/bugfixes branch

**Comment by tomolimo** [comment]
To be noted: this issue occurs only at ticket creation, when the title or the description of the ticket are filled in before setting Ticket Type, or Ticket Category, or Ticket Requester (i.e.: each time there is a postback of the page), as described here: [steps to reproduce]( https://github.com/glpi-project/glpi/issues/2031#issuecomment-319415443)

This doesn't occur at ticket 'Add', when fields are set in the correct order (i.e.: from top left to bottom right) as the title and description are filled in after the postbacks.
