### ISSUE TITLE
Unlocking item locked by myself, doesn`t lock this item in the first tab

### ISSUE THREAD

**Issue by balucha** [glpi-project/glpi#2037]
Example.
I open Computer in first tab
I open same Computer in second tab - GLPI warn me "Item locked by you! UNLOCK Computer #xxxx" 
I unlock Computer 
I switch back to first tab and I can update computer because GLPI doesn`t lock it.

**Comment by tomolimo** [comment]
Hello,
That's normal, you should refresh your first tab if you want to view that it's locked now.
Regards,
Tomolimo

**Comment by balucha** [comment]
If I forged refresh? I have opened many tabs and someone(something) disturb me.

GLPI allow update in tab1 and this is a problem. GLPI must show warning and not update item when I click on Save button in tab1

Problem is, that if I make update in tab1 and than in tab2, update in tab2 rollback update in tab1.

**Comment by trasher** [comment]
Since you have unlocked; GLPI cannot prevent anything; that sounds legit, and this is not a bug (not something we can change as far as as know).

**Comment by tomolimo** [comment]
Hello again,
Yes there is a possibility to poll the "lock" from an editing page, but it will load the network and the database and the web server for a small gain. But anyway if we do this, the only possible thing will be to alert (via a dialog box) the end-user that the page has been unlocked, and that the current content may be lost.
Regards,
Tomolimo

**Comment by balucha** [comment]
Alert  when I update item (after clicking on Send button) in tab1 is enough.

**Comment by tomolimo** [comment]
I don't agree for the only alert after click on save button, as in this case what to do with what has been input in the form? For me the alert should be permanent and it must prevent submitting of the unlocked form.
