### ISSUE TITLE
Phone template disappears after using it

### ISSUE THREAD

**Issue by czernedo** [glpi-project/glpi#204]
You first create a phone template and save it.
After using this template to create a new phone, the template disappears from "choose a template"-list.
In the list of your phones, the created phone is listed twice instead.

**Comment by orthagh** [comment]
I can't replicate this issue.
Could you precise the values you input in your phone template ?

You can also switch to debug mode in your preference and in template selection page, open "See GLPI Debug" (in bottom left corner) to retrieve generated sql query (it should be the second query)

**Comment by yllen** [comment]
I can't reproduce this issue.
You have a post in the forum for gabarit of monitor: http://forum.glpi-project.org/viewtopic.php?id=130933
Are you the author?

**Comment by orthagh** [comment]
no answer...
I close, please use the forum to detail your issue
