### ISSUE TITLE
can`t view "Alternate username" at  "Assets -> Global" tab

### ISSUE THREAD

**Issue by eye-v** [glpi-project/glpi#2044]
Hi.
I`ve experienced some troubles at "Assets -> Global" tab.

**Bug description:**
When we add field "Alternate username" to "Default items to show", then "Assets -> Global" page becomes empty and even button "Select Default Items to Show" missing (so we can`t delete this "Alternate username" from view, it can be deleted only directly from DB table).
if "Debug mode" is turned on we can see error at the SQL query that tells us that field "glpi_softwarelicenses.contact" is missing in the table "glpi_softwarelicenses".

**Steps to reproduce bug:**
1) Go to "Assets -> Global" tab
2) Hit "Select Default Items to Show"
3) Add "Alternate username" to view and close floating tab.

GLPI version is 9.1.2
**sys info:**
Operating system: Linux XXXXX 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64
PHP 7.0.15-0ubuntu0.16.04.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, libxml, mbstring, mcrypt, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml,
	xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="180" memory_limit="512M" post_max_size="256M" safe_mode="" session.save_handler="files"
	upload_max_filesize="150M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at x.x.x.x Port 80)
Server Software: (Ubuntu)
	Server Version: 5.7.17-0ubuntu0.16.04.2
	
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK

Thanks. Best Luck.

**Comment by trasher** [comment]
Duplicates #1329 ;)

**Comment by eye-v** [comment]
oh sorry I haven`t finded it :)
Thanks.
