### ISSUE TITLE
Problem when executing the rules with ticket actors

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#2047]
Version GLPI 9.2 & 9.1.X

When updating a ticket, if the players have already been added, they are not included in the criteria of the rule.

Example : 
![rule1](https://cloud.githubusercontent.com/assets/15138371/25043470/8e648c56-2120-11e7-9a29-f5636bf26f2d.png)

**Example 1 with rule 1** : 
- Creating a new ticket with a category "Category 1"
- Update ticket for the "High" impact field
- The ticket goes into rule 1 and assigns SLA 1 => OK

**Example 2 with rule 1** : 
- Creation of a new ticket with a category "Category 1" and of the impact field to "High"
- Update the ticket with the remove of the SLA.
- Updating the ticket with the modification of the description. No action in the rules. => OK

![rule2](https://cloud.githubusercontent.com/assets/15138371/25043590/4f888540-2121-11e7-81b3-75118095eee4.png)

**Example 3 with rule 2** : 
- Creation of a new ticket with a category "Category 1" and of the impact field to "High"
- Update of the ticket with the addition of the group of technicians «Group 1»
- The ticket goes into rule 2 and assigns SLA 1

**Example 4 with rule 2** : 
- Creation of a new ticket with a category "Category 1" and addition of the group of technicians "Group 1"
- Update ticket for the "High" impact field
- The ticket does not pass in rule 2 whereas the three criteria are present. he worry is that when updating a ticket it is the users and / or groups already added to the ticket, they are not present in the input when checking the criteria.

**Comment by trasher** [comment]
Proposed fix cause issues... Reopening.
