### ISSUE TITLE
Different user on document attachment (mailgate)

### ISSUE THREAD

**Issue by augustoferronato** [glpi-project/glpi#2050]
Hello, 
When i sent a mail to open a ticket, and contains an attachment, the GLPI create the document with a different user, like in image
![glpi_anex_another_user](https://cloud.githubusercontent.com/assets/13663686/25111802/8b4cf364-23c3-11e7-9e9f-f9f44dfaf236.PNG)

Is this a normal behavior?

**Comment by JREA1** [comment]
Hello,

I have the same problem, this behavior is not normal.

**Comment by trasher** [comment]
This duplicates #1476 that have already been fixed for 9.2 (will not be in 9.1.x because it requires a schema change).
