### ISSUE TITLE
Users can upgrade theirs rights

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#206]
If a user have a profile with UPDATE on users, he can add to his account all profiles and all entities.
It seems there is an issue in function Profile::getUnderActiveProfileRestrictRequest() (called by profile::currentUserHaveMoreRightThan() )

ths problem is in the first lines of the function ( https://github.com/glpi-project/glpi/blob/master/inc/profile.class.php#L416-L442 ) who currently return false.
If i comment theses lines, i retrieve the expected behaviors (restricted list of profiles and entities)

**Comment by yllen** [comment]
This issue doesn't exists in 0.85. So i must find which change in 0.90 done this issue.
If you comment first lines, entity is restrict to the current but you can give higher profile like super-admin

**Comment by orthagh** [comment]
In 0.85/bugfixes branche, i have also this issue

**Comment by yllen** [comment]
Orthagh, i think a have find the solution. Can you test it?

**Comment by orthagh** [comment]
seems good.

**Comment by yllen** [comment]
great!
