### ISSUE TITLE
Full richtext support in GLPI

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2066]
Hello,

Having richtext editor throughout GLPI could be really useful : 

![image](https://cloud.githubusercontent.com/assets/12936546/25228630/6a26b498-25cd-11e7-84bc-5646c40c9270.png)

Especially in tasks, followups, problems and solutions. The add of images directly in core text could be a real nice feature too.

I hope you can add it in a future version of application. 

Thanks

**Comment by wawax** [comment]
Hello,

This is already implemented in GLPI 9.2

**Comment by trasher** [comment]
And there already is a rich text editor; you just have to active it in the configuration (setup > General > Assistance, see "Use rich text for helpdesk")

**Comment by ciadch** [comment]
Awesome. Thank's mate. I already use richtext for helpdesk but effectively, this feature for all application would be realy nice. I enjoy it !
