### ISSUE TITLE
Bug in display when "vertical split" is in use

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2068]
Hello,

It's seems there's a bug with "Actor" part when vertical split is set :

![image](https://cloud.githubusercontent.com/assets/12936546/25228907/72d73de6-25ce-11e7-921d-2137343012c3.png)

I try with Chorme and Firefox, same behaviour. 

Thanks

**Comment by trasher** [comment]
Hi,

You're talking about the width for this part?

**Comment by ciadch** [comment]
Yep, on the left side of the form, Actor is "shifted" to the right

**Comment by trasher** [comment]
Yes, I've recently seen this issue... This happens also on default view on "small" screens... This table has a fixed width :'(

**Comment by trasher** [comment]
Looks like it has already been fixed. Could you please test with 9.1/bugfixes branch?

**Comment by ciadch** [comment]
Sorry, same but with 9.1/bugfixes

**Comment by trasher** [comment]
Weird :/ I do not have the problem on the 9.1/bugfixes:
![nodisplaybug](https://cloud.githubusercontent.com/assets/224733/25231285/9b8356ae-25d7-11e7-9193-4c4a0838626f.png)

Did you clean your browser cache?

**Comment by ciadch** [comment]
You're right ! Sorry I miss cache clearing ! Works perfectely like that !

**Comment by trasher** [comment]
Great, thank you for testing :)
