### ISSUE TITLE
Problem to attache a file to a followup of a ticket

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#207]
Each time when I want to attache a file in a Followup of a ticket I receive the message:
File too small -->  what is the limit and it is possible to change it?

GLPI 0.90  Browsers:  IE 11 or Firefos 41.0.2

**Comment by orthagh** [comment]
I can't replicate your issue.
And i don't find any message "File too small" in glpi sources.
Are you sure of this message ?
Could you provide a screenshot of error ?

**Comment by FRANCOIS50** [comment]
Herer is the screenshot:
![capture](https://cloud.githubusercontent.com/assets/12511115/10761033/dac7454a-7cbf-11e5-9a41-f29b41f054b6.PNG)

**Comment by orthagh** [comment]
Can you open your dev tools on your browser (F12) and in console tabs, report here any errors that triggers on file upload ?

**Comment by orthagh** [comment]
Any errors in glpi/files/_log/*.log or in apache error log are interesting

**Comment by FRANCOIS50** [comment]
Here is the error log of php:
2015-10-27 15:47:36 [1446@CHMS000A]
  *** PHP Warning(2): filesize(): open_basedir restriction in effect. File(C:\Windows\Temp\phpBCC7.tmp) is not within the allowed path(s): (C:\inetpub)
  Backtrace :
  :                                                  
  ...ry-file-upload\server\php\UploadHandler.php:261 filesize()
  ...ry-file-upload\server\php\UploadHandler.php:349 UploadHandler->get_file_size()
  ...ry-file-upload\server\php\UploadHandler.php:891 UploadHandler->validate()
  ...y-file-upload\server\php\UploadHandler.php:1147 UploadHandler->handle_file_upload()
  front\fileupload.php:80                            UploadHandler->post()

**Comment by orthagh** [comment]
have you change your server configuration (php.ini).
This error seems related to server problem not glpi

**Comment by FRANCOIS50** [comment]
Thanks for your answer.
I deactivated the open_basedir var and now it works.
Thank you again for you help.
The Issue can be closed
