### ISSUE TITLE
Include parameter in TinyMCE init for not create <p> tags automatically

### ISSUE THREAD

**Issue by wanderleihuttel** [glpi-project/glpi#2072]
I would like to suggest to include in file "inc/html.class.php" in "$js = "tinyMCE.init" for not create <p> tags automatically.

#### Without the option "forced_root_block", by default TinyMCE use &lt;p&gt; tag.
````<p>Hello World</p>````

#### With the option "forced_root_block = ''", TinyMCE do not include &lt;p&gt; tag. 
So the text keeps like the original written.
````Hello World````

Source:
https://www.tinymce.com/docs/configure/content-filtering/#forced_root_block

Best regards
Wanderlei

**Comment by trasher** [comment]
Not sure I understand... When using "source" view from tinymce, you can write exactly what you want, anything will be added.
Seeing a WYSIWYG editor automatically adding tags sounds kind of legit to me :) So... 👎 for me.

**Comment by wanderleihuttel** [comment]
Hello @trasher ! Sorry If I wasn't clear.

By default in TinyMCE the root block is a tag &lt;p&gt; &lt;/p&gt;. If I click in the button to show the source code, after type some text, TinyMCE automatically add to my text the "root block". It included a tag that I didn't type
![tiny1](https://cloud.githubusercontent.com/assets/16232272/25526104/735b832e-2be8-11e7-95e2-63d09edc4625.png)

And if the option "forced_root_block = ''" is added, the TinyMCE did not include the tag in my text.
![tiny2](https://cloud.githubusercontent.com/assets/16232272/25526103/735ad28a-2be8-11e7-828f-ee268f13b1ed.png)

This is the option that should be included
![html_class](https://cloud.githubusercontent.com/assets/16232272/25526393/b94723ec-2be9-11e7-91d0-1113a17f7d18.png)

I guess with this option, TinyMCE keeps the text more pure as was typed.

Best regards
Wanderlei

**Comment by tomolimo** [comment]
Hello

Be aware that <P> has not the same visual effect than </BR>
<P> is a paragraph
</BR> is a linefeed \n (or carriage return + linefeed \r\n)
and usually a <P> means a bigger space between paragraphs than </BR>

regards
Tomolimo

**Comment by trasher** [comment]
@wanderleihuttel I'm sorry, but I still not understand the need :)

The rich text editor acts just like LibreOffice writer or other word processing program. Your phrase belongs per default to a paragraph, and hitting enter gives you a new paragraph.
If you want a carriage return, you have to hit shift+enter.

This seems to me the expected behavior... Also the display shows well what have been done (spacing between paragraphs etc).

I do not agree with this change.

**Comment by trasher** [comment]
I've asked to other GLPI devs, they do not agree with this change. Closing

**Comment by wanderleihuttel** [comment]
Hello

That's the point @tomolimo! The TinyMCE always include one new paragraph even I don't want one!
If I need a text with a break line with less space (</br>) actually is not possible, because of <p> tag included by default.

You always can input a new paragraph using the menu: Formats -> Blocks ->Paragraph.

With this option the texts will be more pure.

Best regards!

**Comment by tomolimo** [comment]
try shift+Enter, it usually input a BR instead of a P

**Comment by wanderleihuttel** [comment]
It includes a &lt;br/&gt; inside a &lt;p&gt; but I guess this can be helpfull.
