### ISSUE TITLE
Get validity date from LDAP

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#2074]
Get the validity date from LDAP and store it in user table

**Comment by AnaelMobilia** [comment]
@wawax Are you speaking of the account validity date (after which AD user will be locked) ?

Regards,
Anael

**Comment by wawax** [comment]
Hi @AnaelMobilia , I'm talking about this attribute, in case of AD : https://msdn.microsoft.com/en-us/library/ms675098(v=vs.85).aspx

Walid.
