### ISSUE TITLE
I see new ticket with a link on a computer in tickets list page , but not in the computer.

### ISSUE THREAD

**Issue by johannsan** [glpi-project/glpi#2078]
Hello,

This is the continuation of the discution 
 https://github.com/glpi-project/glpi/pull/2070#discussion_r112637354

Hello,
with a profile like "technician", I see tickets when I'm in glpi_tickets_users or when the ticket is new, but I don't see all tickets :
image
![image](https://cloud.githubusercontent.com/assets/6028912/25269742/3ced6e98-267e-11e7-90e5-045c577ae6d9.png)

with this correction : https://github.com/glpi-project/glpi/pull/2070#discussion_r112637354
you have solved the first problem (line 5241) : 
https://github.com/glpi-project/glpi/pull/2070/commits/9ab6970e6983e84ad08c2be2dd6910c79e5e48d0

But, In own configuration: 
-  I haven't he right 'READALL'
- I have the rights : "see my tickets"
- I have the rights: assign (to assign new tickets)

So, in tickets list page : 
I don't see all tickets.
I see new tickets (for assign to me, to my group or other person) (I think because right "Ticket::ASSIGN:") : https://github.com/glpi-project/glpi/blob/9.1.2/inc/ticket.class.php#L273-L274
I see my ticket

In computer page, I don't see the new ticket on this computer

It's for this case, I think you have to add the two lines in ticket.class.php / showListForItem(): 
if (Session::haveRight(self::$rightname, self::ASSIGN))
{
$restrict .= "OR (glpi_tickets.status=".self::INCOMING.")";
}

(like https://github.com/glpi-project/glpi/issues/1916)

Thanks

**Comment by orthagh** [comment]
Hum.
You're right after some verifcation.
I confirm from the pov of search class: https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/search.class.php#L2699-L2709

**Comment by yllen** [comment]
I'm not agree with this change. Now, in the Ticket tab of an item (not only computer), you see ALL tickets with incoming status even if the ticket hasn't the item in selected element.
http://forum.glpi-project.org/viewtopic.php?id=157592

**Comment by yllen** [comment]
With https://github.com/orthagh/glpi/commit/63db42cfae25cee810b9def25bf395855c6d6529 deleted, i see my new tickets in tickets tab of an item, like in ticket list

**Comment by trasher** [comment]
@yllen there is already another ticket opened (#2151), and a PR submitted (#2158)! Please do *not* commit directly.

**Comment by trasher** [comment]
Commits have been reverted. Please continue discussion on opened pull request.

**Comment by trasher** [comment]
Have been reverted.
