### ISSUE TITLE
Inventory > Phone IMEI

### ISSUE THREAD

**Issue by AlroneRhyn** [glpi-project/glpi#208]
Hi Guys !
Glad to see you on GitHub, and HUGE GG for your work.

I'm managing my phones throught GLPI. It would be awesome to add a IMEI field and to display it it the phone view. Serial number is OK, but IMEI is the new cellular serial.

It would be sweet to get a carrier field too (Vodaphone, Orange.... and simfree, obviously).

Thx a lot !

**Comment by wawax** [comment]
Hi AlroneRhyn,

We've opened a new suggestion request website : http://suggest.glpi-project.org 
There're a suggestion for including the simcard plugin into the core : http://glpi.userecho.com/topic/840666-integrate-simcard-plugin-into-the-core/ 

It's more or less what you're asking for.
You can leave comments on the request

**Comment by AlroneRhyn** [comment]
Hi Wawax,
Simcard handle simcards. It will add the carrier support i guess. Good. 
I would like to handle my phone with IMEI number ( => https://fr.wikipedia.org/wiki/International_Mobile_Equipment_Identity).

Today i add the phone IMEI into the serial number field. And use the Inventory number field to nest the actual phone serial number. 

Thx!

**Comment by orthagh** [comment]
As @wawax , I suggest same: please use the [suggestion site](suggest.glpi-project.org)
Thus, all users can comment and votes.

Thanks
