### ISSUE TITLE
generate "Satisfaction survey" event, when ticket was Solved

### ISSUE THREAD

**Issue by EugeneSE79** [glpi-project/glpi#2080]
Dear GLPi user.

Is it possible to generate "Satisfaction survey" event, when ticket was Solved. But not closed by Requestor.

**Comment by orthagh** [comment]
Hello @EugeneSE79 

If your requesters don't close their tickets, you can force an autoclose after a delay.
You can setup this behavior in Administation > Entities, choose the entity to edit (generaly "Root Entity") and in Assistance tab, you'll find "Automatic closing configuration" parameter.
