### ISSUE TITLE
digital signature, using the user certificate

### ISSUE THREAD

**Issue by EugeneSE79** [glpi-project/glpi#2081]
Dear GLPi user.

Is it possible to sign Tickets, Change, Problems, by digital signature, using the user certificate?
Perhaps there are suitable plug-ins?

**Comment by wawax** [comment]
Hello,

Please vote for these suggestions if needed : http://glpi.userecho.com/topics/97-glpi-digital-signatures-firmas-digitales/ and http://glpi.userecho.com/topics/148-glpi-handwritten-signatures-biometric-signatures/ for example

Or add a new one.

Thank you.
