### ISSUE TITLE
Collector, category and default field

### ISSUE THREAD

**Issue by zoriax** [glpi-project/glpi#2084]
Hello,

Strange behaviour. When a ticket is automatically created by collector (email) and when I edit it, the **mandatory (from gabarit)** field "category" (directly inherited from entity), is not required when I edit and save the new ticket.

![image](https://cloud.githubusercontent.com/assets/12936546/25280742/447e0d84-26ab-11e7-93fb-0322a4558a8f.png)

In other words, I can save my ticket with this mandatory field empty "---" (?!?). If I create a new ticket whit the same gabarit, when I save it I have the "warning" message that some mandatory fields are missing.

Any suggestion ? 

Thanks

**Comment by orthagh** [comment]
Hello @ciadch 

As far i check in code, tickets created by mail collector don't have any templates applied
In fact, templates are applied:
- on ticket creation form (manual input in browser)
- after category selection (add and edition form)

templates are priorized in this order (if one founded, its the applied one): 
- category
- profile
- entity

I don't know how to adress the issue so.
Maybe we could save the last applied template for a ticket and force mailcollector to applied default template but in case of a mandatory field, it will refuse the ticket creation if missing

**Comment by ciadch** [comment]
Ok thank you for your reply. Let's wait to see :-). I'll be careful when ticket created from email collector.
