### ISSUE TITLE
Rework ticket solution

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2089]
Actually, there is no way to keep a solution for a ticket while adding a new one.
There also are queries in the logs table to get informations on the solution (see #1435).

We should rework entirely solution system to avoid that.

See also demand on userecho: http://glpi.userecho.com/topics/99-ticket-solution-history/

**Comment by trasher** [comment]
Also related: http://glpi.userecho.com/topics/82-record-the-user-who-solved-a-ticket/

**Comment by wawax** [comment]
Also related : 

- http://glpi.userecho.com/topics/217-add-solution-author-tag-to-notification-templates/
- http://glpi.userecho.com/topics/500-glpi-solution-inverse-buttons/
- Split solution field in 2 => http://glpi.userecho.com/topics/533-/

**Comment by tomolimo** [comment]
Could it be moved back to 9.2, if I push something till end of week?

**Comment by trasher** [comment]
We'd prefer not to add this for 9.2; features are freezed since end of June.

I'll branch 9.2 very soon; you can base any work on this on the master branch anyways ;)

**Comment by trasher** [comment]
Done
