### ISSUE TITLE
Ticket History management problem

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#209]
Hi
I work with GLPI 0.90 and according to this version all the texte situated between these two lines:
=-=-=-= Pour répondre par courriel, écrivez au dessus de cette ligne =-=-=-=
texte
texte
=_=_=_= Pour répondre par courriel, écrivez au dessous de cette ligne =_=_=_=
Will not be copied in the answer per mail to this followup.
My Mail system is Lotus notes 8.5
On each answer the texte is copied.
is there anything to change in the GLPI settings to activate this option
than you in advance for your help.

**Comment by yllen** [comment]
You have the text copied in your new follow-up?

**Comment by FRANCOIS50** [comment]
Yes right

**Comment by FRANCOIS50** [comment]
voici le texte que je reçoit lors d'une réponse au premier suivi:
![capture](https://cloud.githubusercontent.com/assets/12511115/10909082/b8122962-8236-11e5-8612-329af3e457f3.PNG)

**Comment by FRANCOIS50** [comment]
A little up !!!!!!!

**Comment by FRANCOIS50** [comment]
I wait to this issue to put version  0.90 in production. Could anybody help me or says me if he has the same problem with lotus Notes 8.5

**Comment by FRANCOIS50** [comment]
Is there anybody who have the same problem with Lotus Notes and GLPI

**Comment by FRANCOIS50** [comment]
A  up concernig this ticket

**Comment by ldcglpi** [comment]
Hi,

I have the same problem, 
my tests:
  - reponse from lotus notes ==> the history of mail is not deleted
  - reponse from other e-mail application ==> the history is deleted but the follow is added 2 times

thanks for your help
version's glpi: V 0.90.1

**Comment by cedric-anne** [comment]
Hi,

Could you try with one of the lastest release (9.2.4 or 9.3.1) ? 

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by nbriandvpf** [comment]
Salut / Hi ,

While searching for my "follow up by email" issue, I found this thread.
I have the same issue : Lotus notes email system, GLPI 9.3.3 .

If someone replies to a auto ticket notification, GLPI understands the email as a follow up of the current case, but it adds the full email content to the follow up.
Is there something I can do to have only the reply .
Here is an example : 

![image](https://user-images.githubusercontent.com/23081570/53579109-44a11600-3b79-11e9-94aa-a5ce76727c07.png)
