### ISSUE TITLE
Global search inside tickets 

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2092]
Hello,

It is not possible to search "inside" a ticket with global search enabled ? I try it but it returns all my tickets and not tickets with criterions in global search field. Here are my global configuration : 

![image](https://cloud.githubusercontent.com/assets/12936546/25338887/0de650d0-2901-11e7-8941-9b0974c89d49.png)

Any help would be appreciated.

Thanks

**Comment by trasher** [comment]
Hi,

Global search act just like default search in mot cases ("items seen" "contains" "your search").  So, you can for example seach in tickets descriptions; if you add the description field in tickets list.

**Comment by ciadch** [comment]
Ok thanks for your reply. But, in my case, if i look for a specific word inside my ticket, it returns every time all my tickets. Is it a normal behaviour ?

Thanks

**Comment by trasher** [comment]
I'd say no, this is not the expected behavior. Just tested with branch 9.1/bugfixes, global search is working as expected; I can't reproduce your issue.
Please try with that branch, and if it is still failing, give us more details on how to reproduce.

**Comment by ciadch** [comment]
So, I did some tests with bugfix branch (fresh install and application default values). I created two tickets with simple content and different values inside them : 
Ticket 1 : 
![image](https://cloud.githubusercontent.com/assets/12936546/25376280/dda45ec8-29a3-11e7-865c-1ff8005111c6.png)

Ticket 2 : 
![image](https://cloud.githubusercontent.com/assets/12936546/25376228/b9cd9230-29a3-11e7-9791-302dbdebd800.png)

Now, with global search, I try to find the word "Look", the result of global search is the following : 

![image](https://cloud.githubusercontent.com/assets/12936546/25376407/571ca224-29a4-11e7-9589-0e3c1dbeb3f5.png)

 But, with the word "test", the global search seems to work correctly : 

![image](https://cloud.githubusercontent.com/assets/12936546/25376431/72ce53be-29a4-11e7-93a1-c32991fec021.png)

For me, description is not included inside global search. Is it normal or not ?

**Comment by trasher** [comment]
> For me, description is not included inside global search. Is it normal or not ?

By default, descirption is not shown on tickets list. So, yes, this is normal. You have to add description on the ticjkets list fields to search into it.

**Comment by ciadch** [comment]
Ok I understand. But it could be really interesting to have different crierions for what we see in ticket list and where to look in global search. Maybe in next release ?

Thank you

**Comment by trasher** [comment]
You can open (if nothing exists yet) a suggestion on http://glpi.userecho.com; that would be a huge job anyways.

**Comment by ciadch** [comment]
Ok, yes I understand ! Thank you for your help and for taking time for me !
