### ISSUE TITLE
[REST API] no data with param with_devices

### ISSUE THREAD

**Issue by ymfinidori** [glpi-project/glpi#2094]
Hi,
since #2042 was resolved, i have now a new issue when i pass "with_devices" param, i get a http code to 200, with an empty reply. 
I can see this behaviour only on 4 servers on my DC (440 servs), all my servs are installed in the same way (FAI + puppet).

http://MYSERV/apirest.php/Computer/8792?expand_dropdowns=True&with_networkports=True&with_components=True&with_disks=True
=> 200
`{
  "is_recursive": 0,
  "date_creation": null,
  "operatingsystemarchitectures_id": "x86_64",
  "os_kernel_version": "3.16.0-0.bpo.4-amd64",
  "id": 8792,
  "entities_id": "inventory-srv01",
  "name": "serv-front06",
  "serial": "8T3SF4RZ4J",
  "otherserial": null,
...
`

http://MYSERV/apirest.php/Computer/8792?expand_dropdowns=True&with_networkports=True&with_components=True&with_disks=True&with_devices=False
=> 200
empty

_even if i pass True or False_

Can someone help me, are give me an advice to investigate ?

**Comment by trasher** [comment]
Hello,

First step is to check the logs; it may contains some notices/warnings/bad queries that could help understanding what's wrong.

**Comment by ymfinidori** [comment]
hi @trasher ,
ty for your advice, but which logs are you talking about, in my access log, there's no error, and i get an 200 http code.

**Comment by trasher** [comment]
Errors are not logged in access_log...

GLPI uses two log files in glpi/files/_log for php and SQL errors. System wide errors depend on your installation/configuration (maybe apache error_log, php-fpm's log file, ...).
For your issue, if there are errors, there will probably be in GLPI's log files.

**Comment by ymfinidori** [comment]
here is the error in php-error.log
`2017-04-25 09:51:38 [13@inventory-srv01]
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  inc/api.class.php:641                              
  inc/apirest.class.php:197                          API->getItem()
  apirest.php:47                                     APIRest->call()`

**Comment by orthagh** [comment]
Hello @ymfinidori 
Could you test the following correction: https://github.com/glpi-project/glpi/pull/2099/files

**Comment by ymfinidori** [comment]
Hi @orthagh ,
still doesn't work : 
`  *** MySQL query error:
  SQL: SELECT
                                       ipnet.`id`,
                                       ipnet.`completename`,
                                       ipnet.`name`,
                                       ipnet.`address`,
                                       ipnet.`netmask`,
                                       ipnet.`gateway`,
                                       ipnet.`ipnetworks_id`,
                                       ipnet.`comment`
                                    FROM `glpi_ipnetworks` ipnet
                                    INNER JOIN `glpi_ipaddresses_ipnetworks` ipadnet
                                       ON ipnet.`id` = ipadnet.`ipnetworks_id`
                                       AND ipadnet.`ipaddresses_id` = 
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 13
  Backtrace :
  inc/api.class.php:634                              
  inc/apirest.class.php:197                          API->getItem()
  apirest.php:47                                     APIRest->call()`

**Comment by orthagh** [comment]
@ymfinidori 

an additional test: https://github.com/glpi-project/glpi/pull/2099/commits/d96ae891fab5d73384879e795428755f4a93346d

**Comment by ymfinidori** [comment]
no change, except the fact that now, i have no errors in logs anymore.

**Comment by orthagh** [comment]
Ok.
I think we have a second issue so.
No errors in sql or php error log ?

**Comment by ymfinidori** [comment]
nothing at all, i have double check :(

**Comment by orthagh** [comment]
if you launch the query without the id (ex apirest.php/Computer/?expand_dropdowns=True&with_networkports=True&with_components=True&with_disks=True&with_devices=False), do you retrieve the problematic computers in the list ?

**Comment by trasher** [comment]
Is there something specific on those 4 servers? Something that exists only on those ones, or something that is missing... We cannot reproduce the issue :/

**Comment by ymfinidori** [comment]
@orthagh yes, he is in the list, (it's that way i get my full list, and then, i loop on this list to get devices).

@trasher , if there is, i didnot find it (yet). For me, all mys servs are installed with the same way (FAI, PUPPET) and i don't kown why i have a diff behaviour.

this is really problematic for me cause i build all my nagios confs from the data i can get with the GLPI API (so these 4 servs are no monitored )

**Comment by trasher** [comment]
> For me, all mys servs are installed with the same way 

It may be an hardware difference, or... Well, many, many things :/ If we're not able to reproduce, we cannot fix the issue.

**Comment by orthagh** [comment]
@ymfinidori how do you populate you computers in GLPI ? with fusioninventory ?
If yes, a xml of one of theses computer could help us to test your issue (if you could anonymise the data)

**Comment by ymfinidori** [comment]
Yes it's done via fusioninventory.
Here is an xml export : 
[export](http://wikisend.com/download/481966/inventory.xml)

**Comment by orthagh** [comment]
And ...


i have answer ...
![image](https://cloud.githubusercontent.com/assets/418844/25389536/32980c9a-29d1-11e7-9bda-a493c4e427e1.png)

We didn't ask you what's glpi version you are using, anyway

**Comment by orthagh** [comment]
And your fusion inventory **plugin** version

**Comment by ymfinidori** [comment]
you right, my bad, it was on the other ticket, i forget to copy/past here.
so : i use FusionInventory 9.1+1.0 and fusioninventory-agent 2.3.10 on debian

**Comment by orthagh** [comment]
and for glpi ?

**Comment by ymfinidori** [comment]
9.1.2

**Comment by orthagh** [comment]
ok, i just have fusioninventory 9.1+1.1 but i think it's not the issue.

i'm clueless at the moment.

**Comment by trasher** [comment]
Hum... Is it possible that faulting servers have been initialy added with another version of glpi and/or fusioninventory plugin?

Do you have the possibility to remove one of those completely, and reimport it to see if that solves the issue?

**Comment by ymfinidori** [comment]
> Hum... Is it possible that faulting servers have been initialy added with another version of glpi and/or fusioninventory plugin?
that's the fact, i migrate from 0.9x to 9.1.2, so your intuition is right.
I allready remove the server (and his componants) from GLPI, and run a fresh **fusioninventory-agent -f** to re-import data, i can see the server with a new ID, but still have an empty reply when i whant to access info via rest-api (only with "with_devices" param, if i remove this param i get a full reply)

**Comment by trasher** [comment]
OK, so this is not the issue... Sorry, but I'm also out of ideas for the moment :/

**Comment by jmiler** [comment]
Hi
I also have the same problem with REST API:

I was trying to get information about devices connected to my host with this query:
	http://glpi_address.example.com/apirest.php/Computer/2838?session_token=SESSION_TOKEN&app_token=APP_TOKEN&with_devices=true
Response from GLPI was: HTTP 200 - no data

Log level is set to: "Complete (All)" and "Logs in files (SQL, email, automatic action...)" is set to True. I was looking in logs: php-errors.log, sql-errors.log and event.log. There was no results related to issue.
I cannot see any big differences between good hosts and bad hosts.

Also I was trying to completely remove host and add it again. Behavior was still the same.

Only a few percent of hosts is affected by this issue.
GLPI version is: 9.1.1 and Fusion Agent version is: 2.3.21.
In my sever room I am using CentOS.
I want avoid upgrade of GLPI and Fusion agent.

Do you have any suggestions how to handle this situation?

**Comment by cconard96** [comment]
I cannot recreate the issue on latest GLPI 9.5 commit.
Issue seems stale unless someone encountered this issue on the newer version(s) of GLPI and can provide more information to try and recreate the issue.
