### ISSUE TITLE
 GLPI [9.1.3] Version question

### ISSUE THREAD

**Issue by CCoruble** [glpi-project/glpi#2098]
Hi,
Recently migrated glpi 0.83.2 => 9.1.2.
Working well except little bugs, I am interested in migrating to the 9.1.3 version but I got an important question :
Is the 9.1.3 Version **ONLY FIXING ISSUES** ? Or is there application / DB / ... changes ??

Really important to me to know this, will determine if we do the migration on our production or not.
(Ps: don't need the answer until 9.1.3 is out)

Thank you for all the job done !
Best regards

**Comment by trasher** [comment]
Hello,

The 9.1.3 release is a bugfix only. But since there were issues in the database... There are also changes on the db (2 missing fields and 2 duplicated search options in preferences -- see https://github.com/glpi-project/glpi/blob/9.1/bugfixes/install/update_911_913.php#L74 fr details).
