### ISSUE TITLE
Review count usage

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2100]
As of PHP 7.2, the `count()` function will throw a warning if parameter is not an array or an object that implements Countable.

**Comment by AnaelMobilia** [comment]
@trasher & @orthagh  As a good practice and a way to "prevent" bad code, could we consider to add typehint on function signatures for the array params too ?
http://php.net/manual/fr/functions.arguments.php#functions.arguments.type-declaration 

It will provide a (catchable) fatal error if param isn't an array [on the meaning, it's better to stop if params isn't what is attended than trying to run code with bad arguments]

Too, it will ease this review as we can't imagine all call case from the function signature (I tried too... ;-))

Regards,
Anael

**Comment by trasher** [comment]
Guess count issues has been addressed since almost 2 years.

@AnaelMobilia typehinting will be added on current master, but this is not directly related to the counts usage.
