### ISSUE TITLE
Add group as watcher to simplified interface

### ISSUE THREAD

**Issue by dan723** [glpi-project/glpi#2108]
Hi
GLPI 9.1 - How can i add a group as watcher when i create a ticket in the simplified interface?

Thanks

**Comment by trasher** [comment]
Hello,

You can use templates to pre-select an watcher group.

**Comment by dan723** [comment]
Hi, 
In this way i would have to pre-selected a group as watcher, what i need is the possibility to select with a "dropdown" a group as watcher in the simplified interface.

Thanks

**Comment by trasher** [comment]
So you'd better open a subject (if it does not exists yet) on suggestions site: http://glpi.userecho.com/
