### ISSUE TITLE
Unappropriated BUS ID informations for a manufacturer

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#2111]
Version 9.1.x or 9.2

When displaying a manufacturer's form, they're bus ID information.
This information is not relevant, as it's only use for PCI or USB component.

It should not be displayed.

**Comment by orthagh** [comment]
I'm not sure about the drop of the feature.
It concerns effectly only pci/usb devices

But the relation is really on the manufacturer not the device only.

We retrieved the original commit.
See this part:
https://github.com/glpi-project/glpi/commit/e9100dad09be215f3f56e88ab3c05fe6627a2d25#diff-ce919f16d0b1900d5fe9830a7ad133deR38

which mention theses lists:
- http://pciids.sourceforge.net/v2.2/pci.ids
- http://www.linux-usb.org/usb.ids

Actually it serves only PCI/USB but it target RegisteredID class which can be extended if needed for other id (network ?)
