### ISSUE TITLE
SQL request on "ALL"

### ISSUE THREAD

**Issue by CCoruble** [glpi-project/glpi#2112]
Hello,

I made a research on ticket, by searching "test" on "All". (All contains test)

The query took so long and so much ressources, CPU were at 100% while RAM was fine.
I wanted to know if it's normal that it take so long to search and take that much ressources. 
I found the query that mysql is doing when searching with "All".
This might be a stupid question but is there any way to make it more efficiencient / optimised ?

(PS: Who the hell did this query ? Is this even human ??)

Best regards.

**Comment by trasher** [comment]
You can't expect a such complex query to be executed quickly. Searching on "all" will query many tables.
Be more restrictive in your search.

You can also consider to contribute and rework the search engine; that is a quite complex part. 

Regards
