### ISSUE TITLE
Add new parameter in My settings: see task to do on central

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2119]
http://forum.glpi-project.org/viewtopic.php?id=157524

The request is justified for task without planning.
Add a new parameter to allow display or not in central My view.
Display only task in status To do

You opinion?

**Comment by Armin83** [comment]
It would be great!

-  sometimes i miss the plan date 
- or i set wrong plan date 

i never look at my tickets with processing planned state and so it would be better for correct handling.

There are some other bugs also https://github.com/glpi-project/glpi/issues/1792

**Comment by tomolimo** [comment]
Duplicates #484
