### ISSUE TITLE
mail receiver issue

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2122]
Hello

I started my receiver this morning and I have this bug

PHP Notice: Undefined variable: doc in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php at line 2575
Fatal error: Uncaught Error: Call to a member function find() on null in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php:2575 Stack trace: #0 C:\inetpub\wwwroot\glpi\inc\commondbtm.class.php(4721): Toolbox::convertTagToImage('<div class=&...', Object(Ticket), Array) #1 C:\inetpub\wwwroot\glpi\inc\commonitilobject.class.php(1238): CommonDBTM->addFiles(Array, Array) #2 C:\inetpub\wwwroot\glpi\inc\ticket.class.php(1780): CommonITILObject->post_addItem() #3 C:\inetpub\wwwroot\glpi\inc\commondbtm.class.php(865): Ticket->post_addItem() #4 C:\inetpub\wwwroot\glpi\inc\mailcollector.class.php(588): CommonDBTM->add(Array) #5 C:\inetpub\wwwroot\glpi\front\mailcollector.form.php(81): MailCollector->collect('2', 1) #6 {main} thrown in C:\inetpub\wwwroot\glpi\inc\toolbox.class.php on line 2575

**Comment by satyan01** [comment]
however tickets have been correctly created

**Comment by wanderleihuttel** [comment]
What version are you using?

Wanderlei

**Comment by trasher** [comment]
@wanderleihuttel this is only on master branch (future 9.2).

**Comment by AnaelMobilia** [comment]
@trasher Issue could be closed ?

Regards

**Comment by trasher** [comment]
Yes, this has been fixed, thanks
