### ISSUE TITLE
Some tickets notifications are not sent

### ISSUE THREAD

**Issue by dan723** [glpi-project/glpi#2132]
Hi
Glpi 9.1 notification used to works fine, then it  just stop sending some ticket  notification not all.
For example is sending notification  for a new ticket but not for a ticket resolution.
I check the mail queue is empty and in the /var/log/maillog there are no mail sent when I resolve a ticket.
I couldn't find anything in the logs. I tried to upgrade to the version 9.1.2 but the problem still exist. 
Any idea about this issue?
Thanks

**Comment by Armin83** [comment]
Did you change your notification configuration ?

**Comment by dan723** [comment]
No, I didn't .
It just stop working and I can't find the issue

**Comment by Armin83** [comment]
No bug - for me it is working. For support you should use http://forum.glpi-project.org/

1. Do you use "direct send" setting or mail queue ?
2. Debug mode on and test it. What error do you get ?

**Comment by dan723** [comment]
Hi,

I don't know where to set "direct send" or "mail queue". email is configured in "notification" -> "email followup configuration"
In debug mode i can't see any error
Ok i will ask for support in http://forum.glpi-project.org/ 

Thanks

**Comment by Armin83** [comment]
ok then pls close this case.

you can find the setting "Delay before sending email notifications" here:
Home - Administration - Entities - Add

direct send = 0 minutes
mail quee if you define a value equal or higher 1 minutes

**Comment by roshanroche** [comment]
@dan723 hello. Did you find a solution for this issue.

**Comment by dan723** [comment]
Hello.

No I didn't
Any idea?

Thanks

**Comment by BICB4** [comment]
Got the same issue, some mail just aren't sent, started 4 days ago, there weren't any changes. I send them manually but that is not a fix, screened the last 2 cases, cron goes every minute, email is in the queue for over an hour, there isn't a number of tries. Haven't found anything in the logs.


![008578ab-f709-4b46-8102-3129fbb6570e](https://user-images.githubusercontent.com/50747765/109715589-1f9a7000-7ba4-11eb-91e2-7f714f8dc76a.jpg)
