### ISSUE TITLE
[9.1.3] : rn is added after each line in ticket solution

### ISSUE THREAD

**Issue by ppenin** [glpi-project/glpi#2141]
When solving a ticket, rn is added after each line. See screenshot.
![solution](https://cloud.githubusercontent.com/assets/22499638/25619198/4ef4a1fe-2f4a-11e7-9e72-3a69a0b9a805.jpg)
This issue never happened with GLPI 9.1.2

**Comment by trasher** [comment]
Duplicates #1944
