### ISSUE TITLE
[9.13] Attached files don't open

### ISSUE THREAD

**Issue by JonnyB1438** [glpi-project/glpi#2144]
Hi,
Attached files don't open (error 500) after updating to version 9.1.3.

Thank you,
regards!

**Comment by trasher** [comment]
Please provide errors from logs.

**Comment by ladenree76000** [comment]
HI,
on my 9.1.3 instance everything look OK : 
ticket created with 9.1.2, files  added with 9.1.2 : OK : i can read files with 9.1.3
ticket created with 9.1.3, files  added with 9.1.3 : OK : i can read files  with 9.1.3
ticket created with 9.1.3(mailgate), files  added with 9.1.3(mailgate) : OK : i can read files  with 9.1.3

**Comment by JonnyB1438** [comment]
Hi,
i find errors in logs:
PHP Fatal error:  Uncaught Error: Call to undefined function utf8_decode() in /var/www/glpi/inc/document.class.php:474\nStack trace:\n#0 /var/www/glpi/front/document.send.php(60): Document->send()\n#1 {main}\n  thrown in /var/www/glpi/inc/document.class.php on line 474, referer: http://servername/glpi/front/ticket.form.php?id=54673

**Comment by trasher** [comment]
You're probably missing php-xml extension. This is related to #981, not an attached files issue.

**Comment by JonnyB1438** [comment]
All right, thank you.
