### ISSUE TITLE
Groups in ticket tasks

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#215]

**Comment by tomolimo** [comment]
This is a great idea :)
Especially with a correct title :)

**Comment by orthagh** [comment]
See theses commits : 
* 28b02433b277e76a11b0f6063c4b858aeec478ed
* 0bf078d906303f9db1b243f0de90b55838e0311b
* b5ee92e137312407c76faefa4d5e82d1c0681f06
* e3360a7039882e38d453729986ef0a352f86e0c3

@yllen, could you attach future commits for this feature to this issue :)

**Comment by yllen** [comment]
You also have this issue https://github.com/glpi-project/glpi/issues/690

**Comment by orthagh** [comment]
Ok so i close this one
