### ISSUE TITLE
GLPI - 9.1.2 Rights issue - List of location is not visible in Standard Interface of Ticketing for Child Entities, same is visible in Simplified Interface.

### ISSUE THREAD

**Issue by ashvanisaini** [glpi-project/glpi#2150]
Rights issue - List of location is not visible in Standard Interface of Ticketing for Child Entities, same is visible in Simplified Interface.

We cannot see Child locations in Entities with tree Structure - only the parent entity location are being seen. 

Same is working correctly in the Simplified Interface of Ticket logging. Location list is seen easily.

**Comment by GuiBaeta** [comment]
Hi, I have the same problem. Did you get any solutions?

**Comment by cedric-anne** [comment]
@GuiBaeta 

Which version of GLPI do you use ?

Regards

**Comment by GuiBaeta** [comment]
GLPI 9.2.2

**Comment by GuiBaeta** [comment]
In the images have some of the locations and how the user is configured and creating called as admin and as end user.

As admin:
![como admin](https://user-images.githubusercontent.com/41923975/43466621-55238d7e-94b6-11e8-8f3d-36b6837a0892.png)

As a user:
![como usuario](https://user-images.githubusercontent.com/41923975/43466623-555b0d30-94b6-11e8-8ca6-b82777cd3db2.png)

The locations:
![localizacoes](https://user-images.githubusercontent.com/41923975/43466624-5581bd72-94b6-11e8-88c6-10385e876007.png)

The user permissions:
![permissoes do usuario](https://user-images.githubusercontent.com/41923975/43466625-55aa9c88-94b6-11e8-8e4f-4c64b9f9710b.png)
