### ISSUE TITLE
[9.1.3] Bug: you can see the open tickets in the tab of the tickets associated with the item

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#2151]
If you go to an item and select the tickets tab you can see the last 6 tickets opened + the number of tickets associated.

**Comment by trasher** [comment]
Could you please precise? I do not understand what the problem is.

Is it related to #1916 or #2078?

**Comment by jsamaniegog** [comment]
Ok, sorry, i try again:

1. Go to an asset.
2. Click on tickets tab.
3. You will see open tickets that are not associated with the asset.

**Comment by ArriMa** [comment]
Me too, after upgrade to 9.1.3 the counter of linked ticket (showed in the TAB) are correct, but the list showed contains tickets that do not contain that object.

**Comment by ArriMa** [comment]
TEMPORARY WORKAROUND: click on "Show All" link, the list of ticket with that associated item is correct.

**Comment by yllen** [comment]
Not agree with the purpose of correction

`// in list of ticket linked to the object, i also display incoming ticket if i have correct right`
            `if (Session::haveRightsAnd(self::$rightname, [self::READASSIGN, self::ASSIGN])) {`
              ` $restrict .= " AND glpi_tickets.status = ".self::INCOMING;`
            `}`
           `$restrict .= ")";`

**Comment by tyronewyatt** [comment]
Is this another duplicate of https://github.com/glpi-project/glpi/issues/2135 ?

**Comment by trasher** [comment]
@tyronewyatt no; this is something else.

**Comment by yllen** [comment]
another post in forum: http://forum.glpi-project.org/viewtopic.php?id=157693

**Comment by trasher** [comment]
Original commit that cause the issue has just been reverted. This solves current issue.
