### ISSUE TITLE
[GLPI API] New feature: Do action as an other user

### ISSUE THREAD

**Issue by ToToL** [glpi-project/glpi#2153]
Hello,

I use the API through an "admin" account to do not have to manage all GLPI token of each users.

I can't find out how to do action "as a specific user". Even if I force some parameters, actions are done with my admin account.

Is it possible to add a new function to do action as an other user (if I have the right to do this of course) or to change my active user for another ?

Thanks

Reagrds

**Comment by trasher** [comment]
Hi,

Please use suggestions website for new features: http://glpi.userecho.com/

Regards,
