### ISSUE TITLE
Associate phone to a ticket

### ISSUE THREAD

**Issue by ArriMa** [glpi-project/glpi#2155]
Hi,
I'd like to know if is possible link phone asset to a ticket.

In the combo "Associated elements" I can't see phone item. In the phone item instead there is the ticket TAB... but it shows many tickets that I don't understand why are referenced by that phone.

Are there any configuration to enable phone to be linked to a ticket?
Thanks.

**Comment by Armin83** [comment]
Go to
- Home
- Administration
- Profiles
- _the profile you want to change_

At the setting _Associable items to a ticket_ is typ phone missing

**Comment by tyronewyatt** [comment]
The tickets appearing in the phone ticket tab might be related to https://github.com/glpi-project/glpi/issues/2135 if running GLPI 9.1.3

**Comment by ArriMa** [comment]
Thank you @Armin83, I knew that was someware that, but can't rembember where. Now I have enable, and now I'm able to link phone in ticket.

@tyronewyatt: Yes the problem is present after upgrade to GLPI 9.1.3, see ticket #2151 
Thanks!
