### ISSUE TITLE
Editing a followup shouldn't change its original author

### ISSUE THREAD

**Issue by nbriche** [glpi-project/glpi#2161]
When followup is edited, the original author's identity is lost, replaced by the last editor.
This is problematic when followups are mainly generated by mail, which are usually riddled with signatures and reply headers, that are (or would be) cleaned up afterwards by IT.

**Comment by trasher** [comment]
User is changed when a task is edited as well

**Comment by tomolimo** [comment]
We should be able to view author and last modifier.

**Comment by trasher** [comment]
Doing so would be an enhancement, not a bugfix; but why not...

**Comment by tomolimo** [comment]
Yes I agree that's an enhancement, but I was just reacting to this issue. But of course it should be on user echo.
