### ISSUE TITLE
HTTP_REFERER.

### ISSUE THREAD

**Issue by menvol3** [glpi-project/glpi#2167]
Hello,

after step 1 (database access) I get redirected and immediately encounter the following error page:
None or Invalid host in HTTP_REFERER. Reload previous page before doing action again.

i do it on Winginx, PHP ver 5.4.45

**Comment by ddurieux** [comment]
**nginx on windows is not stable...**

in your nginx conf, you need add:
```
fastcgi_param  SERVER_NAME      $host;
```

**Comment by menvol3** [comment]
**here is my nginx.conf

can you please help, where i must add this line**


`
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid        temp/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    client_max_body_size 55m;

    #gzip  on;

	scgi_temp_path  temp/uwsgi_temp 1 2;
	uwsgi_temp_path  temp/uwsgi_temp 1 2;

	fastcgi_connect_timeout 1;


	server {
		listen   127.0.0.1:80;

		root home/localhost/public_html;
		index index.php index.html;

		log_not_found off;
        charset utf-8;

		access_log  logs/access.log  main;

		location ~ /\. {deny all;}

		location / {

			if ($host ~ ^(www\.)?([a-z0-9\-\.]+)$){
				root home/$2/public_html;
				access_log  logs/$2-access.log  main;
			}

		}

        location ~ \.php$ {

			if ($host ~ ^(www\.)?([a-z0-9\-\.]+)$){
				root home/$2/public_html;
				access_log  logs/$2-access.log  main;
			}

			if (!-e $document_root$document_uri){return 404;}
			fastcgi_pass localhost:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

			include fastcgi_params;

        }
	}

	server {
		listen 127.0.0.1:443;
		include ssl.conf;

		root home/localhost/public_html;
		index index.php index.html;

		log_not_found off;
        charset utf-8;

		access_log  logs/access.log  main;

		location ~ /\. {deny all;}

		location / {

			if ($host ~ ^(www\.)?([a-z0-9\-\.]+)$){
				root home/$2/public_html;
				access_log  logs/$2-access.log  main;
			}

		}

        location ~ \.php$ {

			if ($host ~ ^(www\.)?([a-z0-9\-\.]+)$){
				root home/$2/public_html;
				access_log  logs/$2-access.log  main;
			}

			if (!-e $document_root$document_uri){return 404;}
			fastcgi_pass localhost:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

			include fastcgi_params;

        }
	}


	include tools-*.conf;

	include vhosts/*.conf;

}
`

**Comment by ddurieux** [comment]
The line before the `include fastcgi_params;`

**Comment by menvol3** [comment]
It needs to be done in 2 places?

**Comment by menvol3** [comment]
Did as you said, but the error is still the same

<a href="http://piccy.info/view3/11151071/f9f2c59787ada66793a0eaa2746d741d/" target="_blank"><img src="http://i.piccy.info/i9/9e26df932c76762f1f23df458931039d/1493994528/4857/1143244/Screenshot_1_500.jpg" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2017-05-05-14-28/i9-11151071/500x85-r" target="_blank"><img src="http://i.piccy.info/a3/2017-05-05-14-28/i9-11151071/500x85-r/i.gif" alt="" border="0" /></a>

**Comment by trasher** [comment]
This tracker is reated to GLPI issues, not nginx ones... Please use forums for support; and maybe ask to the nginx community to get you have this webserver up and running.

**Comment by Podolyan98** [comment]
I have the same problem that I described on the [forum](https://forum.glpi-project.org/viewtopic.php?id=280979). How should I configure nginx.conf?
