### ISSUE TITLE
Auto-submitted rejecting don't work in our environment

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2169]
Background:
- We send maintenance messages from it-support mailbox with outlook.
- We get at the moment oof tickets as response 👎 

Details:
**Rules configured**
![img_008](https://cloud.githubusercontent.com/assets/19192087/25770558/c08f7640-3238-11e7-92b6-690aaba4428e.jpg)

**Rules Test**
![img_009](https://cloud.githubusercontent.com/assets/19192087/25770559/c09068b6-3238-11e7-975e-ab53c3242f41.jpg)

**mailbox glpi import job log**
![img_010](https://cloud.githubusercontent.com/assets/19192087/25770560/c090e688-3238-11e7-948c-1d1c41b7e7c5.jpg)

**the new glpi ticket**
![grafik](https://cloud.githubusercontent.com/assets/19192087/25770554/a7c380f2-3238-11e7-9ac3-499a0d22e7d8.png)

**the auto respone mail from our oof**
- we have a outlook tool (not microsoft feature) but this tool use microsoft features and exchange server is the sending application. the tool only generate the message **
![img_007](https://cloud.githubusercontent.com/assets/19192087/25770607/265eedf6-323a-11e7-8290-e0ff02ab4e17.jpg)

**the original mail**
My subject i wrote is really "oof if support 0826" this was my test subject for oof glpi troubleshooting test ;)
![img_003](https://cloud.githubusercontent.com/assets/19192087/25770653/87e43404-323b-11e7-8db3-5ea6dcc447af.jpg)

**environment**
glpi version 9.1.2
ms exchange 2016  CU 3

**Comment by Armin83** [comment]
@orthagh is this issue solved with #2170 also ?

**Comment by orthagh** [comment]
your rule screenshoted here https://cloud.githubusercontent.com/assets/19192087/25770559/c09068b6-3238-11e7-975e-ab53c3242f41.jpg seems to be different than the provided one on glpi default installation.

Could you provide the criteria/actions for your rule ?

in #2170, i changed the check (i insist, for default installations ! ) on  `Auto-submited` header for the next regex: `/(?i)^(?!.*?no).*$/`
This regex valid any value different to "no" (case insensitive).
I you want, you may change in your current instance

**Comment by Armin83** [comment]
`

Auto-Submitted email header | regular expression matches | /\S+/
-- | -- | --
Auto-Submitted email header | is not | no

`

**Comment by Armin83** [comment]
Should i change to this ?

Logical operator: and

Auto-Submitted email header | regular expression matches | /(?i)^(?!.*?no).*$/
-- | -- | --
Auto-Submitted email header | is not | no

**Comment by orthagh** [comment]
Not really mandatory, in fact i changed two things:
- The rules had 2 criterias, 1 for no empty `Auto-Submited` header, and the other to check this header is different to No. I merged in one criteria
- in consequence, i changed global logical operator for this rule from AND to OR to permits checking some others headers (not added by the way).

But both versions are equivalent in behavior.

**Comment by orthagh** [comment]
Note, the provided regex is bad, it matches on empty string (or absent `Auto-Submitted` header)

Here is a fixed regex: `/^(?!.*no).+$/i`

**Comment by Armin83** [comment]
Both versions don't work on my system. (i'm happy the first one didn't because there is no Auto-Sumitted Header in normal E-Mail. We are using  Outlook & exchange)

![2018-02-26 22_05_00-](https://user-images.githubusercontent.com/19192087/36695377-6e6ab134-1b41-11e8-9cd7-a5bd6ed71868.png)

**Comment by Armin83** [comment]
Do you need an example mail ?

**Comment by orthagh** [comment]
yes, if you could, please send one on glpi-debug@teclib.com

**Comment by orthagh** [comment]
just received it. I don't know well outlook but could you "redirect" the direct mail on the above adress like a direct recipient ?
No forwarding, i mean.

Thereby, i could collect it in my glpi and check results with a real scenario.

**Comment by Armin83** [comment]
I believe i cannot redirect the oof message. If you can send from your glpi mail address to my mail address i send you in the test msg file (armin.....) you will get an oof message this week. ("Only" 1 per day!)

**Comment by orthagh** [comment]
will do now

**Comment by orthagh** [comment]
This mail is indeed refused, but i don't understand, is it not the attended behavior for oof mails ?

**Comment by Armin83** [comment]
Do you want to write "This mail is indeed **_not_** refused" or it is really refused in your system but why it don't work an my site ?

**Comment by orthagh** [comment]
yes it's refused on my local glpi with this rule:
![image](https://user-images.githubusercontent.com/418844/36893110-2887866a-1e07-11e8-8dbe-b0904c1b42c1.png)

No clue for your side by the way

**Comment by Armin83** [comment]
Which version do you use ? 
I have GLPI 9.1.2 at the moment.

**Comment by orthagh** [comment]
9.2/bugfixes branch (~= 9.2.2)
