### ISSUE TITLE
Missing glpi_entitites table from 0.72 to 0.90.1

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#217]
Upgrading a 0.72 database, the glpi_entities table is missing, as indicated by the following error message : 
0.90.1 multiple alter in glpi_entities - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_entities` ADD `inquest_duration` INT(11) NOT NULL DEFAULT '0' - L'erreur est Table 'glpi.glpi_entities' doesn't exist

**Comment by yllen** [comment]
Coorected: https://github.com/glpi-project/glpi/commit/be99771ab825c23c9d414ef941406bc6036a0f68

**Comment by wawax** [comment]
I confirm that it is now fixed.
Thank you yllen
