### ISSUE TITLE
change default rule Auto-Reply X-Auto-Response-Suppress

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2170]
We got problems with the default Auto-Response-Suppress Rule. There should be something changed.
If you have exchange (2016) and use a distribution list (witch member glpi mailgate mailbox) send a mail to distribution list this mail will rejected from this rule.

Name	   Auto-Reply X-Auto-Response-Suppress	
Description  Exclude Auto-Reply emails using X-Auto-Response-Suppress header	
Active	   Yes

Settings:
`X-Auto-Response-Suppress email header	regular expression matches	/\S+/`

I think there will be other constellations. You can read more about this topic there https://www.jitbit.com/maxblog/18-detecting-outlook-autoreplyout-of-office-emails-and-x-auto-response-suppress-header/

**Comment by orthagh** [comment]
Hello @Armin83 

Could you paste here a raw email sent to a list for investigation ?

Regards.

**Comment by Armin83** [comment]
Hello @orthagh 

i send you know a mail to your gmail address. I don't want to post my real business address here on github. You will get a mail with a zip file within 3 msg files.

Regards
Armin

**Comment by orthagh** [comment]
for reference: https://github.com/jpmckinney/multi_mail/wiki/Detecting-autoresponders

**Comment by orthagh** [comment]
i suggested to disable the rule on glpi install to avoid future issue with this.
Actually, existing glpi instances will still have the enabled rule, it's very difficult to update them.
