### ISSUE TITLE
[GLPI 9.1.3]  Calculation of TCO Monthly

### ISSUE THREAD

**Issue by o71** [glpi-project/glpi#2171]
Hello,

I don't know if this is a bug or if there is a reason to how to calculate the monthly TCO.

In the help it says  (in french : [link](http://glpi-project.org/DOC/EN/glpi/inventory_management.html)) :

TCO (value + amount of intervention): the total cost of ownership, which includes all components of a billed product;
Monthly TCO: TCO divided by the number of months between today's date and **the date of purchase** of the equipment;

But the calculation seems to be made from the start **date of the warranty** and not the date of purchase, is this a mistake or is there a reason for this?

Moreover, when there is no warranty start date, the TCO and the monthly TCO are identical.

On the other hand is it normal that the value of the extension of guarantee is not added to the value of the property to calculate the TCO?

Thank you for your explanations.

I opened a topic without answer [here](http://forum.glpi-project.org/viewtopic.php?id=157582)

**Comment by trasher** [comment]
Hi,

Iv'e a fix for the wrong date; but I realy do not know if the warranty must be added to the TCO; and I do not know who to ask.
Please open another ticket for this.

**Comment by o71** [comment]
Hello,

Thanks for the fix, I'll create another ticket for the TCO.

Bye

**Comment by trasher** [comment]
I reopen; ticket wil be closed when fix will be merged ;)

**Comment by o71** [comment]
Oh, I'm sorry.

Have a nice day

**Comment by trasher** [comment]
Merged :)
