### ISSUE TITLE
GLPI 9.1.3 : unable to create items of components

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2172]
Hi

I found it is impossible to create an item of any component from the UI

Steps to reproduce: 

- browse to Setup > Component. Open a component list, no matter its type
- create a  component and open it
- open the tab "Items", and try to create at least one item of the component
- see the creation fais

![image](https://cloud.githubusercontent.com/assets/14139801/25843283/33902912-34a7-11e7-932d-642d5bd65106.png)

![image](https://cloud.githubusercontent.com/assets/14139801/25843294/3961cde6-34a7-11e7-927c-18f434687836.png)

**Comment by trasher** [comment]
Bug introduced from #1816
