### ISSUE TITLE
[GLPI 9.1.4] Open ticket from item - Use entity of the item

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#2173]
Hello

I would like your opinion.

Context : 
- Multiples entities
A
->B (child)

I am positioned as a technician on the entity A
I open a computer of entity B
I open the Ticket tab from the computer & click on "open a ticket for this item"

Problem : 
The ticket form use the entity of the technician profile **A** & not the entity of the computer **B**

Do you think we could change that behavior? (We send a PR) Or you want to keep that behavior ?

BR

**Comment by trasher** [comment]
Hi,

This sounds legit to keep asset entity when opening a ticket for this one. 👍 for me; but I do not know if this is a bug or something that was expected.

**Comment by tsmr** [comment]
@orthagh your opinion ? Do you think that we can send a PR for this ?

**Comment by orthagh** [comment]
i agree.
As ticket are not recursive, we may have possible forbidden access with this behavior.
Let see your pr to discuss and test thoroughly.

**Comment by trasher** [comment]
@tsmr do you plan to send a PR for that? And do you still plan to get it form 9.1 series?

**Comment by trasher** [comment]
@tsmr ping?
