### ISSUE TITLE
[GLPI 9.1.4] Dropdown expired Contract

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#2177]
Hello 

For your opinion & a PR

in inc/contract_item.class.php from item you have : 
```
Contract::dropdown(array('entity'  => $item->getEntityID(),
                                  'used'    => $used,
                                  'expired' => false));
```

So you cannot link an item with a expired contract

But in a contract you can have a Tacit renewal, so you can link items even the contract is expired because there is a Tacit renewal

We can add a criteria into $query ?
```
if (!$p['expired']) {
         $expired = " AND (DATEDIFF(ADDDATE(`glpi_contracts`.`begin_date`, INTERVAL
                                               `glpi_contracts`.`duration` MONTH), CURDATE()) > '0'
                           OR `glpi_contracts`.`begin_date` IS NULL
                           OR (`glpi_contracts`.`duration` = 0
                               AND DATEDIFF(`glpi_contracts`.`begin_date`, CURDATE() ) < '0' ))";
      }
```

**Comment by trasher** [comment]
Well... I agree that contracts with automatic renewal should not be considered as expired.

Bu I guess the end date should be updated; checking for automatic renewal in the query would certainly solve the issue; but the end date of the contract seems wrong anyways :/
