### ISSUE TITLE
[API REST - 9.1.3] Problem with changeActiveEntities

### ISSUE THREAD

**Issue by Jonalex9020** [glpi-project/glpi#2178]
Hello,

I have a problem with the API REST.
I have a user, which is in the root entity, and it can access recursively to others

When i initiate session, I use the getActiveEntities endpoint to check in which entity i am, and the result is entity with id = 0

If I use the changeActiveEntities endpoint to id = 4, i have a "true" response from the server 

But, if I use the getActiveEntities endpoint to check in which entity i am, i'm still on the entity 0 and not on the 4

Have you got any idea to resolve this problem ?

Thanks in advance

**Comment by Jonalex9020** [comment]
nobody have this issue ?

**Comment by rledoigt** [comment]
I have the same kind of issue. Changing a user's entities_id or password apparently succeeds but the values are not changed in the database. 
On the other hand, modifying locations_id worked fine.
All those operations were performed with admin privileges (glpi account).
