### ISSUE TITLE
[API REST 9.1.2] Return incorrect information

### ISSUE THREAD

**Issue by jp-morvan** [glpi-project/glpi#2182]
Hi,

I use API for checking some informations and the return is not the value in database.

**Example :** 
I want to get a phone item with "name" field equals to "000121212". So, I use this curl query 

> curl -s -X GET 'https://myglpi/apirest.php/search/Phone?criteria\[0\]\[field\]=1&criteria\[0\]\[searchtype\]=contains&criteria\[0\]\[value\]=000121212' -H 'Content-Type: application/json' -H 'Session-Token: mytoken'

here is the return :
```
{
   "totalcount":1,
   "count":1,
   "sort":1,
   "order":"ASC",
   "data":[
      {
         "1":121212,
         "7":"",
         "70":null,
         "10127":null,
         "23":null,
         "40":null,
         "4":null,
         "31":null
      }
   ],
   "content-range":"0-0/1"
}
```

The value returned is "121212" and not "000121212" like in database or in GLPI UI. 
The problem exists on every item type.

Thank you

**Comment by ladenree76000** [comment]
i think my bug is the same : 
whatever  criteria[...][searchtype]  (0,1,2 ie : contains equals notequal) it behaves like "contains"

**Comment by golgoth31** [comment]
the  api use some json_encode options when returning resultes:
if ($response !== null) {
         $json = json_encode($response, JSON_UNESCAPED_UNICODE
                                      | JSON_UNESCAPED_SLASHES
                                      | JSON_NUMERIC_CHECK
                                      | ($this->debug
                                          ? JSON_PRETTY_PRINT
                                          : 0));

Remove "JSON_NUMERIC_CHECK" and the returning json will be only with strings. the drawback is taht some values will be unusable as is. example:
memory size before: 16000
memory size after: 16000.00000

**Comment by trasher** [comment]
I've not been able to find any correct solution to get that fixed right now :(

We'll certainly have to drop `JSON_NUMERIC_CHECK` anyways; but we'll have to type properly each value... Database results are _always_ text, we do not have any way to know/typehint values that are returned.

**Comment by Yoda-BZH** [comment]
A possibility: Add a method to each class that can return data through the API.

This new method would transform (if necessary) the returned fields to the target/desired format.

This way, JSON_NUMERIC_CHECK would be unnecessary.

**Comment by trasher** [comment]
> This new method would transform (if necessary) the returned fields to the target/desired format.

The `if necessary` part is the problem. We cannot know.

This would imply data types to be properly handled in the whole framework, this is a huge work (required for some other features like postgresql support). I'm not sure we can find a really good solution until that.

**Comment by Yoda-BZH** [comment]
I'd say it depends on the field type in the database.

But yeah it can be a huge work.

**Comment by trasher** [comment]
> I'd say it depends on the field type in the database.

Nope, most of the times, data retrieved are just strings, event if they're database integers (see unit tests, I has several issues regarding variables types).
