### ISSUE TITLE
HTTP_REFERER when try to install

### ISSUE THREAD

**Issue by menvol3** [glpi-project/glpi#2183]
Hi 
I am trying to install glpi on wnginx  and  after post where i must type my login to mysql database i receive this error 

<a href="http://piccy.info/view3/11166351/a64a3f099622bc95f30c5ceb8b23a4c1/" target="_blank"><img src="http://i.piccy.info/i9/b93ba2062b384aa0bcfc87c168269ea6/1494404510/3903/1144348/http.png" alt="Piccy.info - Free Image Hosting" border="0" /></a><a href="http://i.piccy.info/a3c/2017-05-10-08-21/i9-11166351/690x102-r" target="_blank"><img src="http://i.piccy.info/a3/2017-05-10-08-21/i9-11166351/690x102-r/i.gif" alt="" border="0" /></a>

**Comment by trasher** [comment]
See #2167. No need for a new ticket.
