### ISSUE TITLE
Clean old functions 

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2189]
Deprecated since 0.84
- closeArrowMassives 
- openArrowMassives
- showInteger
- showDateFormItem
- showDateTimeFormItem
- dropdownNoneReadWrite

Deprecated since 0.85
- displaySearchTextForDropdown
- getSearchTextForDropdown
- showAllItems

**Comment by yllen** [comment]
Plugins news https://github.com/glpi-project/plugins/wiki

**Comment by trasher** [comment]
Hello @yllen ; thanks for the wiki page, but the deprecated methods must be added in the CHANGELOG file doing the removal (see https://github.com/glpi-project/glpi/blob/master/CHANGELOG.md#api-changes), and we'll add a "migration guide" before releasing 9.2 on the developer docs based on the contents of the changelog.

**Comment by trasher** [comment]
I've opened several issues both on core and on plugins I've been able to identify:
https://github.com/glpi-project/glpi/issues/2394
https://github.com/glpi-project/glpi/issues/2396
https://github.com/glpi-project/glpi/issues/2399
https://github.com/glpi-project/glpi/issues/2400
https://github.com/glpi-project/glpi/issues/2409

`displaySearchTextForDropdown` and `getSearchTextForDropdown` have already been removed.

**Comment by yllen** [comment]
Done for function deprecated in 0.84.

Remains lock.class because @tsmr has commit a change https://github.com/glpi-project/glpi/commit/9d4d35517b929496e75c4fec0089d4b82c65d512#diff-835053cb01a8bfa3258568afcd7d22b9 and i don't understand what is delete permanently for lock tab

**Comment by trasher** [comment]
@tsmr ping?

**Comment by trasher** [comment]
Only closeArrowMassives and openArrowMassives are remaining. See dedicated ticket #2394
