### ISSUE TITLE
Bug in rights of ticket edite

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#2193]
Hi, 
when not rights of update ticket, I can update ticket in GLPI 9.1.3.
In GLPI 9.1.2 or last it was not.

**Comment by yllen** [comment]
This commit don't correct all problems (see my comments in commit)

**Comment by AircraftRu** [comment]
Hello. How do you do with solve the problem?

**Comment by trasher** [comment]
Hello, this is not fixed yet.

Regards
