### ISSUE TITLE
hourly ticket recurrent not respecting calendar

### ISSUE THREAD

**Issue by magaiverpr** [glpi-project/glpi#2194]
Hello!

I have a recurrent ticket that create a ticket each hour in commercial time. When time hits 18h, they keep creating the tickets, someday until 20h, someday until 3h. Next day they open the ticket in the hour I set correctly, is only when the time pass from the final time.

Time in server is correct, I have recurrent tickets that open daily and the time is ok.

`[code]
 
GLPI 9.1.2 ( => /var/www/html/glpi)

Server
 
Operating system: Linux servername 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bz2, calendar, ctype, curl, date, dom,
	ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, json, ldap, libxml, mbstring, mhash, mysql, mysqli, openssl,
	pcre, pdo_mysql, pdo_sqlite, session, shmop, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="6M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.16 ()
	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.6.27
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp/ : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.
OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.1.21 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/var/www/html/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/var/www/html/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/var/www/html/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.4.1 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi/vendor/ircmaxell/password-compat/lib)
ramsey/array_column in (/var/www/html/glpi/vendor/ramsey/array_column/src)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)

LDAP directories
 
"sensive information omitted"

		Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	news                 Name: Alerts                         Version: 1.3.2.5    State: Enabled
	autologin            Name: Autenticação Automática        Version: 2.1.1      State: Enabled
	addressing           Name: Endereçamentos IP              Version: 2.5.0      State: Not activated
	fusioninventory      Name: FusionInventory                Version: 9.1+1.1    State: Not activated
	mod                  Name: GLPI Modifications             Version: 1.0.3      State: Enabled
	showloading          Name: Mostrar Carregamento           Version: 1.0.0      State: Enabled
	browsernotification  Name: Notificação do navegador       Version: 1.1.2      State: Enabled
	dashboard            Name: Painel                         Version: 0.8.1      State: Enabled

[/code]`

**Comment by magaiverpr** [comment]
Prints attached.
![glpi - calendarios - 2 - google chrome1](https://cloud.githubusercontent.com/assets/10533823/25947954/03667502-3628-11e7-9454-49fb4d6c415b.jpg)
![glpi - chamados recorrentes - 2 - google chrome2](https://cloud.githubusercontent.com/assets/10533823/25947953/03663fce-3628-11e7-8fc8-45fb0d6eca56.jpg)
![glpi - chamados recorrentes - 2 - google chrome3](https://cloud.githubusercontent.com/assets/10533823/25947955/036d89f0-3628-11e7-871e-6ca7b84e8d99.jpg)

**Comment by vithort** [comment]
conseguiu resolver?

**Comment by magaiverpr** [comment]
Ainda não. Continuo na versão 9.1.6, irei atualizar esse mês e irei ver se continua o problema.

**Comment by vithort** [comment]
você usa mais de um calendário? tive o mesmo problema e vi que estava associado um Calendário de herança na Entidade.

Veja em: Administration > Entities > [YOUR ENTITY] > Assistance > Calendar.


Espero ter ajudado.

**Comment by magaiverpr** [comment]
Fiz a alteração e irei acompanhar hoje a noite.

Obrigado!

**Comment by trasher** [comment]
Please use english
