### ISSUE TITLE
Please help : i made a mistake by installing mod plugin

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2202]
Now I have this messager in php log increasing all the time php log file

I have deleted the plugin manually

2017-05-12 08:17:28 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined property: DB::$execution_time
  Backtrace :
  inc\dbmysql.class.php:193                          
  inc\commondbtm.class.php:263                       DBmysql->query()
  inc\plugin.class.php:236                           CommonDBTM->find()
  inc\plugin.class.php:115                           Plugin->checkStates()
  inc\includes.php:110                               Plugin->init()
  plugins\fusioninventory\index.php:49               include()

**Comment by wanderleihuttel** [comment]
Hello 
I don't know what mistake you did, but if is about the files, you can make a download of the same GLPI version and only extract again for overwritten the the files.

If is about database and you does not have a backup you can be in trouble.

Best regards
Wanderlei

**Comment by trasher** [comment]
This looks like an opcache issue after upgrading. Restarting PHP should solve.
