### ISSUE TITLE
Please add the words translation

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#2203]
GLPI 9.1.3
Hello,
not translated the words, example, Computers asset:

![glpi - computer - google chrome 2016-12-23 10 03 19](https://cloud.githubusercontent.com/assets/17082164/21448775/38af64c4-c8f7-11e6-9d56-2f766395ce8e.png)

In issue #1458  did not correct.

**Comment by trasher** [comment]
Indeed, I missed this part in the previous ticket; sorry.

**Comment by trasher** [comment]
Done for 9.2
