### ISSUE TITLE
 Screenshot pasted into a new ticket

### ISSUE THREAD

**Issue by bennijamm** [glpi-project/glpi#2204]
Hello,

I detected a bug when the user wants to paste an image into a new ticket:
Reproduction Protocol:
1. Create a new ticket
2. Paste an image into the drag and drop field + click the Save button to save the image
3. Choose a category for the ticket
=> There, the page reloads and the image disappears ...
When the ticket is recorded, the image is no longer attached.
The file "pasted _..." is always in the files \ _tmp directory of glpi.

Thank you

GLPI v 9.1.2

**Comment by trasher** [comment]
This has certainly been fixed since (many work has been done on 9.2 on this part)
