### ISSUE TITLE
impossible to create ticket

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2219]
Hello

glpi 9.2 master of 12.05.2017

2017-05-18 14:34:31 [539@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: tasktemplates_id
  Backtrace :
  inc\commonitiltask.class.php:1387                  
  inc\ticket.class.php:6801                          CommonITILTask->showForm()
  ajax\timeline.php:78                               Ticket::showSubForm()
2017-05-18 14:34:50 [637@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: login_remember_time
  Backtrace :
  inc\auth.class.php:817                             
  front\login.php:79                                 Auth->Login()
2017-05-18 14:36:25 [636@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: tasktemplates_id
  Backtrace :
  inc\commonitiltask.class.php:1387                  
  inc\ticket.class.php:6801                          CommonITILTask->showForm()
  ajax\timeline.php:78                               Ticket::showSubForm()
2017-05-18 14:38:16 [456@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: login_remember_time
  Backtrace :
  inc\auth.class.php:817                             
  front\login.php:79                                 Auth->Login()

**Comment by trasher** [comment]
Hi,

Once again, your database seems not te be up to date.

**Comment by satyan01** [comment]
What I have to do to fix it ?

**Comment by trasher** [comment]
Find missing tables/fields in the update script and and them to your database:
https://github.com/glpi-project/glpi/blob/master/install/update_91_92.php

**Comment by satyan01** [comment]
how to do $migration ?

 // #1476 - Add users_id on glpi_documents_items
   $migration->addField("glpi_documents_items", "users_id", "integer", ['null' => TRUE]);
   $migration->addKey("glpi_documents_items", "users_id");
   $migration->addPostQuery(
      "UPDATE glpi_documents_items GDI, glpi_documents GD SET GDI.users_id = GD.users_id WHERE GDI.documents_id = GD.id",
      "9.2 update set users_id on glpi_documents_items"
   );

**Comment by satyan01** [comment]
or how to play the entire update_91_92.php ?
