### ISSUE TITLE
Split view and monitoring plugin cause bug in central view

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#222]
Helloa, if i activate vertical split view, central page is bugging, no error appears in php-error.log, see screenshot below

![capture](https://cloud.githubusercontent.com/assets/6815687/10887026/3229c74e-8185-11e5-80ac-98b029623369.JPG)

**Comment by orthagh** [comment]
Hello @Sismic 
Could you test with current master ?

I can't replicate this issue.

**Comment by Sismic** [comment]
Yes, git pull of today ...
bug appears under FF, Chrom and IE

**Comment by orthagh** [comment]
which plugin add theses tabs on you screenshots ?

**Comment by Sismic** [comment]
monitoring plugin from @ddurieux , not really fully write for 0.90 but working

**Comment by Sismic** [comment]
no bug with classic view or tab view

**Comment by orthagh** [comment]
i confirm that monitoring plugin is in cause.
I currently search why.

**Comment by orthagh** [comment]
seems in plugins/monitoring/lib/scripts-1.js (concatened js of libs)

**Comment by orthagh** [comment]
we need a fix in monitoring plugin.
I close this issue.
I suggest to open issue in [monitoring github](https://github.com/ddurieux/glpi_monitoring/issues)
