### ISSUE TITLE
error in debug mode

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2221]
Hello 

When I create a taks I have this error in debug mode

PHP Notice: Undefined index: tasktemplates_id in C:\inetpub\wwwroot\glpi\inc\commonitiltask.class.php at line 1387

and during task cat creation

PHP Notice: Undefined index: knowbaseitemcategories_id in C:\inetpub\wwwroot\glpi\inc\commondropdown.class.php at line 296

**Comment by trasher** [comment]
same as #2219.

**Comment by satyan01** [comment]
you don't have any solution ?

**Comment by satyan01** [comment]
what I have to do to update the database ?

**Comment by satyan01** [comment]
Why do you close the issue if it is not solved ?

**Comment by trasher** [comment]
This is **duplicate**.
