### ISSUE TITLE
9.1.2 Anonymous ticket

### ISSUE THREAD

**Issue by HairullinRR** [glpi-project/glpi#2223]
Does not work anonymous tickets! (/front/helpdesk.php)
After the fields are filled, redirection takes place /index.php?redirect=%2Ffront%2Ftracking.injector.php
and the ticket is not created!
Allow anonymous ticket creation "Yes"

**Comment by yohanpelletier** [comment]
Hi, 
I have the exact same problem, are you find a solution ?

**Comment by Armin83** [comment]
If you have super-admin rights you can see this ticket.

**Comment by yohanpelletier** [comment]
Hi Armin, 

Thanks for your answer, but unfortunately I already have super-admin rights.

**Comment by Armin83** [comment]
And you super-admin profile is the active profile of your user ?
Please provide logs from debug mode. I think it could be a bug - but i can'r reproduce.

**Comment by yohanpelletier** [comment]
Yes, the super admin profile is active. 

Do you know where I have to go for find the debug mode ?

**Comment by Armin83** [comment]
user settings - click on your name (the active profile must be super-admin if you have more)

**Comment by yllen** [comment]
Version of GLPI used?
