### ISSUE TITLE
Add notes for project task

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2229]
#http://forum.glpi-project.org/viewtopic.php?id=157705
http://forum.glpi-project.org/viewtopic.php?id=157794

**Comment by speedlight** [comment]
Hope this can be solved, here at work we are still in 9.1.2 just for the notes in project tasks :) 
Best regards!

**Comment by yllen** [comment]
In 9.1.3, notes were presents in GLPI because of https://github.com/glpi-project/glpi/issues/1750
To add a new note, you don't need to change the database.
For users how used notes of project task in 9.1.3, i think it's better to include this in 9.1.5.
You opinion?

**Comment by trasher** [comment]
@yllen if there are no changes in the database, and if this is not something that would cause breakings (I don't think so); this is OK for me in 9.1.5.
@orthagh?

**Comment by orthagh** [comment]
Ok for me also

**Comment by yllen** [comment]
Thanks for users.
I must commit to 9.1/bugfixes or you do a cherry-pick?

**Comment by orthagh** [comment]
cherry-picked on 9.1/bugfixes
