### ISSUE TITLE
Add max-height to tooltips

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#2237]
Hi,

Sometimes the tooltips can be too big, so big in fact that they can not be closed. The screenshot below shows such a tooltip on the software search page.
It would be good to fix it to a maximum height like 10 lines (around 190px) and add a scrollbar if there's more content. 
![screenshot-192 168 12 254-2017-05-24-14-21-34](https://cloud.githubusercontent.com/assets/3509962/26403183/998df716-408d-11e7-9947-ce9e6888b738.png)

**Comment by pVesian** [comment]
I tried a fix, but the render is ugly because of qtip's `word-wrap: break-word`. 10 becomes 1 and 0 on two lines. It's ugly.
![screenshot-192 168 19 158-2018-05-05-18-54-34](https://user-images.githubusercontent.com/3509962/39665525-18a6cf32-5096-11e8-828f-6e1d56082197.png)

WIP:
```
diff --git a/css/styles.css b/css/styles.css
index 7c2f27546..fbc0b207a 100644
--- a/css/styles.css
+++ b/css/styles.css
@@ -1399,6 +1399,8 @@ td.rotate {
 /* ################--------------- User Picture ---------------#################### */
 .qtip {
    max-width: 380px !important;
+   max-height: 230px;
+   overflow: auto;
 }
 
 .tooltip {
```

**Comment by cedric-anne** [comment]
Maybe you should try with the [overflow-y property](https://developer.mozilla.org/fr/docs/Web/CSS/overflow-y).

**Comment by pVesian** [comment]
@cedric-anne It didn't help. I spent a while on this and found no solution except removing the `word-wrap: break-word` which causes problems if a version name is long.
