### ISSUE TITLE
[0.90] Bug - The ticket status is not set when updating a task

### ISSUE THREAD

**Issue by korial29** [glpi-project/glpi#224]

**Comment by korial29** [comment]
The ticket status is not set when updating a task

Must add the following lines in commonitiltask.class, function post_updateItem() : 
      //change ticket status
      if (isset($_REQUEST['_status']) && !empty($_REQUEST['_status'])) {
         $ticket = new Ticket();
         $ticket->update(array('id'     => intval($_REQUEST['tickets_id']),
                               'status' => intval($_REQUEST['_status'])));
      }

![image](https://cloud.githubusercontent.com/assets/12070735/10915195/04462b20-8256-11e5-9f1f-4f8474c8a9f6.png)

**Comment by yllen** [comment]
You should never use $_REQUEST in GLPI

**Comment by tomolimo** [comment]
Why?

**Comment by yllen** [comment]
commonitiltask.class is not only for ticket.
So 
$ticket = new Ticket();
$ticket->update(...)
it's not possible

**Comment by korial29** [comment]
I agree we should never use this global variable in a class. It should be handle in a front .form file. We must use the object "$this->input".
However i've copied the code set in commonitiltask.class, function post_addItem(), line 454
Thus the ticket is already updated in commonitiltask.class.php.
We should move this ticket update in tickettask.class.
I will suggest a fix for this

**Comment by tomolimo** [comment]
Ok thank you 
I understand now
And I totally agree 
Regards 
Tomolimo

**Comment by orthagh** [comment]
I cleaned in 2533d7b commit, the method to update ticket status from task (to respect GLPI standards).
Copied from followup changes in https://github.com/glpi-project/glpi/commit/5d549a060a97 (moreover, this part is "hidden" in an off topic commit/log message...)

IMO, status change must be in commonitiltask but without direct reference to Ticket class ('_job' is great).
Other Itilobjects doesn't support right now the display of submit button with status change but with the currend code in commonitiltask, we can easily add in near future the feature
