### ISSUE TITLE
RN's in solutions when you use hard enter

### ISSUE THREAD

**Issue by Hevelious** [glpi-project/glpi#2243]
When you use enter in Solution's description GLPI adds space and "RN" text in that place.
When you use soft enter (shift+enter) the problem doesn't exist. 

Same applies to templates of solutions.

GLPI version 9.1.3

It has been mentioned already:
https://www.bountysource.com/issues/42981056-tinymce-adds-cr-lf-to-its-return-content-that-will-be-transformed-to-rn-in-solution

**Comment by trasher** [comment]
Duplicates #1944
