### ISSUE TITLE
Add end date for waiting status of ticket

### ISSUE THREAD

**Issue by ddurieux** [glpi-project/glpi#2246]
New feature:

* Add a `end` date field when set ticket status to `pending`. 
* Add a new cron used to passe the tickets from status `pending` to `assigned` when the date expired
* Add an option in entity named `pending end date` to:
   * disable
   * 0 -> enable the end date field
   * values > 0 in days to have a max duration (so calculate the end date) per default of a pending status

**Comment by orthagh** [comment]
Front side, it could be great to reflect the max waiting duration in jquery ui datepicker:
https://jqueryui.com/datepicker/#min-max

**Comment by PierreTeclib** [comment]
Can you add "reason of waiting" or "type of waiting" like in the moreticket plugin ? 

So when a ticket is in "pending" status you can also add the reason why.

thks

**Comment by ddurieux** [comment]
Why not, seems a good idea, but for history, if the ticket pass more than 1 times in pending with a different reason, where store the information? logs? followups?

**Comment by PierreTeclib** [comment]
I think it can be in the logs and (like in Escalade plugin) add an option to put this in task ?

**Comment by ddurieux** [comment]
ok for options, but perhaps more in private followup than task

**Comment by PierreTeclib** [comment]
+1

**Comment by Armin83** [comment]
http://glpi.userecho.com/topics/213-pending-status-time-limit/

**Comment by lucascacardoso** [comment]
Any chance this new feature happen soon? It will be a huge help!!

**Comment by cedric-anne** [comment]
See #8706.
