### ISSUE TITLE
Browser will hang when in ticket description are the chars <-

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2247]
Hello,

This behavior has been tested with a bare (no plugin and default configuration) of GLPI 9.1.3

Needed:
1. Use rich text for helpdesk: Yes
1. A Receiver (POP)
1. An user with the email address of the email sender (to permit ticket creation)

Send to GLPI a plain text email containing this in description (email body), any subject:

> Hello,
> 
> <- blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla blabla

Get the email via the receiver, and open the newly created ticket. The browser will hang a long time depending on the length of the 'blabla' string... 

This issue has been tested with IE10, IE11, Chrome, Firefox, Opera: browser is hanging,
But with Safari: it opens correctly the ticket, with the correct string in the ticket description...

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
One more thing: there is no error in GLPI logs.

**Comment by cedric-anne** [comment]
Should be fixed by #9011.
