### ISSUE TITLE
PLanning

### ISSUE THREAD

**Issue by AliouneDiop** [glpi-project/glpi#2248]
Dear GLPi user.
Hi
MY problem is only user with a super admin profile can see all tasks on planning. I granted to different profiles the right to see all planning but it s not working .If a task is assigned to a group too it wont be visible on the planning. I am using GLPI 1.9.3.
Thanks

**Comment by Armin83** [comment]
You know you have to select the group or user in planning view to see it in "your planning"
![planning](https://cloud.githubusercontent.com/assets/19192087/26600697/4ec162fa-457d-11e7-972a-66e7b95bbd7f.JPG)

(And you have to plan the task, but if you see the correct task in super_user it can't be this problem)
![plan a task](https://cloud.githubusercontent.com/assets/19192087/26600885/0b369d1a-457e-11e7-9f47-04f83d8a0e03.JPG)

**Comment by AliouneDiop** [comment]
Thanks for clear answer. After assigning a task to the user and adding the user in the planning I am able to see the task after some minutes.
When I assigned a task directly to a group without selecting a user and adding the group to the planning, I wont be able to see the task of the group in the planning. See attached files

![group](https://cloud.githubusercontent.com/assets/29062043/26619555/3651cfea-45df-11e7-81b1-3f141f645c48.JPG)
![groupplanning](https://cloud.githubusercontent.com/assets/29062043/26619554/3650cafa-45df-11e7-8998-4aee1970ea96.JPG)

**Comment by Armin83** [comment]
take care of the difference 
![task-view](https://cloud.githubusercontent.com/assets/19192087/26647514/e3403920-463f-11e7-820c-577b6b7951c5.JPG)
![tasks](https://cloud.githubusercontent.com/assets/19192087/26647513/e33f7ec2-463f-11e7-98e3-b5be6fc50c36.JPG)

**Comment by AliouneDiop** [comment]
Thanks for your support.Is it possible to display the name of person who the task was assigned?

**Comment by Armin83** [comment]
No, you can only see the user who did the last change . Please close this issue. 

For the next time please use system for appropriate request.
Support http://forum.glpi-project.org/
Bug Report https://github.com/glpi-project/glpi/issues
Feature Request https://glpi.userecho.com/

**Comment by trasher** [comment]
Thank you @Armin83
