### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by AliouneDiop** [glpi-project/glpi#2253]
Dear GLPi user.

I am using the new version of GLPI 1.9.3 but since I installed it ,it s impossible to sent a notification  All is well set but nothing is sent.
Thanks

**Comment by AliouneDiop** [comment]
![capture](https://cloud.githubusercontent.com/assets/29062043/26629020/e2237dca-4600-11e7-84b0-b084fc1f85f7.JPG)
![error](https://cloud.githubusercontent.com/assets/29062043/26629019/e219447c-4600-11e7-937d-aa9c990ad3a8.JPG)
All mails are stored in the mailqeue and when you send one, there is an error

**Comment by trasher** [comment]
There is an error with your SMTP, this is not related to GLPI.

Double check your configuration, and checks logs on your mail server side.
