### ISSUE TITLE
[9.2.1] Notes don't change "Last update" of problems

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2257]
Hello,

In GLPI 9.1.3, we notice that adding notes on problems don't change "Last update" field of problems. Moreover in "Historical", you see updates on "Last edit by" and "Note" fields.

Steps to reproduce : 
1. Notice value of "Last update" field on an existing problem
2. Add note on this problem
3. Notice value of "Last update" field on this problem

=> You can see that date don't change.

**Comment by yllen** [comment]
You don't change the problem.
It's the same comportment with a document.

**Comment by nqb** [comment]
To my mind, adding a note on problem is a change. State of problem has changed.

Why do you distinguish elements that update or not "Last update" field ?

**Comment by nqb** [comment]
Issue still presents in 9.2.1.
