### ISSUE TITLE
[9.2.1] French translation of status in changes

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2258]
Hello,

In GLPI 9.1.3, translation of "Test" status for changes is "Tester" in French. Should be "Testé", like "Appliqué" for "Applied".

See in /var/www/glpi/locales/fr_FR.po : 
```
#: inc/change.class.php:482
msgctxt "change"
msgid "Test"
msgstr "Tester"
```

**Comment by wawax** [comment]
Hello,

Thanks for your feedback. The translation process is done through transifex : https://www.transifex.com/ 
You can register and fix the label by yourself.

Regards,

**Comment by trasher** [comment]
Hello,

I wonder if there is not an issue in the original string as well. I do not agree to translate "test" by "Testé" (would be "Tested"). But since this is a state; I guess we should use "Testing" as the original string (which would be  translated in french as "En test" or something similar).

**Comment by nqb** [comment]
We need to make a choice. Which one ?

**Comment by nqb** [comment]
With GLPI 9.2.2, "Testing" is not translate as "En test".

**Comment by trasher** [comment]
Locales has not been updated yet

**Comment by nqb** [comment]
Done in transifex.

**Comment by nqb** [comment]
In GLPI 9.2.2, Testing is now translate as "En test".
