### ISSUE TITLE
PHP Notice:  Constant GLPI_ROOT already defined

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#226]
in .../inc/includes.php on line 38
When opening index.php

https://github.com/glpi-project/glpi/commit/bd76e2426ce5d9ccf40104bdf938d0f3a079c0e1#diff-d0a743c66d90c74b4c7fe9667b7df844R35

we need to review top of index.php or revert this code in includes
```
 if (!defined('GLPI_ROOT')) {
```

**Comment by tsmr** [comment]
Same problem on logout & central.php

**Comment by ladenree76000** [comment]
same problem on webservices : see :http://forum.glpi-project.org/viewtopic.php?id=130320

**Comment by tsmr** [comment]
Same problem
[06-Nov-2015 09:04:14 Europe/Paris] PHP Notice:  Constant GLPI_ROOT already defined in C:\wamp\www\glpi90\inc\includes.php on line 38

**Comment by remicollet** [comment]
Full backtrace ?
Line 38 is the fixed one.
Check your git clone.

**Comment by tsmr** [comment]
No full backtrace it's on error_log of apache
My master is updated before

**Comment by remicollet** [comment]
Can't reproduce, someone else ?

**Comment by tsmr** [comment]
Sorry my fault effectivly
