### ISSUE TITLE
XSS in title and solution fields. GLPI 9.1 

### ISSUE THREAD

**Issue by daedalus** [glpi-project/glpi#2264]
Hi,

We found the following vulnerability in our set up (GLPI 9.1):

Writing this code: <script>alert(document.cookie)</script> in both fields title and solution, it yields the execution of a stored xss vuln.

Neither Normal follow-ups or ticket description seems to be afected.

![screenshot from 2017-06-05 14-49-04](https://cloud.githubusercontent.com/assets/115175/26796026/3787e5f2-49fe-11e7-925d-0c3013b35adb.png)
![screenshot from 2017-06-05 14-59-58](https://cloud.githubusercontent.com/assets/115175/26796374/af6d0f74-49ff-11e7-9e1f-f4253b4deaf8.png)

**Comment by trasher** [comment]
Introduced in https://github.com/glpi-project/glpi/commit/181185fd
