### ISSUE TITLE
bad user when collecting attachment via e-mail

### ISSUE THREAD

**Issue by dmagniez** [glpi-project/glpi#2267]
Hello,

On every ticket created by the collector, attached files are associated to a random user, than the real issuer. Ticket is created with the good issuer.

the install is a fresh new 9.1.2, upgraded today to 9.1.3 for trying to fix this issue.

![image](https://user-images.githubusercontent.com/2813342/26837474-c992b08c-4add-11e7-9ef4-4fa7480ba08a.png)

**Comment by trasher** [comment]
Hello,

As far as I remember, this has been fixed yet. So, I'm closing this issue right now, feel free to reopen if problem persists with latest release.

**Comment by dmagniez** [comment]
Hello, The problem persist, I upgraded to 9.1.4 to be sure.

**Comment by trasher** [comment]
This is fixed in 9.2.
