### ISSUE TITLE
"rn" added in the solution field instead of \r\n 

### ISSUE THREAD

**Issue by philippeplatiau** [glpi-project/glpi#2268]
Dear Team, 

Since latest version upgrade (from 0.90.5 to 9.1.3) I have some issues in the field "Solution" of a ticket. 
When there are multiple lines, an empty line is not ... empty anymore: "rn" is displayed (I suppose it's \r\n )

![bugrn](https://user-images.githubusercontent.com/19855237/26872847-481a8a70-4b78-11e7-8d1f-ec0bca6b6d1f.png)

There is no problem when I add a "follow-up". It's only for the Solution field. 

Any idea ? 

Thanks a lot

**Comment by trasher** [comment]
This dusplicates #1944 ; will be fixed in 9.1.4 release

**Comment by philippeplatiau** [comment]
ok thanks a lot. It's indeed the same bug. I'll wait for the update. I didn't see that previous ticket. I searched in the current issues, but only on "open" ones.  I'll do a general search next time ! 

Regards,

Philippe
