### ISSUE TITLE
[9.1.3] Solution contains "rn" instead of blank line

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#2274]
Hello !

Since we are on 9.1.3, when we add a solution to a ticket, blank ligne are replaced by "rn".

This issue appears only on "solution". Followup, task, and validation are ok.

Please take a look at screenshot.

Step to reproduce .... : Add a solution to a ticket with CR and Blank line between your "text line"

Exemple : 

Solution : 
Installation of MS OFFICE.
rn
Installation of WinZip

![2017-06-09_07h37_48](https://user-images.githubusercontent.com/16323410/26962472-9ef40e10-4ce6-11e7-8e5c-9047b15f8561.png)

![2017-06-09_07h39_31](https://user-images.githubusercontent.com/16323410/26962506-e7b82f46-4ce6-11e7-9fa4-61782137525d.png)

Thks

**Comment by trasher** [comment]
Duplicates #1944
