### ISSUE TITLE
Feature - manage domains expiration

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2276]
The dropdown domains in GLPI currently contains a name and a comment.

Adding a few more fields:
- creation date
- expiration date

would be the basis to implement notifications about imminent expiration.

**Comment by btry** [comment]
Consider integrating the domains plugin in GLPI

**Comment by orthagh** [comment]
Done in 9.5.0 -> https://github.com/glpi-project/glpi/commit/a19900894e0f601828dd5d11d39ef02d492777c1
