### ISSUE TITLE
BUG - GLPI 9.1.3 - New installed software doesn't appears in computer's software list (but this didn't happen in GLPI 9.1.2)

### ISSUE THREAD

**Issue by loyolajavi** [glpi-project/glpi#2288]
Hi, 
I want to show you an error when i install new software in computers. This happens with GLPI 9.1.3 (with 9.1.2 this did not happen):

1) The first inventory of computer "PC1" works fine (the list of software is complete with **416** software installed)
![image](https://user-images.githubusercontent.com/17304522/27144728-5d46eb8c-5109-11e7-96ae-3521318ea995.png)

2) Later, I install "Notepad++" in the computer "PC1" locally

3) Force an inventory in "PC1"

4) The change seems to apply
   4.1) in History of "PC1": 3717	2017-06-12 16:00	Plugin_FusionInventory	Software	Install 
                                          the software: Notepad++ (64-bit x64) - 7.3.3 (1248)
![image](https://user-images.githubusercontent.com/17304522/27145860-95cfb19c-510d-11e7-8ce7-2ba85e2f083a.png)

   4.2) in Import Information: notepad++ (64-bit x64)$$$$7.3.3$$$$48$$$$0$$$$1 ....
![image](https://user-images.githubusercontent.com/17304522/27145905-c4a2e44e-510d-11e7-90b0-164fdf7d40e9.png)

   4.3) But in PC1-Software the list still has **416** installed programs
![image](https://user-images.githubusercontent.com/17304522/27145926-d58cef98-510d-11e7-8d37-e9ed15d7908f.png)

   4.4) The software Notepad++ (64-bit x64) - 7.3.3 appeers in Assets-Software, but in Licenses - Number 
          of installations there is 0 installations.
![image](https://user-images.githubusercontent.com/17304522/27145947-f38c3774-510d-11e7-90cb-c7652068371d.png)

If I click in install software inside the computer PC1 and choose notepad 7.3.3, the software adds to the list, but does not automatically when the fusioninventory send the inventory to glpi (should be add the software notepad++ to computer's software list)
What can i do to solve this?

Thank you very much
Best regards

The GLPI config is:
Operating system: Linux 7d9c4e05842f 4.4.0-38-generic #57-Ubuntu SMP Tue Sep 6 15:42:33 UTC 2016 x86_64
PHP 5.6.30-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at XXX Port ZZ)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.5.41-0ubuntu0.12.04.1
	Server SQL Mode: 
	Parameters: XXX@XXX/XX
	Host info: XXX via TCP/IP
	
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.

Libraries
 
htmLawed version 1.1.21 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.23 in (/var/www/glpi/vendor/phpmailer/phpmailer)
Zend Framework in (/var/www/glpi/vendor/zendframework/zend-loader/src)
zetacomponents/graph in (/var/www/glpi/vendor/zetacomponents/graph/src)
SimplePie version 1.5 in (/var/www/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

**Comment by MarcoMarcellusi** [comment]
I confirm that upgrading 9.1.2 to 9.1.3 (neither 9.1.4), the client doesn't update server with its list ..
(client: FusionInventory 2.3.18 .. 2.3.20)  and DB tables aren't corrupted.

I reverted back tha snapshot and waiting for a solution.

**Comment by loyolajavi** [comment]
Solved.. I installed FusionInventory Plugin 9.1+1.1
