### ISSUE TITLE
[9.2] malformed login error page

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2307]
Hi

If I enter wrong credentials to login in GLPI I get the following page:
![image](https://user-images.githubusercontent.com/14139801/27220911-0522c816-5287-11e7-987f-4f97d068b011.png)

i cannot click on "log in again", because the footer is invisible ans palced over the link. This may lead the user to http://glpi-project.org

See the screenshot with highlighted text
![image](https://user-images.githubusercontent.com/14139801/27221021-62d587e6-5287-11e7-8234-71612b8752c3.png)

**Comment by yllen** [comment]
I test and i can click on "Log in again" and i'm redirect to login windows of connection

**Comment by btry** [comment]
As far as I see there is a CSS and / or HTML problem.

The content of the footer partially overlaps the hyperlink making it not clickable everywhere it should be.

If you don't reprocduce then I shall tell I'm using Chromium packaged for Debian SId. I'll report the exact version soon.

**Comment by yllen** [comment]
I'm using Firefox on CEntOS 7

**Comment by btry** [comment]
I'll compare with others versions of FF, and feedback

**Comment by yllen** [comment]
My version of Firefox is 52.1.0

**Comment by btry** [comment]
Chromium Version 59.0.3071.86 64-bit

Firefox 54.0 64 bits  => OK
Firefox ESR 52.2.0 64 bits => OK too

I don't have Chrome to see how ot works, but it would be interesting to see if the bug is actually in Chromium or not.

**Comment by btry** [comment]
I searched where is the footer by selecting text on the page when running FF

![image](https://user-images.githubusercontent.com/14139801/27343531-84bcab6e-55e3-11e7-82a5-b8e872fb6657.png)

Now if I reduce width of my window (I'm used to use half width of my display 1920x1080)

![image](https://user-images.githubusercontent.com/14139801/27343587-a8bf9cc4-55e3-11e7-86fc-b24347e4e682.png)

There is a small overlap, but it appears to be less thant Chromium.

I think we need to fix the vertical position of the footer, or remove it, as it is supposed to be invisible.

**Comment by yllen** [comment]
I don't have footer like you login failed

**Comment by btry** [comment]
The footer is actually here: see the HTML code (4 last lines)
![image](https://user-images.githubusercontent.com/14139801/27348473-7978166a-55f4-11e7-8c28-42b572115a0a.png)

While discussing with you, I found the problem occurs when the width of the brower's window is approximatively 960px (1920 / 2). for larger windows, the footer does not overlaps the link.

Notice in the following screenshot the tooltip: it belongs to the footer.
![image](https://user-images.githubusercontent.com/14139801/27348617-02f06a3c-55f5-11e7-9fc7-cbf1127ba77a.png)

Anyway in styles.css there is the following code

```css
#footer-login {
    position: absolute;
    right: 10px;
    /* bottom: 0px; */
    height: 40px;
    font-size: 10px;
    font-family: Verdana,Arial,Helvetica,sans-serif;
    font-weight: bold;
}
```

I disabled **bottom: 0px;** This moves the footer in an acceptable postion. See the below screenshot where I reveal the footer by selecting the text in the page.

![image](https://user-images.githubusercontent.com/14139801/27348781-7fb21066-55f5-11e7-9b06-b59f45b792d2.png)

I think I'll submit a PR with this change.

**Comment by btry** [comment]
The same upgrading to GLPI 9.1.4

![image](https://user-images.githubusercontent.com/14139801/27540352-2baf2708-5a80-11e7-93cc-6c799634dc39.png)

**Comment by trasher** [comment]
Fixed
