### ISSUE TITLE
[9.2] - runnung forced upgrade from 9.2 fails

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2308]
Hi

If I upgrade from 9.2 to itself , the upgrade breaks:

the upgrade backs up **glpi_notifications_notificationtemplates** before trying to re-create it. Next it populates the re-created table with data from a table supposed from GLPI 9.1.x

```sql
INSERT INTO glpi_notifications_notificationtemplates (
  notifications_id, 
  mode, 
  notificationtemplates_id
) SELECT 
  id, 
  mode, 
  notificationtemplates_id 
FROM glpi_notifications
```
Unfortunately  **glpi_notifications** does not longer contains a column **mode** in 9.2

**Comment by yllen** [comment]
Coorected https://github.com/glpi-project/glpi/pull/2335
