### ISSUE TITLE
[9.1.4] Can't unlink items from ticket

### ISSUE THREAD

**Issue by Aijt** [glpi-project/glpi#2309]
Hey,

Since the update from 9.1.3 to 9.1.4 to fix the components issue we've been having some issues with tickets. We can't seem to unlink items from tickets. After opening the ticket (Assistance > Tickets > Ticket ID) and going to the Items tab. 

If you select an item:
![image](https://user-images.githubusercontent.com/20682251/27225621-57e283de-529b-11e7-9811-1fd9f66cab78.png)

and press Actions > Disconnect:
![image](https://user-images.githubusercontent.com/20682251/27225553-20bdc12a-529b-11e7-87c5-d4ce16e3da34.png)
 it gives you this error:
![image](https://user-images.githubusercontent.com/20682251/27225545-10f0a53c-529b-11e7-996f-666a7bd31c8e.png)

I really hope a fix comes around the corner quick.
Thanks!

```
Operating system: Windows NT HOSTNAME 6.1 build 7601 (Windows Server 2008 R2 Datacenter Edition Service Pack 1) i586
PHP 7.0.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, apcu, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom,
	fileinfo, filter, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, session, soap, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Microsoft-IIS/7.5
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.5.46
	Server SQL Mode: 
	Parameters: glpi@127.0.0.1/glpidatabase
	Host info: 127.0.0.1 via TCP/IP
	
OKC:\inetpub\wwwroot\glpi/config : OK
OKC:\inetpub\wwwroot\glpi/files : OK
OKC:\inetpub\wwwroot\glpi/files/_dumps : OK
OKC:\inetpub\wwwroot\glpi/files/_sessions : OK
OKC:\inetpub\wwwroot\glpi/files/_cron : OK
OKC:\inetpub\wwwroot\glpi/files/_graphs : OK
OKC:\inetpub\wwwroot\glpi/files/_lock : OK
OKC:\inetpub\wwwroot\glpi/files/_plugins : OK
OKC:\inetpub\wwwroot\glpi/files/_tmp : OK
OKC:\inetpub\wwwroot\glpi/files/_rss : OK
OKC:\inetpub\wwwroot\glpi/files/_uploads : OK
OKC:\inetpub\wwwroot\glpi/files/_pictures : OK
OKC:\inetpub\wwwroot\glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
```

**Comment by orthagh** [comment]
Hello @Aijt 

I can't remember what "disconnect" did, but i think the good action to choose is "Delete permanently the relation with selected element"

**Comment by Armin83** [comment]
On my glpi test system since 9.1 or something newer. i can delete with super-admin the link relation between tickets an computer / phone. 
Computer and phone are manual added.

**Comment by yllen** [comment]
No problem for me in 9.1.4  if you use the action indicated by @orthagh

**Comment by Aijt** [comment]
Yes, the action @orthagh showed did work on 9.1.4 here as well. that is the current action we use if that needs to happen. Thanks
