### ISSUE TITLE
Queued Mail Not Send

### ISSUE THREAD

**Issue by iaanpermana** [glpi-project/glpi#2315]
Dear All,

please help about my issue, recently i'm installing plugin called Form Creator 2.4.2 by TecLib' that has its own helpdesk.
when i do submit or update my form data, it should create a notification for creator and asigned account. 
The plugin working well as it should, but notification that's been generated always stuck in Mail Queue for ever. i do ceck the Setup > Automatic Action > queuedmail and my configuration is : 
Run Frequency : 1 Minute
Run Mode : i've tried CLI or GLPI but it give same result.
I see the statistics and it shows me : 0	Action completed, no processing required
my notification entities has 0 minutes delay

i am running GLPI 9.1.1

how can i get rid of this problem ?
thanks

**Comment by Armin83** [comment]
1. ### Take care about correct time zone configuration i read something in threats in the forum.
(I don't now about this please search in support forum.)


2. Do you use other notification ? Did the others work ?

3. Please check at least 2 and 4 of this threat.
http://forum.glpi-project.org/viewtopic.php?id=157065

4. Do you see this email in glpi/files/_log/mail.log?

5. Do you know about the difference between cli and glpi ?
- In GLPI mode you must have action in your GLPI site to send notification.
- Put automatic task in CLI mode and create the cron guaranteed process.
http://wiki.glpi-project.org/doku.php?id=en:config:crontab

6. More Information similar topic
http://forum.glpi-project.org/viewtopic.php?id=142324

**Comment by iaanpermana** [comment]
@Armin83


**1. Take care about correct time zone configuration i read something in threats in the forum.**
- I've done this, my time zone setup isn't the cause

**2. Do you use other notification ? Did the others work ?**
- Yes it does, the other notification that created from direct ticket creation working great.

**3. Please check at least 2 and 4 of this threat.
    http://forum.glpi-project.org/viewtopic.php?id=157065**
**5. Do you know about the difference between cli and glpi ?
    In GLPI mode you must have action in your GLPI site to send notification.
    Put automatic task in CLI mode and create the cron guaranteed process.
    http://wiki.glpi-project.org/doku.php?id=en:config:crontab**
- Yes I do know the difference, and i've tried both of it. nothings work. my notification still stuck in the queued mail even when I set it to run on GLPI and accessing GLPI aplication, its not a mail configuration failure, i just dont know how to run it automatically.
- When I create a scheduled task to run "cron" as mentioned in the wiki tutorial above with Windows Server 2008R2 and XAMPP, the task won't run at all.

**Comment by iaanpermana** [comment]
Now it works with GLPI mode, thanks all

**Comment by miltonarce** [comment]
What was the solution?
