### ISSUE TITLE
[9.2] rest API: strings containing a number may be truncated

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2318]
Hi

(might impact 9.1.x too)

When getting an item with the rest API, strings containing digits are returned as numbers. If the string is a number with leading zeroes, they're interpreted and removed.

In this example, pin is actually "0123" in  the database, but when JSON encoding the result with JSON_NUMERIC_CHECK, the value becomes "123".

Example:
```json
{
    "id": 1,
    "items_id": 1,
    "itemtype": "Computer",
    "devicesimcards_id": 1,
    "is_deleted": 0,
    "is_dynamic": 0,
    "entities_id": 0,
    "serial": 2134590,
    "otherserial": "inv-9876540",
    "states_id": 2,
    "locations_id": 0,
    "lines_id": 1,
    "pin": 123,
    "pin2": 0,
    "puk": 0,
    "puk2": 0
}
```

**Comment by orthagh** [comment]
close in favor of older issue #2182
