### ISSUE TITLE
SQL error when doing a search on ITILCategories when using dropdown translations

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#232]
Hello,
Way to reproduce this SQL Error:

1) GLPI 0.90 
2) GLPI default language is set to 'English' and your own language is set to 'English' too.
3) Set 'Translate dropdowns' in General Setup
4) Add a new 'ticket category' in the dropdowns setup
5) Add a translation in any language for it (usually I used a text in the form 'FR Name' or 'FR comment')
6) switch your language to 'French',
7) try to view dropdown list

And should get the following error:
"Unknown column 'glpi_itilcategories_trans.value' in 'field list'"
if not then try to change your default view and add comment and name columns.

This bug is existing in GLPI 0.85 and 0.90
regards,
Tomolimo

**Comment by yllen** [comment]
Can you give the complete error in php-errors.log?

**Comment by tomolimo** [comment]
Hello Yllen,
Here is the sql-erors.log file content:

2015-11-09 09:12:29 [937@ARDEVT35]
  *** MySQL query error:
  SQL: SELECT \'MoronO\' AS currentuser,
                        `glpi_itilcategories`.`entities_id`, `glpi_itilcategories`.`is_recursive`,  `glpi_itilcategories`.`completename` AS `ITEM_0`,
                        `glpi_itilcategories`.`id` AS `ITEM_0_id`,
                        `glpi_entities`.`completename` AS `ITEM_1`,   `glpi_itilcategories`.`name` AS `ITEM_2`,
                        `glpi_itilcategories`.`id` AS `ITEM_2_id`,
                        `glpi_itilcategories`.`comment` AS `ITEM_3`, IFNULL(`glpi_itilcategories_trans`.`value`,\'__NULL__\')  AS `ITEM_3_trans`,  `glpi_itilcategories`.`is_incident` AS `ITEM_4`,  `glpi_itilcategories`.`is_request` AS `ITEM_5`,   COUNT(DISTINCT `glpi_changes`.`id`) AS `ITEM_6`,
                     `glpi_itilcategories`.`is_helpdeskvisible` AS `ITEM_7`,  `glpi_itilcategories`.`is_recursive` AS `ITEM_8`,  `glpi_itilcategories`.`id` AS id  FROM `glpi_itilcategories`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_itilcategories`.`entities_id` = `glpi_entities`.`id`
                                              ) LEFT JOIN `glpi_changes` 
                                             ON (`glpi_itilcategories`.`id` = `glpi_changes`.`itilcategories_id`
                                                 ) WHERE   (  1 )  GROUP BY `glpi_itilcategories`.`id` ORDER BY ITEM_0 ASC  LIMIT 0, 15
  Error: Unknown column 'glpi_itilcategories_trans.value' in 'field list'
  Backtrace :
  inc\search.class.php:903                           
  inc\search.class.php:98                            Search::constructDatas()
  inc\search.class.php:81                            Search::showList()
  front\dropdown.common.php:52                       Search::show()
  front\itilcategory.php:41                          include()

**Comment by yllen** [comment]
Issue introduce by commit https://github.com/glpi-project/glpi/commit/25202ec401d0aac06f17eee52146b84af3c3cb96 in https://github.com/glpi-project/glpi/issues/178

**Comment by tomolimo** [comment]
This issue was existing also 0.85

**Comment by tomolimo** [comment]
I made a fix for 0.90

**Comment by orthagh** [comment]
could you share this fix :) ?

**Comment by tomolimo** [comment]
yes of course, but as I don't mast git-hub, it may take some times :)

**Comment by tomolimo** [comment]
PR done, I hope :)
I could see that some other fake commits have been included in the PR,
These were only a try from me to integrate new commits from GLPI into my fork.

**Comment by yllen** [comment]
I ask you for log because i done at home all your commands and can't reproduce your issue.
The only bug i said was that in list of ticket categories, name was not translated,
Orthagh: can you test with indications of tomolimo but before his pull-request?

**Comment by tomolimo** [comment]
Hello Yllen
Did you logout and login from GLPI after you have changed your own language?
Regards
Tomolimo


-------- Original message --------
From: yllen
Date:09/11/2015 17:30 (GMT+01:00)
To: glpi-project/glpi
Cc: "Moron, Olivier"
Subject: Re: [glpi] SQL error when doing a search on ITILCategories when using dropdown translations (#232)


I ask you for log because i done at home all your commands and can't reproduce your issue.
The only bug i said was that in list of ticket categories, name was not translated,
Orthagh: can you test with indications of tomolimo but before his pull-request?

**Comment by orthagh** [comment]
Forum topic on same subject : http://forum.glpi-project.org/viewtopic.php?id=133854

**Comment by orthagh** [comment]
I can't replicate on full list of itilcategories (with default search).
However, if i search on content of name, the sql error triggers

**Comment by tomolimo** [comment]
Could be that it depends on the default columns

**Comment by orthagh** [comment]
I'm reviewing your pr, it's seems ok.

A small notice, pay attention to space on EOL for diff readability.
See this part of diff : 
https://github.com/tomolimo/glpi/commit/1f0fcdc87849c9e6ca7562ddee059faad0ac29ea#diff-a801c52129f44d50ab6d1db9f049c4b7L2269

I continue tests

**Comment by tomolimo** [comment]
I don't see it, could you do screen copy of the trouble?

**Comment by orthagh** [comment]
sorry bad link :D

this : https://github.com/tomolimo/glpi/commit/1f0fcdc87849c9e6ca7562ddee059faad0ac29ea#diff-a801c52129f44d50ab6d1db9f049c4b7L2484

**Comment by tomolimo** [comment]
sorry, I don't catch the problem :)

**Comment by orthagh** [comment]
on L2490, your new line adds a space after comma

**Comment by tomolimo** [comment]
ah, ok, then I'll pay attention to that in future PR,
sorry,

**Comment by tomolimo** [comment]
I've configured my file compare to ignore whitespaces...

**Comment by orthagh** [comment]
it's minor.

Last question before merge : 
Originally, in ticket or itilcategories list, the sentence was translated, right ?

**Comment by tomolimo** [comment]
in ticket: yes, in ITILCategory list: can't see it due to bug

**Comment by orthagh** [comment]
OK in ticket list, sorry
But not in itilcategories list

**Comment by tomolimo** [comment]
in ticket list (and ticket itself) it was (and it is) translated into user's language,
but in dropdown list I've never saw the translation

**Comment by orthagh** [comment]
ok.
Merge incoming

**Comment by orthagh** [comment]
last minor thing, use git pull **--rebase** to avoid merge commits :)

**Comment by tomolimo** [comment]
ok, thank you fo the advice: I'll try that

**Comment by obscandoble** [comment]
Please let me know, this bug can be actual in 9.1?
