### ISSUE TITLE
[GLPI 9.1.3-9.2] Updated document does not update timeline position

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#2323]
Hello,

On GLPI 9.1.3, when you add a document to a ticket and  after you update it with a new one, the document does not move on "action historical view". The Action list is not ordered by last modification time.

We use Vertical Split View.

Step to reproduce : 

Create a ticket

-> Add task / followup
-> Add a document file
-> Add a new followup 
-> Edit your document file with "i"
-> Select & Upload a new file and update
-> Come back to "Action Historical view" and note that Document is at the same place.

![2017-06-19_15h36_01](https://user-images.githubusercontent.com/16323410/27287829-31549100-5505-11e7-8228-447ed4eb6725.png)

Thanks for your help.

**Comment by SylvainGuibert** [comment]
Same issue on 9.1.5

**Comment by tomolimo** [comment]
Hello,

The date used to place the document into the timeline is the date of the insert into the ticket (then the creation date of the link between the document and the ticket).
Changed here: https://github.com/glpi-project/glpi/commit/d98ab5118d7b343800a33dc4eb4ac92f5632d115#diff-007edb12589cf3c8df3121cd7b19028aR6212

Regards,
Tomolimo

**Comment by SylvainGuibert** [comment]
I still have the issue in 9.1.6. Code seems to be ok.

**Comment by SylvainGuibert** [comment]
Same issue with 9.2.

**Comment by trasher** [comment]
When you edit a document, this is the document date time that is changed. The date i the ticket timeline is the one of the relation between document and ticket; so it does not change.
