### ISSUE TITLE
Reopen closed ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2324]
Ticket is closed.
I have right to reopen ticket in cycle life of my profile.

When you reopen a ticket, you create a new foolowup. If you have no rights to create a followup, you can reopen a ticket.

Purpose to add also rights of ticket followup creation to display Reopen button.
Your opinion?

**Comment by lexcorp** [comment]
Is a good idea...

**Comment by yllen** [comment]
Correction is not good because you don't have CREATE right for followup
