### ISSUE TITLE
[9.1.2 to 9.1.4 upgrade] Empty computers list

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#2325]
Hi,

I have upgrade my GLPI from 9.1.2 to 9.1.4.

And i have lost all computers in computers list : 
![2017-06-19 16_44_53-glpi - ordinateurs](https://user-images.githubusercontent.com/113057/27290867-d2fc4c4c-550e-11e7-88e4-c76d9507bb82.png)

Same issue for printers, network, devices.
In database all data are present.

Can you help me ?

Thanks

**Comment by wawax** [comment]
Hello,

Please switch to debug mode and report any error.
Could you also check the glpi logs ?

Thanks.

**Comment by barbuslex** [comment]
In debug mode, i have this error : 
![2017-06-19 16_58_02-glpi - ordinateurs](https://user-images.githubusercontent.com/113057/27291464-8cd9fa64-5510-11e7-8beb-36090baafdce.png)

**Comment by barbuslex** [comment]
I have found !

It need gettext extension to be enable in php.ini

Maybe it would be good to add the test of the presence of the extension before the update.

**Comment by lexcorp** [comment]
Same here #2316 after install php_gettext the list of computers is present

**Comment by trasher** [comment]
gettext is not mandatory, please avoid using it. I've just submitted a pull request and proposed a quick fix on #2316 .
