### ISSUE TITLE
GLPI API - Very Slow InitSession

### ISSUE THREAD

**Issue by hypemonkey** [glpi-project/glpi#2334]
Hi GLPI team, 

When I call InitSession in the API, I get a response (session token) after few minutes (5-10 mins). 

Here's what my URL look like: http://glpi/apirest.php/initSession/?Content-Type=%20application/json&app_token=xxx&user_token=xxx

I can't find why it is so slow... 

Any help would be greatly appreciated !

Thank you in advance :)

**Comment by btry** [comment]
Hi

In your URL you have Content-Type= application/json (with a space after the equals sign). This data shall not be in the query string. **Content-Type** is a HTTP header.

**Comment by hypemonkey** [comment]
Yeah. You are right, my bad. But I still have my problem :(

**Comment by btry** [comment]
Are your users in the database or do they come from an other resource (LDAP for example) ?

**Comment by hypemonkey** [comment]
@btry they are users in the database.

**Comment by ladenree76000** [comment]
if i use this url http://glpi/apirest.php/initSession/?Content-Type=%20application/json&app_token=xxx&user_token=xxx it works (quickly)
if i use headers it works on some server (but nat all i dont know why) but when it works it works fast

**Comment by btry** [comment]
@hypemonkey : If your requests pass through a proxy or any intermediate server, try by requesting directly your GLPI, and also check if there is a resource (hardware or network) bottleneck.

You also may investigate logs of your HTTP server, logs of GLPI (php-errors, sql-errors), check if your tables are optimized or crashed. If you find something relevant, please show it here.

**Comment by Jean-Christophe-P** [comment]
I have the exact same problem on 9.3.3
InitSession takes two minutes and ten seconds using API Token but is instant when using login/password base64 hash.
Reproductible everytime.
