### ISSUE TITLE
When editing the list's fields view, prefix search options

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#2336]
When editing a personnal view, it would become imported to preview the search option's name by the group.

In the following capture, the operating system search option's names may overlap (for example a computer name and a os name). By changing "name" by "Operating System - Name", we'll avoid confusion.

![view](https://user-images.githubusercontent.com/341007/27376323-14abcf8c-5672-11e7-9568-8d46038ecb96.png)

BTW plugins do this kind of things, but we should integrate that in a clean way into GLPI

**Comment by trasher** [comment]
This is more global; see https://github.com/glpi-project/glpi/issues/2681
