### ISSUE TITLE
Duplicate send email to user glpi 9.1.4

### ISSUE THREAD

**Issue by major697** [glpi-project/glpi#2340]
When user send ticket to glpi and when I reply on this ticket to user, mail is sent correctly, but when user reply on mail from glpi, a new mail queue is created in glpi and glpi send duplicate mail 
to user with the same message as the user sent:

![message](https://user-images.githubusercontent.com/18541212/27384253-8b649aac-568e-11e7-8076-2c047e9e781f.png)

I know, is created new foolowup, and glpi send mail but can I block this ??

**Comment by Armin83** [comment]
No you can't if you answer with email.

For the next time please use system for appropriate request.
Support http://forum.glpi-project.org/
Bug Report https://github.com/glpi-project/glpi/issues
Feature Request https://glpi.userecho.com/
