### ISSUE TITLE
Notifications not de-duplicated properly on some cases

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2353]
When raising an event, some notifications are created, inserted in the database, and some are then removed.

For example, creating a new ticket should:
- create a notification (new ticket) for main admin,
- create a notification (new ticket) for current user,
- create a notification (new user in requesters) for current user,
- create a notification (new user in assignee) for current user,
- drop notification (new user in requesters) for current user,
- drop notification (new user in assignee) for current user.

In `NotificationEventMailing` tests; I was waiting for 2 notifications to be created in the database; but I sometimes get 3 of them... I guess this is a side effect of the `forceSend` method, that will send and mark the notification as removed (and therefore, it will not be de-duplicated).

This is hard to debug, this is kind of a random bug (at least from the unit tests). Using a debugger also change the behavior...

I've commited a fix for the tests (https://github.com/glpi-project/glpi/pull/2352) to keep running; because I guess the real fix would be a huge job (and I don not have time right now to fix that).

**Comment by cedric-anne** [comment]
Should be fixed in master.
