### ISSUE TITLE
Notification with timeline

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2358]
http://forum.glpi-project.org/viewtopic.php?id=158047
http://forum.glpi-project.org/viewtopic.php?id=158212

this->input receive [_disablenotif] => 1

**Comment by andreamedea71** [comment]
We need create a Notification for status ticket changed from working status to resolved (or closed) status. It's work from main ticket windows changig status from working to resolved, but if we change ticket status directly from TASK or FOLOWUPS in GLPI Call Process( with layout for timeline TAB on Left) there is the BUG and only notification for other event on task or Followups are sent.
But if the operation is performed by a user with SUPER ADMIN profile notification with timeline for ticket status changed from call process WORKS !? So input receive [_disablenotif] => 1 is only for other profile?

**Comment by sylvainclerc** [comment]
Hello,

This bug still exist in 9.2.2.

**Comment by trasher** [comment]
removing the `_disablenotif` does not seems to be enough; there is something else that goes wrong (deduplcation maybe).

**Comment by trasher** [comment]
You mean 9.3.3 I guess?

**Comment by mrspam** [comment]
No my GLPI is actually in 9.3.2.

**Comment by drlight17** [comment]
GLPI 9.5.6 - still no notification when close ticket working ticket.

**Comment by cconard96** [comment]
If this only occurred when changing the status from a task or followup, I guess this is no longer an issue with GLPI 10 as that feature doesn't exist anymore in the core.
