### ISSUE TITLE
Security die. trying to load an forbidden class name

### ISSUE THREAD

**Issue by AliouneDiop** [glpi-project/glpi#2360]
Dear
I have the error below when I tried to view accounts under Administration in GLPI.
Security die. trying to load an forbidden class name

 I am using glpi 9.1.3
Thanks

**Comment by yllen** [comment]
Can you give exacts errors in glpi php-errors.log?

**Comment by AliouneDiop** [comment]
Hi

no error is written on the log but I noted that when I changed the number of items to display from 15 to 40 or more, I received the error : Security die. trying to load an forbidden class name

find below what I saw on the php-errors logs
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  plugins/accounts/front/account.php:35

**Comment by trasher** [comment]
Please try with all plugins removed (nothing in plugins directory) and see if you can reproduce.

**Comment by AliouneDiop** [comment]
@trasher sorry but I don't understand what you want me to do.thanks

**Comment by AliouneDiop** [comment]
I solved the proble.This post can be closed
Solution
I checked on database and I saw some lines with 0 as value ;the line is Itemtype
I changed it to the default : set Entity
and the problem is solved
