### ISSUE TITLE
Add new hook

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#237]
For my job, i need 2 new hook for display message at login and/or in central.
These hook don't change the comportment of the core all is done in my plugin.

I don't know how to submit a pull-request so i commit in 0.85.5 only.
If not OK revert it.
If OK i'll done it in 0.90

**Comment by remicollet** [comment]
I don't see any problem with such new hook
(except you need to update the example plkugin ;)

**Comment by orthagh** [comment]
ok for me, i link some additionnal asks

**Comment by yllen** [comment]
Can you give me URL for doc_improvement and plugin example?

**Comment by orthagh** [comment]
You should know the (Documentation repository)[https://github.com/glpi-project/doc] :)

The new repository for (plugin example)[https://github.com/pluginsGLPI/example).
This one is in my (very) long todolist to review/improve. It was imported from old forge
I just added you to team if you wanrt to improve the repo.

We need a proper readme in repo, surely import the wiki page to help developers to create plugins, etc.

**Comment by orthagh** [comment]
Done for example plugin : https://github.com/pluginsGLPI/example/commit/d0e0fdcebff5ae87a2d31a56e6f2ef9e7129c06c

This week, i started to import in [plugin example wiki](https://github.com/pluginsGLPI/example/wiki), the documentation to create plugin.
We can add a topic for 0.90->0.90.1 migration.

**Comment by yllen** [comment]
You already have a text that you can put in login_box.
So i prefer to put this after all information from GLPI (login en link for FAQ)
