### ISSUE TITLE
Using TASK TEMPLATES in TICKET TEMPLATE

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#2375]
Please add the possibility to use TASK TEMPLATES in a TICKET TEMPLATE and add the possibilty to predefine User and/or Users Group in the TICKET TEMPLATE as well.
I suppose it would be very usefull.
Thank you in advance.

**Comment by orthagh** [comment]
Hello @okvok 

It's already done: https://github.com/glpi-project/glpi/pull/1815

This work will be present in future 9.2.

**Comment by okvok** [comment]
Thank you very much for your soon reply!
Could you tell me please  approximate date of the 9.2 stable release?
