### ISSUE TITLE
Plugins compatibility check method

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2379]
Actually, each plugin check if it is compatible with GLPI on its own side.

I've added some methods to centralize displayed messages (and translate them) already, but we could provide a complete method that would take a minial version, a maximal version and a flag to support  dev versions.

Recent change on GLPI version (set to "9.2-dev") may mark some plugins as incompatible (because 9.2-dev is lower than 9.2).

Thoughts?

**Comment by yllen** [comment]
Don't forget to add @since version xxx in comment of each new function
