### ISSUE TITLE
Ticket URL approve 

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#238]
Hello.
In version 0.9 the variable ##ticket.urlapprove## redirect to http://glpi/index.php?redirect=ticket_1236_Ticket$2.
The correct would be http://glpi/index.php?redirect=ticket_1236_Ticket$1 for show the approval and refuse the solution. 
This happens in notifications by e-mail.
Thanks

**Comment by yllen** [comment]
##ticket.urlapprove## is URL to approve the solution of a solved ticket by the requester, so Ticket$2 is correct.
Ticket$1 is for ticket validation

**Comment by rjmontenegro** [comment]
Ok, correct. 
I close.

**Comment by sebaminguez** [comment]
Hello!
In glpi 0.90.1 with timeline instead of separated tabs Ticket$1 show approve solution (last in "Processing ticket" tab)
Ticket$2 only goes to solution if  "Keep tabs replaced by the ticket timeline"=yes

**Comment by yllen** [comment]
If glpiticket_timeline active URL always go to Ticket$1

**Comment by sebaminguez** [comment]
Not in my case.
Glpi 0.90.1 upgrading since 0.83

**Comment by yllen** [comment]
@sebaminguez can you try 0.90.2?

**Comment by sebaminguez** [comment]
Sory @yllen
I lost access to that glpi (change of job)
