### ISSUE TITLE
Mail Collector rules by mailgate destination doesn't work

### ISSUE THREAD

**Issue by nathanpinotti** [glpi-project/glpi#2382]
I'm creating rules (3 of them) to assign entity to ticket that come from a specific mailgate collector.

I create:
Name = Entity by email IT
Active = yes
---------------------------------------
Criteria
Mails receiver = IT@mydomain.com
---------------------------------------
Action
Entity - assign - "Root > IT"
---------------------------------------

=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Name = Entity by email Sales
Active = yes
---------------------------------------
Criteria
Mails receiver = sales@mydomain.com
---------------------------------------
Action
Entity - assign - "Entity Root > Sales"
---------------------------------------

The rules just doesn't work properly. All the tickets are assigned to the root entity. If I move IT rule to the top it applies IT entity to all tickets.

**Comment by arthurrschaefer** [comment]
These mailcollector rules are so weird on past few releases. Beyond this one, we have another one that is also facing problems. Look here.
https://github.com/glpi-project/glpi/issues/2024

**Comment by trasher** [comment]
Duplicates #2024
