### ISSUE TITLE
Bug display description 

### ISSUE THREAD

**Issue by yatar** [glpi-project/glpi#239]
Hello, 

i have a problem with display on ticket, but not on the timeline, ticket created by mailcollector
idem on notification email

![description](https://cloud.githubusercontent.com/assets/15038264/11028841/6f3eab44-86c2-11e5-9e06-9d72316bbe0c.jpg)

![timeline](https://cloud.githubusercontent.com/assets/15038264/11028840/6f3dcaa8-86c2-11e5-9c9a-5b6aae2bc2c4.jpg)

![notif](https://cloud.githubusercontent.com/assets/15038264/11028874/ec1365c4-86c2-11e5-96fd-2d67d79616c2.jpg)

**Comment by orthagh** [comment]
Could you test the current master (0.90.1 soon) ?
We have some fixes on theses parts.

**Comment by yatar** [comment]
yes, i test current master

**Comment by orthagh** [comment]
Could you provide the html source of your ticket (from db) ?
On https://gist.github.com/ or http://pastebin.com/ .

**Comment by yatar** [comment]
https://gist.github.com/yatar/eb7265a8557ada6c2213

**Comment by orthagh** [comment]
my fault, by i prefers the raw ticket content from db (glpi_tickets.content)

**Comment by yatar** [comment]
https://gist.github.com/yatar/de3e43f90ff71bcd681a : db

**Comment by yatar** [comment]
on valid content, it's start : &lt;html 
on invalid : &amp;lt;html

**Comment by cedric-anne** [comment]
Hi,

Some fixes were made for this kind of issues between 0.90.1 and 9.4, this one included. Existing data cannot be fixed automatically, but a new ticket creation from mail receiver should not create malformed content like this anymore.

Feel free to reopen if your are facing it again with GLPI 9.4.

Regards
