### ISSUE TITLE
On 0.90 when adding a document to an existing followup (or task) the doc is uploaded, but not added

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#240]
Hello,
The test is made with the drag-drop feature.
At a followup (or task) creation, there is no problem: the doc is added to the ticket,
but at followup (or task) editing, adding a document to it: the doc is uploaded, but not added to the ticket.
I made a test with IE10, FF39 and Chrome46.
There no error in the logs.
regards,
Thank you
Tomolimo

**Comment by orthagh** [comment]
It's indeed a bug, but question :+1: 
Do we need to add/upload document on fup/task edition ?

I'm thinking to delete this part in edition to clean interface. (i still need to improve this part : #159)

**Comment by tomolimo** [comment]
In my internal plugin 'ticket document' I do not permit to add a doc when editing a followup, but it's only due a coding difficulty that I didn't overcome :)
But we may imagine that it's usefull to add a doc to an existing followup (or task)

**Comment by orthagh** [comment]
usefull : surely yes
But current implementation in confusing, imo.
We *add* a document in an action of *edition*.
When adding the element, the user could have add a document and on edition waiting to replace existing one.

I think the single action "add document" is better on this situation.

**Comment by tomolimo** [comment]
ok

**Comment by orthagh** [comment]
I really prefer this solution.
It go in direction of #159
