### ISSUE TITLE
Add month in SLT

### ISSUE THREAD

**Issue by ddurieux** [glpi-project/glpi#2407]
I need to have SLT in month (mostly for `request` type).
We have `minutes`, `hours` and `days`.

I propose add `months`

**Comment by AnaelMobilia** [comment]
@ddurieux Newbie question : what SLT is for ?

**Comment by trasher** [comment]
SLT/SLA are ITIL concepts, see: http://www.itilfrance.com/index.php?pc=pages/docs/glossaire/C/terme_73.inc
