### ISSUE TITLE
SLA SLT sending constant update notifications

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#2408]
Dear All ,
i configured SLA on GLPI. it works perfect , like assigning SLA based on business rules etc. but the issue im facing is there is a constant update ticket notification once the time to resolve it reached. its 100s of emails saying update of ticket. i just want one notification to the technician when time to resolve exceeds. can some one help me please?

**Comment by trasher** [comment]
Duplicates #1996

**Comment by roshanroche** [comment]
Dear trasher,
any updates on this issue?

**Comment by trasher** [comment]
No. If I had updates, I'd wrote on the original issue.

No need to open same issue twice, this will not speed up anything.

**Comment by roshanroche** [comment]
Thank you
