### ISSUE TITLE
Reopen ticket for closed ticket and timeline

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2412]
In my settings: use timeline - don't conserve old tab

When you click on reopen you are redirect to followup tab.
With timeline click on the button do nothing

**Comment by satyan01** [comment]
thx

**Comment by sferia82** [comment]
sorry. ask me the reason for reopen ticket.

**Comment by yllen** [comment]
Issue stil present in Demo site in 9.2

**Comment by yllen** [comment]
http://forum.glpi-project.org/viewtopic.php?id=159413

**Comment by trasher** [comment]
Please do not reassign milestones on closed tickets; this will break changelog.

Also; a bug on tickets reopening has been opened since 9.2; and it's been fixed. Demo website is not up to date.

Please test with current 9.2/bf and open a new ticket.
