### ISSUE TITLE
Clone Assets

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#2427]
How to clone Assets in glpi like: [http://forum.glpi-project.org/viewtopic.php?pid=118700#p118700](http://forum.glpi-project.org/viewtopic.php?pid=118700#p118700)?

**Comment by trasher** [comment]
Sounds like the requester never send a PR to get his changes integrated in core. Please use [sugestions website](http://suggest.glpi-project.org) to upvote or create a ticket.

**Comment by flonou** [comment]
Hi ! I'm willing to try an implementation for this. Do I need to open another issue ? or can I refer this one in my PR ?

**Comment by trasher** [comment]
Hi @flonou, please prefer a new issue; thank you :)
