### ISSUE TITLE
Bug when importing users from different LDAP directories.

### ISSUE THREAD

**Issue by DanielPrette** [glpi-project/glpi#2432]
I have an environment where I have two different LDAP (Windows AD) directories, and when we try to import a user from the directory that is not the default in the advanced mode, clicking the "to change" button and then searching, users do not appear.

The only way we can import users that are not from the default directory is to have the users search the default directory first in simplified mode first, and then go into advanced mode and choose another directory, and then have them search for users that do not Are from the default directory appear normally.

I have tried different filter settings and in all of them the same situation occurs, could anyone verify this situation in their environments?

And I'm sorry for the English of google translator.

**Comment by trasher** [comment]
I do not know if this bug has been solved since you've open the ticket ; but I've just tested with the future 9.2 and that works as expected.
