### ISSUE TITLE
import AD

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#2435]
hi,
- configured AD integration
- There is no user in GLPI
- The user writes e-mail to support
- The user is imported in GLPI

but the ticket is displayed as e-mail.

Is it right ?

![2017-07-10 15 34 39](https://user-images.githubusercontent.com/11009787/28018284-62938d94-6585-11e7-8503-70bc6db231cd.png)

**Comment by roshanroche** [comment]
Hi,
AD integration is via ldap import u can import users from AD into glpi and sync them.
2nd part of ur question is related to receivers. Ticket creation from receivers email import. Both are different things.
