### ISSUE TITLE
[9.1.6] Name display order pref not take into account in Processing ticket

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2442]
Hello,

In GLPI 9.1.4, when a user has "Name display order" preference set as "First name, Surname", this preference is not take into account **only** in Processing ticket tab if : 
- user is the requester
- user adds a followup 
- user adds a task

Steps to reproduce : 
- Set "Name display order" preference set as "First name, Surname" for user Richard Stallman
- Create a ticket with requester as user Richard Stallman
- Save ticket
- Create followup as user Richard Stallman
- Create task as user Richard Stallman

In Processing ticket tab, you can see that : 
- Requester name is in the form Stallman Richard
- Writer of followup and task is in the form Stallman Richard

However, in Ticket tab, all is right.

**Comment by nqb** [comment]
Same issue in 9.1.5.

**Comment by trasher** [comment]
Issue introduced from https://github.com/glpi-project/glpi/pull/2058
