### ISSUE TITLE
[9.2.1] Regression in Ical export

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2443]
Hello,

In GLPI 9.1.4, when you do an Ical export of your planning, you can't read it with an Ical reader like Lightning.

If you open ICS file, you can see that `END:VCALENDAR` line is missing. The file seems to be truncated randomly. If you delete last VEVENT section and add `END:VCALENDAR` line, you can open your file with an Ical reader.

Steps to reproduce : 
- Export your planning with "Export - Ical" in Assistance -> Planning
- Open ICS file and go at end of the file

You can see that ICS file is truncated.

**Comment by nqb** [comment]
#2133

**Comment by dariopsmw** [comment]
Problem can be reproduced on GLPI 9.2

**Comment by nqb** [comment]
@dariopsmw : thanks for your report. I edit issue subject.

**Comment by nqb** [comment]
Still presents in 9.2.1

**Comment by nqb** [comment]
As discussed on IRC, we need to compare size of HTTP requests to get ICS file when modifying following line : https://github.com/glpi-project/glpi/blob/32917452093ade580eda844f3f47616eaee84acb/inc/planning.class.php#L2211 
* Currently : 17,94 Ko (missing `END:VCALENDAR`, ICS contains 461 lines)
* `strlen` in place of  `Toolbox::strlen` : 18,07 Ko (`END:VCALENDAR` presents + blank line at the end, ICS contains 466 lines)
*  `mb_strlen` in place of  `Toolbox::strlen` : 17,94 Ko (missing `END:VCALENDAR`, ICS contains 461 lines)
