### ISSUE TITLE
[9.2.2] Regression in exporting one ICS file for a group

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2445]
Hello,

In GLPI 0.90 planning, we had possibility to export planning for a group in **one** ICS file. 
Since 9.1, we need to export ICS file for each member of a group which is really painful.

Please add possibility to export one ICS file for a group.

**Comment by nqb** [comment]
I have create request on : http://glpi.userecho.com/topics/675-/

**Comment by trasher** [comment]
Thank you. Il close the ticket, another one will be opened if feature is engouh upvoted on userecho.

**Comment by nqb** [comment]
On reflection, it's a regression because functionnality was enable in GLPI 0.90. Please fix this bug.

**Comment by trasher** [comment]
Needs investigation to know if this is really a regression; or if that was intended.

**Comment by nqb** [comment]
Regression still presents in 9.2.1. Please change this behavior.

**Comment by nqb** [comment]
@orthagh, 

As discussed on IRC, I test in 0.90. I found differences between 9.2 and 0.90 regarding group planning.

In 0.90, when a group member scheduled a task, all group members (and himself) can see that task in "Group view" tab. All group members can export this "Group view" in an ICS file. Consequently, a group member show all events for himself and its group with **one** iCal subscription.

In 9.2.2, you can not have same behaviour. Actual results : 
* Using iCal export of a group (when you add "Group" in planning). It works but : 
  * you need to assign manually **each task scheduled** to group
  * two iCal subscriptions to manage (personnal and group)
* Using iCal export for each member of a group (when you add "All users of a group" in planning). It works but : 
  * Really painful. You have to copy **manually** each iCal URL
  * If you group contains 20 technicians, you have 20 iCal subscriptions
  * When you have new group member, you have to manage a new subscription

I suppose that behaviour has been introduced with possibility to assign a task to a group. In 0.90, you can only assign a task to a technician. To my mind, it's really a regression. Please fix it.
