### ISSUE TITLE
Email sending issue GLPI - 9.1.4

### ISSUE THREAD

**Issue by fabriciomdy** [glpi-project/glpi#2453]
Hello, after performing the GLPI update from version 9.1.3 to 9.1.4, I encountered a problem in sending the emails, when finalizing or updating some call the glpi is sending e-mail to the wrong email or Either it should interact with the caller but it is sending to concurrent users.

**Comment by trasher** [comment]
Please use english only here. Thank you.

**Comment by fabriciomdy** [comment]
Hello, after performing the GLPI update from version 9.1.3 to 9.1.4, I encountered a problem in sending the emails, when finalizing or updating some call the glpi is sending e-mail to the wrong email or Either it should interact with the caller but it is sending to concurrent users.

**Comment by fabriciomdy** [comment]
I'm still having problems, some solution to this error in glpi.
