### ISSUE TITLE
9.1.5 Problem with self-service perfil

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#2472]
Tickets opened by self-service users are losing categories.

GLPI 9.1.5 only.

**Comment by glpibr** [comment]
Another problem is that the user is able to change the category after the error. But GLPI attributes user as a technical responsible for the call, even though he is only self-service.

**Comment by orthagh** [comment]
Hello @glpibr 

Could you check the glpi logs (on fs, in glpi/files/_log/) if you have relevant entries ?

**Comment by orthagh** [comment]
Finally found the problem, @glpibr, could you test the following changes: https://github.com/glpi-project/glpi/pull/2474/files

**Comment by Armin83** [comment]
It works for me on my test system.

**Comment by glpibr** [comment]
The test is ok here.
--
Atenciosamente






*Halexsandro de Freitas Sales*

Gerente de projeto

+55 81 3091 4252

halexsandro.sales@verdanatech.com



2017-07-17 6:01 GMT-03:00 Armin83 <notifications@github.com>:

**Comment by yllen** [comment]
@orthagh you add a part deleted to fix a security part?

**Comment by orthagh** [comment]
yes.
I was off yesterday, so i suggest a fast fix.
But today, i need to check to get this part working without security hole present.

**Comment by orthagh** [comment]
Finally after check the original issue, i'm pretty sure that is not present anymore with the new fix

**Comment by orthagh** [comment]
and for a final word, i removed the potential problematic part.
