### ISSUE TITLE
Problem to new ticket (9.1.5)- automatic "Assigned To" owner ticket

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#2473]
When opening a new ticket the applicant is being assigned as responsible automatically, even without having profile for this.

**Comment by nqb** [comment]
Have you see preference "Pre-select me as a requester when creating a ticket" in Setup -> General -> Default Values, section Assistance ?

In my side, preference was set to "Yes" automatically.

**Comment by glpibr** [comment]
Talvez eu não tenha sido claro. O problema é que está sendo atribuído ao usuário com perfil self-service.

**Comment by fabriciomdy** [comment]
I have the same problem, how to solve it?

**Comment by daviddoyen** [comment]
Same problem here after an upgrade : http://forum.glpi-project.org/viewtopic.php?id=158378

**Comment by mbrantes** [comment]
Same problem here. Version 9.1.5. The user running mailgate is selected as the ticket technician.
Mesmo problema aqui. Versão 9.1.5. O usuário que executa o mailgate é selecionado como o técnico do ticket.

**Comment by daviddoyen** [comment]
https://github.com/glpi-project/glpi/pull/2474/files fix it for me.

**Comment by mbrantes** [comment]
Problem solved!

I changed the option "Pre-select me as a technician creating a ticket" in Setup -> General -> Default Values -> section Assistance (reference @nqb) to "No". After, sign out and sign in. Done!

Eu alterei a opção "Me pré-selecione como técnico quando da criação de um chamado" em Configurar -> Geral -> seção Assistência para "Não". Depois, sai do sistema e entrei novamente. Funcionando!

**Comment by glpibr** [comment]
This works as a contour measure. But a definitive solution is needed
because it should not affect self-service users.

Isso funciona como medida de contorno. Mas é necessário uma solução
definitiva pois não deveria afetar usuários self-service.

--
Atenciosamente






*Halexsandro de Freitas Sales*

Gerente de projeto

+55 81 3091 4252

halexsandro.sales@verdanatech.com



2017-07-18 14:40 GMT-03:00 mbrantes <notifications@github.com>:

**Comment by orthagh** [comment]
Issue confirmed, fix incoming today (and a release for regressions soon)

**Comment by orthagh** [comment]
Here is the fix:
https://github.com/glpi-project/glpi/pull/2484/commits/e1e343592543d797aa406c77c242165f9ecbb818
