### ISSUE TITLE
[9.2.1] Assign action on business rule for update

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2477]
Hello,

In GLPI 9.1.5, I notice that when you **assign** a technician group through business rules for tickets (update), current group on ticket is not replaced. Assign action seems to be identical to Add action.

Steps to reproduce : 
1. Create a business rule for ticket : 
  - Use rule for : Update
  - Criteria :  Category is "Bar" 
  - Actions : Technician group - Assign - "Bar" group
2. Create a ticket assign to "Foo" group
3. Select "Bar" category on ticket 
=> Groups "Foo" and "Bar" assign on ticket

Expected behavior : only "Foo" group assign on ticket. "Bar" group replace.

**Comment by nqb** [comment]
No logs in `glpi/files/_log`, no logs in debug mode.

**Comment by lcpj** [comment]
Same as #2294 and #2452

**Comment by nqb** [comment]
Issue still presents in 9.2.1.
