### ISSUE TITLE
reopen ticket does not work

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2478]
Hello

I tried to use it but nothing happens.

nothing in sql log or php log

glpi 9.1.4 - windows 2012 - iis 8.5 - mariadb 10.1 - php 7.012

**Comment by freewood** [comment]
It's was fixed in 9.1.5 https://github.com/glpi-project/glpi/issues/2412

**Comment by satyan01** [comment]
thx

**Comment by sferia82** [comment]
it doesn't work in 9.1.6. i click in reopen and nothinf happens

**Comment by freewood** [comment]
No, it's work fine. When you click "Reopen" page switches to the tasks tab and new "Followup" form opens. You should add new followup with written reason why you want to open this ticket.
