### ISSUE TITLE
Disable field.

### ISSUE THREAD

**Issue by fabriciomdy** [glpi-project/glpi#2479]
Hello, how can I disable the field that follows in the image below!
![erro](https://user-images.githubusercontent.com/29122178/28332516-817fa6ec-6bcb-11e7-8798-61c36f654613.png)

**Comment by ensonb** [comment]
Not sure if you could disable it (maybe by css) but you could hide it in the **Manage Template** section

**Comment by fabriciomdy** [comment]
This field does not appear to be hidden in call templates

**Comment by trasher** [comment]
As @ensonb said, you can hide this field from the template
