### ISSUE TITLE
Still loading computer.form.php page if "Child entities" is true

### ISSUE THREAD

**Issue by tizianosartori** [glpi-project/glpi#2487]
When we try to load the /front/computer.form.php page, the Computer tab still "Loading..." if the computer asset child entities value is set to Yes.

**Comment by orthagh** [comment]
Please attach your glpi version and check if glpi logs (on filesystem, in glpi/files/_logs) contains any entries relative to your issue

**Comment by tizianosartori** [comment]
This is the SQL error:

_2017-07-19 16:50:06 [56@glpi]
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
             FROM `glpi_plugin_ocsinventoryng_winupdates` WHERE `computers_id`=\'260\'
                                                AND entities_id NOT IN (\'0\') 
  Error: Unknown column 'entities_id' in 'where clause'
  Backtrace :
  inc/db.function.php:319                            
  inc/commondbtm.class.php:1876                      countElementsInTable()
  inc/commondbtm.class.php:2372                      CommonDBTM->canUnrecurs()
  inc/computer.class.php:536                         CommonDBTM->showFormHeader()
  inc/commonglpi.class.php:473                       Computer->showForm()
  ajax/common.tabs.php:97                            CommonGLPI::displayStandardTab()_

This is an error of OCS Inventory Plugin... I close the ticket
