### ISSUE TITLE
SQL error with User::getSqlSearchResult()

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#249]
```
2015-11-12 09:26:34 [VM]
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_users`.*
                   FROM `glpi_users`  LEFT JOIN `glpi_useremails`
                     ON (`glpi_users`.`id` = `glpi_useremails`.`users_id`)
                  LEFT JOIN `glpi_profiles_users`
                     ON (`glpi_users`.`id` = `glpi_profiles_users`.`users_id`) WHERE  `glpi_users`.`id` IN (4385,5170,5420,1454,1447,1453,2518,1440,1477,1442,1443,1444,1445,1476,1427,1424,1430,1438,4341,1439,1434,2729,1472,1419,2519,1420,1976,1416,1471,1456,1466,2670,1415,2517,1484,1468,2787,2722,1487,1483,1459,2769,1460,1461,1491,1425,1464,1467,1441,1478,2521,1450,1451,1452,2520,2724,,2734,1485,5285,5288,1000046,2460,5422,5421,1836,5424,5283,2848,3847,5423,5280,3882,5281,3974,3975,3976,3996,4007,5531,4210,4346,4348,4340,1884,4666,4430,4384,4412,4425,4426,5126,5282,2,4239,4964,4445,4442,4434,4440,4671,5448,5538,2438,1000015,5482,1000034,1000055,1000065,1000072,1000098,1000125,1000064,1000166,1000167,1000221,1000220,1000261,1000281,1000272,1000270,1000229) AND `glpi_users`.`is_deleted` = \'0\'
                  AND `glpi_users`.`is_active` = \'1\'
                  AND (`glpi_users`.`begin_date` IS NULL
                       OR `glpi_users`.`begin_date` < NOW())
                  AND (`glpi_users`.`end_date` IS NULL
                       OR `glpi_users`.`end_date` > NOW())  ORDER BY `glpi_users`.`realname`,
                               `glpi_users`.`firstname`,
                               `glpi_users`.`name`  LIMIT 0,200
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2734,1485,5285,5288,1000046,2460,5422,5421,1836,5424,5283,2848,3847,5423,5280,38' at line 5
  Backtrace :
  inc/user.class.php:3133                            
  ajax/getDropdownUsers.php:86                       User::getSqlSearchResult()
  ```

When you try to display observer from simplified interface

**Comment by tsmr** [comment]
Change LEFT JOIN to INNER JOIN

Index: user.class.php
===================================================================
--- user.class.php	(revision 21759)
+++ user.class.php	(working copy)
@@ -2935,7 +2936,7 @@
             if (count($groups)) {
                $query = "SELECT `glpi_users`.`id`
                          FROM `glpi_groups_users`
-                         LEFT JOIN `glpi_users`
+                         INNER JOIN `glpi_users`
                               ON (`glpi_users`.`id` = `glpi_groups_users`.`users_id`)
                          WHERE `glpi_groups_users`.`groups_id` IN (".implode(",",$groups).")
                                AND `glpi_groups_users`.`users_id` <> '".Session::getLoginUserID()."'";

**Comment by yllen** [comment]
I test the drop down of observers in post-only without any error.

**Comment by tsmr** [comment]
For me The SQL result (migration from 0.83 version) of
```
SELECT  `glpi_users`.`id` 
FROM  `glpi_groups_users` 
LEFT JOIN  `glpi_users` ON (  `glpi_users`.`id` =  `glpi_groups_users`.`users_id` ) 
WHERE  `glpi_groups_users`.`groups_id` 
IN ( 62, 84 ) 
AND  `glpi_groups_users`.`users_id` <>  '2'
```
Show me 195 records and inside 20 NULL records

**Comment by yllen** [comment]
In your first SQL error you have 2 ,, in the list of your entity.
I don't understand how you can have that.

**Comment by tsmr** [comment]
I think this is the NULL values

**Comment by yllen** [comment]
have you null value in `glpi_groups_users` for users_id?

**Comment by remicollet** [comment]
It looks like you have a non-consitent DB, with entry in glpi_groups_users for deleted users.

     SELECT * FROM `glpi_groups_users` WHERE `users_id` NOT IN (SELECT id FROM glpi_users);

**Comment by tsmr** [comment]
with AND `glpi_users`.`is_deleted` = 0 into the query : it's ok
