### ISSUE TITLE
[9.2.1] Ticket status not updated after business rule

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2496]
Hello,

When using business rule (in update) that assign a technician group with a criterion based on category, I notice that ticket status is not updated.

Steps to reproduce : 
1. Create a business rule for ticket : 
  - Use rule for : Add/Update
  - Criteria :  Category is "Bar" 
  - Actions : Technician group - Assign - "Bar" group
2. Create a ticket without assignment 
=> Ticket status : New
3. Select "Bar" category on ticket 
=> Assigned to : "Bar" group
=> Ticket status : New

Important :  status is well updated if you use category at creation.

Maybe linked to #2477

**Comment by nqb** [comment]
No logs in `glpi/files/_log`, no logs in debug mode.

**Comment by lcpj** [comment]
Same as #2294 and #2452

**Comment by nqb** [comment]
Issue still presents in 9.2.1.
