### ISSUE TITLE
[9.2.1] Requester name in timeline ticket with attachment

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2498]
Hello,

When a ticket is created by an e-mail with attachment, requester name in timeline ticket is replaced by "Requester" for document row, see attachment : 
![image](https://user-images.githubusercontent.com/10830260/28419940-e077a56e-6d60-11e7-8d21-dffe8d2d3691.png)

Steps to reproduce : 
1. Send an e-mail to a receiver with attachment
2. Go on "Processing ticket" tab on ticket created by receiver

Old issue similar #348

**Comment by nqb** [comment]
Issue still presents in 9.2.1.

**Comment by trasher** [comment]
"Requester" is shown when user has not been found from the collector.

**Comment by nqb** [comment]
@trasher : not agree. 

I'm my screenshot we can see that requester has been found by collector for ticket description but not for attachment.

**Comment by edgardmessias** [comment]
@nqb, you use cron mode with "GLPI" ou "CLI"?

**Comment by edgardmessias** [comment]
@trasher @nqb , the #3710 resolve the problem

**Comment by trasher** [comment]
@nqb please test proposed PR and tell us if that solve your issue.

**Comment by nqb** [comment]
@trasher : it works for me. Thanks @edgardmessias !
