### ISSUE TITLE
[bug] Postonly can alter fields on form after created ticket (9.1.6)

### ISSUE THREAD

**Issue by ricardoasimoes** [glpi-project/glpi#2504]
When the postonly create a ticket, he can change almost every field on ticket.
All the field is avaliable to change but only works in the fields category and description.
In lasted releases (<=9.1.3) this thing doesn't working like that. All fields was not be able to be changed. This way is better

**Comment by arthurrschaefer** [comment]
For now, I think I'm keeping 9.1.3 working here.

**Comment by PierreCPF** [comment]
I have the same issue, but it's an issue or the new ticket access for post-only users ?

**Comment by arthurrschaefer** [comment]
#3187

**Comment by arthurrschaefer** [comment]
In the 9.2.2 post-only are just able to change Category, Urgency and Ticket Title.
Even though, I still don't believe it's a good thing.

I believe the user must be able to change things just until the ticket is not owned by some tech. If it's assigned to someone and work has begun, the ticket fields should be blocked. No changes during the service.
