### ISSUE TITLE
Version GLPI > 9.2.1 - Date and time in interation

### ISSUE THREAD

**Issue by rogeriogc** [glpi-project/glpi#2505]
Good afternoon! 
 
I have identified a blug, I do not know if it is tool lock or a said of a Bug. When I make a record of a task above the user's photo, the date and time of this record is inserted, but if you need to change this date, changing the date or time it does not update. Has anyone with the new 9.2.1 version noticed this problem and know if it really is a lock or bug in the application? Attached follows example I changed the date and time of the record to 16-02-2017 22:20 but even saving still remains old 16-02-2017 20:07.

![image](https://user-images.githubusercontent.com/30326876/28436228-899f6ee6-6d6c-11e7-84ec-e7b70db0944a.png)

**Comment by trasher** [comment]
The date displayed in the ticket history is the modification date of the relation between the task and the ticket; this is not related to the task itself
