### ISSUE TITLE
GLPI doesn't allow to select the ticket Category within the simplified interface

### ISSUE THREAD

**Issue by tbrandysky** [glpi-project/glpi#2507]
Hello,

**after upgrade to 9.1.5 it's not possible to choose the ticket category when creating a ticket. Once the category is selected the whole page is reloaded and the category is back to unselected.** 

[code]   GLPI 9.1.5 ( => /usr/share/glpi)
--

Operating system: Linux server103 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar, 	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, 	mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) PHP/5.4.16 () 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0 Server Software: MariaDB Server 	Server Version: 5.5.52-MariaDB 	Server SQL Mode:  	Parameters: glpi@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 /etc/glpi : OK /var/lib/glpi/files : OK /var/lib/glpi/files/_dumps : OK /var/lib/glpi/files/_sessions : OK /var/lib/glpi/files/_cron : OK /var/lib/glpi/files/_graphs/ : OK /var/lib/glpi/files/_lock/ : OK /var/lib/glpi/files/_plugins : OK /var/lib/glpi/files/_tmp : OK /var/lib/glpi/files/_rss : OK /var/lib/glpi/files/_uploads : OK /var/lib/glpi/files/_pictures : OK /var/log/glpi : OK SELinux mode is Disabled

htmLawed version 1.1.21 in (/usr/share/glpi/lib/htmlawed) phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.23 in (/usr/share/glpi/vendor/phpmailer/phpmailer) Zend Framework in (/usr/share/glpi/vendor/zendframework/zend-loader/src) zetacomponents/graph in (/usr/share/glpi/vendor/zetacomponents/graph/src) SimplePie version 1.5 in (/usr/share/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.12 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) ircmaxell/password-compat in (/usr/share/glpi/vendor/ircmaxell/password-compat/lib) ramsey/array_column in (/usr/share/glpi/vendor/ramsey/array_column/src) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

Server: 'ldap://ldap01.XX', Port: '636', BaseDN: 'dc=XX', Connection filter: '(&(objectClass=inetOrgPerson))', 		RootDN: none, Use TLS: '1'

Not active

Way of sending emails: SMTP+TLS

**Comment by Armin83** [comment]
solved in 9.1.6 + security fixes

**Comment by flegastelois** [comment]
Hi, already fixed, please use GLPI 9.1.6
