### ISSUE TITLE
Location search with space character

### ISSUE THREAD

**Issue by Krakozaber** [glpi-project/glpi#2509]
Filtration at the location does not work if you enter a space in the location selection field

GLPI 9.1.6

**Comment by yllen** [comment]
And you have a location with a space character as name?
If you want to search empty location used ^$

**Comment by Krakozaber** [comment]
I have "5 build > 3 flor > 324 room" and "5 build > 2 flor > 224 room".
If enter the data "3 flor" location filter is broken.

**Comment by jsamaniegog** [comment]
I have the same problem. From version 9.1.3 the searcher separates the words and searches for each one of them.

The only solution I have found is to replace spaces with '%' every time I look for something.

**Comment by ciadch** [comment]
Same problem with version 9.2

**Comment by Krakozaber** [comment]
Same problem with version 9.2.1

**Comment by trasher** [comment]
Duplicates #3021
