### ISSUE TITLE
[0.90.1] Error when adding users in ticket with notifications disabled

### ISSUE THREAD

**Issue by korial29** [glpi-project/glpi#251]
Notification disabled
Add a new user in ticket => this fields "alternative_email" and "use_notification" are not displayed.
That gives the following error : 

  *** PHP Notice(8): Undefined index: use_notification
  Backtrace :
  inc\commonitilobject.class.php:626                 
  inc\ticket.class.php:1060                          CommonITILObject->prepareInputForUpdate()

  *** PHP Notice(8): Undefined index: alternative_email
  Backtrace :
  inc\commonitilobject.class.php:629                 
  inc\ticket.class.php:1060                          CommonITILObject->prepareInputForUpdate()

**Comment by yllen** [comment]
You correct only for Requester? not for observer or assign?
