### ISSUE TITLE
planning stays loading

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#2510]
Hello

9.1.6 - php 7.012 - mariadb 10-iis 8.5

![image](https://user-images.githubusercontent.com/15144026/28515326-84aaf402-705d-11e7-9bf6-ffead967d567.png)

![image](https://user-images.githubusercontent.com/15144026/28515399-c45676a8-705d-11e7-99f6-8c9ad7e97c97.png)

Thank you

**Comment by trasher** [comment]
Please check you logs files

**Comment by trasher** [comment]
Not enough informations. Closing
