### ISSUE TITLE
[9.1.6] Supervisors can't assign ticket to their groups

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2512]
Hello,

With a supervisor profile, I can't assign a ticket to my group(s). With admin or higher profile, I can.
Regression seems to appear between 0.90.5 to 9.1.

Steps to reproduce : 
1. Create a ticket without assignment
2. As a supervisor user, try to assign a ticket to your group(s)
=> When you save, all seems right but assignment is empty.

However, you can self-assign ticket.

No logs in `glpi/files/_log`, no logs in debug mode.

**Comment by flegastelois** [comment]
Hi,

I can't reproduce, as user with "Supervisor" GLPI profil, I can assign ticket to my group (or to anyone else).

Note that by default: the rights in "Assistance > Tickets" are the sames in "Admin" or "Supervisor" Profil.

Regards,

**Comment by nqb** [comment]
Thanks for you feedback. Have you any idea to debug this issue ?

**Comment by yllen** [comment]
On which entity is the supervisor to do the assignation?

**Comment by nqb** [comment]
Entity of supervisor : `Root entity > Company > Service`

**Comment by nqb** [comment]
In 9.2.1, issue is fixed.
