### ISSUE TITLE
[9.1.6] Visibility of tickets unassigned

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#2515]
Hello,

When a user has "See group ticket" right and has not "See all tickets" right, he can see tickets unassigned. This behavior is incoherent : he should see only tickets assigned to his group(s).

Environment : 
* Foo user, member of IT Group
* Bar user

Steps to reproduce : 
- Define a profile with "See group ticket" right (without "See all tickets" right), associated to Bar user
- Create a ticket unassigned as Foo user
- Try to see ticket with Bar user
=> Bar can see ticket
- Assign ticket to IT group as Foo user
=> Bar can't see ticket

**Comment by flegastelois** [comment]
Hi,

I can't reproduce.

1. Ticket in "New" state => Bar can't see, Foo can see.
2. Ticket in "Assigned" state (to "IT Group") => Bar can't see, Foo can see.
3. Ticket in "Assigned" state (to one of "Bar's group") => Bar and Foo can see it both.

Can you run this SQL query (on your MySQL server and GLPI database) and give me the result? 
> SELECT rights FROM glpi_profilerights WHERE name = 'ticket' AND profiles_id = **X**;
_**Replace the "X" with the id of your profile "See group ticket"**_

Regards,

**Comment by nqb** [comment]
```
mysql> SELECT rights FROM glpi_profilerights WHERE name = 'ticket' AND profiles_id = 3;
+--------+
| rights |
+--------+
| 260127 |
+--------+
```

**Comment by flegastelois** [comment]
Ok I understand, by [design](https://github.com/glpi-project/glpi/blob/9.1/bugfixes/inc/ticket.class.php#L275) the right "Assistance > Tickets > Assign" gives the possibility to see the ticket when the status=new (incoming).

It's a feature introduced in GLPI more than 7 years ago.

**Comment by nqb** [comment]
Oh sorry, I understand.

**Comment by flegastelois** [comment]
Hi, 

Yes of course, you can propose this addition in the documentation.
A rewriting job began on the following project space:
https://github.com/glpi-project/doc

Don't hesitate to help us!
Regards,
