### ISSUE TITLE
Oberser can't add follow up

### ISSUE THREAD

**Issue by msizec** [glpi-project/glpi#2517]
Hello,

It seems an observer can't create a follow up.

Is it by design ?

thx

**Comment by flegastelois** [comment]
Hi,

Yes it's by design (by default, as you can see in this screenshot) the "Observer" profile is made to "observe" and not to "act" on the ticket process (except on his own ticket).

![image](https://user-images.githubusercontent.com/470612/28607977-afdff0fa-71de-11e7-8a1d-23ba80232d39.png)

You can change this behavior by adapting the rights of the "Observer" profile.

Regards,

**Comment by msizec** [comment]
The only way you can change this behavior is to give the right to "Add to all ticket" ... but then will they be able to add follow up to tickets they are not observing ?

**Comment by flegastelois** [comment]
"Add to all tickets" means "On all tickets whose profile has access".

So it depends on the rights you put on visibility of the tickets.

**Comment by msizec** [comment]
For you to know : the initial need was to let 'postonly' users add followup on their tickets.
It can be achieved like you said using the "Add to all tickets" right.... but this right is not visible if the profile use the 'simplified UI' (in french 'interface simplifiée'). 
I don't know if this is a bug or not, but if you change the 'simplified UI' to 'standard UI', then you can check the right "Add to all tickets", then you change back the UI setting and the right is still checked, post-only users then will be able to add followup even using the simplified UI.

Did you know that ?

Is it possible that it may break something with the rights management ?
(see this other issue im facing now im in 9.3.3 https://github.com/glpi-project/glpi/issues/5270

**Comment by msizec** [comment]
Hi
just to let you know that it seems there is still a way to give the 'add followup to all tickets' to the observer using 'simplified ui'  (cf my last comment)

it seems that this right can be lost/erased (after updating glpi maybe)
