### ISSUE TITLE
Cannot connect to MySQL with specials character in password

### ISSUE THREAD

**Issue by alffonsse** [glpi-project/glpi#2518]
Hello,

This morning I have tried to upgrade my current 9.1.4 instance of GLPI to 9.1.5 and 9.1.6 but when I enter my MySQL password the connection fails.

After investigating it appears that it fails to connect when using a password containing specials characters like @,% etc.
I didn't have the issue when upgrading from 9.1.3 to 9.1.4.

Here is my current setup :
Debian 8 (up to date)
Apache 2.4.10
PHP 5.6.30
MySQL 5.5
GLPI 9.1.4
Plugins :
behaviors            Name: Comportements                  Version: 1.3        State: Enabled
formcreator          Name: Formulaires                    Version: 2.5.0      State: Enabled
ocsinventoryng       Name: OCS Inventory NG               Version: 1.3.3      State: Enabled
dashboard            Name: Tableau de bord                Version: 0.8.4      State: Enabled

**Comment by trasher** [comment]
I'm not able to reproduce the issue (at least on current 9.1/bf branch).

I've dropped my config file, upgrade process asks me for connection informations, and I've entered a password with a `@` char without any issues.

**Comment by trasher** [comment]
I had no problem from the UI... But it seem I reproduce using cli tools

**Comment by trasher** [comment]
Hum... No, I was doing something wrong. I definitely cannot reproduce.

If you still have the issue, please give more details on how to reproduce, and attach complete error backtrace
