### ISSUE TITLE
notification bug group except manager user don't work

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2519]
I configured cartridge notification for defined group except manager (3 persons - 1 manager - 2 memberr)
-> no mail for mail queue
(If i configure cartridge notification for group manager or grpup it works. -> i got mail in mail queue)

This works
![img_005](https://user-images.githubusercontent.com/19192087/28618595-3ce409fc-7205-11e7-9b79-d5d9f34d7e64.jpg)

This don't work
![img_004](https://user-images.githubusercontent.com/19192087/28618599-3e709fba-7205-11e7-9d96-437f33f5f0ec.jpg)

Alert set was displayed, but there was no e-mail in mail queue (, mail queue dustbin) or mail.log.
![img_003](https://user-images.githubusercontent.com/19192087/28618601-43a402a6-7205-11e7-8d89-fd47295665a5.jpg)

![img_002](https://user-images.githubusercontent.com/19192087/28618184-bf41862e-7203-11e7-8975-645df2f6810f.jpg)

**Comment by Armin83** [comment]
I tested this with ticket update too. I have a own group name "my_teamxy". I set notification to group "my_teamxy" without manager. No one get a notification. (9.3 (rc2) nighly tarball mariadb)

**Comment by kabassanov** [comment]
I have a similar issue with tickets and "Group in charge of the ticket except manager users" with slight difference: only 3 users from a 4 members groups receive the email, and the missing one is not supervisor (same as manager???).

**Comment by Armin83** [comment]
Not sure / maybe configuration problem or something else.

**Comment by aagz** [comment]
I have the same problem.
Any notifications doesn't work if recipients field has value "Group, without manager: "XXX""

**Comment by aagz** [comment]
Please reopen the issue.

**Comment by cedric-anne** [comment]
> Please reopen the issue.

Hi,

Please open a new issue, and give us all requested informations.

Regards
