### ISSUE TITLE
automatic actions - documentation needs an update

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2521]
The following page : 

http://glpi-developer-documentation.readthedocs.io/en/master/devapi/crontasks.html
$CFG_GLPI['use_mailing'] does not longer exists in GLPI 9.2 and is replaced by 2 other parameters.

the SQL query is maybe no longer valid too.

The doc needs an update by refreshing this sample of code from the core

**Comment by flegastelois** [comment]
Hi !
Can you open an issue directly on the doc-dev project ?
https://github.com/glpi-project/docdev/issues
Cheers,

**Comment by btry** [comment]
Hi

I created a PR for the documentation project.

https://github.com/glpi-project/docdev/pull/58

I'm glad to tell you I choosed you as reviewer :)
