### ISSUE TITLE
[9.1.2] When resetting a search, the default bookmark is not reloaded

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2526]
Hello,

Let's have the following config: a public default bookmark on Ticket (named 'Ticket default').
After logon the 'Ticket default' bookmark is loaded each time you want to view the Ticket list.
But if after some search in the ticket list, you want to go back to this 'ticket default' bookmark, if you click on the 'blank' button 
![image](https://user-images.githubusercontent.com/7569958/28707596-41ad18fa-7379-11e7-9f03-41dc2f604ff8.png)
you'll go back to the GLPI default search and not to the public default bookmark.

For me: when a click on the blank button, then GLPI should go back to default public bookmark (or default personal bookmark)

Any thoughts about this?

thank you
regards,
Tomolimo

**Comment by wawax** [comment]
Hi @tomolimo ,

Yes you're right, I've experience the same thing yesterday.

Could you provide a PR for that ?

Thanks.

**Comment by tomolimo** [comment]
I'll look at it, but currently I'm working on the solution history issue :)

**Comment by wawax** [comment]
We'd prefer this work to be done on 9.2 (with unit tests)

**Comment by tomolimo** [comment]
ok,

**Comment by tomolimo** [comment]
I just changed the flags for this issue
