### ISSUE TITLE
Problem with change status with new followup / task

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#253]
On followup or on task you can now change the status too

But this feature have a problem : 
1. open form for add a new task
2. Select waiting or closed status
3. Try to select Assign
4. The status pic don't be change.

**Comment by yllen** [comment]
I confirm.
Icon of status in the button change only if you select an higher status (new to assign, assign to wait, wait to resolve...) not when you select lower status (resolve to wait, wait to assign, assign to new...)
