### ISSUE TITLE
Location

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#2530]
Import to place the position works, but.

in AD indicate the number of the office
![2017-07-28 16 55 19](https://user-images.githubusercontent.com/11009787/28720598-56652462-73b6-11e7-8f8a-f6b96ccdb1a0.png)
GLPI imports correct (OK)
![2017-07-28 16 56 02](https://user-images.githubusercontent.com/11009787/28720670-8a9bd4c4-73b6-11e7-8a99-ecf5398c6345.png)
and
![2017-07-28 16 57 12](https://user-images.githubusercontent.com/11009787/28720690-94339058-73b6-11e7-95bb-3ba000e41e8a.png)

but, I need to bind to an already established offices or companies, is it possible ?
To specify in AD nar23-office > 113 not working

**Comment by yllen** [comment]
Information in your AD must be the same as in GLPI

**Comment by Smiley-k** [comment]
Yes, I admit! But as you can see on the last screen, when you specify the properties user office number, it is not imported in my company, and a new one is created in the Root entity

**Comment by yllen** [comment]
In you AD location is 113.
In GLPI 113 is a sub-location to AD nar23-office
It's not the same

**Comment by Smiley-k** [comment]
Yes, but how do I AD then specify ? **nar23-office > 113** ?  if Yes, then not working.

**Comment by Smiley-k** [comment]
Moreover, even 113 is not imported in my company, and gets to the root entity

**Comment by carlsonsantana** [comment]
I have the same problem, the field **name** of location is **my_sector** and the **complete name** is **my_departament > my_sector**. When I sync a user the GLPI create a new location and if I change the field **As child of** of this new location and sync again, the GLPI create other new location.
