### ISSUE TITLE
Only allow users to see their own assets

### ISSUE THREAD

**Issue by kebyn** [glpi-project/glpi#2534]
I see the same problem here ,
[http://forum.glpi-project.org/viewtopic.php?id=109666](http://forum.glpi-project.org/viewtopic.php?id=109666)
I saw that GLPI version 9.1.6 was released.
Could you let me know something about that feature? 
Thank you very much !

**Comment by trasher** [comment]
Reading the forum; feature seems to be available as of Behavior plugin version 1.5.
