### ISSUE TITLE
Add other filters then 'contains', for example 'less then', 'more then' in assets->search

### ISSUE THREAD

**Issue by EyckWigo** [glpi-project/glpi#254]
When searching through components, some of them work better with numeric comparisions, for example 'Components - Memory (MB)'  would be better if you would be able to search for 'less then 16GB' or 'more then 65 536MB'

**Comment by nbriche** [comment]
You can already do that. 'Components - Memory (MB)' 'contains'  '>1025' gets you any asset with morethan a GB of RAM.

**Comment by orthagh** [comment]
I agree with @nbriche, <, >, <= and >= operators work with all numeric fields
