### ISSUE TITLE
Allow Technician to add components?

### ISSUE THREAD

**Issue by fabiopbx** [glpi-project/glpi#2542]
Hello all,

I've been scratching my eyes out but i can't seem to figure out how to enable the technician (or any other) profile to be able to add components and assign them to assets.

The user is able to see them and even edit the component itself but unable to add/edit an item of said component or link them to an asset, say a computer.

Is there a way to do this or am I just goin round in circles?

**Comment by trasher** [comment]
You have to give profile right on components (see setup tab of the profile)
