### ISSUE TITLE
External links visibility in child entity

### ISSUE THREAD

**Issue by l0ser140** [glpi-project/glpi#2544]
External links not shown in external link column if this link blongs to parent entity and shared to childs.
It shown only if external link belong to the same entity which choosed for view (Independently from visibility setting).

Example:
I have 2 external links. One for Root, one for Child entity. Both have Visibility for childs "yes" option.
https://i.imgur.com/pfbqHGU.png

Few computers in child entity. No external links shown if Root entity (tree view) choosed.
https://i.imgur.com/Hdx11UR.png

If i switch to Child entity external link belongs to that entity appers. But not to the childs again.
https://i.imgur.com/vrjSZS9.png

In compiter view on External links tab everything works as endeed (I can see links from parents entity).
But links counter broken too.
https://i.imgur.com/Aex6hKw.png

**Comment by redisded** [comment]
Hi,

same problem here with GLPI 9.4.4.

Unable to see links of chil entities unless if I go to the computer view.

**Comment by djbren** [comment]
Hi,

same problem here with GLPI 9.4.5

Unable to see links of chil entities unless if I go to the computer view.

**Comment by elduke78** [comment]
Hi,

same problem here with GLPI 9.4.6

Unable to see links of chil entities unless if I go to the computer view.
