### ISSUE TITLE
Recursion in search engine

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2546]
http://forum.glpi-project.org/viewtopic.php?id=158350

Add recursion in search options and massive actions for all recursive objects

**Comment by yllen** [comment]
Done for master https://github.com/glpi-project/glpi/commit/f0d349de975a88848d6d9da576e657475704a603

**Comment by nfarias1882** [comment]
Hola estimados buenas tardes, junto con saludar comento que la problemática que tengo de minuto es que no puedo filtrar por el criterio solicitante. adjunto imagen, me aparece el mensaje la carga fallo, 
favor agradecere me puedan orientar.

saludos desde chile 

![sin titulo](https://user-images.githubusercontent.com/46006378/50242437-1a78ee00-03a9-11e9-93cc-67f8ff9dfc86.png)

**Comment by trasher** [comment]
Please use english only.

**Comment by nfarias1882** [comment]
Hello dear good afternoon, along with health. attached image, I see the message the load failed,
please thank me you can guide me.

greetings from Chile
![ssx](https://user-images.githubusercontent.com/46006378/50243917-45654100-03ad-11e9-9a1d-e151fa2548c6.png)
