### ISSUE TITLE
canUnrecus not honoured for some items

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#2548]
Reproduced, at least on printer.

On a recursive printer, linked to computer in sub-entites
The webUI propose the dropdown to change "is_recursive", when is should not.

Other items may be affected.

**Comment by yllen** [comment]
Purpose a fix for all items linked to a computer (phone, printer, peripheral and monitor).

**Comment by yllen** [comment]
Master done https://github.com/glpi-project/glpi/commit/468199faf643315534277c01bf612a080fb94c69

**Comment by yllen** [comment]
I just done for computer connection.
Have you try all other items?

**Comment by trasher** [comment]
@yllen no... Please close issues when they are solved then ; I'm just trying to keep less issues opened as possible :)

**Comment by cedric-anne** [comment]
Fixed by 1ff810c68962759bed51b0bc7e6fe18e35263bc8.
