### ISSUE TITLE
canRecurs not honoured on massive actions

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#2549]
Reproduced on groups

- create a recursive group
- create sub-groups in sub entities

WebUI doesn't allow to change "is-recursive" => OK.
Massive action allow to change "is_recursive" => Bug

This may raise database inconsistency.

**Comment by remicollet** [comment]
This one is not fixed ;)

**Comment by cedric-anne** [comment]
Fixed by ee2fd5929ed140585d9724dc77a5ffa346a56b84.
