### ISSUE TITLE
[bug][9.1.6] Auto-asignee override GUI selection

### ISSUE THREAD

**Issue by nailyk-fr** [glpi-project/glpi#2552]
Steps to reproduce: 
1. Setup auto assign into settings
2. Create a new ticket, fill all required fields
3. Select "-----" as technician/assignee
4. Submit

"-----" is overwritten and ticket is self-assigned. 

Tested on 9.1.6

**Comment by trasher** [comment]
This have been fixed in the past: https://github.com/glpi-project/glpi/issues/1736

But yes, this fails again :/
