### ISSUE TITLE
Add template for follow up

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2554]
http://forum.glpi-project.org/viewtopic.php?id=126318

**Comment by wawax** [comment]
Hi yllen,

Yes this is a real improvment to make, and we've already discussed that internally when introducing the templates for tasks.

@orthagh would like to review the UI a little bit to do in a efficient way, that's why we haven't already implemented it :)

**Comment by bern2b** [comment]
Hello,

Do you have any news on this very useful evolution?
thank you

**Comment by orthagh** [comment]
here is the feature on suggest website: https://glpi.userecho.com/communities/1/topics/238-add-template-for-followups

I close this one in favor of the suggest site (development not started at all)

**Comment by sector7gp** [comment]
Hi Guys! this is an interesting feature. Is this on the road? or Is not gonna happen?

**Comment by orthagh** [comment]
@sector7gp check #5725
