### ISSUE TITLE
Disabled users in active directory are not updated in GLPI

### ISSUE THREAD

**Issue by wanderleihuttel** [glpi-project/glpi#2556]
Hello Guys

I'm running GLPI 9.1.6 and I've created a group in the active directory server to get only users from this group, but when some user is disabled in AD and already imported as active in GLPI and I try to syncronize, GLPI doesn't update user status to "inactive".

My LDAP config:
![glpi](https://user-images.githubusercontent.com/16232272/28980324-c77c6486-7923-11e7-9a0e-bfd86de7a8d5.png)

I would like to suggest in "ldap.import.php" to include a filter to get active or not active users.
If I use LDAP filters for only active users I guess it will not be possible to update an active user status for inactive, because GLPI will only searchs for active users.

Best regards
Wanderlei

**Comment by Armin83** [comment]
Can you try this suggest ?
http://forum.glpi-project.org/viewtopic.php?id=158614

**Comment by wanderleihuttel** [comment]
Hello @Armin83 !
In the first example, I'm not using the filter "userAccountControl", so should not affect my query.
The second one it's not an GLPI solution, it looks the guy created a SQL script to try to solve this problem.
Even trying to force sync in a specific user, doesn't change the status of user for disabled.
