### ISSUE TITLE
BUG in mailcollector [9.1.6]: If followup is received by mail - 'users_id_lastupdater' is not updated

### ISSUE THREAD

**Issue by 8hh6af** [glpi-project/glpi#2557]
Version: 9.1.6
Technician is called A
User is called B

When B is creating a ticket by using the form the 'users_id_lastupdater' is set to B. (correct)
When A is editing the ticket by adding a followup via webinterface the 'users_id_lastupdater' is set to A. (correct)

When B is creating a ticket by using the form the 'users_id_lastupdater' is set to B. (correct)
User A gets a notification by mail about the new ticket.(correct)
User A adds a followup by answering to the notification received by mail.(correct).
The followup was correctly added but the users_id_lastupdater is still set to B (should be A). BUG

Thank you

**Comment by trasher** [comment]
@8hh6af could you please test with the fix I've proposed in #2611? I do not have time right now myself :) Thank you.
