### ISSUE TITLE
Automatic Closing of ticket  & Masive closing of tikets with  Email template mark the ticket as new

### ISSUE THREAD

**Issue by ensonb** [glpi-project/glpi#256]
Hi,

When automatic scheduled action closes a ticket or several, the email notification received mark the ticket as new.

Also the same happens when massively closing tickets

**Comment by yllen** [comment]
Can you give the definition of your notification?

**Comment by ensonb** [comment]
It's happening in the  Notification - Close Ticket - ID 4, the field on the notification template is ##ticket.status##

**Comment by ensonb** [comment]
Attaching mail notification and ticket screenshot

![notification](https://cloud.githubusercontent.com/assets/2094732/11302092/481052f2-8f69-11e5-8468-b81e5bbf089e.PNG)

![ticket](https://cloud.githubusercontent.com/assets/2094732/11302100/52f4b8c0-8f69-11e5-9829-ede9b3620734.PNG)

**Comment by yllen** [comment]
I made many tests and can reproduce your problem.
Do you use plugins?

**Comment by ensonb** [comment]
Yes, I use OCS Inventory NG, More Reporting and the Dashboard.

**Comment by yllen** [comment]
Can you can a test with plugins deactivated?

**Comment by ensonb** [comment]
I will try  it out on a fresh install from the glpi-master, I suspect i may have something hanging from my previous 0.84 install 


cheers.

**Comment by yllen** [comment]
Have you test on a fresh install?

**Comment by trasher** [comment]
Closing as stalled
