### ISSUE TITLE
No delete button for associated items

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#2565]
Hello All,
In simplified interface. Under add associated items there is no remove button. Standard interface has this option.
Issues is if a user makes a mistake while adding item. Can't be undone. And user has to create the ticket from scratch

**Comment by trasher** [comment]
I've just tested on 9.1/bf branch; the remove icon seems to be present. It may have been fixed since you opened the issue.
Feel free to reopen if problem still persists.

**Comment by Ratherius** [comment]
Hello!
It seems that the issue is present on v. 10.0.9. Could you please tell whether there is some workaround or special setting for this?
Thank you in advance!
