### ISSUE TITLE
Satisfaction Survey

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#2569]
Dear All,
when a satisfaction survey is filled out by an user for the corresponding ticket.
a technician incharge of the ticket get that additional tab Satisfaction , now the issue is a technician can change the level of satisfaction which should not be permitted right?
example even a user gives 3 star the technician can amend it to 5 stars and so on.
can some one review this? or this is a permission issue?
i checked the profile of technician and im not able to find any setting to disable this behavior.

**Comment by yllen** [comment]
To update a satisfaction survey, you must (or right):
- be the requester of the ticket
- be member of requester group of the ticket
- be the author of the ticket and have rights to update satisfaction survey.
So a simple technician can't update a satisfaction survey
