### ISSUE TITLE
Get all virtualMachines with REST-Webservice

### ISSUE THREAD

**Issue by DGermany** [glpi-project/glpi#2575]
Hello there, 

I'm new here and that's my first post. Hope that I'm doing everything right :) 

I'm searching an solution to reach the "_glpi_tab=ComputerVirtualMachine" with REST-Webservice. Or an other possibility to get "all computers with the virtual machines in dependence on the installed software"?? 

There is no opportunity in the front-end of glpi to say "give me all virtual machines from the computer with the software XXXX". 

thanks and greets from germany

![virtualmachines_rest_issue](https://user-images.githubusercontent.com/30858247/29113560-a598ff2e-7cf1-11e7-9785-54aeb128e045.JPG)

**Comment by theoptimiste** [comment]
Hello,

 I am a beginner too, to remount the virtual machines there is a vmware API that traces the vm only for the vmware ESX server.
