### ISSUE TITLE
[9.2-dev] There is a small issue with timeline date position

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2579]
Hello,

I believe this issue is a CSS one, and as I don't master this subject....

Here is the issue:
In a ticket with an approved solution, the timeline is shown like this:
![image](https://user-images.githubusercontent.com/7569958/29116354-d0e507d2-7cfa-11e7-8b7c-aec4f5965b1e.png)

Last digit of the date is missing...

and this is only the case for the date of the solution.

regards,
Tomolimo

**Comment by trasher** [comment]
Sounds like a CSS issue indeed. Does this happen in a specific browser? Does this appear with a different browser window size?

**Comment by tomolimo** [comment]
Any Browsers: IE 10, FF 53, Chrome 59 and Safari 5.1.7
and any resolutions.

I think the culprit is the width of 115px assigned to this element:
![image](https://user-images.githubusercontent.com/7569958/29122584-22267a50-7d13-11e7-9e5e-996b379685e3.png)

and for the other elements, the width is 140px:
![image](https://user-images.githubusercontent.com/7569958/29122611-3d9e3b6a-7d13-11e7-87cf-f9b29c1d969d.png)

**Comment by tomolimo** [comment]
I found the fix :)
