### ISSUE TITLE
Add project to transfer list

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2589]
http://forum.glpi-project.org/viewtopic.php?id=158587
http://glpi.userecho.com/topics/661-project-transfer-between-entities/
http://forum.glpi-project.org/viewtopic.php?id=149989

**Comment by Megachip** [comment]
> trasher added this to the Candidate for next major version milestone on 17 Aug 2017
Which is the next major version? ;)

**Comment by trasher** [comment]
@Megachip no one until explicitly tagged on a version :)

This tags (missnamed) means that we're not against the inclusion in a future major, waiting for someone to open a pull request or order the development.
