### ISSUE TITLE
Cannot update cartridge date and counter information anymore

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#259]
In version 0.85 it was possible to update information about a `cartridge`. Double-clicking a row of the two tables that are displayed on *Cartridges* tab of a *Cartridgeitem* would make a form appears allowing to change/set:
* Add date (`date_in` DB field)
* Use date (`date_use` DB field) (on a used cartridge only)
* End date (`date_out` DB field) (on a used cartridge only)
* Counter (`pages` DB field) (on a used cartridge only)

Since 0.90 this is not possible anymore: the update form does not appears when double-clicking on any cartridge row.

**Comment by C-Duv** [comment]
Well, today it worked. I might have suffered from some browser cache-related issue.

**Comment by orthagh** [comment]
Ok ^^
Sorry for not answering 7 days ago.

I close for now, please reopen if issue triggers again
