### ISSUE TITLE
Alert when upgrading or installing new GLPI instance: mcrypt is deprecated

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2591]
Hello

Here is the screen with the alert message:

![image](https://user-images.githubusercontent.com/7569958/29168396-fbc80f92-7dce-11e7-8859-43537006f69a.png)

As I'm using PHP 7.0.22 for windows, there is no way to disable this extension, as it is statically included into  PHP release.

> phpinfo()
> PHP Version => 7.0.22
> 
> System => Windows NT FRY07689 6.1 build 7601 (Windows 7 Enterprise Edition Service Pack 1) i586
> Build Date => Aug  1 2017 13:54:13
> Compiler => MSVC14 (Visual C++ 2015)
> Architecture => x86
> Configure Command => cscript /nologo configure.js  "--enable-snapshot-build" "--enable-debug-pack" "--disable-zts" "--with-pdo-oci=c:\php-sdk\oracle\x86\instant
> client_12_1\sdk,shared" "--with-oci8-12c=c:\php-sdk\oracle\x86\instantclient_12_1\sdk,shared" "--enable-object-out-dir=../obj/" "--enable-com-dotnet=shared" **_"--with-mcrypt=static"_** "--without-analyzer" "--with-pgo"
> Server API => Command Line Interface
> Virtual Directory Support => disabled
> Configuration File (php.ini) Path => C:\Windows
> Loaded Configuration File => C:\Program Files (x86)\PHP\v7.0\php.ini
> Scan this dir for additional .ini files => (none)
> Additional .ini files parsed => (none)
> PHP API => 20151012
> PHP Extension => 20151012
> Zend Extension => 320151012
> Zend Extension Build => API320151012,NTS,VC14
> PHP Extension Build => API20151012,NTS,VC14
> Debug Build => no
> Thread Safety => disabled
> Zend Signal Handling => disabled
> Zend Memory Manager => enabled
> Zend Multibyte Support => provided by mbstring
> IPv6 Support => enabled
> DTrace Support => disabled

Same for PHP 7.1.8 for windows

So could it be possible to delete this alert?

Regards,
Tomolimo

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/2490
