### ISSUE TITLE
API namespaced itemtype compliance

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2595]
I'm considering use of namespaces in my plugin to enhance maintainability.

If an itemtype uses a namespace, accessing it from the API would require an URL with backslashes. 
I think this needs an improvement; maybe replacing underscores into backslashes like this:

A_Namespace_Itemtype => a\Namespace\Itemtype

**Comment by trasher** [comment]
I guess this kind of feature would be very hard to implement until we can remove automatic santize... Since some class may actually contains `_`; replacing them is not a good choice at all.

**Comment by btry** [comment]
About **_** you're right.

About automatic sanitization, if you're talking about the sanitization found in includes.php this is not a problem, as the API does not relies on $_GET or $_POST.

**Comment by btry** [comment]
Hi

using a dash ```-``` to separate namespaces would be better. I think this wil not conflict with anything.

However, I noticed that column names in MySQL / Maria DB are limited to 64 characters (https://dev.mysql.com/doc/refman/5.7/en/identifiers.html) I think this is easily reachable (example: ```plugin_pluginname_foreignkeys_id```).
