### ISSUE TITLE
[9.1.6] - Contract end mail notification checks start date

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi#2596]
The system send the mail for contract end date using the start date without considering contract period and renewal period. You can see an example on the screenshot below:

![2017-08-10 21_01_18-glpi - contracts - 10](https://user-images.githubusercontent.com/6400595/29187353-b390c9e4-7e0f-11e7-8d23-1aa0e4814230.png)

**Comment by AliouneDiop** [comment]
That's my problem.I have the same issue with notification from contracts

**Comment by AliouneDiop** [comment]
hi
is there any solution for this problem ?
Thanks

**Comment by joschi99** [comment]
Hi,
the problem is also on GLPI 9.2.1. Any news about a fix?
Thanks
