### ISSUE TITLE
Wrong email on anonymous email receivers

### ISSUE THREAD

**Issue by YellowCorwin** [glpi-project/glpi#260]
Hello Team,

First of all thanks a lot for your great job!

We've an issue with receivers on anonymous users, in previous version we did see the complete email address. Now we only get the first letter on the email wich is not very useful for replies ;)

Enclosed a print screen.

Thanks in advance for your help.

![screen shot 2015-11-18 at 09 52 00](https://cloud.githubusercontent.com/assets/12051304/11236467/39ae0b7c-8dda-11e5-8447-96949ec9300e.png)

**Comment by orthagh** [comment]
fixed in dd1a0e21f6c24ffd0af8fd620a6932f70cf33ec8
I plan to release 0.90.1 in the current day.

**Comment by YellowCorwin** [comment]
Thanks for your quit feedback and sorry for duplicate.
