### ISSUE TITLE
SSO connection with Debian server

### ISSUE THREAD

**Issue by popoix** [glpi-project/glpi#2603]
Hi,

i tr to configure SSO but it doesn't work; I know that this functionality didn't work with a Linux server in the past but i would like to know if now i can do that and how. 

I tried with a tuto, i changed my apache config, change authentification in GLPi with no success.

Thank you for your work.
Cheers

**Comment by trasher** [comment]
Hello,

To get help to configure and use glPI, please use the forums at http://forum.glpi-project.org/
