### ISSUE TITLE
Ticket template : associated elements

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2605]
Hello ! 

When I create a ticket template and I will add as predefined fields "Associated elements", I'don't have any dropdown box : 

![image](https://user-images.githubusercontent.com/12936546/29303660-a1e5bdd0-818e-11e7-95cb-4838e04a9cf7.png)

Then, when my ticket is create with this template, I have : 

![image](https://user-images.githubusercontent.com/12936546/29303669-b3ccc4f8-818e-11e7-847b-ee9b843f15b9.png)

Thanks for your help

**Comment by trasher** [comment]
Hi,

This sounds like a bug that have been fixed already. Ceck wit latest GLPI, fel free to reopen.

**Comment by ciadch** [comment]
Thanks for your reply. It was a user right problem. Sorry for the inconvenience
