### ISSUE TITLE
[9.1.6] Can't see automatic action configuration

### ISSUE THREAD

**Issue by R3D2** [glpi-project/glpi#2608]
Oi,

Since the update, mailgate seems having some trouble, when i was going to identify the problem,  panel is blank. I can't see nothing related to mailgate in the front-end.

And it seems that it's not only mailgate related, i tried with other tasks and the same result applies.

<img width="1115" alt="screen shot 2017-08-17 at 08 40 56" src="https://user-images.githubusercontent.com/5547320/29399072-0853306c-8328-11e7-9a46-699542ee7e88.png">

LOG : 

[Thu Aug 17 09:13:53.048552 2017] [:error] [pid 11523] [client 185.31.102.44:56389] PHP Fatal error:  Call to a member function fetch_assoc() on boolean in /var/www/glpi/inc/dbmysql.class.php on line 308, referer: https://support.gva-cloud.ch/front/crontask.php

**Comment by trasher** [comment]
Please check sql-error log. There is something wrong with one query.

**Comment by R3D2** [comment]
2017-08-17 09:32:28 [@SRV-GLPI]
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_crontasklogs`
  Error: Table './GLPI/glpi_crontasklogs' is marked as crashed and last (automatic?) repair failed
  Backtrace :
  inc/dbmysql.class.php:407                          
  inc/commondbtm.class.php:831                       DBmysql->list_fields()
  inc/crontask.class.php:315                         CommonDBTM->add()
  inc/crontask.class.php:833                         CronTask->end()
  front/cron.php:66                                  CronTask::launch()

**Comment by trasher** [comment]
So, you have an issue with your database; this is not related to glpi.
Try to repair your tables; issue should be resolved after that.

**Comment by R3D2** [comment]
Thanks a lot !
