### ISSUE TITLE
update glpi via mantainance

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2613]
good moorning, 
i have a problem when i tried to update via console glpi in mantainance. it says this:

Ha fallado la conexión. Si utiliza un proxy, configúrelo, por favor. (SSL certificate problem: unable to get local issuer certificate)

**Comment by Ddesm** [comment]
Same problem on my installation (9.1.6) on windows server 2012r2 with iss 8.5 and php 5.4.45

"Verbinding mislukt. Als u een proxy gebruikt, configureer deze aub. (SSL certificate problem: unable to get local issuer certificate)"

**Comment by sferia82** [comment]
and anyone know the solution? thankyou

**Comment by trasher** [comment]
You both have an SSL certificate issue; this is not a GLPI issue (but checks may have been reworked since - check with latest release)
