### ISSUE TITLE
Notification Problem

### ISSUE THREAD

**Issue by dan723** [glpi-project/glpi#2615]
GLPI 9.1.2

Followup notification are set up
GLPI is not sending some notification, for example when add a followup the notification is sent only to the technician in charge of the ticket and not to the requester.

Thanks

**Comment by Armin83** [comment]
Perphaps you did a private followup or did you change your settings for the notification ?

**Comment by dan723** [comment]
No, I don't use private followup and I didn't change any configuration, It
used to work fine and it just stoped working from a day to another.
I tried to check in the debug mode but i didn't get any error.

Thanks

El 21/8/2017 13:44, "Armin83" <notifications@github.com> escribió:

Perphaps you did a private followup or did you change your settings for the
notification ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glpi-project/glpi/issues/2615#issuecomment-323795288>,
or mute the thread

**Comment by Armin83** [comment]
This setting is "yes" and not your problem or ? if you set to no then active use how did the post get no email.
mysetting -> personalisation -> Notifications for my changes = yes

**Comment by dan723** [comment]
Notification for my changes is set to YES in all the users profile

El 21/8/2017 16:59, "Armin83" <notifications@github.com> escribió:

This setting is "yes" and not your problem or ? if you set to no then
active use how did the post get no email.
mysetting -> personalisation -> Notifications for my changes = yes

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glpi-project/glpi/issues/2615#issuecomment-323837637>,
or mute the thread

**Comment by yllen** [comment]
In your settings, put your GLPI in Debug mode.
Open a ticket and look at the Debug tab. Do you see requester as recipient for create followup?

**Comment by dan723** [comment]
Yes the requester is set as recipient for new followup

El 29/8/2017 9:17, "yllen" <notifications@github.com> escribió:

In your settings, put your GLPI in Debug mode.
Open a ticket and look at the Debug tab. Do you see requester as recipient
for create followup?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glpi-project/glpi/issues/2615#issuecomment-325645602>,
or mute the thread

**Comment by Armin83** [comment]
Did you check mail queue ?

**Comment by dan723** [comment]
Mail queue is empty and can't find anything on the maillog.


El 29 sept. 2017 12:07 p. m., "Armin83" <notifications@github.com> escribió:

Did you check mail queue ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glpi-project/glpi/issues/2615#issuecomment-333087461>,
or mute the thread
