### ISSUE TITLE
Test migration 0.85.x to 92

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2617]
Fatal error: Class 'SLT' not found in /home/yllen/git92/install/update_0905_91.php on line 725

**Comment by yllen** [comment]
In 9.1 class name was TTR.
So you can't change a file already deliveried in a previous version.
For migration, you must leave the SLT class (even if only this value in it)  to this field and delete it after the migration.

I purpose a PR to fix fix only to check all the migration

**Comment by yllen** [comment]
*** MySQL query error:
  SQL: ALTER TABLE `glpi_tickets` ADD INDEX `slts_ttr_id` (`slts_ttr_id`) ,
DROP INDEX `slalevels_id` ,
ADD INDEX `ttr_slalevels_id` (`ttr_slalevels_id`) 
  Error: Key column 'slts_ttr_id' doesn't exist in table
  Backtrace :
  inc/dbmysql.class.php:213                          
  inc/migration.class.php:637                        DBmysql->queryOrDie()
  install/update_91_911.php:88                       Migration->migrationOneTable()

**Comment by trasher** [comment]
Using class names and/or methods already breaks migration scripts several times... What about using the verbatim value instead of calling a constant?

**Comment by yllen** [comment]
because in previous version you have a calling of constant and you can't change what is always delivered

**Comment by yllen** [comment]
If you use the value instead of constant are you sure that if tomorrow you change constant value in class you will think to change also value in migration files?

**Comment by yllen** [comment]
I done the migration 7 times and at the 8th the migration done.
mistery, mystery...

**Comment by trasher** [comment]
If the constant value cange, let's say in 9.3 ; the expected value in the 0905 migration script woud be the one that was set when script was written, not the 9.3 one.
