### ISSUE TITLE
[9.2-dev] Use objectGUID property as new synchronization field (Active Directory only)

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#2628]
Globally Unique Identifier (well know as [objectGUID](https://msdn.microsoft.com/fr-fr/library/ms679021(v=vs.85).aspx)) is a 16 bytes value that is unique (not only for a single forest but also on all world directories) and assigned to every object create by Active Directory.

Doing a search or synchronization of an object (User/Group/etc) on this field is the best way (and that recommended by Microsoft), because when an object is assigned a GUID it keeps that value for life, even if the user samaccountname, OU or groups, changes.

objectGUID is stored in binary format (hexadecimal string), so we can't use it without having a convert method in GLPI, here is what we get now:

![image](https://user-images.githubusercontent.com/470612/29519968-a11dfed0-867f-11e7-81b5-039a35137ba0.png)

Some references if needed:
- [How to retrieve the GUID of an object from the Active Directory (Microsoft Help Center)](https://support.microsoft.com/en-us/help/325649/how-to-retrieve-the-guid-of-an-object-from-the-active-directory)
- [PHP LDAP-Tools source code](https://github.com/ldaptools/ldaptools/blob/master/src/LdapTools/Security/GUID.php)

**Comment by trasher** [comment]
Need https://github.com/glpi-project/glpi/pull/2073 to be merged first
