### ISSUE TITLE
display licence in search engine

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2643]
http://forum.glpi-project.org/viewtopic.php?id=158682

I don't understand why licence name is added for serial, otherserial and comment of a licence and not for all fields.
If you want the licence's name you can add it in search request

**Comment by yllen** [comment]
http://forum.glpi-project.org/viewtopic.php?id=158695

**Comment by AnaelMobilia** [comment]
Duplicate of #426
Fix on PR #3208
