### ISSUE TITLE
Self service ticket type lost at change category

### ISSUE THREAD

**Issue by thefamedtm** [glpi-project/glpi#2645]
Hello,

First of all, congratulations for glpi-project, it's amazing and complert system. In our company we have working with glpi since 8 years.

I'm working with glpi 9.1.6 and I customized categories with determinate template request.
I only used request type and not incidents. All de categories are from request.

When users goes to self service and select one category (ones with template request assignated) glpi reload webpage and it lost ticket type and appears "incident".

I try the same at ticket page (not self service) and runs ok. Could be the same problem in issue 2472.

Thanks in advance.
Ivan.

**Comment by yllen** [comment]
Have you predefined type in your template?

**Comment by trasher** [comment]
No answer from requester; closing
