### ISSUE TITLE
Visibility Issue with Multiple Assigned to Technical Groups in Tickets List

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#2653]
Hi,

When a ticket is assigned to multiple technical groups, and the viewer who did not open the ticket, and belongs to some of the groups, but not all them, in this case he is unable to see, in the tickets list, assigned groups he does not belong to...

**Comment by yllen** [comment]
example:
ticket created by user A who is also the requester
ticked assigned to groups GA and GB
I am member of group GB

In tickets list, in group assigned column i only see group GB, not group GA. If i open the ticket i can see both groups.
In search engine, if a request on group GA, i only see tickets where i am an actor or author.

**Comment by kabassanov** [comment]
I think it is solved now. Could you confirm at your side?
