### ISSUE TITLE
[9.2] adding a followup on solved ticket is not harmonized

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2656]
Hello,

Imagine a solved ticket (not yet closed) , and that you've kept the Followup tab along with the 'Processing Ticket' tab.
Then it's not possible to add a followup via the followup tab:
![image](https://user-images.githubusercontent.com/7569958/29774601-4cc6d996-8c02-11e7-91ef-6562c36f5a00.png)

But via the 'Processing ticket' tab, it's possible:
![image](https://user-images.githubusercontent.com/7569958/29774633-7317b688-8c02-11e7-9de1-beb3dee78e79.png)

Must be harmonized!

regards,
Tomolimo

**Comment by yllen** [comment]
The comportment in followup tab is the same since lot of versions: you can't add a followup is the ticket is solved or closed.
It's the same comportment for a ticket task.

**Comment by tomolimo** [comment]
@yllen 
Then it should not be possible when in 'Processing ticket' tab... that's the purpose of the isssue, to harmonize behavior between those tabs...

**Comment by yllen** [comment]
So processing tab must change its rights (for task too)
