### ISSUE TITLE
API - Search Tickets by Status - Bug

### ISSUE THREAD

**Issue by apedrob** [glpi-project/glpi#2662]
Hi there,

Well, when I assign someone to a ticket by glpi api, the status ticket change from New (status = 1) to Processing (assigned) (status = 2). This status change happen always, but, sometimes, when I search new tickets, appear some tickets with status equal to 2. 
I repeat that this happens occasionally and I don't know why. 
EDIT: I'm using GLPI 9.1.6 
![bug](https://user-images.githubusercontent.com/14206093/29824050-58b666ec-8cc8-11e7-9e91-21b6b70c4647.png)

**Comment by sonidp** [comment]
I have a same problem.... But i use the URL of GUI. Can you tell me which command with curl i can used this to do search ? thanks
