### ISSUE TITLE
Bug display GANTT

### ISSUE THREAD

**Issue by StackAls** [glpi-project/glpi#267]
For russian language bad display day name in diagram GANTT
![screenshot-118](https://cloud.githubusercontent.com/assets/9604248/11265861/dc8ec2b0-8eb0-11e5-8071-59d73ecd4ead.jpg)
![screenshot-119](https://cloud.githubusercontent.com/assets/9604248/11265863/ec815994-8eb0-11e5-9ca3-a259206c8664.jpg)

**Comment by tsmr** [comment]
Due to substr with Russian Language, i think
array(substr(__('Sunday'),0,1), substr(__('Monday'),0,1),
                         substr(__('Tuesday'),0,1), substr(__('Wednesday'),0,1),
                         substr(__('Thursday'),0,1), substr(__('Friday'),0,1),
                         substr(__('Saturday'),0,1)
                     );
