### ISSUE TITLE
Problem after migration

### ISSUE THREAD

**Issue by carlosbmc** [glpi-project/glpi#2706]
Some errors after migration (from 9.1.1)

1.-  Tickets search does not return resulst 

error:   Unknown column 'glpi_tickets.time_to_resolve' in 'field list' 

2.- migrate main operating system informations - Error durante la consulta a la base de datos: INSERT INTO glpi_items_operatingsystems (itemtype, items_id, operatingsystems_id, operatingsystemversions_id, operatingsystemservicepacks_id, operatingsystemarchitectures_id, license_number, license_id) SELECT 'Computer', id, operatingsystems_id, operatingsystemversions_id, operatingsystemservicepacks_id, operatingsystemarchitectures_id, os_license_number, os_licenseid FROM glpi_computers WHERE operatingsystems_id != 0 OR operatingsystemservicepacks_id != 0 OR operatingsystemarchitectures_id != 0 OR os_license_number IS NOT NULL OR os_kernel_version IS NOT NULL OR os_licenseid IS NOT NULL - Error Duplicate entry '1-Computer-1-1' for key 'unicity'

I have to empty table glpi_items_operatingsystems  to solve this

3.-  Empty page after migration until remove plugin folders  (not olny disable the plugins)

**Comment by carlosbmc** [comment]
Renaming the fields : "due_date" to "time_to_resolve"  is not included in migration ?

**Comment by amma35** [comment]
Can you give us the errors in /log/php-errors.log and sql-errors.log?

**Comment by carlosbmc** [comment]
[ProblemMigration92.zip](https://github.com/glpi-project/glpi/files/1298628/ProblemMigration92.zip)

**Comment by carlosbmc** [comment]
[clean_logs.zip](https://github.com/glpi-project/glpi/files/1298709/clean_logs.zip)

**Comment by amma35** [comment]
There are no errors related to field migration.
And the field is renamed when migrating from 9.1 to 9.2.

**Comment by carlosbmc** [comment]
Coul you see the attached image?,  then ..  what is the problem?
![image](https://user-images.githubusercontent.com/31730629/30380512-1e50c6e0-989a-11e7-8788-55e7acf1ecb2.png)

thank you!!!

**Comment by trasher** [comment]
Does this happens on the first migration try (of a "clean" old database), or is it another run?
BTW, this is not related with the primary subject of the ticket.

**Comment by carlosbmc** [comment]
Firts migration try over Black up of a producción glpi9.1.1.

**Comment by carlosbmc** [comment]
Hello,
sorry by the inconvenience,  I have a problem.  After a correct migration in production DB I submit a ticket to my  HOST PROVIDER on order to restore database previous to migration,  buy I think that they restore the database whitout remove the migrated DB,  so there are tables of a version 9.2 that exists in my production 9.1.1.
I have to delete all tables of a versión 9.2, but,  do you think I will have to do something else?

Thank you!

**Comment by carlosbmc** [comment]
Ok,  I will undo scripts
update_911_913.php
update_91_92.php

Thanks

**Comment by trasher** [comment]
When an update fails, It's better to clean entirely the database before restoring a backup. That was done in previous updates, but this can cause data loss running update several times... We did not find any real solution for this, and I prefer to see errors during migration rather than loosing data :)

Dropping new tables should be enough to solve the original issue; but update is designed to be run at once... We cannot predict what would happen with only a partial update unfortunately.

**Comment by carlosbmc** [comment]
Thank you for all!
