### ISSUE TITLE
Support other cache methods than APCu

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2712]
Currently, locales are cached using APCu behind Zend Cache; but if APCu is working very well on linux boxes; it is still considered as beta on Windows (with IIS at least). And one may already have a caching system setted up he wants to use.

Zend Cache supports a lot of other adapters we may use:
https://docs.zendframework.com/zend-cache/storage/adapter/

We may add a parameter so we can use any extra supported adapter.

**Comment by remicollet** [comment]
Some notices about cache adapters.

For now, only APCu is used for both entities tree cache and translation cache.

- memory cache is not ideal for entities tree as it won't be shared across multiple PHP servers (in big infra)
- network shared cached (redis, memcached, ...) seems better for the entities tree
- network shared cached doesn't seem suitable for translation cache, as each page will pull >200k over the network
- each adapter have its own parameter (server(s), port, credentials, ...)
