### ISSUE TITLE
Software licenses list

### ISSUE THREAD

**Issue by hotdesc** [glpi-project/glpi#2716]
Glpi does not list software licenses

SQL error: Error Code: 1054. Unknown column 'glpi_softwarelicenses.number' in 'field list'

SQL PROBLEM: 
FLOOR(SUM(`glpi_softwarelicenses`.`number`)    [wrong]
FLOOR(SUM(`glpi_softwarelicenses_53942a48cc903d4163c4f6ac35841a36`.`number`) [correct]

URL: http://localhost/glpi-916/front/software.php

SETUP:

![save1](https://user-images.githubusercontent.com/5313969/30219685-341fb810-9493-11e7-9d38-59cde37e5e44.JPG)
![save2](https://user-images.githubusercontent.com/5313969/30219684-341f0078-9493-11e7-8d89-151cad3a62cd.JPG)
![save3](https://user-images.githubusercontent.com/5313969/30219261-e89b8dc0-9491-11e7-9f16-1485958fd64f.JPG)

**Comment by trasher** [comment]
Please tell us how to reproduce the error.

**Comment by hotdesc** [comment]
Login and open this url http://localhost/glpi-916/front/software.php

**Comment by hotdesc** [comment]
I just installed a glpi from scratch and the invetory fusion plugin and the software list screen does not work anymore

**Comment by hotdesc** [comment]
I discovered the error and showed up there what is in the SQL of the page

**Comment by hotdesc** [comment]
i dont know why but the error now is a missing comma afeter ITEM_5
`
FLOOR(SUM(`glpi_softwarelicenses_92989d92e67a92f40cdb9012612c4296`.`number`) * COUNT(DISTINCT `glpi_softwarelicenses_92989d92e67a92f40cdb9012612c4296`.`id`) / COUNT(`glpi_softwarelicenses_92989d92e67a92f40cdb9012612c4296`.`id`)) AS `ITEM_5` MIN(`glpi_softwarelicenses_92989d92e67a92f40cdb9012612c4296`.`number`) AS `ITEM_5_min`
`

**Comment by trasher** [comment]
I still cannot reproduce... Tested on 9.1.6 and current 9.1/bf branch.
