### ISSUE TITLE
enhancement/bug:  Improved handling of MAC addresses (including fixing a parsing bug)

### ISSUE THREAD

**Issue by Stoatwblr** [glpi-project/glpi#2717]
Currently GLPI can only cope with MAC addresses in these formats:

IANA  - xx:xx:xx:xx:xx:xx
raw  - xxxxxxxxxxxx

If can't cope with the other common formats:

Cisco:  xxxx.xxxx.xxxx
3com: xxxx-xxxx-xxxx
microsoft (derived from VMS):  xx-xx-xx-xx-xx-xx
sun:  xx-xx-xx-xx-xx-xx with leading zero suppression, eg 1-2-fe-b-d-12

there are a few other formats. such as : separated with leading zero suppression: eg 1:2:fe:b:d:12

To make matters worse, glpi accepts microsoft-format MACs but stores them differently to IEEE ones - meaning that 12:34:56:78:9a:bc is not treated the same as 12-34-56-78-9a-bc - THIS IS A BUG.

MACs input into GLPI should be normalised - preferably to a 6 byte long - and then the colons inserted into the display text when the mac is extracted.

One normalisation PHP script is at http://www.pmoghadam.com/homepage/HTML/php-validate-normalize-mac.html, there are a number of other standard modules which could be used.

**Comment by trasher** [comment]
I agree this should be kind of normalized...

But you said "is not treated the same"; what do you mean?

In the database, the MAC is stored as is; with ":" or with "-"; so yes, it cannot be find if you do not use the correct separator, but this is the only case I can see.
