### ISSUE TITLE
error: add a followup in the ticket without right via the collector

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#2722]
Version GLPI : 9.2 & 9.1.X

1- Ticket of which I am added as an observer
2- My profile does not allow me to add followup
3- In the ticket interface, I can not add followup
4- On the other hand, by replying to the mail via the collector I can add a followup.

**Comment by cedric-anne** [comment]
Hi,

Can you check the fix provided by #2722 ?

Regards

**Comment by keha35** [comment]
Hi,

Thanks for the fix.
It seams it works great now (tested in 9.3/bugfixes).

Regards

**Comment by keha35** [comment]
Hi,

Thanks for the fix,
It seams the probleme is solved (tested in 9.3/bugfixes)

Regards.

**Comment by trasher** [comment]
@keha35 I do not undesrtand... Is the issue fixed in 9.3/bugfixes or did you try with proposed patch?

**Comment by keha35** [comment]
I've tried the proposed patch

**Comment by trasher** [comment]
Ok, thank you :)
