### ISSUE TITLE
[9.2] JavaScript runtime error: 'menuAff' is undefined

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2724]
Hello,

To reproduce:

1. ask for ticket list
1. and during the update of the list, hover your mouse on the GLPI menu

and you should get: 

> Unhandled exception at line 74, column 59 in http://localhost:52734/front/ticket.php
> 
> 0x800a1391 - JavaScript runtime error: 'menuAff' is undefined
> 

regards,
Tomolimo

**Comment by trasher** [comment]
This is because the call is done before the dom is loaded...

Calls are in `onmouseover` attributes; they should be moved in jquery events added after the dom has been loaded.
