### ISSUE TITLE
9.1.4 - Self Service Profile can modify Fields after Ticket created.

### ISSUE THREAD

**Issue by LordBat** [glpi-project/glpi#2730]
Hi! i will try to explain my scenario:

Today we have all the IT services on root tree and we gonna add 3 entities so what i do was create 4 sub-entities over the root entity.

Root Entity----> Sub-Entity 1
                  ----> Sub-Entity 2
                  ----> Sub-Entity 3
                  ----> Sub-Entity 4
![image](https://user-images.githubusercontent.com/19165739/30343407-e19d386c-97d3-11e7-8d34-b715462d6273.png)

I use the Tranfer List Option to migrate all from root entity to the sub-entity 1 and create the others BUT when an user with Self Service Profile designated to use on Sub-Entity 1 create a ticket and later check the status, the fields are available to modify despite having a "Self-Service" profile.

![image](https://user-images.githubusercontent.com/19165739/30343592-6b7e3edc-97d4-11e7-94db-9123e2f3dbb9.png)

The same situation is happening on the other sub entities.

on GLPI 9.1.4.

If something is not well explained please let me know.

Regards!

**Comment by trasher** [comment]
Self service user can edit tickets he created under some circumstances:
- no followup have been added,
- ticket is not assigned,
- ...

So, what you describe seems ok.

**Comment by ChiefAgibu98** [comment]
Do you have any idea on how to add the assigned to field in creating a ticket with self-service profile?
I want a user with self-service profile to assigned a ticket directly during creation. 

Thanks in anticipation!!
