### ISSUE TITLE
[9.2-RC1] how to install

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2731]
hi,
i want to install 9.2-rc1 on my test system for tests and translation but how ?

- ubuntu 16.10

1.  first try
 ![2017-09-12 23_55_56-new issue glpi-project_glpi](https://user-images.githubusercontent.com/19192087/30350220-1eebdb5a-9816-11e7-880d-a86c75630a29.png)

2. need this "apt-get install composer"

3. run this command
![2017-09-12 23_55_56-new issue glpi-project_glpi](https://user-images.githubusercontent.com/19192087/30350244-3485b792-9816-11e7-82da-f75e2b26a875.png)

4.  result 
 ![2017-09-12 23_55_56-new issue glpi-project_glpi](https://user-images.githubusercontent.com/19192087/30350193-0440263a-9816-11e7-9d08-4a5de3ae498d.png)

5. but don't work for me
 ![2017-09-12 23_55_56-new issue glpi-project_glpi](https://user-images.githubusercontent.com/19192087/30350220-1eebdb5a-9816-11e7-880d-a86c75630a29.png)

**Comment by trasher** [comment]
To install the RC-1, you should use the published archive (and not the "source code" ones).

**Comment by Armin83** [comment]
@trasher 
I'm not sure if do it correct. maybe i'm to stupid to find the right way but i tried this now again

1. Read this news http://glpi-project.org/spip.php?page=annonce&id_breve=383&lang=en
2. follow the link for download
3. now i'm here on github. (screenshot below)

![2017-09-12 23_55_56-new issue glpi-project_glpi](https://user-images.githubusercontent.com/19192087/30395336-190e4b2c-98c6-11e7-9eeb-36c39b8f06d2.png)

4. i copy the download link (https://github.com/glpi-project/glpi/releases/download/9.2-RC1/glpi-9.2-RC1.tgz)
5. on linux i do "wget https://github.com/glpi-project/glpi/releases/download/9.2-RC1/glpi-9.2-RC1.tgz

same problem again

**Comment by trasher** [comment]
This is the correct archive. Do you have a `composer.lock` file in your glpi directory?

**Comment by Armin83** [comment]
Yes. Don't no why. I have 2 test system both have this composer.lock. because you ask i deleted the file - now i get logged in. THANKS
