### ISSUE TITLE
Composer lock?

### ISSUE THREAD

**Issue by Setsuneh** [glpi-project/glpi#2738]
Hi,

I've tried to install GLPI on CT container with Debian 8.
A second user has been created for using composer, forbidden on root. However I've got this problem. 
Have you got any ideas?

Thanks :)

```
composer install --no-dev
Loading composer repositories with package information
Installing dependencies from lock file
Nothing to install or update
Generating optimized autoload files
> @php -r "file_put_contents('.composer.hash', sha1_file('composer.lock'));"
PHP Warning:  file_put_contents(.composer.hash): failed to open stream: Permission denied in Command line code on line 1
```

**Comment by trasher** [comment]
You (system) user does not have rights to write on the current directory.

**Comment by Setsuneh** [comment]
Thanks. How to resolve it? Don't unnderstand how to fix it.

**Comment by trasher** [comment]
You have to fix unix rights on the directory

**Comment by Setsuneh** [comment]
My question was How? I dont see which file is.

**Comment by trasher** [comment]
I can't really tell you how to manage your system rights...
Just give the user you use to do the composer command write access on glpi main directory; or maybe on the `.composer.hash` file just inside it.

The way you're trying to install is for development; you won't have this kind of issues using the release tarballs.
