### ISSUE TITLE
Comments in KB don't accept "<" ex: J<aime

### ISSUE THREAD

**Issue by bacus99** [glpi-project/glpi#2744]
Writing a comment with < in it cause truncate in result

ex:  J<aime

result: J

![image](https://user-images.githubusercontent.com/11425241/30393482-4140b4e6-988e-11e7-8bf1-889fdf61c745.png)

**Comment by bacus99** [comment]
OK for J'aime

![image](https://user-images.githubusercontent.com/11425241/30393528-66069642-988e-11e7-91d9-5ac5ef83a0a0.png)

**Comment by trasher** [comment]
I guess this is a kind of duplicate for https://github.com/glpi-project/glpi/issues/140

**Comment by orthagh** [comment]
yes i'm closing in favor of #140 (still a pain)
