### ISSUE TITLE
[9.2-RC1]Adding multiple tickettasks to tickettemplate produces SQL error

### ISSUE THREAD

**Issue by joeFischetti** [glpi-project/glpi#2747]
I tried the new feature which allows you to add tickettasks to tickettemplates.  I can add one task, but when I try to add a second I get the following SQL error.

  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_tickettemplatepredefinedfields` (`tickettemplates_id`,`num`,`value`) VALUES (\'2\',\'175\',\'1\')
  Error: Duplicate entry '2-175' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:504
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  front/tickettemplatepredefinedfield.form.php:51    CommonDBTM->add()

If I delete the first task that I added, I can add the new one.

**Comment by joeFischetti** [comment]
Feature referenced here:
https://github.com/glpi-project/glpi/pull/1815

**Comment by orthagh** [comment]
I'm currently looking a this bug

**Comment by orthagh** [comment]
@joeFischetti, 63116f9 should fix your issue, we will publish a new RC version next monday (you could patch your instance if you want).
