### ISSUE TITLE
[9.2-RC1]Plug-in Access in Configuration Menu in Error

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#2749]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* For bug reports, you can open an issue here. Add to your content a full description of your glpi setup (you can find it in Setup > General menu, System tab).
* Provide us steps to reproduce your issue.
* Delete this text to submit your issue.

The GLPI team.

**Comment by falco2001** [comment]
hello, the configuration menu then plug-in points to components. In the code, the plugin.php file is called. Do you have an idea ? Thank you

**Comment by trasher** [comment]
I guess the main error here is `PHP Fatal error: Interface 'Zend\Loader\SplAutoloader' not found in /var/www/html/plugins/fusioninventory`

This have been fixed after the RC1 has been released (https://github.com/glpi-project/glpi/commit/f5b56687663a58093959814f3bd3e6174acd28b4)

**Comment by falco2001** [comment]
I will need to test RC1 but is it a GIT repository or should it be downloaded and in this case I do not have patches? Are the bugs committed in this git? Otherwise I can not test because the plugin are inaccessible or I did not understand everything? Thank you

**Comment by trasher** [comment]
To test 9.2; the official way is to use only official releases (RC1 is out already, RC2 should come next week, final is planned for september 25th.

You can of course apply some patches if you know how to do; just be carefull with patches that change database, 3rd party libs or translations (not the case for the one I've pointed out).

As for the plugins, many of them have their current development versions compatible with 9.2; but they're not released yet (for the fusioninventory plugin, you can retrieve the archive for its master branch).

Hope that helps.
