### ISSUE TITLE
[9.2RC1] Can't re-open a closed ticket

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2751]
Hello,

Consider having a profile with the following rights:
![image](https://user-images.githubusercontent.com/7569958/30437037-f178762a-996d-11e7-8b96-0685babb1ed7.png)
This means that a ticket can be re-open to 'solved' or 'processing' when it is closed.

Unfortunately the closed tickets can't be re-open, see:

![image](https://user-images.githubusercontent.com/7569958/30437286-8290f65a-996e-11e7-98f2-6692120d4e88.png)

There is no way to change the status of the ticket, and there is no 'Save' button.

Thank you,
regards,

Tomolimo

**Comment by orthagh** [comment]
i thought the lifecycle matrix was broken, but in fact, reopening ticket is checked against the couple [closed->new].
In case of an existing attribution, it can be not fast forward to understand, so i'll change to check also the couple [close->assigned]
