### ISSUE TITLE
[9.2RC-1] cant select sim car type

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#2752]
I cant associate a simcard to phone : 
assets>phones>[myphone ]>tab assoicate elements> 
1st dropdown -> SimCard (OK)
2nd dropdown -> Empty !!!!  ( in setup in can see in card types Full sim, MicroSim,MiniSim)

**Comment by trasher** [comment]
simcards type must be associated to a simcard component; and this component to a phone. I guess you've missed to create the component.

**Comment by ladenree76000** [comment]
" I guess you've missed to create the component."  => right .
sorry.

so it works...

**Comment by trasher** [comment]
Cool ;)
