### ISSUE TITLE
GLPI API - Admin can not use GET endpoints

### ISSUE THREAD

**Issue by M3lkior** [glpi-project/glpi#2756]
Hello everybody,

- I'm using GLPI API v9.1.3 but rights management set me on trouble. 
- Working on a chatbot, i need, with a single account, call GET endpoints to display parametrized lists or tickets  (`GET - http://dev-glpi.ineat-conseil.fr/glpi/apirest.php/Ticket/192`) and call POST endpoints to create ticket for example (`POST - http://dev-glpi.ineat-conseil.fr/glpi/apirest.php/Ticket`)

Problem: 
- With an ADMIN role, my user can invoke POST on endpoints but not GET : 

![image](https://user-images.githubusercontent.com/5501911/30474589-785d26d6-9a04-11e7-8131-2e1fcfc52f79.png)

Only a super-admin can invoke both ?

**Comment by ladenree76000** [comment]
did you check that you are logged with an admin profile ? did you check thats entities of ticket 192 matches your profile  ?
can admin see all tickets (check profile) ?

**Comment by M3lkior** [comment]
The account used have ADMIN right, yes.

Here is the settings : 
![image](https://user-images.githubusercontent.com/5501911/30541263-e75747c4-9c7a-11e7-9fb2-012f9d3ef91a.png)

![image](https://user-images.githubusercontent.com/5501911/30541321-2e0828f0-9c7b-11e7-8022-84ac48a7bf00.png)

NB : The is no specific configuration for API access
