### ISSUE TITLE
Personnal RSS_Feeds rights

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#276]
I can't find a right to hide this menu, is it missing ?

**Comment by yllen** [comment]
Personal RSS feed like personal Notes is always active.
You just have right for public one

**Comment by orthagh** [comment]
We need to add a right to permit disabling of the feature.
Not urgent, i tag for 0.91

**Comment by yllen** [comment]
Why a right? Personal is only for user that create it

**Comment by yllen** [comment]
actually all users can have their personal RSS or note.
In the future if you add a right, what do you do with personal RSS or note if the right will be disable in the profile?

**Comment by iggytof** [comment]
Bonjour,

Il serait bien utile en effet, d'avoir la possibilité de désactiver les rss personnels.
