### ISSUE TITLE
[9.2RC1] When ticket is closed, one can still add a document

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#2761]
Hello,

When ticket is closed, it is still possible to add a document.
For me, as it can't be done for Followup (nor tasks), it should not be possible to add a document when a ticket is closed.

@Yllen what's your idea about this?

Regards,
Tomolimo

**Comment by trasher** [comment]
Title may be confusing: this is not related to 9.2; as this is already the case on 9.1 at least.

**Comment by trasher** [comment]
👍 for me; I guess we should not be able to add a document when the ticket is closed.

**Comment by trasher** [comment]
Changed
