### ISSUE TITLE
SLA time to own execution issue

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#2765]
Dear All,
On glpi 9.1.6 there is an issue when time to own execution in escalation. For example I have a slt under sla which is time to own. And I create an escalation for this slt .the execution for this escalation I chose time to own from the drop down list. As I save this execution it is still time to own. But once I save it changes to time to resolve.
And the sla reminders are sent at time to resolve instead of time to own.

**Comment by roshanroche** [comment]
Dear All ,
please refer to the pics below regarding this issue. i tried even on 9.2 RC 1 the issue still persists there.
I create SLA , and under the SLA , SLT like below. and SLT is for Time to own.

![image](https://user-images.githubusercontent.com/22425503/30591578-69d10cd8-9d54-11e7-8cad-fbf95927d53b.png)
now for this SLT i create escalation like below
![image](https://user-images.githubusercontent.com/22425503/30591633-a3af6fc6-9d54-11e7-9202-a2bf6ed4c58a.png)
now under escalation i chose execution as time to own.
![image](https://user-images.githubusercontent.com/22425503/30591675-d3865ffc-9d54-11e7-8244-dc5fae5f68db.png)

everything is fine untill i click on save. once i click add this is what happens like below
![image](https://user-images.githubusercontent.com/22425503/30591720-f8f67be6-9d54-11e7-88c5-68e9bf75bbb6.png)
now the execution is time to resolve instead of time to own.

**Comment by orthagh** [comment]
Ok, see above PR, i managed to fix the display, but you say that also the computation is broken.
I'm currently checking

**Comment by orthagh** [comment]
ok tested in 9.2, the level execution seems ok.
@roshanroche, apart the broken display in sla configuration, could you confirm that in 9.2-RC (the [second was released](https://github.com/glpi-project/glpi/releases/tag/9.2-RC2) yesterday), that the send reminder is the good one

**Comment by roshanroche** [comment]
Dear @orthagh i will check this on 9.2 RC2. ( DEV )
but i can confirm on 9.1.6 ( PROD ) there is an issue with execution.

**Comment by orthagh** [comment]
yes sure, but as we changed a lot of thing in 9.2 (adding ola), it could be great to confirm the resolution (9.2 will be out next monday)

**Comment by orthagh** [comment]
Hello @roshanroche, did you have any time to test the RC2 and the triggering of sla levels  ?

**Comment by roshanroche** [comment]
Dear @orthagh @trasher ,
Sorry for the delay.
I tested the commit on 9.2 RC2. Execution issue seems to have fixed , it shows on time to own as week as time to resolve tabs on ticket next escalation properly, however email notification are not being sent. I checked for both time to own and time to resolve . Nothing in mail log for this event of SLA reminder or ticket recall.
Moreover this is on 9.2 RC2 .execution issue still persists on 9.1.6 my initial finding was on 9.1.6

**Comment by roshanroche** [comment]
Dear @orthagh @trasher ,
I confirm SLA OLA time to own and time to resolve email notification works fine. Notification sent without any issue.
I installed a fresh setup of 9.2 version . Earlier I had email notification issue while testing on 9.2RC2.
Thanks One again.
