### ISSUE TITLE
[9.2-RC1] red border for necessary fields

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2766]
I see you change the form display. the necessary field "subject" have a red border.
I have also defined "body text / description" as mandatory but also after try to send the request the border is not red.

![2017-09-15 23_14_12-glpi - einfache ansicht](https://user-images.githubusercontent.com/19192087/30503892-52ec6dcc-9a6c-11e7-9432-913df4b59b71.png)

I send but at 2 there is no red border.

One field is old function one the new ?
![old](https://user-images.githubusercontent.com/19192087/30504363-94230a10-9a6e-11e7-8b37-eb8e6c93b0a0.png)
![new](https://user-images.githubusercontent.com/19192087/30504362-9422e562-9a6e-11e7-8653-ee5bdc0daf88.png)

I hope its no bug on my installation :(

**Comment by trasher** [comment]
I don't think this is a bug; but rather an issue with rich text stuff... If I remember well, we get issues on those fields, and they're not handled exactly the same way than "standard" ones (will have to check anyways).

**Comment by trasher** [comment]
I confirm this is only when rich text is enabled... Do not know yet if it can be fixed.
