### ISSUE TITLE
[9.2-RC1] wishes for changelog / news at the release

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2767]
If i don't test enough i could run in 2 problems at the moment. It would be nice if you can add an advise in release notice

1. Old tasks (from closed ticket) on the cockpit view are displayed 
(i can't close the tasks (=done) -> good new feature but for update process the best practise is to inform all technician to close all old task which should not be opened because the tickets are already closed.

2. Bookmarks / saved searches
I think my old bookmarks where prune form the update process or is this a bug ?
Users should no this before update.

**Comment by trasher** [comment]
Hello, prefer to open one ticket per issue ;)

On the second point, this sounds like a bug. Old bookmarks should still be present on the new installation.

Does something goes wrong during the update process? Check GLPI logs to know more. Please also check contents of `glpi_savedsearches` and `glpi_savedsearches_users` tables to see if data has been lost or if this is a "display" issue.

**Comment by trasher** [comment]
We've just identified a bug that may cause issues in bookrmaks; you may try with https://github.com/glpi-project/glpi/pull/2771 patch

**Comment by Armin83** [comment]
Patch don't work for me.
First try 9.1.2 backup (without disabled plugins) from production to `9.2-**RC1** `dev system (restore db & upgrade) / All searches disappear.

second try 9.1.2 backup (without disabled plugins) from production to 9.1.6 dev system
disabled all plugins
upgrade to `9.2-rc**2** `no problem all searches are available

(no errors in update process)

**Comment by trasher** [comment]
OK then, so the issue gets fixed in the RC2; that is good news.
