### ISSUE TITLE
HTTP 414 error when a large quantity of entities is used with dropdowns

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#277]
Hello,
I got this HTTP error when using a dropdown and having a large quantity of entities defined in GLPI.
HTTP 414 means that URI is too long.
I spied the network traffic and I saw that the user dropdown is getting user names via an ajax call using the HTTP GET verb.
Could we change ajax requests to use POST instead of GET (like it was for GLPI 0.83)?
I can do it if you agree with this change?
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Me again, I would like to know why POST ajax is no longer used as it was in GLPI 0.83?
Same question for $_GET instead of $_REQUEST in PHP code?
Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
up!

**Comment by ddurieux** [comment]
I have same problem, For the moment, you can increase value in apache (LimitRequestLine)

**Comment by tomolimo** [comment]
@ddurieux: we have IIS7.5 :)
and of course I can increase this value, but the question remains: why using GET instead of POST like in the past? Is there a real answer to this question or is it just like that because of default $.Ajax call parameters?
If yes, then it can be changed very quickly...
Apart the fact that a lot of places in the codes are using $_GET and not $_REQUEST...

**Comment by ddurieux** [comment]
I think we convert POST -> GET when drop extjs and use jquery, perhaps it's not the goal to use GET (I don't know :/)

To change to POST, it require change some part of code and test it

**Comment by tomolimo** [comment]
Yes I saw that :)

**Comment by ddurieux** [comment]
I have same problem with a GLPI of a client, the URL has 26k characters (in my case when try add user in group). 
```
ajax/getDropdownUsers.php?all=0&right=all&entity_restrict%5B0%5D=0&entity_restrict%5B1%5D=1&entity_restrict%5B2%5D=2&entity_restrict%5B3%5D=3&entity_restrict%5B4%5D=4[...]
```
I'm trying find a solution for that

**Comment by ddurieux** [comment]
So I propose to put variables in POST instead GET like we have before 0.85 version.

Is it ok for that ?

**Comment by tomolimo** [comment]
Perfect for me!

**Comment by ddurieux** [comment]
I have a first version, I test in all GLPI to see if I have problems
