### ISSUE TITLE
GLPI 9.2 RC1 - Error when updating

### ISSUE THREAD

**Issue by mleblanc136** [glpi-project/glpi#2777]
Hi,

I run GLPI 9.1.6 on CentOS 7 in a virtual environnement. I want to update from GLPI 9.1.6 to GLPI 9.2RC1 and I got the following issues :

1 -  After extracting de ".tgz", I only had a message in my browser telling me to run "composer install --no-dev in my GLPI tree. Si I did what the message told me but the message kept showing. Then I removed the "composer.lock" file and it seemed to have done the trick.

2 -  At the step where GLPI is updating the database, I get the following error :
"Fatal error: Call to undefined function random_int() in /var/www/html/glpi/inc/toolbox.class.php on line 1507"

![glpi error 2](https://user-images.githubusercontent.com/16883767/30565211-71e536ac-9c95-11e7-8893-b3963faec948.jpg)

Is there something that I can do?

Thanks you for your time

**Comment by trasher** [comment]
Hello,

I guess you did something wrong... You have a `composer.lock` file but this file is not shipped in the archive!

So I thing your second issue is related; your vendor directory is probably not up to date.

Rely on the archive of the RC; and not on "source code" github's archives; and make sure you're not overriding a git/source install; with files not shipped in the release.

**Comment by mendezr23** [comment]
Hello friends
I am installing the version glpi-9.2.3 and it shows the same error, I have windows 7 32 bits, can you help me? delete the file they mention and I still have an error.
