### ISSUE TITLE
Improve web access security control to directories

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#2778]
Hi team,

As indicated by the "todo" in the code comment (:+1:) it would be nice not to test only "localhost", in some cases we must wait for timeout because "localhost" is not allowed in the web server configuration.

https://github.com/glpi-project/glpi/blob/3898f16ae0760122013ad105757c77dfa7368514/inc/config.class.php#L2455

++

**Comment by trasher** [comment]
Maybe could we rely on the HTTP_HOST if this is present?
