### ISSUE TITLE
Knowledge base: add tags and/or multiple categories for articles

### ISSUE THREAD

**Issue by nbriche** [glpi-project/glpi#278]
An article can belong to several categories.  For example, a backup protocol for a server dedicated to a particular application would be associated to a category "Backup protocols" and "Applications / &lt;ApplicationName&gt;".  That article can then be found by navigating either of the categories.
Alternatively, an article can be tagged by any number of tags, and then can be found that way.

There is, as of now, no mechanism I'm aware of that can emulate this behavior.  There is a plugin "Tag" which allows tagging of any CommonDBTM-extended object, but even though KnowbaseItem does extend CommonDBTM, the plugin's field doesn't appear.

**Comment by LeadManPL** [comment]
On GLPI 9.3.1 i can see TAGs field in KB - see attached screenshot.

![glpi_tag](https://user-images.githubusercontent.com/13769051/48066637-6ba09a00-e1ce-11e8-9574-6042771e4f94.PNG)

**Comment by trasher** [comment]
This issue is related to Tag plugin, please [use plugin issues](https://github.com/pluginsGLPI/tag/issues) for further discussions.

Thank you :)

**Comment by cedric-anne** [comment]
Actually you already talked about this on the plugin issues.

https://github.com/pluginsGLPI/tag/issues/17

**Comment by nbriche** [comment]
Indeed I did. I feel that this feature (tagging articles and look them up by tag) is either something GLPI should have in Core, in which case the Tag issue is moot ; or, this should be provided by Tag, in which case GLPI should provide a hook for plugins into the knowledge base search engine.

As I said in that comment, I don't think there's even any possibility for any plugin to insert itself into that, since the knowledge base's "home page" is apparently not derived from the main search page.

So maybe there should be a definite stand first from Core: Is KB tagging a Core issue? If Yes, then it's not a Tag issue. If No, let Tag take care of it, then Core should allow Tag to add itself to the search engine (because otherwise there's no point to add tags).

**Comment by LeadManPL** [comment]
@nbriche : I agree, TAG should be a feature of GLPI core. now I cant upgrade GLPI untill tag plugin gets upgraded too. If it was in core, it would eliminate external dependency. Is there some formal way for making such a request?

**Comment by orthagh** [comment]
It will in some times, i can't give you a final date, but we plan to do it (**maybe** in the coming year)
