### ISSUE TITLE
glpi tables stay open potentially causing data corruption errors

### ISSUE THREAD

**Issue by kandresen** [glpi-project/glpi#2798]
GLPI version 9.1.6 without plugins used to test, but likely impact 9.2 as well.
On the database server running GLPI, do the shell command: 
`myisamchk -s -w --check  /var/lib/mysql/*/*.MYI `
In best case you got several warnings like:

```
myisamchk: MyISAM file /var/lib/mysql/test1glpi/glpi_crontasks.MYI
myisamchk: warning: 1 client is using or hasn't closed the table properly
MyISAM-table '/var/lib/mysql/test1glpi/glpi_crontasks.MYI' is usable but should be fixed
```
Typical frequent errors (can still be fixed using myisamchk with the paramter"--safe-recover"): 

```
myisamchk: MyISAM file /var/lib/mysql/test1glpi/glpi_events.MYI
myisamchk: warning: 1 client is using or hasn't closed the table properly
myisamchk: error: Size of datafile is: 6140              Should be: 6204
myisamchk: error: Found key at page 4096 that points to record outside datafile
myisamchk: error: Record-count is not ok; is 90           Should be: 91
myisamchk: warning: Found         90 key parts. Should be: 91
MyISAM-table '/var/lib/mysql/test1glpi/glpi_events.MYI' is corrupted

```
If not dealt with you might run into unrecoverable errors such as these: 

```
myisamchk: MyISAM file /var/lib/mysql/glpi/glpi_ipnetworks.MYI
myisamchk: warning: Table is marked as crashed and last repair failed
myisamchk: warning: Size of indexfile is: 14336         Should be: 4096
myisamchk: Unknown error 126
myisamchk: error: Can't read indexpage from filepos: -1
myisamchk: error: Checksum for key:  1 doesn't match checksum for records
myisamchk: error: Checksum for key:  2 doesn't match checksum for records
myisamchk: error: Checksum for key:  3 doesn't match checksum for records
myisamchk: error: Checksum for key:  4 doesn't match checksum for records
myisamchk: error: Checksum for key:  5 doesn't match checksum for records
myisamchk: error: Checksum for key:  6 doesn't match checksum for records
MyISAM-table '/var/lib/mysql/glpi/glpi_ipnetworks.MYI' is corrupted
```

I did try fixing it using myisamchk with the parameters --recover --extend-check. 
I also did try using the check and recover options within phpmyadmin without results.

It would seem the problem should be easily fixed by simply closing the tables at the end of SQL queries. I for one favour stability over saving some microseconds for not closing the tables after each use.

I consider if the unrecoverable crash I received might have been mitigated with the "table_cache" parameter in "my.cnf". In newer linux distributions this seem to default to 64 tables, which I understand auto-close oldest tables if accessing tables not already open. I might be wrong, but it seem GLPI does not like it when writing to a table it expect is open, but has been been closed outside of its control?

**Comment by trasher** [comment]
GLPI no longer uses myisam but innodb; please check if your issue is reproductible with latest version.

**Comment by trasher** [comment]
No feedback from a while, closing.
