### ISSUE TITLE
[9.2-RC2] rich text enabled post-only bad ticket description view

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2799]
post-only create new ticket. (auto-assign / template to technician group)

post-only bad view
![2017-09-20 23_47_38-glpi - tickets - 5516](https://user-images.githubusercontent.com/19192087/30669415-83b379aa-9e5e-11e7-8c86-5c1e7b4b70b3.png)

technician good view
![2017-09-20 23_48_09-glpi - tickets - 5516](https://user-images.githubusercontent.com/19192087/30669417-89909894-9e5e-11e7-8029-915a04576a87.png)

**Comment by trasher** [comment]
As far as I can see, this happens on the post-only profile only just after ticket creation.

When I reload the page, rich text editor is setted up properly.
