### ISSUE TITLE
Please provide a way to enable/disable LDAP tests

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#2801]
Better to take such configuration fro env.

For php server URI, see PR #2800 

Idea: get GLPI_LDAP from env., if not define, skip the test
Probable the same should be done for GLPI_URI

ie: define('GLPI_URI', getenv('GLPI_URI');
And set GLPI_URI in travis after server is launched.

**Comment by trasher** [comment]
LDAP tests are now executed from a specific directory and a specific composer command
