### ISSUE TITLE
[9.2] alert on saved searches

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#2807]
I look for some help to use this feature. At the moment i was impossible to generate a mail i don't know why.

i found this case for documentation but the link inside isn't working anymore.

https://github.com/glpi-project/doc/pull/11

**Comment by Armin83** [comment]
Could it be that there is no default translation installed ?
https://i.imgur.com/mZodYz3.png

**Comment by Armin83** [comment]
21-09-2017 19:18 | 0.112 seconds | 0 | Action aborted
21-09-2017 19:09 | 0.099 seconds | 0 | Action aborted


[php-errors.txt](https://github.com/glpi-project/glpi/files/1322180/php-errors.txt)

**Comment by Armin83** [comment]
I added a template copy & paste the variables.
![2017-09-21 19_37_20-glpi - notification templates - 44](https://user-images.githubusercontent.com/19192087/30710015-6dde68f0-9f04-11e7-98f9-fc63865055f7.png)

**Comment by trasher** [comment]
Could you please tell me what operator you've selected in the search alert configuration; and what is the value of the `operator` column in the `glpi_savedsearches_alerts` table?

**Comment by Armin83** [comment]
tryied <1, >1, !=0

**Comment by Armin83** [comment]
![2017-10-03 17_19_41-glpi-test nach-restore-vor-9 2rcx wird ausgefuhrt - oracle vm virtualbox](https://user-images.githubusercontent.com/19192087/31133244-3309c9ea-a85f-11e7-8273-7d8e844d3530.png)

operator used < and >

**Comment by Armin83** [comment]
okay we can close this case. i got notification. i delete all bookmarks and created only one new and test again with object computer search. (before i try only with ticket search)

but

1.  can you check your system if you have also a "Action aborted" entry for the task saved_search_alert also if it sends a notification ?

2. i have for each run more entrys in php error log. One of them is "saved search #-1 seems to be broken" but i dont have a glpi_savedsearches_alerts line with id -1.

3. Other Warnings with deprecated functions
