### ISSUE TITLE
APIRest GLPI 9.1.4

### ISSUE THREAD

**Issue by polaris197** [glpi-project/glpi#2808]
I use apirest to search for computers but it seems that i can't have the 'id' of the computer in the response whatever i do, even if i use forcedisplay=[1,2,80] where 1 is name and 2 is id ?

When i use a search upon a ticket, i obtain the 'id' of the ticket in the response.

**Comment by yoshi314** [comment]
i do forcedisplay[0]=x&forcedisplay[0]=y&forcedisplay[0]=z for multiple values. Maybe that works  for you?
