### ISSUE TITLE
can't login after installation

### ISSUE THREAD

**Issue by rwahdan** [glpi-project/glpi#2810]
Hi,

I uploaded all files (V. 9.1.6) on my hosted web server account with smarterasp.net then installed the package. After installation I tried to login with the default admin user and pass glpi/glpi but i am getting the below error! the address have double entry /front/front instead of one /front! I didn't change anything in the files.

http://sendfile.cc/uploads/file/201709/0.247121001505418227.png

please help.

**Comment by ejaecker** [comment]
I too have this weird problem today after a fresh install of 9.2.1.
Install ran fine but after login page i got this message :

![image](https://user-images.githubusercontent.com/26645521/36622663-a4b71d1c-18fe-11e8-915b-205bcb240059.png)

IBTW i was also testing this with a fresh PHP-7.2.2, i wonder if it could  php options related.
any help around ?

**Comment by trasher** [comment]
This should have been fixed in latest release
