### ISSUE TITLE
[9.2 RC2] Need to correcting translations

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#2821]
Hello,
I found some not translated words.

![setup glpi 9 2 - 1](https://user-images.githubusercontent.com/17082164/30735260-0598cd3e-9f87-11e7-9d50-2419fd72e5f3.png)

![setup glpi 9 2 - translate](https://user-images.githubusercontent.com/17082164/30735254-0029d816-9f87-11e7-965f-57d2c44558a9.png)

![glpi - - google chrome 2017-09-22 08 38 17](https://user-images.githubusercontent.com/17082164/30735269-0b4948e4-9f87-11e7-8742-4e7eb0f42b04.png)

**Comment by trasher** [comment]
Strings from GLPI setup has already been fixed in c62669b00d1b0eb287a1a63785633bfa5a0b49e1.

**Comment by trasher** [comment]
And the last one are incorect on transifex (https://www.transifex.com/glpi/GLPI/viewstrings/#ru_RU/glpipot92/117063227?q=AND%20NOT )
