### ISSUE TITLE
[0.91] Add a list of associated elements on ticket creation

### ISSUE THREAD

**Issue by korial29** [glpi-project/glpi#283]
A list of associated element could be directly defined on ticket creation.
There are also impacts on other functions : 
 - Ticket rules : Allow to add multiple actions for the elements, in order to get several items to add (It is currently limited to one action).
 - Ticket template : Allow to add multiple associated elements on "Predefined values"

The specification document (in french) : 
[spécifications fonctionnelles - Eléments associés.pdf](https://github.com/glpi-project/glpi/files/43676/specifications.fonctionnelles.-.Elements.associes.pdf)

**Comment by orthagh** [comment]
Ok for me

**Comment by yllen** [comment]
Undefined index: id in /home/yllen/gitsvn/inc/item_ticket.class.php at line 238

**Comment by yllen** [comment]
fixed by me https://github.com/glpi-project/glpi/commit/b49c1f85bfc07e99c2e9f1139cb1062e9552f663

**Comment by frany88** [comment]
Hi,

Could you help me with an example PHP code to create a ticket with several associated elements?

Thanks in advance!
