### ISSUE TITLE
Delete link to document in an item

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2832]
Document created in root entity.
Item (computer, ticket...) is in sus-entity.

In item i can add link to document in root entity bu a can't delete it (rights issue)

http://forum.glpi-project.org/viewtopic.php?id=158772

**Comment by yllen** [comment]
@trasher your fix is OK for me but i don't see it even in 9.4

**Comment by trasher** [comment]
The fix I've proposed had issues (but to be honest, it is way too old to me to remember what the problem was...) and it has never been merged.
