### ISSUE TITLE
Error loading consumibles on v9.2

### ISSUE THREAD

**Issue by gituncar** [glpi-project/glpi#2833]
My log with debug enable

PHP Notice: Undefined index: table in C:\xampp\htdocs\glpi\inc\search.class.php at line 2271
PHP Notice: Undefined index: field in C:\xampp\htdocs\glpi\inc\search.class.php at line 2272
PHP Notice: Undefined index: linkfield in C:\xampp\htdocs\glpi\inc\search.class.php at line 2286
PHP Notice: Uninitialized string offset: 0 in C:\xampp\htdocs\glpi\inc\toolbox.class.php at line 77
PHP Notice: Undefined index: table in C:\xampp\htdocs\glpi\inc\search.class.php at line 368
PHP Notice: Undefined index: table in C:\xampp\htdocs\glpi\inc\search.class.php at line 370
PHP Notice: Undefined index: linkfield in C:\xampp\htdocs\glpi\inc\search.class.php at line 371
PHP Notice: Undefined index: joinparams in C:\xampp\htdocs\glpi\inc\search.class.php at line 372
PHP Notice: Undefined index: field in C:\xampp\htdocs\glpi\inc\search.class.php at line 373
PHP Catchable Fatal Error: Argument 1 passed to Search::computeComplexJoinID() must be of the type array, null given, called in C:\xampp\htdocs\glpi\inc\search.class.php on line 3607 and defined in C:\xampp\htdocs\glpi\inc\search.class.php at line 6153

**Comment by Panditax** [comment]
Actually it seems this fix doesn't work. I've just upgraded GLPI from 9.1.6 to 9.2.1 and I have the following notices:
```
PHP Notice: Undefined index: table in /usr/share/glpi/inc/search.class.php at line 2301
PHP Notice: Undefined index: field in /usr/share/glpi/inc/search.class.php at line 2302
PHP Notice: Undefined index: linkfield in /usr/share/glpi/inc/search.class.php at line 2316
PHP Notice: Uninitialized string offset: 0 in /usr/share/glpi/inc/toolbox.class.php at line 77
PHP Notice: Undefined index: table in /usr/share/glpi/inc/search.class.php at line 368
PHP Notice: Undefined index: table in /usr/share/glpi/inc/search.class.php at line 370
PHP Notice: Undefined index: linkfield in /usr/share/glpi/inc/search.class.php at line 371
PHP Notice: Undefined index: joinparams in /usr/share/glpi/inc/search.class.php at line 372
PHP Notice: Undefined index: field in /usr/share/glpi/inc/search.class.php at line 373
```
