### ISSUE TITLE
[9.1] Unable to search computers in API via exact match to ip address

### ISSUE THREAD

**Issue by yoshi314** [glpi-project/glpi#2837]
I am trying to find a host with specific ip via API .

For some reason this search fails ( address - ip equals 1.2.3.4)

`criteria[0][field]=126&criteria[0][searchtype]=equals&criteria[0][value]=1.2.3.4`

but this works ( address - ip contains 1.2.3.4 ) 

`criteria[0][field]=126&criteria[0][searchtype]=contains&criteria[0][value]=1.2.3.4`

unfortunately, this includes hosts whose address starts with 1.2.3.4, like 1.2.3.41, 1.2.3.49 , etc.

The very same thing happens in web interface. I tried various types of quoting in equals match when doing api queries but that only produced 0 results or sql errors.

**Comment by ladenree76000** [comment]
did you try 
criteria[0][value]=^1.2.3.4$

**Comment by yoshi314** [comment]
Not, yet but i noticed that adding $ at the end gives me the expected output.

**Comment by ladenree76000** [comment]
1.2.3.4$ => 1.2.3.4 matches but also 11111.2.3.4
try with ^ at the beginning

**Comment by ladenree76000** [comment]
read api serach documentation :+1: Parameters: (query string)

    criteria: array of criterion objects to filter search. Optional. Each criterion object must provide:
        link: (optional for 1st element) logical operator in [AND, OR, AND NOT, AND NOT].
        field: id of the searchoption.
        searchtype: type of search in [contains¹, equals², notequals², lessthan, morethan, under, notunder].
        value: the value to search.

    **¹ - contains will use a wildcard search per default. You can restrict at the beginning using the ^ character, and/or at the end using the $ character.
² - equals and notequals are designed to be used with dropdowns. Do not expect those operators to search for a strictly equal value (see ¹ above).**

**Comment by yoshi314** [comment]
Yes, but my point was that 'equals' doesn't work at all.

**Comment by yoshi314** [comment]
So why is equals a valid option for ip address?

**Comment by orthagh** [comment]
Because, this endpoint exposes all the options of the search engines used by the former frontend of glpi.
So you can combine parameter which cannot be combined normalely.

It's a common mistake (we added the notas after repeaded issues), and i think about adding a warning into the json response when using `equals` with non integer `value`
