### ISSUE TITLE
[GLPI 9.1.4] Fatal Error to access SLA - SLT Configuration

### ISSUE THREAD

**Issue by LordBat** [glpi-project/glpi#2838]
Hi, when i try to configure the SLA - SLT i have this error.

![image](https://user-images.githubusercontent.com/19165739/30859587-bc46d1c8-a29a-11e7-9585-3ff23e845e61.png)

i dont have any error logs on .../glpi/files/_log

Server Info:

Ubuntu 14.04 LTS server
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3
PHP Version 5.5.9-1ubuntu4.22
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 27 2017 15:20:24

Any idea?

Thanks in advance! Regards!

**Comment by LordBat** [comment]
anyone? please?

**Comment by trasher** [comment]
As said on IRC? you should have something logged in your sql-errors file.

Maybe using debug mode should helps as well.

**Comment by LordBat** [comment]
hi trasher, thanks for your response.

How can know who is logged on sql-errors file? 

I am using on debug mode but when i have that error the "debug mode hyperlink" dissapear.

this is before select one of this "Nivel 1" hyperlink,

![image](https://user-images.githubusercontent.com/19165739/30917555-aba40056-a372-11e7-9df1-38b739747e47.png)

after select "Nivel 1" Hyperlink i got this...

![image](https://user-images.githubusercontent.com/19165739/30918213-3ca8bb18-a374-11e7-8427-c40f517ec95a.png)


No debug tab or scrollbar

Thanks and regards!

**Comment by LordBat** [comment]
Hi i was able to solve the issue doing this steps.

1 - Complete backup of  DB
2 - Full copy of the productive GLPI 0.90.1
3 - Creation of DB with exact parameters to the current productive to a test enviroment.
4 - Restoration of the new DB.
5 - Corroboration of access (0.90.1)
6 - Paste the glpi folder 9.1.4
7 - It is done the update of tables without errors
8 - The new version is accessed and it is confirmed that the SLA configuration area works correctly.

thanks for the patience and regards trasher!
