### ISSUE TITLE
Can't create SLAs into Service Levels

### ISSUE THREAD

**Issue by rmundel** [glpi-project/glpi#2848]
After enable all the SLM permissions in the target profile (Super-Admin), I was able to create a new Service Level but when I tried to create a SLA inside that Service Level I got some kind of GLPInception with the "You don't have permssion to perform this action" message, as following:

![image](https://user-images.githubusercontent.com/13142574/30923644-6f310d6e-a37a-11e7-94f5-48d792250bb2.png)

PS.: I just upgraded from 9.1.6.

--
[code]   GLPI 9.2 ( => /var/www/clients/client0/web20/web)

Operating system: Linux panel 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 PHP 7.0.22-0ubuntu0.16.04.1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, calendar, cgi-fcgi, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, 	mbstring, mcrypt, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, session, 	shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="512M" post_max_size="512M" safe_mode="" session.save_handler="files" 	upload_max_filesize="512M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at suporte.digitalwaveti.com.br Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 Server Software: Ubuntu 16.04 	Server Version: 10.0.31-MariaDB-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: c0admin@localhost/c0glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /var/www/clients/client0/web20/web/config : OK /var/www/clients/client0/web20/web/files : OK /var/www/clients/client0/web20/web/files/_dumps : OK /var/www/clients/client0/web20/web/files/_sessions : OK /var/www/clients/client0/web20/web/files/_cron : OK /var/www/clients/client0/web20/web/files/_graphs : OK /var/www/clients/client0/web20/web/files/_lock : OK /var/www/clients/client0/web20/web/files/_plugins : OK /var/www/clients/client0/web20/web/files/_tmp : OK /var/www/clients/client0/web20/web/files/_rss : OK /var/www/clients/client0/web20/web/files/_uploads : OK /var/www/clients/client0/web20/web/files/_pictures : OK /var/www/clients/client0/web20/web/files/_log : OK

htmLawed version 1.2.4 in (/var/www/clients/client0/web20/web/lib/htmlawed) phpCas version 1.3.5 in (/var/www/clients/client0/web20/web/vendor/jasig/phpcas/source) PHPMailer version 5.2.24 in (/var/www/clients/client0/web20/web/vendor/phpmailer/phpmailer) SimplePie version 1.5 in (/var/www/clients/client0/web20/web/vendor/simplepie/simplepie/library) TCPDF version 6.2.13 in (/var/www/clients/client0/web20/web/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/clients/client0/web20/web/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/clients/client0/web20/web/vendor/true/punycode/src) iacaml/autolink in (/var/www/clients/client0/web20/web/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/clients/client0/web20/web/vendor/sabre/vobject/lib)

Not active

Way of sending emails: SMTP (suporte@digitalwaveti.com.br@mail.digitalwaveti.com.br)

fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Enabled 	mreporting           Name: Mais Relatórios                Version: 1.4.0      State: Enabled 	showloading          Name: Mostrar Carregamento           Version: 1.0.0      State: Enabled 	browsernotification  Name: Notificação do navegador       Version: 1.1.9      State: Enabled 	genericobject        Name: Objects management             Version: 2.4.0      State: Not activated 	dashboard            Name: Painel                         Version: 0.8.6      State: Enabled

**Comment by igortarasiuk** [comment]
I have the same problem too.

**Comment by igortarasiuk** [comment]
GLPI 9.2.1 ( => /srv/www/vhosts/support.univest.ua)
Installation mode: TARBALL

Operating system: Linux up-www-lo 3.0.101-107-default #1 SMP Thu Jun 22 14:37:55 UTC 2017 (414ea9f) x86_64 PHP 5.6.26 apache2handler (Core, PDO, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2, ctype, 	curl, date, dom, ereg, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, mhash, 	mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, session, soap, sqlite3, standard, tidy, 	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: Apache/2.2.34 (Linux/SUSE) (Apache/2.2.34 (Linux/SUSE) Server at support.univest.ua Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 Server Software: openSUSE package 	Server Version: 5.5.33-MariaDB-log 	Server SQL Mode:  	Parameters: glpiuser@10.210.101.29/www_in_glpi 	Host info: 10.210.101.29 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /srv/www/vhosts/support.univest.ua/config : OK /srv/www/vhosts/support.univest.ua/files : OK /srv/www/vhosts/support.univest.ua/files/_dumps : OK /srv/www/vhosts/support.univest.ua/files/_sessions : OK /srv/www/vhosts/support.univest.ua/files/_cron : OK /srv/www/vhosts/support.univest.ua/files/_graphs : OK /srv/www/vhosts/support.univest.ua/files/_lock : OK /srv/www/vhosts/support.univest.ua/files/_plugins : OK /srv/www/vhosts/support.univest.ua/files/_tmp : OK /srv/www/vhosts/support.univest.ua/files/_cache : OK /srv/www/vhosts/support.univest.ua/files/_rss : OK /srv/www/vhosts/support.univest.ua/files/_uploads : OK /srv/www/vhosts/support.univest.ua/files/_pictures : OK /srv/www/vhosts/support.univest.ua/files/_log : OK
--

htmLawed version 1.2.4 in (/srv/www/vhosts/support.univest.ua/lib/htmlawed) phpCas version 1.3.5 in (/srv/www/vhosts/support.univest.ua/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/srv/www/vhosts/support.univest.ua/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/srv/www/vhosts/support.univest.ua/vendor/simplepie/simplepie/library) TCPDF version 6.2.13 in (/srv/www/vhosts/support.univest.ua/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/srv/www/vhosts/support.univest.ua/vendor/michelf/php-markdown/Michelf) true/punycode in (/srv/www/vhosts/support.univest.ua/vendor/true/punycode/src) iacaml/autolink in (/srv/www/vhosts/support.univest.ua/vendor/iamcal/lib_autolink) sabre/vobject in (/srv/www/vhosts/support.univest.ua/vendor/sabre/vobject/lib)


Plugins list
--
appliances           Name: Appliances                     Version: 2.3.0      State: Enabled 	badges               Name: Badges                         Version: 2.3.0      State: Enabled 	connections          Name: Connections                    Version: 0.90-1.7.3 State: Enabled 	databases            Name: Databases                      Version: 2.0.0      State: Enabled 	environment          Name: Environment                    Version: 2.1.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.1.5      State: Enabled 	hidefields           Name: Hidefields                     Version: 1.0.0      State: Enabled 	addressing           Name: IP Adressing                   Version: 2.5.0      State: Not activated 	itilcategorygroups   Name: ItilCategory Groups            Version: 2.0.1      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.6      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.4.0      State: Enabled 	physicalinv          Name: Physical inventory             Version: 9.1+1.1    State: Not activated 	tag                  Name: Tag Management                 Version: 2.1.0      State: Not activated 	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Not activated 	typology             Name: Typologies                     Version: 2.4.0      State: Enabled 	webapplications      Name: Web applications               Version: 2.4.0      State: Enabled 	webservices          Name: Web Services                   Version: 1.6.0      State: Not activated 	accounts             Name: Аккаунты                       Version: 2.3.0      State: Enabled 	domains              Name: Домены                         Version: 1.9.0      State: Not activated 	fields               Name: Дополнительные поля    Version: 1.6.0      State: Enabled 	additionalalerts     Name: Другие уведомления      Version: 1.9.0      State: Not activated 	manufacturersimports Name: Импорт поставщиков      Version: 2.0.0      State: Enabled 	positions            Name: Картография                   Version: 4.4.0      State: Enabled 	racks                Name: Конфигурация стойки    Version: 1.8.0      State: Enabled 	reports              Name: Отчет                          Version: 1.11.0     State: Enabled 	purgelogs            Name: Очистка истории            Version: 1.3.0      State: Enabled 	dashboard            Name: Панель отчетов              Version: 0.8.8      State: Enabled 	escalade             Name: Переназначение             Version: 2.2.1      State: Enabled 	pdf                  Name: Печать в PDF                   Version: 1.3.0      State: Enabled 	mreporting           Name: Подробные отчеты          Version: 1.4.0      State: Enabled 	financialreports     Name: Состояние оборудования Version: 2.4.0      State: Enabled 	news                 Name: Уведомления                   Version: 1.3.4      State: Enabled 	simcard              Name: Управление SIM-картами  Version: 1.4.2      State: Enabled 	formcreator          Name: Формы                          Version: 2.6.0      State: Enabled 	resources            Name: Человеческие Ресурсы  Version: 2.3.2      State: To be cleaned

**Comment by hesleymagno** [comment]
I have the same problem.

**Comment by hesleymagno** [comment]
solve the problem.

I accessed the database, added a "slms_id" field of type "Integer" of size "11" inside the table "glpi_slas", then I added a value "1" to that field.

**Comment by trasher** [comment]
So, you get an upgrade issue you did not take care about :/
