### ISSUE TITLE
Unable to make search on components

### ISSUE THREAD

**Issue by gmourani** [glpi-project/glpi#2849]
Hello,

GLPI version: 9.1.6
PHP version: 5.5.11

Selecting a computer from the list then clicking on the "Components" tab on the left bar to make a search based on components to be added doesn't work. The pull down menu list all components but making a search for something return nothing! You have to scroll on the list and select the component you want to add. This is annoying when you have lot of component listed.

Regards,

**Comment by gmourani** [comment]
Still no answer here. Added an image to help understand the point!
![screen shot 2018-02-19 at 10 47 44 am](https://user-images.githubusercontent.com/20328799/36386028-6fe836f6-1562-11e8-8f8d-ec2bc9ec798f.png)

**Comment by trasher** [comment]
Just tested on current 9.2/bugfixes branch and it works. Bug may have been solved
