### ISSUE TITLE
[9.2] Copy and Paste

### ISSUE THREAD

**Issue by alias59** [glpi-project/glpi#2851]
Hello,

The Copy and Paste or move directly in the solution not working

Regards.

**Comment by orthagh** [comment]
Hello @alias59 
You're right, solutions didn't have the parsing of pasted/dropped images.

Here is the correction: https://github.com/glpi-project/glpi/pull/2853/files#diff-76fabfb4d595f943e6103984d4163544 (il will be included in 9.2.1)

**Comment by alias59** [comment]
@orthagh I am proced a the modication the files. But the problem is always the
