### ISSUE TITLE
[9.2] No display on networkequipment

### ISSUE THREAD

**Issue by chauchse** [glpi-project/glpi#2854]
Dear, 
Since upgrade 9.1 to 9.2, i have no result displayed on network equipement menu. 
When i activate DEBUG mode... There is the following SQL request which have a problem 👍 

SELECT 'xxxxx' AS currentuser, `glpi_networkequipments`.`entities_id`, `glpi_networkequipments`.`is_recursive`, `glpi_networkequipments`.`name` AS `ITEM_0`, `glpi_networkequipments`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_states`.`completename` AS `ITEM_2`, `glpi_manufacturers`.`name` AS `ITEM_3`, `glpi_locations`.`completename` AS `ITEM_4`, `glpi_networkequipmenttypes`.`name` AS `ITEM_5`, `glpi_networkequipmentmodels`.`name` AS `ITEM_6`, `glpi_networkequipments`.`date_mod` AS `ITEM_7`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`name`, '__NULL__'), '$#$',`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`id`) SEPARATOR '$$##$$') AS `ITEM_8`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_networkports`.`mac`, '__NULL__'), '$#$',`glpi_networkports`.`id`) SEPARATOR '$$##$$') AS `ITEM_9`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_vlans`.`name`, '__NULL__'), '$#$',`glpi_vlans`.`id`) SEPARATOR '$$##$$') AS `ITEM_10`, GROUP_CONCAT(DISTINCT ADDDATE(`glpi_infocoms`.`warranty_date`, INTERVAL (`glpi_infocoms`.`warranty_duration` ) MONTH) SEPARATOR '$$##$$') AS `ITEM_11`, `glpi_networkequipments`.`serial` AS `ITEM_12`, `glpi_networkequipments`.`id` AS id 
FROM `glpi_networkequipments`
LEFT JOIN `glpi_entities` ON (`glpi_networkequipments`.`entities_id` = `glpi_entities`.`id` )
LEFT JOIN `glpi_states` ON (`glpi_networkequipments`.`states_id` = `glpi_states`.`id` )
LEFT JOIN `glpi_manufacturers` ON (`glpi_networkequipments`.`manufacturers_id` = `glpi_manufacturers`.`id` )
LEFT JOIN `glpi_locations` ON (`glpi_networkequipments`.`locations_id` = `glpi_locations`.`id` )
LEFT JOIN `glpi_networkequipmenttypes` ON (`glpi_networkequipments`.`networkequipmenttypes_id` = `glpi_networkequipmenttypes`.`id` )
LEFT JOIN `glpi_networkequipmentmodels` ON (`glpi_networkequipments`.`networkequipmentmodels_id` = `glpi_networkequipmentmodels`.`id` ) 
LEFT JOIN `glpi_ipaddresses` AS `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540` ON (`glpi_networkequipments`.`id` = `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitems_id` AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitemtype` = 'NetworkEquipment' AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`is_deleted` = 0 ) 
LEFT JOIN `glpi_networkports` ON (`glpi_networkequipments`.`id` = `glpi_networkports`.`items_id` AND `glpi_networkports`.`itemtype` = 'NetworkEquipment' ) 
LEFT JOIN `glpi_vlans` ON (`glpi_networkequipments`.`vlans_id` = `glpi_vlans`.`id` ) 
LEFT JOIN `glpi_infocoms` ON (`glpi_networkequipments`.`id` = `glpi_infocoms`.`items_id` AND `glpi_infocoms`.`itemtype` = 'NetworkEquipment' ) 
WHERE `glpi_networkequipments`.`is_deleted` = '0' AND `glpi_networkequipments`.`is_template` = '0' GROUP BY `glpi_networkequipments`.`id` 
ORDER BY ITEM_0 ASC LIMIT 0, 150

Error Code: 1054. Unknown column 'glpi_networkequipments.vlans_id' in 'on clause'

Thanks for helping

**Comment by purdy87** [comment]
Same problem here and same problem in "Global"

**Comment by trasher** [comment]
This happens when "VLAN" is added to the view

**Comment by purdy87** [comment]
No, it´s not.

Problem in Networkequipment is the missing column "vlans_id" in Table "glpi_networkequiments". 

Problem in Global: Unknown column 'glpi_certificates.contact' in 'field list'

**Comment by trasher** [comment]
So you are talking about 2 different issues; you did not mention the second one in your initial issue. Anyways...

**Comment by trasher** [comment]
I cannot reproduce the second issue; please open a separate ticket with as many details you can provide (and if you can see the certificates list only or if issue is the same).

**Comment by sylvnb** [comment]
Hello,
Same problem for me (9.2): Unknown column 'glpi_networkequipments.vlans_id' in 'on clause'.
This happens when "VLANs" is added to the view.

To refind my view "network equipements":
- I added the column 'vlans_id' to the table 'glpi_networkequipements'
- I refresh my view "network equipements" on GLPI
- I deleted "VLANs" to the view
- I deleted the column 'vlans_id' to the table 'glpi_networkequipements'
