### ISSUE TITLE
PHP Warning on telemetry example page

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#2856]
During v9.2 installation process one can see an example of telemetry data.

Clicking the "_See what would be sent..._" link opens a popin of URL https://glpi.example.com/ajax/telemetry.php

Where the following error is displayed on the first line (note: the telemetry data example are present):

> PHP Warning: get_headers(http://localhost/glpi/): failed to open stream: HTTP request failed! in .../inc/telemetry.class.php at line 146

It looks like an (bad) assumption is done on path to GLPI instance: it thinks it is installed in a sub-directory "/glpi".

Using:
* GLPI v9.2
* PHP v5.6.30 (with Zend OPcache v7.0.6)
* Apache v2.4.10

**Comment by trasher** [comment]
We use the URI configured in the preferences... So, yes, when installing, this may be wrong.

But there is something which should prevent bad uris; maybe we missed a special case.

**Comment by C-Duv** [comment]
Precision: it was on a fresh installation. When doing an upgrade problem did not occurred.

**Comment by AnaelMobilia** [comment]
Hi @C-Duv 
I was unable to reproduce with a fresh install of GLPI v9.2.2 / Apache 2.4.25 / PHP 5.6.30 / Windows 10 (xamp).

Could you, please, provide more informations about your environnement ?
Did you used the server IP address or a DNS alias ?
On your log on have localhost and glpi.example.com => which one did you used ?

Regards,
Anael

**Comment by trasher** [comment]
@AnaelMobilia I guess you can reproduce using a specific domain name (from a vhost configuration) or a "non default path" (ie. GLPI called from http://localhost/my-glpi/) when installing.
