### ISSUE TITLE
Prueba de la extensión APCu	 La extensión APCu no está presente

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2857]
at install or update version 9.2 says this:
Prueba de la extensión APCu	 La extensión APCu no está presente

 how can i solve this? thankyou.

**Comment by remicollet** [comment]
This is only a warning.

You can ignore it or fix it by installing this extension.

Not a bug.

**Comment by sferia82** [comment]
how can i install this extension in wampserver? thank you
