### ISSUE TITLE
create ticket from an item

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2858]
i have 4 entities
root
   region
       entity 1
       entity 2

I'm on the region recursive

I choose a computer of entity 2 (not recursive one, just in this entity)
On ticket tab i create a ticket about this item. Item in associated to the ticket.
At the ticket creation, i choose a user from entity 1. ticket is created in this entity

Finally i have a ticket created in entity 1 with an item of entity 2

For me, before creation of the ticket, check must be done between entity of creation and item associated to the ticket

**Comment by yllen** [comment]
http://forum.glpi-project.org/viewtopic.php?id=159069

**Comment by trasher** [comment]
Duplicates #2173
