### ISSUE TITLE
Upgrade to 9.2

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#2863]
Hi.
On upgrade to 9.2 version I came across the following error:

PHP Notice: Undefined index: dbversion in /var/www/servicedesk.municipiopcr.local/html/glpi/inc/config.php at line 259

After click Upgrade, still stopped with this:

Database connection successful
Change of the database layout - glpi_states (1 second)
Update to 9.2
Work in progress...
     9.2 multiple alter in glpi_states - Error during the database query: ALTER TABLE `glpi_states` ADD UNIQUE `unicity` (`states_id`, `name`) , ADD INDEX `is_visible_line` (`is_visible_line`) - Error is Duplicate entry '0-Abatido' for key 'unicity'

Can someone help?

**Comment by trasher** [comment]
The notice is not really important (will be fixed, but should not change behavior).

As for the state issue; see https://github.com/glpi-project/glpi/issues/2847#issuecomment-332811145

**Comment by rjmontenegro** [comment]
Thanks.
Solved.

**Comment by jctcom** [comment]
Hello.  I have this exact issue on my Synology NAS since several months now.  How can I get that fixed?

Carl
