### ISSUE TITLE
Can't update Operating system

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2864]
In operating system of a computer, if i change the field Name
"Cannot update item: not enough right's on the parent(s) item(s)"

In massive action, action indicated successfully but nothing done.
For change input "N/A (1516): Incompatible Items"

See also: http://forum.glpi-project.org/viewtopic.php?id=159124

**Comment by yllen** [comment]
For me the correction is not correct. entities_id must stay for performance.
The correct correction is to add oeratingsytem in object managed with formard_entity_to of a computer

**Comment by remicollet** [comment]
Seems OK forward_entity_to and optimization is for `CommonDBChild`, not needed for `CommonDBRelation`

My fault, sorry for the noise

Checker (may become a unit test)

```
<?php
require 'inc/includes.php';

echo "+ Login\n";
$auth = new Auth();
var_dump($auth->login('glpi', 'glpi', true));

var_dump(Session::changeActiveEntities(2, true));

echo "+ Disk\n";
$d = new ComputerDisk();
var_dump($d->can(1, READ));
var_dump($d->can(2, READ));

echo "+ OS\n";
$o = new Item_OperatingSystem();

var_dump($o->can(1, READ));
var_dump($o->can(2, READ));
```

All id=1 belongs to Entity 1, id=2 to Entity=2

Ouput
```
+ Login
  From Config::getCache() in /work/GLPI/92-bugfixes/inc/config.class.php line 2752
  Service with name "Zend\Cache\Storage\Adapter\Apcu" could not be created. Reason: ext/apcu is disabled - see 'apc.enabled' and 'apc.enable_cli' 
bool(true)
bool(true)
+ Disk
bool(false)
bool(true)
+ OS
bool(false)
bool(true)
```

So right check seems ok.

**Comment by remicollet** [comment]
BTW, the `forward_entity_to` way seems a better fix

**Comment by yllen** [comment]
$forward_entity_to is used in update of commonDBTM
and it also defined in calendar that iis a commonDropdown, not CommonDbChild or CommonDBRelation

**Comment by trasher** [comment]
Should not have been closed... Was a revert :D
