### ISSUE TITLE
Échec de l'envoi du courriel de test à l'administrateur

### ISSUE THREAD

**Issue by Mystikal57** [glpi-project/glpi#2866]
hello

Since the migration from 9.1.x to 9.2 mails sending doesn't work:
Échec de l'envoi du courriel de test à l'administrateur

No changes in parameters.
Just upgraded php to 5.6.31, but tested rollback to 5.3 -> ko

**Comment by trasher** [comment]
Are you sure your mail parameters are correct?
Check log files for any extra errors.

**Comment by trasher** [comment]
No feedback provided, closing

**Comment by Leonchel** [comment]
bonjour j'ai le même le soucis

**Comment by Leonchel** [comment]
Échec de l'envoi du courriel de test à l'administrateur
