### ISSUE TITLE
Add template task

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#287]
Please add template task

http://glpi.userecho.com/topic/921252-templates-for-tasks/ 

A lot of GLPI users are requesting this feature. And the same for Changes

**Comment by dgsn** [comment]
Yes, please...

**Comment by dgsn** [comment]
voir #184.
On dirait que c'est parti.
SUPER!!!

**Comment by yllen** [comment]
#184 ne peut pas être appliqué car concerne la version 0.90 qui est désormais maintenant figée.

**Comment by orthagh** [comment]
J'ai demandé au dev (mon collègue de bureau) de reprendre sa pr pour la mettre sur une cible 0.91.
Ce sera bientôt fait.
