### ISSUE TITLE
[9.2] Bug "rn" in the ticket description

### ISSUE THREAD

**Issue by alias59** [glpi-project/glpi#2870]
Hello,

The ticket description not take the return at ligne
For each return at ligne and remplace by "rn"

Thanks
Regards

**Comment by sferia82** [comment]
whats is the final solution? it doesn't work well.  :( 

thank you.

**Comment by trasher** [comment]
@sferia82 what does not work well?

For the moment, there is no solution; only a fix proposal (#2872) that is not approved for some reasons.

**Comment by sferia82** [comment]
doesn't collect mails.

**Comment by trasher** [comment]
This issue is about carriage return issues.

**Comment by sferia82** [comment]
yes, but when i fix with the proposed solution it doesn't collect mails.  i return to original code 9.2

**Comment by Rico29** [comment]
Hi, Any news about this bug ?

**Comment by Deelight-fr** [comment]
Everything seems to work ok when rich text is enabled.

**Comment by sferia82** [comment]
how i active rich mode in the body of ticket?
thanks.

**Comment by Deelight-fr** [comment]
Home > Setup > General > Assistance Tab
http://i.imgur.com/YGCVqsN.png

**Comment by trasher** [comment]
@Deelight-fr everything is ok? including mail collector? (see https://github.com/glpi-project/glpi/issues/2870#issuecomment-334128341)

**Comment by lcpj** [comment]
my rich text (TinyMCE) is enable and it stills whows RN when it is suposed to be a CRLF

**Comment by Deelight-fr** [comment]
If you have edited a ticket while rich text was turned off, the "rn" is now probably stored in database. I had to manually fix these entries (couldn't do a search & replace on such a common term).

**Comment by JulienG78** [comment]
I really hope this will be fixed very soon because it's horrible to manage with this problem.
