### ISSUE TITLE
[9.2] Error loading Global View

### ISSUE THREAD

**Issue by purdy87** [glpi-project/glpi#2874]
SQL-Error: 
Unknown column 'glpi_certificates.contact' in 'field list'

`

N° | Queries | Time | Errors
-- | -- | -- | --
1 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fields' | 0.000 |  
2 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'fields' | 0.000 |  
3 | SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'glpi' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_fields_containers%' | 0.016 |  
4 | SELECT * FROM `glpi_plugin_fields_containers` WHERE `type` = 'tab' AND is_active = 1 ORDER BY `label` | 0.000 |  
5 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'datainjection' | 0.000 |  
6 | SELECT DISTINCT `itemtypes` FROM `glpi_plugin_fields_containers` WHERE 1=1 | 0.000 |  
7 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'mreporting' | 0.000 |  
8 | SELECT `glpi_plugins`.* FROM `glpi_plugins` WHERE `glpi_plugins`.`directory` = 'mreporting' | 0.000 |  
9 | SELECT * FROM `glpi_plugin_mreporting_profiles` WHERE `profiles_id` = '4' AND `right` = 1 | 0.000 |  
10 | SHOW COLUMNS FROM `glpi_computers` | 0.016 |  
11 | SHOW COLUMNS FROM `glpi_monitors` | 0.000 |  
12 | SHOW COLUMNS FROM `glpi_softwares` | 0.016 |  
13 | SHOW COLUMNS FROM `glpi_networkequipments` | 0.000 |  
14 | SHOW COLUMNS FROM `glpi_peripherals` | 0.016 |  
15 | SHOW COLUMNS FROM `glpi_printers` | 0.000 |  
16 | SHOW COLUMNS FROM `glpi_cartridgeitems` | 0.016 |  
17 | SELECT `glpi_entities`.* FROM `glpi_entities` WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
18 | SHOW COLUMNS FROM `glpi_consumableitems` | 0.000 |  
19 | SELECT `glpi_entities`.* FROM `glpi_entities` WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
20 | SHOW COLUMNS FROM `glpi_phones` | 0.016 |  
21 | SHOW COLUMNS FROM `glpi_tickets` | 0.000 |  
22 | SHOW COLUMNS FROM `glpi_problems` | 0.031 |  
23 | SHOW COLUMNS FROM `glpi_changes` | 0.016 |  
24 | SHOW COLUMNS FROM `glpi_ticketrecurrents` | 0.000 |  
25 | SHOW COLUMNS FROM `glpi_softwarelicenses` | 0.016 |  
26 | SHOW COLUMNS FROM `glpi_budgets` | 0.000 |  
27 | SHOW COLUMNS FROM `glpi_suppliers` | 0.016 |  
28 | SHOW COLUMNS FROM `glpi_contacts` | 0.000 |  
29 | SHOW COLUMNS FROM `glpi_contracts` | 0.016 |  
30 | SELECT `glpi_entities`.* FROM `glpi_entities` WHERE `glpi_entities`.`id` = '0' LIMIT 1 | 0.000 |  
31 | SHOW COLUMNS FROM `glpi_documents` | 0.000 |  
32 | SHOW COLUMNS FROM `glpi_lines` | 0.016 |  
33 | SHOW COLUMNS FROM `glpi_certificates` | 0.000 |  
34 | SHOW COLUMNS FROM `glpi_projects` | 0.016 |  
35 | SHOW COLUMNS FROM `glpi_reminders` | 0.000 |  
36 | SHOW COLUMNS FROM `glpi_rssfeeds` | 0.000 |  
37 | SHOW COLUMNS FROM `glpi_knowbaseitems` | 0.000 |  
38 | SELECT * FROM `glpi_plugin_mreporting_dashboards` WHERE users_id = 9626 | 0.000 |  
39 | SHOW COLUMNS FROM `glpi_users` | 0.016 |  
40 | SHOW COLUMNS FROM `glpi_groups` | 0.000 |  
41 | SHOW COLUMNS FROM `glpi_entities` | 0.016 |  
42 | SELECT COUNT(*) AS cpt FROM `glpi_mailcollectors` | 0.000 |  
43 | SHOW COLUMNS FROM `glpi_profiles` | 0.000 |  
44 | SELECT DISTINCT `name` FROM `glpi_profilerights` | 0.000 |  
45 | SELECT * FROM `glpi_plugin_fields_fields` WHERE `type` = 'dropdown' | 0.000 |  
46 | SHOW COLUMNS FROM `glpi_mailcollectors` | 0.000 |  
47 | SHOW COLUMNS FROM `glpi_links` | 0.000 |  
48 | SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'glpi' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_fields_containers%' | 0.016 |  
49 | SELECT * FROM `glpi_plugin_fields_containers` WHERE 1=1 AND is_active = 1 ORDER BY `label` | 0.000 |  
50 | SELECT * FROM `glpi_plugin_fields_profiles` WHERE `profiles_id` = '4' AND `plugin_fields_containers_id` = '5' AND `right` >= 1 | 0.000 |  
51 | SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = 'glpi' AND TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME LIKE '%glpi_plugin_fields_containers%' | 0.000 |  
52 | SELECT * FROM `glpi_plugin_fields_containers` WHERE 1=1 AND is_active = 1 ORDER BY `label` | 0.000 |  
53 | SELECT * FROM `glpi_plugin_fields_profiles` WHERE `profiles_id` = '4' AND `plugin_fields_containers_id` = '5' AND `right` >= 1 | 0.000 |  
54 | SELECT fields.name, fields.label, fields.type, fields.is_readonly, containers.name as container_name, containers.label as container_label, containers.itemtypes, containers.id as container_id, fields.id as field_id FROM glpi_plugin_fields_containers containers INNER JOIN glpi_plugin_fields_fields fields ON containers.id = fields.plugin_fields_containers_id AND containers.is_active = 1 WHERE containers.itemtypes LIKE '%Computer%' AND fields.type != 'header' ORDER BY fields.id ASC | 0.000 |  
55 | SELECT * FROM `glpi_plugin_fields_labeltranslations` WHERE `plugin_fields_itemtype` = 'PluginFieldsContainer' AND `plugin_fields_items_id`='5' AND `language` = 'de_DE' | 0.000 |  
56 | SELECT * FROM `glpi_plugin_fields_labeltranslations` WHERE `plugin_fields_itemtype` = 'PluginFieldsField' AND `plugin_fields_items_id`='6' AND `language` = 'de_DE' | 0.000 |  
57 | SELECT * FROM `glpi_plugin_fields_labeltranslations` WHERE `plugin_fields_itemtype` = 'PluginFieldsContainer' AND `plugin_fields_items_id`='5' AND `language` = 'de_DE' | 0.000 |  
58 | SELECT * FROM `glpi_plugin_fields_labeltranslations` WHERE `plugin_fields_itemtype` = 'PluginFieldsField' AND `plugin_fields_items_id`='7' AND `language` = 'de_DE' | 0.000 |  
59 | SELECT * FROM `glpi_plugin_fields_labeltranslations` WHERE `plugin_fields_itemtype` = 'PluginFieldsContainer' AND `plugin_fields_items_id`='5' AND `language` = 'de_DE' | 0.000 |  
60 | SELECT * FROM `glpi_plugin_fields_labeltranslations` WHERE `plugin_fields_itemtype` = 'PluginFieldsField' AND `plugin_fields_items_id`='8' AND `language` = 'de_DE' | 0.000 |  
61 | SELECT * FROM `glpi_displaypreferences` WHERE `itemtype` = 'AllAssets' AND (`users_id` = '9626' OR `users_id` = '0') ORDER BY `users_id`, `rank` | 0.000 |  
62 | SET SESSION group_concat_max_len = 16384; | 0.000 |  
63 | SELECT 'a10409' AS currentuser, `glpi_computers`.`name` AS `ITEM_0`, `glpi_computers`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_computers`.`serial` AS `ITEM_2`, `glpi_computers`.`date_mod` AS `ITEM_3`, `glpi_computers`.`comment` AS `ITEM_4`, `glpi_computers`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_computers`.`contact` AS `ITEM_8`, `glpi_computers`.`id` AS id , 'Computer' AS TYPE FROM `glpi_computers`LEFT JOIN `glpi_entities` ON (`glpi_computers`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_computers`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_computers`.`id` IS NOT NULL AND `glpi_computers`.`is_deleted` = '0' AND `glpi_computers`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_monitors`.`name` AS `ITEM_0`, `glpi_monitors`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_monitors`.`serial` AS `ITEM_2`, `glpi_monitors`.`date_mod` AS `ITEM_3`, `glpi_monitors`.`comment` AS `ITEM_4`, `glpi_monitors`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_monitors`.`contact` AS `ITEM_8`, `glpi_monitors`.`id` AS id , 'Monitor' AS TYPE FROM `glpi_monitors`LEFT JOIN `glpi_entities` ON (`glpi_monitors`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_monitors`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_monitors`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_monitors`.`id` IS NOT NULL AND `glpi_monitors`.`is_deleted` = '0' AND `glpi_monitors`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_networkequipments`.`name` AS `ITEM_0`, `glpi_networkequipments`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_networkequipments`.`serial` AS `ITEM_2`, `glpi_networkequipments`.`date_mod` AS `ITEM_3`, `glpi_networkequipments`.`comment` AS `ITEM_4`, `glpi_networkequipments`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_networkequipments`.`contact` AS `ITEM_8`, `glpi_networkequipments`.`id` AS id , 'NetworkEquipment' AS TYPE FROM `glpi_networkequipments`LEFT JOIN `glpi_entities` ON (`glpi_networkequipments`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_networkequipments`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_networkequipments`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_networkequipments`.`id` IS NOT NULL AND `glpi_networkequipments`.`is_deleted` = '0' AND `glpi_networkequipments`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_peripherals`.`name` AS `ITEM_0`, `glpi_peripherals`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_peripherals`.`serial` AS `ITEM_2`, `glpi_peripherals`.`date_mod` AS `ITEM_3`, `glpi_peripherals`.`comment` AS `ITEM_4`, `glpi_peripherals`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_peripherals`.`contact` AS `ITEM_8`, `glpi_peripherals`.`id` AS id , 'Peripheral' AS TYPE FROM `glpi_peripherals`LEFT JOIN `glpi_entities` ON (`glpi_peripherals`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_peripherals`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_peripherals`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_peripherals`.`id` IS NOT NULL AND `glpi_peripherals`.`is_deleted` = '0' AND `glpi_peripherals`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_phones`.`name` AS `ITEM_0`, `glpi_phones`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_phones`.`serial` AS `ITEM_2`, `glpi_phones`.`date_mod` AS `ITEM_3`, `glpi_phones`.`comment` AS `ITEM_4`, `glpi_phones`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_phones`.`contact` AS `ITEM_8`, `glpi_phones`.`id` AS id , 'Phone' AS TYPE FROM `glpi_phones`LEFT JOIN `glpi_entities` ON (`glpi_phones`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_phones`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_phones`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_phones`.`id` IS NOT NULL AND `glpi_phones`.`is_deleted` = '0' AND `glpi_phones`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_printers`.`name` AS `ITEM_0`, `glpi_printers`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_printers`.`serial` AS `ITEM_2`, `glpi_printers`.`date_mod` AS `ITEM_3`, `glpi_printers`.`comment` AS `ITEM_4`, `glpi_printers`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_printers`.`contact` AS `ITEM_8`, `glpi_printers`.`id` AS id , 'Printer' AS TYPE FROM `glpi_printers`LEFT JOIN `glpi_entities` ON (`glpi_printers`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_printers`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_printers`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_printers`.`id` IS NOT NULL AND `glpi_printers`.`is_deleted` = '0' AND `glpi_printers`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_softwarelicenses`.`name` AS `ITEM_0`, `glpi_softwarelicenses`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_softwarelicenses`.`serial` AS `ITEM_2`, `glpi_softwarelicenses`.`date_mod` AS `ITEM_3`, `glpi_softwarelicenses`.`comment` AS `ITEM_4`, `glpi_softwarelicenses`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_softwarelicenses`.`contact` AS `ITEM_8`, `glpi_softwarelicenses`.`id` AS id , 'SoftwareLicense' AS TYPE FROM `glpi_softwarelicenses`LEFT JOIN `glpi_entities` ON (`glpi_softwarelicenses`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_softwarelicenses`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_softwarelicenses`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_softwarelicenses`.`id` IS NOT NULL AND `glpi_softwarelicenses`.`is_deleted` = '0' AND `glpi_softwarelicenses`.`is_template` = '0' UNIONSELECT 'a10409' AS currentuser, `glpi_certificates`.`name` AS `ITEM_0`, `glpi_certificates`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_certificates`.`serial` AS `ITEM_2`, `glpi_certificates`.`date_mod` AS `ITEM_3`, `glpi_certificates`.`comment` AS `ITEM_4`, `glpi_certificates`.`id` AS `ITEM_5`, `glpi_locations`.`completename` AS `ITEM_6`, `glpi_states`.`completename` AS `ITEM_7`, `glpi_certificates`.`contact` AS `ITEM_8`, `glpi_certificates`.`id` AS id , 'Certificate' AS TYPE FROM `glpi_certificates`LEFT JOIN `glpi_entities` ON (`glpi_certificates`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_certificates`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_states` ON (`glpi_certificates`.`states_id` = `glpi_states`.`id` ) WHERE ( 1 ) AND `glpi_certificates`.`id` IS NOT NULL AND `glpi_certificates`.`is_deleted` = '0' AND `glpi_certificates`.`is_template` = '0' ORDER BY ITEM_0 ASC LIMIT 0, 15 | 0.016 | Unknown column 'glpi_certificates.contact' in 'field list'
64 | SHOW WARNINGS | 0.000 |  

`

**Comment by trasher** [comment]
Dos the issue happens only in global view; or on the certificates lists as well?

**Comment by purdy87** [comment]
Only in Global View. But we don´t use it.

![2017-09-29 14_24_10-glpi - global](https://user-images.githubusercontent.com/11552524/31015777-20758e58-a522-11e7-94d0-145770ad2ede.jpg)

**Comment by trasher** [comment]
OK; thanks for the details.

**Comment by trasher** [comment]
I cannot reproduce... I guess I'm missing some data; but I do not know what exactly.

**Comment by purdy87** [comment]
Hmm.

I added column "contact" into table glpi_certificates. It´s working now.
