### ISSUE TITLE
[9.2] Wrong user on attachments gathered from mail collector

### ISSUE THREAD

**Issue by kelior** [glpi-project/glpi#2875]
When a ticket is created from a mail collector and an attachment is present (document, img, etc)
A document is added in the history tab with a completely random ? user.
![image](https://user-images.githubusercontent.com/19959600/31016057-757ce9b8-a523-11e7-811c-fd52e846c28a.png)

**Comment by trasher** [comment]
Should be fixed in https://github.com/glpi-project/glpi/pull/3109
