### ISSUE TITLE
[9.2] No attachment files

### ISSUE THREAD

**Issue by EugeneSE79** [glpi-project/glpi#2883]
Dear GLPI user.

After updating from 9.1.6 to 9.2, all attachment files are deleted when mail is received.
When opening a new ticket or when replying to a ticket through the mail, the attached documents are not loaded.

files are not added to the ticket and are not added to the Documents.
The problem occurred after the update.
While I had to roll back to version 9.1.6

**Comment by j-burt** [comment]
Had the same issue on my instance from 9.1.4 to 9.2...have reverted back for now.

**Comment by EugeneSE79** [comment]
dear colleagues
i found mistake in code
it was file mailcollector.class.php -> function getRecursiveAttached()
line "$this->getRecursiveAttached($mid, $path, $maxsize, $sub_structure,"
in code wasn't chaned variable @param $mid
in new code must be $uid:
"$this->getRecursiveAttached($uid, $path, $maxsize, $sub_structure,"

If new problems are found, need to check and merge the old code and new code.

**Comment by trasher** [comment]
see https://github.com/glpi-project/glpi/issues/2841
