### ISSUE TITLE
problem with notifications of mreporting plugin

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2887]
good morning, somebody tries mreporting plugin? i'm trying to send via email notification reports of MREPORTING and the crontask fail. Anybody can help me?

my glpi version is 9.2 and mreporting 1.4.0

thank you.

**Comment by trasher** [comment]
Does core notifications works? It may be specific to this plugin (and the bug should be reported on its bugtracker).

**Comment by trasher** [comment]
Ping?

**Comment by sferia82** [comment]
with new version not present error. but not arrive mails of mreporting.

**Comment by trasher** [comment]
Please report plugins issues on plugins bugtracker.
