### ISSUE TITLE
ticket history format plain text instead of html in version 9.2

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2889]
good morning.
since update 9.2 the format in history of ticket doesn't appear as html. Is in plain text. there is any way to show the history in html format?

thank you.

**Comment by trasher** [comment]
What does mean "history of ticket"? Are you talking about the timeline? Please also précise if rich text is enabled or not in your configuration.

**Comment by trasher** [comment]
Ping?

**Comment by sferia82** [comment]
it works with your las version of project.
thanks.
