### ISSUE TITLE
[9.2] Planning : Drag & drop

### ISSUE THREAD

**Issue by jgobet** [glpi-project/glpi#2890]
Hello,

It's always possible to drag and drop ticket tasks from the planning even if:
- We don't have the right to modify the tasks of others but we have read access to their plannings
- Tickets are closed

Can you watch please?

**Comment by jgobet** [comment]
Hello,

Did you reproduce the bug?

**Comment by pVesian** [comment]
Hi, @jgobet, here's what I have on 9.2.3 with a ticket with a task at 18:00:

- Normal drag & drop on the planning works fine
- If I close the ticket but don't reload the planning tab I can still drag & drop tasks
- If I close the ticket but reload the planning tab the task has disappeared from the planning
- If another user in Read-Only profile tries to drag & drop the task it doesn't work
