### ISSUE TITLE
9.1.4 charset problem

### ISSUE THREAD

**Issue by lexcorp** [glpi-project/glpi#2892]
Hello, the answers from the web service plugin shows me some incorrect characters, accents and tildes:

![webserviceerror](https://user-images.githubusercontent.com/5751288/31129002-fd4d4c0a-a818-11e7-8b0e-c5f469872f20.png)

![charset](https://user-images.githubusercontent.com/5751288/31129023-09150604-a819-11e7-8907-71d465afdb1a.JPG)

My apache server is configured with UTF-8 encoding: AddDefaultCharset UTF-8

My php.ini it's ok: default_charset = "UTF-8"

Characters instead of: á, é, í, ó, ú, ñ, ejecución, dañado, depuración.

**Comment by remicollet** [comment]
This bug tracker is for GLPI, not for the plugins.
(already reported on the forum, should be enough)
