### ISSUE TITLE
[9.2] Accented characters in AJAX entities search

### ISSUE THREAD

**Issue by jgobet** [glpi-project/glpi#2893]
Hello,

In AJAX entities search, not consider accented characters.
For example, if I search e show entities where e, é, è, ... in their name.
And if I search é show entities where é and e in their name.

The solution was found in GLPI 0.90 : http://glpi.userecho.com/topics/80-accented-characters-in-entities-search/
Can you apply this solution in this new version?

Thanks.

**Comment by trasher** [comment]
Hello,

The solution you are talking about is only a proposal on a suggestion... Nothing has never been confirmed nor implemented.

Since the suggestion already exists; a ticket is not needed. Thank you.
