### ISSUE TITLE
Syncronization on Active Directory failed 

### ISSUE THREAD

**Issue by isawebs** [glpi-project/glpi#2895]
Hi, ´ve upgrade to 9.2 and cant make syncronization makes effect. Any idea?

**Comment by trasher** [comment]
Please provide aditional details on your setup; check your logs (glpi and system), and so on.

**Comment by trasher** [comment]
Ping?

**Comment by isawebs** [comment]
Wait and ill share the logs

**Comment by isawebs** [comment]
Hil, listen here is the log:
[Log](https://drive.google.com/file/d/0B-WFXROgGzs8U0J1cFBPNm1LSm8/view?usp=sharing)

**Comment by isawebs** [comment]
\notification.php:44                          Search::show()
2017-10-09 15:15:47 [@SERVER]
  *** PHP Warning(2): ldap_search(): Search: Operations error
  Backtrace :
  :                                                  
  inc\authldap.class.php:2789                        ldap_search()
  inc\auth.class.php:633                             AuthLDAP::searchUserDn()
  front\login.php:79                                 Auth->Login()
2017-10-09 15:15:57 [@SERVER]
  *** PHP Warning(2): ldap_search(): Search: Operations error
  Backtrace :
  :                                                  
  inc\authldap.class.php:2789                        ldap_search()
  inc\auth.class.php:633                             AuthLDAP::searchUserDn()
  front\login.php:79                                 Auth->Login()
---------------
I dont know what would be wrong with that

**Comment by tlombardini** [comment]
HI, I have the same problem :(  Any ideas?

**Comment by AnaelMobilia** [comment]
Hello,

Could you, please, provide more details (GLPI setup) => you can find it in Setup > General menu, System tab ?
Does the LDAP connexion test work ?
Have you tried on the 9.3 version ?

Regards,
Anael

**Comment by rmundel** [comment]
Hi, I have the same problem.


Instruções de instalação e configuração
--
[code]   GLPI 9.3.1 ( => /var/www/html/suporte.mazzutti.inet/public_html) Installation mode: TARBALL

Operating system: Linux suporte 4.15.18-4-pve #1 SMP PVE 4.15.18-23 (Thu, 30 Aug 2018 13:04:08 +0200) x86_64 PHP 7.2.10-0ubuntu0.18.04.1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, calendar, cgi-fcgi, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="300" memory_limit="512M" post_max_size="20M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: nginx/1.14.0 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0 Server Software: Ubuntu 18.04 	Server Version: 10.1.34-MariaDB-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (10.1.34) - Perfect! /var/www/html/suporte.mazzutti.inet/public_html/files/_log : OK /var/www/html/suporte.mazzutti.inet/public_html/config : OK /var/www/html/suporte.mazzutti.inet/public_html/files : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_dumps : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_sessions : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_cron : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_graphs : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_lock : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_plugins : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_tmp : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_cache : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_rss : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_uploads : OK /var/www/html/suporte.mazzutti.inet/public_html/files/_pictures : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/html/suporte.mazzutti.inet/public_html/lib/htmlawed) SimplePie version 1.5.2 in (/var/www/html/suporte.mazzutti.inet/public_html/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/var/www/html/suporte.mazzutti.inet/public_html/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/suporte.mazzutti.inet/public_html/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/suporte.mazzutti.inet/public_html/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/suporte.mazzutti.inet/public_html/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/suporte.mazzutti.inet/public_html/vendor/sabre/vobject/lib) phpCas version 1.3.3 in (/usr/share/php)

Server: '192.168.3.10', Port: '389', BaseDN: 'DC=mazzutti,DC=inet', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=administrator,CN=Users,DC=mazzutti,DC=inet', Use TLS: none

Not active

Way of sending emails: PHP

 
My LDAP config:
![image](https://user-images.githubusercontent.com/13142574/46236644-caf8c800-c34d-11e8-8488-14bfd541241d.png)

GLPI logs:
![image](https://user-images.githubusercontent.com/13142574/46236665-e663d300-c34d-11e8-8f89-d37b71b150a7.png)

**Comment by rmundel** [comment]
Yeah. Just found out what it is. It was my samba enforcing strong auth. Thanks

**Comment by pivaldi** [comment]
So, only for GLPI, must we downgrade LDAP authentication  ?

**Comment by rmundel** [comment]
For everything using samba unsecurely.

**Comment by rmundel** [comment]
Add "ldap server require strong auth = no" to your smb.conf.
