### ISSUE TITLE
[9.2] replace category ticket on delete category

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2897]
in version 9.2 when i delete a category of task and there are tickets associated with this category the system tell me if i want to replace to another category but it doesn't work.

thanks

**Comment by trasher** [comment]
I cannot reproduce; ticket tasks get the new seleccted category in my tests.

Please alos check your logs.

**Comment by trasher** [comment]
ping?

**Comment by sferia82** [comment]
it works perfectly. i put the last version with fixes.  thanks
