### ISSUE TITLE
[9.2] -- Not working Reset Ticket Filters

### ISSUE THREAD

**Issue by carlosbmc** [glpi-project/glpi#2898]
After migration from 9.1.1  to   9.2
when I click in Remove buton in Tickets Filter (     front/ticket.php?reset=reset   )
Not removes the filter.  I's working well in previous version 9.1.1

**Comment by trasher** [comment]
Reset filters now goes back to default parameted bookmark if any. Previously, it was reset to a hardcoded default.
So, question is; is the filters after reset the ones in your default saved search?

**Comment by carlosbmc** [comment]
Yes!
Great!!
Thank you this solves my question!

**Comment by trasher** [comment]
:)
