### ISSUE TITLE
[9.2] Link knowbase Item to ticket

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#2899]
From /glpi/front/knowbaseitem.form.php?id=X

When you link a ticket to the knowbase article, the ticket appears four times like this : 

![image](https://user-images.githubusercontent.com/13178158/31174052-599e6222-a90a-11e7-9818-d9363b8d06a3.png)

AND

The dates fields do not use Html::convDateTime

**Comment by trasher** [comment]
This seems to be related to the number of targets of the KB item
