### ISSUE TITLE
Create a multiple associated tickets on ticket creation at Business rules for tickets

### ISSUE THREAD

**Issue by man4red** [glpi-project/glpi#290]
Please advice

We are in need (and I hope we are not only) to create a business rules for tickets that will create associated (linked) tickets and will assign it to Entity/Group etc.

For example: Business rule "Create Workplace for a new Employee"
1. Ticket created "Create Workplace for User01" and selected category "New Workplace Creation"
2. Rule will create a linked ticket "Create User01" for System Administrators group
3. Rule will create a linked ticket "Setup Computer" for Support team
4. Rule will create a linked ticket "Setup Phone" for Telecommunication team
etc...

We are waiting for this feature for a long time :)
Didn't found how to make it thru existing functional

Thx

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
