### ISSUE TITLE
Calendar in item reservation is not translated

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2905]
http://forum.glpi-project.org/viewtopic.php?id=159148

**Comment by mrspam** [comment]
Hi !

Modification solve the calendar problem but in "Licences" and "Contracts" tab the field calendar not work (no logo) and when I put a date and save, I see no modification in the field.

You can see in the picture below, up it's for the Licences and down for the contract.

![sans titre](https://user-images.githubusercontent.com/26159277/32877217-d4e1d4de-cab9-11e7-9d5d-c1c71772a535.jpg)
