### ISSUE TITLE
[GLPI 9.1.6] Automatic reminders of SLT changes "Time to Own" to "Time to resolve"

### ISSUE THREAD

**Issue by OtherF** [glpi-project/glpi#2908]
[GLPI 9.1.6]
I want to send email notification to Group if tickets assigned to Group but not assigned by Technician in 5 minute.

Please find my setup below:

**Notification**:
**Name**: Unassigned Tickets
**Active**: Yes
**Type**: Ticket
**Notification method**: Email
**Event**: Automatic reminders of SLAs
**Notification template**: Unassigned tickets template
**Recipients**: Group in charge of the ticket

**SLA**:
**Name**: SLA-Unassigned 5 min
**Calendar**: 24/7

**SLT**:
**Name**: SLT 5 minute
**SLA**: SLA-Unassigned 5 min
**Type**: Time to own
**Maximum time**: 5 Minutes

**Escalation level**:
**Name**: Send notification
**Execution**: Time to own (_this changes to "Time to resolve"_)
**Criterion**: Technician | does not exist | Yes
**Action**: Automatic reminders of SLT | Send | Yes

**Automatic action - slaticket **
**Name**: slaticket
**Run frequency**: 5 minutes
**Status**: Scheduled
**Run mode**: CLI
**Run period**: 0 -> 24
**Number of days this action logs stored**: 30

Then, I created a ticket, I assigned SLT to the ticket: SLT 5 minute and assigned it to a Group, and not assigned to any technician.
When I hover to the "i" icon I see popup:
**Next Escalation: [time to the next escalation.]
Escalation Level: Send notification**

According to slaticket logs, the action fired:
1 Action completed, fully processed.

But I don't receive any emails about escalation.

This could be bug on 9.1.6.: Execution of **time to own** changes to **time to resolve**.

**Comment by vaibhav12321** [comment]
Did you get any solution? I am having same issue.

**Comment by Armin83** [comment]
this function was buggy in 9.1.x pls check 9.2.x

**Comment by vaibhav12321** [comment]
Yes I am using 9.3 still not getting email.

**Comment by Armin83** [comment]
It is not easy to use.
Please check this 

https://forum.glpi-project.org/viewtopic.php?id=164062
https://forum.glpi-project.org/viewtopic.php?id=164290
https://forum.glpi-project.org/viewtopic.php?id=164684

Regards kkadmin

**Comment by trasher** [comment]
Coud you please try with https://github.com/glpi-project/glpi/commit/836350d500800c565d8e9282c4138af4b63e157c and give feedback? Thank you.

**Comment by trasher** [comment]
No feedback from a while, closing.
