### ISSUE TITLE
[9.2] Impossible to associate element to a ticket

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2912]
When I try to associate an element to a ticket and save it, I have this strange behaviour : 

![image](https://user-images.githubusercontent.com/12936546/31226488-8f4e96f4-a9d6-11e7-85cf-82317e330535.png)

I do this with a user with full access on Parc.

Any idea ?

Thanks for your help

**Comment by ciadch** [comment]
If I do it form "Items" link, it works perfectly

**Comment by ciadch** [comment]
I continued my investigations. 

I create a fresh new user with super-admin rights. I create a new element. 

Then I add it to my ticket and save it : 

![image](https://user-images.githubusercontent.com/12936546/31266659-1543ec66-aa75-11e7-9f4e-a77a8aeffc70.png)

![image](https://user-images.githubusercontent.com/12936546/31266672-235c0ab8-aa75-11e7-94db-90463afbd344.png)

In this case, it works. Then I remove it and save my ticket. I try to add it again :
 
![image](https://user-images.githubusercontent.com/12936546/31266689-4302a4f8-aa75-11e7-9768-18da1fe84e1b.png)

When I save my ticket. My element is not associated 

![image](https://user-images.githubusercontent.com/12936546/31266703-5425aa46-aa75-11e7-8a90-dd76f704838c.png)

And I saw that in the log : 
![image](https://user-images.githubusercontent.com/12936546/31266712-5f083942-aa75-11e7-9a09-1295b02f73db.png)

So it seems that it works for the first time the equipment is associated but not after.

Thanks

**Comment by ciadch** [comment]
Same behaviour with a fresh install, with GLPI account

**Comment by trasher** [comment]
This "feature" is a pain... This do the same as the dedicated form; but with other code, causing specific issues... And this is also hard to maintain.

We'll fix for now; but we'll probably remove that part in a future release.

**Comment by ciadch** [comment]
Thanks for your return. I undestand it could be hard to maintain. But this feature is really really userfull and it's a grate feature ! 

Let's see in future :-)

**Comment by trasher** [comment]
What's the problem with the dedicated tab?

**Comment by ciadch** [comment]
Nothing but maybe a bit longer :-) ! But we have to change our habit :-)

**Comment by trasher** [comment]
OK :D

**Comment by ciadch** [comment]
Great ! 

What it could be really userfull is the possibility to add multiple elements in one shot (multiple select form).

**Comment by trasher** [comment]
I guess this would be a more global change; better to open a proposal on suggestions website (http://glpi.userecho.com/) for that point

**Comment by ciadch** [comment]
Ok great ! I will do that

Thanks

**Comment by yllen** [comment]
Bug is still present in 9.2-bugfixes of today
Step to reproduce:
- from ticket form, associate an item
- save ticket
- delete associated item
- save ticket
- associate the same or another item
- save ticket => item is not associated.

Issue is only on ticket tab not on associated items tab.
(http://forum.glpi-project.org/viewtopic.php?id=159133)

**Comment by trasher** [comment]
@yllen: proposed PR is still waiting for a review

**Comment by yllen** [comment]
@trasher: review done
