### ISSUE TITLE
Knowledge base articles (9.2)

### ISSUE THREAD

**Issue by grvy** [glpi-project/glpi#2916]
When deleting a KB article we get this error:

Fatal error: Call to undefined method KnowbaseItem_Revision::cleanDBonItemDelete() in /var/www/html/glpi/inc/knowbaseitem.class.php on line 343

**Comment by Xiral** [comment]
To resolve this problem you need to modify in glpi/inc/knowbaseitem_revision.class.php at line 43

`class KnowbaseItem_Revision extends CommonDBTM`

to match with it 

`class KnowbaseItem_Revision extends CommonDBRelation`

Best Regards,
Xiral

**Comment by trasher** [comment]
Hi, 

Thanks for the solution @Xiral ; it will not fix @grvy issue since his problem is on Knowbaseitem_Comment; but fix will  probably be similar :)

**Comment by trasher** [comment]
Nevermind... Currently, Comments are not deleted along with KB entry... I've added that on my side and get the same issue (that's why I was confused).

Will fix soon

**Comment by Xiral** [comment]
KB revision block deleting an item on KB so I find this for resolving that. 

Regards, Xiral
