### ISSUE TITLE
[0.90.1] split view bug :  both columns are right truncated

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#292]
http://forum.glpi-project.org/viewtopic.php?id=138612
![glpi0 90 1](https://cloud.githubusercontent.com/assets/13557254/11458694/71ab6bd4-96c5-11e5-8726-ae2c6ca7344a.png)

in split view, both columns are right truncated ( without horizontal scroll bar).
this did not happen with 0.90.
browser mozilla ff 42.0 (wide screen)

**Comment by orthagh** [comment]
This issue is still complicated (sorry for delay)
majority on input fields are still in row width (erk)

I'll check this week, if i can remove all this fixed with to permits a more flexible layout.

**Comment by orthagh** [comment]
I probably do it for 0.91 anyway.

**Comment by orthagh** [comment]
Finally, i succeed to do some better flexible layout.
So, i targeted 0.90.2
