### ISSUE TITLE
Drop adding elements from ticket update main form

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2920]
It is possible to link items to a ticket:
- using the dedicated tab
- using ticket main form.

Both does the same; but the one in the main form is a kind of hack... Therefore, this causes specific bugs, and this requires not needed and hard to maintain specific code.

Proposal is to entirely drop the "Associated elements" form part on ticket update.

Thoughts?

**Comment by orthagh** [comment]
strongly agree on this
