### ISSUE TITLE
[9.2] Bad russian translations in Suppliers

### ISSUE THREAD

**Issue by DanielSanIT** [glpi-project/glpi#2924]
Bad Russian translations in Supplier menu.
Home - Management - Suppliers - Supplier.

"Contacts" = "Контакты"
"Contracts" = "Договоры"
"Items" = "Объекты"
"Documents" = "Документы"
"Tickets" = "Заявкаи"
"Changes" = "Изменения"
![default](https://user-images.githubusercontent.com/20223013/31279171-bb7a8ed8-aab0-11e7-8b65-8b897bb18f7c.png)

**Comment by trasher** [comment]
Please use transifex for translations: https://www.transifex.com/glpi/GLPI/dashboard/
