### ISSUE TITLE
Datacenter mode

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#2926]
Integration of racks plugins

**Comment by magaiverpr** [comment]
It will be cool if the can add a way to control patch panels too.

**Comment by eduardospinola** [comment]
And enclosures for Blade server ( or other hardwares ) too

**Comment by trasher** [comment]
Current specs are available here: https://github.com/glpi-project/spec/wiki/GLPI-Datacenters-management

Please comment on https://github.com/glpi-project/spec/issues/1

**Comment by orthagh** [comment]
@fcrispim77 the job is done and will be released in the next version of glpi.
Beta version will be announced soon.
