### ISSUE TITLE
[Suggestion?] Ticket view (main form)

### ISSUE THREAD

**Issue by grvy** [glpi-project/glpi#2927]
Hello, 

I saw an issue here a while ago where you guys were reconsidering the main ticket form becuz its getting too bloated. As I too agree with this, I wanted to give in my suggestion for a improvement UI side.. 

I dont know if I should post it here, but i wanted to give my suggestion anyways. You dont need to do it like this, its just what I think could work. 

I used paint and snipping tool, as I dont have acces to Photoshop atm, but I hope my vision is clear enough regardless of how hacky it looks.

![ticket_1](https://user-images.githubusercontent.com/5603820/31289634-ad35e796-aac9-11e7-87ac-c5d25e430861.PNG)

The yellow markings mean remove. You could transfer the enite Time to own/Time to resolve etc to a "Time/SLA tab" there's no need to always have that in view as only the date at which the ticket should be sorted should always be seen. The others are just for information or to calculate SLA. 

Also; combine the dropdown for a user to also include groups. That would remove atleast 1 extra dropdown. You can filter/search already so there's no need to seprate them. Maybe include a filtering in the search box? 

Remove e-mail followup or make it a checkmark next to the user field (next to the + maybe?) 

Remove associated elements (this was already discussed in a previous ticket). 

In the end if you do this you would get something that looks something like this:

![hacked_ticket](https://user-images.githubusercontent.com/5603820/31289734-1ffc1cbe-aaca-11e7-8ee6-61866a9b0680.png)

Except for the fact it would look less hacky.. but again I just have paint here. 

I hope my suggestion is clear, and I hope it helps you out to figure out what to do with the at the moment very bloated main ticket form.

Thanks and regards,
Grvy

**Comment by ladenree76000** [comment]
"The yellow markings mean remove." => you can use ticket template to hide this fields.

I use requester groups, observer groups and assigned group  : please don't remove (i dont use assign to supplier so i keep it hidden)

**Comment by grvy** [comment]
@ladenree76000 I know this. And no I dont want them to remove the functionality of groups, what I meant and what I said in the original post is that you can 'combine' them to make it better/less different dropdowns etc.
