### ISSUE TITLE
Translation - issue translating units for volume size

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#2929]
## English (US)

![image](https://user-images.githubusercontent.com/14139801/31315543-20b747ee-ac1b-11e7-9de9-0fbfeab79cfd.png)

As far as I see in the sources, unit should be MiB instead of MB

## English (UK)

![image](https://user-images.githubusercontent.com/14139801/31315549-2b439302-ac1b-11e7-9b2b-1f8341713127.png)

Translations of the unit is not for english

## French 
![image](https://user-images.githubusercontent.com/14139801/31315557-43fba13c-ac1b-11e7-87c9-5763214f68bd.png)

This one is OK

**Comment by trasher** [comment]
As far as I understand, the only problem is the US translation (GLPI default is en_GB); so this should be reported on transifex.
