### ISSUE TITLE
Search engine for licenses

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#293]
See suggestion here : http://glpi.userecho.com/topic/882720-search-engine-for-license/ 

Add a new search engine page for licenses. Also add the ability to create a license without going to a software form.

**Comment by Henry78** [comment]
It should also be possible to link licences to network devices.

**Comment by orthagh** [comment]
see #459 & #466 for completion of this task

**Comment by wawax** [comment]
@Henry78 please open a feature request for the link to network device license link on suggest.glpi-project.org.

Thank you.
