### ISSUE TITLE
[9.2] Followup and images

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#2936]
Hello,

I'm sure it's related to the case #2869 , it's why I'm opening a new issue here.

It seems there is a little bug with image insertion in followup. Sometimes not all the images are displayed into the followup and the size of the image grows each time I paste it.

![image](https://user-images.githubusercontent.com/12936546/31374039-a092616a-ad9c-11e7-921b-ef2ab18364b2.png)

And when it is saved : 

![image](https://user-images.githubusercontent.com/12936546/31374072-c5129fd2-ad9c-11e7-87bf-a465f632d615.png)

Nothing in php-errors.log

Thanks for your help

**Comment by trasher** [comment]
Several issues has been fixed regarding to images in 9.2/bugfixes branch (chrome issue, link issue, system cron issues, etc)

**Comment by ciadch** [comment]
Yes thanks @trasher
