### ISSUE TITLE
[9.2] PHP error with is_template

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#2937]
GLPI : 9.2

When the 'Ticket' tab is used in a plugin that doesn't have the templates: 

![is_template](https://user-images.githubusercontent.com/15138371/31375470-f8614136-ada1-11e7-9690-7e7d56150374.png)

`2017-10-10 09:37:09 [2@M379]
  *** PHP Notice(8): Undefined index: is_template
  Backtrace :
  inc\ticket.class.php:6035                          
  inc\ticket.class.php:882                           Ticket::showListForItem()
  inc\commonglpi.class.php:482                       Ticket::displayTabContentForItem()
  ajax\common.tabs.php:96                            CommonGLPI::displayStandardTab()`

**Comment by yllen** [comment]
Corrected with with PR https://github.com/glpi-project/glpi/pull/2935
