### ISSUE TITLE
Bug mass modification de catégorie dans logiciels - GLPI 0.90

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#294]
Bonjour,

Lorsque je veux modifier en masse la catégorie d'appartenance de plusieurs logiciels, quand je clique sur modifier puis Catégorie, j'ai le message suivant qui apparaît 
Screenshot : http://www.cjoint.com/c/ELbiV6UwSbk

Pour info j'avais sélectionné 698 logiciels (toutes les mises à jour windows (les KB, correctifs et autres).

La modification a fonctionné, c'est juste pour vous informer du message

**Comment by pocketpit** [comment]
Bonjour,

As-tu pris la peine de comprendre le message retourné ? A priori non.
Tu fais une sélection multiple. On t''informe que tu sélectionne un nombre trop important de lignes. On te donne le nom du fichier et le nom de la variable concerné.

Tu ouvres ton fichier php.ini, tu cherche la valeur de cette variable.
La ligne chez moi était précédé par un ;.
Donc tu enlèves le " ; " en début de ligne, tu restart ton php, et tu ne devrais plus avoir de message lorsque tu fais une sélection de plusieurs lignes.

C'est pas une erreur, juste un peu de fainéantise dans l'auto-apprentissage.

**Comment by nbriche** [comment]
Non, c'est bien un bug d'affichage: un warning PHP qui n'a clairement pas sa place dans le frontend...

**Comment by sebfun** [comment]
alors pour répondre à Pockepit. 

S'il y en a bien qui n'est pas fainéant c'est bien moi.
Primo : avant de sortir ce genre de débilité de réponse, si tu avais lu correctement le message ainsi que la PJ tu aurais vu que j'ai fait une sélection de 698 éléments et que le Notice indique un dépassement de 1000 d'où le message de bug...
Deuxio : Tout le monde n'est pas anglophone même si j'avais compris le "Notice".
J'espère que la prochaine fois tu réfléchiras à 2x avant de poster ce genre de message.
Et en plus j'indique bien "c'est juste pour vous informer du message", preuve que tu n'as pas lu jusqu'au bout.
A bon entendeur

nbriche : merci pour ta réponse

**Comment by wawax** [comment]
Bonjour à tous,

Merci de répondre de manière courtoise. Il n'y a pas de place ici pour des messages déplacés sur ce bugtracker.

Cordialement,

**Comment by orthagh** [comment]
la capture originale a été perdue depuis.
Si vous le souhaitez, vous pouvez ré-ouvrir cette issue
