### ISSUE TITLE
double duration displayed in ticket task

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#2945]
- one in direct form
- one in planification

![image](https://user-images.githubusercontent.com/418844/31427648-43d0051e-ae68-11e7-9e82-7ddb5f6fa6c4.png)

We should remove planification one

**Comment by trasher** [comment]
As far as I can see; this it not only used for tickets. Before changing that, we have to identify other UI parts that calls this form and ensure this will not breaks.

**Comment by orthagh** [comment]
Yes, i conclude the same things.
Not really urgent imo, this issue could be postponed

**Comment by trasher** [comment]
I have checked; this is used from reminders; and we do not have any other duration in this one. Postponed for now.
