### ISSUE TITLE
Slugify cyrillic characters fails

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#2946]
On some languages; slugify fails and can result in an empty string... 

For exemple:
```php
Toolbox::slugify('Έρευνα ικανοποίησης - Αιτήματα'); //==> ""
```

A solution would be to use:
```php
transliterator_transliterate("Any-Latin; NFD; [:Nonspacing Mark:] Remove; NFC; [:Punctuation:] Remove; Lower();", 'Έρευνα ικανοποίησης - Αιτήματα'); //==> "ereuna ikanopoieses  aitemata"
```

That sound better; but this requires additional php-intl extension.

I also see an existing library - https://github.com/cocur/slugify - but I'm affraid they support less languages than GLPI.

Slugs are used to make anchors on KB contents, and in charts (so charts are currently failing in some languages).

**Comment by tincturaginseng** [comment]
If slugs is empty, this patch replace it to random string. But in **inc/stat.class.php** in **public function displayPieGraph** slug not empty (used title AND number of tickets). In English all OK - $slug=opened_tickets_534 (for example), but for non-English $slug=534 and it's error and pie graph not draw.
I add prefix for $slug
`
$slug = 'slug_' . str_replace('-', '_', Toolbox::slugify($title));
`
and pie chart is OK.
[https://pastebin.com/hefL5g7t](https://pastebin.com/hefL5g7t)

**Comment by trasher** [comment]
`id` attribute in html must begin with a letter; that would explain why charts are failing. The fix you propose is OK, but for charts only. Slugs are also used to produce anchors on kwnoledge base items contents; problem would be the same other there.

I wonder if we should not add a prefix directly from the slug function when result does not begin with a letter.

**Comment by trasher** [comment]
I've opened a PR that targets 10.0.0; but this could be easily backported to previous releasses; just make sure `php-intl` extension is present.
