### ISSUE TITLE
How can I help with the portuguese translation

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#2952]
I would like to help with the Portuguese-Brazil translation to GLPI 9.2.
How could I help?
Is there a place for this kind of stuff? Or should I just submit a pt-BR.po for you to review?

**Comment by jpnr79** [comment]
You can inscribe at transifex plataform  and inscribe on glpi project.  If
you beed more information tell me. Im portuguese

Pedro Rocha
Faro
jpnr79@gmail.com
+351935478010
www.linkedin.com/in/pedro-rocha79

Em 11/10/2017 12:44, "arthurrschaefer" <notifications@github.com> escreveu:

**Comment by trasher** [comment]
Hello,

I was not fast enough :D

See on  transifex: https://www.transifex.com/glpi/GLPI/dashboard/
