### ISSUE TITLE
Upload document with IE 11

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2959]
http://forum.glpi-project.org/viewtopic.php?id=159279

I have no IE11 to test.

**Comment by trasher** [comment]
Neither do I... :)

**Comment by tomolimo** [comment]
Hello,
see this: https://github.com/glpi-project/glpi/issues/196
regards,
Tomolimo

**Comment by trasher** [comment]
Waiting for user feedback on forum.
