### ISSUE TITLE
N otification for new actor

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2963]
Define a notification for new technician
No notification for update ticket

Add a new technician => receive a notification for update ticket

**Comment by orthagh** [comment]
I don't replicate this issue (or i don't understant it well).

i setup my glpi like below:
- enabled mail notifications
- enabled existing "New user in assignees" (with assign_user event) notification
- added an existing template to this notification

In a new ticket, i add a tech actor and here is the mail in the queue:
![image](https://user-images.githubusercontent.com/418844/32553300-cbc0b27c-c496-11e7-8e4b-4d641c387ba8.png)

The title mention the good event and i don't find any issue.

Could you precise the issue ?

**Comment by Armin83** [comment]
I read this. I thought great i don't know that this is possible. I need this. bug I got also the "bug".

But in my case it is missing configuration. This piece of configuration i hate. the behaviour is bad for the great software glpi, THANKS for the software btw.

I can activiate a notification (i believe never used before) "New user in assignees". I see a template in templates so i think all is okay but it isn't.
If i click on it in the next screen (template id) i can see that there is no template assigned. Field "Notification template" is not filled.

Now it works :)
It would be nice if a user can't do a wrong configuration in this way. 

maybe it was this case ?
