### ISSUE TITLE
Global Search, look for Serial Number

### ISSUE THREAD

**Issue by gituncar** [glpi-project/glpi#297]
Hi, If possible review global seach, over device, because serial number dont show anything.
Global search with all serial numbers.
![image 1](https://cloud.githubusercontent.com/assets/7705197/11538332/8bb0a392-98ef-11e5-800e-a45386a7f6a6.png)
Version 0.90.1

**Comment by satyan01** [comment]
If you want to find serial number by global search, each of your default view must have serial number column selected

**Comment by gituncar** [comment]
It s working with load bookmark, and column serial number, thanks.
