### ISSUE TITLE
[Suggestion] Self service portal

### ISSUE THREAD

**Issue by grvy** [glpi-project/glpi#2971]
Hello. 

The plugin "FormCreator" has a great self service portal for GLPI. I think it would be wise to integrate that plugin into GLPI's core. Or atleast the Self Service Portal (the forms portion I can agree might be a bit too much if you wanna keep it slim) 

The current GLPI "user portal" is severly outdated in comparision to the new and upcoming ticket systems which are all based on having a self service portal.

I think the author of Formcreator could use some help with other GLPI Dev's in creating something awesome that can help the user portion of GLPI. 

Just my suggestion tho, if I could code I would help him out myself, sadly I cant do anything but give my opinion/suggestions and help translate. 

Example (from google)
![afbeelding](https://user-images.githubusercontent.com/5603820/31548145-30f3e5f0-b02a-11e7-88e5-c23cbf2beb35.png)

**Comment by trasher** [comment]
Please use [suggestions webstie](http://suggest.glpi-project.org)
