### ISSUE TITLE
Link after create a gabarit

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2972]
Notification name Alerte cartouches
I create a new gabarit and link display is not to the correct notification 
![capture-20](https://user-images.githubusercontent.com/12936722/31555156-4767739a-b040-11e7-9e72-cc721faa35d8.png)

**Comment by trasher** [comment]
This one should be fixed in e48a11bbdcd30ccb4dabc9a68e67ae6b1c04b306

**Comment by yllen** [comment]
Where are many problem. I explain my actions.
Setup > Notification > Notification
Add a new notification with + icon
Save the form
Click on Template tab
Add a template button
Add the template.
So i see my template with a link List. If i click on this link a have an error "The requested URL /git92/front/notification_notificationtemplate.php was not found on this server."

So i go to my notification with the link of its name
I open my notification, tab Template
If i click on delete definitively to delete this template of this notification it delete the notification template

Name of link seems to be correct now
