### ISSUE TITLE
Don't display GLPI version on login page

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#2976]
Hello,

On the login page, as I'm not logged, is displayed the GLPI version 
`GLPI 9.1.6 Copyright (C) 2015-2017 Teclib' and contributors - Copyright (C) 2003-2015 INDEPNET Development Team`

It appears not beeing a good idea as it allow to automated attack if a security issue is discovered on glpi...

Regards

**Comment by shoothub** [comment]
Version of GLPI can also be found in:

1. login page in suffix URL to CSS files ?v=9.2.2:
\<link rel="stylesheet" type="text/css" href="/css/palettes/auror.css?v=**9.2.2**" media="screen">
\

2. If you have enabled public FAQ, on footer and also in suffix URL to CSS, JS:
http://demo.glpi-project.org/front/helpdesk.faq.php

**Comment by AnaelMobilia** [comment]
@shoothub Thanks for the catch !
See PR #4091
