### ISSUE TITLE
Configuration Entity - Notification for certificat

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#2983]
In this part, green text in the value of inherit parent if selected.
In alarm part you have in green "inheritance of parent entity". You must have Yes or No.

In delay part you have "Send an alert after" but in code the time is calculate before this delay

**Comment by orthagh** [comment]
Translation issue, see:
https://github.com/glpi-project/glpi/blob/9f8dca9033aa8216e9e9f16ba672b29146617db2/locales/fr_FR.po#L10837

Fixed on transifex, next pull will solve this issue
