### ISSUE TITLE
glpi_ticketvalidations table empty

### ISSUE THREAD

**Issue by lexcorp** [glpi-project/glpi#2990]
GLPI Version 9.1.4

Steps to reproduce:
1.- A technician clicks the button to solve a ticket.
2.- Enter a description of the solution.
3.- Click the save button.

Expected result:
1.- The status of the ticket changes to Resolved
2.- In the table "glpi_ticketvalidations", a record with the data of the validation request for the applicant is stored.

Result:
1.- The table "glpi_ticketvalidations" is empty.

When you click the Save button, you should store a record in the table, but it does not. The table is empty.
![validation](https://user-images.githubusercontent.com/5751288/31637942-b625f54c-b296-11e7-8a8f-dedca44aa403.JPG)

**Comment by tomolimo** [comment]
Hello @lexcorp 

glpi_ticketvalidations and solutions are two different objects and they are not linked together.
Validation are used when you (as a ticket tech) asked for a validation of a user request (or incident that must be solved by for example buying something) this validation is aimed to some user's managers. You may ask for several validators to validate the request.

Solutions and approval of solutions are currently stored in the glpi_tickets table.

regards,
Tomolimo
