### ISSUE TITLE
Error while creating a new ticket and the requester has an e-mail address with a single quote in it

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#2993]
Hello,

I tried to create a ticket through the GLPI web interface for an user with single quote in his last name. The system rejected the request with the message that his e-mail address was not valid.

Name (like) : Jacques M'Boon
Address: Jacques.M'Boon@domain.com

In the e-mail field the address was cut like this: Jacques.M

If I put the e-mail address instead of the user name during ticket creation, everything is OK. So I think that the issue appears when the system retrieves the user e-mail address from the glpi user entry.

**Comment by trasher** [comment]
Truncated email address seems to appear as soon as the user is selected in the list.

**Comment by kabassanov** [comment]
Yes, I confirm it works.
Just a small detail: in 9.1.6 the second file is (still) called inc/notificationmail.class.php
