### ISSUE TITLE
glpi suddently don't list tickets [v9.2]

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#2994]
glpi suddently don't list tickets.
it remaining loading but don't list.
why?
i have 9.2 version.
thanks

**Comment by sferia82** [comment]
solved.

**Comment by tomolimo** [comment]
Hello, 
could you please explain more about this?
It will help the community 
Thank you 
Regards 
Tomolimo

**Comment by sferia82** [comment]
sometimes no finish list the tickets. keep loading page. 
i found that is one ticket and if i delete the ticket work perfect. but i don't know why.

thanks

**Comment by sferia82** [comment]
i reopen the issue. i dont solve the issue

**Comment by sferia82** [comment]
I know what the problem is but I do not know how to solve it. in case I do not list the glpi tickets if I disable the option "Use rich text for the help system" shows me up to the email that deleting it lists me all. is the case of an email that with the option is activated does not let me list the complete list of emails. could you send the mail in question so that you help me to know why it is and how to solve it?

Thank you.

**Comment by sferia82** [comment]
i think that there are something that it can't display on listed tickets. but i don't know. :(

**Comment by sferia82** [comment]
there is any way to list tickets without description? there is the reason that not list some tickets.

**Comment by trasher** [comment]
I'm sorry... But I do not understand what you say. Please try to do efforts on your messages.

You first talk about "missing tickets" which is probably due to a migration issue that has already been discussed in other threads.

And then you talk about rich text; emails... That does not makes sense.
