### ISSUE TITLE
Bug GLPI 9.1.4 to 9.2 - edit in the ticket header

### ISSUE THREAD

**Issue by mrcssilvasouza** [glpi-project/glpi#2998]
Dear,

GLPI 9.1.4 to 9.2 has a bug in the call header. An applicant with a ticket opening profile can not change the call header after being assigned to a technician. The ticket, even after it has been assigned, allows you to change the title, description, category, urgency and impact. It should not even show the save button. I expected them to resolve in version 9.2, but the error remains.

the first image is in version 9.1.4

![glpi1](https://user-images.githubusercontent.com/30185683/31750309-8fa02cec-b455-11e7-9efc-17c18fc6b5f8.png)

the second image is in version 9.2

![glpi2](https://user-images.githubusercontent.com/30185683/31750313-9470add2-b455-11e7-9ee0-c1393a88d7f8.png)

see how I left the profile to evidence the error in GLPI.

![glpi3](https://user-images.githubusercontent.com/30185683/31750314-9806268e-b455-11e7-9557-e2086f2048af.png)

**Comment by arthurrschaefer** [comment]
The same in here. https://github.com/glpi-project/glpi/issues/3187

**Comment by trasher** [comment]
Duplicates #2504
