### ISSUE TITLE
Some cliupdate arguments are ignored

### ISSUE THREAD

**Issue by Miminoux** [glpi-project/glpi#3002]
Hi all,
First of all : THANK YOU ! GLPI is a great tool for us.
I have a question on cliupdate.php (9.2), there is no more the optimize step in the end of the script, is it normal ?
From here, I'm guessing : maybe it's normal since DB schema changes in 9.2 then in the update process there is no needed optimize as the DB is optimized with "alter tables" and so on. If I'm right, then I'm not sure that removing the optimize option is a good thing because in some cases (like me haha) launching the optimize on the same schema helps when GLPI is getting slow. 
This is not an issue but a kind question.
Thx

**Comment by trasher** [comment]
Optimization from cliupdate is an option you can add n the command line (as it used to be as far as I can see).

**Comment by Miminoux** [comment]
You removed that part in commit f476327862ab893747ab748fec52b004e0f57439 as far as I can find.
And in the same commit I can't find it in the code but it's true that I didn't test it.

Also I can find DB:optimize_tables in a variable named "obsoletes" in tools/checkfunctions.php so I guess it does not exist anymore.

In the end, I aggree, I can specifi it in the command line but it seems not to be used to me even if I didn't try yet.

Bye bye

**Comment by trasher** [comment]
Problem is command line arguments are not sent to update class.
