### ISSUE TITLE
[9.2] bad display of predefined description in ticket opening

### ISSUE THREAD

**Issue by dmagniez** [glpi-project/glpi#3008]
Hello,

Since 9.2 update, the predefined area in ticket template, "description" in our case, are not displayed well when creating ticket in "easy" mode.

some bracket like `<p>` are added.

by the way, it's not possible to modify predefined area, we have to delete and recreate.

![image](https://user-images.githubusercontent.com/2813342/31770599-00f30530-b4d9-11e7-93f7-31682c28cd11.png)
![image](https://user-images.githubusercontent.com/2813342/31770614-0d6c1978-b4d9-11e7-9d28-b46e188d2f40.png)

**Comment by dmagniez** [comment]
I just modified the item in database, <p> tag appear in database like <lt>p<gt>, I tried to delete all stuff  and do proper carriage return, but <br> appear instead.

so input form re-encapsulate tag in another tags, and display page interpret all tag

**Comment by dmagniez** [comment]
same problem for notifications, <p> appear at each carriage return !

**Comment by abmj1979** [comment]
Hi,

same situation here. 

i already tried do use debug, but without sucess.

**Comment by trasher** [comment]
This has been fixed in 9.2.2
