### ISSUE TITLE
Less-than Sign in Ticket Description or Follow-up

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#3011]
Hi,

I remarked that when I create a ticket through the web interface with a sentence like this for exemple:
"Le prix devrait être <1000 EUR."

On ticket submission it becomes:
"Le prix devrait être "

Mail notifications copy the same.

On the other hand, if I put the same in a follow-up, it remains correct in GLPI, but the sentence is cut the same way in mail notifications...

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/140
