### ISSUE TITLE
Add the menu item "Ticket waiting for your approval" in ticket followup panel

### ISSUE THREAD

**Issue by Drimmwald** [glpi-project/glpi#3016]
Hello!
I made some changes. Maybe it will be interesting for you.
Tickets: add the menu item "Ticket waiting for your approval" in ticket followup panel.
I think it comfortably for users, the rapid passing to ticket waiting for users approval.

![232](https://user-images.githubusercontent.com/32536773/31813188-2b359d66-b58e-11e7-8c41-137f7fe300c7.png)

commit 4408b70a87ed42ce18bda2d6c67c7e86d5a1c97a

**Comment by trasher** [comment]
Added in master
