### ISSUE TITLE
API broken: Delete function in 9.2

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3022]
In 9.1 function ShowGraph exists in Stat.class
In 9.2 this function is deleted

This function must stay and indicated as deprecated since 9.2 (for use by plugins)

**Comment by trasher** [comment]
I do not know if this is possible since old and new libs are very different; this is too much work for 9.2.1 anyways.

**Comment by trasher** [comment]
It is unfortunately not possible to get something compatible with the old call.

To me, it is better in that specific case to get an error rather than trying to hack something that will never work as expected.
