### ISSUE TITLE
[glpi 9.2] file based_config.php missing

### ISSUE THREAD

**Issue by o71** [glpi-project/glpi#3023]
Hello,

After updating glpi 9.1.6 -> 9.2. I have only one file in the config directory (config_db.php).

In version 9.16 I had the files:
- based_config.php
- config_db.php
- config.php
- define.php

 I no longer have the file "based_config.php", without this file I have problems with some ocsinventoryng  plugin scripts.

I saw that a 'based_config.php' file exists in the config / inc directory of glpi 9.2 tar.gz.

Is it a manipulation/installation error or a bug? I have to copy the file from the tar.gz archive?

Thank you.

**Comment by trasher** [comment]
Hi,

File has been moved to inc directory since this is not a config file. Reports issues against the plugin to get that fixed.

**Comment by o71** [comment]
Thanks, It's right : https://github.com/pluginsGLPI/ocsinventoryng/issues/116
