### ISSUE TITLE
Missing SQL Escape string 

### ISSUE THREAD

**Issue by bloublou2014** [glpi-project/glpi#3031]
Hello,

After reviewing GLPI source code it appears commondbtm.class.php does not properly escape string and trust any values provided in update or add function.

'State of the art' workflow : 
- retrieve information on POST or GET
- sanitize data input
- business logic
- data access layer
 - escape string on SQL query with `DB->escape`
 - INSERT/UPDATE/SELECT

GLPI current implementation:
- retrieve information on POST or GET
- escaping data input with `DB->escape`
- sanitize data input
- business logic
- data access layer
 - INSERT/UPDATE/SELECT

In GLPI workflow 'string escape' is done on a "security" level, without any escaping in commun Data Access Layer. In practice front pages uses includes.php (including security level) and escape string on any POSTed data and does not do it on Data Access Layer. 

> Data Access Layer should not assume input data is escaped

As of today a security "issue" exists on `commondbtm.class.php` where no escape is done prior to execute any request : If a plugin executes an update on a field without escaping properly before requesting DAL, database is at risk. This situation could happen if a plugin or a script read from database and inject again same field values. Since no escape is done (and it should not), database will execute whatever field is provided. 

Plugin should trust data coming from Database and should be able to write on database without escaping data (could be a generated log for example).

```
function updateInDB 
...
$query .= " = '".$this->fields[$field]."'";
```

```
function addToDB
...
$query .= "'".$values[$i]."'";
```
### A Solution

Any data provided to common Data Access Layer should be escaped on DAL and not assuming some other piece of code has done it before. It's DAL's responsibility to sanitize data depending on his database.
In add/update use cases :
- Functions addToDB and updateInDB should escape string at their level
- Data provided to add/update function should not be escaped

```
$query .= " = '".$DB->escape($this->fields[$field])."'";
```

### Concrete example : 

Plugin "fields" includes a function "regenerate_files" :
```
function regenerateFiles() {
   $container = new PluginFieldsContainer;
   $found_container = $container->find();
   foreach ($found_container as $current_container) {
      $containers_id = $current_container['id'];
      $container->getFromDB($containers_id);
      $container->post_addItem();
   }
}
```

This function generate again all fields based on current database configuration, does not take any input from POST, and so no data is escaped.
Data comes from db itself, now if a container name is  "xxx', 'injected data " this data will be retrieved from database and injected again in an insecured way : 
```
$query .= "'".$values[$i]."'"; ==> $query .= "'xxx', 'injected data'" 
```

![image](https://user-images.githubusercontent.com/7194069/31857211-608b7b16-b68d-11e7-8b9a-53f6486c6eea.png)

Ending in a database error for this example where injected data is not properly escaped :

```
INTO `glpi_plugin_fields_labeltranslations` (`plugin_fields_itemtype`,`plugin_fields_items_id`,`language`,`label`) VALUES  

(\'PluginFieldsContainer\',\'5\',\'en_GB\',
\'xxx\', \'injected data\'  <== not properly escaped
)
  Error: Column count doesn't match value count at row 1
```

### Version :

[code]   GLPI 9.1.6 ( => D:\__DEV\glpi)
```
Operating system: Windows NT xxxx 10.0 build 15063 (Windows 10) i586 PHP 7.1.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date, 	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, 	pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="3000" memory_limit="2048M" post_max_size="800M" safe_mode="" session.save_handler="files" 	upload_max_filesize="1024M"  Software: Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1 (Apache/2.4.25 (Win32) OpenSSL/1.0.2j PHP/7.1.1 Server at glpi.local 	Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.1.21-MariaDB 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: localhost via TCP/IP
```

**Comment by trasher** [comment]
There is a big problem with automatic escaping we are aware of. We're thinking about changing that; his is a huge job.

We'll provide more information about all that, likely in a few weeks at least.

**Comment by bloublou2014** [comment]
If GLPI Team is aware of this problem and will work on it sooner or later, this ticket can be closed.
