### ISSUE TITLE
Possible migration issue with notifications

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#3037]
Some users try to update their database for tests; and then restore a backup on this database without cleaning anything. 
New created tables stay in place; and parts of migration relying on table presence will not be executed. This has been spotted in #2871 and on the forums/mailing list for the notification issue.

We can change the way we some conditions are done to get that type of migration working ; but since user has made previous tests; his database will remain kind of crap; there is no solution.

Previously, newly created tables was removed (so current problem was solved); but this cause data loss when update is played several times.

**Comment by tomolimo** [comment]
Hello,
Should we manage a status of migration, like: "migration started", "migration done".
Testing this status will inform migration procedure if it must alert for possible loss of data.
regards,
Tomolimo

**Comment by trasher** [comment]
In that case; that would not work. Both migration can be successfull; if you restore a previous backup, GLPI cannot define what has been done.

We've been talking about that already; and I've not been able to find a real solution for all that :(

**Comment by tomolimo** [comment]
And what about a glpi_configs_backup which will store the version of the backup table set?

**Comment by trasher** [comment]
When user will restore his backup; this table will be overidded too... This would work only the first time

**Comment by tomolimo** [comment]
If we have a way to store somewhere a kind of version for each table, will it be a solution?

**Comment by trasher** [comment]
No, this would not be enough since data may be impacted as well... tickets migration issue affects table structure; but notification is only on data in the  table.

**Comment by tomolimo** [comment]
The version can be either a schema evolution and/or a data evolution.
Or we may store not only the version of the table, but also a version of operations on the data.
using for example the table comment field like following:
##Schema: 1.0, Data: 1.0##
##Schema: 1.1, Data: 1.0##
##Schema: 1.2, Data: 1.0##
##Schema: 1.2, Data: 1.2##
or something like this, rules for version evolutions have to be defined, this is an idea only.

**Comment by edgardmessias** [comment]
See this book: https://developers.redhat.com/promotions/migrating-to-microservice-databases/

**Comment by trasher** [comment]
Notifications migratin sissues has been fixed as of #3041.
