### ISSUE TITLE
For information...

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3045]
Bonjour à tous

J'ai plusieurs bugs sur la 9.2

(traduction, caractères spéciaux dans les tickets, pas de pièce jointe)

Je n'ai jamais vu cela encore un logiciel libre passé en version stable !

Avant de passer GLPI 9.2 en version stable, il faudrait penser à tester même si vous êtes bénévoles

Nous sommes plusieurs mécontents de cette version béta !

http://forum.glpi-project.org/viewtopic.php?id=159440

**Comment by remicollet** [comment]
As I sometime read the new Forum messages... 
I think that there is, indeed, lot of bad feedback against 9.2 (the linked post is only one among others)

So a 9.2.1 should be planed ASAP
