### ISSUE TITLE
Bug after update from 9.1 to 9.2

### ISSUE THREAD

**Issue by sassoumani** [glpi-project/glpi#3047]
Hi everybody ,
I just made an update form 9.1 to 9.2 and when I go to "Computer tab" it returns me a Blank Page.
I have data in the glpi_computers table.
After investigation , I have an error in the sql query ::
...
LEFT JOIN `glpi_items_operatingsystems` ON (`glpi_computers`.`items_operatingsystems_id` = `glpi_items_operatingsystems`.`id` )
==> column: glpi_computers.items_operatingsystems_id doesnt exist.

Some one can help me please ?

**Comment by trasher** [comment]
Seems that a relation is missing here.

**Comment by sassoumani** [comment]
relation missing ?
can you telle me more please

**Comment by trasher** [comment]
It is just a note for developers; I will take a look on this later ;)

**Comment by yllen** [comment]
You go to computer tab of which object? Because the field indicated in your error doesn't exist in GLPI.
No problem for me in 9.2.1 with computer tab of many object (but not all tested)

**Comment by sassoumani** [comment]
<img width="1277" alt="capture d ecran 2017-10-25 a 22 21 40" src="https://user-images.githubusercontent.com/33071117/32015703-ea070cc8-b9d2-11e7-985d-3ba2dcbed6e8.png">

Hi thx for your help ==> Assets --> Computer

**Comment by yllen** [comment]
Look in you database if glpi_computers is not crashed and need repair

**Comment by sassoumani** [comment]
Hi ,
glpi_computers not crashed...

**Comment by danilosantossdbrasil** [comment]
Hi sassoumani,

This error must be related to the table:

glpi_displaypreferences and lines itemtype = Computer

Make a backup of the table and delete the last records with itemtype = Computer

**Comment by sassoumani** [comment]
Hi danilosantossdbrasil ,
Thanks for you're help. It's work now :)

**Comment by trasher** [comment]
Could you tell me what was the line you removed? I've not been able to reproduce the issue.
Does this appears on data inserted from 9.2 or from migrated data?

**Comment by sassoumani** [comment]
delete from glpi_displaypreferences where itemtype='Computer' and num=43 ;

**Comment by yllen** [comment]
@trasher i think i understand.
in 9.1 os_license_number and os_licenseid were defined in search option based on glpi_computers.
I don't see any migration for theses displaypreference.

So if a used has field 43 or 44 in its display preference, you have this error

**Comment by trasher** [comment]
Those options have been moved to `Item_OperatingSystem::getSearchOptionsToAddNew()` and kept the same id; so no migration is required

**Comment by rssouzatec** [comment]
Realizei uma Atualização da Versão 9.1.7.1 para 9.2 e Gerou hum Erro de php, mas DEPOIS Que atualizei para a Versão 9.2.1 O Sistema travou na Atualização Dando o Erro Abaixo.

Atualizar 
Conexão com Banco de Dados realizada com Sucesso 
Alteração de layout de fazer Banco de Dados - glpi_problems (0 Segundo)

Atualizar para 9.2.1 
Trabalho em Progresso ...

9.2 migrar modelos de notificações - Erro na consulta Ao Banco de Dados: INSERT INTO glpi_notifications_notificationtemplates ( notifications_id , mode , notificationtemplates_id ) SELECT id , mode , notificationtemplates_id DE glpi_notifications - não existe Erro E tabela 'hmlglpi.glpi_notifications_notificationtemplates'

Alguem Poderia me Ajudar?

**Comment by trasher** [comment]
@rssouzatec this is the second message from you that is not in english; issues are **english only**.

By the way, issues are for bugs only, use forums to get help; or [get a subscription](http://services.glpi-network.com/) or find a partner around your location, or...
