### ISSUE TITLE
GLPI: Error retrieving RSS feed

### ISSUE THREAD

**Issue by dbegit** [glpi-project/glpi#3048]
Hi,
GLPI doesn't seem to be able to read this rss feed:
https://www.cert.ssi.gouv.fr/feed/

"Error retrieving RSS feed".
Thanks for your help.

System information:
Operating system: Linux srvglp45 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64
PHP 5.6.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/5.6.31 ()
	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0
Server Software: MariaDB Server
	Server Version: 10.2.0-MariaDB
	Server SQL Mode: 
	Parameters: glpi_dba@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* For bug reports, you can open an issue here. Add to your content a full description of your glpi setup (you can find it in Setup > General menu, System tab).
* Provide us steps to reproduce your issue.
* Delete this text to submit your issue.

The GLPI team.

**Comment by flegastelois** [comment]
Hi @dbegit 

It works for me : 

![image](https://user-images.githubusercontent.com/470612/31986354-7768dc9c-b968-11e7-8dc7-9e4722fee0f4.png)

What is your version of GLPI ?
Does your GLPI server have access to the internet ? (with or without a proxy?)

Regards,

**Comment by dbegit** [comment]
@flegastelois 

Hi thanks for your reply.
It's strange, I'm behind proxy but configuration seems ok.
I can download rss feed with wget:
wget https://www.cert.ssi.gouv.fr/feed/

I have the same configuration (screenshot) on GLPI for this RSS feed

But still not working on GLPI 9.2
"Error retrieving RSS feed".
"Debug mode" doesn't help me to know what's wrong.

Proxy configuration on GLPI seems OK. I can download GLPI rssfeed 
![glpi_feed](https://user-images.githubusercontent.com/12554762/32754786-6b1e3536-c926-11e7-8e48-070d6612a038.png)

Thanks for your help

**Comment by trasher** [comment]
Hello,

If you are behind a proxy; you may suffer from a bug from the library we use to retrieve feeds.

This bug has been fixed several months ago; but upstream has just released a new version.

See https://github.com/glpi-project/glpi/issues/1658 and try to update simplepie to the latest release; it should solve your problem. Alternatively, you can wait for 9.2.1 to be released (this week); it will ship the new version of the library.

**Comment by dbegit** [comment]
Same problem with 9.2.1
