### ISSUE TITLE
Anonymous watchers [enhancement]

### ISSUE THREAD

**Issue by Moiwouam** [glpi-project/glpi#305]
**What ?**
Allow anonymous watchers from email receivers (like it is already possible to allow anonymous requesters and followups).
It could be an option to enable in Setup\General\Assistance.

**How ?**
Use [this code](https://github.com/glpi-project/glpi/files/51612/anonymous_watchers.txt) (provided by [orcust](http://forum.glpi-project.org/viewtopic.php?pid=179642#p179642)) in mailcollector.class.php (this do not include option to enable/disable the feature).
Note that I use it in production since more than one year on several versions of GLPI, so it seems fairly safe.

**Comment by orthagh** [comment]
Hello @Moiwouam.

Sorry for the (very) long delay on this issue.
Two options for you : 

* You could add your text on [suggest site](http://suggest.glpi-project.org)
* Or submit a pr for your exising code. After reviewing it, il merge it easily.
