### ISSUE TITLE
Add validation status in changes

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#3050]
Goal : 
We have a request about changes in GLPI to add validation status in the main interface as is the case in tickets.

![validation_change](https://user-images.githubusercontent.com/15138371/31990231-c7c95fac-b974-11e7-84bb-77bf155135d6.png)

Is this possible?
If so, I would send a PR for this change.

**Comment by flegastelois** [comment]
Hi @amma35 

It's OK for us, if you put it read-only like on your screenshot (so, not exactly like tickets form).

Thank you very much,
François.
