### ISSUE TITLE
Problems seeing Tickets on Helpdesk

### ISSUE THREAD

**Issue by timsieler** [glpi-project/glpi#3051]
Hello,

I've a big problem with GLPI. 
Only one user (mine) can see all tickets in Helpdesk > Tickets, even if Filter set to "all".
All other users are shown nothing.
The weird thing is, i've nothing changed, no userright, only a update from 9.1 to 9.2. 
No Error returned, nothing else.
When i create a other user with the same right like my user, he also can't see any ticket.

Please help me.

**Comment by vrocheUP** [comment]
Hello,
I get the same problem on test server, which is in the same configuration than the production server.
I can't see any ticket via "Assistance -> Tickets". I can only see the tickets on the homepage. Even with "Super-Admin" profile, no tickets are shown.
There is no problem on the production server.

What have I done wrong ?

Sincerely

**Comment by trasher** [comment]
@vrocheUP not seeing any ticket is not the same that seeing tickets from only one user... Anyways; on 9.2; when tickets does not appear for any user; this is often due to a migration issue (see https://github.com/glpi-project/glpi/pull/2627).
