### ISSUE TITLE
Change: redirect ticket tab

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3052]
When i add a ticket from ticket tab of a change, i redirect to solve tab of the change

**Comment by trasher** [comment]
I can't reproduce with current 9.2/bf. I do not think anything has been changed that would impact this; so I guess there is something that differs (config? entities tuff? status of change?)

**Comment by yllen** [comment]
You have this comportment if you have a solution in the change, even if the change was put to New status.
You don't have this comportment in change tab of a ticket, even if solution exist in the ticket

**Comment by orthagh** [comment]
I reproduce, here is the steps needed:
- the change must have a solution like @yllen said
- you need to come from the changes list 

After that, a ``&forcetab=Change$2`` should be appended to url
And indeed, it forces the tab solution after all page refresh

**Comment by orthagh** [comment]
It's the common behavior for all itil objects.
Here is the line:
https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/search.class.php?utf8=%E2%9C%93#L4686
