### ISSUE TITLE
GLPI 9.1.6 Do not permit to edit or delete tasks from closed tickets

### ISSUE THREAD

**Issue by jv3rgara** [glpi-project/glpi#3053]
I am having issues with GLPI 9.1.6 which do not permit to edit or delete tasks from closed tickets. I checked with GLPI 9.2 and it is the same issue. On older versions we can edit / add / delete task from closed tickets. Thanks very much.

**Comment by leandrotenorio** [comment]
Any answers?

**Comment by Armin83** [comment]
I thought this "feature" is first available in 9.2 but maybe it is in 9.1.6 too. I have my production at the moment still on 9.1.2 or 9.1.3 and we are going to change task with state "todo" to "done" before we upgrade to 9.2.1.  In my opinion it is correct that you don't should have tasks with state todo on closed tickets. (We use the latest behaviours plugin to check this before the ticket could be solved / closed.)

On point 1 of https://github.com/glpi-project/glpi/issues/2767 i suggested a hint in the change log
