### ISSUE TITLE
How to Enable API REST on GLPI to use as DataSource

### ISSUE THREAD

**Issue by arthurvivareal** [glpi-project/glpi#3054]
Hi all, 
I am newbie with APIs/GLPI, i would like to know how can i enable the Rest API to use on Grafana.

I am facing this error: 
![image](https://user-images.githubusercontent.com/23404572/32017542-ca98b12a-b9a5-11e7-98d4-9b1d047c1ceb.png)

**Comment by trasher** [comment]
API configuration is available from Setup/General/API.
