### ISSUE TITLE
[9.2/bugfixes] PHP Fatal error when access install from UI

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#3056]
- I get the current 9.2/bugfixes branch.
- I try an installation from the UI.

> PHP Fatal error:  Uncaught Error: Call to a member function request() on null in /var/www/glpi/inc/config.class.php:2555
Stack trace:
#0 /var/www/glpi/inc/config.class.php(2687): Config::getConfigurationValues('core', Array)
#1 /var/www/glpi/inc/session.class.php(584): Config::getCache('cache_trans')
#2 /var/www/glpi/install/install.php(542): Session::loadLanguage()
#3 {main}
  thrown in /var/www/glpi/inc/config.class.php on line 2555" while reading response header from upstream php7.0

**Comment by trasher** [comment]
This seems to be due to #2769; we should test if a database connection exists before.
