### ISSUE TITLE
Question: why don't you use the user id == 1

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#306]
Hello,
I saw that the init of the 'glpi_users' table starts with an ID of 2 for user glpi.
Why?
Is there any special reason?

Thank you,
regards,
Tomolimo

**Comment by man4red** [comment]
I belive it`s for a security reason

**Comment by tomolimo** [comment]
ah?

**Comment by yllen** [comment]
in 0.7 1 was for helpdesk injector
In 0.72 this user was deleted and the numeration still stay for compatibility.

**Comment by tomolimo** [comment]
Thank you Yllen,
