### ISSUE TITLE
[9.2] Can't reopen ticket

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#3060]
Hi,

since 9.2, we can't reopen tickets, even with superadmin rights.

`GLPI 9.2 (/glpi => C:\xampp\htdocs\glpi)
--

Operating system: Windows NT STSRV2K8_ING 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586 PHP 5.6.21 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, 	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash, 	mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, standard, tokenizer, wddx, xml, xmlreader, 	xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="60" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache (Apache Server at 192.168.254.3 Port 8895) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.1.13-MariaDB 	Server SQL Mode:  	Parameters: stk@localhost/solutek_glpi 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed xmlrpc extension is installed Zend OPcache extension is not present APCu extension is not present C:\xampp\htdocs\glpi/config : OK C:\xampp\htdocs\glpi/files : OK C:\xampp\htdocs\glpi/files/_dumps : OK C:\xampp\htdocs\glpi/files/_sessions : OK C:\xampp\htdocs\glpi/files/_cron : OK C:\xampp\htdocs\glpi/files/_graphs : OK C:\xampp\htdocs\glpi/files/_lock : OK C:\xampp\htdocs\glpi/files/_plugins : OK C:\xampp\htdocs\glpi/files/_tmp : OK C:\xampp\htdocs\glpi/files/_rss : OK C:\xampp\htdocs\glpi/files/_uploads : OK C:\xampp\htdocs\glpi/files/_pictures : OK C:\xampp\htdocs\glpi/files/_log : OK

htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed) phpCas version 1.3.5 in (C:\xampp\htdocs\glpi\vendor\jasig\phpcas\source) PHPMailer version 5.2.24 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer) SimplePie version 1.5 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library) TCPDF version 6.2.13 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src) iacaml/autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)

Server: '10.6.1.2', Port: '389', BaseDN: 'DC=ELB,DC=local', Connection filter: '(&(objectCategory=person)(objectClass=user))', 		RootDN: 'root', Use TLS: none

Not active

Way of sending emails: SMTP (xxxx@xxxx.local@192.168.254.1)

Name: 'glpi@xxxx.fr' Active: No 	Server: '{192.168.254.1:993/imap/ssl/novalidate-cert}' Login: 'xxxxx\glpi' Password: Yes

archires             Name: Architectures réseau           Version: 2.4.0      State: Not activated 	financialreports     Name: Arrêté du parc                 Version: 2.4.0      State: Not activated 	timelineticket       Name: Chronologie des tickets        Version: 9.1+1.0    State: Not activated 	environment          Name: Environnement                  Version: 2.1.0      State: Not activated 	formcreator          Name: Formulaires                    Version: 2.6.0      State: Not activated 	fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Not activated 	mod                  Name: GLPI Modifications             Version: 1.1.4      State: Enabled 	manufacturersimports Name: Imports fabricants             Version: 2.0.0      State: Not activated 	moreticket           Name: More ticket                    Version: 1.3.0      State: Not activated 	browsernotification  Name: Notification de Navigateur     Version: 1.1.9      State: Not activated 	mreporting           Name: Plus de rapports               Version: 1.3.1      State: Not activated 	manageentities       Name: Portail Clients                Version: 2.2.0      State: Not activated 	purgelogs            Name: Purge de l'historique          Version: 1.2.2      State: Not activated 	reports              Name: Rapports                       Version: 1.11.0     State: Not activated 	webservices          Name: Services Web                   Version: 1.7.       State: Not activated 	dashboard            Name: Tableau de bord                Version: 0.8.8      State: Not activated`

**Comment by trasher** [comment]
Hello,

This ha been fixed; see https://github.com/glpi-project/glpi/issues/2836

**Comment by boscorelly** [comment]
Thanks, i installed 9.2 yesterday, so i was thinking in a new bug, and search in opens tickets gives no result ^^
