### ISSUE TITLE
Queued Mail Not Send v. 9.2

### ISSUE THREAD

**Issue by kelsenlima** [glpi-project/glpi#3075]
Has anyone gone through this scenario? After updating the version of GLPI 9.2 stopped working the routine queued mail, not sending the tickets, even having created a routine in crontab does not work.

Now if it is in the notification queue and forcing there the emails are sent.

I did a clean reinstallation, preserving the database and still the auto send error persists.

**Comment by trasher** [comment]
Check if your crontab table references `QueuedNotifications` and not `QueuedMail`; this may be a migration issue.

**Comment by cayetano** [comment]
I'm replace QuedMail with QueuedNotifications in table glpi_crontasks
THis not solve the problem.

**Comment by trasher** [comment]
Yu error was:
```
 Función QueuedMail::cronqueuedmail no definida (para cron)
( Undefindef function )
```

If you replaced QueudMail; I do not think error is the same. Cannot guess what happen.

**Comment by trasher** [comment]
Migrations issues are solved as of https://github.com/glpi-project/glpi/pull/3041

**Comment by DoctorDeatch** [comment]
Hello friends!
I have the same problem
mail comes chaotically, can go immediately, or maybe in 2 days
all the time hanging in the job to send
and the test is sent immediately
can this be corrected?

**Comment by pxlcore** [comment]
I have the same problem as DoctorDeatch.
I have updated from 9.1.3 to 9.2.1 and the chaos began.
Sometimes the mails are in the notification queue. Sometimes they are sent immediately and sometimes they got lost and were never seen again. Really frustrating.

**Comment by jaguar25v** [comment]
Hello,

Had this been resolved? We also migrated on 2/10/18 to 9.2.1 from 9.1.3 and queuednotification automatic action works very chaotically: well, now it sits for an hour and unless I, explicitly, press "Execute", it will not move.

Any updates would be helpful!

Thanks a lot

**Comment by MatheusPRibeiro** [comment]
Problem solved we increased the "**Frequency of execution**" time of the action to 5 min.
Apparently the action, executed every 1 min was **fought**.

**Comment by trasher** [comment]
As initial issue is fixed; I close this one.
