### ISSUE TITLE
Undefined variable: mid (MailCollector issue?)

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#3076]
Hello all,

Since upgrading from GLPI v9.1.6 to 9.2 (CentOS6), my helpdesk staff are saying that emails with attachments are being collected by GLPI (via the receivers config), but the attachments always get dropped. This worked on 9.1.6.

We are seeing this error in "/var/log/glpi/php-errors.log", which may or may not be related:

2017-10-28 08:37:02 [@svr-h003011.hayley-group.local]
  *** PHP Notice(8): Undefined variable: mid
  Backtrace :
  inc/mailcollector.class.php:1412
  inc/mailcollector.class.php:1545                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:704                    MailCollector->getAttached()
  inc/mailcollector.class.php:540                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1647                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:87                                  CronTask::launch()
2017-10-28 08:37:02 [@svr-h003011.hayley-group.local]
  *** PHP Notice(8): Undefined variable: mid
  Backtrace :
  inc/mailcollector.class.php:1412
  inc/mailcollector.class.php:1545                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:704                    MailCollector->getAttached()
  inc/mailcollector.class.php:540                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1647                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:87                                  CronTask::launch()

Regards,

Elliot

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/2841
