### ISSUE TITLE
Incorrect classes and table names

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3079]
"KnowbaseItem_Comment" must be "Comment_KnowbaseItem"
"KnowbaseItem_Item"         must be" Item_KnowbaseItem"

Names in alphabetic order like done for Group_KnowbaseItem

**Comment by trasher** [comment]
There are already several names that are not consistent (ex. `reminder_user` vs `entity_reminder`).
We need an update in the developer documentation to precise this point.

**Comment by yllen** [comment]
reminder_user and entity_reminder are corrects for me.
What is wrong for your?

**Comment by trasher** [comment]
Since they both describe the similar kind of relation; and if `entity_reminder` is correct; I would name the other `user_reminder`.

I do not understand the logic; that's why I was taking about a doc update: either it's missing or not enough clear to me at least.

**Comment by yllen** [comment]
reminder_user is the users of a reminder and reminders for a user (2 ways).
So the CS for table name and class name was :
-names of 2 objects, in alphabetic order, separated by _ like described in
For doc https://github.com/glpi-project/docdev/pull/68

**Comment by trasher** [comment]
Oh... OK. Thanks for the explanation.

**Comment by trasher** [comment]
See https://github.com/glpi-project/docdev/pull/68#issuecomment-446891987
