### ISSUE TITLE
Problem of translation [Catalan]

### ISSUE THREAD

**Issue by InformaticaAuditori** [glpi-project/glpi#308]
In the Spanish version upgrade from version 0.85 to 0.90 the translation of "Incidencias" to "Peticiones" was added correctly.
In the version in Catalan it has not been done. It could also be changed?

Translations would be (from English to Catalan):

---------------------------------------------------------------------------
In assistance:
Ticket --> Peticions
Create ticket --> Obrir petició
Recurrent tickets --> Peticions recurrents

When a ticket is opened:
New ticket --> Nova petició

In the emails notifications should put:
New ticket "name ticket" --> Nova petició "name ticket"
New followup "name ticket" --> Nou seguiment per a aquesta petició "name ticket"
Ticket solved "name ticket" --> Petició resolta "name ticket"
Deleted ticket "name ticket" --> Supressió d'una petició "name ticket"

Inside the ticket:
Processing ticket --> Petició en procés

**Comment by InformaticaAuditori** [comment]
Another email notificacion:
Deleted ticket "name ticket" --> Supressió d'una petició "name ticket"

**Comment by yllen** [comment]
You can ask to be translator of catalan language https://www.transifex.com/moyo/GLPI/

**Comment by orthagh** [comment]
As described by @yllen, we manage translations on transifex service.
