### ISSUE TITLE
Notification for my changes - email

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#3081]
Hello !

Today I found a strange behaviour with email notifications. Let me explain.

I create a ticket with a Requester with "notifications for my changes set to no"

![image](https://user-images.githubusercontent.com/12936546/32158094-84bf9592-bd47-11e7-881c-9a191de951c1.png)

I activated notifications for new followup with requester as recipients 

![image](https://user-images.githubusercontent.com/12936546/32158131-a2407776-bd47-11e7-9361-eac73cbf1945.png)

When I add a new followup my recipient recieve the email correctly. When I answer it (from the recipient mailbox), a new followup is correctly created in my ticket. 

![image](https://user-images.githubusercontent.com/12936546/32158378-b126fd18-bd48-11e7-84fc-1e0f9107837a.png)

But (and it's strange) the recepient recieve the e-mail for it's own followup when it is added to the ticket ?!?!?!

Is this behaviour normal (is it a bug) ?

Thanks for your help

**Comment by ciadch** [comment]
I try this behaviour with a fresh new install of GLPI and is it the same. When a user respond ton a followup email, he recieves his answer even if "Notifications for my changes" is set to no

**Comment by yllen** [comment]
Notification for my change is only for action done in interface, not for mailcollector

**Comment by ciadch** [comment]
Hi @yllen,
Thanks for your feedback but this behaviour is a bit annoying. Every time a customur answers a ticket by mail, he recieves his own answer ? For me it's a bug or in any case an unwill behaviour. Is there a way to disable this ? Or not ?

Thanks !

**Comment by trelerele** [comment]
I update the information after further testing.

If the user is not created within the GLPI platform, the system works correctly.

If the user is created in the platform with the email information. This is when the bug appears.
