### ISSUE TITLE
Create new ticket rule to automatically set Observer from User of element

### ISSUE THREAD

**Issue by denzoil** [glpi-project/glpi#309]
Hi, is it possible to add this option please?
Thank you

**Comment by denzoil** [comment]
Here is the link to the original discussion:
http://forum.glpi-project.org/viewtopic.php?pid=300221#p300221

Thank you!

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
