### ISSUE TITLE
Satisfaction survey

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3090]
In 9.2, near star for satisfaction we have a dropdown and stars are not colour as selected in my answer (they stay grey).

If i colour stars to change my answer, nothing append (stay stay grey and value in the drown doesn't change).
If i change value of the drodown stars stay grey.

![survey](https://user-images.githubusercontent.com/12936722/32183013-6745e308-bd98-11e7-8fb8-96e51d196e96.jpg)

**Comment by trasher** [comment]
I cannot reproduce exact same behavior. Using a postonly account, I do not have any stars; but only the dropdown (which should not appear).
As I do not know which profile was used; I guess this may be related.

**Comment by yllen** [comment]
i used Super-Admin profile

**Comment by trasher** [comment]
So I cannot reproduce. With described this behavior, there should be a JS issue from the browser; images are loaded from the lib (so this one is loaded); but it should hide the dropown.
I do not reproduce using firefox or chromium

**Comment by yllen** [comment]
I am on firefox

**Comment by orthagh** [comment]
i just tested also. don't replicate at all (firefox/chrome, self-service/super-admin).
Could you test again with the last version of 9.2/bugfixes , @yllen ?

**Comment by orthagh** [comment]
i report again as no confirmation.
For next  milestone, this issue will be closed
