### ISSUE TITLE
No external link tag for user's login (not connected user)

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#3091]
I wanted to create external links for GLPI users.
Say I (user "c-duv") am viewing the *toto* user (it's login is *toto*) page (`.../front/user.form.php?id=42`) I want a link to `http://annuaire.example.com/annuaire/view_user.php?u=toto`.

From all the available tags (`[LOGIN]`, `[ID]`, `[NAME]`, `[LOCATION]`, `[LOCATIONID]`, `[IP]`, `[MAC]`, `[NETWORK]`, `[DOMAIN]`, `[SERIAL]`, `[OTHERSERIAL]`, `[USER]`, `[GROUP]`, `[REALNAME]`, `[FIRSTNAME]`) none seems to hold the user's login.
I can only get my own login ("c-duv") with `[LOGIN]`, it's first and last name and a concatenation of both with `[*NAME]`.

Using the following external link:
`https://example.com/login=[LOGIN];name=[NAME];realname=[REALNAME];firstname=[FIRSTNAME];user=[USER]`

I got the following results (tests ran as user "c-duv"):

| User ID | User login   | lastname | User firstname | `[LOGIN]` | `[NAME]`     | `[REALNAME]` | `[FIRSTNAME]` | `[USER]` |
| ------- | ------------ | -------- | -------------- | --------- | ------------ | ------------ | ------------- | -------- |
|       2 | *glpi*       | *GLPI*   | *Admin*        | *c-duv*   | *GLPI Admin* | *GLPI*       | *Admin*       | *[USER]* |
|       3 | *post-only*  | (none)   | (none)         | *c-duv*   | *post-only*  | (empty)      | (empty)       | *[USER]* |
|      42 | *toto*       | *Foo*    | *Bar*          | *c-duv*   | *Foo Bar*    | *Foo*        | *Bar*         | *[USER]* |

In [inc/link.class.php#L282](https://github.com/glpi-project/glpi/blob/2c49fa9de728ea944064cc04ebbe173721707b20/inc/link.class.php#L282), `[NAME]` tag uses `$item->getName()` which, for a user item calls `getRawName()` which then concatenates last and first name.

According to @tomolimo (in IRC chat), the root cause may be a confusion, in the code, between `RawName` and `CompleteName`.

Tested on GLPI v9.1.2 but code hasn't changed for this part since.

**Comment by orthagh** [comment]
I'm not very confident with the proposed solution.
This can permits to expose fields (like hashed password in users for example)

**Comment by orthagh** [comment]
alternative proposal:

```diff
diff --git a/inc/link.class.php b/inc/link.class.php
index 2d75701f90..b5bafa4adc 100644
--- a/inc/link.class.php
+++ b/inc/link.class.php
@@ -280,7 +280,7 @@ class Link extends CommonDBTM {
       }
 
       if (strstr($link, "[NAME]")) {
-         $link = str_replace("[NAME]", $item->getName(), $link);
+         $link = str_replace("[NAME]", $item->getField('name'), $link);
       }
       if (strstr($link, "[SERIAL]")
           && $item->isField('serial')) {
```
