### ISSUE TITLE
Error with glpi_tickets_tickets  table during upgrade 9.1.6 to 9.2.0 

### ISSUE THREAD

**Issue by innovTech** [glpi-project/glpi#3097]
Hi,
I use GLPI v9.1.6 on LAMP server. (PHP v7.1, MySQL 5.7).
After untar 9.2.0 on the root glpi directory server, I launch upgrade process :
1) The check is full green for PHP modules.
2) During upgrade process, an error occur : 
**Connexion à la base de données réussie
Changement de la structure de la base de données - glpi_tickets_tickets (10 secondes)
Mise à jour en 9.2
Traitement en cours...
Api users tokens has been reset, if you use REST/XMLRPC api with personal token for authentication, please reset your user's token.
PHP User Warning: Table glpi_tickets_tickets does not exists in /home/covateammp/www/glpi1/inc/dbutils.class.php at line 465
9.2 multiple alter in glpi_tickets_tickets - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_tickets_tickets` ADD UNIQUE `unicity` (`tickets_id_1`, `tickets_id_2`) - L'erreur est Table 'covateammpglpi.glpi_tickets_tickets' doesn't exist**

Before upgrade I have only these tables with "glpi_tickets*" filter : glpi_tickets, glpi_ticketsatisfactions, glpi_tickets_users. 

In the _log/php-errors/log : 
**
2017-11-01 14:28:19 [@webm273.300gp.ha.ovh.net]
*** PHP Notice(8): Undefined index: dbversion
Backtrace :
inc/config.php:259                                 
inc/includes.php:57                                include_once()
index.php:60                                       include()
2017-11-01 14:28:36 [@webm273.300gp.ha.ovh.net]
*** PHP User Warning(512): Table glpi_tickets_tickets does not exists
Backtrace :
:                                                  
inc/dbutils.class.php:465                          trigger_error()
inc/db.function.php:585                            DbUtils->isIndex()
inc/migration.class.php:507                        isIndex()
install/update_91_92.php:1907                      Migration->addKey()
inc/update.class.php:394                           update91to92()
install/update.php:456                             Update->doUpdates()
install/update.php:561                             doUpdateDb()
**

In the _log/sql-errors.log : 
**
2017-11-01 14:28:36 [@webm273.300gp.ha.ovh.net]
  *** MySQL query error:
  SQL: SHOW INDEX FROM `glpi_tickets_tickets` WHERE Key_name=\'unicity\'
  Error: Table 'covateammpglpi.glpi_tickets_tickets' doesn't exist
  Backtrace :
  install/update_91_92.php:1890                      
  inc/update.class.php:394                           update91to92()
  install/update.php:456                             Update->doUpdates()
  install/update.php:561                             doUpdateDb()
2017-11-01 14:28:39 [@webm273.300gp.ha.ovh.net]
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_tickets_tickets` ADD UNIQUE `unicity` (`tickets_id_1`, `tickets_id_2`) 
  Error: Table 'covateammpglpi.glpi_tickets_tickets' doesn't exist
  Backtrace :
  inc/dbmysql.class.php:213                          
  inc/migration.class.php:637                        DBmysql->queryOrDie()
  inc/migration.class.php:657                        Migration->migrationOneTable()
  install/update_91_92.php:1976                      Migration->executeMigration()
  inc/update.class.php:394                           update91to92()
  install/update.php:456                             Update->doUpdates()
  install/update.php:561                             doUpdateDb()
**

The end of _log/mogration_to_9.2.log : 
**
0 seconde for "Changement de la structure de la base de données - glpi_olalevels_tickets" @ 2017-11-01 14:28:39 [@webm273.300gp.ha.ovh.net]
0 seconde for "Changement de la structure de la base de données - glpi_states" @ 
**

**Comment by trasher** [comment]
The table tat is missing, `glpi_tickets_tickets` has been added for GLPI 0.80; and is present in all creation scripts since.

I've absolutely no idea what went wrong on your database; but if table does not exists, upgrade to 9.2 is not in cause.

**Comment by innovTech** [comment]
Thanks trasher. I suppose I have a corrupt schema. Do you have an idea how to check it?

**Comment by trasher** [comment]
I guess you should install a fresh 9.1.6 and use a third party tool to compare this one to yours. I've never used myself such a tool; I just know several exists.
Since an entire table is missing; you'd better check entire schema; and if you can try to find an older backup where missing identified table/fields did exists (they may have contain data).
