### ISSUE TITLE
Suggestion - Feature

### ISSUE THREAD

**Issue by grego1981** [glpi-project/glpi#3099]
Hello!

I don't know if anybody else have a usage for it, but I think that the SIM card management in the 9.2 version is really lacking features you cannot store info like sn of card pin puk etc.. If it was to be more like the simcard plugin (which has many more info like pin puk and so on) it would be a lot more useful!

Thank you

**Comment by btry** [comment]
Hi

When you create a simcard component, you actually build a template, like you would do for computers for  example.

![image](https://user-images.githubusercontent.com/14139801/32320853-6a6a2b38-bfbf-11e7-81a6-468fc561e87e.png)
I think you already did this. The next stem is to create instalces of simcards from your template. Click on the tab **Items**,  then create one or several instances

![image](https://user-images.githubusercontent.com/14139801/32320893-a0223c48-bfbf-11e7-8884-111075f48d98.png)

![image](https://user-images.githubusercontent.com/14139801/32320953-d87221f8-bfbf-11e7-92af-f4a715429880.png)

Click on **Update** to populate data specific for each instance of simcard.

![image](https://user-images.githubusercontent.com/14139801/32320984-f50ac4a0-bfbf-11e7-9a9e-12c61c3936d7.png)

If you're using  the release 9.2.0 of GLPI, you will miss the MSIN field (Mobile Subscriber Identification Number). It should be available in GLPI 9.2.1 (fix ready to review and merge).

FYI: MSIN is the last 8 or 10 digits of IMSI. The length depends on the length of the IMSI.

**Comment by btry** [comment]
to ssociate an asset to a simcard, open it (let's say a computer), and choose the tab **Components**

![image](https://user-images.githubusercontent.com/14139801/32321275-e4944780-bfc0-11e7-8e67-1bda3bbfcc5d.png)

![image](https://user-images.githubusercontent.com/14139801/32321373-340f841e-bfc1-11e7-96d1-2bfab0210bed.png)

**Comment by grego1981** [comment]
OK! Thank you it's clear now!

**Comment by btry** [comment]
Great, then I close.
