### ISSUE TITLE
improve title 

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#310]
See : http://glpi.userecho.com/topic/921020-add-objects-name-in-title

**Comment by yllen** [comment]
instead of the id?

**Comment by orthagh** [comment]
In my idea, we can complete id with object name, not replace it

**Comment by tomolimo** [comment]
Currently only object type is shown: 'GLPI - Tickets' when openning a ticket.
It could be a good idea to show: 'GLPI - Ticket 124567' for exemple.

**Comment by tomolimo** [comment]
Something like 'GLPI - Ticket id - Name'?

**Comment by yllen** [comment]
for a ticket, if you don't have title, the title is the beginning of description.
And with description possible in rich text... good luck...

**Comment by tomolimo** [comment]
That's why I initially proposed ticket id only:)

**Comment by C-Duv** [comment]
I quggest to move the "GLPI" part at the end of the `<title>` instead of the beginning.
This way the "useful" part (id. the object's name) is more readable: it also helps when user has many tabs.
The favicon stills informs the user that is looking at is from GLPI.

**Comment by yllen** [comment]
@orthagh You can add ID only if $SESSION['glpiis_ids_visible']
and gettext is not correct for all languages
$title = sprintf(_('%1$s - %2$s'), $title, $_GET['id']);

**Comment by orthagh** [comment]
good point for sprintf.
I dislike the usage of $SESSION['glpiis_ids_visible'] in this case, it's too invasive.
Display the id in title seems to be a more generic need.
Enable ids_visible enable for all pages and for logs (i dislike this part)

**Comment by yllen** [comment]
it's not clear in my post but for sprintf, you have 2 _ (i correct your post)

For showing the ID, if you have an option to show it or not, i think you must use it (like count on tab).
But it's my opinion.
