### ISSUE TITLE
LDAP mass sync script manage deleted users only when ACTION_ALL

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#3100]
Hi,

If we want to use the mass synchronization script LDAP (scripts/ldap_mass_sync.php) once with "action=0" (import users only) and another time with "action=1" (synchronize existing users only) : deleted users from LDAP are never managed (no call to "User::manageDeletedUserInLdap" is made).

To handle these deletes, the use of the "action=2" (import & synchronize users) parameter is mandatory (as you can see in the line):
https://github.com/glpi-project/glpi/blob/11b7b4b1bc05b14fd6ff4ebcf0e32ad986a81d56/inc/authldap.class.php#L1796

We have to adapt this part to handle deletions even when we use "action=1".

François

**Comment by AircraftRu** [comment]
Hi @flegastelois 
I got this bug when setted "Action=2" and about 50 % users were turned action in disabled. After I returned that back, disabled users from AD is no longer setted "Active=no".

GLPI 9.1.7.1 and 9.2.1

**Comment by AircraftRu** [comment]
These users is active in LDAP but they have this historical after runed this script (ldap_mass_sync.php):
![glpi - users - 6122 - mozilla firefox 2017-12-26 18 15 13](https://user-images.githubusercontent.com/17082164/34373496-75eee536-eaec-11e7-9865-899f12d0941b.png)
---
![glpi - users - 667 - mozilla firefox 2017-12-27 09 55 39](https://user-images.githubusercontent.com/17082164/34373498-775228e8-eaec-11e7-9b4f-ea0486f91674.png)

**Comment by AircraftRu** [comment]
Аt each actuation:
![image](https://user-images.githubusercontent.com/17082164/34431739-9642ff92-ec82-11e7-8d9c-cf08b6c021c1.png)

**Comment by flegastelois** [comment]
Hi @AircraftRu ,

Your messages are not related to the subject of this issue, I allowed myself to remove them.

Don't mix subjects please, open a new issue if you think you have a bug (in your case, GLPI is not intended to automatically re-enable disabled accounts).
