### ISSUE TITLE
[9.2] - queuedmail & queuedmailclean dont work

### ISSUE THREAD

**Issue by Sma3il** [glpi-project/glpi#3114]
After upgrading to 9.2, 
mail notifications don't work anymore.
No 'mail queue' link on the Administration menu. 
automatic action 'queuedmail' doesn't work anymore.

**Comment by Sma3il** [comment]
After upgrading to 9.2, 
mail notifications don't work anymore.
No 'mail queue' link on the Administration menu. 
automatic action 'queuedmail' doesn't work anymore.

**Comment by cayetano** [comment]
I have dame issue ( #3115 )

**Comment by trasher** [comment]
Duplicates  #3075

**Comment by Sma3il** [comment]
The #3075 is a solution for GLPI on Linux.
My GLPI is running under Win Server 2012, so no CronTAB.

is it normal to not have the 'mail queue' link on the Administration menu anymore ?

**Comment by trasher** [comment]
Operating system does not matter. There is a "Notification queue" in the menu. This no longer concerns only mails (check release notes).

**Comment by Sma3il** [comment]
Problem solved :
update on the table **glpi_crontasks** 
-  itemtype:  QueuedMail => QueuedNotification
- name : queuedmail => queuednotification
and :
- itemtype : QueuedMail => QueuedNotification
- name : queuedmailclean => queuednotificationclean

thank you.

**Comment by cayetano** [comment]
OK, This work already for me.

thanks
Regads
Cayetano

**Comment by pancutan** [comment]
Didn't work for me, after migrate from 9.1 to 9.3.1
