### ISSUE TITLE
Error Sending Qued Mails Cron / GLPI task

### ISSUE THREAD

**Issue by cayetano** [glpi-project/glpi#3115]
I have a bad english, first sorry.

Sending mail form Administration->Notification Queue, select all -> action send work correcly.
Task "queuedmail" is progrmmed at 1 min.
Cron error ( if marqued as CLI task):
Función QueuedMail::cronqueuedmail no definida (para cron)
( Undefindef function )
Error similar if is GLPI task.

Using GLPI 9.2 mgrated from GLPI 8.4

Thanks
Regrads

Cayetano

**Comment by trasher** [comment]
Duplicates  #3075
