### ISSUE TITLE
not import mails

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#3118]
sometime the mailgate not import mails. 
the reason: operation failure.

Failed operation
--

at header mail says:

CAADLUHHMQsCEV4pgT0J2FtxCRXr=ovoLog312b20v9p_owgvoA@mail.gmail.com

whats the meaning?
thanks

**Comment by sferia82** [comment]
where can i see the error stack?
i have installed glpi in windows with wampserver.

thanks.

**Comment by sferia82** [comment]
this happens when you have to add as a follow-up an email that has just arrived at an existing ticket. it adds it but it does not finish processing the mail and in receivers it appears as that it could not import the mail.

**Comment by trasher** [comment]
Most errors are in logs (files/_log/php-errors.log and/or sql-error.log).

**Comment by sferia82** [comment]
in php-errors-log says now:

2017-11-08 09:00:32 [383@W2K12TICKETING]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  ...nventory\inc\inventorycomputerlib.class.php:187 
  ...ry\inc\inventorycomputerinventory.class.php:577 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1461                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()

**Comment by trasher** [comment]
The error is about fusioninventory. Try to disable all your plugins.

**Comment by sferia82** [comment]
the problem is not that it does not matter, but that once you add the mail to an existing ticket as a follow-up, it does not save it from the inbox. he leaves it as read but does not file it.

**Comment by sferia82** [comment]
for more information I have installed the plugin mail analyzer latest version

**Comment by trasher** [comment]
"Failed operation" is a server issue
