### ISSUE TITLE
Mail attachments import failure

### ISSUE THREAD

**Issue by ferdmanp** [glpi-project/glpi#3121]
After recieving e-mail WITH attachment, GLPI creates ticket WITHOUT attachment. 
php-errors.log contains following message:

 PHP Notice(8): Undefined variable: mid
  Backtrace :
  inc/mailcollector.class.php:1412                   
  inc/mailcollector.class.php:1413                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:1545                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:704                    MailCollector->getAttached()
  inc/mailcollector.class.php:540                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1647                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:87                                  CronTask::launch()

It seems like copy-paste issue. I've made some changes in /inc/mailcollector.class.php, and it works now.

Changes: line 1412
was:
`$this->getRecursiveAttached($mid, $path, $maxsize, $sub_structure,
                                        // ($part ? $part.".".($index+1) : ($index+1)));`
now 
  `$this->getRecursiveAttached($uid, $path, $maxsize, $sub_structure,
                                        ($part ? $part.".".($index+1) : ($index+1)));`

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/2841
