### ISSUE TITLE
Backslash in ticket title

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#3123]
Hello,

When we use single quote in ticket tilte (') and change a parameter who relod form (for exemple category), GLPI add 2 backslashes on it each time for is realoded : 

1) Title set : 
![image](https://user-images.githubusercontent.com/12936546/32486889-4c28cfb6-c3a8-11e7-831f-30b8343afd6d.png)

2) Category changed & form reloaded :
![image](https://user-images.githubusercontent.com/12936546/32487732-cb27db66-c3aa-11e7-8896-2bf7fcb472ba.png)

3) Category changed angain :
![image](https://user-images.githubusercontent.com/12936546/32487761-de2bbd36-c3aa-11e7-9c70-b094580c436d.png)

...

Thank's

**Comment by trasher** [comment]
Could you pelase test with 9.2/bugfixes branch? I think this one has been fixed already, but I do not have time to investigate.

**Comment by edgardmessias** [comment]
I confirmed here, the problem still persists

**Comment by edgardmessias** [comment]
Same problem with `'`, `\` and `"`.

The method `showForm` in `Ticket` class, receive in `name` option:

- `'` -> `\\\'`
- `\` -> `\\\\`
- `"` -> `\\\"`
