### ISSUE TITLE
loading ticket error after mailgate task

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#3124]
sometimes when glpi import with mailgate crontask a mail when i try to visualize the tickets says this:

![image](https://user-images.githubusercontent.com/30896591/32493430-15f94a72-c3be-11e7-83f2-2207d2b14bb1.png)

why?

i don't know the reason.

**Comment by trasher** [comment]
Check the logs

**Comment by sferia82** [comment]
where can i see logs?
thanks

**Comment by trasher** [comment]
I already tell you. 
See https://github.com/glpi-project/glpi/issues/3118#issuecomment-342474788.

**Comment by sferia82** [comment]
also in :   
![image](https://user-images.githubusercontent.com/30896591/32545231-5449f412-c47b-11e7-8429-fe62d37addd1.png)


in logs appear:

2017-11-08 09:00:32 [383@W2K12TICKETING]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  ...nventory\inc\inventorycomputerlib.class.php:187 
  ...ry\inc\inventorycomputerinventory.class.php:577 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:790 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1436                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1461                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:378 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:126 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:235 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:463 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()

**Comment by sferia82** [comment]
i think is attribute description of one ticket. its possible that glpi can't not display the description of one ticket. i don't know who.

**Comment by sferia82** [comment]
for more information this is a mail from wetransfer that always make this error at openning.
this is the original mail from gmail.
see atachment.
[original_msg.txt](https://github.com/glpi-project/glpi/files/1518422/original_msg.txt)


thanks

**Comment by sferia82** [comment]
i do another mail with same content and i do a select to view in database this ticket. but i don't see anything.


[original_msg (1).txt](https://github.com/glpi-project/glpi/files/1521184/original_msg.1.txt)

the .txt is .sql

[glpi_tickets.txt](https://github.com/glpi-project/glpi/files/1521187/glpi_tickets.txt)


thanks

**Comment by trasher** [comment]
Just imported the ticket running SQL insert statment in a 9.2.2 database; I cannot reproduce the issue.
Please check with 9.2.2.
