### ISSUE TITLE
Error Undefined index after update to 9.2

### ISSUE THREAD

**Issue by Climberdav** [glpi-project/glpi#3127]
Hello,

I have somme issues after updating from 9.1.1 to 9.2.

First I had to make a mysqldiff to wuth an new installating to create new tables and column
Then I have some Undefined index PHP Notice : 
For exeample when I go to computer at logon, i have those issues, then if clic "search" button all is fine.
and if change colum order all is fine either.
`PHP Notice: Undefined index: table in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 2271
PHP Notice: Undefined index: field in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 2272
PHP Notice: Undefined index: linkfield in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 2286
PHP Notice: Uninitialized string offset: 0 in /var/www/html/Glpi/releases/20171026100351/inc/toolbox.class.php at line 77
PHP Notice: Undefined index: table in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 368
PHP Notice: Undefined index: table in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 370
PHP Notice: Undefined index: linkfield in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 371
PHP Notice: Undefined index: joinparams in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 372
PHP Notice: Undefined index: field in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 373
PHP Catchable Fatal Error: Argument 1 passed to Search::computeComplexJoinID() must be of the type array, null given, called in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php on line 3607 and defined in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 6153`

In the ticket view I have this notice under all authors : `PHP Notice: Undefined index: notifications_mailing in /var/www/html/Glpi/releases/20171026100351/inc/commonitilobject.class.php at line 3344`

Thank you

**Comment by trasher** [comment]
> First I had to make a mysqldiff to wuth an new installating to create new tables and column

Huh? The only supported way to upgrade is to use the provided scripts.

Missing `notifications_mailing` is probably a bad upgrade issue. Not sure for the others.

**Comment by Climberdav** [comment]
I agree with you about the upgrade but I test many time and I had always the same issue.
I posted this on glpi Forum : 
http://forum.glpi-project.org/viewtopic.php?id=159391
http://forum.glpi-project.org/viewtopic.php?id=159620
Then I have the 9.2 archive installin a new folder, so it can't be an updrage error I think, but just in the database.

**Comment by trasher** [comment]
So, as far I see; you get migration issues. This has been reported and solved for 9.2.1 to come. Basically, you tried an upgrade, then you restore a backup. New tables are not removed, that cause the issue.

As of the `notifications_mailing` warning; the install script does:
```
INSERT INTO `glpi_configs` VALUES ('8','core','notifications_mailing','0');
```

Check if this is present in your database.

**Comment by Climberdav** [comment]
I checked the value and I have ('8', 'core','use_mailing','1')

So I assume changing use_mailing to notifications_mailing is the solution, no ?

**Comment by trasher** [comment]
This is the solution for this particular issue. But if something goes wrong during the update, there may be other issues (by the way, this is not possible you get this value on a fresh 9.2 install).

So, 2 solutions : 
1- fix this one and wait for the 9.2.1 (which should be released in a few days) that should fix other potentials issues;
2- drop entire database, restore you 9.1 backup, and run migration. Do not restore a 9.1 backup on a partially migrated database.

**Comment by Climberdav** [comment]
I restored 9.1 backup last week and done the upgrade after. And I have the issue. I'll fix the issues and wait for the 9.2.1 release.

Thank you

**Comment by Climberdav** [comment]
In the issue I have either this : 
`PHP Notice: Undefined index: table in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 2271
PHP Notice: Undefined index: field in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 2272
PHP Notice: Undefined index: linkfield in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 2286
PHP Notice: Uninitialized string offset: 0 in /var/www/html/Glpi/releases/20171026100351/inc/toolbox.class.php at line 77
PHP Notice: Undefined index: table in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 368
PHP Notice: Undefined index: table in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 370
PHP Notice: Undefined index: linkfield in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 371
PHP Notice: Undefined index: joinparams in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 372
PHP Notice: Undefined index: field in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 373
PHP Catchable Fatal Error: Argument 1 passed to Search::computeComplexJoinID() must be of the type array, null given, called in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php on line 3607 and defined in /var/www/html/Glpi/releases/20171026100351/inc/search.class.php at line 6153`
Have you an idea of what append ?

**Comment by Climberdav** [comment]
With this error in the sql : 
`SELECT 'glpi' AS currentuser, `glpi_consumableitems`.`entities_id`, `glpi_consumableitems`.`is_recursive`, `glpi_consumableitems`.`name` AS `ITEM_0`, `glpi_consumableitems`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_consumableitems`.`ref` AS `ITEM_2`, `glpi_consumableitemtypes`.`name` AS `ITEM_3`, `glpi_manufacturers`.`name` AS `ITEM_4`, `glpi_locations`.`completename` AS `ITEM_5`, `glpi_consumableitems`.`alarm_threshold` AS `ITEM_6_alarm_threshold`, ``.`` AS `ITEM_7`, `glpi_consumableitems`.`id` AS id 
FROM `glpi_consumableitems`
LEFT JOIN `glpi_entities` ON (`glpi_consumableitems`.`entities_id` = `glpi_entities`.`id` )
LEFT JOIN `glpi_consumableitemtypes` ON (`glpi_consumableitems`.`consumableitemtypes_id` = `glpi_consumableitemtypes`.`id` )
LEFT JOIN `glpi_manufacturers` ON (`glpi_consumableitems`.`manufacturers_id` = `glpi_manufacturers`.`id` )
LEFT JOIN `glpi_locations` ON (`glpi_consumableitems`.`locations_id` = `glpi_locations`.`id` ) 
WHERE `glpi_consumableitems`.`is_deleted` = '0' 
ORDER BY ITEM_0 ASC LIMIT 0, 30`
Unknown column '' in 'field list'

**Comment by yoshi314** [comment]
I am hitting the same thing after upgrade on computers view

```
PHP Notice: Undefined index: table in /usr/share/glpi/inc/search.class.php at line 2285
PHP Notice: Undefined index: field in /usr/share/glpi/inc/search.class.php at line 2286
PHP Notice: Undefined index: linkfield in /usr/share/glpi/inc/search.class.php at line 2300
PHP Notice: Uninitialized string offset: 0 in /usr/share/glpi/inc/toolbox.class.php at line 77
PHP Notice: Undefined index: table in /usr/share/glpi/inc/search.class.php at line 368
PHP Notice: Undefined index: table in /usr/share/glpi/inc/search.class.php at line 370
PHP Notice: Undefined index: linkfield in /usr/share/glpi/inc/search.class.php at line 371
PHP Notice: Undefined index: joinparams in /usr/share/glpi/inc/search.class.php at line 372
PHP Notice: Undefined index: field in /usr/share/glpi/inc/search.class.php at line 373
PHP Catchable Fatal Error: Argument 1 passed to Search::computeComplexJoinID() must be of the type array, null given, called in /usr/share/glpi/inc/search.class.php on line 3613 and defined in /usr/share/glpi/inc/search.class.php at line 6175
```



I've been using 9.2 and this happened after update to 9.2.1
