### ISSUE TITLE
Suggestion: Switch notifications templates to Twig OR dwoo  template 

### ISSUE THREAD

**Issue by edgardmessias** [glpi-project/glpi#3131]
See 
Twig
https://twig.symfony.com/
https://twig.symfony.com/doc/2.x/templates.html

Dwoo
http://dwoo.org/
http://dwoo.org/documentation/v1.3/dwoo-for-designers.html

**Comment by trasher** [comment]
We have already think to add a templating system; but this will need to clean the code before removing all direct "echo" for example. This point is quite difficult to achieve because there are many direct echo in the code, and we do not have any clean solution to handle what plugins does.

**Comment by trasher** [comment]
See: https://github.com/glpi-project/glpi/issues/3662
