### ISSUE TITLE
"Create New Ticket" Page takes about >15 seconds to load (except super-admin)

### ISSUE THREAD

**Issue by ahinck** [glpi-project/glpi#3132]
HI,

after Upgrade to 9.2 the "new ticket" form takes a long time to show up. Only with super-admin rights it takes < 1 second (?)

![grafik](https://user-images.githubusercontent.com/5278733/32517431-bd10edae-c406-11e7-9747-f3880cd9cbf6.png)

Any ideas?
Thanks + regards
A. Hinck

**Comment by trasher** [comment]
Do you have many entities or a quite complex entities hierarchy?

This issue should be solved activating APCu on your server.

**Comment by trasher** [comment]
No feedback, closing
