### ISSUE TITLE
Save and add to the knowledge base

### ISSUE THREAD

**Issue by Ruiseart** [glpi-project/glpi#3133]
I probably found a problem in GLPI v. 9.2. I select "Yes" in Ticket -> Processing ticket -> Solution -> Save and add to the knowledge base and I press the Save button. The ticket is saved, but GLPI does not add the solution in the knowledge base.

**Comment by trasher** [comment]
Could you please try with current 9.2/bugfixes branch?

**Comment by Ruiseart** [comment]
I did the test and there is no such error in GLPI 9.2/bugfixes branch.

**Comment by Ruiseart** [comment]
In GLPI version 9.2.1 the problem was fixed.
