### ISSUE TITLE
Shortcut to 'Assign myself' in a ticket

### ISSUE THREAD

**Issue by lanner22** [glpi-project/glpi#3137]
Would it be possible to add any shortcut to the 'assing myself to a ticket' tool in the main panel or inside the ticket, in the Processing ticket tab?

**Example below:**

![img1](https://i.imgur.com/Js1egND.png)
![img1](https://i.imgur.com/7paqrts.png)

**Comment by trasher** [comment]
Please use [suggestions website](http://suggest.glpi-project.org)

**Comment by ladenree76000** [comment]
it allready exists (9.2.2 or 9.1.6)
![image](https://user-images.githubusercontent.com/13557254/37522017-f6c4e8f8-2922-11e8-822e-984675728723.png)
If you can own this ticket
