### ISSUE TITLE
Add a "lightbox" JS to display images

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#3139]
When we want to display an image (from a ticket or a followup), fullsize image is opened in a new tab.

using a "lightbox" like JS plugin would permit to open it in a popup.

[FancyBox](http://fancyapps.com/fancybox/3/) is quite a good library; but their dual license sounds strange to me... How something could be GPL and commercial in the same time? Well, this is GPL, so this should be included in GLPI.

There are many alternatives; so I guess we could find something that does the job. Any hints?

**Comment by edgardmessias** [comment]
MIT License:
- [PhotoSwipe](http://photoswipe.com/)
- [MagnificPopup](http://dimsemenov.com/plugins/magnific-popup/)

**Comment by trasher** [comment]
Thank you :) I did not know PhotoSwipe.

As far as I can see, PhotoSwipe is more oriented on gallery; but I guess we can use one image galleries. A feature I appreciate (and I did not see on MagnificPoup) is the "full size zoom" for very large images.

**Comment by trasher** [comment]
Smartphoto seems a good candidate too.

As for LightGallerry... Well; their license ise very unclear to me; just as FancyBox. This is GLP, but they want to impose limitations that are not compatible... I'd prefer to use a lib that has a clear license.

**Comment by edgardmessias** [comment]
More one options: [Lightcase.js](http://cornel.bopp-art.com/lightcase/)

**Comment by abr4xas** [comment]
Another option is: http://lokeshdhakar.com/projects/lightbox2/
