### ISSUE TITLE
GLPI 9.2 restore after backup

### ISSUE THREAD

**Issue by menvol3** [glpi-project/glpi#3145]
Hi

i have an issue in my GLPI 9.2 

before that I had the version 9.1.3,  and  restoring worked fine, but in  the new 9.2 version  backup is creating  but than when i press the  button to  restore from file , the rest of the page just restarts and nothing else appears

**Comment by trasher** [comment]
Could you please check logs and give relevant errors?

**Comment by menvol3** [comment]
Tell me please
which file should be checked?

**Comment by menvol3** [comment]
also in system parameters i receive this messages 

Zend OPcache extension is not present
APCu extension is not present
xmlrpc extension is not present


it can affect to restoring from backup ?

**Comment by menvol3** [comment]
although on version 9.1.3 this extensions were no present too, but restoring worked fine

**Comment by menvol3** [comment]
also button permanently delete don't work as button restore from backup  page just restarts and nothing else appears

**Comment by trasher** [comment]
I do not know exactly what is required for backup/restore. OPCache and APCu are not mandatory. This just makes things faster.
xmlrpc is required only if you use the xmlrpc api.

Logs files are in glpi/files/_log/. Check both php-errors.log and sql-errors.log (for each issue).

**Comment by menvol3** [comment]
This error i receive in file php-errors when press button delete permanently


> 2017-11-10 12:41:33 [@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477
  Zend\Loader\SplAutoloader has been dropped from GLPI. 
2017-11-10 12:41:33 [@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\autoload.function.php:313                      Toolbox::deprecated()
  :                                                  glpi_autoload()
  plugins\genericobject\inc\autoload.php:6           spl_autoload_call()
  plugins\genericobject\setup.php:82                 include_once()
  inc\plugin.class.php:257                           include_once()
  inc\plugin.class.php:114                           Plugin->checkStates()
  inc\includes.php:112                               Plugin->init()
  plugins\fusioninventory\index.php:49               include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477
  Zend\Loader\SplAutoloader has been dropped from GLPI. 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\autoload.function.php:313                      Toolbox::deprecated()
  :                                                  glpi_autoload()
  plugins\genericobject\inc\autoload.php:6           spl_autoload_call()
  plugins\genericobject\setup.php:82                 include_once()
  inc\plugin.class.php:140                           include_once()
  inc\includes.php:118                               Plugin::load()
  front\backup.php:37                                include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.036", 5.79Mio)
  TableExists() function is deprecated 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:549                            Toolbox::deprecated()
  plugins\genericobject\inc\type.class.php:1568      TableExists()
  plugins\genericobject\setup.php:159                PluginGenericobjectType::getTypes()
  :                                                  plugin_post_init_genericobject()
  inc\plugin.class.php:1271                          call_user_func()
  inc\includes.php:122                               Plugin::doHook()
  front\backup.php:37                                include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.020", 6.57Mio)
  FieldExists() function is deprecated 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:568                            Toolbox::deprecated()
  plugins\genericobject\inc\type.class.php:1709      FieldExists()
  plugins\genericobject\inc\object.class.php:343     PluginGenericobjectType->canUseTemplate()
  plugins\genericobject\inc\object.class.php:114     PluginGenericobjectObject->canUseTemplate()
  plugins\genericobject\setup.php:162                PluginGenericobjectObject::registerType()
  :                                                  plugin_post_init_genericobject()
  inc\plugin.class.php:1271                          call_user_func()
  inc\includes.php:122                               Plugin::doHook()
  front\backup.php:37                                include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.011", 6.67Mio)
  TableExists() function is deprecated 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:549                            Toolbox::deprecated()
  plugins\genericobject\inc\field.class.php:184      TableExists()
  plugins\genericobject\inc\field.class.php:278      PluginGenericobjectField::getFieldName()
  plugins\genericobject\inc\type.class.php:1666      PluginGenericobjectField::getFieldOptions()
  plugins\genericobject\inc\object.class.php:199     PluginGenericobjectType::getDropdownForItemtype()
  plugins\genericobject\setup.php:162                PluginGenericobjectObject::registerType()
  :                                                  plugin_post_init_genericobject()
  inc\plugin.class.php:1271                          call_user_func()
  inc\includes.php:122                               Plugin::doHook()
  front\backup.php:37                                include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477
  Zend\Loader\SplAutoloader has been dropped from GLPI. 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\autoload.function.php:313                      Toolbox::deprecated()
  :                                                  glpi_autoload()
  plugins\genericobject\inc\autoload.php:6           spl_autoload_call()
  plugins\genericobject\setup.php:82                 include_once()
  inc\plugin.class.php:140                           include_once()
  inc\includes.php:118                               Plugin::load()
  front\cron.php:42                                  include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.037", 5.72Mio)
  TableExists() function is deprecated 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:549                            Toolbox::deprecated()
  plugins\genericobject\inc\type.class.php:1568      TableExists()
  plugins\genericobject\setup.php:159                PluginGenericobjectType::getTypes()
  :                                                  plugin_post_init_genericobject()
  inc\plugin.class.php:1271                          call_user_func()
  inc\includes.php:122                               Plugin::doHook()
  front\cron.php:42                                  include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.022", 6.49Mio)
  FieldExists() function is deprecated 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:568                            Toolbox::deprecated()
  plugins\genericobject\inc\type.class.php:1709      FieldExists()
  plugins\genericobject\inc\object.class.php:343     PluginGenericobjectType->canUseTemplate()
  plugins\genericobject\inc\object.class.php:114     PluginGenericobjectObject->canUseTemplate()
  plugins\genericobject\setup.php:162                PluginGenericobjectObject::registerType()
  :                                                  plugin_post_init_genericobject()
  inc\plugin.class.php:1271                          call_user_func()
  inc\includes.php:122                               Plugin::doHook()
  front\cron.php:42                                  include()
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  From Toolbox::deprecated() in C:\xampp\htdocs\glpi\inc\toolbox.class.php line 477 (0.012", 6.60Mio)
  TableExists() function is deprecated 
2017-11-10 12:41:42 [8@GRAVITYDEFIED]
  Backtrace :
  inc\toolbox.class.php:478                          Toolbox::backtrace()
  inc\db.function.php:549                            Toolbox::deprecated()
  plugins\genericobject\inc\field.class.php:184      TableExists()
  plugins\genericobject\inc\field.class.php:278      PluginGenericobjectField::getFieldName()
  plugins\genericobject\inc\type.class.php:1666      PluginGenericobjectField::getFieldOptions()
  plugins\genericobject\inc\object.class.php:199     PluginGenericobjectType::getDropdownForItemtype()
  plugins\genericobject\setup.php:162                PluginGenericobjectObject::registerType()
  :                                                  plugin_post_init_genericobject()
  inc\plugin.class.php:1271                          call_user_func()
  inc\includes.php:122                               Plugin::doHook()
  front\cron.php:42                                  include()

>

**Comment by trasher** [comment]
All warnings are form the genericobject plugin that is not compatible with GLPI 9.2. Please remove the plugin and try again.

**Comment by menvol3** [comment]
okay, i delete it 
now i receive this

2017-11-10 13:13:15
  From DBmysql::optimize_tables() in C:\xampp\htdocs\glpi\inc\dbmysql.class.php line 558
  Cannot launch automatic action : crashed tables detected

**Comment by trasher** [comment]
So you have to repair your database

**Comment by menvol3** [comment]
Hi

i decided to create new glpi database on virual machine to test this problem

and after creating backup with one asset, i can't restore with it

there is only one word "Test" in php-errors log file

**Comment by trasher** [comment]
OK, will have to take a closer look when I'll have time :)
