### ISSUE TITLE
[9.2] ticket description looses newline character

### ISSUE THREAD

**Issue by mmallejac** [glpi-project/glpi#3148]
With the new 9.2 release, we've noticed that the description field of a ticket looses the newline character, when there's 3 lines or more 

Open new ticket, with ticket description 
line1
line2
line3

Go back the this ticket, and the description line nows shows
line1rnline2rnline3

We do not use the rich text editor so far.

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/2870
