### ISSUE TITLE
[9.2] difficult to edit again a ticket task

### ISSUE THREAD

**Issue by mmallejac** [glpi-project/glpi#3149]
When editing an already existing ticket task, some fields are out of the display.
My screen resolution is 1920x1080

If working in _Tabs on left_ mode 
![selection_004](https://user-images.githubusercontent.com/11666281/32720495-067ab130-c864-11e7-91f7-583d6de2a80d.jpg)

Even worse in _Vertical split_ mode
![selection_005](https://user-images.githubusercontent.com/11666281/32720605-5fd6ae8c-c864-11e7-8875-ebc9ce5d88a1.jpg)

**Comment by trasher** [comment]
I guess this one has already been fixed for 9.2.1. Please try with current 9.2/bugfixes branch or wait for 9.2.1 to be released (this week).
