### ISSUE TITLE
forbid creation of item in root entity

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#315]
If a user remove entities_id hidden field in his browser dom (with dev tools - F12 in firefox for example), the items will be created in root entity regardless of user profile (computer for example)

User and User_Profile aren't impacted

It's a minor issue, but we can improve check function to avoid that.

Here is some ideas to prevent the problem : 

https://gist.github.com/orthagh/e466425d51cedf2986a3
https://gist.github.com/orthagh/85ed5f45a0722b4f2bd1

@yllen, your opinion ?

**Comment by remicollet** [comment]
IMHO not the right fix.

If entities_id is missing, this means either:
* a glpi bug (missing in the form)
* an security attack (your scenario)

In both case, action should be denied.
So this have to be manage in the "can" method.

**Comment by yllen** [comment]
For me if the user delete needed information, like entity, the function can() must refuse the action.
When you create a ticket, entity is the entity of the requester, not the entity of the author.
