### ISSUE TITLE
[9.2] Ticket tasks to do and Problem tasks to do

### ISSUE THREAD

**Issue by mmallejac** [glpi-project/glpi#3150]
The Personal View now shows two more tables : _Ticket tasks to do_ and _Problem tasks to do_

Since we do not use the Ticket task's status, it defaults to _To do_ and then is now displayed in the Personal View.

There is no longer a way to select which items should be displayed in the _Personal View_.
(or - alternatively - is there a way to default a Ticket and Problem task's status to Done ?)

Many thanks !

**Comment by Armin83** [comment]
personal settings

**Comment by mmallejac** [comment]
Thanks Armin

I've updated my database to set all existing tasks to Done and found the related setting for all new taks, so this is under control : I no longer see the tasks there.

But I couldn't find a way to configure which item should be shown in the _Personal View_
For instance, I'd like not to see the "Your tickets in progress" in this view.
I think something used to exist for that, but I cannot find it anymore. Am I wrong ?

**Comment by Armin83** [comment]
i believe there is not setting to change this view

**Comment by mmallejac** [comment]
Ok, so there is no longer need for this, I close it. Thanks !!
