### ISSUE TITLE
closeticket automatic not working in GLPI 9.2

### ISSUE THREAD

**Issue by marcelofares** [glpi-project/glpi#3153]
The automatic close call function (closeticket) stopped working after I upgraded to 9.2. the script that I use in the windows task scheduler is this below:

c:\xampp\php\php.exe c:\xampp\htdocs\glpi\front\cron.php 

File name is cronGLPI.bat

Can someone help me ?

![captura de tela 2017-11-13 as 13 35 02](https://user-images.githubusercontent.com/33350931/32733880-a21f941c-c877-11e7-8624-6c5b7879b48f.png)

**Comment by edgardmessias** [comment]
PT-BR:
- Primeiro: troque o modo de execução de `GLPI` para `CLI`
- Segundo: Clique no (X) na linha do "Próxima execução   Executando (X)"
- Realizar testes

**Comment by marcelofares** [comment]
Olá @edgardmessias muito obrigado por sua resposta, mas não funcinou cara. 
Por acaso voce tem algum .bat pronto pra min testar pois isso aconteceu depois que atualizei meu GLPI para 9.2 pois antes funcionava normal o meu .bat com a ação dentro do agendador de tarefas.

**Comment by trasher** [comment]
Hello,

Could you please use english only, so everyone can undesrtand? Thank you :)

**Comment by marcelofares** [comment]
@trasher 

Unfortunately the above friend's tip in Portuguese did not work.

I ask.
Someone has some (.bat) as an example, but that is functional on windows so I can test?
I'm doubting the lines of my script in this new version of GLPI.

**Comment by edgardmessias** [comment]
@marcelofares, see the file: `glpi\files\_log\php-errors.log`

My skype: edgardmessias

**Comment by trasher** [comment]
Also check in your `glpi_crontasks` table there are no longer references to `QueuedMail` but to `QueuedNotification` (this is a quite common upgrade issue to 9.2).

**Comment by marcelofares** [comment]
@trasher  Sorry for my ignorance, but where do I see this?

**Comment by trasher** [comment]
You have to chek MySQL table content. Or wait for 9.2.1 release that will fix migration issues.

**Comment by marcelofares** [comment]
Any predictions for the release of this new version?

**Comment by trasher** [comment]
https://mail.ow2.org/wws/arc/glpi-users/2017-11/msg00000.html

**Comment by edgardmessias** [comment]
The `glpi_queuednotifications` and `glpi_crontasks` is OK

**Comment by marcelofares** [comment]
Thank you very much, my friend @edgardmessias .

**Comment by edgardmessias** [comment]
The problem was that the tasks are locked, restarted and worked again
