### ISSUE TITLE
Rich Text: image not visible in tickets.

### ISSUE THREAD

**Issue by dbegit** [glpi-project/glpi#3154]
Hi,
We have a problem with Rich Text on GPLI 9.2, we can't see image in ticket where request source is email.
![glpi_richtext](https://user-images.githubusercontent.com/12554762/32754988-4d6a7832-c927-11e7-9b59-8256a7bbfb32.png)

**Comment by trasher** [comment]
Hello,

This duplicates https://github.com/glpi-project/glpi/issues/2869
