### ISSUE TITLE
[9.2] Php Error on create ticket

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#3156]
For information I have a SLA with TTO SLM (5h) 
```
2017-11-14 14:01:10 [6@P399]
  *** PHP Notice(8): Undefined index: ttr_slalevels_id
  Backtrace :
  inc\levelagreement.class.php:986                   
  inc\ticket.class.php:1514                          LevelAgreement->addLevelToDo()
  inc\ticket.class.php:2126                          Ticket->manageSlaLevel()
  inc\commondbtm.class.php:929                       Ticket->post_addItem()
  front\ticket.form.php:67                           CommonDBTM->add()
```

**Comment by trasher** [comment]
Is the `ttr_slalevels_id` column present in your `glpi_tickets` table?

**Comment by tsmr** [comment]
Yes

**Comment by tsmr** [comment]
I have already the problem into glpi 9.1 version

I add this into glpi 9.1 version
```
$ttr_slalevels_id = 0;

      if(isset($this->fields["ttr_slalevels_id"])) {
         $ttr_slalevels_id = $this->fields["ttr_slalevels_id"];
      }
$slalevels_id = ($slalevels_id ? $slalevels_id
                                     : $ttr_slalevels_id);
```

at the beginning of the function addLevelToDo into slt.class.php

**Comment by trasher** [comment]
As far as I know; if the field is present in the database; this must be part of the array. So I do not agree to fix like that

**Comment by amma35** [comment]
When adding a ticket, if you don't select internal_time_to_own or time_to_own, the field ttr_olalevels_id or ttr_slalevels_id is not present.
There is no problem when updating a ticket because when creating the ticket, the field has been initialized to 0.

**Comment by amma35** [comment]
@trasher I think that this correction will help to resolve this issue: https://github.com/glpi-project/glpi/issues/2908

**Comment by trasher** [comment]
OK, I will ask for feedbacks, thank you :)
