### ISSUE TITLE
Missing "New ticket for this item" on User form (Ticket tab)

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#3157]
"User" entry is missing in the array $CFG_GLPI['ticket_types'] :
https://github.com/glpi-project/glpi/blob/04d0e5711b5172e5f9a1e8d5880491d0d86e062c/inc/define.php#L267

And in the column "glpi_profiles.helpdesk_item_type" of each profile in glpi-empty.sql :
https://github.com/glpi-project/glpi/blob/04d0e5711b5172e5f9a1e8d5880491d0d86e062c/install/mysql/glpi-empty.sql#L7001

Also requires changes in the update process.

**Comment by tabad** [comment]
Hello @flegastelois,

I'm not sure but maybe [this idea](http://bit.ly/2jxiWd3) in [UserEcho](http://glpi.userecho.com/) be related with this issue.

Regards,
