### ISSUE TITLE
[9.2] Errors detected by IDE - $itemtype_2

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#3158]
https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/budget.class.php#L489
https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/document_item.class.php#L524

Undefined variable $itemtype_2

**Comment by trasher** [comment]
I guess your IDE is wrong in both cases. `$item::$itemtype_2` refers to the static property `$itemtype_2` of the Item_Device object; not to a local variable.
