### ISSUE TITLE
[0.91] Allow multiple select on Dropdown::show

### ISSUE THREAD

**Issue by korial29** [glpi-project/glpi#316]
Only Dropdown::showFromArray allows to set multiple choice.
It would be very useful to enable it on every other dropdowns.

To do that the JQuery Select2 library must be upgraded to version 4.0.x.
The "initSelection" must be replaced in Html::jsAjaxDropdown

**Comment by yllen** [comment]
and you must review all code...

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
I close this issue, as noone seems to work on this, but feel free to open a PR if you want to implement it by yourself.

Regards
