### ISSUE TITLE
Incorrect massive action controls in "Items" tab of Tickets...

### ISSUE THREAD

**Issue by tabad** [glpi-project/glpi#3161]
The bug appears in GLPI v9.2 and GLPI 9.1.x. See the attached pictures.

![screenshot-demo glpi-project org-2017-11-15-14-16-54](https://user-images.githubusercontent.com/2183103/32838936-ef2be20a-ca12-11e7-84e9-71d2f85264dd.png)

The "Update the item" column does not contribute anything. Also the action "Delete permanently the relation with selected elements" does not work.

**Comment by trasher** [comment]
I agree for th last column; I guess this should be dropped.
As of the delete massive action, I've just tested it on 9.2/bugfixes branch; all went well. Maybe the issue has been fixed already, or there are specificities to get that reproduced.

**Comment by trasher** [comment]
This UI is quite complex to understand, and is not coherent with what exists elsewhere.

Both checkboxes are designed to be used with the same massive actions button. The massive action form display all possibilities for both items; so actions will work or not depdning on which chackboxes have been checked...

We've decided to remove massive action on items themselves, and keep only ones for the relation (same behavior as all other screens in GLPI).
