### ISSUE TITLE
Duplicate id_search_option (123) in Infocom

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#3162]
Field **warranty_date**:
https://github.com/glpi-project/glpi/blob/09937d583eea9bc2f7b4b609be271d98bdd9f495/inc/infocom.class.php#L1430

Field **glpi_businesscriticities**:
https://github.com/glpi-project/glpi/blob/09937d583eea9bc2f7b4b609be271d98bdd9f495/inc/infocom.class.php#L1588

**Comment by trasher** [comment]
Erf... This should not happen since we've added unit tests to check those duplicates. Have to find out why tests did not see this one.

**Comment by edgardmessias** [comment]
The test `tests/units/Infocom.php` never call the `getSearchOptionsToAdd` function.

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/pull/3417
