### ISSUE TITLE
[9.2] Task elements don't fit on the screen

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3163]
Hello,
GLPI 9.2
I have a screen resolution is 1280x1024 and task elements don't fit on the screen when I open edit mode.

![glpi - tickets](https://user-images.githubusercontent.com/17082164/32882515-aa337060-cac5-11e7-9ed2-897e469c46d5.png)

**Comment by trasher** [comment]
This duplicates https://github.com/glpi-project/glpi/issues/3149
