### ISSUE TITLE
[9.2] cartridge notification error

### ISSUE THREAD

**Issue by hasop** [glpi-project/glpi#3166]
After 9.2 migration, there's an error on cartridge notification :

Subject: [GLPI] ##cartridge.action##  ##cartridge.entity##
Body : ##lang.cartridge.entity## : ##cartridge.entity##

=> tags are no longer interpreted

**Comment by mrspam** [comment]
Hi !

Same problem for me.

**Comment by edgardmessias** [comment]
Hello.

To fix for now, edit the file `inc/notificationtargetcartridgeitem.class.php`

Change `addtDataForTemplate` to `addDataForTemplate` (Removed the letter 't')

**Comment by mrspam** [comment]
Modification done but problem persiste for me.

![sans titre](https://user-images.githubusercontent.com/26159277/33003783-552963ae-cdd6-11e7-8757-a60b2a8c900a.jpg)

**Comment by mrspam** [comment]
Oh sorry it's good finally ^^
