### ISSUE TITLE
Improve template documentation

### ISSUE THREAD

**Issue by artmoni** [glpi-project/glpi#3167]
Because the notification template is an important part to customize the solution, it should be better to have a clear template documentation.

The documentation page below is very poor, some part are not working (foreach last) and no sample code is shown. 

http://glpi-project.org/DOC/FR/glpi/config_notification_templates_tags.html

**Comment by trasher** [comment]
Please report documentation issues on the doc repository:
https://github.com/glpi-project/doc

Also, feel free to propose a pull request to get that page improved.

Thanks.
