### ISSUE TITLE
[9.2] Calendar field problem on "Licences" and "Contracts"

### ISSUE THREAD

**Issue by mrspam** [glpi-project/glpi#3171]
Hi !

I see this topic about translation calendar problem (https://github.com/glpi-project/glpi/issues/2905).

Modification solve problem but in "Licences" and "Contracts" tab the field calendar not work (no logo) and when I put a date and save, I see no modification in the field.

You can see in the picture below, up it's for the Licences and down for the contract.

https://user-images.githubusercontent.com/26159277/32877217-d4e1d4de-cab9-11e7-9d5d-c1c71772a535.jpg

When I delete the modification, all is ok but not the translation calendar problem (in english not french).

Tested on 2 plateforms (production & test).

**Comment by trasher** [comment]
Which GLPI version do you use? Calendar translation issues has been fixed in 9.2.1 released yesterday; try with this one.

**Comment by mrspam** [comment]
GLPI 9.2 ok thank you I try it.

**Comment by mrspam** [comment]
Perfect it work thanks ! =)

**Comment by trasher** [comment]
Great :)
