### ISSUE TITLE
[9.2.1] Error while updating from 9.2 to 9.2.1

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3172]
Hello, 
Error while updating from 9.2 to 9.2.1
Before that I had updated from 9.1.4 to 9.2 on 2 month ago.

![setup glpi - google chrome 2017-11-17 12 55 06](https://user-images.githubusercontent.com/17082164/32941509-12c62768-cb97-11e7-80f1-aefbf792e204.png)

**Comment by AircraftRu** [comment]
The PHP Notice while updating  from 9.1.4 to 9.2.1:

![setup glpi - google chrome 2017-11-20 11 56 10](https://user-images.githubusercontent.com/17082164/33011385-eac07b88-cdee-11e7-9b1d-098f2f0f5c58.png)

**Comment by premutos86** [comment]
same issue for me

**Comment by tech62** [comment]
`[SLM profilerights migration - Erreur durant l'éxecution de la requête : UPDATE `glpi_profilerights` SET `name` = 'slm' WHERE `name` = 'sla' - L'erreur est Duplicate entry '1-slm' for key 'unicity']
`
For me

**Comment by tech62** [comment]
![glpi_error](https://user-images.githubusercontent.com/16237642/33021792-5d696190-ce03-11e7-8628-88e448d90fdc.JPG)

Same things for me 👎

**Comment by zawaye** [comment]
I got this error message too. Can someone help me, if you can fix this problem please?

**Comment by ladenree76000** [comment]
can you check 
SELECT * FROM `glpi_profilerights` where name like ('sl%') ORDER BY `glpi_profilerights`.`profiles_id` ASC 

do you have some profile with more than 1 record  ?

**Comment by tech62** [comment]
![bug_glpi](https://user-images.githubusercontent.com/16237642/33076788-0259c576-cece-11e7-903a-b15cb8a291ca.JPG)
Thanks for your attention, I've this

**Comment by ladenree76000** [comment]
I guess this was not you first migration attempt ?  

/!\make sure you have a dump from your database and you can restore it/!\

DELETE FROM glpi_profilerights where  name ='slm'

**Comment by tech62** [comment]
![glpi_error2](https://user-images.githubusercontent.com/16237642/33078117-06fe3388-ced2-11e7-8f4f-abe2eca5f00c.JPG)

Done, and after i've try to restart the upgrade but the bug is always here :/

**Comment by trasher** [comment]
This is not the same error, and this is due to your previous migrations attempts as well. FIxed for https://github.com/glpi-project/glpi/issues/3184.

By the way, this is absolutely not related to the original issue reported here.

**Comment by trasher** [comment]
@AircraftRu check if you `glpi_slts` table has a `slas_id` column. If that column exists, rename it to `slms_id`; drop index on `slas_id` and add a new one on `slms_id`.

Something went wrong in previous update, no idea what.

**Comment by tech62** [comment]
I'm updating from 9.2 to 9.2.1 .. it's not a big migration ! 
#3184 Fixed in previous version but present in 9.2 and after i use your tips to modify the update script i've got a new error, referenced in #3184 too ..

**Comment by tech62** [comment]
@trasher Don't forget to add a slms_id in glpi_slas after that the update is ok
Can you tell me the property of this field (AI .. )

**Comment by AircraftRu** [comment]
@trasher Hello
`slas_id` and `slms_id` didn't exist in `glpi_slas`. I created `slms_id`. 
Thanks a lot.

**Comment by kornelson** [comment]
I have the same problem, Im´trying to update my glpi from 9.1.6 to 9.2.1 but i can't get that. this is the error.  Error is Key column 'slms_id' doesn't exist in table

AircraftRu may you explain in detail wich is the best way to update without any error. Thanks. and sorry, but my english is poor 👯‍♂️

**Comment by kornelson** [comment]
Hello again, I can Finally update the system, but first, I have to update the 9.1.6 version to 9.1.7.1, and after that I applied the 9.2.1 update, disabled the plugins, and downloaded and replaced the plugins for the correct version. and now I have the 9.2.1 working fine. Thanks. 

The link for 9.1.7.1 version here https://github.com/glpi-project/glpi/releases

**Comment by zawaye** [comment]
Hello,
I can upgrade it as **Kornelson** Said. But, **I couldn't find my previous created ticket in 9.2.1.** Can anyone guide me how can I fix that problem?

**Comment by trasher** [comment]
For migration issues (missing fields, tables ...);see https://github.com/glpi-project/glpi/issues/3427#issuecomment-364856200
For unicity, there has been several tickets opened; take a look ath those ones.

**Comment by rssouzatec** [comment]
Como corrigir este erro - GLPI 9.2.1


PHP User Warning: Table glpi_certificates does not exists in /var/www/html/paginas/hmlglpi/inc/dbmysql.class.php at line 758
PHP User Warning: Table glpi_certificates does not exists in /var/www/html/paginas/hmlglpi/inc/dbmysql.class.php at line 758
9.2.1 multiple alter in glpi_certificates - Erro na consulta ao banco de dados: ALTER TABLE `glpi_certificates` ADD `contact` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL AFTER `manufacturers_id` , ADD `contact_num` VARCHAR(255) COLLATE utf8_unicode_ci DEFAULT NULL AFTER `contact` - Erro é Table 'hmlglpi.glpi_certificates' doesn't exist
