### ISSUE TITLE
[9.2.1] Problem with pop-up ajax

### ISSUE THREAD

**Issue by mrspam** [glpi-project/glpi#3174]
Hi !

Problem with pop-up ajax with GLPI 9.2.1 (same problem with 9.2).
Not send and block in queue list.

Only with pop-up ajax, email sent correctly.

![sans titre](https://user-images.githubusercontent.com/26159277/32946319-72ad2ef6-cbb0-11e7-8adc-32ba3b69fa08.jpg)

**Comment by mrspam** [comment]
Log in php-error.log

2017-11-20 09:19:34 [430@xxx]
  From NotificationEventAjax::send() in /var/www/glpi/inc/notificationeventajax.class.php line 75 (0.001", 2.68Mio)
  NotificationEventAjax::send should not be called!
2017-11-20 09:19:34 [430@xxx]
  From NotificationEventAjax::send() in /var/www/glpi/inc/notificationeventajax.class.php line 75 (0.001", 2.68Mio)
  NotificationEventAjax::send should not be called!

My crontab 

*/1 * * * * /usr/bin/php7.0 /var/www/glpi/front/cron.php &>/dev/null

**Comment by mrspam** [comment]
Any idea please ?

**Comment by trasher** [comment]
This certainly is a duplicate of https://github.com/glpi-project/glpi/issues/2997; fixed as of 9.2.2

**Comment by ladenree76000** [comment]
in 9.2 "queuedmail" is renamed "queudnotification"
