### ISSUE TITLE
GLPI 9.2.1 upgrade fail

### ISSUE THREAD

**Issue by zawaye** [glpi-project/glpi#3184]
Dear GlPI Team,

I couldn't upgrade GLPI 9.2.1 from GLPI 9.1.2. When I try to upgrade, I got the following error message.

**9.2 migrate notifications templates - Error during the database query: INSERT INTO `glpi_notifications_notificationtemplates` (`notifications_id`, `mode`, `notificationtemplates_id`) SELECT `id`, `mode`, `notificationtemplates_id` FROM `glpi_notifications` - Error is Duplicate entry '77-mail-8' for key 'unicity'**

Please help me for smooth migration.

Thanks

**Comment by trasher** [comment]
You probably tried to upgrade previously. Drop database, restore your backup, and play migration again; this should be OK.

**Comment by zawaye** [comment]
Thanks Trasker. I can pass the previous message. But, I got different error message as below:

9.2 multiple alter in glpi_slas - Error during the database query: ALTER TABLE `glpi_slas` ADD INDEX `slms_id` (`slms_id`) - Error is Key column 'slms_id' doesn't exist in table

could you please help me again?

Thanks,

**Comment by zawaye** [comment]
Although I have changed the keyword INSERT to REPLACE that you highlighted, it couldn't solve that problem. I still got the below error message

**9.2 multiple alter in glpi_slas - Error during the database query: ALTER TABLE `glpi_slas` ADD INDEX `slms_id` (`slms_id`) - Error is Key column 'slms_id' doesn't exist in table**

Thanks

**Comment by tech62** [comment]
![glpi_error3](https://user-images.githubusercontent.com/16237642/33079277-82a70eb2-ced5-11e7-9d99-26400da7ddbb.JPG)
Same Problem
