### ISSUE TITLE
The simplified interface users can still change the ticket after a technician or group is assigned

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#3187]
After the simplified interface user opens a ticket. He is able to change some dropdowns like Type, Category, or even title and description. It would be ok if the ticket is not being processed by the tech team. Because the ticket is still in process of being analyzed and the tech team, probably, didn't get in touch with it.

But once the ticket is assigned to a technician or a group. It shouldn't be changed. At least the Type, category, title, and description should be fixed once the team started the attendance.

But users are yet in control of these fields, even after the assignments.

![image](https://user-images.githubusercontent.com/13874922/33023062-2e06ed6a-cdee-11e7-95b6-a28c353cdaf7.png)

GLPI 9.2.1
Installation mode: TARBALL

**Server**
 
Operating system: Linux ip-172-31-1-231 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64
PHP 5.6.30-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap,
	sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at prototipo.bavierati.com.br Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36
Server Software: (Debian)
	Server Version: 10.0.30-MariaDB-0+deb8u2
	Server SQL Mode: 
	Parameters: proto@localhost/prototipo
	Host info: Localhost via UNIX socket
	

- mysqli extension is installed
- ctype extension is installed
- fileinfo extension is installed
- json extension is installed
- mbstring extension is installed
- zlib extension is installed
- curl extension is installed
- gd extension is installed
- simplexml extension is installed
- xml extension is installed
- ldap extension is installed
- imap extension is installed
- Zend OPcache extension is installed
- APCu extension is installed
- xmlrpc extension is installed
- OK/var/www/html/prototipo/config : OK
- OK/var/www/html/prototipo/files : OK
- OK/var/www/html/prototipo/files/_dumps : OK
- OK/var/www/html/prototipo/files/_sessions : OK
- OK/var/www/html/prototipo/files/_cron : OK
- OK/var/www/html/prototipo/files/_graphs : OK
- OK/var/www/html/prototipo/files/_lock : OK
- OK/var/www/html/prototipo/files/_plugins : OK
- OK/var/www/html/prototipo/files/_tmp : OK
- OK/var/www/html/prototipo/files/_cache : OK
- OK/var/www/html/prototipo/files/_rss : OK
- OK/var/www/html/prototipo/files/_uploads : OK
- OK/var/www/html/prototipo/files/_pictures : OK
- OK/var/www/html/prototipo/files/_log : OK

**Libraries**

- htmLawed version 1.2.4 in (/var/www/html/prototipo/lib/htmlawed)
- phpCas version 1.3.5 in (/var/www/html/prototipo/vendor/jasig/phpcas/source)
- PHPMailer version 5.2.26 in (/var/www/html/prototipo/vendor/phpmailer/phpmailer)
- SimplePie version 1.5.1 in (/var/www/html/prototipo/vendor/simplepie/simplepie/library)
- TCPDF version 6.2.13 in (/var/www/html/prototipo/vendor/tecnickcom/tcpdf)
- michelf/php-markdown in (/var/www/html/prototipo/vendor/michelf/php-markdown/Michelf)
- true/punycode in (/var/www/html/prototipo/vendor/true/punycode/src)
- iacaml/autolink in (/var/www/html/prototipo/vendor/iamcal/lib_autolink)
- sabre/vobject in (/var/www/html/prototipo/vendor/sabre/vobject/lib)

**Comment by arthurrschaefer** [comment]
Actually,
They're able to change even the Impact and I don't have any option to deactivate this permission.

**Comment by arthurrschaefer** [comment]
Issue #2504 has the same situation. But on GLPI 9.1.6

**Comment by trasher** [comment]
Duplicates #2504
