### ISSUE TITLE
Close automatically linked requests

### ISSUE THREAD

**Issue by sferia82** [glpi-project/glpi#3191]
Is there any way to close automatically linked requests?
Thank you.

**Comment by ladenree76000** [comment]
there are differnts lin type between tickets

link
duplicate
son of  (since 9.2)
parent of (since 9.2)

duplicate should solve all tickets together then according to your setting, tickets might be closed.

**Comment by cedric-anne** [comment]
Hi,

Answer has been done a long time ago, so I close the issue.

Regards
