### ISSUE TITLE
Incorrect user in ticket with attachment from e-mail - 9.2.1

### ISSUE THREAD

**Issue by dilona** [glpi-project/glpi#3192]
Hello! 
I have upgraded my GLPI from 9.2 to 9.2.1
When create ticket with attachment by e-mail, attached files are associated to an incorrect user.
Sample 1.
 ![image](https://user-images.githubusercontent.com/31918974/33071561-11e8a47c-cecd-11e7-918f-70040cefe126.png)
Sampe 2.
 ![image](https://user-images.githubusercontent.com/31918974/33071621-4aaa00da-cecd-11e7-8186-8f9fe7a97648.png)
Software: GLPI 9.2.1, php7.0, mysql 5.7.2, Ubuntu 16.04
![image](https://user-images.githubusercontent.com/31918974/33071980-b3b38226-cece-11e7-92be-d8ef50263c5f.png)

A similar issue in #2516

**Comment by okvok** [comment]
[https://github.com/glpi-project/glpi/issues/3033](url)

**Comment by okvok** [comment]
Confirm. There are 2 variants of the bug:
1. Like in #3033 is still presenting.
2. In case of scheduled cron task - document's owner is empty. See screenshot:
![image](https://user-images.githubusercontent.com/20252855/33804944-ae6e5f42-ddc0-11e7-8de3-ca956f82b5fc.png)

**Comment by dilona** [comment]
In 9.2.2. problem not solved.
Processing ticket:
![image](https://user-images.githubusercontent.com/31918974/37080113-2751ca42-21f6-11e8-8488-4b65062a0c45.png)
Historical:
![image](https://user-images.githubusercontent.com/31918974/37080264-a896f316-21f6-11e8-8b72-d51371b108f4.png)
Software: GLPI 9.2.2, php7.0, mysql 5.7.2, Ubuntu 16.04:
![image](https://user-images.githubusercontent.com/31918974/37080586-dd9df482-21f7-11e8-9083-505a5cc5e064.png)

**Comment by cedric-anne** [comment]
Hi,

I do not reproduce on current state of 9.4/bugfixes branch. I guess issue has been fixed.

Regards
