### ISSUE TITLE
[9.2.1] difficult to re edit a problem task

### ISSUE THREAD

**Issue by mmallejac** [glpi-project/glpi#3193]
When editing an already existing problem task, some fields are out of the display if working in _Vertical split_ (other modes are ok).
My screen resolution is 1920x1080

Probably very similar to issue #3149 

![selection_002](https://user-images.githubusercontent.com/11666281/33079934-22493944-ced7-11e7-84b3-45afd96832ea.jpg)

**Comment by cedric-anne** [comment]
Hi,

In 9.4.0, "Tasks" tab has been dropped in favor of the "Processing Problem" tab. Task form is now fully displayed so problem is fixed.

![image](https://user-images.githubusercontent.com/33253653/54125731-112a7b00-4406-11e9-978f-41cee5ec22fe.png)

Regards
