### ISSUE TITLE
[9.2.1] Error while updating from 9.2 to 9.2.1

### ISSUE THREAD

**Issue by apeyrou** [glpi-project/glpi#3197]
Hello,
I've an Error while updating from 9.2 to 9.2.1

I've try many times with a truncate of all tables before restoring my backup.
I've try last commit of install files ... with the same error

![glpi1](https://user-images.githubusercontent.com/33878364/33094131-5a7b1260-ceff-11e7-9782-f35c5eb25b48.JPG)

in the sql_log
_ADD INDEX `time_to_own` (`time_to_own`) ,
CHANGE `slalevels_id` `ttr_slalevels_id` INT(11) NOT NULL DEFAULT '0'  
  Error: Unknown column 'due_date' in 'glpi_tickets'
  Backtrace :
  inc/dbmysql.class.php:215                          
  inc/migration.class.php:637                        DBmysql->queryOrDie()
  install/update_92_921.php:72                       Migration->migrationOneTable()
  inc/update.class.php:398                           update92to921()
  install/update.php:457                             Update->doUpdates()
  install/update.php:564                             doUpdateDb()_

In the update php form 92 to 921, i've found something strange

line 67:
  _if (!$DB->fieldExists('glpi_tickets', 'time_to_own')) {
      $migration->addField("glpi_tickets", "**time_to_own**", "datetime", ['after' => 'due_date']);
      $migration->addKey('glpi_tickets', 'time_to_own');_

but  line 237:

_if ($DB->fieldExists("glpi_tickets", "due_date")) {
      $migration->changeField('glpi_tickets', 'due_date', '**time_to_resolve**', 'datetime');
      $migration->migrationOneTable('glpi_tickets');
      $migration->dropKey('glpi_tickets', 'due_date');
      $migration->addKey('glpi_tickets', 'time_to_resolve');
   }_

   _//Change changes
   if ($DB->fieldExists("glpi_changes", "due_date")) {
      $migration->changeField('glpi_changes', 'due_date', '**time_to_resolve**', 'datetime');
      $migration->migrationOneTable('glpi_changes');
      $migration->dropKey('glpi_changes', 'due_date');
      $migration->addKey('glpi_changes', 'time_to_resolve');
   }

   //Problem changes
   if ($DB->fieldExists("glpi_problems", "due_date")) {
      $migration->changeField('glpi_problems', 'due_date', '**time_to_resolve**', 'datetime');
      $migration->migrationOneTable('glpi_problems');
      $migration->dropKey('glpi_problems', 'due_date');
      $migration->addKey('glpi_problems', 'time_to_resolve');_

regards,

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/3427#issuecomment-364856200
