### ISSUE TITLE
[9.2] Business criticality better than Business criticity

### ISSUE THREAD

**Issue by OscarBeiro** [glpi-project/glpi#3199]
On 9.2 and 9.2.1 there's this new Asset Management field: **Business _criticity_**.

Trying to get what it meaned, made a few searchs and apparently it is not correct.
http://www.wordreference.com/definition/criticality
http://www.wordreference.com/definition/criticity
![criticality-vs-criticity](https://user-images.githubusercontent.com/18396050/33121700-d7ab00a8-cf75-11e7-9fc8-8bc159f10691.png)

It seems more correct **Business criticality**

Maybe some native English speaker could confirm this point.

**Comment by AnaelMobilia** [comment]
Should be due to the use of "criticité" for criticality in French... ;-)
