### ISSUE TITLE
[0.90][Cyrillic] bad font in graph

### ISSUE THREAD

**Issue by SergeyDjam** [glpi-project/glpi#320]
Hello! 

cyrillic bad font in graph glpi
fix it:
glpi/inc/graphpalette.class.php

old string: protected $fontName = 'sans-serif';
new string: protected $fontName = 'dejavusans';

**Comment by lexx015** [comment]
Which os you are using? I heard that this happens with SUSE.
It works perfect with debian.

**Comment by SergeyDjam** [comment]
My OSes is CentOS, ROSA Server Linux.

**Comment by remicollet** [comment]
You don't have to change the code.
The used font can be selected in user preferences, and default value in configuration.

**Comment by SergeyDjam** [comment]
I don't find it in user preferences and default configuration

**Comment by yllen** [comment]
in user preferences you can change font for export PDF.
I put my glpi in Russian and in graphic i have cyrillic font
![graph](https://cloud.githubusercontent.com/assets/12936722/13358679/cfc1e384-dcb0-11e5-89bf-293992cebe05.jpg)

**Comment by orthagh** [comment]
User preferences is available on clicking on you login (top/right of the screen)
Defaults values in Setup > General.
