### ISSUE TITLE
Ukrainian localization problem 

### ISSUE THREAD

**Issue by ferdmanp** [glpi-project/glpi#3200]
With feature "Use rich text for helpdesk" enabled, ran into following issue. When using Ukrainian language as interface language ("Українська" in My Settings>Personalization>Language dropdown)
1) "Description" field in ticket form not showing TinyMCE toolbar, and shows HTML tags between words
2) "Linked tickets" not showing dropdown for ticket selection.

**Comment by flegastelois** [comment]
I confirm the 1 bug, we have a javascript error:

![image](https://user-images.githubusercontent.com/470612/33129585-a8eac684-cf90-11e7-8bde-92e2c1e51e1f.png)

Because of "single quote" in this translation string:
https://github.com/glpi-project/glpi/blob/b37964435abc1cb5565729a7727456b0e238c55b/locales/uk_UA.po#L11629

The second bug stems from the first.

**Comment by AnaelMobilia** [comment]
Hello,

I have fix the issue on transifex both for 9.2 and 9.3 branches.
The thing is to use html entities on this specific case (we cannot use \ to escape the char).

So ' become `&#x27;` and all's done.

I've tested the compilation of the mo file 👍 
![image](https://user-images.githubusercontent.com/6187125/33244791-d1b8735c-d2fd-11e7-890c-507a08122468.png)

@trasher to be closed, this issue need an update of the mo / po files on the glpi repository.
I dunno if I can made this ?

Regards,
Anael

**Comment by trasher** [comment]
Thanks to get locale fixed; but I guess this is still an issue; GLPI should take care of escaping for javascript output

**Comment by AnaelMobilia** [comment]
@trasher GLPI use the compiled mo file.
Have we a way to get the value before it's put on JS ?

If no, we could add specific tules on the pl script to "protect" these type of char ?

Regards,
Anael

**Comment by trasher** [comment]
@AnaelMobilia basically, GLPI uses `__()` method for translations, and `__s()` when some escaping is required. I guess the first has been used instead of the second somewhere here.
