### ISSUE TITLE
Search in softwares dropdown uses an OR for spaces

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#3201]
Since fix of #1838

It's pretty problematic for softwares.
Now a space in sentence add a lot of results when you had an exact one before
![image](https://user-images.githubusercontent.com/418844/33176819-b0ec0016-d060-11e7-81f6-ed5cf7bbb6b2.png)

A possible workaround is using `%`:
![image](https://user-images.githubusercontent.com/418844/33176792-983891c4-d060-11e7-92a1-1bb71dd2cee2.png)

But it's not very straightforward

ping @trasher

**Comment by trasher** [comment]
I do not see right now how to get this one fixed without removing fix for #1838... :/

**Comment by augustoferronato** [comment]
Some news about? For the category in ticket page, the same problem with spaces
