### ISSUE TITLE
delete users

### ISSUE THREAD

**Issue by nbrandao** [glpi-project/glpi#3203]
Good afternoon,
I was cleaning some users and I was able to delete users with linked tickets closed, leaving them without an applicant. Is this behavior normal or it should not be possible to delete users with tickets created?

I would like to know if it is possible to change the applicant of several tickets, closed and not closed, to assign them to a specific user.
Thank you
Nuno

**Comment by trasher** [comment]
You can drop a user with linked items, this is not a problem.
As for mass update tickets actors, see https://github.com/glpi-project/glpi/issues/1262
