### ISSUE TITLE
[9.3-dev] many undefined index

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#3207]
Hi,

On 9.3 dev, many undefined index PHP warning

On index.php
  - PHP Notice: Undefined index: login_remember_time in C:\xampp\htdocs\glpi\inc\auth.class.php at line 1116
  - PHP Notice: Undefined index: login_remember_time in C:\xampp\htdocs\glpi\index.php at line 135
  - PHP Notice: Undefined index: notifications_mailing in C:\xampp\htdocs\glpi\index.php at line 147

On front/ticket.form.php
  - PHP Notice: Undefined index: notifications_mailing in C:\xampp\htdocs\glpi\inc\commonitilobject.class.php at line 3558
  - PHP Notice: Undefined index: notifications_mailing in C:\xampp\htdocs\glpi\inc\commonitilobject.class.php at line 3641
  - PHP Notice: Undefined index: notifications_mailing in C:\xampp\htdocs\glpi\inc\commonitilobject.class.php at line 3682
  - PHP Notice: Undefined index: notifications_mailing in C:\xampp\htdocs\glpi\inc\commonitilobject.class.php at line 3730

On ajax/telemetry.php
  - PHP Notice: Undefined index: use_notifications in C:\xampp\htdocs\glpi\inc\telemetry.class.php at line 96

Regards,
Anael

**Comment by trasher** [comment]
Since 9.3 did not yet change much; I guess those ones also affects 9.2.1

**Comment by trasher** [comment]
Sounds like an upgrade issue. Make sure `login_remember_time` and `notifications_mailing` do exists in glpi_configs table.

**Comment by trasher** [comment]
No feedback, closing
