### ISSUE TITLE
eMail attached into eMail are not uploaded via mail collector

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#321]
Hello,
This is an old issue (already existing in 0.83):
When sending an email to the mail collector with Outlook and attaching into this email another email, then the attached email is not uploaded as any other documents would be.
The reason is Outlook (or MSExchange doesn't provide any FILENAME for the MIME part of the attached email like it would do for any other documents).
As the mail collector will ignore empty FILENAME, then the MIME part is not imported.

I'm going to post a fix for that in 0.85 and 0.90 releases.

regards,
Tomolimo

**Comment by orthagh** [comment]
I closed 0.85/bugfixes pr.

Do you want a 0.90.2 milestone or 0.91 ?
For 0.90, i need a corresponding pr.

**Comment by tomolimo** [comment]
I'm going to do it tomorrow

**Comment by orthagh** [comment]
many thanks
