### ISSUE TITLE
PHP Array to string conversion in History tab

### ISSUE THREAD

**Issue by TristanDizetCL** [glpi-project/glpi#3214]
Hi,

GLPI 9.2.1 running here.

The error happened in the Hystory tab of an item in the inventory.
The update field after changing the user of the item looks like this : 
"Changing from  (0) to Array"

In debug mod it says the error is in GLPI_DIR/inc/log.cladd/php line 693

After some digging, the source of the error seems to be the way we created our users.
We use this pattern : 
ID -> John Doe
FirstName -> John
LastName -> Doe

In the table "logs" the new_value is set as "John Doe"

And if we change the ID of the user to be John.Doe and the new_value field in the logs table by "John.Doe". It work great, printing "Changing from  (0) to John Doe (USER_ID)"

Is that a bug or just the way we create our user that's wrong ?

We have a lot of users and updating all user's id and all new_value/old_value in logs table will take a very long time. Is there no other way ?

I stay available for further informations,
Tristan

**Comment by hackman61** [comment]
Hi,
I have the same problem with GLPI  9.3.3 , have you solved your issue  yourself ? 

![image](https://user-images.githubusercontent.com/1253901/51733556-f1234000-2081-11e9-8e0c-3eca201a859b.png)

Thank you !

**Comment by trasher** [comment]
You have to provide a full error stack trace (switching to debug mode may help). Also, please test on 9.4rc2 if this issue still exists.

**Comment by hackman61** [comment]
Oh damn that's it ! I have replaced all space like that : 

update glpi_users set name = replace(name, ' ', '_');

And now everything is fine !

Thank you !
