### ISSUE TITLE
Problem for exclude tasks of project in glpi

### ISSUE THREAD

**Issue by leandrotenorio** [glpi-project/glpi#3215]
It is doesnt possible exclude taks of project in new version, someone already had the same problem?

![screenshot_4](https://user-images.githubusercontent.com/8218579/33318784-12d38964-d423-11e7-9a34-d2b2a5b7c0a0.png)

**Comment by leandrotenorio** [comment]
Any answers?

**Comment by Armin83** [comment]
Sorry, I can only read your english text and i don't understand your problem.

(It is posible to delete tasks.)
![2018-09-07 10_42_58-window](https://user-images.githubusercontent.com/19192087/45208450-e4e14680-b28a-11e8-88cd-85798a6e3c9d.png)
