### ISSUE TITLE
Computer disk and antivirus

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3218]
No rights to update computer - Right to read it.

On antivirus and disk tabs i can see disk and antivirus  with a link to open the object.
When i click on link => nothing displayes

**Comment by AnaelMobilia** [comment]
Hi @yllen 
This issue appears to be solved by #3219 .
If done, this could be closed ;-)

Regards,
Anael

**Comment by yllen** [comment]
@AnaelMobilia
yes #3219 is the PR to fix this issue but i don't know id the reviewer do the cherry-pick for newer version.
So i prefer to let it close this issue

**Comment by trasher** [comment]
I've checked, the commit has been cherry-picker on 9.2/bf and master branches. Thank you :)
