### ISSUE TITLE
[0.90.1] Redirect in loop on active_entity URL

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#322]
Hi,

When i try to access to an entity with the following URL : 

> http://server/glpi/front/central.php?active_entity=2

GLPI seems to redirect loop :

> http://server/glpi/front/central.php?redirect=%2Ffront%2Fcentral.php%3Factive_entity%3D2
> http://server/glpi/front/central.php?active_entity=2
> http://server/glpi/front/central.php?redirect=%2Ffront%2Fcentral.php%3Factive_entity%3D2
> http://server/glpi/front/central.php?active_entity=2

etc...

The Single Sign On is enable on GLPI with REMOTE_USER parameter : 
![SSO](http://www.world-lolo.com/images/uploads/image.num1450097589.of.world-lolo.com.png)

Have you an idea for this issue ?

Thanks to you,

++

**Comment by barbuslex** [comment]
In /front/central.php.
If i replace : 
```
if (Session::changeActiveEntities($_GET["active_entity"],$_GET["is_recursive"])) {
      if (($_GET["active_entity"] == $_SESSION["glpiactive_entity"])
          && isset($_SERVER['HTTP_REFERER'])) {
         Html::redirect(preg_replace("/entities_id.*/","",$_SERVER['HTTP_REFERER']));
      }
   }
```

By this : 
```
if (Session::changeActiveEntities($_GET["active_entity"],$_GET["is_recursive"])) {
      //if (($_GET["active_entity"] == $_SESSION["glpiactive_entity"])
      //    && isset($_SERVER['HTTP_REFERER'])) {
      //   Html::redirect(preg_replace("/entities_id.*/","",$_SERVER['HTTP_REFERER']));
      //}
 }
```

GLPI stop to redirect in loop.

Can you explain me is what these lines ?

Thanks in advance

**Comment by barbuslex** [comment]
up ?

**Comment by yllen** [comment]
if (($_GET["active_entity"] == $_SESSION["glpiactive_entity"])

it's a control to check if the connected user has right to read the entity looking for

**Comment by barbuslex** [comment]
Yeah, but in this case, if we pass the active_entity parameter in the url, glpi redirect in loop.
If we comment theses lines the redirect work's perfectly.
