### ISSUE TITLE
Cannot delete a project's task

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#3224]
Tested on GLPI 9.2 (but it should be present in previous releases).
It's impossible to delete a project task, as there's no button for it.

**Comment by thiagopassamani** [comment]
Thanks!

**Comment by barbuslex** [comment]
+1

**Comment by brunbay** [comment]
Hello, have you got an issue for this ?
Thanks.

**Comment by trasher** [comment]
Issue introduced in fe496ed7e5976b5aaf2c30eb51ac536d0e6e7ed2
