### ISSUE TITLE
Change Status Waiting to Processing (technical follow-up)

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#3228]
Question.

How can I control that a waiting ticket does not change to "in progress" when tracking?

It happens that if I have two roles (requesting user = help desk interface, assigned technician = standard interface) and they belong to a group called "Administrative" (Administrative Group can only be an applicant, Not assigned).

If the ticket is waiting and the technician tracks the ticket, GLPI places it "in progress".

This does not happen if the actors do not belong to the same group (example: Administrative). What should I configure so that only the ticket applicant can change it to the current one even if they belong to the same requesting group?

Any ideas about it

**Comment by pVesian** [comment]
Hi @virginiacorrea, what do you mean by "track a ticket"? Setting the technician as "Watcher"? What's your GLPI version and plugins? Thanks.

**Comment by trasher** [comment]
No feedback, closing
