### ISSUE TITLE
IIS Config for API REST

### ISSUE THREAD

**Issue by Drumhazzard** [glpi-project/glpi#3236]
Its necessary make any special configuration in IIS for the API works?

We try make simple operations but our IIS take the / like path, not as arguments o parameters of apirest.php

When we try to make a "PUT", IIS return Error 404

```
<div class="content-container">
  <h3>HTTP Error 404.0 - Not Found</h3>
  <h4>The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.</h4>
</div>
```
```
<tr class="alt"><th>Requested URL</th><td>&nbsp;&nbsp;&nbsp;http://glpi2018:80/apirest.php/Ticket/80/</td></tr>
<tr><th>Physical Path</th><td>&nbsp;&nbsp;&nbsp;D:\webs\glpi0.921\apirest.php\Ticket\80\</td></tr>
<tr class="alt"><th>Logon Method</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
<tr><th>Logon User</th><td>&nbsp;&nbsp;&nbsp;Anonymous</td></tr>
```
Someone with GLPI in IIS that could give us some light about this?

**Comment by tomolimo** [comment]
Hello,
By default, the PUT verb is not active.
Then I advise to authorize all verbs (as you may also need the DELETE),
Regards,
Tomolimo

**Comment by Drumhazzard** [comment]
Thanks a Lot!

I configured the Handler Mapping and the Request Filtering, to add the verbs, but I got the same result.

It's necessary any "URL Rewrite Rule"?

**Comment by tomolimo** [comment]
Yes and No, it is mandatory when the result code is HTTP 201, then you must have some rewrite rules, as in this case IIS returns HTML with redirection message. I'll give you this rewrite rules when you'll get 201 return codes.
But if you still have HTTP 404, then it's something else.
You may use SoapUI to do tests of the API.
Regards,
Tomolimo

**Comment by Drumhazzard** [comment]
Thanks Tomolimo! Now, seems works, but I have new error:

["ERROR_GLPI_UPDATE","You don't have permission to perform this action."]

**Comment by tomolimo** [comment]
What did you do to solve this issue?

**Comment by Drumhazzard** [comment]
As I was make some test with rewrite rules, I add one for call api.php as apirest.php, but later I delete this rule but I not change my php, and error 404 still happened.

With add the VERBs in IIS, all works fine!

The ["ERROR_GLPI_UPDATE","You don't have permission to perform this action."] was because I has the Self-Service profile as default, I changed this for Tecnician or Super-Admin and all works fine too.

Thanks a lot for your support! There are less documentation from GLPI installations over windows and IIS and your support has been determinant for solve my issue.

**Comment by Drumhazzard** [comment]
Solved!
