### ISSUE TITLE
[9.1.6] ipnetwork - bad name 

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#3237]
Hello,

On the ipnetwork.php file : display of all ip networks.

The column name have a strange behavior : 
![image](https://user-images.githubusercontent.com/6187125/33519404-029f6820-d7a6-11e7-8410-340d331b3300.png)

It include a begin IP for the range which is inconsistent with the actual range displayed...
Eg : 192.168.0.0/16 -> 192.168.192.0/24 will include the 192.168.191.0/24 network.

In reality, the calculation is correct (192.168.192.0/24 include only 192.168.192.0 - 192.168.192.255 IP address), but the title isn't correct.

Regards

**Comment by AnaelMobilia** [comment]
Issue still active.

**Comment by AnaelMobilia** [comment]
.

**Comment by AnaelMobilia** [comment]
.

**Comment by cconard96** [comment]
I don't use an inventory agent in my development environment and I don't really know this part of GLPI.
Can you share the values of the form fields for one of the IP networks with this issue and/or provide steps to recreate the issue?
