### ISSUE TITLE
[9.2.1] Bug with image in ticket description

### ISSUE THREAD

**Issue by usrqmor** [glpi-project/glpi#3239]
Hello,

I repost this problem that I post on version 9.2 on this post : #3235
I update my GLPI Test in 9.2.1 and the bug with pictures in description is still here.
![image](https://user-images.githubusercontent.com/17316903/33542388-2711cf1c-d8d3-11e7-8663-e03ce329be9b.png)

I check the log file and I get any error. I found nothing too in debug mode.

I try a small picture and with standard interface, I see the picture in description but in post only, the requester don't see it.
The big picture can't be see in description even if you're in post only or a profile with standard interface.

Can you help me ?
Thank you.

**Comment by usrqmor** [comment]
Hi,

I do another test and it seems that GLPI try to add picture in the documents section. But when I checked the link, I got : "File not found".
The picture's link is http://glpitest/front/document.send.php?docid=9889&tickets_id=4283. 
The document with id 9889 is good and when I look at the file, I get "File not found".
It seems the drag and drop has a small problem to add picture in GLPI's documents.

I look at the log and i have this : 

> 2017-12-08 09:42:16 [@GLPITEST]
>   *** PHP Warning(2): ldap_bind(): Unable to bind to server: Invalid credentials
>   Backtrace :
>   :
>   inc/auth.class.php:234                             ldap_bind()
>   inc/authldap.class.php:2653                        Auth->connection_ldap()
>   inc/authldap.class.php:2717                        AuthLDAP::ldapAuth()
>   inc/auth.class.php:706                             AuthLDAP::tryLdapAuth()
>   front/login.php:79                                 Auth->Login()
> 2017-12-08 09:42:16 [@GLPITEST]
>   *** PHP Notice(8): Undefined index: glpiactiveprofile
>   Backtrace :
>   inc/html.class.php:1198
>   inc/html.class.php:1769                            Html::includeHeader()
>   front/login.php:83                                 Html::nullHeader()
> 2017-12-08 09:42:26 [@GLPITEST]
>   *** PHP Notice(8): Undefined index: glpiactiveprofile
>   Backtrace :
>   inc/html.class.php:1198
>   inc/html.class.php:1769                            Html::includeHeader()
>   front/login.php:83                                 Html::nullHeader()
> 2017-12-08 09:42:55 [420@GLPITEST]
>   *** PHP Notice(8): Undefined index: entities_id
>   Backtrace :
>   plugins/news/inc/alert.class.php:498
>   :                                                  PluginNewsAlert::preItemForm()
>   inc/plugin.class.php:1271                          call_user_func()
>   inc/ticket.class.php:3899                          Plugin::doHook()
>   front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()
> 2017-12-08 09:43:19 [414@GLPITEST]
>   *** PHP Notice(8): Undefined index: entities_id
>   Backtrace :
>   plugins/news/inc/alert.class.php:498
>   :                                                  PluginNewsAlert::preItemForm()
>   inc/plugin.class.php:1271                          call_user_func()
>   inc/ticket.class.php:3899                          Plugin::doHook()
>   front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()
> 2017-12-08 09:43:25 [414@GLPITEST]
>   *** PHP Notice(8): Undefined index: entities_id
>   Backtrace :
>   plugins/news/inc/alert.class.php:498
>   :                                                  PluginNewsAlert::preItemForm()
>   inc/plugin.class.php:1271                          call_user_func()
>   inc/ticket.class.php:3899                          Plugin::doHook()
>   front/tracking.injector.php:97                     Ticket->showFormHelpdesk()
> 2017-12-08 09:44:08 [414@GLPITEST]
>   *** PHP Notice(8): Undefined index: entities_id
>   Backtrace :
>   plugins/news/inc/alert.class.php:498
>   :                                                  PluginNewsAlert::preItemForm()
>   inc/plugin.class.php:1271                          call_user_func()
>   inc/ticket.class.php:3899                          Plugin::doHook()
>   front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()
> 2017-12-08 09:44:27 [414@GLPITEST]
>   *** PHP Notice(8): Undefined index: entities_id
>   Backtrace :
>   plugins/news/inc/alert.class.php:498
>   :                                                  PluginNewsAlert::preItemForm()
>   inc/plugin.class.php:1271                          call_user_func()
>   inc/ticket.class.php:3899                          Plugin::doHook()
>   front/tracking.injector.php:97                     Ticket->showFormHelpdesk()
> 2017-12-08 09:44:56 [414@GLPITEST]
>   *** PHP Notice(8): Undefined index: entities_id
>   Backtrace :
>   plugins/news/inc/alert.class.php:498
>   :                                                  PluginNewsAlert::preItemForm()
>   inc/plugin.class.php:1271                          call_user_func()
>   inc/ticket.class.php:3899                          Plugin::doHook()
>   front/helpdesk.public.php:98                       Ticket->showFormHelpdesk()
> 
> 

I hope you can help me.
thanks

**Comment by okvok** [comment]
Confirm. It's still a BUG in 9.2.1

**Comment by ferdmanp** [comment]
Please, take a look at my solution in #3240 . Possibly, you have the same issue

**Comment by usrqmor** [comment]
Hello @ferdmanp,
It works for me in 9.2.1. Thanks for the solution.

**Comment by trasher** [comment]
Duplicates #3653
