### ISSUE TITLE
[9.2.1] Ticket from e-mail not shows inserted pictures

### ISSUE THREAD

**Issue by ferdmanp** [glpi-project/glpi#3240]
When creating ticket via e-mail in HTML format with pictures injected as part of body (not as attachment),I've ran into following issue.
Ticket created succesffully, document from picture created succesfully as well. But document is not linked to ticket. 
So picture not showing in "Description" field and under "Documents" tab.
When creating ticket with same content (text and picture in body) from GLPI UI (rich interface enabled), everything works fine.
When picture is a regular attachment in e-mail, everything works fine as well.
I found difference in DB table "glpi_tickets" in field "content" for "bad" and " good " cases.

"Bad" case : &lt;p&gt; &lt;/p&gt;&lt;p&gt;&lt;a href="http://mydomain.com/var/www/html/front/document.send.php?docid=18601" target="_blank"&gt;&lt;img src="http://mydomain.com/var/www/html/front/document.send.php?docid=18601" alt="12fed69f-86cc5719-5a21bc055334a6.67245345" width="1626" height="1017" /&gt;&lt;/a&gt;&lt;/p&gt;&lt;div class="moz-signature"&gt;-- &lt;br /&gt; С уважением,&lt;br /&gt; Павел Фердман &lt;br /&gt; Департамент IT &lt;br /&gt; вн. тел. 111 &lt;br /&gt; &lt;a href="mailto:p.ferdman@mydomain.com"&gt;p.ferdman[at]mydomain.com&lt;/a&gt;&lt;/div&gt;

"Good" case : &lt;p&gt;&nbsp;&lt;/p&gt;&lt;p&gt;&nbsp;&lt;/p&gt;&lt;p&gt;&nbsp;&lt;a href=&quot;/front/document.send.php?docid=18604&quot; target=&quot;_blank&quot;&gt;&lt;img alt=&quot;12fed69f-86cc5719-5a21ca8568a635.69547833&quot; height=&quot;155&quot; width=&quot;247.81710914454274&quot; src=&quot;/front/document.send.php?docid=18604&quot; /&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&nbsp;&lt;/p&gt;

As you can see, in "bad" case glpi stores absolute path for document form, and in "good" case path is relative. 
Hope this helps.

//-----
System info
`[code]
 
GLPI 9.2.1 ( => /var/www/html)
Installation mode: TARBALL

Server

 
Operating system: Linux mydomain.com 3.18.34-20.el7.x86_64 #1 SMP Fri May 27 12:12:30 UTC 2016 x86_64
PHP 5.6.28 apache2handler (Core, PDO, PDO_Firebird, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2,
	calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, interbase, json, ldap,
	libxml, mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, session, shmop, soap, sockets, sqlite3, standard,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.28 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0
Server Software: MariaDB Server
	Server Version: 5.5.52-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
APCu extension is not present
OK/var/www/html/config : OK
OK/var/www/html/files : OK
OK/var/www/html/files/_dumps : OK
OK/var/www/html/files/_sessions : OK
OK/var/www/html/files/_cron : OK
OK/var/www/html/files/_graphs : OK
OK/var/www/html/files/_lock : OK
OK/var/www/html/files/_plugins : OK
OK/var/www/html/files/_tmp : OK
OK/var/www/html/files/_cache : OK
OK/var/www/html/files/_rss : OK
OK/var/www/html/files/_uploads : OK
OK/var/www/html/files/_pictures : OK
OK/var/www/html/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.
OKSELinux mode is Disabled

Libraries

 
htmLawed version 1.2.4 in (/var/www/html/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/html/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/var/www/html/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/var/www/html/vendor/simplepie/simplepie/library)
TCPDF version 6.2.13 in (/var/www/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)

LDAP directories

SQL replicas

 
Not active

Notifications

 
Way of sending emails: PHP

Mails receivers

 
Name: 'helpdesk@mydomain.com' Active: Yes
	Server: '{192.168.0.15/pop}' Login: 'helpdesk' Password: Yes
Name: 'glpi-reply@mydomain.com' Active: Yes
	Server: '{192.168.0.15/pop}' Login: 'glpi-reply' Password: Yes

Plugins list

 
	mailkb               Name: Email KB                       Version: 1.2.0      State: Not activated
	escalade             Name: Escalation                     Version: 0.90-1.2   State: Not installed
	datainjection        Name: File injection                 Version: 2.4.2      State: Not activated
	fusioninventory      Name: FusionInventory                Version: 0.90+1.3   State: Not installed
	mydashboard          Name: My Dashboard                   Version: 1.2.1      State: Not installed
	order                Name: Orders management              Version: 0.85+1.0   State: Not installed
	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Enabled
	webnotifications     Name: Web Notifications              Version: 1.0.4      State: Enabled
	webservices          Name: Web Services                   Version: 1.6.0      State: Not installed
	fields               Name: Дополнительные поля    Version: 1.6.1      State: Not installed
	moreticket           Name: Еще заявка                     Version: 1.2.3      State: Not installed
	anclink              Name: Объекты АНЦ                    Version: 7.1        State: Enabled
	dashboard            Name: Панель отчетов              Version: 0.8.8      State: Enabled
	projet               Name: Проекты                        Version: 1.5.0      State: Not installed
	formcreator          Name: Формы                          Version: 0.90-1.3.4 State: Enabled
	resources            Name: Человеческие Ресурсы  Version: 2.1.0      State: Not installed

[/code] `

**Comment by Mo-GH** [comment]
Yes, its Error i have so Changed:
i replaced this Function : 


			  // replace img[src] and a[href] by cid:tag in html content
    /*   foreach ($inline_docs as $docID => $tag) {
               $current->fields['body_html'] = preg_replace([
                     '/src=["\'].*document\.send\.php\?docid='.$docID.'["\']/',
                     '/href=["\'].*document\.send\.php\?docid='.$docID.'["\']/',
                  ], [
                     "src=\"cid:$tag\"",
                     "href='".$CFG_GLPI['url_base']."/front/document.send.php?docid=$docID'",
                  ],
                  $current->fields['body_html']);
            }
			*/

with this:

 foreach ($inline_docs as $docID => $tag) {
               $current->fields['body_html'] = str_replace( array('src="/front/document.send.php?docid='.$docID,'href="/front/document.send.php?docid='),array('src="cid:'.$tag,'href="http://enginetickets.oktalite.de/front/document.send.php?docid='), $current->fields['body_html']);
			                            }

**Comment by Mo-GH** [comment]
But the first photo come as Thumbnail !! :( 
i need Help too in the same Problem

**Comment by ppenin** [comment]
i have the same issue with 9.2.1 version.
Furthermore, automatic tasks mailgate and queuednotification remain running when a mail in HTML format with pictures injected as part of body is collected.

**Comment by Mo-GH** [comment]
Any new solutions Please ???

**Comment by ppenin** [comment]
Problem #3284  solved with chmod -R 775 /var/lib/glpi/files and change in html.class.php line 5472

                 // Replace tags by image in textarea
                  if ($addLink) {
                     $out .= '<a href="/glpi/front/document.send.php?docid='.$id.
                             '" target="_blank"><img alt="'.$image['tag'].
                             '" height="'.$height.'" width="'.$width.
                             '" src="/glpi/front/document.send.php?docid='.$id.'" /></a>';
                  } else {
                     $out .= '<img alt="'.$image['tag'].
                             '" height="'.$height.'" width="'.$width.
                             '" src="/glpi/front/document.send.php?docid='.$id.'" />';
                  }

**Comment by ferdmanp** [comment]
It seems, solution depends on server configuration. Variable $CFG_GLPI['root_doc'] contains local file path to storage, and $CFG_GLPI['url_base'] allows to create correct link to image file.
In my case this code change  in html.class.php (line 5472) did the trick :
 ```
//Replace tags by image in textarea
	$loc_cfg_base=$CFG_GLPI['root_doc'];
	if(isset($CFG_GLPI['url_base'])){
		$loc_cfg_base=$CFG_GLPI['url_base'];
	}				
	if ($addLink) {
		$out .= '<a href="'.$loc_cfg_base.
				'/front/document.send.php?docid='.$id.
				'" target="_blank"><img alt="'.$image['tag'].
				'" height="'.$height.'" width="'.$width.
				'" src="'.$loc_cfg_base.
				'/front/document.send.php?docid='.$id.'" /></a>';
			} else {
		$out .= '<img alt="'.$image['tag'].
				'" height="'.$height.'" width="'.$width.
				'" src="'.$loc_cfg_base.
				'/front/document.send.php?docid='.$id.'" />';
			}

**Comment by ppenin** [comment]
your code change works well. Do you have issues with automatic tasks mailgate or/and queuednotification staying running when the collector try to create a new ticket ? it happens with each new mail and image embedded in the body (see ticket #3494 ).
it had never happened before with version 9.1.9 and earlier.

**Comment by trasher** [comment]
Duplicates #3653
