### ISSUE TITLE
GLPI 9.2.1 and inventories from fusioninventory

### ISSUE THREAD

**Issue by moobyfr** [glpi-project/glpi#3251]
I've updated from 9.2 to 9.2.1 and I am using fusioninventory for getting inventory (but I'm not sure the bug is related to glpi or fusion)
Since this update, the load on the mysql server raised from 0.02 to 20. there are a lot of requests on the mysql server, putting load, when the computers are reporting the inventory to the glpi server (fusioninventory for glpi,latest version: 9.2+1.0 )
According to the status of the mysql server, all requests are on the table ``glpi_softwareversions``,  most on waiting for a lock on the table.

GLPI is mostly used for inventory only, ~1100 units. the table ``glpi_softwareversions`` has ~1200000 entries
There is no related errors in the logs

EDIT:
Sorting out usuals queries from the mysql server, I get the same query 150 time:
```
SELECT DISTINCT `glpi_computers_softwareversions`.`softwareversions_id`
                   FROM  `glpi_computers_softwareversions`
                   WHERE `glpi_computers_softwareversions`.`softwareversions_id`
                     NOT IN (SELECT id FROM `glpi_softwareversions`)
```
which is rather heavy (12s per request)

**Comment by moobyfr** [comment]
I've solved the current issue by removing all entries in the tables glpi_software*, and stoping inventory on software.
As all computers were moving from one entity to another one, this was trying to move all software too.

**Comment by trasher** [comment]
There were issues on FI plugin with software updates; this was not related to GLPI (not sure if that was fixed; try with latest plugin RC).
