### ISSUE TITLE
Sql error on 9.2.1 before update GLPI since 0.84.2

### ISSUE THREAD

**Issue by cjmorenor** [glpi-project/glpi#3257]
Hi;
Please we need help us.

We have an error when we update GLPI 0.84.2 until 9.2.1. This error is:

*** MySQL query error:
  SQL: SELECT `glpi_itilcategories`.* 
             FROM `glpi_itilcategories`
             
             WHERE 1  AND `is_helpdeskvisible`='1' AND `is_incident`='1'  AND  ( `glpi_itilcategories`.`entities_id` = '12'  OR (`glpi_itilcategories`.`is_recursive`='1' AND `glpi_itilcategories`.`entities_id` IN ('0','10')) ) 
             ORDER BY `glpi_itilcategories`.`entities_id`,  `glpi_itilcategories`.`completename`
             LIMIT -1,1
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-1,1' at line 6
  Backtrace :
  ajax\getDropdownValue.php:295   

*** MySQL query error:
  SQL: SELECT `glpi_olas`.* 
                   FROM `glpi_olas`
                   
                   WHERE 1  AND `glpi_olas`.`type` = '0' AND ( `glpi_olas`.`entities_id` IN ('12', '16')  OR (`glpi_olas`.`is_recursive`='1' AND `glpi_olas`.`entities_id` IN ('0','10')) )  ORDER BY `glpi_olas`.`entities_id`, `glpi_olas`.`name`
                 LIMIT -1,1
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-1,1' at line 5
  Backtrace :
  ajax\getDropdownValue.php:588     

Please, any idea?

Thank you...

**Comment by AnaelMobilia** [comment]
@trasher I check on the [source code of the release](https://github.com/glpi-project/glpi/blob/3a7c5969c0534d0b5bf27fef9c4d96f56147ae66/ajax/getDropdownValue.php#L119)

Cause of the problem : 
>  LIMIT -1,1

Mysql Doc 5.7 :
> The LIMIT clause can be used to constrain the number of rows returned by the SELECT statement. LIMIT takes one or two numeric arguments, which must both be nonnegative integer constants[...]

What will be the better, on the GLPI minds : 
  - Add a quick check on line 125 to "fix" this case (if $start <1, $start = 1)
  - Try to reproduce and find the root cause
?

Regards,
Anael
