### ISSUE TITLE
Weird characters on tickets created via mail receiver

### ISSUE THREAD

**Issue by ensonb** [glpi-project/glpi#3258]
Righ After updating from 9.1.4 to 9.2.1 im getting some weird "n" letters at the 
end and in each line breaks of the ticket 

![selection_037](https://user-images.githubusercontent.com/2094732/33685451-a0ee095e-da9f-11e7-9abb-2aa7131c108c.png)

## My setup 

GLPI 9.2.1 (/glpi => C:\xamppx\htdocs\glpi) Installation mode: TARBALL
--
Operating system: Windows NT APPSERVER 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586 PHP 5.6.14 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, libxml, mbstring, 	mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, sockets, sqlite3, standard, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="300" memory_limit="720M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14 (Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.14 Server at 	10.254.20.14 Port 81) 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.5.16 	Server SQL Mode:  	Parameters: root@localhost/glpigalores 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed ldap extension is not present C:\xamppx\htdocs\glpi/config : OK C:\xamppx\htdocs\glpi/files : OK C:\xamppx\htdocs\glpi/files/_dumps : OK C:\xamppx\htdocs\glpi/files/_sessions : OK C:\xamppx\htdocs\glpi/files/_cron : OK C:\xamppx\htdocs\glpi/files/_graphs : OK C:\xamppx\htdocs\glpi/files/_lock : OK C:\xamppx\htdocs\glpi/files/_plugins : OK C:\xamppx\htdocs\glpi/files/_tmp : OK C:\xamppx\htdocs\glpi/files/_cache : OK C:\xamppx\htdocs\glpi/files/_rss : OK C:\xamppx\htdocs\glpi/files/_uploads : OK C:\xamppx\htdocs\glpi/files/_pictures : OK C:\xamppx\htdocs\glpi/files/_log : OK

htmLawed version 1.2.4 in (C:\xamppx\htdocs\glpi\lib\htmlawed) phpCas version 1.3.5 in (C:\xamppx\htdocs\glpi\vendor\jasig\phpcas\source) PHPMailer version 5.2.26 in (C:\xamppx\htdocs\glpi\vendor\phpmailer\phpmailer) SimplePie version 1.5.1 in (C:\xamppx\htdocs\glpi\vendor\simplepie\simplepie\library) TCPDF version 6.2.13 in (C:\xamppx\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\xamppx\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\xamppx\htdocs\glpi\vendor\true\punycode\src) iacaml/autolink in (C:\xamppx\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\xamppx\htdocs\glpi\vendor\sabre\vobject\lib)

Not active

Way of sending emails: SMTP+SSL (xxxxxxxxx@smtp.gmail.com)

Name: 'xxxx@xxxx.com' Active: Yes 	Server: '{pop.gmail.com:995/pop/ssl/novalidate-cert}' Login: 'xxxx@xxxxx.com' Password: Yes

dashboard            Name: Dashboard                      Version: 0.8.9      State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.1.5      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.6      State: Not activated 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.2      State: Enabled

Host: localhostConnection: OkUse the OCSNG software dictionary: Yes
`

**Comment by Tchanove** [comment]
Hi there !

We're facing the same issue.

To complete, the problem is **NOT** happening when rich text is enabled.
It's not a satisfying solution for us as rich text create a new "<p></p>" for each line and the "<p>" block have a huge margin making the description really hard to read.

Btw, with or without rich we have problem with inline images... But this is another problem, I'll probably open another issues.

Ty for you help 👍

**Comment by ensonb** [comment]
@Tchanove  Yes, I can confirm that this is not a problem with rich text enabled.

thank you for that feedback .

**Comment by jestevan** [comment]
Any solutión for this???, i have the same problem

**Comment by Armin83** [comment]
I think this is your bug and manual solution or wait for 9.2.2 https://github.com/glpi-project/glpi/issues/3413.

Please close if solved

**Comment by ensonb** [comment]
For some reason, I Saw #2872  back in October and could not see the solution due to my poor git hub knowledge, last night i tried again and this is no longer a problem for me.
