### ISSUE TITLE
Location field is empty when automatically assigned

### ISSUE THREAD

**Issue by Juloni** [glpi-project/glpi#3259]
Hi Everyone,

This issue has been messing with my head for some time, and I'm now asking for your kind help ...

In GLPI, if i let the user (Self-Service) select the location when creating the ticket, the location displays just fine in the ticket from the technician's view.
If I choose in my ticket template to pre-assign the location, the location is blank from the technician's view. 

I can't figure it out, and did not see an older post mentionning this particlar issue. Any ideas ?

**Comment by pVesian** [comment]
Hi @Juloni, I've just tested this in 9.2.3, can you test it in this version? Thanks.

**Comment by trasher** [comment]
No feedback, closing
