### ISSUE TITLE
[0.90.1] Message d'avertissement SELinux

### ISSUE THREAD

**Issue by FrBillyD** [glpi-project/glpi#326]
Bonjour,

Sur notre installation de GLPI 0.90.1, nous avons trois messages d'avertissement qui s'affichent dans la page de configuration générale sous l'onglet "Système" :
- SELinux boolean configuration for  (Some features may require this to be on) ;

L'interface fonctionne bien pour le moment ainsi que tous les plug-ins. Je penses que c'est un bug car les messages d'arvertissements ne donne pas la valeur SELinux à activer...

Merci d'avance pour ce que vous pourrez faire.

*Voici la capture des messages :*
![glpi-config_system_selinux](https://cloud.githubusercontent.com/assets/4552702/11805625/95217348-a30d-11e5-9c12-1ab241ebf0e5.png)

**Comment by yllen** [comment]
Ce message est pour vous prévenir que votre SELinux est activé sur votre serveur et que cela n'est pas compatible avec la version actuelle.
En effet, cette fonctionnalité peut bloquer certaines actions dans GLPI

**Comment by remicollet** [comment]
Je pense qu'il y a un soucis, le nom du boolean devrait être affiché.

**Comment by remicollet** [comment]
La sortie doit ressembler à:

    Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect --> off (Some features may require this to be on)
    Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect_db --> off (Some features may require this to be on)
    Some features may require this to be onSELinux boolean configuration for httpd_can_sendmail --> off (Some features may require this to be on)

**Comment by FrBillyD** [comment]
Bonjour, merci pour vos réponses. C'est pour ça que je l'ai signalé. J'avais activé certaines valeurs dont les trois ci-dessus.
Cependant, les messages étaient toujours là, d'où mon post. Par contre, GLPI semble fonctionner correctement.

**Comment by remicollet** [comment]
Que retourne la commande 

    which getsebool

Et 

    getsebool

**Comment by remicollet** [comment]
et aussi

     which getenforce
    getenforce
    getsebool -a | grep http

**Comment by FrBillyD** [comment]
_ `which getsebool` : `/usr/sbin/getsebool` ;
_ `which getenforce` : `/usr/sbin/getsebool` ;
_ `getsebool -a | grep http` : 
```bash
allow_httpd_anon_write --> off
allow_httpd_mod_auth_ntlm_winbind --> off
allow_httpd_mod_auth_pam --> off
allow_httpd_sys_script_anon_write --> off
httpd_builtin_scripting --> on
httpd_can_check_spam --> off
httpd_can_network_connect --> on
httpd_can_network_connect_cobbler --> off
httpd_can_network_connect_db --> on
httpd_can_network_memcache --> off
httpd_can_network_relay --> off
httpd_can_sendmail --> on
httpd_dbus_avahi --> on
httpd_dbus_sssd --> off
httpd_enable_cgi --> on
httpd_enable_ftp_server --> on
httpd_enable_homedirs --> off
httpd_execmem --> on
httpd_manage_ipa --> off
httpd_read_user_content --> off
httpd_run_preupgrade --> off
httpd_run_stickshift --> off
httpd_serve_cobbler_files --> off
httpd_setrlimit --> off
httpd_ssi_exec --> off
httpd_tmp_exec --> off
httpd_tty_comm --> on
httpd_unified --> on
httpd_use_cifs --> on
httpd_use_fusefs --> off
httpd_use_gpg --> off
httpd_use_nfs --> on
httpd_use_openstack --> off
httpd_verify_dns --> off
named_bind_http_port --> off
```
_ `getenforce` : `Enforcing` (contraintes de sécurité, je suis dans un hôpital) ;

Voilà :)

**Comment by remicollet** [comment]
Bon bizarrement, ces commandes ne retourne rien lorsqu'exécuté par apache.
Une autre protection, pour l'instant je n'ai pas d'idée.

Je vais juste ajouter un test pour détecter les réponses vides

**Comment by FrBillyD** [comment]
Ok, et pour info, je n'ai pas de trace d'Apache dans `/var/log/secure`.

**Comment by remicollet** [comment]
The fix is not perfect, but should display 'Unknown"

**Comment by FrBillyD** [comment]
Roger :smile: :stuck_out_tongue:
