### ISSUE TITLE
SQL problem updating from 9.1.3 to 9.2.1

### ISSUE THREAD

**Issue by ashmonger** [glpi-project/glpi#3266]
I was trying to update from 9.1.3 to 9.2.1 and stumble across this error when I was asked to update the database.

>  9.2 multiple alter in glpi_slas - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_slas` ADD INDEX `slms_id` (`slms_id`) - L'erreur est Key column 'slms_id' doesn't exist in table

Information from the server.

X | From | To
--- | --- | ---
OS | Ubuntu 14.04 | Ubuntu 16.04
PHP | Php 5.5.9 | Php 7.0.25
Apache | 2.4.7 | 2.4.18
SQL | MySQL 5.5.50 | MariaDB 10.2

**Comment by ashmonger** [comment]
I tried again and that worked out.

Deleting the database and putting the dump again.

**Comment by lp73** [comment]
J'ai apporté une réponse sur https://github.com/glpi-project/glpi/issues/3671
