### ISSUE TITLE
PHP Errors in SLA / SLAs configuration tab

### ISSUE THREAD

**Issue by tech62** [glpi-project/glpi#3267]
Hi !

I've these errors when i go in the sla/slas configuration, any idea ?

![glpi_bug_sla1](https://user-images.githubusercontent.com/16237642/33791313-3852c96a-dc8a-11e7-8ffc-ffb76af436a7.JPG)
![glpi_bug_sla2](https://user-images.githubusercontent.com/16237642/33791332-82c099b4-dc8a-11e7-81ef-db95481be2a2.JPG)

I can't modify the type and maximum time for the SLA.

Can you help me please ?

Thanks !

**Comment by trasher** [comment]
This issue is quite old, and I'm pretty sure this ha been fixed (at leeast partially) in latests releases. Please try with 9.3.1, and feel free to reopen if it still persists.
