### ISSUE TITLE
Bug - Time Resolution + Progresss

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#3268]
working whith scalation levels the time line not update when change resolution time.

The ticket starts whith 15 minutes on N1. If it is note closed, it is scalated to N2 and the resolutioin time is change to 45 minutes. If is note closed, it is scalated to N2 and resolution time is changed to 2 hours.

The rules to alter the SLA (resolution) is ok. The GLPi apply the new time and add the Groups N2 and after N3. The unique proble is to show the "time to resolve + progress" on "Assistence > Tickets" screen.  the time is changed on fields, but the time bar contiunues whith 100% because the first SLA aplicated (15 minutes). 

![image](https://user-images.githubusercontent.com/22614882/33798112-ed66f88c-dcf1-11e7-825a-4d59421196f0.png)

**Comment by vijayabhaskerg** [comment]
I too have the same problem.  Is there a solution found that updates the "Progress" bar of Time To Resolve when the time is changed.

Thank you.

**Comment by Christian493** [comment]
Hi in version 9.4.4 this problem exist again. is there any solution how to fix it?
Thank You.
