### ISSUE TITLE
Bug to reopen ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3274]
Bug introduce in correction of https://github.com/glpi-project/glpi/issues/2656

This bug is only if you use timeline without old tabs.
When you click on reopen the ticket, a new followup is added. This the correction nothing is done.

You must add control of status only to display Followup button

**Comment by trasher** [comment]
This issue only happens on 9.1; not on 9.2. Reverting commit that fixes #2656 does not solve the issue.

**Comment by yllen** [comment]
I agree with you: with revert only display followup button.

This issue for reopen ticket is only is you don't display old tabs with using timeline.

**Comment by trasher** [comment]
Yes, we're able to reproduce; I did not find the fix right now :/

**Comment by orthagh** [comment]
It can be fixed, i think by cherry-picking commit of #2755

**Comment by orthagh** [comment]
closed by #3318 & 9126c84
