### ISSUE TITLE
Need GLPI GLPI 9.2.1 Documents 

### ISSUE THREAD

**Issue by manideepanchoori** [glpi-project/glpi#3278]
Hi All,

I have installed GLPI 9.2.1 but am getting confused how to implement the tool and how to administer it. May you please any one help me in getting proper Implementation and administration and usage documents for GLPI 9.2.1.

Thanks in advance.

**Comment by Armin83** [comment]
the latest, redesign & version is the there http://glpi-user-documentation.readthedocs.io/fr/latest/index.html you can google translator to read it in your language or English. Maybe you can read french :)

The question mark link from your glpi installation goes to http://glpi-project.org/DOC/

If you want pdf you can use this document many functions are still correct for 9.2.1
https://forge.glpi-project.org/attachments/download/1901/glpidoc-0.85-en-partial.pdf
