### ISSUE TITLE
[0.90.1] Processing tickets - uploading documents

### ISSUE THREAD

**Issue by pzmw** [glpi-project/glpi#328]
When processing a ticket (timeline view), it is possible to select multiple files in the form "Add a document".

However, when clicking on the button "Add a new file" all the files are uploaded to the webserver but only the last selected file is linked to the ticket.
I think all files should be immediately be linked to the ticket.

I am using GLPI 0.90.1

**Comment by yllen** [comment]
No you can only select one document by one document.
So one document is added by action.

**Comment by pzmw** [comment]
You can choose one file, which is uploaded in the background, but you can add another by clicking the button "Choose File" again.
Also, it is a drag and drop area, so multiple files can dropped here.

They are all listed and uploaded to the webserver, only the last added document is linked to the ticket.

**Comment by yllen** [comment]
OK i understand the problem
