### ISSUE TITLE
Bad display of custom views

### ISSUE THREAD

**Issue by mickaelambrosini** [glpi-project/glpi#3282]
Hello,
I have issue with bad issue, sorry if i duplicate but i don't find an equivalent ticket.

Thanks for your works !
![2017-12-13_08-29-28](https://user-images.githubusercontent.com/33825262/33926876-274a68b8-dfe0-11e7-890a-556a965df4f4.png)

**Comment by trasher** [comment]
Your issue miss many informations, includung GLPI version used and browser... Anyways, please test with 9.2.2, I think this has been solved.
