### ISSUE TITLE
[0.90.1] Upload document not working with Internet Explorer 11

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#329]
Hi,

The upload of a document not working with Internet Explorer 11.

If i configure IE in "IE 9" compatibility mode, the upload working, the document upload succefully.
If i let IE in "Edge" compatibility mode the document never upload : 

![Upload progress](http://i.imgur.com/XrRgVJT.png)
![Upload finish](http://i.imgur.com/lQpWMi5.png)

Same issue with IE in "IE 10" compatibility mode.
The upload seems to not working with Internet Explorer version > 9.

I use Internet Explorer 11 in Windows 7 64 bits.

Thanks to solve it

++

**Comment by orthagh** [comment]
Hello @barbuslex 

see this issue #196.

If you have an autlogon (ntlm) enabled, it should be same as this issue

**Comment by barbuslex** [comment]
Hi @orthagh !

Yes i have NTLM autologon enabled.

/front/fileupload.php not exists in GLPI 0.90.1 :(

And i don't have vhost in my server... is it possible to set it in htaccess file ?

Thanks for your reply,

++

**Comment by orthagh** [comment]
(front/fileupload.php)[https://github.com/glpi-project/glpi/blob/0.90.1/front/fileupload.php] still here :)

.htacess (in front folder) should work if your hosting service provider has enable AllowOverride to all with this kind of code (not tested) : 
```
<Files fileupload.php>
     Satisfy Any
 </Files>
```

**Comment by barbuslex** [comment]
Yes my bad...

I use Apache 2.4 so i do a .htaccess file like this in /front/ folder : 
```
<Files fileupload.php>
	Require all granted
</Files>
```

Is it possible to add this file in future version of GLPI ?

Now when i try to upload document (pdf file) i get this error : 
![Failed upload](http://i.imgur.com/wMa1DOe.png)

Have you an idea @orthagh ?

Thanks for your help.

**Comment by barbuslex** [comment]
It's working.... i just replace : 
> Deny from all
by : 
> Require all denied

On each .htaccess files of GLPI.

**Comment by orthagh** [comment]
I close this ticket for now (initial bug refer to #196)
For future integration, it's difficult, its a bug in toolchain IE+NTLM but i keep it in mind.

For your last error, it's a normal behavior, glpi manage a list of authorized extensions in Configuration > Dropdowns > Document Types.
You can a new type for enable upload of your extension.

**Comment by barbuslex** [comment]
It's working.... i just replace : 
> Deny from all

by : 

> Require all denied

On each .htaccess files of GLPI.

**Comment by barbuslex** [comment]
I reopen the issue because the problem of the file extension appears a hit on two : 

- First try : 
![Failed upload](http://i.imgur.com/wMa1DOe.png)

Reponse of fileupload.php
```
{"filename":[{"name":"1450279181-2944","size":0,"type":"multipart\/form-data; boundary=---------------------------7dfa22953003e","error":"Type de fichier non autoris\u00e9","id":"docfilename755000581"}]}
```

- Second try : 
![Success](http://i.imgur.com/6A1dmL9.png)

Response of fileupload.php : 
```
{"filename":[{"name":"Fichier pdf.pdf","size":24835,"type":"application\/pdf","url":"http:\/\/intranet.chet.local\/glpi\/front\/files\/Fichier%20pdf.pdf","deleteUrl":"http:\/\/intranet.chet.local\/glpi\/front\/?filenam=Fichier%20pdf.pdf","deleteType":"DELETE","display":"Fichier pdf.pdf 24.25 Kio","filesize":"24.25 Kio","id":"docfilename476096772"}]}
```

Have you an idead @orthagh ?

Thanks in advance

**Comment by orthagh** [comment]
same filename or extension ?

**Comment by barbuslex** [comment]
Yes the filename is : "Fichier pdf.pdf"

**Comment by orthagh** [comment]
In your first case, filename seems to be 1450279181-2944

Cannot find why ?

**Comment by barbuslex** [comment]
I don't understand why, i upload the same file in 2 case.

Maybe temp filename on server ?

**Comment by barbuslex** [comment]
Have you see the url generated on second case @orthagh ?
> http://server/glpi**/front/files/**Fichier pdf.pdf

Would not it should be a thing like this : 
> http://server/glpi**/files/**Fichier pdf.pdf

???

**Comment by barbuslex** [comment]
Currently the problem disappeared.

Perhaps a problem in the PHP server sessions.

I close the ticket.

**Comment by barbuslex** [comment]
The issue appears again is a real problem for uploading document

**Comment by barbuslex** [comment]
This issue is critical beaucause my users cannot add a file to their tickets.
Anyone can help me ?

**Comment by tomolimo** [comment]
Hello
to help troubleshoot this, you may use fiddler to spy network exchanges bewtween IE and Server.
With fildler you shoul dbe able to see if the strange file name is comming from server or from IE.

**Comment by barbuslex** [comment]
Hi @tomolimo,

Thanks for your reply.
It was very difficult to reproduce the issue. But i managed to produce a .saz file with Fiddler4.

My manipulation: 
- Connected to GLPI with super-admin user
- Helpdesk / New Ticket
- Add file to ticket / Browse...
- Select "Fichier PDF.pdf"

Result:
- 1st upload: unallowed file type
- 2nd upload: unallowed file type
- 3rd upload: success upload file

The .saz file is attached.

Have you an idea ?

Here my server configuration : 
- Windows Server 2008 R2 64 bits
- Apache 2.4.18 x64 VC11
- PHP 5.5.31 NTS x64 VC11 (Configured in fcgid mode)
- MariaDB 10.0.23 64 bits

Thanks for your help.

**Comment by tomolimo** [comment]
Hello,
I can see that you are using NTLM with Apache x64: where did you get the module?
I can see an upgrade to it: https://www.apachehaus.com/cgi-bin/download.plx
I believe there is a problem in configuration or in module itself.
Could you update and redo a test/trace? But this time from start of IE and not only from upload of file?
thank you,
regards,
Tomolimo 

PS: in the past I tried also such configuration and switched to IIS7.5 as IIS natively managed NTML.
But at the end I cancelled use of NTML as it needs three roundtrips with web server to get authorized. As we are using GLPI internally (same LAN, no external connection), I wrote a small JS script that get user name from Windows and sends it to GLPI.

**Comment by barbuslex** [comment]
It's apachehaus.com's mod_authn_ntlm module that i use.
What is the update for this module ? I see 1.0 version in mod_authn_ntml-1.0-2.4.x-x64-vc11.zip.

I don't understand... when i retry to upload i have 100% of success upload now. It's really mysterious.

Previously, when i have the problem, the file wasn't put in /glpi/files/_tmp folder.

When upload works the file uploaded (Fichier PDF.pdf) is present in /glpi/files/_tmp folder.

Here you can find the full trace. The problem occurs in line 809. Previous try are succefull upload.
Between each upload i was delete the "Fichier PDF.pdf" in /glpi/files/_tmp.

The file /front/fileupload.php is out of ntlm authentication with .htaccess file.
/font/.htaccess file content : 
```
<Files fileupload.php>
	Require all granted
</Files>
```

Here the .saz file : https://drive.google.com/file/d/0B5OckHsCwP3dTXU3dzlQQ3pWT1E/view?usp=sharing

**Comment by barbuslex** [comment]
Here the fcgid config for apache : 
```
FcgidInitialEnv PHPRC "C:\\www\\php"
FcgidInitialEnv SystemRoot "C:\\Windows"
FcgidInitialEnv SystemDrive "C:"
FcgidInitialEnv TEMP "C:\\WINDOWS\\TEMP"
FcgidInitialEnv TMP "C:\\WINDOWS\\TEMP"
FcgidInitialEnv windir "C:\\WINDOWS"
	
FcgidIOTimeout 3600
FcgidOutputBufferSize 64
FcgidBusyTimeout 360
FcgidProcessLifeTime 3600
FcgidMaxProcesses 64
FcgidMaxProcessesPerClass 8
FcgidMinProcessesPerClass 0
FcgidConnectTimeout 360
FcgidIdleScanInterval 0
FcgidIdleTimeout  360
FcgidMaxRequestLen 1073741824
```

**Comment by tomolimo** [comment]
Thank you,
I'll look at the traces, and keep you informed.
Sorry for misleading you about the module upgrade I missed the real version number of the module on "apache haus".

Also did you look at this https://github.com/glpi-project/glpi/issues/196?

**Comment by tomolimo** [comment]
The trace you sent are for IE compatibility mode don't they?
Could redo them with no compatibility flag set? I mean normal IE11 mode?
As I prefer to try to debug normal mode rather than compatibility mode :)
Thank you
Tomolimo

PS: you may drag/drop your zip file directly into the post in github.

**Comment by barbuslex** [comment]
Yes the solution of @orthagh has applied in htaccess.
My Windows Server and Internet Explorer 11 are up to date (Tuesday Patch of January 2016)

**Comment by barbuslex** [comment]
@tomolimo 
Yes but it does not influence the manifestation of the problem.
Here traces in IE 11 in Edge mode.
I do not reach the zip document in github. (Probably too big).
Here is the link of the .saz file (the problem occurs in line 566): https://drive.google.com/file/d/0B5OckHsCwP3dMEhKUkMxUTFid2s/view?usp=sharing

**Comment by tomolimo** [comment]
Euh, I can't see this line in the file, and more over still MSIE7.0 ....

**Comment by barbuslex** [comment]
Yes, my bad. The issue occurs in line 379.
I dont understand why MSIE7.0 i'm using IE 11 in Edge mode : 
![ie11](https://cloud.githubusercontent.com/assets/113057/12354568/3478e600-bb97-11e5-8b4f-cdf4a33d06c1.PNG)

**Comment by barbuslex** [comment]
In file /glpi/front/fileupload.php i add a print_r() to the response of UploadHandler object like this : 
```
$response = $upload_handler->post(false);
print_r($response);
```

Here the response : 
```
Array
(
    [filename] => Array
        (
            [0] => stdClass Object
                (
                    [name] => 1452866895-8061
                    [size] => 0
                    [type] => multipart/form-data; boundary=---------------------------7e027ef60066
                    [error] => Le fichier est trop petit
                )

        )

)
```

I see that it's Jquery-File-Upload plugin : 
> * jQuery File Upload Plugin PHP Class 6.10.0
> * https://github.com/blueimp/jQuery-File-Upload

Maybe just an update of this plugin solve the issue ?

**Comment by tomolimo** [comment]
For jQuery: I don't know, you may try.
For IE the user-agent string I can see in the traces is MSIE7.0 means that it is not in IE11 mode but IE7 mode (which is a compatibility mode, and not the native IE11 mode). So please redo the tests with IE11 mode instead of 'Edge' which must not be confused with the name of the new MS browser for Windows10.

**Comment by tomolimo** [comment]
what is in the traces:

    Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; CMDTDFJS; InfoPath.3)

Normally it should be for IE11:

    Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko

see: https://msdn.microsoft.com/fr-fr/library/bg182625(v=vs.85).aspx

**Comment by tomolimo** [comment]
Anyway, I remember that I also tried to have part of the a web site to be with NTLM and some parts to be without (for performance reasons) but as far as I remember, IE9 (at the time of my tests) was not able to manage such situation and was sending anyway the NTLM auth for each requested pages, resulting in a big mess in Apache NTLM module... Could it be somehow the same problem?

**Comment by barbuslex** [comment]
I found why i have IE7 in user agent !
By default Internet Explorer use the compatibility mode for Local Intranet websites. (Thanks Microsoft).

![iedaub](https://cloud.githubusercontent.com/assets/113057/12356442/149271e2-bba3-11e5-8614-6c5cb73970d8.PNG)

To disable this i need to edit this group policy : 
> Computer Configuration/Administrative Templates/Windows Components/Internet Explorer/Compatibility View/Turn on Internet Explorer Standards Mode for Local Intranet

I will test in detail with this configuration next week and i return to you the result. Good week-end to you  and thanks so much for your help :)

**Comment by barbuslex** [comment]
Re @tomolimo ,
Same issue with Internet Explorer 11 without IE 7 compatibility mode.

Here the .saz file : https://drive.google.com/file/d/0B5OckHsCwP3dX0hjU3lFQzdEQVE/view?usp=sharing

The problem appears in line 352.

Thanks for your help

**Comment by tomolimo** [comment]
Hello,
What I suggest is to divide the problem (divide to better reign :)):
I don't remember: did you already try with Chrome and/or Firefox?
Could you also try without NTLM? I mean disable the NTLM authentication on Apache?
Could you also try with IIS7.5?
thank you,
Tomolimo

**Comment by tomolimo** [comment]
Another idea: could you send to me your pdf file? I'll do a local test.

**Comment by barbuslex** [comment]
The problem does not seem to occur on Firefox and Chrome. I am trying to do several tests.

The file /glpi/front/fileupload.php is out of NTLM authentication (with htaccess file in /glpi/front/ folder): 
```
<Files fileupload.php>
    Require all granted
</Files>
```

I didn't try with NTLM authentication completly disable on apache (it's my production server).

The PDF files are very simple. 1 scanned and 1 generated with pdfcreator 1.7.3 : 
https://drive.google.com/file/d/0B5OckHsCwP3dWW56dFNJa2tWRE0/view?usp=sharing

I have not tested with IIS because I have a lot of applications with .htaccess files (including GLPI).

**Comment by tomolimo** [comment]
Could you also try to put out of NTLM the file glpi/ajax/getFileTag.php ?

**Comment by barbuslex** [comment]
I just tried and I have the same problem with a .htaccess file in the folder /glpi/ajax/ and contains the following:
```
Require all granted
```

If you test your side, remember to delete the uploaded file in /glpi/files/_tmp/ folder between each upload.

**Comment by barbuslex** [comment]
I just found a blogger who explain the same issue : https://blog.yorkxin.org/posts/2014/02/06/ajax-with-formdata-is-broken-on-ie10-ie11/

**Comment by tomolimo** [comment]
I don't think this issue is the same than yours...as you don't have HTTP500 error: your HTTP flow seems OK, HTTP is in (200, 401 and 304): there is no internal server error.

**Comment by tomolimo** [comment]
let's look at the HTTP flow:
line 343 you have selected a file and this file is uploaded to the server, right?

**Comment by tomolimo** [comment]
At this point, you should be able to check that the file is really uploaded on the server, right?

**Comment by tomolimo** [comment]
An idea: could you do a trace with fiddler using Chrome? We may compare both traces one with IE and one with Chrome?

**Comment by barbuslex** [comment]
Yes when upload was succeed (line 343) the file was present in the /glpi/files/_tmp/ folder on the server.

You can found here the trace in Chrome and IE11 : https://drive.google.com/file/d/0B5OckHsCwP3dSXAxUTZnaGhrN00/view?usp=sharing

**Comment by tomolimo** [comment]
I made a test on my IIS7.5 with NTLM on GLPI 0.901 and IE10: all is OK.
The traces are looking like the one with Chrome...

**Comment by barbuslex** [comment]
How can you do with htaccess and IIS ?

**Comment by tomolimo** [comment]
I don't know, I believe IIS doesn't take into account these files...

**Comment by barbuslex** [comment]
Ok, but i can't migrate to IIS. Can you send me your PHP configuration ?

**Comment by tomolimo** [comment]
Here it is:
[php.ini.txt](https://github.com/glpi-project/glpi/files/95504/php.ini.txt)
IIS: can be installed and configured on another port than 80, I uses IIS module PHPManager (free) to configure PHP and FastCGI on IIS. PHP must be NTS on IIS. Currently we are using PHP 5.4.44 x86 (but I already made tests with a PHP 5.5, 5.6 x86 and PHP 5.4 x64).
regards,
tomolimo

**Comment by barbuslex** [comment]
Your configuration is similar to mine.
I didn't see what can pose this problem : 
- [php.ini.txt](https://github.com/glpi-project/glpi/files/95551/php.ini.txt)
- [httpd.conf.txt](https://github.com/glpi-project/glpi/files/95552/httpd.conf.txt)

**Comment by tomolimo** [comment]
xdebug seems to be up and running: on your production server?

**Comment by barbuslex** [comment]
Yes just for var_dump() function and beautiful html errors not for debug on remote port.

**Comment by barbuslex** [comment]
What is strange is that if the problem is the web server, the problem should occurs on Firefox and Chrome also. However, this is not the case.

**Comment by tomolimo** [comment]
Don't you have perf problem too?
xdebug slows down server by a coef 100

Anyway from the traces I saw, for me the problem is IE + auth_ntlm, IE doesn't really support switch on and off of NTLM in the same FQDN. IE will send auth HTTP header info when not needed and will be lost when NTLM is not used everywhere.

**Comment by tomolimo** [comment]
At least, it was the case for IE9, and I don't know hos it is managed by IE > 9

**Comment by barbuslex** [comment]
I just disable NTLM authentication on my GLPI and the problem always occurs with Internet Explorer 11.

This is a known bug with sending POST ajax mode.

There are open ticket at Microsoft about this:
https://connect.microsoft.com/IE/Feedback/Details/868498

I just find a way to fix it with a PHP or JS trick ^^

**Comment by tomolimo** [comment]
But in the traces you sent me I cannot see this malformed post data...
and if you look at this: http://blogs.msdn.com/b/david.wang/archive/2005/12/01/http-post-fails-for-anonymous-authentication.aspx
You'll see that IE is performing an auth NTLM optimization when URL to the same site has NTLM or not.

**Comment by barbuslex** [comment]
I disabled the NTLM on GLPI. I will test it for a while. If the problem recurs I transmit to you the trace.

What is the file that handles automatic login via NTLM in GLPI?

**Comment by tomolimo** [comment]
In fact it is managed via a server variable. This variable is checked in auth.class.php in getAlternateAuthSystemsUserLogin function in the self::EXTERNAL case.

**Comment by tomolimo** [comment]
I have just installed and configured a virtual machine running WIN7 x64 + IE11 + fiddler4,
And tried to get GLPI 0.901 + NTLM running.
And sometimes I got the same error than yours, but sometimes it's ok...

**Comment by barbuslex** [comment]
@tomolimo 
Ok ! I'm glad to hear that the problem is not our server.
In this case, the server applications is Apache + PHP or IIS + PHP ?

Maybe we can activate NTLM authentication only in auth.class.php file ?

**Comment by tomolimo** [comment]
not yet sure the problems are identical, as I've a real error code

regarding NTLM: I don't know

**Comment by tomolimo** [comment]
The error I've got is: HTTP 408 (Request body incomplete)

**Comment by barbuslex** [comment]
With IIS or Apache ?
I am about to try to enable NTLM only on certain file to see if that fixed the problem.

**Comment by barbuslex** [comment]
In the old version of GLPI (0.84), without ajax upload, the documents were sent correctly with the same environment.

**Comment by tomolimo** [comment]
IIS7.5

**Comment by barbuslex** [comment]
Maybe IIS response is more explicit than Apache with 408 error.

**Comment by tomolimo** [comment]
I'm going to update this VM to latest updates and also for IE11 and will redo the tests.

**Comment by barbuslex** [comment]
In my machine i am up to date ^^ (Tuesday Patch of January 2016)

**Comment by tomolimo** [comment]
It's a new VM with Win7 enterprise SP1

**Comment by barbuslex** [comment]
I have found another document upload library validated with Internet Explorer : http://docs.fineuploader.com/branch/master/browser-support.html

**Comment by barbuslex** [comment]
I just see that the script is under license (not open source) :(

**Comment by tomolimo** [comment]
For free or open-source project is written the following:

> If you are developing an open-source or free product and will not derive any money from the product using Fine Uploader, you may use Fine Uploader free of charge under the Widen Commercial License.

**Comment by barbuslex** [comment]
Ok, but this script seems to be little be more complex than jquery-file-upload.

**Comment by tomolimo** [comment]
For me the initial problem comes from IE Pre-Authentication behaviour.

Could you try the following?

on your IE computer: start regedit
> HKEY_CURRENT_USER/Software/Microsoft/Windows/CurrentVersion/Internet Settings/
> Add the following registry value: 

> Value Name: DisableNTLMPreAuth
> Data Type: REG_DWORD
> Value: 1

restart your computer,
on server: enable anonymous by default, and enable NTLM *only* for /glpi/index.php and /glpi/front/login.php (of course disable NTLM everywere else). Be sure that anonymous is disabled for those two files.
restart Apache.

and test. In fiddler traces you should only get one or two http 401 for /glpi/index.php (or /glpi/)

**Comment by tomolimo** [comment]
You may check here: https://support.microsoft.com/en-us/kb/251404

**Comment by barbuslex** [comment]
I have applied your reg key on my system and i have reboot.

In apache i set in /glpi/.htaccess : 
```
<Files index.php>
AuthName "Accès restreint"
AuthType SSPI
NTLMAuth On
NTLMAuthoritative On
NTLMOfferBasic On
NTLMPerRequestAuth On
require valid-user
</Files>
```

And in /glpi/front/.htaccess : 
```
<Files login.php>
AuthName "Accès restreint"
AuthType SSPI
NTLMAuth On
NTLMAuthoritative On
NTLMOfferBasic On
NTLMPerRequestAuth On
require valid-user
</Files>
```

But the NTLM not working now... GLPI prompt username/password on index.php.

Have you an idea ?

Thanks

**Comment by tomolimo** [comment]
Could you try to disable Basic auth for index.php?
> NTLMOfferBasic Off

Otherwise, IE will use Basic as it is accepted by server...

**Comment by barbuslex** [comment]
It's good. NTLM authentication works again.

I do this in /glpi/.htaccess : 
```
<Files ~ "^$|index.php|login.php">
	AuthName "Accès restreint"
	AuthType SSPI
	NTLMAuth On
	NTLMAuthoritative On
	NTLMOfferBasic Off
	NTLMPerRequestAuth On
	require valid-user
</Files>
```

I made you a trace immediately (if I can reproduce the problem).

**Comment by tomolimo** [comment]
Did you also change your registry?

**Comment by barbuslex** [comment]
Yes i have patched my registry. The issue seems to to be solved, I continue my tests to be sure.
On your IIS environment with this solution does it work?

**Comment by tomolimo** [comment]
Yes :)

**Comment by tomolimo** [comment]
and for you it should be slightly quicker (shorter response time) as IE will not send authentication request to each requested page.

**Comment by barbuslex** [comment]
Ok, i like this way ;)
Yes indeed it is faster to load.

On machines without the registry patch the problem persists. Changing NTLM authentication had no effect.

I continued my tests on machines with registry patch...

**Comment by tomolimo** [comment]
yes you need both due to this:
> Note Microsoft Internet Explorer requires NTLM authentication for all visits after you visit one NTLM authenticated folder.
ref: https://support.microsoft.com/en-us/kb/251404

**Comment by barbuslex** [comment]
Ok, i have deployed the fix on all machines. I will test more tomorrow.

**Comment by barbuslex** [comment]
How can you found this fix ?

**Comment by tomolimo** [comment]
???

**Comment by barbuslex** [comment]
I answered too quickly ^^
How ~~can~~ did you found this fix ?

**Comment by tomolimo** [comment]
Do you mean: how did you find this fix?

**Comment by barbuslex** [comment]
Yes ^^

**Comment by tomolimo** [comment]
Long story:
1) When I installed GLPI 0.83.8 for our internal use: I first started with Apache 2.4 (three years ago), and then I switch to IIS when I saw too much problems with: NTLM, scalability, and responsetime (yes IIS has better performance than Apache), and also when I saw that a lot of support were existing for PHP on IIS.
2) I saw at this time a lot of network traffic due to NTLM (= three round trip for each authentication), and tried at this time to have only some part of the web site to be NTLM and the rest to be anonymous. I didn't succeed for two reasons: a) IE didn't pay attention to server param (as soon as it is using NTLM, then for the whole site it is using NTLM). b) Didn't find at this time how to have only one file with NTLM on IIS server.
3) I decided then to develop another login mechanism (poor of course, but compatible with IE).  used in a javascript an activeX that permits to get username from computer environment variables, and the same javascript sends this username to the server back to index.php. This script is still in use on our production server. This is SSO without NTLM (so no special network round trips), but works only in IE (due to activeX).
4) I saw that in your traces you've got two problems: a) each page were asking authentication (due to  *SSPIPerRequestAuth On* and that b) even when NTLM was disabled for fileupload.php, sometimes NTLM header was sent by IE.
5) it remembered me what I saw and described above:)
6) I've created a new VM with Win7 enterprise x64 with IE11 to be able to test IE11 (as we don't currently use IE11, but still IE10 in our company, I was not able to test on my PC with IE11). And with this VM I was not able to reproduce exact behavior of your IE11 (as I don't have Apache, but IIS), But being able to trace more or less the same effects.
7) Doing these searches, I learnt how to configure IIS for NTLM just for one (or two) files (such preventing round trips).
8) And for sure I've applied these on my GLPI 0.90.1 and 0.91 servers (dev and tests). And I'll apply these also to my next GLPI 0.91 prod server.

regards,
Tomolimo

**Comment by barbuslex** [comment]
Okay ^^ !
I can not reproduce the problem today.
So we can close the ticket. I will open it ever again if the problem recurs.

**Comment by barbuslex** [comment]
Thanks so much for your help @tomolimo ;)

**Comment by DrKak** [comment]
Hello,
I have the same issue with IE11 and upload files, I disabled with registry key but dosent work.

There is another things to do ?

Thanks

**Comment by tomolimo** [comment]
Please post in another issue as this one is closed!

**Comment by barbuslex** [comment]
Reboot your computer after apply the reg key.
