### ISSUE TITLE
ID missing in the subject of notifications of changes & problems

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#3295]
Version GLPI : 9.2.X & 9.1.X
ID missing in the subject of notifications of changes.

In ticket notifications:
![ticket](https://user-images.githubusercontent.com/15138371/33986969-981b4c94-e0bf-11e7-94b0-daf7a9dee917.png)

In notifications of changes & problems:
![change](https://user-images.githubusercontent.com/15138371/33986964-931f6a86-e0bf-11e7-8eaa-21794c2a96f5.png)

**Comment by amma35** [comment]
can be add this function ? 
```
diff --git a/inc/notificationtargetcommonitilobject.class.php 
+   /**
+    * @param $event  (default '')
+    **/
+   function getSubjectPrefix($event = '') {
+
+      $perso_tag = trim(Entity::getUsedConfig('notification_subject_tag', $this->getEntity(),
+                                              '', ''));
+
+      if (empty($perso_tag)) {
+         $perso_tag = 'GLPI';
+      }
+      return sprintf("[$perso_tag #%07d] ", $this->obj->getField('id'));
+   }
+
```

**Comment by amma35** [comment]
Does this solution seem right to you?

**Comment by trasher** [comment]
Sounds correct, yes; but the method in inc/notificationtargetticket.class.php should be changed.

**Comment by amma35** [comment]
Okay, for GLPI version 9.2 or 9.3? 
Do I do a PR anyway?

**Comment by trasher** [comment]
You can target 9.2 ;)
