### ISSUE TITLE
Adding a new followup permits to change ticket status even if no rights

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#330]
Hello,
Imagine: a user has a profile with which he can't change status of ticket (no ticket update), but he only can add followups to tickets (add to all tickets). And this profile can't change ticket statuses (ticket life cycle has been set to identity).
![image](https://cloud.githubusercontent.com/assets/7569958/11842408/c0e33308-a403-11e5-9953-d19b08d0a5b4.png)
Then with the button to add a new followup he can select any new ticket statuses :(!
![image](https://cloud.githubusercontent.com/assets/7569958/11842367/835fc1d6-a403-11e5-9814-ba1b6b283577.png)
This should not be possible
Regards,
Tomolimo

**Comment by yllen** [comment]
I don't understand what you want.
If you change any field in a ticket you must have right to update it.
And add a new followup don"t change the status

**Comment by tomolimo** [comment]
This is not a request for change, it's a bug!
If you are using a profile which doesn't give you rights to change ticket status, then when you edit a ticket you can't change the status. But if you add a followup, you may change the status of the ticket see screen copies above.

**Comment by yllen** [comment]
Vous vous etes déconnecté parès avoir changé le cycle de vie du profil ?
Je viens de refaire un test et le seul statut possible dans la dropdown du bouton est le statut courant

**Comment by tomolimo** [comment]
Bonjour  Yllen
Je vais refaire un test lundi et te je te tiendrai au courant.
Merci
Tomolimo


-------- Original message --------
From: yllen
Date:18/12/2015 18:38 (GMT+01:00)
To: glpi-project/glpi
Cc: "Moron, Olivier"
Subject: Re: [glpi] Adding a new followup permits to change ticket status even if no rights (#330)


Vous vous etes déconnecté parès avoir changé le cycle de vie du profil ?
Je viens de refaire un test et le seul statut possible dans la dropdown du bouton est le statut courant

**Comment by tomolimo** [comment]
Bonjour Yllen,
J'ai refait un test ce matin et c'est tout bon. J'avais en fait un pb avec le décodage du tableau 'ticket_status' de mon profil...
Merci,
A+
Tomolimo

**Comment by kokno** [comment]
Hello,

I’m having a similar issue here. Even though profile is correctly set to avoid status change and only current status is displayed in the follow up, adding a new followup is putting ticket from Pending to Old status (New or processing). Did someone also have this issue ?

**Comment by cedric-anne** [comment]
@kokno 

This is issue was closed 6 years ago, and is probably different from yours.

Please open a new issue and give us all requested informations.

Regards
