### ISSUE TITLE
Tickets are automatically not getting attached to agents

### ISSUE THREAD

**Issue by manideepanchoori** [glpi-project/glpi#3319]
Hi Team,

I have created some Assets and I have assigned that particular Asset to our support agent. But when End User raises a ticket for that asset that ticket is not getting attached to support agent.

**Comment by pVesian** [comment]
Hi @manideepanchoori, please give us more details like:

- your GLPI version
- screenshots of the asset and ticket
- system information: go to Setup -> General -> System
- etc

Thanks

**Comment by trasher** [comment]
No feedback, closing
