### ISSUE TITLE
[9.2.1] A pop-up notification is ampty

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3321]
Hello, 
A pop-up notification of SLA comment don't display:

![glpi - tickets - 56 - google chrome 2017-12-20 09 12 05](https://user-images.githubusercontent.com/17082164/34194992-6d09e9c8-e56c-11e7-9e33-86f880c81f92.png)

----

![glpi - sla - 3 - google chrome 2017-12-20 09 14 43](https://user-images.githubusercontent.com/17082164/34194999-6fa1de34-e56c-11e7-9c1b-7cfe6559456f.png)

GLPI 9.2.1 (/glpi-test2 => /var/www/glpi921) Installation mode: TARBALL

Operating system: Linux glpi 4.4.0-97-generic # 120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 PHP 7.0.22-0ubuntu0.16.04.1 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, 	apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, uploadprogress, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="512K"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at glpi.gomain.ru Port 80) 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.20-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: root@localhost/glpi921 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /var/www/glpi921/config : OK /var/www/glpi921/files : OK /var/www/glpi921/files/_dumps : OK /var/www/glpi921/files/_sessions : OK /var/www/glpi921/files/_cron : OK /var/www/glpi921/files/_graphs : OK /var/www/glpi921/files/_lock : OK /var/www/glpi921/files/_plugins : OK /var/www/glpi921/files/_tmp : OK /var/www/glpi921/files/_cache : OK /var/www/glpi921/files/_rss : OK /var/www/glpi921/files/_uploads : OK /var/www/glpi921/files/_pictures : OK /var/www/glpi921/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi921/lib/htmlawed) phpCas version 1.3.5 in (/var/www/glpi921/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/glpi921/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/glpi921/vendor/simplepie/simplepie/library) TCPDF version 6.2.13 in (/var/www/glpi921/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi921/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi921/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi921/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi921/vendor/sabre/vobject/lib)

**Comment by trasher** [comment]
SLA display was not designed to display comments; but since this is not coherent with other displays, I'm OK to change that.
