### ISSUE TITLE
0.90  amélioration helpdesk

### ISSUE THREAD

**Issue by sebfun** [glpi-project/glpi#333]
Bonjour
Dans GLPI 0.90 quand on est sur le site support (helpdesk) et quand on veut créer un nouveau ticket. Lorsque l'on a le formulaire à disposition et qu'on veut choisir un utilisateur (d'une liste Active Directory par exemple) et une catégorie, une popup s'ouvre et mouline légèrement pour afficher une liste de la base.
Une fois que je choisis mon utilisateur ou ma catégorie la page se met à rafraichir toute seule (elle se recharge).
Je me demandais s'il n'était pas possible d'avoir la liste des utilisateurs (AD) et des catégories toujours proposés dans les listes ad hoc mais sans que la page ne se rafraichisse car on perd un temps important pour ces 2 opérations.
Par contre j'ai remarqué que la liste SLA affiche bien la totalité des éléments de la base sans avoir à recharger la page quand on en sélectionne un.
Je fais beaucoup de support téléphonique et je vous assure qu'à la fin de la journée ce ne sont pas quelques secondes perdues mais des dizaines de minutes (je tourne entre 75 à 125 tickets par jour).
J'ai regardé dans Configuration Générale puis Assistance je n'ai rien trouvé.

Sinon rien à redire sur cet excellent outil qu'est GLPI :) merci aux dev qui ont fait un boulot énorme

**Comment by tomolimo** [comment]
Bonjour Sebfun,

Voici des réponses  à tes questions :

1)      Sur la liste déroulante des utilisateurs : le chargement de la liste dépend d’un paramétrage de GLPI : menu ‘Administration’ sous-menu ‘General’ -> onglet ‘General Setup’ et option : ‘Page size for dropdown (paging using scroll)’. Si tu mets une valeur basse (comme 10) cela moulinera très courtement. Ne mets pas 0 (car cela chargera la liste complète des utilisateurs et par la suite on ne peut plus le changer…sinon dans la base de données), mieux vaut mettre une petite valeur comme 10 et ensuite chercher en tapant le nom. Et si on veut pouvoir chercher il faut mettre dans ‘Don't show search engine in dropdowns if the number of items is less than’ une valeur inférieure ‘Page size dropdown’ (par exemple : 5).

2)      Le ‘refresh’ de la page est obligatoire à cause du choix de la catégorie qui peut demander le chargement d’un template (gabarit), et de ce fait modifier les champs en profondeur (champs pré-remplis, obligatoires, masqués…).


Merci de ton retour,
Cordialement

Olivier MORON
GLPI Development

RAYNET SAS
Tel : +33 476 33 4952
Fax: +33 4 76 70 56 63

**Comment by sebfun** [comment]
Bonjour

Merci pour la réponse.
En fait je voulais dire que la liste des utilisateurs pourrait être préchargée car oui on peut changer le temps d'affichage de la liste mais quand on a plus 200 utilisateurs à chercher c'est un peu long d'autant qu'il en affiche environ 50 par 50 (sauf si on peut modifier cela ? mais je n'ai pas vu dans le menu Administration).
L'idée c'est que je puisse saisir l'utilisateur (en l'occurence provenant d'un Active Directory) sans que la page ne se recharge. Donc pour un meilleur confort on va dire, je peux modifier le page size for dropdown et mettre une valeur forte ainsi il me laissera la possibilité de saisir un nom d'utilisateur (idem pour la catégorie)

Pour la réponse n° 2 : oui mais je ne comprends pas pourquoi il n'y a pas de refresh pour le choix du SLA (qui peut comporter des dizaines de possibilités) alors qu'il y en a pour la catégorie ?

Merci et bon courage

**Comment by yllen** [comment]
1. Ouvrir la dropdown et ne pas s'occuper du contenu. Taper le nom de l'utilisateur dans la zone au-dessus et cliquer sur le résultat
2. Une catégorie peut introduire l'utilisation d'un nouveau gabarit de ticket. Donc le rafraichissement est obligatoire.

**Comment by orthagh** [comment]
1. J'appuis la réponse du dessus, la meilleure solution est d'utiliser le champs de recherche intégré dans la liste déroulante.

2. j'ajouterais que sur un changement d'utilisateur, l'entité du ticket peux changer.
Donc il n'est pas possible à l'heure actuelle de se passer du rechargement de la page.

je ferme donc

**Comment by sebfun** [comment]
Je me permets de revenir vers vous pour avoir une explication.
J'ai bien compris ce que vous avez répondu en revanche ce que je ne comprends pas c'est que si la catégorie peut introduire un nouveau gabarit cela devrait être le cas avec la catégorie quand on en sélectionne une dans la création d'une nouvelle FAQ dans la base de connaissance ? Or, quand je réalise la même manipulation (c'est-à-dire la sélection d'une catégorie), la page ne se rafraîchit pas dans la page de création d'une FAQ dans la base de connaissance alors qu'elle se rafraîchit pour la création d'un nouveau ticket.

Merci d'avance de m'éclairer car j'avoue que je m'y perds et j'aimerais vraiment pouvoir gagner du temps entre les rafraîchissements de page et le temps de saisir l'utilisateur concerné.

**Comment by tomolimo** [comment]
Sauf qu'il n'y a pas de template (gabarits) possible pour la base de connaissance.
voir les dropdowns (ticket category) dans lesquels on peut définir un gabarit par catégori de ticket et par type (incident ou demande), mais pas de gabarit prévu pour la base de connaissance.

**Comment by sebfun** [comment]
Bonjour
Désolé de vous relancer je reviens à la charge.
J'ai bien pris en considération votre réponse mais quand on ajoute le plugin More tickets on peut donc clôturer / résoudre un ticket en même temps qu'on le saisit dans l'interface helpdesk ce qui est très pratique surtout pour des petits problèmes.

Lors de la saisie de ce ticket je choisis donc "Résolu" et j'obtiens un encadré me proposant de choisir un gabarit de solution, je choisis parmi les gabarits de solution et là la page n'est pas rafraîchit. Pourtant il y a des gabarits de solutions ainsi que des gabarits de type de solution ?
Merci pour vos explications et désolé de vous relancer mais j'aime bien comprendre.

Sébastien

**Comment by tomolimo** [comment]
La gestion interne d'un ticket et d'une solution n'est pas identique : 
1) Ticket : objet principal pouvant héberger des onglets (donc des infos chargées en ajax). Lui-même chargeable uniquement par refresh de la page (je pense : raison historique)
2) Solution : sous-objet (si je peux m'exprimer ainsi:)) d'un ticket chargé en ajax dans un onglet (donc potentiellement rechargeable en ajax)
cordialement,
Tomolimo

**Comment by sebfun** [comment]
ah ok très bien merci j'aurais tout tenté :)
