### ISSUE TITLE
[9.2] Add the "Group" action in "Rules for assigning an item to an entity"

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#3332]
Add the "Group" action in "Rules for assigning an item to an entity" : 
![rule](https://user-images.githubusercontent.com/15138371/34217365-933c06e6-e5ab-11e7-9c12-7d4c625b98f7.png)

**Comment by wawax** [comment]
Hi,
This rule engine is designed to "assign an entity to an item". I suggest that you take a look at the following feature of GLPI 9.3 : business rules for assets https://github.com/glpi-project/glpi/pull/3330
If some things are missing, feel free to contribute to it.

**Comment by tsmr** [comment]
You can also affect a location with this engine rules. 

So why not use it for a affect a group ? Only for next 9.2 release & for 9.3 we use the new business rules.

**Comment by wawax** [comment]
Affecting a location with a rule engine that is designed to assign an entity to an asset, is IMHO, a mistake.
The rules engine is not designed to that.
Depending on my time, I shall try to move the location action to the new engine.
For GLPI 9.2, I suggest that you maintain your own patch, as I'm against including it.
