### ISSUE TITLE
Operatingsystems  Info Unavailable From REST  V 9.2.1 

### ISSUE THREAD

**Issue by databang-io** [glpi-project/glpi#3334]
Hi,
I have an issue with the rest  API in 9.2.1.

The REST API Documentation states that we could retrive the following keys from a Computer object . 

    "operatingsystems_id": "Ubuntu 15.04",
    "operatingsystemversions_id": "15.04",
    "operatingsystemservicepacks_id": " ",
    "os_license_number": null,
    "os_licenseid": null,

But wen performing the following request :

http://glpi/apirest.php/Computer/?expand_drodpowns=true&with_infocoms=true&with_documents=true

I have none of those fields in my response . 
I also have issues with the ?expand_drodpowns=true option witch has no effect on my response .

Bernard

**Comment by chenjeff622** [comment]
the same problem . how to get operation system information?

**Comment by kartnico** [comment]
Hello,

I have the same problem with the following request : 

`https://path/to/glpi/apirest.php/Computer/$id`

(where $id is computer id). I don't have "operatingsystems_id".

My components versions : 
`CentOS Linux release 7.4.1708 (Core)`
`httpd.x86_64 2.4.6-67.el7.centos.2`
`mariadb.x86_64 5.5.56-2.el7`
`php.x86_64 7.2.5-1.el7.remi`
`glpi.noarch 9.2.3-1.el7.remi`
`glpi-fusioninventory.noarch 9.2.0.2.0-1.el7.remi`

Regards,

Nicolas

**Comment by kartnico** [comment]
Hi,

I have the same problem problem after update to GLPI 9.3.1

My Fusioninventory plugin version is 9.3+1.1 (I test with and without this plugin, and I have also the problem).

My Request : https://path/to/glpi/apirest.php/Computer/$id

``
"is_recursive": 0,
	"date_creation": "2017-10-26 22:31:00",
	"id": 3,
	"entities_id": 2,
	"name": "test",
	"serial": "",
	"otherserial": "",
	"contact": "",
	"contact_num": "",
	"users_id_tech": 0,
	"groups_id_tech": 0,
	"comment": "",
	"date_mod": "2017-11-27 17:06:34",
	"autoupdatesystems_id": 0,
	"locations_id": 0,
	"domains_id": 1,
	"networks_id": 0,
	"computermodels_id": 0,
	"computertypes_id": 0,
	"is_template": 0,
	"template_name": null,
	"manufacturers_id": 0,
	"is_deleted": 0,
	"is_dynamic": 0,
	"users_id": 0,
	"groups_id": 0,
	"states_id": 0,
	"ticket_tco": 0,
	"uuid": "",
	"links": [
		{
			"rel": "Entity",
			"href": "https://path/to/glpi/apirest.php/Entity/2"
		},
``

**Comment by trasher** [comment]
Operating systems are on their specific object now; this is no longer part of the computers table. Try querying on `Item_OperatingSystem` with `Computer` as itemtype and computers id as `items_id`.
