### ISSUE TITLE
[9.2.1] Browser notification doesn't work in Google Chrome

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3341]
Hello,
browser ajax notifications don't work in Google Chrome 63 (at the moment: 63.0.3239.108)

![glpi - notifications](https://user-images.githubusercontent.com/17082164/34296703-d60db26a-e724-11e7-8d6d-d585f64bbdba.png)

---------

GLPI 9.2.1 (/glpi-test2 => /var/www/glpi921) Installation mode: TARBALL

Operating system: Linux glpi 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 PHP 7.0.22-0ubuntu0.16.04.1 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, 	apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, uploadprogress, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="512K"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at glpi.domain.ru Port 80) 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0 Server Software: (Ubuntu) 	Server Version: 5.7.20-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: root@localhost/glpi921 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /var/www/glpi921/config : OK /var/www/glpi921/files : OK /var/www/glpi921/files/_dumps : OK /var/www/glpi921/files/_sessions : OK /var/www/glpi921/files/_cron : OK /var/www/glpi921/files/_graphs : OK /var/www/glpi921/files/_lock : OK /var/www/glpi921/files/_plugins : OK /var/www/glpi921/files/_tmp : OK /var/www/glpi921/files/_cache : OK /var/www/glpi921/files/_rss : OK /var/www/glpi921/files/_uploads : OK /var/www/glpi921/files/_pictures : OK /var/www/glpi921/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi921/lib/htmlawed) phpCas version 1.3.5 in (/var/www/glpi921/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/glpi921/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/glpi921/vendor/simplepie/simplepie/library) TCPDF version 6.2.13 in (/var/www/glpi921/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi921/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi921/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi921/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi921/vendor/sabre/vobject/lib)

LDAP directories ----

Not active

Way of sending emails: SMTP (anonymous@mail.dom.ru)

Name: 'glpi@dom.ru' Active: Yes 	Server: '{mail.dom.ru/imap/ssl/novalidate-cert}' Login: 'domain\user-glpi' Password: Yes

fusioninventory      Name: FusionInventory                Version: 9.2+1.1    State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.6      State: Enabled 	archires             Name: Network Architectures          Version: 2.4.1      State: Enabled 	timezones            Name: Timezones                      Version: 2.2.0      State: Enabled 	browsernotification  Name: Браузерные уведомления Version: 1.1.9      State: Enabled 	timelineticket       Name: Временные шкалы заявок Version: 9.2+1.0    State: Not activated 	consumables          Name: Заказ расходных материалов Version: 1.3.0      State: Enabled 	racks                Name: Конфигурация стойки    Version: 1.8.0      State: Enabled 	reports              Name: Отчет                          Version: 1.11.0     State: Enabled 	purgelogs            Name: Очистка истории            Version: 1.3.0      State: Enabled 	dashboard            Name: Панель отчетов              Version: 0.8.9      State: Enabled 	pdf                  Name: Печать в PDF                   Version: 1.3.0      State: Enabled 	mreporting           Name: Подробные отчеты          Version: 1.4.0      State: Enabled 	news                 Name: Уведомления                   Version: 1.3.4      State: Enabled 	order                Name: Управление заказами    Version: 1.9.6      State: Enabled

**Comment by AircraftRu** [comment]
![glpi - notification queue - 275 - mozilla firefox 2017-12-27 11 21 14](https://user-images.githubusercontent.com/17082164/34375569-413f2060-eaf8-11e7-82df-aeb82669b782.png)
---
![glpi - notification queue - mozilla firefox 2017-12-27 11 21 37](https://user-images.githubusercontent.com/17082164/34375570-42c7ef3e-eaf8-11e7-86c7-399fee1ae5df.png)

When I send it myself:
![glpi - notification queue - mozilla firefox 2017-12-27 11 22 05](https://user-images.githubusercontent.com/17082164/34375571-445872b0-eaf8-11e7-8f34-1d7a5951a48c.png)

**Comment by Armin83** [comment]
In my Testsystem it works with chrome Version 63.0.3239.132 (Offizieller Build) (64-Bit)

BUT !!!
I have first to configure chrome setting for notification. The first request to get the authorization like in the version before or firefox don't work at the moment.

**Comment by AircraftRu** [comment]
Oddly, I have only sound. If I allow notifications from my domain site, it happens nothing in the same version.

**Comment by Armin83** [comment]
You have sound ? o:O

1. Clean complete Browser Cache & Restart Browser Check again
2. If possible reset complete browser setting do you have this with any client or only one ? (check again)

**Comment by AircraftRu** [comment]
Other people also have this problem. It worked before. It looks like problem in Google Chrome. I check it.

**Comment by AircraftRu** [comment]
@Armin83 
No. nothing helps me. This is problem with glpi because push-notices work on other websites.

**Comment by AircraftRu** [comment]
Hi!
It works by HTTPS and webite issues a request to get the authorization but I don't know a reason why it doesn't work by HTTP.

**Comment by fgendorf** [comment]
Because Notifications is only supported by HTTPS in google chorme. press
ctrl + shift + j and see warning

_________________________
Frederico Gendorf

**Comment by Armin83** [comment]
Can't find it in the console but you are right. @AircraftRu please close the issue or is your glpi site https ?

https://developers.google.com/web/fundamentals/push-notifications/

> Note: Unless you're using localhost, the Push API requires HTTPS.

**Comment by C-Duv** [comment]
For anyone stepping on this issue from a search engine and looking on how to enable browser notifications on GLPI v9.2:
Go to `/front/setup.notification.php`, set the "_Enable followups via ajax calls_" field ("_Activer les suivis via appels ajax_") to Yes and Save using the "_Save_" button.
A new "_Ajax followups configuration_" ("_Configuration de l'ajout de suivis_") link (pointing to `/front/notificationajaxsetting.form.php`) should now be available on the right panel of the page which allows to configure sound, frequency and icon.
