### ISSUE TITLE
[9.2.1] No picture in FAQ for post only users

### ISSUE THREAD

**Issue by usrqmor** [glpi-project/glpi#3343]
Hello,

I checked if it was already a subject about it but I didn't find one. 
When I create a new article in the knowledge bas, then I checked with an user account, I see the article but not the picture in it.
When  I try to open the picture, I get a message that say "Unauthorized access to this file".
![image](https://user-images.githubusercontent.com/17316903/34302080-a5a6cf5c-e72f-11e7-89c9-a5d8148c33ed.png)

I don't see how to give the access to the post only users. 

Can you help me ? 

Thanks.

**Comment by omesquita** [comment]
I'm having same problems.

**Comment by ddurieux** [comment]
Try with this patch https://github.com/glpi-project/glpi/pull/3141/files

**Comment by usrqmor** [comment]
Hi @ddurieux,

Thanks for the reply.
I apply the patch but the problem is still here. I create another post in my FAQ but it doesn't work. 
I do some tests with the same account with differents profile and I find something.

When I look at the post with a profile with the simplified interface, I can't see the picture.
But when I use the same user and a profile whith standard interface, I have any problem.

I think there's a problem with the right on the document for the simplified interface.

Thanks

**Comment by allanlopesprado** [comment]
#3292

**Comment by CDA39** [comment]
Hi  @ddurieux , @usrqmor 

I have test this patch https://github.com/glpi-project/glpi/pull/3141/files


For me , i have the same problem than @usrqmor  .

When I look at the post with a profile with the simplified interface, I can't see the picture.
But when I use the same user and a profile whith standard interface, I have any problem.

Thanks

**Comment by arthurrschaefer** [comment]
#3292 Fixed the problem with images pasted inside followups. But the images pasted in FAQ items are not working so far.
The Simplified interface users can't see the images.

![image](https://user-images.githubusercontent.com/13874922/36537814-fe0bdc54-17af-11e8-9680-46d4ae1a2032.png)

**Comment by usrqmor** [comment]
Yes I confirm this point. There's no change for the FAQ.
