### ISSUE TITLE
[0.90.1]Security die. trying to load an forbidden class

### ISSUE THREAD

**Issue by Tamalou** [glpi-project/glpi#3344]
Hello,
For a moment, I encounter this type of error on some users: when I want to display all the tickets of a user, some tickets are displayed but for those who are older I have the message Security die ....
It seems that this comes from an update of GLPI but nothing is sure.
After inspecting the logs and the various forums, I did not solve the problem.

Thanks for your help.
![000085](https://user-images.githubusercontent.com/34807956/34325507-c0ca579e-e893-11e7-83c2-284b649d0673.png)

**Comment by JAlvergne** [comment]
Information about system installation and configuration
--
[code]   GLPI 0.90.1 (/glpi => C:\wamp\www\glpi)

Operating system: Windows NT SSA01GLPI3 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) AMD64 PHP 5.4.12 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, calendar, com_dotnet, ctype, 	curl, date, dom, ereg, fileinfo, filter, ftp, gd, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, 	mysqlnd, odbc, pcre, pdo_mysql, pdo_sqlite, session, soap, standard, tokenizer, wddx, xdebug, xml, xmlreader, xmlwriter, zip, 	zlib) Setup: max_execution_time="0" memory_limit="-1" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.4 (Win64) mod_authnz_sspi/0.1.0 PHP/5.4.12 () 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 Server Software: MySQL Community Server (GPL) 	Server Version: 5.6.12-log 	Server SQL Mode: NO_ENGINE_SUBSTITUTION 	Parameters: glpi@localhost/glpi 	Host info: localhost via TCP/IP 	 C:\wamp\www\glpi/config : OK C:\wamp\www\glpi/files : OK C:\wamp\www\glpi/files/_dumps : OK C:\wamp\www\glpi/files/_sessions : OK C:\wamp\www\glpi/files/_cron : OK C:\wamp\www\glpi/files/_graphs : OK C:\wamp\www\glpi/files/_lock : OK C:\wamp\www\glpi/files/_plugins : OK C:\wamp\www\glpi/files/_tmp : OK C:\wamp\www\glpi/files/_rss : OK C:\wamp\www\glpi/files/_uploads : OK C:\wamp\www\glpi/files/_pictures : OK C:\wamp\www\glpi/files/_log : OK

htmLawed version 1.1.20 in (C:\wamp\www\glpi\lib\htmlawed) phpCas version 1.3.4 in (C:\wamp\www\glpi\lib\phpcas) PHPMailer version 5.2.8 in (C:\wamp\www\glpi\lib\phpmailer) ZetaComponent ezcGraph installed in (C:\wamp\www\glpi/lib/zeta/Base):  OK Zend Framework version 2.4.9 in (C:\wamp\www\glpi\lib\Zend) SimplePie version 1.3.1 in (C:\wamp\www\glpi\lib\simplepie) TCPDF version 6.2.12 in (C:\wamp\www\glpi\lib\tcpdf) ircmaxell/password-compat in (C:\wamp\www\glpi\lib\password_compat). Compatitility: Ok

Server: 'X.X.X.X', Port: 'XXX', BaseDN: 'OU=UtilisateursXXXX,dc=X,dc=X,dc=X', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'XXXX', Use TLS: 		none

Not active

Way of sending emails: SMTP (XXX@X.X)

 

manufacturersimports Name: Imports fabricants             Version: 1.6.0      State: New 	datainjection        Name: Injection de fichiers          Version: 2.3.1      State: Not installed 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.2.1      State: Enabled 	purgelogs            Name: Purge de l'historique          Version: 0.84       State: Not activated

Host: XXX Connection: OkUse the OCSNG software dictionary: No

**Comment by Tamalou** [comment]
Somebody have an idea, please ?

**Comment by trasher** [comment]
0.90 is no longer supported. This issue is certainly solved in a more recent release; consider upgrading.
