### ISSUE TITLE
email Notifications are not working 

### ISSUE THREAD

**Issue by manideepanchoori** [glpi-project/glpi#3345]
Hi All,

When am trying to test the email notification it was showing like "Fail to send test email to administrator".

Can anyone suggest what to do here.

Thanks in advance.

**Comment by usrqmor** [comment]
Hello,

Did you check Mail server's configuration ?
It's in Setup -> Notifications -> Email followups configuration.

**Comment by manideepanchoori** [comment]
Yes by default it was given like admsys@localhost I changed it to manideep.anchoori@mydomain.com. But it is not working.

**Comment by usrqmor** [comment]
You must have something like that in your Email Notification :
![image](https://user-images.githubusercontent.com/17316903/34374346-0ac3d66e-eae1-11e7-8d22-4ec3622c6054.png)


Can you check if your SMTP server send the mail ?

**Comment by manideepanchoori** [comment]
Hai Thanks for your reply, I am using Microsoft Office 365 and I have given all the required information shown in your screen shot. Even though when am trying to send test mail to administrator. It was getting failed.

**Comment by trasher** [comment]
You may find extra information in the mail-error log file (>= 9.2); or in your mail server logs.

**Comment by manideepanchoori** [comment]
Hi, Thanks for the reply, I have seen in mail-error log file. It was showing like 
"the email was undeliverable to manideepanchoori@domain.com"

**Comment by trasher** [comment]
Mail error messages may be hard to understand, but most of the time, you have precisions on why this could not be delivered (domain does not exists, mailbox does not exists for the domain or has been disabled or is full, ...)

This is not a GLPI issue, but either a server configuration issue or a mail server one.
