### ISSUE TITLE
[9.2.2] Suivis GLPI reçus en double

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#335]
Bonjour,

Dans notre configuration, les nouveaux suivis _publics_ sont envoyés par mail aux demandeurs sur un ticket. Lorsqu'un demandeur répond à un mail émis par GLPI, il crée un nouveau suivi _public_ avec le contenu de son mail. Le champ "Source de la demande" est placée à la valeur "E-mail".

Notre problème : le demandeur reçoit par e-mail le contenu de son suivi. Cependant, selon moi, on ne reçoit pas ses propres suivis dans GLPI. Il y a donc un comportement anormal.

De plus, si j'ajoute un suivi public sur un ticket dont je suis le demandeur en mettant "Source de la demande" à "E-mail", je ne reçois pas mon suivi.

Pouvez-vous regarder cet aspect ?

**Comment by yllen** [comment]
Un demandeur ne reçoit pas ses propres actions s'il l'a demandé dans ses préférences.
Vérifier le paramètre "Notifications pour mes changements"

**Comment by nqb** [comment]
Bonjour,
Malgré ce paramétrage qui est défini à "Non" dans la configuration générale de GLPI, les utilisateurs reçoivent tout de même leurs propres suivis.

Quels éléments puis-je fournir pour un diagnostic plus approfondi ?

**Comment by SylvainGuibert** [comment]
Au niveau des personnes notifiés tu as quoi ? (glpi en mode debug, puis onglet debug sur le ticket)

**Comment by nqb** [comment]
Bonjour,
Voici le contenu de l'onglet "Debug" après l'émission d'un suivi :
```
Nouveau suivi	Demandeur	Ticket_FOO (fr_FR)	nqbtest2@foo.fr
```
L'utilisateur nqbtest2@foo.fr est le demandeur sur mon ticket. 

Si je regarde le fichier "mail.log", j'observe ceci :
```
2015-12-22 11:22:56 [8@helpdesk3]
Un email a été envoyé à nqbtest2@foo.fr : [CHREDON #0008092] Scénario 3 << Émission du suivi "public"
[..]
2015-12-22 11:24:59 [8@helpdesk3]
Un email a été envoyé à nqbtest2@foo.fr : [CHREDON #0008092] Scénario 3 << Suivi reçu en double
```
Le contenu de l'onglet "Historique" sur mon ticket :
```
10149532	2015-12-22 11:24	cron_mailgate	Suivi	Ajout d'un élément : Suivi (13490)
10149531	2015-12-22 11:21	NQB (8)	        Suivi	Ajout d'un élément : Suivi (13489)
```
En faisant une corrélation des heures, on voit clairement le scénario :
1. Émission d'un suivi public vers le demandeur à 11h21
2. Réponse du demandeur à 11h24
3. Émission du suivi du demandeur vers lui même à 11h24
Si je me connecte en tant que demandeur à GLPI, la préférence "Notification pour mes changements" est à la valeur "Non".

Version de GLPI utilisée : 0.90.1.

**Comment by nqb** [comment]
Bonjour,
Avez-vous trouvé quelque chose ?

**Comment by btry** [comment]
Suite à un échange avec @nqb 

il y a bien une différence de comportement entre 
- l'utilisateur ajoute un suivi via l'interface de GLPI 
- l'utilisateur répond à un mail de suivi

Dans le 1er cas  l'utilisateur ne reçoit aucun mail.
Dans le 2e cas l'utilisateur reçoit 2 mails .

Dans les 2 cas de figure, le paramètre "Notifications pour mes changements" du compte utilisateur est bien à "Non"

**Comment by yllen** [comment]
Je viens de refaire un test et je ne reproduis pas.
J'ai bien répondu à un mail émanant de GLPI, mon suivi a bien été créé dans mon ticket mais je n'ai reçu aucun mail.

**Comment by yllen** [comment]
ah si j'ai reçu 1 mail mais 1 seul

**Comment by yllen** [comment]
Bon je viens de vérifier le code.
Le paramètre pour notifier ou non l'utilisateur de ses changements n'est valable que pour les actions dans l'interface.
Dans le cas de l'envoi d'un mail, c'est un cron qui travaille et nous n'avons pas les préférence de l'utilisateur car celui-ci n'est pas connecté.

**Comment by nqb** [comment]
D'accord.
Peut-on récupérer cette préférence en base de données en se basant sur l'adresse mail destinatrice ?

**Comment by yllen** [comment]
Non. La définition de l'envoi ou non est faite au moment de la génération de l'évènement, donc on a pas le destinataire.

**Comment by nqb** [comment]
Dans ce cas, comment peut-on gérer au mieux ce cas de figure ?

Avez-vous une solution de contournement en attendant une évolution ?

Merci.

**Comment by yllen** [comment]
Le paramètre n'est pris en compte que pour les actions dans l'interface simplifiée.
Aucune parade sans revoir tout le système de notification.

**Comment by nqb** [comment]
Bonjour,

Est-ce que ce point peut être revu dans le cadre de la version 9.1 ? J'ai toujours le défaut sur la version Git.

**Comment by nqb** [comment]
Bug toujours présent en 9.2.1

**Comment by cedric-anne** [comment]
I am closing it in favor of #4643, more recent, and containing technical explaination of the bug.
