### ISSUE TITLE
IT seems glpi dont load documents from the good path

### ISSUE THREAD

**Issue by 4n63lu5** [glpi-project/glpi#3352]
When i try to add an document from an already uploaded file. It seems that glpi try to load it from  _tmp and not from _uploads.

May be the solution is change in inc/document.class.php in function moveUploadedDocument

$fullpath = GLPI_TMP_DIR."/".$filename;
By
$fullpath = GLPI_UPLOAD_DIR."/".$filename;

 GLPI 9.1.6 ( => /home/web_apps/glpi/ht-docs)

Server

Operating system: Linux infv0011 4.13.0-1-amd64 #1 SMP Debian 4.13.13-1 (2017-11-16) x86_64
PHP 7.0.26-1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="512M" safe_mode="" session.save_handler="files"
	upload_max_filesize="1024M" 
Software: Apache/2.4.29 (Debian)
	Mozilla/5.0 (Android 5.1; Tablet; rv:57.0) Gecko/57.0 Firefox/57.0
Server Software: Debian buildd-unstable
	Server Version: 10.1.29-MariaDB-6
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/home/web_apps/glpi/conf : OK
OK/home/web_apps/glpi/data : OK
OK/home/web_apps/glpi/dump_db : OK
OK/home/web_apps/glpi/data/_sessions : OK
OK/home/web_apps/glpi/data/_cron : OK
OK/home/web_apps/glpi/data/_graphs : OK
OK/home/web_apps/glpi/data/_lock : OK
OK/home/web_apps/glpi/data/_plugins : OK
OK/home/web_apps/glpi/data/_tmp : OK
OK/home/web_apps/glpi/data/_rss : OK
OK/home/web_apps/glpi/data/_uploads : OK
OK/home/web_apps/glpi/data/_pictures : OK
OK/home/web_apps/glpi/log : OK

Libraries
htmLawed version 1.1.21 in (/home/web_apps/glpi/ht-docs/lib/htmlawed)
phpCas version 1.3.5 in (/home/web_apps/glpi/ht-docs/vendor/jasig/phpcas/source)
PHPMailer version 5.2.23 in (/home/web_apps/glpi/ht-docs/vendor/phpmailer/phpmailer)

**Comment by lufik** [comment]
I have the same problem. However I'm not sure what is wrong (as tmp should be cleaned periodically).
However the combination in document.class.php (in function moveUploadedDocument):

      $fullpath = GLPI_TMP_DIR."/".$filename;
      $filename = str_replace($prefix, '', $filename);

      if (!is_dir(GLPI_UPLOAD_DIR)) {
         Session::addMessageAfterRedirect(__("Upload directory doesn't exist"), false, ERROR);
         return false;
      }

Seems definitely as a bug (same as the function descrition).
The change breaks plugins so I hope somebody answer if TMP or UPLOAD directory is the right one.

**Comment by trasher** [comment]
The path is correct. Document is stored in temp directory then moved i upload dir (if checks success).
I made some tests on current stable (9.2.2), and cannot reproduce. Please provide detailled steps to reproduce the issue if it's still relevant.

**Comment by lufik** [comment]
I tested it now and you're right the problem is not present in 9.2.2 anymore. I'm sorry there were a bug in 9.1.6
https://github.com/glpi-project/glpi/blob/2683ce0cfe4cce4786e52eec3cf2a54f54f01225/inc/document.class.php

      $fullpath = GLPI_UPLOAD_DIR."/".$filename;

      if (!is_dir(GLPI_UPLOAD_DIR)) {
         Session::addMessageAfterRedirect(__("Upload directory doesn't exist"), false, ERROR);
         return false;
      }

I took the code from newer version last time :( I'm sorry for the confusion.

**Comment by 4n63lu5** [comment]
the problem still exist in glpi 9.2.2for mae , more precisely the problem exist when i use the "Sélectionner un fichier installé par FTP" from the "front/document.form.php" to add a new document.
