### ISSUE TITLE
Glpi 9.2 - global search criterion fails

### ISSUE THREAD

**Issue by mohierf** [glpi-project/glpi#3358]
It looks like #371 is back with most recent 9.2 version.

When adding a global search criterion (eg. a software characteristics) in the global computers search it cannot be removed anymore ...

[edit]: note that only the last criterion cannot be removed ... if more than one criterion is used, only the last one remains always present

**Comment by mohierf** [comment]
Anyone has an idea about this problem ?

**Comment by orthagh** [comment]
regression in https://github.com/glpi-project/glpi/commit/2ef32303b3955f168275731b2308aa1fb9957c05#diff-a801c52129f44d50ab6d1db9f049c4b7L5202

``criteria`` -> ``$key``

**Comment by mohierf** [comment]
Ok @orthagh and what is to be done ? I do not understand ...

**Comment by orthagh** [comment]
not my comment was for reference only, i suggested a fix in your pr
