### ISSUE TITLE
Use PSR-12 coding standards

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#3366]
GLPI coding standards are very specific; we may use something more common (see https://github.com/glpi-project/docdev/issues/62).

Even if PSR standards are not perfect; it is widely used; and current standards are not perfect neither :)

**Comment by trasher** [comment]
Work has begun on master. To make things simplier, and stay compatible with 9.4 as long as possible, we've decided not to switch to PSR for all current codebase, but only for new classes in the src directory.

**Comment by trasher** [comment]
https://www.php-fig.org/psr/psr-12/

**Comment by cedric-anne** [comment]
Done in #10095 .
