### ISSUE TITLE
Error in associated elements in items to show list

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#3367]
Hello,

I found a strang behaviour. When I add multiple associated elements in a ticket : 

![image](https://user-images.githubusercontent.com/12936546/34521046-ea413a8e-f08b-11e7-9f58-e5464cdf73a2.png)

The result in items to show is not the same (?!?) : 

![image](https://user-images.githubusercontent.com/12936546/34521060-06941350-f08c-11e7-912f-30a8f8ca0375.png)

When I entered my ticket, the items are however correct. It's like a random function in list. Anyone has this behaviour ? 

Thanks

**Comment by ciadch** [comment]
A track here, the id are the same : 
/front/computer.form.php?id=1291
/front/networkequipment.form.php?id=1291

**Comment by trasher** [comment]
Just tested with current 9.2/bugfixes branch, cannot reproduce. I guess this has been fixed

**Comment by ciadch** [comment]
Hi @trasher,

Thanks for your return. I'll test it in version 9.2.2, seems to be good now too. 

Let's see in future releases

**Comment by Armin83** [comment]
@trasher do you need examples ?
I have this bug with 9.2.3. (Ticket created with 9.2.3)
I don't have this with all tickets. In my cases i have 2 Computers and 1 monitor linked with the ticket.

Debug mode on - no new error in the logs.
