### ISSUE TITLE
Category not replaced in closed tickets

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#3368]
Version GLPI : 9.1 & 9.2

When I delete a category by replacing with another, closed tickets related to this category don't change.

In the ticket, ID of the category present is that of the old category.

Is this normal?

**Comment by amma35** [comment]
no opinion on the subject?

**Comment by trasher** [comment]
Referencing a category id that n longer exists is not a normal behavior, no.

**Comment by amma35** [comment]
This change solves the problem.

In the class ticket.class.php and the function prepareInputForUpdate() : 

```
diff --git a/inc/ticket.class.php b/inc/ticket.class.php
index 91f91eb63..2c1494851 100644
--- a/inc/ticket.class.php
+++ b/inc/ticket.class.php
@@ -1064,6 +1064,7 @@ class Ticket extends CommonITILObject {
 
             // probably transfer
             $allowed_fields[] = 'entities_id';
+            $allowed_fields[] = 'itilcategories_id';
          } else {
             if ($this->canApprove()
                 && isset($input["status"])) {
```

Is that okay with you? 
I'm doing a PR?

**Comment by trasher** [comment]
Yes, open a pull request please. It would be interesting to add a unit test as well.

**Comment by amma35** [comment]
For which version? 9.2 ?

**Comment by trasher** [comment]
yep :)

**Comment by amma35** [comment]
OK
I'll try for the tests.
You need a ticket update test or a dropdown move test?

**Comment by trasher** [comment]
A ticket update I guess. Ping me if you need help with tests.
