### ISSUE TITLE
[0.90.1] Collecteur Mail : Unknown: Invalid mailbox list

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#337]
Nous avons récemment migré en 0.90.1, jusque-là tout vas bien !
Nous utilisons le collecteur mail depuis quelques temps sans difficulté, même après le passage en 0.90.1.
Hier intégration du plugin "FormCreator" en version 1.3.3. Depuis ce moment [je pense] le collecteur mail ne fonctionne plus correctement. Dans les logs PHP de GLPI j'ai l'erreur suivante : 

2015-12-22 09:29:06 [8@NOM_DU_SERVEUR]
  *** PHP Notice(8): Unknown: Invalid mailbox list: [your-email] (errflg=3)
  Backtrace :
  
Coté configuration du collecteur rien a changé, je peux le lancer à la main, il me dit qu'il y'a X e-mails de présent et que la récupération se passe correctement, mais aucun ticket n'est créé. [Nombre de messages : disponibles=3, récupérés=3, refusés=0, erreurs=0, en liste noire=0]

Coté action automatique, elle fonctionne correctement, la tâche "mailgate" fonctionne correctement.

**Comment by tomolimo** [comment]
Bonjour,
Et si tu désactives le plugin Form ?
Que se passe-t-il?

**Comment by SylvainGuibert** [comment]
Je viens de faire le test, même problème, donc  la "coïncidence" avec le plugin "formcreator" n'est pas avéré. 

Même messages d'erreur dans les logs php

**Comment by tomolimo** [comment]
Est-ce que l'on peut avoir le backtrace complet ?

**Comment by SylvainGuibert** [comment]
Voici la backtrace complète lorsque je lance manuellement la récupération via l'action automatique "mailgate" : 

2015-12-22 13:13:32 [8@NOM_DU_SERVEUR]
  *** PHP Notice(8): Unknown: SECURITY PROBLEM: insecure server advertised AUTH=PLAIN (errflg=1)
  Backtrace :
  :
2015-12-22 13:13:32 [8@NOM_DU_SERVEUR]
  *** PHP Notice(8): Unknown: Invalid mailbox list: [your-email] (errflg=3)
  Backtrace :
  :
2015-12-22 13:13:32 [8@NOM_DU_SERVEUR]
  *** PHP Notice(8): Unknown: Invalid mailbox list: [your-email] (errflg=3)
  Backtrace :
  :

**Comment by tomolimo** [comment]
Ce pourrait-il que la paramétrage du serveur est changé ?

**Comment by SylvainGuibert** [comment]
Le paramétrage coté serveur n'a pas changé.

**Comment by tomolimo** [comment]
Pour moi il y a un pb de connection au serveur (param GLPI, réseau, param serveur,...)
Il va falloir tout vérifier.
Et pour commencer voici un fichier PHP pour vérifier l'aspect connection serveur.

    <?php
    // author: Olivier Moron
    // Test of imap connection and email fetch 
    //
    $imap = imap_open("{servername/pop/novalidate-cert/tls}", "username", "userpassword");
    if( $imap ) {  
         //Check no.of.msgs
         $num = imap_num_msg($imap);
         //if there is a message in your inbox
         if( $num >0 ) {
             //read that mail recently arrived
             echo imap_qprint(imap_fetchheader($imap, 1, FT_PREFETCHTEXT ));
             echo imap_qprint(imap_body($imap, 1, FT_PEEK));
          }
          imap_close($imap);
     }
    ?>

of course servername has to be replaced by real serveur FQDN, username by user login, and user password by user password. You may also replace the complete connection string wth your on paramaters {servername/imap/....} .

regards,
Tomolimo

**Comment by SylvainGuibert** [comment]
Merci pour les retours très rapide !
Je viens de mettre le fichier en place, en adaptant les différents paramètres.
Lors du test, la page se charge, puis reste "blanche".
Aucune erreur coté PHP pour le coup, comment interpreter ce résultat ?

**Comment by tomolimo** [comment]
euh, pardon j'aurais dû le dire : c'est un script, et pas non une page web...

**Comment by SylvainGuibert** [comment]
autant pour moi ........ voici le retour : 

PHP Fatal error:  Call to undefined function imap_open() in /var/www/glpi/test.php on line 5

Dans le php.ini, l'extension est bien activée : extension=imap.so

**Comment by tomolimo** [comment]
peux-tu taper la commande "php -m" et me dire le résultat ?

**Comment by tomolimo** [comment]
et "php -v"

**Comment by SylvainGuibert** [comment]
php -v : 
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

php -m 
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
date
dba
dom
ereg
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
json
ldap
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by tomolimo** [comment]
Apparemment le module imap n'est pas chargé ...

**Comment by tomolimo** [comment]
Il doit y avoir quelque chose qui empèche son chargement...

**Comment by SylvainGuibert** [comment]
Merci je vais regarder dans les logs coté Php. Mais c'est quand même étonnant qu’au niveau de GLPI le collecteur ne me remonte aucune erreur, et surtout, il me donne bien l'information du nombre de mails qu'il a récupérés. Cependant les tickets ne sont pas créés.

**Comment by tomolimo** [comment]
est-ce vraiment le nombre d'emails ?

**Comment by SylvainGuibert** [comment]
Oui, la valeur remonté est correcte. J'ai testé, la suppression d'un mail directement dans la b.a.l, et le nombre de mail traités par le collecteur est à n-1 ce qui me fais dire qu'il lit correctement la b.a.l.

**Comment by tomolimo** [comment]
Peux-tu refaire un essai avec le script que j'ai envoyé ?
en changeant la ligne de l'imap_open comme suit : 
    
    imap_open(servername, userlogin, userpassword, CL_EXPUNGE, 1, array('DISABLE_AUTHENTICATOR' => 'GSSAPI'));

merci.

**Comment by SylvainGuibert** [comment]
Je viens de recharger le module imap dans php (php5enmod imap + restart de apache)
Je lance le script php pour tester la connexion. Il me renvoie bien une partie du premier mail présent dans la b.a.l, suivi des erreurs suivantes : 


PHP Notice:  Unknown: SECURITY PROBLEM: insecure server advertised AUTH=PLAIN (errflg=1) in Unknown on line 0
PHP Notice:  Unknown: Invalid mailbox list: [your-email] (errflg=3) in Unknown on line 0
PHP Notice:  Unknown: Invalid quoted-printable sequence: =UTF-8
X-PHP-Originating-Script: 33:class-phpmailer.php
 (errflg=3) in Unknown on line 0

**Comment by tomolimo** [comment]
et avec la modif proposée ?

**Comment by tomolimo** [comment]
n'empèche cela ressemble à l'erreur des logs GLPI : "SECURITY PROBLEM": bof bof bof

**Comment by tomolimo** [comment]
cela pourrait venir de la chaine de connection serveur "{.....}" il faudrait fairte des tests comme cela:
{servername/pop} uniquement (pas de SSL, pas de certificat)

**Comment by tomolimo** [comment]
c'est ce l'on a chez nous : une chaine très simple: {FQDN_servername/pop}

**Comment by SylvainGuibert** [comment]
Avec la modification il n'arrive pas à ouvrir le stream :

PHP Warning:  imap_open(): Couldn't open stream SERVEURNAME in /var/www/glpi/test.php on line 5
PHP Notice:  Unknown: Can't open mailbox SERVEURNAME : no such mailbox (errflg=2) in Unknown on line 0

**Comment by tomolimo** [comment]
et avec une chaine de connection simple ?

**Comment by SylvainGuibert** [comment]
la chaine que j'utilise est la suivante : {FQDN_servname/imap} donc je peux pas faire plus simple ...

**Comment by tomolimo** [comment]
essayes /pop à la place d'imap

**Comment by SylvainGuibert** [comment]
le service pop, n'est pas disponible sur nos serveurs de messagerie...donc pas de test possible avec pop .... (Connection Refused au niveau du serveur)

**Comment by tomolimo** [comment]
donc essayes avec une chaine plus longue :
{servername/imap/novalidate-cert/tls}

**Comment by SylvainGuibert** [comment]
je viens tester avec la chaîne de connexion suivante : {servername/imap/novalidate-cert/notls}, j'obtient le même message d'erreur que précédemment : 

PHP Notice:  Unknown: SECURITY PROBLEM: insecure server advertised AUTH=PLAIN (errflg=1) in Unkwn on line 0
PHP Notice:  Unknown: Invalid mailbox list: [your-email] (errflg=3) in Unknown on line 0
PHP Notice:  Unknown: Invalid quoted-printable sequence: =UTF-8
X-PHP-Originating-Script: 33:class-phpmailer.php
 (errflg=3) in Unknown on line 0

**Comment by tomolimo** [comment]
bon alors je sèche :(
il faudrait regarder les logs coté serveur 
peut-être tester avec un client imap et espionner les trames pour voir les options qui vont bien

**Comment by tomolimo** [comment]
peut-être un peu de recherche sur google ?

**Comment by tomolimo** [comment]
puisqu'il semble que cela ne soit pas un pb lié à GLPI

**Comment by SylvainGuibert** [comment]
Je vais tenter de googler, je poste la suite de mes recherches ici .... Merci !!

**Comment by tomolimo** [comment]
Bonjour,
Est-ce qu'un client comme Thunderbird arrive à se connecter correctement sur le serveur de mails ?
Est-ce qu'il serait possible d'espionner le traffic réseau entre les deux ?
Mieux encore : serait-il possible de l'installer sur le serveur GLPI afin de vérifier que depuis celui-ci ce client arrive à se connecter correctement sur le serveur de mails ?
merci,
Cordialement,
Tomolimo

**Comment by SylvainGuibert** [comment]
J'ai recherché concernant les erreurs ... je ne trouve pas grand chose. Pour répondre à tes question : 
-> Pour le client mail, la réponse est oui
-> Le serveur GLPI est installé sur la même machine, et il arrive bien à se connecter à la bal puisque dans les logs du collecteur le nombre de mails "récupéré" correspond bien au nombre de mails présent dans la bal. En revanche le ticket qui est censé être crée après récupération n'est pas crée.
-> Pour le traffic réseau, oui c'est possible, mais je pense que ça va apporter peu d'informations.

**Comment by tomolimo** [comment]
j'ai aussi googlé et pas trouvé rand chose non plus si ce n'est que il semble 'nomal' d'avoir cette erreur à la connection...

http://stackoverflow.com/questions/9766203/suppress-bogus-php-imap-open-notice-insecure-server-advertised-auth-plain

Donc il semblerait que le problème serait plus loin lors de la récupération du corps du premier message.
Je suis d'accord pour le traffic : je ne suis pas sûr que cela apporte grand chose (c'est en désespoire de cause....)

Autre piste : http://www.developpez.net/forums/d1292285/php/langage/fonctions/authentification-imap/

**Comment by tomolimo** [comment]
Eventuellement il faudrait tester la connection avec un client imap simplifié.

Ou même carrément en telnet : http://www.anta.net/misc/telnet-troubleshooting/imap.shtml

**Comment by SylvainGuibert** [comment]
-> Merci de compatir :+1: 
-> Pour l'erreur d'authentification en texte plain, j'ai constaté la même chose.
-> Lorsque je fais le test avec une bal vide, le seul message d'erreur php affiché est celui concernant l'authentification (qui pour moi n'empêche pas le fonctionnement).
-> Par contre je pense à un problème de charset dans le mail qui lui poserai problème, je dis ça car dans l'erreur la dernière ligne est la suivante (toujours avec le script PHP) : 
PHP Notice:  Unknown: Invalid quoted-printable sequence: ="=_alternative 0024301                 5C1257F24_="
MIME-Version: 1.0
X-KeepSent: 2BED9615:CD3C (errflg=3) in Unknown on line 0
PHP Notice:  Unknown: Invalid quoted-printable sequence: =_alternative 00243015C                 1257F24_=
 (errflg=3) in Unknown on line 0t="ISO-8859-1"

**Comment by tomolimo** [comment]
autre lien pour test imap à partir de telnet : https://support.microsoft.com/en-us/kb/189326

**Comment by tomolimo** [comment]
et un autre (très clair): http://documents.made-it.com/imapcmd.html

**Comment by SylvainGuibert** [comment]
Merci pour tous les liens...

J'ai testé plusieurs choses, et n'arrivant toujours pas à me connecter en ligne de commande au serveur imap...je me suis dit... il y'a une chose que je n’ai pas faite.... redémarrer la tâche Imap du serveur mail.....(Domino). 
Après redémarrage, je test avec le script et je n'ai plus l'erreur cité deux postes plus haut. Simplement l'avertissement concernant l'authentification non sécurisée.
Je regarde coté GLPI : Le ticket est créé correctement !
Donc le problème ne venait, ni de GLPI, ni de PHP, mais de la tâche IMAP du serveur mail qui ne devait pas fonctionner correctement !

Ce que je n'explique pas, c'est pourquoi PHP n'arrivait pas à lire les mails correctement et que le le client thunderbird, n'avait aucun problème...

Merci pour la réactivé et l'aide apporté @tomolimo ! :+1:

**Comment by tomolimo** [comment]
de rien, peux-tu fermer le topic ?

**Comment by SylvainGuibert** [comment]
bien évidemment !

RESOLUTION : Redémarrage de la tâche IMAP du serveur mail !
