### ISSUE TITLE
[9.2.1] changed global view, now can't see phones

### ISSUE THREAD

**Issue by loriharshbarger1991** [glpi-project/glpi#3377]
I am getting near the end of switching over from GLPI 0.80.5 to 9.2.1. I was able to see everything successfully until I edited the global view. Now I am not able to view the phones portion of the database. I can see computers, printers, and basically everything else. Can somebody point me in the right direction of where I need to look? The order I had the view in is Name, Brand, Location, Status, Manufacturer, Inventory Number, Serial Number, Type, Model, Group, User, Alternate username, Alternate username number, purchase date, and last update.

**Comment by trasher** [comment]
Check GLPI logs, there is probably something wrong.  You say you have "brand" (among other) field in global view; this sounds strange since tis field is not available from global view fields.

**Comment by trasher** [comment]
No feedback, closing.
