### ISSUE TITLE
item_operatingsystem.php not found

### ISSUE THREAD

**Issue by Rico29** [glpi-project/glpi#3379]
hello
using latest git version, branch 9.2.
Hosts informations are retieved via FusionInventory plugin.
when going in an host description, I have, for many hosts, 2 operating systems : the real one, and one like "(170)". I can not remove this dummy operating system. (may concern FusionInventory)

When trying to list operating system, link points to "https://<glpi>/front/item_operatingsystem.php", but page does not exist.

Regards,
Cédric

**Comment by AnaelMobilia** [comment]
Hello @Rico29 

For the duplicate OS, it seem to be [an FusionInventory issue](https://github.com/fusioninventory/fusioninventory-for-glpi/issues/2376)
I try to reproduce your issue, but wasn't able to...
Could you, please, add a few more details (URL of the page, screenshoot, ...) ?

![image](https://user-images.githubusercontent.com/6187125/34651432-88885ee2-f3d0-11e7-9282-f2eea34677ef.png)

Regards,
Anael

**Comment by Rico29** [comment]
Hello @AnaelMobilia 
Here are the screenshots

![selection_006](https://user-images.githubusercontent.com/12935571/34662263-974e0f38-f44f-11e7-8891-7e54d5a3f95d.png)

I'm unable to delete the '(157)' (actions > delete permanently > post). No error given (neither in apache logs ) but the '(157)' OS is still here.

Regards,

**Comment by trasher** [comment]
You should not have two OS on a same computer; the workaround when you get this bug is to drop entries in the items_operatingsystems table (ones without any *_id related).
You can also empty the table and wait for inventories to fill data again.

**Comment by nqb** [comment]
@trasher : on 9.2/bugfix nightly build, I can reproduce this issue.

File `item_operatingsystem.php` doesn't exist in `GLPI_ROOT/front` but `item_operatingsystem.form.php` exists : 
```
[/var/www/glpi/front]: $ ls item_*
item_ticket.form.php
item_project.form.php
item_problem.form.php
item_operatingsystem.form.php          <<<<< 
item_devicesoundcard.form.php
item_devicesimcard.form.php
item_devices.form.php
item_devicesensor.form.php
item_deviceprocessor.form.php
item_devicepowersupply.form.php
item_devicepci.form.php
item_devicenetworkcard.form.php
item_devicemotherboard.form.php
item_devicememory.form.php
item_deviceharddrive.form.php
item_devicegraphiccard.form.php
item_devicegeneric.form.php
item_devicefirmware.form.php
item_devicedrive.form.php
item_devicecontrol.form.php
item_device.common.form.php
item_devicecase.form.php
item_devicebattery.form.php

```
Maybe you forgot a `.form` in filename.

**Comment by serger138** [comment]
Hello,
I have the same trouble. If I look at a systemoperating, ex "front/item_operatingsystem.form.php?id=4863" and I go to "liste", I got the same error  : "The requested URL /front/item_operatingsystem.php was not found on this server." I can't list all my operating system in GLPI
