### ISSUE TITLE
[0.85.5] User in simplified interface can delete ticket

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#338]
When editing a ticket (ticket.form.php) a user with simplified GUI has, next to the "Save" button, a button "Put in dustbin".

This should not be, since the permissions of the simplified interface have no option for deleting a ticket like the standard interface, where you have such a possibility.

If the user clicks on the button "Put in dustbin", the ticket is also actually flagged as deleted (value of glpi_ticket.is_deleted is set to 1). Ironically, an admin in our installation cannot delete tickets, so he has less rights than a regular user.

**Comment by rickyweb** [comment]
We had one case in 0.90.1 where a ticket has been unexpectedly deleted by a user, so there still might be an issue here. However I haven't been able to reproduce it yet.

**Comment by orthagh** [comment]
It works as intended, a self-service user can update and delete his own tickets as long as a technician assign or update it

This to permit to correcting errors in ticket (update) or finally to remove an invalid or unecessary.
