### ISSUE TITLE
Reservation Tab glpi 9.2.1

### ISSUE THREAD

**Issue by Miudon** [glpi-project/glpi#3381]
Hi,
After update to 9.2.1 version, the tab Reservation (reservationitem.php) doesn´t show any reservable item.
The tab Administration in the same screen is ok.
If I click on Show All, the screen shows Calendar and all reservable itens.
Thanks in advance

**Comment by AnaelMobilia** [comment]
Hello @Miudon 

Could you, please, check on the asset, than in teh reservation tab that reservations are currently active for this asset ?
![image](https://user-images.githubusercontent.com/6187125/34651716-eb47ed7e-f3d3-11e7-9699-6b1d551f60c5.png)

If you make available a new asset (which wasn't reservable before update), will it appears correctly on the reservation tab ?

From which version did you upgrade ?

Regards,
Anael

**Comment by Miudon** [comment]
Hi,

Thanks for your help!
Asset is active for reservation.
If I active reservation on new asset, that appear only on tab
administration, like the others.
I've update from 9.1.1 to 9.2.1 directly

Are there any other verification to do?

Thanks in advance

**Comment by Armin83** [comment]
In reservation tab you see only the items from your entity active. i don't know if this is normal but i think so.

**Administration --> all**
![2018-01-16 21_37_47-glpi - reservations](https://user-images.githubusercontent.com/19192087/35011208-aafb1708-fb05-11e7-8873-aa6ab7d9bd0c.png)

**Reservation**
![2018-01-16 21_37_55-glpi - reservations](https://user-images.githubusercontent.com/19192087/35011209-ab205a4a-fb05-11e7-8713-9b90000c01c8.png)

**Reservation with search filter**
![2018-01-16 21_38_11-glpi - reservations](https://user-images.githubusercontent.com/19192087/35011210-ab3fee1e-fb05-11e7-9c1c-ab6aa6ea303f.png)

**Comment by Miudon** [comment]
Hi Armin83, 
I think that is the correct way and it was ok until i've updated.

Enviado do meu iPhone

**Comment by Armin83** [comment]
I tested on http://demo.glpi-project.org with 9.2.1

**Comment by DeedJayB** [comment]
I have the exact same issue 
https://github.com/glpi-project/glpi/issues/3280
Like Miudon, it's not a clean install, i have upgraded GLPI from a previous version but from version 9.2 (I think)
I know I had one warning during the install but I don't think that is the problem.

**Comment by Armin83** [comment]
I searched again and:
If the recursive items are you problem then now i think it is a bug and solved in next version see #3409

Please close this case if solved.

**Comment by DeedJayB** [comment]
I have the exact same issue 
https://github.com/glpi-project/glpi/issues/3280
Like Miudon, it's not a clean install, i have upgraded GLPI from a previous version but from version 9.2 (I think)
I know I had one warning during the install but I don't think that is the problem.

**Comment by DeedJayB** [comment]
I checked this problem and it's not the same problem. My assets and users are in the same Entity.

**Comment by trasher** [comment]
I've just tested on 9.2/bugfixes branch; and I do not reproduce the issue.
