### ISSUE TITLE
Plan a GUI update ? Use bootstrap ?

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#3392]
Hello the team,

After checking CSS files, I found that we have really many "historical" code which could be still used or not...
Too, many tweaks was made in order to get specific browsers compliance (eg [style.css](https://github.com/glpi-project/glpi/blob/master/css/styles.css#L3539)).

On future plans, is planified a migration to a maintained GUI framework as bootstrap (or other) ?
Imo, it would be on the same way of minds than #1605 .

A huge advantage will be browsers compliance managed by an external team which provide more time for the GLPI team to dev core.
Too, we will have advantages of updates for new (versions of) browsers without coding it ourself ;-)

I suggest bootstrap for this use for the following reasons : 
  - [Browsers compatibility](https://getbootstrap.com/docs/4.0/getting-started/browsers-devices/) following GLPI's browsers compatibility
- This framework is already used in telemetry (so teclib already have knowledges on this -> maintenability in times)
- Provide a mobile compatibility at costless...
- Standardize a little more the GLPI' project... which is a good thing in times :)
- As DBIterato #1143, remove echo #1605, PSR-2 #3366  ... it's a big change, so the time to think about it is coherent ;-)

Regards,
Anael

**Comment by orthagh** [comment]
it's a good question, i'm not sure about boostrap itself but yes separate views is a topic often discussed and a (big) step before adopt a css framework.

**Comment by trasher** [comment]
See also https://github.com/glpi-project/glpi/issues/4594

**Comment by cedric-anne** [comment]
See #8365 .
