### ISSUE TITLE
Translate front/helpdesk.php

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#3397]
Hello,

The file [front/helpdesk.php](https://github.com/glpi-project/glpi/blob/master/front/helpdesk.php) is hard coded in french.
We need to add some translations string on transifex.

I dunno how to do this.

Regards,
Anael

**Comment by trasher** [comment]
To solve missing translations, you just have to replace hardcoded strings with their gettext methods (`__('My string')` and so on) equivalent with english text.
Anyways, I'm not sure this file is still used.

**Comment by orthagh** [comment]
duplicate #3432

**Comment by orthagh** [comment]
for information, will be fixed in 9.2.2
