### ISSUE TITLE
Approval of the solution

### ISSUE THREAD

**Issue by alanjra** [glpi-project/glpi#340]
When the technician solves a ticket and this ticket was created by him, the Approval view is shown to him.

![image](https://cloud.githubusercontent.com/assets/13873115/11960964/97eb92ca-a8bc-11e5-92fc-01438290d81a.png)

The Approval view should be shown only to the the requester?

I checked the Validation permission and do not have any permmission to the profile. 

![image](https://cloud.githubusercontent.com/assets/13873115/11961183/091a0afc-a8be-11e5-8f86-e31d382ee81e.png)

**Comment by tomolimo** [comment]
Yes, I agree with you: that's also a problem for us...

**Comment by tomolimo** [comment]
Hello,
This is not only for the survey, it's also for the "Solution Approval". The writer/creator of the ticket must not be able to approve the solution, only the requester should be able to do it. Otherwise, we've got Technicians doing the complete life-cycle of the tickets.
Thank you,
Regards,
Tomolimo

**Comment by ladenree76000** [comment]
I disagree, in some case (ie : call center)  technician could ask the requester "do you approve solution?") and approve for the requester. also for the survey.
it would be a problem for me if requester can not call our call center to approve.

**Comment by tomolimo** [comment]
It should be managed by a right in profiles.

**Comment by ladenree76000** [comment]
:+1:  for management with rights

**Comment by yllen** [comment]
For a call center, the techician create the ticket, approve it and reply to satisfaction survey.
We now have a right for satisfaction survey.
Can we use this right to approve solution too? (i will change the name of the parameter: approve solution and reply to survey)

**Comment by ladenree76000** [comment]
"Can we use this right to approve solution too?".
I would answer YES.
