### ISSUE TITLE
Missing or incorrect device type called!

### ISSUE THREAD

**Issue by gmourani** [glpi-project/glpi#3404]
* Steps to reproduce (which actions have you made) :
Clicking on the "Components" link.

* Expected result :
Have the page appears.

* Actual result :
Blank page!
Get -> PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Missing or incorrect device type called!' in /var/www/html/glpi/front/device.php:36\nStack trace:\n#0 {main}\n  thrown in /var/www/html/glpi/front/device.php on line 36, referer: https://192.168.2.227/glpi/front/dropdown.php

* URL of the page :
https://192.168.2.227/glpi/front/device.php

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.1
Operating system: Linux glpi.dev.lan 2.6.32-696.el6.x86_64 #1 SMP Tue Mar 21 19:29:05 UTC 2017 x86_64
PHP 5.6.32 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, apc, apcu, bz2, ctype, curl, date, dom,
	ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysql, mysqli, openssl,
	pcntl, pcre, pdo_mysql, pdo_sqlite, posix, session, snmp, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlrpc, xsl, zip, zlib)
Setup: max_execution_time="180" memory_limit="512M" post_max_size="192M" safe_mode="" session.save_handler="files"
	upload_max_filesize="128M" 
Software: Apache ()
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7
Server Software: Source distribution
	Server Version: 5.1.73
	Server SQL Mode: 
	Parameters: glpi_user@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
APCu extension is installed
xmlrpc extension is installed
Zend OPcache extension is not present
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
OKSELinux mode is Permissive
Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect --> off (Some features may require this to be on)
Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect_db --> off (Some features may require this to be on)
Some features may require this to be onSELinux boolean configuration for httpd_can_sendmail --> off (Some features may require this to be on)

**Comment by orthagh** [comment]
ref 804ad7d1820  (maybe)

Hello @gmourani, Could you precise where you found the "Components" link ?

**Comment by trasher** [comment]
ping?

**Comment by trasher** [comment]
No ffedback, closing
