### ISSUE TITLE
9.2.1: Planned end date and Real end date not working

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#3407]
Hi, each **Planned end date** and **Real end date** are the same even that **Planned start date** and 
**Real start date**

![image](https://user-images.githubusercontent.com/6815687/34773890-8b7a6ce6-f60d-11e7-9bfa-803afe026a8d.png)

**Comment by Sismic** [comment]
even if i modify date in database, same result, may be in php code but i'm not a specialist for php language.

**Comment by Sismic** [comment]
Good morning, i test again and all apears OK this time ....Sorry for bad feedback.

**Comment by orthagh** [comment]
Ok :smile: 
Let us know if it triggers again
