### ISSUE TITLE
Profile image upload problem

### ISSUE THREAD

**Issue by vihuarar** [glpi-project/glpi#341]
Hi...

We are trying to upload images for the help desk member's, but sometimes the photos cant be upload

Both images has the extension (JPG)

We made a test, we tried to upload 2 images)
One image has the size 43.8kb (this image was uploaded without problems)
and the otherone  91kb (cant be uploaded)

Some images cant be uploaded, but we cant identify when the problem occurs

PHP is configured to recieve files biggers than 2 MB

**Comment by tomolimo** [comment]
Hello
What's the error message?
Thank you
Tomolimo


-------- Original message --------
From: vihuarar
Date:23/12/2015 17:41 (GMT+01:00)
To: glpi-project/glpi
Subject: [glpi] Profile image upload problem (#341)


Hi...

We are trying to upload images for the help desk member's, but sometimes the photos cant be upload

Both images has the extension (JPG)

We made a test, we tried to upload 2 images)
One image has the size 43.8kb (this image was uploaded without problems)
and the otherone 91kb (cant be uploaded)

Some images cant be uploaded, but we cant identify when the problem occurs

PHP is configured to recieve files biggers than 2 MB

**Comment by vihuarar** [comment]
![problem](https://cloud.githubusercontent.com/assets/1976384/11981444/9f1b1930-a970-11e5-9cde-dce60777b7f8.jpg)

**Comment by tomolimo** [comment]
Could you please switch to English and send a screen shot?
I can speak French and English, but for other languages I've got some troubles ☺.
Thank You


-------- Original message --------
From: vihuarar
Date:23/12/2015 18:28 (GMT+01:00)
To: glpi-project/glpi
Cc: "Moron, Olivier"
Subject: Re: [glpi] Profile image upload problem (#341)


[problem]<https://cloud.githubusercontent.com/assets/1976384/11981444/9f1b1930-a970-11e5-9cde-dce60777b7f8.jpg>

**Comment by vihuarar** [comment]
This is the message in english "ENGLISH
Potential upload attack or file too large. Moving temporary file failed."

**Comment by tomolimo** [comment]
Hello 
Could you post the pict file too?
I'll try it on my own server. 
Could you zip it before posting? 
Could you also post GLPI config (for this go to 'General' and 'System')?
Thank you 
Regards 
Tomolimo

**Comment by rickyweb** [comment]
I've had this problem too. The problem is that the extension JPG (in capital letters) is not allowed. If you upload the very same image with the extension jpg, it will work.

**Comment by vihuarar** [comment]
thanks for the advice... I think another users are getting confused...

**Comment by 1993nikhil** [comment]
I am having same problem in uploading image in profile . It is not working with small glpi also @rickyweb

**Comment by yvesholenstein** [comment]
I agree with 1993nikhil. Have the same issues. Picture is displayed in profile screen as if the file did not exist. Error message when trying to access the "src=" path direcly with e.g.
http://glpi.company.local/front/document.send.php?file=_pictures/9a/336_5805d35d2829a_min.jpg

says: "Unauthorized access to this file"

Looking into document.send.php I see the following code which could be the reason:

`if (isset($_GET['docid'])) { // docid for document
   if (!$doc->getFromDB($_GET['docid'])) {
      Html::displayErrorAndDie(__('Unknown file'), true);
   }

   if (!file_exists(GLPI_DOC_DIR."/".$doc->fields['filepath'])) {
      Html::displayErrorAndDie(__('File not found'), true); // Not found

   } else if ($doc->canViewFile($_GET)) {
      if ($doc->fields['sha1sum']
          && $doc->fields['sha1sum'] != sha1_file(GLPI_DOC_DIR."/".$doc->fields['filepath'])) {

         Html::displayErrorAndDie(__('File is altered (bad checksum)'), true); // Doc alterated
      } else {
         $doc->send();
      }
   } else {
      Html::displayErrorAndDie(__('Unauthorized access to this file'), true); // No right
   }

} else if ...`

If a "docid" is set and if `$doc->canViewFile($_GET)` is not true it will cause this error.

Any clues?
