### ISSUE TITLE
Search with All parameter

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3415]
http://forum.glpi-project.org/viewtopic.php?id=160164

*** MySQL query error:***
Error: Too many tables; MySQL can only use 61 tables in a join

**Comment by trasher** [comment]
I do not think the "all" entry is really usefull.

This error is a MySQL/MariaDB hard limitation; this can't be fixed. The only way to go would be to rework the whole search (and probably the schema as well).
