### ISSUE TITLE
Lien des pièces-jointes dans les tickets

### ISSUE THREAD

**Issue by Oyabi** [glpi-project/glpi#342]
Bonjour,
J'ai effectué la migration de notre installation glpi (parc.xxx.fr/glpi/) vers une nouvelle adresse (glpi.xxx.fr) afin d'harmoniser notre SI.
L'ancien site reste tout de même accessible pour le moment mais nous sommes confrontés à un problème.
En effet, lorsque nous uploadons une pièce-jointe dans un ticket sur l'ancien site celle-ci est inaccessible depuis le nouveau et je tombe sur une page m'indiquant tout simplement "Fichier introuvable".
Les configurations apaches sont les mêmes à une exception près (l'ancienne config ne possède pas de ServerName) .
Je n'ai rien dans les logs d'erreurs d'apache (ça marche quand je force une 404).
J'ai bien sur changé l'url dans Configuration -> Générale -> Adresse web de l'application par https://glpi.xxx.fr/

Je sèche complètement et j'en appelle donc à votre aide. Avez-vous une idée de ce qui pourrait causer ce problème svp ?
Cordialement.

**Comment by tomolimo** [comment]
Bonjour
Est ce que via le nouveau site vous pouvez uploader un doc ?
Si oui où est il mis sur le serveur ?
Est ce le même dossier que si le même doc est uploadé via l'ancien site ?
Cordialement
Tomolimo


-------- Original message --------
From: Oyabi
Date:24/12/2015 14:51 (GMT+01:00)
To: glpi-project/glpi
Subject: [glpi] Lien des pièces-jointes dans les tickets (#342)


Bonjour,
J'ai effectué la migration de notre installation glpi (parc.xxx.fr/glpi/) vers une nouvelle adresse (glpi.xxx.fr) afin d'harmoniser notre SI.
L'ancien site reste tout de même accessible pour le moment mais nous sommes confrontés à un problème.
En effet, lorsque nous uploadons une pièce-jointe dans un ticket sur l'ancien site celle-ci est inaccessible depuis le nouveau et je tombe sur une page m'indiquant tout simplement "Fichier introuvable".
Les configurations apaches sont les mêmes à une exception près (l'ancienne config ne possède pas de ServerName) .
Je n'ai rien dans les logs d'erreurs d'apache (ça marche quand je force une 404).
J'ai bien sur changé l'url dans Configuration -> Générale -> Adresse web de l'application par https://glpi.xxx.fr/

Je sèche complètement et j'en appelle donc à votre aide. Avez-vous une idée de ce qui pourrait causer ce problème svp ?
Cordialement.

**Comment by chnateag** [comment]
Bonjour,

Je viens de tester en mettant 2 fichiers textes différents contenant 2 chaines improbables "FFGHJRTMEKHAKGDHDHDFH" que j'ai uploadé sur chacun des domaines, résultat l'upload fonctionne bien sur les 2, et le fichier que j'upload sur glpi.xxx.fr nous génère la même erreur sur parc.xxx.fr.

J'ai l'impression que nos fichiers sont accessibles uniquement par le domaine ou on les uploads.
Par contre sur le serveur si je fait un grep sur mes 2 chaines de caractères, je trouve que le fichier qui a été upload depuis l'ancien domaine parc.xxx.fr 

On va chercher plus mais c'est intéressant deja !

**Comment by tomolimo** [comment]
Bonjour,
Je viens de vérifier dans la base de données : il n'y a aucun lien entre un nom de domaine et le chemin vers le document.
Quelle est la config utilisée (GLPI, serveur,...) ?
Quelles sont les redirections ou règles de ré-écritures utlisées ?
Quelles sont les URL utilisées lors de l'ouverture du document ?
A+
Tomolimo

**Comment by orthagh** [comment]
Bonjour.

En l'absence de réponse, je ferme ce ticket (pour laisser le backlog clean).
Si vous pensez votre problème toujours présent et valide, merci de réouvrir.
