### ISSUE TITLE
Logout from CAS user is broken

### ISSUE THREAD

**Issue by rrignier** [glpi-project/glpi#3424]
Hi !
I submit this issue from this thread in french forum : http://forum.glpi-project.org/viewtopic.php?id=158400

For whatever reason, glpiauthtype session variable is set to 3 (LDAP) insetead of  5 (CAS). I first tried to update authtype in user database withiut success.

------------
* Steps to reproduce (which actions have you made) :

GPLI home page redirect correctly to CAS login when it is activated.
After correct user connection, Logout returns to standard login without SSO logout.

* Expected result :

Use CAS logout Url when clicking on logout icon.

* Actual result :

Returns to local login page with ?noAUTO=1

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.2 (/glpi.stable => /var/www/html/glpi.stable)

**Comment by rrignier** [comment]
Thank you for the PR merge.  :thumbsup:

**Comment by nqb** [comment]
Test on GLPI 9.2.2 (nightly build), it works for me.

**Comment by remicollet** [comment]
Also needed on 9.1

**Comment by trasher** [comment]
Fixed in 9.1/bugfixes branch as well.
