### ISSUE TITLE
Documents eternaly loading... in entity view

### ISSUE THREAD

**Issue by Berrichon** [glpi-project/glpi#3426]
GLPI 9.1.7.1 (french)
Debian 9.3.0
PHP7

when trying to access to the document view of an entity object you should have a document manger and uploader
but it still loading and loading
in debug mode you obtain ::
Fatal error: Uncaught Error: Using $this when not in object context in /var/www/glpi/inc/db.function.php:1738 Stack trace: #0 /var/www/glpi/inc/document_item.class.php(674): getEntitiesRestrictRequest(' AND ', 'glpi_documents', '`glpi_documents...', Array, true) #1 /var/www/glpi/inc/document_item.class.php(583): Document_Item::showAddFormForItem(Object(Entity), 0, Array) #2 /var/www/glpi/inc/document_item.class.php(296): Document_Item::showForItem(Object(Entity), '') #3 /var/www/glpi/inc/commonglpi.class.php(483): Document_Item::displayTabContentForItem(Object(Entity), '1', '') #4 /var/www/glpi/ajax/common.tabs.php(97): CommonGLPI::displayStandardTab(Object(Entity), 'Document_Item$1', '', Array) #5 {main} thrown in /var/www/glpi/inc/db.function.php on line 1738

after investigation you just have to remove a "$this->" in the db.function.php located in glpi\inc folder of your installation line 1738 ::

if ($is_recursive) {
      $ancestors = array();
      if (isset($_SESSION['glpiactiveentities']) && $value == $_SESSION['glpiactiveentities']) {
         $ancestors = $_SESSION['glpiparententities'];
      } else {
         if (is_array($value)) {
            ******$ancestors = $this->getAncestorsOf("glpi_entities", $value);******
            $ancestors = array_diff($ancestors, $value);
         } else if (strlen($value) == 0 && isset($_SESSION['glpiparententities'])) {
            $ancestors = $_SESSION['glpiparententities'];

         } else {
            $ancestors = getAncestorsOf("glpi_entities", $value);
         }
      }

      if (count($ancestors)) {
         if ($table == 'glpi_entities') {
            $query .= " OR $field IN ('" . implode("','",$ancestors) . "')";
         } else {
            $recur = (empty($table) ? '`is_recursive`' : "`$table`.`is_recursive`");
            $query .= " OR ($recur='1' AND $field IN ('" . implode("','",$ancestors) . "'))";
         }
      }
   }

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/3288
