### ISSUE TITLE
item_update not work when change a group in ticket

### ISSUE THREAD

**Issue by hotdesc** [glpi-project/glpi#3428]
GLPI 9.2.1

When you update a ticket and change only the assigned group. The pre_item_update (ticket) is not called and thus the rules are not applied.

The big problem is that if you put a group-based SLA rule. You change the group and the call does not change the SLA.

**Comment by trasher** [comment]
Rules call and plugins hooks are not the same; so I do not understand what the problem is.

**Comment by trasher** [comment]
No feedback, closing.
