### ISSUE TITLE
simple helpdesk.php issues

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#3432]
![image](https://user-images.githubusercontent.com/418844/34943529-521e9308-f9fc-11e7-9b9c-048346c1d3c0.png)

- French language hardcoded
- some notices (no blocking btw)

**Comment by tyronewyatt** [comment]
Shouldn't the helpdesk.php anonymous ticket creation form include an optional email address field? 
This would recording the same details as an anonymous ticket from email.
Can create idea if you prefer.

**Comment by orthagh** [comment]
yeah this is feasible, open an issue on suggest.glpi-project.org for that (and a pull request if you want)

**Comment by tyronewyatt** [comment]
Sorry for the delay.
Created https://glpi.userecho.com/communities/1/topics/800-simple-helpdeskphp-include-email-field 
Thanks @orthagh
