### ISSUE TITLE
[9.2.1] class Rule - function prepareAllInputDataForProcess

### ISSUE THREAD

**Issue by gfernandez-me** [glpi-project/glpi#3435]
function prepareAllInputDataForProcess is never called

i need to change input data before send to process rules but prepareAllInputDataForProcess  is never called and i cant do anything with plugins

The function prepareInputDataForProcess doesn't have plugin hook

**Comment by cedric-anne** [comment]
Hi,

I search for history of this function. It has always been like that (added in commit https://github.com/glpi-project/glpi/commit/a2973731132c7ebbe3a652fc0471ddb2bf52fab5).
Maybe you could do something with the `ruleCollectionPrepareInputDataForProcess` hook, but I do not know well the rule system so I am not sure of that.

Regards
