### ISSUE TITLE
Error installing datainjection plugin

### ISSUE THREAD

**Issue by alexlp1982** [glpi-project/glpi#3438]
Greetings,

When trying to perform the installation of the plugin from the plugins module, the following error appears:

![captura1](https://user-images.githubusercontent.com/25614098/35015101-f627f798-fae0-11e7-9318-4dab12bb5b2c.PNG)

Trabajo en proceso...
Error durante el query a la base de datos: CREATE TABLE IF NOT EXISTS `glpi_plugin_datainjection_models` ( `id` int(11) NOT NULL auto_increment, `name` varchar(255) NOT NULL, `comment` text NULL, `date_mod` datetime NOT NULL default '0000-00-00 00:00:00', `filetype` varchar(255) NOT NULL default 'csv', `itemtype` varchar(255) NOT NULL default '', `entities_id` int(11) NOT NULL default '0', `behavior_add` tinyint(1) NOT NULL default '1', `behavior_update` tinyint(1) NOT NULL default '0', `can_add_dropdown` tinyint(1) NOT NULL default '0', `can_overwrite_if_not_empty` int(1) NOT NULL default '1', `is_private` tinyint(1) NOT NULL default '1', `is_recursive` tinyint(1) NOT NULL default '0', `perform_network_connection` tinyint(1) NOT NULL default '0', `users_id` int(11) NOT NULL, `date_format` varchar(11) NOT NULL default 'yyyy-mm-dd', `float_format` tinyint( 1 ) NOT NULL DEFAULT '0', `port_unicity` tinyint( 1 ) NOT NULL DEFAULT '0', `step` int( 11 ) NOT NULL DEFAULT '0', PRIMARY KEY (`id`) ) ENGINE=MyISAM CHARSET=utf8 COLLATE=utf8_unicode_ci - Error is Invalid default value for 'date_mod'

Try installing the fileinjection plugin versions 2.4.1 and 2.4.2

Installation:
-ubuntu-16.04.3-server-amd64
-GLPI Version 0.90.3
-PHP 5.6.
-mysql-server-5.7 

Regards.

**Comment by trasher** [comment]
Please report the bug on the plugin bug tracker

**Comment by legoniz** [comment]
same problem. Help, please.
