### ISSUE TITLE
All searches with "Serial number Contains NULL" fail with all assets

### ISSUE THREAD

**Issue by tabad** [glpi-project/glpi#3448]
This behaviour has been tested in GLPI v9.2.x and GLPI 9.1.x. To prove this here I'm going to use the [*official* GLPI demonstration system](http://demo.glpi-project.org/), nowadays based on GLPI 9.2.1.

> The following is an example with computer assets, but the same problem exists with all of them (monitors, network devices, devices, etc.).

## Computers with any serial number

This simple filter

```
             Characteristics - Name | Contains | ""
And Characteristics - Serial number | Contains | ""
```

shows all computers. There are thirteen computers; three of them with a serial number and ten without serial number.

![glpi-9 2 1-computers-with-any-serialnumber](https://user-images.githubusercontent.com/2183103/35142445-99668702-fcfe-11e7-9505-c3d912185cf8.png)

## Computers without serial number set or assigned

Now I want to know which computers do not have a serial number set. This is the filter.

```
             Characteristics - Name | Contains | ""
And Characteristics - Serial number | Contains | "NULL"
```

This filter doesn't show any computer and it should show ten computers. This is the first bug. 

![glpi-9 2 1-computers-with-serialnumber-equal-null](https://user-images.githubusercontent.com/2183103/35143399-b1b36606-fd01-11e7-9a2d-d6fcc1c6ef67.png)

## Computers with serial number set or assigned

Now I want to know which computers have a serial number set. This is the filter.

```
                 Characteristics - Name | Contains | ""
And Not Characteristics - Serial number | Contains | "NULL"
```

This filter shows all computers (the thirteen) and it should show only three of them. This is the second bug. 

![glpi-9 2 1-computers-with-serialnumber-distinct-null](https://user-images.githubusercontent.com/2183103/35143597-53b4eab0-fd02-11e7-8c11-3dc8a1db8168.png)

## Final comment

After detecting this behaviour with the field "Serial number", I have performed the same tests with other fields and I have verified that the error not only occurs with the field "Serial number" but it occurs with many others. Here are some of them.

  * Characteristics - Inventory number
  * Characteristics - UUID
  * Characteristics - Building number
  * Characteristics - Location comments
  * Characteristics - Comments
  * Etc.

Regards,

**Comment by tabad** [comment]
Hello,

This issue hasn't been labeled yet. I am almost certain this is a bug, a bug with with many and important ramifications. Please, could you label (or close, whether I'm wrong) this issue?. Could be this issue included in the next milestones 9.2.2 and 9.1.8?

Thanks in advance.

**Comment by orthagh** [comment]
Hello @tabad 

I don't replicate at all with my current version (pre 9.2.2) nor with 9.1.7 (last 9.1.x dev version) nor a 9.1.3 production instance.

Some things to check so:
- are your serial fields don't contains some spaces ?
- enable debug mode, and check generated queries (post it here, the last one), you should see parts like `` .`serial` IS [NOT] NULL``

**Comment by tabad** [comment]
Hello @orthagh,

Maybe you are right. I don't have a GLPI v9.2.1 working yet although I'm working on it. I have done all the proofs regarding v9.2.x with the *official* GLPI demonstration system (http://demo.glpi-project.org/), based on GLPI v9.2.1, with the assets of *Root entity > Entity A > Entity AA*. I have check neither computer has spaces in their field "Serial number". And sorry, I'm not able enable the debug mode on that system. The next monday I'm going to repeat the proofs with GLPI v9.1.2 & v9.1.6.

Regards,

**Comment by orthagh** [comment]
ok i replicate on my local instance
since a recent version, empty serials are set to "" instead of NULL.

I'm currently searching for a solution

**Comment by orthagh** [comment]
hum, i change my answer, the bug was always present since years.
The fact is the search "contains NULL" transform into ``field IS NULL`` in sql but created objects (from gui, with fusioninventory, it's ok) with empty  fields are set to 0 length strings (instead NULL) who don't match at all.

I'm not sure to be able to fix this issue

**Comment by orthagh** [comment]
ok i found a way, see attached pr below

**Comment by tabad** [comment]
Hello @orthagh,

Thank you for your time and your answer. I don't have clear a thing, is FusionInventory for GLPI  involved in this issue or it's only a GLPI issue?.

**Comment by orthagh** [comment]
it seems it's only glpi.
But i don't check computer created by FI.

BTW, the provided PR will fix the issue regarding the db content (NULL or "")
