### ISSUE TITLE
[0.90.1] La traduction des intitulés "casse" l'affichage des listes

### ISSUE THREAD

**Issue by ylegrand** [glpi-project/glpi#345]
Bonjour,

Je viens d'activer la traduction des intitulés. A partir du moment ou j'ajoute un traduction, les listes de valeurs ne s'affichent plus correctement (cf screenshots ci-jointes) :

![screen shot 12-29-15 at 09 43 am](https://cloud.githubusercontent.com/assets/2845524/12048947/815f3cde-aee1-11e5-829e-578923109217.PNG)
![screen shot 12-29-15 at 09 43 am 001](https://cloud.githubusercontent.com/assets/2845524/12048948/82feaad4-aee1-11e5-8924-11ec1a70f473.PNG)

Plusieurs faits notables :
    - Les listes d'intitulés pour lesquelles il n'y a pas encore eu de traduction ne sont pas impactées.
    - La désactivation de l'option "Traduction des intitulés" ne corrige pas l'affichage des listes déjà impactées
    - La suppression des traductions ne corrige pas non plus l'affichage des listes déjà impactées

J'ouvre ce bug sur demande de [btry](http://forum.glpi-project.org/profile.php?id=49485) (http://forum.glpi-project.org/viewtopic.php?id=144674)

```
GLPI 0.90.1 ( => /var/www/glpi)

Server
 
Operating system: Linux srv-support 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64
PHP 5.6.14-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
    calendar, ctype, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, ldap, libxml, mbstring,
    mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
    sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
    upload_max_filesize="5M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at 192.168.2.45 Port 80)
    Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Server Software: (Debian)
    Server Version: 5.5.46-0+deb8u1
    Server SQL Mode: 
    Parameters: root@localhost/glpi
    Host info: Localhost via UNIX socket
    
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.1.20 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/glpi/lib/password_compat). Compatitility: Ok

LDAP directories
 
Server: '192.168.2.187', Port: '389', BaseDN: 'OU=InterlogSolutions,OU=Utilisateurs,OU=IPS,DC=interlog,DC=local', Connection
        filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
        'CN=glpildap,OU=IPS,DC=interlog,DC=local', Use TLS: none
Server: '192.168.2.187', Port: '389', BaseDN: 'OU=InterlogLogistic,OU=Utilisateurs,OU=IPS,DC=interlog,DC=local', Connection
        filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
        'CN=glpildap,OU=IPS,DC=interlog,DC=local', Use TLS: none
Server: '192.168.2.187', Port: '389', BaseDN: 'OU=Utilisateurs,OU=IPS,DC=interlog,DC=local', Connection filter:
        '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
        'CN=glpildap,OU=IPS,DC=interlog,DC=local', Use TLS: none
Server: '192.168.2.187', Port: '389', BaseDN: 'OU=IPS-Chennai,DC=interlog,DC=local', Connection filter:
        '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
        'CN=glpildap_chennai,OU=IPS-Chennai,DC=interlog,DC=local', Use TLS: none

Mysql replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
    fields               Name: Champs supplémentaires         Version: 0.90-1.1   State: Enabled
    behaviors            Name: Comportements                  Version: 0.90       State: Enabled
    formcreator          Name: Formulaires                    Version: 0.90-1.3.2 State: Not activated
    dashboard            Name: Tableau de bord                Version: 0.6.9      State: Enabled
```

**Comment by tomolimo** [comment]
Bonjour,
J'ai fait un test de mon côté et j'obtiens une erreur similaire après avoir ajouté un intitulé sur une catégorie de ticket :

![glpi - ticket categories - windows internet explorer_2016-01-04_16-03-18](https://cloud.githubusercontent.com/assets/7569958/12092406/3960e8e0-b2fd-11e5-91bc-f276339f707a.png)

Par contre si je me déconnecte et me reconnecte sur GLPI, alors je n'ai plus l'erreur.

**Comment by cdlabal** [comment]
Bonjour,
même chose pour moi. Il s'agit donc d'un bug mais non bloquant ni très gênant.

**Comment by yllen** [comment]
Je n'ai aucun problème si j'ajoute un nouvel intitulé.
Pouvez-vous fournir les erreurs exactes dans les logs ?

**Comment by cdlabal** [comment]
Pour les logs, voir post de ylegrand plus haut.

**Comment by tomolimo** [comment]
Bonjour Yllen;

Voici la procédure pour reproduire ce bug:
1) ouvrir GLPI sur les dropdowns après avoir activé les traductiondes dropdowns
2) choisir les catégories de tickets
3) editer une catégorie
4) ajouter une traduction
5) cliquer sur 'List' pour retourner à la liste des catégorie de ticket.

contenu des logs:

2016-01-15 16:00:07 [937@ARDEVT35]
  *** PHP Notice(8): Undefined index: name
  Backtrace :
  inc\search.class.php:4668                          
  inc\search.class.php:1105                          Search::giveItem()
  inc\search.class.php:98                            Search::constructDatas()
  inc\search.class.php:81                            Search::showList()
  front\dropdown.common.php:52                       Search::show()
  front\itilcategory.php:41                          include()


![image](https://cloud.githubusercontent.com/assets/7569958/12356155/4f779af0-bba1-11e5-96e5-21db3f253ffe.png)

**Comment by yllen** [comment]
Merci Tomolimo, je reproduis et j'ai maintenant les logs plus complets

**Comment by yllen** [comment]
Ce bug a été introduit par ce commit https://github.com/glpi-project/glpi/commit/e21a11d4dea6214a2c9963ef15b13064f13d2126#diff-a801c52129f44d50ab6d1db9f049c4b7

Pour moi il ne faut pas traduire la liste des intitulés qui est réservée à un administrateur.
Le principal est que le dropdown soit bien traduite pour l'utilisateur, ce qui est le cas dans les objets

**Comment by tomolimo** [comment]
Je regarderai demain matin à la première heure ce qui se passe.

**Comment by tomolimo** [comment]
Finalement, je ne vais pas avoir le temps de regarder cela pour le moment.
On peut le laisser comme proposé pour l'instant.
Merci,
Tomolimo
