### ISSUE TITLE
Customing Computer Table view

### ISSUE THREAD

**Issue by Renaldy27** [glpi-project/glpi#3455]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.
How to custom table view in Computer not custom table database?

![sq](https://user-images.githubusercontent.com/21188924/35255689-d564dd4a-0022-11e8-94a6-9981a85b9a86.png)

**Comment by orthagh** [comment]
Hello @Renaldy27 

Just click on the wrench icon above the table.

**Comment by Renaldy27** [comment]
how to this add with plugin?

*Best Regards,*

*Rizqi Renaldy Ahmad Faiz*

*Mobile 082257365736*

*Email : Rizqi.renaldy@phincon.com <Rizqi.renaldy@phincon.com>;
rizqirenaldy27@gmail.com <rizqirenaldy27@gmail.com>*


*PT. PhinCon*

*The East Tower 12th Floor Unit 01-02*

*Jl. Dr. Ide Anak Agung Gde Agung Kav. E 3.2 No.1*

*Kawasan Mega Kuningan*

*Jakarta 12950 Indonesia*
*Office: 021-2555-6178 | Fax: 021-2555-6179*

2018-01-26 22:15 GMT+07:00 Alexandre Delaunay <notifications@github.com>:

**Comment by orthagh** [comment]
i don't understand your last answer, could you precise ?
