### ISSUE TITLE
Contrast missing / Problème de contraste

### ISSUE THREAD

**Issue by camlafit** [glpi-project/glpi#346]
Hi

On listing page as front/computer.php constrast isn't enough. Row have same color and reading is complicate.
0.85 was better about this point contrast was more important

Par exemple sur les pages comme front/computer.php le contrast n'est pas assez marqué. La lecture des tableaux est compliquée et il difficille d'identifier/isoler chaque ligne.  

Le constraste proposé par les 0.85 était plus appréciable, moins beau mais plus lisibible

**Comment by orthagh** [comment]
Please, provide a screeneshot to illustrate this issue.

**Comment by camlafit** [comment]
Hi

An example with two rows. We doesn't have any contrast between rows. Is same with more rows.
In 0.8.85, odd and even rows were different, at least more readable.

![glpi_contrast](https://cloud.githubusercontent.com/assets/209915/12113649/4f61ffce-b3a4-11e5-80ba-7eb2e3c94098.png)

**Comment by nqb** [comment]
+1

**Comment by orthagh** [comment]
No.
In 0.85.5 odd/even styles was already disabled for html table

![image](https://cloud.githubusercontent.com/assets/418844/12140382/c723ad8c-b467-11e5-9e03-10da0d24dbe6.png)


But, i'll check if i could enhance that

**Comment by camlafit** [comment]
Hi

Ok :) My mistake about odd/even contrast.

But as we can see, old interface is more readable maybe because all
rows/columns are isolated. I think this behavior can be improved on new
interface.
Of course I talk about only readability (color choice or beautiful aspects
is not in my question/scope)

Thanks

**Comment by ladenree76000** [comment]
+1 for cells borders (I know this is not the feature suggest page but ....)

**Comment by yllen** [comment]
For people with visual disabilities this problem is very important.
In big societies they must look at this.

**Comment by orthagh** [comment]
I agree with that .
We could provide a dedicated theme with high contrast for theses persons.
Here is a new issue to track this need : #489

Anyway, the initial request was to enhance contrast in existing themes.
I don't like that.
If op want to add odd/even class to his css, he could get around by add theses lines to his css theme : 

```CSS
.tab_bg_1 {
   background-color: #EAEAEA !important;
}
```

Anyway, we could think about a config var who store user custom styles.
Here is another issue to begin discussion : #490
