### ISSUE TITLE
SOLVED - "No user to be imported" import  from ldap (active directory)

### ISSUE THREAD

**Issue by alessiotomelleri** [glpi-project/glpi#3465]
Hi,
I've recently installed glpi for testing in our enterprise enviroment in a fresh centos 7.

Configuring ldap it succeded in test but I'm unable to import anything, always return :

"No user to be imported"

From log    /var/log/glpi/php-errors.log  always same result when I try import :

_PHP Warning(2): ldap_search(): Search: Operations error
  Backtrace :
  :                                                  
  inc/authldap.class.php:1595                        ldap_search()
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  inc/authldap.class.php:3726                        AuthLDAP::getAllUsers()
  inc/authldap.class.php:1445                        AuthLDAP::getUsers()
  inc/authldap.class.php:3300                        AuthLDAP::showLdapUsers()
  front/ldap.import.php:70                           AuthLDAP::searchUser()_

Below the conf :

<code>
GLPI 9.2.1 (/glpi => /usr/share/glpi) Installation mode: RPM

Operating system: Linux glpi.my.localdomain.com 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 PHP 7.2.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, 	sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.1 () 	Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0 Server Software: MariaDB Server 	Server Version: 5.5.56-MariaDB 	Server SQL Mode:  	Parameters: glpiadmin@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /etc/glpi : OK /var/lib/glpi/files : OK /var/lib/glpi/files/_dumps : OK /var/lib/glpi/files/_sessions : OK /var/lib/glpi/files/_cron : OK /var/lib/glpi/files/_graphs : OK /var/lib/glpi/files/_lock : OK /var/lib/glpi/files/_plugins : OK /var/lib/glpi/files/_tmp : OK /var/lib/glpi/files/_cache : OK /var/lib/glpi/files/_rss : OK /var/lib/glpi/files/_uploads : OK /var/lib/glpi/files/_pictures : OK /var/log/glpi : OK Web access to files directory is protected : OK SELinux mode is Enforcing SELinux boolean configuration for httpd_can_network_connect --> on SELinux boolean configuration for httpd_can_network_connect_db --> on SELinux boolean configuration for httpd_can_sendmail --> on

htmLawed version 1.2.4 in (/usr/share/php/htmLawed) phpCas version 1.3.5 in (/usr/share/pear) PHPMailer version 5.2.26 in (/usr/share/php/PHPMailer) SimplePie version 1.5.1 in (/usr/share/php/php-simplepie) TCPDF version 6.2.13 in (/usr/share/php/tcpdf) michelf/php-markdown in (/usr/share/php/Michelf) true/punycode in (/usr/share/php/TrueBV) iacaml/autolink in (/usr/share/php/php-iamcal-lib-autolink) sabre/vobject in (/usr/share/php/Sabre/VObject4)

Server: 'ldapserver', Port: '389', BaseDN: 'dc=my,dc=localdomain,dc=com', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'administrator@my.localdomain.com', Use TLS: none

Not active

Way of sending emails: PHP

appliances           Name: Appliances                     Version: 2.3.1      State: Enabled 	archires             Name: Network Architectures          Version: 2.5.0      State: Not installed 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.3      State: Enabled
</code>

Thx in advance...
Alessio Tomelleri

**Comment by alessiotomelleri** [comment]
UPDATE:  I've forgotten... and unable in case of authentication, here the log :

_PHP Warning(2): ldap_search(): Search: Operations error
  Backtrace :
  :                                                  
  inc/authldap.class.php:2789                        ldap_search()
  inc/auth.class.php:232                             AuthLDAP::searchUserDn()
  inc/authldap.class.php:2653                        Auth->connection_ldap()
  inc/authldap.class.php:2705                        AuthLDAP::ldapAuth()
  inc/auth.class.php:727                             AuthLDAP::tryLdapAuth()
  front/login.php:79                                 Auth->Login()_

**Comment by alessiotomelleri** [comment]
SOLVED

it turned as a authentication problem...

**Comment by Sophal-Cam** [comment]
Can you show me the step to fix it please?
