### ISSUE TITLE
[9.1.3] Can't Searching Computermodell with "space bar" - BUG?!

### ISSUE THREAD

**Issue by DGermany** [glpi-project/glpi#3470]
Hey, 

we've updated GLPI from 9.1.1 up to 9.1.3. 

One of our user just told me, that he can't search Computermodels with an space bar in it. 

Example: 
The model Kyocera C . 
- If you search " Kyocera" -> the list in dropdownfield is showing every result with "Kyocera" in the name. So far, so good. 

![kyocera](https://user-images.githubusercontent.com/30858247/35435454-b0e05ca8-0282-11e8-80b6-ff1a0f0bd30c.JPG)

 - If you search "Kyocera C" -> the list starts at the very first emelent of the hole computermodel-list. 

![kyocera_c](https://user-images.githubusercontent.com/30858247/35435483-c5c0c8ec-0282-11e8-832d-29d656e3c1f0.JPG)

I think, it's a bug. But can't say how to fix it. Can anybody help?! 

Thanks from germany

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/1838 and see https://github.com/glpi-project/glpi/issues/3201
