### ISSUE TITLE
[9.2.1] Image denied in body ticket

### ISSUE THREAD

**Issue by marios1984** [glpi-project/glpi#3473]
Dear GLPI user,
I can't see image in ticket created by mailgate:
![image](https://user-images.githubusercontent.com/4922280/35442269-ef842b14-02a6-11e8-86dd-7a4d523dbc27.png)

Have you any idea?

Thank you

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/3301
