### ISSUE TITLE
[9.2.1] Impossible to search problems or changes by id

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#3475]
Hi,

A client on 9.1.1 can't search for problems or changes by id when inside a change or problem. The same issue appears on 9.2.1.

I'm working on a fix, please advise on the procedure to publish it.

* Steps to reproduce:
  * Have a lot of problems and a lot of changes
  * For problems->changes:
    * Go to a problem (/front/problem.form.php?id=1), then switch to the changes tab
    * Search for a change by id => the problem is not found
  * For changes->problems:
    * Go to a change (/front/change.form.php?id=1), then switch to the problems tab
    * Search for a problem by id => the problem is not found
* This happens even with "Show GLPI ID" set to "Yes" in the Configuration default values

**Comment by orthagh** [comment]
See my comment in your PR

**Comment by pVesian** [comment]
PR closed, will be done by always searching by id
