### ISSUE TITLE
Predefined field for description not working  

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#3479]
If in the template I predefined the description field, during the creation of a ticket, GLPi tells me that the "description" field must be evaluated.

* Steps to reproduce (which actions have you made) :

Modify default template to add predefined field for descrition

![image](https://user-images.githubusercontent.com/7335054/35506679-62938826-04ea-11e8-9178-0558025f0465.png)

Create ticket

* Expected result :
![image](https://user-images.githubusercontent.com/7335054/35506745-abc1bcde-04ea-11e8-8ac8-b69d61637a46.png)

* Actual result :

![image](https://user-images.githubusercontent.com/7335054/35506706-7f25ad98-04ea-11e8-8319-7d39f89edf88.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.2.2-git-9.2/bugfixes-eb0ffd9 (/glpi/9.2-bugfixes => /var/www/public/glpi/9.2-bugfixes)
Installation mode: GIT

**Comment by trasher** [comment]
Just tested current 9.2/bugfixes branch, I cannot reproduce the issue. I guess this has been fixed since current itcket has been opened.
