### ISSUE TITLE
[0.90.1] Rappel du ticket : identité du demandeur absente

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#348]
Bonjour,
Est-il normal que le bloc "Rappel du ticket" sur l'onglet "Traitement du ticket" ne contienne pas le prénom/nom du demandeur renseigné à la création du ticket. À la place, on a le mot "Demandeur".

Merci.

**Comment by cdlabal** [comment]
+1

**Comment by rickyweb** [comment]
+1

**Comment by tomolimo** [comment]
Bonjour 
Peux-tu mettre une copie d'écran ?
Merci,
Tomolimo

**Comment by cdlabal** [comment]
[url=http://imagesia.com/rappel-ticket_14kn0][img]http://pimg.imagesia.com/fichiers/14k/rappel-ticket_imagesia-com_14kn0_small.jpg[/img][/url]
[url=http://imagesia.com/?utm_campaign=lc&utm_medium=bbcodem]Hébergé par Imagesia.com[/url]

Au lieu du nom du demandeur, la mention indique simplement "demandeur"

**Comment by tomolimo** [comment]
Peux-tu mettre une copie d'écran élargie ? Je veux dire avec la totalité de la page car je ne vois pas où cela se trouve.
Tu peux la mettre directement sur github dans le post (par glisser/déplacer),
merci,
Tomolimo

**Comment by cdlabal** [comment]
![rappel ticket](https://cloud.githubusercontent.com/assets/14885971/12139582/c5688a86-b461-11e5-9875-506d38d0db74.jpg)

Merci

**Comment by tomolimo** [comment]
ok, j'ai réussi à reproduire cela sur ma 0.90.1.
je vais faire un test sur la 0.91 et te tiens au courant.

**Comment by Siruv** [comment]
Bonjour n'est-ce pas la même chose que ce ticket ci : #157 )?
https://github.com/glpi-project/glpi/issues/157

Si c'est le cas ça semble être une volonté de la team GLPI .

Cordialement,

**Comment by nqb** [comment]
@Siruv : J'ai constaté le bug que je décris dans les cas suivants : 
- ouverture d'un ticket depuis le helpdesk par un technicien qui choisit un demandeur dans la liste des utilisateurs de GLPI
- ouverture d'un ticket à partir d'un collecteur avec une adresse e-mail associée à un utilisateur de GLPI

À l'inverse, le ticket #157 concerne les adresses e-mails _anonymes_ (celles qui ne sont pas associées à un utilisateur de GLPI). Est-ce que la correction du bug #157 n'est pas responsable du bug que nous signalons ?
