### ISSUE TITLE
Ukrainian localization issue

### ISSUE THREAD

**Issue by artemlevenets** [glpi-project/glpi#3480]
With Ukrainian interface in GLPI 9.2.1, there no ability to choose task tempalte, task category, User, Group and to Plan the task.
![glpi issue](https://user-images.githubusercontent.com/35097625/35519417-d6e53d00-051c-11e8-92d9-edade15e28d0.jpg)

**Comment by wawax** [comment]
Hello,

By switching to debug mode, do you see an error appearing on the page ?

Thanks in advance,

**Comment by artemlevenets** [comment]
Hi,

No, there no errors in debug mode.
The same issue on the Follow-Up Tab.

**Comment by trasher** [comment]
This is maybe a javascript issue. Could you please check if there are any JS errors from your browser development console?

**Comment by Alejka** [comment]
Hello,
Yes, This is the javascript issue.
In the tinyMCE.init() block:
`
$(function() {
    tinyMCE.init({
        language: 'uk_UA',
        browser_spellcheck: true,
        mode: 'exact',
        elements: '',
        relative_urls: false,
        remove_script_host: false,
        entity_encoding: 'raw',
        paste_data_images: $('.fileupload').length,
        menubar: false,
        statusbar: false,
        skin: 'light',
        setup: function (editor) {
            if ($('#').attr('required') == 'required') {
                $('#').closest('form').find('input[type=submit]').click(function () {
                    editor.save();
                    if ($('#').val() == '') {
                        alert('Поле опису обов'язкове');
                    }
                });
                editor.on('keyup', function (e) {
                    editor.save();
                    if ($('#').val() == '') {
                        $('.mce-edit-area').addClass('required');
                    } else {
                        $('.mce-edit-area').removeClass('required');
                    }
                });
                editor.on('init', function (e) {
                    if ($('#').val() == '') {
                        $('.mce-edit-area').addClass('required');
                    }
                });
            }
        },
        plugins: [
            'table directionality searchreplace',
            'tabfocus autoresize link image paste',
            'code fullscreen',
            'textcolor colorpicker',
            // load glpi_upload_doc specific plugin if we need to upload files
            typeof tinymce.AddOnManager.PluginManager.lookup.glpi_upload_doc != 'undefined'
                    ? 'glpi_upload_doc'
                    : '',
        ],
        toolbar: 'styleselect | bold italic | forecolor backcolor | bullist numlist outdent indent | table link image | code fullscreen',
        readonly: true
    });
});
`

next code with error:
`alert('Поле опису обов'язкове');`
You need to quote this string.

**Comment by trasher** [comment]
OK then, this is the same as https://github.com/glpi-project/glpi/issues/3200; it has been fixed already ;)
