### ISSUE TITLE
dependency on imap extension

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#3481]
**imap** extension rely on libc-client library (usually provided by uw-imap)

This is a dead project for years
This extension is not available on some enterprise distribution

A serious project should not rely on it (most webmail use pure PHP implementation, ex, roundcubemail, horde, ...)

Big issue is OpenSSL dependency

- most modern distribution have switch to OpenSSL 1.1 by default
- uw-imap is only compatible with old OpenSSL 1.0

Have both OpenSSL 1.0 and 1.1 in the php stack can only raise various strange issue (segfault, ex : [#1539799](https://bugzilla.redhat.com/show_bug.cgi?id=1539799))

FYI: I'm considering dropping the php-imap package from Fedora (and some people also think we should drop it from PHP, and move it in pecl forge, as deprecated)

**Comment by trasher** [comment]
I took a quick look on packagist; on the "top 3", one has not been updated since 2016... Remaining are:
https://github.com/barbushin/php-imap
https://github.com/ddeboer/imap

**Comment by trasher** [comment]
https://wiki.horde.org/project/hordeimaplib would be an alternative (but I did not found documentation)

**Comment by orthagh** [comment]
barbushin/php-imap & ddeboer/imap are build on top of php_imap so there are not really good alternatives

Horde seems good (not on packagist)

Roundcube option (not a separated lib)
https://github.com/roundcube/roundcubemail/tree/master/program/lib/Roundcube

**Comment by trasher** [comment]
Roundcube is GPLv3; we cannot include its code in GLPI with current license (as far as I undesrtand).... :/

**Comment by remicollet** [comment]
> Horde seems good (not on packagist)

horde can be pulled by composer, see https://github.com/horde/Imap_Client/blob/master/composer.json

**Comment by orthagh** [comment]
Another substitution for example : https://github.com/nextcloud/user_external/pull/49/files

**Comment by trasher** [comment]
Done in https://github.com/glpi-project/glpi/commit/f64859cd4dde8984311b5c0830abdc8f3549d9bf

**Comment by vladsf** [comment]
libc-client got OpenSSL 1.1 [patches](https://github.com/uw-imap/imap/tree/cab109466534e206a3652ef1c68fe88101b68bda)
