### ISSUE TITLE
Upgrade 9.1.2 to 9.2.1

### ISSUE THREAD

**Issue by sclouaire** [glpi-project/glpi#3482]
Dear GLPI user.

I try to upgrade my GLPI 9.1.2 to 9.2.1. I have follow the process but I have these problem 

Changement de la structure de la base de données - glpi_states (0 seconde)

An index must be added in the 'id_search_option' field of the 'glpi_logs table'; but your gpi_logs table is too huge. You'll have to add it on your database.

9.2 multiple alter in glpi_states - Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_states` ADD UNIQUE `unicity` (`states_id`, `name`) , ADD INDEX `is_visible_line` (`is_visible_line`) - L'erreur est Duplicate entry '3-Actif' for key 'unicity'

![image](https://user-images.githubusercontent.com/35957624/35562444-afd2b214-05b3-11e8-8d86-35c0a15cabde.png)

**Comment by trasher** [comment]
You have to make sure your items states are unique in your origin database before doing the update (you cannot have a same name for two statuses with same parent).
