### ISSUE TITLE
GLPI 9.2.1 PHP Fatal error

### ISSUE THREAD

**Issue by dan723** [glpi-project/glpi#3483]
After installing GLPI 9.2.1 if i try to change language to Spanish the system crash and i've got this message on the Apache log
PHP Fatal error:  Uncaught Zend\\I18n\\Exception\\OutOfBoundsException: Provided index 1 does not exist in plural array in /var/www/html/vendor/zendframework/zendi18n/src/Translator/Translator.php:415\nStack trace:\n#0 

Thanks

Regards

**Comment by trasher** [comment]
I cannot reproduce on current 9.2/bugfixes branch. Could you please test it?

**Comment by dan723** [comment]
Hi,
What do you mean with test it? We already had the issue in the 9.2.1.
Release.

Thanks

El 5 feb. 2018 9:36 a.m., "Johan Cwiklinski" <notifications@github.com>
escribió:

I cannot reproduce on current 9.2/bugfixes branch. Could you please test it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/glpi-project/glpi/issues/3483#issuecomment-363072352>,
or mute the thread

**Comment by trasher** [comment]
I ask you to test with current 9.2-bugfixes (that will become 9.2.2). You can get latest nightly build at https://forge.glpi-project.org/tarballs/.

**Comment by dan723** [comment]
Ok i'm going to test it, i'll let you know

Thanks a lot

**Comment by dan723** [comment]
Hello,

It seems it works with the 9.2.2

Thanks

2018-02-05 10:01 GMT-03:00 Daniele Artuso <artuso.daniele@gmail.com>:

**Comment by trasher** [comment]
Great, thanks for the feedback :) 9.2.2 should be released quite quickly; just wait for it ;)
