### ISSUE TITLE
[9.2.1] Bug on knowledge base headings

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#3490]
To reproduce: Add a new item to knowledge base and write something, then select the text and apply: Formats > Headings > Heading 1.

HTML: `<h1>Test</h1>`

Result:
![bug_glpi_knowledgebase](https://user-images.githubusercontent.com/15769828/35666811-bbd6664a-072b-11e8-96eb-770ca4f7782d.png)

**Comment by trasher** [comment]
I cannot reproduce with current 9.2/bf branch. Maybe it's been fixed already; please check with that branch if issue remains.

**Comment by jsamaniegog** [comment]
Sorry, i've located the problem in a CSS of monitoring plugin:
glpi/plugins/monitoring/lib/nvd3/src/nv.d3.css

I close the issue.
Thank you very much and sorry for the inconvenience.

**Comment by trasher** [comment]
No problem, thanks for the quick feedback ;)
