### ISSUE TITLE
GLPI 9.2.1 Helpdesk email in distribution group

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#3493]
Hi,

I've just faced with problem - when our helpdesk email included in ActiveDirectory distribution group and user sends email to this distribution group then GLPI 9.2.1 can't register ticket a new ticket properly. A BUG ?

**Comment by orthagh** [comment]
Hello @okvok 

Could you precise the issue ?
When you say you can't register a ticket, what's the glpi behaviors ?

Also, do you find any relative logs in glpi/files/_log/*.log or web server logs ?

Regards

**Comment by okvok** [comment]
I send email to the distribution group:
![image](https://user-images.githubusercontent.com/20252855/35800046-c1dfaa56-0a78-11e8-80c1-bdbf27bc202b.png)
then I'm getting email in glpi and it showing me:
![image](https://user-images.githubusercontent.com/20252855/35800284-8e7b5cc2-0a79-11e8-87d3-4fa9c97a9751.png)
the email was refused.
But if I unfold this group:
![image](https://user-images.githubusercontent.com/20252855/35800498-2f1f6cf4-0a7a-11e8-91a9-e3a46afce194.png)
the glpi successfully registered ticket:
![image](https://user-images.githubusercontent.com/20252855/35800765-ff4d9068-0a7a-11e8-8818-585a555f651a.png)

below you can see mail.log:
2018-02-04 12:34:04 [@bd-sd10.domain.local]
An email was sent to khamidov.in@domain.xyz: [GLPI #0026185] zzzzzzzz
2018-02-05 13:37:14 [7@bd-sd10.domain.local]
An email to khamidov.in@domain.xyz was added to queue: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:37:14 [7@bd-sd10.domain.local]
An email to fedrushkov.vv@domain.xyz was added to queue: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:37:14 [7@bd-sd10.domain.local]
An email to nezgovorova.ea@domain.xyz was added to queue: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:37:14 [7@bd-sd10.domain.local]
An email to shesterikova.ev@domain.xyz was added to queue: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:37:14 [7@bd-sd10.domain.local]
An email to samoilov.tv@domain.xyz was added to queue: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:38:03 [@bd-sd10.domain.local]
An email was sent to khamidov.in@domain.xyz: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:38:03 [@bd-sd10.domain.local]
An email was sent to fedrushkov.vv@domain.xyz: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:38:03 [@bd-sd10.domain.local]
An email was sent to nezgovorova.ea@domain.xyz: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:38:04 [@bd-sd10.domain.local]
An email was sent to shesterikova.ev@domain.xyz: [GLPI #0026186] 22222222222222222222222222222
2018-02-05 13:38:04 [@bd-sd10.domain.local]
An email was sent to samoilov.tv@domain.xyz: [GLPI #0026186] 22222222222222222222222222222
[root@bd-sd10 _log]#
 

And php-errors.log as well:
2018-02-05 13:49:02 [@bd-sd10.gpnbadra.local]
  *** PHP User Notice(1024): Invalid configuration for refused folder in receiver test.helpdesk@gazpromneft-badra.com
  Backtrace :
  :
  inc/mailcollector.class.php:1591                   trigger_error()
  inc/mailcollector.class.php:612                    MailCollector->deleteMails()
  inc/mailcollector.class.php:1647                   MailCollector->collect()
  inc/crontask.class.php:832                         MailCollector::cronMailgate()
  front/cron.php:87                                  CronTask::launch()
2018-02-05 13:49:02 [@bd-sd10.gpnbadra.local]
  *** PHP Notice(8): Unknown: Some of the requested messages no longer exist. (errflg=2)
  Backtrace :
  :
2018-02-05 13:49:02 [@bd-sd10.gpnbadra.local]
  *** PHP Notice(8): Unknown: Some of the requested messages no longer exist. (errflg=2)
  Backtrace :
  :

**Comment by orthagh** [comment]
Ok.

Could you paste a screenshot of your receiver configuration ?

**Comment by okvok** [comment]
Sure:
![image](https://user-images.githubusercontent.com/20252855/35844754-1ee299a0-0b20-11e8-9cbe-f536203c08b9.png)

**Comment by orthagh** [comment]
There is one notice i would to exclude to be sure.
```
PHP User Notice(1024): Invalid configuration for refused folder in receiver test.helpdesk@domain.xyz
```

Could you check the existence of refused folder 'GLPI_tickets_archive` and if you still have error remove it from the receiver configuration.

Second test, if the first doesn't change anything, after a refused collect, check the page "List of not imported mails": 
![image](https://user-images.githubusercontent.com/418844/35848564-e5dbc196-0b1e-11e8-9a1b-61f4d6ddb1ef.png)
You'll find here the refused emails with a reason.
With it, i'll be able to help you.

**Comment by okvok** [comment]
Hi,
I've removed folder from refused folder in configuration and nothing happen )))
The same - no tickets, 1 email refused in pop-up windows, but now no errors in php-errors.log. And "List of not imported emails" is empty.
Email removed to the folder 'GLPI_tickets_archive` like in archive folder.

**Comment by orthagh** [comment]
To you still have logs ?

**Comment by okvok** [comment]
No. There are no errors in php-errors.

**Comment by orthagh** [comment]
i'm sorry, no idea at the moment :/

**Comment by Armin83** [comment]
please try to disable this default rule:
```
Name Auto-Reply X-Auto-Response-Suppress
Description Exclude Auto-Reply emails using X-Auto-Response-Suppress header
Active Yes
```

i tried to explain already the problem here #2170 and hoped for a solution. please try this workaround and give us feedback, thanks

**Comment by Armin83** [comment]
For help do configure refused folder you can use my comment (in wrong issue - sorry again) 

https://github.com/glpi-project/glpi/issues/1518#issuecomment-298849902

**Comment by okvok** [comment]
Yes, got it! Thanks a lot! It works!!!!

**Comment by orthagh** [comment]
thx @Armin83 for the hint.
I try to check your issue issue in the day.
