### ISSUE TITLE
[0.90.1] Notifications actives suite mise à jour

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#350]
Bonjour,
En passant de la version 0.84.8 à la version 0.90.1, des notifications passent automatiquement de l'état "Inactif" à l'état "Actif". J'ai déjà remarqué ce bug lors d'autres mises à jour.

C'est un réel problème car si on ne vérifie pas, de nombreux mails peuvent être émis par erreur.

**Comment by orthagh** [comment]
Sauriez vous préciser quelles notifications sont impactées ?

**Comment by nqb** [comment]
Apparemment toutes les notifications créées sur la version 0.90. C'est-à-dire celles du type : Tâche de Projet, Projet, Changement. Liste ci-dessous : 
```
New change
Update change
Resolve change
Add task
Update task
Delete task
Close change
Delete change
New project
Update project
Delete project
New project task
Update project task
Delete project task
```
La notification "Receiver Errors" était également activée.
Je note que l'installation du plugin "formcreator" après la mise à jour en 0.90.1 a également créé plusieurs notifications, ces dernières sont aussi actives.

**Comment by orthagh** [comment]
> Apparemment toutes les notifications créées sur la version 0.90.

Dans ce cas, c'est tout à fait normal, ce sont des nouvelles notifications (apparue toutes en 0.85), elles sont active par défaut et elle concernait des objets qui n'existaient pas.

> La notification "Receiver Errors" était également activée.
Elle est aussi apparue est 0.85 et ai donc activée par défaut.

Pour résumer, ce ne sont donc pas des notifications existantes qui sont repassées actives mais de nouvelles par défaut active. C'est donc tout à fait normal

> Je note que l'installation du plugin "formcreator" après la mise à jour en 0.90.1 a également créé plusieurs notifications, ces dernières sont aussi actives.

Je dirais que ce soit doit être la même chose, mais il serait pertinent de demander sur l'espace de ce plugin.


Je ferme donc cette "issue" car c'est un comportement normal et souhaité, vous pouvez tout continuer à commenter si vous avez besoin de précisions, ou la ré-ouvrir si vous trouvez une notification existante qui aurait été modifiée

**Comment by nqb** [comment]
Je ne partage pas ce point de vue. 

Si on ne sait pas que c'est le comportement par défaut de GLPI, on émet des notifications vers les utilisateurs sans être au courant avec des informations potentiellement privées.

Je viens de faire une demande d'évolution : http://glpi.userecho.com/topic/1086623-/

**Comment by yllen** [comment]
Il avait été décidé d'activer les nouvelles notifications car les utilisateurs paramétraient les droits sur le nouvel objet et oubliaient les notifications, ce qui engendrait des signalements d'anomalies.
Les utilisateurs ont donc demandés que les nouvelles notifications soient actives par défaut étant donné qu'un nouvel objet était toujours testé avant mise à disposition des utilisateurs.

Par contre, je note qu'il serait bien de mettre un warning dans la doc à ce sujet.
https://github.com/glpi-project/doc/issues/2
