### ISSUE TITLE
GLPI 9.2.1 Search view in Problems for Groups

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#3502]
GLPI 9.2.1 Assistance -> Problems.
Search view does not work for Watchers and Assigned GROUPS. BUG?
Could you fix it please?

**Comment by okvok** [comment]
Hi Gents!
I analysed code and added some changes into search.class.php. Now searching form shows problems with groups properly. I suggest to test code and add it into the next release.
Changed code after 2770 line. All lines were changed have comments like // Khamidov
"// Khamidov 2018-02-04 added '_'.
                  $requestergroup_table = $groupetable.'_'.
                                          self::computeComplexJoinID($searchopt[71]['joinparams']
                                                                     ['beforejoin']['joinparams']).'`';

                  $observer_table       = '`glpi_'.$table.'_users_'.
                                          self::computeComplexJoinID($searchopt[66]['joinparams']
                                                                     ['beforejoin']['joinparams']).'`';
// Khamidov 2018-02-04 added '_'.
                  $observergroup_table  = $groupetable.'_'.
                                          self::computeComplexJoinID($searchopt[65]['joinparams']
                                                                    ['beforejoin']['joinparams']).'`';

                  $assign_table         = '`glpi_'.$table.'_users_'.
                                          self::computeComplexJoinID($searchopt[5]['joinparams']
                                                                     ['beforejoin']['joinparams']).'`';
// Khamidov 2018-02-04 added '_'.
                  $assigngroup_table    = $groupetable.'_'.
                                          self::computeComplexJoinID($searchopt[8]['joinparams']
                                                                     ['beforejoin']['joinparams']).'`';
               }
               $condition = "(";

               if (Session::haveRight("$right", $itemtype::READMY)) {
                  $condition .= " $requester_table.users_id = '".Session::getLoginUserID()."'
                                 OR $observer_table.users_id = '".Session::getLoginUserID()."'
                                 OR $assign_table.users_id = '".Session::getLoginUserID()."'
                                 OR `glpi_".$table."`.`users_id_recipient` = '".Session::getLoginUserID()."'";
// Khamidov 2018-02-04 added IF construction
                   if (count($_SESSION['glpigroups'])) {
                 $k_groups = implode("','", $_SESSION['glpigroups']);
                 $condition .= " OR $requestergroup_table.groups_id IN ('$k_groups')
                                  OR $observergroup_table.groups_id IN ('$k_groups')
                                  OR $assigngroup_table.groups_id IN ('$k_groups') ";
                   }
// Khamidov 2018-02-04 end IF construction "
![image](https://user-images.githubusercontent.com/20252855/35777787-fa7ad7e6-09c4-11e8-9d29-2c4e4cab893e.png)

**Comment by orthagh** [comment]
Hello @okvok 

Thank you for the report.
I don't understand the issue.
Could you attach a screenshot of the UI when the issue triggers ?

**Comment by okvok** [comment]
The search panel in problems did not show the list of problems for user in case if the user is a member of Group_A (example) and if the Group_A in "Watcher"-field or in "Assigned to"-field.
See screenshot:
![image](https://user-images.githubusercontent.com/20252855/35798709-ac7745d8-0a74-11e8-8a7c-77dd70fee75d.png)
and the list of problems was empty:
![image](https://user-images.githubusercontent.com/20252855/35799652-7777c828-0a77-11e8-82c3-23506c23a04c.png)

 Search panel showed the list of problems only for user in "Watcher"-field or in "Assigned to"-field. 
After my changes it works properly for Groups.
![image](https://user-images.githubusercontent.com/20252855/35799025-85c95df8-0a75-11e8-8313-ee8df7331464.png)

**Comment by orthagh** [comment]
ok i see
i prepare a pr with your patch
