### ISSUE TITLE
Telemetry not working when proxy enabled

### ISSUE THREAD

**Issue by tyronewyatt** [glpi-project/glpi#3503]
The GLPI team.

Telemetry not working when proxy enabled for GLPI 9.2

The telemetry automatic action gets suck on running state if a proxy server is enabled. 
![image](https://user-images.githubusercontent.com/13756677/35773268-e2526cd4-09a0-11e8-9670-6409d1985010.png)

When running the automatic action manually I get an error 500. 
![image](https://user-images.githubusercontent.com/13756677/35773263-c36547ec-09a0-11e8-93f9-38fb6cff280b.png)

Changed telemetry automatic action from GLPI mode to CLI but still occurs. 
![image](https://user-images.githubusercontent.com/13756677/35773269-fd2a0bf2-09a0-11e8-93a0-2caa211a00fb.png)

Tested using IIS on Windows and Nginx on Debian.

I know the proxy feature has not worked for some time and there has been a few issues raised but we need the proxy feature working to ensure enterprise users of GLPI are able to share telemetry information to the project.
![image](https://user-images.githubusercontent.com/13756677/35773310-58bc3c96-09a2-11e8-816b-f9ba4bceaf54.png)
![image](https://user-images.githubusercontent.com/13756677/35773317-700d7a22-09a2-11e8-99af-6668320e53e2.png)

![image](https://user-images.githubusercontent.com/13756677/35773321-808a2e36-09a2-11e8-93cf-7e1296d5a533.png)
![image](https://user-images.githubusercontent.com/13756677/35773325-9c136410-09a2-11e8-8591-3a7c38e03aa9.png)

If I check for updates I receive this error message:
![image](https://user-images.githubusercontent.com/13756677/35773248-59ccd66a-09a0-11e8-9351-15691c7e7bcc.png)

All tested sites point to a squid proxy server of various builds. 
Unfortunately bypassing the proxy server is not an option for port 80/443 traffic.
Happy to perform further troubleshooting if need be,

**Comment by trasher** [comment]
Could you please check GLPI logs when you have the `500` error code and give us message(s)?

**Comment by tyronewyatt** [comment]
Unable to locate any errors in php-errors.log or sql-errors.log. 
In cron.log I see: Internal #1: Launch telemetry 2018-02-16 09:50:48 [6@TSCWEB01]
Nothing found in iis logs.
Applied the patch and same result.

**Comment by tyronewyatt** [comment]
Tested on my debian nginx test server and same result.

**Comment by trasher** [comment]
Check on the proxy side if there are no errors. See also https://github.com/glpi-project/glpi/issues/3559

**Comment by tyronewyatt** [comment]
Squid access.log
When Telemetry action Fails:
1518819068.359      1 192.168.2.5 TCP_DENIED/403 3468 CONNECT glpi-project.org:80 - HIER_NONE/- text/html
Compared to when I check for updates in maintenance which is working:
1518818936.657   1464 192.168.2.5 TCP_MISS/200 68224 CONNECT api.github.com:443 - HIER_DIRECT/192.30.255.116 -

**Comment by tyronewyatt** [comment]
Looked at #3559.
@nqb is correct in saying that Telemetry is sending SSL over HTTP port.
If I edit my squid.conf, copy `acl SSL_ports port 443` -> `acl SSL_ports port 80` and reload squid then the squid access log says:
1518819317.163    815 192.168.2.5 TCP_MISS/200 660 CONNECT glpi-project.org:80 - HIER_DIRECT/104.28.10.109 -
