### ISSUE TITLE
[9.2.2] Choices in dropdown menus truncated

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#3506]
Hello,

In GLPI 9.2.2, choices with many caracters in dropdown menus are truncated **at the beginning**. It seems more clear to truncate **at the end**.

Example (with spain translation) in Administration -> Entities -> Assistance tab : 

![glpi](https://user-images.githubusercontent.com/10830260/35805837-a37becb4-0a7d-11e8-8f76-0a2dfdb06384.png)

**Comment by trasher** [comment]
This is expected. Changing this behavior will not satisfy other users...

As far as I know, https://github.com/glpi-project/glpi/issues/2693 may help with that.
