### ISSUE TITLE
Profile images

### ISSUE THREAD

**Issue by Gianfranco97** [glpi-project/glpi#3511]
Greetings.

My situation is the next:
I am developing a web interface that is responsible, among other things, for managing the users of glpi, among my needs is to show their profile images and for this I need a way to download them from the api-rest, I know of the existence of an endpoint that allows the download of files but to use it I need to provide a file id, my problem is precisely this, I have not found any way to get this id. I would be very grateful if you could help me with this.

Thanks in advance.

**Comment by ajsb85** [comment]
Reference:

https://github.com/flyve-mdm/web-mdm-dashboard/issues/279

**Comment by ladenree76000** [comment]
get /user/ $myUserID
then picture url is in $response[picture]

**Comment by trasher** [comment]
@ladenree76000 answered the question :)
