### ISSUE TITLE
Ticket timeline: Wrong original author if requester is changed

### ISSUE THREAD

**Issue by nbriche** [glpi-project/glpi#3514]
A ticket is opened by user X.

Turns out user X was asked to open the ticket by user Y. User X has nothing to do at all with the issue at hand. Requester actors are manually modified: user X and their groups are removed, user Y and their groups are added. In the timeline, the author of the description is now user Y, with no indication that it ever was anyone else.

This can cause some issues for a technician not familiar with the ticket's genesis and asking the "new" requester for details (in the form of "I never said that!" or "I don't know what you're talking about", or the requester just not answering follows notifications because, after all, they didn't open that ticket.)

The timeline should either:
- keep the original author's name for the original description (by using the ticket's "opened by" field), or
- somehow indicate that the current requester is not the original author, with a reference to the original author.

This will not actually correct the underlying user behavior, but it will give the technician a better understanding of the ticket's life.

Technically, the first responder could add a follow to explain the whole thing, but honestly that shouldn't be their job even in they remembered to do it.

**Comment by kedson42** [comment]
What is the status of this fix?

Is it going to be released in the next versions?

**Comment by trasher** [comment]
This is part of GLPI >= 9.2.3
