### ISSUE TITLE
[0.90.1] Some ticket tasks notifications not sent

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#352]
Some task notifications do not get sent even though they are generated and land in the Mail Queue. The GLPI mail.log file says for everything else:
1) mail added to queue
2) mail sent
For the lost mails, the log says only "added to queue" but not "sent". If I'm looking for the item in the queue, it's not available any longer to be resent or such, neither in the unsent ones, neither in the sent ones (in the trash)

I'm still trying to investigate further.

**Comment by rickyweb** [comment]
Here's an excerpt of the mail.log showing two cases where the task notification was added to the mail queue but never sent (lines starting with >>>)

[mail.log.txt](https://github.com/glpi-project/glpi/files/79894/mail.log.txt)

**Comment by orthagh** [comment]
Do you see theses notifications in Administration > Mailqueue page ?

**Comment by rickyweb** [comment]
Hello @orthagh, no, as already mentioned,  the missing notifications are neither in the active queue, nor in the deleted items of the queue.

**Comment by orthagh** [comment]
Have some corresponding lines (same times) in your error log files (php, sql).
You can find these logs at the same place.

Also, checking apache logs could be usefull

**Comment by rickyweb** [comment]
@orthagh, I've investigated the situation inside our company and we've been able to boil it down to the following symptom: if the task and the solution are being submitted very closely together, that is within the same minute, sometimes just several seconds in between, the task mail doesn't get sent, only the solution. To me it looks like as if the solution mail _overwrites_ the task mail, so the queue has nothing to send for the task.
I've looked at the php-errors.log, sql-errors.log and httpd/error_log but they contain nothing for the timespan.
Along with the mail.log, I'm including the httpd/access_log for the agent who was working on that ticket, in case that helps.
[logs.txt](https://github.com/glpi-project/glpi/files/113615/logs.txt

**Comment by yllen** [comment]
You have no errors in yours logs.
Have you only the issue with task notifications? for ticket? for all your users?

**Comment by rickyweb** [comment]
@yllen so far I've only seen the problem with notifications for tickets, not necessary tasks, just anything that gets sent in the same minute. And this affects all users.

**Comment by yllen** [comment]
@rickyweb your problem still exists in last version of GLPI?

**Comment by yllen** [comment]
No news. I close
