### ISSUE TITLE
Could not get DB lock

### ISSUE THREAD

**Issue by jpsbatista** [glpi-project/glpi#3520]
Hi,
For bug reports, you can open an issue here, provide us :

GLPI 9.2.1 with Xampp 3.2.2
MySQL 5.6.36-82.1
PHP 7.1.9
I have problem with mailgate, it crashes in running status.

in the cron.php task logs I get the following error:

PHP Fatal error: Uncaught Error: Call to a member function free() on boolean in
D:\xampp\htdocs\glpi\inc\dbmysql.class.php:432
Stack trace:
#0 D:\xampp\htdocs\glpi\inc\dbmysql.class.php(741): DBmysql->free_result(false)
#1 D:\xampp\htdocs\glpi\inc\dbmysql.class.php(757): DBmysql->tableExists('glpi_e
ntities')
#2 D:\xampp\htdocs\glpi\inc\dbutils.class.php(798): DBmysql->fieldExists('glpi_e
ntities', 'ancestors_cache')
#3 D:\xampp\htdocs\glpi\inc\dbutils.class.php(558): DbUtils->getAncestorsOf('glp
i_entities', '5')
#4 D:\xampp\htdocs\glpi\inc\db.function.php(739): DbUtils->getEntitiesRestrictRe
quest(' WHERE', 'glpi_groups', 'glpi_groups.`...', '5', true, false)
#5 D:\xampp\htdocs\glpi\inc\notificationtarget.class.php(774): getEntitiesRestri
ctRequest(' WHERE', 'glpi_groups', 'entities_id', '5', true)
#6 D:\xampp\htdocs\glpi\inc\notificationtarget.class.php(813): NotificationTarge
t->addGroupsToTargets('5')
#7 D:\xampp\htdocs\glpi\inc\notificationtarget.class.php(130): NotificationTarge
t->addNotificationTargets('5')
#8 D:\xampp\ht in D:\xampp\htdocs\glpi\inc\dbmysql.class.php on line 432

in the cron.log, i receive the following:
Could not get DB lock

**Comment by trasher** [comment]
This is not really related to GLPI; but to the way MyISAM locks. Switch to innodb is probably the only solution to avoid those errors (done in 9.3 - some users have reported a innodb switch on previous versions without issues)
