### ISSUE TITLE
[0.85.X]Patch for PHP7

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#353]
Any plans for releasing an update for the 0.85 branch for php 7 compatibility?

**Comment by orthagh** [comment]
No.

But 0.90.2 will be

**Comment by Megachip** [comment]
:( Thats bad, cause of a lot missing plugins, an upgrade isn't possible atm.

I thought 0.90.1 already fixed all php7 issues;)
But looks not to hard to implement the php7 fixes by myself on 0.85.8.

**Comment by orthagh** [comment]
for my information, could you list the missing plugins ?

**Comment by Megachip** [comment]
Appliances, Monitoring, Network architectures, ...
