### ISSUE TITLE
Ticket standard form - predefined hidden fields

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#3531]
* Steps to reproduce (which actions have you made) :
In ticket template add predefined fields "Status" and "Request source".
In ticket template add hidden fields "Status" and "Request source".
Open "Standard interface" tab.
* Expected result :
Don't known
* Actual result :
"Status" field - uneditable
"Request source" field - only field caption

* URL of the page :
/front/tickettemplate.form.php?id=2
* Screenshot of the problem (if pertinent) :
![scr5554](https://user-images.githubusercontent.com/11641656/36058961-dbcb44ce-0e3e-11e8-9651-62da3ad49d82.png)
* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.2-git-9.2/bugfixes-9bfac06fd ( => /var/www/glpi)
Installation mode: GIT

**Comment by hartois** [comment]
I want to fix this error, but I don't known expected behavior.
I think if field is "hidden" than it must dont be shown with caption.

**Comment by trasher** [comment]
I guess a field should never be set as both mandatory and hidden; fix would probably be to fix that. @orthagh your point of view?

**Comment by orthagh** [comment]
yes, agree with both of you.
- An exclusivity on fields for mandatory and hidden criteria.
- And priority for hidden in case of (bug ?)  both criteria

**Comment by trasher** [comment]
OK for me

**Comment by hartois** [comment]
Sorry! Apparently I was very tired.
These are not mandatory, but predefined fields.

**Comment by hartois** [comment]
@orthagh what you think?

**Comment by orthagh** [comment]
could you edit your first post with the correct type ?
I have trouble to interpret the bug :D

**Comment by hartois** [comment]
@orthagh updated

**Comment by orthagh** [comment]
Not sure, but in my opinion, hidden fields should have priority on mandatory or predefined fields

on case predefined and hidden fields, they should be filled (with an input hidden) but not displayed

**Comment by hartois** [comment]
I agree. I believe that a hidden predefined field should not be displayed, but should be sent in the form.

**Comment by orthagh** [comment]
milestoned this issue

**Comment by trasher** [comment]
Looking at the code; I can see tha predefined fields has precedence over hidden fields; so this is expected "Status" and "Request source" are displayed.
"Request source" value is not displayed because of a non closed HTML tag...
