### ISSUE TITLE
IPAM

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#3538]
https://forge.glpi-project.org/projects/ipam
http://plugins.glpi-project.org/#/plugin/addressing
https://en.wikipedia.org/wiki/IP_address_management

**Comment by magaiverpr** [comment]
Tips of inspirations:

https://phpipam.net/

**Comment by fcrispim77** [comment]
Another great tool:

http://www.gestioip.net/

**Comment by szilvasidave** [comment]
This should not be closed

**Comment by mathieumd** [comment]
GLPI is badly missing good IPAM features, like other softwares linked in this ticket does.

**Comment by Venkarian** [comment]
Is it planned to add this feature to GLPI 10 ?

**Comment by cconard96** [comment]
> Is this on the roadmap by any chance?

https://glpi-project.org/roadmap/

**Comment by alidhehibi** [comment]
Is there any updated regarding IPAM integration?
