### ISSUE TITLE
Translation longitude and lattitude 

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#354]
Cant found these both in transifex.

There are misspellings at least in german translation :(

**Comment by orthagh** [comment]
here some links : 

https://www.transifex.com/moyo/GLPI/translate/#de/glpipot090/51515660?q=longitude
https://www.transifex.com/moyo/GLPI/translate/#de/glpipot090/51515661?q=latitude

For the misspellings, is in english or german sentences ?

**Comment by Megachip** [comment]
Hmm, why I do not find it while searching. Have fixed it. Thx for the links.
