### ISSUE TITLE
 Body translation templates html notifications

### ISSUE THREAD

**Issue by snville** [glpi-project/glpi#3545]
I need the translation templates of the html body of notifications by mail, affect them.

Edit the default translations of Glpi 9.2.1 notifications and now the messages come to me with a poorly designed structure, how can I configure the tags or the html options that are so "## ticket.url ###", that is, , I need the options to create notification templates.

**Comment by trasher** [comment]
Hi, please use [community forums](http://forum.glpi-project.org) to get help on usage.
