### ISSUE TITLE
[9.2.2] telemetry automatic action with a proxy : SSL handshake failed

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#3559]
Hello,

In 9.2.1 and 9.2.2 (bugfix), I notice that telemetry automatic action (CLI or GLPI mode) stay in "Running" state with a proxy server define in `Setup -> General -> Proxy configuration for upgrade check`

In debug mode, I see following error : 
```
Fatal error: Uncaught RuntimeException: Something went wrong sending telemetry
informations: Received HTTP code 403 from proxy after CONNECT in
/var/www/glpi/inc/telemetry.class.php:304 Stack trace: #0
/var/www/glpi/inc/crontask.class.php(832):

Telemetry::cronTelemetry(Object(CronTask)) #1
/var/www/glpi/front/crontask.form.php(49): CronTask::launch(-1, 1,
'telemetry') #2 {main} thrown in /var/www/glpi/inc/telemetry.class.php on line
304
```

In my proxy, I see following log : 
`TCP_DENIED/403 3873 CONNECT glpi-project.org:80 - HIER_NONE/- text/html`

It seems that GLPI try to establish an SSL connection on https://glpi-project.org:80 with errors.

If I go on https://glpi-project.org with my web browser (with or without proxy), I get following error : 
```
Error 525 Ray ID: 3ed73b6a7c42650b • 2018-02-15 09:27:34 UTC
SSL handshake failed
```

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/3503

**Comment by trasher** [comment]
OK, seems another problem as discussed on IRC; I reopen

**Comment by nqb** [comment]
To sum up discuss on IRC : 
- issue due to default config of your Squid proxy : method CONNECT only authorized for SSL Ports (not port 80). Squid is configured like that on many installations.
- function `cronTelemetry` at https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/telemetry.class.php#L269 is different from function `getURLContent` at https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/toolbox.class.php#L1565. There is not this code block in first function : 
```
      // Manage standard HTTPS port : scheme detection or port 443
      if ((isset($taburl["scheme"]) && $taburl["scheme"]=='https')
         || (isset($taburl["port"]) && $taburl["port"]=='443')) {
         $hostscheme  = 'ssl://';
         $defaultport = 443;
      }
```
It seems necessary to add same kind of code in function `cronTelemetry`.

**Comment by trasher** [comment]
Please test with PR #3570

**Comment by nqb** [comment]
Not tested but seen in [PHP : curl_setopt manual](https://secure.php.net/manual/en/function.curl-setopt.php#98751) : 

> CURLOPT_HTTPPROXYTUNNEL means curl will use CONNECT method of the HTTP protocol to make a tunnel through a proxy, which is most likely not the one you want to do.

**Comment by nqb** [comment]
Hello @tyronewyatt,

Have tou try #3570 patch ? If not, could you try to set `CURLOPT_HTTPPROXYTUNNEL` to `0` ?

Thanks

**Comment by nqb** [comment]
@tyronewyatt said on #3503 : 

> Compared to when I check for updates in maintenance which is working:
> 1518818936.657 1464 192.168.2.5 TCP_MISS/200 68224 CONNECT api.github.com:443 - 

Expected behavior : GLPI use CONNECT method to establish connection in HTTPS (443 port). Compatible with Squid's acl SSL_ports.

Code used to check new GLPI versions :   https://github.com/glpi-project/glpi/blob/64fede321eb27d3812251238895172593e2cd697/inc/toolbox.class.php#L1288

**Comment by tyronewyatt** [comment]
Hello @nqb, I did try patch #3570 but didn't fix my issue so I reverted back.
Changed my CURLOPT_HTTPPROXYTUNNEL from 1 -> 0.
No longer get error 500 and in the automatic action logs it says it completed in 5 seconds.
1518840190.303    920 192.168.2.5 TCP_MISS/200 723 POST http://glpi-project.org/telemetry/telemetry - HIER_DIRECT/104.28.11.109 application/json

**Comment by trasher** [comment]
I'm not proxy expert; I wonder if such a change will not break things for some other users...

**Comment by trasher** [comment]
Maybe:
```diff
diff --git a/inc/toolbox.class.php b/inc/toolbox.class.php
index e31a175ef..12a25e10c 100644
--- a/inc/toolbox.class.php
+++ b/inc/toolbox.class.php
@@ -1604,17 +1604,16 @@ class Toolbox {
          $opts += [
             CURLOPT_PROXY           => $CFG_GLPI['proxy_name'],
             CURLOPT_PROXYPORT       => $CFG_GLPI['proxy_port'],
-            CURLOPT_PROXYTYPE       => CURLPROXY_HTTP,
-            CURLOPT_HTTPPROXYTUNNEL => 1
+            CURLOPT_PROXYTYPE       => CURLPROXY_HTTP
          ];
 
          if (!empty($CFG_GLPI["proxy_user"])) {
             $opts += [
-               CURLOPT_PROXYAUTH => CURLAUTH_BASIC,
-               CURLOPT_PROXYUSERPWD => $CFG_GLPI["proxy_user"] . ":" . self::decrypt($CFG_GLPI["proxy_passwd"], GLPIKEY)
+               CURLOPT_PROXYAUTH       => CURLAUTH_BASIC,
+               CURLOPT_PROXYUSERPWD    => $CFG_GLPI["proxy_user"] . ":" . self::decrypt($CFG_GLPI["proxy_passwd"], GLPIKEY),
+               CURLOPT_HTTPPROXYTUNNEL => 1
             ];
          }
-
       }
 
       curl_setopt_array($ch, $opts);
```

**Comment by nqb** [comment]
I will check.

**Comment by nqb** [comment]
@trasher : could you provide me a patch rather than a git diff output ?

**Comment by trasher** [comment]
See referenced commit (7fdf6969aa177343339884338dffc9b33337f3af)

**Comment by nqb** [comment]
@trasher : in 7fdf696, I don't see this changes : 
```diff
diff --git a/inc/toolbox.class.php b/inc/toolbox.class.php
index e31a175ef..d83e29342 100644
--- a/inc/toolbox.class.php
+++ b/inc/toolbox.class.php
@@ -1604,17 +1604,21 @@ class Toolbox {
          $opts += [
             CURLOPT_PROXY           => $CFG_GLPI['proxy_name'],
             CURLOPT_PROXYPORT       => $CFG_GLPI['proxy_port'],
-            CURLOPT_PROXYTYPE       => CURLPROXY_HTTP,
-            CURLOPT_HTTPPROXYTUNNEL => 1
+            CURLOPT_PROXYTYPE       => CURLPROXY_HTTP
          ];
 
          if (!empty($CFG_GLPI["proxy_user"])) {
             $opts += [
-               CURLOPT_PROXYAUTH => CURLAUTH_BASIC,
-               CURLOPT_PROXYUSERPWD => $CFG_GLPI["proxy_user"] . ":" . self::decrypt($CFG_GLPI["proxy_passwd"], GLPIKEY)
+               CURLOPT_PROXYAUTH    => CURLAUTH_BASIC,
+               CURLOPT_PROXYUSERPWD => $CFG_GLPI["proxy_user"] . ":" . self::decrypt($CFG_GLPI["proxy_passwd"], GLPIKEY),
             ];
          }
 
+         if ($defaultport == 443) {
+            $opts += [
+               CURLOPT_HTTPPROXYTUNNEL => 1
+            ];
+         }
       }
 
       curl_setopt_array($ch, $opts);
```

**Comment by nqb** [comment]
@trasher : patch applied.

Results : 
* telemetry automatic action works. It didn't use CONNECT method. Proxy logs identical to @tyronewyatt : 
```
TCP_MISS/200 839 POST http://glpi-project.org/telemetry/telemetry - HIER_DIRECT/104.28.11.109 application/json
```
* checkupdate automatic action works. It use CONNECT method due to HTTPS URL (https://api.github.com/repos/glpi-project/glpi/releases). Proxy logs : 
```
TCP_TUNNEL/200 68215 CONNECT api.github.com:443 - HIER_DIRECT/192.30.253.116
```
> I'm not proxy expert; I wonder if such a change will not break things for some other users...

To be sure, I test telemetry and checkupdate actions without proxy. It works. You can merge.
