### ISSUE TITLE
Assign multihosts on same license

### ISSUE THREAD

**Issue by dsever** [glpi-project/glpi#3560]
In version of glpi 9.2.1 I was unable to assign multiitems on licences that supports multiple hosts (example for vmware vsphere).
After removing  index on table glpi_computers_softwarelicense (unique) for columns computer_id and softwarelicense_id, everything  looks fine.

Want to check is it by design or kind of bug?

Dubravko

**Comment by orthagh** [comment]
Hello @dsever 

I try to understand your need.
for the index, you removed the unicity one ?

So you wanted to add the same licence twice (or more) on the same computer ?

**Comment by dsever** [comment]
Yes exactly. for instance in case of vmware (licenses are per socket) and one license number can contain 1 or many CPU-s. So for given asset (server) that has 2 CPUs  we need to assign the same license few times.

Dubravko

**Comment by orthagh** [comment]
Ok thank you for the explanation.

> Want to check is it by design or kind of bug?
i can't choose between these two :p

Anyway, we will see to remove the unicity for the next major version (i set milestone for the issue)

**Comment by trasher** [comment]
Done
