### ISSUE TITLE
Use of $PLUGIN_HOOKS["helpdesk_menu_entry"]

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3561]
In init of myplugin
$PLUGIN_HOOKS["helpdesk_menu_entry"]['myplugin'] = true;

In version of myplugin
'page' => "/front/mypage.php"

In displayMainMenu of HTML.class
$PLUGIN_HOOKS["helpdesk_menu_entry"][$plugin]) is not a string but a boolean.
So $link is true, not a value

So $infos['page'] is not to define because come from version of my plugin

**Comment by orthagh** [comment]
Not sure at all about this.
I don't know who is right for this hook but i found in my `plugins folder`, two who set urls in this hook:
- https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/setup.php#L371
- https://github.com/ddurieux/glpi_monitoring/blob/master/setup.php#L132

So the change will be a breaking one for existing plugins.

Ping @ddurieux

**Comment by ddurieux** [comment]
How define the page url for the entry ?

**Comment by remicollet** [comment]
I agree with @yllen `$infos['page'] = $link;`  should be moved in the condition.

**Comment by ddurieux** [comment]
I'm really lost

**Comment by remicollet** [comment]
@ddurieux both have to work work
* string => use it
* boolean => use Plugin::getInfo()

**Comment by ddurieux** [comment]
Ah ok, thanks ;)

**Comment by remicollet** [comment]
BTW... code in  `displayMenuAll` shloud also (need to be checked) drop the `is_string` condition....

**Comment by remicollet** [comment]
Also, see https://github.com/pluginsGLPI/example/blob/master/setup.php#L91

**Comment by DataSharing** [comment]
https://github.com/DataSharing/Plugin-example-GLPI-9.1
