### ISSUE TITLE
Open Auto Ticket

### ISSUE THREAD

**Issue by allanlopesprado** [glpi-project/glpi#3563]
I suggest inserting an option in the automatic ticket rules.

An example would be.

*** I use FusionInventory, and sometimes it turns out that some features are inactive / active due to lack of communication or something. ***

It would be important for a ticker to be opened altomatically.

**With this improvement, you can create an automatic ticket for any changes made within the GLPI, not just for the example mentioned.**

**Comment by trasher** [comment]
Hi, 

Please use suggestions website: https://glpi.userecho.com/

Thank you
