### ISSUE TITLE
Plugin PDF

### ISSUE THREAD

**Issue by elianetusset** [glpi-project/glpi#3572]
I would like to request the change to the PDF plugin header code, so that a line break is included because the description is being cut off, as the attached print.
Currently in my support structure I have a parent entity, with several records of child entities.

I would also kindly ask the file and the command to manually include me to remedy the situation.

I have installed version 1.2 of the plugin, but I already tested it with version 1.3 and the situation remains.

Thank's,
![screenhunter_7227 feb 16 11 00](https://user-images.githubusercontent.com/30874403/36308555-5671dc56-1308-11e8-87ca-6fa5342da0db.jpg)

**Comment by trasher** [comment]
Please contact plugin team: https://forge.glpi-project.org/projects/pdf
