### ISSUE TITLE
Add a numbered or bulleted list

### ISSUE THREAD

**Issue by blacksushi42** [glpi-project/glpi#3575]
Dear GLPI team,

I would like to suggest making it possible to add a numbered or bulleted list in the description, the follow-up, the task and the solution.

Especially for tasks, we can then summarize all our actions in one task.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
_GLPI 9.3-dev-git-master-624711f (/glpi => /var/www/html/glpi)
Installation mode: GIT_

Thank you again for this wonderful project.

**Comment by trasher** [comment]
Currently, CSS will display lists... well, not as lists. In order to get that changed; all existing lists will have to be reviewed.
