### ISSUE TITLE
Internal time to own + Progress bar issue

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#3576]
Hello,

I've been trying to use the OLA Service Levels.
The configuration goes well, but when I want to see the Ticket's list showing me the colored Internal time to own + Progress column, the system keeps showing me a red bar even if the ticket is accepted before Internal own due date.
Look the picture below.

- Ticket 18 is assigned to the user "tech". The "OLAs" assigned by rule. The technician was assigned manually. If you look at the "Internal Time to own Exceeded" column, it was not exceeded, but the red bar is there as it was.
- Ticket 21 assigned to anyone but with the same "OLAs" assigned by business rules. The "Internal Time to own Exceeded" column shows that the Internal Time was exceeded.

![image](https://user-images.githubusercontent.com/13874922/36315474-fa1a29b0-131e-11e8-97dd-d40a1892cee6.png)

It seems that we have an issue just with that little bar that doesn't disappear like on SLA situation like on the Ticket 20.

* Steps to reproduce (which actions have you made) :

- Create 1 OLA to own and another to solve.
- 1 rule that assigns the OLAs to the tickets
- Opened the ticket and assigned manually to a technician

* Expected result :
  - The bar on Internal time to own + Progress should disappear after a technician is assigned

* Actual result :
  - The bar is not disappearing but the ticket is not overdue

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.2.1
Tarball

**Comment by arthurrschaefer** [comment]
Also tested in Nightly version.
Same issue.

**Comment by orthagh** [comment]
will be fixed in 9.2.2, see pr #3637
