### ISSUE TITLE
GDPR/RGPD compliance

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#3577]
Hi,

Is GLPI GDPR/RGPD compliant? I know it's possible to delete a user, his computer, etc. Is it possible to delete all data related to one user in a simple way? The same thing would have to apply to plugins if necessary.
The easiest way I see is to rename a user to something like "user_n" (with n an incremental number) and replace occurrences of the user's name and personal data by hand. I just don't know if anonymizing data complies with the regulation.
Also to be compliant, people managing GLPI would have to know exactly where user data is stored (which SQL tables, documents, etc). This information should be available in the documentation.

Thanks

**Comment by trasher** [comment]
What in GLPI is not currently compliant?
Sounds like everything you should want to achieve is already possible. If not, please open a RFE for that point.

GLPI is free software, sources are available, and database is not a kind of blob like some proprietary software; all needed informations are already available.

**Comment by orthagh** [comment]
for reference: https://blogs.mediapart.fr/beta/blog/290418/le-rgpd-guide-pour-les-editeurs-de-logiciels-libres
