### ISSUE TITLE
Tickets criterias bug

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#3592]
Hi,

we are experiencing a problem with multi tech criterias.
glpi v9.2.1
![bug_glpi](https://user-images.githubusercontent.com/3873787/36475388-bd61e9ec-16fa-11e8-95e3-af6d51cadd8b.png)

**Comment by ddurieux** [comment]
It's ok, you can split the search with the _OU_ 
so you have the result of
* tech GIRBEAU

and the result of 
* tech OLLIE
* and statut not closed and not solved
