### ISSUE TITLE
Undefined function CronTask::cronoptimize (for cron)

### ISSUE THREAD

**Issue by nam23690** [glpi-project/glpi#3606]
Dear All,
My GLPI is version 9.2.2. Automatic actions optimize not running. I had check log 'Undefined function CronTask::cronoptimize (for cron)'. Please help me.
Thanks

**Comment by trasher** [comment]
9.2.2 has not been released. Are you sure you run update script properly?

Optimize cron job has been removed and is deleted from the database in update script (https://github.com/glpi-project/glpi/blob/9.2/bugfixes/install/update_921_922.php#L62).

**Comment by yllen** [comment]
Do you used dev version?
Do migration again in command line with
php glpi/scripts/cliupdate.php -- force

**Comment by phep** [comment]
May I draw your attention to the link I gave which points to a (seemingly) non-dev released version and to the "fresh install" words I appended ?

I consequently did not migrate anything. AFAICT it seems the commit pointed to by trasher might have fix the bug for updates but not for fresh installs.

Cheers

**Comment by trasher** [comment]
Indeed; it seems the line is still present in the SQL empty script

**Comment by trasher** [comment]
By the way; running the command @yllen gave you will fix the issue.
