### ISSUE TITLE
Emotes in emails

### ISSUE THREAD

**Issue by Hevelious** [glpi-project/glpi#3609]
When an user sends ticket by email, the description is blanked out after an emote is used.
------------
* Steps to reproduce (which actions have you made) :
Send email with emote f.e. :)

* Expected result :
Emote is still there, description intact.

* Actual result :
Text after emote is removed.

* URL of the page :
Any ticket.

* Screenshot of the problem (if pertinent) :
Can't show  because of ticket content. User :) this text disappears.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.1.6
php 7.0.25
Ubuntu 16.04.1
Apache 2.4.18
MySQL 5.7.21

**Comment by orthagh** [comment]
Hello @Hevelious 

I just tested with 9.2/bugfixes, here the results:
![image](https://user-images.githubusercontent.com/418844/36681796-e4e94e92-1b19-11e8-970f-5405fa225f83.png)

So it seems the code works.

By the way, you are using a non-supported version (9.1.6) and the bug may be already fixed, please check with last version 9.2.1 (or 9.2.2, it will be released this week)

**Comment by Hevelious** [comment]
We will upgrade to 9.2.2 when released, will give info after that.

**Comment by Hevelious** [comment]
We just upgraded our production, the bug still exists.

![1](https://user-images.githubusercontent.com/25429596/37787579-9e6c2cde-2dff-11e8-8f3b-f2027c0187b4.png)
![2](https://user-images.githubusercontent.com/25429596/37787580-9e885e54-2dff-11e8-9e65-8abedee3d160.png)
![3](https://user-images.githubusercontent.com/25429596/37787581-9ea82b6c-2dff-11e8-8f22-9f2c19ac9a52.png)

**Comment by Hevelious** [comment]
The screen capture shows email notification.
The result is the same in GLPI.

When I create a ticket by clicking it trough GUI everything works correctly.
The issue manifests itself when I send the same text with emotes via email.

**Comment by Fchallier** [comment]
I have the same plrobleme here... 
Even if i activate the riche texte in the setup. 

It's impossible tu put an emotes  in the description of the ticket.

**Comment by trasher** [comment]
Just tested mail creation from a collector; and I cannot reprduce any issue:
- txt mail without rich text:
![screenshot-2018-5-3 glpi - tickets - 1101](https://user-images.githubusercontent.com/224733/39562270-ff48409e-4eaa-11e8-9394-6f42b69109a9.png)
- html mail without rich text:
![screenshot-2018-5-3 glpi - tickets - 1102](https://user-images.githubusercontent.com/224733/39562273-082896a0-4eab-11e8-9f8b-3b8b565d5242.png)
- html mail with rich text:
![screenshot-2018-5-3 glpi - tickets - 1103](https://user-images.githubusercontent.com/224733/39562275-100309b4-4eab-11e8-84dc-8d58ed864d30.png)
- text mail with rich text:
![screenshot-2018-5-3 glpi - tickets - 1104](https://user-images.githubusercontent.com/224733/39562305-402f9170-4eab-11e8-9ab9-d83723145d0a.png)

So:
- remove all plugins and test again,
- try with different senders,
- try with another collector on another server.

If you can reproduce, give us *all* informations to reproduce.

**Comment by trasher** [comment]
Also, provide the **raw** email as received by GLPI.

**Comment by Fchallier** [comment]
Thank you for your reply. 

The emoticon like this  :  :) or :-) work fine. 

But when you use Outlook and send a email to the support, the auto correct change this :) to this 😊.

**Comment by orthagh** [comment]
@Fchallier please attach the source of an email send by outlook (see a [tutorial](https://superuser.com/questions/476940/view-raw-message-source-of-an-email-in-outlook-2013).
All our tests also with 😊 emoji failed to replicate

**Comment by Fchallier** [comment]
The orginal message in outlook : 

Test 
Test :)
Test 
😊 
😊 
Test 
Test 

The source  : 

`http://schemas.microsoft.com/office/2004/12/omml" xmlns="http://www.w3.org/TR/REC-html40"><head><meta http-equiv=Content-Type content="text/html; charset=utf-8"><meta name=Generator content="Microsoft Word 15 (filtered medium)"><title>[GLPI #0002561] Nouveau suivi Ticket test ne pas en tenir compte</title><style></style></head><body lang=FR link="#0563C1" vlink="#954F72"><div class=WordSection1><p class=MsoNormal><span style='mso-fareast-language:EN-US'>Test <o:p></o:p></span></p><p class=MsoNormal><span style='mso-fareast-language:EN-US'>Test&nbsp;:)<o:p></o:p></span></p><p class=MsoNormal><span style='mso-fareast-language:EN-US'>Test <o:p></o:p></span></p><p class=MsoNormal><span style='font-family:"Segoe UI Emoji",sans-serif;mso-fareast-language:EN-US'>&#128522;</span><span style='mso-fareast-language:EN-US'> <o:p></o:p></span></p><p class=MsoNormal><span style='font-family:"Segoe UI Emoji",sans-serif;mso-fareast-language:EN-US'>&#128522;</span><span style='mso-fareast-language:EN-US'> <o:p></o:p></span></p><p class=MsoNormal><span style='mso-fareast-language:EN-US'>Test <o:p></o:p></span></p><p class=MsoNormal><span style='mso-fareast-language:EN-US'>Test <o:p></o:p></span></p><p class=MsoNormal><span style='mso-fareast-language:EN-US'><o:p>&nbsp;</o:p></span></p><p class=MsoNormal><span style='mso-fareast-language:EN-US'><o:p>&nbsp;</o:p></span></p></body>`

The result in GLPI  : 
![test_glpi](https://user-images.githubusercontent.com/9974750/39582184-af1a798c-4eed-11e8-87bc-c93d81b96c5e.png)

**Comment by trasher** [comment]
Thanks. Could you please also post the raw data inserted in the database?

**Comment by trasher** [comment]
OK, I give up. Character can not be stored in database; it will appears as `????` Anyways, during our tests, all the data were stored.
I run Linux; I do not have any outlook; and it seems to produce verbose specific HTML while sending emails, it is hard to say what the result will be.

**Comment by trasher** [comment]
Extra note: this may be linked to https://github.com/glpi-project/glpi/issues/140 that cannot be solved for the moment.
