### ISSUE TITLE
To have avatar of the users in the selectable fields for views

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#361]
To add in user list: avatar of the users: to have avatar of the users in the selectable fields for views

**Comment by orthagh** [comment]
Hello @satyan01 
Thanks for theses several suggestions.

I'm a very sorry but i should close them.
We have a dedicated [suggest site](http://suggest.glpi-project.org), if you could post them on that [site](http://suggest.glpi-project.org)

This rule is here to keep this space clean and readable for developpers

That said, if you have pull requests to submit related to these issues, I can keep them

thank you for your understanding.
