### ISSUE TITLE
Remove inline image from a follow up of an Email

### ISSUE THREAD

**Issue by salazar8D** [glpi-project/glpi#3611]
Hi everyone,

I'm having a problem with my version of GLPI. When a user reply an email, if there is a image on the body, the image goes right to attachments on the ticket. I know that's how the program works, however I would like to know if there is a way that I can ignore ONLY the inline images on the body of a reply email of a follow up from the ticket.

Here is my setup :

GLPI 9.2.1 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

**Comment by salazar8D** [comment]
Digging a while I have found a class named mailcollector. In the line 795 there is a step that call a method from the Ticket object. Inside of that class (line 6596) I've found this code:

`   static function convertContentForTicket($content_html, $files, $tags) {

      // We inject another meta tag
      $html = Html::entity_decode_deep($content_html);
      preg_match_all("/src\s*=\s*['|\"](.+?)['|\"]/", $html, $matches, PREG_PATTERN_ORDER);
      if (isset($matches[1]) && count($matches[1])) {
         // Get all image src

         foreach ($matches[1] as $src) {
            // Set tag if image matches
            foreach ($files as $data => $filename) {
               if (preg_match("/".$data."/i", $src)) {
                  $html = preg_replace("`<img.*src=['|\"]".$src."['|\"][^>]*\>`", "<p>".Document::getImageTag($tags[$filename])."</p>", $html);
               }
            }
         }
      }

      return $html;

   }`

I've commented this line:

`$html = preg_replace("`<img.*src=['|\"]".$src."['|\"][^>]*\>`", "<p>".Document::getImageTag($tags[$filename])."</p>", $html);`

but nothing has changed :/

**Comment by salazar8D** [comment]
My problem is that every time that a user makes a follow up via email, the assignature (that's a image) is attached to the ticket. So if my ticket has 15 follow ups, there is 15 images attached to the problem.

**Comment by orthagh** [comment]
Hello @salazar8D 

Some checks to do:
- Do the same picture are duplicated in Management > Documents
  * if no, for this signature picture, you can set "Blacklisted for import = yes" to avoid the behavior
  * if yes, we have a bug

**Comment by salazar8D** [comment]
Here it is an exemple:

![image](https://user-images.githubusercontent.com/30785943/36684429-0f08fdaa-1aff-11e8-9d62-3a810d8cd69d.png)

each employee has his or her own signature.

Ps.: I realize just now that I was writing assignature, not signature. Sorry --'

**Comment by orthagh** [comment]
Ok so no bug but a needed feature here.
I set next major milestone for this need.

We have a feature named "Blacklisted mail content" (available in `Setup > Dropdowns`) which match only on text (replaced by empty string)

We can (technical description for implementation):
- add a type for this blacklisted content (text / regex)
- keep the same behavior for `text` type
- add a `preg_replace` for `regex` type
- manage migration: old `glpi_blacklistedmailcontents` row should have 'text' type
- add tests

With this enhancement, you should be able to add a regex for remonving signature globally.

**Comment by salazar8D** [comment]
Hi @orthagh , thanks again for you reply... So in that case we'll can place a "default signature" of my company and then, every image in the body of an e-mail that's looks like it, will be ignored ? If yes, maybe you guys can place an option to let the user choose between remove that image only from the body or the  attached files... or both maybe. Or am I misunderstanding something ?

**Comment by orthagh** [comment]
no actual `Blacklisted mail content` set only on mail content :D
But attached images must be linked in content to be displayed, so both cases should be covered.

Also, keep in mind we need to work on this enhancement, so maybe we'll do it next release (i set milestone), but it's not an engagement, it will depends on our work charge mainly.

**Comment by salazar8D** [comment]
No problem about the time @orthagh :)
Only still not get it about this:

> So in that case we'll can place a "default signature" of my company and then, every image in the body of an e-mail that's looks like it, will be ignored ?

(ignore the body part u.u This I get it haha)

Yes ? ^^'

**Comment by orthagh** [comment]
i don't understand the "looks like it" part.
Could you precise your idea ?

**Comment by salazar8D** [comment]
Let me show you the problem...

When someone makes a new follow up on the ticket, an email is send to the requester. This is the screen that requester will see in the their webmail if him or her choose to reply by email (Outlook in this case):

![2-1](https://user-images.githubusercontent.com/30785943/36736775-2d4ccbd4-1bb8-11e8-80f4-e4ec40901836.png)

Here the signature of an email is an image which goes at the end of it. But as you can see, the user paste an image on the body, and that image is important, but in the ticket the signature goes with it:

![1-1](https://user-images.githubusercontent.com/30785943/36737857-d44753f8-1bba-11e8-81a5-4ea09ce9b9b3.png)

And as you can see in this email exemple (below) and the image above:

![3-1](https://user-images.githubusercontent.com/30785943/36738760-1821f982-1bbd-11e8-8957-d5017d300515.png)

my ticket begins to fill with documents that doesn't belong to the problem itself.
So, for every follow up make through the webmail, I have an image that's trash for the problem itself.

> if no, for this signature picture, you can set "Blacklisted for import = yes" to avoid the behavior

Your first solucion, for this case, works like charm :D

But here we have 350 employees ... I'll have to do this process for every one of the company. I trought that your solution is to do something like "If the code of that image has (regex here) then ignore that image". In that case, I can place only the default image of the signature and every image from an email that has code similar to regex will be automaticilly ignored by the program.

**Comment by salazar8D** [comment]
Ps.: 350 are my beta testers hahaha The company have around 2100 employees u.u

**Comment by salazar8D** [comment]
I guess I goed too far, right ? haha --' I understand that with your major solution, I'll be able to remove some parts of the content, right ? Something like that ?

**Comment by orthagh** [comment]
Yeah. for pictures, no idea atm.

**Comment by salazar8D** [comment]
I see... So, in the end, this enhancement will do something like:

Email - contant -> "lorem ipsum dolor sit amet consectetur adipiscing elit"
Regex -> "ipsum dolor sit"
Ticket content -> ""lorem amet consectetur adipiscing elit"

That's it ?

**Comment by salazar8D** [comment]
Regardless about the regex situation... The blacklist didn't work in the end:

![1](https://user-images.githubusercontent.com/30785943/36785443-923d8aa2-1c61-11e8-8e64-87a28ff1b350.PNG)

![2](https://user-images.githubusercontent.com/30785943/36785446-96f755be-1c61-11e8-8dcf-ef2c9fbbbc0c.PNG)

I've done something wrong ?

**Comment by arthurrschaefer** [comment]
@salazar8D, have you already tried to use the Rich text for Follow up and tickets. Using it, all the images and signatures are going to be on the ticket body itself.

![image](https://user-images.githubusercontent.com/13874922/39756862-6c36a8f4-52a1-11e8-8a5f-09c1a51b6b9d.png)

If you wanna give it a try.

Setup > General > Assistance > Use rich text for helpdesk

![image](https://user-images.githubusercontent.com/13874922/39756973-ba3e38b4-52a1-11e8-9de9-414aa925302b.png)

**Comment by FRANCOIS50** [comment]
Sorry but the switch to Rich Test doesn't help in my case

**Comment by BlueCatBlog** [comment]
Just for information switching to Rich Text in 9.2.3 solved the problem for me (affect only new tickets).

**Comment by salazar8D** [comment]
Hi you all guys...
@arthurrschaefer , I've already tried it... But the problem still persists.

**Comment by Armin83** [comment]
Do you know this plugin ?
https://github.com/tomolimo/ticketcleaner 
It works for us until i upgrade from 9.1.2 to 9.2.3. (I do not try to activiate it because there is a issue open for 9.2.2 compatibility)

You have to copy your 350 images into a subfolder in the plugin folder
https://github.com/tomolimo/ticketcleaner/wiki#ticket-filters
I have only 5 picture a part of assignature put it works perfect!

IMHO this plugin should be part of the core. It sould get additional feature like block a image for future attachment in the web interface today the glpi admin have to do this. The technician don't have this feature.

**Comment by stdglpi** [comment]
Hello all,

I'm using GLPI 9.5.2 and I have also this problem, I have a lot of picture attached.

Not on all tickets but when it happens it's difficult to follow the discussion.
![lisz9FqGdw](https://user-images.githubusercontent.com/63521311/97151481-d8bce980-176f-11eb-800c-4255c2440506.png)

thank you

**Comment by Ostromix** [comment]
> Hello all,
> 
> I'm using GLPI 9.5.2 and I have also this problem, I have a lot of picture attached.
> the picture appears in the follow-up and and also as an image.
> 
> Not on all tickets but when it happens it's difficult to follow the discussion.
> ![lisz9FqGdw](https://user-images.githubusercontent.com/63521311/97151481-d8bce980-176f-11eb-800c-4255c2440506.png)
> 
> thank you

I have same issue

**Comment by orthagh** [comment]
With the new UI of incoming version 10 of GLPI, this issue should be fixed

**Comment by stdglpi** [comment]
> 
> 
> With the new UI of incoming version 10 of GLPI, this issue should be fixed

Hello @orthagh 

thank you for the feedback ! that's a great news ! 

have a good day
