### ISSUE TITLE
Block\Remove access to user tab personalization

### ISSUE THREAD

**Issue by salazar8D** [glpi-project/glpi#3612]
Hi everyone,

I would like to know if there is a way that can I block\remove the access of the tab personalizations from my users. I have done some modificatins on the layout/rules and I don't want to the users alterate some preferences like: "Pre-select me as Technician when Creating Ticket" and stuffs.

Thank you all

My setup:
:
GLPI 9.2.1 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

**Comment by salazar8D** [comment]
I have found a way that I can do that, but I don't want to make the association on a user_id though... Maybe on a profile_id on something like that ?

Here it's my code edit:

**glpi\front\preference.php -> Starts on line 67**

   if ($_SESSION["glpiactiveprofile"]["interface"] == "central") {
      Html::header(Preference::getTypeName(1), $_SERVER['PHP_SELF'], 'preference');
   } else {
      Html::helpHeader(Preference::getTypeName(1), $_SERVER['PHP_SELF']);
   }
   if(Session::getLoginUserID() == 13){
		$pref = new Preference();
		$pref->display(['main_class' => 'tab_cadre_fixe']);
   }else{
		echo '<div class="center">';
		echo '<br>';
		echo '<br>';
		echo '<img src="/glpi/pics/warning.png" alt="Warning" title="Warning !">';
		echo '<br>';
		echo '<br>';
		echo '<span class="b">You don't have permission to do this action.</span>';
		echo '</div>';
   }
   if ($_SESSION["glpiactiveprofile"]["interface"] == "central") {
      Html::footer();
   } else {
      Html::helpFooter();
   }
}

**Comment by trasher** [comment]
Hello, please use [suggestions website](https://glpi.userecho.com) for RFE.

**Comment by salazar8D** [comment]
https://glpi.userecho.com/communities/1/topics/805-blockremove-access-to-user-tab-personalization

Thanks :)
