### ISSUE TITLE
[9.2.2] Business rules : assign requester group from regex

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#3617]
Hello,

In 9.2.2/bugfix, I wants to assign a requester group on a ticket through business rules with : 
1. Criteria :  Requester in group - regular expression matches - "group*"
2. Actions : Requester group - assign - result of regex in 1.

Currently, requester group actions are : assign, add or copy from item (don't know how to use this last choice).

Could you add an option to permit this behavior ?

**Comment by orthagh** [comment]
Hello @nqb 

1- is easy and already present i think
2- is hard to achieve, regex_result actions are very specific and behavior are hardcoded for each.

Doing a generic regex_result for dropdown is achievable but will need some time of work.

I close this issue for now, could you post your need on suggest.glpi-project.org(link this issue).
We will reopen if popular (or subsidized)
