### ISSUE TITLE
Problème notification mail cloture ticket depusi l'onglet traitement du ticket

### ISSUE THREAD

**Issue by biet-j** [glpi-project/glpi#362]
Bonjour,

Quand nous ouvrons un ticket, une notification est automatiquement envoyée ==> OK
Quand nous allons dans le ticket, onglet "traitement du ticket"(1), puis saisie d'un nouveau suivi (2).
Nous renseignons le suivi et sélectionnons dans le bouton  "ajouter" le menu "cloturer"(3)

![bug_glpi](https://cloud.githubusercontent.com/assets/14232775/12146921/b6abfc00-b496-11e5-9e8f-761f5ef5e444.png)

Une notification de suivi est automatiquement envoyée ==> OK
le ticket est clos automatiquement ==> Ok
Cependant le mail de clôture du ticket ne s'envoie pas. Je n'ai pas de fichier d'erreur dans les log (enfin je pense)

Cordialement.

**Comment by orthagh** [comment]
Pouvez-vous préciser votre version de glpi ?
De plus, un extrait du fichier glpi/files/_log/mail.log concernant ce ticket serait intéressant

**Comment by biet-j** [comment]
Version 0.90.1
Je vous fournirez le fichier log demain quand je serais au travail.

de plus je ne sais pas où poser ma question..... dans mon var/log/ je n'ai pas de dossier glpi.

J'ai vérifié les droits d'écriture mais rien.
Je tiens à précisé que mon installation de glpi est un peu particulière. 
En effet j'ai un glpi pour notre service informatique  ( varr/www/info) et un pour un autre service (var/www/tech) pensez vous que ce type d'installation peut poser problème ? 
Merci

**Comment by biet-j** [comment]
En pièce jointe vous trouverez le mail.log que je viens de faire à l'instant.

bloc 1 ==> Création du ticket ==> notification
Bloc 2 ==> Suivi de mail ==> notification ok
bloc 3 ==> suivi + clôture du mail via l'onglet "traitement du ticket" ==> notification sui + envoi ==> ok, par contre le mail de clôture n'a pas été généré, ni même envoyé.

Cordialement.

[mail.txt](https://github.com/glpi-project/glpi/files/80837/mail.txt)

**Comment by orthagh** [comment]
> En effet j'ai un glpi pour notre service informatique ( varr/www/info) et un pour un autre service (var/www/tech) pensez vous que ce type d'installation peut poser problème ? 

Normalement non

Pour reprendre le sujet initial Quand vous utilisez le processus normal (c'est à dire passer par une solution puis par une approbation de la solution), recevez-vous la notification sur l’événement de clôture ?

**Comment by biet-j** [comment]
Je ne sais pas, je n'utilise pas ce processus.
Par contre, quand je valide mon suivi et que ej retourne dans l'onglet "ticket"(menu principal du ticket) et que je clos le ticket, la notification fonctionne bien .

notre processus: nous recevons un mail ou un coup de téléphone, nous ouvrons le ticket, nous aller dans le suivi et rédigeons l'intervention que nous venons de faire, ensuite si le problème est clos, nous clôturons le ticket.

**Comment by biet-j** [comment]
(nous n'avons pas d'escalade de ticket, ni même de niveau à proprement parler)

**Comment by orthagh** [comment]
ah, en relisant votre ticket, c'est tout à fait normal.

Il ne peux y avoir plusieurs notifications pour un même déclencheur dans glpi.
Dans ce cas précis, c'est le suivi qui est priorisé et vous recevez donc la notification correspondante.

Par contre, quand vous repassez par le formulaire principal du ticket et que vous passez sur clos, vous effectuer une seconde action manuelle (en plus du suivi) et donc vous avez la notification dédiée.

**Comment by biet-j** [comment]
Donc si on passe par le "traitement du ticket ajouter un suiv et clore le ticket, nous ne recevons plus la notification de cloture?

La version précédente (0.85.x) j'utiliser le plugin "discussion (talk en anglais je crois)"
Ce plugin permettait d'envoyer les deux notifications en même temps: le suivis en queuedmail et la cloture en direct (comme l'ouverture) 
Il est vrai qu'avec ce plugin les mails se chevauchaient à des moments (cloture avant le suivi) mais ca fonctionnait.
Est-il possible de modifier le comportement de GLPI pour se calquer sur cette fonctionnalité?

Si ce n'est pas possible, nous reviendrons dans le menu général du ticket afin de clore ces tickets.

Merci en tout cas

**Comment by biet-j** [comment]
Je reviens vers vous sur ce sujet est-il possible de pouvoir envoyer une notification de suivi ET une notification de clôture en même temps depuis le module discussion?

Pour le moment nous revenons dans le menu principal du ticket afin de le clore.

Merci 

Cordialement.

**Comment by Riesuu** [comment]
Bonjour,
je ne sais pas si c'est suite à la maj en 0.90.1 ou à mes tests à faire joujou avec les enquêtes de satisfaction.Mais effectivement je ne reçoit plus de notifications de clôture lorsque je ferme le ticket via l'onglet "traitement du ticket", or quand je le ferme via l'onglet ticket, ça fonctionne.

**Comment by yllen** [comment]
Autre demande concernant la cloture depuis le traitement du ticket : http://forum.glpi-project.org/viewtopic.php?id=147288

**Comment by StephaneAtlani** [comment]
Bonjour,

Nous sommes en version 9.1.1 et de notre coté nous avons nous aussi ce comportement. 
Nous souhaiterions que dans la partie "Traitement du ticket" quand nous passions le ticket à l'état "Clos" un mail soit expédié. (ce qui fonctionne très bien avec l'état résolu, mais nous ne l'utilisons pas dans notre processus). 

est qu'il y un moyen simple de le faire ?

Cordialement,

**Comment by johannsan** [comment]
Bonjour.
Problème surement similaire en 0.90.5 ou 9.1 : (et solution proposée?)
http://forum.glpi-project.org/viewtopic.php?pid=327992#p327992

Cordialement
