### ISSUE TITLE
Error on Super-Admin profile mode, white screen

### ISSUE THREAD

**Issue by origamaster** [glpi-project/glpi#3620]
Hello there, I update my GLPI to 9.2.1 on this friday, but after the weekend when I arrived this morning when I change to Super-Admin profile the webpage below the GLPI logo turns white, I'll attach a screenshot below : 

After this, I opened the debug mode on GLPI and the following message was returned : 

Fatal error: Uncaught Zend\I18n\Exception\OutOfBoundsException: Provided index 1 does not exist in plural array in /var/www/html/hbmbug/vendor/zendframework/zend-i18n/src/Translator/Translator.php:363 Stack trace: #0 /var/www/html/hbmbug/inc/autoload.function.php(196): Zend\I18n\Translator\Translator->translatePlural('Kernel version', 'Kernel versions', 2, 'glpi') #1 /var/www/html/hbmbug/inc/dropdown.class.php(980): _n('Kernel version', 'Kernel versions', 2) #2 /var/www/html/hbmbug/inc/commondropdown.class.php(111): Dropdown::getStandardDropdownItemTypes() #3 /var/www/html/hbmbug/inc/html.class.php(1364): CommonDropdown::getMenuContent() #4 /var/www/html/hbmbug/inc/html.class.php(5948): Html::generateMenuSession() #5 /var/www/html/hbmbug/inc/html.class.php(1468): Html::displayMainMenu(true, Array) #6 /var/www/html/hbmbug/front/central.php(73): Html::header('Interface padr\xC3...', '/hbmbug/front/c...', 'central', 'central') #7 {main} thrown in /var/www/html/hbmbug/vendor/zendframework/zend-i18n/src/Translator/Translator.php on line 363

* Steps to reproduce (which actions have you made) :
I didn't do anything abnormal, it stopped working after the weekend

* Expected result :
Expected to work the Super-Admin profile mode

* Actual result :
Super-Admin profile mode didn't work resulting on the screenshot attached

* URL of the page :
http://10.101.1.15/hbmbug/front/central.php

* Screenshot of the problem (if pertinent) :
![print glpi](https://user-images.githubusercontent.com/23563582/36669485-d2f6630a-1ad3-11e8-8013-aeb06e41652e.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
I can't access the setup area.

**Comment by trasher** [comment]
Make sure to restart PHP; it may be a cache/opcode issue.

**Comment by origamaster** [comment]
hi there trasher, I alredy did that and still not working.

**Comment by trasher** [comment]
Already fixed for 9.2.2; see https://github.com/glpi-project/glpi/issues/3483

**Comment by origamaster** [comment]
hi there trasher, well, when I tried the bugfix for 9.1, I got a message "SQL strict mode is not fully enabled, recommended for development: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER"

**Comment by trasher** [comment]
First, I was talking about 9.2; not 9.1. 
And second, this is normal, this is not a stable release.

You can wait for 9.2.2 to be released (**should** be this week or next week).
