### ISSUE TITLE
Hide field 'by' from Ticket

### ISSUE THREAD

**Issue by salazar8D** [glpi-project/glpi#3631]
Hello Guys !

I don't know if it is a issue or a lack of knowledge by my side, but I can't find a "switch button" to hide or set default user as requester on the 'By' field.

![9](https://user-images.githubusercontent.com/30785943/36753194-3d10dea8-1be4-11e8-88ea-8a48398e65dc.PNG)

The real problem is that I can't allow my user (is this case a Technician) to edit this field area. I have passed on a situation that my technician assigned that field to himself and has approved the solution that him sugested.

Here the conf of my Tech profile:

![9](https://user-images.githubusercontent.com/30785943/36753475-04d6a684-1be5-11e8-8c96-064baeb1566a.PNG)

and the template of a ticket:

![9](https://user-images.githubusercontent.com/30785943/36753514-234b610e-1be5-11e8-8dec-89a5b4e1d540.PNG)

Thank you all

**Comment by Favid1** [comment]
Hello,
Did you find any solution?
Thanks
