### ISSUE TITLE
Ticket clarification feature

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#3632]
Hello.
I need an additional feature: an clarification on ticket.

The fact is that the information in existing notification templates is too redundant in such a situation - users get confused in the text of the notification and do not understand that they need to answer the clarifications written in the comments.
Moreover, it may be necessary to send a letter with clarifications to only certain people or add to the copy of someone who is not a member of ticket.

The question is, how best to implement this: as plugin or in the main code and do PR?
What do you think?

**Comment by Armin83** [comment]
I'm not sure want you want. If we need further information we write an followup (not private) to ask the requester about more information. (I changed many notification templates because the default mail is to difficult to read easy and fast.)

**Comment by hartois** [comment]
1. Our supporters want to send an additional copy of the mail to users (or e-mails), which they will choose (for example, the head of the customer), that does not requesters or observers of this ticket.
2. They want these emails to differ from the usual followups.
There are some users and observers who receive a large number of mails with notifications and it is very easy to miss a mail that requires some action.
Therefore, we want this to be a separate notification, with a separate template and accordingly a separate subject of the notification mail.

**Comment by trasher** [comment]
Current notification process is very complicated and must be rewritten, this is planned... But we really do not know when it can be done (see ).
Since such a request will make the process a bit more complex; I guess this should be included in core, but while rewritting. Until that, a plugin may do the job.

What do you think?

**Comment by trasher** [comment]
I was sure a ticket exists on notfication rewrite... But seems I was wrong. So, I create it, see: https://github.com/glpi-project/glpi/issues/3662

**Comment by hartois** [comment]
OK. I'll try to implement the plugin for this and I'll wait for the rewrite of the notification system.
