### ISSUE TITLE
Composer.json file missing

### ISSUE THREAD

**Issue by DIOHz0r** [glpi-project/glpi#3639]
* Steps to reproduce (which actions have you made) :
Download the [glpi-9.2.1.tgz](https://github.com/glpi-project/glpi/releases/download/9.2.1/glpi-9.2.1.tgz) and uncompress it

* Expected result :
Find the composer.json file on the root directory

* Actual result :
No composer.json file available

**Comment by trasher** [comment]
Composer file is not provided in the release archive, this is intended.
