### ISSUE TITLE
[0.90.1] Éléments associés en vue classique

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#364]
Bonjour,
Si un utilisateur utilise la disposition "vue classique", lorsque ce dernier clique sur la flèche à droite de "Éléments associés" (mise à jour) dans un ticket, il ne se passe rien. L'onglet "Éléments" n'est pas automatiquement sélectionné comme c'est le cas avec les deux autres disposition : séparation verticale et onglets sur la gauche.
Testé avec : 
- Firefox 38.5.2
- Chrome 33
- IE 11

**Comment by yllen** [comment]
No problem with firefox

**Comment by orthagh** [comment]
It should be better
