### ISSUE TITLE
[9.2.2] Bad french translations for "Public/Private Saved searches"

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#3641]
Hello,

In 9.2.2, when you have several saved searches (private and public), french translation are : 
* Recherches sauvegardées publique
* Recherches sauvegardées privée

Should be (missing *s*) : 
* Recherches sauvegardées publique*s*
* Recherches sauvegardées privée*s*

**Comment by trasher** [comment]
Translations are done on transifex ;)

**Comment by nqb** [comment]
@trasher, 

there is already a translation for "Public Saved searches" : 

https://github.com/glpi-project/glpi/blob/39d4ad46a5e5f4ea326ea7b8bcaeccf59deb6b1f/locales/fr_FR.po#L15259

However, files mentioned seems no related to `front/savedsearch.php` or `ajax/savedsearch.php`

**Comment by nqb** [comment]
Certainly : 
https://github.com/glpi-project/glpi/blob/39d4ad46a5e5f4ea326ea7b8bcaeccf59deb6b1f/inc/savedsearch.class.php#L764
https://github.com/glpi-project/glpi/blob/39d4ad46a5e5f4ea326ea7b8bcaeccf59deb6b1f/inc/savedsearch.class.php#L771
