### ISSUE TITLE
[0.90.1] Régression : texte non conservé lors de changement d'onglet

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#365]
Bonjour,
En 0.90.1 sur la partie Assistance, si on écrit du texte dans un bloc de texte sur un onglet sans le sauvegarder, le passage à un autre onglet fait perdre le texte saisi.
Exemple : 
1. Écriture du texte dans un suivi (sans le sauvegarder)
2. Vérification d'une information dans un autre onglet que "Traitement du ticket"
3. Retour sur l'onglet "Traitement du ticket" : le texte saisi à l'étape 1 n'est plus présent.

Ce comportement a changé entre la version 0.84 et 0.90. En 0.84, le texte était conservé.

**Comment by cdlabal** [comment]
Effectivement, je confirme qu'il s'agit d'une régression. +1 donc

**Comment by orthagh** [comment]
fixed in 45b4b87
