### ISSUE TITLE
[9.2.2] pictures issue is back

### ISSUE THREAD

**Issue by ppenin** [glpi-project/glpi#3652]
On 9.2.2 (update from 9.2.1), mails collected with pictures embedded in the body give an issue.
Many posts on the subject but I don't understand why it's back with this new release.

![image](https://user-images.githubusercontent.com/22499638/36859787-bf539b84-1d7f-11e8-8d16-c30e39ff3134.png)

![image](https://user-images.githubusercontent.com/22499638/36859808-d127b7dc-1d7f-11e8-8fb8-714a66bc5d95.png)

the path is not correct
http://10.100.10.18/usr/share/glpi/front/document.send.php?docid=8192&tickets_id=21143
instead of 
http://10.100.10.18/glpi/front/document.send.php?docid=8192&tickets_id=21143

**Comment by trasher** [comment]
It is not back on 9.2.2; it has not been fixed.
Duplicates https://github.com/glpi-project/glpi/issues/3653
