### ISSUE TITLE
Incorrect image path when calling mailcollector from cron

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#3653]
When an image is inserted from a cron call; its path gets incorrect: it references the filesystem path.

See:
https://github.com/glpi-project/glpi/issues/1929
https://github.com/glpi-project/glpi/issues/3240
https://github.com/glpi-project/glpi/issues/3652

And especially: https://github.com/glpi-project/glpi/issues/1929#issuecomment-361683386

A possible solution (need investigations):
https://github.com/glpi-project/glpi/issues/1929#issuecomment-369024198
https://github.com/glpi-project/glpi/issues/3240#issuecomment-367757518

**Comment by ciadch** [comment]
👍  with this solution : https://github.com/glpi-project/glpi/issues/1929#issuecomment-369024198

**Comment by trasher** [comment]
Sound like the solution finally does not work.

**Comment by ciadch** [comment]
This works (but I'm not sure it's what you want) : 
![image](https://user-images.githubusercontent.com/12936546/37039328-7bda60dc-2157-11e8-9dcc-df4f4445329d.png)

In notification queue it works : 
```
<p> <a href="https://mysite/front/document.send.php?docid=633&tickets_id=2611" target="_blank"><img alt="ef5ae96b-779444d6-5a9ead1d1e9779.36432813" height="69" width="356" src=""https://mysite/front/document.send.php?docid=633&tickets_id=2611" /></a></p><p> </p>
```
And in followup too : 
![image](https://user-images.githubusercontent.com/12936546/37039455-cec496aa-2157-11e8-8fd5-bf1cb3ef0712.png)

**Comment by edgardmessias** [comment]
`inc/notificationeventmailing.class.php` use only `$CFG_GLPI['url_base']`

**Comment by edgardmessias** [comment]
Example URL: http://mydomain.org/glpi/index.php
* `$CFG_GLPI['root_doc']` every return `/glpi`
* `$CFG_GLPI['url_base']` every return `http://mydomain.org/glpi` (See config)

**Comment by edgardmessias** [comment]
@trasher, I have a solution.

If is set `$CFG_GLPI['url_base']`, use the `parse_url` function to get only the `path`

**Comment by edgardmessias** [comment]
@trasher, for e-mails notifications, see #3694.

My idea:
* Revert to use `$CFG_GLPI['root_doc']`
* Edit the `config.php`, to after load config from DB, check is from command line, if yes, use `parse_url($CFG_GLPI['url_base'])`  to update `$CFG_GLPI['root_doc']` with `path` part

**Comment by edgardmessias** [comment]
@trasher, check #3714 and #3694

**Comment by ppenin** [comment]
I applied change https://github.com/edgardmessias/glpi/commit/9f90e700dffdda526cf9175237d16d958b9474a4
It solves the issue in GLPI ticket but not in mail 
![image](https://user-images.githubusercontent.com/22499638/37471088-43806c86-2869-11e8-8b0a-e7427732b4c0.png)

![image](https://user-images.githubusercontent.com/22499638/37471109-513042e8-2869-11e8-95ae-09327502d042.png)

Mail converted in html.
The source begins with /glpi instead of http://servername/glpi
![image](https://user-images.githubusercontent.com/22499638/37471370-d76f045c-2869-11e8-8538-e2a82fb3bf2b.png)

**Comment by edgardmessias** [comment]
@ppenin, ser #3694

**Comment by ppenin** [comment]
i applied #3694. It solves the issue with the pictures in mails. It's ok now.
But, automatic tasks mailgate and queuednotification stills hang when a mail with more than a picture is collected. The mail is collected but not deleted. So if we run manually mailgate task, the mail is collected again and appears twice (two tickets).
It's very boring because we have to check the tasks all day et run manually, delete double tickets and so on...

**Comment by edgardmessias** [comment]
Without patch, not duplicate issues?

**Comment by ppenin** [comment]
yes same issue. I opened the  ticket #3494.
This issue never happened before 9.2

**Comment by husisusi** [comment]
Fixed root_doc from command line (Close #3653)  fixes this!!!
You have to add in  inc/config.php line 157:
+      // Fix root_doc from command line
+      if (isCommandLine() && isset($CFG_GLPI['url_base'])) {
+         $path = parse_url($CFG_GLPI['url_base'], PHP_URL_PATH);
+         if (!$path) {
+            $path = "";
+         }
+         $CFG_GLPI["root_doc"] = rtrim($path, '/');
+      }

i can't understand why just the fix on inc/html.class.php is included in the new GLPI version without  inc/config.php fix???? Its one FIX 
https://github.com/edgardmessias/glpi/commit/9f90e700dffdda526cf9175237d16d958b9474a4

**Comment by trasher** [comment]
@husisusi see https://github.com/glpi-project/glpi/pull/3714.

**Comment by husisusi** [comment]
Is there no solution to this issue?

**Comment by FRANCOIS50** [comment]
HI if a read this issue solution I understand that you decided that in version 9.2.2, embedded ticket images are converted to attached images in the follow-up of the ticket?

Is that correct?

**Comment by troublestarter** [comment]
cool ! Will check this

**Comment by risbac** [comment]
In my 9.2.3 version, it's still not fixed. The url is still missing "/glpi", and all images are not displayed. So the fix that was published is not working in all cases. Apparently the function that was modified is not even running (I modified it manually to display something, and nothing happened).

**Comment by troublestarter** [comment]
not functionnal...

**Comment by rjmontenegro** [comment]
Work for me
