### ISSUE TITLE
Does not change a ticket status

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3655]
Hello!
Does not change the status of a ticket after assigned ticket itself. Even after wrote followup with chenging the status on "Processing (assigned)".
This problem is in 9.1.4 and 9.2.2.

![glpi - tickets - 32 - mozilla firefox 2018-03-02 11 42 42](https://user-images.githubusercontent.com/17082164/36890877-a2a10562-1e10-11e8-91ff-778f6d9962c7.png)

![glpi - tickets - 32 - mozilla firefox 2018-03-02 11 50 20](https://user-images.githubusercontent.com/17082164/36890888-b26c0320-1e10-11e8-8b5a-6a9c47701c60.png)

![glpi - tickets - 32 - mozilla firefox 2018-03-02 11 49 33](https://user-images.githubusercontent.com/17082164/36890895-b73fc7c4-1e10-11e8-89f9-6da50c382360.png)

Rights of the profile:
![glpi - profiles - 6 - google chrome 2018-03-02 11 36 18](https://user-images.githubusercontent.com/17082164/36891044-2f950f5e-1e11-11e8-8174-bab7b55f7e86.png)

**Comment by orthagh** [comment]
Hello @AircraftRu 
Indeed without UPDATE right, the assignment seems to no trigger status change.

I tag this issue as bug and milestone it.

**Comment by AircraftRu** [comment]
Hi @orthagh! Thanks a lot! It works!

**Comment by AircraftRu** [comment]
Hi @orthagh 

If I have these rights:

![glpi - profiles - 6 - google chrome 2018-03-05 15 14 25](https://user-images.githubusercontent.com/17082164/36974701-9fd796c8-2088-11e8-8611-81ba228a8357.png)

Doesn't change the status again:

![glpi - tickets - 32 - mozilla firefox 2018-03-05 15 14 44](https://user-images.githubusercontent.com/17082164/36974747-d1f5399e-2088-11e8-81cc-59fb1c72edc4.png)

![glpi - tickets - 32 - mozilla firefox 2018-03-05 15 15 16](https://user-images.githubusercontent.com/17082164/36974750-d505cdc4-2088-11e8-86c7-60577d0dd53b.png)

**Comment by orthagh** [comment]
Currently working on a solution.
I'll amend #3666 when done

**Comment by orthagh** [comment]
done

**Comment by AircraftRu** [comment]
Yes, it's done. Thank you for the work!
