### ISSUE TITLE
Rework notifications

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#3662]
Current notification system is buggy and very hard to maintain/understand.

What should be done:
- rework the way recipients are managed (especially remove the add/drop ugly stuff),
- send lighter notifications by default,
- use a templating system,
- ... ?

**Comment by edgardmessias** [comment]
More control for the user by notification type (all, ignore my, when observe, ....)

**Comment by allanlopesprado** [comment]
Notification of calls awaiting evaluation
Listbox - 1 week, 2 weeks, .... 1 month

Notification, something like

Hello, ##ticket.authors##
You have ##open.satisfaction## open satisfaction survey, to answer access ## ticket.urlsatisfaction ##
List: ##list.open.satisfaction## 
Thanks for answering

**Comment by EC2311** [comment]
Hello
Depending of the status (of project, of ticket) differents users or groups defined in the ticket or project itself may received the notification : not all users or all groups may receive notifications.. It should be great :)

**Comment by nbriche** [comment]
Hello,

Another suggestion: Overriding the reply-to address for a notification trigger.

For example, setting the ticket closing notification to a noreply would force the user to click a link to access the ticket, resulting in a lot less reopenings due to "thank you" replies.

Doing the same to solutions would also force the user to actually go and approve/reject the solution instead of just adding a followup.

**Comment by trasher** [comment]
Ths ticket is about rewriting the complex notifications system; we plan to privde same features that existing, not to add anything new.
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by TarasSavchuk** [comment]
I believe the possible way to improve notification system is by integrating it in business rules for tickets.
Pros:
* we already have a lot of criteria here, i.e. we can match any ticket fields to decide if we need to send notifications (priority, etc) - very flexible notifications possible.
* this approach can be implemented without touching existing notification system.
We already have some notifications integrated there (sending approval requests). What would be great is to implement general action "send email with proper recipients (requestor, agent, agent group, etc)".
