### ISSUE TITLE
HTML code elements in the Notes field in GLPI 9.2.1 and after update for 9.2.2

### ISSUE THREAD

**Issue by gabrielranulfo** [glpi-project/glpi#3663]
Issue Started after updating GLPI 9.1.6 for 9.2.1 in November of 2017 and now in updating to 9.2.2

Some HTML elements appear in the Notes field, the problem comes from version 9.2.1 and maintained in version 9.2.2.

![image](https://user-images.githubusercontent.com/31252711/36920968-4bf051a6-1e41-11e8-9641-e17741a7476d.png)

**Comment by trasher** [comment]
I can reproduce using chromium, but only when just logged in. Just refreshing the page get the issue solved.

**Comment by gabrielranulfo** [comment]
I using Chrome, and on firefox, updating the page the issue it's resolved but  is an solution palliative

**Comment by edgardmessias** [comment]
Maybe problem with cache of TinyMCE.

Add `cache_suffix: '?v=".GLPI_VERSION."',` in `tinyMCE.init` of `inc/html.class.php`

**Comment by gabrielranulfo** [comment]
applied the solution, but the problem continues

**Comment by edgardmessias** [comment]
@gabrielranulfo, You can send the console log of browser?

**Comment by gabrielranulfo** [comment]
yes, one minute

**Comment by gabrielranulfo** [comment]
here is the error

![git](https://user-images.githubusercontent.com/31252711/37156415-ce7d0a2e-22c4-11e8-9fee-83641d1e83c0.jpg)

**Comment by gabrielranulfo** [comment]
please, see also the box position is wrong

**Comment by edgardmessias** [comment]
@gabrielranulfo, in Network tab, has some file with "tiny"?

**Comment by edgardmessias** [comment]
@gabrielranulfo, reinstall the `lib` folder.

Your problem is the TinyMCE is not loaded

**Comment by gabrielranulfo** [comment]
I installed another lib, but the problem only remains on the incognito tab

**Comment by edgardmessias** [comment]
@gabrielranulfo, you can send network tab? Filter by "tiny"

**Comment by gabrielranulfo** [comment]
here is the archive =] 
[tinymce.min.js.txt](https://github.com/glpi-project/glpi/files/1803750/tinymce.min.js.txt)

**Comment by edgardmessias** [comment]
I want to see the load sequence, not the file

**Comment by edgardmessias** [comment]
@trasher, the problem is on first load only, the #3704 resolve the problem.

First load, `$_SESSION['glpi_js_toload']` not contains `tinymce`, on page refresh, is ok

**Comment by gabrielranulfo** [comment]
issue resolved after altereding the line 431 of the archive /inc/define.php from :  'central'   => ['fullcalendar','tinymce']

**Comment by trasher** [comment]
Will be closed automatically once proposed fixes will reach glpi repository ;)

**Comment by gabrielranulfo** [comment]
sorry
