### ISSUE TITLE
Link a project task from the ticket

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#3665]
To be able to link a project task to a ticket from the ticket.

The tab "project tasks" in the ticket was added following this request (https://forge.glpi-project.org/issues/5260) 
Related commit : 
- First commit with adding the form to add a task (https://github.com/glpi-project/glpi/commit/be8d238975d6b7cf82e13004395563badff5cd94)
- Second commit with the commented project task addition form (https://github.com/glpi-project/glpi/commit/3611727844ecbf8a845ece0b924278ba7c6e7476)

Any particular reason for this suppression of adding project task in the ticket?

**Comment by trasher** [comment]
Since commits messages are not explicit at all; it almost impossible to know why this has been dropped

**Comment by amma35** [comment]
Can I propose a PR to add this feature?
