### ISSUE TITLE
[9.2.2] A lot of errors from automaticaly action "ldap_mass_sync.php"

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3672]
GLPI 9.2.2
I use "ldap_mass_sync.php" through cronetab of Ubuntu:
`* 20 * * 0,3,5 root php -q -f /var/www/glpi922/scripts/ldap_mass_sync.php`

php-errors.log grew up until 461 MB:
```
2018-03-06 07:05:07 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1645                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-06 07:05:07 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1630                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-06 07:05:30 [@glpi]
  *** PHP Warning(2): ldap_search(): Search: No such object
  Backtrace :
  :                                                  
  inc/authldap.class.php:1595                        ldap_search()
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
```

**Comment by AircraftRu** [comment]
It goes on:
`2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1630                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1645                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1630                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1645                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1630                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1645                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()
2018-03-25 13:06:15 [@glpi]
  *** PHP Notice(8): Undefined index: modifytimestamp
  Backtrace :
  inc/authldap.class.php:1630                        
  inc/authldap.class.php:1739                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:157                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:118                     import()`

**Comment by cedric-anne** [comment]
Hi,

Can you tell me if the following changes fixes your issue ?
```diff
diff --git a/inc/authldap.class.php b/inc/authldap.class.php
index c97da783f..a490cf28a 100644
--- a/inc/authldap.class.php
+++ b/inc/authldap.class.php
@@ -1627,7 +1627,7 @@ class AuthLDAP extends CommonDBTM {
                   }
 
                   $user_infos[$uid]["timestamp"] = self::ldapStamp2UnixStamp(
-                     $info[$ligne]['modifytimestamp'][0],
+                     $info[$ligne]['modifyTimestamp'][0],
                      $config_ldap->fields['time_offset']
                   );
                   $user_infos[$uid]["user_dn"] = $info[$ligne]['dn'];
@@ -1642,7 +1642,7 @@ class AuthLDAP extends CommonDBTM {
                   } else {
                      //If ldap synchronisation
                      $ldap_users[$uid] = self::ldapStamp2UnixStamp(
-                        $info[$ligne]['modifytimestamp'][0],
+                        $info[$ligne]['modifyTimestamp'][0],
                         $config_ldap->fields['time_offset']
                      );
                      $user_infos[$uid]["name"] = $info[$ligne][$login_field][0];
```

I have no LDAP installed to test against, so I cannot test this fix.

Regards

**Comment by cedric-anne** [comment]
@AircraftRu 

Could you test the solution I proposed on my previous comment ?

Regards

**Comment by chauchse** [comment]
Dear,

I have se same error. Even if I fix, i still have problem.
`  *** PHP Notice(8): Undefined index: modifyTimestamp
  Backtrace :
  inc/authldap.class.php:1644
  inc/authldap.class.php:1755                        AuthLDAP::searchForUsers()
  scripts/ldap_mass_sync.php:153                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:114                     import()
 Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: modifyTimestamp
`

**Comment by trasher** [comment]
`modifyTimestamp` attribute is explicitely required in the query. But it is missing in the results; this sounds like something specific on your ldap server configuration.

Following patch may solve the notice. Please note that `modifyTimestamp` may be really required; make tests.
```diff
index 9885e985cd..f567ab0634 100644
--- a/inc/authldap.class.php
+++ b/inc/authldap.class.php
@@ -1636,7 +1636,7 @@ class AuthLDAP extends CommonDBTM {
                   }
 
                   $user_infos[$uid]["timestamp"] = self::ldapStamp2UnixStamp(
-                     $info[$ligne]['modifytimestamp'][0],
+                     (isset($info[$ligne]['modifyTimestamp']) ? $info[$ligne]['modifytimestamp'][0] : ''),
                      $config_ldap->fields['time_offset']
                   );
                   $user_infos[$uid]["user_dn"] = $info[$ligne]['dn'];
@@ -1651,7 +1651,7 @@ class AuthLDAP extends CommonDBTM {
                   } else {
                      //If ldap synchronisation
                      $ldap_users[$uid] = self::ldapStamp2UnixStamp(
-                        $info[$ligne]['modifytimestamp'][0],
+                        (isset($info[$ligne]['modifyTimestamp']) ? $info[$ligne]['modifytimestamp'][0] : ''),
                         $config_ldap->fields['time_offset']
                      );
                      $user_infos[$uid]["name"] = $info[$ligne][$login_field][0];
```

**Comment by trasher** [comment]
No feedback from a while, closing.
