### ISSUE TITLE
Can't assigned ticket to two or more users without saving - 9.2.2. 

### ISSUE THREAD

**Issue by dilona** [glpi-project/glpi#3680]
Hello!
I have upgraded my GLPI from 9.2.1 to 9.2.2. When you want assigned ticket to several users, you need click add, save, add, save... Doesn't work "add"-button two or more times.
![image](https://user-images.githubusercontent.com/31918974/37036540-06b94cb4-2161-11e8-8d15-d43edcd37a69.png)

Software:
![image](https://user-images.githubusercontent.com/31918974/37036793-bcf6391a-2161-11e8-8eea-85f5ba3b1c64.png)

**Comment by trasher** [comment]
Please use [suggestions website](http://suggest.glpi-project.org) for feature request.
