### ISSUE TITLE
[Cache] Userprofilepictures are not cached

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#3683]
* Steps to reproduce (which actions have you made) :
Open ticket.php with no search filter.

* Expected result :
Userprofile Pictures should be cached and not be reloaded on every request.

* Actual result :
Userprofile is reloaded on every page load and not in cache.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.1.6

**Request** URL:https://..../front/document.send.php?file=_pictures/23/435_592482164d823_min.jpg
Request Method:GET
Status Code:200 
Remote Address:....:443
Referrer Policy:no-referrer-when-downgrade
**Response**
cache-control:private, must-revalidate
content-disposition:filename="23/435_592482164d823_min.jpg"
content-length:2363
content-type:application/octetstream
date:Wed, 07 Mar 2018 08:50:13 GMT
**expires:Mon, 26 Nov 1962 00:00:00 GMT**
pragma:private
server:Apache/2.4.25 (Debian)
status:200
x-powered-by:PHP/5.6.30-0+deb8u1

Caching is enabled by apache conf:
ExpiresByType image/jpg ...
ExpiresByType image/jpeg ...

Where is the 1962 comming from ?

**Comment by edgardmessias** [comment]
GLPI 9.2 solved this.

See the `sendFile` method in `inc/toolbox.class.php`

**Comment by Eon9D** [comment]
@edgardmessias Thanks for the information! I'll try to migrate.
