### ISSUE TITLE
fr_FR.po : translation error

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#3684]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.

------------
* Steps to reproduce (which actions have you made) :
Go on the file : locales/fr_FR.po

* Expected result :
Line 11438 : Le champ description est obligatoire
There is a mistake on the word : olbigatoire

* Actual result :
Line11438 : Le champ description est olbigatoire

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

**Comment by trasher** [comment]
Please use [transifex](https://www.transifex.com/glpi/GLPI/dashboard/) for translation issues.
