### ISSUE TITLE
add informations to telemetry

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#3685]
some ideas:
- mysql engine: innodb/myisam
- is it an update or a new installation ?

**Comment by AnaelMobilia** [comment]
Hello,

+1
I suggest (too) to add a 0-1 (or 0) counter for the usages stats (known if low usage or no usage of the feature)

Regards,
Anael

**Comment by AnaelMobilia** [comment]
@orthagh Could you, please, give more explaination for the "update or new install" part ?

As I understand it, we want to know if the user made of fresh newly install or update from a previous version.
On this meaning, two cases :
  - User update from a non telemetry version => no instance UUID == we can detect it and send
