### ISSUE TITLE
Menu Observateur: Bloqué l'affichage uniquement des superviseurs

### ISSUE THREAD

**Issue by biet-j** [glpi-project/glpi#369]
Bonjour,

Dans notre façon de travailler, nous aimerions qu'un utilisateurs puisse créer un ticket et assigner son superviseur  à ce même ticket.

Le groupe A contient:
toto
tata
titi
tutu

Le superviseur du groupe A est : tutu

quand toto, avec son profil post-only créer un ticket, je voudrais qu'il puisse choisir son superviseur (tutu) en observateur (mais qu'il ne puisse voir uniquement tutu)

Ce n'est pas très "pro" comme demande mais j'ai trouvé que c'était la plus simple et compréhensible.

Merci

Cordialement.

**Comment by orthagh** [comment]
Bonjour.

Nativement il est impossible de faire ce choix du seul superviseur.
Pensez la création de ticket comme un mail, et les obervateurs comme un champ CC.
Rien n'empeche vos utilisateur de mettre leurs contacts en CC.
Bon dans glpi, la liste est limité au membres de leur groupe, mais l'idée est la.
