### ISSUE TITLE
CSV export only exports one value for a field with multiple values

### ISSUE THREAD

**Issue by joopmartens** [glpi-project/glpi#370]
When exporting a table including fields with multiple values into CSV format only the first value of the field is included in the CSV export.

E.g. a software query including a global search criteria of computer-name for each line of software multiple computers are included in the computer-name field. Only the first computer of the computer-name fiels is included in the CSV export.

The PDF export includes all values correctly.

Currently running Glpi 0.90.1

**Comment by orthagh** [comment]
Sorry for the delay of this answer.
I can't replicate your behavior on 0.90/bugfixes (neither on 0.90.1 tag). 

Could you precise the definition of your search (with a screenshot) ?
And extract a part of your csv ?

**Comment by joopmartens** [comment]
This is embarrassing.
Now i try to reproduce the issue to create screenshots I found out that not only one value is included in the csv file but only one value is shown because the cell is only one textline high.
After resizing the cell all values are shown in the csv export.

My apologies for the false bug report.

**Comment by orthagh** [comment]
Ok. No need to worry :)
