### ISSUE TITLE
[9.2.2] Doesn't remove a file from _tmp

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3700]
Hello!
Doesn't remove a file from `_tmp` after added the file. Automatic Action `temp` also changes nothing.

![image](https://user-images.githubusercontent.com/17082164/37271613-989ee508-25e4-11e8-869b-7a3f82a413b7.png)

![image](https://user-images.githubusercontent.com/17082164/37271593-8b14bed0-25e4-11e8-9f56-e883b16ca327.png)

**Comment by AircraftRu** [comment]
Somehow the folder has cleared after one hour

**Comment by edgardmessias** [comment]
@AircraftRu, whats the problem? Steps to reproduce?

GLPI has in "Setup => Automatic Actions" a action called "temp" to clear temporary files

**Comment by AircraftRu** [comment]
No problem, it's work, files are removed.

**Comment by brunohmg89** [comment]
Hello,

I have a similar problem, when I try to insert any file they go to the _tmp folder but they are not moved to their folders such as PNG.

In the WEB interface it doesn't load any error message, it just doesn't load any file to the system.

Any idea what it might be?

I've moved the .htaccess file, I've given permission 777 and several other things but I'm still unsuccessful in attaching any file.
