### ISSUE TITLE
[9.2.2] No translate and HTML is wrong

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3701]
Hello!

No translate and I guess HTML is wrong

Tab General -> System:

![image](https://user-images.githubusercontent.com/17082164/37272281-3edfd10a-25e7-11e8-8ea0-e34cc91b2b8d.png)

![image](https://user-images.githubusercontent.com/17082164/37272323-5c1e6b3c-25e7-11e8-951d-5d3b753f32ff.png)

![image](https://user-images.githubusercontent.com/17082164/37272347-6b95702e-25e7-11e8-9645-f5319d9e97e5.png)

While updating:

![glpi - update needed](https://user-images.githubusercontent.com/17082164/37272401-907cba14-25e7-11e8-8368-375baa74d7df.png)

![image](https://user-images.githubusercontent.com/17082164/37272653-57651afe-25e8-11e8-88f0-6aa43928c2e7.png)

**Comment by trasher** [comment]
Translation was certainly not done yet when 9.2.2 has been released.
