### ISSUE TITLE
Requester followup

### ISSUE THREAD

**Issue by allanlopesprado** [glpi-project/glpi#3709]
The requester no need received your own email, Is there a way to fix this?
![image](https://user-images.githubusercontent.com/17826867/37339432-6e47b716-2699-11e8-9f8a-583979f8471e.png)

**Comment by edgardmessias** [comment]
Maybe this can souve your problem:

```diff
diff --git a/inc/notificationtargetcommonitilobject.class.php b/inc/notificationtargetcommonitilobject.class.php
index 3faa2b3cf..c5dfa414e 100644
--- a/inc/notificationtargetcommonitilobject.class.php
+++ b/inc/notificationtargetcommonitilobject.class.php
@@ -123,6 +123,12 @@ abstract class NotificationTargetCommonITILObject extends NotificationTarget {
             $author_lang  = $data["language"];
             $author_id    = $data['users_id'];

+            if (isset($this->options['followup_id'])
+                && isset($this->options['author_id'])
+                && $this->options['author_id'] == $author_id) {
+               continue;
+            }
+
             if (!empty($data['altemail'])
                 && ($data['altemail'] != $author_email)
                 && NotificationMailing::isUserAddressValid($data['altemail'])) {
diff --git a/inc/ticketfollowup.class.php b/inc/ticketfollowup.class.php
index fe7bf2553..e20bfa22d 100644
--- a/inc/ticketfollowup.class.php
+++ b/inc/ticketfollowup.class.php
@@ -248,6 +248,7 @@ class TicketFollowup  extends CommonDBTM {

       if ($donotif) {
          $options = ['followup_id' => $this->fields["id"],
+                          'author_id' => $this->fields['users_id'],
                            // Force is_private with data / not available
                           'is_private'  => $this->fields['is_private']];
          NotificationEvent::raiseEvent('delete_followup', $job, $options);
@@ -300,6 +301,7 @@ class TicketFollowup  extends CommonDBTM {
                //FIXME: _need_send_mail does not seems to be used

                $options = ['followup_id' => $this->fields["id"],
+                                'author_id'   => $this->fields['users_id'],
                                 'is_private'  => $this->fields['is_private']];

                NotificationEvent::raiseEvent("update_followup", $job, $options);
@@ -466,6 +468,7 @@ class TicketFollowup  extends CommonDBTM {

       if ($donotif) {
          $options = ['followup_id' => $this->fields["id"],
+                          'author_id'   => $this->fields['users_id'],
                           'is_private'  => $this->fields['is_private']];
          NotificationEvent::raiseEvent("add_followup", $this->input["_job"], $options);
       }
```

**Comment by allanlopesprado** [comment]
@edgardmessias

Applying a Fix

This way it works
![image](https://user-images.githubusercontent.com/17826867/37365940-b47c1990-26dd-11e8-93e5-ed877c1abcbc.png)

This way it does not work
![image](https://user-images.githubusercontent.com/17826867/37365945-be203c06-26dd-11e8-9263-0ed0bba2ac48.png)

However the first path, when the technician inserts a new follow-up, he receives a notification (same problem of the beginning, however with technician)

**Comment by edgardmessias** [comment]
@trasher, I will make a pull request.

**Comment by orthagh** [comment]
Please use existing features :)

In Preferences (click you username on top right of glpi)

![image](https://user-images.githubusercontent.com/418844/37392535-af6b1a6e-276e-11e8-80a7-0edc5a996dd5.png)

**Comment by edgardmessias** [comment]
Currently, there is an option to notify the follow-up author.

![glpi](https://user-images.githubusercontent.com/1530997/37398883-a48e218c-275e-11e8-9af5-b983f2f819df.jpg)

**Comment by orthagh** [comment]
i don't understand the issue so, what about removing the recipient ?

**Comment by edgardmessias** [comment]
Why send the notification to author of followup on new followup if I removed "Followup Author" from Recipients?

Currently, the author of followup receive notification, with or without  "Followup Author" in Recipients

**Comment by orthagh** [comment]
is the author of followup also a requester or watcher of the parent ticket ?

**Comment by edgardmessias** [comment]
Yes

**Comment by orthagh** [comment]
So, could you explain (resume from the start) the issue.
We have two ways (by gui setup) to avoid the sending of the notification to the requester:
- remove it from notification recipient
- setup preferences to avoid receiving notification from your own actions.

I don't see when a code modification is needed.
But perhaps i miss the issue

**Comment by edgardmessias** [comment]
My opnion:

Problem: I not want receive my "Followup" notifications, but want receive my changes.

If remove the "Followup Author" from recipients, I still receive "Followup" notifications

Requesters and Watchers need receive my "Followup"

Correct @allanlopesprado?

**Comment by allanlopesprado** [comment]
For me both as solutions work as expected.

But by changing the option (Notification for my changes), I do not know which other processes may fail to be notified.

**Comment by orthagh** [comment]
> But by changing the option (Notification for my changes), I do not know which other processes may fail to be notified.

It's simple, it occurs at the last step of the notification sending, if you are the user connected to glpi and a notification contains your email address, it's dropped from recipient list (your address).

Thereby, you don't receive notification yourself for your own actions.
Note the other recipients still receive the notification as usal.
It affect only you.

**Comment by allanlopesprado** [comment]
@orthagh In my opinion it does not need updating, because the native option already does the work that I need, just did not know the function

**Comment by openseasite** [comment]
This only applies to follow-ups done by the web interface, it's not respected when the follow-up comes from mail.
