### ISSUE TITLE
Gobal search criteria include deleted items while show deleted items is disabled

### ISSUE THREAD

**Issue by joopmartens** [glpi-project/glpi#372]
Running a query using a global search criteria with show deleted items disabled includes deleted items for the global items.

E.g. running a query on software with the global search criteria computer-name includes deleted computers. 

I would expect global search criteria to exclude deleted items if show deleted items has not been enabled for the "local'' query.

Running Glpi 0.90.1

**Comment by yllen** [comment]
I make a global search and deleted items are not showing.
Are you sure you make de global search?
Can you explain all of your actions?

**Comment by joopmartens** [comment]
See the screenshot below for an example query.
The computer named "Tan" is a deleted computer.
Because the show deleted items option is not enabled for this query the 
delete computer "tan" should not be included in the search results.



Thanks in advance for your support.

**Comment by yllen** [comment]
You are on a software, so the request doesn't show deleted software. But your request has a link with computer, so the request is done on all computers of your entity.

You would like to have a new criteria for computer 'is deleted'?

**Comment by joopmartens** [comment]
I would prefer if global search criteria would honor the current (local) search "Show deleted items" value.
This way the user still has the option to choose if the search results have to include deleted items or not.

If I run a search on a piece of software without the option to include deleted items and I add a global search criteria (link) to see on which computers it is installed I would expect it to NOT include deleted computers.

Running the same search query but instead with the show deleted items option enabled it should in my opinion include both deleted software and deleted computers.

A new criteria for computer 'is deleted' would also allow a user the create queries that are fulfilling this behavior but to me it would be more logical if the query would just honor the current (local) search "Show deleted items" value also for linked global search items.

**Comment by loicpascal** [comment]
I would also prefer the same. I think users would rather softwares linked to not deleted computers.
Also, the global includes the deleted computers but in the software itself the deleted computers are not included
