### ISSUE TITLE
Location not saved when opening ticket

### ISSUE THREAD

**Issue by filipeaguiar** [glpi-project/glpi#3720]
* Steps to reproduce (which actions have you made) :
Open a ticket on default interface, selecting a location from the dropdown menu.

* Expected result :
The ticket would be saved with location information.

* Actual result :
The ticket is saved, but the locations_id in database is allways 0. And there's no such location on database.

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

[code]   GLPI 9.2 (/glpi => /var/www/html/glpi)
--

Operating system: Linux hcpe-vp-glpi-prod 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 PHP 5.6.30-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, 	calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at 10.34.0.104 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 Server Software: (Debian) 	Server Version: 5.5.58-0+deb8u1 	Server SQL Mode:  	Parameters: root@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed APCu extension is not present /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK /var/www/html/glpi/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpCas version 1.3.5 in (/var/www/html/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.24 in (/var/www/html/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.13 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)

Server: '10.34.0.100', Port: '389', BaseDN: 'dc=ebserhnet,dc=ebserh,dc=gov,dc=br', Connection filter: 		'(&(objectClass=user)(objectCategory=person)) ', RootDN: 'EBSERHNET\glpi.hcufpe', Use TLS: none

Not active

Way of sending emails: PHP

 

fields               Name: Campos adicionais              Version: 1.7.0      State: Enabled 	mreporting           Name: Mais Relatórios                Version: 1.4.0      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.2      State: Enabled 	reports              Name: Relatórios                     Version: 1.11.0     State: Enabled

Host: 10.34.0.14Connection: OkUse the OCSNG software dictionary: No
[/code]

**Comment by trasher** [comment]
Please update to 9.2.2; should have been fixed.
