### ISSUE TITLE
HTTP_REFERRER not send by the client

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#3729]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.

------------
* Steps to reproduce (which actions have you made) :
If you would like to switch of entity (this example ID : 9) :
Try : http://GLPISERVER/glpi/front/helpdesk.public.php?active_entity=9
I use Google Chrome

* Expected result :
You should change of entity

* Actual result :
You do not change of entity because $_SERVER['HTTP_REFERRER'] is not defined by Google Chrome.

* URL of the page :
Try : http://GLPISERVER/glpi/front/helpdesk.public.php?active_entity=9

* Solution :
If I replace (line 63) :

Html::redirect(preg_replace("/(\?|&|".urlencode('?')."|".urlencode('&').")?(entities_id|active_entity).*/", "", $_SERVER['HTTP_REFERRER']));

By :

Html::redirect(preg_replace("/(\?|&|".urlencode('?')."|".urlencode('&').")?(entities_id|active_entity).*/", "", $_SERVER['PHP_SELF']));

It works perflectly.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.2.2
SLES 12
Apache + MariaDB

**Comment by edgardmessias** [comment]
Browser only send the "REFERRER" if user click a hyperlink

See https://en.wikipedia.org/wiki/HTTP_referer

**Comment by trasher** [comment]
We do not expect GLPI to change entity from a direct link; but clicking a link from the UI. Thas way, HTTP_REFERER is defined, and all goes well.
