### ISSUE TITLE
[API][HATEOAS] Identifying User link

### ISSUE THREAD

**Issue by MartialSeron** [glpi-project/glpi#3735]
When you request a ticket, the links have `rel` attributes with item types.

```js
 {
    ...
    "links": [
        {
            "rel": "Entity",
            "href": "http://glpi/apirest.php/Entity/5"
        },
        {
            "rel": "User",
            "href": "http://glpi/apirest.php/User/6"
        },
        {
            "rel": "User",
            "href": "http://glpi/apirest.php/User/87348"
        },
        {
            "rel": "RequestType",
            "href": "http://glpi/apirest.php/RequestType/3"
        },
   ...
}
```

But I think this is not relevant in specific cases like `User`. It is even confusing because there is a `User` link for each actor and we can't know if it is a recipient, an observer or whatever.

Since there is no standard for HATEOAS, I think this could be a good idea to either change `rel` attribute content or add a `type` attribute (eg : `"type" : "recipient"`).

**Comment by edgardmessias** [comment]
First user is from `users_id_lastupdater`, and second is from `users_id_recipient`.

Maybe, we can add a attribute `field`

Example:

```
{
    ...
    "links": [
        {
            "rel": "Entity",
            "field": "entities_id",
            "href": "http://glpi/apirest.php/Entity/5"
        },
        {
            "rel": "User",
            "field": "users_id_lastupdater",
            "href": "http://glpi/apirest.php/User/6"
        },
        {
            "rel": "User",
            "field": "users_id_recipient",
            "href": "http://glpi/apirest.php/User/87348"
        },
        {
            "rel": "RequestType",
            "field": "requesttypes_id",
            "href": "http://glpi/apirest.php/RequestType/3"
        },
   ...
}
```

**Comment by edgardmessias** [comment]
To view recipient, an observer or whatever, use `apirest.php/Ticket/<number>/Ticket_User`

**Comment by cedric-anne** [comment]
Hi,

`links` in API seems to use the [Web Linking](https://tools.ietf.org/html/rfc5988#section-5) format. Maybe I misunderstood the RFC, but `rel` should describe the relation, not the type. There is a `type` attribute for this.
So, at my opinion, links should be like this:
```json
    "links": [
        {
            "rel": "last_updater",
            "type": "User",
            "href": "http://glpi/apirest.php/User/6"
        },
        {
            "rel": "recipient",
            "type": "User",
            "href": "http://glpi/apirest.php/User/87348"
        }
```

Regards
