### ISSUE TITLE
Redirect in loop after few hours inactivity when clicking on home

### ISSUE THREAD

**Issue by loicpascal** [glpi-project/glpi#374]
After few hours of inactivity, when clicking home or another menu it loops endlessly passing by these different pages :

* glpi/front/central.php?redirect=/front/central.php
* glpi/front/central.php
* glpi/index.php?redirect=/front/central.php&error=3
* glpi/front/login.php?redirect=/front/central.php
* glpi/front/central.php?redirect=/front/central.php
* ...

We need to stop the script and clear cache before it works. We use ldap authentification.

**Comment by orthagh** [comment]
Sorry for delay of answer.

Did you have some authomatic authentifcation with your ldap (NTLM, winbind, cas, etc) ?
Wht's your glpi version ?

**Comment by loicpascal** [comment]
Thanks for your answer. Actually, it seems it was caused by our php.ini configuration... I reset the default php configuration, especially for sessions and it seems to work again.
Thank you

**Comment by orthagh** [comment]
Ok great
