### ISSUE TITLE
Add document in ticket (simplified interface)

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#3741]
http://forum.glpi-project.org/viewtopic.php?id=161075

**Comment by yllen** [comment]
Same problem in 9.1.x

Right is incorrect because helpdesk doesn't have right UPDATE in its profile

**Comment by trasher** [comment]
Change proposed in https://github.com/glpi-project/glpi/pull/3742 is not OK; that breaks unit tests on 9.2 and master.
