### ISSUE TITLE
Mail receiver error when message has single quotes 9.2.2

### ISSUE THREAD

**Issue by bigben386** [glpi-project/glpi#3743]
* Steps to reproduce (which actions have you made) : We have had a recurring issue of certain emails not being picked up by the mail receiver since updating to 9.2.x. Looking at the sql error log, it seems that the single quotes in the email are not being escaped properly by the sql insert.

Error stack:
 SQL: INSERT
                   INTO `glpi_tickets` (`content`,`name`,`urgency`,`requesttypes                                                            _id`,`entities_id`,`status`,`impact`,`priority`,`users_id_recipient`,`itilcatego                                                            ries_id`,`date`,`global_validation`,`slas_ttr_id`,`ttr_slalevels_id`,`time_to_re                                                            solve`,`sla_waiting_duration`,`type`,`date_creation`,`date_mod`) VALUES
  Error: You have an error in your SQL syntax; check the manual that corresponds                                                             to your MySQL server version for the right syntax to use near at line 2
  Backtrace :
  inc/commondbtm.class.php:504
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  inc/mailcollector.class.php:596                    CommonDBTM->add()
  inc/mailcollector.class.php:1659                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate                                                            ()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:65                                  CronTask::launch()

* Expected result : Expect these emails to be processed as new tickets

* Actual result : The emails end up in the not imported queue.

* URL of the page :

* Screenshot of the problem (if pertinent) : 

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Operating system: Linux ocs-ng 3.13.0-141-generic #190-Ubuntu SMP Fri Jan 19 12:53:50 UTC 2018 i686 PHP 5.6.33-3+ubuntu14.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apc, apcu, calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, 	json, ldap, libxml, mbstring, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, 	sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at helpdesk.coldjet.com Port 80) 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.5.59-0ubuntu0.14.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Check permissions to the directory: /var/www/glpi/files/_log | Web access to the files directory, should not be allowedAutomatic checks cannot be done; please review .htaccess file and the web server configuration.
-- | --

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/1264
