### ISSUE TITLE
GLPI go Blank screen or http 500 error 

### ISSUE THREAD

**Issue by Sophal-Cam** [glpi-project/glpi#3745]
Dear GLPI team,

While I upgrade GLPI version from 9.1.6 to 9.2.1 I have met the problem blank screen when I try to log in to this system. Now I have upgrade it to version 9.2.2, it still problem. I also have checked to the system setup > General menu, System tab it show : 
-Web access to the files directory, should not be allowed
Automatic checks cannot be done; please review .htaccess file and the web server configuration.
I am not sure that is the issue related or not. 

I need your help as soon as possible.
Thanks and regards,
Sophal

**Comment by trasher** [comment]
"Web access to the files directory, should not be allowed" is just a warning; this does not block anything.

Check your logs (GLPI and system) to find the error when a blank page appears.

**Comment by Sophal-Cam** [comment]
Could you tell me the specific location of those error-log?

**Comment by jonatangobbato** [comment]
I have the same Warning after update 9.2.1 to 9.2.2. 
How to solve then? i no have changed nothing in the httpd.conf from 9.2.1 to 9.2.2.

**Comment by Sophal-Cam** [comment]
Please help me I need your help

**Comment by trasher** [comment]
@jonatangobbato as already said: check the logs.
@Sophal-Cam logs are in `files/_log`...

**Comment by jonatangobbato** [comment]
@trasher , i have installed the glpi via remi repo, the files directory for me is "/var/lib/glpi" and the logs are in "/var/logs/glpi/" but wich file has the log for this warning? "event.log", "mail-error.log", "mail.log", "php-errors.log"?
I have only the warning, the blank screen does not appear for me, however, I would like to identify what is causing this warning, since in version 9.2.1 it did not appear.

**Comment by trasher** [comment]
@jonatangobbato current bug is about a blank screen.
The warning is displayed as of 9.2.2 because automatic checks cannot be done. Previously, nothing was displayed on failure. RPM configuration is correct on this point (logs files are out of webroot).

**Comment by jonatangobbato** [comment]
ok, then this is a bug of version 9.2.2? Which is the prevision for 9.2.3? I dont understand how git hub works for this updates. Thanks for your attention @trasher

**Comment by trasher** [comment]
**This is not a bug**. Your environment/setup/whatever does not permit to check automatically; whatever GLPI version is. Prior to 9.2.2; this was just failing silently.
We're working to make things more clear for a future release.

9.2 development is in 9.2/bugfixes branch.

Please keep this ticket focused on original issue.

**Comment by Sophal-Cam** [comment]
This issue I can fix just clone old system to re-upgrade it. Thanks for your support.
