### ISSUE TITLE
Auto-merge user glpi user database and ldap problem

### ISSUE THREAD

**Issue by fabibus** [glpi-project/glpi#3747]
Hello,

I have a problem since upgrade 90.5 to 9.2.1.
I have some user in glpi internal database. I use ldap authentication.
When a ldap user have the same id like another one in glpi internal database, GLPI auto merge both in one...
It'a a problem because the right isn't reset and the local user can't connect to glpi.

Is there a way to disable this "auto-merge" local database with ldap ?
In GLPI I can change authentication method but GLPI don't reset the ldap authentication field and the  Emails field from ldap connection... and I can't delete it ...

Is there a way or a field to disable auto-merge ?
More info in GLPI forum [http://forum.glpi-project.org/viewtopic.php?id=160675](http://forum.glpi-project.org/viewtopic.php?id=160675)

Thank you 

I use glpi 9.2.1 with fusioninventory, pdf, reports plugins.

**Comment by trasher** [comment]
As far as I understand; this behavior changes in 9.3, see https://github.com/glpi-project/glpi/pull/3585

**Comment by trasher** [comment]
Since I do not get feedback, I guess #3585 dos fix the issue
