### ISSUE TITLE
Not readable font

### ISSUE THREAD

**Issue by bambresso** [glpi-project/glpi#3748]
On home page Ticket tasks not readable 

![01](https://user-images.githubusercontent.com/13583138/37819432-7d0b044a-2e8e-11e8-9665-bc8fef247891.png)
![02](https://user-images.githubusercontent.com/13583138/37819434-7e842ed2-2e8e-11e8-8202-ef7d625b8497.png)

**Comment by trasher** [comment]
In which lang does problem appears?

**Comment by bambresso** [comment]
all, except English symbols

**Comment by trasher** [comment]
I can't reproduce:
![screenshot-2018-3-27 glpi - standardni rozhrani](https://user-images.githubusercontent.com/224733/37953266-b356e85e-31a2-11e8-9c45-975a8c1c62d6.png)

**Comment by orthagh** [comment]
Hello @bambresso 
it seems you are using he_IL but nevermind you confirm all language except EN triggers this issue ?
Also could you provide some additional informations: Operating system, browsers (did you test on another one ?), glpi version (this could be very important)

**Comment by trasher** [comment]
ping?

**Comment by trasher** [comment]
No feedback, closing
