### ISSUE TITLE
Display restore massive action in the search page, when user have not purge rights

### ISSUE THREAD

**Issue by Alejka** [glpi-project/glpi#3758]
Hello! Glpi 9.2.1 (in last versions the same problem). In the MassiveAction class in we have next code:

```
static function getAllMassiveActions($item, $is_deleted = 0, CommonDBTM $checkitem = null) {
   ......
   $candelete = $itemtype::canDelete();
   $canpurge  = $itemtype::canPurge();
   ......
   if ($is_deleted) {
      if ($canpurge) {
         if (in_array($itemtype, Item_Devices::getConcernedItems())) {
            $actions[$self_pref.'purge_item_but_devices']
                                             = _x('button', 'Delete permanently but keep devices');
            $actions[$self_pref.'purge']  = _x('button', 'Delete permanently and remove devices');
         } else {
            $actions[$self_pref.'purge']  = _x('button', 'Delete permanently');
         }
         $actions[$self_pref.'restore'] = _x('button', 'Restore');
      }
   }
   ......
}
```

So code `$actions[$self_pref.'restore'] = _x('button', 'Restore');` will be executed (and "restore" massive action will be shown in the search page) only when i have `$itemtype::canPurge();` rights. So if I haven't "purge" rights - I **can** restore item in item update form, but **cannot** restore item from massive actions in the search page.

* Your GLPI setup:
GLPI 9.2.1 (the same problem in other versions).

**Comment by trasher** [comment]
Duplicates #3165
