### ISSUE TITLE
No email notification when closing a ticket from a task

### ISSUE THREAD

**Issue by sylvainclerc** [glpi-project/glpi#3759]
Hello,

* Glpi version : 9.1.6 actually, bug reproduced on 9.2.2 in test environnement

* Steps to reproduce (which actions have you made) :
Close a ticket from task interface
Email notification is active when a ticket is closed

* Expected result : Ticket is closed and an email notification is sent

* Actual result : ticket is closed but email notification isn't sent

* Comments : if I close a ticket directly from the ticket , the email notification on closing ticket is sent.
When the notification isn't sent, nothing appears on queuednotification in automatic actions.

* Screenshot of the problem (if pertinent) : 
![screenshot686](https://user-images.githubusercontent.com/25950425/37908001-fad738ba-3106-11e8-87a2-de9e889f1580.jpg)

Thank you,
Sylvain.

**Comment by trasher** [comment]
Duplicates #2358
