### ISSUE TITLE
Warning "Web access to the files" with HTTPS

### ISSUE THREAD

**Issue by jonatangobbato** [glpi-project/glpi#3760]
I have the GLPI installed via RPM (Remi Repo) in the version 9.2.2.
After update from 9.2.1 in the menu Settings > General> System i got the warning:

Web access to the files directory, should not be allowed
Automatic checks cannot be done; please review .htaccess file and the web server configuration.

![image](https://user-images.githubusercontent.com/29125329/37910027-e0f13424-30e2-11e8-8494-678ec41c9b94.png)

i'ts only occur if i access the glpi with HTTPS, when i use HTTP the warning does not show.

Mi GLPI.conf archive:

<VirtualHost *:443>

  DocumentRoot /usr/share/glpi
  ServerName suporte.biamar.com.br
  SSLEngine On
  SSLCertificateFile /etc/ssl/certs/biamar.com.br.crt
  SSLCertificateKeyFile /etc/ssl/private/biamar.com.br.key

#Alias /glpi /usr/share/glpi

<Directory /usr/share/glpi>
    Options None
    AllowOverride Limit Options FileInfo

    <IfModule mod_authz_core.c>
        Require all granted
    </IfModule>
    <IfModule !mod_authz_core.c>
        Order deny,allow
        Allow from all
    </IfModule>
</Directory>

<Directory /usr/share/glpi/install>

    # Install is only allowed via local access (from the GLPI server).
    # Add your IP address if you need it for remote installation,
    # but remember to remove it after installation for security.

    <IfModule mod_authz_core.c>
        # Apache 2.4
        Require local
        # Require ip ##.##.##.##
    </IfModule>
    <IfModule !mod_authz_core.c>
        # Apache 2.2
        Order Deny,Allow
        Deny from All
        Allow from 127.0.0.1
        Allow from ::1
    </IfModule>

    ErrorDocument 403 "<p><b>Restricted area.</b><br />Only local access allowed.<br />Check your configuration or contact your administrator.</p>"

    <IfModule mod_php5.c>
        # migration could be very long
        php_value max_execution_time 0
        php_value memory_limit -1
    </IfModule>
    <IfModule mod_php7.c>
        # migration could be very long
        php_value max_execution_time 0
        php_value memory_limit -1
    </IfModule>
</Directory>

<Directory /usr/share/glpi/config>
    Options -Indexes
    Order Allow,Deny
    Deny from all
</Directory>

<Directory /usr/share/glpi/locales>
    Order Allow,Deny
    Deny from all
</Directory>

<Directory /usr/share/glpi/install/mysql>
    Order Allow,Deny
    Deny from all
</Directory>

<Directory /usr/share/glpi/scripts>
    Order Allow,Deny
    Deny from all
</Directory>

<Directory /var/lib/glpi/files>
     Options -Indexes
</Directory>

</VirtualHost>

How to Solve This?

**Comment by trasher** [comment]
Not a bug.
