### ISSUE TITLE
User in a group assigned as "requester" and "assigned to" approves the solution

### ISSUE THREAD

**Issue by salazar8D** [glpi-project/glpi#3768]
Hi everyone,

Is it right if an user is in group assigned as "requester" and "assigned to" post a solution and the same user approves it ? I don't know if it is a bug or is a lack of an option that allows or not a group solve/approve a solution. Maybe an option in here:

![image](https://user-images.githubusercontent.com/30785943/37969867-4b684f8e-31a8-11e8-817e-185b436486c6.png)

I have edit this blocks in inc\ticket.class.php and the "problem" was solved, but I don't know if it will crash the application in any instance.

![image](https://user-images.githubusercontent.com/30785943/37969052-35ae35f2-31a6-11e8-9ed1-5bad5dec5b00.png)

I've commented the groups line.

![image](https://user-images.githubusercontent.com/30785943/37973497-05a0ffec-31b1-11e8-9043-7e4e5476a7ba.png)

GLPI version 9.2.2

**Comment by salazar8D** [comment]
![image](https://user-images.githubusercontent.com/30785943/37973464-f11a6176-31b0-11e8-90c0-310bd0a21199.png)

**Comment by trasher** [comment]
This seems to be the expected behavior; I don't think we're going to change that.

**Comment by salazar8D** [comment]
Maybe then is not a problem for everyone, but is kind of strange the tech user post a solution for other user and himself approves it just because they are both in the same group. But I get it... Thanks for your time @trasher
