### ISSUE TITLE
User can do modification after ticket is closed

### ISSUE THREAD

**Issue by salazar8D** [glpi-project/glpi#3769]
Hello everyone,

Here it is a Bug or a problem. I don't know if there's already a flag in profiles for this, but If the ticket is already closed, the user can remove/add a tech or group in the "Assigned to" area:

![image](https://user-images.githubusercontent.com/30785943/37976516-0c2dd48c-31b8-11e8-83c4-d96f5a32e249.png)

Heres the code:

![image](https://user-images.githubusercontent.com/30785943/37976604-3ab1bca6-31b8-11e8-9190-e5090d44dd31.png)

I've done this modification in the inc\ticket.class.php and this solved the "problem":

![image](https://user-images.githubusercontent.com/30785943/37976676-65bb461a-31b8-11e8-903c-3267826219bb.png)

The result:

![image](https://user-images.githubusercontent.com/30785943/37976783-a90c1cd2-31b8-11e8-9878-5cd2e8f74523.png)

From where I see it, looks like a logical issue.... I don't know. Maybe a enhancement for this ?

GLPI ver. 9.2.2

**Comment by trasher** [comment]
Could you please provide a patch with your changes rather than an image? This is quite impossible to read

**Comment by salazar8D** [comment]
Sure... Here it is.

   function canAssign() {

      if (isset($this->fields['is_deleted']) && ($this->fields['is_deleted'] == 1) || in_array($this->fields['status'], $this->getClosedStatusArray())) {
         return false;
      }
      return Session::haveRight(self::$rightname, self::ASSIGN);
   }


   function canAssignToMe() {

      if (isset($this->fields['is_deleted']) && ($this->fields['is_deleted'] == 1) || in_array($this->fields['status'], $this->getClosedStatusArray())) {
         return false;
      }
      return (Session::haveRight(self::$rightname, self::STEAL)
              || (Session::haveRight(self::$rightname, self::OWN)
                  && ($this->countUsers(CommonITILActor::ASSIGN) == 0)));
   }
