### ISSUE TITLE
Internal Time to own and Internal Time to resolve are not hidden

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#3771]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.

------------
* Steps to reproduce (which actions have you made) :
Create a template which hide Internal Time to own and Internal Time to resolve
Apply this template to a ticket category

* Expected result :
 Internal Time to own and Internal Time to resolve should be hidden

* Actual result :
They are not hidden

* URL of the page :

* Screenshot of the problem (if pertinent) 👍:
![ola_hidden](https://user-images.githubusercontent.com/2960490/38024365-d908aa3a-3295-11e8-829e-92101eb28afd.PNG)
![hidden_field](https://user-images.githubusercontent.com/2960490/38024369-de1fb900-3295-11e8-98ba-5626cbfe5323.PNG)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.2

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/3595
