### ISSUE TITLE
[9.2.2] The problem with translation of tiny_mce is back again

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#3788]
Hello,
This problem is back again. Old issue #1458
I've removed ru_RU.js of tiny_mce.

![image](https://user-images.githubusercontent.com/17082164/38237442-e9035d56-372f-11e8-949b-62fb70e6f57e.png)

**Comment by trasher** [comment]
Could you please report the issue against TinyMCE project? It must be fixed on their side so we do not have to care bout that in the future.
