### ISSUE TITLE
API/Feature for marking outdated plugins

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#381]
Would be nice if glpi and plugins gets an feature, which marks outdated plugins in the plugin overview. Either with a manual check version button or automatically in background.

Sure, a button for updating these plugins would be much more comfortable, but not such urgent that seeing an outdated plugin.

**Comment by orthagh** [comment]
No work started actually for this, but it's definitely a feature we wants.
I close for the moment, and suggest you to use the [suggest](suggest.glpi-project.org) site to reference this feature.
