### ISSUE TITLE
Glpi 9.2.2 - Error import any mail from collector with an apostrophe in the mail body

### ISSUE THREAD

**Issue by apeyrou** [glpi-project/glpi#3819]
Glpi 9.2.2 debian 9.4

it's not ok with an apostrophe in the mail body 
it ok if I delete the apostrophe.

  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_tickets` (`content`,`name`,`urgency`,`requesttypes_id`,`entities_id`,`status`,`impact`,`priority`,`users_id_recipient`,`itilcategories_id`,`date`,`global_validation`,`type`,`date_creation`,`date_mod`) VALUES ('9999999\n\nCordialement,\n\nArnauld PEYROU\nResponsable Technique et Support\n\nDirection des SystÃ¨mes d'Information.\nInrap - 121 rue d'AlÃ©sia - 75014 Paris\nTÃ©l : 01 40 08 80 48.\nwww.inrap.fr\nAbonnez-vous Ã  la lettre d'information de l'Inrap : http://www.inrap.fr/newsletter.php','test9','3','2','0','1','3','3','8','0','2018-04-06 11:25:01','1','1','2018-04-06 11:25:01','2018-04-06 11:25:01')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Information.\nInrap - 121 rue d'AlÃ©sia - 75014 Paris\nTÃ©l : 01 40 08 80 48.\nw' at line 2
  Backtrace :
  inc/commondbtm.class.php:504                       
  inc/commondbtm.class.php:928                       CommonDBTM->addToDB()
  inc/mailcollector.class.php:596                    CommonDBTM->add()
  inc/mailcollector.class.php:1659                   MailCollector->collect()
  inc/crontask.class.php:832                         MailCollector::cronMailgate()
  front/cron.php:81                                  CronTask::launch()

**Comment by trasher** [comment]
duplicates https://github.com/glpi-project/glpi/issues/1264
