### ISSUE TITLE
bug in notificationtargetcertificate.class.php

### ISSUE THREAD

**Issue by vrocheUP** [glpi-project/glpi#3822]
Hello,

There is a bug in notificationtargetcertificate.class.php line #77, certificate URL is wrong : 
`         '##certificate.url'              => $this->formatURL($options['additionnaloption']['usertype'],
                                                                 "Certificate".$id),`

I corrected to this : 
`           '##certificate.url##'              => $this->formatURL($options['additionnaloption']['usertype'],
                                                                 "Certificate_".$id),`

**Comment by trasher** [comment]
I've opened a PR with the fix you propose, thank you.

**Comment by vrocheUP** [comment]
I think you have to add an underscore after Certificate (line 78) : 
"Certificate_".$id),

I tested without : not working !

**Comment by trasher** [comment]
Fixed, thanks
