### ISSUE TITLE
GLPI-Autentication-Denied_Access

### ISSUE THREAD

**Issue by mariarosa-reds** [glpi-project/glpi#3826]
I just tried to log in with super-admin called 'glpi' with it's password('glpi') but it always sent me to the glpi's access denied page

 It should have logged me in 
 it doesn't logged me in even after changing the password of the super-admin to another md5 password quite a few times 

I was using glpi 9.1.5 with ubuntu 16.05, apache2 and php5.6.

**Comment by trasher** [comment]
GLPI 9.1.x is no longer supported. Sounds like you have a session issue or something similar, check your server configuration
