### ISSUE TITLE
Doc: Mandatory extensions missing xml

### ISSUE THREAD

**Issue by colttt** [glpi-project/glpi#3838]
* Steps to reproduce (which actions have you made) :
install all mandatory extensions, also apache and mysql. If you start the Webinterface to finish the installation you will get an error that are 'simplexml' and 'xml' extensions are missing

* Expected result :
that all extensions are installed like in the documentation 

* Actual result :
missing prerequisites in the Documentation

**Comment by trasher** [comment]
Which documentation are you talking about?

**Comment by colttt** [comment]
I mean http://glpi-install.readthedocs.io/en/latest/prerequisites.html , but I saw that you already fixed it.
