### ISSUE TITLE
Printable version problem

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#384]
Hi,

Here the view of a computer item when printed.
[GLPI - Ordinateurs.pdf](https://github.com/glpi-project/glpi/files/99137/GLPI.-.Ordinateurs.pdf)

The view is altered following the new CSS style (menu, inputs and buttons).

Same issue with others items (Displays, Softwares, Printers etc...)

Thanks

**Comment by barbuslex** [comment]
Thanks

Maybe change the color of the link too ?

From : 
> #659900

To : 
> #3A5693

???

**Comment by orthagh** [comment]
You're right, done

**Comment by barbuslex** [comment]
Thanks so much ;)
