### ISSUE TITLE
[9.2.3] Regression : LDAP sync doesn't retrieve group membership

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#3841]
Hello,

After an upgrade from 9.2.2 to 9.2.3 (yesterday nightly build), GLPI's ldap sync doesn't retrieve group membership for users. Consequently, users loose authorizations.

Steps to reproduce : 
1. Show group members of a LDAP group (for example : Bar group with nqbtest2 user)
2. Log in to GLPI as nqbtest2 user
3. Show group members of Bar group. On Historical tab, you will see an event like this : 
![group_member](https://user-images.githubusercontent.com/10830260/38558054-49b367c8-3ccf-11e8-8378-f27d0e06a63b.PNG)

I checked : 
* Bar group members on my LDAP server : nqbtest2 is a member;
* LDAP directory link tab on Bar Group : all is right.

No logs and no messages in debug.

**Comment by salazar8D** [comment]
@trasher I see it know... I only focused in the authorizations part.

> Also, there are already several existing issues on LDAP/groups issues; are you sure this one is not a duplicate?

I've checked my problem in the issues tab, and I haven't find something similar.
Sorry for the comment.

**Comment by trasher** [comment]
The "duplicate" part was about current ticket description, not your comment.

**Comment by nqb** [comment]
@trasher,

I have two GLPI instances : 
* GLPI 9.2.2 : issue is not present
* GLPI 9.2.3 : copy of GLPI 9.2.2 instance with a nightly build install (9.2bf).

Config between two instances is strictly the same. On GLPI 9.2.3, I notice that issue directly because I lost my authorizations and get Self-Service profile.

IMHO : regression introduced by 9.2.3.

Do you reproduce issue ?

**Comment by trasher** [comment]
I will take hours to install, populate, etc a LDAP; so no, I did not reproduce.
All I can say is this part did not since 9.2.2.

**Comment by nqb** [comment]
> I will take hours to install, populate, etc a LDAP; so no, I did not reproduce.

You can't use tests/LDAP ?

> All I can say is this part did not since 9.2.2.

Not agree, @orthagh and you make some changes on LDAP Authentification in 5106854.

**Comment by orthagh** [comment]
> Not agree, @orthagh and you make some changes on LDAP Authentification in 5106854.

This commit is part of 9.2.3 and it's not released yet

**Comment by orthagh** [comment]
just checked with our openldap and current 9.2/bugfixes
removed my dynamic group from my user form, force synchronisation and did the same process with logout login:
![image](https://user-images.githubusercontent.com/418844/38567189-df00ecf4-3ce5-11e8-8f50-1037ff10ce3b.png)

My ldap config is like this: 
![image](https://user-images.githubusercontent.com/418844/38567258-ff1319d6-3ce5-11e8-8f2d-b18e6605068e.png)

**Comment by trasher** [comment]
> You can't use tests/LDAP ?
No.

> Not agree, @orthagh and you make some changes on LDAP Authentification in 5106854.

This is not related to groups; this change concerns connexion.

**Comment by nqb** [comment]
@trasher, you are right. However, you make some changes related to groups in 79f64e13 (to fix #3780).

**Comment by trasher** [comment]
I still do not think this is related.

However, you can try to revert those commits and see if one of them was really causing your issue. Trying to guess is not really productive...

**Comment by nqb** [comment]
> Trying to guess is not really productive...

Agree. With user.class.php at 3120b4a (last commit before 79f64e1), issue is not present.
Conclusion : regression introduced by 79f64e1.

@orthagh, if you want to reproduce, try my LDAP group config :
![ad_config](https://user-images.githubusercontent.com/10830260/38615300-73763880-3d90-11e8-949e-1d7922997f17.PNG)
Comparing to @orthagh, I get belonging to groups in users.

I don't reproduce issue with following LDAP group configs at 79f64e1 :
- Search type = In groups
- Search type = In users and groups

Tell me if I can help.

**Comment by nqb** [comment]
It works for me.
