### ISSUE TITLE
Tag costs for notification via email is not showing the cost.

### ISSUE THREAD

**Issue by rincat1** [glpi-project/glpi#3844]
Good afternoon, I put the following tags in the notification part via email:
```
## FOREACHcosts ##

## lang.ticket.costs ##

## lang.ticket.numberofcosts ##

## ticket.numberofcosts ##

## ENDFOREACHcosts ##
```

But it is not presenting the value that I put in the costs, the only tag that works is the number of costs that the call has. Here's how the email comes to me:

![image](https://user-images.githubusercontent.com/37090938/38569642-2e56cb6c-3cc2-11e8-902e-8f20b3e05b99.png)
I wonder if it's a bug or if I'm actually misusing the tags .. Thank you very much to everyone!

**Comment by orthagh** [comment]
Hello @rincat1 .

Your example seems good for me.
`lang.*` prefixes are labels 

If you want to have the total cost fort the ticket, maybe you should use `##ticket.totalcost##`
or in the `FOREACH` loop the following tags:
* `##cost.name##`
* `##cost.totalcost##`
* `##cost.budget##`
* `##cost.time##`
* etc

**Comment by rincat1** [comment]
That was it, I did not find this tag because I did a search in the list of tags (CTRL + F) and was looking for "costs" and not "cost", lack of attention of mine, thank you and excuse my ignorance.
