### ISSUE TITLE
[9.1.3] API - Delete SoftwareVersion on PC

### ISSUE THREAD

**Issue by DGermany** [glpi-project/glpi#3857]
Hey, 

to me, it seems like an bug, or I just don't understand the api at this point. 

I just want to delete an Software on an PC. So far, I understand that I've to delete the softwareversion on an pc. BUT, if I drop the following statement, i just get an empty array back! 

Can anybody help? !

https://glpi-q.int.shsservices.de/apirest.php/computer/61335/Computer_SoftwareVersion/

![glpi_delete](https://user-images.githubusercontent.com/30858247/38678388-6723a44e-3e50-11e8-84ed-4c7de1e696ab.JPG)

![glpi_delete2](https://user-images.githubusercontent.com/30858247/38678455-95cacdea-3e50-11e8-8d3f-ad762bd574c8.JPG)

**Comment by trasher** [comment]
Please use forums to get support. Also note that 9.1.3 is old and n longer maintained.
