### ISSUE TITLE
Error when inserting PDUs to Rack - GLPI 9.3 - Beta

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#3859]
*** Steps to reproduce (which actions have you made) :**

1. Create a Rack
2. Create a PDU unit
3. Try to insert a PDU to a Rack (it doesn't matter the position at side or inside)

*** Expected result :**

1. Probably, the options to choose the correct PDU unit

*** Actual result :**

- Permissions error (Image below)

*** URL of the page :**
http://server/front/rack.form.php?id=1

*** Screenshot of the problem (if pertinent) :**
![image](https://user-images.githubusercontent.com/13874922/38688035-79df9928-3e4e-11e8-91ba-9eba8c3115ae.png)

*** Your GLPI setup (you can find it in Setup > General menu, System tab) :**

Information about system installation & configuration
--
[code]   GLPI 9.3-dev (/glpi93 => /var/www/html/glpi93) Installation mode: TARBALL

Operating system: Linux debian 4.9.0-6-686-pae #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) i686 PHP 7.0.27-0+deb9u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, sockets, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at 192.168.0.3 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 Server Software: Debian 9.1 	Server Version: 10.1.26-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: glpi@localhost/glpibeta 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed /var/www/html/glpi93/config : OK /var/www/html/glpi93/files : OK /var/www/html/glpi93/files/_dumps : OK /var/www/html/glpi93/files/_sessions : OK /var/www/html/glpi93/files/_cron : OK /var/www/html/glpi93/files/_graphs : OK /var/www/html/glpi93/files/_lock : OK /var/www/html/glpi93/files/_plugins : OK /var/www/html/glpi93/files/_tmp : OK /var/www/html/glpi93/files/_cache : OK /var/www/html/glpi93/files/_rss : OK /var/www/html/glpi93/files/_uploads : OK /var/www/html/glpi93/files/_pictures : OK /var/www/html/glpi93/files/_log : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi93/lib/htmlawed) phpCas version 1.3.3 in (/usr/share/php) SimplePie version 1.5.1 in (/var/www/html/glpi93/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/html/glpi93/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi93/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi93/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/glpi93/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi93/vendor/sabre/vobject/lib)

Not active

Way of sending emails: PHP

 

 
[/code]

**Comment by trasher** [comment]
I cannot reproduce the issue.

Is your install an update? If so, review profile permissions would be a good start point.
Are you using a multi-entities setup? If so, are both the items created in the same entity? What about recursivity?

**Comment by tsmr** [comment]
Due to CSRF (with GLPI_USE_CSRF_CHECK to 0) it's ok

**Comment by arthurrschaefer** [comment]
Thanks and sorry for no responses.
