### ISSUE TITLE
[9.3] Multiples bugs founded

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#3861]
1. When i want to add new objets : into browser address : 

```front/pdu.form.php?id=-1&amp;withtemplate=2```

-> &amp; is not encoded

2. On location dropdown search, the child are not displayed : 
![image](https://user-images.githubusercontent.com/13178158/38723428-51218b46-3f01-11e8-8ed4-0ada276cae38.png)

3. When addding elements to enclosure

![image](https://user-images.githubusercontent.com/13178158/38723457-7500c7d4-3f01-11e8-8462-8e0489f0af83.png)

4.  When i want to add PDU to racks

![image](https://user-images.githubusercontent.com/13178158/38723515-9e4394aa-3f01-11e8-9906-0c315df08392.png)

5. I cannot navigate into new objects forms (navigationheader) : 
![image](https://user-images.githubusercontent.com/13178158/38723651-1206ca4c-3f02-11e8-80c1-7fd2e41e9d9b.png)

**Comment by trasher** [comment]
For 4, see https://github.com/glpi-project/glpi/issues/3859

**Comment by trasher** [comment]
2, 3 and 5 has been fixed; see https://github.com/glpi-project/glpi/pull/3864

1 does not sems to be an issue really.
For 4, see dedicated ticket
