### ISSUE TITLE
GLPI X Office 365

### ISSUE THREAD

**Issue by daniloramos** [glpi-project/glpi#3865]
Hello guys

I am using version 9.2.1, but since implementation (2 years ago) I have problems with email tracking, the queue gets to have more than 1000 emails, I can not do what the system sends 20 or 30 emails at once and, always continues running and does not complete the cycle (send / stop).

Today the settings are to send 3 emails every 5 minutes, but even then it stays the entire time running and will not run in the next 5 minutes.

I do not know what to do for the system to correctly send the emails, I would like to help you for an effective solution.

**Comment by daniloramos** [comment]
If I try to manually send 20 emails system completely freezes.

**Comment by trasher** [comment]
Check if there is anything in the logs.

Most of the time, email delivery issues are related to the mail server, or to network issues. Please check.
