### ISSUE TITLE
[9.2.1 to 9.3] Cannot paste images in tinyMCE on Internet Explorer

### ISSUE THREAD

**Issue by alexismrni** [glpi-project/glpi#3866]
Problem only on IExplorer 11
Works on Firefox or Chrome

* Steps to reproduce (which actions have you made) :
Make a screenshot (png or jpg) and paste it in the ticket (tinyMCE)

* Expected result :
Image uploaded and included in the text of ticket

* Actual result :
Image refused and an error about the format of file.
"Type de fichier non autorisé"

* URL of the page :
http://GLPI/front/ticket.form.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.3-dev ( => /var/www/html)
Installation mode: TARBALL

Operating system: Linux localhost.localdomain 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64
PHP 5.6.33 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring,
	mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.33 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Server Software: MariaDB Server
	Server Version: 5.5.56-MariaDB
	Server SQL Mode: 
	Parameters: glpiuser@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP

Thank you ;) !

**Comment by trasher** [comment]
Since I do not have any IE, I cannot help much...
Maybe is there a javascript error message somewhere in developer tools (or assimilate)?

**Comment by alexismrni** [comment]
Hello Trasher, 
Nothing on developer tools when i paste with "CTRL + V"

I discovered another bug when i try to paste with "right click -> paste"

> [** UPLOADING FILE == undefined **]

This message appairs in tiny MCE content and have this error on developer tools:

> SCRIPT5007: Impossible d’obtenir la propriété  « replace » d’une référence null ou non définie
> ticket.form.php (179,10)


I also tried with the "Compatibility mode" of IE. 
Actually i'm on 9.3.

Thank you

**Comment by roshanroche** [comment]
Hi,
on GLPI 9.3 i get this in developer tools console

![image](https://user-images.githubusercontent.com/22425503/38796015-319ca654-416b-11e8-8c73-c83204313eed.png)

**Comment by alexismrni** [comment]
Hello @roshanroche,

I have same only with right clic and paste.

Thank you

**Comment by AnaelMobilia** [comment]
$params on glpiuploadhandler.class.php (line 112)
```
array(3) {
 ["name"]=> string(8) "filename"
 ["showfilesize"]=> bool(false)
 ["print_response"]=> bool(true) }

 {"filename":[{"name":"5ae78a14a39ab7.24417122blob","size":63336,"type":"image\/png","url":"http:\/\/127.0.0.1\/glpi\/ajax\/files\/5ae78a14a39ab7.24417122blob","deleteUrl":"http:\/\/127.0.0.1\/glpi\/ajax\/?filenam=5ae78a14a39ab7.24417122blob","deleteType":"DELETE","error":"Filetype not allowed","id":"docfilename2093880503"}]}
```

on IE11 / W10 17.09 x64

**Comment by alexismrni** [comment]
Hello @AnaelMobilia Thank you for these informations. I hope your logs can help to find a solution. 

Have a good day

**Comment by AnaelMobilia** [comment]
For the Right click -> paste, stack trace :
```
stack	"TypeError: Impossible d’obtenir la propriété  « replace » d’une référence null ou non définie
at window.alert (http://127.0.0.1/glpi/front/ticket.form.php:154:10)
at error (http://127.0.0.1/glpi/js/fileupload.js?v=9.4-dev:67:10)
at c (http://127.0.0.1/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.4-dev:4:26028)
at p.fireWith (http://127.0.0.1/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.4-dev:4:26776)
at k (http://127.0.0.1/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.4-dev:6:14281)
at ajax (http://127.0.0.1/glpi/lib/jquery/js/jquery-1.10.2.min.js?v=9.4-dev:6:13759)
at uploadFile (http://127.0.0.1/glpi/js/fileupload.js?v=9.4-dev:40:4)
at insertImageInTinyMCE (http://127.0.0.1/glpi/js/fileupload.js?v=9.4-dev:324:4)
at Anonymous function (http://127.0.0.1/glpi/js/fileupload.js?v=9.4-dev:376:16)
at c.fire (http://127.0.0.1/glpi/lib/tiny_mce/tinymce.min.js?v=9.4-dev:2:182873)"
```
