### ISSUE TITLE
Typo on transifex

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#3875]
Hello,

On the dev channel (and 9.3 / 9.2), we have on config.php #278 a typo 
`echo "<p class='red'><strong>".
                     __('You are trying to update to a development version from a development version. This is not suppoorted.')."</strong></p>";`

There is a typo on supp**o**orted .
I can change the file, but not files on transifex side...

If anybody of the glpi's team could help... :-)

Regards,
Anael

**Comment by trasher** [comment]
The string has to be fixed in source code, transifex strings are updated separately

**Comment by AnaelMobilia** [comment]
@trasher PR is made :)

Regards,
Anael
