### ISSUE TITLE
Autcomplete sugestion

### ISSUE THREAD

**Issue by Simplesmente** [glpi-project/glpi#3878]
Hello everyone. I would like know if there any plugin or configuration for the follow behavior:
- When a user open a ticket, at same time in field "title" (where stay the title about the problem) the glpi do requests to base knowledge showing some sugestions that already exists on base. I think that it avoid the user open a ticket once that problem already related.

I thanks

**Comment by trasher** [comment]
Please [open a suggestion](http://suggest.glpi-project.org) for that ;)
