### ISSUE TITLE
SLA is not displayed when you create the ticket. [9.2.2]

### ISSUE THREAD

**Issue by yustas84** [glpi-project/glpi#3879]
I described the problem on your forum and attached screenshots:
http://forum.glpi-project.org/viewtopic.php?pid=344862#p344862

**Comment by trasher** [comment]
Please test with latest 9.2/bugfixes

**Comment by yustas84** [comment]
Tested on 9.2.2. same problem

**Comment by trasher** [comment]
No ton 9.2.2, on the 9.2/bugfixes current branch.

**Comment by yustas84** [comment]
sorry, don't understand. Where I can download 9.2/bugfixes? That I should install?

**Comment by yustas84** [comment]
Is it? https://forge.glpi-project.org/attachments/download/2234/glpi-reports-1.11.2.tar.gz

**Comment by trasher** [comment]
Take latest 9.2/bugfixes nightly build at: https://forge.glpi-project.org/tarballs/

**Comment by trasher** [comment]
No feedback, closing

**Comment by yustas84** [comment]
updated to 9.2.3 bugfix. The problem is not fixed.
Unlike SLA in the section OLA type and value of the maximal time of the solution are established without problems. Comparative analysis of tables glpi_slas and glpi_olas database showed that the table glpi_class otsutstvuyut field type, number_time, definition_time and end_of_working_day. This is probably a bug in one of the previous updates. After adding the missing fields to the glpi_slas table structure, the problem is solved!
