### ISSUE TITLE
[9.3 beta] automatic action purgelog error

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#3882]
I cant launch purge log automatic action

* Steps to reproduce (which actions have you made) :
setup>automatic actions>[purgelogs]>execute

* Expected result :
empty the logs

* Actual result :

Fatal error: Uncaught Error: Class 'PluginPurgelogsConfig' not found in /var/www/html/glpi93/inc/purgelogs.class.php:364 Stack trace: #0 /var/www/html/glpi93/inc/purgelogs.class.php(72): PurgeLogs::getDateModRestriction('0') #1 /var/www/html/glpi93/inc/purgelogs.class.php(42): PurgeLogs::purgeSoftware() #2 /var/www/html/glpi93/inc/crontask.class.php(836): PurgeLogs::cronPurgeLogs(Object(CronTask)) #3 /var/www/html/glpi93/front/crontask.form.php(49): CronTask::launch(-1, 1, 'PurgeLogs') #4 {main} thrown in /var/www/html/glpi93/inc/purgelogs.class.php on line 364

* URL of the page :
http://localhost/glpi93/front/crontask.form.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

glpi 9.3 upgraded from 9.2.2.

Operating system: Linux Vostro-200 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64
PHP 7.0.28-0ubuntu0.16.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, libxml, mbstring, mcrypt, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml,
	xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at localhost Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0
Server Software: Ubuntu 16.04
	Server Version: 10.0.34-MariaDB-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: xxxxxxx@localhost/glpi93
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
Fixed in 9.3/bugfixes branch
