### ISSUE TITLE
Tickets waiting for your approval button

### ISSUE THREAD

**Issue by kedson42** [glpi-project/glpi#3892]
Hi guys.

I think I found a problem with the "tickets waiting for your approval" button.
It works fine if the ticket has only one approval request, but if it has more than two and one of them is already granted or refused, the button won't bring the ticket anymore.

![image](https://user-images.githubusercontent.com/34751754/39057865-bcb0d404-4490-11e8-8676-bbeeb3576395.png)

![image](https://user-images.githubusercontent.com/34751754/39057933-e53a8b72-4490-11e8-8bd9-26a50dfcd938.png)

![image](https://user-images.githubusercontent.com/34751754/39057968-fc9b6656-4490-11e8-9391-83831dbdb3ce.png)

![image](https://user-images.githubusercontent.com/34751754/39057982-04778bac-4491-11e8-8c2d-2d7cbaf767d8.png)

Perhaps it's necessary to change this button in order to bring more scenarios. Something like this:

![image](https://user-images.githubusercontent.com/34751754/39058115-5535beba-4491-11e8-9f7c-dfff05be4093.png)

I'm using GLPI 9.2.1

**Comment by kedson42** [comment]
I figured that this is actually working perfectly.

The reason I stopped seeing the ticket is because I had approved it! The other approver could see it.
So it makes total sense.

My bad.

I'm closing this issue.

**Comment by yustas84** [comment]
in my case, if I rejected the validation, wrote the comments, and then the designated specialist corrected the comments and again sends me a ticket for approval, I do not see it on the main page. Only if someone sets the General approval status of this ticket to "pending approval", then the ticket appears on my home page in the block "requiring approval"

**Comment by yustas84** [comment]
проблема всё ещё остаётся актуальной.
