### ISSUE TITLE
[9.3 beta] asset massive action decomission date 

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#3894]
* Steps to reproduce (which actions have you made) :
glpi>assets>computers> massive action>modifiy>decomission date> execute

* Expected result :
decomission date is set to choosen date

* Actual result :
 message :  "update failed", decomission date is not set 
![image](https://user-images.githubusercontent.com/13557254/39082561-b69e4144-4555-11e8-914a-5b5d241cfaaa.png).

* URL of the page :
http://localhost/glpi93/front/computer.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
glpi 9.3 upgraded from 9.2.2

**Comment by ladenree76000** [comment]
it allready was so in 9.2.2 ( and 9.1.6)

**Comment by trasher** [comment]
Thanks for the feedback :)
