### ISSUE TITLE
[9.3 beta] ticket task template don't fill task category nor action time

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#3895]
* Steps to reproduce (which actions have you made) :
create task template with description, category, status actiontime, actor, group.
use this template to create a ticket task task

* Expected result :
task created with filled fields

* Actual result :
only description and status are filled

* URL of the page :
http://localhost/glpi93/front/ticket.form.php?id=2236

* Screenshot of the problem (if pertinent) :
template : 
![image](https://user-images.githubusercontent.com/13557254/39086100-09c29942-458d-11e8-9dcc-96f43f8e1699.png)
created task : 
![image](https://user-images.githubusercontent.com/13557254/39086113-4419bb02-458d-11e8-8314-e9ca2a641a5a.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3-dev (/glpi93 => /var/www/html/glpi93)
Installation mode: TARBALL

**Comment by trasher** [comment]
Fixed in https://github.com/glpi-project/glpi/pull/4046
