### ISSUE TITLE
9.2, 9.3 ticket followup with hyperlinks may be misrendered

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#3907]
Tested with GLPI 9.3, branch master, up to date

Notice in the screenshot below t hat the hyperlink spans on 2 distinct paragraphs

![image](https://user-images.githubusercontent.com/14139801/39173497-2c096e08-47a5-11e8-9f84-1a20fd255003.png)

### Steps to reproduce
- create a ticket
- add a followup with at least 2 paragraphs, separated by **only one new line**. First paragraph must end with an URL, second paragraph must have at least 2 words.

example
```
paragraph2 with hyperlink https://github.com
paragraph3 with some words
```

### expected result
![image](https://user-images.githubusercontent.com/14139801/39173890-4c2d4924-47a6-11e8-93c8-8347827eadc8.png)

**Comment by trasher** [comment]
With rich text enabled and/or disabled?

**Comment by btry** [comment]
Rich text is enabled.
