### ISSUE TITLE
Saved Searches - empty dropdown with characteristics: item type

### ISSUE THREAD

**Issue by p-bo** [glpi-project/glpi#3910]
Hi,
When I want to use search function, search by item type, the dropdown menu is empty.
(and there is more, for example Characteristics - operating system isn't present at all).
Debug mode yielded no clue what could be wrong.
 
* Steps to reproduce (which actions have you made) :
N/A - this was first time, I needed to use this function, so didn't notice after what action it is broken.

* Expected result :
see http://glpi-developer-documentation.readthedocs.io/en/master/_images/search_criteria.png

* Actual result :
![search-item_type-empty_list](https://user-images.githubusercontent.com/12208593/39182153-4607892c-47bc-11e8-9a95-123f38a42668.png)

* URL of the page :
glpi_url/front/savedsearch.php

* Screenshot of the problem (if pertinent) :
see Actual result

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
[setup-general-system.pdf](https://github.com/glpi-project/glpi/files/1942355/setup-general-system.pdf)

Thanks :)

**Comment by trasher** [comment]
"Characteristics - operating system" no longer exists in 9.2. It's beenn replaced with several entries under the "Operating system" optgroup.
As for types, they're listed from database contents: no entries, no item list.

As far as I can see, there is no bug here.

**Comment by p-bo** [comment]
For operating system, I see.
For types - in database there are entries - inventory (from Fusion Inventory) of few machines, snmp network devices, etc. and they do have type (notebook, qemu, other, etc).

Sorry for continuing here even it probably isn't bug - if really isn't, may we continue on http://forum.glpi-project.org/ ?

**Comment by trasher** [comment]
You must have saved searches entries; acording to your screenshot, you do not have.
Yes, If you cannot understand how it works, you'd better ask on forums ;)

**Comment by p-bo** [comment]
Oh, I see now - was confused where to use search function - it is everywhere on top bar (and possible to save). Thanks a lot and promise, that next time will ask on forum ;)
