### ISSUE TITLE
GLPI 9.2.2 Knowledge Base (KB) does not add image or other files

### ISSUE THREAD

**Issue by DimmoK** [glpi-project/glpi#3918]
Hello!
Sorry for my English.
I have a problem with adding images or files to Knowledge Base (KB).
When I try to adding new item, the field for adding files is empty.

* Steps to reproduce (which actions have you made) :
Tools --> Knowledge base --> Add

* Expected result :
Adding files 

* Actual result :
Field for adding files is empty

* URL of the page :
http://glpi.test.ru/front/knowbaseitem.form.php

* Screenshot of the problem (if pertinent) :
![gpli_kb_addfile_empty](https://user-images.githubusercontent.com/38726947/39252441-5276f966-48ae-11e8-9b0c-74ccae266743.PNG)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

<details><summary>infornation about my GLPI</summary><p>

Information about system installation and configuration
--
[code]   GLPI 9.2.2 ( => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux gr-services 4.4.0-119-generic #143~14.04.1-Ubuntu SMP Mon Apr 2 18:04:36 UTC 2018 x86_64 PHP 5.6.35-1+ubuntu14.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, XCache, XCache Cacher, 	XCache Coverager, XCache Optimizer, Zend OPcache, apache2handler, bcmath, calendar, ctype, curl, date, dom, ereg, exif, 	fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, json, ldap, libxml, mbstring, mcrypt, memcache, memcached, 	mhash, msgpack, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at glpi.*.ru Port 80) 	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.189 Safari/537.36 Vivaldi/1.95.1077.60 Server Software: (Ubuntu) 	Server Version: 5.5.59-0ubuntu0.14.04.1 	Server SQL Mode:  	Parameters: usrglpi@localhost/gr_glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed APCu extension is not present /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

Server: '**', Port: '***', BaseDN: 'OU=**,DC=*,DC=*,DC=ru', Connection filter: none, RootDN: 		'*@*', Use TLS: none

Not active

Way of sending emails: PHP

Name: '*@*.ru' Active: Yes 	Server: '{mail.*.ru/pop/novalidate-cert/tls}INBOX' Login: '*@*.ru' Password: Yes

environment          Name: Environment                    Version: 2.1.0      State: Not activated 	formvalidation       Name: Form Validation                Version: 0.2.3      State: Not installed 	fusioninventory      Name: FusionInventory                Version: 9.2+2.0-RC1 State: Enabled 	itilcategorygroups   Name: ItilCategory Groups            Version: 2.0.1      State: Not activated 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.7      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.4.0      State: Enabled 	tag                  Name: Tag Management                 Version: 2.1.0      State: Not activated 	browsernotification  Name: Браузерные уведомления Version: 1.1.9      State: Enabled 	domains              Name: Домены                         Version: 1.9.0      State: Enabled 	fields               Name: Дополнительные поля    Version: 1.7.0      State: Not activated 	reports              Name: Отчет                          Version: 1.11.2     State: Not activated 	behaviors            Name: Поведения                      Version: 2.0.2      State: Not activated 	mreporting           Name: Подробные отчеты          Version: 1.4.0      State: Enabled 	archires             Name: Сетевые архитектуры    Version: 2.5.1      State: Enabled 	news                 Name: Уведомления                   Version: 1.3.4      State: Enabled
[/code]

</p></details>

**Comment by trasher** [comment]
Take a try with last 9.2/bugfixes to see if problem is still present.

**Comment by cconard96** [comment]
Verified in master and 9.3/bugfixes. Issue only occurs when "Use rich text for helpdesk" (CFG_GLPI['use_rich_text']) is false which appears to be default?

I noticed knowbaseitem passes 'enable_richtext" to Html::textarea, so Html::textarea tries using the rich text method for file upload. Html::fileForRichText checks the global variable first, then returns if false. Html::textarea doesn't try falling back to the non-rich text method at that point.

**Comment by DimmoK** [comment]
trasher, thank's for your comment, but I using 9.2.2 version.
In my post "infornation about my GLPI" (this is spoiler. Need to click by name).

**Comment by DimmoK** [comment]
Work's for me.

**Comment by joaovitorcavalcante** [comment]
I solved the problem by going into the glpi_configs table and setting the line use_rich_text to 1, but I still do not know how that can affect me.

**Comment by trasher** [comment]
The "rich text" configuration is a nightmare and has alredy been dropped for future major release. as of 9.4, it will always be enable per default.
Setting it to 1 is certinly the best option; but not changing directly in the database.

**Comment by joaovitorcavalcante** [comment]
Yes, I just saw that there is an option for this in the GLPI configuration page. Thanks and have a good day.
