### ISSUE TITLE
Bug with https://github.com/glpi-project/glpi/pull/331

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#392]
Error with this commit:
[Fri Jan 22 15:50:16 2016] [alert] [client ::1] /home/yllen/gitsvn/front/.htaccess: Satisfy not allowed here, referer: http://localhost/glpisvn/front/ticket.form.php?id=144

I'm in apache 2.2.15

After login can't do anything
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

**Comment by barbuslex** [comment]
Yes sorry i've not tested with apache 2.2

I've just replace "Satisfy any" by "Allow from all".

I make a new pull request
