### ISSUE TITLE
Add control of approvals and tasks in tickets

### ISSUE THREAD

**Issue by yustas84** [glpi-project/glpi#3929]
Please add the ability to lock the closure/resolution of the ticket, if a ticket is awaiting approval/validation. control of approvals and tasks in tickets at the moment to prohibit close/solve, if the task is not completed, you can only use the plugins Behaviors. And here to forbid to close/resolve the ticket, if the ticket is not authenticated and is not consistent, the system allows. Specialist receives an alert (screenshot), but to close the ticket maybe.

**Comment by yustas84** [comment]
https://hostingkartinok.com/show-image.php?id=f7c99a4cd22c5da36923679f3ef1a8bb
can't insert file screenshot

**Comment by orthagh** [comment]
Please use [suggestion website](suggest.glpi-project.org) for feature requests, we are a small team and we need to prioritize developments.
So if your feature is popular on the suggest site, we will implements it.

Regards
