### ISSUE TITLE
bad link when try to add Service levels

### ISSUE THREAD

**Issue by klodnitsky** [glpi-project/glpi#3930]
When trying to add Service level, get 404 error and the same with "Checks > Fields unicity"

![image](https://user-images.githubusercontent.com/7794575/39347674-a66dfec6-49fc-11e8-87c6-7a2bfe115ab6.png)

![image](https://user-images.githubusercontent.com/7794575/39347685-b4aa5598-49fc-11e8-88ec-2500ec503c1c.png)

![image](https://user-images.githubusercontent.com/7794575/39347850-62a97750-49fd-11e8-8f37-ce682f296519.png)

I think that there is something wrong with URL variable

GLPI 9.3 BETA

**Comment by trasher** [comment]
https://github.com/glpi-project/glpi/issues/3896
