### ISSUE TITLE
[9.2.3] issue with images in mail 

### ISSUE THREAD

**Issue by ppenin** [glpi-project/glpi#3932]
* Steps to reproduce  :
Send a mail with images/screenshots embedded in the body
Collect this mail with mailgate
add followup with text and copy-paste an image
* Expected result :
Images displayed correctly in GLPI  (ticket page and followups page)
Images displayed correctly in the mail sent by GLPI
no mailgate and queuednotification tasks stucked in running
* Actual result :
Images displayed correctly in GLPI (ticket page and followups page) - test ok
Images not displayed correctly in the mail sent by GLPI - test not ok
no mailgate and queuednotification tasks stucked in running  - test ok

* Screenshot of the problem 

![image](https://user-images.githubusercontent.com/22499638/39360978-b542dd26-4a20-11e8-92bb-83721a4ea743.png)
Server address is correct but no image is displayed in the mail
![image](https://user-images.githubusercontent.com/22499638/39361124-54449734-4a21-11e8-8148-28bcadcb15e5.png)

Followup
![image](https://user-images.githubusercontent.com/22499638/39361021-e0ef3992-4a20-11e8-829f-82e889a99e9e.png)
http://myserver is missing
![image](https://user-images.githubusercontent.com/22499638/39361054-ff5a7694-4a20-11e8-9a87-948af8476079.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

 
GLPI 9.2.3 (/glpi => /usr/share/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux s001linux02 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64
PHP 7.0.29-1+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 10.100.10.18 Port 80)
	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0
Server Software: (Ubuntu)
	Server Version: 5.7.22-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is not present
xmlrpc extension is not present
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_cache : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
OK/usr/share/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

LDAP directories

 
Server: '10.100.10.1', Port: '389', BaseDN: 'DC=mydomain,DC=priv', Connection filter: none, RootDN: 'CN=Service
		Alerte,OU=Comptes de Services,OU=001 (FSS),DC=mydomain,DC=priv', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (hotline-glpi@10.100.10.66)

Mails receivers

 
Name: 'xx@mydomain.fr' Active: Yes
	Server: '{10.100.10.66/pop/novalidate-cert/notls}INBOX' Login: 'hotline-GLPI' Password: Yes

Plugins list

 
	fields               Name: Champs supplémentaires         Version: 1.7.0      State: Enabled
	escalade             Name: Escalades                      Version: 2.2.1      State: Enabled
	simcard              Name: Gestion de cartes SIM          Version: 1.4.2      State: Enabled
	pdf                  Name: Impression pdf                 Version: 1.3.1.1    State: Enabled
	datainjection        Name: Injection de fichiers          Version: 2.5.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.8      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.3      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.4.0      State: Enabled
	reports              Name: Rapports                       Version: 1.11.1     State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.2      State: Enabled

OCS Inventory NG
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: No

**Comment by trasher** [comment]
I'm pretty sure another issue is (was) already opened for that.

**Comment by ppenin** [comment]
Yes it was me but in 9.2.1 and 9.2.2
#3494 and #3284

**Comment by ppenin** [comment]
you can contact me in PM if you want to watch directly

**Comment by ppenin** [comment]
this fixes is already in 9.2.3
I fixes the problème with https://github.com/glpi-project/glpi/pull/3694/commits/8bd958ae02feae207cda8fd92d29d8e6b2de4d58 and the images ares correctly displayed in mails but it stucks queuednotification task.
![image](https://user-images.githubusercontent.com/22499638/39362850-34dbe850-4a28-11e8-90f7-935bc3e897a8.png)

**Comment by ppenin** [comment]
With the fix 8bd958a 
- Mailgate and queuednotifcation are stucked when a mail is collected
- the mail contains only one picture et not the others
![image](https://user-images.githubusercontent.com/22499638/39363088-4f6e8d70-4a29-11e8-90ea-b50e95369f1d.png)

In GLPI
![image](https://user-images.githubusercontent.com/22499638/39363122-72b21a86-4a29-11e8-9212-51ef4261d0cb.png)

**Comment by ameurou** [comment]
you need this one 666025b718b514c511efc93f83e3feecb12b641d too there is a small error  in 8bd958a

**Comment by ppenin** [comment]
The fix 666025b doesn't work for me in 9.2.3
It stucks mailgate and queuednotification when a mail is collected.
First images are not displayed in the mail even if the URL is correct.
![image](https://user-images.githubusercontent.com/22499638/39365161-af71f07a-4a30-11e8-9d46-48fb26f11bd8.png)

Display is ok in GLPI

**Comment by ppenin** [comment]
With this fix, images are correctly displayed in mail and in glpi now. Yes !
![image](https://user-images.githubusercontent.com/22499638/39366018-0cf90bb4-4a33-11e8-81cb-7d2b7c6d422f.png)
But automatic tasks are stucked immediately when the mail is collected. Back to square one !

**Comment by RunSaber** [comment]
I have the same problem.... ¿Really don't exist any fix for this bug?... 

This is a real problem.

Thanks!

**Comment by trasher** [comment]
Guess this is is solved by #3966. Queue remaining running is probably another issue.

**Comment by troublestarter** [comment]
![image](https://user-images.githubusercontent.com/6012203/39690256-c58fbd00-51d9-11e8-9c9b-0b6f5943e072.png)

not functionnal ...
![image](https://user-images.githubusercontent.com/6012203/39690242-b558263e-51d9-11e8-9198-3833afd63358.png)

**Comment by RunSaber** [comment]
Exactly, not functional for me too….

**Comment by troublestarter** [comment]
@trasher something to do ?
Not functionnal ...

**Comment by trasher** [comment]
Ensure apply c8569927eca45e5fcd5860824dd47b158c4ea2e1

**Comment by troublestarter** [comment]
is there only this c856992 to apply to resolve ?

**Comment by RunSaber** [comment]
Ok, i can apply [c856992](https://github.com/glpi-project/glpi/commit/c8569927eca45e5fcd5860824dd47b158c4ea2e1), but the problem continue…

![problem](https://user-images.githubusercontent.com/41074/40064869-6a5d20ca-582e-11e8-860b-5b52ef05f14e.png)

**Comment by vihuarar** [comment]
This problem continues...
