### ISSUE TITLE
[9.2.3] Project > Ticket from project task

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#3937]
Hi,

when i create a ticket from a project task, the ticket title is just the task title, without any reference to the project.
Also, there is no entity defined, and no one as requester.

Is it possible to add it by default to correspond to the project entity at least ?

**Comment by trasher** [comment]
Not sure to undesrtand the issue; but anyways, 9.2.1 is 2 releases late. Please update first, and test again.

**Comment by boscorelly** [comment]
Hi,

i have updated to 9.2.3, and it's the same thing.

I have a project created in root > customer > france. I have created a project task in this project.
When i go to ticket tab, and when i click to "create a ticket from this task", a new ticket page is displayed.

The entity is root instead of the project entity.
The requester is no one (i would prefer the project supervisor)
The ticket name and description are just the task name, instead of (i think) "project name > task name" for the name, and description of the task may be description of the ticket.

**Comment by boscorelly** [comment]
Hi,

just to add, i had to edit the notification template to correspond to the ticket template and have the entity and project name in the email title.

**Comment by trasher** [comment]
OK, this is not a bug, but a RFE. Please use the [suggestion website](http://suggest.glpi-project.org); there are chances a similar request already exists :)
