### ISSUE TITLE
JS error on ticket task creation/update form

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#3938]
On the task creation/edition form, accessible via the `Processing ticket` tab of a ticket, the dropdown located inside the submission button is not closed when a choice is made, due to a javascript error. It seems that it is just a cosmetic issue as the selected status is applied to the ticket after submission.

* Steps to reproduce (which actions have you made) :
1. Create a ticket.
2. Go inside `Processing ticket` tab of this ticket.
3. Click on `Add task` button.
4. Open the dropdown of the submission button.
5. Click on any status.

* Expected result :
The dropdown is closed and the icon corresponding to the choice made is displayed inside the submission button.

* Actual result :
Dropdown is not closed and icon is not displayed.

* URL of the page :
`/front/ticket.form.php`

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3-dev-git-18ddfff5f-18ddfff5f ( => /var/www/glpi)
Installation mode: GIT

**Comment by AnaelMobilia** [comment]
@cedric-anne Hello,
Which browser did you used to test ?

Regards,
Anael
