### ISSUE TITLE
9.2.1 on windows: backups can not be deleted

### ISSUE THREAD

**Issue by ochoalc** [glpi-project/glpi#3939]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.

------------
* Steps to reproduce (which actions have you made) :
 Clic Administracion/Clic Mantenimiento/Clic Borrar Permanentemente

* Expected result :
Borrar un backup antiguo

* Actual result :
Se refresca la pagina y no se borra el backup.

* URL of the page :
192.168.10.56/glpi

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/38859481/39430385-52bc9036-4c53-11e8-9e76-81c8658e3b4b.png)
![image](https://user-images.githubusercontent.com/38859481/39430402-5fb0c564-4c53-11e8-9abe-f94ab9452c18.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

9.2.1 Colombia SurAmerica

![image](https://user-images.githubusercontent.com/38859481/39430464-843cd47c-4c53-11e8-979e-6e8a3bb518fd.png)

**Comment by trasher** [comment]
Please use english.

**Comment by ochoalc** [comment]
Ok. 

Steps to reproduce (which actions have you made) :
Click Administration / Click Maintenance / Click Clear Permanently

Expected result :
Delete an old backup

Actual result: 
The page is refreshed and the backup is not deleted.

URL of the page :
192.168.10.56/glpi

Please, view the screeshots 

GLPI 9.2.1

Thanks

**Comment by trasher** [comment]
Please also edit ticket title

**Comment by ochoalc** [comment]
ok, title edit.

**Comment by AnaelMobilia** [comment]
Bug confirmed on master : the delete button didn't delete the file... :-)

**Comment by ochoalc** [comment]
Thanks

¿What is the solution?

**Comment by AnaelMobilia** [comment]
@ochoalc Could you, please, confirm me than you'r running GLPI on a windows server ?

Regards

**Comment by ochoalc** [comment]
of course, our GLPI run on Windows Server Standard 2012 R2
