### ISSUE TITLE
IE11 - cross site error on tinyMCE ?

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#3944]
* Steps to reproduce (which actions have you made) :
  - Enable rich text on ticket (tiny mce)
  - Open a ticket
  - Copy on the clipboard a picture
  - Made right click -> paste on tinyMCE

* Expected result :
  - Picture is displayed

* Actual result :
Error message (with PR #3943) and no network access (no request are send to glpi !)

Note : there isn't any problem if you made ctrl+v... 😠 

* URL of the page :
http://127.0.0.1/glpi/front/ticket.form.php?id=1

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/6187125/39455066-e6fa48fc-4cde-11e8-8637-38613cafc192.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
dev-9.4
IE11 / W10 17.09 x64

**Comment by trasher** [comment]
Fixed in https://github.com/glpi-project/glpi/pull/3943

**Comment by tomolimo** [comment]
Hello @AnaelMobilia 
Are you sure this is a cross site pb?
It seems to me that there is no other site than GLPI involved, isn't it?
If yes it cannot be cross site :)
Could you switch to developer mode (F12) and check the error message in the Javascript console and in the network trace? When there is a cross site issue, usually, there is a message that shows it.

Regards,
Tomolimo

**Comment by AnaelMobilia** [comment]
Hello @tomolimo 
I'm not sure for the cross site... it looks like an the behavior, but...
As described on the ticket, the error message is "Error: Accès refusé." (as I have a french OS).
Note that this is "Error" and not "Erreur".

As updated on #3943, the error message is displayed.

I duno which part of the navigator block the picture pasting (only if right click + paste, not if ctrl + v or right click + paste after having made a ctrl + v).... really strange behavior.
Only on IE...
Not any trace on the network observer on IE...

Regards,
Anael

**Comment by trasher** [comment]
Can you confirm this behavior is only on GLPI, and not a global browser issue?

**Comment by cedric-anne** [comment]
@AnaelMobilia 

Can you try using the last version of TinyMCE ? I made a PR for this in 9.3 https://github.com/glpi-project/glpi/pull/4148.

Regards
