### ISSUE TITLE
Few spelling mistakes

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#3945]
Hi @trasher ,
found couple of spelling mistakes while translating on transifex
1.  inc/config.php:281 ('You are trying to update to a development version from a development version. This is not suppoorted.')  
should be ('You are trying to update to a development version from a development version. This is not supported.')

2.  inc/notificationmailing.class.php:101
$text .= "\n" . sprintf(__('Orignal email address was %1$s'), $CFG_GLPI['admin_email']);
should be $text .= "\n" . sprintf(__('Original email address was %1$s'), $CFG_GLPI['admin_email']);

3. inc/notificationeventmailing.class.php:254
$text = sprintf(__('Orignal email address was %1$s'), $current->getField('recipient'));
should be $text = sprintf(__('Original email address was %1$s'), $current->getField('recipient'));

4. inc/rack.class.php:307
echo "<td><label for='mesured_power$rand'>".__('Mesured power (in watts)')."</label></td>";
shud be echo "<td><label for='mesured_power$rand'>".__('Measured power (in watts)')."</label></td>";

**Comment by trasher** [comment]
Targets 9.2.x except 4 that does not exists before 9.3.
