### ISSUE TITLE
[0.90.1] Cannot add multiple elements on contracts

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#395]
Hi,

In old contracts (before GLPI 0.90 migration) we can add multiple elements : 
![old_good](https://cloud.githubusercontent.com/assets/113057/12547975/9eb42322-c353-11e5-8bfe-89fbcc18f1a3.PNG)

In new contract (created in GLPI 0.90) we can add only 1 element : 
![new_bad](https://cloud.githubusercontent.com/assets/113057/12547993/bb179b84-c353-11e5-83f0-20bdecf701e9.PNG)
The add button is missing...

I can not add the contact from an element also. The contract does not appear in the dropdown list.

It is a bug ?

Thanks

**Comment by wawax** [comment]
Hello,

What's the max number of items for this contract ?

Thanks.

**Comment by barbuslex** [comment]
Hi @wawax ,

My bad. It was set to 1. Problem solved.

Thanks so much.
