### ISSUE TITLE
Add lines to the global search

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#3950]
Please add lines to the global search.
9.2.2

**Comment by trasher** [comment]
This does not means anything to me. Consider using suggestion webstie for RFE.

**Comment by Eon9D** [comment]
@trasher 
By second reading i see you could misunderstand "lines". I mean the "phone lines" under management.
The global search on the top right corner searches all inventory etc. bot not the "phone lines".
Doesnt seems to be a suggestion, simple has been forgotten as the lines are a new feature.
Or am I wrong ?

**Comment by trasher** [comment]
OK, I did not understand what you mean at all :D
I reopen this one, but I do ont know yet if this can be done easily (this may require some extra work, changes in the schema, ...)

**Comment by Eon9D** [comment]
@trasher @orthagh 
Works! Thank you 👍
