### ISSUE TITLE
No user picture set affects row size on users page 

### ISSUE THREAD

**Issue by tyronewyatt** [glpi-project/glpi#3955]
* Steps to reproduce (which actions have you made) :
Enable picures on default view of users page.

* Expected result :
Display generic head image /glpi/pics/picture_min.png or /glpi/pics/picture.png for users with no picture set.

* Actual result :
No image is displayed
Not displaying generic image affects spacing of users without images.

* URL of the page :
/glpi/front/user.php

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/13756677/39560508-dec5d048-4ee1-11e8-95a0-b13b4196d5c6.png)

**Comment by trasher** [comment]
It seems search results does not return anything when there is no image; so this is not just a simple display issue, but this would lend to rework part of the search engine... 
And this is often a huge job.

**Comment by cedric-anne** [comment]
Hi,

When displaying result, the algorithm does not call `$item->getSpecificValueToDisplay()` function for empty values. It cames from this test: https://github.com/glpi-project/glpi/blob/9.2/bugfixes/inc/search.class.php#L5065, which returns false when value is empty.

It could be a usefull enhancement to give ability to handle empty values directly in this function in each item. The main problem is, as the is no call to this function with empty values for now, changing it could cause many bugs, in core and in plugins.

Adding a new option to allow calls on `getSpecificValueToDisplay()` with empty values seems a bas idea, as it would introduce useless complexity.

Modifiying behaviour of all `getSpecificValueToDisplay()` in core and plugins to handle empty values would be a pain, as it is used in a lot of itemtypes.

Regards
