### ISSUE TITLE
Issue with the itemtype list

### ISSUE THREAD

**Issue by brandonguigo** [glpi-project/glpi#3959]
* Steps to reproduce (which actions have you made) :
Use the GLPI RESTapi to get the data of a ticket. 

* Expected result :
A list of the itemtype and the description of it

* Actual result :
The documentation link is not available.

* URL of the page :
https://forge.glpi-project.org/projects/glpi/embedded/class-CommonDBTM.html

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.1.3

**Comment by trasher** [comment]
GLPI 9.1 is no longer maintained. Please update to latest release and check if problem persists.

**Comment by brandonguigo** [comment]
I've updated to 9.2.3 and the link doesn't redirect to the page which list the itemtype returned by the API in JSON and the description of each items...

**Comment by orthagh** [comment]
In 9.2.3, the link should have returned the following (and functional) url: 
https://forge.glpi-project.org/apidoc/class-CommonDBTM.html

> the description of each items

We don't have this.
If you want to have a specific itemtype when knowing corresponding page in glpi, usually you'll find the system key in the url of this page.

Some example, 
- for ticket: `front/ticket.form.php`, system key: ticket, Itemtype: Ticket
- Network devices: `front/networkequipment.php`, system key: networkequipment, itemtype NetworkEquipment.
etc.

**Comment by brandonguigo** [comment]
I think i didn't explain correctly what I wanted. I want to know what, for example,  the key "users_id_lastupdater" stand for in the JSON returned item when GET request in the rest api?

**Comment by orthagh** [comment]
we don't have any documentation of this kind.
And we don't have time to describe each fields available in each tables of glpi.

If you have some fields you don't understand, we can discuss about it.
[developer documentation](http://glpi-developer-documentation.readthedocs.io/en/master/devapi/database/dbmodel.html) could explains some parts.

For the precise `users_id_lastupdater` example, it's the a foreign key to `glpi_users` table (`_id` part), and the last updater part indicate the specific role (aka the id of the user who last updated the current item).
