### ISSUE TITLE
Massive Action on field "Reform Date" has no effect

### ISSUE THREAD

**Issue by dubreido** [glpi-project/glpi#3964]
* Steps to reproduce (which actions have you made) :
Select 5 computers , then "Action" > "Update" > "Reform Date" > 2018/05/30 via calendar > "Submit"

* Expected result : Reform Date = 2018/05/30

* Actual result : Reform Date = 

* URL of the page :  front/computer.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) : Glpi 9.2.2

**Comment by trasher** [comment]
Please try with latest stable; and provide logs output if any.
