### ISSUE TITLE
9.2.3: No link between profile rigths and allowed search parameters

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#3968]
Hi,

On 9.2.3 (and lower) if I deactivate certain rights from a profile the changes are visible on the menu bar and the items themselves but not in the search options.
Example: I deactivated the Validation, Satisfaction and Problems on tickets. They are no longer available for this profile in the interface but still available in the ticket search options.

How can I quickfix this locally on production and what do you think about fixing this for all GLPI items?

Thanks

**Comment by trasher** [comment]
Did you logout/login again after change to the profile?

**Comment by orthagh** [comment]
See fix for problems: https://github.com/glpi-project/glpi/pull/3973/files

For validation, no change, without validation right, you still can view global validation state in ticket form.
For satisfaction , where did you find a right for this one ?

**Comment by pVesian** [comment]
@orthagh Indeed, it's not there, I must have confused it with something else.
