### ISSUE TITLE
Impossible to have a picture attached in mail but work in UI

### ISSUE THREAD

**Issue by troublestarter** [glpi-project/glpi#3975]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.

------------
* Steps to reproduce (which actions have you made) 
Add a picture in copy/paste in a ticket

* Expected result :
see the picture in the mail send by glpi

* Actual result :
a red cross with message : impossible to display the linked picture.....

* URL of the page :

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/6012203/39640207-8f5af6f2-4fca-11e8-9649-b8dd4e731008.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

[code]   GLPI 9.2.3 ( => /usr/share/glpi) Installation mode: TARBALL
--

Operating system: Linux support 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 PHP 5.6.30-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, 	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at support.my-cosi.info Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 Server Software: (Debian) 	Server Version: 5.5.55-0+deb8u1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /usr/share/glpi/config : OK /usr/share/glpi/files : OK /usr/share/glpi/files/_dumps : OK /usr/share/glpi/files/_sessions : OK /usr/share/glpi/files/_cron : OK /usr/share/glpi/files/_graphs : OK /usr/share/glpi/files/_lock : OK /usr/share/glpi/files/_plugins : OK /usr/share/glpi/files/_tmp : OK /usr/share/glpi/files/_cache : OK /usr/share/glpi/files/_rss : OK /usr/share/glpi/files/_uploads : OK /usr/share/glpi/files/_pictures : OK /usr/share/glpi/files/_log : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed) phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/usr/share/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

Not active

Way of sending emails: SMTP (relay@my-cosi.info@10.10.13.2)

 

news                 Name: Alertes                        Version: 1.3.2.5    State: Not activated 	arsurveys            Name: AR Surveys                     Version: 1.4.1      State: Not activated 	behaviors            Name: Comportements                  Version: 2.0.0      State: Not activated 	formcreator          Name: Formulaires                    Version: 2.5.0      State: Not activated 	datainjection        Name: Injection de fichiers          Version: 2.4.2      State: Not activated 	purgelogs            Name: Purge de l'historique          Version: 1.3.0      State: Not activated 	dashboard            Name: Tableau de bord                Version: 0.8.4      State: Not activated
[/code]

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/3932
