### ISSUE TITLE
9.2.2 unable to display page tickets ( list and detail ) with apache proxy 

### ISSUE THREAD

**Issue by willouuu** [glpi-project/glpi#3978]
* Steps to reproduce (which actions have you made) :
Use apache proxypass, and cache browser
Clic on anything item ( tickets list, ticket, ...)

* Expected result :
Display page

* Actual result :

> �HTTP/1.1 200 OKDate: Mon, 07 May 2018 07:21:21 GMT Server: Apache X-Powered-By: PHP/5.6.36 Expires: Mon, 26 Jul 1997 05:00:00 GMT Cache-Control: no-store, no-cache, must-revalidate Pragma: no-cache x-frame-options: SAMEORIGIN Content-Encoding: gzip Vary: Accept-Encoding Keep-Alive: timeout=15, max=96 Connection: Keep-Alive Transfer-Encoding: chunked Content-Type: text/html; charset=UTF-8 136a ��VMo�0��W(��2�MP``{�`0`=l@��T���Ȳ#�I��'�M�m�Ѻ��2)���)ǣ�_.�~����J����´4�疧q2KcBҐ~�|9c���ͥ�H�L�,�z���L�:��7��s~�-�j��	��>����%��T�}d6M ���t��,!	����<̨H2X��	o$�Z8%5$� �5�%���h���mkH8�E�9� y�#��)�4�F�Uv�ZD��**��^+�p|���qT�a�&����ɻpN8+!C�q�0��Ci���1�5�Ϲ���O4(���ׄ^֓{]� Â�VBn�U%���mx���P�����-����E�?��-z2�n����lX�w�ݝ��u#��-5�s�	�l��o^"���]�ϋ��������v�C?݃$�R�}��D�쐂C���\�����>��0΅\�^˙���1�x ]7��a�؇��Q�&}�G��;6��z|l�/%a	�K�BfYe�l �l���j�+�N�3iA��������is�6���zyQ>�Ķ�I���ݶ�$N�3uG����"����=;��c�@�nw5c��n���T+�,IF4d+��I�gZ�)�⊈`D�\5L��K�I(�0�P|6� �H4�|>�)��#�X�ŋ�G���$��Qo�G��!��~�E����2��r� %��4��¼ �/����&Ha�?u���O5?�!��@f��� �h�p�ȽL�@F኎��p���񖣳` ��"�\Kl1�B������y�Kq5`aXLо�,>K�M��N��;��\]TUsAk�b%@� ޻oM/��ʚjBY�(�0ז}���E��%(����1��<ǀ�C��k�c�'�%��	����Gs�B ���⊄`z��2�BI��+>g*x��Q���F������cN���Jr��`ʉ�yk�ӝ-�>��_~��G���S��t�l�~�0R�%�L�tE�0[�L��0xyM�W�9�� ԁ3Iv����>���/c�����o�����.���1��l�"�7a���+�:��Q7�m��b7�9� �Ie5��R���#DY�>S>���#;^�:|r�a��H�k�S͍����������L�9�Z�y^u1�� �2�¼z�3ښ �6���2�����.ŗ�וފ&IM�Q¢xҍhq~q���ޞl�6q���S4�WX-�L噀U�"iD P�N� fs������=�/xד�����p8c�I�����q� ��<$K��d2���v��Z~4'�&m�4�.��<~�7����!��L������N����Hz����՟��S��$K�������n����yj�/�2~^=Q�j��7�+��R�D	fa�(�SZx��x�>q�|��!���Q�<���p�=@�l���MP�?Q3��/��Sxq�����_=|��.?��_���<��G�x���o��Sw�`�9>��{�w�]n3if�3m�(0`� �~/�� 4�+���x���3�(�6�_c�&1(~(���26�j���Q�ּ��l���	V�y�\cx��0}n������r�a�@OPn-

* URL of the page :
front/central.php
front/ticket.form.php?id=XXXX

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/7153125/39689601-b3af2a64-51d7-11e8-9583-73504f20fc14.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

> GLPI 9.2.2 (/assistance => /local/webRoot/glpi) Installation mode: TARBALL
> --
> 
> Operating system: Linux machine 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 PHP 5.6.36 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, 	libxml, mbstring, mcrypt, memcache, mhash, mysql, mysqli, mysqlnd, oci8, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, 	posix, recode, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, twig, wddx, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="300" memory_limit="2G" post_max_size="2G" safe_mode="" session.save_handler="files" 	upload_max_filesize="2G"  Software: Apache () 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36 Server Software: MariaDB Server 	Server Version: 5.5.56-MariaDB 	Server SQL Mode:  	Parameters: glpi@bdsinfo/glpi 	Host info: bdsinfo via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /local/webRoot/glpi/config : OK /local/webRoot/glpi/files : OK /local/webRoot/glpi/files/_dumps : OK /local/webRoot/glpi/files/_sessions : OK /local/webRoot/glpi/files/_cron : OK /local/webRoot/glpi/files/_graphs : OK /local/webRoot/glpi/files/_lock : OK /local/webRoot/glpi/files/_plugins : OK /local/webRoot/glpi/files/_tmp : OK /local/webRoot/glpi/files/_cache : OK /local/webRoot/glpi/files/_rss : OK /local/webRoot/glpi/files/_uploads : OK /local/webRoot/glpi/files/_pictures : OK /local/webRoot/glpi/files/_log : OK | Web access to the files directory, should not be allowedAutomatic checks cannot be done; please review .htaccess file and the web server configuration.
> 
> htmLawed version 1.2.4 in (/local/webRoot/glpi/lib/htmlawed) phpCas version 1.3.5 in (/local/webRoot/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/local/webRoot/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/local/webRoot/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/local/webRoot/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/local/webRoot/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/local/webRoot/glpi/vendor/true/punycode/src) iacaml/autolink in (/local/webRoot/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/local/webRoot/glpi/vendor/sabre/vobject/lib)
> 
> Server: 'ldap://ldap.domaine.fr', (...........) Use TLS: none
> 
> Not active
> 
> Way of sending emails: SMTP (anonymous@mailhost.domaine.fr)
> 
> Name: 'ticket-informatique@domaine.fr' Active: Yes 	Server: (...........)  Password: 		Yes
> 

If we disable browser cache or if we access to direct page ( without proxypass ) it's work

**Comment by trasher** [comment]
Sounds like a proxy configuration issue rather than a GLPI issue.

**Comment by willouuu** [comment]
I have a basic proxy configuration. It worked very well before the update!
To temporarily fix, I have set this config :

```
        <Location /assistance >
                ProxyPass http://xxxxxx/assistance
                ProxyPassReverse http://xxxxxx/assistance
                Header unset ETag
                Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
                Header set Pragma "no-cache"
                Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
        </Location>
```

**Comment by wixaw** [comment]
I found a solution to my issue. I delete pictures of all users in files/_pictures/
A change of avatars has it occurred between 9.1 and 9.2 ?
