### ISSUE TITLE
Problème d'affichage page suivante dans les onglets d'inventaire

### ISSUE THREAD

**Issue by monpelaud** [glpi-project/glpi#398]
CentOS 7
GLPI 0.90.1/Bugfixes

Bonjour,

Impossible d'afficher plus de 20 enregistrements dans les onglets d'inventaire d'un poste (Logiciels, Historique, etc...).
La modification de la valeur "Affichage (nombre d'éléments)" n'est pas prise en compte et il est impossible de faire défiler les pages avec le bouton "Suivant".

Cordialement

**Comment by orthagh** [comment]
Bonjour.

Normalement ce problème est réglé avec ce commit précis : https://github.com/glpi-project/glpi/commit/d4e705682e6c948cc55678d3a0afc5203313fc67

C'était une regression apportée par ce précédent : https://github.com/glpi-project/glpi/commit/45b4b878dd7ebcc2931d9d26141b42e8dcf53652

Sur une version non pulbiée de glpi donc.
