### ISSUE TITLE
9.2.3 Error on delete devices on dustbin (massive actions)

### ISSUE THREAD

**Issue by gituncar** [glpi-project/glpi#3982]
When I try to delete device after put in dustbin.

![image 1](https://user-images.githubusercontent.com/7705197/39757586-e989e5c8-5292-11e8-9472-5b5816feeaba.png)

Fatal error: Uncaught Error: Class 'PluginFieldsPeripheralcorresponde' not found in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php:501 Stack trace: #0 C:\xampp\htdocs\glpi\inc\plugin.class.php(1259): PluginFieldsContainer::preItemPurge(Object(Peripheral)) #1 C:\xampp\htdocs\glpi\inc\commondbtm.class.php(1440): Plugin::doHook('pre_item_purge', Object(Peripheral)) #2 C:\xampp\htdocs\glpi\inc\massiveaction.class.php(1078): CommonDBTM->delete(Array, 1) #3 C:\xampp\htdocs\glpi\inc\massiveaction.class.php(993): MassiveAction::processMassiveActionsForOneItemtype(Object(MassiveAction), Object(Peripheral), Array) #4 C:\xampp\htdocs\glpi\inc\massiveaction.class.php(972): MassiveAction->processForSeveralItemtypes() #5 C:\xampp\htdocs\glpi\front\massiveaction.php(63): MassiveAction->process() #6 {main} thrown in C:\xampp\htdocs\glpi\plugins\fields\inc\container.class.php on line 501

**Comment by AnaelMobilia** [comment]
Hello,

This appears to be linked with the fields plugin.

Please open an issue again their https://github.com/pluginsGLPI/fields

Regards
