### ISSUE TITLE
"Less than" and "greater than" symbols (< and >) are stripped out from followups (seems HTML tag removal)

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#3983]
My `<` and `>` characters and anything between them are removed from ticket followups.
I am using TinyMCE text editor.

**Steps to reproduce:**
1. Type the following a followup in a ticket: **Hello "<foo>" bar.**
2. Submit the followup.

**Expected result:**
Displayed ticket followup should be:
> *Hello "<foo>" bar.

**Actual result:**
Ticket followup is displayed as follows:
> *Hello "" bar.
(`<foo>` is missing)

**Analysis:**
The `glpi_ticketfollowups.content` database field does indeed contains:
```
&lt;p&gt;Hello "&lt;foo&gt;" bar.&lt;/p&gt;
```
HTML code returned by AJAX call is:
```HTML
<div class='item_content '><p><p>Hello "<foo>" bar.</p></p></div>
```

Editing the followup in AJAX debug mode (having opened the followup tab only) makes the <textarea> contains:
```HTML
<p>Hello "<foo>" bar.</p>
```
On normal mode it contains (in TinyMCE's source code view):
```HTML
<p>Hello "" bar.</p>
```

It looks like some "html entity interpretation" operation is done on AJAX-transport.

**Versions:**

GLPI version: 9.2.2
PHP version: 5.6.33

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/140
