### ISSUE TITLE
Ticket approval rule 

### ISSUE THREAD

**Issue by krlos571** [glpi-project/glpi#3985]
Hi Friends, i created a business rule for automatic approval request depending on the category assigned to the ticket.
In criteria were defined the categories that need the approval of a manager.
In Actions were defined:
- Minimum validation requiered
- Request for approval to the requesting group manager

Technically, an approval request should be sent to the Manager defined in the requesting user group, right?
The action "Minimum validation requiered" is being applied normally.
It would be bug or some incorrect configuration that I did

Thanks

Screenshots:
- Criteria list
![criteria](https://user-images.githubusercontent.com/20146588/39822560-41f148ca-5381-11e8-95ea-c22617d14de8.JPG)
- Actions list
![action](https://user-images.githubusercontent.com/20146588/39822559-41ca2088-5381-11e8-8f15-5c9da2278bad.JPG)
- User group with Manager defined
![group](https://user-images.githubusercontent.com/20146588/39822561-4216a502-5381-11e8-9758-df8e5dfc8544.JPG)
- Test ticket
![ticket](https://user-images.githubusercontent.com/20146588/39822562-423bb6c6-5381-11e8-8ebd-bf8140bb9ab3.JPG)
 - No validation send
![ticket_v](https://user-images.githubusercontent.com/20146588/39822557-41a66580-5381-11e8-853f-9432f823c06b.JPG)

**Comment by jonatangobbato** [comment]
Você pode usar o plugin Beahviors para inserir automaticamente o grupo requerente ao chamado, ou criar uma regra de negócio que faça isso

**Comment by AnaelMobilia** [comment]
@jonatangobbato Please, use english as we can understand and help you :-)

Regards,
Anael

**Comment by krlos571** [comment]
@jonatangobbato Obrigado
Thanks, I'll try to use the plugin and I'll answer if it worked. :)

**Comment by trasher** [comment]
Does not seems to be a GLPI bug, I close
