### ISSUE TITLE
Undefined index: glpiactiveprofile

### ISSUE THREAD

**Issue by monpelaud** [glpi-project/glpi#399]
Bonjour,

Le message d'erreur suivant apparait régulièrement dans le fichier php-errors.log:

  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc/item_ticket.class.php:372
  inc/commonglpi.class.php:208                       Item_Ticket->getTabNameForItem()
  inc/ticket.class.php:657                           CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:158                       Ticket->defineTabs()
  ajax/updatecurrenttab.php:48                       CommonGLPI->defineAllTabs()

Cordialement

**Comment by orthagh** [comment]
Hello. (Sorry for delay)

Could you precise you glpi version and if you find, the action who triggers this error

**Comment by monpelaud** [comment]
Hi,
I'm using GLPI v0.90.1
Sorry but so far I don't have find the action which triggers this error but I search...

Bests regards

**Comment by yllen** [comment]
with your log it seems that it was when you click on Items tag of a ticket.
But i can't reproduce

**Comment by orthagh** [comment]
I just added a check to prevent theses warnings.
I think the errors triggers when session is lost (timeout) and when the user change tab.
