### ISSUE TITLE
Plugin activation is not working on existing sessions

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#3992]
* Steps to reproduce (which actions have you made) :
1) Open GLPI login page inside private navigation in a browser (to get a clean session).
2) Install and enable "News plugin", and create an alert that is shown on login page.
3) Refresh the login page displayed on step 1.

* Expected result :
The alert should be showned.

* Actual result :
The alert is not showned.
It seems that the list of plugins stored inside `$_SESSION['glpi_plugins']` is not recomputed as the `display_login` hook of the plugin not called.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.3

**Comment by trasher** [comment]
Probably linked to https://github.com/glpi-project/glpi/issues/3763

**Comment by cedric-anne** [comment]
As plugin list is now using a shared cache, this behaviours should be fixed.
