### ISSUE TITLE
Error when Profile Self-service add new Followps 9.2.1

### ISSUE THREAD

**Issue by cjmorenor** [glpi-project/glpi#3995]
Hello everybody!

We use version GLPI 9.2.1.

When Profile Self-service add a new followup with  Simplified Interface, the application to post  field Description (New item - Followup) with little  size.

Please, I can modify the code for enlarge this field.  What would be the part of the code to be modified?

Thank you!!

Please, You can see image "GLPI9.2.1.JPG "  with this error.

https://drive.google.com/file/d/1dy_YiWvCMnQNyeScspqKj1X3xzJWxLjo/view

**Comment by trasher** [comment]
Please test with 9.2.3

**Comment by Armin83** [comment]
I have **NO** problems with Internet Explorer, Firefox and Chrome. (OS Windows 10 1607)
GLPI Version 9.2.3.

> Plugins list
>  
> 	news                 Name: Alerts                         Version: 1.3.4      State: Enabled
> 	barcode              Name: Barcode                        Version: 0.90+1.0   State: Not activated
> 	behaviors            Name: Behaviours                     Version: 2.0.2      State: Enabled
> 	reports              Name: Berichte                       Version: 1.7.2      State: Not activated
> 	dashboard            Name: Dashboard                      Version: 0.8.5      State: Not activated
> 	datainjection        Name: File injection                 Version: 2.5.0      State: Enabled
> 	formcreator          Name: Forms                          Version: 2.6.3      State: Enabled
> 	addressing           Name: IP Adressierung                Version: 2.3.0      State: Not installed
> 	mreporting           Name: More Reporting                 Version: 1.3.1      State: Not activated
> 	mydashboard          Name: My Dashboard                   Version: 1.4.0      State: Enabled
> 	pdf                  Name: Print to pdf                   Version: 1.3.1.1    State: Enabled
> 	ticketcleaner        Name: Ticket Cleaner                 Version: 2.0.4      State: Not activated
>

**Comment by trasher** [comment]
> Is posible, that we can adjust a field, without test 9.2.3 version?.

No. You have to use latest stable release (currently 9.2.3).
