### ISSUE TITLE
GLPI 9.3 installing from tarball issue

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#3997]
Hi @trasher ,
while installing ( fresh ) or upgrading 9.3 from tarball the installation stops at this step testing DB engine. cant proceed after that , please refer the screen shots.
![image](https://user-images.githubusercontent.com/22425503/39964185-a3ae4822-568f-11e8-96d9-08c9431c2e87.png)

**Comment by AnaelMobilia** [comment]
Hello @roshanroche 

Issue fixed on #3988 

Regards,
Anael

**Comment by trasher** [comment]
Fixed in https://github.com/glpi-project/glpi/pull/3988
