### ISSUE TITLE
Ticket ID

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#3999]
Hello

I wanted to come back to GLPI basic ticket id format number xxxxx but ticket number stay at the day of the modification

2018050831 and after 2018050832...

I tried to modify 
![image](https://user-images.githubusercontent.com/30655170/39980474-69fe7594-574c-11e8-9235-2f3b3c52111c.png)
![image](https://user-images.githubusercontent.com/30655170/39980484-72c89a74-574c-11e8-82ea-331492a577e0.png)

Thank you for your help

GLPI 9.2.1
Behavior plugin 2.02

**Comment by trasher** [comment]
Please report this issue against the plugin.
