### ISSUE TITLE
Impossible de créer une nouvelle entité

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#4]
la page localhost/glpi90/front/entity.form.php n'affiche pas le formulaire pour la création d'une nouvelle entité.

GLPI sur un serveur WAMP.
pas de plugins
nouvelle installation ( pas de migration depuis une version précédente)

**Comment by wawax** [comment]
Please open issues in english only.

**Comment by ladenree76000** [comment]
localhost/glpi90/front/entity.form.php does not display when try to create a new entity.
GLPI on Wamp Server
No plugins installed
fresh installation ( not upgraded from earlier version)

**Comment by ladenree76000** [comment]
with fresh installation super-admin profile is non recursive by default. So it's imposible to create an other entity.
changing profile to a recursive one solves.
