### ISSUE TITLE
template 090.1

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#400]
Hi all!

I have a problem

I have a template on which to interface two camps hidden helpdesk.

User (helpdesk) enters and perfect sees the two camps ...

It happens that they want to see the two camps created after the ticket (for technical management) but there are still hidden.

I have selected the default template for the entity and sub-distributors and even also for the super-admin profile, however still leaves me hidden fields and I need to see to update them (Standard Interface).

It is very important to me this functionality. I know I'm not ignoring.

If anyone can help me. I appreciate it.

Thank you.

**Comment by orthagh** [comment]
i assume 'camps' = 'fields'.

Can you precise the name of theses ?

With ticket template, you can't have fields hidden in self-service interface and displayed in technician interface.
If you want to custom ticket's form to guide yours users, i suggest the usage of [formcreator plugin](http://plugins.glpi-project.org/#/plugin/formcreator).
It permits the creation of custom forms.

**Comment by orthagh** [comment]
I close. Please reopen if you have an answer
