### ISSUE TITLE
Incorrect image paths from emails

### ISSUE THREAD

**Issue by risbac** [glpi-project/glpi#4005]
* Steps to reproduce (which actions have you made) :
Receive any ticket by email with an included image

* Expected result :
The image should be displayed in the ticket

* Actual result :
The image is not displayed, the path is wrong. 
<img alt="84f2e379-d985547e-5af97e0e1457f9.56601049" height="319" width="488" src="/front/document.send.php?docid=504&amp;tickets_id=1765" data-mce-src="http://ithelps.tebu-bio.com/front/document.send.php?docid=504&amp;tickets_id=1765">

The URLs are wrong, they are missing "/glpi" at the beginning.

* URL of the page :
Ticket page. 

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

[code]   GLPI 9.2.3 (/glpi => C:\xampp\htdocs\glpi) Installation mode: TARBALL
--

Operating system: Windows NT TEBUVEEAM01 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586 PHP 7.2.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date, 	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, 	pdo_mysql, pdo_sqlite, readline, session, standard, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="90" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.1 (Apache/2.4.29 (Win32) OpenSSL/1.1.0g PHP/7.2.1 Server at 	ithelps.tebu-bio.com Port 80) 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.1.30-MariaDB 	Server SQL Mode:  	Parameters: GLPI@localhost/glpi 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed xmlrpc extension is installed Zend OPcache extension is not present APCu extension is not present C:\xampp\htdocs\glpi/config : OK C:\xampp\htdocs\glpi/files : OK C:\xampp\htdocs\glpi/files/_dumps : OK C:\xampp\htdocs\glpi/files/_sessions : OK C:\xampp\htdocs\glpi/files/_cron : OK C:\xampp\htdocs\glpi/files/_graphs : OK C:\xampp\htdocs\glpi/files/_lock : OK C:\xampp\htdocs\glpi/files/_plugins : OK C:\xampp\htdocs\glpi/files/_tmp : OK C:\xampp\htdocs\glpi/files/_cache : OK C:\xampp\htdocs\glpi/files/_rss : OK C:\xampp\htdocs\glpi/files/_uploads : OK C:\xampp\htdocs\glpi/files/_pictures : OK C:\xampp\htdocs\glpi/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed) phpCas version 1.3.5 in (C:\xampp\htdocs\glpi\vendor\jasig\phpcas\source) PHPMailer version 5.2.26 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer) SimplePie version 1.5.1 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library) TCPDF version 6.2.16 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src) iacaml/autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)

Server: '192.168.5.2', Port: '389', BaseDN: 'OU=Utilisateurs Globaux,DC=tebu-bio,DC=com', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'annuaire@tebu-bio.com', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@192.168.5.22)

Name: 'ithelps@tebu-bio.com' Active: Yes 	Server: '{outlook.office365.com:993/imap/ssl/notls}INBOX' Login: 'ithelps@tebu-bio.com' Password: Yes

dashboard            Name: Dashboard                      Version: 0.9.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Enabled 	mreporting           Name: More Reporting                 Version: 1.4.0      State: Enabled 	purgelogs            Name: Purge history                  Version: 1.3.0      State: Enabled 	ticketcleaner        Name: Ticket Cleaner                 Version: 2.0.4      State: Enabled
[/code]

**Comment by trasher** [comment]
Ensure apply c8569927eca45e5fcd5860824dd47b158c4ea2e1

**Comment by trasher** [comment]
More globally, test with current 9.2/bugfixes branch

**Comment by risbac** [comment]
c856992 didn't fix it. 
To test the bugfixes branch, I can simply download and copy paste it on my current version (with the proper backup of course) ?

**Comment by trasher** [comment]
yes

**Comment by trasher** [comment]
No feedback, closing
