### ISSUE TITLE
[9.2.3] countall automatic action - PHP Errors

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#4014]
* Steps to reproduce (which actions have you made) :

Activation of automatic action countall
GLPI launch it by cli (cron)

* Actual result :

2018-05-16 09:01:02 [@server]
  *** PHP Notice(8): Undefined index: glpiname
  Backtrace :
  inc/search.class.php:345                           
  inc/savedsearch.class.php:1343                     Search::constructSQL()
  inc/savedsearch.class.php:1287                     SavedSearch->execute()
  inc/crontask.class.php:832                         SavedSearch::croncountAll()
  front/cron.php:87                                  CronTask::launch()
2018-05-16 09:01:02 [@server]
  *** PHP Notice(8): Undefined index: glpigroups
  Backtrace :
  inc/search.class.php:3501                          
  inc/search.class.php:363                           Search::addDefaultJoin()
  inc/savedsearch.class.php:1343                     Search::constructSQL()
  inc/savedsearch.class.php:1287                     SavedSearch->execute()
  inc/crontask.class.php:832                         SavedSearch::croncountAll()
  front/cron.php:87                                  CronTask::launch()

And the action is interrupted

![image](https://user-images.githubusercontent.com/13178158/40101732-a13ee64a-58e8-11e8-8b8a-c9f568546111.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

9.2.3 (Centos)

**Comment by flegastelois** [comment]
Seems to be similar of #3179

**Comment by trasher** [comment]
Indeed, on another cron call from the same class. Thanks for the pointer @flegastelois!
