### ISSUE TITLE
[9.2.3] problem with initial redactor and requester

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#4015]
Hi,

we are creating tickets for our customers sometimes.

When we create a ticket, me set the correct requester.
When the ticket is created, when we go to the tab "ticket treatment" (traitement du ticket in french), the writer appears to be the person who created the ticket, and not the requester.

I must go to the tab "ticket" and edit the "by" field, set it to the requester, and then it's good.

**Comment by cedric-anne** [comment]
Hi,

It is not a bug. The `Processing ticket` tab displays the author of actions that are displayed. The author of ticket description is the user who opens it, not the requester. This information will not be changed.

As you have notice, the only way to change this information is to edit the ticket and change the value of the `By` field.

Regards

**Comment by boscorelly** [comment]
Hi,

in the past, it was not working like this. We have this behavior since the update to 9.2.1

**Comment by trasher** [comment]
Yes, and this behavior was wrong; it has been changed.

**Comment by boscorelly** [comment]
Is it possible to add a way to change it, like in ticket template ?
Most of tickets are created by us for customers, and we need to change it each time we create a ticket.

**Comment by cedric-anne** [comment]
Hi @boscorelly ,

You should take a look at #6038 .

Regards
