### ISSUE TITLE
[9.2.3] saved searchalert e-mail

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4016]
Result: i got no saved search alarm e-mail
I got this error a ticket witch linked object with formcreator.

2018-05-16 12:18:53 [6@inventar01]
  From Toolbox::deprecated() in /var/www/glpi/inc/toolbox.class.php line 486
  getDatasForTemplate() method is deprecated (NotificationTargetSavedsearch_Alert)
2018-05-16 12:18:53 [6@inventar01]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/notificationtarget.class.php:1158              Toolbox::deprecated()
  inc/notificationtemplate.class.php:254             NotificationTarget->getForTemplate()
  inc/notificationeventabstract.class.php:103        NotificationTemplate->getTemplateByLanguage()
  inc/notificationevent.class.php:163                NotificationEventAbstract::raise()
  inc/savedsearch_alert.class.php:396                NotificationEvent::raiseEvent()
  inc/crontask.class.php:832                         SavedSearch_Alert::cronSavedSearchesAlerts()
  front/crontask.form.php:49                         CronTask::launch()
root@inventar01:/var/www/glpi/files/_log#

**Comment by trasher** [comment]
Deprecated messages are just informative.

**Comment by Armin83** [comment]
You can close if you don't need this ticket anymore. (I forgot to define a name. now it works)
