### ISSUE TITLE
PHP Warning: long2ip() expects parameter 1 to be integer, string given in /usr/share/glpi/inc/apiclient.class.php at line 160

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#4018]
------------
* Steps to reproduce (which actions have you made) :
Creating API Access without IP restriction

* Expected result :

* Actual result :
Getting warning in History

* URL of the page :
front/apiclient.form.php?id=2

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
%

**Comment by cedric-anne** [comment]
Actually, to reproduce this, you have to add an entry in the log by defining or removing IPv4 range on an existing API client, then display the history tab of this client.
