### ISSUE TITLE
Migrate Users to New Server

### ISSUE THREAD

**Issue by DRST-github** [glpi-project/glpi#4023]
Hello,

I want to migrate existing users in a GLPI server, running version 0.83.7, to a fresh install with version 9.1.7.1.

I tried by exporting glpi_users from the old database and importing the sql file into the new database, using the following commands:

```
mysqldump -u USERNAME -p DATABASE glpi_users > FILENAME.sql

mysql -u USERNAME -p -D DATABASE < FILENAME.sql
```

However, user login is not working correctly. After a login attempt, in the glpi_users table, the hash of the password is altered to a string with special characters.
My question would be: what is the correct way to export and import only the users? As I have no need to migrate anything else.

Thank you.

**Comment by trasher** [comment]
Partial migrations are not supported at all. Maybe should you consider migration your whole base before trying to export users; 0.83 is very old.
In any ways, I won't advice such a partial migration, you may have issues.
