### ISSUE TITLE
erreur dans log php

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#403]
2016-01-27 17:32:14 [26@PLAGLPI001]
  *** PHP Notice(8): Undefined index: lock_use_lock_item
  Backtrace :
  inc/objectlock.class.php:379
  inc/commonglpi.class.php:1117                      ObjectLock::manageObjectLock()
  front/ticket.form.php:181                          CommonGLPI->display()

**Comment by tomolimo** [comment]
Hello
How do reproduce the errors?
Thank you
Tomolimo


-------- Original message --------
From: Sismic
Date:27/01/2016 17:33 (GMT+01:00)
To: glpi-project/glpi
Subject: [glpi] erreur dans log php (#403)


2016-01-27 17:32:14 [26@PLAGLPI001]
*** PHP Notice(8): Undefined index: lock_use_lock_item
Backtrace :
inc/objectlockclassphp:379
inc/commonglpiclassphp:1117 ObjectLock::manageObjectLock()
front/ticketformphp:181 CommonGLPI->display()

**Comment by orthagh** [comment]
imo, update from 0.91 to 0.91 (reproduced one hour ago)

So, @Sismic , change you glpi version in glpi_configs table to 0.90.1 and redo update

**Comment by Sismic** [comment]
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191
PHP Notice: Undefined index: names_format in /var/www/glpi/inc/db.function.php at line 1186
PHP Notice: Undefined index: is_ids_visible in /var/www/glpi/inc/db.function.php at line 1191

**Comment by tomolimo** [comment]
Hello Sismic
If you want some help from us, you **must** give more info as how to reproduce the problem.
Tahnk you,
Tomolimo

**Comment by orthagh** [comment]
This one, fixed on commit 384374fbf5776f1caaa8ffccb9c0b21ae76d55fa

Please git pull before.

**Comment by Sismic** [comment]
c'est corrigé mais j'ai quand même les messages d'erreur ci dessus quand je réalise l'update

**Comment by tomolimo** [comment]
update from which version?

**Comment by Sismic** [comment]
git pull from master branch this morning

**Comment by tomolimo** [comment]
yes, but what was the previous version?

**Comment by Sismic** [comment]
another git pull from master :D

**Comment by tomolimo** [comment]
ok, but was it 0.90?

**Comment by Sismic** [comment]
no, 0.91 but i don't rember when i updated it, approximatly end of december 2015

**Comment by tomolimo** [comment]
ok, but could you do a migration test from a real version?
I mean for example: 0.85, 0.90, 0.90.1?

**Comment by yllen** [comment]
Corrections for entity and profile:
https://github.com/glpi-project/glpi/commit/7465650d32b2672457c94a9af5578627b1ab05cd
https://github.com/glpi-project/glpi/commit/b76b44ea7b6057e1fde96dade3a540bcb51af829

**Comment by tomolimo** [comment]
Thank you Yllen,

**Comment by yllen** [comment]
Tomolimo: I don't see the change in the upgrade of file migration for this new function

**Comment by tomolimo** [comment]
What do you mean?

**Comment by drTr0jan** [comment]
I have two errors in php-errors.log:
1. *** PHP Warning(2): Illegal offset type inc/commondbtm.class.php:3593
`$message[$fields] = $this->input[$field];`
I think it should be `$field` instead `$fields`.
2. *** PHP Notice(8): Undefined variable: message inc/commondbtm.class.php:3446
I think it should be `$message = array();` before the `foreach` statement at :3439.

**Comment by orthagh** [comment]
Please don't open issue for work in progress.
Original topic : https://github.com/glpi-project/glpi/pull/363
