### ISSUE TITLE
Closing the ticket via e-mail by the user

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#4031]
Hi, it would be cool to perform a closing of the ticket (the decision of the ticket) via electronic mail by the user.
By type as below:
![2018-05-21 09 33 56](https://user-images.githubusercontent.com/11009787/40293597-57f4e07a-5cda-11e8-9926-508accc2bb6a.png)

**And it is also important to have a report (statistics) on such users and such closures.**

**Comment by trasher** [comment]
Please use the [suggestion website](http://suggest.glpi-project.org) for RFE.
