### ISSUE TITLE
Other components do not appear on the сomponents tab of the network devices

### ISSUE THREAD

**Issue by FrolON** [glpi-project/glpi#4047]
When i associate other component with network device, it dont shown in network device - > Components tab.

* Expected result : List of components associated with network device.

* Actual result : The list is not displayed.

* URL of the page : /front/networkequipment.form.php?

* Screenshot of the problem (if pertinent)  @:
![othercomponents](https://user-images.githubusercontent.com/39527010/40371349-ee34cc56-5dea-11e8-9375-63ccab2de2bd.PNG)

* Your GLPI setup (you can find it in Setup > General menu, System tab) : 9.2.3

**Comment by trasher** [comment]
Could you please test with current 9.2/bugfixes branch to make sure problem has not yet been solved?

**Comment by FrolON** [comment]
Im new on git. How can i do install bugfix version on my glpi?

**Comment by trasher** [comment]
See https://forge.glpi-project.org/tarballs/

**Comment by trasher** [comment]
ping?

**Comment by FrolON** [comment]
I had install tarball on my GLPI, but proplem is still actual. Additionally, i noticed that i can not link OTHER component from Components tab of network device to it.
![othercomponents2](https://user-images.githubusercontent.com/39527010/40647966-ea639184-6335-11e8-804f-b1c9b851218e.PNG)

**Comment by trasher** [comment]
Indeed, there is something inconsistent here; thanks for the feedback.
