### ISSUE TITLE
[9.2 9.3] don't find translation on transifex

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4054]
-----------
* Reproduce
Login Transifex
Search for "Show suppliers" (Source) or target language "lieferant anzeigen" (german).
In German the correct string ist "Lieferanten anzeigen."

* Expected result :
Find the string and change it.

* Actual result :
I dont't find the string. Can it be a combined String ? The plural from "Lieferant" is "Lieferanten". But i don't understand where the lower case letter "l" get there. I changed this. The original string was "lieferant"

* URL of the page :
https://www.transifex.com/glpi/GLPI/translate/#de_DE/glpipot93/124934886?q=translation_text%3ALieferant

* Screenshot of the problem (if pertinent) :

![2018-05-24 08_23_40-glpi - tickets - 7808 - internet explorer](https://user-images.githubusercontent.com/19192087/40468557-0adf9fc2-5f2e-11e8-86c7-69187e603ea4.png)

**Comment by trasher** [comment]
The source string is "Show %1$s". Replacement is done with item type tanslation, but this is lowered in GLPI code.
