### ISSUE TITLE
[9.2.2] Due date progression colors on tickets panel

### ISSUE THREAD

**Issue by otaviokf** [glpi-project/glpi#4064]
Hi!

I've set up due date progression colors on General Setup, but it's not working properly on Tickets panel, it goes right from blank to pink (breached SLA). It's supposed 'Time to Own'/'Time to Resolve' background color to be displayed as configured or did i get it wrong?

![glpi_duedateprogression](https://user-images.githubusercontent.com/38987923/40501144-61baaa60-5f5d-11e8-8efb-91cf241a1eec.jpg)

![glpi_ticketspanel](https://user-images.githubusercontent.com/38987923/40501151-6892bcf6-5f5d-11e8-94c2-0c7fe8987a4d.jpg)

On sess_ files (/files/_sessions), glpiduedatexxxxx_xxxx gets the correct values, but no visual effects are detected.

GLPI 9.2.2, Linux CentOS 7.4, Apache 2.4, MySQL 5.5.6 and PHP 5.6.35. All extensions and permissions OK.

Thank you

**Comment by Armin83** [comment]
Maybe the field changed but i don't know. you can use the fields from my screenshot ![tempsnip](https://user-images.githubusercontent.com/19192087/40530959-f9cfe1d8-5ffa-11e8-96f4-8192ab2d975f.png)

**Comment by orthagh** [comment]
As @Armin83 says, due date progression color setup is for progress column, just add it with wrench icon above the list

**Comment by ian-zaque** [comment]
I know its been sometime, but where can I find the configuration to show the progress bar and make it appear on the tickets table?
