### ISSUE TITLE
[9.3 RC1] broken drop downs need refresh

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4068]
* Steps to reproduce (which actions have you made) :
Open one server rooms view
Click Racks
Open one Racks
Click the new list view button in the above section
click server room --> Now you have broken drop downs --> press F5 all is fine

* Expected result :
Normal Drop Down list

* Actual result :
Drop Down List only one object

* URL of the page :
http://demo.glpi-project.org/front/dcroom.form.php?id=2

* Screenshot of the problem (if pertinent) :
![unbenannt](https://user-images.githubusercontent.com/19192087/40535712-2fd42802-600a-11e8-930e-2c078d9eb4da.PNG)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Demo GLPI 25.05.2018

* Workaround
Press F5 
(Firefox & Chrome)

**Comment by trasher** [comment]
I was able to reproduce the issue when you delcared it... But now it works.
Will need to know which data may cause that :/

**Comment by Armin83** [comment]
I can't believe it. You need also a rack without position like in #4069.

**Comment by trasher** [comment]
Indeed, I reproduce when there is no position. I guess the fix for current issue would also fix #4069 (PR coming soon)

**Comment by trasher** [comment]
Fixed; demo has been updated ;)
