### ISSUE TITLE
[9.3 RC1] server room grid view broken

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4069]
Bug below and one wish. There is only a small text allowed in grid view. (you can't see more) 
 **wish:** 
IMHO it would be good if we could read 10, 15 or 20 chars of the rack name. (My server room is not so big an perphaps microsoft and amazon with realy big serverrooms don't use glpi ;))

**bug**
* Steps to reproduce (which actions have you made) :
Define a rack without position

* Expected result :
1.  server room grid view normal
2.  grid ~~switch~~ toogle not brocken
3.  Or a message "you don't have set all racks the view is not correct and a little brocken" or something else ;)

* Actual result 
1.  server roomd grid is missing (red)
2.  the grid switch to display a, b,c.... 1,2,3.... don't work (yellow)

* URL of the page :
http://demo.glpi-project.org/front/dcroom.form.php?id=2

* Screenshot of the problem (if pertinent) :
![inked1_li](https://user-images.githubusercontent.com/19192087/40537757-036d2ede-6010-11e8-83d7-ef923b267a57.jpg)

![tempsnip2](https://user-images.githubusercontent.com/19192087/40537347-f9157a96-600e-11e8-87dd-1045e5b2885b.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
demo glpi 25.05.2018

**Comment by orthagh** [comment]
For grid display, did you check the toggle above it:
![image](https://user-images.githubusercontent.com/418844/40538781-ee300aa2-6012-11e8-80b1-0cdb89fe4737.png)

**Comment by orthagh** [comment]
> IMHO it would be good if we could read 10, 15 or 20 chars of the rack name. (My server room is not so big an perphaps microsoft and amazon with realy big serverrooms don't use glpi ;))

Our customer who initially order this feature have a room of 40+ racks.
I don't know so.

**Comment by Armin83** [comment]
Yes and No - I think grid means the lines. the lines are always displayed.

rack position set on all assigned racks
![1](https://user-images.githubusercontent.com/19192087/40541053-993ae46a-601a-11e8-9db8-ff2653bb2aa4.PNG)
![2unbenannt](https://user-images.githubusercontent.com/19192087/40541068-a2f221a8-601a-11e8-8019-5d81f26a0a8f.PNG)

if the rack position is not set on a assigned rack
![3unbenannt](https://user-images.githubusercontent.com/19192087/40541086-adf42ca4-601a-11e8-8f8b-a3e12a9cf4e6.PNG)
![4unbenannt](https://user-images.githubusercontent.com/19192087/40541092-b053eb06-601a-11e8-9b92-3ffe8226f996.PNG)

**I have no cleared the rack position. the rack position is now not set.** the bug is active.

**Comment by trasher** [comment]
Duplicates #4068 ;)
