### ISSUE TITLE
Improvement: Login page "Lost password" - make link editable.

### ISSUE THREAD

**Issue by Stoatwblr** [glpi-project/glpi#4075]
At the moment the "forgotten password?" link is to an "enter your email address" page.

On our site we change that to a knowledgebase link telling users to use an anonymous form (linked from this page) or to phone the support desk extension for help.

Of course, every time we update GLPI, that change gets overwritten....

It would be nice to have the link definable as a configuration item, so that sites with different policies can do things differently from the current default method without needing to "jump through hoops" every time they update GLPI.

**Comment by trasher** [comment]
Please open a request or upvote existing one on the [suggestion website](http://suggest.glpi-project.org).
