### ISSUE TITLE
Some CSS issues in High Contrast mode

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#4076]
Hello ,
while enabling High Contrast under general setting , some part of the Create ticket , user add etc the lay out breaks , please refer to the below images
this happens on GLPI 9.2.x and 9.3 Dev.

![image](https://user-images.githubusercontent.com/22425503/40601344-dcecf098-6265-11e8-9368-6e82d7602b15.png)

![image](https://user-images.githubusercontent.com/22425503/40601391-0a2c97de-6266-11e8-8629-6cc7f698bd05.png)

![image](https://user-images.githubusercontent.com/22425503/40601676-251ee6f4-6267-11e8-8dd7-97f17cc1e8e5.png)

**Comment by cedric-anne** [comment]
Fixed by #4143.

**Comment by roshanroche** [comment]
Hi @cedric-anne ,
i checked with Glpi 9.3 RC2 , see the following SS there is one border incomplete under tickets.
![image](https://user-images.githubusercontent.com/22425503/41282846-244d31f0-6e46-11e8-8647-e7bc11a77d2d.png)

**Comment by trasher** [comment]
See #4208
