### ISSUE TITLE
Web access issue

### ISSUE THREAD

**Issue by NightSharp** [glpi-project/glpi#4077]
My environment is
UbuntuKylin-18.04+Nginx+php7.2+MariaDB

I have set the whole glpi directory and its content to www-data:www-data

During "Checking of the compatibility of your environment with the execution of GLPI" Step,
All is well except "Web access to files directory is protected"
It always display the warning below:
"Web access to the files directory should not be allowed"
"Check the .htaccess file and the web server configuration"

How can I remove the warning?

**Comment by trasher** [comment]
Just follow the recommandation, and check your webserver configuration. You have to tell nginx the files directory must not be available. It's a nginx question, not a GLPI one.
