### ISSUE TITLE
[9.2.3] Ticket creator (again)

### ISSUE THREAD

**Issue by boscorelly** [glpi-project/glpi#4082]
Hi,

as i have wrote in this ticket, #4015 we are experiencing issues with the new behavior.

Is there a way to change it without modifying the code directly ? It's not possible directly on ticket page at the creation

**Comment by trasher** [comment]
Again, no.

**Comment by boscorelly** [comment]
Is it possible to at least think about it ?

It's a very big problem for us !

We want the requester to be the redactor of the  request..
