### ISSUE TITLE
PHPMailer configuration issue?

### ISSUE THREAD

**Issue by argaar** [glpi-project/glpi#4088]
* Steps to reproduce (which actions have you made) :
had a configured smtp server that offers TLS but you want to use port 25 and NO ssl/tls

* Expected result :
send mail ignoring tls

* Actual result :
smtp (phpmailer) fails to send

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Apart the issue template, the problem is probably due the fact that in "glpimailer.class.php" TLS and/or SSL is enabled based on user configuration, unfortunately the PHPMailer version, shipped with Glpi 9.2.3 had a small hint in "class.phpmailer.php" on line 1675-1682 suggesting that if the server support STARTTLS in EHLO reply, it would use the TLS encryption tot court.
If I comment out the line 1681 ($tls = true; to //$tls = true;) everything is working fine
Also, inspecting the glpi debug (mail-debug.log) you can see that PHPMailer assumes you want TLS even if SMTP_MODE is 1 in DB

#########From define.php
//Mail send methods
define("MAIL_MAIL", 0);
define("MAIL_SMTP", 1);
define("MAIL_SMTPSSL", 2);
define("MAIL_SMTPTLS", 3);

#########From mail-debug.log
3 - Connection: opening to my.smtp.server:25, timeout=300, options=array (
)2018-05-29 15:30:10 [2@glpi]
3 - Connection: opened2018-05-29 15:30:10 [2@glpi]
2 - SERVER -> CLIENT: 220 my.smtp.server Microsoft ESMTP MAIL Service, Version: 6.0.3790.4675 ready at  Tue, 29 May 2018 15:30:09 +0200
2018-05-29 15:30:10 [2@glpi]
1 - CLIENT -> SERVER: EHLO my.glpi.server
2018-05-29 15:30:10 [2@glpi]
2 - SERVER -> CLIENT: 250-my.smtp.server Hello [172.16.123.234]
250-TURN
250-SIZE
250-ETRN
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-8bitmime
250-BINARYMIME
250-CHUNKING
250-VRFY
250-TLS
250-STARTTLS             <<<---------------
250-X-EXPS GSSAPI NTLM LOGIN
250-X-EXPS=LOGIN
250-AUTH GSSAPI NTLM LOGIN
250-AUTH=LOGIN
250-X-LINK2STATE
250-XEXCH50
250 OK
2018-05-29 15:30:10 [2@glpi]
1 - CLIENT -> SERVER: STARTTLS    <<<--------------------
2018-05-29 15:30:10 [2@glpi]
2 - SERVER -> CLIENT: 220 2.0.0 SMTP server ready
2018-05-29 15:30:10 [2@glpi]
3 - SMTP Error: Could not connect to SMTP host.2018-05-29 15:30:10 [2@glpi]
1 - SMTP NOTICE: EOF caught while checking if connected2018-05-29 15:30:10 [2@glpi]
3 - Connection: closed2018-05-29 15:30:10 [2@glpi]
3 - SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by trasher** [comment]
Since this is provided from a 3rd party library, we are not going to change that.

On next PHPMailer version (that will be shipped in GLPI 9.3), there is a kind of parameter that would permit to disable the automatic detection.
But I do not see why we would want to disable automatic detection; this would lower security for instances that does not have (re)configured their GLPI (for example if the mai server has gain the capacity after GLPI has been setup).

**Comment by argaar** [comment]
Of course lower the security would not be advisable, but if I configure GLPI (from the dropdown) to use only SMTP I would expect that, no matter what, it'll use just plain smtp. maybe a simple tootip like "Attention: If your server supports STARTTLS, our mail library (PHPMailer) will use it even if you choose only SMTP" would be enough.
Glad to know that in the next release it'll handle this case!
