### ISSUE TITLE
[Glpi 9.2.3] ticket associated element wrong dropdown list

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#4090]
Hi in a ticket if I want to add a conneted element like human resources in the dropdown list only the name is displayed (no first name).
If an human resource is added the cursor on the name display popup with the name + first name of the resource manager. Coul you check this two problemes

**Comment by orthagh** [comment]
Hello @FRANCOIS50 

Please create an issue in the plugin project (resource). -> https://github.com/InfotelGLPI/resources/issues

We're not the same team here and we can't help you for this plugin projet.

Regards
