### ISSUE TITLE
User right bug read/write ticket author

### ISSUE THREAD

**Issue by mvestrotech** [glpi-project/glpi#4099]
From version 9.1.7 to version 9.2.2 the rights differ with the same configuration of rights 

### Example : 

Test GLPI 9.1.7

- Creation of a ticket by techA
    - Ticket assigned to techA
- techA has the right to modify its ticket but not techB
- techB has the right to change the status of the ticket

Test GLPI 9.2.2

 - Creation of a ticket by techA
    - Ticket assigned to techA
- techA and techB do not have the right to change the ticket

![priorite](https://user-images.githubusercontent.com/23355435/40714693-a482b3b0-6403-11e8-888c-981bdcee6c45.png)

**Comment by trasher** [comment]
Plase test with latest stable release, and if problem still occurs, with latest 9.2 nightly.

**Comment by ng161621** [comment]
Test perform

- 9.2 : OK
- 9.2.3 : KO

**Comment by trasher** [comment]
@ng161621 could you please test with patch provided in #4103?

**Comment by ng161621** [comment]
@trasher the patch corrects the error. Thank you

**Comment by orthagh** [comment]
> internal ref: 13925
