### ISSUE TITLE
pas d'élément visible pour création de ticket pour les postonly

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#410]
J'ai réaliser un git pull hier soir depuis mon postonly ne peuvent pas faire de tickets car je n'ai que GENERAL qui apparait
![capture](https://cloud.githubusercontent.com/assets/6815687/12641331/511fce8c-c5af-11e5-8e94-852acebff992.PNG)

**Comment by Sismic** [comment]
aucune erruer dans le php-error ou sql-error
le git pull a été fait sur la branche master

voici le debug

SELECT COUNT(`id`) AS 'total'
FROM `glpi_ticketvalidations`
WHERE `status` = '2' AND `users_id_validate` = '26'	0.000	 
2	SELECT *
FROM `glpi_useremails`
WHERE `users_id` = '26' AND `is_default` = '1'	0.000	 
3	SELECT `glpi_entities`.*
FROM `glpi_entities`
WHERE `glpi_entities`.`id` = '0' LIMIT 1	0.000	 
4	SELECT `glpi_entities`.*
FROM `glpi_entities`
WHERE `glpi_entities`.`id` = '0' LIMIT 1	0.000	 
5	SHOW COLUMNS
FROM `glpi_entities`	0.001	 
6	SELECT DISTINCT `glpi_groups_users`.`groups_id`
FROM `glpi_groups_users`
INNER JOIN `glpi_groups` ON (`glpi_groups_users`.`groups_id` = `glpi_groups`.`id`)
WHERE `glpi_groups_users`.`users_id` = '26' AND `glpi_groups_users`.`is_userdelegate` = '1' AND ( `glpi_groups`.`entities_id` = '0' ) 	0.000	 
7	SELECT *
FROM `glpi_requesttypes`
WHERE is_helpdesk_default=1	0.000	 
8	SELECT `glpi_tickettemplates`.*
FROM `glpi_tickettemplates`
WHERE `glpi_tickettemplates`.`id` = '1' LIMIT 1	0.000	 
9	SELECT *
FROM `glpi_tickettemplatehiddenfields`
WHERE `tickettemplates_id` = '1'
ORDER BY `id`	0.000	 
10	SELECT *
FROM `glpi_tickettemplatemandatoryfields`
WHERE `tickettemplates_id` = '1'
ORDER BY `id`	0.000	 
11	SELECT *
FROM `glpi_tickettemplatepredefinedfields`
WHERE `tickettemplates_id` = '1'
ORDER BY `id`	0.000	 
12	SELECT `glpi_entities`.`completename`, '' AS transname, `glpi_entities`.`comment`, '' AS transcomment
FROM `glpi_entities`
WHERE `glpi_entities`.`id` = '0'	0.000	 
13	SELECT COUNT(`glpi_notifications`.`id`)
FROM `glpi_notifications`
INNER JOIN `glpi_notificationtargets` ON (`glpi_notifications`.`id` = `glpi_notificationtargets`.`notifications_id`)
WHERE `glpi_notifications`.`itemtype` = 'Ticket' AND `glpi_notifications`.`mode` = 'mail' AND `glpi_notificationtargets`.`type` = '1' AND `glpi_notificationtargets`.`items_id` = '3'	0.000	 
14	SELECT `glpi_users`.*
FROM `glpi_users`
WHERE `glpi_users`.`id` = '26' LIMIT 1	0.000	 
15	SELECT *
FROM `glpi_useremails`
WHERE `users_id` = '26' AND `is_default` = '1'	0.000	 
16	SELECT *
FROM `glpi_useremails`
WHERE `users_id` = '26'	0.000	 
17	SELECT *
FROM `glpi_items_tickets`
WHERE `tickets_id` = 0 	0.000	 
18	SELECT `glpi_groups_users`.`groups_id`, `glpi_groups`.`name`
FROM `glpi_groups_users`
LEFT JOIN `glpi_groups` ON (`glpi_groups`.`id` = `glpi_groups_users`.`groups_id`)
WHERE `glpi_groups_users`.`users_id` = '26' AND ( `glpi_groups`.`entities_id` = '0' ) 	0.000	 
19	SHOW COLUMNS
FROM `glpi_groups`	0.001	 
20	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '1'	0.000	 
21	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '6'	0.000	 
22	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '19'	0.000	 
23	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '29'	0.000	 
24	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '51'	0.000	 
25	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '57'	0.000	 
26	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '61'	0.000	 
27	SELECT `ancestors_cache`, `groups_id`
FROM `glpi_groups`
WHERE `id` = '88'	0.000	 
28	SELECT *
FROM `glpi_items_tickets`
WHERE `tickets_id` = 0 	0.000

**Comment by yllen** [comment]
Vérifier dans votre profil Post-Only que les types associables à un ticket sont toujours définis.

**Comment by yllen** [comment]
Test faits en 90 et 91 et j'ai bien les types définis dans mon profil

**Comment by orthagh** [comment]
C'est surement lié à l'utilisation du master en production (vu ensemble sur canal irc).
Je clos ce ticket pour le moment.
N'hésitez pas à réouvrir si c'est toujours d'actualité
