### ISSUE TITLE
[GLPI9.2.3] attached items not visible in the tickets list

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#4101]
GLPI 9.2.3
If I had more than one item in a ticket these are not visible in the tickets list
Attached items -->
![2018-05-30_15h37_28](https://user-images.githubusercontent.com/12511115/40723697-f657e93e-640e-11e8-8496-0a1e76ac0f0a.png)

not visible in the tickets list
![2018-05-30_15h36_27](https://user-images.githubusercontent.com/12511115/40723712-0229d506-640f-11e8-974e-40632c5e33fe.png)

Could you check this problem?

**Comment by trasher** [comment]
Just tested on 9.3; cannot reproduce. Please try with latest 9.2 nightly.

**Comment by trasher** [comment]
9.2 nightly is available at: https://forge.glpi-project.org/tarballs/

**Comment by orthagh** [comment]
@FRANCOIS50 
Both me and @trasher tested without replicate your issue.

Could you checks logs and also provide a detailed list of step you did ?

**Comment by FRANCOIS50** [comment]
HI I made some tests and noticed that the problem is only if I open a ticket via un formular.
I will open a new issue in this plugin github
