### ISSUE TITLE
[GLPI9.3.2] Item added in a ticket is note erasable

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#4106]
In a standard ticket, if I add a item, this one can not be deleted. (no 'X' at the end of the line)

![2018-05-30_21h20_18](https://user-images.githubusercontent.com/12511115/40742647-b0cd0d06-643e-11e8-97b2-854181b5d4ff.png)

 I have to add a new one to be able to erase one, (one 'X' at the end of each line)

![2018-05-30_21h23_26](https://user-images.githubusercontent.com/12511115/40742741-f626fed4-643e-11e8-916a-19ddf8a7ce24.png)

Could you check this problem.

**Comment by cedric-anne** [comment]
Hi,

Your ticket uses a template that defines the `Associated elements` field as mandatory. There is a business rule that prevent deletion of an item if it is the unique one when field is mandatory. If you have two elements, the deletion button will disapear if you remove one of them.

Regards

**Comment by FRANCOIS50** [comment]
Thanks for your fast answer
