### ISSUE TITLE
BUG : right user doesn't stop the Time To Own

### ISSUE THREAD

**Issue by mvestrotech** [glpi-project/glpi#4113]
When creating a ticket with SLA and a direct assignement the TTO doesn't stop.

Constraint : the user doens't have the right to update the ticket.

Test : 9.2.2 & 9.2.3

![sans titre](https://user-images.githubusercontent.com/23355435/40842878-8a21aa8c-65af-11e8-888d-483e65d07720.png)

![sans titre](https://user-images.githubusercontent.com/23355435/40842968-c49543fe-65af-11e8-8cd1-901facc9c548.png)

**Comment by Armin83** [comment]
Only the colour ? (I have this without autoassign from one technician. i use only autoassign technician group.) the value is correct but the colour of the field in the ticket table is red

**Comment by mvestrotech** [comment]
This problem is due to a bad configuration of the right.
