### ISSUE TITLE
change translation in the menu of the standard interface 

### ISSUE THREAD

**Issue by Lfrjreyes** [glpi-project/glpi#4114]
* Steps to reproduce (which actions have you made) :
Change the submenu names in the standard interface

* Expected result :
in the support menu where it says tickets and create tickets I need to translate to cases and create cases

* Actual result :
currently draws the menu from a vector and does not allow me to do the translation

* URL of the page :

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/37385312/40846845-5b522b98-6580-11e8-8f8a-6d2d22171167.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

**Comment by trasher** [comment]
Translations are handled on transifex
