### ISSUE TITLE
take into account time summary display in ticket timeline

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4116]
* Steps to reproduce (which actions have you made) :
take into account question.
IMHO: I think in this screen the "bottom" part should be "take into account time" 32 seonds and not "take into account" 32 seconds

* Screenshot of the problem (if pertinent) :
![unbenannt](https://user-images.githubusercontent.com/19192087/40848578-f0ecf28e-65bf-11e8-8949-b5ab2d72bebe.PNG)

**Comment by trasher** [comment]
Since this is in a block named "Times", I do no think this is really relevant.
