### ISSUE TITLE
textarea:focus doesnt work since 9.2.x even in 9.3

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#4118]
Hello ,
the CSS value textarea:focus, input:focus {
   border: 1px solid #5897fb; doesnt seems to be working on some fields in 9.2.x and completely not working in 9.3 dev.
9.1.x it works fine. following are some screen shots.

![image](https://user-images.githubusercontent.com/22425503/40903006-f99cc656-67e6-11e8-8feb-cee733b806b3.png)

![image](https://user-images.githubusercontent.com/22425503/40903113-644bce16-67e7-11e8-9020-02303aa7f394.png)
![image](https://user-images.githubusercontent.com/22425503/40903336-1436ff80-67e8-11e8-8cc6-8fe62def38ed.png)
![image](https://user-images.githubusercontent.com/22425503/40903529-ae523f44-67e8-11e8-86ea-64e01af5a606.png)
![image](https://user-images.githubusercontent.com/22425503/40903580-d2f7f10e-67e8-11e8-961a-8c7e8c4fc4fe.png)

**Comment by trasher** [comment]
@roshanroche could you please try with patch provided in #4120?

**Comment by roshanroche** [comment]
Dear @trasher ,
i tested with the patch , styles.css did not make any changes , but same on styles.min.css same changes worked.
