### ISSUE TITLE
Licence - as child of - empty list

### ISSUE THREAD

**Issue by macpacz** [glpi-project/glpi#4124]
------------
* Steps to reproduce (which actions have you made) :
Create first licence A - root entity - child entities: yes
Create second licence B - root entity - child entities: yes - as child of: empty list 

* Expected result :
Create second licence B - root entity - child entities: yes - as child of: show and select licence A 

* Actual result :
empty list - as child of

* URL of the page :
-

* Screenshot of the problem (if pertinent) :
-

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
http://demo.glpi-project.org

**Comment by trasher** [comment]
Software of the license must be the same for two licenses; assuming that, this works on the demo.

**Comment by macpacz** [comment]
thanks for explaining. I understood the function I did differently.
