### ISSUE TITLE
PHP notice on asset page after upgrade from 9.2.2 to 9.2.3

### ISSUE THREAD

**Issue by androidjuergen99** [glpi-project/glpi#4133]
hi there,
just updated my installation from 9.2.2 to 9.2.3
now i get this notice(s) when i load the asset-page "Global"
working in the other asset-groups.

known bug or am i the only one having this issue?

`PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77
PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77
PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77
PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77
PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77
PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77
PHP Notice: Undefined variable: table in /var/www/inc/search.class.php at line 5067
PHP Notice: Uninitialized string offset: 0 in /var/www/inc/toolbox.class.php at line 77`

**Comment by trasher** [comment]
Please provide full stack trace. It should be one of your plugins that cause this notice, please try with all plugins disabled.

**Comment by androidjuergen99** [comment]
i have no enabled plugin on my test-installation.
what do you mean with full stack trace, how and which info should i provide?

**Comment by trasher** [comment]
On error/notices, there is a stack trace, that may be quite long in the logs. The informations you give does not permit to know where the problem came from.
