### ISSUE TITLE
[9.3 & 9.2.X] Cannot delete a document in a ticket / SQL error

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#4141]
Cannot delete a document in a ticket / SQL error

* Steps to reproduce (which actions have you made) :

1. Creating a ticket with a document and a ticket description with the character '

2. In the "Ticket processing" tab, I want to delete the document,  it does not work.

* Actual result :
SQL error : 
```  *** MySQL query error:
  SQL: UPDATE `glpi_tickets`
                       SET `content` = 'Test d'apostrophe' WHERE `id` ='47792'
  Error: Erreur de syntaxe près de 'apostrophe' 
  Backtrace :
  inc\commondbtm.class.php:433                       
  inc\commondbtm.class.php:1231                      CommonDBTM->updateInDB()
  inc\document_item.class.php:208                    CommonDBTM->update()
  inc\commondbtm.class.php:1456                      Document_Item->post_purgeItem()
  front\ticket.form.php:197                          CommonDBTM->delete()
```

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3RC1 & 9.2.X

**Comment by amma35** [comment]
Hi @trasher, 
Always the same SQL error when deleting a document.

**Comment by amma35** [comment]
We made this change to correct the SQL error:
```
diff --git a/inc/document_item.class.php b/inc/document_item.class.php
index 98b50d826..a72adcb87 100644
--- a/inc/document_item.class.php
+++ b/inc/document_item.class.php
@@ -205,7 +205,7 @@ class Document_Item extends CommonDBRelation{
                                                          [$doc->fields['tag']]);
          }
 
-         $ticket->update($input);
+         $ticket->update(Toolbox::addslashes_deep($input));
       }
       parent::post_purgeItem();
    }
```

The line in 9.2/bugfixes : https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/document_item.class.php#L172

**Comment by trasher** [comment]
Not sure this will not cause issues. If `$input` came from a request, data are already escaped.

**Comment by trasher** [comment]
Please open another issue, reopening issues breaks changelog.
