### ISSUE TITLE
Problem with session: "Empty username or password"

### ISSUE THREAD

**Issue by jswytka** [glpi-project/glpi#4145]
Hi guys.

I have the same problem reported for @dilona at 14 Sep 2017  issue #2745 however in version 9.2.2.

When log out and log in again appears "Empty username or password" (login and password saved).

1) Log in with the saved username and password (When you first start the browser).
![imagem 1](https://user-images.githubusercontent.com/21204053/41134409-99a8a350-6aa2-11e8-8ff8-21c6e513920b.png)

2) Logout -> redirect to /index.php?noAUTO=1
3) Username/password is still saved. Click "Submit"
4) Appear "Empty username or password". Then click "Log in again"
5) Go to /index.php?noAUTO=1 -> Click "Submit" -> Appear "Empty username or password". It repeats permanently.
6) If refresh the page (/index.php?noAUTO=1) it works correct.

**Comment by trasher** [comment]
Cannot reproduce. Sounds like a browser cache issue. What is the browser?

**Comment by jswytka** [comment]
@trasher chrome, but i tested in others machines and browser like firefox. same problem.
