### ISSUE TITLE
TCPDF ERROR: Some data has already been output, can't send PDF file

### ISSUE THREAD

**Issue by FI5CHER** [glpi-project/glpi#4147]
Hi. 

After update to 9.2 with new remi php i got the following error when i tried to save something as pdf

"TCPDF ERROR: Some data has already been output, can't send PDF file"

No PDF was created, just this error message. 

found the solution here 
https://stackoverflow.com/questions/16011050/tcpdf-error-some-data-has-already-been-output-cant-send-pdf-file

with a grep i found 
```
grep -r -l -i "pdf->output" 
inc/search.class.php
```
... and i added a line with "ob_end_clean();" before the lines with "pdf->output"

after adding this the problem was gone .
```
diff /root/glpi/inc/search.class.php inc/search.class.php
5978a5979
>             ob_end_clean();

```

PS: just as an info ... the same i did with the glpi-pdf plugin. Maybe you can forward this to "remi" and "yllen" ... because this glpi-pdf plugin is not on github ... :-( 

```
diff /root/pdf/inc/common.class.php plugins/pdf/inc/common.class.php
378a379
>          ob_end_clean();
666c667
< }
\ No newline at end of file
---
> }

 diff /root/pdf/inc/simplepdf.class.php plugins/pdf/inc/simplepdf.class.php 
 139a140
 >       ob_end_clean();
 153a155
 >          ob_end_clean();
 155a158
 >       ob_end_clean();
```

**Comment by trasher** [comment]
Try with debug mod disabled.

**Comment by FI5CHER** [comment]
debug was disabled. i tried with debug mode enabled as well ... same behavior . 
Interesting was, that pdf creation was working from the dashboard plugin.
i seems that ob_end_clean makes the pdf printing more stable in case that there is something in the buffer ...

**Comment by FI5CHER** [comment]
same result. 
the system is centos 7 with remi 7.2
with remi 5.6 the problem was also there 
the productive system is more or less the same with c7 , glpi 9.1 and php 5.4 . there i dont have the problem.

**Comment by trasher** [comment]
I cannot reproduce on 9.3 (tested on demo website and local).

**Comment by FI5CHER** [comment]
hi "trasher"

i don't want you to reproduce this error and i don't need any help. 

i just recommend to add an 

**ob_end_clean();** 

before every  

**$pdf->Output('glpi.pdf', 'I');** 

in any file where tcpdf is used by glpi , thats all. 

ob_end_clean cleans the output buffer . So if some messages are in this buffer , tcpdf creates this error message ... 
and to avoid this erros it's recommendet tp use

**ob_end_clean(); $pdf->Output('glpi.pdf', 'I');**

instead of a simple 

$pdf->Output('glpi.pdf', 'I');

see  http://php.net/manual/en/function.ob-end-clean.php  and https://stackoverflow.com/questions/16011050/tcpdf-error-some-data-has-already-been-output-cant-send-pdf-file 

for some reasons under centos 7 and glpi 9.2 it's not working without ob_end_clean .

**Comment by Gambware** [comment]
Thats work for me ! Thanks
