### ISSUE TITLE
Ticket opening date is wrong

### ISSUE THREAD

**Issue by gormux** [glpi-project/glpi#4150]
Hello,

There is a problem on ticket creation.
The opening date is when the form to create the ticket has been opened, not when it is saved.

In SLA calculations, that means the SLA starts when the client clicks on Create ticket, and not when the ticket is really opened.
We've had cases (with short SLAs) where the client saves the ticket AFTER the SLA ends, because he took some time to write the ticket.

We have this problem on 9.1.6, but I reproduced on the demo instance with 9.3-dev.

-----------
* Steps to reproduce (which actions have you made) :
Create a new ticket, wait for some time, save the ticket

* Expected result :
The opening date of the ticket should be when the ticket is saved

* Actual result :
The opening date is when the form to create the ticket is shown

**Comment by cedric-anne** [comment]
Hi,

A small change seems to fix this behaviour, but I am not confident with it as I do not know well all the logic that can be based on this field.

Here is the diff for current 9.2/bugfixes branch.

```diff
diff --git a/inc/ticket.class.php b/inc/ticket.class.php
index 1772aa495..257e08f59 100644
--- a/inc/ticket.class.php
+++ b/inc/ticket.class.php
@@ -1754,6 +1754,11 @@ class Ticket extends CommonITILObject {
       // Standard clean datas
       $input =  parent::prepareInputForAdd($input);
 
+      // default opening date if not set
+      if (empty($input['date'])) {
+         $input['date'] = $_SESSION["glpi_currenttime"];
+      }
+
       // Do not check mandatory on auto import (mailgates)
       if (!isset($input['_auto_import'])) {
          if (isset($input['_tickettemplates_id']) && $input['_tickettemplates_id']) {
@@ -4258,7 +4263,7 @@ class Ticket extends CommonITILObject {
                'priority'                  => self::computePriority(3, 3),
                'requesttypes_id'           => $requesttype,
                'actiontime'                => 0,
-               'date'                      => $_SESSION["glpi_currenttime"],
+               'date'                      => '',
                'entities_id'               => $entity,
                'status'                    => self::INCOMING,
                'followup'                  => [],
```

Regards

**Comment by trasher** [comment]
Ths will be fixed once we'll be sure it does not affects anything else... We do not want to introduce another issue that would have mor impact trying to fix this "quickly".
