### ISSUE TITLE
[GLPI 9.2.3] POP3 connection broken in response (errflg=2)

### ISSUE THREAD

**Issue by DimmoK** [glpi-project/glpi#4151]
Hello.

Sorry for my English.

I have a problem.

Autoreceiver don't work.

* Steps to reproduce (which actions have you made) :

## My config:

**Receiver:**

Name (Email address)     glpi@test.ru
Active    Yes
Server    mail.test.ru

**Connection options:**

Incoming mail folder (optional, often INBOX)    INBOX
Port (optional)    
Connection string    {mail.test.ru/pop/novalidate-cert/tls/debug}INBOX
Login    glpi@test.ru
Password     Clear
Use Kerberos authentication    NO
Maximum size of each file imported by the mails receiver    5MB
Use mail date, instead of collect one    NO

* Expected result :
create ticket

* Actual result :
2018-06-08 13:44:02 [@gr-services]
  *** PHP Warning(2): imap_open(): Couldn't open stream {mail.test.ru/pop/novalidate-cert/tls}INBOX
  Backtrace :
  :
  inc/mailcollector.class.php:1109                   imap_open()
  inc/mailcollector.class.php:519                    MailCollector->connect()
  inc/mailcollector.class.php:1660                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:832                         call_user_func()
  front/cron.php:87                                  CronTask::launch()

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
<details><summary>**GLPI SERVER INFO**</summary><p>
Information about system installation and configuration
--
[code]   GLPI 9.2.3-git-9.2/bugfixes-b117651 ( => /var/www/glpi) Installation mode: GIT

Operating system: Linux gr-services 4.4.0-127-generic #153~14.04.1-Ubuntu SMP Sat May 19 14:00:03 UTC 2018 x86_64 PHP 5.6.36-1+ubuntu14.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, XCache, XCache Cacher, 	XCache Coverager, XCache Optimizer, Zend OPcache, apache2handler, bcmath, calendar, ctype, curl, date, dom, ereg, exif, 	fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mbstring, mcrypt, memcache, 	memcached, mhash, msgpack, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at glpi.test.ru Port 80) 	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.42 Server Software: (Ubuntu) 	Server Version: 5.5.60-0ubuntu0.14.04.1 	Server SQL Mode:  	Parameters: usrglpi@localhost/gr_glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed APCu extension is not present /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

Server: 'srdc02', Port: '389', BaseDN: 'OU=Test,DC=internal,DC=test,DC=ru', Connection filter: none, RootDN: 		'glpi@internal', Use TLS: none

Not active

Way of sending emails: PHP

Name: 'glpi@test.ru' Active: Yes 	Server: '{mail.test.ru/pop/novalidate-cert/tls/debug}INBOX' Login: 'glpi' Password: Yes

environment          Name: Environment                    Version: 2.1.0      State: Not installed 	formvalidation       Name: Form Validation                Version: 0.2.3      State: Not installed 	fusioninventory      Name: FusionInventory                Version: 9.2+2.0-RC1 State: Enabled 	itilcategorygroups   Name: ItilCategory Groups            Version: 2.0.1      State: Not installed 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.7      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.4.0      State: Not installed 	tag                  Name: Tag Management                 Version: 2.1.0      State: Not installed 	browsernotification  Name: Браузерные уведомления Version: 1.1.9      State: Enabled 	domains              Name: Домены                         Version: 1.9.0      State: New 	fields               Name: Дополнительные поля    Version: 1.7.0      State: Not installed 	racks                Name: Конфигурация стойки    Version: 1.8.0      State: Enabled 	reports              Name: Отчет                          Version: 1.11.2     State: Not installed 	behaviors            Name: Поведения                      Version: 2.0.2      State: Enabled 	mreporting           Name: Подробные отчеты          Version: 1.4.0      State: Enabled 	archires             Name: Сетевые архитектуры    Version: 2.5.1      State: Not installed 	news                 Name: Уведомления                   Version: 1.3.4      State: Enabled
[/code]

No slave DB
GLPI_DB_OK
GLPI_TABLES_OK
GLPI_SESSION_DIR_OK
Check LDAP servers: gr-ad_OK
No IMAP server
No CAS server
Check mail collectors: glpi@test.ru_PROBLEM
Crontasks_OK

GLPI_PROBLEM
Collapsible until here.
</p></details>

This configuration worked is very well!
What is the problem?
Thank's.

**Comment by trasher** [comment]
`Couldn't open stream` indicate something wrong with your receiver configuration. Double chck your config, and try to see error log on mail server side.

**Comment by DimmoK** [comment]
> Double chck your config, and try to see error log on mail server side.
I'm sorry, but my config worked before it without any problem. I do not modified that.

We use MS Exchange 2013.

**Comment by trasher** [comment]
SO this is an issue on mail server side. Contact your administrator.
