### ISSUE TITLE
Problem with massiveaction in 'automatic action' list

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#417]
Hello,
With GLPI 0.91 PHP 5.6.17 (I tried also with PHP 7.0.2 and I got the same).

When trying to do a massive action on 'Automatic action' list, you get an empty dialog when you select 'update' in the list of possible actions:

![image](https://cloud.githubusercontent.com/assets/7569958/12719186/ea0f47fc-c8f3-11e5-92e1-e13cce458979.png)

There is no error nowhere in logs.
regards,
Tomolimo

**Comment by orthagh** [comment]
No javascript errors in dev tools (F12) ?

Do you see some XHR requests triggering after selection of update value ?

**Comment by tomolimo** [comment]
Hello,
There is no javascript error!
And if I capture network traffic, I got in response body to the ajax/dropdownMassiveAction.php:

`<table width='100%'><tr></tr><tr></tr></table><span id='update_next_step634455149'>&nbsp;</span>`

I think something is missing here :)

regards,
Tomolimo

**Comment by tomolimo** [comment]
I found the root cause for this, I'll PR it
