### ISSUE TITLE
SLA OLA Time To Own Execution Issue

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#4170]
Hi,
Glpi 9.3RC2 i create a Service Level SLM under it i create SLA TTO with Time to own and execution time as 10 Mins. under Execution i select execution as time to own (10 mins)   criteria technician does not exist and action automatic send SLA reminder. Result should be by 10th min automatic reminder should be sent. but in actual scenario no reminder is sent. after testing with different criteria and actions i found that under Time to own no execution really happens.  but under time to resolve all executions happen in sequence. 
i checked this issue on 9.2.3 with same result. 
this issue exists even on 9.1.x 
i will attach screenshots if required.

**Comment by roshanroche** [comment]
Please find the following SS for the steps and actual results ,

i create SLA under SLM , name it Test TTO
![image](https://user-images.githubusercontent.com/22425503/41333722-dfcc6b3c-6ef3-11e8-9aa2-e3495c69fceb.png)

Type of SLA is Time to Own and Maximum time is 5 minutes.
![image](https://user-images.githubusercontent.com/22425503/41333799-214f9ee4-6ef4-11e8-96ed-f2ef06f92297.png)

i create Escalation level under this SLA named TTO1
![image](https://user-images.githubusercontent.com/22425503/41333873-6f80c2d2-6ef4-11e8-89d2-20b2f8008763.png)

with Criteria conditions as follows

![image](https://user-images.githubusercontent.com/22425503/41333922-9ab2fe8e-6ef4-11e8-92fc-bc2a95856b4b.png)

and action for this criteria as follows

![image](https://user-images.githubusercontent.com/22425503/41333962-bdef87be-6ef4-11e8-89f8-fa306249aada.png)

Similarly i create another Escalation level under SLA Test TTO with esclation time as +10 minutes with the same criteria and action.
![image](https://user-images.githubusercontent.com/22425503/41334032-12431420-6ef5-11e8-8519-1a93c302b911.png)

I create a ticket with Test TTO SLA applied to it
![image](https://user-images.githubusercontent.com/22425503/41334099-58bbeb48-6ef5-11e8-9634-f7a257697612.png)
on the tool tip it shows the escalation info which is perfect, now see the below screen shot when the escalation time is reached it should have attached the next escalation level that of +10 mins but as soon as the 1st escalation level reached , it becomes blank.
![image](https://user-images.githubusercontent.com/22425503/41334190-be30aec8-6ef5-11e8-9d5f-cdcafbf9faeb.png)
Under Automatic actions SLA fires the job at the escalation time , but no action happens ( in this case i should have recieved the SLA reminder. but no reminder is sent )
![image](https://user-images.githubusercontent.com/22425503/41334266-09814a0e-6ef6-11e8-99ed-3a262c0b0724.png).
i have tried with many different actions like change Type of ticket from incident to Request , Change impact etc. but no action happens during the escalation time and after the 1st escalation Time to own doesnt process any attached additional escalations. 

![image](https://user-images.githubusercontent.com/22425503/41334364-6fce381c-6ef6-11e8-93cd-2c1301480371.png)

Same steps above when i use for SLA Time to resolve works perfectly.

**Comment by roshanroche** [comment]
Hi ,
after few more tests , it seems like if the ticket is assigned to a group ( Processing ) ( criteria in this case is Technician group exists , technician does not exist ) this above said behavior happens in Time to own scenario. 

if the ticket status is New then all executions happen.

so time to own basically works only if the ticket status is new? time to own also should work when a ticket is assigned to a group and technicians in the group don't self assign the tickets within the time to own time frame.

**Comment by orthagh** [comment]
Hello @roshanroche, according to https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/slalevel_ticket.class.php?utf8=%E2%9C%93#L212

Next level will be applied only if the ticket is not "Taken into account".

So
> so time to own basically works only if the ticket status is new?

Almost yes.
In fact, the tto mechanism works with the stat name "take into account" you could find into statistics tabs on ticket.
If set ( on first ticket modification, like attribution, category change, etc), the ticket is considered as **viewed** and so, "taken into account", and the tto sla end.

**Comment by roshanroche** [comment]
@orthagh ,
I completely agree with u on that parameter, as when the ticket is assigned to a group via business rule , and a group has more than 1 user. Now the ticket remain in unassigned state logically as it’s not assigned to a tech, and untill it’s assigned to a technician manually it remains in unassigned state ( but system assumes it as in assigned state as its assigned to a group ) . Nevertheless thanks for ur efforts.

**Comment by orthagh** [comment]
I know it can be pretty confusing when using sla with automatic business rules.
We can't do small fixes on this part.

I think a possible resolution is to add a new status name "pre-assigned" (for example) which doesn't fill "takeintoaccount_stat".
It's more a feature suggestion in this case, the current behaviors is "intended".

I close this issue, but you add an entry to suggest.glpi-project.org to track your need.

Regards

**Comment by iowatech80** [comment]
This is still an issue to the this day and the problem stems from group assignments satisfying the "take into account" criteria.  If you auto-assign groups based on category then TTO is satisfied immediately on ticket creation.  This is not good because it will not notify the technicians when TTO passes.
