### ISSUE TITLE
[9.3 RC2] search bar empty

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4171]
I have no sql-errors, php-errors but i don't know how to enable sctrict mode http://forum.glpi-project.org/viewtopic.php?id=163231

* Steps to reproduce (which actions have you made) :
Open search bar

* Expected result :
get favorite searches

* Actual result :
get only the spinner (browser dev tool last object is http://192.168.1.108/pics/spinner.48.gif)

* URL of the page :
? / from browser dev tool http://192.168.1.108/ajax/savedsearch.php?action=show

* Screenshot of the problem (if pertinent) :
![2018-06-12 21_44_06-window](https://user-images.githubusercontent.com/19192087/41313256-c5715ec4-6e89-11e8-8d6a-6c111fca3f8a.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Information about system installation and configuration
--

> 
> [code]   GLPI 9.3-dev ( => /var/www/glpi) Installation mode: TARBALL
> 
> Operating system: Linux glpidev 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 PHP 7.2.5-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, session, 	shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zlib) Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at 192.168.1.108 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 Server Software: Ubuntu 18.04 	Server Version: 10.1.29-MariaDB-6 	Server SQL Mode:  	Parameters: glpidbuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (10.1.29) - Perfect! /etc/glpi/ : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.
> 
> htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
> 
> Not active
> 
> Way of sending emails: PHP
> [/code]
> 
>

**Comment by trasher** [comment]
Looks like a JS issue, ajax call seems to answer as expected

**Comment by ladenree76000** [comment]
i got the same behaviour  (9.3 RC 2 upgraded from 9.2.3)
Maria db 10
php7
Firefox
Ubuntu 16.04

**Comment by orthagh** [comment]
@ladenree76000 see https://github.com/glpi-project/glpi/pull/4185/files for the fix
