### ISSUE TITLE
Sometines user's pictures are not synchronized

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#418]
in GLPI 0.91
Sometimes we get no synchronization of the pictures and there is an error in the sql error log.
2016-02-01 15:49:49 [937@ARGLPID20]
  *** MySQL query error:
  SQL: UPDATE `glpi_users`
                       SET `picture` = \'ÿØÿà\\0JFIF\\0\\0`\\0`\\0\\0ÿÛ\\0C\\0ÿÛ\\0CÿÀ\\0\\0`\\0?\\\"\\0ÿÄ\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0\\0	\\nÿÄ\\0µ\\0\\0\\0}\\0!1AQa\\\"q2‘¡#B±ÁRÑð$3br‚	\\n\\Z%&\\\'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyzƒ„…†‡ˆ‰Š’“”•–—˜™š¢£¤¥¦§¨©ª²³´µ¶·¸¹ºÂÃÄÅÆÇÈÉÊÒÓÔÕÖ×ØÙÚáâãäåæçèéêñòóôõö÷øùúÿÄ\\0\\0\\0\\0\\0\\0\\0\\0	\\nÿÄ\\0µ\\0\\0w\\0!1AQaq\\\"2B‘¡±Á	#3RðbrÑ\\n$4á%ñ\\Z&\\\'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz‚ƒ„…†‡ˆ‰Š’“”•–—˜™š¢£¤¥¦§¨©ª²³

...

´‡IÒá}Ÿf´ò\\ZInîÂDÓ^Í)ù\\0wH¢PFÒK¾ø¾ñüG­ø“P¿–0–ñiÉr£tèÓ3L`³àùHÂ0dTUZàç’~Q‡QÔµ	™æûEÍÕÌ®ò®í$²6çf8\\\';ŽNH&gt;˜¯tðD#J¶ŒÜÃ$†k‰¦–6È2ýœÆ	rv+0^2F03^²«*¸…(û”âù’³òJR¶îÖ¶ÖKMÛ&gt;b´c\\nm6åRQQNû%fÒÝ$ûmª?ÿÙ\' WHERE `id` =\'276\'
  Error: Incorrect string value: '\xFF\xD8\xFF\xE0\x00\x10...' for column 'picture' at row 1
  Backtrace :
  inc\commondbtm.class.php:357                       
  inc\commondbtm.class.php:1116                      CommonDBTM->updateInDB()
  inc\authldap.class.php:2088                        CommonDBTM->update()
  front\user.form.php:107                            AuthLDAP::ldapImportUserByServerId()

But if we try several times (3 times) at the end it's ok, and the picture is uploaded into a file and not into the DB like it seems it's trying to do

**Comment by orthagh** [comment]
Which action causes thoses errors ?
Manual synchronisation of a user ?

**Comment by tomolimo** [comment]
Yes manual synch

**Comment by orthagh** [comment]
Not sure about this correction and i can't replicate the issue.
So, let me knows if its ok

**Comment by tomolimo** [comment]
I'm currently out of office: I'll check this on next Wednesday,
thank you
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
It seems to be solved for 0.91 (I did not test for 0.90)
Thank you,
Regards,
Tomolimo
