### ISSUE TITLE
vulnerability assessment on 9.2.3

### ISSUE THREAD

**Issue by daniejstriata** [glpi-project/glpi#4181]
For your review. I did a vulnerability scan of the GLPI homepage for version GLPI 9.2.3 doing an internal (authenticated) and external (unauthenticated) test.

Externally there are not serious findings but internally I can give you information on a couple high risk items.

What is the process to share the scan results?

**Comment by orthagh** [comment]
Send your tests to glpi-security [at] ow2.org

**Comment by daniejstriata** [comment]
Thanks. I sent the PDF. Closing this.
