### ISSUE TITLE
[9.2.2] Business rule do not works

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#4183]
* Steps to reproduce (which actions have you made) :
Add a business rule : 
When you update a ticket
Criteria : Technician exists
Action : Add a technician group (for example : GROUP 1)

* Expected result :
Technician group should be added

* Actual result :
Technician group is not added

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.2

**Comment by orthagh** [comment]
Just tested on 9.2.4 (9.2/bugfixes branch) without encountering the issue:

![image](https://user-images.githubusercontent.com/418844/41525356-01657464-72e1-11e8-8319-bb8af388f6a4.png)

![image](https://user-images.githubusercontent.com/418844/41525366-092751f4-72e1-11e8-94a2-c1b68fa2af9b.png)

I tested on ticket add and on update.

**Comment by trasher** [comment]
No feedback, closing
