### ISSUE TITLE
No warranty notification if set to 0 ?

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#4187]
Took me a long while to figure this out :/

- Infocom is active
- Entity is set to "Send Financial & Administrative Information Alarms Before" -> 30 days
- Create Computer with {date today+7 days} as warranty with "Warranty Duration" -> 0 months
- Trigger cron ... no notification
- Set date to {previous used date - 1month} and "Warranty Duration" to 1 month -> Mail sent

There should also be a mail with the fixed date - can somebody confirm ?

**Comment by Eon9D** [comment]
Okay my bad. The field for the date says "start date".
Nevertheless it would be nice to have an option to set a fixed end date with notification.

**Comment by trasher** [comment]
Please use suggestions website for RFE.
