### ISSUE TITLE
Techicians shouldn't see satisfaction survey's data

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#4190]
Hi,
I just wanna know if it's supposed to happen and I should ask for a new feature on userecho, or if it's a bug.

* Steps to reproduce (which actions have you made) :
-Enable Satisfaction Surveys
-Answer as a post-only user

* Expected result :
-Technicians shouldn't see the satisfaction information of the tickets.

* Actual result :
-Technicians are able to see any satisfaction survey's data.

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Tried on GLPI 9.2.3 and 9.3RC2

**Comment by orthagh** [comment]
There is no right associated to survey display currently.
So any user with read right on the ticket is able to display the results of the survey.

So i think it's more an enhancement, and you could submit it on userecho.

Regards
