### ISSUE TITLE
Satisfaction surveys don't close after due date

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#4192]
* Steps to reproduce (which actions have you made) :

I have configured the satisfaction surveys by the following:

- [ ] Configuring the satisfaction survey - External Survey
- [ ] Create survey after - As soon as possible
- [ ] Rate to Trigger Survey - 70%
- [ ] Duration of survey - 4 days
- [ ] For tickets closed after - 21-05-2018 12:00
- [ ] URL - A Google Forms URL

* Expected result :

- [ ] As I don't use internal surveys, the system can't get to know when the user has answered the survey.
- [ ] As a result, the satisfaction surveys keeps being shown on the home page of every user which has surveys opened.
- [ ] It should disappear after 4 days

* Actual result :

- [ ] The surveys seem not close anytime.

* URL of the page :

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/13874922/41596500-ed5f20bc-73a0-11e8-9cd1-75364ad06829.png)
![image](https://user-images.githubusercontent.com/13874922/41596524-f95afc7e-73a0-11e8-8679-0b71a32e0558.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Information about system installation & configuration
--
[code]   GLPI 9.2.3 ( => /var/www/html/producao) Installation mode: TARBALL

Operating system: Linux ip-172-31-2-143 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 PHP 7.0.27-0+deb9u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.25 (Debian) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 Server Software: Debian 9.1 	Server Version: 10.1.26-MariaDB-0+deb9u1 	 via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed /var/www/html/producao/config : OK /var/www/html/producao/files : OK /var/www/html/producao/files/_dumps : OK /var/www/html/producao/files/_sessions : OK /var/www/html/producao/files/_cron : OK /var/www/html/producao/files/_graphs : OK /var/www/html/producao/files/_lock : OK /var/www/html/producao/files/_plugins : OK /var/www/html/producao/files/_tmp : OK /var/www/html/producao/files/_cache : OK /var/www/html/producao/files/_rss : OK /var/www/html/producao/files/_uploads : OK /var/www/html/producao/files/_pictures : OK /var/www/html/producao/files/_log : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/producao/lib/htmlawed) phpCas version 1.3.5 in (/var/www/html/producao/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/html/producao/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/html/producao/vendor/simplepie/simplepie/library) TCPDF version 6.2.16 in (/var/www/html/producao/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/producao/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/producao/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/producao/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/producao/vendor/sabre/vobject/lib)

Not active

fields               Name: Campos adicionais              Version: 1.6.0      State: Not activated 	behaviors            Name: Comportamental                 Version: 2.0.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.2+1.0    State: Enabled 	pdf                  Name: Imprimir em PDF                Version: 1.3.0      State: Enabled 	showloading          Name: Mostrar Carregamento           Version: 1.0.0      State: Enabled 	os                   Name: OS                             Version: 0.0.8      State: Not activated 	dashboard            Name: Painel                         Version: 0.9.0      State: Enabled 	reports              Name: Relatórios                     Version: 1.11.0     State: Enabled 	renamer              Name: Renamer                        Version: 0.90-1.0   State: Enabled 	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Enabled
[/code]

**Comment by trasher** [comment]
Just tested on 9.3/bugfixes branch; survey no longer appears on central interface when number of days has been reached.

**Comment by arthurrschaefer** [comment]
Hi @trasher,

Thanks for checking. I've tested as well and it really works on a 9.3 clean base, I'm gonna create a prototyping base with my data to check if the already opened surveys are going to be closed as well.

**Comment by trasher** [comment]
@arthurrschaefer thank you for the feedback.

I'm clogin this one since tehre will be no new 9.2 releases (last was yesterday). If you see any problem with your existing data, feel free to reopen ;)

**Comment by arthurrschaefer** [comment]
Hi,
I've updated my instance to 9.3 and even after I wait the time to the satisfaction surveys to close, they're still open.
Right now I have more than 300 surveys open.
Just to remember that I use the external satisfaction survey, that's why there aren't satisfaction responses. 

Is there any way for me to close these surveys manually? The new surveys are expiring as it should, the old ones, aren't.

**Comment by trasher** [comment]
I reopen for further investigation; I do not know this part.

**Comment by arthurrschaefer** [comment]
Hello dear,

Any updates on my request? 

Thanks in advance and sorry for disturbing.

**Comment by arthurrschaefer** [comment]
Hi,
Do you know which is the parameter for the system to know the satisfaction is answered or due?
Maybe I could execute a query to update this parameter. Just for the open satisfactions to go expired or answered.
Thanks.

**Comment by arthurrschaefer** [comment]
I've talked to @orthagh, and he helped me with the following command to update my not answered and not even expired satisfaction surveys.
Thanks Alexandre!

`UPDATE glpi_ticketsatisfactions SET date_answered = NOW() WHERE date_answered IS NULL`

**Comment by serviceticst** [comment]
Hello, @trasher 

Is there a definitive (official) solution planned for this issue, or is the only way to resolve it still through direct database changes as mentioned by Arthur?

Thank you.
