### ISSUE TITLE
ticket creation lost attachment if change requester (or category)

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4195]
* Steps to reproduce (which actions have you made) :

1.  fill titel
2.  fill desc
3.  attach file
4.  change requester or change category the attachment is dropped but **not** the title or description.
5.  (if i change from request to incident the file is also lost but title and description not. I'm not sure but or normal.)

- (deactivated all plugins and deinstalled)
- (no ticket template -  no category on ticket templates ;))
- (entity setting - auto assign category and item is set to no)

http://forum.glpi-project.org/viewtopic.php?id=162931
* Expected result :
Uploaded is still there equal description

* Actual result :
Uploaded file is missing

* URL of the page :
http://192.168.1.108/front/helpdesk.public.php?create_ticket=1
http://192.168.1.108/front/tracking.injector.php

* Screenshot of the problem (if pertinent) :
https://www.youtube.com/watch?v=RrZqSKJ8HkY&feature=youtu.be

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Informationen über das System, die Installation und die Konfiguration
--
[code]   GLPI 9.3-dev ( => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux glpidev 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 PHP 7.2.5-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, session, 	shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zlib) Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at 192.168.1.108 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36 Server Software: Ubuntu 18.04 	Server Version: 10.1.29-MariaDB-6 	Server SQL Mode:  	Parameters: glpidbuser@localhost/glpidb 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (10.1.29) - Perfect! /etc/glpi/ : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

**Comment by trasher** [comment]
I do not think it is possible to keep uploaded file, GLPI not yet handle it, it's only on browser side.

> not the title or description

Just tested on current 9.3/bugfixes branch; on page reload, attachment title and description are removed.

**Comment by Armin83** [comment]
No. In my case only attachment is removed.

> Google Chrome ist auf dem neuesten Stand.
> Version 67.0.3396.87 (Offizieller Build) (64-Bit)

**Comment by trasher** [comment]
Just tested on chromium as well wih current 9.3/bf and cannot reproduce.

**Comment by orthagh** [comment]
With actual design, it's not possible at all to keep attachments on reload.
We're working on a new GUI, i think it may be fixed later.
