### ISSUE TITLE
9.2.3: Multiplied element types in automatic actions

### ISSUE THREAD

**Issue by pVesian** [glpi-project/glpi#4202]
Hi,

On 9.2.3 on the automatic actions list, if you filter by Type of element some of them appear multiple times in the dropdown. They seem to be indexed by id and not by name.

![capture d ecran de 2018-06-20 10-49-33](https://user-images.githubusercontent.com/3509962/41650395-3a73b9a2-747e-11e8-8461-d805ade2db98.png)

Thanks.

**Comment by trasher** [comment]
Do you have plugins enabled? If so, could you please try without plugins?

**Comment by pVesian** [comment]
Yes, but I also tried with all plugins disabled.
