### ISSUE TITLE
Notification if the application is not taken to work within the specified time

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#4206]
hi,
there is a need to notify and add to the observers of the head or responsible if the ticket is not accepted for work within the time (specified time)

is there this option in SLA ? and can it be exist separately ?

**Comment by orthagh** [comment]
Yes in sla, you could add an escalation level containing an action "Automatic reminders of SLA", 
and a criteria to check the ticket status for ex

This one serves to send notifications to different recipients you can manage in Setup > Notifications > Notifications (you may need to add a new event for sla)
