### ISSUE TITLE
Object reference

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#4222]
it is not correct to insert links to objects in GLPI

![2018-06-22 18 02 25](https://user-images.githubusercontent.com/11009787/41783905-be6320b2-7646-11e8-82c6-013a77460bd3.png)

In this regard, links in GLPI and in the notification via e-mail are opened incorrectly.

**Comment by cedric-anne** [comment]
Hi,

Can you please provide steps to reproduce and give us details about your installation (GLPI version, plugins, ... ) ?

Regards

**Comment by cedric-anne** [comment]
I just tried copying a link from the computer list (in page `/front/computer.php`) ans in works both in 9.2.4 and in latest commit of 9.3/bugfixes.

The problem can comes either from the link you copied (which is maybe wrong), either from a bad interaction between your browser, Windows copy/paste tool, and TinyMCE.

If base link is correct, not sure we can do anything about it.

**Comment by Smiley-k** [comment]
No, try the following steps. Select the computer name with the mouse cursor, press ctrl+c, return to the creation of the ticket and press ctrl+v

**Comment by cedric-anne** [comment]
It is exactly what I have done and it works on my machine with Chromium (`Version 66.0.3359.181 (Build officiel) Built on Ubuntu , running on Ubuntu 18.04 (64 bits)`).

As I cannot reproduce, it is hard for me to help.

**Comment by trasher** [comment]
Same as @cedric-anne ; cannot reproduce (FF linux).

**Comment by Smiley-k** [comment]
i use windows 10 \ chrome 67.0.3396.99 (x64)

**Comment by trasher** [comment]
Guess this is a "limitation" of what can be done currently (as example, it's not possible to copy/paste 2 images, maybe your selection is too wide and include another one; something like that).
