### ISSUE TITLE
set font-size to 12px

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#423]
Hi,

It might be interesting to put the font-size to 12px instead of 11px for input and textarea for more comfortable reading.

Enjoy at the same time to enlarge the textarea from 120 to 140/150 px height.

What do you think ?

++

**Comment by orthagh** [comment]
font-size, is personna, i think.
on my side, I dislike 12px.

You can change in your instance in this file : https://github.com/glpi-project/glpi/blob/master/css/styles.css#L319
