### ISSUE TITLE
don't stop SLAs right user

### ISSUE THREAD

**Issue by mvestrotech** [glpi-project/glpi#4231]
Problems encountered in 9.2.2 and on the branch 9.2/bugfixes.

During a ticket creation and direct assignment with an account that does not have the rights to update the Time To Own does not stop.

![image](https://user-images.githubusercontent.com/23355435/41851136-44150ef4-7887-11e8-87d1-ef2fff9b27f4.png)

![image](https://user-images.githubusercontent.com/23355435/41851191-67763986-7887-11e8-8c3a-2c6b31cd7e67.png)

If the same action is reproducted with a super-admin profile the TTO will stop.

Problem reproduced by @Pieurre  and me

**Comment by orthagh** [comment]
as usual, @mvestrotech (and @Pieurre), is the issue has been reproduced on 9.2.4 (released last week) ?

**Comment by mvestrotech** [comment]
9.2.4 : KO

**Comment by trasher** [comment]
duplicates https://github.com/glpi-project/glpi/issues/4170?

**Comment by Pieurre** [comment]
No not the same problem.

**Comment by mvestrotech** [comment]
In summary the TTO does not stop when the creator of the ticket does not have the rights of updates and that the assignment is done at the creation

**Comment by orthagh** [comment]
on new install of glpi 9.2/bugfixes, i don't replicate:

![image](https://user-images.githubusercontent.com/418844/41913647-2d877aee-7951-11e8-925c-f6e2fe509a75.png)

![image](https://user-images.githubusercontent.com/418844/41913695-486eb296-7951-11e8-8a42-e7d7f15ab780.png)
