### ISSUE TITLE
 fail survey

### ISSUE THREAD

**Issue by kabarrerar** [glpi-project/glpi#4233]
I'm activated the satisfaction survey from the notification option every time you create an issue

When closing the incident, the satisfaction option or the survey to qualify does not appear on the ticket and the user receives the result ## ticket.urlsatisfaction ## and does not redirect it to any side.

How do I activate the sastisfaction tab?

Attached screenshot of the result that generates me in the survey

![1](https://user-images.githubusercontent.com/40579214/41873518-ced1cc5a-788a-11e8-8141-ffb4335eb166.JPG)
![2](https://user-images.githubusercontent.com/40579214/41873519-ceecfa7a-788a-11e8-8947-93f1b96376f1.JPG)

Información acerca de la instalación y configuración del sistema
[code]
 
GLPI 9.2.3 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux glpi 4.10.0-19-generic #21-Ubuntu SMP Thu Apr 6 17:04:57 UTC 2017 x86_64
PHP 7.0.22-0ubuntu0.17.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Ubuntu) (Apache/2.4.25 (Ubuntu) Server at 192.168.195.151 Port 80)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.20-0ubuntu0.17.04.1
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpiweb
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/html/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/var/www/html/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+SSL (xxxxxxxxxxxxx@smtp.gmail.com)

Mails receivers
 
Name: 'xxxxxxxx' Active: Yes
	Server: '{imap.gmail.com:993/imap/ssl}' Login: 'xxxxxxxxx' Password: Yes

Plugins list
 
	dashboard            Name: Dashboard                      Version: 0.9.2      State: Not installed
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.3      State: Not installed
	reports              Name: Reportes                       Version: 1.11.3     State: Not installed

[/code]

**Comment by trasher** [comment]
Try with 9.2.4.

**Comment by kabarrerar** [comment]
the problem is not solved with the update

**Comment by hotdesc** [comment]
I have the same problem here

**Comment by cedric-anne** [comment]
Hi,

I just tried on current state of 9.4 branch and I cannot reproduce: displayed URL is correct and redirection to the satisfaction tab is correctly done.

Issue may have been fixed yet.

Regards
