### ISSUE TITLE
Knowledge base Images Error

### ISSUE THREAD

**Issue by tfarion** [glpi-project/glpi#4234]
Im with this error in Knowledge base.

Work just for creator, others user get this error

![image](https://user-images.githubusercontent.com/40583370/41881576-92c89c86-78ba-11e8-8c24-745dc45d434a.png)

![image](https://user-images.githubusercontent.com/40583370/41881564-85a1e0b2-78ba-11e8-9e5e-32f480b463ad.png)

Version: 4.2.4.

**Comment by trasher** [comment]
Duplicate with #4236
