### ISSUE TITLE
[9.2.4] Unauthorized access to this file for pasted images

### ISSUE THREAD

**Issue by GuiGuiSoft** [glpi-project/glpi#4236]
Hello,

* Steps to reproduce (which actions have you made) :
In a ticket : copy-paste an image in a rich text field (description/follow-up/task)

* Expected result :
Everyone that can see the ticket can see the image too.

* Actual result :
Only administrators and users who did the copy-paste can see the image.
_Note that for me the bug was already present in 9.2.3 and is very similar to #3292 ._

![image](https://user-images.githubusercontent.com/8069239/41903620-acef272a-7936-11e8-8720-748c0c751931.png)

![image](https://user-images.githubusercontent.com/8069239/41903681-d97dd03e-7936-11e8-8925-2ddfcb8d49bf.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.4 ( => /opt/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux xxx 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64
PHP 7.0.30-0ubuntu0.16.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
Server Software: (Ubuntu)
	Server Version: 5.7.22-0ubuntu0.16.04.1-log
	Server SQL Mode: 
	Parameters: xxxxx@localhost/xxxxx
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/opt/glpi/config : OK
OK/opt/glpi/files : OK
OK/opt/glpi/files/_dumps : OK
OK/opt/glpi/files/_sessions : OK
OK/opt/glpi/files/_cron : OK
OK/opt/glpi/files/_graphs : OK
OK/opt/glpi/files/_lock : OK
OK/opt/glpi/files/_plugins : OK
OK/opt/glpi/files/_tmp : OK
OK/opt/glpi/files/_cache : OK
OK/opt/glpi/files/_rss : OK
OK/opt/glpi/files/_uploads : OK
OK/opt/glpi/files/_pictures : OK
OK/opt/glpi/files/_log : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

Libraries

 
htmLawed version 1.2.4 in (/opt/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/opt/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/opt/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/opt/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.17 in (/opt/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/opt/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/opt/glpi/vendor/true/punycode/src)
iacaml/autolink in (/opt/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/opt/glpi/vendor/sabre/vobject/lib)

LDAP directories

 
Server: 'xxxxx', Port: '389', BaseDN: 'DC=xxxxx,DC=fr', Connection filter:
		'(&(objectClass=user)(memberOf=CN=xxxxx,OU=Groupes,OU=xxxxx,DC=xxxxx,DC=fr)(cn=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))',
		RootDN: 'xxxxx', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP+SSL (xxxxx@xxxxx.fr)

Mails receivers

 
Name: 'xxxxx@xxxxx.fr' Active: Yes
	Server: '{imap.xxxxx.fr:993/imap/ssl/novalidate-cert}' Login: 'xxxxx' Password: Yes
Name: 'xxxxx@xxxxx.fr' Active: Yes
	Server: '{imap.xxxxx.fr:993/imap/ssl/novalidate-cert}' Login: 'xxxxx' Password: Yes

Plugins list

 
	fields               Name: Champs supplémentaires         Version: 1.7.0      State: Enabled
	escalade             Name: Escalades                      Version: 2.2.1      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.4.0      State: Enabled

**Comment by GuiGuiSoft** [comment]
Oops, just saw the #4234 . Maybe duplicate :innocent:

**Comment by trasher** [comment]
Please try with latest 9.3/bugfixes nightly build (https://forge.glpi-project.org/tarballs/); 9.2 will not receive any further updates.

**Comment by tfarion** [comment]
Worked just for user admin.

Admin user can view all images without errors, but others users get same error

**Comment by tfarion** [comment]
@trasher Any solution?

**Comment by orthagh** [comment]
I just tested on 9.3 with a self-service profile with another user than the ticket's creator without replicating the issue.

Did you (ping @tfarion, @GuiGuiSoft) do your last test with 9.3 (or 9.2.4 at least) and a new ticket (old tickets cannot be fixed) ?

**Comment by GuiGuiSoft** [comment]
Hello, I updated to 9.3.0 : the issue remains but I have new informations :)

Pasted images in rich text fields can be viewed if the user profile has the Read right in Management > Documents. _This right also give access to the Management > Document screen._
![image](https://user-images.githubusercontent.com/8069239/42631302-1e40933c-85da-11e8-8b0e-f902e97afcf5.png)

So pasted images in rich text field need the read right to be viewed whereas "regular" uploaded files doesn't need this right to be viewed (cf. Capture.png file in the screenshot of the first message of this issue).

Is there a permission check on pasted image different on uploaded files ?

Regards.

**Comment by samdurnxn** [comment]
To be better, it might be good to process an image past into the rich text field as it done with an attached file and add a record in the glpi_documents_items.
In addition, it will avoid absolute url of the image in the message.

**Comment by GuiGuiSoft** [comment]
Hello,

At this point it seems that uploaded documents and pasted images in rich text fields are not processed the same way.

- Are you waiting for more informations ?
- Do you accept pull request ?

Regards

**Comment by trasher** [comment]
> Are you waiting for more informations ?

Not really, but we have other things to manage.

> Do you accept pull request ?

Sure, if you think you an get that fixed, feel free.

**Comment by GuiGuiSoft** [comment]
> Sure, if you think you an get that fixed, feel free.

Unfortunately I don't have the needed skills but if I find someone who has it... :smile:

**Comment by bigben386** [comment]
Are there any security concerns giving post only users the documents permissions? I have been fixing this on 9.2.4 by manually adding the kb article to the document's associated items but that is a pain.

**Comment by cedric-anne** [comment]
Hi,

@bigben386 : I made a fix in https://github.com/glpi-project/glpi/pull/4483 for 9.3/bugfixes branch.
I did not test it and did not even review my code so it may not work. I will do the tests on monday.

Regards

**Comment by cedric-anne** [comment]
Hi,

@bigben386 Unfortunately, you will not be able to give access to documents for users that has only simplified interface.

The fix in #4483 should be OK, but it has been made on the 9.3 branch.

Bugs were :
 - users with "central" interface but no rights to view documents were not able to view inlined images in reminders, KB items and tickets,
 - users with simplified interface were not able to see inlined images in reminders and KB items,
 - anonymous users were not able to see inlined images in public FAQ.

Regards

**Comment by Akuket** [comment]
I have tried your fix and I still have a problem to visualize the image :
![image](https://user-images.githubusercontent.com/32392661/44040446-9aa92038-9f1b-11e8-840f-150645bc5c7d.png)

And when I click on this link, I have that :
![image](https://user-images.githubusercontent.com/32392661/44040499-c671116c-9f1b-11e8-8eba-d0866b2b7b16.png)

**Comment by cedric-anne** [comment]
Hi,

If you have this message, you have to apply
https://github.com/glpi-project/glpi/pull/4479 too.

**Comment by Akuket** [comment]
It works properly after that. Well done.

**Comment by GuiGuiSoft** [comment]
Hello,

It seems that the problem re-appeared in 9.3.3 :/
