### ISSUE TITLE
Power supply components do not appear on the device components tab

### ISSUE THREAD

**Issue by FrolON** [glpi-project/glpi#4238]
9.2.4
Expected result : List of components associated with device.

Actual result : The list is not displayed.

URL of the page : /front/peripheral.form.php?

The same problem as in issue #4047, but the type of components is the power supply.

**Comment by trasher** [comment]
It is not possible to add a power supply on a peripheral; at least after the fix provided for #4047.
If the relation has been created before the fix; this is "normal", since the relation is not permitted.

If the relation has been created after the fix; please tell me how to reproduce.

**Comment by FrolON** [comment]
Then everything is fine. This is no longer possible in 9.2.4.

**Comment by trasher** [comment]
OK, thanks for the feedback :)

**Comment by Megachip** [comment]
Same problem with phones. Will it be reintroduced with 9.3?

**Comment by Megachip** [comment]
Anything new on this "bug" ? 

All our phones have power supplies (the desk and the mobile ones), why it isn't possible to assign them anymore?

**Comment by trasher** [comment]
This is not a bug, but something that has never been implmented properly. Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by Megachip** [comment]
@trasher it is ;) Also someone refers on that ticket.
https://glpi.userecho.com/communities/1/topics/862-assign-power-supply-to-phone

Ok, removing a used and necessary feature isn't a bug, but ... hm...

**Comment by trasher** [comment]
This was not a feature, this was not following existing configuration... The feature you're talking about was the bug :D
