### ISSUE TITLE
Is it possible to add the ability to hide an object column

### ISSUE THREAD

**Issue by FrolON** [glpi-project/glpi#4239]
Expected result : hide the entity column.
Screenshot of the problem (if pertinent) :
![list1](https://user-images.githubusercontent.com/39527010/41909470-c3b6f578-794f-11e8-8456-81e76d12eaff.PNG)
GLPI setup (you can find it in Setup > General menu, System tab) : 9.2.4

**Comment by trasher** [comment]
Please use [suggestions website](http://suggest.glpi-project.org) for RFE.
