### ISSUE TITLE
[9.2.4] Dictionnary Rule: Category (Bug)

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#4243]
GLPI 9.2.4 / Fusion inventory 9.2+2.0-RC1
 The criteria category in the dictionary rules doesn't work.

**Comment by trasher** [comment]
Please provide details.

**Comment by FRANCOIS50** [comment]
If I define the action category in a rule of the software dictionary this action will be not applied to the corresponding software:

Rule definition:
![capture0](https://user-images.githubusercontent.com/12511115/41955599-327a5844-79d0-11e8-8b5d-042cbfe363ab.GIF)

Criteria
![capture1](https://user-images.githubusercontent.com/12511115/41955611-3be6d51a-79d0-11e8-8f75-bfde511d0962.GIF)

Actions:
![capture2](https://user-images.githubusercontent.com/12511115/41955617-43397278-79d0-11e8-8337-0365cdb27008.GIF)

if I start the rules application option -->  
![capture3](https://user-images.githubusercontent.com/12511115/41955672-7e1ee33c-79d0-11e8-85f4-718cb9056741.GIF)

Software is correctly named but it doesn't get the category "Géré"

**Comment by cedric-anne** [comment]
Hi,

I made some tests using the "Replay the dictionary rules" button. I noticed that the code responsible of rules replay is doing more than just replay rules, which can lead to a result that differs from realtime rule application.

Following patch fix the case where rule does not change name of the software (which is not the case of the ticket). Indeed, when name changed, the category definition is made using rules from `/front/rulesoftwarecategory.php` and does not applies category computed by software dictionary rules.
```diff
diff --git a/inc/ruledictionnarysoftwarecollection.class.php b/inc/ruledictionnarysoftwarecollection.class.php
index 51c4e164b..b9baf8870 100644
--- a/inc/ruledictionnarysoftwarecollection.class.php
+++ b/inc/ruledictionnarysoftwarecollection.class.php
@@ -167,7 +167,9 @@ class RuleDictionnarySoftwareCollection extends RuleCollection {
                 || (isset($res_rule['is_helpdesk_visible'])
                     && ($res_rule['is_helpdesk_visible'] != $input['helpdesk']))
                 || (isset($res_rule['manufacturer'])
-                    && ($res_rule['manufacturer'] != $input['manufacturer']))) {
+                    && ($res_rule['manufacturer'] != $input['manufacturer']))
+                || (isset($res_rule['softwarecategories_id'])
+                    && ($res_rule['softwarecategories_id'] != $input['softwarecategories_id']))) {
 
                $IDs = [];
                //Find all the softwares in the database with the same name and manufacturer
```

@FRANCOIS50, you can fix your problem by creating a rule here responsible of defining the category of your software `/front/rulesoftwarecategory.php`.

Regards
