### ISSUE TITLE
Alert on Software Licenses doesnt work

### ISSUE THREAD

**Issue by latern02** [glpi-project/glpi#4249]
Hey,
Im using Glpi 9.2.3 on an apache server. 

Its connected with OCS, i tried to start the email notification for the software license... But it doesnt work...
I seem its a bug? 
Its configurated  and the receptor are also given.

greets

**Comment by trasher** [comment]
Try on 9.2.4.If you can reproduce, check the logs for any usefull output; and also try with all plugins disabled.

**Comment by latern02** [comment]
I tried also i updated it, nothing is better.. the one log on sql have an error. There are database with plugins_ lost, when i deactivate the plugins it doesnt work too.
Also there is no entry in the notification queue, but there are some deleted with tickets,... and the Email system is also right, i get emails when tickets are closed or so...

**Comment by latern02** [comment]
Hello again,

The error on sql is solved now, but also no email notification on license expiry date.
Need help please...

greets
