### ISSUE TITLE
GLPI 9.2.4 - Button solution not appear

### ISSUE THREAD

**Issue by mauriciolamego** [glpi-project/glpi#4251]
* Steps to reproduce (which actions have you made) :
After upgrading to 9.2.4 the solution button is not appearing to technicians. Analyzing I saw that now only with the UPDATE CALL option is that the button appears.
This seems to be wrong because I do not want the permission for my technician to change or change the originality of the call.
How to fix this or configure

* Expected result :
the solution button appears to the technician even if he is not allowed to refresh tickets

* Actual result :
the solution button is not showing up for technicians and before the upgrade was.

* URL of the page :
https://glpi/front/ticket.form.php?id=XXX  , in processing ticket > solution

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/40633272/41990691-9997a75e-7a19-11e8-9bd9-bba7c4c79248.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
![image](https://user-images.githubusercontent.com/40633272/41990729-b64a7fc0-7a19-11e8-9b74-432ea40a9b9a.png)

**Comment by trasher** [comment]
Please check logs to see if there are any errors.

**Comment by mauriciolamego** [comment]
Dear, the problem was solved in version 9.3 and I'm already using it. Thank you very much for your attention.
