### ISSUE TITLE
9.2.4 issue when importing users from AD

### ISSUE THREAD

**Issue by shaadowsky** [glpi-project/glpi#4252]
hello, all
i have glpi 9.2.4. Authentification with AD successful
![image](https://user-images.githubusercontent.com/40653586/42015330-8737d500-7ad9-11e8-9f02-3fa49f5ee5a2.png)

when i want import users nothing happens
![image](https://user-images.githubusercontent.com/40653586/42015375-b41b01be-7ad9-11e8-9780-aa4063095d0d.png)

same in group import
![image](https://user-images.githubusercontent.com/40653586/42015557-73eaf8fa-7ada-11e8-8a34-0429289ec9f8.png)

* my GLPI setup
![image](https://user-images.githubusercontent.com/40653586/42015427-efc8b04e-7ad9-11e8-87c6-c867c352664d.png)

**Server:**
Operating system: Linux glpi 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64
PHP 7.0.30-0ubuntu0.16.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 10.10.0.37 Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.21-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_cache : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

**Libraries**
htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/var/www/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.17 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

**LDAP directories**
Server: '10.10.0.1', Port: '389', BaseDN: 'zheldo.local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl;1.2.840.113556.1.4.8-3:=2)))', RootDN: 'glpi@zheldo.local',
		Use TLS: none

**Comment by alessiotomelleri** [comment]
my "Connection Filter" is slight different :+1: 
(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))

look at the endo of yours...   "...  .1.4.8-3:=2)))  
I don't have "-"

Alessio

**Comment by shaadowsky** [comment]
nothing happens:

![image](https://user-images.githubusercontent.com/40653586/42140788-3e90a516-7dd6-11e8-9215-378a65fa9efe.png)
![image](https://user-images.githubusercontent.com/40653586/42140795-4b76b64e-7dd6-11e8-9a73-af3399ddc336.png)
![image](https://user-images.githubusercontent.com/40653586/42140806-6564b7c2-7dd6-11e8-8f89-90761e04eb49.png)

**Comment by roshanroche** [comment]
Hi,
BaseDN 
DC=zheldo,DC=local
connection filter = (&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))

try

**Comment by shaadowsky** [comment]
nothing happens.
if connection filter CLEAR, i see all users in AD

**Comment by roshanroche** [comment]
![image](https://user-images.githubusercontent.com/22425503/42207733-b0468f00-7ebb-11e8-9fa8-23bfc5616743.png)

**Comment by Megachip** [comment]
> if connection filter CLEAR, I see all users in AD
What is your AD Backend? Possible users aren't objectClass `user` and objectCategory `person`

**Comment by cedric-anne** [comment]
@shaadowsky 

Is your issue still present ?

Regards

**Comment by shaadowsky** [comment]
Yeap

пн, 30 июл. 2018 г., 16:03 Cédric Anne <notifications@github.com>:

**Comment by Nosolok** [comment]
@shaadowsky 
BaseDN and RootDN must point to your AD unit.
For example https://wiki.glpi-project.org/doku.php?id=en:ldap section Active Directory setup

**Comment by shaadowsky** [comment]
pong!

**Comment by piyush1337** [comment]
same issue here too someone please help

**Comment by piyush1337** [comment]
> ping?

trasher, as this is still open now and my issue is same can you help here please ????

**Comment by Armin83** [comment]
Did you try debug mode to get a error message ? (maybe similar problem https://forum.glpi-project.org/viewtopic.php?id=165765)

**Comment by shoothub** [comment]
Try to change:
Connection filter: `(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))`
BaseDN: `DC=yourdomain,DC=com`
RootDN: `CN=real_domain_user,CN=Users,DC=yourdomain,DC=com`
Login field: `samaccountname`
Synchronization field: `objectguid`

Here are example filter (Connection filter), if you want only list users whose are member of specific group:
`(&(objectClass=user)(objectCategory=person)(memberOf=CN=Glpi_users,CN=Users,DC=yourdomain,DC=com)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))`

To check your LDAP path you can use ADSI

**Comment by trasher** [comment]
This sounds more like a configuration issue than a bug. 
Please use [forums](http://forum.glpi-project.org) to get support; and o ly use github issues for bugs. Thank you.
