### ISSUE TITLE
[9.3 & 9.2.X] SQL error when delete a document in a ticket

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#4258]
Cannot delete a document in a ticket / SQL error

-  Steps to reproduce (which actions have you made) :

    1. Creating a ticket with a document and a ticket description with the character '

    2 . In the "Ticket processing" tab, I want to delete the document, it does not work.

- Actual result :
    SQL error :

```
  SQL: UPDATE `glpi_tickets`
                       SET `content` = 'Test d'apostrophe' WHERE `id` ='47792'
  Error: Erreur de syntaxe près de 'apostrophe' 
  Backtrace :
  inc\commondbtm.class.php:433                       
  inc\commondbtm.class.php:1231                      CommonDBTM->updateInDB()
  inc\document_item.class.php:208                    CommonDBTM->update()
  inc\commondbtm.class.php:1456                      Document_Item->post_purgeItem()
  front\ticket.form.php:197                          CommonDBTM->delete()
```

-    Your GLPI setup (you can find it in Setup > General menu, System tab) :
    GLPI 9.3RC1 & 9.2.X

Related with this issue : https://github.com/glpi-project/glpi/issues/4141

In the first correction (https://github.com/glpi-project/glpi/commit/9302dabeaff129dbae439cdc633dd523c5354d73), there's no ticket contents.

We made this change to correct the SQL error:

```
diff --git a/inc/document_item.class.php b/inc/document_item.class.php
index 98b50d826..a72adcb87 100644
--- a/inc/document_item.class.php
+++ b/inc/document_item.class.php
@@ -205,7 +205,7 @@ class Document_Item extends CommonDBRelation{
                                                          [$doc->fields['tag']]);
          }
 
-         $ticket->update($input);
+         $ticket->update(Toolbox::addslashes_deep($input));
       }
       parent::post_purgeItem();
    }
```

The line in 9.2/bugfixes : https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/document_item.class.php#L172

In the variable `$input`, the content of the ticket is not escaped, example of the content when deleting a document : 
```
  Array
  (
      [id] => 48583
      [date_mod] => 2018-06-28 16:16:51
      [_donotadddocs] => 1
      [_forcenotif] => 1
      [content] => delete 'image
  )
```

**Comment by trasher** [comment]
Please test provided fix in https://github.com/glpi-project/glpi/pull/4276

**Comment by amma35** [comment]
It's good for me, it works well.

**Comment by trasher** [comment]
Great, thanks for the feedback :)
