### ISSUE TITLE
Listing of software

### ISSUE THREAD

**Issue by bambresso** [glpi-project/glpi#426]
Listing of software have overdata on some columns: “License inventory number” and “License serial number”
How to exclude “License name” from this columns?

![gl1](https://cloud.githubusercontent.com/assets/13583138/12817796/f7eb4876-cb64-11e5-8e73-dca23c57f7b5.png)

**Comment by orthagh** [comment]
This one seems to very old. I checked in git history to find the commit who add this behavior.
@yllen, did you remember why theses lines (https://github.com/glpi-project/glpi/blob/master/inc/search.class.php#L2378-L2421)
concact name before real data ?

**Comment by yllen** [comment]
It's not licence name but software name

**Comment by AnaelMobilia** [comment]
@trasher This issue was fixed on #3208 .
Could you, please, close this issue ?

Thanks & Regards,
Anael

**Comment by trasher** [comment]
Indeed, thanks
