### ISSUE TITLE
not work button solved 

### ISSUE THREAD

**Issue by Smiley-k** [glpi-project/glpi#4264]
hi, After upgrading from version 9.2.4 to version 9.4 my button does not work solved.

GLPI 9.3.0 Copyright (C) 2015-2018 Teclib' and contributors
FusionInventory 9.3+1.0 - Copyleft © 2010-2018 by FusionInventory Team

plugin list

![image](https://user-images.githubusercontent.com/11009787/42088605-bebc30e2-7ba2-11e8-8a1e-b92ab488b828.png)

![image](https://user-images.githubusercontent.com/11009787/42088670-fb15d106-7ba2-11e8-8694-abb8bf383e95.png)

**Comment by Smiley-k** [comment]
![2018-06-29 14 05 18](https://user-images.githubusercontent.com/11009787/42089387-8c801b90-7ba5-11e8-979f-cd34b877cbeb.png)
error 500

**Comment by trasher** [comment]
Check logs

**Comment by Smiley-k** [comment]
@trasher 

[root@rp-vsr-03 _log]# cat php-errors.log
[2018-06-29 14:18:46] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): include_once(/var/www/html/glpi/plugins/mreporting/vendor/autoload.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/mreporting/setup.php:53
  plugins/mreporting/setup.php:53                    include_once()
  inc/plugin.class.php:257                           include_once()
  inc/plugin.class.php:113                           Plugin->checkStates()
  inc/includes.php:109                               Plugin->init()
  plugins/fusioninventory/index.php:49               include()
  {"user":"@rp-vsr-03","mem_usage":"0.011\", 4.19Mio)"}
[2018-06-29 14:18:46] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): include_once(): Failed opening '/var/www/html/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php')
  Backtrace :
  plugins/mreporting/setup.php:53
  plugins/mreporting/setup.php:53                    include_once()
  inc/plugin.class.php:257                           include_once()
  inc/plugin.class.php:113                           Plugin->checkStates()
  inc/includes.php:109                               Plugin->init()
  plugins/fusioninventory/index.php:49               include()
  {"user":"@rp-vsr-03","mem_usage":"0.000\", 4.19Mio)"}
[2018-06-29 14:18:47] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): include_once(/var/www/html/glpi/plugins/mreporting/vendor/autoload.php): failed to open stream: No such file or directory
  Backtrace :
  plugins/mreporting/setup.php:53
  plugins/mreporting/setup.php:53                    include_once()
  inc/plugin.class.php:257                           include_once()
  inc/plugin.class.php:113                           Plugin->checkStates()
  inc/includes.php:109                               Plugin->init()
  plugins/fusioninventory/index.php:49               include()
  {"user":"@rp-vsr-03","mem_usage":"0.012\", 4.22Mio)"}
[2018-06-29 14:18:47] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): include_once(): Failed opening '/var/www/html/glpi/plugins/mreporting/vendor/autoload.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php')
  Backtrace :
  plugins/mreporting/setup.php:53
  plugins/mreporting/setup.php:53                    include_once()
  inc/plugin.class.php:257                           include_once()
  inc/plugin.class.php:113                           Plugin->checkStates()
  inc/includes.php:109                               Plugin->init()
  plugins/fusioninventory/index.php:49               include()
  {"user":"@rp-vsr-03","mem_usage":"0.001\", 4.23Mio)"}

**Comment by Smiley-k** [comment]
Yes, I removed this plugin, but now the logs are empty, it means there are no errors. A button does not work

**Comment by trasher** [comment]
If you have an "Internal server" error like you shown in one of your screenshots, then there is something logged somewhere. In your system logs if not in glpi ones.

**Comment by trasher** [comment]
No feedback, closing.
