### ISSUE TITLE
Error Using Rack Template

### ISSUE THREAD

**Issue by Dackson** [glpi-project/glpi#4267]
* Steps to reproduce (which actions have you made) :
Add new rack model
-- Assets > Racks > Manage Templates > Add a template
Add new model based on model rack
-- Assets > Racks >  Add new rack > Choose a template
-- Save
-- Nothing happens

* Expected result :
A new Rack is added based on the template already created

* Actual result :
After adding a Rack template, and trying to use it nothing happens.
Note: The model is being saved in the glpi_rack table instead of the glpi_rackmodels table

* URL of the page :
Not

* Screenshot of the problem (if pertinent) :
![glpierro](https://user-images.githubusercontent.com/3226885/42108016-b29d87f4-7baf-11e8-9432-d1dc7c0924e0.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Not

**Comment by cconard96** [comment]
Rack templates are supposed to be stored in glpi_racks like other item types. the glpi_rackmodels table is used for models like "Dell Netshelter SX 24U". However, you are correct that adding racks from template fails add items to the DB. I should have a fix shortly.

**Comment by vikipediaEx** [comment]
hello may I ask has this issue been fixed?
