### ISSUE TITLE
[9.3] Localization Issue (German)

### ISSUE THREAD

**Issue by purdy87** [glpi-project/glpi#4273]
Hello,
i have an Issue with the German Localization.
Inventory Main-Dropdown it calls 
"Location"
"Address"
"Postal Code"
"Town"
"State"

The Problem is the translation of State. The correct translation of State should be "Staat" or "Bundesland" like an American State e.g. Ohio.
In the current translation of 9.3 it is translated with "Status". This is very confusing for my users.

How can i edit this translation? I tried to change it via poedit and i also used the new .mo file. Every word is changing - but not this.
In Poedit there is an Marker called "location".

![grafik](https://user-images.githubusercontent.com/11552524/42150644-c5283f40-7dda-11e8-9719-9414699becc3.png)

![grafik](https://user-images.githubusercontent.com/11552524/42150660-d00af6b4-7dda-11e8-87bd-9a2ee409f8f7.png)

Thanks in Advance!

**Comment by trasher** [comment]
Translations are done on Transifex: https://www.transifex.com/glpi/GLPI/language/de_DE/
