### ISSUE TITLE
add server room

### ISSUE THREAD

**Issue by chpego** [glpi-project/glpi#4278]
Hello :)

I don't know if it's a requests or a bug.

------------
* Steps to reproduce (which actions have you made) :
Open Datacenter in Management
Open the list of Server Room
Click on "Add"

* Expected result :
New server room is open

* Actual result :
New datacenter is open

* URL of the page :
/front/dcroom.php

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.0

**Comment by orthagh** [comment]
Not a bug, but a former behavior of glpi.
You can set it up as you want by go to your preference (click on your name top right)

And set "Go to created item after creation" to yes.
