### ISSUE TITLE
Ticket templates

### ISSUE THREAD

**Issue by jgobet** [glpi-project/glpi#428]
I have a problem with ticket templates when I do these actions :
- Installation GLPI in 0.90.1
- Login with **glpi** user
- **Administration** > **Entities** > **Add** (button +) avec **Name** : **entity**
- Logout and login with **glpi** user
- Select entity in clic on the link **Root entity (tree structure)** > clic on button **+** at left of Root entity > clic on **entity** for select
- **Assistance** > **Tickets** > **Manage templates...** (button 2 strokes) > **Add** (button +) with **Name** : **template**
- **Assistance** > **Tickets** > **Manage templates...** (button 2 strokes) > clic on **template** in table > **Predefined fields** > **Request source** > **Phone** > **Add**
- **Administration** > **Entities** > **Root entity > entity** > **Assistance** > **Ticket template** > **template** (in section **Root entity > entity**)
- Select Root entity in clic on the link **entity** (in top right) > clic on **Show all**
- **Setup** > **Dropdowns** > **Ticket categories** (in Assistance) > **Add** (button +) with **Name** : **categorie** and **Child entities** : **Yes**
- **Administration** > **Profiles** > **Technician** > **Assistance** > Unchecked **Upadte** for the line **Tickets** > **Save**
- Logout and login with **tech** user
- Select entity created in clic on the link **Root entity (tree structure)** > clic on button **+** at left of Root entity > clic on **entity** for select
- **Assistance** > **Create ticket** with **Categorie** : **categorie** and **Title** : **ticket**

And here when I create the ticket, the **request source is correct (Phone)**, but when I change page and I come back on the ticket, **the request source is modified (Helpdesk)**.

[For more information see the ticket 120773 open on the GLPI forum >](http://forum.glpi-project.org/viewtopic.php?id=120773).

Thanks.

**Comment by ladenree76000** [comment]
I confirm thi behaviour on 0.90.1 (out of the box, without plugins)

**Comment by orthagh** [comment]
Sorry for the delay of the last fix.
Should be better now
