### ISSUE TITLE
GLPI 9.2.4 to 9.3 Update database error

### ISSUE THREAD

**Issue by Lennynerofr** [glpi-project/glpi#4280]
Hi,

after update 9.2.4 to 9.3, i must update my database.
I have this error : 

9.3 migrate Ticket solution history - Erreur durant l'éxecution de la requête : REPLACE INTO `glpi_itilsolutions` (itemtype, items_id, date_creation, users_id, user_name, solutiontypes_id, content, status, date_approval) SELECT 'Ticket' AS itemtype, ticket.`id` AS items_id, ticket.`solvedate` AS date_creation, IF(log.user_name REGEXP '[(][0-9]+[)]$', SUBSTRING_INDEX(SUBSTRING_INDEX(log.`user_name`, '(', -1), ')', 1), 0) AS users_id, IF(log.user_name REGEXP '[(][0-9]+[)]$', NULL, log.`user_name`) AS user_name, ticket.`solutiontypes_id` AS solutiontypes_id, ticket.`solution` AS content, (CASE WHEN ticket.status = 6 THEN 3 -- if CLOSED, ACCEPTED WHEN ticket.status = 5 THEN 2 -- if SOLVED, WAITING WHEN ticket.status <= 4 THEN 4 -- if INCOMING|ASSIGNED|PLANNED, REFUSED ELSE 1 -- else NONE END) AS status, ticket.`closedate` AS date_approval FROM glpi_tickets AS ticket LEFT JOIN `glpi_logs` AS log ON log.`itemtype` = 'Ticket' AND log.`items_id` = ticket.`id` AND log.`id_search_option` = 24 WHERE LENGTH(ticket.`solution`) > 0 GROUP BY ticket.`id` ORDER BY ticket.`id` ASC, log.id DESC - L'erreur est Table 'glpi.glpi_logs' doesn't exist 

Can you help me please ?

Best regards

**Comment by trasher** [comment]
The `glpi_logs` table should exists. Restore your backup, and ensure your table is not crashed before doing the update

**Comment by Lennynerofr** [comment]
Hi,
i restore my previous glpi version (9.2.4)
My database is not crashed.
I search "glpi_logs" in my database, but it's not present.
Must i create it ?

**Comment by trasher** [comment]
Yes, this table is required.
