### ISSUE TITLE
Trying to write logs before checking write access

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#4286]
When updating (and probably installing as well), if the logs directory is not writable, there is an exception:
```
[03-Jul-2018 14:22:45 UTC] PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/var/www/webapps/glpi/files/_log/php-errors.log" could not be opened: failed to open stream: Permission denied in /var/www/webapps/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /var/www/webapps/glpi/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\StreamHandler->write(Array)
#1 /var/www/webapps/glpi/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#2 /var/www/webapps/glpi/inc/toolbox.class.php(435): Monolog\Logger->addRecord(400, 'Toolbox::userEr...', Array)
#3 /var/www/webapps/glpi/inc/toolbox.class.php(469): Toolbox::log(Object(Monolog\Logger), 400, Array)
#4 /var/www/webapps/glpi/inc/toolbox.class.php(657): Toolbox::logError('  *** PHP Warni...')
#5 [internal function]: Toolbox::userErrorHandlerNormal(2, 'mkdir(): Permis...', '/var/www/webapp...', 1508, Array)
#6 /var/www/webapps/glpi/inc/toolbox.class.php(150 in /var/www/webapps/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107

```

**Comment by Shesoff** [comment]
This patch doesn't fix the problem. 
![2018-10-17_15-52-52](https://user-images.githubusercontent.com/11057128/47087489-ce80c000-d224-11e8-9724-4ddb38152088.png)

`[Wed Oct 17 15:05:56.186933 2018] [:error] [pid 25956] [client 10.1.0.138:53433] PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'The stream or file "/var/www/html/glpi/files/_log/php-errors.log" could not be opened: failed to open stream: Permission denied' in /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107\nStack trace:\n#0 /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\\Handler\\StreamHandler->write(Array)\n#1 /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Logger.php(337): Monolog\\Handler\\AbstractProcessingHandler->handle(Array)\n#2 /var/www/html/glpi/inc/toolbox.class.php(435): Monolog\\Logger->addRecord(400, 'Toolbox::userEr...', Array)\n#3 /var/www/html/glpi/inc/toolbox.class.php(469): Toolbox::log(NULL, 400, Array)\n#4 /var/www/html/glpi/inc/toolbox.class.php(657): Toolbox::logError('  *** PHP Warni...')\n#5 [internal function]: Toolbox::userErrorHandlerNormal(2, 'error_log(/var/...', '/var/www/html/g...', 586, Array)\n#6 /var/www/html/glpi/inc/toolbox.class.php(586): error_log('201 in /var/www/html/glpi/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php on line 107, referer: http://help.invest.ru/front/ticket.php?is_deleted=0&as_map=0&criteria%5B0%5D%5Bfield%5D=12&criteria%5B0%5D%5Bsearchtype%5D=equals&criteria%5B0%5D%5Bvalue%5D=notold&search=%D0%9F%D0%BE%D0%B8%D1%81%D0%BA&itemtype=Ticket&start=0&_glpi_csrf_token=9428aadb4319c1d9a2748c232281717d`

**Comment by vollkommenIrrelevant** [comment]
After Updating PHP from 7.0 to 7.3 and GLPI from 9.4 to 9.5.2 the problem occured again.
