### ISSUE TITLE
Mail solution contains N/A

### ISSUE THREAD

**Issue by InformatiqueOLLN** [glpi-project/glpi#4287]
* Steps to reproduce (which actions have you made) :

Create a ticket and close it.

* Expected result :

The user receiving the e-mail gets the text solution.

* Actual result :

The user receives a "N/A" in solution field

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

[code]
 
GLPI 9.3.0 (/glpi => /var/www/glpi)
Installation mode: TARBALL

Operating system: Linux web 3.2.0-4-amd64 #1 SMP Debian 3.2.41-1 x86_64
PHP 5.6.20-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl,
	ionCube Loader, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix,
	session, shmop, soap, sockets, ssh2, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="512M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache/2.4.10 (Debian) PHP/5.6.20-0+deb8u1 mod_python/3.3.1 Python/2.7.9 OpenSSL/1.0.1t ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Server Software: (Debian)
	Server Version: 5.6.30-1
	Server SQL Mode: 
	Parameters: glpidbuser@xxx.xxx.xxx.xxx/glpidb
	Host info: xxx.xxx.xxx.xxx via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is not present
Database version seems correct (5.6.30) - Perfect!Database version seems correct (5.6.30) - Perfect!
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_cache : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

**Comment by InformatiqueOLLN** [comment]
![image](https://user-images.githubusercontent.com/19569156/42226470-508431f2-7edf-11e8-8e07-7da910414830.png)

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/4266
