### ISSUE TITLE
0.85 and above : Child Entities, tab Notifications, pb with field 'Enable notifs by default'

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#43]
v 0.85.4 & 0.90
refer to topic http://forum.glpi-project.org/viewtopic.php?id=115012 on forum.
In Entities, tab Notifications, of a child entity, when field 'Enable notifs by default' is set to 'Inheritance', an error msg is displayed on screen (at least one field has an incorrect value : Enable notifs by default') every time the form is saved.
Nevertheless, the changes of other fields are correctly saved.
The field 'Enable notifs...' can be modified to Yes/No without error, but cannot be modified back to 'Inheritance'.
It seems that, in inc/entity.class.php, the type of the field 'Enable notifs...' is not correct : bool instead of specific.

**Comment by yllen** [comment]
I have no problem in 0.85.5 svn or in 0.90 beta.
I can change value and go back to inheritance without problem
Which fields are you trying to update?

**Comment by blerohellec** [comment]
I've just retested with an installation from scratch of 0.90 downloaded from the nightly tarball.
The msg appears only for a child entity (I've got one child entity, and a root entity).
The msg appears for any field modified in tab Entity > Notifications, other than 'Enable notifs..'
In db, I've got -2 in glpi_entities.is_notif_enabled_default (and -2 for any field whose value is Inherited on screen)

**Comment by yllen** [comment]
I don't have the field "is_notif_enabled_default" in glpi_entities.
Do you use plugins?

**Comment by blerohellec** [comment]
sorry, the column is named 'is_notif_enable_default' (without a 'd')

**Comment by yllen** [comment]
OK i understand and confirm the bug

**Comment by yllen** [comment]
Correction validated by requester in forum
