### ISSUE TITLE
[9.3]Your database engine version seems too old: 5.5.60.

### ISSUE THREAD

**Issue by major697** [glpi-project/glpi#4304]
Hello I have installed mysql version 5.5.60, but when I want update glpi I have error:

> Your database engine version seems too old: 5.5.60. 

What version of the database should be installed?

In the datasheet is information: 

> We recommand use version 5.5.x (best performances).

**Comment by trasher** [comment]
MySLQ 5.6 / MariDB 10.0. Please use forums for support/questions.
