### ISSUE TITLE
Missing glpi_config table

### ISSUE THREAD

**Issue by Corrano** [glpi-project/glpi#4306]
Hello, I found one problem in the sql-errors.log file and I don't have any idea what can I do. Maybe you have solution for that because it's generate a lot of errors and the size of log files grows very fast :)

As you can see on screen below, table glpi_config is missing but in database I found table with name glpi_configs. I don't know if it's the same table? What and where i should change ? :)

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/39371670/42397242-6664037a-8165-11e8-95f5-b43782eb992a.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.3
php 7.0.25
Ubuntu 16.04.1
Apache 2.4.18
MySQL 5.7.21

**Comment by trasher** [comment]
`glpi_configs` is the right name from a while. Are you upgrading from an older GLPI (and which version)?

Make sure you do not have any `glpi_config` (without final `s`) existing (maybe a crashed or ghost table, dunno).

**Comment by FPAdministrator** [comment]
OK, problem solved, I found in /inc/config.php:128 record like below

![image](https://user-images.githubusercontent.com/7323944/42437195-9ab32ffe-835c-11e8-98ff-ce7cedfc5ea7.png)

I corrected it on  **glpi_configs** and now everything is ok :)

buuut... there is another problem in sql-errors with table glpi_solutions, but now this table realy doesn't exist in database

![image](https://user-images.githubusercontent.com/7323944/42437314-0d41f2f8-835d-11e8-902c-fd04026ab058.png)

**Comment by trasher** [comment]
Please, one issue per ticket. CLosing this one as it's solved.
