### ISSUE TITLE
Notification ticket.solution.description

### ISSUE THREAD

**Issue by Hellden** [glpi-project/glpi#4309]
Hi,

GLPI 9.3

There is a problem with the balise notification ticket.solution.description. The mail received shows N / A and not the solution.

Do you have a workaround ?

Thx

**Comment by roshanroche** [comment]
Duplicate of #4266

**Comment by Hellden** [comment]
Bonjour,

Cette adresse de messagerie n'est plus valide. Merci d'utiliser ma nouvelle adresse: rchapotin@gepy89.fr

Cordialement,
