### ISSUE TITLE
361 tables not migrated to InnoDB engine.

### ISSUE THREAD

**Issue by StbanMc** [glpi-project/glpi#4310]
Server
--
Operating system: Linux us-imm-web124.main-hosting.eu 3.10.0-714.10.2.lve1.5.17.el7.x86_64 #1 SMP Mon Apr 30 13:06:32 EDT 2018 	x86_64 PHP 7.2.5 litespeed (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, 	filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube Loader, json, libxml, litespeed, mbstring, mysqli, 	mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, phalcon, posix, pspell, readline, session, shmop, soap, sockets, sqlite3, 	standard, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="120" memory_limit="256M" post_max_size="128M" safe_mode="" session.save_handler="files" 	upload_max_filesize="128M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.2.15-MariaDB 	Server SQL Mode:  	Parameters: u_glpi 	Host info: mysql.hostinger.com via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed imap extension is installed xmlrpc extension is installed Database version seems correct (10.2.15) - Perfect!

**Comment by StbanMc** [comment]
Update Type, new error:

SQL strict mode is not fully enabled, recommended for development: STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ZERO_DATE,NO_ZERO_IN_DATE,ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER

**Comment by trasher** [comment]
this is not an error, but a message for developpers. It's been removed for next release.
