### ISSUE TITLE
297 tables not migrated to InnoDB engine

### ISSUE THREAD

**Issue by a11g0rhythm** [glpi-project/glpi#4311]
------------
* Steps to reproduce (which actions have you made) :

Upgrade from 9.2.1 to 9.30

* Expected result :
migrated all tables to InnoDB engine ?

* Actual result :
297 tables not migrated to InnoDB engine.

**Comment by trasher** [comment]
InnodDB migration is not part of the standard update, this is expected. Use the provided `scripts/innodb_migration.php` script or any other tool that would permit this change.

**Comment by optik-aper** [comment]
I also wondered about this after doing the upgrade.  Would it make sense to include this info in the warning message?  I can work on a pull request if you'd like.

**Comment by relihschneider** [comment]
i cannot enter to glpi/scripts .. its says You don't have permission to access /glpi/scripts on this server.
i tryed enter to innodb_migration.php but with same error
what can i do?

**Comment by relihschneider** [comment]
> 
> 
> i cannot enter to glpi/scripts .. its says You don't have permission to access /glpi/scripts on this server.
> i tryed enter to innodb_migration.php but with same error
> what can i do?

i was found the solution:
in windows open command , write and replace:
C:\php path\php.exe -f "C:\glpi path\scripts\innodb_migration.php" -- -arg1 -arg2 -arg3

on linux
sudo php /glpi_path/scripts/innodb_migration.php

**Comment by trasher** [comment]
There is no need for `sudo`.

**Comment by Cucala** [comment]
I was looking the script innodb_migration.php and I didn't find in any folder.

Please Can you help me?

**Comment by hackML** [comment]
Para los que buscan información en español para windows, solo van y descargan el siguiente archivo:
https://gitlab.ow2.org/glpi/glpi/blob/a021b318f4fe7e161234029e09c518a27859f70d/scripts/innodb_migration.php

luego lo guardan en la carpeta scripts de glpi ej. C:\xampp\htdocs\glpi\scripts y lo guardan con el nombre "innodb_migration.php"  y luego ejecutan desde la consola de comandos de windows 

C:\ruta donde está el php\php.exe -f "C:\ruta donde se encuentra el glpi\scripts\innodb_migration.php" -- -arg1 -arg2 -arg3

tomando como ejemplo la instalación de glpi que mencioné, la linea a ejecutar quedaría así: 

C:\xampp\php\php.exe -f "C:\xampp\htdocs\glpi\scripts\innodb_migration.php" - -arg1 -arg2 -arg3

 y listo debería funcionar

**Comment by trasher** [comment]
@EstebanB04 https://github.com/glpi-project/glpi/blob/9.4/bugfixes/CONTRIBUTING.md please write only in english.

**Comment by eyasno** [comment]
> Para los que buscan información en español para windows, solo van y descargan el siguiente archivo:
> https://gitlab.ow2.org/glpi/glpi/blob/a021b318f4fe7e161234029e09c518a27859f70d/scripts/innodb_migration.php
> 
> luego lo guardan en la carpeta scripts de glpi ej. C:\xampp\htdocs\glpi\scripts y lo guardan con el nombre "innodb_migration.php" y luego ejecutan desde la consola de comandos de windows
> 
> C:\ruta donde está el php\php.exe -f "C:\ruta donde se encuentra el glpi\scripts\innodb_migration.php" -- -arg1 -arg2 -arg3
> 
> tomando como ejemplo la instalación de glpi que mencioné, la linea a ejecutar quedaría así:
> 
> C:\xampp\php\php.exe -f "C:\xampp\htdocs\glpi\scripts\innodb_migration.php" - -arg1 -arg2 -arg3
> 
> y listo debería funcionar

EstebanB04, thanks you...excellent contribution

**Comment by eyasno** [comment]
**EstebanB04**, thanks you...excellent contribution

**Comment by tikita** [comment]
> 
> https://glpi-install.readthedocs.io/en/latest/command-line.html#from-myisam-to-innodb

Okay, I understand: now, in GLPI 9.5.1, there is no more a script "innodb_migration.php" in the folder scripts.

But because I use a hosted webserver (only via FTP) it seems I can't make the quoted command ("php bin/console glpi:migration:myisam_to_innodb"), or yet - and if so how?

Kind regards, tikita

**Comment by tikita** [comment]
Do I have to write the command

glpi:migration:myisam_to_innodb

somewhere in the file "console" in the folder "bin" with a texteditor?
