### ISSUE TITLE
Attachment lost if ticket template page reloads

### ISSUE THREAD

**Issue by valentindragan** [glpi-project/glpi#4318]
------------
* Steps to reproduce (which actions have you made) :
- Create new ticket
- attach file
- change requester (page reloads keeping all entered data)
OR
- change/select new category
- the file is not attached anymore

* Expected result :
- the file input should automatically remember the file path, for upload, even though the ticket has not been saved yet;

* Actual result :
- there is no file attached in the file section

**Comment by trasher** [comment]
duplicates https://github.com/glpi-project/glpi/issues/4195
