### ISSUE TITLE
[9.3.0] - Problem with import long DN from AD

### ISSUE THREAD

**Issue by dilona** [glpi-project/glpi#4319]
Hi! 
Software: GLPI 9.3.0, php7.0, mysql 5.7.22, Ubuntu 16.04

![image](https://user-images.githubusercontent.com/31918974/42450152-dbc3547c-838b-11e8-8e3a-ed40fd4f7bbe.png)

After upgrade from 9.2.3 to 9.3.0 (with InnoDB migration) we have a problem with users from AD with long DN (>155 character), like:
'_CN=Тест Тестов Тестович,OU=Отдел 337,OU=_some russian text_,DC=xxxx,DC=xxx,DC=xxx,DC=xx_'
In the glpi database, the full DN in the 'user_dn' field is truncated  to:
'_CN=Тест Тестов Тестович,OU=Отдел 337,OU=_some russian text_,DC=xxxx,DC=xxx,DC=xxx_'

![image](https://user-images.githubusercontent.com/31918974/42451761-d3f57edc-8390-11e8-90fb-57bdd3b81c49.png)

As a result, when you login, a message appears:
![image](https://user-images.githubusercontent.com/31918974/42450852-32f86a96-838e-11e8-93da-b812766e2ede.png)
If I do a new import (with such long DN), the problem remains.
In previous versions, no problem with long DN.

**Comment by dilona** [comment]
Note: after manualy update problem was fixed: 
`mysql> update glpi_users set user_dn = 'CN=Тест Тестов Тестович,OU=Отдел 337,OU=some russian text,DC=xxxx,DC=xxx,DC=xxx,DC=xx' where name="test337";`
But with force synchronization user DN truncated again:
![image](https://user-images.githubusercontent.com/31918974/42454590-8f875e52-8398-11e8-84d0-e35a863710a2.png)

**Comment by trasher** [comment]
I've just added a test that import an synchronize a LDAP user with a dn of 186 characters length; and I cannot reproduce (see https://github.com/glpi-project/glpi/pull/4344).
I do not have any way to test on AD, but there does not seems to have any limitations; so this is probably a configuration or environment issue.

**Comment by dilona** [comment]
We created and imported LDAP user with dn length of 224 characters (dn in English) and there were no problems. 
![image](https://user-images.githubusercontent.com/31918974/42761168-6a0d8610-8915-11e8-905d-d7af5ef062d4.png)
![image](https://user-images.githubusercontent.com/31918974/42761235-99765f62-8915-11e8-81ac-06e0ff93d55e.png)

Can you try to reproduce it with the Cyrillic characters? Seems like a problem with that.

For Example (cyrillic with spaces): DN = 'CN=Тестов Тест Тестович,OU=Отдел Тест,OU=Управление с очень очень длинным названием даже сложно запомнить насколько оно длинное и еле влезает в экран№123,DC=example,DC=com,DC=ru'

**Comment by dilona** [comment]
I turned on MySQL query log , and see that UPDATE queries is truncated. It seems truncated in php processing.

**Comment by trasher** [comment]
Just tested with provided data: tests fails, see https://travis-ci.org/glpi-project/glpi/jobs/404465068#L707

But: this fails because string is over 255 characters, not 15(; and this does not work on 9.2 (see https://travis-ci.org/trasher/glpi/jobs/404477010#L818)

**Comment by trasher** [comment]
Here is the fix: https://github.com/glpi-project/glpi/pull/4344/files#diff-a9c4448deb6265f035355e2a9ca92bc0R3007
