### ISSUE TITLE
Business rules for "changes"

### ISSUE THREAD

**Issue by carlosamoura** [glpi-project/glpi#432]
The business rules for tickets works reasonably well for manipulating tickets, but there seems to be no ability to apply any rules for "changes."  We would like to auto assign approvers and "minimum approval" settings for Change requests etc.

Helpe me please. :-)

**Comment by orthagh** [comment]
Hello @carlosamoura 

Thanks for your suggestion.
It's a big work to do that feature and we have no plan to work on for the moment (lack of time).
You can redo this text on http://suggest.glpi-project.org for tracking (and voting).

I close now, but if this features becomes popular or if we have a contribution, we can reopen
