### ISSUE TITLE
REST API : Cannot get data from plugins (Tags for example)

### ISSUE THREAD

**Issue by cadegenn** [glpi-project/glpi#4327]
Hi,

I try to get data from plugin "Tags" via glpi REST API and I can't seem to succeed.
So I wonder : are plugins data available throught GLPI REST API ?
What I try to do is query for a computer Item which I known his ID to get all available data, including the tags associated.

* Steps to reproduce (which actions have you made) :
http request https://glpi.domain.com/glpi/apirest.php/Computer/${id} with a valid Session-Token

* Expected result :
return all data related to this computer, including data from plugins

* Actual result :
return "official" glpi data only

* URL of the page :
https://glpi.domain.com/glpi/apirest.php/Computer/${id}

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.3 Copyright (C) 2015-2018 Teclib' and contributors - Copyright (C) 2003-2015 INDEPNET Development Team
FusionInventory 9.2+2.0 - Copyleft © 2010-2017 by FusionInventory Team
Plugins : 
fusioninventory      Name: FusionInventory                Version: 9.2+2.0    State: Enabled
tag                  Name: Gestion des tags               Version: 2.1.1      State: Enabled
manufacturersimports Name: Imports fabricants             Version: 2.0.0      State: New
ocsinventoryng       Name: OCS Inventory NG               Version: 1.4.3      State: Enabled
mreporting           Name: Plus de rapports               Version: 1.4.0      State: Enabled

Thank you for the great job.

**Comment by sebeka** [comment]
Hi,

we need this too!
We would like to read and write values from additional fields plugin.
At the moment only item "PluginFieldsContainer" is possible, but the output is not very useful:

    [0] => stdClass Object
        (   
            [id] => 1
            [name] => testblockfornewfield
            [label] => Additional in Computers
            [itemtypes] => ["Computer"]
            [type] => dom
            [subtype] =>
            [entities_id] => 0
            [is_recursive] => 0
            [is_active] => 1
            [links] => Array
                (   
                    [0] => stdClass Object
                        (   
                            [rel] => Entity
                            [href] => https://glpi.area56.rz.uni-mannheim.de/apirest.php/Entity/0
                        )

                )

        )

Maybe a starting point would be to inject some (dynamic?) plugin classes in apirest, to fulfill the requirements in "getItemtype":


      private function getItemtype($index = 0, $recursive = true, $all_assets = false) {

      if (isset($this->url_elements[$index])) {
         if ((class_exists($this->url_elements[$index])
              && is_subclass_of($this->url_elements[$index], 'CommonDBTM'))
             || ($all_assets
                 && $this->url_elements[$index] == "AllAssets")) {
            $itemtype = $this->url_elements[$index];

Thanks for the great tool! Hope work is ongoing well

Sebastian

**Comment by sebeka** [comment]
Related to: https://github.com/glpi-project/glpi/issues/1154

**Comment by orthagh** [comment]
tag and fields plugins data are available through rest api.

itemtypes to use:
 - PluginTagTagItem
 - for fields, check the folder: files/_plugins/fields/inc/ and the class files into it, you'll find the iemtype to use (the classname).
