### ISSUE TITLE
Satisfaction survey showing in central

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#433]
http://forum.glpi-project.org/viewtopic.php?id=148480

**Comment by wawax** [comment]
Please also check this suggestion : http://glpi.userecho.com/topics/78-satisfaction-survey/

**Comment by yllen** [comment]
right added to allow or not reply by a technician https://github.com/glpi-project/glpi/commit/3763ccb81583610de3706861abb9c56e8ac42921
