### ISSUE TITLE
Referrer-Policy "strict-origin" breaks save action

### ISSUE THREAD

**Issue by daniejstriata** [glpi-project/glpi#4333]
In hardening the GLPI install I added a Referrer-Policy based on recommendations.

* Steps to reproduce (which actions have you made) :
Enable a new Header  in Apache 

> Header always set Referrer-Policy "strict-origin"

* Expected result :
Website to GLPI should work as normal. It usually does for most action except when clicking on any save button. Doing so takes you back to the GLPI home page.
Nothing gives any errors except that when you click save you're taken to the home page rather than staying on the page you already are on.

* Version:
GLPI 9.2.4

**Comment by orthagh** [comment]
Hello.

If you want to add this header, it need to keep path in referer header send to php.
`strict-origin` doesn't do that.

So i suggest you to use `same-origin` value.

By the way, we have a mecanism in glpi to check referer, so i think it's superflu to add this header.
And moreover, it's this mecanism that fails with `Referer-Policy` set to `strict-origin`

See code for the behavior:

https://github.com/glpi-project/glpi/blob/9.3.0/inc/toolbox.class.php?utf8=%E2%9C%93#L2469-L2513
