### ISSUE TITLE
Content-Security-Policy breaks some pages

### ISSUE THREAD

**Issue by daniejstriata** [glpi-project/glpi#4334]
I added a very generic Content-Security-Policy rule
* Steps to reproduce (which actions have you made) :
Added to Apache
 `Header always set Content-Security-Policy "default-src 'self';"`

* Expected result :
GLPI pages should work like normal.

* Actual result :
Experience a couple of pages breaking. Specifically pages like the *.form.php pages.

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/13314239/42631214-c50b0504-85d9-11e8-848e-8932c5aa4318.png)

![image](https://user-images.githubusercontent.com/13314239/42631236-daf79936-85d9-11e8-976d-9235e1e883a1.png)

* Version:
` GLPI 9.2.4`

**Comment by daniejstriata** [comment]
Implemented the following header to fix issue:

Header always set Content-Security-Policy "connect-src 'self'; default-src 'none'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self'; img-src 'self' data:; "

Recommend that unsafe_eval be removed and nonce.

**Comment by orthagh** [comment]
which GLPI page did you encouter an eval statement (or maybe an error for unsafe-eval) ?

**Comment by orthagh** [comment]
Ok after some checks. It's very too early for glpi to add nonce attributes (and enforces CSP).
Too much inline scripts mainly.

We will see after review of UI code (twig usage).

**Comment by joel-edf** [comment]
Any news on that? Is GLPI now more ready to become CSP compliant?
Thanks for any update!

**Comment by cedric-anne** [comment]
There are still many inline scripts in GLPI. CSP support has been added to the technical backlog, but it will not be possible to do it in a near future because it requires too many changes, in both GLPI and the plugins.

**Comment by joel-edf** [comment]
Thanks for the update! 
If there is an open request on GitHub to track that, I have not seen it. 
Can you point me to it? If not it's fine too.

**Comment by cedric-anne** [comment]
Task is tracked in a private project.
