### ISSUE TITLE
Automatic action, planning recall, action in error state

### ISSUE THREAD

**Issue by troublestarter** [glpi-project/glpi#4335]
* Steps to reproduce (which actions have you made) :
don't know

* Expected result :
don't know

* Actual result :
A mail is sent : Automatic action monitoring, automatic actions in error state

* URL of the page :
an url in the mail : https://xxxxxxxxxxxxxxxxxxx/front/crontask.form.php?id=26&

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/6012203/42634934-f1a284ba-85e4-11e8-9f82-3d2aa1db6097.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Operating system: Linux support 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64
PHP 5.6.30-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at support.my-cosi.info Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Server Software: (Debian)
	Server Version: 5.5.55-0+deb8u1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_cache : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
OK/usr/share/glpi/files/_log : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed)
phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.17 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

Plugins list
--
news                 Name: Alertes                        Version: 1.3.5      State: Enabled 	arsurveys            Name: AR Surveys                     Version: 1.4.1      State: Not activated 	behaviors            Name: Comportements                  Version: 2.0.0      State: Not activated 	formcreator          Name: Formulaires                    Version: 2.5.0      State: Not activated 	purgelogs            Name: Purge de l'historique          Version: 1.3.0      State: Enabled 	dashboard            Name: Tableau de bord                Version: 0.9.2      State: Enabled

**Comment by troublestarter** [comment]
Wich logs ?

**Comment by troublestarter** [comment]
no log in task
![image](https://user-images.githubusercontent.com/6012203/42636197-6f512b52-85e8-11e8-8fa7-ed83a330752c.png)

**Comment by trasher** [comment]
Logs in files/_log/php-errors.log, files/_log/sql-errors.log; php system error log, etc

**Comment by troublestarter** [comment]
2018-06-22 19:41:47 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/datainjection/setup.php:89                 _e()
  inc/plugin.class.php:624                           plugin_datainjection_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
2018-06-22 19:41:50 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  _e() method is deprecated
2018-06-22 19:41:50 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/datainjection/setup.php:89                 _e()
  inc/plugin.class.php:624                           plugin_datainjection_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
2018-06-22 19:41:58 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  TableExists() function is deprecated
2018-06-22 19:41:58 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:41:58 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.004", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:41:58 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:41:58 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.004", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:41:58 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:41:58 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.003", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:41:58 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:41:58 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.003", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:41:58 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:41:58 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.002", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:41:58 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:00 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  _e() method is deprecated
2018-06-22 19:42:00 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/datainjection/setup.php:89                 _e()
  inc/plugin.class.php:547                           plugin_datainjection_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
2018-06-22 19:42:06 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  _e() method is deprecated
2018-06-22 19:42:06 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/datainjection/setup.php:89                 _e()
  inc/plugin.class.php:547                           plugin_datainjection_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  TableExists() function is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.004", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.003", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.003", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.004", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.004", 2.36Mio)
  TableExists() function is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/db.function.php:549                            Toolbox::deprecated()
  plugins/datainjection/hook.php:183                 TableExists()
  inc/plugin.class.php:685                           plugin_datainjection_uninstall()
  :                                                  Plugin->uninstall()
  front/plugin.form.php:48                           call_user_func()
2018-06-22 19:42:09 [9@support]
  From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486
  _e() method is deprecated
2018-06-22 19:42:09 [9@support]
  Backtrace :
  inc/toolbox.class.php:487                          Toolbox::backtrace()
  inc/autoload.function.php:168                      Toolbox::deprecated()
  plugins/datainjection/setup.php:89                 _e()
  inc/plugin.class.php:547                           plugin_datainjection_check_prerequisites()
  front/plugin.php:95                                Plugin->listPlugins()
Test

**Comment by troublestarter** [comment]
[php-errors.zip](https://github.com/glpi-project/glpi/files/2188863/php-errors.zip)
