### ISSUE TITLE
Enclosure items dropdown list

### ISSUE THREAD

**Issue by MrRobbi** [glpi-project/glpi#4338]
* Steps to reproduce (which actions have you made) :

Set language to polish.
Add new rack A.
Add new enclosure B.
Add new computer C.
Put enc B into rack A.
In enc B: Items -> Add new item to this enclosure -> Item type "Computer"

* Expected result :
See item dropdown list with computer C.

* Actual result :
Lack of dropdown list with computer items.
If you set language to english it works as expected.

* URL of the page :
/front/item_enclosure.form.php

* Screenshot of the problem (if pertinent) :
![encdropdown](https://user-images.githubusercontent.com/35692596/42657610-03c46d50-8623-11e8-9ba1-b1dc902106cd.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.0, PHP 7, all extensions installed

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/4283
