### ISSUE TITLE
Create a ticket using python requests

### ISSUE THREAD

**Issue by glowsub** [glpi-project/glpi#4340]
Hi guys, I'm tryung to create a ticket in GLPI, using python requests. My code:
```
from glpi import GLPI
import requests
url = 'https://hd.integrasky.ru/apirest.php/initSession'
auth = ('username', 'password')
headers = {'App-Token': 'token',
           'Content-Type': 'application/json'}
requests.get(url, auth=auth, headers=headers)
payload = {'input': {'name': 'Проблема', 'content': 'Не работает компьютер', 'entities_id': 29}}
requests.post('http://hd.integrasky.ru/apirest.php/Ticket', json=payload)
```
But the ticket is not creating, and there is no exception in my script. 
`Process finished with exit code 0`
What I'm doing wrong? Someone can help me?
And should I use encoding to utf-8 to russian text?

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) for help requests.
