### ISSUE TITLE
Elements not appearing in ticket view

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#4341]
* Steps to reproduce (which actions have you made) :
Create a ticket and associate an element, such as a computer asset.

* Expected result :
Users/technicians should be able to view the ticket and see/edit the associated elements

* Actual result :
When viewing created ticket, the associated elements are hidden to everyone, even those users who have no default ticket template against their profile.

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/16598973/42733044-1044548a-8823-11e8-9bb1-e0fe493604aa.png)
![image](https://user-images.githubusercontent.com/16598973/42733117-fab8a26e-8823-11e8-829a-e3d722540916.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
CentOS 6
GLPI 9.3.0
PHP 5.6.36

This happens even if the GLPI administrator creates and views the ticket (which uses no default ticket templates)

**Comment by hgpit** [comment]
The associated elements appear in the ticket list by the way:
![image](https://user-images.githubusercontent.com/16598973/42734068-7883611e-8835-11e8-84ff-5d1f41ff372f.png)

**Comment by trasher** [comment]
You can find them in the "Items" of the ticket.
