### ISSUE TITLE
Bad model type for new model for other component

### ISSUE THREAD

**Issue by maxxenceg** [glpi-project/glpi#4342]
* Steps to reproduce (which actions have you made) :
When adding a new model for a new other component, it indicates "network card model" instead of "other component model"

* Expected result :
"other component model" wich new name is to save in _glpi_devicepcimodels_ table 

* Actual result :
 "network card model" wich new name is saving in _glpi_devicenetworkcardmodels_ table

* URL of the page :
From page "front/device.form.php?itemtype=DevicePci", click on "Add model" (plus button)

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/41270264/42737393-c92a375e-8872-11e8-86c2-8c5ae5c5e43e.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
[code]   GLPI 9.3.0 (/glpi/prod => /data/applis/glpi/9.3.0) Installation mode: TARBALL

Operating system: Linux aragorn-T901 4.13.0-45-generic #50~16.04.1-Ubuntu SMP Wed May 30 11:18:27 UTC 2018 x86_64 PHP 7.0.30-0ubuntu0.16.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_dblib, pdo_mysql, posix, readline, session, shmop, soap, sockets, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="15M" safe_mode="" session.save_handler="files" 	upload_max_filesize="15M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at localhost Port 80) 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.22-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (5.7.22) - Perfect! /data/applis/glpi/9.3.0/config : OK /data/applis/glpi/9.3.0/files : OK /data/applis/glpi/9.3.0/files/_dumps : OK /data/applis/glpi/9.3.0/files/_sessions : OK /data/applis/glpi/9.3.0/files/_cron : OK /data/applis/glpi/9.3.0/files/_graphs : OK /data/applis/glpi/9.3.0/files/_lock : OK /data/applis/glpi/9.3.0/files/_plugins : OK /data/applis/glpi/9.3.0/files/_tmp : OK /data/applis/glpi/9.3.0/files/_cache : OK /data/applis/glpi/9.3.0/files/_rss : OK /data/applis/glpi/9.3.0/files/_uploads : OK /data/applis/glpi/9.3.0/files/_pictures : OK /data/applis/glpi/9.3.0/files/_log : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/data/applis/glpi/9.3.0/lib/htmlawed) SimplePie version 1.5.1 in (/data/applis/glpi/9.3.0/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/data/applis/glpi/9.3.0/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/data/applis/glpi/9.3.0/vendor/michelf/php-markdown/Michelf) true/punycode in (/data/applis/glpi/9.3.0/vendor/true/punycode/src) iacaml/autolink in (/data/applis/glpi/9.3.0/vendor/iamcal/lib_autolink) sabre/vobject in (/data/applis/glpi/9.3.0/vendor/sabre/vobject/lib) phpCas version 1.3.3 in (/usr/share/php)

Not active

Way of sending emails: PHP

 

timelineticket       Name: Chronologie des tickets        Version: 9.2+1.0    State: Not installed 	consumables          Name: Demande de consommables        Version: 1.3.1      State: Not installed 	escalade             Name: Escalades                      Version: 2.2.2      State: Not installed 	formcreator          Name: Formulaires                    Version: 2.6.3      State: Not installed 	genericobject        Name: Gestion d'objets               Version: 2.5.1      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.4.0      State: Not installed 	surveyticket         Name: Questionnaire                  Version: 9.2+1.1    State: Not installed 	reports              Name: Rapports                       Version: 1.11.3     State: Not installed 	reservation          Name: Reservation                    Version: 2.0.0      State: Not installed 	webservices          Name: Services Web                   Version: 1.8.0      State: Not installed 	dashboard            Name: Tableau de bord                Version: 0.9.2      State: Not installed
[/code]

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/4259
