### ISSUE TITLE
Broken Image in solution notification

### ISSUE THREAD

**Issue by BlueCatBlog** [glpi-project/glpi#4345]
No issue with followup and new ticket description.

1. Steps to reproduce (which actions have you made) :
- Apply bugfix: https://github.com/glpi-project/glpi/pull/4272 to solve "N/A" in solution notification.
- Add a picture inside a solution
![image](https://user-images.githubusercontent.com/16157801/42763590-cb1ac3e8-8913-11e8-942e-9284de46b1a4.png)

2. Expected result :
- Picture is displayed in the mail

3. Actual result :
- A broken tag is displayed: impossible to show picture
![image](https://user-images.githubusercontent.com/16157801/42763600-d4bcd31e-8913-11e8-830e-ac7f21a930d3.png)

4. Your GLPI setup (you can find it in Setup > General menu, System tab) :
9.3.0

**Comment by ppenin** [comment]
Same issue for us after applying bugfix: #4272 to solve "N/A" in solution notification.

**Comment by ppenin** [comment]
Obviously, e-mail notifications issues do not interest many people ... So sad !

**Comment by BlueCatBlog** [comment]
Yeah :(
But our users enjoy very much to have a complete solution with picture inside notifications, I had to add a follow up with picture before add a solution. 

Hope and wait for a quick fix :)

**Comment by trasher** [comment]
@BlueCatBlog @ppenin please test provided solution https://github.com/glpi-project/glpi/pull/4401.

**Comment by BlueCatBlog** [comment]
Hello, 

Thank you for your interest and the quick fix.

It works inside Office Outlook and Outlook iOS but not inside Outlook Web Apps, it's strange but it seems a bigger issue than the current issue because image in followup are broken too inside OWA and not inside Office Outlook or Outlook iOS.
![image](https://user-images.githubusercontent.com/16157801/43327187-08483dea-91bb-11e8-802e-dab7b6f284b2.png)

Thank for the fix, I will look if an other issue exist for Web Client and its broader image issue.

**Comment by ppenin** [comment]
I tested the fix and same conclusion - Ok with Outlook but not ok with Outlook Web App
By the Way, addind a picture in a solution stucks queuednotification task.

**Comment by cedric-anne** [comment]
@BlueCatBlog @ppenin 

I added some commits to the PR #4401. Could you validate the fix ?

Regards

**Comment by ppenin** [comment]
Test made with the fix #4401 (those files replaced
notificationtargetchange.class.php
notificationtargetcommonitilobject.class.php
notificationtargetproblem.class.php
notificationtargetticket.class.php
notificationtemplate.class.php)
ok with solution in Outlook 2013 Client but not ok with Outlook Web App.
A bit complicated to do further tests till 20th August. I'm on holiday. 

Outlook Client
![image](https://user-images.githubusercontent.com/22499638/43468122-79e068da-94e3-11e8-8eda-2c5a48db2354.png)


OWA
![image](https://user-images.githubusercontent.com/22499638/43468085-680c790a-94e3-11e8-8320-c6739ab6ec0f.png)

**Comment by cedric-anne** [comment]
Hi,

I created a specific issue for OWA (#4421). Other problems are fixed by #4401.

Regards

**Comment by cedric-anne** [comment]
Hi @ppenin ,

Could you take a look at #4834 and respond in #4421 if fix is OK ?

Regards
