### ISSUE TITLE
network equipements / network ports : sort order

### ISSUE THREAD

**Issue by Rico29** [glpi-project/glpi#4347]
In network equipements / network ports, switch ports are "string" sorted : 
1
10
11
12
...
2
20
21
22
...
3
30
31...

Expected result :
1
2
3

* URL of the page :
https://glpi.celya.fr/front/networkequipment.form.php?id=2

* Screenshot of the problem (if pertinent) :
![selection_017](https://user-images.githubusercontent.com/12935571/42799511-6a96eac6-8998-11e8-94fb-989108c0daea.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.3.1-git-9.3/bugfixes-c4ea7747b ( => /usr/share/glpi_9.3)
Installation mode: GIT

**Comment by trasher** [comment]
As discussed on IRC, this issue is related to fusion usage. When you add several ports in GLPI, order is correct.
