### ISSUE TITLE
automatic ticket transfer rule

### ISSUE THREAD

**Issue by klodnitsky** [glpi-project/glpi#435]
Here is a good feature
Business rule to transfer tickets between entities. (new action - move to entity...)

[http://forum.glpi-project.org/viewtopic.php?id=36021](url)

**Comment by tomolimo** [comment]
Could you post new feature request here: http://glpi.userecho.com/ ?

**Comment by klodnitsky** [comment]
okay, here it is
[http://glpi.userecho.com/topics/222-/](url)

**Comment by tomolimo** [comment]
Yes, I saw and already vote for it ☺

Olivier MORON
GLPI Development

RAYNET SAS
Tel : +33 476 33 4952
Fax: +33 4 76 70 56 63

**Comment by orthagh** [comment]
Thank you for your suggestion, I close here
