### ISSUE TITLE
[Question] [GLPI 9.3] Associated items on Main View

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#4356]
Hello,

I'm currently testing 9.3 before to upgrade.

Is it normal in 9.3 that associated items are missing from ticket main view in "Vertical Split" layout (same thing with other layout)? Screen capture below are on the same ticket. First on GLPI 9.3 and second on GLPI 9.1.6

GLPI 9.3 : 
![2018-07-18_07h43_22](https://user-images.githubusercontent.com/16323410/42862092-551d464c-8a5e-11e8-8595-82dfdddbdc7e.png)

GLPI 9.1.6 : 
![2018-07-18_07h45_23](https://user-images.githubusercontent.com/16323410/42862192-c10625c2-8a5e-11e8-918b-bcff3533bbad.png)

Thanks for your feedback

**Comment by trasher** [comment]
This was not maintainable, and causes many issues; so it's been dropped.
Associated items are on their own tab.
