### ISSUE TITLE
Add a new date to store item creation

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#436]
Add a new date in database to store when an item has been created.
It then helps to query all assets being created today, or five weeks ago for example

**Comment by yllen** [comment]
Budget : date de dernière mise à jour décalée à droite au lieu d'être sous le commentaire

**Comment by yllen** [comment]
Cartridgeitem :+1: *** PHP Notice(8): Undefined index: colspan
  Backtrace :
  inc/commondbtm.class.php:1968                      
  inc/cartridgeitem.class.php:248                    CommonDBTM->showDates()
  inc/commonglpi.class.php:464                       CartridgeItem->showForm()
  ajax/common.tabs.php:94                            CommonGLPI::displayStandardTab()

**Comment by yllen** [comment]
Computer : pourquoi tu as supprimé l'information que le computer était créé depuis un gabarit ?

**Comment by wawax** [comment]
@yllen I've refactorized the "created from the template xxx" in the new function to display dates. It's now managed at one place, and not in each item.

I've fixed the other issues that you've reported. Thanks for that

**Comment by yllen** [comment]
It seams OK for me

**Comment by yllen** [comment]
For Monitor, Printer, Software, Phone, Last update in not under Comments
