### ISSUE TITLE
[9.2.3] Tickets from mailgate don't send notifications to requester

### ISSUE THREAD

**Issue by pxlcore** [glpi-project/glpi#4362]
* **Steps to reproduce** (which actions have you made) :
Sending a ticket to the mailcollector mailbox.

* **Expected result** :
Mail will be collected by the mailgate job (configured as CLI) and a ticket will be created inside GLPI.
Notifications (new ticket, ticket solved) should be sent to all defined recipients.

![grafik](https://user-images.githubusercontent.com/198268/42922917-2f645042-8b23-11e8-94fc-8e707b444856.png)

* **Actual result** :
No notifications are sent to the requester.
All notifications are sent to the GLPI administrator.
Inside the `mail.log` you can see the entries for the administrator mail, but no entry for the requester mail.
If the same requester is _creating a ticket inside the browser in GLPI_, he gets all notifications!

* **Your GLPI setup** (you can find it in Setup > General menu, System tab) :
```
GLPI 9.2.3 ( => /home/helpdesk/htdocs) Installation mode: TARBALL
```

**Comment by orthagh** [comment]
Could you check the requester want to receive notification for it's own events.

![image](https://user-images.githubusercontent.com/418844/42933911-3f32aa28-8b46-11e8-9e05-c015d8c2d5cb.png)

**Comment by Phorms** [comment]
Hi pxlcore,
maybe I had the same problem (several months), but only rarely.

Today I found my problem. Basically GLPI seem to send only notifications to users and tickets of the same entity. If the user and ticket entity does not match, no notification will be send.

A rule moved ticket to a certain entity and if the user has no right in this entity, then he will get no notification even though he is still connected to the ticket.

Maybe this helps and maybe it is a bug.

**Comment by pxlcore** [comment]
Hi Phorms,

you are right. I've tested it the way you said. It worked!
The solution for me was to create rules which assign the right entity to the tickets.

It's not really a bug but you have to know this ...

Thank you.

pxlcore
