### ISSUE TITLE
[enchancement] Improve 

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#4363]
* Steps to reproduce (which actions have you made) :
Try to create a Content forbidden email in the page blacklistedmailcontent.form.php

* Expected result :
We should be able to create a forbidden content using regex instead of only words

* Actual result :
You can create the forbidden content only with words

* URL of the page :
blacklistedmailcontent.form.php

* Screenshot of the problem (if pertinent) :

**Comment by orthagh** [comment]
Hello @lolokai :)

See existing plugin: http://plugins.glpi-project.org/#/plugin/ticketcleaner

Or if you want in core: 
- add an entry in suggest.glpi-project.org
- or open a ticket for quotation on GLPI network as usual

**Comment by lolokai** [comment]
This plugin is not compatible with GLPI 9.2 and GLPI 9.3

**Comment by orthagh** [comment]
Yes I know, i don't know if @tomolimo plan to migrate it.

I closed this issue, because we track feature suggestion on http://suggest.glpi-project.org
