### ISSUE TITLE
Mail received even if Notify for my changes is not activated when Anonymous ticket creation is activated

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#4366]
* Steps to reproduce (which actions have you made) :
Activate anonymous ticket creation
Desactivate Notify for my changes (personal and general options)
Try to add a followup using web interface or using mail collector

* Expected result :
Your user should not receive a notification

* Actual result :
The user who created the followup receive a notification

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.2.4

**Comment by orthagh** [comment]
i'm loss: https://github.com/glpi-project/glpi/issues/4362

**Comment by cedric-anne** [comment]
Hi,

Same as #4643. I close this one as #4643 is more descriptive.

Regards
