### ISSUE TITLE
Unable to handle users picture file through API Rest

### ISSUE THREAD

**Issue by DIOHz0r** [glpi-project/glpi#4370]
* Steps to reproduce (which actions have you made) :
The API Rest needs some improvement for this cases and possible for other ones. 

1.- When we get the user endpoint with getAnItem the result shows the file name of the picture and we need to show the file on another website, however there is no way to get the file using a direct URL like http://my.glpi.ext/files/_pictures/dir/file.ext because a restriction of a .htaccess and there isn't another endpoints to read the file and show it on another platform.

2.- If we want to update the picture to the user using the API sending a file there aren't any way to do it for the following reasons, the logic for update the picture is on "prepareInputForUpdate" method of User class, that implies that to use the API the info should send via HTTP PUT, but RFC 2616 indicates that this verb "directly complements GET" meaning that sending a file is no viable because the $_FILE variable is not populated by default on PHP, therefore to populate the $_FILE variable the files must be sent via HTTP POST but using that verb on the API is for create a new item, and for populate $_FILE using PUT you have to read the body content (http://php.net/manual/en/features.file-upload.put-method.php) and your code doesn't do it at this moment.

* Expected result :
Been able to get and update the user picture file using the API Rest through the User endpoint or another new special one.

* Actual result :
There is no way to get the picture file and update the file to update it through your API Rest

**Comment by orthagh** [comment]
see #2545, it seems @btry did a way for your project to handle user picture upload with rest api.
I don't know if he have any example to show you

**Comment by orthagh** [comment]
if it's ok for you (and @btry), we'll close this issue (let me know).

By the way, adding an example in https://github.com/glpi-project/glpi/blob/9.3/bugfixes/apirest.md#special-cases could be a real enhancement.

**Comment by btry** [comment]
hi

Not sure we should close  this issue. Actually we can upload a file to GLPI, but it is saved as a document. For user avatar, we don't want save the file as a document, right ? In such case, the current upload endpoint does not fits this specific need.

**Comment by orthagh** [comment]
See #2545 title... it's your work :D

**Comment by btry** [comment]
well ... the title is incomplete. I have the answer in the description :D 

then OK to close.

**Comment by orthagh** [comment]
Still:

> By the way, adding an example in https://github.com/glpi-project/glpi/blob/9.3/bugfixes/apirest.md#special-cases could be a real enhancement.

**Comment by btry** [comment]
Yes, I took note. We may create a dedicated issue
