### ISSUE TITLE
[9.3.1] Difference between Map & search for objects

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#4374]
* Steps to reproduce (which actions have you made) :

When you display number of tickets by location on map, the link which list tickets show not the same number

* URL of the page :

/front/ticket.php

* Screenshot of the problem (if pertinent) :

From map

![image](https://user-images.githubusercontent.com/13178158/43003778-eadfe4b6-8c2d-11e8-887b-1e6a2550cc93.png)

After click on link

![image](https://user-images.githubusercontent.com/13178158/43003810-03222dea-8c2e-11e8-8501-7d42ec111e0e.png)

To resolve this : 
Into search.class.php into showMap function : 

I add 2 parameters : 
```
$params['start']      = 0;
$params['list_limit'] = 999999;
```

**Comment by trasher** [comment]
Can't see images from where I am currently.

But as far as I understand, this is not a good idea; parameters you're talking about are used for pagination. We cannot have any pagination on map view, but we do not want to display all tickets at once in standard view.

So, I do no agree with that change.

**Comment by trasher** [comment]
I'm not sure this is a pagination issue. You expect to see 13 and see only 8; with a pagination of 20 per default. 
I can reproduce on the current demo with "location 0": it displays 11 tickets in the map popup, but 19 following the link.

**Comment by trasher** [comment]
Ok; I see... 11 items are displayed for one location, but total number of tickets loaded for all locations is 20
