### ISSUE TITLE
Please add support PostgreSQL for glpi

### ISSUE THREAD

**Issue by patsevanton** [glpi-project/glpi#4379]
Hello, 

PostgreSQL is the world's most advanced open source database
Please add support PostgreSQL for glpi

Thanks.

**Comment by trasher** [comment]
See https://glpi.userecho.com/communities/1/topics/119-postgresql-compatibility

**Comment by patsevanton** [comment]
Yes, but I didn't find the answer there (or didn't understand the text)

**Comment by Armin83** [comment]
https://glpi.userecho.com is the user wish list.
At the moment this it not a feature from glpi. BUT The devoloper think about it to do this into core because the feature request on (https://glpi.userecho.com/communities/1/topics/119-postgresql-compatibility) got the state under review
