### ISSUE TITLE
issue with loading assigned technician 

### ISSUE THREAD

**Issue by moalkaabi** [glpi-project/glpi#4381]
Hi ,
I'm facing issue with glpi 3.9 as I dont face this issue in old version .
I'm not able to assign the ticket to a technician user as the list is not displayed and it says the list cant be loaded 

![image](https://user-images.githubusercontent.com/8044942/43123340-ef370d0a-8f34-11e8-8fb4-5a724a351229.png)

then the server will be crashed .

can you please help , from the logs I'm not able to see any issue. 
it seems that there is profile issue or ldap issue . 

please help me in fixing the issue

regards,

**Comment by trasher** [comment]
LDAP is ont involed displaying this list. There must be an error, if not in glpi/system logs, then check brwiser errors from development tools.

**Comment by moalkaabi** [comment]
yes  I found the issue that many users have duplication profile of Self service . I have removed all users from self service profile and its working fine now . but when GLPI syncing the users , I have same issue again. it creates many of self service profile for one user .

I have not changed anything , I just upgrade glpi from 9.2.4 to 9.3.

**Comment by trasher** [comment]
So your issue is absolutely not what you described in the ticket; but a sync one.

There are already several tickets talking about syncing, please check.

**Comment by trasher** [comment]
Closing this one since there described bug does not exists

**Comment by moalkaabi** [comment]
I have not seen any issue similar to my issue !! syncing users creates duplicates profiles as shown in the image below

![image](https://user-images.githubusercontent.com/8044942/43243596-6f220cb6-90b8-11e8-862f-6becd2405ffe.png)
