### ISSUE TITLE
Creating Line operators without country code and network code

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#4383]
When trying this, nothing happens.

Expected that the operator will be created or an error message will be displayed.
mandatory fields should be marked.

Most providers operate in different countries and with different network codes.

Best,
meg

**Comment by trasher** [comment]
You can create a line operator without those codes, they'll be set to 0 per default.

What you cannot do (and there is indeed no message about that) is to have those codes duplicated among 2 operators. SQL talks about duplicated key in table.
