### ISSUE TITLE
[9.3.0] - API initSession -> ERROR_LOGIN_PARAMETERS_MISSING

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi#4386]
Hello,

on 9.3.0 I am not able to connect trough the API. If I would like to init a new session I got always the error ERROR_LOGIN_PARAMETERS_MISSING. Same function on 9.2.3 works without problems.

9.3.0 example:
![image](https://user-images.githubusercontent.com/6400595/43150787-15a49756-8f6b-11e8-9ed0-6cad743fbcbb.png)

9.2.3 example:
![image](https://user-images.githubusercontent.com/6400595/43150839-316be066-8f6b-11e8-85d0-df1dc7d3765b.png)

**Comment by joschi99** [comment]
If I put the user_token in the query string it works on 9.3.0
![postman](https://user-images.githubusercontent.com/6400595/43199054-fef7892c-9010-11e8-9e7b-b724ae1f8bd2.png)

**Comment by cedric-anne** [comment]
Hi,

I did not find the official page that explains this behaviour, but, as far as I remember, depending on your modules and configuration, Apache filters Authorization headers that are not matching expected method (Basic or Digest).

I think you could bypass this problem using following rewrite rule, but it requires to enable the rewrite mod:
```
RewriteEngine on
RewriteCond %{REQUEST_URI} /api(?:rest\.php)?/.*$
RewriteCond %{QUERY_STRING} !^(?:.*&)?user_token=[^&]+.*$
RewriteCond %{HTTP:Authorization} ^user_token\ (.+)$
RewriteRule .* %{REQUEST_URI}?user_token=%1 [QSA]
```
Explaination of the rule:
IF requested URI contains `/api/*` or `/apirest.php/*`
AND a not empty `user_token` is not already passed in quesry string
AND a not empty `user_token` is found in Authorization header
THEN `user_token` found in Authorization header is added to query string

Regards
