### ISSUE TITLE
[0.90.1] Wysiwyg non fonctionnel sur les solutions

### ISSUE THREAD

**Issue by ylegrand** [glpi-project/glpi#439]
Bonjour,

Sur le version 0.90.1 de GLPI, lors de la rédaction d'une solution à un ticket, l'éditeur WYSIYG s'affiche bien. Par contre, une fois enregistré le message s'affiche sans aucune mise en page.

Pour information, les balises HTML sont biens stockées en base, car lorsque je souhaite éditer la solution, l'éditeur WYSIWIG s'affiche de nouveau et mon texte est bien formaté.

S'agit-il d'un bug ou d'une configuration qui m'aurait échappé ?

En vous remerciant par avance.

**Comment by yllen** [comment]
Vous pourriez mettre une copie d'écran et préciser votre navigateur et sa version ?

**Comment by orthagh** [comment]
Des éventuelles erreurs javascripts depuis la console de votre navigateur (touche F12) seraient très appréciées

**Comment by ylegrand** [comment]
Bonjour,

Je suis sous Chrome 48, mais le comportement est le même sur tous les navigateurs testés.

Je vous joins les captures d'écran illustrant ma problématique.
![editeur](https://cloud.githubusercontent.com/assets/2845524/13109607/a03e60f2-d57a-11e5-9e9f-f42c2052aeca.PNG)
![rendu](https://cloud.githubusercontent.com/assets/2845524/13109608/a042f13a-d57a-11e5-985b-bc0cee461a40.PNG)

Je vous confirme par ailleurs qu'il n'y a aucune erreur Javascript : 
![screen shot 02-17-16 at 01 31 pm](https://cloud.githubusercontent.com/assets/2845524/13109630/d9f54c48-d57a-11e5-88cd-13d89fcf4ea4.PNG)


L'édition du code HTML généré montre que les balises HTML ont tout simplement été supprimées (équivalent d'un strip_tags ?).

Merci beaucoup

**Comment by yllen** [comment]
Vous constatez ce problème uniquement dans l'onglet Traitement des tickets ?

**Comment by ylegrand** [comment]
Bonjour,

Merci pour la correction apportée.

Oui je n'ai noté ce comportement que dans l'onglet Traitement du ticket, mais je pensais que c'était le seul endroit dans lequel le WYSIWIG est disponible.

Y'a-t-il d'autres endroits où il est possible d'utiliser du texte formaté ? Cela serait très intéressant sur la description du ticket, ou même les suivis classiques.

**Comment by yllen** [comment]
Non je pense que c'est juste à cet endroit mais moi aussi je peux oublier des parties. Donc c'était juste une demande de confirmation.
