### ISSUE TITLE
GLPI plugins error -> To be cleaned

### ISSUE THREAD

**Issue by Blazfhem** [glpi-project/glpi#4390]
* Steps to reproduce (which actions have you made) :
Install a plugin

* Expected result :
The plugin will work

* Actual result :
The plugin sometime work sometime don't and each time says he's in error and need to be clean

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/19334022/43249802-fd3f23c8-90bb-11e8-9000-8085e1576257.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

[code]   GLPI 9.3.0 (/glpi => /usr/share/glpi/www) Installation mode: TARBALL
--

Operating system: Linux centreon 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 PHP 5.6.37 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, json, ldap, libxml, mbstring, mcrypt, 	memcache, memcached, mhash, msgpack, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, 	sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.5.38 mod_perl/2.0.10 Perl/v5.16.3 () 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0 Server Software: MariaDB Server 	Server Version: 10.1.19-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed Zend OPcache extension is installed APCu extension is installed imap extension is not present xmlrpc extension is not present CAS extension is not present Database version seems correct (10.1.19) - Perfect! /usr/share/glpi/www/config : OK /usr/share/glpi/www/files : OK /usr/share/glpi/www/files/_dumps : OK /usr/share/glpi/www/files/_sessions : OK /usr/share/glpi/www/files/_cron : OK /usr/share/glpi/www/files/_graphs : OK /usr/share/glpi/www/files/_lock : OK /usr/share/glpi/www/files/_plugins : OK /usr/share/glpi/www/files/_tmp : OK /usr/share/glpi/www/files/_cache : OK /usr/share/glpi/www/files/_rss : OK /usr/share/glpi/www/files/_uploads : OK /usr/share/glpi/www/files/_pictures : OK /usr/share/glpi/www/files/_log : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

htmLawed version 1.2.4 in (/usr/share/glpi/www/lib/htmlawed) SimplePie version 1.5.1 in (/usr/share/glpi/www/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/usr/share/glpi/www/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/www/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/www/vendor/true/punycode/src) iacaml/autolink in (/usr/share/glpi/www/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi/www/vendor/sabre/vobject/lib)

Server: 'X.X.X.X', Port: '389', BaseDN: 'OU=Users,OU=LA CHAUSSEE ST VICTOR,DC=ELIZEUROPE,DC=LOCAL', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=glpi_ldap,OU=Users_applis,OU=LA CHAUSSEE ST VICTOR,DC=ELIZEUROPE,DC=LOCAL', Use TLS: none Server: 'X.X.X.X', Port: '389', BaseDN: 'OU=SBSUsers,OU=Users,OU=MyBusiness,DC=EPMODOM1,DC=FR', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=GLPIadmin,OU=SBSUsers,OU=Users,OU=MyBusiness,DC=EPMODOM1,DC=FR', Use TLS: none

Not active

 

ocsinventoryng       Name: OCS Inventory NG               Version: 1.5.0      State: To be cleaned 	reservation          Name: Reservation                    Version: 2.0.0      State: To be cleaned
[/code]

**Comment by trasher** [comment]
Seems to be related to the plugin, not to the core.

**Comment by Blazfhem** [comment]
This is comming from the core :
Every plugins that I tried made the same issue

![image](https://user-images.githubusercontent.com/19334022/43252995-23cb4b86-90c4-11e8-813f-0a01e9d74a8c.png)

**Comment by trasher** [comment]
I do not reproduce.

**Comment by cedric-anne** [comment]
Hi,

Could you check your GLPI logs (in `files/_log/*.log`) to see if you have any error ?

Regards

**Comment by Blazfhem** [comment]
There was no error. That's really strange cuz I can't find someone else who encountered this issue.
Even with clean install it was keeping crashing.
So I decided to rollback to 9.1.6 which works well.

Thx for support anyway !
