### ISSUE TITLE
Inconsistency with External link and entities

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#44]
v 0.85.4 & 0.90
Create an external link in root-entity, but not recursive, and associate it to computers.
Go to a computer belonging to a child entity.
- in Links tab of the computer, the nbr (1) is displayed, but the form is empty (no link defined)
- in computers list, add 'External links' to the computers' view. The external link is displayed for the computer, although it should'nt be.

Also Refer to https://forge.glpi-project.org/issues/4822

**Comment by blerohellec** [comment]
Corrections have not solved all of the problem.
If the context entity is the root-entity, it's OK.
If the context entity is the child entity, it's OK. The computer in the child entity do not see the link, and its Links tab doesn't display any number.
But, if the context is All entities (root-entity AND its sub-entities), then I still have the same bug.
Also, same bug, when I create a link in child entity, and the context is all entities : the computers in root-entity displays (1) in Links tab and the Links form is empty.

**Comment by blerohellec** [comment]
Still not correct.
Proposed solution for tab name : in inc/link.class.php, function getTabNameForItem(), call to getEntitiesRestrictRequest(), the entities_id of the item (computer, monitor...) has to be passed as the 4th parameter.
getEntitiesRestrictRequest(" AND ", "glpi_links", '', $item->getEntityID(), true);

**Comment by yllen** [comment]
For master, done in https://github.com/glpi-project/glpi/commit/3debffefafab1236c71609698d3bcd63daccb189
