### ISSUE TITLE
LDAP Group Import (Attribute Name Field) - GLPI 9.1.4

### ISSUE THREAD

**Issue by LordBat** [glpi-project/glpi#4403]
Hi, anyone know if is possible to "Change" the attribute  when im importing my groups from Active Directory?

For Example, the company have name structure about the departments and areas, and create groups like this:  GS_GLPI_SIS_CORE_INFR

When i am importing the groups, glpi takes GS_GLPI_SIS_CORE_INFR as group name.

Is possible to change with other attribute?

Thanks!

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
