### ISSUE TITLE
[9.3.1] Unable to paste image from MS Office Word in KB

### ISSUE THREAD

**Issue by gitdevmod** [glpi-project/glpi#4413]
* Steps to reproduce (which actions have you made) :

Copy/paste image from a Word document

* Expected result :
Image pasted

* Actual result :
No image pasted

* URL of the page :
glpi/front/knowbaseitem.form.php

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
GLPI 9.3.0
```

**Comment by trasher** [comment]
A fix on copy/paste has been proposed recently. Please try with 9.3/bugfixes branch (or lastest nighlty build) to see if your problem is still present.

**Comment by gitdevmod** [comment]
@trasher this PR https://github.com/glpi-project/glpi/pull/4391 ?

**Comment by gitdevmod** [comment]
What is the glpi version (release or bugfixes) at demo.glpi-project.org ?

**Comment by trasher** [comment]
9.3.0.

**Comment by cedric-anne** [comment]
Hi,

Precisely, the problem is that image detection in pasting process is working only if you paste one image. If you try to paste one image inside a text or multiple images, it will not work.

Not sure about the amount of changes to do, but iy may requires a lot of work.

Regards

**Comment by trasher** [comment]
Finally, this is a feature request, and not a bug. Please use suggestion webstie for RFE.
