### ISSUE TITLE
[9.3.1] : cron error when user replies to a "resolved" ticket

### ISSUE THREAD

**Issue by Rico29** [glpi-project/glpi#4414]
* Steps to reproduce (which actions have you made) :

1 - open a ticket
2 - write a mesage in the ticket follow-ups
3 - mark the ticket as resolved
4 - reply to the mail sent to the users, saying ticket has been resolved

* Expected result :
Content of mail appenet to ticket follow-ups

* Actual result :
Content of mail appenet to ticket follow-ups
errors reported by cron task : 

> Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Warning(2): Illegal offset type in isset or empty
>   Backtrace :
>   inc/ticket.class.php:126                           
>   inc/ticketfollowup.class.php:391                   Ticket::getTimelinePosition()
>   inc/commondbtm.class.php:937                       TicketFollowup->prepareInputForAdd()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Warning(2): preg_match() expects parameter 2 to be string, array given
>   Backtrace :
>   :                                                  
>   inc/dbmysql.class.php:877                          preg_match()
>   inc/dbmysql.class.php:900                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:923                          DBmysql->buildInsert()
>   inc/commondbtm.class.php:537                       DBmysql->insert()
>   inc/commondbtm.class.php:974                       CommonDBTM->addToDB()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Notice(8): Array to string conversion
>   Backtrace :
>   inc/dbmysql.class.php:879                          
>   inc/dbmysql.class.php:900                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:923                          DBmysql->buildInsert()
>   inc/commondbtm.class.php:537                       DBmysql->insert()
>   inc/commondbtm.class.php:974                       CommonDBTM->addToDB()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Warning(2): preg_match() expects parameter 2 to be string, array given
>   Backtrace :
>   :                                                  
>   inc/dbmysql.class.php:877                          preg_match()
>   inc/dbmysql.class.php:981                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:1003                         DBmysql->buildUpdate()
>   inc/commonitilobject.class.php:4453                DBmysql->update()
>   inc/ticket.class.php:2543                          CommonITILObject->updateDateMod()
>   inc/ticketfollowup.class.php:407                   Ticket->updateDateMod()
>   inc/commondbtm.class.php:975                       TicketFollowup->post_addItem()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Notice(8): Array to string conversion
>   Backtrace :
>   inc/dbmysql.class.php:879                          
>   inc/dbmysql.class.php:981                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:1003                         DBmysql->buildUpdate()
>   inc/commonitilobject.class.php:4453                DBmysql->update()
>   inc/ticket.class.php:2543                          CommonITILObject->updateDateMod()
>   inc/ticketfollowup.class.php:407                   Ticket->updateDateMod()
>   inc/commondbtm.class.php:975                       TicketFollowup->post_addItem()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  DBmysql::query() in /usr/share/glpi_9.3/inc/dbmysql.class.php line 177
>   *** MySQL query error:
>   SQL: UPDATE `glpi_itilsolutions`
>             SET `status`=4, `users_id_approval`=,
>             `date_approval`='2018-08-01 11:43:01'
>                WHERE `itemtype`='Ticket'
>                AND `items_id`=4658
>                ORDER BY date_creation DESC, id DESC LIMIT 1
>   Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '
>             `date_approval`='2018-08-01 11:43:01'
>                WHERE `itemtyp' at line 2
>   Backtrace :
>   inc/commonitilobject.class.php:1223                
>   inc/ticket.class.php:1563                          CommonITILObject->pre_updateInDB()
>   inc/commondbtm.class.php:1272                      Ticket->pre_updateInDB()
>   inc/ticketfollowup.class.php:446                   CommonDBTM->update()
>   inc/commondbtm.class.php:975                       TicketFollowup->post_addItem()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()

**Comment by trasher** [comment]
Please test with fix proposal in #4416.

**Comment by Rico29** [comment]
Problem is still present : 



> Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Warning(2): Illegal offset type in isset or empty
>   Backtrace :
>   inc/ticket.class.php:126                           
>   inc/ticketfollowup.class.php:391                   Ticket::getTimelinePosition()
>   inc/commondbtm.class.php:937                       TicketFollowup->prepareInputForAdd()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Warning(2): preg_match() expects parameter 2 to be string, array given
>   Backtrace :
>   :                                                  
>   inc/dbmysql.class.php:877                          preg_match()
>   inc/dbmysql.class.php:900                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:923                          DBmysql->buildInsert()
>   inc/commondbtm.class.php:537                       DBmysql->insert()
>   inc/commondbtm.class.php:974                       CommonDBTM->addToDB()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Notice(8): Array to string conversion
>   Backtrace :
>   inc/dbmysql.class.php:879                          
>   inc/dbmysql.class.php:900                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:923                          DBmysql->buildInsert()
>   inc/commondbtm.class.php:537                       DBmysql->insert()
>   inc/commondbtm.class.php:974                       CommonDBTM->addToDB()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Warning(2): preg_match() expects parameter 2 to be string, array given
>   Backtrace :
>   :                                                  
>   inc/dbmysql.class.php:877                          preg_match()
>   inc/dbmysql.class.php:998                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:1030                         DBmysql->buildUpdate()
>   inc/commonitilobject.class.php:4477                DBmysql->update()
>   inc/ticket.class.php:2543                          CommonITILObject->updateDateMod()
>   inc/ticketfollowup.class.php:407                   Ticket->updateDateMod()
>   inc/commondbtm.class.php:975                       TicketFollowup->post_addItem()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()
>  Toolbox::userErrorHandlerNormal() in /usr/share/glpi_9.3/inc/toolbox.class.php line 657
>   *** PHP Notice(8): Array to string conversion
>   Backtrace :
>   inc/dbmysql.class.php:879                          
>   inc/dbmysql.class.php:998                          DBmysql::quoteValue()
>   inc/dbmysql.class.php:1030                         DBmysql->buildUpdate()
>   inc/commonitilobject.class.php:4477                DBmysql->update()
>   inc/ticket.class.php:2543                          CommonITILObject->updateDateMod()
>   inc/ticketfollowup.class.php:407                   Ticket->updateDateMod()
>   inc/commondbtm.class.php:975                       TicketFollowup->post_addItem()
>   inc/mailcollector.class.php:668                    CommonDBTM->add()
>   inc/mailcollector.class.php:1744                   MailCollector->collect()
>   inc/crontask.class.php:836                         MailCollector::cronMailgate()
>   front/cron.php:83                                  CronTask::launch()

**Comment by trasher** [comment]
I can't reproduce. There was only 1 error, the SQL one. All other isses may be related to the content of the mail, and it will take hours/days to find a reproductible use case.

This should get fixed; yes. But since this does not cause real issue (followup is added, and issue state is updated); this is really minor.

**Comment by cedric-anne** [comment]
@Rico29,

Maybe I found the source of your problem, but I do not have a configured env to test reproductibility and my fix. Can you check if #4422 fixes tour problem ?

Regards

**Comment by Rico29** [comment]
Thanks, I made the change, I'll tell you if it does not fix the problem.
Regards
