### ISSUE TITLE
LDAP login page

### ISSUE THREAD

**Issue by flavien11** [glpi-project/glpi#4417]
Hello,

The latest version 9.3 displays a list of LDAP servers available on the login page, is it possible to recover this possibility in the configuration of GLPI? I have not been able to use this option if it exists.

We loved it to migrate to the state of the state, in the state of service, we need to request to customer to customer connection via this choice).

Thank you for your smile lights

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/4406
