### ISSUE TITLE
Unreachable code in search.class.php/giveItem [5365]

### ISSUE THREAD

**Issue by loicbenoit** [glpi-project/glpi#4418]
* Steps to reproduce (which actions have you made) :
1- Open file "glpi/htdocs/inc/search.class.php".
2- Go to the end of function "giveItem", near line 5365.
3- Inspect return statement for potential bug.

`      return $out;
`

* Expected result :
There should be no more code after a return statement located in the main function block.

* Actual result :
There is code after a return statement in main function block.

This code is unreachable:
```
      // Trans in group concat
      if (count($split) == 3 && !empty($split[1])) {
         return Dropdown::getValueWithUnit($split[1], $unit);
      }
      return Dropdown::getValueWithUnit($split[0], $unit);
```

* URL of the page :
https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/search.class.php

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.0

**Comment by trasher** [comment]
Since https://github.com/glpi-project/glpi/commit/54416d4803a indeed. Dunno if this code should be dropped (looks like it works since 2014) or if it must be reintegrated elsewhere.
