### ISSUE TITLE
Validation: confusing interface

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#442]
When a validation is requested, the validator is requested to validate the ticket in an interface where the Global approval status comes before the specific request to the user so that the user tend to change the Global approval status instead of his own validation.
Then it is not possible to define different permissions between validate a ticket and doing a global validation.
Another point is the "minimum validation required". really clear how it works but the labels of the dropdown menu is not clear at all for a normal user. I would change to something like "approved if one approves", "approved if majority approves" and "approved if everybody approves".

davide

**Comment by Electroni-K** [comment]
I'm agree with you !
And the specific user validation request dont show any button to validate or refuse the request (they must click on the request to have the form validation) that's why user wants to change global validation status because they don't see any other buttons to validate !

You ca

**Comment by orthagh** [comment]
I'm closing in favor of suggest topic.

**Comment by trasher** [comment]
@Giudy see https://glpi.userecho.com/communities/1/topics/55-improve-ticket-validation-display
