### ISSUE TITLE
Images in notifications broken in Outlook Web App

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#4421]
* Steps to reproduce (which actions have you made) :
Add a solution on a ticket, with a description containing an image.

* Expected result :
Image is displayed correctly on OWA.

* Actual result :
Image is not displayed in OWA.

* URL of the page :
-

* Screenshot of the problem (if pertinent) :
Outlook Client
![image](https://user-images.githubusercontent.com/22499638/43468122-79e068da-94e3-11e8-8eda-2c5a48db2354.png)

Outlook Web App
![image](https://user-images.githubusercontent.com/22499638/43468085-680c790a-94e3-11e8-8320-c6739ab6ec0f.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
GLPI 9.3/bufixes@9c3fd7d7ad271139e991ff9b5fd960cd80130281
```

**Comment by AnaelMobilia** [comment]
@cedric-anne Could you, please, provide the HTML source of the mail seen on OWA ?

Regards,
Anael

**Comment by cedric-anne** [comment]
@AnaelMobilia 

I do not use OWA, I just copied/paste images from discussion in issue #4345.

Regards
