### ISSUE TITLE
Ldap user import Problem

### ISSUE THREAD

**Issue by gabirro** [glpi-project/glpi#4423]
Dears my friends

This is my first time that i post here. 

We have in production a GLPI 9.1.5 with no problems. 

Today, we have just a new install with the last version 9.3. We have a problem to import users from our LDAP server. The configuration is the same that our production GLPI and we dont know what is happening.  We are doing tests in this versión to evaluate if we upagraded or not. 

At the first we can search any people of our organization but we cant import. We put bellow the errors in GUI and CLI. 

![screenshot_23](https://user-images.githubusercontent.com/42032204/43579651-1eece432-9653-11e8-862f-6f0127df3e7b.png)

![screenshot_24](https://user-images.githubusercontent.com/42032204/43579662-253b4af4-9653-11e8-9a21-fa373ff5a96f.png)

![screenshot_25](https://user-images.githubusercontent.com/42032204/43579768-77aeeee4-9653-11e8-9191-15e42c5ae81c.png)

**Comment by trasher** [comment]
Please provide full error from logs.

**Comment by gabirro** [comment]
Dears, 

I am so sorry but the configuration provided in the second picture below is wrong because it is from a badly configured ldap.

However, with the configuration with the correct parameters and doing connection tests the file php-error.log do not show anything and the same with the log files of the apache.

I have modified the variable 'error_reporting = E_ALL' in php.ini and the log files do not show anything.

Please, could you provide me more information about the log files that you require me?

Thanks.

**Comment by orthagh** [comment]
In your first post, you provided a screenshot of a `tail -f` command.
The output is truncated, we need to have the full backtrace.

**Comment by trasher** [comment]
No feedback from a while, closing.
