### ISSUE TITLE
Add new enclosure

### ISSUE THREAD

**Issue by MrRobbi** [glpi-project/glpi#4424]
* Steps to reproduce (which actions have you made) :
Added two enclosures, trying to add third.

* Expected result :
Button "add" available

* Actual result :
Lack of button.

* URL of the page :
/front/enclosure.form.php?id=-1&amp;withtemplate=2

* Screenshot of the problem (if pertinent) :

![enclosure](https://user-images.githubusercontent.com/35692596/43583175-f873945c-965e-11e8-84bb-14d1dbf94f0a.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.0, php7.0, all extensions installed.

**Comment by MrRobbi** [comment]
1. [Thu Aug 02 14:29:23 2018] [:error] [pid xxxx] [client xxxx] PHP Fatal error:  Uncaught Error: Call to a member function getLink() on boolean in /var/www/glpi/inc/dcbreadcrumb.class.php:69\nStack trace:\n#0 /var/www/glpi/inc/enclosure.class.php(108): Enclosure->showDcBreadcrumb()\n#1 /var/www/glpi/inc/commonglpi.class.php(468): Enclosure->showForm('', Array)\n#2 /var/www/glpi/ajax/common.tabs.php(92): CommonGLPI::displayStandardTab(Object(Enclosure), 'Enclosure$main', '', Array)\n#3 {main}\n  thrown in /var/www/glpi/inc/dcbreadcrumb.class.php on line 69, referer: xxxx/front/enclosure.form.php?id=-1&amp;withtemplate=2

2. When I disable "Tag Management" plugin, an "add enc page" displays only "An error occured loading contents!
Please check GLPI logs or contact your administrator.
or try to reload"
Error in log remains the same.

3. It's on super admin.

**Comment by cedric-anne** [comment]
Hi,

This problem is not really related to adding enclosures. It happens when the rack associated to enclosure has been deleted. https://github.com/glpi-project/glpi/pull/4536 should fix your problem.

Regards
