### ISSUE TITLE
Version mismatch in tgz file

### ISSUE THREAD

**Issue by ricottatosta** [glpi-project/glpi#4428]
Dear developer,
there is a problem downloading release 9.3 in tgz format from a docker container (image: diouxx/glpi).
URL should be:
https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.0.tgz
instead, it is:
https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.tgz
Can you do something to solve it out!
Thanks in advance

**Comment by trasher** [comment]
This won't be changed. 9.3.1 will be proprely named, and we'll take care to name 9.4.0 properly when it will be released.

**Comment by ricottatosta** [comment]
Got it! In the meanwhile I'll use 9.2.4.
Best Regards
