### ISSUE TITLE
[9.3.0] Reload of all schedule frame when planning nor event selected

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#4434]
* Steps to reproduce (which actions have you made) :
Look at the schedule

* Expected result :
When we check or uncheck boxes in the left column, only the schedule is updated

* Actual result :
All the schedule frame is reloaded with the left column and drop-down tabs instead of just reload the schedule only.
Then subgroups of tabs deployed previously are closed to each selection or deselection.
This was not the case with 9.2.2, everything worked well with icons rotating by css.

* Links of reported issue on the forum :  
[Reloading the unexpected tabs on schedule](https://forum.glpi-project.org/viewtopic.php?id=164288)
```
GLPI 9.3.0 - PHP 7.2.8 - Zend OPcache v7.2.8 - APCu 5.1.12
```

**Comment by M-Falken** [comment]
Bug not present with edge but with FF and Chrome (all latests versions)

**Comment by orthagh** [comment]
Here is the fix: https://github.com/glpi-project/glpi/pull/4466/commits/6d4943f952ee81fb20e595de29dd5d3301ae693f

**Comment by trasher** [comment]
Please do not close tickets; it's done once fix is applied.
