### ISSUE TITLE
[9.2.4] I can't move entity to a lower entity

### ISSUE THREAD

**Issue by vv0rk** [glpi-project/glpi#4437]
I created multiple entities and I wanna move them to another entity.
I selected entities and a Move action in a Action menu, but into "As child of" menu I can select only upper layer.
That is bug or feature?

**Comment by cconard96** [comment]
You are able to move to sub-entities from the entity form, so I assume it is a bug with the massive action.

**Comment by vv0rk** [comment]
Thank You!
It is working.
Please add the fix into a 9.2.4 release.
