### ISSUE TITLE
[9.2.1] Problem sending email from automatically (queuednotification)

### ISSUE THREAD

**Issue by rogeriogcosta** [glpi-project/glpi#4440]
Problem sending email, the messages in the notification queue do not send automatically. I try to execute command by windows scheduler using a .bat, but the apahce locks the service.

c:/xampp/php/php.exe -f  C:/xampp/htdocs/glpi/front/cron.php

Versions I'm using:
Windows Server 2016
XAMPP Version: 5.6.33
GLPI 9.2.1

Below XAMPP configuration:
https://imgur.com/a/6rFPjgf

Automatic sending is stopping. E-mail out of the queue forcing manual submission:
https://imgur.com/a/obyo1XY

E-mail stopped in the queue, just send manually by the button Actions> send
https://imgur.com/a/PkQAtQY

**Comment by cedric-anne** [comment]
Hi,

Can you check if you have something in your log files (in `glpi\files\_logs`) when you execute the action ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
