### ISSUE TITLE
Technician can change satisfaction score

### ISSUE THREAD

**Issue by valentindragan** [glpi-project/glpi#4454]
* Steps to reproduce (which actions have you made) :
- a technician creates a ticket he just received by phone, assigning another person as a requester and himself as technician
- the problem is marked as solved;
- requester closes the ticket
- requester assigns satisfaction score 3 stars, after receiving the satisfaction email
- technician receives the satisfaction email answer
- technician can change the score, and save, because he is the ticket writer

* Expected result :
- a technician should not be able to change the score if he is one of the assigned technicians or part of the assigned technician group, even if he created the ticket.
or
- a score should NOT be changed by other person than the one that already assigned it

* Actual result :
- the technician who created the ticket can change the score that the requester assigned.

* URL of the page :
https://glpisite/front/ticket.form.php?id=456 , Satisfaction tab

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
[code] GLPI 9.2.3 ( => /usr/share/glpi)

Information about system installation and configuration
[code]

GLPI 9.2.3 ( => /usr/share/glpi)
Installation mode: GIT

Server

Operating system: Linux 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64
PHP 5.6.36 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2,
calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
mbstring, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer,
wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M"
Software: Apache (Apache Server at removed Port 443)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36
Server Software: MySQL Community Server (GPL) by Remi
Server Version: 5.5.45-log
Server SQL Mode:
Parameters: glpi@localhost/glpi
Host info: Localhost via UNIX socket

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
OK/etc/glpi : OK
OK/var/lib/glpi/files : OK
OK/var/lib/glpi/files/_dumps : OK
OK/var/lib/glpi/files/_sessions : OK
OK/var/lib/glpi/files/_cron : OK
OK/var/lib/glpi/files/_graphs : OK
OK/var/lib/glpi/files/_lock : OK
OK/var/lib/glpi/files/_plugins : OK
OK/var/lib/glpi/files/_tmp : OK
OK/var/lib/glpi/files/_cache/ : OK
OK/var/lib/glpi/files/_rss : OK
OK/var/lib/glpi/files/_uploads : OK
OK/var/lib/glpi/files/_pictures : OK
OK/var/log/glpi : OK
OKSELinux mode is Permissive
OKSELinux boolean configuration for httpd_can_network_connect --> on
OKSELinux boolean configuration for httpd_can_network_connect_db --> on
OKSELinux boolean configuration for httpd_can_sendmail --> on

Libraries

htmLawed version 1.1.20 in (/usr/share/php/htmLawed)
phpCas version 1.3.5 in (/usr/share/glpi/vendor/jasig/phpcas/source)
PHPMailer version 5.2.26 in (/usr/share/glpi/vendor/phpmailer/phpmailer)
SimplePie version 1.5.1 in (/usr/share/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.16 in (/usr/share/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/usr/share/glpi/vendor/true/punycode/src)
iacaml/autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib)

LDAP directories

Server: -

SQL replicas

Not active

Notifications

Way of sending emails: SMTP (anonymous@removed)

Mails receivers

Name: 'removed' Active: No
Server: '{removed:995/imap}' Login: 'removed' Password: Yes
Name: 'removed' Active: Yes
Server: '{removed:143/imap/notls/debug}GLPI' Login: 'removed' Password: Yes
Name: 'removed' Active: No
Server: '{removed:995/imap/ssl}Test' Login: 'removedo' Password: Yes
Name: 'removed' Active: Yes
Server: '{removed:143/imap/notls}GLPI' Login: 'removed' Password: Yes
Name: 'removed' Active: No
Server: '{removed:993/imap/ssl/notls}GLPI' Login: 'removed' Password: Yes

Plugins list

behaviors Name: Comportements Version: 0.85 State: Not activated
moreticket Name: More ticket Version: 1.1.2 State: Not activated
ocsinventoryng Name: OCS Inventory NG Version: 1.4.3 State: Enabled
mreporting Name: Plus de rapports Version: 0.85+1.0 State: Not activated
purgelogs Name: Purge de l'historique Version: 0.85+1.1 State: Not activated
reports Name: Rapports Version: 1.8.0 State: Not activated
OCS Inventory NG
Host: localhost
Connection: Ok
Use the OCSNG software dictionary: No
[/code]
```

**Comment by trasher** [comment]
GLPI 9.2 is no longer supported, please check if issue is still present on 9.3.

**Comment by valentindragan** [comment]
Yes. I have upgraded the glpi locally and can confirm that the described problem can be reproduced on 9.3, as well.
Information about system installation & configuration
[code]
 
GLPI 9.3.0 (/travaux => C:\wamp64\www\glpitrv)
Installation mode: TARBALL

Server
 
Operating system: Windows NT NOM2761 10.0 build 16299 (Windows 10) AMD64
PHP 5.6.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	com_dotnet, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, sockets,
	sqlite3, standard, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.27 (Win64) PHP/5.6.31 (Apache/2.4.27 (Win64) PHP/5.6.31 Server at localhost Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.19
	Server SQL Mode: 
	Parameters: root@localhost/glpitrv_1
	Host info: localhost via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
APCu extension is not present
CAS extension is not present
Database version seems correct (5.7.19) - Perfect!Database version seems correct (5.7.19) - Perfect!
OKC:\wamp64\www\glpitrv/config : OK
OKC:\wamp64\www\glpitrv/files : OK
OKC:\wamp64\www\glpitrv/files/_dumps : OK
OKC:\wamp64\www\glpitrv/files/_sessions : OK
OKC:\wamp64\www\glpitrv/files/_cron : OK
OKC:\wamp64\www\glpitrv/files/_graphs : OK
OKC:\wamp64\www\glpitrv/files/_lock : OK
OKC:\wamp64\www\glpitrv/files/_plugins : OK
OKC:\wamp64\www\glpitrv/files/_tmp : OK
OKC:\wamp64\www\glpitrv/files/_cache : OK
OKC:\wamp64\www\glpitrv/files/_rss : OK
OKC:\wamp64\www\glpitrv/files/_uploads : OK
OKC:\wamp64\www\glpitrv/files/_pictures : OK
OKC:\wamp64\www\glpitrv/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (C:\wamp64\www\glpitrv\lib\htmlawed)
SimplePie version 1.5.1 in (C:\wamp64\www\glpitrv\vendor\simplepie\simplepie\library)
TCPDF version 6.2.17 in (C:\wamp64\www\glpitrv\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\wamp64\www\glpitrv\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\wamp64\www\glpitrv\vendor\true\punycode\src)
iacaml/autolink in (C:\wamp64\www\glpitrv\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\wamp64\www\glpitrv\vendor\sabre\vobject\lib)

LDAP directories
 
========================

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@srv-------)

Mails receivers
 

Plugins list
 
	behaviors            Name: Comportements                  Version: 0.84       State: Not activated
	customtickets        Name: CustomTickets                  Version: 1.0.5      State: Not activated
	themes               Name: Thèmes                         Version: 1.2.0      State: Not activated

[/code]

**Comment by cedric-anne** [comment]
Hi,

Indeed, it is possible for the writer of the ticket to update the satisfaction, even if he it has been submitted by the requester.
It will also be possible, if there are multiple requesters, or if requester is a group, that a requester "B" changes score submitted by requester "A".

A solution to handle this kind of cases is to change the data model to be able to have multiple satisfaction scores by ticket (on by user).

As this is not an issue, I will close this ticket. Feel free to submit a request for enhancement on https://glpi.userecho.com/.

Regards
