### ISSUE TITLE
My Tasks shows Task Template

### ISSUE THREAD

**Issue by grigribou** [glpi-project/glpi#4455]
Hi, :)

I'm looking project management module in GLPI 9.3:
 
I created a project template, and a project form this template.
In template I set group to some tasks

Now, when i'm going to "My tasks" (/front/projecttask.php), i see al tasks : From project but ALSO from template.
![image](https://user-images.githubusercontent.com/8124469/43765507-6537c58e-9a30-11e8-820e-f9cfc72c2462.png)

I think it's annoying to see tasks from template. Mote over it's not possible to filter it :
![image](https://user-images.githubusercontent.com/8124469/43765970-95dd26b0-9a31-11e8-9eb9-480ab9906d8b.png)

It it possible to remove task from template?

Regards,

**Comment by orthagh** [comment]
Here is a fix: https://github.com/glpi-project/glpi/pull/4457/files

**Comment by grigribou** [comment]
Solved with fix #4455
Thanks a lot!! :)

**Comment by grigribou** [comment]
Duplicate of #4457
