### ISSUE TITLE
Feture/PDU enhancement

### ISSUE THREAD

**Issue by juge2** [glpi-project/glpi#4456]
The datacenter / rack view of 9.3 is really great, but I would suggest some enhancements regarding the power and PDU management:

For what I experience, the relation is as following:
Wall Power Outlet(s)  <---> PDU Inlet(s) | PDU Outlet(s) <---> PSU Inlets (Power Supply Inlet(s) of Computers/Monitors/Network Devices, etc.

Currently there seems to be no connection between the Rack PDUs and Equipment PSU possible.

So here my ideas:
1) Create types Inlets and Outles, add them to PDU/PSU types and make connections between them possible: this should be roughly equivalent to the network 'Ethernet port' type.
![2018-08-07_selection_006](https://user-images.githubusercontent.com/559489/43771987-129c6350-9a41-11e8-84b9-1c26c1199699.png)
![2018-08-07_selection_007](https://user-images.githubusercontent.com/559489/43771994-1570b112-9a41-11e8-9cc6-2a68d5fe13a1.png)

And some minor other issues:
2) What does the 'Number' characteristic mean of a PDU plug mean?
3) It is not possible to add external links to PDUs
![2018-08-07_selection_005](https://user-images.githubusercontent.com/559489/43771264-f2419424-9a3e-11e8-989f-82e576618560.png)

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
