### ISSUE TITLE
[GLPI 9.2.3] Help - Log file

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#4458]
Guys, help!

After updating GLPI from summer 9.2.1 to 9.2.3 the file glpi / files / _log / php-errors.log is generating logging without stopping, knocking down my server. Print from the attached log. Can someone help me?

![log](https://user-images.githubusercontent.com/35368369/43792838-49dfca1e-9a50-11e8-85e9-d43194d7430e.PNG)

Error log:

![erro](https://user-images.githubusercontent.com/35368369/43793009-add2e31c-9a50-11e8-90f4-7e84a04edfc8.PNG)

**Comment by phamorais** [comment]
There are no users configured for cron

**Comment by trasher** [comment]
Sounds like you have a ACls issue from your server on the plugins directory. Get it fixed and you should be done.

**Comment by trasher** [comment]
permissions on your directories/files.

**Comment by phamorais** [comment]
@trasher 
All directories and files are with 775 and apache: apache. I do not think it's permission.

**Comment by trasher** [comment]
readdir returns false, so PHP cannot read the directory for any reason (http://php.net/manual/en/function.readdir.php). Problem is on your side, if it's not acl, it's a symlink (unsopported), or whatever.

**Comment by phamorais** [comment]
@trasher I Resolved my problem. Was cache in CENTos
