### ISSUE TITLE
[9.3] Must be in debug mode to select values in selecoxes

### ISSUE THREAD

**Issue by R0dS3rling** [glpi-project/glpi#4464]
Hi,

I migrate this morning my glpi server to the 9.3 version. Since, when i want to select value in any selectbox, i must switch the application in debug mode.
I was in 9.2.2 before and my migration runs OK.

It's very annoying that our users are ALL in debug mode to post tickets.

Here's my telemetry datas 
{
    "glpi": {
        "uuid": "rpDFQ0v7roI65vIAZzYCkrvQa6uXIBcBwdMr79U3",
        "version": "9.3.0",
        "plugins": [
            {
                "key": "fields",
                "version": "1.8.1"
            },
            {
                "key": "genericobject",
                "version": "2.6.0"
            },
            {
                "key": "ocsinventoryng",
                "version": "1.5.0"
            }
        ],
        "default_language": "fr_FR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "500-1000",
            "avg_networkequipments": "0-500",
            "avg_tickets": "1000-2500",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "0-500",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "Debian 9.1",
            "version": "10.1.26-MariaDB-0+deb9u1",
            "size": "634.9",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "",
            "version": ""
        },
        "php": {
            "version": "7.0.30",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "mysqlnd",
                "PDO",
                "xml",
                "apcu",
                "apc",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "imap",
                "json",
                "ldap",
                "exif",
                "mcrypt",
                "mysqli",
                "pdo_mysql",
                "Phar",
                "posix",
                "readline",
                "shmop",
                "SimpleXML",
                "sockets",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "xmlwriter",
                "xsl",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "128M",
                "post_max_size": "8M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "2M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "",
            "version": "4.9.0-6-amd64"
        }
    }
}

Thanks for your help 

Olivier

**Comment by orthagh** [comment]
In normal mode (disable debug mode), du you find any errors relative.
Check:
- files/_logs/php-errors.log
- browser console (F12 keyboard shortcut)

**Comment by R0dS3rling** [comment]
Thanks for the quick response.
In Firefox console i have these errors : 
ReferenceError: formatResult is not defined[En savoir plus] jquery-1.10.2.min.js:47:13 
	<anonyme>
https://glpi.crous-montpellier.fr/lib/jquery/js/jquery-1.10.2.min.js:47:13
c
jquery-1.10.2.js:3048:9
add
jquery-1.10.2.js:3094:6
ready
jquery-1.10.2.js:271:2
init
jquery-1.10.2.js:214:10
x
jquery-1.10.2.js:63:9
<anonyme>
https://glpi.crous-montpellier.fr/lib/jquery/js/jquery-1.10.2.min.js:4:1
globalEval/<
jquery-1.10.2.js:612:4
globalEval
jquery-1.10.2.js:611:5
domManip
jquery-1.10.2.js:6281:8
append
jquery-1.10.2.js:6047:9
html/<
jquery-1.10.2.js:6174:4
access
jquery-1.10.2.js:861:5
html
jquery-1.10.2.js:6138:9
load/</<
https://glpi.crous-montpellier.fr/lib/jquery/js/jquery-ui-1.10.4.custom.min.js:7:54106

I see that all elements on the pages that uses jquery (input text, selectboxes, calendars) are not activated in normal mode but ok in debug mode.

Is this because my site is in httpS ?

**Comment by orthagh** [comment]
if the file exists, could you remove : js/common.**min**.js (the min is very important) and test again

**Comment by orthagh** [comment]
if ok, you should indicate where you get glpi tarball, normally we provide correct minified files, it seems you have an old version of this file

**Comment by R0dS3rling** [comment]
Ok removing js/common.min.js solved the problem.
I get the archive here : https://github.com/glpi-project/glpi/archive/9.3.0.tar.gz

Thanks a lot for your help

**Comment by orthagh** [comment]
You took the source archive, you should always take the 1st one in github:

See: https://github.com/glpi-project/glpi/releases/tag/9.3.0

![image](https://user-images.githubusercontent.com/418844/43838230-1563c788-9b1b-11e8-82a4-11c30cdea9f2.png)

I strongly suggest you to get the correct archive and copy it on your instance.
You may have some other bugs with the source.
