### ISSUE TITLE
mail follow up option with suppliers

### ISSUE THREAD

**Issue by dan723** [glpi-project/glpi#4467]
GLPI version 9.2.3 

When y create a ticket from email and assign to a supplier the field "Email Followup" is automatically set to no.
Is there any configuration to change this behavior?

Thanks

**Comment by orthagh** [comment]
fixed in https://github.com/glpi-project/glpi/pull/4492 (soone in 9.3.1)

**Comment by dan723** [comment]
Ok, thank you very much

Regards
