### ISSUE TITLE
[9.3 Bugfixes] Problem with condition with NULL

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#4468]
9.3 Bugfixes

With changes to the conditions on this commit, (https://github.com/glpi-project/glpi/commit/eef9748aff51a0dd1b098e3307b72f8e78209024) requests with NULL no longer work. 

Example : 
```$where += ['NOT'   => ['date_out' => 'NULL']]; ```
in https://github.com/glpi-project/glpi/commit/eef9748aff51a0dd1b098e3307b72f8e78209024#diff-66244e2fec87faefddf6992880d76167R481

The request gives :
```SELECT COUNT(*) AS cpt FROM `glpi_consumables` WHERE `consumableitems_id` = '3' AND  NOT (`date_out` = NULL)```

But if I pass NULL without ' like this : 
`$where += ['date_out' => NULL];`
The request gives :
```SELECT COUNT(*) AS cpt FROM `glpi_consumables` WHERE `consumableitems_id` = '3' AND `date_out` IS NULL```

**Comment by trasher** [comment]
Iterator does not support NULL string, only null value.
