### ISSUE TITLE
Rules for assigning an item to an entity >> Action Entities child visibility

### ISSUE THREAD

**Issue by grigribou** [glpi-project/glpi#4484]
Hi,

In "Administration > Rules > Rules for assigning an item to an entity" I can assign entity, without problem, but I can't set automatically "Child entities" to "YES"

If it a bug, or maybe a future request?

![image](https://user-images.githubusercontent.com/8124469/43990098-eec8cc7a-9d56-11e8-90e1-55c8e3586e5f.png)

![image](https://user-images.githubusercontent.com/8124469/43990082-a3c37450-9d56-11e8-9d33-4bf319da81f8.png)

Thanks a lot!
Regards,

**Comment by orthagh** [comment]
-> feature request
Post it on http://suggest.glpi-project.org

For information, i know one partner (ping @tsmr and @amma35) is working on this one, so it **may** be released in the next version.

**Comment by orthagh** [comment]
fixed in master by 06c7152
