### ISSUE TITLE
Firefox message after redirect are not shown completely

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#449]
GLPI 0.91
When updating an item (for example a user), using FireFox and with 'Status bar' shown, the message after redirect is not complete:
![image](https://cloud.githubusercontent.com/assets/7569958/12981199/f44822b8-d0df-11e5-9fca-d6e172eb0a06.png)
If 'Status bar' is not shown then it's OK.
![image](https://cloud.githubusercontent.com/assets/7569958/12981239/15768772-d0e0-11e5-933a-07b000cdf9dc.png)

**Comment by orthagh** [comment]
Hello @tomolimo 

Can you hint me a way to add this bar ?
I fail to find it.

**Comment by tomolimo** [comment]
It seems like statusbar is no longer existing with FF4...
https://support.mozilla.org/en-US/kb/what-happened-status-bar#w_the-new-status-bar
So you may close this issue

**Comment by orthagh** [comment]
oh great :D
