### ISSUE TITLE
feature request: please add pgp support

### ISSUE THREAD

**Issue by colttt** [glpi-project/glpi#4495]
Hello,
it would be very nice if you add pgp/gpg support to sign/crypt/encrypt mails like other tools (eg [otrs](https://blog.otrs.com/2017/08/22/encrypt-sign-notifications-otrs-via-pgp/)). Nowadays you don't know if that mail from our (IT)-Support or from somewhere else, so when it signed you know that. The same with encryption, when you write a ticket it is sometimes very helpfull to encrypt the mail (eg for password or tokens).

best regards

**Comment by orthagh** [comment]
Please use http://suggest.glpi-project.org to feature suggestion.
We do triage on this external platform
