### ISSUE TITLE
API User Managment

### ISSUE THREAD

**Issue by Alukard39** [glpi-project/glpi#4497]
Hello
after successful user creation trough api i need to manage user memberships in groups or profile
winch method i need  to use to assign new profile or group to user?

**Comment by orthagh** [comment]
Hello.

For profile (plus recursive and Entity fields), you can pass it directly at user creation with these keys:
 * `_profiles_id`
 * `_is_recursive`
 * `_entities_id`

For two steps creation (mandatory for groups), store the user's id returned by the POST query of user creation and do another POST query:

## user's profiles

POST /Profile_User

with theses keys:
 * `'users_id'`: the id of your user returned by your previous POST query,
 * `'profiles_id'`: id of the profile,
 * `'entities_id'`: id of the entity (default 0),
 * `'is_recursive'`: 1 = yes, 0 = no (default 0)
}

## user's groups

POST /Group_User

with theses keys:
 * `'users_id'`: the id of your user returned by your previous POST query,
 * `'groups_id'`: id of the group,
 * `'is_manager'`: 1 = yes, 0 = no,
 * `'is_userdelegate'`: 1 = delegatee, 0 = no delegation
}

I close this issue, feel free to comment if you need precisions.

Regards
