### ISSUE TITLE
 in the kb search kb, the results don't match regular with search regular expression

### ISSUE THREAD

**Issue by luisjosemachado** [glpi-project/glpi#4498]
GLPI version 9.3 and 9.3/bugfixes

The searches in KB don't show expected result.

* Steps to reproduce:
1. Create a article with title "new article"; 
2. Set the target to "entity" and   "Child entities = Yes";
3. In the search filter applies, respective:
3.1 - "new article"; (use double quotes)
3.2 - arti*

* Expected result :
In both searches (3.1 and 3.2) the result should be the document "new article" 

* Actual result :
No results were found.

* Screenshot of the problem:

![screenshot_2018-08-15 glpi - knowledge base - 10](https://user-images.githubusercontent.com/30940056/44165369-e90cb080-a09e-11e8-9f58-8e2667525c39.png)

![screenshot_2018-08-15 glpi - knowledge base - 10 1](https://user-images.githubusercontent.com/30940056/44165372-ea3ddd80-a09e-11e8-80cb-2d72eaa6b3ee.png)

![screenshot_2018-08-15 glpi - knowledge base 3](https://user-images.githubusercontent.com/30940056/44165388-f164eb80-a09e-11e8-8a0d-998380b18f6f.png)

![screenshot_2018-08-15 glpi - knowledge base 1](https://user-images.githubusercontent.com/30940056/44165378-edd16480-a09e-11e8-8766-e2b7286b3aab.png)

![screenshot_2018-08-15 glpi - knowledge base 2](https://user-images.githubusercontent.com/30940056/44165386-f033be80-a09e-11e8-9f5f-7e480afb5cec.png)

**Comment by orthagh** [comment]
Hello.

Actually, you don't need to add `*` char to do a search. it's automatically done by the full text search of the knowbase.
