### ISSUE TITLE
In Setup > General, tab Assets, autom update elts related to computers : some fields are inverted

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#45]
0.84, 0.85, 0.90

In Setup > General, tab Assets, bottom part 'Automatically update elements related to the computers', field 'User' update record where name=is_group_autoupdate, and so on.
Refer to http://forum.glpi-project.org/viewtopic.php?id=56100

in /inc/config.class.php, function ShowFormInventory, near line 475, the labels displayed on screen (Alternate username, User, Group, Location, Status) are not in the same order as the array $fields which comes after (contact, group, location, user).

**Comment by yllen** [comment]
0.84 is to old but corrected for 0.85-bugfixes and 0.90
