### ISSUE TITLE
GLPI LDAP Mass Sync doesn't load thumbnails

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#450]
Using GLPI 0.91 and GLPI LDAP Mass Sync.
The users's thumbnails (users's pictures) are not loaded into GLPI.
We must force synchronization to get them.

**Comment by orthagh** [comment]
With 0.90, sync ok ?

**Comment by tomolimo** [comment]
Hello
I made a test with 0.90.1: it's OK users pictures are loaded from LDAP into GLPI.
Thank you,
Tomolimo

**Comment by tomolimo** [comment]
With GLPI 0.91, I got these errors running the LDAP mass import script from command line, when running with PHP 5.6.17 (x86)

> 2016-02-17 15:42:56 [@ARGLPID20]
  *** PHP Warning(2): ldap_search(): Partial search results returned: Sizelimit exceeded
  Backtrace :
 :
  inc\authldap.class.php:1364                        ldap_search()
  inc\authldap.class.php:1491                        AuthLDAP::searchForUsers()
  scripts\ldap_mass_sync.php:156                     AuthLDAP::getAllUsers()
  scripts\ldap_mass_sync.php:119                     import()
2016-02-17 15:42:56 [@ARGLPID20]
  *** PHP Notice(8): Undefined index: date_sync
  Backtrace :
  inc\authldap.class.php:1529 
  scripts\ldap_mass_sync.php:156                     AuthLDAP::getAllUsers()
  scripts\ldap_mass_sync.php:119                     import()
2016-02-17 15:49:05 [@ARGLPID20]
  *** PHP Notice(8): Undefined variable: input
  Backtrace :
  inc\authldap.class.php:2062
  scripts\ldap_mass_sync.php:164                     AuthLDAP::ldapImportUserByServerId()
  scripts\ldap_mass_sync.php:119                     import()

And when running with PHP 7, I got also a mysql module load error 

With GLPI 0.90 and PHP 5.4, I also got error message for "LDAP Server size limit exceeded: user deletion disabled"

**Comment by orthagh** [comment]
since php5.6 (and glpi0.85), you could do a panigated search on ldap.
See "Advanced information" tab in you ldap conf to enable it.
It will avoid these "Partial search results returned" messages.

For the current topic, you could test, but i think this is not relative

**Comment by tomolimo** [comment]
I did the setting but it changed nothing

**Comment by orthagh** [comment]
@tomolimo, is this issue still valid ?

**Comment by tomolimo** [comment]
I'll check it on next Thursday. 
Regards

**Comment by tomolimo** [comment]
It is still  valid.
How can I help on this?

**Comment by orthagh** [comment]
In my tests with ldap_mass_sync.php script and with the help of phpdebug, i can retrieve pictures from an openldap.

As other informations, with default options of the script (action=1), picture synchronisation is effective only if user was never updated (i think this part is strange). With action=2, picture is force-updated

Could you test with option action=2 or clear date_sync fields of your glpi users before synchronisation and answer me your results ?

**Comment by tomolimo** [comment]
In fact this is already the action_type I'm using:
Here is my command line:
```
L:\inetpub\wwwroot\glpi091\scripts>"C:\Program Files\PHP\v7.0\php.exe" -f ldap_mass_sync.php action=2 ldap_filter="(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$))(!(samaccountname=*_IWAY))(!(msExchResourceMetaData=ResourceType:*)))"
```

And here are the error files I got:
[php-errors.log.gz](https://github.com/glpi-project/glpi/files/341322/php-errors.log.gz)
[sql-errors.log.gz](https://github.com/glpi-project/glpi/files/341323/sql-errors.log.gz)

**Comment by orthagh** [comment]
What kind of ldap server did you use ? Active Directory ?

**Comment by tomolimo** [comment]
Yes Active Directory

**Comment by orthagh** [comment]
(fyi, Your logs files contains some structure of your directory, i got the files, i think you should now delete them)

**Comment by tomolimo** [comment]
done, thank you

**Comment by orthagh** [comment]
I'm currenlty managing to have an AD in our labo for test this issue.
I'll let you know

**Comment by tomolimo** [comment]
ok, thank you,

**Comment by tomolimo** [comment]
but don't forget that if I force the synchro, then the picture is correctly updated/uploaded

**Comment by orthagh** [comment]
yes, my tests will be with ldap_mass_sync.php script, is it ok ?

**Comment by tomolimo** [comment]
yes

**Comment by orthagh** [comment]
what is the name of tht picture fields in your case ?

**Comment by tomolimo** [comment]
thumbnailphoto

**Comment by orthagh** [comment]
Did you have a simple todo to add a photo to an user ? :D

**Comment by tomolimo** [comment]
unfortunately not in my knowledge
we are using an outlook web access addon...
You may try this tool: http://www.codetwo.com/freeware/active-directory-photos/ (just found it on google)

**Comment by tomolimo** [comment]
I just tested this tool and it seems good enough to do what you need :smiley:

**Comment by orthagh** [comment]
I finally paste my photo as hexadecimal value in the attribute editor of active directory tool and i manage to import & sync without error.

In your log, i can't understand why the picture appears in the sql queries.
In the file authldap.class.php from line 2098 (add) or 2113 (update), a few lines ago, the picture input should be removed.

I pushed a try-commit for others errors (sha1 relative)

**Comment by orthagh** [comment]
Another commit finally, i think i found the issue for update.
Test last master and let me know

**Comment by tomolimo** [comment]
After test:
I no longer get errors in php nor in sql, but no picture has been imported (I checked the user who was going to be created in last sql error log).

If you look at the sql error messages: it was liked something was not correctly escaped in the picture string.

**Comment by tomolimo** [comment]
In fact it looks like the file content was inserted into DB instead of the file name itself

**Comment by orthagh** [comment]
no, picture should not be in this query.
Picture is managed by functions User::post_addItem & prepareInputForUpdate.

A little check, is your user have his field authtype = 3 ?

**Comment by tomolimo** [comment]
authtype is 0 and auths_id is 0

**Comment by orthagh** [comment]
ok, i think we got it.

Could you check an already logged user (0 = not yet authentified), you by example ?

**Comment by tomolimo** [comment]
yes,
would you like me to delete my picture and to start a mass_update?

**Comment by orthagh** [comment]
yes. please

**Comment by tomolimo** [comment]
I'm not sure it will be ok, as I still have the error `LDAP server size limit exceeded: user deletion disabled`

**Comment by tomolimo** [comment]
after test : my user picture is not updated (or my user has not been updates)

**Comment by tomolimo** [comment]
if I logout/login then it's ok: the picture is updated

**Comment by orthagh** [comment]
you should empty date_sync field before executing ldap_mass_sync

**Comment by tomolimo** [comment]
ok, I retry

**Comment by tomolimo** [comment]
I'm going to try with another logged in user :)

**Comment by tomolimo** [comment]
date_sync still null after ldap_mass_sync, my user has not been updated, probably the mentioned problem of the LDAP server size limit exceeded...

**Comment by tomolimo** [comment]
If I force a re-synch of my user, the picture is updated immediately, and of coursse the date_sync also :)

**Comment by orthagh** [comment]
When you do that, you also fix the ldap server, no ?

![image](https://cloud.githubusercontent.com/assets/418844/16491745/740b8a90-3edf-11e6-8a88-bb3a29b4c961.png)

**Comment by orthagh** [comment]
for user with auths_id = 0, i mean

**Comment by tomolimo** [comment]
No I was speaking about my own user account, so I don't need to change authentication scheme, and my user account is already with auths_id=16

**Comment by orthagh** [comment]
ok
for pagins issue, you confirm this configuration in your case : 
![image](https://cloud.githubusercontent.com/assets/418844/16491945/1f10fda8-3ee0-11e6-963c-b8d092f11719.png)

**Comment by tomolimo** [comment]
I've got this one:
![image](https://cloud.githubusercontent.com/assets/7569958/16491988/5b60e94e-3ee0-11e6-8ba6-2834065f880c.png)

**Comment by tomolimo** [comment]
So I'll try with unlimited

**Comment by tomolimo** [comment]
I made a new test with unlimited and then I got a complete refresh. I mixed this field with the page size which is 1000 for our AD.
I'm going to retest the picture update with this.

**Comment by tomolimo** [comment]
Good news:
If I clear the picture of my own user account, and start a ldap_mass_sync (without clearing the date_sync) then the picture is updated.
Bad news:
The previous user picture (with auths_id=0 and authtype=0) has not been updated (even if this user has been imported by the script in a previous call).

**Comment by orthagh** [comment]
yes for the second one, i confirm this behavior, i'll check for a fix tomorrow.

Good need for first par anyway.

**Comment by orthagh** [comment]
Ok, i think we fixed the issue.
For summary : 
- ldap_mass_sync sync now users with  authtype = && auths_id != 0
- we (with @wawax) fix the import process to fill this fields on import

It need a manual fix on your side, you should at least set auths_id field to your users, after that, the scripts will manage theirs pictures.

Let me know if it's good to close this issue (and release 0.90.4 in the coming days).

**Comment by tomolimo** [comment]
Yes, that's ok for me, you may close this issue.
FYI: the tests made yesterday were on the 9.1.
thank you,
regards,
Tomolimo

**Comment by Smiley-k** [comment]
I'm sorry, I also want, but how ? tell me how to do it. I can't understand

**Comment by error500** [comment]
In my case, in the LDAP, the field thumbnailphoto brings base64 coded photo. I had to convert the files with 

` $image=imagecreatefromstring($data);`

Principe is : 

Parse your _pirctures folder
for each file, get data, convert it and save it in the same place


```
<?php

/*******************
* L'import des images depuis l'AD donne lieu a des formats encodes et non des formats JPEG.
* Le script suivant traite les fichiers du répertoire picture pour en faire des JPEG conforme.
*/




/**
* Fonction de parcours d'un répertoire (féflextive)
* revoie un tableau
*/

function scanDirectories($rootDir, $allData=array()) {
    // set filenames invisible if you want
    $invisibleFileNames = array(".", "..", ".htaccess", ".htpasswd");
    // run through content of root directory
    $dirContent = scandir($rootDir);
    foreach($dirContent as $key => $content) {
        // filter all files not accessible
        $path = $rootDir.'/'.$content;
        if(!in_array($content, $invisibleFileNames)) {
            // if content is file & readable, add to array
            if(is_file($path) && is_readable($path)) {
                // save file name with path
                $allData[] = $path;
            // if content is a directory and readable, add path and name
            }elseif(is_dir($path) && is_readable($path)) {
                // recursive callback to open new directory
                $allData = scanDirectories($path, $allData);
            }
        }
    }
    return $allData;
}


/**
* Traitement d'un fichier image de GLPI
* L'import des images depuis l'AD donne lieu a des formats encodes et non des formats JPEG.
* Le script suivant traite le fichier pour en faire JPEG conforme.
*/

function convertFileToImage ($imageFile){
	//on ouvre le fishier à traiter
	$handle=fopen($imageFile, 'r+');
	$contents=fread($handle,512000);
	//$contents= file($imageFile);
	fclose($handle);
	
	$name= pathinfo($imageFile);		
	
	
	// Decodage de la chaine 
	$data= base64_decode($contents);
	
	if ($contents != '') {
		// Creation de l'image binaire
		$image=imagecreatefromstring($data);
		
		if ($image !== false) {
			
			// ecriture du fichier
			
			//imagejpeg($image,$name['filename'].'_min.'.$name['extension']);
			imagejpeg($image,$imageFile,100);
			copy($imageFile,$name['dirname'].'/'.$name['filename'].'_min.'.$name['extension']);
			
			//purge de la variable.
			imagedestroy($image);
			return " fichier $imageFile traité";
		}
		else {
			return " fichier $imageFile déjà traité";
		}
	}
	else {
		return " Pas de fichier";
	}
}


/** 
*Exécution MAIN
*/
echo "<h1>goooo</h1>";
$path=realpath (__DIR__.'/../files/_pictures');	

$imageFiles=scanDirectories($path);

foreach ($imageFiles as  $value) {
			
	echo "<br>".convertFileToImage($value);
	
}

```
