### ISSUE TITLE
mass ticket update: add Assigned to

### ISSUE THREAD

**Issue by colttt** [glpi-project/glpi#4500]
Hello,

it would be nice if you add the following feature:
Mass ticket updates, such as when someone is suddenly off work for a few weeks to easily be able to re-assign all of their tickets to the “general queue” or to someone else.

At the moment its not possible, so far as i can see.
![grafik](https://user-images.githubusercontent.com/10084871/44193290-a5638680-a132-11e8-9b2a-f79cade6717f.png)

**Comment by cedric-anne** [comment]
Hi,

If you have rights to update a ticket, you should see an action named "Add an actor", that will give you ability to assign the ticket to a specific user or to a group.

Regards

**Comment by colttt** [comment]
Hi @cedric-anne ,
which right do I need? at the moment I'm a super-admin and thought that I can do everything

**Comment by colttt** [comment]
nope, I try that with a ticket that is assigned to me, and want to change the assignment, but its still not possible, I also try it with new (unassigned) tickets.

So when you said it must be possible, at it isn't - it looks like a bug ;)

**Comment by arthurrschaefer** [comment]
Look @colttt , it's very clear that you need to be able to **"Update tickets"**. 
The pic you posted there is using the update action for massive tickets. And @cedric-anne has warned you to use the **"Add actor"** option.
The super-admin has all rights, so I believe you're just mismatching the massive action you need to use.
Look here:
![image](https://user-images.githubusercontent.com/13874922/44207415-8adddd00-a133-11e8-83dd-51a15b20e9ed.png)

And that's what you should try:
![image](https://user-images.githubusercontent.com/13874922/44207423-93ceae80-a133-11e8-909a-9a881a54e9d0.png)

It's working fine for me.

**Comment by colttt** [comment]
@arthurrschaefer, 
jep I already saw this, but I don't want to add an actor I will replace/update the actor

**Comment by arthurrschaefer** [comment]
All right. I see.

I guess is a new feature, then.
