### ISSUE TITLE
9.2 to 9.3 update error

### ISSUE THREAD

**Issue by do6po** [glpi-project/glpi#4515]
Hi Guys.
After update from 9.2 to 9.3, i have some problems with login for LDAP users. Not for all users, but for some users who were previously assigned superuser rights.
After login i see "You don't have right to connect".
in file php-errors.log only have that
```
[2018-08-20 09:05:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /opt/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: glpilanguage
  Backtrace :
  inc/html.class.php:1154                            
  inc/html.class.php:1823                            Html::includeHeader()
  front/login.php:88                                 Html::nullHeader()
  {"user":"@help2","mem_usage":"0.018\", 2.16Mio)"} 
[2018-08-20 09:05:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /opt/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: 
  Backtrace :
  inc/html.class.php:1154                            
  inc/html.class.php:1823                            Html::includeHeader()
  front/login.php:88                                 Html::nullHeader()
  {"user":"@help2","mem_usage":"0.000\", 2.16Mio)"} 
```
Cheers.

**Comment by orthagh** [comment]
> After login i see "You don't have right to connect".

This message appears when the user you trying to login doesn't have any profiles associated.
As i know, there isn't any change in rights or profiles in 9.2 to 9.3  migration (apart dcim addition).

So some advises for your issue:
- check the affected users, in the authorizations tab, they must have at least one
- The user must be active (in main tab, active field), but i think the error message on login will be different in this case.
- If you have any authorization rules (in administration > Rules), check they are still valid

One last thing, the log you paste don't seems to be relative to your issue :)

**Comment by do6po** [comment]
User is active :
![default](https://user-images.githubusercontent.com/23662926/44328456-47081200-a46a-11e8-923d-09ecb672a4f0.png)

authorizations tab: 
![default](https://user-images.githubusercontent.com/23662926/44330071-c1d32c00-a46e-11e8-824e-603981812678.png)

Rules by default:
![screenshot_2018-08-20 glpi - rules - 2](https://user-images.githubusercontent.com/23662926/44330137-ef1fda00-a46e-11e8-90d4-b785446e2751.png)

Language code:
```locale -a
C
C.UTF-8
POSIX
ru_RU.utf8
```
![default](https://user-images.githubusercontent.com/23662926/44330337-66ee0480-a46f-11e8-9562-7a315a1a8c7c.png)

**Comment by do6po** [comment]
Still can not fix the error.

**Comment by orthagh** [comment]
Could you paste a screenshot of the entire form of a concerned user ?
Also could you precise if you use non glpi authentication (ldap, ntlm, cas, etc) ?

**Comment by orthagh** [comment]
Oh i may have an idea.

On login page, do you the new dropdown for selecting a source.
I think as you have an ldap named Korabel, you should have two options at least:
This ldap Korabel and "internal GLPI database".

Maybe you have other ldap directories setup in GLPI and the user doesn't choose the good source for login.

By the way, if it's the issue, we added in next version (9.3.1) a config option do choose if this login source should be displayed or not, see: https://github.com/glpi-project/glpi/pull/4512
and the diff: https://github.com/glpi-project/glpi/pull/4512/files

**Comment by do6po** [comment]
>Maybe you have other ldap directories setup in GLPI and the user doesn't choose the good source for login.

This user - is me. I choose "Korabel" in drop-down. If i do wrong choice, i see this : 

![default](https://user-images.githubusercontent.com/23662926/44523532-d4ee3200-a6e2-11e8-8d7b-90801141dcf6.png)

The same I see when I type the wrong password.

**Comment by orthagh** [comment]
Ok this is not the issue (i tried)

**Comment by orthagh** [comment]
So currently you succeed to connect with another account (internal database one) ?

**Comment by do6po** [comment]
I can connect over default account "GLPI", and some users from Korabel. 
like this : 
![screenshot_2018-08-23 glpi - users - 285](https://user-images.githubusercontent.com/23662926/44526139-bccee080-a6eb-11e8-9b04-7a5bfe89aa39.png)

**Comment by orthagh** [comment]
Is the failing account have a good DN (in red in your first screenshot, in front authentication label) when you compare to he account who can login ?

**Comment by do6po** [comment]
Thanks to you - I found dependency. When depth of nesting OU <= 3 - user can login, for nesting > 3 - login failed.
I reduced the nesting for my account in the domain, and the login was successful. It is bag?

**Comment by orthagh** [comment]
could you share you GLPI ldap configuration ? especially Connection Filter and BaseDN ?

**Comment by orthagh** [comment]
Oh also, could you indicate the length of the DN of your user, i remember an issue where the dn could be truncated.

**Comment by do6po** [comment]
>could you share you GLPI ldap configuration ? especially Connection Filter and BaseDN ?

![default](https://user-images.githubusercontent.com/23662926/44535734-5a81da00-a703-11e8-9ffc-a9a75ce7d67d.png)

**Comment by do6po** [comment]
>Oh also, could you indicate the length of the DN of your user, i remember an issue where the dn could be truncated

For this OU login do not work : 
 `OU=Бюро системного администрирования,OU=Отдел информационных технологий (ОИТ),OU=Инженерно-техническое направление,OU=Корабел_Пользователи1,DC=korabel,DC=loc`
For this work fine : 
`OU=Отдел информационных технологий (ОИТ),OU=Инженерно-техническое направление,OU=Корабел_Пользователи1,DC=korabel,DC=loc`

**Comment by orthagh** [comment]
I'm not sure it's the same bug as #4319 
But you can test the provided fix: juste change your inc/user.class.php like described here https://github.com/glpi-project/glpi/pull/4344/files#diff-a9c4448deb6265f035355e2a9ca92bc0L3007

**Comment by trasher** [comment]
ping?

**Comment by do6po** [comment]
> 
> 
> ping?

Greetings. The answer will be given after September 17th.

**Comment by do6po** [comment]
After the upgrade from the bugfix, I have all the same problems.

**Comment by do6po** [comment]
do you have any solutions?

**Comment by do6po** [comment]
When can I wait for an update to fix this problem? Thank.
