### ISSUE TITLE
Add Cable ID field when we link network ports

### ISSUE THREAD

**Issue by rubbermaid123** [glpi-project/glpi#4516]
Hi, 

It will be nice to add a field named Cable ID when we link to network ports together. This is nice to have because in Datacenter cables management best practices, we need to identify each connected cables with a unique ID to help DC tech (remote hands) to spot the right cable.

**Comment by orthagh** [comment]
Please use [suggestion website](suggest.glpi-project.org) for feature requests, we are a small team and we need to prioritize developments.
So if your feature is popular on the suggest site, we will implement it.

Regards
