### ISSUE TITLE
[9.3] Profile rights for new assets

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#4517]
Hi everyone,

Ho can I set profile rights for new assets (like PDU, rack...). I'm looking in Assets in profile but nothing... 

![image](https://user-images.githubusercontent.com/12936546/44382690-3e6d1580-a516-11e8-9594-cc628b8d30cb.png)

Any idea ? 

Thanks for your reply

**Comment by orthagh** [comment]
All parts of DCIM  feature are in Management > Data centers line

**Comment by ciadch** [comment]
Awesome thanks a lot
