### ISSUE TITLE
[9.3] Associated elements in ticket edition

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#4519]
Hi !

I have a strange (or desired ?) behaviour with associated elements in tickets. 

When I create a new ticket, I can correctly add associated elements : 

![image](https://user-images.githubusercontent.com/12936546/44390707-38832e80-a52e-11e8-9e02-a81e479bee71.png)

But when I edit a ticket with an associated element, the dropdown menu disappears (?) 

![image](https://user-images.githubusercontent.com/12936546/44390759-5badde00-a52e-11e8-807e-abdb1efb7a7d.png)

![image](https://user-images.githubusercontent.com/12936546/44390744-518bdf80-a52e-11e8-8a43-2745e30b129e.png)

I use a "full admin" user.

Any idea ? 

Thanks a log

**Comment by ladenree76000** [comment]
this is the new behaviour since  GLPI 9.3.
 see here https://forum.glpi-project.org/viewtopic.php?id=162465

**Comment by ciadch** [comment]
Thanks for your return. It's what I suspected :-)
