### ISSUE TITLE
Lack of software inventory, fields with the architecture of a given program (x86, x64, arm, etc.).

### ISSUE THREAD

**Issue by Wolvverine** [glpi-project/glpi#4521]
Lack of software inventory, fields with the architecture of a given program (x86, x64, arm, etc.) - IMHO best place for this is in version table.
This causes that the same program in various architectures appears in the inventory several times instead of in the form of one entry. It can not be changed with the use of dictionary rules because we will lose information about the architecture in which the program is compiled.

**Comment by orthagh** [comment]
Please use [suggestion website](suggest.glpi-project.org) for feature requests, we are a small team and we need to prioritize developments.
So if your feature is popular on the suggest site, we will implement it.

Regards
