### ISSUE TITLE
[9.3] Drag & drop in processing ticket

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#4523]
Hi,

Strange behaviour with drag & drop in processing ticket (followup or task). 

Wen I put a file with drag and drop, I can't see it in flollwup (like it dosen't upload) : 
![image](https://user-images.githubusercontent.com/12936546/44461463-4067cf00-a611-11e8-80aa-8cfad3b15b09.png)
![image](https://user-images.githubusercontent.com/12936546/44461496-5ecdca80-a611-11e8-96b5-c298f8325efa.png)

If I select the file with "selecting them", it works : 

![image](https://user-images.githubusercontent.com/12936546/44461547-98063a80-a611-11e8-8fb7-4f6bae892f37.png)

Any suggestion ?

**Comment by cedric-anne** [comment]
Hi,

I checked the fix proposed in #4526 and it works for me.

I just noticed that when adding a document that already exists for this ticket, document item is not added as it already exists, so there is no new link in timeline.

Regards
