### ISSUE TITLE
Migration scripts 9.1.3 to 9.3

### ISSUE THREAD

**Issue by anahimself** [glpi-project/glpi#4528]
Hi,

We are currently using GLPI since a long time (several years) and planning a migration.

We use GLPI 9.1.3 on linux, and will migrate to last version (9.3) on windows 2K16.

The 9.1.3 has a lot of unused plugins and not very clean, and we plan to start over with a fresh installation, but will need to keep history of tickets/users at least.

Is that possible to just retrieve relations between tickets/comments/users ? I imagine that it could perhaps be a first step to export/import users so that they have the same IDs (and perhaps some other simple tables to have the tickets/comments ?)

Regards,

**Comment by cedric-anne** [comment]
Hi,

The best solution to migrate GLPI from an older version to a new version is to do it on an existing DB. If they are done according to guidelines, plugins should have their own tables (`glpi_plugin_*` tables), so you will be able to drop tables that you do not need anymore.

1) Backup your DB, the `files` directory of GLPI and the `config/config_db.php` file.
2) If you want to move your DB on another server, just restore the backup you just done on this new server.
3) Install GLPI from official release archive (https://github.com/glpi-project/glpi/releases/download/9.3.0/glpi-9.3.tgz).
4) Restore the `files` directory into the new GLPI installation.
5) Restore or create a new `config/config_db.php` file that indicates to GLPI where to find the existing DB.
6) Launch the `scripts/cliupdate.php` script that will make your data compatible with GLPI 9.3.0.

If you want to keep some plugins, you will have to get new versions compatible with GLPI 9.3.

If you want to clean your DB from plugins data, you can identify them easilly as they should be named like `glpi_plugin_%pluginname%_*`. Some plugins can also have create files in `glpi/files/_plugins/%pluginname%`.

Regards

**Comment by anahimself** [comment]
Thank you very much for the clear answer

We will try that way, hoping that the error log will be neat after the migration (not the case for the moment)

The files directory is needed for some data in flat mode I guess ?

**Comment by cedric-anne** [comment]
Files directory contains multiples stuffs, including uploaded files. I think you can clear `_cache`, `_log`, `_sessions` and `_tmp` without risk.

You will be able to delete old items, using "massive actions" on the list views. It is a good option as it can warn you about links that may need to update before deleting items.

**Comment by anahimself** [comment]
Thank you :)

**Comment by gmsantos1988** [comment]
Is it possible migrate rules and templates from GLPI 9.1.3 to GLPI 9.3 only update the database of GLPI 9.3?
