### ISSUE TITLE
[9.3] sla ola time to own - error in view with debug mode on rule auto assign

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#4530]
* Steps to reproduce (which actions have you made) :
assign ola time to own with ticket rules (Debug mode on)

* Expected result :
No errors in view.
(ola time to solve no error)
(sla time to own no error)
(sla time to solve no error)

* Actual result :
[2018-08-23 21:00:20] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: date
  Backtrace :
  inc/levelagreement.class.php:272
  inc/ticket.class.php:4717                          LevelAgreement->showForTicket()
  inc/commonglpi.class.php:468                       Ticket->showForm()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"2@glpidev","mem_usage":"0.018\", 3.26Mio)"}
[2018-08-23 21:00:20] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: olalevels_id
  Backtrace :
  inc/levelagreement.class.php:274
  inc/ticket.class.php:4717                          LevelAgreement->showForTicket()
  inc/commonglpi.class.php:468                       Ticket->showForm()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

* URL of the page :
http://192.168.1.108/front/ticket.form.php?id=8609

* Screenshot of the problem (if pertinent) :
![unbenannt](https://user-images.githubusercontent.com/19192087/44546527-83f93080-a718-11e8-8027-65fe01453391.PNG)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
Operating system: Linux glpidev 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64
PHP 7.2.7-0ubuntu0.18.04.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, recode, session,
	shmop, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter,
	xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at 192.168.1.108 Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36
Server Software: Ubuntu 18.04
	Server Version: 10.1.34-MariaDB-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpidbuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is not present
Database version seems correct (10.1.34) - Perfect!Database version seems correct (10.1.34) - Perfect!
OK/etc/glpi/ : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_cache : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
```

**Comment by trasher** [comment]
Please check with fix in #4541
