### ISSUE TITLE
[9.3.0] issue with images in mail

### ISSUE THREAD

**Issue by Gmognon** [glpi-project/glpi#4534]
The GLPI team.

------------
* Steps to reproduce (which actions have you made) :
Inset a solution with a embedded image in the body

* Expected result :
Receive a mail with the text and the image

* Actual result :
Receive a mail with the text and and error in the place of a image saying: "_The image could not be show, maybe the file was removed or renamed...."_ 

* URL of the page :

* Screenshot of the problem (if pertinent) :
![image](https://user-images.githubusercontent.com/42303359/44583094-3f05e600-a77a-11e8-8d3d-aaa9200eefe7.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.3.0 ( => /var/www/virtual/glpi.automatus.net) Installation mode: TARBALL
--

Operating system: Linux aut-s1v-st02 3.10.0-862.6.3.el7.x86_64 #1 SMP Tue Jun 26 16:32:21 UTC 2018 x86_64 PHP 7.2.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.57 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.9-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (10.3.9) - Perfect! /var/www/virtual/glpi.automatus.net/config : OK /var/www/virtual/glpi.automatus.net/files : OK /var/www/virtual/glpi.automatus.net/files/_dumps : OK /var/www/virtual/glpi.automatus.net/files/_sessions : OK /var/www/virtual/glpi.automatus.net/files/_cron : OK /var/www/virtual/glpi.automatus.net/files/_graphs : OK /var/www/virtual/glpi.automatus.net/files/_lock : OK /var/www/virtual/glpi.automatus.net/files/_plugins : OK /var/www/virtual/glpi.automatus.net/files/_tmp : OK /var/www/virtual/glpi.automatus.net/files/_cache : OK /var/www/virtual/glpi.automatus.net/files/_rss : OK /var/www/virtual/glpi.automatus.net/files/_uploads : OK /var/www/virtual/glpi.automatus.net/files/_pictures : OK /var/www/virtual/glpi.automatus.net/files/_log : OK Web access to files directory is protected : OK SELinux mode is Enforcing SELinux boolean configuration for httpd_can_network_connect --> on SELinux boolean configuration for httpd_can_network_connect_db --> off (Some features may require this to be on) SELinux boolean configuration for httpd_can_sendmail --> on

htmLawed version 1.2.4 in (/var/www/virtual/glpi.automatus.net/lib/htmlawed) SimplePie version 1.5.1 in (/var/www/virtual/glpi.automatus.net/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/var/www/virtual/glpi.automatus.net/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/virtual/glpi.automatus.net/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/virtual/glpi.automatus.net/vendor/true/punycode/src) iacaml/autolink in (/var/www/virtual/glpi.automatus.net/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/virtual/glpi.automatus.net/vendor/sabre/vobject/lib) phpCas version 1.3.5 in (/usr/share/pear)

**Comment by cedric-anne** [comment]
Hi,

We made a lot of fixes that can be related to your problem. Can you try with latest commit of branch 9.3/bugfixes to see if you still have the problem ?

Regards

**Comment by Gmognon** [comment]
Hello @cedric-anne, I took a look in the 9.3.1 milestone and couldn't find anything about this problem solved.

**Comment by cedric-anne** [comment]
Sorry, I just fix milestone asignation.

https://github.com/glpi-project/glpi/issues/4345
https://github.com/glpi-project/glpi/issues/4236

**Comment by cedric-anne** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/4345.
