### ISSUE TITLE
[9.3.0] Private followup visibility on email notification. 

### ISSUE THREAD

**Issue by miodzio97** [glpi-project/glpi#4535]
Hi, I have problem with visibility private followup on email notification:

1. We create in ticket public nad private followups.
1. We set GLPI to send to requester automatically tickets notification via email (when create ticket/add followups for ticket/ when close ticket).
2. We have template for this notifications with these tags:
---------------------------------------------------------------------------------------------------------------------##FOREACHfollowups##
##lang.followup.date##: ##followup.date##
##lang.followup.author##: ##followup.author##
##lang.followup.description##: ##followup.description##
---------------------------------------------------------------------------------------------------------------------
##ENDFOREACHfollowups##

* Expected result 
GLPI should not attach private followups using ##FOREACHfollowups## tag. Private followups should be always private. Tag ##followup.description## should add non private followups. Should be additional tag for private followups e.g. ##privatefollowup.description##.

* Actual result :
Actually on the example ticket below GLPI:
![image](https://user-images.githubusercontent.com/32955663/44583084-20b4e000-a7a4-11e8-9182-c7322fd3477b.png)

1. We add first private followup - notification has not been send.
2. Then we add public followup - **notification has been send with private followup description**. It should not work that way.
![image](https://user-images.githubusercontent.com/32955663/44583048-febb5d80-a7a3-11e8-961f-b7d9fe56cc69.png)

Is there any solution at the moment?

We have GLPI 9.3.0

**Comment by orthagh** [comment]
You should check the profile of the requester, if he has the right to see privates followups and tasks, the notifications he'll receive will contains theses parts:

![image](https://user-images.githubusercontent.com/418844/44707312-78a15e80-aaa4-11e8-9d29-78f4c17ca9a2.png)

**Comment by orthagh** [comment]
Coudl you save the form you posted in your screenshot in test again ?

**Comment by miodzio97** [comment]
After saving profile settings again private followups are not included in notification.
Thank You so much orthagh!!!

**Comment by seb1435** [comment]
I have exactly the same behavior... Have re-saved the rights but no success...
