### ISSUE TITLE
[0.90.1] Not able to reassign a ticket

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#454]
After the upgrade to the 0.90.1 new profiles (so created after the migration) are not able to re assign a ticket to another technician or to remove themselves as assigner.
The people who's trying to give the ticket to someone else are the current assigner of the ticket
the error we get is "this action is not allowed".
in the profile-assistance-ticket they have everything flagged (of course also on "assign").

I've also tried to change the assigner through the change of the category (we use automatic assignment through specific the flag in the entity settings) but it does not work on update of the tickets. so it assign correctly to the right group for New tickets, but if I change category, it does not chenage the assigner.

any idea?

davide

**Comment by tomolimo** [comment]
Hello,
Do you have any errors in log files?
thank you
Tomolimo

**Comment by Giudy** [comment]
unfortunately I don't find anything. nothing in _log, nothing access.log or in error.log, nothing with debug mode in glpi
it seems that it is the application that behave in this way as "correct" functionality.
but the profile has these permissions:
![image](https://cloud.githubusercontent.com/assets/7987648/13006813/dd319f9e-d18b-11e5-883b-9c1179e52878.png)

if I delete the group that is the only one assigned to the ticket I get this error
![image](https://cloud.githubusercontent.com/assets/7987648/13006859/2fc38632-d18c-11e5-9bf9-3593f68d2eb2.png)


the only things that is possible to do is to assign the ticket ALSO to the user himself, without deleting others assigners

**Comment by tomolimo** [comment]
Could you do a try?
Go to GLPI folder and open the file "/config/define.php",
And change 
`define("GLPI_USE_CSRF_CHECK", "1");`
by
`define("GLPI_USE_CSRF_CHECK", "0");`

save and retry

**Comment by Giudy** [comment]
HI, nothing changed unfortunately.

d

**Comment by tomolimo** [comment]
then there is a bug somewhere :(

**Comment by Giudy** [comment]
do you think it is a bug or an inconsistency of my db/settings?

**Comment by Giudy** [comment]
The weird thing is that notifications are sent even if nothing is changed in the ticket after trying to delete an assigner.

**Comment by Giudy** [comment]
your soultion worked once, but just once, on a test environment.
After this time in which I was able to change the assignment (I could delete 1 and add another 1)
it didn't work any more

**Comment by tomolimo** [comment]
What is your configuration?
GLPi, web server, hosting server, authentication scheme, ...

**Comment by Giudy** [comment]
Windows 2008 R2 server with NTLM authentication..

Operating system: Windows NT MILS007I0005 6.1 build 7601 (Windows Server
2008 R2 Standard Edition Service Pack 1) i586
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML,
apache2handler, bcmath, bz2, calendar, ctype, curl,
date, dom, eAccelerator, ereg, exif, fileinfo, filter, ftp, gd, gettext,
hash, iconv, imap, json, ldap, libxml, mbstring,
mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql,
pdo_sqlite, session, soap, sockets, sqlite3, standard,
tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="256M" post_max_size="17M"
safe_mode="" session.save_handler="files"
upload_max_filesize="16M"
Software: Apache/2.4.4 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/0.9.8y
PHP/5.4.16 (Apache/2.4.4 (Win32) mod_authnz_sspi/0.1.0
OpenSSL/0.9.8y PHP/5.4.16 Server at mils007i0005 Port 80)
Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0;
SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media
Center PC 6.0; .NET4.0C; .NET4.0E)
Server Software: MySQL Community Server (GPL)
Server Version: 5.5.32-log
Server SQL Mode:
Parameters: *****
Host info: 127.0.0.1 via TCP/IP
OKC:\xampp\htdocs\glpi/config : OK
OKC:\xampp\htdocs\glpi/files : OK
OKC:\xampp\htdocs\glpi/files/_dumps : OK
OKC:\xampp\htdocs\glpi/files/_sessions : OK
OKC:\xampp\htdocs\glpi/files/_cron : OK
OKC:\xampp\htdocs\glpi/files/_graphs : OK
OKC:\xampp\htdocs\glpi/files/_lock : OK
OKC:\xampp\htdocs\glpi/files/_plugins : OK
OKC:\xampp\htdocs\glpi/files/_tmp : OK
OKC:\xampp\htdocs\glpi/files/_rss : OK
OKC:\xampp\htdocs\glpi/files/_uploads : OK
OKC:\xampp\htdocs\glpi/files/_pictures : OK
OKC:\xampp\htdocs\glpi/files/_log : OK

Libraries

htmLawed version 1.1.20 in (C:\xampp\htdocs\glpi\lib\htmlawed)
phpCas version 1.3.4 in (C:\xampp\htdocs\glpi\lib\phpcas)
PHPMailer version 5.2.8 in (C:\xampp\htdocs\glpi\lib\phpmailer)
ZetaComponent ezcGraph installed in (C:\xampp\htdocs\glpi/lib/zeta/Base):
 OK
Zend Framework version 2.4.9 in (C:\xampp\htdocs\glpi\lib\Zend)
SimplePie version 1.3.1 in (C:\xampp\htdocs\glpi\lib\simplepie)
TCPDF version 6.2.12 in (C:\xampp\htdocs\glpi\lib\tcpdf)
ircmaxell/password-compat in (C:\xampp\htdocs\glpi\lib\password_compat).
Compatitility: Ok

**Comment by Giudy** [comment]
another note: the user can add himself as Assigner, but then he cannot delete anymore himself.

**Comment by tomolimo** [comment]
Are you using entities to define rights?

**Comment by Giudy** [comment]
no, everything is done by profiles

**Comment by tomolimo** [comment]
don't you have entities?

**Comment by tomolimo** [comment]
all items are in the root entity?

**Comment by Giudy** [comment]
ciao,
 si 1 entity and everything in that entity

2016-02-12 15:59 GMT+01:00 tomolimo <notifications@github.com>:

**Comment by Giudy** [comment]
Here there is a video with the weird behavior 
https://onedrive.live.com/redir?resid=8FBBD06097AEE1E9!1427&authkey=!AKEX_FMZkEmZv2k&ithint=video%2cmp4

**Comment by Giudy** [comment]
last comment of the day.
enabling everything in the profile settings, anyway the users cannot re assign the ticket.
Created a brand new profile and also this cannot reassign the ticket
is someone experiencing the same issue?

**Comment by yllen** [comment]
"if I delete the group that is the only one assigned to the ticket I get this error"

You have this error if you use a ticket template with mandatory group

**Comment by Giudy** [comment]
yes, true, but I get the same error even if I try to delete 1 assigner when
I have more than 1 assigner\

davide

2016-02-12 19:22 GMT+01:00 yllen <notifications@github.com>:

**Comment by tomolimo** [comment]
Hello,
In order to trace down this problem, could you try to narrow down this problem to a minimal database and configuration in order to be able to reproduce it?
After that, could you send your database (in zip) so that one can try to reproduce this behavior?
Thank you,
regards,
Tomolimo

**Comment by Giudy** [comment]
Ciao,
 ok, I'll try this morning.

davide

2016-02-15 9:07 GMT+01:00 tomolimo <notifications@github.com>:

**Comment by Giudy** [comment]
Incredible.. solved. it was the plugin "generic objects".
once given the permissions to all the objects to the profile, everything started working.
I will report the bug to the plugin github page

thanx for the time spent on this issue

davide

**Comment by Giudy** [comment]
https://github.com/TECLIB/genericobject/issues/85
