### ISSUE TITLE
Associated item with mailcollector

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#4542]
* Steps to reproduce (which actions have you made) : 
Create a rule with criteria : 
![image](https://user-images.githubusercontent.com/39367117/44659803-b8653900-aa05-11e8-84f2-5dd3e84e077d.png)

And action : 
![image](https://user-images.githubusercontent.com/39367117/44659500-bcdd2200-aa04-11e8-9210-9a7f304e8ef5.png)
Use the mailcollector for import a mail containing this mail content : 
PC : PCName.DomainName

* Expected result :
Create the ticket with the associated element linked

* Actual result :
Create the ticket with in the description the content of the mail.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI version 9.2.3 & 9.2.4 (9.2-bugfixes)
No plugin activated.

**Comment by orthagh** [comment]
The `affectbyfqdn` action currently need the asset to be associated with a network port and for that port, it need to have a network name with a fqdn (domain)

![image](https://user-images.githubusercontent.com/418844/44667059-16038080-aa1a-11e8-90c2-7261ef5391ee.png)

The field named domain directly available on the computer form is, i think, currenltly not used for this rule action.

I don't know who created this action in the past, but he didn't do the action do what you think.

So the issue if more a feature request.

**Comment by keha35** [comment]
Thanks for the reply.

I've test and it work when i create a ticket, the element is correctly add the element.
But when i update a ticket it didn't add the element in the ticket.
