### ISSUE TITLE
[9.3] Undefined variable table while calling API

### ISSUE THREAD

**Issue by HynekPetrak** [glpi-project/glpi#4546]
When calling API to search for items, like:

http://wacz00133/ceei/glpi/apirest.php/search/AllAssets?range=0-21420&uid_cols=true

I get the following error:

[2018-08-28 16:00:15] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\ceei\glpi\inc\toolbox.class.php line 657
  *** PHP Notice(8): Undefined variable: table
  Backtrace :
  inc\search.class.php:4449                          Search::giveItem()
  inc\search.class.php:1388                          Search::giveItem()
  inc\search.class.php:314                           Search::constructData()
  inc\api.class.php:1446                             Search::getDatas()
  inc\apirest.class.php:193                          API->searchItems()
  apirest.php:45                                     APIRest->call()
  {"user":"2821@WACZ00133","mem_usage":"0.001\", 153.78Mio)"}

**Comment by orthagh** [comment]
With GUI, could you enabled debug mode:
![image](https://user-images.githubusercontent.com/418844/44770174-781dcc00-ab67-11e8-95d5-78a8b1b9aa15.png)

And see in Assets > Global menu, if you replicate the issue.

**Comment by trasher** [comment]
this happens when "Last update" field is displayed
