### ISSUE TITLE
Clean deprecated functions always used in core

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4548]

**Comment by yllen** [comment]
Sorry i don't understand.
This function is indicated deprecated since 9.2. When you indicate a function as deprecated, you must delete all calls of this function and not when you delete the function.

**Comment by trasher** [comment]
> This function is indicated deprecated since 9.2.

This has been removed to make things clear: https://github.com/glpi-project/glpi/commit/6f70710ac1c8ddb5aef85a765f4781c7440f712f

**Comment by yllen** [comment]
If a function is a call to another function, this function is deprecated even if "deprecated" is not indicated in the comments of this function.

**Comment by trasher** [comment]
We've already talked about that, almost a year ago (https://github.com/glpi-project/glpi/issues/2915).

So, to resume:
- the DBUtils class has been created for unit tests (it is **not** possible to mock global and static functions)
- adding a `new DBUtils()` everywhere is a dumb solution, so we'll keep "old" methods until we get a reliable solution (probably a dependency injection system).

Please do not reopen this one again, this is not an issue, those methids are not deprecated, and are no longer marked as.

**Comment by trasher** [comment]
Yes, thank you.
