### ISSUE TITLE
Couldn't massive-action move entities outside of root entity

### ISSUE THREAD

**Issue by Bigjoke007** [glpi-project/glpi#4552]
I tried to move some entities from Root to child entity with massive action

* Steps to reproduce (which actions have you made) :
Select some entities in root
Chose action move

* Expected result :

Dropdown list to chose on which sub entities to gp

* Actual result :
Only root entity available in drop down list

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
9.2.3
```

**Comment by orthagh** [comment]
duplicate #4437
