### ISSUE TITLE
Error run task contracts

### ISSUE THREAD

**Issue by karbotar** [glpi-project/glpi#4553]
[2018-08-30 11:32:57] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 180
  *** MySQL query error:
  SQL: SELECT `glpi_items_devicenetworkcards`.*,
                              `glpi_contracts_items`.`id` AS IDD,
                              `glpi_entities`.`id` AS entity
                        FROM `glpi_contracts_items`,
                              `glpi_items_devicenetworkcards` LEFT JOIN `glpi_entities`
                              ON (`glpi_items_devicenetworkcards`.`entities_id`=`glpi_entities`.`id`)  WHERE `glpi_items_devicenetworkcards`.`id` = `glpi_contracts_items`.`items_id`
                           AND `glpi_contracts_items`.`itemtype` = 'Item_DeviceNetworkCard'
                           AND `glpi_contracts_items`.`contracts_id` = '1' AND ( `glpi_items_devicenetworkcards`.`entities_id` = '0'  )
                     ORDER BY `glpi_entities`.`completename`, `glpi_items_devicenetworkcards`.`name`
  Error: Unknown column 'glpi_items_devicenetworkcards.name' in 'order clause'
  Backtrace :
  inc/contract_item.class.php:275
  inc/contract.class.php:1244                        Contract_Item::getItemsForContract()
  :                                                  Contract::cronContract()
  inc/crontask.class.php:836                         call_user_func()
  front/cron.php:77                                  CronTask::launch()

**Comment by trasher** [comment]
Which GLPI version are you using? You should try with last 9.3/bugfixes nightly build if this still occurs.

**Comment by trasher** [comment]
No feedback from a while, closing.
