### ISSUE TITLE
Help - Business Rules for Tickets

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#4556]
Hello
Could anyone tell me if the GLPI in version 9.2.3 automatically assigns the "Priority" of a call as "Medium"?

I see this after my upgrade from version 9.2.1 to 9.2.3
 
My rule is as follows:

Rule name: test
Criteria: when the "Category" is "XPTO"
Do: * "Priority"> Assign> Low
• SLAs Time to Work> Assign> X hours

However, after these steps he always assigns the category "Medium"

Can someone help me?

IMG1

![img1](https://user-images.githubusercontent.com/35368369/44853356-26934100-ac3c-11e8-8688-c08f2e37fa71.PNG)

img2

![img2](https://user-images.githubusercontent.com/35368369/44853370-2dba4f00-ac3c-11e8-893e-37749a702897.PNG)

IMG3

![img3](https://user-images.githubusercontent.com/35368369/44853375-31e66c80-ac3c-11e8-9865-ae3af846946e.PNG)

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
