### ISSUE TITLE
Authorization profile to import LDAP users in Expert mode

### ISSUE THREAD

**Issue by HynekPetrak** [glpi-project/glpi#4561]
Hello
which authorization is required to import LDAP users in the "Expert mode"? I found it possible only with "super-admin" profile. 
We need to delegate it to and "Admin", "IT" or a new dedicated profile, but I have not found how.
Thanks for help.

**Comment by cedric-anne** [comment]
Hi,

You can find corresponding right in `Administration` tab of profile. It is called `Add external` and has to be added in `Users` row.

Regards

**Comment by HynekPetrak** [comment]
Hi, this enables the simple mode only. I'm looking for the Expert mode of LDAP user import.

**Comment by cedric-anne** [comment]
Expert mode is not available in modal context, wich means that you cannot use it when importing a user in the Ticket form context.

Here is a fix for an edge case, but I am not sure it is yours: https://github.com/glpi-project/glpi/pull/4565.

**Comment by HynekPetrak** [comment]
The #4565 seems it will fix my case. Thank you. Will test&feedback once released.
