### ISSUE TITLE
[9.3 & 9.2] Different behavior in entity search

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#4562]
GLPI 9.3 & 9.2

* Steps to reproduce (which actions have you made) :

1. Creation of an entity with the name "Entity".

2. Search for the entity by name with "Entite" in the interface of entities : 
![entity](https://user-images.githubusercontent.com/15138371/44973412-c6164380-af5c-11e8-98b3-e135ddeec843.png)
The entity "Entité" is well found.

3. Search to change the active entity by the name "Entite": 
![entity2](https://user-images.githubusercontent.com/15138371/44973583-56ed1f00-af5d-11e8-96ef-3c685636d682.png)
The entity "Entité" is not found.

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3 & 9.2

**Comment by trasher** [comment]
MySQL/MariaDB search (first case) does not take care of accentued characters (search on "é" or "e" or "è", you will have same results).
On the second case, search is done with javascript; wich takes care of accents.

I do not have any elegant solution to get that solved (only ugly hacks), that seems to me a lot of work for a very small issue.

(BTW, the same exact problem will be caused if we implement a postgresql support: searching for '"entité" will never return "entite")

**Comment by amma35** [comment]
Okay, thanks for the feedback. I'll look into it.

**Comment by cedric-anne** [comment]
Hi,

Not sure of that, but maybe the solution to use unicode collate is (see http://php.net/manual/fr/mysqli.set-charset.php#121647) : 
```diff
diff --git a/inc/dbmysql.class.php b/inc/dbmysql.class.php
index d469db3d5..e0de459a1 100644
--- a/inc/dbmysql.class.php
+++ b/inc/dbmysql.class.php
@@ -118,7 +118,7 @@ class DBmysql {
          $this->connected = false;
          $this->error     = 1;
       } else {
-         $this->dbh->set_charset(isset($this->dbenc) ? $this->dbenc : "utf8");
+         $this->dbh->query("SET NAMES utf8 COLLATE utf8_unicode_ci");
 
          if (GLPI_FORCE_EMPTY_SQL_MODE) {
             $this->dbh->query("SET SESSION sql_mode = ''");
```
By the way, is the `$this->dbenc` a dead variable ?

To makes 'Entite' shown on result, a solution could be following patch, but search will be fuzzy (really fuzzy) :
```diff
diff --git a/inc/entity.class.php b/inc/entity.class.php
index 42e00f327..1766a28fc 100644
--- a/inc/entity.class.php
+++ b/inc/entity.class.php
@@ -1114,7 +1114,7 @@ class Entity extends CommonTreeDropdown {
                         // the `plugins` array allows you to configure the active plugins on this instance
                         'plugins' : ['search', 'qload', 'conditionalselect'],
                         'search': {
-                           'case_insensitive': true,
+                           'fuzzy': true,
                            'show_only_matches': true,
                            'ajax': {
                               'type': 'POST',
```
