### ISSUE TITLE
Install date become negative if 0000-00-00 date on OCS

### ISSUE THREAD

**Issue by mzulfahmy** [glpi-project/glpi#4568]
Steps to reproduce : Open Computer -> Software tab
Expected result : Date same with OCSInventory 
Actual result : Become -0001-11-30
URL of the page : http://localhost/glpi/ajax/common.tabs.php?_target=/glpi/front/computer.form.php&_itemtype=Computer&_glpi_tab=Computer_SoftwareVersion$1&id=20561&withtemplate=
 Screenshot of the problem (if pertinent) :
![12](https://user-images.githubusercontent.com/4937448/45017412-20e19500-b05a-11e8-942a-be74949ec0f8.PNG)

GLPI Version
[code]
GLPI 9.3.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

**Comment by cedric-anne** [comment]
Hi,

It is related to OCS plugin itself.
Looks like it has been fixed in the 1.5.3 version.

Regards
