### ISSUE TITLE
Bad class for ITILSolution

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#4575]
`ITILSolution` should extends `CommonDBChild`, not `CommonDBTM`

Bad effect:

History is recorded for` itemtype = ITILSolution` (so can't be read), instead of `item = Ticket`, and `itemtype_link= ITILSolution`

**Comment by trasher** [comment]
Seems like the same for the Followups class... But I guess there are several workarounds for the followups :(

**Comment by cconard96** [comment]
Follow-ups were changed to extend commonitilfollowup which extends CommonDBChild in #4558. Only solutions need changed.
