### ISSUE TITLE
[GLPI 9.2.3] PHP error message 

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#4584]
HI
 After installation of the GLPI 9.2.3 version, I receive this kind of message in the PHP-errors.log file:

2018-05-05 10:22:20 [1446@chms0028]
 From Toolbox::deprecated() in /usr/share/glpi/inc/toolbox.class.php line 486 (0.000", 3.43Mio)
 closeArrowMassives() method is deprecated
 2018-05-05 10:22:20 [1446@chms0028]
 Backtrace :
 inc/toolbox.class.php:487 Toolbox::backtrace()
 inc/html.class.php:2038 Toolbox::deprecated()
 inc/lock.class.php:313 Html::closeArrowMassives()
 inc/lock.class.php:348 Lock::showForItem()
 inc/commonglpi.class.php:482 Lock::displayTabContentForItem()
 ajax/common.tabs.php:96 CommonGLPI::displayStandardTab()

My config GLPI 9.2.3 / fusioninventory 9.2 + 1.1 / PHP 7.2.4
 Could you check this message please?

**Comment by trasher** [comment]
Dups https://github.com/glpi-project/glpi/issues/2394
