### ISSUE TITLE
[GLPI 9.2.3] massive action -->PHP error message 

### ISSUE THREAD

**Issue by FRANCOIS50** [glpi-project/glpi#4585]
Hi
 during massive action "unlock elements" on computer I receive this kind of PHP errors messages:

2018-05-05 12:10:58 [1446@chms0028]
 *** PHP Notice(8): Undefined index: Computer_Item
 Backtrace :
 inc/massiveaction.class.php:1282
 inc/lock.class.php:546 MassiveAction->itemDone()
 inc/massiveaction.class.php:993 Lock::processMassiveActionsForOneItemtype()
 inc/massiveaction.class.php:972 MassiveAction->processForSeveralItemtypes()
 front/massiveaction.php:63 MassiveAction->process()

My config GLPI 9.2.3 / fusioninventory 9.2 + 1.1 / PHP 7.2.4
 Could you check this message please?

**Comment by trasher** [comment]
Try with latest release to see if issue still exists.

**Comment by cedric-anne** [comment]
@FRANCOIS50 

I made a fix in #4611. Could you test it please ?

Regards
