### ISSUE TITLE
Move item "completename" to end of array in Location::rawSearchOptionsToAdd() as a workaround for a bug

### ISSUE THREAD

**Issue by loicbenoit** [glpi-project/glpi#4589]
### Proposal
In Location::rawSearchOptionsToAdd(), move item "completename" to end of array (last array position).

### Should have no impact on GLPI
I tested the modification in GLPI 9.3.0 and found no obvious impact. In theory, it should not have any impact on anything, except...

### Why?
It would seriously and immediately alleviate a bug in plugin DataInjection that makes it impossible to map the location field when importing data. **Fixing the bug will take a lot of time**, so an immediate workaround is needed to **help GLPI users quickly with such a common usage scenario**.

The problem is [explained by Cedric-Anne](https://github.com/pluginsGLPI/datainjection/issues/121#issuecomment-419071200). It stems from using the "linkfield" of items in search options instead of "id" or "table.field".

* URL of the page :
https://github.com/pluginsGLPI/datainjection/issues/121

**Comment by trasher** [comment]
Such a change is not something I'd like to see in the core.

The way the plugin parses search options is certainly not optimal, it should be fixed on the plugin side.
This is certainly a huge work, and a q&d hack may be implelmented... But on the plugin side, not on the core.
