### ISSUE TITLE
[GLPI 9.2.4] Catégorie missing in notiffication

### ISSUE THREAD

**Issue by cedrobert** [glpi-project/glpi#4590]
* Steps to reproduce (which actions have you made) :
First create a rule to assigne tickets to a group based on category and configure notification to the groupe, using "##ticket.category##" to display the category in notification.
Then create a ticket without category and save it.
Next with an other user add the category to the ticket, the rule affect the ticket to the correct group.
All members of group receive a notification, but the value for "##ticket.category##" is null.

* Expected result :
the value of "##ticket.category##" must correspond to the category

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

GLPI 9.2.4 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

**Comment by cedrobert** [comment]
I try with 9.3.0, and the issue is still present.
I'll wait for 9.1.3.
thanks for your help.

**Comment by orthagh** [comment]
Here is an example for notification template

```
##IFticket.category## ##lang.ticket.category## : ##ticket.category## ##ENDIFticket.category## ##ELSEticket.category## ##lang.ticket.nocategoryassigned## ##ENDELSEticket.category##
```

Regards
