### ISSUE TITLE
Command line scripts component

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#4592]
All command line scripts are specific and do not rely on any existing component.

We should rely on an existing component to handle all script commands, akingn possible to extend a base from/for plugins, ..., ..., ...
What we mainly want from such a component is:
- arguments parsing (optionaly validation),
- output formatting facilities.

We've discussed about several possibilities including Zend Console, League Climate and Symfony Console.

1- Zend Console

This is a light component already used for cliinstall script. But several capabilities of the component only rely on other Zend components, and there are not output facilities.

2- Climate

It's really standalone, offers output facilities, but no arguments parsing ones.

3- Symfony Console

Can be used as a standalone component (even if the docs always suggests to use other SF framework components).

As the only to provide arguments parsing and outpout facilities is the Symfony Console; it's the one we're probably going to implement.
There are certainly other possibilities we do not look at, but we aslo want to rely on something quite widely used and that will be maintained in time.

**Comment by orthagh** [comment]
One point i didn't mention in previous conversation.
We need `commands` or routing (like laravel artisan output or robo one)

A empty call of the cli tools must list all available commands.

This need excludes climate (mainly a cli helper)

**Comment by orthagh** [comment]
bash/zsh completion could be plus (sf have a optionnal package for that)

**Comment by cedric-anne** [comment]
To route to system process, we could use symfony/process (even if we do not use symfony/console).

**Comment by trasher** [comment]
Completion has not been added yet. Aother ticket can be opened and change made separately. Cli commands has been changed, and documentation as well. See https://glpi-install.readthedocs.io/en/develop/command-line.html
