### ISSUE TITLE
In 'project tasks' tab of a project, type (of task) doesn't take into account available translations

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#46]
0.85.4 & 0.90
In 'project tasks' tab of a projet, column type (of task) doesn't take into account the possible available translation to the current language of type of task.
Same for Status (of tasks) : verified for 0.85.4. But cannot confirm for 0.90 because I can no longer click the items in dropdown 'Task Status'.

**Comment by wawax** [comment]
Bug reproduced

**Comment by yllen** [comment]
I don't have problem. If i have translate Type of project task, the translated name appeared in the dropdown Type of the task.

**Comment by yllen** [comment]
OK i understand. It's not when you create a task but after in the list of created tasks

**Comment by blerohellec** [comment]
The first point is corrected (task type).
But I can't test the 2nd one, because in 0.90, I can't modify the values of the 'project status' dropdown.
The values are no longer clickable (regression from 0.85).

**Comment by yllen** [comment]
I can select value in project status dropdown.
But in 0.85 as in 0.90 there is a big problem: states aren't translated and can't be updated (just with massive actions).
I reopen this issue

**Comment by yllen** [comment]
Reste le problème des intulés concernant les projets non traduits

**Comment by blerohellec** [comment]
0.90
I can now modify values of 'statuses of project' dropdown, add translations...
Translations of task's statuses are correctly taken into account.

BUT coming back to the 'project tasks' tab of a project, I have now task's status ALSO in column Type (I have twice task's status !).
And the color of the Task's status is always Green, when I have different tasks with different statuses.

**Comment by blerohellec** [comment]
Corrected. Thx

**Comment by blerohellec** [comment]
In column Type of 'project tasks' tab of a project, The type of task is no longer translated (regression)

**Comment by blerohellec** [comment]
It's a bit more complicated (see image attached)
In a project, I've got 4 tasks and 1 sub-task. They all use 2 different types of task. Both types of task have translation in French (a task type name followed by (fr) is a translation).
On screen, the type of task is sometimes translated, sometimes not !
![screenshot from 2015-09-01 11 55 28](https://cloud.githubusercontent.com/assets/9383475/9601320/e6828606-50a0-11e5-9f26-c92d9fd4ee2e.png)

**Comment by blerohellec** [comment]
In inc/projecttask.class.php, funct showFor(), line 817 (in 0.90), there is an error : the join clause between glpi_projecttasks and glpi_dropdowntranslations for Project task Type is made on the Project task ID, and not the Project type Task ID.
Hence the error.

**Comment by blerohellec** [comment]
Perfect. Thx
