### ISSUE TITLE
Operating System in GLPI not Updated after Client is Migrated to W10.

### ISSUE THREAD

**Issue by rschubnell** [glpi-project/glpi#4605]
Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps :

* We don't support community plugins. Contact directly their authors, or use the community forum : http://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (http://forum.glpi-project.org) is the best place.
* Please use the below template.
* Delete this text before submiting your issue.

The GLPI team.

------------
* Steps to reproduce (which actions have you made) :
Operating System in GLPI not Updated after Client is Migrated to W10.
We are using fusion inventory 9.3+1.1

* Expected result :
On the Assets - Computers - Computer - Operating Systems the Value is still W7 and not W10.
We see this also with CentOS Machines which are updated from 6.9 to 6.10

* Actual result :

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```9.3+1.1 
paste here
```

**Comment by orthagh** [comment]
Hello.

Do you use fusioninventory plugin ?

**Comment by trasher** [comment]
This is a plugin issue, not GLPI.

**Comment by rschubnell** [comment]
Yes


Thursport Fitnessclub
Antara Gruppenkurse
071 / 622 82 11
mailto: kontakt@thursport.ch
http://www.thursport.ch

**Comment by trasher** [comment]
BTW, see and send feeback on https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2644.

**Comment by trasher** [comment]
same answer.
