### ISSUE TITLE
Fatal error adding computer to enclosure

### ISSUE THREAD

**Issue by jframeau** [glpi-project/glpi#4607]
* Steps to reproduce (which actions have you made) :
- select French language as locale
- create an Enclosure
- add Computer item

* Expected result :
A new computer added to the enclosure

* Actual result :
Item dropdown is not displayed when using French locale while ok using English locale.

* Screenshot of the problem (if pertinent) :
In French
![image](https://user-images.githubusercontent.com/498115/45307274-e6c33800-b51e-11e8-8723-72b10874ec77.png)

In English
![image](https://user-images.githubusercontent.com/498115/45307223-c5624c00-b51e-11e8-9807-8bf58e0c1ceb.png)

**Comment by trasher** [comment]
Please try with latest nighlty build, I'm pretty sure this one has been fixed.

**Comment by cedric-anne** [comment]
Fixed by https://github.com/glpi-project/glpi/issues/4283 I guess.
