### ISSUE TITLE
email configuration error

### ISSUE THREAD

**Issue by revan9112** [glpi-project/glpi#4608]
Hi community, i ben unable to configure a mail acount on glpi to send notifications to my clients, after triple check the mail server addres, dns server and my glpi user account credentials i look into the log file "/var/www/glpi/files/_log/mail-debug.log" 

This is what i found

2018-09-10 11:46:40 [36@ubt18]
1 - CLIENT -> SERVER: STARTTLS
2018-09-10 11:46:40 [36@ubt18]
2 - SERVER -> CLIENT: 220 Begin TLS negotiation
2018-09-10 11:46:40 [36@ubt18]
1 - CLIENT -> SERVER: EHLO 192.168.2.28
2018-09-10 11:46:40 [36@ubt18]
2 - SERVER -> CLIENT: 2018-09-10 11:46:40 [36@ubt18]
1 - SMTP ERROR: EHLO command failed: 2018-09-10 11:46:40 [36@ubt18]
1 - SMTP NOTICE: EOF caught while checking if connected2018-09-10 11:46:40 [36@ubt18]
3 - Connection: closed2018-09-10 11:46:40 [36@ubt18]
3 - SMTP Error: Could not authenticate.2018-09-10 11:46:40 [36@ubt18]
3 - SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting2018-09-10 11:51
3 - Connection: opening to 192.168.2.2:25, timeout=300, options=array (
  'ssl' =>
  array (
    'verify_peer' => false,
    'verify_peer_name' => false,
    'allow_self_signed' => true,
  ),
)2018-09-10 11:51:03 [36@ubt18]
3 - Connection: opened2018-09-10 11:51:03 [36@ubt18]
2 - SERVER -> CLIENT: 220 dvm.esines.cu ESMTP MDaemon 10.0.0; Mon, 10 Sep 2018 11:51:03 -0400
2018-09-10 11:51:03 [36@ubt18]
1 - CLIENT -> SERVER: EHLO 192.168.2.28
2018-09-10 11:51:03 [36@ubt18]
2 - SERVER -> CLIENT: 250-dvm.esines.cu Hello 192.168.2.28, pleased to meet you
250-ETRN
250-AUTH=LOGIN
250-AUTH LOGIN CRAM-MD5
250-8BITMIME
250-STARTTLS
250 SIZE 0
2018-09-10 11:51:03 [36@ubt18]
1 - CLIENT -> SERVER: STARTTLS
2018-09-10 11:51:03 [36@ubt18]
2 - SERVER -> CLIENT: 220 Begin TLS negotiation
2018-09-10 11:51:03 [36@ubt18]
1 - CLIENT -> SERVER: EHLO 192.168.2.28
2018-09-10 11:51:03 [36@ubt18]
2 - SERVER -> CLIENT: 2018-09-10 11:51:03 [36@ubt18]
1 - SMTP ERROR: EHLO command failed: 2018-09-10 11:51:03 [36@ubt18]
1 - SMTP NOTICE: EOF caught while checking if connected2018-09-10 11:51:03 [36@ubt18]
3 - Connection: closed2018-09-10 11:51:03 [36@ubt18]
3 - SMTP Error: Could not authenticate.2018-09-10 11:51:03 [36@ubt18]

I dig a little bit on this fourm and find an issue where they recommend modifying the file "/var/www/glpi/inc/glpimailer.class.php" and add this 2 lines

 $this->Sender = str_replace('=','@',$CFG_GLPI['smtp_username']);
 $this->From = str_replace('=','@',$CFG_GLPI['smtp_username']);
 
this solution is not suitable for me.

Any suggestions will be appreciated

This is my system config

Información sobre la instalación y configuración del sistema
--
[code]   GLPI 9.3.0 ( => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux ubt18 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 PHP 7.2.5-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache () 	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:62.0) Gecko/20100101 Firefox/62.0 Server Software: (Ubuntu) 	Server Version: 5.7.22-0ubuntu18.04.1 	Server SQL Mode:  	Parameters: glpi@repositorio.dvm.esines.cu/glpidvm 	Host info: repositorio.dvm.esines.cu via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (5.7.22) - Perfect! /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) phpCas version 1.3.3 in (/usr/share/php)

Server: '192.168.2.20', Port: '389', BaseDN: 'dc=my,dc=company,dc=cu', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=hermes,OU=Soporte_Tecnico,DC=dvm,DC=esines,DC=cu', Use TLS: none

Not active

Way of sending emails: SMTP (glpi@192.168.2.2)

 

ocsinventoryng       Name: OCS Inventory NG               Version: 1.5.3      State: Enabled

Host: repositorio.dvm.esines.cuConnection: OkUse the OCSNG software dictionary: No
[/code]

```

**Comment by trasher** [comment]
There is an authentication issue; this does not looks like a bug at all. If you need support, please use forums
