### ISSUE TITLE
Assistance -> Tickets: attachment is not saved.

### ISSUE THREAD

**Issue by dbegit** [glpi-project/glpi#4609]
Hi, when I create a new ticket with an attachment "file.txt", upload is successful, I see file.txt 4 o (4o).
I click "save". The ticket is created without attachment.
The attachment disappears!

Thanks for your help.

* Steps to reproduce (which actions have you made) :
Simply create ticket with attachment.

* Expected result :
A ticket with attachment.

* Actual result :
A ticket without attachment.

* URL of the page :
http://localhost/front/ticket.form.php

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Operating system: Linux localhost 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64
PHP 5.6.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="10M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.31 ()
	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Server Software: MariaDB Server
	Server Version: 10.2.0-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
Database version seems correct (10.2.0) - Perfect!Database version seems correct (10.2.0) - Perfect!
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
OK/var/www/html/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

**Comment by trasher** [comment]
Please try with latest 9.3 nightly build.

**Comment by cedric-anne** [comment]
Hi,

I just tried with latest state of 9.3/bugfixes and it works for me.
You file should be visible in the `Document` tab of the ticket.

Regards
