### ISSUE TITLE
The problem GLPI version 0.90.1

### ISSUE THREAD

**Issue by Sball87** [glpi-project/glpi#462]
Hey.
The problem: when you create an application in the field: Description of the text in brackets <> without spaces disappear.
Help solve the problem
The system on which the GLPi centos 6.7

**Comment by yllen** [comment]
For which object of GLPI?

**Comment by orthagh** [comment]
Hello.

Without answer and precision, we can't fix this issue.
I close now, but you can reopen and add comments to this issue
