### ISSUE TITLE
[9.3.1]can't login if "Display source dropdown on login page" set to "NO"

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#4622]
upgrade from 9.3.0 to 9.3.1 (tarball) OK
=>login from LDAP OK (with dropdown visible) 

setup>general setup> "Display source dropdown on login page" set to "NO" 
=>Login(with ldap login) KO

try to login with localAdmin  
=>OK

switch back to   "Display source dropdown on login page" set to "YES"
login OK for all users ( local and LDAP)

some users have local login
some users have LDAP login

2 LDAPS in /glpi93/front/authldap.php  but only one is active

**Comment by orthagh** [comment]
Could you indicate precisily which message you have when the login fails ?

This one ?
```
msgid "You don't have right to connect"
msgstr "Vous n'avez aucun droit pour vous connecter à cette application"
```

**Comment by orthagh** [comment]
Another question, could you test also with "remember me" login option unchecked

**Comment by ladenree76000** [comment]
login with ldap account (dropdown visible)=> OK
setup>general>dropdown visible=false
log out
login  with ldap account, (dropdown hidden "remember me" uncheked) => message 
"Identifiant ou mot de passe incorrect"

login with admin (glpi base)=>OK
 setup>general>dropdown visible=true
log out
login with ldap account (dropdown visible)=> OK

**Comment by orthagh** [comment]
ok. So this is another issue.
Do you have multiple auth servers for ldap connections ?
Do you have any logs relative in glpi log folder ?
You mention the "remember me" checkbox, is the login ok when checked ?

**Comment by ladenree76000** [comment]
in my setting i have 2 LDAPS, but only one is active.
most of my users are authenticated with this LDAP (about 3000) and 50 users have glpi local authentication .

no error in log

no change with rememberme yes or no

**Comment by ladenree76000** [comment]
i deleted inactive LDAP setting (only 1 LDAP left)
now it works.

**Comment by orthagh** [comment]
ok this is a good hint.
i'm currently checking the process of ldap login

**Comment by orthagh** [comment]
ok, i think i got it.
Fix incoming.

**Comment by ruimiranda** [comment]
Hello,
Its possible to have multiple active login sources (different ADs) and set parameter "Display source dropdown on login page" to NO?

I am asking because i have this configuration and I can't login. Error message: is currently unable to handle this request. HTTP ERROR 500

GLPI version: 9.3.2

Thanks.

**Comment by orthagh** [comment]
yes, it's possible.

If you have an error 500, you should have logs.
Check your web server logs (httpd/apache/nginx) and glpi one (in glpi/files/_logs/ directory)

**Comment by ruimiranda** [comment]
The error message is "Unable to bind to server: Can't contact LDAP server"
If I disable this LDAP connection, everything is ok. Its a connectivity problem on development environment.
Thanks a lot.
