### ISSUE TITLE
[9.3.1] e-mail followup without break line

### ISSUE THREAD

**Issue by klodnitsky** [glpi-project/glpi#4623]
When sending an e-mail answer to GLPI, followup which goes to other users via e-mail is without break lines. All text is in one line.

**Comment by v-k-v** [comment]
I have same problem.

**Comment by mauriciolamego** [comment]
I have the same problem. When the answers to the call comes through emails is not being formatted automatically. Text is coming in unformatted.

**Comment by arengore** [comment]
some behavior with GLPI 9.3/bugfixes, 9.3.2 version from commit https://github.com/glpi-project/glpi/tree/f012fd8f6f4bf2235f2ef122d8f173587dca7e54 of 14 September.


A followup from email is formatted differently on helpdesk source, in fact even if it seems correct like this:

![1](https://user-images.githubusercontent.com/35173476/45590766-d3f69c00-b940-11e8-9a15-76e2feacc362.png)
 
going to edit I see instead

![2](https://user-images.githubusercontent.com/35173476/45590770-e4a71200-b940-11e8-9e4d-622457ce7aa5.png)


With the followup generated from helpdesk there isn't this discrepancy.

**Comment by ppenin** [comment]
is there any fix for this issue still remaining in 9.3.1
#4664 and #4739 duplicate #4623 issue but no solution for any of them.

**Comment by cedric-anne** [comment]
Hi @ppenin ,

Could you check the fix provided in https://github.com/glpi-project/glpi/pull/4803 ?

Regards

**Comment by trasher** [comment]
I'm not sure this has link with current issue. Please keep focus on break line issue. For other issue, please use separated tickets.

**Comment by ppenin** [comment]
your fix is not regressive in 9.3.1. Mailgate issue lasts since 9.2.1 (Issue #3494).

Regards

**Comment by cedric-anne** [comment]
OK

So it is clearly another issue, so I will not be part of proposed fix.

Regards

**Comment by trasher** [comment]
@klodnitsky @v-k-v @mauriciolamego @arengore @husisusi please test proposed fix.

**Comment by husisusi** [comment]
Mailgate tasks gets stuck.

**Comment by husisusi** [comment]
Another issue?! Without this fix is no mailgate issue.

**Comment by cedric-anne** [comment]
@husisusi 

Could you provide some log ? I did not had problems during my tests.

Regards

**Comment by arengore** [comment]
In rich text mode, with  mailgate and queuednotification in CLI mode, with GLPI version https://github.com/glpi-project/glpi/tree/4d6c3653ff087f22b3fa49465adc123d38bc432a and mailcollector.class.php from https://github.com/glpi-project/glpi/blob/13763d2243499fc7ee53e3998f48e04ee4c40ee7/inc/mailcollector.class.php, no tasks get stuck (also with embedded images on followup - email sent from Gmail).
No tried without rich text disabled.
