### ISSUE TITLE
[9.3.1] LDAP Synchronization on default user entity doesn't work

### ISSUE THREAD

**Issue by pxlcore** [glpi-project/glpi#4624]
I've defined "authorizations assignment rules" to assign users via their email address domain-name to a default entity. This works great for LDAP import and users first login on GLPI.

* Steps to reproduce (which actions have you made) :
Got to user administration.
The user already exists and has an email address (user@domain1.com).

The user got a new email address (user@domain2.com) in the LDAP.
I used the synchronize feature in GLPI user administration

* Expected result :
The default entity should be changed because of the changed domain name (different assignment rule).

* Actual result :
Entity does not change.
If you drop down the field 'default entity' you can see the correct entity (domain2.com) as a choosable option. But it's not set automatically.

* Screenshot of the problem (if pertinent) :
After synchronization you still see the old entity.
![glpi-entity1](https://user-images.githubusercontent.com/198268/45469953-05e2e500-b72c-11e8-8273-9fccef1dcdd9.png)

But if you drop down the field you already see the right entity
![glpi-entity2](https://user-images.githubusercontent.com/198268/45469994-2b6fee80-b72c-11e8-9410-53fa5ae109fe.png)

The field is not updated.

pxlcore

**Comment by orthagh** [comment]
I'm lost, where do you set the automatic entity rule definition ?
It's a feature i wanted to add to glpi someday, but as far as i know, it doesn't currently exists.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by trasher** [comment]
Please give requested feedback first; RFE should be opened on suggestions website, not here

**Comment by pxlcore** [comment]
OK, here is the requested feedback for @orthagh :

You can find the automatic entity rule definition in the menu:
Administration > Rules > Authorizations assignment rules

Inside a rule you can setup criteria ("email > finished by") and actions ("entity > assign").

**Comment by orthagh** [comment]
Ok, this is much clear, so currently, we can assign an entity for authorizations tab of users.
But not their default entity, this one is loaded by default on user login.

So it's a request for enhancement and please add an entry on suggest.glpi-project.org for tracking.
