### ISSUE TITLE
Error on deleting Peripheral models

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#4627]
GLPI 9.2.4
When deleting a peripheral model, at least via the massive action 'Delete permanently', I get 2 SQL errors (see below).
Indeed, in WHERE clause, there is a blank before word 'peripheralmodels_id'.
As a consequence, GLPI interprets it as if there were no peripheral linked to this peripheral model, and let it delete it.
Data consistency is no longer valid.

2018-09-12 15:43:54 [2@ULYSSE]
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
                            FROM `glpi_peripherals`
                            WHERE ` peripheralmodels_id` = '334'
  Error: Champ ' peripheralmodels_id' inconnu dans where clause
  Backtrace :
  inc\commondropdown.class.php:541                   
  inc\massiveaction.class.php:1068                   CommonDropdown->isUsed()
  inc\massiveaction.class.php:993                    MassiveAction::processMassiveActionsForOneItemtype()
  inc\massiveaction.class.php:972                    MassiveAction->processForSeveralItemtypes()
  front\massiveaction.php:63                         MassiveAction->process()
2018-09-12 15:43:54 [2@ULYSSE]
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_peripherals` WHERE ` peripheralmodels_id` = 334
  Error: Champ ' peripheralmodels_id' inconnu dans where clause
  Backtrace :
  inc\dbmysqliterator.class.php:274                  
  inc\dbmysql.class.php:543                          DBmysqlIterator->__construct()
  inc\commondbtm.class.php:642                       DBmysql->request()
  inc\commondbtm.class.php:567                       CommonDBTM->cleanRelationData()
  inc\commondbtm.class.php:1452                      CommonDBTM->deleteFromDB()
  inc\massiveaction.class.php:1078                   CommonDBTM->delete()
  inc\massiveaction.class.php:993                    MassiveAction::processMassiveActionsForOneItemtype()
  inc\massiveaction.class.php:972                    MassiveAction->processForSeveralItemtypes()
  front\massiveaction.php:63                         MassiveAction->process()

**Comment by cedric-anne** [comment]
Hi,

Could you test fix provided in https://github.com/glpi-project/glpi/pull/4628 ?

Regards
