### ISSUE TITLE
Custom methods

### ISSUE THREAD

**Issue by virusav** [glpi-project/glpi#463]
Good day.
Is there a possibility of implementing own code WITHOUT editing the source, for example, to getSubjectPrefix method in class NotificationTargetTicket return the other text?

Example: in the config folder create a file custom.php and write your code there to override existing methods.

Is there anything similar in your system?

**Comment by orthagh** [comment]
Hello @virusav.

I think there is no way to do code modification without altering the source.
PHP doesn't support monkey patching. 

Anyway, for NotificationTargetTicket::getSubjectPrefix method, it return the [prefix #number] part of a notification subject.
by default prefix is GLPI, but in Administration > Entities, select one, Notification Tab , you could define a custom prefix.

I close this issue, reopen/comment if you need more details

**Comment by tomolimo** [comment]
hum hum hum :smiley:

**Comment by orthagh** [comment]
ok, here is no **good** way
