### ISSUE TITLE
Special characters ^ and $ don't work in negative compound searches...

### ISSUE THREAD

**Issue by tabad** [glpi-project/glpi#4639]
> This bug concerns GLPI releases 9.3.x & 9.2.x.
> All tests that appear here have been done making use of GLPI v9.3.1 from [GLPI Demo Site](https://demo.glpi-project.org).

This is an example of an affirmative compound search (those which relate different assets like computers and software) where the use of special characters `^` and `$` works without any problem.

![glpi931-query-1](https://user-images.githubusercontent.com/2183103/45535600-52e3bb80-b7ff-11e8-8e93-7f3cf59aa883.png)

The compound query shows those computers with `Acrobat Reader` installed (*`AND Software Name Contains ^Acrobat Reader$`*).

The problem comes when you want to know what computers do not have `Acrobat Reader` installed (*`AND NOT Software Name Contains ^Acrobat Reader$`*). This happens when you try that.

![glpi931-query-2](https://user-images.githubusercontent.com/2183103/45535942-4dd33c00-b800-11e8-86a4-d447d8fbc920.png)

Really, the previous search is equivalent to select all computers as you can easily see.

![glpi931-query-3](https://user-images.githubusercontent.com/2183103/45536063-97238b80-b800-11e8-9cf9-f710ac391572.png)

> To obtain the correct set of computers you should not make use of special characters `^` and `$` (*`AND NOT Software Name Contains Acrobat Reader`*)

This bug don't let you construct faster queries (the query *`AND Software Name Contains ^Acrobat Reader$`* is faster than *`AND Software Name Contains Acrobat Reader`*) but it also has important and dangerous collateral effects, for example when you build computers groups of [FusionInventory](https://plugins.glpi-project.org/#/plugin/fusioninventory) to deploy software.

Regards,

**Comment by tabad** [comment]
Hello,

Is there or have you any news about this issue?

Thanks in advance,

**Comment by trasher** [comment]
I've just tested on 9.4 series, this seems to have been fixed.
