### ISSUE TITLE
0.91: Tab titles are truncated on tabs when a quantity is shown

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#464]
With IE10 (same for Chrome48, and FF44), GLPI0.91
For example in a ticket, showing the tabs:
![image](https://cloud.githubusercontent.com/assets/7569958/13106443/844bd08a-d568-11e5-81af-d7bec195d544.png)

or

![image](https://cloud.githubusercontent.com/assets/7569958/13106448/8d5e12d2-d568-11e5-98cd-cbd50c0274a6.png)

**Comment by yllen** [comment]
tab name is complete, but number of item is added on the name, not after

**Comment by tomolimo** [comment]
Then this is a visual bug!

**Comment by orthagh** [comment]
There is a rewriting of the css to set this sup number in position:relative and prevent truncated text.
Tested on last versions of  ff/chrome and internet explorer
