### ISSUE TITLE
GLPI 9.3.1 - Failed to load plugin url: /lib/tiny_mce/lib/langs/ru_RU.js

### ISSUE THREAD

**Issue by v-k-v** [glpi-project/glpi#4640]
Hello.

After update GLPI from 9.2.4 on 9.3.1 i have error in the tickets: "Failed to load plugin url: /lib/tiny_mce/lib/langs/ru_RU.js"

In folder "/lib/tiny_mce/lib/langs/" there is only "ru.js " file.

![default](https://user-images.githubusercontent.com/42035958/45539312-fe960700-b811-11e8-876a-35962afc5900.png)

**Comment by trasher** [comment]
Try to logout and logn again.

**Comment by v-k-v** [comment]
Relogin did not fix the problem.

**Comment by cedric-anne** [comment]
Hi,

#4641 should fix your problem.

Regards
