### ISSUE TITLE
Bookmark loading button not displayed.

### ISSUE THREAD

**Issue by thibvdb** [glpi-project/glpi#465]
When a user goes to "Assistance" => "Tickets", he can save the bookmark of his filter but he cannot load the bookmark because there is no button. I tried as Super-admin profile.
![glpi_bug](https://cloud.githubusercontent.com/assets/14821264/13109001/06b8e536-d577-11e5-9bf0-b1e9645427ac.PNG)

**Comment by tomolimo** [comment]
To load bookmarks use the start near your login name:
![image](https://cloud.githubusercontent.com/assets/7569958/13109498/e6ec708a-d579-11e5-96f9-6dd3835f3a07.png)

**Comment by thibvdb** [comment]
OK!
The button location is strange!
Thank you.

**Comment by tomolimo** [comment]
Not really, as it serves for all object type and from anywhere
