### ISSUE TITLE
Flipped view images of device in Rack 

### ISSUE THREAD

**Issue by alessiotomelleri** [glpi-project/glpi#4658]
Hi,

In Items tab of Rack menu, images front and rear of model device are shown flipped : 

![rack-flippedview-device](https://user-images.githubusercontent.com/4599520/45671838-d9add680-bb26-11e8-8ed9-fa500d325ab9.png)

 but in model of the related network device, that images are correctly saved, see picture below :

![model-switch](https://user-images.githubusercontent.com/4599520/45671851-e29ea800-bb26-11e8-85d7-06bb6496041c.png)

thx in advance,
Alessio

**Comment by cedric-anne** [comment]
Hi,

If you open the "relation" edit form (clicking on the pen displayed when moving the mouse over the item), what is he value of `Orientation (front rack point of view)` field ?

If it is `Rear`, then it is normal to have pictures inverted.

Regards

**Comment by alessiotomelleri** [comment]
> Hi,
> 
> If you open the "relation" edit form (clicking on the pen displayed when moving the mouse over the item), what is he value of `Orientation (front rack point of view)` field ?
> 
> If it is `Rear`, then it is normal to have pictures inverted.
> 
> Regards

Hi, thx for quick answer... it shows rear as correct, but in wrong rack, as it is front...

![relatio-edit-form](https://user-images.githubusercontent.com/4599520/45685413-8ef18600-bb49-11e8-9790-995efbc80533.png)

**Comment by cedric-anne** [comment]
Not sure to understand your answer.

If "orientation" field is set to "Front", then it means that the equipement front side is visible from the front side of the rack.
If "orientation" field is set to "Rear", then it means that the equipement rear side is visible from the front side of the rack.

Your screenshot does not show the properties of the relation between equipement and rack but shows the equipement properties.

**Comment by alessiotomelleri** [comment]
omg  I've been lost in a glass of water... sorry and excuse me for waste your time.

Before I looked only the label rear of the object stand in that rack and misunderstanding... 
I see just now edit properties let you change it orientations.

thx
