### ISSUE TITLE
New ticket creation -> Hardware type -> Add button

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#4660]
* Steps to reproduce (which actions have you made) :
  - Connect to demo.glpi-project.org using post-only account
  - Create a new ticket
  - Try to use the Add button in front of Hardware Type

* Expected result :
  - Ability to add an hardware type

* Actual result :
  - Nothing occurs

* URL of the page :
https://demo.glpi-project.org/front/helpdesk.public.php?create_ticket=1
![capture](https://user-images.githubusercontent.com/6187125/45686110-1388d800-bb3b-11e8-9b16-5f4da300c352.PNG)

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
demo.glpi-project.org
```

Regards

**Comment by cedric-anne** [comment]
Hi,

1. Label is wrong, fiels corresponds to "Associated elements".
2. General is not a value. It comes from the normal ticket form where dropdown is splitted in 2, one for the hardware type, and one for the devices.
3. Add button is made to add what you selected, not to add something to selectable list.

I should have fixed 1 and 2 in #4662.

There is still a lack of callback message, like "You must select an item to be able to add it.". Problem is same as in ticket form of a normal user.

Regards

**Comment by AnaelMobilia** [comment]
@cedric-anne did you know if the third point is now solved ?
Bests regards

**Comment by cedric-anne** [comment]
I do not know.

**Comment by AnaelMobilia** [comment]
.

**Comment by cconard96** [comment]
Closed via #10322
