### ISSUE TITLE
New ticket creation -> redirection to the ticket ?

### ISSUE THREAD

**Issue by AnaelMobilia** [glpi-project/glpi#4661]
Hello,
------------
* Steps to reproduce (which actions have you made) :
  - Using demo.glpi-project.org, use the post-only account
  - Create a new ticket
  - Validate the creation

* Expected result :
  - Display of the ticket

* Actual result :
  - Green flag on the middle of the page, no redirection

* URL of the page :
https://demo.glpi-project.org/front/tracking.injector.php

* Screenshot of the problem (if pertinent) :
![capture](https://user-images.githubusercontent.com/6187125/45686235-6793bc80-bb3b-11e8-9a0e-bacebe2bfa48.PNG)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
demo.glpi-project.org
```

Regards

**Comment by trasher** [comment]
This is already possible enabling "Go to created item after creation" from the account config (but not enabled by default).
