### ISSUE TITLE
Bad CSS in vsplit layout

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#4668]
With split vertical view, 
when the FusionInventory plugin is installed, information is added to the footer, so that the save button (on ticket form) is not displayed entirely

* Steps to reproduce (which actions have you made) :

Install FusionInventory plugin
Create ticket with a large description

* Expected result :

The save button is dispay correctly

* Actual result :

The save button is behind

* URL of the page :

* Screenshot of the problem (if pertinent) :

![image](https://user-images.githubusercontent.com/7335054/45751290-3c2fd100-bc12-11e8-8cd6-e50d0007ecba.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.1
Fusion Inventory Version 9.3+1.1
```
paste here
```

**Comment by AnaelMobilia** [comment]
@trasher This issue could be close please :-)
Regards
