### ISSUE TITLE
Working days

### ISSUE THREAD

**Issue by lexx015** [glpi-project/glpi#467]
Hello!
We have been issued with some holidays which can be transferred to another (working) days.

Let me explain with an example.
In Russia we have a holiday on 23 Feb. So we have 3 days holiday: Sunday(21), Monday(22) and Tuesday(23). But in this case we should work on Saturday for Monday. And there is no way to transfer days or make weekend days working.

So please add a feature like a "close days" but with reverse functionality.

**Comment by tomolimo** [comment]
Please post new feature requests on there: http://glpi.userecho.com/

**Comment by lexx015** [comment]
Ah, thanks for link. I will do it.
