### ISSUE TITLE
Reservation Item with no User to show

### ISSUE THREAD

**Issue by salazar8D** [glpi-project/glpi#4671]
Hello,

I really do not think it's a bug, but it's something to take a look at
Here's what I did to "improve" the form of the reservation item:

Original code:

Line 670 - inc\reservation.class.php:

```
if (!Session::haveRight("reservation", UPDATE)
          || is_null($item)
          || !Session::haveAccessToEntity($item->fields["entities_id"])) {

         echo "<input type='hidden' name='users_id' value='".Session::getLoginUserID()."'>";

      } else {
```

Changed to:

```
if (!Session::haveRight("reservation", UPDATE)
          || is_null($item)
          || !Session::haveAccessToEntity($item->fields["entities_id"])) {
	 //SALAZAR8D
         //echo "<input type='hidden' name='users_id' value='".Session::getLoginUserID()."'>";
         echo "<tr class='tab_bg_2'><td>".__('By')."</td>";
         echo "<td>";
	     User::dropdown(['value'  => $resa->fields["users_id"],
	         'entity' => $item->getEntityID(),
	         'entity_sons' => $item->isRecursive(),
	         'right'  => 'none']);
         echo "</td></tr>\n";
	 //SALAZAR8D
      } else {
```
That way, other users can see info about the user who has made the reservation:

Before:

![image](https://user-images.githubusercontent.com/30785943/45756609-ab4bfc00-bbf7-11e8-9f12-1c820b5a5159.png)

After:

![image](https://user-images.githubusercontent.com/30785943/45756690-e3533f00-bbf7-11e8-9075-45187b5b024c.png)

GLPI 9.3.1 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

**Comment by trasher** [comment]
Is seems incorrect to display a dropdown in that case. Please check #4727 with my change proposal.

**Comment by salazar8D** [comment]
Awesome @trasher !!! Thanks for your time man. I appreciate it.
