### ISSUE TITLE
Problem with Java IE_support used for copy/paste images (imagepaste JQuery plugin)

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#468]
GLPI 0.90 and 0.91

Hello,

There are some troubles which occur after upgrading to Java 7 or 8
Seems to be a problem with IE only (to be checked)

I now receive this kind of error messages when running GLPI in IE10 and trying to open a ticket:
![image](https://cloud.githubusercontent.com/assets/7569958/13143278/2124186a-d643-11e5-9966-6e4a3650b8fe.png)

If I click on OK then ticket is shown, and if I try to paste an image, then I get (when debugging):
![image](https://cloud.githubusercontent.com/assets/7569958/13143323/6d6720fa-d643-11e5-80d1-9604182ad937.png)

- Since Java release 7, security has been reinforced, see:  https://www.java.com/en/download/help/jcp_security.xml

So I set the right authorization in Java security panel (like described above), and now I get this (after a restart of IE):

![image](https://cloud.githubusercontent.com/assets/7569958/13143553/f47495d6-d644-11e5-89f9-bad47513d20b.png)

There is a problem with auto-signed certificate and with this one in particular as it is no longer valid:
Validity: [From: Mon Dec 10 14:23:20 CET 2012, To: Sun Mar 10 14:23:20 CET 2013]

Could it be possible to get a valid certificate (and not auto-signed), see https://letsencrypt.org/

Thank you,
Regards,
Tomolimo

**Comment by orthagh** [comment]
Yeah.
This applet is a crap and a pain to fully integrate (without warning/errors appears) !
My opinion is to drop that, since IE now supports base64 img paste (with IE11/edge).
Old IE versions will lose the img clipboard paste but i'm fini with it.

**Comment by orthagh** [comment]
See this issue : https://github.com/glpi-project/glpi/issues/155

**Comment by tomolimo** [comment]
Yes I agree to drop support for IE10 for the copy/paste as long as the drag/drop is still supported!

**Comment by orthagh** [comment]
yes, it's not in the actual code, but ie10 supports clipboard pasting without applet.

http://snag.gy/ service use the same method and applet don't trigger on IE10 (as far i remember).
If you could test and confirm this

**Comment by tomolimo** [comment]
exact the applet doesn't trigger on IE10 (just got an alert from Java that an applet is blocked), and image is not pasted...

**Comment by orthagh** [comment]
This will be fixed by #723 as i managed to support image paste directly by dom for IE10 and above.
Previous versions still used the java applet.
I plan to drop it next version
