### ISSUE TITLE
9.3.1: User - Used items and managed items gives SQL error for group items

### ISSUE THREAD

**Issue by lufik** [glpi-project/glpi#4682]
* Root cause of the problem in php code:
File: inc/user.class.php
Function: showItems
The user part calls the DB->request:
            $item_iterator = $DB->request($iterator_params);
while the group part calls the DB->request:
               $group_iterator = $DB->request([$iterator_params]);

The bug is also in git master.

It's enough to remove [] from the group DB->request call and everything works perfect.
Should I create pull request or is this enough to fix it?

* Steps to reproduce (which actions have you made) :
Have user with assigned asset(s). This user belongs to group(s) with assigned asset(s).
Go to: Administration -> Users -> choose the user -> go to the tab Used items.

* Expected result :
List of assigned assets to user and also his groups.

* Actual result :
List of assigned assets to user and several errors for assets assigned to group(s):
PHP Warning: preg_split() expects parameter 2 to be string, array given in /var/www/glpi/inc/dbmysql.class.php at line 841
PHP Warning: strpos() expects parameter 1 to be string, array given in /var/www/glpi/inc/dbmysql.class.php at line 852
PHP Notice: Undefined offset: 0 in /var/www/glpi/inc/dbmysql.class.php at line 858
PHP Notice: Array to string conversion in /var/www/glpi/inc/dbmysql.class.php at line 858

There is also several times error log in sql-errors.log:
[2018-09-21 09:45:22] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT * FROM `Array`
  Error: Table 'db_glpi.Array' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/user.class.php:4031                            DBmysql->request()
  inc/user.class.php:234                             User->showItems()
  inc/commonglpi.class.php:488                       User::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

* URL of the page :
https://glpi.devel.invasys.org/front/user.form.php?id=10

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
[code]   GLPI 9.3.1 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux localhost.localdomain 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 PHP 7.1.22 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: Apache/2.4.6 (CentOS) () 	Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 Server Software: MariaDB Server 	Server Version: 10.3.9-MariaDB 	Server SQL Mode:  	Parameters: dbuser@dbserver/dbglpi 	Host info: 192.168.1.1 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (10.3.9) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to files directory is protected : OK SELinux mode is Enforcing SELinux boolean configuration for httpd_can_network_connect --> on SELinux boolean configuration for httpd_can_network_connect_db --> on SELinux boolean configuration for httpd_can_sendmail --> on

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) SimplePie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

Not active

Way of sending emails: PHP

 

news                 Name: Alerts                         Version: 1.4.1      State: Enabled 	behaviors            Name: Behaviours                     Version: 2.1.1      State: Enabled 	fpconsumables        Name: FP Consumables                 Version: 1.2.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.3+1.1    State: Enabled 	handover             Name: Handover protocol              Version: 1.0.2      State: Enabled 	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.5.0      State: Enabled 	genericobject        Name: Objects management             Version: 2.6.2      State: Enabled 	timezones            Name: Timezones                      Version: 2.2.0      State: To be cleaned
[/code]
```

**Comment by trasher** [comment]
Please open a pull request if you can ;) Thank you

**Comment by lufik** [comment]
Pull request submitted against master. Should I create also one for 9.3/bugfix branch?

**Comment by lufik** [comment]
I'm sorry I'm not so keen in using github (changing pull requests). I closed the previous one and created the new one from scratch.

**Comment by trasher** [comment]
No problem
