### ISSUE TITLE
Missing tabs for empty ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4686]
In display preferences for PDF plugin, some tabs are missing for a ticket (statistics, solution and timeline)
These tabs are presents for a change or a problem (solution and statistics)

When you are in display preferences, item is always a new item, so you should not return on this condition.

But still present in 9.2.x

**Comment by orthagh** [comment]
cf: https://forge.glpi-project.org/issues/5558#change-14090

**Comment by AnaelMobilia** [comment]
@trasher This issue could be close too imho.

Regards,
Anael
