### ISSUE TITLE
check all groups when import from ldap

### ISSUE THREAD

**Issue by klodnitsky** [glpi-project/glpi#469]
is it possible to create "check all" check box when i import groups from ldap?

![untitled](https://cloud.githubusercontent.com/assets/7794575/13145172/9bdf7ad6-d657-11e5-8142-25b8ade2048a.png)

**Comment by yllen** [comment]
I don't understand., you have check all near Group in the title of the array (in green)

**Comment by klodnitsky** [comment]
I can check all groups from list with one mouse click, but it is impossible to check "child entities" with one mouse click for all that groups.

**Comment by orthagh** [comment]
Done, thank you for this point
