### ISSUE TITLE
Ticket  timeline : preformatted text may overflow a bubble's background

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#4692]
Rich text enabled, if I add a followup to a ticket with preformatted text "<pre> / <pre>" long lines in this text overflow the followup area.

![image](https://user-images.githubusercontent.com/14139801/45881917-ddeb2580-bdac-11e8-83b5-7e1ec26fba72.png)

------------
* Steps to reproduce (which actions have you made) :ad a followup to a ticket with a looong line in preformatted block

* Expected result :

an horizontal scrollbar ? Truncating the line is not a good idea here.

* Actual result :

text overflows out of the background

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.1
```
paste here
```

**Comment by Badoche1337** [comment]
Hello,

I've reproduced this issue in 9.3.1 but it's fixed in 9.3.2 and above, I close :)

Alan
