### ISSUE TITLE
I could delete used notification templates without a warning

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#4694]
* Steps to reproduce (which actions have you made) :
Take a notification template (eg Problems) used by one or more notifications (by default, template Problems is used by 6-7 notifications) and delete it (button "Delete permanently")

* Expected result :
I'm expecting that it can't be deleted, because used (at least a warning)

* Actual result : the notification template is deleted. Data get inconsistent.
Furthermore, database analysis shows that one record is deleted from table glpi_notificationtemplates, but depending records in tables glpi_notificationtemplatetranslations and glpi_notifications_notificationtemplates are not deleted.

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) : GLPI 9.2.4, GLPI 9.3
```
paste here
```

**Comment by trasher** [comment]
Fixed as of https://github.com/glpi-project/glpi/pull/4965 I guess
