### ISSUE TITLE
Item type criteria for business rule for tickets is not working

### ISSUE THREAD

**Issue by blumfontein** [glpi-project/glpi#4695]
Hi, can not figure out, how Item type criteria for "Business rules for tickets" works. Tried to associate an object of some type to ticket, but rule actions are not applied to ticket. This happens both in 9.2.x and 9.3.x versions.

------------
* Steps to reproduce (which actions have you made) :
1. Create any software asset
2. Create Service level with "Time to resolve" type (or "Time to own")
3. Create business rule for ticket with criteria "Item type is Software" and action "SLA time to resolve"
4. Create Ticket with associated software item

* Expected result :
SLA is applied to ticket

* Actual result :
SLA is not applied to ticket

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
GLPI 9.2.3 ( => /var/www/glpi)
Installation mode: TARBALL

Operating system: Linux core 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64 PHP 7.1.20-1+0~20180910100430.3+jessie~1.gbp17c613 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, json, ldap, 	libxml, mbstring, memcached, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, readline, session, 	shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: nginx/1.14.0 	Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.23 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket
```

**Comment by trasher** [comment]
Hi, you'd better ask on the forums to get help on usage; and then open a ticket here if this is really a bug.

By the way, GLPI 9.2.x is not supported; consider upgrading to latest stable version.
