### ISSUE TITLE
Followup on technician assigned

### ISSUE THREAD

**Issue by anahimself** [glpi-project/glpi#4701]
------------
* Steps to reproduce (which actions have you made) :
Assign a technician

* Expected result :
Wish to have a comment in the followup to state "Technician X has been assigned".
That would also be useful to let the requester know which technician is assigned, and the technician notified of the assignment.

* Actual result :
Nothing in followup

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI v9.1.3

```
If possible, I would be glad to add a line in source code to add the followup everytime a technician is assigned.. I just need to know when to add the line :)

**Comment by trasher** [comment]
9.1 is no longer mainained; please try to reproduce with latest stable version first.

**Comment by anahimself** [comment]
Same behavior in 9.3 (our test environment), I don't think a comment tracking these changes has ever been implemented.

It would be more than useful to us to add this comment in the processing log after every assignment

**Comment by cedric-anne** [comment]
Hi,

I close this ticket as this is an enhancement. You are welcome to open a thread on https://glpi.userecho.com/ to discuss about this feature.

Regards

**Comment by anahimself** [comment]
Possible to give me a clue about where the modification should be done pls ?

On Tuesday, September 25, 2018, Cédric Anne <notifications@github.com>
wrote:
> Hi,
>
> I close this ticket as this is an enhancement. You are welcome to open a
thread on https://glpi.userecho.com/ to discuss about this feature.
>
> Regards
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/_44H1UwSKXeVIXbGGm2B-jhmQweppJi5SEowqMUJ4rv4SlMpR0sMOH3E11ishqeO_qXbrnm648QRaxSGBCvNwOCARyVrh8VMqRIeCKkLnDWFGIvR59culVbPpyANdqD5jpQjuO0zAdPie-4LxCUHiq2RkStfeg=s0-d-e1-ft#https://github.com/notifications/beacon/ARlubmng0V07Er5IUttqLQpXHFYA9tErks5uejjlgaJpZM4W37wI.gif>

**Comment by Armin83** [comment]
you can do a notification with a plugin i believe it is behavivor but you don't have a comment in followup

**Comment by anahimself** [comment]
Unfortunately I don't have this in behavior

I will try to add the comment on technician assignment if i find where to
patch the code

Should be easy if I found where to look, and will propose the feature if
that works

On Tuesday, September 25, 2018, Armin83 <notifications@github.com> wrote:
> you can do a notification with a plugin i believe it is behavivor but you
don't have a comment in followup
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci3.googleusercontent.com/proxy/ox-GIzPPcD6V2jbOv9b7HJxu0cqwh4l7gSw_eIYE1oRtpUC_gjRLvOiXAJyMqNnUh7xKUAPfXOPv7azMhCs-koOs4gRA6JfHF001tQqfQQkSU_NKE-GFoVBfHZKVRAggbsFi3RyiVwh86JxdBrrIdECKXBbMMQ=s0-d-e1-ft#https://github.com/notifications/beacon/ARlubum5xWVFJ-tK0ycyRdqXfxJTlZEuks5uen7wgaJpZM4W37wI.gif>

**Comment by anahimself** [comment]
I was looking on ticket.form.php

More specifically, there is a debug line saying (2 times in the file):
_sprintf(__('%s adds an actor'), $_SESSION["glpiname"]));_

I will try to find a way to add a followup in the ticket after these lines, like "New actor is assigned", but I don't know how to add a followup in the code yet :)
