### ISSUE TITLE
Latencies on GLPI

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#471]
in my prod 0.85.2 I have sometimes latencies on GLPI, and it is the same thing with 0.91. Have you any idea ? 

latencies at logon - in all module, never at the same time, nothing in logs, nothing on mysql, I have tried many things to improve but without success

0.85.2 - xamp - apache 2.4.13 - php 5.5
0.91 - apache 2.4.17 - php 7.02

**Comment by orthagh** [comment]
Can you give a an example time of your latencies ?

On xamp configuration, in past, i had a very good results by changing php to fastcgi.
Is your 0.91 configuration is loaded by a php provided by apache module ?

**Comment by satyan01** [comment]
Apache/2.4.17 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2d PHP/7.0.2
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7e72f9690b1498a1bead7a637c33a831c0d2f655 $
PHP extension: mysqli Documentation
PHP version: 7.0.2
Server version: 10.0.20-MariaDB - mariadb.org binary distribution

**Comment by ddurieux** [comment]
Perhaps automayic tasks in mofe GLPI...
Try active module apcu of php/pecl too ;)

**Comment by satyan01** [comment]
[httpd.zip](https://github.com/glpi-project/glpi/files/136371/httpd.zip)

my httpd.conf

**Comment by orthagh** [comment]
So apache module for your php.
I strongly suggest to test switching to fastcgi on a qualification server to benchmark.

As @ddurieux note, it can be also the automatic actions of glpi who launch on your actions.
You can pass theses in CLI mode and launch them by an external program (windows scheduled tasks) with an execution of front/cron.php file

**Comment by tomolimo** [comment]
Yes I agree with that, and you can also narrow the SSO authentication to two files instead of the whole GLPI folder: 

> &lt;Files ~ "^$|index.php|login.php">
    AuthName "Accès restreint"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    NTLMOfferBasic Off
    NTLMPerRequestAuth On
    require valid-user
&lt;/Files>

another question is: do you have xdebug actived?

**Comment by tomolimo** [comment]
Another help can be to look into your php.ini, if you don't mind :)

**Comment by satyan01** [comment]
[php.zip](https://github.com/glpi-project/glpi/files/136413/php.zip)

**Comment by tomolimo** [comment]
You may greatly benefit from opcache module which cache into memory compiled and optimized PHP code.

**Comment by satyan01** [comment]
of course but I don't know how to do it.

**Comment by satyan01** [comment]
the behavior is strange, for the first logon it takes 2/3 minutes to logon
it was the same before

**Comment by tomolimo** [comment]
before what?

**Comment by tomolimo** [comment]
opcache: https://secure.php.net/manual/fr/book.opcache.php

**Comment by satyan01** [comment]
before the change that you have given me
$
<Files ~ "^$|index.php|login.php">
AuthName "Accès restreint"
AuthType SSPI
NTLMAuth On
NTLMAuthoritative On
NTLMOfferBasic Off
NTLMPerRequestAuth On
require valid-user
</Files>

**Comment by tomolimo** [comment]
did you also de-activated SSO for the rest?

**Comment by satyan01** [comment]
opcache works with php 7 ?

**Comment by satyan01** [comment]
yes I have deleted all the lines

**Comment by tomolimo** [comment]
yes of course

**Comment by tomolimo** [comment]
did you switch to fastcgi?

**Comment by satyan01** [comment]
how can I do that ?

**Comment by tomolimo** [comment]
see: http://php.net/manual/fr/install.windows.apache2.php

**Comment by satyan01** [comment]
I don't see the lines in httpd.conf

Do I have to add it ?

LoadModule fcgid_module modules/mod_fcgid.so  

# Où se trouve le fichier php.ini ?
FcgidInitialEnv PHPRC        "c:/php" 

AddHandler fcgid-script .php  
FcgidWrapper "c:/php/php-cgi.exe" .php

**Comment by remicollet** [comment]
>   Try active module apcu of php/pecl too ;)

Rather apcu_bc (for PHP 7)

**Comment by satyan01** [comment]
How can I check if fast cgi is activated ? and working ?

**Comment by satyan01** [comment]
and opcache, How can I chek if it is activated and work

**Comment by tomolimo** [comment]
Google is your friend 
☺

**Comment by satyan01** [comment]
Hello

I have this message in error log, I could not log in this morning, I had to restart the server and I have seen this message in apache logs

[Mon Feb 22 08:37:56.355256 2016] [ssl:warn] [pid 1136:tid 312] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]

**Comment by satyan01** [comment]
Without any changes sometime I can't reach the server on 0.91 but in 0.85 yes

192.168.102.26 - UNG\\YLA [22/Feb/2016:16:47:35 +0100] "GET /glpi/front/login.php HTTP/1.1" 500 -
192.168.102.26 - - [22/Feb/2016:16:48:23 +0100] "GET /glpi/front/login.php HTTP/1.1" 401 381
192.168.102.26 - UNG\\YLA [22/Feb/2016:16:48:23 +0100] "GET /glpi/front/login.php HTTP/1.1" 500 -
192.168.102.26 - - [22/Feb/2016:16:49:09 +0100] "GET /glpi/front/login.php HTTP/1.1" 401 381
192.168.102.26 - UNG\\YLA [22/Feb/2016:16:49:09 +0100] "GET /glpi/front/login.php HTTP/1.1" 500 -

**Comment by satyan01** [comment]
Hello

Errors in apache

[Tue Feb 23 12:07:08.161510 2016] [:error] [pid 3008:tid 936] [client 192.168.102.26:57436] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on boolean in E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\dbmysql.class.php:280\nStack trace:\n#0 E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\rulerightcollection.class.php(196): DBmysql->fetch_assoc(false)\n#1 E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\rulerightcollection.class.php(222): RuleRightCollection->getFieldsToLookFor()\n#2 E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\rulecollection.class.php(1615): RuleRightCollection->prepareInputDataForProcess(Array, Array)\n#3 E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\rulecollection.class.php(1448): RuleCollection->prepareInputDataForProcessWithPlugins(Array, Array)\n#4 E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\user.class.php(1492): RuleCollection->processAllRules(Array, Array, Array)\n#5 E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\auth.class.php(625): User->getFromLDAP(Resource id #97, Array, 'CN=Yannick Labb...', 'YLA', false)\n#6 E:\\webserver\\Apache24\\htdocs\\glpi\\front\\login.php(78): Auth->Login('YLA', '', false)\n#7 {main}\n  thrown in E:\\webserver\\Apache24\\htdocs\\glpi\\inc\\dbmysql.class.php on line 280

**Comment by satyan01** [comment]
I have latencies yet and aleatory error 500 when I try to connect to the server

**Comment by satyan01** [comment]
[26-Feb-2016 11:59:27 Europe/Berlin] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in E:\webserver\Apache24\htdocs\glpi\lib\Zend\I18n\Translator\Loader\Gettext.php on line 108

**Comment by satyan01** [comment]
[Mon Feb 29 10:49:19.158742 2016] [authnz_sspi:error] [pid 4832:tid 940] (OS 1727)The remote procedure call failed and did not execute.  : [client 192.168.102.26:57910] access to /glpi failed, reason: cannot generate server context

**Comment by satyan01** [comment]
192.168.102.26 - YLA [29/Feb/2016:15:52:41 +0100] "GET /glpi/front/login.php HTTP/1.1" 500 -

**Comment by satyan01** [comment]
the issue is only on 0.91, on the same server 0.85.2 works

**Comment by satyan01** [comment]
Could you help me please?

**Comment by satyan01** [comment]
I have searched in all logs, restarted apache, check php.ini, httpd.conf, glpi log and does not find anything.

**Comment by satyan01** [comment]
42.28 seconds blank page 
42.29 seconds blank page
460ms ok

after a time undetermined I have this behavior

**Comment by orthagh** [comment]
Please, could you resume the actions you have done, which version you use (0.91 is a development version) ?

**Comment by tomolimo** [comment]
Hello,
As far as I remember, you are running Windows 2012 server?
Is it the case?

**Comment by satyan01** [comment]
Hello I use windows 2008 r2

**Comment by satyan01** [comment]
I use 0.91 I have three times error 500 during 42.28s after that it works for a time. And the error comes back

**Comment by tomolimo** [comment]
> Hello I use windows 2008 r2

Then you may use IIS7.5 don't you?

**Comment by satyan01** [comment]
you have all my set up at the top of this topic

**Comment by satyan01** [comment]
I don't know IIS7.5 setup

**Comment by tomolimo** [comment]
> I don't know IIS7.5 setup

This is the configuration we have, and with no latencies, and very easy to maintain.
IIS has a very nice GUI for configuration
Here is what I propose: to install IIS (which is native on Windows server 2008R2): and if you agree, I can provide you a complete setup (with screen copies).

**Comment by satyan01** [comment]
I agree to try with you, thank you for your help

**Comment by tomolimo** [comment]
ok, then open another topic: named something like "How to install and configure PHP and GLPi on IIS"
or better: @orthagh: could it be possible to create a Wiki page with this new topic?

**Comment by orthagh** [comment]
Prepare a page with markdown syntax.

Wiki pages on this website is not a small decision.
We have a former on previous plateform with a lot of stuff (in textitle format) : https://forge.glpi-project.org/projects/glpi/wiki

I'd like to do it, but i don't have time to initiate a migration now.
Here is the prerequisites : 
- convert articles from textile to markdown (pandoc should help)
- clean obsolete articles

Anyway, i can create a dedicated repository on this organisation for "user's recipes".
Let me know.

**Comment by satyan01** [comment]
I have installed and configure IIS7 with auto logon ldap, but an error appears and switch between error=2 and login.php in the adress bar

**Comment by tomolimo** [comment]
Good, very good. It means that the sessions files can't be written into the files/_sessions folder
You need either to configure the fascgi.impersonate=0 in php.ini 
or to give rights to all users on the GLPi folders ("domain\authenticated users").

**Comment by satyan01** [comment]
I have done it and same behavior

**Comment by satyan01** [comment]
IT WORKS ¨!!!!

**Comment by tomolimo** [comment]
Could you tell us the main steps you've followed for IIS, PHP installation?

**Comment by satyan01** [comment]
http://www.iis.net/learn/application-frameworks/install-and-configure-php-on-iis/install-and-configure-php

**Comment by tomolimo** [comment]
I don't follow this, as I've installed "PHP Manager" it's a IIS module, and it manages all configs "behind the scene".
But at the end it's the same.
So do you still have latencies?

**Comment by satyan01** [comment]
no latencies

**Comment by tomolimo** [comment]
then close this issue, and if anything else occurs open a new one, and I'll try to help you.
