### ISSUE TITLE
Can`t print GANTT of project.

### ISSUE THREAD

**Issue by FrolON** [glpi-project/glpi#4713]
GLPI 9.3.0
There is no possible to print GANTT by GLPI functions.
If I try to print from the browser, I get a distorted result, same in different browsers:
![cant_print_gantt](https://user-images.githubusercontent.com/39527010/46078531-220b6b00-c19d-11e8-98a2-bb788e1a8a24.png)

**Comment by AnaelMobilia** [comment]
Hello @FrolON 
GANTT is provided using a third part [jQuery plugin](https://github.com/taitems/jQuery.Gantt/)

They didn't plan to provide an export tool ([as PDF](https://github.com/taitems/jQuery.Gantt/issues/178)).
This jQuery plugin doesn't really look like still supported by the author.
It's not sure than your issue can be fixed.

Regards,
Anael
