### ISSUE TITLE
[9.3.1] Import XML Rule =>Comment = "Array"

### ISSUE THREAD

**Issue by Jean-Christophe-P** [glpi-project/glpi#4714]
Dear GLPI Developer, 

When I want to import an XML file containing rules, the comments are not imported. Instead, I have the string "Array" in the comment.

Whether there is a comment in the XML 
"`<comment>bla bla bla</comment>`"
or not
"`<comment />`" or "`<comment></comment>`"
the result is the same.

------------
* Steps to reproduce (which actions have you made) :
Export rules as XML file cleanup the rules you do not want to import back,
Import you XML file. 

* Expected result :
Rule comment is empty or contains the XML file <comment> attribute.

* Actual result :
Comment field contains "Array"

* URL of the page :

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI 9.3.1 on Debian 9

**Comment by Jean-Christophe-P** [comment]
If there is no <comment> attribute in the rule XML, the problem is not present.

**Comment by Jean-Christophe-P** [comment]
damned, my quotes have been erased...

**Comment by trasher** [comment]
Are you sure you XML is valid and similar to the original one?
I've just tested thhe following : export rules, change one name, reimport modified XML; all seems to be ok.

**Comment by Jean-Christophe-P** [comment]
I honestly tried to be as close as the original file.
I striped down all but ONE rule, removed the UID, Date_creation and ranking.
My startup file was downloaded from GLPI.

The final goal is to forge an XML file to import location rules.
If you have any other method to do it, I would be glad to know :)

**Comment by trasher** [comment]
Double check your XML file, espacially for duplicate keys that should not be. i do not think there is any validation schema existing for this XML, so this is impossible to validate.
Try to edit another file (on maybe another instance) and tell us how this can be reproduced (or provide a faultly XML).

**Comment by Jean-Christophe-P** [comment]
Damned!!!
I can't reproduce it anymore!!!
I tried tens of times!

I was trying to prepare a faulty XML for you and I tried it "just be be absolutely sure" and it works...
I don't understand.

I'm sorry for your time :-(
