### ISSUE TITLE
History of removable components

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#4715]
The history (changes) of removable components (item with serial number etc) shouldn't be attached to the asset. It should attached to the component (item).

**Comment by trasher** [comment]
I do not understand; as fa as I can see, compoennts changes history is currently available in the component history.

**Comment by cedric-anne** [comment]
@Megachip Are you talking about https://github.com/glpi-project/glpi/pull/4677 ?

**Comment by Megachip** [comment]
@cedric-anne seems so.
E.G. when changing the serial number of an simcard, this is not shown on the simcard, but on the phone.

**Comment by cedric-anne** [comment]
@Megachip 

On GLPI 9.3.2, history is now on the asset (the Phone) and on the device (the DeviceSimcard).

Regards
