### ISSUE TITLE
New camera component

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#4716]
There is work in progress to inventory camera in android devices 

https://github.com/flyve-mdm/android-inventory-library/pull/170#issuecomment-425137466

To handle this, Fusion Inventory needs a spec and an implementation 
https://github.com/fusioninventory/fusioninventory.github.io/pull/56

GLPI needs to have a new component for cameras.

**Comment by cedric-anne** [comment]
Done in #8050.
