### ISSUE TITLE
can allow task without tech

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#472]
http://forum.glpi-project.org/search.php?action=show_new

I agree the request.
You must preselect the technician connected but allow task without technician assign

**Comment by tomolimo** [comment]
http://forum.glpi-project.org/viewtopic.php?id=144821

**Comment by yllen** [comment]
Merci du lien tomolimo j'ai fait un mauvais copier/coller

**Comment by tomolimo** [comment]
no problem, with pleasure :)

**Comment by yllen** [comment]
Merci pour cette correction.
Cependant il reste toujours un problème lors de la visualisation des tâches dans Traitement du ticket car c'est l'utilisateur connecté qui apparaît en dessous de la description de la tâche.
Par contre une fois qu'on double-clique sur la tâche le champ Par est bien à vide.
