### ISSUE TITLE
[9.3] Using solution in Change log ERROR

### ISSUE THREAD

**Issue by lufik** [glpi-project/glpi#4724]
* Steps to reproduce (which actions have you made) :
1. Create change
2. Close it using Solution tab

* Expected result :
No error in files/_log/php-errors.log

* Actual result :
```
[2018-10-02 01:13:01] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: internal_time_to_resolve
  Backtrace :
  inc/commonitilobject.class.php:1152                
  inc/change.class.php:293                           CommonITILObject->pre_updateInDB()
  inc/commondbtm.class.php:1369                      Change->pre_updateInDB()
  front/change.form.php:87                           CommonDBTM->update()
```

* URL of the page :
https://glpi.devel.invasys.org/front/change.form.php?id=3
https://glpi.devel.invasys.org/ajax/common.tabs.php?_target=/front/change.form.php&_itemtype=Change&_glpi_tab=ITILSolution$1&id=3&

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
Same as in issue #4682

**Comment by lufik** [comment]
I fixed CS problems in pull request. Should I be the assignee of this ticket?

**Comment by trasher** [comment]
Since you proposed the PR that fix the issue, yes you're the assignee ;)
