### ISSUE TITLE
[GLPI 0.90.1] Dots in Dropdowns

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#473]
In the dropdowns the dots are at the beggining and you can't see the name, for example in the network outlet.

This would not be a problem if you could view the information of the network outlet on the " i " icon, but not shown (bug).

(http://glpi.userecho.com/topics/20-glpi-0901-dots-in-dropdowns/#comment-353)

**Comment by yllen** [comment]
I don't have dots in dropdown for network outlet. Cans you paste a picture?

**Comment by jsamaniegog** [comment]
![dots](https://cloud.githubusercontent.com/assets/15769828/13212083/96a6849e-d93e-11e5-94ba-4fa166c323fe.png)

**Comment by elquim** [comment]
Same issue for me, with no selection 3 dots, after selecting 3 dots plus last characters of the selection.

On click you can see the selected option highlighted.

![image](https://cloud.githubusercontent.com/assets/17473918/13320049/45113432-dbc6-11e5-8f4f-8540eb780c2a.png)


![image](https://cloud.githubusercontent.com/assets/17473918/13320081/8ee9c3b2-dbc6-11e5-9c74-bbe543b88057.png)

**Comment by tomolimo** [comment]
Do you have somewhere in your browser or in your system or in a browser extension a setting about right-to-left text display?

**Comment by orthagh** [comment]
Please, provide your browser name and his version

**Comment by tomolimo** [comment]
I realized that I have also this problem. :smiley: 
With IE10:
It's not everywhere but look at a computer in split view, and show the management tab, then select a supplier (one with a long name), 
![image](https://cloud.githubusercontent.com/assets/7569958/13320444/5c14675a-dbc9-11e5-8577-7bc90e11d59c.png)

For this HTML element: the div with id=s2id_dropdown_suppliers_idxxxxxxx, there is a max size of 70%. if you delete this width, then you get:

![image](https://cloud.githubusercontent.com/assets/7569958/13320484/ae5af2ae-dbc9-11e5-94e5-0da4b2d3ff36.png)

**Comment by elquim** [comment]
You're rigth both, it looks fine using 
Google-Chrome (Version 33.0.1750.149) 

but not on som other browsers: 
Seamonkey (version 2.19)
Firefox (version 22.0)

**Comment by orthagh** [comment]
right elipsis is provided by this piece of code : 
https://github.com/glpi-project/glpi/blob/master/css/styles.css#L265-L312

And initialy this issue requested the change : 
https://github.com/glpi-project/glpi/pull/76

Not so recent versions of popular browser should pass this css and provide elispis (...) only when needed (so it's wanted, but not in all cases, just for prevent overflow and broken design).
Firefox 22 is old (my opinion), current ESR version is 38.x
I don't use Seamonkey.

Anyway, the real bug is why you don't have the full name in tooltip

**Comment by orthagh** [comment]
The commit who introduced correct left ellispis : 
https://github.com/glpi-project/glpi/commit/83e610f48623eb294b20d74a3e6bc50a229b8979

**Comment by elquim** [comment]
I tried with Firefox 44.02 (latest version) and is working fine. I guess developers have been working with recent browsers.
Fixing working browser version is enough for me.
Thanks for your help!

**Comment by tomolimo** [comment]
Did you do a test with GLPI 0.91?
For me this is still present see:
![image](https://cloud.githubusercontent.com/assets/7569958/13350208/f8d7bfc8-dc7e-11e5-995d-d5e68d07faa3.png)

**Comment by orthagh** [comment]
as i say previouslay, it's wanted.

If sentence is too long, the text is truncated on the left.
If not, full sentence appears

**Comment by tomolimo** [comment]
Sorry I though that applied to 'ellipsis' and not to 'left' in your comment...

But traditionally in "occidental cultures" the ellipsis are on the right and not on the left.

**Comment by orthagh** [comment]
In case of long tree dropdown, i think truncate of the left is better (in our glpi context).
In term of complexity, right ellipsis is more easier to do (i'll love to redo that)

**Comment by yllen** [comment]
I agree with @orthagh 
In our GLPI context on the left is the begin of the hierarchical. So put ellipsis on right you will never see the final name, only the parent one.

**Comment by tomolimo** [comment]
I agree when displaying the tree view, but when displaying the value in the dropdown (like in https://github.com/glpi-project/glpi/issues/473#issuecomment-189218857) we should have the complete name, and not only the end.
