### ISSUE TITLE
Validation comment formatting

### ISSUE THREAD

**Issue by tgrignon** [glpi-project/glpi#4736]
When we create a validation and put some comments on it, it will send a link to the user with the URL 

**glpi/front/ticket.form.php?id=78320&forcetab=TicketValidation$1**

The problem is the text formatting. If we use break lines or something else, the text will not be format. I need to show something more friendly to my users. I changed the code into **inc/commonitilvalidation.class.php** into GLPI 9.3, line 868

`echo "<td>".$row["comment_submission"]."</td>";`

For

`echo "<td><pre style='font-family: tahoma'>".$row["comment_submission"]."</pre></td>";`

Is it possible to put that in a next release so I will not need to change the code anymore?

Thank you.

**Comment by cedric-anne** [comment]
Hi,

Rich text feature has been added on validation. It will be available in next GLPI major version.
See #9062

Regards
