### ISSUE TITLE
No satisfaction survey if i opened and solve the ticket

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#474]
When i open and solve a ticket I should not respond the satisfaction survey.

**Comment by yllen** [comment]
Satisfaction survey is generated only after close ticket

**Comment by jsamaniegog** [comment]
I know, I mean I should not respond to the survey of satisfaction when I open, solve and close the ticket,
I can not rate myself.

**Comment by yllen** [comment]
You must wait the cron to generate the survey before reply to it.

**Comment by jsamaniegog** [comment]
I must not be explaining this clearly... (sorry for my English), i try again: if i am the technician and i open a ticket that i solve and close, i shouldn't rate me (logically)

**Comment by yllen** [comment]
If you work on a call center you create the ticket, solve it.
You also approve solution and reply to survey after call to the requester.
I purpose to use a parameter to allox approbation of the solution and reply to survey.
Look at: https://github.com/glpi-project/glpi/issues/340
