### ISSUE TITLE
Ticket View show Ticket from Other entities after upgrade from 9.2.3 to 9.3.1

### ISSUE THREAD

**Issue by Bigjoke007** [glpi-project/glpi#4742]
Hi all,

There is my Issue:

Root> Entity_A
Root> Entity_B

When I'm in Entity_B I can see Tickets from Entity_A in the list of ticket (access denied if I try to open)

**Comment by cedric-anne** [comment]
Hi,

I cannot replicate this issue on https://demo.glpi-project.org/. You do not provide your GLPI version, so I assume that the bug has been fixed between the version you used and the 9.4.0.

Regards
