### ISSUE TITLE
Ability to attach files when solving a ticket.

### ISSUE THREAD

**Issue by EugeneSE79** [glpi-project/glpi#4750]
Hello dear Team.
Tell me, how can I return a function to attach a document when describing a solution?

**Comment by EugeneSE79** [comment]
Hello dear Team.
Tell me, how can I return a function to attach a document when describing a solution?

**Comment by trasher** [comment]
This does not seems possible right now.
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
