### ISSUE TITLE
Introduce with #424

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#476]
https://github.com/glpi-project/glpi/pull/424

**Comment by yllen** [comment]
*** PHP Notice(8): Undefined index: id
  Backtrace :
  inc/item_ticket.class.php:240                      
  inc/ticket.class.php:4168                          Item_Ticket::itemAddForm()
  inc/commonglpi.class.php:464                       Ticket->showForm()
  ajax/common.tabs.php:94                            CommonGLPI::displayStandardTab()


$tt has no id

**Comment by yllen** [comment]
How create an anonymous ticket with item associated ?

**Comment by orthagh** [comment]
@korial29 Could you check this issue

**Comment by yllen** [comment]
This error was only when you don't have template of ticket defined
