### ISSUE TITLE
[9.3.1] - contract notification sent on wrong date

### ISSUE THREAD

**Issue by joschi99** [glpi-project/glpi#4760]
* Steps to reproduce (which actions have you made) :
1. create a contract with start date, initial contract period, notice, email alarms ecc.

* Expected result :
1. email alarm should be sent on correct date

* Actual result :
1. email alarm is sent on wrong date

* Screenshot of the problem (if pertinent) :
![2018-10-10 17_23_35-glpi - contract - 11](https://user-images.githubusercontent.com/6400595/46747452-a1c32a80-ccb1-11e8-9093-f042309105f9.png)

Please note that problem is also on GLPI 9.2.x

**Comment by joschi99** [comment]
Are there any news about this issue?

**Comment by Eon9D** [comment]
Do you have a isolated system for testing?

**Comment by Eon9D** [comment]
To make it short. Can you test if it works for new contracts?(It should - only old contracts cause this problem). Seems you using GLPI for a longer time. There was a BUG that calculated wrong that got fixed but it didn't seems to fix the DB. For me it seemed to help to clean the glpi_alerts table (testet 15min ago - looks good so far).
BELETE FROM `glpi_alerts` WHERE itemtype = "Contract"; (TEST SYSTEM!)
Can you report if that fixed it?

**Comment by trasher** [comment]
Make sure you PHP timezone settigns are the same for web and cli.

**Comment by joschi99** [comment]
I have done some test on GLPI 9.4 with new contracts and the issue seem's solved.

Thanks
