### ISSUE TITLE
GLPI 9.3.1 - Recurring Tickets

### ISSUE THREAD

**Issue by mauriciolamego** [glpi-project/glpi#4761]
* Steps to reproduce (which actions have you made) :
I created a recurring ticket to be created all day 05, with monthly frequency and without preliminary creation. This recurring ticket is linked to a calling template where you have standardized some predefined items.
![image](https://user-images.githubusercontent.com/40633272/46775074-f24f7d80-ccdb-11e8-97a6-0436776ae1f0.png)

if I go in the information tab, there is only the day that has been configured.

* Expected result :
The ticket is expected to be opened on the specified day.

* Actual result :
But the ticket is being opened more than once and at different times. At least two tickets were opened when it should actually be a single ticket on the specified date. In an interval not fixed, but in average 03 days, 02 tickets were opened.

* URL of the page :
https://meudominio.com.br/HelpDesk/front/ticketrecurrent.php 

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
![image](https://user-images.githubusercontent.com/40633272/47375237-36705400-d6c6-11e8-880e-e111038063d2.png)
![image](https://user-images.githubusercontent.com/40633272/47375277-4be57e00-d6c6-11e8-9440-1e8fa0a46d74.png)
![image](https://user-images.githubusercontent.com/40633272/47375310-60c21180-d6c6-11e8-8a74-bce41f7ccea6.png)

**Comment by Armin83** [comment]
Of cource for your needs you have to use cli mode in the automation run mode. Do you know this ?

**Comment by mauriciolamego** [comment]
Currently the mode of execution of the automatic action "recurrent ticket" is configured for GLPI, and I believe that answers because I configured the CRON to call the page cron.php. Actions are running every hour as expected. The problem is that the recurring call is being opened more than once regardless of the specific time I scheduled.

**Comment by mauriciolamego** [comment]
I believe it is related to the newly created call # 4790

**Comment by ebourgui** [comment]
Same for me (in cli mode).
