### ISSUE TITLE
No email memorization in SSO authentification when an user is created

### ISSUE THREAD

**Issue by Nexoz** [glpi-project/glpi#4764]
Hi, 

When a new user connects through external authentification (conveyed by an HTTP request), there is no memorization of the email address that was in the SAML2 request.

This is due by not setting an external authtype in the method `getFromSSO` in the User class.
So, the user authentification type is not considered like that in the function `syncDynamicEmails`, and therefore there is no mail synchronization.

Putting the attribute `authtype` on `Auth::EXTERNAL` in the `getFromSSO` method fixed it for us.

We're using GLPI v9.2.4.

```php
   function getFromSSO() {
      global $DB, $CFG_GLPI;
 
      $a_field = [];
      foreach ($CFG_GLPI as $key=>$value) {
         if (!is_array($value) && !empty($value)
             && strstr($key, "_ssofield")) {
            $key = str_replace('_ssofield', '', $key);
            $a_field[$key] = $value;
         }
      }
 
      if (count($a_field) == 0) {
         return true;
      }
      $this->fields['_ruleright_process'] = true;
      $this->fields["authtype"] = Auth::EXTERNAL; // Fix here
      foreach ($a_field as $field=>$value) {
      …
  }
```

Thank you in advance for your consideration.

**Comment by Nexoz** [comment]
I'm not able to try the versions for few weeks, but the source code seems to remain unchanged in those 2 methods in the last version.

**Comment by trasher** [comment]
This may be solved elsewhere. Anyways, I do not have any setup to reproduce.

**Comment by trasher** [comment]
No feedback from a while, closing.
