### ISSUE TITLE
Unable to import users from AD and "Login again error"

### ISSUE THREAD

**Issue by piyush1337** [glpi-project/glpi#4786]
![forum](https://user-images.githubusercontent.com/44155118/46933947-aef66580-d073-11e8-9a1d-013649f77459.jpg)
![forum1](https://user-images.githubusercontent.com/44155118/46933962-bae22780-d073-11e8-8a3d-984718d294ed.jpg)
![forum3](https://user-images.githubusercontent.com/44155118/46933974-c33a6280-d073-11e8-85e3-95baad73ade6.JPG)
![forum4](https://user-images.githubusercontent.com/44155118/46933986-cb929d80-d073-11e8-812a-dee103054d5c.jpg)

Here are the screenshots attached of my configuration and you can see i am not able to import and i have gone through many threads but still unable to find the solution as the test is successful

and there are some already imported users in past but when i login from that it says "login again"

Please help me to resolve my issue 

Thanks

**Comment by trasher** [comment]
There are several already opened issues on LDAP/AD import and login issues ; and you're using an old release.

So, please test with last release (9.3.1) and if problem persists, check existing issues for somathing similar. Feel free to reopen if it still persists with all that.

**Comment by piyush1337** [comment]
I have checked all threads related to that but didn't find any solution please help and that's why i have put up my config here so that everything is cleared
