### ISSUE TITLE
When planned task is moved then the planning recall notification is not send again on new time

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#4790]
Dear all,

* Steps to reproduce (which actions have you made) :
1. Create a task in a ticket
1. add a planning to this task (ex: today at 10:00 for 1H)
1. add a reminder (15 minutes)
1. This reminder will be sent (around 9:45) (be sure that planning recall cron action is on)
1. and then move the task to another day in the future (the reminder is still attached to the task)
1. But at the time when Reminder should occur, then there is none

* Expected result :
1. a new reminder for the task should be sent as the task has been moved into the future and the date of the reminder is after NOW()

* Error logs
None

* Code
I looked into the code, and this behavior is not implemented in any GLPI releases.

Thank you,
Regards,
Tomolimo

**Comment by mauriciolamego** [comment]
I believe it is related to the Issue call #4761
