### ISSUE TITLE
Sql error on project task with linked ticket

### ISSUE THREAD

**Issue by Blank-Vcf** [glpi-project/glpi#4795]
Since update to 9.3 users cannot seen ticket link to project task
From url: /front/projecttask.form.php?id=xxx

we can see:
Durée des tickets : 3 jours 17 heures 38 minutes
Durée totale : 3 jours 17 heures 38 minutes

ticket number show none and in sql log this error popup :

> [2018-10-16 15:24:39] glpisqllog.ERROR: DBmysql::query() in /var/www/inc/dbmysql.class.php line 177
>   *** MySQL query error:
>   SQL: SELECT COUNT(*) AS cpt FROM `glpi_projecttasks_tickets` LEFT JOIN `glpi_tickets` ON (`glpi_projecttasks_tickets`.`tickets_id` = `glpi_tickets`.`id`) INNER JOIN `glpi_entities` ON (`glpi_tickets`.`entities_id` = `glpi_entities`.`id`) WHERE `glpi_projecttasks_tickets`.`projecttasks_id` = '30' AND (`glpi_tickets`.`entities_id` IN ('4', '5', '9', '7', '6', '10') OR (`glpi_tickets`.`is_recursive` = '1' AND `glpi_tickets`.`entities_id` IN ('0'))) ORDER BY `glpi_entities`.`completename`, `glpi_tickets`.`name`
>   Error: Unknown column 'glpi_tickets.is_recursive' in 'where clause'
>   Backtrace :
>   inc/dbmysqliterator.class.php:95                   
>   inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
>   inc/commondbrelation.class.php:1733                DBmysql->request()
>   inc/projecttask_ticket.class.php:75                CommonDBRelation::countForItem()
>   inc/commonglpi.class.php:210                       ProjectTask_Ticket->getTabNameForItem()
>   inc/projecttask.class.php:194                      CommonGLPI->addStandardTab()
>   inc/commonglpi.class.php:165                       ProjectTask->defineTabs()
>   ajax/updatecurrenttab.php:46                       CommonGLPI->defineAllTabs()

Error only appear if we use any profile that "super admin"

**Comment by trasher** [comment]
I'm pretty sure this one has already been reported and fixed; please check.
