### ISSUE TITLE
Sensitive search by components(proccessors, memories, soundcards...) in Assets->Computers.

### ISSUE THREAD

**Issue by Muilton** [glpi-project/glpi#480]
Sensitive search by components(proccessors, memories, soundcards...) in
Assets->Computers.
Plugin FusionInventory/
I cann't fix it. Help me, please! Thank you!
Location and type work without sensitive search(upper-and lower-case), but @processors@ doesn't work, if first letter in lower case.

**Comment by yllen** [comment]
I made a test and i have no problem with upper/lower case in search engine.
Which version of GLPI do you used?

**Comment by Muilton** [comment]
I use GLPI version 0.85.2., but version of plugin Fusioninventory is latest
 upper/lower case in search BY COMPONENTS (PROCESSORS, RAM...) - THIS IN PLUGIN FUSION INVENTORY, but search good works in SIMPLE GLPI(search by Characteristics ).
Example:::::::
Items Seen:
-----Characteristics  - work
-----Components - not work

Sorry for my English!

**Comment by orthagh** [comment]
Hello @Muilton 

My tests on current 0.90/bugfixes branch : 
![image](https://cloud.githubusercontent.com/assets/418844/13392512/61209a1a-dedb-11e5-9ec6-d30a82072237.png)


0.85.2 glpi version is not supported anymore.
Could you do an upgrade of your installation and test this issue again ?

**Comment by Muilton** [comment]
I updated glpi to 0.90.1 but it doesn't fixed this problem!
![duo](https://cloud.githubusercontent.com/assets/7372020/13665327/f530a194-e6bc-11e5-8da7-405d0e0341b7.png)
![duo_1](https://cloud.githubusercontent.com/assets/7372020/13665332/fc201cf0-e6bc-11e5-95e7-949d68e5cda1.png)

**Comment by yllen** [comment]
Can you try with plugin FusionInventory de-activated?

**Comment by Muilton** [comment]
Yes, I try without plugin FusionInventory, but it don't work!
