### ISSUE TITLE
API [9.3.1] solution field's missing

### ISSUE THREAD

**Issue by marioace** [glpi-project/glpi#4804]
Since v9.3.0, the API doesn't comes with the solution field, and that's very helpfull when you're calling the GLPI from another system.

Now you have

    "date": "2017-01-26 11:52:26",
    "closedate": null,
    "solvedate": "2017-01-31 15:54:11",
    "date_mod": "2017-01-31 15:54:11",
    "users_id_lastupdater": 515,
    "status": 5,
    "users_id_recipient": 371,
    "requesttypes_id": 2,
......
but the "solution": is missing.

GLPI 9.3.1 ( => /var/www/html/glpi)
Installation mode: TARBALL

Is there any chances to get the solution field back again?

**Comment by trasher** [comment]
Solution is no longer a field; but it's handled in an ITILSolution object.
