### ISSUE TITLE
[9.3.1] Historical of the ticket is with the empty solution (N/A)

### ISSUE THREAD

**Issue by mauriciolamego** [glpi-project/glpi#4808]
* Steps to reproduce (which actions have you made) :
![image](https://user-images.githubusercontent.com/40633272/47223316-57b40600-d38f-11e8-9c99-cfd3394a7691.png)
![image](https://user-images.githubusercontent.com/40633272/47223351-72867a80-d38f-11e8-99a1-963fa3a03c50.png)
The solution of the ticket was given by the technician, appears in the accompaniment of the call correctly, but when checking in the history appears as N / A.

* Expected result :
In the history the text of the given solution appears. Some plugins use this information to generate reports, data, and statistics.

* Actual result :

2019606 | 15-10-2018 15:28 | technician (387) | Solution | Add an item: **Solution (N/A (8477))**

* URL of the page :
https://mydomain/front/ticket.form.php?id=6139

* Screenshot of the problem (if pertinent) :

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

![image](https://user-images.githubusercontent.com/40633272/47374883-6a974500-d6c5-11e8-8996-3635a1a43abe.png)
![image](https://user-images.githubusercontent.com/40633272/47374970-97e3f300-d6c5-11e8-99cd-3b71a763c8dc.png)
![image](https://user-images.githubusercontent.com/40633272/47375093-dbd6f800-d6c5-11e8-9bc7-9b0399ca9233.png)

**Comment by trasher** [comment]
>    In the history the text of the given solution appears. Some plugins use this information to generate reports, data, and statistics.

This is not a good idea. And also note that before 9.3.0, part of the solution was indeed stored in the logs that is no longer true. Plugins have to adapt.

**Comment by mauriciolamego** [comment]
Okay, thank you for the answer. I thought it was a mistake.
Thanks!
