### ISSUE TITLE
Windows OS Name and Version not Updating

### ISSUE THREAD

**Issue by letsridehawk65** [glpi-project/glpi#4811]
* Steps to reproduce (which actions have you made) : Update a Windows PC OS (Windows 7 to Windows 10) and run inventory update (Fusion Inventory Agent).  The listed OS Name and version doesn't update in GLPI.  Check the OS information from the "Download inventory file" and it lists the correct OS information.

* Expected result : OS Information getting updated by inventory agent

* Actual result : OS information doesn't change

* URL of the page : glpi/front/computer.form.php

* Screenshot of the problem (if pertinent) : N/A

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

Information about system installation and configuration
--
[code]   GLPI 9.3.1 (/glpi => C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi) Installation mode: TARBALL

Operating system: Windows NT INVENTORY 10.0 build 14393 (Windows Server 2016) AMD64 PHP 7.1.18 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, gd, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mongodb, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, readline, session, standard, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, 	zlib) Setup: max_execution_time="600" memory_limit="64M" post_max_size="40M" safe_mode="" session.save_handler="files" 	upload_max_filesize="40M"  Software: Apache () 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.67 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.22 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (5.7.22) - Perfect! C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_log : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/config : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_dumps : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_sessions : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_cron : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_graphs : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_lock : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_plugins : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_tmp : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_cache : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_rss : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_uploads : OK C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\lib\htmlawed) SimplePie version 1.5.2 in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\vendor\simplepie\simplepie\library) TCPDF version 6.2.17 in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\vendor\true\punycode\src) iacaml/autolink in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\Bitnami\wampstack-7.1.18-1\apache2\htdocs\glpi\vendor\sabre\vobject\lib)

Not active

Way of sending emails: PHP

 

fields               Name: Additionnal fields             Version: 1.8.2      State: Enabled 	datainjection        Name: File injection                 Version: 2.6.3      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.3+1.1    State: Enabled
[/code]

**Comment by trasher** [comment]
Issue is from fusion pluin, not glpi (and has already been reported on their side).
