### ISSUE TITLE
Error during fresh installation of GLPI 9.3.1

### ISSUE THREAD

**Issue by cadegenn** [glpi-project/glpi#4814]
* Steps to reproduce (which actions have you made) :
Install GLPI from scratch. Manually create a database.
Launch installation wizard. Select database previously created.

* Expected result :
Installation complete.

* Actual result :
GLPI SETUP hang at step #3 "initializing databsase" (translated) with no message.

glpi error-log says : 
```
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE TABLE `glpi_alerts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemtype' at line 36
  Backtrace :
  inc/dbmysql.class.php:539                          
  inc/toolbox.class.php:2363                         DBmysql->runFile()
  install/install.php:388                            Toolbox::createSchema()
  install/install.php:649                            step4()
  {"user":"@glpi1804","mem_usage":"0.006\", 125.47Mio)"} 
```

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
GLPI is not installed. version is 9.3.1 from github.

Thanks.

**Comment by cadegenn** [comment]
hmm sorry my fault. It seems my mysql user had not enough rights.
maybe in this documentation https://glpi-install.readthedocs.io/en/latest/prerequisites.html#database you could add how to create a new mysql user dedicated to glpi. For example : 
```
GRANT ALL PRIVILEGES ON `glpi%`.* to `glpi_user`@`%` identified by '********';
flush privileges;
```
You can close this issue. Sorry.
Great job by the way.

**Comment by ramoncruzp** [comment]
hi i got the same error bu my user got all the rights.

**Comment by Bankole2000** [comment]
> hi i got the same error bu my user got all the rights.

Where you able to solve the issue, coz I'm facing it right now @ramoncruzp
