### ISSUE TITLE
[9.3.1] Users of a child entity in the list of tickets observers

### ISSUE THREAD

**Issue by aden45** [glpi-project/glpi#4819]
Hi,

We migrated to version 9.3.1 (we had version 0.91). Since then, it is no longer possible to see, in the oberver zone, the users belonging to a sub entity without having to put themselves in the entity in question.
A "Manager" person, managing several sites (child entities), wants to be able to add people from a sub entity as an observer when creating a ticket without having to switch to the child entity. The "Manager" person has of course the recursive rights on the sub entities.

Do you know where this could come from and if there is a way to re-display users from a sub entity?

Thanks.

**Comment by yllen** [comment]
You can see in a user dropdown of a ticket only users who have right on the entity of the ticket.
