### ISSUE TITLE
0.91: Can't set user default value for Lock

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#482]
If user wants to set its own default value for lock: it's no longer possible:
![image](https://cloud.githubusercontent.com/assets/7569958/13214203/84535640-d94e-11e5-8d7b-114ab98a4f61.png)
Due to this commit in file update_0901_091.php line 280/313: https://github.com/glpi-project/glpi/commit/2ccf455962fa9775c742cd2b7009cd2f05533376#diff-564956cf34a3d734c70d54cc17d4ca1bL280

and due to this commit in file glpi-0.91-empty.sql:
https://github.com/glpi-project/glpi/blob/13b4b3f1562d36b1b639409722bd3d719178367a/install/mysql/glpi-0.91-empty.sql#L7466

**Comment by orthagh** [comment]
merged
