### ISSUE TITLE
Add JS in head

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#4822]
Hi,

It's more of a question than an issue but i find this nowhere :
Is there a way to add a JS script in <head> tag ? 

I'm using : 
$PLUGIN_HOOKS['add_javascript']['myPlugin'][] = 'myPlugin.js';
$PLUGIN_HOOKS['javascript']['myPlugin'][] = '/path/of/myPlugin.js';

But it add the script at the end of the <body> tag.

If it's not possible, 
is there a way to add a script at the begin of the body not at the end ?

**Comment by trasher** [comment]
This is not possible to add javascript elsewhere. Just deal with the ondomloaded event and you're done.
