### ISSUE TITLE
[9.3.2] major API break 

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#4837]
See 7e0ebc6023 

At least FusionInventory is broken

`PHP Warning: Declaration of PluginFusioninventoryInventoryRuleImport::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array) in /usr/share/glpi/plugins/fusioninventory/inc/inventoryruleimport.class.php at line 0`

Why did this happens on a stable release ?

**Comment by cedric-anne** [comment]
For information, change on GLPI side has been requested to be able to do https://github.com/fusioninventory/fusioninventory-for-glpi/pull/2590 on FI plugin side.

**Comment by remicollet** [comment]
IMHO: 9.3.2 + revert = 9.3.3 with a quick release to fix BC break.

**Comment by cedric-anne** [comment]
Hi,

Even if I agree such a change should not happen on a stable branch, I close this issue as 9.3 branch is not maintained anymore so no new release will be made to handle this.

Regards
