### ISSUE TITLE
[9.3.2] Can't filter tickets by "Assigned to - Technician"

### ISSUE THREAD

**Issue by freewood** [glpi-project/glpi#4838]
* Steps to reproduce (which actions have you made) :
1. Open tickets page;
2. Choose in filter "Assigned to - Technician";
3. Open dropdown menu.

* Expected result :
List of technicians.

* Actual result :
Message "The results could not be loaded".

* URL of the page :
https://glpi.address/front/ticket.php

* Screenshot of the problem (if pertinent) :
[Screenshot](http://funkyimg.com/i/2MAsW.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :
```
GLPI 9.3.2 ( => /var/www/sd)
Installation mode: TARBALL

Operating system: Linux sd.example.com 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
PHP 7.0.30-0+deb9u1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)

Setup: max_execution_time="30" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: nginx/1.15.5
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Server Software: (Debian)
	Server Version: 5.6.30-1-log
	Server SQL Mode: 
	Parameters: glpi_user@127.0.0.1/glpi_db
	Host info: 127.0.0.1 via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is not present
Database version seems correct (5.6.30) - Perfect!
OK/var/www/sd/files/_log : OK
OK/var/www/sd/config : OK
OK/var/www/sd/files : OK
OK/var/www/sd/files/_dumps : OK
OK/var/www/sd/files/_sessions : OK
OK/var/www/sd/files/_cron : OK
OK/var/www/sd/files/_graphs : OK
OK/var/www/sd/files/_lock : OK
OK/var/www/sd/files/_plugins : OK
OK/var/www/sd/files/_tmp : OK
OK/var/www/sd/files/_cache : OK
OK/var/www/sd/files/_rss : OK
OK/var/www/sd/files/_uploads : OK
OK/var/www/sd/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/sd/lib/htmlawed)
SimplePie version 1.5.2 in (/var/www/sd/vendor/simplepie/simplepie/library)
TCPDF version 6.2.25 in (/var/www/sd/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/sd/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/sd/vendor/true/punycode/src)
iacaml/autolink in (/var/www/sd/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/sd/vendor/sabre/vobject/lib)

fusioninventory    Name: FusionInventory    Version: 9.3+1.1    State: Not installed
mydashboard       Name: My Dashboard      Version: 1.6.1        State: Not installed
telegrambot         Name: TelegramBot          Version: 2.0.0        State: Not activated
reports                 Name: Report                   Version: 1.11.3      State: Not activated
dashboard            Name: Dashboard            Version: 0.9.4        State: Not activated
behaviors             Name: Behaviors               Version: 2.1.1        State: Enabled
formcreator          Name: Forms                    Version: 2.6.4        State: Not activated
```

**Comment by dunipj** [comment]
Same problem here.

![image](https://user-images.githubusercontent.com/35108492/47666622-d0327800-db82-11e8-866b-c159a875829d.png)

**Comment by freewood** [comment]
> 
> 
> Please provide logs contents
```
2018/10/29 20:43:55 [error] 1798#1798: *176623 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Zend\Cache\Psr\SimpleCache\SimpleCacheInvalidArgumentException: Invalid key "glpi_entities_ancestors_cache_0|27|6|44|4|3|7|1|49|43|8|28|36|9|56|29|11|5|37|53|12|30|13|16|40|55|57|52|42|18|19|51|2|26|47|20|21|22|50|23|41|25|32|38|46|54|58" provided; key is too long. Must be no more than 64 characters in /var/www/sd/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php:344
Stack trace:
#0 /var/www/sd/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php(279): Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator->validateKey('glpi_entities_a...')
#1 /var/www/sd/inc/dbutils.class.php(802): Zend\Cache\Psr\SimpleCache\SimpleCacheDecorator->has('glpi_entities_a...')
#2 /var/www/sd/inc/dbutils.class.php(563): DbUtils->getAncestorsOf('glpi_entities', Array)
#3 /var/www/sd/inc/db.function.php(653): DbUtils->getEntitiesRestrictRequest('AND', 'glpi_profiles_u...', '`glpi_profiles_...', Array, 1, false)
#4 /var/www/sd/inc/user.class.php(3" while reading response header from upstream, client: xx.xx.xx.xx, server: glpi.example.com, request: "POST /ajax/getDropdownUsers.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/sd-php-fpm.sock:", host: "glpi.example.com", referrer: "https://glpi.example.com/front/ticket.php"
```
Only this message appears when dropdown menu opens, it's nginx error log.

**Comment by dunipj** [comment]
Access.log

192.168.1.1 - - [29/Oct/2018:15:03:31 -0300] "POST /glpi/ajax/getDropdownUsers.php HTTP/1.1" 500 - "http://glpi/glpi/front/ticket.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"
192.168.1.1 - - [29/Oct/2018:15:03:33 -0300] "POST /glpi/ajax/getDropdownUsers.php HTTP/1.1" 500 - "http://glpi/glpi/front/ticket.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134"

Error.log

[Mon Oct 29 15:04:18.750566 2018] [:error] [pid 20354] [client 192.168.1.1:49710] PHP Fatal error:  Uncaught exception 'Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheInvalidArgumentException' with message 'Invalid key "glpi_entities_ancestors_cache_0|48|49|58|57|29|39|50|53|54|40|51|52|1|56|2|55|36|37|38" provided; key is too long. Must be no more than 64 characters' in /var/www/html/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php:344\nStack trace:\n#0 /var/www/html/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php(279): Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheDecorator->validateKey('glpi_entities_a...')\n#1 /var/www/html/glpi/inc/dbutils.class.php(802): Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheDecorator->has('glpi_entities_a...')\n#2 /var/www/html/glpi/inc/dbutils.class.php(563): DbUtils->getAncestorsOf('glpi_entities', Array)\n#3 /var/www/html/glpi/inc/db.function.php(654): DbUtils->getEntitiesRestrictRequest('AND', 'glpi_profiles_u...', '', Array, 1, false)\n#4 /var/www/html/glpi/inc/user.class.php(3377): getEntitiesRestrictRequest('AND', 'glpi_profiles_u... in /var/www/html/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php on line 344, referer: http://glpi/glpi/front/ticket.php
[Mon Oct 29 15:04:21.184972 2018] [:error] [pid 20706] [client 192.168.1.1:49711] PHP Fatal error:  Uncaught exception 'Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheInvalidArgumentException' with message 'Invalid key "glpi_entities_ancestors_cache_0|48|49|58|57|29|39|50|53|54|40|51|52|1|56|2|55|36|37|38" provided; key is too long. Must be no more than 64 characters' in /var/www/html/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php:344\nStack trace:\n#0 /var/www/html/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php(279): Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheDecorator->validateKey('glpi_entities_a...')\n#1 /var/www/html/glpi/inc/dbutils.class.php(802): Zend\\Cache\\Psr\\SimpleCache\\SimpleCacheDecorator->has('glpi_entities_a...')\n#2 /var/www/html/glpi/inc/dbutils.class.php(563): DbUtils->getAncestorsOf('glpi_entities', Array)\n#3 /var/www/html/glpi/inc/db.function.php(654): DbUtils->getEntitiesRestrictRequest('AND', 'glpi_profiles_u...', '', Array, 1, false)\n#4 /var/www/html/glpi/inc/user.class.php(3377): getEntitiesRestrictRequest('AND', 'glpi_profiles_u... in /var/www/html/glpi/vendor/zendframework/zend-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php on line 344, referer: http://glpi/glpi/front/ticket.php

**Comment by trasher** [comment]
Thank you. Please test fix proposed in https://github.com/glpi-project/glpi/pull/4845

**Comment by freewood** [comment]
> 
> 
> Thank you. Please test fix proposed in #4845

Looks like this solve the problem. Thank you.

**Comment by dunipj** [comment]
Hi ! 

Change only this file ? inc/dbutils.class.php ?

This one exists ? tests/functionnal/DbUtils.php ?

Tks

**Comment by dunipj** [comment]
OK, thank you ! Now it's working !
