### ISSUE TITLE
0.91: when a ticket task has no planning then it appears nowhere!

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#484]
Hello,
When a ticket task is not planned, then it appears nowhere!
Not even in the user reminders.
Is it by design or a forgotten feature?
Regards,
Tomolimo

**Comment by yllen** [comment]
The ticket task appeared only in ticket.
How do we know user assign to a task if the By field is empty?

**Comment by tomolimo** [comment]
As far as I know : it's possible to assign a tech to a task without plan it!
![image](https://cloud.githubusercontent.com/assets/7569958/13356056/c5740716-dca3-11e5-8c5b-72cd356cbdf1.png)

Apart opening each ticket and selecting the processing tab, a tech assigned to not-planned tasks is not able to view his assigned tasks (like planned tasks on home page).

**Comment by yllen** [comment]
OK. So if i well understand:
when you assign a task to a technician, you want and automatic creation of a reminder?

**Comment by tomolimo** [comment]
Don't know exactly, could be a good idea to show something on the home page.
May be a new panel for not "planned tasks to do": I don't know.

**Comment by orthagh** [comment]
relative to the new issue #758

**Comment by trasher** [comment]
Duplicated by #2119; but the new one seems more clear ;)
