### ISSUE TITLE
New followup email notification without carrage return

### ISSUE THREAD

**Issue by choyrack** [glpi-project/glpi#4840]
Hello

GLPI send email notification about new follow up without carriage return, when new follow up was created by email.

1. Create new ticket by email
2. Add new followup by email

![screenshot_13](https://user-images.githubusercontent.com/44571016/47644787-6a88c080-db6f-11e8-9273-f881bf029d06.png)

Informacje o instalacji i konfiguracji systemu
--
[code]   GLPI 9.3.1 (/glpi => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux ehd1 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 PHP 7.2.10-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_dblib, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, sqlsrv, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="32M" safe_mode="" session.save_handler="files" 	upload_max_filesize="32M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at helpdesk.euroviapolska.local Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0 Server Software: (Ubuntu) 	Server Version: 5.7.24-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	  Deprecated:  __autoload() is deprecated, use spl_autoload_register() instead in /usr/share/php/CAS/Autoload.php on line 99 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (5.7.24) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) SimplePie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.17 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) phpCas version 1.3.3 in (/usr/share/php)

Server: '172.27.19.50', Port: '389', BaseDN: 'DC=euroviapolska,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=Helpdesk,OU=USLUGI,OU=_UZYTKOWNICY_SPECJALNI,DC=euroviapolska,DC=local', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@smtp-app.intranet.eurovia.com)

Name: 'zamowieniait@***' Active: Yes 	Server: '{imap4.***/imap/novalidate-cert/notls}zamowienia' Login: '***' Password: Yes Name: 'pomocit@***' Active: Yes 	Server: '{imap4.***/imap/novalidate-cert/notls/debug}' Login: '***' Password: Yes Name: 'bcc@***' Active: Yes 	Server: '{imap4.***/imap/novalidate-cert/notls}bcc' Login: '***' Password: Yes

dashboard            Name: Dashboard                      Version: 0.9.2      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.5.4      State: Enabled

Host: localhostConnection: OkUse the OCSNG software dictionary: No
[/code]

**Comment by cedric-anne** [comment]
See #4623.
