### ISSUE TITLE
cant login to glpi 9.3 an

### ISSUE THREAD

**Issue by moalkaabi** [glpi-project/glpi#4846]
Hi ,
I'm facing an issue with GLPI LDAP , the user is not able to login with LDAP credential , it was working fine , I have not changed anything .

but it seems that the linux system updated the php version , and I'm not able to find where is the root cause .
this is my php info
![image](https://user-images.githubusercontent.com/8044942/47696646-27872580-dc21-11e8-93bf-bf31adb3bfc3.png)

and this is what I got from the php errors log 
[2018-10-30 09:01:08] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): ldap_bind(): Unable to bind to server: Can't contact LDAP server
  Backtrace :
  :                                                  
  inc/authldap.class.php:2527                        ldap_bind()
  inc/authldap.class.php:2496                        AuthLDAP::connectToServer()
  inc/authldap.class.php:1720                        AuthLDAP->connect()
  scripts/ldap_mass_sync.php:153                     AuthLDAP::getAllUsers()
  scripts/ldap_mass_sync.php:114                     import()
  {"":"@","mem_usage":"127.221\", 6.10Mio)"} 

please support .

**Comment by AnaelMobilia** [comment]
Hello @moalkaabi 
As sayed in the error message, it appears that PHP can't contact your LDAP server.
Could you, please, check if the configuration of your LDAP server in GLPI is OK ?
Check if you can contact this LDAP server ?

Regards,
Anael

**Comment by moalkaabi** [comment]
Hi Aneal,
The configuration of ldap is correct.
How i can check if i can connect to ldap server?

I have already test environment in NAS server and its working fine however the production environment have the issue which is linux OS

.
So how i can check the ldap config in php?


Sent from my iPhone

On Oct 30, 2018, at 5:09 PM, Anael Mobilia <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @moalkaabi<https://github.com/moalkaabi>
As sayed in the error message, it appears that PHP can't contact your LDAP server.
Could you, please, check if the configuration of your LDAP server in GLPI is OK ?
Check if you can contact this LDAP server ?

Regards,
Anael

**Comment by cedric-anne** [comment]
Hi,

As error message is `Can't contact LDAP server`, it seems that your problem is related to a configuration issue.
You can use [forum](https://forum.glpi-project.org/) to get community support or you can get profesionnal support on [GLPI Network Support](https://glpi-project.org/subscriptions/).

Regards
