### ISSUE TITLE
[9.3.2] Long loading dropdown fileds

### ISSUE THREAD

**Issue by pxlcore** [glpi-project/glpi#4847]
Hi,

I've upgraded from 9.3.1 to 9.3.2.

Now the dropdown fields are realy slow. It takes seconds before data is loaded or buttons appear.

Screenrecordings as gif image:

* [dropdown list in new ticket](https://drive.google.com/file/d/10uvwP8zPPXZApeEwG970fSxliImrkumh/view?usp=sharing)
* [loading the transferlist action -> button appears after seconds](https://drive.google.com/open?id=17MAXPeZEnJeZKnW6bPLQBlkMUzK5KX4E)

With verion 9.3.1 all dropdowns came up really quick.

**Comment by trasher** [comment]
Maybe related to https://github.com/glpi-project/glpi/pull/4845; plese test proposed fix

**Comment by magaiverpr** [comment]
Same problem with 9.3.3.

**Comment by TT2N9** [comment]
The dropdown are ever long to load in 9.3.3
