### ISSUE TITLE
item connected to a computer

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4850]
https://forum.glpi-project.org/viewtopic.php?id=165841

right to read computer
right to update monitor

I open a computer with monitor connected. In massive action i choose disconnect..
I have a message for successful action but the monitor is still present in connected items of the computer. A lock is put on the monitor.

I delete the lock.
Go on the monitor and disconnect the computer.
The monitor disappears from connected items list.

I go back to the computer form and the monitor is still present.
In database, relation is still present with is_deleted set to 1

In 9.2, you had error message on disconnect from both item (computer or monitor) and no lock was added.

**Comment by squale323** [comment]
just for information, bug is still present in 9.3.2

**Comment by yllen** [comment]
Yes i confirm.
Normally you must have update right on one object and read right to the other to update a link between two object. In 9.2 the was already an issue.

**Comment by squale323** [comment]
does someone have a temporary fix for this bug please ? since 3 mounth we moved a lot of stuff and it's now a big mess between computers/monitors/printers that were connected/disconnected etc...

**Comment by MonsieurTwinkies** [comment]
Same problem

**Comment by yllen** [comment]
Another post for this problem: https://forum.glpi-project.org/viewtopic.php?id=167044
