### ISSUE TITLE
Can't change private bookmark

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4853]
https://forum.glpi-project.org/viewtopic.php?id=165872

Private bookmarks can be load but i can't update it (to set public by example). They are not all in search result, just if the bookmark is set as default

**Comment by yllen** [comment]
https://forum.glpi-project.org/viewtopic.php?id=167262

**Comment by tola42** [comment]
Hi,

We have the same problem on GLPI 10.0.17.

Some profils can't set  default on private search and/or can't delete private search, no button on GUI.

Thanks

**Comment by cedric-anne** [comment]
> Hi,
> 
> We have the same problem on GLPI 10.0.17.
> 
> Some profils can't set default on private search and/or can't delete private search, no button on GUI.
> 
> Thanks

Please open a new issue and provide all requested information. Also, please try with the latest GLPI version (10.0.18).
