### ISSUE TITLE
[9.1.6] Sometimes the Rule don't affect the ticket

### ISSUE THREAD

**Issue by augustoferronato** [glpi-project/glpi#4854]
* Steps to reproduce (which actions have you made) :
**GLPI 9.1.6**

Strange rule affection

Have 685 items on criteria, and the action is attribute to a tech group
The operator is "or"and the use rule for is: "Add".

When you go to "test engine" the rule works fine. This behavior does not always happen, for it has no way to properly describe how to reproduce it.

* Expected result :
He assign the correct group

* Actual result :
Sometimes, the GLPI don't assign to group, and don't generate any history

* Screenshot of the problem (if pertinent) :

![error_portuguese_ticketrule](https://user-images.githubusercontent.com/13663686/47760701-60141700-dc94-11e8-9135-c80b11871941.png)

![not_assign](https://user-images.githubusercontent.com/13663686/47760704-6609f800-dc94-11e8-9ba7-05799195fc23.png)

* Your GLPI setup (you can find it in Setup > General menu, System tab) :

```
Operating system: Linux server 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64
PHP 5.6.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring,
	mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="180" memory_limit="3000M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="4M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.31 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Server Software: Percona XtraDB Cluster (GPL), Release rel17, Revision c10027a, WSREP version 29.22, wsrep_29.22
	Server Version: 5.7.19-17-57-log
	Server SQL Mode: 
```

**Comment by trasher** [comment]
Please try with last version if the bug still exists.

**Comment by augustoferronato** [comment]
The problem is, we are in a big environment, is not so simply update, I go to duplicate the environment and test, then back with a feedback.

Thanks.

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
