### ISSUE TITLE
To the author of the ticket, personal satisfaction surveys appear

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#4855]
Is it possible or is there some parameter so that they are not "shown" as pending surveys to qualify, surveys in which I am only the author (non-applicant)? In personal view

For example: When approving a form (plugin formcreator) the ticket author is the validator of the form and the ticket applicant is the applicant of the form. However, the validator appears as a pending survey to qualify in his "inbox". Could it only appear to the applicant?

Excuses for the translation is accurate.

I await your comments or suggestions.
ticket ID 752742
![imagen](https://user-images.githubusercontent.com/16838689/47821517-f3018f80-dd2e-11e8-8a88-cb66e8dbd96a.png)

![imagen](https://user-images.githubusercontent.com/16838689/48629672-44915780-e988-11e8-9755-2690136592ca.png)

**Comment by yllen** [comment]
The requester or a member of requester group of a ticket can reply to satisfaction survey.
The author can also reply if he as right in his profile.

In personal view is display the requester of the ticket.

**Comment by virginiacorrea** [comment]
Ok, fine.

But the default query for pending surveys is for author ...

Example: From the previous case in the user's tray lady (author of the ticket 752742) the survey appears (this is ok).
![imagen](https://user-images.githubusercontent.com/16838689/48629883-cd0ff800-e988-11e8-9523-6f510125b073.png)

A Virginia T. (applicant ticket 752742) also appears at the beginning (this is ok), but when clicking, the query is for the author (not the applicant).

![imagen](https://user-images.githubusercontent.com/16838689/48630454-5411a000-e98a-11e8-8e45-780d587b02fb.png)

![imagen](https://user-images.githubusercontent.com/16838689/48630745-f9c50f00-e98a-11e8-9f78-68123fd92162.png)

For this reason, being an applicant, Virginia T. appears at zero.

It is clear that the solution would be in the filter or query to select "requester", instead of author, but for some users this is "complex".

Anyway, thank you very much for the attention. :)

It's a problem of mine. Since the ticket comes from a form (plugin formcreator) the validators of the form (authors finally of the ticket) do not wish to have pending surveys, because although they remain as authors they are not finally the one requesting the service so they do not know how it was provided. service.

Thank you very much for your valuable comments.
