### ISSUE TITLE
[9.3.2]Followup By email sends the Header "=_=_=_="

### ISSUE THREAD

**Issue by jonatangobbato** [glpi-project/glpi#4864]
**Describe the bug**

After update glpi to 9.3.2 the string in the end of the email notification in pt_BR language are inserted on the followup.

![image](https://user-images.githubusercontent.com/29125329/48100198-60b72b00-e209-11e8-8421-47761c7b977f.png)

I think that the error its with the "'=_=_=_='" inserted before the string.
When i replace the "'=_=_=_='" manually on the emai repply to "=-=-=-=" works fine.

**To reproduce**

Answer a followup by e-mail with the PT_BR language.

[code]
 
GLPI 9.3.2 ( => /usr/share/glpi)
Installation mode: RPM

Server
 
Operating system: Linux glpi.biamar.local 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
PHP 7.2.11 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.11 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.2.8-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
Database version seems correct (10.2.8) - Perfect!Database version seems correct (10.2.8) - Perfect!
OK/var/log/glpi : OK
OK/etc/glpi : OK
OK/var/lib/glpi/files : OK
OK/var/lib/glpi/files/_dumps : OK
OK/var/lib/glpi/files/_sessions : OK
OK/var/lib/glpi/files/_cron : OK
OK/var/lib/glpi/files/_graphs : OK
OK/var/lib/glpi/files/_lock : OK
OK/var/lib/glpi/files/_plugins : OK
OK/var/lib/glpi/files/_tmp : OK
OK/var/lib/glpi/files/_cache : OK
OK/var/lib/glpi/files/_rss : OK
OK/var/lib/glpi/files/_uploads : OK
OK/var/lib/glpi/files/_pictures : OK
OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.2.4 in (/usr/share/php/htmLawed)
SimplePie version 1.5.2 in (/usr/share/php/php-simplepie)
TCPDF version 6.2.26 in (/usr/share/php/tcpdf)
michelf/php-markdown in (/usr/share/php/Michelf)
true/punycode in (/usr/share/php/TrueBV)
iacaml/autolink in (/usr/share/php/php-iamcal-lib-autolink)
sabre/vobject in (/usr/share/php/Sabre/VObject4)
phpCas version 1.3.6 in (/usr/share/pear)

LDAP directories
 
Server: 'biamar.local', Port: '389', BaseDN: 'dc=biamar,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person))', RootDN: 'biamar\administrator', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP+TLS (jonatan@biamar.com.br@smtp.office365.com)

Mails receivers
 
Name: 'suporte@biamar.com.br' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl/novalidate-cert/notls}' Login: 'jonatan@biamar.com.br\suporte' Password: Yes

Plugins list
 
	fusioninventory      Name: FusionInventory                Version: 9.3+1.2    State: Enabled

[/code]

**Comment by cedric-anne** [comment]
Hi,

This should fix your problem https://github.com/glpi-project/glpi/pull/4885.

Regards

**Comment by jonatangobbato** [comment]
Thats work for me.
Thank you very much.

 Is there a way to remove also the header above? "
From: Suporte - Biamar Malhas <suporte@-----.com.br> 
Sent in: segunda-feira, 12 de novembro de 2018 16:57
To: Jonatan Gobbato - Biamar Malhas <jonatan@-----.com.br>
Assunto: [GLPI #0000304] Novo acompanhamento - Teste"
?

**Comment by cedric-anne** [comment]
Hi,

Thoose lines format, order and presence depends on the web client you use. It is not impossible to do, but cleaning it would require a lot of work. So it is not something we would done, unless someone opens a PR that handles this cleaning correctly and without any risk of stripping something else than the original message.

Regards

**Comment by rjmontenegro** [comment]
> Hi,
> 
> Thoose lines format, order and presence depends on the web client you use. It is not impossible to do, but cleaning it would require a lot of work. So it is not something we would done, unless someone opens a PR that handles this cleaning correctly and without any risk of stripping something else than the original message.
> 
> Regards

Hello @cedric-anne .
The same thing happens to me as well as @jonatangobbato. I would like to remove this information from notifications. Can you help with that?

**Comment by cedric-anne** [comment]
Hi,

As said in my previous comment, as it depends on used client, cleaning correctly the received email is not so easy. I would personally not try to develop this kind of cleaning logic as I do not have time to do it.

Related piece of code is here https://github.com/glpi-project/glpi/blob/f487cf34496fb8ad7b94214944253e233f175d93/src/MailCollector.php#L1152-L1181

**Comment by rjmontenegro** [comment]
of course I understand.  normally all customers put this information but it varies from customer to customer and not to mention the languages.

Ricardo Montenegro
________________________________
