### ISSUE TITLE
Log rotation doesn't seem to delete the logs in glpi/file/_log folder

### ISSUE THREAD

**Issue by Mexonizator** [glpi-project/glpi#4872]
Hello!

GLPI: 9.3.2
Fusion Inventory: 9.3+1.2

So. Noticed that the logs in said folder take awfully much space. I enabled log rotation in the GLPI general settings and in the Fusion Inventory ones as well. Then started the log task in Automatic actions.

It ran smoothly. The database shrank twice in size. But, all the files remained in the folder and I had to delete them manually. 

Is it a bug or a feature? As I expected the log rotation to clean the folder up too.

Thanks.

**Comment by orthagh** [comment]
some precisions, we have two logs cleaning actions in GLPI.

- Clean of **glpi_logs table in database** (Confer the Setup > General you mentionned)
- Circular logs regarding logs **files**, see the automatic action (in Setup menu) named "circularlogs"

**Comment by Mexonizator** [comment]
Oh, thanks. Didn't know about it.

**Comment by tguichard25** [comment]
`[2020-06-15 08:45:27] glpiphplog.ERROR: Toolbox::callCurl() in C:\glpi_lab\inc\toolbox.class.php line 1714
Échec de connexion. Si vous utilisez un proxy, merci de le configurer. (SSL certificate problem: self signed certificate in certificate chain)  {"user":"6@SRV-PARC01"} 
[2020-06-15 08:52:57] glpiphplog.ERROR:   *** PHP User Error (256): Trying to load a forbidden class name "0" in C:\glpi_lab\inc\autoload.function.php at line 266
  Backtrace :
  inc\autoload.function.php:266                      trigger_error()
  :                                                  glpi_autoload()
  :                                                  spl_autoload_call()
  plugins\formcreator\ajax\commontree.php:45         is_a()`
