### ISSUE TITLE
racks_plugin.php error

### ISSUE THREAD

**Issue by sdvroot** [glpi-project/glpi#4879]
Migrate GLPI from 9.2.2 version to 9.3.2, and the racks_plugin.php not working, please help to resolve issue.

Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined offset: 0
  Backtrace :
  scripts/migrations/racks_plugin.php:267            
  scripts/migrations/racks_plugin.php:43             migratePlugin()
 Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined offset: 1
  Backtrace :
  scripts/migrations/racks_plugin.php:268            
  scripts/migrations/racks_plugin.php:43             migratePlugin()
 PHP Fatal error:  Class '' not found in /var/www/glpi/scripts/migrations/racks_plugin.php on line 274

**Comment by trasher** [comment]
@sdvroot could you please test proposed fix? Thank you.

**Comment by koopa3822** [comment]
Hi @trasher, it must be a fortune to find this portal and find you.

In the company for which I work we are implementing GLPI.

when we try to synchronize the users of the active directory (we have successful test of the ldap configuration) it tells us that there are no users.

The error that shows us our linux (fedora core server) is the following:

glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
  *** PHP Warning(2): ldap_search(): Search: Operations error
  Backtrace :
  :
  inc/authldap.class.php:1604                        ldap_search()
  inc/authldap.class.php:1750                        AuthLDAP::searchForUsers()
  inc/authldap.class.php:3769                        AuthLDAP::getAllUsers()
  inc/authldap.class.php:1454                        AuthLDAP::getUsers()
  inc/authldap.class.php:3332                        AuthLDAP::showLdapUsers()
  front/ldap.import.php:66                           AuthLDAP::searchUser()
  {"user":"2@mesadeayuda.inexmoda.org.co"}

I tried to do everything and I searched a lot in forums but I have not been successful, you could help me a little in guiding me to a solution I would greatly appreciate your help.
