### ISSUE TITLE
Error trying update glpi 9.1 to 9.3

### ISSUE THREAD

**Issue by jmurilloariza** [glpi-project/glpi#4880]
Hi I have a problem when updating GLPI, I currently have version 9.1 and I want to update to 9.3 but I see the following error screen and I can not find how to solve it.

![image](https://user-images.githubusercontent.com/23342870/48227852-86f7da80-e371-11e8-91a5-801c1cc36449.png)

However, version 9.1 still works when I try to access the backup I made before starting the update.

**Comment by cedric-anne** [comment]
Hi,

Sorry for the late.

I have not investigate on this, but you should be able to update to GLPI 9.3.3 using the `script/cliinstall.php` from a shell.

Regards

**Comment by cedric-anne** [comment]
> I have not investigate on this, but you should be able to update to GLPI 9.3.3 using the `script/cliinstall.php` from a shell.

I miss this point, but you should not use the install process to update.

1. Backup files and database.
2. Get the new version archive and install it.
3. Copy the `config/config_db.php` file from previous version.
4. Open GLPI in your browser.

You should be redirected to the `install/update.php` page.

You can also use the `scripts/cliupdate.php` from a shell.

**Comment by trasher** [comment]
See install doc for upgrade instructions: https://glpi-install.readthedocs.io/en/latest/update.html
