### ISSUE TITLE
Mail collector: emails refused

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4889]
https://forum.glpi-project.org/viewtopic.php?id=166074

**Comment by cedric-anne** [comment]
Hi,

In GLPI 9.3.2, we added checks on user rights in mail collector. Basically, the email will be refused if user cannot make the same action on UI.

Regards

**Comment by cedric-anne** [comment]
Changes were made to prevent users to do a forbidden action.
For example, any user were able to add followups on any ticket, even without any followup rights.

You are talking about test you have done. On which version have you done them ? What are the result of your tests ?

**Comment by yllen** [comment]
Tests done on 9.3.2svn
Results of my test correspond to what is expected
- no right to create anonymous ticket in global config => ticket not created
- no right to create anonymous followup in global config => followup not created
- right to create anonymous ticket or followup => ticket or followup was created if mail sent with an unknown email address
....

**Comment by cedric-anne** [comment]
Hi @yllen,

What was done in 9.3.2 was intentional. Indeed, I considered that the fact that a user does not have rights on the interface should result in the refusal of his email.
Since this choice is not understood by the users and does not reflect our expectations, we have chosen to review what has been done.
We continue to add rights checking on user profiles, but only if the corresponding `Allow anonymous ...` option is not enabled.

PR #4904 should fix this (in replacement of #4890 which reverts too many changes). I will make some tests on my side. Could you also test on your side ?

Regards

**Comment by cedric-anne** [comment]
I tested following cases, result is what I expected:

- create a ticket without creation rights but with 'anonymous creation' enabled : accepted
- create a ticket without creation rights and with 'anonymous creation' disabled : rejected
- create a ticket with creation rights and with 'anonymous creation' enabled : accepted
- create a ticket with creation rights and with 'anonymous creation' disabled : accepted

- create a followup on my ticket without 'add on my' rights but with 'anonymous followup' enabled : accepted
- create a followup on my ticket without 'add on my' rights and with 'anonymous followup' disabled : rejected
- create a followup on my ticket with 'add on my' rights and with 'anonymous followup' enabled : accepted
- create a followup on my ticket with 'add on my' rights and with 'anonymous followup' disabled : accepted

- create a followup on a ticket from another requester without 'add on all' rights but with 'anonymous followup' enabled : accepted
- create a followup on a ticket from another requester without 'add on all' rights and with 'anonymous followup' disabled : rejected
- create a followup on a ticket from another requester with 'add on all' rights and with 'anonymous followup' enabled : accepted
- create a followup on a ticket from another requester with 'add on all' rights and with 'anonymous followup' disabled : accepted

**Comment by cedric-anne** [comment]
See also #4856 .

**Comment by trasher** [comment]
ping?

Without any feedback from users =, we will integrate the proposed patch since it seems to solve the issues.

**Comment by pedroluisvsousa** [comment]
> I tested following cases, result is what I expected:
> 
>     * create a ticket without creation rights but with 'anonymous creation' enabled : accepted
> 
>     * create a ticket without creation rights and with 'anonymous creation' disabled : rejected
> 
>     * create a ticket with creation rights and with 'anonymous creation' enabled : accepted
> 
>     * create a ticket with creation rights and with 'anonymous creation' disabled : accepted
> 
>     * create a followup on my ticket without 'add on my' rights but with 'anonymous followup' enabled : accepted
> 
>     * create a followup on my ticket without 'add on my' rights and with 'anonymous followup' disabled : rejected
> 
>     * create a followup on my ticket with 'add on my' rights and with 'anonymous followup' enabled : accepted
> 
>     * create a followup on my ticket with 'add on my' rights and with 'anonymous followup' disabled : accepted
> 
>     * create a followup on a ticket from another requester without 'add on all' rights but with 'anonymous followup' enabled : accepted
> 
>     * create a followup on a ticket from another requester without 'add on all' rights and with 'anonymous followup' disabled : rejected
> 
>     * create a followup on a ticket from another requester with 'add on all' rights and with 'anonymous followup' enabled : accepted
> 
>     * create a followup on a ticket from another requester with 'add on all' rights and with 'anonymous followup' disabled : accepted

I liked this approach. Great!
