### ISSUE TITLE
Mailqueue

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4891]
Why new ticket goes in mailqueue?
Mailqueue was created for sending many notification as same object for a same user once.
A ticket creation can't be group with another ticket creation.

For creation of an object, notification is send immediately, even if you have no notification for my changes in my settings, because it's the proof of creation.

I don't check for other object creation (change, problem...)

**Comment by yllen** [comment]
I'm not agree with you: notification was send immediately at the ticket creation to avoid this: https://forum.glpi-project.org/viewtopic.php?id=166127

I done this change in the past

**Comment by trasher** [comment]
Well, I do not know then. This needs more investigations

**Comment by DrasticSolutions** [comment]
I also have an issue with **Home > Administration > Notification queue**
Messages stay a lot of time (hours/days) in "Notification queue" randomly and don't get sent in email.

In **Home > Setup > Automatic Actions > queuednotification**
Run Frequency: 1 minute ; Scheduled ; Run Mode: CLI
(what is the difference between CLI and GLPI ?)

In **Home > Setup > Automatic Actions > queuednotificationclean**
Run Frequency: Each Day ; Scheduled ; Run Mode: GLPI

Which of these two (**queuednotification / queuednotificationclean**) actually sends the mail ?

GLPI Server Info
```
GLPI 9.4.5 ; PHP 7.4.1 - all extensions installed ; Database 5.7.28 - Perfect!
Installation mode: TARBALL
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" upload_max_filesize="2M"
Notifications = Way of sending emails: PHP
Plugins list = Name: FusionInventory Version: 9.4+2.3    State: Enabled ; GLPI cron not running
```

And can anyone explain how **Notification queue** feature work ? or point to the right documentation.
Where can I see the logs ? How often GLPI looks in queue and after that when it sends the notification ?
