### ISSUE TITLE
Not imported email

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4892]
In this list, i have a refused email.
My refused emails are in a specific directory.
Bu in not imported emails, i have massive action to import it. But it can't be because it was not in directory reading by the collector.

So if you try to import, you have an information message: Operation Successful
and a red error message: Email dda253d6-63a2-c2df-d6de-c1c2a7c5e5e1@toto.com not found. Impossible Import.

**Comment by cedric-anne** [comment]
@yllen ,

Could you please test the fix proposed in #4906 ?

Regards

**Comment by cedric-anne** [comment]
Note that the "not imported" table is truncated every time the collector start its process, so I am pretty sure that most of the time (i.e. when collector is launch by cron using a short interval), refused mails would be lost before anyone would be able to force their import.

Also not that this import function does not take care of any rule/rights.
