### ISSUE TITLE
«0.90.1» Impossible to view Change or Problem if "Assigner" 

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#491]
Hello, 
 if a user is is only an assigner of a Change, he does not see the change.
He cannot neither access with the direct link to the change.
The only way is to give permissions for change as "See all
I guess that ä solution could be to add of the column "See Assigned" in Administration-Profiles-<profile>-assistance-change  (and maybe Problems) and manage this authorization.

davide

**Comment by yllen** [comment]
If the user has right See(my) and he is assign to the change, he can see it.
See(my) is for a change that user is 
- requester or member of the requester group
- observer or member of the observer group
- assigned or member of the assigned group

**Comment by Giudy** [comment]
I did some test on a brand new installation with no plugins and an empty DB and I couldn't see the Changes with a profile with no permissions on SEE ALL CHANGES if the changes where assigned to a user.

**Comment by yllen** [comment]
You must be the requester, observer or be assigned to the change to see it.
Your can't see changes of other persons.

**Comment by Giudy** [comment]
Yllen, that's is what I was assuming. Unfortunately I cannot make i tworking nor in the production and neither in test environment. The test environment is a brand new installation with no data in it.
I did a screencast of what I mean:
https://mega.nz/#!yxZAwQRR!dpAkij44LXYuFKfirjy9KWCzq96DLi0Qt_LB34Y2ceY
as you can see the user tech has created a change assigning it to the glpi user.
The glpi user can see it if super admin but not with a profile (in this case I have modified the standard Supervisor profile) with no permission on SEE ALL CHANGES.
the version I'm using is the 0.90.1. 
In production it is on a windows (XAMPP) stack but in test is on Cntos/Apache/mysql
