### ISSUE TITLE
[GLPI 9.3.2] Dropdown translation - Only one translation can be added

### ISSUE THREAD

**Issue by makev70** [glpi-project/glpi#4912]
When adding dropdown translations only one translation can added. No matter what dropdown you trying to translate.

Example:
1. Select Ticket categories -> Translations -> Add a new translation -> Select 'Language' -> Select field 'Name' -> Add value -> Press Add
2. Add a new translation -> Select another 'Language' -> 'Name' field in dropdown is gone
3. Add a new translation -> Select 'Language' -> Select field 'Comments' -> Add value -> Press Add
4. Add a new translation -> Select another 'Language' -> 'Comments' field in dropdown is gone

![image](https://user-images.githubusercontent.com/44969954/48459090-ad829f00-e7d1-11e8-8aff-5036589ea4a9.png)

We have upgraded from version 9.1.6 to 9.3.2. We have working translations from that earlier version.

GLPI 9.3.2
Linux 4.9.0-8-amd64 Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64, MySQL Community Server Version 8.0.13, PHP 7.0.30-0+deb9u1, Apache/2.4.25 (Debian)

**Comment by trasher** [comment]
Please check logs

**Comment by yllen** [comment]
@trasher no error in log
If fields translated it's not avalaible for other language

**Comment by trasher** [comment]
@yllen ok, thanks for the feeback :)
