### ISSUE TITLE
Mailgate not updating "Last Edit By" in 9.3.2

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#4924]
GLPI v9.3.2

Hello,

Since upgrading from 9.3.1, when mail is collected via the mailgate, the relevant ticket isn't having it's "last edit by" updated accordingly.

For instance, if our ticket 123456 is last edited by "Joe Bloggs at 10:15", and the mailgaite imports a follow-up to the ticket at 12:42 from "Jane Doe" (the original requester), the ticket is updated with the new content, but its last 'edit by' is "Joe Bloggs at 12:42".

Can't see any errors in our Apache error log when this happening.

Can anyone else replicate, or is this something peculiar to our own setup?

Thanks

**Comment by Corrano** [comment]
Hello, 
I also have this problem after upgrade to 9.3.2.
When someone add new followup and someone else answer by email, everything works fine except "Last edit by" in global tickets view. 

"Last edit by" still presents person which create first followup and We can't see that someone else write something new. We must open ticket and look is there something new. If you have many tickets it's very possible that you miss new followup

**Comment by mauriciolamego** [comment]
Hello, I also share the problem and is really missing the fix, can impact on critical service. We thank you for the attention you have always had for the community and staff.

**Comment by hgpit** [comment]
Comforting to know that it's not just something odd with our own setup then!

I hope a dev can replicate and create a fix soon. It's also causing us a lot of issues.

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by mauriciolamego** [comment]
Good morning, you're suggesting that we download the master.tar.gz repository and replace (overwriting) the production application?

**Comment by trasher** [comment]
1- not master, no.
2- certainly not on a **production** env...
3- I did not understand.

**Comment by mauriciolamego** [comment]
Good afternoon, I'm already using the most current version of GLPI 9.3.2, where the reported problem occurs.

**Comment by cedric-anne** [comment]
@hgpit @Corrano @mauriciolamego 

Could you test the fixed provided in #4969 ? We would prefer having a feedback on the fix before merging it.

Regards
