### ISSUE TITLE
Problem with checkboxes containing quotes

### ISSUE THREAD

**Issue by Synairgis** [glpi-project/glpi#4928]
**Describe the bug**

Given that GLPI does not have many checkboxes natively, I recommend using the formcreator plugin to reproduce it. Basically, if you create a checkbox containing the value "L'école" (or any values that contains a quote for that matters), the generated HTML will end up garbled.

**To reproduce**

1. Create a new form using the formcreator plugin
2. Add a checkbox question with value "L'école"
3. Save and visualize the form
4. Inspect the underlying HTML of the element and you'll notice that both the title and value attributes are messed up. Here's what I had personally:

`<input type="checkbox" class="new_checkbox" id="formcreator_field_1233_3" name="formcreator_field_1233[]" title="L" école'="" value="L">`

**Expected behavior**

I would basically expect the HTML to be correctly rendered, namely having the following being generated:

`<input type="checkbox" class="new_checkbox" id="formcreator_field_1233_3" name="formcreator_field_1233[]" title="L'école" value="L'école">`

**Additional context**

As I said at the beginning, I noticed the problem using the formcreator plugin, but after hours of digging, I was able to trace the problem to the `html.class.php` file, which makes it a GLPI bug. The problem lies in the `getCheckbox()` method. Near the start, there's the following loop:

```
foreach (['id', 'name', 'title', 'value'] as $field) {
	if (!empty($params[$field])) {
		$out .= " $field='".$params[$field]."'";
	}
}
```
The problem here is that if `$params[$field]` contains a quote, it completely messes up the resulting string. I was able to solve this problem by encoding `$params[$field]` using the `htmlentities()` function as follows:

```
foreach (['id', 'name', 'title', 'value'] as $field) {
	if (!empty($params[$field])) {
		$out .= " $field='".htmlentities($params[$field], ENT_QUOTES, 'utf-8')."'";
	}
}
```

**Comment by trasher** [comment]
Well... Giving that esacpements are a nightmare in GLPI, I'm not sure this change is correct. Currently, most of GLPI code expect arguments has already been escaped for database and display.

That means if for some reason any argument has not been escaped, it has to be fixed on the call. Trynig to fix on `getCheckbox`, while not incorrect on a tech point of view would cause duplicate escaping issues (I did not find one in the core after a very quick search - but this does not prove anything).
