### ISSUE TITLE
[0.90svn] timeline - hide document tab is timeline and don't keep tabs

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#493]
Avec timeline d'activée, lorsque je demande à conserver les onglets, l'onglet Suivi n'apparait pas.
Je précise que le problème n'est pas présent en 0.91.

De plus, je me pose une question : vu que timeline fait Suivi, Tâche, Document et Solution
l'onglet Document ne devrait-il pas être masqué si je ne veux pas conserver les onglets ?

**Comment by tomolimo** [comment]
Hello Yllen,
I agree with you: it must be hidden when 'Enable ticket timeline' is set to 'Yes' and 'Keeps tabs replaced by the ticket timeline' is set to 'No'.
Regards
Tomolimo

**Comment by ladenree76000** [comment]
[0.90.1] When selecting Timeline=Yes, keep tabs=Yes, I can see "Followups Tab" and its content. and timeline. (FF : ok & IE :ok)

+1 for hide document TAB when hide followups/tasks/solution TABS

**Comment by yllen** [comment]
Thanks for test ladenree76000.
It was a problem with my profile (deactivate read followup for another test).
