### ISSUE TITLE
Problem when using the drag and drop attaching documents in the ticket

### ISSUE THREAD

**Issue by tacianomittmann** [glpi-project/glpi#494]
I use the 0.90.1 version of GLPI .
The ticket screen, the item documents have problems using the drag and drop , works only with a document. While trying to attach two or more documents appear on only one ticket interface.
Anyone ever had this problem and know how to solve ? It's a bug in this release?
PS :
In a new ticket it works perfectly .
In an existing ticket attach only one document
See the test attachments.
Thank you.

![drag_and_drop_1](https://cloud.githubusercontent.com/assets/17165748/13327295/0353756c-dbc8-11e5-8bd4-141960511636.png)
![drag_and_drop_2](https://cloud.githubusercontent.com/assets/17165748/13327296/0353abf4-dbc8-11e5-80dc-b6663f301bc1.png)
![drag_and_drop_3](https://cloud.githubusercontent.com/assets/17165748/13327376/5cb74c64-dbc8-11e5-896d-999d7f7cf6b3.png)
![drag_and_drop_4](https://cloud.githubusercontent.com/assets/17165748/13327298/03579066-dbc8-11e5-9cac-ff7eea1b90e8.png)
![drag_and_drop_5](https://cloud.githubusercontent.com/assets/17165748/13327299/03666a14-dbc8-11e5-8f14-c63f1732789b.png)
![drag_and_drop_6](https://cloud.githubusercontent.com/assets/17165748/13327300/03763110-dbc8-11e5-85bf-cb1422d1e414.png)
![drag_and_drop_7](https://cloud.githubusercontent.com/assets/17165748/13327301/03770022-dbc8-11e5-835f-d7a5e7162410.png)
![drag_and_drop_8](https://cloud.githubusercontent.com/assets/17165748/13327304/037ed450-dbc8-11e5-9fe6-4ec00b158ff9.png)
![drag_and_drop_9](https://cloud.githubusercontent.com/assets/17165748/13327303/037c6bc0-dbc8-11e5-8cb7-f697ed542e23.png)

Information about system installation and configuration
[code]
 GLPI 0.90.1 (/glpi => /srv/www/htdocs/glpi)

Server
 Operating system: Linux linux-iqe8 4.1.12-1-default #1 SMP PREEMPT Thu Oct 29 06:43:42 UTC 2015 (e24bad1) x86_64
PHP 5.5.14 apache2handler (Core, PDO, Reflection, SPL, SimpleXML, apache2handler, bz2, ctype, date, dom, ereg, fileinfo, filter,
	gd, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, session, sqlite3, standard, tokenizer, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache ()
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36
Server Software: openSUSE package
	Server Version: 10.0.21-MariaDB
	Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/chamados
	Host info: Localhost via UNIX socket
	
OK/srv/www/htdocs/glpi/config : OK
OK/srv/www/htdocs/glpi/files : OK
OK/srv/www/htdocs/glpi/files/_dumps : OK
OK/srv/www/htdocs/glpi/files/_sessions : OK
OK/srv/www/htdocs/glpi/files/_cron : OK
OK/srv/www/htdocs/glpi/files/_graphs : OK
OK/srv/www/htdocs/glpi/files/_lock : OK
OK/srv/www/htdocs/glpi/files/_plugins : OK
OK/srv/www/htdocs/glpi/files/_tmp : OK
OK/srv/www/htdocs/glpi/files/_rss : OK
OK/srv/www/htdocs/glpi/files/_uploads : OK
OK/srv/www/htdocs/glpi/files/_pictures : OK
OK/srv/www/htdocs/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.

Libraries
htmLawed version 1.1.20 in (/srv/www/htdocs/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/srv/www/htdocs/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/srv/www/htdocs/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/srv/www/htdocs/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/srv/www/htdocs/glpi/lib/Zend)
SimplePie version 1.3.1 in (/srv/www/htdocs/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/srv/www/htdocs/glpi/lib/tcpdf)
ircmaxell/password-compat in (/srv/www/htdocs/glpi/lib/password_compat). Compatitility: Ok

Plugins list
dashboard            Name: Painel                         Version: 0.7.1      State: Enabled

**Comment by tomolimo** [comment]
Hello 
What browser do you use? 
Do you have SSO?
Architecture of the infrastructure?  Windows AD?

**Comment by tacianomittmann** [comment]
I used Google Chrome, Mozilla Firefox.
We do not use SSO for access to GLPI.
To make users sign in GLPI use the AD Microsoft.

**Comment by tomolimo** [comment]
Could you please detail the user connection with GLPi?

**Comment by tacianomittmann** [comment]
Authentication	LDAP directory: Name - SC
Last synchronization on 25-02-2016 16:56
User DN: CN=Taciano Mittmann,OU=Tecnico,OU=INFORMATICA,OU=SR,OU=Padrao,OU=Usuarios,OU=SC,DC=intranet


Entities	         Profiles (D=Dynamic, R=Recursive)
 
Entidade raiz	 Super-Admin (R)
![user](https://cloud.githubusercontent.com/assets/17165748/13328857/cd6c69ce-dbcf-11e5-8960-a0d2a21b5600.png)

**Comment by tomolimo** [comment]
Hello,
Could you send Fiddler traces?
Thank you,
regards,
Tomolimo

**Comment by tacianomittmann** [comment]
Hello,
Could you enlighten me what you really have to do to send you this?
I did not understand what you want .

**Comment by tomolimo** [comment]
To help you to narrow the problem I need to have network trace between your browser and your GLPI server.
For this, I propose you to install Fiddler on your PC, and then to capture network exchanges (reproducing the problem you mentioned), and then to post these in a zip file.

**Comment by tacianomittmann** [comment]
[Test drag and drp.zip](https://github.com/glpi-project/glpi/files/148271/Test.drag.and.drp.zip)
Hello,
I performed the test with Fiddler
follows the attachment.

**Comment by tomolimo** [comment]
As far as I can see, there is no network problem in the traces.
Did you reproduce the problem during the session?

**Comment by tacianomittmann** [comment]
Yes , I performed the test and the problem occurred again.

**Comment by yllen** [comment]
No problem for me with firefox. I can add many documents in an existing ticket.

**Comment by tacianomittmann** [comment]
Hello,

I performed the test again , this time I recorded the steps , look at the attachment.

[AutoScreenRecorder_05 Feb. 26 15.45.zip](https://github.com/glpi-project/glpi/files/148725/AutoScreenRecorder_05.Feb.26.15.45.zip)

**Comment by tacianomittmann** [comment]
Hello,

Note that the opening of the ticket works perfectly , but when the ticket is open only appends the last document in the list. But the document was sent to the server , because when I attach it again appears the "filename ( 2 ) .txt " .
I recorded another video. See the attachment.

[AutoScreenRecorder_06 Feb. 26 15.51.zip](https://github.com/glpi-project/glpi/files/148742/AutoScreenRecorder_06.Feb.26.15.51.zip)

**Comment by tomolimo** [comment]
Hello,
I've got the same problem!
When trying to add several documents by drag/drop into an existing ticket, then only one is really added.
It occurs on GLPi 0.90.1, but not on 0.91: seems like something has been fixed!
Regards,
Tomolimo

**Comment by tomolimo** [comment]
I made traces for both cases, and I saw that when using 0.90.1 the filename array is malformed in the POST params:

Look into the traces you sent to us: open them with Fiddler, and select the line 40 (/glpi/front/document.form.php POST)

and you'll the following params in the 'TextView' for the POST:

> -----------------------------71101354620970
Content-Disposition: form-data; name="documentcategories_id"

> 0
-----------------------------71101354620970
Content-Disposition: form-data; name="entities_id"

> 0
-----------------------------71101354620970
Content-Disposition: form-data; name="is_recursive"

> 0
-----------------------------71101354620970
Content-Disposition: form-data; name="itemtype"

> Ticket
-----------------------------71101354620970
Content-Disposition: form-data; name="items_id"

> 14343
-----------------------------71101354620970
Content-Disposition: form-data; name="tickets_id"

> 14343
-----------------------------71101354620970
Content-Disposition: form-data; name="filename[]"; filename=""
Content-Type: application/octet-stream


> -----------------------------71101354620970
Content-Disposition: form-data; name="_filename[0]"

> 7.txt
-----------------------------71101354620970
Content-Disposition: form-data; name="_tag_filename[0]"

> 65df2577-4ad760f9-56d0569685f826.77260442
-----------------------------71101354620970
Content-Disposition: form-data; name="_filename[0]"

> 6.txt
-----------------------------71101354620970
Content-Disposition: form-data; name="_tag_filename[0]"

> 65df2577-4ad760f9-56d056969415f4.83550452
-----------------------------71101354620970
Content-Disposition: form-data; name="_filename[0]"

> 4.txt
-----------------------------71101354620970
Content-Disposition: form-data; name="_tag_filename[0]"

> 65df2577-4ad760f9-56d05696a24f84.97266971
-----------------------------71101354620970
Content-Disposition: form-data; name="_filename[0]"

> 5.txt
-----------------------------71101354620970
Content-Disposition: form-data; name="_tag_filename[0]"

> 65df2577-4ad760f9-56d05696da04d8.76009489
-----------------------------71101354620970
Content-Disposition: form-data; name="add"

> Adicionar novo arquivo
-----------------------------71101354620970
Content-Disposition: form-data; name="_glpi_csrf_token"

> 2167bc11de457ee5bd7ff2ea28aa6056
-----------------------------71101354620970--


The filename array should be incremented like [0], and [1], [2] and so on...
As it stays to [0], only one file will be added to the ticket.

**Comment by orthagh** [comment]
On 0.90/bugfixes branches and master, could not replicate issue
Test on 0.90.1, errors is here.

I can't remember changes on document addition recently.
So i suggest you to wait for 0.90.2 who apparently don't have the bug

**Comment by tacianomittmann** [comment]
Thank you for the feedback !

Let's wait for the 0.90.2 version, I thank the team for guidance and commitment.
No provision for release of version 0.90.2 ?

**Comment by orthagh** [comment]
Asap, I'm currently working on backlog

**Comment by orthagh** [comment]
Finally i retrivied the commit who fixed the issue.
There : 
https://github.com/glpi-project/glpi/commit/f091703ab67f11b8523b4f42e7124119910f851c#diff-f6061ea857b63b7935db5eaddac48c64L583

**Comment by tacianomittmann** [comment]
Perfect,
I just tested and it works very well.
Thank you for feedback and improvements in the system. 
It's really a pleasure to use GLPI . 

:-)
