### ISSUE TITLE
Documents unavailable in the web interface for post-only users in their tickets

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#4941]
Hello,

When a new ticket is created and a file is attached during creation, corresponding link is unavailable in the web interface for the post-only user, ticket owner. 
The same issue appears if the document is inserted in a follow-up or when it is imported by collector.

If the file is inserted through the Document tab, there is no issue.  

Following links in ticket emails allows to open the documents. 

Please, see the attached snapshot. The only link available is for the first document in the list.
 
The GLPI version is 9.3.0 

![bug-documents-glpi](https://user-images.githubusercontent.com/10462658/48786719-bbf81b80-ece7-11e8-94ea-5ac403e081bf.png)

**Comment by cedric-anne** [comment]
Hi,

Could you test with #4483 fix ? If it works, then it has been fixed in 9.3.1 version of GLPI.

Regards

**Comment by kabassanov** [comment]
I could (when I find the way to get a diff from github).
But if I'm not wrong it is not only related to users rights. The glpi document instance name seems not to be the same, so I think there is a different treatment depending of the way the document is inserted.

**Comment by kabassanov** [comment]
OK, I applied #4483 fix.

As you can see, there is now a link for documents inserted during ticket creation, but still not for documents from follow-ups, nor from email collector.
![bug-documents-glpi-fix4483](https://user-images.githubusercontent.com/10462658/48793889-ab03d600-ecf8-11e8-9118-a2fde915f576.png)

**Comment by kabassanov** [comment]
Just for confirmation, after 9.3.2 upgrade, behavior remains the same as described in my previous post.

**Comment by cedric-anne** [comment]
Hi,

In GLPI 9.4.0, the document tab is no longer existing. Links in "Traitement du ticket" should be OK.

Regards
