### ISSUE TITLE
BIOS-Date, BIOS-Version not searchable anymore

### ISSUE THREAD

**Issue by juge2** [glpi-project/glpi#4947]
With 9.3.2 it is not possible anymore to search for the BIOS installation date in anymore, which was still possible with 9.1.6 and FusionInventory.

I suppose this changed with the introduction of the BIOS component (https://github.com/glpi-project/glpi/issues/1765)

**Page(s) URL**
front/computer.php

**To reproduce**

1. Go to 'Assets -> Computers'
2. Click on Search Criteria
3. Search 'Firmware' or 'BIOS' or 'Installation Date'
4. Nothing to select

**Expected behavior**
Criteria for BIOS/Firmware are displayed (BIOS Version, Installation Date, Manufacturer etc.)

**Screenshots**

![2018-11-21_selection_003](https://user-images.githubusercontent.com/559489/48829022-86981000-ed71-11e8-9eaa-a0bb99a7e418.jpg)

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/4799

**Comment by buggzbeny** [comment]
Hello,
We need this research too, bios and bios date. Can you add them ?
Regards.
