### ISSUE TITLE
 problem of displaying images in tickets

### ISSUE THREAD

**Issue by KevinStephane** [glpi-project/glpi#4950]
Hello, 

When users send email to open new tickets with a screenshot,  the screenshot is remplaced by a char sequence in the body of ticket.

We have find a stange thing : if we change language "Francais -> English" the screenshoot is displayed, but not for all users. 

GLPI version is 9.3.0

Please excuse my bad english :-)

Thanks

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by KevinStephane** [comment]
ok thanks

**Comment by KevinStephane** [comment]
Can you explain to me what is the difference between Master and version (s)

**Comment by trasher** [comment]
https://glpi-developer-documentation.readthedocs.io/en/master/sourcecode.html#branches

**Comment by trasher** [comment]
Out of the scope of the current ticket. Report to existing ticket on same problem

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by KevinStephane** [comment]
HI, 
After update to 9.3.3 from 9.3 my problem is not solved.
We can see images everywhere when language is english but nowhere where language is french or other
Any idea ?
