### ISSUE TITLE
Datetimepicker manual input

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#4951]
**Describe the bug**

On an existing tickettask, if you want to manually update the date field, it didn't update correctly the minutes (when debug mode is disabled)

**To reproduce**

1. Go to an existing ticket
2. Click on 'Processing ticket'
3. Update an existing tickettask
4. Update the date manually (without using the datetimepicker button)
5. Save the tickettask
6. The minutes are not the one you submited

**Expected behavior**

The date should be the same as the input.

**Logs**

logs in web browser console :
Error parsing the date/time string: Wrong time format
date/time string = 22-11-2018 10
timeFormat = HH:mm
dateFormat = dd-mm-yy

**Screenshots**

I've changed the date manually but not saved it :
![image](https://user-images.githubusercontent.com/39367117/48896611-51122600-ee48-11e8-9d69-0035229ff593.png)

And after saving, you can see the minutes are 03 instead of 37 :
![image](https://user-images.githubusercontent.com/39367117/48896628-5e2f1500-ee48-11e8-83b9-5b54d92b9363.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

i've tested in 9.3.2 and 9.2.2 it's the same.

**Debug**

The probleme seems to be the hiden field '#hiddendate".$p['rand']."' which is not correctly update when the user use the input manually.
For temporary fixing this, 
i've set the datetimepicker option "showOn" to 'both' in html.class.php.

**Comment by nbriche** [comment]
Can confirm that this bug exists in 9.3.3. The workaround also works for us.

**Comment by cedric-anne** [comment]
Hi,

@keha35 , seems that your fix is not just a workaround but the best solution to fix this issue. I made the cahnge on #5597 .

Regards
