### ISSUE TITLE
[GLPI 9.3.2] Disable warning after super-admin login

### ISSUE THREAD

**Issue by marciofoz** [glpi-project/glpi#4954]
Hi!!

I'm using GLPI 9.3.2 and after migrating all database/tables to InnoDB and upgrade all plugins, I still with one table in MyIsam engine.  This table comes from a plugin, but I need use temporarily in this way.  How I can disable this warning after the super-admin make login ??

Thank you.

![captura de tela de 2018-11-22 10-30-09](https://user-images.githubusercontent.com/10158758/48903264-2b821e00-ee42-11e8-8a1b-06eb67cb6b95.png)

**Comment by trasher** [comment]
This is not possible. Please report issue on plugni so they get that fixed.
