### ISSUE TITLE
Notifications being sent for reservations in the past

### ISSUE THREAD

**Issue by krab-stik** [glpi-project/glpi#4962]
**Describe the bug**

When a reservable item is marked as non-reservable, all linked reservations get deleted, which causes a massive number of "Reservation deleted" notification emails to get sent, even for reservations several years in the past.

We marked an old laptop as non-reservable and all users who had rented it at any point in time were spammed with hundreds of "Reservation deleted" emails.

**Page(s) URL**

- The _Authorize Reservations_ and _Prohibit Reservations_ buttons appear on the _Reservations_ tab for any item, for example: http://example.com/glpi/front/computer.form.php?id=12345
- Reservations can be made on this page: http://example.com/glpi/front/reservation.php?reservationitems_id=98765

**To reproduce**

1. Take any item (or create a new one) and make it reservable with the _Authorize Reservations_ button.
2. Create a new reservation for the item with a date in the past and assign it to another user (if the reservation is made for the current user, no notifications get sent).
3. Now make the item non-reservable by clicking the _Prohibit Reservations_ button.
4. The user will receive a notification email even though the reservation is already over.

**Expected behavior**

When an item is marked as non-reservable and all linked reservations get deleted, notifications should not be sent for old reservations in the past.

**Additional context**

We're running the latest version, GLPI 9.3.2.

**Comment by trasher** [comment]
Please try with 9.3.3 (and/or 9.4-beta)

**Comment by krab-stik** [comment]
We installed GLPI 9.3.3 and it behaves in the same way.
