### ISSUE TITLE
Add locations informations to notification tags

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#497]
Report to this suggestion : http://glpi.userecho.com/topics/21-location-related-notification-tags/ 

Add location informations as notification tags.

**Comment by ladenree76000** [comment]
I dont know how to submit but i wrote a modification for notificationtargetticket.class.php

line #339      
`
 $datas['##ticket.location##'] = '';
      if ($item->getField('locations_id')) {
         $datas['##ticket.location##'] = Dropdown::getDropdownName('glpi_locations',
                                                                   $item->getField('locations_id'));
	$locations = new location();
	$locations->getFromDB($item->getField('locations_id'));	
	$datas['##ticket.location.comment##'] = $locations->getField('comment');
	$datas['##ticket.location.room##'] = $locations->getField('room');
	$datas['##ticket.location.building##'] = $locations->getField('building');
	$datas['##ticket.location.latitude##'] = $locations->getField('latitude');
	$datas['##ticket.location.longitude##'] = $locations->getField('longitude');
	$datas['##ticket.location.altitude##'] = $locations->getField('altitude');
	$datas['##ticket.location.completename##'] = $locations->getField('completename');							   
      }
`

and 

`   function getTags() {

      parent::getTags();

      //Locales
      $tags = array('ticket.type'                  => __('Type'),
                    'ticket.sla'                   => __('SLA'),
                    'ticket.requesttype'           => __('Request source'),
                    'ticket.itemtype'              => __('Item type'),
                    'ticket.item.name'             => __('Associated item'),
                    'ticket.item.serial'           => __('Serial number'),
                    'ticket.item.otherserial'      => __('Inventory number'),
                    'ticket.item.location'         => sprintf(__('%1$s: %2$s'),
                                                              _n('Associated element', 'Associated elements', 2),
                                                              __('Location')),
                                                                                                                        
                    'ticket.item.model'            => __('Model'),
                    'ticket.item.contact'          => __('Alternate username'),
                    'ticket.item.contactnumber'    => __('Alternate username number'),
                    'ticket.item.user'             => __('User'),
                    'ticket.item.group'            => __('Group'),
                    'ticket.isdeleted'             => __('Deleted'),
                    'followup.date'                => __('Opening date'),
                    'followup.isprivate'           => __('Private'),
                    'followup.author'              => __('Writer'),
                    'followup.description'         => __('Description'),
                    'followup.requesttype'         => __('Request source'),
                    'ticket.numberoffollowups'     => _x('quantity', 'Number of followups'),
                    'ticket.numberoflinkedtickets' => _x('quantity', 'Number of linked tickets'),
                    'ticket.numberofproblems'      => _x('quantity', 'Number of problems'),
                    'ticket.numberofchanges'       => _x('quantity', 'Number of changes'),
                    'ticket.numberofitems'         => _x('quantity', 'Number of items'),
                    'ticket.autoclose'             => __('Automatic closing of solved tickets after'),
                    'ticket.location'              => __('Location'),
		    'ticket.location.comment'	   =>__('Location comments'),
		    'ticket.location.room'	   =>__('Room number'),
		    'ticket.location.building'	   =>__('Building number'),
		    'ticket.location.completename' =>__('Location'),
		    'ticket.location.latitude'	   =>__('Latitude'),
		    'ticket.location.longitude'	   =>__('Longitude'),
		    'ticket.location.altitude'	   =>__('Altitude'),
                    'ticket.globalvalidation'      => __('Global approval status'),
                    'ticket.solution.approval.description'  => __('Solution rejection comment'),
                    'ticket.solution.approval.date'         => __('Solution rejection date'),
                    'ticket.solution.approval.author'       => __('Approver')
                  );`

**Comment by ladenree76000** [comment]
notificationtargetticket.class.php 
line 408
`               //Object location
               if ($hardware->isField('locations_id')) {
                  $tmp['##ticket.item.location##']
                              = Dropdown::getDropdownName('glpi_locations',
                                                          $hardware->getField('locations_id'));
			$locations = new location();
			$locations->getFromDB($hardware->getField('locations_id'));	
			$datas['##ticket.item.location.comment##'] = $locations->getField('comment');
			$datas['##ticket.item.location.room##'] = $locations->getField('room');
			$datas['##ticket.item.location.building##'] = $locations->getField('building');
			$datas['##ticket.item.location.latitude##'] = $locations->getField('latitude');
			$datas['##ticket.item.location.longitude##'] = $locations->getField('longitude');
			$datas['##ticket.item.location.altitude##'] = $locations->getField('altitude');
			$datas['##ticket.item.location.completename##'] = $locations->getField('completename');
               }
`
line 358 datas should be initialised
`
 //Tags associated with the object linked to the ticket
      $datas['##ticket.itemtype##']           = '';
      $datas['##ticket.item.name##']          = '';
      $datas['##ticket.item.serial##']        = '';
      $datas['##ticket.item.otherserial##']   = '';
      $datas['##ticket.item.location##']      = '';
      $datas['##ticket.item.contact##']       = '';
      $datas['##ticket.item.contactnumber##'] = '';
      $datas['##ticket.item.user##']          = '';
      $datas['##ticket.item.group##']         = '';
      $datas['##ticket.item.model##']         = '';
      $datas['##ticket.item.location.comment##'] = '';
			$datas['##ticket.item.location.room##'] = '';
			$datas['##ticket.item.location.building##'] = '';
			$datas['##ticket.item.location.latitude##'] = '';
			$datas['##ticket.item.location.longitude##'] = '';
			$datas['##ticket.item.location.altitude##'] = '';
			$datas['##ticket.item.location.completename##'] = ''; 
`
label for tickets item should also be added
line 690;
`		    'ticket.item.location.comment'	   =>__('Location comments'),
		    'ticket.item.location.room'	   =>__('Room number'),
		    'ticket.item.location.building'	   =>__('Building number'),
		    'ticket.item.location.completename' =>__('Location'),
		    'ticket.item.location.latitude'	   =>__('Latitude'),
		    'ticket.item.location.longitude'	   =>__('Longitude'),
		    'ticket.item.location.altitude'	   =>__('Altitude'),  `
