### ISSUE TITLE
[GLPI 9.3.2] - No match search in a dropdown filter with accented word

### ISSUE THREAD

**Issue by pedroluisvsousa** [glpi-project/glpi#4974]
In the GLPI 9.2.4, we could search a word on a dropdown filter with accent.
Eg: search "Catégorie" with "catego" : OK

In the GLPI 9.3.2 the above search no match.

**Screeshots**

* In the GLPI 9.2.4

Ticket page
![categorie_924](https://user-images.githubusercontent.com/26510405/49020735-ef1b2e80-f16f-11e8-9c12-e33c4f0d7f88.png)

User page
![telephone_924](https://user-images.githubusercontent.com/26510405/49020737-ef1b2e80-f16f-11e8-8676-019f24aaf0f5.png)

* In the GLPI 9.3.2

Ticket page
![categorie_932](https://user-images.githubusercontent.com/26510405/49020776-ff330e00-f16f-11e8-89b0-470f2eb7b1fc.png)

User page
![telephone_932](https://user-images.githubusercontent.com/26510405/49020777-ff330e00-f16f-11e8-98ce-b359a557031c.png)

**Comment by trasher** [comment]
@pedroluisvsousa please test proposed fix (#5093 )

**Comment by cedric-anne** [comment]
Hi,

This fix will be merged in 9.4 branch.

I just check and you can apply the patch ( https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/5093.patch ) in 9.3.3 version to fix it.

Regards

**Comment by pedroluisvsousa** [comment]
Hi cedric-anne,

I tested this fix that you suggested and did not work in version 9.3.3.

Regards

**Comment by trasher** [comment]
So you'll have to wait for 9.4 to get it fixed
