### ISSUE TITLE
Inactive Technician show at ticket filter

### ISSUE THREAD

**Issue by dunipj** [glpi-project/glpi#4985]
Hi,

I've just updated to 9.3.3 version and I see that the ticket filter by technician displays old technicians that are inactive and deleted when I do a research.

Here ans example that is inactive and deleted tech:

![image](https://user-images.githubusercontent.com/35108492/49150165-354ccb00-f2f3-11e8-8863-7732a8ce12c5.png)

And here the search:

![image](https://user-images.githubusercontent.com/35108492/49150012-c53e4500-f2f2-11e8-8830-964de3095e6c.png)

At the print, I deleted part of the name.

Tks

**Comment by cedric-anne** [comment]
Hi,

Looks like it is a feature. See https://github.com/glpi-project/glpi/issues/1590.

Regards
