### ISSUE TITLE
version doesn't change in 'glpi_configs' table after upgarde

### ISSUE THREAD

**Issue by GaneshKandu** [glpi-project/glpi#4986]
after upgrading GLPI from  9.3.2 to 9.3.3 i noticed that it does not update version in 'glpi_configs' table

I guess this is due to upgrade php file is missing in /install/ folder.

Can you please check and resolve this issue ?

**Comment by trasher** [comment]
Does it breaks something?

**Comment by GaneshKandu** [comment]
No it does not break anything. But is it supposed to be updated or not ?

**Comment by trasher** [comment]
`dbversion` should have been added since 9.2 (see upgrade file). This is not related.

**Comment by trasher** [comment]
Note that you probably can use the CLI update command with the `--force` flag to get that fixed.
