### ISSUE TITLE
Duplicated tickets

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4989]
https://forum.glpi-project.org/viewtopic.php?id=166255

I confirm the bug.
Call to manageLinkedTicketsOnSolved must stay in post_updateitem for ticket solved just with changing status

**Comment by cedric-anne** [comment]
Hi @yllen ,

Could you test #5581 ?

Regards

**Comment by yllen** [comment]
Tested with solution added, change status, with ticket 1 linked to ticket 2 and ticket 2 linked to ticket 3.

All is not OK.
If you change status of ticket 1 to solved with autoclose delay to immediatly, ticket stay to solved ( linked tickets are solved).
If you add a solution, ticket 1 and linked tickets are closed.

For me in postUpdate of the ticket is missing handle autoclose. this autoclose is only done in postAdd of ITIL solution but when we only change the status we don't call ITILSolution.

It's perhaps not the same bug but when i test, i test all.

**Comment by trasher** [comment]
If the original issue is fixed, we'll merge the pull request. Even if not all is fixed yet, it's better to have as many fixes as possible merged before 9.4.1 release.

New issue does not seems directly related, please open another ticket so we can track. Thank you.
