### ISSUE TITLE
GLPI 9.3.3 wrong log entry after KB revision revert

### ISSUE THREAD

**Issue by shoothub** [glpi-project/glpi#4990]
GLPI version 9.3.3 (also 9.3.2) write a bad log entry in Administration - Logs after reverting knowledge base revision.
It write log entry:

> glpi reverts item to revision d

but should be:

> glpi reverts item to revision 13

The bug is probably in 2 files:
* https://github.com/glpi-project/glpi/blob/master/inc/knowbaseitem.class.php#L1935
* https://github.com/glpi-project/glpi/blob/master/inc/knowbaseitemtranslation.class.php#L434

1. Go to 'Tools - KB, edit KB'
2. Click on 'Revisions'
3. Click to 'restore'
4. Check log in 'Administration - Logs' message

**Expected behavior**
glpi reverts item to revision 13
glpi reverts item translation to revision 14

**Screenshots**
![screenshot from 2018-11-28 15-30-56](https://user-images.githubusercontent.com/28008456/49158549-c12a1b80-f322-11e8-8d7b-38acb6a19531.png)

**Comment by shoothub** [comment]
Hello, you changed line to:

> sprintf(__('%s reverts item to revision %s'), $_SESSION["glpiname"], $revid));

but i think, it should be %d as second parameter, not %s:

> sprintf(__('%s reverts item to revision %d'), $_SESSION["glpiname"], $revid));

Comment for translators tell the same thing:
//TRANS: %s is the user login, %d the revision number

**Comment by trasher** [comment]
I'll change the doc, we cannot be sure `$revid` is not a string.
