### ISSUE TITLE
display item type for post only

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#4991]
https://forum.glpi-project.org/viewtopic.php?id=166271

Only for simplified interface at the creation. OK for standard interface.

Still present in 9.2

**Comment by cedric-anne** [comment]
Hi,

This is not really a bug, just a global behaviour on dropdowns. Indeed, when text is too long, truncation is made on its begining to be sure to display its end. This has been made like this to be sure to display the most important part of labels in case of tree dropdowns.

This should be reviewed globally.

Regards

**Comment by yllen** [comment]
@cedric-anne You did not read my post. This issue is only for simplified interface. 
If it was the change of dropdowns, you may have this issue for all interfaces, all objects...

**Comment by cedric-anne** [comment]
Hi,

I read, test and debug. Problem may be solved for some items by enlarging the field on simplified interface, but if name is too long, it is truncated on left side.

Regards

**Comment by yllen** [comment]
Yes i agree but the text is troncate without reason
![image](https://user-images.githubusercontent.com/12936722/54213704-21655780-44e5-11e9-980d-52bf85f14853.png)
![image](https://user-images.githubusercontent.com/12936722/54213752-35a95480-44e5-11e9-8bca-472b8948f120.png)
