### ISSUE TITLE
Bookmarks: dialog display bug

### ISSUE THREAD

**Issue by nbriche** [glpi-project/glpi#50]
Tested on http://demo.glpi-project.org (don't know which commit; should perhaps put it somewhere in the footer for beta versions)

1) Open the bookmarks dialog.
2) Click on a bookmark to open its properties, then save. The bookmarks list reappears, but under the Edit properties form.
3) Close the bookmarks dialog, reopen it. The Edit properties form is still there (but empty), on top of the bookmarks list.
4) Reload or ctrl+reload: still there.
5) Log off, log on: still there (that one kind of surprised me)

**Comment by nbriche** [comment]
A screenshot of the problem at stage 3:
![capture d ecran de 2015-08-05 11 11 00](https://cloud.githubusercontent.com/assets/424286/9082212/ca046984-3b62-11e5-82f1-b159c788fb1a.png)

Firefox 39 on Ubuntu 15.04.

**Comment by orthagh** [comment]
demo up to date
