### ISSUE TITLE
GLPI 9.3.3 wrong date 2013 after clicking list in planning page

### ISSUE THREAD

**Issue by shoothub** [glpi-project/glpi#5000]
After you click **list** view in Assistance planning calendar screen, and click back to month/week/day listing (one of them), date is reverted to year 2013. For example 2013 Nov 01 – 30 (for month view), 2013 Nov 25 – Dec 01 (for week view), 2013 Nov 28 (for day view). 

**Page(s) URL**
https://demo.glpi-project.org/front/planning.php

**To reproduce**

1. Go to 'Assistance - Planning'
2. Click on 'list' view (right site of page)
3. Click back to one of views 'month, week, or day'
4. Date is in year 2013

**Expected behavior**

Calendar view should show correct date interval after clicking list and month/week/day and not year 2013.

**Screenshots**
![screenshot from 2018-11-28 18-09-50](https://user-images.githubusercontent.com/28008456/49168979-0a856580-f339-11e8-9a2a-4cd82d456b2a.png)
![screenshot from 2018-11-28 18-09-56](https://user-images.githubusercontent.com/28008456/49169012-1e30cc00-f339-11e8-9b8b-05d16529453b.png)
![screenshot from 2018-11-28 18-10-02](https://user-images.githubusercontent.com/28008456/49169014-21c45300-f339-11e8-9bb3-40f74b194aea.png)

Same problem also in 9.3.2

**Comment by M-Falken** [comment]
Bug confirmed in 9.3.3 
and the GET VARIABLE is ok with:
```
date => 2018-11-28
type => week
```
