### ISSUE TITLE
Date format separator not configurable

### ISSUE THREAD

**Issue by shoothub** [glpi-project/glpi#5001]
**Can't change date format separator.**

In current version of GLPI (9.3.3) it is not able to change date format to custom settings (Setup - General - Default values: Date format, or profile - Personalization - Date format). There is only selection of date format from only 3 options:

```
1. YYYY-MM-DD
2. DD-MM-YYYY
3. MM-DD-YYYY
```
Problem is especially with separator - (dash) which is not configurable. For example in Slovak/Czech language we use . (dot) as a separator for date and not dash: 
`29.11.2018`

Another languages use / as separator etc.

So it would be great to have option to also change separator for date format.

**Describe the solution you'd like**

Please add option to change separator for date format. Or better to able to also use custom php format:
http://php.net/manual/en/function.date.php.

For example Wordpress uses 4 predefined options a you can also use your own custom which is great:
https://www.wpbeginner.com/beginners-guide/how-to-change-date-and-time-format-in-wordpress/

![screenshot from 2018-11-29 08-55-59](https://user-images.githubusercontent.com/28008456/49207445-3b0ae500-f3b5-11e8-93d3-72f93aeff5a5.png)

**Comment by orthagh** [comment]
#
Please use [suggestion website](suggest.glpi-project.org) for feature requests, we are a small team and we need to prioritize developments.
So if your feature is popular on the suggest site, we will implement it.

Regards

**Comment by gkukovacec** [comment]
Hi, can you point us to the right direction (file) so we can fix this ourselves?

Thanks!
