### ISSUE TITLE
Time format not configurable, only 24-hours

### ISSUE THREAD

**Issue by shoothub** [glpi-project/glpi#5002]
**Not able to change time format, for example to 12 hours AP/PM.**

GLPI support a lot of languages, but it isn't very flexible in setup language formats, for example change 12/24 hours format.

**Describe the solution you'd like**

It would be fine to have a option to change time format at least 12/24 hours. Better would be add option to also use custom time format for displayed time. 

For example Wordpress use 4 option and one custom:

![screenshot from 2018-11-29 09-11-27](https://user-images.githubusercontent.com/28008456/49207976-c9cc3180-f3b6-11e8-8d6a-4f0c5bfed7a4.png)

**Comment by orthagh** [comment]
Please use [suggestion website](suggest.glpi-project.org) for feature requests, we are a small team and we need to prioritize developments.
So if your feature is popular on the suggest site, we will implement it.

Regards
