### ISSUE TITLE
First day of week not configurable in calendar

### ISSUE THREAD

**Issue by shoothub** [glpi-project/glpi#5003]
**Cannot change first date of week in calendars.**

Calendar in Assistance/Plannings and while entering dates in tickets for example starts with Monday. But some countries use Sunday as a start of week.

**Describe the solution you'd like**

Please add option to change first day of week at least option to change Sunday/Monday and use it on calendar interfaces.

**Screenshots from glpi 9.3.3**

![screenshot from 2018-11-29 09-18-37](https://user-images.githubusercontent.com/28008456/49208428-0f3d2e80-f3b8-11e8-8f8f-90fe2d815b6b.png)
![screenshot from 2018-11-29 09-18-47](https://user-images.githubusercontent.com/28008456/49208433-12381f00-f3b8-11e8-970c-fd2078947598.png)

**Comment by orthagh** [comment]
Please use [suggestion website](suggest.glpi-project.org) for feature requests, we are a small team and we need to prioritize developments.
So if your feature is popular on the suggest site, we will implement it.

Regards
