### ISSUE TITLE
Secure Database Connection

### ISSUE THREAD

**Issue by sergiozygmunt** [glpi-project/glpi#5016]
**Describe the bug**

GLPI does not support secure database connections.

**Page(s) URL**

All of GLPI. If you install a new GLPI instance with a MySQL server that mandates SSL/TLS, it will fail. If you upgrade an existing GLPI instance's database to require SSL/TLS, the database connection will fail.

**To reproduce**
Install GLPI using a MySQL database that requires/forces SSL/TLS connections.

**Expected behavior**

GLPI should support SSL/TLS database connections.

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE. There is already one for that: https://glpi.userecho.com/communities/1/topics/824-ssl-connection-to-mysql-db
