### ISSUE TITLE
Check new plugin versions

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#5017]
**Describe the solution you'd like**

Add a command/cron to check for plugins new versions on [plugins website](https://plugins.glpi-project.org).

**Comment by orthagh** [comment]
Done in marketplace integration (9.5.0) - see https://github.com/glpi-project/glpi/commit/7004cc023dd55c2c4977922983a10d56983419e3#diff-e8bb340ccfcc363ff30fef5803c4f2a641219a1a69264b7750f5320ead95071b
