### ISSUE TITLE
Mail collector - add followup and refuse ticket solution

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#5020]
**Describe the bug**
You have a resolved ticket. GLPI send an email ton the user. 
The user answer (to say "thanks") and the email goes to collector.
The email add a followup and refuse the solution of the ticket.

**To reproduce**

1. Create a ticket
2. Resolve it
3. Send an email to the collector to add a followup to the ticket
4. The ticket's solution has been refused because of the followup

**Expected behavior**
It would be better if the mail only add a followup to the ticket.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Tested on GLPI 9.3.3

**Comment by batu-one** [comment]
That's exactly what should happen. You should clarify to your users that when a ticket is solved, any reply will reopen the ticket.
You can modify your notification template to include such message.

**Comment by keha35** [comment]
Hi, 

Thanks for the reply.
I think this shouldn't happen like this.
When you receve the email you need to validate the solution in using the GLPI's interface.
Sending an email to the collector to add a followup to the ticket should only add a folowup.

**Comment by keha35** [comment]
I've tested with 9.4-rc1 and the probleme is still here.

**Comment by cedric-anne** [comment]
Hi,

Changing this behaviour seems pretty simple, here is the diff (not tested yet):
```diff
diff --git a/inc/mailcollector.class.php b/inc/mailcollector.class.php
index d9a5a53d77..9e2d4e9058 100644
--- a/inc/mailcollector.class.php
+++ b/inc/mailcollector.class.php
@@ -1035,10 +1035,6 @@ class MailCollector  extends CommonDBTM {
          // No hardware associated
          $tkt['itemtype'] = "";
          // Mail request type
-
-      } else {
-         // Reopen if needed
-         $tkt['add_reopen'] = 1;
       }
 
       $tkt['requesttypes_id'] = RequestType::getDefault('mail');
```

@trasher, @orthagh, should we change the behaviour or should we handle it using a configuration value ?

Regards

**Comment by orthagh** [comment]
agree with the diff, i'm not for one additional config parameter.

**Comment by OscarBeiro** [comment]
This has been GLPI behavior (at least for a while).
IMO, just changing it without the possibility to keep it the same, doesn't seem a good idea.

**Comment by trasher** [comment]
So this is not a bug, but a feature. Feel free to open or upvote proposition on suggestion website).
