### ISSUE TITLE
Error500 when reopenning the browser

### ISSUE THREAD

**Issue by ThomasLoupiac** [glpi-project/glpi#5024]
Hello,

We recently migrated from GLPI V0.72 to 9.2, and with new version we are experiencing a very problematic issue.

We have to type of user : 
- internal user, linked to the ldap
- external user, not linked to the ldap and using local glpi account

When a external user connect to GLPI, no issue, but if he close his browser and come back, it generate a error 500. 

**Page(s) URL**

Directly when accessing the application,

**To reproduce**

1. Go to GLPI (when ldap is actve) with a local account
2. login then close the browser without login out
3. Go to GLPI
4. Error 500 or black page (depend on the browser)

**Expected behavior**

User is asked to login again

**Logs**

Apache log :
[Wed Dec 05 14:51:29.031897 2018] [:error] [pid 2224] [client XXXXX] PHP Fatal error:  Uncaught RuntimeException: Something went wrong searching in LDAP directory in /var/www/glpi/inc/authldap.class.php:2805\nStack trace:\n#0 /var/www/glpi/inc/auth.class.php(633): AuthLDAP::searchUserDn(Resource id #18, Array)\n#1 /var/www/glpi/front/login.php(79): Auth->Login('test.erreur500', '', false, false)\n#2 {main}\n  thrown in /var/www/glpi/inc/authldap.class.php on line 2805

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.2.1 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux XXXX #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 PHP 7.0.30-0+deb9u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, 	wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="2000M" post_max_size="1024M" safe_mode="" session.save_handler="files" 	upload_max_filesize="1000M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at XXXX Port XXXX ) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0 Server Software: Debian 9.6 	Server Version: 10.1.37-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: OpusMySQL@localhost/OpusPreprod 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is not present xmlrpc extension is not present /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK /var/www/glpi/files/_log : OK Web access to the files directory, should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpCas version 1.3.5 in (/var/www/glpi/vendor/jasig/phpcas/source) PHPMailer version 5.2.26 in (/var/www/glpi/vendor/phpmailer/phpmailer) SimplePie version 1.5.1 in (/var/www/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.13 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

Server: 'XXXX', Port: 'XXX', BaseDN: 'ou=Users,ou=XXXX ,dc=XXXX ,dc=LOCAL', Connection filter: none, RootDN: 		'XXXX', Use TLS: none Server: 'XXXX', Port: 'XXXX', BaseDN: 'ou=Espagne,ou=HR Path,ou=Users,ou=XXXX,dc=XXXX,dc=LOCAL', Connection filter: 		none, RootDN: 'cn=Linux GLPI,ou=Service Accounts,ou=IT,ou=XXXX ,dc=XXXX ,dc=LOCAL', Use TLS: none Server: 'XXXX ', Port: '389', BaseDN: 'ou=France,ou=XXXX ,ou=Users,ou=XXXX ,dc=XXXX ,dc=LOCAL', Connection filter: 		none, RootDN: 'XXXX ', Use TLS: none Server: 'XXXX ', Port: 'XXXX ', BaseDN: none, Connection filter: 'ou=XXXX ,ou=Users,ou=XXXX ,dc=XXXX ,dc=LOCAL', 		RootDN: 'XXXX ', Use TLS: none

Not active

Way of sending emails: SMTP (XXXX )

 

aide                 Name: Aide                           Version: 1.0        State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.7.0      State: Enabled 	feuilletemps         Name: feuille de temps test version  Version: 1.0        State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.1.5      State: Enabled 	pdf                  Name: Impression pdf                 Version: 1.3.1.1    State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.4.0      State: Enabled 	reports              Name: Rapports                       Version: 1.11.2     State: Enabled 	release              Name: Release                        Version: 1.0        State: Enabled
[/code]

Thank a lot for your assistance.

Thomas

**Comment by trasher** [comment]
9.2 is not maintained anymore. Please try with latest version and see if the problem still appears.

**Comment by picklesrein** [comment]
I just received the same error. It wasn't happening before I tried (likely unsuccessfully) to add LDAP authentication.
Will try upgrading to the next version but suspect I put bad data in the LDAP settings and now I'm locked out. Is there a specific database entry I might be able to modify/remove to undo my error?

**Comment by picklesrein** [comment]
> 9.2 is not maintained anymore. Please try with latest version and see if the problem still appears.

What is the maintenance schedule? How long do you anticipate 9.3.3 to be actively maintained?
Merci!

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/#support.
