### ISSUE TITLE
Problem with Session for Setup

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#5034]
There is a problem with default values in Session
Fresh installation of 9.4

I change default priority color - and it's the default color (when install) that is displayed on ticket list

glpipriority_5    =>    #ffadad in SESSION VARIABLE DEBUG 
but in config - in defualt values i define #198322

I try with high contrast too -> not loaded on save setup

If i save my preferences, change priority color & high contrast are OK

So this is a cache problem with default values (without user preferences)

**Comment by trasher** [comment]
This does not seems related to 9.4; even if some changes in this last version may permit to reproduce easier.

**Comment by cedric-anne** [comment]
Hi,

Should be fixed by #5418.

Regards
