### ISSUE TITLE
Html Tag in ticket comment

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#5035]
**Describe the bug**

With rich text desable, when you update a ticket description in adding for exemple "<test>" in the existing comment, after saving the ticket, the description contain all <br /> where there was a carriage return. 

**To reproduce**

With rich text desable:
1. Go to an existing ticket
2. Update the description with "<someText>"
3. Save the ticket
4. You can see the new description

**Expected behavior**

A clean description without the br tags

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

I'v test with glpi 9.2 and 9.3

**Comment by trasher** [comment]
Rich text parameter has been dropped in 9.4, so this kind of issues are automatically resolved ;)

**Comment by keha35** [comment]
Ok but with rich text when you add a tag like <Test> it is interpreted as Html tag and desapear from the comment.
