### ISSUE TITLE
Selection in big dropdown

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5036]
https://forum.glpi-project.org/viewtopic.php?id=166365

I don't have Internet Explorer so i can't reproduce

**Comment by M-Falken** [comment]
Tested under 9.3.3 with Win10 + IE11 v11.134.17763.0

With categories and subcategories (10)
I do not reproduce the bug.

**Comment by trasher** [comment]
Thanks for the feedback, I gues this has been solved since.

**Comment by becaudp** [comment]
https://forum.glpi-project.org/viewtopic.php?id=166365
I have this bug.

**Comment by xmprx** [comment]
I also have this behavior with Windows 10 + IE11 on GLPI 9.3.3.
9.4 does not seem to be affected by this.

Is there a patch for 9.3.3 or do I have to go to 9.4?

Thank you!

**Comment by trasher** [comment]
9.3 is no longer maintained, and the fix is not identified. So, yes, you have to switch to the latest release.

**Comment by cedric-anne** [comment]
Hi,

For your information, this is a bug in select2 component that seems hard enough to replicate that is has not been fixed since it has been reported in 2016.
https://github.com/select2/select2/issues/4684

Regards

**Comment by xmprx** [comment]
Hi,

in case it would be of any help, I've been trying to replicate it in other versions of glpi, and it appears it is only present in 9.3.3. 

The width of the whole (opened) dropdown should be determined by the longest value, as it is in 9.2.1 and 9.4. In 9.3.3, it just sets the width of the dropdown by the selected value, and if that is shorter than the longest one, selection breaks - it selects an item close to "selected" one.

Please find attached pictures, just in case there would be a way to fix it in 9.3.3 so we can postpone 9.4 upgrade till some later date.

Thank you!
![image004](https://user-images.githubusercontent.com/25879607/53500266-4fd94080-3aaa-11e9-9df7-d6c8e3fbe2ac.png)
![image005](https://user-images.githubusercontent.com/25879607/53500276-523b9a80-3aaa-11e9-80fc-a04d9bdcab5e.png)

**Comment by trasher** [comment]
9.3 is no longer maintained, nothing will get fixed there (especially if this is already fixed)
