### ISSUE TITLE
ldap_mass_sync.php filter interpretation errors when using NOT (!) operator

### ISSUE THREAD

**Issue by optik-aper** [glpi-project/glpi#5047]
The help text says to use double quotes when defining ldap_filter option.  Bash on Ubuntu doesn't like that and tries interpreting the NOT (!) operator in the filter.  It works fine if you use single quotes.

To reproduce (on Ubuntu 16.04):
- `cd /var/www/glpi/scripts/`
- `php ldap_mass_sync.php action=1 ldap_filter="(&(uid=*)(!(sn=Smith)))"`

Returns the below and doesn't continue
```
bash: !: event not found
```
Based on the help text shown below, I'd expect the filter to work with double quotes.
```
Usage: php -q -f ldap_mass_sync.php [action=<option>]  [ldapservers_id=ID]
Options values:
0: import users only
1: synchronize existing users only
2: import & synchronize users
before-days: restrict user import or synchronization to the last x days
after-days: restrict user import or synchronization until the last x days
ldap_filter: ldap filter to use for the search. Value must be surrounded by ""
```
The problem goes away if you use single quotes:
```
php ldap_mass_sync.php action=1 ldap_filter='(&(uid=*)(!(sn=Smith)))'
Processing LDAP Server: ldap.<redacted>, ID: 1 
...................................................................
^C

**Comment by trasher** [comment]
I guess this is quite specific. Using another shell, you may have variants... Not sure the example is in cause, and not sure replacing double with single quotes will make everybody happy...
