### ISSUE TITLE
missing btu and amps in rack models

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#5049]
Missing the calculation (and the values) for amps and btu in the new rack management ...

**Comment by trasher** [comment]
It's a bit cryptic, but I guess you're talking about power management; this is not implemented.

Check specs, and rely on suggestion webstite for RFE please. Thank you.

**Comment by Megachip** [comment]
Put a suggestion:
https://glpi.userecho.com/communities/1/topics/953-missing-tech-specs-and-rack-calculations-on-glpi-93

didn't know that suggest.glpi-project.org is monitored, cause questions most times are not replied.

**Comment by trasher** [comment]
Many features has already been implemented from suggestion website. For support, it's better to use forums.
