### ISSUE TITLE
[beta 9.4] upgrade from 9.3.3 issue with plugins

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#5050]
**Description : **
upgrade from 9.3.3 to 9.4 returns fatal error related to plugin 

**To reproduce**
extract tarball in a new glpi94 folder
mysqldump from glpi9.3.3 database restored in a new glpi94 database
with browser goto localhost\glpi94
tests OK
set server/user/password  select database glpi94
i got this message

La version de la base de données semble correcte (10.1.34) - Parfait !La version de la base de données semble correcte (10.1.34) - Parfait !

Fatal error: Uncaught Error: Call to a member function set() on null in /var/www/html/glpi94/inc/plugin.class.php:665 Stack trace: #0 /var/www/html/glpi94/inc/update.class.php(171): Plugin->unactivateAll() #1 /var/www/html/glpi94/install/update.php(464): Update->doUpdates('9.3.3') #2 /var/www/html/glpi94/install/update.php(577): doUpdateDb() #3 {main} thrown in /var/www/html/glpi94/inc/plugin.class.php on line 665

**Expected behavior**
upgrade  to 9.4

**Logs**
[2018-12-08 10:13:19] glpiphplog.WARNING: Test logger  
[2018-12-08 10:13:24] glpiphplog.WARNING: Test logger  
(nothing else)

**My GLPI setup (from my 9.3.3 instance)**
Operating system: Linux xxx-Vostro-200 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64
PHP 7.0.33-1+ubuntu18.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at localhost Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Server Software: Ubuntu 18.04
	Server Version: 10.1.34-MariaDB-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: xxxx@localhost/glpi93
	Host info: Localhost via UNIX socket

**Additional context**
I had some plugin in 9.3.3 ( in my DB dump) but did not copy  files in glpi94/files

**Comment by ladenree76000** [comment]
new installation works ( no upgrade)

**Comment by ppasserini** [comment]
Same to me.
I also tried to disable and uninstall all the plugin from 9.3, then make a SQL dump and restore it. Didn't works, same error.

**Comment by trasher** [comment]
I guess this is the presence of the plugin itself that cause the issue. Could you please try removing directories directly If you can say which plugins(s?) do cause the issue, it would help.

**Comment by ppasserini** [comment]
IMO it's related to information about old plugin still present into DB because when I tried the update my plugin directory was empty and, as you can read up, before the update process I did the disable and uninstall steps for each plugin inside my 9.3.1 installation.

**Comment by ladenree76000** [comment]
My plugin directory was also empty (but plugin tables were in DB dump)

**Comment by ladenree76000** [comment]
i added line as described by tsmr and could upgrade from 9.2.4 
i tried again from 9.3.3 and i got  : 
Version non supportée (9.3.3)

**Comment by OscarBeiro** [comment]
Tested and running OK.
Thanks @cedric-anne

**Comment by cedric-anne** [comment]
Hi @OscarBeiro,

I just changed my PR using a less specific logic.

Could you test again ?

Regards
