### ISSUE TITLE
[beta 9.4.] upgrade from 9.3.3 not supported

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#5062]
**Describe the bug**
upgrade from glpi 9.3.3 to 9.4 returns : "Version non supportée (9.3.3)"

**Page(s) URL**
/
**To reproduce**
dump glpi9.3.3
restore dump into glpi9.4
extract install package in glpi9.4 ( set owner and rights)
modifiy pluginclass line 664 (	   $GLPI_CACHE = Config::getCache('cache_db'); ) se issue #5050 
run migration

**Expected behavior**
run migration to 9.4
**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

"Version non supportée (9.3.3)"

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Linux xxxx-Vostro-200 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64
PHP 7.0.33-1+ubuntu18.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at localhost Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0
Server Software: Ubuntu 18.04
	Server Version: 10.1.34-MariaDB-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: xxxxxxx@localhost/glpi94
	Host info: Localhost via UNIX socket

**Additional context**

i could upgrade from a 9.2.4 dump ( sorry, i dont have other dumps to test)

**Comment by trasher** [comment]
Please try proposed fix

**Comment by neogorn** [comment]
Hi, 

Not works for me!

I run **bin/console db:update --allow-unstable**, but it appears that "version 9.3.3 is not supported"

![image](https://user-images.githubusercontent.com/42190708/50304294-b7558d00-0476-11e9-84a1-4c1e4d2264e6.png)

tks.
