### ISSUE TITLE
[beta 9.4] innodb migration tool missing

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#5063]
**Describe the bug**

innodb migration script is missing

**To reproduce**
upgrade from 9.2.4 to 9.4 
migration works but table are MyISAM type. 
message : 396 tables non migrées au moteur InnoDB.

**Expected behavior**
As for 9.3 migration : use migration scripts that should be in glpi/scripts

**Comment by trasher** [comment]
As stated in the changelog, CLI commands have been changed. See https://glpi-install.readthedocs.io/en/develop/command-line.html#from-myisam-to-innodb.
