### ISSUE TITLE
An error occured loading contents. New ticket SuperAdmin User

### ISSUE THREAD

**Issue by touchmahorbs** [glpi-project/glpi#5071]
**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by trasher** [comment]
Filling description template is mandatory. Thank you.

**Comment by touchmahorbs** [comment]
in /var/log/messages:

mysqld: 2018-12-10 10:17:28 8642 [Warning] Aborted connection 8642 to db: 'db_glpi_prod' user: 'glpidb' host: 'localhost' (Got an error reading communication packets)
