### ISSUE TITLE
glpi 94 beta 

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5075]
Tentative de mise sur base test 9.3.3

LPI SETUP

Mise à jour
Connexion à la base de données réussie
La version de la base de données semble correcte (10.3.7) - Parfait !La version de la base de données semble correcte (10.3.7) - Parfait !

Fatal error: Uncaught Error: Call to a member function set() on null in C:\inetpub\wwwroot\glpi940beta\inc\plugin.class.php:665 Stack trace: #0 C:\inetpub\wwwroot\glpi940beta\inc\update.class.php(171): Plugin->unactivateAll() #1 C:\inetpub\wwwroot\glpi940beta\install\update.php(464): Update->doUpdates('9.2.4') #2 C:\inetpub\wwwroot\glpi940beta\install\update.php(577): doUpdateDb() #3 {main} thrown in C:\inetpub\wwwroot\glpi940beta\inc\plugin.class.php on line 665

**Comment by trasher** [comment]
Please use english only. There are already an open issue.

**Comment by ladenree76000** [comment]
see #5050
it seem to be fixed.
then you'll have "version 9.3.3 non supportée"
also fixed with :

**Comment by yalgva** [comment]
https://github.com/glpi-project/glpi/issues/5050 fixed

**Comment by ladenree76000** [comment]
see also  #5062
