### ISSUE TITLE
[9.4]Ticket Satisfaction

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#5079]
When saving the satisfaction of the ticket redirects to the page /front/ticketsatisfaction.form.php that does not exist

**Screenshots**
![imagen](https://user-images.githubusercontent.com/39123808/49727551-d121f380-fc70-11e8-9103-933130e3e976.png)

![imagen](https://user-images.githubusercontent.com/39123808/49727698-2eb64000-fc71-11e8-92eb-c2169b0d23ad.png)

![imagen](https://user-images.githubusercontent.com/39123808/49727748-4e4d6880-fc71-11e8-9674-1f3f2e44689d.png)

**Comment by cedric-anne** [comment]
Hi,

I think this link was also badly generated in previous GLPI versions.
Could you test fix provided in #5091 ?

Regards

**Comment by xacobofg** [comment]
I tried the fix and it works fine.
But I found another error that already happened in the previous versions.
If you re-open a request that already had a satisfaction when closing it again, it causes an error.
In version 9.3 it just wrote down the error in the log but in 9.4 what it does is leave the window blank.
This is the error written in the log:
```
glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: INSERT INTO `glpi_ticketsatisfactions` (`tickets_id`, `date_begin`, `type`) VALUES ('5', '2018-12-12 10:24:32', '1')
  Error: Duplicate entry '5' for key 'tickets_id'
  Backtrace :
  inc/dbmysql.class.php:814                          
  inc/commondbtm.class.php:658                       DBmysql->insert()
  inc/commondbtm.class.php:1140                      CommonDBTM->addToDB()
  inc/ticket.class.php:1660                          CommonDBTM->add()
  inc/commondbtm.class.php:1474                      Ticket->post_updateItem()
  inc/itilfollowup.class.php:222                     CommonDBTM->update()
  inc/commondbtm.class.php:1141                      ITILFollowup->post_addItem()
  front/itilfollowup.form.php:59                     CommonDBTM->add()
  {"user":"2@35f1c1eefe0d"} 
```

**Comment by cedric-anne** [comment]
@xacobofg Could you open another issue for this problem ?

Regards
