### ISSUE TITLE
glpi error 500

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#508]
Hello I open this new ticket, I have the same issue with IIS.

log :+1: 
2016-03-02 12:10:42 192.168.20.117 GET /glpi/front/login.php - 80 - 192.168.102.26 Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/48.0.2564.97+Safari/537.36 401 2 5 0
2016-03-02 12:11:24 192.168.20.117 GET /glpi/front/login.php - 80 UNG\YLA 192.168.102.26 Mozilla/5.0+(Windows+NT+6.1;+WOW64)+AppleWebKit/537.36+(KHTML,+like+Gecko)+Chrome/48.0.2564.97+Safari/537.36 500 0 0 42510

**Comment by satyan01** [comment]
[php.zip](https://github.com/glpi-project/glpi/files/154715/php.zip)

**Comment by tomolimo** [comment]
I'll see after lunch

**Comment by satyan01** [comment]
ok thx

**Comment by tomolimo** [comment]
Ok, let's try several things:
look into error logs in:

1. 'GLPi folder'/files/_logs/php-errors.log
1. e:\webserver\php\php_errors.log

**Comment by satyan01** [comment]
1 - nothing today
2 - nothing today

**Comment by tomolimo** [comment]
But does it work one time at least?

**Comment by satyan01** [comment]
yes as before

**Comment by tomolimo** [comment]
so, what has been done between both?

**Comment by satyan01** [comment]
I have migrated to IIS 7, all was fine, no change, after around one hour error 500. three try and ok, one hour error 500...

**Comment by satyan01** [comment]
Have you seen my php.ini ? all is correctly set up?

**Comment by tomolimo** [comment]
> Have you seen my php.ini ? all is correctly set up?
Seems OK yes,

We'll try to get all the traces from IIS.

1. enable logs on IIS like this (you may have it already enabled):
![image](https://cloud.githubusercontent.com/assets/7569958/13462431/a69c66fc-e087-11e5-8de6-f0ca0fe2a30d.png)

2. if not already install module Failed Request Tracing:
![image](https://cloud.githubusercontent.com/assets/7569958/13462474/e2a678ea-e087-11e5-8ee1-3b2307730999.png)

3. Enable tracing like following
![image](https://cloud.githubusercontent.com/assets/7569958/13462518/244bd934-e088-11e5-8e7d-b8d8d166641b.png)

4. replay your problem, and check the IIS Failed request traces

**Comment by satyan01** [comment]
I am sorry I don't find how to install the module, under configure on the right pane I have just limits

**Comment by tomolimo** [comment]
screen copy?

**Comment by satyan01** [comment]
I had to install the role service. done

**Comment by tomolimo** [comment]
ok

**Comment by satyan01** [comment]
nothing int failedreqlogfiles when i have the 500 error

**Comment by tomolimo** [comment]
You may have a problem with fastcgi sessions that may expires before PHP sessions.

**Comment by satyan01** [comment]
What I Have to do ?

**Comment by tomolimo** [comment]
I believe the best would be to request help from an external consultant.
May be someone from Teclib or Siprosii or else? @orthagh @ddurieux : could you direct @satyan to someone who can help him on site?
Currently, I've got no time to help you in such deep way: I've got an internal GLPi release to do:)!
