### ISSUE TITLE
[9.4] Link in reminder description

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#5080]
If I keep a link in the description of the reminder I can not click but in the ticket yes
![imagen](https://user-images.githubusercontent.com/39123808/49728308-a89af900-fc72-11e8-96a0-a1b7649a2eb9.png)
![imagen](https://user-images.githubusercontent.com/39123808/49728352-bf415000-fc72-11e8-9579-289c06f0d227.png)
![imagen](https://user-images.githubusercontent.com/39123808/49728376-dbdd8800-fc72-11e8-8ef5-eb629b7201f3.png)

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE; this is not currently possible.
