### ISSUE TITLE
[0.90.1] Missing tickets columns in super-admin profile

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#509]
Hi,

I encounter a malfunction with my GLPI.
On some tickets (not all), super-admin profile several columns of Directors are missing (status etc ..):
![missing_columns](https://cloud.githubusercontent.com/assets/113057/13460582/cd0b6952-e07b-11e5-91a7-3c644b128e9e.PNG)

Is there a solution to correct the problem?

++

**Comment by orthagh** [comment]
Please, write in English here or use the [forum](forum.glpi-project.org) for support in french.

Anyway, could you provide additional informations ?
- What's your glpi version ?
- Do you replicate the issue on various browsers ?
- Do you have some plugins enabled ?
- Could you test without them ?

**Comment by yllen** [comment]
and do you use ticket template?

**Comment by orthagh** [comment]
No answers since days, i close.
Reopen if you have precisions.

**Comment by barbuslex** [comment]
Same issue: 2 tickets in same entity, 2 differents bahaviors

Ticket 1
![image](https://cloud.githubusercontent.com/assets/113057/14167556/581114fa-f71c-11e5-885b-adc30beb1b6f.png)

Ticket 2
![image](https://cloud.githubusercontent.com/assets/113057/14167532/2f05d366-f71c-11e5-8ffe-99ae6dea5774.png)

Plugins : 
![image](https://cloud.githubusercontent.com/assets/113057/14167585/84eeeefc-f71c-11e5-8970-4198ef75b4ad.png)

Profile: super-admin
GLPI version : 0.90.1
Browsers: Google Chrome 49.0.2623.87, Internet Explorer 11, Firefox 45.0.1

**Comment by orthagh** [comment]
Do you have a specific config in you ticket's templates ?

**Comment by barbuslex** [comment]
@orthagh Yes but the column "Statut" isn't hide: 
![image](https://cloud.githubusercontent.com/assets/113057/14174145/c2c6c1b6-f742-11e5-8022-4426d87c8fea.png)
![image](https://cloud.githubusercontent.com/assets/113057/14174154/cef08d64-f742-11e5-953e-d9c14394104f.png)
![image](https://cloud.githubusercontent.com/assets/113057/14174157/d9d654e8-f742-11e5-822c-a4016aebd611.png)

**Comment by orthagh** [comment]
Can you check (and post here) in your profiles administration, your lifecycle for tickets ?

**Comment by barbuslex** [comment]
Profile: super-admin

![image](https://cloud.githubusercontent.com/assets/113057/14176994/46d164b4-f754-11e5-9c41-71ae0091cb5b.png)

![image](https://cloud.githubusercontent.com/assets/113057/14177040/ab98fba0-f754-11e5-892d-7464f3ecef0c.png)

![image](https://cloud.githubusercontent.com/assets/113057/14177049/b47e6dfe-f754-11e5-9c49-8400f6a2f873.png)

**Comment by orthagh** [comment]
On the tickets concerned by this issues, do you have some javascript errors (you can retrieves theses in developper tools of your browser - F12 key) ?

**Comment by yllen** [comment]
Types of your tickets are different: with Incident you don't see status, with Demand you see it.
I think your template arr not the right one because i see 2 mandatory fields must in your picture you don't have * near the name of mandatory fields

**Comment by barbuslex** [comment]
@orthagh No JS errors in developper console 

@yllen 
Here the full content of the templates (i have hide history and categories).
Incident: 
![incident](https://cloud.githubusercontent.com/assets/113057/14249005/edd336ae-fa77-11e5-9dac-3ee2bdb911a3.png)

Demande: 
![demande](https://cloud.githubusercontent.com/assets/113057/14249013/f157d776-fa77-11e5-910c-d356cfe4183c.jpg)

**Comment by barbuslex** [comment]
I have found the issue!
I had another template "Harware issues" that applies only to hardware problem and "Status" column was hidden in it.
Thank you for your help and sorry for the inconvenience.
