### ISSUE TITLE
[9.3.3] kernel (from operating systems tab) uses wrong database field

### ISSUE THREAD

**Issue by abeulink** [glpi-project/glpi#5094]
Problem: kernel field uses wrong database field

I have created a kernel list for "Operating systems" tab and I tried to select kernel field, but my list is not showing, see my screenshot below.

![image](https://user-images.githubusercontent.com/26407519/49796516-380cde80-fd3d-11e8-91f0-c13b64980972.png)

Then I wanted to see my list again, so I moved cursor to "i" and.... I found a problem.
It said "Show Kernel versions" (!!!!!!)

I think "Kernel" uses wrong database field, BECAUSE at left side on the screenshot you see a text mention "Kernel", not "Kernel version". 

And there is no "Kernel Version" on Operating systems tab. 
(version on right side is version number of operating system, example Windows 10)

**Comment by trasher** [comment]
There is a kernel table and a kernel_version one (see dropdowns). Link on OS is done on kernel version, this is excepted.
