### ISSUE TITLE
Upgrade PHP minimum version to 5.4

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#51]
It is now interesting to update PHP min version from 5.3 to 5.4.
Having PHP 5.4 by default would, for example, simplify LDAP sizelimit management.

**Comment by remicollet** [comment]
+1 for 5.4

**Comment by orthagh** [comment]
+1 

Impact on files : 
* index.php (l 40 & 41)
* inc/calendar.class.php (check and clean)
* inc/html.class.php (idem)
* inc/mailcollector.class.php (idem)
* inc/toolbox.class.php (l861 to 872)

On release we should announce this new prerequisite.

Is this could unlock some libraries update ?

**Comment by ddurieux** [comment]
Perhaps upgrade tiny_mce from version 3.x to version 4.x, load it is more faster (very more faster)

**Comment by remicollet** [comment]
> Is this could unlock some libraries update ?

Yes, ZF could be updatred to latest 2.4.x
* 2.3 (EOL) requires 5.3.3
* 2.4 requires  5.3.23
* 2.5 requires 5.5

**Comment by orthagh** [comment]
I just change preresite in markdown doc.
But i don't know how to update current dita version.
@yllen, do you have the right to edit it ?
