### ISSUE TITLE
MailCollector works erratically

### ISSUE THREAD

**Issue by DeedJayB** [glpi-project/glpi#5108]
**Bug Description**

Since 3 or 4 days, the mailcollector works very slowly. It supposed to be executed every 15 minutes. But the tickets are created within 2 or 3 hours. No changes have been made to the conf and no glpi updates since 9.3.1 (more than 1 month).

A mysqlcheck has been performed and there is one error : 
Table glpidb.glpi_notimportedemails doesn't exist

A quick look to the folder shows that there is glpi_notimportedemails.frm but no .idb

Could this be the cause ? 
Anyway, how to recreate this table ? From an old backup, this table seems to be empty.

**Expected behavior**

**Logs**

[2018-12-12 15:57:42] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP User Notice(1024): Configuration incorrecte du dossier accepted pour le collecteur support@xxxxx.fr
  Backtrace :
  :
  inc/mailcollector.class.php:1688                   trigger_error()
  inc/mailcollector.class.php:694                    MailCollector->deleteMails()
  front/mailcollector.form.php:77                    MailCollector->collect()
  {"user":"362@srv-glpi","mem_usage":"1.449\", 9.75Mio)"}
[2018-12-12 15:57:45] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP User Notice(1024): Configuration incorrecte du dossier accepted pour le collecteur support@xxxxx.fr
  Backtrace :
  :
  inc/mailcollector.class.php:1688                   trigger_error()
  inc/mailcollector.class.php:694                    MailCollector->deleteMails()
  front/mailcollector.form.php:77                    MailCollector->collect()
  {"user":"362@srv-glpi","mem_usage":"0.019\", 10.36Mio)"}
[2018-12-12 15:57:46] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP User Notice(1024): Configuration incorrecte du dossier accepted pour le collecteur support@xxxxx.fr
  Backtrace :
  :
  inc/mailcollector.class.php:1688                   trigger_error()
  inc/mailcollector.class.php:694                    MailCollector->deleteMails()
  front/mailcollector.form.php:77                    MailCollector->collect()
  {"user":"362@srv-glpi","mem_usage":"1.271\", 10.38Mio)"}
[2018-12-12 16:55:58] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP User Notice(1024): Configuration incorrecte du dossier accepted pour le collecteur support@xxxxx.fr
  Backtrace :
  :
  inc/mailcollector.class.php:1688                   trigger_error()
  inc/mailcollector.class.php:694                    MailCollector->deleteMails()
  front/mailcollector.form.php:77                    MailCollector->collect()
  {"user":"362@srv-glpi","mem_usage":"0.018\", 9.91Mio)"}
[2018-12-13 10:33:01] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  inc/auth.class.php:765
  front/login.php:84                                 Auth->login()
  {"user":"@srv-glpi","mem_usage":"0.015\", 3.30Mio)"}
[2018-12-13 10:33:15] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 657
  *** PHP Notice(8): Undefined index: id
  Backtrace :
  inc/auth.class.php:765
  front/login.php:84                                 Auth->login()
  {"user":"@srv-glpi","mem_usage":"0.014\", 3.30Mio)"}

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.3.1 ( => /var/www/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux srv-glpi 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
PHP 5.6.32-1+ubuntu14.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apc, apcu, calendar, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap,
	json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop,
	sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="4M" 
Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at glpi.support.lan Port 80)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.6.27-0ubuntu0.14.04.1
	Server SQL Mode: 
	Parameters: glpiuser@127.0.0.1/glpidb
	Host info: 127.0.0.1 via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is not present
CAS extension is not present
Database version seems correct (5.6.27) - Perfect!Database version seems correct (5.6.27) - Perfect!
OK/var/www/glpi/files/_log : OK
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_cache : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

Libraries
 
htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
SimplePie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library)
TCPDF version 6.2.17 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iacaml/autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)

**Comment by orthagh** [comment]
> Anyway, how to recreate this table ?

Here is the sql for this table creation:
```sql
CREATE TABLE `glpi_notimportedemails` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `from` varchar(255) NOT NULL,
  `to` varchar(255) NOT NULL,
  `mailcollectors_id` int(11) NOT NULL DEFAULT '0',
  `date` datetime NOT NULL,
  `subject` text,
  `messageid` varchar(255) NOT NULL,
  `reason` int(11) NOT NULL DEFAULT '0',
  `users_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `users_id` (`users_id`),
  KEY `mailcollectors_id` (`mailcollectors_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```

I don't know why you don't have this table (maybe a previous failed migration to innodb). but recreating it will be sufficient.


> this table seems to be empty
Usually if you dont have reject with mailcollector, the table is empty.

Regards.

**Comment by alansenairj** [comment]
glpidb.glpi_notimportedemails
Error    : Table 'glpidb.glpi_notimportedemails' doesn't exist in engine
status   : Operation failed

adding it

ERROR 1050 (42S01): Table 'glpi_notimportedemails' already exists
