### ISSUE TITLE
0.90: Private Follow-ups and Tasks Visible for users on profiles with Standard Interface

### ISSUE THREAD

**Issue by henrybartz** [glpi-project/glpi#511]
If I create a new test profile, setup Profile's Interface as Standard interface, uncheck all options and check the following options on Assistance menu: 
	See my ticket
	Update
	Create
	Beeing in charge
	Steal
	Change the priority
	See group ticket
	See assigned
	Assign

Setup the new profile and any group to an user.

When I login with the user and display a ticket I'm able to see the Private Follow-ups associated to the ticket.

**Comment by yllen** [comment]
Being in charge allow display private follow up because only a technician can being in charge, so he must read all follow up

**Comment by yllen** [comment]
Have you delete Being in charge in your profiles?

**Comment by orthagh** [comment]
No answers since days, i close.
Feel free to re-open and comment if you need precisions
