### ISSUE TITLE
[9.3+] Timeout during installation

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#5114]
The database creation can take 2-3 minutes, which is greater than default `max_execution_time` and greater than default `ProxyTimeout` (when FPM is used), both being set to 30 seconds.

**Comment by remicollet** [comment]
```
$ time bin/console glpi:database:install --config-dir=./tests --no-interaction --db-name=glpitest --db-user=root --db-password=valentin --force
Installation done.
real	3m0,599s

$ time mysql -uroot -pvalentin glpitest <install/mysql/glpi-empty.sql
real	2m51,690s

```

**Comment by cedric-anne** [comment]
Hi @remicollet 

I found a possible workaround by using a flush operation between each SQL operation. Could you test #5118 ?

Regards
