### ISSUE TITLE
[last Git version] PHP Notice(8): Undefined index: plannings on Init PHP session

### ISSUE THREAD

**Issue by Manu1400** [glpi-project/glpi#512]
1/ Clone branch master of GLPI (-> lasted commit : afc659d7cce4c68ec3297d6bef20e38e372b3a5a)
2/ In /plugins/ clone plugin fields (for have last commit version)
2/ Install GLPI : No update, just a install
3/ Connect to GLPI with glpi user

A PHP Notice is display to user.

In PHP log, i have a PHP Notice : 

2016-03-03 14:10:33 [2@master-ubuntu15]
  *** PHP Notice(8): Undefined index: plannings
  Backtrace :
  inc/toolbox.class.php:592                          
  inc/session.class.php:120                          Toolbox::userErrorHandlerDebug()
  inc/auth.class.php:803                             Session::init()
  front/login.php:78                                 Auth->Login()

Used : Ubuntu, Chrome, MySQL

[code]
 
GLPI 0.90.1-260-gafc659d (/tgu/tmp/glpi-last_version-git/glpi => /var/www/html/tgu/tmp/glpi-last_version-git/glpi)

Server
 
Operating system: Linux master-ubuntu15 3.19.0-30-generic #33-Ubuntu SMP Mon Sep 21 20:58:04 UTC 2015 x86_64
PHP 5.6.4-4ubuntu6.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, json, ldap, libxml,
	mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xdebug, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.10 (Ubuntu) (Apache/2.4.10 (Ubuntu) Server at localhost Port 80)
	Mozilla/5.0 (X11; Linux i686 (x86_64)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.6.25-0ubuntu0.15.04.1
	Server SQL Mode: NO_ENGINE_SUBSTITUTION
	Parameters: root@localhost/glpi-last_version-git
	Host info: Localhost via UNIX socket
	
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/config : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_dumps : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_sessions : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_cron : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_graphs : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_lock : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_plugins : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_tmp : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_rss : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_uploads : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_pictures : OK
OK/var/www/html/tgu/tmp/glpi-last_version-git/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.

Libraries
 
htmLawed version 1.1.21 in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/html/tgu/tmp/glpi-last_version-git/glpi/lib/password_compat). Compatitility: Ok

Mysql replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	fields               Name: Champs supplémentaires         Version: 0.90-1.1   State: Not installed

[/code]

**Comment by Manu1400** [comment]
Note : after logout, and a new login action, i have in log : 

2016-03-03 14:19:51 [2@master-ubuntu15]
  *** PHP Notice(8): Undefined index: plannings
  Backtrace :
  inc/session.class.php:120                          
  inc/auth.class.php:803                             Session::init()
  front/login.php:78                                 Auth->Login()

**Comment by Manu1400** [comment]
git blame in inc/session.class.php:120 => 6ac5e758e2096c87f3ed87d12751bf63b3154718

**Comment by Manu1400** [comment]
Issue with code in GLPI core

**Comment by yllen** [comment]
This correction is not correct.
You can read FAQ without being connected.
You can import LDAP group in script without being connected.

**Comment by Manu1400** [comment]
@yllen It's not my commit. It's @orthagh 's commit.

**Comment by orthagh** [comment]
@yllen, this is not the right issue and commit.
Anyway, see my comments here : https://github.com/glpi-project/glpi/commit/6ac5e758e2096c87f3ed87d12751bf63b3154718#commitcomment-16779687

I reclose here
