### ISSUE TITLE
Drop very old database update support

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#5132]
We're currently working on rewritting all raw SQL queries in GLPI. There are many, many of those in the update process, from very, very, very old GLPI releases.

Basic migration unit tests are run from a 0.72.2 release. That means we have no idea currently if preceding migrations are still working.
1- I propose to remove all update scripts < 0.72.3,

Some files beetween 0.72.3 and 0.80 are very huge and would require time to be migrated. 
2 - I propose to remove all update scripts < 0.80.

0.8 has been released in 2011, this change would target GLPI v 10.0.0 that will not be released this year :D

For users who have a version older than 0.80 or 0.72.3 would have to update to 9.4.x before migration to 10.0.0.

**Comment by trasher** [comment]
Removing < 0.72.3 support:
https://github.com/glpi-project/glpi/commit/32ca13ff4d10cd94321b1d89f4cec5b96c740533

Removing Also < 0.80 support:
https://github.com/glpi-project/glpi/commit/98c327617c41b0eca8e8b60e2c9fe4ec503339e4

Both:
https://github.com/glpi-project/glpi/compare/master...trasher:drop-old-updates

**Comment by ddurieux** [comment]
If it's documented to upgrade from very old version with step versions, no problems for me

**Comment by btry** [comment]
I agree with @ddurieux !

**Comment by trasher** [comment]
Sure docs will be updated: https://github.com/glpi-project/doc-install/compare/feature/cleaned-updates

**Comment by cconard96** [comment]
I agree with the change. I can't imagine many people use those versions still.

**Comment by trasher** [comment]
Thank you all for the feedback!

**Comment by MarcusStill** [comment]
Hello. Can you suggest how to update GLPI 0.72.4 to current?

**Comment by cedric-anne** [comment]
> Hello. Can you suggest how to update GLPI 0.72.4 to current?

GLPI 9.5.x supports update from GLPI 0.72.4. To get community support about the best way to do, please [use forums](https://forum.glpi-project.org/).

**Comment by cedric-anne** [comment]
Done in #7720.
