### ISSUE TITLE
[GLPI 9.3.2/9.3.3] - Php7 - Planning not display all events

### ISSUE THREAD

**Issue by dubreido** [glpi-project/glpi#5133]
Planning not display all events. 
After several hours, i find that the problem cause by the fonction json_encode() : return code 5 : UTF8ERROR.

This is an idea of resolution of this problem.
File : ajax/planning.php
Lign : 40 : Origin
```php
if ($_REQUEST["action"] == "get_events") {
   header("Content-Type: application/json; charset=UTF-8");
   echo json_encode(Planning::constructEventsArray($_REQUEST));
   exit;
}
```
Solution proposed ( find with another problem similar on github whith json an php7) :

```php
function utf8ize($mixed) {
    if (is_array($mixed)) {
        foreach ($mixed as $key => $value) {
            $mixed[$key] = utf8ize($value);
        }
    } else if (is_string ($mixed)) {
            return mb_convert_encoding($mixed, 'UTF-8', 'UTF-8');
    }
    return $mixed;
}

if ($_REQUEST["action"] == "get_events") {
   header("Content-Type: application/json; charset=UTF-8");
   echo json_encode(Planning::constructEventsArray($_REQUEST));
   if (json_last_error()==5)
   { 
            $clean=utf8ize(Planning::constructEventsArray($_REQUEST));
            echo json_encode($clean);
   }
   exit;
}
/*
if ($_REQUEST["action"] == "get_events") {
   header("Content-Type: application/json; charset=UTF-8");
   echo json_encode(Planning::constructEventsArray($_REQUEST));
   exit;
}
*/
```
For us , this solution solved our problem.

**Comment by pedroluisvsousa** [comment]
Likewise for me.

Regards.

**Comment by orthagh** [comment]
I'm not sure i replicate the same issue.

Could you check that you can get the events loading in planning view after displaying them into list view ?
Even with your changes, it seems my issue is still present.
Also you talk about php7, could could specify the full version 7.0.x, 7.1.x, 7.2.x and provide some informations about your environnement (server, os, etc) ?

By the way, i fixed some issues for planning in the incoming 9.4.0 version (beta here https://github.com/glpi-project/glpi/releases/download/9.4.0-rc1/glpi-9.4.0-rc1.tgz if you mind look at your bug with this release).

**Comment by douglascomim** [comment]
Hello,
we also face the same situation presented by @dubreido.
We noticed that when the task text is too large (over 255 chars) and has special characters, the tasks are not listed.

I tested the solution presented by @dubreido, and it worked like magic!

Thanks.

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on GLPI 9.4.0. This may have been fixed.
Feel free to reopen if you are able to reproduce.

Regards
