### ISSUE TITLE
problems with selection criteria

### ISSUE THREAD

**Issue by nfarias1882** [glpi-project/glpi#5141]
Hello good afternoon estimated, along with the health, the time of my life, the search filters in glpi 9.1.7.1, basically when I apply the search criteria: requestor -> is -> I return the load of failure. (
![ssx](https://user-images.githubusercontent.com/46006378/50244771-89f1dc00-03af-11e9-92e6-4c52262e346f.png)
to image).  

I'll thank you very much for sharing a patch or giving me some guidance
greetings I am very attentive

**Comment by Armin83** [comment]
already fixed in newer update please update
