### ISSUE TITLE
[9.4] Private reminder also shows on the panel as a public reminder

### ISSUE THREAD

**Issue by pedroluisvsousa** [glpi-project/glpi#5142]
**Describe the bug**

Private reminder also shows on the panel as a public reminder.

**To reproduce**
1. Create a private reminder
2. Go to home panel
3. See the reminder panels

**Expected behavior**
The private reminder shows only private reminders panel.

**Actual result**
The private reminder shows in both panels: private and public.

**Screenshots**

![screenshot_2018-12-19 glpi - reminders - 1](https://user-images.githubusercontent.com/26510405/50253066-bd406500-03c7-11e9-8b80-5ed9b4faf6ee.png)

![screenshot_2018-12-19 glpi - reminders - 1 1](https://user-images.githubusercontent.com/26510405/50253065-bca7ce80-03c7-11e9-857a-2157936574fd.png)

![screenshot_2018-12-19 glpi - standard interface](https://user-images.githubusercontent.com/26510405/50253064-bca7ce80-03c7-11e9-97ff-c49ae79bc2b2.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.4 beta

**Comment by trasher** [comment]
Could you please try with 9.4.0-rc1? We've fixed several issues, but not sure for this one.

**Comment by cedric-anne** [comment]
Hi,

Could tou test #5157 ?

Regards

**Comment by pedroluisvsousa** [comment]
Great!! That's OK!

Regards
