### ISSUE TITLE
[0.90.1] Still possible to "associate myself" as ticket assignee if ticket deleted

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#515]
Steps to reproduce:
1) user creates a new ticket
2) user notices it's a duplicate and deletes it right away
3) sometime later a tech types in this ticket's number in the URL and sees the ticket as "new". There's no visual hint that it has been deleted
4) however - and this is a bug - the tech can still associate himself as an assignee of this ticket. All other changes are not possible since the save button is missing.

To fix this bug: associate myself should not be possible
Optionally: make it visible that a ticket has been deleted.

**Comment by yllen** [comment]
You can assign to myself and you can delete present users.
