### ISSUE TITLE
Upgrade from 9.3.3 not supported 

### ISSUE THREAD

**Issue by neogorn** [glpi-project/glpi#5152]
Hi!

The proposed solution on #5062 not works for me.

I run _**bin/console db:update --allow-unstable**_, but it appears that "version 9.3.3 is not supported"

![image](https://user-images.githubusercontent.com/42190708/50304754-f89a6c80-0477-11e9-958e-c5e17ecfc11c.png)

Any suggestion?

Tks.

**Comment by trasher** [comment]
Please try with 9.4.0-rc1

**Comment by cedric-anne** [comment]
Hi,

Should be fixed by 938da131a28853469513bd74a72a1e10b65f0a7a, which is included in 9.4.0-rc1.

Regards

**Comment by neogorn** [comment]
> Hi,
> 
> This has been fixed by [938da13](https://github.com/glpi-project/glpi/commit/938da131a28853469513bd74a72a1e10b65f0a7a), which is included in 9.4.0-rc1.
> 
> Regards

@cedric-anne [938da13](https://github.com/glpi-project/glpi/commit/938da131a28853469513bd74a72a1e10b65f0a7a)  this solved for me.

Tks a lot!
