### ISSUE TITLE
[9.4] kb - search in browser tab

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#5153]
**Describe the bug**
search don't work in faq / browser

**Page(s) URL**
http://192.168.1.108/front/knowbaseitem.php

**To reproduce**
go to Home - Tools - Knowledge base
click  tab browse
search for category not possible. (the search works only in glpi debug mode)

**Expected behavior**
i can search for category

**Logs**
```
nothing all empty


**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

Add any other context about the problem here.

**Comment by trasher** [comment]
Were you using the 9.4.0-beta? We've just released a rc1 with latests fixes.

**Comment by cedric-anne** [comment]
Hi @Armin83,

In a previous version of this feature, search was done using an ajax request, so it was performed only if, at least, 3 chars were typed in the search box.

As all the tree is loaded when tree is display, search does not requires anymore an ajax call so I removed this "3 chars" constraint in #5154 .

Could you test the fix ?

Regards

**Comment by Armin83** [comment]
@trasher on my dev system. yesterday i downloaded not the beta because 14 days old. i take the github direct download. yes i know a bad descision but i only want to take a look with the latest fixes. i did plan to test or open a case. but this litle thing a thought it could not a problem with the dev tools and so on and otherwise you could fast test it and close this issue.

**Comment by Armin83** [comment]
@cedric-anne 
I go back to my clean 9.3.3 vm os snapshot.
Download & install rc1
integrate your patch
test & thanks it works fine

**Comment by trasher** [comment]
Thanks for the feedback @Armin83 

>  yes i know a bad descision 
No, no, you did right :) Many bugs has been fixed since beta ;)
