### ISSUE TITLE
Switch to PDO

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#5156]
Use PDO instead of mysqli.

**Comment by jasorlando** [comment]
A

**Comment by henriquearthur** [comment]
@jasorlando @trasher https://github.com/jasorlando/glpi/commit/3ced35b056c5c8df554ab59a08207cb5d5efa170 does this mean thw switch to PDO is done? Are we gonna be able to use another DBMS once this is merged?

**Comment by trasher** [comment]
No, switch to PDO is not done.
