### ISSUE TITLE
GLPI 9.4 New WEB UI Interface

### ISSUE THREAD

**Issue by sworlls** [glpi-project/glpi#5159]
Hello Dev Team, 
It would be fantastic if you could create a new WEB UI Interface, i see GLPI as a fantastic tool with so many opportunities, but at other side the interface for admin and users (Not Customer) is quietly confused, not intuitive as other tools. With a new interface with more intuitive buttons, text area, labels, etc. this would make the tool easier to work.
Thank about that.
thank you

**Comment by trasher** [comment]
We are going to change a lot of thing with the 10 release; including UI.
