### ISSUE TITLE
problem closure

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5160]
Hello

GLpi 9.3.2 / mariadb / windows 2012 server

When I want to solve a problem I have a message "you can't close this problem without solution type"

Even if I select (closed solved or closed not solved) I have this message.

I can force closure directly in database.

Thank you for your help

**Comment by Armin83** [comment]
do you use plugin behaviour ? (check the settings from plugin)

**Comment by yalgva** [comment]
yes

**Comment by yalgva** [comment]
I selected no and it is ok 

thx
