### ISSUE TITLE
with ' at each time we have ////// added

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5173]
Hello

glpi 9.3.2

with ' at each time we have ////// added in title or description.

Thank you

**Comment by yalgva** [comment]
Hello, have a nice year !

Please, could you explain why it is invalid ?

**Comment by trasher** [comment]
You did not provide requested informations. See https://github.com/glpi-project/glpi/blob/9.4/bugfixes/CONTRIBUTING.md#bugs

**Comment by yalgva** [comment]
Hello I am sorry but I don't see what is missing
glpi 9.3.2 
Which information do you need ?

Thank you for your help
