### ISSUE TITLE
requete mysql une aide serait très appréciée. merci

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5177]
Bonjour

J'ai une anomalie sur des tickets clos qui n'ont pas de groupe de techniciens, de ce fait les statistiques de l'année sont faussées.

Pour corriger cela j'aurai besoin d'une requete sql pour sélectionner les tickets sans groupe de technicien afin de pouvoir entrer dans la base le groupe correspondant.

Il faut également que le technicien attribué soit affiché afin que je puisse déterminer quelle groupe attribuer

Pourriez vous m'aider svp.

glpi_tickets
glpi_groups
glpi_groups_tickets

**Comment by yalgva** [comment]
J'ai tenté ca mais mysql part dans les choux

SELECT t0.date
        ,closedate
        ,status
        ,CONCAT(`realname`, ' ', `firstname`) AS Technicien
       ,t4.groups_id as Groupe
FROM glpi_tickets as t0
    ,glpi_users as t2
    ,glpi_tickets_users as t3
    ,glpi_groups as t4
    ,glpi_groups_tickets
    left join glpi_groups_tickets on t0.id = t5.tickets_id
WHERE t3.users_id = t2.id
    AND t3.type = 2
    AND t3.users_ID = 799
    AND t0.id = t5.tickets_id
    
    ORDER BY groupe

**Comment by yalgva** [comment]
SELECT t0.date
        ,closedate
        ,status
        ,CONCAT(`realname`, ' ', `firstname`) AS Technicien
       ,t4.groups_id as Groupe
FROM glpi_tickets as t0
    ,glpi_users as t2
    ,glpi_tickets_users as t3
    ,glpi_groups as t4
    ,glpi_groups_tickets as t5
    left join glpi_groups_tickets on t0.id = t5.tickets_id
WHERE t0.id = t5.tickets_id
    AND t3.users_id = t2.id
    AND t3.type = 2
    AND t3.users_ID = 799
    
    ORDER BY groupe
et la j'ai t0_id  unknown column 't0.id' in on clause

**Comment by yalgva** [comment]
encore un essai et part dans les choux

SELECT t1.date
        ,closedate
        ,status
        ,CONCAT(`realname`, ' ', `firstname`) AS Technicien
       ,t4.groups_id as Groupe
FROM (glpi_tickets as t1
    ,glpi_users as t2
    ,glpi_tickets_users as t3
    ,glpi_groups as t4
    ,glpi_groups_tickets as t5)
LEFT JOIN glpi_groups_tickets on t1.ID = t5.tickets_id
LEFT JOIN glpi_tickets_users on t3.users_id = t2.id
WHERE t3.type = 2
    AND t3.users_ID = 799
	 and not exists (SELECT * 
		FROM glpi_groups
		WHERE glpi_groups_tickets.tickets_id = t1.id)

**Comment by trasher** [comment]
Please:
- use **only english**,
- use forums for user support.

Regards.

**Comment by yalgva** [comment]
thx for your help !!!
