### ISSUE TITLE
[last Git version] *** PHP Warning(2): Invalid argument supplied for foreach() when i add a ticket

### ISSUE THREAD

**Issue by Manu1400** [glpi-project/glpi#518]
Steps to reproduce issue : 
1/ Install the last commit of GLPI (empty GLPI - no data in database)
2/ Logging with 'glpi' user
3/ Activate Debug Mode (in your User preference)
3/ Page "Create a new ticket" (go to this page from menu)
4/ In form for create a new ticket, put a simple description in description textearea (ie : 'description' string)
5/ Click on "Add" button (for create ticket).

A PHP error is displayed, and i have in php log : 

```
2016-03-08 16:28:16 [2@master-ubuntu15]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc/ticket.class.php:1368                          
  inc/commondbtm.class.php:799                       Ticket->prepareInputForAdd()
  front/ticket.form.php:50                           CommonDBTM->add()
```

And code is added by @korial29 in commit b8fcf32650bd5df985381e69c05bc68f3bac58df

**Comment by Manu1400** [comment]
```
var_dump($input['items_id']);
```

retourne 
```
string '0' (length=1)
```

**Comment by yllen** [comment]
Can you try the correction purposed?

**Comment by orthagh** [comment]
No answers since days, i close
