### ISSUE TITLE
9.1.3 queuedmail does not execute

### ISSUE THREAD

**Issue by taiuan99** [glpi-project/glpi#5194]
9.1.3 queuedmail does not execute

**Comment by orthagh** [comment]
Hello dear user.

We are not seer or witch doctor, and you should probably have an issue but with this poor report, i'm afraid we can't help you as we can't see through the Internets to check you instance.

More, we provide a template you should use when creating an issue, asking for glpi configuration, logs, etc.

Bref, i close
