### ISSUE TITLE
Add a parameter in config to show satisfaction in central

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#52]
https://forge.glpi-project.org/issues/5323

**Comment by orthagh** [comment]
Suggestion: don't list suvey for user_id_recipient (only for requester)

**Comment by yllen** [comment]
the request was originally: "the technician who created the ticket to remember it to call requester".
With your proposal doesn't match.
For me the solution is to added a new parameter to show or not.

**Comment by orthagh** [comment]
ok. So next version.
It can be dev in a fork/pr

**Comment by yllen** [comment]
Add 3 values for the parameter:
- NO
- Yes at the begining
- Yes at the end
The 2 last parameters is for order of array in central

**Comment by yllen** [comment]
Now you have a parameter to allow technician to reply or not to satisfaction.
This issue is not useful.
