### ISSUE TITLE
Logs of a cloned object (by an entity transfer) should states it is a clone

### ISSUE THREAD

**Issue by C-Duv** [glpi-project/glpi#520]
When the entity transfer wizard is cloning objets, an explicit "_Cloning from object x_" event should be added to clone object's logs.

I got into this when transferring a computer to another entity. That computer was attached to documents (and contracts) which where cloned into the destination entity.
### Steps to reproduce (my experience, variations may also works)
- Have the following entities:
  - Entity _E1_
  - Entity _E2_ (as a sub-entity of _E1_)
- Create computer _C1_ into entity _E1_
- Create computer _C2_ into entity _E1_
- Create document _D_ into entity _E1_ (ID=726, used below)
- Attach document _D_ to computers _C1_ and _C2_
- Transfer _C1_ to entity _E2_
### Actual result

Computer _C1_ is now into entity _E2_.
A new document _D'_ is created into entity _E2_ as a copy/clone of document _D_ (the latter stays in _E1_) with ID=727 (in my example)
While cloning the document _D_, GLPI clones _D_'s logs: it creates new events rows with new IDs keeping the original dates and other informations, but it alos adds two new events "Add the item" and "Change Entity E1 (0) by Entity E1 > Entity E2 (1)" timestamped at the date the transfer was performed.

Logs of _D_:

```
8641    2016-03-09 10:54    User (8)    Computer    Add a link with an item: Test computer2 for entity transfer (409)
8625    2016-03-09 10:46    User (8)    Computer    Add a link with an item: Test computer1 for entity transfer (408)
8624    2016-03-09 10:45    User (8)    -   Add the item
```

Logs of _D'_:

```
9320    2016-03-09 11:00    User (8)    Entity  Change Entité racine (0) by Entité racine > FooBar (1)
9319    2016-03-09 10:54    User (8)    Computer    Add a link with an item: Test computer2 for entity transfer (409)
9316    2016-03-09 10:46    User (8)    Computer    Add a link with an item: Test computer1 for entity transfer (408)
9315    2016-03-09 10:45    User (8)    -   Add the item
9314    2016-03-09 11:00    User (8)    -   Add the item
```

We see that events 8624, 8625 and 8641 gets copied to _D'_ as-is (respectively as 9315, 9316 and 9319) and that events 9314 and 9320 are added.
### Proposition

I suggest that logs of that _D'_ object states it was created as a clone of _D_.
The Event 9314's label should be "Create the item as a clone of Document 726" or something similar.
### Context informations

GLPI version: 0.90.1

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards

**Comment by C-Duv** [comment]
I understand, here is it: [Logs of a cloned object (by an entity transfer) should states it is a clone](https://glpi.userecho.com/communities/1/topics/1006-logs-of-a-cloned-object-by-an-entity-transfer-should-states-it-is-a-clone)
