### ISSUE TITLE
Ticket parent and tickets son

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5206]
In linked tickets part of a ticket there are Parent of and Son of options.
If i understand correctly https://github.com/glpi-project/glpi/issues/909 when you close the parent ticket all son tickets will be closed automatically.

Tests done:
- change status of parent ticket to close -> son tickets are not closed
- change configuration of my entity for closing ticket immediately after solved status. Add a solution in parent ticket -> son tickets are not closed

**Comment by orthagh** [comment]
No currently, this type of link is only informative.

The only behavior existing  is when you display the solution form on the parent ticket, a message will warn you that the current ticket have some children still opened.

Also, we use the relation also in formcreator plugin, we can generate relation between target tickets of a form.

Nothing more currently but i plan to add some criteria and actions in a short future in the ticket business rule engine.

I close for the moment, but feel free to comment or add suggestions if you want.

**Comment by yllen** [comment]
Thanks @orthagh for explanation.
But message is strange because you ask "Are you sure you want to close it?" when you add a solution.
Adding a solution doesn't close a ticket...
And can we have also the message when you change state of the parent ticket?
