### ISSUE TITLE
if a ' in a followup by email => erreur addtodb

### ISSUE THREAD

**Issue by robertdelamancha** [glpi-project/glpi#521]
hi, 
glpi 0.90.1
when a user response by email from followup and  there are ' in response, the email is in error in mail_gate.

The error  is from addtodb function the ' is not replace par \'

INSERT INTO `glpi_ticketfollowups` (`content`,`tickets_id`,`users_id`,`requesttypes_id`,`is_private`,`date`) VALUES ('c'et fait.\n\nxxx xxxLe 8 mars 2016 Ã  19:52, \n\n \n\n','3638','164','2',0,'2016-03-09 12:18:56')
erreur addToDB

thks 

--

**Comment by robertdelamancha** [comment]
In ticketfollowup.class.php
i add  after the test for use_tich_text

$input["content"] = str_replace("'","\'",$input["content"]);

thks

**Comment by pgnlog** [comment]
Hello

I'm facing the same issue but I'm unable to locate this line "$fup = new TicketFollowup();" in ticketfollowup.class.php.

We are using GLPI 0.90. 

ticketfollowup.class.php is both  similar in 0.90 and 0.90.1

TIA.

Patrick.

**Comment by tomolimo** [comment]
Hello,
It has been fixed there: https://github.com/glpi-project/glpi/commit/3ded427fda2de86236a3dca0c53ba481f2a0a5bf#diff-bb7c2f434e967018d0af7b0789728933
So either you wait for 0.90.2 release, or you change it directly into file.
Regards,
Tomolimo

**Comment by yllen** [comment]
@tomolimo i think your post is for document added in the follow up not for the content of follow up
But you have right, this bug was fixed https://github.com/glpi-project/glpi/commit/3dc868c07722f9b7e6b9bbd7d7e51e48b358c845

**Comment by robertdelamancha** [comment]
no, il have the error when i add  à follow up by  mai but It is possible that my  signature is detect as document.

**Comment by robertdelamancha** [comment]
pgnlog , 

In **mailcollector.class** not  ticketfollowup.class.php

i add after : $fup = new TicketFollowup();

> $tkt['content'] = utf8_decode(str_replace("'","\'",html_entity_decode($tkt['content'],ENT_QUOTES)))

thks

**Comment by guillermohaad** [comment]
Thank you robertdelamancha, you're a genius friend...

**Comment by orthagh** [comment]
fixed in 0.90.2 by 3ded427 commit, i close
