### ISSUE TITLE
Rework gantt display

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5212]
https://forum.glpi-project.org/viewtopic.php?id=165504

**Comment by orthagh** [comment]
I transform your issue in feature suggestion as this is planned (i tag it in roadmap).
We need to completly replace the gantt library (which is pretty outdated) by someone permitting to edit/move task directrly.

Some examples:
- https://frappe.io/gantt
- https://github.com/robicch/jQueryGantt
- https://oguzhanoya.github.io/jquery-gantt/

**Comment by cedric-anne** [comment]
Already done.
