### ISSUE TITLE
[9.4] An user with Admin profile is not able to change his password

### ISSUE THREAD

**Issue by ConteZero** [glpi-project/glpi#5214]
In GLPI version 9.4 RC1 an user with Admin profile is not able to change his password from /front/user.form.php page.
This is caused by 2 missing inserts in glpi_profilerights table from glpi-empty.sql, global_validation and rule_asset are not present into the table and this is the cause of the problem.
Manually adding them to glpi_profilerights fixes the bug.

I've created a new profile with the same permissions of Admin default profile and looking at the result of

SELECT * FROM `glpi_profilerights` WHERE `profiles_id`= 3;

and comparing with the same query repeated for the newly created profile there are many differences into the values.

For example for Admin you have

datacenter 	255

instead for the other profile you have

datacenter 	31

this means that the Admin has permissions on 'Read notes' 'Update notes' 'Select/unselect all' that are not enabled on the other profile.
'Read notes' and 'Update notes' are not selectable from the interface and 'Select/unselect all' should only be a javascript function to enable the full row.

From my point of view, having these differences into the database could potentially impact functions that compare profiles permissions and could cause unexpected results.
The same inconsistencies in default permissions values are present also for other profile created by glpi-empty.sql file.
I think that this problem is also related with the issue https://github.com/glpi-project/glpi/issues/5098

**Comment by cconard96** [comment]
Related to my comment in #5098 . I am trying to look into the rights discrepancies for the default profiles.

**Comment by cconard96** [comment]
Actually, not sure the issues are related. Seems like a UI inconsistency between /front/user.form.php and /front/preference.php when editing your own user.

**Comment by ConteZero** [comment]
function currentUserHaveMoreRightThan in /inc/profile.class uses getUnderActiveProfileRestrictCriteria that gives not correct results with current default profiles created by installer.
The discrepancies for the default profiles have effect also on new user creation, in my config I have the default Admin profile and a newly create profile (AdminTest) with the same permissions:
- Admin is able to create a new user with Admin or AdminTest profiles
- AdminTest is able to create a new user with AdminTest profile but not with Admin profile
