### ISSUE TITLE
GLPI Cluster Support

### ISSUE THREAD

**Issue by Greenstonetr** [glpi-project/glpi#5217]
Can GLPI cluster work?
Anybody running?

**Comment by orthagh** [comment]
I redirect you to the [suggest website](suggest.glpi-project.org) and this [topic](https://glpi.userecho.com/communities/1/topics/942-multi-instance-of-glpi-with-database-synchronization) where we talked about replication and mysql cluster.

but here is shot answer: yes, you can have a cluster system to serve GLPI application. It's an ops topic and not a dev one. As GLPI is a mysql-php-html application, no difficulty will be on GLPI side, just search about mysql replication / cluster topic on google and it's probably applicable
