### ISSUE TITLE
special chars not working in csv export file

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#522]
Hi,

When i export in csv file (ex: computers), the special chars are not translate correctly in csv.

Example: 
In GLPI:
```
Root entity > entity A > entity AA
```

Become this in csv export file : 
```
Root entity &gt; entity A &gt; entity AA
```

Thanks to solve it.

++

**Comment by tsmr** [comment]
already corrected https://github.com/glpi-project/glpi/issues/470

**Comment by barbuslex** [comment]
Ok thanks
