### ISSUE TITLE
[9.4 RC1] Calendar widget shows unnecessary second, milisecond, microsecond and timezone rows

### ISSUE THREAD

**Issue by shoothub** [glpi-project/glpi#5220]
**Calendar widget shows unnecessary rows**

Calendar widget shows unnecessary second, milisecond, mikrosecond and timezone rows, which is not used at all, only use space. Please hide/remove this rows, as it is useless.

**Page(s) URL**
All pages where you can input date (calendar icon next input)

**To reproduce**

1. Go for example to 'Assistance - Create ticket'
2. Click on calendar icon next to 'Opening date'
3. Rows: Second, Milisecond, Microsecond and Time Zone are useless in calendar widget
4. See widget

**Expected behavior**

Hide/remove rows `Second, Milisecond, Microsecond and Time Zone` which aren't used at all.

**Screenshots**

![screenshot from 2019-01-09 14-33-00](https://user-images.githubusercontent.com/28008456/50903011-d499cd80-141c-11e9-9701-23796d55b02c.png)

**GLPI setup**

```
GLPI 9.4 RC1, using remi collet rpm: glpi-9.4.0~RC1-2.el7.remi.noarch
```

**Comment by orthagh** [comment]
Hello @shoothub 

Already fixed in 9.4/bugfixes branch, see https://github.com/glpi-project/glpi/pull/5187
