### ISSUE TITLE
glpi_networkequipmentfirmwares doesn't exist

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#5232]
Hi,

Have just tried to run /usr/share/glpi/scripts/add_creation_date.php against our GLPI v9.3.3 but it fell over:

`DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: UPDATE glpi_networkequipmentfirmwares
             LEFT JOIN (
               SELECT max(`id`), `date_mod`, `itemtype`, `items_id`
               FROM  glpi_logs
               GROUP BY itemtype, items_id
             ) as logs
               ON `logs`.`itemtype` = 'NetworkEquipmentFirmware'
               AND `logs`.`items_id` = `glpi_networkequipmentfirmwares`.`id`
            SET  `glpi_networkequipmentfirmwares`.`date_mod` = `logs`.`date_mod` WHERE `glpi_networkequipmentfirmwares`.`date_mod` IS NULL
  Error: Table 'glpi.glpi_networkequipmentfirmwares' doesn't exist
  Backtrace :
  inc/dbmysql.class.php:206                          
  scripts/add_creation_date.php:79                   DBmysql->queryOrDie()`

I inspected our schema, and this table doesn't exist in our GLPI. None of my users have encountered a problem from the front-end accessing network equipment asset info.
Should this table really exist or not?

**Comment by hgpit** [comment]
I just checked a 9.3.2 and a 9.2.1 install we have, and this table exists in none of them.

**Comment by trasher** [comment]
This table does not exists; this should have been fixed for 9.4 already: `bin/console glpi:migration:build_missing_timestamps`
