### ISSUE TITLE
Selecting a category gives you a different Ticket Template

### ISSUE THREAD

**Issue by LuminousWing** [glpi-project/glpi#5236]
**Describe the bug**

While creating a new ticket, using a custom temlate (Default still exists), when selecting a category, a full page refresh happens and it suddenly loads a different template.

**Page(s) URL**

glpi/front/ticket.form.php

**To reproduce**

1. Go to 'Create Ticket'
2. Click on 'category.'
3. Select any category
4. GLPI will do a full page refresh and load a different ticket template

**Comment by trasher** [comment]
Yes, this is the expected behavior.

**Comment by LuminousWing** [comment]
But it's not supposed to load a whole different template, is it? That makes no sense.
Fields I've hidden on the template I want to use, suddenly show up after selecting a category because it loads a different template.

**Comment by trasher** [comment]
Sounds like an usage issue; please use [forums](http://forum.glpi-project.org) to get support.
