### ISSUE TITLE
Add an item' to Documents shows Items options in select for profiles without permissions on Assets

### ISSUE THREAD

**Issue by ConteZero** [glpi-project/glpi#5243]
GLPI version 9.4 RC1
- Login with an user with all permissions on documents but without permissions on Assets.
- Go to Documents, select a document from the list and click on 'Associated items' tab.
- The 'Add' select shows many options related to assets like 'Item - Battery link', 'Item - Case link', etc...

I don't know if this is the expected behavior, but if the user has no permissions on Assets I think that these option should not appear into the Select.

**Comment by trasher** [comment]
Could you check if that was already th case on 9.3? Not sure this is 9.4 specific;

**Comment by ConteZero** [comment]
Actually I've only a test install with 9.4, I'm a 'new' GLPI user...

**Comment by ConteZero** [comment]
It's not possible to replicate in https://demo.glpi-project.org because there are no profiles with permissions on Documents and without permissions on Assets.

**Comment by ConteZero** [comment]
I've found another unexpected result related to Assets permissions, an user without permissions on assets but with permissions on Users can view the tabs 'Used items' and 'Managed items' on user.form.php page, these tabs should not be hidden for his profile?
