### ISSUE TITLE
No search option for ID in profile itemtype

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#5245]
Hi

I'm building a tool which consules the API ogf GLPI.

I noticed that when I do a Search on the Profile itemtype I'm unable to get the ID of the profiles returned. 

There is no search option for this data, and the search option 2, usually dedicated to the ID,  is used for something else.

**Comment by btry** [comment]
@trasher @cedric-anne @orthagh 

I think that we should move the search option 2 to an other number. What do you think ?

**Comment by orthagh** [comment]
agreed

**Comment by trasher** [comment]
This needs an update script, but ok for me :)

**Comment by cedric-anne** [comment]
Closed by cf74ecec87e49973ca420538c270cc7e3100a513.
