### ISSUE TITLE
Allowed memory size exhausted

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5248]
Hello,

glpi 9.3.2 maria db ,php 7.2

PHP Notice: Undefined variable: footer_string in C:\inetpub\wwwroot\inc\notificationtemplate.class.php at line 308

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 15198848 bytes) in C:\inetpub\wwwroot\inc\dbmysql.class.php on line 903

Thank you

**Comment by yalgva** [comment]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 15189192 bytes) in C:\inetpub\wwwroot\inc\html.class.php on line 69

i can't see anymore in GLPI with any request

**Comment by trasher** [comment]
try to **remove all,plugins** and disable stuff like xdebug etc on your server.

**Comment by yalgva** [comment]
I have this message Redémarrage pour cause de mémoire saturée (restart because of memory )

**Comment by yalgva** [comment]
![image](https://user-images.githubusercontent.com/30655170/51109760-7d1da800-17f6-11e9-82ce-00601dcca4b8.png)

**Comment by yalgva** [comment]
I put memory_limit = -1  and I can see the list of new tickets, but it is very slow

**Comment by yalgva** [comment]
I have uninstalled all plugins, same behavior

**Comment by trasher** [comment]
Well, since you did ot provide any details on what you are trying to do, what you have, etc, etc; it's impossible to say.
You have something in your data that is not correct, this may be a bug, or this may be something wrong in your data (corruption, failed upgrade, ...,, ..., ...).

You'll have to investigate on your side to understand what goes wrong; since this only appears on your instance (ie not on demo or my local instance; or several other users with very huge databases).

**Comment by yalgva** [comment]
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 7594171 bytes) in C:\inetpub\wwwroot\lib\htmlawed\htmLawed.php on line 428

**Comment by yalgva** [comment]
Ok, I have tried to investigate but I did not make any change, so I would like to have a clue to find where the issue comes from please

**Comment by trasher** [comment]
«You have something in your data that is not correct»

**Comment by trasher** [comment]
You are the only one that kkonw where your issue happens.

**Comment by yalgva** [comment]
What do you mean about data ?
This line explains a fatal error so it should come from glpi

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 15189192 bytes) in C:\inetpub\wwwroot\inc\html.class.php on line 69

**Comment by yalgva** [comment]
Is it possible that it is an image in description ? because I saw just before midday a ticket with screenshot and the description is with many characters instead of the pic

**Comment by yalgva** [comment]
The issue came from 7 tickets with a screenshot.
The screenshot description contains characters instead of the screenshot.
I deleted these tickets and it comes back to normal

**Comment by cedric-anne** [comment]
No,

If you want to get latests fixes, just upgrade to last version of GLPI (9.3.3).

Regards

**Comment by yalgva** [comment]
Ok thank you so much for your help, I have planned an update for next thirsday.
