### ISSUE TITLE
Ticket with same titles are being merged

### ISSUE THREAD

**Issue by LuminousWing** [glpi-project/glpi#5254]
**Describe the bug**

When a ticket exists with Title A and a new ticket is made with the same title, both tickets ends up being merged even if they're completely different and made by different users.

**To reproduce**

1. Create ticket with any name.
2. Create another ticket with only the same name
3. Tickts will be merged even if made by other users.

Not sure if reported already and/or fixed, if so please excuse me.

**Comment by LuminousWing** [comment]
Cannot reproduce anymore, guess it was a weird occurence.

**Comment by tomolimo** [comment]
Hello @LuminousWing 

1. Are you using Outlook?
1. Are you using MailAnalyzer plugin?

Thank you
Tomolimo

**Comment by LuminousWing** [comment]
@tomolimo I am not using either, these tickets were made using the ticket form of glpi.
