### ISSUE TITLE
Enable/Disable maintenance mode from the cli console

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#5256]
**Describe the solution you'd like**

Enable/Disable maintenance mode from the cli console, maybe like Nextcloud OCC command.

``bin/console glpi:maintenance:mode --on``

``bin/console glpi:maintenance:mode --off``

**Comment by sebma** [comment]
@trasher Hi, does this new `php bin/console glpi:maintenance:enable` command stop the Cron tasks ?

**Comment by cedric-anne** [comment]
Maintenance mode is supposed to block cron tasks execution, indeed.
