### ISSUE TITLE
Knowlegde Base - See all articles in SuperAdmin

### ISSUE THREAD

**Issue by ropie** [glpi-project/glpi#526]
Hello,
The problem is if an article was written by the SuperAdmin and the target don't contain the profile Super Admin, the article dissepear for the Super Admin.
He have to change profile to see the article even if he is the redactor.

I think that the Super Admin does have the right all the articles no?

Thks

**Comment by yllen** [comment]
Super-admin must have right "Knowledge base administration" in his profile to see all articles.
He can see article reading by him in manage tab.
