### ISSUE TITLE
My glpi user does not receive notifications when opening a ticket by email

### ISSUE THREAD

**Issue by victoria1984** [glpi-project/glpi#5262]
Hi all,
I need help with a problem.
I'm using the version of glpi 9.3.2 and I have notifications configured to be sent when I open a ticket. I have tried them with the portal and everything goes ok, but when I open a ticket by email, if the sender's mail belongs to a user of glpi, he does not send any notification.
Example: If I open a ticket from my gmail, my email address is stored in my user of glpi, I do not receive notifications, however when I do the same test from my outlook account that does not belong to any user of glpi if I receive notifications.
Could you explain why it happens and how can I solve it?

Thank you.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
