### ISSUE TITLE
Can't see users at imported domain group

### ISSUE THREAD

**Issue by licz83** [glpi-project/glpi#5266]
Hello,

I have connected GLPI to domain and I am able to import group from it. But I don't see users of the domain group. Could you please help and tell me what is wrong?
![obrazek](https://user-images.githubusercontent.com/46780630/51313748-9e78d100-1a4e-11e9-8a57-8727ba1159b3.png)

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
