### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#5269]
This is a very huge task.

- [ ] switch to PDO (see #5156)
- [ ] insert data from php (see #5268)
- [ ] convert installation script to postgresql (or find a way to get table creation scripted...)
- [ ] improve dbiterator so it natively supports SQL functions (may differ beetween mysql and postgres)
- [ ] convert all direct SQL functions to iterator equivalents
- [ ] improve data types in GLPI code
- [ ] maybe rework GROUP (well... among others...) usage, since PostgreSQL will not be tolerant

**Comment by redddcyclone** [comment]
Hi @trasher 

Are there any plans for this to be done yet?

**Comment by cconard96** [comment]
> Hi @trasher
> 
> Are there any plans for this to be done yet?

There is still work needed to be done to make the SQL queries more generic to work with different database types and moving away from raw queries in general but there is active work being done on that.

https://github.com/glpi-project/glpi/pulls?q=is%3Apr+is%3Aclosed+author%3Acconard96+sql+function+replace
https://github.com/glpi-project/glpi/pulls?q=is%3Apr+is%3Aclosed+author%3Acconard96+dbal
