### ISSUE TITLE
After update to 9.3.3/9.4.0, problem with rights (users can see all tickets)

### ISSUE THREAD

**Issue by msizec** [glpi-project/glpi#5270]
hello,

as said in title, now when accessing tickets' list, they see all 'not closed' tickets.
Before, and Ive tested it using our old VM, the tickets' list contained only 'not closed' user's tickets 

Ive looked at rights for profiles, and post'only does not have the right to see "all the tickets"

**Comment by msizec** [comment]
Is it possible that we're the only ones facing this issue ?
How can I check if this is a bug ? 

I did activate the debug mode for user 'glpi', I activate the profile 'post-only' for user glpi, Ive load the url **http://glpi/front/ticket.php** then I searched for the sql request for tickets (see above). is there something wrong ?


```
SELECT DISTINCT `glpi_tickets`.`id` AS id, 'glpi' AS currentuser, `glpi_tickets`.`id` AS `ITEM_0`, `glpi_tickets`.`name` AS `ITEM_1`, `glpi_tickets`.`id` AS `ITEM_1_id`, `glpi_tickets`.`id` AS `ITEM_1_id`, `glpi_tickets`.`content` AS `ITEM_1_content`, `glpi_tickets`.`status` AS `ITEM_1_status`, `glpi_tickets`.`date` AS `ITEM_2`, `glpi_users_users_id_recipient`.`name` AS `ITEM_3`, `glpi_users_users_id_recipient`.`realname` AS `ITEM_3_realname`, `glpi_users_users_id_recipient`.`id` AS `ITEM_3_id`, `glpi_users_users_id_recipient`.`firstname` AS `ITEM_3_firstname`, GROUP_CONCAT(DISTINCT `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` SEPARATOR '$$##$$') AS `ITEM_4`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id`, ' ', `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_4_2`, `glpi_tickets`.`priority` AS `ITEM_5`, `glpi_itilcategories`.`completename` AS `ITEM_6`, `glpi_tickets`.`status` AS `ITEM_7`, `glpi_tickets`.`solvedate` AS `ITEM_8`, `glpi_locations`.`completename` AS `ITEM_9`, `glpi_tickets`.`date_mod` AS `ITEM_10` 
FROM `glpi_tickets` 
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 ) 
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 ) 
LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b` ON (`glpi_tickets`.`id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )
LEFT JOIN `glpi_users` AS `glpi_users_users_id_recipient` ON (`glpi_tickets`.`users_id_recipient` = `glpi_users_users_id_recipient`.`id` )
LEFT JOIN `glpi_users` AS `glpi_users_a5e2026cbcb683e774f93a59e24a62a4` ON (`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id` = `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` )
LEFT JOIN `glpi_itilcategories` ON (`glpi_tickets`.`itilcategories_id` = `glpi_itilcategories`.`id` )
LEFT JOIN `glpi_locations` ON (`glpi_tickets`.`locations_id` = `glpi_locations`.`id` ) 
WHERE `glpi_tickets`.`is_deleted` = 0 AND ( `glpi_tickets`.`status` IN ('1','2','3','4') AND (`glpi_itilcategories`.`id` IN ('6','40','7','8','9','35','10','11','42','33','32','39','38','41')) OR `glpi_tickets`.`status` IN ('1','2','3','4') AND (`glpi_itilcategories`.`id` IN ('36','37','43')) ) GROUP BY `glpi_tickets`.`id` 
ORDER BY ITEM_10 DESC
```

**Comment by eyaz86** [comment]
I want see all videos

**Comment by msizec** [comment]
Could someone answer me ... I don't really know if this is a bug, but it really semmes like one ...
but nobody seems to react so does it mean no one experienced the same bug ?

**Comment by msizec** [comment]
Still the same in 9.4.0

With default filter, when listing tickets, all are visible (but I can't access them)
![image](https://user-images.githubusercontent.com/29256398/53002201-65a49100-342c-11e9-846a-0eeab8f2bfcd.png)

With a filter on tickets the user created (still not closed), there is 0 tickets 
![image](https://user-images.githubusercontent.com/29256398/53002429-f5e2d600-342c-11e9-86c9-1c5203225309.png)


here is the profil configuration : 
![image](https://user-images.githubusercontent.com/29256398/53002266-997fb680-342c-11e9-9b69-938bdb56bb01.png)

**Comment by msizec** [comment]
Just looked à the sql database, glpi_profilerights table.
For post-only, profiles_id 1, 'ticket' right is set to 5 (see my tickets and create ticket).
Despite this, when listing tickets with post-only profile, users can see all tickets, opened by anybody ...

**Comment by cedric-anne** [comment]
Hi,

I just checked on current state of 9.4/bubfixes and on [demo website](https://demo.glpi-project.org/) and I cannot reproduce your issue.

Regards

**Comment by msizec** [comment]
My bad, thanks for your time. 
Heres the explanation : upon activating aclcategory plugin, you need to define all the right to each category, if you don't, everybody can see everything (in tickets' list, no access to tickets' details)

Heres a googd example of how to loose precious time ...
