### ISSUE TITLE
missing update_090_0901.php from branch 0.90/bugfixes

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#528]
Hi i want to make an upgrade to last version of 0.90/bugfixes but GLPI can't find update_090_0901.php from .../install

PHP Warning: include(update_090_0902.php): failed to open stream: No such file or directory in /var/www/glpi/install/update.php at line 787
PHP Warning: include(): Failed opening 'update_090_0902.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/glpi/install/update.php at line 787
Fatal error: Call to undefined function update090to0902() in /var/www/glpi/install/update.php on line 788

**Comment by yllen** [comment]
Always corrected:
https://github.com/glpi-project/glpi/commit/3414eec4a05fb1e23b92253b94218c6cf6ba25ca
https://github.com/glpi-project/glpi/commit/d467f166fa4eab4df88d85c65b5adff5e73b6ff8
https://github.com/glpi-project/glpi/commit/9dfe501affef56ad75e53124d5e262f4483fe556

**Comment by Sismic** [comment]
Hi Yllen, sorry but i don't see file file** update_090_0902.php** in **install **directory

**Comment by yllen** [comment]
You don't need this file.
Now you have update_090_0901.php and update_0901_0902.php
