### ISSUE TITLE
Savedsearches exposed ?

### ISSUE THREAD

**Issue by msizec** [glpi-project/glpi#5285]
hello

don't know if this is a bug but now in 9.3.3 theres a way to see all the savedsearches (from all users)
even in post-only, I can see them all (but can't access to the details).

Is it on purpose ?

this seems like the other issue Ive created ( https://github.com/glpi-project/glpi/issues/5270 ) where all the tickets can be seen

**Comment by cedric-anne** [comment]
Hi,

I just checked on current state of 9.4/bubfixes and on [demo website](https://demo.glpi-project.org/) and I cannot reproduce your issue.

Regards

**Comment by trasher** [comment]
9.3 is no longer maintained, please test on 9.4 (demo may be a good place). Closing for now
