### ISSUE TITLE
PHP Array to string conversion in History tab

### ISSUE THREAD

**Issue by hackman61** [glpi-project/glpi#5294]
**Describe the bug**

Hello,
I don't know how to reopen a bug, but I have the same problem like this one #3214

Feel free to close this bug if we can reopen #3214

Thank you !

**Comment by trasher** [comment]
Hi, 9.2.1 is out of date, 9.4 will be released soon and current stable is 9.3.3.

Do not open new tickets; you can still comment on closed ones.
