### ISSUE TITLE
Wrong API error message when App-Token is invalid

### ISSUE THREAD

**Issue by mohierf** [glpi-project/glpi#5295]
On API *initSession* request when the App-Token is not valid, the error message is not correctly translated in Franch:

```
le paramètre user_token semble incorrect; Afficher la documentation dans votre navigateur à http://10.0.4.21/apirest.php/#ERROR_WRONG_APP_TOKEN_PARAMETER
```

**Comment by AnaelMobilia** [comment]
Hello @mohierf ,
It isn't a translation problem :
![image](https://user-images.githubusercontent.com/6187125/51898863-21384f00-23b2-11e9-9927-c3534003d56c.png)

Imho, the message didn't manage App-Token => need to add a string on this case.

Regards,
Anael

**Comment by M-Falken** [comment]
I think this is some of a translation issue indeed:
https://github.com/glpi-project/glpi/blob/48225442749ea0875fc59ecae748c275e64fde62/locales/fr_FR.po#L3924
https://github.com/glpi-project/glpi/blob/48225442749ea0875fc59ecae748c275e64fde62/locales/fr_FR.po#L3914
https://github.com/glpi-project/glpi/blob/48225442749ea0875fc59ecae748c275e64fde62/locales/fr_FR.po#L3983
https://github.com/glpi-project/glpi/blob/48225442749ea0875fc59ecae748c275e64fde62/locales/fr_FR.po#L3987
https://github.com/glpi-project/glpi/blob/48225442749ea0875fc59ecae748c275e64fde62/locales/fr_FR.po#L4003
https://github.com/glpi-project/glpi/blob/48225442749ea0875fc59ecae748c275e64fde62/locales/fr_FR.po#L4007
This is only some constants name that are used in the translated string, so it's most a matter of view to replace all occurrences.
`le paramètre user_token semble incorrect`
would be
`le paramètre jeton utilisateur semble incorrect`
And so on...
I can make a pull request, but this is the same for all languages.

**Comment by trasher** [comment]
Translations issue should be fixed on transifex.
