### ISSUE TITLE
SimCard Component - Voltage field ? (GLPI 9.3.3)

### ISSUE THREAD

**Issue by LordBat** [glpi-project/glpi#5296]
**Describe the bug**
Hi! i dont know if this is a bug but, Im not sure why a simcard needs Voltage Information instead like IMEI number. 

**Page(s) URL**

GLPI ----> Setup ----> Components ----> Simcards ----> New item - Simcard

![image](https://user-images.githubusercontent.com/19165739/51839325-b3275580-22e7-11e9-9c35-b6170f068227.png)

Regards!

**Comment by Smiley-k** [comment]
and add SIM card serial number as a separate item =)

**Comment by trasher** [comment]
Hello,

This is not a bug, please rather use [suggestion website](http://suggest.glpi-project.org) for RFE. Thank you
