### ISSUE TITLE
searchItems API and giveItems produce messy content

### ISSUE THREAD

**Issue by mohierf** [glpi-project/glpi#5297]
Using the REST API searchItems with `giveItems` parameter provides some data that are not clean nor usable. For instance, for tickets, we get:
```
{ 1: "<a id='Ticket115' href=\"/front/ticket.form.php?id=115\">Ticket title ... </a> <div id='contentTicket115' class='invisible'>From: John DOE[John.DOE@mail.fr] <br />\n Envoyé : lundi 7 janvier 2019 10:02<br />\n À : Jean Dupont<br />\n Objet : TR: Ticket title <br />\n<br />\nBonjour , <br />\n<br />\nBla bla bla. <br />\n<br />\nRegards, <br />\n<br />\n#c77f994e-f4757a0b-5c2c836d6f91d0.41880419#<br />\n</div><script type=\"text/javascript\">\n//<![CDATA[\n\n$('#Ticket115').qtip({\n         position: { viewport: $(window) },\n         content: {text: $('#contentTicket115')}, style: { classes: 'qtip-shadow qtip-bootstrap'}});\n\n//]]>\n</script>", 2: 115, 3: "Moyenne", … }
​​
```

This text is only for the ticket title //// note that it contains a part of the description and it also contains some Javascript !

Note that it would be enough to simply get the name rather than HTML content for the fields!

**Comment by trasher** [comment]
Problem is presentation is heavily mixed with logic currently; this will be fixed when they'll be separated (part of a huge changeset).
