### ISSUE TITLE
Autofilled DateTime Fields not saved in Firefox. On Chrome is working

### ISSUE THREAD

**Issue by rmorandell-pgum** [glpi-project/glpi#5299]
When we edit on Assets->Computer->Management the date fields like "Start date of warranty" and we get the date from the AutoFill suggestion from Firefox the data will not be saved. When we click in the field a modify the value the it will be saved.

On Chrome is working fine.

**To reproduce**

1. Open GLPI with **FIREFOX**
2. Go to 'Asset->Computer->Management'
3. Edit "Start date of warranty" field getting the value from autofill suggestions from firefox
4. Save the Asset
5. Reopen the Asset and check the value

**Screenshots**

Select a date from the list

![image](https://user-images.githubusercontent.com/46994680/51897348-dc5ee900-23ae-11e9-9901-8e1316e6bb64.png)

on save (POST) we debug the $_POST  on infocom.form.php for $_POST["update"]

![image](https://user-images.githubusercontent.com/46994680/51897464-103a0e80-23af-11e9-98ff-389d5f5388af.png)

the "_warranty_date" is set the "warranty_date" is empty. When we write the value in the field without autofill both values are set.

After save the field is empty

![image](https://user-images.githubusercontent.com/46994680/51897664-8d658380-23af-11e9-91ef-dc31346f29fa.png)

**Comment by trasher** [comment]
Hello, 

Sounds like this issue is from the jquery-ui lib used. It cannot be updated for now, this should be fixed in next major release since that lib will be updated.
