### ISSUE TITLE
Wrong info on refused solution

### ISSUE THREAD

**Issue by stonebuzz** [glpi-project/glpi#5301]
When the caller refuses a solution, the text indicates that it is the technician who adds the solution who refused

1. Resolve ticket with solution and technician user
2. Log with post_only
3. Refuse solution

![image](https://user-images.githubusercontent.com/7335054/51902420-40d37580-23ba-11e9-9cda-e530a43db0f4.png)

**Expected behavior**

the text should mention the person who refuses rather than the person who is behind the solution

**Comment by trasher** [comment]
Internal reference: 16002

**Comment by Armin83** [comment]
@trasher Do you know an easy way to fix in 9.3.3 ?

**Comment by trasher** [comment]
@Armin83 Same change, but in `inc/ticket.class.php`:
https://github.com/glpi-project/glpi/blob/9.3/bugfixes/inc/ticket.class.php#L6907
