### ISSUE TITLE
Allow search for locations by address

### ISSUE THREAD

**Issue by petersonbasso** [glpi-project/glpi#5302]
**Is your feature request related to a problem? Please describe.**
The GLPI should allow you to search for locations by registered address, in situations where there are many locations may be the only way to find the correct location.

**Describe the solution you'd like**
Allow search for locations by address.

**Describe alternatives you've considered**
Allow location search by address directly on the ticket opening screen.

**Comment by trasher** [comment]
Hi,

Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
