### ISSUE TITLE
[GLPI 9.3] Can update a ticket even if UPDATE rights are not given

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#5303]
Hello,

A user can update a ticket if he/she is a requester (or writer) of this ticket and if there is no followups and no tasks and ticket.status is not closed, nor solved.

This is a problem, when the UPDATE right is not given to this user.

And this is of course a problem with the object lock mechanism.

See screenshot:

![image](https://user-images.githubusercontent.com/7569958/51911149-5ef8a000-23d1-11e9-83e8-6e169cf4e3b7.png)

I'm going to provide a fix for that.

Thank you,
regards,
Tomolimo

**Comment by msizec** [comment]
Could be linked to https://github.com/glpi-project/glpi/issues/5270 ?
