### ISSUE TITLE
New

### ISSUE THREAD

**Issue by wagnerpf** [glpi-project/glpi#5308]
Hello everyone,
I would have a suggestion for improvement for GLPI, I miss it very much in the area of the followups something similar to the solution model.
Where would you record the followups with the standard text.

For example:
I have to ask the user to contact the service center because we can not get in touch with the user. This text could already be registered in the tool that standardizes the communication of the technicians with the users.

**Comment by trasher** [comment]
Hi,
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by ladenree76000** [comment]
https://glpi.userecho.com/communities/1/topics/238-add-template-for-followups
