### ISSUE TITLE
Web services API, possible extension

### ISSUE THREAD

**Issue by mohierf** [glpi-project/glpi#5309]
I did not found any possibility to extend the Glpi REST API through an installed plugin. Is it possible or this feature has not been considered as of now? Did I missed something ?

With former Glpi versions, one had to install the Web Services plugin that allowed any other plugin to register new API endpoints thanks to the `register_methods` hook. The monitoring plugin used this feature ans some other plugins tha t I know were also using this feature

I am currenlty trying to make these plugins compatible with the most recent Glpi version and I am meeting this problem. Any help / hint would be appreciated ....

**Note** that I alreaqy had a look in the Glpi core API source code but I did not found any hint in the huge *if ... else if* of the *call* function ...

**Comment by trasher** [comment]
Hi,

As far as I know, you can acces to plugins objects from the API as for those on the core.
Webservices plugins has nothing common with GLPI native API.

This is a usage question not a bug (so far), better use forums etc; Thanks ;)
