### ISSUE TITLE
Behavior changed since 0.90 in commondevices (processors, memories...)

### ISSUE THREAD

**Issue by ddurieux** [glpi-project/glpi#531]

**Comment by orthagh** [comment]
I currently manage backlog of this issue tracker.
So could you precise your issue ?
Do you need precisions on this commit ?

**Comment by ddurieux** [comment]
When add _DeviceProcessor_, _DeviceMemory_, now have log in glpi_logs (history). If it's the behavior wanted, it's not a problem ;)

**Comment by orthagh** [comment]
ok, so i tag and close
