### ISSUE TITLE
(ITILSolution) Improve the migration process from 9.2 to 9.3

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#5312]
**Describe the bug**

In some cases, after migration from 9.2.x to 9.3.x some tickets may have lost their solution.

In 9.2 these tickets had:
- an empty solution content
- a type of solution filled

It's because of this forced condition (we only retrieve solutions with content, good idea, but in some cases users only use the "Type of solution"):
https://github.com/glpi-project/glpi/blob/780c6bbae693cbeefe0e0c4ebcb1acef16911e2d/install/update_92_93.php#L115-L117

**To reproduce**

1. **[9.2.x]** solves a ticket with empty solution content and a solution type filled 
2. **[9.3.x]** update GLPI to 9.3 (``glpi_itilsolutions`` is created and filled)
3. **[9.3.x]** the ticket created in (1), has no solution.

**Expected behavior**

Migrate all ticket solutions, even if they have no content.

**Additional context**

To recover the data after migration, you must have the ``glpi_logs`` table filled (id_search_option = 23 for the type of solution) or use the backup made before migration.

**Comment by trasher** [comment]
@tomolimo since you write the migrations queries initially, do you think we can change to something like `LENGTH(ticket.`solution`) > 0  OR solutiontypes_id > 0`?
