### ISSUE TITLE
Notification for new planned Tasks.

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#5317]
Hi

When we set a new task, "Add task" notification is sent

But when we want to set a new task just in a waiting list for example, the notification is sent anyway, so without any information.
We don't want to send an empty notification to the customer now but just at the time when we will drop it on the planning.

So it could be great to have a new trigger like:
"New task planning"

And perhaps another one to have the possibility to distinguish between a simple task update from the update of the planning for a task.
"Updated of task planning"

Thanks to consider

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
