### ISSUE TITLE
just have first level of sla escalation

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5319]
https://forum.glpi-project.org/viewtopic.php?id=167241

Buf still present in 9.4

getFromDBForTicket is empty because glpi_slalevel_ticket is empty

**Comment by cedric-anne** [comment]
Hi @yllen ,

#5805 fixes this problem.

Regards

**Comment by cedric-anne** [comment]
Only elements having their first level of escalation not yet processed will be fixed. Patch does not recompute missed SLA escalations.
