### ISSUE TITLE
9.3.3 Rule.class.php Sqlerror

### ISSUE THREAD

**Issue by FranciscoVLopes** [glpi-project/glpi#5327]
Hi,
i'm using 9.3.3 version with php 7.2.10 and mysql 8.0.13.
when adding a rule, php and sql error log presents the following errors:

**php error log:**
[2019-02-05 11:50:15] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /u01/apps/glpi/product/glpi-9.3.3/inc/toolbox.class.php line 657
  *** PHP Notice(8): Trying to get property 'num_rows' of non-object
  Backtrace :
  inc/dbmysql.class.php:284
  inc/rule.class.php:1950                            DBmysql->numrows()
  inc/rule.class.php:1929                            Rule->getNextRanking()
  inc/commondbtm.class.php:1090                      Rule->prepareInputForAdd()
  front/rule.common.form.php:70                      CommonDBTM->add()
  front/ruleimportcomputer.form.php:37               include()

**sql error log:**
[2019-02-05 11:50:15] glpisqllog.ERROR: DBmysql::query() in /u01/apps/glpi/product/glpi-9.3.3/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT MAX(`ranking`) AS rank
              FROM `glpi_rules`
              WHERE `sub_type` = 'RuleImportComputer'
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank
              FROM `glpi_rules`
              WHERE `sub_type` = 'RuleImpor' at line 1
  Backtrace :
  inc/rule.class.php:1948
  inc/rule.class.php:1929                            Rule->getNextRanking()
  inc/commondbtm.class.php:1090                      Rule->prepareInputForAdd()
  front/rule.common.form.php:70                      CommonDBTM->add()
  front/ruleimportcomputer.form.php:37               include()

No consequences, the rule is added but error is there (rule.class.php).
"SELECT MAX(`ranking`) AS **rank** FROM `glpi_rules` WHERE `sub_type` = 'RuleImportComputer'"

Thanks for your work.

**Comment by cedric-anne** [comment]
Hi,

The rank is now a reserved word in MySQL 8.

I do not have a MySQL 8 test server. Could you test following patch ?

```diff
diff --git a/inc/migration.class.php b/inc/migration.class.php
index 8c7c287e31..a16d896c91 100644
--- a/inc/migration.class.php
+++ b/inc/migration.class.php
@@ -728,7 +728,7 @@ class Migration {
       $rule['description'] = '';
 
       // Compute ranking
-      $sql = "SELECT MAX(`ranking`) AS rank
+      $sql = "SELECT MAX(`ranking`) AS `rank`
               FROM `glpi_rules`
               WHERE `sub_type` = '".$rule['sub_type']."'";
       $result = $DB->query($sql);
```

Regards

**Comment by FranciscoVLopes** [comment]
Hi,
it was my workaround also and work's just fine. No more errors in php or mysql error log files.
Thanks
