### ISSUE TITLE
HTML elements appearing in problem solution - GLPI 9.3.0

### ISSUE THREAD

**Issue by nithinsugathan** [glpi-project/glpi#5330]
Hi,
HTML elements appearing along with the description after adding a solution to the problem in GLPI 9.3.0
![screenshot-2019-2-6 assets demo - problems - 14 1](https://user-images.githubusercontent.com/33018653/52326626-5fb3b680-2a0f-11e9-9a8c-7c684b59d016.png)

Thanks in advance

**Comment by trasher** [comment]
9.3.0 is old, try with a more recent version (test with 9.4.0-rc2)
