### ISSUE TITLE
Handle custom tags correctly for Notification Targets

### ISSUE THREAD

**Issue by flonou** [glpi-project/glpi#5334]
**Describe the bug**

I don't know if it's a bug or a feature that should be added but I would say that for me it looks more like a bug :
The notificationtarget class currently allows extension of existing targets through plugin hooks.
While we can add new events and new tags to base events, we cannot completely add new tags to new events for now. I mean, we can technically add them and use them in template translations, but not tell the user they exist in the tag list
I propose to : 
- add a specific hook to add new tags in order to be more intuitive and consistent with the current system (instead of using the item_get_datas or item_add_targets hooks, the plugin developer will use item_get_tags)
- fix the way tags are added in order to be able to add them to custom events (basically, that must mean that the notificationtarget::addTagToList method should call getAllEvents and not getEvents)

**Comment by cedric-anne** [comment]
Hi,

This is more an enhancement. Another issue already exists for the first part (#4599).

I keep yours as it is more descriptive.

Regards
