### ISSUE TITLE
Bug on massive action "Merge as followup"

### ISSUE THREAD

**Issue by Pieurre** [glpi-project/glpi#5338]
Hello @all

When on an ticket you use the new function "Merge as followup", sometimes (maybe randomly), an error occured.

![image](https://user-images.githubusercontent.com/6872020/52400887-add4c280-2ac0-11e9-803a-04769906fede.png)

I'm in SuperAdmin. I can't attach the logs for the moment but I can do this later.

Thank you.

**Comment by cconard96** [comment]
Is there already a link between the tickets you are merging?

**Comment by Pieurre** [comment]
Hello,

No, no links.

Thank you.

**Comment by trasher** [comment]
@cconard96 could take care of this one please? Thank you :)

**Comment by cconard96** [comment]
I looked at this and couldn't recreate the issue. @Pieurre can you provide logs?

**Comment by cedric-anne** [comment]
@Pieurre ,

Was the ticket content containing a `'` ?

**Comment by cedric-anne** [comment]
@Pieurre 

I reproduced this problem for tickets having a  `'` in their description. I consider your problem was related to this.
This has been fixed by #5678, so I close this issue.

Regards
