### ISSUE TITLE
Planning issue or working as intended?

### ISSUE THREAD

**Issue by b00paul** [glpi-project/glpi#5344]
When creating a project and a project task, if I set a time for the Planned Start Date and Planned End Date of multiple days with specific times, the calendar is showing it as all day despite it set to 13:00 to 16:00.

![image](https://user-images.githubusercontent.com/31808219/52414568-b8885b00-2ab2-11e9-9f94-be165ec172d7.png)

My expectation was it was supposed to look like this:
![image](https://user-images.githubusercontent.com/31808219/52414596-c76f0d80-2ab2-11e9-9543-23ca61afcc36.png)

This is the settings:
![image](https://user-images.githubusercontent.com/31808219/52414611-cf2eb200-2ab2-11e9-94fc-b651db254553.png)

I was using the GLPI demo page (version 9.3.3): demo.glpi-project.org/front/planning.php

And I also tested this using the RC version 9.4

Also could you explain the purpose of the Planned duration/effective duration? Is there a reason it isn't automatically calculated from the times selected?

Sorry if this is an intended feature, I just was curious how it's supposed to work.

**Comment by trasher** [comment]
The behavior seems to be the expected one; what you want to achieve is not possible currently. 
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

I do not know about "calculated times"; you'd rather use [forums](http://forum.glpi-project.org) to get support.
