### ISSUE TITLE
GLPI_CACHE plugins

### ISSUE THREAD

**Issue by salleman33** [glpi-project/glpi#5368]
Hi, 

I have GLPI 9.4 and i think there is a bug with automatic action for plugin.
I use the crontask '/usr/bin/php /var/www/html/glpi/front/cron.php' to launch automatic actions.
i try to debug : 
on the function 'getNeedToRun' in file crontask.class.php, call to function Plugin::getPlugins() returns nothing, so tasks for a plugin cannot  be launched. 
$GLPI_CACHE->get('plugins') is an empty array

Regards

**Comment by cedric-anne** [comment]
Hi,

I tried to reproduce but I cannot. Are you sure your plugins are active ?

Regards

**Comment by yllen** [comment]
You have also ask about automatic action of plugin in the forum
https://forum.glpi-project.org/viewtopic.php?id=167631

**Comment by salleman33** [comment]
Yes, plugins are active. I use fusioninventory, reservations, manufacturersimports. No task starts. I will try to reinstall glpi...

**Comment by cedric-anne** [comment]
If you launch cron from cron or cli, make sure that all required php extensions are loaded and user is same as webserver one.

**Comment by salleman33** [comment]
same, call Plugin::getPlugins() is empty.
if i enable debug mode on glpi : 

![1](https://user-images.githubusercontent.com/37148072/53114656-9a0b7080-3544-11e9-9fc6-64cb885e27d9.png)

**Comment by salleman33** [comment]
I patch the code in file crontask.class.php to force add plugin :  
$query .= " OR `itemtype` LIKE 'Plugin$plug%'";

**Comment by trasher** [comment]
Could you please open a pull request with the fix proposal? Thank you.

**Comment by salleman33** [comment]
it's not a clean patch :/
I have tested again on an other server, ubuntu 16.04 (my first test was on debian 9), I have installed GLPI 9.4.0 from scratch and plugin FusionInventory. Problem is still here... 

![2](https://user-images.githubusercontent.com/37148072/53156318-6d486f00-35bf-11e9-99d9-7121e77a5d60.png)

**Comment by trasher** [comment]
Anyways you did not precise where you did the change that make things work for you, this may help us to know if it is correct or not, and maybe what the problem is.

**Comment by cedric-anne** [comment]
Hi,

In your screenshot, I think your cache is populated but rendering is broken, please try with https://github.com/glpi-project/glpi/pull/5448 .

For the main problem, I may have an explainition. If your web interface is using a different cache storage than the cron, it can explains that your cron does not load plugins.
Are you using APC ? Is APC extension loaded when you launch PHP in CLI mode ?

Regards

**Comment by trasher** [comment]
@salleman33 please tyr to drop all but remove.txt file from files/_cache directory. This should solve issue right now.
We're working on a fix.

**Comment by salleman33** [comment]
@trasher yes, it works now ! thanks

**Comment by trasher** [comment]
@salleman33 , since you did not answer to @cedric-anne questions regarding APCu and you did not provide logs, nor system configuration, it's hard to guess whet the initial problem can be.
Please provided requested informations.

**Comment by salleman33** [comment]
@cedric-anne , yes i use APC and the extension is loaded for apache and CLI mode. 

Just after a clean install and a plugin enabled, "files/_cache/cache_db/zfcache-63/zfcache-plugins.dat " contains : 
`a:0:{}`
after I removed cache directories : 
`a:1:{i:1;s:11:"reservation";}`

Here is my config  : 


[code]  
GLPI 9.4.0 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux glpi 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 PHP 7.0.33-0+deb9u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache () 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 Server Software: Debian 9.6 	Server Version: 10.1.37-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (10.1.37) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/var/www/html/glpi/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)


Plugins list
--
addressing           Name: Adressage IP                   Version: 2.7.1      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled 	manufacturersimports Name: Imports fabricants             Version: 2.2.0      State: Enabled 	reservation          Name: Reservation                    Version: 2.1.3      State: Enabled
[/code]

**Comment by trasher** [comment]
Thanks for the details; your setup should be correct; I do not explain this issue. Anyways, follow #5465 fix proposal;

**Comment by trasher** [comment]
Hi @all, please test #5465 and see if you can reproduce. Thanks.

**Comment by cedric-anne** [comment]
See #5629 .

**Comment by cedric-anne** [comment]
Hi @salleman33 ,

Was the problem still occurs on your side after applying #5465 ? If yes, can you test #5629 ?

Regards

**Comment by cedric-anne** [comment]
> Just after a clean install and a plugin enabled, "files/_cache/cache_db/zfcache-63/zfcache-plugins.dat " contains :

Just notice that of you have this, then it implies that APCu cache instanciation failed, certainly  in CLI mode. #5465 + #5629 have to be applied both to fix this.

**Comment by salleman33** [comment]
Hi, 
I will test it  next week 

Thanks
