### ISSUE TITLE
Default Language for Notification Template Translation is not correctly set

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#537]
Hello,

Tried with 0.91 latest sources and fresh install from scratch.

To reproduce: after installation go to 'Notifications' create new a notification template, fill-in the 'Default Translation', and type-in any text, and 'Add'. The field 'language' in the DB table will contain a '0' (zero).

This behavior occurs also when editing any other template translations, the 'language' field is reset to '0'.

Regards,
Tomolimo

**Comment by orthagh** [comment]
As @yllen mention in https://github.com/glpi-project/glpi/pull/538#issuecomment-198506816, we need to fix the original dropdown instead fix the consquence

**Comment by tomolimo** [comment]
Still not fixed in latest installation :(

**Comment by yllen** [comment]
@tomolimo can you test my correction on 0.90.
If ok i will do the same for 9.1

**Comment by tomolimo** [comment]
Thank you @yllen, it's working well now, I've checked in the DB, the `language` field is kept empty.

**Comment by tomolimo** [comment]
I made also a test for 9.1 and there, there is no '---' option in the template translation language choice...for 0.90.3: this '---' option is present.

**Comment by yllen** [comment]
as said, modification was not done in 9.1. A report this change.
@tomolimo is OK now for you?

**Comment by tomolimo** [comment]
Yes it's ok for 0.90.
But if I report this into 9.1, then I got what I said: no '---'

**Comment by yllen** [comment]
@tomolimo it's better now?

**Comment by tomolimo** [comment]
It's perfect :smiley:  
Thank you
Regards,
Tomolimo
