### ISSUE TITLE
[9.4] PREFERENCES are remembered in the options but not applied

### ISSUE THREAD

**Issue by InformatiqueOLLN** [glpi-project/glpi#5372]
Hi,

Private followup is remembered in the options but not applied.

I set the option to have private followup by default.
Everything work fine.
I close the navigator (chrome or firefox).
I reopen glpi
followup are no more private.
If i go to user prefs, i see private by default = true.
I Need to Save my parameters (without doing anything) to get private by default.

**Expected behavior**

Private allways checked by default

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

Operating system: Linux web 3.2.0-4-amd64 #1 SMP Debian 3.2.41-1 x86_64 PHP 5.6.20-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, 	ionCube Loader, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_pgsql, pgsql, posix, 	session, shmop, soap, sockets, ssh2, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, 	xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="512M" post_max_size="32M" safe_mode="" session.save_handler="files" 	upload_max_filesize="32M"  Software: Apache/2.4.10 (Debian) PHP/5.6.20-0+deb8u1 mod_python/3.3.1 Python/2.7.9 OpenSSL/1.0.1t () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.96 Safari/537.36 Server Software: (Debian) 	Server Version: 5.6.30-1 	Server SQL Mode:  	Parameters: glpidbuser@192.168.65.80/glpidb 	Host info: 192.168.65.80 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (5.6.30) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.
--

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/var/www/glpi/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src) paragonie/random_compat in (/var/www/glpi/vendor/paragonie/random_compat/lib)

LDAP : ON

SQL replicas
--
Not active

Way of sending emails: PHP

Name: 'informatique.........

fields               Name: Champs supplémentaires         Version: 1.9.1      State: Enabled 	shellcommands        Name: Commandes Shell                Version: 2.2.1      State: To be cleaned 	mydashboard          Name: Dashboard                      Version: 1.6.1      State: Not activated 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.7.0      State: Enabled 	order                Name: Gestion des commandes          Version: 2.4.0      State: Enabled 	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.6.0      State: Enabled 	dashboard            Name: Tableau de bord                Version: 0.9.4      State: Not activated
[/code]

**Additional context**

**Comment by InformatiqueOLLN** [comment]
It's not only private followups, but all prefs (theme, ...)

**Comment by usrqmor** [comment]
Hello,

I confirm this bug. I reproduce it on my test server and the demo version on https://demo.glpi-project.org/
There are some screenshot that I take from the demo version 
Screenshot of the bug 
![image](https://user-images.githubusercontent.com/17316903/53016083-fb501880-344c-11e9-8c58-e881ddf2fe25.png)
![image](https://user-images.githubusercontent.com/17316903/53016088-02772680-344d-11e9-8851-42b1ec53819e.png)

Screenshot after using save in order to reapply the preferences
![image](https://user-images.githubusercontent.com/17316903/53016125-1d499b00-344d-11e9-9ce0-4ae83839ef61.png)
![image](https://user-images.githubusercontent.com/17316903/53016131-1fabf500-344d-11e9-96f0-33e047dbd61d.png)

But if you connect you automatically on GLPI when you open your browser, you don't have the problem.

**Comment by ConteZero** [comment]
I can confirm the bug with a clean 9.4.0 install.
Current language for the user is Italian, if I change the language to English in /front/preference.php it is applied to the current session.
But after a logout/login procedure the config is lost, the language of the interface is now in Italian, but the preference page show English.
The default language in /front/config.form.php (Default values tab) is Italian so I think that that value is used instead of the language form /front/preference.php

**Comment by cedric-anne** [comment]
Hi all,

Could you test this fix: #5418 ?

Regards

**Comment by InformatiqueOLLN** [comment]
Hi, I applied fix #5418 and it works.

Thanks,

**Comment by usrqmor** [comment]
I confirm that it works ! 
Thanks

**Comment by ConteZero** [comment]
The fix works, thanks
