### ISSUE TITLE
GLPI 9.3.3 - Bug with permissions defined in the technical profile (standard interface)

### ISSUE THREAD

**Issue by mrsric** [glpi-project/glpi#5373]
In GLPI 9.3.3 I created a technical profile that is not allowed to edit (update) tickets, only interact in the tasks, follow-ups and solution, but the technicians of this profile are able to edit them.

Problem does not occur in version 9.2.3

Difference in variable $canupdate (ticket.class.php):
`//9.3
// check right used for this ticket
     $canupdate     = !$ID  || (Session::getCurrentInterface() == "central"  && $this->canUpdateItem());

//9.2
// check right used for this ticket
      $canupdate     = !$ID || Session::haveRight(self::$rightname, UPDATE);
`

**Comment by trasher** [comment]
Please check if you can reproduce on 9.4.0

**Comment by mrsric** [comment]
I reproduced on 9.4.0 and it has the same problem.

`//9.4.0
// check right used for this ticket
      $canupdate     = !$ID || (Session::getCurrentInterface() == "central" && $this->canUpdateItem());
`

**Comment by trasher** [comment]
OK, thanks for the feedback

**Comment by cedric-anne** [comment]
Hi,

Can you take a screenshot of exact rights applied to this profile ?

Regards

**Comment by mrsric** [comment]
Hi,

Here is the screenshot of support permissions in tickets:

![image](https://user-images.githubusercontent.com/24476333/53636414-ec145c00-3bfe-11e9-9db7-7a293197b328.png)

The technical profile that is not allowed to edit (update) ticket:

![image](https://user-images.githubusercontent.com/24476333/53636429-00585900-3bff-11e9-9f0a-868506eefdef.png)

But when the technician is assigned, he can edit (update) ticket:
![image](https://user-images.githubusercontent.com/24476333/53636446-09e1c100-3bff-11e9-9a08-cc9ca1cc3ea0.png)

**Comment by sworddestiny** [comment]
Tengo el mismo problema. Ese detalle no se ha resuelto en la versión 9.4.2.

**Comment by trasher** [comment]
@sworddestiny **english only** please.

**Comment by sworddestiny** [comment]
I have the same problem. This detail has not been resolved in version 9.4.2.

**Comment by sworddestiny** [comment]
I have the same problem. This detail has not been resolved in version 9.4.2.
