### ISSUE TITLE
Ticket content not formatted when created by API

### ISSUE THREAD

**Issue by Akuket** [glpi-project/glpi#5379]
Hello

**Describe the bug**

When a ticket is created by the API, it seems that formatting rules aren't applied. So when a ticket is updated from the front/ticket.form.php page the ticket is recreated with the correct rules.
When checking the database before the update, when can see ```\n``` caractères for example and after ```&lt;br /&gt;``` caractères (```<br />```).

**Page(s) URL**

front/ticket.form.php

**To reproduce**

1. Create a ticket through API with some ```\n``` characters inside
2. Go to the page front/ticket.form.php?id=new ticket id
3. Change the status to resolved
4. See error: Normally, the ticket should be recreated and now the status should be new
5. Change the status to resolved: It's all good

**Logs**

For security reason, I can't paste our logs here. Sorry

**GLPI setup**

```
GLPI 9.3.3 ( => /opt/glpi)
Installation mode: TARBALL
```

Regards

**Comment by trasher** [comment]
Hi, please test if problem still occurs in 9.4.0

**Comment by Akuket** [comment]
Hi, sorry for the wait.
The problem still occurs in glpi 9.4.0

**Comment by Akuket** [comment]
Does anyone have an idea why this problem occurs?

**Comment by cedric-anne** [comment]
Hi,

Not sure it is a bug.

I think the problem here is that the conversion from text to HTML is done on front-end by the TinyMCE javascript component.

I guess we may handle this by transforming content using `nl2br` and then encapsulate result inside a `<p></p>` tag. If we do this, it should be done globally, so we need to find a solution to identify rich text fields easilly.
@orthagh Do you think this is something we could/should do ?

Regards

**Comment by Akuket** [comment]
Hello

I think maybe we are going in the wrong direction. Rather than trying to solve the problem of formatting, it may be necessary to find out why the status changes and goes "new" again in this case. Whereas for classic tickets, the status does not change. There may be a hardcoded rule in glpi?

Regards

**Comment by Akuket** [comment]
Hi,

Does someone have an idea for this ?

Regards

**Comment by GuiGuiSoft** [comment]
Hello,

Same problem here with 9.4.4 version.

I don't know why the ticket (created by API) goes again to the "new" status when I manually try to change the status to Resolved or Closed.

The problem does not occurs when I use a Solution.  
If I add a Solution then the ticket becomes Resolved (and not new).

**Comment by Akuket** [comment]
May this can help ? @cedric-anne 
![image](https://user-images.githubusercontent.com/32392661/67190360-20d45e00-f3f0-11e9-9113-f704be612198.png)
It's before and after the change of status
