### ISSUE TITLE
[GLPI 9.4.0] : some fonts awesome icons not displayed

### ISSUE THREAD

**Issue by ppenin** [glpi-project/glpi#5381]
**Describe the bug**

some fonts awesome icons are not displayed

**Page(s) URL**
![image](https://user-images.githubusercontent.com/22499638/52767464-e4fc2400-302a-11e9-832d-8af80643461e.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

GLPI 9.4.0 (/glpi => /usr/share/glpi) Installation mode: TARBALL
--

Operating system: Linux s001linux02 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 PHP 7.0.33-1+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, 	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="1024M" post_max_size="1000M" safe_mode="" session.save_handler="files" 	upload_max_filesize="1000M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 10.100.10.18 Port 80) 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:65.0) Gecko/20100101 Firefox/65.0 Server Software: (Ubuntu) 	Server Version: 5.7.25-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (5.7.25) - Perfect! /usr/share/glpi/files/_log : OK /usr/share/glpi/config : OK /usr/share/glpi/files : OK /usr/share/glpi/files/_dumps : OK /usr/share/glpi/files/_sessions : OK /usr/share/glpi/files/_cron : OK /usr/share/glpi/files/_graphs : OK /usr/share/glpi/files/_lock : OK /usr/share/glpi/files/_plugins : OK /usr/share/glpi/files/_tmp : OK /usr/share/glpi/files/_cache : OK /usr/share/glpi/files/_rss : OK /usr/share/glpi/files/_uploads : OK /usr/share/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/usr/share/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/usr/share/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/usr/share/glpi/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/usr/share/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/usr/share/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) leafo/scssphp in (/usr/share/glpi/vendor/leafo/scssphp/src)

**Comment by orthagh** [comment]
Hello, Are you using the plugin mreporting ?

**Comment by ppenin** [comment]
Yes i do . When mreporting is disabled the fonts are displayed.

**Comment by trasher** [comment]
So this is a plugin issue, see https://github.com/pluginsGLPI/mreporting/issues/175
