### ISSUE TITLE
Add notifications for "add followup" with "close action" or "resolve action"

### ISSUE THREAD

**Issue by tguichard25** [glpi-project/glpi#5382]
Hello,

Would it be possible to add notifications for "add followup" with "close action" or "resolve action".
I found this topic: https://github.com/glpi-project/glpi/issues/1044
that no longer seems to apply to version 9.4.0
By the way would not it be possible to put it in place for the future version?

**Comment by trasher** [comment]
As far as I can say, it's never been implemented. See also #1400
