### ISSUE TITLE
error when filtering

### ISSUE THREAD

**Issue by revan9112** [glpi-project/glpi#5385]
Hello community, 2 days ago I am noticing that the system does not allow me to filter the equipment by the components, no matter which component is chosen. I can not filter and just let me use the contains field, the "equals" and "not equals" fields do not show them to me, does anyone know how to fix it?

I am using the GLPI version 9.3.1. I update to version 9.4 in a test environment and the problem persists

**Comment by trasher** [comment]
Hello, please use [suggestion website](http://suggest.glpi-project.org) for RFE; this is not a bug.
