### ISSUE TITLE
Allocated Table

### ISSUE THREAD

**Issue by PBeierle** [glpi-project/glpi#5388]
I would like to know which table connects the monitors to the computers (item to computer).
With version 9.4 the bug "https://github.com/glpi-project/glpi/issues/4850" is fixed for new connected monitors but connected monitors can not be disconnected.

**Comment by cedric-anne** [comment]
Hi,

The table is `glpi_computers_items`.

@yllen Does your fix (#4850) only applies to new elements or does it correct the display of existing data ? In other words, is it necessary to plan a migration?

Regards

**Comment by MonsieurTwinkies** [comment]
Same problem

**Comment by squale323** [comment]
same problem

**Comment by Dayflare** [comment]
i have the same problem. New items are fixed but i have some old monitors which can't be disconnected from the computers. The connected computer was deleted from the monitor, but the connection is still visible from the computer.

You can't migrate monitors to another entity with such a broken link.

@cedric-anne is it safe to delete the link directly via database edit?

**Comment by cedric-anne** [comment]
Hi,

I do not know and it is why I asked @yllen if a migration was needed.

Regards

**Comment by orthagh** [comment]
Fixed by #6003
