### ISSUE TITLE
When creating a reservation, the end is specified as a duration by default instead of a date

### ISSUE THREAD

**Issue by flonou** [glpi-project/glpi#5392]
A clear and concise description of what the bug is :

xxx/glpi/front/reservation.form.php

Create a new reservation
You then have a start date and a duration to specify. The time step are specified in the Assistance tab in the setup

What I would expect :
Specifying a duration could be an option but not the default one. My reasoning is the following : People do not book items for 5 or 15 min, but for longer periods, like hours, days, etc .... Having to go through a (rather long, and generated) dropdown is not user friendly. People will always open the dropdown, maybe scroll, select "specify an end date" and then use the now available calendar selection.
Also, the parameter for the time steps being the one used for assistance doesn't seem intuitively placed. Maybe reservations should have their own setup tab and parameters ?

As far as the first part goes (specifying an end date by default), I'm totally ok to propose a PR, it's quite simple to fix

**Comment by trasher** [comment]
Hello,

This is not really an issue, but an evolution. Please use [suggestion website](http://suggest.glpi-project.org) or upvote if it already exists.

Thank you.
