### ISSUE TITLE
Description formatting on Ticket Processing [9.4]

### ISSUE THREAD

**Issue by jonatangobbato** [glpi-project/glpi#5393]
In GLPI 9.4 the ticket description on the Ticket Processing tab now has a bad formatting.

![image](https://user-images.githubusercontent.com/29125329/52876216-ae62fe00-313d-11e9-884b-cde9112dd361.png)

**Expected behavior**

See bellow a comparison betwen GLPI 9.3.3 and GLPI 9.4.4

9.3.3

![image](https://user-images.githubusercontent.com/29125329/52876416-4bbe3200-313e-11e9-9d71-42e78fa8b4e9.png)

9.4

![image](https://user-images.githubusercontent.com/29125329/52876468-701a0e80-313e-11e9-999d-82a93bdaca53.png)

GLPI Instalation

[code]   GLPI 9.4.0 (/glpi_test => /usr/share/glpi_test) Installation mode: TARBALL
--

Operating system: Linux glpi.biamar.local 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64 PHP 7.2.15 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.15 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.2.8-MariaDB 	Server SQL Mode:  	Parameters: glpi_test@localhost/glpi_test 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (10.2.8) - Perfect! /usr/share/glpi_test/files/_log : OK /usr/share/glpi_test/config : OK /usr/share/glpi_test/files : OK /usr/share/glpi_test/files/_dumps : OK /usr/share/glpi_test/files/_sessions : OK /usr/share/glpi_test/files/_cron : OK /usr/share/glpi_test/files/_graphs : OK /usr/share/glpi_test/files/_lock : OK /usr/share/glpi_test/files/_plugins : OK /usr/share/glpi_test/files/_tmp : OK /usr/share/glpi_test/files/_cache : OK /usr/share/glpi_test/files/_rss : OK /usr/share/glpi_test/files/_uploads : OK /usr/share/glpi_test/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

htmLawed version 1.2.4 in (/usr/share/glpi_test/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/usr/share/glpi_test/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/usr/share/glpi_test/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/usr/share/glpi_test/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi_test/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi_test/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi_test/vendor/iamcal/lib_autolink) sabre/vobject in (/usr/share/glpi_test/vendor/sabre/vobject/lib) zendframework/zend-cache in (/usr/share/glpi_test/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/usr/share/glpi_test/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/usr/share/glpi_test/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/usr/share/glpi_test/vendor/zendframework/zend-serializer/src) monolog/monolog in (/usr/share/glpi_test/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi_test/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi_test/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi_test/vendor/symfony/console) leafo/scssphp in (/usr/share/glpi_test/vendor/leafo/scssphp/src) phpCas version 1.3.6 in (/usr/share/pear)

[/code]

**Comment by OscarBeiro** [comment]
Same here.

**Comment by vordee** [comment]
Some Here.

**Comment by salleman33** [comment]
Some Here.

**Comment by trasher** [comment]
Probably dups https://github.com/glpi-project/glpi/issues/5363
