### ISSUE TITLE
[9.4] Update GlobalIterator raise open_basedir error

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#5406]
Hi ! 

I try to upgrade my GLPI version (9.3.3) to the last version (9.4). When I try to migrate, I have a PHP error : 
```
Fatal error: Uncaught UnexpectedValueException: GlobIterator::__construct(): open_basedir restriction in effect. File(\glpi\files\_cache\cache_db\glpi_cache_db_9.4.0-*\glpi_cache_db_9.4.0-*.*) is not within the allowed path(s): (\glpi) 
```

As you can see, I'm in the correct folder. It's not the first time I update GLPI on my Windows server. Is it a bug or do I investigate in my server. 

IIS10 and PHP 7.3

Thanks for your help !

**Comment by ciadch** [comment]
I try with multiple version of PHP (5.6, 7.2, 7.3), same behaviour

**Comment by trasher** [comment]
Error message «open_basedir restriction in effect» seems to be quite relevant. Fix your php configuration, and you're done.
This is related to server configuration; GLPI should not take care of that.

**Comment by ciadch** [comment]
Hi @trasher,

Thanks for answering me, I'll investigate in my server. 

Have a nice day

**Comment by ujohnrag** [comment]
hi i too got same error when i try to upload a project in glpi 
"**PHP Warning:  file_exists(): open_basedir restriction in effect. File(C:\inetpub\wwwroot/front/setup.templates.php?itemtype=Project&amp;add=1) is not within the allowed path(s): (C:\inetpub\wwwroot) in C:\inetpub\wwwroot\src\Toolbox.php on line 3536/**"

can you please guide where and what i need to configure.
