### ISSUE TITLE
GLPI 9.3.0 rich text: image not visible in tickets notification 

### ISSUE THREAD

**Issue by nwf00** [glpi-project/glpi#5407]
Hi everyone,

I'm new in GLPI, and I have a small problem. maybe someone can help me. It's very similar to https://github.com/glpi-project/glpi/issues/3154, my problem is that I can see the images in the ticket inside GLPI and I cant't see them on the email notification that arrives in may mailbox. In case #3154 the are talking of GLPI 9.2.0 or 9.2.1 and i don't want to correct thing and mess things up. Can someone give me an update or tell mi if this can be solved.

Thanks

![image](https://user-images.githubusercontent.com/25247256/52976471-67c50c00-33a8-11e9-8c98-af88fa8d05c9.png)

**Comment by cedric-anne** [comment]
Hi,

Maybe it was this bug, which has been fixed in 9.3.2: https://github.com/glpi-project/glpi/issues/4421 .
You should update to GLPI 9.3.3 and test is this problem is still present.

Regards

**Comment by trasher** [comment]
Since 9.3 is no longer supported, it would probably be better to thik about updating to 9.4.0 ;)

**Comment by nectop** [comment]
9.4.3 same issue, but only with JPG, PNG is ok.

**Comment by cedric-anne** [comment]
Hi @nectop ,

Please open another issue and provide all requested informations. Current issue was stale and may be different from yours.

Regards
