### ISSUE TITLE
Your planning always empty

### ISSUE THREAD

**Issue by tkuijs** [glpi-project/glpi#5411]
Since upgrading to 9.4 'Your Planning' on the central page is always empty. The previous version I ran was 9.3 and this version was still showing ticket tasks.

![screenshot 2019-02-19 at 12 46 43](https://user-images.githubusercontent.com/722305/53012884-8bd62b00-3444-11e9-9435-01ed9a5dbb2a.png)
![screenshot 2019-02-19 at 12 46 49](https://user-images.githubusercontent.com/722305/53012885-8bd62b00-3444-11e9-9549-aefc1e678dec.png)

**Comment by trasher** [comment]
As asked in the template you did not fill; please provide any relevant logs.

**Comment by tkuijs** [comment]
1) On central the Your Planning block is always empty since 9.4
2) When clicking on Your Planning the schedule does show all tasks
3) In the code there is a POST call to https://domain/ajax/planning.php with the following values:
action: get_events
display_done_events: 0
start: 2009-02-19
end: 2009-02-19
4) When manually altering the details in a GET URL: https://domain/ajax/planning.php?action=get_events&start=2019-02-19&end=2019-02-28 (changing the END) I do get results in the file

The logs or debug function are not showing anything. Hopefully this makes any sense.

**Comment by trasher** [comment]
It may be a javascript problem. Please check your browser console to see if any error occurs. Also, precise what browser you do use (and try with another one to be sure it's not related to a particular browser version.

**Comment by tkuijs** [comment]
The same thing happens on Firefox (latest), Chrome (latest), IE, Edge on Windows and Chrome, Firefox and Safari on Mac. No errors in console but the following which are related to non-existing files:

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.qtip.min.map, line 0): 
/lib/jqueryplugins/qtip2/jquery.qtip.min.map
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (leaflet.markercluster.js.map, line 0): 
/lib/leaflet/plugins/Leaflet.markercluster/leaflet.markercluster.js.map

Also as mentioned before I am using the developer tools and see the response of the planning.php actually being emtpy. This is being Requested by Javascript so it looks like that is not the issue.

**Comment by trasher** [comment]
>  the response of the planning.php actually being emtpy. 

You said POST'ed end_date is wrong, so it may be JS that pick the wrong one... Anyways, that was just a guess, I'm not sure.

**Comment by tkuijs** [comment]
If somebody can point me to the file where the POST for the /ajax/planning.php is generated and handled I can investigate some more (and have a look at what changed in the code). It looks like the post is forcing the request to just look at tasks between today 00:00:00 and today 00:00:00 which is always none (in my case..)

I just added a task from yesterday 23:50:00 until today 00:50:00 and it instantly pops up in the Your Planning screen:

![screenshot 2019-02-19 at 14 50 40](https://user-images.githubusercontent.com/722305/53019758-bc729080-3455-11e9-82cd-20bd2e2d1952.png)

**Comment by ConteZero** [comment]
I can confirm the problem with a clean 9.4.0 install.
I have a task for the current day that is shown in /front/planning.php but 'Your planning' in /front/central.php is empty.

**Comment by tkuijs** [comment]
Can somebody confirm this will be fixed? And perhaps if there is a way to patch this for the time being? If more information from me is needed please let me know. More than willing to assist.

**Comment by cedric-anne** [comment]
Hi @tkuijs , @ConteZero ,

Could you test the fix #5455 ?

Regards

**Comment by tkuijs** [comment]
Hi @cedric-anne 

This fixed my issue, thanks!

Best!

**Comment by cedric-anne** [comment]
I reopened the issue, it will be closed automatically when the PR will be merged.

**Comment by ConteZero** [comment]
I can confirm that proposed fix solves the issue, thanks

**Comment by Favid1** [comment]
Hello ,
after using the proposed solution, it works correctly, but in the records of php-errors.log they give me different notices each time I create the task, ¿Solutions?
Thank you
GLPI 9.4

`[2019-06-28 10:35:48] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: default_date
  Backtrace :
  inc/planning.class.php:621                         
  inc/planning.class.php:2111                        Planning::showPlanning()
  inc/central.class.php:232                          Planning::showCentral()
  inc/central.class.php:82                           Central::showMyView()
  inc/commonglpi.class.php:485                       Central::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"129@essansc1"} 
[2019-06-28 10:35:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: default_date
  Backtrace :
  inc/planning.class.php:621                         
  inc/planning.class.php:144                         Planning::showPlanning()
  inc/commonglpi.class.php:485                       Planning::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"129@essansc1"} 
[2019-06-28 10:35:56] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: default_date
  Backtrace :
  inc/planning.class.php:621                         
  inc/planning.class.php:2111                        Planning::showPlanning()
  inc/central.class.php:232                          Planning::showCentral()
  inc/central.class.php:82                           Central::showMyView()
  inc/commonglpi.class.php:485                       Central::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"129@essansc1"} 
[2019-06-28 10:38:48] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: default_date
  Backtrace :
  inc/planning.class.php:621                         
  inc/planning.class.php:144                         Planning::showPlanning()
  inc/commonglpi.class.php:485                       Planning::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"129@essansc1"} 
[2019-06-28 10:38:51] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: default_date
  Backtrace :
  inc/planning.class.php:621                         
  inc/planning.class.php:2111                        Planning::showPlanning()
  inc/central.class.php:232                          Planning::showCentral()
  inc/central.class.php:82                           Central::showMyView()
  inc/commonglpi.class.php:485                       Central::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"129@essansc1"} 
`

**Comment by cedric-anne** [comment]
Hi @Favid1 ,

Please open a new issue as this is a different problem.

Regards
