### ISSUE TITLE
Ticket description display

### ISSUE THREAD

**Issue by GuiGuiSoft** [glpi-project/glpi#5415]
**Describe the bug**

The description of the ticket (with green background in the treatment tab), is displayed on a very small part of the screen (I would say it is "ugly", but it is very subjective :) ).

**Page(s) URL**

/front/ticket.form.php

**To reproduce**

1. Display the ticket treatment tab

**Expected behavior**

The description of the ticket should take more space (width).

**Screenshots**

![capture](https://user-images.githubusercontent.com/8069239/53033887-63fdbc00-3472-11e9-80e9-68f08a8f7aa4.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.0 ( => /var/www/html/glpi)
Installation mode: TARBALL
```

**Comment by trasher** [comment]
Please search in existing tickets before opening another one. This issue has been reported several times; and has been fixed.

**Comment by cedric-anne** [comment]
Duplicates #5363.
