### ISSUE TITLE
[0.90.1] Option "Allow anonymous followups (receiver)" bypassed

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#542]
When option "Allow anonymous followups (receiver)" has value "No", you could anyway send anonymous followups.

Steps to reproduce issue : 
- Configure "Allow anonymous ticket creation (helpdesk.receiver)" with "Yes" value"
- Configure "Allow anonymous followups (receiver)" with "No" value
- Send an e-mail from *an anonymous e-mail* to a receiver
- Add public followup from helpdesk on created ticket
- Reply to this public followup with anonymous e-mail

Result : a new followup is added on created ticket.

**Comment by orthagh** [comment]
This behavior work as intended.
If an email is already an actor (or a supplier) of the ticket, the option "Allow anonymous followups (receiver)" is bypassed.
This to permits answers if you are an "anonymous" actor of a ticket and if you receive notification from it.

See : 
https://github.com/glpi-project/glpi/blob/a5fef58ad6a98ebb9d87dea1ca51049ad7ae2549/inc/mailcollector.class.php#L792

I close, feel free to reopen and comment if you need precisions
