### ISSUE TITLE
[9.3.3][LDAP] User is not disabled upon LDAP entry removal

### ISSUE THREAD

**Issue by gillesdubois** [glpi-project/glpi#5426]
**Describe the bug**

In my GLPI, the user should be disabled when the LDAP entry is removed.
It was working perfectly before our upgrade (from 9.1.1) but since 9.3.3, it's not working anymore.

I also tried to run the ldap_mass_sync.php to check if the removed LDAP entries were displayed, it's the case. (see [ldap_mass_sync_output.txt](https://github.com/glpi-project/glpi/files/2885363/ldap_mass_sync_output.txt))

**To reproduce**

1. Set "Action upon LDAP entry removal" to "Disable"
2. Create an LDAP entry
3. Sync LDAP users in GLPI (manual or crontab)
4. Remove the LDAP entry
5. Sync again (manual or crontab)
6. The user is not disabled 

**Expected behavior**

User should be disabled

**Server Infos**

OS : CentOS 7.4
PHP version : 5.6
Mysql version : 5.6

**Logs**

Apache error logs are empty
GLPI error logs also are empty

**Comment by Armin83** [comment]
Please close this issue - please use forum for future support request.
AND here is your solution:

https://forum.glpi-project.org/viewtopic.php?pid=352646#p352646
Post 2018-09-07 20:25:16

1. mass sync with action=2
2. of course you have to set "setup -> authentication ->setup -> set action when a user is deleted from the ldap directory. to disable

**Comment by trasher** [comment]
Thank you @Armin83 :)

**Comment by gillesdubois** [comment]
Hi @Armin83 @trasher,

My problem has been resolved by updating my GLPI installation.

@Armin83 as you can see in my issue, i already used action => 2 in the LDAP sync script (see the attachment).
Also, since it was working BEFORE the upgrade, it mean that the settings were correct before updating GLPI to 9.3.3. (GLPI don't reset it's configuration on every update...)

First line of the attached file : 

> [user@srv ~]#  php /path/to/glpi/scripts/ldap_mass_sync.php --action=2

As i said in action to reproduce "set action when a user is deleted from the LDAP directory" was already set to "disable" (first step).

> Set "Action upon LDAP entry removal" to "Disable"

Note : i give you that i didn't use the right term here

The most important thing is that my problem has been resolved and is not present in the newer version of the software.

However, closing an issue because it's irrelevant is OK but closing an issue without even bothering reading it is a bit frustrating.

Regards,
Gilles Dubois.

**Comment by bigben386** [comment]
@gillesdubois Could you explain in more details how you fixed this issue? I have exactly the same problem in 9.3.4. My users are not automatically disabled anymore even though they do not get returned by the ldap search and the user object shows "User missing in LDAP directory" yet the user is still active! We run have run the ldap mass sync script with action=2 for quite a while. It seems it probably stopped working when we upgraded to 9.3
