### ISSUE TITLE
getEmpty function for self service 

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#543]
The function getEmpty is not loaded into self service interface. 

In admin interface into showForm function of ticket.class.php, the function launch a check function then a can function and also getEmpty function. 

Into self service interface, there is no check so no can so no getEmpty function. 

Can we add this->getEmpty() in the showFormHelpdesk() function ?

**Comment by yllen** [comment]
In central interface you have 1 function for create and show ticket.
In simplified interface, you have a function to create a ticket  ShowFormHeldesk() where you don't have ID of the ticket and ShowForm() to view created ticket.
Why do you nedd getEmpty for simplified interface?

**Comment by tsmr** [comment]
It's for plugins. The hook getempty for plugins doesn't work on self service interface

**Comment by trasher** [comment]
Fixed from https://github.com/glpi-project/glpi/issues/1438
