### ISSUE TITLE
Can't close automatically a ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5435]
**In the configuration of my entity : autoclose ticket immediately**

=> I put a solution in my ticket, error 
[2019-02-21 11:49:15] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/yllen/git94/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  front/itilsolution.form.php:40         

and in debug mode
Fatal error: Class name must be a valid object or a string in /home/yllen/git94/front/itilsolution.form.php on line 40 

BUT the solution was added

Analyze:
itilsolution.form was called two times and the second time the $_POST is empty

**In the configuration of my entity : autoclose ticket set to 3 days**
=> I put a solution in my ticket => OK

I don't understand why the cron can block the adding of the solution

**Comment by yllen** [comment]
Précisions:
- Tested with and without plugin activated.
- No problem in 9.3-bugfixes

**Comment by yllen** [comment]
I make new search about this issue.
If your have a solution already defined in the ticket you don't have the error.

**Comment by yllen** [comment]
Issue introduce by correction of https://github.com/glpi-project/glpi/issues/5115

**Comment by guillermohaad** [comment]
@yllen 
hello yllen I was looking for you by sky and sea because I have a question to ask you about how I can change the path of the document repository in Glpi? I mean GLPI_DOC_DIR

Thank you

**Comment by trasher** [comment]
https://glpi-install.readthedocs.io/en/latest/install/index.html#files-and-directories-locations
