### ISSUE TITLE
[9.4] The ticket url has double slash

### ISSUE THREAD

**Issue by pedroluisvsousa** [glpi-project/glpi#5436]
Hi,

By clicking on the browser notification box area, the ticket page is opens, but with double slash in URL address.

![notifica_01](https://user-images.githubusercontent.com/26510405/53168784-3c197000-35ba-11e9-8060-b1b51b18aa2e.png)

![dupla_barra](https://user-images.githubusercontent.com/26510405/53168840-5e12f280-35ba-11e9-99d4-25b0e0172433.png)

The URL opens correctly when you click the URL link.

![notifica_02](https://user-images.githubusercontent.com/26510405/53168869-6f5bff00-35ba-11e9-86ea-f6a72e07d7ad.png)

![captura de tela de 2019-02-20 17-31-13](https://user-images.githubusercontent.com/26510405/53169430-f9f12e00-35bb-11e9-8df4-074cea0dc66a.png)

Regards.

**Comment by cedric-anne** [comment]
Hi,

To fix this we have to normalize the way we generate URL. Currently, we do not check if URL set in confg contains an ending slash or not, and we append almost everywhere a path that starts with a slash.

Not sure it is more than a cosmetic issue.

Regards

**Comment by pedroluisvsousa** [comment]
When I use the escalation plugin, this problem is shown.

![screenshot_2019-02-22 glpi - chamados - 11510](https://user-images.githubusercontent.com/26510405/53258341-2768d500-36ab-11e9-9b2a-a8924cc32bce.png)

Regards.

**Comment by trasher** [comment]
Then this is a plugin issue, please report issue against it. In GLPI core, this is only cosmetic and will be fixed in a future release.
