### ISSUE TITLE
No documents tab in Problem view 

### ISSUE THREAD

**Issue by laszlokertesz** [glpi-project/glpi#5438]
The Problem view is missing the Documents tab. I saw this in 9.4.0 and tried with the latest github code too.

So there is no way of assigning documents from the Problem view.
And even if i assign a document from the Documents view to the Problem, it cannot be viewed from the Problem view.

If there is a Document associated with the Problem there is a link in the main Problem view
"1 associated document" but if clicked it does nothing. It has the following format:

```
https://example.com/glpi//front/problem.form.php?id=1&forcetab=Document_Item$1
```

But clicking the page just reloads. Here is the Problem view (notice the lack of Documents tab):

![glpi](https://user-images.githubusercontent.com/7746354/53180082-9b4ca400-35fd-11e9-8ca7-8607d8c2bfd9.png)

**Comment by yllen** [comment]
In 9.4 documents are in processing problem tab

**Comment by cedric-anne** [comment]
Hi,

I confirm that in 9.4.0, you can add documents in Ticket/Problem/Change using the "Processing" tab.

Regards
