### ISSUE TITLE
Upgrading from 0.85.4 to 9.4.0 the OS data is not translated into the new database and innodb migration was not performed

### ISSUE THREAD

**Issue by laszlokertesz** [glpi-project/glpi#5440]
Upgrading from 0.85.4 to 9.4.0 the OS data is not translated into the new database (the script reports success).
All computers had blanks in the OS section.
We fixed this by runnig a script to update the computers that were missing this data with data extracted from the old glpi_computers table, but we were fortunate that we had backups.

Also the innodb table migration script is missing from 9.4.0 (the one from 9.3.3 works though).

**Comment by trasher** [comment]
For innodb migration, see: https://glpi-install.readthedocs.io/en/develop/command-line.html#from-myisam-to-innodb

**Comment by cedric-anne** [comment]
Hi,

Could you give us the script you used to fix the migration, or tell us which exact fields were not migrated to the new table ? It could help us to fix this bug.

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
