### ISSUE TITLE
Can't do followup after update 9.3 to 9.4

### ISSUE THREAD

**Issue by Arnaudfr31** [glpi-project/glpi#5442]
When i open a ticket, click on the followup button, an error appear :
"You don't have permission to perform this action"

**Comment by cedric-anne** [comment]
Hi,

We need more informations.
Have you some instaled plugins ?
Have you found something in your logs that can be related to this ?
Which rights do you have in your profile ?
What is your role on the ticket ?

Also, try to reproduce on https://demo.glpi-project.org/ and, if you can, give us the reproduction scenario.

Regards

**Comment by cedric-anne** [comment]
Hi,

We cannot reproduce your issue.
If you reproduce on 9.4 nightly build and without any activated plugins, feel free to reopen.

Regards
