### ISSUE TITLE
GLPI - Error in crontask

### ISSUE THREAD

**Issue by bhodeler** [glpi-project/glpi#5449]
Hi,

I recently installed version 9.4.0 of GLPI. Next I show you the information of the system:

[code]   GLPI 9.4.0 (/glpi => /home/impulso/public_html/glpi) Installation mode: TARBALL
--

Operating system: Linux server2.impulsohosting.es 2.6.32-042stab133.2 #1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64 PHP 7.1.26 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, calendar, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, soap, sockets, sqlite3, standard, tokenizer, wddx, xml, 	xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="90" memory_limit="512M" post_max_size="120M" safe_mode="" session.save_handler="files" 	upload_max_filesize="120M"  Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.6.41 	Server SQL Mode:  	Parameters: impulso_glpi@localhost/impulso_glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is not present xmlrpc extension is not present CAS extension is not present Database version seems correct (5.6.41) - Perfect! /home/impulso/public_html/glpi/files/_log : OK /home/impulso/public_html/glpi/config : OK /home/impulso/public_html/glpi/files : OK /home/impulso/public_html/glpi/files/_dumps : OK /home/impulso/public_html/glpi/files/_sessions : OK /home/impulso/public_html/glpi/files/_cron : OK /home/impulso/public_html/glpi/files/_graphs : OK /home/impulso/public_html/glpi/files/_lock : OK /home/impulso/public_html/glpi/files/_plugins : OK /home/impulso/public_html/glpi/files/_tmp : OK /home/impulso/public_html/glpi/files/_cache : OK /home/impulso/public_html/glpi/files/_rss : OK /home/impulso/public_html/glpi/files/_uploads : OK /home/impulso/public_html/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

htmLawed version 1.2.4 in (/home/impulso/public_html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/home/impulso/public_html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/home/impulso/public_html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/home/impulso/public_html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/impulso/public_html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/impulso/public_html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/home/impulso/public_html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/home/impulso/public_html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/home/impulso/public_html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/home/impulso/public_html/glpi/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/home/impulso/public_html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/home/impulso/public_html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/home/impulso/public_html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/impulso/public_html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/home/impulso/public_html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/home/impulso/public_html/glpi/vendor/symfony/console) leafo/scssphp in (/home/impulso/public_html/glpi/vendor/leafo/scssphp/src)

Not active

Way of sending emails: SMTP (soporte@impulsotecnologico.com@mail.impulsotecnologico.com)

Name: 'soporte@impulsotecnologico.com' Active: Yes 	Server: '{mail.impulsotecnologico.com/imap/ssl/novalidate-cert/notls}INBOX' Login: 'soporte@impulsotecnologico.com' Password: 		Yes Name: 'support@impulsotecnologico.com' Active: Yes 	Server: '{mail.impulsotecnologico.com/imap/ssl/novalidate-cert/notls}INBOX' Login: 'support@impulsotecnologico.com' Password: 		Yes Name: 'comercial@impulsotecnologico.com' Active: Yes 	Server: '{mail.impulsotecnologico.com/imap/ssl/novalidate-cert/notls}INBOX' Login: 'comercial@impulsotecnologico.com' Password: 		Yes

actualtime           Name: ActualTime                     Version: 1.1.0      State: Enabled 	fields               Name: Campos adicionales             Version: 1.9.1      State: Enabled 	behaviors            Name: Comportamientos                Version: 2.1.1      State: Not activated 	dashboard            Name: Dashboard                      Version: 0.9.4      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled 	mydashboard          Name: Mi Dashboard                   Version: 1.7.0      State: Enabled 	browsernotification  Name: Notificación de navegador      Version: 1.1.9      State: Enabled 	notifications        Name: Notifications                  Version: 9.3+1.0    State: Enabled
[/code]

The problem I have had for a few weeks now is that it sends me this error in the log file, and I don´t know what it is due to:

Toolbox::userErrorHandlerNormal() in /home/impulso/public_html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): unlink(/home/impulso/public_html/glpi/files/_tmp/auto_orient): Is a directory
  Backtrace :
  :                                                 
  inc/crontask.class.php:1602                        unlink()
  inc/crontask.class.php:829                         CronTask::cronTemp()
  front/cron.php:83                                  CronTask::launch()

Can you help me?

**Comment by cedric-anne** [comment]
Hi,

It is just a warning due to the fact that the cron responsible of cleaning the GLPI temp directory is trying to delete a directory as it would do for a file.
Can test the fix #5452 ?

Regards
