### ISSUE TITLE
display planning

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#545]
[0.90.2]
![090](https://cloud.githubusercontent.com/assets/12936722/13877656/95ad2782-ed0c-11e5-9a8f-220da38da49a.jpeg)

[0.91]
![091](https://cloud.githubusercontent.com/assets/12936722/13877660/9d624c78-ed0c-11e5-86c0-7a1fa528f3d2.jpeg)

**Comment by orthagh** [comment]
I don't cherry-pick the last commit, The planning is fully reworked in 0.91.

**Comment by yllen** [comment]
not correct in 0.90.2.
Look at the picture. The text of my task is "seconde tache" not "#a95166d...."

**Comment by yllen** [comment]
For 0.91 a have the title of the ticket instead of the content of the task

**Comment by orthagh** [comment]
For 0.91, as i say, i'll merge soon a PR who full rewrite it (#448).

For 0.90.x, can you provide a more specific way to replicate your issue

**Comment by yllen** [comment]
For 0.90.x a create a task "Nouvelle tache". In the planning the text is not the content of the task but the content of the ticket

**Comment by yllen** [comment]
For 9.1 button for plan the task is not active

**Comment by yllen** [comment]
New tests done this day.
Content of my ticket: test pour planification tache
Content of my planned task: Nouvelle tâche

For 0.90.4svn: In the planning i have the content of the ticket (test pour planification tache) instead of the content of the task (Nouvelle tâche)

For 9.1: Button for plan the task is not active

**Comment by orthagh** [comment]
button fixed

**Comment by orthagh** [comment]
For 0.90.4 part of this issue, as far i remember, ticket's task always displayed the title of ticket in planning (and not the content of the task).
I don't like very much this behavior, but, itiltasks don't have title field and truncates content to display it can render incorrectly.
I try to adress this behavior in 9.1 master, the itiltask events still display ticket title in the title of event but now also show content of the task in the content of the event. So i think it's a much comprehensive display.

If you agree with that, i think we can close this issue

**Comment by tomolimo** [comment]
Ok for me

**Comment by yllen** [comment]
Ok for me too.
