### ISSUE TITLE
admin rights and maybe other missing after php5.6 to php7.x update

### ISSUE THREAD

**Issue by EagleEnergy** [glpi-project/glpi#5453]
Hi,

Today I'm updating my GLPI 0.90.3 to 9.4.0.

For this I install steps by step GLPI 9.1 => 9.2 => 9.3.

During the update I have upgrade my PHP version to 5.6 and Mysql-server to 5.7

All working fine.

So now, I'm thinking PHP 5.6 is to old, I want to update to PHP 7.x.

Firstly I have upgraded to PHP 7.1 => reinstall GLPI 9.4.0 (to be sure)
i'm going to my plateforme and I loose my admi rights (LDAP auhtentication)

I upgrade to PHP7.2 => reinstall GLPI => same problem
And PHP7.3 same problem again.

It gives the impression to working but I loose my rights without any reason and I'm scarred to have others bugs due of this upgrade....

**Comment by cedric-anne** [comment]
Hi,

What do you mean by "reinstall" ? Are you talking about the application package or about the installation procedure that reinstall the database ?

If you just reinstall the package, it should not change anything. If run the GLPI installation procedure on an existing database, your existing data have been dropped to be replaced by a fresh GLPI instance.

If you do not reinstalled the GLPI DB from scratch, it may be a cache issue.
1. Try to restart your PHP server (apache or php-fpm for instance).
2. Try to remove the cache directory of GLPI (`files/_cache` if you do not customize the path).
3. Login and logout.

Regards

**Comment by EagleEnergy** [comment]
By reinstall I mean: Re download GLPI => extract => follow **upgrade** procedure (checks PHP extension, DB conneciton setup, ...)


I have followed your instructions: 

- Restart php-fpm 
- remove files/_cache 
- logout and login or login in new private window.

I have the same issue... :/

**Comment by cedric-anne** [comment]
I really have no idea of what is the problem. Many people uses GLPI with php 7.x and we run our test suites in php 5.6 and php 7.x, so I am not sure it is related to the php version itself, but maybe it is related to php configuration or extensions.

Can you check that you have same configuration and loaded extensions as in your 5.6 version ?

Can you also check if you have something in your logs that can be related to your problem ?

**Comment by trasher** [comment]
"step by step"? You'd rather upgrade to last release at once; issues may have been fixed (and this is far more simple trying to find a problem in one complex process rather than several ones).

**Comment by EagleEnergy** [comment]
Hello, sorry for my late answer.

@cedric-anne 
I have tryed to export my GLPI SQL base to multiples  fresh installs with same extensions
9.4.0 with PHP7.3 => Same problem
9.4.0 with PHP7.2 => Same problem
9.4.0 witth PHP7.1 => Same problem
9.4.0 with PHP5.6 => I have my rights

During each login action I have logged Nginx, FPM, MySQL and Slapd.

Alls comportements are exactly same. Nothing appear in logs...

@trasher All works fine with PHP5.6 so I assume my GLPI update was good.

**Comment by EagleEnergy** [comment]
I found a clue. By default my LDAP users are affect to LDAP-users profile

![image](https://user-images.githubusercontent.com/28734497/53501472-81eba200-3aac-11e9-86d9-0996de8aa562.png)

If I disable this profil as default profil I have my admins rights.

Why this default profil "overwrite" my super-admin profile with PHP7.x but not with 5.6...

**Comment by cedric-anne** [comment]
Hi,

I may have an explaination.

In PHP 7.0, [foreach no longer changes the internal array pointer](http://php.net/manual/en/migration70.incompatible.php#migration70.incompatible.foreach.array-pointer).

In our code, we init profiles data into session using a foreach (see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/session.class.php#L486), then, if default profile for user is not set or not existing in session context, we use the current element in available profiles (see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/session.class.php#L154).

So, theorically, `key($_SESSION['glpiprofiles'])` will not return the same value in PHP 5.6 and in PHP 7.x.

I do not have a test environment up. Can you try to debug and give us result using following patch ?
```diff
diff --git a/inc/session.class.php b/inc/session.class.php
index 16b64b0..4c9e382 100644
--- a/inc/session.class.php
+++ b/inc/session.class.php
@@ -146,11 +146,15 @@
 
                self::initEntityProfiles(self::getLoginUserID());
 
+               Toolbox::logWarning('available profiles:', array_keys($_SESSION['glpiprofiles']));
+
                // Use default profile if exist
                if (isset($_SESSION['glpiprofiles'][$auth->user->fields['profiles_id']])) {
+                  Toolbox::logWarning('default profile used:', $auth->user->fields['profiles_id']);
                   self::changeProfile($auth->user->fields['profiles_id']);
 
                } else { // Else use first
+                  Toolbox::logWarning('first profile used:', key($_SESSION['glpiprofiles']));
                   self::changeProfile(key($_SESSION['glpiprofiles']));
                }
 ```
It should log the profile id used in `files/_log/php-errors.log`.

**Comment by EagleEnergy** [comment]
On PHP7.3:
```
[2019-02-28 10:02:28] glpiphplog.WARNING: Session::init() in /var/www/glpi/inc/session.class.php line 149
available profiles: Array
  (
      [0] => 8
      [1] => 4
  )
   {"user":"35@976e826e0ce7","mem_usage":"0.454\", 9.97Mio)"} 
[2019-02-28 10:02:28] glpiphplog.WARNING: Session::init() in /var/www/glpi/inc/session.class.php line 157
first profile used: 8  {"user":"35@976e826e0ce7","mem_usage":"0.000\", 9.97Mio)"} 
```

On PHP5.6:
```
[2019-02-28 10:14:59] glpiphplog.WARNING: Session::init() in /var/www/glpi/inc/session.class.php line 148
available profiles: Array
  (
      [0] => 8
      [1] => 4
  )
   {"user":"35@inventory","mem_usage":"0.615\", 4.03Mio)"} 
[2019-02-28 10:14:59] glpiphplog.WARNING: Session::init() in /var/www/glpi/inc/session.class.php line 155
first profile used: 4  {"user":"35@inventory","mem_usage":"0.000\", 4.03Mio)"} 
```

**Comment by cedric-anne** [comment]
OK,

So we have the explaination why PHP 5.6 and PHP 7.x acts differently, it is due to the fact that the foreach which populates profiles 

But to be honest:
1. the array is populated based on profiles sorted by name,
2. we use on of them based on something that has no functionnal value (first or last),
3. we will drop usage of PHP 5.6 in next version.

So, it cannot really be considered as a bug and taking time to fix this difference of behaviour seems not really usefull.

If you want to be super admin by default, you should be able to do this by setting your default profile in your preferences.
![image](https://user-images.githubusercontent.com/33253653/53561399-11499180-3b4f-11e9-8004-3fa6b70d2315.png)

**Comment by EagleEnergy** [comment]
Ho yeah I can switch mannually between profils.

It's ok for me.
Maybe I can rename my profiles to prioritize super-admin, I don't know I'll test it.

Tanks you very much for time and explainations.
