### ISSUE TITLE
Network ports display broken (typo)

### ISSUE THREAD

**Issue by Stoatwblr** [glpi-project/glpi#5460]
There's a typo in the 9.4 release code which breaks network port display for _everything_.
I am surprised no one spotted this in testing (don't testers use network ports?)

see https://forum.glpi-project.org/viewtopic.php?id=167743

glpi/inc/networkportinstantiation.class.php           

line 289 
```
-                  'WHERE'  => ['networkports_id_list' => ['LIKE', '%"'.$netport-getID().'"%']]
+                  'WHERE'  => ['networkports_id_list' => ['LIKE', '%"'.$netport->getID().'"%']]

```
There are no other instances of this particular typo in the code. 
That does not mean there are other instances of "$this-something()"

**Comment by cedric-anne** [comment]
Hi,

Could you test 5462 ?

I searched for `\$\w+\s*-\s*\w+\s*\(` in the code and did not find any other occurenc of this kind of typo.

Regards
