### ISSUE TITLE
9.4 SQL syntax error - network port breakage

### ISSUE THREAD

**Issue by Stoatwblr** [glpi-project/glpi#5461]
Subselect syntax error

Every derived table (AKA sub-query) MUST have an alias. I.e. each query in brackets must be given an alias (AS whatever), which can the be used to refer to it in the rest of the outer query.

ie: the SQL here SHOULD be something like:

```
SELECT * FROM ((SELECT `networkports_id` FROM `glpi_networkportaliases` WHERE `networkports_id_alias` = '9481801') UNION ALL (SELECT `networkports_id` FROM `glpi_networkportaggregates` WHERE `networkports_id_list` LIKE '%"9481801"%') ) AS FOOBAR
```

NB: trying to alias the inner bracketed SELECT statements either side of the UNION will break things, it's the outer bracketed set that needs fixing.

As with the last bug I filed: this affects breaks network port display

=> sql-errors.log <==
[2019-02-24 11:59:19] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT * FROM ((SELECT `networkports_id` FROM `glpi_networkportaliases` WHERE `networkports_id_alias` = '9481801') UNION ALL (SELECT `networkports_id` FROM `glpi_networkportaggregates` WHERE `networkports_id_list` LIKE '%"9481801"%'))
  Error: Every derived table must have its own alias
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:569                          DBmysqlIterator->execute()
  inc/networkportinstantiation.class.php:289         DBmysql->request()
  inc/networkportethernet.class.php:162              NetworkPortInstantiation->getInstantiationHTMLTable()
  inc/networkportinstantiation.class.php:253         NetworkPortEthernet->getPeerInstantiationHTMLTable()
  inc/networkportethernet.class.php:174              NetworkPortInstantiation->getInstantiationHTMLTableWithPeer()
  inc/networkport.class.php:776                      NetworkPortEthernet->getInstantiationHTMLTable()
  inc/networkport.class.php:1196                     NetworkPort::showForItem()
  inc/commonglpi.class.php:485                       NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"11@msslyz.mssl.ucl.ac.uk"}

**Comment by cedric-anne** [comment]
Hi,

Is #5462 fix the problem ?

If yes, looks like we have to force definition of alias in `QueryUnion`  constructor.

Regards

**Comment by Stoatwblr** [comment]
It does, thanks.

**Comment by Stoatwblr** [comment]
Confirming that c471f9d fixes the issue.
