### ISSUE TITLE
Performance problem with a lot of queries done on information_table

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#5466]
Hello,
Since our migration from 9.1 to 9.2 we are experimenting a lot of slow downs :angry: 
And after some investigations, it seems that GLPI is doing a lot of SELECT TABLE_NAME FROM information_schema.`TABLES` ... see below:
![image](https://user-images.githubusercontent.com/7569958/53340623-c0952700-3909-11e9-8d69-65826693e841.png)

These lead me to the DBmysql::tableExists() function which seems to be called even during normal runtime of GLPI and not only during upgrade.

I've inserted a metric on the function call, and I measured that during a normal day this function may be called more than 1,144,508 times !!! See screen copy below for 2 hours the function has been called 286,127 times !!!
![2019-02-22 13_39_23-windows cache extension for php - statistics](https://user-images.githubusercontent.com/7569958/53341691-80837380-390c-11e9-81f3-d9357612f50e.png)

I'm going to propose a solution for this.

Thank you
Regards,

Tomolimo

**Comment by tomolimo** [comment]
These slow downs were especially experimented when the LDAP synchro (or OCS synchro) scheduled task was running, but not only. Sometimes there was no running cron, and the slow downs were present.
...

**Comment by trasher** [comment]
See #5502

**Comment by tomolimo** [comment]
This #5502 is only a part of the solution as tableExists is called a lot of time apart of fieldExists

**Comment by cedric-anne** [comment]
@tomolimo 

I started to reduce usage of tableExists method.

Most important gain will be on configuration loading. For 9.4.x, we still have to check existence of `glpi_config`/`glpi_configs` tables as we are still handling migrations from GLPI < 0.78. Enhancement has been done [here](https://github.com/glpi-project/glpi/pull/5474).
On master, [we completely removed checks](https://github.com/glpi-project/glpi/pull/5500) on config table as we only support migrations from versions that uses the `glpi_configs` table.

Other usages of this methods should not have a huge impact on performances as they are used on specific usecases.

**Comment by tomolimo** [comment]
Thank you @cedric-anne for this work.
But for sure there are some plugins that also uses this tableExists method intensively ... So that I did a solution that uses the GLPI_CACHE to cache the list of existing tables in the DB.
I'll do some tests on your solution and give you my feedback, but I'm going to be in holidays the next 2 weeks :)
Thank you
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
Hi,

I close this issue as it was related to previous GLPI versions.
Please free to reopen another issue with an analysis done on GLPI 9.5, if the problem still exists.

Regards
