### ISSUE TITLE
Clean-up "var" usage

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#547]
var is something remaining from the old PHP 4 time, and which is (probably) going to be [deprecated](https://wiki.php.net/rfc/var_deprecation) in PHP 7.1.

Moving everything to "public" is the trivial / simple way.
Perhaps more work may have value to check what really to be public and what is protected / private.

Notice: everything "public" is part of the API (used by plugins) and which should not change. "private" properties can be changed more easily.

**Comment by remicollet** [comment]
The RFC was declilned :)

So really no urgency on this one (despite still better to clean PHP 4 syntax)

**Comment by orthagh** [comment]
Ok.
Anyway, i agree on the need to clean

**Comment by yllen** [comment]
@remicollet  can you check if all OK for you and close this ticket if it's good?

**Comment by remicollet** [comment]
Seems ok.
