### ISSUE TITLE
Handle timezones

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#5475]
A [timezone plugin exists](https://github.com/tomolimo/timezones), but it does change many core fields, which is not recommended.

It is possible to handle timezones from the database engine either in MariaDB and PostgreSQL (for the future).

**Comment by tomolimo** [comment]
Hello
In fact this plugin is changing ALL the DATETIME fields into TIMESTAMP fields (which natively manage timezone in mySQL and MariaDB)
And this plugin is currently compliant to GLPI 9.1, and will be 9.2 and 9.3 very soon.
Regards,
Tomolimo

**Comment by trasher** [comment]
Yep, that's what I said: it changes core fields and data; this is a bit large for a plugin ;)

Anyways, managing this directly in the core would be better :)

**Comment by tomolimo** [comment]
Hello @trasher 
Nice work!
Did you also add this feature for DB replica?
Regards,
Tomolimo

**Comment by trasher** [comment]
Since this is handled on the main database objects, replicates should be handled as well

**Comment by trasher** [comment]
Oh, and alos, I do not have any replicate setup, I'm not really able to test that particular point ;)

**Comment by tomolimo** [comment]
cool :)

**Comment by felag** [comment]
Hello,

What impact does it have to NOT grant glpi database account a select permission on table mysql.timezone_name ?
(I have seen that users can be tied to a timezone. Is there any other impact ?)

Some context on my impact request:
In a galera cluster, mysql databases are not synchronized between nodes. So having access to such table is (currently) not acceptable for my IT department. They told me I can setup a dedicated mariadb server, but then I will lose database HA…
