### ISSUE TITLE
Group Project tasks in Gantt

### ISSUE THREAD

**Issue by StackAls** [glpi-project/glpi#5476]
**Describe the bug**

If I create project and few subproject and create some tasks in this subprojects, when I look GANTT this project - I see that all tasks are mixed.
Please add hierarchy group tasks for subprojects.

**To reproduce**

1. Go to 'Tools' - > 'Projects' and create project
2. Create few tasks
3. Create project 'as child of' first project
4. Create few tasks for this subproject
5. Look in first project GANTT
6. See this tasks and projects - all mixed

**Expected behavior**
I expected to see a hierarchy of projects and tasks.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Information about system installation and configuration
--
[code]   GLPI 9.3.3 (/glpi => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux sl062000080398.0062.pfr.ru 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 PHP 5.6.38 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar, 	ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, sockets, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="16M" safe_mode="" session.save_handler="files" 	upload_max_filesize="16M"  Software: Apache/2.4.6 (CentOS) PHP/5.6.38 () 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.10-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (10.3.10) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to files directory is protected : OK SELinux mode is Disabled

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) SimplePie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) TCPDF version 6.2.25 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iacaml/autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) phpCas version 1.3.5 in (/usr/share/pear)

Server: '10.62.0.235', Port: '389', BaseDN: 'dc=0062,dc=pfr,dc=ru', Connection filter: 		'(&(samaccountname=*)(&(objectClass=user)(objectCategory=person)))', RootDN: '062LDAPread@0062.pfr.ru', Use TLS: none

Not active

Way of sending emails: SMTP (glpi@10.62.0.77)

Name: 'glpi@062.pfr.ru' Active: No 	Server: '{10.62.0.77/pop}INBOX' Login: 'glpi' Password: Yes

fusioninventory      Name: FusionInventory                Version: 9.3+1.3    State: Enabled 	notifications        Name: Notifications                  Version: 9.3+1.0    State: Not installed 	tasklists            Name: Tasks list                     Version: 1.4.1      State: Not activated 	reports              Name: Отчеты                         Version: 1.12.0     State: Not activated 	shellcommands        Name: Служебные команды        Version: 2.2.2      State: Not activated 	formcreator          Name: Формы                          Version: 2.7.0-beta.1 State: Not activated
[/code]

![screenshot-797](https://user-images.githubusercontent.com/9604248/53478421-d4ff2e00-3a87-11e9-8ae7-ed179de5f6de.jpg)
![screenshot-796](https://user-images.githubusercontent.com/9604248/53478422-d4ff2e00-3a87-11e9-9177-46cfd9d703da.jpg)
![screenshot-795](https://user-images.githubusercontent.com/9604248/53478423-d4ff2e00-3a87-11e9-8d28-9d749ba96dcf.jpg)
![screenshot-794](https://user-images.githubusercontent.com/9604248/53478424-d4ff2e00-3a87-11e9-91cc-6505b3a1068e.jpg)
![screenshot-793](https://user-images.githubusercontent.com/9604248/53478425-d597c480-3a87-11e9-8858-c2c457de6558.jpg)
![screenshot-792](https://user-images.githubusercontent.com/9604248/53478426-d597c480-3a87-11e9-89ff-20d25d80d1a8.jpg)
![screenshot-791](https://user-images.githubusercontent.com/9604248/53478428-d597c480-3a87-11e9-964c-19f7948898ce.jpg)

**Comment by trasher** [comment]
Hi,

Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/)) or [on the demo](https//demo.glpi-project.org).

**Comment by StackAls** [comment]
Same result

**Comment by StackAls** [comment]
https://demo.glpi-project.org/front/project.form.php?id=7

**Comment by orthagh** [comment]
CF #5212 for project viz refresh, currently the used library is pretty outdate (and does not permits what you ask)

**Comment by derry43** [comment]
This issue still exists and relates to the GLPI PHP code rather than the js library.  The GLPI PHP is used to generate a list of projects and tasks in order and then it is submitedt to the jQuery.Gantt JS library. Issue is with GLPI code not with library.

**Comment by derry43** [comment]
GLPI code appears to sort tasks and projects based on start date value. This is fine for projects and tasks on the same level, but tasks and sub-projects should appear after their parent project/sub-project.

**Comment by derry43** [comment]
Can we re-open this?

**Comment by cedric-anne** [comment]
@derry43 

The Gantt view has been reviewed in master branch.

You install the [master nightly build](https://nightly.glpi-project.org/glpi/) on a test server to test it. Unless I am wrong this enhancement has been done.

Reagrds
