### ISSUE TITLE
Browser bug macos safari

### ISSUE THREAD

**Issue by dwtz** [glpi-project/glpi#5479]
**Describe the bug**
macOS (10.13.6) / Safari Browser
if you create a new ticket and want to add a device, the list looks like in First.JPG. If you close the field and open it again everything is correct (Second.jpg).

**Page(s) URL**

front/helpdesk.public.php?create_ticket=1

**To reproduce**

1. Reload page
2. Click on 'My devices'

**Expected behavior**

that it would work the first time.

**Screenshots**
![first](https://user-images.githubusercontent.com/21999928/53495087-7a71cc00-3a9f-11e9-8bdb-08b426e50b88.jpg)
![second](https://user-images.githubusercontent.com/21999928/53495097-7e9de980-3a9f-11e9-89a7-57ad28a86ebe.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.4.0

**Comment by cedric-anne** [comment]
Hi,

Looks like this is a known bug on the select2 component we use, see https://github.com/select2/select2/issues/4678 .
Unfortunately, looks like noone is working on it.

I do not have a MacOS env, so I cannot help.

Regards

**Comment by trasher** [comment]
We cannot fix used libs issues, please see bug on select2.
