### ISSUE TITLE
Moving network ports to other devices Bug? Or feature request?

### ISSUE THREAD

**Issue by Stoatwblr** [glpi-project/glpi#5480]
Network devices for any GLPI entity can be selected and "moved" to another "computer" or "network device" - but not to "printer" "device" "pdu", etc - the target list really needs to track the list of device categories that have network ports,

**Comment by trasher** [comment]
Even if there is something incoherent; this is not a bug.
This may cause side effects, and network ports part is one of the most complex in thee whole project; so this can only be handled as a feature.

Please use [suggestion website](http://suggest.glpi-project.org) then ;)
