### ISSUE TITLE
[0.90.1] Ticket's "Last update" date/time: do not consider any more validations

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#549]
Hello, 
 if a ticket is validated, the "last update" date is not updated .
For example, If In the historical Tab the validation events is shown as last event with the correct date , anyway the field " last update" is not updated.

davide

**Comment by yllen** [comment]
cycle of validation is different of cycle of ticket.
So last update of the ticket doesn't include validation actions

**Comment by Giudy** [comment]
Got it, but before 0.90 it was like this... then it is not coherent with the history of the ticket that include also validations actions...

**Comment by yllen** [comment]
I make a new test with the last 0.90 version.
If i change something for validation i can see my actions in Historical tab
