### ISSUE TITLE
upgrade to 9.3.3 checkdb.php table schema differs

### ISSUE THREAD

**Issue by alessiotomelleri** [glpi-project/glpi#5492]
Recently upgraded from 9.3.2 to 9.3.3

### Enviroment:

GLPI 9.3.3 (/glpi => /usr/share/glpi) Installation mode: RPM
Operating system: Linux glpi.arpa.veneto.it 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 PHP 7.2.15 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.15 () 	Mozilla/5.0 (X11; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0 Server Software: MariaDB Server 	Server Version: 10.3.13-MariaDB 	Server SQL Mode:  	Parameters: glpiadmin@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP
...

Checking db it shows : 
[root@glpi scripts]# php checkdb.php 
```
Config::getCache() in /usr/share/glpi/inc/config.class.php line 2985
An exception was raised while creating "Zend\Cache\Storage\Adapter\Apcu"; no instance returned Table schema differs for table glpi_itilsolutions
--- Original
+++ New
@@ @@
 create table `glpi_itilsolutions` (
   `id` int(11) not null auto_increment
   `itemtype` varchar(100) not null
   `items_id` int(11) not null default '0'
   `solutiontypes_id` int(11) not null default '0'
-  `solutiontype_name` varchar(255) null default null
+  `solutiontype_name` varchar(255) default null
   `content` longtext
   `date_creation` datetime default null
   `date_mod` datetime default null
   `date_approval` datetime default null
   `users_id` int(11) not null default '0'
-  `user_name` varchar(255) null default null
+  `user_name` varchar(255) default null
   `users_id_editor` int(11) not null default '0'
   `users_id_approval` int(11) not null default '0'
-  `user_name_approval` varchar(255) null default null
+  `user_name_approval` varchar(255) default null
   `status` int(11) not null default '1'
-  `ticketfollowups_id` int(11) default null 
+  `ticketfollowups_id` int(11) default null
   primary key (`id`)

Table schema differs for table glpi_racks
--- Original
+++ New
@@ @@
   `room_orientation` int(11) not null default '0'
-  `position` varchar(50)
+  `position` varchar(50) default null
   `bgcolor` varchar(7) default null
   `max_power` int(11) not null default '0'
   `mesured_power` int(11) not null default '0'
   `max_weight` int(11) not null default '0'
   `date_mod` datetime default null
   `date_creation` datetime default null
   primary key (`id`)
 
Table schema differs for table glpi_items_racks
--- Original
+++ New
@@ @@
   `position` int(11) not null
-  `orientation` tinyint(1)
+  `orientation` tinyint(1) default null
   `bgcolor` varchar(7) default null
   `hpos` tinyint(1) not null default '0'
   `is_reserved` tinyint(1) not null default '0'
   primary key (`id`)
   unique key `item` (`itemtype`,`items_id`,`is_reserved`)
<cut some other schema differs...> 
```
Is it a problems ?  If I'll upgrade to 9.4 this lead me to issue...  I have to do something ?

thx in advance

**Comment by trasher** [comment]
That is not a bug. Most of the differences are case not properly handled during schemas comparison. Also, database schema checks are done from CI on each commit; all is fine.
