### ISSUE TITLE
Error wshen doing a transfer

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5497]
Fatal error: Call to undefined method DB::requests() in /home/yllen/git94/inc/transfer.class.php on line 978

**Comment by MxpOZORUS** [comment]
Sorry but it's works sometimes but sometimes i have this:

**Comment by cedric-anne** [comment]
Hi,

Try #5503 for this problem.

Regards

**Comment by MxpOZORUS** [comment]
Ok i do it but now at the same line:


( ! ) Fatal error: Uncaught Error: Call to a member function next() on null in C:\wamp64\www\glpi\inc\transfer.class.php on line 1322
--

**Comment by MxpOZORUS** [comment]
Thanks a lot it's works.
But there is a mistake in the solution: $row = $$items_iterator->next(); 
1 dollars need to be deleted for this: $row = $items_iterator->next();
