### ISSUE TITLE
Many sql errors when doing a transfer

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5499]
``==> sql-errors.log <==
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_computers_items` LEFT JOIN `glpi_monitors` ON (`glpi_computers_items`.`items_id` = `glpi_monitors`.`id` AND `glpi_computers_items`.`itemtype` = 'Monitor') WHERE `glpi_monitors`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_monitors` ON (`glpi_computers_items`.`items_id` = `glpi_monitors' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:338                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly"} 
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_computers_items` LEFT JOIN `glpi_phones` ON (`glpi_computers_items`.`items_id` = `glpi_phones`.`id` AND `glpi_computers_items`.`itemtype` = 'Phone') WHERE `glpi_phones`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_phones` ON (`glpi_computers_items`.`items_id` = `glpi_phones`.`i' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:338                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.003\", 29.50Mio)"} 
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_computers_items` LEFT JOIN `glpi_peripherals` ON (`glpi_computers_items`.`items_id` = `glpi_peripherals`.`id` AND `glpi_computers_items`.`itemtype` = 'Peripheral') WHERE `glpi_peripherals`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_peripherals` ON (`glpi_computers_items`.`items_id` = `glpi_perip' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:338                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.49Mio)"} 
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_computers_items` LEFT JOIN `glpi_printers` ON (`glpi_computers_items`.`items_id` = `glpi_printers`.`id` AND `glpi_computers_items`.`itemtype` = 'Printer') WHERE `glpi_printers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_printers` ON (`glpi_computers_items`.`items_id` = `glpi_printers' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:338                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.003\", 29.50Mio)"} 
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_computers_softwareversions` LEFT JOIN `glpi_computers` ON (`glpi_computers_softwareversions`.`computers_id` = `glpi_computers`.`id`) WHERE `glpi_computers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_computers` ON (`glpi_computers_softwareversions`.`computers_id` ' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:379                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.50Mio)"} 
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_computers_softwareversions` LEFT JOIN `glpi_softwareversions` ON (`glpi_computers_softwareversions`.`softwareversions_id` = `glpi_softwareversions`.`id`) WHERE `glpi_softwareversions`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_softwareversions` ON (`glpi_computers_softwareversions`.`softwar' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:391                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.50Mio)"} 
[2019-03-01 14:36:41] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_softwareversions` LEFT JOIN `glpi_softwares` ON (`glpi_softwareversions`.`softwares_id` = `glpi_softwares`.`id`) WHERE `glpi_softwares`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_softwares` ON (`glpi_softwareversions`.`softwares_id` = `glpi_so' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:403                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.50Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_computers` ON (`glpi_contracts_items`.`items_id` = `glpi_computers`.`id` AND `itemtype` = 'Computer') WHERE `glpi_computers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_computers` ON (`glpi_contracts_items`.`items_id` = `glpi_compute' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:575                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.038\", 29.57Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_contracts`.`id`) WHERE `glpi_contracts`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_con' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:587                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.57Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_monitors` ON (`glpi_contracts_items`.`items_id` = `glpi_monitors`.`id` AND `itemtype` = 'Monitor') WHERE `glpi_monitors`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_monitors` ON (`glpi_contracts_items`.`items_id` = `glpi_monitors' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:575                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_contracts`.`id`) WHERE `glpi_contracts`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_con' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:587                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_peripherals` ON (`glpi_contracts_items`.`items_id` = `glpi_peripherals`.`id` AND `itemtype` = 'Peripheral') WHERE `glpi_peripherals`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_peripherals` ON (`glpi_contracts_items`.`items_id` = `glpi_perip' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:575                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_contracts`.`id`) WHERE `glpi_contracts`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_con' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:587                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_printers` ON (`glpi_contracts_items`.`items_id` = `glpi_printers`.`id` AND `itemtype` = 'Printer') WHERE `glpi_printers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_printers` ON (`glpi_contracts_items`.`items_id` = `glpi_printers' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:575                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_items` LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_contracts`.`id`) WHERE `glpi_contracts`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_contracts` ON (`glpi_contracts_items`.`contracts_id` = `glpi_con' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:587                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_suppliers` LEFT JOIN `glpi_contracts` ON (`glpi_contracts_suppliers`.`contracts_id` = `glpi_contracts`.`id`) WHERE `glpi_contracts`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_contracts` ON (`glpi_contracts_suppliers`.`contracts_id` = `glpi' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:636                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contracts_suppliers` LEFT JOIN `glpi_suppliers` ON (`glpi_contracts_suppliers`.`suppliers_id` = `glpi_suppliers`.`id`) WHERE `glpi_suppliers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_suppliers` ON (`glpi_contracts_suppliers`.`suppliers_id` = `glpi' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:648                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.010\", 29.58Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_infocoms` LEFT JOIN `glpi_computers` ON (`glpi_infocoms`.`items_id` = `glpi_computers`.`id` AND `glpi_infocoms`.`itemtype` = 'Computer') WHERE `glpi_computers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_computers` ON (`glpi_infocoms`.`items_id` = `glpi_computers`.`id' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:820                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.68Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_infocoms` LEFT JOIN `glpi_monitors` ON (`glpi_infocoms`.`items_id` = `glpi_monitors`.`id` AND `glpi_infocoms`.`itemtype` = 'Monitor') WHERE `glpi_monitors`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_monitors` ON (`glpi_infocoms`.`items_id` = `glpi_monitors`.`id` ' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:820                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.68Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_infocoms` LEFT JOIN `glpi_peripherals` ON (`glpi_infocoms`.`items_id` = `glpi_peripherals`.`id` AND `glpi_infocoms`.`itemtype` = 'Peripheral') WHERE `glpi_peripherals`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_peripherals` ON (`glpi_infocoms`.`items_id` = `glpi_peripherals`' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:820                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.68Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_infocoms` LEFT JOIN `glpi_printers` ON (`glpi_infocoms`.`items_id` = `glpi_printers`.`id` AND `glpi_infocoms`.`itemtype` = 'Printer') WHERE `glpi_printers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_printers` ON (`glpi_infocoms`.`items_id` = `glpi_printers`.`id` ' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:820                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.68Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contacts_suppliers` LEFT JOIN `glpi_contacts` ON (`glpi_contacts_suppliers`.`contacts_id` = `glpi_contacts`.`id`) WHERE `glpi_contacts`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_contacts` ON (`glpi_contacts_suppliers`.`contacts_id` = `glpi_co' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:871                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.68Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_contacts_suppliers` LEFT JOIN `glpi_suppliers` ON (`glpi_contacts_suppliers`.`suppliers_id` = `glpi_suppliers`.`id`) WHERE `glpi_suppliers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_suppliers` ON (`glpi_contacts_suppliers`.`suppliers_id` = `glpi_' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:883                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.68Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_documents_items` LEFT JOIN `glpi_computers` ON (`glpi_documents_items`.`items_id` = `glpi_computers`.`id` AND `glpi_documents_items`.`itemtype` = 'Computer') WHERE `glpi_computers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_computers` ON (`glpi_documents_items`.`items_id` = `glpi_compute' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:937                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.001\", 29.69Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_documents_items` LEFT JOIN `glpi_monitors` ON (`glpi_documents_items`.`items_id` = `glpi_monitors`.`id` AND `glpi_documents_items`.`itemtype` = 'Monitor') WHERE `glpi_monitors`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_monitors` ON (`glpi_documents_items`.`items_id` = `glpi_monitors' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:937                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.69Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_documents_items` LEFT JOIN `glpi_peripherals` ON (`glpi_documents_items`.`items_id` = `glpi_peripherals`.`id` AND `glpi_documents_items`.`itemtype` = 'Peripheral') WHERE `glpi_peripherals`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_peripherals` ON (`glpi_documents_items`.`items_id` = `glpi_perip' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:937                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.69Mio)"} 
[2019-03-01 14:36:42] glpisqllog.ERROR: DBmysql::query() in /home/yllen/git94/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: DELETE FROM `glpi_documents_items` LEFT JOIN `glpi_printers` ON (`glpi_documents_items`.`items_id` = `glpi_printers`.`id` AND `glpi_documents_items`.`itemtype` = 'Printer') WHERE `glpi_printers`.`id` IS NULL
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LEFT JOIN `glpi_printers` ON (`glpi_documents_items`.`items_id` = `glpi_printers' at line 1
  Backtrace :
  inc/dbmysql.class.php:1044                         
  inc/transfer.class.php:937                         DBmysql->delete()
  inc/transfer.class.php:174                         Transfer->simulateTransfer()
  front/transfer.action.php:46                       Transfer->moveItems()
  {"user":"8@nelly","mem_usage":"0.002\", 29.69Mio)"}

**Comment by cedric-anne** [comment]
Hi,

Is it fixed by #5491 ?

Regards

**Comment by yllen** [comment]
@cedric-anne no it's another bug

**Comment by trasher** [comment]
```
 SQL: DELETE FROM `glpi_computers_items` LEFT JOIN `glpi_monitors` ON (`glpi_computers_items`.`items_id` = `glpi_monitors`.`id` AND `glpi_computers_items`.`itemtype` = 'Monitor') WHERE `glpi_monitors`.`id` IS NULL
```

If we add table name beetween delte and from, this is fixed. So #5491 fix this one as well.

**Comment by MxpOZORUS** [comment]
Hi Yllen,

It's the same problem than #5497 ?
Because i change the line 978 and now have an other line error...

**Comment by yllen** [comment]
@cedric-anne sorry your PR is OK for this bug

**Comment by yllen** [comment]
Same bug as https://github.com/glpi-project/glpi/issues/5478
