### ISSUE TITLE
Language personalization not saved on new login

### ISSUE THREAD

**Issue by isaconsas** [glpi-project/glpi#5506]
Hello,
we've recently installed 9.4 version. At a first look we noticed this two issues about language personalization:
1 - On first login on the new version, our lang personalization (IT) was lost. We had English instead.
2 - Language change seems to work only only on the active session so, if we logout and then login again, IT language is lost again (English instead).

Hope this can help you.
Best regards
Simone I
 

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by taicyber** [comment]
I also have same problem. Still waiting for the solution.

**Comment by trasher** [comment]
This seems to duplicate https://github.com/glpi-project/glpi/issues/5372
