### ISSUE TITLE
Only some Profile:* can be assignied to the contract notifications

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#5507]
Hi
GLPI 9.3.3 / 9.4.0

It could also be a feature request, if it is, then change it as you wish.

If we want to set the _requesting_ client on the ticket notification, everything is fine,
And we can also choose: _Administrator_, _Supervisor_, etc.

But when we want to do the same thing for contract notifications, we can't.
There is only the _profile: *_ and the _group: *_ the _group supervisor: *_ etc.

Not good at least for me.
When a notification for a contract is sent, all users of the entity receive it, simply because we can only choose Profile: Applicant.
As a contract is tied to a machine (a printer in our case), we simply want the user of this printer to be notified, not all other users of the entity.
I created another profile for those who manage the entity and if I have to send contract notifications to them, I put it in the contract notice.

To make things simpler:
**I think we need all the features of the recipients regardless of the notifications.**

Not formally a bug, but we have a lot of feedback from customers who do not understand why they receive a notification that does not concern them.

Thanks

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE. Thank you.
