### ISSUE TITLE
Field unicity across all itemtypes

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#551]
The idea would be to have unicity across itemtypes.
For example, an inventory number must be unique, whatever the itemtype.

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards

**Comment by rafael-prazeres** [comment]
Hi wawax, I posted your proposal on the [channel indicated by cedric-anne](https://glpi.userecho.com/communities/1/topics/2196-field-unicity-across-all-itemtypes). In fact, this enhancement reflects a clear need related to asset inventory control. Let's hope your proposal gets the attention it deserves.
