### ISSUE TITLE
Ticket created for all mailgate e-mails (even reply)

### ISSUE THREAD

**Issue by tomSDL** [glpi-project/glpi#5514]
Hi,

Upgraded to 9.4 on Friday. A

Tickets are being created for each e-mail reply. Please see sceenshot.

![image](https://user-images.githubusercontent.com/32687810/53738075-19bf0680-3e86-11e9-9996-47b4cac114f1.png)

I cant figure out why.

Any suggestions please?

Thanks,

Tom

**Comment by cedric-anne** [comment]
Hi,

This is a duplicate from #5283.

We added rights checking in GLPI 9.3.x for mail collector. Following comment is a good summary of how mails are handled now: #4889 (comment).

Regards
