### ISSUE TITLE
Unable to assign ticket to group (since 9.4)

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#5522]
Using GLPI v9.4

Previous v9.3.x version worked fine.

**PROBLEM:**
Even if a Group is configured to be able to be '**Assigned to**' a ticket (/front/group.form.php), it does not display in the ticket '**Assigned to**' (Group) drop-down.

We have found that if we edit the Group configuration (/front/group.form.php) and set '**Requester**' to '**Yes**', then the Group becomes available in the drop-down for assignable groups to a ticket.

This means that GLPI is checking against the wrong configuration option when deciding whether a Group can be '**Assigned**' to a ticket (it's incorrectly looking at the '**Requester**' option, instead of the '**Assigned to**' option.

**FURTHER EXPLANATION:**
The following configuration of a Group should mean the Group can be assigned to a ticket:
![image](https://user-images.githubusercontent.com/16598973/53810649-560a6980-3f4f-11e9-94d8-91d032515aaa.png)

But in GLPI 9.4 you can only assign a Group to a ticket, if you set the '**Requester**' to '**yes**'. We believe this to be a bug:

![image](https://user-images.githubusercontent.com/16598973/53810777-91a53380-3f4f-11e9-999b-c598410dbe00.png)

**Comment by cedric-anne** [comment]
Hi,

Could you try the fix from #5527 ?

Regards

**Comment by hgpit** [comment]
Looks good. Thank you! :)
