### ISSUE TITLE
Bug with search results

### ISSUE THREAD

**Issue by CDG47** [glpi-project/glpi#5526]
When we combine the search by status and by items seen, the result is false.

1. Go to https://demo.glpi-project.org/front/ticket.php
2. Write for exemple "category" for items seen contains
3. See bug

![image](https://user-images.githubusercontent.com/11661365/53816424-d6d36080-3f63-11e9-8e18-5f58682b761b.png)
![image](https://user-images.githubusercontent.com/11661365/53816469-e6eb4000-3f63-11e9-9b12-d9d9229d2d58.png)

**Comment by cedric-anne** [comment]
Hi,

Seems to duplicate #5493. It should be fixed by #5509.

Regards
