### ISSUE TITLE
[GLPI 0.90.1] No permission at delete followup email

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#553]
![bug_img0](https://cloud.githubusercontent.com/assets/15769828/14074852/715304f4-f4d4-11e5-9720-299131b9e5c4.png)
-------------------------------------------------------------------------------------------------------------------------
![bug_img1](https://cloud.githubusercontent.com/assets/15769828/14074857/794e600e-f4d4-11e5-8a24-edfcd94ab27e.png)
-------------------------------------------------------------------------------------------------------------------------
![bug_img2](https://cloud.githubusercontent.com/assets/15769828/14074864/7bc500a4-f4d4-11e5-9c71-6c68cec4f195.png)

**Comment by orthagh** [comment]
You need the right to update ticket to do this action

**Comment by jsamaniegog** [comment]
Thank you for comment. I have the right, of course,

**Comment by orthagh** [comment]
Ok, i have also the error.
I currently search for a fix

**Comment by orthagh** [comment]
So for resume , 
GLPI Core forbid the association of anonymous user (email only) for Assign Column.
The following code : https://github.com/glpi-project/glpi/blob/master/inc/commonitilactor.class.php#L83
is the cause.

This is intended, an anonymous actor can't handle a login on glpi and so can't handle the assigned ticket.

The true question is why the forms (creation and update) allows this behavior or why There isn't no error message

**Comment by yllen** [comment]
You have the input text to change the defined email.
By example, you assign the ticket to a supplier, but for this ticket, you know that this supplier ask to another supplier to solve this problem, so you can directly define this other supplier.
You assign a technician but this technician is not in the society and can't read his email. So you define another email (like when you are in intervention out of your society)

**Comment by orthagh** [comment]
It seems OK for me, i close.
