### ISSUE TITLE
GLPI 9.4 - Add new task or follow up from grid 

### ISSUE THREAD

**Issue by isaconsas** [glpi-project/glpi#5532]
Hello,
we've recently installed 9.4 version. Update seemed to be good but we noticed two (I suppose) bugs when adding a new Task or Follow Up from grid.

Rep Step:
1 - Select items from grid (single or massive)
2 - Click on Action
3 - Select 'Add a new task' or 'Add a new follow up'.
4 - In both cases no fields appear down the dropdowns. In case of  'Add a new follow up', as you can see in the attached images, only the post button appears (if you click it error is raised on right bottom of web page).

Hope this helps.
Please let me know if you need further details.
Simone

![glpi action new followup from grid](https://user-images.githubusercontent.com/48152775/53875554-08503880-4005-11e9-84d9-02080efb979a.JPG)
![glpi action new task from grid](https://user-images.githubusercontent.com/48152775/53875555-08503880-4005-11e9-966c-8c1582a304c6.JPG)

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by hgpit** [comment]
I can confirm that we have this exact same issue also.
