### ISSUE TITLE
9.4.0 Notificationqueue not send out via cron or glpi must send notifications manually

### ISSUE THREAD

**Issue by orosi** [glpi-project/glpi#5535]
Hi all, 
we are using GLPI 9.4.0 
PHP 7.2.15
Ubuntu 18.04 LTS
Problem : Follow-up not send to watchers and requesters when they are in Profile Self-Service
Notifications are safed in queue but not send automatically.
Must "select all > action > send" for sending.
Notification for admin users go out with no problems.
Maybe  there is a hidden setting I not found please help 

many thanks to all

**Comment by cedric-anne** [comment]
Hi,

I cannot replicate and I do not see any difference in notification process between admin users and self-service users.

1. Could you search in your logs if you see something that can be helpfull ?

2. For notifications that were not automatically sent, could you 
- switch to the "trashbin" view
![image](https://user-images.githubusercontent.com/33253653/54134498-6079a700-4418-11e9-9484-a10ee27bdc7b.png)
- give us notification data (see example below)
![image](https://user-images.githubusercontent.com/33253653/54134714-c23a1100-4418-11e9-8003-8deb3896e89b.png)
?

Regards

**Comment by drginfo** [comment]
Boa tarde, após atualização para a versão atual, as notificações não saem e ficam na fila de envio. Já configurei para GLPI / CLI e nada. Tem que enviar manualmente. Aparece diversos erros no log do apache "/var/www/html/glpi/files/_log/php-errors.log" como o citado abaixo:
tail -f /var/www/html/glpi/files/_log/php-errors.log
[2019-03-25 16:24:32] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: telegram_username
  Backtrace :
  plugins/telegrambot/inc/user.class.php:67          
  inc/plugin.class.php:1074                          PluginTelegrambotUser::item_update_user()
  inc/commondbtm.class.php:1360                      Plugin::doHook()
  inc/user.class.php:4810                            CommonDBTM->update()
  inc/auth.class.php:872                             User->getAuthToken()
  front/login.php:84                                 Auth->login()
  {"user":"10@xxxxx.xxxxxxxxxx.br","mem_usage":"2.703\", 2.58Mio)"} (xxxx=editado)

E ao executar o comando do cron manualmente também gera vários erros como o citado abaixo:

php /var/www/html/glpi/front/cron.php
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/glpi/inc/commondbtm.class.php on line 3807
PHP Stack trace:
PHP   1. {main}() /var/www/html/glpi/front/cron.php:0
PHP   2. include() /var/www/html/glpi/front/cron.php:38
PHP   3. include_once() /var/www/html/glpi/inc/includes.php:48
PHP   4. include_once() /var/www/html/glpi/inc/config.php:42
PHP   5. spl_autoload_call() /var/www/html/glpi/inc/dbconnection.class.php:41
PHP   6. glpi_autoload() /var/www/html/glpi/inc/dbconnection.class.php:41

Versão do GLPI: 9.4.1.1
Versão BD: Server version: 10.1.38-MariaDB-0ubuntu0.18.04.1
Sistema Operacional: Ubuntu 18.04
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

Dados do GLPI (Sistema):

Server
--
Operating system: Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 PHP 7.2.15-0ubuntu0.18.04.1
apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gearman, geoip, gettext, gmagick, gmp, 	gnupg, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mailparse, mbstring, memcache, memcached, mongodb, msgpack, 	mysqli, mysqlnd, openssl, pcre, pdo_dblib, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, solr, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) 

Setup: max_execution_time="30"
memory_limit="256M"
post_max_size="8M"
safe_mode=""
session.save_handler="files" 
upload_max_filesize="25M"
Software: Apache () 
Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/70.0.3538.77
Safari/537.36 Server 

Software: Ubuntu 18.04 
Server Version: 10.1.38-MariaDB-0ubuntu0.18.04.1 
Server SQL Mode:  
Parameters: glpi@localhost/glpi 
Host info: Localhost via UNIX socket

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.1.38) - Perfect!
/var/www/html/glpi/files/_log : OK
/var/www/html/glpi/config : OK
/var/www/html/glpi/files : OK
/var/www/html/glpi/files/_dumps : OK
/var/www/html/glpi/files/_sessions : OK
/var/www/html/glpi/files/_cron : OK
/var/www/html/glpi/files/_graphs : OK
/var/www/html/glpi/files/_lock : OK
/var/www/html/glpi/files/_plugins : OK
/var/www/html/glpi/files/_tmp : OK
/var/www/html/glpi/files/_cache : OK
/var/www/html/glpi/files/_rss : OK
/var/www/html/glpi/files/_uploads : OK
/var/www/html/glpi/files/_pictures : OK
Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Not active
Way of sending emails: SMTP+SSL (xxxxx@xxxxx.com.br@email-ssl.com.br)

Name: 'xxxxx@xxxx.com.br' Active: Yes 	Server: '{email-ssl.com.br/pop/ssl/novalidate-cert/notls}' Login: 'xxxx@xxxx.com.br' Password: Yes

behaviors
Name: Comportamental
Version: 2.2.0
State: Enabled
fusioninventory
Name: FusionInventory
Version: 9.4.0+1.0
State: Enabled
pdf
Name: Imprimir em PDF
Version: 1.4.0
State: Enabled
os
Name: Os
Version: 0.1.1
State: Enabled
dashboard
Name: Painel
Version: 0.9.6
State: Enabled
telegrambot
Name: TelegramBot
Version: 2.0.0
State: Enabled

**Comment by trasher** [comment]
@drginfo in english, please.

**Comment by drginfo** [comment]
Sorry, force of habit. good night, after updating to the current version, the notifications do not leave and are in the sending queue. I already configured for GLPI / CLI and nothing. You have to submit manually. Appear several errors in the apache log '/var/www/html/glpi/files/_log/php-errors.log' as quoted below:
tail -f /var/www/html/glpi/files/_log/php-errors.log
[2019-03-25 16:24:32] glpiphplog.ERROR: Toolbox :: userErrorHandlerNormal () in /var/www/html/glpi/inc/toolbox.class.php line 659
*** PHP Notice (8): Undefined index: telegram_username
Backtrace:
plugins / telegrambot / inc / user.class.php: 67
inc / plugin.class.php: 1074 PluginTelegrambotUser :: item_update_user ()
inc / commondbtm.class.php: 1360 Plugin :: doHook ()
inc / user.class.php: 4810 CommonDBTM-> update ()
inc / auth.class.php: 872 User-> getAuthToken ()
front / login.php: 84 Auth-> login ()
{'user': '10@xxxxx.xxxxxxxxxx.br', 'mem_usage': '2.703', 2.58Mio) '} (xxxx = edited)

And running the cron command manually also generates several errors like the one quoted below:

php /var/www/html/glpi/front/cron.php
PHP Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/glpi/inc/commondbtm.class.php on line 3807
PHP Stack trace:
PHP 1. {main}() /var/www/html/glpi/front/cron.php:0
PHP 2. include() /var/www/html/glpi/front/cron.php:38
PHP 3. include_once() /var/www/html/glpi/inc/includes.php:48
PHP 4. include_once() /var/www/html/glpi/inc/config.php:42
PHP 5. spl_autoload_call() /var/www/html/glpi/inc/dbconnection.class.php:41
PHP 6. glpi_autoload() /var/www/html/glpi/inc/dbconnection.class.php:41

Version of GLPI: 9.4.1.1
Version DB: Server version: 10.1.38-MariaDB-0ubuntu0.18.04.1
Operational system: Ubuntu 18.04
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"

GLPI Data (System):

Server
Operating system: Linux 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 PHP 7.2.15-0ubuntu0.18.04.1
apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gearman, geoip, gettext, gmagick, gmp, gnupg, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mailparse, mbstring, memcache, memcached, mongodb, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_dblib, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, solr, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)

Setup: max_execution_time="30"
memory_limit="256M"
post_max_size="8M"
safe_mode=""
session.save_handler="files"
upload_max_filesize="25M"
Software: Apache ()
Mozilla/5.0 (X11; Linux x86_64)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/70.0.3538.77
Safari/537.36 Server

Software: Ubuntu 18.04
Server Version: 10.1.38-MariaDB-0ubuntu0.18.04.1
Server SQL Mode:
Parameters: glpi@localhost/glpi
Host info: Localhost via UNIX socket

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.1.38) - Perfect!
/var/www/html/glpi/files/_log : OK
/var/www/html/glpi/config : OK
/var/www/html/glpi/files : OK
/var/www/html/glpi/files/_dumps : OK
/var/www/html/glpi/files/_sessions : OK
/var/www/html/glpi/files/_cron : OK
/var/www/html/glpi/files/_graphs : OK
/var/www/html/glpi/files/_lock : OK
/var/www/html/glpi/files/_plugins : OK
/var/www/html/glpi/files/_tmp : OK
/var/www/html/glpi/files/_cache : OK
/var/www/html/glpi/files/_rss : OK
/var/www/html/glpi/files/_uploads : OK
/var/www/html/glpi/files/_pictures : OK
Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Not active
Way of sending emails: SMTP+SSL (xxxxx@xxxxx.com.br@email-ssl.com.br)

Name: 'xxxxx@xxxx.com.br' Active: Yes Server: '{email-ssl.com.br/pop/ssl/novalidate-cert/notls}' Login: 'xxxx@xxxx.com.br' Password: Yes

behaviors
Name: Comportamental
Version: 2.2.0
State: Enabled
fusioninventory
Name: FusionInventory
Version: 9.4.0+1.0
State: Enabled
pdf
Name: Imprimir em PDF
Version: 1.4.0
State: Enabled
os
Name: Os
Version: 0.1.1
State: Enabled
dashboard
Name: Painel
Version: 0.9.6
State: Enabled
telegrambot
Name: TelegramBot
Version: 2.0.0
State: Enabled

**Comment by cedric-anne** [comment]
@drginfo 

For first error (`*** PHP Notice (8): Undefined index: telegram_username`), it looks like it cames from the Telegram plugin. We cannot fix it on our side.

For second error (`PHP Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /var/www/html/glpi/inc/commondbtm.class.php on line 3807`), it looks like you have a PHP configuration issue. Trying to launch the cron with only 2MB memory allowed is a bit optimistic.

Regards
