### ISSUE TITLE
[9.4] Large image when document is attached to a followup

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#5536]
Hi ! 

I'm not sure it's a bug but since glpi 9.4, I have a strang display of mime type image : 

As you can see, the image take the size of a follow uo when a document is joined to a ticket 

![image](https://user-images.githubusercontent.com/12936546/53907775-2beba100-404e-11e9-910e-36dbcfa31c61.png)

Is it a bug or not ? Anyone saw that ? 

Thanks for your help.

**Comment by ciadch** [comment]
I try this behaviour with a fresh install of glpi 9.4. Same :-(

![image](https://user-images.githubusercontent.com/12936546/53909551-41fb6080-4052-11e9-8b75-0bf9f8945719.png)

**Comment by hgpit** [comment]
We also are seeing this issue.

**Comment by cedric-anne** [comment]
Duplicates #5363.

**Comment by ciadch** [comment]
Hi @cedric-anne !

Thanks for your replay, I didin't find the opened case :-)

I'll wait for the next release
