### ISSUE TITLE
"Results to Display on Homepage" count resetting to 5 every time logout and after login

### ISSUE THREAD

**Issue by ozalpmurat** [glpi-project/glpi#5537]
**Description**

I am using GLPI 9.4.0. Each time I log on, the 'Results to Display on Homepage' number is returning to 5. I see five tickets in each category on the main page. But when I look at the personal settings, I see what number I set. When I click on "Save" without making any changes, the number of tickets displayed on the main page is improved. When I log out and reopen it, it is back to the beginning.

**To reproduce**
1. Go to 'Personalization' tab under the user preferences
2. Set 'Results to Display on Homepage' more than 5 (i.e:25)
3. Go to homepage and see up to 25 tickets under every category
4. Logout and login again
5. Go to homepage and see only 5 tickets under every category

**Screenshots**

![image](https://user-images.githubusercontent.com/4588954/53935519-abfa2100-40b7-11e9-9ad4-11baa32b4bc0.png)

![image](https://user-images.githubusercontent.com/4588954/53935530-b1f00200-40b7-11e9-8b61-bc455ad4ed46.png)

**GLPI setup**

```
GLPI 9.4.0
Operating system: Linux 100-bis 4.15.18-11-pve #1 SMP PVE 4.15.18-34 (Mon, 25 Feb 2019 14:51:06 +0100) x86_64
PHP 7.1.17-0ubuntu0.17.10.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="200" memory_limit="2048M" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="80M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at bis.bilecik.edu.tr Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:65.0) Gecko/20100101 Firefox/65.0
Server Software: (Ubuntu)
	Server Version: 5.7.22-0ubuntu0.17.10.1
	Server SQL Mode: 
	Parameters: glpi-vt@localhost/glpi-vt
	Host info: Localhost via UNIX socket
```

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/5372
