### ISSUE TITLE
[GLPI 0.90.1] Don't sending new followups on email

### ISSUE THREAD

**Issue by valternugga** [glpi-project/glpi#554]
I created a ticket. Email notification arrived. Then go to "Processing ticket" and added a new followup. Email notification was not sended, but appears in Mail queue.(for my case 1 message). Then i add another followup. But in mail queue i see only first previous message. How can i solve problem?

**Comment by orthagh** [comment]
In queuemail process, we keep only the last notification with all these criteria : 
- same event (add ticket, add followup, etc)
- same item (ticket id)
- same recipient

This process added to merge multiple notifications to a same user.

If you want to send all notifications , setup you entit[y|ies] in notification tab, option "Delay before sending email notifications" to 0 minutes.

**Comment by orthagh** [comment]
No questions sinces days, i close this issue.
Feel free to reopen if you need

**Comment by guillermohaad** [comment]
Hello, orthagh 

I have of next problem in the version 0.90.: 

when sending an email reply to a ticket Followup The Followup is also displayed in format HTML:
![html_followup](https://cloud.githubusercontent.com/assets/12921805/15688507/04834e4e-2740-11e6-86f6-cb3618f13832.png)
