### ISSUE TITLE
9.4.1 Merge as followup attachment

### ISSUE THREAD

**Issue by miodzio97** [glpi-project/glpi#5542]
In GLPI 9.4.1 the function "Merge as followup" is not working properly.
Attachments included in the source ticket  are not transferred to followup.

**Comment by trasher** [comment]
ping @cconard96? Could you take care of this one?

**Comment by trasher** [comment]
BTW, 9.4.1 does not exists. You're either using 9.4.0 or current 9.4 nightly build, please precise @miodzio97.

**Comment by miodzio97** [comment]
Hmm...
The newest version from git.  
![image](https://user-images.githubusercontent.com/32955663/53958499-841fb300-40e1-11e9-8717-75a88561afb8.png)

[code]
GLPI 9.4.1 (/glpi => /usr/share/glpi)
Installation mode: RPM

**Comment by trasher** [comment]
Maybe not related, but `Installation mode: RPM` is not correct. From git version, you should have the branch and the commit sha displayed. I wonder if your setup is ok.

**Comment by cconard96** [comment]
@trasher @miodzio97 documents are not currently merged, just followups, but I will make that change tonight.

Should everything be merged? Approvals, tasks, items, etc? The original request was just for follow-ups I think.

**Comment by miodzio97** [comment]
Thank You.
Sorry I did not see the original request, but merge a larger number of elements seems to be logical.
Especially when the original request elements are removed.
Generally there is no complete ticket merge function, but your solution will be very good.

Yes, in my opinion, should be merged:

- all elements from "Processing ticket" (except solutions - this can cause a collision with ticket closing)
- Items

Optionally (if there are no collisions):
- Project
- Project task
- Knowledge base

**Comment by cconard96** [comment]
Right now, followups are duplicated and the ticket is deleted so that the original ticket can still be recovered from the bin later.

All other links could be duplicated as well (items, projects, etc).

**Comment by trasher** [comment]
> @trasher @miodzio97 documents are not currently merged, just followups, but I will make that change tonight.
> 
> Should everything be merged? Approvals, tasks, items, etc? The original request was just for follow-ups I think.

Looking first at the issue, I guess that was a bug; but it seems to be a feature finally... So there is no hurry.

Maybe @orthagh would have a opinion?

**Comment by orthagh** [comment]
Maybe for a start, we can add only documents and tasks.
For the first, it can break the timeline (document refered in a followup for example).

Other associated objects is subject to controversy.
