### ISSUE TITLE
Boundary problem with dropdown_limit

### ISSUE THREAD

**Issue by grahamj42** [glpi-project/glpi#5543]
**Describe the bug**

When the number of matches in a dropdown list retrieved from the database exceeds N items (where N is dropdown_max), the item N+1 is skipped. Noticed in ticket/category in version 9.3.0. It seems from the code that it's not limited to this usage and not updated in 9.4

**Page(s) URL**
/ajax/getDropdownValue.php

**To reproduce**

1. Go to 'Ticket...Create new ticket'
2. Click on 'Category'
3. Note the 5th to 7th category names in the dropdown list.
4. Go to 'Configuration...General' and change the Dropdown max items to 5.
5. Repeat steps 1 and 2.
6. Observe that the 6th category name is missing 

**Expected behavior**

All category names are presented.

**Logs**

No errors are logged.

**Comment by cedric-anne** [comment]
Hi,

Changes were made on this (for example https://github.com/glpi-project/glpi/pull/4829).

Please try on 9.4 if the problem persists.

Regards

**Comment by grahamj42** [comment]
Sorry, I had some finger trouble browsing the tags. The fix you mentioned is tagged 9.3.2, 9.3.3, so I'll try 9.3.3.

**Comment by grahamj42** [comment]
OK, it's fixed in 9.3.3 (commit 580ce05 on 26 Oct 2018).
Sorry to have bothered you.
