### ISSUE TITLE
9.4 : purge de la corbeille impossible

### ISSUE THREAD

**Issue by Sicoval31** [glpi-project/glpi#5548]
Bonjour,
actuellement sur une version 9.4 en TEST, j'ai constaté que : 
- les assets placés dans la corbeille sont mis à jour par Fusion (et non pas recréés) (ticket créé sur le forum bug FI)
- impossible de supprimer en masse ou individuellement les assets placés dans la corbeille. (ticket créé sur le forum bug glpi)

Le mode debug n'affiche pas d'informations lors de ces tentatives de suppression. En revanche, j'ai un plantage ZendFramework car la requête prend trop de temps.

PS : sur ce même serveur tourne un version 9.3.2 de TEST sans plantages ni malfonctions FI

**Comment by trasher** [comment]
Please use english and respect the issue tmeplate.

**Comment by cedric-anne** [comment]
Duplicates #5459.
