### ISSUE TITLE
Plugins not loading.

### ISSUE THREAD

**Issue by tomSDL** [glpi-project/glpi#5552]
Plugins will not load any longer.

I have cleared out the plugins folder. Reset permissions. They do not load. See screenshot.

**Logs**
```
[2019-03-08 09:01:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:01:18] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:04:17] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:04:17] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:39:36] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:39:37] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:39:37] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:39:37] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:40:15] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:40:29] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:40:31] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:41:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Unknown: Kerberos error: No Kerberos credentials available (try running kinit) for sdl-(errflg=1)
  Backtrace :
  :
  {"user":"@helpdesk"}
[2019-03-08 09:41:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:41:07] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:41:09] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:44:05] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
[2019-03-08 09:44:07] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
```

![image](https://user-images.githubusercontent.com/32687810/54021168-715fb980-4187-11e9-8a16-96cc62618708.png)

![image](https://user-images.githubusercontent.com/32687810/54021103-4aa18300-4187-11e9-90a4-5e8226d2258e.png)

[code]   GLPI 9.4.0 (/glpi => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux helpdesk 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 PHP 7.0.33-0ubuntu0.16.04.2 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, 	apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, 	json, ldap, libxml, mbstring, mcrypt, memcache, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, 	readline, recode, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="3000" memory_limit="2048M" post_max_size="300M" safe_mode="" session.save_handler="files" 	upload_max_filesize="300M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at  Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.25-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (5.7.25) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/var/www/html/glpi/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

appliances           Name: Appliances                     Version: 2.4.1      State: To be cleaned 	behaviors            Name: Behaviours                     Version: 2.2.0      State: To be cleaned 	certificates         Name: Certificates                   Version: 2.3.0      State: To be cleaned 	dashboard            Name: Dashboard                      Version: 0.9.0      State: To be cleaned 	databases            Name: Databases                      Version: 2.1.1      State: To be cleaned 	archimap             Name: Diagrams                       Version: 2.0.15     State: To be cleaned 	domains              Name: Domains                        Version: 2.1.0      State: To be cleaned 	environment          Name: Environment                    Version: 2.3.0      State: To be cleaned 	formcreator          Name: Forms                          Version: 2.7.0      State: To be cleaned 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: To be cleaned 	glpi2mdt             Name: GLPI 2 MDT                     Version: 0.2.1      State: To be cleaned 	mod                  Name: GLPI Modifications             Version: 1.3.0      State: To be cleaned 	openvas              Name: GLPi openvas Connector         Version: 1.2.0      State: To be cleaned 	geninventorynumber   Name: Inventory number generation    Version: 2.4.0      State: To be cleaned 	mydashboard          Name: My Dashboard                   Version: 1.7.0      State: To be cleaned 	order                Name: Orders management              Version: 2.4.0      State: To be cleaned 	manufacturersimports Name: Suppliers imports              Version: 2.1.2      State: To be cleaned
[/code]

**Comment by trasher** [comment]
This has been fixed already, try with lastest 9.4 nightly build

**Comment by tomSDL** [comment]
@trasher thanks, where do I find the nightly please?

**Comment by orthagh** [comment]
here is 
https://forge.glpi-project.org/tarballs/

Take 9.4/bugfixes

**Comment by cedric-anne** [comment]
Hi,

Looks more like a problem in Fusion Inventory plugin.
```
  *** PHP Notice(8): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION'
  Backtrace :
  inc/toolbox.class.php:676
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
  {"user":"@helpdesk"}
```

Regards

**Comment by tomSDL** [comment]
Thanks all.

That nightly has fixed the issue!

**Comment by tomSDL** [comment]
In order to get this to work I have to clean the plugin first. 

I dont want to lose forms or fusion inventory config.

**Comment by tomSDL** [comment]
This is still an issue. If I clean the plugin it then appears but I have lost all the config of that plugin.

![image](https://user-images.githubusercontent.com/32687810/54281517-cccbe600-4591-11e9-9d76-e679505eceb4.png)

If I clean the plugin it will then appear.

**Comment by cedric-anne** [comment]
Hi,

The clen function only removes the plugin status from database. If reinstall the plugin makes you lose data, then it is a problem in the plugin itself.

Regards

**Comment by tomSDL** [comment]
Hi,

All plugins I have previously used (forms, fusion, inventory, barcode) has this issue (except new/previously unused).

It is only when I clean, the plugin become available\active again.

I have had to clean all plugins so far. I haven’t cleaned fusion yet as I have a large amount of settings I don’t want to lose but I am getting to the point where I have too.

Thanks,

Tom

**Comment by tomSDL** [comment]
Hi,

I exported the sql tables out for fusion cleaned the plugin. Enabled it again and then reimported the tables.

Its fine now.

Tom

**Comment by guillermohaad** [comment]
Hi friend @tomSDL 
Hi, I have the same problem and I want you to explain more in detail how I solve it?
thank you

**Comment by cpasDav** [comment]
Hi,

I'm running glpi 9.5.5 on CentOS.
My plugins are not listed in plugin list so I can't install them.
I have correctly extracted the plugins folder into glpi folder, I have recursively set apache as owner and group.

Here are the logs:
PHP Warning (2): include_once(/var/www/html/glpi/plugins/karastock/setup.php): failed to open stream: Permission denied in /var/www/html/glpi/inc/plugin.class.php at line 1508
PHP Warning (2): include_once(): Failed opening '/var/www/html/glpi/plugins/karastock/setup.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/glpi/inc/plugin.class.php at line 1508
PHP Warning (2): include_once(/var/www/html/glpi/plugins/consumables/setup.php): failed to open stream: Permission denied in /var/www/html/glpi/inc/plugin.class.php at line 1508
PHP Warning (2): include_once(): Failed opening '/var/www/html/glpi/plugins/consumables/setup.php' for inclusion (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/glpi/inc/plugin.class.php at line 1508

Any idea?

Regtards

**Comment by betoxtrue** [comment]
Hi cpasDav,

If you're running GLPI on a Rhel server it's the Linux firewall and Selinux settings,
In my base I ran this way and and re-enabled the plugins, validate if you can run this before.

firewall-cmd --zone=public --add-service=mysql --permanent
firewall-cmd --zone=public --add-port=3306/tcp --permanent
firewall-cmd --permanent --zone=public --add-service=http
firewall-cmd --permanent --zone=public --add-service=https
firewall-cmd --reload

setsebool -P httpd_can_sendmail 1
setsebool -P httpd_can_network_connect 1
setsebool -P httpd_can_network_connect_db 1
setsebool -P httpd_mod_auth_ntlm_winbind 1
setsebool -P allow_httpd_mod_auth_ntlm_winbind 1
setenforce 0

**Comment by cpasDav** [comment]
Hi @betoxtrue,

I run your commands but I still have the same errors.
