### ISSUE TITLE
GLPI 9.4.1. Generating QR Code

### ISSUE THREAD

**Issue by miodzio97** [glpi-project/glpi#5570]
The url link contained in the QR code is generated with double text in link.
I choose all information to generate a QR code.
The code contains a url link that you have scanned:

My example:
URL = http://pg-ocs.xyz.pl/glpi/glpi/front/phone.form.php?id=3

Should be:
URL = http://pg-ocs.xyz.pl/glpi/front/phone.form.php?id=3

It's double "/glpi/glpi/"

**Comment by orthagh** [comment]
I think you should report to the plugin repository (Hint: https://github.com/pluginsGLPI/barcode).
Currently GLPI doesn't support natively QR code export
