### ISSUE TITLE
Accessing Install.php gives blank page

### ISSUE THREAD

**Issue by rmsilva1973** [glpi-project/glpi#5571]
**Describe the bug**
When accessing glpi for the first time and getting to install.php, I get a blank page. Enabling debug by commenting out "error_reporting(0)" on install.php, I get to see the following error on the browser:

4<br />
<b>Fatal error</b>:  Uncaught Error: Call to a member function has() on null in C:\dev\glpi\inc\plugin.class.php:1691
Stack trace:
#0 C:\dev\glpi\inc\session.class.php(613): Plugin::getPlugins()
#1 C:\dev\glpi\install\install.php(557): Session::loadLanguage()
#2 {main}
  thrown in <b>C:\dev\glpi\inc\plugin.class.php</b> on line <b>1691</b><br />

This error seems to be caused by GLPI_CACHE->has() method being invoked with the class not having been instantiated.

**Page(s) URL**

/install/install.php

**To reproduce**
Deploy the application and acccess it for the first time.

**Expected behavior**
Get to the installation wizard page.
**Logs**
No log generate

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
Unable to access it as install fails

**Comment by trasher** [comment]
You did not indicate what GLPI version you're using, so I assume you're talking about 9.4.0.

Similar issue(s) has been fixed already, please try  with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by cedric-anne** [comment]
Hi,

This error has been introduced recently on 9.4/bugfixes branch but was not part of a stable release. It has been fixed by https://github.com/glpi-project/glpi/pull/5564 yesterday.

Regards

**Comment by fray6c** [comment]
Hi, I have the same issue, apologies in advance as I am not that technical. I've downloaded and uncompressed the tarball file 9.4-bugfixes but that does not seem to have resolved the issue on my end. 

Could someone provide me with a step guide as to fix this issue on my test server?
Regards
