### ISSUE TITLE
GLPI 9.4.0 - Rejected ticket

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#5574]
**Describe the bug**

Ticket which are re-opened and solved again appears on "Rejected Ticket views" of the technician.

**To reproduce**

1. Open a ticket
2. Solve a ticket
3. Re-open a ticket (adding a follow up)
4. Solve it again with a new solution
5. Check the Technician Dashboard

**Expected behavior**

Normally the ticket appears on this view only when the ticket is rejected. If a new solution is added to the ticket, it should not not appears on the rejected ticket view.

**Screenshots**

![image](https://user-images.githubusercontent.com/16323410/54183531-ad0ac400-44a4-11e9-9da4-6a6b4e9f3e6a.png)

1 - The first solution is rejected
2 - The second solution is waiting for approval

![image](https://user-images.githubusercontent.com/16323410/54183391-59987600-44a4-11e9-95ee-8bfd7e5363ff.png)

Ticket appears on "rejected tickets"

**Comment by cedric-anne** [comment]
Hi,

#5576 should solve your issue.

Regards
