### ISSUE TITLE
Actions historical of processing ticket empty for 2 layout

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5582]
with classic view => not OK
![image](https://user-images.githubusercontent.com/12936722/54266540-de07f900-4577-11e9-8e75-3ec51d7edd32.png)

with vertical split => not OK
![image](https://user-images.githubusercontent.com/12936722/54266755-4c4cbb80-4578-11e9-816a-233cff8dcc0a.png)

with tabs on left => OK
![image](https://user-images.githubusercontent.com/12936722/54266840-7a320000-4578-11e9-949a-c8e2a0103e00.png)

Only ticket creation is missing.
For vertical split ans classic view you can see the text of the ticket on bottom or on left but you don't have creation date and author. You must go to historical tab to have these information.
For me 3 layout must display same thing.

**Comment by cedric-anne** [comment]
Hi @yllen ,

This is not really a bug, and not really a new feature. We discuss about it with @orthagh and @flegastelois and agree remove this "limitation. See #5596.

Regards
