### ISSUE TITLE
Uncaught Error: Call to undefined method Config::getCache() in /var/www/html/glpi/install/install.php:49\nStack trace:\n#0 {main}\n  thrown in /var/www/html/glpi/install/install.php on line 49

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#5583]
**Describe the bug**
When try install master branch get this error:
`Uncaught Error: Call to undefined method Config::getCache() in /var/www/html/glpi/install/install.php:49\nStack trace:\n#0 {main}\n  thrown in /var/www/html/glpi/install/install.php on line 49`
I solved this adding to inc/config.class.php the function getCache() from branch 9.4/bugfixes and `use Glpi\Cache\SimpleCache;`

**Comment by trasher** [comment]
In facts, cache on master is managed from dependency injection container, try:
```diff
diff --git a/install/install.php b/install/install.php
index 02435ecabc..78cb8c8d86 100644
--- a/install/install.php
+++ b/install/install.php
@@ -44,10 +44,6 @@ Config::detectRootDoc();
 $GLPI = new GLPI();
 $GLPI->initLogger();
 
-// $GLPI_CACHE is indirectly used in Session::loadLanguage() to retrieve list of plugins.
-global $GLPI_CACHE;
-$GLPI_CACHE = Config::getCache('cache_db');
-
 //Print a correct  Html header for application
 function header_html($etape) {
    global $CFG_GLPI;
```
