### ISSUE TITLE
Add the possibility to add several requester on ticket creation

### ISSUE THREAD

**Issue by neeftarah** [glpi-project/glpi#56]
Hi,

GLPI currently accept only one requester on ticket creation.

Some plugins (and GLPI users themselves) may want to add several requester on ticket creation.

We still can add more requesters on tickets update, but if we create tickets with no requesters or only one requester, we have the following problems:
- The "ticket creation notification" will not be send to all requesters
- If the requester is mandatory, the ticket creation failed

Regards,
Jérémy

**Comment by yllen** [comment]
It's a big job.
You must change:
- ticket creation form
- ticket template form
- business rules
....

**Comment by yllen** [comment]
You close the ticket but the request is not solved.
The request was: adding many requesters at the creation of a ticket
and your commit is "adding many watchers"

**Comment by orthagh** [comment]
Api now supports multiple actors on ticket creation. This issue requested for plugin. It's ok i think
I juste added the mutiple watcher in self-service in same commit

**Comment by yllen** [comment]
I verify: you can't add many requesters in the ticket creation form of a post-only.
You only have a single dropdown if ticket doesn't concerns me

**Comment by orthagh** [comment]
> I verify: you can't add many requesters in the ticket creation form of a post-only.
Yes but it's not the purpose of this issue.
@neeftarah (my office mate) requested the possibility to add several actors with api (for formcreator plugin)
The api now supports this with c8cbcd2 commit .
I added the possibility to add several watchers in self service in same commit.
It was the best test for the api code and an improvement to self-service form.
I always confronted this form with email, and we missed the possibility to add several CC/watchers.

I personally think we don't need several requesters in this interface.
If, again, we compare to email, you always have a single sender/requester.

For central interface, maybe we could add this enhancement, but it's a big work i wanted to delay to later.
