### ISSUE TITLE
Update error 9.4.1.1

### ISSUE THREAD

**Issue by dwtz** [glpi-project/glpi#5603]
**Describe the bug**

Web: Update error. Page is redirected to upgrade.php without css.

cp -rp itsm/* itsm-test/
cd itsm-test
tar xvfz /home/dw/glpi-9.4.1.1.tgz --strip 1
bin/console --lang=en_GB db:update --allow-unstable
The version of the database is not compatible with the version of the installed files. An update is necessary.

**Comment by cedric-anne** [comment]
Hi,

From which version did you try the update ?

Regards

**Comment by dwtz** [comment]
GLPI 9.4.0 ( => /var/www/html/itsm) Installation mode: TARBALL
--

Operating system: Linux itsm.otterbach.de 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 PHP 7.2.15 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, pdo_s

**Comment by cedric-anne** [comment]
OK.

1. You should not extract the archive on an existing GLPI directory, but create a new directory, extract the archive,n and then copy the `config/config_db.php` file, the `files` and the `plugins` directory of your old installation on this new directory.

2. You should try the command with the `--no-plugins` arg.

3. If the problem persist, you should try to remove the `files/_cache` directory.

**Comment by dwtz** [comment]
Hi @cedric-anne,

thanks. It is a plugin issue. 
before copying the plugins bin/console still works.
after copying the plugin directory you get the error message bin/console. 

It's the notifications plugin. 

Thanks.
Regards

**Comment by trasher** [comment]
@dwtz try to remove the following line:
https://github.com/ddurieux/glpi_notifications/blob/master/setup.php#L46

ANd open an issue against the plugin aswell ;)

**Comment by cedric-anne** [comment]
Hi

I reopened the issue as it looks like this is not so uncommon to have a plugin that makes this happen.

Fix is #5610 .

Regards
