### ISSUE TITLE
Knowledge Base br

### ISSUE THREAD

**Issue by dwtz** [glpi-project/glpi#5607]
**Describe the bug**

Hi,

If you make a new entry and format the text with pre, the edit view looks fine (edit.jpg)

![edit](https://user-images.githubusercontent.com/21999928/54437144-46033e80-4734-11e9-9965-7d50b8f6e5fc.jpg)
. 

In the main view, a br is always inserted.
![kb](https://user-images.githubusercontent.com/21999928/54437169-5a473b80-4734-11e9-858b-45104587e34c.jpg)

**Page(s) URL**

front/knowbaseitem.form.php

**Expected behavior**

Should pre not be displayed without br?

Regards

**Comment by pxlcore** [comment]
Hi,
I have the same problem in version 9.3.3.

**Comment by cedric-anne** [comment]
Should be fixed by #9011.
