### ISSUE TITLE
Network equipment and computer connection which is best can display the source and target each cabinet which equipment which port

### ISSUE THREAD

**Issue by mouse2008** [glpi-project/glpi#5613]
**Is your feature request related to a problem? Please describe.**

A clear and concise description of what the problem is. E.g. I'm always frustrated when [...]

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mouse2008** [comment]
Cabinets and devices that need to display the source and destination of the port connection

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.
If you want to implement this enhancement by yourself, feel free to reopen this issue and add a clear description of what your are going to do.

Regards
