### ISSUE TITLE
[9.4.1] Error FAQ Count

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#5616]
GIT 9.4.1 up to date : 

Simplified interface - counts are not good

![image](https://user-images.githubusercontent.com/13178158/54477787-52a69600-480b-11e9-9e80-4a52a9dc8629.png)

**Comment by trasher** [comment]
We're not able to reproduce on current 9.4/bugfixes branch. Either this has been fixed, or there are specificities in your data.

**Comment by tsmr** [comment]
It's due to
$kbitem_visibility_crit l264 on knowbase.class.php

If i comment it , i have good counts

**Comment by trasher** [comment]
@tsmr please test (asap) PR #5761 ;)
