### ISSUE TITLE
[9.4.1] Display FAQ articles - CSS problem

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#5617]
FAQ articles are over footer

![image](https://user-images.githubusercontent.com/13178158/54477837-ee380680-480b-11e9-8ffd-588c4282d6d6.png)

**Comment by tsmr** [comment]
#kb_browse {
    display: flex;
    align-items: stretch;
    border: 1px solid #e6e6e6;
    /* height: 100%; */
    min-height: 60vh;
    margin-left: -10px;
    margin-top: -5px;

Comment height: 100%; ?

**Comment by cedric-anne** [comment]
Hi,

Which browser do you use ?

Regards

**Comment by tsmr** [comment]
Sorry it's ok now. Certainly due to another problem
