### ISSUE TITLE
[9.4.1] Search FAQ articles - Console error

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#5618]
When you search for FAQ Articles

![image](https://user-images.githubusercontent.com/13178158/54477889-9d74dd80-480c-11e9-84cd-772470612afd.png)

There are no results & have error in console : 

![image](https://user-images.githubusercontent.com/13178158/54477898-bed5c980-480c-11e9-9bba-fb00e9968983.png)

![image](https://user-images.githubusercontent.com/13178158/54477901-ce551280-480c-11e9-9d25-8d5f1310d45c.png)

**Comment by cedric-anne** [comment]
Hi @tsmr ,

#5623 should fix this error.

Regards
