### ISSUE TITLE
[9.4.1.1] Error in the image link

### ISSUE THREAD

**Issue by KoDa-fr** [glpi-project/glpi#5619]
The link of each image in the ticket is corrupted.
The image does not appear and the link is as follows:
//front/document.send.php?docid=5787&tickets_id=38978
While there should be the domain before : 
https://domaine.net/front/document.send.php?docid=5787&tickets_id=38978

Tickets are created by the collector.

**Comment by cedric-anne** [comment]
Hi,

Can you try to remove the trailing `/` in `URL of the application` global configuration ?
![image](https://user-images.githubusercontent.com/33253653/54516833-5a2b8380-4960-11e9-9686-cdead4764c53.png)

This sould fix new collected tickets.

I will made a fix to trim this automatically.

Regards

**Comment by KoDa-fr** [comment]
Thank you, that corrected the problem. thank you so much
