### ISSUE TITLE
dbversion on database is incorrect in 9.4.1.1

### ISSUE THREAD

**Issue by rmsilva1973** [glpi-project/glpi#5620]
SQL installation script (install/mysql/glpi-empty.sql) populates glpi_configs table with incorrect dbversion on tag 9.4.1.1:

$ grep dbversion install/mysql/glpi-empty.sql
INSERT INTO `glpi_configs` VALUES ('178','core','dbversion','9.3-dev');

**Comment by trasher** [comment]
Version is set correctly from the install script, so this is not an issue (using the SQL file is not the way to install GLPI).

Also we're planning to move all those insertions from the SQL file into PHP code, so this kind of issue will disappear.
