### ISSUE TITLE
Errors on sql-errors 9.4.1.1

### ISSUE THREAD

**Issue by supervisando** [glpi-project/glpi#5622]
Is not a problem. Only write errors.

When show a ticket, Write one error sql

Glpi versión: 9.4 and 9.4.1.1 Tables innodb

Mysql :  8.0.15 MySQL Community Server

This is the log
[2019-03-18 08:18:10] glpisqllog.ERROR: DBmysql::query() in /my.glpi.es/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Ticket' AND `items_id` = '10467270' AND `is_deleted` = '0'
  Error: Column 'itemtype' in where clause is ambiguous
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:569                          DBmysqlIterator->execute()
  inc/dbutils.class.php:329                          DBmysql->request()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  inc/ticket.class.php:750                           countElementsInTable()
  inc/commonglpi.class.php:210                       Ticket->getTabNameForItem()
  inc/ticket.class.php:873                           CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:165                       Ticket->defineTabs()
  inc/commonglpi.class.php:634                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1002                      CommonGLPI->showPrimaryForm()
  front/ticket.form.php:217                          CommonGLPI->display()
  {"user":"98@my.glpi.es"}
[2019-03-18 08:18:11] glpisqllog.ERROR: DBmysql::query() in /my.glpi.es/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_items_tickets` INNER JOIN `glpi_tickets` ON (`glpi_items_tickets`.`tickets_id` = `glpi_tickets`.`id`) WHERE `itemtype` = 'Ticket' AND `items_id` = '10467270' AND `is_deleted` = '0'
  Error: Column 'itemtype' in where clause is ambiguous
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:569                          DBmysqlIterator->execute()
  inc/dbutils.class.php:329                          DBmysql->request()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  inc/ticket.class.php:750                           countElementsInTable()
  inc/commonglpi.class.php:210                       Ticket->getTabNameForItem()
  inc/ticket.class.php:873                           CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:165                       Ticket->defineTabs()
  inc/commonglpi.class.php:707                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1005                      CommonGLPI->showTabsContent()
  front/ticket.form.php:217                          CommonGLPI->display()
  {"user":"98@my.glpi.es","mem_usage":"1.207\", 7.08Mio)"}

I think the problem is in /inc/ticket.class.php 
lines
748						   'itemtype' => $item->getType(),
749						   'items_id' => $item->getID(),

**Comment by cedric-anne** [comment]
Hi,

Unless you did not follow the (install process)[https://glpi-install.readthedocs.io/en/latest/install/index.html] or (update process)[https://glpi-install.readthedocs.io/en/latest/update.html], you should not have an `itemtype` column in your `glpi_tickets` table, (which is the reason of your error).

If your were updating from an older version of GLPI, plese restore your backup and follow the update procedure. If your were installing GLPI for the forst time, get the latest release and reinstall it.

If the problem persist, feel free to reopen the ticket and give us more details about how you installed GLPI.

Regards

**Comment by supervisando** [comment]
Sorry.
I do not know why I had the itemtype columns, items_id in the table glpi_tickets
Thanks.
