### ISSUE TITLE
A technical cant add followup ou task

### ISSUE THREAD

**Issue by robsonjorgefernandez** [glpi-project/glpi#5628]
Hi,

I have the follow situation: 
A technical only can add followup or task if the right **See My Ticket** is cheked.

![see my tickets 03](https://user-images.githubusercontent.com/16673533/54533736-a6c78c80-4969-11e9-91bd-b084c60bda66.png)

Logged as technical
![see my tickets 01](https://user-images.githubusercontent.com/16673533/54533707-944d5300-4969-11e9-8fb1-1ceb49fb4d55.png)

The **Add** bar appears:
![see my tickets 02](https://user-images.githubusercontent.com/16673533/54533711-97484380-4969-11e9-8feb-da378a9d9d6b.png)

If I remove this right the technical can't add followup or task.

![no right 03](https://user-images.githubusercontent.com/16673533/54533794-c52d8800-4969-11e9-87af-cfbeeda3eab8.png)

Logged as technical
![no right 01](https://user-images.githubusercontent.com/16673533/54533790-c2cb2e00-4969-11e9-95a2-2f64feab1167.png)

The **Add** bar doesn't appear:
![no right 02](https://user-images.githubusercontent.com/16673533/54533793-c3fc5b00-4969-11e9-96ef-3b8261cf28e6.png)

This situation didn't happen on version 9.3.3 and begin after upgrade to 9.4.1.1

<details><summary>My system:</summary>
<p>

<pre>
{
    "glpi": {
        "uuid": "MRaizpbTXfhzZ2L5TTF3oGh69uCqutZNvF2NY6tR",
        "version": "9.4.1.1",
        "plugins": [
            {
                "key": "fusioninventory",
                "version": "9.4.0+1.0"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "0-500",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "0-500",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MariaDB Server",
            "version": "10.3.13-MariaDB-log",
            "size": "3122.3",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "Apache",
            "version": "2.4.34"
        },
        "php": {
            "version": "7.1.8",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqlnd",
                "PDO",
                "Phar",
                "posix",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sqlite3",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "xml",
                "xmlwriter",
                "xsl",
                "zip",
                "mysqli",
                "pdo_mysql",
                "pdo_sqlite",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "apcu",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "256M",
                "post_max_size": "8M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "5M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "Red Hat Enterprise Linux Server release 7.6 (Maipo)",
            "version": "3.10.0-957.10.1.el7.x86_64"
        }
    }
}
</pre>
</p>
</details>

**Comment by cedric-anne** [comment]
Hi,

Can you test #5630 fix ?

Regards

**Comment by robsonjorgefernandez** [comment]
It's works!

Thank you.

**Comment by cedric-anne** [comment]
Thanks for the feedback.

I reopen as fix is not yet merged.

Regards
