### ISSUE TITLE
9.4.0 to 9.4.1.1 database is not compatible with the version of the installed files

### ISSUE THREAD

**Issue by lekost93** [glpi-project/glpi#5632]
I am trying to upgrade from version 9.4.0 to 9.4.1.1 to solve the problem of automatic actions not running. Problem # 5558.
However when trying to update I have the following error:
The version of the database is not compatible with the version of the installed files. An update is necessary.
Print:
https://i.imgur.com/KKi6naL.png
So I click on Upgrade and nothing happens, the GLPI loads another page, without CSS, I can click a thousand times in upgrade and nothing happens:
https://imgur.com/a/sj3csQ2

I have already tested without cache and even from other computers.

My GLPI SETUP:
Information about system installation and configuration
[code]
 
GLPI 9.4.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux glpi 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64
PHP 7.0.32 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="200M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.0.32 mod_perl/2.0.9dev Perl/v5.16.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.2.22-MariaDB
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is not present
Database version seems correct (10.2.22) - Perfect!Database version seems correct (10.2.22) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-console in (/var/www/html/glpi/vendor/zendframework/zend-console/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

LDAP directories
 
Server: '192.168.2.10', Port: '389', BaseDN: 'dc=######,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: '#####\glpi', Use TLS:
		none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (ti@#### @mail.#####)

Mails receivers
 

Plugins list
 
	positions            Name: Cartografia                    Version: 4.5.1      State: Not activated
	fusioninventory      Name: FusionInventory                Version: 9.3+1.2    State: Not activated
	dashboard            Name: Painel                         Version: 0.9.6      State: Not activated

[/code]

**Comment by cedric-anne** [comment]
Hi,

Update fusioninventory to 9.4 compatible version and retry.

Regards

**Comment by maxwal41** [comment]
I see the same problem when trying to upgrade. 
FusionInventory 9.4.0+1.0 

[code]
 
GLPI 9.4.0 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

Server

 
Operating system: Windows NT Y 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586
PHP 7.1.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9 (Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9 Server at 192.168.1.101
	Port 80)
	Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
Server Software: mariadb.org binary distribution
	Server Version: 10.1.26-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
imap extension is installed
ldap extension is not present
Zend OPcache extension is not present
APCu extension is not present
xmlrpc extension is not present
CAS extension is not present
Database version seems correct (10.1.26) - Perfect!Database version seems correct (10.1.26) - Perfect!
OKC:\xampp\htdocs\glpi/files/_log : OK
OKC:\xampp\htdocs\glpi/config : OK
OKC:\xampp\htdocs\glpi/files : OK
OKC:\xampp\htdocs\glpi/files/_dumps : OK
OKC:\xampp\htdocs\glpi/files/_sessions : OK
OKC:\xampp\htdocs\glpi/files/_cron : OK
OKC:\xampp\htdocs\glpi/files/_graphs : OK
OKC:\xampp\htdocs\glpi/files/_lock : OK
OKC:\xampp\htdocs\glpi/files/_plugins : OK
OKC:\xampp\htdocs\glpi/files/_tmp : OK
OKC:\xampp\htdocs\glpi/files/_cache : OK
OKC:\xampp\htdocs\glpi/files/_rss : OK
OKC:\xampp\htdocs\glpi/files/_uploads : OK
OKC:\xampp\htdocs\glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed)
phpmailer/phpmailer version 6.0.6 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.2 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.2.26 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
zendframework/zend-cache in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-cache\src)
zendframework/zend-console in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-console\src)
zendframework/zend-i18n in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-i18n\src)
zendframework/zend-serializer in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-serializer\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
leafo/scssphp in (C:\xampp\htdocs\glpi\vendor\leafo\scssphp\src)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP+SSL (myhelp@trianglelab.ru@mail.megaprovider.ru)

Mails receivers

 
Name: 'myhelp@trianglelab.ru' Active: Yes
	Server: '{mail.megaprovider.ru:995/pop/ssl/novalidate-cert/notls}' Login: 'myhelp@trianglelab.ru' Password: Yes

Plugins list

 
	barcode              Name: Barcode                        Version: 2.1.0      State: Enabled
	costs                Name: Costs                          Version: 1.1.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled
	notifications        Name: Notifications                  Version: 9.3+1.0    State: To be cleaned
	reports              Name: Отчеты                         Version: 1.12.0     State: Not activated
	dashboard            Name: Панель отчетов              Version: 0.9.4      State: Enabled
	pdf                  Name: Печать в PDF                   Version: 1.4.0      State: Not activated
	mreporting           Name: Подробные отчеты          Version: 1.6.1      State: Enabled

**Comment by maxwal41** [comment]
I see the same problem when trying to upgrade.
FusionInventory 9.4.0+1.0 
[code]
 
GLPI 9.4.0 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

Server

 
Operating system: Windows NT Y 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) i586
PHP 7.1.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl,
	pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9 (Apache/2.4.27 (Win32) OpenSSL/1.0.2l PHP/7.1.9 Server at 192.168.1.101
	Port 80)
	Mozilla/5.0 (Windows NT 5.1; rv:52.0) Gecko/20100101 Firefox/52.0
Server Software: mariadb.org binary distribution
	Server Version: 10.1.26-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
imap extension is installed
ldap extension is not present
Zend OPcache extension is not present
APCu extension is not present
xmlrpc extension is not present
CAS extension is not present
Database version seems correct (10.1.26) - Perfect!Database version seems correct (10.1.26) - Perfect!
OKC:\xampp\htdocs\glpi/files/_log : OK
OKC:\xampp\htdocs\glpi/config : OK
OKC:\xampp\htdocs\glpi/files : OK
OKC:\xampp\htdocs\glpi/files/_dumps : OK
OKC:\xampp\htdocs\glpi/files/_sessions : OK
OKC:\xampp\htdocs\glpi/files/_cron : OK
OKC:\xampp\htdocs\glpi/files/_graphs : OK
OKC:\xampp\htdocs\glpi/files/_lock : OK
OKC:\xampp\htdocs\glpi/files/_plugins : OK
OKC:\xampp\htdocs\glpi/files/_tmp : OK
OKC:\xampp\htdocs\glpi/files/_cache : OK
OKC:\xampp\htdocs\glpi/files/_rss : OK
OKC:\xampp\htdocs\glpi/files/_uploads : OK
OKC:\xampp\htdocs\glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed)
phpmailer/phpmailer version 6.0.6 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.2 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.2.26 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
zendframework/zend-cache in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-cache\src)
zendframework/zend-console in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-console\src)
zendframework/zend-i18n in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-i18n\src)
zendframework/zend-serializer in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-serializer\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
leafo/scssphp in (C:\xampp\htdocs\glpi\vendor\leafo\scssphp\src)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP+SSL (myhelp@trianglelab.ru@mail.megaprovider.ru)

Mails receivers

 
Name: 'myhelp@######.ru' Active: Yes
	Server: '{mail.########.ru:995/pop/ssl/novalidate-cert/notls}' Login: 'myhelp@#######.ru' Password: Yes

Plugins list

 
	barcode              Name: Barcode                        Version: 2.1.0      State: Enabled
	costs                Name: Costs                          Version: 1.1.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled
	notifications        Name: Notifications                  Version: 9.3+1.0    State: To be cleaned
	reports              Name: Отчеты                         Version: 1.12.0     State: Not activated
	dashboard            Name: Панель отчетов              Version: 0.9.4      State: Enabled
	pdf                  Name: Печать в PDF                   Version: 1.4.0      State: Not activated
	mreporting           Name: Подробные отчеты          Version: 1.6.1      State: Enabled

**Comment by Dayflare** [comment]
i have the same error. Fusioninventory 9.4.0+1.0 is already installed.

**Comment by cedric-anne** [comment]
Hi,

Try with https://github.com/glpi-project/glpi/pull/5610

Regards

**Comment by Stoatwblr** [comment]
Same problem and #5610 fixes it for me.

**Comment by cedric-anne** [comment]
Thanks for the feedback.

I close as it duplicates #5603.

Regards

**Comment by 9160602200** [comment]
![image](https://github.com/glpi-project/glpi/assets/42964686/b7d15f7c-536f-4da0-87ae-715ef4afdc0f)
unable to install glpi latest version GLPI VERSION 10.0.14
share the screen for solution.
![glpi](https://github.com/glpi-project/glpi/assets/42964686/925542cf-af17-4824-bac7-56f861d239fd)
