### ISSUE TITLE
Possibility to assign VLAN to location/data center/server room

### ISSUE THREAD

**Issue by mariaczi** [glpi-project/glpi#5634]
**Describe the solution you'd like**

Have a possibility to assign VLAN (VLANID) to Location/DataCenter/Server room. Be able to check which VLAN ID are used in which DataCenter/Server Room.
Be able to see all this details about VLAN on the list in "Setup" -> "Dropdowns" -> "VLAN".

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by mariaczi** [comment]
Done: https://glpi.userecho.com/communities/1/topics/1009-possibility-to-assign-vlan-to-locationdata-centerserver-room ;)
