### ISSUE TITLE
Calendar in Initial Contract Duration 

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#5636]
Good afternoon
In contracts, the calculated period for the alarm is the "Initial Date" - "Initial Contract Duration".

However, only a list with closed months is displayed. But there are situations where contracts are not 30 days accurate, and can be contracted 15, 17 or 18 days. Is it possible to include "Calendar" in the list?

![Contratos](https://user-images.githubusercontent.com/35368369/54604932-c5d82400-4a26-11e9-84cc-223f4c3224b0.PNG)

**Comment by wikyyy123** [comment]
how to add calendar or set date of initial contract period.
