### ISSUE TITLE
Problems with plugins - GLPI 9.4.1.1

### ISSUE THREAD

**Issue by jvergacas** [glpi-project/glpi#5637]
I have updated GLPI to version 9.4.1.1 and am having problems with PLUGINS. They are installed and enabled but at some point they stop working and I have to disable and enable them again.

Plugins enabled:
![2019-03-19 12_03_36-Window](https://user-images.githubusercontent.com/43650152/54617663-756dc000-4a40-11e9-8090-364c35283c6a.png)

Plugins disabled:
![2019-03-19 12_04_23-Window](https://user-images.githubusercontent.com/43650152/54617724-97ffd900-4a40-11e9-98b5-c54c0e41e1dd.png)

**Comment by cedric-anne** [comment]
Hi,

After several iterations, I think I found a fix for this bug. Can you apply #5611 and check if the problem persists ?

Regards

**Comment by jvergacas** [comment]
Hi,

I have tested in my homologation environment and everything is working.
I'm going to install in the production environment, but I'm afraid I will not have any more problems now.

Thank you.

**Comment by cedric-anne** [comment]
Hi,

I made some more changes to the #5611 PR. You should maybe wait for an approval of it before pushing it in production.

Regards
