### ISSUE TITLE
Problem hiden actions historical after  glpi upgrade from 0.83.6 to 9.1.6

### ISSUE THREAD

**Issue by Mnbill** [glpi-project/glpi#5639]
Hello 

**Describe the bug**

I did a glpi upgrade from V0.83.6 to V9.1.6

the upgrade was okay

but  when i go to processing ticket --> actions historical i can't see the historical actions, just the first and docs (images ...)

PS: The actions are in my table glpi_tickettasks

**Expected behavior**

To see all my historical actions

**Environnement**
CentOS 6.7
GLPI 9.1.6

/bug
/need-help
/help

**Comment by trasher** [comment]
9.1 is not maintained from a while. Please update to last release.

**Comment by Mnbill** [comment]
I can't upgrade for now
