### ISSUE TITLE
GLPI 9.4.1.1 - simcard component broken (maybe other components as well)

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#5641]
Hi

I noticed that the simcard component triggers a fatal error when we "instanciate" them then edit them to associate to an asset. 

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. go to components, simcards
2. create a simcard template
3. create an instance of the simcard
4. click on Update to modify it
5. See the fatal error in item_devices.class.php

**Expected behavior**

No fatal error

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/

( ! ) Fatal error: Uncaught Error: Class '' not found in /home/dethegeek/public_html/glpi-94/inc/item_devices.class.php on line 82
--
1 | 0.0002 | 396752 | {main}(  ) | .../item_devicesimcard.form.php:0
2 | 0.1500 | 2595304 | include( '/home/dethegeek/public_html/glpi-94/front/item_device.common.form.php' ) | .../item_devicesimcard.form.php:36
3 | 0.8275 | 8184752 | Item_DeviceSimcard->display(  ) | .../item_device.common.form.php:87
4 | 0.8399 | 8269368 | Item_DeviceSimcard->showNavigationHeader(  ) | .../commonglpi.class.php:996
5 | 0.8401 | 8269976 | Item_DeviceSimcard->getName(  ) | .../commonglpi.class.php:864
6 | 0.8401 | 8269976 | Item_DeviceSimcard->getRawName(  ) | .../commondbtm.class.php:3484

```

The instanciated simcard in Items_devicesimcards has an empty string in the column itemtype.

If I manually set it to **Computer** for example, the fatal error vanishes. The involved code is related to a commit done 29 days ago.

**Screenshots**

![image](https://user-images.githubusercontent.com/14139801/54690644-1ed8b280-4b22-11e9-8d48-8a2d8c0a57f8.png)

```
paste here
```

**Comment by cconard96** [comment]
@btry Could you test the fix in #5647?
