### ISSUE TITLE
Signal > between entities names is not working in ticket category

### ISSUE THREAD

**Issue by guieloi** [glpi-project/glpi#5646]
Signal **>** between entities names is not working whe choice the category in a new ticket, example print

**Page(s) URL**

front/helpdesk.public.php?create_ticket=1

**To reproduce**

Access a child entity 
1. Go to 'Create new ticket'
2. Click on 'Category'
3. See "Entity **&gt;** ChildEntity"

**Expected behavior**

See "Cimcal > T.I."

**Screenshots**
![exemplobug](https://user-images.githubusercontent.com/4099326/54726256-16e43700-4b51-11e9-8b3d-33ea88468ffc.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.1.1 ,
Operating system: Linux us-imm-web176.main-hosting.eu 3.10.0-714.10.2.lve1.5.19.8.el7.x86_64 #1 SMP Wed Oct 24 08:54:57 EDT 2018
	x86_64
PHP 7.3.0 litespeed (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo,
	filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, libxml, litespeed, mbstring, mysqli, mysqlnd, openssl,
	pcntl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, session, shmop, soap, sockets, sqlite3, standard, tidy, tokenizer,
	wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="2400" memory_limit="512M" post_max_size="256M" safe_mode="" session.save_handler="files"
	upload_max_filesize="256M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.2.18-MariaDB
```

**Comment by ppenin** [comment]
same issue for me

**Comment by cedric-anne** [comment]
Hi,

Could you test with #5653 ?

Regards

**Comment by ppenin** [comment]
it doesn't work for me

**Comment by guieloi** [comment]
it doesn't work for me too

**Comment by cedric-anne** [comment]
I forgot that javascript files used provided by rpm/tarball are minified and renamed, so changing the custom.js files will not help if you installed GLPI in a normal way, unless you run GLPI in debug mode and force browser cache cleaning.

**Comment by ppenin** [comment]
i confirm. it only works in debug mode
