### ISSUE TITLE
[9.4.1.1] PHP erorrs.  inc\toolbox.class.php line 659

### ISSUE THREAD

**Issue by yustas84** [glpi-project/glpi#5649]
Disable all plugins. Error in the logs appeared, but rarely. Turned on only one, and the error is repeated many times a minute. Logs attached.
[php-errors - копия.log](https://github.com/glpi-project/glpi/files/2994911/php-errors.-.log)

**Comment by cedric-anne** [comment]
Hi,

Same problem as #5637.

Regards
