### ISSUE TITLE
update bug

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#565]
Bonjour,

Afin de tester la nouvelle release j'ai tenté la mise à jour depuis ma base actuelle et voici le message 
Mise à jour

Connexion à la base de données réussie

Traitement en cours...

Version 0.4

- Erreur durant l'éxecution de la requête : ALTER TABLE `glpi_users` DROP PRIMARY KEY - L'erreur est Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by wawax** [comment]
Hello,

From which version are you updating your GLPi ?

**Comment by satyan01** [comment]
effectively from 0.91 so ...
