### ISSUE TITLE
[9.4.1.1] PHP error in mailcollector

### ISSUE THREAD

**Issue by yustas84** [glpi-project/glpi#5650]
When you click the "get now" button in mailcollector, an error occurs. Part of the letters are made in the application. When you click "get it now" again, the same letters are drawn up in duplicate applications.

`PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Warning: count(): Parameter must be an array or an object that implements Countable in D:\WWW\GLPI\inc\dbutils.class.php at line 645
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
Fatal error: Maximum execution time of 300 seconds exceeded in D:\WWW\GLPI\inc\cache\simplecache.class.php on line 261`

**Comment by yustas84** [comment]
> PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
PHP Notice: Undefined index: sendprivate in D:\WWW\GLPI\inc\notificationtargetcommonitilobject.class.php at line 812
Fatal error: Maximum execution time of 300 seconds exceeded in D:\WWW\GLPI\vendor\phpmailer\phpmailer\src\SMTP.php on line 1125

**Comment by cedric-anne** [comment]
Hi,

#5655 should fix this. For information, this should not have any functionnal impact.

Regards
