### ISSUE TITLE
because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

### ISSUE THREAD

**Issue by kiayunan** [glpi-project/glpi#5651]
**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Go to 'dropdown'
2. Click on 'any dropdown item and want to add new item to any dropdown'
3. Scroll down to ''
4. See error refused to cnnect

**Expected behavior**

usually doesn't show that error

**Screenshots**

![Screenshot_2](https://user-images.githubusercontent.com/42923102/54971070-65f9f400-4fb7-11e9-93fe-497bdb4791cb.png)

![image](https://user-images.githubusercontent.com/42923102/54812054-c4c02480-4cbc-11e9-957e-6c172836242c.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Information about system installation and configuration
--
![image](https://user-images.githubusercontent.com/42923102/54812481-c807e000-4cbd-11e9-9cf6-5199a051bec7.png)
![image](https://user-images.githubusercontent.com/42923102/54812511-d81fbf80-4cbd-11e9-8642-6fdbe3563ea5.png)
![image](https://user-images.githubusercontent.com/42923102/54812535-e1a92780-4cbd-11e9-9d6d-0b9da535a8a7.png)

**Additional context**

recently i've got this error, i don't know why. Please i need a solution. Thank you

**Comment by cedric-anne** [comment]
Hi,

9.3.0 version is not supported anymore. Can you try to reproduce on 9.4.x version ?

Regards

**Comment by kiayunan** [comment]
i've upgrade my glpi to 9.4.1, but i've got the same error Refused to apply style from 'http://myserver/glpi/css/styles.css?v=9.4.1.1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled. Maybe is there something wrong with my apache configuration??

**Comment by kiayunan** [comment]
I've try to change my configuration at /etc/apache2/conf-enabled/ssl-params.conf from 
(Header set X-Content-Type-Options "nosniff") to (Header set X-Content-Security-Policy "allow 'self';") the error is changing to jquery.js:6272 GET http://myserver/glpi/css/styles.css?v=9.4.1.1 net::ERR_ABORTED 404 (Not Found)

**Comment by cedric-anne** [comment]
Hi,

I do not know why such a request is made. In 9.4.x, CSS are not anymore served on this URL.
Can you disable all plugins and check if the problem persist ?

Regards

**Comment by kiayunan** [comment]
When I'm disabling all plugins, the error is gone and I finally find out what plugins that makes an error, thank you for your support
