### ISSUE TITLE
GLPI 9.4.1.1 Ticket-field "Opening date" is no longer automatically filled 

### ISSUE THREAD

**Issue by orgdv** [glpi-project/glpi#5654]
**Describe the bug**

When creating a new ticket, the field Opening date is no longer automatically filled (default).
Therefore we changed back to version 9.3.3.

**Page(s) URL**

/glpi/front/ticket.form.php

**To reproduce**

Assitance -> Create Ticket

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

In 9.4 version, we just remove the fact that the form is pre-filled with current date, but if you submit the form, the value will be set to the current timestamp. See #4150.

Regards
