### ISSUE TITLE
version master bug

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#566]
hello 

when I open a computer I have this issue

PHP Notice: Undefined index: itemdevices_types in C:\inetpub\wwwroot\glpi\inc\item_devices.class.php at line 248
PHP Warning: in_array() expects parameter 2 to be array, null given in C:\inetpub\wwwroot\glpi\inc\item_devices.class.php at line 299
Fatal error: Uncaught Error: Call to a member function fetch_assoc() on boolean in C:\inetpub\wwwroot\glpi\inc\dbmysql.class.php:280 Stack trace: #0 C:\inetpub\wwwroot\glpi\inc\db.function.php(317): DBmysql->fetch_assoc(false) #1 C:\inetpub\wwwroot\glpi\inc\computerantivirus.class.php(66): countElementsInTable('glpi_computeran...', 'computers_id = ...') #2 C:\inetpub\wwwroot\glpi\inc\commonglpi.class.php(208): ComputerAntivirus->getTabNameForItem(Object(Computer), '') #3 C:\inetpub\wwwroot\glpi\inc\computer.class.php(108): CommonGLPI->addStandardTab('ComputerAntivir...', Array, Array) #4 C:\inetpub\wwwroot\glpi\inc\commonglpi.class.php(158): Computer->defineTabs(Array) #5 C:\inetpub\wwwroot\glpi\inc\commonglpi.class.php(689): CommonGLPI->defineAllTabs(Array) #6 C:\inetpub\wwwroot\glpi\inc\commonglpi.class.php(1135): CommonGLPI->showTabsContent(Array) #7 C:\inetpub\wwwroot\glpi\front\computer.form.php(107): CommonGLPI->display(Array) #8 {main} thrown in C:\inetpub\wwwroot\glpi\inc\dbmysql.class.php on line 280

et a la creation d'une tache planning

PHP Notice: Undefined index: planning_add_types in C:\inetpub\wwwroot\glpi\inc\planning.class.php at line 1322
PHP Notice: Undefined index: planning_add_types in C:\inetpub\wwwroot\glpi\inc\planning.class.php at line 1328
PHP Warning: Invalid argument supplied for foreach() in C:\inetpub\wwwroot\glpi\inc\planning.class.php at line 1328

**Comment by yllen** [comment]
Date of the master please?

**Comment by satyan01** [comment]
04/03/2016

**Comment by yllen** [comment]
Can you make new tests with daily version? I can't reproduce
