### ISSUE TITLE
no location fields in user add form

### ISSUE THREAD

**Issue by Draft0412** [glpi-project/glpi#5663]
Hello
Since updating to version 9.4.x it does not change the location field in the form to add a user

![imagen](https://user-images.githubusercontent.com/31328019/54847847-87a06600-4cad-11e9-888a-51e5e18599d5.png)

**Comment by cedric-anne** [comment]
Hi,

This field is not shown on creation form but is shown on update form.
It is the case since 0.90.2 (see #143).

Regards
