### ISSUE TITLE
Cannot add title to top level menu

### ISSUE THREAD

**Issue by Multiconecta** [glpi-project/glpi#5664]
**Describe the bug**

When a plugin insert a top menu by means of 
$PLUGIN_HOOKS['menu_toadd']['`plugin_name`'] = ['`toplevelkey'` => ['`class_name`']];
the new top level menu gets inserted, but there is no way to assert 'title' and 'default' properties, resulting in an empty title menu.

**Page(s) URL**

Top main menu or reponsive menu

**To reproduce**

1. Create a new menu with 'menu_toadd' hook, but using a new key, instead of an existent menu key, and the value as an array, instead of string.
2. Log on or change profile for new menu generation
4. See error (new menu exists, but it lacks title and height and compromise visual organization)

**Expected behavior**

A new menu is created with no bugs, title appears and default page can be set.

**Logs**

No error displayed, menu just have a blank title

**Screenshots**
Menu is off balance because of new 'empty title' menu:
![image](https://user-images.githubusercontent.com/38262036/54869719-99503f00-4d7b-11e9-946c-a266899a77be.png)

But the empty menu is there:
![image](https://user-images.githubusercontent.com/38262036/54869733-c43a9300-4d7b-11e9-99b7-17bee21f5dc1.png)

In responsive menu also:
![image](https://user-images.githubusercontent.com/38262036/54869741-d5839f80-4d7b-11e9-959d-2f61596befee.png)

How it should be (after patch applied):
![image](https://user-images.githubusercontent.com/38262036/54869752-ea603300-4d7b-11e9-86d3-c13774a7d92f.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]
 
GLPI 9.3.3 ( => /var/www/html/atendimento.multiconecta.com.br-ssl)
Installation mode: GIT

Operating system: Linux xxxxxxxxxxxxxxxxxxx 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64
PHP 5.6.40 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring,
	mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, shmop, sockets,
	sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_perl/2.0.10 Perl/v5.16.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.1.37-MariaDB
	Server SQL Mode: 
	Parameters: xxxxxxxxxx@xxxxxxxxxxxxxxxxxxxxx
	Host info: xxxxxxxxxxxxxxx via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
Database version seems correct (10.1.37) - Perfect!Database version seems correct (10.1.37) - Perfect!
```

**Additional context**

A simple patch in `function generateMenuSession()`, in `html.class.php` will enable the plugin `getMenuContent` method to upload `title` and `default` properties of top menu, and avoid overwriting 'default' property. I have a PR ready, if needed.

**Comment by cedric-anne** [comment]
Hi,

If you have a PR for that, feel free to open it, then we will be able to discuss of your solution.

Regards
