### ISSUE TITLE
Lines not visible when looking up user

### ISSUE THREAD

**Issue by wimaerts** [glpi-project/glpi#5668]
**Describe the bug**

If u search for a user who has a line in "management -> lines" u won't be able to see it with the global search.

I tried this on my own instance, but i can also reproduce it on https://demo.glpi-project.org
I created a line for the user "chris allen" there.

**Page(s) URL**

https://demo.glpi-project.org/front/search.php?globalsearch=allen+chris&globalsearchglass=&_glpi_csrf_token=a63e1e62579ec567852839b9e4f1c912

**To reproduce**

1) management -> lines -> create a new line and add it to a user. 
2) now search the user in the global search field on top and scroll to the bottom.
3) it will show "No item found".

**Expected behavior**

It should show the line that was added for the user.

**Screenshots**

![line chris](https://user-images.githubusercontent.com/9324456/54916033-d55cde80-4ef8-11e9-94ec-db737f7f8319.jpg)

![lines](https://user-images.githubusercontent.com/9324456/54916003-bd855a80-4ef8-11e9-9a8a-aa2526963f59.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

9.4.1

**Comment by cedric-anne** [comment]
Hi,

Search is made on fileds that are configured on the item view. So if you add `User` field in the `Lines` view (`/front/line.php`), you will be able to search on its name.

Regards

**Comment by wimaerts** [comment]
Did not know that, thanks!
