### ISSUE TITLE
Big files freeze queredmail

### ISSUE THREAD

**Issue by dboscaini** [glpi-project/glpi#5670]
I am in version 9.4.4.1 and we accept video attachments in our tickets, but when there is an interaction and a notification is sent the queuednotification frezze, I believe it is because of the size of the file, we can limit the types of attachments that can be sent notifications?

**Comment by cedric-anne** [comment]
Hi,

In "Setup > Notifications > Email followups configuration", you have a "Add documents into ticket notifications" that can be use to disable sending of all attachements (except embedded images). There is no precise filtering feature on this.

Please use the [suggestion website](https://glpi.userecho.com/) if you want to propose an enhancement for this.

Regards
