### ISSUE TITLE
9.4.1 Debug forced if CommandLine is generating email every minute

### ISSUE THREAD

**Issue by Pouet78** [glpi-project/glpi#5673]
**Debug forced if CommandLine is generating email every minute**

With the 9.4.1(.1) upgrade, the crontab is generating one email every minute!

**To reproduce**

On CentOS 7.5, Installation from remi's repo

**Expected behavior**

If cron tasks are all OK, no new email should be generated

**Email generated every minute**

From apache@srv-glpi-test.chgr.local  Mon Mar 25 15:01:02 2019
Return-Path: <apache@srv-glpi-test.chgr.local>
X-Original-To: apache
Delivered-To: apache@srv-glpi-test.chgr.local
From: "(Cron Daemon)" <apache@srv-glpi-test.chgr.local>
To: apache@srv-glpi-test.chgr.local
Subject: Cron <apache@srv-glpi-test> /usr/bin/php /usr/share/glpi/front/cron.php
Content-Type: text/plain; charset=UTF-8
Auto-Submitted: auto-generated
Precedence: bulk
X-Cron-Env: <XDG_SESSION_ID=43799>
X-Cron-Env: <XDG_RUNTIME_DIR=/run/user/48>
X-Cron-Env: <LANG=fr_FR.UTF-8>
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/usr/share/httpd>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=apache>
X-Cron-Env: <USER=apache>
Date: Mon, 25 Mar 2019 15:01:02 +0100 (CET)
Status: R

Externe #1 : Démarrage mailgate
Externe #2 : Démarrage queuednotification

**GLPI setup**

[code]   GLPI 9.4.1.1 ( => /usr/share/glpi) Installation mode: RPM
--

Operating system: Linux srv-glpi-test.chgr.local 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 PHP 7.2.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, soap, sockets, sqlite3, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.16 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.2.8-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.2.8) - Perfect! /var/log/glpi : OK /etc/glpi : OK /var/lib/glpi/files : OK /var/lib/glpi/files/_dumps : OK /var/lib/glpi/files/_sessions : OK /var/lib/glpi/files/_cron : OK /var/lib/glpi/files/_graphs : OK /var/lib/glpi/files/_lock : OK /var/lib/glpi/files/_plugins : OK /var/lib/glpi/files/_tmp : OK /var/lib/glpi/files/_cache : OK /var/lib/glpi/files/_rss : OK /var/lib/glpi/files/_uploads : OK /var/lib/glpi/files/_pictures : OK SELinux mode is Enforcing SELinux boolean configuration for httpd_can_network_connect --> on SELinux boolean configuration for httpd_can_network_connect_db --> on SELinux boolean configuration for httpd_can_sendmail --> on

htmLawed version 1.2.4 in (/usr/share/php/htmLawed) phpmailer/phpmailer version 6.0.7 in (/usr/share/php/PHPMailer/PHPMailer6) simplepie/simplepie version 1.5.2 in (/usr/share/php/php-simplepie) tecnickcom/tcpdf version 6.2.26 in (/usr/share/php/tcpdf) michelf/php-markdown in (/usr/share/php/Michelf) true/punycode in (/usr/share/php/TrueBV) iamcal/lib_autolink in (/usr/share/php/php-iamcal-lib-autolink) sabre/vobject in (/usr/share/php/Sabre/VObject4) zendframework/zend-cache in (/usr/share/php/Zend/Cache) zendframework/zend-i18n in (/usr/share/php/Zend/I18n) zendframework/zend-serializer in (/usr/share/php/Zend/Serializer) monolog/monolog in (/usr/share/php/Monolog) sebastian/diff in (/usr/share/php/SebastianBergmann/Diff) elvanto/litemoji in (/usr/share/php/LitEmoji) symfony/console in (/usr/share/php/Symfony3/Component/Console) leafo/scssphp in (/usr/share/php/Leafo/ScssPhp)

Server: 'ldap://172.26.100.1', Port: '389', BaseDN: 'OU=ETABLISSEMENT,DC=CHGR,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CHGR\glpi', Use TLS: 		none

Not active

Way of sending emails: PHP

Name: '****' Active: No 	Server: '****' Login: '****' Password: Yes

news                 Name: Alertes                        Version: 1.5.1      State: Enabled 	treeview             Name: Arborescence                   Version: 1.8.0      State: Enabled 	behaviors            Name: Comportements                  Version: 2.2.0      State: Enabled 	formcreator          Name: Formulaires                    Version: 2.7.0      State: Enabled 	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: To be cleaned 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled

Host: srv-ocs-inventory.chgr.localConnection: KOUse the OCSNG software dictionary: No
[/code]

**Comment by cedric-anne** [comment]
Hi,

You can fix this with #5675.

Regards
