### ISSUE TITLE
[GLPI 0.90.2 & 0.90.1] : Unable to force MIME type

### ISSUE THREAD

**Issue by SylvainGuibert** [glpi-project/glpi#568]
Hello,

We use lot of *.eml file in our ticket. When we upload this file, the mime type automaticly added by glpi is "text/html". So when you open this file, is open with your default brower and it's unreadable. The mime type for eml is message/rfc822 so i set up it on "Setup -> Dropdowns ->  Document File EML -> MIME TYPE".

After i do that, i still have the issue. When i upload an *.eml file, the mime type is always set on "text/html". Is it a bug or a bad configuration ?

After the eml file is upload, when i manualy change mime type on the file (text/html to message/rfc822), the file is downloaded and opened in a mail client.

nb : I have tested it on 0.90.1 and 0.90.2 (on a test environnement)

------- This is my server setup ------

Operating system: Linux XXXXXXXXXX 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64
PHP 5.5.9-1ubuntu4.14 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml,
	mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="60" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at XXXXXXXXXX.XXX.XXX Port 80)
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.5.41-0ubuntu0.14.04.1
	Server SQL Mode: 
	Parameters: xxx@xxxxxx/xxxx
	Host info: Localhost via UNIX socket

**Comment by SylvainGuibert** [comment]
on the server side, file mime.types have "eml message/rfc822" too.

**Comment by SylvainGuibert** [comment]
I'm alone with this issue ? Somebody can try to reproduce ?

I will upgrade in 0.90.3 to test.

**Comment by tomolimo** [comment]
Hello,
No you are not alone I already add this kind of problem in the past, and I managed to fix them (the only difference is that it was with the mailgate, and the standard file upload.
Let me check what can be the root cause.
thank you
regards,
Tomolimo

**Comment by tomolimo** [comment]
I just made a test with 0.90.3 and this is still a problem :grimacing:

**Comment by SylvainGuibert** [comment]
Thanks for your feddback. so it's a bug ?

**Comment by tomolimo** [comment]
I should not say so, as I think it's by design to permit to view in the browser the EML files.

**Comment by SylvainGuibert** [comment]
Ok let me know.

**Comment by tomolimo** [comment]
What browser did you use for the tests?
I made tests with: 

1. IE10: EML is open inside browser
1. Chrome: EML is open outside browser by Outlook
1. FF: same than for Chrome

**Comment by tomolimo** [comment]
Hello again,
I fixed this with some registry changes. You may check this sit: https://social.technet.microsoft.com/Forums/office/fr-FR/464cce50-e03c-4d28-8fee-7ef146dbf66e/eml-files-wont-open-in-outlook-on-some-computers?forum=officeitproprevious
and use the following registry script I made to delete the wrong keys: 
BEWARE that this reg script deletes some keys, so be cautious about it.

[eml_ie_reset.reg.txt](https://github.com/glpi-project/glpi/files/220517/eml_ie_reset.reg.txt)

Close IE, and restart it,

Regards,
Tomolimo

**Comment by SylvainGuibert** [comment]
I had test it with  Chrome / and IE.

I think this is not a issue browser, because when i upload an eml file (chrome or ie), the mime type affected to this file is wrong.

In this case, mime type for eml file is set to text/html. After an upload if i manualy change the mime type espacily this file to message/rfc822 (with glpi), the file is downloaded by the browser and open by the mail client.

**Comment by tomolimo** [comment]
Could you upgrade GLPi to 0.90.3?

**Comment by tomolimo** [comment]
We need to troubleshoot this.
And I propose to create a small PHP script:
```php
  <?php
   function getMime($file, $type=false) {

      static $finfo = NULL;

      if (is_null($finfo)) {
         $finfo = new finfo(FILEINFO_MIME_TYPE);
      }
      $mime = $finfo->file($file);
      if ($type) {
         $parts = explode('/', $mime, 2);
         return ($parts[0] == $type);
      }
      return ($mime);
   }

   echo getMime( "test.eml" );

?>
```

On the server, create this script, replace "test.eml" by a complete path to your EML file, save the script, and execute it like PHP -f pathtoscript

and look at result: it is the way GLPi is getting the MIME type of uploaded files. What is the result?

**Comment by tomolimo** [comment]
I made tests on my environment with PHP versions:

1. x86 5.3: result: message/rfc822
1. x86 5.4: result: message/rfc822
1. x86 5.5: result: message/rfc822
1. x64 7.0: result: message/rfc822

**Comment by SylvainGuibert** [comment]
I will test it on Monday 18th. thx for your help

**Comment by SylvainGuibert** [comment]
I have test it. And the result of mime type with the script is "text/html" (same as glpi). 
it is a php issue ?

Php Version : 5.5

**Comment by tomolimo** [comment]
Could you zip your EML file and send it to me so that I can try with my PHP versions?

**Comment by SylvainGuibert** [comment]
Yes i can do that but i prefered in a private way. mail ?

**Comment by tomolimo** [comment]
You may also on your side make a test with attached EML file for which I get "message/rfc822"
[test2.eml.txt](https://github.com/glpi-project/glpi/files/223262/test2.eml.txt)

**Comment by tomolimo** [comment]
even if I let the .txt in the previously attached file name, I got message/rfc822

**Comment by tomolimo** [comment]
professional email: 
![image](https://cloud.githubusercontent.com/assets/7569958/14597154/4b0d3a8a-054b-11e6-9459-39c4f40ea546.png)

**Comment by SylvainGuibert** [comment]
With your file, mime type is correct : message/rfc822.

[test_mail.eml.txt](https://github.com/glpi-project/glpi/files/223277/test_mail.eml.txt)

**Comment by tomolimo** [comment]
then let's try with yours

**Comment by tomolimo** [comment]
With yours I got text/html :grimacing:

**Comment by tomolimo** [comment]
So we may deduce that your file is malformed regarding the rfc822 :(

**Comment by SylvainGuibert** [comment]
I think you're right but in the document type section in GLPI, on "EML files", mime type is not supposed to force mime type of the file ?

**Comment by tomolimo** [comment]
unfortunately no, as this is not used to determine the mime type, but only what I sent you (the getMime() function)

**Comment by SylvainGuibert** [comment]
ok, so this field is just an information field :(

**Comment by tomolimo** [comment]
It is used when sending an email with attached files in it.

**Comment by SylvainGuibert** [comment]
OK.
I search on the messaging client side (IBM Notes), and in this client you can drag and drop file to your desktop, and the file is automaticly saved as and eml file. But after some search, they are one settings, to check on the notes client. "Export drag and drop file as EML". If the setting is not active, EML file are exported with a wrong mime type (text/html), but if this setting is on, eml file is exported as message/rfc822. I have tested it and it works ! Can you check with this file : 
[test_settings.eml.txt](https://github.com/glpi-project/glpi/files/223335/test_settings.eml.txt)

**Comment by tomolimo** [comment]
With this last file, I got for PHP:
5.3 x86 nts: message/rfc822
5.4 x86 nts: message/rfc822
5.5 x86 nts: message/rfc822
7.0 x64 nts: message/rfc822
:smile:

**Comment by SylvainGuibert** [comment]
Right ! So it's not a GLPI issue but an IBM Notes issue ! :(

Perhaps, the document type field "mime type" can be used to force the mine type ? enhancement ?

**Comment by tomolimo** [comment]
This is a good question and the answer is not trivial.
As of today PHP is trying to guess the MIME type from the content: it is the most reliable way to do it. Otherwise the system may be mistaken if based only on file extension.

**Comment by SylvainGuibert** [comment]
Ok, but perhaps, you can do it like below : 

1 - If the mime type field in  document type is empty, php determine the mime type
2 - If the mime type field in document type is full, mime type is set up on file by glpi.

**Comment by tomolimo** [comment]
and in 2) how to be sure that it is not a forged one?
for example 'test_settings.eml.txt' will show 'message/rfc822' if you use content guess, but with your example, it will be set as txt...

**Comment by SylvainGuibert** [comment]
You're right, but it can be a desired behavior .
 
And if we can do that glpi administrator must know if mime type is setup , mime type will be forced by glpi. 

Perhaps a good thing if you don't want open eml file in a mail client (security reasons ?).

I don't it's just an idea :).

**Comment by SylvainGuibert** [comment]
Last question of this topic : You know how php retreive mime type ? It use /etc/mime.types from apache ?

**Comment by tomolimo** [comment]
I don't think there is any link between both, as I don't have Apache installed on my PC...

**Comment by SylvainGuibert** [comment]
Do you know how to add a mime type to php ? I have a similar issue with VNC file.....

**Comment by tomolimo** [comment]
see http://php.net/manual/en/book.fileinfo.php for documentation

**Comment by tomolimo** [comment]
look into this function: http://php.net/manual/en/function.finfo-open.php
Seems like if you set MAGIC environment variable to point to a magic file then it will take this file for reference

**Comment by SylvainGuibert** [comment]
Thank's for your help @tomolimo !

See you on next thread !

**Comment by SylvainGuibert** [comment]
Resume : 

-> The field "mime type" in glpi type document is not used to force mime type but only for determine mime type of attachement file in a mail collector.
-> The issue is not in glpi but is the mail client (Notes) which not set up mime type correctly of eml file.
