### ISSUE TITLE
Creating BMP thumbnail error

### ISSUE THREAD

**Issue by drTr0jan** [glpi-project/glpi#5683]
GLPI 9.3, 9.4
There's a case in a switch in _Toolbox::resizePicture()_ (inc/toolbox.class.php):
```
...
         case IMAGETYPE_BMP :
            $source_res = imagecreatefromwbmp($source_path);
...
```
But imagecreatefromwbmp is not compatible with IMAGETYPE_BMP.
It is throwing an error while resizing:

> PHP Warning:  imagecreatefromwbmp(): './BMP/d3/69710bbbfe475a975d1ae23eff6d87c9044c3f.BMP' is not a valid WBMP file in inc/toolbox.class.php.

It's need to use imagecreatefrombmp() function from PHP 7.2 or use a bodge of the function.

**Comment by cedric-anne** [comment]
Hi,

Could you test following fix ?
```diff
diff --git a/inc/toolbox.class.php b/inc/toolbox.class.php
index 986cb38ab8..8414146794 100644
--- a/inc/toolbox.class.php
+++ b/inc/toolbox.class.php
@@ -1340,6 +1340,10 @@ class Toolbox {
 
       switch ($img_type) {
          case IMAGETYPE_BMP :
+            $source_res = imagecreatefrombmp($source_path);
+            break;
+
+         case IMAGETYPE_WBMP :
             $source_res = imagecreatefromwbmp($source_path);
             break;
```

Regards

**Comment by drTr0jan** [comment]
@cedric-anne, I've tested with BMP on PHP 7.2. It works!
But I cannot test it on PHP 7.1. It will be an error most likely.

**Comment by cedric-anne** [comment]
Right, we have to take a closer look on this.

Thanks for the feedback.

**Comment by BorisNovg** [comment]
Same error in glpi 9.5.5, PHP 8.0.7.
BMP file attached to ticket. Internal error in queuednotification - "0 Execution error", repeatedly, queue blocked, notifications not sending.

/var/log/glpi/cron.log - "Internal #1: Error during queuednotification execution. Check in "/var/log/glpi/php-errors.log" for more details."

/var/log/glpi/php-errors.log:
[2021-07-02 09:18:31] glpiphplog.WARNING:   *** PHP Warning (2): imagecreatefromwbmp(): &quot;/var/lib/glpi/files/BMP/31/379752faf6633cf200988373fccab79ef9337b.BMP&quot; is not a valid WBMP file in /usr/share/glpi/inc/toolbox.class.php at line 1347
  Backtrace :
  inc/toolbox.class.php:1347                         imagecreatefromwbmp()
  inc/document.class.php:1571                        Toolbox::resizePicture()
  inc/notificationeventmailing.class.php:359         Document::getImage()
  inc/notificationeventmailing.class.php:268         NotificationEventMailing::attachDocuments()
  inc/queuednotification.class.php:564               NotificationEventMailing::send()
  inc/crontask.class.php:943                         QueuedNotification::cronQueuedNotification()
  front/crontask.form.php:49                         CronTask::launch()

[2021-07-02 09:18:31] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: imagecopyresampled(): Argument #2 ($src_image) must be of type GdImage, bool given in /usr/share/glpi/inc/toolbox.class.php at line 1378
  Backtrace :
  inc/toolbox.class.php:1378                         imagecopyresampled()
  inc/document.class.php:1571                        Toolbox::resizePicture()
  inc/notificationeventmailing.class.php:359         Document::getImage()
  inc/notificationeventmailing.class.php:268         NotificationEventMailing::attachDocuments()
  inc/queuednotification.class.php:564               NotificationEventMailing::send()
  inc/crontask.class.php:943                         QueuedNotification::cronQueuedNotification()
  front/crontask.form.php:49                         CronTask::launch()


Solution - Fix in /usr/share/glpi/inc/toolbox.class.php line 1347:
      switch ($img_type) {
         case IMAGETYPE_BMP :
-            $source_res = imagecreatefromwbmp($source_path);
+            $source_res = imagecreatefrombmp($source_path);
            break;

Solution Ok tested!

**Comment by BorisNovg** [comment]
P.S.
https://www.php.net/manual/en/function.imagecreatefromwbmp.php
Note: WBMP images are Wireless Bitmaps, not Windows Bitmaps. The latter can be loaded with imagecreatefrombmp().
