### ISSUE TITLE
[9.4] Improved linebreaks in followups

### ISSUE THREAD

**Issue by drTr0jan** [glpi-project/glpi#5692]
The issue is similar to #3737
The linebreaks has been marked as `<P></P>` after upgrading from 9.3 to 9.4 instead `<BR>`.
It keeps more space.
Is it bug or feature?

![glpi_linebreak](https://user-images.githubusercontent.com/10733191/55075888-cc7a3180-50df-11e9-8952-e78ffa793ea1.png)

**Comment by cedric-anne** [comment]
Hi,

We only keep the rich text mode in GLPI 9.4 and removed ability to use raw text. This rich text mode use TinyMCE JS component. If you want to add line break instead creating a new paragraph, just use `CTRL+Enter` instead of `Enter`.

Regards
