### ISSUE TITLE
Problems inserting an image into a call (ticket)

### ISSUE THREAD

**Issue by drginfo** [glpi-project/glpi#5709]
Problems inserting an image into a call (ticket):

Both in the screens of new ticket, accompaniment and etc.

When trying to copy and paste directly into the body of the call, or click on select to open an image already saved on the computer, ie we are not able to attach any file type, be it image, pdf, .doc, ... etc, to called.
**Logs**
nothing logs us
**Screenshots**
![image](https://user-images.githubusercontent.com/48928120/55186416-427ca800-5175-11e9-8c7d-b339e5120768.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Installation and Setup Instructions
--
[code]   GLPI 9.4.1.1 ( => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux  4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 PHP 7.2.15-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gearman, geoip, gettext, gmagick, gmp, 	gnupg, hash, iconv, igbinary, imap, intl, json, ldap, libxml, mailparse, mbstring, memcache, memcached, mongodb, msgpack, 	mysqli, mysqlnd, openssl, pcre, pdo_dblib, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, solr, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="25M"  Software: Apache () 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0 Server Software: Ubuntu 18.04 	Server Version: 10.1.38-MariaDB-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.1.38) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Not active

Way of sending emails: SMTP+SSL (suporte@drginfo.com.br@email-ssl.com.br)

Name: 'suporte@drginfo.com.br' Active: Yes 	Server: '{email-ssl.com.br/pop/ssl/novalidate-cert/notls}' Login: 'suporte@drginfo.com.br' Password: Yes

behaviors            Name: Comportamental                 Version: 2.2.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled 	pdf                  Name: Imprimir em PDF                Version: 1.4.0      State: Enabled 	os                   Name: Os                             Version: 0.1.1      State: Enabled 	dashboard            Name: Painel                         Version: 0.9.6      State: Enabled 	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

This message is displayed if PHP is not able to write uploaded files into its temporary directory. See https://stackoverflow.com/a/42393026

As it is not a GLPI bug but a server configuration problem, I close the issue. Feel free to open a subject on [forums](https://forum.glpi-project.org/) to get helps from community.

Regards
