### ISSUE TITLE
Saved searches dont recall list of displayed columns

### ISSUE THREAD

**Issue by ettalhi** [glpi-project/glpi#5715]
**Describe the bug**

Some users want the saved searches to recall the list of the displayed columns so they can use this feature like reports when exporting the result in PDF or Excel format.

**Page(s) URL**

http://localhost:8080/glpi/front/computer.php

**To reproduce**

1. Go to [Assets/Computers]
2. Make a search by criteria and personalize which list of columns you want to view.
3. Save this search by clicking on the star icon next to [search] button
4. Try other searches using other list of criteria and different list of viewed columns.
5. Try now to run the saved search by clicking on the big star close to logout button on the top-right side.
6. Error : the saved search recall criteria but not the list of columns.

**Expected behavior**
Want to recall the list of columns.

**Comment by cedric-anne** [comment]
Hi,

Which version of GLPI are you using ?

Regards

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards

**Comment by cedric-anne** [comment]
Hi,

I reopen this issue as you are working on it.

Regards
