### ISSUE TITLE
don't show expired contracts in dropdown

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#572]
http://forum.glpi-project.org/viewtopic.php?id=152827

limit showing contracts based on begin date and initial duration ans no tacit

**Comment by yllen** [comment]
On an item (computer) list of contracts is empty
On a supplier you have all contracts even contract already selected

**Comment by orthagh** [comment]
> On an item (computer) list of contracts is empty

No, not in my case : 
![image](https://cloud.githubusercontent.com/assets/418844/15609881/bb3b98f6-2422-11e6-8702-d2d2d847577a.png)

> On a supplier you have all contracts even contract already selected
Yes, i only add a expired option to the dropdown and set it to false to avoid changes on other part of core
So, we have 2 options :: 
* we set in supplier the expired option to true
* we change the default to this option to true to apply to all core

> In sql request, use of $idrest deleted in your commit
I don't think so, see this line: 
https://github.com/glpi-project/glpi/commit/bc6637dc77ed6657cbc38b11593739f6d93805eb#diff-f1c85229ada85805a6883511411b31daL1254

$idrest is still present in sql query

**Comment by orthagh** [comment]
oh, forget me, you're right for the last one, i'll fix that

**Comment by yllen** [comment]
If you have a contract without date_begin or without duration, your contract is not showed in the dropdown

**Comment by yllen** [comment]
You also must review sql request of contract_supplier

**Comment by orthagh** [comment]
done for first comment

For supplier, i redo my striked question so:

Yes, i only add a expired option to the dropdown and set it to false to avoid changes on other part of core
So, we have 2 options:
* we set in supplier the expired option to true
* we change the default to this option to true to apply to all core

What do you think ?

**Comment by yllen** [comment]
For your commit, now i have all contracts for all entities. I think you miss ()
```
AND (DATEDIFF(ADDDATE(....
         OR...
         OR....
       )
```
For your question, i think it's more simple to change the default option in Contract::Dropdown (for be apply on all dropdowns of Contracts)
