### ISSUE TITLE
GLPI update from 9.3 > 9.4.1 - errors in sql-error.log os_license_number

### ISSUE THREAD

**Issue by adamcios** [glpi-project/glpi#5726]
**Describe the bug**

After upgrading i get such errors in sql-errors.log

**To reproduce**
Just download, upgrade and get no errors

**Logs**
[2019-04-02 09:44:39] glpisqllog.ERROR: DBmysql::query() in /home/www/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT `glpi_computers`.`id`
                      FROM `glpi_computers`
                      WHERE  `glpi_computers`.`is_template` = '0'  AND `glpi_computers`.`serial`='CND4305Q3D' AND `os_license_number`='YTMG3-N6DKC-DKB77-7M9GH-8HVX7'
                      GROUP BY `glpi_computers`.`id`
                      ORDER BY `glpi_computers`.`is_deleted` ASC
                      LIMIT 1
  Error: Unknown column 'os_license_number' in 'where clause'
  Backtrace :
  ...inventory/inc/inventoryruleimport.class.php:695
  inc/rule.class.php:1563                            PluginFusioninventoryInventoryRuleImport->findWithGlobalCriteria()
  inc/rule.class.php:1429                            Rule->checkCriterias()
  inc/rulecollection.class.php:1539                  Rule->process()
  ...ry/inc/inventorycomputerinventory.class.php:337 RuleCollection->processAllRules()
  ...ry/inc/inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory/inc/communication.class.php:229 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory/inc/communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins/fusioninventory/front/communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins/fusioninventory/index.php:59               include_once()

**Comment by cedric-anne** [comment]
Hi,

The `fusioninventory` plugin is using a field that does not exists anymore since 9.2 version of GLPI.
Please open an issue on plugin reprository. We cannot fix it inside GLPI itself.

Regards
