### ISSUE TITLE
Template not affected for profile other than super-admin

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5734]
Template created with category predefined.
Template assigned for entity.

Ticket created with super-admin profile => category of template is affected
Ticket created with other profile  => category is not affected

https://forum.glpi-project.org/viewtopic.php?id=168538

**Comment by trasher** [comment]
Just tested on 9.4/bugfixes branch, I cannot reproduce

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by MarcSN311** [comment]
It is still not possible to define a default category for new tickets.

**Comment by ftoledo** [comment]
hi @trasher, i have same issue on 9.4.4
can you telme what commits affect this issue from 9.4/bugfixes ?
i want to test on production environment without put all branch updates
thanks!

**Comment by trasher** [comment]
No idea; and I'm not going to spend hours to find... Well I even do not know what to look for. 9.4 is no longer maintained anyways, consider upgrading.
