### ISSUE TITLE
[9.4.1.1] Navigation arrow hide by footer when plugin enabled

### ISSUE THREAD

**Issue by Jeff-Tall** [glpi-project/glpi#5739]
Hi,

Here is the display of my page in IE or Firefox when I have the fusioninventory plugin enabled.

![image](https://user-images.githubusercontent.com/18677500/55486556-ced31300-562c-11e9-8805-ffb008f8003d.png)

Thanks.

**Comment by Jeff-Tall** [comment]
Hi @trasher,

What the tag invalid mean ?

Is the GLPI footer involved?

Or is the fusion inventory plugin that needs to change the CSS to be responsive ?

Tell me if I need to create this question somewhere else.

Thanks

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/blob/9.4/bugfixes/CONTRIBUTING.md

**Comment by Jeff-Tall** [comment]
Ok i close.
