### ISSUE TITLE
7 tables non migrées au moteur InnoDB malgré le lancement du script

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5741]
Hello

glpi 9.3.3 / mariadb 10

I have 7 tables not migrated, I have started the script innodb_migration.php as usual but it changes anything.

Could you help me please

**Comment by yalgva** [comment]
php-errors.log 
[2019-04-04 13:52:48] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in C:\inetpub\wwwroot\inc\toolbox.class.php line 657
  *** PHP Warning(2): Declaration of PluginVipRuleVip::executeActions($output, $params) should be compatible with Rule::executeActions($output, $params, array $input = Array)
  Backtrace :
  inc\autoload.function.php:365                      
  inc\autoload.function.php:365                      include_once()
  :                                                  glpi_autoload()
  inc\rulecollection.class.php:267                   spl_autoload_call()
  inc\rule.class.php:213                             RuleCollection->getRuleClass()
  inc\html.class.php:1426                            Rule::getMenuContent()
  inc\html.class.php:6190                            Html::generateMenuSession()
  inc\html.class.php:1530                            Html::displayMainMenu()
  front\ticket.php:40                                Html::header()

**Comment by trasher** [comment]
Use english only please (issue title is not). 9.3 is no longer supported; try with last stable release or (better) latest nightly.
If problem persists, please tell us which tables are not migrated.

Logs are about a plugin, ether get it fixed or remove it.
