### ISSUE TITLE
Blank page after login if remember me is checked

### ISSUE THREAD

**Issue by hapctic** [glpi-project/glpi#5745]
**Describe the bug**
If Remember me is checked, after login, GLPI not redirecting to user home page (/front/central.php or /front/helpdesk.public.php).

**Page(s) URL**
http://glpiserver.domain/index.php

To reproduce

1. Go to index/login page
2. Check Remember me
3. Enter
4. Error: 
- Blank page (not redirect to /front)
- http status 500

**Expected behavior**
After successful login load user front page.

**Logs**

apache2: PHP Fatal error:  Call to undefined method User::getAuthToken() in /glpi/inc/auth.class.php on line 872

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
PHP 5.6.38-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpiserver Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: Debian 9.6
	Server Version: 10.1.37-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
Requested informations has not been provided.

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce, and, as you do not provide your GLPI version, I assume the bug has been fixed.

Feel free to reopen if you can reproduce on [nightly 9.4/bugfixes build](https://forge.glpi-project.org/tarballs/).

Regards
