### ISSUE TITLE
php extension ext-fileinfo is missing

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#5747]
Hello

I would like to install glpi 9.4.1 but when I want to launch composer install --no-dev I have the message php extension ext-fileinfo is missing.

I use glpi 9.3.3 actually with phpfileinfo extension installed.

So I don't understand this message, I tried to restart the w2012r2 server without success.

Thank you for your help

**Comment by cedric-anne** [comment]
Hi,

Try to run `php -r "echo 'fileinfo extension loaded ? ' . (extension_loaded('fileinfo') ? 'yes' : 'no') . PHP_EOL;"`. If it outputs "no", then the extension is not loaded.
This is a configuration issue, not a GLPI issue.

If you need help, you can open a topic on [forum](https://forum.glpi-project.org/).

Regards

**Comment by yalgva** [comment]
Hello I have checked but it is activated
![image](https://user-images.githubusercontent.com/30655170/55728879-52b64200-5a15-11e9-9368-c60d80cc8ef3.png)

**Comment by cedric-anne** [comment]
Hi,

Have you run the command I give you? Most of the time, configuration differs between PHP CLI and web server.

Regards

**Comment by yalgva** [comment]
![image](https://user-images.githubusercontent.com/30655170/55729722-f5bb8b80-5a16-11e9-915c-783e18811f52.png)

**Comment by yalgva** [comment]
php 7.2.2 - glpi 9.3.3

**Comment by trasher** [comment]
Extension is not loaded form command line. Check you "webserver's" documentation to know how to proceed.
Please use forums for assistance.

**Comment by yalgva** [comment]
![image](https://user-images.githubusercontent.com/30655170/55730146-d6712e00-5a17-11e9-85bd-814f03a18bac.png)

**Comment by yalgva** [comment]
![image](https://user-images.githubusercontent.com/30655170/55730520-ad9d6880-5a18-11e9-83f2-98366ab361a6.png)
 I don't understand why it is loaded but composer see not loaded

**Comment by yalgva** [comment]
I found the issue, the php-ini is in another php folder.

Thank you for your help
