### ISSUE TITLE
##ticket.url## and ##ticket.urlapprove## is not correct as my default path

### ISSUE THREAD

**Issue by bensonzhou** [glpi-project/glpi#5758]
**Describe the bug**
i had changed the default web path   to below  in the  httpd.conf.

and then the result of the notification  by e-mail  send out the  ticket url like this :
http://192.168.31.65/glpi/index.php?redirect=ticket_14
http://192.168.31.65/glpi/index.php?redirect=ticket_15&noAUTO=1
 the problem is   i must delete the /glpi in the URL then can access it ,
like this:http://192.168.31.65/index.php?redirect=ticket_14

so  please help me   to correct the settings .    thank you  in advance!

DocumentRoot "/var/www/html/glpi"
<Directory "/var/www/html/glpi">
    AllowOverride None
    # Allow open access:
    Require all granted
</Directory>

**Comment by cedric-anne** [comment]
Hi,

I am pretty sure you have to change the base URL here:
![image](https://user-images.githubusercontent.com/33253653/55786297-46cd8d00-5ab4-11e9-817a-d67e751d759d.png)

For future help requests, please use [forums](https://forum.glpi-project.org).

Regards

**Comment by bensonzhou** [comment]
that's perfect , thank you !

**Comment by faviancab** [comment]
perfect, thank you very much
