### ISSUE TITLE
Queries with 'AND NOT' giving wrong results in GLPI 9.4.1

### ISSUE THREAD

**Issue by danton004** [glpi-project/glpi#5763]
**Describe the bug**

A query with "AND NOT" for a Computer name, gives diferent results in GLPI 9.3 and GLPI9.4.1.
It seems that the right result is the one given in GLPI 9.3
In my tests both GLPIs have the same computers with the same softwares.

The query shown in debug mode is different

In GLPI 9.3:
```sql
SELECT 'glpi' AS currentuser, `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`, `glpi_computers`.`name` AS `ITEM_0`, `glpi_computers`.`id` AS `ITEM_0_id`, `glpi_states`.`completename` AS `ITEM_1`, `glpi_manufacturers`.`name` AS `ITEM_2`, `glpi_computers`.`serial` AS `ITEM_3`, `glpi_computertypes`.`name` AS `ITEM_4`, `glpi_computermodels`.`name` AS `ITEM_5`, `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_6`, `glpi_locations`.`completename` AS `ITEM_7`, `glpi_computers`.`date_mod` AS `ITEM_8`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`designation`, '__NULL__'), '$#$',`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id`) SEPARATOR '$$##$$') AS `ITEM_9`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_softwares`.`name`, '$#$' , `glpi_softwares`.`id`) SEPARATOR '$$##$$') AS `ITEM_10`, `glpi_computers`.`id` AS id
FROM `glpi_computers`
LEFT JOIN `glpi_states` ON (`glpi_computers`.`states_id` = `glpi_states`.`id` )
LEFT JOIN `glpi_manufacturers` ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id` )
LEFT JOIN `glpi_computertypes` ON (`glpi_computers`.`computertypes_id` = `glpi_computertypes`.`id` )
LEFT JOIN `glpi_computermodels` ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id` )
LEFT JOIN `glpi_items_operatingsystems` ON (`glpi_computers`.`id` = `glpi_items_operatingsystems`.`items_id` AND `glpi_items_operatingsystems`.`itemtype` = 'Computer' )
LEFT JOIN `glpi_operatingsystems` AS `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090` ON (`glpi_items_operatingsystems`.`operatingsystems_id` = `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`id` )
LEFT JOIN `glpi_locations` ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id` )
LEFT JOIN `glpi_items_deviceprocessors` ON (`glpi_computers`.`id` = `glpi_items_deviceprocessors`.`items_id` AND `glpi_items_deviceprocessors`.`itemtype` = 'Computer' )
LEFT JOIN `glpi_deviceprocessors` AS `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604` ON (`glpi_items_deviceprocessors`.`deviceprocessors_id` = `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id` )
LEFT JOIN `glpi_computers_softwareversions` AS `glpi_computers_softwareversions_Software` ON (`glpi_computers_softwareversions_Software`.`computers_id` = `glpi_computers`.`id` AND `glpi_computers_softwareversions_Software`.`is_deleted` = 0)
LEFT JOIN `glpi_softwareversions` AS `glpi_softwareversions_Software` ON (`glpi_computers_softwareversions_Software`.`softwareversions_id` = `glpi_softwareversions_Software`.`id`)
LEFT JOIN `glpi_softwares` ON (`glpi_softwareversions_Software`.`softwares_id` = `glpi_softwares`.`id`)
LEFT JOIN `glpi_softwarelicenses` AS `glpi_softwarelicenses_Software` ON (`glpi_softwares`.`id` = `glpi_softwarelicenses_Software`.`softwares_id`)
WHERE `glpi_computers`.`is_deleted` = 0 AND `glpi_computers`.`is_template` = 0 GROUP BY `glpi_computers`.`id` HAVING ((`ITEM_10` NOT LIKE '%S1%' OR `ITEM_10` IS NULL) )
ORDER BY ITEM_0 ASC
```

In GLPI 9.4.1:
```sql
SELECT DISTINCT `glpi_computers`.`id` AS id, 'glpi' AS currentuser, `glpi_computers`.`entities_id`, `glpi_computers`.`is_recursive`, `glpi_computers`.`name` AS `ITEM_Computer_1`, `glpi_computers`.`id` AS `ITEM_Computer_1_id`, `glpi_states`.`completename` AS `ITEM_Computer_31`, `glpi_manufacturers`.`name` AS `ITEM_Computer_23`, `glpi_computers`.`serial` AS `ITEM_Computer_5`, `glpi_computertypes`.`name` AS `ITEM_Computer_4`, `glpi_computermodels`.`name` AS `ITEM_Computer_40`, `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`name` AS `ITEM_Computer_45`, `glpi_locations`.`completename` AS `ITEM_Computer_3`, `glpi_computers`.`date_mod` AS `ITEM_Computer_19`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`designation`, '__NULL__'), '$#$',`glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id`)
ORDER BY `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id` SEPARATOR '$$##$$') AS `ITEM_Computer_17`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_softwares`.`name`, '$#$' , `glpi_softwares`.`id`)
ORDER BY `glpi_softwares`.`id` SEPARATOR '$$##$$') AS `ITEM_Software_1`
FROM `glpi_computers`
LEFT JOIN `glpi_states` ON (`glpi_computers`.`states_id` = `glpi_states`.`id` )
LEFT JOIN `glpi_manufacturers` ON (`glpi_computers`.`manufacturers_id` = `glpi_manufacturers`.`id` )
LEFT JOIN `glpi_computertypes` ON (`glpi_computers`.`computertypes_id` = `glpi_computertypes`.`id` )
LEFT JOIN `glpi_computermodels` ON (`glpi_computers`.`computermodels_id` = `glpi_computermodels`.`id` )
LEFT JOIN `glpi_items_operatingsystems` ON (`glpi_computers`.`id` = `glpi_items_operatingsystems`.`items_id` AND `glpi_items_operatingsystems`.`itemtype` = 'Computer' )
LEFT JOIN `glpi_operatingsystems` AS `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090` ON (`glpi_items_operatingsystems`.`operatingsystems_id` = `glpi_operatingsystems_9719987b154aaf3b42c3db32aef59090`.`id` )
LEFT JOIN `glpi_locations` ON (`glpi_computers`.`locations_id` = `glpi_locations`.`id` )
LEFT JOIN `glpi_items_deviceprocessors` ON (`glpi_computers`.`id` = `glpi_items_deviceprocessors`.`items_id` AND `glpi_items_deviceprocessors`.`itemtype` = 'Computer' )
LEFT JOIN `glpi_deviceprocessors` AS `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604` ON (`glpi_items_deviceprocessors`.`deviceprocessors_id` = `glpi_deviceprocessors_7083fb7d2b7a8b8abd619678acc5b604`.`id` )
LEFT JOIN `glpi_computers_softwareversions` AS `glpi_computers_softwareversions_Software` ON (`glpi_computers_softwareversions_Software`.`computers_id` = `glpi_computers`.`id` AND `glpi_computers_softwareversions_Software`.`is_deleted` = 0)
LEFT JOIN `glpi_softwareversions` AS `glpi_softwareversions_Software` ON (`glpi_computers_softwareversions_Software`.`softwareversions_id` = `glpi_softwareversions_Software`.`id`)
LEFT JOIN `glpi_softwares` ON (`glpi_softwareversions_Software`.`softwares_id` = `glpi_softwares`.`id`)
LEFT JOIN `glpi_softwarelicenses` AS `glpi_softwarelicenses_Software` ON (`glpi_softwares`.`id` = `glpi_softwarelicenses_Software`.`softwares_id`)
WHERE `glpi_computers`.`is_deleted` = 0 AND `glpi_computers`.`is_template` = 0 AND ( ((`glpi_softwares`.`name` NOT LIKE '%S1%' OR `glpi_softwares`.`name` IS NULL) ) ) GROUP BY `glpi_computers`.`id`
ORDER BY ITEM_Computer_1 ASC 
```

The query in GLPI 9.4.1 doesn´t have a HAVING clause

**Page(s) URL**

/glpi/front/computer.php

**To reproduce**

1. Go to 'Computer'
2. Set a query with 'AND NOT' and contains SOFTWARE name
3. Search
4. Results are wrong on GLPI 9.4.1

**Expected behavior**

Both results should be the same. Computers where software "C1" is not installed

**Screenshots**

GLPI 9.3

![image](https://user-images.githubusercontent.com/49440121/55797855-c7e54e00-5acd-11e9-8c69-f219550705ae.png)

GLPI 9.4.1

![image](https://user-images.githubusercontent.com/49440121/55797937-f6632900-5acd-11e9-872e-3dcfd2cbe04f.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

In GLPI 9.3

Information about system installation and configuration

[code]
 
GLPI 9.3.0 (/glpi93 => /var/www/html/glpi93)
Installation mode: TARBALL

Server

 
Operating system: Linux inventarioglpi 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
PHP 7.0.33-0+deb9u3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at 10.0.2.11 Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: Debian 9.6
	Server Version: 10.1.37-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: root@localhost/glpi93
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is not present
Database version seems correct (10.1.37) - Perfect!Database version seems correct (10.1.37) - Perfect!
OK/var/www/html/glpi93/config : OK
OK/var/www/html/glpi93/files : OK
OK/var/www/html/glpi93/files/_dumps : OK
OK/var/www/html/glpi93/files/_sessions : OK
OK/var/www/html/glpi93/files/_cron : OK
OK/var/www/html/glpi93/files/_graphs : OK
OK/var/www/html/glpi93/files/_lock : OK
OK/var/www/html/glpi93/files/_plugins : OK
OK/var/www/html/glpi93/files/_tmp : OK
OK/var/www/html/glpi93/files/_cache : OK
OK/var/www/html/glpi93/files/_rss : OK
OK/var/www/html/glpi93/files/_uploads : OK
OK/var/www/html/glpi93/files/_pictures : OK
OK/var/www/html/glpi93/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (/var/www/html/glpi93/lib/htmlawed)
SimplePie version 1.5.1 in (/var/www/html/glpi93/vendor/simplepie/simplepie/library)
TCPDF version 6.2.17 in (/var/www/html/glpi93/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi93/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi93/vendor/true/punycode/src)
iacaml/autolink in (/var/www/html/glpi93/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi93/vendor/sabre/vobject/lib)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: PHP

Mails receivers

 

Plugins list

 
	fusioninventory      Name: FusionInventory                Version: 9.3+1.4    State: New

In GLPI 9.4.1

Information about system installation and configuration

[code]
 
GLPI 9.4.1.1 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux inventarioglpi 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
PHP 7.0.33-0+deb9u3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at 10.0.2.11 Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: Debian 9.6
	Server Version: 10.1.37-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.1.37) - Perfect!Database version seems correct (10.1.37) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: PHP

Mails receivers

 

Plugins list

 
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled

**Comment by danton004** [comment]
I tested it and works fine now. 
Thanks @cedric-anne.

Regards

**Comment by trasher** [comment]
Issue will be closed once PR has been merged
