### ISSUE TITLE
PHP Fatal error:  Call to a member function addRecord() on null in inc/toolbox.class.php on line 435

### ISSUE THREAD

**Issue by ftoledo** [glpi-project/glpi#5768]
I have this error when running cron via php cli:

PHP Fatal error:  Call to a member function addRecord() on null in inc/toolbox.class.php on line 435

php version: 

PHP 5.6.40-1~dotdeb+7.1 (cli) (built: Jan 12 2019 20:13:26) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

GLPI version: 9.4.1.1 and Fusioninventory 9.4+ 1.1

relevant php-error.log:
```
2019-04-09 12:49:14 [11@bm01]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-04-09 12:49:19 [11@bm01]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-04-09 12:49:23 [11@bm01]
includeLocales(softversioninstallations_report_title, reports) => not found
[2019-04-09 12:49:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/soporte/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: size1
  Backtrace :
  plugins/dashboard/front/sh/df.php:45
  plugins/dashboard/front/main.php:524               include()
  {"user":"11@bm01"}
[2019-04-09 12:49:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/soporte/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined variable: size2
  Backtrace :
  plugins/dashboard/front/sh/df.php:46
  plugins/dashboard/front/main.php:524               include()
  {"user":"11@bm01","mem_usage":"0.001\", 2.68Mio)"}
2019-04-09 12:49:24 [11@bm01]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-04-09 12:49:29 [11@bm01]
includeLocales(softversioninstallations_report_title, reports) => not found
2019-04-09 12:49:34 [11@bm01]
```

cron.log:
```
2019-04-09 12:34:04 [11@bm01]
Interno #1: Nada para lanzar
2019-04-09 12:39:43 [11@bm01]
Interno #1: Nada para lanzar
2019-04-09 12:46:32 [11@bm01]
Interno #1: Nada para lanzar
```

**Comment by trasher** [comment]
This should have been solved already for 9.4.2. Please try with [latest 9.4/bugfixes nightly build](https://forge.glpi-project.org/tarballs/).

Feel free to reopen if issue is stil present.

**Comment by ftoledo** [comment]
I confirm that was solved in this version, thanks!

**Comment by crespicarlos** [comment]
Hello,
I have installed GLPI 9.4.2 with fusioninventory 9.4+1.1 and I have the same problem. 
(Ubuntu+apache+php 7.2)

Is it a permissions issue?
I get the same error running cron as www-data, but not if I run it as root.

Thank you.

**Comment by cedric-anne** [comment]
Hi,

Please open a new issue and fill all requested informations.

Regards
