### ISSUE TITLE
GLPI Error ldap Search

### ISSUE THREAD

**Issue by koopa3822** [glpi-project/glpi#5773]
Hi @trasher, it must be a fortune to find this portal and find you, or anyone who can help me.

In the company for which I work we are implementing GLPI.

when we try to synchronize the users of the active directory (we have successful test of the ldap configuration) it tells us that there are no users.

The error that shows us our linux (fedora core server) is the following:

glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /usr/share/glpi/inc/toolbox.class.php line 657
*** PHP Warning(2): ldap_search(): Search: Operations error
Backtrace :
:
inc/authldap.class.php:1604 ldap_search()
inc/authldap.class.php:1750 AuthLDAP::searchForUsers()
inc/authldap.class.php:3769 AuthLDAP::getAllUsers()
inc/authldap.class.php:1454 AuthLDAP::getUsers()
inc/authldap.class.php:3332 AuthLDAP::showLdapUsers()
front/ldap.import.php:66 AuthLDAP::searchUser()
{"user":"2@mesadeayuda.inexmoda.org.co"}

I tried to do everything and I searched a lot in forums but I have not been successful, you could help me a little in guiding me to a solution I would greatly appreciate your help.

**Comment by trasher** [comment]
Please do not use issues to get support. Either use forums, or get profesional help (see https://services.glpi-network.com/ for example).
