### ISSUE TITLE
[9.4.1.1] LDAP import error

### ISSUE THREAD

**Issue by gloomy-master** [glpi-project/glpi#5775]
Good afternoon, developers.
I deployed a clean version 9.4.1.1 for the test and I encountered that I could not import users via the web.
I am informed that no users were found, although the test in the Authentication settings is successful.

When I turn on the mode, I get the following php error
![GLPI-LDAP_error](https://user-images.githubusercontent.com/21122546/55933741-d6577500-5c47-11e9-937a-1902220e5541.jpg)

**Comment by trasher** [comment]
This seems an usage issue, not a bug. Please use forums to get support.
