### ISSUE TITLE
Transfert equipement entre entité: pas de transfert des tickets

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#578]
Bonjour, GLPI v0.90.2

Je dois réaliser en refont complète des entités et réalise des transfert entre entités. Lorsque je réalise ce transfert, les tickets ne sont pas deversés dans l'entité de destination bien que l'option soit mis à GARDER.

**Comment by yllen** [comment]
You transfer which kind of items?

**Comment by Sismic** [comment]
All asset: computer, network, phone ...

**Comment by trasher** [comment]
A solution has been proposed in #1042, closing this one.
