### ISSUE TITLE
Better logging for Mail Imports

### ISSUE THREAD

**Issue by MakerTim** [glpi-project/glpi#5781]
Hey team GLPI, or bonjour

When you install and configure the mailcollector[s], you have 0 feedback what is going on
Debugging if it is reading your mail; meh, try count for connecting is something
But when you are importing mails, there are no logs or feedback what is going on

My suggestion is to use log entries in the database for every mail; with some information to debug what is going on;

Things like 0 rules match / no mail <-> user relation found; are easy things to fix, but a dragon to kill to find out

Im open to other solutions; but for debugging problems as end user; its near inpossible to setup now; what is a shame!

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
