### ISSUE TITLE
[9.4.x] Chrome - space after 3 times shift+enter on Google Chrome

### ISSUE THREAD

**Issue by ciadch** [glpi-project/glpi#5786]
Hi !

Since GLPI 9.4, we ecounter a strange behaviour with Google Chrome and GLPI editor. After 3 shift+enter line break, it's impossible to add space in text. You need to push space bar twice to add a space (and it's a double space).
The same behaviour appears everywhere in GLPI editor and only with Google Chrome. I can't reproduice it with Firefox or Edge.

Thanks

**Comment by cedric-anne** [comment]
Hi,

Looks like a bug in TinyMCE component. Check their [changelog](https://www.tiny.cloud/docs-4x/changelog/) and open an issue on their repository if you did not find anything.

Regards

**Comment by ciadch** [comment]
Hi @cedric-anne,

Effectively, this bug was correcter in 4.9.3 : 

![image](https://user-images.githubusercontent.com/12936546/55961922-2fd39a00-5c70-11e9-8c10-68ade407c2b2.png)

As I can see, in GLPI it's the version 4.7.13 (2018-05-16) 

Do you plan to upgrade it ? 

Thanks

**Comment by cedric-anne** [comment]
If it has been fixed on 4.9.3 version of TinyMCE, then it is already fixed in the 9.5.x branch (see https://github.com/glpi-project/glpi/blob/9.5/bugfixes/package-lock.json#L4698).

We do not plan to update javascript dependencies on 9.4.x branch for now.

**Comment by ciadch** [comment]
Ok thanks a log for your return
