### ISSUE TITLE
Search computers with number of installations

### ISSUE THREAD

**Issue by danton004** [glpi-project/glpi#5790]
**Describe the bug**

Searching computers with a certain number of installations gives no results. Debug shows that there is an error in SQL query.

**Page(s) URL**

/glpi/front/computer.php

**To reproduce**

1. Go to Computers
2. Click on Global Rule
3. Select software in the first dropdown
4. In the second dropdown select Number of Installations
5. Search

**Expected behavior**

Show computers with the number of installations

**Screenshots**

![image](https://user-images.githubusercontent.com/49440121/56016751-9652c980-5cfd-11e9-963f-777fc5eaf0c0.png)

There is an error in the SQL query

![image](https://user-images.githubusercontent.com/49440121/56016873-e6ca2700-5cfd-11e9-8c00-819429d56376.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.4.0 (/glpi94 => /var/www/html/glpi94)
Installation mode: TARBALL

Server

 
Operating system: Linux inventarioULMA 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
PHP 7.2.17-1+ubuntu18.04.1+deb.sury.org+3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="550M" safe_mode="" session.save_handler="files"
	upload_max_filesize="500M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at localhost Port 80)
	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: (Ubuntu)
	Server Version: 5.7.25-0ubuntu0.18.04.2
	Server SQL Mode: 
	Parameters: root@localhost/glpi94
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is not present
Database version seems correct (5.7.25) - Perfect!Database version seems correct (5.7.25) - Perfect!
OK/var/www/html/glpi94/files/_log : OK
OK/var/www/html/glpi94/config : OK
OK/var/www/html/glpi94/files : OK
OK/var/www/html/glpi94/files/_dumps : OK
OK/var/www/html/glpi94/files/_sessions : OK
OK/var/www/html/glpi94/files/_cron : OK
OK/var/www/html/glpi94/files/_graphs : OK
OK/var/www/html/glpi94/files/_lock : OK
OK/var/www/html/glpi94/files/_plugins : OK
OK/var/www/html/glpi94/files/_tmp : OK
OK/var/www/html/glpi94/files/_cache : OK
OK/var/www/html/glpi94/files/_rss : OK
OK/var/www/html/glpi94/files/_uploads : OK
OK/var/www/html/glpi94/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (/var/www/html/glpi94/lib/htmlawed)
phpmailer/phpmailer version 6.0.6 in (/var/www/html/glpi94/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi94/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi94/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi94/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi94/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi94/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi94/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi94/vendor/zendframework/zend-cache/src)
zendframework/zend-console in (/var/www/html/glpi94/vendor/zendframework/zend-console/src)
zendframework/zend-i18n in (/var/www/html/glpi94/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi94/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi94/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi94/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi94/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi94/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi94/vendor/leafo/scssphp/src)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: PHP

Mails receivers

 

Plugins list

 
	fields               Name: Campos adicionales             Version: 1.9.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4.0+1.0  State: Enabled

**Comment by cedric-anne** [comment]
Hi,

First, you should consider updating to 9.4.2 version to get latest bugfixes.

Second, could you try #5791 ?

Regards

**Comment by danton004** [comment]
Hi,

I tested in version 9.4.2.

SEARCH

![image](https://user-images.githubusercontent.com/49440121/56029051-d758d700-5d19-11e9-95dd-9e49d562f72a.png)

QUERY

![image](https://user-images.githubusercontent.com/49440121/56028929-8e088780-5d19-11e9-9877-041691986c1b.png)

The query is now correct, but still no results. It seems that there is also an error in the WHERE clause.

WHERE `glpi_computers`.`is_deleted` = 0 AND `glpi_computers`.`is_template` = 0 AND ( _**(`glpi_computers_softwareversions_0a35c270152be19b5c8a485502badcd7_Software`.`id` = 3)**_ ) GROUP BY `glpi_computers`.`id` 

The number of instalations is for some reason compared with an _id_. I think it should be _ITEM_Software_72_

Regards

**Comment by cedric-anne** [comment]
After investigation, it appears that this criteria was not available prior to 9.4.x (see https://github.com/glpi-project/glpi/commit/0c077e4e2ddb4f0d22a8f0ef79d25794ce1bbc1f#diff-17af799339343190eb55774113e99760 from 2010).

I tried to find a solution to make it work, but it looks too complicated to achieve for something really specific.
