### ISSUE TITLE
Statistic by ticket - solution type

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#5796]
**Describe the bug**
Try to use the statistic of tickets by ticket : characteristics - solution type.
It didn't show datas and make an sql error :

```
SQL: SELECT FROM_UNIXTIME(UNIX_TIMESTAMP(`glpi_tickets`.`date`),'%Y-%m') AS date_unix, COUNT(`glpi_tickets`.`id`) AS total_visites FROM `glpi_tickets` LEFT JOIN `glpi_itilsolutions` ON (`glpi_tickets`.`id`.`glpi_itilsolutions`.`items_id` = `glpi_itilsolutions`.`itemtype`.`Ticket`) WHERE `glpi_tickets`.`is_deleted` = '0' AND `glpi_itilsolutions`.`solutiontypes_id` = '0' AND (((`glpi_tickets`.`date` >= '2017-11-01') AND (`glpi_tickets`.`date` <= ADDDATE('2019-04-12', INTERVAL 1 DAY)))) GROUP BY `date_unix` ORDER BY `glpi_tickets`.`date`
Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.`items_id` = `glpi_itilsolutions`.`itemtype`.`Ticket`) WHERE `glpi_tickets`.`is' at line 1
```

Version of glpi tested 9.4.2 & 9.3.3

**Comment by keha35** [comment]
the fix i've done in GLPI 9.4.2 in the file 'stat.class.php'  :
line 851 - i've remove the line : "case "solutiontypes_id"

And line 862 - i've add : 
`case "solutiontypes_id" :
            $LEFTJOIN = [
                'glpi_itilsolutions' => [
                    'ON' => [
                        'glpi_itilsolutions'   => 'items_id',
                        'glpi_tickets'               => 'id'
                    ]
                ]
            ];
            $WHERE["glpi_itilsolutions.$param"] = $value;
            break;`

**Comment by cedric-anne** [comment]
Hi,

Please make a PR if you have a fix.

Regards

**Comment by trasher** [comment]
@keha35 ping?
