### ISSUE TITLE
Ticket not unlocking when exiting

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#5799]
**Describe the bug**

We are experiencing an issue regarding ticket-locking since upgrading from v9.4.1.1 to v9.4.2. It's possible that this issue was in v9.4.1.1 but not all our technicians reported/noticed it. Now, every technician reports it.

If we enter a ticket (as a technician) and choose the option to unlock it for edit/update, then exit the ticket, the ticket remains locked.

**Expected behavior**

In previous versions of GLPI, the ticket unlocked itself when exiting the ticket.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

![image](https://user-images.githubusercontent.com/16598973/56077250-cc617d80-5dd1-11e9-81bc-f41651680415.png)

![image](https://user-images.githubusercontent.com/16598973/56077251-d7b4a900-5dd1-11e9-8035-4b21aaaad9b3.png)

Has anyone else encountered this and/or has a fix?

Thank you

**Comment by hgpit** [comment]
Upon further investigation, it looks like this issue is a bug or incompatibility Google Chrome.

When we test this is Firefox 62.0.3 (64-bit) of 64.0 (64-bit), the tickets unlock upon exit, as expected.

In our Chrome 73.0.3683.103 (Official Build) (64-bit) we have the problem.

Unfortunately, our company's IT policy is to only allow/use/support Chrome, so it would be great if GLPI could still work correctly under Chrome.

**Comment by hgpit** [comment]
By the way, we have tried clearing the Chrome caches etc, but it doesn't help.

**Comment by cedric-anne** [comment]
Hi,

> If we enter a ticket (as a technician) and choose the option to unlock it for edit/update, then exit the ticket, the ticket remains locked.

I am not sure about what you talk about. Can you take a screenshot of this "option" ?

Can you also provide us the list of plugins you use ?

Regards

**Comment by tomolimo** [comment]
Hello @hgpit, @cedric-anne 

We also have the same issue. and we are using GLPI 9.2.4
And I made tests with Chrome, IE11, Edge, FireFox and Safari, and only Chrome has the described issue.
I've investigated and it seems that Chrome is not firing the event named beforeunload (which is standart event)  https://www.w3schools.com/jsref/event_onbeforeunload.asp

Regards,
Tomolimo

**Comment by tomolimo** [comment]
I also made a test on a former Chrome version:
73.0.3683.86 (Official Build) (64-bit) we **don't** have the problem in this version.

**Comment by cedric-anne** [comment]
Maybe it is related to this: https://bugs.chromium.org/p/chromium/issues/detail?id=952452.

**Comment by hgpit** [comment]
@cedric-anne 

I think you're probably familiar with the issue now, but just in case:

Before editing a ticket, the 'Locked by' is empty:
![image](https://user-images.githubusercontent.com/16598973/56135634-117be000-5f89-11e9-8934-37c923bbd704.png)

Once the ticket has been worked on, and I exit the ticket:
![image](https://user-images.githubusercontent.com/16598973/56135730-4425d880-5f89-11e9-87ce-ec086b13f7fc.png)

You can see that the ticket remains locked (by me), despite having exited the ticket.

**Comment by tomolimo** [comment]
I confirm @cedric-anne post: this is related to https://bugs.chromium.org/p/chromium/issues/detail?id=952452 and such is not a GLPI bug.

**Comment by hgpit** [comment]
@tomolimo , thank you for confirming it as a Chrome bug :)

**Comment by orthagh** [comment]
@tomolimo Could you explain why the xhr need to be sync in the use case of GLPI ?

**Comment by cedric-anne** [comment]
I reopen this issue as synchronous request made on beforeunload will be [deprecated soon in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=952452#c48).

See #5828 for more details.

**Comment by Armin83** [comment]
@cedric-anne 
Do you know that apple ios device witch safari browser also don't work (same problem) ?
(windows with latest chrome works again.)

**Comment by cedric-anne** [comment]
@Armin83 

Can you test the fix proposed in #5828 ?

Regards

**Comment by tomolimo** [comment]
@orthagh sorry for being late to answer, I was in holidays :)
I fact the asynchronous unlock will work in most of GLPI use cases, but one use case must be deeply tested the 'Page reload' (F5 or CTRL+R) and may need to be re-engineered.
And on another hand I'm not sure that XHR calls will be available as it seems that the new way of doing things is to use the sendBeacon() feature, see: https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/LnqwTCiT9Gs/tO0IBO4PAwAJ
In fact, this is not clear that the async XHR will be maintained.
Thank you,
Regards,
Tomolimo

**Comment by Armin83** [comment]
@cedric-anne 
I changed the file. (Btw on glpi 9.3.3)
Second Test:
Restart apache
Open new private tap on safari (ios)
I have the same problem.
It does not work.

**Comment by tomolimo** [comment]
@Armin83 
Which version of Chrome?

**Comment by Armin83** [comment]
@tomolimo 
No, i don't use chrome in this situation - sorry it was a small question / comment different topic but maybe same cause, (apple ios device with safari browser)

Now i tested on apple iphone 7 ios 12.2 and chrome APP (version 73.0.3683.68)
I have also the same problem. (btw i use a vpn connection)

**Comment by tomolimo** [comment]
@Armin83 
But with this Chorme release this issue has never happen... as the depreciation has been introduce only since the the 73.0.3683.103. So you may have something else dur to iOS?

**Comment by Armin83** [comment]
@tomolimo 
I only tested with iOS because the bug on the windows pc with chrome. Maybe this bug on iOS already existed before. (On my windows pc with chrome the bug happens with version xxx and gone with version xx)

**Comment by b-keller** [comment]
Hi,

We just update GLPI from 9.3.4 to 9.4.4 and we have the same kind of problems with Firefox ESR 68.2 and Developer Edition 71.x

When I enter in a ticket, and went back to ticket list : the ticket is still locked by myself (whether if I add a task , a followup or nothing)

This problem is not present in Chromium 80.x

**Comment by b-keller** [comment]
@trasher 
Hi,

to solve this bug with Firefox and GLPI 9.4.4, I need to put back 
`async: false,`
line 317

**Comment by tomolimo** [comment]
Hello,
This is an issue with FireFox...
I've got the same (see https://github.com/glpi-project/glpi/pull/6395#issue-324250734)
Unfortunately, FireFox has implemented the depreciation the wrong way...
The only solution is to use the SendBeacon feature with FireFox.
....
to be followed...

**Comment by tomolimo** [comment]
To be clear:
Chrome, and Chromium are now (or in a near future) preventing synchronous XHR calls in the onbeforeunload event handlers.
FireFox is now preventing asynchronous XHR calls in the onbeforeunload event handlers.
😬

**Comment by orthagh** [comment]
Maybe we could:
- send an async xhr 
- and send after a sync xhr.

As it both cases are covered, if both pass, we won't delete more data by the way, no ?

**Comment by tomolimo** [comment]
Yes it could be a solution.
Another could be to test if sendBeacon is available and use it, and if not, use async XHR.

**Comment by orthagh** [comment]
sendBeacon feature is too late in some cases, you will not be sure on a tab refresh your beacon was send before loading the new page.

Another way to explore is "fetch keep alive", but i don't find any resources about the timing (which is the key point)

**Comment by tomolimo** [comment]
yes the tab refresh is the problem!

**Comment by mab18** [comment]
Hi, 
This message is more an help to be a workaround.
Would it be possible to add a mass unlock option in the list of items? Indeed, going into the element to click "unlock" is not always practical nor fast.
An "Unlock item" in massive action should ok.

**Comment by tomolimo** [comment]
Hello @mab18,
This is already the case:
![image](https://user-images.githubusercontent.com/7569958/68785214-1ba8ae80-063e-11ea-82f9-d7d0bf978d74.png)
Regards,
Tomolimo

**Comment by orthagh** [comment]
@b-keller i push a pr (#6600) for the issue with firefox, could you test the proposition ?

**Comment by b-keller** [comment]
@orthagh 
Hi,

I just test it with Firefox 70.0.1 and dev edition 71.0B9 : ticket isn't locked anymore but there are a display refresh bug.

 If I enter in a ticket and go back to ticket list, the ticket is mark as locked, but if i refresh (F5) lock disappear.

**Comment by cedric-anne** [comment]
Hi @hgpit @tomolimo @Armin83 @b-keller @mab18 ,

Can you try with #6644 and tell me if it fixes the problem ?

Regards

**Comment by b-keller** [comment]
Hi @cedric-anne 

For me, there's still one problem : (FF browser)
If I enter inside a ticket, doing nothing, and going back to ticket list : the ticket is marked as locked by myself, but it 's just a refresh bug...

thx
