### ISSUE TITLE
 Issues with Tags for Email Notifications

### ISSUE THREAD

**Issue by mrcssilvasouza** [glpi-project/glpi#5800]
Tags for ticket approval do not work
Examples:
##validation.commentsubmission##
##validation.submissiondate##
##validation.validator##

TAGs for tickets and forms work.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by mrcssilvasouza** [comment]
In fact I had to put FOREACH and ENDFOREACH for validation TAGs.

Thank you
