### ISSUE TITLE
Slow frontpage load

### ISSUE THREAD

**Issue by gitpwc** [glpi-project/glpi#5801]
**Describe the bug**

After updating to 9.4.x from 9.2, opening frontpage requires 60 seconds. After, navigating within the size is fast as normal

**Page(s) URL**

http://server_fqdn/glpi/front/central.php

**To reproduce**

1. Go to http://server_fqdn/glpi/front/central.php

**Expected behavior**

Load should take few seconds as before

**Screenshots**

[code]   
GLPI 9.4.2 (/glpi => /srv/glpi) Installation mode: TARBALL
--
Operating system: Linux sever_fqdn 3.10.0-957.10.1.el7.x86_64 #1 SMP Mon Mar 18 15:06:45 UTC 2019 x86_64
PHP 7.3.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, ionCube Loader, json, ldap,
	libsmbclient, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, smbclient, soap, sockets,
	sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) PHP/7.3.4 mod_perl/2.0.10 Perl/v5.16.3 (Apache/2.4.6 (CentOS) PHP/7.3.4 mod_perl/2.0.10
	Perl/v5.16.3 Server at SERVERNAME Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.25-log
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
exif extension is installed
xmlrpc extension is not present
CAS extension is not present
Database version seems correct (5.7.25) - Perfect!
Database version seems correct (5.7.25) - Perfect!
OK/srv/glpi/files/_log : OK
OK/srv/glpi/config : OK
OK/srv/glpi/files : OK
OK/srv/glpi/files/_dumps : OK
OK/srv/glpi/files/_sessions : OK
OK/srv/glpi/files/_cron : OK
OK/srv/glpi/files/_graphs : OK
OK/srv/glpi/files/_lock : OK
OK/srv/glpi/files/_plugins : OK
OK/srv/glpi/files/_tmp : OK
OK/srv/glpi/files/_cache : OK
OK/srv/glpi/files/_rss : OK
OK/srv/glpi/files/_uploads : OK
OK/srv/glpi/files/_pictures : OK
SELinux mode is Disabled

 
htmLawed version 1.2.4 in (/srv/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/srv/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/srv/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/srv/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/srv/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/srv/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/srv/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/srv/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/srv/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/srv/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/srv/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/srv/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/srv/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/srv/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/srv/glpi/vendor/symfony/console)
leafo/scssphp in (/srv/glpi/vendor/leafo/scssphp/src)

PLUGINS LIST

	appliances           Name: Appliances                     Version: 2.3.2      State: Not activated
	positions            Name: Cartography                    Version: 4.6.0      State: Not activated
	dashboard            Name: Dashboard                      Version: 0.9.4      State: Enabled
	databases            Name: Databases                      Version: 2.2.1      State: Not activated
	addressing           Name: IP Adressing                   Version: 2.8.0      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.6.1      State: Enabled
	archires             Name: Network Architectures          Version: 2.5.1      State: Not activated
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled
	reports              Name: Reports                        Version: 1.12.0     State: Not activated
	webapplications      Name: Web applications               Version: 2.5.1      State: Not activated
[/code]

**Additional context**

Please see https://forum.glpi-project.org/viewtopic.php?id=168813 on how I worked-around the issue

These are the "long running" SQL Queries which takes ~30 seconds each
SELECT DISTINCT `glpi_tickets`.`id`
                FROM `glpi_tickets`
                LEFT JOIN `glpi_tickets_users`
                     ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)
                LEFT JOIN `glpi_groups_tickets`
                     ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`) 
			     LEFT JOIN `glpi_itilsolutions`
                           ON (`glpi_itilsolutions`.`id` = (SELECT `last_solution`.`id`
                                    FROM `glpi_itilsolutions` as `last_solution`
                                    WHERE `last_solution`.`items_id` = `glpi_tickets`.`id`
                                    AND `last_solution`.`itemtype` = 'Ticket'
                                    ORDER BY `last_solution`.`id` DESC
                                    LIMIT 1))
                        WHERE  `glpi_tickets`.`is_deleted` = 0
                             AND ( (`glpi_tickets_users`.`users_id` = '455'
                            AND `glpi_tickets_users`.`type` = '2'))
                             AND `glpi_tickets`.`status` <> '6'
                             AND `glpi_itilsolutions`.`status` = '4'    LIMIT 0,30;

SELECT DISTINCT `glpi_tickets`.`id`
                FROM `glpi_tickets`
                LEFT JOIN `glpi_tickets_users`
                     ON (`glpi_tickets`.`id` = `glpi_tickets_users`.`tickets_id`)               
			   LEFT JOIN `glpi_groups_tickets`
                     ON (`glpi_tickets`.`id` = `glpi_groups_tickets`.`tickets_id`) LEFT JOIN `glpi_itilsolutions`
                           ON (`glpi_itilsolutions`.`id` = (SELECT `last_solution`.`id`
                                    FROM `glpi_itilsolutions` as `last_solution`
                                    WHERE `last_solution`.`items_id` = `glpi_tickets`.`id`
                                    AND `last_solution`.`itemtype` = 'Ticket'
                                    ORDER BY `last_solution`.`id` DESC
                                    LIMIT 1))
                        WHERE  `glpi_tickets`.`is_deleted` = 0
                             AND ( (`glpi_tickets_users`.`users_id` = '455'
                            AND `glpi_tickets_users`.`type` = '2'))
                             AND `glpi_tickets`.`status` <> '6'
                             AND `glpi_itilsolutions`.`status` = '4'  ORDER BY `glpi_tickets`.`date_mod` DESC;

**Comment by Jeff-Tall** [comment]
Hi @gitpwc ,
You can test this solution : [https://github.com/glpi-project/glpi/issues/5806#issuecomment-498768558](url)

**Comment by trasher** [comment]
dups https://github.com/glpi-project/glpi/issues/5806
