### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by juliosw** [glpi-project/glpi#5802]
**Describe the bug**

after the login screen the access denied message is shown . 

V. 9.4.1.2

**Expected behavior**

Access.

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

![image](https://user-images.githubusercontent.com/45014255/56138685-bc7ea080-5f6d-11e9-9276-d55b0846d943.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

**Comment by cedric-anne** [comment]
Hi,

Could you provide requested informations (i.e logs, system informations, ...) ?

Regards

**Comment by juliosw** [comment]
> Hi,
> 
> Could you provide requested informations (i.e logs, system informations, ...) ?
> 
> Regards

Hi @cedric-anne ,

linux ubuntu 16.04.5 LTS (Xenial)
php version 7.0.33
mysql 5.7.25
GLPI 9.4.1.2


was working perfectly for almost 1 year

only that
![Image 4](https://user-images.githubusercontent.com/45014255/56139572-8d692e80-5f6f-11e9-9842-f56bd987447a.png)

**Comment by cedric-anne** [comment]
Looks like you have a file permission problem.

Have you use a GLPI CLI command or are you calling GLPI cron from crontab ? If yes, is the user used is the same than the one used by your webserver ?

Try to chown `files/_cache` directory to give ownage to your webserver.

Regards

**Comment by juliosw** [comment]
It´s works !! Thnx Bro.
