### ISSUE TITLE
[9.4.2] Bad performance for select caller after update

### ISSUE THREAD

**Issue by Jeff-Tall** [glpi-project/glpi#5806]
Hi,

After update GLPI 9.4.1.1 to 9.4.2, when we create a ticket, loading of entity in caller is very, very long (3 > 6 secs) or i have this message !

![image](https://user-images.githubusercontent.com/18677500/56193963-28c2d800-6032-11e9-9aad-47be6ecb9e9a.png)

Other action in GLPI is fast.

I have test with no plugins and the result is the same.

Thanks for your help.

```

    Operating system: Linux  3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64
PHP 7.3.4 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube
	Loader, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix,
	pspell, redis, session, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader,
	xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="60" memory_limit="512M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="16M" 
Software: Apache (Apache Server at Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: (Debian)
	Server Version: 10.0.38-MariaDB-0+deb8u1
	Server SQL Mode: 
	Parameters: glpi@localhost:3306/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.0.38) - Perfect!Database version seems correct (10.0.38) - Perfect!
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_log : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/config : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_dumps : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_sessions : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_cron : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_graphs : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_lock : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_plugins : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_tmp : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_cache : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_rss : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_uploads : OK
OK/mnt/disk/plesk/xxx.fr/httpdocs/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK


fields               Name: Champs supplémentaires         Version: 1.9.1      State: Not activated
credit               Name: Crédits                        Version: 1.6.1      State: Not activated
formcreator          Name: Form Creator                   Version: 2.8.1      State: Not activated
fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Not activated
moreticket           Name: More ticket                    Version: 1.5.0      State: Not activated
```

**Comment by Jeff-Tall** [comment]
More elements :

![image](https://user-images.githubusercontent.com/18677500/56197964-354b2e80-603a-11e9-8f58-1b984c5772e2.png)

![image](https://user-images.githubusercontent.com/18677500/56197765-ca015c80-6039-11e9-8d28-d9a0ade1307b.png)

**Comment by CDG47** [comment]
Same problem for us.

Operating system: Linux parc 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64
PHP 7.0.33-0+deb9u3 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" upload_max_filesize="5M" 
Server Software: Debian 9.6
Server Version: 10.1.37-MariaDB-0+deb9u1

PLugins
         news                 Name: Alertes                        Version: 1.5.1      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.9.1      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled
	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled

**Comment by Jeff-Tall** [comment]
Hello,

Would you like additional information to help solve this performance problem?

The average load is 4 seconds today.

![image](https://user-images.githubusercontent.com/18677500/57215529-70af9c00-6fed-11e9-9209-d141426ba8b5.png)

Thank you in advance for your return.

**Comment by cedric-anne** [comment]
Hi @Jeff-Tall, @CDG47  ,

Could you test if it works faster after applying #5981 ?

Regards

**Comment by Jeff-Tall** [comment]
Hello @cedric-anne 

In my GLPI Folder, i do :

```
wget https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/5981.patch
```

and after
```
patch -p1 < 5981.patch
```

Result : 

```
patching file inc/dbutils.class.php
patching file inc/session.class.php
```

After my first test, the result is **awesome** !! ;)

I have to test more but i think is in the good way...

Thanks, i give you more result tomorow in production...

**Comment by Jeff-Tall** [comment]
Hi @cedric-anne ,

After a morning of work, I can say that the performance problem is **solved** !

Thank you for your work !!

_I would make a return after applying version 9.4.3 if there was a difference in performance._
