### ISSUE TITLE
9.4.2 Ticket Lock by byself

### ISSUE THREAD

**Issue by grigribou** [glpi-project/glpi#5812]
Hi,

Since I updated from 9.4.1 to 9.4.2, I have an issue with ticket lock.

For each modify of a tickt we have alert as ticket is locked by myself.
All users have same issue.

![image](https://user-images.githubusercontent.com/8124469/56280290-292ea200-610a-11e9-8a81-9f88461703b7.png)

Regards,

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/5799
