### ISSUE TITLE
bug after installation on Windows 10 64bit

### ISSUE THREAD

**Issue by LeSigne** [glpi-project/glpi#5813]
after installation the following message is displayed when clicking on the button use glpi, the same problem appears on version 9.4.0 / 9.4.1.1
Configuration: Windows 10 64 bit / Easyphp DevServer 17 / Apache 2.4.25 / Mysql 5.7.17
> Fatal error: Uncaught exception 'ErrorException' with message 'fopen(C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\glpi\files\_cache\cache_trans\glpi_cache_trans_9.4.2235ed4644c9cb66b906662fd5926d36b-96\glpi_cache_trans_9.4.2235ed4644c9cb66b906662fd5926d36b-Zend_I18n_Translator_Messages_e4f80f70980f9b99859a1330d2598e5c.dat): failed to open stream: Invalid argument' in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\glpi\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php:1572 Stack trace: #0 [internal function]: Zend\Stdlib\ErrorHandler::addError(2, 'fopen(C:\\Progra...', 'C:\\Program File...', 1572, Array) #1 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\glpi\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php(1572): fopen('C:\\Program File...', 'cb') #2 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\glpi\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php(969): Zend\Cache\Storage\Adapter\Filesystem->putFileContent('C:\\Program File...', 'C:31:"Zend\\I18n. in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-www\glpi\vendor\zendframework\zend-cache\src\Storage\Adapter\Filesystem.php on line 1580
> [php-errors.log](https://github.com/glpi-project/glpi/files/3091309/php-errors.log)
>

**Comment by trasher** [comment]
You should consider updating to 9.4.2. This looks like a file access issue, try to clean files/_cache directory and check directories/files rights.

**Comment by LeSigne** [comment]
thanks for your answer, this is the error message that appears after installing 9.4.2
I attributed all access to the "files" and "_cache" folder (no success)
I deleted all files from the "_cache" folder (no success)

**Comment by guillermohaad** [comment]
hi @LeSigne , I solved  : putting write rights in / cache * =  chmod -R 777 *
check directories/files rights.
