### ISSUE TITLE
[9.4.2] Contract randomly disappeared

### ISSUE THREAD

**Issue by zoriax** [glpi-project/glpi#5814]
Hello !

Strange bug since 9.4.2, the contract on my devices (licences, computers and all the rest) diseapperared randomly ! I can't see any log in contracts and in device. 

Anyone has this behaviour ? 

Thanks for you help / return

**Comment by Armin83** [comment]
Disable all plugins and try again.

**Comment by Eon9D** [comment]
This is concerning me as I am currently preparing the production upgrade..
I know this has nothing to do with it directly but on issue ..5690 they say:
"If I transfer any computer (even just 1) between entities then all the financial and administrative info is gone. Not just for the 1 asset but all assets!"

Is just one contract disappearing or all?
Trashbin is empty?
Is it still in mySQL visible?
...
Thanks

**Comment by cedric-anne** [comment]
@ciadch, Are you sure this in only happening since 9.4.2 update ? Which version was you using before ? Is it possible that you used tranfer on some elements with the 9.4.1 version ?

@Eon9D , Lost of items during a transfer has been fixed in #5703, in 9.4.2.

Regards

**Comment by ciadch** [comment]
@cedric-anne I come from version 9.4.1 but I don't transfer any element from this version. I pass the upgrade directly

**Comment by ciadch** [comment]
As I can see, this "bug" seems related to a cron job. Before the weekend, I have approx. 100 assets without contract, this morning more then 1000... and I can't see anything in logs excepted : 

In php-error.log
```
 *** PHP Warning(2): Use of undefined constant PLUGIN_FUSIONINVENTORY_VERSION - assumed 'PLUGIN_FUSIONINVENTORY_VERSION' (this will throw an Error in a future version of PHP)
  Backtrace :
  inc/toolbox.class.php:676                          
  plugins/fusioninventory/front/communication.php:73 Toolbox::userErrorHandlerDebug()
  plugins/fusioninventory/index.php:59               include_once()
```
And in sql-error.log
```
 *** MySQL query error:
  SQL: INSERT INTO `glpi_items_operatingsystems` (`itemtype`, `items_id`, `operatingsystemarchitectures_id`, `operatingsystemkernelversions_id`, `operatingsystems_id`, `operatingsystemversions_id`, `operatingsystemservicepacks_id`, `operatingsystemeditions_id`, `licenseid`, `license_number`, `is_dynamic`, `entities_id`, `is_recursive`, `date_creation`, `date_mod`) VALUES ('Computer', '382', '2', '1139', '1', '0', '1', '0', '00555-AAA-0990000-00000', '00555-AAAA-0990000-00000', '1', '0', '0', '2019-04-23 07:39:58', '2019-04-23 07:39:58')
  Error: Duplicate entry '382-Computer-1-2' for key 'unicity'
```
But I'm not sure there is a linl

**Comment by ciadch** [comment]
To continue the test, I restored the version of GLPI 9.4.1.1 -> the contracts are not presents too. So it seems the bug coms from update from 9.4 to 9.4
