### ISSUE TITLE
"last edited by" 9.4.2 not being updated

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#5817]
**Describe the bug**

- Create a ticket as user.
- Technician edit ticktet -> "last edited by" is set to technician
- User is answering the mail he received by mail
-> "Last edited by" is still the technician 

**Expected behavior**

Last edited is the user that sent the mail

Last case from 9.3.2: https://github.com/glpi-project/glpi/issues/4924

Thanks

**Comment by Armin83** [comment]
IMO this is normal.
Ticket last edited is only changed if you change prio, sla, titel, description... but not if you add a "comment" but i'm not sure.

**Comment by Eon9D** [comment]
It was working in the previous releases and even got solved in the link I've posted; So I think this is not normal.

**Comment by Eon9D** [comment]
This seems to be the issue. Sadly I am not able to solve this (lack of understanding of objects etc.) :/
1201 is the user which should be the new user but it remains on the old 421 user ...
![update_user](https://user-images.githubusercontent.com/32479943/56473741-ad1cbd00-646f-11e9-957a-d9b51690aa47.png)

**Comment by Eon9D** [comment]
I've noticed that there is a new notification.

When a technician is answering a ticket by mail - he gets his own answer by mail. Is this because the last author is not updated or is this a new bug?

**Comment by Eon9D** [comment]
Issue was caused by wrong setup CRON/GUI.
