### ISSUE TITLE
[GLPI 9.4.2] pictures error while ticket created by mailgate collector

### ISSUE THREAD

**Issue by Kotarik** [glpi-project/glpi#5822]
Hi,

Since update glpi to 9.4.2, we have pictures problem in tickets. This appear when tickets are created by the mailgate collector.

The HTML code of the picture in error is :

`<img width="247" height="124" style="width: 2.575in; height: 1.2916in;" id="Image_x0020_5" src="denied:cid:image001.png@01D4FA7E.99EDD170" alt="image" data-mce-src="denied:cid:image001.png@01D4FA7E.99EDD170" data-mce-style="width: 2.575in; height: 1.2916in;" data-mce-selected="1">`

**Screenshots**

![image](https://user-images.githubusercontent.com/35108914/56646984-f2fc9f80-6680-11e9-95c1-95ab319c1286.png)

Befor the update, a good image is  :

`<img src="https://glpi.domaine.fr/front/document.send.php?docid=2353&amp;tickets_id=12871" alt="5655b4a5-878a205d-5c5bc61a71ff05.76014956" width="309" data-mce-src="https://glpi.domaine.fr/front/document.send.php?docid=2353&amp;tickets_id=12871" data-mce-selected="1">`

How can i fix that ?

Thanks by advance

**Comment by GoulvenPace** [comment]
Hi,

Did you try to change the priviliges of the directory who contains the pictures ?

Like that :
chmod 775 -R /var/lib/glpi/files

**Comment by cedric-anne** [comment]
Hi @Kotarik ,

Which version were you using before ?

Regards

**Comment by Kotarik** [comment]
Hi, Thanks @GoulvenPace , that solve my problem....
