### ISSUE TITLE
[GLPI 9.4] Locales files modifications ignored 

### ISSUE THREAD

**Issue by SIEDV86** [glpi-project/glpi#5824]
Following update GLPI 9.3.3 -> 9.4.2, the file '/var/www/glpi/locales/fr_FR.po' has been modified and then recompiled with the command 'msgfmt fr_FR.po -o fr_FR.mo'.

The french titles only have been modified. The goal is to customize the content of Impact, Priority and Urgency dropdown lists within the ticket interface.

Example:

#: inc/commonitilobject.class.php:2168
msgctxt "impact"
msgid "Medium"
msgstr "Moyen"

becomes:

#: inc/commonitilobject.class.php:2168
msgctxt "impact"
msgid "Medium"
msgstr "Bloquant - Individuel"

The modifications seems not to be taken into account. Nevertheless, if 'fr_FR.mo' file is deleted, the french language is no longer available in the GLPI interface, which suggests that the file is in use!

This has been tested with Edge, Mozilla Firefox and Chrome (lastest versions) using private navigation windows with no browser cache. This process has been used for previous GLPI updates and worked perfectly.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by SIEDV86** [comment]
Already posted either on [GLPI forum](https://forum.glpi-project.org/viewtopic.php?id=168675) or freenode IRC with no help provided...

**Comment by SIEDV86** [comment]
It seems to be a bug and not a simple support request, see in the provided link (I'm not the only one facing the issue).

**Comment by trasher** [comment]
Trying to change source code is development, not usage. This is **not** a bug.

**Comment by SIEDV86** [comment]
Apologize...
