### ISSUE TITLE
Toolbox encrypt/decrypt not work

### ISSUE THREAD

**Issue by navessan** [glpi-project/glpi#5827]
Hi,
I'm trying to configure mailcollector, and i always have error [AUTH] login failure.
Looking for a mistake I found a problem in the functions Toolbox::encrypt and Toolbox::decrypt. They not work as expected in my configuration.
Also I have some troubles with LDAP auth, some long passwords don't work.

**Page(s) URL**

glpi/front/mailcollector.form.php

**To reproduce**

I wrote a test small php script to test functions.
```
<?php

define('GLPI_ROOT', __DIR__);
include_once (GLPI_ROOT . "/inc/based_config.php");

$pass="1qaz2wsx3edc";
$crypt=Toolbox::encrypt($pass, GLPIKEY);

echo "key=".GLPIKEY." <br>\n";
echo "original=".$pass." <br>\n";
echo "crypted=".$crypt." <br>\n";
echo "decrypted=".Toolbox::decrypt($crypt, GLPIKEY)."\n";

```
My output for this
```
key=GLPIkey2wsx
original=1qaz2wsx3edc
crypted=qbitynvi2PFl3Nfb
decrypted=1qaz��wbΉ�� 
```

**Expected behavior**
original and decrypted should be equal

**Additional context**
<details><summary>glpi configuration</summary><p>

[code]   GLPI 9.4.2 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux glpi 4.4.0-141-generic #167-Ubuntu SMP Wed Dec 5 10:40:15 UTC 2018 x86_64 PHP 7.0.33-0ubuntu0.16.04.4 apache2handler (Core, PDO, PDO_Firebird, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, 	interbase, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, 	snmp, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="300" memory_limit="512M" post_max_size="32M" safe_mode="" session.save_handler="files" 	upload_max_filesize="32M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at glpi Port 80) 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0 Server Software: (Ubuntu) 	Server Version: 5.7.25-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (5.7.25) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

</p></details>

**Comment by trasher** [comment]
I cannot reproduce.

I've added the case in unit tests:
https://github.com/trasher/glpi/commit/7f0869685f899103a81ca018aad1c763ebb3dd8a

Result is:
https://circleci.com/gh/trasher/glpi/10319

I wonder if tere is something wrong in your environment.

**Comment by navessan** [comment]
Thanks for reply.
I have found option 
`[mbstring]
mbstring.func_overload = 2
`
in my php.ini was set by other web service.
