### ISSUE TITLE
Empty dropdown menu "Network port type to be added"

### ISSUE THREAD

**Issue by prfad** [glpi-project/glpi#583]
Hi,
i want to ask you about my problem with adding network port "Network port type to be added". Everything was working fine, but few days ago after regular reboot of server i want to add some new network port on some device and the dropdown menu was empty. 

![snimek obrazovky 2016-04-11 v 16 03 17](https://cloud.githubusercontent.com/assets/18399035/14429920/b5660d22-ffff-11e5-9b02-b21477cda78c.png)

![snimek obrazovky 2016-04-11 v 16 03 27](https://cloud.githubusercontent.com/assets/18399035/14429925/baf3a81c-ffff-11e5-90ef-93047d3661d4.png)

When i click "Add" new port was created, but not with all informations.

![snimek obrazovky 2016-04-11 v 16 03 41](https://cloud.githubusercontent.com/assets/18399035/14429949/dcf8b3d0-ffff-11e5-955b-40c31d55af76.png)

![snimek obrazovky 2016-04-11 v 16 04 12](https://cloud.githubusercontent.com/assets/18399035/14429967/f7055b34-ffff-11e5-930e-bc088e633758.png)

When i have looked into the database into table "glpi_networkports" in line of this port was missing some information in column "instantiation_type".

![snimek obrazovky 2016-04-11 v 16 05 14](https://cloud.githubusercontent.com/assets/18399035/14430053/4849dde4-0000-11e6-8787-fdf5c15acdd5.png)

I have tried to manually add information "NetworkPortEthernet" 

![snimek obrazovky 2016-04-11 v 16 05 54](https://cloud.githubusercontent.com/assets/18399035/14430109/9088b404-0000-11e6-9bb6-4a6835fc6c4a.png)

![snimek obrazovky 2016-04-11 v 16 06 26](https://cloud.githubusercontent.com/assets/18399035/14430121/9913b060-0000-11e6-9534-8ff038f86dfc.png)

![snimek obrazovky 2016-04-11 v 16 06 42](https://cloud.githubusercontent.com/assets/18399035/14430125/9f04fed4-0000-11e6-8ff9-df9a176cfc8a.png)

and check the same screen after refresh, it was looking well

![snimek obrazovky 2016-04-11 v 16 06 55](https://cloud.githubusercontent.com/assets/18399035/14430130/a47263fc-0000-11e6-9353-116ec1a948ce.png)

Please, can you tell me, where can be problem and how can i solve it?

Thank you very much.
Nice day. Jan

[code]
GLPI 0.90.3 (/glpi => C:\xampp\htdocs\glpi)
Running on XAMPP 7.0.3

**Comment by orthagh** [comment]
Hello @prfad 

It's a strange issue, i never saw this dropdown empty.

Could you check the glpi logs files you'll find in .../glpi/files/_logs/* for relative errors ?

A login/logout on glpi may also "fix" this issue.

**Comment by prfad** [comment]
Thank you very much for your reply, **orthagh**,
logout/login doesn`t change nothing. I have completelly reboot web server.

There is some error in "php-errors.log".
Is there some way to fix this problem?
Thanx again.
Nice day. Jan


  *** PHP Warning(2): preg_replace(): Compilation failed: a numbered reference must not be zero at offset 17
  Backtrace :
  :                                                  
  plugins\genericobject\inc\functions.php:40         preg_replace()
  plugins\genericobject\hook.php:49                  _log()
  inc\plugin.class.php:1166                          plugin_genericobject_getDropdown()
  inc\plugin.class.php:1181                          Plugin::doOneHook()
  inc\dropdown.class.php:858                         Plugin::getDropdowns()
  inc\commondropdown.class.php:108                   Dropdown::getStandardDropdownItemTypes()
  inc\html.class.php:1297                            CommonDropdown::getMenuContent()
  front\central.php:73                               Html::header()

**Comment by orthagh** [comment]
This log trace does not seems relative to your issue.
Could you truncate theses files, reproduce your error and check again ?

Also, you can check your apache log (for xampp, it should be in ...\xampp\apache\logs\error.log)

**Comment by prfad** [comment]
Thanx for your concern,
in error.log I have just these rows:

[Tue Apr 26 15:28:51.546735 2016] [ssl:warn] [pid 3500:tid 276] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 26 15:28:51.593535 2016] [core:warn] [pid 3500:tid 276] AH00098: pid file C:/xampp/apache/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Tue Apr 26 15:28:51.796335 2016] [ssl:warn] [pid 3500:tid 276] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 26 15:28:51.921135 2016] [mpm_winnt:notice] [pid 3500:tid 276] AH00455: Apache/2.4.18 (Win32) OpenSSL/1.0.2e PHP/7.0.3 configured -- resuming normal operations
[Tue Apr 26 15:28:51.921135 2016] [mpm_winnt:notice] [pid 3500:tid 276] AH00456: Apache Lounge VC14 Server built: Dec  9 2015 10:17:39
[Tue Apr 26 15:28:51.921135 2016] [core:notice] [pid 3500:tid 276] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Tue Apr 26 15:28:51.921135 2016] [mpm_winnt:notice] [pid 3500:tid 276] AH00418: Parent: Created child process 1980
[Tue Apr 26 15:28:52.825935 2016] [ssl:warn] [pid 1980:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 26 15:28:53.044335 2016] [ssl:warn] [pid 1980:tid 288] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Tue Apr 26 15:28:53.122335 2016] [mpm_winnt:notice] [pid 1980:tid 288] AH00354: Child: Starting 150 worker threads.

I have tried migrate GLPI database and whole folder to another instalation of XAMPP (no changes from default install, just passwords and file size) and this error (empty dropdown menu) also appeared :-(

Thank you for any advice :-)
Jan

**Comment by orthagh** [comment]
When opening dev tools (F12) of your browser, do you see some (javascript) errors in console tab ?

**Comment by prfad** [comment]
No, there is just one information:
Using getPreventDefault()is outdated. Rather, use defaultPrevented.
From file jquery-1.10.2.js

Some informations are shown in tab CSS
for example:
Unknown property '-moz-box-shadow ". Declaration dropped. style.css: 76: 112
Unknown property '-moz-border-radius ". Declaration dropped. style.css: 80: 155
Unknown property 'user-select. " Declaration dropped. rateit.css: 10: 15
Unknown property "zoom". Declaration dropped. select2.css: 9: 8
Expected declaration but found "*". Skipped to next declaration. select2.css: 10: 4
Unknown property 'user-select. " Declaration dropped. select2.css: 49: 25
Error while parsing the value of 'background-image'. Declaration dropped. select2.css: 52: 22
Error while parsing the value of 'background-image'. Declaration dropped. select2.css: 53: 22
Expected 'none', or URL filtering function but found 'progid'. Error while parsing the value of "filter". Declaration dropped. select2.css: 55: 12
Error while parsing the value of 'background-image'. Declaration dropped. select2.css: 68: 22
Error while parsing the value of 'background-image'. Declaration dropped. select2.css: 69: 22
Expected 'none', or URL filtering function but found 'progid'. Error while parsing the value of "filter". Declaration dropped. select2.css: 71: 12
Expected 'none', or URL filtering function but found 'alpha ('. Error while parsing the value of "filter". Declaration dropped. Select2.css: 137: 12
Error while parsing the value of 'background-image'. Declaration dropped. select2.css: 201: 22
Error while parsing the value of 'background-image'. Declaration dropped. select2.css: 202: 22

and others......

**Comment by orthagh** [comment]
Could you test (on another folder) an empty installation to check ?

**Comment by prfad** [comment]
I have tried new installation of 0.90.1 (that was my first install of GLPI), also i have tried 0.90.3 and in both installation was everything working well and everywhere (Mac+FF, Mac+Safari, Win7+FF, Win7+IE, Win2008+FF) I have tried to create new network device and ports was shown all type of ports. Also I have tried upgrade from 0.90.1 to 0.90.3 and with this clean install/upgrade without data was it working perfectly.

So I will try to migrate all plugins, database and all data to new installation.

When it will works, it will be fine.
Maybe one more question: Do you know release date of new 9.1 version? When it will be soon, i will wait :-)

Thank you for your advice.
Nice day. Jan

**Comment by orthagh** [comment]
Late spring for 9.1

I close this issue
