### ISSUE TITLE
Duplicated softwares

### ISSUE THREAD

**Issue by mulbzh** [glpi-project/glpi#5833]
Hello,

In 9.4.2, in software section, GLPI create one software for each computer for software who have the same name, same entity, same version

For example, i have 5 software for the same software "Microsoft Office 365 ProPlus - fr-fr"

Microsoft Office 365 ProPlus - fr-fr | entity toto | Microsoft Corporation | 16.0.11425.20228 | 
Microsoft Office 365 ProPlus - fr-fr | entity toto  | Microsoft Corporation | 16.0.11425.20228 | 
Microsoft Office 365 ProPlus - fr-fr | entity toto  | Microsoft Corporation | 16.0.11425.20228 | 
Microsoft Office 365 ProPlus - fr-fr | entity toto  | Microsoft Corporation | 16.0.11425.20228 | 

**Url** : glpi/front/software.php

**My system :**

Operating system: Linux ssgvweb 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64
PHP 7.2.17-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap,
	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_dblib, pdo_mysql, posix, pspell, readline, recode, session,
	shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl,
	zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at www1.brestaim.fr Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763
Server Software: Ubuntu 18.04
	Server Version: 10.1.38-MariaDB-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket

thanks a lot

**Comment by trasher** [comment]
Use **english**. Thank you.

**Comment by trasher** [comment]
Also, fill al requested informations from template;

**Comment by mulbzh** [comment]
done !

**Comment by trasher** [comment]
This is still incomplete; we do not know if there are plugins, and yu did not mention logs.

**Comment by trasher** [comment]
So, check with all plugins disabled, and if you stil can reproduce, try with last 9.4/bugfixes nightly build.

**Comment by mulbzh** [comment]
i have this error but i think it is after software regroupment  in massive action :

`*** MySQL query error:
  SQL: UPDATE `glpi_computers_softwareversions` SET `softwareversions_id_use` =                                                                                                      '1025' WHERE `softwareversions_id_use` = '1027'
  Error: Unknown column 'softwareversions_id_use' in 'where clause'
  Backtrace :
  inc/dbmysql.class.php:937
  inc/software.class.php:1040                        DBmysql->update()
  inc/software.class.php:373                         Software->merge()
  inc/massiveaction.class.php:991                    Software::processMassiveAct                                                                                                     ionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSe                                                                                                     veralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()`

**Comment by trasher** [comment]
Should be fixed with #5840. Closing for now, please check we'll reopen if needed.
