### ISSUE TITLE
saved search not all recipients notified

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#5835]
**Describe the bug**

Not all users are notified on saved searches.
- Create saved search with an alert (public)
- Select a profile you are a member of as recipient
- Trigger notification

**Expected behavior**

All members of the profile should get the notification.

**Logs**

Deleted all logs - executed notification - logs shows no errors.

**Your GLPI version**
9.4.2

**Additional context**
Seems to have something to do with notify_me and detecting whether it is cron.
If I change the "owner" of the saved search for example to the GLPI admin the notification is sent correctly - of course the GLPI admin wont receive the notification (mySQL -glpi_savedsearches - users_id).

savedsearchesalerts task is set to: Run mode CLI
su - www-data -s /bin/bash -c '/usr/bin/php7.0 /var/www/glpi/front/cron.php'

**Comment by trasher** [comment]
Please try patch proposed #5843

**Comment by Eon9D** [comment]
I will test it in the evening. Thanks!

**Comment by cedric-anne** [comment]
@Eon9D 

Did you test the fix ?

Regards

**Comment by Eon9D** [comment]
Sorry for the late response - I was/am very busy :/

TEST (Group with two people)

Without patch
Person A gets a mail OK
Person B gets no mail NOK

With patch
Person A gets a mail OK
Person B gets a mail OK

Patch works! Thank you very much.
