### ISSUE TITLE
[API] no results with "/Ticket_user/"

### ISSUE THREAD

**Issue by Rico29** [glpi-project/glpi#5837]
**Describe the bug**
I'm using a PHP function which calls GLPI's API like this : 
> ..
>         $this -> url = "search/Ticket_user/";
>         $this -> method = 'GET';
>         $this -> data = array(
>             'criteria' => array(
>                 1 => array(
>                     'field' => 4,
>                     'searchtype' => 0,
>                     'value' => '57'
>                 )
>             )
>         );
> ...

/listSearchOptions/Ticket_user/ says that field 4 is "[field] => users_id", searchtype 0 is "contains", and value is a valid user_id.

When asking directly mysql DB, I get results : 
`# mysql -u root -p glpi_dev -e 'SELECT count(*) FROM `glpi_tickets_users` WHERE `users_id`=57'
Enter password: 
`

> +----------+
> | count(*) |
> +----------+
> |        3 |
> +----------+

GLPI version : 9.4.2

Any idea what can be wrong in my API request ? I'm using same sort of queries to get user, entities, etc... without problems.
Regards
Cédric

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by Rico29** [comment]
here's more info on that -maybe- bug.

my function which calls the API (only interesting parts)

```
    function get_tickets_of_user($id_user){
        $this -> url = "search/Ticket_User/";
        $this -> method = 'GET';
        $this -> data = array(
            'criteria' => array(
                1 => array(
                    'field' => 4,
                    'searchtype' => 0,
                    'value' => '57'
                )
            )
        );
        return $this -> __call_ws();
    }
```
when calling it
```
$glpi = new glpi_api();
print_r($glpi->get_tickets_of_user(57));
```
I see in apache logs : 

> /apirest.php/search/Ticket_User/?criteria%5B1%5D%5Bfield%5D=4&criteria%5B1%5D%5Bsearchtype%5D=0&criteria%5B1%5D%5Bvalue%5D=57

encoded in json : 
> {"criteria":{"1":{"field":4,"searchtype":0,"value":"57"}}} 

But I don't get any results

I do have an user with ID 57 who has 3 tickets : 
```
root@boggs:~# mysql -u root -p glpi_dev -e 'SELECT count(*) FROM `glpi_tickets_users` WHERE `users_id`=57'
Enter password: 
+----------+
| count(*) |
+----------+
|        3 |
+----------+
```

my "__call_ws()" function and the relative class is used by dozens of functions (read and write) without problems.

Can I provide more debug ?
Regards

**Comment by cedric-anne** [comment]
Hi,

Not sure, but `'searchtype' => 0,` seem not valid. Try with `'searchtype' => 'equals',`.

Regards

**Comment by orthagh** [comment]
I agree with @cedric-anne, you are using a wrong searchtype.

By the way, if you want to have all ticket for a user, maybe a simpler query could achieve your need:
`apirest.php/User/5/Ticket_User`

No need to use the search engine for that

**Comment by Rico29** [comment]
@cedric-anne 
it does not work better with 'searchtype'=>'equals'.
listsearchoptions/ticket_user shows : 

>     [4] => Array
>         (
>             [name] => Utilisateur
>             [table] => glpi_users
>             [field] => users_id
>             [datatype] => text
>             [nosearch] => 
>             [nodisplay] => 
>             [available_searchtypes] => Array
>                 (
>                     [0] => contains
>                     [1] => notcontains
>                 )
> 
>             [uid] => Ticket_user.User.users_id
>         )

so 'searchtype' =>'equals' is not valid, isn't it ?

@orthagh : it works fine with "apirest.php/User/57/Ticket_User", thanks for the tip.

**Comment by cedric-anne** [comment]
> so 'searchtype' =>'equals' is not valid, isn't it ?

Indeed, `contains` should be so.

**Comment by Rico29** [comment]
still does not work with searchtype=>'contains'.
