### ISSUE TITLE
Migration log name inconsistency

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#584]
After migration from 0.90.2 to 0.90.3, a log file is created, named migration_to_0.90.2.log, this seems inconsistent and confusing..

Need to check if GLPI_VERSION is defined during update process and use it.

This only happens when there is no scheme update, so no call to $migration->setVersion(), so version used if the one used in 

       $migration = new Migration($current_version);

**Comment by orthagh** [comment]
To be sure of this issue, this inconsistency triggered before (0.85.2 for example) ?
