### ISSUE TITLE
Corporate email footer showing several repeated images in ticket description

### ISSUE THREAD

**Issue by davear6** [glpi-project/glpi#5844]
When a user creates a ticket via email the ticket description shows several footer repeated images in ticket description.

![github_glpi](https://user-images.githubusercontent.com/26468245/56905613-86154b00-6a6e-11e9-8e86-a125690d63be.jpg)

Installation:

Información acerca de la instalación y configuración del sistema
--
[code]   GLPI 9.4.0 ( => /var/www/html) Installation mode: TARBALL

Operating system: Linux phdesk01v 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 PHP 7.3.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="180" memory_limit="1024M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.3.2 () 	Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.25 	Server SQL Mode:  	Parameters: admin@localhost/helpdesk 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (5.7.25) - Perfect! /var/www/html/files/_log : OK /var/www/html/config : OK /var/www/html/files : OK /var/www/html/files/_dumps : OK /var/www/html/files/_sessions : OK /var/www/html/files/_cron : OK /var/www/html/files/_graphs : OK /var/www/html/files/_lock : OK /var/www/html/files/_plugins : OK /var/www/html/files/_tmp : OK /var/www/html/files/_cache : OK /var/www/html/files/_rss : OK /var/www/html/files/_uploads : OK /var/www/html/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

**Comment by trasher** [comment]
You should first try with latest release and see if reproduce.

**Comment by davear6** [comment]
I installed 9.4.2 and I still have the same problem

![newest_version_problem](https://user-images.githubusercontent.com/26468245/57102456-85401b80-6cf1-11e9-99f9-095228b784a6.png)

**Comment by trasher** [comment]
It may be due to the mail content, each mail client do its own stuff. We need the original source email.

**Comment by davear6** [comment]
I am attaching an original example email and image.
![image1](https://user-images.githubusercontent.com/26468245/57145930-34ccca80-6d92-11e9-8ba1-9cbe5306eb77.png)

[email.zip](https://github.com/glpi-project/glpi/files/3142445/email.zip)

**Comment by trasher** [comment]
i'm sorry, but this message format does not seems usable.

**Comment by trasher** [comment]
What we need is an original email, not a forward from another mailbox, please sent it to glpi-debug@teclib.com

**Comment by davear6** [comment]
ok, I will send the email later as I have to ask for permission for outgoing mails. 

We also found out that the images repeating are the ones that have the same tag on the database which are stored as documents earlier in the past.

![repeated](https://user-images.githubusercontent.com/26468245/57228725-7c499580-6fe2-11e9-9dfe-498cbf300cca.png)

**Comment by trasher** [comment]
@davear6 please try fox proposal #5868

**Comment by davear6** [comment]
Fix works fine, thank you very much for your help.
