### ISSUE TITLE
9.4.2 - NetworkName - Unable to search by NetworkName ID

### ISSUE THREAD

**Issue by Jean-Christophe-P** [glpi-project/glpi#5848]
**Describe the bug**

When search thru the network name dropdowns, if you select the ID field, it actually search for the ID of the network port it is associated with not the ID of the Network Name itself.

**To reproduce**
1. Go to 'Setup' -> 'DropDowns' -> "Network Names'
2. Select 'Chracteristic - ID' as search criteria
3. Add a Network Port ID as criteria value
4. Click "Search"

**Expected behavior**
Getting the network ports where the ID contains what you searched for

**Actual behavior**
You get the list of network names where the linked network port ID contains your search string.

**Additional Info**
This makes the search for network names unavailable thru the API also. This is how I discovered this.
The search options for the NetworkName object type doesn't contains the item 2 (witch is often the ID)

**Comment by cedric-anne** [comment]
Hi,

This `ID` field is not buggy, but it's label is not correct. Maybe it should be changed to `Associated item`.

But I do not understand why you want to use a search function in API if you know the ID of an element. Can you explain the use case ?

There are some elements where there is no search option on the ID field. I do not know why, and I am not sure it can be fixed globally. I have to check if there is something that may prevent to handle it globally.

Regards

**Comment by Jean-Christophe-P** [comment]
Sorry for the delay.
Honestly, I don't remember the initial goal.
I went around and found another way to do want I wanted.

It just looked strange that the criteria 2 wan't present for this specific object.

**Comment by trasher** [comment]
Network related objects are very specific in GLPI, and cannot be considered identical to others; espcaially on the ID.

This is not going to change since this is a real nightmare.

**Comment by Jean-Christophe-P** [comment]
I agree. 
I spend several weeks with trials and errors (lot of them) to finally have a working solution to manage network port, network name, IP, etc... on phones (via API).
