### ISSUE TITLE
rest api TicketFollowup

### ISSUE THREAD

**Issue by Akuket** [glpi-project/glpi#5859]
Hello,

We use the rest API of glpi to create tickets and follow-ups. Before we used the url `Ticket/:id:TicketFollowup` to add a followup to one ticket. But now, we have a 400 error. Maybe since TicketFollowup class is deprecated? Must we do use the ITILFollowup? And with what url and parameters?

Regards.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
