### ISSUE TITLE
9.4.2 - Console tool - ldap sync - PHP Notice

### ISSUE THREAD

**Issue by J-C-P** [glpi-project/glpi#5860]
**Describe the bug**

Using the console tool to sync ldap users gives a lot of PHP Notice.

**To reproduce**

./console  ldap:sync --ldap-server-id 2 -n

**Expected behavior**

Clean output.

**Logs**

```
A lot of...
PHP Notice:  Undefined index: modifytimestamp in /var/www/html/glpi/inc/authldap.class.php on line 1686
PHP Notice:  Undefined index: modifytimestamp in /var/www/html/glpi/inc/authldap.class.php on line 1701
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.2 ( => /var/www/html/glpi)
Installation mode: TARBALL

Operating system: Linux GLPI-01 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64
PHP 7.0.33-0+deb9u3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, ssh2, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi.cgdis.lu Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36
Server Software: Debian 9.6
	Server Version: 10.1.37-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
```

**Additional context**

It looks like it doesn't impact the functionality. It could be only a cosmetic issue.

**Comment by trasher** [comment]
dup of https://github.com/glpi-project/glpi/issues/3672?

**Comment by cedric-anne** [comment]
Hi,

Which LDAP server do you use, and in which version ?

Regards

**Comment by Jean-Christophe-P** [comment]
Hi Trasher,
php_errors.log doesn't contain any error related to the problem I have.

cedric-anne,
This is an Active Directory 2016 server. Does it answer your question?

Thanks,
JC

**Comment by cedric-anne** [comment]
I do not really know how to configure an AD, but, as far as I understand articles I just read, it seems that you have to permit reading of `modifyTimeStamp` attribute on the server side.

**Comment by Jean-Christophe-P** [comment]
Thanks for the followup.

By default, in AD, every authenticated users have read permission on all properties (except password and privates field, but ModifyTimeStamp is not private).

![image](https://user-images.githubusercontent.com/21988062/57129851-f76b3b80-6d97-11e9-9443-1f33bf6dc7c1.png)

**Comment by cedric-anne** [comment]
The PHP `ldap_search` function is used to get list of users and the `modifyTimeStamp` is explicitely listed in attributes argument.
Can you try to use another tool to see if this attribute is part of the response when doing a search on AD ?

**Comment by Jean-Christophe-P** [comment]
Here we are.
As you can see, I run the command using the same account srvGLPI.

In PowerShell from a random server.
The ModifyTimeStamp is available.
![image](https://user-images.githubusercontent.com/21988062/57133809-43bc7880-6da4-11e9-88e5-8e67396e1a6e.png)

From the GLPI server, using ldapsearch, using the GLPI account.
the ModifyTimeStamp is also available.
![image](https://user-images.githubusercontent.com/21988062/57134196-a95d3480-6da5-11e9-96c9-2a9ba5d42196.png)

**Comment by cedric-anne** [comment]
Hi. Unfortunately, as I have no access to any AD, I cannot really help to debug this.

**Comment by Jean-Christophe-P** [comment]
I have access to plenty of AD but I'm totally useless in programming :-/

**Comment by trasher** [comment]
I made some tests for the old ticket on an internal AD, but I've never been able to reproduce. This may be related to the version, or config on any side... :/

**Comment by Jean-Christophe-P** [comment]
On the AD side, there is no specific config. It is straight out of the box.

On Monday morning, I will have access to another GLPI 9.4.2 setup linked to another AD. I will try and let you know if I reproduce the issue.
Have a good weekend you all :-)

**Comment by Jean-Christophe-P** [comment]
So...
I tried on another AD server from another GLPI 9.4.2 instance.
The result is not the same.
Still a lot of undefined indexes but not the same variable...

![image](https://user-images.githubusercontent.com/21988062/57294969-96aa6e80-70c9-11e9-8f40-060d3e3cfa06.png)

**Comment by cedric-anne** [comment]
Hi,

Could you test following patch:
```diff
diff --git a/inc/authldap.class.php b/inc/authldap.class.php
index 6430621d7b..39ecead9a9 100644
--- a/inc/authldap.class.php
+++ b/inc/authldap.class.php
@@ -1845,7 +1845,7 @@ class AuthLDAP extends CommonDBTM {
                                    'timestamp'  => $user_infos[$userfound[$field_for_sync]]['timestamp'],
                                    'date_sync'  => $tmpuser->fields['date_sync'],
                                    'dn'         => $user['user_dn']];
-               } else if (($values['action'] == self::ACTION_ALL)
+               } else if (($values['mode'] == self::ACTION_ALL)
                           || (($ldap_users[$user[$field_for_db]] - strtotime($user['date_sync'])) > 0)) {
                   //If entry was modified or if script should synchronize all the users
                   $glpi_users[] = ['id'         => $user['id'],
```

Regards

**Comment by Jean-Christophe-P** [comment]
Hello Cedric-Anne,
I confirm your patch solves the PHP Notices I had on my second test.

However, it doesn't change anything for the first problem (PHP Notice:  Undefined index: modifytimestamp)
Thanks for your quick reaction :-)

**Comment by cedric-anne** [comment]
Hi,

I made a PR to fix this undefined `action` (see https://github.com/glpi-project/glpi/pull/5881) but keep this ticket opened for the initial issue.

Regards
