### ISSUE TITLE
After update from 9.3.3 to 9.4.2 - technical user can not write comments in tickets

### ISSUE THREAD

**Issue by wadaki** [glpi-project/glpi#5870]
**Describe the bug**
I updated GLPI from 9.3.3 to 9.4.2, there is not SQL error when I login as "glpi" user. The update was fine.
But I have trouble in my tickets. I old tickets and in new new tickets I can not add a comment as "followup", than I get a permission error only. It's possible to create a "task", "document" and "solution" as well, only the "followup" works not. (See screen shot.)

**Page(s) URL**

http://172.17.xxx.xx/glpi/front/ticket.form.php?id=248

**To reproduce**

1. Go to 'Tickets'
2. Open a 'ticket'
3. Click to 'followup'

**Expected behavior**

After I clicked "followup" button, I can see a message "You don't have permission to perform this action."
This message is available as glpi administrator, technical user and end user.

**Logs**
SQL-error-log

[code]
[2019-05-07 10:39:24] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt FROM `glpi_itils_projects` WHERE `itemtype` = 'Ticket' AND `items_id` = '248'
  Error: Unknown column 'itemtype' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:569                          DBmysqlIterator->execute()
  inc/dbutils.class.php:329                          DBmysql->request()
  inc/db.function.php:178                            DbUtils->countElementsInTable()
  inc/itil_project.class.php:76                      countElementsInTable()
  inc/commonglpi.class.php:210                       Itil_Project->getTabNameForItem()
  inc/ticket.class.php:878                           CommonGLPI->addStandardTab()
  inc/commonglpi.class.php:165                       Ticket->defineTabs()
  inc/commonglpi.class.php:707                       CommonGLPI->defineAllTabs()
  inc/commonglpi.class.php:1005                      CommonGLPI->showTabsContent()
  front/ticket.form.php:217                          CommonGLPI->display()
  {"user":"2@tkysv0079","mem_usage":"0.001\", 8.38Mio)"}
[/code]  

```

**Screenshots**

If applicable, add screenshots to help explain your problem.


**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]
 
GLPI 9.4.2 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux XXXXXXXX4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64
PHP 7.0.33-0+deb9u3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at 172.17.200.79 Port 80)
	Mozilla/5.0 (X11; Gentoo; rv:65.0) Gecko/20100101 Firefox/65.0
Server Software: Debian 9.1
	Server Version: 10.1.26-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (10.1.26) - Perfect!Database version seems correct (10.1.26) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

Libraries

 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.3 in (/usr/share/php)

LDAP directories

 
Server: '172.17.202.100', Port: '389', BaseDN: 'dc=senju,dc=com,dc=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'cn=S0115,ou=User,ou=Users,ou=SENJU,dc=senju,dc=com,dc=local', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP+TLS (xxxxx@xxxxx.com@smtp.office365.com)

Mails receivers

 
Name: 's0121@senju.com' Active: Yes
	Server: '{outlook.office365.com:993/imap/ssl}' Login: 'xxxxx@xxxxx.com' Password: Yes

Plugins list

 
	dashboard            Name: Dashboard                      Version: 0.9.5      State: Not installed
	formcreator          Name: Form Creator                   Version: 2.8.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled
	addressing           Name: IP Adressierung                Version: 2.8.0      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.6.1      State: Not activated
	genericobject        Name: Objects management             Version: 2.7.0      State: Enabled

[/code] 
```

**Additional context**

Add any other context about the problem here.

**Comment by wadaki** [comment]
![20190507_101521_Window](https://user-images.githubusercontent.com/8577568/57266578-74a7f080-70b7-11e9-8b79-2c59ea13a4ce.png)
Added screen shot

**Comment by wadaki** [comment]
![20190507_101521_Window](https://user-images.githubusercontent.com/8577568/57266626-bf296d00-70b7-11e9-9718-4625735a244b.png)
Added screen shot.

**Comment by cedric-anne** [comment]
Hi,

The only explaination I have is that the update was not done correctly.

As explained [here in the warning section](https://glpi-install.readthedocs.io/en/latest/update.html), please:
 - empty your database (i.e. drop all glpi_* tables),
 - restore your SQL dump,
 - run the update again.

Regards

**Comment by wadaki** [comment]
I understand, but is there no other option?

Best regards


Von: notifications@github.com
Gesendet: 7. Mai 2019 18:02
An: glpi@noreply.github.com
Antworten: reply@reply.github.com
Cc: rsato@senju.com; author@noreply.github.com
Betreff: Re: [glpi-project/glpi] After update from 9.3.3 to 9.4.2 - technical user can not write comments in tickets (#5870)



Hi,

The only explaination I have is that the update was not done correctly.

As explained here in the warning section<https://glpi-install.readthedocs.io/en/latest/update.html>, please:

  *   empty your database (i.e. drop all glpi_* tables),
  *   restore your SQL dump,
  *   run the update again.

Regards

**Comment by trasher** [comment]
Your database is broken, there is no way to know what is wrong really; this is the best way to go.

You can use the "console db:check" command if you want to fix yourself, but there are no guarantees.
