### ISSUE TITLE
524 tables not migrated to InnoDB engine

### ISSUE THREAD

**Issue by Sophal-Cam** [glpi-project/glpi#5873]
Dear team,

I have updated my glpi to 9.4.2 and i have this message :

524 tables not migrated to InnoDB engine.

What should i do to fix this ?

Thanks.
Sophal IT

**Comment by trasher** [comment]
https://glpi-install.readthedocs.io/en/latest/command-line.html#from-myisam-to-innodb

**Comment by Sophal-IT** [comment]
Hello there,

Could you please more detail about that link. My GLPI is working with Centos 6 OS. I already tried follow by your link but not work. 

Thanks for your respond.
Sophal

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
