### ISSUE TITLE
how to increase the solution time of a GLPI SLAs - How to change the maximum service time in GLPI

### ISSUE THREAD

**Issue by august-pinh** [glpi-project/glpi#5878]
how to increase the solution time of a GLPI SLAs?
Maximum is 100, i need more of 100, to 120, 150, 180...

**Comment by august-pinh** [comment]
How to change the maximum service time in GLPI

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support or use [suggestion website](http://suggest.glpi-project.org) for RFE.
