### ISSUE TITLE
Tab Solution only if ticket has status Solved

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#588]

**Comment by orthagh** [comment]
I don't understand this issue (and the commit).
Why restrict solution tab only on solved status (how we solve the ticket ?)

I you wanted to exclude Solution tab when timeline is enabled, i think the commit is not the right one.

**Comment by tomolimo** [comment]
For me the 'solve' status comes after the solution is set.
Then if status is 'processing', and a tech sets a solution, then the status will be automatically set to 'solved'.
And not reverse...
