### ISSUE TITLE
9.4.2 API return glpi login page in response

### ISSUE THREAD

**Issue by PowerShellPlace** [glpi-project/glpi#5880]
**Describe the bug**

When I call an API first time I get HTML page, in php return code is 302 (page loaded for later use), every next API call return desired object

What can I do? I want to call an API once and get object 

Thank you 

**Page(s) URL**

For Ex. http://pathtoglpi/glpi/apirest.php/Computer/

**Expected behavior**

Return Ex. Computer object

**Screenshots**
GLPI 9.4.2

**Comment by AdrienClairembault** [comment]
Hello,

I saw this exact problem a few months ago, if I remember correctly it was caused by a plugin (I think it was "My Dashboard").
Do you use this plugin ? If so can you disable it and check if it makes a difference ?

**Comment by PowerShellPlace** [comment]
Yes, we are using this plugin :) I disabled, and API works perfect! 
Thank you :) Issue is to close
