### ISSUE TITLE
PHP Warning in php-errors.log

### ISSUE THREAD

**Issue by giorini** [glpi-project/glpi#5886]
I get the following message, someone has an idea of what it is. Thank you

[2019-05-09 15:14:13] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): unlink(/var/www/html/glpi/files/_tmp/auto_orient): Is a directory
  Backtrace :
  :                                                  
  inc/crontask.class.php:1602                        unlink()
  inc/crontask.class.php:829                         CronTask::cronTemp()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@glpi-server"} 

The alert comes out after executing the scheduled task temp

![image](https://user-images.githubusercontent.com/48732125/57484575-c00cfb00-727f-11e9-9036-7d70ba6c2755.png)

![image](https://user-images.githubusercontent.com/48732125/57484826-6eb13b80-7280-11e9-9d96-53e0fa4a0494.png)

**Comment by trasher** [comment]
Missing informations from issue template

**Comment by cedric-anne** [comment]
Duplicates #5449.
