### ISSUE TITLE
GLPI : Login ?lang=<code> parameters

### ISSUE THREAD

**Issue by iGitnow** [glpi-project/glpi#5887]
**Is your feature request related to a problem? Please describe.**

One piece I think is missing that would have made the multi-lingual approach complete, is to allow a ?lang=fr or a ?lang=en parameter when the login page is called. This would allow companies like ours, that have the same version of a website in different languages, to redirect their customers to the right login form (the right language).

**Describe the solution you'd like**

The feature described above I see it implemented just for the login page. Once logged in, the implementation in GLPI, based on the user profile, is just perfect.

**Describe alternatives you've considered**

Tried researching a bit the code and came up with a few alternatives. However any solution I could find wasn't clean enough for future upgrades.

-  Defining the $_SESSION['glpilanguage'] based on a URL parameter, within the index.php is not sufficient. The initial call to the login page ignores the definition. A refresh of the login page will trigger the wanted language.

-  I took my investigation further and I noticed that handling such a change would involve modifying several include files among them config, session.class, based_config...

This is why I thought this feature request would make sense, since it will become a better lasting solution (future upgrades).

Cheers!

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
