### ISSUE TITLE
Error in Profiles - GLPI 9.4.2

### ISSUE THREAD

**Issue by grcmec** [glpi-project/glpi#5901]
**Describe the bug**

I have an error when access to Profiles, Assets - Assistance - Management - Tools - Administration - Setup - Reports - OCSNG - Other alerts - Domains - Barcode, show the following error:

An error ocurred loading contets!
Please check GLPI logs or contact your
administrator.
or try to reload.

Actually we use GLPI on CentOS 7.5

![image](https://user-images.githubusercontent.com/28117868/57666788-d63ff180-75c6-11e9-8a52-8958474a420c.png)

**Page(s) URL**

This error occur in all profiles menu.

**To reproduce**

1. Go to Administration - Profiles - Select one of the profiles
2. Click on Assets or Assistance
3. See error

![image](https://user-images.githubusercontent.com/28117868/57666898-40f12d00-75c7-11e9-9c64-eda6bb2c34d3.png)

**Expected behavior**

The correct should be the right that the profile have.

**Logs**

[2019-05-13 21:35:01] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): mysqli::__construct(): Headers and client library minor version mismatch. Headers:50560 Library:100136
  Backtrace :
  :
  inc/dbmysql.class.php:105                          mysqli->__construct()
  inc/dbmysql.class.php:78                           DBmysql->connect()
  plugins/ocsinventoryng/inc/dbocs.class.php:56      DBmysql->__construct()
  ...ins/ocsinventoryng/inc/ocsdbclient.class.php:52 PluginOcsinventoryngDBocs->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1788 PluginOcsinventoryngOcsDbClient->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2952 PluginOcsinventoryngOcsServer::getDBocs()
  inc/crontask.class.php:829                         PluginOcsinventoryngOcsServer::cronocsng()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@swd-ct-ocsglpi"}

[2019-05-13 21:35:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): mysqli::__construct(): Headers and client library minor version mismatch. Headers:50560 Library:100136
  Backtrace :
  :
  inc/dbmysql.class.php:105                          mysqli->__construct()
  inc/dbmysql.class.php:78                           DBmysql->connect()
  plugins/ocsinventoryng/inc/dbocs.class.php:56      DBmysql->__construct()
  ...ins/ocsinventoryng/inc/ocsdbclient.class.php:52 PluginOcsinventoryngDBocs->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1788 PluginOcsinventoryngOcsDbClient->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1855 PluginOcsinventoryngOcsServer::getDBocs()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:128 PluginOcsinventoryngOcsServer::checkVersion()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2960 PluginOcsinventoryngOcsProcess::manageDeleted()
  inc/crontask.class.php:829                         PluginOcsinventoryngOcsServer::cronocsng()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@swd-ct-ocsglpi","mem_usage":"0.165\", 11.10Mio)"}
[2019-05-13 21:35:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): mysqli::__construct(): Headers and client library minor version mismatch. Headers:50560 Library:100136
  Backtrace :
  :
  inc/dbmysql.class.php:105                          mysqli->__construct()
  inc/dbmysql.class.php:78                           DBmysql->connect()
  plugins/ocsinventoryng/inc/dbocs.class.php:56      DBmysql->__construct()
  ...ins/ocsinventoryng/inc/ocsdbclient.class.php:52 PluginOcsinventoryngDBocs->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1788 PluginOcsinventoryngOcsDbClient->__construct()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:132 PluginOcsinventoryngOcsServer::getDBocs()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2960 PluginOcsinventoryngOcsProcess::manageDeleted()
  inc/crontask.class.php:829                         PluginOcsinventoryngOcsServer::cronocsng()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@swd-ct-ocsglpi","mem_usage":"0.201\", 11.15Mio)"}
[2019-05-13 21:35:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): mysqli::__construct(): Headers and client library minor version mismatch. Headers:50560 Library:100136
  Backtrace :
  :
  inc/dbmysql.class.php:105                          mysqli->__construct()
  inc/dbmysql.class.php:78                           DBmysql->connect()
  plugins/ocsinventoryng/inc/dbocs.class.php:56      DBmysql->__construct()
  ...ins/ocsinventoryng/inc/ocsdbclient.class.php:52 PluginOcsinventoryngDBocs->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1788 PluginOcsinventoryngOcsDbClient->__construct()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:856 PluginOcsinventoryngOcsServer::getDBocs()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2996 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  inc/crontask.class.php:829                         PluginOcsinventoryngOcsServer::cronocsng()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@swd-ct-ocsglpi","mem_usage":"0.288\", 11.28Mio)"}
[2019-05-13 21:35:03] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): mysqli::__construct(): Headers and client library minor version mismatch. Headers:50560 Library:100136
  Backtrace :
  :
  inc/dbmysql.class.php:105                          mysqli->__construct()
  inc/dbmysql.class.php:78                           DBmysql->connect()
  plugins/ocsinventoryng/inc/dbocs.class.php:56      DBmysql->__construct()
  ...ins/ocsinventoryng/inc/ocsdbclient.class.php:52 PluginOcsinventoryngDBocs->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1788 PluginOcsinventoryngOcsDbClient->__construct()
  plugins/ocsinventoryng/hook.php:1328               PluginOcsinventoryngOcsServer::getDBocs()
  inc/plugin.class.php:1196                          plugin_ocsinventoryng_ruleCollectionPrepareInputDataForProcess()
  inc/rulecollection.class.php:1705                  Plugin::doOneHook()
  inc/rulecollection.class.php:1528                  RuleCollection->prepareInputDataForProcessWithPlugins()
  ...ins/ocsinventoryng/inc/ocsprocess.class.php:885 RuleCollection->processAllRules()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2996 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  inc/crontask.class.php:829                         PluginOcsinventoryngOcsServer::cronocsng()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@swd-ct-ocsglpi","mem_usage":"0.696\", 12.23Mio)"}
[2019-05-13 21:35:04] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Warning(2): mysqli::__construct(): Headers and client library minor version mismatch. Headers:50560 Library:100136
  Backtrace :
  :
  inc/dbmysql.class.php:105                          mysqli->__construct()
  inc/dbmysql.class.php:78                           DBmysql->connect()
  plugins/ocsinventoryng/inc/dbocs.class.php:56      DBmysql->__construct()
  ...ins/ocsinventoryng/inc/ocsdbclient.class.php:52 PluginOcsinventoryngDBocs->__construct()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:1788 PluginOcsinventoryngOcsDbClient->__construct()
  ...inventoryng/inc/ocsadmininfoslink.class.php:276 PluginOcsinventoryngOcsServer::getDBocs()
  ...ns/ocsinventoryng/inc/ocsprocess.class.php:1165 PluginOcsinventoryngOcsAdminInfosLink::updateAdministrativeInfo()
  ...ins/ocsinventoryng/inc/ocsserver.class.php:2996 PluginOcsinventoryngOcsProcess::synchronizeComputer()
  inc/crontask.class.php:829                         PluginOcsinventoryngOcsServer::cronocsng()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@swd-ct-ocsglpi","mem_usage":"1.124\", 13.98Mio)"}

**Screenshots**

![image](https://user-images.githubusercontent.com/28117868/57667141-1653a400-75c8-11e9-9c30-39a9a12459fa.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Information about system installation & configuration
--
Operating system: Linux swd-ct-ocsglpi 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64
PHP 7.1.21 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring,
	mcrypt, mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sqlite3, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="50M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.21 mod_perl/2.0.10 Perl/v5.16.3 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: MariaDB Server
	Server Version: 10.1.36-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/HelpDesk
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (10.1.36) - Perfect!Database version seems correct (10.1.36) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

```

**Additional context**

**Comment by trasher** [comment]
>  Headers and client library minor version mismatch. Headers:50560 Library:100136
 
Seems like a system issue, check your PHP installation.
