### ISSUE TITLE
Logs Not Imported Emails

### ISSUE THREAD

**Issue by MonakaDev** [glpi-project/glpi#5903]
Hello,

I have some emails that are refused for no reason and they don't end up in the list of non-imported emails in GLPI.

How could I add logs for each email that are not imported ?

Thanks you.

**Comment by trasher** [comment]
Not imported are reset each time collecteor is launched. It sounds like a configuration issue, please request help on [forums](http://forum.glpi-project.org) to get support.

**Comment by MonakaDev** [comment]
Thanks, already did a post but nobody helped me : https://forum.glpi-project.org/viewtopic.php?id=168840
