### ISSUE TITLE
Security die. trying to load a forbidden class name

### ISSUE THREAD

**Issue by liberodark** [glpi-project/glpi#5905]
Hi,

Have error when try to open issue groupe.
Is very strange you have screenshot.
My DB is upgraded with your script and have upgrade GLPI 9.2 to 9.4.2.
All work / All plugins is updated.

GLPI 9.4.2

**Server**

```
Operating system: Linux fr-cfe-helpdesk.novalocal 3.10.0-957.12.1.el7.x86_64 #1 SMP Mon Apr 29 14:59:59 UTC 2019 x86_64
PHP 7.2.18 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.18 ()
	Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.17-log
	Server SQL Mode: 
	Parameters: glpiuser@10.200.103.191:8635/glpi
	Host info: 10.200.103.191 via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (5.7.17) - Perfect!Database version seems correct (5.7.17) - Perfect!
OK/var/www/glpi/files/_log : OK
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_cache : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

```

**Libraries**

```
htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/plugins/mreporting/vendor/symfony/console)
leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.7 in (/usr/share/pear)
```

**Plugins**

       treeview             Name: Arborescence                   Version: 1.8.0      State: Enabled
	badges               Name: Badges                         Version: 2.5.0      State: Enabled
	shellcommands        Name: Commandes Shell                Version: 2.3.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.2      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled
	geninventorynumber   Name: Génération de numéros d'invent Version: 2.4.0      State: Enabled
	genericobject        Name: Gestion d'objets               Version: 2.7.0      State: Enabled
	order                Name: Gestion des commandes          Version: 2.5.0      State: Enabled
	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled
	reports              Name: Rapports                       Version: 1.13.0     State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.6      State: Enabled

**Logs**

```
[Fri Mar 08 14:49:20.402229 2019] [:error] [pid 25345] [client 10.10.100.100:54961] script '/var/www/glpi/front/__fortiweb_test__.php' not found or unable to stat
[Fri Mar 08 14:49:20.506550 2019] [:error] [pid 25345] [client 10.10.100.100:54961] script '/var/www/glpi/front/__fortiweb_test__.php' not found or unable to stat
[Fri Mar 08 14:49:20.611064 2019] [:error] [pid 25345] [client 10.10.100.100:54961] script '/var/www/glpi/front/__fortiweb_test__.php' not found or unable to stat
```

**Screenshots**

![image](https://user-images.githubusercontent.com/4238928/57688829-a8968f00-763e-11e9-8283-f67ed2300abd.png)

**Comment by cedric-anne** [comment]
Hi,

Your logs are related to a file that is not part of GLPI core, and you did not provide requested informations.

Regards

**Comment by liberodark** [comment]
Where is it ?

**Comment by liberodark** [comment]
My only problem is Security die. trying to load a forbidden class name not the forninet php page.

**Comment by liberodark** [comment]
Please reopen my issue

**Comment by trasher** [comment]
Please provide requested informations...

**Comment by liberodark** [comment]
Yes im work on

**Comment by liberodark** [comment]
Is done please reopen my issue have explain all informations.

**Comment by cedric-anne** [comment]
Hi,

You have a lot of plugins, please deactivate them and make a new test.

Regards

**Comment by liberodark** [comment]
ok im try this

**Comment by cedric-anne** [comment]
Hi,

I think you have somewhere in your database a line with a numeric value in an `itemtype` column. In GLPI core, this behaviour has been changed in 0.80 version.
So if you have a numeric value in an `itemtype` column, it means that a plugin you used had generated this kind of data and does not uses the migration function provided by GLPI core ( see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/plugin.class.php#L781 ). In this case, as the migration is the responsibility of the plugin, we cannot help.

Regards

**Comment by nectop** [comment]
Same issue with current release. 
I'm tiring to Search Query Management
![image](https://user-images.githubusercontent.com/26596969/86118690-e328e880-bad9-11ea-8b64-ade095f07f0e.png)

**Comment by cedric-anne** [comment]
This will not be reopened. We removed this "Security die" on 9.5 branch (that is already in RC phase), and, as sid on latest comment, it can only be fixed by the plugin who created the related entry in DB.
