### ISSUE TITLE
Add observer automatically from email

### ISSUE THREAD

**Issue by MonakaDev** [glpi-project/glpi#5909]
Hello,

I found out why some e-mails was not collected in GLPI. It happens when someone that is not an observer or the requester of the ticket respond to a follow up.

Is it possible to automatically add them in the observers of the ticket when they send the email ?

**Comment by cedric-anne** [comment]
Hi,

You have a configuration param that can be set to allow anyone to add followups (in "Setup > General > Assistance").
![image](https://user-images.githubusercontent.com/33253653/57838772-a7dc3500-77c5-11e9-9279-3dd32502b9ad.png)

If you need more support, please use [forums](https://forum.glpi-project.org/) for that.

Regards

**Comment by MonakaDev** [comment]
Hello,

the mails that are refused are from people already in the user database, meaning that they are not anonymous. That's why it is a problem for me.

**Comment by cedric-anne** [comment]
Did you test to change this option ?

As I said, if you need more support, please use [forums](https://forum.glpi-project.org/) for that.

**Comment by MonakaDev** [comment]
The problem with this option is it allows anybody to create tickets/followups, but I want only the users in GLPI to have the right to do it. 
The e-mails that I got refused are from GLPI users, but they are still getting refused and I think it's because they are not specified as "observer" in the ticket they respond to. 
So I'm trying to know if it is possible to modify the code to add them as observer automatically when they respond to a ticket they are not in only if they are in the GLPI user database, do you understand?

I've already made a post, but nobody is helping me: https://forum.glpi-project.org/viewtopic.php?id=168840
