### ISSUE TITLE
9.4.x Solution types from all entities under entity

### ISSUE THREAD

**Issue by bigworld1** [glpi-project/glpi#5910]
After update to 9.4.x when adding solution to a ticket in sub-entity and chosing Solution type, all solution types for all entities are listed. http://glpi/front/ticket.form.php?id=xxx

**Comment by trasher** [comment]
I do not reproduce on latest release, this may have been fixed.
Feel free to reopen if the issue persists, and take care to provide all useful informations in order to reproduce.
