### ISSUE TITLE
[9.4.2] eml files are not attached to the ticket by mailgate

### ISSUE THREAD

**Issue by schoubi** [glpi-project/glpi#5913]
**Describe the bug**

We use mailgate to create ticket from mail adressed to the support team.

Sometimes, we received forwarded mail as attached file (.eml, type message/rfc822).

So we added two types of documents: 

- "Mime message" with type mime "message/rfc822"
- "Forward message" with extension "eml"

But we never see the attached file. GLPI worked as if the file isn't exist at all. The ticket contain only the mail body, but no file is attached to the ticket.

If i directly upload the file.eml in the ticket, it is correctly attached and detected as "message/rfc822"

**To reproduce**

1. Add two types of documents in GLPI: 
- "Mime message" with type mime "message/rfc822"
- "Forward message" with extension "eml"

2. Configure your mail client to forward mail as attached files (.eml)

3. Forward a mail to GLPI

4. The ticket is correctly created but no file attached.

**Expected behavior**

Eml must be attached to the ticket the same way it is when we upload it directly.

**Comment by bigben386** [comment]
I just came across this issue as well. I was trying to setup the knowbe4 phish alert program for my users but noticed none of the attachments are available in glpi. Has anyone come up with a solution for this?

**Comment by cedric-anne** [comment]
Hi,

Can you provide an export (in eml format) of your email that cause the problem ?
Can you also check in logs if you see somthing related to this ?

Regards

**Comment by bigben386** [comment]
There is an error in php-errors. Not sure if it is related `[2020-07-07 13:49:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolb$
  *** PHP Notice(8): Undefined variable: message
  Backtrace :
  inc/mailcollector.class.php:1649
  inc/mailcollector.class.php:1550                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:1688                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:861                    MailCollector->getAttached()
  inc/mailcollector.class.php:684                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1799                   MailCollector->collect()
  :                                                  MailCollector::cronMailgate()
  inc/crontask.class.php:829                         call_user_func()
  front/cron.php:61                                  CronTask::launch()
  {"user":"@ocs-ng"}
`

No errors in mail.log.

I added .eml to the file types list but it made no difference

These eml files are from gmail forward as attachment.

**Comment by cedric-anne** [comment]
Hi,

I just made a test with GLPI 9.5 (with #7652 fix), and, after adding eml as a document type (see image below), mailgate crontask correctly create a new ticket with an attached eml document.

![image](https://user-images.githubusercontent.com/33253653/87305109-3b1e1100-c516-11ea-8645-cd5e7d66c161.png)

![image](https://user-images.githubusercontent.com/33253653/87305188-5db02a00-c516-11ea-93fd-2ca720c2756b.png)

So I close this issue as it is already fixed in current supported version (GLPI 9.5).

Regards
