### ISSUE TITLE
Upgrade to Fullcalendar v4

### ISSUE THREAD

**Issue by OscarBeiro** [glpi-project/glpi#5917]
**Is your feature request related to a problem? Please describe.**
There are some bugs in current v3, plus interesting new features in the new version

**Describe the solution you'd like**
Simply upgrade Fullcalendar to v4 

**Describe alternatives you've considered**

**Additional context**
Useful links:
- https://fullcalendar.io/docs#toc

- https://fullcalendar.io/docs/upgrading-from-v3

**Comment by orthagh** [comment]
Hello Óscar.

We have the project to do it, we have a private "request for evolution" in progress with another customer for this subject.
If you want, i can show you the document on our private support (you know how to do).

But in summary, here is what we plan for planning
- support external event (human ressources managements) with recurrent actions / background events
- upgrade to last version (more, it doesn't depends on jquery)
- webcal import
- add [scheduler addon](https://fullcalendar.io/scheduler)
- drag & drop not planned events (sort of the plugin you did on your side)
- clone events (by ctrl + drag event)

And here is a mockup for the main idea (manage technicians capacity):

![image](https://user-images.githubusercontent.com/418844/57853843-167dba80-77e7-11e9-9b98-d96de2afdd7f.png)

Regards.
Alexandre.

**Comment by OscarBeiro** [comment]
Great news!
Thanks.

**Comment by cedric-anne** [comment]
Done in #6025 .
