### ISSUE TITLE
GLPI v9.1.2 compatibility issue in IE8

### ISSUE THREAD

**Issue by vkasharma** [glpi-project/glpi#5920]

**Comment by vkasharma** [comment]
I have been trying glpi version 9.1.2 in IE8 but I have been facing some jQuery related issues. There's no other browser is an option for me. so any help will be appreciated. 

![error_js](https://user-images.githubusercontent.com/11803704/57908013-a0d42600-789c-11e9-9914-40f59829f78d.jpg)

**Comment by cedric-anne** [comment]
Hi,

IE8 support has ended in 2014/04/08 and external libraries we use progressively drop compatibility with this version of IE. Since we need to use recent versions to take advantage of the latest features of these libraries, we can not go against this loss of compatibility.

Regards

**Comment by sbind29893** [comment]
I am also facing the same issue. Kindly help
