### ISSUE TITLE
status.php check IMAP authentication

### ISSUE THREAD

**Issue by spegghy69** [glpi-project/glpi#5922]
status.php display Problem checking Mail authentication  (IMAP in my case).
The problem is due not setting $host address from $param table;

I solve adding this line 
$host = $param['address'];
after line 129 .

------------------------------
         $param = Toolbox::parseMailServerConnectString($method['connect_string'], true);
         $host = $param['address'];     ### Added line
         if ($param['ssl'] === true) {
------------------------------

Bye

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by kfcito84** [comment]
Hola Disculpa, 

tengo este error cuando cuando intento autentificar el receptor
![image](https://user-images.githubusercontent.com/50878654/58107972-940f4500-7bb0-11e9-8870-56f70452a3e5.png)

**Comment by trasher** [comment]
@kfcito84 in english.
