### ISSUE TITLE
Administration of reservations

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#5929]
If i allow reservation for software item, i got this error
![image](https://user-images.githubusercontent.com/12936722/58031317-71355000-7b20-11e9-9478-6501be604268.png)
Bug not present in 9.3

i can't put item in the dustbin or change comment with massive actions. Actions are presents but nothing was done

**Comment by trasher** [comment]
I've just tried on current 9.4/bugfixes branch, and I'm not able to reproduce. Also make sure this is not a plugin related issue.

**Comment by cconard96** [comment]
I was able to get that errorb on latest 9.4 if you have the inventory number column visible. Software doesn't have that field.

I was able to update comments from the massive action, but not delete. No php error was logged.

**Comment by yllen** [comment]
I confirm that this error appears when inventory number column is displayed
