### ISSUE TITLE
sort column in queud mail

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#593]
Hello

in Queued mail, when I click on a column the list dissapear.

glpi master 04.04.2016

**Comment by orthagh** [comment]
You should have a sql error.
Please retrieve it in file/_logs/sql-errors.log

**Comment by satyan01** [comment]
2016-03-03 17:32:35 [@UNGSRVGVA118]
  *** MySQL query error:
  SQL: UPDATE `glpi_users`
                       SET `lock_directunlock_notification` = NULL WHERE `id` =\'2\'
  Error: Column 'lock_directunlock_notification' cannot be null
  Backtrace :
  inc\commondbtm.class.php:357                       
  inc\commondbtm.class.php:1116                      CommonDBTM->updateInDB()
  inc\auth.class.php:756                             CommonDBTM->update()
  front\login.php:78                                 Auth->Login()

**Comment by tomolimo** [comment]
Hello,
Did you do a migration, or was it from scratch?
Thank you,
Tomolimo

**Comment by tomolimo** [comment]
**BUT** the error is from 03-03-2016, don't you have nothing else more recent???

**Comment by satyan01** [comment]
no

**Comment by tomolimo** [comment]
Then this is not linked with the error message!

**Comment by satyan01** [comment]
so I don't have log in mysql

**Comment by tomolimo** [comment]
could be in the php-error logs?

**Comment by tomolimo** [comment]
So you may have javascript errors, could you check with javascript debug on?
(to do so, press F12 in your browser, and activate javasript debug)

**Comment by satyan01** [comment]
I have just that

2016-04-13 10:24:21 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: language
  Backtrace :
  inc\toolbox.class.php:592                          
  inc\plugin.class.php:200                           Toolbox::userErrorHandlerDebug()
  inc\session.class.php:592                          Plugin::loadLang()
  install\update.php:875                             Session::loadLanguage()

**Comment by tomolimo** [comment]
Yes, but this is in the php error log, but could you start javascript debug on the browser?

**Comment by satyan01** [comment]
I don't know how to do it, I don't see how to do that even with google search

**Comment by tomolimo** [comment]
Chrome: CTRL+SHIFT+J

**Comment by satyan01** [comment]
nothing happened

**Comment by satyan01** [comment]
IT misses "is deleted" when I click on sort in the request

**Comment by tomolimo** [comment]
Could you post screen copies?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14523097/1bf9a772-0232-11e6-8b6e-3e8bfe5d504b.png)

**Comment by orthagh** [comment]
so duplicate of #589

**Comment by orthagh** [comment]
#589 closed
fixed by 2f14730

**Comment by satyan01** [comment]
After updating with your modification I have still the issue

**Comment by yllen** [comment]
@orthagh 
On dustbin of an item, if you click on column title to sort item, you go out of dutsbin

**Comment by orthagh** [comment]
It should be better

**Comment by satyan01** [comment]
Thank you very much
