### ISSUE TITLE
Time duration minute intervals on projects stop at 8 hours

### ISSUE THREAD

**Issue by gmourani** [glpi-project/glpi#5936]
Hello,

When assigning a time duration for a task, more than 8 hours, it's not possible to chose 5 minutes or more (ex. 8:15) interval. All listed hours become 1 hour interval.
<img width="421" alt="Screen Shot 2019-05-21 at 9 19 56 AM" src="https://user-images.githubusercontent.com/20328799/58099499-c36e8380-7ba9-11e9-94fc-3a9035083968.png">

GLPI: 9.2.3
PHP: 5.6.33
Apache: 2.2.34
Linux: CentOS 6.9

Regards,

**Comment by trasher** [comment]
As far as I know, this is the expected behavior. 
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
