### ISSUE TITLE
Upload document and IE11

### ISSUE THREAD

**Issue by DrKak** [glpi-project/glpi#594]
Hello,

I follow this problem:
https://github.com/glpi-project/glpi/issues/329

I disabled DisableNTLMPreAuth and I reboot the computer, same problem. (unauthorized files but works with Chrome)

I need to change something else? htaccess ?

I'm desperate :( 

Thans for help !!

**Comment by tomolimo** [comment]
Hello,
Could you give your config? (GLPI, Web server,...)
Thank you
Tomolimo

**Comment by DrKak** [comment]
GLPI 0.90.3 (same on 0.90.1)
XAMPP for Windows 7.0.0 on Windows Server 2008 R2
PHP 7.0
Apache/2.4.18

Thanks :)

**Comment by tomolimo** [comment]
Which authentication scheme are you using?

**Comment by DrKak** [comment]
I have this:
  
AuthName "Accès restreint"
  AuthType SSPI
  SSPIAuth On
  SSPIAuthoritative On
  SSPIOfferBasic On
  SSPIPerRequestAuth On
  require valid-user

**Comment by tomolimo** [comment]
then check this: https://github.com/glpi-project/glpi/issues/329#issuecomment-173199131

**Comment by DrKak** [comment]
If I put this on .htaccess

<Files ~ "^$|index.php|login.php">
    AuthName "Accès restreint"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    NTLMOfferBasic Off
    NTLMPerRequestAuth On
    require valid-user
</Files>

I've got an error 500.

**Comment by tomolimo** [comment]
Look into log files in Apache and in GLPI

**Comment by tomolimo** [comment]
Did you do this exactly?

> &lt;Files ~ "^$|index.php|login.php">
    AuthName "Accès restreint"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    NTLMOfferBasic Off
    NTLMPerRequestAuth On
    require valid-user
&lt;/Files>

in

> /glpi/.htaccess

**Comment by DrKak** [comment]
Ok I solved the problem (missing LoadModule ntlm_module modules/mod_ntlm.so')

But I have already the same problem with upload.

I disabled with registry and I reboot 

In my glpi/htaccess:
<Files ~ "^$|index.php|login.php">
    AuthName "Accès restreint"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    NTLMOfferBasic Off
    NTLMPerRequestAuth On
    require valid-user
</Files>

In front/htaccess:
<Files login.php>
AuthName "Accès restreint"
AuthType SSPI
NTLMAuth On
NTLMAuthoritative On
NTLMOfferBasic Off
NTLMPerRequestAuth On
require valid-user
</Files>

I think I forget a thing.

**Comment by tomolimo** [comment]
Did you do this exactly?

> &lt;Files ~ "^$|index.php|login.php">
    AuthName "Accès restreint"
    AuthType SSPI
    NTLMAuth On
    NTLMAuthoritative On
    NTLMOfferBasic Off
    NTLMPerRequestAuth On
    require valid-user
&lt;/Files>

in

> /glpi/.htaccess

**Comment by DrKak** [comment]
Yes, I dont know why but the upload fail or succes randomly.

**Comment by tomolimo** [comment]
Did you set the &lt;Files.. just once?
and not on the complete folder tree?
To be sure: could you post your Apache config?

**Comment by DrKak** [comment]
The httpd.conf ?

**Comment by tomolimo** [comment]
Yes

**Comment by DrKak** [comment]
I resumed this project on my enterprise, so I dont know everything, i'm sorry !
[httpd.txt](https://github.com/glpi-project/glpi/files/218575/httpd.txt)

**Comment by tomolimo** [comment]
1. You are loading two modules for NTLM: I don't think they are compatibles: `mod_authnz_sspi` and  `mod_authn_ntlm`
1. Please use the latest modules from here: [Apache Haus](https://www.apachehaus.com/cgi-bin/download.plx)

**Comment by DrKak** [comment]
Ok I commented mod_authnz_sspi and I use only mod_authn_ntlm (the latest version).

I make a test (W7 x64 IE11) with the same file:
First upload: unauthorized files
Second upload: unauthorized files
Third upload: success

This is random :(

**Comment by tomolimo** [comment]
ok, then you may get a network traffic trace with fiddler and post it.
thank you

**Comment by orthagh** [comment]
No answers since days, I close.
Feel free to reopen this issue if you need precisions
