### ISSUE TITLE
Erreur lors de la recherche de tickets / Requête

### ISSUE THREAD

**Issue by thgallet** [glpi-project/glpi#5941]
GLPI Version 9.4.0

Lorsque le critère "Caractéristiques - statut" est le premier élément de la requête, ce critère n'est pas pris en compte dans la recherche. 

![image](https://user-images.githubusercontent.com/38798217/58164274-cb035a80-7c85-11e9-88c5-2ee18bf56c1d.png)

Si l'on inverse les critères, cela fonctionne.
![image](https://user-images.githubusercontent.com/38798217/58164332-ebcbb000-7c85-11e9-8015-5ac425b28d0f.png)

**Comment by trasher** [comment]
Requesed informations are not provided. Issue is not in english.
