### ISSUE TITLE
Time to own & Time to resolve does not display

### ISSUE THREAD

**Issue by ykasdi** [glpi-project/glpi#5957]
Hello,
I created a service level with SLAs Time to own and Time to resolve, I create rules for these SLAs, when I create a ticket the rules are applied well but the Time to own and Time to resolve is not displayed.
![26-05-2019 17-11-59](https://user-images.githubusercontent.com/23259888/58385020-03829b80-7fda-11e9-84a2-8b6fbb32540d.png)
![26-05-2019 17-04-24](https://user-images.githubusercontent.com/23259888/58385021-03829b80-7fda-11e9-9740-83bdf3f7a8cb.png)

thank you for helping me

**Comment by ykasdi** [comment]
any idea please?

**Comment by cedric-anne** [comment]
Hi,

Could you please tell us which version of GLPI you use, which plugins are active, and what is your server configuration ?

Could you try to reproduce with [nightly build](https://forge.glpi-project.org/tarballs/) and without any active plugin ?

Regards

**Comment by ykasdi** [comment]
Hello, 
thank you, he probléme is solved, the problem in the calendar, was not configured correctly.
