### ISSUE TITLE
Post Only Ticket: No access to associated element

### ISSUE THREAD

**Issue by cdlabal** [glpi-project/glpi#596]
Hello,
With post-only profil, creating a ticket, there is no access to "associated element".
![glpi - associated element](https://cloud.githubusercontent.com/assets/14885971/14522990/9524cbf0-0231-11e6-9fe6-283f268887b5.jpg)

However, in section "Association" of profil, all is setup:
- Link with items for the creation of tickets = My device and All items
- Associable items to a ticket = Comuters, Monitors, Printers, Devices, Phones
![glpi - postonlysetup](https://cloud.githubusercontent.com/assets/14885971/14523032/c48445d8-0231-11e6-8d90-7d75008b30d1.jpg)

GLPI 0.90.3 - MySql  5.5.46-0 -  Apache 2.4.10 - Debian 8u1

**Comment by cdlabal** [comment]
I've found what right is necessary in the profil to access to "associated element": Update
![glpi - postonlysetup](https://cloud.githubusercontent.com/assets/14885971/14525159/797f1c56-023c-11e6-8ca3-749f7f6a3b4b.jpg)

In GLPI 0.84, it is not neccessary to have this right. Is it possible to correct this?

**Comment by yllen** [comment]
http://forum.glpi-project.org/viewtopic.php?id=153052
