### ISSUE TITLE
hide identity of the technician

### ISSUE THREAD

**Issue by Txime** [glpi-project/glpi#5970]
HI
Here we have an old problem: in our current help-desk, a user can see who has solved an ticket. And as soon as the users have a new problem, they ignore the ticket creation and just make a phone call directly to that technician, because they realize "who is the one that solves problems".

I would like the name of the technician not to appear in the follow-ups and ticket information for self-service users.
![image](https://user-images.githubusercontent.com/51116521/58471013-372d0500-8143-11e9-9452-4fdf1dc1c087.png)
![image](https://user-images.githubusercontent.com/51116521/58471054-4a3fd500-8143-11e9-91bb-c2b6fa8512fa.png)
![image](https://user-images.githubusercontent.com/51116521/58471093-65aae000-8143-11e9-8c61-bb0aa9432b60.png)
Is there a possibility to eliminate the red parts for creation for self-service users?
GLPI 9.4.0
ubuntu0.18.04
Thanks

**Comment by tuxxic** [comment]
Hi Txime,

In my organisation, we decided to use pseudonyms (like Support 43) to avoid having our names written.
People see only that code.

But I am interested in any solution you may find to avoid having this, and an option to hide the identity.

**Comment by cedric-anne** [comment]
This feature has been added in #7015 and will be available in next GLPI major version.
