### ISSUE TITLE
[9.5 Bugfixes] problem with CSS

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#5975]
[GIT 9.5 updated]

9.5
![image](https://user-images.githubusercontent.com/13178158/58558956-59498480-8222-11e9-9f18-58323a569a4b.png)

9.4
![image](https://user-images.githubusercontent.com/13178158/58558978-649cb000-8222-11e9-8a9e-a381385563c0.png)

due to :
![image](https://user-images.githubusercontent.com/13178158/58559049-885ff600-8222-11e9-8ca8-20772a2a58b0.png)

Uncheck font-family in console : all is ok

**Comment by cedric-anne** [comment]
Hi,

I do not see any difference on Chrome and Firefox. Which browser do you use ? Is it possible that zoom is not set to 100% on one of your browser session ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
