### ISSUE TITLE
Error in glpi/locales/ru_RU.po

### ISSUE THREAD

**Issue by wemian** [glpi-project/glpi#5979]
In the file glpi/locales/ru_RU.po translation error.
The term 9384 (msgstr "Состояние") should be stated as msgstr "Область"
Since in this context "State" is not "Status".
 
https://github.com/glpi-project/glpi/blob/9c96d6ff949ae591973459466719b1000d90945f/locales/ru_RU.po#L9384

**Comment by trasher** [comment]
Trannslations are done on transifex: https://www.transifex.com/glpi/GLPI/dashboard/
