### ISSUE TITLE
[9.4.2] Performance Issue

### ISSUE THREAD

**Issue by CCoruble** [glpi-project/glpi#5984]
**Describe the bug**

Performance issues, 100% CPU usage, for exemple on first time a user login or when a user changes his color palette.

_I had more performance issues in 9.4.1 but a lot got fixed with 9.4.2 update._

For the moment, in 9.4.2, this are the only pages I found having performance issues but there might be more.

**Page(s) URL**

Login page, preference page

**To reproduce**

Install GLPI 9.4.2
Try to connect

**Expected behavior**

Lower CPU usage.

**Screenshots**

![performance_issue](https://user-images.githubusercontent.com/24699373/58856615-714a5980-86a3-11e9-926f-8304c7ac3bf1.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]
 
GLPI 9.4.2 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux TEST_glpi 4.4.0-139-generic #165-Ubuntu SMP Wed Oct 24 10:58:50 UTC 2018 x86_64
PHP 7.0.33-0ubuntu0.16.04.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="1024M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at XXXXX Port 443)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0
Server Software: (Ubuntu)
	Server Version: 5.7.26-0ubuntu0.16.04.1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (5.7.26) - Perfect!Database version seems correct (5.7.26) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

Libraries

 
htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

LDAP directories
 
Server: 'XXXXX'

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (XXXXX)

Mails receivers


Plugins list

 
	addressing           Name: Adressage IP                   Version: 2.8.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.1      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled

[/code] 
```

**Additional context**

I checked SQL queries, with debug mode, when changing color palette but nothing seems to be blocking / wrong.

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by CCoruble** [comment]
I tried with the fix.
Login & color palette still has the same behavior.
Also, loading the login page for the first time increase CPU load (90%-100%).

I heard that fusion inventory caused a lot of performance issues in last versions, I know it's supposed to be fixed but ... could it be the source of the problem ?

**Forgot to mention:** I have redmine on the same machine, but we never had problem before.

Let me know if you need more information.

**Comment by trasher** [comment]
Well, using the same server for several big applications may not be a good idea. Both redmine and GLPI can take a lot of resources.
But this will also depends on your real usage, number of suers connected, etc.

Plugins can have bugs themselves that would slow down GLPI entirely. You should try without any installed plugins and see how fast/slow it works (also, try with up to date nightly, some work has been done since your last try).

For the palettes/highcontrast issues, a bug has been fixed recently for the 9.5 branch as far as I remember, but it cannot be applied on the 9.4.

**Comment by CCoruble** [comment]
Hello,

I tried without any plugins and latestnightly 9.4 fix. I still have performance issues upon connecting and disconnecting.

Since it only affect login (connection/disconnection) could it come from LDAP connection ?

_There is maximum 5 simultaneous users on redmine, glpi is about 30 simultaneous. So far we never suffered performance issues even with redmine & glpi in the same machine._

**Comment by trasher** [comment]
> Since it only affect login (connection/disconnection) could it come from LDAP connection ?

That's possible
