### ISSUE TITLE
Post Only Ticket validation: right issue

### ISSUE THREAD

**Issue by cdlabal** [glpi-project/glpi#599]
A user with no right to change ticket can change the approvals status.
**Rights:**
![profil - tickets](https://cloud.githubusercontent.com/assets/14885971/14530840/0e368f3c-025b-11e6-9f9e-26d37e3a92c4.jpg)
User have to be able to send a approval request and to validate:
![profil - validation](https://cloud.githubusercontent.com/assets/14885971/14530846/12fa7722-025b-11e6-8c30-dc92090e48f2.jpg)

**Issue:**
![validation right issue](https://cloud.githubusercontent.com/assets/14885971/14530852/1c8253fa-025b-11e6-9290-84b3ccf1cbf6.jpg)
![validation right issue 2](https://cloud.githubusercontent.com/assets/14885971/14531236/c6c4970a-025c-11e6-9379-49c3b5b0cbaf.jpg)

**Comment by yllen** [comment]
Cycle of validation is different of cycle of ticket.
With your picture, user change the status of the validation, not the status of the ticket

**Comment by cdlabal** [comment]
The problem is that user who no have right to change ticket can change the global approbal status in the header of a ticket that is pending or close.
Users should be able to send appoval request and validate à approval request ticket, but not to manualy change the global approbal status of tickets.
This works fine in GLPI 0.84.

**Comment by yllen** [comment]
In 0.90 you have the dropdown for global validation status but you don't have the button to validate the change in the ticket.
Like in 0.84 or 0.85 for validation you must do your actions in Validation tab

**Comment by cdlabal** [comment]
You're rigth.there is no "save" option to validate the change.
But it strange that only global approbal status is in edit mode.
So, Ok for me.
