### ISSUE TITLE
Add some constants for default profiles, users, ...

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#5992]
```
Could we set some constants to identify
    profiles id (ex PROF_SUPERADMIN_ID, PROF_OBSERVER_ID, etc)
    users id (USER_GLPI_ID, USER_TECH_ID, etc)
    Rights values (READ, UPDATE, etc)
```
See https://github.com/glpi-project/glpi/pull/5947#pullrequestreview-246394813

**Comment by Terux101** [comment]
<font></font>
{<font></font>
    "query": {<font></font>
        "country_iso": "DE",<font></font>
        "nid": "37040044",<font></font>
        "account": "3901190310"<font></font>
    },<font></font>
    "success": true,<font></font>
    "account_valid": false,<font></font>
    "nid_valid": true,<font></font>
    "records_found": "17",<font></font>
    "records_displayed": 1,<font></font>
    "directory_results": [<font></font>
        {<font></font>
            "office_type": "DB",<font></font>
            "legal_type": "B",<font></font>
            "institution_status": "BANK",<font></font>
            "iso_lei_code": "",<font></font>
            "bic8": "COBADEFF",<font></font>
            "branch_bic": "366",<font></font>
            "bic": "COBADEFF366",<font></font>
            "chips_uid": "",<font></font>
            "national_id": "37040044",<font></font>
            "connected_bic": "COBADEFF366",<font></font>
            "institution_name": "COMMERZBANK AG",<font></font>
            "branch_information": "Commerzbank Pulheim",<font></font>
            "pob_number": "",<font></font>
            "street_address_1": "KAISERSTRASSE 16",<font></font>
            "street_address_2": "",<font></font>
            "street_address_3": "",<font></font>
            "street_address_4": "",<font></font>
            "city": "FRANKFURT AM MAIN",<font></font>
            "cps": "HESSE",<font></font>
            "zip_code": "60261",<font></font>
            "country_name": "GERMANY",<font></font>
            "iso_country_code": "DE",<font></font>
            "subtype_indicator": "SUPE",<font></font>
            "network_connectivity": "CNN",<font></font>
            "service_codes": "EBAERPFINTG+"<font></font>
        }<font></font>
    ],<font></font>
    "error": {<font></font>
        "code": "813",<font></font>
        "message": "Invalid Account Check Digit"<font></font>
    }<font></font>
}<font></font>
<font></font>
