### ISSUE TITLE
Work for WCAG and RGAA

### ISSUE THREAD

**Issue by flegastelois** [glpi-project/glpi#5996]
Related resources:
- [WC3 International Guidelines](https://www.w3.org/WAI/standards-guidelines/wcag/) [EN]
- [French Certified Translation](https://www.w3.org/Translations/WCAG20-fr/) [FR]
- [Accessiweb HTML5 / ARIA reference](http://www.accessiweb.org/index.php/accessiweb-html5aria-liste-deployee.html) [FR]
- [Resources from DINSIC (a French Interministerial initiative)](https://github.com/DISIC) [FR]
- [French RGAA](https://disic.github.io/rgaa_referentiel/index.html) [FR]

**Comment by terastar8** [comment]
Thanks

**Comment by cconard96** [comment]
As a note, I believe GLPI needs to meet the standards set by the EU Accessibility Act of 2025 by June 2030.

This would mean at least WCAG 2.1 AA level.
