### ISSUE TITLE
contract date notification is wrong

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#6004]
![image](https://user-images.githubusercontent.com/32479943/59107381-c783fa80-8938-11e9-924d-4588883d52f7.png)

It is adding the contract renewal period (+1 Year)
Calculation why we recieved the notification on the wrong date:
```
Begin date (27.09.2018)
+periodicity (12 month)
- contract notice (3 month)
- notify before; set by entity (21 days)
= 06.06.2019
```
This is wrong. The contract runs for 36 month (06.06.2021 would be the right date) before it can't be cancelled. 

It seems that the initial contract period is not in the calculation which send wrong notification dates.

See contract.class.php Line:1371 ("duration" is missing in that calculation?)

Version 9.4.2 stock - but this affects all previous versions.

**Comment by Eon9D** [comment]
Any updates?

**Comment by Eon9D** [comment]
@trasher I know this is "rude" to link a person directly even when he is not involved it the ticket and I am sorry about this. But this seems to me a major flaw as contacts are from financial relevance and the current "version" leads to a wrong interpretation of how the date is calculated and to wrong notifications.
Can you say something about this?

**Comment by Eon9D** [comment]
@orthagh Can you say something about this?

**Comment by cedric-anne** [comment]
Hi @Eon9D ,

Can you check if #6077 fixes your problem ?

Regards

**Comment by Eon9D** [comment]
Hey! Thank you very(!) much for addressing this issue and taking care of it!
I did a very quick test yesterday evening but something was not working in my test system(couldn't test the patch). I will do a test this evening and definitely let you know!

Thanks again.

**Comment by Eon9D** [comment]
Okay. Seems to work. Did some test and couldn't see any problems except something which probably is unrelated to this.

![image](https://user-images.githubusercontent.com/32479943/60459563-ce551300-9c41-11e9-9304-0f6dae803dfe.png)

System time was set to 22.12.19.
Would have expected one -21 days (as set in the entity) but even after the contract already ended there is no notification.
This is for example for service contracts (no auto renewal - on time pay you have to renew yourself).
Is there something wrong in the screenshot? If not I would make a new ticket.

Thank you for fixing this issue!

**Comment by cedric-anne** [comment]
Hi,

I do not know well this part, and I do not really have time to investigate right now.
As initial bug seems to be fixed, this issue will be closed on PR merging. So you should open another ticket for this new problem.

Regards

**Comment by orthagh** [comment]
And for information, if you need support with commitment, please take a look at https://services.glpi-network.com/
