### ISSUE TITLE
Follow ups dissapeared or are not being saved

### ISSUE THREAD

**Issue by oscargomez87** [glpi-project/glpi#6005]
**Describe the bug**

Just updated from 9.3 to 9.4.2, suddenly followups disappeard and now when i add a folloup it banishes. this is what appears when i press the followup buton in a ticket

**To reproduce**

go to any ticket and into procesing ticket and try adding a followup

**Expected behavior**

A new follow up appears in the ticket

**Logs**

[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: items_id
  Backtrace :
  inc/itilfollowup.class.php:884
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6823
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6832
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6832
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6832
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6832
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6832
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}
[2019-06-10 18:05:23] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/glpi.lan.cdo-sa.com/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/ticket.class.php:6832
  inc/itilfollowup.class.php:884                     Ticket::getSplittedSubmitButtonHtml()
  inc/itilfollowup.class.php:815                     ITILFollowup->showFormButtons()
  ajax/timeline.php:116                              ITILFollowup->showForm()
  {"user":"231@glpi","mem_usage":"0.000\", 4.09Mio)"}

**Screenshots**

![image](https://user-images.githubusercontent.com/45802292/59232443-0076d600-8baa-11e9-8ad2-8ab04e24bb35.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Information about system installation & configuration
--
[code]   GLPI 9.4.2 (/glpi => /home/www/glpi.lan.cdo-sa.com/glpi) Installation mode: TARBALL

Operating system: Linux glpi 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 PHP 7.1.8 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, 	pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="16M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: nginx/1.14.0 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.3.10-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.3.10) - Perfect! /home/www/glpi.lan.cdo-sa.com/glpi/files/_log : OK /home/www/glpi.lan.cdo-sa.com/glpi/config : OK /home/www/glpi.lan.cdo-sa.com/glpi/files : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_dumps : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_sessions : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_cron : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_graphs : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_lock : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_plugins : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_tmp : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_cache : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_rss : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_uploads : OK /home/www/glpi.lan.cdo-sa.com/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Enforcing SELinux boolean configuration for httpd_can_network_connect --> on SELinux boolean configuration for httpd_can_network_connect_db --> on SELinux boolean configuration for httpd_can_sendmail --> on

htmLawed version 1.2.4 in (/home/www/glpi.lan.cdo-sa.com/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/elvanto/litemoji/src) symfony/console in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/symfony/console) leafo/scssphp in (/home/www/glpi.lan.cdo-sa.com/glpi/vendor/leafo/scssphp/src)

Server: '', Port: '', BaseDN: 'dc=,dc=com', Connection filter: none, RootDN: 		'uid=,cn=,cn=', Use TLS: none

Not active

Way of sending emails: SMTP+TLS ()

Name: '' Active: Yes 	Server: '{}' Login: 'soporte' Password: Yes

behaviors            Name: Behaviours                     Version: 2.1.1      State: Not activated 	dashboard            Name: Dashboard                      Version: 0.9.7      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Not activated 	mod                  Name: GLPI Modifications             Version: 1.3.2      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.0      State: Enabled 	genericobject        Name: Objects management             Version: 2.6.2      State: Not activated 	order                Name: Orders management              Version: 2.5.0      State: Enabled 	pdf                  Name: Print to pdf                   Version: 1.4.0      State: Not activated 	reports              Name: Reports                        Version: 1.13.1     State: Enabled
[/code]


```

**Comment by cedric-anne** [comment]
Hi,

Can you check in your database if `glpi_itilfollowups` table contains a `items_id` column ?
If this column is missing, it means that something wrong happens during migration. You may have to restore your database backup and retry update procedure as described [here](https://glpi-install.readthedocs.io/en/latest/update.html).

Regards

**Comment by oscargomez87** [comment]
Hello, this is the result of db:check

Table schema differs for table "glpi_rulecriterias".
--- Original
+++ New
@@ @@
 create table `glpi_rulecriterias` (
   `id` int(11) not null auto_increment
   `rules_id` int(11) not null default '0'
   `criteria` varchar(255) default null
   `condition` int(11) not null default '0'
-  `pattern` text default null
+  `pattern` text
   primary key (`id`)

Table schema differs for table "glpi_slms".
--- Original
+++ New
@@ @@
 create table `glpi_slms` (
   `id` int(11) not null auto_increment
   `name` varchar(255) default null
   `entities_id` int(11) not null default '0'
   `is_recursive` tinyint(1) not null default '0'
+  `calendars_id` int(11) not null default '0'
   `comment` text
-  `calendars_id` int(11) not null default '0'
   `date_mod` datetime default null
   `date_creation` datetime default null
   primary key (`id`)

Table schema differs for table "glpi_slas".
--- Original
+++ New
@@ @@
   `number_time` int(11) not null
-  `calendars_id` int(11) not null default '0'
   `date_mod` datetime default null
   `definition_time` varchar(255) default null
   `end_of_working_day` tinyint(1) not null default '0'
   `date_creation` datetime default null
   `slms_id` int(11) not null default '0'
   primary key (`id`)

Table schema differs for table "glpi_softwarelicenses".
--- Original
+++ New
@@ @@
   `date_creation` datetime default null
-  `is_deleted` tinyint(1) not null default '0'
+  `is_template` tinyint(1) not null default '0'
+  `template_name` varchar(255) default null
@@ @@
   `is_helpdesk_visible` tinyint(1) not null default '0'
-  `is_template` tinyint(1) not null default '0'
-  `template_name` varchar(255) default null
+  `is_deleted` tinyint(1) not null default '0'
+  `manufacturers_id` int(11) not null default '0'
   `states_id` int(11) not null default '0'
-  `manufacturers_id` int(11) not null default '0'
   `contact` varchar(255) default null
   `contact_num` varchar(255) default null
   primary key (`id`)

Table schema differs for table "glpi_itilsolutions".
--- Original
+++ New
@@ @@
 create table `glpi_itilsolutions` (
   `id` int(11) not null auto_increment
   `itemtype` varchar(100) not null
   `items_id` int(11) not null default '0'
   `solutiontypes_id` int(11) not null default '0'
-  `solutiontype_name` varchar(255) null default null
+  `solutiontype_name` varchar(255) default null
   `content` longtext
   `date_creation` datetime default null
   `date_mod` datetime default null
   `date_approval` datetime default null
   `users_id` int(11) not null default '0'
-  `user_name` varchar(255) null default null
+  `user_name` varchar(255) default null
   `users_id_editor` int(11) not null default '0'
   `users_id_approval` int(11) not null default '0'
-  `user_name_approval` varchar(255) null default null
+  `user_name_approval` varchar(255) default null
   `status` int(11) not null default '1'
-  `itilfollowups_id` int(11) default null
+  `itilfollowups_id` int(11) default null
   primary key (`id`)

Table schema differs for table "glpi_tickets".
--- Original
+++ New
@@ @@
   `global_validation` int(11) not null default '1'
+  `slas_id_tto` int(11) not null default '0'
   `slas_id_ttr` int(11) not null default '0'
-  `slas_id_tto` int(11) not null default '0'
   `slalevels_id_ttr` int(11) not null default '0'
   `time_to_resolve` datetime default null
   `time_to_own` datetime default null
   `begin_waiting_date` datetime default null
   `sla_waiting_duration` int(11) not null default '0'
   `ola_waiting_duration` int(11) not null default '0'
   `olas_id_tto` int(11) not null default '0'
   `olas_id_ttr` int(11) not null default '0'
   `olalevels_id_ttr` int(11) not null default '0'
   `internal_time_to_resolve` datetime default null
   `internal_time_to_own` datetime default null
   `waiting_duration` int(11) not null default '0'
   `close_delay_stat` int(11) not null default '0'
   `solve_delay_stat` int(11) not null default '0'
   `takeintoaccount_delay_stat` int(11) not null default '0'
   `actiontime` int(11) not null default '0'
   `is_deleted` tinyint(1) not null default '0'
   `locations_id` int(11) not null default '0'
   `validation_percent` int(11) not null default '0'
   `date_creation` datetime default null
   primary key (`id`)

Table schema differs for table "glpi_racks".
--- Original
+++ New
@@ @@
   `room_orientation` int(11) not null default '0'
-  `position` varchar(50)
+  `position` varchar(50) default null
   `bgcolor` varchar(7) default null
   `max_power` int(11) not null default '0'
   `mesured_power` int(11) not null default '0'
   `max_weight` int(11) not null default '0'
   `date_mod` datetime default null
   `date_creation` datetime default null
   primary key (`id`)

Table schema differs for table "glpi_items_racks".
--- Original
+++ New
@@ @@
   `position` int(11) not null
-  `orientation` tinyint(1)
+  `orientation` tinyint(1) default null
   `bgcolor` varchar(7) default null
   `hpos` tinyint(1) not null default '0'
   `is_reserved` tinyint(1) not null default '0'
   primary key (`id`)
   unique key `item` (`itemtype`,`items_id`,`is_reserved`)

Table schema differs for table "glpi_enclosures".
--- Original
+++ New
@@ @@
   `is_deleted` tinyint(1) not null default '0'
-  `orientation` tinyint(1)
+  `orientation` tinyint(1) default null
   `power_supplies` tinyint(1) not null default '0'
   `states_id` int(11) not null default '0'
   `comment` text
   `manufacturers_id` int(11) not null default '0'
   `date_mod` datetime default null
   `date_creation` datetime default null
   primary key (`id`)

Table schema differs for table "glpi_itilfollowups".
--- Original
+++ New
@@ @@
 create table `glpi_itilfollowups` (
   `id` int(11) not null auto_increment
   `itemtype` varchar(100) not null
-  `items_id` int(11) not null default '0'
+  `tickets_id` int(11) not null default '0'
   `date` datetime default null
   `users_id` int(11) not null default '0'
   `users_id_editor` int(11) not null default '0'
   `content` longtext
   `is_private` tinyint(1) not null default '0'
   `requesttypes_id` int(11) not null default '0'
   `date_mod` datetime default null
   `date_creation` datetime default null
   `timeline_position` tinyint(1) not null default '0'
   `sourceitems_id` int(11) not null default '0'
   `sourceof_items_id` int(11) not null default '0'
   primary key (`id`)

Sadly i restored and migrated again using console db:update before i could see you're answer so I couldn't check, right now I can see the followups again. tough im having another undefined index error from the fusioninventory plugin.

**Comment by cedric-anne** [comment]
OK, so maybe something wrong happened on first migration.

Now the error you have is related to fusioninventory plugin, so please check issues on plugin repository dorectly.
