### ISSUE TITLE
Issue updating GLPI

### ISSUE THREAD

**Issue by rvargasg** [glpi-project/glpi#6013]
Hello everyone.

I'm trying to update GLPI from 0.72.3 version but the process get stuck in the version 0.84.1 showing "Work in progress..." and never ends.

I've tried some ways to do this update:

- I launched the update from 9.3.3 packet version but, It fails
- I tried the same from older packets (0.84.1, 0.85...) but it get stuck in same step

In previous versions the page wizard is loading while do the update but in 0.84.1 id doesn't.

Could anyone help me? I have tried everything not get advance.

Thank you so much for your help.
![Captura_glpi](https://user-images.githubusercontent.com/39514484/59342708-90cc2c80-8d0a-11e9-8208-b98cdfc31695.PNG)

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
