### ISSUE TITLE
[9.4.2] Error of display message in mass actions

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#6018]
From glpi users list : 

Mass action : Dissociate from profil : 

![image](https://user-images.githubusercontent.com/13178158/59356084-6f7a3900-8d28-11e9-9ccf-7612859fa80b.png)

**Comment by cedric-anne** [comment]
Hi,

List if OK on my side. Have you enabled plugins ? Can you test without any plugin ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
