### ISSUE TITLE
Show validation for closed ticket

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#602]
post for 0.85.5 but still exist in 0.90 http://forum.glpi-project.org/viewtopic.php?id=153115

The request to validation is
     ```
 $query = "SELECT *
                FROM `".$this->getTable()."`
                WHERE `".static::$items_id."` = '".$item->getField('id')."'";
      if (!$canadd) {
         $query .= " AND `users_id_validate` = '".Session::getLoginUserID()."'";
      }
```
But for a closed ticket you can't add new validation.
So you only can see validation that you are the validator.

For me, if i can see the ticket, i can see also all the validation tab.
Your opinion?

**Comment by tomolimo** [comment]
ok for me!

**Comment by remicollet** [comment]
it also seems to make sense to me.
