### ISSUE TITLE
Some redirections lends to a 404 page

### ISSUE THREAD

**Issue by allanvianna** [glpi-project/glpi#6027]
Hi,
Can you help me? 
When I try to log in after session gets timeout I get 404 error. 
I can notice that the redirect URL after I log in is wrong, as you can see in the print screen.
It should be domain/ti/front/ticket.php but the sistem redirect to domain/ti/fontcket.php 

How can I fix it?

![Err404](https://user-images.githubusercontent.com/28231919/59463327-1e3b7980-8dfc-11e9-98c4-49660213b90d.png)

**Comment by cedric-anne** [comment]
Hi,

First, next time you open an issue, thanks to provide informations requested in issue form (see https://github.com/glpi-project/glpi/issues/new?template=bug_report.md ).

Second, could you try the fix #6028 ?

Regards

**Comment by allanvianna** [comment]
Hi, there!

Sorry about not provided informations as requested in issue form. 

The solution [#6028](https://github.com/glpi-project/glpi/pull/6028), worked perfectly!

Thank you

Regards!
