### ISSUE TITLE
Searching on Firstname + Lastname doesnt work when selecting a user.

### ISSUE THREAD

**Issue by wimaerts** [glpi-project/glpi#603]
Changing display settings to show first name + last name was implemented a long time ago, but searching that way still doesn't work when selecting a user in a ticket. This can be fixed rather quickly by changing inc/user.class.php

			     OR CONCAT(`glpi_users`.`firstname`,' ',`glpi_users`.`realname`) ".
                                       Search::makeTextSearch($search)."
                             OR CONCAT(`glpi_users`.`realname`,' ',`glpi_users`.`firstname`) ".
                                       Search::makeTextSearch($search).")";

**Comment by orthagh** [comment]
Hello @wimaerts.

I can't find the "Firstname + Lastname" sentence.
Could you precise your issue (ans the line number of your fix) ?

Also, please, precise the concerned glpi version

**Comment by wimaerts** [comment]
0.90.3
inc/user.class.php
line number 3119 (or search for concat in user.class.php)

Thanks for looking in to this!

**Comment by wimaerts** [comment]
The issue = adding a person to a ticket, i can type in "aerts wim" to select myself, but i can't type in "wim aerts" without the fix.

**Comment by orthagh** [comment]
is 
```php
OR CONCAT(`glpi_users`.`firstname`,' ',`glpi_users`.`realname`,' ',`glpi_users`.`firstname`) ".
                                   Search::makeTextSearch($search)."
```
still works in your case.

I have troubles to replicate the issue (not to understand it) ?

**Comment by wimaerts** [comment]
Yes, that also works for me!

**Comment by orthagh** [comment]
Thank you for your contribution
