### ISSUE TITLE
After execution of SavedSearch_Alert::cronSavedSearchesAlerts, cron session is not restored

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#6037]
**Description**

During execution of SavedSearch_Alert::cronSavedSearchesAlerts, default cron session is not restored. And as a session is created per user to be able to get the correct search results, then this user session is passed to next cron...
Also, the logs are in the user session timezone / language, and not in the GLPI default timezone / language.

**Logs**
in cron.log
```
2019-06-13 22:25:25 [@ARGLPP301]
External #3: Launch planningrecall
2019-06-13 22:25:25 [@ARGLPP301]
External #4: Launch queuednotification
2019-06-13 22:25:26 [@ARGLPP301]
External #5: Launch savedsearchesalerts
2019-06-13 22:25:26 [937@ARGLPP301]
External #6: Launch pmtaskactions
```

user 937 was not really logged in at 22:25:26,  but only the cron was running..

I'm going to provide a fix for this.

Thank you
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
Fixed by #6039 .
