### ISSUE TITLE
Use composer for libraries

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#604]

**Comment by orthagh** [comment]
See also adc52ab

Some minor issues anyway :
* vcardclass seems very old and i can't find it on packagist (maybe we must do a rewrite)
* kwi/urllinker has no release
* glpi autoloader have some exceptions, do we need to keep them ? https://github.com/glpi-project/glpi/blob/5a24c95e9cd716d4be18e47760da5da1d82f30cd/inc/autoload.function.php#L292-L304

**Comment by orthagh** [comment]
Fusioninventory uses Zendframework/Loader previously packaged with glpi.
On this branch, if fusion is present in plugin folder, it triggers an error 500.
See : https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/lib/autoload.php#L3-L5
I re-imported that lib temporarily.

So, I think glpi doesn't use anymore this dependency and fusion plugin need to provide itself.

@ddurieux, @remicollet your opinions ?

**Comment by remicollet** [comment]
I think it would be better to fix FusionInventory to either 
- bundles zend-classloader in its lib
- configure (GLPI) composer autoloader to add needed class
- also switch to composer

BTW, probably make sense to keep it (temporarily) in GLPI.

**Comment by ddurieux** [comment]
It is used to autoload .view files. Perhaps see if we can do it with another method

**Comment by orthagh** [comment]
We have some local patches in lib folder, here is a list : 
* simplepie : https://github.com/glpi-project/glpi/commit/c99425394d9df913a62d315488db777dd5b29ed8
-> can be fixed by the 1.4.1 version of simplepie who permit to add curl options (see https://github.com/simplepie/simplepie/blob/1.4.1/library/SimplePie.php#L828 & https://github.com/simplepie/simplepie/pull/407)

* Htmlawed : https://github.com/glpi-project/glpi/commit/6cfd777a4f4280867159e9ffdf3813abeeb1265c#diff-1f10b22c0e9b8a11c475ab35c0f9ba3fR103
-> this one is bad imo (my fault), all Html::clean must be reviewed and cleaned

* tinymce is strongly patched, and i think we must review this lib usage (and update version also), it include review of paste image feature

**Comment by orthagh** [comment]
htmlawed & tinymce fixes in progress in #723

**Comment by orthagh** [comment]
branch merged
