### ISSUE TITLE
[9.4] Display error on material rules engine

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#6040]
On criterias

![image](https://user-images.githubusercontent.com/13178158/59616584-024e1580-9125-11e9-9170-fe2400ab38d0.png)

And actions :

![image](https://user-images.githubusercontent.com/13178158/59616631-1c87f380-9125-11e9-9f31-878695af567a.png)

**Comment by cedric-anne** [comment]
Hi,

Can you explain the problem you encounter and what you expect ?

Regards

**Comment by tsmr** [comment]
The dropdowns sholoud list users with their names & firstname  : 

Todo : 

into inc/ruleasset.class.php replace each

$actions['users_id_..']['type']       = 'dropdown'; by $actions['users_id_...']['type']       = 'dropdown_users';

**Comment by cedric-anne** [comment]
@tsmr 

Could you open a PR for this ?

Regards
