### ISSUE TITLE
Added a custom notification template - nothing sent

### ISSUE THREAD

**Issue by sazanof** [glpi-project/glpi#6044]
When I add a custom new Email notification template on Close Ticket event (for ex.), when ticket closed, default notification (Ticket) sent, but my template not sent

1. Settings - Notifications - Notifications Templates
2. Click on Add new template plus. TITLE: Satisfaction, BODY: Здравствуйте. Приглашаем принять участие в небольшом опросе на Вашу заявку (##ticket.title##)
http://....../........html?tid=##ticket.id##&mode=glpi
3. GO to Settings - Notifications - Notifications
4. Add new Notification
5. title - Ticket Satisfaction Send, Active - YES, Type - Ticket, Event - Close Ticket (ticket solved)

the notification template is associated with the notification itself, but when i add a solution or close a ticket - comes only one default notification (called Ticket)

Please, if its not a bug, explain

GLPI 9.4.2 Copyright (C) 2015-2019 Teclib' and contributors
FusionInventory 9.4.0+1.0 - Copyleft © 2010-2019 by FusionInventory Team
Operating system: Linux webserver 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64
PHP 7.2.19-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="1500" memory_limit="256M" post_max_size="10M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at glpi.mosgortur.ru Port 80)
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 YaBrowser/19.6.0.1574 Yowser/2.5 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.26-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

Error log is empty

**Comment by DrizztFR** [comment]
Hello sazanof,

Did you try after setting "Active = No" to the default notification ?

**Comment by sazanof** [comment]
@DrizztFR, no, I did not disable the default notification, as there is a need for both notifications to work, as they have different recipients
