### ISSUE TITLE
PHP Fatal error to load Plugin on plugin.class.php file

### ISSUE THREAD

**Issue by rodrigocantarino** [glpi-project/glpi#6047]
**Describe the bug**

When I try to install a plugin a PHP Fatal error is occurring.
After some code investigation, I found out that is a problem on plugin.class.php file.
When the class Plugin() try to load the plugin on its folder it is doing twice.
The first time it loads correctly calling __/myplugin__.
But on the second time it is calling __/Myplugin__.
Note that the first time the call is made with the first letter of the plugin name in lowercase, but on the second time, the call is made with the first letter in uppercase.

**Page(s) URL**

http://myglpi.com/front/plugin.php

**To reproduce**

1. Go to 'Setup->Plugins'
2. Click on 'Install'
3. See error on php_error.log

**Expected behavior**

Just install the Plugin.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
Default GLPI 9.4.2
```

**PHP Fatal error**

PHP Fatal error:  Cannot redeclare plugin_myplugin_check_config() 
(previously declared in /my_glpi_path/plugins/myplugin/setup.php:130) in /my_glpi_path/glpi/plugins/Myplugin/setup.php on line 130

**Suggestion to bug fix**

- Go to file: **/glpi/inc/plugin.class.php**

  **Plugin::load() - line 161 (GLPI 9.4.2)**
  ```php
    static function load($name, $withhook = false) {
      global $LOADED_PLUGINS;
      $name = strtolower($name); //-> Add this line
      ...
    } 
  ```

  **Plugin::loadLang() - line 193 (GLPI 9.4.2)**
  ```php
    static function loadLang($name, $forcelang = '', $coretrytoload = '') {
        // $LANG needed : used when include lang file
        global $CFG_GLPI, $LANG, $TRANSLATE;
        $name = strtolower($name); //-> Add this line
        ...
    } 
  ```

  **Plugin::doHook() - line 1105 and 1124 (GLPI 9.4.2)**
  ```php
    static function doHook ($name, $param = null) {
        ...
        if (isset($PLUGIN_HOOKS[$name]) && is_array($PLUGIN_HOOKS[$name])) {
                foreach ($PLUGIN_HOOKS[$name] as $plug => $tab) {
                   $plug = strtolower($plug); //-> Add this line
                   ...
        } else { // Standard hook call
            if (isset($PLUGIN_HOOKS[$name]) && is_array($PLUGIN_HOOKS[$name])) {
               foreach ($PLUGIN_HOOKS[$name] as $plug => $function) {
                  $plug = strtolower($plug); //-> Add this line
                  ...
    }
  ``` 

  **Plugin::doHookFunction() - line 1158 (GLPI 9.4.2)**
  ```php
    static function doHookFunction($name, $parm = null) {
      global $PLUGIN_HOOKS;

      $ret = $parm;
      if (isset($PLUGIN_HOOKS[$name]) && is_array($PLUGIN_HOOKS[$name])) {
         foreach ($PLUGIN_HOOKS[$name] as $plug => $function) {
            $plug = strtolower($plug); //-> Add this line
            ...
    } 
  ```

**Comment by cedric-anne** [comment]
Hi,

Which plugin is affected by this bug ? I cannot reproduce on plugins I use.

Regards
