### ISSUE TITLE
Total duration not shown after ticket was created

### ISSUE THREAD

**Issue by cmiscloni** [glpi-project/glpi#6049]
- When you create a ticket, the total duration time field exist in the template but after creation  the field disapearing.
- It is still possible to show the value with adding the field in the default global view.
- We had tried to change the template used for the ticket but problem still exist

- GLPI Version : 9.4.3

**Comment by SergeyTovstonog** [comment]
v10.0.7 - the issue still persists. 
I need the option to set the total duration manually by tech.
The workaround is to create a task in the ticket and set its duration.
Another way is to set it by API.
But both are not too convenient when working with UI.
It is definitely in the template and seen in the preview, could be added as a column to the list of tickets? but not visible in ticket's standard interface.
So, please reopen.
