### ISSUE TITLE
GLPi 0.90.3: HTTP Error 404.0 - Not Found

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#605]
Hello,
To reproduce this error:

1. Open a new session on GLPi 0.90.3 (new installation from scratch)
1. go to notification templates
1. Open the notification template called 'Tickets' (ID=4)
1. Go to Template translation
1. Click on 'Default translation'
1. Then click on the 'List' link upper left which normally goes back in the notification template 
![image](https://cloud.githubusercontent.com/assets/7569958/14603696/869c47f2-056f-11e6-9de6-5b955dc7ee9d.png)
And you'll get the HTTP 404

Thank you

**Comment by orthagh** [comment]
Hello @tomolimo 

I reproduce the issue only when i got the page url (http://.../front/notificationtemplatetranslation.form.php?id=4&notificationtemplates_id=4) just after login.

When i follow your steps and pass by the related notification, the id of this notification is stored in session so i have the right link : 
![image](https://cloud.githubusercontent.com/assets/418844/14675387/12880522-0709-11e6-815b-8cb9a52bb9bb.png)

So, in normal usage, i think you can't have this error, no ?

**Comment by tomolimo** [comment]
Were you in debug mode?

**Comment by orthagh** [comment]
yes

**Comment by tomolimo** [comment]
Could you retry in normal mode?

**Comment by orthagh** [comment]
Same behavior.

For your search, this link is generated by Session::addToNavigateListItems function
For notificationtemplatetranslation, it's initialized here : 
https://github.com/glpi-project/glpi/blob/0.90/bugfixes/inc/notificationtemplatetranslation.class.php#L216

and used by showNavigationHeader function (called by display function in front)
https://github.com/glpi-project/glpi/blob/0.90/bugfixes/inc/commonglpi.class.php#L771-L777

**Comment by tomolimo** [comment]
Thank I'll check that, and keep you informed

**Comment by tomolimo** [comment]
I can't reproduce this any longer, so I close it
