### ISSUE TITLE
glpi 9.4.2 , technician cannot edit solution once saved using pencil icon (Uncaught ReferenceError: viewEditSubitem is not defined)

### ISSUE THREAD

**Issue by ElioJarma** [glpi-project/glpi#6053]
**Describe the bug**

when a technician try to modify a solution saved that he just made,
(clicking on pencil) nothing happens, in follow section works fine
but in solution not,
when I try to debug this with chrome console I get the following error:
Uncaught ReferenceError: viewEditSubitem151281398738937 is not defined
    at HTMLSpanElement.onclick (ticket.form.php?id=15128&forcetab=Ticket$2:1)
onclick @ ticket.form.php?id=15128&forcetab=Ticket$2:1

tried also with superadmin profile but I get the same result

**Page(s) URL**

http://helpdesk/front/ticket.form.php?id=15128

If applicable, page(s) URL where the bug happens.

http://helpdesk/front/ticket.form.php?id=15128&forcetab=Ticket$2

**To reproduce**

login as a technician/superadmin
select & open a created ticket to interact/resolve with
go to "solution"  put whatever you want
Save
try to edit with pencil

**Expected behavior**
a text box displayed to modify the text written in solution box

**Screenshots**

![image](https://user-images.githubusercontent.com/52041412/59856264-f2b11580-934c-11e9-951c-fc7d98f5672a.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Información sobre la instalación y configuración del sistema
--
[code]   GLPI 9.4.2 ( => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux svrmtx040 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 PHP 7.2.19-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="512M" post_max_size="20M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at helpdesk Port 80) 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.26-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (5.7.26) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

 

genericobject        Name: Administración de Objetos      Version: 2.5.2      State: To be cleaned 	consumables          Name: Consumable request             Version: 1.3.1      State: To be cleaned 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled 	reports              Name: Informes                       Version: 1.11.3     State: To be cleaned 	mydashboard          Name: My Dashboard                   Version: 1.5.2      State: To be cleaned
[/code]

![printglpi](https://user-images.githubusercontent.com/52041412/59856423-43c10980-934d-11e9-9c0f-f9d091652b1f.png)

**Comment by cedric-anne** [comment]
Hi,

Can you check if #6078 solves your problem ?

Regards

**Comment by ElioJarma** [comment]
It works  now!, thank you very much

![print](https://user-images.githubusercontent.com/52041412/60289095-054ac200-98ec-11e9-97a8-622ddc867ab0.png)

**Comment by cedric-anne** [comment]
Will be closed on PR merge.
