### ISSUE TITLE
Migration class : table alteration sequences may fail

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#6057]
Hi

In some case the migration class may behave unexpectedly.

The following sequence:
- dropField($table, 'foo');
- changeField($table, 'bar', 'foo');

The sequence will fail because changeField will check for existence of **foo** before registering the data. At this time, the column **foo** is not yet deleted, then the change request will be ignored.

I think that the check should occur in the migrationOneTable method, and the alter table should (probably, need a check in DBMS doc) be split into several alter table queries.

To make the sequence succeed, I need to call migrationOneTable() before the changeField() call.

**Comment by trasher** [comment]
As far as I remember, you must call the `migrationOneTable` beetween the instructions; this looks like an enhancement more than an bug

**Comment by btry** [comment]
This is indeed the workaround I used. However most use cases of this class makes that the developer does need to bother about basic checks (existence of a column). This is why I think this use cas should be handleded as I described.

Not a bug as this is workaroundable ;)
