### ISSUE TITLE
Space character not always working

### ISSUE THREAD

**Issue by msizec** [glpi-project/glpi#6063]
Its a weird issue
Found using chrome 75 on 2 different computers.
I didn't managed to reproduce but it happended a few times during last week

whjen writing in a description or followup textarea, sometimes the space character won't respond, and you find yourself with something like 'thisismytextwithoutspaces'

And we found that, when the probleme occurs, pressing a second time spacebar lead to display a space character

glpi 9.4.2 (freshly updated from 9.3.?)

**Comment by cedric-anne** [comment]
Hi,

Duplicates #5786 

Regards
