### ISSUE TITLE
Add locations fields to search

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#6065]
**Is your feature request related to a problem? Please describe.**

In the list of locations it is not possible to filter by address, zip code and city fields.

**Describe the solution you'd like**

I have added the fields to the function to be able to select them in the search

**Additional context**
![image](https://user-images.githubusercontent.com/39123808/60087855-10f88600-973e-11e9-97c6-7b163343de48.png)

**Comment by orthagh** [comment]
Hello @xacobofg 

Do you have some code to share for the need ?

- if yes, i encourage you to open a pull request on this project to facilitate the integration.
- if not, please use the [suggestion](suggest.glpi-project.org) website. It permits on our side to classify and prioritize feature by popularity.

Regards.

**Comment by orthagh** [comment]
it seems the above line answers me, thank you
