### ISSUE TITLE
satisfaction survey is received by the creator not the requester

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#607]
Hello

Is it possible to fix it please ?

Thank you

**Comment by orthagh** [comment]
Yes.

But it's a configuration you've done you need to fix.
In the default notification for Ticket Satisfaction, it's the requester and not the writer who is recipient, see :
![image](https://cloud.githubusercontent.com/assets/418844/14675801/f5ef97ca-070a-11e6-9346-a60bb93d67ae.png)

**Comment by satyan01** [comment]
It is already the case

**Comment by orthagh** [comment]
Oh, I'm going to check.

**Comment by orthagh** [comment]
Ok i confirm the bug

**Comment by orthagh** [comment]
finally no (i have trouble to identify email adresses).

To fully check your report, could you : 
- enable debug mode in your preferences
- create a test ticket with 2 different users in writer and requester (with different mail)
- in this ticket, go to debug tab on post a screenshot of it here.

Thank you

**Comment by satyan01** [comment]
Hello

Which content of debug tab do you want ?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14701853/b69a33bc-07a7-11e6-9b7c-5d49d1eb2394.png)

**Comment by orthagh** [comment]
Not this debug :)

Display the ticket after his creation, you'll have a debug tab for it

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14703031/f2e8fffa-07ad-11e6-8253-66389ba8df77.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14703050/10816b88-07ae-11e6-8d61-ff855ddb03ef.png)

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14703100/4ae67642-07ae-11e6-8c5c-3574e4bc90ee.png)

I have approved the solution of the ticket and The satisfaction survey has been sent to me

**Comment by orthagh** [comment]
Could you post also the Ticket tab ?

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14703190/e989bdd6-07ae-11e6-9300-163e9813959d.png)

**Comment by orthagh** [comment]
And did Florian Cotting receive also this notification ?

An extract of last entries of your .../glpi/files/mail.log could help also

**Comment by satyan01** [comment]
he has received it the notification, I don't have ./glpi/files/mail.log

**Comment by orthagh** [comment]
You could enable logging of sent mails by go in  Setup > General, system tab, param "Logs in files (SQL, email, automatic action...)"

**Comment by satyan01** [comment]
2016-04-21 11:12:33 [@UNGSRVGVA118]
  *** MySQL query error:
  SQL: UPDATE `glpi_users`
                       SET `lock_directunlock_notification` = NULL WHERE `id` =\'636\'
  Error: Column 'lock_directunlock_notification' cannot be null
  Backtrace :
  inc\commondbtm.class.php:357                       
  inc\commondbtm.class.php:1116                      CommonDBTM->updateInDB()
  inc\auth.class.php:756                             CommonDBTM->update()
  front\login.php:78                                 Auth->Login()

**Comment by satyan01** [comment]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:13:05 [636@UNGSRVGVA118]

**Comment by satyan01** [comment]
2016-04-21 11:13:39 [636@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: simcorpbaadminrightsfield
  Backtrace :
  plugins\fields\inc\field.class.php:737             
  plugins\fields\inc\field.class.php:424             PluginFieldsField::prepareHtmlFields()
  plugins\fields\inc\container.class.php:526         PluginFieldsField::showForTabContainer()
  inc\commonglpi.class.php:469                       PluginFieldsContainer::displayTabContentForItem()
  ajax\common.tabs.php:94                            CommonGLPI::displayStandardTab()

**Comment by satyan01** [comment]
2016-04-21 11:15:30 [@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: glpiactiveprofile
  Backtrace :
  inc\item_ticket.class.php:372                      
  inc\commonglpi.class.php:208                       Item_Ticket->getTabNameForItem()
  inc\ticket.class.php:663                           CommonGLPI->addStandardTab()
  inc\commonglpi.class.php:158                       Ticket->defineTabs()
  ajax\updatecurrenttab.php:48                       CommonGLPI->defineAllTabs()

**Comment by satyan01** [comment]
2016-04-21 11:15:00 [896@UNGSRVGVA118]
  *** PHP Notice(8): Undefined offset: 5200
  Backtrace :
  inc\search.class.php:2756                          
  inc\search.class.php:465                           Search::addWhere()
  inc\search.class.php:97                            Search::constructSQL()
  inc\search.class.php:81                            Search::showList()
  front\ticket.php:56                                Search::show()

**Comment by satyan01** [comment]
I don't know if these errors are useful for you

**Comment by orthagh** [comment]
not really, 
I 'd like to get an extract mail.log for a full cycle of a creation ticket.

Could you redo the steps i provide you here : https://github.com/glpi-project/glpi/issues/607#issuecomment-212787420
And extract **all** events in mail.log for this new ticket.

**Comment by satyan01** [comment]
2016-04-21 11:12:34 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:12:34 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:12:34 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:12:34 [854@UNGSRVGVA118]
Un email a été envoyé à fcotting@unigestion.com : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:13:04 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:13:05 [636@UNGSRVGVA118]
An email to tleavitt@unigestion.com was added to queue: [GLPI #2015041608] Ticket number  :  2015041608
2016-04-21 11:13:06 [636@UNGSRVGVA118]
An email to fsaddiki@unigestion.com was added to queue: [GLPI #2015041608] Ticket number  :  2015041608
2016-04-21 11:13:20 [539@UNGSRVGVA118]
An email to dfourgous@unigestion.com was added to queue: [GLPI #2016041903] Ticket number  :  2016041903
2016-04-21 11:13:24 [854@UNGSRVGVA118]
Un email a été envoyé à fcotting@unigestion.com : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:13:47 [636@UNGSRVGVA118]
An email was sent to fsaddiki@unigestion.com: [GLPI #2015041608] Ticket number  :  2015041608
2016-04-21 11:13:47 [636@UNGSRVGVA118]
An email was sent to tleavitt@unigestion.com: [GLPI #2015041608] Ticket number  :  2015041608
2016-04-21 11:13:47 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:13:48 [539@UNGSRVGVA118]
An email was sent to dfourgous@unigestion.com: [GLPI #2016041903] Ticket number  :  2016041903
2016-04-21 11:13:48 [539@UNGSRVGVA118]
An email to dfourgous@unigestion.com was added to queue: [GLPI #2016041903] Ticket number  :  2016041903
2016-04-21 11:13:58 [854@UNGSRVGVA118]
Un email a été envoyé à fcotting@unigestion.com : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:14:20 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:14:21 [854@UNGSRVGVA118]
Un email a été envoyé à fcotting@unigestion.com : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:14:23 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Ticket number  :  2016042108
2016-04-21 11:14:23 [854@UNGSRVGVA118]
Un courriel pour fcotting@unigestion.com a été ajouté à la file d'attente : [GLPI #2016042108] Satisfaction survey test2
2016-04-21 11:14:23 [854@UNGSRVGVA118]
Un email a été envoyé à fcotting@unigestion.com : [GLPI #2016042108] Satisfaction survey test2

**Comment by satyan01** [comment]
for other errors, Do I need to open issue ?

**Comment by orthagh** [comment]
Yes, if you want

for this one, in your last tests, did your receive yourself a mail name "[GLPI #2016042108] Satisfaction survey test2" ? Because your mail logs do not show it

**Comment by satyan01** [comment]
No I did not received it

**Comment by orthagh** [comment]
That was your issue
