### ISSUE TITLE
Fix Dropdown::show when using html input array

### ISSUE THREAD

**Issue by loicbenoit** [glpi-project/glpi#6079]
**Describe the bug**
Using html input array with Drodown::show breaks the javascript (and halts javascript for the entire page, which, in turn, breaks all dropdowns and menus).

**To reproduce**
1. Call Dropdown::show with an attribute name like: states_id[]
2. It produces html like: `<span class="fa fa-plus-circle pointer" title="Ajouter" onclick="$('#add_dropdownstates_id[]1080628746').dialog('open');">`

The "#add_dropdownstates_id[]1080628746" generates a javascript error that breaks JS on the entire page.

**Expected behavior**
Dropdown:show should be able to handle hmtl input arrays, without it breaking anything.

**Additional context**
Bug fix proposition is to replace "$params['name']" with "$field_id" in 2 places in method Dropdown::show (See pull request)

**Comment by cedric-anne** [comment]
Closed by #6082
