### ISSUE TITLE
assigned to display mail instead of name

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#608]
Hello

This morning I have a bug, two tickets are assigned to mail adress instead of name of the technician

glpi master 04.04.2016. 

![image](https://cloud.githubusercontent.com/assets/15144026/14630505/5bb26aa4-060e-11e6-9dc4-2b480c13ef8b.png)

**Comment by orthagh** [comment]
Hi @satyan01 

Could you provide a procedure to replicate your issue ?

**Comment by satyan01** [comment]
Hello

Unfortunately it is not happened again

**Comment by orthagh** [comment]
Ok. Feel free to reopen if that problem triggers again
