### ISSUE TITLE
Cannot transfer objects between child entities, Glpi 9.4.2 and 9.4.3

### ISSUE THREAD

**Issue by laszlokertesz** [glpi-project/glpi#6080]
It seems that there is an issue with transferring objects between entities. 
In this case i wanted to transfer a computer to a child entity of the default root entity.
Note that this computer has documents and problems attached. Tried to enable child entities on these but it still fails.

I saw that there is a similar issue that was marked solved, but i see this error on our 9.4.2 and 9.4.3 stable glpi versions so it is very much a persistent issue.

This is the error that pops up in debug mode:

`Fatal error: Uncaught RuntimeException: Empty IN are not allowed in /var/www/html/glpi/inc/dbmysqliterator.class.php:546 Stack trace: #0 /var/www/html/glpi/inc/dbmysqliterator.class.php(516): DBmysqlIterator->analyzeCriterion(Array) #1 /var/www/html/glpi/inc/dbmysqliterator.class.php(506): DBmysqlIterator->analyseCrit(Array) #2 /var/www/html/glpi/inc/dbmysqliterator.class.php(288): DBmysqlIterator->analyseCrit(Array) #3 /var/www/html/glpi/inc/dbmysqliterator.class.php(94): DBmysqlIterator->buildQuery('`glpi_contracts...', Array, false) #4 /var/www/html/glpi/inc/dbmysql.class.php(580): DBmysqlIterator->execute(Array, '', false) #5 /var/www/html/glpi/inc/transfer.class.php(2781): DBmysql->request(Array) #6 /var/www/html/glpi/inc/transfer.class.php(2719): Transfer->transferSingleSupplier('2') #7 /var/www/html/glpi/inc/transfer.class.php(1077): Transfer->transferInfocoms('Computer', '811', '811') #8 /var/www/html/glpi/inc/transfer.class.php(203): Transfer->transferItem('Computer', '811', '811') #9 /var/www/html/glpi/front/tra in /var/www/html/glpi/inc/dbmysqliterator.class.php on line 546`

**Comment by AHinMaine** [comment]
Seeing this as well.

The thing I noticed is that I can transfer my objects that do _not_ have a Supplier associated with them.  If it has a related Supplier, I get the same error you posted above.

I see in your error you have a Supplier as well.  Try transferring an object that doesn't have one and see if that works for you as well.

I posted in the forum as well.  https://forum.glpi-project.org/viewtopic.php?id=171584

**Comment by AHinMaine** [comment]
I think I figured it out.  Go into your Supplier (id '2' in your case) and change the Sub-entities value from No to Yes.

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/6243

**Comment by Aditbunta** [comment]
Hi, please help me.

I'm currently update GLPI version from 9.1 to 9.4 step by step.
All the process already done, and there is no issues.
but then when I want to move entity of the asset it does not change to new entity, although status operation is successful. There is no error in the log, but it seems nothing has changes after I do "add to transfer list" action. Can someone help me about this case?


Thank You.
