### ISSUE TITLE
Problems with task in 9.4

### ISSUE THREAD

**Issue by Favid1** [glpi-project/glpi#6081]
**Describe the bug**

Hello ,
after using the proposed solution #5455 for the error #5411 , it works correctly, but in the records of php-errors.log they give me different notices each time I create the task, ¿Solutions?
Thank you
GLPI 9.4

[2019-06-28 10:35:48] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
*** PHP Notice(8): Undefined variable: default_date
Backtrace :
inc/planning.class.php:621
inc/planning.class.php:2111 Planning::showPlanning()
inc/central.class.php:232 Planning::showCentral()
inc/central.class.php:82 Central::showMyView()
inc/commonglpi.class.php:485 Central::displayTabContentForItem()
ajax/common.tabs.php:92 CommonGLPI::displayStandardTab()
{"user":"129@essansc1"}
[2019-06-28 10:35:54] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
*** PHP Notice(8): Undefined variable: default_date
Backtrace :
inc/planning.class.php:621
inc/planning.class.php:144 Planning::showPlanning()
inc/commonglpi.class.php:485 Planning::displayTabContentForItem()
ajax/common.tabs.php:92 CommonGLPI::displayStandardTab()
{"user":"129@essansc1"}

----------------------------------------------------------------------------------------------------------

[code]   GLPI 9.4.0 (/glpi => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux essansc1 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 PHP 7.2.19-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at helpdesk Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.26-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpidb@localhost/glpidb 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is not present Database version seems correct (5.7.26) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-console in (/var/www/html/glpi/vendor/zendframework/zend-console/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Server: '10.136.65.1', Port: '389', BaseDN: 'dc=fagorindustrial,dc=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person))', RootDN: 'srvglpiadu@fagorindustrial.local', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@onneragroup-com.mail.protection.outlook.com)

Name: 'helpdesk@onneragroup.com' Active: Yes 	Server: '{outlook.office365.com:993/imap/ssl/novalidate-cert/notls}' Login: 'helpdesk@onneragroup.com' Password: Yes

behaviors            Name: Comportamientos                Version: 2.2.1      State: To be cleaned 	formcreator          Name: Form Creator                   Version: 2.8.2      State: Not activated 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled 	reports              Name: Informes                       Version: 1.13.0     State: To be cleaned 	mreporting           Name: Más Informes                   Version: 1.6.1      State: To be cleaned 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: To be cleaned 	dashboard            Name: Tablero de informes            Version: 0.9.7      State: To be cleaned
[/code]
@cedric-anne

**Comment by cedric-anne** [comment]
Hi,

You should upgrade to 9.4.3. Code related to this backtrace changed.

Regards
