### ISSUE TITLE
[9.4] Problem when Display the complete name in tree dropdowns is set to yes

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#6083]
**Describe the bug**

When you set the configuration " Display the complete name in tree dropdowns" to "yes" for both general configuration and profil settings,
A probleme occures when displaying the result of a search in ticket categories :
![image](https://user-images.githubusercontent.com/39367117/60420652-86ee6880-9be8-11e9-833b-97cf19adb88b.png)

**To reproduce**

1. Go to profil settings > Personalization
2. Change the setting "Display the complete name in tree dropdowns" to "yes"
3. Same in setup > General > Default values
4. Go create a ticket and search a child category.

**Expected behavior**

See the full name of category with ">" instead "&gl;"

Try with version GLPI 9.4.2 & 9.4.3

**Comment by cedric-anne** [comment]
Hi @keha35 ,

#6094 should fix this.

Regards

**Comment by keha35** [comment]
Hi,

Thanks for the fix.
It works for me.

I'm closing the issue.
