### ISSUE TITLE
Mail from external user

### ISSUE THREAD

**Issue by bliwako** [glpi-project/glpi#6087]
When tech receives external mail directly - he drag&drop mail into mailbox of GLPI.

GLPI pulls mail but in ticket it shows requester is tech - it should show external mail.
Latest version.

**Comment by cedric-anne** [comment]
Hi,

Please provide all requested informations.

Also, can you tell us if the `mailgate` automatic action was launched by the cron service (run mode: CLI), or via GLPI UI (run mode: GLPI), or manually ?

Regards

**Comment by bliwako** [comment]
Sorry for very long reply. I forgot.

I made a a video to show issue.

![final](https://user-images.githubusercontent.com/52458879/61187490-f9902700-a671-11e9-92d3-87c1fcf25819.gif)

OK?

**Comment by bliwako** [comment]
In addition. When external person reply to technician. The "Last edited by" of the ticket is not updated.

**Comment by cedric-anne** [comment]
> Sorry for very long reply. I forgot.
> 
> I made a a video to show issue.
> 
> ![final](https://user-images.githubusercontent.com/52458879/61187490-f9902700-a671-11e9-92d3-87c1fcf25819.gif)
> 
> OK?

Hi,

Bad identity of requester has been solved by https://github.com/glpi-project/glpi/pull/6038 in 9.4.3

Regards
