### ISSUE TITLE
Tickte Statistics wrong

### ISSUE THREAD

**Issue by MarcSN311** [glpi-project/glpi#6095]
The line:
https://github.com/glpi-project/glpi/blob/6b638592c8cab1b53e939974fba032e1afad2194/inc/stat.class.php#L1114
breaks the calculation for the Total Duration if some tickets have a duration of zero. 

We hat a Total Duration of 589 hours while it was actually 133 hours. Removing this line fixes the issue.

**Comment by cedric-anne** [comment]
Hi,

Please provide a full context, and all other requested informations.

Regards
