### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined method Config::getCache() in /var/www/html/glpi/inc/config.php:45 Stack trace: #0 /var/www/html/glpi/inc/includes.php(48): include_once() #1 /var/www/html/glpi/index.php(71): include('/var/www/html/g...') #2 {main} thrown in /var/www/html/glpi/inc/config.php on line 45

### ISSUE THREAD

**Issue by RiCkEquinoxe** [glpi-project/glpi#6099]
Hi everyone, I'm having problems, the virtual server gave me a problem and I got the hyper-v backup of the GLPI server. When I started the system, I gave HTTP ERROR 500, after debugging the error, gave the message:

Fatal error: Uncaught Error: Call to undefined method Config :: getCache () in /var/www/html/glpi/inc/config.php:45 Stack trace: # 0 / var / www / html / glpi / inc / includes .php (48): include_once () # 1 /var/www/html/glpi/index.php(71): include ('/ var / www / html / g ...') # 2 {main} thrown in /var/www/html/glpi/inc/config.php on line 45

I checked the includes.php file line 48:
include_once (GLPI_ROOT. "/inc/config.php");

I checked the line 45 config.php:
$ GLPI_CACHE = Config :: getCache ('cache_db');

I do not know how to solve this problem, could anyone help me? I have a lot of information on this system

**Comment by cedric-anne** [comment]
Hi,

As you did not provide requested informations, it is hard for us to know how to investigate.
We do not even know which version of GLPI you use, and how it has been installed.

Regards

**Comment by RiCkEquinoxe** [comment]
Hi, sorry for the flaw.
I am using the Linux distribution Debian 9.9 with GLPI 9.4.2 with PHP 7.0, apache2, database Mariadb v. 10.

**Comment by cedric-anne** [comment]
How did you install GLPI ?

**Comment by RiCkEquinoxe** [comment]
I created a virtual machine with Debian 9.9, downloaded the newest GLPI from the site and installed all the add-ons. The system was integrated with Active Directory, was already sending e-mails, all right. The installation was performed without errors.

**Comment by cedric-anne** [comment]
Hi

If all was working and just stops after an operation on virtual server, then problem is not on application side.
You can ask for support on [community forum](https://forum.glpi-project.org) or get [professionnal support](https://glpi-project.org/subscriptions/).

I close this issue as we only track GLPI bugs on this repository.

Regards
