### ISSUE TITLE
Interface tweak suggestion

### ISSUE THREAD

**Issue by stdonato** [glpi-project/glpi#61]
Add some color to table headers and enlarge the width of central table: 

![glpi_-_interface_padrao_-_2015-08-13_10 42 11](https://cloud.githubusercontent.com/assets/7674445/9252875/bb62f7fa-41a8-11e5-9eb2-a873c769f803.png)

![glpi_-_chamados_-_2015-08-13_10 41 56](https://cloud.githubusercontent.com/assets/7674445/9252871/b370ba14-41a8-11e5-839f-b30275155c02.png)

**Comment by orthagh** [comment]
Hello Stevenes.

The absence of colors in main part of glpi is intended.
To facilitate integration with all palettes, keep simple theses, and have a clear design.

But If you want, you can add a new palette (copy of a builtin) who add the header color in table.

I close this issue, you can reopen it if you want.
Oh, and in a few days, we will open a new space for suggest features and enhancement (with votes).

Regards.

**Comment by stdonato** [comment]
I understand. Thanks.

Best Regards,

Stevenes

2015-08-14 3:12 GMT-04:00 Alexandre Delaunay <notifications@github.com>:
