### ISSUE TITLE
tag appears in ticket description after saving <p> </p> 

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#610]
Hello

After ticket creation tag appears in ticket description after saving <p> </p> 

glpi 0.91 04.04.2016

**Comment by orthagh** [comment]
Could you attach a screenshot of your issue ?

**Comment by satyan01** [comment]
![tag error glpi](https://cloud.githubusercontent.com/assets/15144026/14678080/9d4e87c0-0714-11e6-9f3b-a5883e77a633.png)

**Comment by orthagh** [comment]
Is this triggers after a manual creation of ticket / update existing, with a collect of an email ?

**Comment by satyan01** [comment]
manual creation

**Comment by orthagh** [comment]
I fail to replicate your issue. :(

Could you test upgrade your version since you are already on dev version (master) to last commit  and check again ?

so, please describe if you do some special actions when you create your ticket

**Comment by satyan01** [comment]
it is master version of 04.04.2016

**Comment by satyan01** [comment]
I use it in production, I know it is not advised, but it works perfectly

**Comment by satyan01** [comment]
except few issues but not high

**Comment by orthagh** [comment]
no problem with that :)

could you pull to last version anyway ?

**Comment by satyan01** [comment]
not for the moment

**Comment by satyan01** [comment]
the issue is always present

**Comment by orthagh** [comment]
@satyan01 is this still valid with your last updates ?

**Comment by satyan01** [comment]
yes

**Comment by orthagh** [comment]
ok, we can consider this issue as solved so.

**Comment by satyan01** [comment]
ok
