### ISSUE TITLE
[9.4.2 - 9.4.3] Error in the notification queue 

### ISSUE THREAD

**Issue by usrqmor** [glpi-project/glpi#6101]
Hello,

I open an issue wich is [#5492](https://github.com/glpi-project/glpi/issues/5942)  for a notification queue problem.

I'm sorry to bother with this. You can find my system in the link above.
I try to send the mail from my test server but the problem persist and there is only this type of message in the log : 

> [2019-05-22 14:54:48] glpiphplog.ERROR: NotificationEventAjax::send() in /var/www/glpi/inc/notificationeventajax.class.php line 75

You will find in the attached file the log.
[php-errors.log](https://github.com/glpi-project/glpi/files/3362851/php-errors.log)

I check the cron to with the automatic action queuednotification but there's no error in the journal.
I try to launch it with  the --debug option but I didn't have any error too.

I try on the last GLPI version but it don't work too ... 

Thanks for your help.

**Comment by cedric-anne** [comment]
Hi,

Can you try to disable all plugins to see if error persists ?

Regards

**Comment by usrqmor** [comment]
Hi @cedric-anne,

Sorry for the late reply. I was away last week. I disabled all my plugin and retry to send the notification.
It doesn't work, the error persists.

Thanks

**Comment by usrqmor** [comment]
Hi,

I think I found what the problem. It's not a probelm in fact. I was searching some solutions or informations that can help me and I see that all of the notifications blocked in queue are browser notification, not mail notification.
I didn't check the mode of the notification.

I had some reply from my users that they didn't receive mail at a time and I associate this problem with the notification. 

I have a question for the mail notification in the queue. When the mail is send, did he go to the bin ? 
I didn't check this before so I see it today.

Thanks.
