### ISSUE TITLE
[9.4.3] Signal > between entities names is not working in ticket category: Filter

### ISSUE THREAD

**Issue by robsonjorgefernandez** [glpi-project/glpi#6102]
The signal **>** between entities name is not working when we do a search/filter in category box.
I think this bug is the same path from issue [5646](https://github.com/glpi-project/glpi/issues/5646).

No filter:
![nofilter](https://user-images.githubusercontent.com/16673533/60743503-4d9b5d00-9f48-11e9-9557-833511b8c386.png)

Filter:
![filter](https://user-images.githubusercontent.com/16673533/60743505-555b0180-9f48-11e9-8e5c-51e156af3d77.png)

<details><summary>Follow my GLPI setup</summary>
<pre>
{
    "glpi": {
        "uuid": "MRaizpbTXfhzZ2L5TTF3oGh69uCqutZNvF2NY6tR",
        "version": "9.4.3",
        "plugins": [
            {
                "key": "formcreator",
                "version": "2.8.3"
            },
            {
                "key": "fusioninventory",
                "version": "9.4+1.1"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "0-500",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "500-1000",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MariaDB Server",
            "version": "10.3.16-MariaDB-log",
            "size": "3193.6",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "Apache",
            "version": "2.4.34"
        },
        "php": {
            "version": "7.1.8",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqlnd",
                "PDO",
                "Phar",
                "posix",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sqlite3",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "xml",
                "xmlwriter",
                "xsl",
                "zip",
                "mysqli",
                "pdo_mysql",
                "pdo_sqlite",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "apcu",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "256M",
                "post_max_size": "20M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "5M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "Red Hat Enterprise Linux Server release 7.6 (Maipo)",
            "version": "3.10.0-957.21.2.el7.x86_64"
        }
    }
}
<pre>
</details>

**Comment by cedric-anne** [comment]
Hi @robsonjorgefernandez ,

Can you test #6109 ?

Regards

**Comment by robsonjorgefernandez** [comment]
Hi @cedric-anne,

I have applied this merge [#6109](https://github.com/glpi-project/glpi/pull/6109), but did not work.

![image](https://user-images.githubusercontent.com/16673533/60819079-4c9b4300-a175-11e9-873f-9562b7c8af97.png)

I cleaned the Chrome cache and tested it on Firefox as well. The results were the same.

![image](https://user-images.githubusercontent.com/16673533/60819219-971cbf80-a175-11e9-8832-baf1fb97c721.png)

I had not noticed, but some filters almost work:

![image](https://user-images.githubusercontent.com/16673533/60819745-83258d80-a176-11e9-98ec-d7f4283d5b00.png)

**Comment by cedric-anne** [comment]
Hi,

Maybe your browser loads minified files. Can you try in "debug" mode ?
![image](https://user-images.githubusercontent.com/33253653/60821171-4b810a80-a1a3-11e9-98e3-f56d17d782a0.png)


Regards

**Comment by robsonjorgefernandez** [comment]
Thats it!

Debug OFF:
![image](https://user-images.githubusercontent.com/16673533/60825517-3ba4fe80-a182-11e9-9834-ba351f10bc81.png)

Debug ON:
![image](https://user-images.githubusercontent.com/16673533/60825566-57100980-a182-11e9-8268-87ef089a5ddc.png)

Thank you!
