### ISSUE TITLE
Indentation in followup mail

### ISSUE THREAD

**Issue by Elitius** [glpi-project/glpi#613]
Hi,

We got an issue since 0.90.1 > 0.90.3 update.

In every followup mail we send/receive, we does'nt have any indentation in "description" block. All lines feed disapeared. But we still have them in GLPI tickets.

Thanks for your help.

**Comment by kabassanov** [comment]
HI, 

I have the same issue (I hope it is an issue)...

**Comment by yllen** [comment]
Remove not useful part because Html::clean is called at the beginning of GetDatasForObject, so HTML is already cleaned.
