### ISSUE TITLE
[9.4.3] Recurring tickets doesn't create tickets anymore

### ISSUE THREAD

**Issue by robsonjorgefernandez** [glpi-project/glpi#6140]
My recurring tickets stopped work and I believe this happened when I have updated the system from 9.4.2 to 9.4.3.

Recurring tickets
![01](https://user-images.githubusercontent.com/16673533/61229130-f93d6d80-a6fd-11e9-9b8e-c6c88779aeda.png)
![02](https://user-images.githubusercontent.com/16673533/61229166-0e1a0100-a6fe-11e9-9a35-d9738e410ef6.png)
![03](https://user-images.githubusercontent.com/16673533/61229173-0fe3c480-a6fe-11e9-8ca8-89cfad8de816.png)

Calendars
![04](https://user-images.githubusercontent.com/16673533/61229194-212cd100-a6fe-11e9-9b20-9e7a838a590b.png)

Automatic Actions
![05](https://user-images.githubusercontent.com/16673533/61229228-2f7aed00-a6fe-11e9-8646-1d9d5d45a1da.png)
![06](https://user-images.githubusercontent.com/16673533/61229244-36096480-a6fe-11e9-9ade-3dea3dcbe150.png)

Log
![07](https://user-images.githubusercontent.com/16673533/61229254-3bff4580-a6fe-11e9-80f6-1f3a9bf3b0e4.png)

I don't receive any error in my log.
How can I depurate this issue?

<details><summary>My system:</summary>
<p>

<pre>
{
    "glpi": {
        "uuid": "MRaizpbTXfhzZ2L5TTF3oGh69uCqutZNvF2NY6tR",
        "version": "9.4.3",
        "plugins": [
            {
                "key": "formcreator",
                "version": "2.8.3"
            },
            {
                "key": "fusioninventory",
                "version": "9.4+1.1"
            }
        ],
        "default_language": "pt_BR",
        "install_mode": "TARBALL",
        "usage": {
            "avg_entities": "0-500",
            "avg_computers": "0-500",
            "avg_networkequipments": "0-500",
            "avg_tickets": "10000-50000",
            "avg_problems": "0-500",
            "avg_changes": "0-500",
            "avg_projects": "0-500",
            "avg_users": "500-1000",
            "avg_groups": "0-500",
            "ldap_enabled": true,
            "mailcollector_enabled": false,
            "notifications_modes": [],
            "notifications": [
                "mailing",
                "ajax"
            ]
        }
    },
    "system": {
        "db": {
            "engine": "MariaDB Server",
            "version": "10.3.16-MariaDB-log",
            "size": "3179.9",
            "log_size": "",
            "sql_mode": ""
        },
        "web_server": {
            "engine": "Apache",
            "version": "2.4.34"
        },
        "php": {
            "version": "7.1.8",
            "modules": [
                "Core",
                "date",
                "libxml",
                "openssl",
                "pcre",
                "zlib",
                "filter",
                "hash",
                "Reflection",
                "SPL",
                "session",
                "standard",
                "apache2handler",
                "bz2",
                "calendar",
                "ctype",
                "curl",
                "dom",
                "mbstring",
                "fileinfo",
                "ftp",
                "gd",
                "gettext",
                "iconv",
                "intl",
                "json",
                "ldap",
                "exif",
                "mysqlnd",
                "PDO",
                "Phar",
                "posix",
                "shmop",
                "SimpleXML",
                "soap",
                "sockets",
                "sqlite3",
                "sysvmsg",
                "sysvsem",
                "sysvshm",
                "tokenizer",
                "xml",
                "xmlwriter",
                "xsl",
                "zip",
                "mysqli",
                "pdo_mysql",
                "pdo_sqlite",
                "wddx",
                "xmlreader",
                "xmlrpc",
                "apcu",
                "Zend OPcache"
            ],
            "setup": {
                "max_execution_time": "30",
                "memory_limit": "256M",
                "post_max_size": "20M",
                "safe_mode": false,
                "session": "files",
                "upload_max_filesize": "5M"
            }
        },
        "os": {
            "family": "Linux",
            "distribution": "Red Hat Enterprise Linux Server release 7.6 (Maipo)",
            "version": "3.10.0-957.21.2.el7.x86_64"
        }
    }
}
</pre>

**Comment by fgendorf** [comment]
same issue here
_________________________
Frederico Gendorf

**Comment by cedric-anne** [comment]
Hi,

Can you try to apply commit a04bb30b301756233825b504e09649c7f8425b31 and open and save the recurring ticket form ?
It should result in computation of next creation date (`next_creation_date` will be updated in DB).

Regards

**Comment by fgendorf** [comment]
It works, thank you

**Comment by robsonjorgefernandez** [comment]
It did work!
Thank you @cedric-anne !

**Comment by barbuslex** [comment]
Hi,
I have the same issue in my GLPI 9.4.3.
Have you a SQL query to fix NULL next_creation_date column ?
Thanks

**Comment by cedric-anne** [comment]
Hi @barbuslex ,

As computation is done on PHP side, the best option is to apply the patch and open/save form for affected recurring tickets.

Regards

**Comment by barbuslex** [comment]
@cedric-anne 
Thanks for your reply but it not fix the issue. The NULL column stay at NULL if the begin date is in the past.
I need to update the begin date to today to fix it... :S
There are no other way ?

**Comment by cedric-anne** [comment]
It works on my side even with a date in past. What was the value of you begin date ?

**Comment by barbuslex** [comment]
I have apply this fix : 
https://github.com/cedric-anne/glpi/commit/ec42af93d34524da0bd175eedd44b92b9d55bdd1

Here the value of begin date set at today : 
![image](https://user-images.githubusercontent.com/113057/61461898-fb0f6700-a971-11e9-80e9-f13b0620ac09.png)

I save.

Here the database : 
![image](https://user-images.githubusercontent.com/113057/61462003-2f832300-a972-11e9-9bb9-5ad764ef7a30.png)

**Comment by cedric-anne** [comment]
Explaination can be that, `begin date + (periodicity * n)` is always ouside working hours of calendar.

**Comment by barbuslex** [comment]
I have test without calendar and its the same result : 
![image](https://user-images.githubusercontent.com/113057/61462675-4d9d5300-a973-11e9-8130-45d9c4b77c4c.png)

**Comment by cedric-anne** [comment]
As I am not able to reproduce, even after injecting your data in my DB, I can't help anymore.

**Comment by barbuslex** [comment]
the are only inc/ticketrecurrent.class.php to edit ?

I have replace this (on line 343) : 
```php
if (!is_int($periodicity) && !preg_match($periodicity_pattern, $periodicity)) {
```

By this : 
```php
if (!is_int($periodicity) && !preg_match('/^\d+$/', $periodicity)
          && !preg_match($periodicity_pattern, $periodicity)) {
```

**Comment by cedric-anne** [comment]
Should be the only file to update.

Other users says that it works, and I cannot reproduce the problem with this fix.

Maybe you have some configuration or plugin thaty explains your issue. If you need advanced support, please consider taking a subscription ( https://glpi-project.org/support/ ) or ask for help on community forums ( https://forum.glpi-project.org/ ).

**Comment by barbuslex** [comment]
I have disabled all plugins. The next_creation_date was updated !

But, i have set NULL value manually in next_creation_date for retry.
Second try: I save the recurrent ticket from glpi form. The next_creation_date is not set and stay null.
![image](https://user-images.githubusercontent.com/113057/61514341-23de3d80-aa00-11e9-9a58-77b5e125b4de.png)

If i set a end_date from glpi form it work !
![image](https://user-images.githubusercontent.com/113057/61514456-5ee07100-aa00-11e9-8f02-3e4600caed29.png)

If i set null in columns begin and end date manually.
I saved another form from glpi without end date and with different begin date. The next date is not generated.
![image](https://user-images.githubusercontent.com/113057/61514609-ab2bb100-aa00-11e9-82ce-6da361a26f37.png)

**Comment by esbnet** [comment]
Friends,

I noticed that even after the correction made by fix # 6140 of the Git Hub, when adding the "Recurring Call" nothing is recorded in the "Next creation" field, leaving it as "[NULL]". This is also true when changing the start date. However, when a change is made in the Name field "name" and confirmed, the "Next creation" is updated with the correct value, starting to generate the calls within the programmed.
