### ISSUE TITLE
GLPI 9.4.3 Contract Items (You can add only 1 item)

### ISSUE THREAD

**Issue by miodzio97** [glpi-project/glpi#6149]
You can add only one element on the contracts menu in the elements category.
It should be possible to add elements multiple times as in tickets or other places.

**Comment by cedric-anne** [comment]
Hi,

Hard to be sure of what you are talking about has you did not provide any real context informations or screenshots.

Can you check that number of already linked elements is lower thant the `Max number of items` value of the contract ?

Regards

**Comment by miodzio97** [comment]
Sorry
I haven't noticed this list.
All  work's Great.
Ticket closed :)
