### ISSUE TITLE
[9.4.3] Bad date format on recurrent ticket begin/end date change

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#6154]
Hi,

Following my remarks on issue #6140, i have investiged more on debug in `inc/ticketrecurrent.class.php` file.

I have found an issue with datepicker on recurrent ticket form dates.

When, whe display and save without modify any value in recurrent ticket form the date format is "Y-m-d H:i:s" : 
![image](https://user-images.githubusercontent.com/113057/61536532-26a75580-aa35-11e9-9f6c-20cf3567c053.png)
My test in `inc/ticketrecurrent.class.php` :
![image](https://user-images.githubusercontent.com/113057/61536576-3aeb5280-aa35-11e9-822d-cc71db66cabc.png) 
The result :
![image](https://user-images.githubusercontent.com/113057/61536616-4f2f4f80-aa35-11e9-98d3-c0419f47e4c7.png)

If we return on ticket form and we pick a new begin date from date picker, the date format send is "Y-m-d **H:i**" (missing seconds) :
![image](https://user-images.githubusercontent.com/113057/61536687-7ede5780-aa35-11e9-8aa7-d90ede8f14c9.png)
The result : 
![image](https://user-images.githubusercontent.com/113057/61537189-cca78f80-aa36-11e9-87c9-e247a8f648c8.png)

Same issue for end date.

I think it need to change the format send by datepicker.

Thanks

**Comment by barbuslex** [comment]
I have try to fix it.
It work's perfectly with this code : 
![image](https://user-images.githubusercontent.com/113057/61538827-818f7b80-aa3a-11e9-852b-cb19723b6579.png)

**Comment by cedric-anne** [comment]
Hi,

#6157 seems a better fix, as it will globally fix this problem.

Regards

**Comment by barbuslex** [comment]
@cedric-anne Yes it works too ! I haven't found the file of datepicker ^^
Thanks
