### ISSUE TITLE
SLQ Error

### ISSUE THREAD

**Issue by msizec** [glpi-project/glpi#6172]
Hi

Heres what I found in sql-errors.logs

[2019-07-25 11:11:45] glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT `glpi_users`.`id` AS `users_id`, `glpi_users`.`1`, `glpi_users`.`language` AS `language`, `glpi_tickets_users`.`use_notification` AS `notif`, `glpi_tickets_users`.`alternative_email` AS `altemail` FROM `glpi_tickets_users` LEFT JOIN `glpi_users` ON (`glpi_tickets_users`.`users_id` = `glpi_users`.`id`) INNER JOIN `glpi_profiles_users` ON (`glpi_profiles_users`.`users_id` = `glpi_users`.`id`  ) WHERE `glpi_tickets_users`.`tickets_id` = '59981' AND `glpi_tickets_users`.`type` = '2' AND `glpi_tickets_users`.`users_id` = '232'
  Error: Unknown column 'glpi_users.1' in 'field list'
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:569                          DBmysqlIterator->execute()
  plugins/behaviors/inc/ticket.class.php:188         DBmysql->request()
  plugins/behaviors/inc/ticket.class.php:98          PluginBehaviorsTicket::getLastLinkedUserByType()
  inc/plugin.class.php:1112                          PluginBehaviorsTicket::addActionTargets()
  inc/notificationtarget.class.php:1148              Plugin::doHook()
  inc/notificationeventabstract.class.php:91         NotificationTarget->addForTarget()
  inc/notificationevent.class.php:163                NotificationEventAbstract::raise()
  inc/commonitilactor.class.php:408                  NotificationEvent::raiseEvent()
  inc/ticket_user.class.php:59                       CommonITILActor->post_addItem()
  inc/commondbtm.class.php:1142                      Ticket_User->post_addItem()
  inc/commonitilobject.class.php:1588                CommonDBTM->add()
  inc/ticket.class.php:2157                          CommonITILObject->post_addItem()
  inc/commondbtm.class.php:1142                      Ticket->post_addItem()
  front/ticket.form.php:63                           CommonDBTM->add()
  {"user":"232@REIAPPGLPI01","mem_usage":"0.000\", 4.92Mio)"}

I was my user who generated the page and the errror

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by msizec** [comment]
didnt find page urls
didn't manage to reproduce

about the server : 

[code]   GLPI 9.4.2 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux REIAPPGLPI01 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 PHP 7.2.12-1+0~20181112102304.11+stretch~1.gbp55f215 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, 	json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi Port 80) 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.3.11-MariaDB-1:10.3.11+maria~stretch 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.3.11) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)


fields               Name: Champs supplémentaires         Version: 1.10.0     State: Enabled 	behaviors            Name: Comportements                  Version: 2.2.1      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.8.3      State: Enabled 	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

The backtrace is related to `behaviors` plugin. You should open an issue on their repository.

Regards
