### ISSUE TITLE
redirect to document remove tickets_id parameter

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#618]
Ex : 

/index.php?redirect=/front/document.send.php?docid=4511&tickets_id=2573&noAUTO=1

transform to 

/document.send.php?docid=4511

**Comment by remicollet** [comment]
Doesn't seems to work, according to http://forum.glpi-project.org/viewtopic.php?pid=317828#p317828

**Comment by yllen** [comment]
Problem come from https://github.com/glpi-project/glpi/pull/507
