### ISSUE TITLE
Knowledgebase articles not showing up when associated to a group

### ISSUE THREAD

**Issue by Tagge** [glpi-project/glpi#6180]
**Describe the bug**

When adding a knowledge base article and adding a group to it, users of this group are unable to find the article in their knowledgebase.
However, they're able to "direct-access" it if they've got a link of this sort : 
GLPI_URL/front/knowbaseitem.form.php?id=ID
For the context, this issue seems to be following an upgrade from v9.2.4 to 9.4.2

**Page(s) URL**

GLPI_URL/front/knowbaseitem.form.php?id=ID (where the article can be accessed)
GLPI_URL/front/knowbaseitem.php (where the article doesn't show up)

**To reproduce**

1. Create a new article in the knowledge base and publish it
2. Add a new group to it
3. Make sure to assign this group to yourself and to switch to Supervisor
4. Consult GLPI_URL/front/knowbaseitem.php, where the article shouldn't appear anywhere

**Expected behavior**

Article should be impossible to find by exploring the knowledge base. If you've got the article ID, however, you can access it using the URL given above.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Windows NT POSEIDON 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
PHP 5.6.35 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar,
	com_dotnet, ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, sockets,
	sqlite3, standard, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.33 (Win64) mod_authnz_sspi/0.1.1 PHP/5.6.35 (Apache/2.4.33 (Win64) mod_authnz_sspi/0.1.1 PHP/5.6.35 Server
	at poseidon Port 80)
	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.21
	Server SQL Mode: 
	Parameters: root@localhost/glpibiospringer
	Host info: localhost via TCP/IP

**Additional context**

This is the query that I've extracted using the debug mode : 
SELECT DISTINCT `glpi_knowbaseitems`.* 
FROM `glpi_knowbaseitems` 
LEFT JOIN `glpi_knowbaseitems_users` ON (`glpi_knowbaseitems_users`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) 
LEFT JOIN `glpi_groups_knowbaseitems` ON (`glpi_groups_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) 
LEFT JOIN `glpi_knowbaseitems_profiles` ON (`glpi_knowbaseitems_profiles`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) 
LEFT JOIN `glpi_entities_knowbaseitems` ON (`glpi_entities_knowbaseitems`.`knowbaseitems_id` = `glpi_knowbaseitems`.`id`) 
WHERE (`glpi_knowbaseitems`.`users_id` = '2449' OR `glpi_knowbaseitems_users`.`users_id` = '2449' OR (`glpi_groups_knowbaseitems`.`groups_id` IN ('1') AND (`glpi_groups_knowbaseitems`.`entities_id` < '0')) OR (`glpi_knowbaseitems_profiles`.`profiles_id` = '7' AND (`glpi_knowbaseitems_profiles`.`entities_id` < '0' OR (`glpi_knowbaseitems_profiles`.`entities_id` IN ('0')))) OR `glpi_entities_knowbaseitems`.`entities_id` IN ('0')) AND (`glpi_entities_knowbaseitems`.`entities_id` IS NOT NULL OR `glpi_knowbaseitems_profiles`.`profiles_id` IS NOT NULL OR `glpi_groups_knowbaseitems`.`groups_id` IS NOT NULL OR `glpi_knowbaseitems_users`.`users_id` IS NOT NULL) AND (`glpi_knowbaseitems`.`begin_date` IS NULL OR `glpi_knowbaseitems`.`begin_date` < NOW()) AND (`glpi_knowbaseitems`.`end_date` IS NULL OR `glpi_knowbaseitems`.`end_date` > NOW()) 
ORDER BY `date` DESC LIMIT 10
I have manually run the query with MySQL in order to find if there was a way to fix it. I've been able to fix this issue by modifying this condition : 
OR (`glpi_groups_knowbaseitems`.`groups_id` IN ('1') AND (`glpi_groups_knowbaseitems`.`entities_id` < '0'))
and replacing it by :-1: 
OR (`glpi_groups_knowbaseitems`.`groups_id` IN ('1'))
What I found during my search was that in the table glpi_groups_knowbaseitems, the entities_id value was always equal to 0, therefore preventing the fetching of articles associated to a group. A quick fix for me was to set this value to -1 for all pre-existing glpi_groups_knowbaseitems rows, but it falls short of solving the problem for future additions to the knowledge base.

**Comment by cedric-anne** [comment]
Hi,

Duplicates #5643. Seems like #6161 solves this issue. Please confirm on #5643 

Regards
