### ISSUE TITLE
API REST : Lines not appear with search AllAssets

### ISSUE THREAD

**Issue by Kartoon93** [glpi-project/glpi#6189]
Hi, 

I use GLPI 9.4.2 since a few weeks, and I work on a powershell script with the API REST. 

I tried to retrieve all the assets of an user with the request : 

apirest.php/search/AllAssets?criteria[1][link]=AND&criteria[1][field]=70&criteria[1][searchtype]=contains&criteria[1][value]=terrthfr&range=0-1000

This request return me all the Assets (computer, phone, monitor) of "terrthfr", except for the lines. 

If i replace "AllAssets" by "Lines", it return the lines. 

Is it normal that the lines aren't includes in AllAssets ?  

Is there a way to have lines and assets (Computer, Monitor) with 1 request ? 

Thanks for your help

**Comment by cedric-anne** [comment]
Hi,

Technically, it is normal that `Line` items are not listed in `AllAssets` request (see https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/define.php#L209).

On a functionnal point of view, I do not know.

Regards

**Comment by Kartoon93** [comment]
Hi Cedric, 

Thanks for this quick answer. 

Do you know is there a way to add Line in Assets ? 
I just see lines doesn't appear neither on the user profile. It's very problematic. 

Thanks for your help,

**Comment by trasher** [comment]
It seems the feature you expect do not exists yet. Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
