### ISSUE TITLE
Validation of a request or incident is not working in the "Simplified Interface" profile

### ISSUE THREAD

**Issue by maguimmm** [glpi-project/glpi#6192]
**Describe the bug**

When the functionality that allows a user to be validated is checked, it is doing the opposite effect to what the functionality proposes, ie when checked should allow a user to validate the ticket. We noticed that when the validation functionality is enabled, in the Processing called tab the document permission and follow-up is enabled, but when unchecked no permission is applied, thus inhibiting the possibility of validation.

**Page(s) URL**
https://glpi/front/ticket.form.php?id=23795
**To reproduce**

1.	Go to Administration>Profiles>Self-Service>Assistance
a.	Select validate a request and an incident
 
![image](https://user-images.githubusercontent.com/53317395/62233009-fd27eb80-b39d-11e9-90ef-b11367a372b4.png)

2.	Go to called processing tab and approve a request, but the approval box is not opened. 
![image](https://user-images.githubusercontent.com/53317395/62233387-dcac6100-b39e-11e9-953a-f457bee088eb.png)
  
The approval request is only possible when to select the tab approvals.
 
![image](https://user-images.githubusercontent.com/53317395/62233448-fe0d4d00-b39e-11e9-9235-d86c53361504.png)

Obs.: Go to Administration>Profiles>Self-Service>Assistance
When the validate incident and request selections are removed, the approval functionality on the calling processing tab is granted.
 
![image](https://user-images.githubusercontent.com/53317395/62233491-11b8b380-b39f-11e9-914d-c41778429355.png)

**Expected behavior**
1.	Go to Administration>Profiles>Self-Service>Assistance
a.	Select validate a request and an incident
 
![image](https://user-images.githubusercontent.com/53317395/62233514-1c734880-b39f-11e9-95a5-41d1e27a1a7e.png)

In the processing ticket tab click the indicated icon.
 
![image](https://user-images.githubusercontent.com/53317395/62233534-26954700-b39f-11e9-8a93-1da865e52345.png)

Window that opens after clicking on the icon.
 
![image](https://user-images.githubusercontent.com/53317395/62233558-32810900-b39f-11e9-9fcd-ce6473ba8d1a.png)

**Logs**
Information about system installation and configuration
[code]
 
GLPI 9.4.3 ( => /glpi/css)
Installation mode: TARBALL

Server
 
Operating system: Linux  4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64
PHP 7.0.27-0+deb9u1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, calendar, cgi-fcgi, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="15M" safe_mode="" session.save_handler="files"
	upload_max_filesize="15M" 
Software: nginx/1.10.3
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36
Server Software: Debian 9.6
	Server Version: 10.1.37-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: @localhost/GLPI
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.1.37) - Perfect!Database version seems correct (10.1.37) - Perfect!
OK/glpi/css/files/_log : OK
OK/glpi/css/config : OK
OK/glpi/css/files : OK
OK/glpi/css/files/_dumps : OK
OK/glpi/css/files/_sessions : OK
OK/glpi/css/files/_cron : OK
OK/glpi/css/files/_graphs : OK
OK/glpi/css/files/_lock : OK
OK/glpi/css/files/_plugins : OK
OK/glpi/css/files/_tmp : OK
OK/glpi/css/files/_cache : OK
OK/glpi/css/files/_rss : OK
OK/glpi/css/files/_uploads : OK
OK/glpi/css/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.2.4 in (/glpi/css/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/glpi/css/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/glpi/css/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/glpi/css/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/glpi/css/vendor/michelf/php-markdown/Michelf)
true/punycode in (/glpi/css/vendor/true/punycode/src)
iamcal/lib_autolink in (/glpi/css/vendor/iamcal/lib_autolink)
sabre/vobject in (/glpi/css/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/glpi/css/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/glpi/css/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/glpi/css/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/glpi/css/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/glpi/css/vendor/sebastian/diff/src)
elvanto/litemoji in (/glpi/css/vendor/elvanto/litemoji/src)
symfony/console in (/glpi/css/vendor/symfony/console)
leafo/scssphp in (/glpi/css/vendor/leafo/scssphp/src)

LDAP directories
 
Server: '', Port: '', BaseDN: 'DC=,DC=,DC=,DC=,DC=', Connection filter:
		'(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf=CN=-1,OU=Grupos,OU=E-MAIL,OU=GRUPOS_RECURSOS,DC=,DC=,DC=,DC=,DC=))',
		RootDN: , Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@)

Mails receivers
 
Name: '' Active: Yes
	Server: '{/imap/ssl/novalidate-cert}' Login: '' Password: 

Plugins list
 
	webapplications      Name: Aplicações web                 Version: 2.6.0      State: Enabled
	fields               Name: Campos adicionais              Version: 1.10.1     State: Enabled
	behaviors            Name: Comportamental                 Version: 2.2.1      State: Enabled
	escalade             Name: Escalonamento                  Version: 2.4.4      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.3      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled
	tag                  Name: Gerenciamento de Etiquetas     Version: 2.4.2      State: Enabled
	genericobject        Name: Gerenciamento de objetos       Version: 2.7.0      State: Enabled
	mreporting           Name: Mais Relatórios                Version: 1.6.1      State: Enabled
	orderservice         Name: Ordem de Serviço               Version: 2.0.0      State: Enabled
	dashboard            Name: Painel                         Version: 0.9.7      State: Enabled
	consumables          Name: Pedidos de consumíveis         Version: 1.5.0      State: Enabled
	reports              Name: Relatórios                     Version: 1.13.1     State: Enabled

[/code]

**Comment by mauriciolamego** [comment]
Hello, I am also having this same problem. Users are only being able to approve on the approvals tab, when in version 9.3.3, which we previously used, this normally worked directly on the "processing ticket" tab.
And as we have already instructed our users to get approved by the "processing ticket" tab we are having several related incidents.
We refer our users to the approval by the "processing ticket" tab, because in the "approvals" tab they get confused and end up doing wrong, creating a new approval request or even just entering a comment, without selecting if they approved or denied the request.
We would be grateful for a solution!
Thanks!

**Comment by flegastelois** [comment]
Hi,

Thanks for your report, I confirm this behavior but not exactly as you describe it.

Validate directly from the Processing tab is possible if users have the rights "Validations > Create for Request or Incident". The problem is with these parameters.

We'll fix it in a future release, if you'd like to help us produce a fix faster: you can subscribe to GLPI Network at https://services.glpi-network.com

Kind regards,

**Comment by Dayflare** [comment]
had this issue too, the new version 9.4.4 fixed it for me.

**Comment by cedric-anne** [comment]
@maguimmm @mauriciolamego ,

Can you confirm that this issue is solved on 9.4.4 ?

Regards

**Comment by maguimmm** [comment]
@Dayflare Can we make this change in version 9.4.3 without upgrading to version 9.4.4?

**Comment by trasher** [comment]
9.4.4 is a security release, you really should consider upgrading. Also, applying single fix among all other changes may not work and/or have not sense.

**Comment by Dayflare** [comment]
@maguimmm version 9.4.4 has no database changes, you just copy the new files to your server and refresh your browser. Done in 5 minutes.
