### ISSUE TITLE
Technician in charge doest not receive email

### ISSUE THREAD

**Issue by ManuelCan** [glpi-project/glpi#6195]
Hi.

I'm unable to send notifications when new follow up is added and I see this error in php-errors.log.
Same error with imported AD and only local users.

GLPI Version is 9.4.3
Server version: Debian 9.9

[2019-08-02 17:38:44] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: from
  Backtrace :
  inc/rulemailcollectorcollection.class.php:116
  inc/rulecollection.class.php:1695                  RuleMailCollectorCollection->prepareInputDataForProcess()
  inc/rulecollection.class.php:1528                  RuleCollection->prepareInputDataForProcessWithPlugins()
  inc/mailcollector.class.php:1053                   RuleCollection->processAllRules()
  inc/mailcollector.class.php:677                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1794                   MailCollector->collect()
  inc/crontask.class.php:829                         MailCollector::cronMailgate()
  front/crontask.form.php:49                         CronTask::launch()
  {"user":"2@----1"}

**Comment by flegastelois** [comment]
Hi,

Error you specify is not related to notifications, but to "Rule Mail Collector" which appears to have an implementation error.

If you need help configuring GLPI notifications, you can contact an official partner:
https://glpi-project.org/partners/

Or use the community forum:
https://forum.glpi-project.org

Kind regards,
