### ISSUE TITLE
Glpi Reminders sent at wrong time

### ISSUE THREAD

**Issue by roshanroche** [glpi-project/glpi#6197]
Hi ,
when i create a new reminder and add to schedule and select the start date 05-08-2019 08:05 , Period 1h00 , Reminder 15 mins.
I should be getting a reminder at 08:50 
But the reminder is sent immediately upon adding the reminder.
Because the reminder countdown starts from 08:05 instead of 09:05
![image](https://user-images.githubusercontent.com/22425503/62438411-4e4a2d80-b758-11e9-8ff4-859db39d9db6.png)
the recall is fired at 7:50 which is 15 mins before 8:05.
recall should be at 8:50 15 mins before the 1h end time of 9:05

tried on glpi9.3.x and 9.4.x

**Comment by flegastelois** [comment]
Hi,

The "Planning recalls" feature is designed to send a reminder **before the start** of a scheduled event (such as appointments in a calendar), not to warn of the end of an event.

So, the feature you want (choose whether the planning recalls should be sent before the start of an event, or before the end of an event, or even after an event) currently doesn't exist in GLPI.

Ideas to be implemented, must be discussed first on suggestion website (https://suggest.glpi-project.org).

Can you declare your issue on this platform? I close this one.

Kind regards,
