### ISSUE TITLE
opcode and user data cache

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#620]
GLPI works faster with opcache and apcu.

Idea about this:

- detect them during installer (not a blocker, only information)
- add a new tab on configuration with information
     - missing
     - memory consumption
     - hits
     - reset button

Thoughts ?

**Comment by ddurieux** [comment]
It's a good idea, it can help people to win in performance ;)

**Comment by orthagh** [comment]
I think it's a good idea

**Comment by tomolimo** [comment]
I totally agree for opcache (as I'm using it for my new GLPi 9.1 installation, and really I got ~20% benefit of performance), but I don't understand the need for apcu. 
Could you explain the need for apcu?

**Comment by ddurieux** [comment]
When you request a php file, php read the code, compile it and execute it.
With apcu, it will cache the "php read the code, compile it", so it only execute it and so it's reduce resources on server and time to serve the page.

**Comment by remicollet** [comment]
What @ddurieux describe is opcache feature ;)

APCU is used, in GLPI, by zend-cache / zend-i18n to save parsed locale file, which is a long process, and so save lot of time.

**Comment by tomolimo** [comment]
I though it was the role of opcache?
PHP manual explains that apcu is for user data only: "APCu is APC stripped of opcode caching."

**Comment by tomolimo** [comment]
oups our answers are mixed now :)!

**Comment by tomolimo** [comment]
@remicollet thank you, I understand now for APCu, and I agree for both

**Comment by remicollet** [comment]
Central load time (PHP 5.6.20)

* No cache: 0.038 seconde - 17.89 Mio
* opcache: 0.015 seconde - 11.96 Mio
* opcache + apcu: 0.005 seconde - 12.02 Mio

**Comment by ddurieux** [comment]
Ah? I was thinking APCu can do this too (php cache) :/

**Comment by remicollet** [comment]
Notice: for now zend-cache use the old APC API, so with PHP-7 the extension needed is [apcu-bb](https://pecl.php.net/package/apcu_bc), while [apcu](https://pecl.php.net/package/apcu) is enough on PHP 5

APC (the old extension doing opcode + user data cache is dead, should be avoid).

**Comment by tomolimo** [comment]
Tried to install apcu_bc for PHP 7, and it requires apcu to be installed also: strange?
And after both installations I got HTTP500 from times to times when looking at Tickets.

**Comment by remicollet** [comment]
> Tried to install apcu_bc for PHP 7, and it requires apcu to be installed also: strange?

Normal. apcu-bc is only a compatibility layer (mostly function aliasses)

>  And after both installations I got HTTP500 from times to times when looking at Tickets.

Strange, error message (apache log ?)

**Comment by satyan01** [comment]
Hello, same error for me

glpi 9.1.4 php 7.012 apcu 5.1.8 iis8.5

**Comment by tomolimo** [comment]
Hello,
Seems like APCu is not really compatible with IIS and Windows memory model. I got HTTP 500 Error each time I tries APCu.
Regards,
Tomolimo

**Comment by satyan01** [comment]
Hello

It has been solved, I will see in time...
