### ISSUE TITLE
Bug on batteries management

### ISSUE THREAD

**Issue by emaw705** [glpi-project/glpi#6202]
Hi.

I detected some things that are wrongs.

**Describe the bug**

First, in the "Setup -> Dropdowns" section I detected a difference between the "English(US)" and "Spanish" language.

In English language GLPI shows the option 'Device processor models', but in Spanish GLPI doesn't show that option.

In Spanish language GLPI shows the option 'Modelos de batería de dispositivo' or 'Device battery models', but in English (US) GLPI doesn't show that option.

![image](https://user-images.githubusercontent.com/48997363/62535295-69cd3b00-b821-11e9-81c5-63726bff47f2.png)

Then, if I create a 'Device battery models', it never could be used because in the section "Setup -> Components -> Batteries" isn't the option "Model".

![image](https://user-images.githubusercontent.com/48997363/62535660-58386300-b822-11e9-895b-2ec19efeb47c.png)

In addition, on "Setup -> Dropdowns" doesn't show the option "Baterries Types", so never can I load batteries types, except selecting the icon "i" on Batteries Component (URL: Setup -> Components -> Batteries)

![image](https://user-images.githubusercontent.com/48997363/62536500-81f28980-b824-11e9-8e9e-29611abeaff0.png)

![image](https://user-images.githubusercontent.com/48997363/62536320-1c060200-b824-11e9-840d-f7e4ea84aafb.png)

![image](https://user-images.githubusercontent.com/48997363/62536074-6470f000-b823-11e9-83a8-eac2b8255c07.png)

Thanks.

Bye.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided (such as GLPI version).

Translations are handled on transifex, see: https://www.transifex.com/glpi/GLPI/dashboard/.

**Comment by emaw705** [comment]
Sorry.

The version of GLPI is 9.4.3.

![image](https://user-images.githubusercontent.com/48997363/62538407-14952780-b829-11e9-90be-37aee3b82ab5.png)

It isn't a problem for translation, it is a functional problem. I don't understand because if I change the languaje, appear differents links in the same section.

In Spanish -> Impossible to create Processor models
In English -> Impossible to create Battery models

Thanks.

**Comment by flegastelois** [comment]
Hi,

I confirm, this is a translation issue.

![image](https://user-images.githubusercontent.com/470612/63582311-243a9d00-c599-11e9-8ac9-1050ac70d035.png)

Translations are handled on transifex by the community, see: https://www.transifex.com/glpi/GLPI/dashboard/

Kind regards,
