### ISSUE TITLE
ProjectTask linked to KDB

### ISSUE THREAD

**Issue by grigribou** [glpi-project/glpi#6219]
Hi,

I created a proyect template with different task to do.
I'd like to link this task with an existing KDB article, but I'm not able to find how to do it.

Only way I found is to put KDB url into a Document, and link this document... 
I don't think this is a good way to do it... 

There is no way to do it as we can link a KDB into a ticket?

Thanks,

**Comment by flegastelois** [comment]
Hi,

The feature you want (direct link ProjectTask to KDB article) currently doesn't exist in GLPI.

Ideas to be implemented, must be discussed first on suggestion website (https://suggest.glpi-project.org).

Can you declare your issue on this platform? I close this one.

Regards,
