### ISSUE TITLE
mysql error

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#622]
Hello I have this issue in log mysql

2016-04-21 11:12:33 [@UNGSRVGVA118]
*** MySQL query error:
SQL: UPDATE glpi_users
SET lock_directunlock_notification = NULL WHERE id =\'636\'
Error: Column 'lock_directunlock_notification' cannot be null
Backtrace :
inc\commondbtm.class.php:357

inc\commondbtm.class.php:1116 CommonDBTM->updateInDB()
inc\auth.class.php:756 CommonDBTM->update()
front\login.php:78 Auth->Login()

**Comment by orthagh** [comment]
@tomolimo 
Could you check this issue ?

**Comment by tomolimo** [comment]
Yes :)
I already got this when I updated my 0.91 sources to 9.1 master.
For me it's coming from a wrong upgrade from 0.91 to 9.1 which is not existing in the upgrade paths.
@satyan01: you should perform a new upgrade from 0.902 to 9.1, or a new installation from scratch.

**Comment by satyan01** [comment]
OK I am waiting for the new official GLPI version

**Comment by orthagh** [comment]
Ok, i close

**Comment by satyan01** [comment]
I have tried but I have this message 

Error during the database query: ALTER TABLE `glpi_users` DROP PRIMARY KEY - Error is Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by tomolimo** [comment]
What did you tried exactly?

**Comment by satyan01** [comment]
copy 0.90.2 and copy actual db and migrate

**Comment by satyan01** [comment]
You are trying to use GLPI with outdated files compared to the version of the database. Please install the correct GLPI files corresponding to the version of your database.

**Comment by tomolimo** [comment]
What is the version of actual DB?

**Comment by tomolimo** [comment]
could you open another issue, as this one is already closed?

**Comment by satyan01** [comment]
yes of course.

**Comment by jayshah19949596** [comment]
I am having the same issue... Any solution ??

**Comment by orthagh** [comment]
in mysql:

```sql
ALTER TABLE `glpi_users`
HANGE COLUMN `lock_directunlock_notification` `lock_directunlock_notification` TINYINT(1) NULL;
```
