### ISSUE TITLE
GLPI 9.4.3 Project 

### ISSUE THREAD

**Issue by yazmit** [glpi-project/glpi#6220]
Hi  I have a problem with the project, the element and the cost of the project appears in the budget, but doesn't subtract from the total value of the budget. I tried to change the statute of the project,"Closed" but nothing is working for me. I will appreciate everyone help because it bothers me a lot  thanks in advance

**Comment by flegastelois** [comment]
Hi,

Thanks for your report, I confirm the bug when Entity mode is active.

Here is the generated SQL error.

```txt
[2019-08-23 10:33:07] glpisqllog.ERROR: DBmysql::query() in /glpi/9.4-bugfixes/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_projects`.`entities_id`, SUM(`glpi_projectcosts`.`cost`) AS sumvalue FROM `glpi_projectcosts` INNER JOIN `glpi_projects` ON (`glpi_projects`.`id` = `glpi_projectcosts`.`projects_id`) WHERE `glpi_contractcosts`.`budgets_id` = '1' GROUP BY `glpi_projects`.`entities_id`
  Error: Unknown column 'glpi_contractcosts.budgets_id' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/budget.class.php:791                           DBmysql->request()
  inc/budget.class.php:89                            Budget->showValuesByEntity()
  inc/commonglpi.class.php:485                       Budget::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
```
We'll fix it in a future release, if you'd like to help us produce a fix faster: you can subscribe to GLPI Network at https://services.glpi-network.com

Kind regards,

**Comment by yazmit** [comment]
Thanx a lot worked like a charm .
