### ISSUE TITLE
sql-erros.log big

### ISSUE THREAD

**Issue by rjmontenegro** [glpi-project/glpi#6221]
Hi all.
In less than 1 day I have 2000000 error lines in the sql-errors.log file and 150MB. The error is always the same:
[2019-08-13 00:58:26] glpisqllog.ERROR: DBmysql::query() in /var/www/servicedesk.glpi.local/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT COUNT(*) AS cpt
                FROM `glpi_calendars_holidays`
                INNER JOIN `glpi_holidays`
                     ON (`glpi_calendars_holidays`.`holidays_id` = `glpi_holidays`.`id`)
                WHERE `glpi_calendars_holidays`.`calendars_id` = '2'
                      AND (('35281-04-25' <= `glpi_holidays`.`end_date`
                             AND '35281-04-25' >= `glpi_holidays`.`begin_date`)
                           OR (`glpi_holidays`.`is_perpetual` = 1
                               AND MONTH(`end_date`)*100 + DAY(`end_date`)
                                       >= 425
                               AND MONTH(`begin_date`)*100 + DAY(`begin_date`)
                                       <= 425
                              )
                          )
  Error: Illegal mix of collations (utf8_unicode_ci,COERCIBLE) and (latin1_swedish_ci,NUMERIC) for operation '<='
  Backtrace :
  inc/calendar.class.php:263                         
  inc/calendar.class.php:355                         Calendar->isHoliday()
  inc/calendar.class.php:384                         Calendar->isAWorkingDay()
  inc/ticketrecurrent.class.php:391                  Calendar->isAWorkingHour()
  inc/ticketrecurrent.class.php:124                  TicketRecurrent->computeNextCreationDate()
  inc/commondbtm.class.php:1363                      TicketRecurrent->prepareInputForUpdate()
  front/dropdown.common.form.php:106                 CommonDBTM->update()
  front/ticketrecurrent.form.php:36                  include()
  {"user":"18@srvsd-pcr.glpi.local","mem_usage":"0.001\", 2.35Mio)"} 

Thanks

**Comment by rjmontenegro** [comment]
mysql> SELECT CCSA.character_set_name FROM information_schema.`TABLES` T, information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation AND T.table_schema = "glpi" AND T.table_name = "glpi_holidays";
+--------------------+
| character_set_name |
+--------------------+
| utf8               |
+--------------------+
1 row in set (0.00 sec)

mysql> SELECT CCSA.character_set_name FROM information_schema.`TABLES` T, information_schema.`COLLATION_CHARACTER_SET_APPLICABILITY` CCSA WHERE CCSA.collation_name = T.table_collation AND T.table_schema = "glpi" AND T.table_name = "glpi_calendars_holidays";
+--------------------+
| character_set_name |
+--------------------+
| utf8               |
+--------------------+
1 row in set (0.00 sec)

**Comment by rjmontenegro** [comment]
but a database looks like this:
mysql> SELECT SCHEMA_NAME 'database', default_character_set_name 'charset', DEFAULT_COLLATION_NAME 'collation' FROM information_schema.SCHEMATA;
+--------------------+---------+-------------------+
| database           | charset | collation         |
+--------------------+---------+-------------------+
| information_schema | utf8    | utf8_general_ci   |
| glpi               | latin1  | latin1_swedish_ci |
| mysql              | latin1  | latin1_swedish_ci |
| performance_schema | utf8    | utf8_general_ci   |
| sys                | utf8    | utf8_general_ci   |
+--------------------+---------+-------------------+

**Comment by rjmontenegro** [comment]
The sql-errors.log file only grows until it fills the disk when the "ticketrecurrent" automatic action is up and running. I've also deleted the records from the glpi_calendars_holidays and glpi_holidays table. Can you help?
Thanks

**Comment by trasher** [comment]
Tables are created in utf8 in GLPI, so this is a database issue. Please see https://src-bin.com/en/q/f629f to get that fixed (thanks to @flegastelois who find this link).

**Comment by rjmontenegro** [comment]
> Tables are created in utf8 in GLPI, so this is a database issue. Please see https://src-bin.com/en/q/f629f to get that fixed (thanks to @flegastelois who find this link).

Hi Johan.
Sorry for insistence but the tables glpi_calendars_holidays and glpi_holidays are utf8 and now database also.
Could it be nothing else?

mysql> SHOW TABLE STATUS where name like 'glpi_holidays';
+---------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
| Name          | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation       | Checksum | Create_options | Comment |
+---------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
| glpi_holidays | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        98304 |         0 |              1 | 2019-09-04 10:06:40 | NULL        | NULL       | utf8_unicode_ci |     NULL |                |         |
+---------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
1 row in set (0.00 sec)

mysql> SHOW TABLE STATUS where name like 'glpi_calendars_holidays';
+-------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
| Name                    | Engine | Version | Row_format | Rows | Avg_row_length | Data_length | Max_data_length | Index_length | Data_free | Auto_increment | Create_time         | Update_time | Check_time | Collation       | Checksum | Create_options | Comment |
+-------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+
| glpi_calendars_holidays | InnoDB |      10 | Dynamic    |    0 |              0 |       16384 |               0 |        32768 |         0 |              1 | 2019-09-04 10:06:27 | NULL        | NULL       | utf8_unicode_ci |     NULL |                |         |
+-------------------------+--------+---------+------------+------+----------------+-------------+-----------------+--------------+-----------+----------------+---------------------+-------------+------------+-----------------+----------+----------------+---------+

**Comment by trasher** [comment]
Initial error was on a field as far as I can see, not on a table.
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by rjmontenegro** [comment]
> Initial error was on a field as far as I can see, not on a table.
> Please use [forums](http://forum.glpi-project.org) to get support.

ok, thanks
