### ISSUE TITLE
9.4.3 - Merge ticket not working

### ISSUE THREAD

**Issue by Raoul2k19** [glpi-project/glpi#6223]
**Describe the bug**

When I use the "merge as followup" function, I have a message sayong everything is OK, but my tickets aren't merged.
There is no ' in the ticket's name.

**To reproduce**

1. Go to 'Ticket'
2. Check one or more ticket
3. click on "Action"
4. Select merge as followup
5. Select the ticket to merge into in the dropdown list
6. Check or not merge followup and merge documents

**Expected behavior**

selected ticket merge as a followup of the ticket selected in the dropdownlist

**Logs**

nothing in php-error.log
nothing int sql-error.log

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]
 
GLPI 9.4.3 ( => /var/www/html/glpi)
Installation mode: TARBALL

**Comment by cconard96** [comment]
Can you provide the name/contents of a ticket that fails to merge? A simple ticket seems to merge OK on a test instance of 9.4.3.

**Comment by Raoul2k19** [comment]
Any name or content, is the same result.
I just test again with :
Ticket 1:
 - Name: Test1
 - Content: Test1

Ticket 2:
 - Name: Test2
 - Content: Test2

I selected Ticket 2 to merge into Ticket 1. I got Operation successfull message, but the 2 tickets are still present.

**Comment by cconard96** [comment]
I'm sorry, I still cannot recreate this issue even with a new install of 9.4.3.

**Comment by Raoul2k19** [comment]
There is a way to enbale a step by step deug ou something else to trace what append on my server?

**Comment by Raoul2k19** [comment]
OK, problem solved.
I had lot of `"[ERROR] Transaction not registered for MariaDB 2PC, but transaction is active"` message in /var/log/message
After enable logs in mariadb and try to merge tickets I saw that all the SQL part between START TRANSACTION and COMMIT wasn't executed.
I restarted mariadb and found the following error message when the daemon start:
`[ERROR] Missing system table mysql.roles_mapping; please run mysql_upgrade to create it`
So I ran `mysql_upgrade -u root -p` and all the databas was updated and now everything works fine.
