### ISSUE TITLE
Associated elements listed without permission

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#6228]
Self-service user called and said she had no permission..turn out she can see Associated elements without permission to open them.

- Create KB article.
- Associate Ticket with it
- Let different user open the KB article and open the tab "Associated elements"
- There is the ticket where she has no permission to open it

IMHO this shouldn't be listed there.

GLPi 9.4.2

**Comment by flegastelois** [comment]
Hi,

Thanks for your report.

We'll fix it in a future release, if you'd like to help us produce a fix faster: you can subscribe to GLPI Network at https://services.glpi-network.com

Kind regards,

**Comment by grigribou** [comment]
Hi,

I have a similar issue after GLPI server migration + Upgrade.

Not sure if t's due tu update to 9.5.3 (from 9.5.2) of for migration itself.

![image](https://user-images.githubusercontent.com/8124469/104206811-4653ea00-5430-11eb-96fb-8cb4e3c8344e.png)


I don't understand what's wrong

**Comment by Eon9D** [comment]
Had this issue today.
Caused by knownbaseitem.class.php if I remember correctly.
Just compare it to 9.5.2 and revert.


grigribou <notifications@github.com> schrieb am Mo. 11. Jan. 2021 um 17:14:

**Comment by fgendorf** [comment]
this was fixed on https://github.com/glpi-project/glpi/pull/8431
_________________________
Frederico Gendorf

**Comment by grigribou** [comment]
@fgendorf Thanks a lot! I confirm it solved my issue.
