### ISSUE TITLE
php issue

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#623]
Hello I have this issue in php log

2016-04-21 11:15:00 [896@UNGSRVGVA118]
*** PHP Notice(8): Undefined offset: 5200
Backtrace :
inc\search.class.php:2756

inc\search.class.php:465 Search::addWhere()
inc\search.class.php:97 Search::constructSQL()
inc\search.class.php:81 Search::showList()
front\ticket.php:56 Search::show()

**Comment by orthagh** [comment]
inc\search.class.php:2756 is an empty line for me in current master.

Could you copy the line here ?

**Comment by satyan01** [comment]
$table     = $searchopt[$ID]["table"];

**Comment by orthagh** [comment]
It seems relative to a plugin.
Could you attach the list of installed here ?

**Comment by satyan01** [comment]
Adressage IP	2.3.0	
Badges	2.1.1	GPLv2+	
Certificats	2.1.1	
Champs supplémentaires	0.90-1.1	
Comportements	
Connections	0.90-1.7.3	
Escalation	0.90-1.1	
Formulaires	0.90-1.4	
FP Software	1.1.0	
FusionInventory	0.90+1.1	
Injection de fichiers	2.4.1	
More ticket	1.2.3	
News	0.90-1.2	
Réservation	1.3.2	
Sim 
Tableau

**Comment by orthagh** [comment]
is this error repeats in your log ?

**Comment by orthagh** [comment]
Could you post the results of this mysql query : 

```sql
SELECT *
FROM glpi_displaypreferences
WHERE num = 5200
```

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/14737995/4ff825e6-087f-11e6-8ae2-8275556db297.png)

**Comment by orthagh** [comment]
I think 5200 keys was from customfields plugin
I failed to find this searchoption key in your list of plugins

I think you may delete theses entries
