### ISSUE TITLE
Ability to customize header column

### ISSUE THREAD

**Issue by oooforum** [glpi-project/glpi#6230]
By example, in Assets, we have long caption like : "Financial & Administrative Information - Date of Purchase". That will be fine to set a short customize text instead.

Thanks

**Comment by flegastelois** [comment]
Hi @oooforum,

Ideas to be implemented, must be discussed first on suggestion website (https://suggest.glpi-project.org).

Can you declare your issue on this platform? I close this one.

Regards,
