### ISSUE TITLE
Asset Depreciation

### ISSUE THREAD

**Issue by kevnflores** [glpi-project/glpi#6237]
I have not seen any tickets related to depreciation support. I really enjoy working with GLPI, but one of features that I think would be very useful is the incorporation of depreciation. Many ITSM projects incorporate some sort of straight line depreciation reporting. It looks like this was brought up in 2010 https://forum.glpi-project.org/viewtopic.php?id=21692

This would be a great feature in the Management field with either "Depreciation Rate" or set the rate based on asset type like "Computers - 5 year depreciation" 

It would be nice to then pull reports on current assets values. Let me know if I'm missing some configuration, but based on my testing there is only currently Amortization support.

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
