### ISSUE TITLE
copy 0.90.2 and copy actual db and migrate

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#624]
I use 0.91 database and glpi master from 04.04.2016

You are trying to use GLPI with outdated files compared to the version of the database. Please install the correct GLPI files corresponding to the version of your database.

Error during the database query: ALTER TABLE glpi_users DROP PRIMARY KEY - Error is Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by tomolimo** [comment]
Before starting the update of your actual DB.
Could you give the content of glpi_configs table? I need the record with id 1 (which is also the 'core' 'version' record)?

**Comment by satyan01** [comment]
core version 0.91

**Comment by tomolimo** [comment]
There is no existing DB migration procedure between 0.91 and 9.1
That's the reason why you have problems.

**Comment by satyan01** [comment]
ok thank you for your answer
