### ISSUE TITLE
special character in password

### ISSUE THREAD

**Issue by FernandoJungblut** [glpi-project/glpi#6244]
**Describe the bug**

when logging in to glpi and the password contains special characters like * glpi does not recognize the password.

**Page(s) URL**

Login

**To reproduce**

1. Go to 'Page Login'
2. Fill in login and password
2. Click on 'Send'
3. See error

**Expected behavior**

perform authentication and the ticket page appears

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.
