### ISSUE TITLE
The cache GLPI_CACHE / cache_db is never cleared

### ISSUE THREAD

**Issue by ettalhi** [glpi-project/glpi#6247]
**Describe the bug**
It seems that the cache called `cache_db` is never emptied or cleared.
That cache is used in the function `dbutils.class.php::getSonsOf() `for example; the problem occurred when we have imported another content for table  `glpi_entities`  but we still saw old entities in `glpiactiveentities_string` for example.  Even when I logged out and logged again for many times !

That cache file exists under path `files/_cache `.

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

see **Describe the bug** above.

**Expected behavior**
The cache is supposed to be cleared at each logoff or new login. or somethings like that.

**Logs**
`No logs`

**Screenshots**

`No screenshots`

**Comment by trasher** [comment]
Cache is not per user, but per instance. So, it will certainly not be removed on logout.
Also, you can configure caching to use something else than file caching.

**Comment by loicbenoit** [comment]
I believe the question is not about the cache mechanism, but about cache invalidation. The cache should invalidate when the source (DB) changes. The bug is that the cache doesn't invalidate when the DB changes.

**Comment by trasher** [comment]
Cache is updated when cached objects are changed in database, there are tested case in the tests suite. 
So maybe there is something that went wrong, but invalidating should not be required until there is a GLPI update.

**Comment by ettalhi** [comment]
@trasher : Do you have an idea of how to clear just a segment of the cache (a given table).
I know it is working by keys only, like `$ckey = $table . '_sons_cache_' . $IDf;`.  but should we do if we want to clear just some tables after import? or all that what we have is clear all the cache or using keys ?
