### ISSUE TITLE
LDAP group name issue

### ISSUE THREAD

**Issue by wadaki** [glpi-project/glpi#6248]
I use the latest GLPI version and installed as fresh.
After the installation I setup the Active Directory and added the CRONJOB for auto. sync

All works fine on the User, but I have trouble with Active Directory groups.

Some groups starts with "#" and he names of the groups were not imported correctly.

Example:
Active Directory group name: #p-whatever-you-like
After the import in GLPI, I can see the ID number only, no name.

How can I solve this issue?

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
