### ISSUE TITLE
Recurrent tickets' tasks are created by random users

### ISSUE THREAD

**Issue by danvasc** [glpi-project/glpi#6253]
**Describe the bug**

Everytime a recurring ticket is created with a predefined task, this task has a random author.

It doesn't matter how the task template is configured. It happens everytime with a different technician as author (only in recurring tickets).

**Page(s) URL**

Ticket's "Processing Ticket" tab.

**To reproduce**

1. Create task template
2. Create ticket template with the task template as predefined field
3. Create recurring ticket using the previously created ticket template
4. Wait for the ticket creation and check the ticket's "Processing Ticket" tab

**Expected behavior**

Maybe the task could be showed without an author or with a message like "generated automatically". 
Or even the task template creation menu could have an "author" option besides the responsible technician field.

**Screenshots**

As you can see in the screenshots, in three consecutive days, the same recurring ticket has tasks with different authors.

![print1](https://user-images.githubusercontent.com/53951841/64022130-e9da7e00-cb0b-11e9-9c0e-fa9f13a2af11.jpg)
![print2](https://user-images.githubusercontent.com/53951841/64022343-5fdee500-cb0c-11e9-88d2-632abd467884.jpg)
![print3](https://user-images.githubusercontent.com/53951841/64022346-62413f00-cb0c-11e9-8610-242c6df7aa7b.jpg)

**Your GLPI setup**

9.4.2

**Comment by trasher** [comment]
You should try with latest release, and latest 9.4 nightly build if not fixed in latest.

**Comment by cedric-anne** [comment]
Hi,

What is the configured `run mode` of your automatic task `ticketrecurrent` ? `GLPI` or `CLI` ?

Regards

**Comment by danvasc** [comment]
My `ticketrecurrent` `run mode` is configured as `GLPI`.

**Comment by danvasc** [comment]
> You should try with latest release, and latest 9.4 nightly build if not fixed in latest.

I'm trying the 9.4.3 version in my test environment, but I'm having some trouble. When I have the results, I'll post it here.

**Comment by danvasc** [comment]
> Hi,
> 
> What is the configured `run mode` of your automatic task `ticketrecurrent` ? `GLPI` or `CLI` ?
> 
> Regards

Based on your question, I changed the `run mode` to `CLI`. Now the tasks are marked as opened by the Requester.

Thank you all, I think it's solved.

![print4](https://user-images.githubusercontent.com/53951841/64131113-e578c400-cd9c-11e9-931e-ec00f9b5e0eb.jpg)
