### ISSUE TITLE
[9.5.0] ITILTemplate fields and keys not renaming on update

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#6256]
**Describe the bug**

Noticed while running tests locally for another feature,
Fields and keys are not renamed properly for templates when updating.

"Unknown column 'glpi_itilcategories.itiltemplates_id_incident' in 'on clause'". After looking into it more, many keys are using the old names instead of new ones. They are not renamed in the update script, only fields.

For the field rename issue, there is a duplicate key in the array so only one change is applied:
'glpi_itilcategories'               => 'tickettemplates_id_incident',
'glpi_itilcategories'               => 'tickettemplates_id_demand',

**Page(s) URL**

Noticed in functional tests (Search test).

**To reproduce**

Run functional tests on an updated DB.

**Expected behavior**

All old ticket template fields and keys get renamed to itil template name.

**Comment by trasher** [comment]
I'll take a look. This should only happens updating from an old 9.5/bugfixes (since rename was reverted).
