### ISSUE TITLE
dbmysql query error

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#6259]
Hello
I have this message regularly in sql-errors.log. Thank you for your help

[2019-09-02 10:46:51] glpisqllog.ERROR: DBmysql::query() in C:\inetpub\wwwroot\inc\dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_softwareversions`.`id`
                      FROM `glpi_softwareversions`
                      WHERE  `glpi_softwareversions`.`is_template` = '0'  AND `glpi_softwareversions`.`serial`='A0J253748'
                      GROUP BY `glpi_softwareversions`.`id`
                      ORDER BY `glpi_softwareversions`.`is_deleted` ASC
                      LIMIT 1
  Error: Unknown column 'glpi_softwareversions.is_template' in 'where clause'
  Backtrace :
  ...inventory\inc\inventoryruleimport.class.php:707 
  inc\rule.class.php:1563                            PluginFusioninventoryInventoryRuleImport->findWithGlobalCriteria()
  inc\rule.class.php:1429                            Rule->checkCriterias()
  inc\rulecollection.class.php:1539                  Rule->process()
  ...ventory\inc\inventorycomputerlib.class.php:1488 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:538 PluginFusioninventoryInventoryComputerLib->updateComputer()
  ...inventory\inc\inventoryruleimport.class.php:781 PluginFusioninventoryInventoryComputerInventory->rulepassed()
  inc\rule.class.php:1432                            PluginFusioninventoryInventoryRuleImport->executeActions()
  inc\rulecollection.class.php:1539                  Rule->process()
  ...ry\inc\inventorycomputerinventory.class.php:341 RuleCollection->processAllRules()
  ...ry\inc\inventorycomputerinventory.class.php:102 PluginFusioninventoryInventoryComputerInventory->sendCriteria()
  ...fusioninventory\inc\communication.class.php:227 PluginFusioninventoryInventoryComputerInventory->import()
  ...fusioninventory\inc\communication.class.php:461 PluginFusioninventoryCommunication->import()
  plugins\fusioninventory\front\communication.php:93 PluginFusioninventoryCommunication->handleOCSCommunication()
  plugins\fusioninventory\index.php:59               include_once()
  {"user":"2442@GLPI02","mem_usage":"0.001\", 5.92Mio)"}

**Comment by cedric-anne** [comment]
Hi,

Stacktrace shown that this bug comes from FusionInventory plugin. Please open an issue on plugin github repository.

Regards
