### ISSUE TITLE
glpi 9.4.3: ticketrecurrent doesn't work

### ISSUE THREAD

**Issue by dbegit** [glpi-project/glpi#6264]
Hello,

ticketrecurrent doesn't work on glpi 9.4.3
In cron.log I see :
2019-09-09 14:45:01 [@srvglp45]
Externe #1 : Démarrage ticketrecurrent"

In php-errors.log, I don't see errors about ticketrecurrent or cron.

How to debug this?
Thanks for your help.

**Comment by flegastelois** [comment]
Internal ticket 17755.

**Comment by flegastelois** [comment]
Linked to (maybe duplicate) #6205

**Comment by cedric-anne** [comment]
Hi @dbegit  ,

Could you try the fix from #6275 ?

Regards

**Comment by meuced** [comment]
Hi,

I have the same problem. How can I test your fix ? I'm not familiar with gh.

Thanks.

**Comment by meuced** [comment]
It's OK for the test, sorry.

Here is another problem, perhaps same than initial issue (same problem with your fix) :
- create a new recurrent ticket with a periodicity of 1 hour or day (or 2 hours, etc. but not with month or year)
- In table glpi_ticketrecurrents, next_creation_date is NULL
- If you change periodicity from 1 hour to 1 MONTH, next_creation_date is now OK

Regards.

**Comment by cedric-anne** [comment]
> It's OK for the test, sorry.
> 
> Here is another problem, perhaps same than initial issue (same problem with your fix) :
> 
> * create a new recurrent ticket with a periodicity of 1 hour or day (or 2 hours, etc. but not with month or year)
> * In table glpi_ticketrecurrents, next_creation_date is NULL
> * If you change periodicity from 1 hour to 1 MONTH, next_creation_date is now OK
> 
> Regards.

I think this is related to another bug, see https://github.com/glpi-project/glpi/pull/6144

**Comment by meuced** [comment]
> > It's OK for the test, sorry.
> > Here is another problem, perhaps same than initial issue (same problem with your fix) :
> > 
> > * create a new recurrent ticket with a periodicity of 1 hour or day (or 2 hours, etc. but not with month or year)
> > * In table glpi_ticketrecurrents, next_creation_date is NULL
> > * If you change periodicity from 1 hour to 1 MONTH, next_creation_date is now OK
> > 
> > Regards.
> 
> I think this is related to another bug, see #6144

Yes that's it ! #6144 did the job, and #6275 fix another bug i had too.
Thanks !
