### ISSUE TITLE
simcard management access

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#6276]
Since integration of simcard plugin, we have a lot of complaints about the menu access of simcards list.

Previously the plugin inserts the link directly into assets menu.
After the integration, we decide to identify simcards as components and so they are available in 
Setup > Components > Simcards

We have two list in fact, 
- DeviceSimcard -> model of simcard
- Item_DeviceSimcard -> real simcard, kind of instance of previous class

The first one should stay in Components list, i think.
We should decide what to do with the second class.
More globally, do we need to push All Item_DeviceXxx to a more accessible menu ?

**Comment by btry** [comment]
Hi

I link here a feedback from a user https://github.com/pluginsGLPI/simcard/pull/70
