### ISSUE TITLE
auto-detect good profil

### ISSUE THREAD

**Issue by beudbeud** [glpi-project/glpi#628]
Hi have a bug with one install of GLPI.

If a people have two profile :

first entity is techicinan and in second entity is self-service and the default entitu is the one with technician profile.

if the people open a ticket in the second entity. But when he try to clic on the url in notification mail. the people got access denied because he got default profile.

I think it need auto check all profile for find the good one for access

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
