### ISSUE TITLE
see private tasks option unchecked, profile can't see tickets list on the tickets page

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#6288]
**Describe the bug**

Hi,
With this commit b052d61 applied on _search.class.php_ part of a 9.4.3
If a profile don't have the "see private tasks option checked" the user that use this profile can't see tickets list on the tickets page.
Just no results at all on the page.
Without this commit, all is fine again.

**Page(s) URL**

_/front/ticket.php_

**To reproduce**
![Screenshot_2019-09-11 GLPI - Profils - 9(1)](https://user-images.githubusercontent.com/1380639/64677929-d10d8900-d478-11e9-9fe4-7e9eee4904bc.png)

1. Go to a profile set it like the screen above and confirm that the "see private tasks option" is unchecked.
2. Assign this profile to your own account, and use it.
3. Go to _/front/ticket.php_
4. You should see the ticket list.
5. Now apply the b052d61
6. Refresh or change your profile once to any other then back to the test one.
7. Go to _/front/ticket.php_
8. Ticket list is empty.

**Expected behavior**

We should see the ticket list whatever the "see private tasks option" checked or not.

**Logs**

```
no error log for this and nothing with debug
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.3 PHP 7.3.9 + Opcache + APCu 5.1.17 under Litespeed | 10.2.26-MariaDB
```

**Comment by trasher** [comment]
I do not reproduce with an up to date 9.4/bugfixes branch, please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

**Comment by trasher** [comment]
I still do not reproduce.

**Comment by M-Falken** [comment]
Ok, I give up on this one for now.
I suspect a specific modified plugin to interfere.
So I will wait the next official release then I'll do a new bunch of tests at this time.
Thanks for the time.
