### ISSUE TITLE
Drop usage of tecnickcom/TCPDF lib

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#6300]
According to lib author, "tecnickcom/TCPDF" is not maintained anymore and should be replaced by  "tecnickcom/tc-lib-pdf". Also, it looks like the only dependency (on GLPI 9.5+) we have that uses PHP mcrypt extension that has been [deprecated in PHP 7.1](https://www.php.net/manual/en/migration71.deprecated.php#migration71.deprecated.ext-mcrypt) and [dropped from core package in PHP 7.2](https://www.php.net/manual/en/migration72.other-changes.php#migration72.other-changes.mcrypt).

However, this new "tecnickcom/tc-lib-pdf" lib is still under development and there is no release date available for it. Thus, as it has been completely rewritten, we will have to rewrite all the code related to its usage.

So maybe we should consider moving to another lib for PDF generation.

**Comment by remicollet** [comment]
For now: https://github.com/tecnickcom/TCPDF/pull/134

**Comment by cedric-anne** [comment]
> For now: [tecnickcom/TCPDF#134](https://github.com/tecnickcom/TCPDF/pull/134)

Thanks.

**Comment by remicollet** [comment]
TCPDF version 6.3.0 is released, and supports PHP 7.4.0

**Comment by remicollet** [comment]
But probably need to wait for 6.3.1 ;)

https://github.com/tecnickcom/TCPDF/pull/135
https://github.com/tecnickcom/TCPDF/pull/136

**Comment by remicollet** [comment]
TCPDF version 6.3.1 is released, and now really supports PHP 7.4.0

**Comment by trasher** [comment]
Great, once again, thanks for your job ;)

**Comment by cedric-anne** [comment]
I searched for alternatives to technicom/TCPDF but I did not find a library corresponding to all these criteria:
 - compatible with GLPI license,
 - actively supported,
 - well coded,
 - easy to use.

So I close this issue.
