### ISSUE TITLE
LDAP User picture deleted on sync

### ISSUE THREAD

**Issue by jackburton79** [glpi-project/glpi#6301]
Version 9.4.3
Users authentication is done via LDAP.

If I add a picture to an user manually, the next time he authenticates, the picture is lost (probably because in LDAP there is no picture).
It should not delete the locally added picture if there is none in LDAP.
![immagine](https://user-images.githubusercontent.com/3501519/64801429-c93d0a00-d588-11e9-87af-cd0a941abae4.png)

**Comment by cedric-anne** [comment]
Hi,

Can you confirm it is fixed by #6131 ?

Regards

**Comment by jackburton79** [comment]
> 
> 
> Hi,
> 
> Can you confirm it is fixed by #6131 ?
> 
> Regards

Yes! Thank you!
