### ISSUE TITLE
I can not identify myself

### ISSUE THREAD

**Issue by virtazp** [glpi-project/glpi#6307]
Hello,

I installed GLPI 9.4.3, on a debian 9 VM with nginx.
I can not connect with glpi / glpi, normal / normal, etc.
I have the message "username or password empty".
However, sometimes I can connect with and sometimes not.
Do you have an idea ?

thank you very much!

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
