### ISSUE TITLE
SQL query error - under asset filter (also with saved bookmark)

### ISSUE THREAD

**Issue by isaconsas** [glpi-project/glpi#6316]
Hi, Simone's writing. Company I work with uses GLPI for its business.

After I'd created a private bookmark (please see the attached image), tested it (ok with retrieved data) I set it public so that other users (same profile associated) could use it too.
At this time, other users, can see the new bookmark but we noticed that:
1 - auto count doesn't show any number but '!' char
2 - once we select the saved BM no data show up but (not ever) an error message saying '-
... partial data load ...' (roughly translated from Italian).

I had a look on the log (sql-errors log). It seems that the underling sql query misses some tables in join clause (in this specific case glpi_networks). Log refers to the attached filter image.

I had a further test with user that has issue mentioned above. I simply create a different filter on printers asset that uses the network field, just to test it specifically.
It worked with retrieving data just with the AND connector but not with AND NOT (the same as attached bookmark). Don't know if relevant or related to what I've mentioned above, but maybe it could help you.

SUMMARY: something seems to be wrong when the underling dynamic query is built by the page.

Hope the explanation is clear. Please let me know otherwise. 

Best regards.
Simone

PS: I just browned some useless details in the image.

```
[2019-09-16 15:42:06] glpisqllog.ERROR: DBmysql::query() in /web/htdocs/www.visualimaging.name/home/inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_printers`.`id` AS id, 'glpi' AS currentuser,
                        `glpi_printers`.`entities_id`, `glpi_printers`.`is_recursive`,  `glpi_printers`.`name` AS `ITEM_Printer_1`,
                        `glpi_printers`.`id` AS `ITEM_Printer_1_id`,
                        `glpi_entities`.`completename` AS `ITEM_Printer_80`,  `glpi_states`.`completename` AS `ITEM_Printer_31`,  `glpi_manufacturers`.`name` AS `ITEM_Printer_23`,  `glpi_locations`.`completename` AS `ITEM_Printer_3`,  `glpi_printertypes`.`name` AS `ITEM_Printer_4`,  `glpi_printermodels`.`name` AS `ITEM_Printer_40`,  `glpi_printers`.`date_mod` AS `ITEM_Printer_19`,  `glpi_printers`.`serial` AS `ITEM_Printer_5`,  `glpi_printers`.`otherserial` AS `ITEM_Printer_6` FROM `glpi_printers`LEFT JOIN `glpi_entities` 
                                          ON (`glpi_printers`.`entities_id` = `glpi_entities`.`id`
                                              )LEFT JOIN `glpi_states` 
                                          ON (`glpi_printers`.`states_id` = `glpi_states`.`id`
                                              )LEFT JOIN `glpi_manufacturers` 
                                          ON (`glpi_printers`.`manufacturers_id` = `glpi_manufacturers`.`id`
                                              )LEFT JOIN `glpi_locations` 
                                          ON (`glpi_printers`.`locations_id` = `glpi_locations`.`id`
                                              )LEFT JOIN `glpi_printertypes` 
                                          ON (`glpi_printers`.`printertypes_id` = `glpi_printertypes`.`id`
                                              )LEFT JOIN `glpi_printermodels` 
                                          ON (`glpi_printers`.`printermodels_id` = `glpi_printermodels`.`id`
                                              ) WHERE  `glpi_printers`.`is_deleted` = 0  AND `glpi_printers`.`is_template` = 0  AND (    (`glpi_entities`.`id` = '8') AND (   (`glpi_states`.`id` = '0' OR `glpi_states`.`id` IS NULL)  OR (`glpi_states`.`id` = '16')) AND (   (`glpi_printertypes`.`id` = '1')  OR (`glpi_printertypes`.`id` = '5'))  AND (`glpi_networks`.`id` <> '3' OR `glpi_networks`.`id` IS NULL) AND (   (`glpi_locations`.`id` NOT IN ('655','339') OR `glpi_locations`.`id` IS NULL)  AND ((`glpi_locations`.`completename` NOT LIKE '%assago%'  OR `glpi_locations`.`completename` IS NULL) )) AND (  (   ((`glpi_printers`.`name` NOT LIKE '%245%'  OR `glpi_printers`.`name` IS NULL) ) AND `glpi_infocoms`.`inventory_date` < '2018-09-16') OR (  (   (`glpi_printers`.`name`  LIKE '%245%'  )  OR (`glpi_networks`.`name`  LIKE '%2 INT%'  )) AND `glpi_infocoms`.`inventory_date` < '2019-03-16')) ) ORDER BY `id` 
  Error: Unknown column 'glpi_networks.id' in 'where clause'
  Backtrace :
  inc/search.class.php:1191                          
  inc/savedsearch.class.php:1401                     Search::constructData()
  inc/savedsearch.class.php:937                      SavedSearch->execute()
  inc/savedsearch.class.php:809                      SavedSearch->displaySavedSearchType()
  ajax/savedsearch.php:108                           SavedSearch->displayMine()
```

Information about system installation and configuration
--
[code]   GLPI 9.4.2  Installation mode: TARBALL

Operating system: Linux webxc226s03.ad.aruba.it 3.10.0-862.3.2.el7.x86_64 #1 SMP Mon May 21 23:36:36 UTC 2018 x86_64 PHP 7.2.17 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, SourceGuardian, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, ionCube Loader, json, libxml, mbstring, 	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, propro, raphf, session, soap, sqlite3, standard, tidy, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="900" memory_limit="256M" post_max_size="30M" safe_mode="" session.save_handler="files" 	upload_max_filesize="50M"  Software: Apache () 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36 Server Software: Percona Server (GPL), Release 86.0, Revision eba1b3f 	Server Version: 5.6.44-86.0-log 	Server SQL Mode:  	Parameters: Sql(omissis)@89.46.111.72/Sql1247384_1 	Host info: 89.46.111.72 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed imap extension is installed xmlrpc extension is installed exif extension is installed ldap extension is not present Zend OPcache extension is not present APCu extension is not present CAS extension is not present Database version seems correct (5.6.44) - Perfect! 

File permissions are all OK.
![Screen Shot 2019-09-16 at 17 09 15](https://user-images.githubusercontent.com/48152775/64991349-03344600-d8d2-11e9-87e6-a02c3a4beebb.png)

**Comment by trasher** [comment]
You should try with latest release, many things have changed since 9.4.2

**Comment by trasher** [comment]
No feedback from a while, closing.
