### ISSUE TITLE
"MySQL query error" when create\delete task in project.

### ISSUE THREAD

**Issue by kittkott** [glpi-project/glpi#6317]
glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 188
*** MySQL query error:
SQL: SELECT * FROM `glpi_items_projects` WHERE `projecttasks_id` = '7'
Error: Unknown column 'projecttasks_id' in 'where clause'
Backtrace :
inc/dbmysqliterator.class.php:95
inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
inc/dbutils.class.php:433                          DBmysql->request()
inc/db.function.php:238                            DbUtils->getAllDataFromTable()
inc/notificationtargetprojecttask.class.php:442    getAllDatasFromTable()
inc/notificationtarget.class.php:1236              NotificationTargetProjectTask->addDataForTemplate()
inc/notificationtemplate.class.php:253             NotificationTarget->getForTemplate()
inc/notificationeventabstract.class.php:108        NotificationTemplate->getTemplateByLanguage()
inc/notificationevent.class.php:163                NotificationEventAbstract::raise()
inc/projecttask.class.php:291                      NotificationEvent::raiseEvent()
inc/commondbtm.class.php:1672                      ProjectTask->pre_deleteItem()
front/projecttask.form.php:69                      CommonDBTM->delete()
{"user":"6@glpi.ptslab.int"}

1. Go to 'Project -> select any project -> select project task'
2. Click on 'add task'
3. See error in /var/log/glpi/sql-errors.log

**Expected behavior**
No error on log? 

**Logs**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.4.3 ( => /var/www/glpi)
Installation mode: TARBALL

Server

Operating system: Linux glpi.ptslab.int 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64
PHP 7.2.19-0ubuntu0.18.04.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at glpi.ptslab.int Port 443)
	Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0
Server Software: (Ubuntu)
	Server Version: 5.7.27-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (5.7.27) - Perfect!
OK/var/log/glpi : OK
OK/etc/glpi/config/ : OK
OK/var/lib/glpi/files/ : OK
OK/var/lib/glpi/files//_dumps : OK
OK/var/lib/glpi/files//_sessions : OK
OK/var/lib/glpi/files//_cron : OK
OK/var/lib/glpi/files//_graphs : OK
OK/var/lib/glpi/files//_lock : OK
OK/var/lib/glpi/files//_plugins : OK
OK/var/lib/glpi/files//_tmp : OK
OK/var/lib/glpi/files//_cache : OK
OK/var/lib/glpi/files//_rss : OK
OK/var/lib/glpi/files//_uploads : OK
OK/var/lib/glpi/files//_pictures : OK

Libraries
 
htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.3 in (/usr/share/php)

**Comment by cedric-anne** [comment]
Hi,

Thanks for your report.

I confirm the bug.

We'll fix it in a future release, if you'd like to help us produce a fix faster: subscribe to GLPI Network at https://services.glpi-network.com

Kind regards,
