### ISSUE TITLE
Cant Assign (phone)line to phone

### ISSUE THREAD

**Issue by Megachip** [glpi-project/glpi#6330]
Did I missed something or how can I assign a (phone)line to a phone?

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by Megachip** [comment]
@trasher seems bug reports and feature requests will be ignored there. 

https://glpi.userecho.com/communities/1/topics/963-how-to-assign-lines-to-phones
https://forum.glpi-project.org/viewtopic.php?pid=368223

Maybe the answer is not possible? But this makes absolutely no sense :/

**Comment by trasher** [comment]
Use github issues for bugs only. For questions, ask the forums; and for new features, post to userecho.

**Comment by Megachip** [comment]
@trasher did ;) But this feels like a bug. I've a phone and a phone line, but can't connect it. But maybe it never worked. So yeah, in this case it will be a feature request.
