### ISSUE TITLE
 Problem with font in ticket description

### ISSUE THREAD

**Issue by albercuba** [glpi-project/glpi#6333]
Hello everyone,

for some reason the font in my tickets description is wrong.

When I check the code it reads:

`font-family: ';Lato';`

instead of:

`font-family: 'Lato';`

The font is installed in the server and in my computer.

When I try to add:

```
p.MsoNormal {
    font-size: 10.0pt;
    font-family: 'Lato';
    color: black;
}
```

to my **glpi/css/styles.scss**, it doesn't work.

And I do not find any file defining **p.MsoNormal** which is the class containing my variable.

![grafik](https://user-images.githubusercontent.com/11768756/65309585-ae702400-db8c-11e9-90c4-0daf51636056.png)

Any idea how to fix this?

**Comment by trasher** [comment]
Probably a cache issue. 
Please use [forums](http://forum.glpi-project.org) to get support.
