### ISSUE TITLE
Move assets from one category to another

### ISSUE THREAD

**Issue by albercuba** [glpi-project/glpi#6337]
It would be nice to be able to change the asset's category.

Example:

My SMTP discovery task detects my Sophos UTM devices but registers them under **Assets - Computers** instead of under **Assets - Netwok devices** and there is no option to move them from **Computers** to **Network devices**. But if I have an asset under **Network devices**, I can move it to **Computers**

Best regards

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.

**Comment by Kastet85** [comment]
Hello!
The link https://suggest.glpi-project.org/ doesn't work.
Please tell me what is the current address for FRE?

**Comment by cedric-anne** [comment]
Hello,

Link has been fixed. 

Regards
