### ISSUE TITLE
Could not bound a contract with several elements

### ISSUE THREAD

**Issue by monpelaud** [glpi-project/glpi#634]
Hello,
For some contracts I can't add links to several elements. The box " Ajout d'un élément " is not displayed on screen.
This problem seems to be specific to the newly created contracts with 0.9.0.x version of GLPI.
Screen for old contracts:
![capture02](https://cloud.githubusercontent.com/assets/16806004/14956258/0ace3dae-107f-11e6-921e-cd83776c1af1.JPG)

Screen for new contracts without "Ajout d'un élément" box and "Ajouter" button:
![capture01](https://cloud.githubusercontent.com/assets/16806004/14956281/2a0fe730-107f-11e6-880e-e8bc3904d0cd.JPG)

Best Regards

**Comment by wawax** [comment]
Hello,

how many items can be associated with the contract (as defined in the contract's main form) ?

**Comment by monpelaud** [comment]
Thanks for your quick reply,

Sorry, I did not see this parameter in the contract's main form.
I set it to "Unlimitted" and all works well.
I close this issue.

Many thanks
