### ISSUE TITLE
users can (not) update API Token

### ISSUE THREAD

**Issue by manugre** [glpi-project/glpi#6343]
GLPI 9.4.3

Even if user are not allow to modify their password, they can modify their user token.
This is strang,

To prevent this, I update the code like this : (in the "user pref update part" of GLPI 
file inc/user.class.php
I add line 2648 :  if ($this->can($ID, UPDATE)) {
and close line 2686 : }

This is excatly the same code line 2278 ->2329

**Comment by ADN45** [comment]
No comprendo?

**Comment by manugre** [comment]
The problem :
When a user IS NOT ALLOW to update his password, he IS ABLE to update his api token (and his personnal token).
This is not logic.

**Comment by ADN45** [comment]
What schould I do?

**Comment by manugre** [comment]
don't allow users to update thier token if they are not allow to update their password
