### ISSUE TITLE
TAG in ticket comment

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#6351]
Hi,

**Describe the bug**
When you add a comment in a ticket like this :"<azerty>TEST</azerty>" , 
The tag is interpreted as Html tag and desapear from the comment.

**Expected behavior**
The comment with the tag not interpreted : "<azerty>TEST</azerty>"

Probleme reproduce in GLPI 9.4.3 and bellow

Br.

**Comment by orthagh** [comment]
use \` to share code snippets in markdown

**Comment by trasher** [comment]
This is an aready known issue, I'm pretty sure there are already tickets about it.

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/140
