### ISSUE TITLE
"Failed to resize image (auto_orient)"

### ISSUE THREAD

**Issue by lackmannbg** [glpi-project/glpi#6355]
Hi,

I try to upload a image from my profile, but can't. Appears this message error:

"Failed to resize image (auto_orient)"

The same message appears when I want to attach an image to the ticket.

We are using GLPI v. 9.4.4

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided. We do not have enough details to reproduce nor understand the issue.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by maravtdm** [comment]
Check your permission on your [...]/_tmp directory
it must be 777

**Comment by assistenzait** [comment]
Sorry, on GLPI, after update glpi from 9.4.3 to 9.4.4 release, I've the same problem:

1 - The permissioni on mu [...]/_tmp directory is 777
2 - php accept upload files 8M max
3 - Jpg-jpeg files are defined in "Document Type".

Error is only about jpg files (png and gif correctly work) and only when I try to copy the jpg file inside the "Description" . If I choose Browse files it's ok.

The error is this:

1. PHP Warning: imagecreatefrompng(): '/var/www/html/glpi/files/_tmp/5dd50e3c1d15e9.08594513image_paste9906678.png' is not a valid PNG file in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 596
2. PHP Warning: imagesx() expects parameter 1 to be resource, boolean given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 756
3. PHP Warning: imagesy() expects parameter 1 to be resource, boolean given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 757
4. PHP Warning: Division by zero in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 765
5. PHP Warning: Division by zero in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 766
6. PHP Warning: imagecreatetruecolor() expects parameter 1 to be integer, float given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 782
7. PHP Warning: imagecolorallocate() expects parameter 1 to be resource, null given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 799
8. PHP Warning: imagecolortransparent() expects parameter 1 to be resource, null given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 799
9. PHP Warning: imagealphablending() expects parameter 1 to be resource, null given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 801
10. PHP Warning: imagesavealpha() expects parameter 1 to be resource, null given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 802
11. PHP Warning: imagecopyresampled() expects parameter 1 to be resource, null given in /var/www/html/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 815
12. 

Thank you 

Gian Paolo

**Comment by starlab-IT** [comment]
It's happening the same to me. It only allows me when attaching a png but with jpeg, I get this:

PHP Warning: imagecreatefrompng(): '/data/www/glpi/files/_tmp/5dd7b32b18d443.68621131image_paste8167105.png' is not a valid PNG file in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 596
PHP Warning: imagesx() expects parameter 1 to be resource, boolean given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 756
PHP Warning: imagesy() expects parameter 1 to be resource, boolean given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 757
PHP Warning: Division by zero in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 765
PHP Warning: Division by zero in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 766
PHP Warning: imagecreatetruecolor() expects parameter 1 to be integer, float given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 782
PHP Warning: imagecolorallocate() expects parameter 1 to be resource, null given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 799
PHP Warning: imagecolortransparent() expects parameter 1 to be resource, null given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 799
PHP Warning: imagealphablending() expects parameter 1 to be resource, null given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 801
PHP Warning: imagesavealpha() expects parameter 1 to be resource, null given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 802
PHP Warning: imagecopyresampled() expects parameter 1 to be resource, null given in /data/www/glpi/lib/jqueryplugins/jquery-file-upload/server/php/UploadHandler.php at line 815
{"filename":[{"name":"5dd7b32b18d443.68621131image_paste8167105.png","size":2307228,"type":"image\/png","url":"http:\/\/helpdesk.stne.com\/ajax\/files\/5dd7b32b18d443.68621131image_paste8167105.png","error":"Failed to resize image (auto_orient)","deleteUrl":"http:\/\/helpdesk.stne.com\/ajax\/fileupload.php?filenam=5dd7b32b18d443.68621131image_paste8167105.png","deleteType":"DELETE","id":"docfilename38818771"}]}

Any help would be greatly appreciated!

Thanks :)

**Comment by cedric-anne** [comment]
I confirm the bug.

To reproduce, simply drop a jpeg file into a rich text field.

**Comment by cedric-anne** [comment]
Hi,

#6625 should solve this bug.

Regards

**Comment by assistenzait** [comment]
Hi, I confirm that this bug is solved for me too.

Regards
