### ISSUE TITLE
Prohibit ticket creation on root entity

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#636]
Hello

I have looked for a solution but not find it.

Please could you tell me how to prohibit ticket creation on root entity.

Thank you very much

It was already asked

http://forum.glpi-project.org/viewtopic.php?id=34773

**Comment by remicollet** [comment]
Don't give right on this entity, but only on sub-entities

**Comment by remicollet** [comment]
Closing as not a bug

**Comment by satyan01** [comment]
Hello,

For technicians, to see tickets of all entities they need to see all subentities without changing entities at each time.

**Comment by yllen** [comment]
As remicollet said, you must give right on each sub-entities.
This is not an issue but a feature already refused by the community.
