### ISSUE TITLE
 Exchange Online (Office 365) - failed email test

### ISSUE THREAD

**Issue by kchassaing** [glpi-project/glpi#6363]
Hello.
My company migrated the mail server to an online exchange.
The new SMTP host is of type domain-fr.mail.protection.outlook.com.
When I make the SMTP host switch in Glpi I replace the old server ip by this address in Configuration - Notifications - Setting up Email Notifications.
Once saved the conf I click on "Send a test email to the administrator" and the sending error appears.
I do not have a mail log file in "\var\lib\www\glpi\files\ _log", so I have absolutely no idea where the problem may come from.
Thank you for your help.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.
