### ISSUE TITLE
Can't open master version

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#639]
On firefox
_Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log._

On apache log
_[Fri May 06 09:32:51 2016] [alert] [client ::1] /home/yllen/gitsvn/.htaccess: ExpiresActive not allowed here
[Fri May 06 09:34:44 2016] [alert] [client ::1] /home/yllen/gitsvn/.htaccess: ExpiresByType not allowed here_

Due to this post 
https://github.com/glpi-project/glpi/commit/6891853ba3d69b5b7031fe1f03a68d58ded7de34

**Comment by orthagh** [comment]
You opened discussion on the specified commit 
https://github.com/glpi-project/glpi/commit/6891853ba3d69b5b7031fe1f03a68d58ded7de34

I asked you : "How is your AllowOverride directive in your apache ?"

Since 9.1, you can't install glpi without altering this directive
