### ISSUE TITLE
Error  unknown column 'glpi_itilfollowups.date' in 'field list'

### ISSUE THREAD

**Issue by cp61** [glpi-project/glpi#6390]
**Describe the bug**

The Ticket tab for users in Post Only no longer displays open tickets

The sql-errors.log log returns the Error: Unknown column 'glpi_itilfollowups.date' in 'field list' (see log below)

**Page(s) URL**

glpi/front/ticket.php

**To reproduce**

1. Go to /glpi/front/ticket.php
2. no open ticket appears

**Expected behavior**

the tickets opened by the user should appear

**Logs**

Log de sql-errors.log

[2019-10-01 17:22:49] glpisqllog.ERROR: DBmysql::query() in C:\xampp\htdocs\glpi\inc\dbmysql.class.php line 188
*** MySQL query error:
SQL: SELECT DISTINCT glpi_tickets.id AS id, 'ocsinventoryng' AS currentuser,
glpi_tickets.id AS ITEM_Ticket_2, glpi_tickets.name AS ITEM_Ticket_1,
glpi_tickets.id AS ITEM_Ticket_1_id,
glpi_tickets.id AS ITEM_Ticket_1_id, glpi_tickets.content AS ITEM_Ticket_1_content, glpi_tickets.status AS ITEM_Ticket_1_status, glpi_tickets.status AS ITEM_Ticket_12, glpi_tickets.date AS ITEM_Ticket_15, glpi_tickets.date_mod AS ITEM_Ticket_19, GROUP_CONCAT(DISTINCT glpi_users_a5e2026cbcb683e774f93a59e24a62a4.id SEPARATOR '$$##$$')
AS ITEM_Ticket_4,
GROUP_CONCAT(DISTINCT CONCAT(glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60.users_id, ' ',
glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60.alternative_email)
SEPARATOR '$$##$$') AS ITEM_Ticket_4_2,
GROUP_CONCAT(DISTINCT glpi_users_f201be21cd638ee780d08cba4ceff0d4.id SEPARATOR '$$##$$')
AS ITEM_Ticket_5,
GROUP_CONCAT(DISTINCT CONCAT(glpi_tickets_users_819efb92c8b927b345e489211ec8e43b.users_id, ' ',
glpi_tickets_users_819efb92c8b927b345e489211ec8e43b.alternative_email)
SEPARATOR '$$##$$') AS ITEM_Ticket_5_2,
glpi_itilcategories.completename AS ITEM_Ticket_7, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5.content, 'NULL'),
'$#$',glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5.id)
ORDER BY glpi_itilfollowups.date DESC
SEPARATOR '$$##$$')
AS ITEM_Ticket_25 FROM glpi_tickets LEFT JOIN glpi_tickets_users AS glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60
ON (glpi_tickets.id = glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60.tickets_id
AND glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60.type = 1 ) LEFT JOIN glpi_tickets_users AS glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8
ON (glpi_tickets.id = glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8.tickets_id
AND glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8.type = 3 ) LEFT JOIN glpi_groups_tickets AS glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8
ON (glpi_tickets.id = glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8.tickets_id
AND glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8.type = 3 ) LEFT JOIN glpi_tickets_users AS glpi_tickets_users_819efb92c8b927b345e489211ec8e43b
ON (glpi_tickets.id = glpi_tickets_users_819efb92c8b927b345e489211ec8e43b.tickets_id
AND glpi_tickets_users_819efb92c8b927b345e489211ec8e43b.type = 2 ) LEFT JOIN glpi_groups_tickets AS glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b
ON (glpi_tickets.id = glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b.tickets_id
AND glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b.type = 2 )LEFT JOIN glpi_users AS glpi_users_a5e2026cbcb683e774f93a59e24a62a4
ON (glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60.users_id = glpi_users_a5e2026cbcb683e774f93a59e24a62a4.id
)LEFT JOIN glpi_users AS glpi_users_f201be21cd638ee780d08cba4ceff0d4
ON (glpi_tickets_users_819efb92c8b927b345e489211ec8e43b.users_id = glpi_users_f201be21cd638ee780d08cba4ceff0d4.id
)LEFT JOIN glpi_itilcategories
ON (glpi_tickets.itilcategories_id = glpi_itilcategories.id
) LEFT JOIN glpi_itilfollowups AS glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5
ON (glpi_tickets.id = glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5.items_id
AND glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5.itemtype = 'Ticket'
AND (glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5.is_private = 0
OR glpi_itilfollowups_66b94b1bca2cb3afd58d60e14dc821d5.users_id = '9') ) WHERE ( glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60.users_id = '9'
OR glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8.users_id = '9'
OR glpi_tickets.users_id_recipient = '9') AND glpi_tickets.is_deleted = 0 AND ( glpi_tickets.status IN ('2') ) GROUP BY glpi_tickets.id ORDER BY ITEM_Ticket_19 DESC
Error: Unknown column 'glpi_itilfollowups.date' in 'field list'
Backtrace :
inc\search.class.php:1246
inc\search.class.php:98 Search::constructData()
inc\search.class.php:80 Search::showList()
front\ticket.php:45 Search::show()

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Informations sur le système, l'installation et la configuration

[code]
 
GLPI 9.4.4 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

Server

 
Operating system: Windows NT SRV-SIC 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
PHP 7.1.11 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, wddx, xml, xmlreader,
	xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache/2.4.29 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2l PHP/7.1.11 (Apache/2.4.29 (Win32) mod_authnz_sspi/0.1.0
	OpenSSL/1.0.2l PHP/7.1.11 Server at srv-sic Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0
Server Software: mariadb.org binary distribution
	Server Version: 10.1.28-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: localhost via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (10.1.28) - Perfect!Database version seems correct (10.1.28) - Perfect!
OKC:\xampp\htdocs\glpi/files/_log : OK
OKC:\xampp\htdocs\glpi/config : OK
OKC:\xampp\htdocs\glpi/files : OK
OKC:\xampp\htdocs\glpi/files/_dumps : OK
OKC:\xampp\htdocs\glpi/files/_sessions : OK
OKC:\xampp\htdocs\glpi/files/_cron : OK
OKC:\xampp\htdocs\glpi/files/_graphs : OK
OKC:\xampp\htdocs\glpi/files/_lock : OK
OKC:\xampp\htdocs\glpi/files/_plugins : OK
OKC:\xampp\htdocs\glpi/files/_tmp : OK
OKC:\xampp\htdocs\glpi/files/_cache : OK
OKC:\xampp\htdocs\glpi/files/_rss : OK
OKC:\xampp\htdocs\glpi/files/_uploads : OK
OKC:\xampp\htdocs\glpi/files/_pictures : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

Libraries

 
htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed)
phpmailer/phpmailer version 6.0.7 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src)
simplepie/simplepie version 1.5.2 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library)
tecnickcom/tcpdf version 6.2.26 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf)
michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf)
true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src)
iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib)
zendframework/zend-cache in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-cache\src)
zendframework/zend-i18n in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-i18n\src)
zendframework/zend-serializer in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-serializer\src)
monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog)
sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src)
elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src)
symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console)
leafo/scssphp in (C:\xampp\htdocs\glpi\vendor\leafo\scssphp\src)

SQL replicas

 
Not active

Notifications

 

Mails receivers

 

Plugins list

 
	news                 Name: Alertes                        Version: 1.5.4      State: Enabled
	escalade             Name: Escalades                      Version: 2.4.4      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled

OCS Inventory NG
Host: 10.61.7.103
Connection: Ok
Use the OCSNG software dictionary: No
[/code]

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.
Message is no in english.

**Comment by cp61** [comment]
Edited in english

**Comment by trasher** [comment]
Informations are still missing.

**Comment by cp61** [comment]
Edited
