### ISSUE TITLE
[GLPi 9.4.4]Global search not working 

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#6396]
Hello i just upgrade  9.2.1 to 9.4.4.

And now i cant do a global search from tickets :

![image](https://user-images.githubusercontent.com/55700796/66139255-60cdcf80-e600-11e9-9df0-2487289e489c.png)

And from sql-errors.log, i got this error : 

glpisqllog.ERROR: DBmysql::query() in /var/www/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
......
Error: Unknown column 'glpi_users.realname' in 'where clause'
  Backtrace :
  inc/search.class.php:1246                          
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  front/ticket.php:45                                Search::show()

But the column exist : 
desc glpi_users;
...
| realname                       | varchar(255) | YES  | MUL | NULL    |                |

Can you help me what is wrong ?

**Comment by cconard96** [comment]
Please test with #6388
Patch:
https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/6388.patch

**Comment by kevin-m87** [comment]
Edited file inc/search.class.php, modifications not working global search "all" from tickets not working

**Comment by cconard96** [comment]
Could also be related to #6390 if follow-ups or tasks are visible

**Comment by kevin-m87** [comment]
Still not working

**Comment by cconard96** [comment]
I cannot recreate the issue. Please show the full query from sql-errors.

**Comment by yllen** [comment]
I confirm the bug.
You can reproduce it by display any actor column
Error in SQL in field list and in where list:
Unknown column 'glpi_users_users_id_recipient.name' in 'field list'
Unknown column 'glpi_users_users_id_lastupdater.firstname' in 'where clause'
....
Bug introduce by https://github.com/glpi-project/glpi/commit/cc63e97d618f4fd179ac1aa620766c47c3f80be2#diff-a801c52129f44d50ab6d1db9f049c4b7

**Comment by mklimasz5** [comment]
I can confirm that 9.4.4 also doesn't like complex searches (tried: Changes -> "Not solved" + Approver -> selected person) yelds zero results (thou appropriate record exists) and SQL returns known error: "Unknown column 'glpi_users_users_id_validate_2d1730155923788fd500e852fa06caeb.realname' in 'where clause'". It seem to be a repeateable pattern for searching in various places (#6388, #6399, #6397)

**Comment by trasher** [comment]
This duplicates https://github.com/glpi-project/glpi/issues/6397
