### ISSUE TITLE
[GLPi 9.4.4]Global search problem

### ISSUE THREAD

**Issue by cmiscloni** [glpi-project/glpi#6398]
- Just after migration from 9.4.3 to 9.4.4, searching, for example for a computer in the default view (Visualized elements), doesn't work anymore.
- We have to select a different characteristic (name of computer) to make it works again
- The visualized view contain of course the name of the computer.
- No error returned even with debug mode.

On a French GLPI installation
Tested with change the language to English too.

![image](https://user-images.githubusercontent.com/4446733/66154724-6803d600-e61e-11e9-96ff-2020799ed52f.png)

**Comment by cconard96** [comment]
Please test with #6388
Patch:
https://patch-diff.githubusercontent.com/raw/glpi-project/glpi/pull/6388.patch

**Comment by cmiscloni** [comment]
Ok for me, thanks

**Comment by trasher** [comment]
https://github.com/glpi-project/glpi/pull/6388 merged
