### ISSUE TITLE
Constitution of location from LDAP for user form

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#640]
http://glpi.userecho.com/topics/31-active-directory-fields-synchronization/

Done for location

**Comment by wawax** [comment]
Hi Yllen,

In this case it means that all locations are going to root entity. It is really what we want ?
Imagine in a multi entity environment, it means that all locations will be visible in all entities.
It seems to me quite painfull to manage and quite dangerous.

**Comment by remicollet** [comment]
> In this case it means that all locations are going to root entity. It is really what we want ?

Entity is not defined at this point, so this seems to be the only way.
This is a limitation of this feature, but as it is asked by various users...

**Comment by yllen** [comment]
When you import a new user, this user goes in the root entity. His affectation to a special entity depend of the profile assigned to this entity.
