### ISSUE TITLE
Import document with mailgate : User associated

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#641]
Version 0.90.3

When the mailgate add a document, the user which is defined is the user connected when the automatic action (mailgate - GLPI) is launched (and not the ticket Requester) - no problem with CLI 

![image](https://cloud.githubusercontent.com/assets/13178158/15107397/dd3c6ac2-15cf-11e6-975b-e8edb62d84dc.png)

**Comment by barbuslex** [comment]
+1 I have the same issue in my company environment.
This is a fairly critical problem because the person who was selected to attach the attachment receives an email notification.

**Comment by trasher** [comment]
This has been fixed in 9.2; see https://github.com/glpi-project/glpi/issues/1476
