### ISSUE TITLE
task and solution

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#642]
Hello

WHen something missing during creation in task or solution we have to fill all again because all disappear if we go back

**Comment by tyronewyatt** [comment]
Do you have glpi behaviors plugin enabled? It might be the plugin cause this issue.

**Comment by satyan01** [comment]
Yes I have

**Comment by wawax** [comment]
please open an issue on the behaviors plugin tracker.
this is a common issue related to the plugin.

Thank you

**Comment by yllen** [comment]
In Behaviors plugin there is no mandatory field for a task.
Can you deactivate this plugin a try to create a new task?

**Comment by satyan01** [comment]
unfortunately not in production.

**Comment by orthagh** [comment]
As said by other participant, it's an issue relative to behavior plugin.
I close this issue so.
