### ISSUE TITLE
[GLPI 9.4.4] new ticket and opening date

### ISSUE THREAD

**Issue by mulbzh** [glpi-project/glpi#6424]
Hello,

In GLPI 9.4.4 when we create a new ticket, "opening date" is blank by default.

So, it is not set by default the date and the hour

thanks

**Comment by jsamaniegog** [comment]
Same problem, even setting the predefined field.

**Comment by jsamaniegog** [comment]
Ok, if you don't set it as mandatory, GLPI will fill it in when you create the ticket. Before, GLPI filled it in when loading the ticket.

**Comment by mulbzh** [comment]
yes, true !

before it was not like that, it was filled when you clock on create ticket

**Comment by cedric-anne** [comment]
Hi,

Indeed, we changed this behaviour. If you leave this field blank, value will be automatically set to form submission date. You can still fill this field by yourself to change the default value.

See #4150 for explaination.

Regards
