### ISSUE TITLE
Unknown column 'glpi_tickettemplates_tickettemplates_id_incident.name'

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6425]
Hello to all !

My GLPI version is 9.4.4 migrated from 9.4.3/ubuntu.

I want to select item from http://myip/glpi/front/dropdown.php categorie de tickets

I see nothing when I enter a criteria !
In logs, I have a nice error : 
[2019-10-07 16:09:03] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_itilcategories`.`id` AS id, 'prestalb3' AS currentuser,
                        `glpi_itilcategories`.`entities_id`, `glpi_itilcategories`.`is_recursive`,  `glpi_itilcategories`.`completename` AS `ITEM_ITILCategory_1`,
                        `glpi_itilcategories`.`id` AS `ITEM_ITILCategory_1_id`,
                         `glpi_users`.`name` AS `ITEM_ITILCategory_70`,
                        `glpi_users`.`realname` AS `ITEM_ITILCategory_70_realname`,
                        `glpi_users`.`id`  AS `ITEM_ITILCategory_70_id`,
                        `glpi_users`.`firstname` AS `ITEM_ITILCategory_70_firstname`,
                        `glpi_groups`.`completename` AS `ITEM_ITILCategory_71`,   COUNT(DISTINCT `glpi_tickets`.`id`) AS `ITEM_ITILCategory_77`,
                     `glpi_tickettemplates`.`name` AS `ITEM_ITILCategory_73`,  `glpi_itilcategories`.`is_incident` AS `ITEM_ITILCategory_74`,  `glpi_itilcategories`.`is_request` AS `ITEM_ITILCategory_75` FROM `glpi_itilcategories`LEFT JOIN `glpi_users`
                                          ON (`glpi_itilcategories`.`users_id` = `glpi_users`.`id`
                                              )LEFT JOIN `glpi_groups`
                                          ON (`glpi_itilcategories`.`groups_id` = `glpi_groups`.`id`
                                              ) LEFT JOIN `glpi_tickets`
                                             ON (`glpi_itilcategories`.`id` = `glpi_tickets`.`itilcategories_id`
                                                 )LEFT JOIN `glpi_tickettemplates`
                                          ON (`glpi_itilcategories`.`tickettemplates_id_incident` = `glpi_tickettemplates`.`id`
                                              ) WHERE   (  1 )  AND (  (   (`glpi_itilcategories`.`completename`  LIKE '%TRUC%'  ) OR  (((`glpi_users`.`realname`   LIKE '%TRUC%'
                            OR `glpi_users`.`firstname`   LIKE '%TRUC%'
                            OR `glpi_users`.`name`   LIKE '%TRUC%'
                            OR CONCAT(`glpi_users`.`realname`, ' ', `glpi_users`.`firstname`)   LIKE '%TRUC%'  )
                            ) )  OR  (`glpi_groups`.`completename`  LIKE '%TRUC%'  )  OR  (`glpi_tickets`.`id`  LIKE '%TRUC%'  )  OR  (`glpi_tickettemplates_tickettemplates_id_incident`.`name`  LIKE '%TRUC%'  )  OR  (`glpi_itilcategories`.`is_incident`  LIKE '%TRUC%'  )  OR  (`glpi_itilcategories`.`is_request`  LIKE '%TRUC%'  ))  ) GROUP BY `glpi_itilcategories`.`id` ORDER BY ITEM_ITILCategory_1 ASC
  Error: Unknown column 'glpi_tickettemplates_tickettemplates_id_incident.name' in 'where clause'
  Backtrace :
  inc/search.class.php:1246
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  front/dropdown.common.php:51                       Search::show()
  front/itilcategory.php:36                          include()
  {"user":"007@srv-glpi"}

We should have the result filtered.

I saw a problem that resembles mine here https://forum.glpi-project.org/viewtopic.php?id=172963 BUT doesn't correct for me.

I have downloaded and send on my server search.class.php : 
My md5 sum 
md5sum  /var/www/html/glpi/inc/search.class.php
c6804d91f67283fddcadd0dd085a70ee  /var/www/html/glpi/inc/search.class.php
(301K oct.   4 14:47)

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/6375, fixed in https://github.com/glpi-project/glpi/pull/6388

**Comment by mab18** [comment]
Hi,
I confirm : it's corrected ;-)
