### ISSUE TITLE
[0.90.3] notification is not sent to the group

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#643]
Business rule Configuration:
![rule](https://cloud.githubusercontent.com/assets/15769828/15144240/76527f6a-16ae-11e6-88d5-058b9a57d70b.png)

Notification - Update Ticket:
![update_notification](https://cloud.githubusercontent.com/assets/15769828/15144313/e423226a-16ae-11e6-9af1-55de7018f0aa.png)

When you change the category to "Telecom" and update the ticket the notification must be sent to the group. This only works on add event.

http://glpi.userecho.com/topics/8-problem-with-rule-to-assign-technician-group/

**Comment by kabassanov** [comment]
Perhaps, it works for me. I've just created a ticket (the system added automatically a group in charge of the ticket), then I removed manually the group, sent a follow-up, and reaffected the ticket to the group. In my glpi mail logs, I can see that an email for the last modification has been sent to all members of the group...

Did you do anything in a different manner?

**Comment by jsamaniegog** [comment]
The rule works in both cases. The problem is when you create the ticket the email is sent but if you update the ticket modifying the category the email is not sent to the group assigned by the rule.

**Comment by kabassanov** [comment]
I've just modified the category of one of my tickets and I can see in the mail logs of glpi that an e-mail was issued... Do you get the same message in your logs?

**Comment by jsamaniegog** [comment]
No, I don't get a new message in: **glpi/files/_log/mail.log**...

**Comment by yllen** [comment]
Test do today: no problem for me in update case

In Debug mode, you have an added tab in the ticket.
In this Debug Tab, you can see recipients for each event. Do you see the notification for assigned group?

**Comment by jsamaniegog** [comment]
Hi, sorry for the delay.

In the debug tab I always see the same records irrespective of the changes you make...

**Comment by yllen** [comment]
Have you look at the mail queue?

**Comment by jsamaniegog** [comment]
Yes i have, there isn't the record.

**Comment by yllen** [comment]
I can't reproduce.
@orthagh  can you repoduce?

**Comment by orthagh** [comment]
I confirm it works
Here is my tests : 
* Add a rule with add/update config, who assign a specific group  when a specific category is set.
* Create ticket with 0 actors (no by, no requester, no observers, no assign)
* Install & enable Behaviors plugin to add assign notifications (theses doesn't exists by default in glpi)
* Add a notification for assign group event with "group in charge of the ticket" in recipients.
* Change the category of my ticket to the specified one in my rule.
* I note the group is assigned in consequence.
* Checking my mailqueue (cleaned before tests): 

![image](https://cloud.githubusercontent.com/assets/418844/16302811/7a155b2e-394d-11e6-90c6-d9100eef1286.png)


@jsamaniegog, Could you check all of this steps are valid for you.

**Comment by jsamaniegog** [comment]
Hello, sorry for the delay, I have been away.

I've tried all the steps and the notification is not sent. I have something different... I'll continue trying things until I find the problem...

Thank you @orthagh !

**Comment by jsamaniegog** [comment]
Hi,
the issue is solved, the error was in the configuration of the notification Update Ticket.
Excuse me, please.

Thank you.

**Comment by orthagh** [comment]
Hello @jsamaniegog 

Thank you very much for this feedback :)

**Comment by jsamaniegog** [comment]
Hi @orthagh, 
I changed the type unintentionally
