### ISSUE TITLE
top-menu problem

### ISSUE THREAD

**Issue by klodnitsky** [glpi-project/glpi#645]
Hi,
GLPI 0.90.3 problem with top-menu, when choose in profile other languages (for example latvian), top-menu blue line are fixed-sized.
![image](https://cloud.githubusercontent.com/assets/7794575/15207196/2d311c9e-182d-11e6-9050-dc0a09e0b2f7.png)

**Comment by orthagh** [comment]
Hello @klodnitsky 

Thank you for your report.
It will be fixed in next release
