### ISSUE TITLE
[9.2, 9.3, 9.4, 9.5] detectRootDoc() doesn't compute correct $CFG_GLPI["root_doc"] value when called via cron.php

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#6458]
Hello,

**Bug description**

When cron.php is started, the Config::detectRootDoc() method will wrongly set the $CFG_GLPI["root_doc"] to the string: "cron.php"

**To reproduce**

1. add the following code block at the end of the config.php file: 
```
$notiftarget = new NotificationTarget;
$item = new Ticket;
$item->getFromDB(1); // need to have a ticket in DB with id == 1
Toolbox::logInFile('php-errors', "CFG_GLPI['root_doc']: ".$CFG_GLPI["root_doc"]."\n".
                                 "URL: " . $notiftarget->formatURL(NotificationTarget::EXTERNAL_USER, urlencode($item->getLinkURL())).
                                 "\n", true);
```
2. start a command line terminal
3. go to glpi/front/ folder
4. start cron.php: `php cron.php 1`
5. look in the php error log file. you should see a line like: 

> 2019-10-11 15:36:58 [@FRY09565]
> CFG_GLPI['root_doc']: **cron.php**
> URL: http://../index.php?redirect=**cron.php**/front/ticket.form.php?id=1

**Expected behavior**

> 2019-10-11 15:36:58 [@FRY09565]
> CFG_GLPI['root_doc']: (= empty string)
> URL: http://.../index.php?redirect=/front/ticket.form.php?id=1

Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello again,
I made tests within Windows and within Ubuntu, and the results are identical.
Thank you
Regards,
Tomolimo

**Comment by mulbzh** [comment]
Hello,

I don't know if the problem is the same as i have. I have GLPI 9.4.4.

When cron.php add mail to GLPI, documents are imported : good !
But in tickets, the link is broken because the URL is bad, the URL is like this :

http://glpi.toto.fr/front/glpi.toto.fr/glpi/front/document.send.php?docid=146&amp;tickets_id=148" alt="19a070c2-d9d62df8-5da583c6e523a0.28549694" 

i have 2 times glpi.toto.fr/glpi in the URL. it is the same as you said ?

**Comment by tomolimo** [comment]
Hello @mulbzh, 

To be sure if these issues are identical, you must do the test I propose here: https://github.com/glpi-project/glpi/issues/6458#issue-505706207

And look into the php-errors.log file

Regards,
Tomolimo

**Comment by mulbzh** [comment]
Hello,
no need do this test because i am sure it is a problem with CRON because when i use the collector from GLPI interface to force recover emails it works very good, links are not broken.

So i am sure the problem is with the cron.php

**Comment by tomolimo** [comment]
Hello,
I agree with, but could you do it even if you are sure?
This will give valuable clues to help for the fix, thank you.
Regards,
Tomolimo

**Comment by mulbzh** [comment]
Hello,

this bug is not resolve ?

**Comment by tomolimo** [comment]
Hello,
I checked with 9.5.5, and the bug is still present...
Thank you
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
Any up?
Thank you

**Comment by cedric-anne** [comment]
Hi,

Can you check if #11085 fixes your issue ?
