### ISSUE TITLE
Error during document suppression from a ticket

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#646]
Hi,

When I try to definitely suppress a document from a ticket, I get the following error:

Les champs obligatoires ne sont pas définis. Merci de corriger : Documents
Opération échouée
(0 problèmes de droits, 1 échecs)
N/A : Erreur en exécutant l'action 

I looked up for another solution:
I entered into the document object and succeeded in putting it into the recycle bin.
After that I tried to definitely suppress it from the same object and I got the following:

Les champs obligatoires ne sont pas définis. Merci de corriger : Documents
Suppression avec succès du fichier /var/lib/glpi/files/PDF/e4/5934cad2e9f0cdd55ff4acb89ad842bd695508.PDF

Mise à jour impossible de l'élément : pas assez de droit sur le(s) parent(s)

Les champs obligatoires ne sont pas définis. Merci de corriger : Documents

Élément supprimé définitivement avec succès : Document : Ticket - Machine intel

So now in the ticket (in debug mode) I have also a red line saying:
PHP Notice: Undefined index: date_mod in /usr/share/glpi/inc/ticket.class.php at line 6147

About GLPI:

[code]
GLPI 0.90.3 (/glpi => /usr/share/glpi)

Operating system: Linux xxxxx.lip6.fr 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
PHP 5.6.21 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, apc, apcu, bcmath, bz2, calendar, ctype,
	curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, igbinary, imap, intl, json, ldap, libxml,
	lzf, mbstring, mcrypt, mhash, msgpack, mysql, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session,
	shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="10M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.6.21 ()
	Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko
Server Software: MariaDB Server
	Server Version: 5.5.47-MariaDB
	Server SQL Mode: STRICT_ALL_TABLES
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/etc/glpi : OK
OK/var/lib/glpi/files : OK
OK/var/lib/glpi/files/_dumps : OK
OK/var/lib/glpi/files/_sessions : OK
OK/var/lib/glpi/files/_cron : OK
OK/var/lib/glpi/files/_graphs : OK
OK/var/lib/glpi/files/_lock : OK
OK/var/lib/glpi/files/_plugins : OK
OK/var/lib/glpi/files/_tmp : OK
OK/var/lib/glpi/files/_rss : OK
OK/var/lib/glpi/files/_uploads : OK
OK/var/lib/glpi/files/_pictures : OK
OK/var/log/glpi : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

Plugins list
	additionalalerts     Name: Alertes supplémentaires        Version: 1.8.0      State: Enabled
	certificates         Name: Certificats                    Version: 2.1.1      State: Enabled
	fields               Name: Champs supplémentaires         Version: 0.90-1.2   State: Enabled
	customfields         Name: Customfields                   Version: 1.7        State: Not activated
	fusioninventory      Name: FusionInventory                Version: 0.90+1.2   State: Enabled
	geninventorynumber   Name: Génération de numéros d'invent Version: 0.85+1.0   State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.2.1      State: Enabled

**Comment by jsamaniegog** [comment]
I have the same error, if you try to disociate from ticket or document screen get the following error:

Mandatory fields are not filled. Please correct: Documents

**Comment by yllen** [comment]
Solved in https://github.com/glpi-project/glpi/issues/649

**Comment by kabassanov** [comment]
Je confirme.
