### ISSUE TITLE
GLPI 9.4.2 - Ldap user image not displayed

### ISSUE THREAD

**Issue by Zarau123** [glpi-project/glpi#6472]
**Describe the bug**
After updating from 9.4.0 to 9.4.2 all users lost their profile foto that is sync from LDAP

I already check the pach to the thumbnail and everything is right but still no image displayed

On the spot of the foto i only have Image whitten

**GLPI SETUP**

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (5.7.27) - Perfect!Database version seems correct (5.7.27) - Perfect!
OK/var/www/html/servicedesk/files/_log : OK
OK/var/www/html/servicedesk/config : OK
OK/var/www/html/servicedesk/files : OK
OK/var/www/html/servicedesk/files/_dumps : OK
OK/var/www/html/servicedesk/files/_sessions : OK
OK/var/www/html/servicedesk/files/_cron : OK
OK/var/www/html/servicedesk/files/_graphs : OK
OK/var/www/html/servicedesk/files/_lock : OK
OK/var/www/html/servicedesk/files/_plugins : OK
OK/var/www/html/servicedesk/files/_tmp : OK
OK/var/www/html/servicedesk/files/_cache : OK
OK/var/www/html/servicedesk/files/_rss : OK
OK/var/www/html/servicedesk/files/_uploads : OK
OK/var/www/html/servicedesk/files/_pictures : OK

**Additional context**

![image](https://user-images.githubusercontent.com/56557411/66770794-66ed6700-eeb0-11e9-86ec-2eee81876d6a.png)

**Comment by trasher** [comment]
This is fixed in latest release
