### ISSUE TITLE
After Update to 9.4.4 contract search does not work

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#6484]
After Update to 9.4.4 contract search does not work and give no result.

Erorr log:

Error: Unknown column 'glpi_plugin_fields_contractordners.ordnerfolderfield' in 'where clause'
  Backtrace :
  inc/search.class.php:1246                          
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  front/contract.php:39                              Search::show()

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided. Also, this is certainly already fixed; try with up to date 9.4/bugfixes
