### ISSUE TITLE
Show Entity field on ticket creation, when entity has child entities

### ISSUE THREAD

**Issue by lfardin** [glpi-project/glpi#6487]
When user is creating a ticket at the upper level entity, the form could display an entity field enabling to choose a child entity to register the issue.
The form should then reload with the corresponding entity model, without the need to specifically change the entity at the upper right corner of the screen.

**Comment by tomolimo** [comment]
Hello @lfardin 
This is already the case in central interface... when adding a requester at ticket creation form, it will show a dropdown in which you can select the entity, and after selection, the ticket is reloaded into the entity context.
Thank you,
Regards,
Tomolimo
