### ISSUE TITLE
[9.5] - php warning entities_id not set with a CommonDBChild itemtype

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#6488]
Hi

It seems the issue appears with commit 033d5f963bd13488b5ca5669ef4d1be28ceaf353

In Formcreator 2.9, when I view a target ticket (itemtype inherited from CommonDBChild, without a column entities_id) I get the following warning

![image](https://user-images.githubusercontent.com/14139801/67094579-6f95b400-f1b4-11e9-89ed-ede1128bcbb6.png)

****
call stack:
PluginFormcreatorTargetTicket->showNavigationHeader (/glpi-95/inc/commonglpi.class.php:983)
PluginFormcreatorTargetTicket->display (/glpi-95/inc/commonglpi.class.php:1153)
{main} (/glpi-95/plugins/formcreator/front/targetticket.form.php:90)

$this->isEntityAssign() is implemnted in CommonDBChild and checks the itemtype defined in the static property $itemtype . When true, the code in the if statement reads the entities_id of the current CommonDBChild object, but when the valie does not exists, we get a warning.

**Comment by cedric-anne** [comment]
Fixed in #6719 .
