### ISSUE TITLE
Rule/Ticket actions on criteria limited to 1

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6491]
In 9.4/bugfixes, we can't create more than 1 action on a rule
Question : Is there a function that allows you to enter the max number of actions ? If yes, where is it ?

**To reproduce**
Create a rule on ticket, add a action, the button add dispear : we can't add a second one.

**Expected behavior**
Can add more than one action

**Logs**
/
**Screenshots**
No action : can add : 
![image](https://user-images.githubusercontent.com/55535560/67184375-ecf33b80-f3e3-11e9-8640-8847a990da9d.png)
One action : can't add : 
![image](https://user-images.githubusercontent.com/55535560/67184419-01cfcf00-f3e4-11e9-8047-99b6f3dbba92.png)
Before the version inc.rule.class.php : 
![image](https://user-images.githubusercontent.com/55535560/67184518-452a3d80-f3e4-11e9-83fc-b837ed0cabb2.png)

**Comment by cedric-anne** [comment]
Hi,

#6718 should fix this problem.

Regards
