### ISSUE TITLE
Create a change or a problem from a ticket removes text formatting

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6496]
Hi,

**Describe the bug**
When create a problem or a change from a ticket, the copied description does not have anymore text formating. This causes problems in rows with numbered formatting, and so on.

**To reproduce**
Create a new ticket with bold, underline, title format in the description, etc, save the ticket.
Update ticket by going to folder "create a problem/change from this ticket" (créer un problème/changement à partir de ce ticket).
Go to the new linked problem/change : the formatting of the text has disappeared.

**Expected behavior**

The formatting of the text should follow the ticket as is.

**Logs**
/
**Screenshots**
Ticket :
![image](https://user-images.githubusercontent.com/55535560/67207623-45423180-f414-11e9-869b-db423d0da532.png)
Problem created from ticket : 
![image](https://user-images.githubusercontent.com/55535560/67207679-54c17a80-f414-11e9-8efa-54983537044a.png)

GLPI version 9.4.4

**Comment by trasher** [comment]
Same as https://github.com/glpi-project/glpi/issues/6062
