### ISSUE TITLE
one failed login and account is disabled

### ISSUE THREAD

**Issue by Eon9D** [glpi-project/glpi#6498]
**Describe the bug**

LDAP Account
--
System settings: Display source dropdown on login page = Yes
Login multiple times with a valid username but wrong passwords.
Login with the same valid username and the correct password.
You are logged in.

System settings: Display source dropdown on login page = NO
Login ONCE with a valid username but wrong passwords.
Login with the same valid username and the correct password.
The account is disabled and you cannot login.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
9.4.4
```

**Logs**
```
[2019-10-21 21:16:46] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): ldap_bind(): Unable to bind to server: Invalid credentials
  Backtrace :
  :
  inc/auth.class.php:234                             ldap_bind()
  inc/authldap.class.php:2733                        Auth->connection_ldap()
  inc/authldap.class.php:2788                        AuthLDAP::ldapAuth()
  inc/auth.class.php:757                             AuthLDAP::tryLdapAuth()
  front/login.php:84                                 Auth->login()
  {"user":"@server"}

```

Thanks

**Comment by trasher** [comment]
`ldap_bind(): Unable to bind to server: Invalid credentials` this is your LDAP connection/configuration that fail here, not GLPI. Fix your issue first

**Comment by Eon9D** [comment]
LDAP is working fine for a long time. The mentioned log entry only comes when I set "Display source dropdown on login page" to NO.

Why is it not in the log when I set this to "YES"?

Can you please test this for 2 minutes..
Thanks

**Comment by prohand** [comment]
Hello,

I have a same problem with same configuration

Can you fix please.

**Comment by OscarBeiro** [comment]
Hi,
We've found a similar issue. To shed some light on this question, we have found if 
 **Display source dropdown on login page** is set to **NO** and there are multiple authentication methods (4 in this particular instance) the user is disabled.
However, if we set it to YES it works. Of course, this is not always an option, so we'll keep looking for a proper fix.

**Comment by OscarBeiro** [comment]
We have found the problem.
If more than one LDAP authentication is added to GLPI and not using the Auth dropdown, it will check every LDAP server.
The loop checks if DN exists in every LDAP server. So:

Imagine a 2 LDAP scenario:
1. LDAP 1 has the user on it, so DN exists. Password is wrong so GLPI continues to next LDAP server.
2. LDAP 2 doesn't have the user on it, so no matching DN. GLPI disables the user, according to Auth configuration (Disable, remove authorizations, etc).

We are working in a patch, and will add a PR soon.
