### ISSUE TITLE
computer search 9.4.4

### ISSUE THREAD

**Issue by arkanium** [glpi-project/glpi#6501]
Hello,

I just upgraded 9.4.3 to 9.4.4 and immediately rollback.
When anyone want to search (global search or inside computer search only) no result can be found.

The request is basic for any "items seen" that "contains" [full name | partial name ] no result.
If i change "items seen" to "computer name" / "user" (what i want to find) it work fine (in computer only).

when i try a global search the computer part never show in the list.

No errors on screen or apache log just a blank page downside the search filter.

Navigator cache cleared and tried from Firefox (69.0.3) / google chrome (77.0.3865.120).

When i came back to 9.4.3 everything work fine angain with the search filter.

Many Thanks

**Comment by trasher** [comment]
There already have open issues about that. This is certainly due to a column displayed.

BTW Informations requested in ticket template has not been provided.

**Comment by arkanium** [comment]
Ok,

My apologises about all requested elements.

Have a nice day
