### ISSUE TITLE
Check box in tasks list done / not done useless

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6512]
Hello,

In the processing list of the ticket, if a task has been added, it is possible to check a box at the top left of the task (or uncheck it) ... for nothing since it is not managed here, and anyway, will not be saved.

It is a disturbing behavior, because it can be unchecked when it is and we can believe that it is recorded, while no.

**To reproduce**

Create a ticket and create a task
In the processing tab of the ticket, note that check/uncheck the box at the top left of the task is useless.

Set this box to read-only. (Because there is management in the task to do around this box, modify the text for example)

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/67551624-a8301300-f709-11e9-8e0f-8045db95172e.png)

GLPI  9.4.4+behaviors 2.2.2

**Comment by trasher** [comment]
Write in english only.

**Comment by mab18** [comment]
Done  ;-)

**Comment by mab18** [comment]
> 
> 
> Write in english only.

Done ;-)
