### ISSUE TITLE
Problems installing / upgrading GLPI 9.4.4

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#6519]
Hi guys, I'm trying to install GLPI 9.4.4 and I get the following browser error:

Gateway Timeout
The gateway did not receive a timely response from the upstream server or application.

![erro](https://user-images.githubusercontent.com/35368369/67676556-8a102000-f960-11e9-8cc4-fa692f336ffd.PNG)

The error is presented at the time of installation or upgrade when I enter the user password of the database.

the file "php_errors" within _log gives me the following

lpiphplog.DEBUG: Html::compileScss() in /var/www/html/GLPI/inc/html.class.php line 6829
css/palettes/auror is new, loading  {"user":"@unknownd8cb8adfddab","mem_usage":"0.018\", 1.06Mio)"}
[2019-10-26 22:53:25] glpiphplog.WARNING: Test logger
[2019-10-26 23:08:08] glpiphplog.WARNING: Test logger
[2019-10-26 23:14:38] glpiphplog.WARNING: Test logger

the file "sql-erros" within _log gives me the following

Error: Table 'inmet.glpi_plugins' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbtm.class.php:525                       DBmysql->request()
  inc/plugin.class.php:124                           CommonDBTM->find()
  inc/console/application.class.php:388              Plugin->init()
  inc/console/application.class.php:91               Glpi\Console\Application->loadActivePlugins()
  bin/console:71                                     Glpi\Console\Application->__construct()
  {"user":"@unknownd8cb8adfddab","mem_usage":"0.000\", 8.03Mio)"}

anyone can help me?

MariaDB 10.3
PHP 7.3

**Comment by trasher** [comment]
glpi_plugins should exists, your database seems corrupted; 
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by phamorais** [comment]
@trasher 
Thank you very much.
However, this problem even occurs in the installation, that is, in the creation of the database, so the database n is corrupted

**Comment by tieugene** [comment]
Same problem with glpi 9.4.5 @ Fedora 30, CentOS 8.
Installing from  scratch.
Has no any error log.

**Comment by fgksuporte** [comment]
I have the same problem, either installing the CENTOS 8.1 package with version 9.3 or 9.4, or performing the manual installation by downloading versions 9.3.0 to 9.3.4 and 9.4.1 to 9.4.5 directly from GitHub. I installed a server from scratch just to see if it was a database or php problem. Nothing worked. Is there anything that can be done to resolve this?
Thanks for listening

**Comment by brwainer** [comment]
Adding "Timeout 600" to "nano /etc/httpd/conf/httpd.conf" allowed the database step to complete for me.
