### ISSUE TITLE
Glpi 0.90.3 fix in Follow by Email

### ISSUE THREAD

**Issue by guillermohaad** [glpi-project/glpi#653]
Dear GLPi user.

When you sent a follow email arrives HMLT format like this:

<Div dir = "ltr"> <div> <br> </ div> change tracking test .. <br clear="all"> <div> <br> </ div> - <br> <div class = "gmail_signature"> <div dir = "ltr"> <div> <div dir = "ltr"> <div style = "font-size: 12.8000001907349px"> GUILLERMO HAAD A. <br> <span style = " font-family: arial; font-size: small "> DBA Frimac - Friofrimac </ span> <br> FRIMAC SA </ div> <div style =" font-size: 12.8000001907349px "> <a href =" mailto: E-mail%3Aegomez@frimac.com.co "style =" color: rgb (17,85,204) "target =" _ blank "> <span style =" color: rgb (0,0,204) "> E-mail: ghaad @ frimac.com.co </ span> </a> </ div> <div style = "font-size: 12.8000001907349px"> Tel: + 57 2060 6486767 Ext </ div> <div style = "font-size : 12.8000001907349px "> Cel: <a target="_blank"> href="tel:317-5730774" value="+573175730774" style="color:rgb(17,85,204)" 317-5730774 </a> < / div> <div style = "font-size: 12.8000001907349px"> <p> <span lang = "EN" style = "font-size: 10pt"> <font color = "# 222222"> Internet: </ font > <a href="www.frimac.com.co/" style="color:rgb(17,85,204)" target="_blank"> <span style = "color: rgb (0,0,153)"> www. frimac.com.co </ span> </a> </ span> <font color = "# 222222"> <u> </ u> <u> </ u> </ font> </ p> <p > <span style = "font-size: 8pt; color: rgb (47,125,23)"> Please consider the environment before printing this email </ span> </ p> </ div> </ div>. </ div> </ div> </ div> </ div>

**Comment by flegastelois** [comment]
Hi Guillermo,

What is your problem ?

Regards,

**Comment by guillermohaad** [comment]
When sending mail to Followup my ticket, GLPI receives in HTML format. Only it happens to follow.

attached image:

![error_seguimiento](https://cloud.githubusercontent.com/assets/12921805/15505133/ba8eb340-2187-11e6-8d1a-31c365ecfe3c.png)

**Comment by guillermohaad** [comment]
The error is from addtodb function the ' is not replace par \'

INSERT INTO glpi_ticketfollowups (content,tickets_id,users_id,requesttypes_id,is_private,date) VALUES ('c'et fait.\n\nxxx xxxLe 8 mars 2016 Ã 19:52, \n\n \n\n','3638','164','2',0,'2016-03-09 12:18:56')
erreur addToDB

solution:

In mailcollector.class 

add after : $fup = new TicketFollowup();

$tkt['content'] = utf8_decode(str_replace("'","\'",html_entity_decode($tkt['content'],ENT_QUOTES)));
