### ISSUE TITLE
PHP Deprecated function: array_key_exists(): 

### ISSUE THREAD

**Issue by vasiliyaltunin** [glpi-project/glpi#6545]
I just install latest version from git, and just after install i get this error

Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in /var/www/html/vendor/zendframework/zend-i18n/src/Translator/Loader/Gettext.php at line 142

Well i understand that notice, but it must not be there and zend-i18n seems has fix for it - https://github.com/zendframework/zend-i18n/issues/121

I use nginx and php 7.4

**Comment by trasher** [comment]
php 7.4 is not yet released; and 9.5 branch is already compatible.

**Comment by gauburtincc** [comment]
Hi, 

now Php 7.4 is released and GLPI 9.5 is not released.
I get the same error
What can we do ?

I use nginx / php 7.4 / GLPI 9.45

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/issues/6761

**Comment by gauburtincc** [comment]
Well, 

Do E_NOTICE logs can be ignored ?
