### ISSUE TITLE
[90.3] Doesn't delete the null inscription in ticket

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#655]
Hello. Yesterday I found an error when deleting a documemt. The document was removed but the inscription has remained and when I click on the Delete permanently button doesn't delete the inscription. When I click on the Edit opens a document with null id.

![glpi - tickets - google chrome 2016-05-16 16 18 31](https://cloud.githubusercontent.com/assets/17082164/15315401/1623aef8-1c20-11e6-9ddb-651196231d60.png)
![glpi - tickets - google chrome 2016-05-16 16 19 16](https://cloud.githubusercontent.com/assets/17082164/15315407/196652f0-1c20-11e6-94a9-fddb01ed8500.png)
![glpi - tickets - google chrome 2016-05-16 17 03 02](https://cloud.githubusercontent.com/assets/17082164/15315410/1c18c6d6-1c20-11e6-8c0d-8f8bff3bd58d.png)

**Comment by orthagh** [comment]
Hello @AircraftRu 

I can't replicate your issue at all.
Could you precise the glpi version  and if you can, a way to always trigger theses errors ?

I think it can a cache issue.

**Comment by AircraftRu** [comment]
In MySQL database not deleted link with a non-existent document. I corrected it. 
May was local problem to php. Maybe it's a random bug.

**Comment by orthagh** [comment]
Ok So i close this issue now.
Feels free to re-open and comments if you trigger again and had replication steps .

Regards
