### ISSUE TITLE
SQL-Error when searching unter Management->Licenses

### ISSUE THREAD

**Issue by FSD-Christian-ISS** [glpi-project/glpi#6555]
When starting a search in the Management->Licenses menu there are no results shown.
The debug mode shows an error message:
``Unknown column 'glpi_softwareversions.name' in 'where clause'``
for this SQL query:

``SELECT DISTINCT `glpi_softwarelicenses`.`id` AS id, 'schulz' AS currentuser, `glpi_softwarelicenses`.`entities_id`, `glpi_softwarelicenses`.`is_recursive`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_softwarelicenses`.`name`, '$#$' , `glpi_softwarelicenses`.`id`)
ORDER BY `glpi_softwarelicenses`.`id` SEPARATOR '$$##$$') AS `ITEM_SoftwareLicense_1`, `glpi_locations`.`completename` AS `ITEM_SoftwareLicense_3`, `glpi_softwares`.`name` AS `ITEM_SoftwareLicense_10`, `glpi_softwares`.`id` AS `ITEM_SoftwareLicense_10_id`, `glpi_softwarelicensetypes`.`name` AS `ITEM_SoftwareLicense_5`, FLOOR(SUM(`glpi_softwarelicenses`.`number`) * COUNT(DISTINCT `glpi_softwarelicenses`.`id`) / COUNT(`glpi_softwarelicenses`.`id`)) AS `ITEM_SoftwareLicense_4`, MIN(`glpi_softwarelicenses`.`number`) AS `ITEM_SoftwareLicense_4_min`, `glpi_softwarelicenses`.`is_valid` AS `ITEM_SoftwareLicense_9`, `glpi_users`.`name` AS `ITEM_SoftwareLicense_70`, `glpi_users`.`realname` AS `ITEM_SoftwareLicense_70_realname`, `glpi_users`.`id` AS `ITEM_SoftwareLicense_70_id`, `glpi_users`.`firstname` AS `ITEM_SoftwareLicense_70_firstname`, `glpi_softwarelicenses`.`comment` AS `ITEM_SoftwareLicense_16`, `glpi_softwarelicenses`.`otherserial` AS `ITEM_SoftwareLicense_162`, COUNT(DISTINCT `glpi_documents_items`.`id`) AS `ITEM_SoftwareLicense_119`, `glpi_softwarelicenses`.`serial` AS `ITEM_SoftwareLicense_11`, `glpi_softwareversions_softwareversions_id_buy`.`name` AS `ITEM_SoftwareLicense_6`
FROM `glpi_softwarelicenses`
LEFT JOIN `glpi_locations` ON (`glpi_softwarelicenses`.`locations_id` = `glpi_locations`.`id` )
LEFT JOIN `glpi_softwares` ON (`glpi_softwarelicenses`.`softwares_id` = `glpi_softwares`.`id` )
LEFT JOIN `glpi_softwarelicensetypes` ON (`glpi_softwarelicenses`.`softwarelicensetypes_id` = `glpi_softwarelicensetypes`.`id` )
LEFT JOIN `glpi_users` ON (`glpi_softwarelicenses`.`users_id` = `glpi_users`.`id` )
LEFT JOIN `glpi_documents_items` ON (`glpi_softwarelicenses`.`id` = `glpi_documents_items`.`items_id` AND `glpi_documents_items`.`itemtype` = 'SoftwareLicense' )
LEFT JOIN `glpi_softwareversions` AS `glpi_softwareversions_softwareversions_id_buy` ON (`glpi_softwarelicenses`.`softwareversions_id_buy` = `glpi_softwareversions_softwareversions_id_buy`.`id` )
WHERE `glpi_softwarelicenses`.`is_deleted` = 0 AND `glpi_softwarelicenses`.`is_template` = 0 AND ( ( (`glpi_softwarelicenses`.`name` LIKE '%abbyy%' ) OR (`glpi_locations`.`completename` LIKE '%abbyy%' ) OR (`glpi_softwares`.`name` LIKE '%abbyy%' ) OR (`glpi_softwarelicensetypes`.`name` LIKE '%abbyy%' ) OR (`glpi_softwarelicenses`.`number` LIKE '%abbyy%' ) OR (`glpi_softwarelicenses`.`is_valid` LIKE '%abbyy%' ) OR (((`glpi_users`.`realname` LIKE '%abbyy%' OR `glpi_users`.`firstname` LIKE '%abbyy%' OR `glpi_users`.`name` LIKE '%abbyy%' OR CONCAT(`glpi_users`.`realname`, ' ', `glpi_users`.`firstname`) LIKE '%abbyy%' ) ) ) OR (`glpi_softwarelicenses`.`comment` LIKE '%abbyy%' ) OR (`glpi_softwarelicenses`.`otherserial` LIKE '%abbyy%' ) OR (`glpi_softwarelicenses`.`serial` LIKE '%abbyy%' ) OR (`glpi_softwareversions`.`name` LIKE '%abbyy%' )) ) GROUP BY `glpi_softwarelicenses`.`id`
ORDER BY ITEM_SoftwareLicense_1 ASC``

After a quick look at that query  in the WHERE clause the line
`` OR (`glpi_softwareversions`.`name` LIKE '%abbyy%' )``
should either read `` OR (`glpi_softwareversions_softwareversions_id_buy`.`name` LIKE '%abbyy%' )``
or the alias in the Join clause 
``LEFT JOIN `glpi_softwareversions` AS `glpi_softwareversions_softwareversions_id_buy` ON (`glpi_softwarelicenses`.`softwareversions_id_buy` = `glpi_softwareversions_softwareversions_id_buy`.`id` ) ``
should be removed

using GLPI 9.4.4 with FusionInventory 9.4+2.0

**Comment by trasher** [comment]
Dups https://github.com/glpi-project/glpi/issues/6397
