### ISSUE TITLE
Move task in planning cause "Mandatory category in a task" (it's allready filled)

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6558]
Describe the bug : 
When I move a tash in the planning, a message in red at back right says "Mandatory category in a task" (Catégorie obligatoire dans une tâche).

If applicable, page(s) URL where the bug happens.
./glpi/front/planning.php

**To reproduce**
Create a ticket with a planned task.
Go to planning pannel, try to move this task to another day : message appears.
2 behaviors accurs : 
- drag and drop with mouse suggest that task has moved, but F5 confirms no.
- double-click ont the task and change with keyboard the date+ valid let's appears the error message, BUT the task is moved anyway !

**Expected behavior**
When category is filled, there should be no error message.

GLPI 2.4.4

**Comment by cedric-anne** [comment]
Hi,

There is no such check in GLPI core. I guess you use `behaviors` plugin and set to `yes` the `Task category is mandatory in a task` configuration.
Please report bug on plugin repository.

Regards

**Comment by mab18** [comment]
Hi,
Correct : I have behaviors with this option enabled ;-)
