### ISSUE TITLE
[90.3]Can't check for update

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#656]
Can't check for update on server
![glpi - maintenance - google chrome 2016-05-17 15 14 27](https://cloud.githubusercontent.com/assets/17082164/15321908/30c7de56-1c42-11e6-99ef-96dd6334778c.png)

**Comment by tyronewyatt** [comment]
I remember reporting that the check for updates stopped working last year here http://forum.glpi-project.org/viewtopic.php?id=127804 
After changes made here https://github.com/glpi-project/glpi/issues/163 it would inform you of a new version if not running 0.90. But when running 0.90 it wouldn't inform of newer versions like 0.90.1.
Hope this somewhat helps.

**Comment by orthagh** [comment]
It should be fixed now.

My script to auto-update [latest_version](http://glpi-project.org/latest_version) wasn't set executable.
The file now contains 0.90.3 until next release

**Comment by AircraftRu** [comment]
The bug is still present

**Comment by orthagh** [comment]
Could you precise ?

Do you have a proxy in your organisation ?

**Comment by AircraftRu** [comment]
Yes.
Proxy is access open for GLPI.
Squid log on Ubuntu:
`1464343678.778      0 192.168.40.68 NONE/501 3539 GET https://api.github.com/repos/glpi-project/glpi/releases - HIER_NONE/- text/html`

**Comment by AircraftRu** [comment]
As it appears server cann't connect when https

**Comment by orthagh** [comment]
I think it's relative to your server/infrastructure not glpi directly.

I you haven't set it, i suggest to do proxy configuration in Setup > General, System tab

**Comment by AircraftRu** [comment]
I set it!
