### ISSUE TITLE
Error generating recurring ticket

### ISSUE THREAD

**Issue by geanferrani123** [glpi-project/glpi#6563]
Guys, good morning!

I do not know if this would be a problem in GLPI itself or another issue, lately I am having problems generating only one recurring call, this called his opening period is once a month. When I set the period in question and click save, all my GLPI crashes, I can't do anything else, I can only unlock GLPI by restarting the server, has anyone had this problem?

**Comment by geanferrani123** [comment]
When I tail -f the phperro.log file it returns me the information below:

![image](https://user-images.githubusercontent.com/55212206/68592119-164a3900-0471-11ea-9546-7228fe900357.png)

**Comment by geanferrani123** [comment]
When I tail -f the sql-errors.log file it returns me the information below:

![image](https://user-images.githubusercontent.com/55212206/68594093-983c6100-0475-11ea-8dac-853a134ffc4a.png)

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by geanferrani123** [comment]
I'm sorry, i open new topic using the correct template
