### ISSUE TITLE
Item associated in a KB

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#6568]
https://forum.glpi-project.org/viewtopic.php?id=175891

Bug introduce by https://github.com/glpi-project/glpi/issues/5689

**Comment by mab18** [comment]
Hi,
No change :-(
I have the same problem with file glpi/inc/knowbaseitem_item.class.php from commit 7d30f45
"Une erreur est survenue au chargement des contenus !

Vérifiez les logs de GLPI ou contactez votre administrateur.
ou essayez de recharger "

Trace ./files/_log/php-error.log
[code]
  *** PHP Notice(8): Undefined index: status
  Backtrace :
  inc/knowbaseitem_item.class.php:121
  inc/knowbaseitem_item.class.php:84                 KnowbaseItem_Item::showForItem()
  inc/commonglpi.class.php:485                       KnowbaseItem_Item::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"123@srv-glpi"}
[/code]

**Comment by yllen** [comment]
PHP Notice ist not a blocking error, just an information.
i don't understand your issue because at line 121 we just count kb items (no reference to status)

**Comment by trasher** [comment]
@yllen @mab18 could you please test with fix provided in #6672? Thank you :)
