### ISSUE TITLE
Error generating recurring ticket

### ISSUE THREAD

**Issue by geanferrani123** [glpi-project/glpi#6571]
**Describe the bug**

I do not know if this would be a problem in GLPI itself or another issue, lately I am having problems generating only one recurring call, this called his opening period is once a month. When I set the period in question and click save, all my GLPI crashes, I can't do anything else, I can only unlock GLPI by restarting the server, has anyone had this problem?

Page(s) URL
https://GLPI/front/ticketrecurrent.form.php?id=XX

**To reproduce**

Go to '...'
ASSISTANCE> RECURRENT TICKET - Click on an existing recurring ticket.
The item in question is the one highlighted below.

![image](https://user-images.githubusercontent.com/55212206/68672839-380af500-0531-11ea-831a-327f51eeff98.png)

After choosing the periodicity, click "save".

If you choose any other period, no problem, now every time you set the "1 month" period, the GLPI service crashes completely and you need to restart the server for the application to work again.

**Expected behavior**

Allow the system to save the recurring call with the period "1 month" and clicking "save" does not lock the application, thus allowing the recurring call to function normally.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.4.4 ( => /glpi/css) Installation mode: TARBALL

Operating system: Linux S3A71024D1 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 PHP 7.0.27-0+deb9u1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, calendar, cgi-fcgi, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="15M" safe_mode="" session.save_handler="files" 	upload_max_filesize="15M"  Software: nginx/1.10.3 	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.75 Safari/537.36 Server Software: Debian 9.6 	Server Version: 10.1.37-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: sueq@localhost/GLPI 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.1.37) - Perfect! /glpi/css/files/_log : OK /glpi/css/config : OK /glpi/css/files : OK /glpi/css/files/_dumps : OK /glpi/css/files/_sessions : OK /glpi/css/files/_cron : OK /glpi/css/files/_graphs : OK /glpi/css/files/_lock : OK /glpi/css/files/_plugins : OK /glpi/css/files/_tmp : OK /glpi/css/files/_cache : OK /glpi/css/files/_rss : OK /glpi/css/files/_uploads : OK /glpi/css/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/glpi/css/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/glpi/css/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/glpi/css/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/glpi/css/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/glpi/css/vendor/michelf/php-markdown/Michelf) true/punycode in (/glpi/css/vendor/true/punycode/src) iamcal/lib_autolink in (/glpi/css/vendor/iamcal/lib_autolink) sabre/vobject in (/glpi/css/vendor/sabre/vobject/lib) zendframework/zend-cache in (/glpi/css/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/glpi/css/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/glpi/css/vendor/zendframework/zend-serializer/src) monolog/monolog in (/glpi/css/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/glpi/css/vendor/sebastian/diff/src) elvanto/litemoji in (/glpi/css/vendor/elvanto/litemoji/src) symfony/console in (/glpi/css/vendor/symfony/console) leafo/scssphp in (/glpi/css/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

Server: 'net.meudominio.com.br', Port: '389', BaseDN: 'DC=NET,DC=MEUDOMINIO,DC=COM,DC=BR', Connection filter: 		'(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf=CN=Meudominio-1,OU=Grupos,OU=E-MAIL,OU=GRUPOS_RECURSOS,DC=net,DC=MEUDOMINIO,DC=COM,DC=BR))', 		RootDN: 'meudominio\userservice', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@192.168.255.131)

Name: 'chamados.desen@meudominio.com' Active: No 	Server: '{172.17.11.33:993/imap/ssl/novalidate-cert}' Login: 'meudominio\chamados.desen' Password: Yes

webapplications      Name: Aplicações web                 Version: 2.6.0      State: Enabled 	impacts              Name: Asset impacts                  Version: 1.3.2      State: Enabled 	fields               Name: Campos adicionais              Version: 1.10.2     State: Enabled 	behaviors            Name: Comportamental                 Version: 2.2.2      State: Enabled 	escalade             Name: Escalonamento                  Version: 2.4.4      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.8.3      State: To be cleaned 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled 	tag                  Name: Gerenciamento de Etiquetas     Version: 2.4.2      State: Enabled 	genericobject        Name: Gerenciamento de objetos       Version: 2.7.0      State: Enabled 	mreporting           Name: Mais Relatórios                Version: 1.6.1      State: Enabled 	browsernotification  Name: Notificação do navegador       Version: 1.1.9      State: Not installed 	orderservice         Name: Ordem de Serviço               Version: 2.0.0      State: Enabled 	dashboard            Name: Painel                         Version: 0.9.7      State: Enabled 	consumables          Name: Pedidos de consumíveis         Version: 1.5.0      State: Enabled 	reports              Name: Relatórios                     Version: 1.13.1     State: Enabled
[/code]

**Additional context**

When I tail -f the phperror.log file it returns me the information below:

![image](https://user-images.githubusercontent.com/55212206/68673759-3b06e500-0533-11ea-9bf2-5f1f5325ce46.png)

When I tail -f the sql-errors.log file it returns me the information below:

![image](https://user-images.githubusercontent.com/55212206/68673770-44904d00-0533-11ea-9559-898ccd202ade.png)

Has anyone else had this problem? I am using GLPI version 9.4.4, can you help me?

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/)). 
You should also try without any plugin.

**Comment by cedric-anne** [comment]
Hi,

Could you also provide the full trace for `sql-errors.log` ? Having the error message would help.

Regard

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce, and as you did not provide the full error trace, it is impossible to know where we have to investigate.
Please free to reopen the ticket if you are able to provide the full error trace.

Regards
