### ISSUE TITLE
Curious behavior when we click on a link of an email.

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6581]
Hello,

**Describe the bug**
I'm using a saved search that sends an email.
A - When I click on the link provided in the email, while the browser is closed, the browser opens and displays the _Search list saved_. If the browser is already open, it just adds a tab and opens the contents of the saved search instead of displaying the list.

B - I encounter a similar problem with the ticket modification notification email: If the browser is closed, it opens the ticket at the same time as the browser, otherwise it opens the list of tickets with the filter recently used in a new tab .

By changing the default browser, it is reproducible on Edge, IE, Chrome and Firefox. Windows 10/64 context, GLPI 9.4.4.
**Expected behavior**
A - The browser should open the list of THE saved search instead of the list of saved searchs.
B - The browser should open the ticket instead of the list of tickets.

Link to glpi forum : https://forum.glpi-project.org/viewtopic.php?pid=378491#p378491

**Comment by tomolimo** [comment]
Same issue for notifications from saved searches

**Comment by trasher** [comment]
I've not been able to reproduce. What is the link in the received email? I wonder if there is any encoding (or similar) issue here.

**Comment by mab18** [comment]
Hi, 
did you see the https://github.com/glpi-project/glpi/issues/6916 ?
