### ISSUE TITLE
[GLPI 9.4.4] Translation error / inconsistency

### ISSUE THREAD

**Issue by At-M** [glpi-project/glpi#6583]
When getting a notification e-mail about a new reservation, the german translation has an inconsistency, since it uses a Swiss-German translation once.

(##reservation.action##)
When creating a reservation: "Neue Reservierung"
When deleting a reservation: "Löschung einer **Reservation**"
Correct Term: "Löschung einer **Reservierung**"

`GLPI 9.4.4 (/glpi => /var/www/html/glpi) Installation mode: TARBALL `

**Comment by trasher** [comment]
Translations are done on transifex

**Comment by trasher** [comment]
https://www.transifex.com/glpi/GLPI/dashboard/
