### ISSUE TITLE
GLPI [9.4.4]Error close Partial load of the saved search - Self-service

### ISSUE THREAD

**Issue by chauchse** [glpi-project/glpi#6596]
Dear,

Since upgrade from 9.6.3 to 9.4.4 i cannot use "self-service" profile for any users.

All searches give errors like that :

![image](https://user-images.githubusercontent.com/17750964/68927771-cd53f680-0788-11ea-9803-1b96078d98f3.png)

I have disabled all plugins and try to create another "self-service" profile... but the problem is persistent.

My config :

Information about system installation and configuration
--
[code]   GLPI 9.4.4 ( => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux XXXXXX 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 PHP 7.2.24-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="20M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at XXXXXXX Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.27-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (5.7.27) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

news                 Name: Alertes                        Version: 0.90-1.3.1 State: Not activated 	archires             Name: Architectures réseau           Version: 2.6.0      State: Not activated 	fields               Name: Champs supplémentaires         Version: 0.90-1.2   State: Not installed 	shellcommands        Name: Commandes Shell                Version: 2.0.0      State: To be cleaned 	openvas              Name: Connecteur OpenVAS pour GLPi   Version: 1.1.0      State: Not activated 	domains              Name: Domaines                       Version: 1.9.0      State: Not activated 	formcreator          Name: Formulaires                    Version: 2.7.0-beta.3 State: Not activated 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Not activated genericobject        Name: Gestion d'objets               Version: 2.7.0      State: Not activated datainjection        Name: Injection de fichiers          Version: 2.6.3      State: Not activated 	mailanalyzer         Name: Mail Analyzer                  Version: 1.3.1      State: Not activated 	browsernotification  Name: Notification de Navigateur     Version: 1.1.8      State: Not activated
[/code]

When i open simplified interface "self-service", no error is registered in :
 /glpi/files/_log/php-errors.log
/var/log/apache2/error.log
/var/log/nginx/error.log (I use nginx as reverse proxy)
The only error i can see is in AJAX web debug mode :

SELECT DISTINCT `glpi_tickets`.`id` AS id, 'TEST' AS currentuser, `glpi_tickets`.`id` AS `ITEM_Ticket_2`, `glpi_tickets`.`name` AS `ITEM_Ticket_1`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`content` AS `ITEM_Ticket_1_content`, `glpi_tickets`.`status` AS `ITEM_Ticket_1_status`, `glpi_tickets`.`content` AS `ITEM_Ticket_21`, `glpi_tickets`.`priority` AS `ITEM_Ticket_3`, `glpi_tickets`.`date_mod` AS `ITEM_Ticket_19`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`content`, '__NULL__'), '$#$',`glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`id`)ORDER BY `glpi_tickettasks`.`date` DESC SEPARATOR '$$##$$') AS `ITEM_Ticket_26`, GROUP_CONCAT(DISTINCT `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_5`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id`, ' ', `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_5_2`, `glpi_tickets`.`status` AS `ITEM_Ticket_12`, GROUP_CONCAT(DISTINCT `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_4`, GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id`, ' ', `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`alternative_email`) SEPARATOR '$$##$$') AS `ITEM_Ticket_4_2`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`items_id`, '__NULL__'), '$#$',`glpi_items_tickets`.`id`)ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_13`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`itemtype`, '__NULL__'), '$#$', `glpi_items_tickets`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Ticket_13_itemtype`, `glpi_tickets`.`date` AS `ITEM_Ticket_15`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets`.`takeintoaccount_delay_stat`, '__NULL__'), '$#$',`glpi_tickets`.`id`)ORDER BY `glpi_tickets`.`id` SEPARATOR '$$##$$') AS `ITEM_Ticket_150`FROM `glpi_tickets`LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )LEFT JOIN `glpi_groups_tickets` AS `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60` ON (`glpi_tickets`.`id` = `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`.`tickets_id` AND `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`.`type` = 1 )LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_tickets`.`id` = `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 )LEFT JOIN `glpi_groups_tickets` AS `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8` ON (`glpi_tickets`.`id` = `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`tickets_id` AND `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`type` = 3 )LEFT JOIN `glpi_tickets_users` AS `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b` ON (`glpi_tickets`.`id` = `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )LEFT JOIN `glpi_groups_tickets` AS `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b` ON (`glpi_tickets`.`id` = `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`tickets_id` AND `glpi_groups_tickets_819efb92c8b927b345e489211ec8e43b`.`type` = 2 )LEFT JOIN `glpi_tickettasks` AS `glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb` ON (`glpi_tickets`.`id` = `glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`tickets_id` AND (`glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`is_private` = 0 OR `glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`users_id` = '6') )LEFT JOIN `glpi_users` AS `glpi_users_f201be21cd638ee780d08cba4ceff0d4` ON (`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id` = `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` )LEFT JOIN `glpi_users` AS `glpi_users_a5e2026cbcb683e774f93a59e24a62a4` ON (`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id` = `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` )LEFT JOIN `glpi_items_tickets` ON (`glpi_tickets`.`id` = `glpi_items_tickets`.`tickets_id` )WHERE ( `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.users_id = '6' OR `glpi_tickets_users_d86d1fe2a1ea996e3820de82e6aa57e8`.users_id = '6' OR `glpi_tickets`.`users_id_recipient` = '6' OR `glpi_groups_tickets_d1524bb2ea1d461ab90aed3b5f0e7e60`.`groups_id` IN (1,2,28) OR `glpi_groups_tickets_d86d1fe2a1ea996e3820de82e6aa57e8`.`groups_id` IN (1,2,28)) AND `glpi_tickets`.`is_deleted` = 0 AND ( `glpi_tickets`.`entities_id` IN ('0') ) AND ( `glpi_tickets`.`status` IN ('2') ) GROUP BY `glpi_tickets`.`id`ORDER BY ITEM_Ticket_19 DESC | 0.002 | **Unknown column 'glpi_tickettasks.date' in 'field list'**
-- | -- | --

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/))

Also, logs are in lgos files (files/_logs/) ; what you pasted is difficult to read.

**Comment by chauchse** [comment]
Hi,

Thanks for your answer. 
I don't understand what i need to do with "bugfixes branch"

the sql error is :

 >tail -f /var/www/glpi/files/_log/sql-errors.log
  *** MySQL query error:
  SQL: SELECT DISTINCT `glpi_tickets`.`id` AS id, 'TEST' AS currentuser,
                        `glpi_tickets`.`id` AS `ITEM_Ticket_2`,   `glpi_tickets`.`name` AS `ITEM_Ticket_1`,
                        `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`,
                        `glpi_tickets`.`id` AS `ITEM_Ticket_1_id`, `glpi_tickets`.`content` AS `ITEM_Ticket_1_content`, `glpi_tickets`.`status` AS `ITEM_Ticket_1_status`, `glpi_tickets`.`content` AS `ITEM_Ticket_21`,  `glpi_tickets`.`priority` AS `ITEM_Ticket_3`,  `glpi_tickets`.`date_mod` AS `ITEM_Ticket_19`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`content`, '__NULL__'),
                                               '$#$',`glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`id`)
//                                     ORDER BY `glpi_tickettasks`.`date` DESC
                                       ORDER BY `glpi_tickettasks_d477e94036d739be6fb0229e20c10aeb`.`date` DESC
                                     SEPARATOR '$$##$$')
                                    AS `ITEM_Ticket_26`,

                        GROUP_CONCAT(DISTINCT `glpi_users_f201be21cd638ee780d08cba4ceff0d4`.`id` SEPARATOR '$$##$$')
                                       AS `ITEM_Ticket_5`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`users_id`, ' ',
                                                        `glpi_tickets_users_819efb92c8b927b345e489211ec8e43b`.`alternative_email`)
                                                        SEPARATOR '$$##$$') AS `ITEM_Ticket_5_2`,
                           `glpi_tickets`.`status` AS `ITEM_Ticket_12`,   GROUP_CONCAT(DISTINCT `glpi_users_a5e2026cbcb683e774f93a59e24a62a4`.`id` SEPARATOR '$$##$$')
                                       AS `ITEM_Ticket_4`,
                           GROUP_CONCAT(DISTINCT CONCAT(`glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`users_id`, ' ',
                                                        `glpi_tickets_users_d1524bb2ea1d461ab90aed3b5f0e7e60`.`alternative_email`)
                                                        SEPARATOR '$$##$$') AS `ITEM_Ticket_4_2`,
                            GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`items_id`, '__NULL__'),
                                               '$#$',`glpi_items_tickets`.`id`) ORDER BY `glpi_items_tickets`.`id` SEPARATOR '$$##$$')
                              AS `ITEM_Ticket_13`,

                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_items_tickets`.`itemtype`,
                                                                         '__NULL__'),
                                                   '$#$', `glpi_items_tickets`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$')
                                    AS `ITEM_Ticket_13_itemtype`, `glpi_tickets`.`date` AS `ITEM_Ticket_15`,   GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_tickets`.`takeintoaccount_delay_stat`, '__NULL__'),

**Comment by trasher** [comment]
Try with 9.4 nigthly (link in previous comment).

**Comment by cedric-anne** [comment]
Hi @chauchse ,

I think it has been fixed by #6399 . Could you confirm ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
