### ISSUE TITLE
Emails are sent while the job queuednotification is disabled.

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6601]
**Describe the bug**

Hello,

In my test environment, I disabled sending emails.
queuednotification is _deactivated_.
Nevertheless, some mails leave anyway completely randomly, sending test mails to the mail server, to users.... mixing some old tickets to users, this brings confusion sometimes.

This problem is very annoying and worrying.

**To reproduce**

Disable  queuednotification / do actions that make notifications.
Some times, emails are sent.

**Expected behavior**

emails have to stay in queuednotification while queuednotification job is disabled.

**Logs**
no problem in log
just proof mail are sent by 
cat /var/www/html/glpi/files/_log/mail.log|grep -v file|grep email
says lines staring with : "Un email a été envoyé à xxx@domain.fr(.....)"

GLPI 9.4.4/Ubuntu

**Comment by trasher** [comment]
Some emails has always been sent immediately, not using the mail queue (even if an entry may be created in the table, the behavior is not the same).
Disabling notification queue will not prevent all mails to be sent.

Just disable notifications from setup, notifications.

**Comment by mab18** [comment]
It's not the same thing : setting to not send notifications don't create them at all.
For the same context, sometimes they are send direcly sometimes not...
Do you think it's a normal fonction ? I think it's a bug...
Have you got the list of notification who are send directly ? Who can I give this list ?

**Comment by trasher** [comment]
`emails have to stay in queuednotification while queuednotification job is disabled.` => this assertion is currently false, as I've said; this is a long time behavior, and if this is "documented", this was certainly in the old forge (in a ticket maybe). There is an option in one of the involved methods as far as I remember, I do not remember which exactly.

**Comment by trasher** [comment]
(BTW, this behavior will be reworked as part of the entire notifications system rewrite)
