### ISSUE TITLE
SQL Error when launch cleanhistory.php

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6610]
**Describe the bug**
I run (in CLI, ./GLPI/tools directpory by default) 
`php ./cleanhistory.php --item=SoftwareVersion  --delay=12`
 and I have this error : 

>     Total entries in history : 385108
> Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
>   *** PHP Warning(2): Illegal string offset 'COUNT'
>   Backtrace :
>   inc/dbutils.class.php:327
>   inc/db.function.php:178                            DbUtils->countElementsInTable()
>   tools/cleanhistory.php:141                         countElementsInTable()
>  DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 188
>   *** MySQL query error:
>   SQL: SELECT * FROM `glpi_logs` WHERE cdate_mod` < SUBDATE(NOW(), INTERVAL 12 month)
>   Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '` < SUBDATE(NOW(), INTERVAL 12 month)' at line 1
>   Backtrace :
>   inc/dbmysqliterator.class.php:95
>   inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
>   inc/dbutils.class.php:329                          DBmysql->request()
>   inc/db.function.php:178                            DbUtils->countElementsInTable()
>   tools/cleanhistory.php:141                         countElementsInTable()
>   Selected entries in history : 0

**To reproduce**
```
cd /installofglpi/tools
php ./cleanhistory.php    --delay=12
php ./cleanhistory.php  --item=SoftwareVersion  --delay=12
```

**Expected behavior**
Should return numbers of items to be deleted

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
9.4.4

**Comment by trasher** [comment]
Note: scripts in tools directory are not supported.
