### ISSUE TITLE
GLPI 9.4.4 unable to create additional entities

### ISSUE THREAD

**Issue by reinethernal** [glpi-project/glpi#6611]
**Describe the bug**
When I try to create child entities, I get an error that the rights are not enough rights

**Page(s) URL**
glpi/front/entity.form.php

**To reproduce**

1. Go to 'Entities'
2. Click on 'Add'
3. See error

**Expected behavior**

Create new entity

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

![image](https://user-images.githubusercontent.com/35932698/69244633-58345700-0bb6-11ea-9524-6473b7abd7d7.png)
![image](https://user-images.githubusercontent.com/35932698/69245285-9da55400-0bb7-11ea-9128-99d39751e556.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here



```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

I can reproduce only if I use a 'Super Admin' profile that is not recursive.

Can you check your user authorizations ? If there is no `(R)` beside the 'Super Admin' profile, then it is normal to not be able to create a new entity.
![image](https://user-images.githubusercontent.com/33253653/69418620-59cb5f80-0d1b-11ea-9fe0-d8df375ba07f.png)

Regards

**Comment by reinethernal** [comment]
Hi! 
Profile is not recursive. How can i add a new entity?

**Comment by reinethernal** [comment]
Oops, found it) Thank you)
