### ISSUE TITLE
GLPI 9.4.3 - Image profile returns to default

### ISSUE THREAD

**Issue by wesleyfox** [glpi-project/glpi#6619]
The problem occurs after image upload to the user profile. In "Home> My settings (picture)".

Upon logout and login, the user avatar returns to the default GLPI.

**Comment by trasher** [comment]
This issue has already been fixed

**Comment by wesleyfox** [comment]
> This issue has already been fixed

Version 9.4.4 ?

**Comment by trasher** [comment]
9.4.4 ou current 9.4 nightly, look at the changelog.
