### ISSUE TITLE
No update of IP addresses in inventory

### ISSUE THREAD

**Issue by ashmonger** [glpi-project/glpi#662]
Hello,

I use third-party plugin to update the inventory in GLPI, but the IP addresses are not updated correctly, even if the agents/plugins give a good information (i.e. on a clean new base, everything works, on a old base with lots of stuffs, computers are not completely updated)

When I crawl the database, I can relate IP adresses and computers, but I have to use _glpi_networknames_ and _glpi_networkports_.

With this SQL request, I can relate everything but the _glpi_ipaddresses.mainitems_id_ and _glpi_ipaddresses.mainitemtype_ are not correctly filled, so the links are not directly made on the inventory Computer page, and I cannot search by IP.

`SELECT glpi_computers.id, glpi_computers.name, glpi_ipaddresses.mainitems_id, glpi_ipaddresses.name, glpi_ipaddresses.items_id, glpi_networkports.items_id, glpi_networkports.mac 
FROM glpi_computers
LEFT JOIN glpi_networkports ON glpi_networkports.items_id = glpi_computers.id
LEFT JOIN glpi_networknames ON glpi_networknames.items_id = glpi_networkports.id
LEFT JOIN glpi_ipaddresses ON glpi_ipaddresses.items_id = glpi_networknames.id
ORDER BY glpi_computers.name;`

So I wonder where theses informations (_glpi_ipaddresses.mainitems_id_ and _glpi_ipaddresses.mainitemtype_) are used and why they are not updated if considered as 0 or NULL in the database.

**Comment by yllen** [comment]
mainitemtype is the type of the item (computer, printer...)
mainitems_id is the id of the item
So yes, there are very useful

**Comment by ashmonger** [comment]
Yeah, I don't doubt that!

I just wanted to know why theses informations are not updated when a plugin like Fusioninventory or OCSInventory update information about the computer.

**Comment by orthagh** [comment]
What's the third party program(s) ?

**Comment by ashmonger** [comment]
OCSNG and/or FI, I have tried both.
We plan to migrate from glpi(0.85.2)+ocsng(2.0.5) to glpi(0.90.3)+fi(0.90+1.3).

The thing is no value is locked, but the networkname table isn't up to date, and nothing makes it up to date.

Looks like the update is prevented by something, but can't find what.

I made a little [work-around](https://gist.github.com/ashmonger/7eb11fcf4c02a079f5ed56cf229b067e) to update some stuff, but it's not enough considering the work which have to be done on NetworkEquipments, Printers, and Phones (at last we don't have phone, and so few printers).

**Comment by orthagh** [comment]
You can have two locks tabs if you use Fusioninventory.
* Locks (GLPI native, used by ocs inventory plugin only)
* Locks fields (provided by Fusion)

But ip addresses are not forbidden by theses locks, as i known.
I will check (after lunch) network relative code

**Comment by ashmonger** [comment]
Yup, I've check thoses.

Thanks

**Comment by orthagh** [comment]
new checks : 
In my case, glpi_ipaddresses mainitems_id and mainitemtype are filled with good information on fusioninventory insertion and update

I also tested unlink my ethernet cable and switch to wifi connection.
ip_adresses (and the above fields) are correctly updated

**Comment by ashmonger** [comment]
With fusioninventory the insertion is good, but the update is not.
We had this problem with more than hundred computers.

I agree that when you wipe a computer (emptying the trashcan), the computer is correctly inserted with all informations.

**Comment by orthagh** [comment]
on a customer db i manage (12k computers, 26k ip adresses), no lines in glpi_ipadresses have mainitem* fields empty or null.

What version of the FI plugin do you use ?

**Comment by ashmonger** [comment]
2.3.16 or 2.3.17 for the agent, and 0.90+1.3 for the plugin.

**Comment by cedric-anne** [comment]
Hi @ashmonger ,

This issue has been created a long time ago. Can you check if you can still reproduce ?

Regards

**Comment by ashmonger** [comment]
Hi, don't know. Doesn't work for this company anymore.

Here, it seems to work correctly. Maybe you could close this issue.

> GLPI 9.2.1 Copyright (C) 2015-2017 Teclib' and contributors - Copyright (C) 2003-2015 INDEPNET Development Team
FusionInventory 9.1+1.0 - Copyleft © 2010-2016 by FusionInventory Team

**Comment by cedric-anne** [comment]
Hi,

Thanks for the feedback. I close the issue.

Regards
