### ISSUE TITLE
Entity of Problem / Change from ticket tab

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#663]
When create problem or change from a ticket tab, the entity of the problem /change ins't the ticket entity.

Example : 
Profile Entity 1 - open the ticket form (with child entity)
Launch link to create a problem / change from the ticket
The problem / Change have for entity (not the child entity of the ticket) but the entity of the profile session.

**Comment by yllen** [comment]
It's the comportment for all object created about another.
You can be on a parent entity and want to create a recursive problem/change.

We can easily change this comportment but i want other opinions.

**Comment by cedric-anne** [comment]
Hi,

This enhancement has been done in #5378 and will be available in GLPI 9.4.1.

Regards
