### ISSUE TITLE
api initsession

### ISSUE THREAD

**Issue by manugre** [glpi-project/glpi#6631]
Version : 9.4.3

The InitSession API REST function has a problem :
Header "Authorization: Basic" is not implemented
.. so it could not work 👎 
In the documentation, it should be "Authorization: Basic base64({login}:{password})"

Not implemented in apirest.class.php
Not implemented in inc/api.class.php 

---- Line 478 -- apirest.class.php
... nothing with "Basic" Header

---Line 188 -- inc/api.class.php
protected function initSession($params = []) {
      global $CFG_GLPI;

      $this->checkAppToken();
      $this->logEndpointUsage(__FUNCTION__);

      if ((!isset($params['login'])
           || empty($params['login'])
           || !isset($params['password'])
           || empty($params['password']))
         && (!isset($params['user_token'])
             || empty($params['user_token']))) {
         $this->returnError(__("parameter(s) login, password or user_token are missing"), 400,
                            "ERROR_LOGIN_PARAMETERS_MISSING");
      }

**Comment by flegastelois** [comment]
Hi,

"Authorization: Basic" is implemented and is functional in GLPI REST API.

You can use the forum if you need help to use it.
https://forum.glpi-project.org/viewforum.php?id=23

Regards

**Comment by manugre** [comment]
I'm sorry, but is does not work ...
I'm speaking about basic authorisation in headers

.. everybody seems to use url and not headers way (because basic
authorisation in headers does not work)

**Comment by flegastelois** [comment]
Hi,

I confirm it again, basic authentication in headers works as expected in the documentation :
https://github.com/glpi-project/glpi/blob/9.4/bugfixes/apirest.md#init-session

![image](https://user-images.githubusercontent.com/470612/69646352-f23d4900-1067-11ea-8b1e-eee1d2ea72ce.png)

Maybe your web server intercepts this header, so you have to configure it correctly (search "SetEnvIf Authorization Apache" on the web for example), but it's not a GLPI side implementation problem.

Regards,

**Comment by manugre** [comment]
ok... really strang

thanks,
