### ISSUE TITLE
9.4.4 - Unable to get the ID of the rule in a search answer (with a FIX)

### ISSUE THREAD

**Issue by J-C-P** [glpi-project/glpi#6641]
Hello,

Using the API, I search for a specific rule (using the provided search options).
I found it BUT the ID is not in the answer. This would be very helpful for further manipulations.

By adding 
```     $tab[] = [
         'id'                 => '2',
         'table'              => $this->getTable(),
         'field'              => 'id',
         'name'               => __('ID'),
         'datatype'           => 'number',
         'massiveaction'      => false
      ];
```
after line 696 of the rule.class.php, I get the ID in the search options and in the result.
Could anyone confirm this is how I'm supposed to fix this?
If yes, could you add it to the official repository ?

Thanks, 
JC

**Comment by trasher** [comment]
Hi, please open a pull request with your change proposal. Thank you

**Comment by cedric-anne** [comment]
Done in #6717 .
