### ISSUE TITLE
Ticket notification doesn't have direct pictures 

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6650]
**Describe the bug**
I have a ticket with a pasted picture from a part of my screen in description of the ticket.
The text value "##ticket.description##" does not show the image, there is only an empty frame instead with a error message in it.

**To reproduce**
have notification of new ticket enabled, with ##ticket.description## in. 
Notification by mail have to be enabled too.
Create a new ticket, see in the mail : no picture, just a blank area with a error text who explain the picture doesn't exists (she is in ticket as you could see in pictures below).

**Expected behavior**
Pictures should be in the notification too.

**Logs**
/

**Screenshots**

![GLPI - 2019-11-29 11_37-picture is not in the notification - 01 · Issue #xxx](https://user-images.githubusercontent.com/55535560/69863449-1d5cae00-129d-11ea-9b68-d7f0fcb40c91.png)
![GLPI - 2019-11-29 11_37-picture is not in the notification - 02 · Issue #xxx](https://user-images.githubusercontent.com/55535560/69863450-1d5cae00-129d-11ea-9a93-c768b4b51651.png)

GLPI V 9.4.4

[EDIT 11:44]
Note : The same picture is well working in tasks notifications.

**Comment by cedric-anne** [comment]
Hi,

Could you test #6699 ?

Regards

**Comment by mab18** [comment]
Hi,

Perfect ! #6699 corrects the picture in notification
![image](https://user-images.githubusercontent.com/55535560/70543065-20438280-1b6a-11ea-9c9a-496f28a7944e.png)
