### ISSUE TITLE
Attached file is lost when submitting a new ticket 

### ISSUE THREAD

**Issue by HADDADENICAR** [glpi-project/glpi#6651]
I am using glpi 9.1.2 , when i create  a new ticket i attach to it  an image (file) , before submitting :

    
![image](https://user-images.githubusercontent.com/35377776/69863236-9b6c8500-129c-11ea-98fe-98e78f5364c4.png)

after submitting , i check the new ticket , i found that the image is missing :

 
![image](https://user-images.githubusercontent.com/35377776/69863358-e6869800-129c-11ea-9060-ea3f3517307d.png)

however when i do the same steps in localhost  i get the image displayed :

 
![image](https://user-images.githubusercontent.com/35377776/69864104-9577a380-129e-11ea-8fef-f1a69b6234bc.png)

what is wrong ?

**Comment by trasher** [comment]
GLPI 9.1 is very outdated, consider upgrading
