### ISSUE TITLE
[9.1-dev] Rules broken

### ISSUE THREAD

**Issue by ddurieux** [glpi-project/glpi#666]
Rules are broken on master (works in 0.90).

Like make a software dictionnary.

* Criteria: _regexp_ ```/^7-([a-z]*) (.*)$/```
* Actions : _software_ regexp value ```#0``` and _version_ regexp value ```#1```

Test with _7-zip 2.3_

regex find
```
0	2.3
```
instead
```
0	zip
1	2.3
```

**Problem found with unit test of plugin FusionInventory**

**Comment by guillaumelecerf** [comment]
Broken by https://github.com/glpi-project/glpi/commit/b8fcf32650bd5df985381e69c05bc68f3bac58df#diff-c060826358414cb2b2a882f737189a53L451

**Comment by guillaumelecerf** [comment]
Fixed in #668

**Comment by ddurieux** [comment]
Yes it fix ;)
But Why this bug has been introduced (the commit message is not very clear and no linked to an issue https://github.com/glpi-project/glpi/commit/b8fcf32650bd5df985381e69c05bc68f3bac58df)... but most important is the commit has introduced other bugs?

**Comment by orthagh** [comment]
PR merged
