### ISSUE TITLE
Add User Button

### ISSUE THREAD

**Issue by levifranzen** [glpi-project/glpi#6661]
**Is your feature request related to a problem? Please describe.**
When opening a ticket and selecting the Requester, the "plus" button refers to "Import A User" when it would be more practical to be "Add User", so you can add a new user without leaving the ticket.

**Describe the solution you'd like**
Clicking the "plus" button beside the Requester field prompts to input a new user.

![import a user](https://user-images.githubusercontent.com/35925385/69965934-18de0280-14f4-11ea-843d-93f2d1f0c944.jpg)

**Comment by cedric-anne** [comment]
Hi,

Please use [RFE website](https://glpi.userecho.com/) for feature request, unless you plan to propose a PR for it.

Regards
