### ISSUE TITLE
API Returns Incorrect Software Version Name (Typecasting Issue)

### ISSUE THREAD

**Issue by b1scuit-thi3f** [glpi-project/glpi#6663]
**Describe the bug**

When pulling software version information via the REST API, versions with a single decimal that ends in 0 have the zero trimmed off when pulling back the data. For example, if I request the software version of ID 1559 - relating to a version named "2.10", I would get 2.1 back. I suspect this is because the values are typecast (so 2.10 as a float becomes 2.1).

**Page(s) URL**

https://[URL]/glpi/apirest.php/SoftwareVersion

**To reproduce**

Create a new version on a software asset with something like 1.10, or 2.10, etc
Use the above URL to make a GET request to pull back software version information. You will find you get something like the following back:

{'id': 1559, 'entities_id': 0, 'is_recursive': 0, 'softwares_id': 933, 'states_id': 0, **'name': 2.1**, 'comment': None, 'operatingsystems_id': 0, 'date_mod': '2019-11-29 17:19:51', 'date_creation': '2019-11-29 17:19:51'}

**Expected behaviour**

2.10 should be returned instead. An option to allow all values to be returned as strings would be useful.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Linux itsm01 4.15.0-1050-aws #52-Ubuntu SMP Thu Sep 12 19:56:00 UTC 2019 x86_64
PHP 7.2.24-0ubuntu0.18.04.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at [redacted] Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.28-0ubuntu0.18.04.4
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by trasher** [comment]
This has have been fixed in 9.5 branch (will not be in 9.4, too many low level changes).

**Comment by trasher** [comment]
Dups https://github.com/glpi-project/glpi/issues/2182
