### ISSUE TITLE
9.4.4 Element not present when linked in a ticket

### ISSUE THREAD

**Issue by EnObliO81** [glpi-project/glpi#6678]
Hello, 

When users create a new ticket and link their own computer to it (self-service profile), I'm not able to see it in the ticket overview. There is a tab named "Elements", I'm able to see the small "1" that indicates there is an element linked to the ticket, when I click on this link, the elements overview is displayed but nothing's in it. (Screenshot below)
![image](https://user-images.githubusercontent.com/58559091/70241512-716d0400-176f-11ea-8195-9cbdffd6dea9.png)

I've checked the mysql tables and I founded one named "glpi_items_tickets". In it, there are all the items that are linked to a ticket. And here is the bug... The items_id field is set to "0".... (Screenshot below)
I guess when a user link his computer, the computer_id is not found and set to 0. That's why 0 is displayed in the glpi_items_tickets table.

![image](https://user-images.githubusercontent.com/58559091/70241466-5f8b6100-176f-11ea-9804-7bdd8a48fdbd.png)

Hope it help
Regards,

**Page(s) URL**

Ticket creation  -> https://<PATH_TO_GLPI>/glpi/front/ticket.form.php
Ticket overview -> https://<PATH_TO_GLPI>/glpi/front/ticket.form.php?id=<TICKET_ID>

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
[code]   GLPI 9.4.4 (/glpi => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux it-glpi-vs-tou 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u1 (2019-09-20) x86_64 PHP 7.0.33-0+deb9u5 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, recode, session, shmop, soap, sockets, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi.tlselautrec.local Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36 Server Software: Debian 9.9 	Server Version: 10.1.41-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.1.41) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

Not active

Way of sending emails: SMTP+TLS (helpdesk@clinique-toulouse-lautrec.com@ex3.mail.ovh.net)

 

addressing           Name: Adressage IP                   Version: 2.8.0      State: Enabled 	archires             Name: Architectures réseau           Version: 2.6.0      State: Not installed 	behaviors            Name: Comportements                  Version: 2.2.1      State: Enabled 	mydashboard          Name: Dashboard                      Version: 1.7.4      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.8.5      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled 	geninventorynumber   Name: Génération de numéros d'invent Version: 2.4.0      State: Enabled 	racks                Name: Gestion de baies               Version: 1.8.0      State: Not installed 	manufacturersimports Name: Imports fabricants             Version: 2.2.0      State: Enabled 	pdf                  Name: Impression pdf                 Version: 1.5.0      State: Enabled 	manageentities       Name: Portail Clients                Version: 3.1.0      State: Enabled 	reports              Name: Rapports                       Version: 1.13.1     State: Enabled 	dashboard            Name: Tableau de bord                Version: 0.9.7      State: Enabled
[/code]
```

**Comment by cedric-anne** [comment]
Hi,

I reproduced it by :
1. Creating a ticket with a linked computer.
2. Put the computer into trashbin.
3. Delete permanently the computer.
4. Display the ticket items list.

Is it possible that the computer related to your ticket has been deleted permanently ? In this case #6697 should prevent this issue.

Regards

**Comment by Milo-81** [comment]
Hi in our case this is not from a delete computer. 
This happen with all computers. When a new ticket is create, the user select a computer in the provided list and this happen.

**Comment by EnObliO81** [comment]
Hi, the computer isn't deleted. User create the ticket, link his computer and submit the ticket. Then, I see it in the tickets list, click on it and when I click on Elements, I'm not able to see the computer.
 
But, in the glpi_items_tickets table, 0 is set in the items_id field. 

When I add it manually from the Super Admin view, the value change to the correct one and I'm able to see the computer in the Elements tab.


![image](https://user-images.githubusercontent.com/58559091/70609811-bdea9080-1c02-11ea-810a-85668cb7cf23.png)

**Comment by cedric-anne** [comment]
I reopen this issue as #6697 seems to not fix all cases.

**Comment by cedric-anne** [comment]
Hi,

Sorry, I do not find how to reproduce this bug, using a fresh installation of current state of 9.4/bugfixes branch.

Regards

**Comment by EnObliO81** [comment]
Hi,

I've resolved the problem. It was a problem in the "Default" ticket template. "Associated element" was in required. I've just removed the required option and it resolved my problem :)

Thanks for helping me,
Regards

**Comment by cedric-anne** [comment]
Hi,

I reopen this issue as this behaviour seems not correct. Form should not be validated if field is required.

Regards

**Comment by EnObliO81** [comment]
Yep, I think if the field is in required mode and no element as been selected in the ticket creation, 0 value is returned. That's why 0 is set in the SQL table 

Regards,

**Comment by trasher** [comment]
I've just tested with 9.5, problem seems to be solved; I had the following message trying to reproduce:

> Mandatory fields are not filled. Please correct: Associated elements
