### ISSUE TITLE
Clone Assets

### ISSUE THREAD

**Issue by flonou** [glpi-project/glpi#6682]
**Is your feature request related to a problem? Please describe.**

When adding new assets, we sometimes need to add multiple instances of the same one with few parameters changing (name, serial number)

**Describe the solution you'd like**

The solution I propose is a clone feature so that people can clone an existing object and only change de few different fields (if any)

**Describe alternatives you've considered**

Using templates, which is kind of the opposite way of thinking about the problem : I will have x assets, better create a template vs I already have this asset, I will have x more, better clone it

**Additional context**

I'm willing to submit a PR for this feature. Although I'm not an expert in php and glpi dev, I believe I can provide at least a first step and working solution for most cases.

**Comment by Mirkk** [comment]
Sorry for my ignorance, but was this finally implemented or not, and if yes, how? Linked issue #6684, seems to be, reading the comments, removed from the candidates because of missing tests, and is not set as candidate for the next version. Thanks!

**Comment by trasher** [comment]
Cloning feature is part of GLPI since 9.5.0
