### ISSUE TITLE
Knowledge base - Search folders

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#6683]
Hi @btry 

Starting with version 9.4, browsing through folders has gotten a lot better.

However, is it possible to implement the search field functionality to find knowledge articles? Currently it only searches the folder names.

![image](https://user-images.githubusercontent.com/35368369/70338226-4647ea80-182b-11ea-9a6a-d82c31f6cdf5.png)

**Comment by btry** [comment]
Hi

I guess this request should go in Formcreator ?

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
