### ISSUE TITLE
Error with PHP 5.4

### ISSUE THREAD

**Issue by ddurieux** [glpi-project/glpi#669]
GLPI 0.90 (and master branch) is currently not compatible with PHP 5.4, we have this error:

```
PHPUnit_Framework_Exception: PHP Fatal error:  Can't use method return value in write context in glpi/inc/commondbtm.class.php on line 2298
```

It's because in 

```
         if ($_SESSION['glpiis_ids_visible'] || empty($this->getTypeName(1))) {
```
we can't do empty() on a return of function

**Problem found with unit test of plugin FusionInventory**

**Comment by wawax** [comment]
Could you please provide a pull request to fix the issue ?
thank you

**Comment by ddurieux** [comment]
Not have yet try to fix it, will try find a little time today

**Comment by orthagh** [comment]
I guess #667 is the corresponding PR.

**Comment by ddurieux** [comment]
Yes that's is, not see it ;)
