### ISSUE TITLE
Support for Synology and NetApp

### ISSUE THREAD

**Issue by mskrishna20051974** [glpi-project/glpi#6693]
Hi,

Currently GLPI + Fusion Inventory does not detect NAS devices properly. 

It detects Synology NAS as Network device and there is no category which i can create in GLPI

Is there a way for support of Storage devices in the future?

Regards,
Krishna M S

**Comment by trasher** [comment]
Not sure this is related to GLPI core, but please use [suggestion website](http://suggest.glpi-project.org) for RFE.
