### ISSUE TITLE
"Software deleted after merging" after merging softwares

### ISSUE THREAD

**Issue by laszlokertesz** [glpi-project/glpi#6707]
Glpi version 9.4.2 but it happened on older versions, thi sis an old issue.

Hi,

We use a GLPI 9.4.2 and i had to merge quite a few software entries.
Specifically the Mac Fusion Inventory reported Word/Excel/Outlook installs were reported with a specific Manufacturer entry that contained the version of the program so we  ended up with 100+ entries.
I created a Glpi rule that renames everything that contains "Microsoft Corporation" and is not exactly "Microsoft Corporation" to "Microsoft Corporation". Now the additional entries dissapeared but the older ones i merged into one. I had 2 entries remaining, one of 150, the other of about 40 and i merged them (both entries contain already merged entries).

Now the isssue i face is that the 2 entries become separated and one of them regularly ends up deleted automatically and the category overridden to "FUSION" and a comment added "Software deleted after merging". How i can prevent this?

**Comment by cedric-anne** [comment]
Hi,

It seems that this behaviour is caused by Fusion Inventory plugin. If you need support about this plugin, please use [dedicated forum](https://forum.glpi-project.org/viewforum.php?id=20).

Regards
