### ISSUE TITLE
Category is missing in Hidden fields options. GLPI 0.90.3

### ISSUE THREAD

**Issue by yurisilvano** [glpi-project/glpi#671]
Good morning. I've an issue with the hidden fields. When i edict a template ticket, in "hidden fields" the option "category" is missing.
I already posted a topic with this issue in the GLPI forum, but no one could help me.

The link of the post is http://forum.glpi-project.org/viewtopic.php?id=153885

There i post some prints screens and better develop the subject.

I'm sorry any English mistake.

Server
 
Operating system: Linux monitor.microdest.com.br 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64
PHP 5.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl,
        date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, json, ldap, libxml, mbstring, mhash, mysql, mysqli,
        openssl, pcre, pdo_mysql, pdo_sqlite, session, shmop, sockets, sqlite3, standard, tokenizer, wddx, xml, xmlreader, xmlwriter,
        xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="16M" safe_mode="" session.save_handler="files"
        upload_max_filesize="2M"
Software: Apache/2.4.6 (CentOS) PHP/5.4.16 ()
        Mozilla/5.0 (Windows NT 10.0; WOW64; rv:46.0) Gecko/20100101 Firefox/46.0
Server Software: MySQL Community Server (GPL)
        Server Version: 5.6.30
        Server SQL Mode: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
        Parameters: glpi-microdest@127.0.0.1/glpi_defagro
        Host info: 127.0.0.1 via TCP/IP
       
OK/var/www/html/glpi-defagro/config : OK
OK/var/www/html/glpi-defagro/files : OK
OK/var/www/html/glpi-defagro/files/_dumps : OK
OK/var/www/html/glpi-defagro/files/_sessions : OK
OK/var/www/html/glpi-defagro/files/_cron : OK
OK/var/www/html/glpi-defagro/files/_graphs : OK
OK/var/www/html/glpi-defagro/files/_lock : OK
OK/var/www/html/glpi-defagro/files/_plugins : OK
OK/var/www/html/glpi-defagro/files/_tmp : OK
OK/var/www/html/glpi-defagro/files/_rss : OK
OK/var/www/html/glpi-defagro/files/_uploads : OK
OK/var/www/html/glpi-defagro/files/_pictures : OK
OK/var/www/html/glpi-defagro/files/_log : OK
OKSELinux mode is Permissive
Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect --> off (Some features may require this to be on)
Some features may require this to be onSELinux boolean configuration for httpd_can_network_connect_db --> off (Some features may require this to be on)
Some features may require this to be onSELinux boolean configuration for httpd_can_sendmail --> off (Some features may require this to be on)
 
Libraries
 
htmLawed version 1.1.21 in (/var/www/html/glpi-defagro/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/html/glpi-defagro/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/html/glpi-defagro/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/html/glpi-defagro/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/html/glpi-defagro/lib/Zend)
SimplePie version 1.3.1 in (/var/www/html/glpi-defagro/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/html/glpi-defagro/lib/tcpdf)
ircmaxell/password-compat in (/var/www/html/glpi-defagro/lib/password_compat). Compatitility: Ok
 
Mysql replics
 
Not active
 
Notifications
 
Way of sending emails: SMTP (helpdesk@defagro.com.br@smtp.defagro.com.br)
 
Mails receivers
 
 
Plugins list
 
        dashboard            Name: Painel                         Version: 0.7.3      State: Enabled

**Comment by flegastelois** [comment]
Hi,

As yllen has told you, this is not possible in GLPi to hide the category field in the simplified interface, "because you can have a ticket template associate to the categorie".

Regards,

**Comment by yurisilvano** [comment]
Hi flegastelois, I'm sorry the question but I'm kind of layman.
So there's no way to hide the category field?
Or is there any procedure so that I can disable it?

Tks.

**Comment by tomolimo** [comment]
Hello,
Would you like to hide the 'ticket category' for simplified interface only or also for complete interface?
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello,
You may use the following plugin: https://github.com/tomolimo/hidefields
regards,
Tomolimo

**Comment by yllen** [comment]
It's not a bug of GLPI.
Since the template of ticket was created (0.83), you never can't hide Category field
