### ISSUE TITLE
Insert file menu doesn't display an explorer

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6725]
**Describe the bug**
When creating a ticket, we can insert a file with "insert/modify a picture", this little panel doesn't have an explorer, so we have to type the entire directory chain+name of file.

**To reproduce**

1. Go to create a ticket
2. go to description and click on insert/update a picture 
3. no selection of directory/file is shown
4. have to type the precise directory chain + name of file

**Expected behavior**
Add a little explorer to select the file with mouse.

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/70924123-4dd87200-2029-11ea-803d-82c2fc21bbe8.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
9.4.4

**Comment by trasher** [comment]
This screen is from the TinyMCE editor, I'm not sure tinymce provides anything else. 
But you can paste or grag & drop in the editor at least.

**Comment by mab18** [comment]
Thanks for the answer.
