### ISSUE TITLE
[GLPI 9.3.3 to 9.4.4]  Ticket Template Does Not Follow Entity Rule

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#6737]
I use Administration> Entities> Assistance> Automatic Assignment of Tickets> Based on the category then the item
It has long used this rule to automate ticket type classification. However, after I realized that the rule is not working.
If I go to Assistance> Create Ticket and select the category, GLPI will use the registered template, but it is not changing the “type”

Field Standardization (Ticket Model)

![1](https://user-images.githubusercontent.com/35368369/71474428-24061480-27ba-11ea-94c0-f0271f627874.png)

Ticket Categories

![2](https://user-images.githubusercontent.com/35368369/71474440-308a6d00-27ba-11ea-92c6-f2ca76371848.png)

However,. When I open a new Ticket he is not reading the rule

![3](https://user-images.githubusercontent.com/35368369/71474447-3f711f80-27ba-11ea-87da-1f81bc4631d2.png)

1. Go to --> Assistance > Create Ticket
2. Click on --> Select the category
3. See error --> Type of ticket dont chance based on Rules of entities

**Expected behavior**

When selecting the category, the ticket type should be changed to the ticket template.

**Your GLPI setup

- GLPI 9.3.3 + 9..4.4 + 9.4.3

**Comment by phamorais** [comment]
Anyone else with this problem?

**Comment by flegastelois** [comment]
(Internal 18871)

**Comment by orthagh** [comment]
I copy my answer on private support here:

> Hello.
> 
> Regarding the current code, it appears the current behavior is needed to have the template system working.
> 
> Here is the priority list of template application when creating a ticket:
> 
> - First, get the default template defined for the ticket's entity.
> - If none, get the user's profile one.
> - Then if a type-category couple is defined, get the associated template.
> 
> In this last case and when the user change one of the both parameters, it triggers template reload and so type and category are removed from default predefined data to prevent loop in template loading.
> Other cases, like loading templates from entities or profiles get the additionnal data (type and category) as they don't serve as trigger.
> 
> I don't have easy workaround for you, but maybe you can test formcreator plugin (developped by us) to construct a service catalog tailored for your needs (custom forms presented to your final users).
> See: https://plugins.glpi-project.org/#/plugin/formcreator
> 
> Regards

I close for the moment, feel free to continue discussion here if you need
