### ISSUE TITLE
Windows Mail/ Android mail client mail collector

### ISSUE THREAD

**Issue by povkinasss** [glpi-project/glpi#6762]
MailCollector denies tickets from the WindowsMail client and from some Android OS. 
In php-error.log we can see the message with current error:
[2020-01-02 13:31:59] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined property: stdClass::$message_id
  Backtrace :
  inc/mailcollector.class.php:1360
  inc/mailcollector.class.php:825                    MailCollector->getHeaders()
  inc/mailcollector.class.php:680                    MailCollector->buildTicket()
  front/mailcollector.form.php:77                    MailCollector->collect()
  {"user":"6@rep"}

From that message we assume that php cannot get message_id from the email headers. 
We've added IF before the assignation. 
before 1358 line (version 9.4.4)
 if (!isset($mail_header->message_id)) {
            $mail_header->message_id = '';
         }

After that fix all , message is not blacklisted and accepted by mailcollector.

**Comment by trasher** [comment]
All this has changed a lot for 9.5; and I'm not able to propose a atch that would not potentially breaks collector :/
And since there are no automatic tests (I've added that for 9.5); we prefer not to include unpredictable regressions in a bugfixes release.
