### ISSUE TITLE
Empty showlist on some items

### ISSUE THREAD

**Issue by drTr0jan** [glpi-project/glpi#6766]
There's an empty showlist in case of using the items with digit trailed type-name.

**Logs**

```
[2020-01-05 20:00:13] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): Undefined index: PluginGenericobjectTest5_2
  Backtrace :
  inc/search.class.php:6183
  inc/search.class.php:1445                          Search::giveItem()
  inc/search.class.php:98                            Search::constructData()
  inc/search.class.php:80                            Search::showList()
  plugins/genericobject/front/object.php:35          Search::show()
```

**Screenshots**

![correct-show](https://user-images.githubusercontent.com/10733191/71778183-3a03a880-2ff6-11ea-85e8-a388af5895f4.png)
![incorrect-show](https://user-images.githubusercontent.com/10733191/71778184-3a9c3f00-2ff6-11ea-99c1-010bcd2889a6.png)

**Additional context**

The problem was appeared after #4802.
There's an regexp in constructData()@inc/search.class.php:1368:
`if (preg_match('/ITEM(_(\w[^\d]+))?_(\d+)(_(.+))?/', $key, $matches))`
And `ITEM_PluginGenericobjectTest5_2` isn't matched by the regexp.
Why is `[^d]` using at the regexp?
There is no a problem without `[^d]`.

**Comment by cedric-anne** [comment]
Already discussed in #5495.

This have to be solved in plugins. For genericobject, it will be solved by https://github.com/pluginsGLPI/genericobject/pull/247 , but this fix is based on some methods intoduced in GLPI 9.5.
