### ISSUE TITLE
cron and fastcgi

### ISSUE THREAD

**Issue by manugre** [glpi-project/glpi#6780]
php-error.log:
```
[2019-11-30 23:48:02] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/restricted/ssh/XXXX/www/portail/glpi/inc/toolbox.class.php line 659
  *** PHP Notice(8): **Undefined index: SCRIPT_FILENAME**
  Backtrace :
  inc/autoload.function.php:55                       
  inc/includes.php:150                               isAPI()
  front/cron.php:38                                  include()
  {"user":"@XXX"}
```

==> I have to modify  **inc/autoload.function.php**
**Ligne 55 / function IsAPI():
Add :**
```
if (!isset($_SERVER["SCRIPT_FILENAME"]) || empty($_SERVER["SCRIPT_FILENAME"])) {
      return false;
```

And **Function isCommandLine() does not return good value**
```
 inc/autoload.function.php ligne 45,
return (PHP_SAPI == 'cli');  
```
==> in my case, return : PHP_SAPI = 'cgi-fcgi' even if I call it via command line

Solution ==>
```
    return (!isset($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' || (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)));
```

[code]
 
GLPI 9.4.5 (/glpi => /var/www/restricted/ssh/XXXX/www/portail/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux web27 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64
PHP 7.1.18 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date,
	dom, exif, fileinfo, filter, ftp, gd, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre,
	pdo_mysql, pdo_sqlite, posix, readline, session, soap, sqlite3, standard, tidy, tokenizer, xml, xmlreader, xmlwriter, xsl, zip,
	zlib)
Setup: max_execution_time="60" memory_limit="1200M" post_max_size="1000M" safe_mode="" session.save_handler="files"
	upload_max_filesize="1000M" 
Software: Apache (Apache Server at portail.XXXX Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0
Server Software: Debian 9.8
	Server Version: 10.1.38-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: XXXX@XXX/XXXX
	Host info: web27 via TCP/IP
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
exif extension is installed
APCu extension is not present
xmlrpc extension is not present
CAS extension is not present
Database version seems correct (10.1.38) - Perfect!Database version seems correct (10.1.38) - Perfect!
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_log : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/config : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_dumps : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_sessions : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_cron : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_graphs : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_lock : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_plugins : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_tmp : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_cache : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_rss : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_uploads : OK
OK/var/www/restricted/ssh/XXXX/www/portail/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries

 
htmLawed version 1.2.4 in (/var/www/restricted/ssh/XXXX/www/portail/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.2 in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.2.26 in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/restricted/ssh/XXXX/www/portail/glpi/vendor/leafo/scssphp/src)

SQL replicas

 
Not active

Notifications

 
Way of sending emails: PHP

Mails receivers

 

Plugins list

 
	fields               Name: Champs supplémentaires         Version: 1.10.1     State: Enabled
	behaviors            Name: Comportements                  Version: 2.2.1      State: Enabled
	genericobject        Name: Gestion d'objets               Version: 2.7.0      State: Enabled
	reports              Name: Rapports                       Version: 1.13.1     State: Enabled

[/code]

**Comment by cedric-anne** [comment]
Hi,

Indeed, this case should be investigated. I quickly took a look at PHP doc and it seems that it is a common behaviour of `php-cgi` (see https://www.php.net/manual/fr/function.php-sapi-name.php#89858 ).

You can propose a PR if you think you have a good solution for that.

Regards

**Comment by manugre** [comment]
.. ok, 
but my knowledge stop here
I am not able to propose a propre PR ;

**Comment by manugre** [comment]
I did this commit
https://github.com/manugre/glpi/commit/15ac84f51899e5922af2f7562ab41cd08a179afb#diff-727b8f2d9dba8c1391a0cbd157ee257a

**Comment by cedric-anne** [comment]
Hi,

Can you test #6840 ?

Regards

**Comment by manugre** [comment]
I tested..
did not work, sorry
no error message, but the queuednotification did not start.  Nothing in log.
It statred as soon as I put this : 

    return (!isset($_SERVER['SERVER_SOFTWARE']) && (php_sapi_name() == 'cli' || (is_numeric($_SERVER['argc']) && $_SERVER['argc'] > 0)));
  //  return PHP_SAPI == 'cli' || (PHP_SAPI == 'cgi-fcgi' && defined('STDIN'));

**Comment by manugre** [comment]
The second part  -in IsAPI() funtction is ok
Succed
this worl 👍 👍  :
	/*
	if (!isset($_SERVER["SCRIPT_FILENAME"]) || empty($_SERVER["SCRIPT_FILENAME"])) {
      return false;
    }
   if (strpos($_SERVER['SCRIPT_FILENAME'], 'apirest.php') !== false) {
      return true;
   }
   if (strpos($_SERVER['SCRIPT_FILENAME'], 'apixmlrpc.php') !== false) {
      return true;
   }
   return false;
   */
   $script = isset($_SERVER['SCRIPT_FILENAME']) ? $_SERVER['SCRIPT_FILENAME'] : '';
   if (strpos($script, 'apirest.php') !== false) {
      return true;
   }
   if (strpos($script, 'apixmlrpc.php') !== false) {
      return true;
   }
   return false;

**Comment by cedric-anne** [comment]
Hi,

I am not confident with using `(!isset($_SERVER['SERVER_SOFTWARE'])` for everybody, as it is hardly testable and may have a huge impact.

What is the content of your crontab ?

If call to GLPI cron looks like `php /path/to//usr/local/bin/php`,  can you try to call php cli using its full path (`/usr/local/bin/php  /path/to//usr/local/bin/php`) ?

Regards

**Comment by manugre** [comment]
here the glpi line :
  [30] => */5 * * * * /var/www/restricted/ssh/XXX/cgi-bin/php /var/www/restricted/ssh/XX/www/portail/glpi/front/cron.php --debug

**Comment by cedric-anne** [comment]
Hi,

I am not sure that we should handle. Indeed, you are using PHP-CGI from a CLI context, but PHP-CGI is made to serve website pages. Handling this could be really tricky and we recommand you to call PHP from its CLI executable when you are on CLI context.

Here is a list of main differences between PHP-CGI and PHP-CLI: http://www.php-cli.com/php-cli-cgi.shtml.

Regards
