### ISSUE TITLE
[GLPI 0.90.3]

### ISSUE THREAD

**Issue by chauchse** [glpi-project/glpi#679]
Dear,

I have recently install the genericobject plugin. I would like use it in helpdesk.

I can't really use it  :-(

I am able to :
- Install the plugin
- Activate the plugin
- Define a new object
- Create several entries for the new object

When i try to assign it to heldesk (by behavior object tab and in each entries), i can't see it when i create new tickets.
(I tried with and without group and/or users)

Edit : It works fine in project but not in helpdesk
The only error in phplog is :
` tail /var/www/glpi/files/_log/php-errors.log
2016-05-24 14:04:25
  *** PHP Warning(2): array_search() expects parameter 2 to be array, null given
  Backtrace :
  :
  plugins/genericobject/inc/type.class.php:278       array_search()
  inc/commondbtm.class.php:1329                      PluginGenericobjectType->pre_deleteItem()
  inc/massiveaction.class.php:1076                   CommonDBTM->delete()
  inc/massiveaction.class.php:991                    MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:970                    MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:62                         MassiveAction->process()
`
Thank  you for your help
(Ubuntu server)

**Comment by flegastelois** [comment]
Hi, 

Please open your issue on genericobject project : 
https://github.com/TECLIB/genericobject

Thank's.

**Comment by chauchse** [comment]
Sorry, it's a mistake ;)
