### ISSUE TITLE
[9.4 bugfixes] - garbage in rich text areas

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#6795]
![image](https://user-images.githubusercontent.com/14139801/72146534-f796ee80-339c-11ea-86fb-44432f0f25db.png)

To reproduce : create a ticket, and view the HTML code of the description text area. The garbage is present in the empty form, no need to save the ticket.

**Comment by trasher** [comment]
Tested on several versions from several peron, we cannot reproduce

**Comment by btry** [comment]
I tried with an other browser, and the problem vanished. I may have an extension with something suspicious

**Comment by btry** [comment]
removed some extensions and the bug disappeared. one of them had a malicious code
