### ISSUE TITLE
Transparent image loses transparency on GLPI and gets a black background

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#6797]
**Describe the bug**

Our corporate email signature has an image with a transparent background.
Whenever we get a new ticket, on GLPI the image appears ok, but the email that the client receives, sends that same image with a black background!
In our case it stays a black rectangle, since the letters on the image are all black :(

Why ????

Another test I made, was to upload a completely different image, with transparent background, using the followup menu,  and that image was then sent by GLPI email.
The image appeared with a black blackground to...

Original:
![image](https://user-images.githubusercontent.com/43515938/72152782-e7ced880-33a3-11ea-9e6c-25ec375fd4bc.png)

Received:
![image](https://user-images.githubusercontent.com/43515938/72152808-fcab6c00-33a3-11ea-8766-ad3a538477d0.png)

**Comment by cedric-anne** [comment]
Hi,

#6839 should fix this issue.

Regards
