### ISSUE TITLE
Anyone can access devices from assets

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#6798]
**Describe the bug**

When defining some devices types to be displayed in asset menu (in `Setup > General > Assets` tab), these devices appears in menu of any user using the standard interface, whatever his rights.

Note that it is also possible to access this list with direct URL, even for devices that are not displayed in assets menu.

**To reproduce**

1. Go in `Setup > General > Assets` and add a device type in `Devices displayed in menu` field.
2. Create a profile having no rights on assets nor components.
3. Create a user using this profile.
4. Login with created user.
5. See that user has an asset menu with an entry to device type selected in step 1.

**Expected behavior**

User should not have this menu entry.

**Logs**

.

**Screenshots**

![image](https://user-images.githubusercontent.com/33253653/72247796-fd3b4100-35f5-11ea-995d-89b483d9dc00.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.0-dev-git-9.5/bugfixes-19254862d0 ( => /var/www/glpi)
Installation mode: GIT
```

**Additional informations**

Removing the `Item_Devices::canView()` override, which always return `tru`, fixes this problem, but I do not know if it has any side-effect.

**Comment by trasher** [comment]
More than having just a menu entry, user can access to simcards page.
