### ISSUE TITLE
Cannot link items to user when user has no authorizations

### ISSUE THREAD

**Issue by sbraz** [glpi-project/glpi#6804]
**Describe the bug**
When editing computers, peripherals and other items, I can only select users which have authorizations from the `User` dropdown, .

**Page(s) URL**
`/front/computer.form.php`

**To reproduce**

1. Go to `Computers`
2. Select the `User` dropdown
3. Search for a user that has no authorizations

**Expected behavior**
It should be possible to select users without authorizations.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.3.1 (/glpi => /usr/share/glpi)
Installation mode: RPM
```

**Additional context**

Users are displayed properly when I set `users_id` manually in the database.

**Comment by cedric-anne** [comment]
Hi,

Can you check on 9.4.5 if the error is still present ?

Regards

**Comment by sbraz** [comment]
@cedric-anne I will try to update my instance and try that.

You seem to maintain the file injection plugin. Would it work there too after the update? Should I open an issue for the plugin as well?

**Comment by cedric-anne** [comment]
I just updated code of the plugin to handle deprecations from GLPI. Latest release should be compatible with GLPI 9.4.

**Comment by sbraz** [comment]
@cedric-anne the error is still here with version 9.4.5.
