### ISSUE TITLE
deleted ticket cannot be deleted in a knowledge base entry

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6810]
**Describe the bug**
A ticket is deleted who was linked in a item of the knowbase and it appears in the item as "-1 " and is unable to delete.

**Page(s) URL**
myIP/glpi/front/knowbaseitem.form.php?id=myidoftheknowbaseitem

**To reproduce**
I think : the ticket was deleted OR the ticket was fusionned with another.
To delete it, I updated by SQL:

> UPDATE`` `glpi_knowbaseitems_items` SET `items_id` = 'AValidTicket' WHERE `glpi_knowbaseitems_items`.`id` = myidoftheknowbaseitem

** It should be possible to delete this inconsistency or have automatic deletion of this record when deleting/fusionning ticket.

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/72363636-71104300-36f5-11ea-8b9f-27c92d5764d8.png)
Debug is : 
![image](https://user-images.githubusercontent.com/55535560/72364139-4672ba00-36f6-11ea-80ed-d6b36eeb231c.png)
![image](https://user-images.githubusercontent.com/55535560/72364699-3a3b2c80-36f7-11ea-96c3-ce08534a7248.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.4.5

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug. When an item is deleted, a link to it remains in KB.

#6837 should fix this for future deletions.

Regards
