### ISSUE TITLE
Error: Illegal mix of collations for operation 'like'

### ISSUE THREAD

**Issue by yanxu4780** [glpi-project/glpi#6816]
**Describe the bug**

Filter box cannot search Chinese.

Mysql Version is 5.6.39

**Page(s) URL**

Default homepage

**To reproduce**

1. Go to 'Default homepage'
2. Click on 'Filter '
3. Search any Chinese words

**Expected behavior**

**Logs**

```
The log show Error: Illegal mix of collations for operation 'like'.
inc/search.class.php:1194                          
inc/search.class.php:98                            Search::constructData()
front/search.php:60                                Search::showList()
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

GLPI 9.4.5
--


```

**Additional context**

I found the solution.
Modify inc/search.class.php:7616.
Change "like" to "like binary".
And It works.

**Comment by trasher** [comment]
GLPI setup and version are missing
