### ISSUE TITLE
[APIREST][9.4.5] ProjectTask display restriction

### ISSUE THREAD

**Issue by Belface** [glpi-project/glpi#6818]
Hello
I try to display all Project Tasks using the request **[ServeurName]/apirest.php/search/ProjectTask**
This returns only Project Tasks for which the user (defined for the "user token" request) is a team member of the task team.

![Capture](https://user-images.githubusercontent.com/55400519/72600807-9d55da80-3914-11ea-88d0-96f9ec8940c0.JPG)

_In this example, I use the **MyUserName** "User Token" in my request. It returns only Project tasks where **MyUserName** is defined as member of the task team._

How can I retreive all Project Tasks from all projects (even if my user is not member of the task team) ?

What I tried :
- same request with root "user token" : NOK
- applying super-admin rights to **MyUserName** account : NOK
- connecting to GLPI web interface with **MyUserName** account : it works, I can list/access projects, project tasks, ...

Thanks for your help

**Comment by J-C-P** [comment]
The problem is still there in 9.5.5
How can we solve that ?

Thanks !

**Comment by masakazuwatanabe** [comment]
I am also in trouble with this problem.
This problem also occurs in Ver9.5.7.

If "See all" in "Projects" of "Profile" is checked,

![profile01](https://user-images.githubusercontent.com/16225492/160785018-eb149868-0a03-4c67-a141-163bad4fc265.png)

- All projects can be displayed
- All project tasks can be displayed

![project01](https://user-images.githubusercontent.com/16225492/160785115-7f857741-14a3-4b5b-ae4f-b37b61a717e1.png)
![projecttask01](https://user-images.githubusercontent.com/16225492/160785123-092f5e45-892b-485d-8872-7b5bf039c10a.png)

but,

* Allow API to the same user
* Get the list of "Project Task" by REST-API with the same user
It seems that only the ones associated as "Task Teams" are displayed when I execute.
(Operation equivalent to "MyTasks"?)

After confirming how the conditions are met in REST-API
In "Project", if there is "Project :: READALL", it will be displayed, but
There is no such condition in "ProjectTask", and it seems that a condition equivalent to "MyTasks" is added.

https://github.com/glpi-project/glpi/blob/e9b16bc8e9b61ebb2d35b96b9c71cd25c5af9e48/inc/search.class.php#L3878-L3908

If all projects have permissions
Just as the WebUI shows all the tasks,
I also want to get a list of all tasks in REST-API.
