### ISSUE TITLE
[9.4.5] Financial and administrative information alerts error mass import

### ISSUE THREAD

**Issue by prohand** [glpi-project/glpi#6819]
Hello,

I encounter a problem when I want to activate mass alerts on financial and administrative information

To reproduce the problem:

Go to: Park -> Computer -> Select 1 or more computer -> Actions -> Select "Activate financial and administrative information"

And popup with error: Operation failed
(0 rights issues, 1 failures)
N / A: Unable to retrieve the item

On the other hand if I go directly in the form of the computer, I can activate the parameter.

I have about 200 activated and the mass operation would be simpler.
I tried to deactivate all the plugins but I have the same problem.

GLPI version: 9.4.5

If you need more information don't hesitate;)

Thank you

**Comment by cedric-anne** [comment]
Hi,

This message appears when trying to activate financial and administrative informations on an item that already have this state.

#6836 should fix the issue.

Regards
