### ISSUE TITLE
[9.4.3 or 9.4.5] Plugins in "error / to be cleaned" state after GLPI upgrade

### ISSUE THREAD

**Issue by JackBauer78** [glpi-project/glpi#6820]
**Describe the bug**

After GLPI upgrade from 9.4.2 to 9.4.3 or 9.4.5, almost all the plugins I have are in "error / to be cleaned" state.
I upgraded all the plugins to the last version before the GLPI upgrade.

**Page(s) URL**

/front/plugin.php

**To reproduce**

Upgrade GLPI from 9.4.2 to 9.4.3 or 9.4.5

**Expected behavior**

All the plugins working normally after a GLPI upgrade.

**Screenshots**

![image](https://user-images.githubusercontent.com/44880890/72682322-164b6280-3acc-11ea-8a66-2b3df68e61d8.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Informations sur le système, l'installation et la configuration
--
[code]   GLPI 9.4.3 ( => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux svtl-web01 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 PHP 7.3.12-1+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, 	json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at glpitest2 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0 Server Software: (Ubuntu) 	Server Version: 5.7.28-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (5.7.28) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)

Server: 'taken out', Port: '389', BaseDN: 'taken out', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'taken out', Use TLS: 		none

Not active

Way of sending emails: SMTP (taken out)


fields               Name: Champs supplémentaires         Version: 1.10.2     State: To be cleaned 	behaviors            Name: Comportements                  Version: 2.2.2      State: To be cleaned 	mydashboard          Name: Dashboard                      Version: 1.7.7      State: To be cleaned 	formcreator          Name: Form Creator                   Version: 2.9.1      State: To be cleaned 	fusioninventory      Name: FusionInventory                Version: 9.4+2.3    State: To be cleaned 	flyvemdm             Name: Gestion d'appareil mobile Flyv Version: 2.0.0      State: To be cleaned 	manufacturersimports Name: Imports fabricants             Version: 2.2.1      State: To be cleaned 	pdf                  Name: Impression pdf                 Version: 1.6.0      State: To be cleaned 	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: To be cleaned 	metabase             Name: metabase                       Version: 1.0.0      State: To be cleaned 	mreporting           Name: Plus de rapports               Version: 1.6.1      State: To be cleaned 	reports              Name: Rapports                       Version: 1.13.1     State: To be cleaned 	dashboard            Name: Tableau de bord                Version: 0.9.8      State: To be cleaned 	vip                  Name: VIP                            Version: 1.6.0      State: To be cleaned
[/code]



```

**Comment by cedric-anne** [comment]
Hi,

Plugin state is set as "to be cleaned" when system is not able to load its informations from plugin `setup.php` file during plugins loading. It means that, at a given moment, your GLPI tried to load plugins that were not present in plugins directory or not readable.

Regards

**Comment by mab18** [comment]
N'auriez-vous pas des répertoires en trop dans ./plugins, des versions différentes d'un même plugin ou encore un nom de répertoire de plugin qui n'est pas le bon ?

**Comment by JackBauer78** [comment]
@cedric-anne 
Thank you for this information.

@mab18 
After the GLPI update, the ./plugins directory was empty, so I took the extracted folder from the last version of the plugin's compressed file and I moved it to the ./plugins folder. I did a `chown -R www-data:www-data` and `chmod 755 -R` on the folder as always and still the same.
I tried to take the plugin's folder in the 9.4.2 GLPI ./plugins folder that worked before the GLPI update, but that was the same thing.

However, I have some plugins working and I can't understand why.

I always delete or move the old versions in ./plugins

**Comment by mab18** [comment]
@JackBauer78  
hi !
your tests are interesting...
thanks for your feedback

**Comment by JackBauer78** [comment]
@mab18 @cedric-anne 
Hi !
I tried to update to GLPI 9.4.6 today and I still have the same issue.

To sum up : after the GLPI upgrade, if I install the same version of any plugin by putting the folder (the one I just freshly extracted from tar file) into the plugin folder, it doesn't work : the state of the plugin stays "to be cleaned".
But if I install a new version of any plugin, the plugin works.

@cedric-anne gave me an interesting information but I don't know what to do with it.

Do you have any idea ?
Thank you in advance.

**Comment by cedric-anne** [comment]
> @mab18 @cedric-anne
> Hi !
> I tried to update to GLPI 9.4.6 today and I still have the same issue.
> 
> To sum up : after the GLPI upgrade, if I install the same version of any plugin by putting the folder (the one I just freshly extracted from tar file) into the plugin folder, it doesn't work : the state of the plugin stays "to be cleaned".
> But if I install a new version of any plugin, the plugin works.
> 
> @cedric-anne gave me an interesting information but I don't know what to do with it.
> 
> Do you have any idea ?
> Thank you in advance.

You have to restore your plugins directory "before running" the GLPI upgrade. If you run the GLPI upgrade before, it will not detect your plugins and will set them as "to be cleaned".

**Comment by JackBauer78** [comment]
Ok, it sounds logic.
Do you know how to restore the plugins directory ?
I don't know how to do it and it seems to work fine before the upgrade.

**Comment by cedric-anne** [comment]
> Ok, it sounds logic.
> Do you know how to restore the plugins directory ?
> I don't know how to do it and it seems to work fine before the upgrade.

Just copy it from your old GLPI installation.

**Comment by cedric-anne** [comment]
Hi,

This "error / to be cleaned" state will not dissapear just by putting back your plugins directory. This behaviour will change on GLPI 9.5, but will remains on previous versions. If you do not want to have this state, you should never run any GLPI script nor display any GLPI page when plugins directories are not present.

So, when you manage to upgrade GLPI, you have to restore your plugins directories before running the upgrade process.

If you cannot rollbak to the previous state, just click and the "clean" button, then on "install" and "activate". If plugin handles this correctly, you should not loose any data, but it depends on how plugin is built.

I will not continue anymore this discussion. If you need support, please use forums.

Regards

**Comment by JackBauer78** [comment]
> Hi,
> 
> This "error / to be cleaned" state will not dissapear just by putting back your plugins directory. This behaviour will change on GLPI 9.5, but will remains on previous versions. If you do not want to have this state, you should never run any GLPI script nor display any GLPI page when plugins directories are not present.
> 
> So, when you manage to upgrade GLPI, you have to restore your plugins directories before running the upgrade process.
> 
> If you cannot rollbak to the previous state, just click and the "clean" button, then on "install" and "activate". If plugin handles this correctly, you should not loose any data, but it depends on how plugin is built.
> 
> I will not continue anymore this discussion. If you need support, please use [forums](https://forum.glpi-project.org/).
> 
> Regards

I did exactly as you said there and it works !!!
I moved the running glpi folder to another location.
I put the newly extracted one to /var/www, I did a `chown -R www-data:www-data /var/www/glpi` and a `chmod -R 755 /var/www/glpi` and I put as you said.
I took all the plugins folders from the old glpi installation and I moved them to the new glpi installation plugin folder.
After that, I launched GLPI and I did the update as usual and when it was over, all the plugins were working normally.

So thank you very much @cedric-anne for your time and your help.
I hope this issue will help someone else.
