### ISSUE TITLE
In a problem, when you delete a task, you don't see its number in the history.

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6822]
**Describe the bug**
Id of a task in a problem is not shown in history when deleted.

**To reproduce**
In a problem, add a new task.
Delete it, go to history of this problem, id of deleted task is not shown, just a "( )". See snapshot below.

**Expected behavior**
We should see wich number has been deleted in history.

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/72719075-73e8b900-3b77-11ea-8839-7b90b3f46dd9.png)

**Additional context**
GLPI v9.4.5

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug, but it is not simple to fix and would not be done in 9.4.x as it may have lot of side effects.

Technical explanaition is that `CommonITILTask` extends `CommonDBTM` instead of extending `CommonDBChild`.

Regards
