### ISSUE TITLE
Unable to add or view a document in a problem

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6823]
**Describe the bug**
Go to a new problem, there is no function to add a document. But we can see zero document are related.
It's possible to add one by add in document page, and add the problem, it's not convienient at all and wee can't see documents when we are in the problem. We can see "1 document associé" clickable, but not functionnal.

**To reproduce**
Create a new problem.
We have to tool or link to add a document in it.

Second time, go to documents menu, add the problem to this document.
Back to the problem : click on "1 document associé" does nothing.

**Expected behavior**
Have tthe ability to add document directly in problem, and when document are added, can have the list of them and can open them.

**Logs**
NA

**Screenshots**
![image](https://user-images.githubusercontent.com/55535560/72721907-5fa7ba80-3b7d-11ea-87d9-e384536f5c46.png)

**Additional context**
GLPI 9.4.5

**Comment by cedric-anne** [comment]
Hi,

You can add documents in the `Processing problem` tab of the problem with this button: 
![image](https://user-images.githubusercontent.com/33253653/72972029-f917dc00-3dca-11ea-9dd8-4561f281b889.png).

Documents will be shown in this tab. You can use filters accessible at upper right corner to display only documents.

Regards

**Comment by mab18** [comment]
Hi, 
Thanks many for the answer and explanation. 
It remains that it's disturbing to see this link doing nothing when you click on it.

**Comment by cedric-anne** [comment]
Hi,

I focused on the ability to manage documents and did not take this point into account. This link was pointing on something that has been removed in 9.4. It has to be removed (see #6845 ).

Regards
