### ISSUE TITLE
Queued notifications don’t working.

### ISSUE THREAD

**Issue by paulovictorml** [glpi-project/glpi#6825]
Hello everyone. I’ve made a new installation of the GLPI 9.4.5 in a server and i configured the emails from tickets to send to the users. The job run if i click in ‘run now’ the queuednotifications on the Configure>Automatic actions>queuednotifications, but if i configure the time to send emails in 1 or 5 minutes the action don’t execute the job to sent those emails.

I made a test: i reopened 10 tickets and close in order (1 to 10) to see the queue of notifications via email. Two emails wasn’t sent because they haven’t a email configured, three was sent normally and five still stuck in the queue.

**Expected behavior**

The job queuednotifications running automatically in time pre configured.

**Logs**

mail-debug.log
https://imgur.com/YELK3iW
cron.log
https://imgur.com/3b9S4T2
mail.log
https://imgur.com/1et8mCs

**Screenshots**

Queuednotifications don't working
https://imgur.com/UinbO00

Emails in Queue
https://imgur.com/iLIcroo

Email 'stuck in time' since 3 days ago
https://imgur.com/EnwRKw4

**GLPI setup**

```
Server
 
Operating system: Linux Srv-Web-02 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64
PHP 7.3.13-1+0~20191218.50+debian9~1.gbp23c2da apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
	apache2handler, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="400M" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="80M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at 192.168.0.30 Port 8090)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Server Software: Debian 9.9
	Server Version: 10.1.41-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: glpi@localhost:8090/chamadosti
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
imap extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
exif extension is installed
ldap extension is not present
APCu extension is not present
CAS extension is not present
Database version seems correct (10.1.41) - Perfect!Database version seems correct (10.1.41) - Perfect!
OK/var/www/html/chamadosti/files/_log : OK
OK/var/www/html/chamadosti/config : OK
OK/var/www/html/chamadosti/files : OK
OK/var/www/html/chamadosti/files/_dumps : OK
OK/var/www/html/chamadosti/files/_sessions : OK
OK/var/www/html/chamadosti/files/_cron : OK
OK/var/www/html/chamadosti/files/_graphs : OK
OK/var/www/html/chamadosti/files/_lock : OK
OK/var/www/html/chamadosti/files/_plugins : OK
OK/var/www/html/chamadosti/files/_tmp : OK
OK/var/www/html/chamadosti/files/_cache : OK
OK/var/www/html/chamadosti/files/_rss : OK
OK/var/www/html/chamadosti/files/_uploads : OK
OK/var/www/html/chamadosti/files/_pictures : OK
Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

```

I hope someone can help me with this :)
Thanks to all the help.

**Comment by DrasticSolutions** [comment]
I also have an issue with **Home > Administration > Notification queue**
Messages stay a lot of time (hours/days) in "Notification queue" randomly and don't get sent in email.

In **Home > Setup > Automatic Actions > queuednotification**
Run Frequency: 1 minute ; Scheduled ; Run Mode: CLI
(what is the difference between CLI and GLPI ?)

In **Home > Setup > Automatic Actions > queuednotificationclean**
Run Frequency: Each Day ; Scheduled ; Run Mode: GLPI

Which of these two (**queuednotification / queuednotificationclean**) actually sends the mail ?

GLPI Server Info
```
GLPI 9.4.5 ; PHP 7.4.1 - all extensions installed ; Database 5.7.28 - Perfect!
Installation mode: TARBALL
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" upload_max_filesize="2M"
Notifications = Way of sending emails: PHP
Plugins list = Name: FusionInventory Version: 9.4+2.3    State: Enabled ; GLPI cron not running
```

And can anyone explain how **Notification queue** feature work ? or point to the right documentation.
Where can I see the logs ? How often GLPI looks in queue and after that when it sends the notification ?

**Comment by cedric-anne** [comment]
Hi,

Can you display the `Mode` column in notification list and confirm that stuck notifications are using `Email` mode ? Even if all notifications are displayed as it was emails, in can be, in fact, browser notifications of any other type handled by a plugin.

Regard

**Comment by paulovictorml** [comment]
Sorry for not sent any feedback at days... i'm searching this info now.

**Comment by paulovictorml** [comment]
Yes, it is "Email" in the mode column. Here: https://imgur.com/lMxux0o

**Comment by cedric-anne** [comment]
Hi,

Unfortunately, I have no other way of explaining this problem.

If it is possible on your installation, try to change run mode from GLPI to CLI, and see if it fixes this.

Regards

**Comment by paulovictorml** [comment]
No problem, i'm glad for your help. I've tried to change to CLI but it doesn't work too. :(

**Comment by biznlinks** [comment]
Same problem here, I have to be sending the emails manually.

**Comment by troublestarter** [comment]
Same problem here. Notification not sent every minutes.
Sent only twice a day !
Notification are GUI configured. Worked well for years !

**Comment by DavidGena** [comment]
Hello,
same problem here with GLPI 9.4.5. I didn't try with another version.

**Comment by aivorra** [comment]
I have the same problem, with glpi 9.4.6.

**Comment by CarlosSalg** [comment]
Same problem GLPI 9.5.0

**Comment by cedric-anne** [comment]
Hi,

Please consider upgrading to GLPI 9.5.5 (released yesterday).

In #8878, we changed the way crontask errors are handled. Now, when a task fails, the error should be logged correctly in `php-errors.log`, and task status should be put back to "waiting" state. If a task fails too many times (5 fails on last 10 executions), a notification will be sent (notification is configurable using `Automatic actions` itemtype and `Monitoring of automatic actions` event).

With this, you should be able to provide us an error stack trace, which can help us to investigate.

Regards

**Comment by trasher** [comment]
Should be fixed, https://github.com/glpi-project/glpi/issues/8836#issuecomment-821137384

**Comment by soportems** [comment]
Buenas tardes, continuo con el problema en envio de notificaciones en la versión 9.5.6

**Comment by soportems** [comment]
Good afternoon, I continue with the problem in sending notifications in version 9.5.6

**Comment by cedric-anne** [comment]
> Good afternoon, I continue with the problem in sending notifications in version 9.5.6

Please, open a new issue.

**Comment by loyiso89** [comment]
Same issue and I am on 10version
