### ISSUE TITLE
Very slow performance from 9.4.4 to 9.4.5 

### ISSUE THREAD

**Issue by yazmit** [glpi-project/glpi#6834]
Hello everyone 
I have encountered a very strange bug when  updating to the latest version of GLPI
a very slow response up to 3 min per request 
I would appreciate everyone help 
Thanks in advance

**Comment by paulovictorml** [comment]
Hello! Did you tried turn off the plugins and test if works?

**Comment by yazmit** [comment]
yes i tried to turn off all the plugins but doesn't seem to work

**Comment by cedric-anne** [comment]
Hi,

Can you give us, at leaste following informations ?

- Your GLPI setup (you can find it in Setup > General menu, System tab)
- Content of GLPI logs that are produced when you do your request.

**Comment by yazmit** [comment]
Hello 
1- the setup : 

[code]   GLPI 9.4.5 (/glpi => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux SNBSRV17010.CASTEL-DZ.local 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u4 (2019-07-19) x86_64 PHP 7.0.33-0+deb9u6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, sockets, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpialgerie.castel-dz.com Port 80) 	Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Server Software: Debian 9.8 	Server Version: 10.1.38-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: phpmyadmin@localhost/glpidb 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.1.38) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to files directory is protected : OK

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.3 in (/usr/share/php)

Server: ' ldap://10.208.26.5', Port: '389', BaseDN: 'DC=CASTEL-DZ,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'CN=Administrateur 		Systeme,OU=IT,OU=Utilisateurs,OU=ORN,DC=CASTEL-DZ,DC=local', Use TLS: none

Active PHP Warning: mysqli::__construct(): (HY000/2002): Connection timed out in /var/www/glpi/inc/dbmysql.class.php at line 105PHP Warning: mysqli::__construct(): (HY000/2002): Connection timed out in /var/www/glpi/inc/dbmysql.class.php at line 105SQL server: 10.208.26.112 - can't connect to the database

Way of sending emails: SMTP (anonymous@10.208.26.7)

Name: 'support@castel-dz.com' Active: Yes 	Server: '{oran.castel-dz.com:143/imap/novalidate-cert/tls}INBOX' Login: 'support' Password: Yes

activity             Name: Activités quotidiennes         Version: 2.5.0      State: Enabled 	actualtime           Name: ActualTime                     Version: 1.2.0      State: Enabled 	news                 Name: Alertes                        Version: 1.5.4      State: Enabled 	additionalalerts     Name: Alertes supplémentaires        Version: 2.2.0      State: Enabled 	bettermailimporter   Name: Better Mail Importer           Version: 1.0.1      State: Enabled 	timelineticket       Name: Chronologie des tickets        Version: 9.4+1.0    State: Enabled 	uninstall            Name: Cycle de vie des matériels (un Version: 2.6.2      State: Enabled 	consumables          Name: Demande de consommables        Version: 1.5.0      State: Enabled 	useditemsexport      Name: Export des éléments utilisés   Version: 2.3.0      State: Enabled 	financialreports     Name: Financial reports              Version: 2.6.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+1.1    State: Enabled 	gappessentials       Name: Gapp Essentials                Version: 1.1.0      State: Enabled 	mod                  Name: GLPI Modifications             Version: 1.5.2      State: Enabled 	pdf                  Name: Impression pdf                 Version: 1.6.0      State: Enabled 	datainjection        Name: Injection de fichiers          Version: 2.7.0      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.1      State: Enabled 	mask                 Name: Mask                           Version: 2.3.0      State: Enabled 	metademands          Name: Meta-Demandes                  Version: 2.6.1      State: Enabled 	moreticket           Name: More ticket                    Version: 1.5.1      State: Enabled 	notifications        Name: Notifications                  Version: 9.4+1.0    State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled 	reports              Name: Rapports                       Version: 1.13.1     State: Enabled 	reservation          Name: Reservation                    Version: 2.2.0      State: Enabled 	dashboard            Name: Tableau de bord                Version: 0.9.8      State: Enabled 	taskdrop             Name: TaskDrop                       Version: 1.1.0      State: Enabled

Host: localhostConnection: OkUse the OCSNG software dictionary: No
[/code]

2- The logs 
[event.log](https://github.com/glpi-project/glpi/files/4113250/event.log)
[migration_to_9.4.5.log](https://github.com/glpi-project/glpi/files/4113251/migration_to_9.4.5.log)
[sql-errors.log](https://github.com/glpi-project/glpi/files/4113252/sql-errors.log)
[warning_during_migration_to_9.4.0.log](https://github.com/glpi-project/glpi/files/4113253/warning_during_migration_to_9.4.0.log)

**Comment by cedric-anne** [comment]
Hi,

You have some `MySQL server has gone away` errors in your logs. You should take a look at your database configuration. As this does not seems to be a GLPI bug, I close the issue.

As this does not seems to be a bug, I close this issue. Feel free to ask for community support on [forums](https://forum.glpi-project.org/) or for professionnal support via the [GLPI Network](https://glpi-project.org/glpi-network/).

Regards
