### ISSUE TITLE
Half Days on Calender

### ISSUE THREAD

**Issue by zinhleShabangu** [glpi-project/glpi#6835]
Good Day 

may i please suggest the addition of half day as part of the closing days. 

in GLPI the close times can be linked to the calender such that these are excluded in the overall reporting of a ticket life time. 

suggestion: Add a time **start** and **end** of all close times. this will enable the addition of a halfday where the closing time is between 12:00 pm to say 5:00 pm. please this would assist a lot. in my work we have half days every month. the SLA's keep going even though work hours are off the rest of the day.

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
