### ISSUE TITLE
Add a configuration item to prevent solving of tickets/problems/changes if some tasks are 'to do'

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#684]
Hello,

I propose to add a configuration in config.form.php (Assistance tab) that will prevent (or not) the solving of tickets/problems/changes when some tasks are in status 'to do'.

I propose also to add a new hook ('can_solve_item') that will be called to ask if plugins agree to solve the ticket/problem/change, and to give back an alert message that will be shown when the solution tab is viewed. This hook may be called even if configuration is not set.

regards,
Tomolimo

PS: I'll do the PR, as I have some experience about this (used already in my company for ticket solution tabs).

**Comment by yllen** [comment]
Or for your first purpose.

I don't understand why you need a hook. You have in the core the function CanSolve() that you can call from your plugin. It's not the plugin agree to solve but rights in GLPI.

**Comment by tomolimo** [comment]
Use case of the second proposal:
We have a certain process that runs with ProcessMaker plugin. this process is for Change Management, and this process has for last step what is called Process Implementation Review (PIR). This PIR must be done after the ticket survey answer so that it will take into account the feedback of the user. So after survey means after close which means after solve. So to sum-up this use-case: the ticket must be solved, even if a task is still in to-do: the PIR task will be done after ticket closing.
That's why I need to have this hook ('can_solve_item') which is a request from the core to plugins to get authorization to solve ticket. Or may be the name is not the right one, may be we should call it 'may_solve_item')
And if all plugins answer yes then solve it (regardless of the configuration), and if one at least answer no then don't solve it.
regards,
Tomolimo

**Comment by orthagh** [comment]
Behaviors plugin do that to check emptiness of solution when a user try to solve ticket.
See : 
* https://forge.glpi-project.org/projects/behaviors/repository/entry/trunk/setup.php#L74
* https://forge.glpi-project.org/projects/behaviors/repository/entry/trunk/inc/ticket.class.php#L224

But in fact, the check and message is done **after** solution submission, so user's data is cleared (and the users complains about that).

So i think it could be a great enhancement to glpi and plugins

**Comment by tomolimo** [comment]
In fact this is not the same at all.
Behaviors (we are using this feature) will prevent the solve of a ticket if solution is empty.
My purpose is to prevent the solve if a task is still in 'todo' status. 
It can be implemented like Behaviors does for empty solution (i.e. on the server after the POST) but it can also be implemented by preventing the 'Solution' tab to be viewed (replaced by a panel that will alert about non-done tasks).

**Comment by orthagh** [comment]
Yes, i agreed in fact, maybe it was not very clear :)

**Comment by wawax** [comment]
The hook seems very interesting !

**Comment by maeichris** [comment]
This request was also posted on the GLPI UserEcho suggestion website by @tomolimo on 2016-02-22.  Assuming that site is in active use by the developers, it probably doesn't need to be in github as a bug/issue.

https://glpi.userecho.com/en/communities/1/topics/231-prevent-solve-of-ticket-change-problem-when-to-do-tasks-are-existing
