### ISSUE TITLE
No blueprint picture on server room (racks) when blank space in file name

### ISSUE THREAD

**Issue by vincentdeniau** [glpi-project/glpi#6847]
**Bug description**

Background (blueprint) picture does not appear if there is a blank space in file name.

**Page(s) URL**

/front/dcroom.form.php , _Rack_ tab

**How to reproduce**

1. Go to Home > Management > Data centers > Server rooms
2. Select any existing room
3. On the main tab (Server room), add a Background picture (blueprint) whith blank space in name (e.g. "My Picture.png")
4. Save
5. Got to Rack tab
6. Ensure the blueprint toggle is ON
7. See no background image

**Expected behavior**

The uploaded picture should appear behind the grid.

**Comment by cedric-anne** [comment]
Hi,

Can you give us more details about your installation ? For instance version of GLPI, list of plugins, content of logs, ...

Regards

**Comment by cedric-anne** [comment]
I confirmed the bug on 9.4/bugfixes branch. This part has been refactored and is now fixed in 9.5/bugfixes branch.
As this bug is minor, and as fix is part of a code refactor, it will not be backported to 9.4 branch.

Regards

Regards

**Comment by cedric-anne** [comment]
Fixed by #6125
