### ISSUE TITLE
New hooks to permit plugins to add some dedicated behaviors when objects are shown

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#685]
Hello,

I propose to add two hooks (pre_show_item and post_show_item) to permit plugins to change a little bit the way objects are shown.

Use case exemples:  A plugin can add tasks into a ticket and want to prevent users to edit these. A plugin wants to localize task contents.

regards,
Tomolimo

PS: I'll do the PR, as I have some experience about this (used already in my company for ticket task tab).

**Comment by orthagh** [comment]
As i said in our phone meeting, i approve future PR for this need.

I prefer adding these new hooks instead viewing plugins developers doing monkey patching (runkit) or altering views with javascript. In final, theses plugins will modify the views, so let them do it easilly.

**Comment by orthagh** [comment]
#777 merged
