### ISSUE TITLE
Duplicated tickets

### ISSUE THREAD

**Issue by nathanpinotti** [glpi-project/glpi#6852]
Hello
I'm getting duplicated ticket in GLPI 9.3.2. The mailgate is working like a charm but when it gets a new ticket right after a few minutes a new ticket is created with the same description from the same user but with a diff ID.

I've already checked all the configs. I'm using the following;
cron * * * * * /usr/bin/php7.0 /var/www/glpi/front/cron.php >/dev/null 2>&1

Any chance to get the issue from a log file?
Should I also consider a mail issue?

**Comment by nathanpinotti** [comment]
Hello
I'm getting duplicated ticket in GLPI 9.3.2. The mailgate is working like a charm but when it gets a new ticket right after a few minutes a new ticket is created with the same description from the same user but with a diff ID.

I've already checked all the configs. I'm using the following;
cron * * * * * /usr/bin/php7.0 /var/www/glpi/front/cron.php >/dev/null 2>&1

Any chance to get the issue from a log file?
Should I also consider a mail issue?

**Comment by trasher** [comment]
9.3 version is no longer supported, please try with last release, and feel free to reopen if problem stil happen.
