### ISSUE TITLE
planning.php / cross origin ressource sharing

### ISSUE THREAD

**Issue by manugre** [glpi-project/glpi#6855]
the direct access to planning.php for getting an ics cal could have a problem of cross origin ressource sharing

I had to add headers, copy/past form apirest.php :
.. By the way I do not mastering this. It works, I do not know why

In front/planning.php, line 33
/**
    * Set headers according to cross origin ressource sharing
    *
    * @param string $verb Http verb (GET, POST, PUT, DELETE, OPTIONS)
    *
    * @return void
    */

      if (isset($_SERVER['HTTP_ORIGIN'])) {
         header("Access-Control-Allow-Origin: *");
      }

      if ($_SERVER['REQUEST_METHOD'] == 'GET' || $_SERVER['REQUEST_METHOD'] == 'OPTIONS') {
         header("Access-Control-Expose-Headers: content-type, content-range, accept-range");
      }

      if ($_SERVER['REQUEST_METHOD'] == "OPTIONS") {
         if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_METHOD'])) {
            header("Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS");
         }
         if (isset($_SERVER['HTTP_ACCESS_CONTROL_REQUEST_HEADERS'])) {
            header("Access-Control-Allow-Headers: ".
                   "origin, content-type, accept, session-token, authorization");
         }
         exit(0);
      }

--- 
GLPI version 9.4.5

**Comment by cedric-anne** [comment]
Hi,

When you talk about `direct access to planning.php`, from which software are you doing this access ?

CORS are made to prevent unallowed requests from a domain to another, so unless you make a request from inside a web application, I do not understand how you can get such an error.

Regards

**Comment by manugre** [comment]
I’m doing a frontend in js 
Planning.php is called via fetch ()

The idea is to publish a calendar on a public screen in the office

**Comment by cedric-anne** [comment]
Ok, so this problem is related to your specific usage. You should read documentation about CORS and adapt your Apache configuration to your needs.

Regards
