### ISSUE TITLE
Periodically import new users from Active Directory

### ISSUE THREAD

**Issue by hahahafr** [glpi-project/glpi#686]
Hello,
I have this problem :

I need to import new Active Directory users, since the last import.

Currently I have this filter :
(& (objectClass=user)(objectCategory=person)(lastLogonTimestamp>=130986000000000000)(mail>=0))

How can I do this ?

**Comment by orthagh** [comment]
Hello @hahahafr 

To achieve an auto update and auto import of your ldap users, you can user the file script ldap_mass_import.php which is available in scripts directory of your glpi

Define an entry in crontab for this, daily for example is the best way

**Comment by hahahafr** [comment]
Should I look into the ldap_mass_import.php file and try to uderstand how it works by myself ?

**Comment by orthagh** [comment]
launch it in cli, ex :
```
php scripts/ldap_mass_import.php 
```
You'll find some inline documentation, it's pretty straightforward.

**Comment by hahahafr** [comment]
Ok so will it sync existing users, delete existing users? Or just add new
users? How about my filter?

**Comment by tomolimo** [comment]
Hello,


Yes, it will sync existing users as soon as their logon information are LDAP and login matches.
And for deleting it's up to you to decide, it's in the parameters of the LDAP settings.
About filter: you need to specify it on the command line, here is ours:

> php -f scripts/ldap_mass_sync.php action=2 ldap_filter="(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(!(samaccountname=*$)))"

This will filter out account like 'something$' and 'de-activated users'.

Don't forget to configure Authentication in 'Setup > Authentication > setup'

![image](https://cloud.githubusercontent.com/assets/7569958/15642006/c8eaccc8-2644-11e6-984b-c8cbb7738bf8.png)

And to create a LDAP entry in the 'Setup > Authentication > LDAP Directories' in GLPi (I advise you to use the same filter in the LDAP definition than with the CLI).

![image](https://cloud.githubusercontent.com/assets/7569958/15642029/ea886bb0-2644-11e6-8c05-4e08dcbbe756.png)


Regards,
Tomolimo

**Comment by hahahafr** [comment]
Hello, just to give some updates I used the ldap_mass_sync.php script with option to update everything (action=2 I think) and everything is fine for now.

**Comment by orthagh** [comment]
Great !
