### ISSUE TITLE
Rich text editor show at ticket description and solution but not at follow and tasks

### ISSUE THREAD

**Issue by ftoledo** [glpi-project/glpi#6860]
I try to determine the issue that make disabled the tinymce editor only at follows and tasks.
But i can see it on ticket description and solution, i dont found any javascript related errors. I check file permissions. 
I'm running 9.4.4 and Firefox 72
Any help for research will apreciated!
Thanks!

Ticket description (OK):

![imagen](https://user-images.githubusercontent.com/95441/73289127-e93d3500-41da-11ea-9ee9-266f6062d612.png)

Add solution (OK)

![imagen](https://user-images.githubusercontent.com/95441/73289152-f5c18d80-41da-11ea-9baf-92483b59fefb.png)

Add follow(FAIL)

![imagen](https://user-images.githubusercontent.com/95441/73289173-ff4af580-41da-11ea-9510-cd1a34a8b4a3.png)

Add task (FAIL)

![imagen](https://user-images.githubusercontent.com/95441/73289196-096cf400-41db-11ea-9dca-2dc80899f85d.png)

**Comment by cedric-anne** [comment]
Hi,

I am not able to reproduce on current state of 9.4/bugfixes branch.

Can you try with all plugins disabled ?
Can you tell us which layout (horizontal split, vertical split, tabs on left) you use ?

Regards
