### ISSUE TITLE
Images inserted as bad tracking

### ISSUE THREAD

**Issue by geanferrani123** [glpi-project/glpi#6864]
** Describe the bug **

A clear and concise description of what the error is.

** Page URL (s) **

If applicable, URL of the page (s) where the error occurs.

**Reproduce**

1. Go to ticket opening
2. enter the problem description
3. attach a problem attachment (image)
4. Add the accompaniment
5. When checking the follow-up email and clicking on the attachment, the image quality is terrible and the size is small, when the same image is opened inside the GLPI, the quality and size are normal.

**Expected behavior**

The behavior that should have occurred is that the image had to be of the same quality and size that you can see inside the GLPI. It is nothing related to email, firewall and etc. (this has already been verified).

**Historic**

`` ''
paste logs here
Find them in the * -error.log files in glpi / files / _log /
`` ''

** Your GLPI configuration (you can find it in Configuration> General menu, System tab) **

Installation and configuration instructions
[code]
 
GLPI 9.4.4 (=> / glpi / css)
Installation mode: TARBALL

Server
 
Operating system: Linux S3A71024P1 4.9.0-6-amd64 # 1 SMP Debian 4.9.88-1 + deb9u1 (2018-05-07) x86_64
PHP 7.0.27-0 + deb9u1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, calendar, cgi-fcgi, ctype,
curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd,
openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml,
xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time = "30" memory_limit = "128M" post_max_size = "15M" safe_mode = "" session.save_handler = "files"
upload_max_filesize = "15M"
Software: nginx / 1.10.3
Mozilla / 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 79.0.3945.130 Safari / 537.36
Server Software: Debian 9.6
Server Version: 10.1.37-MariaDB-0 + deb9u1
Server SQL Mode:
Parameters: sueq @ localhost / GLPI
Host info: Localhost via UNIX socket

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (10.1.37) - Perfect! Database version seems correct (10.1.37) - Perfect!
OK / glpi / css / files / _log: OK
OK / glpi / css / config: OK
OK / glpi / css / files: OK
OK / glpi / css / files / _dumps: OK
OK / glpi / css / files / _sessions: OK
OK / glpi / css / files / _cron: OK
OK / glpi / css / files / _graphs: OK
OK / glpi / css / files / _lock: OK
OK / glpi / css / files / _plugins: OK
OK / glpi / css / files / _tmp: OK
OK / glpi / css / files / _cache: OK
OK / glpi / css / files / _rss: OK
OK / glpi / css / files / _uploads: OK
OK / glpi / css / files / _pictures: OK
Web access to files directory is protectedWeb access to files directory is protected: OK

Libraries
 
htmLawed version 1.2.4 in (/ glpi / css / lib / htmlawed)
phpmailer / phpmailer version 6.0.7 in (/ glpi / css / vendor / phpmailer / phpmailer / src)
simplepie / simplepie version 1.5.2 in (/ glpi / css / vendor / simplepie / simplepie / library)
tecnickcom / tcpdf version 6.2.26 in (/ glpi / css / vendor / tecnickcom / tcpdf)
michelf / php-markdown in (/ glpi / css / vendor / michelf / php-markdown / Michelf)
true / punycode in (/ glpi / css / vendor / true / punycode / src)
iamcal / lib_autolink in (/ glpi / css / vendor / iamcal / lib_autolink)
saber / vobject in (/ glpi / css / vendor / saber / vobject / lib)
zendframework / zend-cache in (/ glpi / css / vendor / zendframework / zend-cache / src)
zendframework / zend-i18n in (/ glpi / css / vendor / zendframework / zend-i18n / src)
zendframework / zend-serializer in (/ glpi / css / vendor / zendframework / zend-serializer / src)
monolog / monolog in (/ glpi / css / vendor / monolog / monolog / src / Monolog)
sebastian / diff in (/ glpi / css / vendor / sebastian / diff / src)
elvanto / litemoji in (/ glpi / css / vendor / elvanto / litemoji / src)
symfony / console in (/ glpi / css / vendor / symfony / console)
leafo / scssphp in (/ glpi / css / vendor / leafo / scssphp / src)
phpCas version 1.3.3 in (/ usr / share / php)

LDAP directories
 
Server: 'net.sefaz.es.gov.br', Port: '389', BaseDN: 'DC = NET, DC = MEUDOMI, DC = COM, DC = BR', Connection filter:
'(& (objectCategory = person) (objectClass = user) (! (userAccountControl: 1.2.840.113556.1.4.803: = 2)) (memberOf = CN = MEUDOMI-1, OU = Groups, OU = EMAIL, OR = GRUPOS_RECURSOS, DC = NET, DC = MEUDOMINIO, DC = COM, DC = BR)) ',
RootDN: 'MEUDOM \ userservice', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@192.168.255.131)

Mails receivers
 
Name: 'calls@mydomain.com' Active: Yes
Server: '{172.17.11.33:993/imap/ssl/novalidate-cert}' Login: 'myname \ called' Password: Yes

Plugins list
 
webapplications Name: Applications w

**Comment by cedric-anne** [comment]
Duplicates #6739.
