### ISSUE TITLE
GLPI ticket side tabs moved to bottom

### ISSUE THREAD

**Issue by JMCGES** [glpi-project/glpi#6866]
**Description**

When I'm updating a ticket the side tabs to create followups went to the bottom side of the ticket form.

**To reproduce**

1. Go to any ticket
2. Check side bars are not on the left side.
3. Scroll down to the end of the page.

**Screenshots**

<img width="1548" alt="Captura de pantalla 2020-01-30 a las 8 07 56" src="https://user-images.githubusercontent.com/60461936/73428271-fec87100-4338-11ea-8f3f-533026c5f686.png">
<img width="1156" alt="Captura de pantalla 2020-01-30 a las 8 08 06" src="https://user-images.githubusercontent.com/60461936/73428280-0556e880-4339-11ea-878b-8e10562035bd.png">

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by JMCGES** [comment]
> Informations requested in ticket template has not been provided.

Because it's only to show the error, the bug keeps failing even when information is complete.

**Comment by trasher** [comment]
Github ticket template. https://github.com/glpi-project/glpi/issues/new?template=bug_report.md

**Comment by JMCGES** [comment]
> Github ticket template. https://github.com/glpi-project/glpi/issues/new?template=bug_report.md

You mean GLPI Setup? Here You have it

[code]   GLPI 9.4.5 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux ip-172-31-18-218 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 PHP 7.0.33-0ubuntu0.16.04.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, 	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at soporte.eritea.es Port 8080) 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.28-0ubuntu0.16.04.2 	Server SQL Mode:  	Parameters: GLPI@localhost/GLPI 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed APCu extension is not present CAS extension is not present Database version seems correct (5.7.28) - Perfect! /var/www/html/glpi/files/_log : OK /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)

Not active

Way of sending emails: SMTP+TLS (soporte@eritea.es@smtp.gmail.com)

Name: 'soporte@eritea.es' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl/novalidate-cert}' Login: 'soporte@eritea.es' Password: Yes

dashboard            Name: Tablero de informes            Version: 0.9.8      State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

Can you tell us which layout is configured in your preferences (`/front/preference.php` page) ?
![image](https://user-images.githubusercontent.com/33253653/73545570-daa18880-443b-11ea-9ab2-aa57b1b223ad.png)

Can you also make a try with all plusings disabled ?

Regards

**Comment by JMCGES** [comment]
> Hi,
> 
> Can you tell us which layout is configured in your preferences (`/front/preference.php` page) ?
> ![image](https://user-images.githubusercontent.com/33253653/73545570-daa18880-443b-11ea-9ab2-aa57b1b223ad.png)
> 
> Can you also make a try with all plusings disabled ?
> 
> Regards

Okay... didn't see this option... Thank you so much!
