### ISSUE TITLE
Update GLPI 9.3.0 to 9.4.5 failed with PHP GLPI class error

### ISSUE THREAD

**Issue by itpro-tips** [glpi-project/glpi#6868]
Hi,

During the uptade process from GLPI 9.3.0 to 9.4.5, I used [this documentation](https://glpi-project.org/DOC/FR/glpi/admin_upgrade.html).

After replace files in _/var/www/html/glpi_, when I go to _https://glpiURL_ I reach the authentication page instead of the update wizard.

If I go to https://glpiURL/install/install.php, I get blank page.

My HTTPD log tells me:
```
# tailf /var/log/httpd/ssl_error_log
PHP Fatal error:  Class 'GLPI' not found in /var/www/html/glpi/install/install.php on line 38
```

**Comment by cedric-anne** [comment]
Hi,

You may have done something wrong in the update process. As you are the first one to give us such a feedback, and as this part of code has not been change for a logn time, I doubt you are facing a GLPI bug.

Try to retry update process from the beginning, and, if problem persist, ask for community support on [forums](https://forum.glpi-project.org/).

Regards
