### ISSUE TITLE
Calendar of SLA not used for delay

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#687]
http://forum.glpi-project.org/viewtopic.php?id=154067

**Comment by yllen** [comment]
Correction approve on the forum

**Comment by sioua** [comment]
Bonjour .
Merci pour cette correction vraiment superbe. 
Les modifications marchent nikel. Sauf que si le ticket est créé en dehors des heures du calendrier, le délai de résolution ne se calcule pas. Le système met le solve_delay_stat à 0. Peut-on forcer le calcul du délai de résolution à prendre en compte les tickets créés en dehors des heures du calendrier?
Merci d'avance

**Comment by oacapo** [comment]
good evening everyone
I created a new SLA calendar except that in our country, we work from Monday to Friday from 8 am to 6.30 pm. How then to add them in the closed periods so that the resolution time is not real?
