### ISSUE TITLE
Users images are not catched

### ISSUE THREAD

**Issue by emaw705** [glpi-project/glpi#6876]
Hi.

I'm using GLPI 9.4.3 in production. In this version, user image is not load on cache, so always it is loaded from server, like I show in the next image: 

![image](https://user-images.githubusercontent.com/48997363/73547944-b7b4ab80-441e-11ea-9df2-a1ebbf94affd.png)

![image](https://user-images.githubusercontent.com/48997363/73547963-c4390400-441e-11ea-923d-48276ebf7baa.png)

Because of that, the time that GLPI use to load a web page is high.

For test, I have an development environment with GLPI 9.4.5. In this, I delete from DB the picture path in glpi_users table. After that, the time for load the same page show in the above image is lower.

My configuration in production is:

Operating system: Linux XXXXX082 4.9.0-9-amd64 # 1 SMP Debian 4.9.168-1 (2019-04-12) x86_64
PHP 7.3.9-1+020190902.44+debian91.gbpf8534c apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache,
apache2handler, apc, apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlsrv, posix, readline, session, shmop, sockets, sodium,
sqlsrv, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
upload_max_filesize="2M"
Software: Unknown (Unknown Server at )
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36
Server Software: MySQL Community Server (GPL)
Server Version: 5.7.27
Server SQL Mode:
Parameters: XXXXXXXXXXX@XXXXXXXX
Host info: Localhost via UNIX socket

mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
exif extension is installed
CAS extension is not present
Database version seems correct (5.7.27) - Perfect!Database version seems correct (5.7.27) - Perfect!
OK/var/www/html/glpi/files/_log : OK
OK/var/www/html/glpi/config : OK
OK/var/www/html/glpi/files : OK
OK/var/www/html/glpi/files/_dumps : OK
OK/var/www/html/glpi/files/_sessions : OK
OK/var/www/html/glpi/files/_cron : OK
OK/var/www/html/glpi/files/_graphs : OK
OK/var/www/html/glpi/files/_lock : OK
OK/var/www/html/glpi/files/_plugins : OK
OK/var/www/html/glpi/files/_tmp : OK
OK/var/www/html/glpi/files/_cache : OK
OK/var/www/html/glpi/files/_rss : OK
OK/var/www/html/glpi/files/_uploads : OK
OK/var/www/html/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

There is anything wrong? 

I need to improve the performance of GLPI.

Best regards!

**Comment by cedric-anne** [comment]
Hi,

This enhancement is already done and will be available on 9.5 version of GLPI. See #6126.

Regards

**Comment by emaw705** [comment]
Hi Cedric.

Is there an estimated release date for GLPI 9.5?

Thanks.

Regards

**Comment by orthagh** [comment]
some weeks (a beta will come mid february)
