### ISSUE TITLE
Tabs in Administration -> profile_name -> profiles errors

### ISSUE THREAD

**Issue by scylla999** [glpi-project/glpi#6877]
Hello folks,
I'm having issues with the Administration, profile_name, profiles.   Most of the tabs, when selected give errors:

![glpi-bug-admin-profiles](https://user-images.githubusercontent.com/24919069/73553518-17f41f00-4418-11ea-985a-50cec0566490.jpg)

Here's my setup (CentOS, v7.7):

Information about system installation & configuration
--
[code]   GLPI 9.4.5 (/glpi => /home/www/secure_html/glpi) Installation mode: TARBALL

Operating system: Linux  3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 PHP 7.1.33 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, 	mysqli, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, 	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.33 mod_perl/2.0.11 Perl/v5.16.3 () 	Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0 Server Software: MariaDB Server 	Server Version: 10.4.12-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.4.12) - Perfect! /home/www/secure_html/glpi/files/_log : OK /home/www/secure_html/glpi/config : OK /home/www/secure_html/glpi/files : OK /home/www/secure_html/glpi/files/_dumps : OK /home/www/secure_html/glpi/files/_sessions : OK /home/www/secure_html/glpi/files/_cron : OK /home/www/secure_html/glpi/files/_graphs : OK /home/www/secure_html/glpi/files/_lock : OK /home/www/secure_html/glpi/files/_plugins : OK /home/www/secure_html/glpi/files/_tmp : OK /home/www/secure_html/glpi/files/_cache : OK /home/www/secure_html/glpi/files/_rss : OK /home/www/secure_html/glpi/files/_uploads : OK /home/www/secure_html/glpi/files/_pictures : OK Web access to files directory is protected : OK SELinux mode is Disabled

htmLawed version 1.2.4 in (/home/www/secure_html/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/home/www/secure_html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/home/www/secure_html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/home/www/secure_html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/home/www/secure_html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/home/www/secure_html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/home/www/secure_html/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/home/www/secure_html/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/home/www/secure_html/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/home/www/secure_html/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/home/www/secure_html/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/home/www/secure_html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/home/www/secure_html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/home/www/secure_html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/home/www/secure_html/glpi/vendor/symfony/console) leafo/scssphp in (/home/www/secure_html/glpi/vendor/leafo/scssphp/src)

**Comment by cedric-anne** [comment]
Hi,

Can you find something in GLPI logs related to these errors ?
Can you try with all plugins disabled ?

Regards

**Comment by scylla999** [comment]
I'm not using any plugins.

Here are php errors that I'm getting:
[2020-01-31 10:38:26] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /home/www/secure_html/glpi/inc/toolbox.class.php line 658
  *** PHP Notice(8): Undefined index: translate_kb
  Backtrace :
  inc/config.class.php:345                           
  inc/config.class.php:2158                          Config->showFormDisplay()
  inc/commonglpi.class.php:485                       Config::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"8@intranet.gi.polymtl.ca","mem_usage":"0.000\", 1.97Mio)"} 
[2020-01-31 10:38:28] glpiphplog.WARNING: Test logger  
[2020-01-31 10:51:00] glpiphplog.WARNING: Test logger  
[2020-01-31 10:51:39] glpiphplog.WARNING: Test logger  
[2020-01-31 10:55:40] glpiphplog.WARNING: Test logger

**Comment by scylla999** [comment]
And in my system logs:
Jan 31 11:12:58 intranet mysqld: 2020-01-31 11:12:58 1270 [Warning] Aborted connection 1270 to db: 'glpi' user: 'glpi' host: 'localhost' (Got an error reading communication packets)

**Comment by scylla999** [comment]
Could it be a bug in my PHP stack?

*** Error in `/usr/sbin/httpd': free(): invalid pointer: 0x00007fb5836f96e0 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81679)[0x7fb5a1993679]
/etc/httpd/modules/libphp7.so(zend_array_destroy+0xc1)[0x7fb5919b7e81]
/etc/httpd/modules/libphp7.so(+0x32e133)[0x7fb591a41133]
/etc/httpd/modules/libphp7.so(execute_ex+0x2b)[0x7fb5919ee86b]
/etc/httpd/modules/libphp7.so(zend_execute+0x194)[0x7fb591a42654]
/etc/httpd/modules/libphp7.so(zend_execute_scripts+0xc3)[0x7fb5919a6923]
/etc/httpd/modules/libphp7.so(php_execute_script+0x2d8)[0x7fb591943b08]
/etc/httpd/modules/libphp7.so(+0x331677)[0x7fb591a44677]
/usr/sbin/httpd(ap_run_handler+0x40)[0x55eb9ee35af0]
/usr/sbin/httpd(ap_invoke_handler+0x69)[0x55eb9ee36039]
/usr/sbin/httpd(ap_process_async_request+0x1ea)[0x55eb9ee4ac4a]
/usr/sbin/httpd(ap_process_request+0x22)[0x55eb9ee4af32]
/usr/sbin/httpd(+0x530c2)[0x55eb9ee470c2]
/usr/sbin/httpd(ap_run_process_connection+0x40)[0x55eb9ee3f120]
/etc/httpd/modules/mod_mpm_prefork.so(+0x37af)[0x7fb5990577af]
/etc/httpd/modules/mod_mpm_prefork.so(+0x39f5)[0x7fb5990579f5]
/etc/httpd/modules/mod_mpm_prefork.so(+0x468e)[0x7fb59905868e]
/usr/sbin/httpd(ap_run_mpm+0x4e)[0x55eb9ee1a0ce]
/usr/sbin/httpd(main+0xa96)[0x55eb9ee12e26]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7fb5a1934505]
/usr/sbin/httpd(+0x1ef5f)[0x55eb9ee12f5f]

**Comment by trasher** [comment]
The invalid pointer issues is a PHP issue on your side; yes. You should try to see if any updates are available; or switch to php-fpm as example. Or investigate on your operating system's support side.

This kind of issue will potentially affect all PHP apps on the system.

I close this one since this is not a GLPI issue, feel free to reopen once your PHP has been fixed and if you still see the initial issue.

**Comment by scylla999** [comment]
I installed php73 from the remi CentOS repository and it solved my problem.
