### ISSUE TITLE
Personalized personal and group view page

### ISSUE THREAD

**Issue by ALESS330** [glpi-project/glpi#6878]
Hello!

To facilitate the organization and better visualization of the calls attributed to the technician and the group, I suggest that it is possible to personalize the cards contained in the "Personal view" and "Group view" tabs, on the home page. 

Today they only show "Calls to be processed" and "Calls with status pending", but it might be possible to view calls by _category_ or by _responsible technician_. 

Thanks.

**Comment by trasher** [comment]
There is a dev in progress: https://github.com/glpi-project/glpi/pull/6459. If that does not cover your needs, please use [suggestion website](http://suggest.glpi-project.org) for RFE.
