### ISSUE TITLE
Notifications not working for one entity

### ISSUE THREAD

**Issue by jlms77** [glpi-project/glpi#6879]
Hi,

Im new to GLPI, a have one entity working OK, the tickets are being assigned from one receiver to automatically be assigned to the right entity and a watcher group is being assigned automatically, the web and email notifications are working properly.

The issue i have found is that i have created another identity using exactly the same method than the other one but the notifications and the getmail automatic action are not working for this one, both identities are below the main one.

This are my steps:

1.- Created the new entity, all parameters are exactly the same as the other identity, except the administrator email and reply to email (Notifications are enabled)
2.- Created the the Receiver, when i manually execute the action the emails are being received and the tickets are being created on the right entity and the observer group is being assigned  just like the first identity

I can't find where to activate this actions for the second identity, i will really appreciate if someone can point me in the right direction.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
