### ISSUE TITLE
GLPI randomly not accessible after submitting a task, adding technicial, changing description

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#688]
Hello

GLPI randomly not accessible after submitting a task, adding technicial, changing description

Drop down lists randomly empty with the error message "Connection failed"

Tabs randomly empty (screenshot 2, browser needs to be closed to solve the issue)

![Uploading image.png…]()

**Comment by orthagh** [comment]
Hello @satyan01 

You're certainly a regular user of this bug tracker but i can't remember your server specification, your environnement and your glpi version, if you have sso, and any parts who can interfer, etc
Please detail theses.

Also, you screenshot attached to your issue failed to upload.

**Comment by satyan01** [comment]
windows 2012R2 - IIS 8.5 - php 7.04 - mariadb 10

**Comment by orthagh** [comment]
> if you have sso ?

**Comment by satyan01** [comment]
yes

**Comment by tomolimo** [comment]
Hello,
I know this: it's coming from this line:
`define("GLPI_USE_CSRF_CHECK", "1");`
in config/define.php
change it to 
`define("GLPI_USE_CSRF_CHECK", "0");`
regards,
Tomolimo

**Comment by satyan01** [comment]
I have done it and tell you if the case is fixed

**Comment by satyan01** [comment]
Which case is it solved with this fix ?

1 - GLPI randomly not accessible after submitting a task, adding technicial, changing description


2 - Drop down lists randomly empty with the error message "Connection failed"

3 - Tabs randomly empty (screenshot 2, browser needs to be closed to solve the issue)

**Comment by tomolimo** [comment]
All :smile:

**Comment by satyan01** [comment]
perfect !!!

**Comment by orthagh** [comment]
@tomolimo, it's a right fix for end users, but i think, it's not a good technical solution.
CSRF is a security to prevent form injection, disabling it can be perilous (interne public access for example) 

Do you have not other solution to avoid theses errors with this kind environnement ? 
(it's a naive question, i don't follow all historical who achieve to this solution)

**Comment by tomolimo** [comment]
I agree @orthagh but I don't have any other solution for the moment. 
And anyway using GLPi on intranet only, I am not sure it's really useful.

**Comment by satyan01** [comment]
Hello

the issue is still present...

**Comment by satyan01** [comment]
![image](https://cloud.githubusercontent.com/assets/15144026/15929071/f55ba4ae-2e4a-11e6-8a27-6335ae8dbb61.png)

**Comment by tomolimo** [comment]
Still using 0.91? and not 9.1?

**Comment by satyan01** [comment]
0.91

**Comment by tomolimo** [comment]
Yes, you are not using the latest version which is not 0.91 but 9.1,
so please:

1. update to 9.1
1. re-test your problem

thank you

**Comment by satyan01** [comment]
how to update to 9.1 ?

**Comment by tomolimo** [comment]
how did you get to 0.91?

**Comment by satyan01** [comment]
download master on april

**Comment by tomolimo** [comment]
strange as the version change has been done on the 4th of April...
see https://github.com/glpi-project/glpi/commit/2ffeda3e0a2a236aadcbd7fcc39578bd06e1e003#diff-0bc8258030f7da8727f0453dbd3e9b30R30

**Comment by orthagh** [comment]
Is this issue still valid @satyan01 ?

**Comment by satyan01** [comment]
No it looks better with 9.1 last release
