### ISSUE TITLE
[0.90.3] Problem to rights of users

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#689]
Users cann't associate the computers when create a ticket.
Given the right:
Computers -> Read
Tickets -> See my ticket, Create, See group ticket, See all tickets,    See assigned
Association -> all

Add the ability to association the computer with the ticket when creating the ticket.

**Comment by orthagh** [comment]
Hello @AircraftRu 

You can actually associate item on ticket creation (if you right to do it)

![image](https://cloud.githubusercontent.com/assets/418844/15609778/4630380a-2422-11e6-9175-5a5233effa09.png)


If you can't see this part, check : 
* profile of the user(s)
* ticket template
* plugins ?

**Comment by AircraftRu** [comment]
I can to add associate item if I have the right to update the ticket but these rights I don't want to give users

**Comment by orthagh** [comment]
The issue you described initially was to associate items (assets) when your (self-service ?) users creating tickets.
You **can** do that, here is a list of points who are necessary to provide this feature to your users : 
- the fields 'hardware type' in (default) template is not hidden
- the profile of your user permit to associate theirs asset (or all assets)
- your users have assets associated with them (for view their assets, no need for all assets)

To precise, self-service users can add assets when creating a ticket, but can add asset when editing an existing ticket (anyway the 'update ticket' right doesn't exist for this kind of profile)

For technician users (standard interface), they can't associate assets to existing ticket without the right to update the ticket.

Let me know if you have trouble with this

**Comment by AircraftRu** [comment]
We have a secretary creates tickets for all, to give rights to update the tickets we don't want, but we want to give rights to associate assets in the whole office

**Comment by yllen** [comment]
Associate assets for all need right update all tickets

**Comment by AircraftRu** [comment]
You can add the rights of associate assets when create a tickets but when a user doesn't have rights of update all tickets?
