### ISSUE TITLE
End of life MAP/POP Basic authentication on Exchange Online - October 2020

### ISSUE THREAD

**Issue by itpro-tips** [glpi-project/glpi#6895]
Hello,

Microsoft will remove basic authentication on Exchange Online in October 2020 [link](http://www.expta.com/2019/09/the-death-of-basic-authentication-in.html).
As a result, GLPI users who have Office 365 and who use IMAP / POP collectors will no longer work.
GLPI has a roadmap on this?

Thanks
EDIT : english language

**Comment by trasher** [comment]
Please use english, thnk you.

**Comment by cedric-anne** [comment]
Hi,

In GLPI 9.5, we replaced usage of PHP Imap extension by usage of Zend/Laminas Mail component.
I do not know if it will work for Exchange Online, but google provides a [simple example](https://github.com/google/gmail-oauth2-tools/wiki/PhpSampleCode) of an implementation of Oauth2 usage to connect to their mail servers, based on Zend/Laminas Mail component.

I guess implementing it could be done without too much pain by someone who has access to a GApps or a Exchange server. If you want to sponsor development of this feature, feel free to contact us at contact@teclib.com .

Regards

**Comment by trasher** [comment]
@itpro-tips you should test , give feedbacks and discuss on #6903. Thank you.

**Comment by Skouat** [comment]
Hi,

Based on Microsoft doc, Gmail Oauth will not work.
https://docs.microsoft.com/en-us/outlook/rest/php-tutorial

Maybe this could help : https://github.com/OfficeDev/office-content/blob/master/rest-api/php/getting-started-Office-365-APIs-php.md

Regards.

**Comment by Skouat** [comment]
Hi @cedric-anne,

From what I saw, Laminas framework handles more mail protocols but it doesn't add a support for OAuth2.

What do you think about the following library?
https://github.com/thephpleague/oauth2-client library

Regards.

**Comment by carlosbmc** [comment]
Something news about this?

Yesterday Octuber 1st Office365 account configured in receivers starst to fail

**Comment by teksetter** [comment]
I have the same problem.

**Comment by carlosbmc** [comment]
Problem using 9.5.1 version

**Comment by cedric-anne** [comment]
Hi,

We released this feature in a dedicated plugin: https://github.com/pluginsGLPI/oauthimap/

Documentation is not yet available, but I am working on it.

It should be available directly in the markeplace page.

If you encounter an bug, open an issue on the plugin reprository.

Regards

**Comment by cedric-anne** [comment]
Documentation: https://glpi-plugins.readthedocs.io/en/latest/oauthimap/index.html

**Comment by Pedrolit0** [comment]
Hi, 
Is there someone that got success on connecting collector to Azure oauth imap that can share his configuration from the azure side ?
I am getting some issue when trying to get the folder structure (connector seems is ok as i got a token from azure). 
Php error : An error occured trying to connect to collector. cannot change folder, maybe it does not exist

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.

**Comment by francescobianco** [comment]
Hi @trasher @Skouat @orthagh @teksetter @carlosbmc 

could you please look at https://github.com/javanile/php-imap2 to replace imap_*() functions with all equivalent imap2_*()
