### ISSUE TITLE
Right for task

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#690]
I have many questions about ticket task

In task, you have right to see public, right to see private.
The only right to update is Update all.

So the user can see all tasks, not only task affected to him. It's correct?
If not, we can filter this by: 
if no right to see private task and
- if task is private and task is affected to the user => he can read it
- if task is private but not affected to the user => he can't read it

If a user is affected to a task, he never update the task (to select Done or time spent on the task)?

If you don't have right to update all task but right to purge, you can't open the task to see the purge button

**Comment by tomolimo** [comment]
Hello Yllen,

I agree with you, but have a question about:

> If a user is affected to a task, he never update the task (to select Done or time spent on the task)?

Could you explain?
Thank you,
Tomolimo

**Comment by yllen** [comment]
Hello Tomolimo.

In a task, my name is selected in the field "By", so the task in affected to me (planned or not).
After i done the task, i never change the state of the task (for To do to Done)? I never indicate the time spent for doing the task?

**Comment by yllen** [comment]
Right put on the parent because must be use also by problemtask and change task.
Must review all rights for these 2 itemtype

**Comment by yllen** [comment]
@remicollet do you remember why task of problem and change don't use profile rights of tasks?
Actually problem task use right of problem and change task right of change

For me task rights are for all item with a task.

**Comment by remicollet** [comment]
Looking at the profile right configuration form, "tasks and followups" are indeed a separate section, so we could expect these rights apply to all objects (ticket, problem, change).

Having to duplicate these rights for each object type seems to much work for a low benefit.

**Comment by tomolimo** [comment]
Hello

Could it be possible that someone needs these to be configurable as separate item?

Tomolimo
