### ISSUE TITLE
[9.4.5] Unable to add email containing a single quote in the local part of the address

### ISSUE THREAD

**Issue by tuxxic** [glpi-project/glpi#6900]
**Describe the bug**

While adding a user email containing a single quote in it, the system refuses 

![image](https://user-images.githubusercontent.com/4680438/73736080-84d12700-4740-11ea-9abc-3fcc77aca760.png)

**Page(s) URL**

front/user.form.php

**To reproduce**

1. Go to the User form (front/user.form.php)
2. Try to add an email address containing a quote (ex: test'abc@example.org)

**Expected behavior**

The mail address is added, because they are acceptable characters : https://en.wikipedia.org/wiki/Email_address

**Comment by trasher** [comment]
This has nothing to deal with email address. Problem is on login field.
