### ISSUE TITLE
Error when applying rules to add and assign groups

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#6906]
**Describe the bug**

When several rules are applied during ticket creation when assigning a group it does not remove the groups added by other rules

**To reproduce**
1. A rule is executed to add a group.
2. Then another one is executed to assign a different group.
3. The ticket will have the two groups assigned

**Expected behavior**

When running the rule to assign a group you should remove the previous rule to add a group so the ticket created should have only one group assigned

**Screenshots**

First rule
![imagen](https://user-images.githubusercontent.com/39123808/73842255-7eb07880-481c-11ea-8c33-01e90a392dec.png)
Second rule
![imagen](https://user-images.githubusercontent.com/39123808/73842324-a30c5500-481c-11ea-8d80-5b3bc59a14b8.png)
Result
![imagen](https://user-images.githubusercontent.com/39123808/73842383-c33c1400-481c-11ea-9358-fb9ad2e43cfa.png)
Expected
![imagen](https://user-images.githubusercontent.com/39123808/73842418-d51db700-481c-11ea-9d49-0779f46d3d61.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.5
```

**Additional context**

I haven't checked if this also happens when I update the ticket

**Comment by cedric-anne** [comment]
Fixed by #6907

**Comment by tristangallet** [comment]
Thanks, it's weird because in the rule there is : use rule for add or update, but that's ok, it works with ADD which seems to be more logical, thanks.
