### ISSUE TITLE
[0.90.3] A bug in the rights of the tickets template

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#691]
if the ticket template "example" ticket to hide a field, such as the watcher, then if you select the category of ticket where set the ticket template to "default", then the field is revealed when you create a ticket - I believe this is a mistake

if the category to specify the ticket template "example", then when you create the ticket after it is hidden as it should be, but after that in all ticket these fields are hidden, even for administrator - this is a big mistake!

You need to delineate rights to it or to remove the dependence of the ticket template and of the created tickets!

![glpi - ticket templates - tickettemplate form php 2016-05-30 12 01 18](https://cloud.githubusercontent.com/assets/17082164/15645119/6311bc02-265f-11e6-9da9-67f213cd5779.png)

![glpi - ticket categories - itilcategory form php 2016-05-30 11 40 19](https://cloud.githubusercontent.com/assets/17082164/15645146/8ce9c704-265f-11e6-84aa-085e813fefc6.png)

![glpi - profiles - profile form php 2016-05-30 12 02 00](https://cloud.githubusercontent.com/assets/17082164/15645151/9077ebd0-265f-11e6-9f5a-7253e257c2f9.png)

**Comment by AircraftRu** [comment]
Do you understand me?

**Comment by yllen** [comment]
It's not a mistake.
When you create a ticket, template affected to the entity or to the profile is filled.
If you choose de catégory and this category has a template, the template of the category is filled.

**Comment by AircraftRu** [comment]
It's not right.
I want to hide the form of the watcher when a user create a tickets.
How do it? I'm a admin, the user with limited rights.

**Comment by yllen** [comment]
You must create a template of ticket affected on the user profile

**Comment by AircraftRu** [comment]
That's exactly what I did. But when choosing a category opens the field watcher, if in the category is specified the template default. 
If in the category is specified the my created template where hidden the field watcher then hiding this field in all existing tickets with this category.

**Comment by yllen** [comment]
Like i said: template of category is applied after template of profile that is applied after template of entity.
Is your end user uses the simplified interface, you can create a new category with the template applied and the already created category you define it as no visible for simplified interface.

**Comment by AircraftRu** [comment]
You realize that this is not right?
I want to hide the field watcher when user create tickets but don't want to hide this field all existing tickets for admins. All categories common for all admins and users.

**Comment by orthagh** [comment]
@AircraftRu the current template system doesn't permit to hide fields for self-service user and show them for technicians.
As @yllen said, if you assign ticket's template to a category, it will apply to your self-service users instead the one where you hid your field

I suggest you use the [formcreator plugin](https://github.com/pluginsGLPI/formcreator) to publish specific and driven forms to your sefl-service users.
It create tickets your technicians could manage, and you don't have to hide any fields (you define which fields are displayed)

**Comment by AircraftRu** [comment]
What is the meaning of such a system?

**Comment by tomolimo** [comment]
Hello You may also use http://plugins.glpi-project.org/#/plugin/hidefields

**Comment by AircraftRu** [comment]
I was hoping to implement it in GLPI without plugins, everything is hidden except the watcher. I'm not much upset.

**Comment by orthagh** [comment]
> What is the meaning of such a system?
A limitation, and no time to enhance this (big) part this for the moment, that's all.

**Comment by AircraftRu** [comment]
Ok, I got it.

**Comment by orthagh** [comment]
Thank you, for your undestanding.
Could you post this need on http://suggest.glpi-project.org for future release ?
