### ISSUE TITLE
saved alerts do not give the correct link

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6916]
Hi,

**Describe the bug**
I note the link in saved alerts don't go to the list of the saved alert.
Instead, the link sends to the home page. 

**To reproduce**
Make a saved search who send a email with a link to the saved search.

My link in my email is http://a.b.c.d/glpi/?redirect=%2Ffront%2Fsavedsearch.php%3Faction%3Dload%26id%3D21

and I think it's not correct because the page that appears is the home page.

Add a saved search who selecting something. make a notification using it and notification to email. Add in the template of the notification :
##savedsearch.url##
Run the saved search job, in the mail received, the link should seem same as mine.

NOTE : 
I have a .htaccess with this content : 
```
##Options -Indexes
##FallbackResource ../
```
This, because of URL modified by users, who permit to list directory instead of showing something.

RE-NOTE : Without this lines, the same context show the list of the saved searches instead of the content of the saved search. This is IF no browser is open, else if browser is already opened, it show the content of the saved search if my 2 lines are not present, and home page if they are.

I think there is a problem with this link and/or computing what to do with this link.

**Expected behavior**
The page should go to the content of the saved search.

**Logs**
No problem in logs. In the apache2 log, we don't see the initial link but just the call to home page.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.4.5 /plugin independant, I already try to disable some or all of them.

**Comment by cedric-anne** [comment]
Hi,

Seems that it duplicates an issue you already created (#6581).

Regards

**Comment by mab18** [comment]
Hi,
Right ! I should have write this precisions in the other ticket. ;-)
