### ISSUE TITLE
Error when filtering tickets by ID

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#6917]
**Describe the bug**

When trying to filter the tickets by 'Characteristics - ID' the options you can select are 'contains' or 'not contains' but when you run the sql it uses equal.

If that's its normal behavior you should change 'contains' to 'is'.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
9.4.5
```

**Comment by florian-lutz** [comment]
Hi, I also had some problems with the filter wording. But after looking around a bit, I found an explanation in the RestAPI documentation, mentioned in #2053.

https://github.com/glpi-project/glpi/blob/abd75a49d6d46f760e242532b0c617b4e802a093/apirest.md#search-items

- _contains_ will use a wildcard search per default. You can restrict at the beginning using the ^ character, and/or at the end using the $ character.
- _equals_ and notequals are designed to be used with dropdowns. Do not expect those operators to search for a strictly equal value (see ¹ above).

There is further information in the (french) documentation about the workings of the filter.

https://glpi-user-documentation.readthedocs.io/fr/latest/premiers-pas/rechercher.html

As far as I see it is never explicitly menitoned that numeric values are always compared as _equal_ even if the dropdown says _contains_. But you could deduce it from the example searches. And you can prefix a number with **<** **<=** **>** **>=** to achieve the corresponding comparison.

I also found out that switching to _not contains_ does not negate the search, only the leading NOT does. That might be considered a bug.

(And want to thank Sarah F. for looking through the french documentation)

**Comment by florian-lutz** [comment]
I created a quick patch that "solves" the wording and the _not contains_ issue.

[glpi-9.4.5-issue-6917.patch.txt](https://github.com/glpi-project/glpi/files/4389738/glpi-9.4.5-issue-6917.patch.txt)

**Comment by OscarBeiro** [comment]
Hi @florian-lutz,

Thanks for the information. This looks pretty good to me. Let's see what @cedric-anne thinks ;)

**Comment by cedric-anne** [comment]
Hi @florian-lutz ,

Please open a new pull request with your solution, so we could be able to see if tests are passing and everyone will be able to comment your fix.

Regards

**Comment by florian-lutz** [comment]
Ok, yould you please pull the Path from this Repository: https://github.com/florian-lutz/glpi-9.4.5-issue-6917-patch

**Comment by cedric-anne** [comment]
Please open a pull request by yourself, so you will be able to edit your changes if someone ask for changes on it.

To do so, use the edit icon (pencil) on https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/search.class.php , then patch the code and submit the change proposal. It will automatically create a pull request.

**Comment by florian-lutz** [comment]
Hi, thanks for describing it. I wasn't exactly aware of this workflow.
