### ISSUE TITLE
unable to select the good object in a project

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6928]
Hi,

In glpi/front/projet.form.php page, we can add Change, problems or tickets.

We can only select by the name, it's not convenient. See example of my site :
Selecting ticket on this page : 
![74033663-f4504c00-49b6-11ea-9928-362d5bb2ab2a](https://user-images.githubusercontent.com/55535560/74227751-69759700-4cbf-11ea-9f0e-c717045c13cc.png)
Selecting ticket on glpi/front/ticket.form.php (link to anothier ticket)
![74033591-cb2fbb80-49b6-11ea-9974-0b890d06ddd4](https://user-images.githubusercontent.com/55535560/74227763-6f6b7800-4cbf-11ea-9c26-ebafbaee54e2.png)

**Describe the solution you'd like**
It should be possible to select by the number (ID) too of the object. Otherwise, it's unusable in a majority of cases.

**Comment by msizec** [comment]
It is the same when we need to join a ticket to an article in the knowledge base

**Comment by cedric-anne** [comment]
Done in 09ee4a5.

**Comment by mab18** [comment]
Hi, Perfect !
