### ISSUE TITLE
Approval by Icon

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#6931]
Hello people,

Most of my users have reported that the approval icon on the "Accompaniments" screen is not intuitive, and I agree with them. I suggest that the approval area be more intuitive, following a very simple proposal.

![test](https://user-images.githubusercontent.com/35368369/74239157-07646400-4cb6-11ea-8416-ccfc5853f66c.PNG)

**Comment by orthagh** [comment]
Already done in incoming 9.5 release with pr #6258 

Here is a screenshot: 
![image](https://user-images.githubusercontent.com/418844/74239430-1cea8580-4cd8-11ea-93c0-79cc02aba375.png)

**Comment by orthagh** [comment]
Note also, you can ask for a validation directly in the same tab.
