### ISSUE TITLE
I can't use the backspace key to erase words I've written in a combo-box

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#6934]
When I have written a word in the filter of a combo-box I cannot delete a letter if I use the backspace key, in my case I have to move with the arrows and use the delete (SUPR) key.

It should be possible to use the backspace key to erase the letters of a word when using the search filter of a combo-box.

**Comment by cedric-anne** [comment]
Hi,

First, you did not provide informations that are requested when opening an issue (see https://github.com/glpi-project/glpi/issues/new?template=bug_report.md).

Second, unless I am wrong, you are talking about dropdown fields that are displayed using the Select2 javascript component. It is an external library that has its own repository and this bug may have already be fixed (or maybe you use a browser that is not supported anymore). Please open a ticket on their [repository](https://github.com/select2/select2) as we will not be able to fix this on GLPI directly.

Regards
