### ISSUE TITLE
Add null Computer select to License successfull 

### ISSUE THREAD

**Issue by Nawhath** [glpi-project/glpi#6941]
In Menu Management > Licenses

I choose 1 item,
    At the computer menu.
     I successfully added a computer without having to select items.
![2020-02-14 13_52_09-](https://user-images.githubusercontent.com/40232168/74509963-4fdd8500-4f35-11ea-910a-64adf8704d88.png)

This information will be found in the report. And I can't delete it.
![2020-02-14 14_15_15-GLPI - Detailed license report](https://user-images.githubusercontent.com/40232168/74510030-73083480-4f35-11ea-8def-8d4d3aad03f6.png)

Thank you.
Nath.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.
