### ISSUE TITLE
Wrong log path for phpmailer

### ISSUE THREAD

**Issue by neradp** [glpi-project/glpi#6943]
**Describe the bug**

phpmailer tries write to absolute path /var/log/phpmail.log 

**Expected behavior**

This could be path relative to GLPI instalation folder. (im running cron task as limited user without access to /var/log/ directory.)

**Logs**

Toolbox::userErrorHandlerNormal() in .../glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): mail(/var/log/phpmail.log): failed to open stream: Permission denied
  Backtrace :
  :                                                  
  vendor/phpmailer/phpmailer/src/PHPMailer.php:800   mail()
  vendor/phpmailer/phpmailer/src/PHPMailer.php:1713  PHPMailer\PHPMailer\PHPMailer->mailPassthru()
  vendor/phpmailer/phpmailer/src/PHPMailer.php:1518  PHPMailer\PHPMailer\PHPMailer->mailSend()
  vendor/phpmailer/phpmailer/src/PHPMailer.php:1352  PHPMailer\PHPMailer\PHPMailer->postSend()
  inc/notificationeventmailing.class.php:266         PHPMailer\PHPMailer\PHPMailer->send()
  inc/queuednotification.class.php:560               NotificationEventMailing::send()
  inc/crontask.class.php:829                         QueuedNotification::cronQueuedNotification()
  front/cron.php:83                                  CronTask::launch()
 Toolbox::userErrorHandlerNormal() in ..../glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): mail(/var/log/phpmail.log): failed to open stream: Permission denied
  Backtrace :
  :                                                  
  vendor/phpmailer/phpmailer/src/PHPMailer.php:800   mail()
  vendor/phpmailer/phpmailer/src/PHPMailer.php:1713  PHPMailer\PHPMailer\PHPMailer->mailPassthru()
  vendor/phpmailer/phpmailer/src/PHPMailer.php:1518  PHPMailer\PHPMailer\PHPMailer->mailSend()
  vendor/phpmailer/phpmailer/src/PHPMailer.php:1352  PHPMailer\PHPMailer\PHPMailer->postSend()
  inc/notificationeventmailing.class.php:266         PHPMailer\PHPMailer\PHPMailer->send()
  inc/queuednotification.class.php:560               NotificationEventMailing::send()
  inc/crontask.class.php:829                         QueuedNotification::cronQueuedNotification()
  front/cron.php:83                                  CronTask::launch()

**Comment by trasher** [comment]
There is no mail log configured in GLPI or PHPMailer. This cames from youyr PHP ocnfiguration.
