### ISSUE TITLE
specific entities notifications parameters

### ISSUE THREAD

**Issue by Rico29** [glpi-project/glpi#6944]
Hello,
It seems that the notification tab in entities settings does not act on sent notifications.

I have 2 entities, A and B.
A is configured with all email settings= adminA@domain.tld
B is configured with all email settings= adminB@domain.tld

global settings for email notifications : only param set is "admin email"=adminA@domain.tld

when a ticket is created in entity B, notifications are sent from adminA@domain.tld.

It should be sent from adminB@domain.tld.

**Page(s) URL**
https://glpi-dev.celya.fr/front/entity.form.php?id=304

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.4.5-git-9.4/bugfixes-1bd5991f34 ( => /usr/share/glpi_dev_9.4)

**Additional context**

external smtp relayhost

**Comment by Rico29** [comment]
updated glpi today to latest 9.4, still have the same issue

**Comment by Rico29** [comment]
another related post on forum : https://forum.glpi-project.org/viewtopic.php?pid=477433#p477433

**Comment by Rico29** [comment]
up !

**Comment by Knoppix1** [comment]
Hi !
i have the same issue with multi entities 

In header email recipt : 
From: GLPI <service-info@xxxxx.fr>
Reply-To: "intervention.ctm@xxxxx.fr" <intervention.ctm@xxxxx.fr>

<service-info@xxxxx.fr> is adresse mail of adadministrateur

My server in 9.4
Did you try in 9.5 ?
