### ISSUE TITLE
could not instantiate mail function when a mail contains certain characters

### ISSUE THREAD

**Issue by heikomania** [glpi-project/glpi#6945]
**Issue**

When the ticket contains a dot (.) followed by a break/new line (user presses Enter) and in the next line another dot (.) the system fails to properly format the notification, cuts the text after the first dot and you get the error "Could not instantiate mail function" in GLPI. Also the systems will sent an email - which is not formated in HTML - and it will send the mail 5 times.

**To reproduce**

1. Send a mail with a text like this to your inbox:
'Test.
.
You can added more text here'
2. Wait until the job grabs the mail.
3. Assign the ticket to a technician - now you'll see the error message and you will receive the wrongly formatted email and the text will be cut off after the first dot.

**Expected behavior**

Even if an email is typed this way, it should work like any other ticket.

**Screenshots**

Initial email:
![grafik](https://user-images.githubusercontent.com/7688883/74639271-eac0a400-516d-11ea-8a24-10c8a92b84b7.png)

Email after you assigned the ticket to a technician:
![grafik](https://user-images.githubusercontent.com/7688883/74639312-fdd37400-516d-11ea-8ba8-df111e6e4a20.png)

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.
