### ISSUE TITLE
Error in "Time to allow 'Remember Me' "

### ISSUE THREAD

**Issue by emaw705** [glpi-project/glpi#6948]
Hi.

In Setup -> General -> General Setup, the option "Time to allow Remember Me" show the value 'Disabled' when the option selected is < 1 day. When the option selected is >= 1 day, the option is displayed correctly.

Nevertheless, when the automatic task 'Session' is executed, it consider the option selected.

I'm using GLPI 9.4.4.

Best regards.

**Comment by cedric-anne** [comment]
Hi,

#7454 should fix this issue.
This was indeed a display issue only.

Regards
