### ISSUE TITLE
receivers error when receive mail to create ticket

### ISSUE THREAD

**Issue by snakewqq** [glpi-project/glpi#6960]
**Describe the bug**

i update GLPI version from 9.4.2 to 9.4.5, and updated the database by install.php.
with 9.4.2: receivers work well (receive email from mailbox to create ticket)
but with 9.4.5 and same settings, it have error, can not connect to mailbox, i reset the receivers config, same error, i don't know how to debug it.(9.4.5 is a new server)

**Page(s) URL**

/front/mailcollector.form.php

**To reproduce**

9.4.5
![image](https://user-images.githubusercontent.com/16697584/75000109-6a18e500-5498-11ea-82ae-7118f9abf022.png)

9.4.2
![image](https://user-images.githubusercontent.com/16697584/74999482-bbc07000-5496-11ea-969b-9403b053ffff.png)

**Expected behavior**

**Logs**

```
[2020-02-21T10:44:01.915128+08:00] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /data/www/wwwroot/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): imap_open() has been disabled for security reasons
  Backtrace :
  :
  inc/mailcollector.class.php:1229                   imap_open()
  inc/mailcollector.class.php:659                    MailCollector->connect()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  inc/crontask.class.php:829                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@BT-GLPI"}
[2020-02-21T10:44:01.915283+08:00] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /data/www/wwwroot/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): imap_open() has been disabled for security reasons
  Backtrace :
  :
  inc/mailcollector.class.php:1229                   imap_open()
  inc/mailcollector.class.php:659                    MailCollector->connect()
  inc/mailcollector.class.php:1795                   MailCollector->collect()
  inc/crontask.class.php:829                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
  {"user":"@BT-GLPI","mem_usage":"0.000\", 2.55Mio)"}
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by snakewqq** [comment]
*** PHP Warning(2): imap_open() has been disabled for security reasons

I fixed it.
php imap_open is disabled, open it will fix it.

**Comment by tubeprem0101** [comment]
> *** PHP Warning(2): imap_open() has been disabled for security reasons
> 
> I fixed it. php imap_open is disabled, open it will fix it.

sorry i have same issue but i new on GLPI,,,where i can fix it?
