### ISSUE TITLE
[9.4.5] Knowledge base: restore revision removes backslashs in text

### ISSUE THREAD

**Issue by pxlcore** [glpi-project/glpi#6961]
I have a article in the knowledge base. This article has multiple revisions.
I restored one of the latest revisions and GLPI removes the backslashes in the text. Double backslash will get one backslash.

**Example**
original:
`\\SERVERNAME\Path1\Path2`
Result after restore:
`\SERVERNAMEPath1Path2`

The revision preview (_show_ link) of the old revision still shows the correct text with all backslashes

**Comment by trasher** [comment]
Fixed in https://github.com/glpi-project/glpi/commit/ebca9b1a7e6a347e30273f281e3518f34e42c8c4
