### ISSUE TITLE
Question about notifications

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#6962]
**Describe the bug**
_Not a bug_

A clear and concise description of the question : 
What does GLPi do with notifications when a ticket have two tech groups with the same users and one group have "can be notified=yes" and the other have "no" ?
Notification or not for users are in the two groups ? 
Are group order important (by the alpha sort)... ???

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
