### ISSUE TITLE
User display name behavior

### ISSUE THREAD

**Issue by thiagosmartins** [glpi-project/glpi#697]
I have GLPI 0.90.1, but it looks like it happens on newer versions also.

When a user does not have both First Name and Last Name present, GLPI displays only the login of the user on the system.

The correct behavior should be that if the user have any of the information (First Name OR Last Name)  to show the information available. If the user only have the login and no other information, then display the login.

For me, this is a bug, but maybe it is the expected behavior in your vision. I think it is more logical to display the information in the way the administrator needs. In some countries, Last Name is not more important than middle name and some names are big (5 or 6 names) and all names are as important. Some times the First Name, Last Name can cause duplicates too.

In my setup, I want do display the user Full Name. In my Active Directory, this is the DisplayName field. I am mapping this to the Name inside GLPI, but if I don`t populate Surname with a valid field, the login is always showing up.

Is there any way to change this behavior without code? Maybe I am missing some configuration.

**Comment by yllen** [comment]
Last name is mandatory to not display the login.
First name only is not enough because lot of persons has the same first name

**Comment by flegastelois** [comment]
Hi,

Please open a feature request on http://suggest.glpi-project.org

Regards,
