### ISSUE TITLE
Dropdown 'user validate' of Tickets in Search Option, no shows Users

### ISSUE THREAD

**Issue by OscarLoayzaB** [glpi-project/glpi#698]
Syntax Error: index de searchoption for 'users_id_validate'
line 1133 and 1135 for properties 'right' It`s 59 not 58.
cause problem in the dropdown

class file 'commonitilvalidation.class.php'

      $tab[59]['table']             = 'glpi_users';
      $tab[59]['field']             = 'name';
      $tab[59]['linkfield']         = 'users_id_validate';
      $tab[59]['name']              = __('Approver');
      $tab[59]['datatype']          = 'itemlink';
      if (static::$itemtype == 'Ticket') {
         $tab[59]['right']          = array('validate_request', 'validate_incident');
      } else {
         $tab[59]['right']             = 'validate';
      }
      $tab[59]['forcegroupby']      = true;
      $tab[59]['massiveaction']     = false;
      $tab[59]['joinparams']        = array('beforejoin'
                                             => array('table'      => static::getTable(),
                                                      'joinparams' => array('jointype' => 'child')));

**Comment by yllen** [comment]
Thanks a lot for this bug and its correction.
