### ISSUE TITLE
[9.5] - size of an upload in simplified interface undefined

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#6990]
If I upload a screenshot in the simplified interface, the size of the upload fails to compute.

No JS error found

![image](https://user-images.githubusercontent.com/14139801/75549350-c0a19880-5a2f-11ea-903a-8ea7329d1d88.png)

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce this issue. I close the issue as I consider it has been fixed now.

Regards
