### ISSUE TITLE
PHP log error : couldn't fetch mysqli when enable debug mode

### ISSUE THREAD

**Issue by mab18** [glpi-project/glpi#7021]
Hi,
**Describe the bug**
When I enable debug mode, I have many and many message in PHP log

**Logs**

```
[2020-03-05 17:24:51] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /var/www/html/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): print_r(): Couldn't fetch mysqli
  Backtrace :
  :
  inc/html.class.php:3859                            print_r()
  inc/html.class.php:3848                            Html::printCleanArray()
  inc/html.class.php:3848                            Html::printCleanArray()
  inc/html.class.php:829                             Html::printCleanArray()
  inc/html.class.php:1671                            Html::displayDebugInfos()
  front/crontask.php:64                              Html::footer()```

GLPI 9.4.5

**Comment by trasher** [comment]
Sounds like you lost you mysql connection. You should check its log and adapt configuration.

**Comment by cedric-anne** [comment]
Duplicates #6546

**Comment by mab18** [comment]
Hi @cedric-anne & @trasher ,
Thanks for your correct answer !
If possible, just a question : Why this fix is not in 9.4.5 ?

**Comment by cedric-anne** [comment]
We did not initially detect it on 9.4 branch, and we thought that it was due to a change in 9.5 branch.

I create a pull request to apply this on 9.4 branch: #7026

**Comment by mab18** [comment]
@cedric-anne  & @trasher : Many Thanks !! :-) 

Have a good day
