### ISSUE TITLE
home screen shows expired satisfaction surveys

### ISSUE THREAD

**Issue by lfardin** [glpi-project/glpi#7028]
**Describe the bug**

When acessing home screen, the Satisfaction survey block displays all tickets that had no survey anwers, ignoring the configuration for the entity that dictates the Duration of survey

**Page(s) URL**

front/central.php

**To reproduce**

1. Define a expiration period for satisfaction surveys on an entity
2. Create a ticket and solve it
3. Wait the amount of days defined for survey expiration
4. Go to Home screen and the ticket is show as pendind survey, even when expired the survey

**Expected behavior**

No expired surveys should be displayed at home screen

**Logs**

not applicable

**Screenshots**

not applicable

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

 GLPI 9.4.5 ( => /var/www/html)

**Additional context**

not applicable

**Comment by arthurrschaefer** [comment]
I've seen some instances of 9.4.6 and 9.5.3. with this problem as well.

**Comment by AdrienClairembault** [comment]
This is the intended behavior, there is two important things to understand about surveys:

1\) First, surveys never expires.
What you call "expiration period for satisfaction surveys" define the time limit for **sending** surveys (once a survey has been sent there is no time limit to answer it).

2\) The home screen show the surveys for ticket where you are the requester AND for tickets that you created.
So if you created a ticket for someone else, this allow you to also answer the survey for them (delegation).
If you only want to see the surveys for the ticket where you are the requester then you need to disable the following right:
![image](https://user-images.githubusercontent.com/42734840/115683804-184b4380-a357-11eb-9a74-725066fcb3ad.png)

Best regards,
Adrien

**Comment by lfardin** [comment]
Adrien,

About the second behaviour, that was not my point, and I clear understand that.

My point was about the configuration below, that can be done on Entities management, tab "assistance":

![image](https://user-images.githubusercontent.com/56692658/115701814-90593f80-a33e-11eb-82e9-64b79021875d.png)

When I set "Create survey after" (creating it automatically after the selected time period), not requiring manual action, I understand that setting the configuation "Duration of survey" would define the time period for someone answer it, 

If is not what this setting means, probably the label is not so clear.

Im complement, I understand that, letting a user evaluate a ticket anytime can direct to poor data. As time time passes, the clarity of how well or not the ticket was solved is not the same (the user can even forget what was done).

For instance: my computer is working slowly. A technician acts and solve the incident (maybe optimizing, removing unwanted files, etc..). 5 months again, the computer can be slow again, and the user now says: the first ticket was poorly solved, so he can be influenced for a second problem, when trying to aswer the survey.

**Comment by AdrienClairembault** [comment]
Ifardin,

> When I set "Create survey after" (creating it automatically after the selected time period), not requiring manual action, I understand that setting the configuation "Duration of survey" would define the time period for someone answer it,
>
> If is not what this setting means, probably the label is not so clear.

I agree that the label may be confusing in the current interface.
It would be a lot clearer if we had a second option under it like "Time to respond to the survey".

However this "Time to respond to the survey" feature doesn't exist at this moment so any survey will stay open forever.

> Im complement, I understand that, letting a user evaluate a ticket anytime can direct to poor data. As time time passes, the clarity of how well or not the ticket was solved is not the same (the user can even forget what was done).

 If you think this feature is important you should submit it [here](https://glpi.userecho.com/).

Best regards,
Adrien

**Comment by lfardin** [comment]
Adrien,

Thanks again. 

Here's the link to this suggestion, so anyone requiring the same can vote

https://glpi.userecho.com/en/communities/1/topics/1957-time-to-respond-to-the-survey
