### ISSUE TITLE
Question about "Migration cleaner" tool

### ISSUE THREAD

**Issue by castorsenior** [glpi-project/glpi#7033]
Hi,
I have 9835 records in the tool "Migration cleaner" from a previous administrator on my GLPI/OCS server. What should I do with that ? What means the name ? What are these items called 0(1), 0(2), etc. ?
![image](https://user-images.githubusercontent.com/12443836/76301089-0414c600-62be-11ea-935a-785fa772f06e.png)
![image](https://user-images.githubusercontent.com/12443836/76301140-15f66900-62be-11ea-9f62-2839bc4010a2.png)
Some items have a square to click in and some not.
In any case, if I click on an item, the next screen tells me that I have no rights to see the content (but I have all rights) !
Thank you for your help !

**Comment by trasher** [comment]
First, informations requested in ticket template has not been provided. Second, where did you find the "tool" you are talking about? This does not seems present in GLPI.

**Comment by castorsenior** [comment]
Hi,sorry for the informations not provided. I'll give it in a few minutes. 
About the tool, it is here :   
![image](https://user-images.githubusercontent.com/12443836/76303605-493af700-62c2-11ea-8e6f-e901dc5e2b0b.png)
I have this inside :   
![image](https://user-images.githubusercontent.com/12443836/76303660-5eb02100-62c2-11ea-828d-99345b25c43b.png)
And if I click on the blue square, the machine works 30 minutes and finishes on a white screen. At this moment the URL is ...../front/ipnetwork.form.php

**Comment by trasher** [comment]
Oh ok, I've never seen this one before :D 
It seems to be a very old feature used for some 0.8x migrations; this will certainly be removed.

**Comment by castorsenior** [comment]
My environment :   
- GLPI 9.1.7.1 
- PHP 7.3.11
- MariaDB : 10.3.13
- Apache 2.4.34
- RedHat 7.7

**Comment by castorsenior** [comment]
When I migrate my GLPI 9.1.7.1, this tool is still present.

**Comment by trasher** [comment]
Yes, it will be removed; so I do not think we'll fix anything on it.

**Comment by castorsenior** [comment]
The debug shows : 
![image](https://user-images.githubusercontent.com/12443836/76305104-cff0d380-62c4-11ea-813a-87c2ac2b56f9.png)
![image](https://user-images.githubusercontent.com/12443836/76305155-e860ee00-62c4-11ea-89bf-0563eea668a7.png)

**Comment by castorsenior** [comment]
Shall I just truncate the table glpi_networkportmigrations ?

**Comment by trasher** [comment]
Since this seems to be used only for 0.8x migrations it has been written for; this table does not seems to exists for everyone (not present in standard install nor on 0.72 updated).
I have not idea how this was supposed to be used; but I guess your data has been migrated for a while.

**Comment by castorsenior** [comment]
Thank you very much @trasher for your attention and your help :-)
