### ISSUE TITLE
Add ticket writer as a criteria on business rule

### ISSUE THREAD

**Issue by OscarBeiro** [glpi-project/glpi#7037]
**Is your feature request related to a problem? Please describe.**

If a tech creates a ticket, and GLPI has:

1. Pre-select me as a technician when creating a ticket.

1. A rule to assign tickets to this tech.

This tech will be assigned twice.

**Describe the solution you'd like**

Adding  a new criteria **Writer** to Business rules for tickets will easily allow the exclusion of this  tech avoiding the problem.

**Describe alternatives you've considered**

Behaviors plugin can fix this by allowing only one tech, but this is not always an alternative.

**Additional context**

If you are interested we can work on this an make a PR

**Comment by tomolimo** [comment]
Fixed by #11234
