### ISSUE TITLE
GLPI 9.4.4 - LDAP user status not syncronize to GLPI user table

### ISSUE THREAD

**Issue by Zarau123** [glpi-project/glpi#7041]
Hello mates,

I need your help to solve a problem that I'm facing.

In my company we use GLPI 9.4.4 linked to our LDAP, I can import and synchronize without problems, but when it comes to the "active" field =yes/no the same is not changed.

GLPI - In the authentication settings is set to disable the user when it is disabled in Active directory.

Even if the syncronizer is forced it also does not change the status

Any suggestions or solutions? Thank you.

![image](https://user-images.githubusercontent.com/56557411/76540244-c5c40600-6479-11ea-8e56-bc0b06c278bd.png)

![image](https://user-images.githubusercontent.com/56557411/76540475-18052700-647a-11ea-8778-101bd81394c3.png)

**Comment by bigben386** [comment]
I have exactly the same issue even in 9.4.6. I have many users that are "missing" in ldap yet remain active in glpi. I have tried the different disposition options and it doesn't make a difference. I've tried manually syncing from the gui and bin/console.
![image](https://user-images.githubusercontent.com/9749364/81084253-9f43a980-8ec3-11ea-80b7-5f5405658658.png)

**Comment by aagz** [comment]
I have the same problem, in version 9.5.1

**Comment by aagz** [comment]
Hi, I solved this problem, you should to change authentication server for your accounts.

**Comment by sandroalvesbrasil** [comment]
I am facing this issue current version.

When I use the filter (&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2))) and try to update existing users, the deactivated users do not appear.

When I remove the filter they appear, but when I sync they don't disable.

But I get to change user status when I run forced sync for one or all.

Thanks.

**Comment by sandroalvesbrasil** [comment]
> Hi, I solved this problem, you should to change authentication server for your accounts.

I don't understand what you mean by changing the server.
