### ISSUE TITLE
Content Security Policy directive: "default-src * data: 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'default-src' is used as a 

### ISSUE THREAD

**Issue by davidg327** [glpi-project/glpi#7049]
When I open the tree I get this error and the entities are not seen as folders, the application is already on a server.

**_Refused to create a worker from 'blob: 'uri' because it violates the following Content Security Policy directive: "default-src * data: 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'default-src' is used as a fallback._**

![Captura de pantalla_2020-03-16_10-59-06](https://user-images.githubusercontent.com/47389371/76777427-2c953800-6776-11ea-90c7-794ddffdb2e0.png)

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by neoproject18** [comment]
Hello, how you solved this problem? I have same problem about this. Please help me. Thanks
