### ISSUE TITLE
[0.90.3] List is not sorted  in mail queue

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#705]
I click on the trash button, when I click on sort, example, "Send date" then everything is reset.

![glpi - mail queue - google chrome 2016-06-07 10 14 39](https://cloud.githubusercontent.com/assets/17082164/15851055/e213fb7e-2ca3-11e6-82fa-9eb0b130d8d4.png)

**Comment by orthagh** [comment]
Hi @AircraftRu 

See #589 and #593 for this issue.
It should be fixed in future 0.90.4
