### ISSUE TITLE
can't move a user from his entity

### ISSUE THREAD

**Issue by mmiat** [glpi-project/glpi#7053]
**Describe the bug**

I've created a user and i've selected his entity, now i want to change/move it in root entity but i can't

**Page(s) URL**

front/user.form.php?id=9

**To reproduce**

create a user, put in an entity, try to move to root

**Expected behavior**

I can move user

**Logs**

if you need Ill post later (now I can't access logs)

**Screenshots**

![Screenshot_20200318_160817](https://user-images.githubusercontent.com/11910225/76975344-b5f16980-6932-11ea-9de1-20a24911ee36.png)

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by mmiat** [comment]
GLPI Setup
[glpi.txt](https://github.com/glpi-project/glpi/files/4350237/glpi.txt)

**Comment by trasher** [comment]
Still no logs. Plugins list has been dropped from infos.  I've just tested on 9.4/bugfixes branch, cannot reproduce. 
Please try with up to date current bugfixes branch (or [latest nightly](https://forge.glpi-project.org/tarballs/)), and try without any plugins.
