### ISSUE TITLE
search an ip address

### ISSUE THREAD

**Issue by mmiat** [glpi-project/glpi#7057]
I've added 2 computers, added an ip address to each one, but when I search them I can't find. is ip address a field searchable or is it a bug?
thanks

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support. And as already said, requested informations are **mandatory**; future invalid tickets will just be closed.

**Comment by mmiat** [comment]
if it could be useful for someone in future, ip address is searchable after adding it as field in computer list
