### ISSUE TITLE
date de creation du ticket à 00:00:00

### ISSUE THREAD

**Issue by Sicoval31** [glpi-project/glpi#7065]
Bonjour,
je me retrouve face à un bug aléatoire découvert depuis la mise à jour en 9.4.2 en juin 2019, j'ai certain tickets qui ont une heure de création à minuit (alors que dans l'historique on retrouve la bonne heure).
De ce fait, les stats liés aux SLA, délai de prise en compte, etc sont complétement faussées.
cela représente à ce jour environ 6% des tickets; environ 0 à 2 ticket par jour sont dans ce cas

Je n'ai pas trouvé d'éléments communs entre les tickets impactés : toutes catégories, tous types, date, priorité, groupe, etc ...
Tous les cas sont représentés

Vue les nombreux bug et problèmes qu'amènent les versions suivantes 9.4.3 et 9.4.4, je suis très frileux à faire une montée de version.

de plus, en base mysql, la table glpi_tickets comporte deux champs similaires :
- Date, qui remonte en interface comme étant la date de création (c'est celle-ci qui est parfois générée à minuit sans aucune raison logique)
- Date_creation, qui ne remonte pas dans l'interface
ces deux dates sont souvent différentes avec parfois quelques heures d'écarts.
connaissez vous la différence entre ces deux champs ?

si vous avez une idée, une piste, une résolution, merci pour votre aide.
Excellente journée

**Comment by trasher** [comment]
English only please: https://github.com/glpi-project/glpi/blob/9.4/bugfixes/CONTRIBUTING.md#contributing-to-glpi
Please test on last release (9.4.5) or last nightly.
