### ISSUE TITLE
[GLPI 9.5] Display "Contract" In menu

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7067]
In transifex, there is no plural for "Contract"

![image](https://user-images.githubusercontent.com/13178158/77091359-bd834200-6a08-11ea-9b50-125a83c7779b.png)

![image](https://user-images.githubusercontent.com/13178158/77091413-ce33b800-6a08-11ea-8c94-f4022ff60414.png)

Into GLPI : 

![image](https://user-images.githubusercontent.com/13178158/77091689-2f5b8b80-6a09-11ea-9445-625e05540f1f.png)

**Comment by trasher** [comment]
Please fix directly on transifex (done for this one).

**Comment by tsmr** [comment]
I wanted to, but the glpi.pot was using the wrong value :P
