### ISSUE TITLE
Notification email sender error

### ISSUE THREAD

**Issue by JarJar025** [glpi-project/glpi#7084]
I have a hotline address and I want this address to be the sender of the notification. But I want my address to stay in administrator address.
My problem is when I am in Setup> Notification>Email followups configuration, I have this configuration
![image](https://user-images.githubusercontent.com/16539689/77534505-133c6c00-6e99-11ea-8e2d-f4e1e32f0775.png)

When I try to test with the debug mode I have those logs
2 - SERVER -> CLIENT: 235 2.7.0 Authentication successful ==> **NO PROBLEM IN THE PASSWD**
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: MAIL FROM:<hotline@domaine.com> ==> OK FOR ME
2020-03-25 12:32:33 [2@SRV-SUP]
2 - SERVER -> CLIENT: 250 2.1.0 Sender OK
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: RCPT TO:<myaddress@domaine.com> ==> OK FOR ME
2020-03-25 12:32:33 [2@SRV-SUP]
2 - SERVER -> CLIENT: 250 2.1.5 Recipient OK
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: DATA
2020-03-25 12:32:33 [2@SRV-SUP]
2 - SERVER -> CLIENT: 354 Start mail input; end with <CRLF>.<CRLF>
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: Date: Wed, 25 Mar 2020 12:32:32 +0100
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: To: ME <myaddress@domaine.com>==> OK FOR ME
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: From: ME <myaddress@domaine.com> ==> **NOK FOR ME**
2020-03-25 12:32:33 [2@SRV-SUP]
1 - CLIENT -> SERVER: Subject: [GLPI] Courriel test
...
CLIENT: 554 5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message 

The issue is because hotline@domaine.com address has no rights to send as myaddress@domaine.com address. The SERVER:From: Me is supposed to be hotline@domaine.com and not myaddress@domaine.com.
Am I right ?

[code]   GLPI 9.4.5 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux SRV-SUP 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 PHP 7.0.33-0+deb9u7 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	bcmath, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi.lerel.dom Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0 Server Software: Debian 9.11 	Server Version: 10.1.44-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: GLPI@localhost/glpi_db 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.1.44) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)

Server: '172.20.0.1', Port: '389', BaseDN: 'dc=lerel,dc=dom', Connection filter: 		'(&(&(objectClass=user)(objectCategory=person)(mail=*)(!(userAccountControl:1.2.840.113556.1.4.803:=2))))', RootDN: 		'CN=glpi,OU=Generique,OU=User,OU=_Lerel,DC=lerel,DC=dom', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (hotline@groupelerel.fr@smtp.office365.com)

Name: 'hotline@groupelerel.fr' Active: Yes 	Server: '{outlook.office365.com:993/imap/ssl}INBOX' Login: 'hotline@groupelerel.fr' Password: Yes

mydashboard          Name: Dashboard                      Version: 1.7.4      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+2.4    State: Enabled
[/code]

**Comment by lecbee** [comment]
Hello,

Same problem for me (version 9.4.5 too).

After few hours of troubleshooting, I found out that when GLPI send the email, it effectively send it with the correct _Sender SMTP field_ (as requested), but it keeps the _Administrator email_ inside the **SMTP/IMF data** (aka rfc822) instead of changing it to the requested one.

So there is two different values for that mail. Our server (MS Exchange here) doesn't like that at all and responds with :
_5.7.60 SMTP; Client does not have permissions to send as this sender_

**Comment by lecbee** [comment]
Hello,

Same problem for me (version 9.4.5 too).

After few hours of troubleshooting, I found out that when GLPI send the email, it effectively send it with the correct _Sender SMTP field_ (as requested), but it keeps the _Administrator email_ inside the **SMTP/IMF data** (aka rfc822) instead of changing it to the requested one.

So there is two different values for that mail. Our server (MS Exchange here) doesn't like that at all and responds with :
_5.7.60 SMTP; Client does not have permissions to send as this sender_

**Comment by lecbee** [comment]
Actually, it doesn't work ONLY in the testing function !
The emails are sent correctly when using the notifications as expected in the other part of the application.

In order to fix the testing function, here is a ugly hack (for the version 9.4.5):

```
Edit "/usr/share/glpi/inc/notificationmailing.class.php":

Change line 89 :
$mmail->SetFrom($CFG_GLPI["admin_email"], $CFG_GLPI["admin_email_name"], false);

By :
//$mmail->SetFrom($CFG_GLPI["admin_email"], $CFG_GLPI["admin_email_name"], false);
$mmail->SetFrom('your-sender-email@myserver.myorg.dom', '', false);


And change lines 127/128 :
$data['sender']                               = $options['from'];
$data['sendername']                           = $options['fromname'];

By :
//$data['sender']                               = $options['from'];
//$data['sendername']                           = $options['fromname'];
$data['sender']                               = 'your-sender-email@myserver.myorg.dom';
$data['sendername']                           = '';
```


"**your-sender-email@myserver.myorg.dom**" should be the same value as stored in the "front/notificationmailingsetting.form.php" web page.
