### ISSUE TITLE
Standardize colors to improve theming

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#7087]
**Is your feature request related to a problem? Please describe.**
The current core CSS styles are a mess of seemingly randomly picked colors and it makes it difficult to maintain the built-in themes or add new rules that conform to style guidelines. For example, there was a few times when a feature was added with hard coded colors, but the new "darker" theme wasn't updated as well so it looked ugly for that theme or was just plain unusable/unreadable.

On a slightly outdated 9.5 build I found 1619 total hex color codes (did not check other formats so its even worse), with there being 162 unique ones.

The new "darker" theme is evidence of this issue when any other palette is around 130-200 lines, this one is around 800 and it still doesn't look right.
Just a few examples:
- Central dashboard icons are black on gray and difficult to see.
- Assets dashboard is very out of place and uncomfortable when expecting a mostly dark page (white background taking up most of the screen)
- Multiselect dropdown selections are unreadable because of gray on gray colors (Fails accessibility audits)
- Text over the bars in General > Performance are unreadable (These are done by images which is a pain to style for).

Looking at the colors in the styles.scss file, many of them are very similar and can probably be made to match.

**Describe the solution you'd like**

1. Replace hard coded colors with variables that are named by their purpose.
2. Modify palettes to define the colors.
3. Move default colors to the default auror palette.
4. Add import statement in core stylesheets for the default palette.
5. Remove inline styles related to colors when possible

For example, one of my projects has the following in a theme css file:
```
:root {
   --nav-primary-bg-color: #4d4d4d;
   --nav-secondary-bg-color: #737373;
   --nav-text-color: white;
   --nav-hover-text-color: #eeeeee;

   --body-bg-color: #fafafa;
   --body-text-color: #1a1a1a;

   --content-bg-color: #fafafa;
   --content-hover-bg-color: #e8e8e8;
   --content-text-color: #1a1a1a;

   --table-header-bg-color: #e8e8e8;

   --form-field-bg-color: #fafafa;
   --form-field-hover-bg-color: #e8e8e8;
   --form-field-text-color: #1a1a1a;
}
```
GLPI would have more colors defined, but this should give you an idea of what I'm talking about.

**Describe alternatives you've considered**

No other alternatives considered.

**Additional context**

These changes will make it easier to add a theme designer in the future or allow users to create and share their own palettes/themes without messing around with 162 different colors. We could easily add a page with a few colors that they can change and generate a working palette/theme file.
Example designer from OpenITCockpit:
![Selection_030](https://user-images.githubusercontent.com/17678637/77567007-e38f6300-6e9c-11ea-9882-bac226150c49.png)

This request can be expanded to other things like font sizes, fonts, etc.

https://glpi.userecho.com/communities/1/topics/115-add-the-posibility-to-choose-a-theme-and-change-logo-colors-and-look-and-feel

**Comment by phamorais** [comment]
@cconard96 

any chance this  in roadmap 9.5?

**Comment by cconard96** [comment]
> @cconard96 
> 
> any chance this  in roadmap 9.5? 

No. This would be a major change and would have to wait for the next major version at least. New 9.5 releases are mainly bug fixes only.
The first major part of this is on the roadmap for the next major version already.

**Comment by phamorais** [comment]
Thx @cconard96 !

**Comment by cconard96** [comment]
The request I made here to standardize colors is sufficiently covered (and more) by the UI/UX rework being done for GLPI 10.0. See #8365.
The theme designer suggestion isn't required for me anymore.
