### ISSUE TITLE
Category not respecting child entities in simplified ticket

### ISSUE THREAD

**Issue by magaiverpr** [glpi-project/glpi#709]
Hello!

When I try to open tickets in simplified mode, the category dropdown show all the categories that are in others entities when I am in root entity.

In standard mode its ok, none are shown.

[code]
 
GLPI 0.90.3 ( => /var/www/glpi)

Server
 
Operating system: Linux heldesk 3.2.0-4-amd64 #1 SMP Debian 3.2.63-2+deb7u2 x86_64
PHP 5.4.36-0+deb7u3 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype,
	date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mhash, mysql,
	mysqli, openssl, pcre, pdo_mysql, posix, session, shmop, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx,
	xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.2.22 (Debian) (Apache/2.2.22 (Debian) Server at servicedesk.restaurantemadero.com.br Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Server Software: (Debian)
	Server Version: 5.5.40-0+wheezy1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

Libraries
 
htmLawed version 1.1.21 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/glpi/lib/password_compat). Compatitility: Ok

**Comment by yllen** [comment]
Is your profile with simplified interface recursive?

**Comment by magaiverpr** [comment]
Yes!  But even when I change the interface in "profile" without changing the recursive status, this keeps happen.
