### ISSUE TITLE
[GLPI 9.5] Icon display for Impact analysis

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7091]
Hello

In our plugin we use a function for display pics of objects like : 

[PluginCmdbTest] => plugins/cmdb/front/icon.send.php?idDoc=30617

And into impact.class.php, we cannot use it because the code check the existence of the pics : 

```
if (!file_exists(__DIR__ . "/../$icon")) {
   $icon = "pics/impact/default.png";
...
if (!file_exists(__DIR__ . "/../$image_name")) {
   $image_name = "pics/impact/default.png";
```

So we cannot display our icons on graph

Can you change the check to : 
```
if (empty($icon)) {
   $icon = "pics/impact/default.png";
...
if (empty($image_name)) {
   $image_name = "pics/impact/default.png";
```
Or do an exception for plugins which do not use a direct access of a pics directory, but a document uploaded into GLPI ?

Goal : 

![image](https://user-images.githubusercontent.com/13178158/77754174-14050780-702b-11ea-8f85-0571bc5934ff.png)

Thanks for that

**Comment by tsmr** [comment]
Ok for me. Thanks. 👍

**Comment by virgiliua** [comment]
Hello !
I have GLPI 10.0.3 and 2.14.1 Object Inventory plugin installed. 
In "Impact analysis", any object added it's not show it's icon that it was uploaded in /files/_plugins/genericobject/impact_icons/ Directory
In the /www/src/Impact.php file, the lines:
       _// Check if icon exist on the filesystem_
        $file_path = GLPI_ROOT . "/$icon_path";
        if (file_exists($file_path) && is_file($file_path)) {
			return $icon_path;
        }
return an error in browser console:
GET https://files/_plugins/genericobject/impact_icons/PluginGenericobjectFrigidere_5ee98bf0744a7c.76164678frigorifero-refrigerator.png 
**net::ERR_NAME_NOT_RESOLVED**
I cannot find a solution to solve this, but is clear that the server **domain.com** is missing in URL.
Also, I try change the **return** line from above file, with direct path to picture:
return "files/_plugins/genericobject/impact_icons/PluginGenericobjectFrigidere_5ee98bf0744a7c.76164678frigorifero-refrigerator.png";
And it's get a **403 access error** in browser console :
GET https://domain.com/files/_plugins/genericobject/impact_icons/PluginGenericobjectFrigidere_5ee98bf0744a7c.76164678frigorifero-refrigerator.png 
**403 (Forbidden)**

Any solution or suggestion?
Thank you !

**Comment by AdrienClairembault** [comment]
Hello @virgiliua,

We'd prefer to keep this issue closed as it was already solved 2 years ago (it is not really the same as the one you are describing).
Feel free to open a new one with your problem and the team will look into it when they have time.

You may also consider [professional support](https://services.glpi-network.com/) if you need this specific issue be prioritized.
