### ISSUE TITLE
[0.90.1] Number of tickets link to users in multi entity configuration

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#710]
Hello,

Issue open following #632.

When you create ticket with end-user requester, below name of requester, you see number of tickets with "Processing" status. "Processing : X" seems to count tickets opened in all entities. However, if you are a technician, you only need to have count of tickets opened in **your** entity.

Entity configuration
```
               Organisation name (parent entity)
                    |
                    |
-------------------------------------------
|                   |                     |
|                   |                     |
Entity A (ex : IT)  Entity B           Entity C
```
All our end-users have self-service recursive profiles on parent entity. Technicians have technician profiles (no recursive) on entity which correspond to their department (ex : IT).

Steps to reproduce : 

1. In entity A, create a ticket as technician with end-user requester (self-service recursive profile on parent entity).
2. In entity B, create a ticket as technician with same end-user requester 
3. Click on link "Processing : X" . Search shows only tickets opened in entity B but "Processing : X" seems to count tickets opened in entities A + B.

**Comment by orthagh** [comment]
see 3c27899c306b0cf09a2b523ec61e3de09c3dcb6c

**Comment by orthagh** [comment]
I think it's an entity problem.

I detected that summary view doesn't show the tickets which you are writer but not requester.
I pushed just now, a commit to fix that.

Could you test the changes listed in https://github.com/glpi-project/glpi/commit/2a2e4fee02881335df5870cea78c0b6532d6e5c6 ?

**Comment by nqb** [comment]
Hello @orthagh 

In 0.90.4, we have same issue.

Moreover, I notice that when you go on end-user requester form, you have same issue with "Created tickets" tab. Steps to reproduce : 

Go in Administration -> Users : 
1. Select a User
2. Click on "Created tickets". For example, you see 70 items but tab "Created items" report a count of tickets opened in entities A + B.

**Comment by orthagh** [comment]
you're right, the above fix is not at the good part of glpi.
New fix incoming

**Comment by orthagh** [comment]
next bugfixes version will really fix that issue
