### ISSUE TITLE
[0.90.1] Category not under "X" lists only tickets with category

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#711]
Hello,

When you do a search with this criterion : 
`Characteristics - Category // not under // Example`
You don't see tickets without category. In my opinion, you should see these tickets.

If you do a search with this criterion : 
`Characteristics - Category // is not // Example`
You see tickets without category.

**Comment by yllen** [comment]
Not under X means ticket have a category that is not a sub category of X category.

To search tickets without category you must select
Contains ^$ (means empty)
