### ISSUE TITLE
[0.90.3] Rights on reminders when accessing planning via http (Ical)

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#712]
Hello,

When a user create a reminder and plan it with a group target, it appears in : 

- Assistance -> Planning -> Personnal view and Group view for group members
- Download of the planning in Ical format for group members

However, it appears **only** in owner's note planning when using http link of Ical planning.

## Steps to reproduce : 

Needs : two accounts "foo" and "bar" in group "example".

With account "foo" : 
1. Create a reminder, plan it
2. Add a target for "example" group

With account "bar"
1. Go on Assistance -> Planning -> Personnal view and Group view : you see reminder.
2. Click on "Ical" on "Group view". Download file. Open file : you see reminder.
3. Click on "Ical" and choose "Copy link address"
4. Configure your iCal client with link address copied at step 3 : you **don't** see reminder

With account "foo"
1. Go on Assistance -> Planning -> Personnal view and Group view : you see reminder.
2. Click on "Ical" on "Group view". Download file. Open file : you see reminder.
3. Click on "Ical" and choose "Copy link address"
4. Configure your iCal client with link address copied at step 3 : you see reminder

**Comment by orthagh** [comment]
Hello @nqb 

Next major version of glpi (9.1) will contains a full rewrite of planning.
I did also a rewrite of ical part (library change).
This version will come soon (we're reviewing and bugfixing major features)

If it's a valid option for you, i plan to do nothing on this issue, as it will be fixed soon. Your opinion

**Comment by nqb** [comment]
I will test in 9.1. You can close this issue.
