### ISSUE TITLE
[GLPI 9.5] New item - virtualization - no selecting from the list

### ISSUE THREAD

**Issue by miodzio97** [glpi-project/glpi#7121]
Please add on the Computers tab -> virtualization -> add virtual machine the option of selecting such a mass from the list of computers. 
Currently, this can only be entered manually, but it makes no sense while the virtual machines are inventoried and are in GLPI.

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
