### ISSUE TITLE
Error in "Associated elements" in "Tools" ->"Knowledge base" menu

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#7122]
**Describe the bug**:

Hello.
Each time we access a knowledge base article, if we choose the "Associated elements" option, we keep getting the same error:

![image](https://user-images.githubusercontent.com/43515938/78365663-4b3d6080-75b7-11ea-8351-50b89daf5efa.png)

Activating Debug Mode:

![image](https://user-images.githubusercontent.com/43515938/78366481-78d6d980-75b8-11ea-9d35-0be728cab824.png)

Why is this happening? Anyone?
Is it really a bug? Or maybe a problem in our configuration?

**Comment by cedric-anne** [comment]
Duplicates #6568
