### ISSUE TITLE
Is there a way to automatically merge tickets into followups?

### ISSUE THREAD

**Issue by Cristian9828** [glpi-project/glpi#7124]
Hi, I just upgraded my GLPI to the 9.4.5 version. In the 9.3 version we are using for our company, we have the possibility to reach answers to a ticket email like a followup of the same. It is very important and comfortable because we use to communicate with the user by emails only. It is great for our ticketing system, working perfectly.
My question so is: is there a way to set ticket merging automatic like it was before the upgrade?
Thank you very much!

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
