### ISSUE TITLE
[0.90.1] Clickable links in Timeline

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#713]
Hello,

When you add an HTTP link in followup ou task (like http://example.fr), you can directly click on. However, it doesn't work for all extensions like ``example.lan`` or ``example.local``.

It is a configurable thing or a parsing error ?

**Comment by orthagh** [comment]
Hello @nqb 

It's not configurable and i think it can't be considered as a parsing error.
Kind of links you provide as example can't be considered as valid by a parser (currently http://www.kwi.dk/projects/php/UrlLinker/).

Your links should contains https?:// to be linkable in timeline

**Comment by nqb** [comment]
Hello @orthagh,

My links contains "https?://". If you add "http://example.lan" or "http://example.local" in timeline, links are not "clickable". However UrlLinker's documentation says : 

> UrlLinker is a PHP module for converting plaintext to HTML, and any URLs in the text into HTML links.

http://example.local or http://example.lan are **any URLs**.

**Comment by orthagh** [comment]
Oh i see, 

urllinker have a list of valid tld (from http://data.iana.org/TLD/tlds-alpha-by-domain.txt).
If you want to add your own, edit the file glpi/lib/urllinker/urllinker.php
