### ISSUE TITLE
[GLPI 9.4.5] Receiver: Querying mailbox folder fails for shared mailboxes "Connection errors"

### ISSUE THREAD

**Issue by mooseyfate** [glpi-project/glpi#7132]
**Describe the bug**

When setting adding/editing a mail receiver, using an Office365 shared mailbox causes "Connection errors" message when trying to query the remote folders.

The error turns out to be a string with backslashes being escaped twice, resulting in four backslashes.

**Page(s) URL**

https://glpi.domain.com/front/mailcollector.form.php?id=X

**To reproduce**

1. Add/edit a mail collector.
2. Configure an Office365 shared mailbox: account@domain.com\shared_mailbox@domain.com
3. Fill in the rest ff the form.
4. Click on the hamburger (three parallel lines)
5. Observe error.

**Expected behavior**

Show remote folders.

**Logs**

_log/php-errors.log:
```
*** PHP Warning(2): imap_open(): Couldn't open stream {outlook.office365.com/imap/novalidate-cert/tls}
  Backtrace :
  :
  inc/mailcollector.class.php:1229                   imap_open()
  inc/mailcollector.class.php:378                    MailCollector->connect()
  ajax/mailcollector.php:73                          MailCollector->displayFoldersList()
*** PHP Notice(8): Unknown: LOGIN failed. (errflg=1)
 *** PHP Notice(8): Unknown: Too many login failures (errflg=2)
```

**Additional context**

Investigating the code, I found that the AJAX call results in backslashes being escaped twice.
The "login" field for example, becomes "account@domain.com\\\\shared_mailbox@domain.com" and the login to Office365 fails.

I edited "ajax/mailcollector.php" and added the below line to remove the additional slashes.

//fix back-slashes being escaped too much (for shared mailboxes)
$input['login'] = str_replace ('\\\\' , '\\' , $input['login']);

**Comment by trasher** [comment]
Problem is certainly GLPI sanitize on GET/POST; you should probably use `stripslashes` rather than `str_replace`. Could you open a pull request with the correct fix?

Please also note mail collector connection has been entirely reworked on 9.5, dunno yet if the bug will happens on it as well (I had never seen a mail login with a backslash before :D).

**Comment by mooseyfate** [comment]
#7139 pull request created.
Apologies if I did not reference the issue correctly.
