### ISSUE TITLE
Since upgrade GLPI 9.4.5 notification are no more sent every minutes

### ISSUE THREAD

**Issue by troublestarter** [glpi-project/glpi#7137]
**Describe the bug**

Notifications are no more sent every minutes

**Screenshots**

See this attached screen
![image](https://user-images.githubusercontent.com/6012203/79231694-c11eb300-7e66-11ea-8dd8-f1e52cb5085c.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Linux support 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64
PHP 5.6.37-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	bcmath, bz2, calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json,
	ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at support.my-cosi.info Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0
Server Software: Debian 9.1
	Server Version: 10.1.26-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (10.1.26) - Perfect!Database version seems correct (10.1.26) - Perfect!
OK/usr/share/glpi/files/_log : OK
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_cache : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

**Comment by troublestarter** [comment]
Bug vu ici aussi :
https://forum.glpi-project.org/viewtopic.php?id=168100

**Comment by troublestarter** [comment]
Tested with CLI mode and works well

So big bug in GUI mode

**Comment by trasher** [comment]
If uit works with CLI, your crontask is configured from cli (and won't work from web). Either setup a system crontask (recommended) or swithc your crontasks to web mode.

**Comment by troublestarter** [comment]
When i am in GUI mode, mail are sent not everyminutes like before upgrade...
So i have switched to CLI mode (with crontab)

**Comment by trasher** [comment]
Using cron via the web UI are only triggered when a page is visited; a real crontab is really better. You may try with current 9.4/bugfixes which may contains fixes.

If the cron was broken, it would not work from CLI neither, so this is certainly linked to your environment or some config (or even a bug, but we have to know how to reproduce); so you'll have to search to find out what is wrong if you really want.

**Comment by trasher** [comment]
Oh and also... Please make sur you run all CLI commands with the same user the webserver uses, to prevent conflicts (ie. do not run cron.php as root...).
