### ISSUE TITLE
[0.90.3] Tab "used items" doesn't count items

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#714]
Hello,

When you go in Administration -> Users : 

1. Select a User
2. Click on "Used items". For example, you see 3 items but tab "Used items" doesn't have number "3" next to his name.

**Comment by yllen** [comment]
We can't display a count for Used items and Managed items because types of items are different and can come from a plugin

**Comment by nqb** [comment]
Hello,

Is there is an alternative to indicate that users have Used items and Managed items ? 
Today, you have an invalid view of a user.

**Comment by yllen** [comment]
Check all used or managed items will severely impact the performances of GLPI.
So no, it's not possible
