### ISSUE TITLE
GLPI 9.4.5 very slow

### ISSUE THREAD

**Issue by OlivierPITHON** [glpi-project/glpi#7140]
Hello,

Since last upgrade to GLPI 9.4.5 the application is very slow.
Pages takes times to appear and drop down list are specially slow.
We use Windows Server 2016, My SQL 8, GLPI 9.4.5
I have Added ZendOPcache 7.1.7 but no change.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

Also, please give more informations, no idea what is "slow" (php processes, network requests, db, ..., ...).

**Comment by OlivierPITHON** [comment]
When we open a ticket and choose the user the drop down list take few second to appear, after when choose the user the page became completely blank and reappear after few second. This is the same on every menu : drop down list slow + pages which Always refresh themselves slowly.

**Comment by tsmr** [comment]
With IIS you need to replace localhost to 127.0.0.1 into config_db.php

**Comment by tomolimo** [comment]
Hello @OlivierPITHON 

What was the previous version of GLPI?
Did you also upgrade the MySQL application?
Have you also activated wincache?
Could you post the "information about system installation and configuration" section of the Setup > System tab? What is between the tags [code] and [/code]

Thank you,
Regards,
Tomolimo

**Comment by OlivierPITHON** [comment]
Solved now
This issue was due to SSO implementation that required a change setting in :

/config/config_db.php

$dbhost=’localhost’; => $dbhost=’127.0.0.1’;


Thanks


Regards



Olivier Pithon
System and Network Administrator
........................................................................................
Recipharm Monts
Adresse: 18 Rue de Montbazon | 37260 MONTS | France
Téléphone: +33 2 47 21 10 20 (Direct) | +33 2 47 26 68 82 (Fax)
www.recipharm.com<http://www.recipharm.com/>


[Logo signature email]

________________________________
De : tomolimo <notifications@github.com>
Envoyé : jeudi 16 avril 2020 14:50
À : glpi-project/glpi <glpi@noreply.github.com>
Cc : Pithon, Olivier <Olivier.Pithon@recipharm.com>; Mention <mention@noreply.github.com>
Objet : Re: [glpi-project/glpi] GLPI 9.4.5 very slow (#7140)


Hello @OlivierPITHON<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOlivierPITHON&data=02%7C01%7Colivier.pithon%40recipharm.com%7C6b3aaee5cc524af8851a08d7e204bb77%7Caf1d2833a47b4ad187d8fe0a82ba7957%7C1%7C0%7C637226382267057033&sdata=6%2BkhmlpxHpngA6RyOWH8Y9GRfacAhwFR9710i7fybBs%3D&reserved=0>

What was the previous version of GLPI?
Did you also upgrade the MySQL application?
Have you also activated wincache?
Could you post the "information about system installation and configuration" section of the Setup > System tab? What is between the tags [code] and [/code]

Thank you,
Regards,
Tomolimo

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fglpi-project%2Fglpi%2Fissues%2F7140%23issuecomment-614632249&data=02%7C01%7Colivier.pithon%40recipharm.com%7C6b3aaee5cc524af8851a08d7e204bb77%7Caf1d2833a47b4ad187d8fe0a82ba7957%7C1%7C0%7C637226382267067028&sdata=C8P59wV52RvgEd1d7gz0Z9KfheMOdALl1Hu33nPuYqw%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIDBZBFMDMXFC2IYNKWOQRDRM35I7ANCNFSM4MIMDTXQ&data=02%7C01%7Colivier.pithon%40recipharm.com%7C6b3aaee5cc524af8851a08d7e204bb77%7Caf1d2833a47b4ad187d8fe0a82ba7957%7C1%7C0%7C637226382267067028&sdata=pusQc3NFDBuPKRS7Taw8ajkAZSlNOOJeDyptTwVCJyc%3D&reserved=0>.

________________________________

Recipharm Legal Notice:

The information transmitted may contain confidential material and
is intended only for the person or entity to which it is
addressed. Any review, retransmission, dissemination or other
use of, or taking of any action by persons or entities other than
the intended recipient is prohibited. If you are not the
intended recipient, please delete the information from your
system and contact the sender.
