### ISSUE TITLE
"Remember me" option not working if use 2 pc's or more: cookie not valid

### ISSUE THREAD

**Issue by bintocher** [glpi-project/glpi#7150]
**Describe the bug**

same error here : https://github.com/glpi-project/glpi/issues/5751

but i use GLPI 9.4.5

The "remember me" option is set to 60 days in configuration.

After login on 2 pc's one session auth will lost. 

user is forced to re-login with a message : Error : cookie not valid.

**Steps to reproduce the behavior:**

- Go to setup and activate auto-login
- use first pc to logon
- use another pc to logon
- the first pc does error, while try open any page in glpi
Error message : invalid data on cookie.

**Expected behavior**

Auto-login should respect is behavior.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.4.5 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux glpi.pelican.local 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 PHP 7.4.1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, ctype, 	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, 	openssl, pcre, pdo_mysql, pdo_sqlite, session, sockets, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, 	zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="256M" safe_mode="" session.save_handler="files" 	upload_max_filesize="256M"  Software: Apache/2.4.6 (CentOS) PHP/7.4.1 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 YaBrowser/20.3.2.238 Yowser/2.5 Yptp/1.23 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.4.12-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.4.12) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration. SELinux mode is Disabled

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.2 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.2.26 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src) phpCas version 1.3.8 in (/usr/share/pear)

Plugins:

barcode              Name: Barcode                        Version: 2.4.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+2.3    State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled 	telegrambot          Name: TelegramBot                    Version: 2.0.0      State: Not activated 	reports              Name: Отчеты                         Version: 1.13.1     State: Enabled 	dashboard            Name: Панель отчетов              Version: 0.9.8      State: Enabled 	behaviors            Name: Поведения                      Version: 2.2.2      State: Enabled 	archires             Name: Сетевые архитектуры    Version: 2.7.0      State: Enabled 	timelineticket       Name: Сроки заявок                  Version: 9.4+1.0    State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

I confirm this behaviour which had been introduced in GLPI 9.4.1. Since this version, in order to improve security, the token is recreated when user logs in. As there is, for now, only one value stored in database for this `remember me` token, it automatically invalidates thoose stored in other devices.

Storing multiple tokens to permit to use this feature on multiple devices could be interesting for many people. If you want to sponsor this enhancement, feel free to contact us at contact@teclib.com.

Regards
