### ISSUE TITLE
are receivers limited to 50 ?

### ISSUE THREAD

**Issue by vrocheUP** [glpi-project/glpi#7157]
Hi all,
I have a 9.4.4 GLPI installation, with 50 active receivers configured, all working perfectly.
If I add a new receiver (so creating the 51th receiver) the mailgate automatic action is not working anymore and all mails are blocked in all the mailboxes.
If I deactivate one of the previously working receiver (so I have only 50 active receivers), everything works like a charm, including the 51th receiver. That's really annoying. Any idea ?

Sincerely,
Valery

**Comment by trasher** [comment]
Hi,

Using 50 or more mail collectors is not really a standard usage; and it seems you've reached a limit.

This kind of need is not relevant for community support; please rely on professional services (like https://services.glpi-network.com/).

Regards.

**Comment by vrocheUP** [comment]
Hi,
Your answer can't be a serious answer. What is standard usage according to you ?
What is implied by your answer is that there is no real limit (we all know how a foreach loop works), but only a marketing limit.  

I'm sorry but your answer makes me feel angry.

Regards

**Comment by trasher** [comment]
There are no known limits  on that point, this case has never been reached before as far as I know, but we will not spend time on such specific case. 
You can also get that fixed by yourself and open a PR, you know how a loop works.

Regards.

**Comment by cedric-anne** [comment]
Hi,

I quickly took a look at the code and there is no SQL or loop limit. So you should at least provide some logs to help us investigate. Maybe it is due to something else than a limit on `50` items.

Regards
