### ISSUE TITLE
[9.4.5] API: first call with a new token-session always fail and redirect to auth page

### ISSUE THREAD

**Issue by rk4an** [glpi-project/glpi#7161]
**Describe the bug**

API: first call with a new token-session always fail and redirect to auth page

**To reproduce**

curl --location --request GET 'https://xxx/apirest.php/initSession/' \
--header 'Content-Type: application/json' \
--header 'App-Token: zzz' \
--header 'Authorization: Basic xxx'

I get a new-token-session yyy

curl --location --request GET 'https://xxx/apirest.php/search/Entity?uid_cols=1&withindexes=1' \
--header 'Session-Token: yyy' \
--header 'App-Token: zzz'

First call redirect me, other call works

**Expected behavior**

The API should respond with correct information the first time and not redirect to auth page

**Logs**

```
no log
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.5
```

**Additional context**

**Comment by rk4an** [comment]
Problem found: it was the "my_dashboard" plugin. Thanks

**Comment by trasher** [comment]
Maybe see https://github.com/InfotelGLPI/mydashboard/issues/75
