### ISSUE TITLE
Global search issue with cyrillic letters

### ISSUE THREAD

**Issue by antsharapov** [glpi-project/glpi#719]
This error is only when I made a search in cyrillic.

`
error in sql_errors.log
....
OR`glpi_tickets`.`due_date`LIKE \'%ИБП%\'    OR`glpi_tickets`.`solvedate`LIKE \'%ИБП%\'    OR`glpi_tickets`.`date_mo
d`LIKE \'%ИБП%\'   )  ) GROUP BY`glpi_tickets`.`id`ORDER BY ITEM_11 DESC
  Error: Illegal mix of collations for operation 'like'
  Backtrace :
  inc/search.class.php:903
  inc/search.class.php:98                            Search::constructDatas()
  front/search.php:65                                Search::showList()`

**Comment by antsharapov** [comment]
GLPI 0.90.3 ( => /usr/share/glpi)

Server
 
Operating system: Linux sd-glpi.basel.aero.local 3.16.0-71-generic #92~14.04.1-Ubuntu SMP Thu May 12 23:31:46 UTC 2016 x86_64
PHP 5.5.9-1ubuntu4.17 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="-1" post_max_size="30M" safe_mode="" session.save_handler="files"
	upload_max_filesize="30M" 
Software: Apache/2.4.7 (Ubuntu) (Apache/2.4.7 (Ubuntu) Server at sd-glpi.basel.aero.local Port 80)
	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.5.49-0ubuntu0.14.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket
	
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
OK/usr/share/glpi/files/_log : OK

Libraries
 
htmLawed version 1.1.21 in (/usr/share/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/usr/share/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/usr/share/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/usr/share/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/usr/share/glpi/lib/Zend)
SimplePie version 1.3.1 in (/usr/share/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/usr/share/glpi/lib/tcpdf)
ircmaxell/password-compat in (/usr/share/glpi/lib/password_compat). Compatitility: Ok

**Comment by yllen** [comment]
Can you try a search without display columns containing a date?

**Comment by antsharapov** [comment]
It's not a full listing of an error, I can't put it all cause github makes it unreadable. But it's not the date field problem. It's a problem of a 'LIKE' statement and a russian chars. I believe it should be done something like this:
CONVERT(field USING 'utf-8') LIKE 'search_string'

**Comment by orthagh** [comment]
i close this issue in favor of the new one: #1169
