### ISSUE TITLE
GLPI Ticket Map Location Blank

### ISSUE THREAD

**Issue by sworlls** [glpi-project/glpi#7190]
Hello everyone, good night.
Sorry if i am creating the question on wrong location, i am new here and i am looking for some help about map within GLPI to show tickets by locataion on MAP.

I had selected the tickets what i want to show into the map and then i clicked into the globe next to the trashbin but it always show blank page as you can see attached printscreen.

The entities are configured with lonngitude and latitude accordingly to the map set but anyway it does not show the map.

can you give me some help on this issue?
thank you and have a great night.
![Map Not Working](https://user-images.githubusercontent.com/45639833/80558452-d0e2df00-89b0-11ea-872a-288e7fc746c8.png)

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support, only issues should be reported here.
