### ISSUE TITLE
"Processing ticket" Section don't work

### ISSUE THREAD

**Issue by Saber119** [glpi-project/glpi#720]
Hi guys,

I have updated glpi to 0.90.3 on a Ubuntu server 16.04. Everything is perfect except the "processing ticket" Section for adding tasks or manual followups. I have tried to access from plenty computer with various OS (Ubuntu, Mac and Windows 10 and 8.1) and i have installed glpi on some virtual machine to test and it's always the same issue.
Here is a capture of the issue:
![capture](https://cloud.githubusercontent.com/assets/19840947/15936204/574eb3a0-2e27-11e6-97cd-07dd1607c828.PNG)

Thanks a lot guys

**Comment by tomolimo** [comment]
Hello 
Could you please look into the log files and report back any error you can find?
Thank you 
Regards 
Tomolimo

**Comment by Saber119** [comment]
I've got this :

[Thu Jun 09 09:28:04.120096 2016] [:error] [pid 33616] [client ::1:56674] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/glpi/inc/dbmysql.class.php:280\nStack trace:\n#0 /var/www/glpi/inc/ticket.class.php(6556): DBmysql->fetch_assoc(false)\n#1 /var/www/glpi/inc/ticket.class.php(6244): Ticket->getTicketActors()\n#2 /var/www/glpi/inc/ticket.class.php(606): Ticket->showTimeline(2017548465)\n#3 /var/www/glpi/inc/commonglpi.class.php(469): Ticket::displayTabContentForItem(Object(Ticket), '1', '')\n#4 /var/www/glpi/ajax/common.tabs.php(91): CommonGLPI::displayStandardTab(Object(Ticket), 'Ticket$1', '', Array)\n#5 {main}\n  thrown in /var/www/glpi/inc/dbmysql.class.php on line 280, referer: http://localhost/front/ticket.form.php?id=1
[Thu Jun 09 09:36:06.296773 2016] [:error] [pid 33593] [client ::1:56750] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/glpi/inc/dbmysql.class.php:280\nStack trace:\n#0 /var/www/glpi/inc/ticket.class.php(6556): DBmysql->fetch_assoc(false)\n#1 /var/www/glpi/inc/ticket.class.php(6244): Ticket->getTicketActors()\n#2 /var/www/glpi/inc/ticket.class.php(606): Ticket->showTimeline(113321865)\n#3 /var/www/glpi/inc/commonglpi.class.php(469): Ticket::displayTabContentForItem(Object(Ticket), '1', '')\n#4 /var/www/glpi/ajax/common.tabs.php(91): CommonGLPI::displayStandardTab(Object(Ticket), 'Ticket$1', '', Array)\n#5 {main}\n  thrown in /var/www/glpi/inc/dbmysql.class.php on line 280, referer: http://localhost/front/ticket.form.php?id=1
[Thu Jun 09 09:38:30.896298 2016] [:error] [pid 33615] [client ::1:56758] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on boolean in /var/www/glpi/inc/dbmysql.class.php:280\nStack trace:\n#0 /var/www/glpi/inc/ticket.class.php(6556): DBmysql->fetch_assoc(false)\n#1 /var/www/glpi/inc/ticket.class.php(6244): Ticket->getTicketActors()\n#2 /var/www/glpi/inc/ticket.class.php(606): Ticket->showTimeline(934438794)\n#3 /var/www/glpi/inc/commonglpi.class.php(469): Ticket::displayTabContentForItem(Object(Ticket), '1', '')\n#4 /var/www/glpi/ajax/common.tabs.php(91): CommonGLPI::displayStandardTab(Object(Ticket), 'Ticket$1', '', Array)\n#5 {main}\n  thrown in /var/www/glpi/inc/dbmysql.class.php on line 280, referer: http://localhost/front/ticket.form.php?id=1

**Comment by tomolimo** [comment]
Seems like your DB is not in the right format. 
Before this did you do an upgrade?

**Comment by Saber119** [comment]
Upgrading the Database ? well i did everything from scratch and the database was created by the install.php 
if else what upgrade can i do
System info :
Ubuntu server 16.04 64bit
Mysql Server 5.7
PHP 7.0
Apache 2

**Comment by tomolimo** [comment]
So to be clear: your DB is empty?

**Comment by Saber119** [comment]
yes, if you want i can send you the whole sql file of my database

**Comment by Saber119** [comment]
[glpi.txt](https://github.com/glpi-project/glpi/files/307594/glpi.txt)

**Comment by tomolimo** [comment]
I'll check it tomorrow morning

**Comment by tomolimo** [comment]
To be clearer:
What version of PHP do you use? I know 7.0, but 7.0.?
Same question for mySQL: 5.7.?
Me I'm using on my dev server PHP 7.0.3 and mySQL 5.7.11

What was your the previous version of GLPi? you said that you've done an update of GLPi 

> Hi guys,
>
> I have **updated** glpi to 0.90.3 on a Ubuntu server 16.04. Everything is perfect except the "processing ticket" Section for adding tasks or manual followups. I have tried to access from plenty computer with various OS (Ubuntu, Mac and Windows 10 and 8.1) and i have installed glpi on some virtual machine to test and it's always the same issue.

Thank you,

**Comment by yllen** [comment]
And give the exacts errors in glpi/files/_logs (php and sql-error.log)

**Comment by Saber119** [comment]
Regarding PHP, i'm using 7.0.4 and for mysql server i'm using 5.7.12.
you'll find down below the log files (php and mysql)


[php-errors.txt](https://github.com/glpi-project/glpi/files/309170/php-errors.txt)
[sql-errors.txt](https://github.com/glpi-project/glpi/files/309169/sql-errors.txt)

**Comment by Saber119** [comment]
i have tested the thing on a ubuntu 14.04.4 with php 5.5.9 and mysql server 5.5.49 and the "processing ticket" section is working fine.

**Comment by remicollet** [comment]
PHP is not compatible with MySQL 5.7, see #627 

You can try to disable strict_mode, no warranty

Closing as duplicate
