### ISSUE TITLE
Right for ticket task

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#7200]
I can create a task but i can't change it after creation.

**Comment by trasher** [comment]
Waiting for feedback on PR

**Comment by yllen** [comment]
I don't see feedback needed in my PR

**Comment by cedric-anne** [comment]
See comments on #7201.

**Comment by yllen** [comment]
Yes i thing you missing something because if you are not the author of the task you don't have the icon to edit it.
My PR, added just the button to save change like displayed in copy under past

![Capture d’écran de 2020-07-20 19-54-58](https://user-images.githubusercontent.com/12936722/87969934-4d262380-cac3-11ea-9035-f6c71c8cf16c.png)

**Comment by cedric-anne** [comment]
Hi,

Can you be more precise on steps to reproduce ?

I cannot find a case where I have no edit icon when I have rights to update a task.

Regards
