### ISSUE TITLE
glpi 9.1 installation  computer error 500

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#721]
Hello

I have installed 9.1 for test before migration. 

All seems to be ok except when I open a computer I obtain error 500.

no matter which one I select

Thank you for your help

PS: with same setup on 0.91 it works without problem

windows 2012r2 / IIS 8.5 / php 7.04 / mariadb 10.1.

**Comment by tomolimo** [comment]
Did you upgrade from 0.91 or from 0.90?

**Comment by satyan01** [comment]
from 0.91

**Comment by tomolimo** [comment]
Hello,
What you must understand is that GLPi 0.91 has never been an official release of GLPi, and that you are currently working with the 'master' branch, and the 'master' branch is not and will never be a stable release by itself.

Then to fix your problem you must redo a correct upgrade as the GLPi source code doesn't include an upgrade path from 0.91 to 9.1 (as 0.91 has never been an official release).

To do that, you have 2 solutions:

1. is to re-play an upgrade from your last productive GLPi database. I mean if your last productive GLPi is 0.85, then you must redo the upgrade from this 0.85 release. **This method is the official method to upgrade and the only one supported by the team**.
1. just change the version of GLPi in DB and restart an upgrade (**Beware that this method is not supported at all: it's at your own risk**). To change the version, update the record with id=1 in glpi_configs: set it to 0.90.2 (`UPDATE glpi_configs SET value='0.90.2' WHERE id=1;`), then restart your browser with GLPi URL like http://your_glpi_domain/.

regards,
Tomolimo

**Comment by satyan01** [comment]
Ok I will do it and come back to you. Thank you for your great Help

**Comment by satyan01** [comment]
installation works with your procedure so I am in 9.1 but I have the same problem to send notification

**Comment by tomolimo** [comment]
Then close this post
