### ISSUE TITLE
glpi 9.1 send mail impossible - Add options for PHP Mailer

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#722]
After many tests it is impossible to send a message,

Administrator test neither

Élément modifié avec succès : retro Ticket for restarting Gain Services during main chain moitoring 
Erreur dans l'envoi du courriel
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troublesho

**Comment by tomolimo** [comment]
Is it with your newly upgraded GLPi?
If yes then it is linked to #721

**Comment by satyan01** [comment]
yes

**Comment by tomolimo** [comment]
Could you fix your upgrade first?
See #721 
Before posting other issues?
Thank you

**Comment by satyan01** [comment]
I think it is linked, and the install 9.1 is new, I have just copy my database and upgraded it

**Comment by yllen** [comment]
You can't connect with SSL if you use an auto-signed certificate.

GLPI must add options of PHP mailer in email configuration to allow or not usage of one or more options.

**Comment by satyan01** [comment]
I don't use auto signed certificate

**Comment by yllen** [comment]
It's not a problem with new GLPI version but with default parameter of version of PHP mailer.
You use certificate that can be verified: SSL routines:ssl3_get_server_certificate:certificate verify failed

**Comment by satyan01** [comment]
I had understood as well, but how can I solved this issue ?

**Comment by tomolimo** [comment]
You said:

> I think it is linked, and the install 9.1 is new, I have just copy my database and upgraded it

Juste one question: what was the database version before upgrade? Was it 0.91 or else?

**Comment by satyan01** [comment]
0.91 yes

**Comment by satyan01** [comment]
all work except send mail

**Comment by satyan01** [comment]
plugins as well and except computers error 500

**Comment by tomolimo** [comment]
then please, start by doing a correct migration path as explained here #721

**Comment by satyan01** [comment]
migration done but same issue

**Comment by orthagh** [comment]
See #760 for a fix
