### ISSUE TITLE
Reopen issues #593 & #589

### ISSUE THREAD

**Issue by lirmikey** [glpi-project/glpi#724]
I have to choose the dustbin twice to get it working directly after login in 0.90.3. Choosing it the first time produces queuedmail.php?is_deleted=0 in the address bar. The second time becomes queuedmail.php?is_deleted=1, which makes it work.

**Comment by orthagh** [comment]
pager and dustbin problem is already fixed for 0.90/bugfixes and master branch.

No need for a new issue. 0.90.4 release will contains the bugfix for #589 and #593
