### ISSUE TITLE
Associated contracts search option in Suppliers not working correctly

### ISSUE THREAD

**Issue by yild** [glpi-project/glpi#7240]
Hello,
when selecting 'is' in 'Associated contracts' search option in 'Suppliers' list, only Dropdown::EMPTY_VALUE is visible (listed) in select box.

This issue is related to code:
https://github.com/glpi-project/glpi/blob/565dec5452552fa19bba1c179ce4c5c5f966af79/inc/contract.class.php#L1563-L1565

If there are (or can be) any items assigned to Contract there is no way to get contract to be visible in dropdown. Also 'nochecklimit' param is set to FALSE by default and there is no chance to pass this param set to TRUE in rawSearchOptionsToAdd function.

GLPI 9.4.5

**Comment by cedric-anne** [comment]
Hi,

I confirm there is something wrong here. Contracts that have reach their max linked items are not displayed.

Regards
