### ISSUE TITLE
you may want to update the copyright to 2020

### ISSUE THREAD

**Issue by maarten-boot** [glpi-project/glpi#7241]
**Describe the bug**

GLPI 9.4.6 Copyright (C) 2015-2019 Teclib' and contributors

as 9.4.6 came out in 2020 i expect that should become

GLPI 9.4.6 Copyright (C) 2015-2020 Teclib' and contributors

**To reproduce**

login and look at the bottom right  ;-)

**Expected behavior**

GLPI 9.4.6 Copyright (C) 2015-2020 Teclib' and contributors

**Screenshots**

![image](https://user-images.githubusercontent.com/11140490/81202733-4c531a80-8fc7-11ea-9eec-8335cef39dde.png)

**Comment by trasher** [comment]
See https://github.com/glpi-project/glpi/commit/6323657feda958207ba78e71462bff6c43e2e31c
