### ISSUE TITLE
Information is missing when you transform a task in a project into a ticket.

### ISSUE THREAD

**Issue by picinformatique** [glpi-project/glpi#7252]
In the project tool when you transform a task of a project into a ticket, there is only the title of the task which is retrieved and inserted in the title of the ticket and the description (content) of the ticket.

The start and end dates, the entity, and the description are not included when the ticket is created.

**Exemple :** 
https://demo.glpi-project.org/front/ticket.form.php?_projecttasks_id=5

**Steps to reproduce the behavior:**

1. Go to 'tools/Project'
2. Click on "+" to create a project
3. Go in project
4. Create task on project with description
5. Create a ticket from the task
6. we can see that only the task title is retrieved and inserted in the title and description

At the very least, I would like the description to be retrieved. is it possible to modify a php file to adapt this?

**Screenshots**

![Capture](https://user-images.githubusercontent.com/65170526/81565506-bc7fe880-9399-11ea-95ac-cebef1f68ed2.PNG)

![Capture1](https://user-images.githubusercontent.com/65170526/81565522-c1dd3300-9399-11ea-8ffb-c64a82259c5f.PNG)

![Capture2](https://user-images.githubusercontent.com/65170526/81565529-c6095080-9399-11ea-9bd6-221554aac79c.PNG)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.3.0 ( => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux glpi 4.4.0-171-generic #200-Ubuntu SMP Tue Dec 3 11:04:55 UTC 2019 x86_64 PHP 7.0.33-0ubuntu0.16.04.14 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, standard, sysvmsg, sysvsem, 	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="300" memory_limit="1024M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at glpi.picinformatique.com Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.30-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: root@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed Database version seems correct (5.7.30) - Perfect! /var/www/html/glpi/config : OK /var/www/html/glpi/files : OK /var/www/html/glpi/files/_dumps : OK /var/www/html/glpi/files/_sessions : OK /var/www/html/glpi/files/_cron : OK /var/www/html/glpi/files/_graphs : OK /var/www/html/glpi/files/_lock : OK /var/www/html/glpi/files/_plugins : OK /var/www/html/glpi/files/_tmp : OK /var/www/html/glpi/files/_cache : OK /var/www/html/glpi/files/_rss : OK /var/www/html/glpi/files/_uploads : OK /var/www/html/glpi/files/_pictures : OK /var/www/html/glpi/files/_log : OK

**Comment by trasher** [comment]
9.3 is no longer maintained. Please try with 9.4.6 and reopen ticket if problem persists.
