### ISSUE TITLE
PHP 7.1 compatibility

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#726]
Bug tracker.

GLPI already works correctly with 7.1.0alpha1, but some new notices are raised, need to be fixed

See
- 25f02addabbb727cda7bb48a2c1185edb06373f5
- 39fffe0a69532689f918e4f5e74f17764c777d98
- 6dd7c3ae2a3d1866c1fd1e45a32170af5d51c97b

Probably more to come.

**Comment by trasher** [comment]
As far as I can say... GLPI is now fully compatible with php 7.1 (and probably 7.2 as well) ;)
