### ISSUE TITLE
GLPI 0.90.3: Add technicien to a ticket: suggestion doesn't work

### ISSUE THREAD

**Issue by cdlabal** [glpi-project/glpi#728]
When writing first caracteres of name of Technicien in the field "Assigned to", there is no suggestion made. The search bar disappear immediatly.
For exemple, writing "tec", the system should propose "technicien".
It works fine for Requester and Watcher fields.

![search](https://cloud.githubusercontent.com/assets/14885971/16011075/440038d6-3184-11e6-8240-21f3666dd505.jpg)

Thanks

**Comment by ladenree76000** [comment]
do some technicians have a valid profile in this current ticket entity ?

**Comment by cdlabal** [comment]
Yes of course. All techniciens appears in the list.
The problem concerned the search bar in the field.

**Comment by yllen** [comment]
Because you have less technicians than define in the global setup:
In Setup > Genral > field "Don't show search engine in dropdowns if the number of items is less than"

**Comment by cdlabal** [comment]
Great!!!
Thank you yllen!
