### ISSUE TITLE
Global Assets displays zero results

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#7286]
**Describe the bug**
Since upgrading to GLPI v9.4.6 (from v9.4.5) our global assets list no longer works. When choosing to view Global Assets from the menu, the list appears with no entries.

**Page(s) URL**
https://helpdesk.hayley-group.local/front/allassets.php

**To reproduce**
Just browse to Global Assets

**Expected behavior**
A list of all assets should appear as it has done in previous versions of GLPI.

**Screenshots**
![image](https://user-images.githubusercontent.com/16598973/82333943-3f7af180-99df-11ea-8595-0d1aeb0b22cd.png)

**Additional context**
We see the following Apache error when accessing the broken page:
`
[Tue May 19 14:40:23 2020] [error] [client 10.11.9.202] PHP Fatal error:  Uncaught Error: Call to a member function isEntityAssign() on null in /usr/share/glpi/inc/search.class.php:3292\nStack trace:\n#0 /usr/share/glpi/inc/search.class.php(428): Search::addDefaultToView('AllAssets', Array)\n#1 /usr/share/glpi/inc/search.class.php(96): Search::prepareDatasForSearch('AllAssets', Array)\n#2 /usr/share/glpi/inc/search.class.php(80): Search::showList('AllAssets', Array)\n#3 /usr/share/glpi/front/allassets.php(45): Search::show('AllAssets')\n#4 {main}\n  thrown in /usr/share/glpi/inc/search.class.php on line 3292, referer: https://helpdesk.hayley-group.local/front/central.php
`

The error occurs even after disabling all plugins.

Any help in fixing would be greatly appreciated :)

**Comment by orthagh** [comment]
Hello @hgpit, please check above fix.

**Comment by hgpit** [comment]
Thanks for the fix :)
