### ISSUE TITLE
Login unsuccessful for GLPI user [9.4.5]

### ISSUE THREAD

**Issue by 7uppi** [glpi-project/glpi#7287]
Hello.

I have a GLPI instance running, where I haven't touched it for a while.
Then when I tried to login to my admin account, it didn't have the administrative rights anymore.
I then proceeded to try and login to the GLPI user (This is not disabled), but here I just get told I use the wrong password.

Confused about this, I proceeded to look at how to reset the password for the GLPI user in the database, and I have found these two up until now:
https://forum.glpi-project.org/viewtopic.php?id=12725
https://techexpert.tips/glpi/glpi-password-recovery/

Neither of these have worked out for me, and I am now a little stuck.
I need to get back into the server, but I am a bit lost on how.
Any help is very appreciated.

Thanks.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
