### ISSUE TITLE
Assigned to Ticket and assigned to TicketTask

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#729]
Hello,
I suggest to add a right for being in charge of a task. This means that one person can have the right to be in charge of tasks but not being in charge of tickets. 

The need behind is that we need to assign tasks to requesters that are not ticket technicians but are 'post-only'. Use-case: assign a task to a requester which asks him to do something and to report as 'done' when done.

Of course I will push this code to repo.

What do you think about that?

Thank you
Regards,
Tomolimo

**Comment by yllen** [comment]
i think your must is linked with https://github.com/glpi-project/glpi/issues/690.

We must review all right for tasks
