### ISSUE TITLE
[9.4.6] Issue with time display

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#7291]
Hello,

The time for tracking tickets is truncated in the display on the right panel (left panel is ok) :

![Capture](https://user-images.githubusercontent.com/55700796/82362565-cbefd900-9a0c-11ea-91c5-42cc27a76415.PNG)

The browser used is firefox 76.0.1, this is not reproduced when zooming (ex: 110% no problem) 
And when we revert to 100% it is truncated.

With Chrome and Edge no problems.

**Comment by cedric-anne** [comment]
Hi,

Can you provide a more descriptive context ? Like a page URL or a more global screenshot ? I did not find where this informations is displayed.

Regards

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by kevin-m87** [comment]
![image](https://user-images.githubusercontent.com/55700796/85116022-f526a380-b21c-11ea-800c-483216331b71.png)

**Comment by cedric-anne** [comment]
Hi,

I cannor reproduce but rendering may depend on fonts rendering. Can you try with #7501 ? You'll have to use debug mode to see if fix is working.

Regards

**Comment by kevin-m87** [comment]
Hi,

I setting to change file css/styles.scss  with max-width: 145px;

This issue is only with firefox.

**Comment by cedric-anne** [comment]
Hi,

Did you check using debug mode ? Did you try to empty browser cache ?

Regards

**Comment by kevin-m87** [comment]
Hi,

Yes for both.
