### ISSUE TITLE
Add option: Aleatory assign to technician with fewer tickets

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#73]
Original request found on Linkedin : https://www.linkedin.com/grp/post/84619-6038349977007198212

One more time, I'm installing GLPI and the project managers want GLPI with automatic assignament of ticket with feature "assign ticket to technician with fewer opened tickets ".

**Comment by lexx015** [comment]
Hi!
In this case ticket should be assigned only to the group or technician who is response for a ticket.

**Comment by zorianny** [comment]
Hi,
It also can be partially solved by a SLA, eg. criteria="category is X" and action="assign group Y", then the tickets with category X is assigned to the group Y; this ticket can be automatically assigned to a technician with the action "add technician" in a SLA.

It would be excellent a SLA to assign the technician of the group with fewer open tickets.

**Comment by arthurrschaefer** [comment]
GLPI already reads how many tickets a technician is processing at the moment of Create a ticket (Default Interface). Maybe it could be great to have in future releases!!

**Comment by yllen** [comment]
What do you mean by "Opened tickets"? All tickets not solved? Even tickets in Waiting status?

**Comment by zorianny** [comment]
No, I'm just taking into account tickets in Processing(assigned) status because the tickets in Waiting status is due to a specific thing

**Comment by seymos** [comment]
Hello,
As a user of GLPI, I find it's a great idea!

But in this case we must manage planning in GLPI and that system into account.

For example, if a technician to a job ticket / problem / project / Change Plan, we need to pass along. And if it were all some thing Plan, return to longer available.
Indicate absences / vacation / leave / disease for new tickets are not associated with an absent technician.

Consideration should be given in case a technician already a ticket for the same user to group requests / incidents / problem / change a single technician or group.


I feel that that's a lot!
