### ISSUE TITLE
[0.90.3] Fixed Footer CSS

### ISSUE THREAD

**Issue by thiagopassamani** [glpi-project/glpi#730]
Add in file glpi/css/style.css for fixed footer:

#footer {
   font-size: 9px;	
   color: #000;
   background-color: #E2E1DE;
   padding: 6px;
   height: 18px;
   padding: 5px;
   /* CUSTOM */
   position: fixed;
   bottom: 0;
   right: 0;
   width: 99%;
   z-index: 1500;
}

![2016-06-14_11-00-57](https://cloud.githubusercontent.com/assets/5321107/16045550/52c6739e-321f-11e6-9b39-63da49ba4753.png)

**Comment by yllen** [comment]
Since 0.90.3 each palette has a specific CSS file.
So your post can solve only 1 palette if put in glpi/css/palettes/classic.css

**Comment by orthagh** [comment]
Hello @thiagopassamani 

Thank you for your suggestion and your contribution ( #738 ).
I think the footer element contains only minor informations and should not be displayed always in default layout.

However, the "splitted" layout (available in config and user preferences) already have this fixed footer as all the page is contains in the full height of the page body.

So, I refuse the issue (and the corresponding PR).
Anyway, feel free to comment this issue.
You can also propose a suggestion on the [dedicated site](http://suggest.glpi-project.org)
