### ISSUE TITLE
[9.5] Impact analysis - problem with linked tickets

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7301]
On my cmdb plugin, i display for example a server.

When i click on linked ticket

![image](https://user-images.githubusercontent.com/13178158/82466247-7117b980-9ac0-11ea-8e9a-068775e332a3.png)

i am redirected to http://localhost/glpi95/plugins/xxx/front/ticket.form.php?id=64945

& not to http://localhost/glpi95/front/ticket.form.php?id=64945

in impact.js you do not use root_doc parameter : 

```
listElements: function(title, elements, url) {
      var html = "";

      if (elements.length > 0) {
         html += "<h3>" + title + "</h3>";
         html += "<ul>";

         elements.forEach(function(element) {
            var link = "./" + url + ".form.php?id=" + element.id;
            html += '<li><a target="_blank" href="' + link + '">' + element.name
               + '</a></li>';
         });
         html += "</ul>";
      }

      return html;
   },
```

**Comment by cedric-anne** [comment]
Hi @tsmr ,

Can you check if #7450 fixes your issue ?

Regards
