### ISSUE TITLE
Wrong/default language when using 'Other authentication send in the HTTP request'

### ISSUE THREAD

**Issue by Nevets82** [glpi-project/glpi#7302]
**Describe the bug**

I am currently using 'Other authentication send in the HTTP request' to authenticate GLPI users. This works perfectly except for the user's language. This is because the locale in the *OIDC_CLAIM_locale* HTTP request header is using a hyphen instead of an underscore (**fr-FR** instead of **fr_FR**).

**Page(s) URL**

https://demo.glpi-project.org/front/auth.others.php

**Expected behavior**

Add support for a hyphen in the **$lang** parameter of [getLanguage](https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/config.class.php#L2020) function in [config.class.php](https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/config.class.php).

Alternatively modify the parameter before calling  [getLanguage](https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/user.class.php#L1865) function in [user.class.php](https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/user.class.php).

**Relevant Source Files**

https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/user.class.php#L1865
https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/config.class.php#L2020
https://github.com/glpi-project/glpi/blob/9.4/bugfixes/tests/functionnal/Config.php#L497

**Screenshots**

![image](https://user-images.githubusercontent.com/4462739/82577104-cc15e300-9b8a-11ea-89a7-9a3eba2e606c.png)

**Additional context**

I am currently using [Identity Server 4](https://identityserver.io/)  and Apache 2 [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) to authenticate GLPI users.

**Comment by RodrigueAnge** [comment]
Hi

Please, help me.
I want to do the same thing with GLPI : Other Authentication in HTTP Request.
I have a website where users can log and i want to automatically log them in GLPI without typing again credentials.
Please, Give me a sample code in PHP

Thank You !

**Comment by cedric-anne** [comment]
@RodrigueAnge 

To get community support, please use [forum](https://forum.glpi-project.org/).

If you want to get professionnal support, you may consider taking a [subscription](https://glpi-project.org/subscriptions/) or [contact GLPI editor team](https://portal.glpi-network.com/contact-us) directly.

**Comment by RodrigueAnge** [comment]
Okay
Thank You, I really appreciate your help.



Le mar. 15 févr. 2022 à 10:22, Cédric Anne ***@***.***> a
écrit :
