### ISSUE TITLE
PHPDoc corrections

### ISSUE THREAD

**Issue by nbriche** [glpi-project/glpi#7308]
Many PHPDoc blocks are currently not using the [current GLPI coding standards](https://glpi-developer-documentation.readthedocs.io/en/master/codingstandards.html#comments), or even the basic PHPDoc syntax.

This means that IDEs (in my case PHPStorm) are often confused about parameter and return types, missing tags and more. So many warnings are on display that genuine errors and warnings are missed in the flood.

I am currently correcting as much doc blocks as I can, but I would like some guidance as to which branch(es) I should PR these corrections towards: master? 9.4/bugfixes? Both?

**Comment by cedric-anne** [comment]
Hi,

We know that invalid PHPDoc blocks can be a real pain when using IDEs that based their code analysis on them.

We already worked on fixing some of them, but it is a painful job, as much for the one who fixes them as for them who have to validate the pull request. So, if you want to work on this, please try to split the job into medium-sized PR and focus on important changes.

You should target 9.5/bugfixes branch, which contains the next major version of GLPI.

Regards

**Comment by nbriche** [comment]
Perfect. What would constitute a "medium-sized" PR?

**Comment by cedric-anne** [comment]
More or less 250 lines of doc updated.
