### ISSUE TITLE
GLPI - Problem adding form answer to a ticket

### ISSUE THREAD

**Issue by unitglpi** [glpi-project/glpi#7322]
We have a problem adding a form answer to a ticket:
In the drop-down list there's a list of form answers, but only the name is shown, so we can't distinguish a answer from a day, from one that occurred on a different day
There is some way to configure this drop-down menu:
- To display the form name and form ID? Or the date when the form was created?
- To show values sorted by date of creation?

Actualy, the values are not sorted by name, because we have seen that the most recent form answer do not come out at the end, but rather in the middle of the list of values. Is that normal? In what order does the list of default values come out, in the case of the form answers?

Attached image:

![Captura](https://user-images.githubusercontent.com/66062763/83125146-63bd8900-a0d7-11ea-8193-0fa6cef623e3.JPG)

Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps:

* We don't support community plugins. Contact directly their authors, or use the community forum : https://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (https://suggest.glpi-project.org). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (https://forum.glpi-project.org) is the best place.
* Please use the below template.

For more informations, please check contributing guide:
https://github.com/glpi-project/glpi/blob/master/CONTRIBUTING.md

The GLPI team.
-->

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by unitglpi** [comment]
My GLPI version:

GLPI: version 9.4.2
Forms Creator plugin: version 2.8.3

**Comment by trasher** [comment]
Seems related to formcreator plugin, not to GLPI.
