### ISSUE TITLE
GLPI-9.4.6 Problem with Knowledge base when user profil is self-service

### ISSUE THREAD

**Issue by Alexis-Damien** [glpi-project/glpi#7324]
On GLPI-9.4.6 there is a problem with Knowledge base when user profile is "self-service" with simple profile the menu does not appear on the left side.

**Comment by Alexis-Damien** [comment]
The problem appear (no menu) when we select an entry of the knowledge base.

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by Alexis-Damien** [comment]
I join an example with a screen copy.

![image](https://user-images.githubusercontent.com/45090274/83846142-6f7a0280-a70a-11ea-8f9b-f63cd409181a.png)

Thank you

**Comment by cedric-anne** [comment]
Hi,

Maybe I am wrong, as I do not know well this part, but it seems that it has not changed from a while.

If you want to sponsor UX enhancement on this part, feel free to contact us at contact@teclib.com.

As it does not seems to be a bug, I close this issue. You can open a topic to discuss with community about enhancements on [suggestion website](https://glpi.userecho.com/).

Regards
