### ISSUE TITLE
Upgrade from 9.1.7 to 9.4.6

### ISSUE THREAD

**Issue by rihemben** [glpi-project/glpi#7325]
Unable to perform upgrade of production database from 9.1.7 to 9.4.6
i have tried all combination starting the upgarde step by step from version  9.2 to 9.2.1 to 9.2.4.
But when upgrading to 9.3 i faced this problem

![glpi_upgrade](https://user-images.githubusercontent.com/17871571/83263460-e8cf9d80-a1be-11ea-8535-ad1bc09fe35a.PNG)

**Comment by cedric-anne** [comment]
Hi,

Creation of missing column should be done during upgrade from 9.1 to 9.2.
Please retry the migration process from the begining. If you need support, please ask on community forums https://forum.glpi-project.org/ .

Regards
