### ISSUE TITLE
GLPI 9.4.6 - Global search doesn't work.

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#7326]
Dear GLPI Team!
After upgrading to 9.4.6 version I've faced with an follow issue in Assets -> Global Search.
![glpi946 global search error](https://user-images.githubusercontent.com/20252855/83281107-445e5300-a1e0-11ea-8b8d-75a36911a51e.jpg)

This error I appears on debug mode. 
In normally mode Global search doesn't work at all.
![glpi946 global search normally](https://user-images.githubusercontent.com/20252855/83281707-2a714000-a1e1-11ea-88e5-bfea83949c39.jpg)

That code:
![search_class_php_on_line_3292](https://user-images.githubusercontent.com/20252855/83282287-05c99800-a1e2-11ea-9cfe-a78bc040064e.jpg)

changed to:
![search_class_php_on_line_3292_work](https://user-images.githubusercontent.com/20252855/83282437-41fcf880-a1e2-11ea-8747-2c4711108742.jpg)

Could you verify it please.
Thank you in advance.

**Comment by okvok** [comment]
In the method addDefaultToView of class Search in case of global searching the $item = null is  always because the $itemtype = 'AllAssets'. The $item never has opportunities to get another value except NULL. So why you trying call method $item->isEntityAssign() at row 3293? It will NEVER WORK ! 
That's why I commented that call.

**Comment by AdrienClairembault** [comment]
Thanks for your report, this was fixed a couple days ago in https://github.com/glpi-project/glpi/pull/7294.
