### ISSUE TITLE
Could not get DB lock - Problem with mailgate

### ISSUE THREAD

**Issue by PotterWayne** [glpi-project/glpi#7327]
Hi there,
Every time that mailgate runs, it stucks in running state. I can't get any error log, the only message I can see when this happes is in cron.log: Can't get DB lock (in spanish). We just identified that this happens when a mail have an attachment or a inline image. When the mail isn't have any attachment, is procesed normally.

1.  Make sure that in you receiver's inbox you have a mail with attachment or an inline image
2. Run to Setup > automatic actions > Mailgate  - Click in excute
3. The task keep stuck in running forever, and if you see the cron.log, it's shows Can't get DB lock several times, until we have to restart the apache service.

* 2: (You may do it in _Setup > Receivers > enter the receiver > Actions > Get email tickets now_ but it doesn't register any error log, it just keep loading forever)

**Expected behavior**

The mail with attachments should be register in the glpi system normally.

**Logs**
This is what is showed in cron.log:
```

Interno #1: Lanzar mailgate
2020-05-30 20:15:01 
No se puede realizar bloqueo de BD
2020-05-30 20:16:02 
No se puede realizar bloqueo de BD
2020-05-30 20:16:04 
No se puede realizar bloqueo de BD
2020-05-30 20:17:01 
No se puede realizar bloqueo de BD
2020-05-30 20:18:01 
No se puede realizar bloqueo de BD
2020-05-30 20:19:02 
No se puede realizar bloqueo de BD
```

**Screenshots**

![image](https://user-images.githubusercontent.com/37676029/83342760-cde15400-a2b8-11ea-9fe9-bc2f00c0830d.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

Information about system installation and configuration
--
[code]   GLPI 9.4.4 ( => /var/www/html/glpi) Installation mode: TARBALL


Server
--
Operating system: Linux thanos.dcsenati.dc.senati 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 PHP 7.2.24 apache2handler (Core, PDO, PDO_OCI, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mysqli, mysqlnd, oci8, openssl, pcre, pdo_mysql, pdo_sqlite, session, soap, sockets, sqlite3, standard, tokenizer, wddx, xml, 	xmlreader, xmlrpc, xmlwriter, xsl, zlib)
 Setup: max_execution_time="600" memory_limit="1028M" post_max_size="10M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  
Software: Apache () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36 
Server Software: MySQL Community Server (GPL) 
Server Version: 5.7.25 	Server SQL Mode:  	Parameters: glpi@localhost/glpi933 	Host info: Localhost via UNIX socket



```
![image](https://user-images.githubusercontent.com/37676029/83342996-d0dd4400-a2ba-11ea-9cbf-678b0a2499f9.png)

**Additional context**

This is the first time we starting to use mailgate. There's 13 recivers configurared, every 15 mins and 18 mails per task. I alredy check the database, all the glpi tables are migrated to innoDB; mailgate is configurated in CLI mode, debug mode doesn`t bring any errors. 

My actual version is 9.4.4. We've tested in a dev enviroment upgrading to 9.4.6 but the problem still happens. The mail service we are working with is Office 365. We have set memory_limit in php to 1028MB.

When we attach files manually, it works fine, even in tickets and follow ups.

Hope you can help me.
Regards.

**Comment by trasher** [comment]
I guess your tables are using the myisam engine; you should update to innodb.

**Comment by cedric-anne** [comment]
Hi,

`Can't get DB lock` is not related to DB engine. Actually, a lock (see https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html ) is put inside DB before each task execution and released just after execution. This does not lock database, it is just a kind of locking flag that is used by GLPI.
This lock should be released when DB connection that opens it is closed.

When you click on "run" for your task, you actually run it using apache. You should test it using command line, to be sure it will be executed in same context as it will be ran by GLPI (CLI mode = ran by crontab).

Can you tell us what is the result of the command `php -d error_reporting=E_ALL -d display_errors=on front/cron.php --force mailgate --debug && echo $?` ? If you get a `Can't get DB lock`, restart apache and run the command again.

Regards

**Comment by PotterWayne** [comment]
Hi!
I run the indicated process but it get stuck again throwing mailgate. I was testing with mail with attachments.

![image](https://user-images.githubusercontent.com/37676029/83952534-1a6be880-a7ff-11ea-9ba1-20609f0ff9e2.png)
I check the cron.log and get the same messages "Could not get DB lock".

![image](https://user-images.githubusercontent.com/37676029/83952538-2192f680-a7ff-11ea-8d7d-08f010706ab1.png)

Then I try with mails without attachtments and it worked normally. The issue with attachments still happens =/

anything else I could try? I tried running the comand with previously  setting setenforce  to 0  but get the same result.

Thanks.
Regards.

**Comment by cedric-anne** [comment]
Hi,

Your first screenshot does not show the return code. Also, with this command, logs should be directly display during command execution. Could you give us the full result of command execution ?

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot do anything without feedback.

Regards

**Comment by abnerrizzi** [comment]
I am facing the exame same issue on GLPI 9.4.3

**Comment by cedric-anne** [comment]
@abnerrizzi 

You should upgrade to a more recent version, and open a new issue if problem persist.
