### ISSUE TITLE
Issue with API Updates on Certain Fields

### ISSUE THREAD

**Issue by b1scuit-thi3f** [glpi-project/glpi#7352]
**Describe the bug**

Hi, 
I know you mention you do not support community plugins, which is fair enough, although I feel this is an issue with the RestAPI and so I am posting it here.
Yesterday I suddenly found I could not update fields for a computer asset that have been generated by the AddtionalFields plugin, but only through the API. If I use the GLPI GUI I can easily update the values. I have tested the API updating as a super user, so I don't believe it is a permissions issue. 

I can also update core fields (such as comment) fine at the same time, but the additional field doesn't change.

I have no idea what is going wrong, and there is no errors I can see that might point me in the right direction. I am hoping that you might have come across this issue before, or know what might be causing it. We have upgraded both GLPI to the latest version (from 9.4.5 to 9.4.6) and the plugin, and the issue persists. 

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

curl -X PATCH -H 'Content-Type: application/json' -H "Session-Token: REDACTED" -d '{"input": [{"id":4506,"lowfield":"50","comment":"50"}]}' 'https://***/glpi/apirest.php/Computer/' 

Returns
[{"4506":true,"message":""}]

**Expected behavior**

The field "low" should be updated, as well as comments, but only comments has changed. Changing both values work fine via the GUI.

**Logs**

from api.log
2020-06-02 12:25:25 [14@HOST NAME REDACTED]
Enpoint 'updateItems' called by IP REDACTED (USER ID REDACTED)

no errors around this timestamp are found in any of the logs files.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Linux HOST REDACTED 5.3.0-1019-aws #21~18.04.1-Ubuntu SMP Mon May 11 12:33:03 UTC 2020 x86_64
PHP 7.2.24-0ubuntu0.18.04.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="50M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at REDACTED Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.30-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (5.7.30) - Perfect!
OK/var/log/glpi : OK
OK/etc/glpi/ : OK
OK/var/lib/glpi : OK
OK/var/lib/glpi/_dumps : OK
OK/var/lib/glpi/_sessions : OK
OK/var/lib/glpi/_cron : OK
OK/var/lib/glpi/_graphs : OK
OK/var/lib/glpi/_lock : OK
OK/var/lib/glpi/_plugins : OK
OK/var/lib/glpi/_tmp : OK
OK/var/lib/glpi/_cache : OK
OK/var/lib/glpi/_rss : OK
OK/var/lib/glpi/_uploads : OK
OK/var/lib/glpi/_pictures : OK

htmLawed version 1.2.4 in (/var/www/html/glpi/lib/htmlawed)
phpmailer/phpmailer version 6.0.7 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.3 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.2 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
zendframework/zend-cache in (/var/www/html/glpi/vendor/zendframework/zend-cache/src)
zendframework/zend-i18n in (/var/www/html/glpi/vendor/zendframework/zend-i18n/src)
zendframework/zend-serializer in (/var/www/html/glpi/vendor/zendframework/zend-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
leafo/scssphp in (/var/www/html/glpi/vendor/leafo/scssphp/src)
phpCas version 1.3.3 in (/usr/share/php)

Plugin list
	actualtime           Name: ActualTime                     Version: 1.2.0      State: Enabled
	fields               Name: Additionnal fields             Version: 1.10.3     State: Enabled
	behaviors            Name: Behaviours                     Version: 2.2.2      State: Enabled
	dashboard            Name: Dashboard                      Version: 0.9.6      State: Enabled
	escalade             Name: Escalation                     Version: 2.4.4      State: Enabled
	datainjection        Name: File injection                 Version: 2.7.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.8.3      State: Enabled
	itilcategorygroups   Name: ItilCategory Groups            Version: 2.3.1      State: Enabled
	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.1      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.6.1      State: Enabled
	genericobject        Name: Objects management             Version: 2.7.0      State: Enabled
	tag                  Name: Tag Management                 Version: 2.6.0      State: Enabled
	tasklists            Name: Tasks list                     Version: 1.5.1      State: Enabled
	timezones            Name: Timezones                      Version: 2.5.2      State: Enabled

**Comment by orthagh** [comment]
Hello.

check the dom in the gui : 
![image](https://user-images.githubusercontent.com/418844/83723994-d383c480-a63f-11ea-8aaf-aa932a338465.png)

You need to pass `_plugin_fields_type` and `_plugin_fields_subtype` to have aditionnal fields managed by the plugin.

Regards

**Comment by b1scuit-thi3f** [comment]
Hello,

Thank you for your reply. I've tried your solution and I can confirm it does work when the field is added to one of the original tabs (such as Computer, OS, etc). However, it appears these values aren't available for custom tabs, and only `plugin_fields_containers_id` exists. Are you able to advise on what I might need to pass here? I have tried passing `plugin_fields_containers_id`, just the two you mentioned (setting `_plugin_fields_type` to "dom" and "tab" in case that helped), and all three together, but none appeared to work.

Regards

**Comment by bloempotsoep** [comment]
Experiencing the same problem as @b1scuit-thi3f describes above. Works fine for fields injected into the Computer form, does not function for other tabs.

**Comment by orthagh** [comment]
for tab container : 

![image](https://user-images.githubusercontent.com/418844/83757744-3ccffb80-a671-11ea-8f22-11be9845315b.png)

so, you must have:

- the fieldname
- `plugin_fields_containers_id`
- `items_id`
- `itemtype`

maybe also `update_fields_values` but not sure.

You may note the gui do **not** update computer form but container form so your api request must do a PUT on `PluginFieldsContainer` and not on `Computer`

Hope this help.

**Comment by skreu** [comment]
Hi everyone and Happy New Year !
Sorry to bother you but i'm a little confused. I'm trying to update a custom field in Appliance section
I succeeded in modifying a text field which is in the main form (before save button) and... that's it.

I'm trying to update a custom field in Appliance section which is a dropdown field and I can't succeed. Status is 200 but nothing changes.
Also I didn't understand how to modify a text field in a specific tab whether the field is a text one or a dropdown one.

Would you mind if I ask for an example ? Thank you very much !
