### ISSUE TITLE
Fix display of tickets associated to a document

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#7357]
**Describe the bug**
Related tickets are not shown from a document page.

Debug says:

SELECT COUNT(*) AS cpt FROM `glpi_tickets` LEFT JOIN `glpi_documents_items` ON (`glpi_documents_items`.`items_id` = `glpi_tickets`.`id`) LEFT JOIN `glpi_entities` ON (`glpi_tickets`.`entities_id` = `glpi_entities`.`id`) WHERE (`glpi_documents_items`.`documents_id` = '3727' OR (`glpi_documents_items`.`itemtype` = 'Document' AND `glpi_documents_items`.`items_id` = '3727')) AND `glpi_documents_items`.`itemtype` = 'Ticket' AND ((`glpi_tickets`.`entities_id` IN ('12') OR (`glpi_tickets`.`is_recursive` = '1' AND `glpi_tickets`.`entities_id` IN ('0', '9')))) ORDER BY `glpi_entities`.`completename`, `glpi_tickets`.`id`

0.001

Unknown column 'glpi_tickets.is_recursive' in 'where clause'

**Page(s) URL**
.../glpi/front/document.form.php

**To reproduce**

1. Go to Management -> Documents
2. Click on a document (supposing it is from a ticket)
3. Go to Associated Items
4. See no tickets are associated to the document
5. See in Historical that a link with a ticket item has been added.

**Expected behavior**

Display list of tickets associated to a document

**Logs**

[2020-06-02 16:18:17] glpisqllog.ERROR: DBmysql::query() in /usr/share/glpi/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: SELECT `glpi_tickets`.*, `glpi_documents_items`.`id` AS `linkid`, `glpi_entities`.`id` AS `entity` FROM `glpi_tickets` LEFT JOIN `glpi_documents_items` ON (`glpi_documents_items`.`items_id` = `glpi_tickets`.`id`) LEFT JOIN `glpi_entities` ON (`glpi_tickets`.`entities_id` = `glpi_entities`.`id`) WHERE (`glpi_documents_items`.`documents_id` = '3727' OR (`glpi_documents_items`.`itemtype` = 'Document' AND `glpi_documents_items`.`items_id` = '3727')) AND `glpi_documents_items`.`itemtype` = 'Ticket' AND ((`glpi_tickets`.`entities_id` IN ('12') OR (`glpi_tickets`.`is_recursive` = '1' AND `glpi_tickets`.`entities_id` IN ('0', '9')))) ORDER BY `glpi_entities`.`completename`, `glpi_tickets`.`id`
  Error: Unknown column 'glpi_tickets.is_recursive' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95
  inc/dbmysql.class.php:580                          DBmysqlIterator->execute()
  inc/commondbrelation.class.php:1833                DBmysql->request()
  inc/document_item.class.php:412                    CommonDBRelation::getTypeItems()
  inc/document_item.class.php:275                    Document_Item::showForDocument()
  inc/commonglpi.class.php:485                       Document_Item::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()
  {"user":"1234@toto.titi.fr"}

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]
 
GLPI 9.4.6 (/glpi => /usr/share/glpi)
Installation mode: RPM

Server
--
Operating system: Linux toto.titi.fr 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 PHP 7.2.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, igbinary, imap, intl, json, ldap, 	libxml, lzf, mbstring, mcrypt, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, recode, session, shmop, 	snmp, soap, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zip, zlib) Setup: max_execution_time="120" memory_limit="512M" post_max_size="15M" safe_mode="" session.save_handler="files" 	upload_max_filesize="15M"  Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.31 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363 Server Software: MariaDB Server 	Server Version: 10.2.22-MariaDB 	Server SQL Mode:  	Parameters: root@::1/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed Database version seems correct (10.2.22) - Perfect! /var/log/glpi : OK /etc/glpi : OK /var/lib/glpi/files : OK /var/lib/glpi/files/_dumps : OK /var/lib/glpi/files/_sessions : OK /var/lib/glpi/files/_cron : OK /var/lib/glpi/files/_graphs : OK /var/lib/glpi/files/_lock : OK /var/lib/glpi/files/_plugins : OK /var/lib/glpi/files/_tmp : OK /var/lib/glpi/files/_cache : OK /var/lib/glpi/files/_rss : OK /var/lib/glpi/files/_uploads : OK /var/lib/glpi/files/_pictures : OK SELinux mode is Disabled

Libraries
--
htmLawed version 1.2.4.2 in (/usr/share/php/htmLawed) phpmailer/phpmailer version 6.1.6 in (/usr/share/php/PHPMailer/PHPMailer6) simplepie/simplepie version 1.5.4 in (/usr/share/php/php-simplepie) tecnickcom/tcpdf version 6.3.5 in (/usr/share/php/tcpdf) michelf/php-markdown in (/usr/share/php/Michelf) true/punycode in (/usr/share/php/TrueBV) iamcal/lib_autolink in (/usr/share/php/php-iamcal-lib-autolink) sabre/vobject in (/usr/share/php/Sabre/VObject4) zendframework/zend-cache in (/usr/share/php/Zend/Cache) zendframework/zend-i18n in (/usr/share/php/Zend/I18n) zendframework/zend-serializer in (/usr/share/php/Zend/Serializer) monolog/monolog in (/usr/share/php/Monolog) sebastian/diff in (/usr/share/php/SebastianBergmann/Diff) elvanto/litemoji in (/usr/share/php/LitEmoji) symfony/console in (/usr/share/php/Symfony3/Component/Console) leafo/scssphp in (/usr/share/php/Leafo/ScssPhp) phpCas version 1.3.8 in (/usr/share/pear)

Plugins list
--
additionalalerts     Name: Alertes supplémentaires        Version: 2.2.0      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.10.1     State: Enabled 	printercounters      Name: Compteurs Imprimantes          Version: 1.6.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.9.1      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.4+2.4    State: Enabled 	geninventorynumber   Name: Génération de numéros d'invent Version: 2.4.0      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Enabled

[/code]

**Comment by cedric-anne** [comment]
Hi,

You did not provide informations requested in issue template.

Regards

**Comment by kabassanov** [comment]
Sorry, I've just updated initial post and filtered sensible data.

**Comment by cedric-anne** [comment]
Hi,

I confirm the SQL issue. To reproduce, you must be in a sub entity.

But if you do not see tickets here, it is because there are not visible in the current entity. I am not sure we should display them as even their title may contain a sensitive information.

Regards

**Comment by kabassanov** [comment]
Hi, sorry for delayed reply.
Fix works for me.

Cedrric-Anne: Related tickets were from the same entity, but I had sub entities view selected...
