### ISSUE TITLE
Problem Tickets with sub-entity is default entity

### ISSUE THREAD

**Issue by cp61** [glpi-project/glpi#7371]
**Describe the bug**

Hello,

We have one entity and 8 sub-entities

I am super administrator for all

If in my profile I assign myself by default the main entity as a super-administrator, I can see all the tickets of all the sub-entities.

If I assign myself a sub-entity by default in my profile and I return to the main entity then no ticket appears.

**To reproduce**

1. Go to 'Administration / Users'
2. Click on 'user with multiple right super admin'
3. Affect one sub-entity
4. Reconnect GLPI, no tickets in main entity

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.4.6 (/glpi => C:\xampp\htdocs\glpi) Installation mode: TARBALL
--

Operating system: Windows NT SRV-SIC 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586 PHP 7.1.11 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, 	mcrypt, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, standard, tokenizer, wddx, xml, xmlreader, 	xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.29 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2l PHP/7.1.11 (Apache/2.4.29 (Win32) mod_authnz_sspi/0.1.0 	OpenSSL/1.0.2l PHP/7.1.11 Server at srv-sic Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0 Server Software: mariadb.org binary distribution 	Server Version: 10.1.28-MariaDB 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.1.28) - Perfect! C:\xampp\htdocs\glpi/files/_log : OK C:\xampp\htdocs\glpi/config : OK C:\xampp\htdocs\glpi/files : OK C:\xampp\htdocs\glpi/files/_dumps : OK C:\xampp\htdocs\glpi/files/_sessions : OK C:\xampp\htdocs\glpi/files/_cron : OK C:\xampp\htdocs\glpi/files/_graphs : OK C:\xampp\htdocs\glpi/files/_lock : OK C:\xampp\htdocs\glpi/files/_plugins : OK C:\xampp\htdocs\glpi/files/_tmp : OK C:\xampp\htdocs\glpi/files/_cache : OK C:\xampp\htdocs\glpi/files/_rss : OK C:\xampp\htdocs\glpi/files/_uploads : OK C:\xampp\htdocs\glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed) phpmailer/phpmailer version 6.0.7 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.3 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.3.2 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src) iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib) zendframework/zend-cache in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-cache\src) zendframework/zend-i18n in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-i18n\src) zendframework/zend-serializer in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-serializer\src) monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog) sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src) elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src) symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console) leafo/scssphp in (C:\xampp\htdocs\glpi\vendor\leafo\scssphp\src)

Server: 'ldap://10.61.7.100', Port: '389', BaseDN: 'DC=SDIS,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=svcad,OU=USERS,OU=02_ADMINISTRATION,DC=SDIS,DC=local', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@10.61.7.121)

Name: 'support@sdis61.fr' Active: Yes 	Server: '{10.61.7.121/imap/novalidate-cert/tls}' Login: 'sdis\support' Password: Yes

news                 Name: Alertes                        Version: 1.6.0      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.10.3     State: Enabled 	behaviors            Name: Comportements                  Version: 2.2.2      State: Enabled 	escalade             Name: Escalades                      Version: 2.4.4      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.9.2      State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.8.0      State: Not activated 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.1      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled

Host: 10.61.7.103Connection: OkUse the OCSNG software dictionary: No
[/code]

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce the problem.

Are you sure that tickets are viewable from selected entity ? If tickets are located in subentities, you have to click on following button to be able to see them : 
![image](https://user-images.githubusercontent.com/33253653/84990334-45cacd80-b145-11ea-8ac0-caa6c973a551.png)


Regards

**Comment by trasher** [comment]
ping?

**Comment by cp61** [comment]
Hello sorry I had not seen your return.

I see if I can make you a video to make it more meaningful

**Comment by cp61** [comment]
It is OK for me. If I click on the logo it works by cons if I click directly on the name of the entity it does not have the same effect. Why ?


> 
> 
> Hi,
> 
> I cannot reproduce the problem.
> 
> Are you sure that tickets are viewable from selected entity ? If tickets are located in subentities, you have to click on following button to be able to see them :
> ![image](https://user-images.githubusercontent.com/33253653/84990334-45cacd80-b145-11ea-8ac0-caa6c973a551.png)
> 
> Regards

**Comment by cedric-anne** [comment]
It is expained here : 
![image](https://user-images.githubusercontent.com/33253653/86125599-3b151e80-badd-11ea-87b4-804a22086eeb.png)
