### ISSUE TITLE
Spaces trimmed when writing followup (Chrome / Firefox) - Installed version 9.4.5

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#7378]
**Describe the bug**

We have several complaints regarding trimmed spaces when writing a followup (a new paragraph). In this case, it happened when using Chrome or Firefox.
If the issue happens, for us to be able to put a space between words, we have to press the "space key" twice!

**Expected behavior**

Not to loose the spaces, when we are writing a message.

**Screenshots**

![image](https://user-images.githubusercontent.com/43515938/84009788-b0248680-a96b-11ea-912c-9fa42aa7bce5.png)

Anyone else with this issue??

**Comment by cedric-anne** [comment]
Duplicates #5786

Fixed on next major version (9.5).
