### ISSUE TITLE
Drop "all" tab

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#7382]
I do not know if this feature is really used, I personally do not see a real interest to keep the "all" tab; therefore I propose to remove it.

For future evolution (like replacing the JS lib used to handle tabs), this would require extra work; so I'm not sure we should keep it.

**Comment by trasher** [comment]
This can indeed make sense on this page; thanks for the feedback :)

When using rule configuration UI, actions and criteria are on different tabs, this can be useful to understand better to display them from the "all" tab currently.
For that one, we think the complete UI would need to be reworked a little; including merge of those tabs into one, so usage for "all" tab would no longer be needed.

**Comment by OscarBeiro** [comment]
All tab helps newbies into searching for a particular field, using browser search, otherwise they need to open every tab in order to find it.

**Comment by hgpit** [comment]
I'm with @cconard96 and @OscarBeiro. We use the all tab in particular for finding options to change when updating authorization profiles

**Comment by cconard96** [comment]
@OscarBeiro Are there specific forms/pages where that is needed like Profiles or just helpful in general? I could see the Entity and General settings being confusing for new users too.

**Comment by vollkommenIrrelevant** [comment]
We don't user the tab for user management, only for searching a specific setting in the settings page. Nevertheless think it make sense to have this button.

**Comment by OscarBeiro** [comment]
@cconard96 Sorry for the late reply. As I told before, tabs are OK when you are 100% sure about where you are looking, and helps reducing loading times by not showing unnecessary options, but usually, it's easier to search on the browser for a known string if all of them are shown.

So, helpful in general :)

**Comment by Mirkk** [comment]
Agree with @OscarBeiro, the "All"-Tab is a great GLPI feature - for browser search and to get a fast overview.

**Comment by arthurrschaefer** [comment]
I guess almost everybody had put the major people experience about the 'All' tab.

It's great for searching when people don't really know the exact location of a string or field.

I see many people using it on a daily basis.
