### ISSUE TITLE
[9.5] PopUp when change Type of ticket on ticket creation

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7389]
When you create a new ticket, and you change the type of the ticket

![image](https://user-images.githubusercontent.com/13178158/84250621-91112a80-ab0c-11ea-8411-27fa356d35f6.png)

There is Pop Up for quit Web site.. not really usefull ?

**Comment by trasher** [comment]
ping @cconard96

**Comment by cconard96** [comment]
I can't make a PR right now, but any fields that trigger a reload like that need 'data-track-changes="false"' attribute added to them.
