### ISSUE TITLE
usage of "parent::" in lock class who inherit nothing

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#739]
In current master

see : 
https://github.com/glpi-project/glpi/blob/master/inc/lock.class.php#L51
https://github.com/glpi-project/glpi/blob/master/inc/lock.class.php#L556

**Comment by orthagh** [comment]
Forget me @tomolimo, i mixed up lock and itemlock.
Issue is still valid anyway

**Comment by tomolimo** [comment]
no problem

**Comment by orthagh** [comment]
Seems a copypasted code, removal incoming
