### ISSUE TITLE
[9.5 RC1]can't install from package

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#7399]
**Describe the bug**
Can not install from intall package

**To reproduce**

download archive from github
mv glpi-9.5.0-rc1.tgz /var/www/html
cd /var/www/html  (there is no glpi folder)
tar -xvf glpi-9.5.0-rc1.tgz 
cd glpi
php bin/console db:update

=> error message :+1: 
Uncaught Exception Error: Class 'Locale' not found in /var/www/html/glpi/inc/session.class.php at line 632

**Logs**
[2020-06-10 20:47:44] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'Locale' not found in /var/www/html/glpi/inc/session.class.php at line 632
  Backtrace :
  inc/console/application.class.php:383              Session::loadLanguage()
  inc/console/application.class.php:93               Glpi\Console\Application->computeAndLoadOutputLang()
  bin/console:101                                    Glpi\Console\Application->__construct()
  

**Screenshots**
using firefox  : localhost/glpi  displays blanK screen 

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
UBUNTU 20.04 LTS
MariaDB10
php7.4.3

**Comment by trasher** [comment]
You must indeed install the required intl extension, see related docs: https://glpi-install.readthedocs.io/en/develop/prerequisites.html#php
This is still a bug, since there is a requirements checks on cli command that should handle those case more user friednly.

**Comment by ladenree76000** [comment]
I could update. after enabling intl extension.
console update from 9.4.6 to 9.5 RC1

every things looks to work fine, however in migration to 9.5.log i have :

**Duplicated document item relation  {"user":"@myuser-Vostro-200","mem_usage":"9.240\", 25.88Mio)"}** 
[about hundred times the same]


[2020-06-11 20:38:29] glpiphplog.NOTICE: GLPIKey::getLegacyKey() in /var/www/html/glpi/inc/glpikey.class.php line 116
Called method is deprecated  {"user":"@myuser-Vostro-200","mem_usage":"61.077\", 28.33Mio)"} 
[2020-06-11 20:38:29] glpiphplog.NOTICE: Toolbox::decrypt() in /var/www/html/glpi/inc/toolbox.class.php line 310

Use sodiumDecrypt  {"user":"@myuser-Vostro-200","mem_usage":"0.001\", 28.35Mio)"} 
[ 6 time the same message]

**Comment by orthagh** [comment]
we should check if cli warn users about missing extensions.

**Comment by cedric-anne** [comment]
> This is still a bug, since there is a requirements checks on cli command that should handle those case more user friednly.

Well, this is a it tricky to handle this one. Indeed, this error happens during locale initialization which is done before requirements checks.
I just checked, and if a mandatory dependency is missing, install/update from cli is not possible:
![image](https://user-images.githubusercontent.com/33253653/84651402-2d22a380-af0a-11ea-997a-1273cda4c018.png)


> **Duplicated document item relation {"user":"@myuser-Vostro-200","mem_usage":"9.240", 25.88Mio)"}**
> [about hundred times the same]
This one seems to be due to a difference between unicity check on update script and unicity check on document item class. I created issue #7430  for this.

> 
> [2020-06-11 20:38:29] glpiphplog.NOTICE: GLPIKey::getLegacyKey() in /var/www/html/glpi/inc/glpikey.class.php line 116
> Called method is deprecated {"user":"@myuser-Vostro-200","mem_usage":"61.077", 28.33Mio)"}
> [2020-06-11 20:38:29] glpiphplog.NOTICE: Toolbox::decrypt() in /var/www/html/glpi/inc/toolbox.class.php line 310
> 
> Use sodiumDecrypt {"user":"@myuser-Vostro-200","mem_usage":"0.001", 28.35Mio)"}
> [ 6 time the same message]

Could you provide the full trace ? This may be due to a plugin.

**Comment by ladenree76000** [comment]
i ran the full upgrade : 

-remove plugin from 9.4.6
-dump & restore in glpi95 database
-extract RC1 archive in glpi95
cd /var/www/html/glpi95
php bin/console db:update -u

in phperror log :
 hundreds times same message : 
**Duplicated document item relation  {"user":"@TESNIERE-Vostro-200","mem_usage":"1.602\", 28.17Mio)"} 
[2020-06-16 23:20:43] glpiphplog.ERROR: Document_Item::prepareInputForAdd() in /var/www/html/glpi95/inc/document_item.class.php line 121**

but other messages are not present anymore

**Comment by Mikhail-D** [comment]
I have a blank screen on install. And no any errors in php_errors.log.
Deeper I found that line in **session.class.php** is brake the script:
`\Locale::setDefault($trytoload);`
 I just comment it to succes install.

**Comment by trasher** [comment]
PHP fatal errors like this one are logged in PHP system logs (depends on your system php configuration).
Correct fix is to install the missing **required** extension, not to disable its usage.

**Comment by cedric-anne** [comment]
Original issue fixed in d3be4aa.
