### ISSUE TITLE
[9.5 RC1] Upgrade Erro 9.3 to 9.5 RC1

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#7400]
Erro to make upgrade from 9.3.4 direct to 9.5RC1

The process stop in "work in process"

SO: Ubuntu 20.04
PHP: 7.4
MariaDB: 15.1 Distrib 10.3.22-MariaDB,

![image](https://user-images.githubusercontent.com/22614882/84323545-58de0c00-ab4d-11ea-8168-ae3e726b1f55.png)

**Comment by flegastelois** [comment]
Hi,

No problem for me, 9.3.4 direct to 9.5.0-RC1:

![image](https://user-images.githubusercontent.com/470612/84359158-85833980-abc8-11ea-97b9-62c5e2281c1f.png)

Please provides logs as indicate in new issue template (Find them in *-error.log files under glpi/files/_log/, or in your javascript console).

**Comment by glpibr** [comment]
Erro to rename a Table:

![image](https://user-images.githubusercontent.com/22614882/84441935-0e26c780-ac13-11ea-92bb-866c538bc9c6.png)

- - - Text Report

root@PEVTCMTNB2590:/home/halexsandro/public_html# tail -f  glpi95/files/_log/php-errors.log

[2020-06-11 18:38:33] glpiphplog.WARNING: Test logger  
[2020-06-11 18:38:33] glpiphplog.WARNING: Test logger  
[2020-06-11 18:38:33] glpiphplog.DEBUG: Html::compileScss() in /home/halexsandro/public_html/glpi95/inc/html.class.php line 7384
css/palettes/auror.scss is new, loading  {"user":"@PEVTCMTNB2590"} 
[2020-06-11 18:38:34] glpiphplog.DEBUG: Html::compileScss() in /home/halexsandro/public_html/glpi95/inc/html.class.php line 7384
css/styles.scss is new, loading  {"user":"@PEVTCMTNB2590"} 
[2020-06-11 18:38:42] glpiphplog.ERROR: Migration::renameTable() in /home/halexsandro/public_html/glpi95/inc/migration.class.php line 631
Não é possível renomear tabela glpi_changes_projects (ok) para glpi_itils_projects (nok)!  {"user":"@PEVTCMTNB2590"} 

- - - end text report

Did you use a real data base in your test?

I tested on 2 customer bases that are in operation with > 4GB.
 
If you need any specific tests, I am at your service!

**Comment by flegastelois** [comment]
Thanks,

Do you have the same error when migrating from 9.3.4 to 9.4.6? This table rename is not on 9.5 upgrades.

Also, can you provide the "sql-errors"?

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by glpibr** [comment]
Sorry for the delay in responding, I was involved with some projects here and I was unable to return the tests.

Today, I migrated from 9.3.4 to 9.4.6 and found the same error.

During my tests, I could identify that the error occurred because a table with the same name already existed, however, without any data entered. I didn't have time to validate when this table was created. But, I believe it is an error in the installation process. The script is probably creating, at some inopportune time, the glpi_itils_projects table and when it tries to rename the glpi_changes_projects table it stops the process with the error because a table with this name already exists.

Here I print the list of tables present before the upgrade is performed... Notice that the glpi_changes_projects table exists:


![image](https://user-images.githubusercontent.com/22614882/86496177-85eb9c00-bd52-11ea-8ae3-c7134efc9c26.png)

Note that the glpi_itils_projects table does not exist either before the upgrade process. Therefore, I assume that the table is being created by the upgrade script at the wrong time.
![image](https://user-images.githubusercontent.com/22614882/86496341-64d77b00-bd53-11ea-9257-53ef4ebcdabf.png)

**Outline Solution**

For those who encountered this error, I proceeded as follows:
I saw that the table existed after I started the installation process. So, I listed its contents to see what information was in it.
I noticed that the table contained no data. So, I deleted the table and restarted the update process.
That done, the process ran smoothly.

This error affects the migration from 9.3.4 to 9.4.6 and 9.3.4 to 9.5 RC1.

**Solução de Contorno**

Para quem encontrat este erro, procedi da seguinte forma:
Vi que existia a tabela depois que iniciei o processo de instalação. Então, listei o seu conteúdo para ver quais informações estavam nela. 
Percebi que a tabela não continha dados. Então, excluí a tabela e reiniciei o processo de atualização.
Feito isso, o processo rodou normalmente. 

Este erro afeta a migração de 9.3.4 para a 9.4.6 e 9.3.4 para a 9.5 RC1.

![image](https://user-images.githubusercontent.com/22614882/86496529-3e660f80-bd54-11ea-8f0b-5c9b2df94d72.png)

**Comment by trasher** [comment]
glpi_itis_projects tables is created during the upgrade from 9.3 to 9.4. So it does not exists in the 9.3 database. You are trying to run upgrade several times the same base, that cause issue.
If you have issues during any upgrade, you have to restore your backup before doing another try.

**Comment by cedric-anne** [comment]
Hi,

This kind of issues commonly happens when admin installs the new GLPI version on a new DB and restore the old GLPI DB on this new DB, creating a mix of old and new tables.
If you want to update GLPI, then you must not follow the installation process. Just run the update process on your existing GLPI DB and it will works.

**Comment by glpibr** [comment]
Hello gentlemen,
I can guarantee that I only performed the update process because it was going from 9.3.4 to 9.4.6.

Anyway, I left the record here in case other people encounter the error.

A great day everyone!

#PTBR
Olá senhores,
posso garantir que apenas realizei o processo de update pois, estava saindo da 9.3.4 para a 9.4.6.

De toda forma, deixei aqui o registro para o caso de outras pessoas se depararem com o erro.

um ótimo dia a todos!


[photo]
Halexsandro de Freitas Sales
Gerente de Projetos | Consultor Service Desk

+55 81 3091 42 52<tel:+55%2081%203091%2042%2052>   |  9 8802 30 1<tel:+55%2081%209%208802%2030%2011>1<mailto:halexsandro.sales@verdanadesk.com>


Recife, Pernambuco - Brasil <https://www.verdanadesk.com>

Telegram: @halexsandro<https://www.verdanadesk.com>
halexsandro.sales@verdanadesk.com<mailto:halexsandro.sales@verdanadesk.com>

________________________________
De: Cédric Anne <notifications@github.com>
Enviado: segunda-feira, 6 de julho de 2020 09:23
Para: glpi-project/glpi <glpi@noreply.github.com>
Cc: Halexsandro Sales <halexsandro.sales@verdanatech.com>; Author <author@noreply.github.com>
Assunto: Re: [glpi-project/glpi] [9.5 RC1] Upgrade Erro 9.3 to 9.5 RC1 (#7400)


Hi,

This kind of issues commonly happens when admin installs the new GLPI version on a new DB and restore the old GLPI DB on this new DB, creating a mix of old and new tables.
If you want to update GLPI, then you must not follow the installation process. Just run the update process on your existing GLPI DB and it will works.
