### ISSUE TITLE
Marketplace not Working

### ISSUE THREAD

**Issue by tguichard25** [glpi-project/glpi#7411]
Hello,

I can't access to MarketPLace.
On the last dev 9.5, 
![image](https://user-images.githubusercontent.com/47602797/84477949-cd6d9380-ac90-11ea-97b1-af37dc2675ff.png)
I don't use any proxy.
![image](https://user-images.githubusercontent.com/47602797/84478077-fee65f00-ac90-11ea-9496-b6fa4815ac50.png)

**Comment by orthagh** [comment]
@cedric-anne it seems we have an issue with pro-abono mode (services mode seems to be working).

Users with "registerd" offers (maybe also paid ones) cannot check network informations.

obsfucated backtrace
```
[2020-06-12 07:58:35] glpiphplog.ERROR: GLPINetwork::getRegistrationInformations() in C:\laragon\www\glpi\9.5.git\inc\glpinetwork.class.php line 197
{
    "message": "Undefined index: DateStart",
    "exception": "ErrorException",
    "file": "app/Services/Subscriptions/CustomerManager.php",
    "line": 304,
...
```

**Comment by cedric-anne** [comment]
Hi @tguichard25 ,

We fixed an issue on registration API. Could you check if it works now ?

Regards

**Comment by tguichard25** [comment]
Same error, no change.

**Comment by cedric-anne** [comment]
Can you check on GLPI logs ?
Can you also provide your system configuration ?

**Comment by tguichard25** [comment]
`[2020-06-15 08:45:27] glpiphplog.ERROR: Toolbox::callCurl() in C:\glpi_lab\inc\toolbox.class.php line 1714
Échec de connexion. Si vous utilisez un proxy, merci de le configurer. (SSL certificate problem: self signed certificate in certificate chain)  {"user":"6@SRV-PARC01"} 
[2020-06-15 08:52:57] glpiphplog.ERROR:   *** PHP User Error (256): Trying to load a forbidden class name "0" in C:\glpi_lab\inc\autoload.function.php at line 266
  Backtrace :
  inc\autoload.function.php:266                      trigger_error()
  :                                                  glpi_autoload()
  :                                                  spl_autoload_call()
  plugins\formcreator\ajax\commontree.php:45         is_a()`

Server Windows 2012 R2
IIS 8.5
PHP 7.2
MySQL 5.6

**Comment by orthagh** [comment]
Could you test again, we did some changes in the ssl chain.

**Comment by tguichard25** [comment]
SSL certificate problem: unable to get local issuer certificate

**Comment by flegastelois** [comment]
Hi,

This last error is due to an incorrect SSL configuration on your PHP Windows installation (missing CA certificates in curl module).

https://curl.haxx.se/docs/sslcerts.html

https://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate/34883260#34883260

Regards,

**Comment by tguichard25** [comment]
I entered curl.cainfo in php.ini, now it works.

Thank you.

**Comment by orthagh** [comment]
as said in this morning meeting, do help users understand that some issues could be on their side, GLPI Network tab on general setup may display some debug messages

**Comment by LazMs** [comment]
Hello how are you?
I managed to solve this problem by adding a line in /et/hosts
51.210.109.9 services.glpi-network.com

**Comment by LehandroBlesses** [comment]
![error GLPI](https://github.com/glpi-project/glpi/assets/113634731/7bceaac4-6cda-4d89-8e45-6998c3ac253a)
Yo tengo el siguiente error
