### ISSUE TITLE
api query missing sql escape

### ISSUE THREAD

**Issue by buborh** [glpi-project/glpi#7414]
**Describe the bug**

Api query missing sql escape.

**Page(s) URL**
/apirest.php/phonemodel?searchText[name]='n'

**To reproduce**

Use curl example:
curl -X GET -H 'Content-Type: application/json' -H "Session-Token:REMOVED" -H "App-Token:REMOVED"  "http://domain.com/apirest.php/phonemodel?searchText[name]='n'"

**Expected behavior**

It retrives all result.

**Logs**

[2020-06-12 12:33:07] glpisqllog.ERROR: DBmysql::query() in /inc/dbmysql.class.php line 177
  *** MySQL query error:
  SQL: SELECT SQL_CALC_FOUND_ROWS DISTINCT `glpi_phonemodels`.id,  `glpi_phonemodels`.*
                FROM `glpi_phonemodels`

                WHERE 1=1  AND (`glpi_phonemodels`.`name`   LIKE '%'n'%' )
                ORDER BY id ASC
                LIMIT 0, 51
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'n'%' )
                ORDER BY id ASC
                LIMIT 0, 51' at line 4
  Backtrace :
  inc/api.class.php:1270
  inc/apirest.class.php:237                          API->getItems()
  apirest.php:48                                     APIRest->call()

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.4.2 ( => /var/www/clients/client1/web12/web)
Installation mode: TARBALL
PHP 7.2.24-0ubuntu0.18.04.6 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bcmath, calendar,
	cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, json, ldap, libxml,
	mbstring, memcache, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium,
	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="330" memory_limit="512M" post_max_size="80M" safe_mode="" session.save_handler="files"
	upload_max_filesize="200M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at trigoglpi.iamit.hu Port 443)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.30-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: c1trigoglpi@localhost/c1trigoglpi
	Host info: Localhost via UNIX socket

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

#7457 should fix you issue.

Regards
