### ISSUE TITLE
 [9.5 RC1] X columns are not compatible with timezones

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#7415]
I am not sure if it is a bug.
After Update from 9.4.3 to 9.5 I have warning on dashboard,
473 columns are not compatible with timezones usage.
![grafik](https://user-images.githubusercontent.com/8606735/84521651-a1283600-acd5-11ea-91f4-d7838b9b6bb3.png)

**Comment by trasher** [comment]
This is not a bug. If you want to use timezones, you have to fix your current schema, which can takes time (this is not done on update).
See https://glpi-install.readthedocs.io/en/develop/command-line.html#use-timestamp-data-type.

Don't forget https://glpi-install.readthedocs.io/en/develop/timezones.html if you plan to use them; mysql do requires additional setup.

**Comment by we-sell-bags** [comment]
This does not seem to resolve the issues.
Still getting "5" columns  not compatible with time zone usage.
been into the database with a DB tool & the tables & rights appear to have been added inline with the required documents

**Comment by sioud** [comment]
You could repare it by this command line, I am using Centos 7:
move to the path of Glpi : cd /usr/share/glpi
then put this command : bin/console glpi:migration:timestamps
Accept [yes]
Done :)

**Comment by sioud** [comment]
If you want to set you timezone correctly fellow these steps 👍 
$ mysql -u root -p

>put there your password for the mysql root 

GRANT SELECT ON `mysql`.`time_zone_name` TO 'inetum_u4glpi'@'%';
FLUSH PRIVILEGES;
exit

cd /usr/share/glpi
bin/console glpi:migration:timestamps

**Comment by DoctorDeatch** [comment]
> 
> 
> If you want to set you timezone correctly fellow these steps 👍
> $ mysql -u root -p
> 
> > put there your password for the mysql root
> 
> GRANT SELECT ON `mysql`.`time_zone_name` TO 'inetum_u4glpi'@'%';
> FLUSH PRIVILEGES;
> exit
> 
> cd /usr/share/glpi
> bin/console glpi:migration:timestamps

Спасибо большое !!!
