### ISSUE TITLE
Appliances and Webapps not migrated from plugins

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#7416]
**Describe the bug**
After upgrade from 9.4.6 to 9.5 RC-1  Appliances (previoulsy managed by plugin) are now empty

**Page(s) URL**
http://localhost/glpi95/front/appliance.form.php?id=1

**To reproduce**
install glpi 9.4.6 + appliance 2.5.0 create some appliances
upgrade to glpi 9.5 RC-1
go to management>appliances :  no appliances

r=try to open a ticket linked with a previos appliance =>**Uncaught Exception Error: Class 'PluginAppliancesAppliance' not found in /var/www/html/glpi95/inc/ticket.class.php at line 7350**  (plugin is not present)

**Expected behavior**

appliances data should be migrated from plugin to core 

**Additional context**
appliance plugin in not (not yet ?) compatible with 9.5

**Comment by trasher** [comment]
Appliances integration concerns appliances and webapps plugins; a migration script would take care of both.
We did not plan to work on that for now, but of course anyone can do it and open a pull request to get it integrated :)

As of the plugins compatibility, no idea, better ask their maintainers ;)

**Comment by trasher** [comment]
```
Uncaught Exception Error: Class 'PluginAppliancesAppliance' not found in /var/www/html/glpi95/inc/ticket.class.php at line 7350 (plugin is not present)
```
That one should probably be fixed anyways, this should not cause an error, will take a look.

**Comment by trasher** [comment]
> That one should probably be fixed anyways, this should not cause an error, will take a look.
Already fixed :)

**Comment by ladenree76000** [comment]
As far as I can see, webapplications are not in 9.5RC2 core so I wil still use Webapplicaiton plugin.
for appliances these sql statements do the job  :
```
INSERT INTO glpi_appliances(id,entities_id,is_recursive,name,is_deleted,appliancetypes_id,comment,locations_id,manufacturers_id,applianceenvironments_id,users_id,users_id_tech,
groups_id,groups_id_tech,relationtype,date_mod,states_id,externalidentifier,serial,otherserial) select id,entities_id,is_recursive,name,is_deleted,plugin_appliances_appliancetypes_id,comment,locations_id,0,plugin_appliances_environments_id,users_id,users_id_tech,
groups_id,groups_id_tech,relationtype,date_mod,states_id,externalid,serial,otherserial  FROM  glpi_plugin_appliances_appliances  WHERE 1=1
INSERT INTO glpi_plugin_appliances_relations(id,appliances_appliances_items_id,relations_id) select  id,plugin_appliances_appliances_items_id,relations_id from glpi_plugin_appliances_relations wHERE 1=1
insert into glpi_appliances_items (id,appliances_id,items_id,itemtype) SELECT id, plugin_appliances_appliances_id,items_id,itemtype FROM glpi_plugin_appliances_appliances_items WHERE 1=1
INSERT INTO glpi_appliancetypes(id,entities_id,is_recursive,name,comment,externalidentifier) SELECT id,entities_id,is_recursive,name,comment,externalid FROM glpi_plugin_appliances_appliancetypes WHERE 1=1
INSERT INTO glpi_applianceenvironments (id,name,comment) SELECT id,name,comment FROM glpi_plugin_appliances_environments WHERE 1=1
update glpi_items_tickets set itemtype='Appliance' where itemtype='PluginAppliancesAppliance'
update glpi_items_problems set itemtype='Appliance' where itemtype='PluginAppliancesAppliance'
update glpi_items_projects set itemtype='Appliance' where itemtype='PluginAppliancesAppliance'
update glpi_profiles set helpdesk_item_type=replace(helpdesk_item_type,'PluginAppliancesAppliance','Appliance') where 1=1

```

**Comment by trasher** [comment]
Looks like webapplications plugin is almost the same as appliances; with just different names/tables and some other changes, but really not a lot.

Thank you fro the SQL, it may help other in the same case.

**Comment by ladenree76000** [comment]
I wonder if it wouldn't be better to manage it plugin side :  the APPLIANCES plugin migration script should manage migration to GLPI's core 

we will see in next glpi version if webapplications are also merged in glpi's core

**Comment by ladenree76000** [comment]
I've tried to write a script for migrating data from plugin to core using console.
it works if no appliances have been added to core before running this script.
this script uses id's from plugin. ( I don't understand how does the mapping works)

 

[appliancesplugintocorecommand.class.txt](https://github.com/glpi-project/glpi/files/4919749/appliancesplugintocorecommand.class.txt)

**Comment by ladenree76000** [comment]
https://github.com/glpi-project/glpi/pull/7717

**Comment by ladenree76000** [comment]
there a job in progress for web appliances https://github.com/InfotelGLPI/webapplications/tree/3.0.0

it might not be compatible with this script.

**Comment by EC2311** [comment]
Hello

I was using web-applications plugin too. 
Now this plugin is inside GLPI : OK.

Nevertheless, using this plugin, I was able to add some added "type" : like Project, group, user, which can be useful to add information on web-application.

I tried to do this for the core :

- Update define.php : line 465
$CFG_GLPI['appliance_types']     = ['Computer', 'Monitor', 'NetworkEquipment', 'Peripheral', 'Phone',
                                       'Printer', 'Software', 'Cluster', **'Project', 'Group', 'User', 'Appliance'**'];
like this : we can add this kind of GLPI objects : ok. 
appliance may be useful to link as 'parent' topic...

BUT
when we look at appliances list : the 'attached items' are not well known... Group appears with appliance link (for instance)

Nevertheless, When we look at the inside file : it's good : the item is group, and so on...
And if we select the appliance it-self to update it : the list of 'attached items' it ok !

It seems that in 'search.class.php (line 6018 about)' the array $DATA[ID$] seems to have wrong data (in itemtype). BUt I don't succeed in finding where it is filled :(

Any Idea ?

**Comment by EC2311** [comment]
Hello

I found an explanation
You must add a field to the SQL request : 
![image](https://user-images.githubusercontent.com/42341169/109969037-b3c71d00-7cf3-11eb-9ced-76fae6fa01e6.png)

in the initial request, "order by" is missing for items (Item_5)

GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_appliances_items`.`items_id`,  '__NULL__ '),
                                                '$#$ ',`glpi_appliances_items`.`id`) **ORDER BY `glpi_appliances_items`.`id`** SEPARATOR  '$$##$$ ')
                              AS `ITEM_Appliance_5`,
                  
                   IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_appliances_items`.`itemtype`,
                                                                          '__NULL__ '),
                                                    '$#$ ', `glpi_appliances_items`.`id`) SEPARATOR  '$$##$$ '),  '__NULL__$#$ ')
                                    AS `ITEM_Appliance_5_itemtype`
