### ISSUE TITLE
[9.5 rc-1] SQL error when profile can open ticket for simcards

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#7417]
**Describe the bug**
when opening a ticket >tab items > (debug mode) displays 

SQL Error "1054": Unknown column 'users_id' in 'where clause' in query "SELECT * FROM `glpi_items_devicesimcards` WHERE `users_id` = '190' AND ((`glpi_items_devicesimcards`.`entities_id` = '1' OR (`glpi_items_devicesimcards`.`is_recursive` = '1' AND `glpi_items_devicesimcards`.`entities_id` IN ('0')))) AND `is_deleted` = '0' AND `is_helpdesk_visible` = '1' ORDER BY `name`"

**Page(s) URL**

http://localhost/glpi95/front/ticket.form.php?id=3245
**To reproduce**
select debugmode
select a profile that can associate simscards to tickets
select a ticket and select Items tab => displays SQL ERROR
select a profile that CAN NOT  associate simscards to tickets
go back to tickets>items => OK

**Expected behavior**
no sql error should happen when profile can associate simcards

**Logs**

```
paste logs here
SQL Error "1054": Unknown column 'users_id' in 'where clause' in query "SELECT * FROM `glpi_items_devicesimcards` WHERE `users_id` = '190' AND ((`glpi_items_devicesimcards`.`entities_id` = '1' OR (`glpi_items_devicesimcards`.`is_recursive` = '1' AND `glpi_items_devicesimcards`.`entities_id` IN ('0')))) AND `is_deleted` = '0' AND `is_helpdesk_visible` = '1' ORDER BY `name`"
```

**Screenshots**

![image](https://user-images.githubusercontent.com/13557254/84548574-33e0c900-ad06-11ea-8f73-935c91feed5c.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
glpi 9.5. RC1 upgraded from 9.4.6 

**Additional context**
the error happened with no simcards created.
I have created one simcard (not very intuitive) but the message still happens
(never installed simcards plugin in previous versions)

**Comment by cedric-anne** [comment]
Fixed by 4f0a74b.
