### ISSUE TITLE
[9.5 RC-1] Columns are not Align center with items name

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#7419]
This bug is present in all sections: (if you viewed just a few columns)
![grafik](https://user-images.githubusercontent.com/8606735/84560043-5f80a500-ad40-11ea-895e-a64ced4b74e1.png)

![grafik](https://user-images.githubusercontent.com/8606735/84560074-a078b980-ad40-11ea-8568-1c1b9130dfc1.png)

**Comment by husisusi** [comment]
199ab53 did not fix it. No effect.

**Comment by orthagh** [comment]
Hello, please check in debug mode.

The released archive contains minified files for js/css and so in normal mode, applying the mentionned commit will not have any effects.

**Comment by husisusi** [comment]
Sorry! I can not explain but after reboot it works.
![grafik](https://user-images.githubusercontent.com/8606735/84784071-2ec39880-afea-11ea-8644-27ebfa6d269b.png)
Thanks!
