### ISSUE TITLE
[9.5 RC-1] Cannot add simcards item

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#7420]
**Describe the bug**
If I try to add simcards item, I get this error "Simcards: A device ID is mandatory"
![grafik](https://user-images.githubusercontent.com/8606735/84560420-2ea26f00-ad44-11ea-811b-dc4c716bf00b.png)

 **To reproduce**
Just try add new simcard item

**Expected behavior**
new simcards item added

**Logs**
No errors in php-errors.log or sql-errors.log
In AJAX DEBUG:
`
_target | => | /glpi/front/item_devicesimcard.form.php
-- | -- | --
_itemtype | => | Item_DeviceSimcard
_glpi_tab | => | Item_DeviceSimcard$main
id | => |  
sort | => |  
order | => |  
withtemplate | => |  
entities_id | => | 0
is_recursive | => | 0
`

**Comment by ladenree76000** [comment]
You only can add simcard if linked with a component :
![image](https://user-images.githubusercontent.com/13557254/84574242-74dbea80-ada5-11ea-96f0-2ff4e51e6985.png)

**Comment by husisusi** [comment]
Thank You! It Works.
