### ISSUE TITLE
[9.5 RC-1] Cannot view NetworkPort form

### ISSUE THREAD

**Issue by cconard96** [glpi-project/glpi#7421]
**Describe the bug**

Form does not load completely. On debug mode the following is shown:
Uncaught Exception Error: Cannot instantiate abstract class NetworkPortInstantiation in /var/www/html/fix95/inc/dbutils.class.php at line 302

**Page(s) URL**

http://localhost/fix95/front/networkport.form.php?id=5

**To reproduce**

1. Go to any asset with a network port
2. Click on the port number to view the form

**Expected behavior**

The form loads

**Additional context**

Issue is caused by NetworkPortInstantiation class being abstract now. When it tries to load that tab on the NetworkPort form, it tries instantiate the abstract class in CommonGLPI::addStandardTab since getTabNameForItem is not static.

Full stack:
```
dbutils.class.php:302, DbUtils->getItemForItemtype()
db.function.php:138, getItemForItemtype()
commonglpi.class.php:338, NetworkPort->addStandardTab()
networkport.class.php:452, NetworkPort->defineTabs()
commonglpi.class.php:294, NetworkPort->defineAllTabs()
commonglpi.class.php:859, NetworkPort->showTabsContent()
commonglpi.class.php:1230, NetworkPort->display()
networkport.form.php:139, {main}()
```

**Comment by bitstacker** [comment]
Workaround that worked for me:
in inc/networkport.class.php line 452
remove/comment the line
`//$this->addStandardTab('NetworkPortInstantiation', $ong, $options);`

**Comment by trasher** [comment]
This whould work:
```diff
diff --git a/inc/networkportinstantiation.class.php b/inc/networkportinstantiation.class.php
index fb9ef7afea..a9f92a2d60 100644
--- a/inc/networkportinstantiation.class.php
+++ b/inc/networkportinstantiation.class.php
@@ -50,7 +50,7 @@ if (!defined('GLPI_ROOT')) {
  * @since 0.84
  *
 **/
-abstract class NetworkPortInstantiation extends CommonDBChild {
+class NetworkPortInstantiation extends CommonDBChild {
 
    // From CommonDBTM
    public $auto_message_on_action   = false;
```
