### ISSUE TITLE
Unable to register for marketplace in 9.5.0

### ISSUE THREAD

**Issue by simon-inman** [glpi-project/glpi#7423]
**Describe the bug**

In 9.5.0-rc1 I am unable to add a registration key to use the marketplace
I get the error: Unable to fetch registration informations.

This is potentially blocking access/view to manually install plugins.

**Page(s) URL**

/front/config.form.php?forcetab=GLPINetwork%241

**To reproduce**

1. Go to Plugins
2. Click on 'fill your registration key on setup'
3. Paste registration key. Click Save

**Expected behavior**

I would expect the registration key to be applied and the market place available.

**Logs**

[2020-06-14 11:32:26] glpiphplog.ERROR: Plugin::getInfo() in /usr/share/glpi/inc/plugin.class.php line 1388
plugin_version_analytics-1.0.2 method must be defined!  {"user":"2@xxx-xxx"}

**Screenshots**

NA

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.0-dev ( => /usr/share/glpi)
Installation mode: TARBALL

**Additional context**

Updated install from 9.4.5 to 9.5.0-rc1/dev

**Comment by simon-inman** [comment]
already logged as issue

**Comment by cedric-anne** [comment]
Hi @simon-inman ,

We fixed an issue on registration API. Could you check if it works now ?

Regards

**Comment by simon-inman** [comment]
Thank you :-)
Works now

**Comment by pnopriadi** [comment]
Hi @simon-inman and @cedric-anne , I found the same issue while we are using GLPI 9.5.1. 
I can't register the key then white blank page shown after Save the page. 

I'm try on localhost but there is no issue. Is there any idea to fix the issue?

**Comment by AntonioMadeira** [comment]
Hello, i have the same problem in glpi  9.5.4 please help me out

**Comment by cedric-anne** [comment]
> Hello, i have the same problem in glpi 9.5.4 please help me out @cedric-anne

Hi,

Initial issue was solved. Please open a new one and give us all requested informations.

Regards
