### ISSUE TITLE
[9.5 RC-1] No permission to add domain "Record"

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#7424]
**Describe the bug**
If I try to add a Record in domain section (Super-admin) I get:
"You don't have permission to perform this action"

**To reproduce**

1. Switch to  Super-admin profile
2. Click on "Management" > " Domains"
3. Click "Record" on the side menu
4. Click "+" to add new records
![grafik](https://user-images.githubusercontent.com/8606735/84602181-bba11180-ae85-11ea-992b-663aa60317f8.png)

5. You will get "You don't have permission to perform this action"
![grafik](https://user-images.githubusercontent.com/8606735/84602231-23575c80-ae86-11ea-908d-8fb567a5ef55.png)

**Comment by trasher** [comment]
Is this a fresh install or an update? Check ACLs in configuration, you should be able to fix that.

**Comment by husisusi** [comment]
It was Update!
Of course the ACLs, I was looking for it but it's tiny, sorry!!!
![grafik](https://user-images.githubusercontent.com/8606735/84786589-42243300-afed-11ea-8d2f-83acacf0a972.png)

now works
![grafik](https://user-images.githubusercontent.com/8606735/84786691-5c5e1100-afed-11ea-9a0b-22fcf3f258f0.png)
