### ISSUE TITLE
[9.5.0-rc1] Duplicated document item relation

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#7430]
**Describe the bug**

During ugrade to GLPI 9.5.0, there is lots of logs related to `Duplicated document item relation`.

**Page(s) URL**

-

**To reproduce**

Upgrade to GLPI 9.5.0.
I did not find the exact problem, but it seems to happens when a ticket contains multiple times a same document.

**Expected behavior**

No erros during ugrade.

**Logs**

```
Document_Item::prepareInputForAdd() in /var/www/glpi/inc/document_item.class.php line 121
Duplicated document item relation

Backtrace :
  inc/document_item.class.php:122                    Toolbox::backtrace()
  inc/commondbtm.class.php:1099                      Document_Item->prepareInputForAdd()
  install/update_94_95.php:1557                      CommonDBTM->add()
  inc/console/database/updatecommand.class.php:179   update94to95()
  vendor/symfony/console/Command/Command.php:255     Glpi\Console\Database\UpdateCommand->execute()
  vendor/symfony/console/Application.php:1000        Symfony\Component\Console\Command\Command->run()
  inc/console/application.class.php:218              Symfony\Component\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:271         Glpi\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:147         Symfony\Component\Console\Application->doRun()
  bin/console:102                                    Symfony\Component\Console\Application->run()

```

**Screenshots**

-

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
9.5.0-rc1
```

**Additional context**

Seems to be due to a mismatch between checks done on update script and checks done on class itself.
Indeed https://github.com/glpi-project/glpi/blob/9.5/bugfixes/install/update_94_95.php#L1556 checks on more fields than https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/document_item.class.php#L117 .

**Comment by trasher** [comment]
Are you sure this happens on the first run? Not really sure because I do not know how to reproduce, but it may happens on a second run, and in this case this may be ignored.

**Comment by cedric-anne** [comment]
@ladenree76000 

Did these warnings appears on the migration from a previous version or didi it appears only when replaying the migration to 9.5.0 once it has already been done ?

Regards

**Comment by ladenree76000** [comment]
it happened at the first attempt and also the following.
each time i start from an empty database, restore 9.4.6 dump and run db upgrade from console ( however i'm thinking that i did not copy /glpi/files/* from 9.4.6 to my new 9.5 instance)

**Comment by ladenree76000** [comment]
i'm downloading all my files to glpi95/files ,(this will take a long time)  then i will drop my database, extract archive, restore dump, copy files, upgrade and give feedback.

**Comment by cedric-anne** [comment]
Hi,

This is not directly related to document files, having them will not change anything about this error.
Can you try #7494 ?

Regards

**Comment by ladenree76000** [comment]
what I did :(using command lines) with RC2

remove oldglpi folder
drop database glpi95
create database glpi95

restore glpi9.4.6 dump to glpi95 DB
extract RC2 archive in glpi95 folder

replace 3 files modified by commit

set downstream.php (files, log and config not in web server)

set glpi95 owner to www-data

cd /var/www/html/glpi95

 php bin/console db:update -u

wait 3 minutes

migration done :  empty log :-)
