### ISSUE TITLE
[9.5 RC1] SQL Errors if use leftjoin from plugins

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7436]
Hello

I have plugins which use _addLeftJoin hook & i have sql errors into GLPI linked to 

https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/search.class.php#L4965

The problem is that the hook is not loaded

If i comment this line - it's ok

**Comment by cedric-anne** [comment]
Fixed by 9ef4155.
