### ISSUE TITLE
Notice in planning export

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#7437]
in debug mode, export planning shows 
![image](https://user-images.githubusercontent.com/13557254/84574483-fa13cf00-ada6-11ea-947d-52038c8538e9.png)

undefine index host in  .../inc/planning.class.php at line 966

_Originally posted by @ladenree76000 in https://github.com/glpi-project/glpi/issues/7393#issuecomment-643649074_

**Comment by cedric-anne** [comment]
Hi @ladenree76000

What is your configured application URL ?
You can see this configurationv value in `Setup` > `General` > `General setup`.

Regards

**Comment by ladenree76000** [comment]
my configured application URL is http://localhost/glpi95

**Comment by cedric-anne** [comment]
Hi,

The only explaination I have is that you may have a leading space in your configuration. Can you check ?

```
$ php -r "var_dump(parse_url('http://localhost/glpi95'));"
array(3) {
  ["scheme"]=>
  string(4) "http"
  ["host"]=>
  string(9) "localhost"
  ["path"]=>
  string(7) "/glpi95"
}
```

```
$ php -r "var_dump(parse_url(' http://localhost/glpi95'));"
array(1) {
  ["path"]=>
  string(24) " http://localhost/glpi95"
}
```

**Comment by ladenree76000** [comment]
you got it !
I checked twice url and  instead of http**:**//localhost/glpi95 i typed http**;**//localhost/glpi95  (semicolumn) 

it's ok now

sorry for wasting your time...

**Comment by cedric-anne** [comment]
Well, maybe we should add a check on config form submission to prevent this kind of issues.
