### ISSUE TITLE
Only can paste images in tickets if debug mode is enabled GLPI 9.5.0-dev

### ISSUE THREAD

**Issue by aesquis** [glpi-project/glpi#7443]
**Describe the bug**

After upgrade to lastest verion GLPI 9.5.0-dev when we try to paste a clipboard image in a ticket description nothing happends. But if enable debug mode it works perfectly

**To reproduce**

1. Open new ticket
2. Paste a clipboard image in description

**Logs**

We checked /files/_log/php-error.log and nothing happened

**Server Info**

GLPI 9.5.0-dev (/glpi => /var/www/html/glpi) Installation mode: TARBALL

 
GLPI 9.5.0-dev (/glpi => ./glpi)
Installation mode: TARBALL

**Comment by trasher** [comment]
Probably the same issue as https://github.com/glpi-project/glpi/issues/7393, but on another lib.

**Comment by aesquis** [comment]
This is the java error

fileupload.min.js?v=9.5.0-dev:7 Uncaught ReferenceError: fileType is not defined
    at XMLHttpRequest.n.onload (fileupload.min.js?v=9.5.0-dev:7)


n.onload | @ | fileupload.min.js?v=9.5.0-dev:7
-- | -- | --
  | load (async) |   |  
  | (anonymous) | @ | fileupload.min.js?v=9.5.0-dev:7
  | c | @ | tinymce.min.js?v=9.5.0-dev:367
  | fire | @ | tinymce.min.js?v=9.5.0-dev:370
  | un | @ | tinymce.min.js?v=9.5.0-dev:952
  | kt | @ | tinymce.min.js?v=9.5.0-dev:962
  | St | @ | tinymce.min.js?v=9.5.0-dev:963
  | d | @ | tinymce.min.js?v=9.5.0-dev:978
  | Ae | @ | tinymce.min.js?v=9.5.0-dev:979
  | (anonymous) | @ | tinymce.min.js?v=9.5.0-dev:980
  | w | @ | tinymce.min.js?v=9.5.0-dev:964
  | (anonymous) | @ | tinymce.min.js?v=9.5.0-dev:980
  | Promise.then (async) |   |  
  | t | @ | tinymce.min.js?v=9.5.0-dev:977
  | M | @ | tinymce.min.js?v=9.5.0-dev:980
  | (anonymous) | @ | tinymce.min.js?v=9.5.0-dev:983
  | c | @ | tinymce.min.js?v=9.5.0-dev:367
  | fire | @ | tinymce.min.js?v=9.5.0-dev:370
  | vf | @ | tinymce.min.js?v=9.5.0-dev:373
  | n | @ | tinymce.min.js?v=9.5.0-dev:375
  | r | @ | tinymce.min.js?v=9.5.0-dev:34
  | x | @ | tinymce.min.js?v=9.5.0-dev:34

**Comment by husisusi** [comment]
same here.

**Comment by trasher** [comment]
Then you should just drop the `lib/jquery-file-upload.min.js`, issue is fixed already; see the other ticket and linked PR.

**Comment by aesquis** [comment]
Hello again, I just trying to remove lib/jquery-file-upload.min.js file and/or replacing commits in https://github.com/glpi-project/glpi/commit/53145d3bcfb7946c4d2ae9ec2ede8e52996fc844 but I'm still wiht the same problem.

As I understud you said that we only have to remove /public/lib/jquery-file-upload.min.js , is thris true?

Thanks

**Comment by trasher** [comment]
Applying the commit won't change anything if you do not compile again JS files. This is done on release.
If all goes fine in dev mode, just remove all `*.min.js` files from public directory, this would be enough.
If problem still persists in dev mode, this is not the same issue.

You can try with latest nightly build of 9.5/bugfixes branch: https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22
