### ISSUE TITLE
Feature Request: Software licenses assignable to Network Device

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#7445]
Hi all,

Currently using GLPI v9.4.6.

For things like Cisco network gear, we sometimes buy additional feature licenses, OS upgrades, Sophos/McAfee AV and other service subscriptions etc.

We asset manage these under Software Licenses area of GLPI, but are unable to link the licenses to the appropriate network device. It appears that only Computers are assignable to software.

Is it possible to allow GLPI to link Software Licenses to Network Devices in the future please?

Thank you

**Comment by trasher** [comment]
Try 9.5.0-RC1, see https://github.com/glpi-project/glpi/pull/6216
