### ISSUE TITLE
GLPI Website Down

### ISSUE THREAD

**Issue by memtech3** [glpi-project/glpi#7448]
The GLPI website at glpi-project.org is currently down according to https://www.isitdownrightnow.com/glpi-project.org.html

**Comment by trasher** [comment]
Hi, thanks for the report. We are aware of the problem, we're working on it.

**Comment by matthewbaynham** [comment]
Also the forum website is down as well.
https://forum.glpi-project.org

**Comment by husisusi** [comment]
Guys, If you need help just let as know!
It's getting embarrassing!

**Comment by flegastelois** [comment]
Hi,

Our current host provider experiencing a major outage, all GLPI Project en Network sites are being migrated to another hosting platform, it may take a little more time to do.

:muscle:

**Comment by memtech3** [comment]
RIP Hosting provider

**Comment by cedric-anne** [comment]
Problem is solved.
