### ISSUE TITLE
groups_id_tech is missing in notification templates

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#745]
Hello,

The groups_id_tech tags are missing in notification templates in notificationtargetcommonitilobject.class.php in `getTags()` and in `getDatasForObject()`

Regards,
Tomolimo

**Comment by orthagh** [comment]
merged

**Comment by yllen** [comment]
Not correct for group with > in this name

**Comment by yllen** [comment]
Revert please, i'm working on it https://github.com/glpi-project/glpi/issues/215

**Comment by orthagh** [comment]
ok, sorry for the conflict (reverted in af62cd2)

**Comment by yllen** [comment]
Done https://github.com/glpi-project/glpi/commit/58969ccfe2667e1d34abc6d159e1fa6c1efc5754
