### ISSUE TITLE
'Group in charge of the task' is missing in the notification recipients

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#746]
Hello,

'Group in charge of the task' is missing in the notification recipients
Should mimic the 'Technician in charge of the task recipient.

regards,
Tomolimo

**Comment by yllen** [comment]
I'm working on it https://github.com/glpi-project/glpi/issues/215

**Comment by yllen** [comment]
Done https://github.com/glpi-project/glpi/commit/58969ccfe2667e1d34abc6d159e1fa6c1efc5754
