### ISSUE TITLE
No Function of Mail Collector

### ISSUE THREAD

**Issue by jeaneve79** [glpi-project/glpi#7460]
Hello,

i installed GLPI 9.5. RC1 on Cent OS with Xampp. In the Version 9.4.4 everything was fine. In the new Version when i enter my mail Server and Credentials i have a Problem to collect mails. Every Time i Press the Button "collect mails" the browser jumps in an empty page and nothing happens. I try with pop3, 110, no tls, no cert check. What can i do.

Greets 
Eve

**Comment by trasher** [comment]
CentOS with xampp? Sounds strange.

Anyways, as requested in ticket template, please provide logs.
