### ISSUE TITLE
Global search does not include Domains section

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#7461]
Global search does not include **Domains, Simcards and more**.

![grafik](https://user-images.githubusercontent.com/8606735/85132361-e77f1700-b238-11ea-8d06-f3c60e232a44.png)

But:
Computers, Contacts, Contract, Documents, Monitors, Network, devices, Devices, Phones, Printers, Software, Licenses, Tickets, Problems, Changes, Users, Groups, Projects, Suppliers, Budgets, Certificates, Lines, Data, centers, Server, rooms, Enclosures, PDUs, Racks, Clusters.

**Comment by husisusi** [comment]
Is this really an unimportant enhancement?
How complicated is it to expand this search?

**Comment by husisusi** [comment]
This bug has been resolved. You can close this issue.

**Comment by trasher** [comment]
Thank you for the feedback.
