### ISSUE TITLE
Images importation from the collector

### ISSUE THREAD

**Issue by evanTruck** [glpi-project/glpi#7471]
The issues is this one : we have a mail collector in GLPI can get import the mails into tickets. But, we have a mail signature. And when GLPI import this one, the image disappear and we have a big attachement in the tickets of a grey image. 

And I have a "<![if !vml]>" instead of the image.

**Expected behavior**

I would like to have the signature image in the ticket traitement section, and not a big grey line in attachement. 

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.4.4 (/glpi => /var/www/html/glpi)
Installation mode:TARBALL

**Comment by cedric-anne** [comment]
Hi,

It seems that your signature is built using "Conditional comments" which are not understood by the component we use to "sanitize" HTML, resulting in having a `<![if !vml]>` text.

For the "grey line" image, it can be found either in the message body and the signature. You should check the source code of your message.
You may have a separator that is rendered using an image.
You may also have an incorrect alternative image in your signature. Indeed, most of the time, signatures using VML embed 2 images, the first one displayed if VML renderer is available, and a second one displayed if not. If you always open your messages using Outlook, you will never see this second image, and never notice that it is not a valid one.

If you want us to be able to investigate deeper into your issue, you should attach here the original message (inside a `.eml` file).

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot do anything without feedback.

Regards
