### ISSUE TITLE
Project Task limited to 100 hours

### ISSUE THREAD

**Issue by yalgva** [glpi-project/glpi#7472]
Hello,

glpi 9.5 and 9.4.6

I don't know if it is a bug or not, but tasks for project are limited to 100 hours.

It is very short. Is it possible to modify this value if it is not a but.

Thank you

**Comment by cedric-anne** [comment]
Hi,

I personally find that allowing affecting up to 100 hours for a unique task is already a too high limit. There are many reasons why the separation into several tasks may be more relevant (there are many articles explaining these reasons, like this one : https://blog.trello.com/microproductivity-break-tasks-into-smaller-steps ).

I am not sure that adding more more values on this dropdown will be usefull for common usages, and I do not even know what can be the most relevant max value.

For information, this limit is defined here https://github.com/glpi-project/glpi/blob/9.4/bugfixes/inc/projecttask.class.php#L597.

Regards

**Comment by tsmr** [comment]
For information, I got the same request from my manager and I increased the value to 500

**Comment by yalgva** [comment]
Thx I did the same value to 500.
