### ISSUE TITLE
mysqli extension not properly checked when a config file is present

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#7473]
**Describe the bug**

If mysqli is not installed; and there is already a `config/config_db.php` file present; extension check is not done (from cli, not tested on web).

**To reproduce**

1. Uninstall mysqli extension
2. From an already configured 9.5 instance, try to install/update or any command from cli
3. See error

**Expected behavior**

Extension should be checked.

**Logs**

```
$ php72 bin/console glpi:system:check_requirements
Uncaught Exception Error: Class 'mysqli' not found in /var/www/webapps/glpi/inc/dbmysql.class.php at line 160
```

**Comment by cedric-anne** [comment]
Fixed by 6f0b503.
