### ISSUE TITLE
Error inserting mail to queue Glpi 9.4.6

### ISSUE THREAD

**Issue by rogers3d** [glpi-project/glpi#7479]
Dear Glpi masters

After migration from 9.3 (new installation, db backup and restore) to 9.4.6, new tickets notifications are not sending from glpi, and updates in some fields (category, assigments, anything else) shows the following error (Error inserting mail to queue):

![image](https://user-images.githubusercontent.com/48422181/85620634-0cf19380-b632-11ea-8b81-256efbbd28d6.png)

In case of updates, the same error is shown but mail is sent. I review the notification queu and saw some suspicius, blank lines where must be a message queued,

![image](https://user-images.githubusercontent.com/48422181/85620913-71acee00-b632-11ea-8712-f5b5198363f4.png)

Did I miss something? Any suggestion? 

Thanks in advance

The installation is:

GLPI 9.4.6 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux localhost.localdomain 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 PHP 7.2.31 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, ctype, curl, 	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, 	pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, 	wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="1000" memory_limit="128M" post_max_size="2G" safe_mode="" session.save_handler="files" 	upload_max_filesize="8M"  Software: Apache/2.4.6 (CentOS) PHP/7.2.31 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36 Server Software: MariaDB Server 	Server Version: 10.1.45-MariaDB 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed exif extension is installed Zend OPcache extension is not present APCu extension is not present xmlrpc extension is not present CAS extension is not present Database version seems correct (10.1.45) - Perfect! /var/www/glpi/files/_log : OK /var/www/glpi/config : OK /var/www/glpi/files : OK /var/www/glpi/files/_dumps : OK /var/www/glpi/files/_sessions : OK /var/www/glpi/files/_cron : OK /var/www/glpi/files/_graphs : OK /var/www/glpi/files/_lock : OK /var/www/glpi/files/_plugins : OK /var/www/glpi/files/_tmp : OK /var/www/glpi/files/_cache : OK /var/www/glpi/files/_rss : OK /var/www/glpi/files/_uploads : OK /var/www/glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.SELinux mode is Disabled

htmLawed version 1.2.4 in (/var/www/glpi/lib/htmlawed) phpmailer/phpmailer version 6.0.7 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.3 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.2 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) zendframework/zend-cache in (/var/www/glpi/vendor/zendframework/zend-cache/src) zendframework/zend-i18n in (/var/www/glpi/vendor/zendframework/zend-i18n/src) zendframework/zend-serializer in (/var/www/glpi/vendor/zendframework/zend-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) leafo/scssphp in (/var/www/glpi/vendor/leafo/scssphp/src)

Not active

Way of sending emails: SMTP+SSL (xxxx@xxxxxxx.xx@smtp.gmail.com)

Name: 'ticket@xxxx.xxx' Active: Yes 	Server: '{imap.gmail.com:993/imap/ssl}INBOX' Login: 'ticket@xxxx.xxx' Password: Yes Name: 'soporte@xxxx.xxx' Active: No 	Server: '{imap.gmail.com:993/imap/ssl}INBOX' Login: 'xxxx@xxxx.xxx' Password: Yes

dashboard            Name: Dashboard                      Version: 0.9.8      State: Enabled 	datainjection        Name: Data injection                 Version: 2.7.1      State: Not activated 	mod                  Name: GLPI Modifications             Version: 1.5.4      State: Enabled
[/code]

**Comment by rogers3d** [comment]
Of ourse, I've paste the logs from:

cron.log

![image](https://user-images.githubusercontent.com/48422181/85730330-92735300-b6c7-11ea-8ca1-d9ed6e2a60a4.png)

prp-errors.log

![image](https://user-images.githubusercontent.com/48422181/85730680-da927580-b6c7-11ea-9873-7d2925416bcd.png)

sql-errors.log

![image](https://user-images.githubusercontent.com/48422181/85730897-07df2380-b6c8-11ea-99b8-eb8f129aff20.png)

mail-error.log

![image](https://user-images.githubusercontent.com/48422181/85731415-8045e480-b6c8-11ea-954d-fdb2bf9bbd1f.png)

queuednotification is set to CLI mode, and sending mail to administrator works fine.

Thanks in advance, and sorry my bad english.

**Comment by cedric-anne** [comment]
Hi,

There is multiple errors shown in your logs.

First, it seems that there is a problem with `mod` plugin. You should try to disable this plugin and do some tests.

Seconds, it seems that you have SMTP connection problems, can you check that your SMTP connection is correctly configured ? Maybe your problem comes from this.

Then, the SQL error seems related to the "merge as followup" action of a ticket. I am not sure it has anything to do with notifications.

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
