### ISSUE TITLE
Management tab suppiler and budget - historical log 

### ISSUE THREAD

**Issue by r0bertk** [glpi-project/glpi#7480]
Hello, from version 9.4.2 to 9.5 logging in the Assets-> computers-> Management-> Suppiler and budget tab does not work. no new entry appears in Historical log

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.

To reproduce :
 - create a supplier,
 - create a computer,
 - enable financial and administrative informations from that computer,
 - define the supplier of the computer and save,
-> supplier is saved but nothing appears in historical tab.

As modifying other fields in "management" tab adds an entry in history, modifying supplier should also do this.

Regards

**Comment by cedric-anne** [comment]
Fixed by #13857
