### ISSUE TITLE
Php-error : Profile with no plugin access

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7482]
Php-error :

[2020-06-23 15:41:07] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in C:\wamp64\www\glpi\inc\plugin.class.php at line 101
  Backtrace :
  inc\html.class.php:1577                            Plugin::getMenuContent()
  inc\html.class.php:6871                            Html::generateMenuSession()
  inc\html.class.php:1696                            Html::displayMainMenu()
  front\central.php:81                               Html::header()

![image](https://user-images.githubusercontent.com/13178158/85425006-ef142800-b578-11ea-8a35-aa963597bd70.png)

To resolve it : 

```
diff --git a/inc/plugin.class.php b/inc/plugin.class.php
index 48b3e061f8..13b1de0e1e 100644
--- a/inc/plugin.class.php
+++ b/inc/plugin.class.php
@@ -98,7 +98,7 @@ class Plugin extends CommonDBTM {
                            : '/front/plugin.php';
          $menu['icon']  = self::getIcon();
       }
-      if (count($menu)) {
+      if (is_array($menu) && count($menu)) {
          return $menu;
       }
       return false;
```

_Originally posted by @tsmr in https://github.com/glpi-project/glpi/issues/7196#issuecomment-648248172_

**Comment by trasher** [comment]
@tsmr please test https://github.com/glpi-project/glpi/pull/7484
