### ISSUE TITLE
Racks are changing rear and front images of assets

### ISSUE THREAD

**Issue by arthurrschaefer** [glpi-project/glpi#7502]
**Describe the bug**

When you set the images for the assets templates you must choose the correct front and rear images.
When you attach the asset (Computers) to the rack, the rear image is shown in the front view of the rack, and the front image is shown in the back of the rack.

We changed the `glpi/inc/rack.class.php` FRONT to 0 and REAR to 1.

**Correct set up:**
![image](https://user-images.githubusercontent.com/13874922/86004875-4b989c80-b9ea-11ea-8803-695cbe5ad83f.png)

**Wrong view:**
![image](https://user-images.githubusercontent.com/13874922/86004932-5bb07c00-b9ea-11ea-91f5-4c55f441ed51.png)

**How it should be shown:**
![image](https://user-images.githubusercontent.com/13874922/86004991-6f5be280-b9ea-11ea-9658-2264c4c6ca39.png)

`glpi/inc/commondcmodeldropdown.class.php`
![image](https://user-images.githubusercontent.com/13874922/86005214-b649d800-b9ea-11ea-8205-f5cd4048254e.png)

`glpi/inc/rack.class.php`
![image](https://user-images.githubusercontent.com/13874922/86005248-c06bd680-b9ea-11ea-83bf-05f9817a5cda.png)

**Version GLPI 9.5 RC2** The Beta and RC1 don't appear to have this bug.

**Comment by orthagh** [comment]
Hello @arthurrschaefer.

I'm not sure about this bug, i saw it on the pt_br telegram channel, but didn't replicate on my side.

The code your pointed seems good on the repository : https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/commondcmodeldropdown.class.php#L126-L138

**Comment by orthagh** [comment]
Oh i may have an explanation, on the link between the rack and the item, you can choose the item orientation to do a reverse insertion : 
![image](https://user-images.githubusercontent.com/418844/86006667-9c25ef00-ba16-11ea-91c1-49f6dfbf8048.png)

To edit an existing relation, toggle images off and click on the pencil icon
![image](https://user-images.githubusercontent.com/418844/86006745-b3fd7300-ba16-11ea-8213-e82949690cb0.png)

**Comment by orthagh** [comment]
Could you confirm you have rear orientation (and so no issue)

**Comment by arthurrschaefer** [comment]
Hey, @orthagh.

I see. And now I realized that he made the change in `glpi/inc/commondcmodeldropdown.class.php`. So the picture is already the change he made before realizing the problem was in the rack.class.php, where he changed the FRONT and REAR IDs to 0 and 1 respectively.

**Comment by arthurrschaefer** [comment]
> Could you confirm you have rear orientation (and so no issue)

I'm gonna ask him, since I don't have the RC here. 😁

**Comment by arthurrschaefer** [comment]
Yes, @orthagh.

I didn't realize that option there.

If I change the orientation from front to rear, the image is shown changed. And it makes sense. It's like I'm at the back of the rack and see the assets.

We just got confused because the headers of the racks are the same.

Maybe if it had a tag notifying we are seeing the rack by the front or the rear that could be easier not to get confused.

But it's not a bug. Just misinformation.

Thanks!

**Comment by orthagh** [comment]
To note, it's the orientation of the asset, not the orientation of the rack.
If defined on Rear, the front of the asset is placed on the rear of the rack

**Comment by arthurrschaefer** [comment]
Understood!

Now I got it.

I didn't remember the assets we attach in the rear of the racks.

Thank you very much, again! @orthagh
