### ISSUE TITLE
Imagens no corpo de email nao esta carregando 

### ISSUE THREAD

**Issue by wesleyfernandocabrera** [glpi-project/glpi#7503]
**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by arthurrschaefer** [comment]
@wesleyfernandocabrera . O suporte aqui é em inglês. Se tu puderes dar mais detalhes, eu posso repassar para o suporte aqui em inglês. Ok?

Versão, passos para reproduzir, quando acontece....

-----------
The support here is in English. If you can give us more details, I can rewrite them in English so the support can help with the problem.

Version, steps to reproduce it, when the problem happens.
