### ISSUE TITLE
RC2 feedback-Notifications work only with a few entities

### ISSUE THREAD

**Issue by oldkeg** [glpi-project/glpi#7506]
The notifications for new tickets are working just with a few entities. The entities have the same configuration and rules but when generating a new ticket the notification is not generated, only in the first 3 entities

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

Can you provide requested informations (logs, GLPI setup, ...) ?

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot really investigate without logs.

Regards
