### ISSUE TITLE
[9.5 RC2] Dropdown::addNewCondition() must be of the type array

### ISSUE THREAD

**Issue by keha35** [glpi-project/glpi#7507]
**Describe the bug**

In tickets Rules, in actions when you choose "SLA Time to resolve" this error appears :

_Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in C:\xampp\htdocs\9.5\glpi95rc2\inc\dropdown.class.php on line 157 in C:\xampp\htdocs\9.5\glpi95rc2\inc\dropdown.class.php at line 278_

**To reproduce**

1. Go to Tickets rules
2. Click on actions
3. Choose "SLA Time to resolve" in the dropdown

**Screenshots**

![image](https://user-images.githubusercontent.com/39367117/86133439-913b8f00-bae8-11ea-80bd-de8cbfb29e4c.png)

**Comment by trasher** [comment]
Please provide full  stack tace from logs

**Comment by cedric-anne** [comment]
Hi @keha35 ,

Can you check with #7508 ?

Regards
