### ISSUE TITLE
GLPI - OCS Inventory Plugin: Softwares not associated with Computers

### ISSUE THREAD

**Issue by asm19** [glpi-project/glpi#7509]
Hello,

I am testing the OCS Inventory plugin with version 9.5rc2 and it is working but I have a problem. When I open a computer, it does not have any associated software. The software being imported into the software category but it is not associated with computers:

The version of your GLPI: 9.5rc2
The version of the plugin: 1.7.0

![image](https://user-images.githubusercontent.com/1648981/86137420-2ccb0080-bae5-11ea-9f33-5cb61fc6a551.png)

![image](https://user-images.githubusercontent.com/1648981/86137530-4a986580-bae5-11ea-9064-4b1e28fa6d8c.png)

In the plugin settings the software is active:

![image](https://user-images.githubusercontent.com/1648981/86138119-f04bd480-bae5-11ea-9c5b-7e7f5448c94d.png)

Is this a bug in the plugin or GLPI?

Thank you

**Comment by trasher** [comment]
We cannot know. Since adding a software to a computer works fine from the fusioninventory plugin, I guess the problem is rather on the plugin side (changes has been made on 9.5 on softwares).
You should check your logs also, if something went wrong, there are chances to find extra info in them).
