### ISSUE TITLE
[RC feedback] Renaming a Dashboard is not persistent after login

### ISSUE THREAD

**Issue by viktor-sc** [glpi-project/glpi#7510]
**Describe the bug**

Renaming a dashboard won't last after logging out and logging in again

**To reproduce**

1. In version 9.5 RC2, edit a dashboard (like 'central' or an own one) and change the name of it. Save.
2. Toggle edit mode. The name seems to be accepted for the whole session.
3. Logout and login again
4. The old name appears again.

**Expected behavior**

A changed name should remain after logging in again.

**Comment by cconard96** [comment]
Can you check to see if making the change in the linked PR fixes the issue for you?

**Comment by viktor-sc** [comment]
Hi,
after changing title to name in the file the issue seems to be fixed for me.
Thanks!
