### ISSUE TITLE
Dashboard - SIMCard Item wrong url

### ISSUE THREAD

**Issue by asm19** [glpi-project/glpi#7547]
In the dashboard the SIMCard icon, the link does not appear correct: http://XXXXXXXXX/front/item_device.php?itemtype=Item_DeviceSimcard?reset

It seems to me that the correct link is: http://XXXXXXXXX/front/item_device.php?itemtype=Item_DeviceSimcard

**Version**: 9.5RC2

![image](https://user-images.githubusercontent.com/1648981/86333838-59495e80-bc44-11ea-9d39-c349acfff2d2.png)

![image](https://user-images.githubusercontent.com/1648981/86334177-c826b780-bc44-11ea-8387-fa6fc579fd75.png)

**Comment by cedric-anne** [comment]
Hi,

#7592 should fix this issue.

Regards
