### ISSUE TITLE
Question about CommonDBTM::check() function

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#755]
Hello,

There is something that seems strange to me:
The `CommonDBTM::check()` method is called in the `$this` context (as it is not a static method), and there is a call to `getFromDB($ID)` which reloads the object from DB even if object is already loaded.
For me we should optimize this behavior with a test to prevent reload of object from DB when object is already loaded.
Do you agree?

regards,
Tomolimo

**Comment by tomolimo** [comment]
up!

**Comment by trasher** [comment]
Hello, I agree :)
I guess we could look if the id field is set before calling getFromDB().

**Comment by btry** [comment]
Hi

The fix looks good to me.

**Comment by tomolimo** [comment]
Thank you
