### ISSUE TITLE
[0.90.1-3] Permission denied

### ISSUE THREAD

**Issue by fsimplice** [glpi-project/glpi#756]
From scratch on **0.90.3**,
1 - Add an email to glpi user
2 - Enable notification service
3 - Create Ticket > **Type : Request**
4 - In **'Assigned to'** field, **choose '-----'**,
5 - Add a Title and a description
6 - Confirm the request 

Once the request is submitted, 
a. You **can't disabled** the email followup
b. You **can't delete** the email

![glpi](https://cloud.githubusercontent.com/assets/4199718/16229732/5d4dfe96-37be-11e6-84f6-386afc2caf7e.png)

This issue appeared since 0.90.1.

NB:
On version **< 0.90.1** or on **'incident' ticket type**, when you choose '-----' the **email field is cleared**.

**Comment by tomolimo** [comment]
Hello,
Could you send your GLPi configuration (in 'Setup menu > General option > System tab')?
You may copy/paste lines from `[code]` to `[/code]`.
Thank you
Regards,
Tomolimo

**Comment by fsimplice** [comment]
### Information about system installation and configuration

GLPI 0.90.3 (/glpi-0.90.3 => C:\wamp\apps\glpi-0.90.3)

### Server

Operating system: Windows NT D0175 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) AMD64
PHP 5.5.12 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2, calendar, com_dotnet,
	ctype, curl, date, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap, json, ldap, libxml, mbstring,
	mcrypt, mhash, mysql, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, session, shmop, soap, sockets, sqlite3,
	standard, tokenizer, wddx, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="3M" safe_mode="" session.save_handler="files"
	upload_max_filesize="64M" 
Software: Apache/2.4.9 (Win64) PHP/5.5.12 (Apache/2.4.9 (Win64) PHP/5.5.12 Server at localhost Port 80)
	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0
Server Software: MySQL Community Server (GPL)
	Server Version: 5.6.17
	Server SQL Mode: NO_ENGINE_SUBSTITUTION
	Parameters: root@127.0.0.1:3307/glpi_0_90_3
	Host info: 127.0.0.1 via TCP/IP
	
OKC:\wamp\apps\glpi-0.90.3/config : OK
OKC:\wamp\apps\glpi-0.90.3/files : OK
OKC:\wamp\apps\glpi-0.90.3/files/_dumps : OK
OKC:\wamp\apps\glpi-0.90.3/files/_sessions : OK
OKC:\wamp\apps\glpi-0.90.3/files/_cron : OK
OKC:\wamp\apps\glpi-0.90.3/files/_graphs : OK
OKC:\wamp\apps\glpi-0.90.3/files/_lock : OK
OKC:\wamp\apps\glpi-0.90.3/files/_plugins : OK
OKC:\wamp\apps\glpi-0.90.3/files/_tmp : OK
OKC:\wamp\apps\glpi-0.90.3/files/_rss : OK
OKC:\wamp\apps\glpi-0.90.3/files/_uploads : OK
OKC:\wamp\apps\glpi-0.90.3/files/_pictures : OK
OKC:\wamp\apps\glpi-0.90.3/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK

### Libraries
htmLawed version 1.1.21 in (C:\wamp\apps\glpi-0.90.3\lib\htmlawed)
phpCas version 1.3.4 in (C:\wamp\apps\glpi-0.90.3\lib\phpcas)
PHPMailer version 5.2.8 in (C:\wamp\apps\glpi-0.90.3\lib\phpmailer)
ZetaComponent ezcGraph installed in (C:\wamp\apps\glpi-0.90.3/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (C:\wamp\apps\glpi-0.90.3\lib\Zend)
SimplePie version 1.3.1 in (C:\wamp\apps\glpi-0.90.3\lib\simplepie)
TCPDF version 6.2.12 in (C:\wamp\apps\glpi-0.90.3\lib\tcpdf)
ircmaxell/password-compat in (C:\wamp\apps\glpi-0.90.3\lib\password_compat). Compatitility: Ok

### Mysql replicas
Not active

### Notifications
Way of sending emails: PHP

### Mails receivers

### Plugins list

**Comment by orthagh** [comment]
I can't retrieve the commit who fix this issue.
But, it's already fixed in upcoming 9.1 version (we will release soon).
