### ISSUE TITLE
Problem with planning

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#757]
Profile rights: see only my planning
In planning display form, i can choose user (other than me), all user of a group and groups

I am on a parent entity (not recursively) - Task  created on a sub entity
I can see the task planned but error of right when i click on it to open

I am on a sub entity - Task created on a parent entity
I can see the task planned but error of right when i click on it to open

**Comment by yllen** [comment]
For groups, i can add all groups (even recursive one), not only my groups

**Comment by orthagh** [comment]
Hello @yllen 
Maybe we could close this issue.
I think it applied to 0.90.6 not to 9.1.

I close for the moment, reopen if you think it's still valid
