### ISSUE TITLE
Bugs in dbmysql.class.php

### ISSUE THREAD

**Issue by ahellingil** [glpi-project/glpi#7578]
I have version 9.3.1. When I activate **debug mode**, the /front/central.php shows the exception:
**PHP Notice: Trying to get property 'num_rows' of non-object in /var/www/html/tilena/inc/dbmysql.class.php at line 285
PHP Notice: Trying to get property 'num_rows' of non-object in /var/www/html/tilena/inc/dbmysql.class.php at line 285
PHP Notice: Trying to get property 'num_rows' of non-object in /var/www/html/tilena/inc/dbmysql.class.php at line 285
PHP Notice: Trying to get property 'num_rows' of non-object in /var/www/html/tilena/inc/dbmysql.class.php at line 285**

Viewing that PHP file, I see that if any application page calls the method numrows($result) with null $result, the app crashes.
Then, I suggest to change:
```
   function numrows($result) {
	return $result->num_rows;
   }
```
To:
```
   function numrows($result) {
	 if ($result) {
		return $result->num_rows;
	 } else {
		return 0;
	 }
   }
```
The same should be done with **fetch_array(), fetch_row(), fetch_assoc(), fetch_object(), data_seek(), field_name() and free_result()**.

**Comment by trasher** [comment]
I do not agree. `numrows` should not be called if the result does not exists.

Also, you should probably consider upgrading.

Regards.
