### ISSUE TITLE
Tasks with past due-date don't appear in Central view 

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#758]
Hello
Use-case: imagine that some tasks assigned to tech X were scheduled yesterday (or even before), as these tasks will not appear on 'Central' planning view, X will not be alerted for late tasks.

In previous GLPi version it was possible to add them via a plugin (and to show them in RED as late tasks), this is no longer possible due to FullCalendar which filters the tasks with the current day date.

Example of what was possible in 0.83:
![image](https://cloud.githubusercontent.com/assets/7569958/16258348/c25d0b16-385d-11e6-8213-f755b05faf1d.png)

Could it be possible to fix this?

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Could be that the fix is something like http://fullcalendar.io/docs/views/Custom_Views/

**Comment by orthagh** [comment]
I do a little search this morning on customview. In fact, it seems possible but need a big work to glue pieces together.
At bottom of this file (a fork of fullcalendar), you'll find an implementation of a listview : 
https://raw.githubusercontent.com/stephenharris/Event-Organiser/master/js/fullcalendar.js

I think we can be inspired by this code (who is compatible with 2.2.3) to do a custom view.

Another easier option, is to code a simple php list of events.
After my serach, this morning, i think it's a better option

**Comment by tomolimo** [comment]
We may get something like this:
![image](https://cloud.githubusercontent.com/assets/7569958/16487742/f77ef744-3ecc-11e6-9af9-1c4937c2be91.png)
I don't know why the left border is missing...

**Comment by tomolimo** [comment]
Hello,
There is a big caveat to the used listview (listYear): the past-due tasks are only seen if they are due in the current year.
...
Regards,
Tomolimo

**Comment by orthagh** [comment]
Hello @tomolimo

I started worked today, on a new version with a better listview.
In addition of listYear, fullcalendar added in 3.0.0 version a range customizable list view
I need to tweak some details but here the pros/cons:
- new "FullList" can display a time defined range, i set 4 years in my current version
- by default (and in Assistance > Planning page), date range starts on today year (2016-01-01) and so finish 4 years after (2020-01-01)
- for index planning list, i set starting date at -2years: 2014-01-01 to 2018-01-01
- i need to fix the title for this new view

So it's better, but not completely satisfying. I'm currently searching for a way to tweak the param start sended by fullcalendar and set it to 1970 for example.

I plan also an update of the lib, we have a new 3.0.1 versions with somes fixes.

**Comment by tomolimo** [comment]
ok, thank you
