### ISSUE TITLE
[9.5.0-rc2] split screen: Attached Image in Followup problem.

### ISSUE THREAD

**Issue by Pieurre** [glpi-project/glpi#7580]
Hello,

I'm having a problem with the images in the follow-ups.

When I open it, the left side of the split is highlighted and the image I open is underneath:

Ticket:
![image](https://user-images.githubusercontent.com/6872020/86360417-9f1d1b80-bc72-11ea-8c0b-1953c08374f0.png)

clic on the image on the follow up:

![image](https://user-images.githubusercontent.com/6872020/86360480-bd831700-bc72-11ea-9333-066735bd87a9.png)

Thanks :)

**Comment by cedric-anne** [comment]
Hi,

Maybe the root cause of the problem is same as in #7194 .

Regards
