### ISSUE TITLE
Error attaching .png file

### ISSUE THREAD

**Issue by jorgecamargosdb** [glpi-project/glpi#7582]
I upgraded the GLPi from Version 9.4.5 to 9.4.6 and noticed that when trying to attach .png files it presents the error "Error resizing the image (auto_orient)"

![image](https://user-images.githubusercontent.com/23311692/86365811-5f453c80-bc50-11ea-8f28-8275e7a6dea3.png)

--------- GLPi Setup----------
 
GLPI 9.4.6 ( => /usr/share/glpi)
Installation mode: TARBALL

Operating system: Linux vps20462.publiccloud.com.br 3.10.0-1127.10.1.el7.x86_64 #1 SMP Wed Jun 3 14:28:03 UTC 2020 x86_64
PHP 7.1.33 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.6 (CentOS) PHP/7.1.33 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.2.32-MariaDB
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
xml extension is installed
ldap extension is installed
imap extension is installed
Zend OPcache extension is installed
APCu extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
Database version seems correct (10.2.32) - Perfect!Database version seems correct (10.2.32) - Perfect!
OK/usr/share/glpi/files/_log : OK
OK/usr/share/glpi/config : OK
OK/usr/share/glpi/files : OK
OK/usr/share/glpi/files/_dumps : OK
OK/usr/share/glpi/files/_sessions : OK
OK/usr/share/glpi/files/_cron : OK
OK/usr/share/glpi/files/_graphs : OK
OK/usr/share/glpi/files/_lock : OK
OK/usr/share/glpi/files/_plugins : OK
OK/usr/share/glpi/files/_tmp : OK
OK/usr/share/glpi/files/_cache : OK
OK/usr/share/glpi/files/_rss : OK
OK/usr/share/glpi/files/_uploads : OK
OK/usr/share/glpi/files/_pictures : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Permissive
OKSELinux boolean configuration for httpd_can_network_connect --> on
OKSELinux boolean configuration for httpd_can_network_connect_db --> on
OKSELinux boolean configuration for httpd_can_sendmail --> on

**Comment by cedric-anne** [comment]
Hi,

Please provide logs.

Regards

**Comment by jorgecamargosdb** [comment]
Hello, I decided applying chmod 777 in / files

Thanks

**Comment by cedric-anne** [comment]
777 is never a good idea :/
