### ISSUE TITLE
ticket capture via email

### ISSUE THREAD

**Issue by wesleyfernandocabrera** [glpi-project/glpi#7585]
**when the call comes via email the images that are added to the body of the email do not load into glpi*

**Page(s) URL

**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots
![image](https://user-images.githubusercontent.com/67604147/86466470-118d0a80-bd0a-11ea-996c-324c69082f2e.png)

**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

Please fill all requested informations (glpi version, logs, system informations, ...).

Regards

**Comment by wesleyfernandocabrera** [comment]
hello all right, below the items

version 9.5 RC2 
![image](https://user-images.githubusercontent.com/67604147/86468645-3c795d80-bd0e-11ea-9576-8d836e642e5a.png)

PHP 7.3 
![image](https://user-images.githubusercontent.com/67604147/86468620-2b305100-bd0e-11ea-9ea5-1ba733e7588c.png)

MYSQL
![image](https://user-images.githubusercontent.com/67604147/86468740-7185b000-bd0e-11ea-9d0b-4694814ef423.png)

HTTPD
![image](https://user-images.githubusercontent.com/67604147/86468855-a7c32f80-bd0e-11ea-9753-b5a9603e75fc.png)

Logs
[remove.txt](https://github.com/glpi-project/glpi/files/4869668/remove.txt)
[php-errors.log](https://github.com/glpi-project/glpi/files/4869659/php-errors.log)
[cron.log](https://github.com/glpi-project/glpi/files/4869660/cron.log)
[event.log](https://github.com/glpi-project/glpi/files/4869661/event.log)
[mail.log](https://github.com/glpi-project/glpi/files/4869662/mail.log)
[mail-error.log](https://github.com/glpi-project/glpi/files/4869663/mail-error.log)
[mailgate.log](https://github.com/glpi-project/glpi/files/4869664/mailgate.log)
[migration_to_9.5.0.log](https://github.com/glpi-project/glpi/files/4869665/migration_to_9.5.0.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/4869666/php-errors.log)
[warning_during_migration_to_9.5.0.log](https://github.com/glpi-project/glpi/files/4869667/warning_during_migration_to_9.5.0.log)

**Comment by cedric-anne** [comment]
It would be helpful if you can just provide logs related to mailgate crontask execution.

**Comment by wesleyfernandocabrera** [comment]
which log do you want, so I can get the correct one

**Comment by cedric-anne** [comment]
All the logs that may be generated by this task, but only them. You give logs from 2020-07-02 4pm to 2020-07-03 9am, it is hard to know if there is any log related to this task execution.

**Comment by wesleyfernandocabrera** [comment]
[cron.log](https://github.com/glpi-project/glpi/files/4869893/cron.log)

would be this?

**Comment by wesleyfernandocabrera** [comment]
[php-errors.log](https://github.com/glpi-project/glpi/files/4869899/php-errors.log)


or this? I deleted the logs and generated the tasks again

**Comment by cedric-anne** [comment]
Logs says that you have permissions errors. Can you give read and write permissions to the webserver user to `/sistemas/glpi/files` directory and all its childs, make sure to run crontasks using the webserver user, and check if it fixes your issue ?

**Comment by wesleyfernandocabrera** [comment]
![image](https://user-images.githubusercontent.com/67604147/86474171-a72f9680-bd18-11ea-818b-271418b3826c.png)

hello I already gave permission -R 777 for all files in the folder

**Comment by trasher** [comment]
`777` is **never** a good solution. Please review ACLs correctly.

**Comment by wesleyfernandocabrera** [comment]
reviewed it, still has the same problem

**Comment by trasher** [comment]
If logs are still saying there is a permission problem, then you probably have missed something; there is nothing we can do to fix your installation.

**Comment by trasher** [comment]
BTW, just saw you've checked right on wrong place. right smust be fixed on `files` directory, not inc or anything else into it. Read the documentation, GLPI requires write access on files dir only, except at install it also requires write access to config dir.

This is not a glpi issue, closing.
