### ISSUE TITLE
9.5.2-rc2. Percentage completed of the task is not changed to 100% in kanban view mode

### ISSUE THREAD

**Issue by andersonprante** [glpi-project/glpi#7589]
When some project task (in kanban view mode) is moved to "closed" column. Percentage completed of the task is not changed to 100%.

**Comment by cconard96** [comment]
The Kanban only updates the status when you move a card to a different column. It is the same as changing the status in the form view. This functionality doesn't seem to have existed in the form view.

**Comment by andersonprante** [comment]
You're right, but makes sense if the task is closed, i think that was done 100%, or not?

**Comment by cconard96** [comment]
I agree, but this couldn't be a part of 9.5.0 since it already is in RC (bug fixes only). I am working on implementing this for the next version if the core GLPI devs agree with this functionality. @trasher If agreed on, please assign me to this feature request.

**Comment by cedric-anne** [comment]
Hi,

IMHO, closing a task may be done when a task is abandonned, not only when it is completed. In this case, changing its progress to 100% is not relevant.

By the way, I do not know if closed tasks completion pecentage is used somewhere, but maybe it should not. If a task is closed (completed or abandonned), then the project completion should consider that no more job is required for it. So maybe this problem should be taken from the other end.

Regards

**Comment by cconard96** [comment]
I have two thoughts about that.
Either GLPI prompts the user if they want to set the percentage to 100%, or we add a way to identify states that are completed vs abandoned. There is an "is_finished" field on states which sounds to me like the task or project has been completed. For anything abandoned, I would have just deleted it but I can see how having an active record of an abandoned task or project may be useful.

In either case, I think the Kanban needs to give the user the ability to change the percentage done from that view without having to open the item. I've already added this to my list of things to do for phase 2 of the Kanban.
