### ISSUE TITLE
Knowledge Base don't accept Source Codes (XML) in their content - even adding codesnippet into TinyMCE

### ISSUE THREAD

**Issue by Gambware** [glpi-project/glpi#7590]
Hi Guys, 

We need to insert some XML code into our KB on GLPI - (We are creating Zabbix Templates XML repository in GLPI KB)
I could verify there isn't  codesnippet button into TinyMCE editor. After some changes into html.class.php and adding TinyMCE plugin called codesamples, We enabled the button codesnippet into TinyMCE. as the image below

![image](https://user-images.githubusercontent.com/24397740/86524239-781b4100-be4e-11ea-806d-361d77d2ad20.png)

even add and work the codesample plugin 

![image](https://user-images.githubusercontent.com/24397740/86524252-9aad5a00-be4e-11ea-8526-12e531ed8578.png)

![image](https://user-images.githubusercontent.com/24397740/86524256-ab5dd000-be4e-11ea-8206-037ff6fdf9f4.png)

When save the KB, everything stay messed

![image](https://user-images.githubusercontent.com/24397740/86524275-f4ae1f80-be4e-11ea-93a2-215ae89f501d.png)

There is anyway to solve this ? Cause it will be usefull use the KB as a SourceCode repository. 

Thanks advandes

**Comment by cedric-anne** [comment]
Hi,

This is a know problem, but fixing it is really complicated as it will require lot of changes on either core and plugin changes, and maybe a painfull migration for everyone.

I tried a fix on #6111, but I was not able to provide a bulletproff migration, so it wa abandonned for now.

Problem is same as #140, so I close this issue.

Regards
