### ISSUE TITLE
[9.5 RC] addme_observer doesn't work on problems & changes

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7591]
![image](https://user-images.githubusercontent.com/13178158/86575166-23bfb080-bf77-11ea-8547-5b83bae9fba6.png)

The link addme_observer doesn't work on problems & changes.

GLPI launch a new problem / change form and don't update the item

**Comment by cedric-anne** [comment]
Hi,

I tried to create a problem and a change and assign them to me and it works. Can you give us a precise context to reproduce this issue ?
Can you also check logs and javascript console ?

Regards

**Comment by cedric-anne** [comment]
I misread the issue. Indeed, there is a bug on the button to add self as observer. I was trying on assignment button.

#7595 should fix this.
