### ISSUE TITLE
self-signed certificates for smtp are rejected 

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#760]
Example of log :   
```
*** PHP Warning(2): stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```

Maybe, we could add an option (disabled by default) to smtp setting to disable phpmailer checks.
Ex : 
```php
if ($CFG_GLPI['smtp_dont_check_certificate']) {
   $this->SMTPOptions = array(
                               'ssl' => array(
                                   'verify_peer' => false,
                                   'verify_peer_name' => false,
                                   'allow_self_signed' => true
                               ));
}
```

**Comment by satyan01** [comment]
not fixed the issue is the same after upgrade

**Comment by orthagh** [comment]
Actually, this issue and #761 are not part yet of glpi.
It's a proposal.

I don't what you do by "after upgrade" but if you got the official glpi master version, it's not (yet) in

**Comment by satyan01** [comment]
I have modified directly files and it works. Thank you very much

**Comment by satyan01** [comment]
I knew that was included in glpi master

**Comment by orthagh** [comment]
Great !

**Comment by satyan01** [comment]
Maybe you could help me on another issue with fusioninventory, timeslot are not displayed
the issue is Uncaught ReferenceError: d3 is not defined

**Comment by satyan01** [comment]
I can't do network scan anymore due to this issue

**Comment by orthagh** [comment]
this is offtopic, but please test my version https://github.com/orthagh/fusioninventory-for-glpi and open issue here if needed
