### ISSUE TITLE
Count for problems /changes is empty for User / Group / Supplier

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7603]
Example :

I have a user which is an actor of changes / problems

From his detail form, we will see problems / changes  : 
![image](https://user-images.githubusercontent.com/13178158/86752526-b592f080-c03f-11ea-8af5-31452c3b2fb8.png)

But there is no count on tab : 
![image](https://user-images.githubusercontent.com/13178158/86752686-d22f2880-c03f-11ea-9037-00d8ff17138e.png)

this is a problem with https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/change_item.class.php#L228

(It's not use the good table - change_users etc)

**Comment by cedric-anne** [comment]
Hi,

Problem is also present on 9.4 branch.

Regards
