### ISSUE TITLE
Personal preferences: make 'results to display by page' offer higher numbers

### ISSUE THREAD

**Issue by Mexonizator** [glpi-project/glpi#7605]
Hello.

I'm using 9.4 and it's still not possible to choose the number in the personal preferences higher than 50. Which is very inconvenient as there's more than 50 comps and I have to manually set the number in 'Display (number of items)' on https://domain/front/computer.php page everytime I visit it.

So, I'd like to ask to add some numbers to the setting. Thanks.

**Comment by akoscomp** [comment]
You can change the limit in inc/config.class.php, row 339, list_limit_max, max => 200 to higher value.
