### ISSUE TITLE
auto assign user to manager when creating a project

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#7608]
Not the first time i was annoyed by that in my tests.
But when you creating a project, you're not pre-assigned to manager.

Immediate consequence, you cannot alter columns in kanban view.

Maybe, we can also set the manager fields as required.

Not urgent and not really blocking (as projects should have a manager), 9.5.0 will be released without, but can be ok to have the fix for 1st bugfixes version

**Comment by cconard96** [comment]
This should have already been done in 37310edca6e44d071a481e3b21d16203f9bf49b8. I'll have to look into it more later.

**Comment by cconard96** [comment]
I cannot recreate the issue on newest 9.5/bugfixes. Any project I make from the Kanban automatically makes me the manager.

**Comment by orthagh** [comment]
On a fresh install of the new 9.5 (with the archive) : 
![image](https://user-images.githubusercontent.com/418844/86885224-2b0cc880-c0f5-11ea-8b43-45c3fe44177b.png)

**Comment by trasher** [comment]
It concerns projects added from the standard way... Sounds like there is specific code when it's created from the global kanban view, that is not correct.

**Comment by cconard96** [comment]
Oh... I think I misunderstood. I thought the screenshot was of the regular Project form, but see that it is a new Project form. I did just have the Kanban take me that instead of creating the Project itself like it is supposed to.
