### ISSUE TITLE
[9.5.0] Network Interface connect: Undefined variable: Db

### ISSUE THREAD

**Issue by SerBep** [glpi-project/glpi#7617]
PHP Notice (8): Undefined variable: Db in /array/SITES/www/glpi/ajax/dropdownConnectNetworkPort.php at line 115
Uncaught Exception Error: Call to a member function request() on null in /array/SITES/www/glpi/ajax/dropdownConnectNetworkPort.php at line 115

Error, when connecting network interface to another network interface.

/glpi/front/networkport.form.php

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.0 
```

**Comment by cedric-anne** [comment]
Hi,

Can you check if #7632 fixes your issue ?

Regards

**Comment by SerBep** [comment]
Thanks! It's works.
