### ISSUE TITLE
[9.5.0] Cloned element in planning will not show up

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7622]
PHP 7.3.16 ; Centos 8.1 stable

Unwanted current behavior: 
When you right click on an event in the planning and clone, then no new event shows up.

Wanted proper behavior : 
A newly cloned element should show up

**Comment by orthagh** [comment]
Could you check in your browser's console (f12) if you have any javascript errors.

Do the same, with fs logs (sql-errrors.log ans php-errors.log)

**Comment by joomlafun** [comment]
No JS error nor php but in the SQL I have this

  *** MySQL query error:
  SQL: INSERT INTO `glpi_tickettasks` (`tickets_id`, `taskcategories_id`, `date`, `users_id`, `users_id_editor`, `content`, `is_private`, `actiontime`, `begin`, `end`, `state`, `users_id_tech`, `groups_id_tech`, `date_mod`, `date_creation`, `tasktemplates_id`, `timeline_position`, `sourceitems_id`, `uuid`) VALUES ('20', '1', '2020-07-08 07:58:28', '2', '0', '&lt;p&gt;S'assurer que le mobilier permet d'accueillir le matériel&lt;/p&gt;&lt;p&gt;S'assurer que suffisamment d'alimentations sont prévues&lt;/p&gt;&lt;p&gt;S'assurer que réseau électrique est disponible en fonction du matériel qui sera installé&lt;/p&gt;', '0', '3600', '2022-02-02 02:00:00', '2022-02-02 03:00:00', '0', '22', '0', '2020-07-08 07:58:28', '2020-07-08 07:58:28', '3', '1', '0', 'aac9e30c-1517-48cd-aaee-3553d71d28ea')
  Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'assurer que le mobilier permet d'accueillir le matériel&lt;/p&gt;&lt;p&gt;S'ass' at line 1
  Backtrace :
  inc/dbmysql.class.php:1125                         
  inc/commondbtm.class.php:602                       DBmysql->insert()
  inc/commondbtm.class.php:1139                      CommonDBTM->addToDB()
  inc/planning.class.php:1550                        CommonDBTM->add()
  ajax/planning.php:58                               Planning::cloneEvent()
  {"user":"2@it5.siteground.eu"}

**Comment by orthagh** [comment]
ok escaping issue so, thanks
