### ISSUE TITLE
[9.5.0] PHP Notice during upgrade

### ISSUE THREAD

**Issue by eiseli** [glpi-project/glpi#7626]
**Describe the bug**

During the migration from 9.1.3 to 9.5.0, we get a series of PHP errors where it complains about Undefined indexes. If you need any other information, don't hesitate to come back to me.

**Logs**

```
glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: notifications_ajax in /srv/glpi/9.5.0/inc/queuednotification.class.php at line 513
glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: notifications_mailing in /srv/glpi/9.5.0/inc/queuednotification.class.php at line 513
glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: translate_kb in /srv/glpi/9.5.0/inc/knowbaseitemtranslation.class.php at line 351
glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: use_notifications in /srv/glpi/9.5.0/inc/ticket.class.php at line 1495
```

**Comment by trasher** [comment]
Sounds like GLPI configuration is not loaded during web installer; which would cause those warnings.
This is annoying, but should not really be an issue; those are not needed at all for the process upgrade to work properly.
