### ISSUE TITLE
Empty block in header for self-service users

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#763]
![image](https://cloud.githubusercontent.com/assets/418844/16337530/828fd634-3a16-11e6-8fde-f360dd979b96.png)

**Comment by yllen** [comment]
<div id='header'> is never closed

**Comment by orthagh** [comment]
i disagree :) : https://github.com/glpi-project/glpi/blob/master/inc/html.class.php#L2214

**Comment by yllen** [comment]
id='header' opened line 2201
id='header_top' opened  line 2202
id='c_logo' opened line 2204 and closed line 2007
id='c_preference' opened line 2010 and closed line 2060
closed div from line 2066 is for id='header_top'
id='c_menu' opened line 2069
id='c_ssmenu2' opened line 2171 and closed line 2212
closed div from line 2214 is for id='c_menu' 

one closed div is missing
