### ISSUE TITLE
[GLPI 9.5]  automatic action "logs" no longer works

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#7633]
Hello,

I have returns by email that the automatic logs task poses a problem.
I run this task manually without debug mode, it remains on a blank page.

In debug mode I have this error :
Uncaught Exception Error: Call to a member function rowCount() on bool in /var/www/html/glpi/inc/crontasklog.class.php at line 67

Do you have the same problem with version 9.5 ?

**Comment by cedric-anne** [comment]
Hi,

Can you check on your GLPI logs to see if you have a SQL error ?

Regards

**Comment by steph461** [comment]
No SQL Error in the table glpi_logs

In the meantime, I am executing this request
DELETE FROM glpi_logs WHERE date_mod < NOW()-INTERVAL XX DAY;

**Comment by cedric-anne** [comment]
Can you check if #7634 fixes your issue ?

Regards

**Comment by steph461** [comment]
fix crontashlog.class.php  OK Problème Resolve
Thank you for the fix
