### ISSUE TITLE
[9.5.0] Unable to save impacts, control list in changes

### ISSUE THREAD

**Issue by ppenin** [glpi-project/glpi#7635]
**Describe the bug**

Unable to save impacts, control list in changes
Unable to save deployment plan, backup plan, checklist in changes
no action with Save button
Same issue with impacts, causes, symptoms in Problems

If applicable, page(s) URL where the bug happens.

https://glpi.domain.intra/glpi/front/change.form.php?id=1592
https://glpi.domain.intra/glpi/front/problem.form.php?id=738

1. Go to 'Changes' > Plans
2. Add text in Deployment plan aera or Backup Plan area or Checklist area
3. Click on 'Save'
4. Nothing happens

**Expected behavior**

text added in text area saved

**Screenshots**

![image](https://user-images.githubusercontent.com/22499638/87026739-7352e600-c1dc-11ea-9297-196779929166.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server

 
Operating system: Linux s001linux03 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="1000M" safe_mode="" session.save_handler="files"
	upload_max_filesize="1000M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at s001linux03.federation-saint-sauveur.priv Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Server Software: (Ubuntu)
	Server Version: 8.0.20-0ubuntu0.20.04.1
	Server SQL Mode: 
	Parameters: root@localhost/glpi
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (8.0.20) - Perfect!Database version seems correct (8.0.20) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

GLPI constants

 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_FORCE_NATIVE_SQL_TYPES: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 9.5.0
GLPI_SCHEMA_VERSION: 9.5.0
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2020

Libraries

 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.5 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.8 in (/usr/share/php/CAS/source)

LDAP directories

 
Server: 'ldaps://x.x.x.x', Port: '636', BaseDN: 'DC=domain,DC=intran', Connection filter: none, RootDN:
		'CN=Service,OU=Comptes de Services,OU=001,DC=domain,DC=intra', Use TLS: none

SQL replicas

 
Not active

Notifications

 
Way of sending emails: SMTP (glpi@domain.intra)

Mails receivers

 
Name: 'hotline@domain.intra' Active: Yes
	Server: '{x.x.x.x/pop/novalidate-cert/notls/debug}INBOX' Login: 'hotline-GLPI' Password: Yes
Name: 'support-qgr@domain.intra' Active: Yes
	Server: '{x.x.x.x/pop/novalidate-cert/notls/debug}INBOX' Login: 'support-QGR' Password: Yes

Plugins list

 
	barcode              Name: Barcode                        Version: 2.5.0      State: Enabled
	fields               Name: Champs supplémentaires         Version: 1.11.0     State: Installed / not activated
	timelineticket       Name: Chronologie des tickets        Version: 9.4+1.0    State: Installed / not activated
	datainjection        Name: Data injection                 Version: 2.7.1      State: Installed / not activated
	escalade             Name: Escalades                      Version: 2.5.0      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	flyvemdm             Name: Gestion d'appareil mobile Flyv Version: 2.0.0      State: To update
	pdf                  Name: Impression pdf                 Version: 1.6.0      State: Installed / not activated
	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.1      State: Enabled
	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.0      State: Installed / not activated
	mreporting           Name: Plus de rapports               Version: 1.7.0      State: Enabled
	reports              Name: Rapports                       Version: 1.13.1     State: Installed / not activated
	dporegister          Name: Registre DPO                   Version: 1.4        State: Installed / not activated
	dashboard            Name: Tableau de bord                Version: 0.9.8      State: Enabled

**Comment by trasher** [comment]
Any logs (glpi and/or system)?
Have you tried to with plugins disabled?

**Comment by trasher** [comment]
Thi also may be a javascript issue, check you browser developer tools console also.

**Comment by ppenin** [comment]
Tests made with Firefox 78.0.1, Google Chrome  83.0.4103.116, Internet Explorer 11
same result
no information in debug mode

below the last php error logs :

[2020-07-09 11:19:39] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Class 'DomainItem' not found in /var/www/html/glpi/plugins/fusioninventory/inc/agent.class.php at line 1045
  Backtrace :
  plugins/fusioninventory/inc/agent.class.php:1084   PluginFusioninventoryAgent->getAgentBaseURLs()
  plugins/fusioninventory/inc/agent.class.php:885    PluginFusioninventoryAgent->getAgentStatusURLs()
  ...s/fusioninventory/inc/agentwakeup.class.php:188 PluginFusioninventoryAgent->getStatus()
  inc/crontask.class.php:847                         PluginFusioninventoryAgentWakeup::cronWakeupAgents()
  front/crontask.form.php:49                         CronTask::launch()
  
[2020-07-09 11:26:19] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:26:23] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:26:25] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:26:30] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:26:32] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:27:01] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  front/cron.php:38                                  include()
  
[2020-07-09 11:27:03] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:27:11] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:27:12] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 11:27:19] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  plugins/fusioninventory/index.php:49               include()
  
[2020-07-09 12:09:09] glpiphplog.WARNING: Test logger

**Comment by ppenin** [comment]
everything works again after applying the fix
Thank's a lot
