### ISSUE TITLE
Unit tests failing with MariaDB 10.4 and 10.5

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#7640]
With MariaDB 10.5, on both github actions and circleci, functional tests never ends on Search class (Circle closes after 10 min timeout, github actions never ends).

**Comment by trasher** [comment]
Hum, looks like this is not related to MariaDB 10.5, I still have fails with 10.4. I do not undestand what goes wrong :-/

I've not been able to see which tests causes this fail, we'll have to investigate.

**Comment by cedric-anne** [comment]
This has been fixed.
