### ISSUE TITLE
Log-in with multiple LDAP takes too long

### ISSUE THREAD

**Issue by eiseli** [glpi-project/glpi#7644]
**Describe the bug**

When logging in with the authentication sources drop-down turned off in the general setup, it takes around 10 seconds to log in.

**Page(s) URL**
/index.php

**To reproduce**

1. We have around 50 different active LDAP sources configured in /front/authldap.php
2. We turned off the authentication sources drop-down on the login screen because that would be too complicated for the users to select the correct one.
3. When we create a user, his profile gets filled with the correct LDAP directory source and also lists the complete user DN.
4. When the user logs in with his correct credentials, the system cycles through all available LDAP sources until the right one is found, although it is already saved in his profile. 

**Expected behavior**

If the LDAP source is missing it is correct that the system needs to cycle through all the available LDAP sources. However, in our case, it should directly try with the saved source.

**Quick fix**

Feel free to adapt it to your coding standards :)

```
diff -u auth.class.bak.php auth.class.php
--- auth.class.bak.php  2020-07-07 12:30:18.000000001 +0200
+++ auth.class.php      2020-07-09 16:54:40.910441358 +0200
@@ -713,6 +713,13 @@
             $authtype = self::EXTERNAL;
             $this->user->fields["authtype"] = self::EXTERNAL;
          }
+      } else if (empty($login_auth) ) {
+         $_user = $this->user->getFromDBbyName($login_name); // Returns associative array
+         if( is_array($_user) && $_user['authtype'] != 0 ) {
+            $authtype = $_user['authtype'];
+            $this->user->fields["authtype"] = $_user["authtype"];
+            $this->user->fields["auths_id"] = $_user["auths_id"];
+         }
       }
       if (!$noauto && ($authtype = self::checkAlternateAuthSystems())) {
          if ($this->getAlternateAuthSystemsUserLogin($authtype)
```

**Comment by eiseli** [comment]
I think this is wrongly labelled as enhancement, it should be a bug fix, because it is a regression compared to version version 9.3-RC1

I believe it got broken with the following change: "Manage accounts on sources (#3585)"

This code is still there, but doesn't work.:

[auth.class.php#L734](https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/auth.class.php#L734)
```
//User has already authenticate, at least once : it's ldap server if filled
if (isset($this->user->fields["auths_id"])
    && ($this->user->fields["auths_id"] > 0)) {
   $authldap = new AuthLdap();
   //If ldap server is enabled
   if ($authldap->getFromDB($this->user->fields["auths_id"])
       && $authldap->fields['is_active']) {
      $ldapservers[] = $authldap->fields;
   }
} else { // User has never beeen authenticated : try all active ldap server to find the right one
```

**Comment by trasher** [comment]
I did not undersdood this was working before; I do not know this part, and the change you initially suggest was not like a fix (and since you've pointed there is existing code, proposed fix is at least incomplete). Label does not really matter anyways,, even if this was not existing before, this specific one certainly should be added "quickly".

Best way to propose a fix is to open a pull request, that will run existing tests.

**Comment by cedric-anne** [comment]
Hi,

#9540 should enhance login time when there are many LDAP sources.

Regards
