### ISSUE TITLE
[9.5.0] Market place says "votre enregistrement glpi network n'est pas valide" with proper key

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7645]
//PHP 7.3.16 ; Centos 8.1 stable
//error logs below

Unwanted current behavior:
-On GLPI network I use the "copy button" from the registration page to get the key in order to place it in configuration>general>glpi network
The key is then said to be valid, but if I click on any tab from the market place I get the following error
![image](https://user-images.githubusercontent.com/63743077/87075370-82f41e00-c220-11ea-9ceb-4dd69060de8f.png)
Then if I return in the configuration it now says that the key is not valid.

Wanted proper behavior :
No error should be visible as the key is said to be valid on the glpi network site.

logs return : 
 [2020-07-09 12:58:46] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 2 passed to Glpi\Marketplace\View::getPaginationHtml() must be of the type int, string given, called in /home/newsurf9/glpidemo1/ajax/marketplace.php on line 107 in /home/newsurf9/glpidemo1/inc/marketplace/view.class.php at line 844
  Backtrace :
  ajax/marketplace.php:107                           Glpi\Marketplace\View::getPaginationHtml()
  
[2020-07-09 12:59:30] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of GLPINetwork::getOffers() must be of the type array, null returned in /home/newsurf9/glpidemo1/inc/glpinetwork.class.php at line 295
  Backtrace :
  inc/marketplace/controller.class.php:315           GLPINetwork::getOffers()
  inc/marketplace/view.class.php:769                 Glpi\Marketplace\Controller->getRequiredOffers()
  inc/marketplace/view.class.php:486                 Glpi\Marketplace\View::getNetworkInformations()
  inc/marketplace/view.class.php:323                 Glpi\Marketplace\View::getPluginCard()
  inc/marketplace/view.class.php:272                 Glpi\Marketplace\View::displayList()
  ajax/marketplace.php:94                            Glpi\Marketplace\View::discover()

**Comment by cedric-anne** [comment]
Hi @joomlafun ,

Can you apply #7650 and check what is logged in your error log when you try to access to marketplace ?

Regards

**Comment by joomlafun** [comment]
Hi, I copied and pasted the 315 lines of #7650 ; however I now get an empty tab area with no options wether I go to configuration>general>glpi network or to the configuration>plugin tab.

But there are logs now however :)

[2020-07-10 04:56:18] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Unable to decrypt content in /home/glpi/inc/toolbox.class.php at line 296
  Backtrace :
  inc/glpinetwork.class.php:165                      Toolbox::sodiumDecrypt()
  inc/glpinetwork.class.php:180                      GLPINetwork::getRegistrationKey()
  inc/glpinetwork.class.php:243                      GLPINetwork::getRegistrationInformations()
  inc/marketplace/view.class.php:149                 GLPINetwork::isRegistered()
  inc/marketplace/view.class.php:192                 Glpi\Marketplace\View::checkRegister()
  inc/marketplace/view.class.php:115                 Glpi\Marketplace\View::installed()
  inc/commonglpi.class.php:637                       Glpi\Marketplace\View::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

**Comment by cedric-anne** [comment]
Did you update your security key ? This can explain your error.

#7653 should give you the ability to display the form to be able to save your key.
#7654 should fix the fact that the registration key is not updated when you change your security key.

**Comment by joomlafun** [comment]
No, this key matches the key I have on https://services.glpi-network.com/registration
But if I am the only one with the issue, maybe I just can contact glpi network to get a new key.

**Comment by cedric-anne** [comment]
You should apply #7653 and verify that the displayed key is correct.

**Comment by joomlafun** [comment]
Thanks for the help but I got this now in configuration>general>glpi network:
![image](https://user-images.githubusercontent.com/63743077/87160788-cd7aa680-c2c3-11ea-8a43-2829ada3e614.png)

In the logs : 

[2020-07-10 08:38:57] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Return value of GLPINetwork::getOffers() must be of the type array, null returned in /home/glpi/glpidemo1/inc/glpinetwork.class.php at line 295
  Backtrace :
  inc/marketplace/controller.class.php:315           GLPINetwork::getOffers()
  inc/marketplace/view.class.php:597                 Glpi\Marketplace\Controller->getRequiredOffers()
  inc/marketplace/view.class.php:453                 Glpi\Marketplace\View::getButtons()
  inc/marketplace/view.class.php:323                 Glpi\Marketplace\View::getPluginCard()
  inc/marketplace/view.class.php:272                 Glpi\Marketplace\View::displayList()
  ajax/marketplace.php:94                            Glpi\Marketplace\View::discover()
  
[2020-07-10 08:39:01] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 2 passed to Glpi\Marketplace\View::getPaginationHtml() must be of the type int, string given, called in /home/glpi/glpidemo1/ajax/marketplace.php on line 107 in /home/glpi/glpidemo1/inc/marketplace/view.class.php at line 844
  Backtrace :
  ajax/marketplace.php:107                           Glpi\Marketplace\View::getPaginationHtml()
  
[2020-07-10 08:39:03] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 2 passed to Glpi\Marketplace\View::getPaginationHtml() must be of the type int, string given, called in /home/glpi/glpidemo1/ajax/marketplace.php on line 107 in /home/glpi/glpidemo1/inc/marketplace/view.class.php at line 844
  Backtrace :
  ajax/marketplace.php:107                           Glpi\Marketplace\View::getPaginationHtml()

**Comment by cedric-anne** [comment]
Hi,

Seems that patch from #7650 is no longer present on your GLPI, first error should not happen when this patch is applied.

Regards

**Comment by joomlafun** [comment]
Hi,

The issue is gone in general>glpi network, it says my key is valid and it stays like that unlike before.

The issue remains on the market place though:
New logs using the #7650 patch 

[2020-07-18 05:27:41] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 2 passed to Glpi\Marketplace\View::getPaginationHtml() must be of the type int, string given, called in /home/glpi/glpidemo1/ajax/marketplace.php on line 107 in /home/glpi/glpidemo1/inc/marketplace/view.class.php at line 844
  Backtrace :
  ajax/marketplace.php:107                           Glpi\Marketplace\View::getPaginationHtml()

[2020-07-18 05:27:40] glpiphplog.ERROR: GLPINetwork::getRegistrationInformations() in /home/newsurf9/glpidemo1/inc/glpinetwork.class.php line 218
Unable to fetch registration informations. NULL {
    "message": "Too Many Attempts.",
    "exception": "Illuminate\\Http\\Exceptions\\ThrottleRequestsException",
    "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
    "line": 124,
    "trace": [
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/ThrottleRequests.php",
            "line": 53,
            "function": "buildException",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Routing\\Middleware\\ThrottleRequests",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 682,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 657,
            "function": "runRouteWithinStack",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 623,
            "function": "runRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php",
            "line": 612,
            "function": "dispatchToRoute",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 176,
            "function": "dispatch",
            "class": "Illuminate\\Routing\\Router",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 30,
            "function": "Illuminate\\Foundation\\Http\\{closure}",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/fideloper/proxy/src/TrustProxies.php",
            "line": 57,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Fideloper\\Proxy\\TrustProxies",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php",
            "line": 21,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php",
            "line": 27,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php",
            "line": 62,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 163,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php",
            "line": 53,
            "function": "Illuminate\\Pipeline\\{closure}",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php",
            "line": 104,
            "function": "Illuminate\\Routing\\{closure}",
            "class": "Illuminate\\Routing\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 151,
            "function": "then",
            "class": "Illuminate\\Pipeline\\Pipeline",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php",
            "line": 116,
            "function": "sendRequestThroughRouter",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        },
        {
            "file": "/var/www/services.glpi-network.com/public/index.php",
            "line": 57,
            "function": "handle",
            "class": "Illuminate\\Foundation\\Http\\Kernel",
            "type": "->"
        }
    ]
}  {"user":"2@it5.siteground.eu"}

**Comment by cedric-anne** [comment]
Hi,

I am not sure what you did exactly, but you hit the Marketplace API request limit, which is 60 requests per minute.

An explaination could be that your GLPI cache is not working properly. Are you using APCu ? Are files in `files/_cache` owned or writable by your webserver user ?

Regards

**Comment by joomlafun** [comment]
Maybe this is related to the following error I have on the marketplace page :
"Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /home/newsurf9/glpidemo1/inc/glpikey.class.php at line 102"

I did not have this in 9.5, only since 9.5.1

**Comment by cedric-anne** [comment]
Well,

The security key file is created on install/update process at almost the same moment than the database configuration file, and in the same directory. So if DB config file has been created, security key file should have been too.
Did you copied GLPI from another server/directory without the `config/glpi.key` file ?

Regards

**Comment by joomlafun** [comment]
Thank you for the explanation, 

I placed the security key of the backup that I had and I can now access the market place.

The bug is no more present so your patch was effective !

(if the security key was not present it is because I updated with an  outdated documentation on https://glpi-project.org/DOC/FR/glpi/admin_upgrade_prepare.html
I sent an email to glpi-project to correct it and add the infos about the config file.

Thanks a lot for your time cedric-anne !
