### ISSUE TITLE
[9.5.0] Plugin not showing in the plugin list when market place is activated

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7646]
//PHP 7.3.16 ; Centos 8.1 stable
//php logs below

Unwanted current behavior:
-Plugin not showing in the plugin list when marketplace is activated

Wanted proper behavior :
-Plugin to be visible in the plugin list

Steps to repeat:
Drag and drop an unzipped plugin folder in the plugin or in the marketplace folder; log in/log off ; the plugin will not show in the list of plugin to activate
Tried with 2 plugins : https://github.com/pluginsGLPI/fields/ and https://github.com/Probesys/glpi-plugins-groupcategory/

logs:
[2020-07-09 13:29:12] glpiphplog.ERROR: Plugin::getInfo() in /home/newsurf9/glpidemo1/inc/plugin.class.php line 1394
plugin_version_fields-master method must be defined!  {"user":"2@it5.siteground.eu"}

**Comment by trasher** [comment]
`plugin_version_fields-master` sounds strange to me. Are you sure you plugin directory is correctly named? For fields, it must be named `fields` for example (also be sure there is no other directory for this plugin, like `fields.backup`, which may lend to errors.

**Comment by joomlafun** [comment]
Ok sorry, this is my bad; the github download gave me the wrong file name.

**Comment by trasher** [comment]
Then you've probably downloaded the source archive, and not the release one; this may cause several other issues with some plugins.
