### ISSUE TITLE
[9.5.0] Invalid base URL! -Invalid API base URL!

### ISSUE THREAD

**Issue by aleadco** [glpi-project/glpi#7647]
**Describe the bug**

I have a stable GLPi 9.4.6 instance, I upgraded to 9.5 and I get below error in app url setting and api url.
![invalid base URL](https://user-images.githubusercontent.com/35962168/87113998-81851e80-c23d-11ea-9a43-4396d766a387.jpg)
![invalid API base URL](https://user-images.githubusercontent.com/35962168/87114006-8649d280-c23d-11ea-8fe3-2f545389239e.jpg)
For a moment I considered it was an error in the update and decided to install a new system from scratch, unfortunately I got the same error in the installation.
The logs do not indicate anything at the time of the error.
Any ideas.
Regards

**Comment by trasher** [comment]
Probably duplicates #7642; a failing URL is missing here.

**Comment by aleadco** [comment]
@trasher yes, exactly I have duplicated it, thank you very much
