### ISSUE TITLE
[9.5.0] logs crontask pending with error

### ISSUE THREAD

**Issue by tizianosartori** [glpi-project/glpi#7657]
When execute logs crontask I get this error in php-errors.log

`[2020-07-11 16:13:33] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function rowCount() on bool in /var/www/glpi/inc/crontasklog.class.php at line 67
`

The task still in execution state and do not terminate.

**Comment by ppenin** [comment]
Hello, it was solved in #7633

Regards,

**Comment by tizianosartori** [comment]
> Hello, it was solved in #7633
> 
> Regards,

Thank you!
