### ISSUE TITLE
0.90.1 to 0.90.3 : regression on number of items in timeline

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#766]
Hello,

I notice a regression between 0.90.1 and 0.90.3. See snapshots : 

**0.90.1** : you see number of items in timeline 
![0 90 1](https://cloud.githubusercontent.com/assets/10830260/16372819/1df39ca2-3c4f-11e6-914e-299fb18201cf.png)

**0.90.3** : you didn't see number of items in timeline, just "..." 
![0 90 3](https://cloud.githubusercontent.com/assets/10830260/16372848/3deda822-3c4f-11e6-953e-bcfd63c1cc1d.png)

**Comment by diogo-leal** [comment]
In english version the number of items works normally, but in portuguese happens this same error

**Comment by nqb** [comment]
I agree with @diogo-leal.

**Comment by orthagh** [comment]
Fixed
