### ISSUE TITLE
[9.5.0] User Groups restriction only include current group and parent

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7663]
//PHP 7.3.16 ; Centos 8.1 stable

Unwanted current behavior:
-When the option "view only my group tickets" is activated, then if you attribute the a ticket to third or fourth parent group who a user belong to, then the ticket will not show for the user.

Like A>B>C>D>User ; if the ticket is requested by group A or B, the user will not see it; only if ticket is requested by D or C, the user will see it.

Wanted proper behavior :
Show tickets for current groups and parents on any level for a user who belong to those groups.

**Comment by orthagh** [comment]
Hello.

I don't replicate the behavior.

I created 4 groups 
![image](https://user-images.githubusercontent.com/418844/87307042-3c047200-c519-11ea-931b-4793ca4d5315.png)
And set my user in the group D.

In my profile, i removed "View all tickets"
![image](https://user-images.githubusercontent.com/418844/87307129-5b9b9a80-c519-11ea-889b-c9550e0bc8d2.png)


When the ticket is assigned to another group than D, i do not see it.

Are you sure your user is not directly set in group C ?

Regards

**Comment by joomlafun** [comment]
> Are you sure your user is not directly set in group C ?
My user is in D and can view a ticket if it is attributed to D or C but not to A or B (I just made a test again)

Kind regards

**Comment by orthagh** [comment]
> My user is in D and can view a ticket if it is attributed to D or C but not to A or B (I just made a test again)

No point was : could you check your user is not a member also of group C ?

For us, the fact you see the tickets of group C and not a member of it is the bug.

**Comment by joomlafun** [comment]
Yes, he is a member of group C

**Comment by orthagh** [comment]
So it's the normal behavior, the option "see tickets of my groups" is for direct assignment not parent/child relation.

I close, feel free to comment if needed

**Comment by joomlafun** [comment]
Ok, good to know, thank you for your time Orthag.
