### ISSUE TITLE
[9.5.0] Group Action>Associate to a group removes all the current group of the user

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7664]
//PHP 7.3.16 ; Centos 8.1 stable

Unwanted current behavior:
-All groups get removed to add only the selected group to the user

Wanted proper behavior :
Preserver current groups & add the new group

**Comment by cedric-anne** [comment]
Hi,

I tried to reproduce and I was able to associate a group to a user in addition of existing ones.
Can you explain more precisely how to reproduce your issue ?

Regards

**Comment by joomlafun** [comment]
Hi,

1° Action
![image](https://user-images.githubusercontent.com/63743077/87287265-2e8bbf80-c4fa-11ea-87e1-ecf15f14614a.png)

2° Result on group page(wrong)
![image](https://user-images.githubusercontent.com/63743077/87287535-81657700-c4fa-11ea-976e-d4242bd3a3f4.png)

3° Result on user page(good)
![image](https://user-images.githubusercontent.com/63743077/87287763-c8ec0300-c4fa-11ea-980a-89a9059f6fd7.png)

Kind regards,

**Comment by cedric-anne** [comment]
When there is too many groups, only first is shown and this black "comments" icon is shown and can be clicked to view all groups related to the user.

So there is no bug here.

**Comment by cedric-anne** [comment]
You can change the max length displayed by changing the value of `Default characters limit (summary text boxes)` in general configuration of GLPI.

**Comment by joomlafun** [comment]
Sorry then, thank you for checking, thank you for your help.
