### ISSUE TITLE
SLK export Computer Asset - same component type with multiple components - wrong SLK format

### ISSUE THREAD

**Issue by Diamond2** [glpi-project/glpi#7670]
I'm using GLPI 9.4.6
When exporting the Asset->Computers which have multiple components with the same type

![Screenshot_391](https://user-images.githubusercontent.com/773739/87294383-e7b7bd00-c52d-11ea-932f-5d16a233f042.png)

Line break will appear in SLK file, that leads to wrong format and makes missing data. Below is SLK file openned by Notepad++, as you can see, line 150 doesn't have SLK format.

![Screenshot_390](https://user-images.githubusercontent.com/773739/87294446-05852200-c52e-11ea-8acd-554e2810286b.png)

In my screenshot, "SSD WD 500GB WDS500G2B0A" will be missed when open with Microsoft Excel or LibreaOffice Spreadsheet (Libre will silence the missing data while Microsoft will display the error/warning)

Thank you

**Comment by cedric-anne** [comment]
Hi,

I cannot find how a newline should be escaped in SLK format.
Have you an idea about this ?

Regards

**Comment by Diamond2** [comment]
It seems SLK doesn't have newline. I guess we can remove `newline` when exporting to SLK

thanks

**Comment by Diamond2** [comment]
Hello,


Here is newline character for SLK.
![Screenshot_402](https://user-images.githubusercontent.com/773739/87749820-e7683c00-c823-11ea-8e17-8251703b833b.png)


[search.class.php.zip](https://github.com/glpi-project/glpi/files/4935797/search.class.php.zip)

You can check and update it

Thanks

**Comment by trasher** [comment]
It is a bit late, fix has been published yesterday in 9.5.1.
I'm not sure such a change is really needed; but if you want that to be changed, feel free to open a pull request :)
