### ISSUE TITLE
Console commands dump core when not using mysqlnd driver

### ISSUE THREAD

**Issue by hfath** [glpi-project/glpi#7675]
On NetBSD 9 / PHP 7.3, an attempt to upgrade the database after upgrading to 9.5 results in

<pre>
# su -m httpd -c 'ktrace -di /usr/pkg/share/glpi/bin/console --config-dir=/etc/pkg/glpi db:update'
PHP Notice:  Constant GLPI_CONFIG_DIR already defined in /usr/pkg/share/glpi/config/local_define.php on line 9
PHP Notice:  Constant GLPI_CONFIG_DIR already defined in /usr/pkg/share/glpi/inc/downstream.php on line 9
PHP Notice:  Constant GLPI_CONFIG_DIR already defined in /etc/pkg/glpi/local_define.php on line 9
PHP Notice:  Constant GLPI_VAR_DIR already defined in /etc/pkg/glpi/local_define.php on line 12
PHP Notice:  Constant GLPI_LOG_DIR already defined in /etc/pkg/glpi/local_define.php on line 15
PHP Notice:  Constant GLPI_FONT_FREESANS already defined in /etc/pkg/glpi/local_define.php on line 23
PHP Notice:  Constant GLPI_SYSTEM_CRON already defined in /etc/pkg/glpi/local_define.php on line 26
PHP Warning:  Use of undefined constant MYSQLI_OPT_INT_AND_FLOAT_NATIVE - assumed 'MYSQLI_OPT_INT_AND_FLOAT_NATIVE' (this will throw an Error in a future version of PHP) in /usr/pkg/share/glpi/inc/dbmysql.class.php on line 213
PHP Warning:  mysqli::options() expects parameter 1 to be int, string given in /usr/pkg/share/glpi/inc/dbmysql.class.php on line 213
Segmentation fault (core dumped)
#
</pre>

When I upgrade through the web interface, it tells me to update timestamps, which again

<pre>
# su -m httpd -c '/usr/pkg/share/glpi/bin/console --config-dir=/etc/pkg/glpi glpi:migration:timestamps'
PHP Notice:  Constant GLPI_CONFIG_DIR already defined in /usr/pkg/share/glpi/config/local_define.php on line 9
PHP Notice:  Constant GLPI_CONFIG_DIR already defined in /usr/pkg/share/glpi/inc/downstream.php on line 9
PHP Notice:  Constant GLPI_CONFIG_DIR already defined in /etc/pkg/glpi/local_define.php on line 9
PHP Notice:  Constant GLPI_VAR_DIR already defined in /etc/pkg/glpi/local_define.php on line 12
PHP Notice:  Constant GLPI_LOG_DIR already defined in /etc/pkg/glpi/local_define.php on line 15
PHP Notice:  Constant GLPI_FONT_FREESANS already defined in /etc/pkg/glpi/local_define.php on line 23
PHP Notice:  Constant GLPI_SYSTEM_CRON already defined in /etc/pkg/glpi/local_define.php on line 26
PHP Warning:  Use of undefined constant MYSQLI_OPT_INT_AND_FLOAT_NATIVE - assumed 'MYSQLI_OPT_INT_AND_FLOAT_NATIVE' (this will throw an Error in a future version of PHP) in /usr/pkg/share/glpi/inc/dbmysql.class.php on line 213
PHP Warning:  mysqli::options() expects parameter 1 to be int, string given in /usr/pkg/share/glpi/inc/dbmysql.class.php on line 213
Segmentation fault (core dumped)
#
</pre>

The first login produces the warnings

<pre>
PHP Warning:  Use of undefined constant MYSQLI_OPT_INT_AND_FLOAT_NATIVE - assumed 'MYSQLI_OPT_INT_AND_FLOAT_NATIVE' (this will throw an Error in a future version of PHP) in /usr/pkg/share/glpi/inc/dbmysql.class.php on line 213
PHP Warning:  mysqli::options() expects parameter 1 to be int, string given in /usr/pkg/share/glpi/inc/dbmysql.class.php on line 213
</pre>

in bright red.

After that, everything looks normal, but there may of course be hidden breakage.

A gdb stack trace of the php core does not produce much, I would have to rebuild with debugging information and unstripped.

[ktrace.out.ascii.gz](https://github.com/glpi-project/glpi/files/4912598/ktrace.out.ascii.gz)

On a side issue, glpi/marketplace/plugins could not be created for lack of permission, and the ktrace shows glpi looking for glpi/tools.

**Comment by cedric-anne** [comment]
Hi,

First, the fact that your PHP does not know `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` is weird. It has been added in PHP on PHP 5.3.

Second, notices you have related to already defined constants seems to be caused by the fact that they are declared in multiple files (at least `GLPI_CONFIG_DIR` seems defined in `/etc/pkg/glpi/local_define.php`, `/usr/pkg/share/glpi/inc/downstream.php`, `/usr/pkg/share/glpi/config/local_define.php` and another file that is load prior to them.

Third, can you make sure to use the lastest version of PHP 7.3 ? We cannot do anything about segmentation faults, maybe it is a bug in PHP that has already been fixed.

Regards

**Comment by hfath** [comment]
The PHP installed is 

<pre>
% php --version
PHP 7.3.19 (cli) (built: Jul  1 2020 10:13:04) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.19, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.18, Copyright (c) 1999-2018, by Zend Technologies
%
</pre>

-- I see that 7.3.20 has just come out, but that shouldn't be necessary?

And where should `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` be defined? In base php, or in an extension?

**Comment by cedric-anne** [comment]
This constant is defined by `mysqli` extension but only when using the native driver `mysqlnd` (which is the default since PHP 5.4). So I guess you compiled your PHP using a different mysql driver.

It is possible for you to compileyour PHP using the default mysql driver ?

**Comment by hfath** [comment]
Hm. pkgsrc databases/php-mysqli wanted to be built with "mysqlnd" support, that takes care of the `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` issue.

php still cores - I had hoped that might be related, but it's not.

I might look into updating php to 7.3.20, and build unstripped/with debug symbols.

**Comment by hfath** [comment]
Is there any way to make `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` optional in glpi?

As it is, the www/php-glpi package would have to check that database/php-mysqli has been built with option "mysqlnd", and fail otherwise. This virtually ensures that there will not be a binary pkgsrc package for glpi, which sounds like a fairly steep price for (ATM) exactly one occurrence of the constant in the source tree.

**Comment by cedric-anne** [comment]
> Is there any way to make `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` optional in glpi?
> 
> As it is, the www/php-glpi package would have to check that database/php-mysqli has been built with option "mysqlnd", and fail otherwise. This virtually ensures that there will not be a binary pkgsrc package for glpi, which sounds like a fairly steep price for (ATM) exactly one occurrence of the constant in the source tree.

Hi,

We cannot make it optionnal, as it has an huge impact on how data is returned by database. Unfortunately, in GLPI, there is nothing to handle DB results casting on PHP side, and it would take years to add it in core and plugins. Having diffference on this would be a pain for developpers and would be really hard to handle in automated tests, and would surely result in tons of bugs.

Regards

**Comment by hfath** [comment]
On Thu, 16 Jul 2020 01:13:49 -0700, Cédric Anne wrote:
>> Is there any way to make `MYSQLI_OPT_INT_AND_FLOAT_NATIVE` optional 
>> in glpi?
>> 
>> As it is, the www/php-glpi package would have to check that 
>> database/php-mysqli has been built with option "mysqlnd", and fail 
>> otherwise. This virtually ensures that there will not be a binary 
>> pkgsrc package for glpi, which sounds like a fairly steep price for 
>> (ATM) exactly one occurrence of the constant in the source tree.
> 
> We cannot make it optionnal, as it has an huge impact on how data is 
> returned by database. Unfortunately, in GLPI, there is nothing to 
> handle DB results casting on PHP side, and it would take years to add 
> it in core and plugins. Having diffference on this would be a pain 
> for developpers and would be really hard to handle in automated 
> tests, and would surely result in tons of bugs.

Cédric,

thanks for the explanation.

I note that until now GLPI has worked fine without the "mysqlnd" option.

As the maintainer of the pkgsrc GLPI package, I will not at this point 
upgrade from 9.4.6, unless there is consensus on building php-mysqli 
with "mysqlnd" per default.

Cheerio,
Hauke

-- 
     The ASCII Ribbon Campaign                    Hauke Fath
()     No HTML/RTF in email            Institut für Nachrichtentechnik
/\     No Word docs in email                     TU Darmstadt
     Respect for open standards              Ruf +49-6151-16-21344

**Comment by cedric-anne** [comment]
> I will not at this point upgrade from 9.4.6, unless there is consensus on building php-mysqli with "mysqlnd" per default. Cheerio, Hauke

According to the documentation of PHP, it would be logical (for the end user) to have a `php-mysqli` built with mysqlnd by default:
![image](https://user-images.githubusercontent.com/33253653/87653161-6fcbdb80-c755-11ea-9360-5cdaf240012a.png)

But, as I do not really know how packaging is handled on pkgsrc, my opinion may be wrong.

**Comment by hfath** [comment]
On Thu, 16 Jul 2020 09:15:44 +0000 (UTC), Cédric Anne wrote:
> According to the documentation of PHP, it would be logical (for the 
> end user) to have a `php-mysqli` built with mysqlnd by default:
> 
![image](https://user-images.githubusercontent.com/33253653/87653161-6fcbdb80-c755-11ea-9360-5cdaf240012a.png)

Thanks for the pointer - I am not very familiar with database stuff, 
and would defer to others for a decision on what the php-mysqli 
package's defaults should be.

> But, as I do not really know how packaging is handled on pkgsrc, my 
> opinion may be wrong.

pkgsrc has traditionally been oriented towards building from source, in 
which case you can configure package options any way you like. But 
there is increasing weight on providing binary packages, which are 
built with the packages' default options; and in this case, the GLPI 
build would have to be failed.

Cheerio,
Hauke

-- 
     The ASCII Ribbon Campaign                    Hauke Fath
()     No HTML/RTF in email            Institut für Nachrichtentechnik
/\     No Word docs in email                     TU Darmstadt
     Respect for open standards              Ruf +49-6151-16-21344
