### ISSUE TITLE
[9.5] Unable to create newtorkports relations

### ISSUE THREAD

**Issue by tizianosartori** [glpi-project/glpi#7677]
**Describe the bug**
When opening the dropdown menu for networkports connection, no network cards are listed.

**Page(s) URL**
`/front/networkport.form.php?id=ID`

**To reproduce**
1. Go to '/front/networkport.form.php?id=ID'
2. Click on dropdown menu and select Network devices
3. Select a network device with network cards

**Expected behavior**
I expect network cards dropdown shown up.

**Logs**
`PHP Notice (8): Undefined variable: Db in /var/www/glpi/ajax/dropdownConnectNetworkPort.php at line 115
Uncaught Exception Error: Call to a member function request() on null in /var/www/glpi/ajax/dropdownConnectNetworkPort.php at line 115`

**Comment by cedric-anne** [comment]
Hi,

It has already been fixed. See #7617 

Regards

**Comment by tizianosartori** [comment]
Sorry, apparently I'm not lucky with the searches...
