### ISSUE TITLE
[0.90.3] Filtering not retained when the page changes in trash

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#768]
Hi,

In trash mode, the filtering is not retained when the page changes.
Here the example : 
![1](https://cloud.githubusercontent.com/assets/113057/16415549/1bab6516-3d3e-11e6-94b6-d7cd68104447.jpg)
![2](https://cloud.githubusercontent.com/assets/113057/16415553/2466c43e-3d3e-11e6-8df1-dc3f85e47f6e.jpg)

Tested with IE 11 and Chrome 51 on Windows 7 64 bits.
GLPI 0.90.3

Have you a solution to fix this issue ?

Thanks

**Comment by orthagh** [comment]
Hello @barbuslex 

Yes we have a solution:
See #589 and #593.
It should be fixed in future 0.90.4

**Comment by barbuslex** [comment]
Ok thanks !
