### ISSUE TITLE
Replace SLK exports

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#7686]
SLK exports are done manually on GLPI side, it maybe would be better to replace it with something like https://github.com/PHPOffice/PhpSpreadsheet

**Comment by cconard96** [comment]
SYLK writing is not supported by PhpSpreadsheet, just reading (See https://phpspreadsheet.readthedocs.io/en/latest/). Perhaps switching to XLSX would be better through this same library?
SYLK is quite old with many security concerns and to my knowledge, no UTF support.
