### ISSUE TITLE
[9.5.0] Wrong rights on lamina cache for ldap_mass_sync.php

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi#7695]
**Describe the bug**

On GLPI 9.5 when i use www-data to launch ldap_mass_sync.php i've an error message who say he don't can open a lamina cache file. 

**To reproduce**

1. su - www-data -s /bin/bash
2. cd /XXXX/XXXX/glpi/scripts/ && php ldap_mass_sync.php action=X ldapservers_id=X ldap_filter="${FILTRE_LDAP}"

**Expected behavior**

This is because the rights is by default "root:root" chmod 600. In GLPI 9.4.6 the rights is "www-data:www-data" chmod 600.
I would like to not use a root account to sync my LDAP with GLPI

**Logs**

```
Uncaught Exception Laminas\Cache\Exception\RuntimeException: Error opening file '/XXXX/XXXX/glpi/files/_cache/cache_trans/glpi_cache_trans_9.5.0c69de3d6bfa5159b3b6550ecb5c3ab2d-74/glpi_cache_trans_9.5.0c69de3d6bfa5159b3b6550ecb5c3ab2d-Laminas_I18n_Translator_Messages_e4f80f70980f9b99859a1330d2598e5c.dat' in /XXXX/XXXX/glpi/vendor/laminas/laminas-cache/src/Storage/Adapter/Filesystem.php at line 1581
```

Thank you

**Comment by trasher** [comment]
GLPI does not set ACLs on file. If your files are owned by `root:root`, then you've miusssed a chmod somewhere, or used root to call any script or cron.
