### ISSUE TITLE
[9.5.0] Upgrade error from 9.4.6 to 9.5.0: SQL Error "1118": Row size too large. 

### ISSUE THREAD

**Issue by laszlokertesz** [glpi-project/glpi#7697]
**Describe the bug**

When upgrading from version 9.4.6 to 9.5.0 at the upgrade section i get the followig error:

```
SQL Error "1118": Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs in query "ALTER TABLE `glpi_entities` ADD `suppliers_as_private` INT(11) NOT NULL DEFAULT '-2' "
9.5.0 multiple alter in glpi_entities - Error during the database query: ALTER TABLE `glpi_entities` ADD `suppliers_as_private` INT(11) NOT NULL DEFAULT '-2' - Error is Row size too large. The maximum row size for the used table type, not counting BLOBs, is 8126. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs 
```

**To reproduce**

1. Start the upgrader
2. follow the steps 

**Expected behavior**

No error.

**Logs**
Log file contains 3 rows, not helpful:
```
2020-07-16 11:15:31 [@hostname]
0 seconds for "Work in progress..." @ 2020-07-16 11:23:09 [@hostname]
0 seconds for "Work in progress..." @ 2020-07-16 11:27:02 [@hostname]
0 seconds for "Work in progress..." @ root@hostname:/var/www/html# 
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
Not accesible.

System: Debian 10 64 bit
Database: mariadb 10.3.22

**Comment by trasher** [comment]
This looks like a database configuration issue, see:
- https://mariadb.com/kb/en/troubleshooting-row-size-too-large-errors-with-innodb/
- https://stackoverflow.com/questions/22637733/mysql-error-code-1118-row-size-too-large-8126-changing-some-columns-to-te

I'm not sure we can do anything on GLPI side; at least without changing entirely the entities table; and that would be a huge work.

**Comment by kepi** [comment]
Easy solution is to change `row_format` for `glpi_entities` table. This should be documented in GLPI update documentation (thus I think this should reopen) or even added to migration (if it is possible and same on MySQL - not sure about that).

Anyway for those who will hit this, just use:

```sql
alter table glpi_entities row_format=dynamic;
```

**Comment by trasher** [comment]
It seems this is the default on mariadb for a while: https://mariadb.com/kb/en/innodb-row-formats-overview/#default-row-format

**Comment by phamorais** [comment]
@trasher  @keha35 

Only for historical consultation by the community.

Today I upgraded from 9.4.6 to 9.5.4 and had the same problem, but in the "glpi_entities" and "glpi_users" tables.

The command "changes the table table_name row_format = dynamic; it also worked for me.

Thanks

**Comment by hfath** [comment]
Same here, the update to 10.0.8 on my system needed an

*alter table `glpi_queuednotifications`  ROW_FORMAT=DYNAMIC;*

Isn't this something that the updater could and should do by itself?
