### ISSUE TITLE
[GLPI 9.5.0] opening element from project side menu in new tab won't load html/css entirely

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7702]
//PHP 7.3.16 ; Centos 8.1 stable
//Tested in Chrome & Firefox last version in Windows 10 environnement

Unwanted current behavior : 
Right clicking to open element from project side menu in new tab won't load html/css entirely in the new tab.

Expected behavior :
loading all html and css when opening element in a new tab

**Comment by trasher** [comment]
Tabs are designed to be loaded that way; and this won't be changed until a complete rewrite of the front part.

**Comment by joomlafun** [comment]
Ok, thanks for the feedback trasher.
