### ISSUE TITLE
URL checks fails on IP addresses

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#7703]
I'm get a erro when try to save an IP address at base url. Just FQDN is accept.

![image](https://user-images.githubusercontent.com/22614882/87675488-ce8d5700-c74d-11ea-9d3f-278988f594ee.png)

PTBR

Estou tendo erro ao salvar um endereço IP em URL BASE. Só está aceitando usar FQDN.

**Comment by glpibr** [comment]
If I use localhost and not 127.0.0.1, is OK.
But it is a problem in some internal instalations.


![image](https://user-images.githubusercontent.com/22614882/87675940-60955f80-c74e-11ea-8810-661046e92da1.png)

**Comment by cedric-anne** [comment]
Hi,

This has been fixed by #7733.

Regards
