### ISSUE TITLE
[GLPI 9.5.0] project in kanban will be created in the root entity and not current entity

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7704]
//PHP 7.3.16 ; Centos 8.1 stable

Unwanted current behavior
In project>Kanban if you add a project then the project gets added to the root entity even though you may be in another entity.

Wanted behavior
Project getting added to the current entity

**Comment by joomlafun** [comment]
Thank you.
Still about the Kanban, by any chance do you happen to know why actors or supervisors are missing
![image](https://user-images.githubusercontent.com/63743077/87851003-e6530f80-c8f4-11ea-8eaa-d8b2f3bdca30.png)
Here you can see them :
![image](https://user-images.githubusercontent.com/63743077/87850954-76dd2000-c8f4-11ea-9613-83dc0ddd9897.png)

Kind regards,

**Comment by cconard96** [comment]
@joomlafun Two things about that.
First, I did find a bug with no team member badges showing on the cards at all (PR coming soon hopefully).
Second, the Project cards only show actors on its team and not the team of any tasks under it. It's the same behavior GLPI had before. Project task team members were never shown as being in the Project's team. That change should be done in the Project code, not the Kanban so the experience is uniform across views and so the Kanban can remain somewhat separated from the rest of GLPI. It makes it easier for the Kanban to be reused by plugins or for other item types in the future.

**Comment by joomlafun** [comment]
Ok thank you the explanation.
