### ISSUE TITLE
Upgrade Erro 9.5 to 9.5.1

### ISSUE THREAD

**Issue by glpibr** [glpi-project/glpi#7707]
In upgrade processes I get this erro message:
![image](https://user-images.githubusercontent.com/22614882/87678739-ac95d380-c751-11ea-809f-797c16798bf7.png)
Before Erro, I just put address in Browser and access the system.

**Comment by orthagh** [comment]
for information, 9.5.1 has no updates so no consequences.

Will be fixed by #7706
