### ISSUE TITLE
kb translation and fulltext search return all rows

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#771]
See : https://github.com/glpi-project/glpi/blob/0.90.3/inc/knowbaseitem.class.php#L1096-L1105
We can't do a fulltext search on multiple tables
also a null value in a match against will result on returning all rows (regardless of $search)

PR incoming for this issue

**Comment by orthagh** [comment]
@tomolimo. Could you check this PR ?

**Comment by tomolimo** [comment]
Hello,
I made some tests, and got this SQL error:
![image](https://cloud.githubusercontent.com/assets/7569958/16484343/09abffca-3eb9-11e6-81c9-5faa687ce21f.png)

**Comment by tomolimo** [comment]
You should add:

    FULLTEXT INDEX `Index 4` (`name`),
	FULLTEXT INDEX `Index 5` (`answer`),

to table creation
and then I get results

**Comment by orthagh** [comment]
uh ?

Actually glpi_knowbaseitems and glpi_knowbaseitemstranslations have fulltext index (since this feature order from your campany) : 

* https://github.com/glpi-project/glpi/blob/master/install/mysql/glpi-9.1-empty.sql#L3192
* https://github.com/glpi-project/glpi/blob/master/install/mysql/glpi-9.1-empty.sql#L3237

**Comment by tomolimo** [comment]
I made another test: 
I switched back to MyISAM engine the glpi_knowbaseitemstranslations table, and then tada!
:smiley:

**Comment by tomolimo** [comment]
of course without the new proposed indexes :)

**Comment by tomolimo** [comment]
See: http://stackoverflow.com/questions/35267528/fulltext-indexing-on-myisam-single-column-vs-multiple-column-indexing

**Comment by orthagh** [comment]
Oh great, i didn't know innodb was now compatible with fulltext index.
It's a very good news.

On the original issue (fulltext on multiple table), do you agree with the fix ?

**Comment by tomolimo** [comment]
Fulltext in innodb since 5.6.x (don't remember x)

for the fix: for me it seems ok (but, partially tested only, as I'm not the originator of the request)
