### ISSUE TITLE
glpi_infocoms sql error

### ISSUE THREAD

**Issue by sazanof** [glpi-project/glpi#7710]
Hi! There is an error from sql-errors.txt log
```
[2020-07-16 15:37:46] glpisqllog.ERROR: DBmysql::query() in /home/saz/www/glpi.mosgortur.ru/inc/dbmysql.class.php line 305
  *** MySQL query error:
  SQL: SELECT `glpi_infocoms`.* FROM `glpi_infocoms` WHERE `LEF JOIN` IN ('Array')
  Error: Unknown column 'LEF JOIN' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:856                          DBmysqlIterator->execute()
  inc/infocom.class.php:467                          DBmysql->request()
  inc/crontask.class.php:847                         Infocom::cronInfocom()
  front/cron.php:61                                  CronTask::launch()
  {"user":"788@webserver","mem_usage":"0.005\", 3.44Mio)"} 
```
Perhaps, the error is here https://github.com/glpi-project/glpi/blob/c312b51b007e56d2fb129e18864f51c802dd34a8/inc/infocom.class.php#L469
[sysinfo.txt](https://github.com/glpi-project/glpi/files/4932293/sysinfo.txt)

**Comment by trasher** [comment]
Next time, please provide sys infos in ticket (at least glpi version), way more fast for us to find information without having to download anything.

By the way, you are right, the issue is a missing "T" in the line you pointed.

**Comment by sazanof** [comment]
i just see errors for other issue & see this in sql-errors. so I decided to open it =) Thank you
