### ISSUE TITLE
Invalid API base URL!

### ISSUE THREAD

**Issue by 1053850726** [glpi-project/glpi#7712]
Click the button to display :

```
Error

Invalid API base URL!
```

```
API
--
URL of the API : http://192.168.1.245/apirest.php/

Enable Rest API : Yes

Enable login with credentials :Yes        Enable login with external token:Yes
```

![QQ截图20200717103738](https://user-images.githubusercontent.com/58255247/87743038-9d2e8d00-c81a-11ea-8e7e-341933f5e5c7.png)
![QQ截图20200717103828](https://user-images.githubusercontent.com/58255247/87743053-a4559b00-c81a-11ea-8816-b4377fbe6714.png)
![123](https://user-images.githubusercontent.com/58255247/87743120-ce0ec200-c81a-11ea-9c34-6cb86eed5727.jpg)

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/7703
