### ISSUE TITLE
Uncaught Exception Error: Call to a member function listTables() on null in /var/www/glpi/inc/config.class.php at line 2915 on update glpi 9.5.0 to 9.5.1

### ISSUE THREAD

**Issue by kcscoelho** [glpi-project/glpi#7713]
Uncaught Exception Error: Call to a member function listTables() on null in /var/www/glpi/inc/config.class.php at line 2915

When proceeding with the update, after selecting the GLPI database, the above error was displayed.
However, it seems that the update was completed and when accessing the home address I was directed to the dashboard.
I haven't noticed any problems so far, but my mistake has worried me.

**To reproduce**

Update GLPI from v.9.5.0 to v.9.5.1
Web access, fill the language, fill database params, select database, select confirm, show erro.

in time, my password contains an @ and I noticed that it is configured as code in config_db.php, whenever I update I need to correct this character in the file, but never receive the related erro. 

In config.class.php line 2915 have:

$config_tables_iterator = $DB->listTables('glpi_config%');

I hope this information helps in something.
Tks

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/7707

**Comment by kcscoelho** [comment]
Sorry
