### ISSUE TITLE
GLPI 9.5 - save button not working for Assistance->Change->(Plans, Analysis)

### ISSUE THREAD

**Issue by Kuba-Pawlak** [glpi-project/glpi#7716]
Hello
I would like to report bug for glpi 9.5.0. There is no possibility to save any information in Assistance->Change->(Plans, Analysis).
Save button does not work.

**Comment by cedric-anne** [comment]
Hi,

It has been fixed in 9.5.1.

Duplicates #7635

Regards

**Comment by Kuba-Pawlak** [comment]
Thank you
