### ISSUE TITLE
Connexion not possible since 9.5 - Important regression

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#7725]
This commit introduce a BC break https://github.com/glpi-project/glpi/pull/6794

When i try a connexion in GLPI database, my account is desactivated because an LDAP rule is played. Why? i'm not connected using LDAP.
All dynamics rights are lost.
Having dual authentication methods (LDAP with dynamic rights and GLPIDB) is no more possible.

Note: processAllRules is still played in User.class, so in 9.5 it's played two times, including one for all authentications (KO)

**Comment by orthagh** [comment]
Hello @yllen 

I don't know about this.
More of our users are using external authentication (like oauth) and not ldap to get their users and need dynamic rules for their users rights.

We extended the current rules to only ldap to all auth sources.

I'm sorry your are impacted in a bad way by this change.

Could you explain a little the need of a global (no criteria ?) rule disabling users to see how we can fix all people need (including your side).

Regards.

**Comment by yllen** [comment]
We have a LDAP rule with this criteria, not a global criteria but an LDAP one:
(LDAP)User ID | expression rationnelle ne vérifie pas | /^([0-9]{6})/
If the User ID doesn't match, we de-activate the user account.

I'm want to log in GLPI but my account is always de-activated, however i'm logging in GLPI DB with user/password.
All my dynamics profiles were deleted.

We need to connect with login/password if we have a problem with the LDAP server (or other authentication method).

I don't understand why all rules are played at the login even if it's a specific rule, like mine based on LDAP, even you log yourself without authentication server.
Having criteria based on LDAP is useless because always played?

For me, if you have a rule based on a LDAP criteria, your rule must only be played if you try a connection with an LDAP server.

**Comment by cedric-anne** [comment]
Maybe a solution would be to add a logic on update script in order to add the criterion `"Authentication type" is "Authentication on a LDAP directory"` when a rule have at least one LDAP criterion.

**Comment by trasher** [comment]
Since there were no feedback from a while, it cannot be part of 9.5.2

**Comment by trasher** [comment]
Still no feedback fro months, closing.
