### ISSUE TITLE
[GLPI 9.5.0] & [GLPI 9.5.1] Kanban tab will not load after adding new status(Jquery error)

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7728]
//PHP 7.3.16 ; Centos 8.1 stable
//Chrome & Firefox latest versions

Hi, 

The kanban tab in projects give the following error after I created several new status (8 in total) from the "project status menu" in general>intitulé 

// error in Chrome : 

![image](https://user-images.githubusercontent.com/63743077/87852607-ae9f9400-c903-11ea-9cde-4f7a243768ac.png)

//error in firefox

Uncaught TypeError: column is undefined
    appendColumn kanban.js:1629
    loadColumn kanban.js:1851
    jQuery 2
        fire
        add
    loadColumn kanban.js:1848
    loadState kanban.js:1965
    jQuery 4
        fire
        fireWith
        done
        callback
kanban.js:1629:10
    appendColumn kanban.js:1629
    loadColumn kanban.js:1851
    jQuery 2
    loadColumn kanban.js:1848
    loadState kanban.js:1965
    jQuery 4

**Comment by cconard96** [comment]
Can another user view the Kanban for that Project or can you view other the Kanban for other Projects without the new columns?
Looks like the issue happens after it tries loading your user's view for that one Kanban.

**Comment by joomlafun** [comment]
The same happens with another user.
If I go to another project, I can see the cards but not the button to add/hide status.

I removed all the statuses and the issue persists

**Comment by cconard96** [comment]
Seems like it may be a bad user-state based on you feedback and the area of the code where the issue occurs (loading state). Could you get the "state" value from the `glpi_items_kanbans` DB table for an affected user (`users_id`) and Project (`itemtype` = Project and `items_id`) and add it here? The data in the state should not contain any names or content of the Projects or tasks, but double check that before uploading.
Deleting the record will force it to regenerate, although I'm not sure if the issue would just re-appear.

**Comment by joomlafun** [comment]
{"0":{"column":"0","folded":true,"cards":{"0":"ProjectTask-4"}},"1":{"column":"3","visible":true,"folded":true,"cards":{}},"2":{"column":"6","visible":true,"folded":true,"cards":{}},"3":{"column":"1","visible":true,"folded":true,"cards":{"0":"Project-16"}},"4":{"column":"2","visible":true,"folded":false,"cards":{"0":"Project-11","1":"Project-9","2":"Project-13","3":"Project-15","4":"Project-12","5":"ProjectTask-11","6":"ProjectTask-10","7":"ProjectTask-12","8":"ProjectTask-13","9":"ProjectTask-14"}},"5":{"column":"5","visible":true,"folded":true,"cards":{}},"6":{"column":"8","visible":true,"folded":true,"cards":{}},"7":{"column":"7","visible":false,"folded":false,"cards":{}},"8":{"column":"4","visible":false,"folded":false,"cards":{"0":"ProjectTask-8"}},"9":{"column":"9","visible":true,"folded":true,"cards":{"0":"Project-14"}}}

I deleted the records, nothing happened, then I created a new project and I do not have the JS error any more and I can add new statuses from the kanban.
