### ISSUE TITLE
User not addedd if name field value: no error prompted.

### ISSUE THREAD

**Issue by Kaya84** [glpi-project/glpi#7735]
**Describe the bug**

No user added if login field is empty and no error message printed
**To reproduce**

Go to user -> add new user
Fill the form except for the login field.
Click Add

**Expected behavior**

A new user without login or eventually an error saying that field is mandatory.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
GLPI 9.4.4

**Possibile solution**
glpi/front/user.form.php line 61 replace
```
else if (isset($_POST["add"])) {
   $user->check(-1, CREATE, $_POST);

   // Pas de nom pas d'ajout
   if (!empty($_POST["name"])
       && ($newID = $user->add($_POST))) {
      Event::log($newID, "users", 4, "setup",
                 sprintf(__('%1$s adds the item %2$s'), $_SESSION["glpiname"], $_POST["name"]));
      if ($_SESSION['glpibackcreated']) {
         Html::redirect($user->getLinkURL());
      }
   }
   Html::back();

} 
```
with 
```
else if (isset($_POST["add"])) {
   $user->check(-1, CREATE, $_POST);

   if ($_POST["name"] == ""){
	Session::addMessageAfterRedirect("Login filed cannot be empty", true, ERROR);
}
	
   // Pas de nom pas d'ajout
   if (!empty($_POST["name"])
       && ($newID = $user->add($_POST))) {
      Event::log($newID, "users", 4, "setup",
                 sprintf(__('%1$s adds the item %2$s'), $_SESSION["glpiname"], $_POST["name"]));
      if ($_SESSION['glpibackcreated']) {
         Html::redirect($user->getLinkURL());
      }
   }
   Html::back();

}
```

**Comment by cedric-anne** [comment]
Hi,

Your solution may be a quick fix, but, in fact, this check have to be removed. Indeed it is already done on User class itself, and already displays an error message in this case. See #7747 .

Regards
