### ISSUE TITLE
Large/many external calendars handling (slow or not showing)

### ISSUE THREAD

**Issue by edphemeria** [glpi-project/glpi#7736]
**Describe the bug** : 
- v9.5.0 & v9.5.1 : external calendars don't load with large calendars (10Mb .ics with 5000+ events), the page never loads (blank calendar)
- v9.5.0 & v9.5.1 : external calendars seem to load complete calendars on each view (week/month...), really slow with more than 5-6 external calendars to display (10s before displaying the next view)

**Page(s) URL**
/glpi/front/planning.php

**Steps to reproduce**
1. Display the planning, add 5+ calendars containing 100+ events from various sources (Google Calendar, Zimbra, ...)
2. Wait for the page to load

OR

1. Add one single calendar containing 5000+ events (mine is a 10Mb Zimbra .ics share, 3 years of work)
2. Wait for the page to load, it never does

**Expected behavior**
Ability to handle large calendars (limitless?)
For a better loading time, have the external calendar stored in a cache before checking for changes (and if changes, load them seamlessly only where something changes)

**Logs**
For the large .ics issue : 
Unable to parse calendar data from URL "https://caldav-server/home/user@domain.com/%23%20WORK.ics"  {"user":"100@glpi-server"}
> Note: the issue is not coming from the %23%20 .ics URL, I have other calendars with the same naming that do work (smaller sizes)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
Operating system: Linux glpi-server 4.15.0-111-generic #112-Ubuntu SMP Thu Jul 9 20:32:34 UTC 2020 x86_64
PHP 7.2.24-0ubuntu0.18.04.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc,
	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap,
	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="64M" post_max_size="32M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at inventaire Port 80)
	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 5.7.30-0ubuntu0.18.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

**Comment by cedric-anne** [comment]
Hi,

Indeed, there is no caching on this feature, and it may be improved.

For the `Unable to parse calendar data from URL` issue, it means that your calendar cannot be parsed by the library used.
Can you apply following patch and give us what appears in logs when this error happens ?
```diff
diff --git a/inc/planning.class.php b/inc/planning.class.php
index 3394f7ad54..4cf73774df 100644
--- a/inc/planning.class.php
+++ b/inc/planning.class.php
@@ -2011,7 +2011,12 @@ class Planning extends CommonGLPI {
          try {
             $vcalendar = Reader::read($calendar_data);
          } catch (ParseException $exception) {
-            Toolbox::logError(sprintf('Unable to parse calendar data from URL "%s"', $planning_params['url']));
+            Toolbox::logError(
+               sprintf('Unable to parse calendar data from URL "%s"', $planning_params['url']),
+               $exception->getMessage(),
+               "\n",
+               $exception->getTraceAsString()
+            );
             continue;
          }
          if (!$vcalendar instanceof VCalendar) {
```

Regards

**Comment by edphemeria** [comment]
Hi cedric-anne,

Thanks for your support! 
I applied the provided catch tuning code, here is the output for me:
`Unable to parse calendar data from URL "https://caldav-server.com/home/user@domain.com/%23%20WORK.ics"  {"user":"842@glpi-server"}`

Regards

**Comment by cedric-anne** [comment]
Hi,

With this patch, you should have the complete trace of the exception and the exception message.
Without the exception trace, we cannot do anything.

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
