### ISSUE TITLE
Email is not sent (using gmail)

### ISSUE THREAD

**Issue by lcoria** [glpi-project/glpi#774]
Dears, 
I'm going crazy, because i configured in many ways the gmails SMTP in GLPI. but no email is sent when  create a incident or request. All emails stays in queue, but not sent automatically.
I'm able to send them manually, but is not the right way.

![image](https://cloud.githubusercontent.com/assets/19955232/16501196/9d059b30-3ede-11e6-9b6b-ca9e5c8f583d.png)

in the queuedmail, I've tried all ways, but nothing. So far I let it as it:
![image](https://cloud.githubusercontent.com/assets/19955232/16501241/d60758c4-3ede-11e6-970f-489640701d0e.png)

In Adminitration-->email Queue, i see that all messages are there:
![image](https://cloud.githubusercontent.com/assets/19955232/16501314/43248e9a-3edf-11e6-9db7-43723ae077e8.png)

manually, works fine, and I see in my inbox, the emails. But the idea is that the user, will be able to create an incindent or request, and after pressing the SUBMIT button, receive a notification.

I had open my IMAP in my gmail account. 
i've tried with the last version and also with version 0.8.5.5, but the email sending is not working.

Can somebody help me with this to make it work and send automatically a notification email ?
Is there some rule i'm forgetting? I'm using GLPI as it, just 1 user to create test ticktes, and the glpi users, to manage configuration.

I didn't create any new element.

Thanks

**Comment by guillermohaad** [comment]
Hi Icoria,
checks the mail log in /var/www/glpi/files/_log/mail.log

**Comment by lcoria** [comment]
Yes, i've been cheking the logs all the time, but it's says only that my incidente has been added to the queue. NO error messages, or no other things:

2016-06-30 20:58:59 [6@INGENIERIA5-PC]
Un correo para xxxxxxxxxz@gmail.com fue añadido a la cola: [GLPI #0000006] Nuevo incidente test6
2016-06-30 20:58:59 [6@INGENIERIA5-PC]
Un correo para xxxxxxxxx8@gmail.com fue añadido a la cola: [GLPI #0000006] Nuevo incidente test6


When Manually i send the emails, the log register it as a success send. 

What could it be? is there a way to make a test with some email software?

Thanks
Luis

**Comment by guillermohaad** [comment]
Hola Icoria, disculpa por escribir en ingles, en español mas fácil para mi.
cuando haces pruebas manuales como las haces?. en que sistema operativo lo tienes instalado?

**Comment by tomolimo** [comment]
Please in English!
Thank you,

**Comment by guillermohaad** [comment]
Sorry
when you do manual testing as do ?. in which operating system you have it installed?

**Comment by lcoria** [comment]
Thanks for the replies.
1) to do the test Manually, i go to Configuration-->Notifications
![image](https://cloud.githubusercontent.com/assets/19955232/16522301/5f69c4fa-3f73-11e6-9a2c-75726277c991.png)

2) I press the button Send test Message to Administrator
![image](https://cloud.githubusercontent.com/assets/19955232/16522346/ad6d4e2e-3f73-11e6-8336-6eb3566c9e27.png)

3) I get the message that the email has been sent to the administrator. I go to my email account to check it, and i received it ok:
  
![image](https://cloud.githubusercontent.com/assets/19955232/16522394/f28f2996-3f73-11e6-98a1-f717601b262c.png)

That means that my configuration seems to be OK.
The log file doesn´t shows anything.

I tried with Windows 7 Ultimate and also with my macbook pro with El Capitan OS


Thanks a lot
Luis

**Comment by guillermohaad** [comment]
Ok, I understand, I see that can be problem cron. 
so I have it:

![image](https://cloud.githubusercontent.com/assets/12921805/16522766/505f1aae-3f65-11e6-944c-2ce89aaedda2.png)

![image](https://cloud.githubusercontent.com/assets/12921805/16522785/6f566e62-3f65-11e6-8a63-efa02d4c0103.png)

**Comment by lcoria** [comment]
Thanks for the reply, I left the same way that to have, but isn't working yet.

I created a new test ticket:
![image](https://cloud.githubusercontent.com/assets/19955232/16523020/8bfd0d70-3f77-11e6-9e48-9fbfbd659b90.png)

And I'm still waiting for the notification. 

What version are you using? Perhaps i can use it to compare. As i mentioned before, I used the last version (9.0) and now i'm using the version 8.5.5

Thanks

**Comment by guillermohaad** [comment]
I have used versions from 0.85, 0.90.0, 0.90.1 and 0.90.3 currently I have the and not problem.

**Comment by guillermohaad** [comment]
see how it behaves/glpi/files/_log/cron.log

**Comment by guillermohaad** [comment]
Hi Icoria how was the problem?

**Comment by lcoria** [comment]
Negative. I'm still with the issue.
I'll reinstall one more time everything and try again on my MacBook 

I'll let you know
Thanks for the help

**Comment by guillermohaad** [comment]
Ok with pleasure

**Comment by yllen** [comment]
In your settings, do you want to be notify for your change?
If yes, put your profile in Debug mode (in your settings)
Open a ticket after the creation. You will see a Debug tab.
Open it and you will see wich notification is sent for which event to which email address.
If all OK, open glpi/files/_log/mail.log and look if you want mail generated to the requester.

**Comment by lcoria** [comment]
Thanks, i did what you sugeested, and I dont see nothing wrong in the debug mode.
In the log file, it says that my incident has been added to the queue.

I go to "Automatic action - queuedmail - ID 22"  (As an administrator) and I see the message "Running". It's been for a long time and I'm still seeing the message. Looks like the system stays in that status and it won't send emails. I've been wainting for 15 minutes and nothing happened yet.

![image](https://cloud.githubusercontent.com/assets/19955232/16732203/626c35d4-4752-11e6-9b41-43edaa689883.png)


I'm still looking for some solution.
Thanks

**Comment by orthagh** [comment]
Hello @lcoria 

Sorry for the delay of this answer.

To resume your issue, notifications are populated in queue but never sent ?

If yes, could you check theses followings steps. If one fail or if you see errors messages (red background), please let us know : 

**Initial setup**:
- Enable debug mode in your preferences (you should be super-admin).

**Send tests** (for each, you need to have notification(s) in the queuemail):
- Triggers manually the send action in the queue mail (select checkboxes and choose Actions > Send).
- Go into the queuemail  automatic action (like above capture), reset it if currently running, and run it.
- Launch with php command line the front/cron.php file

If you see error messages (red background), you should retrieve the traces in your logs files (files/_logs/ directory).

**Comment by jcpinerosc** [comment]
I had the same problem with 9.1.2 versión, after upgrade glpi 0.84 in a new server. The problem is due to PHP date.timezone variable in php.ini when it's not set. 

Email notifications (and everything else), date creation and date estimated delivery were in UTC, but my server had UTC-5.

The cron delayed the actions by five hours. It is a stupid mistake, but it's posible, that it could be the root cause of the weird error reported by @Icoria.

Is it posible to add a check for this variable in the installation process? Or to display a warning?

**Comment by iaanpermana** [comment]
hello, i had the same problem, all my task notification stuck in the mail queue and had to be manually send.
i think the automatic action didn't work, so i read this post and wondering, how to setup crontab that mentioned above ? i am using windows and xampp. thanks

**Comment by Armin83** [comment]
If yes, could you check theses followings steps. If one fail or if you see errors messages (red background), please let us know :

### Do you know about the difference between cli and glpi ?
- In GLPI mode you must have action in your GLPI site to send notification.
- Put automatic task in CLI mode and create the cron for guaranteed process.
http://wiki.glpi-project.org/doku.php?id=en:config:crontab

### More Information similar topic
http://forum.glpi-project.org/viewtopic.php?id=142324

### Test it for further error
1. Enable debug mode in your preferences (you should be super-admin).
2. Go into the queuedmail automatic action (like above capture), reset it if currently running, and run it. If it is currently running and is in stuck nothing could work so cancel it.
3. If you see error messages (red background), you should retrieve the trace in your logs files (files/_logs/ directory).

**Comment by trasher** [comment]
This ticket is not a bug, but seems to be a configuration/comprehension issue. I close

**Comment by AungShwe2002** [comment]
Thanks You , It work times zone error and fix it
