### ISSUE TITLE
[GLPI 9.5.1] ticket project task tab view will not display linked task nor load project tasks in dropdown

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#7740]
//PHP 7.3.16 ; Centos 8.1 stable

Hi, 

1° I cannot view to which project task my ticket is linked to 
2° dropdown menu to add to a project tasks says "les résultats ne peuvent pas être chargés"

![image](https://user-images.githubusercontent.com/63743077/87977411-f9b9d280-cace-11ea-83e6-0f58b0c12866.png)

//logs

[2020-07-21 17:43:36] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Empty IN are not allowed in /home/glpi/glpidemo1/inc/dbmysqliterator.class.php at line 559
  Backtrace :
  inc/dbmysqliterator.class.php:530                  DBmysqlIterator->analyseCriterion()
  inc/dbmysqliterator.class.php:516                  DBmysqlIterator->analyseCrit()
  inc/dbmysqliterator.class.php:289                  DBmysqlIterator->analyseCrit()
  inc/dbmysqliterator.class.php:94                   DBmysqlIterator->buildQuery()
  inc/dbmysql.class.php:857                          DBmysqlIterator->execute()
  inc/projecttask_ticket.class.php:320               DBmysql->request()
  inc/projecttask_ticket.class.php:98                ProjectTask_Ticket::showForTicket()
  inc/commonglpi.class.php:637                       ProjectTask_Ticket::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

**Comment by cedric-anne** [comment]
Hi,

The logs you provided are not corresponding to the error you had on your screenshot.
Can you provide the full stack trace of the displayed exception ?

Regards

**Comment by joomlafun** [comment]
You are right, please find the updated post with new logs above.

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.
It will happen when you have no state with `is_finished` flag, and/or no project with a `is_finished` state.

Regards
