### ISSUE TITLE
Uncaught Exception Error when trying to update from 9.5.0 to 9.5.1 via GUI

### ISSUE THREAD

**Issue by Mexonizator** [glpi-project/glpi#7749]
Hello.

Full text of the error:

`Uncaught Exception Error: Call to a member function listTables() on null in /usr/share/nginx/glpi/inc/config.class.php at line 2915`

After refreshing the page:

`Uncaught Exception RuntimeException: You must create a security key, see glpi:security:change_key command. in /usr/share/nginx/glpi/inc/glpikey.class.php at line 102`

**Comment by cedric-anne** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/7707
