### ISSUE TITLE
Entities problem since migration into 9.4.6

### ISSUE THREAD

**Issue by jeromarsan** [glpi-project/glpi#7750]
Hello,

After migrate GLPI 9.1 to 9.4.6, i have entoty problems.

That's my entity schema, i have more 10 entitys

ROOT ENTITY
|_ ENTITY A 
|_ ENTITY B 
|_ ENTITY C 
etc...

In 9.1 version, on my homepage, i saw all the tickets and computers of all my entities, by the root entity.

Since the upgrade, i have to select the specific entity to see the computers and tickets.

Now i haven't global vision of all my entities.

On my BDD, i have this config :

ROOT ENTITY (1)
|_ ENTITY A (2)
|_ ENTITY B (2)
|_ ENTITY C (2)

If you have and idea, i will be happy :D 

Thanks

**Comment by jeromarsan** [comment]
![image](https://user-images.githubusercontent.com/6598465/88069123-5cfc4100-cb71-11ea-9c7b-e5460afe09cb.png)
![image](https://user-images.githubusercontent.com/6598465/88069136-62f22200-cb71-11ea-9006-45d1a57446f7.png)

When i create a new entity, i can see it under the root. But no the olders entities.
![image](https://user-images.githubusercontent.com/6598465/88069200-72716b00-cb71-11ea-829c-d051344a236a.png)

**Comment by cedric-anne** [comment]
Hi,

Are you in recursive mode ? To display child entities, you have to click on "green chevrons" icon next to entity name: 
![image](https://user-images.githubusercontent.com/33253653/88069483-cd0ac700-cb71-11ea-8cbf-5ffe0c7a8e9c.png)

Regards

**Comment by jeromarsan** [comment]
Yes i am :)

**Comment by jeromarsan** [comment]
![Annotation 2020-07-21 165030](https://user-images.githubusercontent.com/6598465/88069917-5de1a280-cb72-11ea-944c-e6f009d644d5.png)

**Comment by cedric-anne** [comment]
Can you try to logout/login ?

Can you try without any active plugin ?

**Comment by jeromarsan** [comment]
> Can you try to logout/login ?
> 
> Can you try without any active plugin ?

Already done :(

**Comment by jeromarsan** [comment]
I have try with another browser, without cache, etc, the same problem

**Comment by jeromarsan** [comment]
No idea ?

**Comment by jeromarsan** [comment]
Hello, anyone have the same problem ?
