### ISSUE TITLE
GLPI 9.5.1 Check new version button

### ISSUE THREAD

**Issue by AndreasGermany** [glpi-project/glpi#7751]
Hello,

I installed GLPI version 9.5.1 but when I click on the check new version button, it keeps telling me that a new version 9.5.1 is available.
System Info:

![Version](https://user-images.githubusercontent.com/57146876/88150952-59fd6100-cc02-11ea-8271-4e0f80d57532.JPG)
Check new version result:

![New_Version](https://user-images.githubusercontent.com/57146876/88150974-62559c00-cc02-11ea-856f-61f6c8ec96d4.JPG)

Best regards
Andreas

**Comment by cedric-anne** [comment]
Hi,

Is it a new installation or an upgrade from a previous version ? If you upgraded from UI, then I guess this is due to a problem in upgrade process (see #7707) which prevented the current version to be stored in DB.

I keep it open as it may be fixed with a patch.

Regards

**Comment by cedric-anne** [comment]
#7751 may fix this.

**Comment by AndreasGermany** [comment]
Hi, yes, you are right. It was an update.
