### ISSUE TITLE
9.5.1 assets - global - search : Class 'AllAssets' not found in /var/www/html/glpi/ict/inc/search.class.php at line 4658

### ISSUE THREAD

**Issue by mdesfawes** [glpi-project/glpi#7752]
in glpi 9.5.1 (but same error in 9.5)
you click on assets - global
you search with a status
characteristic-status is new
you start the search

you receive : 
Uncaught Exception Error: Class 'AllAssets' not found in /var/www/html/glpi/ict/inc/search.class.php at line 4658

after this, when you go to assets-global, you receive always this error until  you restart a new browser and a new connection to glpi

Thanks
Michel

**Comment by cedric-anne** [comment]
Hi,

#7761 should fix your issue.

Regards
