### ISSUE TITLE
MAPI - Exchange Protocol

### ISSUE THREAD

**Issue by cgalvons** [glpi-project/glpi#7755]
**Is your feature request related to a problem?**

No, I'd like a new feature on GLPI.

**Describe the solution you'd like**

I'd like to receive tickets by mail but GLPI allow POP/IMAP protocols only. Unluckly I am not able to allow those supported protocols in my Exchange server due to company security policies. Then I'd like to know if could be possible to enable MAPI (Exchange protocol) onto GLPI to match my need. It could be a solution for other people as well.

Thanks in advance for read my message.

**Comment by tontonrico** [comment]
Hello,
same need because in october the IMAP/POP support will be stopped by MS.
