### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by Rutaa** [glpi-project/glpi#7756]
Hello guys
I have problem with update process, after click update button I get this error
![image](https://user-images.githubusercontent.com/26909103/88214397-6d3c1b00-cc5a-11ea-987a-08955c308d5a.png)

**Comment by consensusdevteam** [comment]
Have the same issue upgradig from v9.5 to v9.5.1 in CentOS 8 with MariaDB 10.3 and PHP 7.3

**Comment by cedric-anne** [comment]
Duplicates #7707.
