### ISSUE TITLE
PHP >= 7.2.0 requiered - Ubuntu 18.04, MySQL 8.0, PHP 7.4.8

### ISSUE THREAD

**Issue by Koll17** [glpi-project/glpi#7765]
Hello everyone, 

I was updating glpi from 9.3 to 9.5, I also updated Ubuntu 16.04 to 18.04 and MySQL 5.3 to 8.0, but when I downloaded glpi version 9.5 and extracted it, I tried to install via localhost / glpi and the message "PHP > = 7.2.0 required" appeared. then I updated PHP 7.0 to 7.2 and the same message, then I updated to 7.3 and 7.4 and the same problem. 

Could someone help me with this "problem"?

Thanks a lot... 

![GLPI_PHP74](https://user-images.githubusercontent.com/68739943/88396276-ee450080-cd87-11ea-8120-2ed3a290ee80.png)

**Comment by flegastelois** [comment]
Hi,

Your version of Apache PHP module is not the correct one: are you sure "php7_mod" is version 7.4? check the available modules and load the correct one.

Testing with PHP cli version is irrelevant.

Kind regards,
