### ISSUE TITLE
impossibility to assing more than 1 observer to a ticket (9.5.1)

### ISSUE THREAD

**Issue by jonatangobbato** [glpi-project/glpi#7766]
When a user opens a ticket, its only possible o assign one observer.

**To reproduce**

1. Go to "New Ticket"
2. On observers, select an user as Observer
3. Try to add another Observer to a ticket.

**Expected behavior**

When the user clicks on the "+" button, a option to choose another observer appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/29125329/88400389-a8476700-cd9e-11ea-9a66-2195f7968aaf.png)

![image](https://user-images.githubusercontent.com/29125329/88400460-c319db80-cd9e-11ea-9dae-a9faf10e7cd4.png)

GLPI 9.5.1 ( => /var/www/glpi) Installation mode: TARBALL

**Comment by desenbahia-usi** [comment]
Hi Jonatan, 

We have exactly the same issue here. Do you find out something to do to fix this?  

Centos 8 
GLPI 9.5.1 (Tarball installation)
Nginx 1.14.1 
PHP 7.4.9 

"php-errors.log"
[2020-08-24 12:32:50] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function getMandatoryMark() on string in .../glpi/inc/commonitilobject.class.php at line 4200
  Backtrace :
  inc/ticket.class.php:4013                          CommonITILObject->showActorAddFormOnCreate()
  ajax/helpdesk_observer.php:42                      Ticket::showFormHelpdeskObserver()

**Comment by jonatangobbato** [comment]
Hi @desenbahia-usi ,


I still have the problem, waiting for a solution.

**Comment by desenbahia-usi** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cedric-anne** [comment]
Hi,

#7879 should fix your issue.

@jonatangobbato , next time, please provide logs as requested during issue creation. It could help to reproduce and fix the issue.

Regards

**Comment by jonatangobbato** [comment]
Hi ,

@cedric-anne the #7879 has worked. Thanks

Sorry for the logs, my bad.
