### ISSUE TITLE
Mail Receyver doesnt work after upgrade to 9.5.1

### ISSUE THREAD

**Issue by suuguus** [glpi-project/glpi#7767]
**Describe the bug**

Ungültige Adresse
An error occured trying to connect to collector.
cannot connect to host ; error = fsockopen(): unable to connect to ssl://192.168.10.12:995 (Unknown error) (errno = 0 )

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**
![image](https://user-images.githubusercontent.com/15847877/88450284-2e6eb680-ce4e-11ea-8851-252ed423ef35.png)

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```
[2020-07-24 10:52:01] glpiphplog.ERROR: MailCollector::collect() in /usr/share/glpi/inc/mailcollector.class.php line 669
#0 /usr/share/glpi/vendor/laminas/laminas-mail/src/Storage/Pop3.php(149): Laminas\Mail\Protocol\Pop3->connect()
#1 /usr/share/glpi/inc/toolbox.class.php(2323): Laminas\Mail\Storage\Pop3->__construct()
#2 /usr/share/glpi/inc/mailcollector.class.php(1290): Toolbox::getMailServerStorageInstance()
#3 /usr/share/glpi/inc/mailcollector.class.php(667): MailCollector->connect()
#4 /usr/share/glpi/inc/mailcollector.class.php(1725): MailCollector->collect()
#5 /usr/share/glpi/inc/crontask.class.php(847): MailCollector::cronMailgate()

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

For now, `no-validate-cert` option is not working in GLPI 9.5, but we are working on it. See #7767.

Regards

**Comment by suuguus** [comment]
Ok Thanks for the info...
So I go paraglyding and wait for the solution.
Have a good day....
roger

**Comment by artnoise** [comment]
> 
> 
> Hi,
> 
> For now, `no-validate-cert` option is not working in GLPI 9.5, but we are working on it. See #7767.
> 
> Regards

Hello, what is the work around?? Thanks

Same issues. on Glpi 9.5.1
