### ISSUE TITLE
v9.5 - massive action "clone" useless in tickets mandatory fields management

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#7771]
Hi

I noticed that the **clone**  massive action is useless (and fails because of unicity) when I'm un the ticket templates.

Clone should be a forbidden action here.

![image](https://user-images.githubusercontent.com/14139801/88529184-eee7cc00-cfff-11ea-8d4e-a737a0da29f0.png)

**Comment by btry** [comment]
Hi

Same problem in items associated to a ticket

![image](https://user-images.githubusercontent.com/14139801/89121903-649ddd00-d4c3-11ea-969d-005d39ab2853.png)

**Comment by cconard96** [comment]
Related to #7815 and #7816

**Comment by cedric-anne** [comment]
Fixed by #7815
