### ISSUE TITLE
12 columns do not support the use of time zones

### ISSUE THREAD

**Issue by ortiga88** [glpi-project/glpi#7772]
Going from 9.4.7 to .9.5.1 I get that message in the main panel and I have done all the steps correctly

**Comment by cedric-anne** [comment]
Hi,

Did you run the `php bin/console glpi:migration:timestamps` command ? These columns may have been created by plugins that did not yet modified their installation process.

Regards

**Comment by ortiga88** [comment]
ok it works thanks
