### ISSUE TITLE
Cannot Add Simcards

### ISSUE THREAD

**Issue by simon-inman** [glpi-project/glpi#7776]
**Describe the bug**
In GLPI 9.5.1 I am unable to add a new simcard. When saving. I get the error: Simcards: A device ID is mandatory

**Page(s) URL**
https://glpi.bip.solutions/front/item_devicesimcard.form.php

**To reproduce**

Steps to reproduce the behaviour:
1. Go to Assets, Simcards
2. Click on +
3. Enter basic data
4. Save
5. See error

**Expected behavior**
I would expect the simcard to be created and appear in the list

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
[code]
 
GLPI 9.5.1 ( => /usr/share/glpi)
Installation mode: TARBALL

**Comment by cedric-anne** [comment]
Duplicates #7420.
