### ISSUE TITLE
Different date format since 9.5

### ISSUE THREAD

**Issue by LuminousWing** [glpi-project/glpi#7780]
Before GLPI 9.5, when you made a ticket you could select "Today" when choosing the date of the ticket which automaticly entered the current date and hour.
Since 9.5 this feature is gone, would it be possible to re-add it since the current way is quite horrible to use.

![image](https://user-images.githubusercontent.com/45965394/88764717-bff36680-d175-11ea-8f4a-ef7d8dca3869.png)

**Comment by cedric-anne** [comment]
Hi,

Did you try to let this field empty ? I think it will be automatically filled with the current date/hour on form valdiation.

Regards

**Comment by LuminousWing** [comment]
> Hi,
> 
> Did you try to let this field empty ? I think it will be automatically filled with the current date/hour on form valdiation.
> 
> Regards

That did it, so apparently there's no need to fill it in if the current date/time is ok.
Thanks for the feedback.
