### ISSUE TITLE
v9.5.1: Dashboards not displayed with IE11

### ISSUE THREAD

**Issue by slegrand-cpam45** [glpi-project/glpi#7786]
Hi,

When i go to the `front/central.php` page as administrator, the dashboards are not displayed with IE11 browser. But that works with Chrome or Firefox.

The bug seems due to the lack of including `gridstack-poly.min.js` file. To quote the gridstack documentation (https://github.com/gridstack/gridstack.js):

> Because of that we are still bundling jquery (3.4.1) + jquery-ui (1.12.1 minimal drag|drop|resize) internally in gridstack.all.js. IFF your app needs to bring it's own version instead, you should instead include gridstack-poly.min.js (optional IE support) + gridstack.min.js + gridstack.jQueryUI.min.js after you import your libs.

And if i add the following line at the beginning of central.php, the bug is fixed, IE11 correctly displays the dashboards:

`echo '<script src="https://cdn.jsdelivr.net/npm/gridstack@1.1.2/dist/gridstack-poly.min.js"></script>';`

**Comment by OscarBeiro** [comment]
Hi,
I don't think so. Check this: https://github.com/glpi-project/glpi/pull/7669

**Comment by slegrand-cpam45** [comment]
Ah... Ok. I didn't know. I guess i have to close this issue then. Thank you for your answer.
