### ISSUE TITLE
picture don't appear in the Ticket when Mail is sending with Outlook

### ISSUE THREAD

**Issue by gcastellarin** [glpi-project/glpi#7787]
Yesterday i upgrade my GLPI 9.4.4 to 9.5, the upgarde seeam to be good. When i test this version i see i have un bug when i send mail with outlook to collector with picture in the body. The Picture is not present in the ticket.
So after, i updated to the 9.5.1 version and the problem still the same with Outlook.
When a another email is sending by webmail (rouncube) to collector, the ticket appear with the picture correctly in GLPI.

**Screenshots**

![image](https://user-images.githubusercontent.com/68955902/88810755-12ed0e00-d1b6-11ea-9c21-a8aa951784b2.png)

![image](https://user-images.githubusercontent.com/68955902/88811005-547db900-d1b6-11ea-9f6f-7e2647c58659.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.1 (/glpi => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux glpi 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64 PHP 7.3.19-1~deb10u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at glpi.agroparc.local Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 Server Software: MySQL Community Server - GPL 	Server Version: 8.0.18 	Server SQL Mode:  	Parameters: GLPI@localhost/glpi_db 	Host info: Localhost via UNIX socket

[eml.zip](https://github.com/glpi-project/glpi/files/4995467/eml.zip)

**Comment by cedric-anne** [comment]
Hi,

#7748 should fix this.

Thanks for your eml export. I take your email, anonymized it, and added it in our test suite.

Regards
