### ISSUE TITLE
Automatic tasks won't start

### ISSUE THREAD

**Issue by Mexonizator** [glpi-project/glpi#7794]
Hi.

It seems the issue with them is going to be eternal, seeing various posts about the problem which date back to 2015, 2012, 2011 years... Nevertheless.

I upgraded to GLPI 9.5.1, and the tasks in automatic actions don't start. What I did:

1. Made sure there's a task in cron for the web server's user:
`*/1 * * * * /usr/bin/php72 /usr/share/nginx/glpi/front/cron.php &>/dev/null`
2. Checked the path to the cron.php, checked the rights - they're alright;
3. Set all the tasks in Automatic actions to run in CLI mode.

As a result, that's what I have on the page of any task:

![111](https://user-images.githubusercontent.com/41675971/88929228-81979d80-d282-11ea-86ba-c95e34d4b4e5.jpg)

It should run, but won't.

Additionally  cron.log says that:

`Internal #1: Nothing to launch`

So, I strongly suspect there's a bug at play as before the upgrading everything worked fine.

UPD. If I push the execute button a task will run properly.

Thanks.

**Comment by cedric-anne** [comment]
Hi,

Did you solve your issue ?
What is the result of a manual call to `php front/cron.php --debug` ?

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as no feedback were given to latest comment.

Regards

**Comment by yorenet** [comment]
Hi,
I experience exactly the same issue after upgrade to 9.5.1
Regards
