### ISSUE TITLE
After Update 9.5.1, add two observator in ticket is impossible

### ISSUE THREAD

**Issue by Dealtis-mcado** [glpi-project/glpi#7798]
hi

after update glpi in 9.5.1, i have this error when i add a second observator on a ticket creation form :

Uncaught Exception Error: Call to a member function getMandatoryMark() on string in /usr/share/glpi/inc/commonitilobject.class.php at line 4200

i need help for this
thanks

**Comment by jonatangobbato** [comment]
i have same issue, details on ticket #7766
