### ISSUE TITLE
php error when add a task

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#78]
0.90
Create a projet, the add a task -> I get a php error (extract php-errors.log hereafter).
Nevertheless, the task is correctly created, but the screen is hardly empty.
  *** PHP Notice(8): Undefined variable: newID 
  Backtrace : 
  front/projecttask.form.php:62

**Comment by yllen** [comment]
I have recently corrected a bug for task project (https://github.com/glpi-project/glpi/issues/86)
Can you test again?

**Comment by blerohellec** [comment]
Php notice still there

**Comment by blerohellec** [comment]
Corrected
