### ISSUE TITLE
[9.5] Some dropdown options broken

### ISSUE THREAD

**Issue by Renton31** [glpi-project/glpi#7817]
**Describe the bug**

When using certain dropdowns in tickettemplate.form.php, got this error when I select SLAs....

> Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /var/www/html/glpi/inc/dropdown.class.php on line 157 in /var/www/html/glpi/inc/dropdown.class.php at line 278

**Page(s) URL**

/glpi/front/tickettemplate.form.php?id=1

**To reproduce**

1. Go to 'glpi/front/tickettemplate.php'
2. Click on 'Default'
3. Click on 'Predefined fields'
4. Click on the dropdown menu and select "SLA Time to own" or "SLA Time to resolve"

![image](https://user-images.githubusercontent.com/69094262/89112339-aac25480-d461-11ea-8472-80801939bdad.png)

**Expected behavior**

I would like to set my SLAs on the default ticket template.

**Logs**

```
[2020-08-02 02:04:58] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /var/www/html/glpi/inc/dropdown.class.php on line 157 in /var/www/html/glpi/inc/dropdown.class.php at line 278
  Backtrace :
  inc/dropdown.class.php:157                         Dropdown::addNewCondition()
  inc/commondbtm.class.php:3910                      Dropdown::show()
  inc/commondbtm.class.php:4831                      CommonDBTM::dropdown()
  inc/ticket.class.php:6788                          CommonDBTM->getValueToSelect()
  ajax/dropdownMassiveActionField.php:99             Ticket->getValueToSelect()
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

[code]
 
GLPI 9.5.0 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux SVMDB-GLPI 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64
PHP 7.3.19-1~deb10u1 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apc, apcu, bz2, calendar, cgi-fcgi,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at svmdb-glpi.omnium-finance.com Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.197
Server Software: Debian 10
	Server Version: 10.3.22-MariaDB-0+deb10u1
	Server SQL Mode: 
	Parameters: dbuser_glpi@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.3.22) - Perfect!Database version seems correct (10.3.22) - Perfect!
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.

GLPI constants
 
GLPI_ROOT: /var/www/html/glpi
GLPI_CONFIG_DIR: /var/www/html/glpi/config
GLPI_VAR_DIR: /var/www/html/glpi/files
GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_FORCE_NATIVE_SQL_TYPES: 1
GLPI_DOC_DIR: /var/www/html/glpi/files
GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache
GLPI_CRON_DIR: /var/www/html/glpi/files/_cron
GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales
GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock
GLPI_LOG_DIR: /var/www/html/glpi/files/_log
GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins
GLPI_RSS_DIR: /var/www/html/glpi/files/_rss
GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions
GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/glpi/locales
GLPI_VERSION: 9.5.0
GLPI_SCHEMA_VERSION: 9.5.0
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2020

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.5 in (/var/www/html/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/glpi/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src)
wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

LDAP directories
 
none

SQL replicas
 
Not active

Notifications
 
Mails receivers
 

Plugins list
 
	formcreator          Name: Form Creator                   Version: 2.10.1     State: Not installed
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.9      State: Not installed
	yagp                 Name: yagp                           Version: 1.1.0      State: Not installed

[/code]

```

**Additional context**

Fresh install

**Comment by SwingJudge** [comment]
Hi,

i have the same problem, see my config

Log
`[2020-08-03 12:27:29] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /var/www/vhosts/innotec-sa.com/Serveurs/SI/inc/dropdown.class.php on line 157 in /var/www/vhosts/innotec-sa.com/Serveurs/SI/inc/dropdown.class.php at line 278
  Backtrace :
  inc/dropdown.class.php:157                         Dropdown::addNewCondition()
  inc/commondbtm.class.php:3910                      Dropdown::show()
  inc/commondbtm.class.php:4831                      CommonDBTM::dropdown()
  inc/ticket.class.php:6788                          CommonDBTM->getValueToSelect()
  ajax/dropdownMassiveActionField.php:99             Ticket->getValueToSelect()`

My config 
`Server
--
Operating system: Linux vpscloud.innotec-sa.com 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 PHP 7.2.32 fpm-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, 	ctype, curl, date, dba, dom, enchant, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, ionCube 	Loader, json, ldap, libxml, mbstring, mysqli, mysqlnd, odbc, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, 	pspell, redis, session, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, 	xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: nginx/1.16.1 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.31-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: si_innotec_bdu@si_innotec_bdd/si_innotec_bdd 	Host info: si_innotec_bdd via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.31) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/config has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_dumps has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_sessions has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_cron has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_graphs has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_lock has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_plugins has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_tmp has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_cache has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_rss has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_uploads has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_pictures has been validated. Write access to /var/www/vhosts/innotec-sa.com/Serveurs/SI/marketplace has been validated. Web access to files directory is protected PHP Warning (2): file_exists(): open_basedir restriction in effect. File(/usr/sbin/getenforce) is not within the allowed path(s): (/var/www/vhosts/innotec-sa.com/:/tmp/) in /var/www/vhosts/innotec-sa.com/Serveurs/SI/inc/system/requirement/selinux.class.php at line 51

GLPI_ROOT: /var/www/vhosts/innotec-sa.com/Serveurs/SI GLPI_CONFIG_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/config GLPI_VAR_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files GLPI_MARKETPLACE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_FORCE_NATIVE_SQL_TYPES: 1 GLPI_DOC_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files GLPI_CACHE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_cache GLPI_CRON_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_cron GLPI_DUMP_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_dumps GLPI_GRAPH_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_locales GLPI_LOCK_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_lock GLPI_LOG_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_log GLPI_PICTURE_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_plugins GLPI_RSS_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_rss GLPI_SESSION_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_sessions GLPI_TMP_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_tmp GLPI_UPLOAD_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/vhosts/innotec-sa.com/Serveurs/SI/locales GLPI_VERSION: 9.5.0 GLPI_SCHEMA_VERSION: 9.5.0 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/sabre/http/lib) sabre/uri in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/sabre/uri/lib) sabre/vobject in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/elvanto/litemoji/src) symfony/console in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/symfony/console) scssphp/scssphp in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/ramsey/uuid/src) psr/log in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/guzzlehttp/guzzle/src) wapmorgan/unified-archive in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/vhosts/innotec-sa.com/Serveurs/SI/vendor/paragonie/sodium_compat/src)

Not active

Way of sending emails: PHP

`
Additional context
it's too a fresh install, and i have the same problem with an upgrade from 9.3.2

**Comment by trasher** [comment]
I've just tried, and cannot reproduce. 
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)).

**Comment by SwingJudge** [comment]
Hi Trasher,

i just test with this [nightly build](https://github.com/glpi-project/glpi/actions/runs/197006196), and it's OK, thanks

**Comment by trasher** [comment]
Great, thanks for the feedback.
