### ISSUE TITLE
Bulk edit of fieldset( such values as Category, Manufacture Year)

### ISSUE THREAD

**Issue by Aa98765** [glpi-project/glpi#7819]
**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by btry** [comment]
see #7820
