### ISSUE TITLE
Bulk edit of fieldset( such values as Category, Manufacture Year)

### ISSUE THREAD

**Issue by Aa98765** [glpi-project/glpi#7820]
Hi,

Dear Snipe it staff,
I strongly recommend that you should make some changes in Bulk edit. Recently, we realized that we had to update the values of fieldset (such as Physically Labeled?,Manufacture Year, Operating System and Equipment belongs to which category?). And to update those values of fieldset the only way seems to be to do this one by one, manually editing each asset and updating the values. It realy creates a great discomfort since there are a large quantity of assets in inventory. Please, make it possible to bulk edit the mentioned vallues. I look forward to receiving your support.
Thanks in advance

Dear GLPI user.

BEFORE SUBMITTING YOUR ISSUE, please make sure to read and follow these steps:

* We don't support community plugins. Contact directly their authors, or use the community forum : https://forum.glpi-project.org.
* For feature requests or enhancements, use the suggest dedicated site (https://suggest.glpi-project.org). We check it very often.
* We prefer to keep this tracker in ENGLISH. If you want support in your language, the community forum (https://forum.glpi-project.org) is the best place.
* Please use the below template.

For more informations, please check contributing guide:
https://github.com/glpi-project/glpi/blob/master/CONTRIBUTING.md

The GLPI team.
-->

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cconard96** [comment]
I think you are looking for https://github.com/snipe/snipe-it/issues
This repository is for GLPI, not Snipe-IT.

**Comment by flegastelois** [comment]
For feature requests or enhancements, use the suggest dedicated site (https://suggest.glpi-project.org). We check it very often.
