### ISSUE TITLE
Mail Collector Bug

### ISSUE THREAD

**Issue by jgreenhalgh51** [glpi-project/glpi#7824]
GLPI 9.5.1

Hi , i have a bug with mail collector

Permanently , mail collector said user ou wrong password
I have verified user an password it's ok 

The log of mail collector

[2020-08-04 17:21:35] glpiphplog.ERROR: MailCollector::collect() in /var/www/html/inc/mailcollector.class.php line 691
An error occured trying to connect to collector. cannot read - connection closed?
 #0 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Imap.php(150): Laminas\Mail\Protocol\Imap->nextLine()
#1 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Imap.php(269): Laminas\Mail\Protocol\Imap->nextTaggedLine(NULL)
#2 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Imap.php(292): Laminas\Mail\Protocol\Imap->readLine(NULL, 'TAG1', true)
#3 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Imap.php(357): Laminas\Mail\Protocol\Imap->readResponse('TAG1', true)
#4 /var/www/html/vendor/laminas/laminas-mail/src/Protocol/Imap.php(413): Laminas\Mail\Protocol\Imap->requestAndResponse('LOGIN', Array, true)
#5 /var/www/html/vendor/laminas/laminas-mail/src/Storage/Imap.php(217): Laminas\Mail\Protocol\Imap->login('it@XXX.fr', Password)
#6 /var/www/html/inc/toolbox.class.php(2324): Laminas\Mail\Storage\Imap->__construct(Object(stdClass))
#7 /var/www/html/inc/mailcollector.class.php(1309): Toolbox::getMailServerStorageInstance('imap', Array)
#8 /var/www/html/inc/mailcollector.class.php(685): MailCollector->connect()
#9 /var/www/html/front/mailcollector.form.php(77): MailCollector->collect('3', 1)
#10 {main}  {"user":"2@SFCNGLPIITFCN"}

**Comment by jgreenhalgh51** [comment]
Ok i have find the problem 

not special caractères in password

**Comment by lgpdmap** [comment]
> Ok, eu encontrei o problema
> 
> caracteres não especiais na senha
thanks!
