### ISSUE TITLE
After update GLPI 9.4.5 to 9.5.1 the ldap connection no longer works

### ISSUE THREAD

**Issue by TOH2F** [glpi-project/glpi#7838]
Hello All, Bonjour à tous,

Voici mon problème :

Execute command line : 
/opt/www/html/glpitest/bin/console ldap:sync --ldap-server-id 2 -n

Error message 
Toolbox::sodiumDecrypt() in /opt/www/html/glpitest/inc/toolbox.class.php line 296
Unable to decrypt content. It may have been crypted with another key. PHP Warning:  ldap_parse_result() expects parameter 2 to be resource, bool given in /opt/www/html/glpitest/inc/authldap.class.php on line 1678
Erreur lors du contact du serveur LDAP "2".
In connexion web interface :

Identifiant ou mot de passe incorrect
Impossible de joindre l'annuaire LDAP

Se reconnecter

[2020-08-11 16:03:04] glpiphplog.ERROR: Toolbox::sodiumDecrypt() in /opt/www/html/glpitest/inc/toolbox.class.php line 296
Unable to decrypt content. It may have been crypted with another key.  {"user":"2067@risa.epsm-stvenant.net"}
[2020-08-11 16:03:57] glpiphplog.DEBUG: Html::compileScss() in /opt/www/html/glpitest/inc/html.class.php line 7394
css/palettes/auror.scss is new, loading  {"user":"2067@risa.epsm-stvenant.net"}
[2020-08-11 16:03:57] glpiphplog.DEBUG: Html::compileScss() in /opt/www/html/glpitest/inc/html.class.php line 7394
css/styles.scss is new, loading  {"user":"2067@risa.epsm-stvenant.net"}
[2020-08-11 16:04:25] glpiphplog.WARNING: Test logger
[2020-08-11 16:04:28] glpiphplog.ERROR: Toolbox::sodiumDecrypt() in /opt/www/html/glpitest/inc/toolbox.class.php line 296
Unable to decrypt content. It may have been crypted with another key.  {"user":"@risa.epsm-stvenant.net"}
[2020-08-11 16:04:28] glpiphplog.WARNING:   *** PHP Warning (2): ldap_parse_result() expects parameter 2 to be resource, bool given in /opt/www/html/glpitest/inc/authldap.class.php at line 1678
  Backtrace :
  inc/authldap.class.php:1678                        ldap_parse_result()
  inc/authldap.class.php:1837                        AuthLDAP::searchForUsers()
  ...sole/ldap/synchronizeuserscommand.class.php:279 AuthLDAP::getAllUsers()
  vendor/symfony/console/Command/Command.php:255     Glpi\Console\Ldap\SynchronizeUsersCommand->execute()
  vendor/symfony/console/Application.php:1000        Symfony\Component\Console\Command\Command->run()
  inc/console/application.class.php:232              Symfony\Component\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:271         Glpi\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:147         Symfony\Component\Console\Application->doRun()
  bin/console:102

**Comment by ladenree76000** [comment]
password encrypting has changed.
you should type your password again in setup>autentication>ldap

**Comment by TOH2F** [comment]
Hello indeed that to solve the problem thank you for your contribution!

**Comment by cedric-anne** [comment]
Hi,

#7782 should help to prevend passwords corruption during upgrade.

I close this issue as problem has been solved.

Regards

**Comment by j0hn97** [comment]
> password encrypting has changed.
> you should type your password again in setup>autentication>ldap

ça a marché pour moi merci beaucoup

**Comment by cpasDav** [comment]
I have upgraded from 9.4.7 to 9.5.2 and I also have this problem.
From LDAP settings, the LDAP connexion test is fine.
However I can't sync users neither log in using ldap account.

Any idea?
