### ISSUE TITLE
Upload files with the "follow-up" or with "documents"

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#7840]
**Describe the bug**

When we upload files (PNG, PDF etc ...) by the "follow-up" the attachments is missing in the notifications (by mail).
When we upload files (PNG, PDF etc ...) by the menu "Documents" we receive the attachments.

In both cases, the documents are present in the ticket but 

GLPI 9.5.1
_Profile :_ Super-Admin
_Rights :_ chown -R www-data /var/www/glpi
chmod 775 -R /var/www/gpli

Notifications tested on Gmail and Microsoft Office 365.

For information, I have a second GLPI server on 9.5.0 but we exchange a lot by email with customers.

![image](https://user-images.githubusercontent.com/63521311/89991120-a5e07a80-dc83-11ea-81a4-3dd3fdd146be.png)
![image](https://user-images.githubusercontent.com/63521311/89991199-c4467600-dc83-11ea-84a3-f2aa82b8331a.png)

**Comment by cedric-anne** [comment]
Hi,

#7884 should fix your issue.

Regards

**Comment by stdglpi** [comment]
Thank you ! 👍 

@cedric-anne @trasher
