### ISSUE TITLE
 Add team to the project

### ISSUE THREAD

**Issue by IBRAMED** [glpi-project/glpi#7847]
It is not possible to add a member to the Project team, displays the following message:

"You are not allowed to perform this action."

Way:
Projects> Edit> Project Team Menu> Select a member or group> add button

* Only SuperAdmin user can successfully give this action, the rest cannot.

**Comment by IBRAMED** [comment]
The version is GLPI 9.5.1

**Comment by IBRAMED** [comment]
I don't know if this is the solution, but I found a light:

https://forum.glpi-project.org/viewtopic.php?id=155910

**Comment by trasher** [comment]
Sounds like this one is fixed; fixing ACLs should fix.
