### ISSUE TITLE
[GLPI 9.5.1]  license management : adding an element no longer works,  nothing is displayed

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#7853]
Create my licence
![1](https://user-images.githubusercontent.com/68054991/90404151-42e74d00-e0a2-11ea-86d8-adab4fb0bcee.jpg)

after add element but impossible with version glpi 9.5.1
nothing is displayed , i cant add my computers

![2](https://user-images.githubusercontent.com/68054991/90404195-55fa1d00-e0a2-11ea-963f-27f24b1f3035.png)

no error message is generated in the log php

With version 9.4.6, its OK

**Comment by steph461** [comment]
exemple before GLPI 9.5.1
![exmple ok](https://user-images.githubusercontent.com/68054991/90434241-607ddc00-e0cd-11ea-9629-5d84616e03a8.png)

**Comment by steph461** [comment]
The table glpi_computers_softwarelicenses (GLPI 9.4.6) was renamed by glpi_items_softwarelicenses with glpi 9.5.1 ? because the table glpi_computers_softwarelicenses doesn't exists with glpi 9.5.1
 
maybe the problem comes from this renaming

**Comment by steph461** [comment]
I test the fix, it's ko

but I go by computer then software, I can add it by this tab. Its ok
![Capture2](https://user-images.githubusercontent.com/68054991/90733478-e451e700-e2cc-11ea-90a4-0c01f091538c.PNG)
![Capture](https://user-images.githubusercontent.com/68054991/90733489-e6b44100-e2cc-11ea-9e33-ae0b485e585a.PNG)

==============================================================================
it is through management then license, it does not work
![Capture3](https://user-images.githubusercontent.com/68054991/90733655-24b16500-e2cd-11ea-9709-9857379e88cd.PNG)

==============================================================================
For the moment I go by computer, software and license. Its ok

**Comment by trasher** [comment]
#7865 is not supposed to fix this issue, this is only related to Transfer.

**Comment by trasher** [comment]
I've just tried with up to date 9.5/bugfixes branch, I do not reproduce. Either there is a setup/data difference that cause the issue, or it may have been fixed already. 
Ensure you switch to debug mode and keep an eye on your logs (both system and glpi) when the error raises.

Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)) and see if you still have the issue.

**Comment by steph461** [comment]
I try 9.5-bugfixes.bc72918.tar.gz 
same problem


But if I go through computer then software and license. I can make the link without problem.
I would do this by going through computer and without going through management and license
![Capture](https://user-images.githubusercontent.com/68054991/90773243-e7ad9880-e2f5-11ea-868c-e8188ff6f106.PNG)
![Capture2](https://user-images.githubusercontent.com/68054991/90773270-eed4a680-e2f5-11ea-80cc-e38b2dfe2e77.PNG)

**Comment by trasher** [comment]
Then I cannot reproduce, no more ideas for the moment.

**Comment by cedric-anne** [comment]
Hi,

This bug is almost invisible in english, but easilly reproduceable in other languages.

#7880 should fix it.

Regards

**Comment by steph461** [comment]
Its OK

My issues is resolve

Thx
