### ISSUE TITLE
OCS Inventory link Down

### ISSUE THREAD

**Issue by hobeur** [glpi-project/glpi#7857]
Hi in the documentation webapage :
the link to OCS Inventory
https://www.ocsinventory-ng.org/fr/
seems to be down

**Comment by orthagh** [comment]
Maybe you should ask to OCS developpers, we are not related to them. Regards

**Comment by orthagh** [comment]
oh could you point where we have an ocs link in our documentation please

**Comment by hobeur** [comment]
I thought you wouldn't want to have a dead link on the webpage 
https://github.com/glpi-project/glpi
search for "OCS Inventory" there's only one mention
have a nice day

**Comment by orthagh** [comment]
my bad, i though initially you pointed their site was in 404. Sorry for the harsh comment.
Will fix the link.
