### ISSUE TITLE
Date field is not editable + today button

### ISSUE THREAD

**Issue by HynekPetrak** [glpi-project/glpi#7858]
Hello,
it seems that with version 9.5.x
1. the date fields are not anymore directly editable and the date must be selected with calendar pop up.  I.e. you cannot write the date by hand as a text. This requires selecting additional effort, writing a year, selecting a month from drop-down and picking up the day. Is it possible to open the dates fields for direct edit again?
2. There is also no "today" button.
Imagine for instance the "Date of last physical inventory". Usually you update this field with today's date. In case the field has been filled in the past you need to select year, month, day through the calendar pop up. Having a today button is straightforward.

**Comment by J-C-P** [comment]
Additionnaly, I would like to mention that if the field is empty, and if you click in the field then click somewhere alse on the page, the current date is selected  BUT not the current time.
