### ISSUE TITLE
transfer ticket when transfer equipment

### ISSUE THREAD

**Issue by Sismic** [glpi-project/glpi#786]
Hello

When transferring of equipment, would it be possible to have the opportunity to also transfer the tickets?

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
