### ISSUE TITLE
Incorrect ticket's description encoding

### ISSUE THREAD

**Issue by mdorobisz** [glpi-project/glpi#7861]
Hello,
after upgrade GLPI from 9.4 to 9.5.1 we observe incorrect mail receiver work. All e-mails sent to the mailbox are imported as new tickets, but ticket's description has incorrect encoding. 

Message sent looks like that:
![Zrzut ekranu 2020-08-19 o 10 33 22](https://user-images.githubusercontent.com/69894057/90611800-7ee7f280-e207-11ea-9a0c-b06ab1654a01.png)
[Test email.eml.zip](https://github.com/glpi-project/glpi/files/5095055/Test.email.eml.zip)

But in GLPI:
![Zrzut ekranu 2020-08-19 o 10 35 59](https://user-images.githubusercontent.com/69894057/90612049-ce2e2300-e207-11ea-8959-144b6b80a85e.png)

**Comment by trasher** [comment]
Duplicates https://github.com/glpi-project/glpi/issues/7709
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)).
