### ISSUE TITLE
[9.5.0 + 9.5.1] glpi_items_softwareversions deleted on transfer for ALL COMPUTERS

### ISSUE THREAD

**Issue by Kaefer1303** [glpi-project/glpi#7864]
Hi,
When I move one ore more computers to another entity (transfer list) I lose the connection between Software and all computers in my GLPI
To reconnect the Software I have to do an inventory of all computers.

If my research is correct, the table "glpi_items_softwareversions" is the link between software and computer!?
this table is empty after each computer transfer to another entity.

I installed a new testing GLPI 9.5.1 system and tried a few settings. The same thing happens there.

I have saved a mysql query logfile from the moment I click on "execute".
I can post it if required.

my System:
GLPI 9.5.1 with fusioninventory 9.5.0+1.0
Ubuntu Server 20.04 LTS
Apache 2.4.41
PHP 7.4.3
MariaDB 10.3.22

**Comment by steph461** [comment]
before this table called glpi_computers_softwarelicenses look my issues #7853

**Comment by cedric-anne** [comment]
Hi,

Can you check if #7865 fixes the issue ?

Regards

**Comment by steph461** [comment]
I test the fix, it's ko

but I go by computer then software, I can add it by this tab. Its ok
![Capture2](https://user-images.githubusercontent.com/68054991/90733478-e451e700-e2cc-11ea-90a4-0c01f091538c.PNG)
![Capture](https://user-images.githubusercontent.com/68054991/90733489-e6b44100-e2cc-11ea-9e33-ae0b485e585a.PNG)


it is through management then license, it does not work
![Capture3](https://user-images.githubusercontent.com/68054991/90733655-24b16500-e2cd-11ea-9709-9857379e88cd.PNG)


For the moment I go by computer, software and license. Its ok

**Comment by Kaefer1303** [comment]
Hi,
changing the file inc/transfer.class.php did not fix my issue.
I don't habe the  tests/functionnal/Computer.php
let me know if there is anything else I can test or do.
Regards
Kai

**Comment by trasher** [comment]
Depending on your configuration (opcode among others), you may have to restart your PHP server to be sure changes are loaded.

Is it still not work; double check the fix has been properly applied; empty your logs, and then reproduce the issue; and check the logs. Please also check in database what's for those software, software_version and item_softwareversion.

**Comment by Kaefer1303** [comment]
I did restart apache2 service each time before testing.
Evrytime the same happens. The Table items_softwareversions is empty after a transfer.
softwares and softwareversions are still filled and show in GLPI with 0 installations.
I attached a new mysql logfile from the Moment i clicked on "execute".
Are there any logs I should look into?

[mysql.log](https://github.com/glpi-project/glpi/files/5102666/mysql.log)

**Comment by Kaefer1303** [comment]
Hi,
i did a new test on a different webserver to rule out my specific setting.
New glpi 9.5.1 setup on:
Apache/2.4.6 (CentOS 7) OpenSSL/1.0.2k-fips PHP/7.2.33

still the same problem there.

**Comment by trasher** [comment]
@Kaefer1303 could you please test if #7967 does solve your issue?

**Comment by Kaefer1303** [comment]
Yes, is does solve the issue on both testing and my main GLPI.
Thank you @trasher!

**Comment by trasher** [comment]
Thanks for the feedback
