### ISSUE TITLE
Problem when going to fullscreen with ticket content

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#787]
Hello,
When using the 'fullscreen' feature of tinymce, I get this:
![image](https://cloud.githubusercontent.com/assets/7569958/16620265/140a6564-4392-11e6-8153-67b2d38c060b.png)
With IE 10, Firefox 44 and Chrome 51
Regards,
Tomolimo

**Comment by orthagh** [comment]
fixed yesterday, please update

**Comment by tomolimo** [comment]
I've updated yesterday after your last commit of 15:22

**Comment by tomolimo** [comment]
Ok, I see the fix was after my last refresh in style.css

**Comment by tomolimo** [comment]
After refresh the problem is still present...

**Comment by tomolimo** [comment]
oups sorry again, forget my last post, I made the test on previous refresh :)

**Comment by tomolimo** [comment]
Now I get this:
![image](https://cloud.githubusercontent.com/assets/7569958/16621948/6f2c132e-4398-11e6-95dd-d73193cc7aea.png)
This is perfect!
Thank you,
Tomolimo

**Comment by orthagh** [comment]
error messages are a paste,right ?

**Comment by tomolimo** [comment]
yes, :smiley:

**Comment by tomolimo** [comment]
sorry for confusing

**Comment by orthagh** [comment]
i though (2 seconds) you was sarcastic with this message : This is perfect!

**Comment by tomolimo** [comment]
No, I was not: this is really perfect :smile:
