### ISSUE TITLE
[GLPI 9.5.0]Help Automatic Task

### ISSUE THREAD

**Issue by edgarfabiancalderon** [glpi-project/glpi#7870]
**Describe the bug**

update glpi 9.4.4 to the new version 9.5.0 but when I go to the automatic tasks I get this

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Go to 'Automatic Task'
2. See error
![image](https://user-images.githubusercontent.com/64982932/90830738-dc636880-e307-11ea-95bd-f79d3613a6f5.png)

SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '``.`id` AS `ITEM_CronTask_3`, `glpi_crontasks`.`state` AS `ITEM_CronTask_4`,...' at line 4 in query "SELECT DISTINCT `glpi_crontasks`.`id` AS id, 'Admin' AS currentuser, `glpi_crontasks`.`name` AS `ITEM_CronTask_1`, `glpi_crontasks`.`id` AS `ITEM_CronTask_1_id`, `glpi_crontasks`.`itemtype` AS `ITEM_CronTask_8`, ``glpi_crontasks``.`id` AS `ITEM_CronTask_3`, `glpi_crontasks`.`state` AS `ITEM_CronTask_4`, `glpi_crontasks`.`lastrun` AS `ITEM_CronTask_7` FROM `glpi_crontasks` ORDER BY ITEM_CronTask_1 ASC LIMIT 0, 20"

Help

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on GLPI 9.5.1. Can you try on your side ? Maybe this bug has already been solved.

Regards

**Comment by kofe88** [comment]
I have same bug, pls help. GLPI 9.5.1, upgraded from 9.4.6
SQL Error "1064": You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '``.`id` AS `ITEM_CronTask_3`, `glpi_crontasks`.`state` AS `ITEM_CronTask_4`, `' at line 4 in query "SELECT DISTINCT `glpi_crontasks`.`id` AS id, 'glpi' AS currentuser, `glpi_crontasks`.`name` AS `ITEM_CronTask_1`, `glpi_crontasks`.`id` AS `ITEM_CronTask_1_id`, `glpi_crontasks`.`itemtype` AS `ITEM_CronTask_8`, ``glpi_crontasks``.`id` AS `ITEM_CronTask_3`, `glpi_crontasks`.`state` AS `ITEM_CronTask_4`, `glpi_crontasks`.`lastrun` AS `ITEM_CronTask_7` FROM `glpi_crontasks` ORDER BY ITEM_CronTask_1 ASC LIMIT 0, 20"
![err1](https://user-images.githubusercontent.com/16879167/90990949-1b1a4c80-e5ae-11ea-9209-517b741ddb12.JPG)

**Comment by cedric-anne** [comment]
Hi,

Same problem appeared in #7843 and was not reproduceable on a freshly installed instance.

Do you use php-fpm ? In this case, can you try to restart PHP service ? Maybe this bug comes from an unescpected behaviour in PHP cache.

Regards

**Comment by edgarfabiancalderon** [comment]
Hi 

fix the error according to this case in the GLPI forum
https://forum.glpi-project.org/viewtopic.php?id=278862

I quote jaferrer's answer

"Finalmente resolví el problema. Borré todo el contenido del directorio de GLPI con excepción de los directorio files/ y config/ Luego volví a descomprimir el tar del GLPI 9.5.1 en el mismo directorio y luego de eso, pude ver el contenido de las tareas automáticas, como también los computadores. Revisé además todos los menú del GLPI verirficando que no arrojaran error en el archivo files/_log/sql-errors.log.-

Con ello quedó operativo."


"I finally solved the problem. I deleted all the contents of the GLPI directory with the exception of the files / and config / directories. Then I unzipped the GLPI 9.5.1 tar in the same directory and after that, I was able to see the contents of the automatic tasks, as well as the computers. Also check all the GLPI menus verifying that they will not throw an error in the files / _log / sql-errors.log file.

With this it was operational."



Although it worked at first and I also needed to update my glpi because it had 9.5.0

the same error returned from one moment to another


I started looking at the SQL LOG

![image](https://user-images.githubusercontent.com/64982932/91069490-192aaa80-e5fb-11ea-9543-d844699b3536.png)


Notice that the error occurred in the search.class.php file
look at the path and I had two of these the .bak and the one that was using the GLPI what I did was rename the one that was using glpi for
search.class.php.old
and the .bak for
search.class.php
I restarted apacha and the automatic tasks worked again

![image](https://user-images.githubusercontent.com/64982932/91069844-84747c80-e5fb-11ea-8617-a926a08eeea5.png)


I really don't know why this error occurs because I had to fix it immediately but this is how I solved it
![image](https://user-images.githubusercontent.com/64982932/91069970-b4bc1b00-e5fb-11ea-8f8f-a3c397ab8643.png)

**Comment by cedric-anne** [comment]
Hi,

> Notice that the error occurred in the search.class.php file
> look at the path and I had two of these the .bak and the one that was using the GLPI what I did was rename the one that was using glpi for
> search.class.php.old
> and the .bak for
> search.class.php

I do not understand how you can have a `search.class.php.bak` if you removed source files and reinstalled them from the release archive. Was is present in the "tar" file you used ? Is this the tool you use to upload files in your server that creates automatically these "bak" files ?

Regards

**Comment by edgarfabiancalderon** [comment]
Good question but really only leave the config folders and the rest files, I delete them, I don't know why GLPI created me two search.class.php I only know they were when I looked at the sql log mentioned above
