### ISSUE TITLE
[GLPI 9.5.1]Does not accept encoding (Cyrillic (Windows), Cyrillic (KOI8-R), Windows-1251) in email.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#7876]
1. Send mail with Russian words from MS Outlook in Cyrillic (Windows) or Cyrillic (KOI8-R) or Windows-1251 encoding.
2. Receive mail in MDaemon server.
3. Grab from MDaemon server via IMAP
4. Automatic create new ticket.
5. Bad text encoding in ticket
![err2](https://user-images.githubusercontent.com/16879167/90991418-9f220380-e5b1-11ea-9d96-f9d608e9926c.JPG)

In 9.4.6 this working good.

**Comment by cedric-anne** [comment]
Hi,

It duplicates #7709 and has been fixed by #7748.

Regards

**Comment by danielrodrigsand** [comment]
> 1. Envíe correo con palabras en ruso desde MS Outlook en codificación cirílico (Windows) o cirílico (KOI8-R) o Windows-1251.
> 2. Reciba correo en el servidor MDaemon.
> 3. Tomar del servidor MDaemon a través de IMAP
> 4. Creación automática de un nuevo ticket.
> 5. Codificación de texto incorrecta en el ticket
>    ![err2](https://user-images.githubusercontent.com/16879167/90991418-9f220380-e5b1-11ea-9d96-f9d608e9926c.JPG)
> 
> En 9.4.6 esto funciona bien.
Hello, you could share your mail receiver settings using an email from mdaemon server, it doesn't want to work for me. I'm using GLPI 9.5.2
