### ISSUE TITLE
Dropdown::addNewCondition() error on helpdesk interface

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7877]
![image](https://user-images.githubusercontent.com/13178158/91058838-3e361200-e629-11ea-876d-a9e30d18d026.png)

https://github.com/glpi-project/glpi/blob/0f00acaa8c7700add2756aa1fd2393ac11e71e6c/inc/commonitilobject.class.php#L3387

must be replaced by $newtab['condition']         = ['is_helpdeskvisible' => 1];

**Comment by cedric-anne** [comment]
Hi,

#7878 should fix this.

Regards
