### ISSUE TITLE
Critical error : MailCollector with an email who contain empty subject

### ISSUE THREAD

**Issue by mat44444** [glpi-project/glpi#7886]
**Describe the bug**

When a email with empty subject is in MailCollector box we got:
Blank page when launch manually the process,
Or the job is stunc in status: In process in the automatic job

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Have a working MailCollector on a configured mailbox
2. Send a email with empty subject
3. Force  the mail collector to launch

**Expected behavior**

At least, handle the error, log a warning and skip the mail.
The better option, should be replys to the sender and said the request could not be handle because there not subject in email and flush the email

**Logs**

```
[2020-08-26 13:05:15] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Storage\Exception\InvalidArgumentException: Header with Name subject or subject not found in /opt/www/gri.dmz.urgences-sante.qc.ca/html/vendor/laminas/laminas-mail/src/Storage/Part.php at line 307
  Backtrace :
  ...r/laminas/laminas-mail/src/Storage/Part.php:376 Laminas\Mail\Storage\Part->getHeader()
  inc/mailcollector.class.php:1035                   Laminas\Mail\Storage\Part->__get()
  inc/mailcollector.class.php:734                    MailCollector->buildTicket()
  front/mailcollector.form.php:77                    MailCollector->collect()
  

```

**Screenshots**

![image](https://user-images.githubusercontent.com/8290219/91310811-553b4800-e780-11ea-8af1-84327588bc48.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```

```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

It duplicates #7790 and has been fixed in #7748.

Regards
