### ISSUE TITLE
Uncaught Exception Error: Call to a member function listTables() on null in /var/www/glpi/inc/config.class.php at line 2915

### ISSUE THREAD

**Issue by tigerblue77** [glpi-project/glpi#7888]
Hello,

I encounter a bug when upgrading from 9.5.0 to 9.5.1

**Describe the bug**

This message appears on the glpi web page when installing (step after choosing database) : Uncaught Exception Error: Call to a member function listTables() on null in /var/www/glpi/inc/config.class.php at line 2915

**Page(s) URL**

http://glpi-server-hostname/glpi/install/install.php

**To reproduce**

1. Install v9.5.1 in GLPI directory
2. chown -R www-data: /var/www/glpi/*
3. Go to your glpi web server
4. Follow installation steps
5. After checking the database to update, see error

**Expected behavior**

I expected installation to run

**Comment by cedric-anne** [comment]
Hi,

It duplicates #7707 and has been fixed in #7706.

Regards
