### ISSUE TITLE
tasks by mail case 

### ISSUE THREAD

**Issue by edgarfabiancalderon** [glpi-project/glpi#7889]
I currently have created some task templates for the emails and it works

![](https://i.imgur.com/LbVarkB.png)

But when the cases are created by email, the template does not work because this happens and if they help me to solve it

![](https://i.imgur.com/zsDjk8M.png)

GLPI 9.5.0
Centos 7
Thanks

**Comment by edgarfabiancalderon** [comment]
ok I wanted to see what happened when a case was created and this is what I got

Array
(
    [_tasktemplates_id] => Array
        (
            [0] => 3
        )

    [date] => 
    [time_to_own] => 
    [slas_id_tto] => 0
    [time_to_resolve] => 
    [slas_id_ttr] => 0
    [internal_time_to_own] => 
    [internal_time_to_resolve] => 
    [type] => 1
    [itilcategories_id] => 45
    [_users_id_requester] => 2
    [_users_id_requester_notif] => Array
        (
            [use_notification] => Array
                (
                    [0] => 1
                )

            [alternative_email] => Array
                (
                    [0] => edgarc@suppliesdc.com
                )

        )

    [entities_id] => 0
    [_groups_id_requester] => 0
    [_users_id_observer] => Array
        (
            [0] => 0
        )

    [_users_id_observer_notif] => Array
        (
            [use_notification] => Array
                (
                    [0] => 1
                )

            [alternative_email] => Array
                (
                    [0] => 
                )

        )

    [_groups_id_observer] => 0
    [_users_id_assign] => 2
    [_users_id_assign_notif] => Array
        (
            [use_notification] => Array
                (
                    [0] => 1
                )

            [alternative_email] => Array
                (
                    [0] => edgarc@suppliesdc.com
                )

        )

    [_groups_id_assign] => 0
    [_suppliers_id_assign] => 0
    [_suppliers_id_assign_notif] => Array
        (
            [use_notification] => Array
                (
                    [0] => 1
                )

            [alternative_email] => Array
                (
                    [0] => 
                )

        )

    [status] => 1
    [requesttypes_id] => 1
    [urgency] => 3
    [_add_validation] => 0
    [validatortype] => 0
    [impact] => 4
    [locations_id] => 0
    [priority] => 3
    [my_items] => 
    [itemtype] => 0
    [items_id] => 0
    [actiontime] => 0
    [name] => ASD
    [content] => 
ASDASD


    [_link] => Array
        (
            [link] => 1
            [tickets_id_1] => 0
            [tickets_id_2] => 0
        )

    [add] => Agregar
    [_tickettemplate] => 1
    [_predefined_fields] => eyJfdGFza3RlbXBsYXRlc19pZCI6WyIzIl0sImltcGFjdCI6IjQifQ==
    [_promoted_fup_id] => 0
    [_skip_promoted_fields] => 1
    [id] => 0
    [_glpi_csrf_token] => ab8e909bba53bc25781c587320613961c680a9d7fa0dd0d63d1cb34bad32e787
)

**Comment by edgarfabiancalderon** [comment]
I guess this array is the order to insert the task

Array
(
[_tasktemplates_id] => Array
(
[0] => 3
)


But I don't know if it is different when creating a case by email

**Comment by cedric-anne** [comment]
Hi @edgarfabiancalderon ,

I am not sure to understand what you want to do.

Can you describe preceisely what you have done and what you expect ?

Regards
