### ISSUE TITLE
Move Assets from Network to Computers or other catergory

### ISSUE THREAD

**Issue by mskrishna20051974** [glpi-project/glpi#7892]
We have several NAS which are detected as NAS. There is no way we can move them to Computers or to a different category. Is this something which can be fixed?

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
