### ISSUE TITLE
GLPI 9.5.1 language is not correctly appears.

### ISSUE THREAD

**Issue by Nervari** [glpi-project/glpi#7899]
Hi!
We updated our GLPI from 9.5 to 9.5.1 and we see, that translation on LV language is not correctly appears.
For example: types in 9.5v was "tipi", but it 9.5.1 left "Types", same with dashboard, in dashboard all in ENG, but was in LV.

Is any solutions, how to translate in LV?

**Comment by cedric-anne** [comment]
Hi,

You can take part in translation enhancements in Transifex: https://www.transifex.com/glpi/GLPI/language/lv_LV/ .

Regards

**Comment by Nervari** [comment]
Hi,
I see percents, but how it’s helps me?


[cid:image001.png@01D67F9F.6DBF9CD0]



ar cieņu,

Marija Starodubova
Informācijas sistēmu atbalsta departaments
Lietotāju atbalsts nodaļa
Datorsistēmu un datortīklu administratore

Valsts reģionālās attīstības aģentūra
Alberta iela 10, Rīga
+371 29591277

**Comment by cedric-anne** [comment]
Transifex is a translation service. If you registered on it, we could add you to the translation team, and you would be able to propose new translations.

**Comment by Nervari** [comment]
OK, "You joined the Latvian (Latvia) (lv_LV) language."
What's next?

**Comment by cedric-anne** [comment]
You should read the service documentation: https://docs.transifex.com/getting-started-1/translators

**Comment by Nervari** [comment]
Yes, it's all done.
But where I may start to translate?
