### ISSUE TITLE
[GLPI 9.4 - 9.4.5] Datetimepicker issue

### ISSUE THREAD

**Issue by artemlevenets** [glpi-project/glpi#7900]
There are an issue with GLPI Datetimepicker in GLPI 9.4 - 9.4.5.
Steps to reproduce:
1) Go to the ticket form (creation or update form doesn`t matter).
2) Click on the Time to Resolve datetimepicker.
3) Click Now twice.
4) The dateteime picker sets current time with -1 hour.
The same behaivour at any datetimepicker field in GLPI.
Issue also is in the GLPI 9.5.0-dev (https://demo.glpi-project.org/)

![Annotation 2020-08-31 163557](https://user-images.githubusercontent.com/35097625/91725924-11917580-eba8-11ea-871c-573c92c0d911.png)

**Comment by trasher** [comment]
I think this issue has been solved already. Old demo is not up to date; please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)).
