### ISSUE TITLE
Problem printers display with external links with GLPI 9.5.x

### ISSUE THREAD

**Issue by Dankenobi** [glpi-project/glpi#7915]
Hi,

When I  want to display all printers attached on sub-entites, Printers are not display on screen. Problem is due to "external link" on global or personal view. If I uncheck "external link" all printers are display ! 
I test it on 2 GLPI Instances with differently databases and I have the same problem and the samething with GLPI demo on 9.5.0-dev

I have this error :

SQL Error "1630": FUNCTION glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f.id does not exist. Check the 'Function Name Parsing and Resolution' section in the Reference Manual in query "SELECT DISTINCT `glpi_printers`.`id` AS id, 'xxxxxxxx' AS currentuser, `glpi_printers`.`entities_id`, `glpi_printers`.`is_recursive`, `glpi_printers`.`name` AS `ITEM_Printer_1`, `glpi_printers`.`id` AS `ITEM_Printer_1_id`, `glpi_entities`.`completename` AS `ITEM_Printer_80`, `glpi_states`.`completename` AS `ITEM_Printer_31`, `glpi_manufacturers`.`name` AS `ITEM_Printer_23`, `glpi_locations`.`completename` AS `ITEM_Printer_3`, `glpi_printertypes`.`name` AS `ITEM_Printer_4`, `glpi_printermodels`.`name` AS `ITEM_Printer_40`, `glpi_printers`.`date_mod` AS `ITEM_Printer_19`, `glpi_printers`.`comment` AS `ITEM_Printer_16`, `glpi_users`.`name` AS `ITEM_Printer_70`, `glpi_users`.`realname` AS `ITEM_Printer_70_realname`, `glpi_users`.`id` AS `ITEM_Printer_70_id`, `glpi_users`.`firstname` AS `ITEM_Printer_70_firstname`, `glpi_printers`.`serial` AS `ITEM_Printer_5`, `glpi_printers`.`have_ethernet` AS `ITEM_Printer_45`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`name`, '__NULL__'), '$#$',`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`id`) ORDER BY `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`id` SEPARATOR '$$##$$') AS `ITEM_Printer_126`, GROUP_CONCAT(DISTINCT ADDDATE(`glpi_infocoms`.`warranty_date`, INTERVAL (`glpi_infocoms`.`warranty_duration` ) MONTH) SEPARATOR '$$##$$') AS `ITEM_Printer_120`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_plugin_manufacturersimports_models`.`model_name`, '__NULL__'), '$#$',`glpi_plugin_manufacturersimports_models`.`id`) ORDER BY `glpi_plugin_manufacturersimports_models`.`id` SEPARATOR '$$##$$') AS `ITEM_Printer_2150`, `glpi_printers`.`id` AS `ITEM_Printer_2`, `glpi_printers`.`is_recursive` AS `ITEM_Printer_86`, `glpi_printers`.`is_global` AS `ITEM_Printer_82`, `glpi_locations`.`address` AS `ITEM_Printer_101`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id`, '__NULL__'), '$#$', `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_id`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`link`, '__NULL__'), '$#$', `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_link`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`name`, '__NULL__'), '$#$', `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_name`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`data`, '__NULL__'), '$#$', `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_data`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`open_window`, '__NULL__'), '$#$', `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_open_window` FROM `glpi_printers`LEFT JOIN `glpi_entities` ON (`glpi_printers`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_states` ON (`glpi_printers`.`states_id` = `glpi_states`.`id` )LEFT JOIN `glpi_manufacturers` ON (`glpi_printers`.`manufacturers_id` = `glpi_manufacturers`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_printers`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_printertypes` ON (`glpi_printers`.`printertypes_id` = `glpi_printertypes`.`id` )LEFT JOIN `glpi_printermodels` ON (`glpi_printers`.`printermodels_id` = `glpi_printermodels`.`id` )LEFT JOIN `glpi_users` ON (`glpi_printers`.`users_id` = `glpi_users`.`id` ) LEFT JOIN `glpi_ipaddresses` AS `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540` ON (`glpi_printers`.`id` = `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitems_id` AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitemtype` = 'Printer' AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`is_deleted` = 0 ) LEFT JOIN `glpi_infocoms` ON (`glpi_printers`.`id` = `glpi_infocoms`.`items_id` AND `glpi_infocoms`.`itemtype` = 'Printer' ) LEFT JOIN `glpi_plugin_manufacturersimports_models` ON (`glpi_printers`.`id` = `glpi_plugin_manufacturersimports_models`.`items_id` AND `glpi_plugin_manufacturersimports_models`.`itemtype` = 'Printer' ) LEFT JOIN `glpi_links_itemtypes` ON (`glpi_links_itemtypes`.`itemtype` = 'Printer' ) LEFT JOIN `glpi_links` AS `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f` ON (`glpi_links_itemtypes`.`links_id` = `glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`id` (`glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f`.`entities_id` IN ('2')) ) WHERE `glpi_printers`.`is_deleted` = 0 AND `glpi_printers`.`is_template` = 0 AND ( `glpi_printers`.`entities_id` IN ('2') OR (`glpi_printers`.`is_recursive`='1' AND `glpi_printers`.`entities_id` IN (0)) ) GROUP BY `glpi_printers`.`id` ORDER BY ITEM_Printer_1 ASC LIMIT 0, 50"

But on Root entities it's Ok, Printers are display on screen. All printers are attached to sub-entities and sub-entities profile is ok to display correctly.

http://srvglpi/glpi/front/printer.php

**Comment by trasher** [comment]
Seems there is a missing operator (just before the WHERE clause):
```sql
glpi_links_itemtypes.links_id = glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f.id (glpi_links_77bfaf6d8fe833f65cecbb61bf730e5f.entities_id IN ('2'))`
```

**Comment by ToFz** [comment]
Hi, I have the same problem, have you a solution ? thx

**Comment by cedric-anne** [comment]
Hi,

#7930 should fix your issue.

Regards

**Comment by ToFz** [comment]
Thx its OK for me 👍

**Comment by trasher** [comment]
Thanks for the feedback :)
