### ISSUE TITLE
Input Box missing when starting a Query with Global Search Criterias

### ISSUE THREAD

**Issue by wagneral** [glpi-project/glpi#792]
When starting a query by entering a global search criteria to filter the ticket list, the last input box for attributes is not visible after pushing the search button. The result is correct, but the box is simply not displayed - so it's difficult to reproduce the criteria when re-entering the site. Futhermore you are not able to change the attribute unless you delete the criteria and add a new one.

The Screenshot shows the view after pushing the search button (global criteria: technician is glpi)

![glpi_search_criteria](https://cloud.githubusercontent.com/assets/6931503/16680268/b4a95050-44ed-11e6-9ed1-803d7218c1c6.png)

**Comment by wagneral** [comment]
When starting a query by entering a global search criteria to filter the ticket list, the last input box for attributes is not visible after pushing the search button. The result is correct, but the box is simply not displayed - so it's difficult to reproduce the criteria by re-entering the site. Futhermore you are not able to change the attribute unless you delete the criteria and add a new one.
![glpi_search_criteria](https://cloud.githubusercontent.com/assets/6931503/16680268/b4a95050-44ed-11e6-9ed1-803d7218c1c6.png)

**Comment by yllen** [comment]
No problem for me with version of today

**Comment by orthagh** [comment]
fixed by 64dbe20e3f096b9ebe637f4f3a7466d35d407e21
