### ISSUE TITLE
Moreticket plugin form marketplace GLPI 9.5.1

### ISSUE THREAD

**Issue by 99net** [glpi-project/glpi#7932]
The Moreticket plugin installed from the Marketplace blocks the display of the ticket list in GLPI 9.5.1. 
After installing the plugin from Marketplace and setting "Postponement date" in the ticket display list casues all list disappears.

Solution is to remove plugin from marketplace folder and manual upload to plugin folder.

![postponed](https://user-images.githubusercontent.com/43380069/92222816-da6cde00-ee9f-11ea-8dde-251dfeb67781.png)

**Comment by cedric-anne** [comment]
Hi,

This error seems related to the plugin itself. Please open an issue on their repository ( https://github.com/InfotelGLPI/moreticket/ ).
If they found an use case that is not handled in GLPI, they may reopen this issue and add some technical details to help us investigate.

Regards

**Comment by 99net** [comment]
thx
