### ISSUE TITLE
La date d'installation n’apparaît pour les machines sous debian 10

### ISSUE THREAD

**Issue by chris4269** [glpi-project/glpi#7933]
Comme indiquée dans le titre la date d installation n'apparait dans la fiche ordinateur pour une machine debian
pas de pb pour windows 2012 & 2008 & 2019

Version 
GLPI 9.5.1 Copyright (C) 2015-2020 Teclib' and contributors
FusionInventory 9.5.0+1.0 - Copyleft © 2010-2019 by FusionInventory Team

Agent 1:2.5.2-1

**Comment by trasher** [comment]
Use only english.
You provided too few information; your issue sounds to be a inventory issue; you should report that against the plugin.
