### ISSUE TITLE
[9.5.1] Saved searches list doesn't include is_private field

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#7936]
**Describe the bug**

The listing doesn't allow to see which of the saved searches are global, and which ones are private. Nor is it possible to make a mass action to set the selected ones to private or global.

**Page(s) URL**

/front/savedsearch.php

**To reproduce**

1. Go to 'Tools>Saved Searches'
2. The list shows all private and global searches, but you don't know which are which
3. Click on the "Tool" icon in order to "Select default items to show". Note that there's no way to select the private/global field
4. Close the window
5. Tick some of the Saved searches
6. Click on "Action"
7. Note that there is no possibility to update the private/global field
8. Note also, that the "Visibility" field is not the field we are looking for, but defines in which entities the search will be shown

**Expected behavior**

In steps 3 and 7, there should be a way to select the private/global field

As in previous versions (e.g. 9.1.3) it was possible to see the private and the global saved searches separately, you would know at any time if you were editing a private or a global saved search. Here it's only possible to see once you clicked on the search to edit, this is why I consider this a regression bug.

**Comment by trasher** [comment]
This is not a bug, but a "missing" feature. Adding the search option on private field (add to search and displayed rows) can be done anyways.

Adding a massive action would require more work; as we need to take care of users_id field when the private status changes; please use [suggestion website](http://suggest.glpi-project.org).
