### ISSUE TITLE
[9.5.1] Incorrect groups drop-down

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#7942]
**Describe the bug**

In the Groups tab of the user administration, only the groups from within the Root entity are shown. Other groups not. On the other hand, on the same page under Actions > Associate to a group, the whole correct list of groups is shown.

**Page(s) URL**

/front/user.form.php?id=123

**To reproduce**
***Prerequisites***
Create an Entity structure like this
Root entity
- entity 0
- entity 1

Create the following groups:
- g_re in Root entity
- g_e0 in entity 0
- g_e1 in entity 1

Create a user:
- assign to him the profile Self-Service in entity 1
- assign to him the group g_e1
- assing to him the profile Supervisor in Root entity, with recursive option enabled 

***Steps to reproduce the behavior:***
1. Log into GLPI as administrator
2. Go to 'Administration>Users>Search for the user>Enter the users record'
3. Click on tab 'Groups'
4. Open the Dropdown below 'Associate to a group', you'll see only the group 'g_re' from within Root entity
5. Click on 'Actions' and select 'Associate to a group'. In the modal window opening, open the dropdown, you will see all groups we created in the prerequisistes.

**Expected behavior**
In step 4, all groups should be shown like in step 5.

**Screenshots**

Screenshot for step 4
![Screenshot - 09 09 2020 , 16_42_48](https://user-images.githubusercontent.com/2961791/92619769-3d0c1280-f2c2-11ea-93d0-155db4b62117.png)

Screenshot for step 5
![Screenshot - 09 09 2020 , 17_24_54](https://user-images.githubusercontent.com/2961791/92619801-42695d00-f2c2-11ea-8c62-189f8d2af262.png)

**Comment by trasher** [comment]
@rickyweb could you please test #7942? Thanks.

**Comment by rickyweb** [comment]
I confirm this is fixing the issue. However there's still a difference between both dropdowns: the one in Actions always contains all groups, while the one directly accessible on the page only contains the groups not yet assigned to this user. I don't have any preference, but I think the dropdown should behave the same way in both contexts.

**Comment by cedric-anne** [comment]
Actions on items forms are built on top of massive actions proposed in items lists. As these massive actions were built to propose actions on multiple elements, fields are not filtered. It may be a usefull enhancement but would require a lot of work, and it would not be done for now.
