### ISSUE TITLE
[9.5.1] Simplified interface: Ticket creation cannot add more than one watcher

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#7945]
**Describe the bug**

When creating a ticket in the simplified interface, one can only add a single watcher. If one clicks on the (+) in order to add a further watcher, only the symbol of a person is added, but the form is missing.

**Page(s) URL**

front/helpdesk.public.php?create_ticket=1

**To reproduce**

1. Log in as a user that uses the simplified interface
2. Go to 'Create a ticket'
3. In the section "Watchers", click on (+) below the e-mail field
4. Observe that only the "Person" symbol appears, but not the three other fields and the information symbol

**Expected behavior**

Clicking on the (+) should add another instance of the watchers form like it used to in previous versions (for example 9.1.3)

**Screenshots**

Screenshot showing bug in 9.5.1
![Screenshot - 10 09 2020 , 10_47_21](https://user-images.githubusercontent.com/2961791/92705084-b738a780-f353-11ea-9252-3c064460901e.png)

Screenshot showing correct behavior in 9.1.3
![Screenshot - 10 09 2020 , 10_51_53](https://user-images.githubusercontent.com/2961791/92705117-bc95f200-f353-11ea-9d5c-63a8ab2a9f3f.png)

**Comment by cedric-anne** [comment]
Hi,

It duplicates #7766 and has been fixed by #7879. 

Regards
