### ISSUE TITLE
[9.5.1] SLA expired notification was sent regardless of pending status

### ISSUE THREAD

**Issue by aagz** [glpi-project/glpi#7946]
Hi. SLA expired notification was sent regardless of pending status.

Notification settings:
![image](https://user-images.githubusercontent.com/46520039/92730330-4a85d300-f37c-11ea-9b9a-ec3e216c3917.png)
Notification recipients:
![image](https://user-images.githubusercontent.com/46520039/92730371-540f3b00-f37c-11ea-872d-245fa7cf610e.png)

Ticket params:
![image](https://user-images.githubusercontent.com/46520039/92730681-cd0e9280-f37c-11ea-8da5-5c2421e0c6be.png)
Ticket logs:
![image](https://user-images.githubusercontent.com/46520039/92731057-45755380-f37d-11ea-8474-a8d3a5c8775d.png)

Mail.log
![image](https://user-images.githubusercontent.com/46520039/92734643-6344b780-f381-11ea-959e-4fd172664570.png)

**Comment by aagz** [comment]
GLPI 9.5.2 and 9.5.3 the same problem.

**Comment by aagz** [comment]
At first I thought the problem was in some plugin, but by disabling all plugins, the problem is still there.

**Comment by sistemasgvc** [comment]
Hello, in GLPI 9.5.4 version SLAs expire while in "Pending" state. Any solution for this?
