### ISSUE TITLE
[9.5.1] When editing a task, file upload doesn't work

### ISSUE THREAD

**Issue by rickyweb** [glpi-project/glpi#7948]
**Describe the bug**

Uploading a file when editing a task doesn't work, while it does work when creating a new task.

**Page(s) URL**

/front/ticket.form.php

**To reproduce**

1. Go to a specific ticket
2. Click on 'Processing ticket > Task'
3. Save the task
4. Edit the same task
5. Attach a file to the task
6. Save the task
7. Observe that the file was not attached. There was no error message on the frontend.
8. Click on 'Processing ticket > Task'
9. Attach a file to the task
10. Save the task
11. Observe that the file was attached.

**Expected behavior**

In step 7 the file should have been attached similarly like in step 11.

**Screenshots**

Step 5
![Screenshot - 11 09 2020 , 11_12_06](https://user-images.githubusercontent.com/2961791/92901224-99854400-f420-11ea-9214-f5cd5d46cd6f.png)
Step 7
![Screenshot - 11 09 2020 , 11_12_28](https://user-images.githubusercontent.com/2961791/92901242-9c803480-f420-11ea-8dc4-cb34b77197db.png)

Step 9
![Screenshot - 11 09 2020 , 11_08_48](https://user-images.githubusercontent.com/2961791/92901239-9be79e00-f420-11ea-9563-f7f3b3abb58b.png)
Step 11
![Screenshot - 11 09 2020 , 11_09_11](https://user-images.githubusercontent.com/2961791/92901232-9b4f0780-f420-11ea-9232-11d66685b2cc.png)

**Comment by stdglpi** [comment]
Hello @rickyweb 

I have tested also on GLPI 9.5.0, I notice the same result.

I don't know if this is normal behavior or if we want to update a ticket with an attachment we should add a new task to inform it.

**Comment by rickyweb** [comment]
The use case would look like this: I'm adding a task, set its status "To do", come back later, upload the file I created in the mean time and set the status to "Done".

If it was not meant to work, the attach area should not be there in the first place.

**Comment by rickyweb** [comment]
> I don't know if this is normal behavior or if we want to update a ticket with an attachment we should add a new task to inform it.

@stdglpi ,

The use case would look like this: I'm adding a task, set its status "To do", come back later, upload the file I created in the mean time and set the status to "Done".

If it was not meant to work, the attach area should not be there in the first place.

**Comment by cedric-anne** [comment]
Hi,

#7960 should fix this issue.

Regards
