### ISSUE TITLE
[9.5.1] "Replay the dictionary rules" action does not work.

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#7950]
Hello

**Describe the bug**

"Replay the dictionary rules" action does not work.

**To reproduce**

1. Go to 'Home > Administration > Dictionaries > Software'
2. Add new rule and set criteria and actions (assign to category).
3. Use 'Replay the dictionary rules' the button located on the 'Home > Administration > Dictionaries > Software' tab
4. Check the category
5. No effect.

**Expected behavior**
The action assigned to the rule should be applied.
It works, but from the 'Home > Assets > Software' > select the software > Actions button > "Replay the dictionary rules".

**Screenshots**

**<<<1>>>**
![](https://zapodaj.net/images/1dc70de294fba.png)

**<<<2>>>**
![](https://zapodaj.net/images/cffdd0c62b3fa.png)

**<<<3>>>**
![](https://zapodaj.net/images/516fd59e4496a.png)

**<<<4>>>**
![](https://zapodaj.net/images/ea30d8844da9b.png)

**<<<5>>>**
![](https://zapodaj.net/images/479658cadcf7b.png)

**<<<6>>>**
![](https://zapodaj.net/images/abbb3c687349e.png)
 

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.1 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Operating system: Linux chronos 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
    calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
    mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard,
    sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
    upload_max_filesize="2M"
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at server.domain.com Port 443)
Mozilla/5.0 (Windows NT 10.0; WOW64; rv:68.0) Gecko/20100101 Firefox/68.0
Server Software: (Ubuntu)
    Server Version: 8.0.21-0ubuntu0.20.04.4

PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!
mysqli extension is installed
ctype extension is installed
fileinfo extension is installed
json extension is installed
mbstring extension is installed
iconv extension is installed
zlib extension is installed
curl extension is installed
gd extension is installed
simplexml extension is installed
intl extension is installed
ldap extension is installed
apcu extension is installed
Zend OPcache extension is installed
xmlrpc extension is installed
CAS extension is installed
exif extension is installed
zip extension is installed
bz2 extension is installed
sodium extension is installed
Database version seems correct (8.0.21) - Perfect!
Timezones seems loaded in database
The log file has been created successfully.
Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.

**Comment by cedric-anne** [comment]
Hi,

#7961 should fix your issue.

Regards
