### ISSUE TITLE
2038 bug - any decent work-around?

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#7953]
GLPI v9.5.1

Attempting to enter any date with a year later than 2038 fails.
For instance, we need to enter domain expiry dates of 2039-07-09

We've tried entering the date directly into the DB and the issue appears to be due to a known bug: https://bugs.mysql.com/bug.php?id=12654

Is there any work-around for now, or is it just down to waiting for MySQL/MariaDB devs to address?

Thanks

**Comment by WebGregGit** [comment]
2039... maybe by then the world will end ;)

For now, just set 2038 and insert the correct date in the comment field. Before that date, the software will be updated many times.

**Comment by trasher** [comment]
Date limits are not a GLPI issue, but a MariaDB/MySQL one.
