### ISSUE TITLE
Slow performance on Home Page and Tickets page in 9.5.1

### ISSUE THREAD

**Issue by atanasag** [glpi-project/glpi#7959]
Hi again,
This is still an issue even with 9.5.1 I'v updated yesterday.
 I have changed PHP to 7.4 with Wincache 2.0.0.8 everything else **but** Home view and Tickets View works fast.

_Originally posted by @atanasag in https://github.com/glpi-project/glpi/issues/5740#issuecomment-692737339_

**Comment by cedric-anne** [comment]
Hi,

Please add more information to your issue. We need to know, at least, list of active plugins, any log related to your issue context.

Your previous comment that your homepage requires more than 9000 DB queries. Can you give us a list of them ?

Regards

**Comment by atanasag** [comment]
Here are logs from glpi and list of queries when debug Ticket view

[9.5.1_logs.zip](https://github.com/glpi-project/glpi/files/5232170/9.5.1_logs.zip)

**Comment by atanasag** [comment]
Hi,
Here are logs i was found useful including query list you need:

[9.5.1_logs.zip](https://github.com/glpi-project/glpi/files/5232278/9.5.1_logs.zip)

**Comment by cedric-anne** [comment]
@atanasag ,

Can you test #7966 and give us a feedback ?

I did not try to reproduce your case, but I found that some requests made by the `Calendar::isHoliday()` method are done 80 times each. I guess you have multiple entites that uses the same calendar, and this patch should reduce DB requests count.

Regards

**Comment by atanasag** [comment]
Hi,
It is better but still slow.
[queries after change 7966.txt](https://github.com/glpi-project/glpi/files/5239162/queries.after.change.7966.txt)
Regards

**Comment by cedric-anne** [comment]
Hi,

Can you give us the list of queries for the exact same context, with and without the patch ?

If I compare your logs from yesterday with the logs given 2 days ago, I found a difference of more than 5500 requests (from 9342 to 3646), but I do not know if it is the same context.

Regards

**Comment by atanasag** [comment]
Hi,
Yes, the context is exactly the same. Yes as I said there are noticeable improvement (from 9342 to 3646) but still a bit slow.
Regards

**Comment by cedric-anne** [comment]
I added some more cache, but I am not sure it will give noticeable improvement. Can you check again and give us a feedback on how many requests were saved ?

**Comment by atanasag** [comment]
Hi,
Same context, queries is 100 less now:
[queries 1892020.txt](https://github.com/glpi-project/glpi/files/5245128/queries.1892020.txt)

Regards

**Comment by cedric-anne** [comment]
OK, so this second improvement is not really interesting, as it act on really precise elements that are, most of the time, not shared between different computations.

So we will continue the work only for the first one at the moment.

**Comment by cedric-anne** [comment]
@atanasag 

We closed this issue as a first improvement has been merged and will be available in upcoming GLPI 9.5.2. I opened a new issue (#7989) to add more improvements. I will keep you informed.

Regards
