### ISSUE TITLE
[9.5.1] Problem update 9.4.6 to 9.5.1 - SQL Error glpi_items_softwareversions

### ISSUE THREAD

**Issue by cp61** [glpi-project/glpi#7963]
**Describe the bug**

When migrating glpi from 9.4.6 to 9.5.1 a following error results from the migration of databases

SQL Error "2006": Mysql server has gone away in query "UPDATE" 'glpi_items_softwareversions' SET' itemtype '=' AuthLDAP 'WHERE' itemtype '=' AuthLdap "

In the mysql logs we have the following errors:

020-09-16 14:08:05 2860 [ERROR] Found index itemtype whose column info does not match that of MySQL.

2020-09-16 14:08:05 2860 [ERROR] Build InnoDB index translation table for Table. \ Glpi \ glpi_items_softwareversions failed

2020-09-16 14:08:05 2860 [ERROR] Index itemtype of glpi / glpi_items_softwareversions has 1 columns unique inside InnoDB, but MySQL is asking statistics for 2 columns. Have you mixed up .frm files from different installations? See http://dev.mysql.com/doc/refman/5.6/en/innodb-troubleshooting.html

2020-09-16 14:08:05 2860 [ERROR] Index items_id of glpi / glpi_items_softwareversions has 1 columns unique inside InnoDB, but MySQL is asking statistics for 2 columns. Have you mixed up .frm files from different installations? See http://dev.mysql.com/doc/refman/5.6/en/innodb-troubleshooting.html

2020-09-16 14:08:05 2860 [ERROR] Index item of glpi / glpi_items_softwareversions has 2 columns unique inside InnoDB, but MySQL is asking statistics for 3 columns. Have you mixed up .frm files from different installations? See http://dev.mysql.com/doc/refman/5.6/en/innodb-troubleshooting.html

200916 14:08:05 [ERROR] mysqld got exception 0xc0000005;
This could be because you hit a bug. It is also possible that this binary
or one of the libraries it was linked against is corrupt, improperly built,
or misconfigured. This error can also be caused by malfunctioning hardware.

Immediately after the mysql service stops

**Page(s) URL**
 /glpi/install/update.php

**To reproduce**

1. Migrate GLPI

**Screenshots**

![image](https://user-images.githubusercontent.com/8723270/93338988-5b768e80-f82b-11ea-8ec9-92bade8ed591.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.4.6 (/glpi => C:\xampp\htdocs\glpi) Installation mode: TARBALL
--

Operating system: Windows NT SRV-SIC 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586 PHP 7.4.10 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, readline, session, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, 	zip, zlib) Setup: max_execution_time="600" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.29 (Win32) mod_authnz_sspi/0.1.0 OpenSSL/1.0.2l PHP/7.4.10 (Apache/2.4.29 (Win32) mod_authnz_sspi/0.1.0 	OpenSSL/1.0.2l PHP/7.4.10 Server at srv-sic Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 Server Software: mariadb.org binary distribution 	Server Version: 10.1.28-MariaDB 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: localhost via TCP/IP 	 mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed xml extension is installed ldap extension is installed imap extension is installed Zend OPcache extension is installed APCu extension is installed xmlrpc extension is installed exif extension is installed CAS extension is not present Database version seems correct (10.1.28) - Perfect! C:\xampp\htdocs\glpi/files/_log : OK C:\xampp\htdocs\glpi/config : OK C:\xampp\htdocs\glpi/files : OK C:\xampp\htdocs\glpi/files/_dumps : OK C:\xampp\htdocs\glpi/files/_sessions : OK C:\xampp\htdocs\glpi/files/_cron : OK C:\xampp\htdocs\glpi/files/_graphs : OK C:\xampp\htdocs\glpi/files/_lock : OK C:\xampp\htdocs\glpi/files/_plugins : OK C:\xampp\htdocs\glpi/files/_tmp : OK C:\xampp\htdocs\glpi/files/_cache : OK C:\xampp\htdocs\glpi/files/_rss : OK C:\xampp\htdocs\glpi/files/_uploads : OK C:\xampp\htdocs\glpi/files/_pictures : OK Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure acces to error log file is forbidden; otherwise review .htaccess file and web server configuration.

htmLawed version 1.2.4 in (C:\xampp\htdocs\glpi\lib\htmlawed) phpmailer/phpmailer version 6.0.7 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.3 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.3.2 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src) iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib) zendframework/zend-cache in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-cache\src) zendframework/zend-i18n in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-i18n\src) zendframework/zend-serializer in (C:\xampp\htdocs\glpi\vendor\zendframework\zend-serializer\src) monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog) sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src) elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src) symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console) leafo/scssphp in (C:\xampp\htdocs\glpi\vendor\leafo\scssphp\src)

news                 Name: Alertes                        Version: 1.6.0      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.10.3     State: Enabled 	behaviors            Name: Comportements                  Version: 2.2.2      State: Enabled 	escalade             Name: Escalades                      Version: 2.4.4      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.10.0     State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.8.0      State: Not installed 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.6.1      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.6.1      State: Enabled

Host: 10.61.7.103Connection: OkUse the OCSNG software dictionary: No
[/code]

**Comment by cedric-anne** [comment]
Hi,

It looks like failure comes from your MySQL server. Indeed, it failed on a simple and valid request, and MySQL logs seems to indicate that your database files are corrupted.
As it is not a problem on GLPI side, we cannot do anything.

Regards
