### ISSUE TITLE
Ticket subject (Thai language) encoding problems.

### ISSUE THREAD

**Issue by mukata69** [glpi-project/glpi#7972]
The GLPI ticket subject became unreadable if I create a ticket by email with the Thai language in the subject.
But the ticket body is ok. (see Picture-1 & Picture-2)
The GPLI log is showing the subject unreadable too (Picture-3).

My System:
     - GLPI 9.4.4
     - OS Centos 7
     - Email System Microsoft 365
     - Email Client: Outlook on the web, Outlook on iOS, Outlook on Android (all faced the same problem)

Picture-1
![Picture-1](https://i.imgur.com/HjPx6Pt.png)

Picture-2
![Picture-2](https://i.imgur.com/vCqNwq2.png)

Picture-3
![Picture-3](https://i.imgur.com/rW42bWc.png)

ps. same issue with this topics https://forum.glpi-project.org/viewtopic.php?id=279323

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)); I wonder if that has been fixed yet.

**Comment by mukata69** [comment]
Tested on GLPI 9.5.1 same problems but switch positions.
This time the subject can read but the body can not.
OS Centos 7 same server

![chrome_2020-09-18_15-32-55](https://user-images.githubusercontent.com/13465816/93575817-4d0faa80-f9c4-11ea-939b-4d1a14b6ff26.png)

**Comment by trasher** [comment]
There were many fixes since 9.5.1 has been released,  please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))

**Comment by mukata69** [comment]
Tested on GLPI 9.5.1 same problems but switch positions.
This time the subject can read but the body can not.
OS Centos 7 same server

![chrome_2020-09-18_15-32-55](https://user-images.githubusercontent.com/13465816/93575817-4d0faa80-f9c4-11ea-939b-4d1a14b6ff26.png)

**Comment by cedric-anne** [comment]
Hi,

#7748 should fix this.

Regards

**Comment by mukata69** [comment]
> 
> 
> Hi,
> 
> #7748 should fix this.
> 
> Regards

After replacing the file "inc\mailcollector.clalss.php" (GLPI version 9.5.1) with file from 9.5/bugfixes the problems solved.
Thank you for your support.
