### ISSUE TITLE
[9.5.1] Massive action for rules and dictionaries doesn't work properly

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#7974]
Hello

**Describe the bug**

A blank page appears after executing the cloning action. Setting the number of clones is ineffective.

**To reproduce**

1. Go to 'Home > Administration > Dictionaries > Software' or 'Home> Administration > Rules > Rules for assigning a category to software'
2. Check some rule.
3. Select 'clone' from the action
4. Set how many copies do you want to create... example 2 > post
5. A blank page appears /glpi/front/massiveaction.php
6. Return to page from point 1. And you will see only 1 copy.

**Expected behavior**

After executing the action, automatic return to the rules page with the declared number of copies of the previously selected rule.

Clone action for devices works good.

**Comment by trasher** [comment]
Many issues has been fixed since 9.5.1 regarding the new cloning feature. 
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))

**Comment by WebGregGit** [comment]
I don't know if I'm doing it right. I stoped apache.

1. I downloaded the package from the site https://github.com/glpi-project/glpi/actions/runs/258485829
2.  sudo cp -r /tmp/glpi/ /var/www/html/
3. cd /var/www/html/glpi
4. sudo chmod -R 755 config/ files/ marketplace/
5. sudo chown -R www-data:www-data files/ config/ marketplace/
6. sudo service apache2 start
7. I opened the GLPI website and updated

Home> Setup > General > Historical tab: Change dbversion 9.5.0 to 9.5.2
It still shows at the bottom of the page: GLPI 9.5.1 Copyright (C)
I checked the cloning action - no changes.

**Comment by trasher** [comment]
Ok, soudns like this is another broken case then

**Comment by cedric-anne** [comment]
Hi,

I confirm there is a bug.

Here is the trace:
```
==> files/_log/php-errors.log <==
[2020-09-30 08:01:04] glpiphplog.CRITICAL:   *** Uncaught Exception RuntimeException: Cannot guess  in /var/www/glpi/inc/commondbchild.class.php at line 872
  Backtrace :
  inc/features/clonable.class.php:68                 CommonDBChild::getItemField()
  inc/commondbtm.class.php:1234                      Rule->post_clone()
  inc/massiveaction.class.php:1312                   CommonDBTM->clone()
  inc/massiveaction.class.php:1087                   MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:1066                   MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()
```

Regards
