### ISSUE TITLE
[9.4 / 9.5] Tooltip of ticket content / Drop Html::clean

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#7981]
Hello

Into List of tickets, we can see comment of the ticket : Html::showToolTip(nl2br(Html::Clean($content)),
https://github.com/glpi-project/glpi/blob/9.5/bugfixes/inc/search.class.php#L6072

The description of ticket allow html code so when you use <table> into description you see : 

![image](https://user-images.githubusercontent.com/13178158/93668977-caa0ec80-fa90-11ea-9573-5403adaa0390.png)

If you remove Html :: clean:

![image](https://user-images.githubusercontent.com/13178158/93668996-f6bc6d80-fa90-11ea-875b-100ee4c79204.png)

It's time to change that, no ?

**Comment by cedric-anne** [comment]
Done in master branch.
