### ISSUE TITLE
GLPI 9.5.1 - Image aren't display when sent by mail collector

### ISSUE THREAD

**Issue by tprudent0803** [glpi-project/glpi#7984]
Hi !

First of all, thanks a lot for this beautiful tool. We used it in our company and it is really great.

Since we have moved an GLPI 9.5.1 (we were in 9.4.6 before) we have a problem with image which are sent into a mail and collect with the mailcollector.

The image, sometimes, is shown as an icon and we can't see the image. When I try to look the link of the image I always have a ling like this one : denied:cid:image001.png@01D69009.DBB7A780

I saw a lot of solution in many other tickets, but it doesn't work for me. I tried the modification of the folder rights (I'm on windows). I try to find, in html.class.php ou in mailcollector.php the different part of the code that some user changed but in 9.5.1 I don't find these part of code.

Is there someone who have had the same issu and have a solution ?

It seems to work for some user. I don(t know which is different between one or another.

Thanks for all.

![image](https://user-images.githubusercontent.com/63103223/93753651-c5fb4600-fc00-11ea-95be-84deab5976b6.png)

**Comment by cedric-anne** [comment]
Hi,

Did you tried #7968 ?

Regards

**Comment by tprudent0803** [comment]
Hi, 

Thanks for the quick answer. 

I will try this one quickly. I will let you know ! 

Thx

**Comment by tprudent0803** [comment]
Just to be sure to make the right correction. I juste have to change the line in the ticket.class.php ? Other change in the tickets are for tests ?

Thanks

**Comment by cedric-anne** [comment]
> Just to be sure to make the right correction. I juste have to change the line in the ticket.class.php ? Other change in the tickets are for tests ?

Indeed, you only have to change `inc/ticket.class.php`.

Regards

**Comment by tprudent0803** [comment]
One user sent me a ticket after the correction and I still have the issue...

It is really strange... It is not for all the user perhaps there is something on the mail client...

**Comment by cedric-anne** [comment]
If you can attach the email into eml format here, I could be able to debug this.

**Comment by tprudent0803** [comment]
Ok I will do this. Thx. I have try to put the image in attachement file and it works. The problem is when the image is in the body of the email.

**Comment by tprudent0803** [comment]
Voici le mail avec lequel j'ai reproduit le problème.

[corps de mail.zip](https://github.com/glpi-project/glpi/files/5255666/corps.de.mail.zip)

**Comment by lucastva** [comment]
Hey guys! I have same problem! But i did some tests:

Send e-mail with images on the body of message by Outlook > **GLPI NOT RECEIVE** (but the mailbox receive normally the images)
Send e-mail with images on the body of message by Thunderbird> GLPI RECEIVE
Send e-mail with images on the body of message by Webmail>GLPI RECEIVE

But...

Send e-mail with images on attach by Outlook > GLPI RECEIVE
Send e-mail with images on attach by Thunderbird> GLPI RECEIVE
Send e-mail with images on attach by Webmail> GLPI RECEIVE

![images-error](https://user-images.githubusercontent.com/71664545/93804468-b853b980-fc1c-11ea-8eae-32eef30a499e.png)

**Comment by cedric-anne** [comment]
> Here is the email in eml format.
> 
> [corps de mail.zip](https://github.com/glpi-project/glpi/files/5255666/corps.de.mail.zip)

I do not reproduce with current state of 9.5/bugfixes branch. I guess it has already been fixed, but as many fixes were done on this part, it is hard to tell you which patch you have to apply.

Regards

**Comment by tprudent0803** [comment]
Ok... That's not a good news but I understand that ti will probably corrected in the futur version.

I found in ticket 7964 that you gave a zip file of the fixed bugs for the 9.5.

I will try to make a copy of my glpi installation and try these fixes to see if it correct my problem.

**Comment by trasher** [comment]
@tprudent0803 @lucastva please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)) to see if you can reproduce.

**Comment by tprudent0803** [comment]
I will try this asap. Thx

**Comment by tprudent0803** [comment]
I have try with the 9.5.1+fixes and you're right, the problem has gone !

I will install this temporary version in the glpi which is in production. 

Thanks !

You can close the ticket.

**Comment by lucastva** [comment]
> I have try with the 9.5.1+fixes and you're right, the problem has gone !
> 
> I will install this temporary version in the glpi which is in production.
> 
> Thanks !
> 
> You can close the ticket.

I tryied to use this version, but the followups dont load after update, anyone have same problem?

**Comment by lucastva** [comment]
> @tprudent0803 @lucastva please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)) to see if you can reproduce.

I tryied to use this version, but the followups and tasks dont load after update. I rollback version.

**Comment by tprudent0803** [comment]
What do you mean by "followups and tasks dont load" ? Thanks. I don't saw any problems in my tests.

**Comment by lucastva** [comment]
![image](https://user-images.githubusercontent.com/71664545/93936968-54ed8880-fcfd-11ea-9fc8-c807e2cee441.png)

Look this print, isnt load the followups, just stay blank

**Comment by tprudent0803** [comment]
I have put the fixes in production this morning and all seems to be ok for now.

**Comment by cedric-anne** [comment]
> ![image](https://user-images.githubusercontent.com/71664545/93936968-54ed8880-fcfd-11ea-9fc8-c807e2cee441.png)
> 
> Look this print, isnt load the followups, just stay blank

I guess you have logs related to this. Can you give us these logs ?

**Comment by lucastva** [comment]
> I have put the fixes in production this morning and all seems to be ok for now.

Hi! I did the update to 9.5-bugfixes.ecf3c78

Now the problem is mail collector conection. 
I re-entry the mail and password correct but still not connecting

![image](https://user-images.githubusercontent.com/71664545/94147127-457c5580-fe4b-11ea-9e58-6bddc6f097e4.png)
