### ISSUE TITLE
[9.5.1] Import Users from LDAP

### ISSUE THREAD

**Issue by r0sek0ng** [glpi-project/glpi#7985]
I have the problem with import users from LDAP.

My ldap configuration:
BaseDN: `OU=Users,DC=w*****,DC=k*****,DC=pl`
also `DC=w*****,DC=k*****,DC=pl`
also  `OU=F****,DC=w*****,DC=k*****,DC=pl`

RootDN: `w*****\user `also `CN=GLPI,CN=Users,DC=w*****,DC=k*****,DC=pl`

Connection filter: `(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))`
also` (&(objectClass=user)(objectCategory=person))`
also  `(&(objectClass=top)(objectClass=person)(objectClass=organizationalPerson)(objectCategory=User))`
Login field:  `distinguishedname` also `samaccountname`

In every case during searching Users in:
**Administration > Users > LDAP directories > Import new users > Expert mode**
I receive a message: No user to be imported

What is more interesting when I searching the Grups:
**Administration > Groups > LDAP directories > Import of new groups**
Filter to search in groups
`(&(objectClass=user)(objectCategory=person))`
Search filter for users
`(&(objectClass=user)(objectCategory=person))`
or empty
the result is Users and Grups objects.

![601](https://user-images.githubusercontent.com/66087170/93767252-04e8c600-fc18-11ea-8eba-37aecf5c4dab.png)

I used the query
(& (objectClass = user) (objectCategory = person) (! (userAccountControl: 1.2.840.113556.1.4.803: = 2)))
in ldap tool and the program correctly displays the users list. 

![501](https://user-images.githubusercontent.com/66087170/93767277-10d48800-fc18-11ea-9f5d-d5f57ae5adcb.png)

---------------------------------------------------------------
GLPI:
GLPI 9.5.1
SQL Server version: 8.0.20
PHP Version : 7.4.3
Description:    Ubuntu 20.04 LTS

**Comment by flopez12** [comment]
Hi.
have you been able to fix it, I have the same problem.
Cheers

**Comment by r0sek0ng** [comment]
Yes. I deleted all configuration according to LDAP server. In GLPI I
created one more time LDAP object with default configuration. It works.




niedz., 18 paź 2020, 01:04 użytkownik flopez12 <notifications@github.com>
napisał:

**Comment by flopez12** [comment]
Hi.
I have reconfigured the ldap connection, but I still see the users.
when you mean remove ldap configuration on server, i am not clear what you mean.
thanks
