### ISSUE TITLE
Improve SLA/OLA TTR/TTO computations

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#7989]
A static cache was added by #7966 to cimprove computation of SLA/OLA TTR/TTO, but performances can still be improved.

TODO
- [x] Replace static cache by usage of `$GLPI_CACHE` object.
- [x] Try to cache `Calendar::getActiveTimeBetween()` results.
- [x] Invalidate cache on `CalendarSegment` and `Holiday` changes (addition, deletion, update).

**Comment by cedric-anne** [comment]
`Calendar::getActiveTimeBetween()` is using timestamps with precision to the second, so cache will be usefull for tickets that are created on the same weekday + hour/minute/second (e.g. `Monday 14 September at 10:05:03` and `Monday 21 September at 10:05:03`) It may happens, for example for tickets created by mail collectors, but probability is low.
Caching results with precision to the second will also produce a huge amount of cache data, and I am pretty sure, at least when cache is based on filesystem, that it may take more time to handle cache operations than the time required to do the SQL request.
So, IMHO, caching `Calendar::getActiveTimeBetween()` results is a bad idea.

**Comment by cedric-anne** [comment]
@atanasag ,

Can you try with #7990 ? It replaces the static cache (that has a lifetime of the PHP request), by an usage of the GLPI cache, that has a "perpetual" lifetime.

Can you give us, for the same context, "amount of SQL requests + time spent", for first and second page display, for following code states ?
1 - without any patch;
2 - with #7966 applied;
3 - with #7990 applied.

It will help us a lot to validate our improvements on a relevant use case.

Thanks for your help.

**Comment by atanasag** [comment]
@cedric-anne 

HI,
I've tried it. There is an improvement - 2710 Queries - 936 less than before (same context):
Here is result in same context as before:
[queries 2392020.txt](https://github.com/glpi-project/glpi/files/5267448/queries.2392020.txt)

**Comment by atanasag** [comment]
1 - without any patch -  9332 Queries took 10.62s
2 - with #7966 applied; - 3646 Queries took 4.5949999999999s
3 - with #7990 applied.  - 2710 Queries took 3.0269999999998s

**Comment by atanasag** [comment]
Second try with restarting IIS after every pach:
1 - without any patch - First page: 9591 Queries took 10.551s; Second page: 20246 Queries took 23.197000000004s
2 - with #7966 applied; - First page: 4026 Queries took 4.5349999999999s; Second page: 3584 Queries took 4.0939999999997s
3 - with #7990 applied. - First page: not loading more than 1 min; Second page: not loading

**Comment by atanasag** [comment]
I think #7966  works better than #7990

**Comment by cedric-anne** [comment]
1) Can you paste here a screenshot of the `Setup > General > Performance` page ?

2) Can you check your GLPI logs to see if there is any warning like `Cannot write "xxx" cache footprint file. Cache performance can be lowered.` or `Cache footprint file "xxx" contents was invalid, it has been cleaned.` ?

3) I tried to reproduce on my developpement machine (which runs on a 10 years old HDD), and when I display 200 tickets with SLA/OLA fields, it requires about 4000 requests, but they take only 0.05s. Maybe there is something to tweak, either on the link between GLPI and your DB, either on your DB server itself.

**Comment by atanasag** [comment]
1. - ![image](https://user-images.githubusercontent.com/21614115/94015409-7ca02780-fdb5-11ea-932a-87c5c3acadc8.png)
2. - [_log23092020.zip](https://github.com/glpi-project/glpi/files/5268233/_log23092020.zip)
3. - ![image](https://user-images.githubusercontent.com/21614115/94015826-0a7c1280-fdb6-11ea-8200-56ea4f7d186e.png)
      ![image](https://user-images.githubusercontent.com/21614115/94016015-4020fb80-fdb6-11ea-9b79-47a6d09ccc9a.png)
      ![image](https://user-images.githubusercontent.com/21614115/94016071-57f87f80-fdb6-11ea-9f1e-bd97392b82d7.png)     
      [Unused indexes.txt](https://github.com/glpi-project/glpi/files/5268288/Unused.indexes.txt)
      ![image](https://user-images.githubusercontent.com/21614115/94016134-6e9ed680-fdb6-11ea-9681-85e4185c3dbe.png)

**Comment by atanasag** [comment]
[Statements with hight cost.txt](https://github.com/glpi-project/glpi/files/5268320/Statements.with.hight.cost.txt)

**Comment by cedric-anne** [comment]
I see two errors in your logs.

This first error show that there is something wrong with access to your cache footprint file (used to check cache validity accross processes). Please check that rights are correct. I may propose a PR to enhance this case.
```
[2020-09-23 14:06:31] glpiphplog.NOTICE:   *** PHP Notice (8): file_get_contents(): read of 8192 bytes failed with errno=13 Permission denied in C:\inetpub\wwwroot\glpi\inc\cache\simplecache.class.php at line 285
  Backtrace :
  inc\cache\simplecache.class.php:285                file_get_contents()
  inc\cache\simplecache.class.php:72                 Glpi\Cache\SimpleCache->checkFootprintFileIntegrity()
  inc\config.class.php:3315                          Glpi\Cache\SimpleCache->__construct()
  inc\config.php:240                                 Config::getCache()
  inc\includes.php:48                                include_once()
  ajax\dashboard.php:33                              include()
```

Second error is directly linked to wincache usage. I do not wincache, and I found weird that with a maxiumum space of 8MB you get this error when the function `wincache_ucache_get` is called.
```
[2020-09-23 14:07:51] glpiphplog.CRITICAL:   *** PHP Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 40960 bytes) in C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-cache\src\Storage\Adapter\WinCache.php at line 137  
```

**Comment by atanasag** [comment]
First error show that there is something wrong with access to your cache footprint file - where is this file? I'm using Windows environment I have modify permissions on files dir: 
![image](https://user-images.githubusercontent.com/21614115/94108568-38119c00-fe48-11ea-8735-88d533e6f52b.png)
fot wincache - this error is very strange - Allowed memory size of 536870912 bytes is 512MB

**Comment by cedric-anne** [comment]
The footprint file is located in `files/_cache` and has a name like `glpi_cache_db_9.5.130360edb3237dd0d291a4d52bc7ffe8d.json` (name is dynamic).

**Comment by atanasag** [comment]
There is no problem with file/_cache folder's permissions.

**Comment by trasher** [comment]
Well, there is a permission issue, that what's written in your logs. Default cache path is `files/_cache`; it can be overriden by config (see documentation). I do not think there is currently a way to known what the current path is; but you can log it doing something like:

```diff
diff --git a/inc/cache/simplecache.class.php b/inc/cache/simplecache.class.php
index 07870210f9..cbfffa727d 100644
--- a/inc/cache/simplecache.class.php
+++ b/inc/cache/simplecache.class.php
@@ -282,6 +282,7 @@ class SimpleCache extends SimpleCacheDecorator implements CacheInterface {
          return;
       }
 
+      \Toolbox::logWarning('Footprint file: ' . $this->footprint_file);
       $file_contents = file_get_contents($this->footprint_file);
       if (empty($file_contents)) {
          // Create empty array in file if empty.
```

Output will be the file that has permission issues; and there is nothing we can do on our side to fix that.

As for the memory issues, this is maybe not related; but anyways it's better to fix the footprint file permission issue first.

**Comment by atanasag** [comment]
![image](https://user-images.githubusercontent.com/21614115/94147581-221ece00-fe7e-11ea-8c76-3b1d58016ee2.png)

**Comment by cedric-anne** [comment]
Hi @atanasag ,

Can you apply #8000 patch and see if you still have error related to file permissions on your cache footprint file ?

Regards

**Comment by atanasag** [comment]
HI @cedric-anne ,

Yes, I've applied it. How to  check if it works as expected?

**Comment by cedric-anne** [comment]
Check your logs to see if you have some warnings about cache.

**Comment by atanasag** [comment]
Checked everything is OK. I spotted something interesting. When I apply #7796  then i receive this error:

[2020-09-25 13:57:43] glpiphplog.CRITICAL:   *** PHP Error (1): Allowed memory size of 536870912 bytes exhausted (tried to allocate 81920 bytes) in C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-cache\src\Storage\Adapter\WinCache.php at line 137

When I go back with #7966  - the error disappears .

**Comment by cedric-anne** [comment]
Unless I am wrong, there is no official stable build of Wincache for PHP 7.4, and the latest version (2.0.0.8) is 4 years old. So maybe there is a bug on Wincache.

**Comment by atanasag** [comment]
Hi @cedric-anne,
I think there is some kind of memory leak with 7990 pach when WinCache is used - this is my point.

**Comment by trasher** [comment]
« when WinCache is used » we can' do anything on that point. I know there were major issues on APCu on windows, I do not know if this has been fixed since; maybe should you take a look at that.
Since we do  not use windows, we cannot test anything, but that looks like an issue on wicache itself, or in the lib used (laminas-cache); I'm almost sure nothing can be done on GLPI side.

**Comment by cedric-anne** [comment]
There is a APCu pecl package for windows, and it seems to be compatibile with PHP 7.4 : https://pecl.php.net/package/APCu/5.1.18/windows

**Comment by cedric-anne** [comment]
Hi @atanasag ,

I worked on an alternative solution that may greatly improve performances in your case. Could you test it ?

Regards

**Comment by atanasag** [comment]
OK, I will later today and will post results

**Comment by cedric-anne** [comment]
See #8413 for alternative solution.

**Comment by atanasag** [comment]
I'm using ver 9.5.1
Changed only files in #8413 
glpi/inc/calendar_holiday.class.php
glpi/inc/calendar.class.php
glpi/inc/holiday.class.php
glpi/tests/functionnal/Calendar.php
glpi/tests/functionnal/Calendar_Holiday.php

Results:
First page : 3021 Queries for 3.3 - 6.2 secs
Second page 2984 queries for 3.71 - 3.99 secs

Tried Apcu php_apcu-5.1.18-7.4-nts-vc15-x64 for PHP 7.4 but everything stops responding on the login page

**Comment by cedric-anne** [comment]
OK, so it seems better compared to previous tests as you have 25% less queries on first run, and 15% less on second run (see below).

Can you confirm that context was similar ?

For APCu, honnestly, I cannot help. I did not use PHP on a windows environment for almost 10 years.

> Second try with restarting IIS after every pach:
> 1 - without any patch - First page: 9591 Queries took 10.551s; Second page: 20246 Queries took 23.197000000004s
> 2 - with #7966 applied; - First page: 4026 Queries took 4.5349999999999s; Second page: 3584 Queries took 4.0939999999997s
> 3 - with #7990 applied. - First page: not loading more than 1 min; Second page: not loading

**Comment by trasher** [comment]
Historically, there have been many problems with APCu on windows, it has not been working for several years (at least). I had in mind this was fixed since but... I do not use windows myself neither :)
On windows, it seems that it's better to rely on wincache.

**Comment by tomolimo** [comment]
Hello @atanasag 

> I'm using ver 9.5.1
> Changed only files in #8413
> glpi/inc/calendar_holiday.class.php
> glpi/inc/calendar.class.php
> glpi/inc/holiday.class.php
> glpi/tests/functionnal/Calendar.php
> glpi/tests/functionnal/Calendar_Holiday.php
> 
> Results:
> First page : 3021 Queries for 3.3 - 6.2 secs
> Second page 2984 queries for 3.71 - 3.99 secs
> 
> Tried Apcu php_apcu-5.1.18-7.4-nts-vc15-x64 for PHP 7.4 but everything stops responding on the login page

We are running a similar configuration than yours, would you contact me on discord? My username is Tomolimo#1077
We may exchange ideas/information about configurations and performances.

Thank you
Regards,
Tomolimo
