### ISSUE TITLE
GLPI don't get computer last version with fusionagentInventory

### ISSUE THREAD

**Issue by rouroutera** [glpi-project/glpi#7991]
Hi, im just get hired and i have to make working GLPI  the guy before me did it but that doesn't work on all computer

i have a domaine where i have 70/80 computer, my server is runing, i can ping him with computers, i did firewall autorisation in ad , i install fusionagent with GPO , i have new inventory each day but for some computer i don't update since 5 month, fusioninventory is already installed and configured, i have try to force inventory with http://localhost:62354/now, but not working i really need some help i don't understand why that doesn't work

You will be a cheif captain cheif if you help me.

**Comment by trasher** [comment]
This is not related to GLPI, but to fusioninventory plugin. Also, you'd better ask for support on their forums rather than opening an issue (until this is really a bug, of course).
