### ISSUE TITLE
Bug with printers list

### ISSUE THREAD

**Issue by idle4you** [glpi-project/glpi#7995]
After updating to version 9.5.0 and 9.5.1, printers are no longer displayed.
How do I fix this error?

![image](https://user-images.githubusercontent.com/71770803/94017760-7a8b9800-fdb8-11ea-9876-b7e7d833de80.png)

`SQL Error "1370": execute command denied to user 'glpi'@'localhost' for routine 'glpi_links_c22f518493105896e6c9e574ca83a8f7.id' in query "SELECT DISTINCT `glpi_printers`.`id` AS id, 'sbynkov' AS currentuser, `glpi_printers`.`entities_id`, `glpi_printers`.`is_recursive`, `glpi_printers`.`name` AS `ITEM_Printer_1`, `glpi_printers`.`id` AS `ITEM_Printer_1_id`, `glpi_entities`.`completename` AS `ITEM_Printer_80`, `glpi_states`.`completename` AS `ITEM_Printer_31`, `glpi_locations`.`completename` AS `ITEM_Printer_3`, `glpi_printertypes`.`name` AS `ITEM_Printer_4`, `glpi_printermodels`.`name` AS `ITEM_Printer_40`, `glpi_printers`.`serial` AS `ITEM_Printer_5`, `glpi_users`.`name` AS `ITEM_Printer_70`, `glpi_users`.`realname` AS `ITEM_Printer_70_realname`, `glpi_users`.`id` AS `ITEM_Printer_70_id`, `glpi_users`.`firstname` AS `ITEM_Printer_70_firstname`, `glpi_printers`.`comment` AS `ITEM_Printer_16`, `glpi_printers`.`last_pages_counter` AS `ITEM_Printer_12`, COUNT(DISTINCT `glpi_cartridges_73e264b1b51f0a2b3ed0dd5561562d34`.`id`) AS `ITEM_Printer_18`, `glpi_printers`.`contact` AS `ITEM_Printer_7`, `glpi_printers`.`contact_num` AS `ITEM_Printer_8`, COUNT(DISTINCT `glpi_cartridges_16e1cf18af458587862de5883d33525e`.`id`) AS `ITEM_Printer_17`, GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`name`, '__NULL__'), '$#$',`glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`id`) ORDER BY `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`id` SEPARATOR '$$##$$') AS `ITEM_Printer_126`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id`, '__NULL__'), '$#$', `glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_id`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_c22f518493105896e6c9e574ca83a8f7`.`link`, '__NULL__'), '$#$', `glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_link`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_c22f518493105896e6c9e574ca83a8f7`.`name`, '__NULL__'), '$#$', `glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_name`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_c22f518493105896e6c9e574ca83a8f7`.`data`, '__NULL__'), '$#$', `glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_data`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_links_c22f518493105896e6c9e574ca83a8f7`.`open_window`, '__NULL__'), '$#$', `glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_Printer_145_open_window` FROM `glpi_printers`LEFT JOIN `glpi_entities` ON (`glpi_printers`.`entities_id` = `glpi_entities`.`id` )LEFT JOIN `glpi_states` ON (`glpi_printers`.`states_id` = `glpi_states`.`id` )LEFT JOIN `glpi_locations` ON (`glpi_printers`.`locations_id` = `glpi_locations`.`id` )LEFT JOIN `glpi_printertypes` ON (`glpi_printers`.`printertypes_id` = `glpi_printertypes`.`id` )LEFT JOIN `glpi_printermodels` ON (`glpi_printers`.`printermodels_id` = `glpi_printermodels`.`id` )LEFT JOIN `glpi_users` ON (`glpi_printers`.`users_id` = `glpi_users`.`id` ) LEFT JOIN `glpi_cartridges` AS `glpi_cartridges_73e264b1b51f0a2b3ed0dd5561562d34` ON (`glpi_printers`.`id` = `glpi_cartridges_73e264b1b51f0a2b3ed0dd5561562d34`.`printers_id` AND `glpi_cartridges_73e264b1b51f0a2b3ed0dd5561562d34`.`date_out` IS NOT NULL ) LEFT JOIN `glpi_cartridges` AS `glpi_cartridges_16e1cf18af458587862de5883d33525e` ON (`glpi_printers`.`id` = `glpi_cartridges_16e1cf18af458587862de5883d33525e`.`printers_id` AND `glpi_cartridges_16e1cf18af458587862de5883d33525e`.`date_use` IS NOT NULL AND `glpi_cartridges_16e1cf18af458587862de5883d33525e`.`date_out` IS NULL ) LEFT JOIN `glpi_ipaddresses` AS `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540` ON (`glpi_printers`.`id` = `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitems_id` AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`mainitemtype` = 'Printer' AND `glpi_ipaddresses_0cc35feab42e5909929ff742b4834540`.`is_deleted` = 0 ) LEFT JOIN `glpi_links_itemtypes` ON (`glpi_links_itemtypes`.`itemtype` = 'Printer' ) LEFT JOIN `glpi_links` AS `glpi_links_c22f518493105896e6c9e574ca83a8f7` ON (`glpi_links_itemtypes`.`links_id` = `glpi_links_c22f518493105896e6c9e574ca83a8f7`.`id` (`glpi_links_c22f518493105896e6c9e574ca83a8f7`.`entities_id` IN ('0')) ) WHERE `glpi_printers`.`is_deleted` = 0 AND `glpi_printers`.`is_template` = 0 AND ( `glpi_printers`.`entities_id` IN ('0') ) GROUP BY `glpi_printers`.`id` ORDER BY ITEM_Printer_1 ASC LIMIT 0, 15"`

**Comment by idle4you** [comment]
Click you name
<img width="398" alt="resolve problem pic 1" src="https://user-images.githubusercontent.com/71770803/94043665-e5979780-fdd5-11ea-8370-1d65ae359995.png">
Goto personal settings -> Personal View and delete your customized view
<img width="700" alt="resolve problem pic 2" src="https://user-images.githubusercontent.com/71770803/94044592-08767b80-fdd7-11ea-8202-2cd97312b908.png">
Done!

**Comment by cedric-anne** [comment]
Hi,

Unless I am wrong, it is the same issue as #7915 , fixed by #7930 .

Regards
