### ISSUE TITLE
Errors /inc/log.class.php

### ISSUE THREAD

**Issue by ukkt** [glpi-project/glpi#7999]
Describe the bug
On some computers, I have some error in the history. I don't know why.

Page(s) URL
glpi/front/computer.form.php?id=xyz&

To reproduce
Some Pc have error, other not. But still the same.

choose a computer
Click on tab historical

Logs
[2020-09-25 08:17:39] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: table in C:\xampp\htdocs\glpi\inc\log.class.php at line 727
  Backtrace :
  inc\log.class.php:362                              Log::getHistoryData()
  inc\log.class.php:98                               Log::showForItem()
  inc\commonglpi.class.php:637                       Log::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-09-25 08:17:39] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: field in C:\xampp\htdocs\glpi\inc\log.class.php at line 728
  Backtrace :
  inc\log.class.php:362                              Log::getHistoryData()
  inc\log.class.php:98                               Log::showForItem()
  inc\commonglpi.class.php:637                       Log::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()

Screenshot
![Bild](https://user-images.githubusercontent.com/49140655/94233390-1d066100-ff08-11ea-8566-b92ad3e6b0f6.JPG)

GLPI 9.5.1 (/glpi => C:\xampp\htdocs\glpi)
Installation mode: TARBALL

**Comment by cedric-anne** [comment]
Hi,

You already opened an issue for this, and it seem it was due to datainjection plugin. See #7821.

Regards
