### ISSUE TITLE
new installation issue

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#800]
hello 

I would like to test master version and at start I obtain this message

Run "composer install --no-dev" in the glpi tree

When do you think glpi new stable version will be available ?

**Comment by orthagh** [comment]
I can't say better than "soon"

for composer, it's possible to install on windows : https://getcomposer.org/doc/00-intro.md#installation-windows

**Comment by tomolimo** [comment]
Yes, I did that and it works perfect :)

**Comment by satyan01** [comment]
solved by composer installation.

Thank you

**Comment by vhamon** [comment]
On ubuntu  :
curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer

**Comment by obarriospino** [comment]
Greetings, I ´ve already installed composer in my server, and followed the steps of de link but the install does not work.

**Comment by flegastelois** [comment]
Hi,

Have you run "composer install" and/or "composer update" in the glpi tree ?

Do you have a new "vendor" directory in the glpi tree ?

Regards,

**Comment by Iceman1980** [comment]
Hello, 
I have the same error message by trying to install him since my NAS Synology.

Cordially.

**Comment by obarriospino** [comment]
Thanks, i solved the problem. i moved the files of composer to the site of glpi a execute de comand (composer install --no-dev) using cmd in the same folder of glpi site.
