### ISSUE TITLE
[9.4 / 9.5] Business rules criteria on category (completename and code) doesn't fully work

### ISSUE THREAD

**Issue by AlanBadier** [glpi-project/glpi#8001]
How to reproduce :

![image](https://user-images.githubusercontent.com/52499594/94259070-302c2780-ff2e-11ea-85de-923c738c1755.png)

![image](https://user-images.githubusercontent.com/52499594/94259090-36ba9f00-ff2e-11ea-9728-e9ab71f44a82.png)

contains condition (but I think others like "regex" doesn't work either) on category completename or code never trigger

Several things about that : 

- On update, when you modify the itil category, the criteria on "code" is never triggered, because the validation method of criteria search for "itilcategories_id_code" in input array (because of only_criteria parameter), but only 'itilcategories_id' is present. Need to modify ruleticketcollection.class.php on method prepareInputDataForProcess to add itilcategories_id_code in input array on itilcategories_id change

- Because of "dropdown" type on criteria, the field passed to the 'match' function is always (I think ?) the "name" field of category, but in itilcategories_id_cn and itilcategories_id_code criteria it would be nice to fill the $input array with the right field value, and removing the dropdown type on category completename criteria

i've quickly fixed this bug locally with this code onruleticketcollection.class.php:123

```      
if (isset($input['itilcategories_id'])) {
         $itilcategory = new ITILCategory();
         $itilcategory->getFromDB($input['itilcategories_id']);

         $input['itilcategories_id_cn']   = $itilcategory->fields['completename'];
         $input['itilcategories_id_code'] = $itilcategory->fields['code'];
}
```

But it's not the most effective way to do it I think

Alan

**Comment by eduardospinola** [comment]
I'm having the same problem here.

**Comment by WebGregGit** [comment]
Try to upgrade - we already have version 9.5.2 which has quite a few bug fixes.
