### ISSUE TITLE
(9.5.1)Unnecessary update message.

### ISSUE THREAD

**Issue by aleadco** [glpi-project/glpi#8003]
**Describe the bug**

I have version 9.5.1 installed and when I press to check for a new version it keeps showing me the version currently installed.

**Additional context**

![image](https://user-images.githubusercontent.com/35962168/94356227-cf017280-0059-11eb-910e-50eb3d7f5f8c.png)

**Comment by cedric-anne** [comment]
Hi,

It duplicates #7751 and has been fixed in #7758.

Regards
