### ISSUE TITLE
Can't add new archives.

### ISSUE THREAD

**Issue by RLCTN** [glpi-project/glpi#8007]
**Describe the bug**

When i click on Documents, and "ADD NEW ARCHIVE", nothing happens, GLPI just refresh the page and I can't add a new archive on the ticket. Same for solutions, Can't add a new archive in the solution, the field to add archive to the solution is missing.

![image](https://user-images.githubusercontent.com/72040201/94468215-77b6eb80-019a-11eb-8eb3-36188090ff94.png)

![image](https://user-images.githubusercontent.com/72040201/94468263-87cecb00-019a-11eb-9419-97110142db16.png)

Att.

**Comment by cedric-anne** [comment]
Hi,

Can you provide your installation details, logs, ... and try with no active plugin ?

Regards
