### ISSUE TITLE
Unable to register for marketplace in 9.5.1

### ISSUE THREAD

**Issue by pnopriadi** [glpi-project/glpi#8009]
**Describe the bug**

In 9.5.1 I am unable to add a registration key to use the marketplace
I get the error: White blank page URL below
This is potentially blocking access/view to manually install plugins.

**Page(s) URL**
/front/config.form.php?forcetab=GLPINetwork%241

**To reproduce**

- Go to Plugins
- Click on 'fill your registration key on setup'
- Paste registration key. Click Save
- See error

**Expected behavior**
I would expect the registration key to be applied and the market place available.

**Logs and Screenshots**
NA

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by pnopriadi** [comment]
Hi please find the screen capture below for reference: 
<img width="1128" alt="Registration Key Inserted" src="https://user-images.githubusercontent.com/72032422/94657446-0c088600-0334-11eb-885e-384ad807ddb5.png">

After click Save button, then the page turn while blank as below:
<img width="1126" alt="White Blank Screen" src="https://user-images.githubusercontent.com/72032422/94657457-1165d080-0334-11eb-8371-a3445e1f8555.png">

**Comment by cedric-anne** [comment]
Hi,

A blank screen is often the result of an error. Please provide GLPI logs related to this.

Regards

**Comment by pnopriadi** [comment]
> Hi,
> 
> A blank screen is often the result of an error. Please provide GLPI logs related to this.
> 
> Regards

Hi @cedric-anne , please find GLPI log from document attached. Below the summary log issue that can use as reference:

[php-errors.log](https://github.com/glpi-project/glpi/files/5304181/php-errors.log)
[2020-09-29 09:12:47] glpiphplog.CRITICAL:   *** Uncaught Exception SodiumException: Key must be CRYPTO_AEAD_XCHACHA20POLY1305_KEYBYTES long in /home/sosfromt/public_html/inventory/vendor/paragonie/sodium_compat/src/Compat.php at line 897
  Backtrace :
  ...paragonie/sodium_compat/lib/php72compat.php:350 ParagonIE_Sodium_Compat::crypto_aead_xchacha20poly1305_ietf_encrypt()
  inc/toolbox.class.php:272                          sodium_crypto_aead_xchacha20poly1305_ietf_encrypt()
  inc/config.class.php:263                           Toolbox::sodiumEncrypt()
  inc/commondbtm.class.php:1433                      Config->prepareInputForUpdate()
  front/config.form.php:50                           CommonDBTM->update()

**Comment by cedric-anne** [comment]
This bug has already been fixed (by multiple patches).

You should regenerate a security key (by running the `bin/console glpi:security:change_key`) and try again. You may have to reenter your receivers passwords, stmp password, and LDAPs passwords.
