### ISSUE TITLE
PHP Error : Solution

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#801]
When adding or refusal or approval of a solution in the ticket, I get this PHP error : 
PHP Fatal error:  Class 'Solution' not found in C:\wamp\www\glpi91\inc\ticket.class.php on line 6291

**Comment by flegastelois** [comment]
Linked to commit 94c8fada5438fa35126cb97f213fd0bf8476a3ef

Ping @tomolimo :)

Fatal error: Uncaught Error: Class 'Solution' not found in /var/www/glpi/git/inc/ticket.class.php:6292 Stack trace: #0 /var/www/glpi/git/inc/ticket.class.php(633): Ticket->showTimeline(19750714) #1 /var/www/glpi/git/inc/commonglpi.class.php(477): Ticket::displayTabContentForItem(Object(Ticket), '1', '') #2 /var/www/glpi/git/ajax/common.tabs.php(97): CommonGLPI::displayStandardTab(Object(Ticket), 'Ticket$1', '', Array) #3 {main} thrown in /var/www/glpi/git/inc/ticket.class.php on line 6292

**Comment by tomolimo** [comment]
Ok, I saw what is missing, I'm going to fix

**Comment by aleaddinozer** [comment]
There is another similar error when adding network port as Fatal error: Uncaught HTMLTableUnknownHeader: Instantiation:Connected in /var/www/glpi/inc/htmltablebase.class.php:160 Stack trace: #0 /var/www/glpi/inc/htmltablerow.class.php(205): HTMLTableBase->getHeaderByName('Instantiation', 'Connected') #1 /var/www/glpi/inc/networkportinstantiation.class.php(249): HTMLTableRow->getHeaderByName('Instantiation', 'Connected') #2 /var/www/glpi/inc/networkportethernet.class.php(174): NetworkPortInstantiation->getInstantiationHTMLTableWithPeer(Object(NetworkPort), Object(HTMLTableRow), NULL, Array) #3 /var/www/glpi/inc/networkport.class.php(777): NetworkPortEthernet->getInstantiationHTMLTable(Object(NetworkPort), Object(HTMLTableRow), NULL, Array) #4 /var/www/glpi/inc/networkport.class.php(1196): NetworkPort::showForItem(Object(Computer), '') #5 /var/www/glpi/inc/commonglpi.class.php(485): NetworkPort::displayTabContentForItem(Object(Computer), '1', '') #6 /var/www/glpi/inc/commonglpi.class.php(452): CommonGLPI::displayStandardTab(Object(Computer), 'NetworkPort$1', '', Array) #7 /var/www/ in /var/www/glpi/inc/htmltablebase.class.php on line 160

**Comment by cedric-anne** [comment]
> There is another similar error when adding network port as Fatal error: Uncaught HTMLTableUnknownHeader: Instantiation:Connected in /var/www/glpi/inc/htmltablebase.class.php:160 Stack trace: #0 /var/www/glpi/inc/htmltablerow.class.php(205): HTMLTableBase->getHeaderByName('Instantiation', 'Connected') #1 /var/www/glpi/inc/networkportinstantiation.class.php(249): HTMLTableRow->getHeaderByName('Instantiation', 'Connected') #2 /var/www/glpi/inc/networkportethernet.class.php(174): NetworkPortInstantiation->getInstantiationHTMLTableWithPeer(Object(NetworkPort), Object(HTMLTableRow), NULL, Array) #3 /var/www/glpi/inc/networkport.class.php(777): NetworkPortEthernet->getInstantiationHTMLTable(Object(NetworkPort), Object(HTMLTableRow), NULL, Array) #4 /var/www/glpi/inc/networkport.class.php(1196): NetworkPort::showForItem(Object(Computer), '') #5 /var/www/glpi/inc/commonglpi.class.php(485): NetworkPort::displayTabContentForItem(Object(Computer), '1', '') #6 /var/www/glpi/inc/commonglpi.class.php(452): CommonGLPI::displayStandardTab(Object(Computer), 'NetworkPort$1', '', Array) #7 /var/www/ in /var/www/glpi/inc/htmltablebase.class.php on line 160

Hi,

Current issue was closed almost 3 years ago, and was concerning the 9.1 version of GLPI.
If you want us to investigate on your issue, please open a new one and fill all requested informations.

Regards
