### ISSUE TITLE
 [GLPI 9.5.1] GLPI Rich text or version HTML

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#8013]
Hello,
since GLPI version 9.5.1, interfaces and mail exchanges are in rich text. Before, we had the possibility of making this choice in assistance configuration then "Use rich text for assistance" yes and no.

I had made sure to never activate it and I had modified the GLPI code in the exchanges of mail, the creation of ticket, the closing of ticket and the response via webmail ... All this was ok in order to have html with css in the exchanges but not in the database!

Today during my tests before the migration that I have to do in 9.5.1 (I am in 9.3.4), the database is entirely polluted by html code. How to turn off rich text?

Thank you

here is what is in base:

**Logs**
&lt;h1&gt;Donn&eacute;es du formulaire&lt;/h1&gt;&lt;h2&gt;Demande libre&lt;/h2&gt;&lt;div&gt;&lt;b&gt;1) Titre : &lt;/b&gt;test yves&lt;/div&gt;&lt;div&gt;&lt;b&gt;2) Urgence : &lt;/b&gt;Moyenne&lt;/div&gt;&lt;div&gt;&lt;b&gt;3) Lieu : &lt;/b&gt;&nbsp;&lt;/div&gt;&lt;div&gt;&lt;b&gt;4) Observateur : &lt;/b&gt;<br />&lt;/div&gt;&lt;div&gt;&lt;b&gt;5) Descriptif précis de votre problème, y compris les erreurs éventuelles : &lt;/b&gt;&lt;p&gt;1&lt;/p&gt;&lt;table style="border-collapse: collapse; width: 100%;" border="1"&gt;&lt;tbody&gt;&lt;tr&gt;&lt;td style="width: 33.3333%;"&gt; &lt;/td&gt;&lt;td style="width: 33.3333%;"&gt; &lt;/td&gt;&lt;td style="width: 33.3333%;"&gt; &lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td style="width: 33.3333%;"&gt; &lt;/td&gt;&lt;td style="width: 33.3333%;"&gt; &lt;/td&gt;&lt;td style="width: 33.3333%;"&gt; &lt;/td&gt;&lt;/tr&gt;&lt;/tbody&gt;&lt;/table&gt;&lt;p&gt;3&lt;/p&gt;&lt;p&gt; &lt;/p&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;6) Bureau : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;7) Téléphone : &lt;/b&gt;&lt;/div&gt;&lt;div&gt;&lt;b&gt;8) Site / Bâtiment : &lt;/b&gt;----&lt;/div&gt;&lt;div&gt;&lt;b&gt;9) Fichier joint : &lt;/b&gt;Document joint&lt;/div&gt;&lt;div&gt;&lt;b&gt;10) Host : &lt;/b&gt;localhost&lt;/div&gt;&lt;div&gt;&lt;b&gt;11) IP : &lt;/b&gt;127.0.0.1&lt;/div&gt;
```

**Comment by trasher** [comment]
Rich text has been enabled per default since GLPI 9.4, and this parameter has been dropped; this is not an issue.
