### ISSUE TITLE
Email to requesters cannot be sent

### ISSUE THREAD

**Issue by SakisGalanis** [glpi-project/glpi#8014]
I am trying to configure GLPI in order to send emails to the requester. If i understand correctly there are two options :
1.Email Followups configuration lets you reply through mail client ( outlook ) but it creates a new ticket ( it works in my case ) but it is not preffered because it creates new ticket on every reply.
2. Browser followups configuration where - if i understand correctly - it allows a techician to reply on tasks, tickets etc through the GLPI platform ( browser ). This feature does not work and keeps all notifications in the queue ( Administration -> Notification queue ) and when i try to send them manually i get an error message: Failed Operation (0 authorizations problems, 1 failures)
My question is: how can i setup GLPI ( email followup or browser followup ) in order to reply to tickets by keeping the same ticket ID and add every answer to the right field ( followup, tasks, tickets )?

Thanks

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support, only bugs should be reported here

**Comment by SakisGalanis** [comment]
Ok sorry
