### ISSUE TITLE
[9.5.1] - personal view and group view slow to load

### ISSUE THREAD

**Issue by loubaje1** [glpi-project/glpi#8015]
Hi, since i have moved from version 9.1.7 to 9.5.1, a bug occur only on two views on the page http://frannas97/glpi/front/central.php.
on both views, it take 15 seconds to display. all other pages are not impacted.

in debug mode, i have identified 2 query that take each 8s to execute
![image](https://user-images.githubusercontent.com/72065628/94580542-56c5c780-027a-11eb-9890-e20d7c55d5b8.png)

if i execute those two query directly on base with phpmyadmin, i get the same issue
![image](https://user-images.githubusercontent.com/72065628/94580822-a6a48e80-027a-11eb-9cf9-de119667636d.png)

![image](https://user-images.githubusercontent.com/72065628/94580936-c89e1100-027a-11eb-9d1c-328a9ed4e29e.png)

i have noticed that if on the two request i remove the LIMIT 1 in 
![image](https://user-images.githubusercontent.com/72065628/94581283-2d596b80-027b-11eb-8950-78d5c9e9014d.png)
, query execute instantly with the same result

![image](https://user-images.githubusercontent.com/72065628/94581380-4feb8480-027b-11eb-9c08-c869af7fee05.png)

i have tried to disable the two pluggins installed, in case it could help, but it makes no difference

Informations sur le système, l'installation et la configuration
--
Vérifier si une nouvelle version est disponible
[code]   GLPI 9.5.1 (/glpi => /var/www/glpi) Installation mode: TARBALL

Operating system: Linux frannas97 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64 PHP 7.2.24-0ubuntu0.18.04.6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, 	sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="64M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at frxxxx Port 80) 	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.31-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: GLPI@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is not present xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.31) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/glpi/config has been validated. Write access to /var/www/glpi/files has been validated. Write access to /var/www/glpi/files/_dumps has been validated. Write access to /var/www/glpi/files/_sessions has been validated. Write access to /var/www/glpi/files/_cron has been validated. Write access to /var/www/glpi/files/_graphs has been validated. Write access to /var/www/glpi/files/_lock has been validated. Write access to /var/www/glpi/files/_plugins has been validated. Write access to /var/www/glpi/files/_tmp has been validated. Write access to /var/www/glpi/files/_cache has been validated. Write access to /var/www/glpi/files/_rss has been validated. Write access to /var/www/glpi/files/_uploads has been validated. Write access to /var/www/glpi/files/_pictures has been validated. Write access to /var/www/glpi/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/glpi GLPI_CONFIG_DIR: /var/www/glpi/config GLPI_VAR_DIR: /var/www/glpi/files GLPI_MARKETPLACE_DIR: /var/www/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/glpi/files GLPI_CACHE_DIR: /var/www/glpi/files/_cache GLPI_CRON_DIR: /var/www/glpi/files/_cron GLPI_DUMP_DIR: /var/www/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/glpi/files/_locales GLPI_LOCK_DIR: /var/www/glpi/files/_lock GLPI_LOG_DIR: /var/www/glpi/files/_log GLPI_PICTURE_DIR: /var/www/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/glpi/files/_plugins GLPI_RSS_DIR: /var/www/glpi/files/_rss GLPI_SESSION_DIR: /var/www/glpi/files/_sessions GLPI_TMP_DIR: /var/www/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/glpi/locales GLPI_VERSION: 9.5.1 GLPI_SCHEMA_VERSION: 9.5.0 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (/var/www/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/var/www/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/glpi/vendor/guzzlehttp/guzzle/src) wapmorgan/unified-archive in (/var/www/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.3 in (/usr/share/php)

Server: 'fxxxxxxx01.axxxx.priv', Port: '389', BaseDN: 'DC=fxxx,DC=priv', Connection filter: '(objectClass=user)', RootDN: 		'CN=fxxxx-gxxx,OU=Service Accounts,OU=Axxx,OU=Axx,OU=Pxxx,DC=fxxxx,DC=priv', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@smtp.fxx.ixxx)

 

ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.0      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.7.0      State: Enabled

Host: 10.xx.x.xxxConnection: OkUse the OCSNG software dictionary: No
Host: frxxxxConnection: OkUse the OCSNG software dictionary: No
[/code]

thanks in advance for your help

**Comment by loubaje1** [comment]
error still persist on 9.5.2

**Comment by Jitbuff** [comment]
Same issue here (GLPI 9.5.3, IIS, MySQL 8.0, PHP 8.0):
![obraz](https://user-images.githubusercontent.com/79311623/108495373-01ca3280-72a9-11eb-84d2-7c39042a2fb9.png)

Sometimes it takes even longer. Worked OK on 9.2.3 with the same version of MySQL. I believe this is same query as reported here: https://github.com/glpi-project/glpi/issues/6765
Any ideas?

**Comment by cedric-anne** [comment]
> Same issue here (GLPI 9.5.3, IIS, MySQL 8.0, PHP 8.0):
> ![obraz](https://user-images.githubusercontent.com/79311623/108495373-01ca3280-72a9-11eb-84d2-7c39042a2fb9.png)
> 
> Sometimes it takes even longer. Worked OK on 9.2.3 with the same version of MySQL. I believe this is same query as reported here: #6765
> Any ideas?

Hi,

How many entities do you have ?

Regards

**Comment by Jitbuff** [comment]
Hi cedric-anne, 
There is about 30 entities configured.

**Comment by cedric-anne** [comment]
Without the database to do some tests, it is hard to know what can be the problem. Maybe some fields could be added to index to speed up this query specifically.

**Comment by loubaje1** [comment]
hi, on our side, we have 3 entities including the root entity

**Comment by Jitbuff** [comment]
Turned out that the InnoDB buffer in MySQL was set to 128 MB. Changing this to 8 GB resolved the issue.

**Comment by cedric-anne** [comment]
> Turned out that the InnoDB buffer in MySQL was set to 128 MB. Changing this to 8 GB resolved the issue.

It may prevent the problem to appear, but I guess something may be done on GLPI side to prevent this.

**Comment by loubaje1** [comment]
i changed the innoDB Buffer in mysql too, passed from 128MB to 2GB, i didn't see any improvement

**Comment by loubaje1** [comment]
hello, i tryed to upgrade to 9.5.5 version, but it does not solved the problem.
after looking more precisely, the only thing slowing down the display of the presonnal view, is the request of the refused tickets.
as the request search for all  tickets with a solution but with status different than closed the more tickets have been solved by the users, the longest is the request.

as previously mentionned perhaps adding index on this specific query could help

**Comment by Wieprzos** [comment]
>>Turned out that the InnoDB buffer in MySQL was set to 128 MB. Changing this to 8 GB resolved the issue.

> i changed the innoDB Buffer in mysql too, passed from 128MB to 2GB, i didn't see any improvement

i moved up to 8.5 GB, noticed some improvement but still it sometimes takes longer than it sholud to load the central view. happens quite randomly...
