### ISSUE TITLE
GLPI 9.5.1 - Move assets to different entities = Delete  the software associated 

### ISSUE THREAD

**Issue by rcfloresh** [glpi-project/glpi#8017]
**Describe the bug**

When you move a computer from an entity to another all the software is removed. 

**To reproduce**

Scenario 1. 
1. Go to 'Assets'
2. Mark the computer name in the check box.
3. Click on 'Actions'
4. Scroll down to 'Add to transfer list' 
5. Click on 'Add'
6. Transfer mode 'complete'
7. Scroll down to 'Entitty'
8. Scroll down in all the asset and choose 'Preserve'
9. Click in 'Execute'

**Expected behavior**
Move the computer an all the elements associated like the software to the new entity 

**Logs**
No logs founded 

**Video**

[video_2020-09-29_14-42-51.zip](https://github.com/glpi-project/glpi/files/5301794/video_2020-09-29_14-42-51.zip)

**Comment by trasher** [comment]
Duplicates #7864
