### ISSUE TITLE
PHP Fatal error on planning with PHP7

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#804]
Hello,

This error occured when running GLPi on PHP 7 : 
[php:fpm] [11-Jul-2016 12:51:25] WARNING: [pool www] child 39 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Access to undeclared static property: Planning::$event_type_color in /app/glpi/inc/planning.class.php on line 1672"

**Comment by tomolimo** [comment]
Seems to be linked to #778

**Comment by orthagh** [comment]
good catch
