### ISSUE TITLE
GLPI update weird up to 9.4 issue Toolbox::userErrorHandlerNormal()

### ISSUE THREAD

**Issue by ivanbuitron** [glpi-project/glpi#8053]
After updating glpi to version 9.4 with the same database that I had in the previous version 9.1 the problem is that the plugins did not appear in the list (even if they were there) then I entered the php log error and I got a 9M records error with something like this

[2020-08-22 21:41:43] glpiphplog.WARNING: Test logger  
[2020-08-22 21:48:42] glpiphplog.WARNING: Test logger  
[2020-08-22 21:55:01] glpiphplog.WARNING: Test logger  
[2020-08-23 18:34:35] glpiphplog.WARNING: Test logger  
[2020-08-23 20:44:49] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /volume1/Web/glpi/inc/toolbox.class.php line 658
  *** PHP User Warning(512): Table glpi_users does not exists
  Backtrace :
  :                                                  
  inc/dbutils.class.php:457                          trigger_error()
  inc/db.function.php:489                            DbUtils->isIndex()
  inc/migration.class.php:512                        isIndex()
  install/update_0853_0855.php:68                    Migration->addKey()
  inc/update.class.php:362                           update0853to0855()
  install/update.php:471                             Update->doUpdates()
  install/update.php:585                             doUpdateDb()

[2020-08-24 16:55:57] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /volume1/Web/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): readdir() expects parameter 1 to be resource, boolean given
  Backtrace :
  :                                                  
  inc/plugin.class.php:274                           readdir()
  front/plugin.php:40                                Plugin->checkStates()

[2020-08-24 16:58:29] glpiphplog.ERROR: Toolbox::userErrorHandlerNormal() in /volume1/Web/glpi/inc/toolbox.class.php line 658
  *** PHP Warning(2): readdir() expects parameter 1 to be resource, boolean given
  Backtrace :
  :                                                  
  inc/plugin.class.php:274                           readdir()
  front/plugin.php:40                                Plugin->checkStates()

![imagen](https://user-images.githubusercontent.com/68391478/94970017-5b33ef80-04c9-11eb-8f43-4602a3b1079e.png)

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Update GLPI to 9.4 from 9.1 with the same 9.1 database
2. Click on configuration menu-> plugins
3. Go to /Web/glpi/files/_log/php-errors.log

**Expected behavior**

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

First, 9.4 version of GLPI is not anymore supported.

Second, this kind of should not happens unless your web server has no rights to access the `plugins` (`/Web/glpi/plugins`) directory.

Regards

**Comment by trasher** [comment]
` *** PHP User Warning(512): Table glpi_users does not exists` this does not sound good neither :D It seems there are several configuration issues on your system; please use [forums](http://forum.glpi-project.org) to get support. And plan to upgrade to supported version (currently 9.5).
