### ISSUE TITLE
GLPI often returns a 500 internal server error

### ISSUE THREAD

**Issue by LuminousWing** [glpi-project/glpi#8060]
**Describe the bug**

While using the GLPI, it will often return a 500 internal server error, when it gives this error often a refresh will make it work again. Sometimes you need to wait a minute or more untill it will pop back up

**Page(s) URL**

All

**To reproduce**

Not possible, happens at random times

**Expected behavior**

During normal work, adding computers, devices, logging tickets, etc.. the page will refresh to an internal server error page.

**Logs**

Files are kinda large so I uploaded them, https://we.tl/t-DHFcK8TV3T

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Windows NT W2016GLPI 10.0 build 14393 (Windows Server 2016) AMD64 PHP 7.3.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, exif, 	fileinfo, filter, gd, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, pcre, readline, session, standard, 	tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Microsoft-IIS/10.0 	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.3.11-MariaDB 	Server SQL Mode:  	Parameters: root@localhost/sfzglpi 	Host info: localhost via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is not present xmlrpc extension is not present CAS extension is not present exif extension is installed zip extension is installed bz2 extension is not present sodium extension is not present Database version seems correct (10.3.11) - Perfect! Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html. The log file has been created successfully. Write access to C:\inetpub\wwwroot\glpi/config has been validated. Write access to C:\inetpub\wwwroot\glpi/files has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_dumps has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_sessions has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_cron has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_graphs has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_lock has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_plugins has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_tmp has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_cache has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_rss has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_uploads has been validated. Write access to C:\inetpub\wwwroot\glpi/files/_pictures has been validated. Write access to C:\inetpub\wwwroot\glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
--

GLPI_ROOT: C:\inetpub\wwwroot\glpi GLPI_CONFIG_DIR: C:\inetpub\wwwroot\glpi/config GLPI_VAR_DIR: C:\inetpub\wwwroot\glpi/files GLPI_MARKETPLACE_DIR: C:\inetpub\wwwroot\glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: C:\inetpub\wwwroot\glpi/files GLPI_CACHE_DIR: C:\inetpub\wwwroot\glpi/files/_cache GLPI_CRON_DIR: C:\inetpub\wwwroot\glpi/files/_cron GLPI_DUMP_DIR: C:\inetpub\wwwroot\glpi/files/_dumps GLPI_GRAPH_DIR: C:\inetpub\wwwroot\glpi/files/_graphs GLPI_LOCAL_I18N_DIR: C:\inetpub\wwwroot\glpi/files/_locales GLPI_LOCK_DIR: C:\inetpub\wwwroot\glpi/files/_lock GLPI_LOG_DIR: C:\inetpub\wwwroot\glpi/files/_log GLPI_PICTURE_DIR: C:\inetpub\wwwroot\glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: C:\inetpub\wwwroot\glpi/files/_plugins GLPI_RSS_DIR: C:\inetpub\wwwroot\glpi/files/_rss GLPI_SESSION_DIR: C:\inetpub\wwwroot\glpi/files/_sessions GLPI_TMP_DIR: C:\inetpub\wwwroot\glpi/files/_tmp GLPI_UPLOAD_DIR: C:\inetpub\wwwroot\glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: C:\inetpub\wwwroot\glpi/locales GLPI_VERSION: 9.5.1 GLPI_SCHEMA_VERSION: 9.5.0 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020

htmlawed/htmlawed version 1.2.5 in (C:\inetpub\wwwroot\glpi\vendor\htmlawed\htmlawed) phpmailer/phpmailer version 6.1.6 in (C:\inetpub\wwwroot\glpi\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.5 in (C:\inetpub\wwwroot\glpi\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.3.5 in (C:\inetpub\wwwroot\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\inetpub\wwwroot\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\inetpub\wwwroot\glpi\vendor\true\punycode\src) iamcal/lib_autolink in (C:\inetpub\wwwroot\glpi\vendor\iamcal\lib_autolink) sabre/dav in (C:\inetpub\wwwroot\glpi\vendor\sabre\dav\lib\DAV) sabre/http in (C:\inetpub\wwwroot\glpi\vendor\sabre\http\lib) sabre/uri in (C:\inetpub\wwwroot\glpi\vendor\sabre\uri\lib) sabre/vobject in (C:\inetpub\wwwroot\glpi\vendor\sabre\vobject\lib) laminas/laminas-cache in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-cache\src) laminas/laminas-i18n in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-i18n\src) laminas/laminas-serializer in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-serializer\src) monolog/monolog in (C:\inetpub\wwwroot\glpi\vendor\monolog\monolog\src\Monolog) sebastian/diff in (C:\inetpub\wwwroot\glpi\vendor\sebastian\diff\src) elvanto/litemoji in (C:\inetpub\wwwroot\glpi\vendor\elvanto\litemoji\src) symfony/console in (C:\inetpub\wwwroot\glpi\vendor\symfony\console) scssphp/scssphp in (C:\inetpub\wwwroot\glpi\vendor\scssphp\scssphp\src) laminas/laminas-mail in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mail\src\Protocol) laminas/laminas-mime in (C:\inetpub\wwwroot\glpi\vendor\laminas\laminas-mime\src) rlanvin/php-rrule in (C:\inetpub\wwwroot\glpi\vendor\rlanvin\php-rrule\src) blueimp/jquery-file-upload in (C:\inetpub\wwwroot\glpi\vendor\blueimp\jquery-file-upload\server\php) ramsey/uuid in (C:\inetpub\wwwroot\glpi\vendor\ramsey\uuid\src) psr/log in (C:\inetpub\wwwroot\glpi\vendor\psr\log\Psr\Log) psr/simple-cache in (C:\inetpub\wwwroot\glpi\vendor\psr\simple-cache\src) mexitek/phpcolors in (C:\inetpub\wwwroot\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors) guzzlehttp/guzzle in (C:\inetpub\wwwroot\glpi\vendor\guzzlehttp\guzzle\src) wapmorgan/unified-archive in (C:\inetpub\wwwroot\glpi\vendor\wapmorgan\unified-archive\src) paragonie/sodium_compat in (C:\inetpub\wwwroot\glpi\vendor\paragonie\sodium_compat\src)

Server: '10.23.2.127', Port: '389', BaseDN: 'DC=sfz,DC=local', Connection filter: 		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'CN=installer3,CN=Users,DC=sfz,DC=local', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@smtp.sfz.local)

Name: 'ticket.it@sfz.be' Active: Yes 	Server: '{office365.com/imap}' Login: 'ticket.it@sfz.be' Password: Yes Name: 'helpdeskkws@sfz.be' Active: Yes 	Server: '{office365.com/imap}' Login: 'helpdeskkws@sfz.be' Password: Yes

fields               Name: Additionnal fields             Version: 1.11.0     State: Enabled 	dashboard            Name: Dashboard                      Version: 0.9.9      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.7.0      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.8.0      State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

Your logs are too large and most of errors are due to the fact that your server cannot connect other servers (smpt and imap servers).

Are you running `queuenotification` and `mailgate` automatic actions with `GLPI` run mode ?

Regards

**Comment by LuminousWing** [comment]
The mode is CLI, I disabled mailgate for now. Queuednotification is on, as was Mailgate.
If the problem persists, shall I upload a new log?

**Comment by cedric-anne** [comment]
You should provide a log that corresponds to the time the error happens. It is almost impossible to find what cause your problem on 25MB logs.

**Comment by LuminousWing** [comment]
I will upload a new log should the error appear again.
