### ISSUE TITLE
new function isActive

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#807]
@tomolimo 

I'll revert this part https://github.com/glpi-project/glpi/pull/789/files#diff-7f569484c496f62a6ccf54647fed2b1bR2699 finally

In fact, you don't use this function in your PR #789 and we have a big conflict with fusioninventory plugin:

``` log
PHP Warning: Declaration of PluginFusioninventoryConfig::isActive($name) should be compatible with CommonDBTM::isActive() in /var/www/html/glpi/0.91-git/plugins/fusioninventory/inc/config.class.php at line 0
```

I'm not against this new function, but i think it need the thoughts of all involved actors

ping @ddurieux

**Comment by tomolimo** [comment]
Ok, thank you,

**Comment by ddurieux** [comment]
add this because it's in GLPI, I will modify this fusioninventory function and all calls, it's not a problem
