### ISSUE TITLE
Supplier received e-mail same 'Email Followup' is set "No"

### ISSUE THREAD

**Issue by brenodveronezi** [glpi-project/glpi#8074]
GLPI send email notification for suppliers assigned in to ticket,  same "email followup" is set yes or not.

I create the ticket and set email follow up for the supplier NOT, ths supplier is my.

![forn1](https://user-images.githubusercontent.com/40043968/95241443-20d99380-07e4-11eb-9126-18ce3ba65f0f.PNG)

Add the followup in the ticket:

![followup](https://user-images.githubusercontent.com/40043968/95241599-5e3e2100-07e4-11eb-8d27-c5b9b67d0db4.PNG)

GLPI generated the email for supplier, same definied NOT.

![fon2](https://user-images.githubusercontent.com/40043968/95241664-744be180-07e4-11eb-9cb0-de955189c3fa.PNG)

I checked that issue happen only to suppliers.

GLPI Version i tested: 9.5.0 and 9.5.1.

Your can help me fix this?

**Comment by cedric-anne** [comment]
Hi,

I guess this is linked to #5656.

Regards

**Comment by brenodveronezi** [comment]
Hi,

In issue #5656 the 'Email Followup' is set to send email, here is set to not send email, but send even so.

Regards,

**Comment by eduardomozart** [comment]
I could also reproduce the issue. The supplier only receives the email if the "Suppliers" are added into "Add followup" notification (Setup > Notifications > Notifications > Add followup > Recipients), but it ignores the 'Email Followup' option set to "No" from the ticket and send the email to the supplier anyway.

**Comment by eduardomozart** [comment]
GLPI seems to respect the "Email Followup" field from requester set to "No" when the "Requesters" is added into "Add followup" notification (Setup > Notifications > Notifications > Add followup > Recipients). It only ignores the "Email Followup" field from Suppliers.
