### ISSUE TITLE
9.5.2 - Tickets dashboard overlaps search form

### ISSUE THREAD

**Issue by kevin-m87** [glpi-project/glpi#8077]
Hi this issue is still there with 9.5.2 : https://github.com/glpi-project/glpi/issues/7867

Describe the bug

Tickets dashboard overlaps search form (see screenshot), preventing clicks on the top of some inputs.

Page(s) URL

/front/ticket.php

To reproduce

    Go to /front/ticket.php
    Select Items seen contains for the first search criterion
    Try to click on the criterion input
    Click does not give focus if done on the top half of the input

**Comment by husisusi** [comment]
I can not reproduce this issue!

**Comment by kevin-m87** [comment]
Yes when i disable tickets dashboard its works.

There is a issue with https://github.com/glpi-project/glpi/commit/a80a00e88f323f117134929dadfaf4b4f2bc0211

**Comment by andrepetinga** [comment]
Same here. The mention issue [a80a00e](https://github.com/glpi-project/glpi/commit/a80a00e88f323f117134929dadfaf4b4f2bc0211) doens't resolve it.

**Comment by fralla2** [comment]
Same here with 9.5.2 and all bugfixes prior to November 10 applied...

![image](https://user-images.githubusercontent.com/38400135/99609331-aa80a180-29dd-11eb-8c56-b5b1988cd679.png)

As you can see, the mini-dashboard appears positionned correctly but on all dropdowns, only the part bellow the red line is clickable. 

![Screenshot_20201118-205355_Microsoft Remote Desktop](https://user-images.githubusercontent.com/38400135/99610914-b15ce380-29e0-11eb-908e-a5f924b6e06f.jpg)
![Screenshot_20201118-205501_Microsoft Remote Desktop](https://user-images.githubusercontent.com/38400135/99610917-b1f57a00-29e0-11eb-8182-e69ee6d3e21b.jpg)

Seems to be the style of one of those 2 elements that make the div overlap the search dropdowns
div id="dashboard-18664391u" of class="dashboard mini"
or 
div id="grid-stack-186643917" of class="grid-stack grid-stack-33 grid-stack-instance-2642 grid-stack-static"

**Comment by andrepetinga** [comment]
Just installed 9.5.3 and the overlap problem is gone! :)
What I noticed now is the text size of the dashboard buttons, it has gone bigger and won't change line...

![image](https://user-images.githubusercontent.com/43515938/101152566-2eac6900-361b-11eb-9aa1-df51bf235993.png)

**Comment by husisusi** [comment]
This bug has been resolved. You can close this issue.

**Comment by trasher** [comment]
Thank you for the feedback.
