### ISSUE TITLE
Undefined index warnings on update 9.4.7 to 9.5.2

### ISSUE THREAD

**Issue by fabissilva** [glpi-project/glpi#8081]
**Describe the bug**
when I log in with my user on glpi

**Page(s) URL**
http://192.168.xxx.1/glpi/front/central.php

If applicable, page(s) URL where the bug happens.
inicial page

**To reproduce**
was after upgrading from 9.4.7 to 9.5.2 the message appears **Notice: **Undefined index: GLPI in C:\xampp\htdocs\GLPI\inc\user.class.php on line 5129

[migration_to_9.5.0.log](https://github.com/glpi-project/glpi/files/5343367/migration_to_9.5.0.log)
[migration_to_9.5.2.log](https://github.com/glpi-project/glpi/files/5343368/migration_to_9.5.2.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/5343369/php-errors.log)
[sql-errors.log](https://github.com/glpi-project/glpi/files/5343370/sql-errors.log)
[warning_during_migration_to_9.5.0.log](https://github.com/glpi-project/glpi/files/5343371/warning_during_migration_to_9.5.0.log)
[cron.log](https://github.com/glpi-project/glpi/files/5343372/cron.log)
[event.log](https://github.com/glpi-project/glpi/files/5343373/event.log)
[mail.log](https://github.com/glpi-project/glpi/files/5343374/mail.log)
[migration_to_9.4.7.log](https://github.com/glpi-project/glpi/files/5343375/migration_to_9.4.7.log)
![3](https://user-images.githubusercontent.com/57729814/95378754-bfd0bf00-08ba-11eb-82ec-8cb1657303e1.PNG)
![1](https://user-images.githubusercontent.com/57729814/95378759-c0695580-08ba-11eb-885e-2f4fac019609.PNG)
![2](https://user-images.githubusercontent.com/57729814/95378761-c101ec00-08ba-11eb-8a0a-779f895c1f7d.PNG)

**Comment by cedric-anne** [comment]
Hi,

#8083 should fix this issue.

Regards
