### ISSUE TITLE
UserId override for ITIL Solution through API

### ISSUE THREAD

**Issue by bosquig** [glpi-project/glpi#8090]
**Describe the bug**

When adding a solution to a ticket through the API with a given "users_id", the input "users_id" is overriden by the current user which is a problem if we have a connector user handling API requests. Can you be consistant with the followup behavior for example ?

in itilsolution.class.php - prepareInputForAdd : 
```      $input['users_id'] = Session::getLoginUserID();```

whereas in itilfollowup.class.php - prepareInputForAdd : 
```     
 if (!isset($input["users_id"])) {
         $input["users_id"] = 0;
         if ($uid = Session::getLoginUserID()) {
            $input["users_id"] = $uid;
         }
      }
```

**To reproduce**

POST /apirest.php/ITILSolution
{"input":[{"content":"resolution","users_id":6,"itemtype":"Ticket","_auto_import":true,"items_id":2,"solutiontypes_id": 1,"add":true}]}

**Expected behavior**

If users_id of the request session is "1", the solution will be linked to users_id 1 instead of 6. (should be the user indicated in POST body and not current user)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.1
```

**Comment by jeanpaulo** [comment]
Same happened to me yesterday, on **GLPI 9.4.5**, through another endpoint.

**To reproduce:**
POST /apirest.php/ticket/<ticket_id>/itilsolution/
{"id":14163,"input":[{"itemtype":"Ticket","items_id":14163,"content":"&lt;p&gt; Content.&lt;/p&gt;","users_id":95,"status":2,"solutiontypes_id":0}]}

When I get this itil solution request, the users_id is different. 
The API posted the integration user that i was testing.
