### ISSUE TITLE
[9.5.1 & 9.5.2] Undefined index: itemtype in front/item_disk.form.php when disk/volume purge

### ISSUE THREAD

**Issue by dkurzelewski** [glpi-project/glpi#8092]
**Describe the bug**

When volume is delete (permanent) GLPI not back to volume page of asset. In debug mode I've get

```
PHP Notice (8): Undefined index: itemtype in front/item_disk.form.php at line 71
Uncaught Exception Error: Class name must be a valid object or a string in front/item_disk.form.php at line 72
```

**Page(s) URL**

front/item_disk.form.php

**To reproduce**

1. Go to 'Asset'->'Computer'
2. Select any computer with volumes
3. Click on volume to see details (redirect to front/item_disk.form.php?id=xx)
4. Click ' Delete permanently' button
5. Confirm deletion

In 'normal' mode -> blank page
In 'debug' mode -> message

```
PHP Notice (8): Undefined index: itemtype in front/item_disk.form.php at line 71
Uncaught Exception Error: Class name must be a valid object or a string in front/item_disk.form.php at line 72
```

**Comment by trasher** [comment]
I've not been able to reproduce (tester on master branch, but there were no notable changes with 9.5/bugfixes one). Anyways, #8101 should fix your issue.
