### ISSUE TITLE
glpi 9.5.x Reports Status "Warning state.class.php on line 185"

### ISSUE THREAD

**Issue by wasonhome55555** [glpi-project/glpi#8095]
Hi glpi everyone,

  I Used glpi 9.5.2 , glpi 9.5.3 Reports Status Menu >>  "Warning state.class.php on line 185"

[<img src="https://www.img.in.th/images/9bdd1e4932482d3bf9c5635c9c9b478d.jpg" alt="9bdd1e4932482d3bf9c5635c9c9b478d.jpg" border="0" />](url)

How do I Fix this Problem ? or Has Bug ?

I Install GLPI 9.5.2 on XAMPP for Windows 7.4.7 , PHP Version 7.4.7 (Windows Server 2012 R2)

**Comment by eliottdbs** [comment]
Hi,

I have a similar issue : when I select Status Report, an infinite and empty array is generated.
I'm currently with GLPI 9.5.2 (and apache2) on Linux.

![Capture d'écran Deepin_zone de sélection _20201015153500](https://user-images.githubusercontent.com/56924502/96137260-bec41100-0efc-11eb-928b-10ffd26334d4.png)

Thanks
