### ISSUE TITLE
glpi 9.5-9.5.3 Timezone Not Load on XAMPP for Windows 7.4.7

### ISSUE THREAD

**Issue by wasonhome55555** [glpi-project/glpi#8096]
Hi All GLPI Everyone ,

  I Has found Timezone not Load I found this problem after upgrade version glpi 9.4.6 to glpi 9.5.0 and glpi 9.5.3 , I Cannot see timezone in GLPI 9.5.3

[<img src="https://www.img.in.th/images/9a4c2faebec74d384dfaa5af13ed3139.jpg" alt="9a4c2faebec74d384dfaa5af13ed3139.jpg" border="0" />](url)

I Install GLPI 9.5.2 and Upgrade to 9.5.3 on XAMPP for Windows 7.4.7 , PHP Version 7.4.7 (Windows Server 2012 R2)

**Comment by trasher** [comment]
Well, all should be explained in provided link. Please use forums for support.
