### ISSUE TITLE
[GLPI 9.5.1] Error during message parsing

### ISSUE THREAD

**Issue by miodzio97** [glpi-project/glpi#8100]
GLPI can't download ticket from email with standard jpg or jpeg attachment.
When i try download manually in receivers I have error in :

Error during message parsing: Laminas\Mail\Header\ContentType::setType expects a value in the format "type/subtype"; received "image/*"

Type of documents are ok:

![image](https://user-images.githubusercontent.com/32955663/95855406-a61af600-0d58-11eb-876c-1deb554ff474.png)
![image](https://user-images.githubusercontent.com/32955663/95856772-de233880-0d5a-11eb-8085-833618e1abfa.png)
![image](https://user-images.githubusercontent.com/32955663/95857329-bda7ae00-0d5b-11eb-8347-a6ae8564f711.png)

**Comment by trasher** [comment]
This has been fixed in 9.5.2
