### ISSUE TITLE
Mail retrieving stops on certain mails (probably Content-Transfer-Encoding problem)

### ISSUE THREAD

**Issue by paulz1** [glpi-project/glpi#8107]
**Describe the bug**

We use GLPI 9.5.0 (installed over CentOS Linux release 7.8.2003) (Installation mode: TARBALL)

Essentially we use it for ticketing.
Recently we have a strange problem. Sometimes some users send a ticket via e-mail and this ticket stay blocked in the mailbox (and so, these tickets block all further tickets send by mail).

If we go to "Receivers" and do "Get email tickets now" we get a blank screen and the operation is stopped. We could go back to GLPI pages, but the mails are not retrieved.

We did some little debug on our side and we have an impression that the problem is linked to Headers processing and particularly with "Content-Transfer-Encoding".
But it's not clear that exactly happens and why.

If we remove the mail with a problem, automatic (and manual) mail retrieving starts work again.

1. User send a mail with a ticket
2. Automatic action to get the mails into tickets do not work
3. The mail stay in the mailbox, it's not retrieved. And this mail block all others further mails.
4. Manual action to "retrieve the mails" do not work neither

**Comment by trasher** [comment]
Update to 9.5.2
