### ISSUE TITLE
I Cannot Delete this Plugin "Form Creator" from GLPI 9.5.2

### ISSUE THREAD

**Issue by wasonhome55555** [glpi-project/glpi#8123]
Hi GLPI Everyone
   I Cannot Delete this plugin "Form Creator" and GLPI 9.5.X - 9.5.2 Has Remember old version and Cannot Install Form Creator New Version
  I Install this "Form Creator" from GLPI 9.2.3 but I Has upgrade to GLPI 9.5.X - 9.5.2 and I Cannot Upgrade "Form Creator" New Version Plugin

<img src="https://www.img.in.th/images/532d1af643a915923f78768dff004fb2.jpg" alt="532d1af643a915923f78768dff004fb2.jpg" border="0">

<img src="https://www.img.in.th/images/fd4efa56ca574867be96446693a07112.jpg" alt="fd4efa56ca574867be96446693a07112.jpg" border="0">

<img src="https://www.img.in.th/images/2ad940bc2244023cffeb178b568450c0.jpg" alt="2ad940bc2244023cffeb178b568450c0.jpg" border="0">

**Comment by trasher** [comment]
Please report issue on plugin; this is not a glpi issue
