### ISSUE TITLE
[0.90.3] "Alerts by email" field missing on contracts

### ISSUE THREAD

**Issue by barbuslex** [glpi-project/glpi#813]
Hi,

Sice GLPI 0.90, I cannot find the column "Alerts by email" on contracts.

![contracts](https://cloud.githubusercontent.com/assets/113057/16943132/597c1b44-4d9a-11e6-99a7-0a61c682309b.jpg)
![contract_detail](https://cloud.githubusercontent.com/assets/113057/16943134/5a4e060e-4d9a-11e6-8b33-a0ebc647f916.jpg)

The column moved elsewhere or is it a bug?

Thanks for your reply

++

**Comment by flegastelois** [comment]
Hi,

To be able to view this field on contract form, you must enable the "Alarms on contracts" option in the configuration of the entity.

![image](https://cloud.githubusercontent.com/assets/470612/16944482/2163a5a4-4da1-11e6-9648-fdf7a9f80fcc.png)

Regards,

**Comment by barbuslex** [comment]
Exact!

Thanks so much
