### ISSUE TITLE
Notice: Trying to access array offset on value of type bool in "commondropdown.class.php on line 974"

### ISSUE THREAD

**Issue by wasonhome55555** [glpi-project/glpi#8131]
Hi GLPI Everyone,

  I Has this error "Notice: Trying to access array offset on value of type bool in C:\xampp\htdocs\glpi\inc\commondropdown.class.php on line 974"
  How do I fix this problem ?

<img src="https://www.img.in.th/images/9765986811f37da62938b809c0fab999.jpg" alt="9765986811f37da62938b809c0fab999.jpg" border="0" />

<img src="https://www.img.in.th/images/9a3b919f4e0ed0a77f806b6b4c66c0b4.jpg" alt="9a3b919f4e0ed0a77f806b6b4c66c0b4.jpg" border="0" />

**Comment by cedric-anne** [comment]
Hi,

Please provide requested informations, as GLPI version, full trace of the error, ...

Regards

**Comment by ajithc16** [comment]
I am getting the same warning using GLPI version 9.5.3 on LAMPP 8.0 (PHP 8). 
My GLPI site was recently upgraded from an old version 9.3.3 on LAMPP 7.0.8

**Comment by YullR** [comment]
I am getting the same warning using GLPI version 9.5.5

**Comment by cconard96** [comment]
Does the change in #9556 resolve the issue for you?
