### ISSUE TITLE
Input Field Missing when solving a Ticket

### ISSUE THREAD

**Issue by wagneral** [glpi-project/glpi#814]
Hello everyone,

I just made a new pull and unfortunately found a small error in the "processing ticket" mask.

When entering the blue "Solution" button to solve a ticket, the form field "description" is not visible. This occurs when having selected a custom language: the form field only is visible when having selected "English" or "Francais"

Kind regards

![glpi_solve-ticket](https://cloud.githubusercontent.com/assets/6931503/16953262/ac0eb0c4-4dcc-11e6-8a07-c411ab31248e.png)

**Comment by orthagh** [comment]
Fixed

Could you confirm you're using current master of the project ?

**Comment by wagneral** [comment]
Thanks for fixing it. And yes, I'm using the current master of the project.
