### ISSUE TITLE
Software -> Version  child entities attribute change from yes to no

### ISSUE THREAD

**Issue by balucha** [glpi-project/glpi#815]
In windows with creating new software version child entities is set to yes and I cant`t change it(inhered form parents).

![software1](https://cloud.githubusercontent.com/assets/13922307/16966224/de24c468-4e03-11e6-9e95-1187c4e8a87c.png)
When I open new version child entities attribute is changed to no (GLPI says that is inhered form parents too). Where is truth?
![software2](https://cloud.githubusercontent.com/assets/13922307/16966223/de249790-4e03-11e6-923a-c394b243bc3d.png)

Not working after upgrade from 0.85.3 to 0.90.4

**Comment by balucha** [comment]
I tested it and it is no question, but the bug. 
Everything works OK till 0.85 version. In 0.85 version or above is a problem. In version 0.85 was added attribute child entities to software versions.  When I create new software version, it creates with attribute child entities to NO in spite of that in create windows is set to YES. This is bug. 
When I creating new version GLPI saying me that attribute child entities will be set to YES, but is set to NO. Look at the pictures in first post. On first picture is situation when I creating new version, on second picture is situation when I open created new version.
 Then I cannot move software from old version to new using massive actions in child entities. But manualy I can do this (delete software from computer and than again add same software and I choose new version).

Try creating new software version and you will see.

All versions created in 0.84 and migrated to 0.85 or above has attribute child entities set to YES. Only versions created in 0.85 or above are set to NO.

**Comment by orthagh** [comment]
I replicate the issue.
To be sure, i tested also with 0.85.5 and 0.84.8 versions and the "bug" was already here.

In fact, in the db, glpi_softwareversions table doesn't have "is_recursive" field, the diplayed "child entities" information should be from the parent object (in this case the software).
I think only the display is wrong. I currently investigate on this display.

Also, "Then I cannot move software from old version to new using massive actions in child entities", could you explain what you do,; i can't understand this part and where is the bug occurs.

**Comment by balucha** [comment]
Not only display is wrong because I can`t use this versions on computers in child entities with move function(look at the pictures.).  

Adobe Reader is in the root entity, computers are in child entities and I trying to upgrade old versions to new 9.5 version. No success, because version 9.5 has attribute child entities set to NO. 

p.s. for what reason is good this attribute in software version? I think that software versions must have same attributes(values) as software(parent).
Can I change this attribute (can I set/change which version can be used/installed in child entities)?  If no, then this attribute is useless.

![sw1](https://cloud.githubusercontent.com/assets/13922307/17117534/bd8ee0f4-52bc-11e6-8d7f-c507ab932491.png)
![sw3](https://cloud.githubusercontent.com/assets/13922307/17117535/bd98c6b4-52bc-11e6-8104-f07057ed5e00.png)

**Comment by orthagh** [comment]
Ok i confirm the behavior with the versions and the entities/recursivity.

Here is the fix you can apply on your instance (it will be in 0.90.5) : 
https://github.com/glpi-project/glpi/compare/306bc32f31629b6321ac9a4b4f58bf59e709a192...372b7eb847d492ba4e7a0e210c86ff0f573c4e3f

You could also "fix" your db with this query : 
```SQL
UPDATE glpi_softwareversions SET is_recursive = 1 WHERE is_recursive = 0;
```

For the attribute, i agree with you, but my global understanding of this part of glpi (child/parent management) is poor, so i prefer to not break things by removing fields.
Anyways, I could do  small fix like the current one.

If you agree, i think we can close this issue.
