### ISSUE TITLE
Fixed footer

### ISSUE THREAD

**Issue by stdonato** [glpi-project/glpi#816]
Fixed footer.
Put this function in script.js fix footer: 

/* Fixed footer */
		 $(document).ready(function() {
		
		   var docHeight = $(window).height();
		   var footerHeight = $('#footer').height();
		   var footerTop = $('#footer').position().top + footerHeight;
		
		   if (footerTop < docHeight) {
		    $('#footer').css('margin-top', 4+ (docHeight - footerTop) + 'px');
		   }
		  });

**Comment by flegastelois** [comment]
Hi,

I don't understand your message.
Can you give us further explanation ?

Regards,

**Comment by stdonato** [comment]
Hi,
The page footer not is fixed at the bottom.


Regards,

Stevenes DOnato

2016-07-21 4:27 GMT-04:00 François Legastelois <notifications@github.com>:

**Comment by orthagh** [comment]
@stdonato 

Why do you want to fix footer on bottom ?

It's already the case in splitted layout, but in "left tab" layout, we don't want fixed footer.

see #730 (duplicate ?)
