### ISSUE TITLE
Duplicate recurring tickets on GLPI 9.4.6

### ISSUE THREAD

**Issue by fjcobo** [glpi-project/glpi#8168]
Same problem that #6205
Several tickets created by "cron_ticketrecurrent" when begin date is not in calendar.  Possible on GLPI 9.4.6 ?

[code]

GLPI 9.4.6 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL
Server
Operating system: Linux  3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64
PHP 7.2.28 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, libxml,
	mbstring, mongodb, mysqli, mysqlnd, oci8, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pdo_sqlsrv, pgsql, posix, redis,
	session, shmop, soap, sockets, sqlite3, sqlsrv, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="2G" post_max_size="100M" safe_mode="" session.save_handler="files"
	upload_max_filesize="100M" 
Software: Apache ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0
Server Software: MariaDB Server
	Server Version: 10.2.31-MariaDB
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

[/code]

**Comment by cedric-anne** [comment]
Hi,

Please provide all requested informations when creating an issue. Without your installation and settings details, it is complicated to investigate.

Regards

**Comment by trasher** [comment]
GLPI 9.4 is no longer maintained. Please try if you reproduce on 9.5.2

**Comment by fjcobo** [comment]
thanks for your quick response @cedric-anne @trasher

**Comment by cedric-anne** [comment]
We fixed some bugs on calendar computation in last few month, but I could not say the specific versions affected.

First, you should try to reproduce on GLPI 9.5.2 and see if problem persist. In this case, please provide the exact configuration of your recurrrent ticket and of your calendar settings.
