### ISSUE TITLE
GLPI 9.5.2 - Barre de recherche / Search bar

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#8169]
**Describe the bug**

Search bar not available when we want to add a "requester" or "observer" on an existing ticket.
I don't know if this is part of the bug category but see the details below :

**To Reproduce**

1. Create a ticket
2. In the search bar when selecting the requester, it is available and you can directly type the name of your user and select it in the short list.
3. Go back to the created ticket then add another requester or observer.
**Expected behavior**

This search bar saves us time because we have a large number of users in the GLPI database.

Example where the bar is not visible, there is a "------" instead.
![ticket2](https://user-images.githubusercontent.com/63521311/97163571-242bc380-1781-11eb-82ee-3f948e61a45b.png)

Ce que nous souhaitons avoir :
![ticket4](https://user-images.githubusercontent.com/63521311/97163763-681ec880-1781-11eb-8660-9ca924f7055f.png)

**GLPI:**
v9.5.2
Ubuntu

**Desktop :**
 - Windows 10 2004
 - MS Edge 
 - Version 85.0.564.63 (Version officielle) (64 bits)

**Comment by trasher** [comment]
Please use only english on github issues

**Comment by stdglpi** [comment]
> Please use only english on github issues

Sorry it's updated.

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce this issue. I have the search feature on update form as well as on creation form. Do you use some plugin ? Can you try to deactivate them and see if issue persist ?
Also, how long is your list ? There is a configuration that is use to determine, fro dropdown, the minimum length from which the search feature will be displayed: `Don't show search engine in dropdowns if the number of items is less than`.

Regards

**Comment by stdglpi** [comment]
> Also, how long is your list ? There is a configuration that is use to determine, fro dropdown, the minimum length from which the search feature will be displayed: `Don't show search engine in dropdowns if the number of items is less than`.
> 
> Regards

**Thank you ! It was fixed on "100" on this setting. I applied on "never" and now it is working.**

- [X] You can close this request
