### ISSUE TITLE
error after upgrade to 9.5.2

### ISSUE THREAD

**Issue by xc0derx** [glpi-project/glpi#8173]
After upgrade 9.51. to 9.5.2 view blank page and
error in files/_log/php-errors.log:
[2020-10-27 07:03:20] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function Laminas\I18n\Translator\Plural\ctype_digit() in /home/www/glpi/vendor/laminas/laminas-i18n/src/Translator/Plural/Parser.php at line 315
  Backtrace :
  ...minas-i18n/src/Translator/Plural/Parser.php:264 Laminas\I18n\Translator\Plural\Parser->getNextToken()
  ...minas-i18n/src/Translator/Plural/Parser.php:125 Laminas\I18n\Translator\Plural\Parser->expression()
  ...minas-i18n/src/Translator/Plural/Symbol.php:139 Laminas\I18n\Translator\Plural\Parser::Laminas\I18n\Translator\Plural\{closure}()
  ...minas-i18n/src/Translator/Plural/Parser.php:260 Laminas\I18n\Translator\Plural\Symbol->getNullDenotation()
  ...minas-i18n/src/Translator/Plural/Parser.php:247 Laminas\I18n\Translator\Plural\Parser->expression()
  ...laminas-i18n/src/Translator/Plural/Rule.php:207 Laminas\I18n\Translator\Plural\Parser->parse()
  ...inas-i18n/src/Translator/Loader/Gettext.php:148 Laminas\I18n\Translator\Plural\Rule::fromString()
  .../laminas-i18n/src/Translator/Translator.php:745 Laminas\I18n\Translator\Loader\Gettext->load()
  .../laminas-i18n/src/Translator/Translator.php:617 Laminas\I18n\Translator\Translator->loadMessagesFromFiles()
  .../laminas-i18n/src/Translator/Translator.php:440 Laminas\I18n\Translator\Translator->loadMessages()
  .../laminas-i18n/src/Translator/Translator.php:355 Laminas\I18n\Translator\Translator->getTranslatedMessage()
  inc/autoload.function.php:123                      Laminas\I18n\Translator\Translator->translate()
  inc/user.class.php:3042                            __()
  inc/commondbtm.class.php:3626                      User->rawSearchOptions()
  inc/commondbtm.class.php:3933                      CommonDBTM->searchOptions()
  inc/commondbtm.class.php:4005                      CommonDBTM->getSearchOptionByField()
  inc/commondbtm.class.php:1442                      CommonDBTM->filterValues()
  inc/auth.class.php:913                             CommonDBTM->update()
  front/login.php:84                                 Auth->login()

**Comment by cedric-anne** [comment]
Hi,

I guess you use FreeBSD, which does not include the `ctype` extension by default in its PHP package.

You have to install this extension. Documentation: https://www.php.net/manual/en/ctype.installation.php

Regards
