### ISSUE TITLE
[9.1] and [0.90.4] Problem with settings sql_mode ONLY_FULL_GROUP_BY

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#819]
MySQL 5.7. With this option sql_mode in 9.1 is not displaing tickets in the tickets tab.

MySQL 5.5. With this option sql_mode in 0.90.4 is not displayed tickets in the home tab.

**Comment by orthagh** [comment]
see #627 for details.

I close this issue to avoid duplicate.
