### ISSUE TITLE
Default unit for Harddisk drive

### ISSUE THREAD

**Issue by ashmonger** [glpi-project/glpi#821]
Hey,

I was filling a brand new GLPI but something hit me, when we create new componants, especially HDD, the default capacity is expressed in Mio and not Gio, is it just a little thing to change (so I can do it) or is it something you want to stay this way even we do not use HDD smaller than Gio ?

GLPI 9.1 RC1

Thanks

**Comment by orthagh** [comment]
Hello @ashmonger 

Here is the place where the volumes are displayed : 
https://github.com/glpi-project/glpi/blob/master/inc/computerdisk.class.php#L300-L303

In fact, i think the MB unit is now a little outdated (glpi is more than 10 years old), maybe we can think to update to GB to match current volumes sizes.

**Comment by orthagh** [comment]
Here is a fix

**Comment by ashmonger** [comment]
Thanks!
Can't wait to have the next release!
