### ISSUE TITLE
Error on console command

### ISSUE THREAD

**Issue by koddajr** [glpi-project/glpi#8225]
i'm testing glpi 9.5.2 and when a type the command "php bin/console glpi:migration:timestamps" say is not defined

**Page(s) URL**

**To reproduce**

1. go to cmd
2. type php bin/console glpi:migration:timestamps
3. see the error

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

![2](https://user-images.githubusercontent.com/53986027/98016523-d9dbbf80-1ddc-11eb-803e-19dc03e259df.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

This command is handled by the `inc/console/migration/timestampscommand.class.php` file. Is this file is missing on your GLPI ?

Also, can you provide informations related to your GLPI setup, as requested in issue form ?

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as no feedback was given.

Regards

**Comment by Scjonatha** [comment]
Olá, poderia me informar que arquivo é esse que você havia citado em uma das respostas a cima por favor : 
```
inc/console/migration/timestampscommand.class.php
``` 
Estou com o mesmo problema, já pesquisei como resolver porém não compreendi muito bem as resoluções que encontrei. No meu caso realizei uma atualização da versão 9.5.7 para a versão 10.0.12 (utilizo o windows server), após essa atualização esse erro começou a aparecer e então executei o comando: 
```
C:\xampp\htdocs\glpi> php bin/console migration:timestamps
``` 
e o seguinte erro foi retornado: 'php' is not recognized as an internal or external command. operable program or batch file.
Acredito que esteja faltando esse arquivo que você sitou. Como consigo baixar esse arquivo para o meu diretorio do glpi?

![folder bin](https://github.com/glpi-project/glpi/assets/97475763/521f8658-cc6b-4fad-9861-242c27ddeffe)
![folder inc](https://github.com/glpi-project/glpi/assets/97475763/8e38acb3-9a78-4e53-a753-a61bb625dc15)
