### ISSUE TITLE
[9.5.2]  Sometimes it doesn't show network ports for network devices

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#8257]
**Describe the bug**

The network port card does not display content

**Page(s) URL**

glpi/front/networkequipment.form.php

**To reproduce**

Home > Assets > Network devices > I choose a device > network ports tab > they are there or aren't

**Expected behavior**

I should see a list of ports

**Logs**

In debug mode: Uncaught Exception HTMLTableUnknownHeader: Instantiation:Origin in /var/www/html/glpi/inc/htmltablebase.class.php at line 160

**Screenshots**

![problem](https://user-images.githubusercontent.com/68922721/98961103-7a309300-2505-11eb-870a-ee518511b6f4.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Linux chronos 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at .......... Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.193 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.22-0ubuntu0.20.04.2
	Server SQL Mode: 
	Parameters: ..........
	Host info: Localhost via UNIX socket

**Additional context**

I have tried on different computers, tried to delete the device and inventory it again.

Please ignore the error in the screenshot for glpi_cache_db_9.5.2.json - this has already been resolved, but it did not change the port display problem.

**Comment by trasher** [comment]
Please provide logs

**Comment by WebGregGit** [comment]
[2020-11-12 16:35:28] glpiphplog.CRITICAL:   *** Uncaught Exception HTMLTableUnknownHeader: Instantiation:Origin in /var/w>
  Backtrace :
  inc/htmltablerow.class.php:205                     HTMLTableBase->getHeaderByName()
  inc/networkportaggregate.class.php:108             HTMLTableRow->getHeaderByName()
  inc/networkportinstantiation.class.php:194         NetworkPortAggregate->getInstantiationHTMLTable()
  inc/networkportinstantiation.class.php:238         NetworkPortInstantiation->getPeerInstantiationHTMLTable()
  inc/networkportethernet.class.php:169              NetworkPortInstantiation->getInstantiationHTMLTableWithPeer()
  inc/networkport.class.php:772                      NetworkPortEthernet->getInstantiationHTMLTable()
  inc/networkport.class.php:1198                     NetworkPort::showForItem()
  inc/commonglpi.class.php:637                       NetworkPort::displayTabContentForItem()
  ajax/common.tabs.php:92                            CommonGLPI::displayStandardTab()

**Comment by viktor-sc** [comment]
I have a similar error. Also Network ports. But for me it doesn't open always for the same devices. So on some devices it shows up, on others it doesn't at all.
Unfortunately there's no entry in the logs! Sometimes it shows an error saying the memory limit exceeded. Sometimes just a generic error like in the attached screenshot.
![image](https://user-images.githubusercontent.com/21951987/99239727-c1679e00-27fb-11eb-9631-a28a224a7eaf.png)

**Comment by cedric-anne** [comment]
> I have a similar error. Also Network ports. But for me it doesn't open always for the same devices. So on some devices it shows up, on others it doesn't at all.
> Unfortunately there's no entry in the logs! Sometimes it shows an error saying the memory limit exceeded. Sometimes just a generic error like in the attached screenshot.
> ![image](https://user-images.githubusercontent.com/21951987/99239727-c1679e00-27fb-11eb-9631-a28a224a7eaf.png)
> 
> Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 16384 bytes) in /volume1/web/glpi/inc/dbmysql.class.php on line 299 Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /volume1/web/glpi/vendor/composer/ClassLoader.php on line 444 Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 36864 bytes) in Unknown on line 0

This one was fixed by #8221 

For the error mentionned by @WebGregGit , trace is different, so maybe error source is different too.

**Comment by WebGregGit** [comment]
SOLVED after updating to version 9.5.3
