### ISSUE TITLE
APIREST - GLPI Network port for network equipment

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#8262]
**Describe the bug**

I use GLPI 9.5.2
When you use REST API to find a NetworkEquipment you are not able to find the management ip adress.

**Page(s) URL**

http://XXX/apirest.php/NetworkEquipment/XX/NetworkPort/ID

**To reproduce**

1. Ask for http://XXX/apirest.php/NetworkEquipment/XX/NetworkPort/ID

**Expected behavior**

A field called ipaddress should appear

**Logs**

$VAR1 = {
          'logical_number' => 0,
          'is_recursive' => 0,
          'itemtype' => 'NetworkEquipment',
          'name' => 'management',
          'date_mod' => '2020-11-05 01:22:57',
          'items_id' => 57,
          'date_creation' => '2020-11-05 01:22:57',
          'is_dynamic' => 0,
          'instantiation_type' => 'NetworkPortAggregate',
          'comment' => undef,
          'entities_id' => 0,
          'is_deleted' => 0,
          'id' => 2988,
          'mac' => '00:0c:85:fa:8b:c0',
          'links' => [
                       {
                         'rel' => 'NetworkEquipment',
                         'href' => 'http://XXXXX/apirest.php/NetworkEquipment/57'
                       },
                       {
                         'rel' => 'Entity',
                         'href' => 'http://XXXXX/apirest.php/Entity/0'
                       }
                     ]
        };

**Comment by orthagh** [comment]
hello @lolokai 

Could you please open this issue on teclib support ?
