### ISSUE TITLE
Dashboard display issues

### ISSUE THREAD

**Issue by paulopimentel** [glpi-project/glpi#8270]
When adding a card containing graphics, (number of calls per month, status of calls, evolution of calls) when opening the home screen to check the chart it appears as if it were to be loaded and then the information disappears, sometimes it even shows the graph however cuts the bottom part of the graph showing the months.

URL of the page (s)
localhost/front/central.php

Home page, add the card in data, enter the type (number of calls per month, status of calls, evolution of calls) then apply.
And saved.

Screenshots
![image](https://user-images.githubusercontent.com/13908364/99094920-35fbcc00-25b3-11eb-8b69-842cc9c8bb4e.png)
![image](https://user-images.githubusercontent.com/13908364/99095022-59267b80-25b3-11eb-9f66-829bea79c417.png)
![image](https://user-images.githubusercontent.com/13908364/99095054-65aad400-25b3-11eb-8d87-9eddacc8c43c.png)

I need this dashboard working, can you help me?

**Comment by trasher** [comment]
You did not specify which GLPI version you are using. Since there were several issues already fixed, please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))

**Comment by phamorais** [comment]
@trasher 

Hello!
In my test environment the same thing happens. However I realized that the occurrence is mainly with the google chrome browser.

GLPI 9.5.2


Print when running the dashboard using google chrome

![chrome2](https://user-images.githubusercontent.com/35368369/99255902-5c0faf00-27f3-11eb-900a-ae42e087addc.gif)


Print when running the dashboard usingfirefox. See that with firefox the error is not displayed

![firefox](https://user-images.githubusercontent.com/35368369/99255460-b9573080-27f2-11eb-9bd1-8484d5a60e71.gif)


Log in /files/_log/php-errors.log

![image](https://user-images.githubusercontent.com/35368369/99256070-98dba600-27f3-11eb-8ffd-dce8e72398ff.png)

![image](https://user-images.githubusercontent.com/35368369/99257220-734f9c00-27f5-11eb-847e-f799ddc56d6b.png)

![image](https://user-images.githubusercontent.com/35368369/99257440-cb869e00-27f5-11eb-9fb8-c75a0edfc661.png)

**Comment by cedric-anne** [comment]
@paulopimentel @phamorais ,

These issues may have been fixed by #8151 and #8170 . Could you confirm ?

Regards

**Comment by paulopimentel** [comment]
> You did not specify which GLPI version you are using. Since there were several issues already fixed, please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))

Thanks, got the last bug fix, thanks. Resolved!

**Comment by trasher** [comment]
Great, thanks for the feedback :)

**Comment by phamorais** [comment]
@cedric-anne 

After apply https://github.com/glpi-project/glpi/pull/8151 and https://github.com/glpi-project/glpi/pull/8170 only a blank page is displayed.

![image](https://user-images.githubusercontent.com/35368369/99410107-d7935e00-28d0-11eb-9408-b96df2ba2130.png)

**Comment by cedric-anne** [comment]
@phamorais 

Maybe patch was not applied correctly. However, as you are using a test environment, you may consider to use the [latest nighlty build](https://github.com/glpi-project/glpi/actions/runs/369245988).

Regards
