### ISSUE TITLE
Problem with viewing of imported emails part II

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#8281]
Sending email from Outlook and office 365 mail server to GLPI IMAP mailcollector will create a ticket with wrong view.

Original email eml:
[Test mail to GLPI.txt](https://github.com/glpi-project/glpi/files/5546514/Test.mail.to.GLPI.txt)

It looks:

![image](https://user-images.githubusercontent.com/8606735/99254175-39d95980-2812-11eb-947b-e76c7b7f8ef0.png)

**Comment by cedric-anne** [comment]
Hi,

Your source email contains an empty paragraph between each non empty paragraph. I guess they are not shown in your Outlook client, but they are in GLPI.

Source:
```xml
<p class="MsoNormal">Hello,<o:p></o:p></p>
<p class="MsoNormal"><o:p>&nbsp;</o:p></p>
<p class="MsoNormal"><span lang="EN-US">this is just a test mail.<o:p></o:p></span></p>
```

Result:
```xml
<p>Hello,</p>
<p>&nbsp;</p>
<p>this is just a test mail.</p>
```

So spacing in your screen capture is consistent with the source HTML code.

I consider this is not a bug, as GLPI cannot decide if an empty paragraph is has been added voluntarily by the writer or added by the mail client without the writer knowing.

Regards

**Comment by husisusi** [comment]
@cedric-anne Thanks, 
but sorry, I don't agree with you! If I open the eml with Thunderbird, Firefox or any HTML viewer, it will be displayed correctly.
And when I send the same eml email with Thunderbird I got the same issue.

**Comment by cedric-anne** [comment]
GLPI strips embed CSS, which contains `p.MsoNormal { margin-bottom:.0001pt; }`. Prevent removal of custom CSS could require lot of work, and could introduce side effects on GLPI styles, so not sure we want to do it.

@orthagh @trasher 

Regards

**Comment by trasher** [comment]
I agree with @cedric-anne; this sounds a very big work with uncertain results in many cases... To kind of fix what an email client did wrong?

**Comment by trasher** [comment]
> @cedric-anne Thanks,
> but sorry, I don't agree with you! If I open the eml with Thunderbird, Firefox or any HTML viewer, it will be displayed correctly.
> And when I send the same eml email with Thunderbird to GLPI, I got the same issue.

GLPI is not an email client, its goal is not to display HTML pages correctly. If you use the same EML file, you'll have for sure the same result.
Empty paragraphs are present in the source email, and therefore are imported; this sounds normal. CSS are not imported; but CSS is only for display. Note that several web email clients will not import all CSS rules like outlook or thunderbird.

**Comment by husisusi** [comment]
I understand, thank you!
