### ISSUE TITLE
Charts disappear when the page is refreshed

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#8284]
Hi.
Charts disappear when the page is refreshed.
Page: 
/front/dashboard_helpdesk.php
/front/dashboard_assets.php
/front/central.php 
[Youtube Video](https://youtu.be/X5F5TQ-6NdA)

GLPI 9.5.2 
FusionInventory 9.5.0+1.0
Google Chrome Версия 86.0.4240.198 (Официальная сборка), (64 бит)

Also, the charts disappear when you install them cleanly on the server, without any plugins.

Operating system: Linux support 5.4.0-52-generic #57~18.04.1-Ubuntu SMP Thu Oct 15 14:04:49 UTC 2020 x86_64 PHP 7.2.24-0ubuntu0.18.04.7 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, 	ldap, libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, pspell, readline, recode, session, shmop, 	sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at glpi.myserver.ru Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Server Software: Ubuntu 18.04 	Server Version: 10.1.47-MariaDB-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.1.47) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

**Comment by cedric-anne** [comment]
Hi,

It duplicates #8110 and has already been solved by #8151 and #8170.

Regards

**Comment by kofe88** [comment]
> Hi,
> 
> It duplicates #8110 and has already been solved by #8151 and #8170.
> 
> Regards

Sorry =)
Thank you!
