### ISSUE TITLE
Add CC users as observer / Send Individual email

### ISSUE THREAD

**Issue by acarbajo** [glpi-project/glpi#8296]
**Describe the bug**

When I resolve a ticket, the observers receive an email individually.

Not just a CC email is sent to observers

```

**Screenshots**

If applicable, add screenshots to help explain your problem.


![image](https://user-images.githubusercontent.com/74682296/99583330-53fd6e00-29b1-11eb-8385-c0bb88209472.png)


**Additional context**

Add any other context about the problem here.

**Comment by cedric-anne** [comment]
Hi,

Activate this option will make adresses in `cc` emails headers to be used to define created tickets observer. It has nothing to do with the way notifications are send.

Regards
