### ISSUE TITLE
File not found: rrule.js.map

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#8302]
**Describe the bug**

While using GLPI, Apache is occasionally logging the following to its error log:
[Thu Nov 19 12:00:57 2020] [error] [client 10.11.253.153] File does not exist: /usr/share/glpi/front/rrule.js.map

**Page(s) URL**

https://glpi.domain.local/front/central.php

**To reproduce**

1. Go to 'https://glpi.domain.local/front/central.php'.

**Expected behavior**

No idea what 'rrule.js.map' is, so what's supposed to be happening here is unknown

**Logs**

```
[Thu Nov 19 12:00:57 2020] [error] [client 10.11.253.153] File does not exist: /usr/share/glpi/front/rrule.js.map
[Thu Nov 19 12:04:53 2020] [error] [client 10.11.253.153] File does not exist: /usr/share/glpi/front/rrule.js.map
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.2 ( => /usr/share/glpi)
PHP 7.3.24

```

**Comment by tomolimo** [comment]
Hello

Same issue for me
GLPI 9.5.2
PHP 7.3.23

Thank you
Regards,
Tomolimo
