### ISSUE TITLE
Timestamps update

### ISSUE THREAD

**Issue by grego1981** [glpi-project/glpi#8309]
I try to update the timestamps as per documentation, after upgrading from 9.4 to 9.5, I have done the mysql part and when I run the command php bin/console glpi:migration:timestamps I get the following error:

PHP Deprecated:  Use sodiumDecrypt in /var/www/html/glpi/inc/toolbox.class.php on line 632
Found 189 table(s) requiring migration.
Do you want to continue ? [Yes/no]Uncaught Exception Error: Call to undefined method Symfony\Component\Console\Question\ConfirmationQuestion::getAutocompleterCallback() in /var/www/html/glpi/vendor/symfony/console/Helper/QuestionHelper.php at line 108

1. Go to 'server cli glpi apache root directory'
2. run php bin/console glpi:migration:timestamps
3. get the error above

**Expected behavior**

To update timestamps

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Information about system installation & configuration
--
Check if a New Version is Available
[code]   GLPI 9.5.2 (/glpi => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux itsrv-05-test 4.4.0-193-generic #224-Ubuntu SMP Tue Oct 6 17:15:28 UTC 2020 x86_64 PHP 7.2.34-8+ubuntu16.04.1+deb.sury.org+1 apache2handler (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apc, apcu, bcmath, bz2, calendar, ctype, curl, date, dba, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, 	hash, iconv, igbinary, imagick, imap, intl, json, ldap, libsmbclient, libxml, mbstring, memcache, mysqli, mysqlnd, odbc, 	openssl, pcre, pdo_mysql, posix, pspell, readline, recode, redis, session, shmop, smbclient, snmp, soap, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.18 (Ubuntu) (Apache/2.4.18 (Ubuntu) Server at 10.10.99.50 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 Server Software: (Ubuntu) 	Server Version: 5.7.32-0ubuntu0.16.04.1 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.32) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.2 GLPI_SCHEMA_VERSION: 9.5.2 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020 GLPI_MOD_DIR: /var/www/html/glpi/plugins/mod

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.5 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/plugins/flyvemdm/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/marketplace/metabase/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/marketplace/metabase/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.3 in (/usr/share/php)

accounts             Name: Accounts                       Version: 2.6.0      State: Enabled 	activity             Name: Activities                     Version: 3.0.0      State: Enabled 	fields               Name: Additional Fields              Version: 1.12.0     State: Enabled 	news                 Name: Alerts                         Version: 1.8.0      State: Enabled 	appliances           Name: Appliances                     Version: 3.1.0      State: Enabled 	archisw              Name: Apps structures                Version: 2.2.1      State: Error / to clean 	impacts              Name: Asset impacts                  Version: 1.3.7      State: Installed / not activated 	barcode              Name: Barcode                        Version: 2.5.0      State: Enabled 	behaviors            Name: Behaviours                     Version: 2.4.1      State: Enabled 	bettermailimporter   Name: Better Mail Importer           Version: 1.0.1      State: Enabled 	browsernotification  Name: Browser Notification           Version: 1.1.9      State: Enabled 	positions            Name: Cartography                    Version: 4.6.0      State: Enabled 	connections          Name: Connections                    Version: 9.5        State: Enabled 	consumables          Name: Consumable request             Version: 1.6.0      State: Enabled 	credit               Name: Credit vouchers                Version: 1.8.0      State: Enabled 	dashboard            Name: Dashboard                      Version: 0.9.8      State: Enabled 	datainjection        Name: Data injection                 Version: 2.8.1      State: Enabled 	databases            Name: Databases                      Version: 2.3.0      State: Enabled 	dataflows            Name: Dataflows                      Version: 2.2.2      State: Installed / not activated 	archimap             Name: Diagrams                       Version: 2.2.1      State: Enabled 	domains              Name: Domains                        Version: 2.2.1      State: Enabled 	manageentities       Name: Entities portal                Version: 3.2.0      State: Enabled 	father               Name: Father&Sons                    Version: 1.2.0      State: Enabled 	financialreports     Name: Financial reports              Version: 2.6.0      State: Enabled 	flyvemdm             Name: Flyve Mobile Device Management Version: 2.0.0-rc.3 State: Enabled 	formcreator          Name: Form Creator                   Version: 2.10.4     State: Enabled 	formvalidation       Name: Form Validation                Version: 0.6.8      State: Enabled 	archifun             Name: Functional Areas               Version: 2.2.2      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	gdrive               Name: GDrive                         Version: 1.3.0      State: Enabled 	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled 	openvas              Name: GLPi openvas Connector         Version: 1.2.0      State: Enabled 	groupcategory        Name: GroupCategory                  Version: 1.2        State: Enabled 	resources            Name: Human Resources                Version: 2.7.0      State: Enabled 	geninventorynumber   Name: Inventory number generation    Version: 2.5.0      State: Enabled 	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled 	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.7.0      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 1.6.0      State: Enabled 	metabase             Name: metabase                       Version: 1.2.1      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.7.0      State: Enabled 	satisfaction         Name: More satisfaction              Version: 1.5.0      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.8.0      State: Enabled 	nebackup             Name: nebackup                       Version: 2.2.2      State: Enabled 	archires             Name: Network Architectures          Version: 2.7.0      State: Enabled 	notifications        Name: Notifications                  Version: 9.4+1.0    State: Enabled 	genericobject        Name: Objects management             Version: 2.9.1      State: Enabled 	orderservice         Name: Ordem de Serviço               Version: 2.0.0      State: Enabled 	order                Name: Orders management              Version: 2.6.0      State: Enabled 	additionalalerts     Name: Others alerts                  Version: 2.2.0      State: Enabled 	pdf                  Name: Print to pdf                   Version: 1.7.0      State: Enabled 	printercounters      Name: Printer counters               Version: 1.7.0      State: Enabled 	processmaker         Name: Process Maker                  Version: 3.6.16     State: Enabled 	protocolsmanager     Name: Protocols manager              Version: 1.2        State: Enabled 	reports              Name: Reports                        Version: 1.14.0     State: Enabled 	reservation          Name: Reservation                    Version: 2.2.0      State: Enabled 	seasonality          Name: Seasonalities                  Version: 1.5.0      State: Enabled 	shellcommands        Name: Shell Commands                 Version: 3.0.0      State: Enabled 	showconns            Name: Show connected items           Version: 0.2        State: Enabled 	showloading          Name: Show Loading                   Version: 1.0.0      State: Enabled 	manufacturersimports Name: Suppliers imports              Version: 2.3.0      State: Enabled 	tag                  Name: Tag Management                 Version: 2.8.0      State: Enabled 	tasklist             Name: Task list generator            Version: 1.0.5      State: Enabled 	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled 	tasklists            Name: Tasks list                     Version: 1.6.0      State: Enabled 	ticketcleaner        Name: Ticket Cleaner                 Version: 2.5.1      State: Enabled 	timelineticket       Name: Timeline of tickets            Version: 9.4+1.0    State: Enabled 	timesheet            Name: Timesheet for GLPI             Version: 1.0.0      State: Enabled 	typology             Name: Typologies                     Version: 3.0.0      State: Enabled 	useditemsexport      Name: Used items export              Version: 2.4.0      State: Enabled 	webapplications      Name: Web applications               Version: 3.0.0      State: Enabled 	webnotifications     Name: Web Notifications              Version: 1.1.3      State: Installed / not activated 	webservices          Name: Web Services                   Version: 2.0.0      State: Installed / not activated
[/code]

**Comment by cedric-anne** [comment]
Hi,

Can you try to use the `--no-plugins` options when running the command ? One of your plugins may embed an old version of the `symfony/console` component that may conflicts with the one required by GLPI.

Regards

**Comment by grego1981** [comment]
It seems to work nowm athough it seems to run slowly or not at all, it is at 0% for a few minutes now..

**Comment by grego1981** [comment]
The command finished successfully! Thank you for your help! I think it would be very helpful for other users to add this tip to the documentation.

**Comment by cedric-anne** [comment]
We cannot predict what plugins are for. It may happen that an active plugin has a legitimate action to do during a command execution, so in this case, running command with no plugins may be harmfull. I guess user will find this page in their preferred search engine if they encounter the same error.

I close this issue as it a plugin issue. If you find which plugin is responsible of this, do not hesitate to open an issue on its own repository.
