### ISSUE TITLE
Confirmation pop-up when adding a new follow-up message

### ISSUE THREAD

**Issue by ricostone** [glpi-project/glpi#8313]
**Describe the bug**

When adding a new follow up comment, the page ask to confirm leaving the page.

**To Reproduce**

1. Go to a ticket
2. Add a follow-up with some text
4. Click the "Add" button
4. A pop-up appears stating that we are leaving the page (content depend of the browser)
5. Confirm "leaving the page" to save correctly.

**Expected behavior**

We expect that we don't have any pop-up asking for confirming leaving the page when submitting the new message correctly using the submit button.

**Screenshots**

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/1039656/99969281-85ec4700-2d9a-11eb-8a8f-af43fc62efa4.png)

**Setup**
 - OS:  Windows 10 pro
 - Browser : Firefox 78.5 , Edge 87.0
 - GLPI Version : 9.5.1

**Additional context**

I clearly think it's related to the beforeunload event : https://github.com/glpi-project/glpi/blob/31dccae2249b9504d94e5466b12ed9faf4f7b7c5/js/common.js#L1155

I think the global variable window.glpiUnsavedFormChanges should be set to false when submitting the new message using the submit button.

Maybe related ? https://github.com/glpi-project/glpi/pull/7986

**Comment by cconard96** [comment]
The linked PR should have already fixed this issue and has been part of 9.5.2 for a while. I suggest updating and testing that the issue was resolved.

**Comment by ricostone** [comment]
GLPI updated to 9.5.2 , confirmed problem solved. Thank you !

**Comment by cconard96** [comment]
You're welcome
