### ISSUE TITLE
[0.90.4] Regression on "Documents" tab

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#832]
Hello,

Since the update to 0.90.4 from 0.90.3, there is no "Documents" tab on tickets. 

In relation to #828 ?

**Comment by orthagh** [comment]
No relative to #493.

You should enable the option "Keeps tabs replaced by the ticket timeline" in your preferences

**Comment by nqb** [comment]
Ok sorry @orthagh.

**Comment by orthagh** [comment]
No need for excuses.
