### ISSUE TITLE
[0.90.4] ID of problems

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#834]
Hello,

Since the update to 0.90.4, there is no ID displayed next to "Problem" in Assistance -> Problems : 

0.90.1 
![problem_0 90 1](https://cloud.githubusercontent.com/assets/10830260/17143598/1c82a270-5354-11e6-9099-c2854fbb8b90.png)

0.90.4
![problem_0 90 4](https://cloud.githubusercontent.com/assets/10830260/17143604/21071bdc-5354-11e6-986e-e5b8a0bd2d14.png)

**Comment by orthagh** [comment]
See #650 for this change.
Not only problem objects are affected.
And i'm not sure i can qualify this issue as a bug.
