### ISSUE TITLE
[9.5.3] Bug with import mail collector

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#8340]
There is a problem with https://github.com/glpi-project/glpi/pull/8256/files#diff-9494cb651c6f01aceaf8fed5b361ad70a20120fcfbf9717a9d93be465b9c8050

After this change, the mails are not matching rule (with user group criteria & are rejected) or match another rule

**Comment by tsmr** [comment]
I confirm I undo change into rulemailcollector.class.php & rulemailcollectorcollection.class.php and now all mails are imported into GLPI

**Comment by cedric-anne** [comment]
Hi,

Can you check your logs, to see if there is an error, and can you also provide a reproductible case (with rules exports for instance) ?

Regards

**Comment by tsmr** [comment]
No log
For test create a rule with these criteria 👍 

![image](https://user-images.githubusercontent.com/13178158/100615083-5d72c880-3317-11eb-89c3-5c21cdab1334.png)

The email don't match rule & then do this : 

https://github.com/glpi-project/glpi/issues/8297#issuecomment-735683527

**Comment by ppenin** [comment]
Same issue for me : no more tickets are imported in GLPI.
Rollback to 9.5.2

**Comment by prohand** [comment]
Hello, do you have a solution for this problem ?
I have a same problem.
Thank you

**Comment by mgallais76** [comment]
Hello,

I have the same issue, did you find a fix?

Regards

**Comment by prohand** [comment]
> Hello,
> 
> I have the same issue, did you find a fix?
> 
> Regards

Hello, 

no fix at this time :(

**Comment by cedric-anne** [comment]
Hi @tsmr @ppenin @prohand @mgallais76 ,

#8677 should solve your issue.

Could you test it ?

Regards

**Comment by prohand** [comment]
Hello,

My instance is in a production mode.
I can't test.

I will see when the next version is released

Thank you

**Comment by prohand** [comment]
Hello,

Where do I have to place the RuleMailcollector.php file?

Thank you

**Comment by prohand** [comment]
Finally i have place the file in inc folder.
I have test and it's OK.
Thank you
