### ISSUE TITLE
[glpi 9.5.2] TCPDF ERROR:

### ISSUE THREAD

**Issue by FelipeLaras** [glpi-project/glpi#8342]
TCPDF ERROR: [Image] Unable to get the size of the image: http://10.100.1.217/glpi/front/document.send.php?docid=46971&tickets_id=96074

please can you help me with this question.

**Comment by cedric-anne** [comment]
Hi,

Please at least provide steps to reproduce, logs, and GLPI system informations.

Regards

**Comment by FelipeLaras** [comment]
ok, in the next I will pay attention, sorry lol ..

I tried to reproduce the error and not revealed anymore, I will close a problem ... Thanks
