### ISSUE TITLE
[0.90.4] Associated elements hidden when status is closed

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#835]
Hello,

Since the update to 0.90.4, when you closed a ticket, associated elements are hidden on "Ticket" tab : 

![associated_elements_hidden](https://cloud.githubusercontent.com/assets/10830260/17143798/db8aab04-5354-11e6-86b9-5010287ef5e8.png)

However, you can see associated elements on "Elements" tab.

**Comment by tyronewyatt** [comment]
Can confirm http://forum.glpi-project.org/viewtopic.php?id=154936

**Comment by orthagh** [comment]
relative to #596, rights change to access associated elements from this part
