### ISSUE TITLE
[0.90.4] Can't save anywhere bookmarks 

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#836]
Try to save a bookmark at http://demo.glpi-project.org/front/ticket.php#.
It do not work with 0.90.4.
I try it after i read http://forum.glpi-project.org/viewtopic.php?id=154931

I got the message "Security die. trying to load an forbidden class name"

#

**Comment by orthagh** [comment]
Hello @Armin83 

Thank you for the report.
I plan to release a new 0.90.5 today, because we have a fex regression in 0.90.4 version

**Comment by Armin83** [comment]
Do not work in Demo 0.90.5.

**Comment by Armin83** [comment]
If i open book marks with star button i got also the message "Security die. trying to load an forbidden class name"

**Comment by kamiben** [comment]
Same issue with 0.90.5 on our systems. 
There is also the message when loading bookmarks.

**Comment by orthagh** [comment]
Could you check in your glpi_bookmarks table if there is some line with itemtype=0 ?
And clean them if exists.
