### ISSUE TITLE
Software associate to Virtual machine

### ISSUE THREAD

**Issue by olegbatalov** [glpi-project/glpi#837]
Dear GLPi developers

Long ago there is an opportunity to associate the software and its licenses for the physical computer.
But, in certain cases, the software is set in the virtual machine of the physical server. Which in turn may contain several virtual machines.
You couldn't  an opportunity, bind the software and its licenses with the virtual machines

**Comment by wawax** [comment]
Hello,

Why not to install an inventory agent in the virtualmachine ? 
If you want to inventory vm by hand, create a new computer, and put the same UUID for them vm as declared on the vm and in the newly created computer.

By doing so, you can associate a software or a license to a vm.

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
