### ISSUE TITLE
[9.5] Can't any longer attach documents when posting a solution...

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#8372]
Hello,

**Describe the bug**
Can't attach documents to a ticket solution... That was possible in previous GLPI releases

**To reproduce**
1. Go to a ticket
2. Click on "Solution" to add a solution to this ticket
3. See that it's not possible to add a PDF document (for example) to this solution

**Expected behavior**
It was possible to attach any type of document to a solution. This is expected to be a "normal" feature like it was in the past.

**Logs**
There is no log

**Screenshots**

Curent situation:
![image](https://user-images.githubusercontent.com/7569958/100987463-d740c700-354e-11eb-8b0f-fce10b375a6c.png)

As it should be:
![image](https://user-images.githubusercontent.com/7569958/100987557-f5a6c280-354e-11eb-95eb-888c8d58b28c.png)

Thank you very much,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Seems linked to https://github.com/glpi-project/glpi/commit/bafcb1b1d4022f0a2a11b89a9ff7edf44a9c0c19

**Comment by andrepetinga** [comment]
In my case, I never had that option! It was an expected option, but we don't have it in our installation...
Our trick was to upload a document and then post a solution, and the document is sent with the solution...

**Comment by tomolimo** [comment]
Hello @andrepetinga 
This was possible in GLPI 9.2:
![image](https://user-images.githubusercontent.com/7569958/114989124-68c62b00-9e97-11eb-993c-7d1f7ecb5220.png)
Thank you
Regards,
Tomolimo
