### ISSUE TITLE
[9.5.3] issue with Mailgate, Laminas mail expects a value in the format "type/subtype"; received "image/*"

### ISSUE THREAD

**Issue by dlepenven** [glpi-project/glpi#8375]
Hi,

I am using a GLPI v 9.5.3 with collectors configured in **POP SSL**.

Collectors are working but for some message, for some reason, it fails with this message in the log :

- Erreur lors de l'analyse du message : Laminas\Mail\Header\ContentType::setType expects a value in the format "type/subtype"; received "image/*"<br/>

I try to change the regex in the function setType of laminas librarie but then I received this message : 

- Message invalide : Laminas\Mail\Header\ContentType::setType expects a value in the format "type/subtype"; received "multipart/mixed"<br/>

**Comment by lfardin** [comment]
To fix this issue, you should change the RegEx at this file "vendor/laminas/laminas-mail/src/Header/ContentType.php", line 114
from 
 _if (! preg_match('/^[a-z-]+\/[a-z0-9.+-]+$/i', $type)) {_
to 
 _if (! preg_match('/^[a-z-]+\/[*a-z0-9.+-]+$/i', $type)) {_

**Comment by dlepenven** [comment]
Hi,

As I say, I already tried to just edit the regex, but it trigger another error.

**Comment by lfardin** [comment]
The RegEX you used was this one, including and "*" befora the second "a"?

/^[a-z-]+/[*a-z0-9.+-]+$/i

We are using version 9.5.3 and I just did this fix, and messages with "image/*" are being processed correctly now, with no errors.

**Comment by trasher** [comment]
Hum... The `*` character will allow any character; maybe better to use `\*`

**Comment by dlepenven** [comment]
I will retry both * and \* to be sure, it was 2 weeks ago, I don't remerber which one I used.

**Comment by trasher** [comment]
Both should have fixed the issue. 

Since the fix cannot be implemented on GLPI side, please consider opening an issue (or a pull request) on laminas-mail component. I'm not able to say if the proposed fix is "correct".

**Comment by trasher** [comment]
Please also note the issue should be on GLPI side, if for example we try to get information on something we should'nt; but I do not think we are in that case.

**Comment by dlepenven** [comment]
Thanks for the feedback. I will test it and make the feedback here

**Comment by tomolimo** [comment]
Hello,
I also came to this issue with an email sent from a smartphone...
And the issue has been fixed using the following regex: `/^[a-z-]+\/[\*a-z0-9.+-]+$/i`
This has not been fixed in the laminas-mail used in GLPI 10.0.15
Thank you,
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
@tomolimo 
Could you please attache an example of message in eml format, so we could try to fix this issue ?

**Comment by tomolimo** [comment]
Hello @cedric-anne 
I cannot send it to github (too much private info) but I'm going to send it to the Teclib support site.
Thank you,
Regards,
Tomolimo
