### ISSUE TITLE
Locked fields in Computer

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#8378]
Hello,

how can i unlock locked fields?

For Example:
![grafik](https://user-images.githubusercontent.com/25504254/101052066-79c86c80-3586-11eb-8f20-7055fdabc3d7.png)

I tried Action - > locked (fields), but there is no possibility for input something:
![grafik](https://user-images.githubusercontent.com/25504254/101052285-bb591780-3586-11eb-8cc6-a73ee13c45af.png)

I'm using GLPI 9.5.1.

**Comment by trasher** [comment]
Since you did not provide requested information; it's hard to be sure, but this seems to be from fusioninventory plugin.

**Comment by vollkommenIrrelevant** [comment]
> 
> 
> Since you did not provide requested information; it's hard to be sure, but this seems to be from fusioninventory plugin.

You can never be shure 👎 
If it is a bug - you can get the information. Do you think it is a bug or do you think it is a setting of fuseninventory plugin?

**Comment by vollkommenIrrelevant** [comment]
bump

**Comment by trasher** [comment]
What in "you did not provide requested information" did not you understand?

**Comment by vollkommenIrrelevant** [comment]
> 
> 
> What in "you did not provide requested information" did not you understand?

What in 

> 
> 
> > Since you did not provide requested information; it's hard to be sure, but this seems to be from fusioninventory plugin.
> 
> You can never be shure 👎
> If it is a bug - you can get the information. Do you think it is a bug or do you think it is a setting of fuseninventory plugin?

did not you understand?

**Comment by trasher** [comment]
OK, see https://github.com/glpi-project/glpi/blob/9.5/bugfixes/.github/ISSUE_TEMPLATE/bug_report.md: requested information are not provided.
