### ISSUE TITLE
No notification on followup

### ISSUE THREAD

**Issue by Edzilla2000** [glpi-project/glpi#8382]
We have an issue with some users, where GLPI does not send any email on followups, even though a notification is configured.
The issue only happens with some users, others with the same profile correctly receive the emails.
The issue is not with the mail gateway: emails do not appear in GLPI mail queue.

We have two "new followup" notification rules, depending on the profile they send different emails.
The problem started on upgrade to 9.5.
It seemed to disappear when we upgraded to 9.5.2, but now two users have the problem again.

**Comment by Eon9D** [comment]
Check if the user is active in GLPI

**Comment by Edzilla2000** [comment]
Hello, 
Yes, the user is active in GLPI.
Here is an example of someone who has the issue:
https://i.imgur.com/ffx03f1.png

**Comment by Edzilla2000** [comment]
Is there any information I can give that would help? This issue is very problematic for us

**Comment by martin-crockett** [comment]
i have the same problem, we have a working glpi 9.4.6 and before updating we wanted to test the new version so i installed the 9.5.5 on an other domain and setup everything like the 9.4.6 and only the validation notification works, no notification for follow up or task or event on ticket creation

**Comment by Edzilla2000** [comment]
Are there any log that I can give or anything that might help get this issue resolved? This is a huge problem for us!

**Comment by Edzilla2000** [comment]
I have some more information I can add to this ticket: 
It seems that for some reason GLPI tries to send notifications not the the user's email but to its user_id:
![image](https://user-images.githubusercontent.com/5339038/119795498-d1fa7e80-bed8-11eb-9861-8220a2af4c74.png)
![image](https://user-images.githubusercontent.com/5339038/119797010-27835b00-beda-11eb-8734-c4b898c30eed.png)

This the user in question (770):
![image](https://user-images.githubusercontent.com/5339038/119795755-0e2ddf00-bed9-11eb-9a32-95c9f9ded063.png)

As you can see it's correctly configured I believe. At least it's worked fine for 10 years, and the same configuration for other users works fine.

**Comment by Eon9D** [comment]
IDs are nothing uncommon. These are for browser push notifications. 
Screenshots are IMHO useless if they are not in english - I am not able to understand them.
Add "notification template" in the notification queue and repost the screenshots.

**Comment by Eon9D** [comment]
"LDP - New Followup" is not the default template. Maybe the user changed the language and you don't have a template?

Screenshot of user language please and template languages.

**Comment by Edzilla2000** [comment]
Thanks for the reply!

Here is the screenshot in english, with the added column:
![image](https://user-images.githubusercontent.com/5339038/119798682-a7f68b80-bedb-11eb-829c-8f2ed5c021c3.png)

You're right actually, it might be a browser notification, I added it to the template when I realized people where not receiving emails.

Here is the user language: 
![image](https://user-images.githubusercontent.com/5339038/119799019-fd329d00-bedb-11eb-9952-376affe44cd4.png)

And here is the template:
![image](https://user-images.githubusercontent.com/5339038/119799147-19363e80-bedc-11eb-964a-1afa5a893140.png)

**Comment by Eon9D** [comment]
For testing - maybe on the wrong track but I am currently limited in time for testing myself:
I see GLPi does have "Fracais",  "Fracais (Canada)", "Fracais(Belgique)"

Can you change the language of the user to  "Fracais" instead of "Fracais(Belgique)"

**Comment by Edzilla2000** [comment]
YES! That's it, the user now receives emails.

I think I understand what happened: the problem came from the fact that the default GLPI template "Tickets Followup" did not have a default translation, only french and english. This probably comes from the fact that our GLPI installation is more than 10 years old and some stuff was never implemented again if it did not exist back then.

We use two notification templates, depending on the profile of the user. The notification from our custom template always worked as it has a default translation, but when some users selected another language than french or english, they stopped receiving notification from the default language.
I have added a default translation to the default template and it seems to work again.

Thank you a LOT for your help!

**Comment by Eon9D** [comment]
Happy to hear that! Can you please mark this post as solved. Thank you.
