### ISSUE TITLE
[9.5]Users Associated tickets

### ISSUE THREAD

**Issue by rollandpf** [glpi-project/glpi#8389]
Hello,

I don't realy Know if this is a bug or a non implemented function but I have the folowing issue.

In the Administration -> Users section, at the end of the listing table we have the Number of tickets as requester. 

![image](https://user-images.githubusercontent.com/48216797/101379134-3a668c80-38b4-11eb-89b4-8144163dfbb2.png)

When I click of the number on tickets, I was especting, like with the computers, to go to the Assistance -> Tickets section with a filter isolating the tickets linked to the User (julie.reig for example). Like below.

![image](https://user-images.githubusercontent.com/48216797/101379423-89acbd00-38b4-11eb-87a4-3ffbdf26cacb.png)

But instead, We hane a reset filter command (http://.../glpi/front/ticket.php?reset=reset).

Regards,
Pierre-François ROLLAND

GLPI 9.5.3 (Installation mode: TARBALL)
Debian 10.3.25
Apache 2.4.38
PHP 7.9.19-1
MariaDB 10.3.25

**Comment by cconard96** [comment]
It is a bug in the search engine.
In the `Search::giveItem` method, the parameter `$ID` is supposed to be an integer corresponding to the search option (60 in this case). Later in the function it gets assigned as a string based on the itemtype, `User_60` in this instance.

I've found the following workaround, but I don't know what else is broken, or what else this patch affects.
```diff
diff --git a/inc/search.class.php b/inc/search.class.php
index 4de9afed1c..661db82141 100644
--- a/inc/search.class.php
+++ b/inc/search.class.php
@@ -5766,7 +5766,7 @@ JAVASCRIPT;
 
                      if ($itemtype == 'User') {
                         // Requester
-                        if ($ID == 60) {
+                        if ($ID == 'User_60') {
                            $options['criteria'][0]['field']      = 4;
                            $options['criteria'][0]['searchtype']= 'equals';
                            $options['criteria'][0]['value']      = $data['id'];
@@ -5774,14 +5774,14 @@ JAVASCRIPT;
                         }
 
                         // Writer
-                        if ($ID == 61) {
+                        if ($ID == 'User_61') {
                            $options['criteria'][0]['field']      = 22;
                            $options['criteria'][0]['searchtype']= 'equals';
                            $options['criteria'][0]['value']      = $data['id'];
                            $options['criteria'][0]['link']       = 'AND';
                         }
                         // Assign
-                        if ($ID == 64) {
+                        if ($ID == 'User_64') {
                            $options['criteria'][0]['field']      = 5;
                            $options['criteria'][0]['searchtype']= 'equals';
                            $options['criteria'][0]['value']      = $data['id'];
```
