### ISSUE TITLE
Unable to add user using a child entity member with admin privileges

### ISSUE THREAD

**Issue by PCcunha** [glpi-project/glpi#839]
Adding users as a child entity shows a blank form, nomatter what permissions i give to the user (i've added all permissions possible in both parent (with recursive) and on child)

Steps to reproduce:
- Add a child entity.
- Give super admin permission for a user os parent entity to that entity you created.
- Log-in as that user
- Switch the active entity to the child entity you created
- goto administration->users and try to create a user. This shoud open a blank page.

http://forum.glpi-project.org/viewtopic.php?pid=322594#p322594

Thank you!

GLPI 0.90.1 (/glpi => /var/www/glpi)

Server
Operating system: Linux lepus 4.2.0-16-generic #19-Ubuntu SMP Thu Oct 8 15:35:06 UTC 2015 x86_64
PHP 5.6.11-1ubuntu3.4 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
    calendar, ctype, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
    mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
    sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
    upload_max_filesize="2M" 
Software: Apache/2.4.12 (Ubuntu) (Apache/2.4.12 (Ubuntu) Server at lepus Port 80)
    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Server Software: (Ubuntu)
    Server Version: 5.6.31-0ubuntu0.15.10.1
    Server SQL Mode: NO_ENGINE_SUBSTITUTION
    Parameters: root@localhost/glpi
    Host info: Localhost via UNIX socket

OK/var/www/glpi/config : OK
OK/var/www/glpi/files : OK
OK/var/www/glpi/files/_dumps : OK
OK/var/www/glpi/files/_sessions : OK
OK/var/www/glpi/files/_cron : OK
OK/var/www/glpi/files/_graphs : OK
OK/var/www/glpi/files/_lock : OK
OK/var/www/glpi/files/_plugins : OK
OK/var/www/glpi/files/_tmp : OK
OK/var/www/glpi/files/_rss : OK
OK/var/www/glpi/files/_uploads : OK
OK/var/www/glpi/files/_pictures : OK
OK/var/www/glpi/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.

Libraries

htmLawed version 1.1.20 in (/var/www/glpi/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/glpi/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/glpi/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/glpi/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/glpi/lib/Zend)
SimplePie version 1.3.1 in (/var/www/glpi/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/glpi/lib/tcpdf)
ircmaxell/password-compat in (/var/www/glpi/lib/password_compat). Compatitility: Ok

LDAP directories

Server: '192.168.7.1', Port: '389', BaseDN: 'dc=iorj,dc=gov', Connection filter:
        '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'iorj\administrador',
        Use TLS: none

Mysql replicas
Not active
Notifications
 Way of sending emails: SMTP (anonymous@192.168.11.10)
Mails receivers
 Plugins list
 Mysql replicas
 oNt active
Notifications
 Way of sending emails: SMTP (anonymous@192.168.11.10)
Mails receivers
 Pluins list
 [/code]

**Comment by cedric-anne** [comment]
Hi,

Cannot reproduce on 9.4. I guess this has been fixed.

Regards
