### ISSUE TITLE
[9.4?][9.5] GLPI not handling PHPmailer opportunistic TLS feature. 

### ISSUE THREAD

**Issue by finalbeta** [glpi-project/glpi#8390]
After upgrading to GLPI 9.5 from GLPI 9.3 I found SMTP notifications broken in GLPI.

GLPI Allows you to select if you want to use SMTP, SMTP+SSL or SMTP+TLS to send Email, my environment needs SMTP (no encryption). 

However, PHPMailer now uses opportunistic TLS if it detects that the server handles it. Meaning, if the server shows 250-STARTTLS in the banner, PHPMailer with still try to use encryption. Even though the parameters in GLPI claim it wont. In some cases PHPMailer will fail setting up TLS encryption and we have no way to disable it in GLPI.

Quote: 
`PHPMailer 5.2.10 introduced opportunistic TLS - if it sees that the server is advertising TLS encryption (after you have connected to the server), it enables encryption automatically, even if you have not set SMTPSecure. This might cause issues if the server is advertising TLS with an invalid certificate, but you can turn it off with $mail->SMTPAutoTLS = false;."`

As the server is a local relay server in my network I was unable to change certificates or fix the issue. I currently changed the " public function startTLS()" in _GLPIROOT_/vendor/phpmailer/phpmailer/src/SMTP.php and added a return true; as the first line. 
This fixes my installation. (I'm open to better suggestions). 

I do however think/suggest that GLPI should manages this change in behavior of PHPMailer by allowing control of the SMTPAutoTLS feature, or by disabling it by default on the "SMTP" option to replicate previous behavior. 

Debug log was posted on https://forum.glpi-project.org/viewtopic.php?pid=481720#p481720
TCPDump can be provided if required.

**Comment by trasher** [comment]
Please try if #8391 tix your issue

**Comment by finalbeta** [comment]
Thank you, I confirm that the changes in glpimailer.class.php fix this for me. (I've tested the change)

**Comment by trasher** [comment]
Thanks for the quick feedback :)
