### ISSUE TITLE
GLPI 9.5.2 email recipient configuration error

### ISSUE THREAD

**Issue by rodrigoalves1901** [glpi-project/glpi#8396]
Hello, I have a problem registering an email to open a ticket via email.
When registering an email the following message appears below and in the log this other message appears. How to fix?

![image](https://user-images.githubusercontent.com/43248152/101498611-ad1e4900-3942-11eb-81ed-556bb377cc8f.png)

log message:

glpiphplog.WARNING: *** PHP Warning (2): error_log(/var/www/html/centraldeservicos/files/_log/mailgate.log): failed to open stream: Permission denied in /var/www/html/centraldeservicos/inc/toolbox.class.php at line 656
Backtrace :
inc/toolbox.class.php:656 error_log()
inc/mailcollector.class.php:727 Toolbox::logInFile()
front/mailcollector.form.php:77 MailCollector->collect()

**Comment by trasher** [comment]
" failed to open stream": I guess that message is clear. you have to fix that, and then check the log for your error.
