### ISSUE TITLE
console reports based_config.php borked

### ISSUE THREAD

**Issue by Ressy66** [glpi-project/glpi#8398]
trying to update glpi to 9.5.3 using bin/console
it wont run

glpi/bin# ./console 

Parse error: syntax error, unexpected '(' in /opt/web/glpi/inc/based_config.php on line 152
} ) ( ) ;  is line 152

**Comment by cedric-anne** [comment]
Hi,

GLPI 9.5 requires, at least, PHP 7.2.

Next time you open an issue, please provide requested informations (system configuration at least).

Regards

**Comment by Ressy66** [comment]
+-----------------------+-------------+--------+
|                       | Current     | Target |
+-----------------------+-------------+--------+
| Database host         | 10.10.0.254 |        |
| Database name         | glpi        |        |
| Database user         | glpi        |        |
| GLPI version          | 0.83.91     | 9.5.3  |
| GLPI database version | 0.83.91     | 9.5.3  |
+-----------------------+-------------+--------+
Do you want to continue ? [Yes/no]yes
========================================== Update to 0.84 ==========================================
Migration::renameTable() in /var/www/glpi/inc/migration.class.php line 633
Unable to rename table glpi_ocsadmininfoslinks (ok) to ocs_glpi_ocsadmininfoslinks (nok)! 

maria 10.5
php 7.4.13
apache 2.4.46

**Comment by cedric-anne** [comment]
> Unable to rename table glpi_ocsadmininfoslinks (ok) to ocs_glpi_ocsadmininfoslinks (nok)!

It means that the table `glpi_ocsadmininfoslinks` could not be renamed to `ocs_glpi_ocsadmininfoslinks` as this last one already exists. This table is now managed by `ocsinventoryng`, and maybe you have install a version of this plugin that creates these tables. We have no idea how to bypass this problem.

You should ask for community support on [forums](https://forum.glpi-project.org/).

Regards

**Comment by Ressy66** [comment]
weird there is no ocs_ anything in the database   all tables are glip_

ocs_glpi_ocsadmininfoslinks does not already exist, so perhaps this is a bug?

is this ocs a plugin? so it can be deleted?

**Comment by Ressy66** [comment]
Ahh actually it does exist, so if it exists  it isa bug in your upgrader it should see it exists and do nothing or something special with it.
well anyway it looks like we have lost the  whole site, wont update itself and we cant run the old version on this new machine.
time to migrate to some other software that wont act this way.

**Comment by cedric-anne** [comment]
> Ahh actually it does exist, so if it exists it isa bug in your upgrader it should see it exists and do nothing or something special with it.
1. Restore your DB backup.
2. Run the migration again and it should work.

Most of the time, when the table exists, it means that someone restored a backup of an older version on a database already migrated, which result in a completely mixed-up database. Upgrader tool cannot handle all possible wrong manipulations of database.

**Comment by Ressy66** [comment]
Fatal error: Cannot make static method CommonGLPI::canCreate() non static in class Bookmark in /var/www/glpi/inc/bookmark.class.php on line 47

ok so it seemed to upgrade to 0.84, then in trying to get to 0.84.1 it bailed with above..

I guess it is just not possible to upgrade from such old versions

**Comment by cedric-anne** [comment]
> Fatal error: Cannot make static method CommonGLPI::canCreate() non static in class Bookmark in /var/www/glpi/inc/bookmark.class.php on line 47

This file should not even exist in version 9.5.3.

**Comment by Ressy66** [comment]
so upgrade is not touching old stuff... tell me this, would this work...
wipe out entire html directory (it was just over wrote as instructions) , install 9.5.3, then try teh db:update?

**Comment by Ressy66** [comment]
I will try in morning anyway, nothing to lose, I have to leave now

**Comment by Ressy66** [comment]
========================================= Update to 0.84.3 =========================================
========================================= Update to 0.84.4 =========================================
========================================= Update to 0.84.6 =========================================
========================================== Update to 0.85 ==========================================
========================================= Update to 0.85.3 =========================================
========================================= Update to 0.85.5 =========================================
========================================== Update to 0.90 ==========================================
========================================= Update to 0.90.1 =========================================
========================================= Update to 0.90.5 =========================================
========================================== Update to 9.1 ===========================================
========================================= Update to 9.1.1 ==========================================
========================================= Update to 9.1.3 ==========================================
========================================== Update to 9.2 ===========================================
========================================= Update to 9.2.1 ==========================================
========================================= Update to 9.2.2 ==========================================
========================================= Update to 9.2.2 ==========================================
========================================= Update to 9.2.3 ==========================================
========================================== Update to 9.3 ===========================================
========================================= Update to 9.3.1 ==========================================
========================================= Update to 9.3.2 ==========================================
========================================= Update to 9.4.0 ==========================================
========================================= Update to 9.4.1 ==========================================
========================================= Update to 9.4.2 ==========================================
========================================= Update to 9.4.3 ==========================================
========================================= Update to 9.4.5 ==========================================
========================================= Update to 9.4.6 ==========================================
========================================= Update to 9.4.7 ==========================================
========================================= Update to 9.5.0 ==========================================
============================= Rename "AuthLdap" itemtype to "AuthLDAP" =============================
============================= Rename "Crontask" itemtype to "CronTask" =============================
============================== Rename "InfoCom" itemtype to "Infocom" ==============================
========================================= Update to 9.5.2 ==========================================
======================= Building inline images data in glpi_documents_items ========================
========================================= Update to 9.5.3 ==========================================
Migration done.


wow very impressed by new look compared to the old one, my congratulations on hard work over the years.

As you can see, the only way this migration worked was to wipe out the entire html directory excluding config dir, then the migration worked :) I've clicked  into a handful of options and all work and can update and save ok.

So when upgrading from very old versions we can not just extract over the top,  not from versions several years old anyway.

Thanks, your clue about that other file should not exist made me think to try another approach, maybe add to your FAQ what to do if so old?
anyway I'm happy thanks you can close this off now.
