### ISSUE TITLE
Installation process - detect MySQL and PHP packages compatibility

### ISSUE THREAD

**Issue by mohierf** [glpi-project/glpi#840]
During a fresh installation on a recent Ubuntu 16.04 server I encountered the following problems : 
 - mysql 5.7 is not currently supported whereas it is the default and recommended version ... the installation process should, at minimum, check this dependency and should not proceed to the installation

 - PHP gd package was not installed on my server and I could not continue the installation, whereas this package is an optional package as stated in the doc

**Comment by orthagh** [comment]
for mysql 5.7, see issue in progress: #627 

For gd, it seems strange, i'll check soon

**Comment by orthagh** [comment]
Here is for gd extension.
For mysql issue, please, continue in the #627 issue
