### ISSUE TITLE
Setup3 error

### ISSUE THREAD

**Issue by YounesBerbri** [glpi-project/glpi#8402]
I am trying to install GLPI on my windows xamp server and as soon as I reach setup3 i do get this error that happend to me using wamp 2.
**PHP Error (1): Maximum execution time of 120 seconds exceeded in C:\xampp\htdocs\glpi\inc\toolbox.class.php at line 2504
![error](https://user-images.githubusercontent.com/74791228/101643746-bc7dbf00-3a34-11eb-9217-9feb9f3f0b56.png)
**

**Comment by cedric-anne** [comment]
Duplicates #4223.
