### ISSUE TITLE
Vlan incorrectly reported as "Not Tagged"

### ISSUE THREAD

**Issue by cadegenn** [glpi-project/glpi#8405]
**Describe the bug**

In [Network Management] page, in the [Network Ports] page, I choose to display VLAN information. All VLAN are displayed as "Not tagged", even if obsiously there are.

I checked the raw inventory in XML format and network ports are correctly reported as tagged or untagged.

**To reproduce**

1. get the inventory of a switch
2. upload this inventory to GLPI
3. got to [Network Assets] -> [Network Ports]
4. click the wrench to Display VLAN
5. See all VLAN as untagged

**Expected behavior**

Respect the <TAGGED></TAGGED> tag of the XML inventory to display the VLAN as (un)tagged as appropriate.

**Screenshots**

Extract of the inventory as XML :
![Sélection_040](https://user-images.githubusercontent.com/6342490/101875694-5f485180-3b8b-11eb-9966-06ee10649826.png)

What I see in GLPI :
![Sélection_041](https://user-images.githubusercontent.com/6342490/101875701-63746f00-3b8b-11eb-98b3-4cf8df7700ce.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

``` 
GLPI 9.5.3 ( => /var/www/glpi/glpi-prod-9.5.3)
Installation mode: TARBALL

fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
tag                  Name: Gestion des tags               Version: 2.8.0      State: Enabled
manufacturersimports Name: Imports fabricants             Version: 2.3.0      State: Enabled
mreporting           Name: Plus de rapports               Version: 1.7.0      State: Enabled

```

**Additional context**

The inventory of switchs assets is made with fusionInventory.

Thank you for all the work

**Comment by trasher** [comment]
This is a fusioninventory issue, please open issue on plugin bug tracker.

**Comment by cadegenn** [comment]
hmm I do not think so. The XML inventory file is well formed.
I digged a bit further, and it seems the database lacks some informations. The `glpi_networkports_vlan` table look like this
![Sélection_042](https://user-images.githubusercontent.com/6342490/101877366-2d84ba00-3b8e-11eb-91a7-423cfc2fa749.png)

whereas on fresh install I get
![Sélection_043](https://user-images.githubusercontent.com/6342490/101877466-5907a480-3b8e-11eb-8c4d-614ca7465c21.png)

How can I "repair" the database ? Maybe there are some other missing informations. All upgrades since a long time went well.
thank you

**Comment by cedric-anne** [comment]
> How can I "repair" the database ? Maybe there are some other missing informations. All upgrades since a long time went well.
> thank you

Hi,

This field should have been added during migration from 0.83.1 to 0.84, so maybe you had a problem during this migration.
You can run `bin/console db:check`, that may help you to identify missing fields. If you need community support, please open a discussion on [forum](https://forum.glpi-project.org/).

This issue will remained closed, unless you provide a stack trace of an error that occurs during migration to 0.84 and that is related to this field.

Regards

**Comment by cadegenn** [comment]
ok thanks for the lead. I will investigate and play with `db:check` and `db:reconfigure` on test database.
thank you.
