### ISSUE TITLE
[9.5.3] PHP-Errors on load Group view on central

### ISSUE THREAD

**Issue by tsmr** [glpi-project/glpi#8407]
```
[2020-12-11 10:59:32] glpiphplog.WARNING:   *** PHP Warning (2): count(): Parameter must be an array or an object that implements Countable in C:\wamp64\www\glpi\inc\commonitiltask.class.php at line 1871
  Backtrace :
  inc\central.class.php:260                          CommonITILTask::showCentralList()
  inc\central.class.php:95                           Central::showGroupView()
  inc\commonglpi.class.php:637                       Central::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
  
[2020-12-11 10:59:32] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to a member function next() on bool in C:\wamp64\www\glpi\inc\commonitiltask.class.php at line 1940
  Backtrace :
  inc\central.class.php:260                          CommonITILTask::showCentralList()
  inc\central.class.php:95                           Central::showGroupView()
  inc\commonglpi.class.php:637                       Central::displayTabContentForItem()
  ajax\common.tabs.php:92                            CommonGLPI::displayStandardTab()
```

It's a user without group

![image](https://user-images.githubusercontent.com/13178158/101895952-85301f00-3ba8-11eb-9010-86934a00c13b.png)

For resolve it :

public static function getTaskList($status, $showgrouptickets, $start = null, $limit = null) 

Comment : 
else {
            return false;
         }

**Comment by jlmelladovalle** [comment]
That will make to perform unstable behaviours, like with FormCreator plugin (i.e. blank page in simplified self-service).

> For resolve it :
> 
> 
> public static function getTaskList($status, $showgrouptickets, $start = null, $limit = null)
> 
> 
> Comment :
> 
> else {
> 
> return false;
> 
> }

**Comment by cconard96** [comment]
@tsmr , @jlmelladovalle does #8708 resolve the issue for both of you without creating other issues? I tested it with FormCreator enabled and didn't see an issue although I don't have many forms created to be sure there isn't an issue.

**Comment by jlmelladovalle** [comment]
Still having a blank page with this solution through simplified ticket system: http://glpiwepage.com/plugins/formcreator/front/wizard.php
