### ISSUE TITLE
Ticket validation seems not working correctly

### ISSUE THREAD

**Issue by Badoche1337** [glpi-project/glpi#841]
Hi,

I've setted up 4 approvers on a ticket, with a minimal validation of 50%. 2 approvers have approved the ticket, so the global validation status was changed to "approved", but the 2 others have always this ticket in their "ticket to validate" dashboard.

Is this "normal" ? some customers don't understand this validation process, it could be great to add a condition in the SQL query of this dashboard to filter validation request with a global status on "approved".

Have a good day !

**Comment by stonebuzz** [comment]
Confirmed with glpi 9.1

**Comment by cedric-anne** [comment]
Hi,

I just checked on GLPI 9.4 and the behaviour seems correct now.

Regards
