### ISSUE TITLE
[0.90.5] Unable to create a new bookmark

### ISSUE THREAD

**Issue by kamiben** [glpi-project/glpi#842]
Hello !
After upgrading to 0.90.4 our users are unable to create new bookmarks (was working previously on 0.90.2). Even the super-admin cannot create new bookmarks.

The following error appears while creating one : "Security die. trying to load an forbidden class name"
There is no error created in php-errors.log for this action (but the file is populated by other errors, e.g. : user logging in with invalid credentials) 

Steps to reproduce :
1. Go to assistance - tickets
2. Add some search parameters
3. Click on the star to create a new bookmark
4. Specify a name and click Add.
5. The error appears at the top and the bookmark is not created
![securitydie](https://cloud.githubusercontent.com/assets/389495/17208473/31a6a94c-54b9-11e6-81bc-e43c9a019a01.jpg)

Here is my setup :
[setup.txt](https://github.com/glpi-project/glpi/files/388085/setup.txt)
 
Thanks in advance !

**Comment by ropie** [comment]
The 0.90.5 is online this yesterday and fix this problem.
Regards

**Comment by kamiben** [comment]
Ok thanks I'm closing the issue !

**Comment by kamiben** [comment]
I've done the upgrade to 0.90.5 on our systems. The issue is still there.
The user also gets the same message when opening the load bookmark page (star at the top).

**Comment by orthagh** [comment]
Could you check in your glpi_bookmarks table if there is some lines with itemtype=0 ?
And clean them if exists.

**Comment by kamiben** [comment]
We had 19 lines with itemtype=0.
This query solved the issue, users are now able to create and user bookmarks without error. 
SELECT * FROM `glpi_bookmarks` WHERE `itemtype` = '0';
Thanks a lot !
