### ISSUE TITLE
State of cloned ticket

### ISSUE THREAD

**Issue by nykroy** [glpi-project/glpi#8434]
**Clone closed ticket  **
When I clone a closed ticket this cloned is still closed i thing the state of cloned ticket should be new

Page(s) URL

/glpi/front/ticket.form.php

To reproduce

    Go to '.Assistance.'
    Click on '.Tickets.'
    click on one ticket
    click on Select Actions
    click on clone

Expected behavior

I have that error with all web browser (chrome;firefox..;)
I have Glpi 9.5.3 installed
I thing a ticket clone is on state New 

**Screenshots**

![image](https://user-images.githubusercontent.com/7745881/102684557-e031c980-41d9-11eb-99a7-797d66d40896.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
```
[code]
 
GLPI 9.5.3 ( => /usr/share/glpi)
Installation mode: RPM

```

**Comment by levifranzen** [comment]
And it does clone even the statistics of a closed/solved ticket to a new one.

**Comment by nykroy** [comment]
https://glpi.userecho.com/es/communities/1/topics/1937-cloned-tickets-on-new-status
