### ISSUE TITLE
glpi_crontasklogs is not empty correctly

### ISSUE THREAD

**Issue by lolokai** [glpi-project/glpi#8444]
**Describe the bug**

When you define a retention in automatic tasks for cron tasks logs. The table glpi_crontasklogs is not empty correctly : logs are kept even if you define a retention

**Page(s) URL**

http://XXXXXX/front/crontask.form.php?id=22

**To reproduce**

1. Go to http://XXXXX/front/crontask.form.php?id=22
2. Click on Temps de conservation des journaux (en jours)
2. See error

**Expected behavior**

Retenton should work

**Logs**

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided.

**Comment by lolokai** [comment]
Which info do you need ?
