### ISSUE TITLE
General inconsistencies when dealing with namespaces

### ISSUE THREAD

**Issue by joao-coli** [glpi-project/glpi#8449]
**Describe the bug**

Many items and utility functions in GLPi do not seem to be able to handle classes/ items using namespaces, even the proposed 'GlpiPlugin\' namespace. That, however, seems to happen due to a variety of causes.

Some examples:

+  `getItemForItemType` function
   Inside the `DbUtils` class, this function doesn't check for the plugin namespace (maybe intentionally?) NS_PLUG, checking only for NS_GLPI. That'll cause some other problems, as it'll be shown below.

+ `viewsubitem.php` Ajax file
   Due to a difference between the way JavaScript and PHP escape `\` (and how PHP handles `$_POST`, eventually), the `getType()` function from an item defined inside a namespace will be mapped, in the HTML (e.g., when calling `Ajax::updateItemJsCode`, giving `__CLASS__` or `Item::getType()` as the value to `'type'`), to `GlpiPlugin\\Foo\\Bar`, for example. However, that is PHP equivalent to `GlpiPlugin\\\\Foo\\\\Bar`.
   This way, the class wouldn't be recognized either by `class_exists` or by `getItemForItemtype` (which uses the former function before it checks for the presence of the namespace constant).
   Creating a copy of such Ajax file and adding a line like `$_POST['type'] = preg_replace('/\\\\{2,}/', '\\', $_POST['type']);` (without fixing `getIemForItemtype`, that is) solves the issue, albeit it's not the best solution as it would have to be done in all the other ajax files.

+ `document_item.class.php` class
   Fixing `getItemForItemtype` won't fix all issues, however. In a similar way as in the last example, calling `Document_Item::showForItem` giving an item defined in a plugin (`GlpiPlugin\Foo`, for example) might not bring a display error, but will fail to link new or existing files to such item. What is ultimately given to this class is the double-backslash class name (`Glpi\\\\Foo`) which isn't able to pass the `class_exists` verification in `Document_Item::prepareInputForAdd`.

+ `dropdown.class.php` class
   An example here is `Dropdown::getDropdownValue`, that uses `getItemForItemtype` and `getTableForItemtype`. While the latter might not be a problem thanks to `$CFG_GLPI['glpitablesitemtype'][]`, the former requires a fix. It also breaks `getDropdownValue.php` Ajax file.

**Page(s) URL**

Not applicable.

**To reproduce**

+ Try creating a plugin using `GlpiPlugin\PluginName` namespace pattern and then replicate any of the given examples
+ Try, for example, putting `Project` under `Glpi` namespace and see if attaching a document is still possible.

**Expected behavior**

I'd expect that, when checking if an item or class exists, the string representing the class name was sanitized (removal of additional backslashes) and that it would check for the `GlpiPlugin` when applicable.

**Logs**

Most of the described behaviors do not cause direct errors. Generally, the action either is not executed or the function returns false (as in `class_exists` or `getItemForItemtype`).

**Screenshots**

--

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.2 ( => /var/www/html)
Installation mode: TARBALL

Server
 
Operating system: Linux 9417fa4e78c3 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
PHP 7.3.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, ctype, curl,
	date, dom, fileinfo, filter, ftp, gd, hash, iconv, intl, json, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_sqlite,
	posix, session, sodium, sqlite3, standard, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at localhost Port 8001)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36
Server Software: mariadb.org binary distribution
	Server Version: 10.5.4-MariaDB-1:10.5.4+maria~focal
	Server SQL Mode: 
	Parameters: jcoli@db/glpi
	Host info: db via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is not presentldap extension is not present
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is not presentCAS extension is not present
exif extension is not presentexif extension is not present
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.5.4) - Perfect!Database version seems correct (10.5.4) - Perfect!
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/config has been validated.Write access to /var/www/html/config has been validated.
Write access to /var/www/html/files has been validated.Write access to /var/www/html/files has been validated.
Write access to /var/www/html/files/_dumps has been validated.Write access to /var/www/html/files/_dumps has been validated.
Write access to /sessions has been validated.Write access to /sessions has been validated.
Write access to /var/www/html/files/_cron has been validated.Write access to /var/www/html/files/_cron has been validated.
Write access to /var/www/html/files/_graphs has been validated.Write access to /var/www/html/files/_graphs has been validated.
Write access to /var/www/html/files/_lock has been validated.Write access to /var/www/html/files/_lock has been validated.
Write access to /var/www/html/files/_plugins has been validated.Write access to /var/www/html/files/_plugins has been validated.
Write access to /var/www/html/files/_tmp has been validated.Write access to /var/www/html/files/_tmp has been validated.
Write access to /var/www/html/files/_cache has been validated.Write access to /var/www/html/files/_cache has been validated.
Write access to /var/www/html/files/_rss has been validated.Write access to /var/www/html/files/_rss has been validated.
Write access to /var/www/html/files/_uploads has been validated.Write access to /var/www/html/files/_uploads has been validated.
Write access to /var/www/html/files/_pictures has been validated.Write access to /var/www/html/files/_pictures has been validated.
Write access to /var/www/html/marketplace has been validated.Write access to /var/www/html/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

GLPI constants
 
GLPI_ROOT: /var/www/html
GLPI_CONFIG_DIR: /var/www/html/config
GLPI_VAR_DIR: /var/www/html/files
GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
GLPI_SESSION_DIR: /sessions
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/html/files
GLPI_CACHE_DIR: /var/www/html/files/_cache
GLPI_CRON_DIR: /var/www/html/files/_cron
GLPI_DUMP_DIR: /var/www/html/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales
GLPI_LOCK_DIR: /var/www/html/files/_lock
GLPI_LOG_DIR: /var/www/html/files/_log
GLPI_PICTURE_DIR: /var/www/html/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins
GLPI_RSS_DIR: /var/www/html/files/_rss
GLPI_TMP_DIR: /var/www/html/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/locales
GLPI_VERSION: 9.5.2
GLPI_SCHEMA_VERSION: 9.5.2
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2020

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.5 in (/var/www/html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src)

SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	fields               Name: Campos adicionais              Version: 1.12.0     State: Enabled
	gestaohoras          Name: Gestão de Horas                Version: 1.0.0      State: Not installed
	ramo                 Name: Ramo                           Version: 0.9.4.25   State: Enabled

```

**Additional context**

I'll send a PR soon, but it won't address the entire application. Those behaviors probably happen in many other classes, but those were the ones that I stumbled upon.

**Comment by cconard96** [comment]
I've run into some similar issues with a namespaces plugin. I'll give you a hand with this current list of issues if you need it and I'll hopefully have another PR ready later for other issues.

**Comment by trasher** [comment]
Well, some explanations first. GLPI do a "sanitize" (a kind of magic_quotes stuff, for both display and database) on all data; since... I guess the beginning of the project, years ago.
This is the cause of the escaping issues (and many other issues opened from a while that cannot be fixed). That cannot be fixed without spending _months_ working on it (we already tried).

GLPI should not alter data, and we should not try to guess what the real data is. We already face that kind of case several times, and that's always a nightmare (any change cause several other issues) when we try to fix. And another one when we have to fix a side effect we did not see at the beginning...

Trying to fix that partially does not seems possible. Most of the development team is not present those days, so wait for their opinion - but to me, if you open a PR for that, it won't be merged because it would have a too large impact.

Using namespaces is not really a requirement to have any wonderful plugin working; GLPI base code is more than 10years old, and we all have to deal with that at the moment.

**Comment by joao-coli** [comment]
@cconard96 thanks, I'll certainly need your help. I really appreciate it.

@trasher, generally agree with what you said. I would like to point out, however, that in `getItemForItemtype`, the "guessing" is already there: first searching for NS_GLPI, then explicitly calling `stripslashes`. Maybe looking for double slashes in class names isn't much of guessing and more of an extra sanitization step, since having double slashes is probably either a typo or a weird escaping problem. That wouldn't solve everything, though, and I understand when you say it's a lot trickier than it seems. By the way, maybe you've already tried changing that specific function and know what other errors it brings, in which case I'd be interested in knowing more about it (since I made some changes in my local code already).

I make myself availble to help in such matters, if there's more people interested. Namespaces are not needed to make a plugin work, sure, but it becomes really handy when dealing with an ever-groing codebase. Also, I see adopting some PSR standards is in the roadmap and you are already starting to use namespaces, so maybe it's a matter of time before those behaviors become a must-solve.

Finally, I won't propose any PR for now anymore. Being an important topic, it may be better waiting for some other takes from the team.

**Comment by trasher** [comment]
> @trasher, generally agree with what you said. I would like to point out, however, that in `getItemForItemtype`, the "guessing" is already there: first searching for NS_GLPI, then explicitly calling `stripslashes`. Maybe looking for double slashes in class names isn't much of guessing and more of an extra sanitization step, since having double slashes is probably either a typo or a weird escaping problem. That wouldn't solve everything, though, and I understand when you say it's a lot trickier than it seems. By the way, maybe you've already tried changing that specific function and know what other errors it brings, in which case I'd be interested in knowing more about it (since I made some changes in my local code already).

Well, yes - and no. I can tell you there are issues trying to use a namespaced class in GLPI core that correspond to a table in the database; and another one is when you try to store the class name in database (itemtype column in many tables). Also note many parts of the code are specific and therefore need to be tested/fixed specifically.

On another hand, we had to revert a lot of code following sanitizing fixes (I guess almost all changes I made on tickets sanitizing issues had finally been reverted - and I've spend days working on that).

Yes, we begin to use namespaced classes; but none of them reach those cases as far as I remember.

IMHO the best we could propose is a _partial_ support of namespaces, and we cannot really tell what will work and what won't; trying to guess with a double escaping will not be enough (it's never been for similar issues).
