### ISSUE TITLE
And Firmware for all

### ISSUE THREAD

**Issue by ashmonger** [glpi-project/glpi#849]
Hi,

Why can't we have a firmware field for computers as well as network equipment or phones?
On servers you might want to know which firmware you have installed to check if it's up to date.

Thanks

**Comment by flegastelois** [comment]
Hi,

For feature requests or enhancements, use the suggest dedicated site (http://suggest.glpi-project.org ). We check it very often.

Regards,

**Comment by ashmonger** [comment]
Done.
http://glpi.userecho.com/topics/354-/

**Comment by ddurieux** [comment]
The plugin FusionInventory add this field in computer and fill it with the inventory sent by the agent

**Comment by ashmonger** [comment]
I know @ddurieux , but since there is nothing to take care of stuffs like Chassis/BladeCenter, it could be a good way.
