### ISSUE TITLE
[9.5.3] USERS // Forced synchronization not working after changing LDAP authentification

### ISSUE THREAD

**Issue by tristangallet** [glpi-project/glpi#8494]
Hello,
I've got several Active Directories to authenticate users.

If i change the LDAP directory of a user, and i click on "Force Synchronization", when i see the user i've got :
User missing in LDAP directory and the DN is still the old.

If i log out and i log in on the new LDAP server, that's ok and the information from the new LDAP is well encoded.

**Comment by Claudiofcmartins** [comment]
Hi, i had the same probleme. Try to reput the same LDAP to the user then try the Force Synchronization.

**Comment by tristangallet** [comment]
Hello, i ve made a mass action on > 1000 users today (LDAP old to LDAP New). I've deactivated the old LDAP Server from GLPI.

I can see that the authentification LDAP is NEW, but some users can not log. If the old LDAP is reactivated, that's ok. 

So despite the gui show the New LDAP, it's the old that is used !!!

This is a big problem, i can not see the real LDAP used ! Could you help me ?

I can send you pictures or logs if that can helps...

Regards,
Tristan.
