### ISSUE TITLE
GLPI 9.5.3 mailcollector drops some attached documents depending on the file name

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#8495]
Hello,

**Describe the bug**

Some times, email attached documents wont be uploaded into created tickets.

**To reproduce**

[email attached doc.zip](https://github.com/glpi-project/glpi/files/5775742/email.attached.doc.zip)

1. Send an email to GLPI with the Excel document from the zipped file above.
2. Open the receiver, and "get email tickets now"
3. Look in the newly created ticket, and you see that the ticket doesn't contain the attached Excel file.
4. In the log files, you should find the below errors

**Expected behavior**

The Excel file should be attached in the ticket as a document

**Logs**

```
[2021-01-06 13:22:48] glpiphplog.WARNING:   *** PHP Warning (2): file_put_contents(C:\Projects\GLPI\9.5/files/_tmp/=?UTF-8?Q?=E5=8A=9E=E5=85?==?UTF-8?Q?=AC=E7=94=A8=E5?==?UTF-8?Q?=93=81=E9=A2=84?=约Apply for officesupplies online.xlsx): failed to open stream: Illegal byte sequence in C:\Projects\GLPI\9.5\inc\mailcollector.class.php at line 1614
  Backtrace :
  inc\mailcollector.class.php:1614                   file_put_contents()
  inc\mailcollector.class.php:1513                   MailCollector->getRecursiveAttached()
  inc\mailcollector.class.php:1654                   MailCollector->getRecursiveAttached()
  inc\mailcollector.class.php:989                    MailCollector->getAttached()
  inc\mailcollector.class.php:750                    MailCollector->buildTicket()
  front\mailcollector.form.php:88                    MailCollector->collect()

```

It seems like Laminas is retrieving a wrong file name from the email, and of course trying to create a file with a question mark will fail (at least on Windows).

Thank you,
Regards,

Tomolimo

**Comment by tomolimo** [comment]
Hello,

This also occurs for the same document when sent in a reply to a notification... the document will not be uploaded into the corresponding ticket, and the follow-up will be created without the doc.

Thank you
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
Hi @tomolimo ,

1) Can you tell us if your are using IMAP or POP3 for this mail collector ?
2) Can you try with current 9.5/bugfixes branch ? We updated the laminas-mail component 2 days ago, maybe this bug has been fixed.

Regards

**Comment by tomolimo** [comment]
Hello @cedric-anne 
1. I'm using IMAP
2. I'll try and keep you informed.

Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @cedric-anne 

Which version of Laminas are you using now?

Thank you
Regards,
Tomolimo

**Comment by trasher** [comment]
As far as I remember, the lib itself is not the only related thing that has been changed; try with up to date 9.5/bugfixes branch

**Comment by tomolimo** [comment]
I found it don't worry

**Comment by tomolimo** [comment]
Hello @trasher and @cedric-anne 

I made a test on the 9.5/bugfixes branch, and the result is identical than the one of the 9.5.3:

```
[2021-01-06 16:40:18] glpiphplog.WARNING:   *** PHP Warning (2): file_put_contents(C:\Projects\GLPI\9.5-bugfixes/files/_tmp/=?UTF-8?Q?=E5=8A=9E=E5=85?==?UTF-8?Q?=AC=E7=94=A8=E5?==?UTF-8?Q?=93=81=E9=A2=84?=约Apply for officesupplies online.xlsx): failed to open stream: Illegal byte sequence in C:\Projects\GLPI\9.5-bugfixes\inc\mailcollector.class.php at line 1617
  Backtrace :
  inc\mailcollector.class.php:1617                   file_put_contents()
  inc\mailcollector.class.php:1516                   MailCollector->getRecursiveAttached()
  inc\mailcollector.class.php:1657                   MailCollector->getRecursiveAttached()
  inc\mailcollector.class.php:992                    MailCollector->getAttached()
  inc\mailcollector.class.php:754                    MailCollector->buildTicket()
  front\mailcollector.form.php:88                    MailCollector->collect()

```

Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @trasher and @cedric-anne 
Any news?
Thank you
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
Hi,

I did not had time to investigate. I guess header parameters sould be autiomatically decoded by laminas-mail component, as it is done, for instance, on the subject header. I do not know if it is a bug or a missing feature.

Regards

**Comment by tomolimo** [comment]
Hello @cedric-anne 
I'll try to investigate, and I'll keep you inform about what I can find :)
Thank you,
Regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello @cedric-anne,

I'm a bit lost in the Laminas lib...
Here is what I found:

1. Sending an email with a bare SMTP client like this one https://www.01net.com/telecharger/windows/Internet/courrier_email/fiches/143588.html gives good results, the file is correctly imported into GLPI and attached to the newly created ticket.
2. Sending an email with Outlook will lead to the issue mentioned above.

I've investigated the internal content of the email: In the multipart body content, there is
1. For the bare smtp client:
```----boundary_1_99c65811-3a2f-456e-81af-3f097146cd40
Content-Type: application/octet-stream;
        name="=?utf-8?B?5Yqe5YWs55So5ZOB6aKE57qmQXBwbHkgZm9yIG9mZmljZSBzdXBwbGllcyBvbmxpbmUueGxzeA==?="
Content-Transfer-Encoding: base64

UEsDBBQABgAIAAAAIQCkU8XPTgEAAAgEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAC
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
```

2. For Outlook:
 ```--_002_983b6268410645dd9184c2a9845e97b5araymondcom_
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;
        name="=?utf-8?B?5Yqe5YWs55So5ZOB6aKE57qmQXBwbHkgZm9yIG9mZmljZSBzdXBwbGllcyBv?=
 =?utf-8?Q?nline.xlsx?="
Content-Description:
        =?utf-8?B?5Yqe5YWs55So5ZOB6aKE57qmQXBwbHkgZm9yIG9mZmljZSBzdXBwbGllcyBv?=
 =?utf-8?Q?nline.xlsx?=
Content-Disposition: attachment;
        filename="=?utf-8?B?5Yqe5YWs55So5ZOB6aKE57qmQXBwbHkgZm9yIG9mZmljZSBzdXBwbGllcyBv?=
 =?utf-8?Q?nline.xlsx?="; size=11504;
        creation-date="Wed, 06 Jan 2021 05:06:00 GMT";
        modification-date="Thu, 07 Jan 2021 13:49:03 GMT"
Content-Transfer-Encoding: base64

UEsDBBQABgAIAAAAIQCkU8XPTgEAAAgEAAATAAgCW0NvbnRlbnRfVHlwZXNdLnhtbCCiBAIooAAC
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
...
```

As you can see there is more part headers when sent by Outlook, than for the bare smtp client.
I made new tests with Telnet to confirm that the issue is coming from the part headers, and the results are yes, the issue is from the Content-Disposition part header that gives the wrong filename shown in the PHP warning in the issue first post.
I made some steps by steps debugging and I saw that in the `vendor\laminas\laminas-mail\src\Storage\Part.php` file there is line 200 a new static, and before that line the filename is ok, and after the filename is like shown on the first post. 
This drilled down to the Mime.php file `\vendor\laminas\laminas-mime\src\Mime.php` that re-encode the complete 'Content-Disposition' part header, and returns the faulty filename.

Questions: 
1. why this re-encoding is done?
2. why use a so complex PHP library when imap PHP extension is existing and seems to do the job?

As I don't understand the Laminas philosophy, I'm not really able to fix this issue, could you help me?

I'm always available in order to do tests, and to provide more investigations, don't hesitate.

Thank you,
Regards,
Tomolimo

**Comment by trasher** [comment]
php-imap is dead, from a while (see https://github.com/glpi-project/glpi/issues/3481). As of how laminas-mail works, I have no idea, I'm not involved in their project; would be better to ask them.

**Comment by tomolimo** [comment]
Hello @trasher 

Thank you for the info: I didn't know that imap was deprecated... I'm a bit surprised that it is still available in PHP 7.4...
And about Laminas-mail, the search feature (like it was available with PHP imap module) seems not existing...

Thank you,
Regards,
Tomolimo

**Comment by edgardmessias** [comment]
A temporary solution: https://github.com/edgardmessias/glpi-fixmailcollector

**Comment by cedric-anne** [comment]
> A temporary solution: https://github.com/edgardmessias/glpi-fixmailcollector

I like this solution, this is a pretty smart way to not directly include a patch in GLPI.

I looked at your pull request on Laminas project, and, even if it fixes our issue, I cannot validate it as I am not really aware of all RFCs related to mails formatting. So, as @trasher says in https://github.com/glpi-project/glpi/pull/8531#discussion_r559544475, we will wait for a validation of your PR on Laminas project before including this fix in GLPI (using an offical release or a patch, depending on our and their schedule).

**Comment by cedric-anne** [comment]
> A temporary solution: https://github.com/edgardmessias/glpi-fixmailcollector

Hi,

We saw your plugin submission on plugin's catalog, but we will refuse it. Indeed, we do not accept plugins that may have a really short lifetime in the catalog.

Regards
