### ISSUE TITLE
Upgrade from 9.4.5 to 9.5.3 - No Dashboard

### ISSUE THREAD

**Issue by dunipj** [glpi-project/glpi#8507]
I'm upgrading from 9.4.5 to 9.5.3 and i don't have the default dashboard.

![image](https://user-images.githubusercontent.com/35108492/104015113-f3a9d200-5192-11eb-925a-bceddaec0757.png)

If we access with the GLPI user it appears, but with the other tech users it does not.

Any ideais ?

Tks

**Comment by OscarBeiro** [comment]
This looks like a missing profile permissions issue.

Review them

**Comment by dunipj** [comment]
Any suggestions where to check? It happens with all tech users :(

**Comment by luisjosemachado** [comment]
@dunipj , please check the profile configuration below.
![profile_user](https://user-images.githubusercontent.com/30940056/105498341-d69af600-5c9e-11eb-9266-9a2c23c5a3a5.png)

**Comment by dunipj** [comment]
Great ! That's it !

All working now, thank you very much !
