### ISSUE TITLE
Error creating IPv6 networks and wrong mapping IP Adress to IPv6 network

### ISSUE THREAD

**Issue by jchnbckr** [glpi-project/glpi#8519]
By creating an ipv6 net the system told me, that the network is still viewable.
I created the Network 2001:1234:123:201:: / 64 first an 2nd 2001:1234:123:200:: / 64 will not be created.
also my devices unter 2001:1234:123:200::40 are mapped to the network 2001:1234:123:201:: / 64

1. Go to https://<hostname>/glpi/front/ipnetwork.php with fresh glpi version 9.5.3
2. Add a Device with an adress on the 2nd ipv6 network
3. 2. Click on New and Create the networks 
4. See the wrong mapping in the network interfaces by the device

ps i have masked the ipv6 addresses a little but i works

**Comment by jchnbckr** [comment]
I think the check for the ipv6 subnet is buggy. It returns, that this 2nd subnet is available but it is not, it is a diffrerent one in the last bit. of the prefix.

**Comment by hwlmag** [comment]
Hi, i'm having the same problem in GLPI Version 10.0.0. 
Steps to reproduce:

Fresh install of GLPI 10 (i use docker with "diouxx/glpi" and some minor modifications with mariadb:10 as db)

1. Go to Setup > Dropdowns > Internet > IP Networks 
2. Add a IPv6 subnet (anything will do - I used ::/64 in my tests)
3. Try to add a second different Subnet (Example: fd00::/64)
-> Result is an error: "Network already defined in visible entities" which is not true



4. (Additional) Add an IPv6 address outside of ::/64 which will be linked wrong
 - First create a network device
 - Add a network port
 - Add an IPv6 to that Port (i used fd00::2)
 -> The address gets linked to ::/64
 
 This makes glpi unusable as documentation in IPv6 environments

**Comment by stonebuzz** [comment]
Hi @kcscoelho, @hwlmag, @jchnbckr 

Can you try this ?

https://github.com/glpi-project/glpi/pull/15024

Best regards

**Comment by stonebuzz** [comment]
nice !

I'll wait to hear from the other participants

**Comment by hwlmag** [comment]
Good morning, 
#15024 fixed our problems. 
Many thanks!

**Comment by trasher** [comment]
Fixed as of #15024
