### ISSUE TITLE
cannot select the kanban columns to display in a project

### ISSUE THREAD

**Issue by Danyt83** [glpi-project/glpi#8530]
**Describe the bug**

In a project, in the kanban tab, only the No status column is displayed and there is no column selection button. In the Global kanban, there is no problem, the Add a column button allows you to select.
---
Dans un projet, dans l'onglet kanban, seul la colonne Aucun statut est affiché et il n'y a pas le bouton de selection de colonne. Dans le kanban Global, il n'y a pas de probème, le bouton Ajouter une colonne permets de selectionner.

**Screenshots**
the Global Kanban : 

![image](https://user-images.githubusercontent.com/15905496/104570682-8a263980-5652-11eb-8c3e-c77f93d3e257.png)

 the kanban tab : 
![image](https://user-images.githubusercontent.com/15905496/104576850-0459bc80-5659-11eb-9284-69d44462674f.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]
 
GLPI 9.5.2 ( => /app/www/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux pfs-glpi-prod-web201 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64
PHP 7.3.19-1~deb10u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, ldap, libxml, mbstring,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem,
	sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="16M" safe_mode="" session.save_handler="files"
	upload_max_filesize="40M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at ***.fr Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.101 Safari/537.36
Server Software: Debian 9.13
	Server Version: 10.1.47-MariaDB-0+deb9u1
	Server SQL Mode: 
	Parameters: ***.fr/glpi
	Host info: ***.fr via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.1.47) - Perfect!Database version seems correct (10.1.47) - Perfect!
Access to timezone database (mysql) is not allowed.Access to timezone database (mysql) is not allowed.
The log file has been created successfully.The log file has been created successfully.
Write access to /app/www/glpi/config has been validated.Write access to /app/www/glpi/config has been validated.
Write access to /app/www/glpi/files has been validated.Write access to /app/www/glpi/files has been validated.
Write access to /app/www/glpi/files/_dumps has been validated.Write access to /app/www/glpi/files/_dumps has been validated.
Write access to /app/www/glpi/files/_sessions has been validated.Write access to /app/www/glpi/files/_sessions has been validated.
Write access to /app/www/glpi/files/_cron has been validated.Write access to /app/www/glpi/files/_cron has been validated.
Write access to /app/www/glpi/files/_graphs has been validated.Write access to /app/www/glpi/files/_graphs has been validated.
Write access to /app/www/glpi/files/_lock has been validated.Write access to /app/www/glpi/files/_lock has been validated.
Write access to /app/www/glpi/files/_plugins has been validated.Write access to /app/www/glpi/files/_plugins has been validated.
Write access to /app/www/glpi/files/_tmp has been validated.Write access to /app/www/glpi/files/_tmp has been validated.
Write access to /app/www/glpi/files/_cache has been validated.Write access to /app/www/glpi/files/_cache has been validated.
Write access to /app/www/glpi/files/_rss has been validated.Write access to /app/www/glpi/files/_rss has been validated.
Write access to /app/www/glpi/files/_uploads has been validated.Write access to /app/www/glpi/files/_uploads has been validated.
Write access to /app/www/glpi/files/_pictures has been validated.Write access to /app/www/glpi/files/_pictures has been validated.
Write access to /app/www/glpi/marketplace has been validated.Write access to /app/www/glpi/marketplace has been validated.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI constants
 
GLPI_ROOT: /app/www/glpi
GLPI_CONFIG_DIR: /app/www/glpi/config
GLPI_VAR_DIR: /app/www/glpi/files
GLPI_MARKETPLACE_DIR: /app/www/glpi/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /app/www/glpi/files
GLPI_CACHE_DIR: /app/www/glpi/files/_cache
GLPI_CRON_DIR: /app/www/glpi/files/_cron
GLPI_DUMP_DIR: /app/www/glpi/files/_dumps
GLPI_GRAPH_DIR: /app/www/glpi/files/_graphs
GLPI_LOCAL_I18N_DIR: /app/www/glpi/files/_locales
GLPI_LOCK_DIR: /app/www/glpi/files/_lock
GLPI_LOG_DIR: /app/www/glpi/files/_log
GLPI_PICTURE_DIR: /app/www/glpi/files/_pictures
GLPI_PLUGIN_DOC_DIR: /app/www/glpi/files/_plugins
GLPI_RSS_DIR: /app/www/glpi/files/_rss
GLPI_SESSION_DIR: /app/www/glpi/files/_sessions
GLPI_TMP_DIR: /app/www/glpi/files/_tmp
GLPI_UPLOAD_DIR: /app/www/glpi/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /app/www/glpi/locales
GLPI_VERSION: 9.5.2
GLPI_SCHEMA_VERSION: 9.5.2
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2020

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/app/www/glpi/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/app/www/glpi/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.5 in (/app/www/glpi/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/app/www/glpi/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/app/www/glpi/vendor/michelf/php-markdown/Michelf)
true/punycode in (/app/www/glpi/vendor/true/punycode/src)
iamcal/lib_autolink in (/app/www/glpi/vendor/iamcal/lib_autolink)
sabre/dav in (/app/www/glpi/vendor/sabre/dav/lib/DAV)
sabre/http in (/app/www/glpi/vendor/sabre/http/lib)
sabre/uri in (/app/www/glpi/vendor/sabre/uri/lib)
sabre/vobject in (/app/www/glpi/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/app/www/glpi/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/app/www/glpi/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/app/www/glpi/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/app/www/glpi/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/app/www/glpi/vendor/sebastian/diff/src)
elvanto/litemoji in (/app/www/glpi/vendor/elvanto/litemoji/src)
symfony/console in (/app/www/glpi/vendor/symfony/console)
scssphp/scssphp in (/app/www/glpi/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/app/www/glpi/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/app/www/glpi/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/app/www/glpi/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/app/www/glpi/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/app/www/glpi/vendor/ramsey/uuid/src)
psr/log in (/app/www/glpi/vendor/psr/log/Psr/Log)
psr/simple-cache in (/app/www/glpi/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/app/www/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/app/www/glpi/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/app/www/glpi/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/app/www/glpi/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/app/www/glpi/vendor/paragonie/sodium_compat/src)
phpCas version 1.3.6 in (/usr/share/php/CAS/source)

LDAP directories
 
Server: '***', Port: '389', BaseDN: 'dc=***', Connection filter: '***',
		RootDN: 'cn=admin,dc=***', Use TLS: none
Server: '***', Port: '389', BaseDN: 'ou=utilisateurs,dc=***,dc=fr', Connection filter: none, RootDN: none,
		Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: PHP

Mails receivers
 

Plugins list
 
	treeview             Name: Arborescence                   Version: 1.9.0      State: Not installed
	archires             Name: Architectures réseau           Version: 2.7.0      State: Not installed
	datainjection        Name: Data Injection                 Version: 2.8.1      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.10.3     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	mreporting           Name: Plus de rapports               Version: 1.7.0      State: Enabled
	reports              Name: Rapports                       Version: 1.14.0     State: Enabled
	dashboard            Name: Tableau de bord                Version: 0.9.4      State: Installed / not activated

[/code]

**Comment by cconard96** [comment]
I can't recreate this issue on 9.5.3.
To modify individual Project boards you have to be the manager or a member of the managing group. These are set on the Project's main form.
