### ISSUE TITLE
Associated elements in template tickets not working

### ISSUE THREAD

**Issue by nguyenlong89** [glpi-project/glpi#8535]
I have use GLPI version 9.5.0
server Centos 7
PHP : 7.2
During create tickets template, i have use function "Associated elements" have link with computer but in tab "Predefined fields" show word **computer** only not show which computer use for this template.
And when i create new tickets (use module "Recurrent tickets") with this template, tab Item not yet link with any computer.
how can i fix it?
![image](https://user-images.githubusercontent.com/41143544/104878304-4141ee00-598e-11eb-8071-86a7c69780c5.png)
![image](https://user-images.githubusercontent.com/41143544/104878384-6cc4d880-598e-11eb-9ca3-45c86832ec68.png)

**Comment by trasher** [comment]
Try with latest GLPI release
