### ISSUE TITLE
"Save button" on Ticket top menu

### ISSUE THREAD

**Issue by husisusi** [glpi-project/glpi#8541]
This is not a bug it is enhancement.
It's really annoying to scroll through all of the ticket pages to save changes made to the top of the ticket.
it would be very nice to have a save button on the top of the Ticket:

![image](https://user-images.githubusercontent.com/8606735/104998195-12c62080-5a2b-11eb-8b23-b529eb8cf791.png)

**Comment by flegastelois** [comment]
Dear GLPI user,

Thank you for your suggestion, please consider adding (or upvoting) this enhancement on our suggest website: https://suggest.glpi-project.org

If you want to contribute to the project code, please take a time to read the project coding guidelines: https://glpi-developer-documentation.readthedocs.io

If you want to fund this feature, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us

Kind regards,
