### ISSUE TITLE
Dictionary:Software:Category not working (was #7950)

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#8558]
Same issue as #7950 . The point is that now it does work using the button "Replay the dictionary rules" but it does not work when importing software from fusion.
I've tried different actions and it looks like that also the "associable to a ticket is not working" (but it is working with the "Replay" command).

davide

GLPI 9.5.3
Fusion 9.5+1.0

**Comment by WebGregGit** [comment]
Hi.
Have you tried to install the latest patch package? 
https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22
