### ISSUE TITLE
Supported cache systems

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#8561]
GLPI currently uses per default APCu (or wincache on windows) if it is available (while it is possible to use several other by configuration).

While it does the cache job, and really can enhance performances, there are several issues with that kind of system; mainly because command line and web cache are not shared; and we have more and more GLPI CLI commands... Also, current lib (laminas-cache) has lacks on some points (nothing is cached in FS when a TTL is set. All silently...).

Proposal would be to keep only cache system relying on servers (memcache(d), redis) and filesystem (as default anyways). Is certainly requires more setup to get the cache system available; but it would also be mush more reliable.

**Comment by cedric-anne** [comment]
Done in #8561.
