### ISSUE TITLE
[9.5.3] MailCollector is getting emails from IMAP Inbox in a LIFO way

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#8562]
Hello,

**Describe the bug**

MailCollector is fetching emails from IMAP Inbox in a wrong order. It is retrieving emails using last in first out (LIFO) order instead of using first in last out (FIFO) order.

**To reproduce**

1. Use the two EML files provided below in the zip.
[emails.zip](https://github.com/glpi-project/glpi/files/5850596/emails.zip)
2. Place them in the Inbox of the IMAP server
3. Get "email ticket now" from the mail collector "Actions" page 
4. And look at the created tickets
5. You'll see that they are not created in the right sequence 

**Expected behavior**

To get the emails from the IMAP in the FIFO order and not in the LIFO order

Thank you,
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
Hi @tomolimo ,

Maybe #8563 could fix this, but I am not sure that is the best solution.
Indeed, I guess the order may depends on mail server, and maybe alos on used protocol. The best way to be sure that we collect emails in a FIFO order would be to fetch all messages, store a `$key => $date` entry for each of them, sort the list, then process the list.
Problem is that we have to be careful about memory usage when doing this, and if the servers contains hundred of emails, fetching all of them could be really long (maybe a warning could be sufficient).

I do not have time to work on this right now, so if you find a good solution, do not hesitate to propose the fix.

Regards

**Comment by tomolimo** [comment]
Hello @cedric-anne 
This morning, I can't reproduce this issue any longer...
I'm sorry, I've probably done a wrong thing
I'm going to check again, and keep you informed.
Thank you
Regards,
Tomolimo

**Comment by cedric-anne** [comment]
It seems that dovecot serve email in a FIFO order (see test suite results), so this fix may work for your case, but may introduce your issue on other configurations.

**Comment by tomolimo** [comment]
Hello @cedric-anne 
Thank you for your involvement, but I think I did something wrong in the steps, probably when I've copied/pasted the EML files in the mail box.
I made new tests and the order is OK.
I close this issue,
Thank you again,
Regards,
Tomolimo
