### ISSUE TITLE
Css error in ticket timeline history

### ISSUE THREAD

**Issue by CoRpO** [glpi-project/glpi#8566]
I noticed that since 0.90 (commit https://github.com/glpi-project/glpi/commit/28004a5b1f39694e33755178c5dc63438160a146?branch=28004a5b1f39694e33755178c5dc63438160a146), the right column of the ticket timeline history gets wrong margin for p html tags, resulting in no space between paragraphs. But the richtext editor use those, resulting in not very readable results for the users

I think that the css should be the same for left & right columns

**Comment by cedric-anne** [comment]
Hi,

Please propose a pull request with your fix.

Regards
