### ISSUE TITLE
GLPI 9.5.2 project view KANBAN  : see all project 

### ISSUE THREAD

**Issue by ecastel1103** [glpi-project/glpi#8574]
Bonjour,

menu OUTILS / PROJETS puis vue KANBAN
![image](https://user-images.githubusercontent.com/77977055/105722087-913c2a00-5f25-11eb-8c9e-7c934b9de2c5.png)

Sur l'écran KANBAN qui apparait ensuite, les projets et les taches de toutes les autres entités apparaissent alors que je suis positionné sur une entité bien précise.

Normal ou pas ?

Merci d'avance pour vos lumières.

**Comment by cedric-anne** [comment]
Hi,

#8810 should fix this issue.

Next time, please observe the issue form and write in english, provide details about your GLPI informations, add screenshots and some logs if relevant.

Regards
