### ISSUE TITLE
Problem to add physical computer to a rack

### ISSUE THREAD

**Issue by plassey54** [glpi-project/glpi#8584]
**Describe the bug**

We have problems adding computer to a rack, the drop down list does not show physical computers even if their models are correctly set with the required number of U.Howerver the list shows virtual machine, making possible to add a vm to a rack ! 
When whriting some text in the list, it does not act as a filter as well.
This was tested with severals browsers : IE, edge, chrome, firefox

**Page(s) URL**

**To reproduce**

1. Go to 'rack'
2. Click on '+' to add an element to a rack
3. In the windows that opens, select computer, the a list of available computers for adding appears
4. This list contains virtual machine but not physical machine 

**Expected behavior**

The physical computers should appears, if their models contains a valid number of unit (U)
When writing the beginning of a computer present in the list, it should filter the names as well and should only show computers with names  beginning with the writed text

**Logs**

No errror log

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.4.4
```

**Additional context**

**Comment by trasher** [comment]
GLPI 9.4 is not supported from a while, and there were several bugfixes releases since. Please try with an up to date version; feel free to comment here if you reproduce.
