### ISSUE TITLE
Flatpickr is inconsistent with GLPI regarding 12/24 hr AM/PM time display

### ISSUE THREAD

**Issue by CartCaved** [glpi-project/glpi#8586]
**Describe the bug**

When using GLPI in English, the times are displayed in 24 hour format - except in the flatpickr date/time picker. 

I want to have the time in 24 format but I don't know if GLPI is correct or flatpickr is correct according to my setup.

1. Go to (for example) Tools>Project>Project Task
2. Click on the calendar button next to Planned start date. The time is shown in 12 hour format. 
3. Select a date and time and accept (press enter)
4. The time is shown in 24 hour format

**Expected behavior**

My expected behaviour is that the flatpickr module follows the rest of GLPI, so when I have managed to get GLPI to use 24 hour format, flatpickr should follow.

**Screenshots**

![image](https://user-images.githubusercontent.com/2926235/105987353-77722280-609e-11eb-9479-7b13fe681e3b.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

It seems flatpickr is using the option (https://flatpickr.js.org/options/) `time_24hr`, which is configured to be false by default.

**Comment by cedric-anne** [comment]
Hi,

GLPI has no configuration that gives ability to the user to change between `12 am/pm` and `24 hours` format for time.

So dorcing `time_24hr` value on flatpickr initialization seems indeed an easy solution to make time selection consistent with time dsplaying.

Regards

**Comment by Roland-GoIT** [comment]
This annoying bug is still unresolved

**Comment by CartCaved** [comment]
I wanted to make a PR, but I can't find flatpickr in the code. It's in the tarball, so I guess it gets bundled when the deployment package is prepared.

There may be a place in the code to override the bundled defaults, but I don't know enough about the code and the toolchain to be able to suggest a place in the code to change.

However, as a workaround, in the installation, the second instance of `time_24hr:false ` in the file `public/lib/flatpickr.min.js` can be changed to `time_24hr:true`. As far as I could see so far, that's sufficient. But it's also possible to change `time_24hr:false` to `time_24hr:true` everywhere to be certain.

Since the entire code in the file is in one line, a diff didn't really help.

**Comment by cedric-anne** [comment]
@CartCaved 

`flatpickr` code should not be changed. I guess the solution is to instanciate it using the good option value.

**Comment by CartCaved** [comment]
Of course - the above was just me sharing my temporary workaround for my local installation. It's not a solution.

I don't know where or how flatpickr is instantiated in glpi, but if I got some pointer, I might be able to create a PR.

**Comment by cedric-anne** [comment]
There are many places where it is instanciated. You can search for `.flatpickr(` to find them.

**Comment by CartCaved** [comment]
Let's see how this goes!
https://github.com/glpi-project/glpi/pull/14185

**Comment by cedric-anne** [comment]
Fixed by #14185.

Thanks for the contribution.
