### ISSUE TITLE
Custom CSS in UI customization does not handle quotes properly

### ISSUE THREAD

**Issue by mikekaganski** [glpi-project/glpi#8587]
In version 9.5.3, writing a custom CSS under Administration->Entities->[Entity]->UI customization, things like this:
```
#header #c_logo {
    background: url("path/to/image.png") 0 0 no-repeat
}
```
becomes in the HTML this:
```
#header #c_logo {
    background: url(&quot;path/to/image.png&quot;) 0 0 no-repeat
}
```
Note the quotes turned `&quot;` entities. This CSS results in the logo being invisible.
Of course, in this specific case it's possible to write it without quotes at all, but there may be situations when quotes are needed.

**Comment by cedric-anne** [comment]
Hi,

Fixed by #8589.

Regards
