### ISSUE TITLE
[9.5.3] Project tasks created from a Project template are created on Root Entity

### ISSUE THREAD

**Issue by OscarBeiro** [glpi-project/glpi#8598]
**Describe the bug**
Project tasks created from a Project template are created on Root Entity .  Additional screenshots at: Teclib !20488
**Page(s) URL**

Creating a new project from template: setup.templates.php

**To reproduce**

I have started using GLPI projects thanks to the new Kanban feature. Congrats by the way! 

I have found two ugly bugs. This is the first one:

1. Create project template on root entity.
2. Add a few tasks to the template
3. Create a project, based on the template, on a child entity.
4. Project is created on the chosen child entity.
5. Project tasks are created on root entity.

**Expected behavior**

Both project and task projects should be on the same entity.

**Logs**

Not relevant

**Screenshots**

Please check: Teclib !20488
[glpi-test-project-bugs.txt](https://github.com/glpi-project/glpi/files/5892963/glpi-test-project-bugs.txt)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Attached

**Additional context**

Today I've found a workaround.
If you change project recursivity, tasks are moved to the right entity.

**Comment by cedric-anne** [comment]
Hi,

#8813 should fix this issue. Can you confirm ?

Regards

**Comment by OscarBeiro** [comment]
Sorry about the late reply. Busy week.
I confirm it is fixed.
Thanks
