### ISSUE TITLE
Update 0.83 to 0.90.1

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#861]
Good day.

I have a problem. Glpi I'm upgrading from version 0.83 to 0.90.1 happens that initiates process but falls and does not advance.  I would like to know if it happened to someone else and if there is a solution or recommendation to take it into account.

This is what it takes, but as long as indicated (file):

![glpi_update](https://cloud.githubusercontent.com/assets/16838689/17385566/219fb454-59a9-11e6-90a6-3dde2875cb3b.png)

Thank you...

**Comment by tomolimo** [comment]
Hello,
Could you check the max_execution_time in PHP config file? Default setting is usually too low for migration.
Could you also check in `files/_logs/ folder` `php-errors.log` and `sql-errors.log` files?
Tomolimo

**Comment by virginiacorrea** [comment]
Thank you very much for your help.

Indeed, I expanded and runtime ok.

Thank you.
