### ISSUE TITLE
[9.5.3] The software assigned to the computer is multiple

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#8616]
**Describe the bug**

On the software tab of the computer I see the same application multiple times - with different versions.

**Page(s) URL**

glpi/front/computer.form.php

**To reproduce**

1. Go to 'Assets' > Computers > Software tab
2. Here I have the same application many times.

**Expected behavior**

I should see only the one application with actualy installed version.

**Logs**

php-errors.log ( I don't know if these errors are related - I also don't know how to fix them to check it )

[2021-02-01 15:38:50] glpiphplog.WARNING:   *** PHP Warning (2): error_log(/var/www/html/glpi/files/_log/cron.log): failed to open stream: Permission denied in /var/www/html/glpi/inc/tool>
  Backtrace :
  inc/toolbox.class.php:658                          error_log()
  inc/crontask.class.php:847                         Toolbox::logInFile()
  front/cron.php:61                                  CronTask::launch()

[2021-02-01 16:00:24] glpiphplog.WARNING:   *** PHP Warning (2): mysqli::real_connect(): (HY000/2002): No such file or directory in /var/www/html/glpi/inc/dbmysql.class.php at line 185
  Backtrace :
  inc/dbmysql.class.php:185                          mysqli->real_connect()
  inc/dbmysql.class.php:147                          DBmysql->connect()
  inc/dbconnection.class.php:192                     DBmysql->__construct()
  inc/dbconnection.class.php:274                     DBConnection::switchToMaster()
  inc/config.php:85                                  DBConnection::establishDBConnection()
  inc/includes.php:48                                include_once()
  ajax/notifications_ajax.php:33                     include()

**Screenshots**

![multiple_software](https://user-images.githubusercontent.com/68922721/106458341-84bd5180-6490-11eb-88e0-7691059ee97e.jpg)

![multiple_software_2](https://user-images.githubusercontent.com/68922721/106458435-ab7b8800-6490-11eb-97cb-7353c53b7c03.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]
 
GLPI 9.5.3 (/glpi => /var/www/html/glpi)
Installation mode: TARBALL

Server
 
Operating system: Linux server 5.4.0-60-generic #67-Ubuntu SMP Tue Jan 5 18:31:36 UTC 2021 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at server.domain Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Server Software: (Ubuntu)
	Server Version: 8.0.22-0ubuntu0.20.04.3
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (8.0.22) - Perfect!Database version seems correct (8.0.22) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/glpi/config has been validated.Write access to /var/www/html/glpi/config has been validated.
Write access to /var/www/html/glpi/files has been validated.Write access to /var/www/html/glpi/files has been validated.
Write access to /var/www/html/glpi/files/_dumps has been validated.Write access to /var/www/html/glpi/files/_dumps has been validated.
Write access to /var/www/html/glpi/files/_sessions has been validated.Write access to /var/www/html/glpi/files/_sessions has been validated.
Write access to /var/www/html/glpi/files/_cron has been validated.Write access to /var/www/html/glpi/files/_cron has been validated.
Write access to /var/www/html/glpi/files/_graphs has been validated.Write access to /var/www/html/glpi/files/_graphs has been validated.
Write access to /var/www/html/glpi/files/_lock has been validated.Write access to /var/www/html/glpi/files/_lock has been validated.
Write access to /var/www/html/glpi/files/_plugins has been validated.Write access to /var/www/html/glpi/files/_plugins has been validated.
Write access to /var/www/html/glpi/files/_tmp has been validated.Write access to /var/www/html/glpi/files/_tmp has been validated.
Write access to /var/www/html/glpi/files/_cache has been validated.Write access to /var/www/html/glpi/files/_cache has been validated.
Write access to /var/www/html/glpi/files/_rss has been validated.Write access to /var/www/html/glpi/files/_rss has been validated.
Write access to /var/www/html/glpi/files/_uploads has been validated.Write access to /var/www/html/glpi/files/_uploads has been validated.
Write access to /var/www/html/glpi/files/_pictures has been validated.Write access to /var/www/html/glpi/files/_pictures has been validated.
Write access to /var/www/html/glpi/marketplace has been validated.Write access to /var/www/html/glpi/marketplace has been validated.

**Additional context**

The navigation links (next and previous) not working with it. When I choose one application "the next" will stop on first doubled application on list. The previous will skip number. For example if I have 7 applications on list:

Software 1
Software 2
Software 3
Software 3 second version
Software 4
Software 5
Software 5 second version

When I open "Software 1" above I have "next" link (1/7). When I click it... 2/7. Click again and 3/7. Click again and... 3/7. He gets stuck on the first multiple application.

When I click "Last" I will go to 6/7 posiotion. Not 7/7 because the last application is multiple too.

If I'm at the last one and I will use the "previous" link - I will go to 5/7. Again click on "previous" and... 3/7. Why? Because 4/7 is multiple. It looks like multiple applications are transparent for this links. It stops complitly for "Next", and skips for "Previous".

I have just installed https://github.com/glpi-project/glpi/actions/runs/526317566  (GLPI nightly build GLPI nightly build #240)

**Comment by cedric-anne** [comment]
Hi,

Deduplication is not made by GLPI itself but by the inventory plugin (fusioninventory or ocsinventory in most cases). Please open an issue on their bug tacker.

Regards
