### ISSUE TITLE
Information unrelated to user's Entity is shown in user details in Administration

### ISSUE THREAD

**Issue by mikekaganski** [glpi-project/glpi#8620]
In v.9.5.3, having a child entity like `Root > Subentity1`, and a user that has an authorization to the said sub-entity (recursive), the said user (without any authorization to top-level entity or any other sibling sub-entities) can see some information about e.g. super-admins (`glpi`) that they should not: e.g., in Authorizations, they see that `glpi` has an authorization to the `Root` entity (which is *arguably* bad per se, and *possibly* could be better expressed as "has authorization to `Subentity1`, inherited from parent" to not name specific information that current user is not expected to know), but more importantly - also an explicit authorization to `Root > Subentity2` that I added for testing purposes, and which is absolutely unrelated to `Subentity1`. This would expose the names of subentities that might be confidential if they represent customers, partners, etc. Also in `Historical`, the user sees "584 | 2021-02-02 07:28 | glpi (2) | Profile | Add an item: Profile (Partner (11))", which is also something that the user is not intended to see.

**Comment by cedric-anne** [comment]
Hi,

Indeed, I confirm that it would be preferable that these informations be not accessible.

Regards
