### ISSUE TITLE
Error install GPLI 9.5.3 - /tecnickcom/tcpdf/

### ISSUE THREAD

**Issue by C0Y4** [glpi-project/glpi#8621]
Hi! 

I am trying to install GLPi 9.5.3, the latest version with php 7.4, and I get the following error:

> patch -f -p1 -d vendor/tecnickcom/tcpdf/ < tools/tcpdf-php8-compat.patch || echo 'Error applying patch, deprecation warnings related to TCPDF lib may pollute logs'
patch: **** Can't change to directory vendor/tecnickcom/tcpdf/ : No such file or directory
Error applying patch, deprecation warnings related to TCPDF lib may pollute logs

how can i fix it? 
Thanks.

**Comment by flegastelois** [comment]
Dear GLPI User,

You are trying to install GLPI from source (which is often reserved for developer), we advise you to use our official release archive ("DOWNLOAD" button) : https://glpi-project.org/downloads/

Kind regards,
