### ISSUE TITLE
GLPI 9.5.3 Rules for assigning a ticket created through a mails receiver

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#8630]
Hi GLPI team!

I've faced with an issue in gpli 9.5.3 regarding "Rules for assigning a ticket created through a mails receiver".
It doesn't work properly. The same rule in GLPI 9.4.6 works fine.
When I send email to helpdesk a ticket is created in a Root entity but due rule it should be assigned to sub-entity.
Is it a bug? or I did something wrong?
Below you can see screenshot with rule setting:
![glpi953_rules_issue](https://user-images.githubusercontent.com/20252855/106916065-d0356100-6717-11eb-8efd-47bb2400d200.jpg)

Thanks in advance for the help.

**Comment by okvok** [comment]
Works only one default rule "Root"

**Comment by diegulec** [comment]
Hi ,  I had same issue but  just Resolved this by using rule like this  :

![1](https://user-images.githubusercontent.com/78162275/108070450-d48d4280-7064-11eb-9322-6b13e7462406.PNG)
![2](https://user-images.githubusercontent.com/78162275/108070461-d820c980-7064-11eb-8f87-069e2549fa4f.PNG)

**Comment by cedric-anne** [comment]
Hi,

It duplicates #8340 .

Regards
