### ISSUE TITLE
Bugs in exporting GLPI contacts as .vcf

### ISSUE THREAD

**Issue by oj1969** [glpi-project/glpi#8636]
Dear all,

in GLPI 9.5.3 there is a bug in exporting contacts as **.vcf** file. When you import the **.vcf-file** into Outlook or another app the following happen:

| GLPI            | Outlook/other App           | Should be    |
| --------------- | --------------------------- | ------------ |
| phone           | phone                       | phone        |
| mobile phone    | another phone field         | mobile phone |
| faximile number | another phone field 2       | faxsimile    |
| address         | name of the linked supplier | address      |
| zip code        | n/a                         | zip code     |
| city            | n/a                         | city         |
| country         | n/a                         | country      |
| typ             | n/a                         | note         |
| title           | n/a                         | title        |

This is core functionality in GLPI and can be found in the menu topic "contacts". See Link "visit card". _Expected is an fully functional working export which is fully compatible with the vcf-format_.

It should be work at a glance. When will this fixed ?

Thanks

Kind regards

Oliver

**Comment by cedric-anne** [comment]
Hi,

Indeed, I confirm the bug.
vCard export is not working, as generated file does not seems fully complient with vCARD format and some informations are missing.

Regards

**Comment by oj1969** [comment]
This is still a bug - even in the newest Version
