### ISSUE TITLE
There is no way to view the ratings and comments of the satisfaction surveys.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#8645]
GLPI 9.5.2

In the history of the closed application:
![image](https://user-images.githubusercontent.com/16879167/107500882-be384000-6ba7-11eb-8e06-1c7668dcf8ab.png)
On the satisfaction tab:
![image](https://user-images.githubusercontent.com/16879167/107500958-d5772d80-6ba7-11eb-89b5-0250c6d7c7b2.png)
The ability to view ratings and comments of satisfaction surveys is missing?

The average score is also not displayed:
![image](https://user-images.githubusercontent.com/16879167/107502029-36533580-6ba9-11eb-9759-a684f3f32ecb.png)

**Comment by cedric-anne** [comment]
Hi,

Please add more details about the way to reproduce and add screenshots in english.

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot investigate without any feedback.

Regards
