### ISSUE TITLE
$DB->list_tables() also lists views

### ISSUE THREAD

**Issue by SylvieCozic** [glpi-project/glpi#865]
Hello GLPi team,

For some particular plugins we use views in the glpi database.

But we have an issue when the `$DB->list_tables()` function is called as it's not only returning all tables but also all views.

For example, if I want to migrate lets say to 9.1 RC2 :) then
`install\update.php` will call `DBmysql::optimize_tables($migration);`
`optimize_tables` function will call `$result = $DB->list_tables();`
and `$query = "OPTIMIZE TABLE `".$table."` ;";` will crash when trying to "optimize" my views.

To avoid this I changed the list_tables function :

```
   function list_tables($table="glpi_%") {
--      return $this->query("SHOW TABLES LIKE '".$table."'");
++	  return $this->query("SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = (SELECT DATABASE()) AND TABLE_TYPE != 'VIEW' AND TABLE_NAME LIKE '".$table."'");
   }

```

I change this function since glpi 0.83.7 but I am maybe not the only one needing this.

To reproduce the case, just :
- create a fake view on any "recent" version of glpi
- execute a "SHOW TABLES" --> the view is listed
- execute a "SELECT TABLE_NAME FROM information_schema.`TABLES` WHERE TABLE_SCHEMA = (SELECT DATABASE()) AND TABLE_TYPE != 'VIEW'" --> only tables are listed
- just try and execute an "OPTIMIZE" on the view ^^

It is maybe not the best way to list tables. I just couldn't find a better way. 

Regards,

_Sylvie_

**Comment by trasher** [comment]
The `SHOW` command allows to limit with a `WHERE` clause, but we have to use the `FULL` keyword:

    SHOW FULL TABLES WHERE Table_Type != 'VIEW'

This command outputs two colons; but I guess it should be OK.

**Comment by trasher** [comment]
Could you please test with the change proposed on my fork? If that sounds good, I'll open a PR :)

**Comment by SylvieCozic** [comment]
Hi Johan,

I could actually not find a class, function or script that does not fetch only the first column (index [0]) of the result. So your code _could_ be used.
But I don't have all possible plugins installed and, if possible, I still won't change the number of columns of the result array in a function of  _inc/dbmysql.class.php_.

My query returns only one column.
Reading your code, I slightly changed my query to use `$this->dbdefault` instead of` (SELECT DATABASE())` :yum: 
```
      return $this->query(
         "SELECT TABLE_NAME FROM information_schema.`TABLES` 
             WHERE TABLE_SCHEMA = '$this->dbdefault'
             AND TABLE_TYPE != 'VIEW'
             AND TABLE_NAME LIKE '$table'"
      );
```
Do you think that using _information_schema_ could be an issue ?

_Sylvie_

**Comment by trasher** [comment]
Hi Sylvie,

Yes, you are right about the columns count, it should not change; and there is no way with `SHOW` to query on table type; we have to use `FULL` :/

I'm not sure about the `information_schema`, I do not know if we can safely rely on this. I'll make some searchs, and take your solution if we can.
I guess same informations are used in the background anyways.

Thanks :)

**Comment by trasher** [comment]
OK, so I was wrong :) The `information_schema` is an ANSI standard, so we can rely on it; `SHOW TABLES` is specific to mysql (I had in mind both were MySQL specific).

Thank you very much!

**Comment by trasher** [comment]
Reference: https://dev.mysql.com/doc/refman/5.6/en/faqs-information-schema.html#faq-mysql-where-ansi-information-schema

**Comment by orthagh** [comment]
I'm not sure that using mysql.information_schema was available in some case.
You need to provide USAGE on mysql db to do that.

I think the query coold be better: 
```sql
SHOW FULL TABLES WHERE Table_Type = 'BASE TABLE'
```

**Comment by trasher** [comment]
And what about returning multiple colons instead of one? 
Dose not the "SHOW" query require some grant somewhere as well?

**Comment by orthagh** [comment]
i think the SHOW need the same rights as usage of information_schema.

You're right for the two columns, i missed that.
Perhaps your proposal is better in fact.

**Comment by trasher** [comment]
I cannot find any really reliable info on privileges that makes one better than the other :(
As for the number of columns returned, @SylvieCozic point this to me when I've proposed a first "SHOW FULL" version of the change.

Another point for the `information_schema` table: that is a standard. `SHOW` statement is not, as far as I know.

**Comment by orthagh** [comment]
i suppose also another db engines (like pgsql) doesn't use any of theses syntax ?

**Comment by trasher** [comment]
Yes, it does!
https://www.postgresql.org/docs/9.1/static/infoschema-tables.html

;)

**Comment by trasher** [comment]
And it does not for "SHOW TABLES"; see http://stackoverflow.com/questions/769683/show-tables-in-postgresql

See also http://www.postgresqltutorial.com/postgresql-show-tables/ that list only pgsql specific ways of doing this.

**Comment by SylvieCozic** [comment]
What a debate !! :smile: 
Thx everyone :+1: 

_Sylvie_
