### ISSUE TITLE
[9.5.2] Wrong e-mail for Reply-To and From

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#8652]
Hello,
In notification configuration page.
Admin is : admin@test.com
Manager is : manager@test.com

despite of setting the manager@test.com e-mail address for:
- from_email
- admin_reply
- smtp_sender

Mails received by customers are still with a From : admin@test.com

**The page**
/front/notificationmailingsetting.form.php

**Expected behavior**
Reply-To and From should reflect what we set

**Screenshots of my setting**
![Screenshot_2021-02-10 GLPI - Notifications](https://user-images.githubusercontent.com/1380639/107540391-4af1f680-6bc6-11eb-800e-45bf631bf80e.png)

**Comment by cedric-anne** [comment]
Hi,

Maybe #8559 fixes this issue. Could you test with GLPI 9.5.4 ?

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as I considered it as fixed.

Regards
