### ISSUE TITLE
Adding a task in a specific entity> Outlook

### ISSUE THREAD

**Issue by Richard76000** [glpi-project/glpi#8657]
Hello,

We encounter a big problem when we want to add a task in a specific entity: root entity> computing> agglomeration

We plan the task then we see the task appear in the planning.

When you do a CALLDAV synchronization with Outlook, the tasks do not synchronize.

On the other hand, if we create a task in the root entity, it is synchronized.

My question is: how do we synchronize tasks from several specific entities and not just the root entity?

The schedule is in root entity + sub-entities so normally I should see all the tasks in Outlook.

**Comment by Richard76000** [comment]
?? no answer...

**Comment by cedric-anne** [comment]
Hi,

Maybe I miss something, but, there is currently no entity management in CalDAV server in GLPI, which means that wherever you create your task, it will be served by the CalDAV endpoint for your user.

I just checked by creating Ticket task, Project task and External event in a sub entity, and all were visible in Thunderbird.

If you find a way to reproduce, please provide detailed steps.

Regards

**Comment by Richard76000** [comment]
We use Outlook. If the user does not have access to the root entity and the task is created on a sub-entity, suddenly in Outlook we do not see the task. As soon as we add the rights to the user A reached at the root entity. It works.
My question is why we are forced to reach at the root entity

**Comment by cedric-anne** [comment]
I take a look at the code and I reproduced this issue.

It is not directly related to the entity where the task is created, but it is related to the rights defined in the defaut (or first) profile of the user. Indeed, CalDAV ACL are currently computed based on the default profile. They should be computed based on all available profiles for this user, but this kind of logic does not exists yet in GLPI.

A technical solution could be to add ability to use `all` as parameter value for `Session::changeProfile()`, and, in this case, to compute the sum of all available profiles. Not so easy, but maybe the solution that requires fewer code changes (no need to change the way `can*` methods are implemented.

As fix may not be produced soon, a workaround could be to change default profile of your users.

If you want to speed up the resolution of this issue, you may consider subscribe to [professionnal support](https://glpi-project.org/subscriptions/).

**Comment by Richard76000** [comment]
Thanks a lot for your advice.

**Comment by Richard76000** [comment]
This is a pity...

**Comment by Richard76000** [comment]
Because suddenly we are obliged for the user to have the root entity

**Comment by cedric-anne** [comment]
> Because suddenly we are obliged for the user to have the root entity

Unless I miss something, it is not necessary.

I created 3 child entities in my root entity, created a user and give him these authorizations:
 - E1: Observer
 - E2: Observer
 - E3: Self-Service
 - User has no autorization on root entity.
Then I created a task on a ticket on E1 and E2.

If I choose "Observer" as default profile for this user, I am able to fetch task events in Outlook.
If I choose "Self-Service" as default profile for this user, I am NOT able to fetch task events in Outlook.

So, it may be tricky, depending on your profiles definition, but you may find a solution that does not requires to give authorization on root entity.
