### ISSUE TITLE
Calendar don't show on IE 11 (W7 and W10)

### ISSUE THREAD

**Issue by nicnic456** [glpi-project/glpi#8658]
Calendar (flatpickr) is not shown on IE 11 (on both W7 and W10)

I fix the issue in the inc/html.class.php file.

In calendar initilisation, the file have (line 2877 & 3056) :
_onClose(dates, currentdatestring, picker)_
I replace it by 
_onClose: function(dates, currentdatestring, picker)_

Then IE throw me an error in the console on the i18n initialisation. I just add a comma on line 1444 of the same file and now it works.

GLPI version 9.5.3

Best Regards,
Nicolas

**Comment by OscarBeiro** [comment]
Hi. 
IE is a discontinued browser, and it is not supported.
Cheers,

**Comment by cedric-anne** [comment]
Hi,

IE 11 is not supported anymore in GLPI.

Regards
