### ISSUE TITLE
mailgate-job hangs

### ISSUE THREAD

**Issue by magheinz** [glpi-project/glpi#8663]
sometimes, the mailgate-job hangs.
so the last job-run is any date, next-job-run is
1. running or
2. in the past
If next job-run is in the past, it never runs.

**Comment by magheinz** [comment]
when the job hangs, ther are one or more ticket with these history
`182703158 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
-- | -- | -- | -- | --
182703157 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703156 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703155 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703154 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703153 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703152 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703151 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703150 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703149 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703148 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703147 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703146 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703145 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703144 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703143 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703142 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703141 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703140 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703139 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703138 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703137 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703136 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703135 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703134 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703133 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)
182703132 | 22-02-2021 14:15 | cron_mailgate | Status | Change Processing (assigned) to New
182703131 | 22-02-2021 14:15 | cron_mailgate | Status | Change New to Processing (assigned)`

you can see the numbers in the first coloum.

**Comment by cedric-anne** [comment]
Hi,

Can you please provide information that are requested when creating an issue ? For instance, your GLPI setup, your GLPI logs, ...

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot investigate without any feedback.

Regards
