### ISSUE TITLE
9.1 RC2 Can't assign sftware to computer

### ISSUE THREAD

**Issue by bambresso** [glpi-project/glpi#867]
not showing version list.
files\_log\php-errors.log
2016-08-07 10:34:41 [2@DESKTOP-BEI3BCQ]
  *** PHP Notice(8): Undefined variable: values
  Backtrace :
  ajax\dropdownInstallVersion.php:88

**Comment by tomolimo** [comment]
Hello,
I can't reproduce this issue. Can you provide exact steps in order to reproduce?
Thank you,
Regards,
Tomolimo

**Comment by bambresso** [comment]
select computer
Tab Software
Select Software in dropdown
Click Install
Nothing change.
![default](https://cloud.githubusercontent.com/assets/13583138/17471897/909328fc-5d58-11e6-9577-2a6ba9fb86fc.png)
[code]
 
GLPI 9.1 ( => C:\srv\site\help)


 

Server

 
Operating system: Windows NT DESKTOP-BEI3BCQ 10.0 build 10586 (Windows 10) AMD64
PHP 7.0.8 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, fileinfo,
	filter, gd, hash, iconv, json, libxml, mbstring, mcrypt, mysqli, mysqlnd, openssl, pcre, session, standard, tokenizer, wddx,
	xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/10.0
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.13-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpi@localhost/glpi
	Host info: localhost via TCP/IP
	
OKC:\srv\site\help/config : OK
OKC:\srv\site\help/files : OK
OKC:\srv\site\help/files/_dumps : OK
OKC:\srv\site\help/files/_sessions : OK
OKC:\srv\site\help/files/_cron : OK
OKC:\srv\site\help/files/_graphs : OK
OKC:\srv\site\help/files/_lock : OK
OKC:\srv\site\help/files/_plugins : OK
OKC:\srv\site\help/files/_tmp : OK
OKC:\srv\site\help/files/_rss : OK
OKC:\srv\site\help/files/_uploads : OK
OKC:\srv\site\help/files/_pictures : OK
OKC:\srv\site\help/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK


 

Libraries

 
htmLawed version 1.1.21 in (C:\srv\site\help\lib\htmlawed)
phpCas version 1.3.4 in (C:\srv\site\help\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (C:\srv\site\help\vendor\phpmailer\phpmailer)
ZetaComponent ezcGraph installed in (C:\srv\site\help\vendor\zetacomponents\graph\src): OK
Zend Framework in (C:\srv\site\help\vendor\zendframework\zend-loader\src)
SimplePie version 1.4.1 in (C:\srv\site\help\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (C:\srv\site\help\vendor\tecnickcom\tcpdf)
ircmaxell/password-compat in (C:\srv\site\help\vendor\ircmaxell\password-compat\lib). Compatitility: Ok
iacaml/autolink in (C:\srv\site\help\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\srv\site\help\vendor\sabre\vobject\lib)
guzzlehttp/guzzle in ()


 

SQL replicas

 
Not active


 

Notifications

 
Way of sending emails: PHP


 

Mails receivers

 


 

Plugins list

 


 
[/code]

**Comment by tomolimo** [comment]
I did the same and got the version info:
![image](https://cloud.githubusercontent.com/assets/7569958/17473430/c1f03712-5d50-11e6-871e-561deb47a8dc.png)

So could you check if you have any version available for the software you would like to install?

regards,
Tomolimo

**Comment by bambresso** [comment]
Yes, no versions. My mistake. Thanks.
