### ISSUE TITLE
Wrong software count on asset tabs

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi#8670]
**Describe the bug**

On GLPI 9.5.3 nightly build from yeaterday (https://github.com/glpi-project/glpi/actions/runs/567034923), the software count showed on the left tabs of an asset is wrong when viewing from an sub-entiry.... 

It displays the correct number in the main entity

In my example bellow, it list 1883407 softwares installed when in reality there is only 402. 

I'm not sure where the loop is coming from but on 9.5.2, it was dispaying the correct number. 

**Page(s) URL**

https://glpi.mydomain/glpi/front/computer.form.php?id=9530

**Screenshots**

![image](https://user-images.githubusercontent.com/38400135/108084970-d34b1e00-7042-11eb-81ba-dfab19880743.png)

![image](https://user-images.githubusercontent.com/38400135/108085208-160cf600-7043-11eb-962d-bd4da0d8137d.png)

** Additional context *
- Computer asset is created/updated by fusionInventory and resides on a sub-entity
- All related softwares seems to be in the correct sub-entity but I haven't had time to check the whole 402  from this computer
- The error shows `**THE SAME WRONG number for all computers**`, not just one affected
- It only shows the wrong number when viewing the asset from the sub-entity (where the computer is located) and not when viewing from the root entity`
- **This number seems to be growing (I suspect fusionInventory client creating duplicate software iteration on each inventory maybe)**

Thanks
Francois

**Comment by fralla2** [comment]
`This number seems to be growing (I suspect fusionInventory client creating duplicate software iteration on each inventory maybe)`

**Correction :** This number is growing but probably not from each inventory since it only added 6 items (now shows 1883412 instead of 1883406) from the last time I've checked and fusionInventory receives about a 1000 inventory per hour.... Maybe a new app was added to the global softwares inventory (or 6) in between

**Comment by cedric-anne** [comment]
Hi,

#8779 should fix this issue. Could you confirm ?

Regards

**Comment by fralla2** [comment]
I confirm the fix is working and asset page loading went from 4-5 sec to 0.292 sec :)

Thanks again for your excellent work @cedric-anne
