### ISSUE TITLE
"Custom Fields/Fields" plugins issue

### ISSUE THREAD

**Issue by saumyajit** [glpi-project/glpi#868]
Hi,

I've installed "Custom Fields/Fields" plugins but they are either not compatible or unable to create multiple (additional) fields which will be visible on the default Ticket creation page. Kindly suggest.

**Comment by remicollet** [comment]
Please report plugin issues against respective project.
Not a GLPI bug

**Comment by saumyajit** [comment]
Thanks Remi for the update. Surely I'll check with respective teams.
