### ISSUE TITLE
A request created from a project task is not attached to this task.

### ISSUE THREAD

**Issue by kofe88** [glpi-project/glpi#8680]
GLPI 9.5.2

When you create a request from a project task (the "Create a request for this task" button), 
![image](https://user-images.githubusercontent.com/16879167/108352379-cfacc800-71f7-11eb-87dc-8b9e45c4e5df.png)
the request creation form opens. 
![image](https://user-images.githubusercontent.com/16879167/108352454-eb17d300-71f7-11eb-9f80-9b4b43725fdb.png)
But when you change the Category, Initiator, etc., the page is reloaded and the projecttasks_id link disappears from its address. 
![image](https://user-images.githubusercontent.com/16879167/108352549-100c4600-71f8-11eb-94b0-7a97eb75355d.png)
Before: /front/ticket.form.php?_projecttasks_id=11 
![image](https://user-images.githubusercontent.com/16879167/108352599-24504300-71f8-11eb-99c6-0463b704f067.png)
After: /front/ticket.form.php. 
![image](https://user-images.githubusercontent.com/16879167/108352667-38944000-71f8-11eb-9c77-3e8bb922adcd.png)
And after creating a request, it does not join the task/project automatically.

**Comment by cedric-anne** [comment]
Hi,

#8778 should fix this issue. Could you confirm ?

Regards
