### ISSUE TITLE
Automatic actions Wake agents up broken/confusing

### ISSUE THREAD

**Issue by we-sell-bags** [glpi-project/glpi#8681]
`GLPI 9.5.3 (/glpi => /usr/share/glpi)
Installation mode: TARBALL
Operating system: Linux glpi 3.10.0-1160.15.2.el7.x86_64 #1 SMP Wed Feb 3 15:06:38 UTC 2021 x86_64
PHP 7.3.27 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.6 (CentOS) PHP/7.3.27 ()
`

The menu item "run period" is broken.
the  boxes runs from 0-24

if the first box is set to 0, then it does not show up, it is still blank.
this and the run frequency just don't make sense....

say for example run frequency  "2 days"  run period 0-24.. what exactly is that supposed to mean?

if you then click "execute"  you get sent to :
http://bob.com/glpi/front/crontask.form.php

which is a dead screen.....

Why not just lay it out as a CRON table & have done with it........
have a collection of  simple setups in " simple schedule", or even a user defined nested item.
or like the following:

![bob](https://user-images.githubusercontent.com/25189116/108448735-3b953c00-729d-11eb-924b-cd123abe2c94.jpg)

**Comment by cedric-anne** [comment]
Hi,

First of all, maybe I'm wrong, but the use of ellipsis leaves room for unpleasant innuendo. If you want your problem to be taken care of properly, it would be best if you were at least polite.

Secondly, if you have a "dead screen", you may have logs to explain what happens.

For the "blank" box when 0 value is seleted, #8682 should fix this issue.

For the way the automatic actions schedule is done, it may certainly be improved. You can either propose a pull request to enhance this, either [contact us](https://portal.glpi-network.com/contact-us) to fund an improvement.

And then, as the `Wake agents ups` task is a task from the fusioninventory plugin, we cannot fix this problem in GLPI. Please open an issue on this plugin's reprository.

Regards
