### ISSUE TITLE
[9.5.3] Enhancement of planning display

### ISSUE THREAD

**Issue by ZeikoFr** [glpi-project/glpi#8685]
Hello,

Currently this is how the planning look like : 
![image](https://user-images.githubusercontent.com/54892453/108683654-2f55ec80-74f2-11eb-8d3a-f11d1e44200b.png)

As you can see low time task are almost not visible (see at 10h00 on monday) and there's a lot of unused space at the bottom, maybe it could be expanded so the low time task are more visible ?

It's the same with day to day planning : 

![image](https://user-images.githubusercontent.com/54892453/108683944-8cea3900-74f2-11eb-9cd6-c5e5e3ccc01b.png)

Regards,

**Comment by cedric-anne** [comment]
Hi,

This may be part of a more global improvement on planning view. I close this issue as it will not be treated individually.

Regards

**Comment by ZeikoFr** [comment]
Perfect, thanks, is there any plans for an improvement on the planning view in the next major update ?

**Comment by cedric-anne** [comment]
We are currently working on complete refurbish of the UI. See #8365 .

**Comment by ZeikoFr** [comment]
> We are currently working on complete refurbish of the UI. See #8365 .

Thanks a lot ! Really exited to see the changes !
