### ISSUE TITLE
Correctly import proxyAddresses field from Active Directory

### ISSUE THREAD

**Issue by CartCaved** [glpi-project/glpi#8686]
**Describe the bug**

If a user has multiple email address in Active Directory, those are stored in the field `proxyAddresses`. The main email address is prefixed with `SMTP:` and the aliases are prefixed with `smtp:` (lowercase). 

When GLPI imports the field `proxyAddresses`, the prefix remains and the email address isn't recognized.

**To reproduce**

1. Go to Setup>Authentication>LDAP Directories
2. Pick or create an AD LDAP directory
3. Go to Users tab, add proxyAddresses (to Email2 for example) and save
4. Force synchronize a user
5. The user will now have the main email address and the alias(es) as email addresses, however with the prefix (`smtp:` or `SMTP:`). I.e. the importer correctly adds multiple email addresses, as the `proxyAddresses` field can have multiple rows, but the prefix isn't removed.
6. Sending an email to the mail receiver from an email address with a prefix doesn't work (refused)

**Expected behavior**

My preference is that 1. the prefix is removed when importing addresses from `proxyAddresses`, and 2. the alias with `SMTP`: prefix (upper case) is used as the main email address for the user. Any non-smtp address could be discarded.

**Additional context**

See for instance https://docs.microsoft.com/en-us/powershell/module/exchange/set-mailuser under parameter -EmailAddresses:

> * SMTP: The primary SMTP address. You can use this value only once in a command.
> * smtp: Other SMTP email addresses.
> * X400: X.400 addresses in on-premises Exchange.
> * X500: X.500 addresses in on-premises Exchange.

**Comment by cedric-anne** [comment]
Hi,

Handling this field may be an interresting feature (maybe more appropriate in a GLPI plugin dedicated to Azure AD), but it is not part of our roadmap.

You may consider to discuss about this with the community on our suggest website: https://suggest.glpi-project.org .

If you want to fund this feature, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us

Regards

**Comment by CartCaved** [comment]
Hi!

Just a couple of points. 
(i) Naturally, it's up to the project to decide what is on the roadmap! I'm just grateful for the great project!
(ii) This is not restricted to Azure AD, it is applicable for any AD where users have multiple email addresses. Finding out what email address(es) a user has from AD is supposed to be from the `proxyAddresses` field. The `mail` field, although it works in most configurations, is actually not the correct field to retrieve the email address(es) of a user. When retrieving the correct field from the LDAP authenticator, the field is not parsed in a way that works. That's why I opened it as a bug, not a feature request.
(iii) I'm happy to work on a pull request, if I can get some pointers where to start in the code. It's a large code base and I do not know my way around it!

Thanks

**Comment by cedric-anne** [comment]
Hi,

We discussed about that with GLPI Core team and we all think that this kind of code, which will be specific to a given external system (AD in this case) should be located into a plugin.

If you want to create your own plugin, there are two hooks in GLPI that you could use to get these informations and set in on the user: `retrieve_more_field_from_ldap` and `retrieve_more_data_from_ldap`.
There is an example plugin [here](https://github.com/pluginsGLPI/example) which can help you to see how hooks (in general) are implemented.

Regards

**Comment by Sarameen78** [comment]
I do have exactly the same situation and yes, everyone using GLPI with AzureAD or ActiveDirectory LDAP will have to face that problem : the field is named "ProxyAdresses".

I've looked to make a plugin to deal with it but it seems to be out of reach for my ability to code...

As a workaround, I've modify the /GLPI/src/User.php to alter the function syncDynamicEmails() (line 1453)
I've added 2 lines and now, it works well :
$email=str_replace("smtp:","",$email);
$email=str_replace("SMTP:","",$email);
there : 

    public function syncDynamicEmails()
    {
        global $DB;

        $userUpdated = false;

       // input["_emails"] not set when update from user.form or preference
        if (
            isset($this->fields["authtype"])
            && isset($this->input["_emails"])
            && (($this->fields["authtype"] == Auth::LDAP)
              || Auth::isAlternateAuth($this->fields['authtype'])
              || ($this->fields["authtype"] == Auth::MAIL))
        ) {
            if (isset($this->fields["id"]) && ($this->fields["id"] > 0)) {
                $authtype = Auth::getMethodsByID($this->fields["authtype"], $this->fields["auths_id"]);

                if (
                    count($authtype)
                    || $this->fields["authtype"] == Auth::EXTERNAL
                ) {
                    // Clean emails
                    // Do a case insensitive comparison as it seems that some LDAP servers
                    // may return same email with different case sensitivity.
                    $unique_emails = [];
                    foreach ($this->input["_emails"] as $email) {
						$email=str_replace("smtp:","",$email);
						$email=str_replace("SMTP:","",$email);
                        if (!in_array(strtolower($email), array_map('strtolower', $unique_emails))) {
                            $unique_emails[] = $email;
                        }
                    }
                    $this->input["_emails"] = $unique_emails;


I'm not fond of the idea to alter core file. Can you eventually help me to do the plugin ?
