### ISSUE TITLE
Operation status popup, bad position

### ISSUE THREAD

**Issue by remicollet** [glpi-project/glpi#87]
The operation status popup (element added, updated, ...) appears above the button to navigate in the list (next, end)
This make mass editing painful.

A better position should be find, permanent display (like in 0.85) seems definitively better, as it is very common to use the displayed link to edit the newly created object.

**Comment by yllen** [comment]
+1
For small monitor popup in under action button (like add translation) or in form in backcreated option is selected

**Comment by yllen** [comment]
Now the pop up in in the middle right of the newly form created.
You must to close this pop up to have access to fields

**Comment by orthagh** [comment]
It should be in bottom right of screen.

Your reporting of middle position is strange, could you attach a screenshot ?

I can also add a event who close this toast dialog on html body click.
