### ISSUE TITLE
API to add notes of problem or change

### ISSUE THREAD

**Issue by wilcorrea** [glpi-project/glpi#870]
Hi, I am searching about one way to add notes to a problem or change using the api. I did not found nothing about in forum (http://forum.glpi-project.org) or in docs (https://forge.glpi-project.org/projects/webservices/wiki/En_devguide). 

I will appreciate any light about it ; )

**Comment by orthagh** [comment]
Here is a curl example to post a new note to an existing problem identified by ##problem_id##

```bash
curl -X POST \
-H 'Content-Type: application/json' \
-H "Session-Token xxxx" \
-H "App-Token xxxx" \
-d '{"input": {"itemtype": "Problem", "items_id": ##problem_id##, "content": "my note content"}}' \
'http://path/to/glpi/apirest.php/Notepad/'
```

**Comment by wilcorrea** [comment]
Where I can find more about this docs?

**Comment by orthagh** [comment]
Here for POST usage: https://github.com/glpi-project/glpi/blob/master/apirest.md#add-items-add_items

I retrieved fields to fill by the sql schema of notepads : https://github.com/glpi-project/glpi/blob/master/install/mysql/glpi-9.1-empty.sql#L3899-L3907

**Comment by wilcorrea** [comment]
Thank you! I will study this ; )
