### ISSUE TITLE
Error on loading on launching cron task for custom model

### ISSUE THREAD

**Issue by teleinformatique** [glpi-project/glpi#8701]
**Describe the bug**

I create a custom by following the documentation.
When I try to laugh the cron task I got this error
PHP Compile Error (64): Cannot redeclare plugin_init_qowisio() (previously declared in /Applications/MAMP/htdocs/glpi/plugins/qowisio/setup.php:12) in /Applications/MAMP/htdocs/glpi/plugins/Qowisio/setup.php at line 23

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

/glpi/front/crontask.form.php
**To reproduce**

1. Get the example plugin https://github.com/pluginsGLPI/example
2. install it
3. got to page for cron task page to launch it

**Expected behavior**

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.3
Installation mode: TARBALL```
PHP 7.3.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, apache2handler, apc, apcu, bcmath, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, posix, session, soap, sockets, sodium, sqlite3, standard, tokenizer,
	wddx, xml, xmlreader, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="32M" 
Software: Apache ()
	
Server Software: MySQL Community Server (GPL)
	Server Version: 5.7.26
	Host info: Localhost via UNIX socket
**Additional context**

Add any other context about the problem here.

**Comment by trasher** [comment]
This issue is due to a plugin, all should goes fine if you remove it.

**Comment by teleinformatique** [comment]
I fix it by adding strtolower function
if ($plug = isPluginItemType($crontask->fields['itemtype'])) {
                  Plugin::load(strtolower($plug['plugin']), true);
   }

Name of plugin: PluginQowisioCron. 
The function isPluginItemType have this  preg_match("/Plugin([A-Z][a-z0-9]+)([A-Z]\w+)/", $classname, $matches). It return the name Qowisio. 
The system try to load glpi/plugins/Qowisio/setup.php
Where I got the error.

**Comment by cedric-anne** [comment]
Hi,

Which filesystem are you using for your webserver ?

#8705 should fix your issue.

Regards

**Comment by teleinformatique** [comment]
Hi It's work now.
I fixe it by putting strtolower see #8705. 
Your solutions work too.
Thanks
