### ISSUE TITLE
add a message during root entity ticket creation

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#871]
Hello

To avoid ticket creation on root entity it would be useful to add an option in general settings permitting to add a message during root entity ticket creation.

Example : Warning you are on root entity !

**Comment by remicollet** [comment]
So RFE,, please use http://glpi.userecho.com/

BTW, if you don't want ticket on root entity, don't give right on it.

**Comment by satyan01** [comment]
technicians have right to root entity and childs entities. but I want that they can only create ticket on childs entities

**Comment by tomolimo** [comment]
Hello,
You may disable ticket creation rights in their default profile and force them, when they want to create a ticket, to switch to another profile with no rights on root, but rights on the entity on which they must create tickets.
OR
You may give several lines of rights for the child entities, one line per child. This way they don't need to switch to another profile, but select the right entity.
regards,
Tomolimo
