### ISSUE TITLE
problem in Ticket->getCalendar() function

### ISSUE THREAD

**Issue by vaibhav12321** [glpi-project/glpi#8710]
The **slas_id_ttr** refers to class SLA. But in code, it's using class SLM which is wrong. It may give the wrong time for sla. Please check the below link for more info.

https://github.com/glpi-project/glpi/blob/b794aa463f46c2e8d54b1df74e50ced9bc169712/inc/ticket.class.php#L6704

**Comment by cedric-anne** [comment]
Hi,

Indeed, it cannot work as expected. Can you test with #8712 ?

Regards
