### ISSUE TITLE
Tickets restrict tree structure creation

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#872]
Hello :)

Question....

Daughters have created categories as appropriate entities. That is, for each sub-entity I create categories corresponding to the sub-entity.

![image](https://cloud.githubusercontent.com/assets/16838689/17590772/adec6ab8-5fa0-11e6-852d-49c10c828557.png)

The problem is that if a user has access to several sub-entities and have multiple profiles, changing profile appears to another entity (entity "x" - tree structure). This property allows you to view all categories whether or not that entity in which it is located, allowing you to select category of another entity.

WRONG..
image
![image](https://cloud.githubusercontent.com/assets/16838689/17590787/ba62bd60-5fa0-11e6-9ff9-fc693ef6f8b3.png)

OK..
![image](https://cloud.githubusercontent.com/assets/16838689/17590782/b4651bec-5fa0-11e6-912a-6b0df36a6deb.png)

WRONG... By doing this, the ticket is created in another entity, dragging the new category. For me this is a big problem.

I would like to know if I can disable this option (tree structure) for a particular user or profile .... or any idea how to make this not allowed. The best thing for me would automatically remain in the entity corresponding to the selected category.

The functionality of the tree structure or use is required for the super-admin profile that has all these possibilities, but do not know how to control this comportamieto for other users or profiles or finally works.

It can be very simple but I have not found how or what to do ... :(

I hope I have explained myself better.

**Comment by tomolimo** [comment]
Hello,
Which GLPi do you have?
Could you give configuration?
Thank you,
Tomolimo

**Comment by tomolimo** [comment]
Could you switch to English and give steps to reproduce and understand in detail your question?

**Comment by virginiacorrea** [comment]
Glpi 090.1

**Comment by virginiacorrea** [comment]
I have a parent entity (root) with several child entities.

1. A user permissions to give some of these entities.
2. If the user entity is changed and appears in tree structure ...
![image](https://cloud.githubusercontent.com/assets/16838689/17591282/22040fd0-5fa3-11e6-92b4-9ec8974ee0b7.png)

3. Allows you to see all categories ... Even those who are not of the entity where it is ...
![image](https://cloud.githubusercontent.com/assets/16838689/17591359/6a631d2a-5fa3-11e6-9d0e-f12bdba00326.png)

4. The user (error) select a category of another entity ...

EXAMPLE
![image](https://cloud.githubusercontent.com/assets/16838689/17591392/845ad56a-5fa3-11e6-8bc4-fdf9bee68b42.png)


5. This creates a ticket in the state where it is not in the entity to which the category belongs.
![image](https://cloud.githubusercontent.com/assets/16838689/17591519/2d76633a-5fa4-11e6-84b1-fde5519caff0.png)

6. This only happens when watching "all" or "tree structure".

Therefore I must transfer the ticket to the entity corresponding ... This is not practical for me ... :(

I hope I have explained it better ...

**Comment by virginiacorrea** [comment]
In the above example VEHICLE URGENT daughter is part of the entity:
Entity Root> CLIENTES> DAVIVIENDA BPO.

But the case was created in the root entity (which was positioned the user).

**Comment by tomolimo** [comment]
Hello,
I can't reproduce your issue.
Let's show what I've defined on a fresh 0.90.5 install:

Entities:
![image](https://cloud.githubusercontent.com/assets/7569958/17614418/7ce64d64-6066-11e6-9429-2269aa2b95b2.png)

Ticket Categories:
![image](https://cloud.githubusercontent.com/assets/7569958/17614508/3d856f28-6067-11e6-8301-bfb28df3129a.png)

And result, when in self-service, is:
![image](https://cloud.githubusercontent.com/assets/7569958/17614527/69409d40-6067-11e6-9eba-774a2eb9ea23.png)
Only the 'Main Cat' is available.

But I believe that your Categories are not well defined, beware at the entity for each sub-cat:
![image](https://cloud.githubusercontent.com/assets/7569958/17614567/a6591220-6067-11e6-959a-2481214ef25e.png)
In order to achieve this you must switch from 'root entity' to 'Child A' before category creation.
At the end a category is a child of a parent category and must be in a child entity of the root entity.

Could you post a screen copy of your categories like the one I've posted?

Thank you,
Regards,

Tomolimo

**Comment by virginiacorrea** [comment]
Hello

Entities:
![image](https://cloud.githubusercontent.com/assets/16838689/17626944/06056766-6075-11e6-96ba-962de70b471e.png)


Ticket Categories:
![image](https://cloud.githubusercontent.com/assets/16838689/17627627/84689dc4-6077-11e6-93cc-05d3425dd044.png)

And result, when in self-service, is:
![image](https://cloud.githubusercontent.com/assets/16838689/17627715/d23d1c64-6077-11e6-8d02-39d57eb9bf01.png)
Usuario = self-service

**Comment by virginiacorrea** [comment]
I do not understand because it leaves the category "VEHICLE URGENT" if it is created in a child entity.

If I only positioned itself at the root entity (without tree structure) thus it does not show it, which would be right.

![image](https://cloud.githubusercontent.com/assets/16838689/17627892/812c45e2-6078-11e6-8bfa-8f5c371cf6c3.png)

I do not know I'm doing wrong. :(

**Comment by tomolimo** [comment]
Could you try to migrate to the 0.90.5?

**Comment by virginiacorrea** [comment]
it's complicated.

It is the version?

**Comment by tomolimo** [comment]
Could be as I made a test with 0.90.5 and can't reproduce the issue.

**Comment by virginiacorrea** [comment]
Okay,

I made the upgrade to 090.5 in the first instance is ok. Ie if the user changes feature shows only the categories of that entity.

However if the user does this ....

![image](https://cloud.githubusercontent.com/assets/16838689/17636661/41866522-60a4-11e6-9566-2e3cff031b41.png)


Follow the inconvenience.

**Comment by tomolimo** [comment]
Hello,
Could you send me back a screen copy of the user's rights?
Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
I made a carbon copy of the settings you showed me, bu I still can't reproduce your trouble.
Could you give me more details about user's settings, entity's settings, category's settings, and explain step by step the way to reproduce your trouble?
Thank you
Regards,
Tomolimo

**Comment by virginiacorrea** [comment]
OK thank you very much.

It is understood...

With version 090.5 this does not happen . The solution is to spend the 090.1 to 090.5 . This I can not do immediately for internal reasons but I understand that would be the solution .

Tomolino thank you very much for your attention and response, which was invaluable .

But now I continue with the inconvenience but for the plug forms.

I will review that I can do about it because the Forms Line created if recursively shows and believe in the institution where I position .

Thank you very much for plugins would understand that the developer of the plugin so I think the next step is to close this problem here.

**Comment by diegosanchez114** [comment]
Virginia, como estas. Como hiciste para que las categorías padre no sean tomadas como incidencias. Yo lo que hice fue crearlas como incidentes y también como  entidad. He mirado varias maneras pero no me funciona, Gracias. Te envío el print screen.

![captura](https://cloud.githubusercontent.com/assets/14283446/25186680/841a651c-24e6-11e7-898a-3101e55147a6.PNG)

**Comment by virginiacorrea** [comment]
Hola Diego.

No comprendo bien lo que requieres....  Es decir ¿tu necesitas que "Aplicativos Internos" no pueda ser seleccionable para el usuario?

Si es así, debes seleccionar  en Configuración > Menú Desplegable>Categorías de las Incidencias... 

![image](https://cloud.githubusercontent.com/assets/16838689/25205669/68ef5b88-2529-11e7-8666-9e6c437133bc.png)

Con esto solo quedaran seleccionables "Firma Digital", "Orfeo" y "SINFAD".

Espero te sirva, sino me cuentas...

Cordialmente,

**Comment by tomolimo** [comment]
Please write in English! 
If you need to speak something else then use the forum. 
Current site must be used in English! 
Thank you 
Regards 
Tomolimo

**Comment by diegosanchez114** [comment]
regards!

Virginia, thank you  very much. It was a powerful help!

Can you help me with other issue?.
 Basically is how to enable the satisfaction survey with degrees of satisfaction (0 to 5) and export these results.
