### ISSUE TITLE
[9.5.4] Wrong number of late ticket if user profile  can't view All ticket

### ISSUE THREAD

**Issue by Bourba** [glpi-project/glpi#8746]
Hi all,
In GLPI 9.5.4
If profile can't view all tickets
![image](https://user-images.githubusercontent.com/79939888/109708568-df36f400-7b9b-11eb-99d2-05bf13d6ffb2.png)

The number of late is equal to all not solved.
![image](https://user-images.githubusercontent.com/79939888/109708885-3e950400-7b9c-11eb-8cfd-784caf0d38cc.png)

If profile can view all tickets, number of late is ok.
![image](https://user-images.githubusercontent.com/79939888/109708981-579db500-7b9c-11eb-8991-450fb65db5a9.png)

**Comment by cedric-anne** [comment]
Hi,

Could you test with #8774 ?

Regards

**Comment by Bourba** [comment]
All fine thanks
