### ISSUE TITLE
Slow ticket rendering

### ISSUE THREAD

**Issue by adonix-dev** [glpi-project/glpi#8749]
Hi everyone,

We use GLPI for many years now in our company with 200 users and more than 24k hundred tickets.
For approximately 6 month the page showing the tickets (http://glpi/front/ticket.php...) list is loading super slowly... displaying a ticket line per second.

Our production VM specs :

> CentOS 7
> php 5.4
> MySQL 5.6 ver 14.14
> GLPI 9.4.5 - OCS Inventory NG - fields - dashboard- behaviors
> 2vCPU, 4GO RAM, 40go SSD

So, we tried few things to solve this boring problem:

1) First we tried upgrading from 9.4.5 to 9.5.3 but nothing has changed;
2) We tried creating a full new VM with those specs:

> CentOS 7
> php 8
> MySQL 8.0.23
> Apache 2.4.6
> GLPI 9.5.3 no plugins
> 4vCPU, 4GO RAM, 40go SSD

3) We tried with a database of 24k ticket and one of 1k ticket and nothing has changed
4) Using the debug mode we can see that the SQL queries take less than 1 second
![image](https://user-images.githubusercontent.com/31833518/109815648-28d11e80-7c30-11eb-8554-874df5a15df5.png)

5) The Chrome network analysis show us that:
![image](https://user-images.githubusercontent.com/31833518/109815704-3ab2c180-7c30-11eb-8d5b-19f236a84dec.png)

5) We tried changing from Apache to Nginx : unsuccessfully
6) We tried cleaning the log tables

7) We made a new GLPI instance without importing our database. Then, we created 5k ticket using the cloning feature and t**his time the ticket loading is fine.**

Thanks so much for your help.

**Comment by cedric-anne** [comment]
Hi,

Do you have something in GLPI logs ?

Regards

**Comment by adonix-dev** [comment]
Hi @cedric-anne, 

Thanks for your answer but we've already checked the GLPI/Apache/MySQL logs but sadly, nothing relevant.

Sincerely,
Antony

**Comment by cedric-anne** [comment]
Hi,

How many tickets are you displaying on a page ? How many columns are you displaying ?

Can you try to create a personnal view with only a few column (i.e. id, name and content), and display 50 tickets per page, and see if problem persist ?

Also, on debug panel of GLPI, can you check how many queries you have, and maybe try to find some slow queries or even duplicated queries ?

Regards

**Comment by adonix-dev** [comment]
Hi, 

We tried displaying few ticket with few probleme but displaying 5 tickets is as slow as displaying 100 because a single line is displaying one after another.

As shown in the part 4 of my original issue description, the page loading needs 0.317s to execute 202 SQL queries.

Our GLPI behaviour is shown in the following video: https://user-images.githubusercontent.com/31833518/110618224-d4c9bb00-8196-11eb-9d92-09b3cc9603ec.mp4

**Comment by cedric-anne** [comment]
So, this is clearly not an issue related to SQL queries, and it cannot be an issue related to page rendering on GLPI side (there is nothing special to handle).

Did you try to deactivate all GLPI plugins ? 

Also, do you use any system component that may alter/process content generated by GLPI (i.e `pagespeed` module on webserver, varnish, any proxy that perform security analysis, PHP xdebug extension, ...) ? It seems that something causes the GLPI generated content to be delivered really slowly to your web browser.

**Comment by adonix-dev** [comment]
Yes we tried with all the plugins desactivated and the server is on our lan so there is no components that can slow the loading speed... no anti-virus, proxy, xdebug.. We clearn have no idea of what can be de reason of this slow page generation.

**Comment by cedric-anne** [comment]
Maybe you can make a test by installing GLPI on a test webserver creating from scratch with only apache/php, connect it to the existing database, and see if you have also these performances issues.
Your server may be on your own LAN, you can still have this kind of issue due to an incompatible/interfering/misconfigured system component.

**Comment by adonix-dev** [comment]
Hi, 

We already did that as we said in 2) and 6) :/
With a new database there is no slow displaying.. It appears after importing and updating our dumped database.

**Comment by cedric-anne** [comment]
If I understand right, you tried on a VM, and I guess it was on same infrastructure.

Can you try, let's say, on your local machine ?

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot investigate more without any feedback.

Regards
