### ISSUE TITLE
can't open master version

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#875]
.htaccess not working with default configuration

`[Fri Aug 12 12:48:01 2016] [error] [client ::1] Options FollowSymLinks or SymLinksIfOwnerMatch is off which implies that RewriteRule directive is forbidden: /home/yllen/gitsvn/front/sla.php, referer: http://localhost/glpisvn/front/ticket.form.php`

Configuration apache change needed
```
Options FollowSymLinks
    AllowOverride All
```

It's the second time you change the default configuration see #639 

For me, GLPI must work with standard configuration as it was in the past

**Comment by remicollet** [comment]
IMHO:

* Expire are not needed for GLPI to work, only optimization => provided as comment
* Redirect is also not mandatory, only useful to use smarter URL => provided as comment

**Comment by ddurieux** [comment]
+1

**Comment by tomolimo** [comment]
My 1 penny worth: for me GLPi should be agnostic (regarding web servers or OSes). And these configurations should be maintained in a dedicated repository.

**Comment by orthagh** [comment]
Fine.

I commented theses lines and enhanced api documentaion to explain how to enable rewriting.
