### ISSUE TITLE
[9.5.4] bad display of actions in massaction dropdown list

### ISSUE THREAD

**Issue by MLOcc** [glpi-project/glpi#8750]
**Describe the bug**
Since update from 9.5.3 to 9.5.4, the dropdown lists of massactions display HTML code

**Page(s) URL**
all lists of objects (computers, printers, tickets, users, ...)

**To reproduce**
1. Go to list of tickets
2. Check a line
3. Click on Actions (massactions)
4. Open the dropdown list of Actions
some of entries have <i class='ma-icon ...></i> displaying before the action

**Expected behavior**
to have the action title displaying correctly

**Screenshots**
On GLPI 9.5.3
![image](https://user-images.githubusercontent.com/71837011/109830415-c4698b80-7c3e-11eb-811a-c091585d6589.png)

On GLPI 9.5.4
![image](https://user-images.githubusercontent.com/71837011/109830513-d9deb580-7c3e-11eb-94f3-725035f63d4c.png)

**Comment by steph461** [comment]
same issues

![image](https://user-images.githubusercontent.com/68054991/109973840-2be41180-7cf9-11eb-917f-4536bba60462.png)
