### ISSUE TITLE
Newlines are removed in preformatted text

### ISSUE THREAD

**Issue by GillesMocellin** [glpi-project/glpi#8757]
It is very difficult to show code examples in KB pages.
When editing, it works, but after saving and in the viewer (outside TinyMCE), it breaks formatting.

This line remove every carriage return in the code :
https://github.com/glpi-project/glpi/blob/6ad390b4c087aabcc966c198de5299a4f4ed1c19/inc/html.class.php#L3917

But in `<pre>` and/or `<code>` sections, it should not.

**Comment by we-sell-bags** [comment]
As a secondary note to this.....
OSX (mac)  has a different  EOL formatting, 
so there are cases where it will effect mac  & if it is not cleaned up, it will display differently on cross platforms 
win->osx
OSX->win
you see it even on  github sometimes , when all the text gets shoved into 1 line

**Comment by cedric-anne** [comment]
Hi,

This piece of code, and a few other in multiple places of GLPI, are vestiges of ancient times, where it was possible to not use the "rich text mode" in GLPI. `newline` chars were removed when using rich text mode, and `nl2br` was applied on rendering, whether rich text mode was active or not.

Properly handling this may be not so easy, but you can propose a PR if you think you can propose a fix that will produce a correct rendering for new and existing content (even existing content that was produce in plain text mode).

Regards

**Comment by falco2001** [comment]
see https://github.com/falco2001/glpi/pull/1

**Comment by trasher** [comment]
PR must be opened here, not on your fork; and that PR is not OK (probably not opened on the correct branch).

**Comment by falco2001** [comment]
https://github.com/falco2001/glpi/tree/patch-3 and https://github.com/falco2001/glpi/tree/patch-2

**Comment by cedric-anne** [comment]
This has been fixed by #9011 in master branch.
