### ISSUE TITLE
[9.5.4] Document actions - html code visible 

### ISSUE THREAD

**Issue by BICB4** [glpi-project/glpi#8760]
In the document menu, if you select multiple documents and selet actions dropdown there is some html code visible.
**Describe the bug**

**Page(s) URL**

/front/document.php

**To reproduce**

1. open documents
2. Select mutiple documents
3. Click actions
4. Open dropdown
5.  See error

**Expected behavior**

Expected to bi only values, not code

**Logs**

No errors

**Screenshots**

<img width="743" alt="Screenshot_1" src="https://user-images.githubusercontent.com/50747765/110078254-c12de700-7d87-11eb-8bfe-7aa2319b45ac.png">

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.5.4 (*******) Installation mode: TARBALL
--

Operating system: Windows NT ********* 10.0 build 17763 (Windows 10) AMD64 PHP 7.2.26 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, calendar, cgi-fcgi, ctype, curl, date, 	dom, exif, fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, 	pdo_mysql, pdo_sqlite, pdo_sqlsrv, readline, session, soap, sqlsrv, standard, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, 	xmlwriter, zip, zlib) Setup: max_execution_time="3600" memory_limit="128M" post_max_size="28M" safe_mode="" session.save_handler="files" 	upload_max_filesize="1000M"  Software: Microsoft-IIS/10.0 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36 Server Software: MySQL Community Server (GPL) 	Server Version: 5.6.46-log 	Server SQL Mode:  	Parameters: glpi_user@********/glpidb 	Host info: ************* via TCP/IP

**Additional context**

**Comment by flegastelois** [comment]
duplicate #8750
