### ISSUE TITLE
Cloned Tickets 

### ISSUE THREAD

**Issue by nykroy** [glpi-project/glpi#8762]
**Describe the bug**

When i clon a ticket the clon is cloned  in the same state. If this is closed and i have not permmision to reopen  i cant use this utility. I think is more usefull to clone a ticket on new state. 

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
```
[code]
 
GLPI 9.5.3 ( => /usr/share/glpi)
Installation mode: RPM
```

**Comment by nykroy** [comment]
this is not a bug is a suggestion

**Comment by trasher** [comment]
Please use [suggestion website](http://suggest.glpi-project.org) for RFE.
