### ISSUE TITLE
[GLPI 9.5.4] The search by criteria "%" in monitor or device no longer works with the global rule

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#8765]
hello,

Since the GLPI 9.5.4 update.

that no longer work in the monitor or  peripheral with the "%" criteria. 
**With the version GLPI 9.5.3, it was ok, the selection worked**

example with GLPI 9.5.4:  "the "%" criteria" does not work anymore

Go to monitor
look my image
![1](https://user-images.githubusercontent.com/68054991/110094062-ae251200-7d9b-11eb-96fc-99c09e8462ed.jpg)
I have no information

Go to peripheral
look my image
![1](https://user-images.githubusercontent.com/68054991/110094469-27bd0000-7d9c-11eb-94b1-da36124a5603.jpg)
I have no information

In the meantime I found another solution by going to computer
Go to computer Its OK
look my image
![2](https://user-images.githubusercontent.com/68054991/110095662-6e5f2a00-7d9d-11eb-9456-39ed73e1d888.png)
The "%" works well in the computer,  I have information

**Comment by cedric-anne** [comment]
Hi,

Could you test #8766 ?

Regards

**Comment by steph461** [comment]
Its ok
Bug resolve

Thx you
