### ISSUE TITLE
9.5.3 Ticket View- Task description not in the same order as task status

### ISSUE THREAD

**Issue by joomlafun** [glpi-project/glpi#8769]
**Describe the bug**

On the ticket list view the task description is not matching the task status if you put those 2 column next to each.
Please look at the screenshot

**Page(s) URL**
Ticket list page

1°Create a ticket with 2 tasks with different status
2° View ticket list and see that items showin in task description column and the task status column are not ordered in the same way.

**Expected behavior**
Task description to match task status in the ticket view

**Screenshot
![ticket](https://user-images.githubusercontent.com/63743077/110206964-4812ba80-7e81-11eb-8e64-528e59dad7f9.png)
ots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
glpi 9.5.3 PHP 7.4.9 Kubuntu

**Comment by cedric-anne** [comment]
Hi,

Which DB server/version do you use ?

Regards

**Comment by joomlafun** [comment]
MariaDB 10.3.25 on Kubuntu

**Comment by cedric-anne** [comment]
Hi,

I reproduced the issue.

Problem is that task content is ordered by date DESC (due to specific code below) and other task fields are ordered by id.

Solution can be:
1. To drop this date ordering for task/followup content (really simple fix, but date ordering may be helpful).
2. Apply the date ordering on all fields related to followup/tasks (not so simple, and requires uni tests).

```php
// inc/search.class.php: 3675
         case "glpi_itilfollowups.content":
         case "glpi_tickettasks.content":
         case "glpi_changetasks.content":
            if (is_subclass_of($itemtype, "CommonITILObject")) {
               // force ordering by date desc
               return " GROUP_CONCAT(
                  DISTINCT CONCAT(
                     IFNULL($tocompute, '".self::NULLVALUE."'),
                     '".self::SHORTSEP."',
                     $tocomputeid
                  )
                  ORDER BY `$table$addtable`.`date` DESC
                  SEPARATOR '".self::LONGSEP."'
               ) AS `".$NAME."`, $ADDITONALFIELDS";
            }
            break;
```


Regards

**Comment by joomlafun** [comment]
Thanks a lot for your feedback Cédric, this solution helps to quickly visualize the tasks which need to be taken care of.

Have a good week-end,
