### ISSUE TITLE
after update from 90.3 to 9.1 i lost network objects

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#877]
hello!
anyway, objects still alive:
i can find it by
http://prntscr.com/c565i1
and so on:
http://prntscr.com/c565q0
but in networks directory targetly:
http://prntscr.com/c564zy
they are don't.

**Comment by Zegordo** [comment]
software too:
http://prnt.sc/c5675y
and directly
http://prnt.sc/c5678s

**Comment by flegastelois** [comment]
Hi,

You have an SQL or PHP Error, for sure : please active the Debug mode to confirm.
Go to your Preferences > Use GLPI in mode "Debug" and go again on search engine pages.

Can you give us the latest errors on GLPi's logs files (php-errors.log, sql-errors.log) ?
This files are in glpi/files/_log/ folder.

Regads,

**Comment by Zegordo** [comment]
log folder:
[_log.zip](https://github.com/glpi-project/glpi/files/419722/_log.zip)
and about debug mode...
http://prnt.sc/c6as3o - software
http://prnt.sc/c6as6l - networks

**Comment by tomolimo** [comment]
Could post the GLPi settings from:
![image](https://cloud.githubusercontent.com/assets/7569958/17691977/d7563cf8-6397-11e6-856e-85f8a2a0498e.png)

**Comment by Zegordo** [comment]
![settings](https://cloud.githubusercontent.com/assets/16854682/17692277/ae502076-63a1-11e6-8404-c6166ac234b6.jpg)

**Comment by tomolimo** [comment]
Hello,
Your troubles may come from this mySQL mode: `ONLY_FULL_GROUP_BY`,  see [Server SQL Modes ONLY_FULL_GROUP_BY](http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_only_full_group_by).
Could you try to disable this mode? and test again?
If the issue is still present after the mode disabled, then you may re-play a complete migration from 0.90.3 with this disabled mode.
thank you
regards
Tomolimo

**Comment by tomolimo** [comment]
You may also have a problem with upper/lower case in the table names, I'm going to check that also.

**Comment by tomolimo** [comment]
see also #627

**Comment by tomolimo** [comment]
Hello again,
I confirm: there is a bug on the software licenses queries.
To reproduce: just go to  'Software' tab
and do a request like:
![image](https://cloud.githubusercontent.com/assets/7569958/17693668/59b7ace2-63a0-11e6-8b05-28e1b909b051.png)
And you should get a sql error like:

![image](https://cloud.githubusercontent.com/assets/7569958/17693718/a70e92e4-63a0-11e6-8e89-512e4e032d73.png)

**Comment by tomolimo** [comment]
could you do a test with following mysql queries:

`SELECT * FROM glpi.glpi_networkportFiberchannels`
and
`SELECT * FROM glpi.glpi_networkportfiberchannels`

and give back the results?
thank you,
regards,
Tomolimo

**Comment by Zegordo** [comment]
http://prntscr.com/c6ddn5 - this is a try to enter to the mysql using webmin 
http://prntscr.com/c6did5 - this frome terminal

**Comment by Zegordo** [comment]
> Hello,
Your troubles may come from this mySQL mode: ONLY_FULL_GROUP_BY, see Server SQL Modes ONLY_FULL_GROUP_BY.
Could you try to disable this mode? and test again?
disabling this mode didn't help

**Comment by tomolimo** [comment]
Not all of your errors are linked to this, in the sql-errors.log you have several issues, and one is linked to this setting. So please keep it disabled, and we'll check for the other issues.

**Comment by Zegordo** [comment]
> If the issue is still present after the mode disabled, then you may re-play a complete migration from 0.90.3 with this disabled mode.

firstly, glpi wrote something like a "your database is too old, upgrade is required" and under this a button "update"
click it and
http://prntscr.com/c6e5dp - again this mistake 
http://prntscr.com/c6e5yp - after f5(refresh)
and again networks and software doesn't work

**Comment by tomolimo** [comment]
Here are my conclusions:
In the sql mode, you should disable the `NO_ZERO_DATE` and the `NO_ZERO_IN_DATE`. 
Disable them and re-play the migration.
Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
Then this is also linked to mySQL 5.7.
Could you change the sql mode to: `STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
and re-play a complete migration?

**Comment by Zegordo** [comment]
so..
i changed the sql mode to `STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
but update mistake came again
then i changed the sql mode to `NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
and update mistake is gone
however, networks and software are not repaired...

**Comment by Zegordo** [comment]
http://prntscr.com/c6i34b also

**Comment by tomolimo** [comment]
Hello,
Did you really re-play the migration: I mean starting with your 0.90 database?
Could you clear log files and re-play it again from the 0.90 database and stop it at the first error message (do not refresh page, just stop). And then from this point could you post log files?

If this doesn't bring us some light, then I'll ask you to send to me the zip of the DB in order to play the migration on my PC directly to be able to debug the migration procedure.

Thank you,
Regards,
Tomolimo

**Comment by Zegordo** [comment]
Hello, do you mean migration by deleting old glpi folder?
or copy new glpi to old glpi folder according http://www.glpi-project.org/spip.php?article172 this update procedure?
1. at clear installing by deleting old folder, new DB is clear.
2. at unpacking the new archive with overwriting all files of the old version (with disabling sql strict mode) gives the network/software problem.
logs:
1. first error: [after firt update error.zip](https://github.com/glpi-project/glpi/files/422058/after.firt.update.error.zip)
2. after disabling `STRICT_TRANS_TABLES` in sql
http://prnt.sc/c6rb4w - press update 
http://prnt.sc/c6rbhv - in this moment copy logs below
[disabling sql mode.zip](https://github.com/glpi-project/glpi/files/422067/disabling.sql.mode.zip)
networks/software are not visible.

**Comment by tomolimo** [comment]
So, there is a bug in the query here: 

> 2016-08-17 11:10:13 
>   *** MySQL query error:
>   SQL: INSERT INTO `glpi_apiclients`
>                   VALUES (1, 1, 1, \'full access\', NOW(), 1, NULL, NULL, NULL, \'\', \'\', 0, NULL);
>   Error: Incorrect datetime value: '' for column 'app_token_date' at row 1
>   Backtrace :
>   inc/dbmysql.class.php:204                          
>   install/update_0905_91.php:406                     DBmysql->queryOrDie()
>   install/update.php:795                             update0905to91()
>   install/update.php:954                             updateDbUpTo031()
>

**Comment by Zegordo** [comment]
> So, there is a bug in the query here:

this bug is solved by disabling  `STRICT_TRANS_TABLES` mode

in secong log

**Comment by tomolimo** [comment]
not sure if only the warning is disabled
to be sure do the following query `SELECT * FROM glpi_apiclients`
and post the result

**Comment by Zegordo** [comment]
![image](https://cloud.githubusercontent.com/assets/16854682/17731796/a67c8ff2-6477-11e6-8a4c-ceb6252fa6ac.png)

**Comment by tomolimo** [comment]
then the record has been inserted :)

**Comment by Zegordo** [comment]
mmm.... where has been inserted?

**Comment by tomolimo** [comment]
during the migration

**Comment by Zegordo** [comment]
i dont understand... i shoud do this query after migration or before?

**Comment by tomolimo** [comment]
no, that was just a test to be sure that it was done during migration

**Comment by Zegordo** [comment]
aah, so disabling the disabling` STRICT_TRANS_TABLES` mode really solves update problem?

**Comment by tomolimo** [comment]
yes and no: I made a fix to this faulty query: #879

**Comment by Zegordo** [comment]
but
anyway
software/networks 
what to do with them?

**Comment by tomolimo** [comment]
when disabling the STRICT_TRANS_TABLES we may have hidden other sql errors.
then please manually do the fix I made to `install/update_0905_91.php` line 406, see #879 
and then re-play the migration from 0.90 (with the STRICT_TRANS_TABLE on) and stop at first error and post the error logs.
thank you,

**Comment by Zegordo** [comment]
with your fix update was clear
![image](https://cloud.githubusercontent.com/assets/16854682/17732992/1e2c5f32-647d-11e6-8c17-63e812c28dd0.png)

log after update [aftter update.zip](https://github.com/glpi-project/glpi/files/422319/aftter.update.zip)

and log after login and clicking networks-software-computer 
[netsoft.zip](https://github.com/glpi-project/glpi/files/422321/netsoft.zip)

**Comment by tomolimo** [comment]
Ok, then we have two errors
one for the licenses, to reproduce, just search like following:
![image](https://cloud.githubusercontent.com/assets/7569958/17734744/77bb97ce-647e-11e6-9291-efa231dfafae.png)

and one for networkequipments: could you send to me the query (GLPi bookmark) you have for your default view?

**Comment by Zegordo** [comment]
[bookmark.zip](https://github.com/glpi-project/glpi/files/422488/bookmark.zip)

**Comment by tomolimo** [comment]
I was speaking about:
![image](https://cloud.githubusercontent.com/assets/7569958/17735254/75a5a4e0-6481-11e6-97fc-a966ad2e37fb.png)
and not a php file :)

**Comment by Zegordo** [comment]
:>
![image](https://cloud.githubusercontent.com/assets/16854682/17735305/12df97ea-648a-11e6-94b4-dc575da6de39.png)
in public tab nothing too

**Comment by tomolimo** [comment]
The issue for the glpi_softwarelicenses.number has been introduced by @orthagh here: https://github.com/glpi-project/glpi/commit/53c764f0d71ba7e3383ef79c5886393c33003c34#diff-a801c52129f44d50ab6d1db9f049c4b7R2240
So we have to wait for him to check this.

**Comment by Zegordo** [comment]
>  I'll ask you to send to me the zip of the DB in order to play the migration on my PC directly

what folder to zip?

**Comment by tomolimo** [comment]
you have to do a [mysqldump](http://dev.mysql.com/doc/refman/5.7/en/mysqldump.html)

**Comment by Zegordo** [comment]
[softnoetwo.zip](https://github.com/glpi-project/glpi/files/422811/softnoetwo.zip)

**Comment by Zegordo** [comment]
after update [softnoetwo.zip](https://github.com/glpi-project/glpi/files/422828/softnoetwo.zip)
before update [softnet before.zip](https://github.com/glpi-project/glpi/files/422829/softnet.before.zip)

**Comment by Zegordo** [comment]
some data was cleared(for security, you know)
but anyway update dont work

**Comment by tomolimo** [comment]
ok, thank you, I'll look at this, and keep you informed

**Comment by tomolimo** [comment]
to be sure: GLPi version before is 0.90.5?

**Comment by Zegordo** [comment]
0.90.3

**Comment by tomolimo** [comment]
ok,
I can see that you've sent the glpi DB folder, and not the mysql dump....
This can be a problem, as I don't have exactly the same mysql version than you have (I've 5.7.14, and you have 5.7.13). Can you use mysqldump?

**Comment by tomolimo** [comment]
I've managed to installed the before DB, so don't worry about mysql dump. I'll try these like that.

**Comment by Zegordo** [comment]
> so don't worry about mysql dump

thank you

**Comment by tomolimo** [comment]
Hello,

1. I made a test and good news: I've been able to migrate your database and to view Network devices:
![image](https://cloud.githubusercontent.com/assets/7569958/17766085/978e5c02-6529-11e6-8524-e9775b5d3a0a.png)

2. But before succeeding, I was forced to do a [mysql repair](http://dev.mysql.com/doc/refman/5.7/en/myisamchk-repair-options.html#option_myisamchk_quick) to your DB. It seems like some tables are somehow corrupted and prevent successful migration. When doing a `myisamchk` over the DB, I got some 

> warning: clients are using or haven't closed the table properly

which would sometimes mean `corrupted tables`

--> So: could you do a 'QUICK REPAIR' (`mysiamchk --quick`) of your DB and re-play the migration from 0.90.3? 

Tomolimo

**Comment by Zegordo** [comment]
> --> So: could you do a 'QUICK REPAIR' (mysiamchk --quick) of your DB and re-play the migration from 0.90.3?

not worked
are you really did the only a `myisamchk --quick` over db?

**Comment by tomolimo** [comment]
Yes,  but you may also try an extended or from FRM repair.

**Comment by Zegordo** [comment]
hmhm. 
i tried all variants of repair, but nothing helps.
Could you send to me the zip of the DB folder repaired by you?

**Comment by tomolimo** [comment]
Hello,
Here is what I did:
I took your db 'before.zip' and extracted the files into a newly empty mysql DB (named 'glpi_oleg')
I used the following command line `mysqlcheck.exe -u root -p --databases glpi_oleg > c:\temp\before_repair.txt` and I got the following results: 
[before_repair.txt](https://github.com/glpi-project/glpi/files/426550/before_repair.txt)
And got the following DB (I was forced to stop mysql server in order to get correct closed files): 
[glpi_after_repair.txt](https://github.com/glpi-project/glpi/files/426555/glpi_after_repair.txt) <- replace txt by zip

I started migration:
![image](https://cloud.githubusercontent.com/assets/7569958/17803362/44bafb16-65f6-11e6-8df7-b8ecc2db10fd.png)
end of migration:
![image](https://cloud.githubusercontent.com/assets/7569958/17803370/5109f8cc-65f6-11e6-9532-185707210476.png)
and view of network devices:
![image](https://cloud.githubusercontent.com/assets/7569958/17803377/6134265a-65f6-11e6-8a4f-2db1cad017f7.png)

DB after migration (stop mysql server in order to get clean closed files): 
[glpi_after_migration.txt](https://github.com/glpi-project/glpi/files/426563/glpi_after_migration.txt) <- replace txt by zip

One question: did you stop mysql server before creating the zip file of the GLPi 0.90.3 DB (the softnet.before.zip files)? If not (it could explain the errors in 'before_repair.txt' file) then could you regenerate this file and send it again to me after having stopped mysql?

thank you,
Tomolimo

**Comment by tomolimo** [comment]
Sorry I forgot to tell you the sql_mode of mysql server: 

> STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

**Comment by tomolimo** [comment]
Hello again,
I found the bug!
It's there: https://github.com/glpi-project/glpi/blob/master/inc/networkportfiberchannel.class.php#L336
I'll send a PR to fix it! You may try it: instead of `glpi_networkportFiberchannels` write `glpi_networkportfiberchannels` and it shoul dbe OK.

sorry for being so slow to understand

regards,
Tomolimo

**Comment by Zegordo** [comment]
> One question: did you stop mysql server before creating the zip file of the GLPi 0.90.3 DB (the softnet.before.zip files)? If not (it could explain the errors in 'before_repair.txt' file) then could you regenerate this file and send it again to me after having stopped mysql?

probably not, don't remember well

[now_stopped.zip](https://github.com/glpi-project/glpi/files/426629/now_stopped.zip)

also, after update now, i replaced db by your repaired db and it is not worked too.

**Comment by Zegordo** [comment]
> I'll send a PR to fix it! You may try it: instead of glpi_networkportFiberchannels write glpi_networkportfiberchannels and it shoul dbe OK.

IT WORKED!!!

**Comment by Zegordo** [comment]
so maybe software bug 
http://prnt.sc/c7nftf
has a similar way to solve?

**Comment by tomolimo** [comment]
Yes, but already analyzed: see : https://github.com/glpi-project/glpi/issues/877#issuecomment-240394638

**Comment by Zegordo** [comment]
we can compare our files "search.class.php" from 9.1 r2 glpi  for finding some differences

**Comment by Zegordo** [comment]
if  your glpi with my bd is working

**Comment by Zegordo** [comment]
this issue has 2 bugs
the second still exists

**Comment by tomolimo** [comment]
in fact two others:
#879 
and 
https://github.com/glpi-project/glpi/issues/877#issuecomment-240394638 that should be fixed by @orthagh

**Comment by Zegordo** [comment]
> #877 (comment) that should be fixed by @orthagh 

i allready have an `addtable2` in my files by default

**Comment by tomolimo** [comment]
that's the problem :)
this variable is NOT initialized, and then the table at the end is not found

**Comment by Zegordo** [comment]
could you send this search.class.php to here?

**Comment by tomolimo** [comment]
which?

**Comment by Zegordo** [comment]
glpi/inc/search.class.php

**Comment by tomolimo** [comment]
yes, but which one before fix or after fix?

**Comment by Zegordo** [comment]
after

**Comment by tomolimo** [comment]
just delete the 2 in the `addtable2` between the line https://github.com/glpi-project/glpi/commit/53c764f0d71ba7e3383ef79c5886393c33003c34#diff-a801c52129f44d50ab6d1db9f049c4b7R2345 and https://github.com/glpi-project/glpi/commit/53c764f0d71ba7e3383ef79c5886393c33003c34#diff-a801c52129f44d50ab6d1db9f049c4b7R2348

But as it has been added by @orthagh, I don't want to push a commit for that without knowing if this revert will have some other drawbacks.

**Comment by Zegordo** [comment]
including the lines too?

**Comment by tomolimo** [comment]
yes :smile_cat:

**Comment by Zegordo** [comment]
ohh god. deleting the `2` really helps :>
thanks a lot!

**Comment by orthagh** [comment]
i missed the specific licences numbers, all other case had a if (meta) else, this one not.
now, it's fixed
