### ISSUE TITLE
<i class='ma-icon ..> showing in Actions dropdown list

### ISSUE THREAD

**Issue by dxdemetriou** [glpi-project/glpi#8770]
GLPI upgraded from 9.5.3 to 9.5.4 and everything with class='ma-icon ..' is shown in drop-down list

![image](https://user-images.githubusercontent.com/41939421/110250821-264f2b80-7f86-11eb-855f-0a9c6dfa4bdf.png)

**Comment by flegastelois** [comment]
fixed #8767
