### ISSUE TITLE
Block task duration

### ISSUE THREAD

**Issue by Richard76000** [glpi-project/glpi#8775]
Is it possible to block the duration of tasks to a maximum? If so, is this also possible depending on the categories?

Example:
Remote intervention> 1h max
On-site intervention> 2h max

**Comment by cedric-anne** [comment]
Hi,

This feature does not exists in GLPI core. It may exists in a plugin but I never heard about this.

You may consider to discuss about this new feature with the community on our suggest website: https://suggest.glpi-project.org .

If you want to fund this feature, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us

Regards

**Comment by Richard76000** [comment]
I think this is not a new feature but an important bug. Why ? If a user A decides to schedule your task on another time slot, he or she has the option of extending the duration to 100h ???? Which is absurd.
Our mode of operation is: user A creates a ticket, technician B schedules the task over a period of one hour on a specific date.
This sends an email to user A. Then, user A has the possibility to modify the time slot of his scheduled intervention because he is not available on this date. Suddenly he has the possibility of modifying the task over a longer period than that which was planned.
