### ISSUE TITLE
CallDav Synchronization Root Entity

### ISSUE THREAD

**Issue by Richard76000** [glpi-project/glpi#8777]
Hello,

We encounter a big problem when we want to add a task in a specific entity: root entity> computer> cluster

We plan the task then we see the task appear in the planning.

When you do a CALLDAV synchronization with Outlook, the tasks do not synchronize.

On the other hand, if we create a task in the root entity, it is synchronized.

My question is: how do you synchronize the tasks from several specific entities and not just the root entity?

The schedule is in root entity + sub-entities so normally I should see all the tasks in Outlook.

**Comment by cedric-anne** [comment]
Duplicates #8657.
