### ISSUE TITLE
after update from 90.3 to 9.1 field description in tickets is empty

### ISSUE THREAD

**Issue by achekmez** [glpi-project/glpi#878]
after update from 90.3 to 9.1 field description in tickets is empty

**Comment by tomolimo** [comment]
???
**Could you give a _REAL_ description of the troubles?**
For that could you change the description of your post?
Thank you,
regards,
Tomolimo

**Comment by tomolimo** [comment]
Hello
Could you have a look into the log files?
Thank you,
Regards,
Tomolimo

**Comment by achekmez** [comment]
Hi, it seems nothing in logs exept cron.log - "Unable to get lock of the database" (or like this - i see it in russian). I can see text if I point to the "i" logo near Description and I can read it in "Processing ticket" tab, but not at Description Window. You can see it in attachment 
![glpi](https://cloud.githubusercontent.com/assets/21035924/17695739/b3636fee-63b2-11e6-9f94-43068bacb6d1.png)

**Comment by tomolimo** [comment]
Could you post the GLPi settings?
See: 
![image](https://cloud.githubusercontent.com/assets/7569958/17696760/d001e8da-63b0-11e6-8882-6cf27b53eeed.png)

**Comment by achekmez** [comment]
Information about system installation and configuration
[code]
 
GLPI 9.1 ( => /var/www/glpi_85.1)

Server
 
Operating system: Linux ZIPPO 3.2.0-4-686-pae #1 SMP Debian 3.2.63-2 i686
PHP 5.4.45-0+deb7u2 apache2handler (Core, PDO, PDO_Firebird, Phar, Reflection, SPL, SimpleXML, apache2handler, bcmath, bz2,
	calendar, ctype, curl, date, dba, dom, enchant, ereg, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imap,
	interbase, intl, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, session, shmop,
	snmp, soap, sockets, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.2.22 (Debian) (Apache/2.2.22 (Debian) Server at support.manpower.ru Port 80)
	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Server Software: (Debian)
	Server Version: 5.5.38-0+wheezy1
	Server SQL Mode: 
	Parameters: root@localhost/GLPI
	Host info: Localhost via UNIX socket
	
OK/var/www/glpi_85.1/config : OK
OK/var/www/glpi_85.1/files : OK
OK/var/www/glpi_85.1/files/_dumps : OK
OK/var/www/glpi_85.1/files/_sessions : OK
OK/var/www/glpi_85.1/files/_cron : OK
OK/var/www/glpi_85.1/files/_graphs : OK
OK/var/www/glpi_85.1/files/_lock : OK
OK/var/www/glpi_85.1/files/_plugins : OK
OK/var/www/glpi_85.1/files/_tmp : OK
OK/var/www/glpi_85.1/files/_rss : OK
OK/var/www/glpi_85.1/files/_uploads : OK
OK/var/www/glpi_85.1/files/_pictures : OK
OK/var/www/glpi_85.1/files/_log : OK

Libraries
 
htmLawed version 1.1.21 in (/var/www/glpi_85.1/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/glpi_85.1/vendor/jasig/phpcas/source)
PHPMailer version 5.2.16 in (/var/www/glpi_85.1/vendor/phpmailer/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/glpi_85.1/vendor/zetacomponents/graph/src): OK
Zend Framework in (/var/www/glpi_85.1/vendor/zendframework/zend-loader/src)
SimplePie version 1.4.1 in (/var/www/glpi_85.1/vendor/simplepie/simplepie/library)
TCPDF version 6.2.12 in (/var/www/glpi_85.1/vendor/tecnickcom/tcpdf)
ircmaxell/password-compat in (/var/www/glpi_85.1/vendor/ircmaxell/password-compat/lib). Compatitility: Ok
iacaml/autolink in (/var/www/glpi_85.1/vendor/iamcal/lib_autolink)
sabre/vobject in (/var/www/glpi_85.1/vendor/sabre/vobject/lib)
guzzlehttp/guzzle in ()

LDAP directories
 
Server: '172.16.10.33', Port: '389', BaseDN: 'DC=mpmsk, DC=corp', Connection filter:
		'(&(objectCategory=person)(objectClass=user))', RootDN: 'mpsadmin@mpmsk.corp', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@zoom.mpmsk.corp)

Mails receivers
 
Name: 'support@manpower.ru' Active: Yes
	Server: '{172.16.10.32:110/pop/validate-cert/notls}inbox' Login: 'mskadmin@mpmsk.corp' Password: Yes

Plugins list
 
	dashboard            Name: Панель состояния          Version: 0.6.9      State: Not activated
	formcreator          Name: Формы                          Version: 0.90-1.3.3 State: Not activated

[/code]
To copy/paste in your support request

**Comment by tomolimo** [comment]
Thank you,
Could you also look into the Apache log files to see if any errors are present?

**Comment by achekmez** [comment]
[error_support.txt](https://github.com/glpi-project/glpi/files/420163/error_support.txt)
it seems alot of errors ((((

**Comment by tomolimo** [comment]
then you may start by these, and when fixed, we may continue with GLPi issues

**Comment by achekmez** [comment]
[error_support.txt](https://github.com/glpi-project/glpi/files/420368/error_support.txt)
Could you please look a the file - all errors  looks like "[Tue Aug 16 13:51:38 2016] [crit] [client 172.16.7.24] (13)Permission denied: /var/www/glpi_85.1/lib/tiny_mce/plugins/fullscreen/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable, referer: http://support.manpower.ru/front/ticket.form.php?id=12737" so it seems it is GLPI connected problem and not Apache problem

**Comment by tomolimo** [comment]
@flegastelois: could you help, as I don't master Apache config?

**Comment by flegastelois** [comment]
Hi @achekmez ,

I hope your server is a test server, **GLPi 9.1 RC1** is a **RELEASE CANDIDATE** release, that should only be used on test sites.

According to this error "pcfg_openfile: unable to check htaccess file", I think you have too-strict file-system permissions on the GLPi directory (as shown by the (13)Permission denied part of the message).

Try to correct these permissions with **chown** (for example, www-data:root) and **chmod** (for example, 644 for files, 755 for directory).

Regards,

**Comment by ddurieux** [comment]
Seems you have a problem with the GLPI files installation because _lib/tiny_mce/plugins/fullscreen/.htaccess_ file not exist in archive / repository

**Comment by achekmez** [comment]
it does not exist, but where it should come from? in distributive - glpi-9.1RC2.tar.gz - there is no glpi/lib/tiny_mce/plugins/fullscreen/.htaccess file as well

**Comment by carvanders** [comment]
I had the same problem, in solution description. Solved by giving a chmod -R 755 and chmod -R a+x in glpi/**lib** folder. Don't know how this affect the security environment, but, it worked.

**Comment by flegastelois** [comment]
Hi,

It's better to apply 755 for folder en 644 for files (when your are in glpi directory) : 
# find . -type d -print0 | xargs -0 chmod 0775
# find . -type f -print0 | xargs -0 chmod 0664

Regards,

**Comment by achekmez** [comment]
Thanks ALOT it helped!
Thanks to you all guys!
