### ISSUE TITLE
"Hard drive Size" missing on the filter list

### ISSUE THREAD

**Issue by kocha9** [glpi-project/glpi#8789]
After upgrade to 9.5.4 i can not filter computers by "Hard Drive Size" because this parameter is not available on the filter list, But this parameter is visible as a column.
![GLPI Hard Drive Size Filter problem](https://user-images.githubusercontent.com/46989844/110445606-9791fa00-80be-11eb-92c5-8c135e009e58.png)

**Comment by cedric-anne** [comment]
Hi,

#8793 should fix this. Could you confirm ?

Regards

**Comment by kocha9** [comment]
Hi, #8793 fixed problem. Thank You
