### ISSUE TITLE
Wrong names of actions in action tab

### ISSUE THREAD

**Issue by kocha9** [glpi-project/glpi#8790]
After upgrade to 9.5.4 i see wrong actions names with tags like "<i class='ma-icon fas fa-plug'></i>Connect
![GLPI wrong Action names](https://user-images.githubusercontent.com/46989844/110446023-08d1ad00-80bf-11eb-92a9-800805a86f01.png)

**Comment by trasher** [comment]
This has already been reported and fixed

**Comment by flegastelois** [comment]
already fixed #8767
