### ISSUE TITLE
1 columns are not compatible with timezones usage -> glpi:migration:timestamps -> SQL Error "1932": Table 'glpi.glpi_notimportedemails' doesn't exist in engine

### ISSUE THREAD

**Issue by kocha9** [glpi-project/glpi#8791]
Can not convert glpi:migration:timestamps:
1 columns are not compatible with timezones usage.

bin/console glpi:migration:timestamps
Found 1 table(s) requiring migration.
Czy chcesz kontynuować ? [Yes/no]Yes
 1/1 [============================] 100%DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: ALTER TABLE `glpi_notimportedemails`
         MODIFY COLUMN `date` TIMESTAMP NOT NULL;

  Error: Table 'glpi.glpi_notimportedemails' doesn't exist in engine
  Backtrace :
  ...nsole/migration/timestampscommand.class.php:202
  vendor/symfony/console/Command/Command.php:255     Glpi\Console\Migration\TimestampsCommand->execute()
  vendor/symfony/console/Application.php:1000        Symfony\Component\Console\Command\Command->run()
  inc/console/application.class.php:249              Symfony\Component\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:271         Glpi\Console\Application->doRunCommand()
  vendor/symfony/console/Application.php:147         Symfony\Component\Console\Application->doRun()
  bin/console:102                                    Symfony\Component\Console\Application->run()
 SQL Error "1932": Table 'glpi.glpi_notimportedemails' doesn't exist in engine in query "ALTER TABLE `glpi_notimportedemails`
         MODIFY COLUMN `date` TIMESTAMP NOT NULL;
"
Update of `glpi_notimportedemails` failed with message "(1932) Table 'glpi.glpi_notimportedemails' doesn't exist in engine".
 1/1 [============================] 100%
Migracja zakónczona.

**Comment by cedric-anne** [comment]
Hi,

Please provide informations requested in https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.md .

Regards

**Comment by kocha9** [comment]
After upgrade from 9.4 to 9.5 you have to use timestamp data type https://glpi-install.readthedocs.io/en/latest/command-line.html
 
Many date fields were using the DATETIME type, but this does not allow to rely on timezones. Timezone support requires all fields to use TIMESTAMP data type, but this query can be very long and therefore is not included in the standard update process.

Using the glpi:migration:timestamps command will change those fields to the correct data type, but read documentation on timezones before.

**To reproduce**

1. Go to '/var/www/html/glpi
2. RUN bin/console glpi:migration:timestamps
3. See error like below:

_bin/console glpi:migration:timestamps
Found 1 table(s) requiring migration.
Czy chcesz kontynuować ? [Yes/no]Yes
1/1 [============================] 100%DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 309
*** MySQL query error:
SQL: ALTER TABLE glpi_notimportedemails
MODIFY COLUMN date TIMESTAMP NOT NULL;

Error: Table 'glpi.glpi_notimportedemails' doesn't exist in engine
Backtrace :
...nsole/migration/timestampscommand.class.php:202
vendor/symfony/console/Command/Command.php:255 Glpi\Console\Migration\TimestampsCommand->execute()
vendor/symfony/console/Application.php:1000 Symfony\Component\Console\Command\Command->run()
inc/console/application.class.php:249 Symfony\Component\Console\Application->doRunCommand()
vendor/symfony/console/Application.php:271 Glpi\Console\Application->doRunCommand()
vendor/symfony/console/Application.php:147 Symfony\Component\Console\Application->doRun()
bin/console:102 Symfony\Component\Console\Application->run()
SQL Error "1932": Table 'glpi.glpi_notimportedemails' doesn't exist in engine in query "ALTER TABLE glpi_notimportedemails
MODIFY COLUMN date TIMESTAMP NOT NULL;
"
Update of glpi_notimportedemails failed with message "(1932) Table 'glpi.glpi_notimportedemails' doesn't exist in engine".
1/1 [============================] 100%
Migracja zakónczona._

**Logs**
[sql-errors.log](https://github.com/glpi-project/glpi/files/6108200/sql-errors.log)

GLPI 9.5.4 ( => /var/www/html/glpi)
Installation mode: TARBALL


Operating system: Linux GLPI01 4.9.0-14-amd64 #1 SMP Debian 4.9.246-2 (2020-12-17) x86_64 PHP 7.3.27-9+0~20210227.82+debian9~1.gbpa4a3d6 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, 	apache2handler, apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, 	json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, 	standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at glpi.otcf.pl Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 Server Software: Debian 9.13 	Server Version: 10.1.48-MariaDB-0+deb9u1 	Server SQL Mode:  	Parameters: glpi@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.1.48) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to files directory is protected
--

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.4 GLPI_SCHEMA_VERSION: 9.5.4 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.3 in (/usr/share/php)

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot investigate without any feedback.

Regards

**Comment by orlandotnras** [comment]
Hello i have this problem too 
`SQL Error "1932": Table 'glpi933.glpi_notimportedemails' doesn't exist in engine in query "ALTER TABLE `glpi_notimportedemails`
         MODIFY COLUMN `date` TIMESTAMP NOT NULL;
"
Mise à jour de  `glpi_notimportedemails` échouée avec le message "(1932) Table 'glpi933.glpi_notimportedemails' doesn't exist in engine".
`

**Comment by orlandotnras** [comment]
Failed to SHOW CREATE TABLE `glpi_notimportedemails`
Error: Table 'glpi933.glpi_notimportedemails' doesn't exist in engine
