### ISSUE TITLE
[9.5.X] Mini dashboar does not show closed tickets in a large database

### ISSUE THREAD

**Issue by luisjosemachado** [glpi-project/glpi#8794]
**Describe the bug**

The mini dashboard does not show closed tickets in large database.

**To reproduce**

1. Use a large database of GLPI (In my case, > 200k registred tickets); 
2. Go to Assistence>Tickets menu.
3. In the ticket mini dashboard, see the erro in the closed tickets field.

**Expected behavior**
The mini dashboard shows the closed tickets field.

**Screenshots**

![Screenshot(3)](https://user-images.githubusercontent.com/30940056/110476451-c01af380-80c0-11eb-9116-84a682b70b0a.png)
211k registred tickets - ERROR

![Screenshot(1)](https://user-images.githubusercontent.com/30940056/110473055-dde65980-80bc-11eb-9c0b-3d1c832733d6.png)
11k registred tickets - OK

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

 GLPI 9.5.4 (/nti954 => /var/www/html/nti954) Installation mode: TARBALL
--

Operating system: Linux debian 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 PHP 7.3.19-1~deb10u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, 	bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, 	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at 192.168.100.64 Port 80) 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:86.0) Gecko/20100101 Firefox/86.0 Server Software: Debian 10 	Server Version: 10.3.27-MariaDB-0+deb10u1 	Server SQL Mode:  	Parameters: glpiuser@localhost/nti933 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.27) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/nti954/files/_cache has been validated. Write access to /var/www/html/nti954/config has been validated. Write access to /var/www/html/nti954/files/_cron has been validated. Write access to /var/www/html/nti954/files has been validated. Write access to /var/www/html/nti954/files/_dumps has been validated. Write access to /var/www/html/nti954/files/_graphs has been validated. Write access to /var/www/html/nti954/files/_lock has been validated. Write access to /var/www/html/nti954/files/_pictures has been validated. Write access to /var/www/html/nti954/files/_plugins has been validated. Write access to /var/www/html/nti954/files/_rss has been validated. Write access to /var/www/html/nti954/files/_sessions has been validated. Write access to /var/www/html/nti954/files/_tmp has been validated. Write access to /var/www/html/nti954/files/_uploads has been validated. Write access to /var/www/html/nti954/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/html/nti954 GLPI_CONFIG_DIR: /var/www/html/nti954/config GLPI_VAR_DIR: /var/www/html/nti954/files GLPI_MARKETPLACE_DIR: /var/www/html/nti954/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/nti954/files GLPI_CACHE_DIR: /var/www/html/nti954/files/_cache GLPI_CRON_DIR: /var/www/html/nti954/files/_cron GLPI_DUMP_DIR: /var/www/html/nti954/files/_dumps GLPI_GRAPH_DIR: /var/www/html/nti954/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/nti954/files/_locales GLPI_LOCK_DIR: /var/www/html/nti954/files/_lock GLPI_LOG_DIR: /var/www/html/nti954/files/_log GLPI_PICTURE_DIR: /var/www/html/nti954/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/nti954/files/_plugins GLPI_RSS_DIR: /var/www/html/nti954/files/_rss GLPI_SESSION_DIR: /var/www/html/nti954/files/_sessions GLPI_TMP_DIR: /var/www/html/nti954/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/nti954/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/nti954/locales GLPI_VERSION: 9.5.4 GLPI_SCHEMA_VERSION: 9.5.4 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/html/nti954/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/nti954/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/nti954/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/nti954/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/nti954/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/nti954/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/nti954/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/nti954/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/nti954/vendor/sabre/http/lib) sabre/uri in (/var/www/html/nti954/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/nti954/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/nti954/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/nti954/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/nti954/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/nti954/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/nti954/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/nti954/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/nti954/vendor/symfony/console) scssphp/scssphp in (/var/www/html/nti954/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/nti954/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/nti954/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/nti954/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/nti954/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/nti954/vendor/ramsey/uuid/src) psr/log in (/var/www/html/nti954/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/nti954/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/nti954/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/nti954/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/nti954/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/nti954/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/nti954/vendor/paragonie/sodium_compat/src) phpCas version 1.3.6 in (/usr/share/php/CAS/source)

Server: 'jfce.jus.br', Port: '389', BaseDN: 'dc=jfce,dc=jus,dc=br', Connection filter: 		'(&(objectCategory=person)(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'JFCE\autentica.ad', 		Use TLS: none Server: 'srvappv5.jfce.jus.br', Port: '389', BaseDN: 'ou=People,dc=jfce,dc=jus,dc=br', Connection filter: none, RootDN: 		'uid=samba,ou=People,dc=jfce,dc=jus,dc=br', Use TLS: none

Not active

Way of sending emails: SMTP (chamado.nti@mail.jfce.jus.br)

Name: 'chamado.nti@jfce.jus.br' Active: No 	Server: '{mail.jfce.jus.br/imap/novalidate-cert/notls}' Login: 'chamado.nti' Password: Yes

advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Error / to clean 	behaviors            Name: Behaviours                     Version: 2.4.1      State: Error / to clean 	escalade             Name: Escalation                     Version: 2.6.0      State: Error / to clean 	formcreator          Name: Form Creator                   Version: 2.11.0     State: Error / to clean 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Error / to clean 	mod                  Name: GLPI Modifications             Version: 2.0.1      State: Error / to clean 	moreticket           Name: More ticket                    Version: 1.6.1      State: Error / to clean 	dashboard            Name: Painel                         Version: 1.0.1      State: Error / to clean 	tag                  Name: Tag Management                 Version: 2.8.0      State: Error / to clean 	watermark            Name: Watermark                      Version: 1.0.0      State: Error / to clean

**Comment by cedric-anne** [comment]
Hi,

Do you have something in your GLPI logs or in your browser console related to this ?

Regards

**Comment by luisjosemachado** [comment]
Hi,
In php-errors.log:

piphplog.CRITICAL:   *** PHP Error (1): Allowed memory size of 134217728 bytes exhausted (tried to allocate 876544 bytes) in /var/www/html/nti954/inc/dbmysql.class.php at line 302
