### ISSUE TITLE
service mailgate blocked

### ISSUE THREAD

**Issue by Riesuu** [glpi-project/glpi#8796]
Hi
We have a problem with the mailgate service that remains "running". I have to force it and restart for the collector to work.
We have set up a cron with a boot every 1min. The problem is the same on GLPI 9.5.4

Bests regards.
[cron.log](https://github.com/glpi-project/glpi/files/6109155/cron.log)
[php-errors.log](https://github.com/glpi-project/glpi/files/6109156/php-errors.log)

**Comment by cedric-anne** [comment]
Hi,

I am pretty sure that it is related to #8795. Try to apply proposed fix and close this issue if problem disapear.

Regards

**Comment by Riesuu** [comment]
Actually it work!
many thanks!!

**Comment by Riesuu** [comment]
Hi, probleme is the same with the fix.

**Comment by cedric-anne** [comment]
Hi,

Please provide logs from the exact moment problem occurs (if any).

Regards

**Comment by Riesuu** [comment]
[php-errors.log](https://github.com/glpi-project/glpi/files/6116249/php-errors.log)


The problem appeared around 11:15, but the logs are truncated...

**Comment by cedric-anne** [comment]
Can you temporarly disable this automatic action, remove its running state, and then execute `php front/cron.php --debug --force mailgate && echo $?` from CLI (using the webserver user) ?

**Comment by Riesuu** [comment]
Done. But i have just the user root.
![image](https://user-images.githubusercontent.com/17006344/110640822-92fa3e00-81b1-11eb-8eec-1bb3e00373ab.png)

**Comment by Riesuu** [comment]
![image](https://user-images.githubusercontent.com/17006344/110647207-ebccd500-81b7-11eb-9755-b9f3024639f2.png)


Not yet, i will test tommorow or tonight.

![image](https://user-images.githubusercontent.com/17006344/110647275-fd15e180-81b7-11eb-839e-3cc5ddbb28ca.png)

**Comment by Riesuu** [comment]
HI,
the problem came back around 9am
i've just disable theses plugins:

- Alertes 1.8.2
- FormCreator 2.11.2
- Cycle de vie des materiels: 2.7.0
- -Data injection 2.9

**Comment by cedric-anne** [comment]
Hi,

Without any error trace, we cannot do anything more. Sorry.

Regards

**Comment by Riesuu** [comment]
Sorry !
[php-errors.log](https://github.com/glpi-project/glpi/files/6123169/php-errors.log)

**Comment by Riesuu** [comment]
Problem is back:

![image](https://user-images.githubusercontent.com/17006344/110804661-ad4f1d00-8280-11eb-9258-b10ab7f808e5.png)

[php-errors.log](https://github.com/glpi-project/glpi/files/6123754/php-errors.log)

**Comment by cedric-anne** [comment]
```
[2021-03-11 14:30:02] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/glpi/inc/commonitilobject.class.php at line 2708
  Backtrace :
  inc/itilfollowup.class.php:266                     CommonITILObject::isAllowedStatus()
  inc/commondbtm.class.php:1151                      ITILFollowup->post_addItem()
  inc/mailcollector.class.php:877                    CommonDBTM->add()
  inc/mailcollector.class.php:1746                   MailCollector->collect()
  inc/crontask.class.php:845                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
```

This problem has been fixed, see #8768

**Comment by Riesuu** [comment]
Thanks, i have apply fix #8768

**Comment by cedric-anne** [comment]
@Riesuu , does it fixes your issue ?

**Comment by Riesuu** [comment]
For the moment no problem for me

**Comment by cedric-anne** [comment]
I close the issue. Feel free to reopen if problem comes back.
