### ISSUE TITLE
Statistics Export to CSV , does not convert the stars

### ISSUE THREAD

**Issue by guillermohaad** [glpi-project/glpi#880]
Hi,
I have installed the version GLPI 0.90.3

when I export a report to CSV statistics, the Average Satisfaction does not convert the stars. Deputy evidence
![start average satisfaction](https://cloud.githubusercontent.com/assets/12921805/17739558/2bc95b1c-645b-11e6-94b0-212cd3f46356.png)

**Comment by orthagh** [comment]
Thank you for the report, the abovee commits shoud fix this issue.

**Comment by guillermohaad** [comment]
Thank you for responding quickly and fix the problem, you are great.
