### ISSUE TITLE
[GLPI 9.5.2] carriage return absent

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#8800]
Hello,
When a user sends a message for the creation of the ticket by mail  all is well.  Via GLPI pb of carriage return in the signature
However, when the user adds a follow-up by mail or via the GLPI interface and when he pastes his signature in the message, there is no longer a carriage return in his signature
The signature does contain \ r \ n format but it is not taken into account by GLPI.
I tried to modify notificationtargetcommonitilobject.class and ticket.class.php but without success.
See code ...
If you have an idea.
I do not know what to do. This concerns all users. Users do not see the traces because they are all to the right of the scroll bar. 

`ticket.class.php : ligne 1917  if (isset($input["content"])) {
         $input["content"] = preg_replace('/\\\\r\\\\n/', "\\n", $input['content']);
         $input["content"] = preg_replace('/\\\\n/', "\\n", $input['content']);`

`notificationtargetcommonitilobject.class ligne 770

      $data["content"] = preg_replace('/\\r\\n\\r\\n/', "<br>",  $item->getField('content')); //YD
      $data["content"] = preg_replace('/\n\n/', "<br/>", $data["content"]); //YD
      $data["content"] = preg_replace('/\n/', "<br/>", $data["content"]); //YD
      $data["content"] = preg_replace('/\\\\n/', "<br/>", $data["content"]); //YD
      $data["##$objettype.title##"]        = $item->getField('name');
      $data["##$objettype.content##"]      = $item->getField('content'); 
      $data["##$objettype.description##"]      = $data["content"]; //YD
      $data["##$objettype.id##"]           = sprintf("%07d", $item->getField("id"));
            
        
           $data["##$objettype.content##"]      = $item->getField('content'); 
           //$data["##$objettype.description##"]  = $item->getField('content');`

**Comment by cedric-anne** [comment]
Hi,

This is related to #8757.

Regards

**Comment by falco2001** [comment]
see https://github.com/falco2001/glpi/tree/patch-2 and https://github.com/falco2001/glpi/tree/patch-3
