### ISSUE TITLE
Notice: A non well formed numeric value encountered in \glpi\inc\dropdown.class.php on line 1554

### ISSUE THREAD

**Issue by gituncar** [glpi-project/glpi#8801]
![Untitled](https://user-images.githubusercontent.com/7705197/110506949-93210d80-80cd-11eb-90b9-ff0781d52921.png)

Hi, error on line 1554 (inc\dropdown.class.php) when access http

://localhost/glpi/front/computer.php

case 'auto':
		   
		$value = str_replace([' ', '&nbsp;'], ['', ''], $value); // unformat value
               return Toolbox::getSize($value*1024*1024);

maybe fix with
            $value = str_replace([' ', '&nbsp;', ','], ['', '', ''], $value); // unformat value

version:
GLPI 9.5.4 Copyright (C) 2015-2021 Teclib' and contributors
FusionInventory 9.5.0+1.0 - Copyleft © 2010-2019 by FusionInventory Team 

I have $values with comma (,), but I don't know whete &values get data on tables or array values. to clean.

**Comment by cedric-anne** [comment]
Hi,

Logs says that error is on line 1557 (`case '%'`) and your fix is related to another case, so maybe you have multiple issues.

Which columns are displayed in you search results ? Is there any column where you have an inconsistant value ? We may fix the rendering logic, but it could be also preferable to find and fix the source of malformed data.

Regards

**Comment by cedric-anne** [comment]
Hi,

I close this issue as we cannot investigate without any feedback.

Regards
