### ISSUE TITLE
[9.5.4] Ticket status does not change after receiving a response 

### ISSUE THREAD

**Issue by Socrate-MT** [glpi-project/glpi#8802]
**Describe the bug**

Hello,
Since the update of GLPI to version 9.5.4 (before we were in 9.5.1), responses from clients by email to tickets no longer modify the status of tickets (a mail collector is configured). Previously when the ticket was "Pending", it reverted to the "Processing (assigned)" state when a response was added.
Thank you in advance for your help. 

**Page(s) URL**

Tickets view.

**To reproduce**

1. Open a new ticket
2. Add your email address as an observer
3. Add a new task and set the status to "Pending"
4. Reply by email to this ticket
5. Go back to GLPI : the response has been taken into account but the status of the ticket has not changed

**Expected behavior**

When you reply to the ticket by email, the ticket should revert to "Processing (assigned)" state.

**Comment by RobertoMarcelino** [comment]
See #8768 .
