### ISSUE TITLE
GLPI 9.5.3 - buttons disappear in notes

### ISSUE THREAD

**Issue by CireSacud26** [glpi-project/glpi#8808]
Hello,

Display problem of the buttons in all the "notes" fields (equipment park or others) when the text zone is widened : 
![image](https://user-images.githubusercontent.com/73100577/110613268-5dddf380-8191-11eb-9771-b759eee41660.png)

Regards.

**Comment by cedric-anne** [comment]
Fixed in 4b936938fa0d4e4db5a61a0b74cdb3538399aaa4.
