### ISSUE TITLE
[9.5.4] Dropdown of locations and entities does not load data

### ISSUE THREAD

**Issue by xacobofg** [glpi-project/glpi#8817]
**Describe the bug**

When entering a user's page and trying to assign a location the dropdown does not show any data even though there are two locations created in that entity.
This error also occurs when trying to change the default entity.

**To reproduce**

1. Go to 'Administration > Users > user.form'
2. Click on 'Location' or 'Default entity'
3. See error

**Expected behavior**

The dropdown should show the locations available for assignment.

**Logs**

No log is generated

**Screenshots**

![imagen](https://user-images.githubusercontent.com/39123808/110768287-61d44900-8257-11eb-9029-c1e3c88cb851.png)
![imagen](https://user-images.githubusercontent.com/39123808/110768240-5719b400-8257-11eb-9b0f-80bc12bbdb90.png)
![imagen](https://user-images.githubusercontent.com/39123808/110768261-5bde6800-8257-11eb-839d-244e36d63f80.png)
![imagen](https://user-images.githubusercontent.com/39123808/110768308-67319380-8257-11eb-885d-22ea9bc01472.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.4 ( => /var/www/html/glpi)
Installation mode: TARBALL


Server
--
Operating system: Linux ticgal 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
PHP 7.3.19-1~deb10u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap,
	libxml, mbstring, memcached, msgpack, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets,
	sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="500M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at 172.25.0.188 Port 80)
	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.3
Server Software: Debian 10
	Server Version: 10.3.25-MariaDB-0+deb10u1
```

**Additional context**

In the last image you can see that another user does show me the list of available locations.
The only difference I can detect between one user and the other is that the one where the data is shown has the root entity assigned by default.
As discussed in issue #8806 this error may be caused by validateIDOR.
Because I did a test removing that function from the code and it worked correctly but I understand that this function is a security check so that solution is not valid.

**Comment by cedric-anne** [comment]
Hi,

Can you check in browser console if there is any JS error ?
Can you give us the response of the `ajax/getDropdownValue.php` request ?
Also, can you test with no active plugins ?

Regards

**Comment by xacobofg** [comment]
Hi.
The browser console does not return any errors.

This is the information of the request to `ajax/getDropdownValue.php`
```
** General **
Request URL: http://172.25.0.188/ajax/getDropdownValue.php
Request Method: POST
Status Code: 200 OK
Remote Address: 172.25.0.188:80
Referrer Policy: strict-origin-when-cross-origin

** Response Headers **
Cache-Control: no-store, no-cache, must-revalidate
Connection: Keep-Alive
Content-Length: 0
Content-Type: application/json; charset=UTF-8
Date: Fri, 12 Mar 2021 12:55:42 GMT
Expires: Mon, 26 Jul 1997 05:00:00 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.38 (Debian)

** Request Headers **
Accept: application/json, text/javascript, */*; q=0.01
Accept-Encoding: gzip, deflate
Accept-Language: es-ES,es;q=0.9
Connection: keep-alive
Content-Length: 862
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Cookie: glpi_3f946f74140a3178722cb675d5bf6b47=796ivfppb2vriupbfu5q4qd9ht; glpi_3f946f74140a3178722cb675d5bf6b47_rememberme=%5B4%2C%228bATcqQFdfUPYiTfgpVfR7goPkFcrIz8uqey97Ef%22%5D
Host: 172.25.0.188
Origin: http://172.25.0.188
Referer: http://172.25.0.188/front/user.form.php?id=88
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
X-Requested-With: XMLHttpRequest

** Form Data **
itemtype: Location
display_emptychoice: 1
emptylabel: -----
entity_restrict: ["27","21","8","15","23","26","36","37","38","41","40","11","42","43","44","45","46","47","48","49","50","51","52","53","60","123","54","55","56","57","58","59","62","61","68","72","33","75","148","94","95","103","152","114","122","129","205","155","172","178","190","226","235","237","234","69","20","4","132"]
permit_select_parent: 0
_idor_token: ff3df33a543de202d1f751faf0cd2ead3e238316fb486aa412a4c50fb107dd6d
page_limit: 100
page: 1
```
Returns an empty response

I tried with all plugins deactivated and it still does not work.

**Comment by cedric-anne** [comment]
Hi,

Can you test #8834 ?

Regards

**Comment by GuiGuiSoft** [comment]
Hello,
I had the same problem for some users (they were not able to change their default entity), and it seems to fix the issue.
Regards.

**Comment by xacobofg** [comment]
Hi @cedric-anne.
I test the fix and it solves the error.
