### ISSUE TITLE
[0.90.4 to 0.90.5] Different rights in tar archives

### ISSUE THREAD

**Issue by nqb** [glpi-project/glpi#882]
Hello,

During upgrade from 0.90.4 to 0.90.5, I notice different rights between tar archives. Rights in 0.90.5's archive are more restrictive (see attachment).
![rigths_between_0 90 4_and_0 90 5](https://cloud.githubusercontent.com/assets/10830260/17777622/7ad9181c-6561-11e6-9134-8280d28c9d27.png)

I will be nice to mention this point on release page.

**Comment by orthagh** [comment]
Hello @nqb .

Yes it's an error.
The next release will have (i hope) good permissions.
