### ISSUE TITLE
Incorrect HTML management for tickets containing "<" sign 

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#8822]
**Describe the bug**

GLPI email notifications contain not escaped "<" sign (probably not only this one) in their html code.
It seems to be 2 independent reasons:
  - tinymce always encodes "<" as "& lt ; " (without spaces) from html code tags or from submitted text 
  - send function in notificationeventmailing.class.php decodes content one more time (Html::entity_decode_deep) even if it is already decoded.

**To reproduce**

1A. create a new ticket from the GLPI web interface with the following content:
 
First line
The price should be <50 EUR
Last line

(or) 1B. Send an email to a collector with the same text

2. Take a look at mysql corresponding entry in glpi_tickets (same for itilfollowup)

3A. In 1A case, you can see that "<" is encoded as "& lt ;" (take care github replaces "& lt ;"  without spaces)
3B. In 1B case, you can see that "<" is encoded as "& amp ; lt ;" (take care github replaces "& amp ; lt ;"  without spaces) 

3B seems to be correct for me.

4. Read the HTML version of the notification email you received. Some mail clients will strip the end of the line containing "<".

5. Observe "<" sign in the middle of your email html source code

**Expected behavior**
Generate a correct HTML code for email notifications.

The issue is present in GLPI at least since 2015:
https://forum.glpi-project.org/viewtopic.php?id=47272

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug.

After a quick analysis, it cannot be fixed for input made from UI as long as #140 is not fixed.

Regards

**Comment by kabassanov** [comment]
Hi,

Thank for your reply. 

And what about this useless (I think) entity_decode_deep in notificationeventmailing.class.php ? When I disable it, at least messages coming from email collectors are displayed correctly.

**Comment by cedric-anne** [comment]
You may be right, I've not tested it.

You can propose a PR to fix this, but, as sent emails are not automatically tested, and as most GLPI core developpers have bad experiences related to side-effects of changes on these encoding/decoding operations, I cannot guarantee that it will be validated.

**Comment by kabassanov** [comment]
OK, I see. I did not find where DB entry is decoded upstream yet, but it seems that it is already done in the DB request result... So I wonder if it is not simply some old remaining code... Will keep you in touch.

**Comment by Kuba-Pawlak** [comment]
Confirm the bug. 
Similar problem with actions menu
![image](https://user-images.githubusercontent.com/68420967/110931605-c01e2c00-832a-11eb-9165-c7b424c8ebe5.png)

**Comment by Kuba-Pawlak** [comment]
Confirm the bug
Similar problem with action menu 
![image](https://user-images.githubusercontent.com/68420967/110931789-f65bab80-832a-11eb-89f1-74ba48c6a4eb.png)

**Comment by kabassanov** [comment]
Yes, I can see the same bug with the Action dropdown (in my case in French) from the last GLPI release... Didn't remark it before.

**Comment by trasher** [comment]
Actions menu bug is something else; its already been fixed; you can try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)).

As for the original issue, to me it's the same as #140; and this cannot be fixed without a huge rewrite because of choice made years ago. I close as duplicate.

**Comment by Kuba-Pawlak** [comment]
What does it means? It will be fixed or not? Previous version of GLPI was waorking correctly according email address html decode.

**Comment by kabassanov** [comment]
@Kuba-Pawlak :Which issue are you talking about?

@trasher: is there a place we could talk about the double decode issue? I don't realize why (and when) this operation could be useful...

**Comment by Kuba-Pawlak** [comment]
I mean correctly email decoding.
