### ISSUE TITLE
see all project tasks (090.1-090.5)

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#883]
Good day.

There is a way you can see all project tasks generally (without being associated with them).

![image](https://cloud.githubusercontent.com/assets/16838689/17779589/cbed911c-652d-11e6-9f07-76b93a3f9ed5.png)

Story with super-admin profile but not allow me to see them all or give that privilege by default to a profile manager for all projects.

Cordially,

**Comment by orthagh** [comment]
> There is a way you can see all project tasks generally (without being associated with them).
This icon is called "My tasks", so it's intended to displays associated ones.

We currently don't have any screen who permit to show all tasks (associated or not) outside of projects screen.

**Comment by virginiacorrea** [comment]
Thanks for your reply.

If it seems important to this option (see all tasks) to generate general reports.

Similarly it would be important (perhaps) that the group assigned to the task can also view the tasks of their group.

Anteior what it is not very functional that have per-user add each task you can display all or some.

Anyway thank you very much for your attention.

**Comment by orthagh** [comment]
Should be ok with new global kanban view (https://github.com/glpi-project/glpi/commit/e2ad88942e9076350f3c498365f68b51ccb76055#diff-83c4330c8425d6f2e528d6916fd55f18ed0dc034a6296cda609d0189db457308)
