### ISSUE TITLE
DropdownUser return no data when restrict response on multiple entities.

### ISSUE THREAD

**Issue by blink38** [glpi-project/glpi#8832]
**Describe the bug**

When creating a question in formCreator of type "GLPI Object" > Administration - User, if my Form use sub-entities, then the getDropdownUsers.php failed.

It's not a formCreator problem because, as explain later, the problem is in session.class.php or dropdown.class.php.

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Create a form with formCreator plugin. You have to set "sub-entity" to true.
You also have to select an entity which contains sub-entity.
![image](https://user-images.githubusercontent.com/1789267/110978263-700f8b80-8363-11eb-8399-79e09db14274.png)

2. Add a question of type "GLPI Object"  and GLPI Object = Administration - Users

![image](https://user-images.githubusercontent.com/1789267/110977794-de078300-8362-11eb-82c7-95e322301c6c.png)

3. Save and check users list is not empty
4. See error : empty list
![image](https://user-images.githubusercontent.com/1789267/110977951-0d1df480-8363-11eb-8193-d66e2f06831b.png)

**Expected behavior**

I expect the user list not to be empty. When working :
![image](https://user-images.githubusercontent.com/1789267/110978082-3d659300-8363-11eb-8093-0e72d028a934.png)

**Screenshots**

When debugging, I find the problem is on the POST parameter **entity_restrict**. 

In **session.class.php** 
From screenshot, you can note that $given['entity_restrict'] and $expected['entity_restrict'] dot not have same values. $given contains data from $_POST. Slashes are added to quote mark.
validateIDOR will failed and getDropdownUsers() (**dropdown.class.php**) will return without returning data.

![image](https://user-images.githubusercontent.com/1789267/110979563-0a240380-8365-11eb-8143-6a6689183f44.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI_VERSION: 9.5.4
```

**Additional context**

Adding stripslashes call before validateIDOR resolve the problem, but not sure it's a good thing : 
 ```
public static function getDropdownUsers($post, $json = true) {
      global $CFG_GLPI;

      $post['entity_restrict'] = stripslashes($post['entity_restrict']);

      // check if asked itemtype is the one originaly requested by the form
      if (!Session::validateIDOR($post + ['itemtype' => 'User', 'right' => ($post['right'] ?? "")])) {
         return;
      }
```

**Comment by OscarBeiro** [comment]
Looks like #8817

**Comment by btry** [comment]
Hi

@blink38  I had recently a report similar to yours.

I found there is a problem in a small portion of code in GLPI, but this problem should not trigger because Formcreator enabled recursion on dropdowns when it should not. Then, the bug is more in Formcreator than GLPI for now.

I suggest you use this fix for the plugin : https://github.com/pluginsGLPI/formcreator/pull/2164

**Comment by cedric-anne** [comment]
Hi,

Can you test 8834 ?

Regards

**Comment by cedric-anne** [comment]
Duplicates #8817.

**Comment by blink38** [comment]
I tested #8834 (https://github.com/glpi-project/glpi/pull/8834/files) and it resolved the current problem.
