### ISSUE TITLE
Issue to update from 9.5.3 to 9.5.4 on Windows Server 2012 R2 using IIS

### ISSUE THREAD

**Issue by DEUS-X9** [glpi-project/glpi#8835]
**Describe the bug**

When I try to update GLPI 9.5.3 to 9.5.4 on Windows Server 2012 R2 I get this error : 
```
Application dependencies are not up to date.
Run "php bin/console dependencies install" in the glpi tree to fix this.
```
So I tried this commande line in the CMD and I get this : 
![image](https://user-images.githubusercontent.com/33145849/111139367-55b2f900-8581-11eb-9384-768e093d3994.png)

I also tried to update php to 8.0.3 but nothing happened

I think something is missing in the archive 

**Page(s) URL**

Every page on the local glpi

**To reproduce**

1. Try to install glpi on windows server 2012 R2 using IIS  repertory C:\inetpub\glpi\extract the archive here
2. open a web browser 
3. see the error

**Expected behavior**

To open glpi/install/install.php correctly so I can update glpi

**Logs**

```
Logs are empty
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
default install setup
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

I guess you downloaded the source code of the release. Try with the compiled sources (the glpi-9.5.4.tgz
 file), and it should work.

Regards

**Comment by DEUS-X9** [comment]
That was it, thank you and sorry I just downloaded the .zip file by habit
