### ISSUE TITLE
Can`t remove domain

### ISSUE THREAD

**Issue by antoxa9898** [glpi-project/glpi#8840]
Hello. In GLPI 9.5.4 there is no Put in Trashbun button in domain actions. So it is not possible to remove domains
URL- glpi.domain/glpi/front/domain.php
![image](https://user-images.githubusercontent.com/54843009/111317228-0221d780-8675-11eb-935e-e1fe326f6f03.png)

**Comment by trasher** [comment]
Please double check profiles ACLs

**Comment by antoxa9898** [comment]
oh, thank you very much! it`s strange that it was not allowed for super-admin profile by default
