### ISSUE TITLE
[9.5.4] Problem adding an ethernet or alias port on Devices

### ISSUE THREAD

**Issue by RobertoMarcelino** [glpi-project/glpi#8845]
Do not add alias port on Devices, sending to a blank page.

![image](https://user-images.githubusercontent.com/57845086/111520040-78d2d980-8736-11eb-818c-72250ceed58c.png)

![image](https://user-images.githubusercontent.com/57845086/111520184-9ef87980-8736-11eb-8e24-cc2d743c39bc.png)

**Comment by cedric-anne** [comment]
Hi,

I just tried and I did not reproduced on current state of 9.5/bugfixes branch.

Can you, please, fill **ALL** informations requested in [issue form](https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.md) ? Maybe it could help us to reproduce (and that is why we ask for them, by the way).

Regards

**Comment by RobertoMarcelino** [comment]
The inc/toolbox.class.php file was corrupted.

I fixed it and the problem was over.

Big hugs!
