### ISSUE TITLE
plugins fields

### ISSUE THREAD

**Issue by guillermohaad** [glpi-project/glpi#885]
Hi Friends, 
how's it going over there?

I have a question about of plugins fields?

as you could save multiple tabs custom fields. This would add more not save?

example:

have multiple records of the same tabs such as a button New Register
![campos personalizados](https://cloud.githubusercontent.com/assets/12921805/17810757/a4d60e80-65e4-11e6-8fa3-9c8a2884c000.png)

**Comment by orthagh** [comment]
Hello @guillermohaad , please open issue for plugin fields in its dedicated bugtracker : https://github.com/pluginsGLPI/fields/issues

Here, it's for the glpi core issues.
