### ISSUE TITLE
 GLPI 9.5.4 - Action list appears with wrong text with html codes.

### ISSUE THREAD

**Issue by danielmjmarques** [glpi-project/glpi#8856]
If you select a ticket and click on the actions button, you will see that the list that appears in the dropdown list has codes coming from the html and does not contain only the text. This started to happen in the version of glpi 9.5.4, in the previous version it didn't happen. I did a clean installation and the problem also occurred.
![glpi](https://user-images.githubusercontent.com/33032935/111847173-0d7c3980-88e7-11eb-828b-221fe2f35b66.png)

**Comment by trasher** [comment]
Already reported several times, and fixed for next bugfixes version.
