### ISSUE TITLE
Unable to pick values from dropdowns [9.5.4]

### ISSUE THREAD

**Issue by mklimasz5** [glpi-project/glpi#8859]
**Describe the bug**

After upgrading to 9.5.4 the following behavior is observed: When in any asset, filtering is not offering predefined values (e.g.: selecting filter item "Status" and method "is", "is not", "under" or "not under" - should display list of items to choose from). Any selectable (dropdown) type of item is affected the same way. This behavior is only observed if a final Entity is chosen (no "(tree structure)" in a selected context) - after selecting the Entities with "(tree structure)" everything returns to normal. Filtering by "contains" or "does not contain" methods works just right. Disabling all plugins doesn't change the behavior - issue still exists. The same problem has been observed on two independent instances (both running 9.5.4), and did not exist in 9.5.3.

**Page(s) URL**

/front/computer.php (example, all asset categories are affected the same way)

**To reproduce**

1. Select any final (NOT "tree structure") Entity for a working context / appropriate profile 
2. Enter into Assets (any category)
3. Try defining filtering: field "Status", method "is", try selecting the values
4. Result: "The results could not be loaded."

**Expected behavior**

Values available for choice when selecting "is", "is not", "under" or "not under" methods; selection from expected dropdown should be shown.

**Logs**

No error is thrown into \files\_log\php-errors.log, \files\_log\sql-errors.log neither Apache logs (access.log and error.log).

**Screenshots**

![image](https://user-images.githubusercontent.com/41328086/111969334-696adc00-8afa-11eb-901a-4ae6cb394136.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.4 ( => /var/www/html)
Installation mode: TARBALL

Server
 
Operating system: Linux xxxxxxxxxx 3.10.0-1062.9.1.el7.x86_64 #1 SMP Mon Dec 2 08:31:54 EST 2019 x86_64
PHP 7.4.9 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, ctype,
	curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, soap, sockets, sodium, sqlite3, standard, sysvmsg,
	sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/7.4.9 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.4.10-MariaDB
	Server SQL Mode: 
	Parameters: xxxxxxxx@localhost/xxxxxxx
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is not presentCAS extension is not present
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.4.10) - Perfect!Database version seems correct (10.4.10) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/html/files/_cache has been validated.Write access to /var/www/html/files/_cache has been validated.
Write access to /var/www/html/config has been validated.Write access to /var/www/html/config has been validated.
Write access to /var/www/html/files/_cron has been validated.Write access to /var/www/html/files/_cron has been validated.
Write access to /var/www/html/files has been validated.Write access to /var/www/html/files has been validated.
Write access to /var/www/html/files/_dumps has been validated.Write access to /var/www/html/files/_dumps has been validated.
Write access to /var/www/html/files/_graphs has been validated.Write access to /var/www/html/files/_graphs has been validated.
Write access to /var/www/html/files/_lock has been validated.Write access to /var/www/html/files/_lock has been validated.
Write access to /var/www/html/files/_pictures has been validated.Write access to /var/www/html/files/_pictures has been validated.
Write access to /var/www/html/files/_plugins has been validated.Write access to /var/www/html/files/_plugins has been validated.
Write access to /var/www/html/files/_rss has been validated.Write access to /var/www/html/files/_rss has been validated.
Write access to /var/www/html/files/_sessions has been validated.Write access to /var/www/html/files/_sessions has been validated.
Write access to /var/www/html/files/_tmp has been validated.Write access to /var/www/html/files/_tmp has been validated.
Write access to /var/www/html/files/_uploads has been validated.Write access to /var/www/html/files/_uploads has been validated.
Write access to /var/www/html/marketplace has been validated.Write access to /var/www/html/marketplace has been validated.
Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.Web access to the files directory should not be allowed
Check the .htaccess file and the web server configuration.
For security reasons, SELinux mode should be Enforcing.For security reasons, SELinux mode should be Enforcing.

GLPI constants
 
GLPI_ROOT: /var/www/html
GLPI_CONFIG_DIR: /var/www/html/config
GLPI_VAR_DIR: /var/www/html/files
GLPI_MARKETPLACE_DIR: /var/www/html/marketplace
GLPI_USE_CSRF_CHECK: 1
GLPI_CSRF_EXPIRES: 7200
GLPI_CSRF_MAX_TOKENS: 100
GLPI_USE_IDOR_CHECK: 1
GLPI_IDOR_EXPIRES: 7200
GLPI_ALLOW_IFRAME_IN_RICH_TEXT: 
GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org
GLPI_INSTALL_MODE: TARBALL
GLPI_NETWORK_MAIL: glpi@teclib.com
GLPI_NETWORK_SERVICES: https://services.glpi-network.com
GLPI_MARKETPLACE_PRERELEASES: 
GLPI_USER_AGENT_EXTRA_COMMENTS: 
GLPI_AJAX_DASHBOARD: 1
GLPI_CALDAV_IMPORT_STATE: 0
GLPI_DEMO_MODE: 0
GLPI_FORCE_EMPTY_SQL_MODE: 1
GLPI_DOC_DIR: /var/www/html/files
GLPI_CACHE_DIR: /var/www/html/files/_cache
GLPI_CRON_DIR: /var/www/html/files/_cron
GLPI_DUMP_DIR: /var/www/html/files/_dumps
GLPI_GRAPH_DIR: /var/www/html/files/_graphs
GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales
GLPI_LOCK_DIR: /var/www/html/files/_lock
GLPI_LOG_DIR: /var/www/html/files/_log
GLPI_PICTURE_DIR: /var/www/html/files/_pictures
GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins
GLPI_RSS_DIR: /var/www/html/files/_rss
GLPI_SESSION_DIR: /var/www/html/files/_sessions
GLPI_TMP_DIR: /var/www/html/files/_tmp
GLPI_UPLOAD_DIR: /var/www/html/files/_uploads
GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/
GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/
GLPI_I18N_DIR: /var/www/html/locales
GLPI_VERSION: 9.5.4
GLPI_SCHEMA_VERSION: 9.5.4
GLPI_MIN_PHP: 7.2.0
GLPI_YEAR: 2021

Libraries
 
htmlawed/htmlawed version 1.2.5 in (/var/www/html/vendor/htmlawed/htmlawed)
phpmailer/phpmailer version 6.1.6 in (/var/www/html/vendor/phpmailer/phpmailer/src)
simplepie/simplepie version 1.5.6 in (/var/www/html/vendor/simplepie/simplepie/library)
tecnickcom/tcpdf version 6.3.5 in (/var/www/html/vendor/tecnickcom/tcpdf)
michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf)
true/punycode in (/var/www/html/vendor/true/punycode/src)
iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink)
sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV)
sabre/http in (/var/www/html/vendor/sabre/http/lib)
sabre/uri in (/var/www/html/vendor/sabre/uri/lib)
sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib)
laminas/laminas-cache in (/var/www/html/vendor/laminas/laminas-cache/src)
laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src)
laminas/laminas-serializer in (/var/www/html/vendor/laminas/laminas-serializer/src)
monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog)
sebastian/diff in (/var/www/html/vendor/sebastian/diff/src)
elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src)
symfony/console in (/var/www/html/vendor/symfony/console)
scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src)
laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol)
laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src)
rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src)
blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php)
ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src)
psr/log in (/var/www/html/vendor/psr/log/Psr/Log)
psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src)
mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors)
guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src)
guzzlehttp/psr7 in (/var/www/html/vendor/guzzlehttp/psr7/src)
wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src)
paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src)

LDAP directories
 
Server: 'xxxxxxxxx', Port: '389', BaseDN: 'DC=xxxx,dc=xxxx,dc=xxxx', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=xxxxxxx,OU=xxxx,OU=xxxx,OU=xxxx,OU=xxxx,DC=xxxx,dc=xxxx,dc=xxxx', Use TLS: none

SQL replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (xxxxxxxx@xxxxxxxx)

Mails receivers
 
Plugins list
 
	datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.11.2     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5+2.0    State: Enabled
	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled
	genericobject        Name: Objects management             Version: 2.10.0     State: Enabled
	phpsaml              Name: PHP SAML                       Version: 0          State: Enabled
	pdf                  Name: Print to pdf                   Version: 2.0.0      State: Enabled
 
**Additional context**

None

**Comment by cedric-anne** [comment]
Hi,

Couyld you test with #8834 ?

Regards

**Comment by mklimasz5** [comment]
Tested and found working! :) Thanks Cedric-Anne 👍
