### ISSUE TITLE
API config for IIS

### ISSUE THREAD

**Issue by tyronewyatt** [glpi-project/glpi#886]
Hello GLPI DEVs,

It's come to my attention that REST API for 9.1 RC1/2 requires mod_rewrite and the config currently only supports Apache but we use IIS in our production sites.
Since GLPI's githib main page says that the web server prerequisites are Apache, Nginx and IIS I thought I would create an issue for this.
Converting the Apache .htaccess file to a IIS web.config is fairly straight forward and an example can be found here https://blogs.msdn.microsoft.com/azureossds/2015/04/23/converting-apache-htaccess-rules-to-iis-web-config-using-iis-manager-for-azure-websites/
Luckily web.config files behave similar to .htaccess files and you can have one web.config file per folder/sub folder. 
Can we please extend any web.config to include the other .htaccess in folders you wish to block access to such as ./files/.htaccess (deny from all).
A similar issue has ready been logged for Web server Nginx https://github.com/glpi-project/glpi/issues/881 
Don't hesitate to contact me if you would like to test the web.configs

Regards,
Tyrone Wyatt.

**Comment by orthagh** [comment]
hello @tyronewyatt 

You're right, current api url was tested with the couple apache+mod_rewrite.
I don't have any experience with rewrite rules for iis, maybe @tomolimo could help here ?

I just provided an example for nginx (see https://github.com/glpi-project/glpi/blob/master/apirest.md#nginx), complete the documentation with iis could be great.
In fact, it need to describe a redirection to work: 

/api(.*) -> /apirest.php$1

The server var PATH_INFO need also to be filled (it was kind of tricky to achieve on nginx)

**Comment by tomolimo** [comment]
Hello,
There is a wizard to import Apache mod_rewrite rules into IIS :)
And online doc: http://www.iis.net/learn/extensions/url-rewrite-module/importing-apache-modrewrite-rules?amp;clcid=0x409
When I'll have time to test, I'll provide rules for IIS, or may be @tyronewyatt 
regards,
Tomolimo

**Comment by trasher** [comment]
Hello

Some changes have been made on the code, and this is no longer required to use rewrite rules to access the API.

You can still add rules for rewriting on your own if you wish; but you can call the api directly from the .php file :)
