### ISSUE TITLE
Impossible to create an entity

### ISSUE THREAD

**Issue by Riesuu** [glpi-project/glpi#8865]
Hi,
I want to create an entity on GLPI 9.5.4. By clicking on "+", I arrive on the page /front/entity.form.php to edit the main entity.
[php-errors.log](https://github.com/glpi-project/glpi/files/6189348/php-errors.log)

Bests regards.

**Comment by trasher** [comment]
This issue has already been reported several times, and has been fixed.

**Comment by cedric-anne** [comment]
See #8747
