### ISSUE TITLE
[9.5.3] API - Error using PUT method for Satisfaction

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#8869]
**Describe the bug**

We have the API configuration with "Enable login with external token" and when try to send a satisfaction using API, we get a permission error (GET method works well).

**To reproduce**

Configure Postman with app and user tokens and configure PUT method

![image](https://user-images.githubusercontent.com/43515938/112308505-1fb8f780-8c9a-11eb-8bf1-8966d421b0d9.png)

**Expected behavior**

PUT method should work as expected.

Looking at the source code we managed to get a solution, changing the return value of "canUpdateItem()" in ticketsatisfaction.class.php from FALSE to TRUE.

![image](https://user-images.githubusercontent.com/43515938/112309161-f056ba80-8c9a-11eb-8d0a-5178e55e708f.png)

We believe the problem relies on the latest IF that is searching for permissions, but it seems to us that is not searching for permissions when using API.

Another (possible) solution is to add the API user as an actor of the ticket, but this doesn't look like a good solution to us...
This works because the first line of the latest IF is searching for requester:

$ticket->isUser(CommonITILActor::REQUESTER, Session::getLoginUserID())

We don't know if we can add a new requester to the ticket using API (we haven't tried it yet).

**Comment by cedric-anne** [comment]
Hi,

If your user have many profiles, the API will use the default profile of your user, or the first found if the default one is not set. So maybe the profile used by the API has no rights for this.

Can you check ?

Regards

**Comment by andrepetinga** [comment]
Hello.
In our Production environment it is set to "Super-Admin"

![image](https://user-images.githubusercontent.com/43515938/112328922-a8419300-8cae-11eb-8d3c-1afd96d0d93f.png)

**Comment by andrepetinga** [comment]
We also have a plugin (developed internally) that syncs tickets between GLPI and our Intranet (bidirectional) and the programmer warned me that, in order to make it work, he had to add this API user as a requester in every ticket.
So maybe it is a related problem... Something to do with API user privileges, but we don't know what are the exact settings for this user, to make it work.

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support; this does not sounds a GLPI bug but rather a misconfiguration
