### ISSUE TITLE
ticket status is blocked due to the CRON Mailgate /!\

### ISSUE THREAD

**Issue by stdglpi** [glpi-project/glpi#8873]
### **Sum up**

After updating GLPI 9.5.3 to 9.5.4 we have noticed a serious problem. 

Each time the support answer to the ticket we pass it into the pending status.
Once the customer is responding the status doesn't change...

Also if you use the "solution" mode and the client respond, the ticket is stuck on solved and you will probably miss it.

If **_you stop the automatic action for the mail gate and you force manualy the collector to collect the emails the phenomenon does not occur._**

For the moment we pass on manually mode.

**_I tested on linux server and on a windows server = same result._**

### **Screenshots**

See that we pass the ticket on "pending" after you can see a new followup then we force to pass on "In progress" to show the problem.
![image](https://user-images.githubusercontent.com/63521311/112547662-53d80980-8dbb-11eb-8b9b-1d30d056b30c.png)

### **To reproduce**

1. Update to 9.5.4
2. CRON is configured and "mailgate" on mode "CLI"
3. Open a ticket and change the status
4. Add a followup by email with the collector

### **Expected behavior**

Automatic actions with the CRON has to back to normal.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

![image](https://user-images.githubusercontent.com/63521311/112550229-5a688000-8dbf-11eb-90b8-8047e2eb2134.png)

### **Additional context**

Plugins : formcreator, tag

**Comment by cedric-anne** [comment]
Hi,

#8773 should fix this issue. Feel free to reopen if problem persist.

Regards
