### ISSUE TITLE
Access to timezone database (mysql) is not allowed.

### ISSUE THREAD

**Issue by StbanMc** [glpi-project/glpi#8874]
Dear GLPI.

I have problems with the execution of automatic actions, this is because I cannot adjust the regional zone of mysql because it is a shared hosting.

I followed what was suggested in the forum:
https://forum.glpi-project.org/viewtopic.php?id=278919

The GLPI team.
-->

**Describe the bug**

The dates of the automatic tasks are creating a future execution date due to the regional zone difference which I cannot modify or adjust because it is a shared hosting. This causes automatic actions and queued messages to be queued

**Page(s) URL**

glpi/front/crontask.php

**To reproduce**

1. Go to task
2. Click on name
3. Scroll down to frist task
4. See datetime

**Expected behavior**

Future Date
![image](https://user-images.githubusercontent.com/40925832/112574776-02c91500-8dbd-11eb-9ca3-be1036482452.png)

**Additional context**

time_zone 'America/Bogota'

**Comment by cedric-anne** [comment]
Hi,

There is no relation between tilmezone and cron task state. If a non running task is marked as "Running", it means that an error occurs during its execution. Check the logs to see if there is something related to this.

Without logs, we cannot do anything.

Regards

**Comment by trasher** [comment]
There is no bug here; I close this one, feel free to open a new issue with all related information required in issue template.
