### ISSUE TITLE
Affichage incorrect du nombre de logiciels

### ISSUE THREAD

**Issue by mdubois-jst** [glpi-project/glpi#8877]
**Describe the bug**

En regardant à l'intérieur d'une fiche de poste, je constate que la catégorie "Logiciels" indique un nombre incorrect. Comme vous pouvez le voir sur la capture ci-dessous, il est indiqué 103823 **(1)**.

En observant plus en détail dans la section d'affichage des logiciels (nom, version, etc) il en est indiqué 169 comme sur la capture ci-dessous **(2)**.

Il y a donc un problème d'affichage dans le bouton dans la colonne de gauche.

**Screenshots**

**(1)** : ![image](https://user-images.githubusercontent.com/77621125/112608274-6e8d9b00-8e1a-11eb-9a08-9926183e8feb.png)

**(2)** : ![image](https://user-images.githubusercontent.com/77621125/112608518-b57b9080-8e1a-11eb-90ec-7b049e9a3783.png)

**Comment by cedric-anne** [comment]
Fixed by #8779.
