### ISSUE TITLE
Connection to the database failed in the install wizard because of the password characters

### ISSUE THREAD

**Issue by Fonfon02** [glpi-project/glpi#8880]
**Describe the bug**

During the installation wizard, if your database password has an % in it. It will fail the connection to the db.

**Page(s) URL**

https://example.com/install/install.php

**To reproduce**

1. Create a user in your future GLPI database (MariaDB in my case) and assign him a password with the % character in it.
2. Go through the install wizard and fill the form to establish a connection to your database.
3. See the error.

**Expected behavior**

I was able to connect to my database using a shell command and using the same credentials that I used in the wizard.

So it should works.

**Idea of the origin of the problem**

I looked for the origin of the problem, so I checked your install.php file and I found this line in it:
https://github.com/glpi-project/glpi/blob/5c114419c9a35d448f2222d4dae10ca4cc1a5fa8/install/install.php#L353

I found out more information about the rawurlencode php function:
  - www.php.net/manual/en/function.rawurlencode.php

So, if I understood correctly, the password is impacted by the rawurlencode function and when PHP tries to make the connection to the db it sends a wrong password.

**Work around solution**

I removed the % character in my database password and it works as expected.

**Comment by cedric-anne** [comment]
Hi,

I confirm the bug. Problem occurs when `%` and following chars corresponds to a valid URL-encodede char (i.e. `%20`).

This is due to this piece of code :
```php
   if (isset($_POST["db_pass"])) {
      $_POST["db_pass"] = stripslashes($_POST["db_pass"]);
      $_POST["db_pass"] = rawurldecode($_POST["db_pass"]);
      $_POST["db_pass"] = stripslashes($_POST["db_pass"]);
   }
```

According to code history, this has been done to handle `$` char in passwords.

Regards

**Comment by Fonfon02** [comment]
Nice thanks! 👍🏻

**Comment by Fonfon02** [comment]
Sorry for closing the issue, bad handling...
Thanks for your response.
