### ISSUE TITLE
[GLPI 9.5.4] : assistance ticket: the "calendar button" is no longer displayed in the search criteria if you click on it

### ISSUE THREAD

**Issue by steph461** [glpi-project/glpi#8884]
1. Go to ' assistance tickets'
2. look my image for description
![calendar](https://user-images.githubusercontent.com/68054991/112808296-202a0780-9079-11eb-9d8c-820e41c17024.png)
cannot click on button

3. For resolve my issue, I inform manually

is it a bug ?

**Comment by steph461** [comment]
for most information :
the bug is reproduced on all tabs with this button
example : planning and other whith this button calandar

**Comment by cedric-anne** [comment]
Hi,

Which browser do you use ?

Regards

**Comment by steph461** [comment]
Chrome /89.0.4389.90

**Comment by cedric-anne** [comment]
Can you look into your browser console to see if there is any error ?

**Comment by trasher** [comment]
Also, make sure to clean caches (restart php, empty files/_cache directory, ensure to login/logout, and ensure there is no plugins loaded (you should have mentionned that in your initial ticket, this is asked among others in the issue template). Also clean your browser cache.

**Comment by steph461** [comment]
Clean_Cache GLpi OK
Clean cache Browser chromium ( chrome and edge) OK
it's ok thx  , it was the cache that was the problem

thank you

I close the ticket
