### ISSUE TITLE
How add the new devices [1] by default?  (question)

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#889]
Hello!

In computers -> components we have to add the new devices.
By default, the number for adding the new devices is 0.
http://imgur.com/a/QJR0j
So, please tell me, how to change from default 0 to default 1 for every new device add?

**Comment by cedric-anne** [comment]
Hi,

You can change it by applying this modification:
```diff
diff --git a/ajax/selectUnaffectedOrNewItem_Device.php b/ajax/selectUnaffectedOrNewItem_Device.php
index 386d47f3e..8a4585c16 100644
--- a/ajax/selectUnaffectedOrNewItem_Device.php
+++ b/ajax/selectUnaffectedOrNewItem_Device.php
@@ -83,7 +83,7 @@ if ($_POST['items_id']
       dropdown::showFromArray($linktype::getForeignKeyField(), $devices, ['multiple' => true]);
    }
    echo "</td><td>";
-   Dropdown::showNumber('new_devices', ['min'   => 0, 'max'   => 10]);
+   Dropdown::showNumber('new_devices', ['value' => 1, 'min'   => 0, 'max'   => 10]);
    echo "</td></tr></table>";

 }
```

You must be aware that users would have to set the value to 0 if they want to add items only from unaffected devices.

Regards
