### ISSUE TITLE
Error on cron job CLI : Uncaught Exception Error

### ISSUE THREAD

**Issue by teleinformatique** [glpi-project/glpi#8892]
**Describe the bug**

I got this error after few minutes
Uncaught Exception Error: Class 'Laminas\Cache\Psr\SimpleCache\SimpleCacheException' not found in /var/www/html/glpi/vendor/laminas/laminas-cache/src/Psr/SimpleCache/SimpleCacheDecorator.php at line 307

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.3
Operating system: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3 (2019-02-02) x86_64
PHP 7.3.27-1~deb10u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, intl, json, libxml, mbstring, mysqli,
	mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at 41.82.204.101 Port 80)
	Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36
Server Software: Debian 10
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

It looks like your GLPI files are corrupted. Please try to reinstall release archive.
Documentation is available here: https://glpi-install.readthedocs.io/en/latest/install/

Regards
