### ISSUE TITLE
the 'Item not unique' notification is not totally in the recipient's language

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#89]
GLPI 0.85
Hereafter an example of 'item not unique' notification. Majority is in Spanish (the language of the recipient), but the 'Message' part (##unicity.message## "Enreg impossible...") which is in French (the current language when the event occured).
Indeed, the 'Message' part is built by func getUnicityErrorMessage() (in inc/commondbtm.class.php) which deals only with the current GLPi language.
-----
Entidad : Root entity
Tipo : SIM card
Mensaje : Enregistrement impossible pour IMSI = 1234
Un autre élément existe
[Ma carte SIM - ID : 1 - Numéro de série : 1234 - Entité : Root entity]
Autor de la acción : glpi
Acción prevista : Añadir el elemento
Fecha : 2015-08-28 16:46
---

**Comment by yllen** [comment]
@blerohellec Can you try fix purposed only done for 0.85?

**Comment by blerohellec** [comment]
It's much better, but not yet perfect. Hereafter the message part of the notif where the 1st 'Numéro de série' is still in french. The rest is correct (in spanish).

Mensaje : Registro imposible para Numéro de série = 1234
Existe otro elemento
[Ecran 1 - ID: 1 - Número de serie: 1234 - Entidad: Entité racine]

**Comment by blerohellec** [comment]
Another example : 'Numéro d'inventaire' stayed in french. 'Numéro d'inventaire' is the field which must be unique.

Mensaje : Registro imposible para Numéro d'inventaire = 4321
Existe otro elemento
[SIM 3 - ID: 3 - Número de serie: 1234 - Entidad: Entité racine]

**Comment by blerohellec** [comment]
And going to the Debug tab of the a 'Field unicity check', I get a serie of errors (on screen and in php-errors.log), 1 serie per recipient of the notification.
These errors seem to be linked to the addition made in inc/notificationtargetfieldunicity.class.php.

PHP Notice: Undefined index: label in /var/www/glpi085/inc/notificationtargetfieldunicity.class.php at line 64
PHP Notice: Undefined index: field in /var/www/glpi085/inc/notificationtargetfieldunicity.class.php at line 65
PHP Notice: Undefined index: double in /var/www/glpi085/inc/notificationtargetfieldunicity.class.php at line 66
PHP Warning: implode(): Invalid arguments passed in /var/www/glpi085/inc/commondbtm.class.php at line 3434
PHP Warning: Invalid argument supplied for foreach() in /var/www/glpi085/inc/commondbtm.class.php at line 3438

**Comment by yllen** [comment]
I made a test in spanish.
Elemento añadido correctamente pero registro duplicado en Número de serie = DNL3D1J
Existe otro elemento
[SBEI005W (429) - ID: 429 - Número de serie: DNL3D1J - Entidad: Root entity > Niveau 1 > Niveau 2 > Mon Entité]
[N/A (91254) - ID: 91254 - Número de serie: DNL3D1J - Entidad: Root entity > Niveau 1 > Niveau 2 > Mon Entité]
Elemento actualizado correctamente: N/A (2632)

**Comment by yllen** [comment]
Can you test my last commit?
If OK i'll do the same correction in 0.90

**Comment by blerohellec** [comment]
Correction validated on 0.85.
Thx
