### ISSUE TITLE
API call examples

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#891]
In all examples (in apirest.md and internal api documentation) of API calls App-Token header is wrong:
-H "App-Token {f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7}"
should be:
-H "App-Token: f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7"

Same with Session-Token:
-H "Session-Token {83af7e620c83a50a18d3eac2f6ed05a3ca0bea62}"
should be:
-H "Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62"

I spent 4 hours for it to find out why api-calls does not work, thinking that my nginx configuraion is wrong :(

**Comment by orthagh** [comment]
Thank your for your feedback and sorry for that error in the doc.

**Comment by hartois** [comment]
Colon after header name also required.
Without colon I have ERROR_APP_TOKEN_PARAMETERS_MISSING message.
Must be:
"App-Token f7g3csp8mgatg5ebc5elnazakw20i9fyev1qopya7"
"Session-Token: 83af7e620c83a50a18d3eac2f6ed05a3ca0bea62"

**Comment by orthagh** [comment]
You're right
