### ISSUE TITLE
Active Directory LDAP: issue while importing users

### ISSUE THREAD

**Issue by vrindergyani** [glpi-project/glpi#892]
Hi, 

We are facing a quite annoying issue. 
I don't know if this issue has been already reported but we can't import users through the import users in administration. Every time I tried to import I get the error: 
Information
Failed operation
(0 authorization problems, 1 failures)
wdevos: Error on executing the action

I tried to upgrade to the latest version 0.90.5 but still the same.

To workaround this, we insert the users in the database manually then sync them and this works.

We are using Active Directory as LDAP.

To reproduce this issue:
Need to setup the LDAP config in GLPI 
go to administration=>users=>LDAP Directory link
Import new users
Try to import new users =>action "import"
And here the error comes.

I don't know where to find the logs plus we don't know if it's the database logs which needed or the application logs.

I saw in the release notes of the version 0.90.4 that there was issue reported regarding importing users with LDAP and it has been closed but it's still not working as expected.

Please let me know also if it's a config issue or it's a known issue.

Regards,
Vrinder

**Comment by tomolimo** [comment]
Hello 
Need to know your config please. 
Regards 
Tomolimo

**Comment by vrindergyani** [comment]
Hi,
Which config you need to know?

Regards,
Vrinder

**Comment by tomolimo** [comment]
Go to:  'Setup > General' Tab: 'System' and copy/paste here the texte below 'Information about system installation and configuration'

And 

Go to: 'Setup > Authentication > LDAP directories', and in your directory, go to 'Advanced information', and paste here a screen copy.

thank you,

**Comment by vrindergyani** [comment]
GLPI 0.90.5 ( => /data/www/helpdesk.sia.bc)

Server
 
Operating system: Linux bms-web02.bms.11skynet.local 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64
PHP 5.6.14 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dba, dom,
	ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml, mbstring, mcrypt, mhash, mysql, mysqli,
	mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_sqlite, posix, session, soap, sockets, sqlite3, standard, tokenizer, wddx, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="128M" post_max_size="300M" safe_mode="" session.save_handler="files"
	upload_max_filesize="300M" 
Software: nginx/1.9.5
	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.1.8-MariaDB
	Server SQL Mode: NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: glpiprodusr@10.46.137.31/helpdesk
	Host info: 10.46.137.31 via TCP/IP
	
OK/data/www/helpdesk.sia.bc/config : OK
OK/data/www/helpdesk.sia.bc/files : OK
OK/data/www/helpdesk.sia.bc/files/_dumps : OK
OK/data/www/helpdesk.sia.bc/files/_sessions : OK
OK/data/www/helpdesk.sia.bc/files/_cron : OK
OK/data/www/helpdesk.sia.bc/files/_graphs : OK
OK/data/www/helpdesk.sia.bc/files/_lock : OK
OK/data/www/helpdesk.sia.bc/files/_plugins : OK
OK/data/www/helpdesk.sia.bc/files/_tmp : OK
OK/data/www/helpdesk.sia.bc/files/_rss : OK
OK/data/www/helpdesk.sia.bc/files/_uploads : OK
OK/data/www/helpdesk.sia.bc/files/_pictures : OK
OK/data/www/helpdesk.sia.bc/files/_log : OK
Web access to files directory is protectedWeb access to files directory is protected : OK
OKSELinux mode is Disabled

Libraries
 
htmLawed version 1.1.21 in (/data/www/helpdesk.sia.bc/lib/htmlawed)
phpCas version 1.3.4 in (/data/www/helpdesk.sia.bc/lib/phpcas)
PHPMailer version 5.2.8 in (/data/www/helpdesk.sia.bc/lib/phpmailer)
ZetaComponent ezcGraph installed in (/data/www/helpdesk.sia.bc/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/data/www/helpdesk.sia.bc/lib/Zend)
SimplePie version 1.3.1 in (/data/www/helpdesk.sia.bc/lib/simplepie)
TCPDF version 6.2.12 in (/data/www/helpdesk.sia.bc/lib/tcpdf)
ircmaxell/password-compat in (/data/www/helpdesk.sia.bc/lib/password_compat). Compatitility: Ok

LDAP directories
 
Server: 'bms.11skynet.local', Port: '389', BaseDN: 'DC=bms,DC=11skynet,DC=local', Connection filter:
		'(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN:
		'CN=idp_glpi,OU=Services,OU=Accounts,OU=Company,DC=bms,DC=11skynet,DC=local', Use TLS: none

Mysql replicas
 
Not active

Notifications
 
Way of sending emails: SMTP (anonymous@10.46.137.20)

Mails receivers
 
Name: 'glpi-uat@siabms.be' Active: Yes
	Server: '{BMS-EXCH01/imap/ssl/novalidate-cert/notls}INBOX' Login: 'idp_mailbox_glpi-uat' Password: Yes

Plugins list
 
	dashboard            Name: Dashboard                      Version: 0.6.9      State: Enabled
	fusioninventory      Name: FusionInventory                Version: 0.90+1.0   State: Enabled


and
![image](https://cloud.githubusercontent.com/assets/21223434/17966692/15e55d5a-6ac3-11e6-9d96-b4941b3d9c32.png)

**Comment by tomolimo** [comment]
Here is my AD - LDAP configuration:
![image](https://cloud.githubusercontent.com/assets/7569958/17967034/5a236e2e-6ac5-11e6-8487-96d60f5a37e2.png)

and advanced config:
![image](https://cloud.githubusercontent.com/assets/7569958/17967041/64f9e918-6ac5-11e6-99e8-05b2bc2800d4.png)

Could you check if the 'TEST' LDAP configuration is working?
Regards,
Tomolimo

**Comment by vrindergyani** [comment]
Yes it's working as I can sync the users but can't import them.

**Comment by tomolimo** [comment]
As the sync doesn't work the same way than the 'Test' (that's why I insist on this point).
Did you really push the button 'Test'?

**Comment by vrindergyani** [comment]
yes it's successful the test
Test successful: Main server AD

**Comment by tomolimo** [comment]
would you try with my settings?
like 'Page size' and 'LDAP aliases'?
Also: does the login field is well set? should be "samaccountname" for AD

**Comment by vrindergyani** [comment]
I have tried with your settings. It's still the same error.
The login field is set to sameaccountname.

**Comment by tomolimo** [comment]
sameaccountname or samaccountname?

**Comment by vrindergyani** [comment]
samaccountname

**Comment by vrindergyani** [comment]
sorry

**Comment by tomolimo** [comment]
no problem :)

**Comment by tomolimo** [comment]
Could look into the GLPi log files?

**Comment by vrindergyani** [comment]
Do you know where I can find them?

**Comment by tomolimo** [comment]
yes: **glpi_folder**/files/_log/*.log

**Comment by vrindergyani** [comment]
ok I will get you the logs. I have checked logs but don't seem to have any error or warning.

**Comment by wanderleihuttel** [comment]
Hello @tomolimo.

I was trying to use a LDAP filter to get only users for a specific group. I tested a lot of possibilities, but no one works.
Is it a limitation of LDAP or GLPI?

I would like to create a group (g_glpi) in Active Directory in include only users that will can use the GLPI and use this group in LDAP filter.

### My LDAP Server
![ldap001](https://cloud.githubusercontent.com/assets/16232272/25210164/3e91e2da-2555-11e7-9a5c-1a8118eef878.png)

### LDAP Import Users
![ldap002](https://cloud.githubusercontent.com/assets/16232272/25210165/3e9681f0-2555-11e7-8b7b-7bb5e33a426b.png)

Those users marked in red I wouldn't import.

Best regards
Wanderlei

**Comment by tomolimo** [comment]
Hello @wanderleihuttel,
Is there any link with the current issue?
If not, could you create another one? Otherwise it's impossible to distinguish the real root causes.
Thank you,
regards,
Tomolimo

**Comment by wanderleihuttel** [comment]
Hello @tomolimo! 
After a lot of tests with php-ldap I got what I wanted.
I created a group on the LDAP server (Group_GLPI) and linked users who can access the GLPI.
And then I used the following filter:

````
(&(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberof=CN=Group_GLPI,OU=Grupos,DC=domain,DC=local))
````

Thank you!

Best Regards
Wanderlei

**Comment by tomolimo** [comment]
@vrindergyani: no news for initial issue: I close, feel free to re-open.

**Comment by bellah2629** [comment]
Hello everyone , I have struggled with this same issue for so long. Please assist me

**Comment by BachirCoder** [comment]
@vrindergyani: I faced the same issue as yours. The solution was quite simple.

All what you need is go to: Setup --> Authentication --> Setup. Then Check "Yes" on the "Add a user without accreditation from a LDAP directory" field.

![image](https://user-images.githubusercontent.com/11787680/34382154-49b3d8ac-eb0d-11e7-8dbf-62e2baae4c13.png)

**Comment by Yasamal33** [comment]
> 
> 
> @vrindergyani: I faced the same issue as yours. The solution was quite simple.
> 
> All what you need is go to: Setup --> Authentication --> Setup. Then Check "Yes" on the "Add a user without accreditation from a LDAP directory" field.
> 
> ![image](https://user-images.githubusercontent.com/11787680/34382154-49b3d8ac-eb0d-11e7-8dbf-62e2baae4c13.png)

It looks like a workaround but it works. Thank you a lot

**Comment by BachirCoder** [comment]
@Yasamal33 you are welcome.

**Comment by wshsenanayaka** [comment]
Hello need help importing the user from the LDAP  @tomolimo 
.
Error 

Failed Operation
(0 authorizations problems, 1 failures)
170db628-0a6c-47f1-9d3b-cafacfe7592c: Error on executing the action

Thanks
