### ISSUE TITLE
GLPI 9.5.4 and 9.5.3 hidden watcher wrong id 

### ISSUE THREAD

**Issue by yakirillko** [glpi-project/glpi#8922]
for some reasons we need an itil cathegory with watcher that cannot be change. so we tryed to create template.

When configure ticket template:
1. Set user in watcher with  id more than 9. for examle 14 
2. Set  watcher user field hidden.
3. Watch in standart interface: if you have user with id for example 1(first digit in id of selected user(for example 14)) you will see user with id 1 in watcher . 
4. Watch simplified interface:   you will see user with id 14.
5. When you try to create new ticket with that tamlpate in standart interface you will get in watcher user with id 1(in this examle) from simplified interface - 14.

**Comment by yakirillko** [comment]
Found solution. it is because types
in  commonitilobject.class.php: 

} else { // predefined value
            if (isset($options["_users_id_observer"][0]) && $options["_users_id_observer"][0]) {
               echo static::getActorIcon('user', CommonITILActor::OBSERVER)."&nbsp;";
               echo Dropdown::getDropdownName("glpi_users", $options["_users_id_observer"][0]);
               echo "<input type='hidden' name='_users_id_observer' value=\"".
                      $options["_users_id_observer"][0]."\">";
               echo '<hr>';
            }
         }

change to 


} else { // predefined value
		if (!is_array($options['_users_id_observer'])){
			 $options['_users_id_observer'] = [$options['_users_id_observer']];
		}

            	if (isset($options["_users_id_observer"][0]) && $options["_users_id_observer"][0]) {
              	echo static::getActorIcon('user', CommonITILActor::OBSERVER)."&nbsp;";
               	echo Dropdown::getDropdownName("glpi_users", $options["_users_id_observer"][0]);
               	echo "<input type='hidden' name='_users_id_observer' value=\"".
                      $options["_users_id_observer"][0]."\">";
               	echo '<hr>';
            	}   
         }

**Comment by cedric-anne** [comment]
Hi,

Please propose a pull request with your changes.

Regards

**Comment by yakirillko** [comment]
Created pull request
