### ISSUE TITLE
API dropdowns

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#893]
Sorry, but I cannot find answer in documentation...
Can I get/create/edit/delete dropdown items with RestAPI?
In particular, now I'm interested in "locations"...

**Comment by hartois** [comment]
I found the answer to my question)) 
Dropdowns - this is also the objects.
Accordingly, I can use the calls like "search/location" and the like.

**Comment by orthagh** [comment]
Here is some examples

**for GET all locations:**

```bash
curl -X GET \
-H 'Content-Type: application/json' \
-H "Session-Token: xxxxxxx" \
http://path/to/glpi/apirest.php/Location
```

**GET a single location:**
```bash
curl -X GET \
-H 'Content-Type: application/json' \
-H "Session-Token: xxxxxxx" \
http://path/to/glpi/apirest.php/Location/:location_id
```

**POST (create):**
```bash
curl -X POST \
-H 'Content-Type: application/json' \
-H "Session-Token: xxxxxxx" \
-d '{"input": {"name": "My location"}}' \
http://path/to/glpi/apirest.php/Location
```


**PUT (update a single location):**
```bash
curl -X PUT \
-H 'Content-Type: application/json' \
-H "Session-Token: xxxxxxx" \
-d '{"input": {"name": "my location renamed"}}' \
http://path/to/glpi/apirest.php/Location/10'
```

**DELETE (you could add ?forcepurge=true to url to avoid trashbin)**
```bash
curl -X DELETE \
-H 'Content-Type: application/json' \
-H "Session-Token: xxxxxxx" \
http://path/to/glpi/apirest.php/Location/10'
```

**Comment by hartois** [comment]
Thank you!

**Comment by orthagh** [comment]
I close, feel free to comment if you need precisions.
