### ISSUE TITLE
Action list form shows wrong characters

### ISSUE THREAD

**Issue by gmed-ed** [glpi-project/glpi#8931]
If one choses an action for an asset while in global asset list, in the action-table some items show code like <i class='ma-icon ...
and icons aren't shown.

If one is direct on an asset page, action-table is complete incl. icons

**Page(s) URL**

If applicable, page(s) URL where the bug happens:

glpi/front/computer.php#modal_massaction_content5d787c51b7883448bd2fe2a88748fcc5

**To reproduce**

1. Go to Assets -> eg Computers
2. mark one or more assets and click "Actions"
3. Scroll the Actions-list
4. See errors 

**Expected behavior**

All items in Action-List dialog should be proper readable including the icons.

**Logs**

no log entry

Disordered Action-list in global asset page:
![glpi_954_action-dialog_bug040421](https://user-images.githubusercontent.com/43848352/113519914-ae2d5300-958f-11eb-8b0e-49c8932f9af7.png)

Correct Action-list in single asset page:
![glpi_954_action-dialog_clean040421](https://user-images.githubusercontent.com/43848352/113520040-a1f5c580-9590-11eb-813e-241452f8497b.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.4 ( => /var/www/glpi) Installation mode: TARBALL
--

Operating system: Linux los-dbi1 4.19.0-14-686-pae #1 SMP Debian 4.19.171-2 (2021-01-30) i686 PHP 7.4.16 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, imap, intl, json, ldap, 	libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="512M" post_max_size="50M" safe_mode="" session.save_handler="files" 	upload_max_filesize="50M"  Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at 10.42.199.165 Port 443) 	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36 Server Software: Debian 10 	Server Version: 10.3.27-MariaDB-0+deb10u1 	Server SQL Mode:  	Parameters: root@127.0.0.1/glpiweb 	Host info: 127.0.0.1 via TCP/IP

**Comment by trasher** [comment]
Already reported, and fixed

**Comment by gmed-ed** [comment]
Nice to see, that it's reported and fixed allready...
but where and how could i find the solution?

**Comment by sistemasgvc** [comment]
Good morning, where can I find the solution to this problem. Thanks

**Comment by cedric-anne** [comment]
You can upgrade to GLPI 9.5.5.

**Comment by sistemasgvc** [comment]
> You can upgrade to GLPI 9.5.5.

Thanks, I'll do it! I will inform what the result was !.
