### ISSUE TITLE
API search

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#894]
1. Can I search by field name instead of field number? Can I use field name in forcedisplay option?
2. How can I get in result of search AllAssets itemtype and ID of asset?

**Comment by orthagh** [comment]
1. No, Glpi core use theses numbered indexes to retrieve and display data.
2. itemtype is present, i just added missing id in above commit

**Comment by hartois** [comment]
Thanks.
Can I get the number of fields by names through API?

**Comment by orthagh** [comment]
Yes, use the [listSearchOptions](https://github.com/glpi-project/glpi/blob/master/apirest.md#list-searchoptions-list_searchoptions) endpoint
