### ISSUE TITLE
Bug: The technician in charge of the hardware must have to self-assign tickets or cannot be in charge of the hardware

### ISSUE THREAD

**Issue by conchaji** [glpi-project/glpi#8940]
I open this ticket here because we think it is a bug, otherwise I do not find sense.

For users to appear in the list of assets of "technicians in charge of hardware" in GLPI, the user must have the token "Assigned Tickets" active in their profile.

However, this triggers the fact that the tickets created by that profile are automatically self-assigned and this is not always desired (even if it is a technician)

What does the fact that the technician is in charge of the hardware have to do with self-assigning a ticket? we do not understand ..

**How to reproduce it:**

- Assets> New asset computer
- Assign: Technnician in charge of hardware
- Nothing appears in the drop-down unless you have the Assigned Tickets token in your profile.

Thanks a lot
All the best!

**Comment by conchaji** [comment]
This occurs even when in the entity the option: "Tickets Configuration \ Automatic Assignment of Tickets" is set to no.

**Comment by conchaji** [comment]
Anyone?

**Comment by cedric-anne** [comment]
Hi,

As there is nothing to identify "hardware technicians" in GLPI, it was decided 9 years ago (see 0d6ce30c3454b35a0f55d15140cc53b478ecbe3c) to consider as "hardware technician" anyone that is able to assign a ticket. In most situations, as technicians that are in charge of hardware are also in charge of tickets, this condition is valid.

There can be several solutions to answer your problem, and it is therefore necessary to think carefully about it before choosing which one is best able to answer the different situations.

As far as I know, this is not part of GLPI roadmap for now. If you want to fund such an enhancement, please don't hesitate to contact us: https://portal.glpi-network.com/contact-us

I close this issue as this is not really a bug, but a missing feature.

Regards
