### ISSUE TITLE
9.5.3 / 9.5.4 Bug - Missing financial data with computer template  

### ISSUE THREAD

**Issue by mirda123** [glpi-project/glpi#8942]
**Describe the bug**

When creating a computer using a template - financial data is added BUT no financial data is saved in the computer after choosing "add" 

**To reproduce**

1 - add a computer
2 - choose a template with financial data
3 - look at the financial data : OK 
4- Save the new computer created =  " add"
4 - open the  computer : financial data is empty.

**Expected behavior**

Financial data... 

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**
![bug01](https://user-images.githubusercontent.com/78594318/114032367-88989600-987c-11eb-9fe9-771355c01eb4.jpg)
![bug02](https://user-images.githubusercontent.com/78594318/114032382-8c2c1d00-987c-11eb-88d6-aaece6bc72a9.jpg)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by trasher** [comment]
duplicates #8544

**Comment by mirda123** [comment]
Hi,
problem is still there

need fix, thank you !
