### ISSUE TITLE
[9.5.4] Dashboard error

### ISSUE THREAD

**Issue by jbesnard** [glpi-project/glpi#8945]
Hi all,

I migrate my production server from 9.2.1 to 9.5.4.
Now, I have a problem with the dashboard "Statuts des tickets par mois"

On debug mode, I see this error message :

"Uncaught Exception TypeError: Argument 1 passed to Glpi\Dashboard\Provider::formatMonthyearDates() must be of the type string, null given, called in /var/www/html/glpi/inc/dashboard/provider.class.php on line 939 in /var/www/html/glpi/inc/dashboard/provider.class.php at line 1252"

I have run this command "php bin/console glpi:migration:timestamps" but there are no tables to migrate.

Can you help me ?

GLPI 9.5.4
UBUNTU 20.04
PHP 7.4.3

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)), I think this has been already fixed.

**Comment by jbesnard** [comment]
I have restarted the server and everything is working.
