### ISSUE TITLE
[0.90.5]bug ? mass action : notification activation

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#895]
home>setup>notification>notification> select 2 notifications or more>mass action>modify>active=no> submit : 
returns =>
information : 
Field itemtype is mandatory
Field itemtype is mandatory
Opération échouée
(0 problèmes de droits, 2 échecs)

it works fine when activate without "mass action"

notifications in root entity, user in root entity with super-admin profile recursive.

**Comment by orthagh** [comment]
Introduced by 3b0105a and #648 in glpi 0.90.4.
I'm currently investigating to add an exception for massive action
