### ISSUE TITLE
"Impact Analysis" tab broken in 9.5.4

### ISSUE THREAD

**Issue by hgpit** [glpi-project/glpi#8950]
Hello,

Just completed an upgrade from GLPI v9.5.3 to 9.5.4.
Now, when we go into a ticket, and click "Impact Analysis" tab, we get this:

![image](https://user-images.githubusercontent.com/16598973/114300165-c7199500-9ab6-11eb-851f-f7cf1e302ace.png)

Running in PHP 7.3.24 on CentOS

**Comment by cedric-anne** [comment]
see #8837
