### ISSUE TITLE
glpi 9.5.4 entity creation not work

### ISSUE THREAD

**Issue by pmrusek** [glpi-project/glpi#8956]
It is not possible to create an entity with the version 9.5.4

![image](https://user-images.githubusercontent.com/82391761/114408831-1b517180-9baa-11eb-8781-dbd8505b018c.png)

This is what i get, also when i take the glpi version 9.5.4 and untar, after setting up is this the result.

Also when i create in the database in the entity table it will not be displayed in glpi.

With the version before it works perfectly.

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)), this has been fixed already
