### ISSUE TITLE
Easier update

### ISSUE THREAD

**Issue by CoalaJoe** [glpi-project/glpi#896]
Refactor code to be installed with composer. On a new update you simple make a composer update rather than download & extract the tar ball, migrate your files and config to the new installation.

It is really bothersome to do this on every little update. And a composer package would make this application much more reliable.

**Comment by orthagh** [comment]
Hello @CoalaJoe.

It's an error, the release archive should have vendor directory.
I missed to do it when i tagged RC2.

I'm returning from vacation so i didn't find the time to correct the archive.
I'll do it before end of week.

See #848 for details.
