### ISSUE TITLE
Error update 9.5.4 to 9.5.5

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#8963]
Hi Guy!

When updating the system in a development environment, via command line everything was correct.

However, when trying to access the updated environment I get a blank screen

![image](https://user-images.githubusercontent.com/35368369/114755403-f7b83380-9d2f-11eb-90bd-fa59f7038b15.png)

In apache log I have

[Wed Apr 14 14:41:45.056778 2021] [php7:warn] [pid 148513] [client 10.1.1.19:65178] PHP Warning:  Erroneous data format for unserializing 'Laminas\\I18n\\Translator\\TextDomain' in /var/www/html/homologa/vendor/laminas/laminas-serializer/src/Adapter/PhpSerialize.php on line 128

In GLPI php-erros.log

![image](https://user-images.githubusercontent.com/35368369/114755587-33eb9400-9d30-11eb-9d56-bf0cdc33fb7e.png)

Informations

Update do GLPI 9.5.4 to 9.5.5;
PHP 8.0.3 (cli)
Zend Engine v4.0.3,
Debian GNU/Linux 10

**Comment by cedric-anne** [comment]
Hi,

Try to clear cache by removing content of `files/_cache` and/or restart apache/php process.

Regards

**Comment by phamorais** [comment]
@cedric-anne 
Its Work! Thx!!
