### ISSUE TITLE
"Access Denied" when trying to import users from LDAP (Active Directory) with Super-Admin profile

### ISSUE THREAD

**Issue by bbicudo** [glpi-project/glpi#8966]
It's an obvious error (access denied means access denied), but i can't inport users from my Active Directory server via LDAP even logged in as Super-Admin.

I only get an access denied message everytime i try.

Do you guys know of any changes i can to the system or how to debug permission so that i can finish importing my users?

PS.: It's not a fresh installation. Someone has changed permissions in the past to prevent some users from opening tickets and other tasks on the system...

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
