### ISSUE TITLE
[9.5.5] SSO and anonymus / GLPI Base authentication with IIS server

### ISSUE THREAD

**Issue by CireSacud26** [glpi-project/glpi#8976]
Hi !

**Bug description**
Using GLPI 9.5.5 on IIS 8.5 server (Php 7.4 and MySql 5.7). Some users accounts are GLPI locally based and some others are Active Directory synchronised. By default IIS authentication is set to "Anonymus authentication", so all users (GLPI locally based and AD sync) have to manually login with ID and password.

If IIS authentication is set only to "Windows authentication" to setup SSO authentication (as described here : https://rdr-it.com/glpi-sso-avec-iis-authentification-unique/), autologon based on Windows session works fine for users set from AD sync but no more for GLPI locally based users with ID and password.

If IIS authentication is set to both "Windows authentication" and "Anonymus authentication", SSO authentication does not work anymore. GLPI locally based users can logon with ID and password but not those AD sync.

**To reproduce**

1. Go to Administration > User and manually add a user ID = USERLOCAL + Pwd
2. Go to Setup > Authentication > LDAP Directories and add an LDAP Directory containing users
3. Go to Administration > User > LDAP Directory link > Import New User > Import one or more of the LDAP users
4. Go to Administration > User > LDAP Directory link > Synchronising already imported users > Select LDAP server and sync the above imported users
5. Close GLPI session

IIS is set with "Anonymus authentication" enabled only
1. Logon with local user ID and password => OK
2. Logon with LDAP user ID and password => OK

IIS is set with "Windows authentication" enabled only ("Anonymus authentication" is disabled)
1. Automatic SSO logon with Windows connect user => OK
2. Logon with local user ID and password => **NO OK - "Id or password incorrect - Try to reconnect"**

IIS is set with both "Windows authentication" and "Anonymus authentication" enabled
1. Automatic SSO logon with Windows connect user => **No automatic logon**
2. Logon with local user ID and password => OK
2. Logon with LDAP user ID and password => **NO OK - "Id or password incorrect - Try to reconnect"**

**Expected behavior**

In my opinion, I think the locally based GLPI user should be able to log in at any time, even if SSO authentication is enabled. 

**Logs**
Nothing relevant in log files

[code]Operating system: Windows NT PSWEB02 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586 PHP 7.4.11 cgi-fcgi (Core, PDO, PDO_ODBC, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, 	ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, readline, session, soap, sockets, sodium, sqlite3, standard, 	tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, zlib) Setup: max_execution_time="300" memory_limit="128M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Microsoft-IIS/8.5 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0 Server Software: MySQL Community Server (GPL) 	Server Version: 5.7.11-log 	Server SQL Mode:  	Parameters: root@localhost/glpi-test 	Host info: localhost via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (5.7.11) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to T:\/files/_cache has been validated. Write access to T:\/config has been validated. Write access to T:\/files/_cron has been validated. Write access to T:\/files has been validated. Write access to T:\/files/_dumps has been validated. Write access to T:\/files/_graphs has been validated. Write access to T:\/files/_lock has been validated. Write access to T:\/files/_pictures has been validated. Write access to T:\/files/_plugins has been validated. Write access to T:\/files/_rss has been validated. Write access to T:\/files/_sessions has been validated. Write access to T:\/files/_tmp has been validated. Write access to T:\/files/_uploads has been validated. Write access to T:\/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
--

GLPI_ROOT: T:\ GLPI_CONFIG_DIR: T:\/config GLPI_VAR_DIR: T:\/files GLPI_MARKETPLACE_DIR: T:\/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: T:\/files GLPI_CACHE_DIR: T:\/files/_cache GLPI_CRON_DIR: T:\/files/_cron GLPI_DUMP_DIR: T:\/files/_dumps GLPI_GRAPH_DIR: T:\/files/_graphs GLPI_LOCAL_I18N_DIR: T:\/files/_locales GLPI_LOCK_DIR: T:\/files/_lock GLPI_LOG_DIR: T:\/files/_log GLPI_PICTURE_DIR: T:\/files/_pictures GLPI_PLUGIN_DOC_DIR: T:\/files/_plugins GLPI_RSS_DIR: T:\/files/_rss GLPI_SESSION_DIR: T:\/files/_sessions GLPI_TMP_DIR: T:\/files/_tmp GLPI_UPLOAD_DIR: T:\/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: T:\/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (T:\vendor\htmlawed\htmlawed) phpmailer/phpmailer version 6.1.6 in (T:\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.6 in (T:\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.3.5 in (T:\vendor\tecnickcom\tcpdf) michelf/php-markdown in (T:\vendor\michelf\php-markdown\Michelf) true/punycode in (T:\vendor\true\punycode\src) iamcal/lib_autolink in (T:\vendor\iamcal\lib_autolink) sabre/dav in (T:\vendor\sabre\dav\lib\DAV) sabre/http in (T:\vendor\sabre\http\lib) sabre/uri in (T:\vendor\sabre\uri\lib) sabre/vobject in (T:\vendor\sabre\vobject\lib) laminas/laminas-cache in (T:\vendor\laminas\laminas-cache\src) laminas/laminas-i18n in (T:\vendor\laminas\laminas-i18n\src) laminas/laminas-serializer in (T:\vendor\laminas\laminas-serializer\src) monolog/monolog in (T:\vendor\monolog\monolog\src\Monolog) sebastian/diff in (T:\vendor\sebastian\diff\src) elvanto/litemoji in (T:\vendor\elvanto\litemoji\src) symfony/console in (T:\vendor\symfony\console) scssphp/scssphp in (T:\vendor\scssphp\scssphp\src) laminas/laminas-mail in (T:\vendor\laminas\laminas-mail\src\Protocol) laminas/laminas-mime in (T:\vendor\laminas\laminas-mime\src) rlanvin/php-rrule in (T:\vendor\rlanvin\php-rrule\src) blueimp/jquery-file-upload in (T:\vendor\blueimp\jquery-file-upload\server\php) ramsey/uuid in (T:\vendor\ramsey\uuid\src) psr/log in (T:\vendor\psr\log\Psr\Log) psr/simple-cache in (T:\vendor\psr\simple-cache\src) mexitek/phpcolors in (T:\vendor\mexitek\phpcolors\src\Mexitek\PHPColors) guzzlehttp/guzzle in (T:\vendor\guzzlehttp\guzzle\src) guzzlehttp/psr7 in (T:\vendor\guzzlehttp\psr7\src) wapmorgan/unified-archive in (T:\vendor\wapmorgan\unified-archive\src) paragonie/sodium_compat in (T:\vendor\paragonie\sodium_compat\src)

Server: '10.10.100.105', Port: '389', BaseDN: 'OU=USERS,OU=MyCompany,DC=net', Connection filter: 		'(&(objectClass=user)(objectCategory=person))', RootDN: 'CN=admin,OU=Administration,OU=MyCompany,DC=net', Use TLS: none

Not active

addressing           Name: Adressage IP                   Version: 2.9.0      State: Enabled 	news                 Name: Alertes                        Version: 1.9.0      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.12.4     State: Enabled 	accounts             Name: Comptes                        Version: 2.6.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.11.2     State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.10.1     State: Enabled 	order                Name: Gestion des commandes          Version: 2.6.0      State: Enabled 	pdf                  Name: Impression pdf                 Version: 2.0.0      State: Enabled 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.7.2      State: Enabled 	reports              Name: Rapports                       Version: 1.14.1     State: Enabled
[/code]

Regards,
Eric

**Comment by CireSacud26** [comment]
Hi !

Solution found by adding index.php?noAUTO=1 at end of main URL and GLPI base users can logon even if SSO is active and anonymus logon disabled in IIS.

But there is still another problem in this configuration with API access. I'll close this issue and open a new one.

Regards,
Eric

**Comment by andresoton-eab** [comment]
Hello,

@CireSacud26 could you give some deep information about getting working index.php?noAUTO=1 with only Windows Authenticaton Enabled?

When I cancel the promt of credentials I get a 401 error "Unauthorized: Access is denied due to invalid credentials."

What other configuration have you done on IIS?

Regards,
Andres

**Comment by CireSacud26** [comment]
Hi Andres,

If you get a 401 error, check in the global settings of your GLPI site in IIS if the "connect as" works.

If it's OK, i've no idea of what could going wrong, sorry.

Regards,
Eric
