### ISSUE TITLE
[0.84.8 to 0.91RC2] Database update crash

### ISSUE THREAD

**Issue by surfreg** [glpi-project/glpi#898]
Hi,

I'm testing migrate my GLPI 0.84.8 to 091RC2 and during the database update, i've a crash with message :

Mise à jour

Connexion à la base de données réussie

Ajout de - Object Locks à la base de données (28 secondes)

Mise à jour en 0.85

Traitement terminé. (20 secondes)

Mise à jour en 0.85.3

Traitement terminé. (27 secondes)

Mise à jour en 0.85.5

Traitement terminé. (28 secondes)

Mise à jour en 0.90

Traitement terminé. (28 secondes)

Mise à jour en 0.90.1

Traitement terminé. (28 secondes)

Mise à jour en 0.90.5

Traitement terminé. (28 secondes)

Mise à jour en 9.1

Traitement en cours...

9.1 insert first line into table glpi_apiclients - Erreur durant l'éxecution de la requête : INSERT INTO `glpi_apiclients` VALUES (1, 1, 1, 'full access', NOW(), 1, NULL, NULL, NULL, '', '', 0, NULL); - L'erreur est Incorrect datetime value: '' for column 'app_token_date' at row 1

Have you a issue ?

Thanks

Surfreg

**Comment by tomolimo** [comment]
fixed with #879

**Comment by surfreg** [comment]
Hi tomolimo,

Thanks for your answer it's ok now after the change of the "\install\update_0905_91.php" file.

Bye
