### ISSUE TITLE
GLPI 9.5.5: Actions menu issue with the "Add an items"

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#8989]
Hi GLPI Team!

After upgrading to GLPI 9.5.5 I faced with an issue. When I try to add an item to the ticket from right up menu "Actions" it couldn't find an existed item computer. 
![image](https://user-images.githubusercontent.com/20252855/115874229-87569400-a44c-11eb-8fe5-3a9acff89f20.png)

![image](https://user-images.githubusercontent.com/20252855/115874266-8faecf00-a44c-11eb-9308-d28a37e4c997.png)

BUT! If I try to add an item from ticket's tab "Items" it works and an item will be able to be attached.
![image](https://user-images.githubusercontent.com/20252855/115874444-c684e500-a44c-11eb-8240-e80709542290.png)

Is it a BUG or I forgot to set some settings in GLPI 9.5.5?

Thanks in advance for the help!

**Comment by cedric-anne** [comment]
Hi,

I cannot reproduce on my side.

Please try to logout/login, sometimes, after an upgrade, session data can be mixed up. Also, try to reproduce with no active plugins.

If probelm persist, please provide logs and GLPI system informations.

Regards

**Comment by okvok** [comment]
Hi,
I attached the screen with a ticket entity location:

![image](https://user-images.githubusercontent.com/20252855/115881039-04393c00-a454-11eb-9a16-cef91f63b17b.png)

Ticket located in sub-entity. I work in tree structure view when I can see all tickets from all sub-entities.
But when I go to the sub-entity where ticket is located the items from Action menu become accessible. See attached screen below where 1 is root entity and 2 is sub-entity where ticket is located.

![image](https://user-images.githubusercontent.com/20252855/115882639-9ee64a80-a455-11eb-9b84-e69716a15ae9.png)

All plugins were disabled.


 
GLPI 9.5.5 ( => /var/www/glpi)
Installation mode: TARBALL

 
Operating system: Linux bd-sd01.gpnbadra.local 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64
PHP 7.4.16 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, calendar,
	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mcrypt,
	mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, session, snmp, soap, sockets, sodium, sqlite3, standard, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="120" memory_limit="1024M" post_max_size="30M" safe_mode="" session.save_handler="files"
	upload_max_filesize="30M" 
Software: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_auth_kerb/5.4 PHP/7.4.16 ()
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36
Server Software: MariaDB Server
	Server Version: 10.3.11-MariaDB-log
	Server SQL Mode: 
	Parameters: glpidb@localhost/db_glpi_prod
	Host info: Localhost via UNIX socket
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.3.11) - Perfect!Database version seems correct (10.3.11) - Perfect!
Timezones seems loaded in databaseTimezones seems loaded in database
The log file has been created successfully.The log file has been created successfully.
Write access to /var/www/glpi/files/_cache has been validated.Write access to /var/www/glpi/files/_cache has been validated.
Write access to /var/www/glpi/config has been validated.Write access to /var/www/glpi/config has been validated.
Write access to /var/www/glpi/files/_cron has been validated.Write access to /var/www/glpi/files/_cron has been validated.
Write access to /var/www/glpi/files has been validated.Write access to /var/www/glpi/files has been validated.
Write access to /var/www/glpi/files/_dumps has been validated.Write access to /var/www/glpi/files/_dumps has been validated.
Write access to /var/www/glpi/files/_graphs has been validated.Write access to /var/www/glpi/files/_graphs has been validated.
Write access to /var/www/glpi/files/_lock has been validated.Write access to /var/www/glpi/files/_lock has been validated.
Write access to /var/www/glpi/files/_pictures has been validated.Write access to /var/www/glpi/files/_pictures has been validated.
Write access to /var/www/glpi/files/_plugins has been validated.Write access to /var/www/glpi/files/_plugins has been validated.
Write access to /var/www/glpi/files/_rss has been validated.Write access to /var/www/glpi/files/_rss has been validated.
Write access to /var/www/glpi/files/_sessions has been validated.Write access to /var/www/glpi/files/_sessions has been validated.
Write access to /var/www/glpi/files/_tmp has been validated.Write access to /var/www/glpi/files/_tmp has been validated.
Write access to /var/www/glpi/files/_uploads has been validated.Write access to /var/www/glpi/files/_uploads has been validated.
The directory could not be created in /var/www/glpi/marketplace.The directory could not be created in /var/www/glpi/marketplace.
Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.Web access to the files directory should not be allowed but this cannot be checked automatically on this instance.
Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.
SELinux configuration is OK.SELinux configuration is OK.

**Comment by okvok** [comment]
Any news about my question? 
Does anybody explain me may be it is a normal behavior of glpi?

**Comment by cedric-anne** [comment]
Hi,

This is due to the fact that the action dropdown has been built on top of the "massive actions" feature. While the form located in the ticket "Items" tab proposes a list of items that can be accessible from the ticket context (i.e. ticket entity), the form accessible via the actions dropdown will propose a list of items that can be accessible from the current entity, without even applying recursivity rules.

With the current filtering, it is possible to attach a non recursive item from root entity to a ticket that is located in a sub-entity, which should not be possible, I guess. 
I guess a solution could be to propose items that are accessible for all selected tickets, based on the intersection of their respective context.

Regards

**Comment by okvok** [comment]
Hi,
Sorry for the late answer. 
The item located at the same entity as the ticket.
![image](https://user-images.githubusercontent.com/20252855/134761555-5fd61509-bd1f-4199-a19f-3c2f879c9539.png)

Now I test 9.5.6 version and nothing changed.
