### ISSUE TITLE
Networks name in other language dont work?

### ISSUE THREAD

**Issue by Zegordo** [glpi-project/glpi#899]
Hello!
i have some problem: in setup/dropdowns/network names
i can not type a network name in any language, except english
http://prntscr.com/caopnx 
is a bug or some feauture?

**Comment by orthagh** [comment]
Hello @Zegordo .

> is a bug or some feature?

In fact, an outdated code. Glpi follow rfc 1123 (max length: 63 , and latin char only)
see: https://github.com/glpi-project/glpi/blob/master/inc/fqdnlabel.class.php#L74-L96

I'll check to support Internationalized domain name for next versions

**Comment by orthagh** [comment]
next release (9.1) will support these idn.
