### ISSUE TITLE
Wrong display of images in ticket

### ISSUE THREAD

**Issue by ITMan220** [glpi-project/glpi#8993]
Hi,

I am facing a problem with displaying images in tickets properly. images are placed in wrong position completely.
I've tried both setups IMAP and POP3 same result

Using GLPI 9.5.5

![GLPI](https://user-images.githubusercontent.com/83121078/115957760-ef6caf00-a50c-11eb-9a80-a327cf2e4029.png)
![Original message](https://user-images.githubusercontent.com/83121078/115957871-9c472c00-a50d-11eb-9802-bcbb3eee4bd2.png)

[code]
 
GLPI 9.5.5 ( => D:\GLPI\GLPI04192021\glpi)
Installation mode: TARBALL

Operating system: Windows NT TASKMGMT 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) i586
PHP 7.2.26 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif,
	fileinfo, filter, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql,
	pdo_sqlite, pdo_sqlsrv, readline, session, soap, sodium, sqlsrv, standard, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc,
	xmlwriter, zip, zlib)
Setup: max_execution_time="300" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Microsoft-IIS/8.5
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36 OPR/72.0.3815.400
Server Software: MySQL Community Server (GPL)
	Server Version: 5.6.6-m9-log
	Server SQL Mode: 
	Parameters: root@TASKMGMT/sascoglpi
	Host info: TASKMGMT via TCP/IP
	
PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is not presentapcu extension is not present
Zend OPcache extension is not presentZend OPcache extension is not present
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is not presentCAS extension is not present
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (5.6.6) - Perfect!Database version seems correct (5.6.6) - Perfect!
Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html.
The log file has been created successfully.The log file has been created successfully.
Write access to D:\GLPI\GLPI04192021\glpi/files/_cache has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_cache has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/config has been validated.Write access to D:\GLPI\GLPI04192021\glpi/config has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_cron has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_cron has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_dumps has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_dumps has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_graphs has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_graphs has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_lock has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_lock has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_pictures has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_pictures has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_plugins has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_plugins has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_rss has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_rss has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_sessions has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_sessions has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_tmp has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_tmp has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/files/_uploads has been validated.Write access to D:\GLPI\GLPI04192021\glpi/files/_uploads has been validated.
Write access to D:\GLPI\GLPI04192021\glpi/marketplace has been validated.Write access to D:\GLPI\GLPI04192021\glpi/marketplace has been validated.
Web access to files directory is protectedWeb access to files directory is protected

Name: 'servicedesk@**' Active: Yes
	Server: '{outlook.office365.com:995/pop/ssl}' Login: 'servicedesk@**' Password: Yes

**Comment by cedric-anne** [comment]
Hi,

Rendering in GLPI could differ from rendering in a mail client. Indeed, GLPI is not a mail client and, as handling a correct rendering of emails comming from many different clients could be a really huge job, it is not something that we plan to do.

Despite this, I can see that the email seems to be wrongly parsed, as you have some `</p></a>` that appears as text. Could you export the original email into eml format and attach it to current issue ? It would help us to investigate on this bug.

Regards

**Comment by ITMan220** [comment]
Hi Cedric,

Thank you for message. please find attached as requested.

**Comment by cedric-anne** [comment]
Hi,

Please export your email into eml format. msg file format cannot be used with open source tools.

Regards

**Comment by tomolimo** [comment]
Hello @cedric-anne,

Here you are:
[44.zip](https://github.com/glpi-project/glpi/files/6494969/44.zip)

Regards
Tomolimo
