### ISSUE TITLE
Polish translation - incorrect plural forms count

### ISSUE THREAD

**Issue by yild** [glpi-project/glpi#8998]
At the moment polish translation file pl_PL.po plural forms are defined incorrect as 4 forms:

`"Plural-Forms: nplurals=4; plural=(n==1 ? 0 : (n%10>=2 && n%10<=4) && (n%100<12 || n%100>14) ? 1 : n!=1 && (n%10>=0 && n%10<=1) || (n%10>=5 && n%10<=9) || (n%100>=12 && n%100<=14) ? 2 : 3);\n"
`

correct number in polish language is 3

`"Plural-Forms: nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"
`

see also 

https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/Plural-forms.html

**Comment by trasher** [comment]
Translations are handled on transifex, see https://www.transifex.com/glpi/GLPI.

**Comment by cedric-anne** [comment]
Transifex is basing its rules on https://unicode-org.github.io/cldr-staging/charts/latest/supplemental/language_plural_rules.html , which describes 4 plural forms for Polish language.
