### ISSUE TITLE
Inconsistency between (unicity) checks and 'ignored values for uniqueness' dropdown

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#90]
version 0.84, 0.85, 0.90
- the itemtype 'Financial & Admin info' is available in checks but not in the dropdown
- itemtype Contact : the field 'Address' is available in the dropdown, but not in the check
- same for Supplier / Address
- Same for User/ user DN

**Comment by yllen** [comment]
Can you specify where you have the dropdown "ignored values for uniqueness" in GLPI ?

**Comment by blerohellec** [comment]
Setup > Dropdowns > Ignored values for uniqueness (paragraph 'Fields unicity')

**Comment by cedric-anne** [comment]
Hi,

Even if such an enhancement could be interesting, we cannot implement all requested enhancements and have to prioritize our work.
Please use the [suggestion website](https://glpi.userecho.com/) for your proposals, to help us identify most valuable ones.

Regards
