### ISSUE TITLE
Ticket with adding a link to a document

### ISSUE THREAD

**Issue by amma35** [glpi-project/glpi#900]
Version of GLPI : 0.90 and 9.1

Setup : 
- Preferences : Enable ticket timeline => Yes
- Document add with user "normal" : 
  ![doc](https://cloud.githubusercontent.com/assets/15138371/18000224/55f7a582-6b7d-11e6-9f7c-672f2e0b6c53.PNG)
- Adding to a ticket link with the document with the user "glpi" : 
  ![link](https://cloud.githubusercontent.com/assets/15138371/18000264/8c1efe44-6b7d-11e6-8737-e170e49c2150.PNG)

Result : 
- In "Ticket Processing", the user is displayed is "normal" when it is "glpi" who added the document to the ticket. 

![result](https://cloud.githubusercontent.com/assets/15138371/18000302/a402722a-6b7d-11e6-8592-be6aa2b4664c.PNG)

**Comment by orthagh** [comment]
For understanding well, you upload a document already existing in the document database ?

**Comment by amma35** [comment]
Yes, I add an existing document into GLPI.

**Comment by amma35** [comment]
How can we go forward on this issue?

**Comment by trasher** [comment]
Since there is no user stored in the relation between document and item; I guess this is not possible actually.

It would require a database change to add user id to the glpi_documents_items I guess.

**Comment by amma35** [comment]
Yes, a database change will be required.

**Comment by cedric-anne** [comment]
Hi,

I just checked on current 9.4 nightly build and this is now fixed.

Regards
