### ISSUE TITLE
Auto refresh messing "actions" menu selections

### ISSUE THREAD

**Issue by we-sell-bags** [glpi-project/glpi#9006]
GLPI 9.5.5

if you have "auto refresh" set on tickets or other screens

then you are in the middle of using "actions" to reset items or change items.
the screen "resets" in the middle of what you are doing.....
and cancels the "actions" menu

**Comment by cedric-anne** [comment]
Hi,

Please provide requested informations, such as detailled steps to reproduce, screenshots,logs, GLPI system information, installed plugins, ...

Regards

**Comment by we-sell-bags** [comment]
1. turn on auto refresh for tickets
2. set a time
3. go to ticket screen
4. select some tickets
5. get the "actions" box up
6. make some actions.
7. wait for refresh to trigger.
8. screen is cleared BACK to just showing tickets, before action can complete


![tickets](https://user-images.githubusercontent.com/25189116/116373986-78068a80-a840-11eb-855b-7c1108fbc14d.jpg)


![actions](https://user-images.githubusercontent.com/25189116/116374071-8bb1f100-a840-11eb-9b55-cd1ee052bc19.jpg)


![tickets_after trigger](https://user-images.githubusercontent.com/25189116/116374174-a1271b00-a840-11eb-91b8-c0246c5d7110.jpg)




plugins:
 
	actualtime           Name: ActualTime                     Version: 1.5.0      State: Enabled
	fields               Name: Additionnal fields             Version: 1.12.4     State: Enabled
	advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Enabled
	news                 Name: Alerts                         Version: 1.9.0      State: Enabled
	badges               Name: Badges                         Version: 2.6.0      State: Enabled
	barcode              Name: Barcode                        Version: 2.5.0      State: Enabled
	camerainput          Name: Camera Input                   Version: 1.0.0      State: Not installed
	datainjection        Name: Data injection                 Version: 2.9.0      State: Installed / not activated
	escalade             Name: Escalation                     Version: 2.6.2      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.11.2     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	geninventorynumber   Name: Inventory number generation    Version: 2.5.0      State: Enabled
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.7.0      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.7.2      State: Enabled
	genericobject        Name: Objects management             Version: 2.10.1     State: Enabled
	tag                  Name: Tag Management                 Version: 2.8.1      State: Enabled
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled
	treeview             Name: Tree view                      Version: 1.9.0      State: Enabled
	useditemsexport      Name: Used items export              Version: 2.4.0      State: Enabled




Operating system: Linux glpi 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 PHP 7.3.27 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard, 	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files" 	upload_max_filesize="20M"  Software: Apache/2.4.6 (CentOS) PHP/7.3.27 () 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0 Server Software: MariaDB Server 	Server Version: 10.4.18-MariaDB 	Server SQL Mode:  	Parameters: glpi@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.4.18) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /usr/share/glpi/files/_cache has been validated. Write access to /usr/share/glpi/config has been validated. Write access to /usr/share/glpi/files/_cron has been validated. Write access to /usr/share/glpi/files has been validated. Write access to /usr/share/glpi/files/_dumps has been validated. Write access to /usr/share/glpi/files/_graphs has been validated. Write access to /usr/share/glpi/files/_lock has been validated. Write access to /usr/share/glpi/files/_pictures has been validated. Write access to /usr/share/glpi/files/_plugins has been validated. Write access to /usr/share/glpi/files/_rss has been validated. Write access to /usr/share/glpi/files/_sessions has been validated. Write access to /usr/share/glpi/files/_tmp has been validated. Write access to /usr/share/glpi/files/_uploads has been validated. Write access to /usr/share/glpi/marketplace has been validated. Web access to files directory is protected For security reasons, SELinux mode should be Enforcing.
--

GLPI_ROOT: /usr/share/glpi GLPI_CONFIG_DIR: /usr/share/glpi/config GLPI_VAR_DIR: /usr/share/glpi/files GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /usr/share/glpi/files GLPI_CACHE_DIR: /usr/share/glpi/files/_cache GLPI_CRON_DIR: /usr/share/glpi/files/_cron GLPI_DUMP_DIR: /usr/share/glpi/files/_dumps GLPI_GRAPH_DIR: /usr/share/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /usr/share/glpi/files/_locales GLPI_LOCK_DIR: /usr/share/glpi/files/_lock GLPI_LOG_DIR: /usr/share/glpi/files/_log GLPI_PICTURE_DIR: /usr/share/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /usr/share/glpi/files/_plugins GLPI_RSS_DIR: /usr/share/glpi/files/_rss GLPI_SESSION_DIR: /usr/share/glpi/files/_sessions GLPI_TMP_DIR: /usr/share/glpi/files/_tmp GLPI_UPLOAD_DIR: /usr/share/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/share/glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/usr/share/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/usr/share/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)

**Comment by cconard96** [comment]
Would be fixed by #9058 for the next major version of GLPI.
With this, the search results would be refreshed/updated without reloading the entire page.

**Comment by we-sell-bags** [comment]
Really the "update" should be turned off for the duration of menu selection
because if you are still updating, it may be the order of things in the list change, which means the user selected item may then point to the wrong item and any action on it , may end up affecting the wrong item.
