### ISSUE TITLE
GLPI 9.5.5 ./console glpi:database:check did anybody test it?

### ISSUE THREAD

**Issue by okvok** [glpi-project/glpi#9008]
GLPI 9.5.5 ./console glpi:database:check did anybody test it?

It's so funny works!!!!
![image](https://user-images.githubusercontent.com/20252855/116399405-9022dd80-a831-11eb-85bf-6401f8f087d9.png)

Too much bugs in the output of it.

**Comment by cedric-anne** [comment]
Hi,

We completely reworked this part on master branch, see especially #8593 and #8625.

Regards
