### ISSUE TITLE
Cant add Plugins

### ISSUE THREAD

**Issue by glpinewbi** [glpi-project/glpi#901]
I have an issue, i have installed 0.90.5 and i can't add Plugins, the Field "add" is Grey and "search" too. In the last Version which was installed (0.90.3) i can use the button "add" but no plugins are found. Please fix this issue

**Comment by orthagh** [comment]
Hello @glpinewbi 

We currently don't have an interactive search and installation of plugins in glpi (like wordpress for example).

You can browse existing plugin in this site: http://plugins.glpi-project.org/#/
You need to download the plugin archive, unpack it and copy to the plugins folder of glpi.

After that, the plugin will be listed in the page

**Comment by orthagh** [comment]
For information, we are thinking about an interactive plugins management in glpi interface with packages downloading and installation (.deb and .rpm), but we don't have any code for the moment.
