### ISSUE TITLE
Problem opening Statistics using More Reporting plugin

### ISSUE THREAD

**Issue by andrepetinga** [glpi-project/glpi#9010]
**Describe the bug**

Since we installed More Reporting plugin using marketplace, we get an error when accessing the reports using the Statistics option within Assistance menu.
If we try it using the More Reporting option within the Tools menu, all is ok

**Page(s) URL**

https://{glpi_url}/front/stat.php

**To reproduce**

1. Go to 'Assistance' - 'Statistics'
2. Click on a More Reporting option
3. You get an error "404 Not Found"

**Expected behavior**

The problem is because the links report to the old path of the plugin installation (public_html/plugins) instead of the new ones, since the plugin is now installed in Marketplace (public_html/marketplace)

When we click on the Statistics report, we get this kind of URL:
https://{glpi_url}/plugins/mreporting/front/graph.php?short_classname=Helpdeskplus&f_name=reportVstackbarGroupChange&gtype=vstackbar

When we open a report using the More Reporting option we get:

https://{glpi_url}/marketplace/mreporting/front/graph.php?short_classname=Helpdeskplus&f_name=reportVstackbarGroupChange&gtype=vstackbar

I'm posting this here but i'm not sure if the problem is in the GLPI core or the More Reporting plugin. The problem is, in the More Repoting Git Hub page I can't open an issue...

**Comment by trasher** [comment]
Hello,

This issue is related to a plugin, this cannot be fixed on GLPI. Issues seems indeed closed on this plugin (no idea why), but it seems pull requests are still opened.

Regards
