### ISSUE TITLE
[9.1-RC2] Not translated of words

### ISSUE THREAD

**Issue by AircraftRu** [glpi-project/glpi#902]
Not translated of words on page `http://server/glpi/front/config.form.php`
![glpi - setup - google chrome 2016-08-30 13 22 17](https://cloud.githubusercontent.com/assets/17082164/18085897/dc9ba6e8-6eb5-11e6-997c-58e9f22b916e.png)

**Comment by orthagh** [comment]
Hello @AircraftRu 

Translations effort is provided by the community.
I you find some locales untranslated in Ru, you can add a translation or fix existing on [transifex](https://www.transifex.com/glpi/) service.

Usually, i pull new locales before releases (RC and final).

**Comment by AircraftRu** [comment]
These words are translated on transifex service a month ago.

**Comment by orthagh** [comment]
ok, so next release candidate (probably at the end of week), will contains theses translations.
