### ISSUE TITLE
Fix $link for items ShowForDocument

### ISSUE THREAD

**Issue by OscarLoayzaB** [glpi-project/glpi#903]
As in other such functions.
Should be used getFormURLWithID() function. This for the variable $link.
If the item is Generic Object type, will return error in the link.

 file inc/document_item.class.php : line 521 & 522

```
                     $link = Toolbox::getItemTypeFormURL($itemtype);
                     $name = "<a href=\"".$link."?id=".$data["id"]."\">".$linkname."</a>";
```

Updated to:				 
```
					 $link     = $itemtype::getFormURLWithID($data['id']);
					 $name = "<a href=\"".$link."\">".$linkname."</a>";  
```

This change could be included in the code .??
Thanks.

**Comment by orthagh** [comment]
Sure, commit above.
It will be available in 9.1.
