### ISSUE TITLE
Templates Management problems?

### ISSUE THREAD

**Issue by pchevallereau** [glpi-project/glpi#904]
Hello!

When we create an new template in a entitie we can't find it in other. Is that normal that computers template cannot be used in multiple entities? 

Version: GLPI 0.90.4

Screenshot:
In first entitie we have six templates available
![glpi1](https://cloud.githubusercontent.com/assets/20992504/18121155/88af2ed4-6f63-11e6-801d-1b1870fcd7f8.PNG)

Then, in second we have nothing:
![glpi2](https://cloud.githubusercontent.com/assets/20992504/18121308/3c5ffd00-6f64-11e6-93ec-49cc8258879b.PNG)

**Comment by orthagh** [comment]
Hello @pchevallereau 

Did you set in your computer's templates, the "child entities" field to yes ?
![image](https://cloud.githubusercontent.com/assets/418844/18122416/b8bc2144-6f69-11e6-90fb-72c9973ff512.png)

Another question, you have some glitches in the glpi interface on your screenshots, what's your environnement (os, browser) ?

**Comment by pchevallereau** [comment]
Hello @orthagh 

When i create an new computer's templates, i haven't the child entities field.
![glpi3](https://cloud.githubusercontent.com/assets/20992504/18123416/fcdb8d02-6f6d-11e6-9046-030f7e2aa4e0.PNG)

Os: Windows 7 enterprise 64 bits
Browser: Firefox ESR 24.4.0

**Comment by orthagh** [comment]
Your profile-s (in administration  > Users > your login, Authorizations tab) should be recursive=yes to see that field.
Single-entity profiles can't use recursivity/child system

Ok for firefox ESR 24, it's a little outdated, last ESR (and only supported) is 45.x.

**Comment by pchevallereau** [comment]
I screenshot the authorizations tab for admin, he is recursive with super-admin profil
![glpi4](https://cloud.githubusercontent.com/assets/20992504/18126056/b41cdfb0-6f79-11e6-83cc-10ce69ec4b67.PNG)

With an Firefox 45.x. the problem already exist.

**Comment by ladenree76000** [comment]
it is strange that entities name are not displayed in this screenshot isn't it ?

**Comment by pchevallereau** [comment]
I have mask this for the politics of confidentiality.

**Comment by orthagh** [comment]
Your first screenshot doesn't display any entity selector. Ex:
![image](https://cloud.githubusercontent.com/assets/418844/18267393/2ccdf56c-741f-11e6-8f52-095a4caff399.png)


Did you hide it also ?

**Comment by pchevallereau** [comment]
I mask it for confidentiality.
Yes, the new release fix the problem, thanks for help.

You can close this issue.
Have a good day.
