### ISSUE TITLE
Error when loading bookmark

### ISSUE THREAD

**Issue by wawax** [glpi-project/glpi#905]
When loading a bookmark, I've got the following errors : 

2016-08-31 13:32:39 [1939@hopi]
  *** PHP Notice(8): Undefined index: itemtype
  Backtrace :
  inc/bookmark.class.php:433
  inc/bookmark.class.php:497                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:469                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()
2016-08-31 13:32:39 [1939@hopi]
  *** PHP Notice(8): Undefined index:
  Backtrace :
  inc/search.class.php:5402
  inc/search.class.php:5129                          Search::getOptions()
  inc/bookmark.class.php:433                         Search::getCleanedOptions()
  inc/bookmark.class.php:497                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:469                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()
2016-08-31 13:32:39 [1939@hopi]
  *** PHP Warning(2): Invalid argument supplied for foreach()
  Backtrace :
  inc/search.class.php:5402
  inc/search.class.php:5129                          Search::getOptions()
  inc/bookmark.class.php:433                         Search::getCleanedOptions()
  inc/bookmark.class.php:497                         Bookmark->prepareQueryToUse()
  inc/bookmark.class.php:469                         Bookmark->getParameters()
  front/bookmark.php:97                              Bookmark->load()

**Comment by wawax** [comment]
The line in DB for this bookmark : 
mysql> select * from glpi_bookmarks where id=108;
+-----+-------------------------------+------+----------+----------+------------+-------------+--------------+--------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id  | name                          | type | itemtype | users_id | is_private | entities_id | is_recursive | path               | query                                                                                                                                                                                                                                                                                                      |
+-----+-------------------------------+------+----------+----------+------------+-------------+--------------+--------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 108 | Dans le Parc | Mac - Portable |    1 | Computer |     1939 |          0 |           0 |            1 | front/computer.php | itemtype=Computer&sort=5150&order=DESC&criteria[0][field]=31&criteria[0][searchtype]=equals&criteria[0][value]=12&criteria[1][field]=4&criteria[1][link]=AND&criteria[1][searchtype]=equals&criteria[1][value]=21&metacriteria[0][field]=view&metacriteria[0][searchtype]=contains&metacriteria[0][value]= |
+-----+-------------------------------+------+----------+----------+------------+-------------+--------------+--------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

**Comment by orthagh** [comment]
The current line miss metacriteria[0][itemtype]=
Maybe a migration bug, but i tested that bookmark with the 0.84-> 0.85 migration without replicating the issue.

I suggest a clean of metacriteria as the old 0.84 data doesn't seems to contains fields2 params.

I close for now, we could reopen if we triggers this again
