### ISSUE TITLE
[9.5.5] Can add templates to notifications type, but can't remove some

### ISSUE THREAD

**Issue by M-Falken** [glpi-project/glpi#9059]
**Describe the bug**

Hi,
As we can add templates to notifications type, we should be able to remove some.

**Page(s) URL**

/front/notification.form.php

**To reproduce**

1. Create a new notification template
2. Go to '/front/notification.php'
3. Choose a notification
4. Add the new created template
5. Try to remove any of the list

**Expected behavior**

Be able to delete any model but none if it is the last one assigned

**Screenshots**

![screenshot-www emaging fr-2021 05 09-11_18_08](https://user-images.githubusercontent.com/1380639/117566930-ca09a480-b0b9-11eb-8097-be1e0faea65a.png)

```
GLPI 9.5.5
```

**Comment by Mirkk** [comment]
Hi, I have the same "issue", in GLPI 9.5.5, but also in older versions such as 9.5.2.

It is so "evident" that I thought the "delete" button has been removed for some specific reason and that there is a workaround, but I couldn't find one (except editing the association directly on the DB). It would be really helpful if someone of the developers can comment this issue.

Thank you a lot
Mirko

**Comment by cconard96** [comment]
A workaround for this is to click on the ID in the list shown in the image above to show the form for the Notification -> Notification Template relation, and then clicking the delete button in that form.

**Comment by M-Falken** [comment]
Thanks cconard96

**Comment by Mirkk** [comment]
Thanks Curtis,
It works, however it is not intuitive at all. Most similar interfaces have a massive action check box and the "delete" option in the actions. Moreover, clicking the delete button there you suppose that the template itself would be deleted, if you are not a core user that looks at the differences in the called php site **notification_**notificationtemplate.form.php.

**Comment by M-Falken** [comment]
Yes Mirkk,
that's why I've totally missed it, and report as an issue.

**Comment by Mirkk** [comment]
The issue still persists.
