### ISSUE TITLE
update from 0.90.5 to 9.1. RC2

### ISSUE THREAD

**Issue by pepeEL** [glpi-project/glpi#906]
Hi
I have a version 0.90.5 and i want update to 9.1 RC2. I copy all files to my GLPI. When open page i have info:
Run "composer install --no-dev" in the glpi tree

Please help

**Comment by trasher** [comment]
Hello,

In order to install GLPI dependencies for 9.1; you must use composer.

You can find installation instructions on the following page:
https://getcomposer.org/doc/00-intro.md

Once installed, you can run the install command from the GLPI tree.

Regards,

**Comment by pepeEL** [comment]
But i have GLPI installed on NAS Synology.

**Comment by tomolimo** [comment]
Then you can issue this command via the rsh.

**Comment by trasher** [comment]
You also can download the released RC2 (not the "source code" ones) from:
https://github.com/glpi-project/glpi/releases/download/9.1-RC2/glpi-9.1-RC2.tar.gz

This archive contains all vendors files.

Regards,
