### ISSUE TITLE
[9.5.5]  Error with a bad signature in a mail (the link of the images makes errors)

### ISSUE THREAD

**Issue by SeiyaGame** [glpi-project/glpi#9075]
**Describe the bug**

I apologize if my translation is bad, I'm not very good in English.
Let me explain the bug that I encounter. When users send emails to our support mailbox, they are retrieved by the mailgate to create tickets. The problem is that in some cases the ticket passes correctly and in other cases it remains blocked and duplicated endlessly. This results in a lot of tickets and queued tickets(~4000).

**To reproduce**

It's complicated to create the bug again because I myself don't understand everything what's happening. Users have a BoostMyMail signature with images like these

![signature_exemple](https://user-images.githubusercontent.com/40237982/118244509-e6358900-b49f-11eb-95f5-e16c26b64652.png)

And sometimes the images can't be found, which results in errors and ticket duplication, but also in the ticket queue being blocked.

![signature_exemple_bug](https://user-images.githubusercontent.com/40237982/118245846-8f30b380-b4a1-11eb-8a42-aa634d4ea94a.png)

I looked at the error logs and I concluded that glpi could not recover the size of the image and that it generated errors. (But that does not explain the duplication of ticket...)

**Logs**

php-errors.log
```
[2021-05-14 08:23:02] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: round(): Argument #1 ($num) must be of type int|float, string given in /var/www/glpi/inc/notificationeventmailing.class.php at line 223
  Backtrace :
  inc/notificationeventmailing.class.php:223         round()
  inc/queuednotification.class.php:564               NotificationEventMailing::send()
  inc/crontask.class.php:943                         QueuedNotification::cronQueuedNotification()
  front/cron.php:83                                  CronTask::launch()
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
Operating system: Linux srv-glpi-2021 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
PHP 8.0.5 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, xml,
	xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="600" memory_limit="512M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.38 (Debian) (Apache/2.4.38 (Debian) Server at support-info.amarris.local Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36
Server Software: Debian 10
	Server Version: 10.3.27-MariaDB-0+deb10u1
	Server SQL Mode: 
	Parameters: glpi@127.0.0.1/glpi
	Host info: 127.0.0.1 via TCP/IP
```

**Comment by cedric-anne** [comment]
Hi,

Is it possible for you to export one of these emails into eml format ? It could help us to add this case in our test suite in order to reproduce this bug and fix it.

Regards

**Comment by SeiyaGame** [comment]
Hi,

Thank you for the quick response

While searching on our side, we discovered that the Vadesecure solution was set up to protect our users from fraudulent emails (I was not aware of this). This means that all images / url links are protected by Vadesecure with a redirection link (which is temporary...) This system works very well during the day but from 5:30 pm - 6 pm (French time) from time to time the error explained above appears.

We are looking for more information about Vadesecure. I think GLPI should ignore these images ?!
Or do you have a solution to ignore these images?

I put you the .eml file as requested, I had to anonymize it though! ([eml_file.zip](https://github.com/glpi-project/glpi/files/6492315/mail_buge_glpi_anonymise.zip))

Regards

**Comment by cedric-anne** [comment]
Hi,

Can you validate that #9089 fixes your issue ?

Regards
