### ISSUE TITLE
Software rules doesn't remove duplicates if action software name isn't changed by action

### ISSUE THREAD

**Issue by ftrotin** [glpi-project/glpi#9079]
**Describe the bug**

When I create a software rule to remove duplicate software, it doesn't work if the old and the new software name are the same (I have to set a fake new name to make it work then set the right name and replay the rule)

**Page(s) URL**

/front/software.php

**To reproduce**

1. Go to 'Administration/Dictionaries/Software'
2. Add a new rule with theses parameters :
3. Name : Fusion PDFCreator
4. Logicial Operator : and
5. Criteria : Software | contains | PDFCreator
6. Action : Publisher |  Assign | pdfforge GmbH
7. Action : Software | Assign | PDFCreator
8. Go to 'Assets/Software'
9. Filter items seens contain PDFCreator
10. Selects items and execute the replay dictionary rules action

**Expected behavior**

The PDFCreator softwares shoud be merged.

If I change the action to Software | Assign | PDFCreator**2**, and replay the dictionary rules, the softwares are merged and renamed.
Then I revert the action to Software | Assign | PDFCreator, and replay the dictionary rules to get the original name (But when Fusion Inventory imports this software again, it recreates duplicates and I have to do this workaround again ; I hope it will work when this issue is solved in GLPI)

**Logs**

```
no logs in *-error.log files under glpi/files/_log/
```

**Screenshots**

![image](https://user-images.githubusercontent.com/23727823/118595268-0cfb0480-b7ab-11eb-938a-4dfd6a42a741.png)
![image](https://user-images.githubusercontent.com/23727823/118595376-3d42a300-b7ab-11eb-91ce-8897081f841e.png)
![image](https://user-images.githubusercontent.com/23727823/118595467-69f6ba80-b7ab-11eb-977e-dabe78594d6b.png)
![image](https://user-images.githubusercontent.com/23727823/118595540-872b8900-b7ab-11eb-9851-f1dd2f68dde9.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.3
```

**Comment by larsen0815** [comment]
I am experiencing the same bug (I guess) with GLPI 10.0.17.

After merging differing Firefox installations, I am left with two entries of "Mozilla Firefox", and then have to use yet another rule to merge these.
See https://forum.glpi-project.org/viewtopic.php?pid=514973
