### ISSUE TITLE
When go to Assets>Software tab after creating some Software records: Unknown column 'glpi_softwarelicenses.number' in 'field list'

### ISSUE THREAD

**Issue by atanasag** [glpi-project/glpi#908]
When go to Assets>Software tab after creating some Software records there is debug view error:
Unknown column 'glpi_softwarelicenses.number' in 'field list' in that statement:

SELECT 'glpi' AS currentuser, `glpi_softwares`.`entities_id`, `glpi_softwares`.`is_recursive`, `glpi_softwares`.`name` AS `ITEM_0`, `glpi_softwares`.`id` AS `ITEM_0_id`, `glpi_entities`.`completename` AS `ITEM_1`, `glpi_manufacturers`.`name` AS `ITEM_2`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_softwareversions`.`name`, '__NULL__'), '$#$',`glpi_softwareversions`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_3`, IFNULL(GROUP_CONCAT(DISTINCT CONCAT(IFNULL(`glpi_operatingsystems_0a35c270152be19b5c8a485502badcd7`.`name`, '__NULL__'), '$#$',`glpi_operatingsystems_0a35c270152be19b5c8a485502badcd7`.`id`) SEPARATOR '$$##$$'), '__NULL__$#$') AS `ITEM_4`, COUNT(DISTINCT `glpi_computers_softwareversions_154c8440a55efea26b94d5d49ee0f76e`.`id`) AS `ITEM_5`, FLOOR(SUM(`glpi_softwarelicenses`.`number`) * COUNT(DISTINCT `glpi_softwarelicenses`.`id`) / COUNT(`glpi_softwarelicenses`.`id`)) AS `ITEM_6`, MIN(`glpi_softwarelicenses`.`number`) AS `ITEM_6_min`, `glpi_softwares`.`id` AS id 
FROM `glpi_softwares`
LEFT JOIN `glpi_entities` ON (`glpi_softwares`.`entities_id` = `glpi_entities`.`id` )
LEFT JOIN `glpi_manufacturers` ON (`glpi_softwares`.`manufacturers_id` = `glpi_manufacturers`.`id` ) 
LEFT JOIN `glpi_softwareversions` ON (`glpi_softwares`.`id` = `glpi_softwareversions`.`softwares_id` )
LEFT JOIN `glpi_operatingsystems` AS `glpi_operatingsystems_0a35c270152be19b5c8a485502badcd7` ON (`glpi_softwareversions`.`operatingsystems_id` = `glpi_operatingsystems_0a35c270152be19b5c8a485502badcd7`.`id` ) 
LEFT JOIN `glpi_computers_softwareversions` AS `glpi_computers_softwareversions_154c8440a55efea26b94d5d49ee0f76e` ON (`glpi_softwareversions`.`id` = `glpi_computers_softwareversions_154c8440a55efea26b94d5d49ee0f76e`.`softwareversions_id` AND `glpi_computers_softwareversions_154c8440a55efea26b94d5d49ee0f76e`.`is_deleted_computer` = '0' AND `glpi_computers_softwareversions_154c8440a55efea26b94d5d49ee0f76e`.`is_deleted` = '0' AND `glpi_computers_softwareversions_154c8440a55efea26b94d5d49ee0f76e`.`is_template_computer` = '0' ) 
LEFT JOIN `glpi_softwarelicenses` AS `glpi_softwarelicenses_53942a48cc903d4163c4f6ac35841a36` ON (`glpi_softwares`.`id` = `glpi_softwarelicenses_53942a48cc903d4163c4f6ac35841a36`.`softwares_id` AND (`glpi_softwarelicenses_53942a48cc903d4163c4f6ac35841a36`.`expire` IS NULL OR `glpi_softwarelicenses_53942a48cc903d4163c4f6ac35841a36`.`expire` > NOW()) ) 
WHERE `glpi_softwares`.`is_deleted` = '0' AND `glpi_softwares`.`is_template` = '0' GROUP BY `glpi_softwares`.`id` 
ORDER BY ITEM_0 ASC LIMIT 0, 20

-----------GLPI Config-----------------
[code]
 
GLPI 9.1 ( => C:\inetpub\wwwroot\bbbb)

 

Server

 
Operating system: Windows NT GCS3-5 6.3 build 9200 (Windows Server 2012 R2 Datacenter Edition) i586
PHP 5.6.0 cgi-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, bcmath, calendar, cgi-fcgi, ctype, curl, date, dom, ereg, exif,
	fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, libxml, mbstring, mcrypt, mhash, mysql, mysqli, mysqlnd, odbc,
	openssl, pcre, pdo_mysql, pdo_sqlite, pdo_sqlsrv, session, soap, sqlsrv, standard, tidy, tokenizer, wddx, xml, xmlreader,
	xmlrpc, xmlwriter, zip, zlib)
Setup: max_execution_time="600" memory_limit="1028M" post_max_size="0" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Microsoft-IIS/8.5
	Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko
Server Software: MySQL Community Server (GPL)
	Server Version: 5.5.27-log
	Server SQL Mode: STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
	Parameters: xxx@gcs3-1.server.com/xxxx
	Host info: gcs3-1.server.com via TCP/IP
	
OKC:\inetpub\wwwroot\bbbb/config : OK
OKC:\inetpub\wwwroot\bbbb/files : OK
OKC:\inetpub\wwwroot\bbbb/files/_dumps : OK
OKC:\inetpub\wwwroot\bbbb/files/_sessions : OK
OKC:\inetpub\wwwroot\bbbb/files/_cron : OK
OKC:\inetpub\wwwroot\bbbb/files/_graphs : OK
OKC:\inetpub\wwwroot\bbbb/files/_lock : OK
OKC:\inetpub\wwwroot\bbbb/files/_plugins : OK
OKC:\inetpub\wwwroot\bbbb/files/_tmp : OK
OKC:\inetpub\wwwroot\bbbb/files/_rss : OK
OKC:\inetpub\wwwroot\bbbb/files/_uploads : OK
OKC:\inetpub\wwwroot\bbbb/files/_pictures : OK
OKC:\inetpub\wwwroot\bbbb/files/_log : OK

 

Libraries

 
htmLawed version 1.1.21 in (C:\inetpub\wwwroot\bbbb\lib\htmlawed)
phpCas version 1.3.4 in (C:\inetpub\wwwroot\bbbb\vendor\jasig\phpcas\source)
PHPMailer version 5.2.16 in (C:\inetpub\wwwroot\bbbb\vendor\phpmailer\phpmailer)
ZetaComponent ezcGraph installed in (C:\inetpub\wwwroot\bbbb\vendor\zetacomponents\graph\src): OK
Zend Framework in (C:\inetpub\wwwroot\bbbb\vendor\zendframework\zend-loader\src)
SimplePie version 1.4.1 in (C:\inetpub\wwwroot\bbbb\vendor\simplepie\simplepie\library)
TCPDF version 6.2.12 in (C:\inetpub\wwwroot\bbbb\vendor\tecnickcom\tcpdf)
ircmaxell/password-compat in (C:\inetpub\wwwroot\bbbb\vendor\ircmaxell\password-compat\lib). Compatitility: Ok
iacaml/autolink in (C:\inetpub\wwwroot\bbbb\vendor\iamcal\lib_autolink)
sabre/vobject in (C:\inetpub\wwwroot\bbbb\vendor\sabre\vobject\lib)
guzzlehttp/guzzle in ()

SQL replicas
Not active
Notifications

Way of sending emails: PHP
Mails receivers

Plugins list
[/code]

**Comment by tomolimo** [comment]
fixed by 37abd349823178e3e67df48e66a33dad837fe738,  see #844
