### ISSUE TITLE
I did not find to replace the logo

### ISSUE THREAD

**Issue by Thilip707** [glpi-project/glpi#9080]
**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
paste here
```

**Additional context**

**Comment by tomolimo** [comment]
Hello @Thilip707 
If you do not fill in the form above, we cannot help you...
Thank you
Regards,
Tomolimo

**Comment by trasher** [comment]
Informations requested in ticket template has not been provided. Please use [forums](http://forum.glpi-project.org) to get community support; gh issues are for bugs only.
