### ISSUE TITLE
Son-Parent type for tickets links

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#909]

**Comment by tomolimo** [comment]
Notion of 'Master' ticket?

**Comment by orthagh** [comment]
Yes.

**Comment by wawax** [comment]
master ticket suggestion  http://glpi.userecho.com/topics/1-master-ticket/

**Comment by wawax** [comment]
Feature adding by PR https://github.com/glpi-project/glpi/pull/2365

**Comment by lexcorp** [comment]
How does this feature work?

**Comment by trasher** [comment]
@lexcorp this work as tickets links; see http://glpi-project.org/DOC/EN/glpi/helpdesk_ticket_link.html.
This is not up to date; but I don't think that has changed much.

**Comment by Armin83** [comment]
@trasher i took a fly over the code how to get this warning "
'Warning: non closed children tickets depends on current ticket. Are you sure you want to close it?'"

other user want to know this too http://forum.glpi-project.org/viewtopic.php?id=160223
