### ISSUE TITLE
[9.5.4] Rights on ticket when task assigned.

### ISSUE THREAD

**Issue by yakirillko** [glpi-project/glpi#9091]
Hi! I don't know it is a bug, but i think so.
In our server config we disable viewing all tickets for tech.
![изображение](https://user-images.githubusercontent.com/22744420/119098454-88b0b780-ba1e-11eb-8793-2fa95cfc04b3.png)
They can view only tickest that assign to them. But when we create task in ticket we can assign task to any tech and it sucssesfully asigned. 
Tech can see it in personal view.
![изображение](https://user-images.githubusercontent.com/22744420/119098245-4ab39380-ba1e-11eb-816b-190c9b6b3584.png)
But when we try to view that task we cannot access to ticket.
![изображение](https://user-images.githubusercontent.com/22744420/119098383-70d93380-ba1e-11eb-9f55-6088e73b2b26.png)
Also we doesn't see it in Assistance-Tickets
![изображение](https://user-images.githubusercontent.com/22744420/119099411-8a2eaf80-ba1f-11eb-9ca3-17acd52d6a7f.png)

in compare with validation. when validatition is assigned we can acces to ticket without other rights to ticket.

so we have to add user or group also in watchers or assigners. It is not we expect to 

Maybe there is missconfig in our config. But i don't found anything(

**Comment by M-Falken** [comment]
Hi
Did you try "See assigned" rather than "Assign" ?

**Comment by yakirillko** [comment]
> 
> 
> Hi
> Did you try "See assigned" rather than "Assign" ?

Try to add "See assigned"  nothing changes. I think this checkbox for Tickets not for Tasks in ticket.
