### ISSUE TITLE
GLPI 9.5.5 - After update, no items displayed in Automatic actions

### ISSUE THREAD

**Issue by Zarau123** [glpi-project/glpi#9100]
Hello Mates,

After upgrading GLPI from V9.4.4 to 9.5.5 all the automatic actions are not listed, i know they are there because i can see the next action that will be executed, but the list of all automatic actions are not displayed...
![image](https://user-images.githubusercontent.com/56557411/119642850-102d6a80-be13-11eb-835d-a9a8103a48d0.png)

Already tryed to copy the old crontask files from 9.4.4 to this new version but no luck. Can someone please help?

**Comment by Zarau123** [comment]
Noticed now a error in debug mode
![image](https://user-images.githubusercontent.com/56557411/119643533-c1340500-be13-11eb-92d1-fb1a8a12b085.png)

**Comment by cedric-anne** [comment]
Hi,

Please provide all requested informations inissue form ( https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.md ).

Regards

**Comment by cedric-anne** [comment]
Duplicates #7997.

"modifications" plugin is responsible of this, it alters GLPI code and creates the bug. You have to remove this plugin and reinstall GLPI source files.

**Comment by Zarau123** [comment]
Thank you Cedric

That was the problem indeed.... i removed the plugin and now works like a charm. Thank you once again mate!
