### ISSUE TITLE
Ticket Information Visualization Error

### ISSUE THREAD

**Issue by E-Rodri** [glpi-project/glpi#9108]
Hi my name is Enzo. I need help for the issue mentioned on the tittle.

The server shutdown due to a vmware error, an after that, in the GLPI web app dont show the information of the tickets. Screenshot: https://ibb.co/hBBhB7y

The users can create tickets and technician too. This Tickets are listed in Support>Incident . Screenshot: https://ibb.co/svymzYy

The mail notification of this new tickets, arrive with al the information correct. Screenshot: https://ibb.co/fXzq76y

The database havent any issue

Can any give me some help please.

**Comment by cedric-anne** [comment]
Hi,

Please provide all requested informations in issue form (https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.md). I guess you will find usefull information in GLPI logs.

Regards
