### ISSUE TITLE
Api: Webhooks

### ISSUE THREAD

**Issue by orthagh** [glpi-project/glpi#913]
send events by http to others applications.

It can ease future integrations (like slack/mattermost/telegram, etc)

**Comment by lucassmacedo** [comment]
I Want this

**Comment by catudals** [comment]
very much this

**Comment by godsom** [comment]
rocketchat as well

**Comment by sulian** [comment]
Hello !

Any news about this feature ? (I vote for Zulip/Mattermost)

**Comment by e-ruiz** [comment]
+1 Up

**Comment by morevsky** [comment]
+1 Zulip plz)

**Comment by svarog11** [comment]
+1

**Comment by julianobarbosa** [comment]
+1

**Comment by levifranzen** [comment]
+1

**Comment by yohariel** [comment]
have already been created?

**Comment by levifranzen** [comment]
> have already been created?

Nope, but should be in the next major version.

**Comment by prybak** [comment]
Is there any plan for that? It would be useful as this supports automation of handling tickets added by users.

**Comment by heizac** [comment]
We're in december already. Any news about this integration??

**Comment by catudals** [comment]
UP to keep this open

**Comment by prybak** [comment]
Try it out: https://github.com/FutureProcessing/glpi-webhook

**Comment by C-Duv** [comment]
Bot, unstale this please.

**Comment by levifranzen** [comment]
Bot, unstale this please.

**Comment by hostage007** [comment]
+1 need this

**Comment by fulljackz** [comment]
+1 (6 years later)

**Comment by Uzzi** [comment]
+1
pleaseeeeee

**Comment by FabFara** [comment]
+1

**Comment by svarog11** [comment]
+119:43, 22 декабря 2022 г., vfvjwork ***@***.***>:
+1 I need this !

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
