### ISSUE TITLE
Incorrect KPIs Dashboards compared to the GLPI filter [GLPI 9.5.5]

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#9134]
**Describe the bug**
In version 9.5.5 when using the chart "Top called by assigned groups"

Example

When hovering over the chart it shows "14 tickets".
![image](https://user-images.githubusercontent.com/35368369/120553417-d76f3180-c3ce-11eb-86bc-119e46cf5b90.png)

However, when clicking, the GLPI presents a list of "7 tickets".

![image](https://user-images.githubusercontent.com/35368369/120553519-f7065a00-c3ce-11eb-82b9-da70cb3d1b9e.png)

The profile of the user who is viewing has permission to see data only from the tickets of the groups she is part of

![image](https://user-images.githubusercontent.com/35368369/120553693-2b7a1600-c3cf-11eb-9092-9d7d5917b387.png)

If I do the same operation with the "super-admin" profile, the error doesn't happen

![image](https://user-images.githubusercontent.com/35368369/120553840-5a908780-c3cf-11eb-8e26-caa36e3b293d.png)

**Page(s) URL**
- /front/central.php
- /front/ticket.php

**Expected behavior**
View the correct indicators

**Logs**

not relevant

System

PHP version is at least 7.2.0 - Perfect!PHP version is at least 7.2.0 - Perfect!
Sessions support is available - Perfect!Sessions support is available - Perfect!
Allocated memory > 64 Mio - Perfect!Allocated memory > 64 Mio - Perfect!
mysqli extension is installedmysqli extension is installed
ctype extension is installedctype extension is installed
fileinfo extension is installedfileinfo extension is installed
json extension is installedjson extension is installed
mbstring extension is installedmbstring extension is installed
iconv extension is installediconv extension is installed
zlib extension is installedzlib extension is installed
curl extension is installedcurl extension is installed
gd extension is installedgd extension is installed
simplexml extension is installedsimplexml extension is installed
intl extension is installedintl extension is installed
ldap extension is installedldap extension is installed
apcu extension is installedapcu extension is installed
Zend OPcache extension is installedZend OPcache extension is installed
xmlrpc extension is installedxmlrpc extension is installed
CAS extension is installedCAS extension is installed
exif extension is installedexif extension is installed
zip extension is installedzip extension is installed
bz2 extension is installedbz2 extension is installed
sodium extension is installedsodium extension is installed
Database version seems correct (10.4.14) - Perfect!Database version seems correct (10.4.14) - Perfect!

**Comment by phamorais** [comment]
any ?

**Comment by eandry77** [comment]
Same issue with top ticket assignment.

**Comment by phamorais** [comment]
Fixed issue with PR of @edgardmessias
