### ISSUE TITLE
Issue with SMTP since migration to 9.5.5

### ISSUE THREAD

**Issue by chichtacos** [glpi-project/glpi#9143]
Hi,

I migrated my GLPI to 9.5.5 version. 
We can't send mail outside our organisation. Internal notifications work well.

In mail-error.log, we can see this : Unable to relay recipient in non-accepted domain

It was working perfectly well before we migrate. 

GLPI SETUP 

[code] &nbsp; GLPI 9.5.5 ( =&gt; C:\xampp\htdocs\glpi) Installation mode: TARBALL
--

Operating system: Windows NT VM-SDIS-WEB01 6.3 build 9600 (Windows Server 2012 R2 Datacenter Edition) i586 PHP 7.3.2 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, 	mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, snmp, standard, tokenizer, wddx, xml, xmlreader, xmlwriter, 	zip, zlib) Setup: max_execution_time="6000" memory_limit="2000M" post_max_size="2000M" safe_mode="" session.save_handler="files" 	upload_max_filesize="8000M"  Software: Apache/2.4.38 (Win32) mod_authnz_sspi/0.1.1 OpenSSL/1.1.1a PHP/7.3.2 (Apache/2.4.38 (Win32) mod_authnz_sspi/0.1.1 	OpenSSL/1.1.1a PHP/7.3.2 Server at glpi.sdis36.org Port 443) 	Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.1.38-MariaDB 	Server SQL Mode:  	Parameters: root@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory &gt; 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is not present Zend OPcache extension is installed xmlrpc extension is not present CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is not present Database version seems correct (10.1.38) - Perfect! Timezones seems not loaded, see https://glpi-install.readthedocs.io/en/latest/timezones.html. The log file has been created successfully. Write access to C:\xampp\htdocs\glpi/files/_cache has been validated. Write access to C:\xampp\htdocs\glpi/config has been validated. Write access to C:\xampp\htdocs\glpi/files/_cron has been validated. Write access to C:\xampp\htdocs\glpi/files has been validated. Write access to C:\xampp\htdocs\glpi/files/_dumps has been validated. Write access to C:\xampp\htdocs\glpi/files/_graphs has been validated. Write access to C:\xampp\htdocs\glpi/files/_lock has been validated. Write access to C:\xampp\htdocs\glpi/files/_pictures has been validated. Write access to C:\xampp\htdocs\glpi/files/_plugins has been validated. Write access to C:\xampp\htdocs\glpi/files/_rss has been validated. Write access to C:\xampp\htdocs\glpi/files/_sessions has been validated. Write access to C:\xampp\htdocs\glpi/files/_tmp has been validated. Write access to C:\xampp\htdocs\glpi/files/_uploads has been validated. Write access to C:\xampp\htdocs\glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: C:\xampp\htdocs\glpi GLPI_CONFIG_DIR: C:\xampp\htdocs\glpi/config GLPI_VAR_DIR: C:\xampp\htdocs\glpi/files GLPI_MARKETPLACE_DIR: C:\xampp\htdocs\glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: C:\xampp\htdocs\glpi/files GLPI_CACHE_DIR: C:\xampp\htdocs\glpi/files/_cache GLPI_CRON_DIR: C:\xampp\htdocs\glpi/files/_cron GLPI_DUMP_DIR: C:\xampp\htdocs\glpi/files/_dumps GLPI_GRAPH_DIR: C:\xampp\htdocs\glpi/files/_graphs GLPI_LOCAL_I18N_DIR: C:\xampp\htdocs\glpi/files/_locales GLPI_LOCK_DIR: C:\xampp\htdocs\glpi/files/_lock GLPI_LOG_DIR: C:\xampp\htdocs\glpi/files/_log GLPI_PICTURE_DIR: C:\xampp\htdocs\glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: C:\xampp\htdocs\glpi/files/_plugins GLPI_RSS_DIR: C:\xampp\htdocs\glpi/files/_rss GLPI_SESSION_DIR: C:\xampp\htdocs\glpi/files/_sessions GLPI_TMP_DIR: C:\xampp\htdocs\glpi/files/_tmp GLPI_UPLOAD_DIR: C:\xampp\htdocs\glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: C:\xampp\htdocs\glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (C:\xampp\htdocs\glpi\vendor\htmlawed\htmlawed) phpmailer/phpmailer version 6.1.6 in (C:\xampp\htdocs\glpi\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.6 in (C:\xampp\htdocs\glpi\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.3.5 in (C:\xampp\htdocs\glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (C:\xampp\htdocs\glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (C:\xampp\htdocs\glpi\vendor\true\punycode\src) iamcal/lib_autolink in (C:\xampp\htdocs\glpi\vendor\iamcal\lib_autolink) sabre/dav in (C:\xampp\htdocs\glpi\vendor\sabre\dav\lib\DAV) sabre/http in (C:\xampp\htdocs\glpi\vendor\sabre\http\lib) sabre/uri in (C:\xampp\htdocs\glpi\vendor\sabre\uri\lib) sabre/vobject in (C:\xampp\htdocs\glpi\vendor\sabre\vobject\lib) laminas/laminas-cache in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-cache\src) laminas/laminas-i18n in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-i18n\src) laminas/laminas-serializer in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-serializer\src) monolog/monolog in (C:\xampp\htdocs\glpi\vendor\monolog\monolog\src\Monolog) sebastian/diff in (C:\xampp\htdocs\glpi\vendor\sebastian\diff\src) elvanto/litemoji in (C:\xampp\htdocs\glpi\vendor\elvanto\litemoji\src) symfony/console in (C:\xampp\htdocs\glpi\vendor\symfony\console) scssphp/scssphp in (C:\xampp\htdocs\glpi\vendor\scssphp\scssphp\src) laminas/laminas-mail in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mail\src\Protocol) laminas/laminas-mime in (C:\xampp\htdocs\glpi\vendor\laminas\laminas-mime\src) rlanvin/php-rrule in (C:\xampp\htdocs\glpi\vendor\rlanvin\php-rrule\src) blueimp/jquery-file-upload in (C:\xampp\htdocs\glpi\vendor\blueimp\jquery-file-upload\server\php) ramsey/uuid in (C:\xampp\htdocs\glpi\vendor\ramsey\uuid\src) psr/log in (C:\xampp\htdocs\glpi\vendor\psr\log\Psr\Log) psr/simple-cache in (C:\xampp\htdocs\glpi\vendor\psr\simple-cache\src) mexitek/phpcolors in (C:\xampp\htdocs\glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors) guzzlehttp/guzzle in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\guzzle\src) guzzlehttp/psr7 in (C:\xampp\htdocs\glpi\vendor\guzzlehttp\psr7\src) wapmorgan/unified-archive in (C:\xampp\htdocs\glpi\vendor\wapmorgan\unified-archive\src) paragonie/sodium_compat in (C:\xampp\htdocs\glpi\vendor\paragonie\sodium_compat\src)

Server: '192.168.200.251', Port: '389', BaseDN: 'DC=sdis36,DC=local', Connection filter: 		'(&amp;(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'sdis36\administrateur', Use TLS: none

Not active

Way of sending emails: SMTP (anonymous@192.168.200.250)

Name: 'support-trs@sdis36.org' Active: Yes 	Server: '{192.168.200.250:143/imap/novalidate-cert/tls}INBOX' Login: 'support-trs' Password: Yes Name: 'support-ssi@sdis36.org' Active: Yes 	Server: '{192.168.200.250:143/imap/novalidate-cert/tls}INBOX' Login: 'support-ssi' Password: Yes

fields               Name: Champs supplémentaires         Version: 1.11.0     State: Enabled 	behaviors            Name: Comportements                  Version: 2.2.2      State: Enabled 	printercounters      Name: Compteurs Imprimantes          Version: 1.7.0      State: Enabled 	datainjection        Name: Data Injection                 Version: 2.8.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.10.1     State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.9.0      State: Enabled 	pdf                  Name: Impression pdf                 Version: 2.0.0      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.0      State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.7.0      State: Enabled 	satisfaction         Name: Plus de satisfaction           Version: 1.5.0      State: Enabled 	reports              Name: Rapports                       Version: 1.14.1     State: Enabled 	reservation          Name: Reservation                    Version: 2.3.3      State: Enabled 	dashboard            Name: Tableau de bord                Version: 1.0.2      State: Enabled
[/code]

**Comment by cedric-anne** [comment]
Hi,

You should try to reconfigure SMTP password.

What was your previous GLPI version ? Did you copied the encryption key file into the configuration directory before launching the upgrade process ?

Regards

**Comment by chichtacos** [comment]
Hi thx for the quick feedback !
I was in 9.5.2. I did not copy the encryption key. Where is this file ?
I have a backup so I can retrieve it easily.

**Comment by cedric-anne** [comment]
File is `config/glpicrypt.key`.

**Comment by chichtacos** [comment]
Hi,

Just updated the file.
But still don't work. 

I did receive notification internally

2021-06-07 15:15:09 [@VM-NAME-TOTO]
Attention : un courriel n'a pas pu être délivré à toto@titi.com. 5 tentatives restantes. Message : [GLPI #0006284] test - NE PAS PRENDRE EN COMPTE -- OUVERTURE, Erreur : SMTP Error: The following recipients failed: toto@titi.com: SMTP; Unable to relay recipient in non-accepted domain

Thx !

**Comment by trasher** [comment]
`Unable to relay recipient in non-accepted domain` is your issue; and this is not related to glpi.

**Comment by chichtacos** [comment]
Indeed, issue was coming from my exchange 2016 server. But I don't explain why it was working well before the migration to 9.5.5...
For information (it's not a glpi issue, but if it can help someone), I post here the manipulation I executed this morning : 

https://blogmotion.fr/systeme/exchange-unable-to-relay-recipient-in-non-accepted-domain-17219

I have already an anonymous smtp connector, but the rights of "anonymous" user were not set.

I close this case.
