### ISSUE TITLE
front/users.php take a long time to load

### ISSUE THREAD

**Issue by ameurou** [glpi-project/glpi#915]
Hi,

Calling front/users.php take around a minute to give back answer for 344 users in database.

With debug on, we got 79286 sql queries executed for each call
![bug0](https://cloud.githubusercontent.com/assets/11721263/18172253/ffea768c-7064-11e6-9fc4-68817f42e97a.JPG)

One query seems to be run a lot (2 profiles concerned 1 and 4) : 

![bug1](https://cloud.githubusercontent.com/assets/11721263/18172270/168f6a14-7065-11e6-9488-2566e9314323.JPG)

Here is our setup : 
[sysinfo.txt](https://github.com/glpi-project/glpi/files/450027/sysinfo.txt)

**Comment by ladenree76000** [comment]
how many rows do you display ?
how many columns ?

the query on profiles runs for each row, this can explain that tere are many time the same query.

if i display 500 users ( from 3500)=> 1898 Queries took 0.388s

**Comment by ameurou** [comment]
Ok found the "problem" : column "number of tickets as requester". When it is selected, answer delay is good until 15 row then it grow up to at least 40 seconds... 

We don't need this column in our global view, so i've just drop it for now.

But 

> if i display 500 users ( from 3500)=> 1898 Queries took 0.388s

For only 40 users display => i got 79286 queries

**Comment by orthagh** [comment]
Hello @ameurou 

79286 is a huge amount of queries.
Could you post the number of entity set in your glpi ? List your plugins also ?

For the column "number of tickets as requester", yes, it could triggers some slow queries.
A possible bypass exists, you could force sorting by id instead of name. So, It usually execute instantly.
In some cases (with leftjoin/orderby/limit usage), mysql indexes couldn't be used and the query become slower in case of name sorting.

Here is a patch to test this default id sorting:
```diff
diff --git a/inc/search.class.php b/inc/search.class.php
index 8bea372..4689d25 100644
--- a/inc/search.class.php
+++ b/inc/search.class.php
@@ -137,7 +137,7 @@ class Search {
       // Default values of parameters
       $p['criteria']            = array();
       $p['metacriteria']        = array();
-      $p['sort']                = '1'; //
+      $p['sort']                = ''; //
       $p['order']               = 'ASC';//
       $p['start']               = 0;//
       $p['is_deleted']          = 0;
@@ -5038,7 +5038,7 @@ class Search {
 
       $default_values["start"]       = 0;
       $default_values["order"]       = "ASC";
-      $default_values["sort"]        = 1;
+      //$default_values["sort"]        = 1;
       $default_values["is_deleted"]  = 0;
 
       if ($CFG_GLPI['allow_search_view'] == 2) {
```

**Comment by ameurou** [comment]
We have 3 entitites set and these plugins : 

databases Version: 1.8.1
fusioninventory Version: 0.90+1.3
pdf Version: 1.0.2
ocsinventoryng Version: 1.2.2
reports Version: 1.9.1

> For the column "number of tickets as requester", yes, it could triggers some slow queries.

Actually, each SQL query run fast (debug says 5 seconds for 79286 queries), but script take 30 to 40 seconds to load. I was thinking about code issue instead of slow sql query.

I'm going to test the patch and let you know.

**Comment by orthagh** [comment]
Could you extract (or resume) theses queries and post it on a paste site (http://hastebin.com/ for example) ?

**Comment by ameurou** [comment]
I've copy/paste from GLPI debug the 15 firsts queries and a resume of the 2 queries iterated thousands times after

http://hastebin.com/kumuvuyudo.md

**Comment by orthagh** [comment]
```sql
SELECT `glpi_profiles`.*, '' AS transname, '' AS transcomment
FROM `glpi_profiles`
WHERE `glpi_profiles`.`id` = '4'	
```

Theses are very strange

**Comment by ameurou** [comment]
i've made quick tests : 

- On default user view on prod db (login, entitiy (profile),surname,emails,phone,location,active), i've got somes too : http://hastebin.com/uwahasujuc.md (full export)

- french db with only the root entity and a default ldap (active directory) server : this query is not executed

**Comment by ameurou** [comment]
These queries are related to entities : on fresh db with only root entity 

- add a child entity
- close/open admin session 
- load user page and look at glpi debug, queries are showing up

**Comment by orthagh** [comment]
Could you confirm you are using the dropdown translations system ?

**Comment by ameurou** [comment]
If you mean that one, yes !

![capture](https://cloud.githubusercontent.com/assets/11721263/18247335/35e12b36-7372-11e6-841b-2adad1f8d643.JPG)

**Comment by orthagh** [comment]
ok, i think i got it.
The culprit is the column "Number of tickets as requester".
Due to a bad group by/group_concat on glpi_profiles.name column, there will be number of profiles * number of ticket queries for each rows of this page.

Each of theses queries is pretty fast, but 79286 is an insane number.

I'm currently checking to add a DISCTINCT on profiles to avoid theses duplicates/

**Comment by orthagh** [comment]
ok. I can't distinct in fact, we have a row for each ticket before the group by in the mysql query
i manage to deduplicate the profiles data after in php.

Here is a patch:

```diff
diff --git a/inc/search.class.php b/inc/search.class.php
index 8bea372..43068c3 100644
--- a/inc/search.class.php
+++ b/inc/search.class.php
@@ -4181,7 +4181,9 @@ class Search {
                   $count_display = 0;
                   $added         = array();
                   for ($k=0 ; $k<$data[$num]['count'] ; $k++) {
-                     if (strlen(trim($data[$num][$k]['name'])) > 0) {
+                     if (strlen(trim($data[$num][$k]['name'])) > 0
+                         && !in_array($data[$num][$k]['name']."-".$data[$num][$k]['entities_id'],
+                                      $added)) {
                         $text = sprintf(__('%1$s - %2$s'), $data[$num][$k]['name'],
                                         Dropdown::getDropdownName('glpi_entities',
                                                                   $data[$num][$k]['entities_id']));
@@ -4198,14 +4200,12 @@ class Search {
                         if (!empty($comp)) {
                            $text = sprintf(__('%1$s %2$s'), $text, "(".$comp.")");
                         }
-                        if (!in_array($text,$added)) {
-                           if ($count_display) {
-                              $out .= self::LBBR;
-                           }
-                           $count_display++;
-                           $out     .= $text;
-                           $added[]  = $text;
+                        if ($count_display) {
+                           $out .= self::LBBR;
                         }
+                        $count_display++;
+                        $out     .= $text;
+                        $added[]  = $data[$num][$k]['name']."-".$data[$num][$k]['entities_id'];
                      }
                   }
                   return $out;
@@ -4220,7 +4220,9 @@ class Search {
                   $count_display = 0;
                   for ($k=0 ; $k<$data[$num]['count'] ; $k++) {
                      if (isset($data[$num][$k]['name'])
-                         && (strlen(trim($data[$num][$k]['name'])) > 0)) {
+                         && (strlen(trim($data[$num][$k]['name'])) > 0)
+                         && !in_array($data[$num][$k]['name']."-".$data[$num][$k]['profiles_id'],
+                                      $added)) {
                         $text = sprintf(__('%1$s - %2$s'), $data[$num][$k]['name'],
                                         Dropdown::getDropdownName('glpi_profiles',
                                                                   $data[$num][$k]['profiles_id']));
@@ -4237,14 +4239,12 @@ class Search {
                         if (!empty($comp)) {
                            $text = sprintf(__('%1$s %2$s'), $text, "(".$comp.")");
                         }
-                        if (!in_array($text,$added)) {
-                           if ($count_display) {
-                              $out .= self::LBBR;
-                           }
-                           $count_display++;
-                           $out    .= $text;
-                           $added[] = $text;
+                        if ($count_display) {
+                           $out .= self::LBBR;
                         }
+                        $count_display++;
+                        $out    .= $text;
+                        $added[] = $data[$num][$k]['name']."-".$data[$num][$k]['profiles_id'];
                      }
                   }
                   return $out;
```

**Comment by ameurou** [comment]
Page know loading in 5 seconds with a limited number of queries.

Looks good !

**Comment by orthagh** [comment]
I pushed the fix on master.
I think we can close

**Comment by ameurou** [comment]
Yes, good for me.
