### ISSUE TITLE
[GLPI 9.5.5][PDF 2.0.0] TCPDF Error

### ISSUE THREAD

**Issue by ASLLR** [glpi-project/glpi#9159]
**Describe the bug**

Hi,

i'was update recently my GLPI and all of plugins. Now, randomly,  when i generate a pdf from ticket i've an error message who tell me :

TCPDFERROR : [Image] : Unable to get the size of the image : [URL of Ticket]

do you have any idea why i have this ?

Best Regards

**Page(s) URL**

http://server/glpi/plugins/pdf/font/export.php

**Comment by cedric-anne** [comment]
Hi,

Your problem seems related to PDF plugin. Please open an issue on this plugin reprository.

Regards
