### ISSUE TITLE
Operating system informations in DB

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#918]
Hello,

Some informations on operating systems have been added in the FusionInventory plugin, I guess that should be done in core. It also rework the database structure, exporting OS informations into several tables.

I've reported the issue on the plugin side:
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1920

Since it will be required to change the database structure, it can't reach 9.1; but maybe one of the future releases.

**Comment by remicollet** [comment]
How many new fields are needed to store the information retrieved by FusionInventory ?

If only 1-2 new dropdown, IMHO, seems something which can be fixed in 9.1 to avoid to much change and facilitate coordination between both projects.

**Comment by ddurieux** [comment]
No, we are in RC, so not modify DB structure or add features now...

**Comment by wawax** [comment]
Hi David.

Could you explain what is the need for these new fields ? What are the uses cases ? What does it brings ?
Do we need to take it in account in rules engines and reports ?

Thank you :)

**Comment by ddurieux** [comment]
See specs here: https://github.com/fusioninventory/fusioninventory-for-glpi/issues/1295#issuecomment-222272332

**Comment by wawax** [comment]
@tsmr what do you think about this discussion ? 
Are these new informations relevant in OCS case ?

**Comment by tsmr** [comment]
In XML from OCS, for example : 
```
* OSNAME : Microsoft Windows 10 Entreprise
* OSVERSION : 10.0.10240
* ARCH : x86 64 bit
```
So OCSNAME contains already the two fields (OS name / OS edition) & so i need to explode the original data for use two fields if this is the goal of this thread.

Kernel name & version are not used by OCS, i think.
