### ISSUE TITLE
[9.5.5]  Suivi tickets : Affichage à supprimer

### ISSUE THREAD

**Issue by falco2001** [glpi-project/glpi#9187]
Bonjour,
J'ai dans le cas d'une réponse à un message clos le message suivant :

 ```
<!-- The "invisibleIntroduction" is the text used for short preview of the email before the user opens it (50 characters max). Sometimes, you do not want to show this message depending on your design but this text is highly recommended. You do not have to worry if it is hidden, the next
> will automatically center and apply to the width 100% and also shrink to 50% if the first 

```

je voudrais supprimer ce message.

J'ai regardé  dans notificationtargetticket.class mais cette fois mes modifications n'ont pas d'effet.

Dans le css de la page affichée je vois une class flexibleContainer et flexibleContainerCell que je devrais passer à display:none mais impossible de trouver cette classe dans les css et dans le code ni en base !

Merci pour votre aide.

Remarque :
j'avais fait cceci en 9.3.3 mais ici rien ne marche :
mailcollector.class.php
  * ligne 1066
```

// => to handle link in Ticket->post_addItem()
            $tkt['_linkedto'] = $tkt['tickets_id'];
            unset($tkt['tickets_id']);
            
            // ICI Debut seul  passage pour ticket close //YD
            // il faut utiliser strstr et substr pas autre chose ..
            
            //debut de message avec chaine de caractères
            
            //$carToDelimite = 'http-equiv="Content-Type" content="text/html; charset=UTF-8">';
            $carToDelimite = 'charset=UTF-8">';
            
           $string = $tkt['content'];    
           $tkt['content'] = strstr($string, $carToDelimite)  ;
                       
            //fin de message avec chaine de caractères et <BR />
            $carToDelimite2 = 'au dessus de cette ligne';
            $string = $tkt['content'];    
            $tkt['content'] = substr($string, 25, strpos($string,$carToDelimite2)); 
            
            // ICI Fin seul  passage pour ticket close //YD
```

**Comment by falco2001** [comment]
re,
pourquoi mon message est invalid ? 
Je veux juste savoir ou supprimer ce message et/ou comment accèder à la balise CMS lexibleContainerCell
Merc ià vous

**Comment by trasher** [comment]
Because we ask to write in english, and you write in french, and we ask for several information you did not even provide.
See https://raw.githubusercontent.com/glpi-project/glpi/9.5/bugfixes/ISSUE_TEMPLATE.md.

Also, it seems you are not reporting a bug, so I close.

Please use [forums](http://forum.glpi-project.org) to get community support; [suggestion website](http://suggest.glpi-project.org) for RFE; or apply for professional support.
