### ISSUE TITLE
Operating system informations display

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#919]
Hello,

In PR #373, the way operating system is displayed has been changed: a popup has been added to hide some infromations that does not seems to be important on a daily usage.

It seems that some users does not like that :) I'm not really fan myself, and it sounds inconsistent with GLPI display globally (I can't remember I see another popup).

The point is the computer tab becomes very huge, a complete rework of the display is probably something to do, but this would be a very important work, and that cannot be done quickly; we'll have to think about it some time, and then spend a lot of time to develop :)

For the moment, what I propose is:
1- display back OS informations as they were, or alternatively put them in a separate tab (maybe there is too few informations for a specific tab, even with data that could be added in #918)
2- add a resume tab wich will be displayed per default, and that will show only "important" data for the computer, retrieved from other tabs (we'll need to define what "important data" are).

What do you think?

**Comment by ddurieux** [comment]
Add a new tab, it's better solution

**Comment by remicollet** [comment]
As commented on PR #373, for consistency, I'm +1 for a new "OS" tab.

**Comment by trasher** [comment]
Here is what I get so far... First, the OS tab itself:
![os_tab](https://cloud.githubusercontent.com/assets/224733/18245126/d2f55ce4-7363-11e6-90d4-a828694ff752.png)

This sounds correct, except the "Computer" title on the top; I was not able to remove it since it's echo-ed from showFormheader() method...

In the main tab, I've removed OS informations; and also moved a bit Fusioninventory informations:
![computer_tab_noos](https://cloud.githubusercontent.com/assets/224733/18245132/d89a7788-7363-11e6-838a-6de67ac37673.png)

**Comment by trasher** [comment]
If that sounds good to you, I'll make a PR today to get this in the 9.1 releae.

**Comment by ddurieux** [comment]
For the tab yes ;)
