### ISSUE TITLE
DO NOT LOAD SOME FILES OF THE SAME TYPE

### ISSUE THREAD

**Issue by monroyc** [glpi-project/glpi#9192]
Hello everyone, I have a problem with the glpi management, in the follow-ups, when receiving the tickets in some cases the pasted image is not displayed, when it is tried to respond through the follow-ups, for example 10 pasted images are attached, only 5 to 10 images are attached, the others come out as follows in mails.

![imagen](https://user-images.githubusercontent.com/86063003/122582324-a5400f80-d01d-11eb-8105-92003b514c5a.png)
![imagen](https://user-images.githubusercontent.com/86063003/122582695-0cf65a80-d01e-11eb-80ee-5bce3ca1152b.png)

It is the same with the attached files, for example a pdf is attached, it does not load the first time, it has to be re-generated or renamed to upload the file, it was tried to upload the capacity but still it is not exceeded the problem

1. Go to test like i'm a user, i go to send a mail

![imagen](https://user-images.githubusercontent.com/86063003/122584752-5647a980-d020-11eb-93d1-c0c1aeebb40b.png)

2I add pasted images as a technician
![imagen](https://user-images.githubusercontent.com/86063003/122585880-99564c80-d021-11eb-8391-1b80cf33f129.png)
![imagen](https://user-images.githubusercontent.com/86063003/122585932-a70bd200-d021-11eb-872f-a77a5ac39415.png)

3. Scroll down to Añadir

![imagen](https://user-images.githubusercontent.com/86063003/122586003-bbe86580-d021-11eb-8d8b-13eb44a69f04.png)
![imagen](https://user-images.githubusercontent.com/86063003/122586036-c7d42780-d021-11eb-9b51-028f8f565cba.png)

** GLPI setup 

[code] &nbsp; GLPI 9.5.3 ( =&gt; /var/www/html) Installation mode: TARBALL
--

Operating system: Linux VSRV-SDESK-TIC-02 4.9.0-15-amd64 #1 SMP Debian 4.9.258-1 (2021-03-08) x86_64 PHP 7.4.15 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bcmath, 	bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="256M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="10M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at servicedesk.fondesurco.com Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.4.17-MariaDB-1:10.4.17+maria~stretch-log 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory &gt; 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.4.17) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/config has been validated. Write access to /var/www/html/files has been validated. Write access to /var/www/html/files/_dumps has been validated. Write access to /var/www/html/files/_sessions has been validated. Write access to /var/www/html/files/_cron has been validated. Write access to /var/www/html/files/_graphs has been validated. Write access to /var/www/html/files/_lock has been validated. Write access to /var/www/html/files/_plugins has been validated. Write access to /var/www/html/files/_tmp has been validated. Write access to /var/www/html/files/_cache has been validated. Write access to /var/www/html/files/_rss has been validated. Write access to /var/www/html/files/_uploads has been validated. Write access to /var/www/html/files/_pictures has been validated. Write access to /var/www/html/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: /var/www/html GLPI_CONFIG_DIR: /var/www/html/config GLPI_VAR_DIR: /var/www/html/files GLPI_MARKETPLACE_DIR: /var/www/html/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/files GLPI_CACHE_DIR: /var/www/html/files/_cache GLPI_CRON_DIR: /var/www/html/files/_cron GLPI_DUMP_DIR: /var/www/html/files/_dumps GLPI_GRAPH_DIR: /var/www/html/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/files/_locales GLPI_LOCK_DIR: /var/www/html/files/_lock GLPI_LOG_DIR: /var/www/html/files/_log GLPI_PICTURE_DIR: /var/www/html/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/files/_plugins GLPI_RSS_DIR: /var/www/html/files/_rss GLPI_SESSION_DIR: /var/www/html/files/_sessions GLPI_TMP_DIR: /var/www/html/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/locales GLPI_VERSION: 9.5.3 GLPI_SCHEMA_VERSION: 9.5.3 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2020 GLPI_MOD_DIR: /var/www/html/plugins/mod

htmlawed/htmlawed version 1.2.5 in (/var/www/html/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/vendor/sabre/http/lib) sabre/uri in (/var/www/html/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/vendor/symfony/console) scssphp/scssphp in (/var/www/html/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/vendor/ramsey/uuid/src) psr/log in (/var/www/html/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/vendor/paragonie/sodium_compat/src)

Server: '192.168.13.2', Port: '389', BaseDN: 'DC=fondesurco,DC=com', Connection filter: 		'(&amp;(objectCategory=person)(objectClass=user)(mail=*))', RootDN: 'fondesurco\ldap', Use TLS: none

Not active

Way of sending emails: SMTP+TLS (*****@*.org.*@smtp.gmail.com)

Name: '***@*.org.pe' Active: Yes 	Server: '{pop.gmail.com:995/pop/ssl/novalidate-cert}' Login: '*****@*.org.pe' Password: Yes Name: 'a*****s@*.org.pe' Active: Yes 	Server: '{pop.gmail.com:995/pop/ssl/novalidate-cert}' Login: '*****@*.org.*' Password: Yes

actualtime           Name: ActualTime                     Version: 1.4.0      State: Enabled 	databases            Name: Bases de datos                 Version: 2.3.1      State: Enabled 	datainjection        Name: Data injection                 Version: 2.8.1      State: Not installed 	escalade             Name: Escalado                       Version: 2.6.0      State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	airwatch             Name: GLPi Airwatch Connector        Version: 1.5.0      State: Enabled 	mod                  Name: GLPI Modifications             Version: 2.0.2      State: Enabled 	ldapcomputers        Name: LDAP computers                 Version: 0.4.1      State: Enabled 	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.1      State: Enabled 	satisfaction         Name: More satisfaction              Version: 1.5.1      State: Enabled 	dashboard            Name: Tablero de informes            Version: 0.9.9      State: Enabled 	badges               Name: Tarjetas identificadoras       Version: 2.6.0      State: Not installed 	ticketmail           Name: Ticket Mail                    Version: 3.4.0      State: Not installed 	useditemsexport      Name: Used items export              Version: 2.4.0      State: Not installed
[/code]

**Comment by trasher** [comment]
Hi,

You should first try with latest release or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22)
