### ISSUE TITLE
GLPI 0.9.0.5 retrocompatibility issue with IE8 :: proposed fixes

### ISSUE THREAD

**Issue by etiquet** [glpi-project/glpi#920]
Dear community,

Some organisation have still massive IE8 deployment.
We've just spend a couple of days trying fixing IE retrocompatibility issues with GLPI 0.9.0.5 and RC2
Those fix have been tested (basic) with recent Safari, Chrome, Firefox, IE 11, and Egde

Here are the proposed fixes.

1/ ISSUE ONE
IE8 repeat css background image randomly when using the syntax `<span .../>` 
the xhtml method `... />`for closing span is not properly recognized by IE8
The following sequence `<span ...>` followed by a separated `</span>` works.

The issue gives following aspect :
![capture d ecran 2016-09-02 a 21 24 10](https://cloud.githubusercontent.com/assets/18629332/18215839/a3b3621c-7153-11e6-9994-dce300488366.png)

note:  In simplified display the first Menu in `c_menu` section have a phantom effect (appear twice) with error on page structure.

So ... In html.class.php the following code works. (search and replace the entire paragraph)

```
  /// Prefs / Logout link
  echo "<div id='c_preference' >";
  echo "<ul>";

  echo "<li id='deconnexion'>";
  echo "<a href='".$CFG_GLPI["root_doc"]."/front/logout.php";
        /// logout witout noAuto login for extauth
  if (isset($_SESSION['glpiextauth']) && $_SESSION['glpiextauth']) {
     echo "?noAUTO=1";
  }

  echo "' title=\"".__s('Logout')."\">";
  echo "<span id='logout_icon' title=\"".__s('Logout').
         "\"  alt=\"".__s('Logout')."\" class='button-icon'>";
  echo "</span></a>";// MODIF
  echo "</li>\n";


  echo "<li id='preferences_link'><a href='".$CFG_GLPI["root_doc"]."/front/preference.php' title=\"".
             __s('My settings')."\">";
  echo "<span id='preferences_icon' title=\"".__s('My settings').
         "\"  alt=\"".__s('My settings')."\" class='button-icon'> 
        </span>";

  // check user id : header used for display messages when session logout
  if (Session::getLoginUserID()) {
     echo "<span id='myname'>";
     echo formatUserName (0, $_SESSION["glpiname"], $_SESSION["glpirealname"],
                          $_SESSION["glpifirstname"], 0, 20);
     echo "</span>";
  }
  echo "</a></li>";  

  /// Bookmark load
  echo "<li id='bookmark_link'>";
  Ajax::createIframeModalWindow('loadbookmark',
                                $CFG_GLPI["root_doc"]."/front/bookmark.php?action=load",
                                array('title'         => __('Load a bookmark'),
                                      'reloadonclose' => true));
  echo "<a href='#' onClick=\"".Html::jsGetElementbyID('loadbookmark').".dialog('open');\">";
  echo "<span id='bookmark_icon' title=\"".__s('Load a bookmark').
         "\"  alt=\"".__s('Load a bookmark')."\" class='button-icon'></span>";// MODIF
  echo "</a></li>";// MODIF


  echo "<li id='help_link'><a href='".
             (empty($CFG_GLPI["central_doc_url"])
               ? "http://glpi-project.org/help-central"
               : $CFG_GLPI["central_doc_url"])."' target='_blank' title=\"".__s('Help')."\">".
              "<span id='help_icon' title=\"".__s('Help').
              "\"  alt=\"".__s('Help')."\" class='button-icon'></span>"; // MODIF
       "</a></li>"; // MODIF
     echo "";

  echo "<li id='language_link'><a href='".$CFG_GLPI["root_doc"].
             "/front/preference.php?forcetab=User\$1' title=\"".
             addslashes(Dropdown::getLanguageName($_SESSION['glpilanguage']))."\">".
             Dropdown::getLanguageName($_SESSION['glpilanguage'])."</a></li>";


  /// Search engine
  echo "<li id='c_recherche'>\n";
  if ($CFG_GLPI['allow_search_global']) {
     echo "<form method='get' action='".$CFG_GLPI["root_doc"]."/front/search.php'>\n";
     echo "<span id='champRecherche'><input size='15' type='text' name='globalsearch'
                                     placeholder='". __s('Search')."'>";
     echo "</span>";
     Html::closeForm();
  }
  echo "</li>";
  echo "</ul>";
  echo "</div>\n";
  echo "</div>";
```

2/ ISSUE TWO
Menu transparency are gone with IE8
Reasons : background: rgba(255, 255, 255, 0.9);  does not work for IE8

FIX : override the following css entry in the css/styles.css or in your palette preferred css if you don't want to modify the standard style.css files

ul#menu ul.ssmenu {
   top:5px;
   left: 0px;
    width: 144px;
    border: 1px solid #CCCCDD;
    background: #FEFEFF; 
   -moz-box-shadow: 0px 0px 0px 0px #BCB6B3;
   -webkit-box-shadow: 0px 0px 0px 0px #BCB6B3;
   box-shadow: 0px 2px 2px 1px #BCB6B3; 
    opacity: 0.9;
    -ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=90)"; // first!
    filter: alpha(opacity=90);                  // second! 
}

3/ ISSUE 3 WITH bootstrap breadcrumb ( the 3rd menu area, below the top left logo)
Issue : there is no background and difficult to locate the current 
did not spend lot of time, but the simple fix is to add a background to the css item 

.breadcrumb_item {
  background-color: #F2F2F2; // modifier pour IE8 vs bootstrap
}

either in the default styles.css or your preferred style.

Hope it help. 
And Community what about integrating those little changes for future version ?

**Comment by etiquet** [comment]
it seems the syntax were gone for the first issue `<span .../>` not properly recognized. `<span ...>` followed by `</span>` works.

The visual gives following aspect :

![capture d ecran 2016-09-02 a 21 24 10](https://cloud.githubusercontent.com/assets/18629332/18215839/a3b3621c-7153-11e6-9994-dce300488366.png)

**Comment by etiquet** [comment]
I tested with RC2 the fixes still works. I am new to github, could someone performs the change ?
# the change consist to replace the section form : "<div id='c_preference' >  until  ///Main menu 
# within following function (or replace all file) 
[html.class.php.zip](https://github.com/glpi-project/glpi/files/453275/html.class.php.zip)

# function helpHeader($title, $url='') {
# function header($title, $url='', $sector="none", $item="none", $option="")

with many thanks

**Comment by orthagh** [comment]
Hello @etiquet 

> I am very new to github with no pull request right, could someone please integrate the change for future releases on the following file ?

You could the fork button on the top right of the project page, push your changes on your fork and submit a pull request.

Your fixes seems good. We decided to drop efforts on IE8 compatibility this year.
But a pull request adding better compatibility with that browser will still be accepted.

**Comment by etiquet** [comment]
Hi,

I just did the newbranch stuff and update my change to the main branch and commit it. (3 files)
I try to click on the publish / pull request the GIt application (mac) says I don’t have the right, I guess this is normal.
Hope I did things right. please provide guidance otherwise.

Kind regards,
Eric

**Comment by trasher** [comment]
Hi @etiquet ; I guess you are trying to push on the main glpi clone, on which you do not have ACLs.

I do notk now wich git client your are using, but you can basically add a new remote with the url from your clone, and then push your changes on it. You'd better work on a different branch than master also.

An example on the command line (from the glpi clone directory):
    $ git branch 0.90/ie8_compat
    $ git remote add etiquet https://github.com/etiquet/glpi.git
    $ git push -u etiquet 0.90/ie8_compat

At some point (on the push I guess), it will ask you your github credentials. Hope that helps.

**Comment by etiquet** [comment]
ok just did the procedure and request for a pull. everything looks fine ?

**Comment by trasher** [comment]
Hello, that sounds correct, yes. I've just changed the PR against 0.90/bugfixes brach instead of master; let's wait for someone to make a review of this ;)

**Comment by trasher** [comment]
Done, see #1982
