### ISSUE TITLE
display lists are not being compresseed correctly

### ISSUE THREAD

**Issue by we-sell-bags** [glpi-project/glpi#9202]
/glpi/front/networkequipment.php
GLPI 9.5.5 (/glpi => /usr/share/glpi)
Installation mode: TARBALL

Operating system: Linux glpi 3.10.0-1160.25.1.el7.x86_64 #1 SMP Wed Apr 28 21:49:45 UTC 2021 x86_64
PHP 7.3.28 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, sockets, sodium, sqlite3, standard,
	sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)

plugin list
actualtime           Name: ActualTime                     Version: 1.5.0      State: Enabled
	fields               Name: Additionnal fields             Version: 1.12.4     State: Enabled
	advancedplanning     Name: advancedplanning               Version: 0.2.0      State: Enabled
	news                 Name: Alerts                         Version: 1.9.0      State: Enabled
	badges               Name: Badges                         Version: 2.6.0      State: Enabled
	barcode              Name: Barcode                        Version: 2.5.0      State: Enabled
	camerainput          Name: Camera Input                   Version: 1.0.0      State: Not installed
	datainjection        Name: Data injection                 Version: 2.9.0      State: Installed / not activated
	escalade             Name: Escalation                     Version: 2.6.2      State: Enabled
	formcreator          Name: Form Creator                   Version: 2.11.2     State: Enabled
	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled
	geninventorynumber   Name: Inventory number generation    Version: 2.5.0      State: Enabled
	uninstall            Name: Item's Lifecycle (uninstall)   Version: 2.7.0      State: Enabled
	mreporting           Name: More Reporting                 Version: 1.7.2      State: Enabled
	genericobject        Name: Objects management             Version: 2.10.1     State: Enabled
	tag                  Name: Tag Management                 Version: 2.8.1      State: Enabled
	taskdrop             Name: TaskDrop                       Version: 1.2.0      State: Enabled
	treeview             Name: Tree view                      Version: 1.9.0      State: Enabled
	useditemsexport      Name: Used items export              Version: 2.4.0      State: Enabled

some of the mac address lists are compressed into "tooltip" boxes only displaying the first one
others display teh full list of all addresses ,which can be excessive

![list-pic](https://user-images.githubusercontent.com/25189116/123218189-ff4d4300-d4fd-11eb-9fee-82a63fc4b0e3.jpg)

**Comment by orthagh** [comment]
In Setup > General, you'll find a parameter to control when the summary starts to show:

![image](https://user-images.githubusercontent.com/418844/123219003-b16c1700-d4cc-11eb-83f6-8f3565d283cf.png)

**Comment by we-sell-bags** [comment]
I already had it set to 250 & still not enough
500 seemed to fix it.

but it still does not do the  "networking - ip " addresses even if set to 1,000

**Comment by we-sell-bags** [comment]
ah... ok it is reduce the size not increase it.....
