### ISSUE TITLE
Imap/pop mailgate Office365

### ISSUE THREAD

**Issue by Razorbob** [glpi-project/glpi#9215]
**Describe the bug**

Get Emails via POP and IMAP from Office365 with openssl and selfsigned Cert.

**Page(s) URL**

http://xxxxx/glpi/front/mailcollector.form.php?id=1

**To reproduce**

1) Add a Simple Connection to your Office365 Mailbox
2) test connection
3) An error occured trying to connect to collector.
    last request failed

**Expected behavior**

No Connection Errors

**Logs**

```
glpi/files/_log/php-errors.log

[2021-06-28 12:28:23] glpiphplog.ERROR: MailCollector::collect() in /var/www/html/glpi/inc/mailcollector.class.php line 689
An error occured trying to connect to collector. last request failed
 #0 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Pop3.php(192): Laminas\Mail\Protocol\Pop3->readResponse()
#1 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol/Pop3.php(244): Laminas\Mail\Protocol\Pop3->request()
#2 /var/www/html/glpi/vendor/laminas/laminas-mail/src/Storage/Pop3.php(155): Laminas\Mail\Protocol\Pop3->login()
#3 /var/www/html/glpi/inc/toolbox.class.php(2348): Laminas\Mail\Storage\Pop3->__construct()
#4 /var/www/html/glpi/inc/mailcollector.class.php(1324): Toolbox::getMailServerStorageInstance()
#5 /var/www/html/glpi/inc/mailcollector.class.php(683): MailCollector->connect()
#6 /var/www/html/glpi/front/mailcollector.form.php(88): MailCollector->collect()


```
<img width="941" alt="Helpdesk_problem_1" src="https://user-images.githubusercontent.com/8940098/123624065-717b9b80-d80e-11eb-8819-0b1fb2c2628a.PNG">

**Comment by Razorbob** [comment]
I am stupid.
I forgot to enable it in the mailbox settings for the specific Mailbox in office 365.

**Comment by loziu00** [comment]
> tell me Razorbob , what you enable it in the mailbox settings and where i didn't see nothing in  mailbox to enable , i have the same problem

**Comment by loziu00** [comment]
hi, in my case the problem was related to the disabled IMAP protocol in the Microsoft Admin console for the user responsible for receiving mail

![imap_glpi](https://user-images.githubusercontent.com/115995961/232593795-9cc2a071-38c0-49f2-8bec-397c490ee504.png)
