### ISSUE TITLE
Personal_Token is missing in GLPI API

### ISSUE THREAD

**Issue by prybak** [glpi-project/glpi#9219]
**Describe the bug**

GLPI API doesn't return users personal/api_token if you are getting user data from super-admin profile.
This means that you cannot impersonate as a user using external service that integrates with GLPI.

**Page(s) URL**

Ref.: https://forum.glpi-project.org/viewtopic.php?id=278609
https://forum.glpi-project.org/viewtopic.php?id=162759

**To reproduce**

1. Get data from user/{userId} endpoint as a Super-admin user.
2. JSON doesn't return personal/api tokens. You can only get dates related to those tokens.

**Expected behavior**

Getting data as super-admin should return also tokens to perform impersonate operation.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**
N/A

**Comment by cconard96** [comment]
Just like a user's password should never be exposed through the API or any other method, I don't think a user's API token's should be visible to anyone except themselves. For a good impersonation feature, you should be able to act as another user without knowing their secrets. It doesn't matter how privileged your account is.
Giving access to a user's secrets bypasses any accountability logging which is done from a user impersonating another. When impersonating another user from the web GUI, logged actions clearly show that you are impersonating another user.

Instead, this seems to me like a request to add the ability to impersonate a user via the API which should only require the right permissions to impersonate other users and the user's username, ID, or some other public information.

**Comment by prybak** [comment]
Is there any workaround for this issue?

**Comment by OscarBeiro** [comment]
Impersonate is a Debug feature (and a pretty good one :)). 
I can only see trouble from sharing tokens in any possible way.

**Comment by prybak** [comment]
Well yes, but there should be an option to authorize user somehow and make actions in his/her name. 
Just like in some online services where you can grab identity from any identity server and perform actions as a user using your service/software. This is nothing surprising/rare in the IT world.
