### ISSUE TITLE
Knowlegde Base: upload images to the server

### ISSUE THREAD

**Issue by jsamaniegog** [glpi-project/glpi#922]
When you copy or insert an image the reference is a internet URL but the users can't access.

The best way is copy the image to the server and link to this.

Than you.

**Comment by orthagh** [comment]
Hello @jsamaniegog 

I couldn't replicate the issue you mention.
Could explain in detail the process you follow to trigger it ? Also please provide information about your glpi version.

**Comment by jsamaniegog** [comment]
Hi @orthagh 

Sorry for my English, I did not explain well ...

This is not an error but a feature request. The problem is that if you add an image in the article that refers to a URL that the user can not access he can not see the image.

To solve this we should upload the image to GLPI server. I think.

Regards.

**Comment by orthagh** [comment]
oh ok.

Yeah, it's a missing feature, one of my colleagues (@stonebuzz) are currently working on this featurehttps://github.com/stonebuzz/glpi/tree/9.1/uploadAndRichText 
It will not ship in the 9.1 release, but probably in the next major one

The feature consist to direct paste of the image in the texteditor. That paste will trigger the upload in documents base and replace the image by a link.

**Comment by jsamaniegog** [comment]
Cool!
Thank you @orthagh

**Comment by trasher** [comment]
Done in master branch; will be available in the 9.2 release
