### ISSUE TITLE
Add a way to remove/edit form title added from showFormHeader method

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#924]
When creating a form, we use CommonDBTM::showFormHeader(), wich will display a title it will guess from the entity type - among many others.

In some cases, we should want to hide this title (or maybe force it to another string); the actual code does not permit this.

As an example, you can see the OS tab screenshot on #919; the "Computer" title is automatically added from the method, but here that makes no sense, and should be removed/replaced.

Any thoughts?

**Comment by tomolimo** [comment]
We may add an optional title to the $options parameter?
if empty then keep title guesses like today, and if filled then take the passed value.

**Comment by ddurieux** [comment]
If it is NULL => use like now, if filled or empty, use this value (like this, we can manage the case we don't want a title)

**Comment by remicollet** [comment]
+1

**Comment by trasher** [comment]
OK, many thanks to you all; I'll work on it!

So if empty, or false, no title will be displayed.
I propose to name this option "formtitle", or even simple "title", I guess it would be self explaining enough :)

**Comment by orthagh** [comment]
Maybe, we need a similar option on footer.
On the provided screenshot, imo, the footer is not needed.

The creation/modifications dates refers to computer object, not only the os sub part.

**Comment by trasher** [comment]
You are right; we've discussed this with @wawax yesterday; but since it was not part of the initial ticket and the header was done, I had in min to create another ticket and PR for this specific part.
