### ISSUE TITLE
glpi 9.5.5  tickets : customed colors -> still wrong color for "high priority"

### ISSUE THREAD

**Issue by mirda123** [glpi-project/glpi#9241]
**Describe the bug**

I changed the 6 priority colors in general setup / default values , with purple colors. 
But it stil remain "red color" for the tickets if priority is : High . 
If priority si "very high, medium, very low, it's ok.
If very low, not sure it's ok either.

**To reproduce**

glpi 9.5.3 and glpi 9.5.5
1. Go to general / setup / default value change the 6 priority colors with purple colors
2. check priority colors  : not ok for "high priority "

**Expected behavior**
purple color

**Screenshots**

![color1](https://user-images.githubusercontent.com/78594318/124256448-9bdd9980-db2b-11eb-9795-c0a87513527c.jpg)
![color4](https://user-images.githubusercontent.com/78594318/124256461-a009b700-db2b-11eb-899c-e9bc669ca83b.jpg)

**Comment by mirda123** [comment]
can someone confirm if it's a bug please ?  : ) many thanks

**Comment by mirda123** [comment]
noone ?

**Comment by mirda123** [comment]
hi, pb is still there, waitinf for a fix please, thanks

**Comment by mirda123** [comment]
hi, pb is still there, waiting for a fix please, thanks

**Comment by mirda123** [comment]
hi, pb is still there glpi 9.5.6, waiting for a fix please, thanks

**Comment by cconard96** [comment]
Cannot recreate on latest 9.5 commit.

![Screenshot from 2022-01-22 10-49-39](https://user-images.githubusercontent.com/17678637/150645658-85c7ea61-d0ef-41df-a025-ecc35a8d274b.png)
1. Ensured the colors were all set to null in my user's personalization tab
2. Set colors in General setup
3. Verified the colors set in General showed on Assistance tab
4. Set custom colors in my user
5. Verified my colors showed on Assistance tab of General setup

It sounds like the user you are testing with has a custom color set for the High priority.

**Comment by mirda123** [comment]
Hi thank you for your answer, i think you're right, it's something related to user's personalization tab but only one of the 6 , which is strange.. because nobody changed it there.. anyway.. i tried to change the personnalised color ==> it changed = OK !

Now i'm trying to "reset" to null the user's personalization tab, because i want the general colors to apply fir the user... please can  you describe how you " set to null in you user's personalization tab"   I tried "0"  everywhere, but now i have a black color everywhere : )

Once i solve that, the ticket can be closed. : )

![color](https://user-images.githubusercontent.com/78594318/150674085-83c17499-1834-4fe2-9003-6b29eddf4d56.jpg)

**Comment by cconard96** [comment]
Unfortunately, there is no ability to do this in the GLPI web interface.

In a SQL command:
```mysql
UPDATE `glpi_users` 
SET 
    priority_1 = NULL,
    priority_2 = NULL,
    priority_3 = NULL,
    priority_4 = NULL,
    priority_5 = NULL,
    priority_6 = NULL
WHERE
    id = 2;
```
Replace the "id" with the user's ID or remove the WHERE clause completely to reset everyone's priority colors.

The only other option is to lock personalizations for the profile (Remove Update right under Setup > Personalization in affected profiles). This would force them to use the defaults under the General configuration but affects more than just these colors.
