### ISSUE TITLE
Error: Table 'glpi.glpi_rulemailcollectors' doesn't exist Glpi  ver 9.5.5

### ISSUE THREAD

**Issue by sudhakarang** [glpi-project/glpi#9246]
Dear team ,
    I am getting following error in mysql logs 

[2021-07-03 16:43:52] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: SELECT `glpi_rulemailcollectors`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_rulemailcollectors` WHERE `glpi_rulemailcollectors`.`id` = '271'
  Error: Table 'glpi.glpi_rulemailcollectors' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:876                          DBmysqlIterator->execute()
  inc/dropdown.class.php:376                         DBmysql->request()
  ajax/comments.php:97                               Dropdown::getDropdownName()
  {"user":"6@kits"} 

**Describe the bug**

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**
In  rules engine I am trying to insert a new Criterion in mail receiver rules, purpose is to read cc user and assign entity based on his profile. 
in /inc/rulemailcollector.class.php
     
      $criterias['cc']['name']                        = __('cc in email header');
      $criterias['cc']['table']                       = '';
      $criterias['cc']['type']                        = 'text';
 

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
[2021-07-03 16:43:52] glpisqllog.ERROR: DBmysql::query() in /var/www/html/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: SELECT `glpi_rulemailcollectors`.*, '' AS `transname`, '' AS `transcomment` FROM `glpi_rulemailcollectors` WHERE `glpi_rulemailcollectors`.`id` = '271'
  Error: Table 'glpi.glpi_rulemailcollectors' doesn't exist
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:876                          DBmysqlIterator->execute()
  inc/dropdown.class.php:376                         DBmysql->request()
  ajax/comments.php:97                               Dropdown::getDropdownName()
```
![image](https://user-images.githubusercontent.com/22138949/124442243-275c6200-dd9a-11eb-8bb1-3afbe0f96f21.png)

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

--
<html>
<body>

[code]   GLPI 9.5.5 (/glpi => /var/www/html/glpi) Installation mode: TARBALL
--

Operating system: Linux kits 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, gmp, hash, iconv, imagick, imap, intl, json, ldap, 	libxml, mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, pspell, readline, session, shmop, 	snmp, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, 	xsl, zip, zlib) Setup: max_execution_time="360" memory_limit="256M" post_max_size="100M" safe_mode="" session.save_handler="files" 	upload_max_filesize="100M"  Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at 10.20.1.5 Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Server Software: Ubuntu 20.04 	Server Version: 10.3.25-MariaDB-0ubuntu0.20.04.1 	Server SQL Mode:  	Parameters: glpi@127.0.0.1/glpi 	Host info: 127.0.0.1 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.3.25) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to files directory is protected

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/var/www/html/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/html/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/html/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/html/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/html/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/html/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/html/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/html/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/html/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/html/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/html/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/html/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/html/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/html/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/html/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/html/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/html/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/html/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/html/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/html/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/html/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/html/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/html/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/html/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/html/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/html/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/html/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/html/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/html/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/html/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/html/glpi/vendor/paragonie/sodium_compat/src) phpCas version 1.3.8 in (/usr/share/php/CAS/source)

Not active

Way of sending emails: SMTP (anonymous@1.1.1.1)

accounts             Name: Accounts                       Version: 2.6.0      State: Enabled 	barcode              Name: Barcode                        Version: 2.5.0      State: Installed / not activated 	camerainput          Name: Camera Input                   Version: 1.0.1      State: Not installed 	datainjection        Name: Data injection                 Version: 2.8.1      State: Installed / not activated 	databases            Name: Databases                      Version: 2.3.0      State: Enabled 	domains              Name: Domains                        Version: 2.2.1      State: Installed / not activated 	formcreator          Name: Form Creator                   Version: 2.10.4     State: Installed / not activated 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled 	ipphonescanner       Name: IpPhoneScanner                 Version: 0.0.1      State: Not installed 	mailanalyzer         Name: Mail Analyzer                  Version: 2.0.1      State: Enabled 	mailbehaviours       Name: Mail Behaviours                Version: 1.0.3      State: Enabled 	mydashboard          Name: My Dashboard                   Version: 1.8.0      State: Enabled 	archires             Name: Network Architectures          Version: 2.7.0      State: Not installed 	ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Enabled 	printercounters      Name: Printer counters               Version: 1.7.0      State: Enabled 	reservation          Name: Reservation                    Version: 2.3.3      State: Enabled 	tasklists            Name: Tasks list                     Version: 1.6.1      State: Enabled 	webapplications      Name: Web applications               Version: 3.0.0      State: Enabled
[/code]

</body>
</html>

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

Please provide all informations requested in issue form: steps to reproduce, system informations, ....

Regards
