### ISSUE TITLE
Error 404 after login

### ISSUE THREAD

**Issue by dptecnicoaver** [glpi-project/glpi#9249]
Hi,

After change the web services server, the GLPI show this error message after login:
 - 404: File or directory not found

I see that the URI show an error, repeating two times **/front/front/**
![GLPI-Error](https://user-images.githubusercontent.com/60703973/124363410-6031f500-dc3b-11eb-9ca1-9f13ee68cac3.png)

The environment:
- Windows Server 2019
- Internet Information Server
- Plesk Obsidian 18.0.36
- GLPI versión: 9.1.7.1
 
Any suggestion?

Best regards.
Mario Lozano

**Comment by trasher** [comment]
That sounds like a server configuration issue. Also; you should consider upgrading.
