### ISSUE TITLE
ticket.url tag not working with new ticket notification

### ISSUE THREAD

**Issue by ZeikoFr** [glpi-project/glpi#9264]
**Describe the bug**

When creating a new ticket a mail notification is automaticly send to the asker but any link using the ticket.url tag is not working

**To reproduce**

 
Create a notification with event "New ticket"

In the template translation add the tag ticket.url

Here is the following line for the footer of the ticket in my case :  

`<div class="infos" style="font-size: 13px;"><a href="##ticket.url##">Ticket ###ticket.id##</a>
`
This is what happen when i'm overing the URL in the new ticket mail : 

![image](https://user-images.githubusercontent.com/54892453/124888916-d5545000-dfd6-11eb-87bb-ed71b8b4ee38.png)

With the exact same code on a new followup notification :  

![image](https://user-images.githubusercontent.com/54892453/124889036-f6b53c00-dfd6-11eb-95ac-18aaaba504e2.png)

And this one redirect correctly

**Expected behavior**

The behavior of the tag should be the same as a followup notification

**Additional context**

I'm not a dev but my take is that the notification mail is sent before the URL is generated, which send a mail with and empty URL that my webmail try to fill with his own address to avoid inconvenience

**Comment by ftoledo** [comment]
We have same issue at glpi 10.0.16
the notification have a empty url.
