### ISSUE TITLE
Menu Problem

### ISSUE THREAD

**Issue by pchevallereau** [glpi-project/glpi#927]
Hello!

For GLPI 9.1,
i found a menu display problem, on firefox/internet explorer browsers.

For firefox:
![firefox menu](https://cloud.githubusercontent.com/assets/20992504/18316645/bff9cbf2-751b-11e6-91ae-6c8337bd5e69.PNG)

For internet explorer:
![ie menu](https://cloud.githubusercontent.com/assets/20992504/18316655/c5485628-751b-11e6-9db7-fef14f50096d.PNG)

**Comment by orthagh** [comment]
Hello @pchevallereau 

Here is fix for firefox: b3aa467
For internet explorer, it should work with version 10.

**Comment by pchevallereau** [comment]
Ok, it's works

Thanks, you can close the issue.
