### ISSUE TITLE
Refresh too fast when choosing an item from customized dropdown lists to update a field

### ISSUE THREAD

**Issue by progaddicted** [glpi-project/glpi#9275]
**Describe the bug**

When I try to update any element (whichever it is) choosing an item from a dropdown list (a customized one) if I'm not quick enough to press "save" in time the page gets refreshed ignoring my modification.

**Page(s) URL**

N/A

**To reproduce**

1. go to the form for e. g. to update an existing user;
2. in the "Default entity" field open the dropdown list;
3. select a new one;
4. the page refresh takes place, ignoring the modification;
Same story when changing e. g. the type of a project, or its user.
Apparently this happens only when picking an element from customized dropdown lists; in fact, when changing the completion percentage of a project (built-in dropdown list) everything runs as expected.

**Expected behavior**

The page should wait until hitting "add" or "save" button, and show the updated value.

**Logs**

As you will see, no errors at all (nothing dated July, 11th).

**php-errors.log** ===============================================================================

[2021-06-20 21:37:32] glpiphplog.CRITICAL:   *** Uncaught Exception TypeError: Argument 1 passed to Dropdown::addNewCondition() must be of the type array, string given, called in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/dropdown.class.php on line 159 in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/dropdown.class.php at line 288
  Backtrace :
  inc/dropdown.class.php:159                         Dropdown::addNewCondition()
  ...ns/fusioninventory/ajax/dropdown_taskjob.php:61 Dropdown::show()
  
[2021-07-10 17:38:56] glpiphplog.DEBUG: Html::compileScss() in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/html.class.php line 7505
css/styles.scss is new, loading  {"user":"6@web-lnx206.ergonet.host"} 
[2021-07-10 17:38:57] glpiphplog.DEBUG: Html::compileScss() in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/html.class.php line 7505
css/palettes/auror.scss is new, loading  {"user":"6@web-lnx206.ergonet.host"} 
[2021-07-10 17:52:41] glpiphplog.DEBUG: Html::compileScss() in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/html.class.php line 7505
css/dashboard.scss is new, loading  {"user":"6@web-lnx206.ergonet.host"} 
[2021-07-10 18:02:00] glpiphplog.WARNING: Test logger  
[2021-07-10 18:02:01] glpiphplog.WARNING:   *** PHP Warning (2): file_exists(): open_basedir restriction in effect. File(/usr/sbin/getenforce) is not within the allowed path(s): (/var/www/vhosts/m59s.net/:/tmp/:/var/lib/php/session/:/dev/urandom) in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/system/requirement/selinux.class.php at line 51
  Backtrace :
  inc/system/requirement/selinux.class.php:51        file_exists()
  ...m/requirement/abstractrequirement.class.php:103 Glpi\System\Requirement\SeLinux->check()
  ...m/requirement/abstractrequirement.class.php:133 Glpi\System\Requirement\AbstractRequirement->doCheck()
  inc/config.class.php:1919                          Glpi\System\Requirement\AbstractRequirement->isOutOfContext()
  inc/config.class.php:2315                          Config->showSystemInformations()
  inc/commonglpi.class.php:637                       Config::displayTabContentForItem()
  ajax/common.tabs.php:106                           CommonGLPI::displayStandardTab()
  
[2021-07-10 18:31:33] glpiphplog.WARNING: Test logger  

**sql-errors.log** =================================================================================

[2021-07-07 22:27:50] glpisqllog.ERROR: DBmysql::query() in /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/inc/dbmysql.class.php line 309
  *** MySQL query error:
  SQL: INSERT INTO `glpi_entities` (`id`, `address`, `email`, `phonenumber`, `postcode`, `state`, `town`, `authldaps_id`, `entities_id_software`, `level`, `name`, `completename`, `entities_id`, `ancestors_cache`, `sons_cache`, `comment`, `autofill_buy_date`, `autofill_delivery_date`, `autofill_order_date`, `autofill_use_date`, `autofill_warranty_date`, `autofill_decommission_date`, `delay_send_emails`, `is_notif_enable_default`, `default_cartridges_alarm_threshold`, `default_consumables_alarm_threshold`, `default_contract_alert`, `default_infocom_alert`, `cartridges_alert_repeat`, `consumables_alert_repeat`, `notclosed_delay`, `use_licenses_alert`, `use_certificates_alert`, `send_licenses_alert_before_delay`, `send_certificates_alert_before_delay`, `use_contracts_alert`, `send_contracts_alert_before_delay`, `use_reservations_alert`, `use_infocoms_alert`, `send_infocoms_alert_before_delay`, `use_domains_alert`, `send_domains_alert_close_expiries_delay`, `send_domains_alert_expired_delay`, `calendars_id`, `tickettype`, `auto_assign_mode`, `autoclose_delay`, `inquest_config`, `inquest_rate`, `inquest_delay`, `inquest_duration`, `max_closedate`, `tickettemplates_id`, `changetemplates_id`, `problemtemplates_id`, `suppliers_as_private`, `autopurge_delay`, `anonymize_support_agents`, `enable_custom_css`, `date_creation`, `date_mod`) VALUES ('8', 'Via XXV Aprile, 2', 'germoglio.cse@gmail.com', '02 9530 5165', '20051', 'MI', 'Cassina de\' Pecchi', '0', '-2', '3', 'CSE', 'TovisMaster > CoopGermoglio > CSE', '2', '{\"0\":0,\"2\":2}', '{\"7\":7}', 'Riferimento: Riccardo', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '-2', '0', '-10', '0', '2021-07-07 22:27:50', '-2', '-2', '-2', '-2', '-10', '-2', '-2', '2021-07-07 22:27:50', '2021-07-07 22:27:50')
  Error: Duplicate entry '2-CSE' for key 'unicity'
  Backtrace :
  inc/dbmysql.class.php:1148                         
  inc/commondbtm.class.php:602                       DBmysql->insert()
  inc/commondbtm.class.php:1172                      CommonDBTM->addToDB()
  inc/commondbtm.class.php:1262                      CommonDBTM->add()
  inc/massiveaction.class.php:1319                   CommonDBTM->clone()
  inc/massiveaction.class.php:1097                   MassiveAction::processMassiveActionsForOneItemtype()
  inc/massiveaction.class.php:1076                   MassiveAction->processForSeveralItemtypes()
  front/massiveaction.php:59                         MassiveAction->process()
  {"user":"6@web-lnx206.ergonet.host"} 

**cron-log** =================================

2021-07-11 00:01:17 [@web-lnx206.ergonet.host]
Interno #1: Avvia queuednotification
2021-07-11 01:00:30 [@web-lnx206.ergonet.host]
Interno #1: Avvia mailgateerror
2021-07-11 02:02:05 [@web-lnx206.ergonet.host]
Interno #1: Avvia mailgate
2021-07-11 03:00:32 [@web-lnx206.ergonet.host]
Interno #1: Avvia planningrecall
2021-07-11 04:01:22 [@web-lnx206.ergonet.host]
Interno #1: Avvia slaticket
2021-07-11 05:00:14 [@web-lnx206.ergonet.host]
Interno #1: Avvia olaticket
2021-07-11 06:00:37 [@web-lnx206.ergonet.host]
Interno #1: Avvia ticketrecurrent
2021-07-11 07:00:57 [@web-lnx206.ergonet.host]
Interno #1: Avvia graph
2021-07-11 08:00:29 [@web-lnx206.ergonet.host]
Interno #1: Avvia reservation
2021-07-11 09:01:14 [@web-lnx206.ergonet.host]
Interno #1: Avvia temp
2021-07-11 10:00:24 [@web-lnx206.ergonet.host]
Interno #1: Avvia queuednotification
2021-07-11 11:01:56 [@web-lnx206.ergonet.host]
Interno #1: Avvia alertnotclosed
2021-07-11 12:01:37 [@web-lnx206.ergonet.host]
Interno #1: Avvia mailgate
2021-07-11 12:46:40 [@web-lnx206.ergonet.host]
Internal #1: Launch planningrecall
2021-07-11 13:00:57 [@web-lnx206.ergonet.host]
Interno #1: Avvia slaticket
2021-07-11 14:00:54 [@web-lnx206.ergonet.host]
Interno #1: Avvia contract
2021-07-11 15:00:38 [@web-lnx206.ergonet.host]
Interno #1: Avvia olaticket
2021-07-11 15:16:46 [@web-lnx206.ergonet.host]
Internal #1: Launch closeticket
2021-07-11 15:17:49 [@web-lnx206.ergonet.host]
Internal #1: Launch ticketrecurrent
2021-07-11 16:00:15 [@web-lnx206.ergonet.host]
Interno #1: Avvia graph
2021-07-11 17:00:44 [@web-lnx206.ergonet.host]
Interno #1: Avvia reservation
2021-07-11 18:01:21 [@web-lnx206.ergonet.host]
Interno #1: Avvia infocom
2021-07-11 18:59:47 [@web-lnx206.ergonet.host]
Internal #1: Launch queuednotification
2021-07-11 19:00:56 [@web-lnx206.ergonet.host]
Internal #1: Launch temp
2021-07-11 19:01:31 [@web-lnx206.ergonet.host]
Interno #1: Avvia mailgate

**event.log** ===============================
2021-07-11 15:16:54 [@web-lnx206.ergonet.host]
[login] 3: MarcoAdm login from IP 185.128.27.99
2021-07-11 18:59:50 [@web-lnx206.ergonet.host]
[login] 3: MarcoAdm login from IP 185.128.27.99
2021-07-11 19:01:14 [@web-lnx206.ergonet.host]
[login] 3: MarcoAdm login from IP 185.128.27.99

**Screenshots**

N/A

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Information about system installation & configuration
--
GLPI 9.5.5 (/glpi => /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi) Installation mode: TARBALL

Server
Operating system: Linux web-lnx206.ergonet.host 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64

- PHP 7.4.15 fpm-fcgi (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, bcmath, bz2, calendar, cgi-fcgi, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, ionCube Loader, json, libxml, mbstring, 	memcached, mysqli, mysqlnd, openssl, pcntl, pcre, pdo_mysql, pdo_pgsql, pdo_sqlite, posix, redis, session, soap, sockets, 	sodium, sqlite3, sqlsrv, standard, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, yaml, zip, zlib) 

- Setup: max_execution_time="300" memory_limit="256M" post_max_size="256M" safe_mode="" session.save_handler="files" 	upload_max_filesize="256M" 

- Software: Apache () Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0 Server Software: MariaDB

- Server 	Server Version: 10.1.35-MariaDB 	Server SQL Mode:  Parameters: GLPIMaster@localhost/GLPI 	Host info: Localhost via UNIX socket 	

PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is not present apcu extension is not present Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.1.35) - Perfect! Access to timezone database (mysql) is not allowed. The log file has been created successfully. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_cache has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/config has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_cron has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_dumps has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_graphs has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_lock has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_pictures has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_plugins has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_rss has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_sessions has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_tmp has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_uploads has been validated. Write access to /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/marketplace has been validated. Web access to files directory is protected

GLPI constants
GLPI_ROOT: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi GLPI_CONFIG_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/config GLPI_VAR_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files GLPI_MARKETPLACE_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files GLPI_CACHE_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_cache GLPI_CRON_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_cron GLPI_DUMP_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_locales GLPI_LOCK_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_lock GLPI_LOG_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_log GLPI_PICTURE_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_plugins GLPI_RSS_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_rss GLPI_SESSION_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_sessions GLPI_TMP_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

Libraries
htmlawed/htmlawed version 1.2.5 in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/sabre/http/lib) sabre/uri in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/sabre/uri/lib) sabre/vobject in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/elvanto/litemoji/src) symfony/console in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/symfony/console) scssphp/scssphp in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/ramsey/uuid/src) psr/log in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/var/www/vhosts/m59s.net/subdomains/glpi/httpdocs/glpi/vendor/paragonie/sodium_compat/src)

SQL replicas
Not active

Notifications
Way of sending emails: PHP

Plugins list

1. fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled 
2. ocsinventoryng       Name: OCS Inventory NG               Version: 1.7.3      State: Installed / not activated

**Additional context**

Please find attached two HAR files (please remove the txt extension) showing the network activities in case of respectively a normal successful update (user activation) and a failing one (change of the user's manager); I'm not an expert, but at a first sight I see in the second case no "POST" is present...
[user activation.har.txt](https://github.com/glpi-project/glpi/files/6797391/user.activation.har.txt)
[user manager change.har.txt](https://github.com/glpi-project/glpi/files/6797392/user.manager.change.har.txt)

**Comment by progaddicted** [comment]
![Inspect default-entity-dropdown](https://user-images.githubusercontent.com/54311010/125420440-a127b2d6-d59b-4df8-973a-126fcfa50738.png)
![Inspect default-profile-dropdown](https://user-images.githubusercontent.com/54311010/125420443-f8481540-437c-419c-a4c2-d0d88d9c1534.png)
As requested by @cconard96 in the glpi-project forum.

**Comment by cconard96** [comment]
@progaddicted I had wanted to see the event listeners for the `select` tag because it seemed like there was something listening for a change even and triggering a page refresh. In Firefox, you can click the Event button next to the element.
I highlighted the button in blue.
![125420443-f8481540-437c-419c-a4c2-d0d88d9c1534](https://user-images.githubusercontent.com/17678637/125422353-b1539691-3cac-49f9-adc0-17c7c982252b.png)

**Comment by progaddicted** [comment]
OK, sorry, here you go; you'll find attached as well a text file with the jqueries invoked.
![Inspect default-entity-dropdown-2](https://user-images.githubusercontent.com/54311010/125427685-fc0bfc61-c32b-4822-8823-c64f50a65df3.png)
[Inspect default-entity-dropdown-2.txt](https://github.com/glpi-project/glpi/files/6807657/Inspect.default-entity-dropdown-2.txt)

**Comment by progaddicted** [comment]
Closed BY MISTAKE, sorry

**Comment by progaddicted** [comment]
Hi there, any news? Sorry for bother, but I'm in real troubles with this. I tried with all the browsers I know, including Safari on iPad, the behaviour is always the same, so is a matter of the site itself, I guess.
Should it be of any help I can try to get the Apache configuration from the provider, OK?

**Comment by cconard96** [comment]
I've not been able to recreate the issue.

**Comment by progaddicted** [comment]
> I've not been able to recreate the issue.
So what?
What about granting you access to my site, in order to let you see "live" what happens?

**Comment by progaddicted** [comment]
For info: the problem gets solved after enabling Zend OPCache. At least for my installation.

Thanks.

BR
Marco
