### ISSUE TITLE
SMTP doesn't work

### ISSUE THREAD

**Issue by excelsius** [glpi-project/glpi#929]
Hi.
I had a 0.90.5 GLPI running with mail notifications running smoothly before a server update (I run it on Debian 8).

After that update, no GLPI instances that I have running on this server can send e-mails anymore.
The mail configurations seems right. I tested installing ssmtp and sending mails with the same account I use to send mails in GLPI. Also, other systems running on the same server still works after this update.

I also tryed creating a new server for testing, reinstaling GLPI and connecting to the same account and database and it still doesn't work.
I also tryed a full new instance of GLPI with a new database and it also didn't work. 
And also trying a new install on a Ubuntu Server.

I feel like I'm missing something really obvious and simple, but can't say where.

This is my system as asked:

Instruções de instalação e configuração

[code]

GLPI 0.90.5 ( => /var/www/glpi-cti)

Server

Operating system: Linux glpi-cti 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64
PHP 5.6.24-0+deb8u1 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, bcmath, bz2,
    calendar, ctype, date, dba, dom, ereg, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, json, ldap, libxml,
    mbstring, mhash, mysql, mysqli, openssl, pcre, pdo_mysql, posix, readline, session, shmop, soap, sockets, standard, sysvmsg,
    sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
    upload_max_filesize="2M" 
Software: Apache/2.4.10 (Debian) (Apache/2.4.10 (Debian) Server at suporte.mto.ifsp.edu.br Port 80)
    Mozilla/5.0 (Windows NT 6.1; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0
Server Software: MySQL Community Server (GPL)
    Server Version: 5.6.31
    Server SQL Mode: NO_ENGINE_SUBSTITUTION
    Parameters: glpicti@10.0.0.28/glpi-cti
    Host info: 10.0.0.28 via TCP/IP

OK/var/www/glpi-cti/config : OK
OK/var/www/glpi-cti/files : OK
OK/var/www/glpi-cti/files/_dumps : OK
OK/var/www/glpi-cti/files/_sessions : OK
OK/var/www/glpi-cti/files/_cron : OK
OK/var/www/glpi-cti/files/_graphs : OK
OK/var/www/glpi-cti/files/_lock : OK
OK/var/www/glpi-cti/files/_plugins : OK
OK/var/www/glpi-cti/files/_tmp : OK
OK/var/www/glpi-cti/files/_rss : OK
OK/var/www/glpi-cti/files/_uploads : OK
OK/var/www/glpi-cti/files/_pictures : OK
OK/var/www/glpi-cti/files/_log : OK
Web access to the files directory, should not be allowed
Check the .htaccess file and the web server configuration.

Libraries

htmLawed version 1.1.21 in (/var/www/glpi-cti/lib/htmlawed)
phpCas version 1.3.4 in (/var/www/glpi-cti/lib/phpcas)
PHPMailer version 5.2.8 in (/var/www/glpi-cti/lib/phpmailer)
ZetaComponent ezcGraph installed in (/var/www/glpi-cti/lib/zeta/Base):  OK
Zend Framework version 2.4.9 in (/var/www/glpi-cti/lib/Zend)
SimplePie version 1.3.1 in (/var/www/glpi-cti/lib/simplepie)
TCPDF version 6.2.12 in (/var/www/glpi-cti/lib/tcpdf)
ircmaxell/password-compat in (/var/www/glpi-cti/lib/password_compat). Compatitility: Ok

LDAP directories

Server: '10.0.0.24', Port: '389', BaseDN: 'DC=ifsp,DC=mto', Connection filter: none, RootDN:
        'cn=bind,ou=usuarios,dc=ifsp,dc=mto', Use TLS: none

Mysql replicas

Not active

Notifications

Way of sending emails: SMTP+TLS (mt000032@mail.ifsp.edu.br)

Mails receivers

Name: 'mt000032@ifsp.edu.br' Active: Yes
    Server: '{mail.ifsp.edu.br/pop/ssl}INBOX' Login: 'mt000032' Password: Yes

Plugins list

```
dashboard            Name: Painel                         Version: 0.7.4      State: To be cleaned
```

[/code]
Para copiar/colar na sua requisição de suporte

Also, this is my last entry on my php-errors.log:
2016-09-06 14:17:09 [50@glpi-cti]
  **\* PHP Warning(2): imap_open(): Couldn't open stream {mail.ifsp.edu.br:587/pop/ssl/novalidate-cert/tls}INBOX
  Backtrace :
  :
  inc/auth.class.php:196                             imap_open()
  inc/authmail.class.php:263                         Auth->connection_imap()
  front/authmail.form.php:69                         AuthMail::testAuth()
2016-09-06 14:17:09 [50@glpi-cti]
  **\* PHP Notice(8): Unknown: Can't open mailbox {mail.ifsp.edu.br:587/pop/ssl/novalidate-cert/tls}INBOX: invalid remote specification (errflg=2)
  Backtrace :
  :
Test

(my server date is right, so the last entry is from september 6th).

This is my last entry on mail.log
2016-09-07 14:50:56 [50@glpi-cti]
Um e-mail foi enviado para suporteti.mto@ifsp.edu.br: [GLPI #0000020] Novo acompanhamento E-mails GLPI

About that, I noticed that the mails are sent to the queue, but they aren't delivered and after I send them through the options/automatic actions they are all sent to the bin and don't get delivered. 

Where else could I search?

Thank you!

**Comment by trasher** [comment]
There is a connexion issue between your server and you smtp; this is not a glpi issue.
