### ISSUE TITLE
[9.5.5] Reload of mini dashboard doesn't work in ticket.php

### ISSUE THREAD

**Issue by nenes82** [glpi-project/glpi#9292]
Hello
**Describe the bug**

On ticket.php when we toggle auto refresh, after reload  the cards are not displayed.
In Dashboard.js 
 -> getCardsAjax: function (specific_one) 
 -> $(".grid-stack-item:not(.lock-bottom)" + specific_one) => don't return anything

**Page(s) URL**

/front/ticket.php

**To reproduce**

1. Go to '/front/ticket.php'
2. Click on 'toggle auto refresh.'
3. wait auto reload

**Expected behavior**
Cards are realoded

**Screenshots**

![image](https://user-images.githubusercontent.com/48098839/125958219-42b9e80b-0eed-469b-bb74-734f483b22ce.png)
List ticket is below

**Comment by VincentLegros** [comment]
This problem is blocking as now users can't use the auto refresh option...
