### ISSUE TITLE
Error PHP when adding a contract to an item, and contract is already linked to this item

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#93]
0.85 & 0.90
In the Contracts tab of an asset (computer, monitor ... but also simcard...), one can try to add a 2nd time the same contract, already linked to the asset.
Provided that the contract has not yet reached its 'Max nbr of items', the contract is proposed in the list.
Obviously, the contract won't be added twice, but it generates a PHP error (extract hereafter).
Would be nice to exclude from the list the contract(s) already linked to the asset.
Same for the list of items in the Items tab of a contract.

  SQL: INSERT
                   INTO `glpi_contracts_items` (`items_id`,`itemtype`,`contracts_id`) VALUES (\'6\',\'Computer\',\'1\')
  Error: Duplicate entry '1-Computer-6' for key 'unicity'
  Backtrace :
  inc/commondbtm.class.php:421                       
  inc/commondbtm.class.php:820                       CommonDBTM->addToDB()
  front/contract_item.form.php:43                    CommonDBTM->add()

**Comment by orthagh** [comment]
I can't reproduce that behavior.
In my test, when a contract already added for a computer (from contracts tabs), it isn't present in contract list (the limit is reached or not)

see : https://github.com/glpi-project/glpi/blob/master/inc/contract_item.class.php#L364
The showForItem function contain a sql query to retrieve used contracts

![image](https://cloud.githubusercontent.com/assets/418844/9652397/3341fe06-521b-11e5-9d77-b08f61cec255.png)

**Comment by blerohellec** [comment]
I've added some traces.
In inc/contract_item.class.php, function showForItem, the $used array contains IDs of table glpi_contracts_items (and not contract IDs).
This $used array is passed to function Contract::dropdown in inc/contract.class.php.
But this function considers the $used array to be contract IDs : line 1238
$idrest = " AND glpi_contracts.id not in (implode($p[used]))"

In your case, I guess you're playing with a brand new GLPI installation (or this is the first time you've created contracts). So, the IDs in both tables glpi_contracts_items and glpi_contracts may be the same, and it seems to work.
But add and delete several times a contract to a computer, and I bet it will stop working.

**Comment by orthagh** [comment]
I see, i'll check this afternoon

**Comment by blerohellec** [comment]
OK for Contracts tab of an asset.
BUT KO for 'Associated items' tab of a contract.

**Comment by blerohellec** [comment]
OK. Thx
