### ISSUE TITLE
[0.90.5] Dropdowns broken because of translation (same as #345)

### ISSUE THREAD

**Issue by Djiock** [glpi-project/glpi#930]
Hello !

I'm reopening an issue about the problem described here : https://github.com/glpi-project/glpi/issues/345, because it's still happening for us... the exact same problem.

I'm not sure I understand the follow-ups at the end, is the issue supposedly solved (and thus, reappeared), or is a workaround available ? (I'm French so it's not a language issue :) )

Thanks in advance for your help, if you need additional details I can provide them.

**Comment by trasher** [comment]
The initial bug has been fixed; you may have a similar but not exactly same issue.

What does logfiles says? Could you provide steps to reproduce the issue? I can't reproduce the issue on 0.90.5 nor 9.1 following the exact steps described in ticket you pointed out.

**Comment by Djiock** [comment]
Thanks for your quick answer Trasher,

Well that's weird because I can easily reproduce... Even on a fresh 0.90.5 install : just create a few dropdowns for anything, computer types for example, then add a translation. The same problem as #345 occurs :

![capture du 2016-09-08 15-33-31](https://cloud.githubusercontent.com/assets/7031632/18382292/a47bdb2a-7680-11e6-8394-51d14becebd6.png)

And after that it stays. Even if you delete all translations or even disable it.

**Comment by trasher** [comment]
I guess it is the same issue than #953 . Could you test if the proposed fix works for you?

I close the current ticket, feel free to reopen if issue still occurs.
