### ISSUE TITLE
GLPI 9.5.5 Emails rules not working after upgrading to 9.5.5

### ISSUE THREAD

**Issue by patriciocs1979** [glpi-project/glpi#9306]
**Describe the bug**

After upgrading from 9.5.4 to 9.5.5  Rules for assigning a ticket created through a mails receiver are not being applied. All autresponse e-mails and mail delivery issues notifications are not discarded generating new tickets.

**Page(s) URL**

N/A

**To reproduce**

1. Go to Administration, Rules, Rules for assigning a ticket created through a mails receiver
2. Check that default email rules are activated
3. Tickets are being created for e-mails that should have been rejected

**Expected behavior**

No ticket should be created for e-mails stisfiying the rejection rules

**Logs**
[GLPILogs.zip](https://github.com/glpi-project/glpi/files/6848985/GLPILogs.zip)

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

[code]   GLPI 9.5.5 ( => /usr/share/glpi) Installation mode: RPM
--

Operating system: Linux xxxxxxxx3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 PHP 7.4.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, 	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, 	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sodium, sqlite3, 	standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="180" memory_limit="512M" post_max_size="128M" safe_mode="" session.save_handler="files" 	upload_max_filesize="256M"  Software: Apache/2.4.48 (codeit) OpenSSL/1.1.1k PHP/7.4.20 () 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.70 Server Software: MariaDB Server 	Server Version: 10.4.20-MariaDB 	Server SQL Mode:  	Parameters:xxxxx/xxxxxHost info: 127.0.0.1 via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.4.20) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated. Write access to /usr/share/glpi/marketplace has been validated. xxxxxxxx

GLPI_ROOT: /usr/share/glpi GLPI_CONFIG_DIR: /etc/glpi GLPI_VAR_DIR: /var/lib/glpi/files GLPI_LOG_DIR: /var/log/glpi GLPI_HTMLAWED: /usr/share/php/htmLawed/htmLawed.php GLPI_FONT_FREESANS: /usr/share/fonts/gnu-free/FreeSans.ttf GLPI_SYSTEM_CRON: 1 GLPI_INSTALL_MODE: RPM GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/lib/glpi/files GLPI_CACHE_DIR: /var/lib/glpi/files/_cache GLPI_CRON_DIR: /var/lib/glpi/files/_cron GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales GLPI_LOCK_DIR: /var/lib/glpi/files/_lock GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins GLPI_RSS_DIR: /var/lib/glpi/files/_rss GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions GLPI_TMP_DIR: /var/lib/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/share/glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/usr/share/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/usr/share/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)

Server: 'xxxxxxx', Port: 'xxxx', BaseDN: 'OU=CL,OU=xxx,OU=BV,DC=xx,DC=xx,DC=coxxxrp', 		Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 		'xxxxxx', Use TLS: none Server: 'xxxxxxx', Port: 'xxxx', BaseDN: 'ou=people,xxxxxxx', Connection filter: 		'(&(uid=<userid>)(nsroleDN=cn=*,ou=<app>,ou=applications,dc=xxxxs,dc=com))', RootDN: 'xxxxx', Use TLS: 		none

Not active

Way of sending emails: SMTP+SSL (xxxxxxxxxx)

Name: 'helpdesxxxxl' Active: No 	Server: '{xxxxxxx/pop/notls}' Login: 'xxxxxxx' Password: Yes

fields               Name: Additionnal fields             Version: 1.12.6     State: Enabled 	behaviors            Name: Behaviours                     Version: 2.4.1      State: Enabled 	datainjection        Name: Data injection                 Version: 2.9.0      State: Enabled 	formcreator          Name: Form Creator                   Version: 2.11.4     State: Installed / not activated 	fusioninventory      Name: FusionInventory                Version: 9.5.0+1.0  State: Enabled 	addressing           Name: IP Adressing                   Version: 2.9.0      State: Enabled 	tasklists            Name: Lista de tareas                Version: 1.6.0      State: Enabled 	mreporting           Name: More Reporting                 Version: 1.7.3      State: Enabled 	satisfaction         Name: More satisfaction              Version: 1.5.1      State: Installed / not activated 	moreticket           Name: More ticket                    Version: 1.6.1      State: Enabled 	printercounters      Name: Printer counters               Version: 1.7.0      State: Installed / not activated 	protocolsmanager     Name: Protocols manager              Version: 1.4        State: Enabled 	reports              Name: Reportes                       Version: 1.14.0     State: Enabled 	screenshot           Name: Screenshot                     Version: 1.1.3      State: Enabled
[/code]

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

Can you attach here an export, in eml format, of an email that should be rejected ? It could help us to debug and integrate it in our test suite.

Regards

**Comment by patriciocs1979** [comment]
Here are some e-mails that triggered the creation of tickets despite the fact that default rejection rules (X-Auto-Response-Suppress and Auto-Reply Auto-Submitted) are activated.

FYI the regular expressions for those default rules are the next:

X-Auto-Response-Suppress: /\S+/
Auto-Reply Auto-Submitted: /^(?!.*no).+$/i
[e-mails.zip](https://github.com/glpi-project/glpi/files/6863950/e-mails.zip)

Thanks in advance

**Comment by cedric-anne** [comment]
Hi,

#9387 should fix this issue.

Regards

**Comment by member26** [comment]
> **Describe the bug**
> 
> After upgrading from 9.5.4 to 9.5.5 Rules for assigning a ticket created through a mails receiver are not being applied. All autresponse e-mails and mail delivery issues notifications are not discarded generating new tickets.
> 
> **Page(s) URL**
> 
> N/A
> 
> **To reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Go to Administration, Rules, Rules for assigning a ticket created through a mails receiver
> 2. Check that default email rules are activated
> 3. Tickets are being created for e-mails that should have been rejected
> 
> **Expected behavior**
> 
> No ticket should be created for e-mails stisfiying the rejection rules
> 
> **Logs**
> [GLPILogs.zip](https://github.com/glpi-project/glpi/files/6848985/GLPILogs.zip)
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> **Your GLPI setup (you can find it in Setup > General menu, System tab)**
> 
> ## [code]   GLPI 9.5.5 ( => /usr/share/glpi) Installation mode: RPM
> Operating system: Linux xxxxxxxx3.10.0-1160.31.1.el7.x86_64 #1 SMP Thu Jun 10 13:32:12 UTC 2021 x86_64 PHP 7.4.20 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, pdo_sqlite, posix, session, shmop, snmp, soap, sockets, sodium, sqlite3, standard, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="180" memory_limit="512M" post_max_size="128M" safe_mode="" session.save_handler="files" upload_max_filesize="256M" Software: Apache/2.4.48 (codeit) OpenSSL/1.1.1k PHP/7.4.20 () Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.70 Server Software: MariaDB Server Server Version: 10.4.20-MariaDB Server SQL Mode: Parameters:xxxxx/xxxxxHost info: 127.0.0.1 via TCP/IP PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed CAS extension is not present exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.4.20) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to /var/lib/glpi/files/_cache has been validated. Write access to /etc/glpi has been validated. Write access to /var/lib/glpi/files/_cron has been validated. Write access to /var/lib/glpi/files has been validated. Write access to /var/lib/glpi/files/_dumps has been validated. Write access to /var/lib/glpi/files/_graphs has been validated. Write access to /var/lib/glpi/files/_lock has been validated. Write access to /var/lib/glpi/files/_pictures has been validated. Write access to /var/lib/glpi/files/_plugins has been validated. Write access to /var/lib/glpi/files/_rss has been validated. Write access to /var/lib/glpi/files/_sessions has been validated. Write access to /var/lib/glpi/files/_tmp has been validated. Write access to /var/lib/glpi/files/_uploads has been validated. Write access to /usr/share/glpi/marketplace has been validated. xxxxxxxx
> 
> GLPI_ROOT: /usr/share/glpi GLPI_CONFIG_DIR: /etc/glpi GLPI_VAR_DIR: /var/lib/glpi/files GLPI_LOG_DIR: /var/log/glpi GLPI_HTMLAWED: /usr/share/php/htmLawed/htmLawed.php GLPI_FONT_FREESANS: /usr/share/fonts/gnu-free/FreeSans.ttf GLPI_SYSTEM_CRON: 1 GLPI_INSTALL_MODE: RPM GLPI_MARKETPLACE_DIR: /usr/share/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT: GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_NETWORK_MAIL: [glpi@teclib.com](mailto:glpi@teclib.com) GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES: GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS: GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/lib/glpi/files GLPI_CACHE_DIR: /var/lib/glpi/files/_cache GLPI_CRON_DIR: /var/lib/glpi/files/_cron GLPI_DUMP_DIR: /var/lib/glpi/files/_dumps GLPI_GRAPH_DIR: /var/lib/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/lib/glpi/files/_locales GLPI_LOCK_DIR: /var/lib/glpi/files/_lock GLPI_PICTURE_DIR: /var/lib/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/lib/glpi/files/_plugins GLPI_RSS_DIR: /var/lib/glpi/files/_rss GLPI_SESSION_DIR: /var/lib/glpi/files/_sessions GLPI_TMP_DIR: /var/lib/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/lib/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /usr/share/glpi/locales GLPI_VERSION: 9.5.5 GLPI_SCHEMA_VERSION: 9.5.5 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021
> 
> htmlawed/htmlawed version 1.2.5 in (/usr/share/glpi/vendor/htmlawed/htmlawed) phpmailer/phpmailer version 6.1.6 in (/usr/share/glpi/vendor/phpmailer/phpmailer/src) simplepie/simplepie version 1.5.6 in (/usr/share/glpi/vendor/simplepie/simplepie/library) tecnickcom/tcpdf version 6.3.5 in (/usr/share/glpi/vendor/tecnickcom/tcpdf) michelf/php-markdown in (/usr/share/glpi/vendor/michelf/php-markdown/Michelf) true/punycode in (/usr/share/glpi/vendor/true/punycode/src) iamcal/lib_autolink in (/usr/share/glpi/vendor/iamcal/lib_autolink) sabre/dav in (/usr/share/glpi/vendor/sabre/dav/lib/DAV) sabre/http in (/usr/share/glpi/vendor/sabre/http/lib) sabre/uri in (/usr/share/glpi/vendor/sabre/uri/lib) sabre/vobject in (/usr/share/glpi/vendor/sabre/vobject/lib) laminas/laminas-cache in (/usr/share/glpi/vendor/laminas/laminas-cache/src) laminas/laminas-i18n in (/usr/share/glpi/vendor/laminas/laminas-i18n/src) laminas/laminas-serializer in (/usr/share/glpi/vendor/laminas/laminas-serializer/src) monolog/monolog in (/usr/share/glpi/vendor/monolog/monolog/src/Monolog) sebastian/diff in (/usr/share/glpi/vendor/sebastian/diff/src) elvanto/litemoji in (/usr/share/glpi/vendor/elvanto/litemoji/src) symfony/console in (/usr/share/glpi/vendor/symfony/console) scssphp/scssphp in (/usr/share/glpi/vendor/scssphp/scssphp/src) laminas/laminas-mail in (/usr/share/glpi/vendor/laminas/laminas-mail/src/Protocol) laminas/laminas-mime in (/usr/share/glpi/vendor/laminas/laminas-mime/src) rlanvin/php-rrule in (/usr/share/glpi/vendor/rlanvin/php-rrule/src) blueimp/jquery-file-upload in (/usr/share/glpi/vendor/blueimp/jquery-file-upload/server/php) ramsey/uuid in (/usr/share/glpi/vendor/ramsey/uuid/src) psr/log in (/usr/share/glpi/vendor/psr/log/Psr/Log) psr/simple-cache in (/usr/share/glpi/vendor/psr/simple-cache/src) mexitek/phpcolors in (/usr/share/glpi/vendor/mexitek/phpcolors/src/Mexitek/PHPColors) guzzlehttp/guzzle in (/usr/share/glpi/vendor/guzzlehttp/guzzle/src) guzzlehttp/psr7 in (/usr/share/glpi/vendor/guzzlehttp/psr7/src) wapmorgan/unified-archive in (/usr/share/glpi/vendor/wapmorgan/unified-archive/src) paragonie/sodium_compat in (/usr/share/glpi/vendor/paragonie/sodium_compat/src)
> 
> Server: 'xxxxxxx', Port: 'xxxx', BaseDN: 'OU=CL,OU=xxx,OU=BV,DC=xx,DC=xx,DC=coxxxrp', Connection filter: '(&(objectClass=user)(objectCategory=person)(!(userAccountControl:1.2.840.113556.1.4.803:=2)))', RootDN: 'xxxxxx', Use TLS: none Server: 'xxxxxxx', Port: 'xxxx', BaseDN: 'ou=people,xxxxxxx', Connection filter: '(&(uid=)(nsroleDN=cn=*,ou=,ou=applications,dc=xxxxs,dc=com))', RootDN: 'xxxxx', Use TLS: none
> 
> Not active
> 
> Way of sending emails: SMTP+SSL (xxxxxxxxxx)
> 
> Name: 'helpdesxxxxl' Active: No Server: '{xxxxxxx/pop/notls}' Login: 'xxxxxxx' Password: Yes
> 
> fields Name: Additionnal fields Version: 1.12.6 State: Enabled behaviors Name: Behaviours Version: 2.4.1 State: Enabled datainjection Name: Data injection Version: 2.9.0 State: Enabled formcreator Name: Form Creator Version: 2.11.4 State: Installed / not activated fusioninventory Name: FusionInventory Version: 9.5.0+1.0 State: Enabled addressing Name: IP Adressing Version: 2.9.0 State: Enabled tasklists Name: Lista de tareas Version: 1.6.0 State: Enabled mreporting Name: More Reporting Version: 1.7.3 State: Enabled satisfaction Name: More satisfaction Version: 1.5.1 State: Installed / not activated moreticket Name: More ticket Version: 1.6.1 State: Enabled printercounters Name: Printer counters Version: 1.7.0 State: Installed / not activated protocolsmanager Name: Protocols manager Version: 1.4 State: Enabled reports Name: Reportes Version: 1.14.0 State: Enabled screenshot Name: Screenshot Version: 1.1.3 State: Enabled
> [/code]
> 
> **Additional context**

I must change the glpi code to have an alert when the status of ticket clos can you plz tell me where i should change ????

**Comment by member26** [comment]
I must change the glpi code to have an alert when the status of ticket clos can you plz tell me where is the code file  i should change ????

**Comment by member26** [comment]
hi i have problem with the code  source glpi i should have alerte when the ticket status is clos but i dont khnow where i should change the code can you plz hel me

**Comment by TylerVD** [comment]
Hello, 
I have applied the fix and the mails with auto-submitted header are now triggering the rules correctly.

FYI, the line number was not like in the fix.

Your fix: 
![image](https://user-images.githubusercontent.com/82641169/130414004-c77280b2-d90e-4c24-b471-4e29e15963d3.png)

My file: 
![image](https://user-images.githubusercontent.com/82641169/130413960-e117b3c9-ea15-4b00-b638-0d48047b0d54.png)
