### ISSUE TITLE
[9.5.5] mailgate error 500

### ISSUE THREAD

**Issue by Riesuu** [glpi-project/glpi#9322]
Hello,
I have a problem with the mailgate service which is still blocked. When I restart it, I get "error 500" which appears.
When I try to validate a ticket, I get the 500 error every other time.

[mailgate.log](https://github.com/glpi-project/glpi/files/6868822/mailgate.log)
[cron.log](https://github.com/glpi-project/glpi/files/6868824/cron.log)

thanks

**Comment by cedric-anne** [comment]
Hi,

Please attach the email that causes this issue, into eml format. It could help us to debug.

Regards

**Comment by Riesuu** [comment]
Maybe this one, it was one of the first in the queue on the collector
[AnyConv.comeml.zip](https://github.com/glpi-project/glpi/files/6868862/AnyConv.comeml.zip)

**Comment by Riesuu** [comment]
The service has just been launched, while looking at the mails, I notice that we have a mail with a .MP3 file in the "OK" folder...

**Comment by Riesuu** [comment]
Hello,
the problem has happened again, I have nothing in the queue and the collector refuses to start. ERROR 500

**Comment by Riesuu** [comment]
I may have found it. I gave apache the rights on the plugin + file directory and the mailgate works again. I will reinstall the server when I get back.
