### ISSUE TITLE
[9.5.5] Bug in autoload in tickets page

### ISSUE THREAD

**Issue by lucas-enqueiroz** [glpi-project/glpi#9324]
In Assistence > tickets, when page is reloaded with auto refresh, show a div with high height

And I noticed that mini dashboard in tickets is disappearing when that happens

![image](https://user-images.githubusercontent.com/36959868/126797830-e1e979ee-2738-4af0-878a-d510feff91ea.png)

**Comment by fralla2** [comment]
Same here
