### ISSUE TITLE
Issue with automatic action => Infocom

### ISSUE THREAD

**Issue by nenes82** [glpi-project/glpi#9326]
**Describe the bug**

When the entity administrator is a LDAP user, he is considered like a GLPI_USER instead of EXTERNAL_USER in the function NotificationTarget::addToRecipientlist()
So in the sended email the link contain the parameter "noAUTO=1"

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Enable automatic action "Infocom"
2. Enable notification
3. Execute the cron

**Expected behavior**

The link in the email must be /index.php?redirect=Peripheral_1631_Infocom and no /index.php?redirect=Peripheral_1631_Infocom&noAUTO=1

Regards

**Comment by tomolimo** [comment]
Hello 
This bug is still existing...
Thank you,
Regards,
Tomolimo
