### ISSUE TITLE
GLPI 9.5.5 mailgate e queuenotifications do not work 

### ISSUE THREAD

**Issue by guimarchioretto** [glpi-project/glpi#9328]
Hi Guys,

mailgate and queuenotifications do not work. Configured as follows:

Frequency of execution: 1 minute
Status: scheduled
Execution mode: GLPI

Messages are not being collected so you need to click run. After forcibly executing the notification queue is not automatically released, it also requires forced execution.

1. Go to 'configure' > automatic actions > mailgate
2. Go to 'configure' > automatic actions > queuenotifications

No error image is generated, GLPI is simply not doing what it should. When forcing execution, calls are received normally.

**Comment by btry** [comment]
Hi

What is the configuration of run mode ?

![image](https://user-images.githubusercontent.com/14139801/127822912-dab3564f-0f25-401f-86e3-70eb9e6b6a82.png)

**Comment by cedric-anne** [comment]
Hi,

Please provide requested informations in issue form, like logs, installed plugins , ...

Regards
