### ISSUE TITLE
$_SESSION['glpiname'] is undefined

### ISSUE THREAD

**Issue by nenes82** [glpi-project/glpi#9336]
**Describe the bug**

When glpi:ldap:synchronize_users is executed in console. If a user is duplicated. 

**Page(s) URL**

bin/console glpi:ldap:synchronize_users

**To reproduce**

1. Have a duplicate user
2. Have fields unicity on User - fields Login and Synchronization field
3. Run command
4. See error in log file

**Expected behavior**
logs : trying to add an item that already exists: Impossible record for Login = xxx
Other item exist
[ID: xxx]

**Logs**
glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: glpiname in L:\glpi\inc\commondbtm.class.php at line 4385
  Backtrace :
  inc\commondbtm.class.php:1497                      CommonDBTM->checkUnicity()
  inc\authldap.class.php:2542                        CommonDBTM->update()
  ...sole\ldap\synchronizeuserscommand.class.php:372 AuthLDAP::ldapImportUserByServerId()
  vendor\symfony\console\Command\Command.php:255     Glpi\Console\Ldap\SynchronizeUsersCommand->execute()
  vendor\symfony\console\Application.php:1000        Symfony\Component\Console\Command\Command->run()
  inc\console\application.class.php:249              Symfony\Component\Console\Application->doRunCommand()
  vendor\symfony\console\Application.php:271         Glpi\Console\Application->doRunCommand()
  vendor\symfony\console\Application.php:147         Symfony\Component\Console\Application->doRun()
  bin\console:102                                    Symfony\Component\Console\Application->run()
```

**Comment by cedric-anne** [comment]
Should be fixed by #9339.
