### ISSUE TITLE
Getting "Can't get DB lock" error

### ISSUE THREAD

**Issue by vaibhav12321** [glpi-project/glpi#9349]
**Describe the bug**
We are getting "Can't get DB lock" frequently. We also see that once "mailgate" or "queuednotification" start the other crontask does not run.
Example: mailgate, queuednotification, slaticket etc are set to execute at frequency 1 minute. Suppose queuednotification takes more time say 10 minute, in this case the other cron does not run and continue to throw error "Can't get DB lock".

My question is can we remove below lock check from code:
https://github.com/glpi-project/glpi/blob/c422b75b3c9d1805e2d1ecbe563c1598ce9ffe1d/inc/crontask.class.php#L917

**Page(s) URL**
php /var/www/html/glpi/front/cron.php

If applicable, page(s) URL where the bug happens.

**Comment by cedric-anne** [comment]
Hi,

This "locking" system has been made to ensure that multiple tasks are not launched at the same time. If execution time of your tasks is too long, it certainly means that it consumes lots of system resources. By removing this "locking" system, you will permit memory/CPU tasks to be launched at the same time, with a high potential of negative impact on response time for all your users/inventory agents/API clients.

The GLPI cron system launch tasks depending on their last execution date / frequency, so all tasks will be executed anyway, even if it is 10 minutes later than expected.

If some task have an exaggerated execution time compared to what they are supposed to process, then something should be done to enhance their execution time, but removing the locking system is not an option for now.

Regards

**Comment by vaibhav12321** [comment]
Thank you. But what is the use case for **--force** option. I am unable to find documentation for it.

**Comment by cedric-anne** [comment]
> Thank you. But what is the use case for **--force** option. I am unable to find documentation for it.

When using `--force $taskname`, you can launch a single task, unless there is already a running task, and unless this task is already running.
