### ISSUE TITLE
Dashboard : tag icon should not appear in some cases 

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#9374]
Technician and group both support special values : **myself** and **my groups**

When these values are selected, the font awesome tag appears.

![image](https://user-images.githubusercontent.com/14139801/127828518-c60ba6f5-48d5-4c6e-9a9d-3f9494893095.png)

**Comment by btry** [comment]
The problem seels to be related to a JS comparison to determine if the filter has a value.

**Comment by cconard96** [comment]
Fixed via #9382
