### ISSUE TITLE
PHP notices on infocom reports

### ISSUE THREAD

**Issue by cedric-anne** [glpi-project/glpi#9376]
**Describe the bug**

When displaying "Hardware financial and administrative information" report, it triggers some PHP notices

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

1. Create a computer.
2. Enable infocom data in "Management" tab.
3. Define a value, an amortization type and duration.
4. Go to "Tools > Reports" and display "Hardware financial and administrative information" report.
5. See PHP notices.

**Logs**

```
[2021-08-02 09:41:27] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: name in /var/www/glpi/inc/stat.class.php at line 1894
  Backtrace :
  inc/stat.class.php:1606                            Stat->generateCsvFile()
  front/report.infocom.php:245                       Stat->displayLineGraph()
  front/report.infocom.php:298                       display_infocoms_report()
  
[2021-08-02 09:41:27] glpiphplog.NOTICE:   *** PHP Notice (8): Undefined index: name in /var/www/glpi/inc/stat.class.php at line 1894
  Backtrace :
  inc/stat.class.php:1606                            Stat->generateCsvFile()
  front/report.infocom.php:325                       Stat->displayLineGraph()
```

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.5-git-9.5/bugfixes-3b8bd39c37 ( => /var/www/glpi)
Installation mode: GIT
```

**Comment by delcroip** [comment]
I think there is a mix up when using the Chartlist lib; according to doc there is 2 possible usage in the examples: https://gionkunz.github.io/chartist-js/examples.html 

- label and series as  array(array(int)) (Time Series with Moment.js)
- series as JSONobject(name:str, data:array(x,y)) (Using events to replace graphics)

But in the code there is label with series as JSON object --> It cannot work
