### ISSUE TITLE
[9.5] Translation of "Mio" missing in part "#. TRANS: list of unit (o for octet)"

### ISSUE THREAD

**Issue by michelr44** [glpi-project/glpi#9381]
Hi,
at least in fr_FR.po and en_GB.po, the translation of "Mio" is missing in part "#. TRANS: list of unit (o for octet)".
In fr_FR.po, it's about line #10820.
It can impact the display in asset management (see https://forum.glpi-project.org/viewtopic.php?id=281561)

Another thing, in French, we also use ko, Mo, Go and To instead of kio, Mio, Gio et Tio.
Do I have to open another issue ?

**Comment by trasher** [comment]
Hi,
Translations issues should be handled on transifex https://www.transifex.com/glpi/GLPI/dashboard/
