### ISSUE TITLE
[GLPI 9.5.5] Unable to see FAQ documents with any profile

### ISSUE THREAD

**Issue by capu81** [glpi-project/glpi#9383]
**Describe the bug**

I've a lot of knowledge base items but i can't see any attachment documents with any profile (super-admin or self-service) in FAQ

**Page(s) URL**

helpdesk.faq.php

**To reproduce**

1. Go to FAQ
2. Click on any knowledgebase with attachments (here i can see the list of documents and i can click on it to open)
3. Can only see the faq description without documents (no left menù)

**Expected behavior**

See documents

**Logs**

No error in log

**Screenshots**
Here i can see the documents and i can access it
![01](https://user-images.githubusercontent.com/25194917/127990655-38de3cc8-357b-4806-aa39-9a3a55977fed.png)

Here i can see only the description
![02](https://user-images.githubusercontent.com/25194917/127990749-d76b68f8-a140-49b2-ae27-b2f8818c3357.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

Operating system: Linux intranet 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64
PHP 8.0.9 fpm-fcgi (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apcu, bz2, calendar, cgi-fcgi, ctype, curl,
	date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, igbinary, intl, json, ldap, libxml, mbstring, mysqli, mysqlnd,
	openssl, pcre, pdo_mysql, posix, readline, redis, session, shmop, snmp, sockets, sodium, standard, sysvmsg, sysvsem, sysvshm,
	tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files"
	upload_max_filesize="2M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at servizi.comune.calenzano.fi.it Port 80)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
Server Software: Ubuntu 20.04
	Server Version: 10.3.30-MariaDB-0ubuntu0.20.04.1
	Server SQL Mode: 
	Parameters: glpi@localhost/glpi
	Host info: Localhost via UNIX socket

**Additional context**

if i use knowbaseitem.form.php instead helpdesk.faq.php it works with all profile, if i use helpdesk.faq.php don't work with any profile
![03](https://user-images.githubusercontent.com/25194917/127991758-f9d97708-7793-4e32-a4b5-001da6d90863.png)

**Comment by cedric-anne** [comment]
Hi,

This feature has been developped recently, but on master branch (see #8847).

Dusplicates #8523.

Regards
