### ISSUE TITLE
Rights to create SIM card

### ISSUE THREAD

**Issue by neutrolino** [glpi-project/glpi#9389]
Only administrators have rights to create SIM card assets.
It is not possible to grant full rights to other profiles to the SIM card asset.

![изображение](https://user-images.githubusercontent.com/68535525/128184391-28cc5fa8-82c3-4293-b685-ed841fc562e7.png)
GLPI 9.5.5 ( => /var/www/html/glpi) Installation mode: TARBALL

Operating system: Linux sv-helpdesk-01 4.15.0-151-generic #157-Ubuntu SMP Fri Jul 9 23:07:57 UTC 2021 x86_64 PHP 7.2.24-0ubuntu0.18.04.8 apache2handler (Core, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, 	apcu, bz2, calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, http, iconv, imap, intl, json, 	ldap, libxml, mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, propro, raphf, readline, session, shmop, snmp, 	sockets, sodium, standard, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="600" memory_limit="512M" post_max_size="500M" safe_mode="" session.save_handler="files" 	upload_max_filesize="500M"  Software: Apache/2.4.29 (Ubuntu) (Apache/2.4.29 (Ubuntu) Server at helpdesk.technomoscow.ru Port 443) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0 Server Software: (Ubuntu) 	Server Version: 5.7.35-0ubuntu0.18.04.1 	Server SQL Mode:  	Parameters: glpi@localhost/glpi 	Host info: Localhost via UNIX socket_

**Comment by btry** [comment]
Hi

Simcards are implemented as components, like RAM, mainboard, or other internal parts of a computer.

To allow a user to manage simcards you must tune the rights on components

![image](https://user-images.githubusercontent.com/14139801/128191994-0fb7e8f1-9622-4fe3-b6f7-2b07850f6fdc.png)

**Comment by WilliamBlake97** [comment]
Hola:
Yo tengo todos los privilegios de Super-Admin, y tampoco puedo tener los privilegios de crear tarjetas SIM.
![GLPI - Tarjetas sim - Google Chrome](https://user-images.githubusercontent.com/97705003/149413138-71e40bb1-720e-4604-8dc9-2a86329655b5.jpg)
