### ISSUE TITLE
Show planned project task in the planning

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#94]
http://forum.glpi-project.org/viewtopic.php?id=118889

Show project task in each member type  User of the project task team?

**Comment by orthagh** [comment]
We need to discuss soon of features added in 0.91.
Imo tickets task and planning need a refresh.

**Comment by orthagh** [comment]
see #213

**Comment by yllen** [comment]
[Fri Feb 05 16:43:38 2016] [error] [client ::1] PHP Fatal error:  Class 'value' not found in /home/yllen/gitsvn/inc/planning.class.php on line 780, referer: http://localhost/glpisvn/front/planning.php?limititemtype=value&_date=05-02-2016&date=2016-02-05&type=month&submit=Show&_glpi_csrf_token=99aa322ce18da71f93b1535164a91d77

**Comment by orthagh** [comment]
big commit incoming for planning (complete refresh with [fullcalendar](http://fullcalendar.io/))

**Comment by pvasener** [comment]
@yllen Sorry, I can't reproduce the problem. I get no error clicking on the 'Show' button. I tried with various filters.

**Comment by yllen** [comment]
@pvasener corrected by @orthagh

**Comment by yllen** [comment]
I have another problem: your SQL request is wrong
In glpi_projecttasks, you can have empty plan_end_date with a planned_duration.
So you must define the plan_end_date given in the request

**Comment by yllen** [comment]
I search in all the code and my request is stupid.
You can't show project task in the planning because you can have duration without begin or end.
So it's not possible to show it in the planning
