### ISSUE TITLE
Use composer for plugin's dependencies

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#941]
Hi

I'm searching for a solution to use additional PHP libraries for plugins.

I found something interesting there 
https://github.com/wikimedia/composer-merge-plugin

This plugin for Composer allows searching for .json files in arbitrary directories to be added in GLPi's composer.json (for GLPi this would be **plugins/*/composer.json** )

I did a try and looks to be working great.

Additional librarires are saved in /vendor and are available with the existing autoload system in GLPi.  This also allows a single copy of a lib when several plugins have the same dependencies.

**Comment by trasher** [comment]
Hello,

I've already seen this plugin; for the plugins, it would be a good idea. The only possible negative point I see right now is that require a quite recent release of composer, we'll have to ensure that most distro packages are ok (it is for Fedora/RHEL/CentOS).

One question: each plugin will provide its own composer stuff, which can be used standalone? It would be used to build plugin releases archives, for example.

**Comment by remicollet** [comment]
I dont think having all dep (core + plugins) in glpi/vendor directory is a good idea.

Especially as the GLPI tarball will provide the vendor dir, plugin installation should not require to run composer (half of the users don't even know what composer is... see the various reports about broken RC2)

A plugin can of course provides its own composer.json, and then its vendor directory (see for example {next,own}cloud plugins). The release process of the plugin need to include this step (composer) and the tarball have to include the vendor directory. The glpi/plugins/foo/vendor/autoload.php can then be load in the plugin setup script.

**Comment by tomolimo** [comment]
I agree with Remi: each plugin should provide its own environment, otherwise we may have risks of breaks  in GLPi or other plugins.

**Comment by trasher** [comment]
I totally agree with @remicollet ; I had in mind it would be used only for developpers/advanced users.

As for the release process, that was the point of my question from the plugin side.
On the glpi side, if no plugins are present when running the composer install for the release, vendor dir would only contains glpi's deps, and not plugins ones; right? In that case, that does not really change anything, it only add a useless dep.

**Comment by btry** [comment]
Hi

@trasher 

Debian stable 8 does not have Composer in their repo. They need to wait for Stretch or install it by hands.

About your question : yes each plugin may have its own composer.json file. Have a look to the path I gave in bold text. The joker char does the stuff. 

@remicollet 
I tried with as you described at first but it seems to not work as expected. Have a

**Comment by btry** [comment]
Using a standalone vendor directory for the plugin satisfies my needs. 

Thank you for your feedbacks. Closing
