### ISSUE TITLE
Website : https://glpi-project.org/resources/ target to freenode

### ISSUE THREAD

**Issue by camlafit** [glpi-project/glpi#9417]
Hello

On https://glpi-project.org/resources/ project target to a death IRC link.
I don't know if irc really active but actual link don't allow to communicate with other user
I found also a irc channel fork on libera.chat

**Comment by camlafit** [comment]
Hello

I've not found any change, is it normal ?

**Comment by trasher** [comment]
I found no dead link on website. Anyways, IRC is no longer used, and Freenode seems to be kind of closed; maybe try telegram: https://t.me/glpien

**Comment by trasher** [comment]
BTW, link will be removed on GLPI website when someone with access have time to work on that

**Comment by camlafit** [comment]
Looks done indeed nor more freenode link
The webchat link was broken, as we could display webchat interface but not connected as they have disable feature to allow connection.

I was not enough explicit about broken behavior.

Thanks
