### ISSUE TITLE
alerte

### ISSUE THREAD

**Issue by member26** [glpi-project/glpi#9423]
I must change the glpi code to have an alert when the state of ticket clos can you plz tell me where i should change the code???

**Comment by jcervantes-sipecom** [comment]
Hi, It's no necessary to change the code, GLPI can do it with Notifications, be aware that you should need to configure SMTP notificationes before:

![image](https://user-images.githubusercontent.com/56606032/130248078-572ad145-a90c-40b0-8950-bf2e35c9d21c.png)

![image](https://user-images.githubusercontent.com/56606032/130248297-37b582bb-039a-4946-a739-fb979617a08f.png)

Also you can customize a Template with the Notifications you want to receive.

**Comment by member26** [comment]
thanks for answer me but i really should because in the next step of my
project i will send a message when the status of ticket is clos the email
are take it  by the new formulaire that i changed too  can you plz help me

**Comment by trasher** [comment]
Please use [forums](http://forum.glpi-project.org) to get support.
