### ISSUE TITLE
Single license can't contains multi softwares 

### ISSUE THREAD

**Issue by icy1xtee** [glpi-project/glpi#9424]
**Describe the bug**

Can't attach few softwares to single license.

**Page(s) URL**

front/softwarelicense.php

**To reproduce**

1. Go to Management -> Licenses
2. Click on 'add' button
3. When you choose Software you can't pick multi (few or more softwares)

**Expected behavior**

It will be awesome if I could pick few software under the license. Now it works backwards, you can pick few license under single software. I found this unreasoned. There are a lot of situations when I buy license that refer to many softwares. For example: We bought Autodesk license, but there are no software "Autodesk", there are a lot of stuff like AutoCAD, Revit, DWG Trueview and so on and so on.

**Screenshots**

<img width="593" alt="Снимок экрана 2021-08-20 в 12 59 45" src="https://user-images.githubusercontent.com/89250400/130216722-dc09a82f-5669-4cbf-bdb0-fabb7a8ccdb6.png">

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

GLPI 9.5.4

**Comment by fgendorf** [comment]
I ask for it in the past #1398

**Comment by icy1xtee** [comment]
> I ask for it in the past #1398

There are no solution yet? it's been a long time..

**Comment by fgendorf** [comment]
I think they don't buy expensive software, like Adobe package, Autocad
Package, Microsoft Assurance, etc. So it's not a big deal for him...
_________________________
Frederico Gendorf
