### ISSUE TITLE
ldap: Accept User principal name (UPN) format 

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#9426]
**Describe the bug**

If you enable Authentication via ldap it is not possible to login with the User principal name format.

**Page(s) URL**

index.php

**To reproduce**

1. Enable autentication with ldap
2. Go to login-page
3. Enter username@domain.xy
4. Select your domain from Dropdown
==> Incorrect username or password

**Expected behavior**
User is logged in

**Logs**

```
unsuitable
```

**Screenshots**

![grafik](https://user-images.githubusercontent.com/25504254/130252033-261cfc06-bf73-475d-b843-57b5c55f1bde.png)
![grafik](https://user-images.githubusercontent.com/25504254/130252072-cc9958a3-2560-4c28-b8f4-f0451e8f75c0.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
unsuitable
```

**Additional context**

Microsoft requires for the usage of m365 that the user login with her Mailadress. It is not possible to explain the users that they have to login everywhere with there mailadress - execepted glpi. That will never works :-)

More Information from Microsoft: [https://docs.microsoft.com/en-us/windows/win32/secauthn/user-name-formats](https://docs.microsoft.com/en-us/windows/win32/secauthn/user-name-formats)

**Comment by vollkommenIrrelevant** [comment]
bump

**Comment by vollkommenIrrelevant** [comment]
Can please somebody have a look at this?

**Comment by vollkommenIrrelevant** [comment]
bump

**Comment by vollkommenIrrelevant** [comment]
still important to improve...

**Comment by cedric-anne** [comment]
Hi,

The UPN format should work if the related GLPI LDAP configuration is correct.
You could ask for support on [community forum](https://forum.glpi-project.org/), or consider taking a [subscription](https://glpi-project.org/subscriptions/) to get professionnal support.

I close this issue as we do only track bugs here.

Regards

**Comment by vollkommenIrrelevant** [comment]
lol... It is not working, i attached screenshots that it is not working and you close the ticket.

**Comment by cedric-anne** [comment]
> lol... It is not working, i attached screenshots that it is not working and you close the ticket.

This is not a bug a configuration issue. As I said, we do not track support issues here.
