### ISSUE TITLE
Cannot activate plugins from the Pop-UP using the Spanish language (LATAM)

### ISSUE THREAD

**Issue by jcervantes-sipecom** [glpi-project/glpi#9427]
**Describe the bug**

When GLPI is using the Spanish language (Latin America) [Español (America Latina)] and a plugin is installed, a pop-up appears to activate the plugin, but it does not work, it appears with this text:

```
¡El plugin TaskDrop ha sido instalado!

¿Desea %a activar el enlace?
```

And it does not allow activating it from the Pop-up, you have to go to the plugin and activate it manually.

**Page(s) URL**

/front/plugin.php

**To reproduce**

1. Change the language from English to Spanish (Latin America) [Español (America Latina)]
2. Go to Setup> Plugins
3. Install a new Plugin
4. The pop-up to activate the plugin will appear, but it will not be possible because the text %a is not an activatable link and the plugin must be activated manually. 

**Expected behavior**

Having the Spanish language (Latin America) to be able to activate the plugin once installed from the Pop-up.

**Screenshots**

![image](https://user-images.githubusercontent.com/56606032/130258636-b50ebe94-f163-46d3-a5a8-c23468042abb.png)

**Comment by trasher** [comment]
Hi, this seems a translation issue, that should be fixed or reported on transifex https://www.transifex.com/glpi/GLPI/dashboard/
