### ISSUE TITLE
Extend DropDown "Results to display by page"

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#9433]
**Describe the bug**

The Dropdown-Menu is limitied for 200 what is to small. It should be possible to extend it to 2000 or unlimited.

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

$PATH_TO_GLPI/front/preference.php

1. Click on UserName at top right
2. Clilck on Personalization at top right
3. Extend Dropdown at "Results to display by page
4. See that the maximum is 200

**Expected behavior**

The Maximum should me much higher or unlimited.

**Logs**

```
unsuitable
```

**Screenshots**

![grafik](https://user-images.githubusercontent.com/25504254/130596395-b7b032a8-8e19-4976-87e4-dc0b5ab7e2cc.png)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
unsuitable
```

**Additional context**

**Comment by vollkommenIrrelevant** [comment]
bump

**Comment by vollkommenIrrelevant** [comment]
Can please somebody have a look at this?

**Comment by cedric-anne** [comment]
Hi,

There are performances issues on search page, which can be a real problem depending on used search criteria and displayed columns. We are trying to fix these (see #9495), but we still not found a solution that suits to everyone.

I am not sure we will not accept to increase max value in this dropdown until these performances issues are not fixed.

I close this issue as we only track bugs here. Enhancement proposals are tracked on [suggestion website](https://glpi.userecho.com/).

Regards

**Comment by vollkommenIrrelevant** [comment]
Ps. We need to show more as 200 devices by default. Is there a different solution?

**Comment by vollkommenIrrelevant** [comment]
It's working without coding. But I have to change this value again from 200 to 2000 after logout/login...
![grafik](https://user-images.githubusercontent.com/25504254/136176034-e82842f4-a6db-4170-9cb3-0d64f80b31a9.png)

**Comment by vollkommenIrrelevant** [comment]
bump
