### ISSUE TITLE
[9.5.1] : cannot associate massively a computer with an appliance

### ISSUE THREAD

**Issue by ericferon** [glpi-project/glpi#9434]
**Describe the bug**

In massive actions, when associating computers with an appliance, I get an sql error message

**Page(s) URL**

http://localhost/glpi/front/computer.php#modal_massaction_contente59f855a9415b6a820471339573d9573

**To reproduce**

1. Go to 'Assets>Computers'
2. Select 2 of them
3. Click on "Actions" and select the action "Associate to appliance"

**Expected behavior 1**

I should be able to select an appliance in the dropdown lists

**Logs error 1**

```
  *** MySQL query error:
  SQL: SELECT * FROM `glpi_appliancetypes` WHERE `id` IN (SELECT DISTINCT `appliancetypes_id` FROM `glpi_appliances` WHERE `glpi_appliances`.`is_deleted` = '0' AND ((`appliances`.`entities_id` IN ('2', '7', '10', '9', '8', '705', '719', '745', '863', '63', '1125', '984', '954', '923', '1128', '978', '827', '861', '757', '779', '845', '794', '1013', '1015', '1016', '1017', '848', '1023', '1008', '1009', '864', '1034', '1131') OR (`appliances`.`is_recursive` = '1' AND `appliances`.`entities_id` IN ('0', '5', '6', '1'))))) ORDER BY `name`
  Error: Unknown column 'appliances.entities_id' in 'where clause'
  Backtrace :
  inc/dbmysqliterator.class.php:95                   
  inc/dbmysql.class.php:857                          DBmysqlIterator->execute()
  inc/appliance.class.php:407                        DBmysql->request()
  inc/appliance.class.php:511                        Appliance::dropdownMA()
  inc/massiveaction.class.php:661                    Appliance::showMassiveActionsSubForm()
  ajax/dropdownMassiveAction.php:48                  MassiveAction->showSubForm()

```

**Additional context for error 1**

Solution : change "appliances" into "glpi_appliances" in file inc/appliance.class.php, function dropdownMA, call to getEntitiesRestrictCriteria, line 394

**Comment by trasher** [comment]
Please try with up to date current bugfixes branch (or [latest nightly](https://github.com/glpi-project/glpi/actions?query=workflow%3A%22GLPI+nightly+build%22))
