### ISSUE TITLE
Liste demandeur vide ; observateur/assignée remplies

### ISSUE THREAD

**Issue by Sicoval31** [glpi-project/glpi#9461]
Bonjour, 
lors de la création d'un ticket avec l'interface standard (pour le helpdesk), la liste déroulante pour assigner un **demandeur** retourne l'erreur "**_Les résultats ne peuvent être chargés_**"
![image](https://user-images.githubusercontent.com/42040529/131625984-949794c6-c682-4e50-8f0f-a04286080209.png)
Le mode debug n'apporte pas d'indication complémentaire.

Les liste **observateur** **ou assigné à**, sont elles correctement renseignées.
Le php-errors.log ne semble pas remonter d'erreur non plus (pas d'erreur à l'heure de création du ticket), mais j'ai des erreurs concernant ceci (erreur apparaissant à l'écran à chaque modification d'un ticket ou ajout d'un suivi) :
```
glpiphplog.WARNING:   *** PHP User Warning (512): Missing type for Ticket template! in C:\wamp\www\glpi\inc\commonitilobject.class.php at line 7957
  Backtrace :
  inc\commonitilobject.class.php:7957                trigger_error()
  inc\commonitilobject.class.php:7918                CommonITILObject->getTemplateFieldName()
  inc\commonitilobject.class.php:792                 CommonITILObject->getITILTemplateToUse()
  inc\ticket.class.php:974                           CommonITILObject->handleTemplateFields()
  inc\commondbtm.class.php:1484                      Ticket->prepareInputForUpdate()
  inc\ticket.class.php:2332                          CommonDBTM->update()
  inc\commonitilactor.class.php:382                  Ticket->updateDateMod()
  inc\group_ticket.class.php:66                      CommonITILActor->post_addItem()
  inc\commondbtm.class.php:1173                      Group_Ticket->post_addItem()
  inc\commonitilobject.class.php:1023                CommonDBTM->add()
  inc\ticket.class.php:1169                          CommonITILObject->prepareInputForUpdate()
  inc\commondbtm.class.php:1484                      Ticket->prepareInputForUpdate()
  front\ticket.form.php:72                           CommonDBTM->update()
```

GLPI 9.5.5 (sur windows server 2016 + wamp 3.2.5)
php 8.0.8
mysql 8.0.21
apache 2.4.46

**Comment by Sicoval31** [comment]
tag invalid ? pourquoi
invalid Tag ? why ?

**Comment by trasher** [comment]
It is asked to use english only.

**Comment by Sicoval31** [comment]
even if my english is not as fluent as yours and the glpi dev' are french ???? lol
So i'll try to repost my ticket in english with high risk that the dev doens't understand my problem !
Nice idea :)

**Comment by cconard96** [comment]
I'm a native English speaker. Even if posts are done through a translation service like Google Translate, having everything posted in one language makes it easier to search through issues.

**Comment by trasher** [comment]
@Sicoval31 that kind of answer is really a pleasure to read. 

If you prefer to speak french, go on the forums.
Thank you.
