### ISSUE TITLE
No vertical scrollbar for followup tab in split view

### ISSUE THREAD

**Issue by ladenree76000** [glpi-project/glpi#95]
on  Online Demo(03/09/2015) ( example here http://demo.glpi-project.org/front/ticket.form.php?id=27183)
in SplitView , when Followup/Task/timeline Tab is higher than screen, vertical scrollbar is missing for right tab. 
it is ok for left tab (ticket)
(browser :  FF)

**Comment by orthagh** [comment]
You're right, it's fixed by ecb5c17 commit (yesterday).

I will update demo this afternoon
