### ISSUE TITLE
Bug in DB update script from 0.90.5 to 91

### ISSUE THREAD

**Issue by ksandell** [glpi-project/glpi#952]
In file `install/update0905_91.php`, lines 404-405 should be:
```php
      $query = "INSERT INTO `glpi_apiclients`
                  VALUES (1, 1, 1, 'full access', NOW(), 1, NULL, NULL, NULL, '', NULL, 0, NULL);";
```
(_3rd last NULL replaces ''_)

This avoids a `app_token_date` field invalid format error during DB upgrade.

**Comment by tomolimo** [comment]
fixed in #879
