### ISSUE TITLE
Add more insightful logging

### ISSUE THREAD

**Issue by fralla2** [glpi-project/glpi#9531]
Hy,

We came across an issue while debugging a problem with the plugins FusionInventory and had to modify a core file of GLPI to obtain enough meaningful logs for the problem.

I'm pretty sure the community could benefit from this change to troubleshoot other issues in the future too so I propose to add this to the main code..

https://github.com/glpi-project/glpi/blob/7c4fe46b69bb68bc49eb8da0765fcdada4068040/inc/commondbtm.class.php#L349

**Change from this :** 
`sprintf(
   'getFromDBByCrit expects to get one result, %1$s found!',
   count($iter)
)`

**To this :** 
`sprintf(
   'getFromDBByCrit expects to get one result, %1$s found! in table %2$s with criterias %3$s',
   count($iter), print_r($crit['FROM'],1), print_r($crit['WHERE'],1)
)`

This could potentially be apply to other parts of the code too with some minor modifications...

**Reference issue :** 
https://github.com/fusioninventory/fusioninventory-for-glpi/issues/3159#issuecomment-916259899

Thanks
Francois

**Comment by trasher** [comment]
Please open a pull request with your change proposal

**Comment by cedric-anne** [comment]
Done in #9538 .
