### ISSUE TITLE
1 contract = 1 asset only

### ISSUE THREAD

**Issue by Sicoval31** [glpi-project/glpi#9536]
GLPI 9.5.5
After creating contracts and assets (appli), i want to link my applicationS with this contract but :$
 - I can link only 1 asset with my contract
 - or i can link only one contract with my asset
Nor are the reality, many contracts are signd for multiple assets, and some assets are covered with many contracts.

Thanks to permit that.

-----
J'ai crée un contract (apple dev) afin de gérer mes applis mobiles via "applications".
A ce jour, je ne peux lier à un contrat qu'un seul élément (ce qui ne reflete pas la réalité) et inversement, je ne peux lier qu'un contrat à un asset (ce qui ne reflete pas non plus la réalité).
En effet, mon contrat Apple Dev (tout comme gogle dev) me permet de gérer plusieurs applications ; elles même gérées par plusieurs contrats (apple et google en l'occcurence).

Merci de permettre cela.
Cdlt

**Comment by orthagh** [comment]
Hello

In the main form of the contract, please check the following field:
![image](https://user-images.githubusercontent.com/418844/133090756-95b9c3d0-08e9-4011-a7b7-a8b594fb23dc.png)

**Comment by Sicoval31** [comment]
Thanks
