### ISSUE TITLE
Locked object not purposed in search engine

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#954]
Numbers used by objectlock are always used by notepad

**Comment by tomolimo** [comment]
What do you mean exactly?

**Comment by tomolimo** [comment]
ah ok, I understand, forgot my previous comment.

**Comment by tomolimo** [comment]
This is an interesting question, as I asked that several months ago when I was about to commit these, and I didn't get any satisfactory answers...:)

We must have a maintained list of those numbers to know exactly which new numbers can be taken for any new dev, or also for any new plugin....

**Comment by orthagh** [comment]
For get an empty number: https://github.com/glpi-project/glpi/blob/master/tools/getsearchoptions.php

**Comment by tomolimo** [comment]
ok, thank you, I'll use this in the future
