### ISSUE TITLE
Asset Transfering problems with licenses

### ISSUE THREAD

**Issue by felipebart10** [glpi-project/glpi#9542]
**Description**
As reported in issue #9532, the problem persists on version 9.5.5. When transfering computers, I've identified that some licenses are being thrown at the trashbin. From what I saw in new tests, this issue happens when licenses' 'Number' field is 1. When we execute the routine, 'Number' field is increased to 2 and the license is put in the bin. This occurs with our OEM Windows/Office licenses and doesn't make sense since OEM licenses should have 1 unit only. I've also identified that in some cases, a license is deleted and a copy of this license and the software linked to it is created. This happened with Photoshop and CorelDRAW installations, leading to unnecessary duplications and confusion. I saw the source code via GitHub and noticed that the transfer routine has a section that tests 'Number' field (will put down below). I do not know if this was a defined business rule by the project team but everytime we have to transfer, we need to restore the license and edit its 'Number' field again. 

The problem only occurs with computer assets.

**Page(s) URL**
/front/transfer.action.php

**Reproduction**
1. Go to Assets > Computers
2. Mark a computer with softwares/licenses and on 'Actions' choose 'Add to transfer list'
3. Choose a transfer template and an entity to transfer the PC
4. Go to Management>Licenses and see the trashbin with some licenses that belongs to the transfered PC.
5. On each license, see the 'Number' field to see that it was incremented by 1.

**Expected behavior**
The transfer should be done without putting licenses registers at the bin and not be creating copies of some transfered licenses. Licenses should mantain their correct quantity at 'Number' field after the process is done.

**Code snipet**
file: glpi/transfer.class.php

```PHP
   function transferAffectedLicense($ID) {
      global $DB;

      $item_softwarelicense = new Item_SoftwareLicense();
      $license                  = new SoftwareLicense();

      if ($item_softwarelicense->getFromDB($ID)) {
         if ($license->getFromDB($item_softwarelicense->getField('softwarelicenses_id'))) {

            //// Update current : decrement number by 1 if valid
            if ($license->getField('number') > 1) {
               $license->update(['id'     => $license->getID(),
                                      'number' => ($license->getField('number')-1)]);
            } else if ($license->getField('number') == 1) {
               // Drop license
               $license->delete(['id' => $license->getID()]);
            }

            // Create new license : need to transfer softwre and versions before
            $input     = [];
            $newsoftID = $this->copySingleSoftware($license->fields['softwares_id']);

            if ($newsoftID > 0) {
               //// If license already exists : increment number by one
               $iterator = $DB->request([
                  'SELECT' => ['id', 'number'],
                  'FROM'   => 'glpi_softwarelicenses',
                  'WHERE'  => [
                     'softwares_id' => $newsoftID,
                     'name'         => addslashes($license->fields['name']),
                     'serial'       => addslashes($license->fields['serial'])
                  ]
               ]);

               $newlicID = -1;
               //// If exists : increment number by 1
               if (count($iterator)) {
                  $data     = $iterator->next();
                  $newlicID = $data['id'];
                  $license->update(['id'     => $data['id'],
                                          'number' => $data['number']+1]);

               } else {
                  //// If not exists : create with number = 1
                  $input = $license->fields;
                  foreach (['softwareversions_id_buy',
                                 'softwareversions_id_use'] as $field) {
                     if ($license->fields[$field] > 0) {
                        $newversID = $this->copySingleVersion($license->fields[$field]);
                        if (($newversID > 0)
                              && ($newversID != $license->fields[$field])) {
                           $input[$field] = $newversID;
                        }
                     }
                  }

                  unset($input['id']);
                  $input['number']       = 1;
                  $input['entities_id']  = $this->to;
                  $input['softwares_id'] = $newsoftID;
                  $newlicID              = $license->add(Toolbox::addslashes_deep($input));
               }

               if ($newlicID > 0) {
                  $input = ['id'                  => $ID,
                                 'softwarelicenses_id' => $newlicID];
                  $item_softwarelicense->update($input);
               }
            }
         }
      } // getFromDB

```

**Screenshots**

I uploaded an album on imgur with detailed printscreens. [Here it is](https://imgur.com/a/hKDIrhB)

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.5 ( => /var/www/html/glpi)
Installation mode: TARBALL
```

**Additional context**

Current Problem Workaround: to avoid this issue, our manager is manually changing the computer's location directly at the database. It is a risky solution which we don't even know its applicable and some human errors already happened. I already thanks you guys for the attention.

**Comment by trasher** [comment]
I made a try to reproduce on unit tests; but I was not able to reproduce

**Comment by trasher** [comment]
Yes,, it seems that all went as expected; but it was in the tests suite; this can differs.
To be sure this is not a configuration issue, you can maybe try with an empty database and see if you reproduce

**Comment by felipebart10** [comment]
Perfect. I will try with a completely fresh instance, create some entities and devices and will try to reproduce. Thanks!
