### ISSUE TITLE
Empty opening date issue is ramaining after updating from 9.5.4 to 9.5.5

### ISSUE THREAD

**Issue by GLPIFred** [glpi-project/glpi#9547]
Dears,

We have updated our GLPI from version 9.5.4 to 9.5.5 and we still have some ticket having an empty creation date field.

We are currently running version 9.5.5 and I'm wondering why this is still happening as it should have been fixed according to the screenshot below.

Is there anything else to do or to activate/deactivate to fix this ?

Thanks in advance for your replies.

![image](https://user-images.githubusercontent.com/90773013/133437348-635e48c7-1806-49fc-9cb1-74a788df1c36.png)

**Comment by cedric-anne** [comment]
Hi,

On 9.5.5, a fix was made to prevent the `date_creation` to be updated with current timestamp on each ticket update. This has nothing to do with your issue.

1. You should think about upgrading to 9.5.6 for security reasons.
2. You should provide a better description of your issue, including all requested informations in issue form (see https://github.com/glpi-project/glpi/issues/new?assignees=&labels=&template=bug_report.md ).

Regards

**Comment by GLPIFred** [comment]
Hi,

Thanks for your quick reply, we'll first update to latest 9.5.6 version and check if we still have our issue. which like this : 

empty opening date/ticket creation date for some tickets, not even all of them and not linked to entities.

I don't have a lot more infos about that actually as I'm also not even able to reproduce it by myself.

Thanks again.

![image](https://user-images.githubusercontent.com/90773013/133445409-e20fdb21-663f-4778-b954-5d71645d636b.png)
