### ISSUE TITLE
Antivirus for a computer

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#955]
https://github.com/glpi-project/glpi/commit/7708d07f8675d93037e541d91ed5db6857eb2239#diff-9ba546a723a78cbe34105e12e0c5c601

Can't search on Name IS/NOT IS (dropdown is empty)

**Comment by yllen** [comment]
Same number given in searchoption for Creation date and Expiration date

**Comment by yllen** [comment]
Why a GetSearchOption because you don't have search engine for this object?

**Comment by yllen** [comment]
Since many versions we don't put ":" after the label of the field

**Comment by yllen** [comment]
Don't use SELECT in a query but $DB->request

**Comment by yllen** [comment]
In computer, titre is too short for the table

**Comment by yllen** [comment]
Done for display title: https://github.com/glpi-project/glpi/commit/0e1a30eec62d9ace4edf15349be718d32f8604e6

**Comment by orthagh** [comment]
here is a pr for two of your notes: #972 

I didn't find the mentioned ":"

**Comment by trasher** [comment]
FYI, the ":" stuff has been fixed in 86854bf :)

**Comment by orthagh** [comment]
#972 merged
