### ISSUE TITLE
[cosmetics] Print parent elements in a less contrasted color

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#9559]
**Describe the bug**

Inline display of tree elements (for example: `Root Entity > Group Inc. > My Department` or `France > Toulouse > Building B`) in tables don't allow user to quickly see the relevant information (here, `My Department` or `Building B`).

**Expected behavior**

Parent elements should be in a less contrasted color. See screenshots.

**Screenshots**

- Before :
![before](https://user-images.githubusercontent.com/2104679/133755400-ccf0f421-847e-4de9-804f-93050622b138.png)
- After :
![after](https://user-images.githubusercontent.com/2104679/133755455-f884d0a2-4250-469b-a27d-3e754871534c.png)

**Suggested Fix**

I think it could be easily fixed with this patch:

```diff
diff --git a/css/styles.scss b/css/styles.scss
index a3cbb386f9..b1ed806e95 100644
--- a/css/styles.scss
+++ b/css/styles.scss
@@ -245,6 +245,10 @@ a, .btn-linkstyled {
    }
 }

+.lowcontrast, .lowcontrast a {
+   color: darkgray;
+}
+
 #page a.fa, #page a.far, #page a.fas {
    color: #222;

diff --git a/inc/search.class.php b/inc/search.class.php
index 859689ad58..e521d6f63e 100644
--- a/inc/search.class.php
+++ b/inc/search.class.php
@@ -7401,7 +7401,21 @@ JAVASCRIPT;
             } else {
                $value = preg_replace('/'.self::LBBR.'/', '<br>', $value);
                $value = preg_replace('/'.self::LBHR.'/', '<hr>', $value);
-               $out .= $value;
+               // Print parent elements with less contrasted color
+               if (preg_match('/ > /', $value)) {
+                  $values = preg_split('/ > /', $value);
+                  foreach ($values as $k => $v) {
+                     if ($k === array_key_first($values)) {
+                        $out .= '<span class="lowcontrast">' . $v . ' > ';
+                     } else if ($k === array_key_last($values)) {
+                        $out .= '</span>' . $v;
+                     } else {
+                        $out .= $v . ' > ';
+                     }
+                  }
+               } else {
+                  $out .= $value;
+               }
             }
             $out .= "</td>\n";
       }
```

Shall I make a merge request?

**Comment by mathieumd** [comment]
Suggestion posted here: https://glpi.userecho.com/fr/communities/1/topics/2028-show-parent-elements-in-a-less-contrasted-color

**Comment by mathieumd** [comment]
ping

**Comment by cconard96** [comment]
Feel free to open a pull request with this change so it can be reviewed.

**Comment by mathieumd** [comment]
PR #10464.
