### ISSUE TITLE
[9.5.5] Bug list of categories not recognized in braille

### ISSUE THREAD

**Issue by Priif** [glpi-project/glpi#9561]
Edit : the same problem occurs in all auto-complete dropdown lists.

Hi,

I have just migrated from GLPI 9.2.2 to 9.5.5.

In the **9.2.2 version**, when creating a ticket and selecting a data in the dropdown list of categories, the braille viewer translates the list correctly:
![image](https://zupimages.net/up/21/37/9lmz.png)

In **9.5.5 version**, this same list of categories is "empty" on the viewer:
![image](https://zupimages.net/up/21/37/7air.png)

This is very annoying because visually impaired people are now unable to choose a category. Can you help me?

Thanks

**Comment by Priif** [comment]
Any ideas ? Thanks

**Comment by trasher** [comment]
Unfortunately, no... There were many changes since 9.2.2, including updates of the lib used to display dorpdown lists (select2).

Maybe you should try with their examples (https://select2.org/getting-started/basic-usage for example) and see if you reproduce.
If so, you should open an issue on their side.

**Comment by Priif** [comment]
Hello,

Thank you for your help. I tried as you suggested on the select2 examples.

https://select2.org/data-sources/ajax

I reproduced the same problem, so it's from select2.

Thanks

**Comment by trasher** [comment]
Thanks for the feedback. Open an issue on select2 side (https://github.com/select2/select2/issues), and add a link to current issue (I'll keep it open for now).
Once it's been fixed on their side, we maybe can try to update.

**Comment by Priif** [comment]
Hi,

I opened an issue here: https://github.com/select2/select2/issues/6099.

Hope for a quick correction! Thank you for your help trasher :)
