### ISSUE TITLE
Incorrect presentation of information when there are 'zeros' in Login Field (User administration) [9.5.6]

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#9565]
I'm reviewing version 9.5.6 to upgrade.

We are currently at version 9.5.5, our user "login" field there are some "left zeros" as below

![image](https://user-images.githubusercontent.com/35368369/133818232-a3a32c90-bac2-4d67-aa8b-e61df2725909.png)

After the update to 9.5.6 the column does not show the correct user login...removing the zeros in left

![image](https://user-images.githubusercontent.com/35368369/133818472-4f3f22d3-5e83-495a-90ab-d1ad119397d1.png)

![image](https://user-images.githubusercontent.com/35368369/133818615-5b33296a-a0db-40e0-88c5-6afd245b007f.png)

**Comment by trasher** [comment]
Duplicates #9566
