### ISSUE TITLE
Fiber channel network ports

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#957]
https://github.com/glpi-project/glpi/pull/805

Why a getSearchOption? you don't have search engine for this object.
Use instead getSearchOptionToAdd if you want to have search since computers list

**Comment by orthagh** [comment]
The fiber channel was adapted from NetworkPortEthernet class.
That one has also getSearchOptions. See https://github.com/glpi-project/glpi/blob/master/inc/networkportethernet.class.php#L183 added in 0.84 i think (i was not in core team for this version).

I can't find any usage of theses searchoptions anyway.

**Comment by trasher** [comment]
What to do here? Should we drop `getSearchOption` from this object or change for an adapted `getSearchOptionToAdd()`? Ping @orthagh @wawax

**Comment by orthagh** [comment]
i think we could keep theses searchoptions.
They could be used with the rest/xml API.
We don't have equivalent in frontend but it's not very important.

**Comment by orthagh** [comment]
And so close this ticket and remove milestone
