### ISSUE TITLE
Error on mailgate

### ISSUE THREAD

**Issue by digisam1985** [glpi-project/glpi#9577]
I have this error on mailgate

`[2021-09-21 09:42:26] glpiphplog.CRITICAL:   *** Uncaught Exception ValueError: Unknown format specifier "m" in C:\xampp\htdocs\glpi\inc\mailcollector.class.php at line 926
  Backtrace :
  inc\mailcollector.class.php:926                    sprintf()
  inc\mailcollector.class.php:1755                   MailCollector->collect()
  inc\crontask.class.php:943                         MailCollector::cronMailgate()
  front\cron.php:83                                  CronTask::launch()`

**Comment by VOLKOVukr** [comment]
I have a similar problem (CentOS 7).

[2021-09-17 11:48:01] glpiphplog.CRITICAL:   *** Uncaught Exception Laminas\Mail\Exception\InvalidArgumentException: The input exceeds the allowed length in /var/www/glpi/vendor/laminas/laminas-mail/src/Address.php at line 78

  Backtrace :
  vendor/laminas/laminas-mail/src/Address.php:54     Laminas\Mail\Address->__construct()
  ...inas-mail/src/Header/AbstractAddressList.php:87 Laminas\Mail\Address::fromString()
  :                                                  Laminas\Mail\Header\AbstractAddressList::Laminas\Mail\Header\{closure}()
  ...inas-mail/src/Header/AbstractAddressList.php:66 array_map()
  vendor/laminas/laminas-mail/src/Headers.php:548    Laminas\Mail\Header\AbstractAddressList::fromString()
  vendor/laminas/laminas-mail/src/Headers.php:284    Laminas\Mail\Headers->loadHeader()
  vendor/laminas/laminas-mail/src/Headers.php:105    Laminas\Mail\Headers->addHeaderLine()
  ...r/laminas/laminas-mail/src/Storage/Part.php:113 Laminas\Mail\Headers::fromString()
  ...laminas/laminas-mail/src/Storage/Message.php:53 Laminas\Mail\Storage\Part->__construct()
  ...or/laminas/laminas-mail/src/Storage/Pop3.php:64 Laminas\Mail\Storage\Message->__construct()
  ...aminas-mail/src/Storage/AbstractStorage.php:268 Laminas\Mail\Storage\Pop3->getMessage()
  inc/mailcollector.class.php:721                    Laminas\Mail\Storage\AbstractStorage->current()
  inc/mailcollector.class.php:1755                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()


And this affects the sending of the service satisfaction survey, they are not sent. In this case, the rest of the notifications come.

**Comment by digisam1985** [comment]
I have version 9.5.6 of glpi.
