### ISSUE TITLE
Associated items in ticket list

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#959]
Only the first associated item is listed.
Ok in 0.90.6

**Comment by orthagh** [comment]
Hello @yllen.

I tested on the current master without find the issue:

The ticket detail:
![image](https://cloud.githubusercontent.com/assets/418844/18473748/eaf7a3a4-79be-11e6-8b51-7061e9bd6fcb.png)

The ticket list
![image](https://cloud.githubusercontent.com/assets/418844/18473739/e0bb66d2-79be-11e6-8f8b-af7001eb945d.png)

**Comment by trasher** [comment]
Cannot reproduce on my side, all items are correctly displayed, as in @orthagh 's screenshots.

**Comment by chaoservices** [comment]
Perhaps @yllen means the associated items list on the email notification?

After upgrading our system from 0.85 to 0.90.5 the template tags are no longer inserting content.

**Comment by yllen** [comment]
No I said in ticket list (search engine) not in ticket form

**Comment by orthagh** [comment]
My second screenshot is from ticket list

**Comment by Armin83** [comment]
@yllen 
It works on glpi demo today 9.1 with 2 items.

![9 1-demo-works](https://cloud.githubusercontent.com/assets/19192087/19449885/a8af916a-94a7-11e6-99c4-a1150ac2c1f4.JPG)

**Comment by yllen** [comment]
It's seams ok now
