### ISSUE TITLE
Failed operation for location clone action

### ISSUE THREAD

**Issue by WebGregGit** [glpi-project/glpi#9592]
**Describe the bug**

While I try clone Location I'm getting message: 

Failed operation
(0 authorizations problems, 1 failures)
p.338: Error on executing the action

**Page(s) URL**

front/location.php

**To reproduce**

Setup > Dropdowns > Locations > Check one and chose from action Clone

**Expected behavior**

I need clone Locations because I need to add many rooms with the same Latitude and Longitude for example.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.5 ( => /var/www/html/glpi)
Installation mode: TARBALL

Operating system: Linux glpi 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64
PHP 7.4.3 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apc, apcu, bz2,
	calendar, ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imap, intl, json, ldap, libxml,
	mbstring, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, snmp, soap, sockets, sodium, standard,
	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib)
Setup: max_execution_time="30" memory_limit="128M" post_max_size="20M" safe_mode="" session.save_handler="files"
	upload_max_filesize="20M" 
Software: Apache/2.4.41 (Ubuntu) (Apache/2.4.41 (Ubuntu) Server at glpi.domain.com Port 443)
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
Server Software: (Ubuntu)
	Server Version: 8.0.26-0ubuntu0.20.04.2
	Server SQL Mode: 
	Parameters: glpiuser@localhost/glpidb
	Host info: Localhost via UNIX socket
```

**Additional context**

While I try clone item status I'm getting error too but with reason given: "State must be unique!". With Locations there is no reason given and I don't realy know why it is blocked.

**Comment by trasher** [comment]
You should try with latest stable release and see if you reproduce.

**Comment by WebGregGit** [comment]
I have 9.5.6 too - the same problem.
