### ISSUE TITLE
rej and orig files of /vendor/laminas/laminas-mail/src/Header/ContentDisposition.php left in release tarball

### ISSUE THREAD

**Issue by lirmikey** [glpi-project/glpi#9597]
**Describe the bug**

rej and orig files of /vendor/laminas/laminas-mail/src/Header/ContentDisposition.php left in release tarball

**Page(s) URL**

If applicable, page(s) URL where the bug happens.

**To reproduce**

**Expected behavior**

only patched file of ContentDisposition.php should exist in release tarball

**Logs**

```
paste logs here
Find them in *-error.log files under glpi/files/_log/
```

**Screenshots**

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
Version 9.5.6
```

**Additional context**

**Comment by cedric-anne** [comment]
Hi,

Thanks for the report. The patch was applied twice during release process. #9602 will fix this.

Regards
