### ISSUE TITLE
"Items Seen not contains XYZ" should not behave like "contains"

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#9604]
**Describe the bug**

When you use the "Items Seen" search (in Computers, for example), and select the "not contains" XYZ, it matches all objetcs that have at least one field not containing XYZ. Which means it usualy match all objects, as there is always a field not containing some string.

**Expected behavior**

Only objects having not a single field containing X should match.

**Your GLPI setup (you can find it in Setup > General menu, System tab)**

```
GLPI 9.5.5
Installation mode: TARBALL
```

**Comment by mathieumd** [comment]
Still same problem with GLPI 9.5.6.

**Comment by mathieumd** [comment]
ping

**Comment by cconard96** [comment]
The behavior of this search does seem odd, but it is possible to get the results you were looking for by using "NOT Items Seen contains XYZ".

**Comment by mathieumd** [comment]
Thanks, it does work as expected, indeed.

I still believe the code should be fixed/amended, because it's not intuitive for end users.
