### ISSUE TITLE
Permits documents 090.1 (self-service)

### ISSUE THREAD

**Issue by virginiacorrea** [glpi-project/glpi#963]
Question.

A user "x " with self-service profile creates a ticket with an observer and similarly sends an approval.

It happens that neither the observer nor the approver can download or open the document to validate or observe .

I utilizao version is 0.90.1 and 0.83 before had had no objection .

Anyone have any guidance which may be the problem.

Thanks in advance.

**Comment by trasher** [comment]
Hello,

I'm not sure to understand correctly... Are you using 0.90.1? If so, you should try to upgrade to the latest rekease and see if this issue has been fixed.

**Comment by virginiacorrea** [comment]
Thanks
