### ISSUE TITLE
Warnings in update 9.4.3 to 9.5.6

### ISSUE THREAD

**Issue by phamorais** [glpi-project/glpi#9659]
Hey guys!
When updating GLPI in an environment via the console, I got these warnings

![image](https://user-images.githubusercontent.com/35368369/135946535-a2a1ac63-7923-409b-beb7-eadea1ec3770.png)

Despite the Warnings, the update took place correctly. Do we need to worry in the future?

Log in php-errors (not relevant) I will not active fusion

![image](https://user-images.githubusercontent.com/35368369/135946795-09d43438-d08f-4d3a-ab1c-56361134cee1.png)

Log in sql-errors

![image](https://user-images.githubusercontent.com/35368369/135946825-605e4a54-088a-4320-b450-5dd5c9ed856d.png)

**Comment by trasher** [comment]
Locales dir missing is fixed in #9586
