### ISSUE TITLE
imap_fetchstructure(): No body infromation avaliable

### ISSUE THREAD

**Issue by sudhakarang** [glpi-project/glpi#966]
Dear team,
                  I recently upgraded my Glpi version to 0.90.5 ,after upgrading I am facing issue in mailcollector , I have configured imap in receiver .When receiving tickets from mail body is not attached to description in mail .I have tried all possible work outs ,but no hope .Please can you check whether its a imap related bug.
![capture](https://cloud.githubusercontent.com/assets/22138949/18422306/82330d0c-78cb-11e6-9423-0804d0506d39.JPG)

**Comment by wawax** [comment]
Hello,

What is your mail server ?

**Comment by sudhakarang** [comment]
Dear Walid,
                       Thanks for response ,My mail server is Zimbra ver 7.


Thanks & Regards,
Sudhakaran Ganesan

**Comment by orthagh** [comment]
Here, we are using glpi collector on a zimbra 8 without issues.
Is the version update the only thing you changed ?

Also could you provide the php version you are using ?

**Comment by sudhakarang** [comment]
Dear Alex,
                 yes only version update from 0.85 to 0.90.5
PHP version :
PHP Version 5.5.9

Thanks & Regards,
Sudhakaran Ganesan

**Comment by sudhakarang** [comment]
Dear All,
                  Anyone come across this issue ,I have been facing this when I upgraded my Glpi from 0.85 to 0.90.5 ,Now I have upgraded to  9.1.1 still the problem persists .

2016-12-16 09:49:18 [6@kits]
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  inc/mailcollector.class.php:1420                   
  inc/mailcollector.class.php:1513                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:673                    MailCollector->getAttached()
  inc/mailcollector.class.php:508                    MailCollector->buildTicket()
  front/mailcollector.form.php:80                    MailCollector->collect()
2016-12-16 09:49:18 [6@kits]
  *** PHP Notice(8): Trying to get property of non-object
  Backtrace :
  inc/mailcollector.class.php:1425                   
  inc/mailcollector.class.php:1513                   MailCollector->getRecursiveAttached()
  inc/mailcollector.class.php:673                    MailCollector->getAttached()
  inc/mailcollector.class.php:508                    MailCollector->buildTicket()
  front/mailcollector.form.php:80                    MailCollector->collect()
2016-12-16 09:49:18 [6@kits]
  *** PHP Warning(2): imap_fetchstructure(): No body information available
  Backtrace :
  :                                                  
  inc/mailcollector.class.php:1109                   imap_fetchstructure()
  inc/mailcollector.class.php:1526                   MailCollector->getStructure()
  inc/mailcollector.class.php:715                    MailCollector->getBody()
  inc/mailcollector.class.php:508                    MailCollector->buildTicket()
  front/mailcollector.form.php:80                    MailCollector->collect()
2016-12-16 09:49:18 [6@kits]
  *** PHP Warning(2): imap_fetchheader(): Bad message number
  Backtrace :
  :                                                  
  plugins/mailanalyzer/hook.php:63                   imap_fetchheader()
  plugins/mailanalyzer/hook.php:114                  PluginMailAnalyzer::getAdditionnalHeaders()
  plugins/mailanalyzer/hook.php:281                  PluginMailAnalyzer::getHeaderAndMsgNum()
  :                                                  PluginMailAnalyzer::plugin_pre_item_add_mailanalyzer()
  inc/plugin.class.php:1125                          call_user_func()
  inc/commondbtm.class.php:806                       Plugin::doHook()
  inc/mailcollector.class.php:564                    CommonDBTM->add()
  front/mailcollector.form.php:80                    MailCollector->collect()

**Comment by sudhakarang** [comment]
Dear all,
                   Thsi issue is fixed ,thr problem was in my p3scan in zimbra.Thanks for support.
