### ISSUE TITLE
Expected date for plugin compatibility with 0.91 ?

### ISSUE THREAD

**Issue by geekson** [glpi-project/glpi#967]
Hello,

The new version seems great but none of the plugin are compatible with it. Do you depend on other partner? When can we expect to have it ready?

Regards,
David

**Comment by ddurieux** [comment]
Each plugin has own team / timeline, so see with each of them

**Comment by tomolimo** [comment]
Hello,

> The new version seems great but none of the plugin are compatible with it. Do you depend on other partner? When can we expect to have it ready?

As a matter of fact this is not true, see: http://plugins.glpi-project.org/#/version/9.1/plugins
regards,
Tomolimo

**Comment by geekson** [comment]
OK thanks for your answer.

**Comment by trasher** [comment]
Question has been answered, closing :)

**Comment by orthagh** [comment]
We have now 21 plugins compatible with the future 9.1 release. Thanks to @trasher.
