### ISSUE TITLE
Improve information message box

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#969]
When using Session::addMessageafterRedirect(); we can set 2 types actually: INFO or ERROR; but the window title always display "Information"; that is quite wrong while displaying an error.
I guess a different box display (say a "red" box, not a "blue" one) should be more visible for the users.

Maybe we can also think to add a "warning" level, that would be used to inform user for things that did not work as expected, but that are not blockers (just an idea, I've used this in some other projects already).

**Comment by tomolimo** [comment]
ok for me, good idea

**Comment by ddurieux** [comment]
Yes _info_, _warning_, _error_ seems good idea with colors _green_, _orange_, _red_ (background color)

**Comment by trasher** [comment]
Yup, that was colors I had in mind ;)

**Comment by ddurieux** [comment]
Yes, but it's better to specify all here to share with all ;)

**Comment by trasher** [comment]
Ok, I've worked on this, here are the actual output. Here is what it looks like:
![err_msg](https://cloud.githubusercontent.com/assets/224733/18546860/9c844230-7b40-11e6-8089-4ea705f7e1e7.png)
![warn_msg](https://cloud.githubusercontent.com/assets/224733/18546861/9c86dd1a-7b40-11e6-8fd6-4583d1d5e7a9.png)
![info_msg](https://cloud.githubusercontent.com/assets/224733/18546859/9c802fce-7b40-11e6-8b85-b0582e80e036.png)

Note that I've kept info messages in blue, since there is no green in the glpi interface.
Well, at least, it is only 2 or 3 lines of css to change if everyone wants some green ;)

**Comment by ddurieux** [comment]
nice, but to be more readeable, can you set background color more lighter to have the text more readable (I say about the text part  _This is an..._)

**Comment by trasher** [comment]
Yes, you are right, will do :)

**Comment by trasher** [comment]
Here it is:
![capture d ecran de 2016-09-15 13-31-57](https://cloud.githubusercontent.com/assets/224733/18548436/eec8b6e0-7b48-11e6-82da-3f63a4eef878.png)

Ttiles are white, exept for warnings because it is not readable.

I've done most of the job; but I stil have an issue to resolve (and I do not yet know how...): when opening at once two types of messages, the dialogs are at the same position, the last displayed hide others... :/

**Comment by ddurieux** [comment]
nice, for the color of title, it's not same so I'm not like it :/
Can you make screenshot with warning title in white?

**Comment by trasher** [comment]
Sure:
![capture d ecran de 2016-09-15 13-44-04](https://cloud.githubusercontent.com/assets/224733/18548727/94854e62-7b4a-11e6-8932-412abee25370.png)

**Comment by ddurieux** [comment]
I prefer all titles in white, and if somebody has problem to read the title, it can see ore quickly it's a warning with the color (yes, we see the color before read the title :p)

**Comment by trasher** [comment]
ok then ;)

**Comment by orthagh** [comment]
In fact, i merged a little too soon.

If you change your current "palette", the message with info type dosn't follow the palette.
I think you should not change the color, or use a more neutral color (silver ?)

**Comment by trasher** [comment]
Hum... Why would the info box change its color and not the error/warnings ones? Anyways, we should change (and get back to another color for the title).

BTW, I guess you did not see I had a javascript issue for now (well, only when opening multiple message types at once, but an issue anyways). I do not yet find a way to fix it :/
