### ISSUE TITLE
Something wrong with ticket rules

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#9698]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

After migration from GLPI 9.4.6 to 9.5.6, some strange behaviours appeared during tickets rules execution.

Let's imagine that there is a rule looking for a given text pattern in ticket subject (ex: [gf-test]). This rule assigns on ticket modification the ticket to a given group (let's say group-test).
In the rule list there is another rule that based on "assigned to group = group-test", assigns the ticket to a technician (me).

So let's open a new ticket where I'm the requester (from the web interface I become also assigned technician). There is another rule that assigns the ticket to my "tech-admin-team" group. This is also ok. 

Now, if I put  [gf-test] in the ticket subject and validate, My name appears twice in the "assigned to" list, but not group-test as assigned group. Tracing related glpi code, I can see that group assignment is executed and after that, reverse "assignment group -> technician (me)" also. So something happens after that.

There is no trace for the group assignement in the ticket history, and 2 assignments for technician are present. By the way, the order displayed is not correct (for instance subject modification log after second technician assignment) .

This is probably somehow related to issue #9411, where the same tracing showed that the rule processing order was correct  internally (for ticket creation), but final result not. Like if there was a parallel rules executions.  Not sure if it is related, but there are 2 notification mails at ticket creation, one for new ticket and another one for technician assignment changes. "Normally" ticket creation ticket should appear after the one for assignment, because that means that rules are applied immediately on ticket creation and not on a second turn.

PS: As there is nobody on #glpi chan on freenode, please let me know if there is another one elsewhere...

### Steps To reproduce

It is easy to reproduce the first one ("disappearing assigned to group"):

1. Create a group "tech-admin-team" 
2. Create a group "group-test" with a technician (called technician1) in it
3. Create a rule matching [gf-test] in subject  assigning ticket to group "group-test"  on ticket modification
4. Create a rule matching group "group-test" that assigns ticket to "technician1" (yes assigned and requester are the same)
5. Create a rule assigning  ticket on ticket creation/update "assigned to" group "tech-admin-team" if requester is "technician1" 
6. From the web interface, "technician1" creates a ticket with subject "Test ticket". It is assigned to him and to "tech-admin-team" (by default for technician and by rule 5 for group).
7. Now, change subject to "[gf-test] Test ticket". Technician name appears twice (so rule 4 is executed, even if technician should not appear twice, and rule 3 is executed, because it triggers rule 4). No trace of group assignment in the ticket. See attached files.

![2assignedtohistory](https://user-images.githubusercontent.com/10462658/136943507-b660ef57-421c-4389-bc3b-14f70cbbe6f4.png)
![2assignedto2](https://user-images.githubusercontent.com/10462658/136943538-82426906-f644-4e47-9f83-9412bc9daede.png)

Reproducing the second bahaviour is a little bit more difficult. It depends even on some debug Toolbox::logError lines I added in the code. But let's try (with the same groups and users). So:

1. Create a ticket category Cat1 
2. Create a group "tech-admin-team" 
3. Create a group "group-test" with a technician (called technician1) in it
4. Create a rule matching [gf-test] in subject  assigning ticket to group "group-test" and ticket  category to Cat1 on ticket creation
5. Create a rule matching group "group-test" that assigns ticket to "technician1" (yes assigned and requester are the same)
6. Create a rule assigning  ticket on ticket creation/update "assigned to" group "tech-admin-team" if requester is "technician1" and IF TICKET CATEGORY IS NOT Cat1
7. From an e-mail collector inject: an email containing [gf-test] in the subject. Group "tech-admin-team" is present in the ticket (so Cat1 was not set when rule 6 started...). Order in history is strange.

![wrongassignment1](https://user-images.githubusercontent.com/10462658/136948533-1186f28c-f81e-4137-b489-7f7bad132d60.png)
![wrongassignment2](https://user-images.githubusercontent.com/10462658/136948833-d1d91c89-5b32-402f-a6a6-66e88e99fa28.png)

**Comment by kabassanov** [comment]
Still present...

**Comment by cconard96** [comment]
Can you share the order the ticket rules are in for you? That should determine their priority/order they run in and will be needed to recreate the issue.

**Comment by kabassanov** [comment]
Hi, I propose to close this issue and to move ahead in the issues this one was split into... It is easier to understand them. Sorry to have reopened this one.
