### ISSUE TITLE
new parameter in my setting: selct me a requester

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#97]
http://forum.glpi-project.org/viewtopic.php?id=119456

Your opinion?

**Comment by ddurieux** [comment]
I have written a patch for a client for that some weeks ago, I can make a PR...

I think it can be a good idea in some cases (so depends on client use tool, but most time when technicians create a ticket with 'technician' profile)

**Comment by wawax** [comment]
I totally agree with this feature request

**Comment by orthagh** [comment]
Seems good to have a personnal settings, so I'm OK with this feature also

**Comment by ladenree76000** [comment]
Personnal setting would be great. 
for self -service profile this feature is usefull
 hotliner  profile,should create tickets with no self requester feature !

Ok for personnal settings, or profile settings

**Comment by yllen** [comment]
It's OK for 0.91
