### ISSUE TITLE
No pictures of users

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#970]
Hello

I have started  master test and I have no pictures of users (timeline in tickets) or user administration

Ldap authentification method and server selected is lost after migration.

If I add manually the server and force syncronisation it works, but it is long for 250 users ...

I have done it massively and it works.

It would be great to fix it for migration

**Comment by orthagh** [comment]
Hello @satyan01 

for migration, it's very weird you lost ldap link for your users. I'll test a migration to check your issue.
For fix your instance, you could do it through massive action, use "change the authentication method" option : 

![image](https://cloud.githubusercontent.com/assets/418844/18587578/0b57378e-7c23-11e6-98e9-5b13cf829f80.png)


After that, you could use another option: 
![image](https://cloud.githubusercontent.com/assets/418844/18587602/27aaa2e0-7c23-11e6-9265-95b4f044a1ae.png)

**Comment by satyan01** [comment]
Done, thx for the solution
