### ISSUE TITLE
Timeout when no Internet access from server (HTTP return code 499)

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#9728]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

On a GLPI installed on a server without access to Internet, access to some pages timeout with this red message:

> Une erreur est survenue au chargement des contenus !
> 
> Vérifiez les logs de GLPI ou contactez votre administrateur.
> ou essayez de recharger

On another GLPI, installed on a server *with* Internet access, there is not such problem.

### Relevant log output

Not sure if it's really related (because I have the same 499 HTTP code on the server with Internet access), but when I access *Configuration > General > System* I have a 499 error in `/var/log/nginx/glpi-test.example.com_access.log`:

```shell
::ffff:192.168.x.y - - [19/Oct/2021:16:05:58 +0200] "GET /front/locale.php?domain=glpi&version=9.5.6 HTTP/2.0" 499 0 "https://glpi-test.example.com/front/config.form.php" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"                                                                                                                        
::ffff:192.168.x.y - - [19/Oct/2021:16:05:58 +0200] "GET /front/locale.php?domain=fusioninventory&version=9.5+3.0 HTTP/2.0" 499 0 "https://glpi-test.example.com/front/config.form.php" "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0"
```

### Page URL

Configuration > General > System https://glpi-test.example.com/ajax/common.tabs.php?_target=/front/config.form.php&_itemtype=Config&_glpi_tab=Config$5&id=1&formoptions=data-track-changes%3Dtrue

### Your GLPI setup information

Well, that's the problem: I cannot load the System tab page.

It's a GLPI 9.5.6 freshly upgraded from 9.5.5, on Ubuntu 20.04.3 LTS. It cannot access to Internet:

```bash
curl -LI glpi-project.org
curl: (28) Failed to connect to glpi-project.org port 80: Connection timed out
```

**Comment by cedric-anne** [comment]
Hi,

499 error code generally means that your request was aborted by your browser (see https://httpstatuses.com/499).

You should check GLPI logs, i.e logs located in `glpi/files/_logs`.

Regards
