### ISSUE TITLE
no content in computer

### ISSUE THREAD

**Issue by satyan01** [glpi-project/glpi#973]
no content in computer

![image](https://cloud.githubusercontent.com/assets/15144026/18478884/32b8de74-79d3-11e6-9a07-e8ed18803d71.png)

**Comment by ddurieux** [comment]
You have error in webserver logs?

**Comment by satyan01** [comment]
The same for sla

![image](https://cloud.githubusercontent.com/assets/15144026/18479218/7e62c370-79d4-11e6-99bc-17627dc31d22.png)


2016-09-13 14:24:05 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: highcontrast_css
  Backtrace :
  inc\toolbox.class.php:592                          
  inc\user.class.php:165                             Toolbox::userErrorHandlerDebug()
  inc\session.class.php:125                          User->computePreferences()
  inc\auth.class.php:813                             Session::init()
  front\login.php:78                                 Auth->Login()
Test
2016-09-13 14:25:04 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: url_base_api
  Backtrace :
  inc\config.class.php:705                           
  inc\config.class.php:2075                          Config->showFormAPI()
  inc\commonglpi.class.php:477                       Config::displayTabContentForItem()
  ajax\common.tabs.php:97                            CommonGLPI::displayStandardTab()

2016-09-13 14:24:05 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: highcontrast_css
  Backtrace :
  inc\toolbox.class.php:592                          
  inc\user.class.php:165                             Toolbox::userErrorHandlerDebug()
  inc\session.class.php:125                          User->computePreferences()
  inc\auth.class.php:813                             Session::init()
  front\login.php:78                                 Auth->Login()
Test
2016-09-13 14:25:04 [854@UNGSRVGVA118]
  *** PHP Notice(8): Undefined index: url_base_api
  Backtrace :
  inc\config.class.php:705                           
  inc\config.class.php:2075                          Config->showFormAPI()
  inc\commonglpi.class.php:477                       Config::displayTabContentForItem()
  ajax\common.tabs.php:97                            CommonGLPI::displayStandardTab()

**Comment by satyan01** [comment]
2016-09-13 14:25:04 [854@UNGSRVGVA118]
  *** MySQL query error:
  SQL: SHOW COLUMNS FROM `glpi_apiclients`
  Error: Table 'glpidb91.glpi_apiclients' doesn't exist
  Backtrace :
  inc\dbmysql.class.php:402                          
  inc\commondbtm.class.php:288                       DBmysql->list_fields()
  inc\commondbtm.class.php:2686                      CommonDBTM->getEmpty()
  ajax\searchrow.php:100                             CommonDBTM->maybeDeleted()
  inc\search.class.php:1873                          include()
  inc\search.class.php:79                            Search::showGenericSearch()
  inc\config.class.php:756                           Search::show()
  inc\config.class.php:2075                          Config->showFormAPI()
  inc\commonglpi.class.php:477                       Config::displayTabContentForItem()
  ajax\common.tabs.php:97                            CommonGLPI::displayStandardTab()

**Comment by orthagh** [comment]
Hello @satyan01 

As previously said, you shouldn't use 9.1 in production for the moment.
We don't have any migration scripts from between different versions of the current master.

Anyway, search in your glpi_configs table the line with name=version (surely the first line), set the value to 0.90.5 and redo the migration. So, the migration script will create missing fields and table.

**Comment by satyan01** [comment]
Thank you, I have noted that for the next migration.
