### ISSUE TITLE
"Computer import (by serial + uuid)" rule should be triggered before "by serial" or "by uuid" update rules

### ISSUE THREAD

**Issue by g-bougard** [glpi-project/glpi#9741]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

master

### Bug description

When a computer asset A has a serial and and uuid, it should match the first time the "Computer import (by serial + uuid)" rule, than later it will match the "Computer update (by serial + uuid)".

Another computer asset B may share the same serial but with another uuid (this may be the case for example with docker images as an agent will see the host serial but another uuid). Then the computer asset B will first trigger the "Computer update (by serial)" rule as the serial is still known and the asset A will be updated by the asset B data: uuid will even be replaced.

I guess another computer asset C sharing the same uuid but with a different serial will match the "Computer update (by uuid)" rule. This case should probably not happen as I can't see own 2 devices with a different serial can share the same uuid, unless with a forged inventory.

Expected behavior:
The "Computer import (by serial + uuid)" rule is triggered before any of the "Computer update (by uuid)" and "Computer update (by serial)" rules but still after "Computer update (by serial + uuid)".

**Comment by g-bougard** [comment]
No `github-actions`, please don't close this issue !!! :-p

**Comment by cconard96** [comment]
Would #10820 help avoid this issue?
