### ISSUE TITLE
GLPI image on logon page internet explorer 11

### ISSUE THREAD

**Issue by Armin83** [glpi-project/glpi#975]
Since a few versions there is no glpi image on logon page with internet explorer 11.

**Comment by orthagh** [comment]
Hello @Armin83 

On my side, it seems here (both 0.90 and 9.1): 
![image](https://cloud.githubusercontent.com/assets/418844/18503277/4e5cac3a-7a5c-11e6-82b0-957c41f2e6b8.png)


Could you post your screen resolution ? 
if you have a different theme ?

**Comment by tomolimo** [comment]
Same thing for me on IE10 and GLPi 0.90.5:

![image](https://cloud.githubusercontent.com/assets/7569958/18503435/3ec0d692-7a5d-11e6-8d96-8b7adb390f49.png)

**Comment by tomolimo** [comment]
Could it be a problem of using the 'compatibility mode'?
Could check this with F12 (developper mode)?
![image](https://cloud.githubusercontent.com/assets/7569958/18503506/78ef0546-7a5d-11e6-8811-b99801c2a71e.png)

**Comment by Armin83** [comment]
Ok - omg. I will solve many other problems with this knowledge.
We have mode 7. So i think it is internet explorer 7.... mode instead IE 11 / edge mode on windows 8.1
![img_006](https://cloud.githubusercontent.com/assets/19192087/18510604/347f1a5a-7a7f-11e6-9e69-dcd96f8d8d77.jpg)

We can close this case. Do you know the setting where i change this forever and all ?

**Comment by tomolimo** [comment]
You should be able to change it in the 'Compatibility list' that you should be able to manage in 'Compatibility view settings':
Screen copy for IE10 (almost the same for IE11):
![image](https://cloud.githubusercontent.com/assets/7569958/18510845/978e41e2-7a80-11e6-9f2a-73aecb71568c.png)
But for Edge, this mode is not existing, as Edge has been built from scratch without the dirty things from IE.

**Comment by Armin83** [comment]
thanks so much.
It is strange ;) on microsoft "edge mode" is on windows 8.1 where no edge is... (edge comes with 10) but on windows 8.1 ie 11 there is no 11 mode so i think edge is the 11 mode from windows 8.1

**Comment by tomolimo** [comment]
'Edge mode' is NOT 'Edge' browser
'Edge mode' can be specified in HTML pages to tell the browser that it can switch to the higher available mode.
'Edge' browser is a browser :smiley:. And there is no mode in 'Edge'

**Comment by Armin83** [comment]
okay not easy :) 
thanks so it works :+1:

**Comment by tomolimo** [comment]
Yes, I know I spent many hours in reading docs :(
'Edge' browser has not been named the right way as there is possible confusion between two different notions
