### ISSUE TITLE
From array to simple value for _users_id_assign in output array

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#9764]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.6

### Bug description

Another split of #9698...

So back to the first issue of the mentionned case, I'm partially  responsible for the situation:

My rules "assign" (not "append") groups of technicians. So as "tech-admin-team" rule is after "group-test" in the rules list, it is executes once again after the "group-test" rule (and the "group-test" to technician1 rule) and overrides it. Probably this is the right behavior, something that has been cleaned between 9.4.6 and 9.5.6.

But having the same technician1 assigned twice is still strange. It seems that in the executeActions function in /usr/share/glpi/inc/ruleticket.class.php, the output entry is transformed from array to simple value:

>     [_users_id_assign] => Array
>         (
>             [0] => 7753
>         )
>
---
>     [_users_id_assign] => 7753

Is it possible that there is some inconsistency in the calling function (sending an array) that prevents detecting that the user is already assigned?

**Comment by kabassanov** [comment]
I didn't see any correction for this? Did I miss anything?

**Comment by cconard96** [comment]
Having Assign override existing actors seems correct.
Deduplication of actors has been fixed in #10826.
