### ISSUE TITLE
[DomainsAlert] Expiring domains not found by automatic action/crontask

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#9772]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

As explained (in French) here: https://forum.glpi-project.org/viewtopic.php?id=281837

A domain (example.com) expiring tomorrow is not found by DomainsAlert crontask.

Root Entity is configured with notifications 60 days before expiration.

A direct SQL query with the configured delay does find the expiring domains:

```
MariaDB [glpi]> select id,name,date_expiration from glpi_domains where date_expiration is not null and is_deleted = 0 and datediff(curdate(), date_expiration) > -60;                                          
+----+---------------------+---------------------+
| id | name                | date_expiration     |
+----+---------------------+---------------------+
|  1 | xxx.fr              | 2021-11-28 00:00:00 |
|  4 | example.com         | 2021-10-27 00:00:00 |
|  5 | yyy.fr              | 2021-11-06 00:00:00 |
| 15 | zzz.fr              | 2021-10-24 00:00:00 |
+----+---------------------+---------------------+
4 rows in set (0.005 sec)
```

**Comment by mathieumd** [comment]
ping

**Comment by cedric-anne** [comment]
Hi,

Default recipients for Domain/Certificate alerts are not working, see #10497.

You should try to use another type of recipient, and see if you receive notifications. Also, as please provide related GLPI logs, if any, and information related to your GLPI system, as requested in issue form.

Regards

**Comment by cedric-anne** [comment]
I close this issue due to lack of feedback. Feel free to reopen.

**Comment by abhishek-rajput-44** [comment]
I have installed latest glpi 10.0.3.

A domain (example.com) expiring prior to 30 days is found by DomainsAlert crontask only one time and an email is get queued in notification queue. after that even if i manually execute DomainsAlert automatic action, email is not queuing in the notification queue menu under Administration.

Root Entity is configured with notifications 30 days before expiration.

I want whenever cron will run or execute it manually, the respective email should be queued for domain alert action.
