### ISSUE TITLE
Dozens of sql errors at profile creation

### ISSUE THREAD

**Issue by blerohellec** [glpi-project/glpi#98]
0.85 & 0.90
Create a profile, from scratch (not a clone). The profile is created, I get 70 records in table glpi_profilerights, all with rights = 0.
BUT, I also get 70 SQL errors, all of the same type
  *** MySQL query error:
  SQL: INSERT
                   INTO `glpi_profilerights` (`profiles_id`,`name`,`rights`) VALUES (\'10\',\'user\',\'\')
  Error: Incorrect integer value: '' for column 'rights' at row 1
  Backtrace :
  inc/commondbtm.class.php:425                       
  inc/commondbtm.class.php:824                       CommonDBTM->addToDB()
  inc/profileright.class.php:254                     CommonDBTM->add()
  inc/profile.class.php:189                          ProfileRight->updateProfileRights()
  inc/commondbtm.class.php:825                       Profile->post_addItem()
  front/profile.form.php:50                          CommonDBTM->add()

**Comment by blerohellec** [comment]
OK. Thx

**Comment by blerohellec** [comment]
This error came back.

**Comment by yllen** [comment]
in which version ?

**Comment by blerohellec** [comment]
0.85 & 0.90

**Comment by yllen** [comment]
I confirm

**Comment by blerohellec** [comment]
Corrected. Thx
