### ISSUE TITLE
[9.5.6] Visibility of tickets in status New: all technicians can see those tickets vene if they are not actors

### ISSUE THREAD

**Issue by Giudy** [glpi-project/glpi#9825]
### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.6

### Bug description

Hello, 
     if a ticket is in status NEW, everybody has a standard interface profile, with no permissions on SEE ALL TICKETS but with permission on SEE ASSIGNED (see img)
![immagine](https://user-images.githubusercontent.com/7987648/139908001-a8a7a3b8-f4c7-4a3f-967b-01348508bb9d.png)

can see all tickets in status NEW whenever or not the user is among the actors of the ticket.
It seems that the issue is in the "SEE ASSIGNED" permissions: as soon as it is set to False in the profile, the user is not able to see any more those tickets.

The issue is present also in 9.5.5 and I've tested over several different installations

**Comment by kabassanov** [comment]
Hi, it is probably an expected behaviour. In order to allow techs to pick up new tickets? At least it was already present in 9.4...

**Comment by Giudy** [comment]
Ups, Never noticed. if it is so I guess it should be a column in the profile/Assistence to enable a profile to see "new and not assigned tickets".
Is there someone that could confirm that this is a feature ?

thanx

**Comment by WebGregGit** [comment]
I agree. The specificity of the work may require that a profile does not have access to new requests, but only to those already assigned.

**Comment by kabassanov** [comment]
I agree also.

**Comment by Giudy** [comment]
I've added the request of the feature on userecho
[https://glpi.userecho.com/en/communities/1/topics/2034-profile-new-column-for-standard-assistance-new-tickets](https://glpi.userecho.com/en/communities/1/topics/2034-profile-new-column-for-standard-assistance-new-tickets)

**Comment by kabassanov** [comment]
Could this be tagged as feature request, please? Thanks.

**Comment by cedric-anne** [comment]
Hi,

We do not track anymore feature request here, unless to discuss about its implementation when someone wants to implement it.

Regards
