### ISSUE TITLE
Add possibility to remove bookmark of an user 

### ISSUE THREAD

**Issue by PierreTeclib** [glpi-project/glpi#983]
Hello,

It will be fine in the configuration menu to add possibility to remove boomark(s) of an user.

Thks

**Comment by ddurieux** [comment]
What's the goal ?

**Comment by tomolimo** [comment]
Please post new feature or suggestion on http://glpi.userecho.com/

**Comment by wawax** [comment]
The goal is for an administrator to remove a faulty bookmark for a user.
For example a bookmark is set by default for a user's computer view, and it's query is too big and make mysql use temporary table.
As the admin have access to the slow queries log, it sees which user cause the query, and delete the bookmark to prevent further problem.

This is only one example.

**Comment by tsmr** [comment]
👍

**Comment by trasher** [comment]
Done for 9.2 :)
