### ISSUE TITLE
[9.5.5] Missing rejected solution in the follow-up of the ticket by mail

### ISSUE THREAD

**Issue by TheDevilDan** [glpi-project/glpi#9849]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.5

### Bug description

Hello,

According to my research, it seems that this had been corrected in previous versions of GLPI (which does not seem to be the case anymore).
However, when I solve a ticket, then someone reopens it (by e-mail or by the web interface) **I don't see the refused solution in the e-mail follow-up.**

I can't understand the follow-up of the ticket, so it gives in the follow-up by e-mail :

--> Description of the ticket
--> Solution
** --> /!\ Rejected solution which does not appear /!\ /!\ /!\ /!\ /!\ /!\ **
--> Follow-up
--> Follow-up
** --> /!\ Rejected solution which does not appear /!\ /!\ /!\ /!\ /!\ /!\ **
--> Follow-up
--> Follow-up

I specify that concerning the mail part, I use the excellent plug-in GLPI MailAnalyzer of Tomolimo which recently corrected its plug-in so that when a user sends an e-mail with GLPI in copy and that the ticket is in solved status, that behaves like in GLPI natively i.e. that the ticket is reopened (thus not of new generated ticket)

Is it possible to have a **complete follow-up by email** please including all the follow-ups and the refused solutions?

Thank you in advance.

### Steps To reproduce

1 create ticket
2 solve ticket
3 re-open ticket
4 solve ticket
Follow-up missing history solved followup

**Comment by TheDevilDan** [comment]
I am surprised that no one can provide me with at least one information answer indicating whether this behaviour is normal for a tool that calls itself ITIL?

Are you sure that this behaviour is normal? I'm not sure if this is normal for a tool that claims to be ITIL? Are you sure that this behaviour is normal?

**Comment by cedric-anne** [comment]
Hi,

As far as I understand from the code, on 9.5 branch, only the latest solution is available in notification templates.

On master branch, a new `timelineitems` array will be available and will contains tasks, followups and solutions, so it will be easier to display them in a chronological order (see #9456).

I close this issue as this is already fixed. We will not backport this in 9.5 branch.

Regards

**Comment by TheDevilDan** [comment]
Hello,
Thanks for your feedback, how do I access this new feature? On which version of GLPI? Knowing that to my knowledge the last one is 9.5.6, does that mean that it is available in 9.5.6?

**Comment by cedric-anne** [comment]
> Hello, Thanks for your feedback, how do I access this new feature? On which version of GLPI? Knowing that to my knowledge the last one is 9.5.6, does that mean that it is available in 9.5.6?

It will be included in GLPI 10.0. Release schedule is not defined yet.
