### ISSUE TITLE
Redundant data in $_SESSION and $CFG_GLPI

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#986]
Hi

The method CommonDBTM::getTable() stores in **$_SESSION['glpi_table_of']** a map to find a table in DB for each itemtype. I guess this has been designed to improve performance.

It duplicates a similar mapping maintained in **$CFG_GLPI['glpitablesitemtype']**, but does not duplicate **$CFG_GLPI['glpiitemtypetables']** (see the functions **getItemTypeForTable()** and **getTableForItemType()** in db.function.php)

The overall design shows the mapping in $_SESSION is filled from $_CFG_GLPI mapping. 

Would be better to maintain the two mapping directions only in $_SESSION or $CFG_GLPI instead of both ?

**Comment by trasher** [comment]
Hello,

As far as I can see, data are not really duplicated here. 

On `central.php` page, looking at `$_SESSION['glpi_table_of']`, this is an array of 69 entries, while `$CFG_GLPI['glpitablesitemtype']` contains only two (from fusioninventory plugin), that are not present in the former.

Is this behavior relative to the usage of the different possibilities? Maybe, it's a bit unclear to me right now.

**Comment by btry** [comment]
Hi

To me this is normal because the data in $_SESSION persist accross requests whereas data in CFG_GLPI are reset between requests. 

That's why I think the usage of $_SESSION is for performance purpose.

If you look into CommonDBTM::getTable() you'll see it calls getTableForItemType() if $_SESSION does not already contains the needed map entry.

**Comment by trasher** [comment]
That is what I first think; but the two entries I can see on my CFG array never reach SESSION apparently.

That is why I suspect there is unconsistency accross calls; I'm affraid that removing CFG array would cause the plugin to fail :/
But I agree that if the session stuff has been added for perfs; it should always been used (seems that is not actually :'().

**Comment by btry** [comment]
If the map in $_SESSION is populated from  the content of $CFG_GLPI, I think there is nothing to populate in the opposite way. At least I didn't find such code.

When there is a need to get a table name of an itemtype, I usually fond a call to Itemtype::getTable()
which searches in $_SESSION. If $_SESSIONS does not contains the map entry, then there is a search in $CFG_GLPI, and at last resort, the table name is computed and added in $CFGL_GLPI and next in $_SESSION.

As $_SESSION persists across requests but not $CFG_GLPI, then the map in $_SESSION  is always a superset of the map in $CFG_GLPI . 

To make this assertion false, $CFG_GLPI needs to be populated by calls to getTableForItemType() elsewhere than CommonDBTM::getTable() or by a direct affectation.

In GLPi's scope this should be rather easy to check (I guess). Checking all plugins is less obvious. However I didn't saw any plugin accessing directly these maps, and I'm personnaly used to overload the method getTable() for some very specific cases (which should avoided as much as possible).

**Comment by cedric-anne** [comment]
Hi,

Using of `$_SESSION['glpi_table_of']`/`$GLPI_CACHE->get('table_of')` for caching has been dropped in master branch. I guess this solve this issue.

Regards
