### ISSUE TITLE
Mailgate debug

### ISSUE THREAD

**Issue by hartois** [glpi-project/glpi#987]
GLPI Version: 9.1

I have a nasty problem with mailgate.
Periodicaly (once or twice a day) it freezy after connection to imap server.
It can remain in this state for a long time. To check, I waited for 10 hours.

With netstat I see tcp connection in ESTABLISHED state.
With tcpdump I see periodicaly packets in this tcp session, but connection crypted by SSL and I cannot see packets content.
Nothing in php-errors.log or mail.log at this time.

In mailgate configuration I added option "debug", but I cannot see debug information in logs.

I have to keep an eye on the state of the job and if it is stuck - to kill the process and change the status of the mailgate job.

What can I do to track down the cause of the problem?

**Comment by orthagh** [comment]
Hello @hartois 

You are facing a complex issue, here is some minor advices:
- you can add Toolbox::logDebug functions in the code to track variables in the code (it will output in files/_log/php_errror.log)
- install/use xdebug extension for php to breakpoint on the mailgate process
- it's not a solution, but we have a script to stop and reset long crontasks : https://github.com/glpi-project/glpi/blob/master/scripts/unlock_tasks.php (it takes a cycle parameter to stop running tasks with exceeded cycle * task's frequency)

Let us know if you find some clues/solution to this problem

**Comment by hartois** [comment]
Thanks, I will try to determine at what point the work of the mailgate freezes.

About unlock_tasks script. It only clean lock without killing process?

**Comment by orthagh** [comment]
yes

**Comment by hartois** [comment]
Hmm...
I'm add two syslog() calls in mailcollector.class.php:
before and immediately after imap_open on row 1072

On some next launch I see in log only first syslog message.
This means that the code hangs during a call imap_open().

**Comment by cedric-anne** [comment]
Hi,

Do you still have this issue ?

Regards

**Comment by trasher** [comment]
No feedback from a while, closing.
