### ISSUE TITLE
[Note sure if Bug or suggestion] Improve Ticketassignment

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [glpi-project/glpi#9883]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Version

9.5.6

### Bug description

Currently It's to complicated to assign a Ticket directly to an agent. 
You have to:
   - toggle the ticket
   - Action -> Scroll down to "assign a ticket..."
   - Select -> assign to
   - Select User
   - Select the name of the user...

That's a little bit to complicated and not effective. For my understanding there should be an more easier solution like Open Ticket -> Assign -> Select Username and save. For technical Groups should be the same procedure possible.

### Relevant log output

```shell
Not applicable
```

### Page URL

https://XXX.local/front/dashboard_helpdesk.php

### Steps To reproduce

   - toggle the ticket
   - Action -> Scroll down to "assign a ticket..."
   - Select -> assign to
   - Select User
   - Select the name of the user...

### Your GLPI setup information

Not applicable

### Anything else?

For me a bad GUI which needs improvements is a kind of bug. But it's not a error so I'm not shure how the devs think about this - please let me know.

**Comment by nbriche** [comment]
I'm not sure of your steps? Those are the way to do it if you want to assign the same tech (or group) to more than one ticket at once (hence "mass actions"), so it doesn't really make sense to only select one. For one ticket you already do it the way you described as an easier solution.
GLPI v10 also searches through users and groups at once, so you don't even have to first select "user" or "group", but it's still in beta.
I may have misunderstood something?

**Comment by vollkommenIrrelevant** [comment]
Hello @nbriche 
thank you for your response. If i want to assign one ticket i have to do the same steps (If i get it the right way). I saw that it was improved with glpi v10, so i have to wait if it had been released official.

**Comment by nbriche** [comment]
So you're saying that you can't assign a tech directly in the ticket?

![image](https://user-images.githubusercontent.com/424286/145551467-8225ede8-a8ee-42a9-92aa-9a676900d64f.png)

**Comment by vollkommenIrrelevant** [comment]
Ok, this is a better solution. I didn't get the icon next to "assitgn to" for expand this. But - usability is still a bit complicated, i have to click +, select "user" and then select "username". Thank you for the solution...
