### ISSUE TITLE
Duplicate ranking on renumbering Business Rules for Tickets

### ISSUE THREAD

**Issue by kabassanov** [glpi-project/glpi#9888]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

I imported some Business Rules for Tickets from a xml file as usual and tried to move them from the end to "move before a given rule" (by mass action). After this I saw that some rules were not correctly sorted. So I exported all rules into a file and I was surprised to see duplicate  ranking numbers for several rules. If I try to move some of them again, the operation fails (probably normal).

### Relevant log output

```shell
Didn't find anything related
```

### Steps To reproduce

Not really sure how to reproduce exactly... 

1. Probably, install a set with some rules
2. Add some other rules
3. Move escond set of rules by massive action in the middle of the first one (move them before one in the middle)...

**Comment by kabassanov** [comment]
Just a comment, I don't know if it could be related, but with this action, the number of active rules exceeded 1024...

**Comment by kabassanov** [comment]
After some investigations, it appears that rules we want to move before an other rule (let's call it ref_ID)  get correct ranking number, the ref_ID rule, we moved other rules before, has its ranking number incremented correctly, but rules that had to be pushed between the old ref_ID rank and the new ref_ID rank keep the same rank as ref_ID... 

Example: We want to move rules with rank 1039-1050 before rule with rank 344.

We get:
1039-1050 become 344-355
344 becomes 356 
345 - 355 become 356  (bug)

**Comment by kabassanov** [comment]
Well, take a look at this:

[sql:DBmysqlIterator:private] => SELECT `id`, `ranking` FROM `glpi_rules` WHERE `sub_type` = 'RuleTicket' AND (`ranking` IN ('=>', '683')) AND (`ranking` < '1053')

This is the result of the following code from the moveRule function in rulecollection.class.php:

         // Move forward all rule  between old and new rank
         $iterator = $DB->request([
            'SELECT' => ['id', 'ranking'],
            'FROM'   => 'glpi_rules',
            'WHERE'  => [
               'sub_type'  => $this->getRuleClassName(),
               ['ranking'  => ['=>', $rank]],
               ['ranking'  => ['<', $old_rank]]
            ]
         ]);

This is proably a parse error of "=>" , sequence not treated as arithmetic operator. In glpi arithmetic definition  there is only ">=".

Any comment?

**Comment by cedric-anne** [comment]
Hi,

You are right, there is a typo here. Will be fixed by #9909 .

Thanks for your precise analysis.

Regards
