### ISSUE TITLE
Rework plugins administration

### ISSUE THREAD

**Issue by trasher** [glpi-project/glpi#989]
Once a plugin has been installed, we have to find it again in the list and then enable it (and the list may be quite huge, esppecially for developpers :p).

Maybe should we add after installation an anchor on the table line, and some CSS; to find and enable quickly recently installed plugin.

What do you think?

**Comment by tomolimo** [comment]
Or we may manage plugin list as any other item list with a search query?

**Comment by ddurieux** [comment]
Or split list in 4:
* enabled
* installed
* to update
* not installed

**Comment by remicollet** [comment]
We really need massive action, to be able (at least) to enable all available plugins

**Comment by trasher** [comment]
I agree with you all :-]

That will be a biggest work that my first proposal, but that would be far better!

Maybe we can consider the plugins page as other pages (like assets), and add a search box, massive actions, and a color code for different states.

If the list can be ordered, the split would not be required (and that should be ordred by state per default).

**Comment by ddurieux** [comment]
So yes with search engine like @tomolimo has proposed

**Comment by Stoatwblr** [comment]
I'd add a suggestion that the buttons be colour-coded. On a long list it becomes hard to see the difference between "enable" and "disable"

**Comment by cedric-anne** [comment]
Hi,

Plugin page is now using search engine in 9.4 (done in #4802). I close thie issue.

Regards
