### ISSUE TITLE
can't add a document from an tiem (0.85 and 0.90)

### ISSUE THREAD

**Issue by yllen** [glpi-project/glpi#99]

**Comment by remicollet** [comment]
Idem

**Comment by yllen** [comment]
Try again tody and it's OK now.

**Comment by remicollet** [comment]
Still same issue

**Comment by remicollet** [comment]
debug ($_POST, $_GET, $_FILES)

  From /work/GLPI/master/front/fileupload.php line 48 
  Array
  (
      [entities_id] => 0
      [is_recursive] => 0
      [name] => Tete
      [current_filepath] => 
      [current_filename] => 
      [documentcategories_id] => 0
      [link] => 
      [comment] => 
      [mime] => 
      [is_blacklisted] => 0
      [upload_file] => 
      [_read_date_mod] => 2015-09-04 19:36:15
      [id] => 1
      [_glpi_csrf_token] => c6a61172440beb6b892162e3ff7e2fd4
  )
  Array
  (
      [name] => filename
      [showfilesize] => 1
  )
  Array
  (
      [filename] => Array
          (
              [name] => Array
                  (
                      [0] => bmw.jpg
                  )
  
              [type] => Array
                  (
                      [0] => image/jpeg
                  )
  
              [tmp_name] => Array
                  (
                      [0] => /tmp/phpbeMrTq
                  )
  
              [error] => Array
                  (
                      [0] => 0
                  )
  
              [size] => Array
                  (
                      [0] => 156093
                  )
  
          )
  
  )
  
debug ($esponse)

  From /work/GLPI/master/front/fileupload.php line 111 (0.001", 2.54Mio)
  Array
  (
      [filename] => Array
          (
              [0] => stdClass Object
                  (
                      [name] => bmw (8).jpg
                      [size] => 156093
                      [type] => image/jpeg
                      [url] => http://php54scl/glpi090/front/files/bmw%20%288%29.jpg
                      [deleteUrl] => http://php54scl/glpi090/front/?filenam=bmw%20%288%29.jpg
                      [deleteType] => DELETE
                      [display] => bmw (8).jpg 152.43 Kio
                      [filesize] => 152.43 Kio
                      [id] => docfilename2026246386
                  )
  
          )
  
  )

**Comment by remicollet** [comment]
With https://github.com/blueimp/jQuery-File-Upload/pull/3326/files
Everything works as expected.
