### ISSUE TITLE
BusinessRules for Tickets "Status is Solved" and Processing ticket trough Solution

### ISSUE THREAD

**Issue by VladoTTX** [glpi-project/glpi#9907]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Business rules for Tickets with condition **Status is Solved** AND **any other conditions** is not evaluating properly if state of ticket is changed as result of "Processing Ticket" flow. 

Instead rule matches and Action is executed when:
- State of ticket is changed directly adjusting "State" dropdown rule matches.
- Also if there is only one condition in rule: "state is Solved"

Looks like a bug which is related to action of Processing Ticket -> "Solution" workflow.

### Steps To reproduce

**How to reproduce:**
1. Create Business rule for tickets with example following conditions (at least 2 one of which is not state):
- Logical operator: add
- Use rule for: Add/Update
- Condition:
    - Status "is" Solved
    - title "contains" XXX
- Action:
   - Watcher assign "yourself"

2. Create ticket with title containing XXX in title
Go to Processing ticket ->Solution. Fill in "Solution Type" and Description. Click "+Add".

**Result:**
Ticket state is changed to Solved but rule is not matched/Action not executed

### Your GLPI setup information

Clean setup of 9.5.6 without plugins

**Comment by VladoTTX** [comment]
I found what is the problem, but I am not sure about the correct fix.
Processing Ticket calls update with just "status" field in input array. Business rules works on input array so they do not see other parameters I would need to match.
Maybe other fields should be copied to "input" (at least those for which BR criteria exist)?

**Comment by trasher** [comment]
I did not check in the code, but from your explanations; yes I guess the existing data would be also passed to the rules. 

Please open a pull request with the change proposal.

**Comment by VladoTTX** [comment]
Problem exist on several places which call Ticket::update() directly like ITILSolution, ITILFollowup and might be elsewhere..
It is cased by fact that just parameters "id" and "status" are passed to the update function.
I can imagine similar bug to affect various fields updated this way, not just this one with "status".

This causes BR not matching criteria which are defined on other fields (like title, content and others) as Ticket::prepareInputForUpdate() works just with $input and BR works also just with $input passed to it from Ticket::prepareInputForUpdate().
Question is where to place the fix. 
Whether it should be in Ticket::prepareInputForUpdate() or Rules directly.
And how to fix properly:
 - copy fields which are used in Rules criteria to the $input 
 - or all the $fields should be copied
 - make BR to handle $fields also?

**Comment by VladoTTX** [comment]
I would do following in ticket.class.php. Just copy over the non-existing fields to input in loop which creates $changes.
For me this fixes described problem.

--- ticket.class.php.20220204	2022-02-04 23:06:37.322015773 +0100
+++ ticket.class.php	2022-02-04 23:09:16.000472836 +0100
@@ -1068,6 +1068,8 @@
                 || ($DB->escape($this->fields[$key]) != $input[$key])) {
                $changes[] = $key;
             }
+	 } elseif(isset($this->fields[$key]) && !isset($input[$key])){
+                $input[$key] = $this->fields[$key];
          }
       }

**Comment by needim** [comment]
> I would do following in ticket.class.php. Just copy over the non-existing fields to input in loop which creates $changes. For me this fixes described problem.
> 
> ```
> --- ticket.class.php.20220204	2022-02-04 23:06:37.322015773 +0100
> +++ ticket.class.php	2022-02-04 23:09:16.000472836 +0100
> @@ -1068,6 +1068,8 @@
>                  || ($DB->escape($this->fields[$key]) != $input[$key])) {
>                 $changes[] = $key;
>              }
> +	 } elseif(isset($this->fields[$key]) && !isset($input[$key])){
> +                $input[$key] = $this->fields[$key];
>           }
>        }
>  
> ```

this patch is worked for me also.

**Comment by VladoTTX** [comment]
If you would like to use it, rather use this one, where input is cleaned after rules are finished and also field data are escaped: 
```
--- ticket.class.php.20220204	2022-02-04 23:06:37.322015773 +0100
+++ ticket.class.php	2022-02-04 23:09:16.000472836 +0100
@@ -1068,6 +1068,8 @@
                 || ($DB->escape($this->fields[$key]) != $input[$key])) {
                $changes[] = $key;
             }
+	 } elseif(isset($this->fields[$key]) && !isset($input[$key])){
+                $input[$key] = $DB->escape($this->fields[$key]);
+                $tocleanafterrules[$key] = $DB->escape($this->fields[$key]);
          }
       }
```
