### ISSUE TITLE
GLPI 10 : bad contrast in confirmation toast (blue) with auror darkheme

### ISSUE THREAD

**Issue by btry** [glpi-project/glpi#9914]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Version

10.0

### Bug description

Toasts are hard to read with Auror dark theme

- title
- hyperlink

![image](https://user-images.githubusercontent.com/14139801/142862470-7ee20637-d636-4b32-bdac-72349efadd37.png)

### Relevant log output

```shell
none
```

### Steps To reproduce

Use default Auror theme
go in personal settings, switch to Auror dark
A confirmation  toast appears after page reload. Theme is applied, and the toast is partially unreadable

**Comment by btry** [comment]
Also same kind of issue with debug buttons

![image](https://user-images.githubusercontent.com/14139801/142864976-50cfe370-512a-4001-9034-475fb8c1cff6.png)

**Comment by cconard96** [comment]
I tested all these cases on the latest master branch and they all seem to be resolved now.
Most or all of these fixes may have been fixed within Tabler itself.
