### ISSUE TITLE
Name or Serial number "123e456"  displayed as "inf"

### ISSUE THREAD

**Issue by mathieumd** [glpi-project/glpi#9917]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

The value of `Name` and `Serial Number` of *Phone Equipment* is interpreted when displayed in item listing.

Serial number value of `123E456` is displayed as `inf` (instead of `123E456`, obviously).

**Comment by cedric-anne** [comment]
Hi,

I think it should be fixed by #9570.

Regards

**Comment by mathieumd** [comment]
OK
