### ISSUE TITLE
Increase the usage of expressions with combined operators

### ISSUE THREAD

**Issue by elfring** [glpi-project/glpi#9927]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

Extra memory allocations

### Steps To reproduce

:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of combined operators](https://www.php.net/manual/en/language.operators.assignment.php#language.operators.assignment.arithmetic "Description for assignment operators") accordingly.

### Anything else?

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal> perl -p -i.orig -0777 -e 's#(?<target>\$\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+/%^.]|-(?!>)|&(?!&)|\|(?!\|)|\*\*?|<<|>>|\?\?)#$+{target} $+{operator}=#gm' $(find ~/Aktivitäten/GLPI/lokal -name '*.php')
```

:crystal_ball: How will development interests evolve further also according to update candidates in 69 lines of this software?

**Comment by cconard96** [comment]
Having an issue open for this does not seem helpful and the change is purely a personal preference. There should be no difference between "a = a + b" and "a += b" in terms of functionality or performance. There is no rule that enforces one form over the other in our coding standards.

**Comment by elfring** [comment]
>… There should be no difference between "a = a + b" and "a += b" in terms of … or performance. …

I came along other impressions and expectations for desirable software run time characteristics.
