### ISSUE TITLE
Uncaught Exception Error: Call to undefined function ldap_connect()

### ISSUE THREAD

**Issue by adminraz** [glpi-project/glpi#9930]
### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6 

### Bug description

Hello I need your help please I have configured the cron task correctly, switched to cli mode in glpi, but the task still does not work.
But connection information are good, because when I click manually on the mail collection it works very well.
no mail is collected even though the task is running 
thank for your help

### Relevant log output

```shell
[2021-11-23 18:40:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function ldap_connect() in /var/www/html/glpi/inc/authldap.class.php at line 2637
  Backtrace :
  inc/authldap.class.php:2618                        AuthLDAP::connectToServer()
  inc/authldap.class.php:2477                        AuthLDAP->connect()
  inc/user.class.php:4495                            AuthLDAP::ldapImportUserByServerId()
  inc/mailcollector.class.php:1052                   User::getOrImportByEmail()
  inc/mailcollector.class.php:758                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1755                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()

[2021-11-23 18:41:02] glpiphplog.CRITICAL:   *** Uncaught Exception Error: Call to undefined function ldap_connect() in /var/www/html/glpi/inc/authldap.class.php at line 2637
  Backtrace :
  inc/authldap.class.php:2618                        AuthLDAP::connectToServer()
  inc/authldap.class.php:2477                        AuthLDAP->connect()
  inc/user.class.php:4495                            AuthLDAP::ldapImportUserByServerId()
  inc/mailcollector.class.php:1052                   User::getOrImportByEmail()
  inc/mailcollector.class.php:758                    MailCollector->buildTicket()
  inc/mailcollector.class.php:1755                   MailCollector->collect()
  inc/crontask.class.php:943                         MailCollector::cronMailgate()
  front/cron.php:83                                  CronTask::launch()
```

### Your GLPI setup information

<html>
<body>

Operating system: Linux ***** 4.9.0-11-amd64 #1 SMP Debian 4.9.189-3+deb9u2 (2019-11-11) x86_64 PHP 8.0.13 apache2handler (Core, FFI, PDO, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bz2, calendar, 	ctype, curl, date, dom, exif, fileinfo, filter, ftp, gd, gettext, hash, iconv, imagick, imap, intl, json, ldap, libxml, 	mbstring, memcache, mysqli, mysqlnd, openssl, pcre, pdo_mysql, posix, readline, session, shmop, sockets, sodium, standard, 	sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="30" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.25 (Debian) (Apache/2.4.25 (Debian) Server at ****** Port 80) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Server Software: Debian 9.13 	Server Version: 10.1.48-MariaDB-0+deb9u2 	Server SQL Mode:  	Parameters: glpiuser@localhost/glpi 	Host info: Localhost via UNIX socket 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.1.48) - Perfect!  The log file has been created successfully. Write access to /var/www/html/glpi/files/_cache has been validated. Write access to /var/www/html/glpi/config has been validated. Write access to /var/www/html/glpi/files/_cron has been validated. Write access to /var/www/html/glpi/files has been validated. Write access to /var/www/html/glpi/files/_dumps has been validated. Write access to /var/www/html/glpi/files/_graphs has been validated. Write access to /var/www/html/glpi/files/_lock has been validated. Write access to /var/www/html/glpi/files/_pictures has been validated. Write access to /var/www/html/glpi/files/_plugins has been validated. Write access to /var/www/html/glpi/files/_rss has been validated. Write access to /var/www/html/glpi/files/_sessions has been validated. Write access to /var/www/html/glpi/files/_tmp has been validated. Write access to /var/www/html/glpi/files/_uploads has been validated. Write access to /var/www/html/glpi/marketplace has been validated. Web access to the files directory should not be allowed Check the .htaccess file and the web server configuration.
--

GLPI_ROOT: /var/www/html/glpi GLPI_CONFIG_DIR: /var/www/html/glpi/config GLPI_VAR_DIR: /var/www/html/glpi/files GLPI_MARKETPLACE_DIR: /var/www/html/glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: /var/www/html/glpi/files GLPI_CACHE_DIR: /var/www/html/glpi/files/_cache GLPI_CRON_DIR: /var/www/html/glpi/files/_cron GLPI_DUMP_DIR: /var/www/html/glpi/files/_dumps GLPI_GRAPH_DIR: /var/www/html/glpi/files/_graphs GLPI_LOCAL_I18N_DIR: /var/www/html/glpi/files/_locales GLPI_LOCK_DIR: /var/www/html/glpi/files/_lock GLPI_LOG_DIR: /var/www/html/glpi/files/_log GLPI_PICTURE_DIR: /var/www/html/glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: /var/www/html/glpi/files/_plugins GLPI_RSS_DIR: /var/www/html/glpi/files/_rss GLPI_SESSION_DIR: /var/www/html/glpi/files/_sessions GLPI_TMP_DIR: /var/www/html/glpi/files/_tmp GLPI_UPLOAD_DIR: /var/www/html/glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: /var/www/html/glpi/locales GLPI_VERSION: 9.5.6 GLPI_SCHEMA_VERSION: 9.5.6 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

 

</body>
</html>

### Anything else?

![image](https://user-images.githubusercontent.com/94925246/143076413-d4b20fcc-432c-48b6-b3c1-87ba21008699.png)

**Comment by cedric-anne** [comment]
Hi,

It seems that, in the execution context you use, the LDAP extension is not loaded. Fixing your PHP configuration should solve this issue.

Regards

**Comment by cconard96** [comment]
PHP has different configurations for the web server and CLI so you need to check that the `ldap` extension (and all other required extensions) are loaded in CLI mode.

You can run `bin/console glpi:system:check_requirements` command from root of your GLPI instance to check the requirements and ensure all the needed extensions are loaded.
