### ISSUE TITLE
Automaticaly change pending status to atributed

### ISSUE THREAD

**Issue by cyrakuse** [glpi-project/glpi#9938]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

When we have a ticket in "pending" status, this ticket does not change to "attributed" status automaticaly when the user send a new message on it.

### Steps To reproduce

1. with a tech profile, change the status of a ticket to "pending"
2. with the user profile, send a new message in the ticket
3. the ticket stay in status "pending" and does not change to "attributed" status

### Your GLPI setup information

<html>
<body>

GLPI 9.5.6 (/en_Test/Glpi => D:\www\en_Test\Glpi) Installation mode: TARBALL
--

Operating system: Windows NT PCPORT-HP-BDAN 10.0 build 19044 (Windows 10) AMD64 PHP 7.4.26 apache2handler (Core, PDO, PDO_OCI, Phar, Reflection, SPL, SimpleXML, Zend OPcache, apache2handler, apcu, bcmath, 	bz2, calendar, com_dotnet, ctype, curl, date, dom, exif, fileinfo, filter, gd, gettext, gmp, hash, iconv, imap, intl, json, 	ldap, libxml, mbstring, mysqli, mysqlnd, oci8, openssl, pcre, pdo_mysql, pdo_sqlite, readline, session, snmp, soap, sockets, 	sodium, sqlite3, standard, tokenizer, xdebug, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, zlib) Setup: max_execution_time="120" memory_limit="128M" post_max_size="8M" safe_mode="" session.save_handler="files" 	upload_max_filesize="2M"  Software: Apache/2.4.46 (Win64) mod_authnz_sspi/0.1.1 OpenSSL/1.1.1g PHP/7.4.26 (Apache/2.4.46 (Win64) mod_authnz_sspi/0.1.1 	OpenSSL/1.1.1g PHP/7.4.26 Server at localhost Port 8080) 	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36 Server Software: mariadb.org binary distribution 	Server Version: 10.4.13-MariaDB 	Server SQL Mode:  	Parameters: root@localhost/glpi 	Host info: localhost via TCP/IP 	 PHP version is at least 7.2.0 - Perfect! Sessions support is available - Perfect! Allocated memory > 64 Mio - Perfect! mysqli extension is installed ctype extension is installed fileinfo extension is installed json extension is installed mbstring extension is installed iconv extension is installed zlib extension is installed curl extension is installed gd extension is installed simplexml extension is installed intl extension is installed ldap extension is installed apcu extension is installed Zend OPcache extension is installed xmlrpc extension is installed exif extension is installed zip extension is installed bz2 extension is installed sodium extension is installed Database version seems correct (10.4.13) - Perfect! Timezones seems loaded in database The log file has been created successfully. Write access to D:\www\en_Test\Glpi/files/_cache has been validated. Write access to D:\www\en_Test\Glpi/config has been validated. Write access to D:\www\en_Test\Glpi/files/_cron has been validated. Write access to D:\www\en_Test\Glpi/files has been validated. Write access to D:\www\en_Test\Glpi/files/_dumps has been validated. Write access to D:\www\en_Test\Glpi/files/_graphs has been validated. Write access to D:\www\en_Test\Glpi/files/_lock has been validated. Write access to D:\www\en_Test\Glpi/files/_pictures has been validated. Write access to D:\www\en_Test\Glpi/files/_plugins has been validated. Write access to D:\www\en_Test\Glpi/files/_rss has been validated. Write access to D:\www\en_Test\Glpi/files/_sessions has been validated. Write access to D:\www\en_Test\Glpi/files/_tmp has been validated. Write access to D:\www\en_Test\Glpi/files/_uploads has been validated. Write access to D:\www\en_Test\Glpi/marketplace has been validated. Web access to the files directory should not be allowed but this cannot be checked automatically on this instance. Make sure access to error log file (/en_Test/Glpi/files/_log/php-errors.log) is forbidden; otherwise review .htaccess file and web server configuration.

GLPI_ROOT: D:\www\en_Test\Glpi GLPI_CONFIG_DIR: D:\www\en_Test\Glpi/config GLPI_VAR_DIR: D:\www\en_Test\Glpi/files GLPI_MARKETPLACE_DIR: D:\www\en_Test\Glpi/marketplace GLPI_USE_CSRF_CHECK: 1 GLPI_CSRF_EXPIRES: 7200 GLPI_CSRF_MAX_TOKENS: 100 GLPI_USE_IDOR_CHECK: 1 GLPI_IDOR_EXPIRES: 7200 GLPI_ALLOW_IFRAME_IN_RICH_TEXT:  GLPI_TELEMETRY_URI: https://telemetry.glpi-project.org GLPI_INSTALL_MODE: TARBALL GLPI_NETWORK_MAIL: glpi@teclib.com GLPI_NETWORK_SERVICES: https://services.glpi-network.com GLPI_MARKETPLACE_PRERELEASES:  GLPI_MARKETPLACE_ALLOW_OVERRIDE: 1 GLPI_MARKETPLACE_MANUAL_DOWNLOADS: 1 GLPI_USER_AGENT_EXTRA_COMMENTS:  GLPI_AJAX_DASHBOARD: 1 GLPI_CALDAV_IMPORT_STATE: 0 GLPI_DEMO_MODE: 0 GLPI_FORCE_EMPTY_SQL_MODE: 1 GLPI_DOC_DIR: D:\www\en_Test\Glpi/files GLPI_CACHE_DIR: D:\www\en_Test\Glpi/files/_cache GLPI_CRON_DIR: D:\www\en_Test\Glpi/files/_cron GLPI_DUMP_DIR: D:\www\en_Test\Glpi/files/_dumps GLPI_GRAPH_DIR: D:\www\en_Test\Glpi/files/_graphs GLPI_LOCAL_I18N_DIR: D:\www\en_Test\Glpi/files/_locales GLPI_LOCK_DIR: D:\www\en_Test\Glpi/files/_lock GLPI_LOG_DIR: D:\www\en_Test\Glpi/files/_log GLPI_PICTURE_DIR: D:\www\en_Test\Glpi/files/_pictures GLPI_PLUGIN_DOC_DIR: D:\www\en_Test\Glpi/files/_plugins GLPI_RSS_DIR: D:\www\en_Test\Glpi/files/_rss GLPI_SESSION_DIR: D:\www\en_Test\Glpi/files/_sessions GLPI_TMP_DIR: D:\www\en_Test\Glpi/files/_tmp GLPI_UPLOAD_DIR: D:\www\en_Test\Glpi/files/_uploads GLPI_NETWORK_REGISTRATION_API_URL: https://services.glpi-network.com/api/registration/ GLPI_MARKETPLACE_PLUGINS_API_URI: https://services.glpi-network.com/api/glpi-plugins/ GLPI_I18N_DIR: D:\www\en_Test\Glpi/locales GLPI_VERSION: 9.5.6 GLPI_SCHEMA_VERSION: 9.5.6 GLPI_MIN_PHP: 7.2.0 GLPI_YEAR: 2021

htmlawed/htmlawed version 1.2.5 in (D:\www\en_Test\Glpi\vendor\htmlawed\htmlawed) phpmailer/phpmailer version 6.1.6 in (D:\www\en_Test\Glpi\vendor\phpmailer\phpmailer\src) simplepie/simplepie version 1.5.6 in (D:\www\en_Test\Glpi\vendor\simplepie\simplepie\library) tecnickcom/tcpdf version 6.3.5 in (D:\www\en_Test\Glpi\vendor\tecnickcom\tcpdf) michelf/php-markdown in (D:\www\en_Test\Glpi\vendor\michelf\php-markdown\Michelf) true/punycode in (D:\www\en_Test\Glpi\vendor\true\punycode\src) iamcal/lib_autolink in (D:\www\en_Test\Glpi\vendor\iamcal\lib_autolink) sabre/dav in (D:\www\en_Test\Glpi\vendor\sabre\dav\lib\DAV) sabre/http in (D:\www\en_Test\Glpi\vendor\sabre\http\lib) sabre/uri in (D:\www\en_Test\Glpi\vendor\sabre\uri\lib) sabre/vobject in (D:\www\en_Test\Glpi\vendor\sabre\vobject\lib) laminas/laminas-cache in (D:\www\en_Test\Glpi\vendor\laminas\laminas-cache\src) laminas/laminas-i18n in (D:\www\en_Test\Glpi\vendor\laminas\laminas-i18n\src) laminas/laminas-serializer in (D:\www\en_Test\Glpi\vendor\laminas\laminas-serializer\src) monolog/monolog in (D:\www\en_Test\Glpi\vendor\monolog\monolog\src\Monolog) sebastian/diff in (D:\www\en_Test\Glpi\vendor\sebastian\diff\src) elvanto/litemoji in (D:\www\en_Test\Glpi\vendor\elvanto\litemoji\src) symfony/console in (D:\www\en_Test\Glpi\vendor\symfony\console) scssphp/scssphp in (D:\www\en_Test\Glpi\vendor\scssphp\scssphp\src) laminas/laminas-mail in (D:\www\en_Test\Glpi\vendor\laminas\laminas-mail\src\Protocol) laminas/laminas-mime in (D:\www\en_Test\Glpi\vendor\laminas\laminas-mime\src) rlanvin/php-rrule in (D:\www\en_Test\Glpi\vendor\rlanvin\php-rrule\src) blueimp/jquery-file-upload in (D:\www\en_Test\Glpi\vendor\blueimp\jquery-file-upload\server\php) ramsey/uuid in (D:\www\en_Test\Glpi\vendor\ramsey\uuid\src) psr/log in (D:\www\en_Test\Glpi\vendor\psr\log\Psr\Log) psr/simple-cache in (D:\www\en_Test\Glpi\vendor\psr\simple-cache\src) mexitek/phpcolors in (D:\www\en_Test\Glpi\vendor\mexitek\phpcolors\src\Mexitek\PHPColors) guzzlehttp/guzzle in (D:\www\en_Test\Glpi\vendor\guzzlehttp\guzzle\src) guzzlehttp/psr7 in (D:\www\en_Test\Glpi\vendor\guzzlehttp\psr7\src) wapmorgan/unified-archive in (D:\www\en_Test\Glpi\vendor\wapmorgan\unified-archive\src) paragonie/sodium_compat in (D:\www\en_Test\Glpi\vendor\paragonie\sodium_compat\src)

news                 Name: Alertes                        Version: 1.9.0      State: Enabled 	databases            Name: Bases de données               Version: 2.3.2      State: Enabled 	screenshot           Name: Capture d'écran                Version: 1.1.6      State: Enabled 	fields               Name: Champs supplémentaires         Version: 1.12.8     State: Enabled 	airwatch             Name: Connecteur Airwatch pour GLPi  Version: 1.5.0      State: Enabled 	datainjection        Name: Data Injection                 Version: 2.9.0      State: Enabled 	escalade             Name: Escalades                      Version: 2.7.1      State: Enabled 	useditemsexport      Name: Export des éléments utilisés   Version: 2.4.0      State: Enabled 	dataflows            Name: Flux de données                Version: 2.2.4      State: Installed / not activated 	formcreator          Name: Form Creator                   Version: 2.12.3     State: Enabled 	fusioninventory      Name: FusionInventory                Version: 9.5+3.0    State: Enabled 	geninventorynumber   Name: Génération de numéros d'invent Version: 2.5.0      State: Enabled 	genericobject        Name: Gestion d'objets               Version: 2.11.0     State: Enabled 	mreporting           Name: Plus de rapports               Version: 1.7.3      State: Enabled 	satisfaction         Name: Plus de satisfaction           Version: 1.5.2      State: Enabled 	archisw              Name: Structures d'Applications      Version: 2.2.6      State: Installed / not activated
[/code]

</body>
</html>

**Comment by trasher** [comment]
Please write in english only.

**Comment by cyrakuse** [comment]
Sorry. translated in english
