### ISSUE TITLE
View problem when viewing item from mail queue

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#996]
Dear all,

GLPi: 9.1 RC2
IE10

There is a view problem when viewing an email in the mail queue: the vertical scroll bar doesn't show-up when IE10 is in full screen **and** when own settings are with the 'split view'. 

![image](https://cloud.githubusercontent.com/assets/7569958/18579689/89308a38-7bf7-11e6-8545-aad78a123737.png)

If these conditions are not met, the scroll bar is shown:

![image](https://cloud.githubusercontent.com/assets/7569958/18579713/a6b87e12-7bf7-11e6-9b22-fef691762b37.png)

**Comment by trasher** [comment]
I cannot test the proposed fix; I do not have any IE on hand

**Comment by tomolimo** [comment]
I'll do it

**Comment by tomolimo** [comment]
Passed!

**Comment by trasher** [comment]
Thanks :)

**Comment by tomolimo** [comment]
You're welcome
