### ISSUE TITLE
[enhancement][9.1] add notifications for computer status type

### ISSUE THREAD

**Issue by pszafer** [glpi-project/glpi#997]
Hello,

FusionInventory can change computer status type from e.g. 'WORKING' to 'PROBLEMS' or 'NOT REPORTED SINCE 7 DAYS" etc.
Maybe for GLPI 9.1 you can add feature that if FI changed status of computer glpi can send notification that there could be a problem.

**Comment by pszafer** [comment]
anybody?

**Comment by tomolimo** [comment]
Hello 
Could it be reported to the Fusion Inventory plug-in web site. 
As it can be integrated into the plug-in itself. 
Regards 
Tomolimo

**Comment by pszafer** [comment]
I think it would be better if there could be notification for computer status bundled into GLPI.
Then for example user can change status of computer in GLPI and another user can get notification of that.
If it would be implemented in FI plugin it would be only one way of using it. If it would be implemented into GLPI notification you would have more option to improve it in the future (notification for other things like software etc.).
