### ISSUE TITLE
Task category translation problem when sending notifications

### ISSUE THREAD

**Issue by tomolimo** [glpi-project/glpi#999]
Dear all,

There is a weird problem with task category translations when sending a task notification. 
Let's see the following configuration:

- GLPi default language is en_US
- User X language is fr_FR
- User Y language is en_US
- Task Category TC is defined in default and fr_FR languages

Logged in GLPi as User Y (en_US) add a task in a ticket assigning User X as task technician. Define the task category for this task as Task Category TC.

Then User X will receive a notification with task category being in en_US and not in fr_FR.

Thank you,
Regards,
Tomolimo

PS: I'm going to provide a fix for this

**Comment by tomolimo** [comment]
We have also the same kind of troubles with the `getContentHeader()` and `getContentFooter()` which are currently localized with the sender language and not with the target user language

**Comment by tomolimo** [comment]
In fact as far as I can see none of the dropdowns are localized for the target user, but they are for the sender user...

**Comment by tomolimo** [comment]
oups, I should have done a branch for it instead of a commit?

**Comment by trasher** [comment]
Yep, you should create a specific branch and open a PR... Well, as it is quite a recent rule, we can forgive you for the instance :p

**Comment by tomolimo** [comment]
But my problem is not the rule (I knew it), but you may forgive me as I'm a newbie with GitHub :cry:

**Comment by trasher** [comment]
@tomolimo no problem ;)

Just for information:
The github way of doing this is to create a specific branch on your own fork for each PR you want to open; you'll see a button (on glpi repo page or on your fork page) once the branch has been pushed.

You can still use master from the main repo (origin), and add another remote to your git repository; that is what I personaly do to create quickly branches from glpi/master an push it to my fork.

Do not hesitate to ask us for help if you need; git is powerfull, but can be quite complex, an github is specific too!

**Comment by tomolimo** [comment]
thank you

**Comment by trasher** [comment]
And, talking about the changes... Should not the $_SESSION['language'] changes done in the Session class? It seems more appropriate place (and will cover everything, not just notifications).
The part for the dorpdowns is maybe too specific, I'm unsure for this one.

**Comment by tomolimo** [comment]
Yes, it would be cleaner to do it another way, but it really would be huge work, as it would impact all the Dropdown::getDropdownName() and getTreeValueCompleteName() calls, where the $_SESSION['glpilanguage'] is used....

**Comment by tomolimo** [comment]
One more question: should we cherry pick this to push it to 0.90.x?

**Comment by orthagh** [comment]
for cherry-pick, we can do it.
I'm not sure we'll release a new 0.90 version, but if we do, this fix will be welcome
