### ISSUE TITLE
Request approval redirects to blank page

### ISSUE THREAD

**Issue by Leczo** [glpi-project/glpi#9999]
### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version

9.5.6

### Bug description

After granting an approval to related request by clicking save button, GLPI redirects to a blank page. Besides that, approval is granted but this redirection is inconvenient. 

![image](https://user-images.githubusercontent.com/35179677/144261092-4f322530-74d4-4afe-b3e4-3573a7ff4fad.png)

![image](https://user-images.githubusercontent.com/35179677/144261188-1c5e0f32-0e93-439a-8ff5-67f841f0d027.png)

![image](https://user-images.githubusercontent.com/35179677/144261233-e3dda072-3606-426b-8bbb-51cac6300617.png)

![image](https://user-images.githubusercontent.com/35179677/144261347-b0945ced-db4a-4b18-86d9-936b83786d34.png)

### Steps To reproduce

1. Open any kind of ticket
2. Create an approval request
3. Grant an approval to this request by changing "Status of my Validation" to  "Granted" and clicking save button

**Comment by cconard96** [comment]
Please include your GLPI system information from Setup > General on the System tab, and any related output in the GLPI logs `files/_log/php-errors.log` and `files/_log/sql-errors.log`.

**Comment by trasher** [comment]
No feedback from a while, closing.

**Comment by namtarkur** [comment]
In GLPI version 10.0.10 this issue still appears. Adding screenshot of php-errors.log file and from browser.
![screenshoot02](https://github.com/glpi-project/glpi/assets/24360197/d903884a-093e-44e1-9d73-14f518c5723c)
![screenshoot01](https://github.com/glpi-project/glpi/assets/24360197/4c8bc8aa-7aeb-4f82-80d7-0c90aa99f3b8)

**Comment by cedric-anne** [comment]
@namtarkur 

Please open a new issue with all the requested information.
